### ISSUE TITLE
Prefetching not working for optional catch all routes in Firefox

### ISSUE THREAD

**Issue by samrobbins85** [vercel/next.js#16866] opened 2020-09-05 08:01 UTC
# Bug report

## Describe the bug

When using `next/link` for optional catch all routes, it is prefetched in Chrome but not in Firefox

## To Reproduce

The code can be found in https://github.com/samrobbins85/nextjs-bug-mwe, it is hosted at https://nextjs-bug-mwe.vercel.app/

This bug can also be seen in the Next.js docs

## Expected behavior

The file `working.json` should be prefetched. In general, links with `next/link` should be prefetched

## Screenshots

Firefox network logs:
![image](https://user-images.githubusercontent.com/29740136/92300823-eca95380-ef55-11ea-8a4a-7a87a4324930.png)

Chrome network logs:
![image](https://user-images.githubusercontent.com/29740136/92300826-f8951580-ef55-11ea-8075-2b2200cc6b45.png)

Note that `working.json` is in the Chrome log but not the Firefox one, it is only loaded when actually clicking the link

## System information

- OS: Linux
- Browser (if applies): Firefox 80.0.1
- Version of Next.js: 9.5.3
- Version of Node.js: not sure, hosted on Vercel

**Comment by stefanprobst** [comment] 2020-09-05 19:50
what is your`network.prefetch-next` setting in firefox?

**Comment by samrobbins85** [comment] 2020-09-06 08:00
Turns out this was it, thanks very much! Is this disabled by default in Firefox? I don't remember disabling this

**Comment by stefanprobst** [comment] 2020-09-06 08:05
i have run into a similar issue and for me it was caused by "ublock origin" addon default settings. see my comment [here](https://github.com/vercel/next.js/discussions/11578#discussioncomment-51258)

**Comment by samrobbins85** [comment] 2020-09-06 08:07
Oh that's annoying, thanks very much for your help though!

**Comment by samrobbins85** [comment] 2020-09-06 08:41
Sorry for reopening this. On Firefox I'm often getting a prefetch of around 500 bytes, not showing any response, and not having the effect of prefetching, but on Chrome they're in the order of kilobytes, with the response showing the data from the page. Is this a uBlock Origin thing too?

**Comment by ijjk** [comment] 2020-12-01 19:41
Hi, I'm going to close this as data prefetching has been changed in the latest version and it appears to be working correctly in Firefox as shown in the below screenshot. To ensure issues you are experiencing aren't related to extensions, you can try disabling them and see if they can be reproduced without in the future. 
 
<img width="1396" alt="Screen Shot 2020-12-01 at 1 40 22 PM" src="https://user-images.githubusercontent.com/22380829/100788499-c5d6ae00-33da-11eb-82fa-dc3d652bfd31.png">

**Closed by ijjk** 2020-12-01 19:41 UTC

**Comment by balazsorban44** [comment] 2022-01-29 02:12
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
