### ISSUE TITLE
Nextjs+graylog

### ISSUE THREAD

**Issue by Manikanta-20** [vercel/next.js#12917] opened 2020-05-15 12:06 UTC
# Feature request

Nextjs will support graylog

**Comment by sai1139** [comment] 2020-05-15 12:11
@timneutkens  it should other logger configuration support pino or winston

**Comment by zurez** [comment] 2020-05-16 22:38
@timneutkens  I am new to open source, I would like to resolve this issue. Can you please guide?

**Comment by sai1139** [comment] 2020-06-03 12:59
@timneutkens  can you add this request in 9.5?

**Comment by davscro** [comment] 2020-12-22 15:23
Any progress on this one? I am also able to help here.

**Comment by timneutkens** [comment] 2021-01-03 14:01
Closing as no PR was opened in 7+ months and no github reactions on the initial issue.

**Closed by timneutkens** 2021-01-03 14:01 UTC
Labels: good first issue

**Comment by balazsorban44** [comment] 2022-01-28 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
