### ISSUE TITLE
NextJS 13 layout re-render when changing route

### ISSUE THREAD

**Issue by LOLBRUHNICE** [vercel/next.js#42164] opened 2022-10-30 02:34 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #100~18.04.1-Ubuntu SMP Mon Oct 17 11:44:30 UTC 2022
    Binaries:
      Node: 16.18.0
      npm: 8.19.2
      Yarn: 3.2.4
      pnpm: 7.14.1
    Relevant packages:
      next: 13.0.1-canary.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

edge 107.0.1418.26

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

the layout component re-render when changing the route

### Expected Behavior

the layout should not re-render

### Link to reproduction

https://codesandbox.io/s/suspicious-bessie-h9wlwe

### To Reproduce

run the dev command, visit the /test route, click the button few times to increase the count, click the "go to id 1/2" button to go to leaf segment, and the count will reset

**Comment by timneutkens** [comment] 2022-11-01 14:49
Had a look at this one and the application is working as expected locally, the problem only surfaces on codesandbox as it's replying with a wrong response. I've reached out to Ives from Codesandbox and they're looking into this, will keep you updated 👍

**Comment by AoverK** [comment] 2022-11-01 22:44
I noticed this issue on my most recent version of nextjs where it renders differently in vercel than on my local machine when running npm run dev.

> ### Verify canary release
> * [x]  I verified that the issue exists in the latest Next.js canary release
> 
> ### Provide environment information
> Operating System: Platform: linux Arch: x64 Version: #100~18.04.1-Ubuntu SMP Mon Oct 17 11:44:30 UTC 2022 Binaries: Node: 16.18.0 npm: 8.19.2 Yarn: 3.2.4 pnpm: 7.14.1 Relevant packages: next: 13.0.1-canary.0 eslint-config-next: 13.0.0 react: 18.2.0 react-dom: 18.2.0
> 
> ### What browser are you using? (if relevant)
> edge 107.0.1418.26
> 
> ### How are you deploying your application? (if relevant)
> next dev
> 
> ### Describe the Bug
> the layout component re-render when changing the route
> 
> ### Expected Behavior
> the layout should not re-render
> 
> ### Link to reproduction
> https://codesandbox.io/s/suspicious-bessie-h9wlwe
> 
> ### To Reproduce
> run the dev command, visit the /test route, click the button few times to increase the count, click the "go to id 1/2" button to go to leaf segment, and the count will reset

**Comment by timneutkens** [comment] 2022-11-02 14:28
> I noticed this issue on my most recent version of nextjs where it renders differently in vercel than on my local machine when running npm run dev.

Can you provide a reproduction?

**Comment by LOLBRUHNICE** [comment] 2022-11-03 13:09
> Had a look at this one and the application is working as expected locally, the problem only surfaces on codesandbox as it's replying with a wrong response. I've reached out to Ives from Codesandbox and they're looking into this, will keep you updated 👍

I also have this issue when run it in my local machine and in github codespace, so i dont think it is the problem from codesandbox?

**Comment by LOLBRUHNICE** [comment] 2022-11-03 13:24
https://user-images.githubusercontent.com/65208589/199731953-d5bb0c83-bb1e-4356-9a5c-f533a2004714.mp4

here's the video of running the reproduction in my github codespace

**Comment by timneutkens** [comment] 2022-11-04 11:40
> I also have this issue when run it in my local machine

Can't reproduce it locally, maybe you have a proxy in front that's stripping `__rsc__` headers. We're planning to change these to no longer have `_` as they're being stripped by nginx.

**Comment by timneutkens** [comment] 2022-11-04 17:14
This is now fixed on codesandbox: https://codesandbox.io/p/sandbox/happy-stallman-tlztle?file=%2Fapp%2Ftest%2F%5Bid%5D%2Fpage.tsx

I've opened a PR to rename the headers to something that wouldn't be stripped: #42164

**Comment by dumbravaandrei22** [comment] 2022-11-06 16:05
Hello!

I have a similar issue.

**With next start:**
It seems that the RootLayout always mounts & unmounts the components inside it on the first-page render.

**With next build + start:**
When navigating via <Link>, my AppContext that is located in the RootLayout gets mounted and mounted again when navigating via <Link>.

**Comment by timneutkens** [comment] 2022-11-06 16:16
@dumbravaandrei22 please provide a full reproduction.

**Comment by dumbravaandrei22** [comment] 2022-11-06 17:18
@timneutkens 

I forked your above codesandbox [here](https://codesandbox.io/p/sandbox/green-cdn-ocy255?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A19%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A19%2C%22startLineNumber%22%3A9%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl8skx9az000nlpgeaw1kc72o%2522%252C%2522openFiles%2522%253A%255B%2522%252Fpackage.json%2522%252C%2522%252Fapp%252Flayout.tsx%2522%252C%2522%252Fapp%252FFooComponent.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cla5m94yf048o3b6hzyluvlra%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cla5m8j8u045z3b6h76oh1hus%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D).


I've created FooCoomponent.tsx:

Please see the browser logs:

![image](https://user-images.githubusercontent.com/14004579/200185033-b9686ade-6576-462f-93c9-b1d2ee4be63c.png)

**Closed** 2022-11-08 00:35 UTC
Labels: type: upstream, area: app

**Comment by timneutkens** [comment] 2022-11-08 09:08
1. That's because of React Strict Mode: https://reactjs.org/docs/strict-mode.html
2. The Foo component is part of the layout so it doesn't rerender when you navigate a sub-layout

**Comment by dumbravaandrei22** [comment] 2022-11-12 11:22
@timneutkens Thank you! I managed to solve the issues.
I deactivated the strict mode [https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode](https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode)
