### ISSUE TITLE
3x more network requests and latency issue on the same project after version upgrade

### ISSUE THREAD

**Issue by gabor-at-reed** [vercel/next.js#51653] opened 2023-06-22 14:39 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed May 24 23:46:10 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.7
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Link to the code that reproduces this issue or a replay of the bug

-

### To Reproduce

We have a containerised (Docker) Next.js app running on the Kubernetes environment. Hence we need to map the requests from the real world into the container to the app. Monitoring-wise, we use Datadog. 

Till now, we used to use Next.js v12.x, but now we upgraded the project to the latest v13.4.7. After the version upgrade, the network traffic/requests and the latency increased enormously. We have not changed anything in our codebase or infrastructure or anything else; we just upgraded the Next.js version.

### Describe the Bug

With Next.js v12 we got these traces for a request, which is normal:
![image](https://github.com/vercel/next.js/assets/1906302/df9e00fd-ab24-49ad-9485-5f3d07e9ef35)

But when we upgraded to the latest `v13.4.7`, we got this for the same request:
![image](https://github.com/vercel/next.js/assets/1906302/336c82cc-4b4a-4d9c-a856-ace7cf43afe4)

The requests were tripled! It isn't visible on the client-side, but only on the APM logging, so on the server-side.

I checked the other Next.js versions between these 2, and it turned out that this issue started happening in `v13.3.5-canary.12`. **The `v13.3.5-canary.11` was still fine.**

Requests before and after the version upgrade:
![image](https://github.com/vercel/next.js/assets/1906302/a4d2240a-b8e7-4c56-87af-7f7f2f210afb)

Latency before and after the version upgrade:
![image](https://github.com/vercel/next.js/assets/1906302/e2dfd4c2-b257-4a0c-adb4-6d2186474624)

The new extra GET requests are highlighted with yellow colour as the top resource in terms of requests:
![image](https://github.com/vercel/next.js/assets/1906302/194c42fb-8535-46d7-a6f8-8a59f100263b)

CPU used by pod
![image](https://github.com/vercel/next.js/assets/1906302/7598e118-a731-471f-9703-fbe582f92ab5)

Memory used by pod
![image](https://github.com/vercel/next.js/assets/1906302/3d963665-5ec6-4113-a504-25c9db014d9f)

Network stats:
![image](https://github.com/vercel/next.js/assets/1906302/013574a2-0a24-489a-9d68-4c9cf316e231)

### Expected Behavior

The number of requests should be the same as it was before.

### How are you deploying your application? (if relevant)

Azure DevOps

**Comment by gabor-at-reed** [comment] 2023-07-10 16:26
I've just checked with the latest release of Next.js (v13.4.10-canary.2), and the issue still persists.

**Comment by gabor-at-reed** [comment] 2023-07-11 09:14
I've added a few more stats about CPU and memory usage, as those are doubled as well... 🤯

**Comment by gabor-at-reed** [comment] 2023-07-11 12:32
I cannot spot any major differences between the 13.3.5-canary.11 and the canary.12 where the issue started happening:
https://github.com/vercel/next.js/compare/v13.3.5-canary.11...v13.3.5-canary.12?diff=split

**Comment by gabor-at-reed** [comment] 2023-07-12 09:45
@balazsorban44 do you have any thoughts on this issue?

**Comment by gabor-at-reed** [comment] 2023-07-17 14:13
For those who are suffering from the same issue: I found a weird solution for this issue where everything went back to normal in terms of network requests, latency, memory, etc.

After I checked that diff again that I linked above, I found that `appDir` change was suspicious. 

Even the [documentation](https://nextjs.org/docs/app/api-reference/next-config-js/appDir) says the following:

> Good to know: This option is no longer needed as of Next.js 13.4. The App Router is now stable.

I added the following to the next.config.js:

```
experimental: {
  appDir: false
}

```

After that change you might get a warning on the console like this:

> - warn You have enabled experimental feature (appDir) in next.config.js.
> - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
 
But don't worry about that... at least your app's performance will be fine again...

Some befare and after graphs:

![image](https://github.com/vercel/next.js/assets/1906302/d65c8f72-c850-45e1-a255-29e13a3f6f42)

![image](https://github.com/vercel/next.js/assets/1906302/5ef4dc9d-ac4e-4dc9-b6a2-32ae69cae42c)

![image](https://github.com/vercel/next.js/assets/1906302/fb9db6d6-4f34-45c2-be91-c699224707d7)

![image](https://github.com/vercel/next.js/assets/1906302/79f25945-7382-470b-ae19-b736a6d70056)

I hope someone from the next.js team will look into this issue or at least will respond to something here about the "why".

**Comment by mtlehtin** [comment] 2023-08-03 11:41
I'm experiencing the exact same issue. I upgraded Next.js from 12.3.1 to 13.4.12 and started seeing same issues.

Setting `appDir: false` as @gabor-at-reed suggested did not work in my case. I downgraded first to 13.4.7. with the same option but no effect.

Finally downgraded to last prod version before the canary version of which @gabor-at-reed mentioned. So the issue seemed to vanish when I downgraded to **13.3.4**.

This is preventing us to upgrade to latest Next.js version and I would really love to have some kind of response from Next.js team.

Kudos to @gabor-at-reed for spotting this issue. :pray:  I was losing my mind going through our configs and code..

#### Our setup:

- Docker with 18.17-alpine image
- Node.js 18.17.0 LTS (same issue with 16.14.0)
- npm 9.6.7
- The app is Deployed in Azure App Service

#### Relevant packages

- next: 13.4.12
- eslint-config-next: 13.4.12
- react: 18.2.0
- react-dom: 18.2.0
- typescript: 4.5.5

Here are couple of screenshots from Azure portal

End-to-end transaction details:

<img width="2558" alt="next-13-app-service-issue" src="https://github.com/vercel/next.js/assets/2706267/8fca3059-a5c1-4fd7-b955-d7267e4176b5">

User Flows:

<img width="1710" alt="next-13-app-service-issue-2" src="https://github.com/vercel/next.js/assets/2706267/6b38363c-ad00-4f27-a0aa-671fe29a6800">

**Comment by gabor-at-reed** [comment] 2023-08-09 08:51
@mtlehtin Thanks for the mention, and I'm sorry you have the same issue as we have! At least we know that we are not alone with this bug. Let's hope someone from the team will help us!

I checked my solution with v13.4.12, and it worked for me. Have you added that `appDir` setting with the `experimental` wrapper in the config file?

**Comment by mtlehtin** [comment] 2023-08-09 09:21
Yep, like in below. I need to test it further.

```javascript
experimental: {
  appDir: false
}
```

13.3.4 version had this issue https://github.com/vercel/next.js/issues/48040 in devmode which blocked totally our development. So I had to bump pack to 13.4.12.

[v13.4.14-canary.1](https://github.com/vercel/next.js/releases/tag/v13.4.14-canary.1) has a fix to a memory issue. I've not tested yet if that would resolve this as well.

"Consolidate Server and Routing process into one process: #53523"

**Comment by gabor-at-reed** [comment] 2023-08-09 09:27
The v13.4.13 completely breaks our apps on release flow, and we still need to figure out why (some routes are not accessible). Hence, we stuck with v13.4.12. But this is a different story.

**Comment by mtlehtin** [comment] 2023-08-10 07:17
[v13.4.14-canary.1](https://github.com/vercel/next.js/releases/tag/v13.4.14-canary.1) seems to fix this issue as well. Although another issue emerged from the update 13.4.12 -> 13.4.14-canary.1 (#49896, #53171).

A workaround for ECONNREFUSED error is to define HOSTNAME in Dockerfile runner section:

```bash
ENV HOSTNAME 0.0.0.0
```

But otherwise the request count normalized after 13.4.14-canary.1 update. I also removed the experimental appDir config.

/api/health

<img width="511" alt="Screenshot 2023-08-10 at 9 47 20" src="https://github.com/vercel/next.js/assets/2706267/625cfe5e-2f15-4ec3-a5f3-bc7fe474c735">

<img width="1126" alt="Screenshot 2023-08-10 at 9 45 57" src="https://github.com/vercel/next.js/assets/2706267/82c4c55e-52be-4b60-8072-b77c56f77dc4">

**Comment by mtlehtin** [comment] 2023-08-15 05:24
This issue seems to be fixed in release https://github.com/vercel/next.js/releases/tag/v13.4.15

**Comment by timneutkens** [comment] 2023-08-15 08:17
Thanks for confirming @mtlehtin, we've made a bunch of improvements over the past week 👍 Specifically https://github.com/vercel/next.js/pull/53523 fixed this issue.

@gabor-at-reed could you try upgrading to https://github.com/vercel/next.js/releases/tag/v13.4.16 which is the latest patch release and let me know if that works for your application?

I'm going to close this issue as @mtlehtin confirmed they're no longer seeing the problem.

**Closed by timneutkens** 2023-08-15 08:17 UTC
Labels: template: bug
