### ISSUE TITLE
Rewrite fallback never happens if fallback: 'blocking' or fallback: true is set in getStaticPaths

### ISSUE THREAD

**Issue by Jorenm** [vercel/next.js#26883] opened 2021-07-02 20:52 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.15.1

### What browser are you using?

Edge

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

Rewrite fallback never happens if fallback: 'blocking' or fallback: true is set in getStaticPaths.

next.config.js config:

```
	async rewrites() {
		return {
			fallback: [
				// These rewrites are checked after both pages/public files
				// and dynamic routes are checked
				{
					source: '/:path*',
					destination: `https://mydomain.com/:path*`,
				},
			],
		}
	},
```

[...slug].js config:

```
export async function getStaticPaths({preview = false}) {
	let allPaths = await getAllPaths(preview)

	// Format paths array to format expected by the catchall [...slug].js
	allPaths = allPaths.map((slug) => {
		return {params: {slug: slug.split('/').filter(Boolean)}}
	})

	return {paths: allPaths, fallback: 'blocking'}		
}
```

```
export async function getStaticProps({params, preview = false}) {
	let {page, pageType} = await getAnyPageBySlug(params.slug, preview)

        if (!page || !pageType)
	        return {notFound: true}
        
        return staticPageDataHelper({
	        props: {
		        page: page,
		        pageType: pageType
	        },
        }, preview)
}
```

### Expected Behavior

I would expect a request to a statically generated path returned by getStaticPaths to serve the static file.

If the path isn't one of the paths defined by getStaticPaths, I'd expect it to hit getStaticProps. If the path leads to a page being generated, I expect it to be served. If the path returns a notFound, I expect it to hit the rewrites fallback.

The way this is currently working, I don't see a way to implement an incremental adoption as described here https://nextjs.org/docs/migrating/incremental-adoption without also generated every page at build time, which is impractical for large sites.

### To Reproduce

I can do this if requested/necessary.

**Comment by ijjk** [comment] 2021-07-05 17:37
Hi, this is expected because a catch-all route is being used and `fallback: true/'blocking'` catches all of these as mentioned in the comment above your rewrite since it's a dynamic-route. If you use `fallback: false` only the provided paths returned from `getStaticPaths` will be matched and non-matched paths will continue to the fallback rewrite.

To incrementally adopt while leveraging the other fallback modes you can make more specific dynamic routes that don't match existing paths on the fallback site instead of using a catch-all route.  

I'm going to close this since it isn't a bug, if this could be documented better let us know and we could look into that!

**Closed by ijjk** 2021-07-05 17:37 UTC
Labels: template: bug

**Comment by Jorenm** [comment] 2021-07-06 17:05
Thanks for the quick reply. 

"To incrementally adopt while leveraging the other fallback modes you can make more specific dynamic routes that don't match existing paths on the fallback site instead of using a catch-all route."

The problem with this is I need a universal catchall or my client can't make new pages with new paths. I can't just have all the new site pages exist in different subdirectories because I need the paths to match as we implement more pages on the new build.

Is there anything else you'd recommend? Is it simply impossible to progressively build, incrementally adopt *and* have a fast build with next.js? If it isn't, could you point me to the right place to start looking at customizing the build/fallback process?

**Comment by ijjk** [comment] 2021-07-07 18:47
Hmm I see, it sounds like if the more specific paths are in the existing app it would be easier to have a fallback rewrite from the existing app to your new app so the catch-all dynamic route can use the fallback mode like you're looking for but not block existing paths on the existing app. 

Would this structure work alright or is there a conflict on the existing app that would prevent this?

**Comment by Jorenm** [comment] 2021-07-07 21:29
That would theoretically work, but it's a pretty major change. I'd have to delete the old versions to make it show the new ones, and the old site is on Drupal and it'd have to bootstrap every time, so it would probably not be very performant. Overall I think we'd rather have a super slow build (as bad as that is), than try to work backwards like that.

**Comment by balazsorban44** [comment] 2022-01-28 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
