### ISSUE TITLE
mapbox-gl zoom crashes when code is minified with swc enabled

### ISSUE THREAD

**Issue by heldr** [vercel/next.js#32336] opened 2021-12-09 20:14 UTC
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

14

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel, Netlify(next export)

### Describe the Bug

`mapbox-gl` zoom crashes when compiled with `{ swcMinify: true }` config.

### Map example
![CleanShot 2021-12-06 at 15 04 36](https://user-images.githubusercontent.com/134727/144898439-9d5a71be-6f73-4dd0-ba42-2d5e9a9669a6.gif)

Related issue
https://github.com/mapbox/mapbox-gl-js/issues/11332

### Expected Behavior

Those errors shouldn't be thrown:

### Chrome
<img width="519" alt="CleanShot 2021-12-06 at 15 10 00@2x" src="https://user-images.githubusercontent.com/134727/144899080-dd47e014-b870-43d8-bf78-aa7e9c25b813.png">

### Firefox
<img width="304" alt="CleanShot 2021-12-06 at 15 12 13@2x" src="https://user-images.githubusercontent.com/134727/144899373-8e0d3850-37d8-469b-ad74-412cfa890bfc.png">

### With SWC enabled (please click in zoom button)
https://nextjs-netlify-b77t3cmr9-heldr.vercel.app/

### Without SWC
https://nextjs-netlify-6of28w5sf-heldr.vercel.app/
https://61b2572b9d32d9ea7f040f17--cranky-bose-a8a255.netlify.app/

### Source repo
https://github.com/heldr/nextjs-netlify

**Comment by balazsorban44** [comment] 2021-12-09 23:02
This has been fixed in a newer version. Please update `npm i next@latest`

**Closed by balazsorban44** 2021-12-09 23:02 UTC
Labels: template: bug

**Comment by garretteklof** [comment] 2021-12-14 18:47
This still seems to be an issue .. due to the size of the private app it's been difficult to isolate the cause (or give a sandbox).. however when I run our web app with `swcMinify:true` outside of a local environment .. I get many client-side exception errors including `i is not a Constructor` .. any thoughts? We also use custom vector styles via Mapbox.
