### ISSUE TITLE
`query` in `exportPathMap` crashes `next export`

### ISSUE THREAD

**Issue by eps1lon** [vercel/next.js#24242] opened 2021-04-19 21:45 UTC
Issue template is unavailable at the moment.

`query` is unusable when using `next export`. 
Full repro: https://github.com/eps1lon/nextjs-export-path-map-query-clientside/tree/a408a7e261469de813284e4115dcdf8f1fe8439b

```jsx
// next.config.js
module.exports = {
  exportPathMap: () => {
    return {
      "/": { page: "/", query: { locale: "en" } },
      "/ru": { page: "/", query: { locale: "ru" } },
    };
  },
};

// pages/index.js
import { useRouter } from "next/router";

export default function Home() {
  const { query } = useRouter();
  return <pre>{JSON.stringify(query, null, 2)}</pre>;
}
```

The above config erros with 
```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error:
Error: you provided query values for / which is an auto-exported page. These can not be applied since the page can no longer be re-rendered on the server. To disable auto-export for this page add `getInitialProps`
```

`getInitialProps` is no solution since we want to use `getStaticProps`.

i18n routing is no solution either since it is incompatible with `next export`.

**Comment by ijjk** [comment] 2021-04-20 02:22
Hi, as the error mentions providing the query in `exportPathMap` for auto-exported/prerendered pages is not able to be applied since the pages are already rendered to HTML files during the build and can not be rerendered to include additional query values. 

I'm going to close this since it doesn't appear to be a bug and the error is behaving as intended.

**Closed by ijjk** 2021-04-20 02:22 UTC

**Comment by eps1lon** [comment] 2021-04-20 06:47
Could you please read the full issue. The bug is that this is unresolveable.

**Comment by ijjk** [comment] 2021-04-20 12:36
I did read the issue and as explained since pages are prerendered at build-time not during exporting for `getStaticProps` pages we show this error since the query isn't applied to the page instead of just ignoring the query. It sounds like you're more so requesting a new feature which is allowing query values to be passed from `getStaticPaths`

**Comment by eps1lon** [comment] 2021-04-20 13:03
> I did read the issue

Maybe you missed the part about the misleading error message. `getInitialProps` is not a valid workaround since it requires `getInitialProps`. I do not want to run JS on the client when I don't need to. And I also can't use `getInitialProps` with `getStaticProps`.

So `exportPathMap` is not working with `next export`. Nothing in the docs mention that `exportPathMap` is crashing with certain features of nextjs. And the workarounds that are mentioned in error messages are not applicable. I don't understand how this is considered working as intended?

**Comment by balazsorban44** [comment] 2022-01-28 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
