### ISSUE TITLE
Generic rewrites + catch-all page never proxies

### ISSUE THREAD

**Issue by mAAdhaTTah** [vercel/next.js#16212] opened 2020-08-15 15:14 UTC
# Bug report

## Describe the bug

Somewhat of a follow-on to #15700, I revisited the config to test things after the release of Next v9.5.2. Between then and now, we added an optional catch-all route as we're integrating w/ a CMS and want to derive the slugs from it. In reattempting the configuration options in that issue, I found nothing was getting proxied, presumably because the catchall route 404'd them.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Add a root catch-all route, e.g. `pages/[[...path]].js`
2. Update the next configuration as follows:

    ```js
    trailingSlash: true,
    async rewrites() {
      return [
        // check if Next.js project routes match before we attempt proxying
        {
          source: '/:path*/',
          destination: '/:path*/',
        },
        {
          source: '/:path*/',
          destination: `${process.env.WEB_PROXY_TARGET}/:path*/`,
        },
      ];
    },
    ```
3. Build the project (I tested in development & production modes).
4. Attempt to load a page that should be proxied.
5. See 404 page isntead.

## Expected behavior

Pages that aren't caught by the catch-all route's static paths should be proxied.

## System information

- OS: Docker
- Version of Next.js: 9.5.2
- Version of Node.js: 12

## Additional context

Putting rewrites through its paces! Similar to my comment on the other issue, because this is blocking a move off our custom server, I am happy to provide any additional help needed here.

**Comment by timneutkens** [comment] 2020-08-15 18:53
This is the expected behavior as you're first checking if the path matches a Next.js route and if it does it'll continue onward with the matched route. You'll likely want to distinguish which routes have to be proxied and move them before the Next.js matching or remove the top-level catch all route.

**Comment by mAAdhaTTah** [comment] 2020-08-15 21:09
> This is the expected behavior as you're first checking if the path matches a Next.js route and if it does it'll continue onward with the matched route.

Is the intention that the catch-all routes will still catch paths that aren't covered by `getStaticPaths`? My assumption with `getStaticPaths` is that we know in advance whether a route matches, so if it's not in that list of routes, it should fall back to proxying because the page doesn't match. If the list of paths are static, that it shouldn't match every possible path.

Is this a problem with any wildcard pages (if I've got the right term) or is it specific to the catch-all/spread route? e.g. if I have a `/blog/[path].js` page, would it be possible to fall back to proxying `/blog/page-that-does-not-exist-in-next/`?

**Comment by mAAdhaTTah** [comment] 2020-08-19 18:25
Repro request acknowledged. Will get that together.

**Comment by mifrej** [comment] 2020-09-16 18:07
Any update on this? I have the same problem. In case of URL `/api/*` want to proxy to `http://my.api.service.com/*`.
And it doesn't work.

**Comment by mAAdhaTTah** [comment] 2020-09-17 15:39
@mifrej Main blocker right now is we need a repro case. I haven't had time to put it together but if you can put together a minimal repro, that'll help.

**Comment by Warqus** [comment] 2021-05-01 17:45
What is the status on this?

**Comment by ijjk** [comment] 2021-05-04 17:58
This sounds related to https://github.com/vercel/next.js/pull/24121 which is available in the latest version of Next.js `v10.2.0`.

I'm going to close this since it should be resolved, if you're still encountering problems with this please provide additional information and it can be investigated further!

**Closed by ijjk** 2021-05-04 17:58 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-28 09:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
