### ISSUE TITLE
Custom componentDidCatch does not work during SSR

### ISSUE THREAD

**Issue by kachkaev** [vercel/next.js#5070] opened 2018-09-02 08:45 UTC
# Bug report

## Describe the bug

It looks like [React Error Boundaries](https://reactjs.org/docs/error-boundaries.html) are ignored during SSR, which makes it impossible to use components with `componentDidCatch` lifecycle methods.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Clone MWE from [kachkaev/next-component-did-catch-mwe](https://github.com/kachkaev/next-component-did-catch-mwe)
2. `yarn`
3. `yarn build && yarn start` (using production mode)
4. go to http://localhost:3000/
5. click _open a page that contains something broken_ to go to http://localhost:3000/contains-something-broken
6. observe `Cannot read property '42' of undefined` triggered from `SomethingBroken` and handled by `CustomErrorBoundary` (this is expected behavior)
7. refresh the page to render the same component tree on the server
8. observe next.js 500 + an error stack in CLI instead of the same result as in step 6

## Expected behavior
I expected `componentDidCatch` inside `CustomErrorBoundary` to work both on the on the server, not just on the client. It seems like it's impossible to rely on React error boundaries until this is the case.

## System information
 - OS: macos
 - Version of Next.js: `7.0.0-canary.8`
 - Version of React.js: `16.4.2`

## Additional context

If `componentDidCatch` can be fixed in production SSR it might be worth thinking about how it could be tested in dev mode too. At the moment the error message overlay shows up regardless of `componentDidCatch` has worked on the client-side and it'd be great if a popup could either be completely removed or state that an exception of such kind will be mitigated in production. CRA has a similar problem as well: https://github.com/facebook/create-react-app/issues/3627

**Comment by timneutkens** [comment] 2018-09-02 12:08
Please read https://github.com/facebook/react/issues/10442#issuecomment-321904824

**Comment by kachkaev** [comment] 2018-09-07 10:33
Right, I see where the limitation is coming from. Shall there be a sentence or two in `README` that would warn users about such behaviour? This could go to [_Custom error handling_](https://github.com/zeit/next.js#custom-error-handling) section for instance.

It turns out that it's not practical to define `componentDidCatch` throughout a Next.app unless in a dynamic component that is not server-side-rendered. Am I right with this assumption?

I'll be happy to submit a PR with a little addition to README, but you are also free to do this @timneutkens.

**Comment by timneutkens** [comment] 2018-09-07 10:35
They handle different types of errors, for example on zeit.co we report errors in componentDidCatch of _app.js + we report in `getInitialProps` of `pages/_error.js` (this is called for pretty much every error that happens on SSR)

**Comment by kachkaev** [comment] 2018-09-07 10:48
I also have a similar setup: `componentDidCatch` in `_app.js` reports the event to Google Analytics and `getInitialProps` in `pages/_error.js` helps style the page depending on its kind (_product not found_ is not the same as _random page not found_).

Here's a scenario that does not work though: imagine we have some user-defined JSON that describes a data vis (e.g.[vega](https://vega.github.io/vega/)). This JSON gets passed to a React component, which tries to render an SVG. If a JSON is faulty, an error is thrown and this is where a local `componentDidCatch` would really shine. I tried throwing from a render function inside such a vis component and catching this error using `componentDidCatch` one component up, but instead the server was rendering `pages/_error.js`, which is not what I expected. Warning others that local `componentDidCatch` cannot be used during SSR is what I'm talking about.

**Comment by sheerun** [comment] 2018-10-23 09:33
I think next.js should provide something similar to componentDidCatch but working on both server and client side. This can only be handled by code that calls render() method of react

**Comment by garrettmac** [comment] 2018-12-21 18:57
What is this line doing?

```jsx
super.componentDidCatch(error, errorInfo) 
```

**Comment by morokosi** [comment] 2019-05-02 07:40
Is it possible to give up SSR and retry rendering on client side when an error was thrown during SSR?

**Comment by bezreyhan** [comment] 2019-06-27 22:02
I liked @morokosi solution of sending down the JS bundle without SSR. This allows the app to handle errors on the client like it normally would.

**Comment by mmabraham** [comment] 2019-09-06 14:33
> Is it possible to give up SSR and retry rendering on client side when an error was thrown during SSR?

Or at least make such a feature opt-in

**Comment by aralroca** [comment] 2020-05-27 09:31
Or some page configuration to retry during hydration when a markup error happens on SSR.

**Comment by SergioGeeK7** [comment] 2021-08-13 12:55
any plans to implement a solution for the issue ?

**Comment by kevinolivar** [comment] 2021-09-09 15:58
good old try/catch?

**Comment by SergioGeeK7** [comment] 2021-09-09 17:04
try/catch does work but in my case, I'm using `next/dynamic` and try/catch is not able to catch the error inside the  `next/dynamic` component

**Comment by erosenberg** [comment] 2021-11-16 16:55
Would also love to know how to catch all errors with SSR if that doesn't work.

**Comment by balazsorban44** [comment] 2022-01-19 23:59
Given the OPs reproduction, this is not something that Next.js would even compile today. Since the reported version was Next.js 7, I'm inclined to close this. If anyone experiences a similar issue in newer Next.js versions, please open a separate bug report for that.

We have a documentation section on how to handle situations like this now:

https://nextjs.org/docs/going-to-production#error-handling

https://nextjs.org/docs/advanced-features/custom-error-page

**Closed by balazsorban44** 2022-01-19 23:59 UTC
Labels: type: upstream
