### ISSUE TITLE
static generation should allow the use of `@` in file path

### ISSUE THREAD

**Issue by tungv** [vercel/next.js#15439] opened 2020-07-23 15:54 UTC
# Bug report

## Describe the bug

when I use getStaticPaths and return paths with '@' in its name, it gets replaced with '%40' by encodeURIComponent function here (https://github.com/vercel/next.js/blob/c9492a8cc947f183ec608931239ef04a235776fd/packages/next/build/utils.ts#L635) which leads to a 404 error when the path is requested.

Expectation:
Static generation should honor the @ sign in path, similar to npm.im/@namespace/pkg convention.

## To Reproduce

1. Go to https://xb004.sse.codesandbox.io
2. Click on link "/test/@abc/def"
3. refresh page
4. See error 404

## Expected behavior

Full reload should show exactly the same content. Expected behavior can be found using "/test/abc/def" link

## System information

- OS: codesandbox
- Browser : chrome
- Version of Next.js: 9.4.4
- Version of Node.js: codesandbox default

## Additional context
codesandbox explorer: https://codesandbox.io/s/quizzical-firefly-xb004?file=/pages/test/%5B...pkg%5D.js

**Comment by Janpot** [comment] 2020-07-23 17:46
This should have been fixed by https://github.com/vercel/next.js/pull/14717
Would you mind trying on `v9.4.5-canary.43`?

**Comment by tungv** [comment] 2020-07-24 03:50
hey @Janpot it works for me.

@timneutkens should I keep this open until the release of v9.4.5

**Comment by timneutkens** [comment] 2020-07-24 13:15
Going to close this as it was fixed in #14717

**Closed by timneutkens** 2020-07-24 13:15 UTC

**Comment by balazsorban44** [comment] 2022-01-29 20:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
