### ISSUE TITLE
Can't render a custom error component as next/error is rendered unconditionally when using getStaticPaths and getStaticProps in 9.3.4

### ISSUE THREAD

**Issue by airamrguez** [vercel/next.js#11486] opened 2020-03-30 10:53 UTC
# Bug report

## Describe the bug

I'm trying to render an error component when a dynamic route does not match one of the paths returned by `getStaticPaths`, but it doens't work. I've cloned the *blog-starter* demo to reproduce the error. So if you take a look at these piece of code below:

```js
export default function Post({ post, morePosts, preview }) {
  const router = useRouter();
  console.log("router.isFallback ->", router.isFallback);
  if (!router.isFallback && !post?.slug) {
    // return <ErrorPage statusCode={404} />
    return <div>I would like to show here an Error component</div>;
  }
```

And you navigate to a non-existing route like for example: http://localhost:3000/posts/this-post-that-not-exists we should see in screen "I would like to show here an Error component", but what is rendered is the next/error component.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone the blog-starter-app demo: https://github.com/zeit/next.js/tree/master/examples/blog-starter
1. Let's change this line `return <ErrorPage statusCode={404} />` with `<div>I would like to show here an Error component</div>` in the `[slug].js` file.
2. Open the browser in a non existing route like for example: http://localhost:3000/posts/this-post-that-not-exists
3. See error

## Expected behavior

The error component should be rendered.

## System information

- OS: macOS
- Version of Next.js: 9.3.4

**Comment by RodrigoEspinosa** [comment] 2020-03-30 16:06
I'm experiencing the same issue with a build for `serverless`. I found that the regex generated for the `dynamicRoutes` might have changed.

**Comment by airamrguez** [comment] 2020-04-01 16:18
@RodrigoEspinosa which regex do you mean?

**Comment by ijjk** [comment] 2020-09-10 20:57
Hi, the blog starter example is set to [`fallback: false`](https://nextjs.org/docs/basic-features/data-fetching#fallback-false) mode by default so any paths not returned from `getStaticPaths` will result in the [404 page](https://nextjs.org/docs/advanced-features/custom-error-page#404-page) being rendered.

I'm going to close this since it appears to working as expected.

**Closed by ijjk** 2020-09-10 20:57 UTC

**Comment by balazsorban44** [comment] 2022-01-29 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
