### ISSUE TITLE
ISR page not being deleted after deleting it in CMS

### ISSUE THREAD

**Issue by markdost** [vercel/next.js#25907] opened 2021-06-08 18:32 UTC
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

I was trying out Next.js and build a small app which fetches posts from a headless WordPress app with GraphQL installed. Then I use Apollo/Client to get GraphQL content

### Expected Behavior

When creating a post in WordPress it adds the page. When deleting post it does not get removed. This happens both when doing `npm run dev `and `npm run build` then `npm start`

### To Reproduce

**apollo-client.js**
```
import { ApolloClient, InMemoryCache } from "@apollo/client";

const client = new ApolloClient({
  uri: process.env.WORDPRESS_GRAPHQL_ENDPOINT,
  cache: new InMemoryCache(),
});

export default client;
```

**index.js**
```
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { gql } from "@apollo/client";
import Link from "next/link";
import client from "../apollo-client";

function Home(props) {
  const { posts } = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>Wordpress blog posts</title>
        <meta
          name="description"
          content="Wordpress blog posts with Apollo Client"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>=
        <div className={styles.grid}>
          {posts.map((post) => (
            <a
              key={post.node.databaseId}
              href={`/blog/${post.node.slug}`}
              className={styles.card}
            >
              <h2>{post.node.title}</h2>
              <div dangerouslySetInnerHTML={{ __html: post.node.excerpt }} />
            </a>
          ))}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query Posts {
        posts {
          edges {
            node {
              title
              databaseId
              slug
              excerpt(format: RENDERED)
            }
          }
        }
      }
    `,
  });

  if (!data.posts.edges) {
    return { notFound: true };
  }

  return {
    props: {
      posts: data.posts.edges,
    },
    revalidate: 10,
  };
}

export default Home;
```

**/blog/[slug].js**
```
import Link from "next/link";
import { gql } from "@apollo/client";
import client from "../../apollo-client";

export default function BlogPage(props) {
  const { post } = props;

  if (!post) {
    return <p>Loading...</p>;
  }

  return (
    <div>
      <h1>{post.title}</h1>
      <div dangerouslySetInnerHTML={{ __html: post.content }} />
      <Link href="/">
        <a>&larr; back to home</a>
      </Link>
    </div>
  );
}

export async function getStaticProps({ params }) {
  const { slug } = params;
  const result = await client.query({
    query: gql`
      query GetWordPressPostBySlug($id: ID!) {
        post(id: $id, idType: SLUG) {
          title
          content
        }
      }
    `,
    variables: { id: slug },
  });

  if (!result.data.post) {
    return { notFound: true };
  }

  return {
    props: {
      post: result.data.post,
    },
    revalidate: 10,
  };
}

export async function getStaticPaths() {
  const result = await client.query({
    query: gql`
      query GetWordPressPosts {
        posts {
          nodes {
            slug
          }
        }
      }
    `,
  });

  return {
    paths: result.data.posts.nodes.map(({ slug }) => {
      return {
        params: { slug },
      };
    }),
    fallback: true,
  };
}
```

**Comment by la55u** [comment] 2021-06-08 18:49
Experienced the same thing in https://github.com/vercel/next.js/issues/25470 as well but unfortunately it doesn't get much attention.

**Comment by markdost** [comment] 2021-06-08 23:46
Oh that's not good to hear. I've stumbled on a few similar topics on Stackoverflow as well.

**Comment by ijjk** [comment] 2021-06-08 23:51
On the above page `revalidate` was not set when returning `notFound: true` so the page will no longer be revalidated and the `notFound` is cached instead

**Comment by markdost** [comment] 2021-06-09 05:25
Even with removing `notFound: true` on index.js and or on /blog/slug the problem still occurs

**Comment by hatsumatsu** [comment] 2021-06-17 20:17
@ijjk So if we want a page to return 404 when deleted in the CMS but being revalidated when the content is created again we need something like this?

````
  if (!result.data.post) {
    return { 
        notFound: true,
        revalidate: 10 
    }
  }

  return {
    props: {
      post: result.data.post,
    },
    revalidate: 10,
  };

````

**Comment by ijjk** [comment] 2021-06-17 20:19
@hatsumatsu correct, if that specific case is not working we can investigate that further as it is expected to work.

**Comment by lfades** [comment] 2021-08-10 17:13
Closing as it seems to not be an error with Next.js.

**Closed by lfades** 2021-08-10 17:13 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 00:12
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
