### ISSUE TITLE
image component in next js is not working in development build

### ISSUE THREAD

**Issue by tewarig** [vercel/next.js#19105] opened 2020-11-12 15:44 UTC
# Bug report
image component in next js is not working in development build
## Describe the bug
I tried to preview my web app.. in my local machine I was using the image component but the image is not loading in dev. enviroment.but when I ship the final build the images were loading and were there. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. type yarn next dev in terminal...(it will open dev. build)
2. Click on 'http://localhost:3000/' 
3. See bug

## Expected behavior

the images should be displayed
## Screenshots
![Screenshot from 2020-11-12 21-08-23](https://user-images.githubusercontent.com/54894783/98961391-86c7e200-252b-11eb-954c-7ee630efe9dd.png)

## System information

- OS: Ubuntu 20.04
- Browser chrome
- Version of Next.js:10.0
- Version of Node.js: 10.19.0

**Comment by Timer** [comment] 2020-11-12 17:11
Can you please try `next@canary`?

**Comment by joey3060** [comment] 2020-11-13 19:58
same problem here and I noticed only when the format of the image is png would happen but svg is ok

**Comment by tewarig** [comment] 2020-11-14 15:02
yes, also tried using next@canary it did not work for me.

**Comment by Timer** [comment] 2020-11-16 16:26
Please provide a full demo so we can look into this.

**Comment by ericag1985** [comment] 2020-11-19 02:19
I have the same problem. Oddly, I was not able to reproduce it with a new project, but in my existing project that was upgraded, only svg images work in the dev environment. Things work fine in the production build, but dev throws a 500 error when trying to get the image.

**Comment by algosdev** [comment] 2020-11-28 15:41
The same problem here, I try to explain further:
I get image url as .jpg or .png fromat from the API and use it in the new `<Image />` component

```
         <Image
            src={item.logo_image}
            layout='fill'
            alt={item.title || ''}
            loading='lazy'
          />
```

It's working perfectly in development mode (localhost:3000), but throwing 500 error in production build and just not showing up:


![image](https://user-images.githubusercontent.com/68058088/100519444-bdebf380-31b9-11eb-8940-1c4436de599c.png)

Error: GET https://website.name/_next/image?url=https%3A%2F%2Fwebsite.nam%2Fmovies%2Fimages%2F9e13bc40-2df2-4c03-8d7e-b029effe5144&w=1920&q=75 500 (Internal Server Error)

![IMG_20201128_203324](https://user-images.githubusercontent.com/68058088/100519387-5fbf1080-31b9-11eb-80b7-ee514d471283.png)

**Comment by timneutkens** [comment] 2020-12-04 09:58
Closing as no reproduction was provided.

**Closed by timneutkens** 2020-12-04 09:58 UTC
Labels: please add a complete reproduction

**Comment by taoqf** [comment] 2020-12-17 11:43
I got this error, too.
because the image is not s static file.
the src is like this: `/api/file?id=5bf50f9e-3bee-45e6-a3d0-451aa6bf1514`
I resolved this by using [this](https://react.geist-ui.dev/en-us/components/image)

**Comment by ericag1985** [comment] 2020-12-22 15:22
Update from our side: Our issues wound up being with our docker container and not with Next itself. No fix yet, but we are actively poking at it.

**Comment by lucasalmeida92** [comment] 2020-12-23 17:54
I don't know if you guys did the same, but I was getting the same error because my `public` folder was inside `src` folder.
So I just put it in root folder and it worked!

**Comment by HanliTheron** [comment] 2021-02-12 10:02
Hi @taoqf, our images being server from API are also not working. Can you maybe give more info in regards to how you resolved it? Not sure I understand your fix.

**Comment by taoqf** [comment] 2021-02-14 01:15
I did not resolve that, jut did not use `react/image` to avoid the issue.

**Comment by hyoretsu** [comment] 2021-02-21 16:10
@timneutkens [This](https://github.com/vercel/next.js/issues/20873) might be a reproduction for the same problem.

**Comment by J3ns6** [comment] 2021-05-16 12:56
same, here. The strange thing is, my logo in the navigation bar everything works normally, but not in the footer with a other image.

**Comment by iacobfred** [comment] 2021-06-21 20:29
I'm having the same problem. My navbar image (with .png extension) does not load in dev environment, and the console shows a 400 error coming from `image:1`.
```

**Comment by timneutkens** [comment] 2021-06-21 20:33
Instead of 👎 a post closing this issue please create a **reproduction** as asked for in the issue template so that it can be investigated and fixed. Without one we can't help you unfortunately as we can't reproduce this in any apps we're running or the integration tests. 

Again: we'd be more than happy to investigate and spend time on this if you provide a reproduction.

**Comment by hyoretsu** [comment] 2021-06-22 04:40
> Instead of 👎 a post closing this issue please create a **reproduction** as asked for in the issue template so that it can be investigated and fixed. Without one we can't help you unfortunately as we can't reproduce this in any apps we're running or the integration tests.
> 
> Again: we'd be more than happy to investigate and spend time on this if you provide a reproduction.

I mean, I'm not sure if it's the same issue but I provided a repo with sorta reproducible instructions on [an issue 6 months ago](https://github.com/vercel/next.js/issues/20873) when I was first trying to use Next.js. Currently updating my boilerplate to try and migrate definitely to using Next.js, not sure if it'll still happen then.

**Comment by matwjablonski** [comment] 2021-07-01 11:00
I had the same problem with relative paths to images. I resolved it by importing image and passing it to src.

```
import Link from 'next/link';
import arrow from '../../public/arrow.svg'

const Component = () => (<Image src={arrow} width={49} height={6}/>);
```

When I go that way development and production modes start working properly, but I faced another problem with testing. Jest coudn't find src for Images. So I added some workaround for that:

```
<Image src={arrow || '/public/arrow.svg'} width={49} height={6}/>
```

I am not sure that this is perfect way to do that. But for now it is working in development, production and test env.

**Comment by victor-yunenko** [comment] 2021-07-03 22:20
In my case it was rendering an empty box when used inside the `_document.tsx` file.

**Comment by yarivShamash** [comment] 2021-07-04 08:43
@matwjablonski thanks! I was facing the same problem and your solution helped me fix it.

**Comment by alex-r89** [comment] 2021-07-06 18:24
I am also noticing this issue,  my images are stored at a url, `https://images.mydomain.net` but on localhost these are 400 erroring because its trying to fetch the image from `http://localhost:3000/_next/image?url=https%3A%2F%2Fimages.mydomain.net%2Fdev%2F21.gif&w=1080&q=75`

I have added `{ domains: ['images.mydomain.net'] }` to my next.config.js.

On production this works fine, but locally it does not. Unsure why this is as of yet.

**Comment by Alejo-end** [comment] 2021-07-25 14:46
For my it was because of the nextconfig.js that had this:
{
    loader: 'imgix',
    images: {
      disableStaticImages: false,
    }
and I didnt really use the loader so I removed it and it worked fine again in development.

**Comment by yarivShamash** [comment] 2021-07-29 06:43
Thanks, I had a clash between two packages I was using.

**Comment by c7hm4r** [comment] 2021-08-17 00:02
In my case, the image file was corrupt.

**Comment by ocunex** [comment] 2021-10-03 03:58
Facing the same essue

**Comment by dlbnco** [comment] 2021-10-09 17:05
I was facing this while running Next with Node v10. I changed to v12 and the problem was solved.

**Comment by balazsorban44** [comment] 2022-01-27 13:08
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
