### ISSUE TITLE
Integration Example shows 404 Page

### ISSUE THREAD

**Issue by eKhattak** [vercel/next.js#13998] opened 2020-06-10 07:34 UTC
# Bug report

## Describe the bug
If you try to run `yarn next ./test/integration/basic/` the example lands you on the 404 page.

## To Reproduce
1. Pull Next.Js Repo
2. Run `yarn next ./test/integration/basic/`
3. Visit localhost:3000
4. You will see 

> 404: This page could not be found

## Expected behavior

`localhost:3000 ` should show the correct page.

## Screenshots
![404 Page](https://i.imgur.com/uhg6VzW.png)

## System information

- OS: Windows
- Version of Next.js: 9.4.4
- Version of Node.js: 12.18.0

## Aditional Notes
So the bug seems to be a pretty easy one and It's a good start to start contributing. I'll fix this one. I would like to know how the index page should look like?

**Comment by jamesmosier** [comment] 2020-06-11 02:21
There is no `pages/index.js` file in that directory so it would make sense you'd see a 404. Unless there is a test referencing that page then I personally don't see much benefit in adding a `pages/index.js` file just to have.

The [contributing.md](https://github.com/vercel/next.js/blob/canary/contributing.md#running-the-integration-apps) also references that you can run this command in order to determine which pages are available to be viewed for a given integration test:

```bash
EXAMPLE=./test/integration/basic
(\
  cd $EXAMPLE/pages; \
  find . -type f \
  | grep -v '\.next' \
  | sed 's#^\.##' \
  | sed 's#index\.js##' \
  | sed 's#\.js$##' \
  | xargs -I{} echo localhost:3000{} \
)
```

**Comment by timneutkens** [comment] 2020-06-11 08:39
I'm going to close this as we discussed with @eKhattak the particular test suite does not have a pages/index.js like @jamesmosier was saying.

**Closed by timneutkens** 2020-06-11 08:39 UTC

**Comment by balazsorban44** [comment] 2022-01-30 01:27
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
