### ISSUE TITLE
Warning about chokidar 2 on Node 14

### ISSUE THREAD

**Issue by Vultraz** [vercel/next.js#13627] opened 2020-06-01 13:30 UTC
# Bug report

## Describe the bug

This warning appears when installing Next on Node 14:
> chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.

Our project is using `yarn` if that's relevant.

## System information

- OS: Windows
- Version of Next.js: 9.4.4
- Version of Node.js: 14.2.0

**Comment by danilofuchs** [comment] 2020-06-01 14:38
Seems to be duplicate of https://github.com/vercel/next.js/issues/12857

**Comment by timneutkens** [comment] 2020-06-01 17:24
Yep duplicate of #12857

**Closed by timneutkens** 2020-06-01 17:24 UTC

**Comment by balazsorban44** [comment] 2022-01-30 02:14
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
