### ISSUE TITLE
Warning: Prop `href` did not match. Server: "./page" Client: "/path/page" for relative pathing

### ISSUE THREAD

**Issue by ctsstc** [vercel/next.js#29656] opened 2021-10-05 23:52 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

16.7.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

not yet

### Describe the Bug

When using relative pathing with `next/link` you get a warning error like: 

```
Warning: Prop `href` did not match. Server: "./page" Client: "/path/page"
```

### Expected Behavior

There should not be an error when using relative pathing. It seems that the server side could determine the current path for the relative pathing. I should be able to utilize relative pathing instead of having to use absolute pathing.

### To Reproduce

```jsx
// This would be on a page like `/path/page-1.js`
<Link href="page-2">Go to page 2</Link>
<Link href="./page-2">Go to page 2</Link>
```

The client side links seem to work just fine, but you get the error in the console.

**Comment by ijjk** [comment] 2021-10-06 03:04
Closing as a duplicate of https://github.com/vercel/next.js/issues/19922

**Closed by ijjk** 2021-10-06 03:04 UTC
Labels: template: bug
