### ISSUE TITLE
Shallow routing doesn't work for dynamic route after updating to NextJS 11

### ISSUE THREAD

**Issue by kelokchan** [vercel/next.js#26162] opened 2021-06-16 05:41 UTC
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

15.10.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

Previously I was using `router.replace(
        `${window.location.pathname}?t=${newValue}`,
        router.asPath,
        {
          shallow: true,
        };` whenever I'm changing the tab so that the tab index is set a query param `t`.  It was working fine on NextJS 10. But after upgrading to NextJS 11, the page will refresh even with `shallow: true` . I also notice the reload only happens when my page is a dynamic route

### Expected Behavior

The page should re-route to current page without reloading

### To Reproduce

Do `router.replace(window.location.pathname, undefined, {
            shallow: true,
          });` on NextJS 11

**Comment by vlad-zhukov** [comment] 2021-06-26 15:48
It looks similar to #26508

**Comment by ijjk** [comment] 2021-09-21 05:03
Closing as a duplicate of https://github.com/vercel/next.js/issues/26169 also note `router.pathname` should be used instead of `window.location.pathname` for accurate client-transitions like shown above.

**Closed by ijjk** 2021-09-21 05:03 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
