### ISSUE TITLE
build renders paths twice and root layout multiple times (App Router SSG)

### ISSUE THREAD

**Issue by MangoMarcus** [vercel/next.js#64304] opened 2024-04-10 18:08 UTC
### Link to the code that reproduces this issue

https://github.com/MangoMarcus/nextjs-duplicate-renders

### To Reproduce

1. Clone repo and `cd` into project directory
2. `npm i`
3. `npm run build`

### Current vs. Expected behavior

- Each path should only be rendered once, not twice
- Root layout should only be rendered once, not multiple times including once for each path (it renders again for every path you add)

<img width="606" alt="Screenshot 2024-04-10 at 18 52 39" src="https://github.com/vercel/next.js/assets/72021142/a73a0fe8-ebb6-445a-80f8-da3d4c9a950b">

### Provide environment information

```bash
Operating System:
  Platform: macOS
  Chip: Apple M1 Pro
  Version: macOS 14.4
Binaries:
  Node: 20.2.0
  npm: 9.6.6
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next build (local), Vercel (Deployed)

### Additional context

It's the same behaviour on Vercel, I think it's causing issues with my caching mechanism

**Comment by ztanner** [comment] 2024-07-08 15:38
Thanks for the report! Closing as a duplicate of https://github.com/vercel/next.js/issues/58736 so we can track this in a single place.

**Closed by ztanner** 2024-07-08 15:38 UTC
Labels: bug
