### ISSUE TITLE
`next/navigation` `redirect()` with `loading.tsx` causes page to refresh twice

### ISSUE THREAD

**Issue by steven-tey** [vercel/next.js#62463] opened 2024-02-23 23:54 UTC
### Link to the code that reproduces this issue

https://github.com/steven-tey/redirect-refresh-bug

### To Reproduce

1. Go to https://redirect-refresh-bug.vercel.app/redirect
2. Notice that after the redirect happens, the page refreshes again, which is quite odd

This happens both in prod:

https://github.com/vercel/next.js/assets/28986134/0f13584e-dc5c-408c-800e-309d334e4f0c

And locally:

https://github.com/vercel/next.js/assets/28986134/cf7487bb-1b80-4ff9-b29b-aa4bbc4a6b76

Interestingly, this error doesn't happen when you remove the `loading.tsx` file, which could be the root cause of the issue: 

1. Go to https://redirect-refresh-bug.vercel.app/redirect-without-loading
2. Redirect happens properly.

### Current vs. Expected behavior

Current behavior: after the redirect happens, the page refreshes again when `loading.tsx` is present

Expected behavior: after the redirect happens, the page does not refresh again when `loading.tsx` is present

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.9.0
  npm: 10.2.4
  Yarn: 1.22.21
  pnpm: 8.10.5
Relevant Packages:
  next: 14.1.1-canary.71 // Latest available version is detected (14.1.1-canary.71).
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), Vercel (Deployed)

### Additional context

N/A

<sub>[NEXT-2719](https://linear.app/vercel/issue/NEXT-2719/nextnavigation-redirect-with-loadingtsx-causes-page-to-refresh-twice)</sub>

**Comment by aryobenholzner** [comment] 2024-02-29 08:20
duplicate of https://github.com/vercel/next.js/issues/59800

**Comment by steven-tey** [comment] 2024-03-03 14:02
oh good catch @aryobenholzner, will try the `permanentRedirect` workaround

**Comment by samcx** [comment] 2024-03-06 01:36
Taking a look!

**Closed** 2024-03-28 23:08 UTC
Labels: template: bug, area: Routing, linear: next
