### ISSUE TITLE
custom image loader does not provide webP support option

### ISSUE THREAD

**Issue by dohomi** [vercel/next.js#20967] opened 2021-01-11 08:10 UTC
**Describe the feature you'd like to request**

Currently the custom image loader does not attach webp support. Several image proxy need this information upfront to load the specific image.

**Describe the solution you'd like**

Attach webp-support to the arguments of the custom loader.
```js
const customLoader = ({src, width, quality, webp}) => `imageString...`
```

**Describe alternatives you've considered**

Using own webp function could work as well but I think that NextJS already provides a function to determine webP support for its own handler.

**Comment by timneutkens** [comment] 2021-01-11 08:41
Next.js does not know about the browser supporting webp in the image component. The automatic image optimization can determine if webp is supported based on the Accept header. You can see how that's determined here: https://github.com/vercel/next.js/blob/canary/packages/next/next-server/server/image-optimizer.ts#L270.

As there is no way for us to provide this information reliably to the loader I'm going to close this feature request. Most image CDNs (e.g. cloudinary, imgix etc) all determine the format automatically.

**Closed by timneutkens** 2021-01-11 08:41 UTC
Labels: template: story

**Comment by dohomi** [comment] 2021-01-12 06:01
@timneutkens I am using the image proxy of Storyblok. I would need to pass a specific string to the proxy which determines the support.
If I do this now I receive (because of SSG) client/server hydration errors because the browser supports webp but during the initial build it doesn't.
How does a recommended way look like to solve this issue?

**Comment by dohomi** [comment] 2021-05-13 00:58
@GxDesign you can try https://github.com/ihordiachenko/supports-webp-sync to run before your script

**Comment by bmstefanski** [comment] 2021-07-31 14:33
Hi, I have covered three possible solutions in the article https://bstefanski.com/nextjs-custom-image-loader-webp-support-polyfill. Hope it'll help somebody! :D

**Comment by balazsorban44** [comment] 2022-01-28 01:27
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
