### ISSUE TITLE
Module not found after upgrading next

### ISSUE THREAD

**Issue by cdelacombaz** [vercel/next.js#31133] opened 2021-11-08 09:52 UTC
### What version of Next.js are you using?

10.2

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

macOS Big Sur

### How are you deploying your application?

next run dev

### Describe the Bug

I am trying to upgrade my packages. Most importantly, NextJS from 10.0.3 to 12.0.3.

A reproducable example can be found under following link: https://github.com/cdelacombaz/nextjs-bugreport-example

"main" branch, is a working example of my current versions.

  "dependencies": {
    "@formatjs/intl-getcanonicallocales": "^1.5.6",
    "@formatjs/intl-locale": "^2.4.19",
    "@formatjs/intl-pluralrules": "^4.0.11",
    "next": "10.0.3",
    "react": "17.0.1",
    "react-dom": "17.0.1"
  }

"stillWorking" branch, is an example with the latest Next version where my setup was still working on. v10.1.3

"bugReport" branch, is an example with the error I get by using any Next version equal or higher than v10.2

When upgrading Next to v10.2 or any higher, it results in following error message: `Module not found: Can't resolve '@formatjs/intl-pluralrules/polyfill/'

I also tried to upgrade the @formatjs packages to latest versions, but still get the same error.

![Screenshot 2021-11-08 at 08 29 38](https://user-images.githubusercontent.com/45405753/140720217-da2b040f-c356-4c1c-a5cd-7d948e697fef.png)

### Expected Behavior

Module should be imported without any error, as in the working example.

### To Reproduce

1. clone https://github.com/cdelacombaz/nextjs-bugreport-example/tree/bugReport
2. in your terminal, check that you are in the folder where the package.json is located. Then run `yarn` to install the packages
3. in the same location in your terminal, run `yarn run dev`

You can switch to the main branch to see a working example (you might have to reinstall the packages with if you still have the error showing up)

**Comment by timneutkens** [comment] 2021-11-08 11:59
Seems unexpected that it previously allowed that, the package has `polyfill.js` in the root directory, so a trailing slash in the import path would not resolve to that file as it is at `node_modules/@formatjs/intl-pluralrules/polyfill.js` and you're trying to import `node_modules/@formatjs/intl-pluralrules/polyfill/` which would resolve to a directory called `polyfill`.

I'm going to close this as it's working as expected, seems that previously a specific invalid path was allowed but that that has been fixed since.

**Closed by timneutkens** 2021-11-08 11:59 UTC
Labels: template: bug

**Comment by cdelacombaz** [comment] 2021-11-08 12:01
oh lol... thanks for the fast reply! :)

**Comment by balazsorban44** [comment] 2022-01-27 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
