### ISSUE TITLE
i18n browser language detection only redirects when on the website root

### ISSUE THREAD

**Issue by gpaluk** [vercel/next.js#24122] opened 2021-04-15 22:33 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

15.12.0

### What browser are you using?

Chrome 89.0.4389.114

### What operating system are you using?

macOS

### How are you deploying your application?

Other

### Describe the Bug

When visiting a page that is not the website route, the user is not redirected to the correct locale based on their browser locale settings.

### Expected Behavior

When a browser locale language is set, it would be expected that the user is directed to the correct version of the website regardless of their initial landing page.

### To Reproduce

Add i18n redirects for any language and set the browser locale accordingly. Visit a page that is not the document root. The user does not get redirected to their specific language as expected.

**Comment by ijjk** [comment] 2021-04-17 14:34
This is currently the expected behavior and is mentioned here https://nextjs.org/docs/advanced-features/i18n-routing#automatic-locale-detection

I'm going to close this since it doesn't appear to be a bug and this issue has been duplicated in a few places e.g. https://github.com/vercel/next.js/discussions/22405

**Closed by ijjk** 2021-04-17 14:34 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
