### ISSUE TITLE
delBasePath run twice when go back to dynamic route page

### ISSUE THREAD

**Issue by JYPark88** [vercel/next.js#23809] opened 2021-04-08 11:41 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

10.15.3

### What browser are you using?

chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

This bug occurs when I go back to dynamic route page with basePath.

error like below
Uncaught (in promise) Error: The provided as value (`/mobile/order/23000098995081`) is incompatible with the href value (`/ile/order/[orderId]`).

part of pathname(`mob`) removed by router. 

expected pathname: `/mobile/order/[orderId]`
result: `/ile/order/[orderId]`
the basePath that I set: `/ssr`

### Expected Behavior

Previous page have to be rendered.

### To Reproduce

1. set basePath on next.config.js
2. open any page 
3. move to dynamic route page with router.push
4. move to another page with router.push
5. go back to previous page. <---- this step problem occured.

**Comment by colinhemphill** [comment] 2021-04-14 17:48
We're seeing this too—impacting hundreds of users a day and loading up our Sentry events pretty quickly.

**Comment by YG-qualson** [comment] 2021-05-27 05:27
Ooooh basePath is the key? I didn't catch that. 
Hoping this problem could be solved with updating nextjs...

**Comment by YG-qualson** [comment] 2021-05-27 05:35
this doesn't happens on `next dev`, but still occurs in 10.2.3

**Comment by FourwingsY** [comment] 2021-06-07 01:45
as I see, 5b70802f619a7d5aa111a06850a51078a6ec5a60 is the key. 
before run `delBasePath`, we should check `hasBasePath`, but here it doesn't.

**Comment by ijjk** [comment] 2021-06-07 16:04
Hi, this sounds like a duplicate of https://github.com/vercel/next.js/issues/25285 which is fixed in `v10.2.4-canary.0` of Next.js, please upgrade and give it a try!

**Closed by ijjk** 2021-06-07 16:04 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
