### ISSUE TITLE
"Intrinsic" sizes image incorrectly

### ISSUE THREAD

**Issue by matt-joecoffee** [vercel/next.js#27643] opened 2021-07-31 00:41 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

12.22.3

### What browser are you using?

Brave

### What operating system are you using?

macOS

### How are you deploying your application?

Other

### Describe the Bug

My image has intrinsic width and height of 640x424. It is rendering the full width of the container, while maintaining it's intrinsic height, 768x424.

And so, the image is distorting. These behavior seems to be not as documented.

### Expected Behavior

I would expect the image to scale down when the parent's width is smaller than the image's intrinsic size, and not to grow beyond its intrinsic values ever, effectively:

```css
img {
  display: block;
  height: auto;
  max-width: 100%;
}
```

### To Reproduce

```jsx
import image from './image.png'
...
<Image alt="Description" src={image} />
```

**Comment by styfle** [comment] 2021-08-04 16:52
Can you share the image.png in this example?

Also what does `...` represent? Is there any wrapping parent divs/styles necessary to reproduce?

**Comment by matt-joecoffee** [comment] 2021-08-04 20:29
The `...` is just the standard component markup, such as:

```js
const Component = () => {
  // do whatever
  return (
    <SurroundingJSX>
      <Image alt="Description" src={image} />
    </SurroundingJSX>
  )
}
```

The specific PNG in this case is:

<img width="320" alt="shared-referral" src="https://user-images.githubusercontent.com/86847089/128250010-4800b1a5-80cd-48ee-8eb7-a7ec2ecf2b07.png">

Set as `layout="intrinsic"`, the image seemed to be maintaining its intrinsic height of 424-pixels, but the image would expand to 100% the size of its container when the container exceeded the image width. So it would downscale appropriately for a smaller container, but then distort the width in a larger container.

**Comment by matt-joecoffee** [comment] 2021-08-04 20:36
Oh, I was loading `normalize.css` globally, if that's if that's of interest.

It's immediate parent was an item in a flexbox, but not itself a flexbox. So, like ...

```
<div style="display: flex; flex-direction: column;">
  <div>
    <Image ...
```

**Comment by styfle** [comment] 2021-08-04 21:40
I'm seeing 640x424, seems correct

- Source: https://codesandbox.io/s/reverent-hoover-qfqrd
- Demo: https://qfqrd.sse.codesandbox.io/

**Comment by matt-joecoffee** [comment] 2021-08-04 22:10
That's interesting. Are there any known conflicts, or scenarios in which the component might miscalculate the image width?

**Comment by styfle** [comment] 2021-08-04 22:21
Not that I'm aware of. Thats why we need steps to reproduce the issue in order to fix it 🙂

**Comment by ijjk** [comment] 2021-09-21 04:11
Closing as this appears to be working correctly, if you are still experiencing problems with this please respond with additional info and we can investigate further.

**Closed by ijjk** 2021-09-21 04:11 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
