### ISSUE TITLE
'sharp' problem..

### ISSUE THREAD

**Issue by gtolarc** [vercel/next.js#21137] opened 2021-01-15 02:32 UTC
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

14

**What browser are you using?**

Chrome

**What operating system are you using?**

Docker (node:14-buster)

**How are you deploying your application?**

next build/start

**Describe the Bug**

'sharp' is not optional during build because of the following code.

https://github.com/vercel/next.js/blob/canary/packages/next/build/index.ts#L413

**Expected Behavior**

Even in an environment where 'sharp' cannot be installed, 'next build' should work well.

**To Reproduce**

```
$ next build
Loaded env from /usr/src/app/.env
info  - Creating an optimized production build...
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry


> Build error occurred
Error: Cannot find module 'sharp'
Require stack:
- /usr/src/app/node_modules/next/dist/build/index.js
- /usr/src/app/node_modules/next/dist/cli/next-build.js
- /usr/src/app/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at /usr/src/app/node_modules/next/dist/build/index.js:11:866
    at async /usr/src/app/node_modules/next/dist/build/tracer.js:1:525 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/node_modules/next/dist/build/index.js',
    '/usr/src/app/node_modules/next/dist/cli/next-build.js',
    '/usr/src/app/node_modules/next/dist/bin/next'
  ]
}
error Command failed with exit code 1.
```

**Comment by darrylmabini** [comment] 2021-01-15 07:09
experiencing same issue using Docker (node:14.5.4 LTS)

**Comment by xunuoi** [comment] 2021-01-15 07:35
Hey, this also do happens on us, we can not deploy new version on docker/k8s now.

And if we install the `sharp` by manual, it would slowdown the whole ci/cd time and sometimes also broken and run node-gyp building because of `sharp`.

Please help this ASAP or give a proper solution? Thanks a lot!

**Comment by timneutkens** [comment] 2021-01-15 08:42
Duplicate of #20456

**Closed by timneutkens** 2021-01-15 08:42 UTC
Labels: template: bug

**Comment by genemators** [comment] 2021-02-08 21:57
For macos users: brew install libvips and voila!
For debian users: apt install libvips approximate answer, I dunno how is it called on debian & arch package managers...

Also, don't forget to upgrade it if it exists already!

**Comment by gtolarc** [comment] 2021-02-09 01:15
In my case, I had a problem because I forgot to add the node_modules folder to dockerignore. Therefore, the sharp built with darwin was copied to the docker image as it was, preventing a new build for linux. It was my mistake, and as you said, there seems to be no problem if you pre-install libvips for each os. @genemators

**Comment by genemators** [comment] 2021-02-09 10:09
> In my case, I had a problem because I forgot to add the node_modules folder to dockerignore. Therefore, the sharp built with darwin was copied to the docker image as it was, preventing a new build for linux. It was my mistake, and as you said, there seems to be no problem if you pre-install libvips for each os. @genemators 

I think it is.

**Comment by balazsorban44** [comment] 2022-01-28 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
