### ISSUE TITLE
next.js bigcommerce demo installation broken

### ISSUE THREAD

**Issue by Hewlbern** [vercel/next.js#18455] opened 2020-10-29 10:06 UTC
# Bug report

## Describe the bug

Bug in installing the demo one click install with bigcommerce

## To Reproduce

Use one click installer with bigcommerce in australia

## Expected behavior

working demo
## Screenshots

21:01:31 | Cloning github.com/Hewlbern/commerce (Branch: master, Commit: 0589ff7)
-- | --
21:01:32 | Cloning completed in 871ms
21:01:32 | Analyzing source code...
21:01:33 | Installing build runtime...
21:01:34 | Build runtime installed: 511.926ms
21:01:34 | Looking up build cache...
21:01:34 | Build cache not found
21:01:35 | Installing dependencies...
21:01:35 | yarn install v1.22.4
21:01:35 | [1/4] Resolving packages...
21:01:35 | [2/4] Fetching packages...
21:01:44 | info fsevents@2.1.3: The platform "linux" is incompatible with this module.
21:01:44 | info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
21:01:44 | [3/4] Linking dependencies...
21:01:44 | warning " > @bigcommerce/storefront-data-hooks@1.0.2" has incorrect peer dependency "react@>=17".
21:01:44 | warning " > @vercel/fetch@6.1.0" has unmet peer dependency "@types/node-fetch@2".
21:01:44 | warning " > @vercel/fetch@6.1.0" has unmet peer dependency "node-fetch@2".
21:01:44 | warning "@bigcommerce/storefront-data-hooks > @vercel/fetch > @vercel/fetch-cached-dns@2.0.1" has unmet peer dependency "node-fetch@*".
21:01:44 | warning "@bigcommerce/storefront-data-hooks > @vercel/fetch > @vercel/fetch-retry@5.0.3" has unmet peer dependency "node-fetch@*".
21:01:44 | warning "next > use-subscription@1.5.0" has incorrect peer dependency "react@^17.0.0".
21:01:44 | warning " > postcss-import@13.0.0" has unmet peer dependency "postcss@^8.0.0".
21:01:44 | warning " > react-ticker@1.2.2" has unmet peer dependency "prop-types@^15.5.4".
21:01:47 | [4/4] Building fresh packages...
21:01:50 | Done in 15.22s.
21:01:50 | Running "yarn run build"
21:01:50 | yarn run v1.22.4
21:01:50 | $ next build
21:01:51 | warn  - You have enabled experimental feature(s).
21:01:51 | warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
21:01:51 | info  - Creating an optimized production build...
21:01:51 | Attention: Next.js now collects completely anonymous telemetry regarding usage.
21:01:51 | This information is used to shape Next.js' roadmap and prioritize features.
21:01:51 | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
21:01:51 | https://nextjs.org/telemetry
21:02:05 | warn - The `conservative` purge mode will be removed in Tailwind 2.0.
21:02:05 | warn - Please switch to the new `layers` mode instead.
21:02:26 | <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (137kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
21:02:26 | <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (126kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
21:02:26 | <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (186kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
21:02:37 | info  - Compiled successfully
21:02:37 | info  - Collecting page data...
21:02:38 | info  - Generating static pages (0/45)
21:02:38 | Unhandled error during request: Error: Page with slug 'en-US/shipping-returns' not found
21:02:38 | at getStaticProps (/vercel/workpath0/.next/serverless/pages/[...pages].js:6748:11)
21:02:38 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
21:02:38 | at async renderToHTML (/vercel/workpath0/node_modules/next/dist/next-server/server/render.js:26:109)
21:02:38 | at async renderReqToHTML (/vercel/workpath0/.next/serverless/pages/[...pages].js:7385:22)
21:02:38 | at async Object.exportPage [as default] (/vercel/workpath0/node_modules/next/dist/export/worker.js:12:92)
21:02:38 | Error occurred prerendering page "/en-US/shipping-returns". Read more: https://err.sh/next.js/prerender-error
21:02:38 | Error: Page with slug 'en-US/shipping-returns' not found
21:02:38 | at getStaticProps (/vercel/workpath0/.next/serverless/pages/[...pages].js:6748:11)
21:02:38 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
21:02:38 | at async renderToHTML (/vercel/workpath0/node_modules/next/dist/next-server/server/render.js:26:109)
21:02:38 | at async renderReqToHTML (/vercel/workpath0/.next/serverless/pages/[...pages].js:7385:22)
21:02:38 | at async Object.exportPage [as default] (/vercel/workpath0/node_modules/next/dist/export/worker.js:12:92)
21:02:39 | Unhandled error during request: Error: Page with slug 'en-US/contact-us' not found
21:02:39 | at getStaticProps (/vercel/workpath0/.next/serverless/pages/[...pages].js:6748:11)
21:02:39 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
21:02:39 | at async renderToHTML (/vercel/workpath0/node_modules/next/dist/next-server/server/render.js:26:109)
21:02:39 | at async renderReqToHTML (/vercel/workpath0/.next/serverless/pages/[...pages].js:7385:22)
21:02:39 | at async Object.exportPage [as default] (/vercel/workpath0/node_modules/next/dist/export/worker.js:12:92)
21:02:39 | Error occurred prerendering page "/en-US/contact-us". Read more: https://err.sh/next.js/prerender-error
21:02:39 | Error: Page with slug 'en-US/contact-us' not found
21:02:39 | at getStaticProps (/vercel/workpath0/.next/serverless/pages/[...pages].js:6748:11)
21:02:39 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
21:02:39 | at async renderToHTML (/vercel/workpath0/node_modules/next/dist/next-server/server/render.js:26:109)
21:02:39 | at async renderReqToHTML (/vercel/workpath0/.next/serverless/pages/[...pages].js:7385:22)
21:02:39 | at async Object.exportPage [as default] (/vercel/workpath0/node_modules/next/dist/export/worker.js:12:92)
21:02:40 | info  - Generating static pages (11/45)
21:02:42 | info  - Generating static pages (22/45)
21:02:43 | info  - Generating static pages (33/45)
21:02:44 | info  - Generating static pages (45/45)
21:02:44 | > Build error occurred
21:02:44 | Error: Export encountered errors on following paths:
21:02:44 | /en-US/contact-us
21:02:44 | /en-US/shipping-returns
21:02:44 | at exportApp (/vercel/workpath0/node_modules/next/dist/export/index.js:25:1103)
21:02:44 | at runMicrotasks (<anonymous>)
21:02:44 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
21:02:44 | at async build (/vercel/workpath0/node_modules/next/dist/build/index.js:39:69)
21:02:44 | error Command failed with exit code 1.
21:02:44 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:02:44 | Error: Command "yarn run build" exited with 1
21:02:47 | Done with "package.json"

**Comment by cauezitto** [comment] 2020-10-30 00:55
I have a same problem

**Comment by lfades** [comment] 2020-10-30 02:07
This should be fixed by this PR: https://github.com/vercel/commerce/pull/48 😌

**Closed by lfades** 2020-10-30 02:07 UTC

**Comment by ploxx95** [comment] 2020-11-29 09:14
i had the same problem , i solved it by following the instruction in orden.
first 👍 

    Install Vercel CLI: npm i -g vercel
    Link local instance with Vercel and Github accounts (creates .vercel file): vercel link
    Download your environment variables: vercel env pull .env.local
second 👍 
Create a new branch git checkout -b MY_BRANCH_NAME
Install yarn: npm install -g yarn
Install the dependencies: yarn
Duplicate .env.template and rename it to .env.local.
Add proper store values to .env.local.
Run yarn dev to build and watch for code changes
The development branch is development (this is the branch pull requests should be made against). On a release, the relevant parts of the changes in the staging branch are rebased into master.


now i have other problem,   Error [BigcommerceApiError]: Big Commerce API error (401)

**Comment by Simonwtaylor** [comment] 2021-01-12 14:21
Did you fix this "now i have other problem, Error [BigcommerceApiError]: Big Commerce API error (401)"? @ploxx95

**Comment by eltel** [comment] 2021-03-21 02:31
> i had the same problem , i solved it by following the instruction in orden.
> first 
> 
> ```
> Install Vercel CLI: npm i -g vercel
> Link local instance with Vercel and Github accounts (creates .vercel file): vercel link
> Download your environment variables: vercel env pull .env.local
> ```
> 
> second 
> Create a new branch git checkout -b MY_BRANCH_NAME
> Install yarn: npm install -g yarn
> Install the dependencies: yarn
> Duplicate .env.template and rename it to .env.local.
> Add proper store values to .env.local.
> Run yarn dev to build and watch for code changes
> The development branch is development (this is the branch pull requests should be made against). On a release, the relevant parts of the changes in the staging branch are rebased into master.
> 
> now i have other problem, Error [BigcommerceApiError]: Big Commerce API error (401)

I too am constantly getting the API error and also had the variables error initially - I got around that by copying them manually from the deploy on Vercel - the API error remains, unfortunately - I can't seem to find a fix for this anywhere and the Shopify integration seems to have drifted off into obscurity - I can't find any working examples :(

A real pity.

**Comment by okbel** [comment] 2021-03-22 17:55
@eltel I'm so sorry that you are encountering issues with Next.js Commerce. The 401 API error seems like the integration installation (env vars, etc) was successful but something is wrong with BigCommerce's API.

Check this [thread](https://twitter.com/jodifungula/status/1371919769201479680) where we were able to set up a clean install from scratch. For issues with BigCommece's API, please reach to [@BigCommerceDevs](https://twitter.com/BigCommerceDevs) at Twitter. They will be able to provide much more insights on their API that we could ever do.

In terms of the integrations that "drifted to obscurity", again, really sorry and sad to hear that. We've been putting a lot of effort here and the only reason we haven't documented fully yet is because we are double checking with a lot of third party providers to make sure this API is sustainable in time. Just a heads up on that front, the UI is completely agnostic, check more [here](https://github.com/vercel/commerce/pull/199) and the provider live under the `framework` folder (e.g Shopify) demo -> https://shopify.demo.vercel.store/. 

Best,
Bel.

**Comment by eltel** [comment] 2021-03-22 19:37
Thanks so much for getting back to me, I'm a big fan of Next and confess to
being a little flustered with my experience with your commerce template.
I'll look into this ASAP - thanks again!

**Comment by jamesryan-dev** [comment] 2021-03-29 19:06
```
    ~/Documents/Code/commerce-next-js-test  on   master   ✔  base 
╰─ yarn install
yarn install v1.22.10
[1/5] 🔍  Validating package.json...
error nextjs-commerce@1.0.0: The engine "node" is incompatible with this module. Expected version "14.x". Got "15.2.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

╭─    ~/Doc/Code/commerce-next-js-test  on   master       1 ✘  base 
╰─ npm install
npm notice
npm notice New minor version of npm available! 7.0.10 -> 7.7.5
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.7.5
npm notice Run npm install -g npm@7.7.5 to update!
npm notice
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: nextjs-commerce@1.0.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @reach/portal@0.11.2
npm ERR! node_modules/@reach/portal
npm ERR!   @reach/portal@"^0.11.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/james/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/james/.npm/_logs/2021-03-29T19_04_29_192Z-debug.log
```

Still erroring

**Comment by FBosler** [comment] 2021-04-14 10:01
Is there a fix for this?

**Comment by michaelozery** [comment] 2021-04-16 07:51
Is there any fix besides downgrading node?

**Comment by FBosler** [comment] 2021-04-16 08:26
@michaelozery removing the `engines` part in `package.json` did the trick for me

**Comment by balazsorban44** [comment] 2022-01-28 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
