### ISSUE TITLE
Next 14 crashing with nodejs modules (Turbo)

### ISSUE THREAD

**Issue by sebolio** [vercel/next.js#57600] opened 2023-10-27 13:11 UTC
### Link to the code that reproduces this issue

https://github.com/sebolio/next14-bug

### To Reproduce

This only happens with Turbo: apparently it ignores the `serverComponentsExternalPackages` setting.

Clone the repo and follow the README:

### Current vs. Expected behavior

WIthout turbo it works fine in Next 13 and 14, but with turbo it appears to ignore the nodejs libraries specified in the `serverComponentsExternalPackages` setting.

### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: N/A
  pnpm: 8.9.2
Relevant Packages:
  next: 14.0.1-canary.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Middleware / Edge (API routes, runtime), Routing (next/router, next/navigation, next/link)

### Additional context

Bug happens in both `next` and `canary` branches, with and without `turbo`.

<sub>[PACK-1955](https://linear.app/vercel/issue/PACK-1955/next-14-crashing-with-nodejs-modules-turbo)</sub>

**Comment by mrlemoos** [comment] 2023-10-27 23:07
Hi 👋

The edge runtime only has access to a few of the Web APIs and may not support the APIs required for your project:
- https://nextjs.org/docs/pages/api-reference/edge

Under the hood, `knex` calls `require()` function to load the drivers for the specific database that you use. (take a look at the [lib/knex-builder/internal-config-resolver](https://github.com/knex/knex/blob/master/lib/knex-builder/internal/config-resolver.js) file. However, `require()` is not allowed on the edge (screenshot below).

![Screenshot 2023-10-27 at 8 03 16 pm](https://github.com/vercel/next.js/assets/69330304/027f4f2a-c4a1-4cea-b26c-f6af7e57569f)

I hope I helped you.

**Comment by sebolio** [comment] 2023-10-28 05:51
Hi @mrlemoos, could you please elaborate a little on the subject? The documentation you linked doesn't mention Turbopack, I can't see the relation between the runtime and the packer, I even saw an issue here about Turbo not supporting Edge.

To my understanding, unless you specify a different runtime, Node is picked by default, isn't it?

**Comment by krijoh92** [comment] 2023-10-29 22:39
I see the same in RSC's that import anything that depends on `knex` or some other library using dynamic `require`s , even though I've defined them in `serverComponentsExternalPackages` . 

For me it complains with or without turbo though. 
I have a pnpm monorepo with multiple shared packages, not sure if that affects things. Can set up a reproducable repo if needed.

**Comment by imranhrafi** [comment] 2023-11-11 11:12
I encountered a similar issue on my Manjaro OS (Arch Linux). The problem was resolved by installing Node.js through the Snap package manager. For those facing a similar problem, you can find Node.js on Snap at this link: [Node on Snapcraft](https://snapcraft.io/install/node/manjaro).

**Comment by sebolio** [comment] 2023-11-11 20:21
no news on this?

**Comment by ymc9** [comment] 2024-01-16 10:13
Same here. It seems "serverComponentsExternalPackages" is ignored even I'm not using edge runtime.

**Comment by balazsorban44** [comment] 2024-02-27 21:36
Closing as there has been no activity since asking for a reprodcution. If you still experience this bug, please open a new issue with an attached (public!) code repo.

**Closed by balazsorban44** 2024-02-27 21:36 UTC
Labels: please add a complete reproduction, template: bug, area: Routing, area: Edge, linear: turbopack
