### ISSUE TITLE
Yarn workspace + dynamic import not rendering on the server

### ISSUE THREAD

**Issue by kedarguy** [vercel/next.js#5511] opened 2018-10-24 08:53 UTC
# Bug report

## Describe the bug

When using yarn workspaces, dynamically importing a component inside a component that was imported from a different workspace, wont render on the server.

If a loading component is not supplied to the dynamic import it will first render an error message before rendering the actual component. 

When supplying the loading component it will render it first and then render the dynamically imported one.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to [Reproduction-repo](https://github.com/kedarguy/next-dynamic-import-workspace-repo)
2. clone
3. Follow instructions on readme.md to install deps and start the server

## Expected behavior
The Dynamically imported component to render on the server as happens when dynamically importing from the same workspace (also demonstrated in repo).

![ezgif com-gif-maker](https://user-images.githubusercontent.com/23150397/47419412-cf65a480-d784-11e8-81b2-1f5ec6f71385.gif)

**Comment by Ehesp** [comment] 2018-10-26 08:42
Is this specifically workspace related? I've been having similar issues where the dynamic import isn't loading on the server, just the client like your example shows.

https://spectrum.chat/next-js/?thread=d3007af0-d6df-424c-802b-6c5dbfc7822b

Thats the thread I made... not sure if it's 100% related!

**Comment by kedarguy** [comment] 2018-10-26 10:48
@Ehesp I think the cases are a bit different since in my case I dont get the dynamically imported component on server render, it just shows the loading component and then the dynamically imported one.

**Comment by TxHawks** [comment] 2018-11-13 11:36
Any news on this it possible workaround?

**Comment by timneutkens** [comment] 2018-11-13 18:22
I don't think the issue label can be clearer than it is: "needs investigation"

**Comment by TawKhoury** [comment] 2019-02-12 11:05
Same issue. Any updates?

**Comment by timneutkens** [comment] 2019-02-12 12:15
@TawKhoury please use the GitHub 👍 feature on the initial issue instead of posting "any updates". As you can see on the issue label it says "needs investigation" as said before. I've added `help wanted` and `good first issue`, so if you want to contribute feel free to 🙏

**Comment by TxHawks** [comment] 2019-02-17 12:15
@timneutkens Any hints on where in the codebase to look?

**Comment by nataliemarleny** [comment] 2019-05-10 22:26
## Yarn workspace + dynamic import not rendering on the server #5511


I wasn't able to figure this out completely. 

Here's what I discovered by making modifications to reproduction-repo.

If this is the modified code:

```js
// packages/project-app/pages/index.js
const localCallback = () => import("../components/DynamicComponent");
console.log(localCallback.toString())
```

this is printed to the console:

```js
function DynamicComponent() {
  return __webpack_require__.e(/*! import() */ 0).then(__webpack_require__.bind(null, /*! ../components/DynamicComponent */ "./components/DynamicComponent.js"));
}
```

If this is the modified code:

```js
// packages/project-components/src/Parent.js
const DynamicComponent = () => import("./DynamicChild");
export default DynamicComponent;
```

```js
// packages/project-app/pages/index.js
import { Parent } from "@project/components";
console.log(Parent.toString())
```

this is printed to the console:

```js
function DynamicComponent() {
  return import("./DynamicChild");
}
```

Unfortunately however - I don't yet know what this means.

**Comment by Timer** [comment] 2020-07-19 05:31
Closing this issue as the provided reproduction no longer functions correctly. We've made a lot of fixes to this behavior though, so let us know if it's still not working with Next.js 9.4+!

**Closed by Timer** 2020-07-19 05:31 UTC
Labels: good first issue, type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-29 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
