### ISSUE TITLE
Running next lint doesn't create a .eslintrc.json file when using the app directory.

### ISSUE THREAD

**Issue by ghost** [vercel/next.js#50761] opened 2023-06-04 14:18 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: 8.6.0
    Relevant packages:
      next: 13.4.5-canary.4
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/tyler-lutz/playground

### To Reproduce

Create a new project using the app directory and delete the .eslintrc.json file then run next lint.

### Describe the Bug

Running next lint while using the app folder and not the pages folder doesn't create the .eslintrc.json file

### Expected Behavior

Running next lint should create an .eslintrc.json file if one doesn't exist when using the app folder.

**Comment by danivideda** [comment] 2023-06-29 10:45
I have this exact problem too. 
ESLint only works when I build a new Next app with ESLint checked. Otherwise, running `npm run lint` or `yarn lint` after the Next app is created (without ESLint pre-configured when creating), it will only install the dependencies and but not the .eslintrc.json as it should be

**Comment by lemavorum** [comment] 2023-07-08 16:35
It happens to me as well. Only under the `app` router system though. `pages` seems to be just fine.

**Comment by Freshu23** [comment] 2023-07-11 19:02
Same here 💁

**Comment by ryantang333** [comment] 2023-08-04 19:08
Current workaround for those who are strictly using the `app` router is to just add an empty `pages` folder, run `yarn lint` to get the `eslintrc.json` created, then delete the `pages` folder.

**Comment by Hoody91** [comment] 2023-10-30 10:29
Confirmed this is still happening on Next 14.0.0, although the workaround @ryantang333 mentioned did work and created the `eslintrc.json` as expected

**Comment by derekjwilliams** [comment] 2024-03-12 22:08
ryantang333 has the workaround, thanks so much.  But I'm surprised that this is not better documented.  I wasted a bit of time trying to figure this out.  Should likely not be marked as Closed since the Next eslint plugin instructions don't include the workaround.

**Comment by Zenb0t** [comment] 2024-03-15 20:17
[Seems to be fixed here](https://github.com/vercel/next.js/commit/4c5384351c537c05d71ddee96704a06335557fad).

I was running version on ` "next": "14.1.0",` and still had the issue. Workaround fixed it.

**Comment by devjiwonchoi** [comment] 2024-10-14 18:56
Fixed by https://github.com/vercel/next.js/issues/50761. Thank you for opening the issue!

**Closed by devjiwonchoi** 2024-10-14 18:56 UTC
Labels: bug
