### ISSUE TITLE
When query is added to next/link, and an 'as' prop is present, the page reloads without the new query present

### ISSUE THREAD

**Issue by studiocadogan** [vercel/next.js#27235] opened 2021-07-16 14:01 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

16.3

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### How are you deploying your application?

Other Platform

### Describe the Bug

When I create a Link component using next/link, with both an `as` prop and a `href` prop which either contains a query string or query object, instead of SPA-routing (forgive me, I don't know the proper terminology) to the new page with the hidden query parameters, it load the url as a new page, without the hidden query parameters.

For this to occur, a url rewrite needs to be present in `next.config.js`.

### Expected Behavior

Given one of the following component:

```
<Link href={"/test?foo=bar"} as={"/test"}>Test Link</Link>
// Or
<Link href={{
  pathname: "/test",
  query: { foo: "bar" },
  }}
  as={"/test"}>
  Test Link
</Link>
```

and the following rewrite in `next.config.js`:

```
{ source: "/:wildcard*", destination: "/wildcardRoute" }
```

When the user clicks on the above link, the page should client-side navigate to `/test` and display the `wildcardRoute` page with the query `{foo: "bar"}`

### To Reproduce

Instead, the page reloads and the user is navigated to the `/test`, loading the `wildcardRoute` page without the `{foo: "bar"}` query present. A 404 error is present prior to this reload:

`GET http://localhost:3000/_next/static/chunks/pages/test.js net::ERR_ABORTED 404 (Not Found)`

It appears that it is attempted to load the given `pathname` in this instance, rather than loading the appropriate page file as specified in the rewrites. This does not occur when the `as` prop is not present.

**Comment by ijjk** [comment] 2021-07-18 03:11
Hi, this appears to be a duplicate of https://github.com/vercel/next.js/issues/26169 I'm going to close this in favor of that one

**Closed by ijjk** 2021-07-18 03:11 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
