### ISSUE TITLE
[NEXT-1231] This is probably a bug in the React Server Components bundler.

### ISSUE THREAD

**Issue by codeawy** [vercel/next.js#50243] opened 2023-05-24 02:12 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.3
      eslint-config-next: 13.4.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4

warn  - Latest canary version not detected, detected: "13.4.3", newest: "13.4.4-canary.6".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Link to the code that reproduces this issue or a replay of the bug

npx create-next-app --example reproduction-template-app-dir reproduction-app

### To Reproduce

When attempting to generate a new Next.js project using the command `npx create-next-app@latest`, **I encountered an error in app-router.js# related to the React Client Manifest.** This error is likely due to a bug in the React Server Components bundler, which was triggered after running the `npm run dev` command.

![image](https://github.com/vercel/next.js/assets/109562935/9a5554c3-65c8-4c05-be28-8afc502f5110)

### Describe the Bug

![image](https://github.com/vercel/next.js/assets/109562935/e138e9a6-69fe-410c-b537-3d16b20d4b8e)

### Expected Behavior

Generate a new Next.js app with the latest features

<sub>[NEXT-1231](https://linear.app/vercel/issue/NEXT-1231/this-is-probably-a-bug-in-the-react-server-components-bundler)</sub>

**Comment by hiramhuang** [comment] 2023-05-25 09:33
Same issue here. I'm running on `next@13.4.2`, and this error only occur on production build.

**Comment by codeawy** [comment] 2023-05-25 10:29
I tried to generate a new project now, and this working fine ❤️

**Comment by leimonio** [comment] 2023-06-09 15:08
I'm facing a similar issue running NextJS application through a custom http server, using the `next` module. 
The module itself exists in the given path, but there is also a hash appended. 

```
Uncaught Error: Could not find the module "{absolutePathToFolder}/bit-next-app-type/node_modules/.pnpm/next@13.4.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/image.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at resolveClientReferenceMetadata (webpack-internal:///(sc_server)/../../../../../.pnpm/next@13.4.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:205:27)
```

**Comment by leimonio** [comment] 2023-06-09 16:29
@shuding After a bit further debugging of this it seems like `webpackMap` here only includes references from inside `components` folder but nothing related to the `client/image.js` https://github.com/vercel/next.js/blob/2226d2935f04e10de0a5d563067e7d32e6872f00/packages/next/src/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js#LL2948C10-L2948C32

**Comment by simrin3308** [comment] 2023-06-23 05:30
Faced the same error today. Any fix?

**Comment by shawnesquivel** [comment] 2023-06-30 23:54
Any fix for this? Finding that some people can run `npm install` on my project, but when they run `npm run dev` they get this error.

**Comment by desca96aws** [comment] 2023-07-01 02:08
![image](https://github.com/vercel/next.js/assets/135746162/60cf1958-8010-415c-8176-8cafc01a3365)
 
I get the same issue in the browser, this is what I get in the terminal

**Comment by gharis94** [comment] 2023-07-03 04:52
I am having the same issue, did anyone resolve it? if yes then please share.

**Comment by darasus** [comment] 2023-07-03 11:11
I'm getting similar issue only when running route on `edge`.

**Comment by stevedeighton** [comment] 2023-07-03 20:28
I'm seeing this error when using the Image component. I'm on next@13.4.8 which was released just a few hours ago. Everything is working as expected until I use the  Image component. I get this error...

`Error: Could not find the module "MY_PROJECT_PATH/node_modules/next/dist/client/image-component.js#Image" in the React Client Manifest. This is probably a bug in the React Server Components bundler.`

I also see this in the console...

`error node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js (188:12) @ resolveClientReferenceMetadata`.

Maybe this issue can be reopened please?

**Comment by eliasbauer1** [comment] 2023-07-08 20:33
### Solved the problem
Solve: **I added "use client" in the parent component.** 
Explanation: I rendered the child component dynamically, so if I tried to use useEffect on the child component, it didn't work. For it to not get rendered on the server (and throw the error) I added "use client".

**Comment by alexkirsz** [comment] 2023-07-10 10:33
I think this is about as small a repro as I can make it. The issue seems to stem from using a dynamic import. I've personally encountered this while loading MDX components, but this can occur with any kind of component.

Repro: https://github.com/alexkirsz/next-app-router-dynamic-issue

**Comment by stevedeighton** [comment] 2023-07-10 10:51
> alexkirsz/next-app-router-dynamic-issue

Yes good call. My project is using dynamic imports too!

**Comment by stevedeighton** [comment] 2023-07-10 13:41
@alexkirsz Looks like this issue isn't isolated to the Image component, as I'm getting the same error when using the link component in a component that's dynamically imported.

`Error: Could not find the module "/MY_PROJECT_PATH/node_modules/next/dist/client/link.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.`

**Comment by gokulkrishh** [comment] 2023-07-12 10:14
@stevedeighton I am having similar issue but for different file.

```
Error: Could not find the module "/vercel/path0/node_modules/next/dist/client/components/error-boundary.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at gb (/var/task/.next/server/chunks/2578.js:7033:27)
    at Ya (/var/task/.next/server/chunks/2578.js:7107:38)
    at Object.toJSON (/var/task/.next/server/chunks/2578.js:6871:20)
    at stringify (<anonymous>)
    at ib (/var/task/.next/server/chunks/2578.js:7278:9)
    at fb (/var/task/.next/server/chunks/2578.js:7177:29)
    at Timeout._onTimeout (/var/task/.next/server/chunks/2578.js:7002:16)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '1623416432'
}

```

**Comment by gokulkrishh** [comment] 2023-07-12 11:33
Found out that error.tsx file for error handling was missing. Even though there was no error in development but got the above issue in production.

**Comment by ctkc** [comment] 2023-07-12 14:24
@gokulkrishh I had the same error. In my case I was implementing `global-error.tsx` and I was getting this issue during the productive build, I removed it and it's working properly now

**Comment by gokulkrishh** [comment] 2023-07-12 15:16
@ctkc Yes looks like it, global-error.tsx file caused this issue. Resolved it by removing it. Thanks.

**Comment by stevedeighton** [comment] 2023-07-12 15:20
I have also spotted this error using `useState`. It appears anything that's client side isn't working with dynamic imports, unless I'm doing something totally wrong. I have tried adding `use client` to all of my components but it's still not playing nice. I'll be reverting to the pages router for now :(

**Comment by louisthomaspro** [comment] 2023-07-15 05:14
This error is so weird.. I had it for a moment. I switched branch, then came back to the my main branch. And the error disappeared.
My error log was:
```
Error: Could not find the module "/home/louis/git/minea/minea-front-v2/components/layouts/side-sheet-wrapper.tsx#SideSheetWrapper" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
```

**Comment by keno-reloaded** [comment] 2023-07-15 09:00
Getting the following error:

`Error: Could not find the module "/Users/[user]/Projects/ProjectName/components/Modal.tsx#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.`

NextJs version:
`"next": "^13.4.10",`

Node version:
`v18.16.0`

I'm using the **Intercepting Routes** feature.

It was working yesterday, I updated NextJs today, and it is not working anymore.

- app
  - layout.tsx (modal is added in the layout)
  - page.tsx
  - project/[id]
    - page.tsx
  - @modal
    - (.)project/[id]
      - page.tsx
    
    
 Things I've tried so far without success:
 - Delete `.next` folder
 - Delete `node_modules` folder
 - Delete `package-lock.json`
 - `npm cache clean --force`
 - `npm install`

**Comment by askinbilir** [comment] 2023-07-15 18:52
> Getting the following error:
> 
> `Error: Could not find the module "/Users/[user]/Projects/ProjectName/components/Modal.tsx#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.`
> 
> NextJs version: `"next": "^13.4.10",`
> 
> Node version: `v18.16.0`
> 
> I'm using the **Intercepting Routes** feature.
> 
> It was working yesterday, I updated NextJs today, and it is not working anymore.
> 
> * app
>   
>   * layout.tsx (modal is added in the layout)
>   * page.tsx
>   * project/[id]
>     
>     * page.tsx
>   * @modal
>     
>     * (.)project/[id]
>       
>       * page.tsx
> 
> Things I've tried so far without success:
> 
> * Delete `.next` folder
> * Delete `node_modules` folder
> * Delete `package-lock.json`
> * `npm cache clean --force`
> * `npm install`

I faced with same issue, I don't know the problem, but I guess client components cause the crash when I remove them it's working so if you convert all components to server components, probably will work.

**Comment by IamSolaSholzy01** [comment] 2023-07-16 00:40
> Getting the following error:
> 
> `Error: Could not find the module "/Users/[user]/Projects/ProjectName/components/Modal.tsx#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.`
> 
> NextJs version: `"next": "^13.4.10",`
> 
> Node version: `v18.16.0`
> 
> I'm using the **Intercepting Routes** feature.
> 
> It was working yesterday, I updated NextJs today, and it is not working anymore.
> 
> * app
>   
>   * layout.tsx (modal is added in the layout)
>   * page.tsx
>   * project/[id]
>     
>     * page.tsx
>   * @modal
>     
>     * (.)project/[id]
>       
>       * page.tsx
> 
> Things I've tried so far without success:
> 
> * Delete `.next` folder
> * Delete `node_modules` folder
> * Delete `package-lock.json`
> * `npm cache clean --force`
> * `npm install`

I'm now facing the same issue after upgrading from Next 13.4.7 to 13.4.10. 
V13.4.8 had a different issue, that caused a client exception.

**Comment by monzim** [comment] 2023-07-16 11:40
Same issue
NextJs version: "next": "13.4.10",
React:  "react": "18.2.0",


`@modal

(.)project/[id]

page.tsx`

**Comment by piedrahitapablo** [comment] 2023-07-16 23:30
> Getting the following error:
> 
> `Error: Could not find the module "/Users/[user]/Projects/ProjectName/components/Modal.tsx#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.`
> 
> NextJs version: `"next": "^13.4.10",`
> 
> Node version: `v18.16.0`
> 
> I'm using the **Intercepting Routes** feature.
> 
> It was working yesterday, I updated NextJs today, and it is not working anymore.
> 
> * app
>   
>   * layout.tsx (modal is added in the layout)
>   * page.tsx
>   * project/[id]
>     
>     * page.tsx
>   * @modal
>     
>     * (.)project/[id]
>       
>       * page.tsx
> 
> Things I've tried so far without success:
> 
> * Delete `.next` folder
> * Delete `node_modules` folder
> * Delete `package-lock.json`
> * `npm cache clean --force`
> * `npm install`

I was facing the same issue, downgrading to 13.4.7 fixed the problem. The [nextgram](https://github.com/vercel-labs/nextgram/blob/main/package.json#L12) example is using that version.

**Comment by kieranm** [comment] 2023-07-17 09:18
This appears to have broken our intercepting routes too, but only in the Vercel environment, not locally.
We are on 13.4.8 at the moment.

```
Error: Could not find the module "/vercel/path0/apps/.../app/[locale]/@modal/(.)settings/layout.tsx#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at nb (/var/task/apps/app.daybridge.com/.next/server/chunks/947.js:60872:27)
    at eb (/var/task/apps/app.daybridge.com/.next/server/chunks/947.js:60956:38)
    at Array.toJSON (/var/task/apps/app.daybridge.com/.next/server/chunks/947.js:60710:20)
    at stringify (<anonymous>)
    at pb (/var/task/apps/app.daybridge.com/.next/server/chunks/947.js:61127:9)
    at mb (/var/task/apps/app.daybridge.com/.next/server/chunks/947.js:61026:29)
    at Timeout._onTimeout (/var/task/apps/app.daybridge.com/.next/server/chunks/947.js:60841:16)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
Error: Could not find the module "/vercel/path0/apps/app.daybridge.com/app/[locale]/@modal/(.)settings/page.tsx#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at nb (/var/task/apps/app.daybridge.com/.next/server/chunks/947.js:60872:27)
    at eb (/var/task/apps/app.daybridge.com/.next/server/chunks/947.js:60956:38)
    at Array.toJSON (/var/task/apps/app.daybridge.com/.next/server/chunks/947.js:60710:20)
    at stringify (<anonymous>)
    at pb (/var/task/apps/app.daybridge.com/.next/server/chunks/947.js:61127:9)
    at mb (/var/task/apps/app.daybridge.com/.next/server/chunks/947.js:61026:29)
    at Timeout._onTimeout (/var/task/apps/app.daybridge.com/.next/server/chunks/947.js:60841:16)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

**Comment by piedrahitapablo** [comment] 2023-07-17 14:45
I think this is related to #52681

**Closed** 2023-07-17 17:41 UTC
Labels: template: bug, linear: next

**Comment by pawanrana1992** [comment] 2023-07-18 04:27
Guys please remove `global-error.tsx` it is the culprit here. I tried many things but this issue with error handling from nextjs side. Nextjs team should look into it on priority.
`version: "next": "13.4.10", (app-directory)`

**Comment by timneutkens** [comment] 2023-07-18 08:45
@pawanrana1992 can you share a reproduction of your application where it fails in a new issue? Might be something in the file? I.e. maybe not rendering `<html>` etc.?

**Comment by dihan48** [comment] 2023-07-18 09:52
@timneutkens https://stackblitz.com/github/easydevgit/next-13-course/tree/master/advanced-routing-intercepting-routes

**Comment by timneutkens** [comment] 2023-07-18 12:47
Please open a new issue as I requested.

**Comment by julioflima** [comment] 2023-07-18 20:43
It was launched the a canary 11. Someone tested if it works?

**Comment by julioflima** [comment] 2023-07-18 20:45
> @timneutkens https://stackblitz.com/github/easydevgit/next-13-course/tree/master/advanced-routing-intercepting-routes

Tested using 13.4.11-canary.0. 

Same!

**Comment by khuezy** [comment] 2023-07-19 01:20
@dihan48 Are you going to create the new issue, or should I?
