### ISSUE TITLE
Head shows HTML comment on initial load

### ISSUE THREAD

**Issue by pavankjadda** [vercel/next.js#36131] opened 2022-04-13 19:26 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

 Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.5
      react: 18.0.0
      react-dom: 18.0.0

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

When I load the page I see HTML comment `<!-->Header Name<!-->` briefly before I see actual title. See the attached video for reference. I see this in all pages of the website

https://user-images.githubusercontent.com/17564080/163253897-f9998c87-fd3e-4507-9afc-df4a662f0605.mov

### Expected Behavior

Page title should appear without HTML comments

### To Reproduce

Create new next.js web page with following content

**index.tsx**
```
export default function IndexPage() {
	return (
		<div>
			<PageHead title="Home" />
			<Home />
		</div>
	);
}
```

**PageHead.tsx**

```
function PageHead(props: { title: string }): JSX.Element {
	return (
		<Head>
			<title>{props.title} | CRMS</title>
			<meta name={props.title} content={props.title} />
		</Head>
	);
}

export default PageHead;
```

**Comment by c0b41** [comment] 2022-04-13 23:05
known issue #35870

**Comment by shuding** [comment] 2022-04-16 07:43
Duplicate of https://github.com/vercel/next.js/issues/35870.

**Closed by shuding** 2022-04-16 07:43 UTC
Labels: template: bug
