### ISSUE TITLE
404 status code on 200 page

### ISSUE THREAD

**Issue by DjilanMouhous** [vercel/next.js#64502] opened 2024-04-15 13:38 UTC
### Link to the code that reproduces this issue

https://github.com/DjilanMouhous/next-404-demo.git

### To Reproduce

1. Go to /src/app/[...slug]/dummyApi/singlePage.ts
2. Edit the time const (line 118) to set your build time
3. npm run build
4. npm run start

### Current vs. Expected behavior

Current Behavior: During the first 5 minutes after build, the page displays correctly. In the next 5 minutes, a simulated 404 error occurs to mimic a temporary WordPress issue. After these initial 10 minutes, the page displays correctly but with a 404 error code.

Expected Behavior: After the issue is resolved, the page should display a 200 status code.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: N/A
  pnpm: 7.30.0
Relevant Packages:
  next: 14.2.1-canary.6 // Latest available version is detected (14.2.1-canary.6).
  eslint-config-next: 14.2.1-canary.5
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next build (local), Other (Deployed)

### Additional context

This code replicates an issue encountered in a Next.js application that displays pages fetched from a WordPress API. Sometimes, the WordPress API returns an invalid format, resulting in a 404 error on the Next.js side. After a successful cache validation, the content displays correctly but with a 404 error code, which adversely affects SEO.

Here is a quick demo with screenshots
1. Build ok, API working fine (expected)
<img width="718" alt="image" src="https://github.com/vercel/next.js/assets/45048891/8e83830f-ff04-4d0e-ad61-cdfe5d815bcb">
2. Revalidation not ok because of Wordpress temporary issue, 404 happening (expected)
<img width="718" alt="image" src="https://github.com/vercel/next.js/assets/45048891/8083300b-57bb-422c-86e0-af62348783b3">
3. Revalidation ok because Wordpress if no longer failing, content is displayed but still have 404 status code (not expected)
<img width="718" alt="image" src="https://github.com/vercel/next.js/assets/45048891/74405094-7248-4869-805b-fbb93b87ccf7">

**Comment by DjilanMouhous** [comment] 2024-04-23 14:58
Hi @ztanner @ijjk , I'm sorry to bother you, but do you know if someone at Next.js has had a chance to look at this issue?

**Comment by shubhankartrivedi** [comment] 2024-05-03 22:12
I feel like it's an issue with your code

**Comment by felixmusmann** [comment] 2024-05-08 15:36
Same issue as in #63478?

**Comment by ijjk** [comment] 2024-05-08 17:43
Gonna close this as duplicate of https://github.com/vercel/next.js/issues/63478 for easier tracking

**Closed by ijjk** 2024-05-08 17:43 UTC
Labels: bug
