### ISSUE TITLE
Production build fails with wasm library

### ISSUE THREAD

**Issue by Dig-Doug** [vercel/next.js#33215] opened 2022-01-12 13:48 UTC
### Run `next info` (available from version 12.0.8 and up)

/bin/sh: 1: pnpm: not found

    Operating System:
      Platform: linux
      Arch: x64
      Version: #51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04

### How are you deploying your application?

Vercel

### Describe the Bug

I am trying to use a wasm library in my project and deploy to vercel. Everything works locally, but when I do a production build I get an error.

```bash
npx yarn build                                                                                                            130 ↵
yarn run v1.22.17
$ next build
info  - Checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully

> Build error occurred
[Error: ENOENT: no such file or directory, open '/tmp/nextjs-wasm-bug/my-app/.next/server/static/wasm/5f7c33a730a3b7c2.wasm'] {
  type: 'Error',
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/tmp/nextjs-wasm-bug/my-app/.next/server/static/wasm/5f7c33a730a3b7c2.wasm'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I've created a full reproduction [here](https://github.com/Dig-Doug/nextjs-wasm-bug).

The project tries to load a wasm library. I've included the src for the wasm library in `wasm-lib` (requires building with bazel), but I've included the generated code so you do not need to build it.

Most of the code is generated by the nextjs starter template, the changes I've made are in:

- `pages/index.js`: Load the wasm library and call the function
- `next.config.js`: Enable web assembly

### Expected Behavior

I should be able to build and run on vercel.

## Build

```bash
cd /tmp
git clone https://github.com/Dig-Doug/nextjs-wasm-bug.git
cd nextjs-wasm-bug/my-app
npx yarn install
```

## Run in dev

Running in dev mode, everything works:

```bash
npx yarn dev
```

## Production build

When trying to make a production build, it fails:

```bash
npx yarn build                                                                                                            130 ↵
yarn run v1.22.17
$ next build
info  - Checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully

> Build error occurred
[Error: ENOENT: no such file or directory, open '/tmp/nextjs-wasm-bug/my-app/.next/server/static/wasm/5f7c33a730a3b7c2.wasm'] {
  type: 'Error',
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/tmp/nextjs-wasm-bug/my-app/.next/server/static/wasm/5f7c33a730a3b7c2.wasm'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by danger-mon** [comment] 2022-01-14 17:25
I also have this issue, works fine when running the dev server but fails when doing a production build. A wasm file looks to have moved to .next/server/static/wasm/... but it has a different hash?

**Comment by balazsorban44** [comment] 2022-01-25 16:38
Duplicate of #25852

**Closed by balazsorban44** 2022-01-25 16:38 UTC
Labels: template: bug, area: Compiler
