### ISSUE TITLE
v12.2.2 handleHardNavigation Invariant: attempted to hard navigate to the same URL

### ISSUE THREAD

**Issue by leonardoTavaresM** [vercel/next.js#39258] opened 2022-08-02 14:23 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

  Operating System: 
	Platform: win32  
	Arch: x64 
	Version: Windows 10 Home Single Language 
  Binaries: 
	Node: 14.18.0 
	npm: N/A Yarn: 
	N/A pnpm: N/A 
  Relevant packages: 
	next: 12.2.2
	eslint-config-next: 12.2.2
	react: 17.0.2
	react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome Version 103.0.5060.134 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

Vercel 

### Describe the Bug

I realized that this bug is very specific when vercel + middleware + nextv12.2.2

It seems that in Next.js v12.2 the internal router does an extra fetch for the current page.js. This didn't happen in the older versions of Nextjs . If the current URL is a dynamic route and is rewritten (our case in Middleware) the extra page.js fetch will result in a 404. This causes an attempt to reload the current page which then runs into the handleHardNavigation error Invariant: attempted to hard navigate to the same URL.

ob: Tests from other users in the canary version also generate the same error

![image](https://user-images.githubusercontent.com/87047109/182393384-f5c3e984-afad-4759-9d77-152950572dc2.png)

![image](https://user-images.githubusercontent.com/87047109/182393337-726081a5-f69e-43d0-b350-c732782b71fd.png)

### Expected Behavior

load the page without errors.

### Link to reproduction

https://router-bug.vercel.app/nieuws (I took the reproduction from someone else facing the same error)

### To Reproduce

(I took the reproduction from someone else facing the same error)

Minimal reproduction repo: https://github.com/FDMediagroep/router-bug

Next Middleware rewrite rules:

    ...
    {
      source: /^\/nieuws$/,
      destination: '/nieuws/overview/1',
    },
    {
      source: /^\/nieuws\?page=(?<pageNr>\d+)/gi,
      destination: '/nieuws/overview/$<pageNr>',
    },
    ...
    Navigating to /nieuws will result in the error as described in the bug description for Next.js v12.2. But not on the older version v12.1.

**Comment by ijjk** [comment] 2022-08-07 16:18
Hi, this appears to be a duplicate of https://github.com/vercel/next.js/issues/38171 so I'm gonna close this in favor of that one, would also be good to confirm you are still seeing this behavior in `v12.2.4`!

**Closed by ijjk** 2022-08-07 16:18 UTC
Labels: template: bug
