### ISSUE TITLE
Custom _app getInitialProps does not run when Component uses getStaticProps

### ISSUE THREAD

**Issue by dsacramone** [vercel/next.js#25165] opened 2021-05-16 07:13 UTC
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

v12.11.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

npm run build

### Describe the Bug

When using a custom _app file with getInitialProps, it will not run getInitialProps if an accessed page has getStaticProps. It is only called 1x at build time. Any subsequent refreshes/pageloads (to gen SSR) does not work.

If a page does not use any fetch methods (getStaticProps etc.), _app's getInitialProps runs as expected on every pageload/refresh.

### Expected Behavior

I'd expect any page with either no fetch methods or with, should always run getInitialProps. _App shouldn't care that an accessed page is statically generated or not. "getInitialProps" should still be called and its passed props passed into the wrapped Component. If I have deep links into my site that need SSR and those pages are statically generated, why can't I take advantage of SSR? I want my _app to blocked fetch items for user sessions (not auth). Even though many of the underlying pages are statically generated.

### To Reproduce

https://github.com/dsacramone/potential-getinitialprops-bug

Just load the page. See that the initial 'index.js' page is good. Click on the "about" link, so the subsequent page is using stale data from "build time" and it will not refresh.

NOTE: this is a prod build. Just run it locally. 

1. npm run build
2. npm run start

**Comment by dsacramone** [comment] 2021-05-16 20:17
**REMOVE THIS. AFTER ADDITIONAL RESEARCH I FOUND THIS IS EXPECTED BEHAVIOR. MY APOLOGIES.**

**Comment by ljosberinn** [comment] 2021-05-17 09:05
@dsacramone you can close the issue yourself :)

**Closed** 2021-05-17 11:31 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
