### ISSUE TITLE
Using basePath with rewrites to proxy to another Next.js site fails when deployed to Netlify or Vercel

### ISSUE THREAD

**Issue by elliottsj** [vercel/next.js#54415] opened 2023-08-23 00:50 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: N/A
      pnpm: 8.6.3
    Relevant Packages:
      next: 13.4.20-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.5.3
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/elliottsj/nextjs-13.4.19-basepath-rewrite-issue

### To Reproduce

Create two Next.js sites `x.example.com` and `y.example.com`, where `y.example.com` has `basePath: '/docs'` and requests to `x.example.com/docs` are proxied to `y.example.com/docs` via [rewrites](https://nextjs.org/docs/pages/api-reference/next-config-js/rewrites).

Observe that the expected behaviour works locally, but fails when deployed to both Netlify and Vercel. Failure modes are different depending on whether the `next` package, the `@netlify/plugin-nextjs` package, or both are upgraded to the latest versions.

A detailed reproduction using Turborepo is described in https://github.com/elliottsj/nextjs-13.4.19-basepath-rewrite-issue.

### Describe the Bug

An unexpected 404 page or infinite redirects occur instead of rendering the expected docs page.

See https://github.com/elliottsj/nextjs-13.4.19-basepath-rewrite-issue for a full description.

### Expected Behavior

The docs page should be rendered as shown here:

<img width="247" alt="image" src="https://github.com/vercel/next.js/assets/2177366/50c2aaad-ed04-4dd4-8dc9-e9b3f874b12a">

### How are you deploying your application? (if relevant)

Netlify and Vercel

**Comment by rafaeloliveiraneves** [comment] 2024-03-18 20:39
Any updates on this? I have the same problem and have already tested with the latest canary version.

**Comment by ijjk** [comment] 2024-03-19 23:40
Hi, the cause for this infinite redirecting shown in the above repro is from the rewrite to the upstream path including a trailing slash when it shouldn't for `/docs` so that it tries to redirect it away. The fix for this can be seen in the fork updated here: https://github.com/ijjk/nextjs-13.4.19-basepath-rewrite-issue

Deployment with updated config can be seen here: https://nextjs-13-4-19-basepath-rewrite-issue-web.vercel.app/docs

**Closed by ijjk** 2024-03-19 23:40 UTC
Labels: template: bug
