### ISSUE TITLE
ReferenceError: exports is not defined with edge runtime

### ISSUE THREAD

**Issue by va3y** [vercel/next.js#51313] opened 2023-06-14 21:30 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.3.0
      npm: 9.6.7
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.6-canary.4
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/va3y/grammy-next-edge/blob/next/pages/api/bot.ts

### To Reproduce

Run the dev server and access the route

```typescript
import { NextResponse } from "next/server";

export const runtime = "edge";

export default async function handler() {
	console.log(module); // OK
	console.log(module.exports); // OK

	console.log(exports); // ReferenceError: exports is not defined

	return new NextResponse("", { status: 200 });
}
```

### Describe the Bug

ReferenceError: exports is not defined

### Expected Behavior

`exports` should be globally accessible. A lot of libraries use it

**Comment by balazsorban44** [comment] 2023-06-16 15:41
This is not standard ESM, the library needs to compile correctly, using `export foo` and/or `export default`

The lib author seems to be correct though: https://github.com/grammyjs/grammY/issues/435#issuecomment-1592411494

`grammy/web` is correctly compiled to ESM. The reproduction does not represent the reported issue, so please add one.

**Comment by maccman** [comment] 2023-09-28 15:21
Here is a basic reproduction of the error: https://github.com/maccman/grammyjs-nextjs-edge-bug

**Comment by balazsorban44** [comment] 2024-02-27 20:57
This has been fixed via https://github.com/vercel/next.js/pull/58967, you can update to at least `14.0.4`. If you think you still have the issue after upgrading, please open a new issue.

**Closed by balazsorban44** 2024-02-27 20:57 UTC
Labels: please add a complete reproduction, template: bug, area: Edge
