### ISSUE TITLE
HMR is unreliable when changing JSX

### ISSUE THREAD

**Issue by eTech-Source** [vercel/next.js#62465] opened 2024-02-24 01:03 UTC
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/vercel-next-js-reproduction-template-go8s7s?file=%2Fapp%2Fpage.tsx%3A5%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clszdcmtv00063b6fxkgcy23l%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clszdcmtv00023b6fdur5qevo%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clszdcmtv00043b6fcsrrvn7q%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clszdcmtv00053b6fwly07d0h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clszdcmtv00023b6fdur5qevo%2522%253A%257B%2522id%2522%253A%2522clszdcmtv00023b6fdur5qevo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clszdd9eq003f3b6f5b1fc8xg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clszdd9eq003f3b6f5b1fc8xg%2522%257D%252C%2522clszdcmtv00053b6fwly07d0h%2522%253A%257B%2522id%2522%253A%2522clszdcmtv00053b6fwly07d0h%2522%252C%2522activeTabId%2522%253A%2522clszdfzlu00lk3b6frtkhiljx%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clszdfzlu00lk3b6frtkhiljx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clszdcmtv00043b6fcsrrvn7q%2522%253A%257B%2522id%2522%253A%2522clszdcmtv00043b6fcsrrvn7q%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clszdcmtv00033b6f16pp98me%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clszdcmtv00033b6f16pp98me%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### To Reproduce

Add "use client" to the top of `page.tsx`. Run the server. Make changes to the JSX.

### Current vs. Expected behavior

Currently the changes won't be reflected in the dev preview. It should refresh.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:00 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6020
  Available memory (MB): 32768
  Available CPU cores: 12
Binaries:
  Node: 21.5.0
  npm: 10.2.4
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.71 // Latest available version is detected (14.1.1-canary.71).
  eslint-config-next: 13.5.6
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by samcx** [comment] 2024-02-27 18:15
@eTech-Source I was not able to reproduce this! Are you testing this in CodeSandbox or locally?

**Comment by eTech-Source** [comment] 2024-02-27 23:20
@samcx This was tested locally. I was able to reproduce this on CodeSandbox but the error occurs mostly locally on a frequently yet not perdidicatably. Also are you using the latest version of Next.js in the sandbox? I know the sandbox still uses an old version of Next.

**Comment by samcx** [comment] 2024-02-27 23:25
@eTech-Source I tested this locally as well on the latest canary. Can you try recording this locally (Replay.io, video)?

**Comment by eTech-Source** [comment] 2024-02-28 02:31
@samcx Can't reproduce the issue anymore. Weird. I will keep you posted if it occurs again,

**Comment by samcx** [comment] 2024-02-28 05:51
@eTech-Source I will be closing this issue since we can't reproduce the issue reliably, but let me know if it occurs again! I believe I can re-open the issue before it locks out (in 2 weeks?).

**Closed by samcx** 2024-02-28 05:51 UTC
Labels: template: bug
