### ISSUE TITLE
Middleware linting error (either linting bug or documentation needs improvement)

### ISSUE THREAD

**Issue by marcofranssen** [vercel/next.js#32847] opened 2021-12-27 15:08 UTC
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next lint

### Describe the Bug

When running `next lint` I'm getting following Error.

```bash
./pages/api/_middleware.js
1:1  Error: next/server should not be imported outside of pages/_middleware.js. See https://nextjs.org/docs/messages/no-server-import-in-page.  @next/next/no-server-import-in-page
```

Either this is a bug in the linter or a bug in the [documentation](https://nextjs.org/docs/messages/no-server-import-in-page).

### Expected Behavior

Either the [documentation](https://nextjs.org/docs/messages/no-server-import-in-page) should be updated or the linting behaviour should be updated to not show a warning for this `_middleware.js`.

### To Reproduce

Create  `pages/api/_middleware.js` and add the following import.

```
import { NextResponse } from "next/server";

export async function middleware(req) {
  // Some logic

  return NextResponse.next();
}
```

**Comment by balazsorban44** [comment] 2021-12-27 16:30
Already fixed in `canary`. Please upgrade, or wait for it to get into `latest`

**Closed by balazsorban44** 2021-12-27 16:30 UTC
Labels: template: bug

**Comment by Kinbaum** [comment] 2022-01-07 14:03
This issue is still present in `12.0.8-canary.19`

```ts
// pages/test/_middleware.ts
```

<img width="414" alt="Screen Shot 2022-01-07 at 9 03 00 AM" src="https://user-images.githubusercontent.com/6590356/148554841-1c04b6b3-7c0a-4e53-9154-3487553bc08f.png">

**Comment by balazsorban44** [comment] 2022-01-07 15:56
Make sure that `eslint-config-next` has also been updated! :+1:

**Comment by balazsorban44** [comment] 2022-02-06 16:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
