### ISSUE TITLE
Feat: On-Demand `revalidate` function should take array of strings also instead of just string

### ISSUE THREAD

**Issue by IamManchanda** [vercel/next.js#34581] opened 2022-02-19 12:05 UTC
### Describe the feature you'd like to request

I just played with On-Demand Incremental Static Regeneration, made myself a demo also https://playing-revalidate.vercel.app/ but I think `revalidate` function should support taking in a list of url paths instead of just single url paths as I think we will have cases where you need to revalidate multiple pages instead of just one single ... I know global propagation time will increase for multiple paths but it will also increase if we do it on developer side, in fact will take more at developer side instead of framework side. 

Thanks and Love 💘 

### Describe the solution you'd like

Currently 

```ts
unstable_revalidate: (urlPath: string) => Promise<void>;
revalidate: (urlPath: string) => Promise<void>; // stable version
```

What I am requesting

```ts
unstable_revalidate: (urlPaths: string | string[]) => Promise<void>;
revalidate: (urlPaths: string | string[]) => Promise<void>; // stable version
```

### Describe alternatives you've considered

N/A

**Comment by IamManchanda** [comment] 2022-02-19 12:11
or maybe a `revalidateAll` function ... whatever seems better ... thanks 😃

**Comment by balazsorban44** [comment] 2022-02-20 00:33
This is a duplicate of #34567

**Closed by balazsorban44** 2022-02-20 00:33 UTC
Labels: template: story

**Comment by IamManchanda** [comment] 2022-02-20 06:58
Thanks for letting me know @balazsorban44 ... I have commented over there instead 👍
