### ISSUE TITLE
Next/image stopped working for .GIF's (except locally), Azure deployed

### ISSUE THREAD

**Issue by AidanRRR** [vercel/next.js#34310] opened 2022-02-14 08:28 UTC
### What version of Next.js are you using?

11.1.4

### What version of Node.js are you using?

16.13.2

### What browser are you using?

Chrome / safari / ...

### What operating system are you using?

Windows

### How are you deploying your application?

Azure (nextjs production build)

### Describe the Bug

At some point, GIFS stopped working for our application. (using next/image). An internal server error, 500 is returned.

Locally they still serve.
Other images still work, although I do notice it to be a lot slower than in the past.

- Image location: embedded in the source code and present on the app service (checked)
- Next.config: added an images section with the correct domains.
(should only be required when using an external URL)

Is there anything that I forgat doing or should do on the deployed environment?
It did used to work, so I'm a bit clueless as what might have triggered this to stop working.

Thanks

### Expected Behavior

GIFS to load with no problems.

### To Reproduce

Import a GIF with nextjs 11.1.4, deploy to Azure.

`import Image from 'next/image';`
`import design from '../assets/sales/design.gif';`

`
              <Image
                src={design}
                alt={title}
                layout="fill"
                quality={95}
                objectFit="cover"
              />
`

Deployed [here](https://seatrtest.azurewebsites.net/).
The other images do load, only the GIFs have problems.

**Comment by balazsorban44** [comment] 2022-02-16 02:13
This sounds like an Azure issue. I deployed this to Vercel, using `next@11.1.4`: https://34310.vercel.app

```js
//pages/index.js
import Image from "next/image"
import img from "../public/earth.gif"

export default function Home() {
  return <Image src={img} alt="Earth" />
}
```
(Downloaded this image locally https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotating_earth_%28large%29.gif)

A few things:
Try to check your server logs, it might tell you more. Make sure your image hosting is working/set up correctly.

Please try upgrading to a newer version of Next.js (`latest` or `canary`) to see if a newer release might not have already fixed your problem.

**Comment by AidanRRR** [comment] 2022-02-21 22:21
Could very well be yes. I've been looking into it for a few days, but it is not very clear. No error is thrown in the backend. Also tried creating deploying to a clean resource on Azure with no luck. Used to work just fine, which is a bit frustrating. Upgrading to the latest version (12) of Nextjs is not possible due to restrictions.

Will not be using next/image anymore. Too bad though, worked just fine until some point.

**Comment by AidanRRR** [comment] 2022-02-21 23:10
The thing also is, it works normal on a local environment (and uses the same url, tried hosting the GIFS externally now) but not when hosting in an azure resource. I'll try it out on another platform.

**Comment by balazsorban44** [comment] 2022-02-22 10:04
While trying to access this image: https://seatrtest.azurewebsites.net/_next/image?url=%2F_next%2Fstatic%2Fimage%2Fsrc%2Fassets%2Fsales%2Fdesign.d60e36529dfa4549f2b6884642bf0e42.gif&w=3840&q=95

It shows "Internal Server Error". You should be seeing the logs where you run `next start`. If you could provide that log information, we might be able to debug this further.

**Comment by AidanRRR** [comment] 2022-02-28 20:42
```
2022-02-28T20:39:38.155008060Z: [INFO]  [0]   code: 'ENOENT',
2022-02-28T20:39:38.155012960Z: [INFO]  [0]   syscall: 'mkdir',
2022-02-28T20:39:38.155017661Z: [INFO]  [0]   path: '/home/site/wwwroot/.next/cache/images'
2022-02-28T20:39:38.155022561Z: [INFO]  [0] }
2022-02-28T20:39:38.155027261Z: [INFO]  [0] [Error: ENOENT: no such file or directory, mkdir '/home/site/wwwroot/.next/cache/images'] {
2022-02-28T20:39:38.155032661Z: [INFO]  [0]   errno: -2,
2022-02-28T20:39:38.155037361Z: [INFO]  [0]   code: 'ENOENT',
2022-02-28T20:39:38.155041861Z: [INFO]  [0]   syscall: 'mkdir',
2022-02-28T20:39:38.155046461Z: [INFO]  [0]   path: '/home/site/wwwroot/.next/cache/images'
2022-02-28T20:39:38.155051061Z: [INFO]  [0] }
```

This error keeps popping up. I've tried redeploying to a clean environment, owning the folder with all permissions and some other things. No luck.

This did used to work and stopped working at some point. It does seem like an azure thing though (as you said).

Next steps: I'll try to deploy a fresh app to Azure with a gif with the same nextjs version and node js version.

**Comment by balazsorban44** [comment] 2022-03-01 00:28
If you are using Docker, have a look at these:

- https://nextjs.org/docs/deployment#docker-image
- https://nextjs.org/docs/advanced-features/output-file-tracing#automatically-copying-traced-files-experimental

Apart from drastically reducing the image size, it might solve the issue as well.

In any case, do tell us when you verified this as a Next.js or an Azure bug. :+1: Happy to investigate further if it's the former.

**Comment by AidanRRR** [comment] 2022-03-01 13:55
Thanks for the tips. Following your message; I do remember that we enabled the following Azure option: 'Run from zip', https://docs.microsoft.com/en-us/azure/app-service/deploy-run-package

This approach allows us to build the website on an Azure build agent and deploy still within 5 minutes. The alternative was making a zip while keeping the symlinks intact and then extracting this on the deployed app service.

The last approach is not ideal at all. It just is a real pain to use Azure with NextJS. I understand that you can use anything to host but it doesn't seem to be optimized to build on another machine than the actual server on which it will run due to native dependencies to that hardware.

I'll investigate or the ZIP feature is responsible for this and test next/image a bit deeper on Azure. Thanks!

**Comment by AidanRRR** [comment] 2022-03-03 20:10
Thanks @balazsorban44 for the advice!

It indeed is the `WEBSITE_RUN_FROM_PACKAGE` setting on Azure App services ([link](https://docs.microsoft.com/en-us/azure/app-service/deploy-run-package)) that is causing the issue.

The feature is really neat as it drastically reduces release time on an Azure deployment. Using the traditional 'Package deployment using ZIP Deploy' method eliminates the problem but it takes forever (like 15minutes) to send the prepared application (it already includes the `node_modules` folder).

**However**, one of the points it says on the page: 'Running directly from a package makes wwwroot read-only. Your app will receive an error if it tries to write files to this directory.'

So probably, it cannot use the .next directory I guess to write stuff?
And in the prepared zip, there is a `.next/cache` folder but no `.next/cache/images`.

**Comment by balazsorban44** [comment] 2022-03-03 20:44
Thanks for confirming. This sounds like a platform issue then, and not a bug in Next.js. Closing, but feel free to report back how it went. :+1:

**Closed by balazsorban44** 2022-03-03 20:44 UTC
Labels: please add a complete reproduction, area: next/image
