### ISSUE TITLE
Issue when redirecting from Server Action -> Route Handler -> new page

### ISSUE THREAD

**Issue by cloudkite** [vercel/next.js#59217] opened 2023-12-03 20:04 UTC
### Link to the code that reproduces this issue

https://github.com/cloudkite/next-redirect-bug

### To Reproduce

1. run `npx next dev`
2. click submit button

### Current vs. Expected behavior

Expected: 
When clicking submit page server action redirects to /redirect_route which in turn redirects to /hello.

Actual
URL changes to /redirect_route but displays the content from /hello

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
Binaries:
  Node: 20.8.1
  npm: 10.1.0
  Yarn: 1.22.15
  pnpm: N/A
Relevant Packages:
  next: 14.0.4-canary.37
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by MDFARHYN** [comment] 2023-12-04 02:18
solved https://github.com/MDFARHYN/next-redirect-bug

**Comment by cloudkite** [comment] 2023-12-04 07:25
@MDFARHYN reason it’s a route is that I want to determine redirect path dynamically server-side based on session, database etc.

**Comment by cloudkite** [comment] 2023-12-04 23:23
This problem also occurs when redirecting from middleware

**Comment by shuding** [comment] 2023-12-05 19:47
Looks like a duplicate of #58281?

**Comment by mgray-bemyduo** [comment] 2023-12-09 17:24
@shuding  Even with these bug fixes that were supposed to resolve this, I'm still getting errors in 14.0.4

https://github.com/vercel/next.js/pull/59017
https://github.com/vercel/next.js/pull/58885

<img width="684" alt="Screenshot 2023-12-09 at 9 23 40 AM" src="https://github.com/vercel/next.js/assets/127164822/f381a432-9daa-47af-ade8-a98106dce258">

**Comment by bemyduo-admin** [comment] 2023-12-14 15:10
@MDFARHYN Please see above. Server Actions are unusable with Middleware because this bug is still not fixed.

**Comment by leerob** [comment] 2023-12-30 20:14
> The reason it’s a route is that I want to determine redirect path dynamically server-side based on session, database etc.

I would recommend doing this in a Server Action and not having a redirect -> redirect -> page. Any reason you can't do that?

**Comment by bemyduo-admin** [comment] 2024-01-01 17:52
@leerob  Can you tell me how I can keep my Server Actions  DRY (Don't Repeat Yourself) without using middleware? The whole point is that every single server action should go through rate limiting and the internationalization middleware should work without breaking whenever a user is redirected to the blocked page after being rate limited too many times.

**Comment by leerob** [comment] 2024-01-01 18:01
For some reading on the merits of DRY: https://overreacted.io/the-wet-codebase/

But to your point, can't it a be a function that's called in Middleware and your Server Action?

**Comment by bemyduo-admin** [comment] 2024-01-01 18:05
@leerob  it does NOT work if I use it in Middleware. That's the problem. If I put it in the middleware I get the error as shown at the bottom of the image I shared. I haven't tried to do the redirect directly in the server action because I don't want to have to copy and past the rate limiting code in every single server action because it doesn't really make sense. This also violates the single responsibility rule. The server action shouldn't also have to figure out the rate limiting logic.

**Comment by jimzer** [comment] 2024-02-12 11:42
Having the same issue, I redirect in server action to /page and expect the middleware logic to add locales to kick in to end up on /en/page
The page is rendered properly but the url stays at /page which is a problem.

**Comment by styleai-luke** [comment] 2024-05-20 08:52
Same problem

**Comment by humont** [comment] 2024-06-02 16:14
Similar problem with using a serverAction redirect whilst having middleware rewrites (e.g when doing something similar to the Platform Starter Kit)

e.g: 



middleware.ts
```
import { NextRequest, NextResponse } from "next/server";

export const config = {
  matcher: [
    /*
     * Match all paths except for:
     * 1. /api routes
     * 2. /_next (Next.js internals)
     * 3. /_static (inside /public)
     * 4. all root files inside /public (e.g. /favicon.ico)
     */
    "/((?!api/|_next/|_static/|_vercel|[\\w-]+\\.\\w+).*)",
  ],
};

export default async function middleware(req: NextRequest) {
  console.log("Middleware Called");
  const url = req.nextUrl;
  const subdomain = req.headers.get("host")?.split(".")[0];
  const searchParams = req.nextUrl.searchParams.toString();
  // Get the pathname of the request (e.g. /, /about, /blog/first-post)
  const path = `${url.pathname}${
    searchParams.length > 0 ? `?${searchParams}` : ""
  }`;

  if (subdomain === process.env.NEXT_PUBLIC_ROOT_DOMAIN) {
    // If the subdomain is app or the root domain, redirect to the SaSS website
    let rewriteUrl = new URL(`/saas${path}`, req.url);
    return NextResponse.rewrite(rewriteUrl);
  }

  // Otherwise redirect to the tenant website
  let rewriteUrl = new URL(`/${subdomain}${path}`, req.url);
  return NextResponse.rewrite(rewriteUrl);
}
```

someServerAction.ts
```
import {redirect} from "next/navigation"

export const action = async () => {
  redirect('/some_path')  
}
```

The URL will render correctly, however the app router will ignore the rewrite, and try and fetch the route from the wrong dir.

oddly enough - the middleware function is still being called prior to render.

**Comment by leerob** [comment] 2024-07-19 18:39
The reproduction in the original issue is not longer available. Please open a new issue with an up-to-date reproduction on the latest `canary` version. Thank you!

**Closed by leerob** 2024-07-19 18:39 UTC
Labels: bug
