### ISSUE TITLE
Next 14. Cannot access displayName.valueOf on the server

### ISSUE THREAD

**Issue by Andrew9614** [vercel/next.js#57586] opened 2023-10-27 11:24 UTC
### Link to the code that reproduces this issue

https://github.com/Andrew9614/next14-bug

### To Reproduce

1. Start next dev
2. Error

### Current vs. Expected behavior

Expected: default missing key prop error in console
Current: Unhandled Runtime Error; Cannot access displayName.valueOf on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
Binaries:
  Node: 20.9.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

If within server component using client component and it has children array without key prop it throw Unhandled Runtime Error "Error: Cannot access displayName.valueOf on the server. You cannot dot into a client module from a server component. You can only pass the imported name through." on parent component

![image](https://github.com/vercel/next.js/assets/54529269/3347c270-ae17-4cc7-9062-0938f4086daa)

Options to work around the problem:
- add key prop
- delete 'use client' in Bug component
- add 'use client' in page.jsx 

<sub>[NEXT-2032](https://linear.app/vercel/issue/NEXT-2032/next-14-cannot-access-displaynamevalueof-on-the-server)</sub>

**Comment by JesseKoldewijn** [comment] 2023-10-27 12:23
Hey @balazsorban44 do you know by chance if there's any fix in the making for named client component imports? This seems to be an issue for quite a while already.

**Comment by Andrew9614** [comment] 2023-10-27 12:37
Important clarification: in previous versions there was no such error. At least I didn’t notice it in my projects

**Comment by JesseKoldewijn** [comment] 2023-10-27 12:41
I did notice unreliable behaviour with named client components previously and also noticed multiple issue related to them back then. If this is intended behaviour it might be a good idea to include a rule to the nextjs eslint config, ts-plugin and/or docs.

**Comment by Sravan1011** [comment] 2023-10-28 05:26
So is the bug solved is still an issue ?

**Comment by JesseKoldewijn** [comment] 2023-10-28 09:51
> So is the bug solved is still an issue ?
> 
> 

What do ya mean?

**Comment by Sravan1011** [comment] 2023-10-28 10:06
I wanted ask if the error is solved ? I meant unhandaled error

**Comment by JesseKoldewijn** [comment] 2023-10-28 10:16
> I wanted ask if the error is solved ? I meant unhandaled error 

If you use a default export in client components, yes

**Comment by Sravan1011** [comment] 2023-10-28 18:11
okay thanks for the information

**Comment by justkahdri** [comment] 2023-10-30 20:36
I worked around it changing the export in the client component:
```tsx
"use client"

export const Link = () => {
  // ...
}

export const Dropdown = () => {
  // ...
}

export const Wrapper = () => {
  // ...
}
```

into this:

```tsx
"use client"

const Link = () => {
  // ...
}

const Dropdown = () => {
  // ...
}

const Wrapper = () => {
  // ...
}

module.exports = { Link, Wrapper, Dropdown }
```

**Comment by JesseKoldewijn** [comment] 2023-10-30 21:29
you could do the same with a default export instead of the module.exports bit

like
```
export default { Link, Wrapper, Dropdown }
```

**Comment by Sravan1011** [comment] 2023-11-18 07:29
"use client"

const Link = () => {
}

const Dropdown = () => {
}

const Wrapper = () => {
}

export { Dropdown, Link, Wrapper }
module.exports = { Link, Wrapper, Dropdown }

using this you can't have the error it's solved using this

**Comment by JesseKoldewijn** [comment] 2023-11-28 12:07
> Still facing this problem:
> 
> ```js
> import {Table, TableTbody, TableTd, TableTr} from "@mantine/core";
> import {Subject, subjects} from "@src/shared/api/temporary/api";
> import {FunctionComponent} from "react";
> 
> interface SubjectWithIndex extends Subject {
>     index: number
> }
> 
> const SubjectComp: FunctionComponent<SubjectWithIndex> = (subject) => {
>     return (
>         // <TableTr key={subject.index}>
>         //     <TableTd>
>         //         <pre>{subject.time}</pre>
>         //     </TableTd>
>         //     <TableTd>{subject.name}</TableTd>
>         //     <TableTd>{subject.description}</TableTd>
>         //     <TableTd>{subject.homework}</TableTd>
>         //     <TableTd>{subject.color}</TableTd>
>         // </TableTr>
>         <>
>         </>
>     )
> }
> 
> const ScheduleEdit = () => {
>     const rows = subjects.map((subject, index) => (
>         <SubjectComp index={index}
>                      name={subject.name}
>                      description={subject.description}
>                      homework={subject.homework}
>                      color={subject.color}/>
>     ));
> 
>     return (
>         <Table className="rounded" p={10}>
>             <TableTbody>
>                 {rows}
>             </TableTbody>
>         </Table>
>     );
> };
> 
> export {ScheduleEdit};
> ```

Have you tried any of the suggested solutions?

**Comment by Vyacheslav1557** [comment] 2023-11-28 12:11
I do everything as stated in the docs of mantine and idk why I get this error
https://mantine.dev/guides/next/#compound-components-in-server-components

**Comment by JesseKoldewijn** [comment] 2023-11-28 12:16
> I do everything as stated in the docs of mantine and idk why I get this error https://mantine.dev/guides/next/#compound-components-in-server-components
> 
> If the problem is not with me, then I will ask the question on the forum of mantine

It does to me sound more like an issue on mantine's end in your case. They'll prob be the best party to help ya with the issue you're running into.

**Comment by Vyacheslav1557** [comment] 2023-11-28 12:17
> > I do everything as stated in the docs of mantine and idk why I get this error https://mantine.dev/guides/next/#compound-components-in-server-components
> > If the problem is not with me, then I will ask the question on the forum of mantine
> 
> It does to me sound more like an issue on mantine's end in your case. They'll prob be the best party to help ya with the issue you're running into.

ok, thx

**Comment by DusanStojanovic-gowago** [comment] 2023-12-14 10:59
This error started happening in my project after updating from `14.0.3` to `14.0.4`

**Comment by JeremyKennedy** [comment] 2023-12-15 04:07
I got this after updating next from 13 to 14. I'm using Mantine components in a loop. I resolved it by adding a key to the components generated by the loop.

**Comment by Vyacheslav1557** [comment] 2023-12-19 13:24
> I got this after updating next from 13 to 14. I'm using Mantine components in a loop. I resolved it by adding a key to the components generated by the loop.

hehe, same for me

**Comment by sinafath** [comment] 2023-12-28 14:08
> I got this after updating next from 13 to 14. I'm using Mantine components in a loop. I resolved it by adding a key to the components generated by the loop.

that's how the problem fixed for me

**Comment by nephlin7** [comment] 2023-12-29 19:55
> I got this after updating next from 13 to 14. I'm using Mantine components in a loop. I resolved it by adding a key to the components generated by the loop.

This resolved the issue also on my side. On my case I was using a value as a key that returned undefined from my API.

**Comment by JesseKoldewijn** [comment] 2023-12-30 03:10
@Andrew9614 did you manage to fix your code which prompted you initially to open this issue? And if so, could you close this issue. 

If you didn't find a fix yet, feel free to check any of the suggested fixes.🤙

**Comment by huozhi** [comment] 2024-01-14 13:50
This issue is fixed on React side in https://github.com/facebook/react/pull/27930, fixed on Next.js in #60619

**Closed by huozhi** 2024-01-14 13:50 UTC
Labels: template: bug, linear: next
