### ISSUE TITLE
ChunkLoadError   (timeout: (chunks/xxx)

### ISSUE THREAD

**Issue by mdcarter** [vercel/next.js#38507] opened 2022-07-11 08:29 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.2.2
      eslint-config-next: 12.1.5
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Firefox 102.0

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

When a next js project containing static pages is hosted on Vercel (or anywhere I'm guessing) it regularly generate exception related to chunk loading

```js
ChunkLoadError: Loading chunk 3662 failed.
(error: https://xxx.com/_next/static/chunks/29107295-0151559bd23117ba.js)
```

I looked everywhere for a simple fix for this, it exist in dev mode (simply delete the `.next` folder) but nothing for website in production since it's a caching issue.

### Expected Behavior

This should not happen, or generate exceptions

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-ehpskx

### To Reproduce

Create a nextjs project with static pages (via `getStaticProps`), install Sentry for error tracking and generate trafic

**Comment by yoshiko-pg** [comment] 2022-09-05 07:29
I have the same problem, also happening in Chrome and Safari.
When this error occurs, the entire screen also fails.

If the user does a super reload (hold down Shift while reloading) it resolves the problem, but there is no way to make the user do a super reload from javascript.

**Comment by yoshiko-pg** [comment] 2022-09-05 07:56
This error occurs in the production environment and is reported regularly on Sentry.

**Comment by ianwensink** [comment] 2023-02-09 09:41
Does anyone have a solution for this? We are running into this regularly

**Comment by gabrielbull** [comment] 2023-03-01 20:49
This issue still occurs in production environment and happens quite a lot using latest NextJS.

**Comment by igorpwnd** [comment] 2023-03-15 13:36
My application keeps having this problem (with dynamic imports)

**Comment by longyarnz** [comment] 2023-03-20 10:11
This error is thoroughly explained [here](https://stackoverflow.com/questions/60697927/chunkloaderror-loading-chunk-xy-failed-randomly-getting-fatal-on-production). It's an error due to caching split chunks of the js bundle. The bigger issue is that it cannot be recovered from in production. A possible way to fix it is to edit the cache parameters on the index or page file where is the address to the chunk is provided. I don't know how to do that.

**Comment by ianwensink** [comment] 2023-03-20 15:47
You are assuming that this is the issue, but I'm not convinced. For us all of the chunks that are presumably not loading still exist to this day. Even while the loading error was from a month ago, the chunk still exists now.

**Comment by HQ063** [comment] 2023-03-21 15:10
I'm having the same issue with the same situation described by @ianwensink ,  all the chunks still exist and can be accessed.

**Comment by i8ramin** [comment] 2023-05-07 11:40
Also experiencing this very exact problem. commenting here and hoping for some sort of viable solution from either the nextjs or vercel team. Someone mentioned a service worker solution to load all js and chunks. has anyone tried this and does it work?

**Comment by alexgilbertDG** [comment] 2023-05-17 12:53
I got this problem too in production with Vercel...

**Comment by AyrDS** [comment] 2023-05-22 18:03
I have the same issue in production, any solution?

**Comment by FengeRVictor** [comment] 2023-05-23 11:45
I have found a solution, don't know if it can help you :

```
// Put all your pages that have this issue
const urls = [
  "/dashboard",
];

const fetchAllPages = () => {
  const requests = urls.map((url) => fetch(url, { cache: "no-cache" }));

  return Promise.all(requests);
};

await fetchAllPages();
```

When you do a fetch with no-cache, it will fetch a new page and you will no longer have this error again for the specific page.

It works for me...

**Comment by raphael1807** [comment] 2023-05-23 13:54
Same

**Comment by davidbnk** [comment] 2023-06-09 19:00
> This error is thoroughly explained [here](https://stackoverflow.com/questions/60697927/chunkloaderror-loading-chunk-xy-failed-randomly-getting-fatal-on-production). It's an error due to caching split chunks of the js bundle. The bigger issue is that it cannot be recovered from in production. A possible way to fix it is to edit the cache parameters on the index or page file where is the address to the chunk is provided. I don't know how to do that.

I dont think this is the problem, at least in my case, because the problematic chuck is accessible after the error has ocurred. For example I get a stacktrace like this in sentry:

```
ChunkLoadError: Loading chunk 707 failed.
(error: https://www.mywebsite.com/_next/static/chunks/707-e73a4e529df34709.js)
  at ? (app:///_next/static/chunks/webpack-aaa2a25000886b98.js:1:3378)
  at ? (app:///_next/static/chunks/webpack-aaa2a25000886b98.js:1:1427)
  at reduce([native code])
  at ? (app:///_next/static/chunks/webpack-aaa2a25000886b98.js:1:1399)
  at c(./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.production.min.js:11:96)
  at c(./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.production.min.js:11:481)
  at X(./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.production.min.js:28:399)
  at c(./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.production.min.js:33:175)
  at promiseReactionJob([native code])
```

If I try to access `https://www.mywebsite.com/_next/static/chunks/707-e73a4e529df34709.js` right after the error has been reported to sentry, it is accessible
My guess is that the loading failed but because of another reason, since the file exists

**Comment by BenBrewerBowman** [comment] 2023-06-22 13:34
Has anyone made any progress on this issue? I'm running into the same problem and cannot figure out how to resolve this?

**Comment by mix0000** [comment] 2023-06-26 12:48
I have the same issue and here is the interesting things:

- This bug is not related with NextJS. I get it on SPA, wepback(5.74.0) 
- Reproduces only in Chrome, not even in Microsoft Edge..
- The problem is not related with network because webpack dont event tries to request the file..

**Comment by NathanielHill** [comment] 2023-06-26 18:53
I have the same issue, being experienced by users in production (they end up seeing a network error toast).

It is happening only on Chrome (113 & 114), but on Windows and macOS.

The JS bundle files are accessible.

**Comment by riccardolinares** [comment] 2023-06-28 16:46
I have the same issue. Happening on iPhone OS. No problem on desktop browsers.

**Comment by gsi-chao** [comment] 2023-06-29 21:28
I'm encountering the same issue while deploying my app to AWS Amplify Hosting.

**Comment by riccardolinares** [comment] 2023-06-30 15:32
> I have the same issue. Happening on iPhone OS. No problem on desktop browsers.

My problem was with a tailwind class. I was assigning a class after rendering the component. I deleted it and now it works :)

**Comment by YIZHUANG** [comment] 2023-07-06 00:24
Link to this tweet here:
https://twitter.com/yizhuang1996/status/1676745155657846785?t=RL4iF_wpGTmeoqdMUOkZyg&s=19

**Comment by carosaome** [comment] 2023-07-12 03:25
> 
The same with me. Did you solve this issue?

**Comment by carosaome** [comment] 2023-07-12 03:25
> I have the same issue. Happening on iPhone OS. No problem on desktop browsers.

**Comment by PrzemyslawPolrolniczak** [comment] 2023-07-12 08:09
Happens to me as well. Sentry shows that it only affects safari users, mainly iPhone OS, but there are also a few MacOS incidents

**Comment by baptisteArno** [comment] 2023-07-12 13:58
This issue is raised for a lot of Android users on inapp browsers like Facebook or Instagram...

I don't know what to do.

**Comment by BenBrewerBowman** [comment] 2023-07-12 14:16
> I have the same issue and here is the interesting things:
> 
> * This bug is not related with NextJS. I get it on SPA, wepback(5.74.0)
> * Reproduces only in Chrome, not even in Microsoft Edge..
> * The problem is not related with network because webpack dont event tries to request the file..

I think this might actually be a Next issue in this case. You can have chunk loading errors with any app that uses code splitting, but this one in particular is interesting to me bc of the way it behaves. When working w/ SPA apps on Webpack in the past, we solved this problem by updating the cache w/ the new chunks. The links were actually bad when clicking them (the chunk actually did not exist anymore). This one "feels" to me like Next bc the chunk actually loads whenever I follow the link. Our logs are blowing up w/ chunk loading errors on the user front, however, when I visit the link to the chunk that failed to load, it always loads for me. I think this is odd bc the chunk does in fact exist and the URL points to the chunk. It seems like there is either a timing problem where it doesn't exist for a short period of time, or it is having problems being loaded properly. Might not be a Next error, but it feels like it would be as the chunk does exist and I can always link to it correctly.

**Comment by SergiuGrisca** [comment] 2023-07-19 08:14
Sentry is still reporting this type of errors in our prod,
we are using next with nx , version of the next is `13.4.8`

any progress on this ?

**Comment by designcise** [comment] 2023-08-10 17:51
this happening for me with dynamic routes (e.g. `app/whatever/[slug]/page.js`) in next.js 13 app router; it always fails to load the chunk for the dynamic route on production. if i substitute `[slug]` with a static/named route, then it works. another thing i noticed is that, the 404 / `page-abc123.js:1 ChunkLoadError: Loading chunk xyz failed.` happens only when the link is loaded directly. if you navigate to the url via a link in the app, it works fine.

i have tried about 5 days looking for a solution, but it has been to no avail. i hope someone from vercel looks into it and fixes it. till then, i will have to scrape my hopes of building in next.

**Comment by Elio-Muculo** [comment] 2023-08-13 18:21
I'm facing the same issue, has anyone find a way to fix this? 

Locally the build runs perfectly but on production the chunk is not found even if it exists on the folder this is so weird and it just happen for dynamic route


/route/[slug]/page.tsx

**Comment by patte** [comment] 2023-08-16 14:42
We encountered the same problem in production.
Environment:
```
Operating System:
  Platform: linux
  Arch: x64
Binaries:
  Node: 20.5.1
  npm: 9.8.0
  Yarn: 1.22.19
Relevant packages:
  next: 13.4.16
  eslint-config-next: 13.4.16
  react: 18.2.0
  react-dom: 18.2.0
```

We saw that after a deploy the name `https://DOMAIN/_next/static/chunks/webpack-dcd23afe491cce30.js` did not change, even tough it's content changed. As the file has a long max-age (`31536000`) this resulted in the client's browser using the cached version, which tried to fetch chunks that didn't exist in the new build. Resulting in the error message: `Loading chunk 3572 failed`.
<details><summary>Screenshot diff</summary>

![Clipboard - August 16, 2023 11 53 AM](https://github.com/vercel/next.js/assets/3500621/a4e9c736-98eb-4c0e-80a9-d92eec23aa58)

</details>

As a workaround we added the `buildId` to the name of all chunks by modifying the webpack config like so:
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
  },
  transpilePackages: ['@parse/node-apn', 'web-push'],
  // ugly hack to make sure all chunks have a cache-busting hash
  // we had the issue in production of /_next/static/chunks/webpack-dcd23afe491cce30.js
  // not changing it's filename when the content changed.
  // https://github.com/vercel/next.js/issues/38507
  webpack: (config, { buildId }) => {
    // only apply it if dev: false, isServer: false, nextRuntime: undefined
    if (config.output.filename === 'static/chunks/[name]-[chunkhash].js') {
      config.output.filename = `static/chunks/[name]-[chunkhash]-${buildId}.js`
    }
    return config
  },
}

module.exports = nextConfig
```

**Comment by designcise** [comment] 2023-08-16 14:56
> We encountered the same problem in production. Environment:
> 
> ```
> Operating System:
>   Platform: linux
>   Arch: x64
> Binaries:
>   Node: 20.5.1
>   npm: 9.8.0
>   Yarn: 1.22.19
> Relevant packages:
>   next: 13.4.16
>   eslint-config-next: 13.4.16
>   react: 18.2.0
>   react-dom: 18.2.0
> ```
> 
> We saw that after a deploy the name `https://DOMAIN/_next/static/chunks/webpack-dcd23afe491cce30.js` did not change, even tough it's content changed. As the file has a long max-age (`31536000`) this resulted in the client's browser using the cached version, which tried to fetch chunks that didn't exist in the new build. Resulting in the error message: `Loading chunk 3572 failed`.
> 
> Screenshot diff
> As a workaround we added the `buildId` to the name of all chunks by modifying the webpack config like so:
> 
> ```js
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   experimental: {
>     appDir: true,
>   },
>   transpilePackages: ['@parse/node-apn', 'web-push'],
>   // ugly hack to make sure all chunks have a cache-busting hash
>   // we had the issue in production of /_next/static/chunks/webpack-dcd23afe491cce30.js
>   // not changing it's filename when the content changed.
>   // https://github.com/vercel/next.js/issues/38507
>   webpack: (config, { buildId }) => {
>     // only apply it if dev: false, isServer: false, nextRuntime: undefined
>     if (config.output.filename === 'static/chunks/[name]-[chunkhash].js') {
>       config.output.filename = `static/chunks/[name]-[chunkhash]-${buildId}.js`
>     }
>     return config
>   },
> }
> 
> module.exports = nextConfig
> ```

i tried this, however, the issue still persists for me unfortunately .. my issue is specifically with chunks created for dynamic route javascript files

**Comment by designcise** [comment] 2023-08-16 14:56
> We encountered the same problem in production. Environment:
> 
> ```
> Operating System:
>   Platform: linux
>   Arch: x64
> Binaries:
>   Node: 20.5.1
>   npm: 9.8.0
>   Yarn: 1.22.19
> Relevant packages:
>   next: 13.4.16
>   eslint-config-next: 13.4.16
>   react: 18.2.0
>   react-dom: 18.2.0
> ```
> 
> We saw that after a deploy the name `https://DOMAIN/_next/static/chunks/webpack-dcd23afe491cce30.js` did not change, even tough it's content changed. As the file has a long max-age (`31536000`) this resulted in the client's browser using the cached version, which tried to fetch chunks that didn't exist in the new build. Resulting in the error message: `Loading chunk 3572 failed`.
> 
> Screenshot diff
> As a workaround we added the `buildId` to the name of all chunks by modifying the webpack config like so:
> 
> ```js
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   experimental: {
>     appDir: true,
>   },
>   transpilePackages: ['@parse/node-apn', 'web-push'],
>   // ugly hack to make sure all chunks have a cache-busting hash
>   // we had the issue in production of /_next/static/chunks/webpack-dcd23afe491cce30.js
>   // not changing it's filename when the content changed.
>   // https://github.com/vercel/next.js/issues/38507
>   webpack: (config, { buildId }) => {
>     // only apply it if dev: false, isServer: false, nextRuntime: undefined
>     if (config.output.filename === 'static/chunks/[name]-[chunkhash].js') {
>       config.output.filename = `static/chunks/[name]-[chunkhash]-${buildId}.js`
>     }
>     return config
>   },
> }
> 
> module.exports = nextConfig
> ```

i tried this, however, the issue still persists for me unfortunately .. my issue is specifically with chunks created for dynamic route javascript files..

**Comment by zvs001** [comment] 2023-08-20 23:01
> **Problem**
> 
> this is happening for me as well with dynamic routes (e.g. `app/whatever/[slug]/page.js`) in next.js 13 app router; it always fails to load the chunk for the dynamic route on production.
> 
> **Environment Details**
> 
> ```
> Operating System:
>       Platform: linux
>       Arch: x64
>       Version: #1 SMP Tue Jan 25 12:49:12 MSK 2022
>     Binaries:
>       Node: 18.17.0
>       npm: 9.6.7
>       Yarn: 1.22.19
>       pnpm: N/A
>     Relevant Packages:
>       next: 13.4.14-canary.1
>       eslint-config-next: 13.4.14-canary.1
>       react: 18.2.0
>       react-dom: 18.2.0
>       typescript: 5.1.6
>     Next.js Config:
>       output: N/A
> ```
> 
> **Observations**
> 
> * if i substitute `[slug]` with a static/named route, then it works.
> * i'm only importing only one component in this route's `page.js`, if i remove the imported component, everything works. dynamically loading the component as suggested in one of the answers, does not help.
> * the 404 / "`page-abc123.js:1 ChunkLoadError: Loading chunk xyz failed.`" happens only when the link is accessed directly. if you navigate to the url via a link in the app, it works fine.
> * the missing chunk does exist in the `.next` folder, however, it returns 404 when accessed via `https://.../_next/static/chunks/app/web/tutorial/%5Bslug%5D/page-abc123.js`
> * i do my server deployments via github actions; to rule out issues with that, i even tried directly adding files to the server using SFTP, but the same issue persists
> 
> i even tried setting up the https://vercel.com/templates/next.js/app-directory demo on my server, and it's reproducible, however, the same issue does not seem to be on, for example, https://app-router.vercel.app/not-found/does-not-exist
> 
> **Conclusion**
> 
> i have tried about 5 days looking for a solution, but it has been to no avail. any help would be greatly appreciated!

I dive into same issue today.
Reproduced on next: 13.4.19.

Seems next server doesn't match uri-encoded `[slug]` with existing folder.
I have this issue only on linux server. When I am working under mac, I don't have this problem.

I tried to downgrade to next@13.3.4 and issue was fixed.

Seems we can confirm that we have issue with path resolving on static server.
At least we have temporary workaround

**Comment by marwinlewis** [comment] 2023-08-23 06:47
In my case I have dynamic routing pages > [category] > index.tsx and [id].tsx. The problem started after upgrading nextjs. I also tried the router app and the same problem. 404 in compiled js file in production environment. As [zvs001](https://github.com/zvs001) suggested, downgrading to 13.3.4 fixes this issue.

**Comment by pimmee** [comment] 2023-09-13 20:48
Also seeing a lot of these errors in sentry (and have been for a long time). It happens when I deploy a new version (NextJS / Vercel). 

At first I thought it was related to NextJS Router Cache caching chunks that is removed on new deployments, but the chunks are still accessible via URL as other people have mentioned, so I'm a bit perplexed...

I'm currently on next `13.4.12`, but we've had this issue for a long time.

Right now we're deploying new versions during the night and have implemented custom cache busting (i.e. page reload) functionality to mitigate the issue. 

It would be great if new deployments seamlessly purges any cache or whatever is causing this issue, so we can confidently deploy changes often without risk of users seeing an error screen.

<img width="290" alt="image" src="https://github.com/vercel/next.js/assets/33460567/94b1748d-0c50-42f6-b36c-d1a7718087d7">

**Comment by silent1mezzo** [comment] 2023-09-27 19:10
We're (Sentry) looking at filtering these errors out by default since they don't seem to be actionable. Would this be helpful to y'all?

**Comment by charanjit-singh** [comment] 2023-09-29 09:21
How about handling it in error boundary to force reload the window after clearing all the caches when there's `ChunkLoadError`?

> Also seeing a lot of these errors in sentry (and have been for a long time). It happens when I deploy a new version (NextJS / Vercel).
> 
> At first I thought it was related to NextJS Router Cache caching chunks that is removed on new deployments, but the chunks are still accessible via URL as other people have mentioned, so I'm a bit perplexed...
> 
> I'm currently on next `13.4.12`, but we've had this issue for a long time.
> 
> Right now we're deploying new versions during the night and have implemented custom cache busting (i.e. page reload) functionality to mitigate the issue.
> 
> It would be great if new deployments seamlessly purges any cache or whatever is causing this issue, so we can confidently deploy changes often without risk of users seeing an error screen.
> 
> <img alt="image" width="290" src="https://user-images.githubusercontent.com/33460567/267783006-94b1748d-0c50-42f6-b36c-d1a7718087d7.png">

**Comment by fdev** [comment] 2023-09-29 09:25
It's not necessarily to do with deploying. I have a NextJS application that was deployed on (and running since) April 28th and I still get Chunk Load Errors almost daily.

**Comment by onomated** [comment] 2023-10-04 00:43
> In my case I have dynamic routing pages > [category] > index.tsx and [id].tsx. The problem started after upgrading nextjs. I also tried the router app and the same problem. 404 in compiled js file in production environment. As [zvs001](https://github.com/zvs001) suggested, downgrading to 13.3.4 fixes this issue.

I had this issue with the latest Canary version.  I updated to [this package version](https://github.com/vercel/platforms/blob/main/package.json#L29) `"next": "13.5.5-canary.0"`, at the time of this post and it resolved the issue.  The platforms example app also has `[domain]` and `[slug]` [folders](https://github.com/vercel/platforms/tree/main/app/%5Bdomain%5D).  

Likely unrelated, but on initial deploy, my main page 404s and I occasionally have to `empty cache and hard reload` right after deploy to avoid the error.  Sharing in case the fix is a sequence of steps shared to get this to work.
<img width="285" alt="image" src="https://github.com/vercel/next.js/assets/1012979/b9a9a533-9adb-42ab-9937-f63390cd7324">

**Comment by HazAT** [comment] 2023-10-04 09:10
Heads up - the change to default ignore these error is live on sentry.io 
ref: https://github.com/vercel/next.js/issues/38507#issuecomment-1737937921

**Comment by designcise** [comment] 2023-10-06 22:59
upgrading to next v13.5.4 seems to fix the issue for me

**Comment by krthush** [comment] 2023-10-12 16:11
we now seem to be running into this issue as well, did try upgrading to next  v13.5.4 and hasn't fixed it
have installed sentry now see how bad really this problem is for our users but the inconsistency of it is not ideal ;(

**Comment by 70ki8suda** [comment] 2023-10-23 09:32
+1

**Comment by gidgudgod** [comment] 2023-10-25 17:30
I got this error as well in production. In my case this error happened when I add Next.js `headers()` to every server request (I do this in order to forward end user's headers to my API).
Next.js version that I used is v13.5.6. After downgrading to 13.5.4, error is gone.

**Comment by B-urb** [comment] 2023-10-27 23:25
I also have the error in v14.0.0

**Comment by federicocappellotto97** [comment] 2023-10-30 11:32
I have the same problem with v14.0.0
App dir, i have a folder [...slug] and when i click to a link that take to that folder i got
ChunkLoadError: Loading chunk app/[...slug]/page failed.
(error: http://localhost:3000/_next/static/chunks/app/%255B...slug%255D/page.js)

If i refresh the page works

**Comment by jianliao** [comment] 2023-10-31 06:31
I pretty sure the this error on 13/14 with App dir was caused by this PR - https://github.com/vercel/next.js/pull/54752

**Comment by DanielWTE** [comment] 2023-10-31 20:40
After removing all instances of 'import Script from 'next/script'', it worked perfectly again for me.

**Comment by jianliao** [comment] 2023-10-31 21:26
Check #57829 out. Remove `beforeInteractive` could work around this issue.

**Comment by lunoob** [comment] 2023-11-01 02:38
> Check #57829 out. Remove `beforeInteractive` could work around this issue.

thank you, it work for me

**Comment by donttouchmylancable** [comment] 2023-11-27 18:43
I have the same problem, after deploying a demo branch for a customer.
The Main Branch that worked for a month also doesnt work any more.
I even deleted the cache of both project, but it results in the same issue

**Comment by huozhi** [comment] 2023-11-28 12:09
Is anyone still having the chunk loading issue after upgrading to 14.0.2 where we had a fix for it or above versions? If you still have the problem with new version, please open a new issue with reproduction that would be helpful for investigating the specific issues you're encountering. Thanks!

**Closed by huozhi** 2023-11-28 12:09 UTC
Labels: template: bug

**Comment by igorvargasp** [comment] 2023-11-28 22:46
I am having this problem with next 14.0.2

**Comment by huozhi** [comment] 2023-11-30 09:00
@igorvargasp @iamtun could you file a different issue with reproduction? It's not clear what the exact issue is and what's the root causes of them
