### ISSUE TITLE
[NEXT-378] Next 13: Navigation with Link does not scroll up the page

### ISSUE THREAD

**Issue by alexvcasillas** [vercel/next.js#42492] opened 2022-11-04 15:45 UTC
### Verify canary release

* [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

**Operating System**:
Platform: linux
Arch: x64
Version: #1 SMP Mon Sep 19 19:14:52 UTC 2022
**Binaries**:
Node: 16.15.0
npm: 8.5.5
Yarn: 3.2.4
pnpm: N/A
**Relevant packages**:
next: 13.0.2
eslint-config-next: 13.0.0
react: 18.2.0
react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 107.0.5304.87

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

When navigating between pages using `Link`, the page does not scroll up by default wich is supposed to be the default behaviour of `next/link`

### Expected Behavior

The page scrolls up when switching pages unless I manually disable this feature of `next/link`

### Link to reproduction

[https://beta.otpfy.com/](https://beta.otpfy.com/)

### To Reproduce

* Access [https://beta.otpfy.com/](https://beta.otpfy.com/)
* Scroll down until you see the "Get started for free" button
* Click the given button
* Check that when navigating to the `auth` page the scroll is preserved and not scrolled to the top

\:

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-378](https://linear.app/vercel/issue/NEXT-378/next-13-navigation-with-link-does-not-scroll-up-the-page)</sub>

**Comment by semy** [comment] 2022-11-19 18:43
Same for me... How to fix that?

**Comment by Fredkiss3** [comment] 2022-11-19 23:44
I think it scrolls up to the nearest `<div data-nextjs-scroll-focus-boundary />`, this div is automatically created when you wrap your page in a layout. It is supposed to assure scroll restoration within layouts. 

you can see in the video below : 

https://user-images.githubusercontent.com/38298743/202875831-177954a5-cd9c-4afc-b758-684adc544b46.mov

**Comment by semy** [comment] 2022-11-20 00:16
@ Fredkiss3 Thanks for your answer :) Yes you are right, but what if I don't want to? Normally I want it to just scroll all the way to the top when clicking on another page. That should be clarified.

**Comment by Fredkiss3** [comment] 2022-11-20 00:49
I don't know, they added this feature because it seemed really nice (that's what I know, but maybe I'm wrong), but it seems like it requires the creation of a new react API to do so. 
What I would have liked from them is that they don't include the scroll restore functionality before it is implemented by react.

(sorry for my broken english)

**Comment by rshaul** [comment] 2022-11-21 17:41
I thought this scrolling behavior was a bug at first and rolled back to the pages directory because of it.

Scrolling to top after clicking a link seems like it should be the default behavior to match "web" expectations and maybe you should have to opt into this scroll to nearest layout container div behavior if that's what you want?

**Comment by ElektrikSpark** [comment] 2022-12-09 14:41
I have some routes using the Tailwind UI Sidebar Layout where `html` and `body` need `h-full`. So this wasn't working. [more details](https://stackoverflow.com/questions/1174863/javascript-scrollto-method-does-nothing)

So I had to use this on those routes:
`'use client';

import { useEffect } from 'react';

export default function ScrollUpBody() {
  useEffect(() => document.body?.scrollTo(0, 0), []);

  return null;
}
`

Not fun.

**Comment by Fredkiss3** [comment] 2022-12-09 15:47
Hey, are you still having the same problem after the last canary release ? You can install it with `next@canary`.

I've seen that they removed the unnecessary divs appearing inside children of layouts in #43717

**Comment by ElektrikSpark** [comment] 2022-12-09 16:24
I would love to let you know if I could! [issue](https://github.com/vercel/next.js/issues/43854#issuecomment-1344306336)

**Comment by rosszurowski** [comment] 2022-12-11 12:42
For others who come across this issue, I ran into the same thing, but was able to fix it by removing an unnecessary layout. My directory structure looked like:

```
app/layout.tsx
app/page.tsx
app/blog/[...slug]/layout.tsx
app/blog/[...slug]/page.tsx
```

In my case, navigating to one of the `blog/2020/post-name` pages had the page start half-way down, without scrolling back up to the top. Looking at the DOM structure, there were two layers of `<div data-nextjs-scroll-focus-boundary />` elements.

I found that removing my `app/blog/[...slug]/layout.tsx` and wrapping my one-off layout into `app/blog/[...slug]/page.tsx` instead fixed the issue, since now there was only one layer of layouts rather than two. I moved common layout code into a separate component to share between the two pages where it's needed:

```
app/layout.tsx
app/page.tsx
app/blog/[...slug]/page.tsx
components/layout.tsx
```

For a content-based website like the one I was working on, it was a good reminder that nested layouts are probably more meant for apps with truly nested frames rather than a single view. I guess hearing the word "layout" made me think it'd replace my `Layout` components 1:1.

**Comment by valse** [comment] 2022-12-13 22:26
> Hey, are you still having the same problem after the latest canary release ? You can install it with `next@canary`.
> 
> I've seen that they removed the unnecessary divs appearing inside children of layouts in this PR : #43717

Hi, I'm using the latest `13.0.7-canary.6` version but I have the same issue

**Comment by ElektrikSpark** [comment] 2022-12-19 22:44
I'm using `13.0.7` and the issue is better, but it still does not scroll all the way up if I want it to. It will scroll right below the header.

**Comment by davidcm62** [comment] 2022-12-21 08:22
Same here. We're trying to add a simple layout with a shared header and the main content. On navigation, the page doesn't scroll to the top and the header is always hidden.

**Comment by AndrewIngram** [comment] 2022-12-21 10:24
> 



> For now can be fixed by adding a `<ScrollUp />` component to your page:
> 
> ```tsx
> 'use client'
> 
> import { useEffect } from 'react'
> 
> export default function ScrollUp() {
>   useEffect(() => window.document.scrollingElement?.scrollTo(0, 0), [])
> 
>   return null
> }
> ```

Won't this also be triggered when using the back button though?

**Comment by metawise** [comment] 2022-12-24 05:24
Confirms the scroll restoration not working after upgrade to NextJS 13.1 just today.

**Comment by mikeyakymenko** [comment] 2022-12-28 01:45
Still doesn't work, nextJS `13.1.1`.

**Comment by stevenpetryk** [comment] 2023-01-02 19:13
I'm also on 13.1.1, and it doesn't seem like Next.js is adding any elements with `data-nextjs-scroll-focus-boundary`.

I actually have a relatively simple website that reproduces this behavior if it helps.

- Repo: https://github.com/stevenpetryk/mafs (the `/docs` folder)
- [Live site example page](https://mafs.dev/guides/display/viewbox)

Running `document.querySelectorAll('[data-nextjs-scroll-focus-boundary'])` on a few pages returns empty NodeLists.

**Comment by Waqas-Abbasi** [comment] 2023-01-02 19:15
+1

**Comment by semy** [comment] 2023-01-02 19:20
The next problem is when you press the browser's back button: Normally the previous HTML page should be displayed in the same scroll position as before. But the page hangs and blocks for a moment, and then the document jumps back to the top of the page. This is very inconvenient when I'm scrolling through a list of, for example, blog posts and then go to the details of a post and then want to go back to look at the next blog post. I find this behavior very annoying.

**Comment by semy** [comment] 2023-01-02 19:24
+1

**Comment by valse** [comment] 2023-01-02 19:28
> I'm also on 13.1.1, and it doesn't seem like Next.js is adding any elements with `data-nextjs-scroll-focus-boundary`.
> 
> I actually have a relatively simple website that reproduces this behavior if it helps.
> 
> * Repo: https://github.com/stevenpetryk/mafs (the `/docs` folder)
> * [Live site example page](https://mafs.dev/guides/display/viewbox)
> 
> Running `document.querySelectorAll('[data-nextjs-scroll-focus-boundary'])` on a few pages returns empty NodeLists. I also tried things like removing `display: flex` from `body` to no avail.

Hi the div `data-nextjs-scroll-focus-boundary` is not longer available... This issue is very annoying and I can't understand why is not on the top priority list.
Maybe it happens only for certain configuration or styles?!

**Comment by qpavy** [comment] 2023-01-04 16:35
Still doesn't work on NextJs `13.1.2-canary.0` It seems a little better on NextJs `13.0.5`

**Comment by jessicalc** [comment] 2023-01-04 18:46
I'm on NextJS `12.2.5` and was also observing this problem on pages with shared layouts, where, when I clicked on a Link on Page A to get to Page B, Page B would load scrolled to the position that Page A was at. (i.e. if I was 50% of the way scrolled down on Page A, Page B would load scrolled 50% of the way down!) 

Things I tried that didn't work:
- Not using layouts at all (no dice) 

Things that I did to make it work:
- I removed `scroll-behavior: smooth` from my `html` element (and stuck it on the `body`).  h/t https://stackoverflow.com/a/63379899/4172535 
- When using the `next/link` `Link`, I passed `scroll={true}` 

That combination seems to have fixed things for my situation.

**Comment by qpavy** [comment] 2023-01-04 19:16
With `scroll={true}` on `next/link` `Link` it seems to work better. But sometimes, scrolling stop under my header I don't know why.

**Comment by qpavy** [comment] 2023-01-04 19:46
yeah I don't know why it's working better

**Comment by jessicalc** [comment] 2023-01-04 21:26
> What's the intuition behind `scroll={true}` helping, given that [the docs indicate](https://nextjs.org/docs/api-reference/next/link) that's the default?

That's a good question, @steve-marmalade. I'm going to update my answer to strike-through that bit, because it doesn't do anything.

**Comment by ElektrikSpark** [comment] 2023-01-05 15:07
I just wanted to point out that I do not see a scroll property on the [beta docs](https://beta.nextjs.org/docs/api-reference/components/link). It is not in props or legacy props. 🤷

**Comment by pogran** [comment] 2023-01-09 06:29
i think problem isn't solved yet. Right?

**Comment by devRabbani** [comment] 2023-01-13 20:29
Same problem

**Comment by devRabbani** [comment] 2023-01-14 14:47
I found the error....Actually it is happening because I set height:100% and overflow: auto on html element.

**Comment by reiv** [comment] 2023-01-14 16:49
For what it's worth, this is reproducible on the [app playground](https://app-dir.vercel.app/), which has neither of those.

**Comment by saarnav890** [comment] 2023-01-15 07:18
> I found the error....Actually it is happening because I set height:100% and overflow: auto on html element.

I don't have either in my project, but am still facing the issue :(

**Comment by selenecodes** [comment] 2023-01-15 21:55
Still facing this issue as well on `next@13.1.2`

**Comment by timneutkens** [comment] 2023-01-16 13:41
> why is not on the top priority list.

Scroll behavior and back navigation are on the list of things to investigate further. E.g. there's this PR: #43845. As of right now it's expected that navigation scrolls to the nearest common layout that changed, this ensures that when you're navigating between tabs it keeps the relevant changed content in view and doesn't start from the top of the page. #43845 changes that behavior to scroll to the top of the page if the element stays in the viewport while at the top of the page. This behavior is relevant because in the new router you can soon create e.g. a tab UI similar to what you can see on https://app-dir.vercel.app/ssg where you wouldn't want it to scroll to top on interactions.

Please be patient while we work through the backlog of all `app` related issues, it's in beta for a reason and to reiterate it's not meant to be used in production yet.

Please don't post comments like "same issue", "It's still an issue in version x.x.x", "is this resolved yet" they're not constructive.

**Comment by nx-dariomunoz** [comment] 2023-01-16 14:31
While it's getting under further investigation, for the ones who are still facing this unexpected behaviour (although there're some reasons behind this as Tim stated), this workaround is functional and working: 

> For now can be fixed by adding a `<ScrollUp />` component to your page:
> 
> ```tsx
> 'use client'
> 
> import { useEffect } from 'react'
> 
> export default function ScrollUp() {
>   useEffect(() => window.document.scrollingElement?.scrollTo(0, 0), [])
> 
>   return null
> }
> ```

Just wanted to remark that you can import this _"Scrollup"_ component into your desired _"page.jsx"_ in the route you expect to navigate and be auto-scrolled to the top of the page instead of remaining at the actual scroll spot.

Thanks Tim for the insights about this topic.

**Comment by AndrewIngram** [comment] 2023-01-16 14:49
The problem with that workaround is that it'll also be triggered if you use the back button, which is generally _not_ the desired behaviour -- the "native" behaviour is to to restore the previous scroll position.

It's a viable interim solution if you don't mind that though.

**Comment by sookmax** [comment] 2023-01-17 05:25
> The problem with that workaround is that it'll also be triggered if you use the back button, which is generally _not_ the desired behaviour -- the "native" behaviour is to to restore the previous scroll position.

This is a good point. I also wanted to preserve the default behavior of back/forward navigations from the browser UI (or mouse forward/back, swiping gesture at the screen edge, etc) while bringing the scroll to the top for the navigations triggered by my `<Link />`.

So I came up with something that works for me, but not really sure if the solution is a right way to approach this or if it's against best practices ¯\_(ツ)_/¯.

Anyways, here's the basic idea (in case it's helpful to someone).

* First of all, I need to differentiate the page navigation caused by my `<Link />`s and that caused by all the other methods. I mark this in `onClick` of my `<Link />`s.
* In some appropriate client component (layout component in my case), subscribe to the change in the current path using `usePathname` and `useEffect`. 
* in `useEffect` above, check if the path change was triggered by the `<Link />`.
* if it is, do `window.scrollTo({ top: 0 })` otherwise do nothing.

Here's some code.

```tsx
// ./components/MyLayout.tsx
"use client";
import { usePathname } from "next/navigation";
import { useEffect } from "react";

let top0Requested = false;
export function requestTopO() {
  top0Requested = true;
}

export default function MyLayout(props) {
  const currentPath = usePathname();

  useEffect(() => {
    let requestId: number | undefined;
    if (top0Requested) {
      const rAFCallback = () => {
        if (window.scrollY !== 0) {
          window.scrollTo({ top: 0 });
          requestId = requestAnimationFrame(rAFCallback);
        } else {
          top0Requested = false;
        }
      };
      requestId = requestAnimationFrame(rAFCallback);
    }

    return () => {
      requestId && cancelAnimationFrame(requestId);
    };
  }, [currentPath]);

  return <YourUIComponent {...props} />
}
```

```tsx
// ./components/MyNav.tsx
import { requestTopO } from "./MyLayout";

export default function MyNav() {
  return (
    <ul>
      <li>
        <Link href="/about" onClick={requestTopO}>
          About
        </Link>
        <Link href="/work" onClick={requestTopO}>
          Work
        </Link>
        <Link href="/contact" onClick={requestTopO}>
          Contact
        </Link>
      </li>
    </ul>
  );
}
```

**Comment by lnikell** [comment] 2023-01-21 11:20
I experience similar behavior, but there is something worth mentioning the behavior is different from a page visit through other pages, vs a direct visit with further navigation within the page. In both scenarios behavior is unexpected.

Visit through the homepage and then navigating between links
https://user-images.githubusercontent.com/2697570/213864595-3daf1685-7883-473a-a813-de4661e07f4f.mp4

Page refresh and navigation between links
https://user-images.githubusercontent.com/2697570/213864614-70788b56-0bd9-450d-bb96-401be0b78091.mp4

**Comment by valse** [comment] 2023-01-23 01:33
> it's in beta for a reason and to reiterate it's not meant to be used in production yet

@timneutkens you're right and I'm sorry: I thought only to solve one of my needs and not for the benefit of the product: thanks for your useful explanation and I'm sure we'll find the best solution to cover all the desired use cases 💪🏻

Sincerely, a Next.js ♥️ lover

**Comment by timneutkens** [comment] 2023-01-27 09:39
We've landed #43845 which changes the heuristic to scroll to top when the element is in the viewport when scroll position is at the top. If it's not in the viewport when at the top of the page it'll scroll to the changed element.

**Comment by simonecervini** [comment] 2023-01-30 00:05
I am trying with version 13.1.6, but personally I am still experiencing problems using a basic layout with fixed navbar to navigate between pages that share the same layout. I don't understand if with https://github.com/vercel/next.js/pull/43845 merged this case should already be covered or it is still a work in progress.

**Comment by JanKaifer** [comment] 2023-01-30 15:46
This shouldn't happen. I tried to reproduce it, but I wasn't able to.
Could you try reproducing the issue here https://github.com/JanKaifer/next-repro-42492
It has a navbar with `position: fixed`, but It doesn't change anything.

There could be an issue if the navbar is taller than the viewport, could that be your case?

**Comment by simonecervini** [comment] 2023-01-30 17:59
> This shouldn't happen. I tried to reproduce it, but I wasn't able to. Could you try reproducing the issue here https://github.com/JanKaifer/next-repro-42492 It has a navbar with `position: fixed`, but it still works as expected.
> 
> There could be an issue if the navbar is taller than the viewport, could that be your case? (In that case, it should scroll to the top of the page, just below the navbar).

Thank you for your reply! After an hour of trying, I think the problem is related to CSS Modules. You can try this diff, the content of `styles.module.css` is not relevant.

```diff
diff --git a/app/[num]/page.tsx b/app/[num]/page.tsx
index 83206f4..a939440 100644
--- a/app/[num]/page.tsx
+++ b/app/[num]/page.tsx
@@ -1,17 +1,13 @@
 import Link from "next/link";
+import styles from './styles.module.css'

 export default function Page({ params: { num } }) {
   return (
     <div>
       {new Array(100).fill(0).map((_, i) => (
         <div
+          className={styles.square}
           key={i}
-          style={{
-            height: 100,
-            width: 100,
-            background: "pink",
-            margin: 10,
-          }}
         >
           <Link href={`/${Number(num) - 1}`}>lower</Link>
           <div>{num}</div>
```

**Comment by JanKaifer** [comment] 2023-01-31 10:29
Thank you, I added that to the repro, and I'm able to reproduce this now.
Will look into it.

**Comment by JanKaifer** [comment] 2023-01-31 15:24
I have added a test with a repro here: 

`JanKaifer/jankaifer/next-378-next-13-navigation-with-link-does-not` 

It's a bit tricky because the playwright `click()` won't reproduce this. We need to do `document.getElementById("...").click()`

**Comment by simonhrogers** [comment] 2023-02-06 15:52
+1 

This affects the back button with both the `pages` and `app` directories for me and breaks a fundamental part of the browsing experience.

**Comment by chrber04** [comment] 2023-02-08 13:37
For me, the scroll does work but it doesn't scroll all the way up. Seems like it's scrolling to the top, minus the height of the sticky navbar. When I remove the header, it scrolls just as expected. Anyone know a solution to this?

**Comment by gjuoun** [comment] 2023-02-08 21:01
I have the same issue during the development.

This is clear a bug, please keep it open

**Comment by Untaek** [comment] 2023-02-09 04:47
in my case, importing css in client component cause bug.

**Comment by JanKaifer** [comment] 2023-02-09 10:40
> [JanKaifer/jankaifer/next-378-next-13-navigation-with-link-does-not](https://github.com/JanKaifer/jankaifer/next-378-next-13-navigation-with-link-does-not)

This is the reproduction that we have tried and that works now.
Could you open a new issue with new reproduction (you can just modify mine) to show what's wrong?

There are a lot of issues mentioned in this thread and it would be easier to track them if all of them were in separate issues. Thanks.

**Comment by simonecervini** [comment] 2023-02-09 10:59
> > This shouldn't happen. I tried to reproduce it, but I wasn't able to.
> > Could you try reproducing the issue here [JanKaifer/next-repro-42492](https://github.com/JanKaifer/next-repro-42492)
> > It has a navbar with position: fixed, but it still works as expected.
> 
> This is the reproduction that we have tried and that works now. Could you open a new issue with new reproduction (you can just modify mine) to show what's wrong?
> 
> There are a lot of things mentioned in this thread and it would be easier to track them if all of them were in separate issues. Thanks.

Thank you for your work. I tried the new release just now and it doesn't seem to work the same way every time. I also encountered the same problem in your repro (I added a "You are at the top of the page" message in the root layout for easy visualization):


https://user-images.githubusercontent.com/69400730/217791601-446627da-5eb6-49b8-8ebf-e5bc3e9f838a.mov

![Screenshot 2023-02-09 at 11 49 15](https://user-images.githubusercontent.com/69400730/217791857-730f0975-2b5e-47ef-940a-878a8b8688d2.png)

**Comment by JanKaifer** [comment] 2023-02-09 11:44
Thanks for checking the reproduction.
I can reproduce this locally. It's confusing it works correctly in the CI.
Because we have added this exact reproduction into our test suite.

I'll look into this.

**Comment by njarraud** [comment] 2023-02-09 20:17
If I am not mistaken, scrolling still doesn't work with page params. Navigating from /mypage?page=1 to  /mypage?page=2 using the <Link> component doesn't trigger any sort of scrolling and the page remains at the same location even if the content has changed.

**Comment by ala-garbaa-pro** [comment] 2023-02-10 19:54
I solved the issue by call the 'scrollToTop' on load in 'div':

Of course I add "use client"


```typescript
const isBrowser = () => typeof window !== "undefined"; //The approach recommended by Next.js
function scrollToTop() {
  if (!isBrowser()) return;
  setTimeout(() => {
    window.document.body.scrollIntoView({ behavior: "smooth" });
  }, 500);
}
```


```jsx
const LayoutComponent: React.FC<LayoutComponentProps> = ({ children }) => {

  return (
    <div className={styles._container} onLoad={()=>scrollToTop()}>  <-------------------------
      <Header />
      <div className={styles._page}>{children}</div>

      <Footer />
    </div>
  );
};

export default LayoutComponent;
```

**Closed** 2023-02-10 19:55 UTC
Labels: area: app, linear

**Comment by LotharVM** [comment] 2023-02-16 16:44
@JanKaifer and/or @timneutkens, Maybe not completely related to this issue, but will there be a way to opt-out from the auto-scroll feature? Let's say your page lives inside a modal (with position: fixed) and is using the same layout as the current page, you'd want to maintain the current scroll position. Now, the page scrolls up to the top of the layout.

**Comment by JanKaifer** [comment] 2023-02-16 17:32
@LotharVM Check https://nextjs.org/docs/api-reference/next/link#disable-scrolling-to-the-top-of-the-page

**Comment by timneutkens** [comment] 2023-02-16 19:25
The modal-type UI will be covered by parallel routes and interception which will allow you to create a page / layout that layers on top of the current view with correct scroll behavior.

**Comment by xixixao** [comment] 2023-02-24 23:22
@timneutkens We also ran into this issue, where the viewport is scrolled **down**, to a place where the new page differs from the old - but this is super confusing on mobile, and I haven't found a way to disable this behavior. Would be great if we could decide when auto-scrolling should happen and when it shouldn't (ala the `scroll` prop).

**Comment by filipkowal** [comment] 2023-02-28 09:14
I am still experiencing the scroll position being preserved on the `13.2.2 canary`.
It appears in an `/app` directory, in a server component.

**Comment by Huvinesh-Rajendran-12** [comment] 2023-03-11 12:19
Hi, I am currently seeing this issue in the latest canary release too `13.2.5`

**Comment by charlielow** [comment] 2023-03-14 13:32
Experiencing this on 13.1.2, if I add `scroll={true}` to the <Link /> it fixes the problem but this should be the default behavior according to the docs. 

I did notice the default [experimental scrollRestoration value](https://github.com/vercel/next.js/blob/v13.1.2/packages/next/src/server/config-shared.ts#L592) is `false` but changing this doesn't seem to do anything, links from a scrolled page result in a scrolled destination page.

**Comment by beamercola** [comment] 2023-03-18 00:04
still seeing this in 13.2.4

**Comment by victornevarezcbqa** [comment] 2023-03-21 15:33
> Experiencing this on 13.2.4, links from a scrolled page result in a scrolled destination page. if I add `scroll={true}` to the `<Link />` the problem goes away but this should be the default behavior according to the [docs](https://nextjs.org/docs/migrating/from-react-router#scroll-restoration). Also If I use `router.push(url)` the problem goes away.
> 
> I did notice the default [experimental scrollRestoration value](https://github.com/vercel/next.js/blob/v13.1.2/packages/next/src/server/config-shared.ts#L592) is `false` but changing this doesn't seem to do anything either.

For me it doesn't even work adding scroll={true}

**Comment by jankaifer** [comment] 2023-03-23 08:51
@charlielow, @beamercola and @victornevarezcbqa
Could you please open a new issue with minimal reproduction?

**Comment by this-Cunningham** [comment] 2023-03-24 03:38
This happens to me and makes my application pretty unusable in certain screen widths -- Anytime I have a next layout.tsx and I navigate to a page using the layout... If the rendered `{ children }` part of the page are BELOW THE FOLD/ out of the initial viewport the app scrolls down until the children HTML container is scrolled to the very top of the viewport (if there's enough content to do this) ... however, if there is even the smallest sliver of the layout's `{children}` HTML showing above the viewport/above the fold when navigating.... the application does not scroll down and maintains the correct scroll of zero.  This happens to me on all browsers

**Comment by this-Cunningham** [comment] 2023-03-24 03:58
here is repro I made -- https://github.com/this-Cunningham/Next-link-scroll-bug-repro

**Comment by jankaifer** [comment] 2023-03-24 08:48
@this-Cunningham This is expected behavior.

We do this to show the changed content on navigation because it's bad UX if you click a link and nothing changes.

**Comment by Arctomachine** [comment] 2023-03-31 17:54
Encountered this issue in 13.2.3. Not sure what exactly breaks scrolling. Somewhere it works, somewhere else not. In both cases pages from and pages to have identical respective composition and functionality, so it makes narrowing it down hard if possible.

In my project I implemented solution suggested by @ala-garbaa-pro, but modified it to make it separate component with useEffect hook and only include where scroll is broken

**Comment by surjithctly** [comment] 2023-04-01 10:39
I'm using router for next/prev pagination. But the scroll to top is not working, so that when clicking next from the bottom of the page, it stays there. The older version had an option to see `scroll: true`, but I don't know how to set this in /app dir.

```js
  const handleNextPage = () => {
    router.push(`/archive?page=${pageIndex + 1}`); // <-- keeps same position. Not scrolling up. 
  };
```

**Comment by rijk** [comment] 2023-04-01 10:57
To all: please post a Sandbox with reproduction of your issue, without it these "I'm having this issue in my app as well" comment are useless, just give a thumbs up to the original post!

**Comment by this-Cunningham** [comment] 2023-04-03 20:55
> @this-Cunningham This is expected behavior.
> 
> We do this to show the changed content on navigation because it's bad UX if you click a link and nothing changes.

this scrolling should be opt-in/out because you are making assumptions about the design of the layout with the current implementation
