### ISSUE TITLE
Error stack not exposed when axios error occurs inside `getInitialProps` function

### ISSUE THREAD

**Issue by stegano** [vercel/next.js#10624] opened 2020-02-21 07:14 UTC
# Bug report
Error stack not exposed when axios error occurs inside `getInitialProps` function

## Describe the bug
In the getInitialProps function, the error page is not displayed properly in client side rendering when an error occurs due to `axios`.

**Page code**
```javascript
// pages/example.js
...
ExamplePage.getInitialProps = () => {
  // The code below throws a CORS error on the client side.
  await axios.get('https://google.com');
  ...
  return {}
}
...
```

**Run script**
```
// Run nextjs in development mode.
$ next dev
```
## Expected behavior
If an error occurs in `getInitialProps` function when entering a page through `next/route(route.push)` on the client side, the error information should be exposed on the page, but if an` axios` error occurs, the error page is not exposed(As a result of testing, other errors except `axios` error are normally showing error information on the page.).

## System information
- Browser Chrome
- Version of Next.js: 9.2.1

**Comment by rafaelalmeidatk** [comment] 2020-02-22 15:45
This is a known problem with axios because it rewrites the stack trace. I wrote about a workaround here: https://github.com/rafaelalmeidatk/TIL/issues/4

**Comment by stegano** [comment] 2020-02-23 04:10
@rafaelalmeidatk 
This issue seems to be an issue only client-side rendering in development mode. Is it related to the rafaelalmeidatk/TIL#4 issue?

**Comment by luchux** [comment] 2020-03-19 06:25
You can use axios().then().catch() or wrap in try-catch

**Comment by Shivendra30** [comment] 2020-03-30 01:39
I made a sample app with `create-next-app` and stuck the following code in the index page

```
Home.getInitialProps = async () => {
  const res = await axios.get('https://google.com');
  return { res: res.statusText };
};
```

There was no error on the client or on the server. You didn't mark your function as `async` and also returned an empty object in `getInitialProps` which throws a warning on the sever

**Comment by ijjk** [comment] 2020-09-10 20:17
I'm going to close this since it doesn't appear to be an issue with Next.js and the replies above appear to resolve the problem.

**Closed by ijjk** 2020-09-10 20:17 UTC
Labels: good first issue

**Comment by balazsorban44** [comment] 2022-01-29 13:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
