### ISSUE TITLE
[i18n] app.render in custom server doesn't identify current locale

### ISSUE THREAD

**Issue by jacknevitt** [vercel/next.js#23862] opened 2021-04-09 17:49 UTC
### What version of Next.js are you using?

10.0.9

### What version of Node.js are you using?

14.15.5

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

n/a

### Describe the Bug

When using a custom server, pages served with `app.render` do not identify the locale in the url. Pages served from `handle` (`app.getRequestHandler()`) are able to identify the locale correctly.

### Expected Behavior

When visiting `localhost:3000/fr/product` to visit `pages/product` in a custom server that serves the page via `app.render(req, res, '/product', query)`, the `router` object supplied by `useRouter` in `pages/product.js` should have a `locale` property with the value `'fr'`

### To Reproduce

https://github.com/jacknevitt/emporio-next/tree/add-i18n

run `yarn dev`
open `localhost:3000`
> locale will be the default, 'en'
open `localhost:3000/fr/chaise`
> locale will be undefined (page served from app.render)
open `localhost:3000/es/chaise`
> locale is 'es' (page is served from handle)

**Comment by DonovanCharpin** [comment] 2021-04-10 14:10
I have the same issue with the version 10.1.4-canary.3. The locale is always undefined in `getServerSideProps` or `getStaticProps`

**Comment by chuck-durst** [comment] 2021-04-15 22:53
I had the same issue. I found a temporary patch which consists in manually detecting the locale (for example from the url or a cookie) and passing it to the render method this way:

`app.render(req, res, page, { __nextLocale: 'en' });`

On my side, I duplicated all my routes this way:

**/home -> /:locale/home**

Then you just have to do something like this : 

`app.render(req, res, page, { __nextLocale: req.params.locale });`

You may have to check first that the locale that has been given exists and return a 404 error if it does not. 


I hope this helps!

**Comment by ijjk** [comment] 2021-04-17 15:36
Closing as a duplicate of https://github.com/vercel/next.js/issues/20761

**Closed by ijjk** 2021-04-17 15:36 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
