### ISSUE TITLE
Not found in dymaric route does not render

### ISSUE THREAD

**Issue by hrasoa** [vercel/next.js#55555] opened 2023-09-18 22:00 UTC
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/determined-faraday-gflwsg

### To Reproduce

Browse https://gflwsg-3000.csb.app/en-us/aaaa

### Current vs. Expected behavior

- Current: renders the default not found.
- Expected:  unless I misunderstood, I expected to see `/app/[locale]/not-found.tsx`,

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
all
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

**Comment by joulev** [comment] 2023-09-19 06:13
This is not a bug. Use the root `app/not-found.tsx` for global 404 handling; other `not-found.tsx` files are only triggered by an explicit `notFound`.

To have different `not-found` for different locales, use `app/[lang]/[...notFound]/page.tsx`.

**Comment by balazsorban44** [comment] 2023-09-19 11:56
Closing, as per the docs, this is expected behavior as also pointed out above:

> Good to know: In addition to catching expected notFound() errors, the root app/not-found.js file also handles any unmatched URLs for your whole application. This means users that visit a URL that is not handled by your app will be shown the UI exported by the app/not-found.js file.

https://nextjs.org/docs/app/api-reference/file-conventions/not-found

**Closed by balazsorban44** 2023-09-19 11:56 UTC
Labels: template: bug, area: Routing

**Comment by everythinginjs** [comment] 2023-09-20 09:18
@balazsorban44, app/not-found.js file works well in development but in the build process i get the following error

build process error:
<img width="849" alt="Screenshot 2023-09-20 at 12 40 28 pm" src="https://github.com/vercel/next.js/assets/34276557/4574a11a-7b17-4b4f-8440-c22f106f9305">

my folder structure:
<img width="733" alt="Screenshot 2023-09-20 at 12 38 43 pm" src="https://github.com/vercel/next.js/assets/34276557/bc988066-8f1a-48d2-a100-fda17889efb4">

env:
"next": "13.5.1-canary.1"


@joulev I got confused some discussions say [...not_found] other say [...not-found] you say [...notFound] what the heck is this finally? and I have to point that [...notFound] (or what ever it is called) does not work with optional catch all routes like [[...slug]] and it errors out you can not use both together.

**Comment by joulev** [comment] 2023-09-20 09:29
> @joulev I got confused some discussions say [...not_found] other say [...not-found] you say [...notFound] what the heck is this finally?

It's just an ordinary catch-all route that catches all routes not matched by other routes. You can name it `[...notFound]`, `[...not-found]`, or even `[...tomandjerry]`, it will still work.

> and I have to point that [...notFound] (or what ever it is called) does not work with optional catch all routes like [[...slug]] and it errors out you can not use both together.

Of course, because two catch-alls cannot go together. If you already have a catch-all, use `notFound` with the local `not-found.tsx` file.

**Comment by everythinginjs** [comment] 2023-09-20 10:16
@balazsorban44 , I relocate not-found.tsx to (pages) group routes not the error is gone.
