### ISSUE TITLE
Full Reload warning may not be seen

### ISSUE THREAD

**Issue by Izhaki** [vercel/next.js#13070] opened 2020-05-19 00:08 UTC
# Bug report

I'm filing it as a separate issue to #13024 although they are somewhat related.

## Describe the bug

The warning about Full Reload can easily be missed because as soon as it is shown... the page reloads. Without specific browser settings, many users might miss it.

For me, I saw there was a warning, but couldn't read it until I enabled _Preserve Log_ in Chrome.

## To Reproduce

`pages/index.js`:

```
import '../src/somefile'

export default () => null;
```

Then edit and save `somefile`.

## Expected behavior

The user should see the warning, regardless of browser settings.

It would be nice if the error shows _after_ the reload, not before it

## Screenshots

![Full Reload](https://user-images.githubusercontent.com/880132/82270545-0f930600-996d-11ea-9292-53648cbfdae2.gif)

## System information

- Version of Next.js: 9.4.1

**Comment by Timer** [comment] 2020-08-06 14:35
Duplicate of #14701

**Closed by Timer** 2020-08-06 14:35 UTC
Labels: good first issue, kind: story

**Comment by balazsorban44** [comment] 2022-01-29 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
