### ISSUE TITLE
[NEXT-863] Unable to test page components using metadata API with Jest

### ISSUE THREAD

**Issue by andremendonca** [vercel/next.js#47299] opened 2023-03-19 19:29 UTC
### Verify canary release

* [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.8
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Jest (next/jest)

### Link to the code that reproduces this issue

[https://github.com/andremendonca/metadata-jest-error](https://github.com/andremendonca/metadata-jest-error)

### To Reproduce

git clone [https://github.com/andremendonca/metadata-jest-error.git](https://github.com/andremendonca/metadata-jest-error.git)
npm i
npm test

### Describe the Bug

in NextJs 13+ using the experimental App folder, I cannot test any server component that exports `metadata` or `generateMetadata` from [https://beta.nextjs.org/docs/api-reference/metadata](https://beta.nextjs.org/docs/api-reference/metadata)

Resulting in the following error:

```
 × NEXT_RSC_ERR_CLIENT_METADATA_EXPORT: metadata
       ╭─[/metadata-jest-bug/app/page.tsx:1:1]
     1 │ export const metadata = {
       ·              ────────
     2 │   title: 'My jest sample'
     3 │ }
       ╰────
```

### Expected Behavior

I expected to be able to test Server Components present on app directory

### Which browser are you using? (if relevant)

*No response*

### How are you deploying your application? (if relevant)

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-863](https://linear.app/vercel/issue/NEXT-863/unable-to-test-page-components-using-metadata-api-with-jest)</sub>

**Comment by CedericPrivat** [comment] 2023-04-05 07:03
> Hi, the issue is that `@testing-library/react` simulates a browser environment, while `metadata` is intended to run on the server only.
> 
> I will discuss with the team what we should recommend in this case, but if you want to test a page, you could likely use Playwright or a similar tool to spin up a server where `metadata` can run correctly.
> 
> Another solution could be to extract the Page component into a non-page file and import it into Jest from there, and re-export it in your page file.

I'm having the same issue. Are there any updates on recommendations for testing server components?

**Comment by red2678** [comment] 2023-04-09 09:15
Same issue.

**Comment by JeStew** [comment] 2023-04-18 17:36
Also having this issue

**Comment by kameikay** [comment] 2023-04-20 00:54
Same issue.

**Comment by RafaelZasas** [comment] 2023-05-02 17:22
same issue

**Comment by pravtz** [comment] 2023-05-12 21:53
same issue

**Comment by NebraskaCoder** [comment] 2023-05-21 01:40
Yup. Same.

**Comment by DonikaV** [comment] 2023-05-25 12:44
So, is it anyway to have tests with new app folder?

**Comment by piyushchauhan2011** [comment] 2023-05-25 13:01
For now I just use the way I saw in other issue

```ts
import { render, screen } from '@testing-library/react';
import Home from '@/app/page';

async function resolvedComponent(Component: any, props?: any) {
  const ComponentResolved = await Component(props);
  return () => ComponentResolved;
}

describe('Home', () => {
  it('renders a heading', async () => {
    const HomeResolved = await resolvedComponent(Home);
    render(<HomeResolved />);

    const heading = screen.getByRole('heading', {
      name: /welcome to next\.js!/i,
    });

    expect(heading).toBeInTheDocument();
  });
});
```

Seems to work for now and coverage seems to okay also

**Comment by red2678** [comment] 2023-05-26 10:32
Three months later. 

...rip

**Comment by phdduarte** [comment] 2023-05-27 23:32
same issue

**Comment by DonikaV** [comment] 2023-05-31 13:10
Anybody found a workaround ?

**Comment by fuyu77** [comment] 2023-06-09 23:29
I am writing the tests as follows: creating a wrapper server component for the Page component and writing Jest tests for it.

```tsx
// app/products/[id]/product-page.tsx

import type { Product } from '@/lib/api/interfaces/product';

interface Props {
  product: Product;
}

export default function ProductPage({ product }: Props) {
  return (
    <div>{product.name}</div>
  );
}

```

```tsx
// app/products/[id]/page.tsx

import ProductPage from './product-page';

interface Params {
  params: {
    id: string;
  };
}

export async function generateMetadata({ params }: Params) {
  const product = await fetch('https://api.example.com/...');
  const title = product.name;
  return { title };
}

export default async function Page({ params }: Params) {
  const product = await fetch('https://api.example.com/...');

  return <ProductPage product={product} />;
}
```

```tsx
// __tests__/app/products/[id]/product-page.test.tsx

import { render, screen } from '@testing-library/react';
import ProductPage from '@/app/products/[id]/product-page';

describe('ProductPage', () => {
  const product = { id: 1, name: 'product name' };

  test('renders props', () => {
    render(<ProductPage product={product} />);

    expect(screen.getByText(product.name)).toBeInTheDocument();
  });
});
```

**Comment by ctsstc** [comment] 2023-06-15 00:10
I was trying to write my first test in a brand new repository and it's a pretty sour taste in the mouth and frustrating when the first test you write blows up and SWC gives you no useful message to go off of. I also don't understand why the arrows for the error messages seem to point to nothing useful or relevant. Am I doing something wrong to get such an ugly useless stack trace, or is this just how SWC works; are people fine with this useless ugliness?¿¿ I love the speed that SWC seems to bring, but if it creates useless errors, it makes me not want it in my tooling if it's providing a bad DX.

## Minimum Reproduction

### Config

This seems to be irrelevant, but here's what I've got going on.

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  pageExtensions: ['page.tsx', 'page.ts', 'page.jsx', 'page.js'],
}

module.exports = nextConfig
```

### Directory Structure

```
./src/app/social/[userHandle]
├── page.test.tsx
└── page.tsx
```

### `page.test.tsx`

Just an irrelevant test. It seems to get angry that the  `generateMetadata` exists as an export from the imported file.

```tsx
import { add } from './page'

describe('Page', () => {
  describe('#add', () => {
    it('adds two numbers', () => {
      expect(add(1, 3)).toEqual(4)
    })
  })
})
```

### `page.tsx`

Note: This is just a minimal reproduction but the real code has some async work going on here.

```tsx
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  return {
    title: 'title',
    description: 'description',
  }
}

export default function SocialPage({ params }: Props) {
  return <h1>Hello Worlds</h1>
}

export function add(num1: number, num2: number) {
  return num1 + num2
}
```

**Comment by alfirmanpahlepi** [comment] 2023-06-17 17:41
same issue

**Comment by kevmarchant** [comment] 2023-06-20 15:26
Same here, anyone got any ideas?

**Comment by ctsstc** [comment] 2023-06-20 23:28
I ended up using Cypress to test this, but checking the exported function should be trivial. 

I know at the end of the day what I'm actually interested in is the outcome of the rendered page so Cypress makes sense. On the other hand that should be part of an implementation that's outside of the scope of my code (it belongs to Next JS, and I'll [blind] trust that the dependency I'm using is doing what I expect it to do)

**Comment by pravtz** [comment] 2023-07-05 11:51
same issue

**Comment by ryanhaticus** [comment] 2023-07-05 18:55
Experiencing this at the enterprise level. Definitely needs more attention.

**Comment by red2678** [comment] 2023-07-07 13:05
Not sure how my comment is spam, lol. No sense of humor? Also, not sure why people are downvoting the "same" comments. What do people expect them to say?? We are consumers of this, not the maintainers. This issue is more complex than a simple typo fix in the docs or something I feel. I would think it will require intimate knowledge of the internals of the framework even. It has now been four months with no real response from the team. Not even a "Hey we see this and will try to slate for fixing" or 
"This issue is more complex than a simple typo fix in the docs." This issue clearly affects many people, now even at the enterprise level. Rip...

**Comment by matinzd** [comment] 2023-07-07 13:32
> Not sure how my comment is spam, lol. No sense of humor? Also, not sure why people are downvoting the "same" comments. What do people expect them to say?? We are consumers of this, not the maintainers. This issue is more complex than a simple typo fix in the docs or something I feel. I would think it will require intimate knowledge of the internals of the framework even. It has now been four months with no real response from the team. Not even a "Hey we see this and will try to slate for fixing" or 
> 
> "This issue is more complex than a simple typo fix in the docs." This issue clearly affects many people, now even at the enterprise level. Rip...

Actually a member of the team has replied here:

https://github.com/vercel/next.js/issues/47299#issuecomment-1477912861

Also there is workaround mentioned above to separate your component from the actual page.

**Comment by andremendonca** [comment] 2023-07-07 13:36
> Not sure how my comment is spam, lol. No sense of humor? Also, not sure why people are downvoting the "same" comments. What do people expect them to say?? We are consumers of this, not the maintainers. This issue is more complex than a simple typo fix in the docs or something I feel. I would think it will require intimate knowledge of the internals of the framework even. It has now been four months with no real response from the team. Not even a "Hey we see this and will try to slate for fixing" or "This issue is more complex than a simple typo fix in the docs." This issue clearly affects many people, now even at the enterprise level. Rip...

What do you mean by Enterprise level? if it's about using on a client/at your company, that's me since the beginning. We had to put the migration to a halt due to this issue. And we aren't planning to do it until testing is possible without workarounds. (yes, it's Beta but that's another discussion)

**Comment by matinzd** [comment] 2023-07-07 14:40
Actually a member of the team has replied here:

https://github.com/vercel/next.js/issues/47299#issuecomment-1477912861

Also there is workaround mentioned above to independently test your component from the actual page.

**Comment by ryanhaticus** [comment] 2023-07-13 07:39
> > Not sure how my comment is spam, lol. No sense of humor? Also, not sure why people are downvoting the "same" comments. What do people expect them to say?? We are consumers of this, not the maintainers. This issue is more complex than a simple typo fix in the docs or something I feel. I would think it will require intimate knowledge of the internals of the framework even. It has now been four months with no real response from the team. Not even a "Hey we see this and will try to slate for fixing" or "This issue is more complex than a simple typo fix in the docs." This issue clearly affects many people, now even at the enterprise level. Rip...
> 
> 
> 
> What do you mean by Enterprise level? if it's about using on a client/at your company, that's me since the beginning. We had to put the migration to a halt due to this issue. And we aren't planning to do it until testing is possible without workarounds. (yes, it's Beta but that's another discussion)

Enterprise meaning Fortune 100.

**Comment by OscarJVD** [comment] 2023-07-19 15:37
same issue

**Comment by philwolstenholme** [comment] 2023-07-20 08:32
Does https://github.com/vercel/next.js/pull/52393 help here or is that a separate issue?

**Comment by inakianduaga** [comment] 2023-07-31 12:51
It's really dissapointing that this bug is still on after 4 months. `generateMetadata` is a built in feature from Nextjs, and using `jest` for testing components is really basic. The fact that the app directory was put on stable and there are bugs like this (alongside i18n support breaking draft mode and other things) puzzles me.

**Comment by tcnihr** [comment] 2023-07-31 13:26
Using RTL for integration testing is very common. Having to use Cypress as a workaround is such a shame

**Comment by weilin-ong** [comment] 2023-08-03 14:42
> Hi, the issue is that `@testing-library/react` simulates a browser environment, while `metadata` is intended to run on the server only.
> 
> I will discuss with the team what we should recommend in this case, but if you want to test a page, you could likely use Playwright or a similar tool to spin up a server where `metadata` can run correctly.
> 
> Another solution could be to extract the Page component into a non-page file and import it into Jest from there, and re-export it in your page file.

I'm also having the same issue in layout.tsx. How should i do it?

**Comment by justyn-clark** [comment] 2023-08-04 19:32
Same here 👋🏼

**Comment by pongbao** [comment] 2023-08-16 15:34
Same issue, but only occurs on Github Actions

![image](https://github.com/vercel/next.js/assets/20715325/137ea362-196c-4c32-b063-45e118074160)

```
jobs:
  simple_deployment_pipeline:
    name: Lint and install dependencies
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies on frontend
        working-directory: ./
        run: npm install
      - name: Run jest tests
        run: npm run test:ci
```

**Comment by nickmccurdy** [comment] 2023-08-17 19:21
Did you commit a lockfile update with the patched version of Next?

**Comment by theboyknowsclass** [comment] 2023-08-18 11:44
i did , but i still have the same issue on my repo -> https://github.com/CraftBeerCares/craftbeercares.github.io/pull/9

**Comment by theboyknowsclass** [comment] 2023-08-18 11:53
what version are we meant to be using?

**Comment by JamesBender** [comment] 2023-08-20 15:38
> It's really dissapointing that this bug is still on after 4 months. `generateMetadata` is a built in feature from Nextjs, and using `jest` for testing components is really basic. The fact that the app directory was put on stable and there are bugs like this (alongside i18n support breaking draft mode and other things) puzzles me.

I 100% agree here. I only considered version 13 for use on client work because the app directory was marked as stable. Being able to write tests isn't something I consider optional, and I have a hard enough time getting other developers to get on board with testing without having to have a workaround for this. The "... just use Playwrite" response is not sufficient. I REALLY like this framework, but it's difficult for me to promote it to my client with this issue unresolved.

**Comment by nickmccurdy** [comment] 2023-08-21 04:14
> what version are we meant to be using?

@theboyknowsclass You appear to be using the patched version, not sure why this is still broken.

**Comment by italogama** [comment] 2023-08-25 14:28
Same problem here. Waiting for a solution 😞

**Comment by agvst** [comment] 2023-08-25 19:10
The patch was reverted so it will be still a while I've for now passed on testing metadata and just wrap my component co-located with page.tsx

**Comment by theboyknowsclass** [comment] 2023-08-30 18:17
> > what version are we meant to be using?
> 
> @theboyknowsclass You appear to be using the patched version, not sure why this is still broken.

mine is a client-only app.... no server-side code, seems to be an issue with that?

**Closed** 2023-09-04 11:53 UTC
Labels: type: needs investigation, area: documentation, area: Metadata, area: Jest, area: app

**Comment by mruba** [comment] 2023-09-04 17:40
same issue here

**Comment by leerob** [comment] 2023-09-04 17:41
Hey everyone, we have a [fix](https://github.com/vercel/next.js/pull/54891) landed on the latest [canary](https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.16) (`v13.4.20-canary.16`). Please let us know if it's working for y'all 🙏 Appreciate your patience.

**Comment by mruba** [comment] 2023-09-04 17:46
> `v13.4.20-canary.16`

it works! thank you so much

**Comment by philwolstenholme** [comment] 2023-09-04 18:30
Do we use this new fix in the same way, by setting a Jest environment via a comment at the top of the file or via projects configuration?

**Comment by leerob** [comment] 2023-09-05 03:42
We're also updating examples here: https://github.com/vercel/next.js/pull/54989
