### ISSUE TITLE
router.push does not scroll to top

### ISSUE THREAD

**Issue by stefanprobst** [vercel/next.js#19096] opened 2020-11-12 10:44 UTC
# Bug report

## Describe the bug

When navigating with `router.push`, the page does not scroll to the top when the route transition is done. Note that it *does* scroll to top when navigating with `next/link`.

## To Reproduce

Repro: https://codesandbox.io/s/dreamy-blackwell-0tp3v?file=/pages/index.js

1. Scroll down and click link => page scrolls to top
2. Scroll down and click button => page does not scroll to top

## Expected behavior

`next/link` and `next/router` should have the same behavior.

## System information

- Version of Next.js: 10.0.2-canary.12

**Comment by Tomburgs** [comment] 2020-11-22 19:29
Hey, @stefanprobst & @Timer

I created PR #19419, tested it with the example and it seems to be working now as expected.
Would be great to get some more eyes on it 👀.

**Comment by timneutkens** [comment] 2020-11-27 15:20
Closing as duplicate of #15206, we'll track it there.

**Closed by timneutkens** 2020-11-27 15:20 UTC
Labels: kind: story, point: 3

**Comment by balazsorban44** [comment] 2022-01-29 02:12
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
