### ISSUE TITLE
Shallow routing is broken in the latest release 

### ISSUE THREAD

**Issue by DiaaEddinBK** [vercel/next.js#39077] opened 2022-07-27 16:13 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

   Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.4-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

I am using shallow routing, in the new next release but I noticed that it is not updating query when middlware.ts is present, which is not the intended behavior

### Expected Behavior

router.query should be updated after router.push when shallow is enabled and middleware.ts is present

### Link to reproduction

https://github.com/DiaaEddinBK/nextjs

### To Reproduce

you just need to try shallow push with a query on a project that contains middleware.ts file, router.query won't get updated after the shallow push which is a bug

**Comment by ijjk** [comment] 2022-07-27 16:30
Duplicate of https://github.com/vercel/next.js/issues/38495

**Closed by ijjk** 2022-07-27 16:30 UTC
Labels: template: bug

**Comment by DiaaEddinBK** [comment] 2022-07-27 16:31
@ijjk the auth blocked me from commenting on that issue, and I needed it to get more attention,  I am welling to help if needed

**Comment by ijjk** [comment] 2022-07-27 16:34
This is actively being investigated, no need to create a new issue

**Comment by DiaaEddinBK** [comment] 2022-07-27 16:38
@ijjk thanks, I really appreciate the work that you are doing, if possible could you kindly give me a rough estimation on when the patch for this bug will be released?

**Comment by DiaaEddinBK** [comment] 2022-07-27 16:44
@ijjk actually no the Author did not block me, that was a different issue, also a duplicate of that one, my bad
