### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by phanvanluan94** [vercel/next.js#30907] opened 2021-11-03 18:31 UTC
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

12.22.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

This is happening in production mode after I upgraded from version 11.
Removing `.next`, re-generate the lock file of yarn, removing node_modules did not help.

Stacktrace:
`HookWebpackError: Maximum call stack size exceeded
    at makeWebpackError (/project/node_modules/next/dist/compiled/webpack/bundle5.js:45539:9)
    at /project/node_modules/next/dist/compiled/webpack/bundle5.js:29467:12
    at eval (eval at create (/project/node_modules/next/dist/compiled/webpack/bundle5.js:141008:10), <anonymous>:42:1)
-- inner error --
RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at c (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:29404)
    at s.exports (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:31711)
    at SourceMapSource.streamChunks (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:21241)
    at s.exports (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:26456)
    at ReplaceSource.streamChunks (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:14734)
    at s.exports (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:26456)
    at u (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:25807)
    at CachedSource.streamChunks (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:3491)
    at s.exports (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:26456)
caused by plugins in Compilation.hooks.processAssets
RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at c (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:29404)
    at s.exports (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:31711)
    at SourceMapSource.streamChunks (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:21241)
    at s.exports (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:26456)
    at ReplaceSource.streamChunks (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:14734)
    at s.exports (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:26456)
    at u (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:25807)
    at CachedSource.streamChunks (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:3491)
    at s.exports (/project/node_modules/next/dist/compiled/webpack-sources3/index.js:1:26456)
`

### Expected Behavior

It should compile with custom configuration.

### To Reproduce

1. Use custom Babel configuration
2. Use custom webpack
3. Use terser webpack plugin for minification instead of built-in SWC feature.
4. `next build`

**Comment by timneutkens** [comment] 2021-11-04 09:48
I'm going to close this as this issue is not actionable, please make sure to follow the issue template and review what you wrote down before posting to ensure it can be reproduced based on the information provided, without having your application these reproduction steps simply can't be used.

Example:

> Use custom Babel configuration

This is not provided in the issue.

> Use custom webpack

This is not provided in the issue.

> Use terser webpack plugin for minification instead of built-in SWC feature.

This is not provided in the issue.

**Closed by timneutkens** 2021-11-04 09:48 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 11:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
