### ISSUE TITLE
Webpack 5 resolution is producing an error after upgrading to version 10 from 9

### ISSUE THREAD

**Issue by ebsaral** [vercel/next.js#20842] opened 2021-01-07 08:30 UTC
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

15.0.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

Vercel

**Describe the Bug**

I upgraded Next.js from 9 to 10 and I am trying to use webpack resolution in package.json as shown:

```javascript
"resolutions": {
    "webpack": "5.11.1"
 }
```

Then I want to run the local environment with the command `NODE_ENV=development NODE_OPTIONS='--inspect' next` (to show the exact command), yet I encounter this error:

```
Debugger listening on ws://127.0.0.1:9229/29f28a0b-9c95-408e-8e02-e399deaea229
For help, see: https://nodejs.org/en/docs/inspector
Loaded env from /Users/ebs/finn/finn-auto-ui-frontend/.env
ready - started server on http://localhost:3000
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration[0].module.rules[3] should be one of these:
   ["..." | object { compiler?, dependency?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, loader?, mimetype?, oneOf?, options?, parser?, realResource?, resolve?, resource?, resourceFragment?, resourceQuery?, rules?, sideEffects?, test?, type?, use? }, ...]
   -> A rule.
   Details:
    * configuration[0].module.rules[3].loader should be a non-empty string.
      -> A loader request.
 - configuration[1].module.rules[3] should be one of these:
   ["..." | object { compiler?, dependency?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, loader?, mimetype?, oneOf?, options?, parser?, realResource?, resolve?, resource?, resourceFragment?, resourceQuery?, rules?, sideEffects?, test?, type?, use? }, ...]
   -> A rule.
   Details:
    * configuration[1].module.rules[3].loader should be a non-empty string.
      -> A loader request.
    at validate (/Users/ebs/finn/finn-auto-ui-frontend/node_modules/webpack/node_modules/schema-utils/dist/validate.js:104:11)
    at validateSchema (/Users/ebs/finn/finn-auto-ui-frontend/node_modules/webpack/lib/validateSchema.js:79:2)
    at create (/Users/ebs/finn/finn-auto-ui-frontend/node_modules/webpack/lib/webpack.js:100:3)
    at webpack (/Users/ebs/finn/finn-auto-ui-frontend/node_modules/webpack/lib/webpack.js:137:31)
    at f (/Users/ebs/finn/finn-auto-ui-frontend/node_modules/webpack/lib/index.js:37:15)
    at HotReloader.start (/Users/ebs/finn/finn-auto-ui-frontend/node_modules/next/dist/server/hot-reloader.js:16:415)
    at async DevServer.prepare (/Users/ebs/finn/finn-auto-ui-frontend/node_modules/next/dist/server/next-dev-server.js:15:414)
    at async /Users/ebs/finn/finn-auto-ui-frontend/node_modules/next/dist/cli/next-dev.js:22:1 {
  errors: [
    {
      keyword: 'oneOf',
      dataPath: '[0].module.rules',
      schemaPath: '#/properties/rules/oneOf',
      params: [Object],
      message: 'should match exactly one schema in oneOf',
      schema: [Array],
      parentSchema: [Object],
      data: [Array],
      children: [Array]
    },
    {
      keyword: 'oneOf',
      dataPath: '[1].module.rules',
      schemaPath: '#/properties/rules/oneOf',
      params: [Object],
      message: 'should match exactly one schema in oneOf',
      schema: [Array],
      parentSchema: [Object],
      data: [Array],
      children: [Array]
    }
  ],
  schema: {
    definitions: {
      Amd: [Object],
      AssetModuleFilename: [Object],
      AuxiliaryComment: [Object],
      Bail: [Object],
      CacheOptions: [Object],
      CacheOptionsNormalized: [Object],
      Charset: [Object],
      ChunkFilename: [Object],
      ChunkFormat: [Object],
      ChunkLoadTimeout: [Object],
      ChunkLoading: [Object],
      ChunkLoadingGlobal: [Object],
      ChunkLoadingType: [Object],
      CompareBeforeEmit: [Object],
      Context: [Object],
      CrossOriginLoading: [Object],
      Dependencies: [Object],
      DevServer: [Object],
      DevTool: [Object],
      DevtoolFallbackModuleFilenameTemplate: [Object],
      DevtoolModuleFilenameTemplate: [Object],
      DevtoolNamespace: [Object],
      EnabledChunkLoadingTypes: [Object],
      EnabledLibraryTypes: [Object],
      EnabledWasmLoadingTypes: [Object],
      Entry: [Object],
      EntryDescription: [Object],
      EntryDescriptionNormalized: [Object],
      EntryDynamic: [Object],
      EntryDynamicNormalized: [Object],
      EntryItem: [Object],
      EntryNormalized: [Object],
      EntryObject: [Object],
      EntryRuntime: [Object],
      EntryStatic: [Object],
      EntryStaticNormalized: [Object],
      EntryUnnamed: [Object],
      Environment: [Object],
      Experiments: [Object],
      ExternalItem: [Object],
      Externals: [Object],
      ExternalsPresets: [Object],
      ExternalsType: [Object],
      FileCacheOptions: [Object],
      Filename: [Object],
      FilterItemTypes: [Object],
      FilterTypes: [Object],
      GlobalObject: [Object],
      HashDigest: [Object],
      HashDigestLength: [Object],
      HashFunction: [Object],
      HashSalt: [Object],
      HotUpdateChunkFilename: [Object],
      HotUpdateGlobal: [Object],
      HotUpdateMainFilename: [Object],
      IgnoreWarnings: [Object],
      IgnoreWarningsNormalized: [Object],
      Iife: [Object],
      ImportFunctionName: [Object],
      ImportMetaName: [Object],
      InfrastructureLogging: [Object],
      Library: [Object],
      LibraryCustomUmdCommentObject: [Object],
      LibraryCustomUmdObject: [Object],
      LibraryExport: [Object],
      LibraryName: [Object],
      LibraryOptions: [Object],
      LibraryType: [Object],
      Loader: [Object],
      MemoryCacheOptions: [Object],
      Mode: [Object],
      ModuleOptions: [Object],
      Name: [Object],
      Node: [Object],
      NodeOptions: [Object],
      Optimization: [Object],
      OptimizationRuntimeChunk: [Object],
      OptimizationRuntimeChunkNormalized: [Object],
      OptimizationSplitChunksCacheGroup: [Object],
      OptimizationSplitChunksGetCacheGroups: [Object],
      OptimizationSplitChunksOptions: [Object],
      OptimizationSplitChunksSizes: [Object],
      Output: [Object],
      OutputModule: [Object],
      OutputNormalized: [Object],
      Parallelism: [Object],
      Path: [Object],
      Pathinfo: [Object],
      Performance: [Object],
      PerformanceOptions: [Object],
      Plugins: [Object],
      Profile: [Object],
      PublicPath: [Object],
      RecordsInputPath: [Object],
      RecordsOutputPath: [Object],
      RecordsPath: [Object],
      Resolve: [Object],
      ResolveAlias: [Object],
      ResolveLoader: [Object],
      ResolveOptions: [Object],
      ResolvePluginInstance: [Object],
      RuleSetCondition: [Object],
      RuleSetConditionAbsolute: [Object],
      RuleSetConditionOrConditions: [Object],
      RuleSetConditionOrConditionsAbsolute: [Object],
      RuleSetConditions: [Object],
      RuleSetConditionsAbsolute: [Object],
      RuleSetLoader: [Object],
      RuleSetLoaderOptions: [Object],
      RuleSetRule: [Object],
      RuleSetRules: [Object],
      RuleSetUse: [Object],
      RuleSetUseItem: [Object],
      ScriptType: [Object],
      SnapshotOptions: [Object],
      SourceMapFilename: [Object],
      SourcePrefix: [Object],
      StatsOptions: [Object],
      StatsValue: [Object],
      StrictModuleExceptionHandling: [Object],
      Target: [Object],
      UmdNamedDefine: [Object],
      UniqueName: [Object],
      WasmLoading: [Object],
      WasmLoadingType: [Object],
      Watch: [Object],
      WatchOptions: [Object],
      WebassemblyModuleFilename: [Object],
      WebpackOptionsNormalized: [Object],
      WebpackPluginFunction: [Object],
      WebpackPluginInstance: [Object]
    },
    description: 'Options object as provided by the user.',
    type: 'object',
    additionalProperties: false,
    properties: {
      amd: [Object],
      bail: [Object],
      cache: [Object],
      context: [Object],
      dependencies: [Object],
      devServer: [Object],
      devtool: [Object],
      entry: [Object],
      experiments: [Object],
      externals: [Object],
      externalsPresets: [Object],
      externalsType: [Object],
      ignoreWarnings: [Object],
      infrastructureLogging: [Object],
      loader: [Object],
      mode: [Object],
      module: [Object],
      name: [Object],
      node: [Object],
      optimization: [Object],
      output: [Object],
      parallelism: [Object],
      performance: [Object],
      plugins: [Object],
      profile: [Object],
      recordsInputPath: [Object],
      recordsOutputPath: [Object],
      recordsPath: [Object],
      resolve: [Object],
      resolveLoader: [Object],
      snapshot: [Object],
      stats: [Object],
      target: [Object],
      watch: [Object],
      watchOptions: [Object]
    }
  },
  headerName: 'Webpack',
  baseDataPath: 'configuration',
  postFormatter: [Function: postFormatter]
}
error Command failed with exit code 1.
```

**Expected Behavior**

`next` command to run without giving an error. 

**To Reproduce**

next.config.js 

```
const withSourceMaps = require("@zeit/next-source-maps")();
const SentryWebpackPlugin = require("@sentry/webpack-plugin");
const path = require('path');
const withTM = require('next-transpile-modules')([
  'cookies-next',
  'csso',
  'css-tree',
  'lru-cache',
  'react-intl',
  'react-in-viewport',
  'split-on-first',
  'strict-uri-encode',
  'query-string',
  'yallist'
]);
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true'
});

const {
  NEXT_PUBLIC_SENTRY_DSN: SENTRY_DSN,
  SENTRY_ORG,
  SENTRY_PROJECT,
  SENTRY_AUTH_TOKEN,
  VERCEL_GITLAB_COMMIT_SHA,
  APP_STAGE
} = process.env;

let config = {
    env: {
      APP_STAGE: process.env.APP_STAGE,
      SENTRY_ORG: process.env.SENTRY_ORG,
      SENTRY_PROJECT: process.env.SENTRY_PROJECT
    },
  serverRuntimeConfig: {
    rootDir: __dirname,
  },
  webpack: (config, options) => {
    config.optimization.splitChunks.maxInitialRequests = 5;
    config.module.rules.push({
      test: /\.(eot|woff|woff2|ttf|png|jpg|gif)$/,
      use: {
        loader: 'url-loader',
        options: {
          limit: 100000,
          name: '[name].[ext]'
        }
      },
      test: /\.svg$/,
      use: [
        {
          loader: '@svgr/webpack',
          options: {
            memo: true,
          },
        },
      ],
    });

    if (!options.isServer) {
      config.resolve.alias["@sentry/node"] = "@sentry/browser";
    }

    config.resolve.alias['~'] = path.resolve(__dirname);

    if (
      SENTRY_DSN &&
      SENTRY_ORG &&
      SENTRY_PROJECT &&
      SENTRY_AUTH_TOKEN &&
      APP_STAGE !== "development"
    ) {
      config.plugins.push(
        new SentryWebpackPlugin({
          authToken: SENTRY_AUTH_TOKEN,
          org: SENTRY_ORG,
          project: SENTRY_PROJECT,
          include: ".next",
          ignore: ["node_modules"],
          stripPrefix: ["webpack://_N_E/"],
          urlPrefix: "~/_next",
          release: VERCEL_GITLAB_COMMIT_SHA || 'preview',
        })
      );
    }
    return config;
  }
}

config = withTM(config);
config = withBundleAnalyzer(config);
config = withSourceMaps(config);

module.exports =config
```

package.json

```
{
  "name": "ui-frontend",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "analyze:bundle": "cross-env ANALYZE=true next build",
    "analyze:unused": "next-unused",
    "start": "next start -p $PORT",
    "dev": "cross-env NODE_ENV=development NODE_OPTIONS='--inspect' next",
    "dev2": "yarn && yarn dev",
    "dev:vercel": "cross-env NODE_ENV=development NODE_OPTIONS='--inspect' vercel dev",
    "build": "next build",
    "build:check": "tsc --noEmit",
    "build:robots": "node scripts/buildRobotsTxt.js",
    "e2e": "yarn e2e:run",
    "e2e:production": "CYPRESS_STAGE=production yarn e2e:run",
    "e2e:production:open": "CYPRESS_STAGE=production yarn e2e:open",
    "e2e:staging": "CYPRESS_STAGE=staging yarn e2e:run",
    "e2e:staging:open": "CYPRESS_STAGE=staging yarn e2e:open",
    "e2e:install": "cypress install",
    "e2e:open": "CYPRESS_STAGE=${CYPRESS_STAGE:-development}; cypress open --config-file cypress/config-$CYPRESS_STAGE.json",
    "e2e:run": "CYPRESS_STAGE=${CYPRESS_STAGE:-development}; cypress run --config-file cypress/config-$CYPRESS_STAGE.json",
    "e2e:ci": "yarn e2e:install && cypress run --record",
    "lint": "eslint \"**/*.{ts,tsx}\" --quiet",
    "lint:fix": "eslint \"**/*.{ts,tsx}\" --fix --quiet",
    "test": "jest"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@date-io/dayjs": "1.x",
    "@fullstory/browser": "^1.4.5",
    "@material-ui/core": "^4.8.2",
    "@material-ui/icons": "^4.5.1",
    "@material-ui/lab": "^4.0.0-alpha.39",
    "@material-ui/pickers": "^3.2.9",
    "@sentry/browser": "^5.27.3",
    "@sentry/integrations": "^5.26.0",
    "@sentry/node": "^5.26.0",
    "@sentry/types": "^5.26.0",
    "@sentry/webpack-plugin": "^1.13.0",
    "@types/jsonwebtoken": "^8.5.0",
    "axios": "^0.21.1",
    "axios-retry": "^3.1.9",
    "classnames": "^2.2.6",
    "cookie": "^0.4.0",
    "cookies-next": "^1.1.3",
    "cosmicjs": "^3.2.40",
    "create-file-list": "^1.1.0",
    "css-mediaquery": "^0.1.2",
    "dayjs": "^1.9.7",
    "formik": "^2.1.2",
    "google-auth-library": "^6.1.3",
    "html-react-parser": "^0.10.0",
    "hubspot": "https://github.com/mahmoudalwadia/node-hubspot/tarball/2fabaf4",
    "husky": "^4.3.0",
    "iban": "^0.0.14",
    "intersection-observer": "^0.11.0",
    "intl-messageformat-parser": "^3.6.2",
    "js-cookie": "^2.2.1",
    "jsonwebtoken": "^8.5.1",
    "jsrender": "^1.0.7",
    "lazysizes": "^5.2.0",
    "lint-staged": "^10.4.0",
    "lodash": "^4.17.15",
    "lru-cache": "^6.0.0",
    "next": "10.0.5",
    "next-absolute-url": "^1.2.2",
    "next-transpile-modules": "^6.0.0",
    "nodemailer": "^6.4.6",
    "nprogress": "^0.2.0",
    "query-string": "6.10.1",
    "react": "^16.12.0",
    "react-content-loader": "^5.1.4",
    "react-dom": "^16.12.0",
    "react-gtm-module": "^2.0.8",
    "react-in-viewport": "^1.0.0-alpha.14",
    "react-intl": "^5.8.4",
    "react-masonry-css": "^1.0.14",
    "react-slick": "^0.27.13",
    "react-storefront": "^8.17.4",
    "recompose": "^0.30.0",
    "rmc-date-picker": "^6.0.10",
    "rmc-picker": "^5.0.10",
    "slick-carousel": "^1.8.1",
    "slugify": "^1.4.0",
    "yup": "^0.29.3"
  },
  "resolutions": {
    "webpack": "5.11.1"
  }
  ,
  "devDependencies": {
    "@next/bundle-analyzer": "^9.3.0",
    "@svgr/webpack": "^5.4.0",
    "@types/classnames": "^2.2.9",
    "@types/cookie": "^0.3.3",
    "@types/css-mediaquery": "^0.1.0",
    "@types/formidable": "^1.0.31",
    "@types/iban": "^0.0.30",
    "@types/jest": "^26.0.14",
    "@types/js-cookie": "^2.2.4",
    "@types/lodash": "^4.14.149",
    "@types/lru-cache": "^5.1.0",
    "@types/node": "^13.1.2",
    "@types/nodemailer": "^6.4.0",
    "@types/nprogress": "^0.2.0",
    "@types/react": "^16.9.17",
    "@types/react-gtm-module": "^2.0.0",
    "@types/react-slick": "^0.23.4",
    "@types/react-test-renderer": "^16.9.3",
    "@types/recompose": "^0.30.7",
    "@types/request-promise": "^4.1.45",
    "@types/yup": "^0.26.27",
    "@typescript-eslint/eslint-plugin": "^4.7.0",
    "@typescript-eslint/parser": "^4.7.0",
    "@zeit/next-source-maps": "0.0.4-canary.1",
    "axios-mock-adapter": "^1.17.0",
    "cross-env": "^7.0.2",
    "cypress": "5.0.0",
    "cypress-terminal-report": "^1.4.2",
    "eslint": "^7.13.0",
    "eslint-config-prettier": "^6.15.0",
    "eslint-import-resolver-babel-module": "^5.2.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-react-hooks": "^4.2.0",
    "jest": "^26.4.2",
    "next-unused": "^0.0.3",
    "pre-commit": "^1.2.2",
    "prettier": "^1.19.1",
    "react-test-renderer": "^16.13.1",
    "ts-jest": "^26.4.1",
    "typescript": "3.9.7",
    "url-loader": "^3.0.0"
  },
  "lint-staged": {
    "**/*.{ts,tsx}": [
      "yarn lint:fix"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged",
      "pre-push": "yarn build:check"
    }
  },
  "next-unused": {
    "alias": {
      "~": "."
    },
    "include": [
      "pages",
      "components",
      "contexts",
      "hooks",
      "layouts",
      "services",
      "utils"
    ],
    "exclude": [
      "\\.d\\.ts$",
      "\\.test\\.ts$"
    ],
    "entrypoints": []
  }
}
```

**Comment by timneutkens** [comment] 2021-01-07 09:19
Sounds unrelated to Next.js itself, we have tests to ensure webpack 5 works. You're customizing the webpack configuration through various plugins which is likely the cause of the incompatibility.

**Comment by Timer** [comment] 2021-01-07 13:38
Closing as no reproduction given.
However, this is definitely a bug with your custom configuration and not Next.js itself.

**Closed by Timer** 2021-01-07 13:38 UTC
Labels: please add a complete reproduction

**Comment by bryanmig** [comment] 2021-01-29 14:31
I just upgraded to Next 10 and Webpack 5 and I am seeing the same issue - through process of elimination, I found that the problem is `@next/bundle-analyzer` and after removing this plugin, my builds are passing now.

**Comment by ebsaral** [comment] 2021-01-29 14:58
@bryanmig For us, the problem was that we were using `next-transpile-modules` and add this config:
```
{
  unstable_webpack5: true
}
```

Must be related to a package you are using in `next.config.js` as well.

**Comment by bryanmig** [comment] 2021-02-01 20:03
@ebsaral yes! I jumped the gun when blaming `@next/bundle-analyzer` but this is **not** the cause - I had also commented out the `next-transpile-modules` usage and didn't realize it. However, enabling the flag you mention did not fix it for me.

**Comment by avaneeshtripathi** [comment] 2021-07-08 08:09
@bryanmig  Did we find any resolution for this? For me, its the `next-transpile-modules` commenting which builds successfully but, since the loaders are missing, app won't work. I need the transpile modules here. What may be a solution?

**Comment by balazsorban44** [comment] 2022-01-27 17:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
