### ISSUE TITLE
Unused import causes MongoDb to break

### ISSUE THREAD

**Issue by dasveloper** [vercel/next.js#28942] opened 2021-09-08 22:19 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

15.7.0

### What browser are you using?

Crhome

### What operating system are you using?

macOD

### How are you deploying your application?

next dev, locally

### Describe the Bug

See [this repo](https://github.com/dasveloper/test-mongoose) for a minimal reproduction of the issue. It is a slight modification of the [Next Mongoose example](https://github.com/vercel/next.js/tree/canary/examples/with-mongodb-mongoose).

**Short Description:**
When importing a function from a file that uses a MongoDB connection, if you do not use that imported function it causes MongoDB to throw errors.

**Longer Description:**
In my [services file](https://github.com/dasveloper/test-mongoose/blob/master/lib/services.js) I have two functions `fetchPets` and `fetchFoo`. `fetchPets` connects to my Mongo database via the [dbConnect function](https://github.com/dasveloper/test-mongoose/blob/master/lib/dbConnect.js). Both `fetchPets` and `fetchFoo` are imported into my [index.js file](https://github.com/dasveloper/test-mongoose/blob/master/pages/index.js#L2). `fetchPets` is used in `getServerSideProps` but  `fetchFoo` is never used anywhere. When I then run the application with `next dev` I receive an error: **Error: Please define the MONGODB_URI environment variable inside .env.local**. However, if I just remove the unused function `fetchFoo` from the import then the application runs fine and `fetchPets` is able to successfully connect and read from the database. Also, at the time of the above error, I am able to console.log MONGODB_URI successfully even though it throws an error for being undefined.

### Expected Behavior

When I have an unused import in a file, it should not cause the application/Mongo to throw errors.

### Step 1. Clone this example repo locally
https://github.com/dasveloper/test-mongoose

### Step 2. Get the connection string of your MongoDB server

In the case of MongoDB Atlas, it should be a string like this:

```
mongodb+srv://<username>:<password>@my-project-abc123.mongodb.net/test?retryWrites=true&w=majority
```

### Step 3. Set up environment variables

Copy the `.env.local.example` file in this directory to `.env.local`:

```bash
cp .env.local.example .env.local
```

Then set each variable on `.env.local`:

- `MONGODB_URI` should be the MongoDB connection string you got from step 1.

### Step 4. Run Next.js in development mode

```bash
npm install
npm run dev

# or

yarn install
yarn dev
```

**At this point you should see the error message: "Error: Please define the MONGODB_URI environment variable inside .env.local"**

### Step 5. Remove the unused import
Remove `fetchFoo` from the imports on [line 2 of index.js](https://github.com/dasveloper/test-mongoose/blob/master/pages/index.js#L2) and re-run Next.js in development mode

**At this point the error message should be gone and the app will run smoothly**

**Comment by DannyXT** [comment] 2021-09-09 01:08
From my point of view, by leaving that import (`fetchFoo`) unused, you're trying to run server-side code on the client side. And because of [how next.js uses environment variables](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser), `MONGODB_URI` in client-side, it doesn't exist.


I quote here one of the notes that are in the documentation [basic-features/data-fetching#getserversideprops-server-side-rendering](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering)
> **Note**: You can import modules in top-level scope for use in `getServerSideProps`. Imports used in `getServerSideProps` will not be bundled for the client-side.
> This means you can write **server-side code directly in** `getServerSideProps`. This includes reading from the filesystem or a database.

**Comment by dasveloper** [comment] 2021-09-09 01:17
> From my point of view, by leaving that import (`fetchFoo`) unused, you're trying to run server-side code on the client side. And because of [how next.js uses environment variables](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser), `MONGODB_URI` in client-side, it doesn't exist.
> 
> I quote here one of the notes that are in the documentation [basic-features/data-fetching#getserversideprops-server-side-rendering](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering)
> 
> > **Note**: You can import modules in top-level scope for use in `getServerSideProps`. Imports used in `getServerSideProps` will not be bundled for the client-side.
> > This means you can write **server-side code directly in** `getServerSideProps`. This includes reading from the filesystem or a database.

Oh I see, that really clarifies it. The act of using it in `getServerSideProps` removes it from the client side bundle. Is there a reason it isn't removed from both the client and server side bundles if the import is completely unused?

**Comment by ijjk** [comment] 2021-09-18 15:35
@dasveloper the reason the import isn't automatically removed if it is un-used is due to side-effects the module can have (more info [here](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free). You can also test the code elimination Next.js uses here https://next-code-elimination.vercel.app/

I'm gonna close this since it doesn't appear to be a bug and is currently the expected behavior.

**Closed by ijjk** 2021-09-18 15:35 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
