### ISSUE TITLE
Yarn Berry + inspect/debugger mode fails

### ISSUE THREAD

**Issue by osdiab** [vercel/next.js#21270] opened 2021-01-18 07:17 UTC
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

14.3.0

**What browser are you using?**

Firefox, but irrelevant

**What operating system are you using?**

macOS

**How are you deploying your application?**

Not deployed

**Describe the Bug**

If you use `yarn berry` with pnp mode on, and try to add `NODE_OPTIONS='--inspect'` to your dev command, it crashes.

**Expected Behavior**

It should run your app with the debugger on.

**To Reproduce**

1. Clone https://github.com/osdiab/berry-inspect-nextjs
1. `yarn && yarn dev`

Example was created as follows:

1. `yarn create next-app berry-inspect-nextjs`
1. `cd berry-inspect-nextjs`
1. `yarn set version berry`
1. `rm -rf node_modules`
1. `yarn`
1. Edit `package.json` `"dev"` script to have prefix `NODE_OPTIONS='--inspect'`

**Comment by merceyz** [comment] 2021-01-29 17:00
The repository you're linking to is empty, but the issue is that you're overriding the env variable set by Yarn. You need to preserve the original one

```
NODE_OPTIONS="$NODE_OPTIONS --inspect" next
```
Or you can tell Yarn to add it for you
```
yarn run --inspect next
```
https://yarnpkg.com/cli/run#options-inspect

**Comment by meglio** [comment] 2021-08-13 12:02
This is the issue for me with using Yarn 3.0.0. (Berry) and yarn run --inspect. For example, in my package.json:

```
"debug": "NEXT_TELEMETRY_DISABLED=1 NODE_OPTIONS='--inspect' next dev -H loc.antonphp.com"
```

and then in my terminal:

`yarn run --inspect debug`

This starts Next.js application successfully, but debugger is not started / no listening to any port. There should be note in the command line about a debugger starting to list on some port, but it does not happen. So basically specifying `--inspect` does nothing.

**Comment by meglio** [comment] 2021-08-13 13:01
Is there a workaround until this is fixed?

**Comment by merceyz** [comment] 2021-08-13 13:46
Look at the examples in https://github.com/vercel/next.js/issues/21270#issuecomment-769925932

**Comment by ijjk** [comment] 2021-09-23 04:28
Closing per above https://github.com/vercel/next.js/issues/21270#issuecomment-898468970 as this doesn't sound like a Next.js bug and using the shown example appears to work correctly.

**Closed by ijjk** 2021-09-23 04:28 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
