### ISSUE TITLE
Could not download "with-mongodb" because of a connectivity issue between your machine and GitHub.

### ISSUE THREAD

**Issue by iamKushagra** [vercel/next.js#40154] opened 2022-09-01 13:28 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

While cloning the MongoDB template for next.js using this command:
`npx create-next-app --example with-mongodb mflix`

I am facing this issue:
`Downloading files for example with-mongodb. This might take a moment.`

`? Could not download "with-mongodb" because of a connectivity issue between your machine and GitHub.`
`✔ Could not download "with-mongodb" because of a connectivity issue between your machine and GitHub.`
`Do you want to use the default template instead? …`

Any suggestions?

### Which example does this report relate to?

with-mongodb

### Describe the Bug

`✔ Could not download "with-mongodb" because of a connectivity issue between your machine and GitHub.`

### Expected Behavior

This could work normally

### To Reproduce

Hit `npx create-next-app --example with-mongodb mflix` to reproduce

**Comment by balazsorban44** [comment] 2022-09-01 14:13
Sounds like a duplicate of https://github.com/vercel/next.js/issues/39321 could you verify the Node.js version you are on?

**Comment by iamKushagra** [comment] 2022-09-02 04:18
> Sounds like a duplicate of #39321 could you verify the Node.js version you are on?

v18.7.0

**Comment by balazsorban44** [comment] 2022-09-02 11:02
Thanks. Closing in favor of #39321 as there is a direct correlation of Node 18 > with this bug.

**Closed by balazsorban44** 2022-09-02 11:02 UTC
Labels: area: create-next-app, template: bug
