### ISSUE TITLE
A "use server" file can only export async functions' error when exporting non-async/cache functions

### ISSUE THREAD

**Issue by RiodeJaneiroo** [vercel/next.js#62926] opened 2024-03-06 09:09 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:27 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8103
  Available memory (MB): 8192
  Available CPU cores: 8
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: 8.15.4
Relevant Packages:
  next: 14.2.0-canary.2 // Latest available version is detected (14.2.0-canary.2).
  eslint-config-next: 14.1.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: standalone
```

### Which example does this report relate to?

none

### Describe the Bug

When using the "use server" directive at the top of a file in a Next.js application, if the file exports a non-async function or a React cache function (e.g., React.cache), it throws the following error:

`Error: A "use server" file can only export async functions.`

### Expected Behavior

The expected behavior is to allow exporting non-async functions and React cache functions from a file with the "use server" directive without any errors.

### To Reproduce

[StackBlitz](https://stackblitz.com/edit/stackblitz-starters-dsgbkn?file=app%2Fpage.tsx)

**Comment by idotalmor** [comment] 2024-03-06 10:23
I'm new to nextjs but i don't think it's an error, even if the function code is not async, it runs on server so when the client calls it it's an async call. IMO

**Comment by chungweileong94** [comment] 2024-03-06 14:34
The issue is caused by the stricter `use server` check in the recent 14.1.2 update, it seems to me NextJS is performing syntax-level checking which might raise some false errors. It actually breaks my [server action builder package](https://github.com/chungweileong94/server-act).

Repro: https://github.com/chungweileong94/next-use-server-bug

**Comment by ceIia** [comment] 2024-03-06 15:19
yeah, i had to make sure i used the `export async function(return somepromise)` syntax, as `export const = async () => { await ... }` would not work

**Comment by chungweileong94** [comment] 2024-03-07 07:33
It seems like NextJS is doing `action.constructor.name !== 'AsyncFunction'` check, however, if the action is created via a library, it will get transpiled into `Promise<...>` instead of `action.constructor.name !== 'AsyncFunction'`. 
The only workaround now is to create an async function that wraps around, which is kinda annoying. 

https://github.com/vercel/next.js/blob/7f7943b755f59b3b9c2bdf95f87b89062c75dd8a/packages/next/src/build/webpack/loaders/next-flight-loader/action-validate.ts#L16

**Comment by bduff9** [comment] 2024-03-07 19:18
Its worth noting that this currently breaks the example shown in the documentation around using React.cache currently: https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#fetching-data-on-the-server-with-third-party-libraries

**Comment by shuding** [comment] 2024-03-10 14:25
This is a duplicate of #62860 - please give https://github.com/vercel/next.js/issues/62860#issuecomment-1978730839 and #62821 a read. We'll keep everyone updated there.

Basically it does not make sense to use `React.cache` together with Server Actions and it will not cache anything.

**Closed by shuding** 2024-03-10 14:25 UTC
Labels: area: examples

**Comment by darekrossman** [comment] 2024-03-11 13:15
Though it may be related to https://github.com/vercel/next.js/issues/62860, this issue is not referring to Server Actions.
