### ISSUE TITLE
iPhone/iPad Safari renders transparent/blank components

### ISSUE THREAD

**Issue by dakairus** [vercel/next.js#10387] opened 2020-02-03 01:47 UTC
# Bug report

## Describe the bug

In a site made in Next js and after navigating through it for a couple of minutes some of the components in the screen turns to become blank/transparent. This only happens in Safari for IOS. Only way to fix it at the moment is to restart the next js server every several minutes.

## To Reproduce

1- Going to any page under https://app.thecurator.nz, go through some of the pages.
2- Minimise browser and come back few minutes later or refreshing the browser few times.

## Expected behavior

App should render normally with visible components

## System information
- iPhone & iPad IOS 11 to latest Safari

## Additional context
Thought it was related to react version or styled-components, but upgraded react and removed styled components at all still doesn't solve the issue.

**Comment by timneutkens** [comment] 2020-02-03 08:11
> 1- Going to any page under app.thecurator.nz, go through some of the pages.

There is only one page, a signup page.

**Comment by dakairus** [comment] 2020-02-03 08:33
yes, but if you signup and go through the internal pages or even if you jump in and out between the login page and signup you will end up been able to reproduce the bug. I'm waiting for the bug to happen again and add some extra content about it.

**Comment by Huespal** [comment] 2020-02-06 16:01
I have a similar issue. Coming from a redirect, page loads and components are in markup. 
Every browser available in market shows them except iOS Safari. 
iOS Safari shows the components blank. The html is there, visible from inspector, but the page is completely blank.
Reload 'solves' it.

**Comment by omgMath** [comment] 2020-04-16 14:41
I had a similar issue.
In my case there was a problem with the SSL connection, i.e. the user was able to end up at `http://<some-site>` instead of `https://<some-site>`. Solved it by forwarding `http` to `https`.

Not sure how your setup looks like, but the forwarding can be done in e.g. `Apache` or `nginx`.

Hope that helps.

**Comment by shlaikov** [comment] 2020-05-13 16:31
Did you manage to deal with this problem?

**Comment by omgMath** [comment] 2020-05-13 20:05
Yes, as I mentioned I resolved this issue by forwarding the `http` traffic to `https`.

As I'm not sure how your hosting/setup looks like, I can only refer to some resources.

With `nginx` - see e.g. [https://serverfault.com/questions/250476/how-to-force-or-redirect-to-ssl-in-nginx](here):
```
server {
    listen      80;
    server_name yoursite.com;
    return 301 https://$server_name$request_uri;
}
```

or with an Apache `.htaccess`, see e.g. [https://www.hostinger.com/tutorials/ssl/forcing-https](here):
```
RewriteEngine On 
RewriteCond %{HTTPS} off 
RewriteRule (.*) https://<your-domain>/$1 [R=301,L]
RewriteRule ^(.*)$ http://localhost:<your-port-running-nextjs>/$1 [L,P]
```

Please not that I'm not an expert on the whole sysadmin-stuff, so there might be better ways to do that.

It worked for me, not sure if it applies if you host it with `zeit`/`vercel`.

**Comment by Timer** [comment] 2020-09-03 02:34
Closing as no reproduction provided.

**Closed by Timer** 2020-09-03 02:34 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
