### ISSUE TITLE
with-mobx-state-tree-typescript ssr&ssg doesn't work

### ISSUE THREAD

**Issue by kchjxxgh** [vercel/next.js#27290] opened 2021-07-19 05:19 UTC
### What example does this report relate to?

with-mobx-state-tree-typescript

### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next dev

### Describe the Bug

after 'next dev', and visit 'http://localhost:3000/ssr'

The console report:
![image](https://user-images.githubusercontent.com/19234718/126106565-f1aa7f94-9ef3-4c91-bf1d-82e0a0775cdc.png)

### Expected Behavior

Expect SSR and SSG work correctly. 

In my env, 'with-mobx-state-tree' can work well. 

### To Reproduce

Just checkout 'with-mobx-state-tree-typescript' and run 'npm run dev'

**Comment by ThangHuuVu** [comment] 2021-07-20 11:11
Same issue for reference: https://github.com/vercel/next.js/issues/7322

**Comment by leerob** [comment] 2021-07-20 14:08
Fixed in the linked PR!

**Closed by leerob** 2021-07-20 14:08 UTC
Labels: template: bug, type: example

**Comment by balazsorban44** [comment] 2022-01-28 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
