### ISSUE TITLE
One of examples about image placeholder prop is not being shown

### ISSUE THREAD

**Issue by ffan0811** [vercel/next.js#34093] opened 2022-02-08 13:30 UTC
### What example does this report relate to?

nextjs image component

### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

12.22.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

The [Demo the color effect with blurDataURL prop](https://image-component.nextjs.gallery/color) example on [the nextjs document](https://nextjs.org/docs/api-reference/next/image#placeholder) returns 404

<img width="756" alt="image" src="https://user-images.githubusercontent.com/37147911/152996065-92a8e7f8-5c13-42aa-860c-69de66beb9fa.png">

On [the image component document](https://image-component.nextjs.gallery/), there are only 2 examples.
<img width="768" alt="image" src="https://user-images.githubusercontent.com/37147911/152996009-e0cfa409-fe71-4a5d-8ecf-d37ae561adda.png">

### Expected Behavior

If the third example is supposed to go on public (I forked the canary branch, ran it locally and things worked as expected), it should not redirect to the 404 page.

If the third example is not supposed to go on public, it should not be on the nextjs document.

### To Reproduce

Please check `Describe the Bug` field

**Comment by balazsorban44** [comment] 2022-02-08 18:48
Thanks, this seems to be a duplicate of #34013

**Closed by balazsorban44** 2022-02-08 18:48 UTC
Labels: template: bug
