### ISSUE TITLE
When server action is enabled, title property in metadata does not work.

### ISSUE THREAD

**Issue by zenato** [vercel/next.js#51286] opened 2023-06-14 10:55 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.6-canary.3
      eslint-config-next: 13.4.5
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/zenato/test-next-metadata-with-server-action

### To Reproduce

1. Open your browser to view the main page.
2. Make sure the page title is 'Main'.
3. Click the link to go to the login page.
4. Confirm that the title has changed to 'Login'.
5. Click the link again to go to the main page.
6. But the title doesn't change.

### Describe the Bug

After the title has been changed once, the title does not change any more even if the page is changed again. It works fine if you don't enable the `exeperimental.serverAction` flag in the next.config setting.

### Expected Behavior

Even if the `executive.serverAction` flag is enabled, metadata title should be reflected normally.

**Comment by JJooaa** [comment] 2023-06-14 11:09
I think its a duplicate of this https://github.com/vercel/next.js/issues/49409

**Comment by shuding** [comment] 2023-06-14 15:50
Yes this is a duplicate of #51286.

**Closed by shuding** 2023-06-14 15:50 UTC
Labels: template: bug, area: Metadata, area: app
