### ISSUE TITLE
Stale code being run on newer deployments

### ISSUE THREAD

**Issue by MitchEff** [vercel/next.js#26658] opened 2021-06-28 05:27 UTC
### What version of Next.js are you using?

10.0.1

### What version of Node.js are you using?

12.0.0

### What browser are you using?

Chrome & Safari

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Entirely stock-standard NextJS/Vercel builds are getting stale data until a hard refresh, meaning updates we're deploying aren't showing until caches are cleared/hard refresh. I'm aware the scripts are all hashed so their `Cache-Control: public, max-age=31536000, immutable` cache policies are okay, so I'd assume here the HTML itself is being cached. 

This may be another Vercel bug, but I thought I'd mention it here in case anyone's encountered similar and found a workaround? 

### Expected Behavior

Fresh versions of the updated sites should show after compilation is complete. 

### To Reproduce

- Update code (add a `console.log` just to check)
- Deploy to build system (Vercel in our case)
- Refresh website, check console - no log
- Hard-refresh website, check console - has log

**Comment by timneutkens** [comment] 2021-06-28 12:34
Hey! Can you open a new support request on https://vercel.com/support/request so that our customer success team can help investigate your issue, assuming you can provide a full reproduction then (e.g. deployment urls and such).

**Comment by MaximeBernard** [comment] 2021-07-07 08:18
@MitchEff We're having a very similar issue with our code and we're not using Vercel but GKE to deploy our app. Have you found any solution/root cause?

**Comment by MitchEff** [comment] 2021-07-07 13:25
Mmmnot really. The Vercel team have apparently elevated my ticket and are looking into it, but we've tried everything we can and can't get to the bottom of it ourselves. Wish I could be more helpful here!

**Comment by balazsorban44** [comment] 2021-12-23 22:02
@MitchEff I wonder if this is still an issue for you, or could we close this?

**Closed** 2022-01-13 13:35 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-02-13 00:14
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
