### ISSUE TITLE
Dynamic slugs fallback control seems buggy (getStaticPaths)

### ISSUE THREAD

**Issue by josias-r** [vercel/next.js#12024] opened 2020-04-19 14:29 UTC
Currently, there is this feature where u can create dynamic slugs with the following syntax `[...slug].js`. I noticed with a hierarchical structure like this:

pages:
- `[...slug1.js]`
- `subfolder/`
- - `[..slug2.js]`

When I access something inside the subfolder route that doesn't exist, it will fall back to the slug1 routes.
I have set `fallback` to `false` for my slug2 routes inside `getStaticPaths`.

The fallback property works fine when there is no other dynamic route catching it, but I think it would be nice to have control over fallbacks which have a higher level dynamic route.

I can see that it sometimes would make sense to have the current behaviour, so I'm suggesting to add a new property that controls the fallback behaviour when a higher level dynamic route is available, or change the fallback property from a boolean to an enum with something like: `disabled`, `dynamic`, `static`, where static would cause a 404 error when the **current route** won't return a valid path and dynamic would pass the logic further up to the next route.

**Comment by Timer** [comment] 2020-09-10 18:41
Thanks for opening an issue @josias-r! This is the expected behavior. I'll close this because there have only been two 👍s and we know of a lot of companies leveraging this behavior (including Vercel).

**Closed by Timer** 2020-09-10 18:41 UTC

**Comment by balazsorban44** [comment] 2022-01-29 13:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
