### ISSUE TITLE
Docs: Deduping and caching

### ISSUE THREAD

**Issue by gmoniava** [vercel/next.js#52069] opened 2023-07-01 09:13 UTC
### What is the improvement or update you wish to see?

In the docs [here](https://nextjs.org/docs/app/building-your-application/data-fetching#automatic-fetch-request-deduping), it says:

> On the server, the **cache lasts the lifetime of a server request** until the rendering process completes.

In this [section ](https://nextjs.org/docs/app/building-your-application/data-fetching#static-and-dynamic-data-fetching) then afterwards, it says:

> By default, Next.js automatically does static fetches. This means that the data will be fetched at build time, **cached, and reused on each request**

Initially these two paragraphs were bit confusing because they both mention "cache", I thought they were talking about same cache, but it seems they are referring to different caches, because one has lifetime of server request and other can be reused on each request. Would be nice to make it more clear.

Also would be nice if docs better explain the difference between deduping and caching.

### Is there any context that might help us understand?

N/a

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching

<sub>[DX-1760](https://linear.app/vercel/issue/DX-1760/docs-deduping-and-caching)</sub>

**Comment by koichik** [comment] 2023-07-10 10:23
I agree.

The Next.js cache mechanism has two layers.

* Upper layer: Shared cache between incoming requests provided by Next.js.
* Lower layer: Non-shared cache within incoming requests provided by React.

Passing `cache: "no-store"` to `fetch()` will skip Next.js' cache, but React will deduplicate it.
On the other hand, the POST method is cached by Next.js, but React does not deduplicate it

There is a big difference between these two layers and if not understood correctly we will be surprised by the data fetching behavior.

Hopefully the documentation will help us understand the concept of Next.js caching correctly!

**Comment by gmoniava** [comment] 2023-07-10 11:50
@koichik hm actually the first quote is from section about [deduping](https://nextjs.org/docs/app/building-your-application/data-fetching#automatic-fetch-request-deduping), so I think the first quote refers to the **temporary cache for deduping**, which decides which requests to dedupe, no? 

I was aware there was React cache too, but I think that is not the one mentioned in my quotes, I think you use it if you don't need fetch. 

But yeah in any case if there is some interaction between those layers (react and nextjs) which is not covered in docs, that should also be explained.

**Comment by koichik** [comment] 2023-07-10 14:07
@gmoniava The **temporary cache for deduping** is provided by React not Next.js itself, because Next.js provides shared persistent cache. 

The temporary cache provided by React that I mean is **not** the `cache()` API described [here](https://nextjs.org/docs/app/building-your-application/data-fetching/caching#react-cache).
Below is the React implementation of `fetch()` used under Next.js.
https://github.com/facebook/react/blob/main/packages/react/src/ReactFetch.js

**Comment by gmoniava** [comment] 2023-07-10 15:14
@koichik so who does deduping, react or nextjs? When is the fetch function to which you linked above used? This is all getting more confusing. Do you mind if we tag maintainers maybe they can shed some light? @leerob @delbaoliveira

**Comment by koichik** [comment] 2023-07-10 16:18
@gmoniava The fetch we call is the Next.js one. If its shared persistent cache is not hit, Next.js will call React's. If React's temporary cache is not hit, it will call the original (native) fetch.
This is what I meant by the two-tier cache in my first comment.

And which one will dedupe depends on the conditions:
```
// dedupe by Next.js (actually, it's not just dedupe, the request is 0 or 1 time)
fetch(url);
fetch(url);

//dedupe by React (one request)
fetch(url, { cache: "no-store" });
fetch(url, { cache: "no-store" });

// not dedupe in either (two requests)
fetch(url, { method: "POST", cache: "no-store" });
fetch(url, { method: "POST", cache: "no-store" });
```

It would be nice if the documentation explained why.

**Comment by gmoniava** [comment] 2023-07-10 16:41
@koichik If shared persistent cache is hit, does this mean deduplication may still happen by Nextjs?

**Anyway, I feel all this stuff should be explained in the docs, don't you think?**

Also here:

> // dedupe by Next.js (actually, it's not just dedupe, the request is 0 or 1 time)

What do you mean "not just dedupe, the request is 0 or 1 time"? Doesn't dedupe usually mean 0 or 1 time?

And here:

> fetch(url, { method: "POST", cache: "no-store" });

Do docs mention why this is not deduped? Is it the POST mentioned [here](https://nextjs.org/docs/app/building-your-application/data-fetching/caching#fetch) (see bullet points)?

**Comment by gmoniava** [comment] 2023-07-10 18:19
> I think that the point is "during a rendering pass". If only requests during rendering are deduplicated, then a request will occur at least once (actually, the second example is.).
> However, because the Next.js' cache is _shared and persistent_, it can be hit by another rendering (i.e. an incoming request from the browser) even by a different user. So a request may not occur during one rendering.

This paragraph is a little bit confusing to me. By Nextj's _shared and persistent_ cache you mean the cache which is used for _static_ data right? But that is a _different_ cache mechanism as compared to the cache used for _deduplication_ no? And in my question I was referring to deduplication (when you wrote "not just dedupe, the request is 0 or 1 time")


> In this last case, because "no-store" is specified, Next.js does not use the cache (documented) and calls React's fetch.

In previous comment I just wanted to show you that at some places Nextjs [docs ](https://nextjs.org/docs/app/building-your-application/data-fetching/caching#fetch) mention not deduplicating POST requests (but not sure if this is related to your comment):

> Requests are **not** cached if:
> Dynamic methods (next/headers, export const POST, or similar) are used and the fetch is a POST request (or uses Authorization or cookie headers)

**Comment by koichik** [comment] 2023-07-11 00:44
@gmoniava 
> This paragraph is a little bit confusing to me. 

Haha, this is the reason why I'm commenting on this issue.
Actually, Next.js uses the term "dedupe" to include static data hitting its shared persistent cache.
For example, your previous Issue (#52077) refers to the [docs](https://nextjs.org/docs/app/building-your-application/data-fetching/caching#post-requests-and-cache):
> POST requests are automatically deduplicated when using fetch

and, @SonMooSans's [comment](https://github.com/vercel/next.js/issues/52077#issuecomment-1616678319):
> The first tip was wrong, `POST` requests are automatically deduplicated (I've tested).

They use the term "deduplicated", but actual implementation just hits the Next.js' shared persistent cache.

> By Nextj's *shared and persistent* cache you mean the cache which is used for *static* data right? But that is a *different cache mechanism* as compared to the cache used for *deduplication* no? Caching and deduplication are different mechanisms no? Caching is for reusing already fetched data, deduplication is to prevent unneeded requests, no?

You are right! Thanks for clarifying what I wanted to say in my first comment. 
So, I want Next.js docs to make a clear distinction between deduping and caching, that's the exact title of this issue.

Thus, the previous example should be written like this:
```
// cached by Next.js (not dedupe, the request is 0 or 1 time)
fetch(url);
fetch(url);

//dedupe by React (one request)
fetch(url, { cache: "no-store" });
fetch(url, { cache: "no-store" });

// not cached and dedupe either (two requests)
fetch(url, { method: "POST", cache: "no-store" });
fetch(url, { method: "POST", cache: "no-store" });
```

**Comment by SonMooSans** [comment] 2023-07-11 07:38
Big thanks for mentioning it! I had made a mistake in the test, I didn't disable the cache when fetching data and actually, it's cached instead of deduplicated.

**Comment by koichik** [comment] 2023-07-11 09:33
@SonMooSans Thanks for clarifying! I hope the documentation will be more understandable.

BTW, I think part of the confusion is that React does not deduplicate the POST method. Does the Next.js team have plans to discuss POST method support with the React team?

**Comment by koichik** [comment] 2023-07-11 10:06
I think the behavior of `fetchCache: "auto"` (default) also makes it difficult to understand.

**Comment by gmoniava** [comment] 2023-07-11 11:37
@SonMooSans 
> After getting even deeper into the source code, I found myself more confused...

We should not be looking at the source code, all this should be explained in docs.

One more remark  is this from the docs:

> Requests are not cached if:
> 
> Dynamic methods (next/headers, export const POST, or similar) are used and the fetch is a POST request (or uses Authorization or cookie headers)


Is this clear to you? 

Just asking because initially in below [comment](https://github.com/vercel/next.js/issues/52077#issuecomment-1619957831)  I think you suggested it was clear:

> The definition here is very detailed: https://nextjs.org/docs/app/building-your-application/data-fetching/caching#fetch (as I mentioned in my https://github.com/vercel/next.js/pull/52100)

Now it seems you suggest otherwise. Ps. For me that docs quote isn't very well written either, I would at least add some examples.

**Comment by SonMooSans** [comment] 2023-07-11 13:19
I looked into the source code as I want to ensure what is the expected behavior, also as a hobby.

> Now it seems you suggest otherwise.

What did I suggest? As you said above, I agree that it is not enough detailed, as I found many points confusing for beginners. 

In this issue, we have multiple `cache` with different definitions. Although the docs had said React provides request deduping and Next.js extend options for caching, it's still confusing as people might skip or forgot this concept.

**Comment by gmoniava** [comment] 2023-07-11 13:31
@SonMooSans 

> What did I suggest? 

In _current_ issue you mentioned that quote from docs confused you, but [here](https://github.com/vercel/next.js/issues/52077#issuecomment-1619957831) :

> The definition here is very detailed: https://nextjs.org/docs/app/building-your-application/data-fetching/caching#fetch (as I mentioned in my https://github.com/vercel/next.js/pull/52100)

Seemed you were happy with the docs (you said "The definition here is very detailed").

Anyway my intent wasn't to offend you, I just highlighted this difference. No big deal.

We all agree all we discussed in this issue needs to be addressed in the docs. Let's wait and hope someone from Nextjs team chimes in.

**Comment by SonMooSans** [comment] 2023-07-11 13:59
Oops well, I'm not saying that definition is confusing (it listed every rule), but about deduping and caching. Sorry for my poor expressive skills...

I think the main issue is that they are mentioning the same thing in multiple places. For example, they mentioned [Dynamic Data Fetching](https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic-rendering#dynamic-data-fetching) in the Rendering section, but the same thing already exists [here](https://nextjs.org/docs/app/building-your-application/data-fetching#static-and-dynamic-data-fetching) in the "Data Fetching" section. Sometimes they may come with some differences or conflicts which can be misleading.

Anyway, that's kinda out of topic. At least I think some issues can be fixed by making a contribution to the docs as the core team might be busy.

**Comment by gmoniava** [comment] 2023-07-11 14:27
@SonMooSans 

> At least I think some issues can be fixed by making a contribution to the docs as the core team might be busy

We can make minor contributions but docs should be written be  someone who has thorough understanding of the framework, and who can explain the concepts well. Currently as we are witnessing also in this issue Nextjs docs seem to fail to explain some important concepts well. That's why I hope someone sees this issue and takes things more seriously.

Take react docs as example (react.dev), they are mostly written very well. 

.

**Comment by delbaoliveira** [comment] 2023-07-12 16:23
Hey there! 

Thanks for sharing the things you're confused about, it's helpful. The docs were written quite early on when we didn't have a caching solution specific to the App router and Server Components, much of what was documented reflected the current state at the time. Things have changed significantly since then. 

We're working on a [PR to document the caching mechanisms](https://github.com/vercel/next.js/pull/52514) and what APIs affect them. It's still rough right now, but feel free to leave feedback while I write it.

To answer your first question: 
 
>  I thought they were talking about same cache, but it seems they are referring to different caches, because one has lifetime of server request and other can be reused on each request. Would be nice to make it more clear.

Yes, they are different caches.

**Request deduplication** uses a temporary cache that lasts the lifetime of the request-response lifecycle (or render pass). Its purpose is to prevent multiple calls to a data store for the same data. 

The reason why we have this in place is that you can now fetch data in any component, and there may be cases where you make the same request more than once. So, by deduplicating data requests, only one request is made to the data store, and the result is cached and reused for the other data requests. 

You can almost think of it as a replacement for passing data down as props (or props drilling). You can fetch data in the component where you need to use it, and not worry about performance costs of making multiple fetch calls. 

The other is the **Next.js Data Cache**, which is a persistent data cache. It has a similar purpose to deduplication in the sense that it reduces the calls to the data store. The difference is that it's shared across users and deployments, so instead of having multiple users making requests to your data store, the requests hit the cache layer. 

____

One thing that would help alleviate the confusion would be clarifying the different types of caches. We often tend to think of cache as a coupled system that encompasses data + render output. 

Whereas with Server Components and the way now React renders on the server, we can be a lot more granular with what we cache, where and when. For example, we can cache the rendered components separately from the data, we can also play with the browser cache and server cache. It's all very exciting, and I hope can correctly convey how powerful this is 🤞🏼 

Hope it helps! Let us know if you have further questions!

**Comment by gmoniava** [comment] 2023-07-12 20:19
@delbaoliveira 

Ok, I will ask you few questions.

> The reason why we have this in place is that you can now fetch data in any component, and there may be cases where you make the same request more than once. So, by deduplicating data requests, only one request is made to the data store, and the result is cached and reused for the other data requests.

It seems the functionality you describe here is _very similar to functionality of caching_, no? **What is different here from caching, due to which this process is called deduplication**? And not caching? There must be something different right? Otherwise why introduce new terminology like deduplication, which will further confuse people. So what is the difference?

> The other is the Next.js Data Cache, which is a persistent data cache. 

Ok here we are talking about some standard cache mechanism but with a persistent life time. Is the fact that this is persistent somehow related with static data fetching? Or it is persistent also for dynamic data fetching?

**Comment by SonMooSans** [comment] 2023-07-14 02:42
Great observation!

In [here](https://github.com/vercel/next.js/blob/62aa2d221c6fbd943ad43a6010990bc31b78d281/packages/next/src/server/lib/patch-fetch.ts#L364), it only caches responses with 200 status code. That is absolutely a bug.

**Comment by gmoniava** [comment] 2023-07-17 16:16
@delbaoliveira 

Thanks for the response. I was going to suggest to use more familiar term instead of deduplication but I see the linked PR mentions similarity of deduplication with memoization, which is good. I will look into PR and let you know if I have further questions.

**Closed** 2023-08-04 21:38 UTC
Labels: template: documentation, linear: dx
