### ISSUE TITLE
Example with react-native-web is not working

### ISSUE THREAD

**Issue by DenisTis** [vercel/next.js#31293] opened 2021-11-11 09:21 UTC
### What version of Next.js are you using?

latest for 11.11.2021

### What version of Node.js are you using?

v16.9.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

npm run dev

### Describe the Bug

I just created new application from template and run "npm run dev" without doing any changes in the project :(

Following error was displayed:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
TypeError: Class constructor MyDocument cannot be invoked without 'new'
    at processChild (C:\Personal\NodeProjects\notes-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (C:\Personal\NodeProjects\notes-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Personal\NodeProjects\notes-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Personal\NodeProjects\notes-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (C:\Personal\NodeProjects\notes-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at Object.renderToHTML (C:\Personal\NodeProjects\notes-app\node_modules\next\dist\server\render.js:739:41)
    at async doRender (C:\Personal\NodeProjects\notes-app\node_modules\next\dist\server\next-server.js:1389:38)
    at async C:\Personal\NodeProjects\notes-app\node_modules\next\dist\server\next-server.js:1484:28
    at async C:\Personal\NodeProjects\notes-app\node_modules\next\dist\server\response-cache.js:63:36
error - TypeError: Class constructor MyDocument cannot be invoked without 'new'
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
TypeError: Class constructor MyDocument cannot be invoked without 'new'
    at processChild (C:\Personal\NodeProjects\notes-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (C:\Personal\NodeProjects\notes-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (C:\Personal\NodeProjects\notes-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (C:\Personal\NodeProjects\notes-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (C:\Personal\NodeProjects\notes-app\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at Object.renderToHTML (C:\Personal\NodeProjects\notes-app\node_modules\next\dist\server\render.js:739:41)
    at async doRender (C:\Personal\NodeProjects\notes-app\node_modules\next\dist\server\next-server.js:1389:38)
    at async C:\Personal\NodeProjects\notes-app\node_modules\next\dist\server\next-server.js:1484:28
    at async C:\Personal\NodeProjects\notes-app\node_modules\next\dist\server\response-cache.js:63:36
```

### Expected Behavior

npm run dev compiles the application

### To Reproduce

create new app from template and run "npm run dev"

**Comment by DenisTis** [comment] 2021-11-11 09:55
I forgot to mention. The error is displayed only when calling the url (opening the app in browser)

**Comment by huozhi** [comment] 2021-11-11 10:48
Hi can you try next@canary, should be fixed. Close as duplicated with #31104

**Closed by huozhi** 2021-11-11 10:48 UTC
Labels: template: bug

**Comment by DenisTis** [comment] 2021-11-11 11:55
Thank you! I confirm the solution.
After "npm i --save next@canary" the problem disappeared!

**Comment by abeaclark** [comment] 2021-11-12 21:57
Thanks @huozhi worked for me as well

**Comment by balazsorban44** [comment] 2022-01-27 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
