### ISSUE TITLE
client component useState not work as expected

### ISSUE THREAD

**Issue by wangsenyuan** [vercel/next.js#54869] opened 2023-09-01 05:56 UTC
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
    Binaries:
      Node: 17.3.0
      npm: 8.9.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, CLI (create-next-app)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/wangsenyuan/nextjs-demo.git

### To Reproduce

I just created a nextjs example from 
```
 npx create-next-app@latest

```
And I created a client component app/counter.js
```
"use client";

import { useState } from "react";

export default function Counter() {
  const [count, setCount] = useState(0);

  return (
    <div>
      <div>You clicked {count} times</div>
      <button onClick={() => setCount(count + 1)}>Click</button>
    </div>
  );
}

```

### Describe the Bug

Click button in counter.js does not increase the state

### Expected Behavior

Count increases when button is clicked

### How are you deploying your application? (if relevant)

next run dev

**Comment by emilshr** [comment] 2023-09-01 06:16
@wangsenyuan 
This seems to be working. I'm not sure what I'm missing. Could you elaborate a bit further?

**Comment by eben-vranken** [comment] 2023-09-01 06:16
Can confirm it also works for me

**Comment by wangsenyuan** [comment] 2023-09-01 06:52
> Can confirm it also works for me

You tried my demo, and the counter increases when button clicked? @eben-vranken

**Comment by eben-vranken** [comment] 2023-09-01 06:53
> > Can confirm it also works for me
> 
> You tried my demo, and the counter increases when button clicked? @eben-vranken

Yes! Can you describe what is not working for you?

**Comment by wangsenyuan** [comment] 2023-09-01 06:54
click the button, to increase the counter, but stays 0.

**Comment by eben-vranken** [comment] 2023-09-01 06:56
Mhm, can you walk me through your steps for starting your development environment? What browser are you using?

**Comment by wangsenyuan** [comment] 2023-09-01 06:56
I just upgrade node to v18.17.1, and re-install, it works. before it was v17.3.0

**Comment by wangsenyuan** [comment] 2023-09-01 06:57
> Mhm, can you walk me through your steps for starting your development environment? What browser are you using?

npm run dev 
yarn dev

**Comment by eben-vranken** [comment] 2023-09-01 06:57
Great! So this is fixed? :)

**Comment by wangsenyuan** [comment] 2023-09-01 06:57
yes. thanks for your help

**Comment by eben-vranken** [comment] 2023-09-01 06:59
Alright! Have a nice day :)

**Comment by eben-vranken** [comment] 2023-09-01 07:40
@wangsenyuan make sure to close this issue

**Comment by balazsorban44** [comment] 2023-09-01 09:41
Duplicate of #54328

It's indeed a Node.js upstream bug, and we recommend upgrading.

**Closed by balazsorban44** 2023-09-01 09:41 UTC
Labels: area: create-next-app, template: bug
