### ISSUE TITLE
Nextjs swc need update

### ISSUE THREAD

**Issue by melsiir** [vercel/next.js#33504] opened 2022-01-20 17:37 UTC
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: android                                 Arch: arm                                         Version: #1 SMP PREEMPT Thu Aug 13 12:14:18 CEST 2020                                             Binaries:                                           Node: 17.3.1                                      npm: 8.3.0                                        Yarn: N/A                                         pnpm: 6.24.3                                    Relevant packages:                                  next: 12.0.9-canary.4                             react: 17.0.2                                     react-dom: 17.0.2

### What version of Next.js are you using?

12.0.9-canary-4

### What version of Node.js are you using?

17.3.1

### What browser are you using?

Chrome

### What operating system are you using?

Android termux

### How are you deploying your application?

Not yet

### Describe the Bug

Swc has added support for Android armv7 but nextjs does not have that yet so please update nextjs with latest swc 

### Expected Behavior

Everything working should fine

### To Reproduce

Just create-next-app

**Comment by melsiir** [comment] 2022-01-20 18:36
And Here is it binary :

https://www.npmjs.com/package/@swc/core-android-arm-eabi

**Comment by melsiir** [comment] 2022-01-21 05:58
Does this request has been taken seriously ?
Or I should forget about it ?

**Comment by balazsorban44** [comment] 2022-01-21 11:08
Duplicate of #33518

**Closed by balazsorban44** 2022-01-21 11:08 UTC
Labels: template: bug
