### ISSUE TITLE
Docs: How to debug next/image src error?

### ISSUE THREAD

**Issue by Nefcanto** [vercel/next.js#38820] opened 2022-07-20 06:59 UTC
### What is the improvement or update you wish to see?

I'm using `next/image` and data comes from an API. Here's a sample:

```
<Image src={item.imageUrl} width={300} height={200} />
```

And I have used Next's image in many places. But if for any reason the API's src is undefined, I see this error:

```
Error: Image is missing required "src" property. Make sure you pass "src" in props to the `next/image` component. Received: {}
    at Image (webpack-internal:///../../site/node_modules/next/dist/client/image.js:157:19)
    at renderWithHooks (/site/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5471:16)
    at renderIndeterminateComponent (/site/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5544:15)
    at renderElement (/site/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5759:7)
    at renderNodeDestructive (/site/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5898:11)
    at renderNode (/site/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6030:12)
    at renderHostElement (/site/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5456:3)
    at renderElement (/site/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5765:5)
    at renderNodeDestructive (/site/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5898:11)
    at renderNode (/site/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6030:12)
error - ../../site/node_modules/next/dist/client/image.js (159:18) @ Image
```

Which is not useful at all. It does not give me information about my code at all. Which file? Which line?

So, how should we troubleshoot this? No hint is given in the docs.

### Is there any context that might help us understand?

You can add a section to the `next/image` page explaining your recommended ways to troubleshoot this error. For example:

#### Src is not provided
If you use `next/image` with API and the data is undefined, then specify this configuration in your `next.config.js` to enable verbose stack trace for troubleshooting:
```
{
     image: {
         verboseStackTrace: true
    }
}
```

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-reference/next/image

**Comment by balazsorban44** [comment] 2022-07-20 16:12
Duplicate of #23742

**Closed by balazsorban44** 2022-07-20 16:12 UTC
Labels: area: next/image, template: documentation
