### ISSUE TITLE
[9.5.3] When passing URL Object to Link - it creates incorrect URL

### ISSUE THREAD

**Issue by orian** [vercel/next.js#17588] opened 2020-10-03 14:53 UTC
# Bug report

## Describe the bug

When using a Link according to the documentation of [linking to dynamic paths](https://nextjs.org/docs/routing/introduction#linking-to-dynamic-paths) a resulting URL is broken.
Usage:
```
<Link href={{pathname: "/entry/[id]/page", query: {id: nextId}}}><a>Next page</a></Link>
```

The resulting href is: `http://localhost:3000/entry/[id]/page?id=1235` and should be:  `http://localhost:3000/entry/1235/page`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run `yarn dev` in your local copy of a repo: https://github.com/orian/nextjs-broken-link
2. Open browser http://localhost:3000/entry/1234/page

## Expected behavior

A correct URL: `/entry/1235/page`.

## System information

- OS: macOS, Linux
- Browser Chrome and Firefox.
- Version of Next.js: 9.5.3
- Version of Node.js: v14.10.1

**Comment by timneutkens** [comment] 2020-10-03 15:03
Duplicate of #17380

**Closed by timneutkens** 2020-10-03 15:03 UTC

**Comment by balazsorban44** [comment] 2022-01-29 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
