### ISSUE TITLE
Bug in the internationalization feature

### ISSUE THREAD

**Issue by luckasnix** [vercel/next.js#20212] opened 2020-12-15 20:33 UTC
# Bug report

## Describe the bug

When you navigate to a page that use query parameters and isn't the default locale, the query parameters are treated as "undefined".

## To Reproduce

1. Go to my repo or other repo that uses the internationalization feature (https://github.com/luckasnix/next-bug-report);
2. Switch to other locale (the bug don't appear in the default locale);
3. Navigate to a page that uses query parameters ("/pt-BR/articles?page=1") using the browser buttons (the bug don't appear when using the Next Link);
4. At first, the value of the query parameter is treated as "undefined".

## Expected behavior

The value of the query parameter must not be treated as "undefined". The behavior must be the same as the default locale.

## Screenshots

The console shows the value of the query parameter as "undefined".
![bug-in-the-console](https://user-images.githubusercontent.com/50385918/102269575-9a37e580-3efb-11eb-941b-bece3fe99c4e.png)

## System information

- OS: Windows 8.1
- Browser Google Chrome
- Version of Next.js: 10.0.3
- Version of Node.js: 14.3.0
- Deployment: next dev

## Additional context

No additional context.

**Comment by timneutkens** [comment] 2020-12-16 08:34
Can you check `next@canary`, a lot of i18n fixes were landed.

**Comment by luckasnix** [comment] 2020-12-18 12:40
I tested in the 10.0.4-canary.8 version and the same error occurred.

**Comment by TriStarGod** [comment] 2020-12-23 20:56
@luckasnix  Is it because you are using `getServerSideProps` instead of the newer methods?

**Closed** 2020-12-28 17:58 UTC
Labels: kind: bug, point: 1

**Comment by ijjk** [comment] 2020-12-28 23:17
Hi, this has been updated in `v10.0.5-canary.1` of Next.js, please upgrade and give it a try!

**Comment by luckasnix** [comment] 2020-12-28 23:40
Worked perfectly! No bugs!

**Comment by balazsorban44** [comment] 2022-01-29 00:11
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
