### ISSUE TITLE
No trailing slash if url contains a dot

### ISSUE THREAD

**Issue by fostyfost** [vercel/next.js#18164] opened 2020-10-23 09:32 UTC
# Bug report

## Describe the bug

No trailing slash if url contains a dot

## To Reproduce

1. Go to https://codesandbox.io/s/next-955-router-dot-bug-ih3cc
2. Click on 'Go to /page/with/dot.dot/'
3. See 'asPath is /page/with/dot.dot' (WITHOUT trailing slash)
4. Click on 'Go back'
5. Click on 'Go to /page/without/dotdot/'
6. See 'asPath is /page/without/dotdot/'

## Expected behavior

1. Go to https://codesandbox.io/s/next-955-router-dot-bug-ih3cc
2. Click on 'Go to /page/with/dot.dot/'
3. See 'asPath is /page/with/dot.dot/' (WITH trailing slash)
4. Click on 'Go back'
5. Click on 'Go to /page/without/dotdot/'
6. See 'asPath is /page/without/dotdot/'

**Comment by timneutkens** [comment] 2020-10-23 09:52
This is expected behavior given that static files should not be served with a trailing slash.

**Comment by fostyfost** [comment] 2020-10-23 10:07
It may be necessary to add a configuration parameter that will accept file extensions so that the router does not consider all dotted URLs as static files. What do you think?

**Comment by vitalybaev** [comment] 2020-10-23 10:09
But why this URL is treated as static file, since the URL matches a route and dots are technically allowed in URLs.

Dots don't indicate that it's static files, for example:
https://docs.spring.io/spring-framework/docs/3.0.x/reference/beans.html

**Comment by timneutkens** [comment] 2020-10-23 14:12
`/reference/beans.html` `beans.html` indicates a static html file

**Comment by vitalybaev** [comment] 2020-10-23 14:26
In this case yes. But look at `3.0.x`. In your opinion it would be static file in all cases.
`https://docs.spring.io/spring-framework/docs/3.0.x/`
But it's not true.
Dot in URL segment doesn't explicitly tell us about that it's a static file.

**Comment by Zauberfisch** [comment] 2020-10-24 21:03
I also disagree with @timneutkens. not every file with a `.` is a staic file, and therefore we should not redirect to non-`/` versions without checking if it is in fact a static file.

I've created a test app with just a `pages/[[...slug]].js` with `getServerSideProps` which handles all paths, and urls with `.` would still get redirected to non-`/`. (Though it seems only if it matches `/\.\w*$`):

- `/foo/bar/definately-not-a-static-file.foo.bar.xyz.yesreallynotafile/` redirect to `/foo/bar/definately-not-a-static-file.foo.bar.xyz.yesreallynotafile`
- `/foo/bar/definately-not-a-static-file.foo.bar.xyz.yes-really-not-a-file/` does NOT redirect

And further more, if I create 2 files `public/static-test-file.txt` and `public/static-test-file.test-txt`:
- `/static-test-file.txt/` redirects to `/static-test-file.txt`
- `/static-test-file.test-txt/` does NOT redirect, even though it is a static file

**Comment by Zauberfisch** [comment] 2020-10-25 08:09
It might also be worth adding an option to disable this type of redirecting all together. In case developers what to handle that themselves or have another web server in front of next that already does it for them.

**Comment by lachlanjc** [comment] 2021-01-01 19:26
Related: #16617

**Comment by timneutkens** [comment] 2021-01-03 14:05
Duplicate of #16617

**Closed by timneutkens** 2021-01-03 14:05 UTC

**Comment by Zauberfisch** [comment] 2021-04-18 02:40
@timneutkens I appreciate that you are closing the duplicate issues. But I feel like you closed all of them.

Has this been fixed? Or is there still an issue open for this bug that I am not aware of?

**Comment by balazsorban44** [comment] 2022-01-28 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
