### ISSUE TITLE
Please give us ability to revalidate or disable router cache.

### ISSUE THREAD

**Issue by grogou** [vercel/next.js#54514] opened 2023-08-24 15:05 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
on any env
```

### Which example does this report relate to?

with-next-routes

### Describe the Bug

There is no way to clear route cache or revalidate it. In my case it is important to show updated data immediately, but this strange behavior ( also please describe why you are using that much aggressive  caching ) broke whole app to work smooth.

Also if you don't want to do that and I can't understand why, please provide normal way to disable caching. 

Don't provide stupid router.refresh please. It is not normal to do that in Nextjs or React.

If it is normal behavior for you we can leave this project and do Wordpress if it is normal to refresh page. Also in Wordpress they have Interativity API to not do page refresh, guys comoon.

### Expected Behavior

GIVE US ABILITY TO DISABLE CACHE

### To Reproduce

just use LAST and best version of Next.

From my side maybe it is too much aggressive sorry but caching too)) 

It is not normal. There is a lot of issues, videos, topics and all that people want to know how to disable it.

Why it is default behavior? Give us ability to choose. 

Yes it is revalidating after 30 sec. but it is important in some projects to see updated data immediately. 

Thank you)

**Comment by ankitahuja1** [comment] 2023-08-26 05:40
I tried to add these two configs separately to my route files to avoid caching. It works fine on local build. But when deployed to vercel my route response gives 500 error. 

`export const revalidate = 0`
`export const dynamic = 'auto'`

**Comment by balazsorban44** [comment] 2023-08-27 12:58
This is not a bug report, so closing. About this topic, please read https://github.com/vercel/next.js/discussions/54075 and the associated issue to get more context.


Note: Please use the correct language in the future, and keep it constructive. Thanks

**Closed by balazsorban44** 2023-08-27 12:58 UTC
Labels: area: examples
