### ISSUE TITLE
Next13: Cannot read properties of undefined (reading '')

### ISSUE THREAD

**Issue by benny856694** [vercel/next.js#42033] opened 2022-10-28 03:44 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.17.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.1-canary.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Cannot read properties of undefined (reading '')

### Expected Behavior

should not throw this exception

### Link to reproduction

https://github.com/benny856694/next13-error

### To Reproduce

1. pnpm install
2. run dev
3. open "localhost:3000" page in browser, check the log in backend.

**Comment by james-elicx** [comment] 2022-10-28 07:11
I believe this is a duplicate of #41806

**Comment by theashishmaurya** [comment] 2022-10-28 07:12
I also run into this problem when building my next app. 
![image](https://user-images.githubusercontent.com/50199029/198525915-14aa28aa-5c3f-47eb-90a9-0599434ce555.png)

**Comment by benny856694** [comment] 2022-10-28 07:14
> I believe this is a duplicate of #41806

I noticed that issue is using 12.3.2-canary.43, not sure if it is Nextjs 13

**Comment by james-elicx** [comment] 2022-10-28 07:24
> > I believe this is a duplicate of #41806
> 
> I noticed that issue is using 12.3.2-canary.43, not sure if it is Nextjs 13

That was just the version number of the canary available at the time, it still had all the same features as nextjs13, I've bumped the canary number I use to the latest.

**Comment by Britnell** [comment] 2022-10-28 12:17
+1 I had the same error a couple of times

**Comment by arsaizdihar** [comment] 2022-10-28 14:25
I had the same issue

**Comment by balazsorban44** [comment] 2022-10-28 17:19
It does sound/look like a duplicate of #41806, but I could reproduce this one locally on my Linux machine, while the other I couldn't. So it seems related but maybe not the same issue.

**Comment by timneutkens** [comment] 2022-11-01 12:11
Closing as duplicate of https://github.com/vercel/next.js/issues/41806. I had a look at your reproduction and the problem is that you're rendering `<Head>` from `next/head` in the root layout, that should be `<head>`.

**Closed by timneutkens** 2022-11-01 12:11 UTC
Labels: kind: bug, area: app
