### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useContext')

### ISSUE THREAD

**Issue by official-MKV** [vercel/next.js#67697] opened 2024-07-12 11:02 UTC
### Link to the code that reproduces this issue

https://github.com/official-MKV/test-reproduction

### To Reproduce

1. npm install
2. next build

### Current vs. Expected behavior

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of null (reading 'useContext')
> Export encountered errors on following paths:
        /_error: /404
        /_error: /500
        /_not-found
        /favicon.ico/route: /favicon.ico
        /page: /

### Provide environment information

```bash
operating system: windows
node version: v20.9.0
next version: 14.2.5
react version: @18.3.1
```

### Which area(s) are affected? (Select all that apply)

Webpack

### Which stage(s) are affected? (Select all that apply)

next build (local), Vercel (Deployed)

### Additional context

I noticed the error on one of my previous projects after trying to `next build`, I searched for a solution online, went through everything, there is already an existing issue with this same title, but it was never closed and a conclusive solution was never given. 
1. I deleted my `package.json`, `node_modules`, cleared cache and re-installed
2. I slimmed down my dependencies
3. I set NODE_ENV=production, saw this solution on youtube 
4. I decided to start all over no dependency, no code, and run `next build` and the error was till there

**Comment by Netail** [comment] 2024-07-14 11:58
Reproduction code does not contain useContext usage

**Comment by vishaldhangar15** [comment] 2024-07-17 06:00
can you pls share the video of the exact issue ?

**Comment by vishaldhangar15** [comment] 2024-07-17 06:02
@official-MKV  pls share the video of the exact issue .

**Comment by d-ii-m-a** [comment] 2024-08-11 15:46
I encountered a similar issue.

Resolving the problem by downgrading to these specific versions:
```
    "next": "14.1.1",
    "react": "18.3.1",
    "react-dom": "18.3.1"
```

**Comment by lomocc** [comment] 2024-08-15 03:37
I found this error by upgrade from `14.2.4` to `14.2.5`.

**Comment by Iris-Ares** [comment] 2024-08-26 06:26
this work for me 
```
build --experimental-build-mode `compile`
```
from https://github.com/vercel/next.js/issues/63123#issuecomment-2162009023

**Comment by marcsaga** [comment] 2024-09-27 00:21
I had this error with 14.2.5, upgrading to the latest next version solved the issue.

**Comment by unstubbable** [comment] 2024-09-30 16:26
I can not reproduce the issue with the provided reproduction repo. Since @marcsaga mentioned that this is solved with the latest version, I'm closing it. Feel free to re-open with an updated repro if you still encounter the issue.

**Closed by unstubbable** 2024-09-30 16:26 UTC
Labels: bug, Webpack, linear: next
