### ISSUE TITLE
Allow scroll-to-top with shallow routing

### ISSUE THREAD

**Issue by stefanprobst** [vercel/next.js#21606] opened 2021-01-27 19:38 UTC
**What version of Next.js are you using?**

10.0.6-canary.9

**What version of Node.js are you using?**

14.15.4

**What browser are you using?**

Firefox 84

**What operating system are you using?**

Ubuntu 20.04

**How are you deploying your application?**

Vercel

**Describe the Bug**

Recently (i think 10.0.6-canary.8) the behavior for shallow routing was changed to *not* scroll-to-top anymore. While this makes sense as a default behavior, it should still be possible to force scrolling by providing `<Link shallow scroll>` or `router.push(path, undefined, { shallow: true, scroll: true )`.

**Expected Behavior**

`<Link shallow scroll>` and `router.push(path, undefined, { shallow: true, scroll: true )` should scroll to top.

**To Reproduce**

```js
// pages/index.js
import Link from "next/link";

export default function Home() {
  return (
    <main>
      <h1>Scroll down</h1>
      <div style={{ marginTop: "120vh", padding: "60px" }}>
        <Link href={{ query: { filter: "new" } }} shallow scroll>
          <a>Click me</a>
        </Link>
      </div>
    </main>
  );
}
```

**Comment by timneutkens** [comment] 2021-01-28 12:10
Feel free to send a PR.

**Comment by jigsawpieces** [comment] 2021-01-31 15:36
This functionality already exists but the official docs has not been updated yet. See https://github.com/vercel/next.js/pull/20606 for more information.

You can do:
``` 
router.push(path, path, { scroll: false })
```
to disable / enable auto scrolling.

**Comment by stefanprobst** [comment] 2021-01-31 16:02
For shallow routing, this is no longer true with v10.0.6. see https://github.com/vercel/next.js/pull/21437

**Comment by umutduyum** [comment] 2021-02-04 21:06
https://aka.ms/AAaykem
UPDATE 2/1/21: We are starting to roll out Cumulative Update Build 21301.1010 (KB5000626). This update does not include anything new and is designed to test our servicing pipeline.

Today we are releasing Windows 10 Insider Preview Build 21301 (RS_PRERELEASE) to Windows Insiders in the Dev Channel. This build is being offered to ALL Insiders in the Dev Channel. All Insiders in the Dev Channel will now receive the same build going forward.
What’s new in Build 21301
Improving the touch keyboard design
Important Insider Links
You can check out our Windows Insider Program documentation here, including a list of all the new features and updates released in builds so far. Are you not seeing any of the features listed for this build? Check your Windows Insider Settings to make sure you’re in the Dev Channel. Submit feedback here to let us know if things weren’t working the way you expected.
If you want a complete look at what build is in which Insider channel, head over to Flight Hub. Please note, there will be a slight delay between when a build is flighted and when Flight Hub is updated.
Before you update your machine, visit the Windows Insider Blog today to view full details on new features, general changes, improvements, known issues and much more!

**Comment by Alexn117** [comment] 2021-03-14 07:17
I experienced this today as well. Although there are cases where with shallow routing one might not want the page to scroll up, I think there are some where it's convenient. For example, using shallow routing to change pages via query string params (for frontend pagination without refetching data).

```
<Link href="/posts?page=2" shallow>
  <a>Naturally start new page at the top</a>
</Link>
```

The docs currently say that the default behavior is to obey scroll to top, but this is not happening with `shallow` set to `true` at the moment.

> The default behavior of `Link` is to scroll to the top of the page.

**Comment by luismramirezr** [comment] 2021-03-29 02:57
> I experienced this today as well. Although there are cases where with shallow routing one might not want the page to scroll up, I think there are some where it's convenient. For example, using shallow routing to change pages via query string params (for frontend pagination without refetching data).
> 
> ```
> <Link href="/posts?page=2" shallow>
>   <a>Naturally start new page at the top</a>
> </Link>
> ```
> 
> The docs currently say that the default behavior is to obey scroll to the top, but this is not happening with `shallow` set to `true` at the moment.
> 
> > The default behavior of `Link` is to scroll to the top of the page.

I have the same problem. I'm doing pagination based on query parameters and only the initial fetch is made with SSR. When the user changes a page, the query is updated and then the fetch is made on the client-side.

I would like to have the option to scroll to the top after with a shallow route push.

**Comment by chinanderm** [comment] 2021-05-11 15:16
> IMO the scroll option should just take precedence over opinionated default behavior when it's explicitly set.

Exactly.

**Comment by chrisneven** [comment] 2021-05-31 11:51
> Feel free to send a PR.

Hi @timneutkens, we'd really like to see this fixed and as you might've noticed I opened a pull request with regard to this issue. 

Alvast bedankt!

**Comment by timneutkens** [comment] 2021-06-02 09:22
Posted a reply here: https://github.com/vercel/next.js/pull/24888#pullrequestreview-673952968

**Closed** 2021-06-08 16:48 UTC
Labels: good first issue, kind: story

**Comment by balazsorban44** [comment] 2022-01-28 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
