### ISSUE TITLE
BasePath undefined from server if use next/dist/build

### ISSUE THREAD

**Issue by slider82** [vercel/next.js#16079] opened 2020-08-11 14:55 UTC
# Bug report

## Describe the bug

https://github.com/keystonejs/keystone/blob/master/packages/app-next/index.js

If use **next/dist/build** In this case, basePath will be empty on the server. Since **process.env .__ NEXT_ROUTER_BASEPATH** which is used in the router is not defined, because it is determined during assembly

**Comment by timneutkens** [comment] 2020-08-12 07:54
Doesn't seem like anything in particular of that file would affect basePath.

Going to close this issue as the issue template was removed and no reproduction is provided.

**Closed by timneutkens** 2020-08-12 07:54 UTC

**Comment by balazsorban44** [comment] 2022-01-29 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
