### ISSUE TITLE
Instrumentation.js gets called 3 times

### ISSUE THREAD

**Issue by john-james-gh** [vercel/next.js#51450] opened 2023-06-17 16:14 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.6
      eslint-config-next: 13.4.6
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

btw Windows version is 11 Home. Not sure why `next info` isn't able to identify that.

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

/

### To Reproduce

- Create `instrumentaion.js` as per the guide https://nextjs.org/docs/app/building-your-application/optimizing/instrumentation
- Add a `console.log` in the `register ` function
- Run `npm run build`
- Run `npm start`

There should be 2-3 `console.log`s, seemingly `register ` function gets called multiple times.

### Describe the Bug

`register` function of `instrumentation.js` gets called multiple times. 3 times in Azure Web Services. 2 times locally.

Azure App Service logs
![Screenshot 2023-06-17 170431](https://github.com/vercel/next.js/assets/57100733/a7bbf254-0ba4-4453-b0bb-19dd630ae1bc)

### Expected Behavior

`register` function should be called only once.

### Which browser are you using? (if relevant)

Chrome latest

### How are you deploying your application? (if relevant)

Azure App Services - Linux Single Container but the issue happens locally too.

<sub>[NEXT-1600](https://linear.app/vercel/issue/NEXT-1600/instrumentationjs-gets-called-3-times)</sub>

**Comment by john-james-gh** [comment] 2023-06-18 19:38
Even when using global variables to store the invoke condition, doesn't seem to work. Global variables seem to get complete wiped.

```
export async function register() {
  if (process.env.NEXT_RUNTIME === "nodejs") {
    // @ts-ignore
    console.log(global.shouldInvoke)

    // @ts-ignore
    if (!global.shouldInvoke) {
      // @ts-ignore
      global.shouldInvoke = true

      console.log("`register` function was invoked.")

      // @ts-ignore
      console.log(global.shouldInvoke)
    }
  }
}
```

That printed this

```
Listening on port 3000 url: http://localhost:3000
undefined
`register` function was invoked.
true
undefined
`register` function was invoked.
true
```

**Comment by 1148177968** [comment] 2023-06-29 12:33
I had some problems, too.
register is called twice in dev mode and not at all in production mode.
And when I only import or require server-side modules from within register, it still complains about server-side modules not being available (e.g. path and fs). I've already import it dynamically.

**Comment by emondpph** [comment] 2023-07-12 13:27
Having the same issue using the app router. It seems global variables are wiped, so I can't know if the instrumentation has been called yet

**Comment by neotrow** [comment] 2023-07-21 17:00
+1, having the same issue. 

For me it's without the app router but the traditional one.

**Comment by antonio-magicschool** [comment] 2023-08-30 07:43
+1, having the same issue.

**Comment by pawelkaliniakit** [comment] 2023-09-06 11:32
+1, having the same issue.

**Comment by huozhi** [comment] 2023-09-06 15:49
Hey I couldn't repro this based on the latest canary. is there a reproduction based on the latest canary that you can provide? Thanks

**Comment by YazaHealth** [comment] 2023-09-06 23:15
Unable to give a reproduction, however I am able to confirm still happening on latest canary(13.4.20-canary.18)

**Comment by danieljee** [comment] 2023-09-19 01:06
Having the same issue for nextjs: 13.4.13

**Comment by ganicus** [comment] 2023-10-04 17:50
Is there a way to add another hook that will be called AFTER bootstrapping and wiping out globals? Would love to see the ability to patch mods and set globals.

**Comment by matejfalat** [comment] 2023-10-18 09:35
@huozhi It runs twice if `middleware.ts` is used. Repro here https://codesandbox.io/p/sandbox/cool-darkness-dh2wgt

**Comment by MariusVerdier** [comment] 2023-11-28 07:29
@matejfalat did you find a way to bypass this behavior ? I face the exact same issue

**Comment by mdjfs** [comment] 2023-12-13 14:26
Having the same issue with next 14.0.3

**Comment by huozhi** [comment] 2023-12-13 16:38
@matejfalat 

From the [instrumentation docs](https://nextjs.org/docs/app/building-your-application/optimizing/instrumentation):

> We call register in all environments, so it's necessary to conditionally import any code that doesn't support both edge and nodejs. You can use the environment variable NEXT_RUNTIME to get the current environment. Importing an environment-specific code would look like this:
```js
export async function register() {
  if (process.env.NEXT_RUNTIME === 'nodejs') {
    await import('./instrumentation-node')
  }
 
  if (process.env.NEXT_RUNTIME === 'edge') {
    await import('./instrumentation-edge')
  }
}
```

Middleware is running based on edge runtime and page is on nodejs runtime, you could use above code to separate the instrumentation

**Comment by mdjfs** [comment] 2023-12-13 21:21
@huozhi Yes thats true but in the example 

> Even when using global variables to store the invoke condition, doesn't seem to work. Global variables seem to get completely wiped.
> 
> ```
> export async function register() {
>   if (process.env.NEXT_RUNTIME === "nodejs") {
> 
>     console.log(global.shouldInvoke)
> 
>     if (!global.shouldInvoke) {
> 
>       global.shouldInvoke = true
> 
>       console.log("`register` function was invoked.")
> 
>       console.log(global.shouldInvoke)
>     }
>   }
> }
> ```
> 
> That printed this
> 
> ```
> Listening on port 3000 url: http://localhost:3000
> undefined
> `register` function was invoked.
> true
> undefined
> `register` function was invoked.
> true
> ```

1. Global vars are cleaned randomly 
2. Instrumentation in nodejs runtime is called more than once

**Comment by thomasmillercf** [comment] 2023-12-21 23:32
@matejfalat  you are right the middleware seems to cause the second register for some reason

**Comment by khuezy** [comment] 2024-07-20 03:04
fwiw the `instrumentation.ts` only loads once in the latest 15.canary. The global variable getting wiped is still an issue, most likely due to the RSC stuff.

**Comment by theDanielJLewis** [comment] 2024-07-27 04:38
Has anyone figured this out?

**Comment by theDanielJLewis** [comment] 2024-07-27 04:42
It seems the problem might actually be that Next.js is running `next.config.js` twice.

If you replace `module.exports = nextConfig;` with the following:

```js
module.exports = async (phase) => {
  console.log("Starting phase:", phase);

  return nextConfig;
};
```

That "Starting phase" line will print as many times as the instrumentation runs on running or on build.

**Comment by huozhi** [comment] 2024-08-20 11:28
Closing this issue now since recently we had a few fixes on latest canary release to ensure it run only once.

**Closed by huozhi** 2024-08-20 11:28 UTC
Labels: bug, area: app, linear: next, Instrumentation
