### ISSUE TITLE
`await` breaks dead code elimination

### ISSUE THREAD

**Issue by ViliamKopecky** [vercel/next.js#28705] opened 2021-09-01 12:03 UTC
### What version of Next.js are you using?

11.1.2 (but works the same in 10)

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome (not important)

### What operating system are you using?

macOS

### How are you deploying your application?

vercel

### Describe the Bug

Using `await` inside condition disables it's dead code elimination support.

```ts
if (!process.browser) {
    console.log("this is correcly deleted from browser build");
}
```

```ts
if (!process.browser) {
    // this await breaks dead code elimination
    await new Promise((res) => res(null));
    console.log("this should not be available in browser build");
}
```

### Expected Behavior

Code inside the condition should be eliminated even if it contains `await`

### To Reproduce

Example repository: https://github.com/ViliamKopecky/bugreport-nextjs-await-breaks-dead-code-elimination

**Comment by ljosberinn** [comment] 2021-09-20 14:12
unrelated to nextjs; next doesnt do DCE

**Comment by ijjk** [comment] 2021-09-20 14:33
Hi, this is caused by the regenerator runtime in babel for handling async/await, you can see how this gets tranpsiled [here](https://babeljs.io/repl#?browsers=defaults&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=IYZwngdgxgBAZgV2gFwJYHsIwLbFRACgEoYBvAKBhlThgIEIAHAJ3SgFMQQA6AI1YDuIdsxIUqVAPSSYyABaoQMYALzIY_dsADWSgCZa9MKOgMx2AG1TZ8wNJkoSVamBHYCYABVY3hBAsycJAC8AHwwgSAEEAgWFkREANyOVCYQIOgW7NwW6ADmBABE8oowIHLosUYQ6Oq87MoAbngWwLxZ1Fj86EIiGgioFnqFSeQAkAC-5BNAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.15.7&externalPlugins=&assumptions=%7B%7D). 

@ljosberinn Next.js does attempt DCE using terser currently just noting that as this should normally work just has quirks with async/await. 

I'm gonna close this since it's not a Next.js issue per-se.

**Closed by ijjk** 2021-09-20 14:33 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
