### ISSUE TITLE
[v9.3] - app keeps recompiling when runnning on port 3000 

### ISSUE THREAD

**Issue by tafelito** [vercel/next.js#11271] opened 2020-03-22 06:10 UTC
# Bug report

## Describe the bug

I created a new app with the lates NextJS version 9.3 and as soon as I run it, every 30 secs or so, it tries to recompile showing this

```
[ event ] build page: /next/dist/pages/_error
[ wait ]  compiling ...
[ ready ] compiled successfully - ready on http://localhost:3000
[ event ] build page: /
[ wait ]  compiling ...
[ ready ] compiled successfully - ready on http://localhost:3000
```

Also there are a bunch of errors on browser console

![image](https://user-images.githubusercontent.com/5973652/77243561-bb281000-6be1-11ea-8e40-98d77b1be6a1.png)

## To Reproduce

create a new app with create-next-app and run it

## Expected behavior

HMR to only rebuild when there is an actual change 

## System information

- OS: macOS
- Browser: chrome
- Version of Next.js: [e.g. 9.3.1]

## Additional context

If you run the app on a different port other than 3000, the rebuild does not happen. but the `Invalid href...` still does

**Comment by cullophid** [comment] 2020-04-08 19:11
Im having the same issue. Im running typescript and node 9.3

**Comment by cullophid** [comment] 2020-04-09 08:43
Actually as far as I can tell the app will recompile no matter what:
```
import React, { useState } from "react";
const Page = () => {
  const [value, setValue] = useState("");
  return (
    <div>
      <input
        style={{ color: "blue" }}
        type="text"
        value={value}
        onChange={(e) => setValue(e.target.value)}
      />
    </div>
  );
};

export default Page;
```

a simple next app with only the page below, will still reload the app on every change.

**Comment by dooman87** [comment] 2020-05-15 10:51
Got the same issue after upgrading from 9.1. Tried 9.4 with the same result. Here's what might help with investigation. The issue is only occur when app is running in IFrame (Shopify app). If you open an app using an URL from IFrame then it's only reloads on changes.

When running in iframe then in HMR websocket messages I could see message `{invalid: true}` which is not appearing when running in separate tab.

**Comment by ijjk** [comment] 2020-09-10 20:44
I'm going to close this since a reproduction hasn't been provided. If you are still encountering this on the latest version of Next.js v9.5.3 please open a new issue providing a complete reproduction so we can investigate this further!

**Closed by ijjk** 2020-09-10 20:44 UTC

**Comment by balazsorban44** [comment] 2022-01-29 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
