### ISSUE TITLE
Suspense alongside Zustand leads to Runtime Error

### ISSUE THREAD

**Issue by sbboli** [vercel/next.js#47867] opened 2023-04-03 16:29 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.14.2
      npm: 8.13.2
      Yarn: 1.22.19
      pnpm: 7.28.0
    Relevant packages:
      next: 13.0.4
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://codesandbox.io/s/holy-shape-br1uqs?file=/pages/index.js

### To Reproduce

```Typescript
import { Suspense, useEffect } from 'react';
import { create } from 'zustand';

const useMyStore = create(() => {
  return { count: 420 };
});

export default function SuspenseAndZustand() {
  const store = useMyStore();

  useEffect(() => {
    // only crashes when setting the state here
    useMyStore.setState({ count: 9000 });
  }, []);

  return (
    <div>
      <p>store count: {store.count}</p>
      {/* works as expected when removing the suspense block */}
      <Suspense>Crash.</Suspense>
    </div>
  );
}
```

### Describe the Bug

Throws seemingly unrelated Runtime Error

Error: This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition.

### Expected Behavior

Should not throw Error.

**Comment by SmartMointy** [comment] 2023-04-22 21:44
Duplicate of #43920.

**Comment by websaid** [comment] 2023-05-04 21:47
Anyone found a work around? Using `startTransition` doesn't seem to do anything. :/

**Closed** 2023-05-10 13:20 UTC
Labels: template: bug
