### ISSUE TITLE
[DEBUG-error] Shifting breakpoints

### ISSUE THREAD

**Issue by mufteev** [vercel/next.js#30435] opened 2021-10-27 13:09 UTC
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

v14.18.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next dev

### Describe the Bug

When debugging in VS Code, breakpoints are shifted if template literals occur before these points along with a new line

Example - normal work in Next.js version 11.1.2:
```js
      try {
        const { id = null, record = null } = req.query;
        // const timestamp = new Date();

[*]-->  const t = `
          ok - ${id}
        `;

[*]-->  return res.end(t);
      } catch (error) {
        return res.end('bad'); 
      }
```
Example - bad work in Next.js version 12.0.1:
```js
      try {
        const { id = null, record = null } = req.query;
        // const timestamp = new Date();

[*]-->  const t = `
          ok - ${id}
        `;

        return res.end(t);
      } catch (error) {
[*]-->  return res.end('bad'); 
      }
```

![Untitled](https://user-images.githubusercontent.com/57632588/139070865-15ef4358-9e37-4204-bb3d-68997f277698.png)

It not visible here, but in my project the debugger captures the <ins>**_error_**</ins> variable from catch scope.

A similar problem occurred on the client side

### Expected Behavior

Breakpoints in their places

### To Reproduce

Minimal reproduce on based template: [https://github.com/mufteev/BUG-debugging-with-new-line-in-template-literals](https://github.com/mufteev/BUG-debugging-with-new-line-in-template-literals)

Build:
```cmd
yarn install
```

Run:
```cmd
yarn dev
```

**Comment by meds** [comment] 2021-12-04 09:44
This is still an issue for me in 12.0.5 - one thing I find interesting, if I add a breakpoint to auth.ts (doesn't bind, etc): 

Then I click on the breakpoint in the debugger section:

![image](https://user-images.githubusercontent.com/2121021/144704954-75b78466-6929-40fe-90b3-04640d120520.png)

It sends me to another file with the same name but different icon - in this file all the breakpoints attach correctly and function as expected, but it's a transpiled version (I think?) of the original:
![image](https://user-images.githubusercontent.com/2121021/144704938-6dc6581e-264c-4848-bf32-b3752ccad0f7.png)

So I added a breakpoint at line 80 as you can see, which looks like this in the original file:

![image](https://user-images.githubusercontent.com/2121021/144704986-79a18386-4703-4a62-a30d-1a9be7ea3efe.png)

But line 80 in the transpiled file goes to:

![image](https://user-images.githubusercontent.com/2121021/144704997-7ece51c1-adfd-4bb3-9b8f-2abad9e8de7e.png)

You can see the original transpiled code from below - it's a bit funky and kind of annoying.

**Comment by phifa** [comment] 2021-12-15 14:22
I also have issues. Using the `launch.json` from here: https://nextjs.org/docs/advanced-features/debugging#debugging-with-vs-code. Nothing happens. Breakpoints are not binding. It is a TypeScript project, so I added `"sourceMap": true` to `tsconfig.json`. I also modified the `dev` script: `"dev": "NODE_OPTIONS='--inspect' next dev -p 3333",`.

**Comment by alexbu92** [comment] 2022-01-03 15:19
Same here using next@12.0.7. Can't debug serverside code like getStaticProps, just gives "unbound breakpoint".

**Comment by CMeeg** [comment] 2022-01-23 21:19
If you've come here from #31382 (like I did) I've had some success with getting server side debugging working on `next@12.0.8` (`getStaticProps` and API routes) in VS Code so I thought it might be helpful to add some notes here until the official approach is working.

* Added `--inspect` flag to `next dev` as [documented here](https://nextjs.org/docs/advanced-features/debugging#server-side-code)
  * I'm on Windows so also had to [add cross-env](https://nextjs.org/docs/advanced-features/debugging#debugging-on-windows)
* Added the `launch.json` configuration below
* `npm run dev` - make sure you see the `Debugger listening on...` message in the terminal before the server starts up
* Add breakpoint(s) in VS Code
* Hit F5 in VS Code (though make sure it's using the below `Node: attach` launch profile)
* Browse to / refresh the page / API route in your browser

That should hopefully see your breakpoints get hit.

`launch.json` profile is:

```
{
  "name": "Node: attach",
  "type": "node",
  "request": "attach",
  "skipFiles": ["<node_internals>/**"],
  "port": 9229
}
```

**Comment by frederictobiasc** [comment] 2022-02-24 11:42
Doesn't work for me on `next@12.1.0`

**Comment by zksward** [comment] 2022-03-04 17:49
I have no clue how this works but I was able to mostly follow what @CMeeg has documented, but I was still getting unbound breakpoints. I used some console logging in the file I wanted to inspect and the debug console in VS code included the message with a link out to the file. Clicking on that link out to the file I was able to correctly bind the breakpoints, but the file path doesn't actually exist. If it helps I'm also using next inside a monorepo, so the file I'm trying to bind to is in `/apps/web/pages/api/file.js` but the breakpoints only bind on a supposed `/pages/api/file.js`

**Comment by tianyingchun** [comment] 2022-03-07 07:07
what progress of this issue?

**Comment by jockjocko** [comment] 2022-04-12 19:12
I noticed the issue #31532 was closed as a duplicate of this ticket but this ticket only mentions template literals having an issue.
 
The issue #31532 talks about not being able to debug source at all which I'm also experiencing on next 12.1.4 which in my opinion is more critical.

The file path in the breakpoint inspector points at /pages for a breakpoint in _document.tsx when the debugger is attached clicking the breakpoint takes you to the transpiled version instead of the source file.

Can't debug any typescript source files.

Running on MacOS Monterey 12.3.1
Node: 17.8.0
Vscode: 1.66.2

**Comment by cassioseffrin** [comment] 2022-04-23 23:16
Same here using "next": "12.1.5". I cannot debug serverside in VSCode using the official docs from NextJS. The client side is ok.

**Comment by Brooooooklyn** [comment] 2022-05-02 07:12
Seem to have been fixed in the latest canary version, I can see the breakpoints in their right place with `12.1.6-canary.16`

<img width="1726" alt="image" src="https://user-images.githubusercontent.com/3468483/166197674-9baa0334-ad10-4c30-87f3-f06181c05590.png">

**Comment by balazsorban44** [comment] 2022-05-02 09:52
Please give `canary` a try :point_up: and let us know!

**Closed by balazsorban44** 2022-05-02 09:52 UTC
Labels: kind: bug, area: SWC transforms, area: Debugger

**Comment by timneutkens** [comment] 2022-05-03 10:20
This is out on stable now.
