### ISSUE TITLE
react canary breaks build

### ISSUE THREAD

**Issue by Thinkscape** [vercel/next.js#61067] opened 2024-01-24 04:57 UTC
### Link to the code that reproduces this issue

https://github.com/roev-co/prerender-failure

### To Reproduce

1. `create-next-app`
2. Update `react` and `react-dom` to `canary`.
3. Run `next build`

### Current 

```
❯ next build
   ▲ Next.js 14.1.1-canary.7

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (0/4)  [    ]TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/Projects/prerender-failure/node_modules/styled-jsx/node_modules/react/cjs/react.production.min.js:24:118)
    at StyleRegistry (/Projects/prerender-failure/node_modules/styled-jsx/dist/index/index.js:450:30)
    at Wc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
    at Z (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
    at Z (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)

Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/Projects/prerender-failure/node_modules/styled-jsx/node_modules/react/cjs/react.production.min.js:24:118)
    at StyleRegistry (/Projects/prerender-failure/node_modules/styled-jsx/dist/index/index.js:450:30)
    at Wc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
    at Z (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
    at Z (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/Projects/prerender-failure/node_modules/styled-jsx/node_modules/react/cjs/react.production.min.js:24:118)
    at StyleRegistry (/Projects/prerender-failure/node_modules/styled-jsx/dist/index/index.js:450:30)
    at Wc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
    at Z (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
    at Z (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)

Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/Projects/prerender-failure/node_modules/styled-jsx/node_modules/react/cjs/react.production.min.js:24:118)
    at StyleRegistry (/Projects/prerender-failure/node_modules/styled-jsx/dist/index/index.js:450:30)
    at Wc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
    at Z (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
    at Z (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Projects/prerender-failure/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
 ✓ Generating static pages (4/4)

> Export encountered errors on following paths:
	/_error: /404
	/_error: /500
```

### Expected

Build succeeds.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:05 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6031
Binaries:
  Node: 21.2.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 8.3.1
Relevant Packages:
  next: 14.1.1-canary.7 // Latest available version is detected (14.1.1-canary.7).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, App Router, CLI (create-next-app), Module resolution (CJS / ESM, module resolving)

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

Tested on next `14.0.4` and `canary`.

**Comment by balazsorban44** [comment] 2024-02-27 22:12
I cannot reproduce this using other package managers, leading me to believe it has to do with Bun. Since Bun considers Node.js incompatibilities as bugs, you can try opening this issue with them.

What I can see that pnpm resolved `styled-jsx` with the installed `react@canary` version:

`styled-jsx: 5.1.1(react@18.3.0-canary-3bcd2de01-20240227)`

while Bun will resolve to `18.2.0` (`react@latest`).

Closing as this is not a Next.js issue.

**Closed by balazsorban44** 2024-02-27 22:12 UTC
Labels: area: create-next-app, template: bug, area: Module Resolution
