### ISSUE TITLE
`nft.json`s for edge functions are generated at wrong path

### ISSUE THREAD

**Issue by zhuhaow** [vercel/next.js#39858] opened 2022-08-23 09:51 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: N/A
      pnpm: 7.9.3
    Relevant packages:
      next: 12.2.6-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

The `nft.json` files for edge functions are generated under `.next/pages` instead of `.next/server/pages` like non-edge functions.

### Expected Behavior

NA

### Link to reproduction

NA

### To Reproduce

Put 

```
export const config = {
	runtime: 'experimental-edge',
};
```

in any page and `next build`. The `.next` folder will have the wrong result.

Setting runtime in `next.config.js` won't work as in issue #39800

**Comment by dunglas** [comment] 2022-08-31 16:58
I confirm the issue. This prevents using middlewares (which requires using the `experimental-edge` runtime to generate a response body) with the standalone output.

**Comment by balazsorban44** [comment] 2022-11-15 17:42
Closing as duplicate of #39275

**Closed by balazsorban44** 2022-11-15 17:42 UTC
Labels: template: bug
