### ISSUE TITLE
Next.js 11 issue with styled components

### ISSUE THREAD

**Issue by mike667** [vercel/next.js#26799] opened 2021-07-01 07:20 UTC
### What example does this report relate to?

with-styled-components

### What version of Next.js are you using?

11 (from installation section)

### What version of Node.js are you using?

15.14

### What browser are you using?

Chrome

### What operating system are you using?

macOS, Ubuntu 20.04

### How are you deploying your application?

Vercel, Docker

### Describe the Bug

I described bug in styled-components repo, please check here - https://github.com/styled-components/styled-components/issues/3522

### Expected Behavior

Work stably, display styles correctly.

### To Reproduce

Create a couple of next.js pages and try to navigate between them.

**Comment by Itshardtopickanusername** [comment] 2021-07-02 02:30
Same issue while using Material UI + next.js 11

I'm following the steps to inject and remove server side jss.
When the page first loads ("/"), and server side jss is removed, all the classes are missing. After clicking on a button that takes me to the SAME page "/" everything gets re hydrated properly.

this is a big issue...

**Comment by WeebHiroyuki** [comment] 2021-07-02 14:01
Same issue here with Material UI v4.11.4 and Next.js v11.0.1.

**Comment by Itshardtopickanusername** [comment] 2021-07-03 02:27
So I think issue is caused by next.config.js

I had:
```js
// next.config.js
module.exports = (phase, {defaultConfig}) => {
    return {
        reactStrictMode: true,
        distDir: 'build',
    }
}
```

commenting out reactStrictMode fixes this issue. Can anyone explain this?
```js
// next.config.js 
// removing reactStrictMode
module.exports = (phase, {defaultConfig}) => {
    return {
        // reactStrictMode: true,
        distDir: 'build',
    }
}
```

**Comment by fabb** [comment] 2021-07-03 13:30
we're not using `reactStrictMode` and still many styles cannot be loaded, and i get this in dev mode in the console:
```
Warning: Prop `css` did not match. Server: "\n                            font-weight: ,p => p.theme.fontWeights.regular,;\n                            font-size: ,p => p.theme.fontSizes.s,;\n                            color: ,#8e99ac,;\n                            margin-left: ,p => p.theme.space.s,px;\n                            align-self: flex-end;\n                            display: none;\n\n                            ,p => p.theme.media.desktop, {\n                                display: inline;\n                            }\n\n                            /* stylelint-disable */\n                            ,.sc-gtsrHT,:hover & {\n                                color: ,p => p.theme.colors.palette.primary.main,;\n                            }\n                            /* stylelint-enable */\n                        " Client: "\n                            font-weight: ,function (p) {\n            return p.theme.fontWeights.regular;\n          },;\n                            font-size: ,function (p) {\n            return p.theme.fontSizes.s;\n          },;\n                            color: ,#8e99ac,;\n                            margin-left: ,function (p) {\n            return p.theme.space.s;\n          },px;\n                            align-self: flex-end;\n                            display: none;\n\n                            ,function (p) {\n            return p.theme.media.desktop;\n          }, {\n                                display: inline;\n                            }\n\n                            /* stylelint-disable */\n                            ,.sc-gtsrHT,:hover & {\n                                color: ,function (p) {\n            return p.theme.colors.palette.primary.main;\n          },;\n                            }\n                            /* stylelint-enable */\n                        "
```

it worked fine in next.js 10.2.

**Comment by dohomi** [comment] 2021-07-09 06:33
@Itshardtopickanusername v4 of Material-UI does not work in strict mode. From v5 onwards strict mode is supported

**Comment by BowlingX** [comment] 2021-07-09 15:37
might be related: https://github.com/vercel/next.js/issues/26184

In my case I had problems / different style extractions if I use `import { Paper } from 'material-ui/core' or import Paper from 'material-ui/core/Paper'`

**Comment by fabb** [comment] 2021-07-21 14:45
I found that the issue is that the `babel-plugin-styled-components` seems no longer to work in next.js v11. It should transform the `css` prop to a `className` prop and create according css styles. But this seems no longer to work.

next.js 10.2:
![Screenshot 2021-07-21 at 16 35 10](https://user-images.githubusercontent.com/153960/126507288-14aab88d-f34f-4a7e-ac5b-bef3140c94d3.png)

next.js 11.0.1:
![Screenshot 2021-07-21 at 16 34 58](https://user-images.githubusercontent.com/153960/126507309-706c59d8-c6de-482e-865a-9debf56a0b34.png)

i'm using `next-plugin-custom-babel-config` and `next-compose-plugins` because of my monorepo setup, maybe that's no longer working with next.js v11. need to investigate further. happy for any pointers.

**Comment by theskillwithin** [comment] 2021-09-10 01:57
I don't like the idea of using `next-plugin-custom-babel-config`  because it says its no longer maintained.  any alternative solution?

**Comment by theskillwithin** [comment] 2021-09-16 23:52
```
{
  "presets": ["next/babel"],
  "plugins": [["babel-plugin-styled-components"]]
}
```
I think this helped

**Comment by HNazmul** [comment] 2021-11-14 17:08
I am using next.js 12. How can I solve this problem..

**Comment by theskillwithin** [comment] 2021-11-19 22:35
how can you do this in next 12 without adding a babelrc

**Comment by ybarakhovskyi** [comment] 2021-11-23 12:56
@HNazmul @theskillwithin
https://nextjs.org/docs/advanced-features/compiler#styled-components

**Comment by balazsorban44** [comment] 2022-06-20 14:21
As linked above, the integration should be much better now. I'm closing as this issue seems to be outdated. If you still have issues, please open a new issue with an updated reproduction.

**Closed by balazsorban44** 2022-06-20 14:21 UTC
Labels: area: examples, template: bug
