### ISSUE TITLE
Unable to use react-native-web due to cache conflicts 

### ISSUE THREAD

**Issue by alidcastano** [vercel/next.js#9939] opened 2020-01-04 06:17 UTC
# Bug report
When using react-native-web, when an external package wraps a component (i.e. View) or StyleSheet, those styles are not resolve during server rendering. Causing screen to flicker until styles are provided by client.

I believe part of the issue is that RNW relies on es6 imports for caching, and so perhaps Next.js is splitting the bundles in a way that creates two separate instances of one package.

## To Reproduce

here's a project I bootstrapped with expo cli to demonstrate this: https://github.com/alidlo/expo-next-ssr-cache-bug. setup instructions are in the readme.

## Expected behavior

A package can provide React Native components/stylesheet and they'll be available as part of same bundle/node_module instance while server rendering.

## System information

- OS:  Mac
- Version of Next.js: 9.1.7

## Additional context

From various attempts at bundling, only way I was able to get this working was by making my plugin expose it's on Document class (because I guess that helps resolve the bundle splitting issue).

**Comment by jeremy-coleman** [comment] 2020-01-04 21:14
It might be a webpack issue, see the comment in the resolutions field. I just happened to see this yesterday
‘’’  resolve: {
    alias: {
      // this isn't technically needed, since the default `vue` entry for bundlers
      // is a simple `export * from '@vue/runtime-dom`. However having this
      // extra re-export somehow causes webpack to always invalidate the module
      // on the first HMR update and causes the page to reload.
      'vue': '@vue/runtime-dom'
    }
‘’’
https://github.com/vuejs/vue-next-webpack-preview/blob/master/webpack.config.js

**Comment by balazsorban44** [comment] 2021-12-24 01:08
The reproduction is unavailable now (clicking the link resulted in 404), and it is therefore not viable to investigate the issue further. I'm going to close this, if you have a fresh reproduction, please give me a ping/re-open this issue.

**Closed by balazsorban44** 2021-12-24 01:08 UTC
Labels: good first issue

**Comment by balazsorban44** [comment] 2022-01-27 01:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
