### ISSUE TITLE
__dirname and __filename in imported files from /pages/api/ files  works not correctly

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [vercel/next.js#24594] opened 2021-04-29 08:22 UTC
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

next start

### Describe the Bug

/pages/api/graphql.ts
```ts
import handler from '../../backend/api.ts'
export default handler
```

backend/api.ts
```ts
console.log(__dirname) //  "/pages/api/"
console.log(__filename) //  ".next/server/pages/api/graphql.js"
```

### Expected Behavior

```ts
console.log(__dirname) //  "./backend/"
console.log(__filename) //  "./backend/api.js"
```

### To Reproduce

just try it

**Comment by timneutkens** [comment] 2021-04-29 09:34
Duplicate of #8251

**Closed by timneutkens** 2021-04-29 09:34 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
