### ISSUE TITLE
[Docs] create-next-app Link in Getting Started

### ISSUE THREAD

**Issue by colbyfayock** [vercel/next.js#16275] opened 2020-08-17 21:33 UTC
# Bug report

## Describe the bug

Broken link (404)

## To Reproduce

1. Getting Started > Setup https://nextjs.org/docs/getting-started#setup
2. Click on "create-next-app documentation"
3. See 404

## Expected behavior

Working page

## Screenshots

![image](https://user-images.githubusercontent.com/1045274/90446520-84cac000-e0af-11ea-863b-93a85252a062.png)

## System information

- OS: macOS
- Browser: Chrome
- Version of Next.js: ?
- Version of Node.js: ?

## Additional context

I'd be happy to put a PR in for this if that helps you at all - I just wasn't sure where that should point to, whether the [npmjs package](https://www.npmjs.com/package/create-next-app) or something else.

**Comment by adenekan41** [comment] 2020-08-18 01:32
@colbyfayock  This PR has fixed this issue, it should be live in no time 

PR: https://github.com/vercel/next.js/pull/16069

**Comment by colbyfayock** [comment] 2020-08-18 01:49
cool thanks!

**Comment by timneutkens** [comment] 2020-08-18 13:58
Closing as it was fixed already

**Closed by timneutkens** 2020-08-18 13:58 UTC

**Comment by monooso** [comment] 2020-08-23 18:38
@timneutkens This is still a problem on the live site.

**Comment by timneutkens** [comment] 2020-08-23 18:56
Correct, we release docs together with stable releases to ensure they're always correct with the latest stable.

**Comment by monooso** [comment] 2020-08-24 13:28
@timneutkens Ah, right. The "it should be live in no time" comment confused me. Is there a site for the "unreleased" docs, or should I just refer to the `canary` branch?

**Comment by balazsorban44** [comment] 2022-01-29 16:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
