### ISSUE TITLE
[i18n + rewrites + API Routes] Rewrite to API routes cause 404 when deploying to Vercel

### ISSUE THREAD

**Issue by dmitrykozyrenko** [vercel/next.js#23288] opened 2021-03-22 20:35 UTC
### What version of Next.js are you using?

10.0.9

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

Rewrite to API routes cause 404 when deploying to Vercel, in development all is working right.

### Expected Behavior

Rewrites should working correctly.

### To Reproduce

1. Create config:
`
i18n: {
  locales: ["en", "de", "fr"],
  defaultLocale: "en"
},
async rewrites() {
  return [
    {
      source: '/en/robots.txt',
      destination: '/api/robots',
      locale: false
    },
    {
      source: '/en/sitemap.xml',
      destination: '/api/sitemap',
      locale: false
    },
    {
      source: '/api/(.*)',
      destination: '/api/404'
    }
  ]
}
`
2. Then try to get `/robots.txt`, `/sitemap.xml` or `/api/missing-route` and u will see 404 error. All of them return Vercel 404 error.

**Comment by ijjk** [comment] 2021-04-28 02:49
This appears to be a duplicate of https://github.com/vercel/next.js/issues/23782, as documented here https://nextjs.org/docs/api-reference/next.config.js/rewrites#rewrites-with-i18n-support if you use `locale: false` the `destination` must include the `locale` to match correctly. 

I'm going to close this since it doesn't appear to be a bug, if you're still encountering problems with this please respond with additional info.

**Closed by ijjk** 2021-04-28 02:49 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
