### ISSUE TITLE
Nested paragraph tags not rendering on server

### ISSUE THREAD

**Issue by Ehesp** [vercel/next.js#14409] opened 2020-06-21 13:43 UTC
# Bug report

## Describe the bug

I came across this "bug" when building out a website using a headless CMS. I injected my CMS content into my application via `<p dangerouslySetInnerHTML={{ __html: externalHtml }} />`, however the HTML output from the CMS also contains a nested `<p`> tag.

When I load the page from the server, the content does not show, when I navigate to a page via client routing, it shows.

## To Reproduce

https://github.com/Ehesp/nextjs-html-rendering-issue

https://nextjs-html-rendering-issue.ehesp.vercel.app/

1. Load the page (no text shows)
2. Click the link to page 2, and then the link back to the root page
3. The nested text now shows

## Expected behavior

Technically nested `p` tags are incorrect and I sorted this by adding the HTML to an `article` tag, however since the output is different on server vs client it seems to be a bug?

## Screenshots

Server:
![image](https://user-images.githubusercontent.com/842078/85226070-6907ae00-b3cd-11ea-8807-ad38d55ecebb.png)

Client:
![image](https://user-images.githubusercontent.com/842078/85226073-6e64f880-b3cd-11ea-9f38-61bad8d83e28.png)

## System information

- OS: macOS
- Browser: chrome
- Version of Next.js: v9.4.4
- Version of Node.js: v12.9.1

**Comment by fabrizzioalco** [comment] 2020-06-24 16:02
I want to take a look at this

**Comment by patrick-mcdougle** [comment] 2020-06-28 22:01
Nested `<p>` isn't allowed in the [HTML specification](https://html.spec.whatwg.org/#the-p-element), so I'd argue this is won't fix. `<p>` elements can only contain phrasing content (which p itself is not).

**Comment by fabrizzioalco** [comment] 2020-06-28 23:46
@patrick-mcdougle HTML only have certain elements that can be nested. <p> is not one of those.

**Comment by fabrizzioalco** [comment] 2020-06-28 23:50
@patrick-mcdougle Thanks for the response and the help

**Comment by timneutkens** [comment] 2020-06-29 11:40
> Nested `<p>` isn't allowed in the [HTML specification](https://html.spec.whatwg.org/#the-p-element), so I'd argue this is won't fix. `<p>` elements can only contain phrasing content (which `<p>` itself is not).

This is correct, I think the issue can be closed.

**Comment by Ehesp** [comment] 2020-06-29 15:09
Yeah I understand it's not correct HTML, however wouldn't it make more sense for the output to be consistent (not render anything)?

**Comment by timneutkens** [comment] 2020-06-29 15:19
`<p><p>Hello World!!!</p></p>` It seems that it does output, just the browser does not display it

**Comment by Timer** [comment] 2020-06-29 19:05
This seems to be a no-fix from the Next.js side. Can you please file this upstream with the React team? This seems to be a difference between ReactDOM client and server.

**Closed by Timer** 2020-06-29 19:05 UTC
Labels: good first issue, type: upstream

**Comment by mattdell** [comment] 2020-07-21 12:44
Also ran into this. Very peculiar behavior. It should just render the output, even if it isn't valid markup.

Or at least provide a warning.

**Comment by balazsorban44** [comment] 2022-01-29 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
