### ISSUE TITLE
Blank page when using browser back button on SSR pages.

### ISSUE THREAD

**Issue by iMerica** [vercel/next.js#9989] opened 2020-01-08 04:31 UTC
## Summary
A dynamic SSR rendered page of mine is completely blank when users go back to it from another page.

## To Reproduce

1. Create a new dynamic web page in Next.js. E.g: A React component that is pre-populated with data from a database or cache.
2. In the footer of this page, add a Next.js `<Link/>` to the home page (which is a static, standard next.js page).
3. Deploy the site, visit this dynamic SSR page from step 1.
4. Click the link on the footer.
5. Click the back button or use a keyboard shortcut to "Go back".
6. Observe the page is completely empty. No JS errors occur in the console.

## Expected behavior

When I "Go back" in my browser, the page should display exactly as it did before.

## System information

- OS: macOS
- Browser (if applies) Chrome 79.0.3945.88
- Version of Next.js: ^9.1.6

## Additional context
Issue doesn't occur for static pages, only dynamic SSR pages.

**Comment by AlissonSteffens** [comment] 2020-04-19 20:24
Same problem here. Is there any workaround?

**Comment by nickmarlou** [comment] 2020-06-04 02:20
I have the same issue with dynamic pages. The back button works well when a user goes back to a static page (no [id].js, no ?param=param, etc). But it doesn't work when a user goes back from one dynamic page to another.

After clicking the back button I see the wrong state in `window.history`.

![image](https://user-images.githubusercontent.com/18831863/83707510-831b5f80-a65d-11ea-9920-b06f4be8c40e.png)

**Comment by Timer** [comment] 2020-06-09 17:53
Please provide a full demo so we can look into this.

**Comment by collegewap** [comment] 2020-07-26 08:34
@Timer 

Reproducible here:

Steps to replicate

- Goto https://next-route-issue.vercel.app/page1?foo=bar
- and then click on page2, you will be navigated to page2
- then click on the browser back button. URL will get updated, contents won't!

![image](https://user-images.githubusercontent.com/9767383/88474937-e1233f80-cf48-11ea-9299-cc8bd1e17d43.png)


**Note:** Replicable only when query paraments are present

Repo:
https://github.com/collegewap/next-route-issue

**Comment by chiqui3d** [comment] 2020-07-26 19:26
The same thing happens to me in production and development, the second time I return to the home page.

Although error occurs on the home page, the error seems to come from the dynamic routes. I put my [slug].js component, which is where the error comes from.

I followed Strapi's example from the example repository.

```js

import {getAllPostsWithSlug, getPost, getRecommendedPosts} from '@src/helpers/api'
import Head from 'next/head'
import markdownToHtml from '@src/helpers/markdownToHtml'
import HeaderTop from "@src/components/Layout/Header/HeaderTop";
import HeaderWithBackground from "@src/components/Layout/Header/HeaderWithBackground";
import Footer from "@src/components/Layout/Footer";
import PostContent from "@src/components/Post/Content";
import config from "@src/config";

export default function Post({post, recommendedPosts}) {

    return (
        <>
            <Head>
                <title>{post.title}</title>
            </Head>
            <HeaderTop/>
            <HeaderWithBackground/>
            <div className="main">
                <PostContent post={post} recommendedPosts={recommendedPosts}/>
            </div>
            <Footer/>
        </>
    )
}

export async function getStaticProps({params, preview = null}) {
    const post = await getPost(params.slug, preview);
    const recommendedPosts = await getRecommendedPosts(3);
    const content = await markdownToHtml(post?.[0].content || '');

    return {
        props: {
            preview,
            post: {
                ...post?.[0],
                content,
            },
            recommendedPosts
        },
    }
}

export async function getStaticPaths() {
    const allPosts = await getAllPostsWithSlug()
    return {
        paths: allPosts?.map((post) => `/blog/${post.slug}`) || [],
        fallback: false,
    }
}


```

**Comment by chiqui3d** [comment] 2020-07-26 19:28
I see many other similar issues that have been ignored 🤷‍♂️

**Comment by chiqui3d** [comment] 2020-07-27 01:36
The whole problem seems to come from the `next/link` component, If I use the "a" tag directly, everything works fine. Can't I use the `Link `component in statically generated pages? In the documentation I don't see anything mentioned about.

**Comment by drnachio** [comment] 2020-07-28 18:35
Similar Problem Here:

https://pokedex-tutorial.vercel.app/

You can check the code here:

https://github.com/BinPar/pokedex-tutorial

You can reproduce it:

- SSR the home page (https://pokedex-tutorial.vercel.app/)
- Scroll down
- Select a pokemon
- Click the back (at the bottom)
- The home page goes to the top
- Scroll down
- Select a pokemon
- Click the back (at the bottom)
- Now it works... every time except after the initial SSR

**Comment by ijjk** [comment] 2020-08-25 19:24
Hi, these sound related to https://github.com/vercel/next.js/issues/16028 which was fixed in https://github.com/vercel/next.js/pull/16477 and is available on the latest canary of Next.js `v9.5.3-canary.21`. Can you upgrade and see if the behavior is corrected for you?

**Comment by collegewap** [comment] 2020-08-26 04:49
@ijjk Issue got fixed for me
https://github.com/collegewap/next-route-issue

**Comment by Skarian** [comment] 2020-08-26 12:11
@ijjk Fixed over here :) Thanks!

**Comment by ijjk** [comment] 2020-08-26 15:03
Thanks for testing that @collegewap @Skarian! I'm going to close this since the related reports seem to be fixed. If anyone else is still encountering this please respond with additional details and we can investigate further.

**Closed by ijjk** 2020-08-26 15:03 UTC
Labels: kind: bug, point: 1

**Comment by drnachio** [comment] 2020-08-27 17:26
> Similar Problem Here:
> 
> https://pokedex-tutorial.vercel.app/
> 
> You can check the code here:
> 
> https://github.com/BinPar/pokedex-tutorial
> 
> You can reproduce it:
> 
> * SSR the home page (https://pokedex-tutorial.vercel.app/)
> * Scroll down
> * Select a pokemon
> * Click the back (at the bottom)
> * The home page goes to the top
> * Scroll down
> * Select a pokemon
> * Click the back (at the bottom)
> * Now it works... every time except after the initial SSR

In my case it is not fixded using:  "next": "^9.5.3-canary.21"

**Comment by ijjk** [comment] 2020-08-27 22:44
@drnachio this issue seems to be un-related to the reproduction steps you are describing as the content is loaded correctly when following the steps, it seems that yours is more related to [scroll restoration](https://github.com/vercel/next.js/issues/12530)

**Comment by samuanv** [comment] 2020-09-01 15:44
I had a similar issue: every page reload was displaying blank page. I had to hard reload and remove cache every time.
It is solved with `^9.5.3-canary.21` 👍

**Comment by xaun** [comment] 2020-11-26 00:40
I think I have a similar issue with SSG prod (and SSR developemnt)... Clicking a Next.js Link navigates, then trying to go back with the browser back button just takes me to the top of the screen, changes the URL in the browser, but does not navigate. This using latest 10.2. 

Using a normal link fixes the problem.

**Comment by hanayashiki** [comment] 2021-01-25 16:20
Got similar problem in `"next": "10.0.5"`

**Comment by Noob7** [comment] 2021-04-12 19:14
Hey i did a custom express server with styled-components and material ui. it seems to run on mac without any issues but on windows every page as fouc body{display:none} and resulting in all pages being blank. Curiously if you disable display none page reappears

**Comment by ugtdbt** [comment] 2021-06-07 06:25
same issue in "next": "10.0.9",

**Comment by javonclarke** [comment] 2021-06-23 05:09
I'm experiencing this issue on `NextJs - "^10.2.4-canary.0"` Been trying to wrap my head around the issue. I see so many issues on this topic. Some solutions are difficult to reason about because of implementation, etc

**Comment by SergioGeeK7** [comment] 2021-10-05 20:20
I'm also dealing with this issue next: `11.1.2`

**Comment by tylerharpool** [comment] 2021-11-09 19:52
This issue popped up for me today. 
next@canary

**Comment by hanayashiki** [comment] 2021-11-11 02:07
> The same in "next": "10.0.8"
> 
> @hanayashiki have you found any solutions?
> 
> Hmm... it's OK in Safari. But in Chrome I get blank page on every refresh or back/forward



It is an old issue. I think most of the time it ends up with wrong css configuration, like css-in-js without providing style tags from ssr.

**Comment by thebetterjort** [comment] 2021-11-11 04:37
Bad solution here, but it works. 

'rm -rf node_modules/'
'npm install next@latest'

This works for me.

**Comment by balazsorban44** [comment] 2022-01-27 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
