### ISSUE TITLE
React server mismatches: Prop `className` did not match.

### ISSUE THREAD

**Issue by voronianski** [vercel/next.js#11600] opened 2020-04-02 14:48 UTC
# Bug report

## Describe the bug

After upgrading from Next.js `9.0.5` to `9.2.2` we noticed that we are getting server mismatches for a lot of our components which never errored before. We also tried other versions (e.g. `9.1.x`, `9.2.x`, `9.3.x`) and all of them have the same problem.

## To Reproduce

Please use this repository with easy reproducible error - https://github.com/voronianski/nextjs-server-mismatch-bug

The code of the example component is open-source UI library and you can find it here - https://github.com/sumup-oss/circuit-ui/blob/canary/src/components/Hamburger/Hamburger.js

## Screenshots

![image](https://user-images.githubusercontent.com/974035/78262943-9bf28200-7501-11ea-9865-5738422b9bfc.png)

**Comment by mulholio** [comment] 2020-04-24 08:08
This sounds like an issue with emotion in your library to me.

Obviously it's a different library, but I know [styled components recommend including styled-components as a peer dependency for UI libraries](https://styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library) like the one you're using in this project.

Styled-components, also needs `babel-plugin-styled-components` and a modification of `_document.tsx` to ensure consistent hashing of classNames between environments. Is there something similar you need to do here?

Sorry that's not a solution but maybe some helpful notes.

**Comment by lucent1090** [comment] 2020-05-06 10:32
Hi @mulholio,

Thank you for the suggestion. I've tried the recommend from styled component's document in circuit-ui but the mismatch error still shows up. 

And I think emotion natures comes with SSR setting. Shouldn't need more setup to make the hash consistency. 

Please correct me if I miss anything here.
Thanks!!

**Comment by kkis** [comment] 2020-05-13 10:32
Hi @all,
same problem on my site. Since 3 days i already stuck on this problem.

Packages 

> "next": "9.3.6",
"@types/styled-components": "4.4.3",
"babel-plugin-styled-components": "1.10.7",
"styled-components": "4.4.1",
..


Node 12.14.1

I see that some guys had the same problems before (https://github.com/zeit/next.js/issues/3706) and so i tried to solve my problems tith the tips there. Nothing worked for me :(

**Fails**
- Remove  components where class is broken -> other component fails
- Update/Upgraded styled-components packages 
- Update/Upgraded all packages
- Change different options in Babel config ( used babel-plugin-styled-components with different settings) 
- try using nextjs dynamic import 
- changed also my _document like described here https://github.com/zeit/next.js/issues/3706#issuecomment-471891636

**Comment by barthicus** [comment] 2020-05-13 10:36
@kkis Try to upgrade next to 9.4.0
They fixed it already 💪

**Comment by kkis** [comment] 2020-05-13 10:43
**@barthicus** Same prob

**Comment by barthicus** [comment] 2020-05-13 10:53
@kkis Can you provide some codesandbox os smth similar so we can see the problem and try to fix it?
I'm not that familiar with next but I (or someone else here) can try to find a solution.

I'm using similar libs stack and this message is gone.
My packages:

``` 
"dependencies": {
    "@material-ui/core": "^4.9.14",
    "@material-ui/icons": "^4.9.1",
    "date-fns": "^2.13.0",
    "firebase": "^7.14.3",
    "next": "9.4.0",
    "notistack": "^0.9.13",
    "react": "^16.13.0",
    "react-animations": "^1.0.0",
    "react-dom": "^16.13.0",
    "react-firebase-hooks": "^2.1.1",
    "react-firebaseui": "^4.1.0",
    "styled-components": "^5.0.0"
  },
  "devDependencies": {
    "@types/firebase": "^3.2.1",
    "@types/node": "13.13.5",
    "@types/react": "16.9.35",
    "@types/react-dom": "16.9.8",
    "@types/styled-components": "5.1.0",
    "@typescript-eslint/eslint-plugin": "^2.33.0",
    "@typescript-eslint/parser": "^2.33.0",
    "babel-plugin-styled-components": "^1.10.0",
    "dotenv": "^8.2.0",
    "eslint": "^7.0.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-react": "^7.19.0",
    "eslint-plugin-react-hooks": "^4.0.1",
    "prettier": "^2.0.5",
    "typescript": "3.9.2"
  },
```

Ohh. Did you add this in _app.js/ts?

```
useEffect(() => {
    const jssStyles = document.querySelector('#jss-server-side')
    if (jssStyles && jssStyles.parentElement) {
      jssStyles.parentElement.removeChild(jssStyles)
    }
  }, [])
```

**Comment by kkis** [comment] 2020-05-13 11:02
@barthicus I also saw the solution with the useEffect(). The problem ist, that i have no server rendered code with "#jss-server-side" inside that can be removed...

I will see that i can provide some code on codesandbox.

**Comment by kkis** [comment] 2020-05-14 08:59
@barthicus 

At the end i found the solution -> **Dynamic imports !!**

```
import ...

// Fails :(
import ThemeProvider from '-/components/ThemeProvider'

// Work :)
const ThemeProvider = dynamic(() => import('-/components/ThemeProvider'))

const AppWrapper: FC = props => {
  const {children} = props
  const client = useApolloClient('contentful')
  const categories = useCategoriesLoader()

  // ....

  const {loading: appDataLoading, error, data: appData} = useQuery < AppData > (
    appQuery,
      {
        client,
        variables: {
          locale: APP_LOCALE,
          preview: contentfulPreview,
        },
      }
  )

  return (
    <ThemeProvider theme={getTheme()}>
      <Layout cmsContent={appData}>
        <LocationTracker>{children}</LocationTracker>
      </Layout>
    </ThemeProvider>
  )
}

class App extends NextApp<{
  apolloClients: ApolloClients
  cookies?: NextApiRequest['cookies']
  statusCode?: number
}> {
  render() {
    const {
      apolloClients,
      Component,
      cookies,
      pageProps,
      statusCode,
    } = this.props
    return (
      <ApolloClientProvider clients={apolloClients}>
          <AppWrapper>
            <Component statusCode={statusCode} {...pageProps} />
          </AppWrapper>
      </ApolloClientProvider>
    )
  }
}

```

**Comment by barthicus** [comment] 2020-05-14 09:22
@kkis Glad you made it!
Although I think we shouldn't use these kind of things to get rid of error messages.

I'm pretty sure this can be fixed implementing some other changes in _app/_doc files but I'm not that experienced to be 100% sure.

Happy coding 👍

**Comment by kkis** [comment] 2020-05-15 06:50
Did not work :(

**Comment by voronianski** [comment] 2020-05-15 10:17
@barthicus 
> @kkis Can you provide some codesandbox os smth similar so we can see the problem and try to fix it?

this repo with reproducible setup is available since bug is reported - https://github.com/voronianski/nextjs-server-mismatch-bug

I tried to upgrade to 9.4.0 but it didn't help.

What helped though is using the transpiled version of the component - https://github.com/voronianski/nextjs-server-mismatch-bug/pull/1

**Comment by kkis** [comment] 2020-05-18 08:59
Hello @voronianski , I break down the code.


```
import NextApp from 'next/app'

import styled from 'styled-components'
import React from "react";


const Wrapper = styled.div`
  min-height: 100vh;
`

class App extends NextApp<{}> {
  render() {
    return (
      <>
      <>No error when not using styled wrapper</>
      <Wrapper>Props. Classname error in console and dev env</Wrapper>
      </>
    )
  }
}

export default App

```

**Comment by kkis** [comment] 2020-05-26 07:05
@voronianski 
Here is an Codesandbox example. (https://codesandbox.io/s/next-typescript-app-f2k0y)

You can see that the error appear when i use custom theming. I would be really appreciate if someone knows how to solve the problem.

**Comment by rakeshshubhu** [comment] 2020-05-30 21:38
This appears for me as well. I've used the _document.js from next examples as well as updated babel rc. Next version is `9.4.0`

**Comment by KyorCode** [comment] 2020-06-16 19:21
Same problem here, trying to use `styled(ExternalComponent)` mismatches classes.
Next version 9.4.4
Styled-components version 5.1.1
babel-plugin-styled-components version 1.10.7

**Comment by jeffscottward** [comment] 2020-07-30 18:13
I am using 9.50 and ThemeUI and am also getting this.

No matter how many elements I remove -(as long as there is even just one element in the tree) - I get the error.

What is strange is that this error *doesn't* show up in Blink based browsers but *does* show up everywhere else like Safari, Firefox, etc

**Comment by jflayhart** [comment] 2020-08-02 02:50
> Same problem here, trying to use styled(ExternalComponent) mismatches classes.

Similar issue and @KyorCode's comment was my problem. I just had to convert all `const StyledComponent = styled(Component)` to be `const StyledComponent = styled.[html-element-goes-here]...`

**Comment by kolnogorov** [comment] 2020-10-06 13:40
9.5.2 is still present

**Comment by serkanz** [comment] 2020-10-13 10:41
Also 9.5.3 has the same bug

**Comment by dopt** [comment] 2020-10-25 08:45
9.5.5, bug still persist, it doesn't affect the application much but the client side always fire this warning.

**Comment by LuizHAP** [comment] 2020-10-28 02:39
Version 10 and the problem still persists

**Comment by gabsn** [comment] 2020-10-29 15:03
I can confirm that with next 10 😢

**Comment by siulca** [comment] 2020-11-05 14:57
This has been reported in April and still no fix in November?!

**Comment by timneutkens** [comment] 2020-11-05 15:02
> This has been reported in April and still no fix in November?!

This is not a bug in Next.js. You're likely using a css-in-js library that is not pre-rendering styles correctly (or not pre-rendering at all) which causes a hydration mismatch given the pre-rendered markup would not match the markup generated client-side.

**Comment by altschuler** [comment] 2020-11-07 16:04
For JSS this fixed it in my case https://medium.com/wesionary-team/implementing-react-jss-on-next-js-projects-7ceaee985cad

**Comment by Timer** [comment] 2020-11-07 17:48
Closing as it's a bug in your application and can be better solved in Discussions or on Discord!

**Closed by Timer** 2020-11-07 17:48 UTC
Labels: good first issue

**Comment by msreekm** [comment] 2020-11-16 07:15
for anyone still getting this error with Material-ui and styled components ,I have working code here- 
https://github.com/msreekm/nextjs-material-ui-styled-components-boilerplate

make sure to include the flush()
https://github.com/msreekm/nextjs-material-ui-styled-components-boilerplate/blob/1b807b11d13768fba4159a05b1962475a9ea8a74/_document.js#L30

**Comment by mysticaltech** [comment] 2020-11-26 16:35
Hey folks, in my case it was the `reactStrictMode: true` in next.conf.js that was causing the issue, when I removed it, it's gone! @Timer there is probably a bug here.

**Comment by timneutkens** [comment] 2020-11-27 11:16
> Hey folks, in my case it was the `reactStrictMode: true` flag in _next.conf.js_ that was causing the issue, when I removed it, it's gone! @Timer there is probably a bug here.

It's more likely you're using a library that is not strict mode compatible as strict mode re-executes renders multiple times to check for concurrent mode compatibility.

**Comment by mysticaltech** [comment] 2020-11-28 01:36
@timneutkens You are right I'm using plotly.js that is probably not strict mode compatible. So something like this could cause the client to render something and the server something else. I just don't understand. In my case the classes names were different. _Server: Mui-xyz-26, Client: Mui-xyz-27._

**Comment by christoffee** [comment] 2020-12-14 13:18
>This is not a bug in Next.js. You're likely using a css-in-js library that is not pre-rendering styles correctly (or not pre-rendering at all) which causes a hydration mismatch given the pre-rendered markup would not match the markup generated client-side.

How are component libraries, using styled components, meant to pre-render styles? Our set up is we have a component library using the `babel-plugin-styled-components` ( ['styled-components', { ssr: true, displayName:true }] )... and the same within the nextjs app... but we still get that mismatch classname warning.

`"styled-components": "^5.2.0"`
`"babel-plugin-styled-components": "^1.10.6"`
`"next": "10.0.1"`

**Comment by timneutkens** [comment] 2020-12-15 09:28
> > This is not a bug in Next.js. You're likely using a css-in-js library that is not pre-rendering styles correctly (or not pre-rendering at all) which causes a hydration mismatch given the pre-rendered markup would not match the markup generated client-side.
> 
> How are component libraries, using styled components, meant to pre-render styles? Our set up is we have a component library using the `babel-plugin-styled-components` ( ['styled-components', { ssr: true, displayName:true }] )... and the same within the nextjs app... but we still get that mismatch classname warning.
> 
> `"styled-components": "^5.2.0"`
> `"babel-plugin-styled-components": "^1.10.6"`
> `"next": "10.0.1"`

Make sure you set up `pages/_document` to pre-render the styled-components styles:
https://github.com/vercel/next.js/blob/canary/examples/with-styled-components/pages/_document.js

**Comment by fraanmarelli** [comment] 2020-12-18 16:04
> for anyone still getting this error with Material-ui and styled components ,I have working code here-
> https://github.com/msreekm/nextjs-material-ui-styled-components-boilerplate
> 
> make sure to include the flush()
> https://github.com/msreekm/nextjs-material-ui-styled-components-boilerplate/blob/3a33ef36d7a956e7da357ca9d02333ee43d72979/pages/_document.js#L27

this worked for me today :)

**Comment by machineghost** [comment] 2021-01-31 17:52
>Make sure you set up pages/_document to pre-render the styled-components styles:

I have tried using both a custom `_document.js` of https://github.com/vercel/next.js/blob/canary/examples/with-styled-components/pages/_document.js, and the one from step 6 of this article: https://dev.to/aprietof/nextjs--styled-components-the-really-simple-guide----101c

Neither one fixes the warning :(

**Comment by raptoria** [comment] 2021-02-13 02:40
+1

**Comment by jessetinell** [comment] 2021-03-04 13:03
I've ended up here for 3 different projects the past couple of months. This is what has silenced the error all 3 times:

1. Create the `.babelrc` file in your root folder
2. Add this: `
{
    "presets": [
        "next/babel"
    ],
    "plugins": [
        [
            "styled-components",
            {
                "ssr": true
            }
        ]
    ]
}
`



(hello to future me for the 4th project)

**Comment by olarra** [comment] 2021-03-12 16:00
It was driving me crazy! I spent so many day in this warning  and no of the solutions fixed it for me. I finally getting work with putting this in the .babelrc file

`{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    [
      "babel-plugin-styled-components",
      {
        "ssr": true,
        "minify": true,
        "transpileTemplateLiterals": true,
        "pure": true,
        "displayName": true,
        "preprocess": false
      }
    ]
}`

**Comment by tlkahn** [comment] 2021-03-20 01:41
Confirmed it works, at least for me.

I finally getting work putting this in the .babelrc file
> 
> ```
> {
>  "presets": [
>    "next/babel"
>  ],
>  "plugins": [
>    [
>      "babel-plugin-styled-components",
>      {
>        "ssr": true,
>        "minify": true,
>        "transpileTemplateLiterals": true,
>        "pure": true,
>        "displayName": true,
>        "preprocess": false
>      }
>    ]
>  ]
> }
> ```

**Comment by norbertbiro** [comment] 2021-03-22 12:10
> It was driving me crazy! I spent so many days in this warning and no of the solutions fixed it for me. I finally getting work putting this in the .babelrc file
> 
> ```
> {
>  "presets": [
>    "next/babel"
>  ],
>  "plugins": [
>    [
>      "babel-plugin-styled-components",
>      {
>        "ssr": true,
>        "minify": true,
>        "transpileTemplateLiterals": true,
>        "pure": true,
>        "displayName": true,
>        "preprocess": false
>      }
>    ]
>  ]
> }
> ```

I can also confirm that it works for me as well!

**Comment by xasopheno** [comment] 2021-03-29 23:25
Yes. That works for me as well. Thank you.

**Comment by amponsah** [comment] 2021-04-10 18:43
I'm not using style components and still have this issue!  I'm using Ant design, anyone else has this problem with ant design?

**Comment by globalblob** [comment] 2021-04-21 22:29
For what it's worth, setting the attribute programmatically seems to have cleared the issue in FF:

<button onClick={() => gotoPage(0)} disabled={!canPreviousPage}>

became this:

<button onClick={() => gotoPage(0)} {...({disabled:!canPreviousPage})}>

**Comment by AeShevch** [comment] 2021-04-28 12:23
> For what it's worth, setting the attribute programmatically seems to have cleared the issue in FF:
> 
> <button onClick={() => gotoPage(0)} disabled={!canPreviousPage}>
> 
> became this:
> 
> <button onClick={() => gotoPage(0)} {...({disabled:!canPreviousPage})}>

Did you manage to solve the problem? I also use antd

**Comment by globalblob** [comment] 2021-04-28 13:55
> 
> 
> > For what it's worth, setting the attribute programmatically seems to have cleared the issue in FF:
> > <button onClick={() => gotoPage(0)} disabled={!canPreviousPage}>
> > became this:
> > <button onClick={() => gotoPage(0)} {...({disabled:!canPreviousPage})}>
> 
> Did you manage to solve the problem? I also use antd

The code above did fix it for me, although I also did add babel and made changes to the _document (https://github.com/msreekm/nextjs-material-ui-styled-components-boilerplate/blob/3a33ef36d7a956e7da357ca9d02333ee43d72979/pages/_document.js#L27) as described in the discussion above.

**Comment by clementohNZ** [comment] 2021-05-07 13:27
If you're using material UI, this is a [great guide](https://dev.to/felixmohr/setting-up-a-blog-with-next-js-react-material-ui-and-typescript-2m6k) I found with explanations on why server-side styles need to be removed and how to do it.

After following this guide I never saw the issue again!

**Comment by Xin2050** [comment] 2021-05-10 16:04
> I've ended up here for 3 different projects the past couple of months. This is what has silenced the error all 3 times:
> 
> 1. Create the `.babelrc` file in your root folder
> 2. Add this: `{ "presets": [ "next/babel" ], "plugins": [ [ "styled-components", { "ssr": true } ] ] }`
> 
> (hello to future me for the 4th project)

This is total works for me, Thanks a lot!

**Comment by robertpiosik** [comment] 2021-06-10 19:16
> > I've ended up here for 3 different projects the past couple of months. This is what has silenced the error all 3 times:
> > 
> > 1. Create the `.babelrc` file in your root folder
> > 2. Add this: `{ "presets": [ "next/babel" ], "plugins": [ [ "styled-components", { "ssr": true } ] ] }`
> > 
> > (hello to future me for the 4th project)
> 
> This is total works for me, Thanks a lot!

It's not a proper solution. It breaks hot reload.

**Comment by amponsah** [comment] 2021-06-14 22:27
@globalblob 

Using AntDesign: The material ui link did not help me. Don't know it its works for styled-components!

The only way I managed to make it work was to wrap my component in next/dynamic.  After this all my className mismatched disappeared.

`import dynamic from "next/dynamic";

const Hosting = dynamic(() => import("./Hosting"), {
  ssr: false,
});

export default function HostingPage() {
  return <Hosting />
}
`

**Comment by JayBee007** [comment] 2021-07-03 09:21
@sheeraz1022 
Yes.

1. Starting the dev server, there is no error 
2. Change the props to style-components so new class is applied, gives an error about className mismatch on client and server
3. Further restarting of dev server doesnt solve the issue
4. And then again once in a while, the cycle repeats from point 1

But I have a monorepo, and am building styled-components using tsdx and providing custom .babelrc

**Comment by WebAiz** [comment] 2021-07-15 09:02
I had similar issue when server and client classNames differed with extra "logged" string, so dynamic import resolved the issue. Hope this helps

**Comment by AndrewMyint** [comment] 2021-07-18 17:20
> It was driving me crazy! I spent so many days in this warning and no of the solutions fixed it for me. I finally getting work putting this in the .babelrc file
> 
> ```
> {
>  "presets": [
>    "next/babel"
>  ],
>  "plugins": [
>    [
>      "babel-plugin-styled-components",
>      {
>        "ssr": true,
>        "minify": true,
>        "transpileTemplateLiterals": true,
>        "pure": true,
>        "displayName": true,
>        "preprocess": false
>      }
>    ]
>  ]
> }
> ```

This works for me as well, after deleting my .next folder.

**Comment by DevDaveJ** [comment] 2021-08-05 10:57
> 
> 
> If you're using material UI, this is a [great guide](https://dev.to/felixmohr/setting-up-a-blog-with-next-js-react-material-ui-and-typescript-2m6k) I found with explanations on why server-side styles need to be removed and how to do it.
> 
> After following this guide I never saw the issue again!

Im using nextjs + material-ui.
Not using typescript but my _document.js and _app.js are similar if not the same. The issue still occurs, but what worked for me was changing the import of the component causing the issue.

From:
import { Box } from '@material-ui/core';

To:
import Box from '@material-ui/core/Box';

**Comment by seanblonien** [comment] 2021-08-10 01:06
> Im using nextjs + material-ui.
> Not using typescript but my _document.js and _app.js are similar if not the same. The issue still occurs, but what worked for me was changing the import of the component causing the issue.
> 
> From:
> import { Box } from '@material-ui/core';
> 
> To:
> import Box from '@material-ui/core/Box';

Thank you @DevDaveJ! This fixed it for me. Do you know why this fixes it by chance? Do all MaterialUI imports have to be like this/why can't we import from '@material-ui/core` directly?

**Comment by DevDaveJ** [comment] 2021-08-10 01:33
> 
> 
> > Im using nextjs + material-ui.
> > Not using typescript but my _document.js and _app.js are similar if not the same. The issue still occurs, but what worked for me was changing the import of the component causing the issue.
> > From:
> > import { Box } from '@material-ui/core';
> > To:
> > import Box from '@material-ui/core/Box';
> 
> Thank you @DevDaveJ! This fixed it for me. Do you know why this fixes it by chance? Do all MaterialUI imports have to be like this/why can't we import from '@material-ui/core` directly?

Great! I don't know why the imports are different - they shouldn't be - but I would like to find out as well!

**Comment by jamesbluecrow** [comment] 2021-08-20 00:38
In case this helps, vercel has an example of wha the `.babelrc` file needs to look like for this error not to happen.

https://github.com/vercel/next.js/blob/canary/examples/with-styled-components/.babelrc

**Comment by handycode** [comment] 2021-09-24 08:06
> I've ended up here for 3 different projects the past couple of months. This is what has silenced the error all 3 times:
> 
> 1. Create the `.babelrc` file in your root folder
> 2. Add this: `{ "presets": [ "next/babel" ], "plugins": [ [ "styled-components", { "ssr": true } ] ] }`
> 
> (hello to future me for the 4th project)

That's work for me. Thanks!

**Comment by htgmanics** [comment] 2021-11-13 23:54
> I've ended up here for 3 different projects the past couple of months. This is what has silenced the error all 3 times:
> 
> 1. Create the `.babelrc` file in your root folder
> 2. Add this: `{ "presets": [ "next/babel" ], "plugins": [ [ "styled-components", { "ssr": true } ] ] }`
> 
> (hello to future me for the 4th project)

This works for me, Million Thanks!

**Comment by balazsorban44** [comment] 2022-01-27 09:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
