### ISSUE TITLE
I'm not here to judge vercel but nextjs 13 is UNUSABLE ON MAC.

### ISSUE THREAD

**Issue by Pnlvfx** [vercel/next.js#47920] opened 2023-04-04 16:33 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
no
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), CLI (create-next-app)

### Link to the code that reproduces this issue

no

### To Reproduce

no

### Describe the Bug

it's not my fault.

### Expected Behavior

no

**Comment by YIZHUANG** [comment] 2023-04-05 09:29
Wow, such negativity

**Comment by Cedar-81** [comment] 2023-04-05 14:14
I don't think this should be an approved issue, how can anyone help if you can't state the bug you are facing or how to reproduce it. I am sure you're not the only one on a mac using Nextjs, so please if you have an issue try state it clearly and with a non generic title. Thanks.

**Comment by YIZHUANG** [comment] 2023-04-05 17:34
Without the negativity, here is how i workaround the next13 limitation:

**Regarding the slow local compile time**

1. Do blind coding and deploy to preview to check out the changes
2. Or Work on two repos at the same time, one is with next12 after you are done making the changes, clone the changes to the one with nextjs 13
3. Move the files you don't plan to work on outside the repo and move them back when you're ready to make the deployment -> faster intellisense at least in vscode for me.

Others:
1. Downgrade to 13.2.3 (i think this version has less bugs and still has stream support in the api route in nodejs runtime when deploy to vercel)
2. For dynamic routing, use pages instead -> or change your api to use "post"
4. I18n, the support for pages structure doesn't seem to work anymore. Also don't know the workaround for this since i use the page structure still mostly
5. The window resize seems to be broken, every click now on mobile triggers a resize event, i had to fork the external libraries that have the resize event setup and disable those for now https://github.com/vercel/next.js/issues/47839

Besides these, i would say it's pretty stable, at least haven't found any issues so far in https://junia.ai/

**Comment by laneme** [comment] 2023-04-05 20:32
**Describe the bug:** its not my fault 

:rofl: 

I understand you may be pissed off about certain things, but that doesnt help identify anything

**Comment by ijjk** [comment] 2023-04-05 23:07
Going to close this as off topic, if you have specific reproduction or issues please open a proper issue with details to allow further investigation.

**Closed by ijjk** 2023-04-05 23:07 UTC
Labels: area: create-next-app, template: bug, area: app

**Comment by Pnlvfx** [comment] 2023-04-14 22:34
Sorry for my bad review, I was nervous for an error caused from a linked package and I cannot find anyway of fixing it, this was happening on 3 projects so I was really frustrated, now I've fixed it and everything is working like before if not better. Sorry again
