### ISSUE TITLE
Linting trips up when extending from `plugin:@typescript-eslint/recommended-requiring-type-checking`

### ISSUE THREAD

**Issue by Powell-v2** [vercel/next.js#26930] opened 2021-07-05 12:11 UTC
### What version of Next.js are you using?

^11.0.1

### What version of Node.js are you using?

v12.18.4

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04.1 LTS

### How are you deploying your application?

next start

### Describe the Bug

I'm trying to incorporate `@typescript-eslint/recommended-requiring-type-checking` into the ESLint config. Linting fails with the following error:

`Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.`

Here's my ESLint config:

```js
module.exports = {
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "next/core-web-vitals",
    "next",
    "prettier",
  ],
  overrides: [
    {
      files: ['**/*.ts?(x)'],
      parser: '@typescript-eslint/parser',
      parserOptions: {
        tsconfigRootDir: __dirname,
        project: ["./tsconfig.json"],
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
        warnOnUnsupportedTypeScriptVersion: true,
      },
    },
  ],
}
```

This might not be a bug, but rather an oversight on my part. Please advise - thanks in advance 🙏

### Expected Behavior

Linting doesn't throw the aforementioned error.

### To Reproduce

Run `next lint --fix` with the provided config within TS-enabled project.

**Comment by housseindjirdeh** [comment] 2021-07-14 16:41
@Powell-v2 Unfortunately this isn't an issue with Next.js but has to do with an issue regarding how you've configured `plugin:@typescript-eslint` along with a parser override. I reproduced this issue locally (thanks for the instructions) and the error remains even when I remove `next` and `next/core-web-vitals` from the config.

Tried to quickly debug and figure out what the core issue is, and I think it may have to do with `overrides`. Removing the overrides entirely seems to solve the issue but it'll definitely need more investigation (see #https://github.com/typescript-eslint/typescript-eslint/issues/2186).

Note that the [`next` configuration](https://github.com/vercel/next.js/blob/canary/packages/eslint-config-next/index.js#L37-L49) also includes an override for `.ts*` files to use `@typescript-eslint/parser`. If you're attempting to modify the parser configuration, I would suggest extending from the plugin instead to minimize the chance of conflicts and if you only want Next.js rules in your application and don't need the additional plugins provided by the config (`import`, `react`, `react-hooks`).

```diff
module.exports = {
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
-   "next/core-web-vitals",
-   "next",
+   "plugin:@next/next/recommended",
    "prettier",
  ],
```

Closing this issue since it isn't a Next.js issue, but I hope this all helps!

**Closed by housseindjirdeh** 2021-07-14 16:41 UTC
Labels: template: bug

**Comment by RyanClementsHax** [comment] 2021-10-30 00:11
Thanks for the work put in!

I believe it is possible to add type aware eslint rules in combination with next's eslint config by overriding next's eslint override to handle typescript files. The following config is a minimal example which allows one to enable `@typescript-eslint/no-floating-promises` which requires fancy parser configuration.

```json
{
  "extends": ["plugin:@typescript-eslint/recommended", "next/core-web-vitals"],
  "overrides": [
    {
      "files": ["**/*.ts?(x)"],
      "parserOptions": {
        "project": "./tsconfig.json"
      },
      "rules": {
        "@typescript-eslint/no-floating-promises": "error"
      }
    }
  ]
}
```
![image](https://user-images.githubusercontent.com/20916810/139512917-bd53ca63-13a2-4658-b9d1-164b27c01dee.png)
The versions I was using are as follows:
```json
{
    "devDependencies": {
        "@typescript-eslint/eslint-plugin": "^4.33.0",
        "@typescript-eslint/parser": "^4.33.0",
        "eslint": "^7.32.0",
        "eslint-config-next": "^12.0.1",
    }
}

**Comment by balazsorban44** [comment] 2022-01-27 13:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
