### ISSUE TITLE
Fast refresh errors in next 12.0.8

### ISSUE THREAD

**Issue by snax4a** [vercel/next.js#33256] opened 2022-01-13 12:00 UTC
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
    Binaries:
      Node: 14.17.6
      npm: 6.14.15
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Microsoft Edge dev

### What operating system are you using?

macOS Monterey v12.1

### How are you deploying your application?

Vercel

### Describe the Bug

After updating to next 12.0.8 im getting fast refresh error.

When editing my app with the dev server running I am randomly getting this error. It's not happening every time I edit a file and its not related to one file:

"About to perform a full refresh
Fast Refresh will perform a full reload when you edit a file that is imported by modules outside of the React rendering tree. It is also possible the parent component of the component you edited is a class component, which disables Fast Refresh. Fast Refresh requires at least one parent function component in your React tree.

You can find more information in the related Webpack error below:

```Cannot read properties of undefined (reading 'call')```
You can read more about Fast Refresh in our documentation."

### Expected Behavior

Fast refresh works correctly and no error is present

### To Reproduce
I created minimal reproduce repository here: https://github.com/snax4a/middleware-issue-demo
Just try to edit some file / add comments multiple times and hit save

The issue is related to middleware used in the project.
When I remove middleware there is no error

**Comment by balazsorban44** [comment] 2022-01-13 12:40
Hi, could you contact me via e-mail or on Twitter? (Info is on my GitHub profile)

**Comment by snax4a** [comment] 2022-01-13 12:55
> Hi, could you contact me via e-mail or on Twitter? (Info is on my GitHub profile)
> 
> Do note that the Fast Refresh error might not be new for your project, but is more prominent since `12.0.8`. (I believe previously it was only shown as a warning in the browser console)

I have sent you a message on twitter

**Comment by bmichotte** [comment] 2022-01-13 15:02
I've the same issue but the message is `originalFactory is undefined`

**Comment by balazsorban44** [comment] 2022-01-13 17:50
If anyone can create a reproduction, that would be super helpful!

**Comment by snax4a** [comment] 2022-01-13 18:25
I think I found what may be causing this issue.

In my project i am using middleware for all my pages.
Middleware code is following:
```tsx
import { NextRequest, NextResponse } from 'next/server'

export default function middleware(req: NextRequest) {
  const { pathname } = req.nextUrl

  if (pathname === '/') {
    return NextResponse.redirect('/dashboard')
  } else {
    return NextResponse.next()
  }
}
```

It's just a simple redirect to /dashboard page.

After removing this middleware I can no longer reproduce the fast refresh issue.

Crucial thing is that in the previous next.js versions 12.0.7 and lower this middleware was not working on Vercel, on the dev server it worked perfectly but on Vercel there was no redirection.

I have investigated and noticed that the problem was because i was using next-translate package and i was wrapping my next.config with nextTranslate() function.

This is how my next.config.js look:
```js
const nextTranslate = require('next-translate')

/** @type {import('next').NextConfig} */
const config = {
  reactStrictMode: true,
}

module.exports = nextTranslate(config)
```

When I removed nextTranslate from the config middleware on vercel was working on next v12.0.7

I was about to report this issue but then I saw next v12.0.8 version and saw that issue with middleware was fixed in this release.

In my opinion, next.js is having some config problems when wrapped with other packages.

**Comment by bmichotte** [comment] 2022-01-14 07:20
I tried to remove my middlewares as well, but the issue is still here for me.

Nothing really fancy in my next.config.js
```js
/** @type {import('next').NextConfig} */
module.exports = {
    distDir: process.env.BUILD_DIR ? process.env.BUILD_DIR : '.next',
    env: {
        appName: process.env.APP_NAME,
        baseUrl: process.env.NEXT_URL,
    },
    i18n: {
        locales: ['en', 'fr'],
        defaultLocale: 'en',
    },
    images: {
        domains: [
            'lh3.googleusercontent.com',
            'lh6.googleusercontent.com',
        ],
    },
    webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
        config.resolve = {
            ...config.resolve,
            fallback: {
                fs: false,
                path: false,
                stream: false,
                http: false,
                https: false,
                url: false,
            },
        }

        return config
    },
}
```

I have a global middleware
```ts
/* eslint-disable @next/next/no-server-import-in-page */
import { Settings } from 'luxon'

export async function middleware() {
    Settings.defaultZone = 'utc'
}
```

and a "admin" middleware 
```ts
/* eslint-disable @next/next/no-server-import-in-page */
import { getToken } from 'next-auth/jwt'
import { NextResponse } from 'next/server'
import { Role } from '@prisma/client'

export async function middleware(req) {
    const session = await getToken({
        req,
        secret: process.env.JWT_SECRET_KEY,
        secureCookie: process.env.NEXTAUTH_URL?.startsWith('https://') ?? true,
    })
    if (!session) {
        return NextResponse.redirect('/')
    }
    const roles = session.roles as Role[]
    if (!roles.includes(Role.ADMIN)) {
        return NextResponse.redirect('/')
    }
}
```

**Comment by simontaisne** [comment] 2022-01-14 08:45
Exact same issue here, with the following error `Cannot read properties of undefined (reading 'call')`.

> After removing this middleware I can no longer reproduce the fast refresh issue.

I confirm that by deleting the middleware I can no longer reproduce either 🤔

**Comment by switz** [comment] 2022-01-14 10:34
We've been tracking this issue in #31827 – it has to do with importing files into middleware. There's a reproduction repo in that thread.

**Comment by snax4a** [comment] 2022-01-14 10:53
I have added my own reproduction demo to the reproduction description

**Comment by simontaisne** [comment] 2022-01-14 11:55
Thanks, @switz. In my case, I don't have any custom imports in the middleware, only from `next/server`.

**Comment by balazsorban44** [comment] 2022-01-15 01:49
Sounds like a duplicate of #31827

Closing in favor of that since it's already in our backlog

**Closed by balazsorban44** 2022-01-15 01:49 UTC
Labels: type: needs investigation, template: bug

**Comment by ribeaud** [comment] 2022-01-17 15:06
> We're also getting a similar error after updating to `12.0.8`
> 
> The error is like following
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'baseApiParams')
>     at _callee$ (webpack-internal:///./generated/auth/Api.ts:289:85)
>     at tryCatch (webpack-internal:///./node_modules/next/dist/compiled/regenerator-runtime/runtime.js:45:40)
>     at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/next/dist/compiled/regenerator-runtime/runtime.js:274:22)
>     at Generator.prototype.<computed> [as next] (webpack-internal:///./node_modules/next/dist/compiled/regenerator-runtime/runtime.js:97:21)
>     at asyncGeneratorStep (webpack-internal:///./generated/auth/Api.ts:27:28)
>     at _next (webpack-internal:///./generated/auth/Api.ts:45:17)
>     at eval (webpack-internal:///./generated/auth/Api.ts:50:13)
>     at new Promise (<anonymous>)
>     at eval (webpack-internal:///./generated/auth/Api.ts:42:16)
>     at Api.eval [as request] (webpack-internal:///./generated/auth/Api.ts:377:30)
>     at sessionAuthenticateCreate (webpack-internal:///./generated/auth/Api.ts:489:30)
>     at _callee$ (webpack-internal:///./utils.ts:157:36)
>     at tryCatch (webpack-internal:///./node_modules/next/dist/compiled/regenerator-runtime/runtime.js:45:40)
>     at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/next/dist/compiled/regenerator-runtime/runtime.js:274:22)
>     at Generator.prototype.<computed> [as next] (webpack-internal:///./node_modules/next/dist/compiled/regenerator-runtime/runtime.js:97:21)
>     at asyncGeneratorStep (webpack-internal:///./utils.ts:45:28)
>     at _next (webpack-internal:///./utils.ts:63:17)
>     at eval (webpack-internal:///./utils.ts:68:13)
>     at new Promise (<anonymous>)
>     at Object.eval [as mutationFn] (webpack-internal:///./utils.ts:60:16)
>     at Object.fn (webpack-internal:///./node_modules/react-query/es/core/mutation.js:142:31)
>     at run (webpack-internal:///./node_modules/react-query/es/core/retryer.js:105:31)
>     at new Retryer (webpack-internal:///./node_modules/react-query/es/core/retryer.js:166:3)
>     at Mutation.executeMutation (webpack-internal:///./node_modules/react-query/es/core/mutation.js:136:20)
>     at eval (webpack-internal:///./node_modules/react-query/es/core/mutation.js:96:20)
> ```
> 
> This is being thrown inside a TypeScript class that is generated using this library `swagger-typescript-api` And it seems so far to be thrown when trying to access properties using the `this` keyword inside the class methods.
> 
> Could this be related to `Webpack`or `swc`?
> 
> It is a bit hard to replicate since the tool is generating the Code from an API of one of our projects, but I'll try to put something together 🤞
> 
> Hope this helps a little until then!

This post rings a bell: we are using **openapi-generator-cli** to generate the client side files. One generated class is `runtime.ts` which roughly looks as following:
```ts
export class BaseAPI {

    private middleware: Middleware[];

    constructor(protected configuration = new Configuration()) {
        this.middleware = configuration.middleware;
    }
   ...
}
```
After after updating to _12.0.8_ (it works like a charm before), we're now seeing this output in the console: `Cannot read properties of undefined (reading 'middleware')`.

**Comment by balazsorban44** [comment] 2022-02-17 00:11
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
