### ISSUE TITLE
Cannot find name 'StaticImageData' with Typescript

### ISSUE THREAD

**Issue by tal-rofe** [vercel/next.js#35856] opened 2022-04-03 20:29 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.13.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.4
      react: 17.0.2
      react-dom: 17.0.2
```

### Describe the Bug

I am using the type `StaticImageData` provided by Next Typescript types.
But when compiling with TSC the application, I get: `Cannot find name 'StaticImageData' with Typescript`
This bug has already occurred in version `12.1.1`. My last working version is `12.1.0`.

### Expected Behavior

Should not throw an error for using this type.

### To Reproduce

version `^12.1.1` is required.

I have this file in root: `next-env.d.ts`:
```
/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/basic-features/typescript for more information.
```

which is also included in my `tsconfig.json` file:
`	"include": ["next-env.d.ts"],`

**Comment by balazsorban44** [comment] 2022-04-04 14:50
It looks like #34394 caused some kind of regression, which was introduced in [12.1.1](https://github.com/vercel/next.js/releases/tag/v12.1.1)

I am trying `import type { StaticImageData } from "next/image"`

that seems to work fine. Could you add a code snippet of how are you trying to use `StaticImageData`?

**Comment by tal-rofe** [comment] 2022-04-04 15:36
> It looks like #34394 caused some kind of regression, which was introduced in [12.1.1](https://github.com/vercel/next.js/releases/tag/v12.1.1)
> 
> I am trying `import type { StaticImageData } from "next/image"`
> 
> that seems to work fine. Could you add a code snippet of how are you trying to use `StaticImageData`?

I added all the reproduction needed.
I just using this type without any import. Because inserting this one: "include": ["next-env.d.ts"], makes it work (or at-least should)

**Comment by balazsorban44** [comment] 2022-04-05 08:47
Could you at least describe the way you are using it?

I am not sure we should allow usage without explicit import anyway. It's not really documented anywhere as far as I am aware.

**Comment by tal-rofe** [comment] 2022-04-05 10:59
> Could you at least describe the way you are using it?
> 
> I am not sure we should allow usage without explicit import anyway. It's not really documented anywhere as far as I am aware.

Ok, I'll try using it explicitly and update

**Comment by balazsorban44** [comment] 2022-04-05 11:30
I'm going to close this for now. Since it was undocumented in the first place, I don't think we can call this a bug.

Without a use case provided, it's also hard to tell if we should even document `import type { StaticImageData } from "next/image"`, but let us know. :+1:

**Closed by balazsorban44** 2022-04-05 11:30 UTC
Labels: template: bug, area: TypeScript
