### ISSUE TITLE
10.0.2: On Router.back(), additional query string params are not parsed on spread/wildcard routes

### ISSUE THREAD

**Issue by studiocadogan** [vercel/next.js#19320] opened 2020-11-19 15:40 UTC
# Bug report

## Describe the bug

As of Next 10.0.2 (but possibly in 10.0.0), when using Router.back() (or clicking the browser's back button), if the route is a spread route (i.e. `/blog/[...slugs]` or a rewrite such as `/blog/:slug*`), if there is more than one additional query string in the url (i.e. /blog/sneakers/test?foo=bar&bar=foo), all query strings will be omitted from getInitialProps.

## To Reproduce

1. Create `/blog/[...slugs]` page, or `/blog/:slug*` rewrite, with a getInitialProps function declared inside the page component.
2. Navigate to `/blog/foo/bar?foo=bar&bar=foo`
3. Click an a link to client-side route to another page
4. Click back on the browser, or execute Router.back()

## Expected behavior

ctx.query should contain `{
slugs: ['foo', 'bar'],
foo: 'bar',
bar: 'foo'}`

## Actual behavior

ctx.query contains `{
slugs: ['foo', 'bar']
}`

**Comment by timneutkens** [comment] 2020-11-23 19:43
I can't reproduce this based on this reproduction:

```jsx
import { useRouter } from "next/router";
import Link from "next/link";

export default function Home(props) {
  const router = useRouter();
  return (
    <>
      <pre>
        {JSON.stringify(
          { router: { query: router.query }, props: { query: props.query } },
          null,
          "  "
        )}
      </pre>
      <Link href="/">
        <a>home</a>
      </Link>
    </>
  );
}

Home.getInitialProps = (ctx) => {
  return { query: ctx.query };
};

```

**Comment by timneutkens** [comment] 2020-11-24 10:22
Going to close this issue until a reproduction is provided, thanks!

**Closed by timneutkens** 2020-11-24 10:22 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-01-29 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
