### ISSUE TITLE
Next Image types prevent building since 11.1.1

### ISSUE THREAD

**Issue by nbouvrette** [vercel/next.js#28812] opened 2021-09-05 21:57 UTC
### What version of Next.js are you using?

11.1.1

### What version of Node.js are you using?

v14.17.5

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

While trying to upgrade Next.js I ran into the following build error that seems to be triggered by Next.js 11.1.1:

```
node_modules/next/types/index.d.ts:46:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'loading' must be of type '"eager" | "lazy"', but here has type '"auto" | "eager" | "lazy"'.

46     loading?: 'auto' | 'eager' | 'lazy'
       ~~~~~~~

  node_modules/@types/react/index.d.ts:2156:9
    2156         loading?: "eager" | "lazy" | undefined;
                 ~~~~~~~
    'loading' was also declared here.


Found 1 error.
```

### Expected Behavior

Build should work.

### To Reproduce

Install Next.js 11.1.1 with @types/react  ^17.0.20, and open `node_modules\next\types\index.d.ts` to see the IDE error on line 46.

**Comment by nbouvrette** [comment] 2021-09-06 01:26
This issue seems related to this PR: https://github.com/vercel/next.js/pull/28672

I tried to downgrade to @types/node": "^16.7.10 and still got the same build error.

**Comment by stefanprobst** [comment] 2021-09-06 11:27
i think this should already be fixed by the pr you linked above. can you try with `yarn add next@canary`?

**Comment by timneutkens** [comment] 2021-09-06 11:28
Indeed, it's been fixed already and is out on canary 👍

**Closed by timneutkens** 2021-09-06 11:28 UTC
Labels: template: bug

**Comment by nbouvrette** [comment] 2021-09-06 13:10
@stefanprobst @timneutkens thanks for some reason I didn't realize it was the fix. 

By the way a quick note, it looks like it's not possible to install `@canary` with `npm` (not sure if anyone uses it):

```
$ npm i -D next@canary
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: next@11.1.3-canary.7
npm ERR! node_modules/next
npm ERR!   dev next@"11.1.3-canary.7" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@">=10.2.0" from eslint-config-next@11.1.2
npm ERR! node_modules/eslint-config-next
npm ERR!   dev eslint-config-next@"^11.1.2" from the root project
```

Should open another issue for this?

It seems to be coming from `\node_modules\eslint-config-next\package.json`

```
  "peerDependencies": {
    "next": ">=10.2.0",
  },
```

**Comment by balazsorban44** [comment] 2022-01-27 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
