### ISSUE TITLE
Add lang attribute to html for better accessibility

### ISSUE THREAD

**Issue by okonet** [vercel/next.js#9160] opened 2019-10-22 14:40 UTC
# Feature request

`html` tag accepts `lang` attribute that is, [according to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html), very important for accessibility and accessible technologies like screen readers.

> Providing a lang attribute with a valid IETF identifying language tag on the <html> element will help screen reading technology determine the proper language to announce. 

## Describe the solution you'd like

Add `lang="en"` by default and provide a simple way to configure the language for the whole project.

## Describe alternatives you've considered

We've ended overriding the `_document.js`  as of https://github.com/zeit/next.js#custom-document but not providing this by default contributes to even worse web accessibility situation.

## Additional context

Google Chrome shows "Translate this page" dialog without the `lang` set.

**Comment by kachkaev** [comment] 2019-10-22 14:52
IMHO setting `lang="en"` by default can make things worse for non-English Next.js websites. Setting it in `_document.js` seems to be the right way. [This is what I do](https://gitlab.com/kachkaev/website-frontend/blob/ec20c3bfec24cde40d80194bcad5ba69b308a5ef/src/pages/_document.tsx#L31) and I don't feel bothered.

**Comment by okonet** [comment] 2019-10-23 10:13
I assume most next.js user don't bother overriding `_document.js`.

**Comment by timneutkens** [comment] 2019-10-23 12:58
Assuming all pages are english would be wrong imo. For reference there's a large number of Next.js sites in basically every major language you can think of.

Making it easier to configure something like that would be interesting to pursue. cc @devknoll let's keep this in mind with the `next/head` deprecation.

**Comment by sever1an** [comment] 2019-12-02 20:46
Thinking more broadly, `react-helmet` provides a facility for supplying arbitrary attributes to `html` and `body` within its equivalent of `Head` on any page.

**Comment by timneutkens** [comment] 2019-12-03 09:04
To come back to my earlier comment, RFC for deprecating next/head is here: #9602 8981

**Comment by bionicles** [comment] 2020-01-22 07:38
this fails on lighthouse CI with a default create-next-app and seems easy to fix

**Comment by ScottSmith95** [comment] 2020-01-22 15:50
It would be nice to not have to override `pages/_document.js` and just add something to next’s config.

**Comment by razvangherghina** [comment] 2020-01-25 13:13
+1 lang is important

**Comment by phattranky** [comment] 2020-01-28 06:56
+1 it's important

**Comment by timneutkens** [comment] 2020-01-28 09:50
Please don't spam the thread with +1. Use the GitHub emoji reaction system to add a 👍 on the initial issue.

**Comment by cereallarceny** [comment] 2020-03-24 18:20
Perhaps this is a bit out of scope, but for multi-domain deployments (.com, .nl, .pt) it would also be kind of nice to add the `lang` tag without having to implement a custom server either.

**Comment by TommySorensen** [comment] 2020-04-21 06:47
Anyone managed to set `<Html lang={someLang}>` when using `getServerSideProps` or `getStaticProps` when the language changes between pages? Right now the `_document.js` is only set on first load, from there it is not set again. That means, the my language prop from my pages will never change in the `_document.js` file.

Right now i am using `getServerSideProps` like this. Where i set the language on the page, and then extract the language in `_document.js` from `__NEXT_DATA__` and set it on the `<Html lang={langHere}>`
```js
export async function getServerSideProps(context) {
  const pageContent = await getSomePageContent(context.params)

  return {
    props: {
      language: getLanguageFromParams(context.params),
      pageContent,
    },
  }
}
```

@timneutkens The documentation does not mention any solution on how to set the language again?

**Comment by hangindev** [comment] 2020-06-15 02:22
> Anyone managed to set `<Html lang={someLang}>` when using `getServerSideProps` or `getStaticProps` when the language changes between pages? Right now the `_document.js` is only set on first load, from there it is not set again. That means the language prop from my pages will never change in the `_document.js` file.
> 
> Right now i am using `getServerSideProps` like this. Where i set the language on the page, and then extract the language in `_document.js` from `__NEXT_DATA__` and set it on the `<Html lang={langHere}>`
> 
> ```js
> export async function getServerSideProps(context) {
>   const pageContent = await getSomePageContent(context.params)
> 
>   return {
>     props: {
>       language: getLanguageFromParams(context.params),
>       pageContent,
>     },
>   }
> }
> ```
> 
> @timneutkens The documentation does not mention any solution on how to set the language again?

Using `getServerSideProps` will lose the benefit of static optimization though unless you are already using it already.

My approach is to set different `lang` attributes for different pages using `_document.js`'s `getInitialProps`  so that the search engines and crawler will see the right one:

```js
class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    const { pathname } = ctx;
    const lang = pathname.startsWith("/de") ? "de" : "en";
    return { ...initialProps, lang };
  }

  render() {
    const { lang } = this.props;
    return (
      <Html lang={lang}>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
```

Then, I update the `lang` attribute with the help of `useRouter` hook in `_app.js` for client-transitions:

```js
function MyApp({ Component, pageProps }) {
  const { pathname } = useRouter();
  const lang = pathname.startsWith("/de") ? "de" : "en";
  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  return <Component {...pageProps} />;
}
```

But this approach would only work if browsers and screen readers will pick up dynamically set `lang` attribute.

[![Edit dynamic-html-lang-property-in-statically-generated-next-js-pages](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dynamic-html-lang-property-in-statically-generated-next-js-pages-0z2xu?fontsize=14&hidenavigation=1&theme=dark)

**Comment by JannikZed** [comment] 2020-06-28 14:21
Is there any recommendation on how to set the HTML language when using getstaticprops / path? We can prerender all of our pages and have the active language set as param. `page.de/en/products/XXX` or `page.de/de/products/XXX` - so the language is available as prop. Just curious if we could set the language during static build time.

**Comment by ogostos** [comment] 2020-07-07 05:35
> Using `getServerSideProps` will lose the benefit of static optimization unless you're using it already.
> 
> The following approach is to set different `lang` attributes for different pages using `_document.js`'s `getInitialProps` for SEO.
> 
> ```js
> class MyDocument extends Document {
>   static async getInitialProps(ctx) {
>     const initialProps = await Document.getInitialProps(ctx);
>     const { pathname } = ctx;
>     const lang = pathname.startsWith("/de") ? "de" : "en";
>     return { ...initialProps, lang };
>   }
> 
>   render() {
>     const { lang } = this.props;
>     return (
>       <Html lang={lang}>
>         <Head />
>         <body>
>           <Main />
>           <NextScript />
>         </body>
>       </Html>
>     );
>   }
> }
> ```


Setting through `getInitialProps `won't work for dynamic routes.

**Comment by sim51** [comment] 2020-09-16 13:30
FYI, I have developed a work around on my project for with.
I used the  opengraph meta "og:locale" to define the local for each page and then in my custom `Document` I search it.
This is my code : 

 ```
export default class CustomDocument extends Document<DocumentProps & { lang: string }> {
  static async getInitialProps(ctx: DocumentContext) {
    const initialProps: DocumentInitialProps = await Document.getInitialProps(ctx);
    const ogLocaleMeta = initialProps.head
      ? initialProps.head.find((e) => e && e.type === "meta" && e.props.name === "og:locale")
      : null;
    return { ...initialProps, lang: ogLocaleMeta ? localeToLang[ogLocaleMeta.props.content] : null };
  }

  render() {
    return (
      <Html prefix="og: http://ogp.me/ns#" lang={this.props.lang || "en"}>
```

Hope it can helps someone else :)

**Comment by Timer** [comment] 2020-09-16 14:57
This will be handled by https://github.com/vercel/next.js/discussions/17078

**Comment by Sleepful** [comment] 2020-10-25 05:08
`document.documentElement.lang = 'yourlang'`

**Comment by lachlanjc** [comment] 2020-11-18 00:50
You can add this yourself in _document.js & the new internationalization feature handles it automatically: https://nextjs.org/docs/advanced-features/i18n-routing#search-engine-optimization

I think we can close this @Timer?

**Comment by Sleepful** [comment] 2020-11-20 16:28
You marked my comment as offtopic, but it's the only workaround that works for multi-language apps, because overriding `_document.js` won't update on language change

**Comment by desko27** [comment] 2020-12-20 12:08
Just extending what @lachlanjc already told with the simplest example:

```js
// next.config.js
module.exports = {
  i18n: {
    locales: ['en-US'],
    defaultLocale: 'en-US'
  }
}
```

If you're using Next.js v10+ you can just add an `i18n` entry to `next.config.js` file and you'll get the lang attribute on the html tag for free.

> [From the docs](https://nextjs.org/docs/advanced-features/i18n-routing#search-engine-optimization)
> Since Next.js knows what language the user is visiting it will automatically add the lang attribute to the <html> tag.

**Comment by okonet** [comment] 2020-12-20 22:25
Yes, I think the issue can be closed now.

**Closed** 2020-12-20 22:26 UTC
Labels: kind: story, type: feature request, type: needs investigation

**Comment by brentmclark** [comment] 2020-12-30 18:18
> Just extending what @lachlanjc already told with the simplest example:
> 
> ```js
> // next.config.js
> module.exports = {
>   i18n: {
>     locales: ['en-US'],
>     defaultLocale: 'en-US'
>   }
> }
> ```
> 
> If you're using Next.js v10+ you can just add an `i18n` entry to `next.config.js` file and you'll get the lang attribute on the html tag for free.
> 
> > [From the docs](https://nextjs.org/docs/advanced-features/i18n-routing#search-engine-optimization)
> > Since Next.js knows what language the user is visiting it will automatically add the lang attribute to the  tag.

For future readers, this is not currently supported if you're using SSG via `next export`.  Attempting to export with this setting in place will result in the error `i18n support is not compatible with next export`.  To my knowledge, you'll still need to use one of the alternative methods above for SSG.

See link below for more details:

https://nextjs.org/docs/advanced-features/i18n-routing#how-does-this-work-with-static-generation

**Comment by Sleepful** [comment] 2021-01-08 09:32
> Yes, I think the issue can be closed now.

Still not a solution for multi-language apps.

**Comment by Bulbariss** [comment] 2021-01-08 12:13
You can put `<html lang={seo.siteLanguage} />` last inside next/head component like this:
```
import Head from "next/head";

export default function SEO({ lang }) {
  return (
    <Head>
      {/* Your Meta Tags */}
      <html lang={lang} />
    </Head>
  );
}
```
Works great for me.

**Comment by wilcoxmd** [comment] 2021-03-13 23:40
> Using getServerSideProps will lose the benefit of static optimization unless you're using it already.
> 
> The following approach is to set different lang attributes for different pages using _document.js's getInitialProps for SEO.
> ```js
> class MyDocument extends Document {
>   static async getInitialProps(ctx) {
>     const initialProps = await Document.getInitialProps(ctx);
>     const { pathname } = ctx;
>     const lang = pathname.startsWith("/de") ? "de" : "en";
>     return { ...initialProps, lang };
>   }
> 
>   render() {
>     const { lang } = this.props;
>     return (
>       <Html lang={lang}>
>         <Head />
>         <body>
>           <Main />
>           <NextScript />
>         </body>
>       </Html>
>     );
>   }
> }
> ```
> > Setting through getInitialProps won't work for dynamic routes.

You can get the dynamic route parameter value by using `ctx.query` instead (and `router.query` in _app.js)

**Comment by salyadav** [comment] 2021-06-15 14:16
> > Using getServerSideProps will lose the benefit of static optimization unless you're using it already.
> > The following approach is to set different lang attributes for different pages using _document.js's getInitialProps for SEO.
> > ```js
> > class MyDocument extends Document {
> >   static async getInitialProps(ctx) {
> >     const initialProps = await Document.getInitialProps(ctx);
> >     const { pathname } = ctx;
> >     const lang = pathname.startsWith("/de") ? "de" : "en";
> >     return { ...initialProps, lang };
> >   }
> > 
> >   render() {
> >     const { lang } = this.props;
> >     return (
> >       <Html lang={lang}>
> >         <Head />
> >         <body>
> >           <Main />
> >           <NextScript />
> >         </body>
> >       </Html>
> >     );
> >   }
> > }
> > ```
> > 
> > 
> > > Setting through getInitialProps won't work for dynamic routes.
> 
> You can get the dynamic route parameter value by using `ctx.query` instead (and `router.query` in _app.js)

https://github.com/vercel/next.js/issues/9160#issuecomment-798802733


In typescript, i get an error like this when done something as mentioned-
Property 'hasFaq' does not exist on type 'Readonly<RenderPageResult & { styles?: ReactElement<any, string | JSXElementConstructor<any>>[] | ReactFragment | undefined; } & { ...; }> & Readonly<...>'

**Comment by wilcoxmd** [comment] 2021-06-15 15:29
`Property 'hasFaq' does not exist on type...`

Looks like something specific to your own project typings-- missing the `hasFaq` property somewhere.

**Comment by salyadav** [comment] 2021-06-16 07:35
So

> @salyadav
> 
> `Property 'hasFaq' does not exist on type...`
> 
> Looks like something specific to your own project typings-- missing the `hasFaq` property somewhere.

@wilcoxmd Thanks for replying!
My problem statement looks something like this- 
I need to add FAQ Schema to some of the static pages and not to some other. 
So based on the pages i need to add some additional properties in the html tag like this-
`<html lang="ja" itemscope itemtype="https://schema.org/FAQPage">`

Thats where the hasFaq comes into picture. I am adding a similar logic for this attribute as for lang in the above snippet. Any pointers on how to go about this. 
Note- This needs to be statically generated at build time itself. 
As of now i am running a script to parse the html and do a string replace like this-
```
 ....replace('<html lang="__LANG__">', buildHtmlTag(filePath, label))
.
.
const buildHtmlTag = (filePath, locale) => {
    for (const page of PAGES_WITH_FAQ) {
      if (filePath.endsWith(`${page}.html`)) {
        return `<html lang=${locale} itemscope itemtype="https://schema.org/FAQPage">`;
      }
    }
    return `<html lang="${locale}">`;
  };
```

**Comment by balazsorban44** [comment] 2022-01-28 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
