### ISSUE TITLE
[Next 10][Next/Image] Image in Head breaks at build/server render time

### ISSUE THREAD

**Issue by conanbatt** [vercel/next.js#18799] opened 2020-11-04 17:11 UTC
# Bug report

Images under an tag breaks at build/server render time

## To Reproduce

Repo: https://github.com/conanbatt/nextjs-webpack-5-images
1. yarn build 
OR
1. yarn dev -> go to /

Alternatively run this snippet in a page:
```
<Head>
  <noscript>
    <img src="" />
  </noscript>
</Head>
```

## Expected behavior

Does not produce error

## Screenshots

![image](https://user-images.githubusercontent.com/268199/98142858-355d8a00-1e7d-11eb-954a-ab348cdf6926.png)

## System information

- Version of Next.js: [e.g. 10.0.1]
- Version of Webpack: [e.g. 5.4.0]

## Additional context

I believe this might be related to image changes in Next 10. The error points to the image tag being transformed into something that can't be processed. Does not happen on Next 9.5.3 and webpack 4

I was able to skirt around it by doing:
```
<noscript>
 {[<img src="" key="1]}
</noscript>
```

**Comment by timneutkens** [comment] 2020-11-05 10:53
Looks like a duplicate of #17721

**Comment by Timer** [comment] 2021-01-04 17:41
This is no longer broken on `canary`.
![image](https://user-images.githubusercontent.com/616428/103563132-38c7be80-4e8a-11eb-979b-b030ba6ca38d.png)

**Closed by Timer** 2021-01-04 17:41 UTC
Labels: kind: bug, point: 2

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
