### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS when change headers and uncheck disable cache

### ISSUE THREAD

**Issue by angelamelinda** [vercel/next.js#64030] opened 2024-04-03 15:27 UTC
### Link to the code that reproduces this issue

https://github.com/angelamelinda/reproduce-redirects

## Pre-Requisite

- Using chrome as the browser
- Install [modheader](https://chromewebstore.google.com/detail/modheader-modify-http-hea/idgpnmonknjnojddfkpgkljpfnnfcklj) extention on chrome

## How to Reproduce
- Open modheader and add header **partnerid** with value **a**
  <img width="634" alt="image" src="https://github.com/angelamelinda/reproduce-redirects/assets/19211116/988a66b5-e42d-4d87-9205-9a0734a77cba">
- Run the app with command **yarn dev**
- Open the localhost:3000, it should go to page /a
- Inspect the page, and open network tab and **uncheck disable cache**<img width="725" alt="image" src="https://github.com/vercel/next.js/assets/19211116/aebdd231-c0a9-4bb2-9e25-89330fe3bc0f">
- Change the partnerid value to **b** in modheader, and open the localhost:3000, it should go to page /b, but sometimes it shows **ERR_TOO_MANY_REDIRECTS** first before go to /b and it only happens if the disable cache is turn off
- If you are still not face **ERR_TOO_MANY_REDIRECTS**, please change the partnerid value to **a** in modheader, or otherwise to reproduce the issue.

https://github.com/angelamelinda/reproduce-redirects/assets/19211116/af276b42-0923-4c59-9a64-b28ea4399380

### Current behavior
ERR_TOO_MANY_REDIRECTS happen when uncheck disable cache and change the headers
### Expected behavior
No ERR_TOO_MANY_REDIRECTS happen when uncheck/check disable cache

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Tue Nov  7 21:40:08 PST 2023; root:xnu-8796.141.3.702.9~2/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.12.0
  npm: 10.5.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.2.0-canary.54 // Latest available version is detected (14.2.0-canary.54).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, App Router, Middleware / Edge (API routes, runtime)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Other (Deployed)

### Additional context

I tested this also in 14.1.4 and 14.1.3, and same issue still exists if I uncheck disable cache on chrome.

**Comment by ztanner** [comment] 2024-04-04 14:47
Hi, it looks like you have a logic error in your `entrypoint.tsx` file:
https://github.com/angelamelinda/reproduce-redirects/blob/master/src/pages/entrypoint.tsx#L15

```tsx
  const partnerId =
    reqHeaders?.partnerid !== "undefined"
      ? reqHeaders?.partnerid
      : cookies[COOKIES.PARTNER_ID];
      ```
      
I think you meant to write `typeof reqHeaders?.partnerId !== "undefined"`. Otherwise, if `reqHeaders?.partnerId` is indeed undefined, it will be used for your `partnerId` variable because `undefined !== "undefined"`. In practice this means that if my `partnerId` cookie is `b`, and I visit `a`, `a` will redirect to `entrypoint`, and then `entrypoint` will redirect back to `a`, creating an infinite redirect. 

I'd also suggest not using permanent redirects (`permanent: true`) if the redirect is based on a cookie value, as otherwise your browser cache will see the URL and not even bother checking the response because you previously indicated that the redirect was permanent. 

Closing this as I don't believe there's a bug here, but feel free to ask any follow up questions!

**Closed by ztanner** 2024-04-04 14:47 UTC
Labels: template: bug, area: Edge
