### ISSUE TITLE
Suggestion: Separate next.js example updates / core updates in release notes

### ISSUE THREAD

**Issue by ndom91** [vercel/next.js#14472] opened 2020-06-22 21:12 UTC
# Feature request

## Describe the solution you'd like

I assume removing the examples from the primary repository has already been discussed. As this folder grows and the changes therein more frequent, maybe it makes sense to split that off into its own repo? Anyway, my suggestion here is much simpler.

Simply split the updates to the examples and the updates to next.js core in separate sections in the release notes for much easier reading.

## Additional context

For example, `v9.4.5-canary.12` currently looks like such:

> Patches
> Add test case for loading 404 on invalid bundle: #14082
> [Examples] remove getInitialProps from with-firebase-authentication: #13895
> [Example] remove getInitialProps from aws-amplify-typescript: #13898
> Tests: fail when cannot replace content: #14087
> Fix route in custom-server-koa example: #14080
> Simplify test checks: #14094
> Update AMP Optimizer to v2.5.2: #14095
> Remove Head.rewind as it's no longer needed: #14091
> Add new import flow to CMS examples: #14053
> [Examples] Fix using-preact dev mode issues: #14098
> Update with-userbase Example: #14100
> Fixed Avatar.js component where Strapi CMS would fail when fetching an image: #14084
> Update deploy button in the userbase example: #14107
> Use the expected import: #14111
> Use envLink for deploy buttons: #14110
> Fix(example): needs TypeScript support: #14115

Perhaps it would be easier to read / skim looking something like this:

> ### Patches
> 
> #### Core
> Add test case for loading 404 on invalid bundle: #14082
> Tests: fail when cannot replace content: #14087
> Simplify test checks: #14094
> Update AMP Optimizer to v2.5.2: #14095
> Remove Head.rewind as it's no longer needed: #14091
> Use the expected import: #14111
> Use envLink for deploy buttons: #14110
> 
> #### Examples
> Fix(example): needs TypeScript support: #14115
> Update deploy button in the userbase example: #14107
> Add new import flow to CMS examples: #14053
> [Examples] Fix using-preact dev mode issues: #14098
> Update with-userbase Example: #14100
> Fixed Avatar.js component where Strapi CMS would fail when fetching an image: #14084
> Fix route in custom-server-koa example: #14080
> [Examples] remove getInitialProps from with-firebase-authentication: #13895
> [Example] remove getInitialProps from aws-amplify-typescript: #13898

**Comment by timneutkens** [comment] 2020-06-22 21:15
This is being worked on by @rafaelalmeidatk, we've recently landed automatic labeling

**Comment by lachlanjc** [comment] 2021-01-03 07:42
These have been implemented! 🥳

![image](https://user-images.githubusercontent.com/5074763/103474022-5d7a4400-4d6d-11eb-931b-064890b4c53d.jpeg)

**Closed** 2021-01-03 10:03 UTC
Labels: kind: story

**Comment by balazsorban44** [comment] 2022-01-28 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
