### ISSUE TITLE
Navigating to a dynamic route that matches the page's filename causes a 500 response and an empty query

### ISSUE THREAD

**Issue by jkjustjoshing** [vercel/next.js#19296] opened 2020-11-19 05:02 UTC
# Bug report

## Describe the bug
When I have a dynamic route in Next.js and the user navigates to the dynamic route that matches the filename in my `/pages` directory, they are presented with a 500 error. For example, with the file `pages/[test].tsx`, the route `localhost:3000/[test]` will 500 error. Additionally, the `router.query` object is not populated as expected.

## To Reproduce
1. Create a new dynamic route, i.e. `pages/[test].tsx`
```javascript
import { useRouter } from "next/router";

export default function TestPage() {
  const router = useRouter();
  return <div>Hello World. {JSON.stringify(router.query)}</div>;
}
```
Note that the following work

| URL  | Text on page |
| ------------- | ------------- |
| localhost:3000/abc123  | Hello World. { "test": "abc123" } |
| localhost:3000/foo  | Hello World. { "test": "foo" } |
| localhost:3000/[something-besides-test]  | Hello World. { "test": "[something-besides-test]" } |

2. Navigate to `localhost:3000/[test]`

## Expected behavior

The text `Hello World. { "test": "[test]" }` appears on the page.

## Reproduction

https://codesandbox.io/s/cranky-lichterman-69c06

## Screenshots
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/813192/99623196-921e8000-29f9-11eb-9162-16dedcad3e28.png">

## System information

- OS: macOS 10.15.7
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: v10.0.1
- Version of Node.js: v12.16.3
- Deployment: `next start` and `next` (local development)

**Comment by ijjk** [comment] 2020-11-19 17:17
This appears to be a duplicate of https://github.com/vercel/next.js/issues/17096 so I'm going to close this in favor of that one

**Closed by ijjk** 2020-11-19 17:17 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-29 03:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
