### ISSUE TITLE
Locale not working with custom server

### ISSUE THREAD

**Issue by Rechdan** [vercel/next.js#25983] opened 2021-06-10 11:52 UTC
### What version of Next.js are you using?

Next.js v10.2.3

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

MS Edge Version 91.0.864.41 (Official build) (64-bit)

### What operating system are you using?

Debian GNU/Linux 10 (buster)

### How are you deploying your application?

development

### Describe the Bug

Server config:
```ts
import next from "next";
import http from "http";
import express from "express";
import helmet from "helmet";

const port = 3000;

const nextServer = next({
  conf: {
    experimental: {},
    future: {},
    i18n: {
      locales: ["pt", "en"],
      defaultLocale: "pt",
    },
  },
  customServer: true,
  dev: true,
});

nextServer.prepare().then(() =>
  http
    .createServer(
      express()
        .use(helmet({ contentSecurityPolicy: false }))
        .use(async (req, res) => await nextServer.render(req, res, "/", { currPath: req.path }))
    )
    .on("listening", () => console.log("Listening", port))
    .on("error", (error) => console.error("Error:", error))
    .on("close", () => console.log("Closed!"))
    .listen(port)
);
```

The hook:
```tsx
const { locale, defaultLocale } = useRouter();
```
Here, they are both `undefined`!

### Expected Behavior

Have this:
```tsx
const { locale, defaultLocale } = useRouter();
```
Return `locale = "pt"/"en"` and `defaultLocale = "pt"`

### To Reproduce

Starting the server:
`ts-node --transpile-only --project \"./tsconfig.server.json\" --require tsconfig-paths/register \"./src/index.ts\"`

**Comment by ijjk** [comment] 2021-06-10 16:50
Closing as a duplicate of https://github.com/vercel/next.js/issues/20761

**Closed by ijjk** 2021-06-10 16:50 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
