### ISSUE TITLE
Link component removes trailing slash if a dot is in the URL

### ISSUE THREAD

**Issue by tremby** [vercel/next.js#31472] opened 2021-11-16 01:13 UTC
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

16.13.0

### What browser are you using?

n/a

### What operating system are you using?

n/a

### How are you deploying your application?

n/a

### Describe the Bug

The site I'm working on has [trailing slashes](https://nextjs.org/docs/api-reference/next.config.js/trailing-slash) enabled.

Some of my pages have a dot in their URL. For example, blog posts about new software releases, with version numbers, like `/blog/version-3.1-released/`.

We have found that links to these pages are not correctly rendered to the browser. They do not have the trailing slash present.

I have traced the issue to [the `normalizePathTrailingSlash` function](https://github.com/vercel/next.js/blob/canary/packages/next/client/normalize-trailing-slash.ts).

It looks like it is making the assumption that any URL where the last slash-separated segment has a dot in it, is a static asset and so shouldn't have a trailing slash. This does not seem like a reasonable assumption to me. There are cases where static assets have no dot in their name, and cases like this where pages handled by Next have dots in their path.

I see now that some others have stumbled on the same issue:
- https://github.com/vercel/next.js/issues/18164
- https://github.com/vercel/next.js/issues/16617

One was closed as a duplicate of the other. The other was closed without a reason given, or possibly concluding that something should be added to the documentation about it, but nothing was.

I may be missing something, but I'm not sure a developer would be using the `<Link>` component to point to static assets and so why the test for a dot is there.

Assuming the test is necessary, maybe a compromise would be to have some default file extensions it looks for, rather than just looking for presence of a dot. If necessary, allow this to be configurable so the developer can adjust the test.

### Expected Behavior

Trailing slashes are added or preserved.

### To Reproduce

1. Configure trailing slashes to be switched on
2. Have a page with a dot in its URL
3. Use the `<Link>` component or anything else which uses `resolveHref` to link to that page

Repro repo: https://github.com/tremby/next-trailing-slash-bug-repro

**Comment by ijjk** [comment] 2021-11-16 17:31
Closing as a duplicate of https://github.com/vercel/next.js/issues/25103

**Closed by ijjk** 2021-11-16 17:31 UTC
Labels: template: bug

**Comment by tremby** [comment] 2021-11-16 20:24
@ijjk why is this a duplicate of #25103? That ticket is to do with redirections, this one is not.

**Comment by ijjk** [comment] 2021-11-16 20:52
`next/link` uses the same normalizing as the redirect for the trailingSlash handling

**Comment by balazsorban44** [comment] 2022-01-27 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
