### ISSUE TITLE
Top-level root layout is computed twice

### ISSUE THREAD

**Issue by joulev** [vercel/next.js#52093] opened 2023-07-02 06:50 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:21:34 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8112
    Binaries:
      Node: 20.3.1
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: 8.6.5
    Relevant Packages:
      next: 13.4.8-canary.14
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/joulev/debug/tree/nextjs-root-layout-computed-twice-for-dynamic-routes

### To Reproduce

* `next build`
* `next start`
* Navigate to `/`

### Describe the Bug

The root layout is computed twice.

```
$ pnpm start

> test-rsc-with-mdx@0.1.0 start /Users/joulev/dev/www/debug
> next start

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
Computing layout with incoming pathname: /
Computing layout with incoming pathname: /
```

Interestingly, that only happens to the top-level root layout (`app/layout.tsx`). If I add a directory in-between use something like

```
$ tree ./app       
app
└── (group)
    ├── layout.tsx
    └── page.tsx

2 directories, 2 files
```

then the (still root) layout is not computed twice.

### Expected Behavior

The root layout should only be computed once, like the case where it is not exactly `app/layout.tsx` as shown above.

### How are you deploying your application? (if relevant)

next start

**Comment by izica** [comment] 2023-07-04 14:53
nextjs v13.4.8 same bug

**Comment by balazsorban44** [comment] 2023-07-06 13:47
Thanks, this is a duplicate of #49115 so I'm closing.

**Closed by balazsorban44** 2023-07-06 13:47 UTC
Labels: template: bug, area: app
