### ISSUE TITLE
Redirect with `basePath: false` and i18n does not work

### ISSUE THREAD

**Issue by jeroen-plug** [vercel/next.js#33645] opened 2022-01-25 14:51 UTC
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: linux
      Arch: x64
      Version: #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022
    Binaries:
      Node: 17.2.0
      npm: 8.3.0
      Yarn: 1.22.17
      pnpm: 6.28.0
    Relevant packages:
      next: 12.0.9-canary.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

17.2.0

### What browser are you using?

Firefox, Chromium

### What operating system are you using?

Linux Mint

### How are you deploying your application?

next dev

### Describe the Bug

When using i18n and a basePath in the next config, redirects with `basePath` set to false do not work for any paths that are not in the list of i18n locales.

If the `i18n` block in the example below is removed, the redirects work as expected.

Redirects from source urls that happen to be part of the locales do work for some reason (ex: /en /fr /de).

### Expected Behavior

Given the config below, a request coming in at `/` should be redirected to `/example`. Given that the `locale` property on the redirect is set to false, I do not expect the routing to be affected by a locale prefix.

### To Reproduce

Create a new app using: `npx create-next-app@latest`

Update `next.config.js` to the following:
```js
const basePath = '/example'

module.exports = {
  basePath,

  i18n: {
    locales: ['en', 'fr', 'de'],
    defaultLocale: 'en',
  },

  async redirects() {
    return [
      // Doesn't work (404, no redirect)
      { source: '/', destination: basePath, basePath: false, permanent: false, locale: false },
      { source: '/something', destination: basePath, basePath: false, permanent: false, locale: false },
      { source: '/nl', destination: basePath, basePath: false, permanent: false, locale: false },

      // Does work (redirect)
      { source: '/en', destination: basePath, basePath: false, permanent: false, locale: false },
    ]
  },
}
```

Start using `npm run dev`

Open the page in a browser, note that it does not redirect from `/`, `/something`, or `/nl`.

**Comment by balazsorban44** [comment] 2022-01-25 15:34
Duplicate of #21565

**Closed by balazsorban44** 2022-01-25 15:34 UTC
Labels: template: bug, area: I18n
