### ISSUE TITLE
Image component doesn't load with Concurrent Mode

### ISSUE THREAD

**Issue by sumanthratna** [vercel/next.js#18913] opened 2020-11-06 23:40 UTC
# Bug report

## Describe the bug

The`next/image` component doesn't work with React's Concurrent Mode (I'm aware that Concurrent Mode is experimental)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `yarn create next-app`
2. change the `<img />` at the bottom of `pages/index.js` to `<Image layout='fill' />`
3. `yarn dev`: there's a big Vercel logo across the page
4. enable concurrent mode:
```js
/* next.config.js */
module.exports = {
  experimental: {
    reactMode: 'concurrent',
  },
};
```
5. `yarn dev`: the logo is gone!

this definitely is a problem with SVGs; I'm not sure if it also occurs with other image formats

## Expected behavior

the Vercel logo should appear and take up the whole horizontal viewport, as it does with concurrent mode disabled

## Screenshots

what it should like: 
![big-vercel-logo](https://user-images.githubusercontent.com/31281983/98424335-701f1800-205f-11eb-9520-d05eec650321.png)

what it actually looks like:
![Screen Shot 2020-11-06 at 18 41 20](https://user-images.githubusercontent.com/31281983/98424458-c2f8cf80-205f-11eb-987b-5a7c7b9874c8.png)

## System information

- OS: macOS 11.0 Beta (20A5395g)
- Browser: Chrome 86.0.4240.183, Safari 14.0.1 (16610.2.8.1.1), Firefox 81.0.1
    - the issue occurs with all 3 browsers
- Version of Next.js: 10.0.1
- Version of React: 17.0.1
- Version of Node.js: 12.14.1

## Additional context

N/A

**Comment by sumanthratna** [comment] 2020-11-09 03:48
looks like a very similar problem happens when `experimental.optimizeImages` in the next config is set to true; happy to create a new issue if that helps

**Comment by Timer** [comment] 2020-11-09 06:14
Please try using `next@canary` and let us know if it's fixed!

**Comment by sumanthratna** [comment] 2020-11-09 14:39
> Please try using `next@canary` and let us know if it's fixed!

it looks like canary might not work with Webpack 5 right now—I'll look into this and create a new issue within the next couple of days

**Comment by timneutkens** [comment] 2020-11-09 15:25
> > Please try using `next@canary` and let us know if it's fixed!
> 
> it looks like canary might not work with Webpack 5 right now—I'll look into this and create a new issue within the next couple of days

What does not work?

**Comment by sumanthratna** [comment] 2020-11-09 15:37
> > > Please try using `next@canary` and let us know if it's fixed!
> > 
> > 
> > it looks like canary might not work with Webpack 5 right now—I'll look into this and create a new issue within the next couple of days
> 
> What does not work?

Sorry for being unclear! When I upgrade to Next.js canary, I see this error when I run `yarn build`:
```
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

info  - Creating an optimized production build  
Failed to compile.

./.yarn/$$virtual/next-virtual-90e471bc1b/0/cache/next-npm-10.0.2-canary.5-f947d9c8b6-08c8f41f04.zip/node_modules/next/dist/client/next.js
Error: [BABEL] /Users/suman/quantum/pathflow/frontend/.yarn/$$virtual/next-virtual-90e471bc1b/0/cache/next-npm-10.0.2-canary.5-f947d9c8b6-08c8f41f04.zip/node_modules/next/dist/client/next.js: Failed to resolve "@babel/runtime" relative to "/Users/suman/quantum/pathflow/frontend/.yarn/$$virtual/next-virtual-90e471bc1b/0/cache/next-npm-10.0.2-canary.5-f947d9c8b6-08c8f41f04.zip/node_modules/next/dist/build/babel" (While processing: "programmatic item$5")
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)


> Build error occurred
Error: > Build failed because of webpack errors
    at build (/Users/suman/quantum/pathflow/frontend/.yarn/$$virtual/next-virtual-90e471bc1b/0/cache/next-npm-10.0.2-canary.5-f947d9c8b6-08c8f41f04.zip/node_modules/next/dist/build/index.js:15:918)
```
that error doesn't occur with Next.js 10.0.1

Here's my next.config.js:
```
module.exports = {
  reactStrictMode: true,
  experimental: {
    /* reactMode: 'concurrent', */
    /* modern: true, */
    workerThreads: true,
    pageEnv: true,
    productionBrowserSourceMaps: true,
    optimizeFonts: true,
    optimizeImages: true,
    scrollRestoration: true,
  },
};
```
I'm going to try and reproduce this with the minimal custom configuration (e.g., no experimental flags, no Webpack 5). If I can, I'll create a new GH issue.

Versions:
- `yarn --version`: 2.3.3
- `yarn node --version`: v12.14.1
- React: 17.0.1
- Webpack: 5.4.0
- Next.js: 10.0.1

**Comment by sumanthratna** [comment] 2020-11-10 19:35
> Please try using `next@canary` and let us know if it's fixed!

Hi @Timer—I tried reproducing this issue on canary and it looks this problem has *not* been solved yet.

**Comment by sumanthratna** [comment] 2020-11-18 15:01
the same issue occurs with `reactMode: 'blocking'` on 10.0.2

**Comment by Timer** [comment] 2020-11-18 15:03
Feel free to look into it! Since this is experimental behavior, we probably won't fix it with high priority.

**Comment by sumanthratna** [comment] 2020-11-18 15:55
Wow...I've been playing around with this for a week and I just realized that installing the experimental React build fixes this issue (I assumed that Next.js had a patch for concurrent mode since the rest of the site still worked).

@Timer should I push a PR that adds a warning when users try to use blocking or concurrent mode with a stable React build?

**Comment by shuding** [comment] 2021-07-12 15:46
Hi @sumanthratna I just tested latest `next@canary` with React 18 alpha, and `next/image` works properly. Feel free to reopen if this is still an issue!

**Closed by shuding** 2021-07-12 15:46 UTC
Labels: good first issue, type: experimental

**Comment by balazsorban44** [comment] 2022-01-28 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
