### ISSUE TITLE
Local sub-route with param renders 404 in production app

### ISSUE THREAD

**Issue by gwendall** [vercel/next.js#18397] opened 2020-10-28 16:01 UTC
I have a route with a param (`/src/pages/items/[id].tsx`), and am testing the built-in i18n routing. 

```
// next.config.js
module.exports = {
  i18n: {
    locales: [
      'fr',
      'en-US',
    ],
    defaultLocale: 'fr'
  }
};
```

The app renders correctly the page `/en-US/items/0` in local. However, in production it returns a 404 (app hosted on Vercel). If I navigate to this url from within the app, it works correctly though. It really happens with routes with params, a page `/en-US/items` renders fine.

Is it a bug or I am doing something wrong ?

**Comment by revskill10** [comment] 2020-11-02 19:25
I got the same issue today. Hope this got fixed soon.

**Comment by ijjk** [comment] 2020-11-02 19:44
Hi, can you provide a reproduction showing the unexpected 404? We have tests for i18n and dynamic pages on Vercel which are currently passing as expected.

**Comment by revskill10** [comment] 2020-11-03 09:55
@ijjk I put together the reproducion [here](https://nextjs-locale-dynamic-route.vercel.app/items/1)

The source code is [here](https://github.com/revskill10/nextjs-locale-dynamic-route)

As you see, the `/items/1` link is 404.

**Comment by AliNjie** [comment] 2020-11-04 09:45
Experiencing the same issue. In my case I have the following folder structure `src/pages/company/[companyId].tsx`. Visiting `/company/[companyId]` renders the correct page, but visiting `/company/1` results in a 404.

**Comment by ijjk** [comment] 2020-11-05 19:33
Hi, this should now be corrected, please re-deploy your application and give it a try!

**Comment by gwendall** [comment] 2020-11-05 20:41
Alright, it works now ! Thanks ! 🔥🔥🔥

**Comment by AliNjie** [comment] 2020-11-06 09:24
It seems like this is fixed only for Vercel deployments. I am still experiencing the same issue, running an application with `next start`.

Running `yarn build && yarn start` with [this repro](https://github.com/AliNjie/next-i18n-dynamic-routing) and visiting `/post/1` directly results in a 404, but using the link to `/post/1` from `/` renders the dynamic route.

[The same app deployed to Vercel](https://next-i18n-dynamic-routing.vercel.app/) works as expected.

**Comment by ijjk** [comment] 2020-11-07 18:13
Reopening per @AliNjie

**Closed** 2020-11-08 02:18 UTC
Labels: kind: bug, point: 3

**Comment by ijjk** [comment] 2020-11-09 00:37
This should be corrected for `next start` in the latest canary of Next.js `v10.0.2-canary.5`, please upgrade and give it a try!

**Comment by AliNjie** [comment] 2020-11-09 08:14
Seems to work fine now after upgrading. Thanks 🎉

**Comment by balazsorban44** [comment] 2022-01-29 06:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
