### ISSUE TITLE
Docs: Supporting Next.js App deployment to China #39693

### ISSUE THREAD

**Issue by Moto-Venturer** [vercel/next.js#39825] opened 2022-08-22 15:49 UTC
### What is the improvement or update you wish to see?

I created a PR (https://github.com/vercel/next.js/pull/39228) a couple of weeks **ago about supporting Next.js app deployment for China**, and @leerob mentioned pushing it back on the issue stage, which I did.  

Then, the issue turned into a [discussion](https://github.com/vercel/next.js/discussions/39693). I'm bringing it back around as an Issue again.

### Is there any context that might help us understand?

A quick background brief: Mainland China is unlike any other country. Vercel or Netlify-like deployment solutions don't exist. [Vercel](https://www.21cloudbox.com/solutions/how-to-speed-up-vercel-in-china.html#:~:text=Does%20Vercel%20work%20in%20China%3F) and [Netlify](https://www.21cloudbox.com/solutions/alternatives-to-netlify-in-china.html) don't work out-of-the-box in China due to their Firewall and other legal issues.

21YunBox, created [guides](https://www.21cloudbox.com/solutions/how-to-speed-up-vercel-in-china.html) to make deployment of Next.js apps easy like Vercel for China. If you think this is good conjunction for the Nextjs app in China, I think adding some links on the [next.js docs](https://nextjs.org/docs/deployment) would definitely help oversea developers bridge the gap to get their tech working in China.

Do leave comments here, so I know what you guys think.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/deployment

**Comment by SukkaW** [comment] 2022-08-22 19:58
Stop posting the same content over and over again. Your issue is being turned into a discussion for a reason.

**Comment by ijjk** [comment] 2022-08-22 20:06
Closing per above as this is a duplicate of the discussion https://github.com/vercel/next.js/discussions/39693 which is a valid place for this type of thread.

**Closed by ijjk** 2022-08-22 20:06 UTC
Labels: template: documentation
