### ISSUE TITLE
Reading from "node:fs" is not handled by plugins (Unhandled scheme).

### ISSUE THREAD

**Issue by heart-er** [vercel/next.js#32935] opened 2022-01-01 17:56 UTC
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.10.0

### What browser are you using?

chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Other platform

### Describe the Bug

when i use node-fetch http request in getServerSideProps, next throws error.

This is error information:
 [1] Module build failed: UnhandledSchemeError: Reading from "node:fs" is not handled by plugins (Unhandled scheme).
[1] Webpack supports "data:" and "file:" URIs by default.
[1] You may need an additional plugin to handle "node:" URIs.
[1] Could not find files for /post/[id] in .next/build-manifest.json

### Expected Behavior

Expect no error.

### To Reproduce

none

**Comment by timneutkens** [comment] 2022-01-01 20:46
`fetch` is supported by default. You don't have to install or add `node-fetch` anywhere.

**Comment by balazsorban44** [comment] 2022-01-01 21:45
I believe this might be a duplicate of #28774

**Closed** 2022-01-02 00:08 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-02-01 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
