### ISSUE TITLE
[Docs] Add example for `headers`

### ISSUE THREAD

**Issue by lfades** [vercel/next.js#15073] opened 2020-07-11 00:33 UTC
Documentation for custom routes was released some days ago (https://github.com/vercel/next.js/pull/14887). We should also add one example for every documentation page to better show how it works.

The following three examples are required:

- [x] `rewrites` For [docs/api-reference/next.config.js/rewrites.md](https://github.com/vercel/next.js/blob/canary/docs/api-reference/next.config.js/rewrites.md)
- [x] `redirects` For [docs/api-reference/next.config.js/redirects.md](https://github.com/vercel/next.js/blob/canary/docs/api-reference/next.config.js/redirects.md)
- [x] `headers` For [docs/api-reference/next.config.js/headers.md](https://github.com/vercel/next.js/blob/canary/docs/api-reference/next.config.js/headers.md)

Every example should contain very basic content and focus only on the feature it's about, showing how it works for multiple use cases that are currently not covered by the documentation. After the example is complete, add a link to it at the beginning of the page in docs.

Feel free to open a PR and I'll review it asap.

**Comment by robintom** [comment] 2020-07-15 06:37
Hey @lfades could you assign this to me? I can work on this! :)

**Comment by eKhattak** [comment] 2020-07-20 11:53
@robintom I would love to work on this if you didn't start yet.

**Comment by robintom** [comment] 2020-07-20 15:43
@eKhattak Sorry, i did already start working on it. I will be making a PR soon.

**Comment by lfades** [comment] 2020-07-20 16:45
@robintom If possible please make a PR per example, don't merge all of them on a single one.

**Comment by styfle** [comment] 2021-11-23 18:23
Looks like these are all complete now, closing 👍

**Closed by styfle** 2021-11-23 18:23 UTC
Labels: good first issue, area: examples, area: documentation, kind: story

**Comment by balazsorban44** [comment] 2022-01-27 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
