### ISSUE TITLE
Image component return 404 for images with redirects method in next.config.js

### ISSUE THREAD

**Issue by schriker** [vercel/next.js#18711] opened 2020-11-02 21:47 UTC
# Bug report

## Describe the bug

Image component not creating images with redirects method in next.config.js, if I comment out it, then images works properly. Do I need to add some extra path config to redirects method to make images works?

## To Reproduce

next.config.js

```javascript
module.exports = {
  async redirects() {
    return [
      {
        source: '/',
        destination: '/wonziu',
        permanent: true,
      },
      {
        source: '/favourite/page/1',
        destination: '/favourite',
        permanent: true,
      },
      {
        source: '/:streamer/page/1',
        destination: '/:streamer',
        permanent: true,
      },
      {
        source: '/:streamer/:video',
        destination: '/:streamer/video/:video',
        permanent: true,
      },
    ];
  },
  images: {
    domains: ['assets.vercel.com'],
  },
};
```
## System information

- OS: macOS
- Version of Next.js: 10.0.0
- Version of Node.js: 12.16.1

**Comment by schriker** [comment] 2020-11-02 22:19
It seems like this path is interfering with _next/image path:

```javascript
      {
        source: '/:streamer/:video',
        destination: '/:streamer/video/:video',
        permanent: true,
      },
```

Any tips how to fix this?

**Comment by ijjk** [comment] 2020-11-06 23:08
Hi, this is the expected behavior as redirects occur before filesystem routes like `_next/image`. To prevent the `/:stream/:video` redirect from intercepting the `_next/image `requests you can update the redirect to this:

```js
{
  source: '/:streamer((?!_next)[^\/]+?)/:video',
  destination: '/:streamer/video/:video',
  permanent: true,
}
```

I'm going to close this since it doesn't appear to be a bug in Next.js and the redirect is behaving as it should. Feel free to respond with additional info if you are still encountering problems!

**Closed by ijjk** 2020-11-06 23:08 UTC
Labels: kind: bug

**Comment by balazsorban44** [comment] 2022-01-29 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
