### ISSUE TITLE
Dynamic routes are not being navigated from client side. Links are not clickable but are formed correctly.

### ISSUE THREAD

**Issue by sidreddyinsider** [vercel/next.js#29855] opened 2021-10-13 03:13 UTC
### What version of Next.js are you using?

11.0

### What version of Node.js are you using?

14.17

### What browser are you using?

chrome

### What operating system are you using?

android

### How are you deploying your application?

next start

### Describe the Bug

Application Settings and environment:
We use assetPathPrefix to load our static assets in production.
We load a web-view in our android application to run the application.

Routes:
We have routes as below , 2 are dynamic and 2 are fixes path. None of them have getServerSideProps or getStaticProps and all of them are rendered client side and are served from a web server.

```
/[slug]/search,
/[slug],
/select-city,
/upcoming,
```

Here is the issue we are facing- on our home page all links are well formed but when user is navigating to dynamic routes by clicking the links , they are not clickable. users can click and navigate to fixed path routes.
eg: /movie-title?frmt=2d  ( [slug] route with query param ) - not working.
eg:/movie-title/search ( [slug/]search route ) - not working.
eg: /select-city and /upcoming routes user is able to navigate - working.

**Weirdly this is only happening for few users in production. ( <1% )
For rest of the users everything is working well.**

As our app is loaded in web-view inside an android app, we are not able to debug it. we pushed logs to sentry and can see that urls are being correctly formed.
There is nothing common for the list of users who are facing the issue. In-fact same web-view/android version works well for other users. All users have same web-view settings as it is loaded from inside our android app.

### Expected Behavior

Client side links should work well for all the users in the same way. why should few users get affected here?

### To Reproduce

We are facing this  issue in only few devices < 1 % and we are not able to reproduce ourselves as it working on our local and dev environments.

**Comment by ijjk** [comment] 2021-10-13 03:36
Hi, this sounds related to https://github.com/vercel/next.js/issues/28797 and https://github.com/vercel/next.js/issues/27783 which has a patch applied in `v11.1.3-canary.14` of Next.js, please update to at least that version and give it a try!

**Comment by sidreddyinsider** [comment] 2021-10-14 04:34
We tried this. We had 2 internal users for whom it started working again. For other users it should work is the expectation, we will update you.
But i have a query here.. 
why does it happen repeatedly for  a particular user. This is an in memory thing and it should stop let's say when user kills the app and opens it again ( refresh the webpage ). Why does this random behaviour stop and keeps happening on that device repeatedly and doesnt go away ? @jayphelps @ijjk 

Also this shouldn't be on canary for this long. please release it asap.

**Comment by ijjk** [comment] 2021-11-08 19:47
@sidreddyinsider this could have been occurring on that device due to the conditions causing the timed out prefetches and the cache wasn't busted correctly. The above mentioned patch is now available in a stable release so I'm going to close this.

**Closed by ijjk** 2021-11-08 19:47 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
