### ISSUE TITLE
Unexpected `next/link` behaviour, not redirecting from `not-found.tsx` to home page

### ISSUE THREAD

**Issue by valentinpolitov** [vercel/next.js#49277] opened 2023-05-05 08:32 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.4.0
    Relevant packages:
      next: 13.4.1-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/valentinpolitov/next-link-bug-report

### To Reproduce

1. Create a `not-found.tsx` page in `app` dir
2. Write a `Link` to homepage 
```ts
// app/not-found.tsx

import Link from "next/link";

export default function NotFoundPage() {
  return (
    <>
      <h1>404 Not found</h1>
      <Link href="/">Go home</Link>
    </>
  );
}
```

3. Navigate to any unexisting page, ex: `http://localhost:3000/bad`
4. Click the link

### Describe the Bug

Link component doesn't work in `not-found.js` page, routing doesn't happen. 
Same applies to any unexisting routes all over app, ex: in some page make a link to unexisting route

```ts
// app/page.tsx

import Link from "next/link";

export default function Home() {
  return (
    <>
      <Link href="/good">Link to good page</Link> // this works
      <br />
      <Link href="/bad">Link to bad page</Link> // this doesn't
    </>
  );
}


// app/good/page.tsx

import Link from "next/link";

export default function GoodPage() {
  return (
    <>
      <h1>Good page</h1>
      <Link href="/">Go home</Link> // this works as well
    </>
  );
}

```

### Expected Behavior

Routing should happen

### Which browser are you using? (if relevant)

Chrome 112.0.5615.137 (Official Build) (arm64)

**Comment by jonathatargino** [comment] 2023-05-05 20:11
Same here. When i try to go homepage by clicking a button in not-found page, the url reloads, but the page dont.

**Comment by nicholas5538** [comment] 2023-05-06 10:10
This has been an issue since they released `not-found.tsx` in 13.3.x. Let's give them some time to resolve this issue.

**Comment by timneutkens** [comment] 2023-05-09 18:54
Duplicate of #47862

**Closed by timneutkens** 2023-05-09 18:54 UTC
Labels: template: bug, area: Routing, area: app
