### ISSUE TITLE
Bad pnpm fix makes using preact impossible

### ISSUE THREAD

**Issue by JonathanWolfe** [vercel/next.js#31551] opened 2021-11-17 19:29 UTC
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Firefox

### What operating system are you using?

macoS

### How are you deploying your application?

next start

### Describe the Bug

Error during webpack compile
```
❯ npm run dev

> marketing-next@0.1.0 dev
> next dev -p 8088

ready - started server on 0.0.0.0:8088, url: http://localhost:8088
Error: Cannot find module 'scheduler/package.json'
Require stack:
- /Users/jonwolfe/repos/marketing/app/node_modules/next/dist/build/webpack-config.js
- /Users/jonwolfe/repos/marketing/app/node_modules/next/dist/server/dev/hot-reloader.js
- /Users/jonwolfe/repos/marketing/app/node_modules/next/dist/server/dev/next-dev-server.js
- /Users/jonwolfe/repos/marketing/app/node_modules/next/dist/server/next.js
- /Users/jonwolfe/repos/marketing/app/node_modules/next/dist/server/lib/start-server.js
- /Users/jonwolfe/repos/marketing/app/node_modules/next/dist/cli/next-dev.js
- /Users/jonwolfe/repos/marketing/app/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.mod._resolveFilename (/Users/jonwolfe/repos/marketing/app/node_modules/next/dist/build/webpack/require-hook.js:171:28)
    at Function.Module._resolveFilename (/Users/jonwolfe/repos/marketing/app/node_modules/module-alias/index.js:49:29)
    at Function.resolve (internal/modules/cjs/helpers.js:99:19)
    at getPackagePath (/Users/jonwolfe/repos/marketing/app/node_modules/next/dist/build/webpack-config.js:543:41)
    at Object.getBaseWebpackConfig [as default] (/Users/jonwolfe/repos/marketing/app/node_modules/next/dist/build/webpack-config.js:561:9)
    at async Promise.all (index 0)
    at async Span.traceAsyncFn (/Users/jonwolfe/repos/marketing/app/node_modules/next/dist/trace/trace.js:74:20)
    at async Span.traceAsyncFn (/Users/jonwolfe/repos/marketing/app/node_modules/next/dist/trace/trace.js:74:20)
    at async HotReloader.start (/Users/jonwolfe/repos/marketing/app/node_modules/next/dist/server/dev/hot-reloader.js:325:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jonwolfe/repos/marketing/app/node_modules/next/dist/build/webpack-config.js',
    '/Users/jonwolfe/repos/marketing/app/node_modules/next/dist/server/dev/hot-reloader.js',
    '/Users/jonwolfe/repos/marketing/app/node_modules/next/dist/server/dev/next-dev-server.js',
    '/Users/jonwolfe/repos/marketing/app/node_modules/next/dist/server/next.js',
    '/Users/jonwolfe/repos/marketing/app/node_modules/next/dist/server/lib/start-server.js',
    '/Users/jonwolfe/repos/marketing/app/node_modules/next/dist/cli/next-dev.js',
    '/Users/jonwolfe/repos/marketing/app/node_modules/next/dist/bin/next'
  ]
}
```
caused by: a1e76fb96678b0ac3d7a74c28d2d005516ef1cc0

Needs `try/catch`es added for error handling

Probably also causes #31538

### Expected Behavior

`next dev` does not fail.

### To Reproduce

`package.json`:
```json
{
  "dependencies": {
    "next": "12.0.2",
    "next-plugin-preact": "^3.0.6",
    "preact": "^10.5.15",
    "preact-render-to-string": "^5.1.19",
    "preact-ssr-prepass": "^1.2.0",
    "react": "npm:@preact/compat@^17.0.3",
    "react-dom": "npm:@preact/compat@^17.0.3",
    "react-ssr-prepass": "npm:preact-ssr-prepass@^1.2.0",
  }
}
```

`next.config.js`:
```js
const withPreact = require('next-plugin-preact');

/** @type { import('next').NextConfig } */;
const config = {
    reactStrictMode: true,
};

module.exports = withPreact(config);
```

**Comment by Shashi-GS** [comment] 2021-11-18 10:33
I am also facing the same issue.

**Comment by groenborg** [comment] 2021-11-18 19:45
Same here

**Comment by SentoxAIO** [comment] 2021-12-05 17:44
@JonathanWolfe were you able to fix this?

**Comment by JonathanWolfe** [comment] 2021-12-05 17:58
> @JonathanWolfe were you able to fix this?

@SentoxAIO No, I just set an exact version in my package.json to 12.0.3

**Comment by meck93** [comment] 2022-01-12 10:29
@SentoxAIO and @JonathanWolfe have you seen the temporary workaround: https://github.com/vercel/next.js/issues/31240#issuecomment-991906109

I used `npm i --save-dev scheduler` and it works fine.

**Comment by balazsorban44** [comment] 2022-01-23 23:07
Duplicate of #31240

**Closed by balazsorban44** 2022-01-23 23:07 UTC
Labels: template: bug, area: Yarn PnP / pnpm
