### ISSUE TITLE
client_secret property wrong casing error

### ISSUE THREAD

**Issue by znwhite** [vercel/next.js#26030] opened 2021-06-12 04:00 UTC
### What example does this report relate to?

with-stripe-typescript

### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

12.18.3

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

not deployed yet

### Describe the Bug

In the `<ElementsForm />` component please change `response.client_secret` to `response.clientSecret` because that is the casing that the API handler sends with its response. It creates an error immediately and requires logging the response before realizing that the reason your client secret is `undefined` is because of this casing issue.

### Expected Behavior

For the client secret to not be `undefined` and be passed through the `handleSubmit` function without issue.

### To Reproduce

Just run the project locally and try to submit a test payment.

**Comment by darshkpatel** [comment] 2021-06-29 06:27
I tried to log `response.client_secret` to reproduce the issue and it was successfully logged and isn't undefined
<img width="860" alt="Screenshot 2021-06-29 at 11 54 05 AM" src="https://user-images.githubusercontent.com/11258286/123747550-b7993380-d8d0-11eb-8f1f-4e9929520f4c.png">

I believe the client secret isn't picked up from the environment file ( did create a `.env.local` file ? ), can you give it another shot? / provide more detailed reproduction steps to reproduce the issue

**Comment by ijjk** [comment] 2021-09-21 05:06
Closing per above as this seems to be working correctly in the latest version of Next.js `v11.1.2`

**Closed by ijjk** 2021-09-21 05:06 UTC
Labels: type: example, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
