### ISSUE TITLE
Error: Cannot find module webpack

### ISSUE THREAD

**Issue by HT-Moh** [vercel/next.js#52539] opened 2023-07-11 09:43 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 7.12.1
    Relevant Packages:
      next: 13.4.9
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
---------

    Operating System:
      Platform: linux
      Arch: x64
      Version: #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 7.12.1
    Relevant Packages:
      next: 13.4.10-canary.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

No need

### To Reproduce

use nextjs version 13.4.9 or later, install "next-pwa", change next.config.js to use next-pwa

downgrading to `"next": "13.4.7"` without ^ it works

### Describe the Bug

step run `yarn run dev`

```
Error: Cannot find module 'webpack'
Require stack:
- /home/bicatalyst/src/BiCatalyst/node_modules/workbox-webpack-plugin/build/generate-sw.js
- /home/bicatalyst/src/BiCatalyst/node_modules/workbox-webpack-plugin/build/index.js
- /home/bicatalyst/src/BiCatalyst/node_modules/next-pwa/index.js
- /home/bicatalyst/src/BiCatalyst/next.config.js
```

Same issues as here https://github.com/vercel/next.js/issues/21679 
The issue with all nextjs versions starting from 13.4.7
Rolling back to `13.4.4` fixes the issue

### Expected Behavior

it should just work

**Comment by balazsorban44** [comment] 2023-07-11 11:11
Duplicate of #52366 please add your (minimal) reproduction there, thanks!

**Closed by balazsorban44** 2023-07-11 11:11 UTC
Labels: template: bug
