### ISSUE TITLE
Image 组件  height不生效

### ISSUE THREAD

**Issue by ParkerTzh** [vercel/next.js#50363] opened 2023-05-26 04:04 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Education
    Binaries:
      Node: 18.12.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.1
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/headless-platform-o4cy66?file=%2Fapp%2Fpage.tsx%3A10%2C1

### To Reproduce

```js  {
                        imgsPath.map(item => <div className="max-h-72">
                            <Image className="mt-6 rounded-lg grid-cols-6 mx-auto"
                                   src={item}
                                   key={item}
                                   width="300"
                                   height="300"
                             alt=""/>
                        </div>)
                    }`

### Describe the Bug

```js  {
                        imgsPath.map(item => <div className="max-h-72">
                            <Image className="mt-6 rounded-lg grid-cols-6 mx-auto"
                                   src={item}
                                   key={item}
                                   width="300"
                                   height="300"
                             alt=""/>
                        </div>)
                    }`

### Expected Behavior

直接用，没生效呀

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

next dev

**Comment by JesseKoldewijn** [comment] 2023-05-26 09:56
And what is the issue supposed to be if I may ask?

**Comment by JesseKoldewijn** [comment] 2023-05-26 09:59
One of the things that might cause issues is that you're iterating over an array and returning a div without a key prop. Prob not the issue at hand if any but I'd like to know what the problem seems to be here 😉

**Comment by ParkerTzh** [comment] 2023-05-26 10:04
> One of the things that might cause issues is that you're iterating over an array and returning a div without a key prop. Prob not the issue at hand if any but I'd like to know what the problem seems to be here 😉
> 
> The key needs to be on the div not on the image.

yeah, I'm Improper operation, but do not affect height failure~ 
Is older release Cause problems?

**Comment by JesseKoldewijn** [comment] 2023-05-26 10:06
> > One of the things that might cause issues is that you're iterating over an array and returning a div without a key prop. Prob not the issue at hand if any but I'd like to know what the problem seems to be here 😉
> > The key needs to be on the div not on the image.
> 
> yeah, I'm Improper operation, but do not affect height failure~ Is older release Cause problems?

?
What is the issue then? Since there is basically no description.

**Comment by ParkerTzh** [comment] 2023-05-26 10:08
> 

use Image components,  property width is take effect, but height is invalid.

**Comment by JesseKoldewijn** [comment] 2023-05-26 10:12
Have a read through this, since as far as I know its currently intended behavior.
https://github.com/vercel/next.js/issues/18413 <- other issue regarding the same description
https://stackoverflow.com/questions/74700296/nextjs-image-not-using-the-height-value <- other workaround

**Comment by ParkerTzh** [comment] 2023-05-26 10:15
> Have a read through this, since as far as I know its currently intended behavior. #18413 <- other issue regarding the same description https://stackoverflow.com/questions/74700296/nextjs-image-not-using-the-height-value <- other workaround

okay~ Although it can solve the problem, it is not fundamental, but thank you for your help

**Comment by JesseKoldewijn** [comment] 2023-05-26 10:21
> 

Not fundamental in what way? As you can see on that previous issue and stackoverflow question this has been the expected behavior for quite a while now?

**Comment by JesseKoldewijn** [comment] 2023-05-26 10:28
Please also refer to the docs where there before mentioned behavior is also described as expected:
https://nextjs.org/docs/pages/building-your-application/optimizing/images

**Comment by shuding** [comment] 2023-05-27 11:52
Closing as the reason that @promer94 mentioned. Also you can take a look at this part in the docs:

> The width and height attributes are used to infer the correct aspect ratio of image and avoid layout shift from the image loading in. The width and height do not determine the rendered size of the image file

**Closed by shuding** 2023-05-27 11:52 UTC
Labels: template: bug
