### ISSUE TITLE
Experimental nested catch all routes don't work and workaround doesn't either

### ISSUE THREAD

**Issue by nicholaschiang** [vercel/next.js#13620] opened 2020-05-31 22:08 UTC
# Bug report

## Describe the bug

We need the optional catch all route `/[locale]/search/[[...slug]].tsx` to be able to:
- Show the search view at `/en/search`.
- Show the search view with a selected user at `/en/search/USER_ID` (the "user view" is just a dialog that opens when a search result is clicked).

But nesting a catch all route isn't currently supported (even though it's not explicitly stated in [the documentation](https://nextjs.org/docs/routing/dynamic-routes) that you can't do it), so our workaround was to create two pages:
1. The search view (without a user selected) at `src/pages/[locale]/search/index.tsx`.
2. The user view (the search view with a user selected) at `src/pages/[locale]/search/[user].tsx`.

The code in those two pages is identical (with the search view code just ignoring the fact that there isn't a user selected). So, we define the pages in a separate file (in `src/search/page.tsx`) and re-export it from the page files like so (note that we're using the Typescript `baseUrl` and `paths` options to map `@tutorbook/*` to `src/*`):
```tsx
export * from '@tutorbook/search/page';
```

But that results in messed up tree shaking and [your `next-ssg-transform` plugin](https://github.com/vercel/next.js/blob/canary/packages/next/build/babel/plugins/next-ssg-transform.ts) isn't able to remove the server-side only code that's used in the `getServerSideProps` function exported from `@tutorbook/search/page` and re-exported from `pages/[locale]/search/index.tsx`. So we're left with the following (expected) error:
```
Module not found: Can't resolve 'child_process' in '/home/nchiang/repos/tutorbook/node_modules/google-auth-library/build/src/auth'
```
When the `getServerSideProps` function is defined directly in the page (i.e. in `pages/[locale]/search/index.tsx` and again in `pages/[locale]/search/[user].tsx`) it works fine.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone [this public repository](https://github.com/tutorbookapp/tutorbook).
2. Checkout to the `develop` branch by running:
```
$ cd tutorbook/ && git checkout develop && git pull
```
3. Install our dependencies and start a development server by running the following (in the root of the repository):
```
$ npm i && npm run dev
```
4. Open up http://0.0.0.0:3000/en/search/ or http://0.0.0.0:3000/en/search/dv90ZS4zKFWWda296t2GuHQ9VRf1`.
5. See error.

## Expected behavior

1. Update [this documentation](https://nextjs.org/docs/routing/dynamic-routes) to make it explicit that you do not support nested catch all routes (e.g. `/[locale]/search/[[...slug]].tsx`).
2. Fix [the `next-ssg-transform` plugin](https://github.com/vercel/next.js/blob/canary/packages/next/build/babel/plugins/next-ssg-transform.ts) so that it removes the server-side only imports from re-exported `getServerSideProps` functions.

## System information

- OS: Ubuntu 18.04.2
- Version of Next.js: 9.4.0
- Version of Node.js: 12.16.1

## Additional context

Current workaround is just to literally copy the same code into both page files (i.e. `src/pages/[locale]/search/index.tsx` and `src/pages/[locale]/search/[user].tsx` are exactly the same).

**Comment by svenheden** [comment] 2020-06-01 09:57
Got bitten by this bug as well. Wasn't aware that it was experimentel. Does it say that anywhere in [the docs](https://nextjs.org/docs/routing/dynamic-routes#optional-catch-all-routes)?

**Comment by Janpot** [comment] 2020-06-01 17:30
@nicholaschiang I see you're using v9.4.0. Optional catch-all routes were added in version 9.4.2. Keep in mind that this feature is still experimental and needs to be enabled explicitly by adding
```js
// ./next.config.js
module.exports = { 
  experimental: {
    optionalCatchAll: true 
  }
}
```

**Comment by nicholaschiang** [comment] 2020-06-08 16:46
Thanks @Janpot that addresses my first issue here.

However, that second issue (with the `next-ssg-transform` plugin) still seems to be valid so I'm keeping this issue open.

**Comment by Timer** [comment] 2020-06-08 18:09
Closing in favor of #13906

**Closed by Timer** 2020-06-08 18:09 UTC
Labels: kind: bug

**Comment by balazsorban44** [comment] 2022-01-30 02:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
