### ISSUE TITLE
SSR cache example doesn't work

### ISSUE THREAD

**Issue by xitter** [vercel/next.js#12019] opened 2020-04-19 10:02 UTC
# Bug report
Example https://github.com/zeit/next.js/blob/canary/examples/ssr-caching is broken.

## Describe the bug
There are two problems with this app:
1. `http://localhost:3000/blog/first` gives 404 page. This seems to be a problem with queryParam.
2.  If I fix 1st error, `http://localhost:3000/blog/first` will return correct blog page but prints following on server console:
```
(node:95446) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at /codes/ssr/ssr-caching-app/node_modules/cacheable-response/index.js:40:9
    at /codes/ssr/ssr-caching-app/node_modules/cacheable-response/index.js:108:5
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:95446) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```
It seems that `renderToHTML` executes end command on the response and cacheable-response tries to add header after this.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://github.com/zeit/next.js/tree/canary/examples/ssr-caching
2. Follow steps to setup app.
3. Run `yarn dev`
4. Go to: `http://localhost:3000/blog/first`
5. 404 page is returned.

## Expected behavior
Blog page should have been returned with no error.

## System information

- OS: macOS
- Version of Next.js: 9.3
- Version of Node.js: 10

**Comment by HaNdTriX** [comment] 2020-04-19 16:59
@timneutkens  seems like `app.renderToHTML` is actually calling `res.end`. 

https://github.com/zeit/next.js/blob/86236bc76bcfc69b4e704f06be5b29cda3c1908c/packages/next/next-server/server/send-payload.ts#L49

**Call Stack:**

-`Object.sendPayload`
- `DevServer.renderToHTMLWithComponents`
- `DevServer.renderToHTML`

**Duplicate of:** #11665, #12019

**Comment by fmihal** [comment] 2020-04-19 19:17
@timneutkens @HaNdTriX I can try to investigate this one?

**Comment by leanazulyoro** [comment] 2020-04-20 18:56
This is a hack, I believe the method `app.renderToHTML` should return the renderedHTML, but in the meanwhile, this is working for me using LRU cache:
https://gist.github.com/leanazulyoro/23c6581fb4379ec311e3bc8538715687

**Comment by xitter** [comment] 2020-04-21 09:05
@HaNdTriX @timneutkens to be backward compatible, a flag could be added to not call `sendPayload` and always return html. I can raise a PR for that.

**Comment by mydearxym** [comment] 2020-05-19 04:04
as https://github.com/zeit/next.js/issues/11665 mentioned, the `ERR_HTTP_HEADERS_SENT ` start at v9.3.1, downgrade to next@9.3.0 fix this warning temporary

**Comment by mohitsakhuja** [comment] 2020-05-30 20:09
Any updates on this? I can try to raise a PR for it and fix it, but would like to know the approach that we want to go with.

**Comment by lauriskuznecovs** [comment] 2021-06-10 06:06
I got it working with this:

**server.js**
```
const cacheableResponse = require('cacheable-response')
const express = require('express')
const next = require('next')

const port = parseInt(process.env.PORT, 10) || 3000
const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })

const handle = app.getRequestHandler()

const ssrCache = cacheableResponse({
  ttl: 1000 * 60, // 1 minute
  getKey: ({ req }) => `${req.url}`,
  get: async ({ req, res, path, query }) => {
    const data = await app.renderToHTML(req, res, path, query)

    // Add here custom logic for when you do not want to cache the page, for
    // example when the page returns a 404 status code:
    if (res.statusCode === 404) {
      res.end(data)
      return
    }

    return { data }
  },
  send: ({ data, res }) => res.send(data)
})

app.prepare().then(() => {
  const server = express()

  server.get('/', (req, res) => ssrCache({ req, res, path: req.path, query: req.query, }))

  server.get('/blog/:id', (req, res) => ssrCache({ req, res, path: req.path, query: req.query, }))

  server.get('*', (req, res) => handle(req, res))

  server.listen(port, (err) => {
    if (err) throw err
    console.log(`> Ready on http://localhost:${port}`)
  })
})
```

**Closed** 2021-06-23 18:27 UTC
Labels: good first issue

**Comment by balazsorban44** [comment] 2022-01-28 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
