### ISSUE TITLE
Postcss-resolve-url: postcss.plugin was deprecated

### ISSUE THREAD

**Issue by JameelKhan9** [vercel/next.js#32157] opened 2021-12-06 05:49 UTC
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next dev, next build

### Describe the Bug

Afer upgrading from 12.0.4 to 12.0.7, the following message appears when `yarn dev` or `yarn build && yarn start`:
```
postcss-resolve-url: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
```

### Expected Behavior

The deprecation warning does not show.

### To Reproduce

1. checkout `next.js/examples/with-next-sass` greater than 12.0.4
2. Run `yarn`
3. Run `yarn dev`
```sh
$ > yarn dev                  
yarn run v1.22.17
$ next
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
postcss-resolve-url: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
event - compiled client and server successfully in 1448 ms (171 modules)
```

**Comment by timneutkens** [comment] 2021-12-06 12:36
Related to #31762. This is just a warning and will not affect running your app so it's safe to ignore until it's fixed in Next.js.

**Comment by tonytoth** [comment] 2021-12-06 12:45
@timneutkens it is affecting the application.
<img width="966" alt="Screenshot 2021-12-06 at 14 43 20" src="https://user-images.githubusercontent.com/8457868/144848123-193803a0-f056-4cfe-9de3-b0aede9fd9ab.png">

**Comment by brc-dd** [comment] 2021-12-06 13:16
@tonytoth Your error is different from what JameelKhan9 wrote. Also, it is not reproducible by the steps given by them. Please provide a minimal, reproducible example. Next.js is already using `postcss@8.2.15`, so the error in your case most probably has to do something with your own setup.

**Comment by ZauJulio** [comment] 2021-12-13 18:34
Same error: 
![image](https://user-images.githubusercontent.com/49128655/145867891-4eedfdba-f32b-47fe-a7db-77b9a68f36e6.png)

I recently found using sass...
I don't remember seeing it before version "12.0.7".
Projects before version 12.0.4 are ok

In other projects, in the same version of nextjs, with Chakra-ui and styled-components I didn't find this error.

**Closed** 2022-01-02 22:16 UTC
Labels: kind: bug, area: Compiler

**Comment by balazsorban44** [comment] 2022-02-01 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
