### ISSUE TITLE
Nested/Scoped `App` component for shared logic in `pages` subfolders

### ISSUE THREAD

**Issue by narciero** [vercel/next.js#14898] opened 2020-07-06 23:15 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

It would be great to be able to define multiple `_app.js` (`App` components) in the `pages` hierarchy that would allow for wrapping all pages in that folder. For example, take a site that has an `admin` section that is restricted based on user role...currently it's quite verbose to have to perform the authorization check on every page, it'd be great to be able to define `pages/admin/_app.js` that would contain the shared logic for pages in `pages/admin/**/*`.

## Describe the solution you'd like

The ability to define `_app.js` in any `pages` subfolder that would apply (recursively) to all pages in that tree (just like how the current `pages/_app.js` applies to every page).

<img width="150" alt="Screen Shot 2020-07-06 at 5 10 15 PM" src="https://user-images.githubusercontent.com/9964211/86664052-934f9300-bfab-11ea-9cee-390789bad338.png">

## Describe alternatives you've considered

Currently I wrap every page in the `pages/admin` folder with a HOC component that does the authorization/role check. This becomes tedious and easy to forget especially with sites with more than one "admin" section.

## Additional context

This is supported in CRA using nested routes with `react-router`.

**Comment by timneutkens** [comment] 2020-07-07 11:15
Duplicate of #8193

**Closed by timneutkens** 2020-07-07 11:15 UTC

**Comment by balazsorban44** [comment] 2022-01-29 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
