### ISSUE TITLE
Next js <Image> tag with url at build time Fails to load the image

### ISSUE THREAD

**Issue by lokesh14v** [vercel/next.js#20560] opened 2020-12-29 04:08 UTC
NextJs  tag with CDN URL gives 404 after the production build is taken

"next": "^10.0.3",

<img width="1142" alt="Screenshot 2020-12-28 at 1 10 19 PM" src="https://user-images.githubusercontent.com/26504161/103258001-6ba21c00-498b-11eb-9527-9700fa447d61.png">

**Comment by mylastore** [comment] 2020-12-29 04:46
same here 
`https://defaultseo.com/_next/image?url=https%3A%2F%2Fpapaslive.com%2Fseo-default.webp&w=768&q=75`

**Comment by tminhduc2811** [comment] 2020-12-29 06:43
> same here but this is happening for me when I run production mode and if I visit the image url directly I see the image
> `https://papaslive.com/seo-default.webp`
> 
> `https://defaultseo.com/_next/image?url=https%3A%2F%2Fpapaslive.com%2Fseo-default.webp&w=768&q=75`

Did you include your external domain in the next.config.js?

**Comment by lokesh14v** [comment] 2020-12-29 10:32
> > same here but this is happening for me when I run production mode and if I visit the image url directly I see the image
> > `https://papaslive.com/seo-default.webp`
> > `https://defaultseo.com/_next/image?url=https%3A%2F%2Fpapaslive.com%2Fseo-default.webp&w=768&q=75`
> 
> Did you include your external domain in the next.config.js?

Yes, I have included the **domain** in the config file. Even though while I take the production build and run the app this URL gives 404.

**Comment by lokesh14v** [comment] 2020-12-29 10:33
> > > same here but this is happening for me when I run production mode and if I visit the image url directly I see the image
> > > `https://papaslive.com/seo-default.webp`
> > > `https://defaultseo.com/_next/image?url=https%3A%2F%2Fpapaslive.com%2Fseo-default.webp&w=768&q=75`
> > 
> > 
> > Did you include your external domain in the next.config.js?
> 
> Yes, I have included the **domain** in the config file. Even though while I take the production build and run the app this URL gives 404.

And am using a custom server .

**Comment by rishi-raj-jain** [comment] 2020-12-29 18:19
I think the documentation says that only 3 providers are supported yet..

**Comment by mylastore** [comment] 2020-12-29 20:17
> > same here but this is happening for me when I run production mode and if I visit the image url directly I see the image
> 
> > `https://papaslive.com/seo-default.webp`
> 
> > 
> 
> > `https://defaultseo.com/_next/image?url=https%3A%2F%2Fpapaslive.com%2Fseo-default.webp&w=768&q=75`
> 
> 
> 
> Did you include your external domain in the next.config.js? 

Yes I did

**Comment by mylastore** [comment] 2020-12-29 20:18
> I think the documentation says that only 3 providers are supported yet..

What do you mean?

**Comment by rishi-raj-jain** [comment] 2020-12-29 20:58
So, https://nextjs.org/docs/basic-features/image-optimization#loader says that only 3 cdns' are supported yet.. If you're using vercel hosting then it should d be fine.

**Comment by mylastore** [comment] 2020-12-29 21:50
> So, https://nextjs.org/docs/basic-features/image-optimization#loader says that only 3 cdns' are supported yet.. If you're using vercel hosting then it should d be fine.

Got it, thanks

**Comment by lokesh14v** [comment] 2020-12-30 06:30
> So, https://nextjs.org/docs/basic-features/image-optimization#loader says that only 3 cdns' are supported yet.. If you're using vercel hosting then it should be fine.

so on vercel hosting if we have other CDN apart from those 3 then it will work?

**Comment by wedneyyuri** [comment] 2021-01-06 19:19
@lokesh14v there is a PR to support custom loaders: https://github.com/vercel/next.js/pull/20216

**Comment by timneutkens** [comment] 2021-01-07 09:40
> same here but this is happening for me when I run production mode and if I visit the image url directly I see the image
> `https://papaslive.com/seo-default.webp`
> 
> `https://defaultseo.com/_next/image?url=https%3A%2F%2Fpapaslive.com%2Fseo-default.webp&w=768&q=75`

Looking at the error shown `"url" parameter is not allowed` that happens when you don't have the correct hostname set up in the `domains` configuration. Make sure you add `papaslive.com`.

> I think the documentation says that only 3 providers are supported yet..

You're missing an important note in the docs: `Default: Works automatically with next dev, next start, or a custom server` by default image optimization works on `next start` and `next dev`.

> NextJs tag with CDN URL gives 404 after the production build is taken

As for the initial issue, it does not follow the issue template so it's practically impossible to help/investigate this issue, hence why I'm going to close this issue.

**Closed by timneutkens** 2021-01-07 09:40 UTC
Labels: template: bug

**Comment by lokesh14v** [comment] 2021-01-07 13:30
> > same here but this is happening for me when I run production mode and if I visit the image url directly I see the image
> > `https://papaslive.com/seo-default.webp`
> > `https://defaultseo.com/_next/image?url=https%3A%2F%2Fpapaslive.com%2Fseo-default.webp&w=768&q=75`
> 
> Looking at the error shown `"url" parameter is not allowed` that happens when you don't have the correct hostname set up in the `domains` configuration. Make sure you add `papaslive.com`.
> 
> > I think the documentation says that only 3 providers are supported yet..
> 
> You're missing an important note in the docs: `Default: Works automatically with next dev, next start, or a custom server` by default image optimization works on `next start` and `next dev`.
> 
> > NextJs tag with CDN URL gives 404 after the production build is taken
> 
> As for the initial issue, it does not follow the issue template so it's practically impossible to help/investigate this issue, hence why I'm going to close this issue.

Hi, @timneutkens using <image> tag in next js and if we take the prod build. The URL mapping fails but in the dev build I was woking. Is that issue resolved in 10.0.5?

**Comment by samkahchiin** [comment] 2021-01-12 05:04
> > > same here but this is happening for me when I run production mode and if I visit the image url directly I see the image
> > > `https://papaslive.com/seo-default.webp`
> > > `https://defaultseo.com/_next/image?url=https%3A%2F%2Fpapaslive.com%2Fseo-default.webp&w=768&q=75`
> > 
> > 
> > Looking at the error shown `"url" parameter is not allowed` that happens when you don't have the correct hostname set up in the `domains` configuration. Make sure you add `papaslive.com`.
> > > I think the documentation says that only 3 providers are supported yet..
> > 
> > 
> > You're missing an important note in the docs: `Default: Works automatically with next dev, next start, or a custom server` by default image optimization works on `next start` and `next dev`.
> > > NextJs tag with CDN URL gives 404 after the production build is taken
> > 
> > 
> > As for the initial issue, it does not follow the issue template so it's practically impossible to help/investigate this issue, hence why I'm going to close this issue.
> 
> Hi, @timneutkens using next js Image component and if we take the prod build, the URL mapping fails but on the dev build it was working fine. Is that issue resolved in next:10.0.5?

I have the same issues and would like to know the solutions for this.  @timneutkens 
I can't get the image loaded if I am running the build file but local is working fine.

**Comment by balazsorban44** [comment] 2022-01-28 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
