### ISSUE TITLE
does not compile material-ui correctly

### ISSUE THREAD

**Issue by tylerthehaas** [vercel/next.js#11297] opened 2020-03-23 16:35 UTC
# Bug report

![image](https://user-images.githubusercontent.com/11150235/77339021-ccac0d80-6cf0-11ea-9761-44d856140b0f.png)

## Describe the bug

Material-UI uses popper.js for all of its popovers. When these are used inside next we are getting the above error. This seems to be an issue with how next has its compilation setup. When I do the same code in a create react app setup I do not have this issue.
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

https://github.com/tylerthehaas/test-autocomplete-nextjs

1. run app
2. click in search input
3. See error in console

for comparison here is the same code inside a create react app

https://github.com/tylerthehaas/test-autocomplete-cra

## Expected behavior

Expect it to be able to run without import errors.

## Screenshots

see above

## System information

- OS: macOS 10.14.2
- Browser (if applies) chrome
- Version of Next.js: 9.3.1

**Comment by timneutkens** [comment] 2020-03-24 09:11
cc @oliviertassinari

**Comment by oliviertassinari** [comment] 2020-03-24 09:17
I couldn't reproduce on my env.

**Comment by oliviertassinari** [comment] 2020-03-24 09:19
@tylerthehaas Could you setup a live reproduction with codesandbox?

**Comment by zhe** [comment] 2020-03-24 14:54
I tried to reproduce too, I couldn't see errors in the console.

Although, when `npm install`, some messages appeared:
```
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
```
and 
```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@octanner%2fprism-core - Not found
npm ERR! 404
npm ERR! 404  '@octanner/prism-core@^0.1.6' is not in the npm registry.
```
Run without `@octanner/prism-core`.

Hope it's helpful.

**Comment by tylerthehaas** [comment] 2020-03-24 14:54
I tried but codesandbox had issues with running in codesandbox. I did put this in a docker container and it works fine there. You're right its something with my local environment that got in a bad state somehow. Thanks for all your help. Just wanted to take a minute to say thank you for all your work with material-ui. It is providing incredible value for us.

**Comment by Shivendra30** [comment] 2020-03-30 01:18
Tried to run it on my machine. No errors in the console. 

Although yes, as @zhe said, I removed `@octanner/prism-core` since I got this error

`
Error: https://npm.pkg.github.com/download/@octanner/prism-core/0.1.6/399cd5ecb9ec62c801391e2c2330951fac8b567277d72e573cf8620bd5a4fc89: Request failed "401 Unauthorized"
      at ResponseError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js:696:66)
      at new ResponseError (/usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js:802:124)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js:66900:16)
      at Request.emit (events.js:198:13)
      at Request.module.exports.Request.onRequestResponse (/usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js:141341:10)
      at ClientRequest.emit (events.js:203:15)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
      at TLSSocket.socketOnData (_http_client.js:442:20)
      at TLSSocket.emit (events.js:198:13)

`

Try removing it from your `package.json` file and then run the app maybe

**Comment by tylerthehaas** [comment] 2020-03-30 01:21
This is something where next must be in a bad state somehow. It only happens on my machine. prism-core is just a wrapper around material-ui. Thats not causing the error. Its something else.

**Comment by oliviertassinari** [comment] 2020-03-30 07:36
@tylerthehaas I had to remove `prism-core` from the dependency list because it's private. It sounds like you should look into it his direction.

**Comment by tylerthehaas** [comment] 2020-04-01 01:45
no that isn't the problem. Thats a library I maintain for work under my employers private registry. the same issue happens even without that included in the package.json. I believe this to be a problem with some global thing that is affecting next in a weird way on my machine. I have tried this on multiple computers so I don't know if somehow both of my computers were affected by this somehow. I can confirm that this doesn't happen in a linux environment as when I run it in a docker container it resolves the problem. The problem is exibited on both of my macbook pros however.

**Comment by sauhard98** [comment] 2020-06-02 11:21
@tylerthehaas I had recently faced the same issue with popper and I removed the lock file and updated my dependencies. Try updating the version of @material-ui/core.(Also You might want to remove the node_modules). It works in my machine without any errors (both npm and yarn). 
Also, you should avoid committing the yarn.lock file.

- OS: macOS 10.14.2
- Browser: chrome

**Comment by Timer** [comment] 2020-09-12 04:56
Closing as users above said this cannot be reproduced.

**Closed by Timer** 2020-09-12 04:56 UTC
Labels: good first issue

**Comment by balazsorban44** [comment] 2022-01-29 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
