### ISSUE TITLE
Lighthouse reports me that an <Image> is the Largest Contentful Paint element because it takes 4.6s to load

### ISSUE THREAD

**Issue by aresrioja10** [vercel/next.js#20567] opened 2020-12-29 11:06 UTC
# Bug report

## Describe the bug

Lighthouse is lowering my score in mobile because my hero image takes 4.6s to load (in desktop it takes 1.2s). I'm trying to preload the image but it doesn't work.

## To Reproduce

Use this example code to load a hero image:

```javascript
<Image
 src={data.mediaItemUrl}
 layout="fill"
 priority={true}
 loader="eager"
 objectFit="cover"
 quality={90}
/>
```

## Expected behavior

The image is optimized so it should render faster. Also, as it uses the priority attribute it should preload the image.

## Screenshots

![Captura de pantalla 2020-12-29 a las 12 05 55](https://user-images.githubusercontent.com/3605582/103279501-3bc83800-49ce-11eb-862a-fe12ceb35965.png)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 10.0.1]
- Version of Node.js: [e.g. 12.0.0]
- Deployment: [e.g. next start, next export, Vercel, other platform]

**Comment by TheThirdRace** [comment] 2020-12-31 15:01
I concur, I have the same problem.

Somehow, when loaded with lighthouse, the image URL don't fit the `sizes` property I'm passing.

### Example:

#### next.config.js

```
	images: {
		deviceSizes: [320, 480, 640, 750, 828, 960, 1080, 1200, 1440, 1920, 2048, 2560, 3840]
	},
```

#### Calling the image component

Note, I'm using a custom Image component wrapper to ease passing properties and benefit from Chakra UI's styling system, but at the end it outputs the NextJs Image component correctly.

```
<Image
		src='/img/skyrim/the-elder-scrolls-v-skyrim-header-aspect-ratio-4-1.jpg'
		alt='Skyrim'
		dimensions={[contentMaxWidthInPixel, contentMaxWidthInPixel / 4]} // 4:1 aspect ratio
		layout='responsive'
		sizes={Sizes.main}
		variant='indexArticleHeader'
/>
```

#### Sizes.main

Sizes is an enum that passes this value for `main`:

```
'(max-width: 320px) 320px, (max-width: 480px) 480px, (max-width: 640px) 640px, (max-width: 750px) 750px, (max-width: 828px) 828px, 960px'
```

#### Problem with lighthouse

As you can see from Sizes.main, the maximum width should be 960px.

But when using Lighthouse, it complains about having an image unoptimized because it's too big.

When you look further into the warning/error in lighthouse, it shows the URL for that image.

The width in the URL is 1200, which is impossible given the `Sizes.main` has a max width of 960px.

My screen is 2560px, so the 1200 is NOT coming from there either. I guess it's something to do with how lighthouse use a headless Chrome to render during its tests.

**Comment by Timer** [comment] 2020-12-31 19:18
Preloading of images is fixed on `next@canary`, which is what OP reported!

**Closed by Timer** 2020-12-31 19:18 UTC
Labels: kind: bug

**Comment by balazsorban44** [comment] 2022-01-28 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
