### ISSUE TITLE
Error with ESLint in Next 11 "Parsing error: Cannot find module 'next/babel'"

### ISSUE THREAD

**Issue by adriandelgg** [vercel/next.js#26406] opened 2021-06-21 07:39 UTC
### What version of Next.js are you using?

11

### What version of Node.js are you using?

12.21.0

### What browser are you using?

FireFox

### What operating system are you using?

Linux (Kubuntu/Ubuntu)

### How are you deploying your application?

none

### Describe the Bug

Whenever I have the `.eslintrc` file in my project I receive the error below. However, if I run `npm run lint` as it says in the [docs](https://nextjs.org/docs/basic-features/eslint), it shows that there aren't any issues.
```
File is a CommonJS module; it may be converted to an ES6 module.ts(80001)
Parsing error: Cannot find module 'next/babel'
Require stack:
- /home/dark/Documents/Projects/typescript-test/node_modules/next/dist/compiled/babel/bundle.js
- /home/dark/Documents/Projects/typescript-test/node_modules/next/dist/compiled/babel/eslint-parser.js
- /home/dark/Documents/Projects/typescript-test/node_modules/eslint-config-next/parser.js
- /home/dark/Documents/Projects/typescript-test/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /home/dark/Documents/Projects/typescript-test/node_modules/@eslint/eslintrc/lib/index.js
- /home/dark/Documents/Projects/typescript-test/node_modules/eslint/lib/cli-engine/cli-engine.js
- /home/dark/Documents/Projects/typescript-test/node_modules/eslint/lib/cli-engine/index.js
- /home/dark/Documents/Projects/typescript-test/node_modules/eslint/lib/api.js
- /home/dark/.vscode/extensions/dbaeumer.vscode-eslint-2.1.23/server/out/eslintServer.jseslint
module export=
(property) export=: {
    reactStrictMode: boolean;
}
```

### Expected Behavior

There should be no linting error.

### To Reproduce

Just having the `.eslintrc` with the default configurations.

**Comment by housseindjirdeh** [comment] 2021-06-21 19:17
Few questions so I can try to reproduce this:

- Can you share your ESLint configuration? 
- Are you only seeing this error with `next build` and not with `next lint`
- Are you using [Yarn PnP](https://yarnpkg.com/features/pnp)?

**Comment by baufometic** [comment] 2021-06-22 23:44
The error seems to be occuring due to the VSCode extension of eslint. When I uninstalled the extension and re-ran `npm run lint`, the babel error went away and eslint produced a correct list of linting hints in the terminal.

**Comment by housseindjirdeh** [comment] 2021-06-28 20:47
Thanks @baufometic!

> However, if I run npm run lint as it says in the docs, it shows that there aren't any issues.

@adriandelgg Can you try uninstalling the extension to see if that's the issue? If you're not seeing any issues when you run `next lint` but only in your editor, then it sounds like it could be a VSCode extension bug

**Comment by housseindjirdeh** [comment] 2021-06-30 20:27
@adriandelgg Looks like others running into the same issue [also resolved it](https://github.com/vercel/next.js/issues/26541#issuecomment-870962005) by following @baufometic's solution 

Going to close this, but happy to re-open if the issue is still persisting for you!

**Closed by housseindjirdeh** 2021-06-30 20:27 UTC
Labels: kind: bug

**Comment by balazsorban44** [comment] 2022-01-28 04:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
