### ISSUE TITLE
Docs:  TS and JS Switcher not working and how to extend TS and JS Switcher to any other language 

### ISSUE THREAD

**Issue by waynelwz** [vercel/next.js#62992] opened 2024-03-07 12:00 UTC
### What is the improvement or update you wish to see?

Hi, here is the code , i have two questions: 

1. why isn't TS and JS Switcher working 
2. how to extend TS and JS Switcher with any other language 

### Is there any context that might help us understand?

[source code](https://codesandbox.io/p/devbox/3sw2qp?file=%2Fsrc%2Fpages%2Findex.mdx%3A11%2C19&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clth5ocw800063b6jo0nf3tpx%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clth5ocw700023b6jyiknqi6s%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clth5ocw700043b6jcmfrrzzi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clth5ocw700053b6j6txo306p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clth5ocw700023b6jyiknqi6s%2522%253A%257B%2522id%2522%253A%2522clth5ocw700023b6jyiknqi6s%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clth5yzux00023b6j1z7ma95s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A19%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A19%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fpages%252Findex.mdx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clth5yzux00023b6j1z7ma95s%2522%257D%252C%2522clth5ocw700053b6j6txo306p%2522%253A%257B%2522id%2522%253A%2522clth5ocw700053b6j6txo306p%2522%252C%2522activeTabId%2522%253A%2522clth5tmob00kz3b6jof3bdbg5%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522port%2522%253A1234%252C%2522id%2522%253A%2522clth5oyxb00dq3b6jh74rizec%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clth5tmob00kz3b6jof3bdbg5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clth5ocw700043b6jcmfrrzzi%2522%253A%257B%2522id%2522%253A%2522clth5ocw700043b6jcmfrrzzi%2522%252C%2522activeTabId%2522%253A%2522clth5ocw700033b6j053yphqa%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clth5ocw700033b6j053yphqa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clth5odjx000sdhf86r9vge79%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clth5ov7j00bk3b6jo11zp0od%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/community/contribution-guide#ts-and-js-switcher

**Comment by leerob** [comment] 2024-04-13 18:06
Closing as dupe of https://github.com/vercel/next.js/issues/64292

(We don't plan on extending to other languages, since Next.js doesn't support those)

**Closed by leerob** 2024-04-13 18:06 UTC
Labels: template: documentation
