### ISSUE TITLE
`unstable_revalidate` throws in production mode locally

### ISSUE THREAD

**Issue by alii** [vercel/next.js#34874] opened 2022-02-28 02:36 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
    Binaries:
      Node: 17.4.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.4
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

Was able to figure out that the client could not request itself, perhaps because it's not bound to 0.0.0.0? But the error message was extremely poor and I had to edit the console.log in the following file to figure out what had happened
<img width="691" alt="image" src="https://user-images.githubusercontent.com/25351731/155914685-9eacffae-031e-4787-980f-c17554375bb8.png">

<img width="907" alt="image" src="https://user-images.githubusercontent.com/25351731/155914615-4dbdbb10-dc8f-462a-bbb2-951a20520fce.png">

### Expected Behavior

No error

### To Reproduce

Build a Next.js app that has a dynamic statically rendered route with ISR, build it locally and run it locally and call unstable_revalidate to see it error.

**Comment by alii** [comment] 2022-02-28 02:50
Temp workaround was forcing next to bind to localhost:
```
yarn next start -H localhost
```

**Comment by balazsorban44** [comment] 2022-02-28 14:02
I created the following reproduction:

`pages/index.js`
```js
export default function Home(props) {
  return (
    <button
      onClick={async () => {
        await fetch("/api/revalidate")
        window.location.reload()
      }}
    >
      Revalidated {props.time}
    </button>
  )
}

export async function getStaticProps() {
  return {
    props: { time: new Date().toISOString() },
    revalidate: 3600,
  }
}
```

`pages/api/revalidate.js`
```js
export default async function handler(_, res) {
  await res.unstable_revalidate("/")
  res.json({ revalidated: true })
}
```

And calling `http://localhost:3000/api/revalidate` either through `fetch` or visiting directly works correctly on `localhost`.

**Comment by thefinnomenon** [comment] 2022-04-08 19:35
Ended up here because of a similar error but in my case the error message is a 404 (I went in and added the for path part)
```
Error: Error: Invalid response 404 for http://localhost:3000/posts/my-first-post
    at unstable_revalidate (.../node_modules/next/dist/server/api-utils/node.js:228:15)
```
The 404 for this path makes sense because it really should have a subdomain (e.g. http://chris.localhost:3000/posts/my-first-post) but digging further into this `node.js` file, the problem is here,
```js
async function unstable_revalidate(urlPath, req, context) {
    ...
    const baseUrl = context.trustHostHeader ? `https://${req.headers.host}` : `http://${context.hostname}:${context.port}`;
   ...
}
```
If `context.trustHostHeader` is `false`, like in this case, it creates a url that a possible subdomain. When deployed, everything works correctly because it evaluates to `true` and uses the first url template.

**Comment by ijjk** [comment] 2022-04-08 20:31
Closing as this should be fixed in the latest version of Next.js `v12.1.4` specifically this PR https://github.com/vercel/next.js/pull/35386

**Closed by ijjk** 2022-04-08 20:31 UTC
Labels: template: bug

**Comment by alii** [comment] 2022-04-08 21:22
awesome thx :) :heart:
