### ISSUE TITLE
Type error: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.

### ISSUE THREAD

**Issue by switz** [vercel/next.js#15754] opened 2020-07-31 18:33 UTC
# Bug report

## Describe the bug

Perhaps this isn't a next.js bug, but this same library has compiled on next.js for every version before 9.5. Is there any insight into why on 9.5 it would stop compiling? I didn't notice any major upgrades to typescript in 9.5 that would have caused this.

```
       Creating an optimized production build...
remote: Failed to compile.
remote:
remote: ../../node_modules/@blueprintjs/core/src/components/icon/icon.tsx:24:10
remote: Type error: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
remote:
remote:   22 | import { AbstractPureComponent2, Classes, DISPLAYNAME_PREFIX, IIntentProps, IProps, MaybeElement } from "../../common";
remote:   23 |
remote: > 24 | export { IconName };
remote:      |          ^
remote:   25 |
remote:   26 | export interface IIconProps extends IIntentProps, IProps {
remote:   27 |     /** This component does not support custom children. Use the `icon` prop. */
remote: error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
remote: error Command failed.
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Install `@blueprintjs/core` on next.js 9.5
2. import a few files
3. Build next.js bundle

## Expected behavior

Perhaps this is working as intended, but I'm unsure of why it compiled pre-9.5. I downgraded to 9.4 and it compiled just fine.

## System information

- OS: Mac

- Version of Next.js: Tried 9.5.0 and 9.5.1
- Version of Node.js: [e.g. 10.10.0] 12.16.1
- Version of Typescript: [e.g. 10.10.0] 3.9.7

**Comment by Timer** [comment] 2020-08-03 13:08
See the error message provided by Babel in your OP:

> Type error: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.

The code in question needs to be updated to use `export type { IconName }`.

Next.js itself does not compile `node_modules`, so it's likely you have a `next.config.js` that's turning on compilation of `node_modules` in an unexpected way.

I'm going to close this as this isn't a bug / expected per TypeScript (see the file in reference is `.tsx`).

If you need additional help, please open a Discussion!

**Closed by Timer** 2020-08-03 13:08 UTC

**Comment by balazsorban44** [comment] 2022-01-29 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
