### ISSUE TITLE
BUG: ReactFreshWebpackPlugin - additionalTreeRuntimeRequirements doesn't exist in compilation hooks

### ISSUE THREAD

**Issue by kesor** [vercel/next.js#21134] opened 2021-01-15 00:24 UTC
Tried creating a new project using `create-nx-workspace` and choosing `Next.js` as an option. After running `npm start` the script failed with an exception `Cannot read property 'tap' of undefined`. After a bit of debugging found the exact line that was causing the error.

Credit to @ViableClanMember for leading me to try `nx` and stumble on this bug.

## 

## Running -
```
root@eef1066ee246:/app/viable-saas# npm start

> viable-saas@0.0.0 start
> nx serve

> nx run viable-saas:serve
info  - automatically enabled Fast Refresh for 1 custom loader
Cannot read property 'tap' of undefined
npm ERR! code 1
npm ERR! path /app/viable-saas
npm ERR! command failed
npm ERR! command sh -c nx serve

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-14T23_44_10_516Z-debug.log
```

## The `undefined` object from here -

https://github.com/vercel/next.js/blob/ce5d9c858b70f647b532ec2f62ddde506af32b6a/packages/react-refresh-utils/ReactRefreshWebpackPlugin.ts#L139

## Debug file

```
# cat /root/.npm/_logs/2021-01-14T23_44_10_516Z-debug.log
0 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
1 info using npm@7.3.0
2 info using node@v15.5.1
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/app/viable-saas/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 6ms
19 verbose npm-session 03650f10b6fedc4d
20 timing npm:load Completed in 15ms
21 timing command:run-script Completed in 4569ms
22 timing command:start Completed in 4571ms
23 verbose stack Error: command failed
23 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
23 verbose stack     at ChildProcess.emit (node:events:376:20)
23 verbose stack     at maybeClose (node:internal/child_process:1063:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
24 verbose pkgid viable-saas@0.0.0
25 verbose cwd /app/viable-saas
26 verbose Linux 5.8.0-36-generic
27 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
28 verbose node v15.5.1
29 verbose npm  v7.3.0
30 error code 1
31 error path /app/viable-saas
32 error command failed
33 error command sh -c nx serve
34 verbose exit 1
```

**Comment by timneutkens** [comment] 2021-01-15 09:31
Can you try installing next@canary?

**Comment by timneutkens** [comment] 2021-01-15 09:32
How did you bypass the issue template completely btw?

**Comment by kesor** [comment] 2021-01-18 07:21
As I wrote, I didn't do anything special other than follow the prompts at `npx create-nx-workspace`

**Comment by helloitsm3** [comment] 2021-01-25 14:41
Any fix to this issue? I'm currently have the same error and couldn't figure out how to fix it

**Comment by timneutkens** [comment] 2021-01-26 19:08
Quite certain this was already fixed on `yarn add next@canary`, please try it out and report back.

**Closed by timneutkens** 2021-01-26 19:08 UTC

**Comment by balazsorban44** [comment] 2022-01-28 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
