### ISSUE TITLE
Turbopack doesn't support dynamic requests

### ISSUE THREAD

**Issue by Maclay74** [vercel/next.js#56531] opened 2023-10-06 15:38 UTC
### Link to the code that reproduces this issue

https://github.com/Maclay74/nextjs-turbopack-dynamic-import-bug

### To Reproduce

1. Start application via `npm run dev`
2. Check console output, it should provide correct values from modules
3. Restart application via `npm run dev-turbo`
4. Check console output, names are wrong

### Current vs. Expected behavior

Turbopack should import modules without caching them. 

Current :
```js
{ name: 'First', fileName: 'first.tsx' }
{ name: 'First', fileName: 'second.tsx' }
{ name: 'First', fileName: 'third.tsx' }
```

Expected:
```js
{ Name: 'First', fileName: 'first.tsx' }
{ Name: 'Second', fileName: 'second.tsx' }
{ Name: 'Third', fileName: 'third.tsx' }
```

Moreover, there is inconsistent behavior related to hot-reloading of the page. 
Page has some dynamic imports and when content of any of these modules is changes, it should trigger page reloading, as it depends on it.

Turbopack indeed does that, while webpack doesn't trigger page, although it recomplies the changed module. 
To reproduce that, change `files/first.tsx` and see that with `--turbo` the page is reloaded and it didn't without it.  

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 19.8.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.5-canary.3
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

<sub>[PACK-2246](https://linear.app/vercel/issue/PACK-2246/turbopack-cache-dynamically-imported-modules)</sub>

**Comment by sokra** [comment] 2024-01-19 15:14
The problem is that turbopack doesn't support dynamic requests in `require()` and `import()` yet. It currently always returns the first file. That's a missing feature, we will add.

**Comment by ForsakenHarmony** [comment] 2024-02-05 17:29
This is currently work in progress: https://github.com/vercel/turbo/pull/7153

**Comment by ForsakenHarmony** [comment] 2024-03-15 17:52
Should be fixed now

**Closed by ForsakenHarmony** 2024-03-15 17:52 UTC
Labels: template: bug, area: Turbopack, linear: turbopack
