### ISSUE TITLE
Typescript (or other package) is missing in monorepo

### ISSUE THREAD

**Issue by Oikio** [vercel/next.js#26565] opened 2021-06-24 09:41 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

-

### What operating system are you using?

macOS

### How are you deploying your application?

next build

### Describe the Bug

`next build` with Typescript project throws an error in monorepo structure like `root/packages/next-project` and TS is in dependencies list (but not in node_modules of the package, only at the root node_modules, because it's a shared dependncy). Worked fine with `next v10`.
Error:

```
It looks like you're trying to use TypeScript but do not have the required package(s) installed.

Please install typescript by running:

        npm install --save-dev typescript

If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your pages directory).
```
Also check for if it's `yarn` or `npm` is not working here, because in monorepo `yarn.lock` file is in the root of the project.

### Expected Behavior

`next build` should respect monorepo dependencies installed in upper tree if they are in package.json file of the package where nextjs is run.

### To Reproduce

I guess it's clear from the issue description, but I can elaborate.

**Comment by ljosberinn** [comment] 2021-06-24 11:49
Can't confirm on windows in a yarn workspaces monorepo. Maybe OS specific?

**Comment by RalfWeiss** [comment] 2021-06-25 19:23
Same with me on Ubuntu

**Comment by RalfWeiss** [comment] 2021-06-25 19:35
Please find a reproduction repo here: https://github.com/RalfWeiss/next-example-blog

**Comment by RalfWeiss** [comment] 2021-06-25 20:06
My fault. I was using node version `v12.9.0`. After setting it to `v12.20` everythings running as expected.

**Comment by Oikio** [comment] 2021-06-28 12:42
I wish I could give a reproduction, but not working on this part of our app ATM. 
I will make one or make a PR when I return to NextJS update.

**Comment by ijjk** [comment] 2021-09-19 05:56
Hi, it sounds like this might have been a local `node_modules` issue as it wasn't able to be reproduced and we use `require.resolve` to check for these necessary packages which shouldn't be affected by a monorepo setup so I'm going to close this issue. If you're still encountering this feel free to respond with additional info and we can investigate further!

**Closed by ijjk** 2021-09-19 05:56 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
