### ISSUE TITLE
12.1.3-canary.0 breaks catch-all dynamic routes with Edge runtime

### ISSUE THREAD

**Issue by leo** [vercel/next.js#35686] opened 2022-03-29 08:59 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:36:53 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T8101
Binaries:
  Node: 16.14.0
  npm: 8.3.1
  Yarn: 1.22.17
  pnpm: 6.30.1
Relevant packages:
  next: 12.1.3-canary.0
  react: 18.0.0-rc.1
  react-dom: 18.0.0-rc.1
```

### What browser are you using? (if relevant)

Chrome 99.0.4844.84

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Upgrading from `12.1.2-canary.1` to `12.1.3-canary.0` prevents `next dev` from working:

```
[REDACTED]/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:62
            throw new Error(`Catch-all must be the last part of the URL.`);
                  ^

Error: Catch-all must be the last part of the URL.
    at UrlNode._insert ([REDACTED]/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:62:19)
    at UrlNode._insert ([REDACTED]/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:146:40)
    at UrlNode._insert ([REDACTED]/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:146:40)
    at UrlNode._insert ([REDACTED]/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:146:40)
    at UrlNode._insert ([REDACTED]/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:146:40)
    at UrlNode.insert ([REDACTED]/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:8:14)
    at [REDACTED]/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:170:46
    at Array.forEach (<anonymous>)
    at Object.getSortedRoutes ([REDACTED]/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:170:21)
    at Object.getRoutingItems ([REDACTED]/node_modules/next/dist/shared/lib/router/utils/routing-items.js:20:45)
```

The error isn't being very clear, but I'm assuming it's complaining about one of the dynamic routes I've configured. I have to guess which one it is, since the error doesn't say that, but perhaps this one:

```
/pages/[capture-a]/something/[capture-b]/[...capture-c].server.tsx
```

After removing it, `next dev` works just fine. It also worked just fine with `12.1.2-canary.1`, so this seems like a bug.

My guess is that it was caused by https://github.com/vercel/next.js/pull/32601 (I verified that https://github.com/vercel/next.js/issues/35451 is fixed, though, which I've reported a couple days ago).

### Expected Behavior

I'd expect the behavior for the dynamic route mentioned above to be what it was with version `12.1.2-canary.1` and therefore not break when running `next dev`.

### To Reproduce

1. Add a file at `/pages/[capture-a]/something/[capture-b]/[...capture-c].server.tsx`
2. Run `next dev`
3. See the error in your terminal

**Comment by balazsorban44** [comment] 2022-03-29 09:56
Could you link to a reproduction? I am unable to reproduce :thinking: :

```js
// pages/[capture-a]/something/[capture-b]/[...capture-c].server.jsx
import { useRouter } from "next/router"

export default function Page() {
  const router = useRouter()
  return <pre>{JSON.stringify(router, null, 2)}</pre>
}
```

![image](https://user-images.githubusercontent.com/18369201/160585681-e94b81ca-4e71-48b3-a6ca-e193eabde820.png)

**Comment by leo** [comment] 2022-03-29 10:08
The error only seems to be happening if this is set within the page:

```
// Next.js currently requires this because of:
// https://github.com/vercel/next.js/issues/35633
export const config = { runtime: 'edge' };
```

**Comment by balazsorban44** [comment] 2022-03-29 10:23
Updated my example above, does not reproduce still. Could you distill the problem into a repository and link to it so we can investigate further? :pray:

**Comment by leo** [comment] 2022-03-29 10:33
Here you go: [next-dynamic-routes-bug](https://github.com/leo/next-dynamic-routes-bug).

![CleanShot 2022-03-29 at 12 33 07@2x](https://user-images.githubusercontent.com/6170607/160592848-8f0e659c-730e-4b3a-8345-06c73fab46bf.png)

**Comment by balazsorban44** [comment] 2022-03-29 12:18
Thanks! I could confirm a bug, but it is not related to experimental features. I created a minimal reproduction myself here, using React 17 and no experimental features.

The only requirement for the bug to appear is `export const config = { runtime: "edge" }` in the page component.

https://github.com/balazsorban44/nextjs-35686

The PR #32601 indeed seems to be the problem.

When building the route nodes, `[ '[...capture-c]', '_middleware' ] ` will be problematic, as previously it was not possible to have anything after a dynamic route path segment. That's what's throwing the error.

**Comment by leo** [comment] 2022-04-06 17:32
Seems like the bug might've been reverted here (will test with the next stable): https://github.com/vercel/next.js/commit/9805399faa6b0ec95d3b1c2d702627680368203c

**Comment by javivelasco** [comment] 2022-04-13 07:40
Indeed, closing it.

**Closed by javivelasco** 2022-04-13 07:40 UTC
Labels: kind: bug, area: Middleware, area: Routing
