### ISSUE TITLE
The route in the next.js subfolder does not work

### ISSUE THREAD

**Issue by phoique** [vercel/next.js#12515] opened 2020-05-05 11:31 UTC
# Bug report

The route in the next.js subfolder does not work.

## Describe the bug
I am using the latest version of Next.js '9.3.6'. The route inside the file in the subfolder does not work. Only the route named index. The example does not have user / index access via the browser. It has access as / user. There was no problem in '9.3.4' version of Next.js.

## Expected behavior
Accessing via browser as user / index.

## System information
- OS: Windows 10
- Browser: Opera
- Version of Next.js: 9.3.6
- Version of Node.js:  12.16.1
- Next.js version without error: 9.3.4

**Comment by jamesmosier** [comment] 2020-05-05 14:13
Could you provide a reproducible sample? Or even just a more detailed file structure that you are referencing?

**Comment by phoique** [comment] 2020-05-05 14:31
> Could you provide a reproducible sample? Or even just a more detailed file structure that you are referencing?
I have index.js in a few of my files. They also do not have access to / x / index on the browser.

**Comment by kyle-mccarthy** [comment] 2020-05-05 17:51
@phoique can you eloborate on your file structure? For example, this set up works with an index file in the subfolder.

```
/pages
/pages/index.js
/pages/users
/pages/users/index.js
/pages/users/[id].js
```

That would have 3 routes
- /
- /users
- /users/[id]

**Comment by phoique** [comment] 2020-05-05 18:26
> @phoique can you eloborate on your file structure? For example, this set up works with an index file in the subfolder.
> 
> ```
> /pages
> /pages/index.js
> /pages/users
> /pages/users/index.js
> /pages/users/[id].js
> ```
> 
> That would have 3 routes
> 
> * /
> * /users
> * /users/[id]

Hi, my file layout is like this: 
./pages
./pages/index.js
...
./pages/user/index.js 
./pages/user/update.js

/user/index not working on browser. I reach it like this on the browser /user.

**Comment by sdserage** [comment] 2020-05-05 23:18
I'm getting the same behavior on 9.3.6. I'm rolling back to the last version for now.

**Comment by Timer** [comment] 2020-05-06 03:38
Please provide a full reproduction. We have tests ensuring this behavior works as intended.

> /user/index not working on browser. I reach it like this on the browser /user.

It is expected that accessing `/user/index` would 404. The request needs to be `/user`.

**Comment by phoique** [comment] 2020-05-06 11:08
> Please provide a full reproduction. We have tests ensuring this behavior works as intended.
> 
> > /user/index not working on browser. I reach it like this on the browser /user.
> 
> It is expected that accessing `/user/index` would 404. The request needs to be `/user`.

What exactly do you want me to say? Yes, when you enter /user/index, it throws to 404 page. In the old version, I was able to access as /user/index. In the new version I am accessing as /user only

**Comment by lkbr** [comment] 2020-05-06 12:40
By full reproduction, people usually mean an example on github or codesandbox that shows the minimal amount of code that reproduces the error you're seeing. You have 3 different people willing to help, they just need a little input from you.

**Comment by sauhard98** [comment] 2020-05-06 19:44
Well I think I might know when a 404 is thrown.
Consider the route:
./pages/users/index.js

When you will open **localhost:3000/users** it will display the content of the page, but in case you visit **localhost:3000/users/** It might throw a 404.
The problem is the extra "/" at the end of the url

**Comment by taylorbryant** [comment] 2020-05-07 01:45
Related to #5214

**Comment by Timer** [comment] 2020-09-03 02:32
Closing as no reproduction provided.

**Closed by Timer** 2020-09-03 02:32 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
