### ISSUE TITLE
CNA "Pick a template" is not responsive in Win10+MINGW64

### ISSUE THREAD

**Issue by tomByrer** [vercel/next.js#15215] opened 2020-07-16 09:04 UTC
```bash
$ npx create-next-app
npx: installed 1 in 1.993s
? What is your project named? » card-nextjs
√ What is your project named? ... card-nextjs
? Pick a template » - Use arrow-keys. Return to submit.
>  Default starter app
   Example from the Next.js repo
√ Pick a template » Default starter app
Creating a new Next.js app in D:\doc\prog\learn\js\quiz-json\card-nextjs.

Installing react, react-dom, and next using yarn...
```
Win10, , npm 6.14.5, yarn 1.22.1
"Git Bash" (the shell that ships with stand-alone Git, I think 'MINGW64' terminal client)

2 bugs:

- The arrow keys won't work to select 'Example from Next.js repo'
- Seems to hang at `Installing react, react-dom, and next using yarn..`.

No problems using the Bash in the terminal that ships with VSCode.

I don't remember having to use arrow keys with other install CLI apps, let me know if you think of another to test.

**Comment by jamesmosier** [comment] 2020-07-16 13:29
Hi @tomByrer. Next v9.4.5 will actually be removing the example picker: https://github.com/vercel/next.js/pull/13977

Therefore this will not be a problem going forward.

Alternatively you can choose your example by doing `npx create-next-app --example blog-starter my-blog-starter-app` (for example)

**Comment by Timer** [comment] 2020-07-16 14:21
Closing per above!

**Closed by Timer** 2020-07-16 14:21 UTC

**Comment by tomByrer** [comment] 2020-07-16 15:02
Thanks for the info!

@Timer  Might want to keep open until v9.4.5 is released, so others who get the error understand the fix action.

**Comment by balazsorban44** [comment] 2022-01-29 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
