### ISSUE TITLE
styles in sass file doesn't put on element in first refresh in nextjs

### ISSUE THREAD

**Issue by mahyarfrd70** [vercel/next.js#10752] opened 2020-02-29 17:44 UTC
I have nextjs project that I use styled-jsx and sass for styling. but I have a problem just in development mode. I run the project in development mode and open it on the browser and click on the link to go to another page but when the page changes, styled-jsx loads in page and elements get these styles but styles that exist in sass file doesn't load and when refresh page both styles load in a page.

this is my code :

    //index page

    const Index: NextPage<{}> = () => {
        return (
            <Link href="/home">
                <a>home</a>
            </Link>
         );
    };
    export default Index;

    //home page

    import React from "react";
    import "./style.scss";
    const Home = () => {
        return (
            <div className="home_box">
                <p className="home_text">Test</p>
                <style jsx>{`
                    .home_text {
                        color: red;
                    }
                `}</style>
            </div>
        );
     };
    export default Home;

    //style.scss

    .home_box{
         background-color: green
    }

and this is a demo of my app:

[![enter image description here][1]][1]

[1]: https://i.stack.imgur.com/e3cYA.gif

as you see in the picture I change route and my sass style doesn't exist but when I refresh the page it appears.

it happens just in development mode and just for the first time. in production, everything works well.

how can I fix this problem?

**Comment by timneutkens** [comment] 2020-03-01 14:27
Assuming it's a wrong babelrc, but hard to say when no reproduction is provided and the issue template is ignored.

**Comment by mahyarfrd70** [comment] 2020-03-01 17:46
> Assuming it's a wrong babelrc, but hard to say when no reproduction is provided and the issue template is ignored.

Hi 

https://github.com/mahyarfrd70/next-typescript-boilerplate/blob/master/README.md

This is my repo and you can see my config there . Thanks for help me.

**Comment by vixeven** [comment] 2020-03-04 09:51
I have the same problem with css files (imported via @zeit/next-css). It needs a refresh to get applied.

**Comment by mahyarfrd70** [comment] 2020-03-04 11:57
> I have the same problem with css files (imported via @zeit/next-css). It needs a refresh to get applied.

test your problem in production mode . there isn't problem for me in production mode . please check it and report.

**Comment by vixeven** [comment] 2020-03-04 12:01
@mahyarfrd70 Yeap. After build app works just fine.

**Comment by guilhermepontes** [comment] 2020-03-04 14:20
I'm also having this problem in development.

**Comment by evanlask** [comment] 2020-03-05 17:53
I believe at the moment next does not have a way of injecting new styles for a page after routing when using scss.

In development mode it generates a stylesheet which only contains styles for your current route. In production mode it generates a stylesheet containing all styles for the entire app.

A work around for the issue could be to create a sass file `app.scss` that you import in to the App component. Then @import all of your various sass files into `app.scss` instead of every individual page or component. You end up with one big stylesheet but you won't have to reload in development mode just to see styles.

**Comment by Ali-Mohammadsadegh** [comment] 2020-03-16 01:53
I think that you can doing with external SCSS file and import it into your project.

**Comment by iOiurson** [comment] 2020-03-30 11:42
Same problem for me in dev mode.
Works fine in production, but i would be nice to have it fixed in dev.

**Comment by alieslamifard** [comment] 2020-04-21 17:19
Hey @mahyarfrd70 , try this fix. move to node ^12 and install your packages with yarn and run your development with yarn dev instead of npm run dev.

**Comment by chornos13** [comment] 2020-05-03 00:01
Same problem here only in dev mode.

**Comment by chornos13** [comment] 2020-05-03 00:02
> Hey @mahyarfrd70 , try this fix. move to node ^12 and install your packages with yarn and run your development with yarn dev instead of npm run dev.

I tried this, but no luck

**Comment by Timer** [comment] 2020-09-12 04:55
Closing as this should be fixed with the new Fast Refresh integration.

**Closed by Timer** 2020-09-12 04:55 UTC
Labels: good first issue

**Comment by balazsorban44** [comment] 2022-01-29 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
