### ISSUE TITLE
Nextjs server not responding 

### ISSUE THREAD

**Issue by saurabhmehta1601** [vercel/next.js#29030] opened 2021-09-12 07:11 UTC
### What version of Next.js are you using?

latest

### What version of Node.js are you using?

14.17.1

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04.3 LTS

### How are you deploying your application?

localhost

### Describe the Bug

I installed nextjs template using command `npx create-next-app --example with-tailwindcss .` .Once installed , I tried to run dev server using `npm run dev` .Now , console shows these warnings :
1. You have enabled the JIT engine which is currently in preview.
2. Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
Morever , the main problem is console shows compiled successfull but on opening `http://localhost:3000/` in chrome the page keeps on loading but does not load.
Screenshot :

![Screenshot from 2021-09-12 12-41-18](https://user-images.githubusercontent.com/57309205/132977315-79f8097e-0c1c-4e17-bc96-df0b1418bdf3.png)

### Expected Behavior

The webpage should load  since on using command `npm run dev` since  it is showing compiled successfull . 

### To Reproduce

1. Run `npx create-next-app --example with-tailwindcss .`
2. Run `npm run dev` .
3. Open `http://localhost:3000` in browser .

**Comment by gauravkrp** [comment] 2021-09-15 18:59
hey @saurabhmehta1601 I tried reproducing this but faced no issue on my windows machine. I also got the 2 warnings but it works perfectly in the browser. BTW are you still facing the issue?


![image](https://user-images.githubusercontent.com/12250556/133493232-6ef147ca-dd61-402b-91c6-166519362173.png)

**Comment by ijjk** [comment] 2021-09-23 03:27
Closing as a potential duplicate of https://github.com/vercel/next.js/issues/10061

**Closed by ijjk** 2021-09-23 03:27 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
