### ISSUE TITLE
Next.js 13 non-module imported styles don't get unloaded

### ISSUE THREAD

**Issue by saraelsa** [vercel/next.js#47290] opened 2023-03-19 07:51 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 [redacted]
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.8
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-usgvbr?file=app/page.tsx

### To Reproduce

- Begin with a project that uses the app directory.
- Create a page that imports a CSS file (*.css, not *.module.css).
- Link to another page from the page that imports a CSS file using a router link (the `Link` component).
- Observe that the styles in the css file have not been unloaded.
- Refresh the page.
- The styles will no longer appear.

### Describe the Bug

Global CSS styles do not get unloaded when navigating between components using a `Link`.

### Expected Behavior

If a currently loaded global CSS style is not present in the new route, the style should get unloaded.

### How are you deploying your application? (if relevant)

next dev and next start

**Comment by balazsorban44** [comment] 2023-03-19 12:13
Duplicate of #46817

**Closed by balazsorban44** 2023-03-19 12:13 UTC
Labels: template: bug
