### ISSUE TITLE
Catch-all route SSG returning empty pageProps at first, but desired pageProps after fetch within SSG is successful

### ISSUE THREAD

**Issue by Warqus** [vercel/next.js#21338] opened 2021-01-19 14:57 UTC
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

14.15.3

**What browser are you using?**

chrome

**What operating system are you using?**

Windows

**How are you deploying your application?**

Vercel

**Describe the Bug**

With the following code in my [[...slug]].tsx, I get {} as pageProps in my _app.tsx. Whenever the data fetching within [[...slug]].tsx is done, it returns the correct object.

I wrote a loader, that displays on the page whenever pageProps is empty. This results in a page source of html showing the loader, instead of the actual desired content.

**Expected Behavior**

return the desired pageProps directly instead of {}

**To Reproduce**

entity/[id]/[[...slug]].tsx

```
import React from "react";
import {GetStaticPaths, GetStaticProps} from "next";
import {getSlugInfoFromParams} from "../../../utils/utils_urls";
import {
    fetchEntity, fetchEntityAttributes,
    fetchSiteLocale,
    fetchSiteSettings
} from "../../../utils/utils_fetch";
import {IPropTypesEntityApi} from "../../../components/entity/Entity.types";
import EntityApi from "../../../components/entity/EntityApi";
import {checkEndpointEnvironmentalVariables} from "../../../utils/utils_endpoint";


const PageEntity = (props: IPropTypesEntityApi) => <EntityApi {...props} />
export default PageEntity


export const getStaticProps: GetStaticProps = async context => {
    if(!checkEndpointEnvironmentalVariables()) {
        return { notFound: true }
    }

    const locales = await fetchSiteLocale()

    // get slug and lang from context params
    const {lang} = getSlugInfoFromParams(context.params, locales);

    let dataSiteSettings;
    let dataEntity;
    let dataEntityAttributes;

    if (lang && context.params?.id) {
        dataEntity = await fetchEntity(lang, String(context.params.id))


        dataEntityAttributes = await fetchEntityAttributes(lang)
        dataSiteSettings = await fetchSiteSettings(lang)
    }

    if(!(dataSiteSettings?.settinggeneral?.system.search && dataEntity)) {
        return { notFound: true}
    }

    return {
        props: {
            responseStatus: (dataSiteSettings?.settinggeneral?.system.search && dataEntity) ? 200 : 404,
            locales: locales,
            entity: dataEntity,
            entityAttributes: dataEntityAttributes,
            settings: dataSiteSettings,
        },
        revalidate: 10 * 60
    }
}

export const getStaticPaths: GetStaticPaths = async () => {
    return {
        paths: [],
        fallback: true
    }
}
```

with _app.tsx containing:

```
{
    !pageProps.responseStatus
        ? <Loader/>
        : pageProps.responseStatus >= 400
            ? pageProps.responseStatus === 404 && router.asPath === "/"
                ? <UnderConstruction />
                : <Error statusCode={pageProps.responseStatus} />
            : <Component {...pageProps} />
}
```

With the following pages:

![image](https://user-images.githubusercontent.com/14151318/105051198-d4525500-5a6e-11eb-907c-e2e5d8719a72.png)

Extra information; this is the output of console.log(router) in _app.tsx when navigating to http://localhost:3000/entity/some-id/test/path

```
ServerRouter {
  route: '/entity/[id]/[[...slug]]',
  pathname: '/entity/[id]/[[...slug]]',
  query: {},
  asPath: '/entity/[id]/[[...slug]]',
  basePath: '',
  events: undefined,
  isFallback: true,
  locale: undefined,
  isReady: false,
  locales: undefined,
  defaultLocale: undefined,
  domainLocales: undefined
}
ServerRouter {
  route: '/entity/[id]/[[...slug]]',
  pathname: '/entity/[id]/[[...slug]]',
  query: {
    id: 'some-id',
    slug: [ 'test', 'path' ]
  },
  asPath: '/entity/some-id/test/path',
  basePath: '',
  events: undefined,
  isFallback: false,
  locale: undefined,
  isReady: false,
  locales: undefined,
  defaultLocale: undefined,
  domainLocales: undefined
}
```

**Comment by ijjk** [comment] 2021-01-19 17:28
Hi, this is the `fallback: true` behavior you enabled in `getStaticPaths` see the documentation here for more information https://nextjs.org/docs/basic-features/data-fetching#fallback-true

I'm going to close this since it is the expected behavior and is already documented.

**Closed by ijjk** 2021-01-19 17:28 UTC
Labels: template: bug

**Comment by Warqus** [comment] 2021-01-19 17:34
@ijjk Thanks for the reply. I read the documentation. This is the last step:

"At the same time, Next.js adds this path to the list of pre-rendered pages. Subsequent requests to the same path will serve the generated page, just like other pages pre-rendered at build time."

The page that is generated as html is only the loader, not the actual content. So I assume the step above is not done. Do you know how I could make sure the HTML generated has the desired props?

**Comment by ijjk** [comment] 2021-01-19 17:38
In the above example you aren't prerendering any paths since you're returning an empty paths array from `getStaticPaths` so the first request for each path will show the fallback version of the page which can be detected with `useRouter().isFallback`

**Comment by balazsorban44** [comment] 2022-01-28 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
