### ISSUE TITLE
next.js/examples/with-tailwindcss-emotion

### ISSUE THREAD

**Issue by druvisc** [vercel/next.js#30026] opened 2021-10-18 10:24 UTC
### What example does this report relate to?

with-tailwindcss-emotion

### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

16.11.1

### What operating system are you using?

macOS

### Describe the Bug

```
error - ./pages/_app.js
TypeError: Cannot read properties of undefined (reading 'theme')
```

### Expected Behavior

App to launch.

### To Reproduce

npx create-next-app --example with-tailwindcss-emotion with-tailwindcss-emotion-app
cd with-tailwindcss-emotion-app
npm run dev

**Comment by jamesmosier** [comment] 2021-10-20 01:16
This appears to be a duplicate of https://github.com/vercel/next.js/issues/26337

**Closed by jamesmosier** 2021-10-20 01:16 UTC
Labels: type: example, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 14:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
