### ISSUE TITLE
router.push sometimes works and sometimes it doesn't in development.

### ISSUE THREAD

**Issue by Mishra-Suraj** [vercel/next.js#21056] opened 2021-01-13 08:45 UTC
**What version of Next.js are you using?**

latest

**What version of Node.js are you using?**

14.13.1

**What browser are you using?**

Chromium

**What operating system are you using?**

Kubuntu - 20.10

**How are you deploying your application?**

none

**Describe the Bug**

I have a logout button on a navigation bar. I have attached a function to the button. The function is dead simple and really small, so I don't think there's a problem in my code. The function executes every time I click on logout button. But the router.push() of next/router doesn't works most of the time. And the weird part is it works sometimes without any changes. Here's the function.

```
function logOut() {
	console.log('inLogout');
	cookies.remove('auth');
	router.push('/auth');
}
```

**Expected Behavior**

router.push() should work every time it is used.

**To Reproduce**

1 - Import next/router
2 - Write router.push()
3 - Call it

**Comment by timneutkens** [comment] 2021-01-13 16:36
Going to close this issue it's not actionable as per the issue template.

**Closed by timneutkens** 2021-01-13 16:36 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 20:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
