### ISSUE TITLE
Amplify Causing Errors With Next 12 middleware

### ISSUE THREAD

**Issue by bluetoken-luke** [vercel/next.js#30884] opened 2021-11-03 12:03 UTC
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

16

### What browser are you using?

chrome

### What operating system are you using?

popos

### How are you deploying your application?

ECS

### Describe the Bug

We are working on updating our application up to NextJS 12. In doing so we are interested in moving the authentication check for protected pages to the new middleware feature available in next 12.  I went about attempting to use withSSRContext to check the users authentication status in the middleware.

```javascript
import type { NextFetchEvent, NextRequest } from 'next/server';
import { Amplify, withSSRContext } from 'aws-amplify';
import { AwsConfig } from '../../../../../../src/config';

Amplify.configure({ ...AwsConfig, ssr: true });

export const middleware = async (req: NextRequest, ev: NextFetchEvent) => {
  console.log('req', req);

  const { Auth } = withSSRContext({ req: req });
  return new Response('Hello World!');
};
```

As you can see above, I didn't get too far before this already broke the app. It seems that something underlying is attempting to use window which of course is not present on server.  I have posted this issue in amplify's repository.  Im hoping someone has a way to work around this issue for the time being [#9145.](https://github.com/aws-amplify/amplify-js/issues/9145)

![image](https://user-images.githubusercontent.com/49762288/140056277-7727cac6-1a09-4ea0-b209-580bf2f6d16a.png)

### Expected Behavior

Authentication is checked in the same manner it would be for getServerSideProps

### To Reproduce

In a next 12 application. place a _middleware.ts or _middleware.js file in one of your page directories. In that middleware file, simply import Amplify and that should be enough to draw out the exception.

**Comment by bluetoken-luke** [comment] 2021-11-09 16:27
So been digging into this as we badly want this feature.  What I have found is that in the networkMonitor in Reachability there is a check for if this is running in node (which being on the server it should be).  However, that check is coming back false.  This allows the networkMonitor to continue on in its code thinking presumably its in a browser.  isWebWorker() winds up returning false which makes the globalObj window which then doesn't exist on the server.

![image](https://user-images.githubusercontent.com/49762288/140961778-53e0d329-e03d-48f1-b8da-2de6dcf76866.png)

So went looking for why this isNode call is coming back false.  Looking at browserOrNode() it is checking the node version in process in order to determine if this is node on the server.  However process.versions is empty when running the middleware (it is not when running gSSP).

![image](https://user-images.githubusercontent.com/49762288/140962561-21664eba-094b-4152-a7b1-2fbe54f06524.png)

![image](https://user-images.githubusercontent.com/49762288/140962631-9759b384-fd0a-4f23-8101-006d01241629.png)

This seems to be the cause of the window undefined error seen above when using amplify in nextjs middleware.  Im uncertain on if the fix should be on amplify's end or next's.  It feels like next should probably be setting that version.  But unsure.  Im doing all I can to try and work around this without having to fork amplify and make changes but without being able to modify whats in process, its looking bleak.

**Comment by javivelasco** [comment] 2021-12-22 18:35
Closing this one in favour of #31253

**Closed by javivelasco** 2021-12-22 18:35 UTC
Labels: template: bug, area: Middleware

**Comment by balazsorban44** [comment] 2022-01-27 01:28
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
