### ISSUE TITLE
Dynamically loading MDX with --turbo always returns the first .mdx in the target dir

### ISSUE THREAD

**Issue by maxsteenbergen** [vercel/next.js#50569] opened 2023-05-31 07:36 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 3.3.0
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.5-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Dynamic imports (next/dynamic), MDX (@next/mdx), Turbopack (--turbo)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/maxsteenbergen/dynamic-css-module-repro

### To Reproduce

1. Configure Next to support MDX [as per the docs](https://nextjs.org/docs/app/building-your-application/configuring/mdx)
2. Make a [document] directory inside `./app`
3. Add three separate .mdx files inside the `[document]` directory named `document1.mdx`, `document2.mdx` and `document3.mdx`,
4. Add a `page.tsx` to the [slug] directory that dynamically loads an mdx based on the slug: 
```
"use client";
import dynamic from "next/dynamic";

export default function Page({ params }) {
  const DynamicMDXComponent = dynamic(
    () => import(`./${params.document}.mdx`)
  );

  return <DynamicMDXComponent />;
};
```
5. Run `next dev`, and point your browser to `localhost:3000/document3.mdx`
6. Notice how it renders `document1.mdx`

### Describe the Bug

When dynamically loading an mdx from from a given directory using router slugs, while running with `--turbo`, Next always returns the first .mdx file it finds in the targeted directory.

I have a dir names `[document]` (so as a slug) with three `.mdx` files, and 1 `page.tsx`
Inside the Page, I load the requested .mdx dynamically using 

```
const DynamicMDXComponent = dynamic(
  () => import(`./${params.document}.mdx`)
);
```

Navigating to this page in the browser always renders the first `.mdx`, so `localhost:3000/document3` renders `document1.mdx`, as does `localhost:3000/document2`

### Expected Behavior

Dynamically importing .mdx with --turbo returns the correct mdx file.

### Which browser are you using? (if relevant)

all

### How are you deploying your application? (if relevant)

next start

<sub>[WEB-1156](https://linear.app/vercel/issue/WEB-1156/dynamically-loading-mdx-with-turbo-always-returns-the-first-mdx-in-the)</sub>

**Comment by ForsakenHarmony** [comment] 2024-01-24 16:20
Going to close this as a duplicate of #56531 as that's the core issue, nothing to do with mdx

**Closed by ForsakenHarmony** 2024-01-24 16:20 UTC
Labels: template: bug, area: next/dynamic, area: app, area: Turbopack, area: MDX, linear: turbopack
