### ISSUE TITLE
Layout fetches API twice, and dedupe doesn't work.

### ISSUE THREAD

**Issue by Darren120** [vercel/next.js#50456] opened 2023-05-28 17:10 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.8.1
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.0
      eslint-config-next: 13.4.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/brave-fast-us5d1h?file=%2Fapp%2Flayout.tsx%3A8%2C13

### To Reproduce

Refresh the page, and layout will log twice but home logs once.

### Describe the Bug

Anything in layout even server components inside the root layout will be fetched twice.
I am trying to fetch user once in layout and pass it into my navbar.
I have tried making the navbar itself a server component and have it fetch inside there, but its the same behavior. weirdly, the page.tsx doesn't have this issue.

### Expected Behavior

Fetch api once in layout.tsx or if its a server children comp like {children}.

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

locally

**Comment by thexpand** [comment] 2023-05-28 17:55
Are you sure that's not because of React's strict mode? I believe everything is executed twice there. Try generating a production build and running that build instead of running the development environment.

**Comment by amankumar81** [comment] 2023-05-28 18:43
Hey @Darren120 

Strict mode renders component twice in development mode. But not on production . Deploy your application and then check. You'll find out it's working fine

**Comment by ztanner** [comment] 2024-08-20 18:49
I can no longer reproduce this on the latest stable version ([forked sandbox](https://codesandbox.io/p/devbox/fervent-mahavira-35ypgw?file=%2Fpackage.json%3A15%2C25)), so I'm going to close this issue. If you are still having this problem, please open a new issue with an updated reproduction. Thank you!

**Closed by ztanner** 2024-08-20 18:49 UTC
Labels: bug, area: app
