### ISSUE TITLE
error TS2724: '"next/dist/compiled/webpack/webpack"' has no exported member named 'webpack5'. Did you mean 'webpack'?

### ISSUE THREAD

**Issue by theodorDiaconu** [vercel/next.js#31419] opened 2021-11-15 10:44 UTC
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

14

### What browser are you using?

.

### What operating system are you using?

Mac

### How are you deploying your application?

.

### Describe the Bug

https://github.com/vercel/next.js/blob/canary/packages/next/server/config-shared.ts#L2
You are importing webpack5 from 'dist' in a ts file and that file only exports webpack, this prevents us from compiling an  npm package that depends on next@^12.0.3

### Expected Behavior

...

### To Reproduce

Just compile a package that depends on `next` 

(https://github.com/bluelibs/bluelibs/pull/109/files)

**Comment by timneutkens** [comment] 2021-11-15 11:32
This is fixed on next@canary: #31206

**Closed by timneutkens** 2021-11-15 11:32 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 09:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
