### ISSUE TITLE
`UnhandledSchemeError` when dependency uses `node:assert` imports

### ISSUE THREAD

**Issue by stefanprobst** [vercel/next.js#28774] opened 2021-09-03 18:58 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.17.6

### What browser are you using?

ff

### What operating system are you using?

linux

### How are you deploying your application?

vercel

### Describe the Bug

In a project which has `micromark-util-events-to-acorn@1.0.1` as a dependency, i get the following error when running `yarn dev`:

`Module build failed: UnhandledSchemeError: Reading from "node:assert" is not handled by plugins (Unhandled scheme).`

![Screenshot_20210903_204738](https://user-images.githubusercontent.com/20753323/132053244-06fd9ef3-539f-4d5e-8557-74c517a29c1d.png)

Things to note about this package: it uses an export map with a "development" user condition, and `node:assert` is only used there, not in the exported production build.

### Expected Behavior

No error.

### To Reproduce

1. `git clone https://github.com/stefanprobst/issue-next-webpack-node-imports.git`
2. `cd issue-next-webpack-node-imports`
2. `yarn && yarn add next@latest && yarn dev`
3. open [http://localhost:3000/](http://localhost:3000/)
3. See error message

**Comment by AnthonyKuang** [comment] 2021-09-14 22:27
Any updates on this issue? Facing the same problem but for `xdm`.

**Comment by AnthonyKuang** [comment] 2021-09-15 06:48
After some research, perhaps the cause is the [`node:` protocol](https://github.com/nodejs/node/issues/38343) not being supported in the current Next.js webpack configuration. I believe the protocol is now backported all the way to node v12 on ESM and node v14 on CJS.

> Things to note about this package: it uses an export map with a "development" user condition, and node:assert is only used there, not in the exported production build.

This is true throughout the micromark ecosystem as far as I know, so support for this would be great!

**Comment by stefanprobst** [comment] 2021-11-05 18:54
I'm still getting this error with next.js 12

**Comment by raitucarp** [comment] 2021-11-06 02:04
Me too, using remark getting this error

**Comment by vashisth00** [comment] 2021-11-18 11:12
Still getting this error 

`Module build failed: UnhandledSchemeError: Reading from `
```
handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "https:" URIs.
```

**Comment by balazsorban44** [comment] 2021-12-23 22:38
Looks like `webpack` itself already supports this. https://github.com/webpack/webpack/pull/12693

**Comment by chentsulin** [comment] 2022-01-05 03:27
Find a issue might be relevant to this: https://github.com/webpack/webpack/issues/14166

**Comment by manovotny** [comment] 2022-02-03 17:18
Here's a minimal reproduction repo with no other dependencies besides Next.js and React themselves, if that's helpful.

https://github.com/manovotny/nextjs-node-protocol-bug

**Comment by pwan-a** [comment] 2022-04-04 20:24
Also seeing this issue when using MSW with NextJS

**Comment by chentsulin** [comment] 2022-04-05 06:51
Next.js adds fallbacks for node built-in modules by using `resolve.fallback`:

https://github.com/vercel/next.js/blob/384953b35c5e9935bb4a2fcdfe5056efb73cd740/packages/next/build/webpack-config.ts#L628-L659

And this feature now don't support node protocol: https://github.com/webpack/webpack/issues/14166

**Comment by OskarGroth** [comment] 2022-04-18 13:41
It seems a fix for this bug was pushed in a recent Webpack release here: https://github.com/webpack/webpack/pull/15577

Can NextJS make sure to update their Webpack module to this version?

**Comment by timneutkens** [comment] 2022-04-20 12:19
@OskarGroth this went out in webpack 5.71.0, Next.js is using webpack 5.72.0 on the latest stable (12.1.5).

**Comment by OskarGroth** [comment] 2022-04-21 11:41
@timneutkens I'm using Next.js 12.1.5 and still experiencing this issue.

More info about the error I'm getting and the troubleshooting I've done: https://github.com/leafac/rehype-shiki/issues/7

**Comment by OskarGroth** [comment] 2022-04-26 13:31
No longer experiencing  this issue (12.1.5).

**Comment by firatgh** [comment] 2022-05-02 16:41
I am facing the same issue, after updating to Next 12.1.5

```
wait  - compiling...
error - node:buffer
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
```

**Comment by balazsorban44** [comment] 2022-05-03 11:17
I'm no longer able to reproduce the OP's issue. If you still do, please open a new issue with an attached reproduction, making sure you have tested the `latest` of `next`!

**Comment by stefanprobst** [comment] 2022-05-03 11:39
i am still seeing the exact same error message with `next@12.1.6` and `node@16.14.2`:

1.    git clone https://github.com/stefanprobst/issue-next-webpack-node-imports.git
2.    cd issue-next-webpack-node-imports
3.    yarn && yarn add next@latest && yarn dev
4.    open http://localhost:3000/
5.    See error message

**Comment by balazsorban44** [comment] 2022-05-03 13:55
Oh, interesting. The reproduction uses `11.1.2`, but upgrading to `latest` does throw the error after all. :eyes: 

It might be because the client-side code elimination tool isn't able to recognize the module you are using is for server-only.

```js
import fs from "node:fs"

export default function Home() {
  return null
}

export async function getStaticProps() {
  console.log(fs)
  return { props: {} }
}
```
This works as the code can be analyzed and Next.js will know where the `node:` import is being used.

Let's reopen and investigate further.

**Comment by GabenGar** [comment] 2022-06-02 19:36
Any progress on this? Got hit by this error too while trying to migrate the project to ESM.
Worst part there is no stack trace either.

**Comment by nbouvrette** [comment] 2022-08-08 21:51
This is related to https://github.com/webpack/webpack/issues/13290 (fresh Next.js comments at the bottom of the thread)

For those looking for a workaround, I wrote a Webpack configuration handler in TypeScript.

You can simply use it by setting your `webpack` function in your `next.config.js` to `webpackConfigurationHandler` using the code below:

```ts
import Webpack from 'webpack'

import type { WebpackConfigContext } from 'next/dist/server/config-shared'

/**
 * Next.js did not define any types for its Webpack configs.
 *
 * @see https://github.com/vercel/next.js/blob/canary/packages/next/compiled/webpack/webpack.d.ts
 * @see https://github.com/vercel/next.js/blob/60c8e5c29e4da99ac1aa458b1ba3bdf829111115/packages/next/server/config-shared.ts#L67
 */
export interface WebpackContext extends WebpackConfigContext {
  webpack: typeof Webpack
}

/**
 * Handles the Webpack configuration.
 *
 * @param config - The Webpack configuration options.
 * @param context - The Webpack context
 *
 * @returns A Webpack configuration object.
 */
function webpackConfigurationHandler(
  config: Webpack.Configuration,
  context: WebpackContext
): Webpack.Configuration {
  /**
   * Add support for the `node:` scheme available since Node.js 16.
   *
   * @see https://github.com/vercel/next.js/issues/28774
   */
  config.plugins = config.plugins ?? []
  config.plugins.push(
    new context.webpack.NormalModuleReplacementPlugin(/^node:/, (resource: { request: string }) => {
      resource.request = resource.request.replace(/^node:/, '')
    })
  )

  return config
}

```

**Comment by sebald** [comment] 2022-08-11 09:48
@nbouvrette Thanks for the fix. After that everything works fine, but we get a warning from typescript after adding the plugin.

```
warn  - ../node_modules/.pnpm/typescript@4.7.4/node_modules/typescript/lib/typescript.js
Critical dependency: the request of a dependency is an expression
```

Not sure if this is problematic though.

**Comment by nbouvrette** [comment] 2022-08-11 14:10
@sebald I recall briefly seeing this error and I think I fixed it by deleting the `.next` directory. If this doesn't work, you can check my full implementation [here](https://github.com/Avansai/next-multilingual/blob/3f109e4fd5e42b518826781ee1d2d4a472f524ba/src/config/index.ts#L723) and maybe spot something I a missing. I don't have this error on my end with this implementation.

**Comment by artivilla** [comment] 2022-10-02 05:23
Slight modification I made so I could use the new format using `next@12.3.0` and `webpack@5.74.0`, if this is helpful:

```
const webpack = require("webpack");

module.exports = {
  webpack: (config, options) => {
    config.plugins.push(
      new webpack.NormalModuleReplacementPlugin(/^node:/, (resource) => {
        resource.request = resource.request.replace(/^node:/, "");
      })
    );
    return config;
  },
};

```

**Comment by secretmtgdev** [comment] 2023-03-14 07:18
> Slight modification I made so I could use the new format using `next@12.3.0` and `webpack@5.74.0`, if this is helpful:
> 
> ```
> const webpack = require("webpack");
> 
> module.exports = {
>   webpack: (config, options) => {
>     config.plugins.push(
>       new webpack.NormalModuleReplacementPlugin(/^node:/, (resource) => {
>         resource.request = resource.request.replace(/^node:/, "");
>       })
>     );
>     return config;
>   },
> };
> ```

This is a great workaround!

**Comment by pirtlj** [comment] 2023-04-24 23:12
Sill seeing this in  next@13.3.1

**Comment by Thinkscape** [comment] 2023-04-28 02:37
Could we bump this up?
Even after closing https://github.com/webpack/webpack/issues/13290 and supposed fix in https://github.com/vercel/next.js/pull/45149 merged in Jan, it's still failing.

I've got **code in my middleware.ts** that imports a 3rd party module, which seems to have `@aws-sdk` transient dependency, which dynamically imports `node:file`

```
dev:next: wait  - compiling /src/middleware (client and server)...
dev:next: error - node:fs
dev:next: Module build failed: UnhandledSchemeError: Reading from "node:fs" is not handled by plugins (Unhandled scheme).
dev:next: Webpack supports "data:" and "file:" URIs by default.
dev:next: You may need an additional plugin to handle "node:" URIs.
dev:next: Import trace for requested module:
dev:next: node:fs
dev:next: ./node_modules/.pnpm/strtok3@7.0.0/node_modules/strtok3/lib/FsPromise.js
dev:next: ./node_modules/.pnpm/strtok3@7.0.0/node_modules/strtok3/lib/index.js
dev:next: ./node_modules/.pnpm/file-type@18.3.0/node_modules/file-type/index.js
dev:next: ./node_modules/.pnpm/@keystone-6+core@5.2.0_@aws-sdk+abort-controller@3.310.0_@babel+core@7.21.4_@opentelemetry+ap_eexecvfunafgo67t2ljvtiogxm/node_modules/@keystone-6/core/dist/createSystem-a93ebf95.esm.js
dev:next: ./node_modules/.pnpm/@keystone-6+core@5.2.0_@aws-sdk+abort-controller@3.310.0_@babel+core@7.21.4_@opentelemetry+ap_eexecvfunafgo67t2ljvtiogxm/node_modules/@keystone-6/core/context/dist/keystone-6-core-context.esm.js
dev:next: ./src/keystone/context.ts
dev:next: ./src/server/auth.ts
```

**Comment by CanRau** [comment] 2023-05-11 04:54
wow thanks a lot for clarifying this @Thinkscape always felt there's something off with middleware as I couldn't get mysql2 working which I use in dev locally and was always confused but now that not even cuid2 works got me finally investigating.

This is actually reeaally annoying as so far, I think, middleware is the only place to set cookies on a request without user interaction or calling an api, which is already pretty  annoying but have this middleware limited like this 🥲

Also I'd really like to be able to pass data from middleware to server components/actions and routes (https://github.com/vercel/next.js/discussions/34263#discussioncomment-5821645) which is pretty limiting not being able to do this 😬

**Comment by balazsorban44** [comment] 2023-07-04 11:24
Hi everyone, this should be fixed in newer versions of Next.js, make sure you upgrade (`npm i next@latest`)! I tested the reproduction on top of this issue and it worked.

If you still see an issue and you think it's related, please open a new one with an attached reproduction, thanks! :green_heart:

**Closed by balazsorban44** 2023-07-04 11:24 UTC
Labels: kind: bug, type: needs investigation, area: Compiler

**Comment by nbouvrette** [comment] 2023-07-09 18:27
@balazsorban44 which version should have the fix exactly? I can't find any mention in the release notes of the 2 latest version (`13.4.8` or `13.4.9`)

I tried updating to `13.4.9` and got the following error when removing [my fix](https://github.com/vercel/next.js/issues/28774#issuecomment-1208649870):

```sh
- error node:path
Module build failed: UnhandledSchemeError: Reading from "node:path" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:path
../lib/index.js
```

**Comment by timneutkens** [comment] 2023-07-10 07:02
@nbouvrette It was fixed many releases ago. Keep in mind that `node:` is not supported in client-side code because it's Node.js-only. So e.g. server components or getServerSideProps is fine, other places it'll still error.

**Comment by nbouvrette** [comment] 2023-07-10 12:25
@timneutkens for the explanation - I think I understand what is going on here. The error I am getting is on `import { sep as pathSeparator } from 'node:path'` which is used both by the client and server side.

The reason why it works with my workaround is because the `node:path` module, and specifically the `sep` property, is a bit of a special case. The `sep` property provides the path separator character for the current operating system, which is a simple string ('/' for Unix-based systems, '\\' for Windows). This doesn't rely on any Node.js-specific functionality, so it can be used in the browser without any issues.

Webpack has shims for some Node.js core modules that provide equivalent functionality in the browser, and `path` is one of them. The `path` shim provides the `sep` property, so my code works as expected.

Ideally I would hope that this would work our of the box without having me using special Webpack config. What do you think @timneutkens @balazsorban44 ? Or should I open another issue for this use case?

**Comment by nbouvrette** [comment] 2023-07-10 13:59
Ok I get your point @timneutkens - I suspect for my specific use case the shims are pretty small but I could always try to replace them without having to rely on Webpack so that if you ever decide to drop the default shims my code still work.

**Comment by timneutkens** [comment] 2023-07-11 11:49
Definitely yeah 👍
