### ISSUE TITLE
Cannot read property 'prefetch' and 'push' of null

### ISSUE THREAD

**Issue by kartikag01** [vercel/next.js#16864] opened 2020-09-05 05:48 UTC
# Bug report
Cannot read property 'prefetch' and 'push' of null

**This bug starts coming when I updated the next version from 9.1.4 to 9.5.2 for both production and dev build.**

## Describe the bug
Cannot read property 'prefetch' of null
Cannot read property 'push' of null

```
Uncaught TypeError: Cannot read property 'prefetch' of null
    at prefetch (link.tsx?5e4b:98)
    at eval (link.tsx?5e4b:279)
    at eval (link.tsx?5e4b:60)
    at Array.forEach (<anonymous>)
    at IntersectionObserver.rootMargin (link.tsx?5e4b:51)
```

```
link.tsx?5e4b:144 Uncaught TypeError: Cannot read property 'push' of null
    at linkClicked (link.tsx?5e4b:144)
    at onClick (link.tsx?5e4b:314)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:385)
    at invokeGuardedCallback (react-dom.development.js?61bb:440)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js?61bb:454)
    at executeDispatch (react-dom.development.js?61bb:584)
    at executeDispatchesInOrder (react-dom.development.js?61bb:606)
    at executeDispatchesAndRelease (react-dom.development.js?61bb:713)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js?61bb:722)
    at forEachAccumulated (react-dom.development.js?61bb:694)
    at runEventsInBatch (react-dom.development.js?61bb:739)
    at runExtractedPluginEventsInBatch (react-dom.development.js?61bb:880)
    at handleTopLevel (react-dom.development.js?61bb:5803)
    at batchedEventUpdates$1 (react-dom.development.js?61bb:24401)
    at batchedEventUpdates (react-dom.development.js?61bb:1415)
    at dispatchEventForPluginEventSystem (react-dom.development.js?61bb:5894)
    at attemptToDispatchEvent (react-dom.development.js?61bb:6010)
    at dispatchEvent (react-dom.development.js?61bb:5914)
    at unstable_runWithPriority (scheduler.development.js?3069:697)
    at runWithPriority$2 (react-dom.development.js?61bb:12149)
    at discreteUpdates$1 (react-dom.development.js?61bb:24417)
    at discreteUpdates (react-dom.development.js?61bb:1438)
    at dispatchDiscreteEvent (react-dom.development.js?61bb:5881)
```

## To Reproduce

it's coming when Link Tag is used in the Popover element (https://react-bootstrap-v3.netlify.app/components/popovers/)

```
 <OverlayTrigger
    overlay={(
      <Popover id="popover-saved-item">
        <Link href="/shopping-cart">
          <a><h5>Your Saved Items wishlist</h5></a>
        </Link>
      </Popover>
      )}
  >
Click Popover
  </OverlayTrigger>
```

Click on 

## Expected behavior

the error should not be there.

## Screenshots
![image](https://user-images.githubusercontent.com/10574227/92298391-d3a89e80-ef65-11ea-8ad6-7e95bcba0dbc.png)

## System information
- Version of Next.js: [e.g. 9.5.2]
- Version of Node.js: [e.g. 10.16.0]

## Additional context

When I add `prefetch={false}` to link then the prefetch error doesn`t come while rendering 
but push error is still there on click of the Link

**Comment by olaj** [comment] 2020-09-06 10:57
I had the same issue. But i also had a backlog thing to update my "react-tiny-popover" (from 3 to 5). After i updated it (and fixed the breaking changes) this also seems to have been fixed.

**Comment by timneutkens** [comment] 2020-09-06 15:10
Sounds like the context value is not passed through correctly in the external component you're using.

**Comment by piotrzarycki** [comment] 2020-09-08 04:06
Will fix it :)

**Comment by imdongchen** [comment] 2020-09-10 03:07
I can't reproduce the issue. Seems to work fine https://codesandbox.io/s/cannot-read-property-prefetch-and-push-of-null-16864-5kcj3

**Comment by jdjam** [comment] 2020-09-10 03:42
I've been getting the same issue since v9.5(.0?) but with using sweetalert2-react-content v3.1.0

**Comment by mikerid94** [comment] 2020-09-10 15:20
I've been getting this error in my react-testing-library tests with v9.5 where I am using in the RouterContext
```
...
import Router from 'next/router';
import { RouterContext } from 'next-server/dist/lib/router-context';
...
test('when I click the logo, I am taken to the home page', () => {
  const { getByTestId } = render(
    <RouterContext.Provider value={Router}>
      <Header />
    </RouterContext.Provider>,
  );
...
// trigger Link to be clicked -> "Cannot read property 'push' of null" error
```

I don't have the same error with 9.4.4

**Comment by keubs** [comment] 2020-09-10 16:40
Seeing the same thing as soon as I install Next 9.5. For me, calling `.simulate('click')` on a Next link causes this error, but not on a standard anchor tag. See below:
```
  it('is a test', () => {
    const testSimulate = jest.fn();

    const link = mount(
      <Link href="/test" as="/test" prefetch>
        <a onClick={testSimulate}>test</a>
      </Link>
    );

    const anchor = link.find('a').at(0);

    act(() => {
      anchor.simulate('click');
    });
    expect(testSimulate).toHaveBeenCalled();
  });
```
output:
```
Summary of all failing tests
 FAIL  __tests__/components/utilities/TrackingLink.test.js (10.554s)
   <TrackingLink /> › is a test

    Error: Uncaught [TypeError: Cannot read property 'push' of null]

       97 |
       98 |     act(() => {
    >  99 |       anchor.simulate('click');
          |              ^
      100 |     });
      101 |     expect(testSimulate).toHaveBeenCalled();
      102 |   });
```

conversely, using a standard anchor tag:
```
  it('is a test', () => {
    const testSimulate = jest.fn();

    const link = mount(<a onClick={testSimulate}>test</a>);

    act(() => {
      link.simulate('click');
    });
    expect(testSimulate).toHaveBeenCalled();
  });
```
works fine

**Comment by juliosampaio** [comment] 2020-09-28 20:18
> I've been getting this error in my react-testing-library tests with v9.5 where I am using in the RouterContext
> 
> ```
> ...
> import Router from 'next/router';
> import { RouterContext } from 'next-server/dist/lib/router-context';
> ...
> test('when I click the logo, I am taken to the home page', () => {
>   const { getByTestId } = render(
>     <RouterContext.Provider value={Router}>
>       <Header />
>     </RouterContext.Provider>,
>   );
> ...
> // trigger Link to be clicked -> "Cannot read property 'push' of null" error
> ```
> 
> I don't have the same error with 9.4.4

I'm facing the same issue here @mikerid94

**Comment by Clement-Bresson** [comment] 2020-09-29 09:46
I experience the same error **TypeError: Cannot read property 'push' of null**

` 
> 144 |   router[replace ? 'replace' : 'push'](href, as, { shallow }).then(
      |         ^
  145 |     (success: boolean) => {
  146 |       if (!success) return
  147 |       if (scroll) {
`

Not sure why though. It seems like sometimes `linkClicked` function in null [here](https://github.com/vercel/next.js/blob/canary/packages/next/client/link.tsx#L144)
I  will try to dig into it.

**Comment by mikerid94** [comment] 2020-10-01 11:19
@Clement-Bresson 
Using `import { RouterContext } from  'next/dist/next-server/lib/router-context';` ends up with the error for me:
```
No router instance found.
You should only use "next/router" inside the client side of your app.
```

**Note:** I am using `import { render } from '@testing-library/react';` instead of `ReactDOM.render...` from your example.

**Comment by Regaddi** [comment] 2020-10-01 11:25
I was able to work around the issue by mocking `next/link` instead of `next/router`:

```js
jest.mock('next/link', () => ({ children }) => children);
```

**Comment by juliosampaio** [comment] 2020-10-01 13:22
> I experience the same error **TypeError: Cannot read property 'push' of null**
> 
> Not sure why though. It seems like sometimes `router` passed to `linkClicked` function in null [here](https://github.com/vercel/next.js/blob/canary/packages/next/client/link.tsx#L144)
> I will try to dig into it.
> 
> [Edit]. I found that the link which triggers the bug, in my case, is located inside a `ReactDOM.render` (I parse some content and insert some React component in the middle of some elements, maybe I would need to do this differently but that's another story). And it seems inside this rendered component Next context is indeed not passed (or at least the router). Is there a way to manually give the router context for the next link inside to work ? (**I found solution below to this question**)
> 
> [Edit 2] @juliosampaio @mikerid94 I tried to pass the context as you are doing, but found that error is still hapenning because the Context is not the same. So in the link when router is grabbed from `useRouter`, it's still empty. Using RouterContext from `next/dist/next-server/lib/router-context` instead of from `next-server/dist/lib/router-context` worked for me. So edited solution **working for me**:
> 
> ```
> ...  
> import Router from 'next/router';  
> import { RouterContext } from  'next/dist/next-server/lib/router-context';  
> ...  
> ReactDOM.render(  
>   <RouterContext.Provider value={Router}>  
>      <Link /> // nextJS link  
>    </RouterContext.Provider>  
>  someElement  
> )
> ...
> 
> // trigger Link to be clicked -> Working
> ```
> 
> It might help some people

I can confirm it worked for me as well @Clement-Bresson , thanks!

**Comment by danbergelt** [comment] 2020-10-08 21:59
> @Clement-Bresson
> Using `import { RouterContext } from 'next/dist/next-server/lib/router-context';` ends up with this error for me:
> 
> ```
> No router instance found.
> You should only use "next/router" inside the client side of your app.
> ```
> 
> **Note:** I am using `import { render } from '@testing-library/react';` instead of `ReactDOM.render...` from your example.

+1, experiencing all of the above issues when combining React Testing Library and the Link component. Having to fall back on Cypress, which is suboptimal for integration tests IMO.

**Comment by olaj** [comment] 2020-11-25 10:45
My tests are failing now for more or less each <Link> in Jest tests that i run against "pages". Just wanted to see if anyone else has starting to see this (again) and having a quick fix.

It happened after an upgrade to 10.0.2 (or 10.0.3), it works fine in 10.0.1. Seems to be alot of talk about prefetching in the changelog so maybe one of those PR is to blame.

 To busy to dig into some reproduction at the moment and i will just skip my tests for now, and probably movre these more complicated tests to cypress instead.

**Comment by justincy** [comment] 2020-11-25 17:06
@olaj I'm seeing the same. Tests work fine in 10.0.1 but fail with this prefetch null error in 10.0.3.

I'm using react-testing-library. I don't use router-context.

**Comment by justincy** [comment] 2020-11-25 17:09
This is the problematic line that my tests are complaining about: https://github.com/vercel/next.js/blob/397a375b37ca7727f13d73b36fcc80df61cfc66a/packages/next/client/link.tsx#L49

**Comment by justincy** [comment] 2020-11-25 17:19
The [solution](https://github.com/vercel/next.js/issues/16864#issuecomment-702069418) from @Regaddi to mock `next/link` fixed my test failures.

**Comment by AustinShelby** [comment] 2020-11-26 14:38
I had a different error message `Error: Uncaught [TypeError: Cannot read property 'catch' of undefined]` but also from the `<Link>`.

I managed to fix it by mocking my router like this:

```ts
import React, { ReactElement } from "react";
import { render, RenderResult } from "@testing-library/react";
import { NextRouter } from "next/router";
import "@testing-library/jest-dom";
import { RouterContext } from "next/dist/next-server/lib/router-context";

export const mockRouter: NextRouter = {
  basePath: "",
  pathname: "/",
  route: "/",
  asPath: "/",
  query: {},
  push: jest.fn(),
  replace: jest.fn(),
  reload: jest.fn(),
  back: jest.fn(),
  prefetch: jest.fn().mockResolvedValue(undefined),  // This one fixed it for me
  beforePopState: jest.fn(),
  events: {
    on: jest.fn(),
    off: jest.fn(),
    emit: jest.fn(),
  },
  isFallback: false,
};

export const renderWithRouter = (component: ReactElement): RenderResult => {
  return render(
    <RouterContext.Provider value={mockRouter}>
      {component}
    </RouterContext.Provider>
  );
};
```

and then in my tests, I call `renderWithRouter` instead of `render`.

**Comment by mikerid94** [comment] 2020-11-27 18:57
The failing tests that were throwing this sort of error was pinning my project at Nextv9.4 so I made a stripped back [repo](https://github.com/mikerid94/next-router-testing) to cover all the router tests I needed for Nextv10.

- testing Link component ([commit](https://github.com/mikerid94/next-router-testing/commit/3233540fad881aaa1918dc0a3e4699ea941c27be))
- tests with useRouter ([commit](https://github.com/mikerid94/next-router-testing/commit/52b8f2e3f0a44e7ebaefd0144072777d68afc68e))
- programatically calling Router.push() (e.g. in a redux-saga) ([commit](https://github.com/mikerid94/next-router-testing/commit/3bda2bd5e60969ed3d673df001668e217e09360c))

The router mock I ended up with was very similar to @AustinShelby's:
```javascript
import { RouterContext } from "next/dist/next-server/lib/router-context";

export const routerMock = {
  basePath: "",
  pathname: "/",
  route: "/",
  asPath: "/",
  query: {},
  push: jest.fn().mockResolvedValue(true),
  replace: jest.fn().mockResolvedValue(true),
  reload: jest.fn(),
  back: jest.fn(),
  prefetch: jest.fn().mockResolvedValue(undefined),
  beforePopState: jest.fn(),
  events: {
    on: jest.fn(),
    off: jest.fn(),
    emit: jest.fn(),
  },
  isFallback: false,
};

...
  render(
    <RouterContext.Provider value={routerMock}>
      <Component />
    </RouterContext.Provider>
  );
...
```

**Comment by gko** [comment] 2020-12-05 15:22
> I was able to work around the issue by mocking `next/link` instead of `next/router`:
> 
> ```js
> jest.mock('next/link', () => ({ children }) => children);
> ```

Thank you for solution. A better way of mocking `Link` in case you want to check `href` as well:
```typescript
jest.mock('next/link', () => {
  const React = require('react');
  const { UrlObject } = require('url');

  type Url = string | typeof UrlObject;
  type LinkProps = {
    href: Url;
    as?: Url;
  };

  return ({ children, href }: React.PropsWithChildren<LinkProps>) =>
    React.cloneElement(React.Children.only(children), { href });
});
```

 FYI as of `next` 10 `as` attribute is not necessary anymore.

**Comment by hems** [comment] 2020-12-10 01:39
Any ideas on how to solve this issue on StoryBook ??

We [have created a separate issue](https://github.com/vercel/next.js/issues/1) but it issue got closed as duplicated of this issue

**Comment by tiaanduplessis** [comment] 2020-12-12 11:36
@hems updating `.storybook/preview.js` to the following worked for our use case

```js
import React from "react"; 
import { RouterContext } from  'next/dist/next-server/lib/router-context';  

export const decorators = [
  (Story) => (
    <RouterContext.Provider value={{
      push: () => Promise.resolve(),
      replace: () => Promise.resolve(),
      prefetch: () => Promise.resolve()
    }}>  
      <Story />
    </RouterContext.Provider>
  ),
];
```

**Comment by MontoyaAndres** [comment] 2021-01-05 23:06
same issue as @mikerid94 in version 10.0.1 this error does not exist

**Closed** 2021-01-06 16:19 UTC
Labels: good first issue, kind: story

**Comment by eric-burel** [comment] 2021-01-08 17:20
If I get it right, mocking `next/router` package using a Webpack alias as usual is not enough, because it won't mock the version used by `next/link`, am I right? 
I am not fond of mocking `next/link` either, that affects stories too much. 
So @tiaanduplessis solution is great.

Reading code from the PR #18904 I don't get why it broke suddenly though

**Comment by damusnet** [comment] 2021-01-08 17:48
@eric-burel I don't know about using Webpack aliases.

What happened when it broke is that a feature was introduced that tries to prefetch any internal url as soon as `<Link />` is mounted by default. This used to be disabled by default, and the default was switched if I remember correctly. The issue is that in stories and test, the `<Link />` component is used in isolation, outside the Next.js app, and outside of the `Router` context which provides the `prefetch` function.

In any case, I submitted a patch #19857 that was just merged this week and is included in [the latest release v10.0.5](https://github.com/vercel/next.js/releases/tag/v10.0.5) yesterday, so upgrading to that version should fix it in both tests and stories. Let me know if that is not the case.

**Comment by eric-burel** [comment] 2021-01-09 10:26
I was using Webpack alias to mock imports from `next/router` in my app. But since `next/link` is already built I guess it's too late, the mock is not applied.

I think the blame is not really in Next, but actually in end-user Storybook install. It's perfectly normal to have to setup a decorator to make a framework work (eg loading Material UI theme, adding i18n etc. etc.)., Next is no exception.

So @tiaanduplessis is not only just a quickfix but actually a decorator we may want to have in our Next/Storybook apps to mock the router in any case.
I've updated #19345 so it can become a part of `@next/plugin-storybook`.

**Comment by eric-burel** [comment] 2021-08-30 14:24
Update for Storybook: you can now use this awesome plugin: https://storybook.js.org/addons/storybook-addon-next-router
It works very well and let's you tweak the router mock using parameters of the story, for easy testing of readyness, query params, links...

**Comment by balazsorban44** [comment] 2022-01-27 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
