### ISSUE TITLE
Cannot load WebWorker when deployed to Vercel

### ISSUE THREAD

**Issue by jhaynie** [vercel/next.js#24616] opened 2021-04-29 20:20 UTC
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Cannot use WebWorkers in latest version of next.js.  Support is broken when running in Vercel cloud. I can't tell if it's Webpack 5, Babel or Next but it seems to be related to the contenthash rule of the output filename.

It works locally in dev, but deployed to Vercel causes a 404 for the worker file.

### Expected Behavior

Expect it to load the worker.

### To Reproduce

I've created a minimal NextJS 10.2 example repo that reproduces the bug (and demonstrates a workaround):

https://github.com/jhaynie/nextjs-webworker-bug

This is deployed to vercel at 

https://nextjs-webworker-bug.vercel.app/

If you change `[contenthash]` to `[fullhash]` in webpack, it works.

```
config.output.chunkFilename = "static/chunks/[name].[fullhash].js";
```

**Comment by ijjk** [comment] 2021-04-29 20:23
Closing as a duplicate of https://github.com/vercel/next.js/issues/22813

**Closed by ijjk** 2021-04-29 20:23 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
