### ISSUE TITLE
Custom routes and 404 on client side getServerSideProps access

### ISSUE THREAD

**Issue by davidknezic** [vercel/next.js#11206] opened 2020-03-19 18:43 UTC
# Bug report

## Describe the bug

I'm using custom routes to make translated paths (`/hello`, `/hola`, `/ni-hao`) for my server-side rendered pages (`/hi/[lang].js`).
I then link to them like this:

`<Link href="/hi/[lang]?lang=zh" as="/ni-hao">...</Link>`

Unexpectedly though, a click on that link tries to load the data from `getServerSideProps` by requesting `_next/data/.../ni-hao.json` instead of `_next/data/.../hi/[lang].json`

## To Reproduce

Repo: https://github.com/davidknezic/now-nextjs-issues/tree/now-nextjs-rewrites
Live: https://now-nextjs-rewrites.davidknezic.now.sh

`next.config.js`

```
module.exports = {
  target: 'serverless',
  experimental: {
    async rewrites () {
      return [
        { source: '/hello', destination: '/hi/en' },
        { source: '/hola', destination: '/hi/es' },
        { source: '/ni-hao', destination: '/hi/zh' }
      ]
    }
  }
}
```

`pages/index.js`

```
<Link href="/hi/[lang]?lang=zh" as="/ni-hao">
  <a>ni hao</a>
</Link>
```

`pages/hi/[lang].js`

```
export default function Index () {
  return (
    <h1>hi</h1>
  )
}

export async function getServerSideProps () {
  return {
    props: {}
  }
}
```

## Expected behavior

I'd expect Next.js to fetch server side data based on the links `href` instead of the `as` param.

## System information

- OS: any
- Browser: any
- Version of Next.js: 9.3.1

## Additional context

I host all of this with Now, which currently doesn't seem to understand Next.js rewrites, both in `dev` and productively. Is it planned to introduce this?

**Comment by patricebeutler** [comment] 2020-03-20 21:52
I have exactly the same problem with my website.

**Comment by davidknezic** [comment] 2020-03-21 12:40
@patricebeutler thanks!

I guess you could do this to make your patch work in production, too.

`req.url = req.url.replace(new RegExp('(/_next/data/[^/]+)/[^/]+/startseite.json'), '$1/home.json')`

**Comment by davidknezic** [comment] 2020-03-21 12:56
I was able to make it work by changing `this._getServerData(as)` to `this._getServerData(pathname)` in my local next.js repo:

https://github.com/zeit/next.js/blob/cadc950e2d2eea969ddabf135e9223b2c21108d6/packages/next/next-server/lib/router/router.ts#L618-L624

`this._getStaticData(as)` also uses the `as` param. However, there it might be on purpose.

**Comment by Timer** [comment] 2020-06-29 18:37
This was fixed on the latest Next.js canary version!

**Closed by Timer** 2020-06-29 18:37 UTC

**Comment by pmourer** [comment] 2020-09-02 16:46
Any idea when this will be in a stable release and which version?

**Comment by balazsorban44** [comment] 2022-01-29 14:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
