### ISSUE TITLE
Folder based _app.js/tsx equivalent

### ISSUE THREAD

**Issue by PookMook** [vercel/next.js#13737] opened 2020-06-03 22:25 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

While an application grows, we're still relying on a single _app to keep everything you want to use across pages. This means global CSS, contexts, redux store, etc. 
Some of it could be quite big and only used on few pages but still requires to be on the main single _app.

## Describe the solution you'd like

The best way I see this getting solved is with _app equivalents for nested folders in the pages folder. It doesn't solve every problems that you could encounters and tie your URLs with your logic, but it's a nice middle ground between what we have now and handling routing manually.
This way every pages relying on calendar context for instance could live in pages/calendar/ with a pages/calendar/_section.jsx/tsx handling the calendarContext and other global imports for that section of the app.

## Describe alternatives you've considered

An alternative would be to spawn multiple nextjs instances, one for each section, but now we're entering monorepo problems just to get localized contexts and tools.

## Additional context

First of all, thank you all for your work on nextjs, so far every hiccups we faced had a solution that was OK when we factored in the benefits we get from the nextjs niceties, amazing job!

This one got a little bit thougher as our application grew (as a result of covid-19, we added a lot of features quickly to support retirement home staff through the pandemic), we have a series of context for each sections of the platform that have to live in the _app.tsx.

It's still fine at the moment, but the complexity it adds to keep track of our contexts and reset "activated ones" when navigating away from a section to ensure a clean state on re-entry is growing quickly as well. 
Having the ability to inject an HOC based on folder structure also means we could use heavier tools only on specific sections, like graphQL clients only on sections we use graphQL (or the dreaded moment.js mastodonte)

**Comment by rafaelalmeidatk** [comment] 2020-06-03 23:54
This seems to be a duplicate of #10361. The current workaround is to create a component that wraps all you need and use it in the page components

**Comment by PookMook** [comment] 2020-06-04 00:56
Sadly, doing it this way dismounts the provider and thus resets the value on page changes, which is a bummer, maybe I'm doing it wrong and am just stupid (which is a strong option as well)

**Comment by Pytal** [comment] 2020-06-04 13:53
Instead of having all component nodes in `_app` I've found it cleaner to just extract globally president components into another component and import that into _app.

**Comment by rafaelalmeidatk** [comment] 2020-06-04 20:21
@PookMook yeah you can't avoid the wrapper component from remounting on route changes, currently this is only possible if you render it on `_app`. I will close the issue since it is a duplicate

**Closed by rafaelalmeidatk** 2020-06-04 20:21 UTC

**Comment by balazsorban44** [comment] 2022-01-30 02:14
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
