### ISSUE TITLE
Internationalization capabilities with a full static site (i.e. serverless)

### ISSUE THREAD

**Issue by FarhadG** [vercel/next.js#10040] opened 2020-01-10 18:46 UTC
# Feature request
Internationalization capabilities with a full static site (i.e. serverless)

## Is your feature request related to a problem? Please describe.
Inability to compile a static site with all language ahead of time.

A clear and concise description of what you want and what your use case is.

## Describe the solution you'd like
The ability to provide a static site with multiple languages pre-compiled.

**Comment by anulman** [comment] 2020-04-28 13:12
Working on a solution to this (and other static site permutations) with @iliapir — we are experimenting with:

1. Writing a babel plugin that Inspects the JSX AST for permutable elements (e.g. in our case @marvelapp/react-ab-test `<Experiment>`/`<Variant>` pairs; in OP's case maybe a `<LanguageProvider>`)
    - e.g. `pages/faqs` might have language permutations `en` & `es`
2. Injecting the compiled permutations per-page into `getStaticPaths`, + using `getStaticProps` to compute which permutation to show
    - e.g. `pages/faqs` might emit `pages/faqs_-_en` & `pages/faqs_-_es`
3. Using CDN rules to route traffic to the correct defaults, while also letting React handle dynamic changes (e.g. via a language dropdown).

@FarhadG does this sound like an approach that will solve your statically-compiled internationalization needs? @timneutkens does this look like the right approach within Next.js?

Early feedback is much appreciated, as we suspect this will require monkeying in [`next/build/utils.ts#isPageStatic`](https://github.com/zeit/next.js/blob/canary/packages/next/build/utils.ts#L755-L760) (e.g. by wrapping `mod.getStaticPaths`). If our spike works out, we expect to have a PR ready for comments in a week or three.

**Comment by anulman** [comment] 2020-06-22 17:54
@BiscuiTech @AlexOros — a week or three was a little ambitious. But the PR is up and good to go! #14454 

Note that the CI error is due to the addition of a `path` parameter passed to `getStaticProps({ params: { path } })` for files w/o a dynamic segment.

**Comment by Timer** [comment] 2020-09-14 19:06
Please see the following RFC for first-class i18n support in Next.js:
https://github.com/vercel/next.js/discussions/17078

Thanks!

**Comment by lachlanjc** [comment] 2020-11-18 00:59
This landed! https://nextjs.org/docs/advanced-features/i18n-routing

**Closed** 2020-11-18 11:04 UTC
Labels: type: feature request

**Comment by balazsorban44** [comment] 2022-01-29 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
