### ISSUE TITLE
Static Assets breaking in 9.5.4

### ISSUE THREAD

**Issue by saiichihashimoto** [vercel/next.js#17728] opened 2020-10-08 20:08 UTC
In 9.5.3, referencing the static assets worked but in 9.5.4 it stopped functioning properly.

![image](https://user-images.githubusercontent.com/2819256/95508151-2962d300-0978-11eb-9265-cfeb450ea44a.png)

**Comment by timneutkens** [comment] 2020-10-08 20:10
Duplicate of #17701

**Closed by timneutkens** 2020-10-08 20:10 UTC

**Comment by balazsorban44** [comment] 2022-01-29 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
