### ISSUE TITLE
Dynamic link vars not be interpolated on latest canary version

### ISSUE THREAD

**Issue by followbl** [vercel/next.js#14828] opened 2020-07-03 18:18 UTC
# Bug report

## Describe the bug

https://github.com/vercel/next.js/discussions/14822

happy to report that is is working fine on 9.4.4 - but after seeing if I could reproduce on a next.js/examples paired down repo with the latest canary next.js - it was reproducible. (this could be a functionality changing that I haven't caught in the docs) - but it feels like a bug to me

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. https://github.com/followbl/dynamic-routing
2. Deploy to Vercel
3. Click any post
4. Click any comment
5. View Logs on Vercel
<img width="1079" alt="Screen Shot 2020-07-03 at 2 16 05 PM" src="https://user-images.githubusercontent.com/927065/86491117-ca1d7300-bd37-11ea-8951-5fefb31bd2c2.png">

## Expected behavior

Expect the <Link vars to be interpolated in `getServerSideProps` context - instead they are provided as is in square brackets

## System information
- Version of Next.js: [9.4.5-canary.28]

**Comment by Timer** [comment] 2020-07-06 13:44
Fixed via https://github.com/vercel/vercel/pull/4778 (soon to be released)

**Comment by ijjk** [comment] 2020-07-06 13:50
Hi, @followbl thanks for the report, the fix should be available on stable and canary releases of `@vercel/next` now

**Comment by Timer** [comment] 2020-07-06 14:01
@followbl to try the fix, you'll need to re-deploy your application!

**Comment by followbl** [comment] 2020-07-06 14:01
@ijjk @Timer 🔥

**Comment by Timer** [comment] 2020-07-06 14:22
Please let us know if it works! 🙏

**Comment by timneutkens** [comment] 2020-07-06 15:10
Will close this given @followbl's comment

**Closed by timneutkens** 2020-07-06 15:10 UTC
Labels: kind: bug, point: 2

**Comment by followbl** [comment] 2020-07-06 22:34
@Timer @ijjk deployed and it's working as expected. thanks

**Comment by timneutkens** [comment] 2020-07-07 11:02
Thanks for confirming @followbl 🙏

**Comment by balazsorban44** [comment] 2022-01-29 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
