### ISSUE TITLE
TypeScript types fail with ESM (type: module) + TSConfig module: node16 

### ISSUE THREAD

**Issue by karlhorky** [vercel/next.js#46676] opened 2023-03-02 11:10 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.2.4-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

TypeScript support

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/floral-thunder-44jpww?file=%2Fpages%2Findex.tsx

### To Reproduce

1. Open reproduction above
2. Observe TypeScript error on `dynamic()` function
   ```
   This expression is not callable.
   Type 'typeof import("/project/sandbox/node_modules/next/dynamic")' has no call signatures.
   ```
3. Observe TypeScript error on `Image` component
   ```
   JSX element type 'Image' does not have any construct or call signatures.typescript(2604)
   ```

![Screenshot 2023-03-02 at 12 18 18](https://user-images.githubusercontent.com/1935696/222414098-ed260c80-efda-43b8-9490-957f8a7bc0f9.png)

![Screenshot 2023-03-02 at 12 16 58](https://user-images.githubusercontent.com/1935696/222414003-1e3affd4-a3e7-4466-ba0d-410f8501066a.png)

This occurs with all import paths with slashes into `next` eg:

- `next/dynamic`
- `next/image`
- `next/link`
- `next/navigation`
- `next/script`

### Describe the Bug

The TypeScript types for the imports at the paths mentioned above fail when using:

1. ESM (`"type": "module"` in `package.json`)
2. TSConfig `"module": "node16"`, which was seemingly implemented by @loettz in https://github.com/vercel/next.js/pull/44177

The code however still runs, so it seems to be a problem with the Next.js types and ESM <> CommonJS interop.

I'm guessing that since Next.js is CommonJS, the types of these exports on all `*.d.ts` files are actually wrong:

https://github.com/vercel/next.js/blob/ed51bd870bf00d60ad91b28b0bbbbebb75c135c4/packages/next/link.d.ts#L1-L3

I guess the correct type would actually use the unusual TypeScript syntax `export =`, like my PR over here:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64137/files

cc @andrewbranch @fluggo @cseas @lfades

### Workaround

A workaround is to type the import as the `.default` property, as @kachkaev shows in [this discussion comment](https://github.com/vercel/next.js/discussions/41189#discussioncomment-4026895):

```diff
-import x from "x";
+import _x from "x";
+const x = _x as unknown as typeof _x.default;
```

### Expected Behavior

The import should work out of the box and no TypeScript errors should appear.

### See also

- https://github.com/vercel/next.js/discussions/41189

**Comment by karlhorky** [comment] 2023-03-02 11:26
I'm guessing that since Next.js is CommonJS, the types of these exports on all `*.d.ts` files are actually wrong:

https://github.com/vercel/next.js/blob/ed51bd870bf00d60ad91b28b0bbbbebb75c135c4/packages/next/link.d.ts#L1-L3

I guess the correct type would actually use the unusual TypeScript syntax `export =`, like my PR over here:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64137/files

Also added this to the issue description above.

**Comment by karlhorky** [comment] 2023-03-02 11:30
Indeed, adding this change here fixed the problem:

```diff
 import Link from './dist/client/link' 
 export * from './dist/client/link' 
-export default Link 
+export = Link 
```

@lfades @timneutkens would you accept a PR for this for all `*.d.ts` files?

If you're skeptical of this syntax (I was too at first), there are a bunch of PRs that I have done recently where @andrewbranch has confirmed that this is correct and will not cause problems for other TypeScript configurations.

**Comment by cseas** [comment] 2023-03-02 11:40
I'm able to reproduce this as well [here][1]. To work around this temporarily, I'm building my project with [ignoreBuildErrors][2] config.

[Are The Types Wrong][3] shows that the `next` package is not bundled properly to be consumed by node16 moduleResolution in an ESM project.

<img width="798" alt="Screenshot 2023-03-02 at 5 02 27 PM" src="https://user-images.githubusercontent.com/29686866/222418454-5424b4bd-ef9a-4ef1-bbe5-70a73487ef34.png">

Related bugs:
- https://github.com/vercel/next.js/issues/44095
- https://github.com/vercel/next.js/issues/46267
- https://github.com/vercel/next.js/issues/12557#issuecomment-1427088366

[1]: https://github.com/cseas/blog/blob/main/src/ui/Molecules/Footer.tsx#L4
[2]: https://github.com/cseas/blog/blob/main/next.config.mjs#L28
[3]: https://arethetypeswrong.github.io/

**Comment by balazsorban44** [comment] 2023-03-06 15:37
Closing as duplicate of #46078

**Closed by balazsorban44** 2023-03-06 15:37 UTC
Labels: template: bug, area: TypeScript
