### ISSUE TITLE
12.0.5 Version Document import Error 

### ISSUE THREAD

**Issue by Clzzi** [vercel/next.js#32558] opened 2021-12-16 07:19 UTC
### What version of Next.js are you using?

12.0.5

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

AWS EC2 

### Describe the Bug

I upgraded next package version from 12.0.2 to 12.0.5, But  **Document** in _document.tsx file cause error **Format '() =>any' is not a constructor function format.**  So i can't build my application😥 
How can I solve this error?

### Expected Behavior

I wanted my application to be built well.

### To Reproduce

Error Message(Korean)
![image](https://user-images.githubusercontent.com/62810965/146325565-d1b1335c-a381-413c-ae22-f33fb0fc457c.png)

**Comment by stevenfukase** [comment] 2021-12-16 09:33
Same here

**Comment by timneutkens** [comment] 2021-12-16 09:55
Please update to the latest stable version. This was fixed in 12.0.6

**Closed by timneutkens** 2021-12-16 09:55 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
