### ISSUE TITLE
Creating with-tailwindcss example instead creates with-tailwind-emotion

### ISSUE THREAD

**Issue by almeidaalajoel** [vercel/next.js#40389] opened 2022-09-09 09:45 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

  Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.17.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.3.0
      eslint-config-next: N/A
      react: 18.1.0
      react-dom: 18.1.0

### Which example does this report relate to?

with-tailwindcss

### Describe the Bug

When calling 
`yarn create next-app --example with-tailwindcss test`
or 
`npx create-next-app --example with-tailwindcss test`
the project created is pulled from with-tailwindcss-emotion, rather than with-tailwindcss. 

### Expected Behavior

A project is created from with-tailwindcss example.

### To Reproduce

Call 
`yarn create next-app --example with-tailwindcss test`
or 
`npx create-next-app --example with-tailwindcss test`.

**Comment by balazsorban44** [comment] 2022-09-09 12:28
Thanks for reporting. I was unable to reproduce this on Linux. Might be related to Windows. :thinking:

**Comment by SukkaW** [comment] 2022-09-09 12:32
<img width="841" alt="image" src="https://user-images.githubusercontent.com/40715044/189350393-e25c4e42-f4f9-4832-b3b1-20487bb8ca61.png">

Can't reproduce on macOS either.

**Comment by SukkaW** [comment] 2022-09-09 14:41
@balazsorban44 Sure.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/40715044/189375962-ee457f03-97ef-465c-a2ae-a39814c38376.png">

Full example log, as you can see, no `emotion` from pnpm.

<img width="378" alt="image" src="https://user-images.githubusercontent.com/40715044/189376122-378b69b7-d4d2-45bc-b4c8-ffd7cfd8dde5.png">

And the `package.json`.

**Comment by balazsorban44** [comment] 2022-09-09 15:44
@almeidaalajoel if this is happening to you consistently, could you try to pinpoint which versions of `create-next-app` is causing the issue? The only relevant change I can see somehow is https://github.com/vercel/next.js/pull/40182.


Please run `yarn create next-app@12.2.0 --example with-tailwindcss test`, changing the `12.2.0` version until the installation is correct. This way we could potentially pinpoint which PR introduced this issue.

**Comment by almeidaalajoel** [comment] 2022-09-09 20:40
For some reason, I can't specify version number with yarn - 
`'C:\Users\almei\AppData\Local\Yarn\bin\create-next-app@12.2.0' is not recognized as an internal or external command,
operable program or batch file.
error Command failed.
Exit code: 1
` 
Seems to be same as this error - https://github.com/yarnpkg/yarn/issues/6587 so a bit of a tangent

But npx worked, and yes, 12.2.0 is the correct repo. Can confirm that @canary still has the issue as well. 

Sorry, accidentally closed this.

**Comment by almeidaalajoel** [comment] 2022-09-09 20:54
I've realized I was slightly mistaken - the repo is not pulled from with-tailwindcss-emotion. It seems largely based on the emotion example but it's slightly different. I'm not exactly sure where it's coming from. It is very similar to the with-tailwindcss-emotion repo. The components folder is the same, and it has the same .babelrc specifying emotion, but there is no emotion in the package.json. Not sure if there's a way I can figure out where exactly it's pulling from?

**Comment by agusthas** [comment] 2022-09-11 20:46
> I've realized I was slightly mistaken - the repo is not pulled from with-tailwindcss-emotion. It seems largely based on the emotion example but it's slightly different. I'm not exactly sure where it's coming from. It is very similar to the with-tailwindcss-emotion repo. The components folder is the same, and it has the same .babelrc specifying emotion, but there is no emotion in the package.json. Not sure if there's a way I can figure out where exactly it's pulling from?
> 
> Edit: The readme calls itself the with-tailwindcss example, but it's clearly not the current with-tailwindcss example.

I've checked the examples for `with-tailwindcss-emotion` and `with-tailwindcss`. It seems that the result repo is pulled from both of them and the cli try to merge them.

Later digging on the `create-next-app` on `canary` release, i found this line interesting
https://github.com/vercel/next.js/blob/fc3ef810ba3cfddd7763ad6fc498a6f2cddc3064/packages/create-next-app/helpers/examples.ts#L125

It seems that since both examples folder name `with-tailwindcss` and `with-tailwindcss-emotion` includes the word **with-tailwindcss**, then they both get pulled, extracted, and then merged?

**Comment by balazsorban44** [comment] 2022-09-13 11:42
@agusthas very good catch, I opened a PR to make the path matching more precise when extracting the files. #40513

**Closed** 2022-09-13 20:51 UTC
Labels: kind: bug, area: examples, area: create-next-app
