### ISSUE TITLE
[i18n] Can't refresh the home page and keep the default language after selection

### ISSUE THREAD

**Issue by fromi** [vercel/next.js#18549] opened 2020-10-30 16:38 UTC
# Bug report

## Describe the bug

I use v10 i18n feature. My app default language is 'en', my browser settings is 'fr'.
When I load the root page, I am redirected to '/fr', as expected.
However, if I change the language for 'English', I am redirected to '/', not '/en'. Now if I refresh I am redirected to '/fr' once again, whereas I specifically selected English language earlier.

Suggestion: when changing the locale using Router.push, always keep the locale explicit in the path.

**Comment by fromi** [comment] 2020-11-18 16:00
IMHO, the best way to solve this is to force having a local subpath all the time.
It would have another great benefice: external links!
For example, I implemented Google login on my website. I need to provide a link to the terms of use.
I provided [http://localhost:8080/legal-notice](http://localhost:8080/legal-notice), but a French user is not redirected to http://localhost:8080/fr/legal-notice, which is bad.
If all users were redirected to a local subpath, no matter what, it would solve all my problems.

**Comment by lipoolock** [comment] 2020-12-01 16:33
A merge request has been opened regarding that need https://github.com/vercel/next.js/pull/19035
But apparently something is broken in the CI pipeline... perhaps this is the reason why this has not been yet merged/accepted @Timer ?

By the way, I'm facing the same issue. 
The only way found to never fallback on `/` is actually to force `locale` in the route, like `/en/my-route` but this is not satisfying if you focus on an automatic locale resolving...

**Comment by ijjk** [comment] 2021-09-21 03:16
Closing in favor of https://github.com/vercel/next.js/discussions/18419

**Closed by ijjk** 2021-09-21 03:16 UTC
Labels: kind: bug

**Comment by balazsorban44** [comment] 2022-01-27 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
