### ISSUE TITLE
CSS Styles from unrelated layouts are merged if they have one CSS file in common

### ISSUE THREAD

**Issue by onigoetz** [vercel/next.js#64773] opened 2024-04-19 10:21 UTC
### Link to the code that reproduces this issue

https://github.com/onigoetz/nextjs-css-issue-repro

### To Reproduce

1. build the app and start it (not reproducible in dev mode)
2. go to http://localhost:3000/
3. you should see a green background as defined in its stylesheet

### Current vs. Expected behavior

The background should be green but is red.

The styles from the subpage http://localhost:3000/leakingstyle are applied to http://localhost:3000/ but they have no layout in common and should not. It seems that because they have another CSS file in common they are merged

Another page next to it that has no css file in common does not have this issue : http://localhost:3000/otherstyle

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Jun 2 00:45:15 UTC 2023
  Available memory (MB): 17991
  Available CPU cores: 6
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: 1.22.21
  pnpm: 8.14.1
Relevant Packages:
  next: 14.2.2
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next build (local), Vercel (Deployed)

### Additional context

I tested multiple versions:

* 14.1.4 : OK
* 14.2.0-canary.27: OK
* 14.2.0-canary.28: BROKEN
* 14.2.0 : BROKEN
* 14.2.1 : BROKEN
* 14.2.2 : BROKEN
* 14.3.0-canary.11: BROKEN

Apparently the issue has been introduced in https://github.com/vercel/next.js/releases/tag/v14.2.0-canary.28

I would bet that the issue was introduced in this PR : https://github.com/vercel/next.js/pull/63157

**Comment by astateful** [comment] 2024-04-27 14:30
+1

This issue is directly responsible for a 5-10% performance drop on our SEO optimised pages, in which the Lighthouse "eliminate render blocking resources" diagnostic suggests a savings of 1080ms by removing unused CSS, whereas with 14.1.4 it was around 250ms.

**Comment by alexanderchabo** [comment] 2024-04-29 19:51
Same here, happens only on build. It currently blocks us from upgrading next.js version from 14.1.4 to 14.2.3

**Comment by mvdve** [comment] 2024-05-02 19:28
Unfortunately running in to the same issue where my frontend styles are merged into the backend.

**Comment by iamlinkus** [comment] 2024-05-07 23:25
This actually also happens when there’s no CSS files in common. A single global css (non module) import in one parallel route layout results in those styles being imported in other parallel routes.

**Comment by iamlinkus** [comment] 2024-05-30 10:32
This is super annoying and makes it impossible to use next.js with the payloadcms 3.0, unless you have no global styles (which is rarely the case). Is there any update on this from the next team?

**Comment by samcx** [comment] 2024-06-03 19:22
@onigoetz Thank you for sharing. I can confirm this is an issue we're there is different behavior happening from `next dev / next dev --turbo` and `next build`.

We are taking a look at several CSS issues at the moment and hopefully we can land several fixes at once! Will be sharing updates and testing these <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture>s as we get them.

**Comment by jricaldi** [comment] 2024-06-12 04:51
OMG I am not the only one. I just updated to the lastest version (**14.2.4**). I almost pulled the hair out of my head. xD

**Comment by balatD** [comment] 2024-06-27 07:35
Any updates on this issue? Has anyone found a canary version that doesn't break the merged css files?

**Comment by KnotScientific** [comment] 2024-06-27 20:32
Any updates on this issue?

**Comment by samcx** [comment] 2024-07-01 13:08
No updates yet, but we are indeed prioritizing this issue!

@balatD The CSS merging works as expected versions prior to v14.2.0-canary.28 (just tested on v14.2.0-canary.27).

**Comment by timhettler** [comment] 2024-07-01 21:10
In lieu of a +1 I will just say that my project is stuck on `14.1.x` because of this issue. We are using Sass + CSS Modules, with a single global css file that contains resets and utility classes (i.e. `mobile-only`).

**Closed** 2024-07-05 10:33 UTC
Labels: bug, linear: next

**Comment by samcx** [comment] 2024-07-08 13:33
Hi everyone—

Let us know if canary [v15.0.0-canary.56](https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.56) or higher fixes your issue—we recently shipped a bug fix that changes how we merge global css → https://github.com/vercel/next.js/pull/67373.

@onigoetz I can no longer reproduce the issue!

![CleanShot 2024-07-08 at 16 17 08@2x](https://github.com/vercel/next.js/assets/28912696/f5a0b230-887e-461b-a1a2-892d413a6c79)

![CleanShot 2024-07-08 at 16 16 12@2x](https://github.com/vercel/next.js/assets/28912696/2ce76717-10f1-424e-951e-721428d958a1)

As described in the <picture data-single-emoji=":pr:" title=":pr:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/pr/876af7e7d65e1595.png" alt=":pr:" align="absmiddle"></picture>, the global css file is now a separate chunk (2nd screenshot).

**Comment by timhettler** [comment] 2024-07-18 21:24
@samcx Appreciate that there is progress on this issue - Will these fixes be made in the Next 14.x?

**Comment by samcx** [comment] 2024-07-19 09:49
@timhettler It's been backported to [14.2.5](https://github.com/vercel/next.js/releases/tag/v14.2.5)!
