### ISSUE TITLE
Whole page component re-renders (unmounts) when route changes in 13.2.5-canary.32 - 13.3.0

### ISSUE THREAD

**Issue by panddr** [vercel/next.js#48004] opened 2023-04-06 07:02 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.19
      pnpm: 8.0.0
    Relevant packages:
      next: 13.2.5-canary.32
      eslint-config-next: 13.2.5-canary.32
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

-

### To Reproduce

It's clear from video how dom behaves. Layout component is preserved but page component re-renders completlly not partially

### Describe the Bug

The whole page component is re-rendered (unmounted-mounted) when route, search params change. As a result all react state are lost and etc.

### Expected Behavior

Filter panel should stay opened when filters are applied. As it worsk in next.js 13.2.4

https://user-images.githubusercontent.com/2890580/230296737-7f05b8b0-807d-4ac9-82a1-ecb9c2100b56.mov

**Comment by StephenB-24** [comment] 2023-04-13 00:51
I thought I was going insane and spent a huge portion of the day trying to fix this! Didn't get anywhere on it 😂

Downgrading for now.

**Comment by RobTS** [comment] 2023-04-19 11:34
I suspect this has something to do with whether the routes are available somewhere in a declarative fashion or not. If I programmatically navigate to a route that is available somewhere as a `Link`, all is well. If it is not, I get page reloads.

**Comment by timneutkens** [comment] 2023-05-09 17:22
Duplicate of #48082

**Closed by timneutkens** 2023-05-09 17:22 UTC
Labels: template: bug

**Comment by remorses** [comment] 2023-05-13 12:30
I created an [RFC](https://github.com/vercel/next.js/discussions/49749) to add an option to not reset state on navigation
