### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#19067] opened 2020-11-11 18:43 UTC
```
  ● SSG Prerender › production mode › should reload page on failed data request, and retry

    expect(received).toMatch(expected)

    Expected pattern: /post.*?post-999/
    Received string:  ""

      689 | 
      690 |       const text = await browser.elementByCss('#params').text()
    > 691 |       expect(text).toMatch(/post.*?post-999/)
          |                    ^
      692 |     })
      693 |   }
      694 | 

      at Object.<anonymous> (integration/prerender/test/index.test.js:691:20)
          at runMicrotasks (<anonymous>)

```

**Comment by ijjk** [comment] 2020-12-29 05:55
Closing as this seems to have stabilized, we can re-investigate if this starts flaking again as discussed

**Closed by ijjk** 2020-12-29 05:55 UTC
Labels: kind: bug, point: 2

**Comment by balazsorban44** [comment] 2022-01-29 00:11
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
