### ISSUE TITLE
Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization upgrading from 11.0 to 11.1

### ISSUE THREAD

**Issue by davecarlson** [vercel/next.js#28440] opened 2021-08-24 07:38 UTC
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

14.17.5

### What browser are you using?

Chrome

### What operating system are you using?

Mac OS

### How are you deploying your application?

locally

### Describe the Bug

When compiling typescript files being used with typeorm (0.2.22),  I now get the following error:
ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
    at Module.default (webpack-internal:///./models/client.ts:3:42)
    at eval (webpack-internal:///./models/home.ts:48:90)
    at Object../models/home.ts (/workspace/.next/server/pages/api/v2/candidates/upcoming-dbs-expiry.js:122:1)
    at __webpack_require__ (/workspace/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./models/client.ts:7:63)
    at Object../models/client.ts (/workspace/.next/server/pages/api/v2/candidates/upcoming-dbs-expiry.js:102:1)
    at __webpack_require__ (/workspace/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./models/candidate.ts:7:65)
    at Object../models/candidate.ts (/workspace/.next/server/pages/api/v2/candidates/upcoming-dbs-expiry.js:62:1)
    at __webpack_require__ (/workspace/.next/server/webpack-runtime.js:33:42)
ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization

### Expected Behavior

No Error

### To Reproduce

install next & typeorm 0.2.2
create a typescript model & link

**Comment by rodrigojmr** [comment] 2021-11-05 20:59
This also happens when upgrading from 11.1.2 to 12.x.

What version of Next.js are you using?
12.0.3

What version of Node.js are you using?
v16.13.0

What browser are you using?
Chrome

What operating system are you using?
Windows

How are you deploying your application?
locally

Describe the Bug
error - ReferenceError: Cannot access 'config' before initialization
or
error - Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization

Repo: https://github.com/rodrigojmr/nextjs-error
Sandbox: https://codesandbox.io/s/nextjs-12-webpack-default-error-ipnzk

Just switch versions. It might be tricky on the sandbox, but after a server restart or page refresh it should work.

**Comment by timneutkens** [comment] 2021-11-17 15:48
Closing as no reproduction was provided.

**Closed by timneutkens** 2021-11-17 15:48 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
