### ISSUE TITLE
get(...) is not a function

### ISSUE THREAD

**Issue by ChGGse** [vercel/next.js#21043] opened 2021-01-12 22:38 UTC
**What version of Next.js are you using?**

9.5.5

**What version of Node.js are you using?**

14.15.3

**What browser are you using?**

CryptoTab

**What operating system are you using?**

Windows

**How are you deploying your application?**

npm run dev

**Describe the Bug**

When trying to use Prisma as a function, it tells me get(...) isn't a function.

```js
import Head from "next/head";
import { PrismaClient } from '@prisma/client';
import Nav from '../components/Nav'

const prisma = new PrismaClient();

export async function getServerSideProps({ params }) {
  const users = await prisma.user.findMany({
    where: {
      name: params.toString()
    }
  })

  return {
    props: { users }
  }
}


export default function UserPage({ users }) {
  return (
    <>
      <Head>
        <title>{users.name}</title>
      </Head>
      <Nav />
      <div key={users.id}>
        <h1>{users.name}</h1>
        <p>{users.bio}</p>
      </div>
    </>
  )
}
```

Error from NextJS on the browser:

```
./pages/[...username].tsx
TypeError: E:\libby\libby-web\pages\[...username].tsx: get(...) is not a function
```

**Expected Behavior**

I expected the username endpoint to load with data.

**To Reproduce**

- Create [...username].tsx file
- Use code from above
- Go to localhost:3000/Cheese

**Comment by timneutkens** [comment] 2021-01-13 16:39
Please add a complete reproduction to this issue.

**Comment by ChGGse** [comment] 2021-01-13 17:15
> Please add a complete reproduction to this issue.

I'm not entirely sure what you'd like me to add?

**Comment by timneutkens** [comment] 2021-01-13 17:40
Closing as I checked with the Prisma team and they said it's related to a library you're using (superjson) which is unrelated to Next.js

**Closed by timneutkens** 2021-01-13 17:40 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-01-28 20:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
