### ISSUE TITLE
Wrong import with prisma client and nextJest config

### ISSUE THREAD

**Issue by dstoyanoff** [vercel/next.js#56144] opened 2023-09-28 09:16 UTC
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/thirsty-joji-tgpmz4

### To Reproduce

1. Install dependencies
2. Run `yarn test`

### Current vs. Expected behavior

Fails with the following error, reporting an import from `./client/client`, while the source file only has `./client`;
![image](https://github.com/vercel/next.js/assets/5079334/c078d118-be87-4c84-8bf6-0a0e743157a8)

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 3.6.0
      pnpm: N/A
    Relevant Packages:
      next: 13.5.2
      eslint-config-next: 13.5.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: standalone
```

### Which area(s) are affected? (Select all that apply)

Jest (next/jest), SWC transpilation

### Additional context
- Same setup was working before I upgraded next from 13.1.6
- Overriding the transform in jest config fixes the issue

<sub>[WEB-1682](https://linear.app/vercel/issue/WEB-1682/wrong-import-with-prisma-client-and-nextjest-config)</sub>

**Comment by balazsorban44** [comment] 2023-09-29 00:01
Seems to be a regression introduced in https://github.com/vercel/next.js/compare/v13.4.20-canary.15...v13.4.20-canary.16

We will have a look!

**Comment by dstoyanoff** [comment] 2023-09-29 05:16
I think I have actually isolated it to canary.20, which only has this PR - https://github.com/vercel/next.js/pull/52997

**Comment by dstoyanoff** [comment] 2023-10-16 15:44
Hello @balazsorban44, are there any estimates on when this could be resolved? We are pretty much blocked from upgrading nextjs and missing on other fixes and features.

Any workaround is also useful.

Thanks

**Comment by edwinvrgs** [comment] 2023-10-19 16:04
This is also happening to me, here is the description of the issue: https://stackoverflow.com/questions/77324163/jest-error-after-upgrading-next-js-from-version-12-to-13.

**Comment by edwinvrgs** [comment] 2023-10-20 15:49
I ended up overriding the `transform` property.

What I did:
1. Install `@swc/core` and `@swc/jest`.
2. Adding the following inside `jest.config.ts`:
```ts
transform: {
        "^.+\\.(js|jsx|ts|tsx|mjs)$": [
            "@swc/jest",
            {
                jsc: {
                    transform: {
                        react: {
                            runtime: "automatic",
                        },
                    },
                },
            },
        ],
    },
```

**Comment by dstoyanoff** [comment] 2023-11-29 11:55
Hello @kdy1 @balazsorban44, is there some progress on this? I am still unable to update nextjs in a project because of this

**Comment by kdy1** [comment] 2024-01-03 05:27
This will be fixed by https://github.com/swc-project/swc/pull/8480

**Comment by dstoyanoff** [comment] 2024-01-09 10:43
Hello @kdy1,
After the above was merged, I can confirm the issue is not reproducible, but there is a new issue that happens. For some reason, under tests, jest is trying to resolve the browser version of the prisma client (index-browser.js) instead of the node one. Test environment is set to node, but that doesn't help. Do you have an idea what could be causing that behavior?

**Comment by kdy1** [comment] 2024-01-24 10:27
https://github.com/swc-project/swc/pull/8548 should fix this issue

**Closed** 2024-01-27 09:44 UTC
Labels: template: bug, area: SWC transforms, area: Jest, linear: turbopack
