### ISSUE TITLE
Extending from "plugin:@next/next/recommended" does not apply the rules correctly

### ISSUE THREAD

**Issue by SalahAdDin** [vercel/next.js#26438] opened 2021-06-21 15:47 UTC
### What version of Next.js are you using?

11.0

### What version of Node.js are you using?

14.17.1

### What browser are you using?

Chrome: 91.0.4472.114

### What operating system are you using?

Linux 5.10 Deepin 20.2.1 20.2.1

### How are you deploying your application?

Vercel

### Describe the Bug

We are trying to include the **Next** rules onto our existing project, but it seem to be not applied correctly, creating bugs like [this](https://github.com/mui-org/material-ui/issues/26863#issuecomment-865029181) or the following:
```shell
36:13  Error: 'React' must be in scope when using JSX  react/react-in-jsx-scope
37:13  Error: 'React' must be in scope when using JSX  react/react-in-jsx-scope
40:11  Error: 'React' must be in scope when using JSX  react/react-in-jsx-scope
```

### Expected Behavior

I should apply both `next` and `next/core-web-vitals` at extending by plugin; for instance, since the plugin does disabled [this rule](https://github.com/vercel/next.js/blob/canary/packages/eslint-config-next/index.js#L18), it should not show the aforementioned bug.

### To Reproduce

The following is our `.eslintrc` configuration who generates this issue:
```json
{
  "env": {
    "browser": true,
    "jest": true,
    "es6": true,
    "es2020": true
  },
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2020,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    },
    "project": [
      "./tsconfig.json"
    ]
  },
  "plugins": [
    "@typescript-eslint",
    "import",
    "jsx-a11y",
    "react",
    "react-hooks",
    "prefer-object-spread",
    "prettier"
  ],
  "extends": [
    "eslint:recommended",
    "plugin:testing-library/react",
    "plugin:react/recommended",
    "plugin:react-hooks/recommended",
    "plugin:import/errors",
    "plugin:import/warnings",
    "plugin:import/typescript",
    "plugin:jsx-a11y/recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "plugin:prettier/recommended",
    "plugin:@next/next/recommended"
  ],
  "rules": {
    // https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/docs/rules
    "@typescript-eslint/no-this-alias": "off",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/explicit-module-boundary-types": [
      "warn"
      // {"allowArgumentsExplicitlyTypedAsAny": true}
    ],
    // https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/docs/rules
    "@typescript-eslint/array-type": "error",
    "@typescript-eslint/consistent-type-assertions": "error",
    "@typescript-eslint/consistent-type-imports": "error",
    "@typescript-eslint/prefer-for-of": "error",
    "@typescript-eslint/prefer-optional-chain": "error",
    "import/first": "error",
    // https://github.com/benmosher/eslint-plugin-import
    "import/order": [
      "error",
      {
        "alphabetize": {
          "order": "asc",
          "caseInsensitive": false
        },
        "groups": [
          [
            "builtin",
            "external"
          ],
          "parent",
          [
            "sibling",
            "index"
          ]
        ],
        "newlines-between": "always"
      }
    ],
    "import/newline-after-import": "error",
    "import/no-duplicates": "error",
    "import/no-mutable-exports": "error",
    "no-console": "warn",
    "no-eval": "error",
    // https://eslint.org/docs/rules/
    "no-fallthrough": "off",
    // https://github.com/ionic-team/eslint-config/issues/7
    "no-constant-condition": "off",
    "prefer-object-spread/prefer-object-spread": "error",
    "prefer-template": "error",
    "prettier/prettier": [
      "error",
      {},
      {
        "usePrettierrc": true
      }
    ],
    "react/jsx-filename-extension": [
      1,
      {
        "extensions": [
          ".js",
          ".jsx",
          ".ts",
          ".d.ts",
          ".tsx"
        ]
      }
    ],
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn",
    "react/prop-types": "off"
  },
  "settings": {
    "import/resolver": {
      "node": {
        "paths": [
          "src"
        ],
        "extensions": [
          ".js",
          ".ts",
          ".d.ts",
          ".tsx"
        ]
      }
    },
    "react": {
      "version": "latest"
    }
  }
}
```

**Comment by housseindjirdeh** [comment] 2021-06-21 16:43
The error is being turned off within `eslint-config-next`, not `eslint-plugin-next`. You'll need to extend from that instead of you'd like to use it's configuration:

  "extends": [
    "eslint:recommended",
    "plugin:testing-library/react",
    "plugin:react/recommended",
    "plugin:react-hooks/recommended",
    "plugin:import/errors",
    "plugin:import/warnings",
    "plugin:import/typescript",
    "plugin:jsx-a11y/recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "plugin:prettier/recommended",
    "plugin:@next/next/recommended"
  ],

**Comment by housseindjirdeh** [comment] 2021-06-21 16:59
The error is being turned off within `eslint-config-next`, not `eslint-plugin-next`. `eslint-plugin-next` only provides Next.js-specific rules and you'll need to extend from the shareable config instead of you'd like to use it's entire configuration:

<pre><code>
"extends": [
  //...,
  "next",
  <del>"plugin:@next/next/recommended"</del>
],
</pre></code>

Now if you do just this, you're most likely going to see conflict errors since many plugins in your config are also installed in the `next` config. So you have two options:

1. Update your `.eslintrc` config to remove any duplicate settings from `next` if you would like to extend from it. You'll have to manually go through your `.eslintrc` and update/remove any duplicate `plugins`, `settings`, etc... and it would end up looking something like this:

<pre><code>
{
  "env": {
    "jest": true
  },
  "plugins": [
    "@typescript-eslint",
    "prefer-object-spread",
    "prettier"
  ],
  "extends": [
    "eslint:recommended",
    "plugin:testing-library/react",
    "plugin:import/errors",
    "plugin:import/warnings",
    "plugin:import/typescript",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "plugin:prettier/recommended",
    <strong>"next",</strong>
  ],
  "rules": {
    // Your entire list of rules
  }
}
</code></pre>

You'll need to verify if this works correctly ^

2. Include the plugin to keep your same configuration but only add **Next.js specific rules**. You'll have to manually turn off any rules that you would rather not have.

```
{
  "extends": [
    //...
    "plugin:@next/next/recommended"
  ],
  "rules": {
    // Your entire list of rules,
    "react/react-in-jsx-scope": "off"
  }
}
```

Hope this helps! Happy to re-open the issue if there's a specific issue that can be fixed within the codebase/ESLint settings.

**Closed by housseindjirdeh** 2021-06-21 16:59 UTC
Labels: template: bug

**Comment by SalahAdDin** [comment] 2021-08-05 10:54
@housseindjirdeh can i use the new feature having a `.eslint` file configuration? do i need to delete it?

**Comment by SalahAdDin** [comment] 2021-08-08 19:46
@housseindjirdeh can i use the new feature having a `.eslint` file configuration? do i need to delete it?

**Comment by balazsorban44** [comment] 2022-01-28 00:12
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
