### ISSUE TITLE
Allow Babel config file name `.babelrc.json`

### ISSUE THREAD

**Issue by ghost** [vercel/next.js#11599] opened 2020-04-02 13:28 UTC
# Feature request
On the Babel website it states you are allowed to use the `.babelrc.json` file name when creating a configuration file. With Next.js, this does not work. Only `.babelrc` is allowed. I believe it would be clearer and less error prone if Next.js would allow more Babel configuration file names.  

## Is your feature request related to a problem? Please describe.
When you accidentally use `.babelrc.json`, you are not notified of this. The only difference between `.babelrc.json` and `.babelrc` currently is the console message `Using external Babel configuration` which is easy to miss.

## Describe the solution you'd like

If allowing more file names is not an option, please warn the user if Next.js found a `.babelrc.json` file in the project directory so the user knows they've made a mistake. Also, please update the docs to more clearly warn the user that only exactly this file name is allowed

## Describe alternatives you've considered

Allowing just `.babelrc` is very limiting, especially because the Babel documentation talks about multiple allowed file names. This causes confusion and can cause problems (Babel plugins not working) that are hard to debug because there is no warning about using the wrong file name.

**Comment by Pytal** [comment] 2020-04-02 17:16
The documentation explicitly mentions `.babelrc` although it successfully uses the `babel` field in `package.json` in my experience.

I had assumed that `next` allowed Babel itself to resolve config files but if that is not the case then Babel config resolution should be left up to Babel to ensure compatibility with all config files conventions.

**Comment by timneutkens** [comment] 2020-04-03 07:39
> I had assumed that next allowed Babel itself to resolve config files but if that is not the case then Babel config resolution should be left up to Babel to ensure compatibility with all config file conventions.

This is already the case.

**Comment by JensMeindertsma** [comment] 2020-04-03 14:15
Alright, so if Next leaves this up to Babel, why does a `.babelrc.json` file not get picked up properly when using create-next-app?

**Comment by Timer** [comment] 2020-09-10 19:37
Closing as OP is now a ghost (deleted account)

**Closed by Timer** 2020-09-10 19:37 UTC

**Comment by marceloverdijk** [comment] 2020-12-04 23:12
@Timer  I have the same issue.

It seems `.babelrc.json` is not being picked up, although babel docs mentions it is a valid name.

I wanted to use `.babelrc.json` - instead of `.babelrc` (which is working) - to be consistent with my `.eslintrc.json` and `.prettierrc.json` config files.

**Comment by balazsorban44** [comment] 2022-01-29 01:24
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
