### ISSUE TITLE
Image component can't work with contained non-latin symbols in src prop

### ISSUE THREAD

**Issue by haw0k** [vercel/next.js#19668] opened 2020-11-29 22:42 UTC
# Bug report

## Describe the bug

If src prop of next/image component contained non-Latin (Cyrillic in the followed example) symbols, GET request to this resource are always throw the 404 error

## To Reproduce

<Image src="01-тест.jpg" alt="test image with cyrillic src prop" layout="fill" />

## Expected behavior

Got the image

## Screenshots

Screenshot added

## System information

- OS: [Ubuntu]
- Browser [chrome, firefox]
- Version of Next.js: [10.0.3]
- Version of Node.js: [10.0, 12.0]
- Deployment: [next build, next start]

## Additional context

None
![Screen-2020-11-30_00-34-14](https://user-images.githubusercontent.com/17044655/100555461-4777f000-32a4-11eb-9129-24d721a79288.jpg)

**Comment by gelbartj** [comment] 2020-12-22 22:38
Unable to reproduce on macOS. I used the exact same filename and directory structure, including using webp, and it works fine for me.
<img width="1040" alt="Screen Shot 2020-12-22 at 3 33 23 PM" src="https://user-images.githubusercontent.com/8950606/102939434-8811f600-446b-11eb-887d-5f069c770231.png">

**Comment by haw0k** [comment] 2020-12-23 07:53
> <img alt="Screen Shot 2020-12-22 at 3 33 23 PM" width="1040" src="https://user-images.githubusercontent.com/8950606/102939434-8811f600-446b-11eb-887d-5f069c770231.png">

you are using next version 1.0.3?

**Comment by gelbartj** [comment] 2020-12-24 17:19
Yes, works on 10.0.3 and 10.0.4.

**Comment by haw0k** [comment] 2020-12-24 23:40
looks like the problem fixed in 1.0.4 - I can't reproduce this error with version 1.0.4

**Comment by emarforio** [comment] 2021-02-19 13:59
I had the same issue so I did some further investigation and it is not fixed as of 10.0.6. The problem only seem to appear in production (when running `npm run build && npm run start`) and not in development mode (`npm run dev`). I have tried this on a couple of devices, (Windows, Ubuntu & Alpine in Docker) and the same result can be seen when switching to production from dev. Files containing only ASCII-characters work fine but files with other characters get a 404 response from the image service. The file can be downloaded fine if opened or linked to the public resource so it seems like the issue lies within the image service.

**Comment by stefanprobst** [comment] 2021-08-03 04:35
@emarforio could you check if you can still reproduce this issue in the current `canary` version? i think this might have been fixed by #27671

**Comment by emarforio** [comment] 2021-08-03 11:44
@stefanprobst I can confirm that it works with the canary version. I created a repo as a PoC with the two different versions if you want to test it as well: [https://github.com/emarforio/nextjs-nonascii-test](https://github.com/emarforio/nextjs-nonascii-test)

**Comment by styfle** [comment] 2021-08-03 14:02
Thanks! I'll close this as a duplicate of #27210 which was fixed in [v11.0.2-canary.25](https://github.com/vercel/next.js/releases/tag/v11.0.2-canary.25)

As a reminder, you can try it out canary with `yarn add next@canary`, thanks!

**Closed by styfle** 2021-08-03 14:02 UTC
Labels: kind: bug, type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-28 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
