### ISSUE TITLE
Partial Prerendering not available in request dependent route

### ISSUE THREAD

**Issue by sumiren** [vercel/next.js#63504] opened 2024-03-20 05:09 UTC
### Link to the code that reproduces this issue

https://github.com/sumiren/tsume/blob/main/frontend/src/app/page.tsx

### To Reproduce

In codebase above, delete `export const runtime = 'edge'`

### Current vs. Expected behavior

Current:

```
Error: Clerk: auth() and currentUser() are only supported in App Router (/app directory).
If you're using /pages, try getAuth() instead.
Original error: Error: Route / needs to bail out of prerendering at this point because it used headers. React throws this special object to indicate where. It should not be caught by your own try/catch. Learn more: https://nextjs.org/docs/messages/ppr-caught-error
```

Expected:

PPR should be applied. It is certain that this route relies on the request header (via the Clerk server-side SDK), but this is only within the scope of suspense and should not impact PPR.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020
  Available memory (MB): 98304
  Available CPU cores: 12
Binaries:
  Node: 21.6.2
  npm: 10.2.4
  Yarn: N/A
  pnpm: 8.15.4
Relevant Packages:
  next: 14.2.0-canary.33 // Latest available version is detected (14.2.0-canary.33).
  eslint-config-next: 14.1.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

I'm not sure my expectation is correct.
If my expectation is valid, I will provide more out-of-the-box reproduction code.
Thanks!

**Comment by magnusriga** [comment] 2024-09-18 18:31
Hi @sumiren. I am also getting this error using PPR with Next.js 15.

> Unhandled Rejection: Error: Route / needs to bail out of prerendering at this point because it used headers. React throws this special object to indicate where. It should not be caught by your own try/catch. Learn more: https://nextjs.org/docs/messages/ppr-caught-error
>     at t.unstable_postpone (/var/task/node_modules/.pnpm/next@15.0.0-canary.67_@babel+core@7.25.2_@opentelemetry+api@1.9.0_babel-plugin-macros@3.1.0_r_ptpaedjckrw2odtvs4rowq7xge/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:108:7223)
>     at p (/var/task/apps/nfront-academy/.next/server/chunks/544.js:1:62808)
>     at l (/var/task/apps/nfront-academy/.next/server/chunks/544.js:1:62055)
>     at h (/var/task/apps/nfront-academy/.next/server/chunks/951.js:6:3887)
>     at /var/task/apps/nfront-academy/.next/server/chunks/42.js:377:147118
>     at w (/var/task/apps/nfront-academy/.next/server/chunks/462.js:21:10260)
>     at ek (/var/task/node_modules/.pnpm/next@15.0.0-canary.67_@babel+core@7.25.2_@opentelemetry+api@1.9.0_babel-plugin-macros@3.1.0_r_ptpaedjckrw2odtvs4rowq7xge/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:116:12471)
>     at e (/var/task/node_modules/.pnpm/next@15.0.0-canary.67_@babel+core@7.25.2_@opentelemetry+api@1.9.0_babel-plugin-macros@3.1.0_r_ptpaedjckrw2odtvs4rowq7xge/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:116:16167)
>     at eI (/var/task/node_modules/.pnpm/next@15.0.0-canary.67_@babel+core@7.25.2_@opentelemetry+api@1.9.0_babel-plugin-macros@3.1.0_r_ptpaedjckrw2odtvs4rowq7xge/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:116:16650)
>     at Array.toJSON (/var/task/node_modules/.pnpm/next@15.0.0-canary.67_@babel+core@7.25.2_@opentelemetry+api@1.9.0_babel-plugin-macros@3.1.0_r_ptpaedjckrw2odtvs4rowq7xge/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:116:13923) {
>   '$$typeof': Symbol(react.postpone)
> }
> Node.js process exited with exit status: 128. The logs above can help with debugging the issue.

Were you able to figure out what the reason for the error is?

I have checked all try..catch clauses and they are not catching the error. I have also removed all `loading.tsx`, `not-found.tsx`, and `error.tsx`, but still no luck.

**Comment by ztanner** [comment] 2024-09-20 03:03
The error in the original reproduction looks like it was fixed by https://github.com/clerk/javascript/pull/2518 on the Clerk side - I suggest updating your Clerk dependencies. 

If anyone else is running into this problem, please open a new issue with a reproduction. Closing this as the original reproduction appears to be resolved after upgrading.

**Closed by ztanner** 2024-09-20 03:03 UTC
Labels: bug
