### ISSUE TITLE
react-dev-overlay ally.js causes MutationObserver infinite loop

### ISSUE THREAD

**Issue by dminkovsky** [vercel/next.js#17100] opened 2020-09-15 03:51 UTC
# Bug report

## Describe the bug

react-dev-overlay uses ally.js, which [registers and responds to DOM mutations](https://github.com/medialize/ally.js/blob/b8fd3cdbb9464df08708f11cba35b7481ad846d4/src/observe/shadow-mutations.js#L17-L18) using a MutationObserver. If other MutationObservers are present, this can yield an infinite loop of mutation observing and mutating. 

Specifically, in my case, I am using ProseMirror, which also observes the DOM. When the overlay opens and a ProseMirror instance is present, an infinite loop occurs.

Here's how it goes:

**1 - The overlay initializes in a `useEffect`. As part of its initialization, it mutates the DOM**

<img width="1194" alt="Screen Shot 2020-09-14 at 11 33 39 PM" src="https://user-images.githubusercontent.com/218725/93162969-eea4ac80-f6e3-11ea-8e88-2614b7252036.png">

**2 - ProseMirror detects this mutation, and mutates the DOM too,**

<img width="1193" alt="Screen Shot 2020-09-14 at 11 34 11 PM" src="https://user-images.githubusercontent.com/218725/93163265-aafe7280-f6e4-11ea-986a-840c7823ceb5.png">

**3 - ally.js's MutationObservers detect the mutation, and perform their own mutations**

<img width="1194" alt="Screen Shot 2020-09-14 at 11 34 41 PM" src="https://user-images.githubusercontent.com/218725/93163286-b94c8e80-f6e4-11ea-898d-4808e081a506.png">

And round and round it goes from there... every time I get an error on this route, I have to kill the tab in task manager! It's really painful. Now that I've identified the error, I think I might edit node_modules to disable the underlying cause, but a proper solution would be great.

Thank you!

## System information

- Version of Next.js: [e.g. 6.0.2]  9.5.3

## Update ## 

Indeed, commenting the ally initialization code from the `useEffect` in overlay resolves the issue locally.

**Comment by lachlanjc** [comment] 2021-01-01 19:29
Any chance #20647 fixes this?

**Comment by dminkovsky** [comment] 2021-01-01 20:02
Wow @lachlanjc thanks for noticing the connection to this issue. I will keep an eye on #20647 landing in a release and will test it out when it hits NPM. Judging from the diff I don't think it will make a difference, but maybe this vendored version of ally will not cause this problem. Thanks a lot.

**Comment by Timer** [comment] 2021-01-01 20:43
This should be fixed in `next@canary`, please give it a try!

**Closed** 2021-01-01 20:43 UTC

**Comment by dminkovsky** [comment] 2021-01-05 02:15
@Timer @lachlanjc Yes, this issue is gone in `10.0.5-canary.9`. Thanks again!

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
