### ISSUE TITLE
[i18n] i18n breaks optional catch-all route for index

### ISSUE THREAD

**Issue by herrstucki** [vercel/next.js#19934] opened 2020-12-07 17:04 UTC
# Bug report

## Describe the bug

Under the following conditions, the index page can't be accessed:

- i18n configured
- top-level optional catch-all route `pages/[[...slug]].tsx`
- `fallback: false` is used in `getStaticPaths`

Changing any of those will "fix" the problem:

- Disabling i18n
- Moving the catch-all route to a sub-path like `pages/blog/[[...slug]].tsx`
- Using `fallback: "blocking"`

Obviously, it should work nontheless ;)

## To Reproduce

1. Go to https://codesandbox.io/s/practical-meitner-iq7pj
2. The index page https://iq7pj.sse.codesandbox.io/ shows a 404
3. Any other page https://iq7pj.sse.codesandbox.io/another will work

## System information

- Version of Next.js: 10.0.3 and 10.0.4-canary.2
- Version of Node.js: 14
- Deployment: next dev

**Comment by ijjk** [comment] 2021-01-01 04:36
Hi, it looks like this was fixed in [this PR](https://github.com/vercel/next.js/pull/20509) which is available in the latest version of Next.js `v10.0.5-canary.6`, please update and give it a try!

**Closed by ijjk** 2021-01-01 04:36 UTC
Labels: kind: bug, point: 1

**Comment by herrstucki** [comment] 2021-01-04 16:40
@ijjk I can confirm that this is also fixed per 10.0.5-canary.9 https://codesandbox.io/s/reverent-cartwright-txrem 👍

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
