### ISSUE TITLE
yarn dev crashes

### ISSUE THREAD

**Issue by M1ck0** [vercel/next.js#22923] opened 2021-03-09 21:54 UTC
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

15.10.0

### What browser are you using?

Chrome, Firefox, Brave

### What operating system are you using?

Linux

### How are you deploying your application?

n/a

### Describe the Bug

While in development using `yarn dev` process just crashes with this error message
```
.../node_modules/next/dist/server/hot-reloader.js:16
delete _onDemandEntryHandler.entries[page];return;}_onDemandEntryHandler.entries[page].status=_onDemandEntryHandler.BUILDING;const pageLoaderOpts={page,absolutePagePath};entrypoints[isClientCompilation?clientBundlePath:serverBundlePath]=isClientCompilation?`next-client-pages-loader?${(0,_querystring.stringify)(pageLoaderOpts)}!`:absolutePagePath;}));return entrypoints;};}const multiCompiler=(0,_webpack.webpack)(configs);(0,_output.watchCompilers)(multiCompiler.compilers[0],multiCompiler.compilers[1]);// Watch for changes to client/server page files so we can tell when just

TypeError: Cannot set property 'status' of undefined
    at .../node_modules/next/dist/server/hot-reloader.js:16:94
    at async Promise.all (index 0)
    at async DynamicEntryPlugin.config.entry (.../node_modules/next/dist/server/hot-reloader.js:15:96)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

The process should not crash until manually stopped

### To Reproduce

I am not sure how to reproduce this. Sometimes it crashes after 10 seconds sometimes after 10 minutes but it always does crash eventually.

**Comment by possibilities** [comment] 2021-03-23 11:20
Same problem. I've been using 9.5.5 to avoid this. Can we reopen or should I open a new one?

**Comment by M1ck0** [comment] 2021-03-23 11:28
> Same problem. I've been using 9.5.5 to avoid this. Can we reopen or should I open a new one?

I'll reopen this one then. But it seems no one is interested so far.

**Comment by possibilities** [comment] 2021-03-23 11:31
Thank you. I'll add that I'm also on linux (ubuntu).

**Comment by possibilities** [comment] 2021-03-25 15:30
I'm poised to look further into this because it's cramping up some things I'm trying to accomplish. @M1ck0 I have an untested theory that it only happens with large amounts of data. In my case it's coming from an API that is not part of the next project so maybe something to do with SSR + large amount of data? Let me know if that resonates with you at all. Also maybe worth change `next start` to e.g. "n/a" in the description?

**Comment by M1ck0** [comment] 2021-03-25 15:33
It happens to me when there are no API calls at all. I was only doing Front-End stuff and then it randomly crashes. Sometimes after 5 sometimes after 20 minutes, but it always does happen.

**Comment by bemlw** [comment] 2021-04-06 09:55
Same here, just working on some style amends, no API calls. After about 15, 20 minutes it crashes and I have to restart the server:
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

Happens about twice a day

**Comment by possibilities** [comment] 2021-04-06 11:00
I experience this on 9.5.5. Different I think.

**Comment by bunyk** [comment] 2021-04-14 17:51
Same happens for me on "next": "10.1.3", Node v15.0.1:


```
TypeError: Cannot set property 'status' of undefined
    at /home/tbunyk/projects/blog/node_modules/next/dist/server/hot-reloader.js:16:94
    at async Promise.all (index 0)
    at async DynamicEntryPlugin.config.entry (/home/tbunyk/projects/blog/node_modules/next/dist/server/hot-reloader.js:15:96)
```

**Comment by bunyk** [comment] 2021-04-14 17:59
Probably problem is here: https://github.com/vercel/next.js/blob/0af3b526408bae26d6b3f8cab75c4229998bf7cb/packages/next/server/hot-reloader.ts#L331

**Comment by bunyk** [comment] 2021-04-14 18:14
So entries is a object defined in other place: https://github.com/vercel/next.js/blob/0af3b526408bae26d6b3f8cab75c4229998bf7cb/packages/next/server/on-demand-entry-handler.ts#L19

And who know what could delete keys from there, while that function `await`s response from filesystem for some path. I would suggest just add a check if entry for page is present and return if not, since it got updated during that await.

**Comment by bunyk** [comment] 2021-04-14 18:19
I myself will probably just go to `node_modules/next/dist/server/hot-reloader.js:16:94`, find `_onDemandEntryHandler.entries[page].status=_onDemandEntryHandler.BUILDING;`, and prefix it with 

`if(!('status' in _onDemandEntryHandler.entries[page]))return;`

Will see if it will help. :)

**Comment by M1ck0** [comment] 2021-04-18 09:15
@timneutkens 

For reproduction just create a new project, but the thing is that it happens randomly. Even when there are no third-party packages installed. It just happens.

**Comment by M1ck0** [comment] 2021-04-26 20:03
Since this doesn't happen anymore I'll close this issue for now. If it occurs again I'll reopen it

**Comment by Munien** [comment] 2021-05-12 22:17
Same problem for me here - doing this repeatedly every couple minutes

**Comment by timneutkens** [comment] 2021-11-17 14:52
Next.js 12 has much better memory management through a bunch of optimizations we did to webpack. Unfortunately we can't verify it against your particular case as no reproduction was provided so I'll close this issue.

**Closed by timneutkens** 2021-11-17 14:52 UTC
Labels: please add a complete reproduction
