### ISSUE TITLE
next build fails when using styled-components

### ISSUE THREAD

**Issue by cullophid** [vercel/next.js#16102] opened 2020-08-12 07:13 UTC
# Bug report

## Describe the bug

The "Automatically optimizing pages" build step fails when using styled-components (with plugin)

## To Reproduce
I do not have the same issue on other next projects, but here is some info:

```
npm run build

> cylindo-platform@ prebuild /Users/andreasmoller/code/cms-frontend
> npm run codegen:react && node setupEnvironment.js


> cylindo-platform@ codegen:react /Users/andreasmoller/code/cms-frontend
> graphql-codegen --config codegen.react.yml

  ✔ Parse configuration
  ✔ Generate outputs

> cylindo-platform@ build /Users/andreasmoller/code/cms-frontend
> NODE_OPTIONS=--max_old_space_size=8192 next build

info  - Loaded env from /Users/andreasmoller/code/cms-frontend/.env.production
info  - Loaded env from /Users/andreasmoller/code/cms-frontend/.env
info  - Using external babel configuration from /Users/andreasmoller/code/cms-frontend/.babelrc
[BABEL] Note: The code generator has deoptimised the styling of /Users/andreasmoller/code/cms-frontend/src/generated/graphql.ts as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/andreasmoller/code/cms-frontend/src/generated/graphql.ts as it exceeds the max of 500KB.
Creating an optimized production build  

Compiled successfully.


> Build error occurred
TypeError: Cannot read property 'b' of undefined
    at Object.C (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:15104:85)
    at Object.3h+p (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:656:60)
    at __webpack_require__ (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:23:31)
    at Object.LJdJ (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:15171:21)
    at __webpack_require__ (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:23:31)
    at Object.P+uG (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:17244:15)
    at __webpack_require__ (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:23:31)
    at Module.i6+/ (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:22419:83)
    at __webpack_require__ (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:23:31)
    at Object.0 (/Users/andreasmoller/code/cms-frontend/.next/server/pages/404.js:342:18) {
  type: 'TypeError'
}
Automatically optimizing pages .npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cylindo-platform@ build: `NODE_OPTIONS=--max_old_space_size=8192 next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cylindo-platform@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andreasmoller/.npm/_logs/2020-08-12T07_07_49_184Z-debug.log
```

.babelrc:
```
{
  "presets": ["next/babel"],
  "plugins": [["styled-components", { "ssr": true, "displayName": true }]]
}
```

tsconfig.json:
```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "lib": [
      "ES2015",
      "ES2019",
      "ES2020",
      "DOM"
    ],
    "module": "esnext",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "es6",
    "paths": {
      "cylindo-ui": [
        "src/components/cylindo-ui@next"
      ],
      "src/*": [
        "src/*"
      ],
      "api-src/*": [
        "api-src/*"
      ]
    },
    "noEmit": true
  },
  "include": [
    "src",
    "api",
    "api-src/src"
  ],
  "exclude": [
    "./node_modules",
    "api-src/node_modules"
  ]
}
```

## System information

- OS: [e.g. macOS]
- Version of Next.js: [e.g. 9.5.1]
- Version of Node.js: [e.g. 12.18.3]
- Version of styled-components: [e.g. 5.1.1]

**Comment by timneutkens** [comment] 2020-08-12 07:36
We can't investigate issues like these without a clear and concise reproduction. Please provide a github repository.

**Comment by cullophid** [comment] 2020-08-12 07:48
> We can't investigate issues like these without a clear and concise reproduction. Please provide a github repository.

Unfortunately Its in a private repo, with sensitive information.

Next dev works fine, it only happens during the optimized build.

This is the module that is not compiling properly, Since it only happens during the optimized build, my best guess is that its related to tree shaking?

```
import styled, { css } from "styled-components";
import { colors } from "../../theme/theme";
import { SpaceProps, space, text, TextProps } from "../../styled/styled-utils";

type PropTypes = {
  children: React.ReactNode;
  onClick?: (e: React.MouseEvent<HTMLParagraphElement>) => void;
} & React.HTMLAttributes<HTMLParagraphElement> &
  SpaceProps &
  TextProps;

export const pStyle = css`
  color: ${colors.text};
  text-align: left;
  font-weight: 400;
  font-size: 12px;
  margin-bottom: 20px;
`;

export const P = styled.p<PropTypes>`
  ${pStyle};
  ${space};
  ${text};

  ${props =>
    props.overflow &&
    css`
      overflow: hidden;
      display: -webkit-box;
      -webkit-line-clamp: 3;
      -webkit-box-orient: vertical;
      text-overflow: ellipsis;
    `};
`;

export default P;

```

**Comment by timneutkens** [comment] 2020-08-12 07:51
You can create a separate repository that can be shared, we don't need access to your project.

**Comment by Timer** [comment] 2020-09-03 02:31
Closing as no reproduction provided.

**Closed by Timer** 2020-09-03 02:31 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
