### ISSUE TITLE
Node libs can't be imported in _app

### ISSUE THREAD

**Issue by caenguidanos** [vercel/next.js#37598] opened 2022-06-09 18:23 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101

    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: N/A
      pnpm: 7.1.0

    Relevant packages:
      next: 12.1.6
      react: 18.1.0
      react-dom: 18.1.0

### Describe the Bug

Webpack can't load correctlly node libs imported in `_app.{tsx}`.

>error - node:util
Module build failed: UnhandledSchemeError: Reading from "node:util" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.

### Expected Behavior

The same behavior as the rest of the app. It's working in all places and not in `_app.{tsx}`.

### To Reproduce

Clone this [repo](https://github.com/caenguidanos/import-node-lib-repro-nextjs), install and run.

**Comment by balazsorban44** [comment] 2022-06-13 10:41
Duplicate of #28774

**Closed by balazsorban44** 2022-06-13 10:41 UTC
Labels: template: bug
