### ISSUE TITLE
Not working with PNPM

### ISSUE THREAD

**Issue by zefexdeveloper** [vercel/next.js#16471] opened 2020-08-22 12:55 UTC
# Bug report

## Describe the bug

I tried using Next.js with Rush.js which is a tool that helps developers create and maintain monorepo projects. It has support for NPM, Yarn and PNPM.
I tried using with PNPM cause it's really good compared to Yarn and NPM but I was surprised that it wasn't working with Next.js.
Next.js is working only with Yarn and NPM and it appears that Next.js's server-renderer bundler is not correctly externalizing modules with PNPM.

## To Reproduce

https://github.com/zefexdeveloper/nextjs-pnpm

You can clone the repository and follow the readme. There's also a `yarn` branch with a working example.

## Expected behavior

It should work just like with Yarn/NPM.

## Additional context

I would like to invite @octogonz (Rush.js), @timneutkens @Timer (Next.js) and @zkochan (PNPM). Great people that are related to those projects and it would be amazing to hear from them to see what might be the problem.

**Comment by zefexdeveloper** [comment] 2020-08-28 21:19
Thank you @bitfrost for the PR, I hope that @Timer or @timneutkens can merge.

**Comment by octogonz** [comment] 2020-09-23 17:57
I see that PR https://github.com/vercel/next.js/pull/16614 was closed recently.

Is PR https://github.com/vercel/next.js/pull/16369 expected to fix this issue?

**Comment by elliottsj** [comment] 2020-11-30 22:30
Since https://github.com/vercel/next.js/pull/17279 was merged, Next.js works with pnpm.

I proposed some integration tests to help ensure pnpm continues to work in the future: https://github.com/vercel/next.js/pull/17882

However, there are some outstanding issues using Next.js on Vercel with pnpm, like due to how Vercel's file system works:
* https://github.com/vercel/vercel/discussions/3896#discussioncomment-131265
* https://github.com/elliottsj/nextjs-vercel-pnpm-issue

**Comment by Timer** [comment] 2021-01-04 21:03
Closing as fixed by #17279

**Closed by Timer** 2021-01-04 21:03 UTC
Labels: good first issue, kind: bug

**Comment by vasiliicuhar** [comment] 2021-01-10 13:46
@Timer I think that has been partially fixed. It still does not work when deploying to Vercel.
At first I thought it was because of Rushjs, but it does not work with Pnpm without Rush as well

```

Error: ENOENT: no such file or directory, lstat '/vercel/workpath0/app/url'
--
15:28:10.448 | at realpathSync (fs.js:1643:7)
15:28:10.448 | at handleExternals (/vercel/workpath0/app/node_modules/.pnpm/next@10.0.5_react-dom@17.0.1+react@17.0.1/node_modules/next/dist/build/webpack-config.js:66:21)

```

I spent a lot of time yesterday trying to reproduce it locally but I have no idea what is different between my environment and Vercel build pipeline.

What I tried so far:
- adding url and querystring dependencies using readPackage hook
- changing rush / Pnpm default settings
- in case it's a difference between Mac and Linux, I tried to install packages and build it in a docker container  image `node:12`

Workaround:
Install url and querystring packages as direct dependencies of the project seems to help, but I'd really like to understand why Vercel environment is so specific, since everywhere else #17279 seems to work

Versions:
next@10.0.5, react-dom@17.0.1, react@17.0.1

package.json
```
{
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "~10.0.5",
    "react": "~17.0.1",
    "react-dom": "~17.0.1",
    "postcss": "~8.2.4",
    "tailwindcss": "~2.0.2",
    "autoprefixer": "~10.2.1"
  }
}

```

**Comment by elliottsj** [comment] 2021-01-10 17:41
@vasiliicuhar try this: https://github.com/vercel/next.js/pull/20949

**Comment by danvoyce** [comment] 2021-05-14 12:28
This is still  very broken... Here's a minimal reproducible repo https://github.com/looopdotdev/looop-2.1

I override the install command in Vercel like so `npm i pnpm -g && pnpm i`

All works fine with my app, until I add `getServerSideProps() {...` in one of the page components. As soon as I add that I get a big `500 - internal server error` on the deployed page.

Please help. I'm about to go live with my site and need to simply add some meta data. I really don't want to have to move away from pnpm or Vercel. 

Thanks 🙏

**Comment by PabloSzx** [comment] 2021-05-14 13:49
> This is still very broken... Here's a minimal reproducible repo https://github.com/looopdotdev/looop-2.1
> 
> I override the install command in Vercel like so `npm i pnpm -g && pnpm i`. (I've also simply tried `pnpm i`, but the build errors)
> 
> All works fine with my app, until I add `getServerSideProps() {...` in one of the page components. As soon as I add that I get a big `500 - internal server error` on the deployed page.
> 
> https://looop-2-1.vercel.app/
> 
> Please help. I'm about to go live with my site and need to simply add some meta data. I really don't want to have to move away from pnpm or Vercel.
> 
> Thanks 🙏

It seems like adding "--shamefully-hoist" in the install command fixes it

**Comment by danvoyce** [comment] 2021-05-14 15:21
> It seems like adding "--shamefully-hoist" in the install command fixes it

Dude, thanks so much. Literally save my bacon!!!

**Comment by elliottsj** [comment] 2021-05-14 16:04
These are my Vercel command overrides which seem to work (for https://github.com/elliottsj/elliott.dev): 

<img width="600" src="https://user-images.githubusercontent.com/2177366/118297403-13883400-b4ac-11eb-9f8a-eb96f406044b.png">

@danvoyce I'm curious about the underlying error for your 500 page. Anything in your app's logs?

**Comment by PabloSzx** [comment] 2021-05-14 17:24
> @danvoyce I'm curious about the underlying error for your 500 page. Anything in your app's logs?

I could reproduce this issue and I got the most useless error possible
![image](https://user-images.githubusercontent.com/8672915/118306595-a4184180-b4b7-11eb-8a98-b0487ca3f172.png)

**Comment by elliottsj** [comment] 2021-05-17 17:14
@PabloSzx I suppose it's a tradeoff. Unfortunately `--shamefully-hoist` provides fewer correctness guarantees than pnpm's default strict behaviour.

For example, let's say your project declares a dependency on `foo@1`, and `foo@1` has a dependency on `bar@2`.

With `--shamefully-hoist`, your project can `require('bar')` without error since it's hoisted to `node_modules/bar/`.

But if `foo@1.1` is released (a minor bump) with a new dependency on `bar@3` (a major bump), then your project's `require('bar')` can break the app in unexpected ways.

If forced to choose between `--shamefully-hoist` and slower builds due to being unable to use cached `node_modules`, I would probably choose the latter.

Of course, ideally Vercel should cache `node_modules` correctly with pnpm without having to resort to `--shamefully-hoist`.

**Comment by SirensOfTitan** [comment] 2021-05-18 14:57
Just to add to data here: We're running Next on a non-Vercel host, and our app also doesn't work without use of the `--shamefully-hoist`.  

This issue should probably be reopened, or alternatively another issue cut.  It feels like a fairly high-quality bug with easy reproduction and a couple canned projects that show the issue.

**Comment by dotsinspace** [comment] 2021-08-06 09:28
> > This is still very broken... Here's a minimal reproducible repo https://github.com/looopdotdev/looop-2.1
> > I override the install command in Vercel like so `npm i pnpm -g && pnpm i`. (I've also simply tried `pnpm i`, but the build errors)
> > All works fine with my app, until I add `getServerSideProps() {...` in one of the page components. As soon as I add that I get a big `500 - internal server error` on the deployed page.
> > https://looop-2-1.vercel.app/
> > Please help. I'm about to go live with my site and need to simply add some meta data. I really don't want to have to move away from pnpm or Vercel.
> > Thanks pray
> 
> It seems like adding "--shamefully-hoist" in the install command fixes it

vercel CI goes into infinte loop. even this is not working

**Comment by bitfrost** [comment] 2021-08-06 12:26
Hmm,  we have been using pnpm with no issues for a long time with no issues in many projects with next.js since the above issue was fixed (no use of --shamefully-hoist latest versions of pnpm)  next. 10.1.3 (I will update / try the above repo later today).

**Comment by elliottsj** [comment] 2021-08-06 15:08
For what it's worth, I opened a PR a while ago to fix a specific issue which surfaces when using pnpm: https://github.com/vercel/next.js/pull/21048

May or may not be related to the issues people are experiencing here, but the PR includes updates to the integration tests which should help catch many potential problems. If a maintainer has time to comment on it, it would be appreciated.

**Comment by PabloSzx** [comment] 2021-11-05 16:56
The --shamefully-hoist workaround seems to be broken for Next.js 12 in Serverless Functions in Vercel, RIP 

Can this start having a bigger priority? @Timer @styfle

**Comment by balazsorban44** [comment] 2022-01-27 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
