### ISSUE TITLE
False positive for rule `next/no-page-custom-font`

### ISSUE THREAD

**Issue by josebreijo** [vercel/next.js#28360] opened 2021-08-20 22:08 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.17.5

### What browser are you using?

Brave

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

Using an alias for `next/document` default export other than `Document` causes `eslint` to complain about it.

https://user-images.githubusercontent.com/30603119/130297790-181a5b77-be52-4b4f-8a1b-1a101f91a1d9.mov

### Expected Behavior

The linter rule shouldn't be tied to the default export being used as `Document`.

### To Reproduce

Create a [custom document](https://nextjs.org/docs/advanced-features/custom-document) and rename the default export to other than `Document`.

**Comment by housseindjirdeh** [comment] 2021-08-23 14:22
This should be fixed in v11.1.0. Try upgrading to that version or latest :)

**Closed by housseindjirdeh** 2021-08-23 14:22 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 22:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
