### ISSUE TITLE
context value is undefined on server with Webpack 5

### ISSUE THREAD

**Issue by Velenir** [vercel/next.js#18090] opened 2020-10-21 14:24 UTC
# Bug report

## Describe the bug

In development (`yarn dev`) if I restart the server while the page (http://localhost:3000/) remains open, I get undefined context value on server(but correct value on client).
If I close the page, restart the server, open the page, everything is good.

Doesn't happen with Webpack 4.

## To Reproduce

[Reproduction repo](https://github.com/Velenir/nextjs_webpack5_context_issue)

1. `yarn dev`
2. open `http://localhost:3000/`
3. stop server
4. start again with `yarn dev`
5. see browser console for `Warning: Text content did not match` and `store: undefined` in server console

## Expected behavior

Context value initialized on server, same as on client, always.

## Screenshots

![nextjs_provider_webpack5](https://user-images.githubusercontent.com/5121491/96733416-17dee980-13c2-11eb-97ee-d7d51dce6930.png)

## System information

- OS: Ubuntu 20.04
- Browser Chrome
- Version of Next.js: 9.5.5
- Version of Node.js: v12.18.0

## Additional context

[This](https://github.com/vercel/next.js/issues/13341#issuecomment-667306304) seems to be the same issue.

**Comment by jonawww** [comment] 2020-10-21 19:44
I'm currently facing a similar issue after upgrading to webpack 5. In the first render in development everything seems to be fine, but unfortunately after switching to another route the react tree gets messed up and I get an error with stating an missing React.Provider.

`Error: Component must be wrapped with <Container.Provider>`

In the production build the same error gets emitted, but everything just works fine.

**Comment by stefanprobst** [comment] 2020-10-30 11:03
I'm also seeing this issue with webpack5.

Added another reproduction [here](https://github.com/stefanprobst/next-webpack5-issue)

Some observations:
- with the above repro, i am only seeing the issue in `dev` mode
- initially the context value is actually populated correctly, but after some other page compilation happens, the context value is suddenly `undefined`. at least that's how i'm interpreting these logs:

![webpack5](https://user-images.githubusercontent.com/20753323/97697724-b399e500-1aa7-11eb-8ba9-3cfb6e7c1158.png)

**Comment by timneutkens** [comment] 2021-01-06 13:11
This was fixed in https://github.com/vercel/next.js/pull/20652

**Closed by timneutkens** 2021-01-06 13:11 UTC
Labels: kind: bug

**Comment by balazsorban44** [comment] 2022-01-28 21:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
