### ISSUE TITLE
Removing `redirects()` from next.config.js does not work

### ISSUE THREAD

**Issue by Dylan-Kerler** [vercel/next.js#17069] opened 2020-09-13 21:22 UTC
# Bug report

## Describe the bug

After removing the `redirects` function from next.config.js, the redirects are still persisting. This should not happen since the redirects have been entirely removed.

## To Reproduce

1. Add an initial redirect function in next.config.js:

```javascript
module.exports = {
    async redirects() {
      return [
        {
          source: '/foo',
          destination: '/bar',
          permanent: true,
        },
      ]
    },
  }
```

2. Restart the server with `yarn dev` and see that /foo redirects to /bar.

3. Remove the redirects function

```javascript
module.exports = {
   
  }
```

4. Restart the server with `yarn dev` and see that /foo still redirects to /bar despite the fact that this has been removed.

## Expected behavior

The redirect should no longer work after the redirect function has been removed. 

## System information

- OS: Ubuntu
- Browser: Chrome
- Version of Next.js: v9.5.3
- Version of Node.js: v12.18.3

**Comment by ijjk** [comment] 2020-09-13 21:31
Hi, when setting `permanent: true` on a redirect it uses the `308` status code which instructs the browser to cache the redirect. To skip this cache you should be able to do a [hard refresh](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache#Bypassing_cache) in your browser. To prevent the redirect from being cached you should use the `permanent: false` option.

**Comment by Dylan-Kerler** [comment] 2020-09-13 22:43
After trying ALL of the hard refresh methods in the link it still persists the redirect. I also did a manual hard refresh (by selecting from the dropdown menu "hard refresh", manually cleared the cache and quit/restart chrome; The redirect still persists.

**Comment by jensmeindertsma** [comment] 2020-09-14 08:11
I had to reset my browser cache and restart my PC for this to fix itself. Can you try this?

**Comment by Dylan-Kerler** [comment] 2020-09-14 10:53
No, issue is still there. After running `yarn dev -p 8080` then going to `localhost:8080` (instead of the default `localhost:3000`) the redirect is still there too. Perhaps that would suggest that this is not a problem in the browser?

**Comment by jensmeindertsma** [comment] 2020-09-14 11:36
Have you tried deleting the .next folder?

**Comment by Dylan-Kerler** [comment] 2020-09-14 11:55
I tried this and it didn't work. However I have managed to fix my problem. My original problem was that I had a redirect from '/app' to '/app/dashboard'.

It seems the issue was here:

`const isAppPage = router.asPath.startsWith("/app");`

After removing this line, the redirect no longer persists.

**Comment by Dylan-Kerler** [comment] 2020-09-14 11:58
Ah. Clearing the cache and restarting **DID** work. The actual issue was in my React code. Sorry.

**Comment by Timer** [comment] 2020-09-14 13:42
Closing as user said bug was in their React code.

**Closed by Timer** 2020-09-14 13:42 UTC

**Comment by jonasdehovre** [comment] 2021-12-28 17:09
What did the trick for me was opening the **developer tools** and in the **network** tab check the `disable cache` option 🙌

**Comment by balazsorban44** [comment] 2022-01-27 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
