### ISSUE TITLE
`next dev` and `next build` broken on Yarn PnP in the latest release

### ISSUE THREAD

**Issue by brc-dd** [vercel/next.js#32115] opened 2021-12-04 07:33 UTC
### What version of Next.js are you using?

`v12.0.5`

### What version of Node.js are you using?

`v16.13.1`

### What browser are you using?

N/A

### What operating system are you using?

Windows 11 (Build 22509.1000)

### How are you deploying your application?

`yarn next build && yarn next start`

### Describe the Bug

Getting the following errors on running `yarn next build`:

```txt
$ yarn next build
info  - Checking validity of types
warn  - No ESLint configuration detected. Run next lint to begin setup
info  - Creating an optimized production build
Failed to compile.

./.yarn/__virtual__/next-virtual-fedb67b0ce/0/cache/next-npm-12.0.5-1c991f073c-616235e394.zip/node_modules/next/dist/client/index.js
Error: Failed to read source code from C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\client\index.js

Caused by:
    The system cannot find the path specified. (os error 3)

Import trace for requested module:
./.yarn/__virtual__/next-virtual-fedb67b0ce/0/cache/next-npm-12.0.5-1c991f073c-616235e394.zip/node_modules/next/dist/client/next.js

./.yarn/__virtual__/next-virtual-fedb67b0ce/0/cache/next-npm-12.0.5-1c991f073c-616235e394.zip/node_modules/next/dist/client/request-idle-callback.js
Error: Failed to read source code from C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\client\request-idle-callback.js

Caused by:
    The system cannot find the path specified. (os error 3)

Import trace for requested module:
./.yarn/__virtual__/next-virtual-fedb67b0ce/0/cache/next-npm-12.0.5-1c991f073c-616235e394.zip/node_modules/next/dist/client/route-loader.js
./.yarn/__virtual__/next-virtual-fedb67b0ce/0/cache/next-npm-12.0.5-1c991f073c-616235e394.zip/node_modules/next/dist/shared/lib/router/router.js
./.yarn/__virtual__/next-virtual-fedb67b0ce/0/cache/next-npm-12.0.5-1c991f073c-616235e394.zip/node_modules/next/dist/client/router.js

./.yarn/__virtual__/next-virtual-fedb67b0ce/0/cache/next-npm-12.0.5-1c991f073c-616235e394.zip/node_modules/next/dist/pages/_app.js
Error: Failed to read source code from C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\pages\_app.js

Caused by:
    The system cannot find the path specified. (os error 3)

./.yarn/__virtual__/next-virtual-fedb67b0ce/0/cache/next-npm-12.0.5-1c991f073c-616235e394.zip/node_modules/next/dist/shared/lib/head.js
Error: Failed to read source code from C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\shared\lib\head.js

Caused by:
    The system cannot find the path specified. (os error 3)

Import trace for requested module:
./.yarn/__virtual__/next-virtual-fedb67b0ce/0/cache/next-npm-12.0.5-1c991f073c-616235e394.zip/node_modules/next/dist/pages/_error.js

./.yarn/__virtual__/next-virtual-fedb67b0ce/0/cache/next-npm-12.0.5-1c991f073c-616235e394.zip/node_modules/next/dist/shared/lib/mitt.js
Error: Failed to read source code from C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\shared\lib\mitt.js

Caused by:
    The system cannot find the path specified. (os error 3)

Import trace for requested module:
./.yarn/__virtual__/next-virtual-fedb67b0ce/0/cache/next-npm-12.0.5-1c991f073c-616235e394.zip/node_modules/next/dist/shared/lib/router/router.js
./.yarn/__virtual__/next-virtual-fedb67b0ce/0/cache/next-npm-12.0.5-1c991f073c-616235e394.zip/node_modules/next/dist/client/router.js


> Build failed because of webpack errors
```

The issue seems to be SWC related. After creating `.babelrc` with `next/babel` preset, the `yarn next build` command is working but `yarn next dev` is still throwing error.

Also, why the `Checking validity of types` log is shown even if someone is not using TS?

### Expected Behavior

To build successfully and start as happens in `next@12.0.4`.

### To Reproduce

```sh
mkdir foo && cd "$_"
yarn init -2
yarn add next react react-dom
mkdir pages
echo 'export default () => <div>Hello World</div>' > pages/index.js
yarn next build
```

Based on https://github.com/yarnpkg/berry/blob/master/.github/workflows/e2e-next-workflow.yml

**Comment by timneutkens** [comment] 2021-12-04 10:35
Can you try setting:
```js
module.exports = {
  experimental: {
    swcFileReading: false
  }
}
```

**Comment by brc-dd** [comment] 2021-12-04 10:42
@timneutkens `next build` is working after setting that, but `next dev` is still throwing errors:

```txt
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

error - ./.yarn/__virtual__/react-dom-virtual-7a7367685f/0/cache/react-dom-npm-17.0.2-f551215af1-1c1eaa3bca.zip/node_modules/react-dom/cjs/react-dom.development.js
Module build failed: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received type number (-2147483514)
    at new Promise (<anonymous>)
wait  - compiling...
error - ./.yarn/__virtual__/react-dom-virtual-7a7367685f/0/cache/react-dom-npm-17.0.2-f551215af1-1c1eaa3bca.zip/node_modules/react-dom/cjs/react-dom.development.js
Module build failed: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received type number (-2147483418)
    at new Promise (<anonymous>)
wait  - compiling...
error - ./.yarn/__virtual__/react-dom-virtual-7a7367685f/0/cache/react-dom-npm-17.0.2-f551215af1-1c1eaa3bca.zip/node_modules/react-dom/cjs/react-dom.development.js
Module build failed: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received type number (-2147483418)
    at new Promise (<anonymous>)
(node:13216) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
wait  - compiling /_error (client and server)...
error - ./.yarn/__virtual__/react-dom-virtual-7a7367685f/0/cache/react-dom-npm-17.0.2-f551215af1-1c1eaa3bca.zip/node_modules/react-dom/cjs/react-dom.development.js
Module build failed: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received type number (-2147483418)
    at new Promise (<anonymous>)
error - Error: Qualified path resolution failed - none of those files can be found on the disk.

Source path: C:\Users\brc-dd\Desktop\foo\.next\fallback-build-manifest.json
Not found: C:\Users\brc-dd\Desktop\foo\.next\fallback-build-manifest.json
Not found: C:\Users\brc-dd\Desktop\foo\.next\fallback-build-manifest.json.js
Not found: C:\Users\brc-dd\Desktop\foo\.next\fallback-build-manifest.json.json
Not found: C:\Users\brc-dd\Desktop\foo\.next\fallback-build-manifest.json.node

Require stack:
- C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\server\load-components.js
- C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\build\utils.js
- C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\build\output\store.js
- C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\build\output\index.js
- C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\cli\next-dev.js
- C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\bin\next
Error: Qualified path resolution failed - none of those files can be found on the disk.

Source path: C:\Users\brc-dd\Desktop\foo\.next\fallback-build-manifest.json
Not found: C:\Users\brc-dd\Desktop\foo\.next\fallback-build-manifest.json
Not found: C:\Users\brc-dd\Desktop\foo\.next\fallback-build-manifest.json.js
Not found: C:\Users\brc-dd\Desktop\foo\.next\fallback-build-manifest.json.json
Not found: C:\Users\brc-dd\Desktop\foo\.next\fallback-build-manifest.json.node

Require stack:
- C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\server\load-components.js
- C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\build\utils.js
- C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\build\output\store.js
- C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\build\output\index.js
- C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\cli\next-dev.js
- C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\bin\next
    at Function.external_module_.Module._resolveFilename (C:\Users\brc-dd\Desktop\foo\.pnp.cjs:13363:55)
    at Function.mod._resolveFilename (C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\build\webpack\require-hook.js:171:28)
    at Function.external_module_.Module._load (C:\Users\brc-dd\Desktop\foo\.pnp.cjs:13162:48)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.loadDefaultErrorComponents (C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\server\load-components.js:22:24)
    at DevServer.getFallbackErrorComponents (C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\server\dev\next-dev-server.js:679:43)
    at async DevServer.renderErrorToResponse (C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\server\next-server.js:1738:40)
    at async pipe.req.req (C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\server\next-server.js:1678:30)
    at async DevServer.pipe (C:\Users\brc-dd\Desktop\foo\.yarn\__virtual__\next-virtual-fedb67b0ce\0\cache\next-npm-12.0.5-1c991f073c-616235e394.zip\node_modules\next\dist\server\next-server.js:1156:25)
```

**Comment by dlindenkreuz** [comment] 2021-12-09 12:29
This prevents me from using Next.js >= v12.0.5.

**Comment by dyong1** [comment] 2021-12-12 13:13
same here 😭

**Comment by amuttsch** [comment] 2021-12-13 12:36
The issue is still happening with `v12.0.8-canary.4`. Setting `swcFileReading: false` fixes the `Error: Failed to read source code` error, but it triggers the following error instead:

```
info  - Creating an optimized production build  
Failed to compile.

./.yarn/__virtual__/react-query-virtual-b938dbb86e/0/cache/react-query-npm-3.34.2-955c5a58c3-c2cb423cae.zip/node_modules/react-query/es/core/types.js
Module build failed: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received type number (-2147483201)
    at Object.readFile (node:fs:393:10)
    at .../.pnp.cjs:32872:19
    at new Promise (<anonymous>)
    at NodeFS.readFilePromise (.../.pnp.cjs:32870:18)
    at makeCallPromise.async.subPath.subPath (.../.pnp.cjs:35838:36)
    at ZipOpenFS.makeCallPromise (.../.pnp.cjs:35960:45)
    at ZipOpenFS.readFilePromise (.../.pnp.cjs:35831:17)
    at VirtualFS.readFilePromise (.../.pnp.cjs:33182:26)
    at PosixFS.readFilePromise (.../.pnp.cjs:33182:26)
    at URLFS.readFilePromise (.../.pnp.cjs:33182:26)
```

Not quite sure why react query is unhappy, but I guess it sth. with the bundle process seems wrong.

I also have the `esmExternals: false` option set is this is somehow related.

**Comment by brc-dd** [comment] 2021-12-13 12:53
_For now_, if anyone is facing the issue with `next dev`, try unplugging `react-dom` (`yarn unplug react-dom`), it will work (although in a way this defeats the purpose of plug-n-play).

**Comment by amuttsch** [comment] 2021-12-13 13:08
@brc-dd Thanks for the hint, unplugging react query "fixes" my error above. But I agree, unplugging should not be the solution for this issue. I'm staying on 12.0.5 for now until we have a proper fix :-)

**Comment by reckter** [comment] 2021-12-22 11:18
I needed to unplug `next` itself for it to work with the newest version (`12.0.7`).

**Comment by kyro-dev** [comment] 2021-12-22 16:43
Version 12.0.4 is the highest version I could go without this error.

**Comment by kaykdm** [comment] 2021-12-28 07:18
@timneutkens @sokra 
>next build is working after setting that, but next dev is still throwing errors:

I just opened PR to fix this 
https://github.com/vercel/next.js/pull/32867

**Comment by Markos-Th09** [comment] 2022-01-06 11:06
When do you expect it do be fixed?

**Comment by taavisalo** [comment] 2022-01-12 08:27
Still broken with latest 12.0.8. yarn dev throws "Failed to read source code" errors.

**Comment by kaykdm** [comment] 2022-01-12 10:48
> Still broken with latest 12.0.8. yarn dev throws "Failed to read source code" errors.

@taavisalo 
see here: https://github.com/vercel/next.js/pull/32867#issuecomment-1010860894

**Comment by taavisalo** [comment] 2022-01-12 11:01
> > Still broken with latest 12.0.8. yarn dev throws "Failed to read source code" errors.
> 
> @taavisalo see here: [#32867 (comment)](https://github.com/vercel/next.js/pull/32867#issuecomment-1010860894)

Thank you! Running yarn cache clear fixed the problem.

**Comment by amuttsch** [comment] 2022-01-12 11:46
@taavisalo Have you added `swcFileReading: false,` to `experimental`? Setting it in the root object doesn't work, but in `experimental` I was able to fix this issue.

**Comment by taavisalo** [comment] 2022-01-12 11:50
> @taavisalo Have you added `swcFileReading: false,` to `experimental`? Setting it in the root object doesn't work, but in `experimental` I was able to fix this issue.

This worked. Probably going to have to stick with 12.0.4 still, because current solution requires enabling experimental features.

**Comment by brc-dd** [comment] 2022-01-12 11:52
Can confirm that #32867 fixed the issue with `yarn dev`. But I'm keeping the issue open for now as the https://github.com/vercel/next.js/issues/32115#issuecomment-986005957 workaround is still required.

**Comment by rtritto** [comment] 2022-01-12 13:21
This issue is similar to #31552 (fixed with #32867) and should be closed.
Last issue is #31812 (temporary fixed with workaround of `swcFileReading: false` in experimental).

**Closed** 2022-01-12 16:21 UTC
Labels: kind: bug, area: Yarn PnP / pnpm

**Comment by dgattey** [comment] 2022-01-18 07:52
Hmm, with `12.0.8` this is still broken for me, when running `next dev` or `next build`. If I set `swcFileReading` to `false` in my next.config.js, it works. Should setting that experimental flag still be necessary to get Yarn PnP to work on 12.0.8?

**Comment by balazsorban44** [comment] 2022-01-18 15:31
@dgattey that option has been recently changed to accommodate your use case in #33236 we will include it in the next upcoming `canary` release (which is :soon::tm:), thanks for the feedback! :+1:

**Comment by zigang93** [comment] 2022-01-21 09:20
my `yarn build` seem like stuck at `info  - Checking validity of types`. anyone encounter same issue like me?
