### ISSUE TITLE
Use tailwindcss with AMP in a Next.js project more easily

### ISSUE THREAD

**Issue by thanhtoan1196** [vercel/next.js#19701] opened 2020-12-01 07:57 UTC
## Describe the solution you'd like

Use tailwindcss with AMP in a Next.js project more easily

**Comment by ijjk** [comment] 2020-12-01 20:11
Hi, this appears to be a duplicate of https://github.com/vercel/next.js/issues/7121 so I'm going to close this one in favor of the existing one.

**Closed by ijjk** 2020-12-01 20:11 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-29 02:12
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
