### ISSUE TITLE
Route.ts redirect error: TypeError: ComponentMod.renderToReadableStream is not a function

### ISSUE THREAD

**Issue by tonywei92** [vercel/next.js#52427] opened 2023-07-08 04:01 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: arm64
      Version: #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.2
    Relevant Packages:
      next: 13.4.9
      eslint-config-next: 13.4.9
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

-

### To Reproduce

mywebsite/app/hello/route.ts
```
import { NextResponse } from "next/server";

export async function GET(request: Request) {
  const response = NextResponse.redirect("https://google.com", { status: 302 });
  return response;
}
```

### Describe the Bug

Redirect hang, nothing happens

console showing this error:
```
error TypeError: ComponentMod.renderToReadableStream is not a function
    at AsyncLocalStorage.run (node:async_hooks:338:14)
```

### Expected Behavior

Visiting `/hello` should redirect to `https://google.com`

**Comment by farhanghazi97** [comment] 2023-07-10 01:19
Same issue on my end.

**Comment by farhanghazi97** [comment] 2023-07-10 01:32
You must nest your 'route.ts' file within 'api' folder. Hope this helps.

**Comment by wy1009** [comment] 2023-07-12 09:14
Exactly same problem.

**Comment by wy1009** [comment] 2023-07-12 09:14
> You must nest your 'route.ts' file within 'api' folder. Hope this helps. In your case refactor to the following:
> 
> mywebsite/app/hello/api/route.ts

Not working for me🥲

**Comment by farhanghazi97** [comment] 2023-07-12 09:22
Apologies, the api folder must be at the same level as 'src'.

So, something like:

```src/api/dashboard/route.ts```

**Comment by wy1009** [comment] 2023-07-12 09:31
> Apologies, the api folder must be at the same level as 'src'.
> 
> So, something like:
> 
> `src/api/dashboard/route.ts`

Thank you for your reply! Still not working for me. 🥲 I'm using Next's app router. I don't think your solution is valid because the route hierarchy you mentioned is different from the one in the documentation.
![image](https://github.com/vercel/next.js/assets/18343973/cf2d602c-ae77-45fe-90f7-4582fc17f375)

**Comment by wy1009** [comment] 2023-07-12 09:48
> Apologies, the api folder must be at the same level as 'src'.
> 
> So, something like:
> 
> `src/api/dashboard/route.ts`

I've decided to switch to the pages router. Thanks again for your help!

**Comment by nicksan222** [comment] 2023-07-12 15:09
To me the provided example works fine and redirects to google

**Comment by jrea** [comment] 2023-07-12 15:10
While not necessarily trying to do the same thing as OP, simply having a `route.ts` file inside of a folder with a `page.tsx` breaks the rendering of the page:

```bash
app
  /login
    page.tsx
    route.ts
```

Rendering `http://localhost:3000/login` will throw `TypeError: ComponentMod.renderToReadableStream is not a function`.

As it stands now, you have to do something like this (more in line with what the pages router requires)

```bash
app
  /api/login
    route.ts
  /login
    page.tsx
```

where the client code on in `/login/page.tsx` needs to prefix with `/api/login` vs posting to itself. 

I'd imagine the "real" solution in my case is using [server actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions)

**Comment by juanpicado** [comment] 2023-07-12 17:37
> While not necessarily trying to do the same thing as OP, simply having a `route.ts` file inside of a folder with a `page.tsx` breaks the rendering of the page:
> 
> ```shell
> app
>   /login
>     page.tsx
>     route.ts
> ```
> 
> Rendering `http://localhost:3000/login` will throw `TypeError: ComponentMod.renderToReadableStream is not a function`.
> 
> As it stands now, you have to do something like this (more in line with what the pages router requires)
> 
> ```shell
> app
>   /api/login
>     route.ts
>   /login
>     page.tsx
> ```
> 
> where the client code on in `/login/page.tsx` needs to prefix with `/api/login` vs posting to itself.
> 
> I'd imagine the "real" solution in my case is using [server actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions)

Same issue `TypeError: ComponentMod.renderToReadableStream is not a function` while having `{root}/app/api/route.ts` as doc suggest, the request is ignored, console log is never executed, if I move `route.ts` to the folder I get the `TypeError` error.

```
import { NextResponse } from 'next/server';

// route.ts content
export async function GET() {
	console.log('--->**************************************');
	const response = NextResponse.redirect('https://google.com', { status: 302 });
	return response;
}
```

**Comment by xczdenis** [comment] 2023-07-13 09:01
I think it works like this:
1. If you have the following structure:
```
app/
  login/
    route.ts
    page.tsx
```
It doesn't work because ([doc](https://nextjs.org/docs/app/building-your-application/routing/router-handlers#convention)):

```
Route Handlers can be nested inside the app directory, similar to page.js and layout.js. 
But there cannot be a route.js file at the same route segment level as page.js.
```
2. If you have the following structure:
```
app/
  login/
    api/
      route.ts
    page.tsx
```
The address `http://localhost:3000/login` will render app/login/page.tsx. The `route.ts` file will be ignored. The address `http://localhost:3000/login/api` will call the `route.ts` file and you will get your redirect.
3. If you have the following structure:
```
app/
  login/
    route.ts
```
The address `http://localhost:3000/login` will call the `route.ts` file and you will get your redirect.

**Comment by balazsorban44** [comment] 2023-08-07 11:20
@farhanghazi97 

> You must nest your 'route.ts' file within 'api' folder. Hope this helps.

This is incorrect, App Router does not force "api" to be part of the folder structure.

I could not reproduce this issue, so closing. If you are still experiencing it, please first make sure that you have tried `next@canary`, and then open a new issue with an attached reproduction that we can look at. Thanks!

**Closed by balazsorban44** 2023-08-07 11:20 UTC
Labels: template: bug
