### ISSUE TITLE
Methods of router will be updated after each top to down rerendering

### ISSUE THREAD

**Issue by yangmingshan** [vercel/next.js#27689] opened 2021-08-02 14:47 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

16.6.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Nginx

## The problem

Let's say I have an order list page, it accept a optional parameter `page`. I want fetch the list in the `useEffect`, and jump to the error page if the request fails. The codes should be like this:

```js
// pages/orders.js
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { getOrderList } from "../api";

export default function Orders() {
  const { push } = useRouter();
  const [orders, setOrders] = useState([]);

  useEffect(() => {
    const page = new URLSearchParams(location.search).get("page") || "1";
    getOrderList(page).then(
      (response) => {
        setOrders(response);
      },
      () => {
        push("/error");
      }
    );
  }, [push]);

  // ...
}
```

The problem is when I visit `/orders?page=2`, the order list api will be requested twice, if the request did not fail.

## How this happened

The effect will run after the first rendering, and cause the first request, not surprising. But next.js [will call `router.replace()`](https://github.com/vercel/next.js/blob/807d1ec7ef/packages/next/client/index.tsx#L181) after the first rendering, it will cause a top to down rerendering. The [`router` will be updated](https://github.com/vercel/next.js/blob/807d1ec7ef/packages/next/client/index.tsx#L603) after each `AppContainer` rerendering, so are it's [properties and **methods**](https://github.com/vercel/next.js/blob/807d1ec7ef/packages/next/client/router.ts#L153). So `push` is a new function in the second rendering, and the effect will run **again**. This is how the second request happened.

### Expected Behavior

Methods of router should be stable between rerendering. Or even router itself should be a stable and mutable object, only it's properties should be immutable, like `react-router`.

### To Reproduce

See **Describe the Bug**.

Another request, could we publish unminified codes to npm? Debug next.js is a disaster even with sourcemap 😞.

**Comment by yangmingshan** [comment] 2021-08-02 16:02
Related issue: #27691.

**Comment by ijjk** [comment] 2021-08-10 17:27
Closing as a duplicate of https://github.com/vercel/next.js/issues/18127

**Closed by ijjk** 2021-08-10 17:27 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 00:12
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
