### ISSUE TITLE
swcMinify: true broke SVG path option

### ISSUE THREAD

**Issue by AstRonin** [vercel/next.js#42878] opened 2022-11-14 07:36 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Mar 2 00:30:59 UTC 2022
    Binaries:
      Node: 19.0.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.3
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

"lottie-web": "5.7.8",

### What browser are you using? (if relevant)

Chrome Version 107.0.5304.107 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

With `swcMinify: true` in SVG disappear first latter `M`. Please look to printscreen.

`Error: <path> attribute d: Expected moveto path command ('M' or 'm')`

![image](https://user-images.githubusercontent.com/2378239/201599282-41ae0ccf-1d57-40f6-a19e-0f0b5e7ae0b2.png)
![image](https://user-images.githubusercontent.com/2378239/201599375-2d655810-a40a-4650-9ef3-3f0c8332fa6a.png)

It works fine with `swcMinify: false`

### Expected Behavior

SVG should works fine like without swcMinify.

![image](https://user-images.githubusercontent.com/2378239/201598134-560d828e-9a6f-4d1d-8114-012f984bb8fc.png)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

complex

### To Reproduce

Using lottie.
```
export lottie_object from lottie_object.json
lottie.loadAnimation({
  animationData: lottie_object 
})
```

**Comment by xmahbub** [comment] 2022-11-14 12:07
Same problem!

**Comment by wadehammes** [comment] 2022-11-14 14:43
Same issue as #42801

**Comment by balazsorban44** [comment] 2022-11-15 17:59
Closing as duplicate of #42801. Please post a reproduction there. "complex" is not a reproduction. We cannot investigate that. :pray:

**Closed by balazsorban44** 2022-11-15 17:59 UTC
Labels: template: bug
