### ISSUE TITLE
"Failed to load env from …\.env TypeError: Cannot read properties of undefined (reading 'split')" and "Module not found: Can't resolve '@builder.io/partytown/integration' in …" errors

### ISSUE THREAD

**Issue by omareg94** [vercel/next.js#35645] opened 2022-03-28 04:28 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 16.14.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.2-canary.0
      react: 17.0.2
      react-dom: 17.0.2

### How are you deploying your application? (if relevant)

npx cross-env DEBUG=server:* node server.js

### Describe the Bug

When I run `npx cross-env DEBUG=server:* node server.js` using next latest stable release `12.1.1` or latest canary release `12.1.2-canary.0`, I get:
```
info  - Loaded env from C:\my-app\.env.local
error - Failed to load env from C:\my-app\.env TypeError: Cannot read properties of undefined (reading 'split')
    at C:\my-app\node_modules\@next\env\dist\index.js:1:311
    at Array.reduce (<anonymous>)
    at _interpolate (C:\my-app\node_modules\@next\env\dist\index.js:1:125)
    at expand (C:\my-app\node_modules\@next\env\dist\index.js:1:709)
    at processEnv (C:\my-app\node_modules\@next\env\dist\index.js:1:3638)
    at Module.loadEnvConfig (C:\my-app\node_modules\@next\env\dist\index.js:1:4443)
    at Object.loadConfig [as default] (C:\my-app\node_modules\next\dist\server\config.js:42:21)
    at NextServer.loadConfig (C:\my-app\node_modules\next\dist\server\next.js:114:48)
    at NextServer.getServer (C:\my-app\node_modules\next\dist\server\next.js:120:39)
    at NextServer.prepare (C:\my-app\node_modules\next\dist\server\next.js:96:35)
warn  - SWC minify release candidate enabled. https://nextjs.org/docs/messages/swc-minify-enabled
event - compiled client and server successfully in 14.4s (174 modules)
  server:main > Ready on http://localhost:3000 +0ms
GET / 307 - - 18.663 ms
wait  - compiling / (client and server)...
warn  - ./node_modules/next/dist/pages/_document.js
Module not found: Can't resolve '@builder.io/partytown/integration' in 'C:\my-app\node_modules\next\dist\pages'
```

However, on next previous stable release `12.1.0`, it works normally without any of these warnings.

### Expected Behavior

App to work normally without either of these warnings:
**error - Failed to load env from C:\my-app\.env TypeError: Cannot read properties of undefined (reading 'split')**
**warn  - ./node_modules/next/dist/pages/_document.js
Module not found: Can't resolve '@builder.io/partytown/integration' in 'C:\my-app\node_modules\next\dist\pages'**

### To Reproduce

Use .env file, and custom _document.js on stable release `12.1.1` or canary release `12.1.2-canary.0`.

**Comment by balazsorban44** [comment] 2022-03-28 13:39
Are you using the recently introduced Script with an experimental worker strategy?

Would you mind attaching a reproduction/your code? :pray:

**Comment by FernandVEYRIER** [comment] 2022-03-31 06:50
Ran into the same issue. Easily reproduced with an `.env` file containing `$#` in the values:
```MY_VAR="bug$#bug"```

**Comment by FernandVEYRIER** [comment] 2022-04-01 05:17
Hello @housseindjirdeh ! Thanks for the quick reply.
```
error - Failed to load env from /.env.local TypeError: Cannot read properties of undefined (reading 'split')
    at /node_modules/@next/env/dist/index.js:1:311
    at Array.reduce (<anonymous>)
    at _interpolate (/node_modules/@next/env/dist/index.js:1:125)
    at expand (/node_modules/@next/env/dist/index.js:1:709)
    at processEnv (/node_modules/@next/env/dist/index.js:1:3638)
    at Module.loadEnvConfig (/node_modules/@next/env/dist/index.js:1:4443)
    at Object.loadConfig [as default] (/node_modules/next/dist/server/config.js:42:21)
    at NextServer.loadConfig (/node_modules/next/dist/server/next.js:114:48)
    at NextServer.getServer (/node_modules/next/dist/server/next.js:120:39)
    at NextServer.prepare (/node_modules/next/dist/server/next.js:96:35)
```

Here is the whole dump of the only error on start

**Comment by marlon307** [comment] 2022-04-01 11:36
I'm also facing the same problem after updating my REACT version to 18

**Comment by sdeagh** [comment] 2022-04-01 12:36
My steps to recreate:

1. yarn create next-app testsite
2. cd testsite
3. yarn build (worked fine)
4. create blank file .env.local
5. yarn build (worked fine)
6. add an environment variable, e.g., MY_TEST_ENV_VARIABLE="hello"
7. yarn build (worked fine)
8. edit environment variable to include a $ symbol e.g., MY_TEST_ENV_VARIABLE="hello$"
9. yarn build now results in: 

error - Failed to load env from /Users/******/Dev/testsite/.env.local TypeError: Cannot read properties of undefined (reading 'split')

**Comment by omareg94** [comment] 2022-04-01 13:17
#### **For `Failed to load env from …\.env TypeError: Cannot read properties of undefined (reading 'split')` error :**
I found that I should have escaped the dollar sign (e.g. `MY_VAR="AA\$^A"` or `MY_VAR="bug\$#bug"`) (Not a bug in Next release).
The error is triggered because of a value containing _unescaped dollar sign followed by special character_ (e.g. `$^` or `$#`) like in `MY_VAR="AA$^A"` and `MY_VAR="bug$#bug"` (@FernandVEYRIER's). These are invalid environment values because no environment variable name can contain `^` or `#` characters, so `$` need to be escaped (i.e. .env parser expects `$^A` and `$#bug` to be a call to existing variables if `$` not escaped).

**Comment by housseindjirdeh** [comment] 2022-04-01 18:28
Thanks for the details everyone. Looks like there are two separate issues here:

- `Failed to load env from …\.env TypeError: Cannot read properties of undefined (reading 'split')`: Like some of you have already noticed, you need to escape the `$` character (see note in [docs](https://nextjs.org/docs/basic-features/environment-variables#:~:text=If%20you%20are%20trying%20to%20use%20a%20variable%20with%20a%20%24%20in%20the%20actual%20value%2C%20it%20needs%20to%20be%20escaped%20like%20so%3A%20%5C%24.))
- `Module not found: Can't resolve '@builder.io/partytown/integration'`: This may be due to a setup issue, but I've just included a [patch](https://github.com/vercel/next.js/pull/35793) for webpack to not parse the `require` of the package server-side which should remove any likelihood of it erroring due to not being resolved. This should prevent this error from popping up when it shouldn't :)

**Comment by housseindjirdeh** [comment] 2022-04-01 18:28
Closing this for now! @omareg94 if you are still running into the issue, please update your next dep to v12.1.5-canary.0 as that should fix the problem.

**Closed by housseindjirdeh** 2022-04-01 18:28 UTC
Labels: please add a complete reproduction, template: bug, area: next/script
