### ISSUE TITLE
Docs: Missing "Testing" Page Under "Optimizing" for the "Using App Router" Section

### ISSUE THREAD

**Issue by craigmcc** [vercel/next.js#52347] opened 2023-07-06 19:52 UTC
### What is the improvement or update you wish to see?

The _Using Pages Router_ section, under _Optimizing_, has a nice page about how to set up tests:

[Testing](https://nextjs.org/docs/pages/building-your-application/optimizing/testing)

There is no corresponding page in the _Using Apps Router_ section

It would be really helpful to have such a page for people using the Apps Router documentation (even if it is a pointer back to the same content).

### Is there any context that might help us understand?

I am trying to use the apps router, with some server actions for accessing my database.  The actions themselves work fine in the app, but Jest throws an error when I try to execute a test for them.

```
Cannot find module 'private-next-rsc-action-proxy' from 'src/actions/LibraryActions.ts'
```

(LibraryActions.ts is a bunch of server actions talking to the library database, with "use server" at the top.)

I do not know if there is something weird in my Jest setup, or if that is an actual issue.

**Comment by balazsorban44** [comment] 2023-07-10 10:42
Duplicate of #50334

Related #47299, #47448

**Closed by balazsorban44** 2023-07-10 10:42 UTC
Labels: template: documentation
