### ISSUE TITLE
Parallel / Intercepting Routes rendering 404 on page load

### ISSUE THREAD

**Issue by tommyboylab** [vercel/next.js#48289] opened 2023-04-12 11:10 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.13.0
      npm: 9.4.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.4
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://vercelnextjsnzcvbl-dh2v--3000--b5037fed.local-credentialless.webcontainer.io/1

### To Reproduce

- Create a Intercepting / Parallel route layout within the app directory
- Add a modal with a dynamic page (ex: @modal/[id]) with a console log
- Add a parent page for the same path (ex: [id]) with a console log
- Attempt to navigate to the dynamic page and see the modal is rendered
- Refresh the page and see you have a 404 rendered, while the console log for parent page has been called

### Describe the Bug

Upon initial client-side navigation to an intercepted route, the page is properly navigated and modal is shown. Upon reloading the page the content is not rendered, get a 404 page but params are still passed.

![next-route](https://user-images.githubusercontent.com/44362297/231438087-49ababf5-7f4b-4023-b69a-82e6ec3b652d.gif)

### Expected Behavior

Navigation should first show modal on initial load from top level page. After reloading the parent page should be loaded, not have 404 but still receive props

The intention is to have a blog page with a list of articles with a set of ids (a,b,c..) which are conditionally rendered in a modal while on the blog page itself, are rendered standalone when visiting from a link / page is reloaded.

```
blog
├── @modal/[id]
│   └── page.tsx
├── @list
│   └── page.tsx
└── layout.tsx
├── [id]
     └── page.tsx

```

**Comment by Fredkiss3** [comment] 2023-04-13 01:06
the link to the reproduction code is broken.

**Comment by Nickman87** [comment] 2023-04-26 15:20
@Fredkiss3 I am having similar issues so I tried to build a reproduction codebase here: https://codesandbox.io/p/sandbox/nextjs-intercepting-routes-s9j6mo

If you click `open blog` you go to the blog page, and there you can open a `blog item`, but clicking that just redirects to the actual blog page, and not just the modal. (it also renders both the blog page AND the modal, which is strange).

Not sure if this is the exact problem he is describing, because I also have an issue with a 404 locally, but cannot reproduce right now in a codesandbox.

**Comment by Nickman87** [comment] 2023-04-28 07:32
@feedthejim I think there is still something wrong with the `(.)` selector:
If you check out this repo: https://codesandbox.io/p/sandbox/nextjs-intercepting-routes-s9j6mo
You will see that if you open the blog post, there are two things happening that are off:

1. It also loads the intercepted page als main page (it replaces the blog page with the item page)
2. If you have the blog post modal open and refresh the page, it will give you a 404

I modified this repo to use the old (..) syntax here: https://codesandbox.io/p/sandbox/nextjs-intercepting-routes-forked-bfuitc
If you try this version (only change is `(.)` became `(..)blog`), then everything works as expected.

**Comment by Nickman87** [comment] 2023-04-28 08:58
Maybe related to https://github.com/vercel/next.js/issues/48090 ?

**Comment by conmute** [comment] 2023-06-12 15:35
After some time, I did file move from `/app` folder outside and then inside everything worked well but with `(.)`, here is now working example of intercepted routes that I have 

https://github.com/conmute/fireship-nextjs/tree/main/app/src/app/%40modal

**Comment by jessepinho** [comment] 2023-07-11 20:58
OMG — I think I've figured this out!

I was running into the same problem: the intercepted route would load fine when clicking a `<Link />`; but when I refreshed the page on the intercepted route, it would 404.

**Here's the problem: if the layout slot isn't filled based on the current path, it will 404.** You can test this by removing the slot from the layout file, and then doing a full-page load on the intercepted route path. The full-page load should work just fine now. Then, when you add the slot back to the layout file, it'll 404 again.

**To fix this, you need to use a route group.** Remove the slot from your root layout, and create a new layout inside your route group that just renders `children` and your slot:

```TSX
// src/app/(home)/layout.tsx
import { ReactNode } from 'react'

export default function Layout({
  children,
  slotNameHere,
}: {
  children: ReactNode
  slotNameHere: ReactNode
}) {
  return (
    <>
      {children}
      {slotNameHere}
    </>
  )
}
```

Move your homepage and your intercepted routes underneath your route group:

```
- src
  - app
    - (home)
      - @slotNameHere
        - (.)routeName
          - page.tsx
          - ...etc
```

Note that, if your intercepted route is a few levels down (e.g., `src/app/(home)/@slotNameHere/(.)routeName/foo/bar/page.tsx`, you may need to create a `page.tsx` at the level right under the root of the intercepted route to prevent the same 404 issue (i.e., at `src/app/(home)/@slotNameHere/(.)routeName/page.tsx`). This can just be an empty component that returns `null`.

**Comment by kachkaev** [comment] 2023-07-25 17:57
I am facing a similar bug, the details are here: https://github.com/vercel/next.js/issues/53170

@jessepinho, I am unable to fix 404s with the group. Since you are saying that you have figured it out, can it be that my reproduction example is just misconfigured? If you can spot a missing bit that is causing 404s, that’ll be awesome!

**Comment by jessepinho** [comment] 2023-07-25 22:38
@kachkaev I don't have more time to look into it, but it looks like you're using three dots in the name of your `(...)photo` directory, which I believe is invalid.

**Comment by kachkaev** [comment] 2023-07-25 23:33
@jessepinho three dots [refer to _app root_](https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes#convention) so they are fine I guess. My example works the same way for `(.)photos`. Thanks for looking at it anyway!

**Comment by jscul** [comment] 2023-08-17 05:28
Intercepting and parallel routes seems completely broken to me... or the docs are completely wrong. Either way, this is a very frustrating issue. The group solution did not work for me.

**Comment by jmarbutt** [comment] 2023-09-08 14:42
I am having this issue also.

**Comment by jmarbutt** [comment] 2023-09-08 14:43
I agree with @jscul on this one, so much of this seems completely broken and half baked. The docs are not correct.

**Comment by snettah** [comment] 2023-10-05 08:00
For me I've just need to `rm -rf .next` dir then restart the app

**Comment by AkshatKaushik3005** [comment] 2023-10-07 06:26
has any fix been applied for this?

**Comment by SomervilleTom** [comment] 2023-10-10 00:47
> The "trick" to this is to use default.tsx to cover non-matching slots. Adapting the [example app](https://github.com/vercel-labs/nextgram) worked for my use case

I'm using js rather than tsx, and I have a `'default.js'` (as per the documentation) in the following paths:

* `'src/app/@modal/(..)photos'`
* `'src/app/default.js'`

My hierarchy (borrowed from the "nextgram" example) is:

```
src/
    app/
        @modal/
            (..)photos/
                [id]/
                    page.js
            default.js
        photos/
            [id]/
                page.js
        default.js
```

I develop in vscode on a remote (linux) system.  Here is the complaint I get in the embedded terminal of vscode
when I run "yarn dev":
```
Error: Invalid interception route: /(..)photos/[id]. Cannot use (..) marker at the root level, use (.) instead.
    at extractInterceptionRouteInformation (<...>/node_modules/next/dist/server/future/helpers/interception-routes.js:64:23)
    at generateInterceptionRoutesRewrites (<...>/node_modules/next/dist/lib/generate-interception-routes-rewrites.js:47:121)
    at Watchpack.<anonymous> (<...>/node_modules/next/dist/server/lib/router-utils/setup-dev.js:1346:164)
```

So far as I can tell, this is an issue from `next.js`.

According to `'<...>/node_modules/next/package.json'`, I'm running v13.5.4.

I run the most recent Javascript version of `nextgram`. That uses v13.3.1-canary.1 (according to its package.json), and works as documented.

It looks to me as though v13.5.4 does not align with the documentation or the `next.js` example.

**Comment by kshyr** [comment] 2023-10-10 07:09
@SomervilleTom take a look here https://github.com/vercel-labs/nextgram/tree/main/src/app/%40modal. They use `(.)photos`. From Next.js docs at https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes:

> Note that the (..) convention is based on route segments, not the file-system.

`@modal` does not affect route, so they should be on one segment.

Also seems like nextgram uses v13.4.7. I just had to downgrade because I kept getting `Could not find the module in the React Client Manifest. This is probably a bug in the React Server Components bundler.`

**Comment by SomervilleTom** [comment] 2023-10-10 19:16
I spent the last several hours refactoring my version of `nextgram` to add an extra segment to the "photos"/"@modal" portion.

I added 'console.log' statements to each `'page.js'`, to each `'default.js'`, and to each `'layout.js'` in hopes working out what elements are actually rendered.

The result is that, as far as I can tell, the intercepting route is simply ignored.

Here is my new structure:
```
src/
    app/
        hack/
            @modal/
                (..)photos/
                    [id]/
                        page.js
                default.js
            photos/
                [id]/
                    page.js
            default.js
        layout.js
        page.js
```
The top-level 'page.js' (`'src/app/page.js'`) contains a `Link` button whose href is '/hack/photos'. This opens the "nextgram' page as expected. Each item in that page is a link whose href is `'hack/photos/${id}'`.

When one of those is clicked, the plain (non-modal) `photos/[id]` page is rendered.

At no time is there any evidence that any `'@model'` descendent is ever rendered.

It appears to me that in the v13.5.4 release, parallel/intercepting routes are either broken or do nothing.

**Comment by SomervilleTom** [comment] 2023-10-10 22:23
I spent the rest of the afternoon trying to patch v13.4.7 (the version used in the most recent `nextgram` example) to use the "https" (rather than "http") protocol. The `next.js` code successfully resisted this attempt.

My next step is to punt the "AppRoute" approach altogether, at least for now, and revert to the less-favored "Pages" approach. I don't need to do any streaming, so perhaps this will be more fruitful.

At least for now, the APIRoute approach is a dead-end for me.

**Comment by SomervilleTom** [comment] 2023-10-11 14:04
I was finally able to get a copy of the `nextgram` example working on my system. It worked after I did the following (not all might be needed)

1. Add sections to `'package.json'`

    The following need to be added to "dependencies":
    
    ```
    "@headlessui/react": "^1.7.15",
    "clsx": "^1.2.1",
    ````

    A "devDependencies" apparently needs to be present:

    ```
    "devDependencies: {
        "@types/node": "20.3.1",
        "@types/react": "^18.2.14",
        "autoprefixer": "^10.4.14",
        "postcss": "^8.4.24",
        "sass": "^1.63.6",
        "tailwindcss": "^3.3.2",
        "typescript": "^5.1.3"
    },
    ```
2. Add top-level config files

    * `'tsconfig.json'`
    * `'postcss.config.js'`
    * `'next.config.js'`

        This includes the following "experimental" section:

        ```
        experimental: {
          appDir: true,
        },
        ```

        This is specific to 'v13.4.7' of 'next.js'
  
    * `'tailwind.config.js'`

3. Use explicit paths in `'app/@modal/(.)photos/[id]/page.js'`

    React encourages the use of a top-level 'jsconfig.json' file that provides more convenient expressions in import statements. It appears that the `'@whatever'` syntax breaks that facility.

    I therefore had to change `'app/@modal/(.)photos/[id]/page.js'` as follows:

    Failing:
    ```
    import Frame from '@/components/frame/Frame';
    import Modal from "@/components/modal/Modal";
    ```

    Successful:
    ```
    import Frame from '../../../../components/frame/Frame'
    import Modal from "../../../../components/modal/Modal";
    ```
Please note that I am using Javascript ('.js') rather than Typescript ('.ts').

Now that I have the `nextgram` example working with v13.4.7, I'll update to v14.5.4 and see if I can make it work.

If that succeeds, then I'll try adding back the MaterialUI code (MaterialUI is the point of the exercise for me).

I note the dependency on  `'@headlessui/react'` -- that may explain a lot.

**Comment by SomervilleTom** [comment] 2023-10-11 14:26
I updated to v13.5.4 and all is still well (running the 'nextgram' example).

I removed the "experimental" section from `'next.config.js'`.

Now I'll try adding back in the MUI behavior (piece by piece).

**Comment by joefitter** [comment] 2023-10-11 16:15
Hey, pretty sure this bug has been fixed but not included in a major release yet. I updated to 13.5.4-canary.6 which fixed the MUI issues

**Comment by SomervilleTom** [comment] 2023-10-11 22:05
I was finally able to apply a patch to "start-server.js" for v13.5.4 so that 'yarn dev' start a dev server listening on https instead of http, using the `nextgram` example code.

No console complaints, and the MUI version of 'nextgram' behaves as expected.

I'm finally able to resume development on my own MUI modal behavior.

**Comment by feedthejim** [comment] 2023-10-12 06:45
I'm gonna close this issue because it seems while it's clear people are having various issues with parallel routes, it's unclear to me if they are not related to the original issue in particular.
 
Please open new issues with repros and a description of what doesn't work and feel free to ping me directly there.

**Closed by feedthejim** 2023-10-12 06:45 UTC
Labels: template: bug
