### ISSUE TITLE
NextJS shows warnings for additional properties in config used by other libraries

### ISSUE THREAD

**Issue by Zeko369** [vercel/next.js#39606] opened 2022-08-15 11:13 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.0.0: Mon Aug  1 06:32:26 PDT 2022; root:xnu-8792.0.207.0.6~26/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.11.0
      npm: 8.0.0
      Yarn: 1.22.19
      pnpm: 7.9.0
    Relevant packages:
      next: 12.2.6-canary.0
      eslint-config-next: 12.2.2
      react: 18.2.0
      react-dom: 18.2.0
```

### What browser are you using? (if relevant)

Sizzy 68.0.0-beta.4

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

When using next.js with i.e. blitz / withTM / ... any library that export a config and requires a custom property shows the following warning
```
warn  - Invalid next.config.js options detected: 
  - The root value has an unexpected property, blitz, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
```

### Expected Behavior

Easies -> set `additionalProperties` to true in JSON schema

So so -> Option to disable this in general in the config

Best but hardest to do right ->  There could be an option to disable this on a framework level
i.e. withBlitz returns `{...config, ignoreKeys: [...config.ignoreKeys, 'blitz']}`

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-nckpep?file=next.config.js

### To Reproduce

Add any unknown key to `next.config.js` and it should show the warning

**Comment by Zeko369** [comment] 2022-08-15 11:15
Also would love to PR this if Next team is onboard (currently we're building a hook that's going to patch `next-config-validate.js` to set the top level `additionalProperties` to true)

**Comment by ijjk** [comment] 2022-08-16 00:03
Closing as a duplicate of https://github.com/vercel/next.js/issues/39161, setting `additionalProperties` to `true` is not ideal here as it won't catch typos in configs which this validation was meant to help catch. Instead plugins that wrap Next.js' config should follow the plugin pattern shown here https://github.com/vercel/next.js/blob/canary/packages/next-bundle-analyzer/index.js which doesn't attach the plugin specific config to the returned next config.

**Closed by ijjk** 2022-08-16 00:03 UTC
Labels: template: bug
