### ISSUE TITLE
router.push() does not get the latest ISR on-demand revalidated page 

### ISSUE THREAD

**Issue by anasqadrei** [vercel/next.js#40927] opened 2022-09-27 02:19 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101
Binaries:
      Node: 14.19.1
      npm: 8.6.0
      Yarn: N/A
      pnpm: N/A
Relevant packages:
      next: 12.3.2-canary.9
      eslint-config-next: 12.3.1
      react: 18.2.0
      react-dom: 18.2.0
```

### What browser are you using? (if relevant)

Safari version 16.0 (17614.1.25.9.10, 17614)

### How are you deploying your application? (if relevant)

next start or Vercel

### Describe the Bug

After ISR on-demand revalidation and waiting to the page to be regenerated, `router.push()` doesn't show the regenerated page where `next/link` does. It happens when you push or link from the page to itself.

### Expected Behavior

After revalidation, `router.push()` should show the new content.

### Link to reproduction

https://codesandbox.io/s/ancient-dew-d28bz0

### To Reproduce

The CodeSandbox above uses `next dev`. I'm referring to `next start` or deployment on Vercel.

1. Go to: [https://csb-d28bz0-nz1ywkx5j-anasqadrei.vercel.app](https://csb-d28bz0-nz1ywkx5j-anasqadrei.vercel.app)
index.js page has getStaticProps that will return the time of generation and show it on the page
```javascript
export async function getStaticProps() {
  return {
    props: {
      time: new Date().getTime(),
    },
  }
}
```
2. The page has Link, push, push with skipClientCache, replace and reload. If you click any of those, the time won't change. You'll get the previously generated page.
3. Click revalidate. This will call the revalidate api. getStaticProps will be called, it will return a new time and a new page will be generated
4. Wait few seconds for the page to be regenerated 
5. Click push, push with skipClientCache or replace. Nothing will happen. The time won't change. It gets the old generated page.
6. Click Link. The time will change and you will see the newly regenerated page.

The expected behaviour is to see a new time whenever push is clicked after revalidate

**Comment by ijjk** [comment] 2022-09-27 04:56
Closing as a duplicate of https://github.com/vercel/next.js/issues/39186#issuecomment-1200166303

**Comment by anasqadrei** [comment] 2022-09-27 05:03
@ijjk I read #39186 before writing this. My code is different. There is no racing condition in my code.

**Comment by ijjk** [comment] 2022-09-27 05:40
Ah I see, the reproduction fails to return a response in the revalidate API route so it timed out and never revalidated properly so seemed like a duplicate. After fixing the reproduction I am able to see the issue the described.

**Closed** 2022-09-27 06:30 UTC
Labels: template: bug
