### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by slackerzz** [vercel/next.js#43772] opened 2022-12-06 15:25 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
    Binaries:
      Node: 16.18.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: 7.18.0
    Relevant packages:
      next: 13.0.7-canary.1
      eslint-config-next: 13.0.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/slackerzz/next-middleware-error

### To Reproduce

1. Visit [https://next-middleware-error-git-main-lorenzo2.vercel.app](https://next-middleware-error-git-main-lorenzo2.vercel.app/)
2. the first two links (foo, bar) are ok
3. clicking the third link (baz) point to a page that should returo 404 but you will get:
```
Application error: a client-side exception has occurred (see the browser console for more information).
```

### Describe the Bug

The error is triggerd only if you run `pnpm build && pnpm start`, it is not present if you run `pnpm dev`.

If you remove the `middleware.ts` file from the project the error is gone and you will get a 404 page as expected.

When a middleware is present the `/test/baz` gets `undefined` as props. It seems related to `getStaticProps` returning `{ notFound: true }`

### Expected Behavior

The presence of a middleware should not interfere with page props

### How are you deploying your application? (if relevant)

Vercel

**Comment by slackerzz** [comment] 2022-12-22 16:12
This bug is reproducible also with the laster next 13.1

**Comment by singhofmarco** [comment] 2023-01-31 11:14
I have the exact same issue...

**Comment by wadehammes** [comment] 2023-02-03 15:43
Can confirm this is happening as well. Had to downgrade back to 13.0.6 for time being.

**Comment by Confuze** [comment] 2023-02-04 14:00
Dealing with the same issue right now. I really hope there's a fix for this.

**Comment by slackerzz** [comment] 2023-02-04 16:43
@wadehammes in 13.0.6 it works as expected? I discovered it in 12.3.3 and then in 13.1.
I think it is related to the Link component prefetching but i couldn't dig deeper

**Comment by pimmee** [comment] 2023-02-05 14:27
This happened to us when we deployed a new version.

1. User on page X
2. We deploy a new version (with Vercel)
3. User clicks link to open a new page
4. Error occurred: `Application error: a client-side exception has occurred (see the browser console for more information).`

Also I've received it during development.

**Comment by sindremb** [comment] 2023-02-15 10:50
We also had this issue on our end (v13.1.6)

Every first navigation to certain app folder routes with dynamic route segments would fail, but as long as at least one user had *navigated* to the page once after deploy, the page would work for everyone.

The navigation failed because the browser was served an application/octet-stream (.rsc in the .next/app folder) version of the page which referenced chunks that no longer existed in the current deployment.

The reason for getting the old content on first navigation in our case was due having some dynamic route param that was not known at build time, possibly combined with our self hosting of the next application.

For these pages with incompletely generated static params at build time, .next would generate .html and .rsc files on demand as it was running in our self hosted environment, which was persisted in the .next/app folder alongside files generated at build time. Since these files were not part of our deployment package, they would not be affected by the following deploy, and therefore stick around through multiple deployments. These files were detected as stale by next, but would still be served to the first visitor before new content was generated in the background. These visitors would then experience the exact issue described here.

The fix we have added to solve our specific case is to just ensure that all such "on demand generated" content is cleared during each deployment.

I am not sure how well our case translates to people hosting next applications in other ways, but thought it could be helpful information for people regardless.

**Comment by junedkhatri31** [comment] 2023-02-15 18:35
Facing same issue. This is logs from console. It is not happeing in development server for me. Only heppenning on deployed version on Vercel.
<img width="942" alt="Screenshot 2023-02-16 at 12 04 40 AM" src="https://user-images.githubusercontent.com/20799038/219121240-4bde4a62-2ca9-481c-9315-9faf466776da.png">

**Comment by junedkhatri31** [comment] 2023-02-18 12:41
> Facing same issue. This is logs from console. It is not happeing in development server for me. Only heppenning on deployed version on Vercel. <img alt="Screenshot 2023-02-16 at 12 04 40 AM" width="300" src="https://user-images.githubusercontent.com/20799038/219121240-4bde4a62-2ca9-481c-9315-9faf466776da.png">

In my case I was using `process.env.APP_ROOT_URL` in heading tag in root page. But did not activate `APP_ROOT_URL` environment variable for Preview apps.

I have uploaded buggy code here - https://github.com/junedkhatri31/vercel-reproduce/blob/main/app/head.tsx

**Comment by samcx** [comment] 2023-03-04 02:44
Closing as a duplicate of → https://github.com/vercel/next.js/issues/38239.

**Closed by samcx** 2023-03-04 02:44 UTC
Labels: template: bug

**Comment by samcx** [comment] 2023-03-05 00:45
@slackerzz I have verified that the latest canary → https://github.com/vercel/next.js/releases/tag/v13.2.4-canary.3 <picture data-single-emoji=":fixed:" title=":fixed:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..Eq3FyF7CY3kSHkYj.QEqpQsC-Iin7XEOjm7dhvUpvneRyk5q2ysn5_i7k1MVRkORXqZeaFTpP3eanrkwNovInqkpj6Z3fF28XUJcBuNTijxXMvRT9qnILRiJxFF5rgmi2dJVE.5Dyk6099T6-NYuCWN2AQJw" alt=":fixed:" align="absmiddle"></picture> this issue!
