### ISSUE TITLE
[BUG] The Serve-Send-Event request cannot receive a close event.

### ISSUE THREAD

**Issue by StringKe** [vercel/next.js#50804] opened 2023-06-05 16:03 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.0
    Relevant packages:
      next: 13.4.4
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

https://stackblitz.com/edit/stackblitz-starters-n5uvup?file=pages%2Findex.js

### To Reproduce

1. open the recurrence connection (I did not find the page function of CodeSandbox, I used StackBlitz)
2. Open the browser console
3. Click the button and wait a while
4. Click the button again.

### Describe the Bug

Create an SSE (Server-Sent-Event) request using an API Endpoint that does not receive a disconnect event properly when the client disconnects.

### Expected Behavior

API Request is able to accept disconnected events, as the inability to accept events causes the timer to run forever and add a new one each time it runs.

### Which browser are you using? (if relevant)

Microsoft Edge 113.0.1774.57

### How are you deploying your application? (if relevant)

none

### note 2023-6-6
I tried to write an api with the same functionality using express and I can receive the close event.

https://github.com/StringKe/node-sse-example

link1: https://github.com/vercel/next.js/discussions/48682

**Comment by helmturner** [comment] 2023-06-08 03:09
Is this expected behavior? It seems to be mentioned in the fastify docs https://www.fastify.io/docs/latest/Guides/Detecting-When-Clients-Abort/

**Comment by timcole** [comment] 2023-06-08 04:48
Heyo, I tested this out and noticed two things.
1. I tried it locally and same issue, however if I downgrade next to v12.3.4 it works as expected, and 3 of the 4 on close events fire. The issue seems to be next v13 related.
2. Stackblitz's proxy seems to keep the connection alive so it never closes no matter which version I use.

**Comment by TCatshoek** [comment] 2023-06-08 12:04
I also tested it locally, and it seems to work on next@13.0.6, but not on latest. It seems like any version higher than 13.2.4 causes issues (13.3.0 does not work properly)

**Comment by StringKe** [comment] 2023-06-11 11:02
I tested the version and found that this issue first appeared in 13.2.5-canary.27.

13.2.5-canary.26 is work

**Comment by StringKe** [comment] 2023-06-27 02:19
next@13.4.7 The presence of this problem remains.

[v13.4.8-canary.5](https://github.com/vercel/next.js/releases/tag/v13.4.8-canary.5) The problem was not detected

**Comment by jridgewell** [comment] 2023-06-28 20:26
Fixed by https://github.com/vercel/next.js/pull/51727

**Closed by jridgewell** 2023-06-28 20:26 UTC
Labels: template: bug, area: Edge
