### ISSUE TITLE
Issue running yarn dev after creating a brand new next.js app

### ISSUE THREAD

**Issue by rei-shaholli** [vercel/next.js#37247] opened 2022-05-27 15:42 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.13.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.18
      react: 18.1.0
      react-dom: 18.1.0

### Describe the Bug

I created a new next.js app with typescript via: 

`npx create-next-app@latest --ts`

then ran `npm run dev`

I got the following error message:

**error - ./node_modules/next/dist/client/dev/amp-dev.js**
Module not found: Can't resolve '[pathtoproject]\node_modules\next\dist\compiled\regenerator-runtime\runtime.js' in '[pathtoproject]\node_modules\next\dist\client\dev'

I cleared the node_modules and npm install again.  Same issue.

package.json
{
  "name": "***",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^12.1.7-canary.18",
    "react": "18.1.0",
    "react-dom": "18.1.0"
  },
  "devDependencies": {
    "@types/node": "17.0.35",
    "@types/react": "18.0.9",
    "@types/react-dom": "18.0.5",
    "eslint": "8.16.0",
    "eslint-config-next": "12.1.6",
    "typescript": "4.7.2"
  }
}

### Expected Behavior

The app should be served locally.

### To Reproduce

1. perform an `npx create-next-app@latest --ts` 
2. run the command `npm run dev`
3. observe the error.

**Comment by balazsorban44** [comment] 2022-05-30 15:07
It sounds like a duplicate of https://github.com/vercel/next.js/issues/36259

Could you confirm what `[pathtoproject]` is supposed to be?

**Comment by rei-shaholli** [comment] 2022-05-30 15:26
it's the absolute path to the nextjs project.

**Comment by balazsorban44** [comment] 2022-05-31 10:08
Could you specify, please? I am trying to figure out your project folder's name. It might be important, please see the linked issue.

**Comment by londonadagio** [comment] 2022-06-09 10:40
I just had the same issue, my project folder was named `nextjs-vercel`, changing it to `vercel-nextjs` didn't work, but changing the folder to `vercel-test` did work. 

That was with next version 12.1.6 running on node 16.14.0 on Windows 11 (22621.1 specifically).

**Comment by JanKaifer** [comment] 2023-01-17 10:08
Closing as duplicate of https://github.com/vercel/next.js/issues/36259

**Closed by JanKaifer** 2023-01-17 10:08 UTC
Labels: template: bug, area: Compiler
