### ISSUE TITLE
Unable to build SSG AMP-enabled page on index page

### ISSUE THREAD

**Issue by jasson2788** [vercel/next.js#23462] opened 2021-03-27 19:40 UTC
### What version of Next.js are you using?

10.0.6

### What version of Node.js are you using?

15.12.0

### What browser are you using?

Chome

### What operating system are you using?

Linux

### How are you deploying your application?

github

### Describe the Bug

On index page cannot build SSG with amp hybrid.

I'm getting this error:
> Build error occurred
[Error: ENOENT: no such file or directory, rename '/home/jasson/Dev/personal/.next/export/en/index.amp.html' -> '/home/jasson/Dev/personal/.next/server/pages/en/index.amp.html'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/home/jasson/Dev/personal/.next/export/en/index.amp.html',
  dest: '/home/jasson/Dev/personal/.next/server/pages/en/index.amp.html'
}

### Expected Behavior

It should build without errors.

### To Reproduce

1. Add to pages/index.ts:

export const config = { amp: 'hybrid' };

2. Try to build.

**Comment by Jeonghyun-Kim** [comment] 2021-04-11 10:57
I'm getting the same error right now. anyone knows how to solve this?

**Comment by ijjk** [comment] 2021-04-17 16:18
Closing as a duplicate of https://github.com/vercel/next.js/issues/23462

**Closed by ijjk** 2021-04-17 16:18 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
