### ISSUE TITLE
Unhandled Runtime Error after upgrade to v9.5.4

### ISSUE THREAD

**Issue by dotKuro** [vercel/next.js#17842] opened 2020-10-13 15:04 UTC
# Bug report

## Describe the bug

After upgrading from version 9.5.3 to 9.5.4 running the project in dev mode will cause an Unhandled Runtime Error. The exact error message actually differs from browser to browser.

Firefox:
```
Unhandled Runtime Error

InvalidCharacterError: String contains an invalid character
Source

../../client/head-manager.ts (12:13) @ reactElementToDOM

  10 | 
  11 | function reactElementToDOM({ type, props }: JSX.Element): HTMLElement {
> 12 |   const el = document.createElement(type)
     |             ^
  13 |   for (const p in props) {
  14 |     if (!props.hasOwnProperty(p)) continue
  15 |     if (p === 'children' || p === 'dangerouslySetInnerHTML') continue

Call Stack
updateElements/<
../../client/head-manager.ts (62:4)
updateElements
../../client/head-manager.ts (46:2)
updateHead/updatePromise<
../../client/head-manager.ts (109:22)
```

Chrome:
```
Unhandled Runtime Error
InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('({
  description,
  imageUrl
}) => __jsx(react__WEBPACK_IMPORTED_MODULE_0___default.a.Fragment, {
  __self: undefined,
  __source: {
    fileName: _jsxFileName,
    lineNumber: 12,
    columnNumber: 3
  }
}, __jsx("meta", {
  key: "twitter-card",
  name: "twitter:card",
  content: "summary_large_image",
  __self: undefined,
  __source: {
    fileName: _jsxFileName,
    lineNumber: 13,
    columnNumber: 5
  }
}), __jsx("meta", {
  key: "twitter-site",
  name: "twitter:site",
  content: "@censored",
  __self: undefined,
  __source: {
    fileName: _jsxFileName,
    lineNumber: 14,
    columnNumber: 5
  }
}), __jsx("meta", {
  key: "twitter-title",
  name: "twitter:title",
  content: "censored",
  __self: undefined,
  __source: {
    fileName: _jsxFileName,
    lineNumber: 15,
    columnNumber: 5
  }
}), __jsx("meta", {
  key: "twitter-description",
  name: "twitter:description",
  content: description,
  __self: undefined,
  __source: {
    fileName: _jsxFileName,
    lineNumber: 16,
    columnNumber: 5
  }
}), __jsx("meta", {
  key: "twitter-image",
  name: "twitter:image",
  content: `https://www.censored.tld${imageUrl}`,
  __self: undefined,
  __source: {
    fileName: _jsxFileName,
    lineNumber: 17,
    columnNumber: 5
  }
}))') is not a valid name.

Source
../../client/head-manager.ts (12:13) @ reactElementToDOM

  10 | 
  11 | function reactElementToDOM({ type, props }: JSX.Element): HTMLElement {
> 12 |   const el = document.createElement(type)
     |             ^
  13 |   for (const p in props) {
  14 |     if (!props.hasOwnProperty(p)) continue
  15 |     if (p === 'children' || p === 'dangerouslySetInnerHTML') continue
Call Stack
eval
../../client/head-manager.ts (62:19)
Array.forEach
<anonymous>
updateElements
../../client/head-manager.ts (46:2)
eval
../../client/head-manager.ts (109:8)
```
Safari:
```
Unhandled Runtime Error
InvalidCharacterError: The string contains invalid characters.
Call Stack
createElement

[native code]
forEach

[native code]
promiseReactionJob

[native code]
```

The Chrome error message seems to mirror the content of our TwitterCard component, which looks like this:
```typescript
import React, { FunctionComponent, ReactElement } from 'react';

interface TwitterCardProps {
  description: string;
  imageUrl: string;
}

const TwitterCard: FunctionComponent<TwitterCardProps> = ({
  description,
  imageUrl
}): ReactElement => (
  <React.Fragment>
    <meta key='twitter-card' name='twitter:card' content='summary_large_image' />
    <meta key='twitter-site' name='twitter:site' content='@censored' />
    <meta key='twitter-title' name='twitter:title' content='censored' />
    <meta key='twitter-description' name='twitter:description' content={ description } />
    <meta key='twitter-image' name='twitter:image' content={ `https://www.censored.tld${imageUrl}` } />
  </React.Fragment>
);

export { TwitterCard };
```
I cannot see what should be wrong with this component though.

## To Reproduce

I wasn't really able to reproduce it except with our private code base. We just updated and the error started appearing whenever you start the dev server and load the page in the browser. The error will pop up immediately.

After downgrading the error is won't appear anymore.

## Expected behavior

No error appears, just like before upgrading.

## System information

- OS: macOS
- Browser: Chrome, Safari and Firefox
- Version of Next.js: 9.5.3/9.5.4
- Version of Node.js: 14.13.0

**Comment by vipul0092** [comment] 2020-10-13 16:48
Possible duplicate of https://github.com/vercel/next.js/issues/17721

**Comment by jamesmosier** [comment] 2020-10-13 19:15
Closing in favor of #17721 which also includes a reproduction.

**Closed by jamesmosier** 2020-10-13 19:15 UTC

**Comment by balazsorban44** [comment] 2022-01-29 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
