### ISSUE TITLE
App dir: Navigating to or from app level not-found doesnt show new page

### ISSUE THREAD

**Issue by AndrisBorbas** [vercel/next.js#48880] opened 2023-04-26 16:22 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro   
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.2-canary.7     
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
```

Edit: appDir, Router

### Link to the code that reproduces this issue

https://github.com/AndrisBorbas/next-not-found-no-refresh

### To Reproduce

If you click on the not-found link then the not found page doesnt come up, it only comes up if you refresh the page. When on the not found page, clicking any links also wont change pages, the change will only happen if you manually refresh the page.

```bash
├── app
│   └── classic
│       └── page.tsx
├── layout.tsx
├── not-found.tsx
└── page.tsx
```

### Describe the Bug

A not found page in the root app directory will not show up when navigated to and you won't be able to navigate away from it either with links. It doesn't work in localhost or Vercel either. But after clicking on the not found link and when nothing happens, clicking on the found link, it will just navigate there.

### Expected Behavior

When clicking a link that goes to a non existent page the not-found page would show up.

### Which browser are you using? (if relevant)

Chrome 112.0.5615.138

**Comment by jhemarcos** [comment] 2023-04-26 18:38
#48836

**Comment by jhemarcos** [comment] 2023-04-26 18:39
Also reported in #48836.

**Comment by martinrojas** [comment] 2023-04-28 04:24
The issue happens when the links are Next Links. If you are using regular `<a href='' >` The page behaves as expected. This is happening on `"next": "13.3.1",` and to continue to clarify it only seems to happen on the root not-found. 

Also not sure if this is part of the bug or not, but on localhost on the dev. the page seems to continue to reload on an infinite loop.

**Comment by timneutkens** [comment] 2023-04-28 09:21
Duplicate of #47862

**Closed by timneutkens** 2023-04-28 09:21 UTC
Labels: template: bug
