### ISSUE TITLE
Output standalone mode not omtimizing images?

### ISSUE THREAD

**Issue by nekmart** [vercel/next.js#41111] opened 2022-10-02 17:32 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Hello, I use [automatically coping traced file](https://nextjs.org/docs/advanced-features/output-file-tracing#automatically-copying-traced-files) for deploying my site to ec2 server. I follow this documentation-

https://nextjs.org/docs/advanced-features/output-file-tracing#automatically-copying-traced-files

Here first of all I updated my `next.config.js` file-

```
module.exports = {
  output: 'standalone',
}
```

Then after building I manually copy `static` folder to `standalone/.next/` and also copy `public` folder to `standalone/`. After copying the run `node server.js`. It running successfully. But image optimization not working.

In `terminal` I found this error- 

`Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly`

But When I check `standalone/package.json` and `standalone/node_modules` I can see It already have `sharp` package.

Then after some researching, i also add a `environment varriable` to `standalone/.env` file as `NEXT_SHARP_PATH=/tmp/node_modules/sharp next start`

Image optimization still not working. 

I try to some different way -
`NEXT_SHARP_PATH=/tmp/node_modules/sharp next standalone`,
`NEXT_SHARP_PATH=/tmp/node_modules/sharp standalone`,
`NEXT_SHARP_PATH=/node_modules/sharp`,
`NEXT_SHARP_PATH=/tmp/node_modules/sharp`

Still image optimization not working. How can I fix that problem.

### Describe the Bug

Image optimization not working on `standalone output`

### Expected Behavior

It should work in standalone mood

### Link to reproduction
https://github.com/nekmart/nekmart-reproduction
https://nekmart.com/

### To Reproduce

`NEXT_SHARP_PATH=/tmp/node_modules/sharp next standalone`,

**Comment by naimulemon** [comment] 2022-10-02 17:35
I am having same problem . I want a solution how to host .

**Comment by balazsorban44** [comment] 2022-10-03 16:01
I could not reproduce this, please add a reproduction. Make sure you add `sharp` as a dependency, eg with `npm i sharp` before build, so it gets properly traced.

**Comment by balazsorban44** [comment] 2022-10-03 16:12
Could you link to your repository so I can have a look? It works for me locally.

**Comment by nekmart** [comment] 2022-10-03 16:16
Here is my reproduction link-
https://github.com/nekmart/nekmart-reproduction
https://nekmart.com/

**Comment by nekmart** [comment] 2022-10-03 16:21
@balazsorban44, Thank you, for your reply. I'm stacking for 2 months. No solution I am finding. That's why I create this issue. Please help me Please. I need it😭.

**Comment by nekmart** [comment] 2022-10-03 16:27
***Note: I use linux subsystem on windows. In linux subsystem, When I run product mode npm run start. Image optmization automatically work in this mode, I haven't to give .env also. When I start my project in standalone mood, image optimization is not working. Even when I give .env it's not working.

Here is my next.config.js-

```
/** @type {import('next').NextConfig} */
const withPWA = require("next-pwa")({
  dest: "public",
  register: true,
  disable: process.env.NODE_ENV === "development"
});

const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  output: "standalone",
  images: {
    minimumCacheTTL: 2592000,
    domains: ["dzzoo94ozikw5.cloudfront.net", "lh3.googleusercontent.com", "platform-lookaside.fbsbx.com"]
  },
}

module.exports = withPWA(nextConfig)
```

**Comment by balazsorban44** [comment] 2022-10-03 16:32
Hmm, I am still unable to reproduce, given your repository. There are a lot of complex parts in there, could you make it more minimal? Have a look at [this video](https://www.youtube.com/watch?v=cuoNzXFLitc) for some tips.

Just remove any code that does not contribute to the issue. This way, we can concentrate on the issue more specifically.

Also, don't forget to test with `next@canary` to make sure the issue hasn't already been fixed in a newer Next.js release.

**Comment by nekmart** [comment] 2022-10-03 16:35
I am using next version `12.2.3`. But newer version `12.3.1`

**Comment by balazsorban44** [comment] 2022-10-03 16:38
Yes, could you please install `npm i next@canary` and retry `next build`?

**Comment by nekmart** [comment] 2022-10-03 17:11
I test it with `next@canary` but not working. Please help me.

**Comment by balazsorban44** [comment] 2022-10-03 18:40
we will need a reliable reproduction first. as of now, I cannot reproduce. since you set `NEXT_SHARP_PATH` could you run `node -p "require('/tmp/node_modules/sharp')"`

where the path is what you set and let us know what it yelds?

**Comment by nekmart** [comment] 2022-10-04 06:34
I think it worked now successfully. Problem occured in webpack. Before outpur tracing process, I host this project to aws amplify. Aws amplify told me to install webpack as dependency. By uninstalling webpack it worked successfully now.

1. I can't clearly say that problem occurred for webpack only.
2. I also update my project to latest next version.
3. I also clear some code in next config
4. I also remove NEXT_SHARP_PATH from environment varriable

After doing above step, I just again run build. This time it worked successfully!.

I am closing my issue.

`Specially thanks` to @balazsorban44 `If don't help me, I can't solve that problem. Thank you very much. You are really a good person. Thanks again`

**Closed** 2022-10-04 06:34 UTC
Labels: area: next/image, area: standalone mode, please verify canary

**Comment by balazsorban44** [comment] 2022-10-04 08:59
`webpack` is part of Next.js, so it shouldn't have needed to be installed as a dependency, as you say. Happy that it worked out! :tada:
