### ISSUE TITLE
Rewrites don't support dynamic pages with getStaticProps yet.

### ISSUE THREAD

**Issue by tbgse** [vercel/next.js#16086] opened 2020-08-11 16:22 UTC
Hey Next team,

we've just encountered this error today with our setup. I think the desired feature is very clear by looking at this error.

```
Error: Rewrites don't support dynamic pages with getStaticProps yet.
Using this will cause the page to fail to parse the params on the client
See more info: https://err.sh/next.js/rewrite-auto-export-fallback
```

I've seen that this message was added to the codebase sometime in February. The `yet` makes it sound like this is already a planned feature. But is this actually being in active development or should we not hold our breath for this to become available anytime soon and look for a different solution?

The reason why we are looking into a combination of rewrites + dynamic pages with getStaticProps is because of the hard limit that vercel is putting on rewrites.

**Comment by ijjk** [comment] 2020-08-11 21:26
Hi, an issue for tracking this feature is open here https://github.com/vercel/next.js/issues/16086 and support for this feature is in progress. I'm going to close this issue in favor of the existing one

**Closed by ijjk** 2020-08-11 21:26 UTC

**Comment by tbgse** [comment] 2020-08-12 05:51
@ijjk it seems to me that the link to the other issue above is wrong? It's linking to #16086 which is this issue (that is now closed)

**Comment by timneutkens** [comment] 2020-08-12 07:38
Github autocomplete does that sometimes 😿 This is the issue JJ was referring to: #14695

**Comment by tbgse** [comment] 2020-08-12 07:43
thanks for the update @timneutkens. Will follow the PR closely. 🥳

**Comment by balazsorban44** [comment] 2022-01-29 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
