### ISSUE TITLE
ReferenceError: _ is not defined [12.3]

### ISSUE THREAD

**Issue by irisarco** [vercel/next.js#40405] opened 2022-09-09 15:21 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022
    Binaries:
      Node: 17.4.0
      npm: 8.12.1
      Yarn: 1.22.17
      pnpm: 7.11.0
    Relevant packages:
      next: 12.3.1-canary.0
      eslint-config-next: 12.3.0
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Executing code like this results in `ReferenceError: _ is not defined` using next@12.3.0 (or canary).

```js
const blob = new Blob();
new Uint8Array(await blob.arrayBuffer());
```

Code below works without any errors:
```js
const blob = new Blob();
const buffer = await blob.arrayBuffer();
new Uint8Array(buffer);
```

It works correctly on next@12.2.5

### Expected Behavior

Code above should work regardless of how I decide to structure it.

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-wjnnuq?file=pages/index.tsx

### To Reproduce

1. Open attached reproduction
2. Click the button
3. Error is thrown

**Comment by SukkaW** [comment] 2022-09-09 15:50
Seems to be duplicated with #40399

**Comment by balazsorban44** [comment] 2022-09-09 15:51
Closing in favor of #40399

**Closed by balazsorban44** 2022-09-09 15:51 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-09-09 15:53
Thanks for the reproduction though! :pray:
