### ISSUE TITLE
Dynamic API routes appear to be matched to a page when rewrite present

### ISSUE THREAD

**Issue by jperegoy** [vercel/next.js#26454] opened 2021-06-21 21:36 UTC
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Firefox

### What operating system are you using?

OS 10.15.7

### How are you deploying your application?

N/A, Local

### Describe the Bug

When a capture group is used at the head of a url (via rewrites), dynamic API routes appear to be collected therein. Static paths to API routes work as expected as does page routing.

### Expected Behavior

Dynamic API routes are hit and return appropriate data when requested.

### To Reproduce

We have a situation where a variable number of segments are dynamic at the head of a url, and can be terminated by certain static segments, i.e. `/usa/new-york/new-york-city` or `germany/berlin`.  `/hotels` is an example of a group-terminating segment. As catch-all groups may not be used in these positions for the standard, directory-structure routing we've incorporated rewrites into the `next.config.js` file:

```
async rewrites() {
      return [
        {
          source: "/:place*/hotels",
          destination: "/places/hotels/list"
        },
        {
          source: "/:place*/hotels/:slug",
          destination: "/places/hotels/single"
        },
        {
          source: "/:place*",
          destination: "/places/place"
        },
      ]
    }
  }
  ```

From both a page file and a component (using `useSWR`) attempts to fetch a dynamic API route are met with the error: `TypeError: Cannot read property 'route' of undefined`. This is thrown from a page component, where we are looking for this `route` property.

```
/* In component */
const { data, error } = useSWR("http://localhost:3000/api/maps/arbitrary", url => fetch(url).then(r => r.json()));

/* In `getServerSideProps`*/
const data = await fetch("http://localhost:3000/api/maps/arbitrary").then(r => r.json());
```

Where the relevant directory structure is:
```
/pages
-- /api
-- -- /maps
-- -- -- /index.js
-- -- -- /[id].js
-- / places
-- -- index.js
-- -- /hotels
-- /articles
```

Both `index.js` and `[id].js` are the same example function:
```
export default (req, res) => {
  res.status(200).json({ test: "string" })
};
```

With Next setup like so, routing to an arbitrary place page with and without a terminating segment, fetching a non-dynamic API route in either a _GetProps_ function or SWR work, and the natively-routed `/articles` behave as expected. Fetching a dynamic API route appears to be matched and directed by the third rewrite group:

```
{
  source: "/:place*",
  destination: "/places/place"
},
```

**Comment by ijjk** [comment] 2021-06-22 15:07
Hi, this is the expected behavior for the `/:places*` catch-all rewrite as these come before dynamic routes by default. If you would like to only match this rewrite after checking all dynamic routes you can use a `fallback` rewrite ([related documentation](https://nextjs.org/docs/api-reference/next.config.js/rewrites)).

I'm going to close this since it doesn't appear to be a bug and the rewrite appears to be working as currently expected.

**Closed by ijjk** 2021-06-22 15:07 UTC
Labels: template: bug

**Comment by jperegoy** [comment] 2021-06-23 21:07
Ah, this is super helpful. Thanks and sorry for the noise.

**Comment by balazsorban44** [comment] 2022-01-28 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
