### ISSUE TITLE
NextApiResponse.json does not serialize non-objects as expected

### ISSUE THREAD

**Issue by husseinhere** [vercel/next.js#33582] opened 2022-01-23 20:14 UTC
### Run `next info` (available from version 12.0.8 and up)

/bin/sh: yarn: command not found
/bin/sh: pnpm: command not found

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 17.3.1
      npm: 8.3.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

v17.3.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

In an API route, `res.json(null)` outputs nothing

### Expected Behavior

That it goes through JSON.stringify (i.e. outputs `null`)

### To Reproduce

Put this in an API route:

```
import type { NextApiRequest, NextApiResponse } from "next";

type User = { name: string };

export default async (req: NextApiRequest, res: NextApiResponse<User | null>) => {
  if (false) {
    return res.json({ name: "bob" });
  } else {
    return res.json(null);
  }
};
```

**Comment by balazsorban44** [comment] 2022-01-24 00:30
Duplicate of #21749.

Already reported as per https://github.com/vercel/next.js/issues/21749#issuecomment-804377979

**Closed by balazsorban44** 2022-01-24 00:30 UTC
Labels: template: bug, area: API routes
