### ISSUE TITLE
[NEXT-1104] NextResponse.rewrite is not forwarding the request body to external hosts in dev

### ISSUE THREAD

**Issue by dbk91** [vercel/next.js#48040] opened 2023-04-06 18:54 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:43 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8112
    Binaries:
      Node: 19.6.1
      npm: 9.4.0
      Yarn: N/A
      pnpm: 7.27.0
    Relevant packages:
      next: 13.2.5-canary.33
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/dbk91/nextresponse-defect

### To Reproduce

Steps to reproduce specific to the linked repo:

1. Spin up a server on `http://localhost:4000` where you can log or inspect the body of a request.
2. Run `next dev` to start the development server for Next.js
3. Load the home page.
4. A POST request to `http://localhost:4000/test` should happen on component mount with a JSON body of `{"hello": 123}`

### Describe the Bug

The log shows no output of the JSON body.

### Expected Behavior

The server should receive `{"hello":123}` in the request body.

<sub>[NEXT-1104](https://linear.app/vercel/issue/NEXT-1104/nextresponserewrite-is-not-forwarding-the-request-body-to-external)</sub>

**Comment by dbk91** [comment] 2023-04-07 18:28
Update:

When I tested yesterday, I was unable to send any request on both my Mac mini and laptop using canary and the recently released 13.3. Today it appears to be resolved on both 13.3 and the current canary release. I suppose it must have been an issue specific to my dev environment, although it is odd that it persisted both after a restart and on two machines.

I'll leave this open until a maintainer closes it out if no one else is able to reproduce.

**Comment by rickiesmooth** [comment] 2023-04-08 10:05
strange, I'm still seeing the same issue.

**Comment by rickiesmooth** [comment] 2023-04-10 13:20
I've cloned the code that reproduces this issue, and since 13.3.0 the socket hangs up with the following error:

```
Failed to proxy http://localhost:4000/test Error: socket hang up
    at connResetException (node:internal/errors:717:14)
    at Socket.socketCloseListener (node:_http_client:475:25)
    at Socket.emit (node:events:525:35)
    at TCP.<anonymous> (node:net:322:12) {
  code: 'ECONNRESET'
}
```

when I downgrade to 13.2.4 the middleware works correctly 🤔

**Comment by dbk91** [comment] 2023-04-10 16:24
Thanks for the extra context @rickiesmooth.

I went back and confirmed that this is an issue with `next dev`. Once it's built, it doesn't appear to be an issue. Still exists in 13.3 and canary, AFAIK.

**Comment by steve-marmalade** [comment] 2023-04-11 23:47
> I went back and confirmed that this is an issue with next dev. Once it's built, it doesn't appear to be an issue. Still exists in 13.3 and canary, AFAIK.

This exactly sums up the issue, and can confirm that the bug in `next dev` is still present in the latest canary.

**Comment by BowlingX** [comment] 2023-04-12 11:26
Same problem when using `http-proxy-middleware` within an API route handler. Stopped working since `13.3.0`.

**Comment by steve-marmalade** [comment] 2023-04-12 15:50
I tested [v13.3.1-canary.5](https://github.com/vercel/next.js/releases/tag/v13.3.1-canary.5) and this issue is still present

**Comment by morgs32** [comment] 2023-04-12 21:58
It seems to me that it works fine until you try to write to a different host? If so I might change the issue title.

Here is a reproduction in one tiny [commit to the vercel/app-playground](https://github.com/morgs32/app-playground/commit/c5cca1f2070398fde3e1d8c4de795b052e90cd8d)

**Comment by steve-marmalade** [comment] 2023-04-13 05:20
@morgs32 that's a great point. This made me realize that, for my use case of proxying an external service, we can get away with doing a regular fetch and then returning a `NextResponse`. (Note that `NextResponse.redirect` is not a suitable workaround, since it doesn't appear to support setting headers like `rewrite` does). That said, I think using the `rewrite` API is still preferable, so I hope this issue gets picked up.

**Comment by morgs32** [comment] 2023-04-13 13:08
Ahh smart workaround though thanks for that.

**Comment by dbk91** [comment] 2023-04-13 20:54
Thanks everyone for all of the additional information. I updated the title to reflect the discoveries made in this thread—please correct it if it doesn't accurately reflect it or if I'm missing something.

@steve-marmalade Yes, it would be great if this fix got picked up. Our use-case is using the middleware to proxy to different APIs based on the first slug of the pathname. The `NextResponse.rewrite` makes this super simple to handle. And we use middleware rather than the `rewrites` in `next.config.js` because we make the host name configurable via an environment variable.

**Comment by yagiz-noonlight** [comment] 2023-04-19 20:18
@dbk91 We are doing the same exact thing. Do you have a working example to solve this issue?

**Comment by exallium** [comment] 2023-04-20 11:20
Seeing this as well, using rewrite middleware or next http proxy middleware, request body is not sent to external endpoint.

Broken version was 13.3.0, rolled back to 13.2.4 which works as expected.

**Comment by Xetoxyc** [comment] 2023-04-21 13:18
Can you confirm that 13.2.5-canary.26 still work ?

**Comment by dbk91** [comment] 2023-04-24 17:35
@yagiz-noonlight Unfortunately, we don't have much of a workaround. Any time we test POST requests we have to build the entire app locally and then test or we'd have to test it in the preview branches.

**Comment by muhammetenes** [comment] 2023-04-24 20:43
13.3.1 version has the same problem. I guess the only solution is to continue from 13.2.4

**Comment by mzronek** [comment] 2023-04-27 05:29
Same problem here as well. Without forwarding the headers from request, the rewrites in middleware.ts are stuck and just time out. Without the ability to forward the body as well, middleware proxying is impossible on local development.

Tried [13.3.2-canary.8](https://github.com/vercel/next.js/releases/tag/v13.3.2-canary.8) just to be sure and it doesn't fix the issue. Please let us know when this will be fixed.

**Comment by BowlingX** [comment] 2023-04-27 11:24
It works for me if I disable the `body-parser` for the given API:

```
export const config = {
  api: {
    bodyParser: false,
  },
}
```

**Comment by Angusross111** [comment] 2023-04-28 06:11
I also get the same issue when using the [rewrites](https://nextjs.org/docs/api-reference/next.config.js/rewrites) in `next.config.js` to an external url after upgrading to 13.3.1. Reverting back to 13.2.4 fixes it.

**Comment by selven** [comment] 2023-04-30 19:31
This is still an issue in 13.3.2. I've been trying to debug this, I think I've narrowed it down to this PR:
https://github.com/vercel/next.js/pull/48027

But I haven't been able to find a fix

**Comment by Xetoxyc** [comment] 2023-05-03 21:04
Still no fix ahead. Seems like next team is not aware of this problem @timneutkens

**Comment by sinclairnick** [comment] 2023-05-04 22:34
+1. This is bug has me pinned to 13.2.4 unfortunately

**Comment by cptcrank94** [comment] 2023-05-05 06:42
Vercel released 13.4 with stable app router and the issue still exists. 👎 Hope that we are not longer stuck in 13.2.4

**Comment by Xetoxyc** [comment] 2023-05-05 16:33
i just created a pull request for this issue https://github.com/vercel/next.js/pull/49320

**Comment by bennettdams** [comment] 2023-05-05 17:03
> i just created a pull request for this issue https://github.com/vercel/next.js/pull/49320

@Xetoxyc Have you checked whether this fixes the issue when using `rewrites` in `next.config.js` as described [here](https://github.com/vercel/next.js/issues/48040#issuecomment-1527040469)? It seems like your PR only takes care of middleware rewrites.

**Comment by Xetoxyc** [comment] 2023-05-05 17:08
> > i just created a pull request for this issue #49320
> 
> @Xetoxyc Have you checked whether this also fixes the issue when using `rewrites` in `next.config.js` as described [here](https://github.com/vercel/next.js/issues/48040#issuecomment-1527040469)? It seems like your PR only takes care of middleware rewrites (due to the `x-middleware-rewrite` header check).

You should try it if i remember correctly if u set it in next.conf the rewrite  header is also set

**Comment by leafyshark** [comment] 2023-05-06 15:04
+1 still cannot upgrade from v13.2.4 see: https://github.com/vercel/next.js/discussions/48265

**Comment by player3-blockchain-music** [comment] 2023-05-06 23:55
+1

**Closed** 2023-05-08 22:22 UTC
Labels: template: bug, area: Edge, area: app, linear

**Comment by ijjk** [comment] 2023-05-09 04:12
Hi, this has been updated in `v13.4.2-canary.3` of Next.js, please update and give it a try!

**Comment by florianliebig** [comment] 2023-05-09 08:02
Thanks for the fix so far! It works for me with external rewrite:

![2023-05-09 at 10 01](https://user-images.githubusercontent.com/10775702/237033291-e5fa7af7-e1e4-41e9-8695-fdce94e81eee.png)

But as soon as I change the headers in the rewrite it breaks again:

![2023-05-09 at 10 02](https://user-images.githubusercontent.com/10775702/237033425-fdb2b132-536b-437c-8700-f3a0c904d8c5.png)

**Comment by rickiesmooth** [comment] 2023-05-09 09:14
yay for me this fixed the issue 🎉 

@florianliebig you need the clone the request headers in order to modify them. This example shows you how to do that: https://vercel.com/templates/next.js/edge-functions-modify-request-header

**Comment by florianliebig** [comment] 2023-05-09 09:27
`    const newHeaders = new Headers(req.headers);

    newHeaders.set("origin", apiBase);
    newHeaders.set("host", apiBase.replace(RegExp(/(^\w+:|^)\/\//), ""));
    newHeaders.set("user-agent", "Cloud-CDN-Google");

    return NextResponse.rewrite(req.nextUrl, {
      request: {
        headers: newHeaders,
      },
    });`

Doesn't fix it for me unfortunately

**Comment by florianliebig** [comment] 2023-05-10 13:36
I still have issue when adding headers like in the guide. I was able to create test which creates an error (empty body on the API target): https://github.com/vercel/next.js/pull/49606

**Comment by sehrish30** [comment] 2023-05-14 04:32
No difference even if I add headers

` return NextResponse.rewrite(new URL("/login", request.url), {
        request: {
          headers: request.headers,
        },
   });`

`
 const url = request.nextUrl.clone();
 url.pathname = "/login";
 return NextResponse.rewrite(url);
`

both don't work!

This is my next js version "13.4.2"

**Comment by Xetoxyc** [comment] 2023-05-14 06:03
I cannot verify this. Try this code

```

const requestHeaders = new Headers(request.headers);

    return NextResponse.rewrite(`${URL}`, {
      request: {
        // New request headers
        headers: requestHeaders,
      },
    });

```

**Comment by sehrish30** [comment] 2023-05-14 09:40
> I cannot verify this. Try this code You should not use `request.headers` but `new Headers(request.headers)`
> 
> ```
> 
> const requestHeaders = new Headers(request.headers);
> 
>     return NextResponse.rewrite(`${URL}`, {
>       request: {
>         // New request headers
>         headers: requestHeaders,
>       },
>     });
> ```

still doesnot work do we need to add some configuration in next.config.js

**Comment by rickiesmooth** [comment] 2023-05-15 09:29
do you need to use `rewrite` or can you also call `next` like in the example?

```ts
  return NextResponse.next({
    request: {
      // New request headers
      headers: requestHeaders,
    },
  })
  ```

**Comment by florianliebig** [comment] 2023-05-16 14:58
> I cannot verify this. Try this code You should not use `request.headers` but `new Headers(request.headers)`
> 
> ```
> 
> const requestHeaders = new Headers(request.headers);
> 
>     return NextResponse.rewrite(`${URL}`, {
>       request: {
>         // New request headers
>         headers: requestHeaders,
>       },
>     });
> ```

@Xetoxyc The request itself works, but there won't be any body at the target if you modify the header. Or do you see any issue with me approach? https://github.com/vercel/next.js/pull/49606/files

![2023-05-16 at 16 58](https://github.com/vercel/next.js/assets/10775702/6a0c78f1-b7b6-4b78-a77d-21a2b9b90ca3)

@rickiesmooth `Response.next()` does not work on my side if you want to use it as a proxy to an external API (changing the header to avoid CORS issues)

**Comment by yagiz-noonlight** [comment] 2023-05-16 16:58
This issue is still not fixed. Anyone from Next.js team open this issue? @leerob

Example reproduction step on `middleware.ts`:


```typescript
  if (req.nextUrl.pathname.startsWith('/api/v1')) {
    // Don't mutate apiUrl directly due to concurrency
    const url = req.nextUrl.clone();
    url.protocol = apiUrl.protocol;
    url.host = apiUrl.host;
    url.hostname = apiUrl.hostname;
    url.port = apiUrl.port;
    url.pathname = url.pathname.slice('/api'.length);
    return NextResponse.rewrite(url)
  }
```

**Comment by Xetoxyc** [comment] 2023-05-16 17:05
I can not reproduce anything unexpected.
In my Prod app is use rewrite alot with adding header and body / without body. As i need to add license key headers to every request.

make sure to delete the .next folder and try again

**Comment by joacub** [comment] 2023-05-17 21:37
> I can not reproduce anything unexpected. In my Prod app is use rewrite alot with adding header and body / without body. As i need to add license key headers to every request.
> 
> make sure to delete the .next folder and try again

still not working, test with latest canary version, params in are not being forwarded

**Comment by timneutkens** [comment] 2023-05-22 19:26
Please open a new issue with a reproduction so that it can be triaged accordingly.
