### ISSUE TITLE
next/image: reader mode bugs

### ISSUE THREAD

**Issue by thebuilder** [vercel/next.js#21811] opened 2021-02-03 17:03 UTC
Trying to view a page on iOS reader mode results in both the image and the `sizerSvg` that fixes the size (on `intrinsic` layout) being rendered. This creates a lot of empty space above the image.

I've highlighted the svg here, but it is just transparent. 

![image](https://user-images.githubusercontent.com/3764345/106781889-db21c000-6649-11eb-8d21-e72a40eba0f9.jpeg)

The image itself is also smaller than expected, which might be related to the sizing applied?

Looking at other sites built with Next.js, there seems to be a few bugs with reader mode and images.
Try viewing https://leerob.io/blog/style-guides-component-libraries-design-systems in reader mode. Most images are simply not rendered.

**Comment by lachlanjc** [comment] 2021-02-15 01:12
Related/would be fixed by #22180

**Closed** 2021-12-22 02:18 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 02:14
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
