### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by ppot** [vercel/next.js#16058] opened 2020-08-10 22:55 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Not a problem with next , but a problem since next.

Deploying a dockerized envorinement localy for staging, I run into a problem where I was proxying my services api to `/api` in Nginx. The issue was that you can't do this and will resolve to a problem since nextjs will take this route and map it to `pages/api`

## Describe the solution you'd like

Add documentation to help future users to not use `/api` as a proxy pass. But something like `/services` or anything like this.

## Describe alternatives you've considered

Deploying to a sub route ex: `api.staging.x.x.x` . But to complex for the use case.

## Additional context

Feel free to delete it if it's not relevant to you.

**Comment by lachlanjc** [comment] 2021-01-08 06:48
To me this feels a bit out of scope for the docs, since API routes, which are optional to use, are well-documented in their routing being /api. You can always add a rewrite to make them accessible from another path, too.

**Comment by timneutkens** [comment] 2021-01-11 10:34
Based on the description what you were doing is definitely possible, but the main downside would be that you can't use Next.js API routes. As @lachlanjc said the docs clearly state the Next.js will use the `/api` path for API routes. In that case you added configuration in a layer above Next.js that did not route a certain path to Next.js in which case you're aware it does not route to Next.js, which the docs can't really cover 🤔 You can use https://nextjs.org/docs/api-reference/next.config.js/rewrites to map another url to api routes if needed.

**Closed by timneutkens** 2021-01-11 10:34 UTC

**Comment by balazsorban44** [comment] 2022-01-28 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
