### ISSUE TITLE
Create Next App fails on Node 10 due to `image-size`

### ISSUE THREAD

**Issue by illright** [vercel/next.js#26517] opened 2021-06-23 08:10 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

10.24.1

### What browser are you using?

None

### What operating system are you using?

macOS

### How are you deploying your application?

N/A

### Describe the Bug

`create-next-app` fails to initialize a new Next.js app with Node 10.x because Next.js depends on `image-size`, which requires Node 12.x. This contradicts the documentation which [says that Node 10.x is supported by Next.js](https://nextjs.org/learn/basics/create-nextjs-app/setup)

### Expected Behavior

The app files should be initialized

### To Reproduce

1. Ensure you have Node 10 (for example, `v10.24.1`)
2. Run `yarn create next-app --ts`

**Comment by mattcarlotta** [comment] 2021-06-23 13:41
The documentation is outdated. Next v11.0.1 requires [Node v12+](https://github.com/vercel/next.js/blob/canary/packages/next/package.json#L249-L251)

**Comment by huozhi** [comment] 2021-06-23 16:40
doc is updated by https://github.com/vercel/next.js/pull/26528

**Comment by ijjk** [comment] 2021-06-23 17:21
Closing per https://github.com/vercel/next.js/issues/26517#issuecomment-866994266

**Closed by ijjk** 2021-06-23 17:21 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
