### ISSUE TITLE
Jest.mock() not working at all

### ISSUE THREAD

**Issue by D-Pagey** [vercel/next.js#32982] opened 2022-01-04 14:54 UTC
### What version of Next.js are you using?

latest

### What version of Node.js are you using?

16.1.0

### What browser are you using?

n/a

### What operating system are you using?

macOS

### How are you deploying your application?

n/a

### Describe the Bug

I cloned https://github.com/vercel/next.js/tree/canary/examples/with-jest and simply added 

```
// index.tsx
import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import styles from "@/pages/index.module.css";

console.log({ axios });
```

```
index.test.tsx
import { render, screen } from "@testing-library/react";
import Home from "@/pages/index";

jest.mock("axios");

describe("Home", () => {
  it("renders a heading", () => {
    render(<Home />);

    const heading = screen.getByRole("heading", {
      name: /welcome to next\.js!/i,
    });

    expect(heading).toBeInTheDocument();
  });
});
```

### Expected Behavior

Expect the console log to log a mocked axios but instead returns actual axios

### To Reproduce

Add any `jest.mock` to anything in https://github.com/vercel/next.js/tree/canary/examples/with-jest

**Comment by etiennejcharles** [comment] 2022-01-04 19:01
Seems related to 
https://github.com/swc-project/jest/issues/14

**Comment by etiennejcharles** [comment] 2022-01-04 19:01
Having the same issue right now, not able to do the switch to swc parser at the moment (sadly)

**Comment by balazsorban44** [comment] 2022-01-05 00:13
This actually seems to be a duplicate of #32539

**Closed by balazsorban44** 2022-01-05 00:13 UTC
Labels: kind: bug, area: SWC transforms

**Comment by balazsorban44** [comment] 2022-02-04 01:24
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
