### ISSUE TITLE
Consistent scroll behavior between Router.push and Link

### ISSUE THREAD

**Issue by oyeanuj** [vercel/next.js#15206] opened 2020-07-15 23:37 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I noticed that when using `Link`, you can specify option to prevent scrolling to top but the same option seems missing when using `Router.push`: https://nextjs.org/docs/api-reference/next/router#routerpush

(Additionally, when using browser back buttons, the same scroll behavior happens)

## Describe the solution you'd like

A `scroll` option in the `router.push` method to specify whether page should be scrolled to the top or not. This would make the behavior in the method consistent as they are supposed to be parallel methods.

## Additional context

It seems like here in the code, there needs to be a check for `scroll`:

https://github.com/vercel/next.js/blob/23db226ea5721e5f4bc14e3b79efa03143e0657f/packages/next/next-server/lib/router/router.ts#L738-L740

---
Finally, thank you for all the work that y'all do, and thank you for creating this wonderful library!

**Comment by nfantone** [comment] 2020-08-26 03:53
Sharing a [possible workaround[(https://github.com/vercel/next.js/issues/3249#issuecomment-680532902) here as well for anyone stumbling upon this issue.

**Comment by Timer** [comment] 2020-12-30 02:00
Closing as duplicate of #3249

**Closed by Timer** 2020-12-30 02:00 UTC
Labels: kind: story, point: 3

**Comment by finnss** [comment] 2021-02-17 14:55
I disagree that this is a duplicate. #3249 is entirely focused on _stopping_ the scroll to the top. I am currently having the issue that `router.push` jumps my page to the top, which I'd like to _avoid_ in my use-case. 

I assume the behaviour was changed to always `reset(0, 0)` in [next@canary](https://github.com/vercel/next.js/issues/3249#issuecomment-752695480). 
I (and probably others) sometimes want to keep the scroll position after a `push`, and some sort of `scroll` option like we have with the `<Link>` component seems like the real solution @Timer.

If I'm mistaken and this already exists as an option, my bad! I couldn't find anything in the documentation or any existing issues.

**Comment by balazsorban44** [comment] 2022-01-28 17:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
