### ISSUE TITLE
Unable to override defaults for `modularizeImports`

### ISSUE THREAD

**Issue by rafaelalmeidatk** [vercel/next.js#52310] opened 2023-07-06 08:26 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC transpilation

### Link to the code that reproduces this issue or a replay of the bug

N/A

### To Reproduce

Trying to change or disable a rule in `modularizeImports` does not have any effect:
```js
const nextConfig = {
  modularizeImports: {
    "@ant-design/icons": {}, // or `null`
  },
};
```

### Describe the Bug

This issue is a shot in the dark given there's a comment saying this behavior is intentional here:

https://github.com/vercel/next.js/blob/cee0599628eed54111f855e652da2115e141e083/packages/next/src/server/config.ts#L692

So feel free to close this. But I wanted to raise a concern about this behavior because if any of these libraries in the list changes their bundling (or if the rule is just wrong, see #52307) then the only choice an user will have would be to either be locked in a previous version of Next.js or resort to patch the internals of Next.js until an update is released to fix the problem

This also ties the Next.js version to a specific version range of the target library in the case of bundle changes. If a library changes their bundle output and Next.js updates it, then you will be required to update the library if you want to update Next.js

### Expected Behavior

I should be able to override the defaults for `modularizeImports`. Maybe even introduce a loudy flag (e.g. `dangerouslySetInnerHTML`) to let the user know this is an escape hatch

**Comment by balazsorban44** [comment] 2023-07-11 08:26
Thanks, will close this as a duplicate of #52307, feel free to comment your concern on that issue! :pray:

**Closed by balazsorban44** 2023-07-11 08:26 UTC
Labels: template: bug
