### ISSUE TITLE
`next export` is not working with `app` directory

### ISSUE THREAD

**Issue by zeakd** [vercel/next.js#46111] opened 2023-02-19 10:15 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.14.0
      npm: 9.3.1
      Yarn: 1.22.19
      pnpm: 7.24.2
    Relevant packages:
      next: 13.1.7-canary.21
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

npx create-next-app

### To Reproduce

Hi. basic create-next-app setting raises this issue

1. 
<img width="603" alt="스크린샷 2023-02-19 오후 7 07 19" src="https://user-images.githubusercontent.com/10722657/219941707-58c0acb3-3492-468c-8c33-c217d249adca.png">

2. add script
``` json
"export": "next export",
```

3. and `npm run build && npm run export`

```
info  - Exporting (2/2)
PageNotFoundError: Cannot find module for page: /
    at Object.getPagePath (/Users/deokseong.kim/Works/Toss/playgrounds/next-app-dir/node_modules/next/dist/server/require.js:77:15)
    at /Users/deokseong.kim/Works/Toss/playgrounds/next-app-dir/node_modules/next/dist/export/index.js:384:48
    at Array.map (<anonymous>)
    at /Users/deokseong.kim/Works/Toss/playgrounds/next-app-dir/node_modules/next/dist/export/index.js:375:69
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/Users/deokseong.kim/Works/Toss/playgrounds/next-app-dir/node_modules/next/dist/trace/trace.js:79:20) {
  code: 'ENOENT'
}
```

### Describe the Bug

using app directory and `next export` is not working. 

### Expected Behavior

should be work with basic config.

**Comment by HummingMind** [comment] 2023-02-19 20:10
It's not supported yet. Check out the [App Directory Roadmap](https://beta.nextjs.org/docs/app-directory-roadmap).

**Comment by zeakd** [comment] 2023-02-20 06:23
Thanks. I'll leave it open. Please close it if it's being managed elsewhere.

**Comment by timneutkens** [comment] 2023-02-28 13:58
Going to close this as pointed out it's on the roadmap and not a bug.

**Closed by timneutkens** 2023-02-28 13:58 UTC
Labels: template: bug
