### ISSUE TITLE
Error: <Html> should not be imported outside of pages/_document.

### ISSUE THREAD

**Issue by ahmedyounes** [vercel/next.js#55804] opened 2023-09-22 08:32 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Apr 24 21:10:53 PDT 2023; root:xnu-8020.240.18.701.5~1/RELEASE_X86_64
    Binaries:
      Node: 20.7.0
      npm: 10.1.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.5.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which example does this report relate to?

npm run build

### What browser are you using? (if relevant)

chrome

### Describe the Bug

with next 13.5.2 
fresh installation then run build 
i have this error 

same with latest canary 13.5.3-canary.1
![Screen Shot 2023-09-22 at 11 28 30 AM](https://github.com/vercel/next.js/assets/28989583/f33d0c07-b694-45eb-9005-f00a5fd4be72)
![Screen Shot 2023-09-22 at 11 29 10 AM](https://github.com/vercel/next.js/assets/28989583/8988071d-72f4-437d-b0c6-db341f54e754)

after going back to 13.4.19
![Screen Shot 2023-09-22 at 11 31 58 AM](https://github.com/vercel/next.js/assets/28989583/e829fa28-590d-49fc-8e9e-516ce47f942e)

### Expected Behavior

no errors

### To Reproduce

npm run build

**Comment by roux1max** [comment] 2023-09-22 09:17
Same bug here! If I downgrade to 13.4.19 it works again but I oose the fix on server actions non opting out of static page generation...

## Versions

- `node`: 18.16.0
- `npm`: 9.5.1
- `next`: 13.5.2
- `eslint-config-next`: 13.5.2
- `react`: 18.2.0
- `react-dom`: 18.2.0
- `typescript`: 5.1.6

**Comment by roux1max** [comment] 2023-09-22 09:28
Ok, I just discovered that if I run my `build` command without `env-cmd` (I use it to change the env file loaded for build since `next build` loads automatically `.env.production`) it works!!!

I also had the message:
```shell
⚠ You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
```
That may be a starting point to look for this bug?

**Comment by ahmedyounes** [comment] 2023-09-24 12:05
Its not related to env , issue still exists with 13.5+
but thanks for the hint about env :)

**Comment by cameronk** [comment] 2023-09-24 13:51
I'm having this same issue on my side (version ^13.5.2) but interestingly it only occurs when running `next build` locally, and builds continue to run fine on Vercel. I'll try clearing some caches and see if that fixes things.

I'm also using Turborepo.

**Comment by Yovach** [comment] 2023-09-26 09:01
Hi, I'm encountering the same issue so I made some research and I finally found the solution for this problem. I made a reproduction available here https://github.com/Yovach/nextjs-app-router-document

I discovered some things : 
- The following command `next build` must have the `NODE_ENV` to `production` or it'll print ` ⚠ You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env`
- If a `next build` has `NODE_ENV` to `development`, it'll crashes with following errors:
1. Error: <Html> should not be imported outside of pages/_document.
2. TypeError: Cannot read properties of null (reading 'useContext')

**Comment by valleywood** [comment] 2023-09-26 09:16
> To fix this issue, you must be sure that your `NODE_ENV` is set to `development`.

You probably mean:
To fix this issue, you must be sure that your NODE_ENV is set to **production**.
🤔

**Comment by roux1max** [comment] 2023-09-26 09:19
@ahmedyounes seems I was on the right track ;)

**Comment by Yovach** [comment] 2023-09-26 09:19
> > To fix this issue, you must be sure that your `NODE_ENV` is set to `development`.
> 
> You probably mean: To fix this issue, you must be sure that your NODE_ENV is set to **production**. 🤔

Woops !! Sorry, fixed :)

**Comment by ahmedyounes** [comment] 2023-09-27 11:30
@roux1max thanks 👍 its weird but didn't though it would fix it .. 
@Yovach  thanks a lot ..

**Comment by ahmedyounes** [comment] 2023-09-27 19:36
```json
"scripts": {
 "dev": "NODE_ENV=development next dev",
    "build": "NODE_ENV=production next build",
}
```
as i suffered from other issues related to module not found

**Comment by balazsorban44** [comment] 2023-09-29 02:26
Closing as this seems to have been figured out. FWIW, setting `NODE_ENV` explicitly should not be needed in general. Since there was no reproduction attached, it's hard to tell what could have been an issue. Feel free to open a bug report (using the correct issue template).

**Closed by balazsorban44** 2023-09-29 02:26 UTC
Labels: area: examples

**Comment by Yovach** [comment] 2023-09-29 08:00
> Closing as this seems to have been figured out. FWIW, setting `NODE_ENV` explicitly should not be needed in general. Since there was no reproduction attached, it's hard to tell what could have been an issue. Feel free to open a bug report (using the correct issue template).

Hi, I update my reproduction https://github.com/Yovach/nextjs-app-router-document
The issue is that Next.js error is unclear.

In my example, it displays : 
```
Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
Error: <Html> should not be imported outside of pages/_document.
Read more: https://nextjs.org/docs/messages/no-document-import-in-page
```
and
`You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env`.

But if we don't look at the source code, we don't know that `NODE_ENV` to `development` isn't compatible with `next build`

**Comment by valleywood** [comment] 2023-09-29 08:10
It is also an issue if you run your Next.js solution in a Yarn workspace requirement.
To be able to locate files in projects outside the next project folder you need to have NODE_ENV set to development (which by the way is a valid NODE_ENV value and not "Non-standard" as the warning might indicate).

This means that you are not able to build Next projects with `yarn build` if it's inside a yarn workspace.

This was no issue prior to 13.5.X because then it worked perfectly running `yarn build` with NODE_ENV set to development so this is a new behavior introduced sometime after 13.4.0

**Comment by frixaco** [comment] 2023-09-29 08:29
> It is also an issue if you run your Next.js solution in a Yarn workspace requirement. To be able to locate files in projects outside the next project folder you need to have NODE_ENV set to development (which by the way is a valid NODE_ENV value and not "Non-standard" as the warning might indicate).
> 
> This means that you are not able to build Next projects with `yarn build` if it's inside a yarn workspace.
> 
> This was no issue prior to 13.5.X because then it worked perfectly running `yarn build` with NODE_ENV set to development so this is a new behavior introduced sometime after 13.4.0

Can confirm. This became issue after upgrading to 13.5.3. I had no issues with building in 13.5.2. I'm using SST to deploy our project to different environments including previews for PRs and deploying them started to fail, because we don't set NODE_ENV to production. It was working with no issues a day or two ago.

**Comment by frixaco** [comment] 2023-09-29 08:32
Related: https://github.com/vercel/next.js/issues/19046
