### ISSUE TITLE
[eslint] : Document Import in Page rules giving false error when using `src/pages/_document.js` directory structure

### ISSUE THREAD

**Issue by SimpleIndian** [vercel/next.js#29463] opened 2021-09-28 14:16 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

v14.17.6

### What browser are you using?

Brave

### What operating system are you using?

Windows

### How are you deploying your application?

next-start

### Describe the Bug

eslint giving false error when using a `src/pages/_document.js` structure instead of `pages/_document.js` structure which is valid based on this docs [src-directory](https://nextjs.org/docs/advanced-features/src-directory)

### Expected Behavior

Eslint should NOT give the error.

### To Reproduce

1.  Move your `pages`  directory to `src/pages`
2.  Create a `_document.js` file
3.  Add these line of 
 ```javscript
import Document, {Html, Main, NextScript } from 'next/document';

export default class MyDocument extends Document {
  render() {
    return (
      <Html>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
```
5. eslint should throw this error `next/document should not be imported outside of pages/_document.js. See https://nextjs.org/docs/messages/no-document-import-in-page.eslint(@next/next/no-document-import-in-page)`

**Comment by ijjk** [comment] 2021-09-28 14:28
Closing as a duplicate of https://github.com/vercel/next.js/issues/29021

**Closed by ijjk** 2021-09-28 14:28 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 16:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
