### ISSUE TITLE
Bootstrap with SCSS is no longer working after upgrading Next.js to version 12.

### ISSUE THREAD

**Issue by Nazakatalikharal** [vercel/next.js#31415] opened 2021-11-15 10:29 UTC
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

14.15.4

### What browser are you using?

chrome

### What operating system are you using?

window

### How are you deploying your application?

next start

### Describe the Bug

Module not found: Can't resolve '../node_modules/bootstrap/scss/forms/data:image/svg+xml,<svg xmlns='http:/www.w3.org/2000/svg' viewBox='0 0 16 16'><path fill='none' stroke=''

### Expected Behavior

project not running giving this error

### To Reproduce

in globals.scss  file i'm using  @import "~bootstrap/scss/bootstrap";

**Comment by timneutkens** [comment] 2021-11-15 13:01
This has been fixed on canary already 👍 You can try it using `npm install next@canary`.

**Closed by timneutkens** 2021-11-15 13:01 UTC
Labels: template: bug

**Comment by Nazakatalikharal** [comment] 2021-11-16 11:27
@timneutkens  it worked for me Thanks for quick response. 😃

**Comment by timneutkens** [comment] 2021-11-16 11:46
This is out on 12.0.4 now 🙏

**Comment by balazsorban44** [comment] 2022-01-27 09:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
