### ISSUE TITLE
next 12, swc, openapi-generator-cli doesn't work without .babelrc file 

### ISSUE THREAD

**Issue by nik0145** [vercel/next.js#31487] opened 2021-11-16 11:38 UTC
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

16.12.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

Without `.babelrc` file next doesn't work with openapi-generator.

```
module.exports = {
  presets: ['next/babel'],
};
```
I recreated the situation on codesandbox.
[codesandbox with error](https://codesandbox.io/s/next-with-openapi-without-babelrc-dcsvu)
[working codesandbox but swc is disabled](https://codesandbox.io/s/next-with-openapi-yf7c3)

### Expected Behavior

No errors and can call API successfully.

### To Reproduce

1. Install `@openapitools/openapi-generator-cli`
2. Try to call api from the auto generated file.

**Comment by timneutkens** [comment] 2021-11-16 11:47
Duplicate of #31300

**Comment by timneutkens** [comment] 2021-11-16 11:47
Duplicate of #31300

**Closed by timneutkens** 2021-11-16 11:47 UTC
Labels: template: bug

**Comment by nik0145** [comment] 2021-11-17 15:44
This is not Duplicate.
I know how to solve #31300, but because of this solution swc does not work.
But I will wait until they can answer his question.

**Comment by timneutkens** [comment] 2021-11-19 13:00
> This is not Duplicate.

It's literally the same issue about `@openapitools/openapi-generator-cli` not working with SWC 🤔

**Comment by nik0145** [comment] 2021-11-21 18:23
ok you're right sorry

**Comment by balazsorban44** [comment] 2022-01-27 07:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
