### ISSUE TITLE
Import/GraphQL error

### ISSUE THREAD

**Issue by ryanmalesic** [vercel/next.js#9272] opened 2019-10-31 18:36 UTC
# Examples bug report

## Example name

with-aws-amplify-typescript

## Describe the bug

GraphQL throws because adapter is undefined from config

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Start the dev server after initializing amplify

## Expected behavior

The app should run and fetch from Amplify

## System information

- OS: macOS
- Browser chrome
- Version of Next.js: 9.1.1

## Additional context

The imports from "aws-amplify" break it by trying to pull navigator into the server (it looks to be an issue with Analytics getting imported?). After fixing that issue by importing from "@aws-amplify/api" instead, the issue is that graphql  uses an adapter from config, but adapter is undefined on the server. It works on client. Seems to be change with aws but either way it doesnt work

**Comment by balazsorban44** [comment] 2021-12-24 01:03
The example has been updated multiple times since this was reported. I'm going to close this, feel free to ping me/re-open if you still think this is an issue.

**Closed by balazsorban44** 2021-12-24 01:03 UTC
Labels: good first issue

**Comment by balazsorban44** [comment] 2022-01-27 01:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
