### ISSUE TITLE
Middleware does not work for previously redirected pages

### ISSUE THREAD

**Issue by archisketch-thangly** [vercel/next.js#57587] opened 2023-10-27 11:26 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103
Binaries:
  Node: 18.16.0
  npm: 9.5.1
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 13.5.6
  eslint-config-next: 13.5.6
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A


warn  - Latest canary version not detected, detected: "13.5.6", newest: "14.0.1-canary.0".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which example does this report relate to?

middleware

### Describe the Bug

I'm trying to use middleware to check a user's account for activity and redirect to the login page.

### Expected Behavior

I would expect the middleware to re-fetch pages with the previous 307 status

### To Reproduce

middleware.ts
```typescript
import { NextRequest, NextResponse } from 'next/server';
import apiConstant from 'api/api-constants';

export async function middleware(req: NextRequest) {
  const token = req.cookies.get('token')?.value;
  const refresh_token = req.cookies.get('refresh_token')?.value;

  console.log(JSON.stringify({ token, refresh_token }));

  let login_url = `/login?redirect=${req.nextUrl.pathname}`;

  if (token && refresh_token) {
    const res = await fetch(apiConstant.me, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ token, refresh_token }),
    });

    const { error, error_code, data } = await res.json();

    console.log(error, error_code, data);

    if (error) {
      if (error_code) login_url += `&error_code=${error_code}`;
    } else return NextResponse.next();
  }
  return NextResponse.redirect(new URL(login_url, req.url));
}

export const config = {
  matcher: [
    '/change-email',
    '/dashboard/:path*',
    '/license/:path*',
    '/modeling/order/:path*',
    '/notification',
    '/upload-model/:path*',
    '/user/:path*',
    '/verify',
    '/withdraw',
  ],
};

``` 

1. Active account
2. Lock account
3. When I open the dropdown, the links to the pages are declared in the matcher and they are preloaded with status 307
4. When I go to any page in section 4, I am redirected to the login page
5. When I log in successfully, I cannot go to the pages in section 4 (at this point the account has been unlocked)

https://github.com/vercel/next.js/assets/105255382/0b00fdc0-1fe8-4d0b-a91b-1b9f781f5599

**Comment by archisketch-thangly** [comment] 2023-10-27 11:45
Specifically, previously redirected pages will always be redirected even if the redirect condition in the middleware is incorrect afterward.

**Comment by 7iomka** [comment] 2023-10-27 11:46
I think this issue is related with recent changes how middleware works with headers

Now is required to add `missing` prop.
Use the missing array in the Middleware config to only run the Middleware when the given headers are missing.

```ts
export const config = {
  matcher: [
    {
      /**
       * Match all request paths except for the ones starting with:
       * - api (API routes)
       * - _next/static (static generated files)
       * - _next/image (image optimization files)
       * - favicon.ico (favicon file)
       * - static (static files in public folder)
       */
      source: '/((?!api|_next/static|_next/image|static|favicon.ico).*)',
      missing: [
        { type: 'header', key: 'next-router-prefetch' },
        { type: 'header', key: 'purpose', value: 'prefetch' },
      ],
    },
  ],
};


```

I had links to private pages in my page template.
At the moment when I authorized and used the router to go to the private page (account) it turned out that prefetching was triggered as if before the actual moment of parsing cookies and on the logs I saw that in my midlvar redirect was triggered again to the login because of this.
Maybe this will help in your case too

**Comment by archisketch-thangly** [comment] 2023-10-27 11:50
@7iomka I tried adding missing but the problem still doesn't seem to be fixed, even though I tried to use prefetch for Link but this only prevents prefetching. Once I go to pages that use middleware and get redirected, it always redirects after that. 😭

**Comment by JesseKoldewijn** [comment] 2023-10-27 12:09
I've ran into issues like these as well both in pages and the app router myself. Must say, would like to see a fix for this 😅

**Comment by guptalife** [comment] 2023-10-27 13:16
Hi i can work on this issue please if someone can give me some context on which area it is related to and what steps i can take to solve this.

**Comment by archisketch-thangly** [comment] 2023-10-27 13:28
@guptalife Hi bro!

The way I use middleware in my project is as follows:
1. I use middleware to check if the login session has expired or if the user's account is active for a few specific pages.
2. If the login session expires or the account is inactive I will redirect the user to the login page.

And I have the following problem:
1. When I go to a page that needs to go through middleware and the user account is not active the user will be redirected to the login page.
2. After logging in again I redirect the user to the previous page, it seems that the middleware is not working at the moment and it probably remembers this page was redirected earlier and it always redirects when I try to go to that page.
_This problem should have disappeared when I reloaded the page._

**Comment by guptalife** [comment] 2023-10-27 23:08
@archisketch-thangly can you give me more code so that i can repro exact issue as i see there are some variables you are importing from other file. This should not be mandatory. I am asking if possible.

**Comment by archisketch-thangly** [comment] 2023-10-28 04:43
@guptalife `apiConstant.me` just is api url. I think there is no more middleware related code

**Comment by aziyatali** [comment] 2023-10-30 05:31
@archisketch-thangly  That issue probably associated with caching of the Nextjs 13. 
Can you please try to change your navigation Link where you are using with <Link prefetch={false}> which will ignore the caching?
If it fixes your problem, I can suggest a few work arounds as prefetch={false} too inefficient.

**Comment by archisketch-thangly** [comment] 2023-10-30 08:36
@aziyatali Thanks for your suggestion. But up to now all the methods I have tried cannot fix it. I have switched to checking auth in getSeverSideProps. It's quite inconvenient because I have to do it on every page. 😭

**Comment by aziyatali** [comment] 2023-10-30 08:44
@archisketch-thangly  I know that you need to to for every-page.  However, NextJs mentioned that there is nothing they can do but try some work-around.
You can refer to this [link](https://nextjs.org/docs/app/building-your-application/caching#opting-out-2).

**Comment by leerob** [comment] 2023-10-31 23:37
Please open a new issue with a reproduction and we can look into this. Thank you 🙏

**Closed by leerob** 2023-10-31 23:37 UTC
Labels: area: examples
