### ISSUE TITLE
[NEXT-438] Async head.js or metadata causes never ending loading state

### ISSUE THREAD

**Issue by dlehmhus** [vercel/next.js#45106] opened 2023-01-20 18:01 UTC
### Verify canary release

* [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
Binaries:
  Node: 16.18.1
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: 7.3.0
Relevant packages:
  next: 13.1.3
  eslint-config-next: 13.1.3
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Head component/file (next/head / head.js), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/dlehmhus/next-stuck-in-loading-state-example

### To Reproduce

1. `npm install`
2. `npm run dev`
3. 

[https://user-images.githubusercontent.com/27899554/213771506-bf6a5dfa-b663-4cef-bf12-f1d8f1001c4b.mov](https://user-images.githubusercontent.com/27899554/213771506-bf6a5dfa-b663-4cef-bf12-f1d8f1001c4b.mov)

### Describe the Bug

When the `header.js` is async and loads data [dynamically](https://beta.nextjs.org/docs/api-reference/file-conventions/head#data-fetching-and-dynamic-tags), the application gets stuck in loading state (as shown in the video above).

```
// src/app/[...slug]/head.tsx
async function loadHeadData(): Promise<{ title: string }> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({ title: "Dynamic title" });
    }, 1000);
  });
}

export default async function Head() {
  const data = await loadHeadData();
  return (
    <>
      <title>{data.title}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </>
  );
}
```

Clicking on the link a second time, or triggering any other change for that matter, "fixes" that issue.

### Expected Behavior

Once data has loaded, next.js should exit the loading state.

### Which browser are you using? (if relevant)

Chrome 109.0.5414.87

### How are you deploying your application? (if relevant)

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-438](https://linear.app/vercel/issue/NEXT-438/async-headjs-causes-never-ending-loading-state)</sub>

**Comment by Fredkiss3** [comment] 2023-01-20 23:13
Investigated the issue, and it seems that it is related to the location of `loading.tsx`, you have to move the file from `app/loading.tsx` to `[...slug]/loading.tsx`. 

In the docs, it is show `loading.tsx`  collocated where the page is : https://beta.nextjs.org/docs/routing/loading-ui#instant-loading-states

I think the assumption is that it is supposed to be collocated where the page is.

**Comment by dlehmhus** [comment] 2023-01-21 16:17
@Fredkiss3 thanks for taking the time to look into this. Moving the `loading.tsx` helps - but I noticed that when I keep the top level `loading.tsx` and just add a second one, the issue still persists. As far as I have understood it, you should be able to add as many Suspense boundaries aka `loading.tsx` files as you like, or am I wrong?

**Comment by Fredkiss3** [comment] 2023-01-21 17:51
You are right, but it seems that adding a suspense boundary if the page or layout isn’t an async component it hangs .

**Comment by AndyRae** [comment] 2023-01-22 12:54
I'm also having this issue - it might be a duplicate of #43972?

**Comment by azgskull** [comment] 2023-01-29 14:31
> > Next.js will wait for data fetching inside head.js to complete before streaming UI to the client. This guarantees the first part of a [streamed response](https://beta.nextjs.org/docs/data-fetching/streaming-and-suspense) includes  tags.

In my opinion, waiting for the header to load on the initial page is acceptable, but what I don't like is that it still happens when navigating between pages. If the header for a page is loaded asynchronously, the browser displays a loading icon, but Next.js does not show a loading state.

**Comment by karlhorky** [comment] 2023-01-30 12:46
Looks like `head.js` / `head.ts` is going away, in favor of new exports called `metadata` / `generateMetadata()`:

- https://github.com/vercel/next.js/discussions/41745#discussioncomment-4818481

**Comment by abstractvector** [comment] 2023-02-02 08:04
FWIW, I've just migrated my pre-production site from `head.tsx` to using the new `metadata` / `generateMetadata()` features and this problem still occurs.

It appears as though the behavior is if a route has been preloaded by the time you click on it, it loads almost instantly, but otherwise clicking on a link seems to hang indefinitely. Perhaps a race condition between resolving the promises in the metadata and body?

**Comment by huozhi** [comment] 2023-02-07 14:15
@abstractvector could you share the reproduction for metadata?

**Comment by abstractvector** [comment] 2023-02-07 14:40
> @abstractvector could you share the reproduction for metadata?

Absolutely. I think this issue may be a duplicate of #45418 and I've just left a comment there with an updated reproduction repository showing the same behavior: https://github.com/abstractvector/nextjs-issue-async-head/tree/metadata

**Comment by abstractvector** [comment] 2023-02-07 20:28
@huozhi just to clarify, the loading layer only appears once the `async generateMetadata()` promise resolves. My demo shows the `generateMetadata()` and component render functions taking the same amount of time so you never see the loading layer, but if the render takes longer then the user will briefly see the loading layer.

That erroneous behavior (loading layer not showing) is the subject of #45418 

Separately, I am also able to reproduce the behavior reported in this issue where the loading layer is left permanently on the screen. I can't work out exactly how to reproduce it, but I have seen it numerous times while clicking around after modifying my `generateMetadata()` function to return 1 second faster than the component render.

**Comment by huozhi** [comment] 2023-02-22 13:42
@dlehmhus can you try the `next@canary` it works for me now

**Comment by huozhi** [comment] 2023-02-22 13:43
@abstractvector so far it's expected that it's blocking while navigating, but we're also planning to patch the matdata separately to make navigation faster

**Closed** 2023-02-22 13:45 UTC
Labels: kind: bug, linear, investigate

**Comment by dlehmhus** [comment] 2023-02-22 14:00
@huozhi works as expected now! Thanks 👍
