### ISSUE TITLE
Next/image deploy at Firebase in static webpage

### ISSUE THREAD

**Issue by fjdevesa** [vercel/next.js#18507] opened 2020-10-29 22:42 UTC
# Bug report
New next/images not works when deploy to firebase. At local (npm run dev) works fine, any problem.
## Describe the bug
I get a 404 error and my images on production not works. I load from local (not use any layout as vercel or imgix).

I put all images at /public/img and in next.config.js try soo many path: 'XXXX' as default value path: '/_next/image',
and path:'/img/', path:'/_next/img/', etc etc,). Also move my img files to top of folder /public/ and don't use img folder.

Then try diferents values for src property: 
```
<Image src="/img/XXXX.jpg" width={350} height={200} />
<Image src="/XXXX.jpg" width={350} height={200} />
<Image src="/image/XXXX.jpg" width={350} height={200} />
<Image src="/_next/image/XXXX.jpg" width={350} height={200} />

```
## System information

- OS: [e.g. Windows]
- Browser (if applies) Chrome
- Version of Next.js: [e.g. 10.0.0]
- Version of Node.js: [e.g. v14.15.0.]

**Comment by dowrow** [comment] 2020-10-30 12:47
Same problem here.
Looks like the next/image component relies on an internal API that cannot work on a static site, so the site generated by running `next export` just won't serve those images. Am I right?

**Comment by FranciscoG** [comment] 2020-10-30 18:48
I just learned this the hard way now.  All my images disappeared on staging. I would have caught this if I had run `next export` locally and testing the build.  Now it makes sense why they wanted images to be in `/public` and not included using `require()`.  Feel like this is a big oversight to exclude support for SSG.

Maybe someone can convert the server-side [image optimizer](https://github.com/vercel/next.js/blob/master/packages/next/next-server/server/image-optimizer.ts) function into a plugin. Would probably also mean that a customized/altered version of their [`next/image`](https://github.com/vercel/next.js/blob/canary/packages/next/client/image.tsx) component as well

**Comment by dkodeit** [comment] 2020-10-31 23:41
Same issue with Netlify

**Comment by timneutkens** [comment] 2020-11-02 09:38
Duplicate of #18356

**Closed by timneutkens** 2020-11-02 09:38 UTC

**Comment by fjdevesa** [comment] 2020-11-03 14:59
Related with solution for Firebase: https://github.com/vercel/next.js/issues/18237

In few hours I will try and tells if works for me.

**Comment by dowrow** [comment] 2020-11-03 16:50
@fjdevesa I don't think #18237 is related to this issue.
However I'll try using next-optimized-images instead of next/image for the time being!

**Comment by fjdevesa** [comment] 2020-11-03 20:36
> @fjdevesa I don't think #18237 is related to this issue.
> However I'll try using next-optimized-images instead of next/image for the time being!

Confirmed issue #18237 not resolve my issue of images.

**Comment by FranciscoG** [comment] 2020-11-15 19:57
I've had to revert back to using [next-optimized-images](https://github.com/cyrilwanner/next-optimized-images) (2.x version with my own custom component) for my static site until this has been fixed.

**Comment by balazsorban44** [comment] 2022-01-29 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
