### ISSUE TITLE
`useSelectedLayoutSegment` returns names of route groups

### ISSUE THREAD

**Issue by typeofweb** [vercel/next.js#51677] opened 2023-06-22 22:00 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.4.8-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/wandering-hill-3f5rtr?file=%2Fapp%2F%28group%29%2Fsome-route%2Fpage.tsx

### To Reproduce

- use `useSelectedLayoutSegment` or `useSelectedLayoutSegments`
- have a route group

(or just visit the above codesandbox and navigate to `/some-route`: https://3f5rtr-3000.csb.app/some-route

### Describe the Bug

`useSelectedLayoutSegment()` returns `"(group)"`
`useSelectedLayoutSegments()` returns `["(group)", "some-route"]`

### Expected Behavior

`useSelectedLayoutSegment()` returns `"some-route"`
`useSelectedLayoutSegments()` returns `["some-route"]`

**Comment by ScreamZ** [comment] 2024-05-17 23:20
@leerob @ijjk @timneutkens Guys I guess this is a real issue and bug that need a fix. Almost one year ago that this has been opened :x

Current workaround : https://github.com/vercel/next.js/issues/59842#issuecomment-1961990016

**Comment by CTOverton** [comment] 2024-08-21 20:04
@typeofweb since it's been a year and this is unresolved, have you made a workaround?

**Comment by zvictor** [comment] 2024-10-06 05:36
This is by design and known to the project maintainers, as [clearly stated in the docs](https://nextjs.org/docs/app/api-reference/functions/use-selected-layout-segments):

> The returned segments include [Route Groups](https://nextjs.org/docs/app/building-your-application/routing/route-groups), which you might not want to be included in your UI. You can use the filter() array method to remove items that start with a bracket.

**Comment by timneutkens** [comment] 2024-10-31 11:28
`useSelectedLayoutSegments()` is intended to give you the full path to the unique "route" that you're currently on, which can be different than the url that you see (e.g. because of rewrites or parallel routes). It's indeed documented as per @zvictor's comment, not sure if that was documented when this issue was opened though.

Will close this issue as the behavior is expected.

**Closed by timneutkens** 2024-10-31 11:28 UTC
Labels: bug, area: app
