### ISSUE TITLE
Non public environment variables not visible in pipeline

### ISSUE THREAD

**Issue by danielpid** [vercel/next.js#17419] opened 2020-09-28 13:23 UTC
# Bug report

## Describe the bug

We have a project hosted in Azure DevOps that it's using Next.js
We use Azure DevOps to define the environment variables. The variables that don't start with NEXT_PUBLIC are not properly set.
If I do printenv from the pipeline I see the correct values.

## To Reproduce

1. Create a .env with the following values

- NEXT_PUBLIC_MY_VAR=default_public
- SUPER_SECRET=default_secret

2. In the Azure DevOps Library (where you define the environment variables) I create:

- NEXT_PUBLIC_MY_VAR=env_public
- SUPER_SECRET=env_secret
 
3. From the server-side of Next:
`console.log(process.env.NEXT_PUBLIC_MY_VAR)` // -> env_public
`console.log(process.env.SUPER_SECRET)` // -> default_secret

## Expected behavior

The variables that don't start with 'NEXT_PUBLIC_' are also correctly set using the environment variables.

`console.log(process.env.NEXT_PUBLIC_MY_VAR)` // -> env_public
`console.log(process.env.SUPER_SECRET)` // -> env_secret

## Additional context

As a workaround, we are creating a .env.production file from the pipeline to set from there the values.

**Comment by lfades** [comment] 2020-09-28 19:57
@danielpid It looks like you're only passing the variables at build-time, in which case variables that start with `NEXT_PUBLIC_` get replaced with their value, For example:

```js
console.log(process.env.NEXT_PUBLIC_MY_VAR)
console.log(process.env.SUPER_SECRET)
```

Becomes:

```js
console.log('env_public')
console.log(process.env.SUPER_SECRET)
```

`process.env.SUPER_SECRET` is a runtime environment variable, so you need to set it before running the app (at runtime), not only at build-time.

**Comment by danielpid** [comment] 2020-09-29 07:07
Hi @lfades, thanks for your quick response.

Understood! So, if I want this variable to be resolved at build time, I need to use a file .env.local, right?

**Comment by lfades** [comment] 2020-09-29 16:49
@danielpid You need to have `SUPER_SECRET` set at both build time and runtime.

I'm going to close this issue as this is not an issue with Next.js.

**Closed by lfades** 2020-09-29 16:49 UTC

**Comment by balazsorban44** [comment] 2022-01-29 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
