### ISSUE TITLE
Incorrect type definitions for Document component

### ISSUE THREAD

**Issue by DaniAkash** [vercel/next.js#32280] opened 2021-12-08 07:13 UTC
### What version of Next.js are you using?

12.0.5

### What version of Node.js are you using?

14.15.1

### What browser are you using?

NA

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

The type definitions for the `Document` component is incorrect & is leading to typescript lint failures

<img width="668" alt="Screenshot 2021-12-08 at 12 36 58 PM" src="https://user-images.githubusercontent.com/6841445/145164330-5e113606-19c7-4af9-9646-5e9604703427.png">

The types inside `node_modules` are loading from `node_modules/next/dist/shared/lib/runtime-config.d.ts`

<img width="501" alt="Screenshot 2021-12-08 at 12 37 18 PM" src="https://user-images.githubusercontent.com/6841445/145164092-45789707-3f06-4904-a915-f18e9e9e2bc1.png">

Previously they were loading from `node_modules/next/dist/pages/_document.d.ts`

<img width="470" alt="Screenshot 2021-12-08 at 12 40 33 PM" src="https://user-images.githubusercontent.com/6841445/145164560-6d8b1b80-9a8f-45a2-ae81-fe8472a17670.png">

### Expected Behavior

Types should be loaded from `node_modules/next/dist/pages/_document.d.ts`

### To Reproduce

Create a new Next.js Typescript project with Typescript version: ^4.1.3

**Comment by awareness481** [comment] 2021-12-08 07:23
It's been fixed on 12.0.6! https://github.com/vercel/next.js/issues/32110#issuecomment-986000874

**Closed** 2021-12-08 11:44 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
