### ISSUE TITLE
[typescript] `AppType` is not exported from `next` entry

### ISSUE THREAD

**Issue by JounQin** [vercel/next.js#17407] opened 2020-09-28 07:17 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I have to write like following now:

```ts
import type { AppType } from 'next/dist/next-server/lib/utils'
```

## Describe the solution you'd like

export `AppType` same as `NextPage` at https://github.com/vercel/next.js/blob/canary/packages/next/types/index.d.ts#L67-L73

```ts
import type { AppType } from 'next'
```

## Describe alternatives you've considered

It should be very easy, or

```ts
import type { AppType } from 'next/app'
```

## Additional context

N/A

**Comment by lfades** [comment] 2020-09-28 15:30
Closing as per my feedback in the PR: https://github.com/vercel/next.js/pull/17409#issuecomment-700088792

**Closed by lfades** 2020-09-28 15:30 UTC

**Comment by balazsorban44** [comment] 2022-01-29 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
