### ISSUE TITLE
package export error

### ISSUE THREAD

**Issue by pasicopan** [vercel/next.js#13665] opened 2020-06-02 13:01 UTC
# Bug report

## Describe the bug
I import this package (https://www.npmjs.com/package/url) which is the websocket-nats depend on, in my project

```
// project code
import url from 'url'
function click(){
    const a = url.parse('http://xxx.com')
    console.log('====', a.format)
}

export default () => <div>
    Welcome to next.js!
    <button onClick={click}>click</button>
</div>
```
when my next version is 9.0.0, after click, log is
```
a.format is function (){}
```

when my next version is higher then 9.0.0, eg. 9.4.4, after click, the log is
```
a.format is undefined
``` 

may be the webpack config in nextjs is not work correctly for some 'old package'

## Expected behavior

I need to get the behavior like nextjs 9.0.0 when I use 9.4.4

## Screenshots

<img width="715" alt="a" src="https://user-images.githubusercontent.com/1774918/83522801-c2d63000-a513-11ea-87dd-493d4c496f1d.png">
<img width="566" alt="b" src="https://user-images.githubusercontent.com/1774918/83522818-c8cc1100-a513-11ea-9c87-f62f02326d19.png">
<img width="1094" alt="c" src="https://user-images.githubusercontent.com/1774918/83522830-cc5f9800-a513-11ea-9132-26dbedf971cd.png">

## System information

- OS: macOS
- Browser chrome
- Version of Node.js: v13.1.0

**Comment by balazsorban44** [comment] 2020-06-02 16:09
What version of node are you using?

What is the exact functionality you are trying to achieve? Could you maybe use `useRouter` from `next/router` that already parses you a bunch of stuff? If you want to parse search params for example, you could try the [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/Urlsearchparams) API, that is supported by all modern browsers except IE11 by default.

**Comment by pasicopan** [comment] 2020-06-03 01:35
my mistake。。。node js version is 13.1.0. 
and I use this url package is because the https://www.npmjs.com/package/websocket-nats is depend on it.

**Comment by Timer** [comment] 2020-09-03 02:34
Closing as no reproduction provided.

**Closed by Timer** 2020-09-03 02:34 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
