### ISSUE TITLE
Next >=9.5.4: asPath without trailing slash

### ISSUE THREAD

**Issue by fostyfost** [vercel/next.js#17740] opened 2020-10-09 09:12 UTC
# Bug report

## Describe the bug

`asPath` on SSR without trailing slash.

## To Reproduce

1. Go to https://codesandbox.io/s/next-954-aspath-demo-qrsxp
2. Click on '/page' or '/page/'
3. See 'asPath is /page/'
4. Reload sandbox browser
5. See 'asPath is /page' (without trailing slash)

## Expected behavior

1. Go to https://codesandbox.io/s/next-953-aspath-demo-forked-mvl8t
2. Click on '/page' or '/page/'
3. See 'asPath is /page/'
4. Reload sandbox browser
5. See 'asPath is /page/' (with trailing slash)

**Comment by timneutkens** [comment] 2020-10-09 10:24
Duplicate of #16929

**Comment by fostyfost** [comment] 2020-10-09 10:31
@timneutkens hello. This issue is not duplicate of https://github.com/vercel/next.js/issues/16929. Because in issue https://github.com/vercel/next.js/issues/16929 author uses incorrect config parameter

**Comment by timneutkens** [comment] 2020-10-09 10:55
Changed it so that this one is kept open and the other is closed.

**Comment by lidoravitan** [comment] 2020-10-09 12:54
Can I help with it?

**Comment by fostyfost** [comment] 2020-10-09 14:28
> Can I help with it?

@lidoravitan  Yes, please, you can do it. I wanted to do this next Monday. But if you are planning to fix this bug, then I will wait for your decision.

**Comment by lidoravitan** [comment] 2020-10-10 12:22
I'd like to help with it. Can you give me some directions please? thanks a lot @fostyfost

**Comment by ludofischer** [comment] 2020-10-10 18:50
@lidoravitan Maybe start from https://github.com/vercel/next.js/blob/5cab03fef0782b4ecd7dbe4ec5bd10d10554650f/packages/next/next-server/server/render.tsx#L516
I think a debugger might also turn useful https://nextjs.org/docs/advanced-features/debugging

**Comment by lidoravitan** [comment] 2020-10-11 08:54
@ludofischer thanks i'll start with it now

**Comment by fostyfost** [comment] 2020-10-13 08:58
Same issue in version 9.5.5 
https://codesandbox.io/s/next-955-aspath-demo-d9ej7

**Comment by lidoravitan** [comment] 2020-10-14 10:15
status: 
It looks like the discrepancy started from this pull request #17121.
we need to investigate #17121 before I make any change to avoid any regression. 
any thoughts about that?
@fostyfost  @ludofischer @ijjk

**Comment by ludofischer** [comment] 2020-10-16 16:20
@lidoravitan I  am not a regular Next contributor, I know as little about the context of these changes as you. It looks like issues arise when trying to get consistent results across static pages, server side pages rendered on-the-fly and client-side hydration. You probably need to check that you don’t introduce a regression on #17113 and see what #17143 is about.

**Comment by lidoravitan** [comment] 2020-10-17 15:57
Thanks,@ludofischer. very important references, thanks a lot. because of the regression concern ,I asked for context.
before i'll try to go over that, @timneutkens do you have any thoughts?

**Comment by fostyfost** [comment] 2020-11-29 20:56
Next 10.0.3: i can still reproduce this bug.
https://codesandbox.io/s/next-1003-aspath-demo-d9ej7

Any updates on this issue?

**Comment by beelarr** [comment] 2021-01-19 15:47
I am seeing this discrepancy on the client vs. server when using the combination of `asPath` and `trailingSlash: true`.  `asPath` doesn't have the trailing slash on the server, but does on the client. 

I can get the correct 'path' getServerSideProps on the `context.req.url` property i.e. the trailing slash is present on the server.

**Comment by LetItRock** [comment] 2021-07-02 13:58
The issue doesn't exist in the 11th version, the [link to the codesandbox](https://codesandbox.io/s/next-954-aspath-demo-forked-n9459?file=/pages/page.js). 
@Timer @timneutkens should this ticket be closed?

**Comment by ijjk** [comment] 2021-09-21 04:16
Closing [per above](https://github.com/vercel/next.js/issues/17740#issuecomment-873019605) as this should be resolved in the latest version of Next.js `v11.1.2`

**Closed by ijjk** 2021-09-21 04:16 UTC
Labels: kind: bug, good first issue

**Comment by balazsorban44** [comment] 2022-01-27 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
