### ISSUE TITLE
[Bug] eval-source-maps are failing for dynamic routes and don't map properly

### ISSUE THREAD

**Issue by jasonwilliams** [vercel/next.js#15823] opened 2020-08-03 11:14 UTC
# Bug report
Sourcemaps are not being generated properly from next.js

## Describe the bug
Sourcemaps don't generate the correct `sources` path because it truncates dynamic paths (e.g [id])

## To Reproduce
1. Clone next.js and go to https://github.com/vercel/next.js/tree/master/examples/dynamic-routing (master branch or 9.5)
2. install dependencies, then run `yarn|npm run dev`
3. go to localhost and click "first post"
4. Now go into the `.next` folder, server -> pages -> post -> [id].js
5. Search for `/***/ "./pages/post/[id]/index.js":`
6. Select the base64 content and run `pbpaste | base64 -D` on the command line
6. inspect the JSON output.

```json
{"version":3,"sources":["webpack:///./pages/post//index.js?a773"]}
```
notice `id` has been truncated in the url.
This has broken debugging.

Now, still in the same folder (dynamic routing), change the next.js version in the package.json to 9.3.6
1. yarn install
2. yarn dev
3. same as before navigate to the first post
4. inspect `static/development/pages/post/[id].js.map`

```json
{"version":3,"file":"static/development/pages/post/[id].js","sources":["webpack:///webpack/bootstrap","webpack:///external \"next/dist/next-server/lib/router-context.js\""]}
```

You can see `file` is set correctly.

It looks like there was a change between `v9.3.6` and `v9.4.0` which switches to eval source maps and that doesn't support dynamic routes.
The only change i can see however is an [upgrade](https://github.com/vercel/next.js/pull/12355/files) of the source-maps package.

## Expected behaviour

Sourcemaps should have the proper dynamic routes on them so debugging can work

Related to: https://github.com/vercel/next.js/issues/14906
Regression from?: https://github.com/vercel/next.js/issues/8295

**Comment by timneutkens** [comment] 2020-08-03 11:40
Seems like a bug in the way that webpack handles those source paths (replaces `[id]` and probably `[name]` as well) 👍

**Comment by Javi** [comment] 2020-08-05 03:47
Want to chime in to add breakpoints work correctly on dynamic routes on v9.4.0, and start breaking on v9.4.1 and on. I've tried the latest version, and also Webpack 5 beta. So it does seem to be a regression of https://github.com/vercel/next.js/issues/8295

**Comment by jasonwilliams** [comment] 2020-08-12 09:09
> Seems like a bug in the way that webpack handles those source paths (replaces `[id]` and probably `[name]` as well) 👍

Ok interesting.
Is something you've raised upstream?

**Comment by timneutkens** [comment] 2020-08-12 09:36
> Is something you've raised upstream?

I haven't it's still something that can be investigated by contributors here.

**Comment by Javi** [comment] 2020-08-26 04:39
I may be a bit of a drag but being able to debug is critical to our process, so I can't upgrade to 9.5 until this is fixed or has a workaround, yet the docs don't support old versions and I'm starting to run into signs in them saying to upgrade, which is getting frustrating. Has this been raised upstream? I want to try my hand at it.

**Comment by jasonwilliams** [comment] 2020-09-10 19:09
@Javi i raised it here https://github.com/webpack/webpack/issues/11456 feel free to chase it up

**Comment by jasonwilliams** [comment] 2020-09-25 12:57
Hey @timneutkens 
I've attempted to reproduce this issue using just webpack and taking next out of the equation. It doesn't happen with webpack directly so I'm not sure if this is an upstream issue.

See here: https://github.com/webpack/webpack/issues/11456#issuecomment-698911033

**Comment by timneutkens** [comment] 2020-09-26 13:14
Given that Next.js configures webpack to create the sourcemaps and we don't have any custom plugins that change sourcemaps it's unlikely that it's an issue directly related to Next.js. Either way this still has to be looked into.

**Comment by tunesmith** [comment] 2020-10-06 03:01
It sounds like a webpack@5 fix is in progress, hopefully will be made to webpack@4 too. Are there any other workarounds other than putting `debugger:` everywhere?

**Comment by jasonwilliams** [comment] 2020-10-06 09:32
> It sounds like a webpack@5 fix is in progress

@tunesmith Do you have a link to this?

**Comment by Timer** [comment] 2021-01-04 21:13
Fixed by https://github.com/webpack/webpack/pull/11927

**Closed by Timer** 2021-01-04 21:13 UTC
Labels: kind: bug, priority: p2, type: upstream

**Comment by matt-koevort** [comment] 2021-03-09 07:13
Suggestions on how to use the fix in webpack@5?

Have followed the NextJS instructions to use webpack 5, but then sourcemaps no longer get uploaded to Sentry.

@jasonwilliams curious if you observed the same?

**Comment by jasonwilliams** [comment] 2021-03-09 09:07
@matt-koevort instructions from here? https://github.com/vercel/next.js/issues/21679#issuecomment-771941447 or from the website?

**Comment by balazsorban44** [comment] 2022-01-28 15:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
