### ISSUE TITLE
Custom 404 page doesnt work in produciton [SSG]

### ISSUE THREAD

**Issue by sebqq** [vercel/next.js#12505] opened 2020-05-05 06:31 UTC
# Bug report

## Describe the bug

Is it possible that custom 404 page doesn't work for SSG? It works fine in dev mode but in production it redirects me to original 404 page that comes from next.js

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create static landing page.
2. Create custom 404 page at `pages/404.tsx`.
3. In dev mode it works fine but in production build it doesn't.

## Expected behavior

I would like to see my custom 404 page :D

## System information

- OS: macOS, prod build is running on Debian server
- Version of Next.js: 9.3.6
- Version of Node.js: 12

Thanks!

**Comment by Vadorequest** [comment] 2020-05-05 07:38
I implemented this yesterday and it works fine here:

- Commit: https://github.com/UnlyEd/next-right-now/pull/42/commits/d57001cdd164e2c0e488dd6bac54ddbd3ac1ad4b
- PR: https://github.com/UnlyEd/next-right-now/pull/42

So, I guess the issue is related to your own codebase.

**Comment by timneutkens** [comment] 2020-05-06 09:11
Please add a complete reproduction? Also you didn't include where/how you're hosting the app.

**Comment by Timer** [comment] 2020-09-03 02:34
Closing as no reproduction provided.

**Closed by Timer** 2020-09-03 02:34 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
