### ISSUE TITLE
Hot reload not working at latest version of Next.js

### ISSUE THREAD

**Issue by jarvislin94** [vercel/next.js#51162] opened 2023-06-12 10:57 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.5-canary.12
      eslint-config-next: 13.4.5
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Link to the code that reproduces this issue or a replay of the bug

-

### To Reproduce

1.  npx create-next-app@latest (next-tw)
2. yarn install
3. yarn dev

 
 

### Describe the Bug

```
main-app.js:1425 Uncaught TypeError: __webpack_require__.ts is not a function
    at (app-client)/./node_modules/next/dist/compiled/@next/react-refresh-utils/dist/runtime.js
```

### Expected Behavior

Hot reload should work

**Comment by vikyw89** [comment] 2023-06-13 06:45
tried on "next": "^13.4.5" with typescript tailwind

hotreload doesn't work either

**Comment by kelvinsekx** [comment] 2023-06-18 09:50
I am facing the same problem with the next blog example template: `npx create-next-app --example blog my-blog`

Even when I downgrade my next version to 13.4.0v, it still doesn't work. I am using exactly what the template gave me without making any changes. 

So I can image the kind of frustrations others who might have used this must have faced.

Here is my package and folder tree
![Screenshot (68)](https://github.com/vercel/next.js/assets/51183064/a3a342af-d809-4c9d-9ff7-4133d31c266e)
![Screenshot (66)](https://github.com/vercel/next.js/assets/51183064/83ad68ed-f228-400b-9aa0-ea14e32dfb72)

**Comment by JasonA-work** [comment] 2023-06-21 23:51
@leerob 

Would you mind taking a look at this please? It's really killing dev productivity...(and is very frustrating since we've been spoiled with a super awesome HMR prior to this)

Would appreciate it so much!

**Comment by kelvinsekx** [comment] 2023-06-22 03:52
So I got a fix for mine. I think the hot reload works.
If you are working with wsl2, ensure you move your next folders/app to the home directory.

In fact, it has nothing to do with NextJs in my case. The next app was in the mnt/c folders was what made the HMR not work.

**Comment by JasonA-work** [comment] 2023-06-22 13:14
I'm glad you found a solution for yours.

I'm not using wsl2 but mine performs full reload for almost every change. Even file saves without any changes causes a full reload.

**Comment by s-fletcher** [comment] 2023-06-25 01:01
I was unable to reproduce using your steps. However, I am having this issue with my own project which started in `v13.3.0`. I was able to narrow it down to an issue around the [custom server](https://nextjs.org/docs/pages/building-your-application/configuring/custom-server). Removing this server resolved my issue.

Looks like custom servers also impact some other performance optimizations (see below from the [documentation](https://nextjs.org/docs/pages/building-your-application/configuring/custom-server)).

> **Good to know:**
> * Before deciding to use a custom server, please keep in mind that it should only be used when the integrated router of Next.js can't meet your app requirements. A custom server will remove important performance optimizations, like serverless functions and [Automatic Static Optimization](https://nextjs.org/docs/pages/building-your-application/rendering/automatic-static-optimization).
> * A custom server cannot be deployed on [Vercel](https://vercel.com/solutions/nextjs).

I'll be working on my own workaround without a custom server.

Hopefully this helps!

**Comment by kenbankspeng** [comment] 2023-06-26 05:27
I'm on next 13.4.7 and the only way I am able to see any changes is to perform a production build and then run npm start. Not only does hot reload not work for me, restarting the dev server on port 3000 does not pick up the new changes. 

Maybe I'm missing something, but it looks to me like npm start is serving my production build. Is that expected?

**Comment by eashish93** [comment] 2023-07-04 06:12
Yes custom server is the problem hot reload not working with latest next.js version. But it's a requirement as middleware doesn't support node runtime.

**Comment by jd-carroll** [comment] 2023-08-11 20:12
If anyone is using a custom server for https support only, take a look at #53926 

Looking for any kind of feedback

**Comment by meds** [comment] 2023-08-19 04:55
@weyert not working for me as of 13.4.19

**Comment by McAndersC** [comment] 2023-08-20 17:57
Testing not-found.js on a fresh build also just returns a blank page. Everything worked in 13.4.2 when I test it.

**Comment by McAndersC** [comment] 2023-08-24 14:11
4 days. Is it just me but the current npx create-next-app@latest is broken. It does not refresh on editing and a simple not-found leaves a blank page. Can someone please confirm that this is true. before i loose my marbles. 

This is straight out the box, no custom servers - no nothing?

**Comment by leerob** [comment] 2023-08-24 20:21
Could everyone please provide their environment info similar to the original issue? And what is the last version it is working for you?

**Comment by McAndersC** [comment] 2023-08-25 06:36
next-info: 
    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.13.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.16
      eslint-config-next: 13.4.16
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A

I have tried with @latest and 13.4.20-canary.4 version with the same result as described.

Latest working edition for me was 13.4.2.

**Comment by lazarevartur** [comment] 2023-08-25 09:48
Hey, guys. I also have this problem on the latest version. I switched to version 13.4.15 and that helped me.

**Comment by sandrinjoy** [comment] 2023-08-26 19:00
> Could everyone please provide their environment info similar to the original issue? And what is the last version it is working for you?

Hey, I think many people are facing this issue, because of the node version.
Like me, i was using node v16.3 in nvm as default. but nextjs docs says it needs atleast 16.4. Since i didn't get any errors during my setup, i forgot to change my node version. 
but then later i got this issue when is started to code. since i was using default setup from the docs itself, i immediately realised its the node issue. I switched to node 20 and its working very smoothly.

maybe as in the docs, if there is a way to check the node version during development, its better to throw an error/warning to update node version.

**Comment by ko-lem** [comment] 2023-08-29 08:01
Just like to chime in. I was on node `v16.13.1` and nextjs `13.4.19`

Problems:
- hot reload not working, like OP
- clicking links reloads the whole page
- annoying "ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time" in console

I just updated node version to `v18.17.1` and all those problems went away.

**Comment by Tommoore96** [comment] 2023-09-06 19:38
Doesn't matter what node version I'm on it still happens, I'm on the latest Next version too.

I think one thing that might be linked is parallel routes & route groups, I say that because when scouring for solutions I found a Youtuber mention the same problem when he was trying to fix a parallel route problem by adding route groups to it.

I'm in such a manic rush trying to get things done I don't have to to make a reproduction but I hope this helps.  If it doesn't help give me a nudge and I'll try and reproduce it next week.

Here's a clip from the aforementioned Youtuber:
https://youtube.com/clip/Ugkx37KNnn58pAcfnDyL4_AyVYzJeAk3Lzpr?si=8DihFvLcu6ORMCXd

**Comment by louisgv** [comment] 2023-10-06 18:57
I can confirm using route groups with different runtime per group (edge vs node) will break HMR. We have 3 groups, 1 using edge and 2 using node, and neither has HMR.

**Comment by pelachile** [comment] 2023-10-23 01:39
HMR still not working in Firefox 118.0.2 using Next 13.5.6 on MacOS 14.0

**Comment by jayantbh** [comment] 2023-10-24 11:12
Mine is a similar issue.
Everything works fine, except Hot Reload.

Tested with the following:

| Thing | Version |
|--------|--------|
| Chrome | 116 |
| MacOS | 13 |
| Node | `16.17.0` and `18.16.1` |
| Yarn | 1.22.19 |
| Next | `13.4.19` and `13.5.6` | 



<details>
<summary><strong><h3>Custom HTTP2 server / server.js code<h3></strong></summary>

```js
const next = require('next');

const fs = require('node:fs');
const h2 = require('node:http2');
const { parse } = require('node:url');
const dev = process.env.NODE_ENV !== 'production';
const httpsOptions = {
  key: fs.readFileSync('./local-certificates/localhost.key'),
  cert: fs.readFileSync('./local-certificates/localhost.crt')
};

const hostname = 'localhost';
const port = 3000;

// [A] I've tried it with and without `experimentalHttpsServer`
const app = next({ dev, hostname, port, experimentalHttpsServer: true });
const handle = app.getRequestHandler();

// [B] I've tried it with and without `app.getUpgradeHandler`
const upgradeHandler = app.getUpgradeHandler();

const server = h2.createSecureServer(httpsOptions);

app.prepare().then(() => {
  // Refer to comment [A]
  server.on('upgrade', upgradeHandler);

  server.on('error', (err) => {
    if (err) throw err;
  });
  server.on('request', (req, res) => {
    const parsedUrl = parse(req.url, true);
    handle(req, res, parsedUrl);
  });
  server.listen(3000, () =>
    console.info('> Server started on https://localhost:3000')
  );
});
```
</details>

### Errors I've encountered, which are probably related:

<details>
<summary><strong>Server side error</strong></summary>

```bash
 ⨯ uncaughtException: Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
    at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
```
</details>

<details>
<summary><strong>Browser side error</strong></summary>

```
WebSocket connection to 'wss://localhost:3000/_next/webpack-hmr' failed: 
init @ websocket.js:81
```
</details>

**Comment by patchitodev** [comment] 2023-10-24 19:12
HMR still not working in Google Chrome or Brave using Next 13.5.6 on Windows 11

**Comment by isimmons** [comment] 2023-10-25 02:44
Here's what's happening for me.

Windows 10
Chrome
next v 13.5.6
node v 18.12.0
fresh project created with npx create-next-app@latest

Shows compiled but no HMR.

Same on 13.5.5 but downgrading to 13.5.4 fixed it for me.

**Comment by patchitodev** [comment] 2023-10-25 17:38
> HMR still not working in Google Chrome or Brave using Next 13.5.6 on Windows 11

I just found out my problem was not due to the next.js version but a problem in my layout.tsx. 

The issue was in my layout.tsx file that was causing hydration / mounting issues because of a dom mismatch.

Here is the exact section from [documentation](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#root-layout-required)

> The root layout must define `<html>` and `<body>` tags since Next.js does not automatically create them.

Additionally, don't put any Wrapper Element outside body tag like this:

```
   <AuthProvider>
    <body>
          {children}
     </body>
   </AuthProvider>
```
but make sure that body tag always includes all components

    <body>
       <AuthProvider>
          {children}
      <AuthProvider>
    </body>

Hope it helps!

**Comment by sans-byte** [comment] 2023-11-05 17:08
For me updating the node version to the latest fixes the issue, before I was using node version 18.16.0 now it's 20.9.0

**Comment by showduhtung** [comment] 2023-11-09 12:52
I've been trying to swap node versions (v16.20.2, v20.9.0, v21.1.0) and none of them worked for me. 

```
   Operating System:
      Platform: Darwin
      Arch: arm64
      Version: Darwin Kernel Version 23.1.0:
    Binaries:
      Node: (v16.20.2, v20.9.0, v21.1.0)
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.5.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
```

**Comment by Skippou** [comment] 2023-11-13 12:31
Spent probably three hours trying to find my bug. HMR did not work. 
I have a pages directory and an app directory (Migrating from pages to app).
Deleted my metadata export, font and CSS on my app layout. 
Relaunch dev server.
Hard reload.

Boom it works! 

Now to pinpoint the problem.

**Comment by NunoGomes-dev** [comment] 2023-11-24 14:25
> Spent probably three hours trying to find my bug. HMR did not work. I have a pages directory and an app directory (Migrating from pages to app). Deleted my metadata export, font and CSS on my app layout. Relaunch the dev server. Hard reload.
> 
> Boom it works!
> 
> Now to pinpoint the problem.
> 
> Edit: It is not the metadata. Edit 2: Not the font. Guess it's a problem with globals CSS import? Edit 3: The CSS import in the layout.tsx causes changes in files to full-reload.
> 
> I have no fix.
> 
> Here is my repo: https://github.com/Skippou/next-dynamic-test/tree/HMRnotWorking
> 
> ```
>   Platform: win32
>   Arch: x64
>   Version: Windows 11 Pro
> Binaries:
>   Node: 20.9.0
>   npm: N/A
>   Yarn: N/A
>   pnpm: N/A
> Relevant Packages:
>   next: 14.0.4-canary.9
>   eslint-config-next: 14.0.2
>   react: 18.2.0
>   react-dom: 18.2.0
>   typescript: 5.2.2
> Next.js Config:
>   output: N/A
> ```
> 
> Edit 4: It works if I downgrade to NextJS 13.2 as suggested in: [#57046 (comment)](https://github.com/vercel/next.js/issues/57046#issue-1951896689)


@leerob Can u provide us more info on this?
I have the same issue. It seems that using both pages and app directory on Next v13.5.4 (tested in the next v14 and it happens as well) with some css/scss files imported on layout or at a client component with some context providers causes a full reload of the app after saving any change in the code.

Waiting for feedback/any fix on this.

**Comment by leonardorb** [comment] 2023-12-22 12:27
Not working for me. `node 20.10.0` & `next 14.0.4`. I can see the `[Fast Refresh] rebuilding` on the browser, but nothing happens.

<img width="472" alt="Screenshot 2023-12-22 at 7 19 14 AM" src="https://github.com/vercel/next.js/assets/37300/86d85313-0b20-4fd5-a9dd-3864d02ece96">

**Comment by pavelsavva** [comment] 2023-12-24 07:06
I had the same issue because I was accidentally exporting `async` component from a page with the `'use client';` directive. Everything started working after I removed the `async` keyword.

**Comment by leonardorb** [comment] 2023-12-26 00:01
> Not working for me. `node 20.10.0` & `next 14.0.4`. I can see the `[Fast Refresh] rebuilding` on the browser, but nothing happens.
> 
> <img alt="Screenshot 2023-12-22 at 7 19 14 AM" width="472" src="https://private-user-images.githubusercontent.com/37300/292486328-86d85313-0b20-4fd5-a9dd-3864d02ece96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NDg0OTUsIm5iZiI6MTcwMzU0ODE5NSwicGF0aCI6Ii8zNzMwMC8yOTI0ODYzMjgtODZkODUzMTMtMGIyMC00ZmQ1LWE5ZGQtMzg2NGQwMmVjZTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDIzNDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxN2QzY2Y3MGZmODdjNzg3YjRiZTIyMjU4MWY0MzkyN2I1Mjk3ZGMwZDk0NTM3N2U2YmVmMjFiZDU1YjdlMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Mo47LxVNiOXuz8M-7BQglUQdw3-A8jFAupMtF9vTzQ">

### Update:

Just found out that this issue is with TanStack components that are not re-rendering. Everything else works as expected. Really weird issue.

**Comment by logusgraphics** [comment] 2023-12-27 14:18
Not working for me. `Node 20.10.0 ` & `Next 14.0.4` for `.tsx` files only. (It also failed with Next 12 and 13) and React 17 and 18.
However changes to SCSS files for CSS modules refreshing normally. 
I even get the message on the browser `[Fast Refresh] done in 196ms`. But the DOM is never updated.
I'm using localized static generation (`output: export`) with `getStaticProps` and `getStaticPaths` as described in [this official guide](https://locize.com/blog/next-i18n-static/)

**Comment by shawnesquivel** [comment] 2024-01-03 00:06
Not working for me, I tried 
- using node versions 18 and 20
- downgrading to next `13.4.15`, `latest`, `13.2` as mentioned above

Anyone know a working combination of Node and NextJS that works?

**Comment by shawnesquivel** [comment] 2024-01-03 00:49
> Not working for me, I tried
> 
> * using node versions 18 and 20
> * downgrading to next `13.4.15`, `latest`, `13.2` as mentioned above
> 
> Anyone know a working combination of Node and NextJS that works?

fix that worked for me
- npm i -g create-next-app to use the latest installer
- npx create-next-app@13.4.5
- nvm use node 18

hot reload is working now

**Comment by logusgraphics** [comment] 2024-01-03 07:17
My issue was that I was invoking components as functions from my containers:
```
// header.container.tsx
const props = {...};
return Component(props)
```
When I switched to:
```
// header.container.tsx
const props = {...};
return <Component {...props} />
```
Then fast refresh was working as expected.

**Comment by arafays** [comment] 2024-01-03 18:19
I am using node v20.10.0 (latest LTS) at the time

I fixed it by removing `node_modules` , `.next` and `.netlify` folders
```
rm -rf node_modules .next .netlify
```

and then 
```
npm update --save
```

**Comment by devdomsos** [comment] 2024-01-19 18:19
Not sure why but I also have issue with hot reload. In the browser I see [Fast Refresh] rebuilding but dom is never updated. Any changes to the code require hard reload - basically not able to develop with such performance. 

`"next": "^14.0.4",`

```
"devDependencies": {
    "@types/bcrypt": "^5.0.2",
    "autoprefixer": "^10.4.16",
    "postcss": "^8.4.33",
    "tailwindcss": "^3.4.1"
  }
```

node 20.11

**Comment by Sanan4li** [comment] 2024-01-28 20:04
It's been more than 6 months and this issue is still open with no fix? Really strange. I thought next js is the future of react but I have to rethink about it. 
Facing the same issue and no idea why it says `[Fast Refresh] rebuilding` but doesn't work.

**Comment by Sumansourabh14** [comment] 2024-01-29 18:34
The following worked for me.

I had to create a `nodemon.json` file in my root directory with the following content:

```
{
  "verbose": true,
  "ignore": ["node_modules", ".next"],
  "watch": ["server/**/*", "index.js"],
  "ext": "js json"
}
```

After this, my Next.js app started reloading after any change made in the app.

Version: 

`"next": "14.1.0"`
`"node": "18.17.0"`

**Comment by Jero786** [comment] 2024-01-31 16:50
I fixed the problem of upgrading to version `14.1.0`. In my case then I was faced with the issue of `SyntaxError: Cannot use import statement outside a module`, but after I followed the instructions in [this message](https://github.com/ant-design/pro-components/issues/6525#issuecomment-1820853796), I was able to resolve the problem, and hot reload is working again! :D

**Comment by Sumansourabh14** [comment] 2024-02-03 06:46
Most likely the issue would be related to import or export statement. 

Correct casing of the import statements is very important, Notice the casing of letter "H" in the "heroSection".

`import HeroSection from "@/components/pageComponents/HeroSection";`

`import HeroSection from "@/components/pageComponents/heroSection";`

**Comment by ehsan18t** [comment] 2024-02-07 15:06
I am using `NextJS 14.1.0` and I face the same issue. However in my case,

```
import HeroSection from '@/components/sections/Hero';
import ServicesSection from '@/components/sections/Services';
```

> [!note]
> `Hot Reload` works with import like this.

<br>
<br>

```
import { HeroSection, ServicesSection } from '@/sections';
```
> [!warning]
> `Hot Reload` doesn't work for import like this.

**Comment by jd-carroll** [comment] 2024-02-08 18:35
For anyone coming across this issue, as someone who was very deep in the weeds on this issue and why it was happening, **the issue you are facing is almost certainly your code**.

The Next team previously had a set of proxies in place which were causing issues in a number of areas (especially if you were using your own custom server)

**Those proxies have been removed, thus resolving the (actual) original issue.**

@leerob @JackZong - Could one of you close this issue to make it clear?

**Comment by richardaum** [comment] 2024-02-12 14:21
In my case, it was because I had two non-component `exports` in a component file.

**Comment by selvakumardhivakar** [comment] 2024-02-21 04:32
I had the same issue, but updating layout file solved the issue.

wrapped the {children} in html and body tag
```
<html>
      <body>{children}</body>
</html>
```

**Comment by samivagyok-web** [comment] 2024-02-22 15:05
Today I have created a new app with `npx create-next-app@latest`, after going over #57066 to start the application, without changing anything of the generated code hot reload didn't work. But also if I reloaded the page nothing happened. Only after I restart the application. I chose to use the pages router and Tailwind in the installation process.

package.json

```
{
  "name": "leave_your_marq_web",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "react": "^18",
    "react-dom": "^18",
    "next": "14.1.0"
  },
  "devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "eslint": "^8",
    "eslint-config-next": "14.1.0"
  }
}
```

**Comment by matheusdamiao** [comment] 2024-02-22 21:22
@samivagyok-web I faced the same problem but with a 13.5.4 version.
It turns out it was a typo in one of my imports from a page, just like @Sumansourabh14 pointed out.
So, I'd suggest you to double check your imports.

**Comment by vitaminwater** [comment] 2024-03-05 04:09
Same here the project generated with `npx create-next-app@latest frontend` has its hot reload feature that only works when updating `globals.css` or `page.module.css`.
Trying to update any `.js` file will just output `Compiled in 13ms` in the console. But only once, a second change to any `.js` file will not trigger anything.

Using:
- Linux
- Node v19.9.0
- Next 14.1.2

**Comment by ahmafi** [comment] 2024-03-20 11:50
I have the same problem. It would be nice if the hot reloading script would throw more logs, so we knew why it's happening.

**Comment by Zn4rK** [comment] 2024-04-05 22:51
This also breaks HMR @ next.js <=14.1.4 and 14.2.0-canary.59:

```typescript
// app/page.tsx
"use client"; // Removing the use client directive activates HMR again.

export const runtime = "edge";

export default function Home() {
  return (<main>App</main>);
}
```

**Comment by postinternetsyndrome** [comment] 2024-04-14 09:46
This happened to me too. It was fixed by removing the metadata export in layout.tsx generated by the npx script, since that's a non-react component export, presumably.

```
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
```

**Comment by pete-willard** [comment] 2024-04-22 13:09
In my case I had multiple exports in one of the `/pages` files (an object with mock data). I noticed the full page reloads, did a bunch of googling and found this thread among others. At first I thought it was because of potentially buggy Turbopack but then a warning in the terminal gave me a clue and eventually led me to [the docs](https://nextjs.org/docs/messages/fast-refresh-reload#why-this-error-occurred).

**Comment by AustinShelby** [comment] 2024-04-24 14:46
For me this bug was caused by having `assetPrefix: "http://localhost:3000"` in my `next.config.js` and I fixed it by changing it to `assetPrefix: undefined`.

**Comment by WesleyKapow** [comment] 2024-04-25 12:25
For me I had server rendering errors `ReferenceError: document is not defined`. Setting the component that used that to `use client;` fixed the server side rendering error and fixed fast reload. So make sure you don't have any errors in your server logs!

**Comment by CassWindred** [comment] 2024-04-25 14:03
So I'm having the same problem and it's definitely a WSL2 thing - it works fine from Powershell but Powershell bad, I have copied the project into my WSL2 home dir so no symlinks and identical files.

I'm on the latest version of NextJS and Node, both instances function identically except that when run from WSL2 it seems not to watch or hot-reload any saved changes, requiring a full stop and restart every time. I guess I'll put up with having to use Powershell for now but would be great if there was a way to solve this. 

I started on NextJS 13.5 and Node 16 but have updated each thing independently and tested across both environments, as well as trying all the applicable solutions given in this thread, but HMR continues to fail - accessing pages for the first time after a reload always produces the log `Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload`. 

I'm pretty sure our code is not the issue here given that it works fine when run in Windows over WSL.

**Comment by robMolloy** [comment] 2024-05-01 11:11
I found a strange bug that seems related - hopefully this helps someone. 

I was importing components from `Flash.tsx`. I used the syntax `export * from "./flash";` (notice lowercase 'f' not 'F').

This didn't throw any errors and seemed to all be working fine other than the hot reload.

**Comment by edwinveldhuizen** [comment] 2024-05-23 11:45
It looks like this MR broke it when using assetPrefix:
https://github.com/vercel/next.js/pull/59471

**Comment by normdoow** [comment] 2024-06-01 22:06
HMR is failing for me even when starting out with a fresh next app.

`npx create-next-app@latest`

I haven't changed anything other than testing a text change to test HMR.

next: 14.2.3
node: 20.14.0
npm: 10.7.0

Have to restart the next server `npm run dev` to see any changes. What a drag!

**Comment by Oliver-Turp** [comment] 2024-06-03 17:22
This is happening to me too. It's not every time but it's enough of the time to make it really annoying and slow down my productivity!

next: 14.2.3
npm: 10.8.1
node: 20.11.1

I was coding on other projects 2 weeks ago and it was working fine. Took a weeks break then came back this week and it's not working...

**Comment by electricBonfire** [comment] 2024-06-03 20:56
> It looks like this MR broke it when using assetPrefix: #59471

I can confirm this is what is causing the issue on my end. If I comment out `assetPrefix` from `next.config.js` the hot reloading works.

When inspecting the network the websocket (/_next/webpack-hmr) never connects with `assetPrefix` in place.

**Comment by jessephelps** [comment] 2024-06-05 19:23
Same for me: assetPrefix breaks hot reload.

**Comment by MdSadiqMd** [comment] 2024-06-14 16:32
Just in case you are using `WSL2` then change your project path to `\home` directory that means if your project is present in path `/mnt/c/Users/your-username/your-project` change it to linux `\home` directory by creating a folder in it say `mkdir -p ~/projects` and then move a copy of your project linux file system by using command `mv /mnt/c/Users/your-username/your-project ~/projects/` then navigate to the project by `cd ~/projects/your-project` and open this instance in vs code by using command `code .` and run the code by `npm run dev`

This worked for me hope it worked for you too

**Comment by nsturdivant** [comment] 2024-06-18 13:40
I can confirm that, after either commenting out `assetPrefix` or setting `assetPrefix` to `undefined`, HMR starting working for me locally. For additional context, I came across this issue thread while troubleshooting HMR for a Sitecore XM Cloud head application.

Node: 20.14.0
npm: 10.7.0
Next.js: 14.1.0
Sitecore JSS: 22.0.0

Also worth a read: https://nextjs.org/docs/app/api-reference/next-config-js/assetPrefix.

**Comment by ThanhHung2112** [comment] 2024-06-21 03:50
For `WSL2`, some case you cd to path `home/UserName/win-home/Desktop ....` but the project stills working at `/mnt/c/...` path. Create the project at `/home/Username/PJ_folder/` will solve this.

**Comment by andrei9669** [comment] 2024-06-21 08:38
encountered same issue, setting assetPrefix to undefined in dev mode solved it

**Comment by SangNguyen2810** [comment] 2024-06-29 10:11
having the same issue, just have created a new project. However, my next.config.mjs does not have assetPrefix, it is blank.
Node: v22.0.0
npm: 10.5.1
next: 14.2.4

**Comment by devjiwonchoi** [comment] 2024-08-04 14:04
@jarvislin94 Could not find a valid reproduction, please reopen with repro if the issue is still ongoing, I'll prioritize and take a look. Thank you!

@andrei9669 @nsturdivant @ThanhHung2112 For those who are having issue with the `assetPrefix`, https://github.com/vercel/next.js/pull/67983 did the fix, so please try out the latest canary.

> [!note]  
> An assetPrefix set to a full URL e.g. CDN should be only used in Prod.
> x-ref: https://nextjs.org/docs/app/api-reference/next-config-js/assetPrefix

**Comment by devjiwonchoi** [comment] 2024-08-08 05:20
@ThanhHung2112 @MdSadiqMd @CassWindred @kelvinsekx
Just to confirm, all `WSL2` issue in this thread is about path difference right?
Is there anything I need to dig in on that related to Next.js?

**Comment by kelvinsekx** [comment] 2024-08-08 05:28
> @ThanhHung2112 @MdSadiqMd @CassWindred @kelvinsekx Just to confirm, all `WSL2` issue in this thread is about path difference right? Is there anything I need to dig in on that related to Next.js?

It has nothing to do with NextJS so don't dig it I would say.

If you are working with WSL2, work in your home directory. In fact, for other projects that isn't Next related, I encountered same experience, and switching paths did justice.

**Comment by MdSadiqMd** [comment] 2024-08-08 05:29
@devjiwonchoi Yes my comment specify to move the application to native path(WSL2) nothing more than that with respect to my comment

**Closed** 2024-08-08 06:34 UTC
Labels: bug

**Comment by jamesryan-dev** [comment] 2024-08-13 15:28
Same for me - upgrading from next 12 -> next 14.. Hot Reloading stopped working 

Commenting out `assetPrefix` line in my `next.config.js` fixes hot reloading..

**Comment by devjiwonchoi** [comment] 2024-08-13 16:19
@jamesryan-dev Hey, I'd really love to take a look at your case.
Have you set the CDN url (e.g. https://cdn.example.com) to your `assetPrefix`?
Or is it the `http://localhost:port`?

**Comment by jamesryan-dev** [comment] 2024-08-19 09:43
Hi @devjiwonchoi we are not using CDN

Here is our, now working config:

```
  // Set assetPrefix to our public URL
  // Checking for inDevelopment as '/' breaks Hot Module Reloading if used during development
  assetPrefix: inDevelopment ? undefined : '/',
```

**Comment by devjiwonchoi** [comment] 2024-08-19 11:10
@jamesryan-dev Hey, thanks for reporting. Your case, setting `assetPrefix` as '/' breaking HMR was a valid bug.
It was fixed at https://github.com/vercel/next.js/pull/68622 by this specific code:

https://github.com/vercel/next.js/blob/6266149474be91aca3e745a1a56333dd4d823bf9/packages/next/src/server/lib/router-server.ts#L670-L675

This fix was released to the canary version [v15.0.0-canary.109](https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.109), and will going to be added to the next available stable version. Once again, thank you for reporting your case!

**Comment by AmBha21** [comment] 2024-08-28 15:37
has anyone had issues with the Link tag not hot reloading?

**Comment by metclan** [comment] 2024-09-10 06:17
Actually mine wasn't working because i was using group routes in next js. 

So in one of the route layout, I didn't include the html and body element. 
**Before** 
<section>
 {children}
</section>

**After**
<html>
 <body>
  <section>
    {children}
  </section>
 </body>
</html>
