### ISSUE TITLE
_middleware multiple redirects

### ISSUE THREAD

**Issue by ChiefORZ** [vercel/next.js#32082] opened 2021-12-03 12:29 UTC
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome, Firefox, Cypress

### What operating system are you using?

macOS 11.5.2

### How are you deploying your application?

Heroku

### Describe the Bug

We switched over to using **_middleware** for our page protection and redirects.
Its perfect, API is easy to understand and works as intended!

For the most parts - i don't know if its a bug, or we miss something.
We have following pages:

```
.
├── src
│   ├── pages
│   │   ├── _middleware.ts
│   │   ├── auth
│   │   │   ├── forgotPassword.tsx
│   │   │   ├── login.tsx
│   │   │   ├── logout
│   │   │   │   ├── _middleware.ts
│   │   │   │   └── index.tsx
│   │   │   └── register.tsx
│   │   ├── index.tsx
│   │   └── my
│   │       ├── [bid]
│   │       │   └── index.tsx
│   │       └── _middleware.ts
```

the **pages/index.tsx** is the public landing page, but when you visit the page with a session cookie you will get redirected to **/my/0**.

```js
// pages/_middleware.ts
export const middleware = (request: NextRequest) => {
  if (request.url === '/' && request.cookies.session) {
    return NextResponse.redirect('/my/0');
  }
};
```

the **pages/my/[bid]/index.tsx** is the a private page, so visiting without a cookie will redirect you to the landing page **/**.

```js
// pages/my/[bid]/_middleware.ts
export const middleware = (request: NextRequest) => {
  // when no cookie - redirect to home
  if (!request.cookies.session) {
    return NextResponse.redirect('/');
  }
};

```

and the last part is the logout - where we would like to invalidate the session cookie and redirect to the landing page.

```js
// pages/auth/logout/_middleware.ts
export const middleware = () => {
  const redirect = NextResponse.redirect('/');
  redirect.cookie('session', 'delete', {
    expires: new Date(-1),
    httpOnly: true,
    maxAge: 0,
  });
  return redirect;
};
```

and the problem is, that the browser ends up making two redirects, but invalidates the cookie - so we end up with a completely messed up state:

```http://localhost:5000/auth/logout -> 302: http://localhost:5000/ -> 302: http://localhost:5000/my/0```

### Expected Behavior

the middleware should wait for the cookie to be updated - or somehow we need to wait for the cookie to be changed or invalidated.

```http://localhost:5000/auth/logout -> 302: http://localhost:5000/```

### To Reproduce

as described above

**Comment by ChiefORZ** [comment] 2021-12-03 15:33
The same happens with the **clearCookie** method...

```js
// pages/auth/logout/_middleware.ts
import { NextResponse } from 'next/server';

export const middleware = () => {
  const redirect = NextResponse.redirect('/');

  redirect.clearCookie('session');
  return redirect;
};

```

**Comment by javivelasco** [comment] 2021-12-15 13:08
I've tried reproducing this and I could not reproduce but I've identified an issue with the code you provided. In `/pages/_middleware.ts` you are checking if `request.url` equals `/` to condition the redirect. That's going to refer to the full URL so you should instead use `request.nextUrl.pathname === '/'` which is going to leave out the `basePath` and `i18n` as well in case you have some.

I tried repeatedly and I always get the right redirect. May you try updating the code or providing an example where we can reproduce the issue? Thanks!

**Comment by javivelasco** [comment] 2021-12-21 09:25
I'm closing this issue since the comment above seems to solve the issue and there is reproduction. If this is still an issue, please re-open with a reproduction case.

**Closed by javivelasco** 2021-12-21 09:25 UTC
Labels: template: bug, area: Middleware

**Comment by balazsorban44** [comment] 2022-01-27 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
