### ISSUE TITLE
Inconsistent error stack when editing the page

### ISSUE THREAD

**Issue by rafaelalmeidatk** [vercel/next.js#14138] opened 2020-06-12 18:20 UTC
# Bug report

## Describe the bug

When editing a component and receiving an error, the message has a super helpful hint saying where the error could be coming from: `Check the render method of "Home"`. This message doesn't appear when you access the page and it already has the error (when reloading it, for example)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `npx create-next-app a`
2. Edit `pages/index.js`, with these changes:
```diff
--- a/pages/index.js
+++ b/pages/index.js
@@ -1,4 +1,5 @@
 import Head from 'next/head'
+import { UndefinedThing } from 'react'
 
 export default function Home() {
   return (
@@ -13,6 +14,8 @@ export default function Home() {
           Welcome to <a href="https://nextjs.org">Next.js!</a>
         </h1>
 
+        <UndefinedThing />
+
         <p className="description">
           Get started by editing <code>pages/index.js</code>
         </p>
```
3. Start the server, go to http://localhost:3000
4. See this error:
```
Server Error
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```
5. Edit the file removing `UndefinedThing` from the JSX, save the file and the page will work normally
6. Now add `UndefinedThing` in the JSX again, save the file and this is the error:

```
Unhandled Runtime Error
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Home`.
```

## Expected behavior

`Check the render method of "X"` should be visible in server errors too

## Screenshots

![image](https://user-images.githubusercontent.com/11896398/84534117-beeaa080-acbf-11ea-84ce-93ef35cd19e6.png)

## System information

- Version of Next.js: 9.4.4
- Version of Node.js: 12.17.0

**Comment by Timer** [comment] 2020-06-17 19:56
I dug more into this and its the expected behavior due to limitations with React right now.

Follow #14284 for updates!

Duplicate of #14284

**Closed by Timer** 2020-06-17 19:56 UTC
Labels: kind: bug

**Comment by Gatesvert81** [comment] 2021-03-26 19:47
please what's the solution to fix the bug in my nextjs website

**Comment by balazsorban44** [comment] 2022-01-28 14:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
