### ISSUE TITLE
scroll to top after following a link with firefox

### ISSUE THREAD

**Issue by bpetitcollot** [vercel/next.js#12105] opened 2020-04-22 13:20 UTC
# Bug report

## Describe the bug

Using Firefox, when i click on a Link near to the bottom of a page, window doesn't scroll to the top of the page after it is loaded.

## To Reproduce

This bug can be reproduced on nextjs.org

1. Go to https://nextjs.org/learn/basics/create-nextjs-app/setup
2. Scroll to the bottom of the page
2. Click on 'Next >' blue button
4. Page 3 of the lesson appears but window doesn't scroll back to the top

## Expected behavior

Window should scroll to the top of the page

## Screenshots

Here is an mp4 screencast

[linkNext.zip](https://github.com/zeit/next.js/files/4516295/linkNext.zip)

## System information

Browser: Firefox

bug reproduced with
- Firefox 68.6.0esr / Debian 10
- Firefox 74.0.1 / Windows

it seems this bug doesn't occur with 
- Firefox 74.0.1 / Ubuntu 18.04

**Comment by loicbourg** [comment] 2020-05-20 11:52
Hello,

I reproduced this bug in my app with next.js 9.4.1 .


Is this an expected behavior ?

**Comment by loicbourg** [comment] 2020-08-24 14:15
Hello,

For information, i tried to enable the new experimental option *scrollRestoration* but it does not fix the bug.

**Comment by franky47** [comment] 2020-09-21 06:51
I have the same issue, on:

- Firefox 80.0.1
- macOS 10.14.6
- Next.js 9.5.3

Demo on my website:
- Go to <https://preview.francoisbest.com>
- Scroll to the end of the page
- Click "More albums"
- The browser navigates to `/music` using a Next link (the `scroll` prop is not passed explicitly, it uses the default value), and should scroll to the top.

Scrolling occurs on Chrome (with an animation) and on Safari the page loads already at the top, but Firefox gets stuck to the bottom of the page.

**Comment by mstruebing** [comment] 2020-12-01 10:37
This is the case if we use `scroll-behavior: smooth;` in our CSS.
If we remove it, it is working also in firefox.

**Comment by Timer** [comment] 2020-12-30 01:56
Closing as high likelihood duplicate of #6462, as I cannot reproduce.

**Closed by Timer** 2020-12-30 01:56 UTC
Labels: kind: bug, type: needs investigation

**Comment by alextseitlin** [comment] 2021-02-06 16:18
I have the issue on my end too. Works on chrome but not scrolling of firefox

**Comment by albert-hajdu-mondd-io** [comment] 2021-08-30 12:54
Thanks @mstruebing removing `scroll-behavior: smooth;` fixed the issue.

TBH smooth scrolling on navigation felt weird anyways (especially with page transitions) so I'm not missing it.

**Comment by 58bits** [comment] 2022-01-15 19:23
We actually use `scroll-behavior: smooth` for navigating to anchor-element fragments within a page, so turning it off would be a shame - at least for Firefox users.

**Comment by ketanrana1** [comment] 2022-01-25 13:12
> This is the case if we use `scroll-behavior: smooth;` in our CSS. If we remove it, it is working also in firefox.

It worked for me. Just set scroll-behavior: auto; .
