### ISSUE TITLE
[TurboPack] When using a custom PostCSS config, TurboPack fails to compile application on Windows

### ISSUE THREAD

**Issue by pixel-toys-chris-evans** [vercel/next.js#63755] opened 2024-03-27 10:37 UTC
### Link to the code that reproduces this issue

https://github.com/pixel-toys-chris-evans/browserslist-file-resolution-turbo-win32

### To Reproduce

1. Start the application using next dev with `--turbo` set on a Windows OS.
2. See the error raised in the next dev error overlay and console.

![](https://files.slack.com/files-pri/T178HAN2H-F06RXR1588Z/image.png)

```
> next dev --turbo
  ▲ Next.js 14.2.0-canary.44 (turbo)
  - Local:        http://localhost:3000
 ✓ Starting...
 ✓ Ready in 1681ms
css_asset: Vc { node: TaskCell(TaskId { id: 67444 }, CellId { type_id: ValueTypeId { id: 121, name: "turbopack-core@TODO::::virtual_source::VirtualSource" }, index: 0 }) }, query: ?{%22path%22:%22layout.tsx%22,%22import%22:%22Inter%22,%22arguments%22:[{%22subsets%22:[%22latin%22]}],%22variableName%22:%22inter%22}
 ○ Compiling / ...
 ✓ Compiled / in 1461ms
 ⨯ ModuleBuildError: ./app/page.module.css
Error evaluating Node.js code
Error: Failed to load external module D:\development\browserslist-file-resolution-turbo-win32/./postcss.config.js: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at externalImport (/turbopack/[turbopack]/shared-node/base-externals-utils.ts:16:11) [D:\development\browserslist-file-resolution-turbo-win32\.next\chunks\[output]__next_transform_ad1f0f.js:1336:15]
    [at process.processTicksAndRejections (node:internal/process/task_queues:95:5)]
    at async (postcss.config.js_.loader.mjs:3:13) [D:\development\browserslist-file-resolution-turbo-win32\.next\chunks\_0b8f1c._.js:11:13]
./app/globals.css
Error evaluating Node.js code
Error: Failed to load external module D:\development\browserslist-file-resolution-turbo-win32/./postcss.config.js: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at externalImport (/turbopack/[turbopack]/shared-node/base-externals-utils.ts:16:11) [D:\development\browserslist-file-resolution-turbo-win32\.next\chunks\[output]__next_transform_ad1f0f.js:1336:15]
    [at process.processTicksAndRejections (node:internal/process/task_queues:95:5)]
    at async (postcss.config.js_.loader.mjs:3:13) [D:\development\browserslist-file-resolution-turbo-win32\.next\chunks\_0b8f1c._.js:11:13]
    at processIssues (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\turbopack-utils.js:205:15)
    at handleRouteType (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\turbopack-utils.js:360:17)
    at async Object.ensurePage (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\hot-reloader-turbopack.js:622:17)
    at async DevBundlerService.ensurePage (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\dev-bundler-service.js:18:20)
    at async DevServer.ensurePage (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:551:9)
    at async Object.ensure (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:169:17)
    at async DevRouteMatcherManager.matchAll (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\future\route-matcher-managers\dev-route-matcher-manager.js:96:13)
    at async DevRouteMatcherManager.match (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\future\route-matcher-managers\default-route-matcher-manager.js:155:26)
    at async NextNodeServer.handleCatchallRenderRequest (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\next-server.js:228:31)
    at async DevServer.handleRequestImpl (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:807:17)
    at async D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\trace\trace.js:151:20)
    at async DevServer.handleRequest (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\start-server.js:141:13)
 ○ Compiling /_error ...
 ✓ Compiled /_error in 551ms
 GET / 500 in 2175ms
 ⨯ ModuleBuildError: ./app/page.module.css
Error evaluating Node.js code
Error: Failed to load external module D:\development\browserslist-file-resolution-turbo-win32/./postcss.config.js: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at externalImport (/turbopack/[turbopack]/shared-node/base-externals-utils.ts:16:11) [D:\development\browserslist-file-resolution-turbo-win32\.next\chunks\[output]__next_transform_ad1f0f.js:1336:15]
    [at process.processTicksAndRejections (node:internal/process/task_queues:95:5)]
    at async (postcss.config.js_.loader.mjs:3:13) [D:\development\browserslist-file-resolution-turbo-win32\.next\chunks\_0b8f1c._.js:11:13]
./app/globals.css
Error evaluating Node.js code
Error: Failed to load external module D:\development\browserslist-file-resolution-turbo-win32/./postcss.config.js: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at externalImport (/turbopack/[turbopack]/shared-node/base-externals-utils.ts:16:11) [D:\development\browserslist-file-resolution-turbo-win32\.next\chunks\[output]__next_transform_ad1f0f.js:1336:15]
    [at process.processTicksAndRejections (node:internal/process/task_queues:95:5)]
    at async (postcss.config.js_.loader.mjs:3:13) [D:\development\browserslist-file-resolution-turbo-win32\.next\chunks\_0b8f1c._.js:11:13]
    at processIssues (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\turbopack-utils.js:205:15)
    at handleRouteType (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\turbopack-utils.js:360:17)
    at async Object.ensurePage (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\hot-reloader-turbopack.js:622:17)
    at async DevBundlerService.ensurePage (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\dev-bundler-service.js:18:20)
    at async DevServer.ensurePage (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:551:9)
    at async Object.ensure (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:169:17)
    at async DevRouteMatcherManager.matchAll (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\future\route-matcher-managers\dev-route-matcher-manager.js:96:13)
    at async DevRouteMatcherManager.match (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\future\route-matcher-managers\default-route-matcher-manager.js:155:26)
    at async NextNodeServer.handleCatchallRenderRequest (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\next-server.js:228:31)
    at async DevServer.handleRequestImpl (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:807:17)
    at async D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\trace\trace.js:151:20)
    at async DevServer.handleRequest (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (D:\development\browserslist-file-resolution-turbo-win32\node_modules\.pnpm\next@14.2.0-canary.44_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\start-server.js:141:13)
 GET / 500 in 161ms
```

### Current vs. Expected behavior

Absolute paths within the built chunks are letter based which throws an error on Windows machines. This works fine for our MacOS based machines.

Windows NodeJS is expecting a `file://` absolute path.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32441
  Available CPU cores: 20
Binaries:
  Node: 20.11.1
  npm: N/A
  Yarn: N/A
  pnpm: 8.15.1
Relevant Packages:
  next: 14.2.0-canary.44 // Latest available version is detected (14.2.0-canary.44).
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

This is not currently in the latest release, and can only be found in the Canary release. We updated due to the compilation issues with Sanity.io builds using the `--turbo` flag in lts that are fixed in Canary.

<sub>[PACK-2880](https://linear.app/vercel/issue/PACK-2880/[turbopack]-when-using-a-custom-postcss-config-turbopack-fails-to)</sub>

**Comment by iojcde** [comment] 2024-03-29 00:09
For me renaming postcss.config.js to postcss.config.cjs fixed this issue.
https://github.com/vercel/next.js/issues/63359

**Comment by agilido** [comment] 2024-04-03 21:27
> For me renaming postcss.config.js to postcss.config.cjs fixed this issue. #63359

Thank you @iojcde ! 
Do you know why this fix is working?

**Comment by kachkaev** [comment] 2024-04-11 22:16
For those who are here from search: I have just bumped into the same issue after upgrading to Next.js 14.2.0 and adding `--turbo` to `next dev`. My `postcss.config.cjs`:

```js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
    "./my-custom-plugin.cjs": {},
  },
};
```

Output:

```
Error evaluating Node.js code
Error: Failed to load external module ./my-custom-plugin.cjs: Error: Cannot find module './my-custom-plugin.cjs'
Require stack:
- /path/to/project/.next/chunks/[output]__next_transform_d7cb3a.js
- /path/to/project/.next/transform.js
    at externalRequire (/turbopack/[turbopack]/shared-node/base-externals-utils.ts:38:11) [/path/to/project/.next/chunks/[output]__next_transform_d7cb3a.js:1361:15]
    (error resolving source map: Execution of FileContent::lines failed)
    [at <anonymous>]
    (error resolving source map)
```

Here is what worked for me:

```diff
 module.exports = {
   plugins: {
     tailwindcss: {},
     autoprefixer: {},
-    "./my-custom-plugin.cjs": {},
+    [`/${require("node:path").resolve(".")}/my-custom-plugin.cjs`]: {},
   },
 };
```

Oddly enough, using `__dirname` instead of `require("node:path").resolve(".") help because `__dirname` resolves to `[project]` 🤷

**Comment by bgw** [comment] 2024-04-12 18:52
It looks like this should be resolved by #64386.

Thanks for reporting this issue!

**Comment by timneutkens** [comment] 2024-04-16 19:06
This is still relevant for loading the postcss.config.js, it's fixed for next.config.js loading

**Closed** 2024-04-17 02:13 UTC
Labels: template: bug, area: Turbopack, linear: turbopack

**Comment by bgw** [comment] 2024-04-18 00:19
@pixel-toys-chris-evans I've confirmed that after updating your project to next.js 14.2.2, the issue no longer reproduces on Windows. Thanks again for submitting!
