### ISSUE TITLE
SASS :export does not work with built-in SASS support throwing 'Selector ":export" is not pure'

### ISSUE THREAD

**Issue by zorzysty** [vercel/next.js#11629] opened 2020-04-03 09:33 UTC
# Bug report

## Describe the bug

I use `:export` syntax to export variables from scss files and import them in JS. This worked great with next-sass, but does not even compile with the built-in SASS support.

## To Reproduce
in `Component.jsx`:
```
import colors from './component.module.scss'
```
`component.module.scss`:
```
:export {
  white: #ffffff;
  black: #000000;
}

```

## Expected behavior

`colors` in `Component.jsx` should be an object that looks something like this:
```
{
  white: "#ffffff",
  black: "#000000"
}
```
## Actual behavior
It does not compile the scss file and throws:
```
ModuleBuildError: Module build failed (from ./node_modules/next/node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(1:0) Selector ":export" is not pure (pure selectors must contain at least one local class or id)
```

## System information

- OS: Windows 10 (WSL)
- Version of Next.js: 9.3.4
- Version of SASS: 1.26.3

## Additional information
`next.config.js` does not contain any code related to CSS or SASS

**Comment by davidgolden** [comment] 2020-04-10 17:49
This is because the css modules mode enforced by next is "pure". This is related to #10584.

I've gotten around this issue until this is addressed by adding 

```
config.module.rules.forEach((rule) => {
            if (rule.oneOf) {
                rule.oneOf.forEach(rule => {
                    if (/module/.test(rule.test) && rule.use.loader !== 'error-loader') {
                        if (Array.isArray(rule.use)) {
                            rule.use.forEach(loader => {
                                if (/css-loader/.test(loader.loader) && loader.options.hasOwnProperty('modules')) {
                                    loader.options.modules.mode = 'local';
                                }
                            })
                        }
                    }
                })
            }
        });
```

That's not perfect code and could break if the css-loader config changes on next's side but it is a quick fix for now.

**Comment by nkalinov** [comment] 2020-04-27 10:31
Any updates here? Known workaround?

**Comment by bruqui** [comment] 2020-05-04 02:18
I also have a need for this as well as the ability to add includePaths.

**Comment by ebs-PriyankaKanwar** [comment] 2020-05-04 11:16
Hello Team
I have facing issues regarding the next-CSS . I have using next-CSS but they are giving me a warning and when I removed the next-CSS from next.config file. my style CSS has not loaded chunks in the production. and my CSS is out of order in a production build.
Can you plz help me.

**Comment by delicatesther** [comment] 2020-05-04 14:43
I'm reporting the same problem in Next.js 9.3.6, with Sass 1.23.7. Is anybody looking into this?

**Comment by nkalinov** [comment] 2020-05-04 14:51
The issue is that the built-in `css-loader` options are using by default "pure" CSS modules.
I managed to work around this issue by updating this option for the specific css modules files that we use in our project (.module.scss):
```
/**
 * Stolen from https://stackoverflow.com/questions/10776600/testing-for-equality-of-regular-expressions
 */
const regexEqual = (x, y) => {
  return (
    x instanceof RegExp &&
    y instanceof RegExp &&
    x.source === y.source &&
    x.global === y.global &&
    x.ignoreCase === y.ignoreCase &&
    x.multiline === y.multiline
  );
};

module.exports = {
  webpack: config => {
    const oneOf = config.module.rules.find(
      rule => typeof rule.oneOf === 'object'
    );

    if (oneOf) {
      const moduleSassRule = oneOf.oneOf.find(rule =>
        // rule.sideEffects === false &&
        regexEqual(rule.test, /\.module\.(scss|sass)$/)
      );

      if (moduleSassRule) {
        const cssLoader = moduleSassRule.use.find(({ loader }) =>
          loader.includes('css-loader')
        );
        if (cssLoader) {
          // Use the default CSS modules mode. Next.js use 'pure'. Not sure of all implications
          cssLoader.options.modules.mode = 'local';
        }
      }
    }

    return config;
  },
};
```

I'm not entirely sure of all the implications that this change might have...

**Comment by delicatesther** [comment] 2020-05-07 07:22
I've noticed that `:export` _does_ work if you don't use it in the same partial as the declared variables. So if I create a `variables.scss` and an `exports.scss` and `@use variables as *` in `export.scss`, it works. This is a bit tedious, especially when dealing with different exports (such as colours and breakpoints, for instance, because that means extra work nitpicking the required variables in your JS components. It does work, though!

**Comment by T04435** [comment] 2020-07-06 02:17
> I'm not entirely sure of all the implications that this change might have...

will allow you to have the styles go out of the module ie:

`a.module.css

li {
// Styles for li tags in component A
// which now will apply to all li tags in the app
}
`

@nkalinov Is there a way to extend this so it only applies to a folder ie: `/globals`

**Comment by vavra7** [comment] 2020-07-13 12:40
I am also looking for this functionality which is not working in Next.js. Please fix it!

**Comment by timneutkens** [comment] 2020-07-13 22:03
Feel free to fix it @vavra7

**Closed** 2020-09-09 23:29 UTC
Labels: good first issue, kind: story

**Comment by Timer** [comment] 2020-09-09 23:49
Fixed in `next@9.5.4-canary.8`.

**Comment by lipoolock** [comment] 2021-01-12 16:08
Hello @Timer 

I tried to use that feature (SCSS export) and I did not succeed
Here a codesanbox to help to understand what I tried https://codesandbox.io/s/ecstatic-bohr-70qc5?file=/pages/_app.js

Perhaps I'm wrong in the way I've done it ?
If not, do I have to open a new bug ?

Thanks for help

**Comment by BigglesZX** [comment] 2021-01-28 16:56
@lipoolock I had to rename my `variables.scss` to `variables.module.scss` for this feature to work (from a hint [here](https://github.com/Jam3/nextjs-boilerplate/pull/49#issue-466962277)). That was all!

**Comment by balazsorban44** [comment] 2022-01-28 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
