### ISSUE TITLE
Error occurred prerendering page "/404" when using concurrentFeatures: true

### ISSUE THREAD

**Issue by saurabhguptarock** [vercel/next.js#31126] opened 2021-11-08 05:39 UTC
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Cannot find module for page: /404
at node_modules/next/dist/export/index.js:493:19

> Build error occurred
Error: Export encountered errors on following paths: /404

### Expected Behavior

The page rendering should proceed without error.

### To Reproduce

Enable concurrentFeatures: true in next.config.js

**Comment by vitormv** [comment] 2021-11-09 09:27
This was already fixed in the canary: https://github.com/vercel/next.js/releases/tag/v12.0.4-canary.0

**Comment by huozhi** [comment] 2021-11-09 09:41
Thanks @vitormv!
@saurabhguptarock Should be covered in #31059. Can you try it again with `next@12.0.4-canary.0`. If it still doesn't get fixed please provide a minimal reproduction and reopen the issue. Close the issue for now.

**Closed by huozhi** 2021-11-09 09:41 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
