### ISSUE TITLE
Rewrite wildcard path not working for nested routes

### ISSUE THREAD

**Issue by keslert** [vercel/next.js#24288] opened 2021-04-20 23:21 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Using the following wildcard path matching doesn't match nested routes.
```
{
  source: "/@:username*",
  destination: "/u/:username*",
}
```
This works: `/@vercel`
This doesn't work: `/@vercel/settings`

If I change to the following:
```
{
  source: "/@/:username*",
  destination: "/u/:username*",
}
```
This works: `/@/vercel`
This works: `/@/vercel/settings`

### Expected Behavior

The wildcard path matching should work on nested routes.

### To Reproduce

```
// next.config.js
module.exports = {
  future: {
    webpack5: true,
  },
  async rewrites() {
    return [
      {
        source: "/@:username*",
        destination: "/u/:username*",
      },
    ]
  }
}
```

**Comment by kylemarshall18** [comment] 2021-04-21 02:29
@keslert I believe you have to use [regex pattern matching](https://nextjs.org/docs/api-reference/next.config.js/rewrites#regex-path-matching) to get the expected behaviour or as a work around:
```js
async rewrites() {
    return [
      {
        source: '/:username(@.*)',
        destination: '/u/:username',
      },
    ]
  },
```
This will match `/@vercel` & `/@vercel/settings` but not `/vercel` or `/vercel/settings`

**Comment by ijjk** [comment] 2021-04-28 01:25
Closing as the solution in https://github.com/vercel/next.js/issues/24288#issuecomment-823727821 is correct as using `:path*` with a leading character changes the behavior for non-regex matching.

**Closed by ijjk** 2021-04-28 01:25 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
