### ISSUE TITLE
/basePath redirects to root in NextJS 13 (appDir) 

### ISSUE THREAD

**Issue by cachho** [vercel/next.js#44893] opened 2023-01-15 11:31 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

sandbox@sse-sandbox-mugh8z:/sandbox$ npx --no-install next info

    Operating System:
      Platform: linux
      Arch: x64
      Version: #58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.1.3-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://codesandbox.io/s/appdir-basepath-redirect-to-root-mugh8z?file=/app/page.tsx

### To Reproduce

1. Create an app with appDir enabled
2. Set a basepath
3. Go to https://mugh8z.sse.codesandbox.io/docs in the built in browser
4. Try a link

### Describe the Bug

The basePath is ignored for routing, this goes for Link and useRouter. So all links redirect to root. 

This expands issue #41824, I just wanted to add a codesandbox example to show it's still happening, some people claim it has been solved in the latest releases, but it hasn't for me.

Thanks

### Expected Behavior

Link to basepath/dest

**Comment by ijjk** [comment] 2023-01-16 01:20
Closing as a duplicate of https://github.com/vercel/next.js/issues/41824

Note: adding reproductions to existing threads is also sufficient.

**Closed by ijjk** 2023-01-16 01:20 UTC
Labels: template: bug
