### ISSUE TITLE
Parent `loading` is not mounted when child's one is missing

### ISSUE THREAD

**Issue by lintellme99** [vercel/next.js#69089] opened 2024-08-20 09:53 UTC
### Link to the code that reproduces this issue

https://github.com/lintellme99/nextjs-loading-bug

### To Reproduce

1. type `npm ci`
2. type `npm run dev`
3. navigate to `/`
4. open the `browsers console`
5. click `Jokes list`
6. see `Root layout mounted` log in `console`
7. click `Go to joke 1`
8. no `Root layout mounted` log, even though, it's a `dynamic route` and it's `loading` shouldn't be prefetched by default (https://github.com/vercel/next.js/issues/62115#issuecomment-2030449972 @ztanner, am I right??)

Then you can delete the jokes `loading.tsx` and **more interesting things will appear**:
1. delete `/app/jokes/[id]/loading.tsx`
2. navigate to `/`
3. click `Jokes list`
4. see `Root layout mounted` log in `console`
5. click `Go to joke 1`
6. see `Root layout mounted` log in `console` (but it didn't actually mounted, the screen **doesn't show any loading state** and just **freezes**)
7. after 3 seconds of `jokes` `sleep` function — `/jokes/1` route appears

### Current vs. Expected behavior

**Expected:** As described here — [When the data is missing, and React "suspends", it will fallback to the nearest Suspense boundary](https://github.com/vercel/next.js/issues/62115)
**Current:** So in the first case, when we navigating to `/jokes/1` from the `/jokes` page — data is missing (because it's a `dynamic route` and also a `dev mode` and `prefetch` [doesn't preload it's data](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#2-prefetching)) and the `root loading.tsx` should be used as a fallback, — but it doesn't

**Expected:** The `root loading` should be shown up everywhere where it's need
**Current:** And in the second case, when we delete `/jokes/[id]/loading.tsx` — the `root loading.tsx` is mounted, but doesn't shown up

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:32:11 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T6030
  Available memory (MB): 18432
  Available CPU cores: 12
Binaries:
  Node: 20.7.0
  npm: 10.1.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.5
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Navigation, Upstream

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

**Comment by ztanner** [comment] 2024-08-20 18:43
> Current: So in the first case, when we navigating to /jokes/1 from the /jokes page — data is missing (because it's a dynamic route and also a dev mode and prefetch [doesn't preload it's data](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#2-prefetching)) and the root loading.tsx should be used as a fallback, — but it doesn't

When you go from `/jokes` to `/jokes/1`, the layout & loading boundaries associated with `/jokes` aren't unmounted. They'll remain in the React tree, while the page content associated with `/jokes/1` is added in. So you'll see this fallback state be triggered when navigating to `/jokes`. And when navigating to `/jokes/1`, the `app/jokes/[id]/loading.js` component is used while the data is loading. React won't re-trigger any existing Suspense boundaries that already had their fallback shown unless the whole subtree was remounted.

> Current: And in the second case, when we delete /jokes/[id]/loading.tsx — the root loading.tsx is mounted, but doesn't shown up

Same answer as above, but I'll re-state for clarity: React won't re-trigger any existing Suspense boundaries that already had their fallback shown unless the whole subtree was remounted. The fallback is originally shown when going to the `/jokes` page.  If you wanted it to be shown again, you can either use the nested loading segment as you have in the first example, or add a React key to the element that surrounds `children` in `/app/jokes/layout` that remounts the entire subtree when joke params change. 

Closing this as I believe this by design, but feel free to open a [discussion](https://github.com/vercel/next.js/discussions) rather than an issue if you'd like to discuss it further!

**Closed by ztanner** 2024-08-20 18:43 UTC
Labels: Upstream, bug, Navigation
