### ISSUE TITLE
Webpack 5 throws DeprecationWarning

### ISSUE THREAD

**Issue by jensmeindertsma** [vercel/next.js#15576] opened 2020-07-28 13:33 UTC
# Bug report

## Describe the bug
Using Webpack 5 with the official support shipped in Next.js 9.5, Webpack throws a few DeprecationWarnings when I run my app:
```
[DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
[DEP_WEBPACK_MAIN_TEMPLATE_RENDER_MANIFEST] DeprecationWarning: MainTemplate.hooks.renderManifest is deprecated (use Compilation.hooks.renderManifest instead)
[DEP_WEBPACK_CHUNK_TEMPLATE_RENDER_MANIFEST] DeprecationWarning: ChunkTemplate.hooks.renderManifest is deprecated (use Compilation.hooks.renderManifest instead)
[DEP_WEBPACK_MAIN_TEMPLATE_HASH_FOR_CHUNK] DeprecationWarning: MainTemplate.hooks.hashForChunk is deprecated (use JavascriptModulesPlugin.getCompilationHooks().chunkHash instead)
[DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
[DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'reduce' is deprecated)
[DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_LENGTH] DeprecationWarning: chunk.files was changed from Array to Set (using Array property 'length' is deprecated)
[DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_INDEXER] DeprecationWarning: chunk.files was changed from Array to Set (indexing Array is deprecated)
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
[DEP_WEBPACK_MODULE_ID] DeprecationWarning: Module.id: Use new ChunkGraph API
[DEP_WEBPACK_MODULE_UPDATE_HASH] DeprecationWarning: Module.updateHash: Use new ChunkGraph API
[DEP_WEBPACK_CHUNK_MODULES_ITERABLE] DeprecationWarning: Chunk.modulesIterable: Use new ChunkGraph API
[DEP_WEBPACK_CHUNK_GROUP_GET_MODULE_INDEX_2] DeprecationWarning: ChunkGroup.getModuleIndex2 was renamed to getModulePostOrderIndex
[DEP_WEBPACK_EXTERNALS_FUNCTION_PARAMETERS] DeprecationWarning: The externals-function should be defined like ({context, request}, cb) => { ... }
```
However, the app still runs fine. I just think these should be fixed/hidden.
## To Reproduce
Clone the `development` branch of [this repository](https://github.com/jensmeindertsma/jensmeindertsma.com/tree/development). These warnings appear in development mode and at build time, I also deployed to Vercel where they showed up as well.

## Expected behavior
I would expect there to be no warnings thrown.

## System information

- OS: Windows
- Browser: Chrome
- Version of Next.js: 9.5.0
- Version of Node.js: v12.16.3

## Additional context
I tried updating to 9.5.1-canary.0, but now the app won't run. I'll open another issue about this.

**Comment by timneutkens** [comment] 2020-07-28 13:34
Duplicate of #13341, this is expected as per the todo list.

**Closed by timneutkens** 2020-07-28 13:34 UTC

**Comment by jensmeindertsma** [comment] 2020-07-28 13:36
Sorry, did not look carefully enough to find that one!

**Comment by timneutkens** [comment] 2020-07-28 13:37
No worries!

**Comment by stefaneidelloth** [comment] 2021-03-25 11:21
For me the solution was to update "mini-css-extract-plugin" to version "1.3.9"

**Comment by Igli7** [comment] 2021-04-05 14:24
if you're using yarn 

Run:
yarn upgrade-interactive --latest

and select all the ones in red, select them with the spacebar and navigate through them with up and down arrow keys. 

Hope this helps someone

**Comment by joeczucha** [comment] 2021-06-07 18:55
For me it was to upgrade `clean-webpack-plugin` to 4.0.0-alpha.0

**Comment by hmodykhrtoto** [comment] 2021-11-13 00:10
#config/webpack/development.js


const environment = require('./environment')
const customConfig = {
    resolve: {
      fallback: {
        dgram: false,
        fs: false,
        net: false,
        tls: false,
        child_process: false
      }
    }
  };
  
  environment.config.delete('node.dgram')
  environment.config.delete('node.fs')
  environment.config.delete('node.net')
  environment.config.delete('node.tls')
  environment.config.delete('node.child_process')
  
  environment.config.merge(customConfig);

**Comment by balazsorban44** [comment] 2022-01-27 09:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
