### ISSUE TITLE
Can only build locally, with no changes to file

### ISSUE THREAD

**Issue by igorasilveira** [vercel/next.js#29221] opened 2021-09-19 19:21 UTC
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

12.0.0

### What browser are you using?

Safari, Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

I am trying to make a build on Vercel of some changes I made to my website. However, for some reason now, it will not build on Vercel. Only locally.

The file in question is the **Layout.tsx** file, which I've seen has given many people trouble in the past. But I have confirmed all file and component namings and they are correct. I've made several deploys before with the exact same **Layout.tsx** file and had no issues.

### **Local Build**
<img width="820" alt="Screenshot 2021-09-19 at 20 19 02" src="https://user-images.githubusercontent.com/22747386/133940129-73fe7a86-4e2d-4735-919f-000e21022d78.png">

### **Vercel Build**
<img width="1143" alt="Screenshot 2021-09-19 at 20 16 18" src="https://user-images.githubusercontent.com/22747386/133940140-ab5c0805-cca1-42c5-844c-912e57c2174f.png">

### **My file tree and index.tsx file**
<img width="1259" alt="Screenshot 2021-09-19 at 20 20 01" src="https://user-images.githubusercontent.com/22747386/133940170-74e3eba2-a6f8-435d-9bdf-ebcd2e1dbe8f.png">

### Expected Behavior

Vercel Build should have the same behaviour as local build, which is successful.

### To Reproduce

<img width="1259" alt="Screenshot 2021-09-19 at 20 20 01" src="https://user-images.githubusercontent.com/22747386/133940185-64a7eb70-32c6-433f-a598-e5f4166d4141.png">

**Comment by ijjk** [comment] 2021-09-19 19:29
Hi, this looks like a duplicate of https://github.com/vercel/next.js/discussions/27372#discussioncomment-1033766 so I'm gonna close this, feel free to respond with additional info you have trouble fixing the casing issue.

**Closed by ijjk** 2021-09-19 19:29 UTC
Labels: template: bug

**Comment by igorasilveira** [comment] 2021-09-19 19:43
> Hi, this looks like a duplicate of [#27372 (comment)](https://github.com/vercel/next.js/discussions/27372#discussioncomment-1033766) so I'm gonna close this, feel free to respond with additional info you have trouble fixing the casing issue.

Thank you! That was it 🙏

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
