### ISSUE TITLE
Create Next App blank page on IE11 running next dev

### ISSUE THREAD

**Issue by larswittenberg** [vercel/next.js#22946] opened 2021-03-10 14:28 UTC
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

14.15.4

### What browser are you using?

IE11 on Windows 10

### What operating system are you using?

macOS for development

### How are you deploying your application?

next dev

### Describe the Bug

Blank page in IE 11 with syntax error on `next dev`.

### Expected Behavior

The normal page view as in a current browser.

### To Reproduce

I used the Create Next app. No other dependencies. No code changes. 

Blank page in IE 11 with syntax error on `next dev`. See screenshot 01.png

At least with `next build && next start` I don't get an error message. See screenshot 01.png.
Only the layout bug that was already described in issue #21324.

![01](https://user-images.githubusercontent.com/1742089/110643890-d7d3a400-81b4-11eb-91d5-664617173d27.png)
Screenshot 01 after run `next dev`

![02](https://user-images.githubusercontent.com/1742089/110643900-d99d6780-81b4-11eb-95a3-d7740061e757.png)
Screenshot 02 after run `next build && next start`

**Comment by omegadeep10** [comment] 2021-03-29 16:54
Same issue. I can reproduce by `npx create-next-app` and then `npm run dev'. Loading in IE 11 will return a blank page and an error in console.

Downgrading to version 10.0.5 works for me (temporary solution). 10.0.6 and any version after are broken in IE 11 as far as I can tell.

**Comment by fernandojbf** [comment] 2021-04-13 18:54
Hey, having a quick look it seems to be `node_modules/next/dist/build/webpack/loaders/next-style-loader/runtime/injectStylesIntoStyleTag.js` that is not prepared to IE11. 

I've just transpiled using babel that file and start working.

This was just a quick test but is the loaders file that are causing the issues.

**Comment by timneutkens** [comment] 2021-04-14 08:34
Duplicate of #22270

**Closed by timneutkens** 2021-04-14 08:34 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
