### ISSUE TITLE
[i18n] Optional catch-all route masks more specific routes on client side

### ISSUE THREAD

**Issue by herrstucki** [vercel/next.js#19950] opened 2020-12-08 09:12 UTC
# Bug report

## Describe the bug

When i18n is configured, an optional catch-all route will mask a more specific route, but on client-side navigation only.

```
pages/
  blog/
    [id].tsx
  [[...slug]].tsx
```

In this case, the `[[...slug]]` route will render when using a `<Link href="/blog/1">`.

When i18n is disabled, this works correctly.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://codesandbox.io/s/youthful-https-bo1dp
2. Click on the link to /blog/1
3. The page will show the catch-all route (i.e. `Slug is ["blog", "1"]`) instead of the more specific blog route
4. Reload page or go directly to https://bo1dp.sse.codesandbox.io/blog/1
5. Blog route will be rendered correctly.

## Expected behavior

The behavior should be the same, regardless of i18n being enabled or not.

## System information

- Version of Next.js: 10.0.3, 10.0.4-canary.2
- Version of Node.js: 14
- Deployment: next dev

**Comment by herrstucki** [comment] 2020-12-08 09:13
Maybe related to #19934

**Comment by ijjk** [comment] 2021-01-01 04:44
Hi, this appears to be fixed in the latest version of Next.js `v10.0.5-canary.6`, please update and give it a try!

**Closed by ijjk** 2021-01-01 04:44 UTC
Labels: kind: bug, point: 1

**Comment by herrstucki** [comment] 2021-01-04 16:39
@ijjk I can confirm that it's fixed in 10.0.5-canary.9 https://codesandbox.io/s/practical-cohen-kjtbn

Thanks!

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
