### ISSUE TITLE
next/image is not working 

### ISSUE THREAD

**Issue by aditya305** [vercel/next.js#27578] opened 2021-07-29 04:19 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

7.20.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

CSS is not working for Next Image 

### Expected Behavior

CSS is not working for Next Image 

### To Reproduce

CSS is not working for Next Image

**Comment by timneutkens** [comment] 2021-07-29 09:01
Closing as this is not an actionable issue. Please follow the template instead of copy-pasting the same line multiple times.

**Closed by timneutkens** 2021-07-29 09:01 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 01:27
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
