### ISSUE TITLE
Unable to navigate using link or router.push in not-found.js template (next.js 13.4)

### ISSUE THREAD

**Issue by sanskar-19** [vercel/next.js#49736] opened 2023-05-13 04:20 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home Single Language
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.2
      eslint-config-next: 13.4.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/sanskar-19/nextjs-app-bugs

### To Reproduce

1. Go to homepage
2. Click on Go to random
3. You will notice its not redirecting to 404 first thing. 
4. If you reload the same then it goes to 404
5. From the 404 page link ain't working back to homepage.

### Describe the Bug

Unable to navigate between routes using Link or router.push()

### Expected Behavior

The pages should navigate easily as expected.

### Which browser are you using? (if relevant)

Chrome

**Comment by mkarajohn** [comment] 2023-05-13 12:25
Probably related with https://github.com/vercel/next.js/issues/49662

**Comment by sanskar-19** [comment] 2023-05-13 13:44
> Probably related with #49662

I dont think so, with nextjs 13 before the app directory this wasn't the case with the earlier version and infact your problem of navigating using Link or router wasn't something I faced. I still have that project deployed with the pages directory and router and link seems to be working fine.

**Comment by Refrezsh** [comment] 2023-05-13 21:34
I encountered the same problem. Clicking on the link, prefetch data for the next page, but the page is not updated until I restart it completely

**Comment by TheEdoRan** [comment] 2023-05-13 22:27
Related to #47862

**Comment by sanskar-19** [comment] 2023-05-14 07:47
> Related to #47862

Ahh, man. Such a bummer it is. I thought of using this one on prod. Glad I made it for the internal team first and didn't migrate the whole thing. Has so many countless bugs. Even router.push is not working in a normal client component if I basically validate a simple form submission. :(

**Comment by capJavert** [comment] 2023-05-15 08:15
Happening to me too, custom not found pages are useless. Just wanna raise awareness because with bug like this App directory should have never hit stable. 🔴

**Comment by Refrezsh** [comment] 2023-05-15 08:27
The custom error page has the same problem as in not-found page.

**Comment by timneutkens** [comment] 2023-05-15 11:04
Duplicate of #47862

**Closed by timneutkens** 2023-05-15 11:04 UTC
Labels: template: bug, area: Routing, area: app

**Comment by dilwalashakib** [comment] 2023-05-24 16:58
same problem
