### ISSUE TITLE
[possible regression] window.history.replaceState fails in iframes and native webviews

### ISSUE THREAD

**Issue by omryshap** [vercel/next.js#7426] opened 2019-05-26 15:01 UTC
# Bug report

## Describe the bug
As reported here (#3118, #3437, #5523), using next inside a  iframe or native webview (android for example), fails on this error `Error: Failed to execute 'replaceState' on 'History': A history state object with URL`.

## To Reproduce
create a webview in a native app, add src to a nextjs app, console will show the above error

## Expected behavior
should not throw an error

## Additional context
seems like this was handled in the past but either wasn't merged or somehow was removed from the codebase.

**Comment by semoal** [comment] 2019-05-27 22:18
Ping here, have same issue.

**Comment by semoal** [comment] 2019-05-28 06:58
By the way, I only have this issue on exported html that i render on a iframe like this:
```jsx
<iframe srcDoc={data.htmlReturned} />
```
data.htmlReturned is the html exported by the method app.renderToHtml() that comes from nextjs server side rendering. Also it has a base url that appends the url of the micro service that generates this html.

**Comment by timneutkens** [comment] 2019-05-28 12:10
Instead of posting "same issue" "ping" or similar use GitHub's reaction system and 👍 on the issue.

https://help.github.com/en/articles/about-conversations-on-github#reacting-to-ideas-in-comments

**Comment by denkristoffer** [comment] 2019-10-11 09:32
A use case for running Next.js applications in an iframe is when developing add-ins for Microsoft Office. These add-ins are really just websites rendered by Office inside an iframe, so at the moment it's not possible to use Next.js for these products.

**Comment by smddzcy** [comment] 2019-10-29 22:50
I'm getting the same error while trying to render a Next.js app inside [react-frame-component](https://github.com/ryanseddon/react-frame-component).

**Comment by DuudeXX8** [comment] 2020-03-15 19:31
I'm not getting this error inside a iframe neither native webview.I get this when my page url end's with two or more slashes. `//`.If I remove `withRedux`  in this part of my code ` export default withRedux(makeStore)(MyApp);` from _app.js file I get Internal Server Error in `//` this route.

**Comment by marbiano** [comment] 2020-06-02 21:29
@smddzcy could you help me to build an example where this is failing? I put [an example in here](https://codesandbox.io/s/history-iframe-x4ssm?file=/pages/index.js) but it seems to be working fine. I also tried to add the app to a regular iframe as src and it's working fine too.

@omryshap is there any simple way to create a webview on a native app for a non-mobile developer like me? :)

**Comment by nikhiltech** [comment] 2020-11-10 02:07
We are facing same issue in MS word extension which is using IE11 underneath. Works well if the iframe is opened in chrome.

**Comment by denkristoffer** [comment] 2020-11-10 07:20
@nikhiltech You can use a `history` polyfill for Office extensions.

**Comment by JanKaifer** [comment] 2022-11-23 13:01
I've tried reproducing this with `next@13` and iframes work fine in chrome and firefox:
Iframe wrapper on codesandbox: https://codesandbox.io/s/admiring-villani-l7gtqg?file=/src/App.js

> We are facing same issue in MS word extension which is using IE11 underneath. Works well if the iframe is opened in chrome.

We are not supporting IE: https://nextjs.org/docs/basic-features/supported-browsers-features

> I'm not getting this error inside a iframe neither native webview.I get this when my page url end with two or more slashes. //.If I remove withRedux in this part of my code export default withRedux(makeStore)(MyApp); from _app.js file I get Internal Server Error in // this route.

I wasn't able to reproduce this.

I'll close this issue, but feel free to open a new one if you can reproduce this in a supported browser.

**Closed** 2022-11-23 13:04 UTC
Labels: good first issue, type: needs investigation
