### ISSUE TITLE
Next.JS 11 Custom Server SSR Caching Example not working

### ISSUE THREAD

**Issue by gokulmhegde** [vercel/next.js#26383] opened 2021-06-20 12:40 UTC
### What version of Next.js are you using?

11

### What version of Node.js are you using?

14.6.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

The example mentioned in Custom Server SSR Caching 
[https://github.com/vercel/next.js/tree/canary/examples/ssr-caching](url)
is not working anymore
vist to the [http://localhost:3000/](url) itself giving the following error
`(node:4840) UnhandledPromiseRejectionWarning: TypeError: argument entity is required
    at etag (C:\xampp\htdocs\ssr-caching-app\node_modules\etag\index.js:72:11)
    at C:\xampp\htdocs\ssr-caching-app\node_modules\cacheable-response\index.js:93:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Guys you need to look into this ASAP as our application is breaking.

### Expected Behavior

Should work normally

### To Reproduce

Setup the following example

[https://github.com/vercel/next.js/tree/canary/examples/ssr-caching](url)

enter **npm run dev**

Go to the [http://localhost:3000/](url)

You should see the error in console log

**Comment by awareness481** [comment] 2021-06-20 16:25
https://github.com/vercel/next.js/issues/25621

**Comment by timneutkens** [comment] 2021-06-21 09:38
Duplicate of #25621

**Closed by timneutkens** 2021-06-21 09:38 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
