### ISSUE TITLE
Warning: ReactDOM.hydrate is no longer supported in React 18

### ISSUE THREAD

**Issue by alveshelio** [vercel/next.js#37378] opened 2022-06-01 20:22 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.18
      pnpm: 7.1.7
    Relevant packages:
      next: 12.1.7-canary.27
      react: 18.1.0
      react-dom: 18.1.0

### Describe the Bug

Getting a warning in the console
Warning: ReactDOM.hydrate is no longer supported in React 18. Use hydrateRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

### Expected Behavior

Should not get this warning

### To Reproduce

Visit https://codesandbox.io/s/silent-shape-syfbrx?file=/pages/day/index.js and check the console

**Comment by tm1000** [comment] 2022-06-01 21:31
This is a duplicate and was/is fixed in 12.1.7:

https://github.com/vercel/next.js/issues/37003#issuecomment-1134577540

**Comment by huozhi** [comment] 2022-06-01 22:00
@alveshelio there's no warning like react hydration warning in the codesandbox reproduction you post. Can you double check and to see if there's anything missing in the reproduction?

**Comment by huozhi** [comment] 2022-06-11 07:34
@alveshelio We also discovered another related issue and fix in 12.1.7-canary.35, can you try it on your side to see if it's resolved? I'll close this issue since for now the reproduction is not updated, feel free to comment or reopen if you have any further issue with latest canary build.

**Closed by huozhi** 2022-06-11 07:34 UTC
Labels: please add a complete reproduction, React 18

**Comment by markhughes** [comment] 2022-06-19 22:58
It only happens when you use a custom server

**Comment by fergalmoran** [comment] 2022-06-27 16:35
> It only happens when you use a custom server

Do you know if there's a workaround, @markhughes ?

**Comment by akashdeep-sharechat** [comment] 2022-07-02 23:05
I'm using v12.1.6 and  I seem to be facing this, but then again I'm using a custom express instance to use Next, maybe that's the reason.

**Comment by huozhi** [comment] 2022-07-04 11:46
@akashdeep-sharechat can you try v12.2.0, the custom server issue should be fixed
