### ISSUE TITLE
Global CSS not applied to AMP pages

### ISSUE THREAD

**Issue by achrinza** [vercel/next.js#10549] opened 2020-02-16 14:28 UTC
# Bug report

## Describe the bug

Global CSS (via `_app.tsx`/`_app.js`) are not being applied to AMP pages.

Non-AMP pages do not have this issue.

## To Reproduce

Reproduction sandbox: https://github.com/achrinza/issue-sandbox-nexjs-global-css-amp

Step-by-step:

1. Run `npm init next-app`
2. Create `styles.css`
    ```css
    body {
        color: #f00;
    }
   ```
3. Create `pages/_app.js`
    ```typescript
    import '../styles.css';

    export default ({ Component, pageProps }) => (
      <Component {...pageProps} />
    );
    ```
4. Create `pages/NonAmp.js` page:
    ```typescript
    const NonAmp = () => (
      <p>Hello, world!</p>
    );

    export default NonAmp;
    ```
5. Create `pages/Amp.js` page
    ```typescript
    export const config = { amp: true }
    const Amp = () => (
      <p>Hello, world!</p>
    );

    export default Amp;
    ```
6. Run `npm run dev`
7. View `localhost:3000/Amp` and `localhost:3000/NonAmp` - observe the lack of `color: red` on the AMP page.

## Expected behavior

The AMP page should have a global CSS applied.

## System information

- OS: Windows 10
- Firefox 73.0
- Version of Next.js: 9.2.1

## Additional context

N/A

**Comment by MistaPidaus** [comment] 2020-03-06 13:55
I have the same problem with TailwindCSS setup. I use the Hybrid AMP. Adding inline style `style={{ background: '#000'}}` on div works though.

My NextJS version: 9.2.2

**Comment by filipesmedeiros** [comment] 2020-03-25 12:17
Wow, I've been trying to figure this one out for hours, thanks. I'll see if I can find the error and work on it and eventually do a PR

**Comment by filipesmedeiros** [comment] 2020-03-25 13:58
It has to be somewhere in this file https://github.com/zeit/next.js/blob/canary/packages/next/next-server/server/render.tsx right?

**Comment by filipesmedeiros** [comment] 2020-03-25 14:17
Btw @achrinza as a temp fix, you can probably import your .css like this:

```
export default ({ Component, pageProps }) => <>
    <Head>
        <link rel="stylesheet" src="/styles.css" />
    </Head>
    <Component {...pageProps} />
</>
```

Assuming, ofc, you have the .css in the public dir. This, for some reason however, throws an Amp Validation error

```
[ warn ]  Amp Validation

/  error  The attribute 'href' in tag 'link rel=stylesheet for fonts' is set to the invalid value '/styles/global.css'.  https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml#custom-fonts
```

(This error happens even if the <link> is the only child of <Head>)

This works fine afaik.

Also, this should point in the right direction. Why does importing with `import` not work, while linking inside head does?
Maybe someone from the team can help.

**Comment by achrinza** [comment] 2020-03-25 14:21
@filipesmedeiros Thanks for the the workaround.

Unfortunately (based on the error), this won't generate a valid AMP page which would prevent the AMP Cache from caching the web page.

**Comment by achrinza** [comment] 2020-03-25 14:26
FWIW #8710 seems to be the PR that adds Global CSS

**Comment by filipesmedeiros** [comment] 2020-03-25 14:38
@achrinza True, this doesn't generate valid AMP. I think for now the easiest way then, to have AMP and a "global" style would be to just inline it in the <Head> of the _app.js using styled jsx.

**Comment by filipesmedeiros** [comment] 2020-03-25 14:43
So wait, this should be the cause right: webpack is not putting the imported stylesheets inside <style amp-custom>, maybe it has nothing to do with Next.

**Comment by filipesmedeiros** [comment] 2020-03-26 17:02
@timneutkens Sorry to tag you on this, but I have the feeling you can at point me in the right direction (or tag someone who can?) so I can try to have a fix for this.

I've been on this for a couple of hours, and I think this has to do with the Webpack config because:
1. `styled jsx` styles still get thrown into `<style amp-custom="">`
2. Webpack gets all the global styles in the `<head>` on normal pages

So I think to solve this, we need to find a way to tell Webpack to grab the global stylesheets and put them inside `<style amp-custom="">`. Maybe all of this is really obvious to you guys!

So question is: can you guys point me in the direction of where we are telling Webpack what to do with global stylesheets and how to access the flag that tells us if a page is AMP or not?

If this is asking too much, let me know.

Thanks!

**Comment by timneutkens** [comment] 2020-03-27 10:36
Webpack only compiles the stylesheet. It outputs it into a directory under `.next/static/css`. Main thing that has to be done is inline the full stylesheets needed under one tag in `packages/next/next-server/server.tsx` / packages/next/pages/document.tsx`.

**Comment by filipesmedeiros** [comment] 2020-03-27 11:56
Thanks, gonna check it out.

**Comment by sebastianbenz** [comment] 2020-03-27 18:41
Not sure if this is the best option, but one approach could be to implement a custom transformer for AMP Optimizer which collects all inline styles and merges it into `<style amp-custom>`. I've implemented  a similar transformer for the [eleventy integration](https://github.com/ampproject/eleventy-plugin-amp/blob/master/src/helpers/collectCss.js).

**Comment by filipesmedeiros** [comment] 2020-03-27 19:06
@sebastianbenz you mean after reading the files and getting then inside the markup? So:
1. Read a global `.css` file
2. Create a `<style>` tag for it
3. Append the contents of that tag to the `<amp-custom>` one

Something like this? I was trying to read directly from the file into the `<amp-custom>` but maybe that would be easier? I don't know

**Comment by sebastianbenz** [comment] 2020-03-27 19:47
If reading from the file into amp-custom works, then it's probably the easiest way.

**Comment by filipesmedeiros** [comment] 2020-03-27 21:00
I'm having a hard time connecting the two parts, mainly because it seems that when AMP mode is on, the dev server doesn't execute any code in [this client Webpack loader](https://github.com/zeit/next.js/blob/canary/packages/next/build/webpack/config/blocks/css/loaders/client.ts), which seems to control where the global CSS ends up, at least in dev.

Tim said (for prod I assumed) we only need to append the fully compiled `.css` file into `<amp-custom>` which should be relatively easy, but I'm kinda lost in the code: don't know where to access this file the correct way. I'm trying to pass a `globalStyles` prop to Document's `context._documentProps`, in [this line](https://github.com/zeit/next.js/blob/canary/packages/next/pages/_document.tsx#L445) it will just append it before the `curStyles`.

So currently it seems that for prod and dev, the methods of appending CSS into `<amp-custom>` are kinda different.

Still exploring, though

**Comment by bulentala** [comment] 2020-05-09 11:04
maybe it will work if necessary code arrangements are made

https://ampify.io/guides/docs/installation

**Comment by apoorvmote** [comment] 2020-07-10 12:48
Why nobody is talking about SASS support for amp? I looked through all open and closed issues. I mean there are no open issues even entertaining idea of SASS with amp. I understand it will take a while to get implemented. I would just like to have glimmer of hope that one day I will get built in SASS/SCSS support for amp.

**Comment by filipesmedeiros** [comment] 2020-07-10 13:13
The problem is not SASS I think, it's importing CSS in general with AMP. I think AMP itself is very restrictive on how CSS in handled, so importing is weird with AMP. Best way to do it is with styled-components, emotion, etc, I think

**Comment by bulentala** [comment] 2020-07-10 14:36
I did not have the opportunity to try it, but I saw something about it at this address.

https://www.npmjs.com/package/purify-amp-css

**Comment by apoorvmote** [comment] 2020-07-10 16:00
> Best way to do it is with styled-components, emotion, etc, I think

@filipesmedeiros I disagree. Main objective of AMP is not to make it easy for development but its customer experience. Also there is no custom javascript allowed in general. And they have really good reason for it. You can use it for edge cases. 

@bulentala you can do all that with postCSS. Because either way you need to support for all flavour of browser e.g. mozella, safari, chrome. They all have their propriatary prefixes to css. Also most of these libraries will make your css worse than it already is.

I think Nextjs people have done fantastic job for making it easy to add AMP pages. I have been building amp websites with Hugo SSG. And nextjs does save time for adding AMP pages. It will just take longer without SASS and other stuff.

**Comment by timneutkens** [comment] 2020-07-12 15:10
> Why nobody is talking about SASS support for amp? I looked through all open and closed issues. I mean there are no open issues even entertaining idea of SASS with amp. I understand it will take a while to get implemented. I would just like to have glimmer of hope that one day I will get built in SASS/SCSS support for amp.

Sass/CSS handling is the same so this issue covers both already. It's marked good first issue so feel free to send a PR

**Comment by apoorvmote** [comment] 2020-07-13 02:04
@timneutkens You are the guy I was trying to reach out. I have few related questions. Please let me know if I should create new issue for any of them.

**Is it better to write amp pages with `jsx` or is it better with `.md`?**

The benefit of using `.md` is the front matter(date or cateogory) that I can use to sort blog post and generate blog list pages.

**How would someone go about automatically generating list pages from `amp` page written in `jsx`? or add front matter to `jsx` page?**

**How good is `.md` to `amp` page conversion?**
I am using `marked` (as per documentation) to convert `.md` to `html`, adding dangerous inner html and making `export config = { amp: true }` and hoping that nextjs will do the rest. Like importing relevant amp libraries.

**Comment by jpbow** [comment] 2020-11-12 10:06
I got it working for production builds in https://github.com/vercel/next.js/pull/17914 but I'm not sure what I need to tweak to get styles working in development when viewing AMP pages. Did you make any progress on this @filipesmedeiros ?

**Comment by filipesmedeiros** [comment] 2020-11-12 14:38
@jpbow Not really sorry, I actually kinda gave up on AMP, because performance was good enough without it. Tbh I'm starting to think that having another standard (AMP) is not as productive as trying to optimize "regular" website made, for example, with Next.js or React. With this said, I know very little about AMP so I might be wrong.

**Comment by masihjahangiri** [comment] 2020-11-14 13:14
It's a really big issue because I use tailwind and I need style AMP pages with tailwindcss classes.

**Comment by Kevinfoss** [comment] 2020-11-14 20:08
What do I have to do to stop the hundreds of f@#_## emails I keep getting
from this dam place I've unsubscribed atleast a hundred fu#_## times I sick
if all your f@$$##emails stop motherfuckers

**Comment by Kevinfoss** [comment] 2020-11-14 20:18
Fuck you

**Comment by untitledlt** [comment] 2020-11-14 21:23
Try anger control club 🤣

**Comment by masihjahangiri** [comment] 2020-11-28 20:17
@Timer Thank you very much to follow this issue, can I ask you what is your plan for this critical issue & [this PR.](https://github.com/vercel/next.js/pull/17914)?

**Comment by ho3einmolavi** [comment] 2020-12-30 14:00
I use tailwindcss with AMP framework and need it to be fix.

**Comment by KasraAhmadi** [comment] 2020-12-31 15:23
We really need this feature in our project.

**Comment by Zizico2** [comment] 2021-01-04 13:45
> I use tailwindcss with AMP framework and need it to be fix.
 For people wanting this feature because of tailwind, tailwind-in-js: 
https://github.com/tw-in-js/twind

**Comment by amiralies** [comment] 2021-01-04 16:03
I think it's also possible to achvie this using `raw-loader`.

**Comment by tonny008** [comment] 2021-03-03 04:37
it's also possible to achvie this using styled jsx loader
next.config.js
```js
module.exports = {
  webpack: (config, options) => {
    config.module.rules.push({
      test: /\.css$/,
      use: [
        options.defaultLoaders.babel,
        {
          loader: require('styled-jsx/webpack').loader,
          options: { type: 'global' },
        },
      ],
    });

    return config;
  },
};
```
and
```jsx
import styles from '../styles.css';

      <style jsx global>
        {styles}
      </style>
```

**Comment by bulentala** [comment] 2021-03-03 19:06
@tonny008  Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

**Comment by amorphius** [comment] 2021-06-09 16:02
so no luck resolving this issue after 16 months?

**Comment by mikestopcontinues** [comment] 2021-06-09 16:34
Given that Google is no longer giving priority to AMP pages, I think it makes the most sense to abandon AMP as a strategy. Our dev hours are likely better spent making our sites work well on mobile.

**Comment by amorphius** [comment] 2021-06-09 16:47
> Given that Google is no longer giving priority to AMP pages, I think it makes the most sense to abandon AMP as a strategy. Our dev hours are likely better spent making our sites work well on mobile.

Hmm, didn't know about that. Is there any good article about the reason and what is the future of AMP according to Google? So is it worth making AMP websites now or better to wait for some alternatives?

**Comment by jeremyandbandit** [comment] 2021-06-11 19:15
HELP ME !!!  Hackers won't get away from me

**Comment by hyoretsu** [comment] 2021-06-28 21:11
> Given that Google is no longer giving priority to AMP pages, I think it makes the most sense to abandon AMP as a strategy. Our dev hours are likely better spent making our sites work well on mobile.

Thank you and my luck of checking this issue. AMP is too... Weird, I was about to use Linaria for normal styling and Styled Components for the sole purpose of supporting AMP (aside from the 15 pages I had open about AMP-specific things)

**Comment by rawan249** [comment] 2022-09-06 02:01
Tttttt

**Comment by rawan249** [comment] 2022-09-06 02:01
Google play store

**Comment by amerzad** [comment] 2022-12-05 03:54
AMP is not about getting priority in SERP, and it was never about that except for people who are opportunists. AMP is about inventing a new evergreen HTML standard which continuously removes outdated practices and optimizing for performance automatically, and it started for mobile but it is now for every device form factor.

Many publishing companies are making AMP only response complete websites and they are using Next.js to ease some tasks like SSG, and that worked well for the company I work in so far, and we will continue using Next.js until we find a full solution with SWC support (or any good alternative DX tool chain).

Most of the people who stopped being attracted to AMP are talking about the difficulty of maintaining two websites, but I think they are very outdated about how powerful AMP library got in recent years. Actually we were able easily to do almost all the features we need for a modern publishing website using AMP only. Now, when we need to use some advanced CSR features we will use either hybrid AMP for that page/app (and possibly use AMP-to-PWA pattern), or skip the AMP completely, but the majority (if not all) are done in AMP only with `amp-script` and advanced usage of amp state.

This is an alternative route compared to hydration, but it is better than hydration because the page is fully interactive once it is loaded and it is smaller as there will not be hydration data payload.

After all, supporting Web Vitals is not an easy task for the average developer, and AMP is making it almost ready out of the box.

**Comment by cdsimmons** [comment] 2023-03-20 09:52
I wasn't having much luck with the solution from @tonny008 so I did another workaround. 

My use case is having a single global CSS file imported in the app.js, which has my tailwind imports etc.

First compiled the imported CSS into its own file to make it available later:
```js
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
  webpack: (config, options) => {
    config.plugins.push(
      new MiniCssExtractPlugin({
        filename: '../public/global.css',
      })
    );

    return config;
  },
};
```

Then fetch and embed for amp pages:
```js
import '../styles/global.css';

type MyAppProps = AppProps & {
  css: string;
};

const MyApp = ({ Component, pageProps, css }: MyAppProps) => {
  return (
    <>
      {isAmp && <style jsx global>{css}</style>}
      <Component {...pageProps} />
    </>
  )
};

MyApp.getInitialProps = async () => {
  const res = await fetch('http://localhost:3000/global.css');
  const css = await res.text();
  return { css }
}
```

Loses the advantages of chunking and does not work for CSS modules but fits my use case.

**Comment by leerob** [comment] 2023-11-08 14:06
Thank you for taking the time to open this. Unfortunately, we are not planning on a fix here.

**Closed by leerob** 2023-11-08 14:06 UTC
Labels: kind: bug, area: AMP
