### ISSUE TITLE
bundle rebuilding with routes && styles

### ISSUE THREAD

**Issue by angu001** [vercel/next.js#12047] opened 2020-04-20 13:59 UTC
when  i click any route ,   it is coming. [HMR] bundle rebuilding ... Reloading stylesheets... .  so if it comes , page redirecting very slow. it takes time to display,

"next": "^9.3.4",
Chrome : Version 81.0.4044.113 (Official Build) (64-bit)
macOs : 10.15.3 (19D76)

**npm run dev** 
any one help?

**Comment by Timer** [comment] 2020-09-10 18:43
This should be fixed in Next.js 9.4+ with Fast Refresh!

**Closed by Timer** 2020-09-10 18:43 UTC

**Comment by balazsorban44** [comment] 2022-01-29 13:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
