### ISSUE TITLE
[MAJOR BUG] Next/link forces scroll to top of {children} of layout

### ISSUE THREAD

**Issue by tshmieldev** [vercel/next.js#59387] opened 2023-12-07 22:26 UTC
### Link to the code that reproduces this issue

https://github.com/tshmieldev/next-scroll-bug

### To Reproduce

Issue reproduced on Chrome
1. Start app (npm run dev)
2. Click links

### Current vs. Expected behavior

Current: The link brings you to a page, and scrolls to beginning of {children}, not to top of page.
Expected: Always brings you to top of opened page.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: Windows
  Arch: x86
  Version: Windows 10 latest
Binaries:
  Node: 21.4.0
  npm: 10.1.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14
  eslint-config-next: 14.0.4
  react: 18
  react-dom: 18
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context
This happens if the {children} elements are not visible from the top of the page. If they are (even one pixel of them), the bug doesn't occur. That's why I added margin-bottom to the links, to make the children not visible and trigger the bug.

**Comment by doinki** [comment] 2023-12-13 10:54
It seems to be related to #42492.

**Comment by tshmieldev** [comment] 2023-12-13 13:04
It is most likely also related to https://github.com/vercel/next.js/issues/47475
This seems to be a very serious issue as it happens with a very basic example which might be used for a very common use case.

**Comment by samcx** [comment] 2024-02-22 00:22
@tshmieldev Thank you for submitting an issue!

This is actually the expected behavior → https://github.com/vercel/next.js/blob/aafb329c6d3d16934b5043472cc6062ec23ad03e/packages/next/src/client/components/layout-router.tsx#L248C1-L263C12.

> The default behavior of <Link> is to scroll to the top of a new route or to maintain the scroll position for backwards and forwards navigation.

- https://nextjs.org/docs/app/api-reference/components/link#scroll

I can see that the documentation can be a little clearer with top of a new "route," which makes sense when you consider `{children}` to likely be the thing that changes (you would want the content that changes to be what you see, which is pages not layouts).

Let me know if that makes sense!

**Comment by tshmieldev** [comment] 2024-02-25 09:33
@samcx thank you for your reply
Then, if the default behavior is scrolling to {children}, why doesn't it occur if even one pixel of them is in view on top of the page?
My issue with this behavior, is I had a layout as such:
<Header />
{children}
<Footer />
The issue happened because my header element was big, and sometimes took more than 100vh, and then when opening new route it wouldn't be at the top of viewport. Do you know of a way in nextjs to prevent such behavior? Thank you

**Comment by samcx** [comment] 2024-02-27 23:01
In the code link, here's the comment

> // If the element's top edge is already in the viewport, exit early.

So this means that nothing happens if the `{children}` is in the viewport. If it isn't, scroll to `{children}`. If you want to prevent the scrolling behavior, you can use `https://nextjs.org/docs/app/api-reference/components/link#scroll` in the `<Link>` component.

**Comment by samcx** [comment] 2024-03-04 21:44
@tshmieldev Let me know if that makes sense!

**Comment by tshmieldev** [comment] 2024-03-09 17:50
@samcx I have found that scroll={false} prevents scrolling, however, as I "Expected: Always brings you to top of opened page.", which would be a very useful behavior. I see that you mentioned my issue in a similar thread, where they are facing a very similar problem. Not so sure if this is a bug, definitely something unintuitive, and perhaps malicious (as to get the "right" behavior, you need to use a client component that will window.scroll() for you). Do you know any way to make a <Link /> scroll to the top of the page, instead of scrolling to {children} or not scrolling? Thanks

**Comment by samcx** [comment] 2024-03-09 18:28
@tshmieldev It is the expected behavior, not a big.

A key thing to understand here is that [Layouts do not re-render](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#layouts)—meaning that Pages are responsible for the changing content on your page. Hence, it makes more sense for the default behavior to go to `{children}` if the `{children}` is not in the viewport.

> Do you know any way to make a scroll to the top of the page, instead of scrolling to {children} or not scrolling?

Unfortunately, we don't directly provide a way to do this. Is there a particular reason why your Layout would have content larger than your viewport? I would look to move that into a Page instead.

**Comment by samcx** [comment] 2024-03-09 18:31
In the meantime, I will be closing this issue, since we have confirmed there is no breaking behavior here!

**Closed by samcx** 2024-03-09 18:31 UTC
Labels: template: bug

**Comment by tshmieldev** [comment] 2024-03-09 19:26
@samcx I have a big header component, which doesn't change for pages, so I have it as part of my layout, same with my footer, and on phones specifically it takes over 100vh

**Comment by samcx** [comment] 2024-03-10 23:00
@tshmieldev Noted.

We could possibly look to provide an option to opt of the `{children}` behavior, but in the meantime, I recommend reducing your header size (if possible) or moving that into to your Pages.

**Comment by tshmieldev** [comment] 2024-03-11 10:26
@samcx it would be amazing if you could please do that. I finished that project, and used a workaround, thank you for considering my use case

**Comment by resthedev** [comment] 2024-03-19 00:27
> @tshmieldev Noted.
> 
> We could possibly look to provide an option to opt of the `{children}` behavior, but in the meantime, I recommend reducing your header size (if possible) or moving that into to your Pages.

Please do consider this. I do think the unexpected default behavior is not desired by everyone. Would be good to have the option to opt in or out. Thank you!

**Comment by samcx** [comment] 2024-03-19 21:03
@resthedev We are—will be discussing this with the team!
