### ISSUE TITLE
Safari Doesn't support Next.js

### ISSUE THREAD

**Issue by puneetkathar1** [vercel/next.js#27264] opened 2021-07-17 20:08 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Safari

### What operating system are you using?

iOS

### How are you deploying your application?

Vercel

### Describe the Bug

My website https://murray-ecru.vercel.app/login
is not working with safari when accessing from iPhone but works fine with chrome and Ipad. But the homepage works fine always. Basically when there is SSR used on a page. It doesn't load. 

### Expected Behavior

It should load properly as it does in chrome.

### To Reproduce

Just visit the link https://murray-ecru.vercel.app/login

**Comment by msp5382** [comment] 2021-07-23 11:31
I cannot reproduce this. It's work on safari normally.

**Comment by ijjk** [comment] 2021-07-23 16:08
Hi, Next.js does support safari and we test against multiple versions as can be seen [here](https://github.com/vercel/next.js/runs/3144614363), I'm gonna close this since if there is an issue it is most likely related to a `node_module` being included and the above comment confirms it is working normally as well.

**Closed by ijjk** 2021-07-23 16:08 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 01:28
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
