### ISSUE TITLE
Image component does not change dynamically

### ISSUE THREAD

**Issue by mjr** [vercel/next.js#18499] opened 2020-10-29 18:49 UTC
# Bug report

## Describe the bug

Only changes the `data-src` and `data-srcset` by dynamically changing the `src` attribute.

## To Reproduce

1. Go to https://codesandbox.io/s/frosty-hellman-ilgn0?file=/pages/index.js
2. Click on button change.
3. See the console to see the changes in `data-src` and `data-srcset` only.

## Expected behavior

What is expected is to change the image.

## Screenshots

![2020-10-29 at 15 45 21](https://user-images.githubusercontent.com/9324986/97618706-2058a500-19fe-11eb-9e06-93463a154713.gif)

**Comment by matteo07** [comment] 2020-10-30 10:40
I've encountered the same problem using 
    "next": "10.0.0",
    "react": "17.0.1",

when I toggle a menu I change the src of the icon Image
I correctly see them changing in the component props but the displayed image remains the same

**Comment by cyrus-za** [comment] 2020-10-30 14:44
Ran into same problem. next 10.0.0 and react 16.8

**Comment by lachlanjc** [comment] 2020-11-01 18:56
Yep, seeing the same issue. If you’re on a page like https://scrapbook.hackclub.com/matthewgleich/ or https://scrapbook.hackclub.com/lachlanjc/ & click one of the user mentions down below, the profile picture at the top doesn’t change.

**Comment by lachlanjc** [comment] 2020-11-01 19:00
Related/possibly the same? #18369

**Comment by Timer** [comment] 2020-11-01 23:46
Duplicate of #18369

**Closed by Timer** 2020-11-01 23:46 UTC
Labels: kind: bug, point: 3

**Comment by isaiasneto** [comment] 2020-11-18 00:21
If you set the prop loading to "eager" the image works...

**Comment by balazsorban44** [comment] 2022-01-29 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
