### ISSUE TITLE
Back button for rewritten page broken in last version

### ISSUE THREAD

**Issue by PepijnSenders** [vercel/next.js#25490] opened 2021-05-26 14:41 UTC
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

14

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

none

### Describe the Bug

Pressing the back-button to a rewritten page causes this bug for us in the latest version:

<img width="714" alt="Screen Shot 2021-05-26 at 10 34 29 AM" src="https://user-images.githubusercontent.com/2052659/119679640-867b9e00-be0e-11eb-92da-79f20ce72139.png">

Seems like `shouldResolveHref`, which was added in https://github.com/vercel/next.js/pull/25112 is now `false` and the router is not able to resolve the `href` anymore.

### Expected Behavior

Back button to work.

### To Reproduce

Have a page that is served through a rewrite, go to another page through a next/link transition (only reproducible on the second transition when the page has not been built yet and you're testing it locally), go back to the previous page with the browser back button will throw this error.

**Comment by PepijnSenders** [comment] 2021-05-26 17:37
Apparently, the issue is a bit more complex (probably why it wasn't caught by the current integration tests), but this only breaks when the page has multiple params (like: `[[...param]].jsx`) and the page needs `export const getServerSideProps` as well.

**Comment by m-bp** [comment] 2021-05-27 09:05
This is happening to me and we don't use `getServerSideProps`. We do have dynamic routes, however.

**Comment by ctestamarck** [comment] 2021-05-28 19:27
We're experiencing the same issue using a route with one dynamic param, along with getStaticPaths and getStaticProps. Tested with v10.2.4-canary.0. All click-based navigation works fine using only href param on Links and router.push. I tried adding the 'as' param to Links but that causes the same error message as above when links are clicked.

**Comment by PaulSenon** [comment] 2021-05-31 19:59
Same here.

The problem appears between `v10.2.1-canary.6` and `v10.2.1-canary.7`.
It might be related to this commit: 5bff9ea

A similar issue has been opened and fixed on `v10.2.4-canary.0` (https://github.com/vercel/next.js/issues/25285)
but it seems that it does not really fix the issue...

Here is one sample project to reproduce the bug:
https://stackblitz.com/edit/bug-nextjs-router-back-as-path?file=next.config.js

I also forked and updated (with `v10.2.4-canary.0`) the example from @DaniAkash from the original issue:
* demo: https://tmg8g.sse.codesandbox.io/app
* source: https://codesandbox.io/s/nextjs-routing-issue-forked-tmg8g?file=/pages/index.js

In the meantime, you'll have to rollback to `10.2.0` if you're having the issue in production...

Hope it will be fixed soon :/

**Closed** 2021-06-01 18:01 UTC
Labels: template: bug

**Comment by PepijnSenders** [comment] 2021-06-01 19:41
@ijjk I just tested this with my integration test and it still seems broken. (https://github.com/vercel/next.js/pull/25666#issuecomment-852393471) will see if I can fix it.

**Comment by balazsorban44** [comment] 2022-01-28 07:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
