### ISSUE TITLE
Next.js update causes Jest errors

### ISSUE THREAD

**Issue by akselinurmio** [vercel/next.js#39470] opened 2022-08-10 16:46 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.5-canary.1
      eslint-config-next: N/A
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

Upgrading next.js from version 12.1.0 to `canary` (12.2.5-canary.1) or `latest` (12.2.4) breaks most of project's Jest tests.

In my real world project there are dozens of failing errors, and all of them output the following error message after the update (where `Button` is the name of tested component):

```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
    
    Check the render method of `Button`.
```

### Expected Behavior

Tests are expected to pass.

### Link to reproduction

https://github.com/akselinurmio/next-js-svg-problem/compare/broken

### To Reproduce

1. Run `npm install`
2. Run `npm test`

**Comment by MarianPalkus** [comment] 2022-08-10 18:19
Hi @akselinurmio,
might this be a duplicate of #37542?
As stated in the issue this behaviour can occur when update from version 12.1.0 to 12.1.1  or greater.
https://github.com/vercel/next.js/issues/37542#issuecomment-1151075024 seems to contain solutions to this problem as well.

**Comment by akselinurmio** [comment] 2022-08-10 18:52
Thank you @MarianPalkus, that issue is indeed similar to this one, but it's already locked so I had to create a new issue.

I will have to take a better look at the proposed solution you linked to.

**Comment by akselinurmio** [comment] 2022-08-11 10:10
Workaround described in https://github.com/vercel/next.js/issues/35634#issuecomment-1080942525 worked just fine. However, I’m pretty sure that the test behaviour shouldn’t change in patches, like it did here, so I don’t consider this issue as solved just because there is a way around it.

**Comment by ijjk** [comment] 2022-08-11 14:13
@akselinurmio since you are customizing the webpack config this is isn't covered by semver as noted in our docs here https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config

The mentioned solution is the correct way to handle this with the customization done currently so I'm gonna close this for now.

**Closed by ijjk** 2022-08-11 14:13 UTC
Labels: template: bug
