### ISSUE TITLE
Function.name not working in IE11

### ISSUE THREAD

**Issue by tomdohnal** [vercel/next.js#12722] opened 2020-05-11 15:11 UTC
# Bug report

## Describe the bug

The `Function.name` property is not working (not pollyfilled) in IE 11.

## To Reproduce

See https://github.com/tomdohnal/function-name-repro

1. Run the project
2. Open the console in IE 11 - it outputs `undefined`

## Expected behavior

It should output the name of the function (as in the modern browsers)

## System information

- OS: [Windows]
- Browser IE 11
- Version of Next.js: `9.3.6` and `9.3.7-canary.21`

**Comment by timneutkens** [comment] 2020-05-11 17:28
Why are you using this in the first place 🤔

**Comment by tomdohnal** [comment] 2020-05-11 19:22
It's in a library that I use (`react-spring`)

**Comment by KB1RMA** [comment] 2020-06-06 13:59
@tomdohnal Is this perhaps what's causing this IE issue in the v9 RC? Or are you using v8? 

https://github.com/react-spring/react-spring/issues/1012

**Comment by tomdohnal** [comment] 2020-06-07 14:38
@KB1RMA Yeah, this might be it. Nonetheless, I'm using `next-transpile-modules` for `react-spring`. If I recall correctly there were some other IE-11 compatibility issues with it and I'm not even sure if IE11 support is something they guarantee :)

**Comment by Timer** [comment] 2020-08-18 06:08
Fixed by #13704

**Closed by Timer** 2020-08-18 06:08 UTC
Labels: kind: bug, type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-29 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
