### ISSUE TITLE
Unexpected token "export" on src/router/index.js file

### ISSUE THREAD

**Issue by nlaitan** [vercel/next.js#22928] opened 2021-03-10 05:33 UTC
### What version of Next.js are you using?

v10.0.8

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Linux Mint 20

### How are you deploying your application?

next dev

### Describe the Bug

I have a file created with personal purpouses on next project called it `%ROOT%/src/router/index.js`. 
In that file, next doesn't allow me to use export, the console throws an error:
```
export const ROUTES = {
^^^^^^
SyntaxError: Unexpected token 'export'`
```
instead of it allows me to use commonJS export (with module.exports)

### Expected Behavior

Hability to use export on any file in the project

### To Reproduce

create a file called `%ROOT%/src/router/index.js` and try to use export on it

**Comment by ijjk** [comment] 2021-04-28 03:00
Hi, it sounds like this file is being imported in `next.config.js` or another file that uses commonjs so it is expected for export to cause a syntax error when being loaded from a non-transpiled file.

I'm going to close this since it doesn't sound like a bug, if you are still having trouble with this feel free to respond with additional info/a minimal reproduction and we can investigate further!

**Closed by ijjk** 2021-04-28 03:00 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
