### ISSUE TITLE
Cypress with Cucumber example

### ISSUE THREAD

**Issue by eddiejaoude** [vercel/next.js#37777] opened 2022-06-16 21:25 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```bash
➜  with-cypress git:(canary) ✗ npx --no-install next info 

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.3.0
      npm: 7.15.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 17.0.2
      react-dom: 17.0.2

warn  - Latest canary version not detected, detected: "12.1.6", newest: "12.1.7-canary.40".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which example does this report relate to?

with-cypress

### Describe the Bug

This is **not** a bug, but seemed like the best issue type (`Documentation` was the other option)

I was keen to add another example, which builds on the Cypress example but also has Cucumber

### Expected Behavior

Same tests as the Cypress example but using Cucumber

```gherkin
Feature: About page

    Scenario: Navigating to the about page
        Given I open the "/" page
        When I click on the "about" link
        Then I see "about" in the url
        And I see "About Page" in the "h1"
```

### To Reproduce

Output of the tests

```bash


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  App.feature                              00:02        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:02        1        1        -        -        -  

```

**Comment by balazsorban44** [comment] 2022-06-17 13:30
Closing as this is not a bug, and is being addressed in #37778. Let's continue there. :+1:

**Closed by balazsorban44** 2022-06-17 13:30 UTC
Labels: template: bug
