### ISSUE TITLE
Fast Refresh / Hot Reload on version 10.0.6 doesn't work

### ISSUE THREAD

**Issue by whydnxx** [vercel/next.js#21940] opened 2021-02-07 13:16 UTC
**What version of Next.js are you using?**

10.0.6

**What version of Node.js are you using?**

12.14.1

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**How are you deploying your application?**

next dev

**Describe the Bug**

I have to create new project with ```npx create-next-app my-project``` 
when I change the default code, hot reload not working. But I have solutions to downgrade version from ```10.0.6``` to ```10.0.5``` and hot reload is working.

**Expected Behavior**

-

**To Reproduce**

-

**Comment by timneutkens** [comment] 2021-02-08 14:42
Closing as there is no reproduction provided.

**Closed by timneutkens** 2021-02-08 14:42 UTC
Labels: template: bug

**Comment by wtatum** [comment] 2021-03-04 18:39
I have seen the same in both 10.0.6 and 10.0.7 with a clean `yarn create next-app` and no other changes. Works if I change version back to 10.0.5. 

If you can clarify the best way to provide a reproduction I would be willing to do it.

**Comment by ash0803** [comment] 2021-03-05 18:43
I can confirm the same thing even with the latest 10.0.8. The latest version that works is 10.0.5

I'm using Windows with WSL2

**Comment by DannyFeliz** [comment] 2021-03-30 07:23
Upvote this discussion https://github.com/vercel/next.js/discussions/22214

**Comment by balazsorban44** [comment] 2022-01-28 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
