### ISSUE TITLE
HMR with global style does not work

### ISSUE THREAD

**Issue by SOHELAHMED7** [vercel/next.js#10416] opened 2020-02-04 13:53 UTC
# Bug report

HMR with global style does not work.

https://nextjs.org/learn/basics/styling-components/global-styles-work

## Describe the bug

When we apply `global` keyword in `<style jsx global>{`.....css....`}</style>` and then remove, we must have to reload the browser. It does not automatically change the CSS styles in browser. HMR is not working in this case.

Also sometimes we even need to restart dev server by `npm run dev`

If we remove keyword `global` the style should be removed by HMR
If we add keyword `global` the style should be added by HMR

## To Reproduce

Steps to reproduce the behavior

1. as described here https://nextjs.org/learn/basics/styling-components/setup

## Expected behavior

it should automatically change styles

## System information

- OS: Ubuntu 18.04
- Browser Chrome 79.0.3945.130
- Version of Next.js: 9.2.1

**Comment by aralroca** [comment] 2020-02-05 13:30
Similar behavior with `next-sass` plugin

**Comment by timneutkens** [comment] 2020-03-16 10:48
@aralroca try using the built-in sass support: https://nextjs.org/blog/next-9-3.

**Comment by aralroca** [comment] 2020-03-16 16:36
@timneutkens right now I'm using built-in sass and this is already solved for me.

**Comment by TodorTotev** [comment] 2020-05-29 09:30
> @aralroca try using the built-in sass support: https://nextjs.org/blog/next-9-3.

@timneutkens Do you think its reasonable to add a warning for this particular case?

**Comment by timneutkens** [comment] 2020-05-29 11:58
@TodorTotev Let's just close this one as there wasn't any discussion after the one comment.

**Closed by timneutkens** 2020-05-29 11:58 UTC
Labels: good first issue, help wanted

**Comment by SOHELAHMED7** [comment] 2020-06-19 08:28
I request to add

 - 'won't fix' label to this issue 
- add a note in docs of this as known issue

If you agree for second point, I can create a pull request

**Comment by balazsorban44** [comment] 2022-01-30 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
