### ISSUE TITLE
Hot reloading extremely slow. Goes through every iteration only when page is viewed.

### ISSUE THREAD

**Issue by MarkLyck** [vercel/next.js#10706] opened 2020-02-26 14:05 UTC
# Bug report

It used to be that when you made a code change, the page would hot-reload in the background and I'd barely be able to switch to my browser before the page was re-rendered.

However with Next: 9.2.0 when I make let's say 100 keystroke changes. in. my app doesn't automatically re-render in the background. Instead, it waits till I navigate to my browser and then it will re-render 100 times, 1 at a time and wait for it to finish.

For example, if I'm just changing the text in a `<p>` tag a few times and I go to my localhost:3000 I will see every keystroke change I did render 1 by 1.

It takes forever to wait for and is extremely inefficient. I get the arguable appeal of not re-rendering in the background. But I have absolutely no need for 99% of these re-renders. I just want to see what the current state it. Not see how it changed with every single keystroke I did editing my app.

I assume this must be a bug???

## Additional context

- OS: macOs (2016 Macbook Pro)
- Browser: Google Chrome
- Version of Next.js: 9.2.0

I'm not using Typescript so it's not due to Typechecking or the Fork typescript provider.

I believe this started happening when I updated form next 8.x to 9.x

**Comment by timneutkens** [comment] 2020-02-26 14:10
Sounds unexpected, hard to say what exactly you're experiencing without a reproduction / repository to look at.

**Comment by MarkLyck** [comment] 2020-02-26 19:01
Difficult to provide. It's a pretty standard app, nothing special. But it's pretty big with 10 pages and +100 components.

**Comment by timneutkens** [comment] 2020-02-26 19:34
It's difficult to debug hence why we need a reproduction. Can't recommend anything specific, you'd need to figure out what events are sent through the webpack-hmr eventsource connection and then check how they're applied and in what order, eg if they're stacked until navigation for whatever reason (really not sure based on the provided description).

**Comment by madsfaerch** [comment] 2020-02-26 20:07
@MarkLyck I'm experiencing the same issue. I thought it was just how Next works. I did find it amusing to see a super quick timelapse of all changes I've done since my last visit to the browser.  

Maybe we can compare setups to find a source for the behavior?

**Comment by madsfaerch** [comment] 2020-02-26 20:40
@MarkLyck just to confirm, is this the issue you're describing?

1. Have Next project open in a tab with `next dev` active
2. Focus a different tab
3. Make several code changes, resulting in recompilations
4. Focus browser
5. Focus tab with Next project
6. Observe all the changes applied sequentially


![next-hmr](https://user-images.githubusercontent.com/6967541/75385604-57f7d600-58e0-11ea-9b45-48dbd289ba84.gif)

**Comment by MarkLyck** [comment] 2020-02-26 20:49
@madsfaerch Yes that's exactly what I'm experiencing, except my app's main page is pretty hefty with many animations so it takes 50x longer to render than yours.

But yes, that looks. like the exact same issue, I'm having.

Every time I make a few code changes. I have to wait like 10 seconds before I can interact with my application when running in dev.

**Comment by timneutkens** [comment] 2020-02-26 21:13
@madsfaerch thanks! That makes it a lot clearer on where to look, probably related to: https://github.com/zeit/next.js/blob/canary/packages/next/client/dev/on-demand-entries-client.js#L16-L23

**Comment by madsfaerch** [comment] 2020-02-26 21:29
@timneutkens happy to help! 

I just tried to make a quick reproduction by doing 

- `yarn create next-app`
- `yarn dev`
- Open localhost:3000
- Focus different tab
- Edit `pages/index` multiple times
- Return to browser and focus localhost tab
- Observe the “buffered” changes applied

I checked in FF and Chrome on macOS Catalina. My node version is ~9 and I also observe this in another env with Chrome, node ~10 and macOS Mojave. 

It’s pretty much a non-issue on light pages, but I can imagine it being an impediment on heavy pages. 

I’d be happy to spend some time researching this, but I’m not well versed in HMR configurations.

**Comment by madsfaerch** [comment] 2020-02-26 21:30
How would you like a repro supplied? A github repo?

**Comment by timneutkens** [comment] 2020-02-26 21:31
@madsfaerch if those are the definitive steps to reproduce that's all we'll need 👍 Will have someone investigate if we can improve it 💯 Thanks for providing really clear what you were seeing, it really helps a lot.

**Comment by madsfaerch** [comment] 2020-02-26 21:34
@timneutkens Great! Thank you so much for developing these amazing products. I am in awe of your work (and the pace of it)!

**Comment by Timer** [comment] 2020-09-10 18:22
Just tested this on the latest Next.js and it appears to be fixed by Fast Refresh. We added a feature that delays re-rendering until all updates are processed.

**Closed by Timer** 2020-09-10 18:22 UTC
Labels: kind: story

**Comment by balazsorban44** [comment] 2022-01-29 13:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
