### ISSUE TITLE
Unhandled Runtime Error With Async Page Component + Empty React Fragment

### ISSUE THREAD

**Issue by houzyk** [vercel/next.js#46059] opened 2023-02-17 17:44 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.1
      npm: 9.3.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.1.2-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/houzyk/over-engineered-glob/blob/main/src/app/page.tsx

### To Reproduce

1. In app>page.tsx, make the Home component async.
2. Return only a react fragment <></> (notice that there is no space between <> and </>)

### Describe the Bug

Get unhandled runtime error in browser: `SyntaxError: "undefined" is not valid JSON`. Remember that there was no space between <> and </> when we returned the fragment. If you add a space between them, the runtime error is gone. If we also replace the fragments by an actual HTML tag (like h1), the runtime error also goes away.

Morever, if we remove the "async" from the Home component such that there still is no space between <> and </>, the run time error also goes away.

### Expected Behavior

I expected a blank page without any runtime error as would be the case if I return an empty react fragment.

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Found on localhost:3000

**Comment by Fredkiss3** [comment] 2023-02-17 22:05
I also had the same error #44318 , one workaround is to return null instead of empty fragment

**Comment by timneutkens** [comment] 2023-02-28 14:21
Closing as duplicate of https://github.com/vercel/next.js/issues/44318

**Closed by timneutkens** 2023-02-28 14:21 UTC
Labels: template: bug
