### ISSUE TITLE
Image component caching image

### ISSUE THREAD

**Issue by JamesSingleton** [vercel/next.js#18573] opened 2020-10-31 04:17 UTC
# Bug report

## Describe the bug

Image component caching image unless there is a page refresh. This does not happen with a normal `<img />` tag.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone https://github.com/vercel/next.js/tree/canary/examples/cms-contentful
2. Open up `components/cover-image.js`
3. Change out the `<img />` for `<Image />` from `next/image`
4. Change `src={url}` to `src={`https:${url}`}` due to #18536 
5. Start up Next `yarn dev`
6. Go to an article
7. Click on an article from `More Stories`

 ## ⚠️ Don't forget to add the following to your `next.config.js`
```js
module.exports = {
  images: {
    domains: ['images.ctfassets.net'],
  },
}
```

## Expected behavior

Image from the new story should be the cover photo

## Screenshots

![next-image-component](https://user-images.githubusercontent.com/21000200/97770870-6e4fd480-1af4-11eb-8e8b-bb61035c2b15.gif)

## System information

- OS: Windows
- Browser (if applies) Chrome
- Version of Next.js: 10.0.0
- Version of Node.js: 12.18.4

**Comment by Timer** [comment] 2020-10-31 04:50
Thanks for reporting! I believe we're already tracking this but it doesn't hurt to have again.

**Comment by JamesSingleton** [comment] 2020-10-31 04:54
@Timer, I couldn't find an open issue when I was searching, but maybe I just didn't search the right keywords.

**Comment by Timer** [comment] 2020-10-31 04:59
#18499

**Comment by Timer** [comment] 2020-10-31 04:59
Closing since I found the duplicate above, thanks!

**Closed by Timer** 2020-10-31 04:59 UTC
Labels: kind: bug, priority: p0

**Comment by balazsorban44** [comment] 2022-01-29 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
