### ISSUE TITLE
Server actions failing when route is intercepted

### ISSUE THREAD

**Issue by baked-dev** [vercel/next.js#52591] opened 2023-07-12 12:36 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: 3.4.1
      pnpm: N/A
    Relevant Packages:
      next: 13.4.10-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/baked-dev/interception-actions-reproduction

### To Reproduce

Working:
- open index route
- press "open modal" button
- press "test" button

Not working:
- open `/test`
- press "test" button

### Describe the Bug

Intercepting routes seems to make server actions defined in the un-intercepted version of that same route fail with a 500 error, logging the following:
```
- error TypeError: __webpack_modules__[moduleId] is not a function
    at Object.__webpack_require__ [as require] (/.next/server/webpack-runtime.js:33:42)
```

Note: this issue did not happen in the dev mode of 13.4.8, only when deployed to vercel. In 13.4.9-canary.4 it also happens in the dev environment. In our 13.4.8 deployment on vercel i was able to see the response headers reporting the matched path as `/(...)test` when invoking the action from the full, un-intercepted page 

### Expected Behavior

Server actions should be working when routes are intercepted.

### How are you deploying your application? (if relevant)

Vercel

<sub>[NEXT-1436](https://linear.app/vercel/issue/NEXT-1436/server-actions-failing-when-route-is-intercepted)</sub>

**Comment by klzeng** [comment] 2023-10-20 05:59
This happens to me even in dev mode of version "13.5.4". Odd enough, it seems to come and go (tried clean .next and force browser reload), but persist most of the time.

**Comment by shuding** [comment] 2023-11-30 15:42
Seems to be a duplicate of #49934?

**Closed** 2023-12-01 22:45 UTC
Labels: template: bug, linear: next
