### ISSUE TITLE
global css in _app throwing error

### ISSUE THREAD

**Issue by VinSpee** [vercel/next.js#10219] opened 2020-01-22 21:23 UTC
# Bug report

## Describe the bug

When importing a file from `_app.tsx`, an error is thrown and the page fails to render

>index.js:1 Error was not caught TypeError: Cannot read property 'parentNode' of null
>    at Object.push../src/pages/font.css.options.insert (font.css?2cd5:11)
>    at insertStyleElement (injectStylesIntoStyleTag.js:122)
>    at addStyle (injectStylesIntoStyleTag.js:219)
>    at addStylesToDom (injectStylesIntoStyleTag.js:94)
>    at push../node_modules/style->loader/dist/runtime/injectStylesIntoStyleTag.js.module.exports (injectStylesIntoStyleTag.js:251)
>    at Object../src/pages/font.css (font.css?2cd5:26)
>    at __webpack_require__ (bootstrap:792)
>    at fn (bootstrap:150)
>    at Module../src/pages/_app.tsx (with-apollo.tsx:36)
>    at __webpack_require__ (bootstrap:792)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

a relatively simple `_app.js`:

```tsx
import * as React from 'react';
import { Global } from '@emotion/core';
import { Monterey } from '@tedconf/monterey';
import App from 'next/app';
import { ApolloProvider } from '@apollo/react-hooks';
import { I18nProvider } from '@lingui/react';
import objectFitImages from 'object-fit-images';
import withApollo from '../lib/with-apollo';
import './font.css';

const catalogEN = require('../locales/en/messages.po');

class MyApp extends App<{ apollo: any }> {
  componentDidMount() {
    objectFitImages();
  }

  render() {
    const { Component, pageProps, apollo } = this.props;

    return (
      <I18nProvider language="en" catalogs={{ en: catalogEN }}>
        <ApolloProvider client={apollo}>
          <link rel="icon" href="/favicon.ico" />
          <Global
            styles={{
              html: {
                fontFamily: 'Inter, sans-serif',
              },
            }}
          />
          <Monterey>
            <Component {...pageProps} />
          </Monterey>
        </ApolloProvider>
      </I18nProvider>
    );
  }
}

export default withApollo(MyApp);
```

and a simple css file:

```css
@font-face {
  font-family: 'Inter';
  font-weight: 100 900;
  font-style: normal;
  font-named-instance: 'Regular';
  font-display: swap;
  src: url('/fonts/inter-upright.var.woff2') format('woff2');
}
@font-face {
  font-family: 'Inter';
  font-weight: 100 900;
  font-style: italic;
  font-named-instance: 'Italic';
  font-display: swap;
  src: url('/fonts/inter-italic.var.woff2') format('woff2');
}
body {
  font-variant-ligatures: normal;
}
```

## Expected behavior

The CSS should load or the error should be caught and decipherable

## System information

- OS: macOS
- Browser (if applies) chrome
- Version of Next.js: 9.0.2

## Additional context

Just tried to switch from `withCSS`.

**Comment by alejalapeno** [comment] 2020-01-22 21:40
This is caused by placing the CSS file inside the `/pages` directory. Moving it outside the directory should fix the error, but I agree an error message about stylesheets in the directory should exist or changing the build process to allow co-locating stylesheets with `_app.js`.

**Comment by VinSpee** [comment] 2020-01-23 19:50
Thanks for the idea. I tried moving `src/pages/font.css` to `src/components/font.css` and I am still getting the same result.

Anything else that could be causing it?

**Comment by Timer** [comment] 2020-01-23 20:20
CSS files are supported in the `pages/` directory—there's no problem there.

Can you please share a reproducible demo project?

**Comment by PJijin** [comment] 2020-01-31 12:24
@VinSpee Have you found any solution? I have got this error now.

**Comment by VinSpee** [comment] 2020-01-31 13:27
@PJijin I have not found a solution, I just switched back to `next-css` for now. I haven’t had time to get a minimal reproducible case together

**Comment by Zhekazt** [comment] 2020-04-12 16:54
if you use custom  _document.js   try to add <Head / >  component like this

**Comment by nabettu** [comment] 2020-05-05 05:56
@Zhekazt thanks! 
same problem was fixed with your code

**Comment by Temkit** [comment] 2020-08-08 13:23
sale error here !!!

Cannot read property 'parentNode' of null when importing css from _app.js

**Comment by Timer** [comment] 2020-08-12 20:53
Next.js needs to warn when your custom document doesn't return the proper `<Head />` component!

**Comment by Temkit** [comment] 2020-08-14 19:56
thanks @Timer your answer makes me delete the _document page and no more error !

**Closed** 2020-08-24 02:42 UTC
Labels: kind: story, point: 3

**Comment by business-helper** [comment] 2021-01-10 20:53
Thanks, @Timer, @Temkit!
I had the same issue, deleted the **_document** page, and instead moved the content in **<Head></Head>** to the **_app** page;

**Comment by balazsorban44** [comment] 2022-01-28 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
