### ISSUE TITLE
Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by moaazbhnas228** [vercel/next.js#53470] opened 2023-08-02 06:55 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13-canary.9
      eslint-config-next: 13.4.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.8.2
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/moaazbhnas228/url-issue-reproduction

### To Reproduce

1. `npm install`
2. `npm run dev`
3. Go to home page
4. Click on the "logo" link

<img width="195" alt="image" src="https://github.com/vercel/next.js/assets/111786023/23040937-2d9e-43d2-88e4-55b23d79274c">

### Describe the Bug

The error occurred when a customer clicked on a normal `<Link href="/" />` component.
Our monitor shows that the error occurred in this line:
```
const { pathname , searchParams , search , hash , href , origin  } = new URL(url, resolvedBase);
```
When I examined the code, I guess the issue is in `resolvedPath`.
```
const resolvedBase = base ? new URL(base, globalBase) : url.startsWith(".") ? new URL(typeof window === "undefined" ? "http://n" : window.location.href) : globalBase;
```
And since there's no `base` passed in `href="/"` and the environment is browser, `resolvedPath = globalBase`
I'm not sure whether any of this useful, but that was my attempt 😅.

![image](https://github.com/vercel/next.js/assets/111786023/31b8bae3-bb85-4598-a51f-c16ab9c7fd43)

### Expected Behavior

The link works with no issues.

### Which browser are you using? (if relevant)

Chrome Mobile Version:115.0.0

### How are you deploying your application? (if relevant)

Vercel

**Comment by balazsorban44** [comment] 2023-08-02 10:02
Hi, given the reproduction, I could not reproduce this issue. I'll close the issue for now, but let us know if this is recurring or if you are able to reproduce this reliably by opening a new issue, thanks!

**Closed by balazsorban44** 2023-08-02 10:02 UTC
Labels: template: bug, area: Routing
