### ISSUE TITLE
An error occurred in `next/font`.

### ISSUE THREAD

**Issue by Ajay01103** [vercel/next.js#64393] opened 2024-04-12 10:50 UTC
### Link to the code that reproduces this issue

https://github.com/Ajay01103/Next-14.2.0

### To Reproduce

1). start the the local development server
2). An error occurred in `next/font`.

### Current vs. Expected behavior

I was trying the latest version of next js 14.2.0 after the installation finished and run the local development server the error appear which is like 

An error occurred in `next/font`.
inside src\app\layout.tsx

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

![image](https://github.com/vercel/next.js/assets/125455606/559109db-d5d3-40a1-a329-875f1a5c3c92)

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home Single Language
  Available memory (MB): 15732
  Available CPU cores: 12
Binaries:
  Node: 20.12.1
  npm: N/A
  Yarn: N/A
  pnpm: 8.15.6
Relevant Packages:
  next: 14.2.0 // Latest available version is detected (14.2.0).
  eslint-config-next: 14.2.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, CLI (create-next-app)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

### Additional context

I tested the next js 14.1.4 it just worked fine bu the latest version of next js 14.2.0 is throwing the error inside src\app\layout.tsx

![image](https://github.com/vercel/next.js/assets/125455606/cc46eb45-d41c-4d18-bd90-41f6523af51d)
![image](https://github.com/vercel/next.js/assets/125455606/90980b60-1d21-4e5c-831f-266998f07de4)

**Comment by AtharvaChobe** [comment] 2024-04-12 11:00
Yes, I am also getting that same error

**Comment by maliksynt** [comment] 2024-04-12 12:26
i'm getting it too lmaooo, waiting for a fix

**Comment by ElironB** [comment] 2024-04-12 12:34
Also getting it

**Comment by Thanaen** [comment] 2024-04-12 12:34
Duplicate of https://github.com/vercel/next.js/issues/64371

**Comment by maliksynt** [comment] 2024-04-12 12:39
> Duplicate of #64371

thanks ! it worked

**Comment by timneutkens** [comment] 2024-04-12 13:36
Closing as duplicate of #64371

**Closed by timneutkens** 2024-04-12 13:36 UTC
Labels: area: create-next-app, template: bug

**Comment by wagstalos** [comment] 2024-04-12 18:15
https://nextjs.org/docs/messages/built-in-next-font
