### ISSUE TITLE
Lint issue _middleware

### ISSUE THREAD

**Issue by humble-barnacle001** [vercel/next.js#33104] opened 2022-01-08 13:08 UTC
### Run `next info` (available from version 12.0.8 and up)

```bash
$ npx next info
/bin/sh: 1: pnpm: not found

    Operating System:
      Platform: linux
      Arch: x64
      Version: #8-Ubuntu SMP Thu Nov 11 10:05:41 UTC 2021
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.8-canary.19
      react: 17.0.2
      react-dom: 17.0.2
```

### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

v16.13.0

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

Linux

### How are you deploying your application?

Vercel

### Describe the Bug

`npm run lint` gives me an error
```

./pages/api/getUpdates/_middleware.ts
1:1  Error: next/server should not be imported outside of pages/_middleware.js. See https://nextjs.org/docs/messages/no-server-import-in-page.  @next/next/no-server-import-in-page

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
```

### Expected Behavior

This should not be a lint issue since the `_middleware.ts` is inside `pages` folder

### To Reproduce

- Create `_middleware.ts` in `pages/api/`
- Write the line `import { NextRequest, NextResponse } from "next/server";` for typescript type checking
- Copy the code from here: https://github.com/vercel/examples/blob/main/edge-functions/basic-auth-password/pages/_middleware.ts
- Run `npm run lint`

**Comment by balazsorban44** [comment] 2022-01-09 10:38
This has been fixed on `canary` either upgrade or wait for it to make to `latest`

Make sure you also update `next-eslint-config`

**Closed by balazsorban44** 2022-01-09 10:38 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-02-08 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
