### ISSUE TITLE
Add a `.gitignore` to examples missing it.

### ISSUE THREAD

**Issue by lfades** [vercel/next.js#15102] opened 2020-07-12 18:56 UTC
Many examples don't currently include a `.gitignore`, which is fine when using `create-next-app`, but it will cause the example to not have it by other means, like a manual download or using the deploy to Vercel button.

The `.gitignore` file should look like this:

```ignore
# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# dependencies
/node_modules

# testing
/coverage

# Next.js
/.next/
/out/

# production
/build

# misc
.DS_Store

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env.local
.env.development.local
.env.test.local
.env.production.local

# Vercel
.vercel
```

If the example has other files that need to be ignored, feel free to add them. And if the example already has a `.gitignore` that's not ignoring the files listed above, updates to it are also welcome!

**Comment by amorriscode** [comment] 2020-07-12 20:13
I'd be willing to tackle this over the course of the next week!

**Comment by tanmaylaud** [comment] 2020-07-13 15:03
Hi I have an [open PR](https://github.com/vercel/next.js/pull/15127) for this issue

**Comment by amorriscode** [comment] 2020-07-13 15:56
@tanmaylaud I noticed you didn't do all the examples. Do you intend to continue the work on this ticket?

**Comment by tanmaylaud** [comment] 2020-07-13 16:14
> @tanmaylaud I noticed you didn't do all the examples. Do you intend to continue the work on this ticket?

@amorriscode I considered the examples with vercel deployment. Is gitignore required for all the examples?

**Comment by amorriscode** [comment] 2020-07-13 16:16
@tanmaylaud based on my interpretation of the issue, I think they should all have them. If someone manually downloads the examples, for instance, they will want the `.gitignore`.

I had claimed this issue but you got to it before me. If you want to keep going with the rest of the examples that would probably be useful!

**Comment by tanmaylaud** [comment] 2020-07-13 16:19
> @tanmaylaud based on my interpretation of the issue, I think they should all have them. If someone manually downloads the examples, for instance, they will want the `.gitignore`.
> 
> I had claimed this issue but you got to it before me. If you want to keep going with the rest of the examples that would probably be useful!

@amorriscode , sorry for claiming it. I saw that you already are an active contributor to nextjs whereas I am trying to start. 
Regarding the issue, I thought I should wait for a reviewer to comment/clarify before I add gitignore to all files. I have done the bare minimum for now.

**Comment by Timer** [comment] 2020-07-13 18:30
Every single example needs the `.gitignore` added or merged with its existing one!

**Comment by tanmaylaud** [comment] 2020-07-13 18:42
@Timer  I will add/merge gitignore to all the examples. Regarding the script,  could you please provide more clarity about the requirement? Thanks!

**Closed** 2020-07-16 14:52 UTC
Labels: good first issue, kind: story, point: 2, type: example

**Comment by balazsorban44** [comment] 2022-01-29 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
