### ISSUE TITLE
Serverless Trace build shouldn't rely on the client build

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#8253] opened 2019-08-05 19:08 UTC
Right now, producing a serverless/serverless-trace build relies on the client build.

Is there a way to get rid of this requirement? We should investigate.

We should be able to for at least trace mode.

https://github.com/zeit/next.js/blob/f40a90159b8dd92f45240f90239b0f860f943e71/packages/next/build/index.ts#L202

**Comment by timneutkens** [comment] 2019-08-06 13:07
We need to have the build manifest for client-side builds because of `next/dynamic` needing to know the rendered modules etc.

**Comment by Timer** [comment] 2020-06-06 06:55
@devknoll do you think this is in-scope of your serverless changes?

**Comment by timneutkens** [comment] 2021-01-08 09:10
Closing as this change is no longer needed.

**Closed by timneutkens** 2021-01-08 09:10 UTC
Labels: kind: story, point: 5, priority: stretch

**Comment by balazsorban44** [comment] 2022-01-28 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
