### ISSUE TITLE
navigating to unknown routes when basePath is defined and not-found.tsx defined in production builds gives "Internal Server Error" message

### ISSUE THREAD

**Issue by timredband** [vercel/next.js#54447] opened 2023-08-23 14:42 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 18.9.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.20-canary.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/timredband/base-path-not-found-issue

### To Reproduce

Steps to replicate:

Define `basePath` in the `next.config.js` file.

Add a `not-found.tsx` file.

Serve the app in production mode.

```bash
npm ci
npm run build
npm start
```

Navigate to any path other than `/foo/bar` and you will get an "Internal Server Error" message.

### Describe the Bug

When `basePath` is defined and have a not found fallback defined and running next in production mode and navigate to an unknown route you will get an "Internal Server Error" message. 

### Expected Behavior

Expect the not found fallback page to be rendered.

### Which browser are you using? (if relevant)

Chrome 116.0.5845.97 (Official Build) (64-bit)

**Comment by huozhi** [comment] 2023-08-23 15:08
Close as duplicate of #53126, let's track there

**Closed by huozhi** 2023-08-23 15:08 UTC
Labels: template: bug
