### ISSUE TITLE
redirects config vs prefetch

### ISSUE THREAD

**Issue by vanandmkrtchyan** [vercel/next.js#24468] opened 2021-04-26 12:15 UTC
### What example does this report relate to?

next.config.js - redirects

### What version of Next.js are you using?

10.0.6

### What version of Node.js are you using?

14.15.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

this is my redirects config:

```javascript
redirects: () => [
  {
    source: '/company-history/',
    destination: '/about/',
  }
]
```

And have for example a page which is linked by `Link` 

```javascript
<Link href={'/company-history/'}>
   <a>About Us</a>
<Link>
```

### Expected Behavior

When I'm clicking on that link, I'm getting to `/company-history/` but should be redirected to `'/about/'`

### To Reproduce

click to:
```javascript
<Link href={'/company-history/'}>
   <a>About Us</a>
<Link>
```

then reload the page, and you are now redirected...

**Comment by ijjk** [comment] 2021-04-28 00:45
Duplicate of https://github.com/vercel/next.js/issues/16928

**Closed by ijjk** 2021-04-28 00:45 UTC
Labels: template: bug, type: example

**Comment by balazsorban44** [comment] 2022-01-28 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
