### ISSUE TITLE
context.req is missing in getStaticProps

### ISSUE THREAD

**Issue by EvHaus** [vercel/next.js#16500] opened 2020-08-23 21:08 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

For my website I've built up some APIs via `/pages/api` for the various data fetching needs that my application has. Sometimes I want to hit those endpoints via the client, and other times via the server, and often at build time using `getStaticProps`. Unfortunately, at the moment I cannot call those API methods from the `getStaticProps` method.

My initial instinct was to try:

```js
export const getStaticProps = async () => {
    const data = await fetch('/api/mydata');
}
```

But that gives me `TypeError: Only absolute URLs are supported`. It makes sense because you must provide a hostname to `fetch()` when it's run at build time. How do I give it the hostname of whatever the current server is (localhost during development, but my production server on production)... Not sure.

## Describe the solution you'd like

Ideally I could use the code above to fetch data from my API inside `getStaticProps`. Or alternatively, if `context.req` was exposed in `getStaticProps` then I could do something like this to figure out my current hostname:

```js
# This doesn't work.
export const getStaticProps = async (context) => {
    const data = await fetch(context.req.headers.host + '/api/mydata');
}
```

However the above code doesn't work because `context.req` doesn't exist when using `getStaticProps`.

## Describe alternatives you've considered

For now, I've had to go with something like this:

```js
export const getStaticProps = async (context) => {
    const URL = process.env.NODE_ENV === 'production' ? 'https://mydeployedsite.com' : 'http://localhost:3000';
    const data = await fetch(URL + '/api/mydata');
}
```

**Comment by Timer** [comment] 2020-08-24 01:34
Get static props should not be calling your API via `fetch`. It should be directly importing the API code and running it itself.

In nature, it's not possible for a static page to have a request—it's static. I'll close this issue because of that!

**Closed by Timer** 2020-08-24 01:34 UTC

**Comment by EvHaus** [comment] 2020-08-24 02:22
@Timer Thanks for the feedback, but how can `getStaticProps` call my API when the input to the API requires `req` and `res` params?

[As per the Next.js docs](https://nextjs.org/docs/api-routes/introduction), a typical API endpoint looks like this:

```
export default (req, res) => {
  res.statusCode = 200
  res.setHeader('Content-Type', 'application/json')
  res.end(JSON.stringify({ name: 'John Doe' }))
}
```

In order to call it I need to pass those values in. How can I pass the `req` and `res` values into that method if `getStaticProps` doesn't expose them to me?

**Comment by Timer** [comment] 2020-08-24 03:12
You can refactor your API endpoint into a `getData` method and just the `req/res` wrapper!

**Comment by 0x6a68** [comment] 2020-10-13 15:24
@Timer IMO this documentation leads to the same confusion; https://swr.vercel.app/docs/with-nextjs#pre-rendering

**Comment by MaximeBernard** [comment] 2021-05-19 14:52
@Timer Just got here for the exact same reason @0x6a68 is referring.

Documentation is quite misleading: they give one example we're not supposed to use but no example of how to really use it 😅 

Maybe adding a proper example in https://nextjs.org/docs/basic-features/data-fetching#swr
with both `getServerSideProps` and `usrSWR` would be nice :)

**Comment by Sylvenas** [comment] 2021-12-07 02:22
> `getStaticProps` should not be calling your API via `fetch`. It should be directly importing the API code and running it itself.
> 
> By nature, it's not possible for a static page to have a request—it's static. I'll close this issue because of that!

`getStaticProps` is not static in the ISR scenario, at runtime, it will still be called, at this time, I need to know the current host, a very common scenario, in the test environment server (page url:  `https://test.xxx.com/data/1`), I need to call `test.api.com/api/data/list`, and in the online environment (page url: `https://xxx.com/data/1`) I need to call `prod.api. com/api/data/list`, if I can't get the `host` in `getStaticProps`, I won't be able to distinguish between the two environments

**Comment by balazsorban44** [comment] 2022-01-27 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
