### ISSUE TITLE
Support ESM

### ISSUE THREAD

**Issue by jasonkuhrt** [vercel/next.js#47552] opened 2023-03-27 01:02 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.19.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.11.0
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

TypeScript

### Link to the code that reproduces this issue

N/A

### To Reproduce

Make app be ESM:

1. `"type": "module",` in `package.json`
2. `"module": "NodeNext",` in `tsconfig.json`
3. `"moduleResolution": "nodenext",` in `tsconfig.json`

Watch imports from e.g. `next/head` fail.

### Describe the Bug

Next.js is not an ESM package.

### Expected Behavior

Next.js should be an ESM package.

### Which browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

N/A

<sub>[NEXT-2389](https://linear.app/vercel/issue/NEXT-2389/support-esm)</sub>

**Comment by samcx** [comment] 2023-03-27 02:35
Did you update your `next.config.js` to `next.config.cjs`?

**Comment by jasonkuhrt** [comment] 2023-03-27 12:47
@samcx No, I'm not sure how that is relevant. Looking in the source code, one can see `exports` aren't used.

**Comment by balazsorban44** [comment] 2024-02-07 13:14
I can confirm this. here is a repro: https://github.com/vercel/next.js/issues/47552

I took at stab at it in https://github.com/vercel/next.js/pull/61525 but as expected, it broke a lot of things. I'll see how we can tackle this more incrementally.

**Comment by karlhorky** [comment] 2024-09-18 15:33
@balazsorban44 @samcx is this a duplicate of this other issue over here?

- https://github.com/vercel/next.js/issues/46078

(the other issue has more upvotes and also a different PR https://github.com/vercel/next.js/pull/50357 from @lucgagan which aims to resolve it)

If yes, then these internal Linear tracking numbers are also duplicates:

- [NEXT-2389](https://linear.app/vercel/issue/NEXT-2389/support-esm) (this current issue)
- [NEXT-779](https://linear.app/vercel/issue/NEXT-779/next-typescript-cannot-find-module-when-moduleresolution=nodenext-and) (issue 46078)

**Comment by samcx** [comment] 2024-09-19 22:19
@karlhorky That seems so, let's close this one and keep the older one.

**Closed by samcx** 2024-09-19 22:19 UTC
Labels: bug, TypeScript, linear: next
