### ISSUE TITLE
Cannot read property 'name' of undefined with <style {...props}/>

### ISSUE THREAD

**Issue by Fi1osof** [vercel/next.js#21862] opened 2021-02-04 10:46 UTC
**What version of Next.js are you using?**

10.0.6

**What version of Node.js are you using?**

15.6.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Ubuntu 20

**How are you deploying your application?**

next start

**Describe the Bug**

style tag with any degradation causes error.

Example (used pure next-js):
```jsx

export default function Home() {

  const styleProps = {
    id: "test"
  };

  return (
    <div >
      <p>Hello World</p>
      <style
        {...styleProps}
      />
    </div>
  )
}

```

```
react_devtools_backend.js:2430 ./pages/index.js
TypeError:  /www/next.js/next.js/examples/basic-css/pages/index.js: Cannot read property 'name' of undefined
    at Array.some (<anonymous>)
    at Array.filter (<anonymous>)
overrideMethod	@	react_devtools_backend.js:2430
handleErrors	@	hot-dev-client.js?647e:162
processMessage	@	hot-dev-client.js?647e:208
eval	@	hot-dev-client.js?647e:54
eval	@	eventsource.js?9b42:39
handleMessage	@	eventsource.js?9b42:37

```

This error causes only when:
1. style tag
Any other tags - OK. Style middleware?
2. uses degradation {...}
```
<style prop={propValue} prop2={prop2Value} /> - OK
```

**Expected Behavior**

Render style tag with props.

**To Reproduce**

Add <style {...{}}/> anywhere.

UPD: my workaround:
```
const style = React.createElement(
      "style",
      {
        ...otherProps,
        dangerouslySetInnerHTML: "body {color: black;}",
      },
    )

...
<div>
 {style}
</div>
```

**Comment by balazsorban44** [comment] 2021-12-22 02:38
Could not reproduce anymore. Probably fixed in a later version.

**Closed by balazsorban44** 2021-12-22 02:38 UTC
Labels: template: bug
