### ISSUE TITLE
`onLoadingComplete()` should pass `naturalWidth` and `naturalHeight`

### ISSUE THREAD

**Issue by nickadamson** [vercel/next.js#27213] opened 2021-07-15 23:35 UTC
### What version of Next.js are you using?

11.0.2-canary.16

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Brave (Chromium)

### What operating system are you using?

Windows

### How are you deploying your application?

next dev

### Describe the Bug

onLoadingComplete() event handler does not pass any props.

### Expected Behavior

The expected behavior for onLoadingComplete (unless I'm missing the point of this prop) is the same as onLoad for regular old HTML <img> and onLoadedMetadata/onCanPlay for videos -- a synthetic react event with .target prop.

### To Reproduce

I have a function/event handler that calculates the aspect ratio of an image as soon as it is loaded:
```
const calcAspectRatio = (loadedMedia) => {

      console.log("loadedMedia", loadedMedia)

      let ratio;

      let width;

      let height; // ... you get the idea. bug can be replicated with a simple console.log though. 
```
Here's how I've implemented next/image:
```
<Image layout="fill" src={media} onLoadingComplete={calcAspectRatio} />
```
and videos:
```
<video muted autoPlay={autoPlay} loop onLoadedMetadata={calcAspectRatio}>
    <source src={media} />
</video>
```
Currently the calcAspectRatio **returns `undefined` for next/image - afaiu, this would mean it doesn't pass any reference to itself when loading is complete**

And returns this (expected) for video:
```
SyntheticBaseEvent {_reactName: "onLoadedMetadata", _targetInst: null, type: "loadedmetadata", nativeEvent: Event, target: video.nfte__media-content, …}
```
![buggitybugbug](https://user-images.githubusercontent.com/80008674/125869564-ccbe990a-db70-4efa-b7cf-1e7b7965329e.PNG)

**Comment by nickadamson** [comment] 2021-07-15 23:37
see https://github.com/vercel/next.js/discussions/27152 also

**Comment by brc-dd** [comment] 2021-07-17 12:56
For me using `onLoadingComplete` is throwing the following error on console:

```
Warning: Unknown event handler property `onLoadingComplete`. It will be ignored.
```

**Comment by leerob** [comment] 2021-07-23 02:07
^ Locked https://github.com/vercel/next.js/discussions/27152 and moved the discussion here.

**Comment by botv** [comment] 2021-07-23 02:08
This has been fixed in canary.

**Comment by styfle** [comment] 2021-07-27 14:46
You'll need to updated to the latest canary to get `onLoadingComplete()` prop https://github.com/vercel/next.js/issues/18398#issuecomment-872604823

We are not providing the ref/element at this time because it would be too easy to break the component if you had raw access to the underlying image, for example changing inline styles.

In your example where you use `calcAspectRatio()`, what does the aspect ratio get used for? The component should handle its own aspect ratio.

**Comment by nickadamson** [comment] 2021-07-29 06:31
@styfle `calcAspectRatio()` takes the width and height of original image, calculates the aspect ratio (as well as portrait/landscape orientation) and sets state to `${orientation} ${aspect-ratio}`. The state is used in a className, which tells the div how many grid columns/rows to span. 

Basically a messy, dense gallery grid from a stream of photos outside of my control.

**Comment by styfle** [comment] 2021-07-29 15:53
You can find the width & height from the parent element since `layout=fill` will fill to the dimensions of the parent.

For example, this parent div is 300x500 so the image will also be 300x500.

https://github.com/vercel/next.js/blob/f5ee9ed5afde314f6554e5670176416220f4fe47/examples/image-component/pages/layout-fill.js#L9-L11

Demo: https://image-component.nextjs.gallery/layout-fill

**Comment by nickadamson** [comment] 2021-07-29 18:10
@styfle yeah, I get that, and honestly I might be expecting too much from next/image. But basically I'm setting the width and height of parent element *after* image is loaded.

\> Have grid with auto columns at 10px wide
\> Image URI's are fetched from API
\> For each image URI -> create hidden div with child <Image/img>
\> Once image is loaded -> determine its aspect ratio 
\> change hidden div to div with aspect ratio of image 
\> for example, css classes for 'portrait 2x3' : grid-column-span 20, grid-row-span 30

<details>
<summary>This is the look I'm trying to achieve </summary>
![image](https://user-images.githubusercontent.com/80008674/127542339-d445b6db-a6f6-4431-a278-92d8b84ab8a2.png)
</details>

I could show everything as squares, but the site is for artists and I'd like to respect their creative decisions, like composition.
Honestly if there was a way to get image's metadata over HTTP that would be amazing, but I haven't found a simpler way to do this and I've been tackling this problem for at least a month now.
I'd really like to use next/image as some of the content that gets pulled is ridiculously large 8000px width files. GPU usage can be 50% on my machine depending on what's been published recently. And that's only with 12 items loaded. If next/image allowed the ref the function would be able to run.

Also, if next/image just had a fileAspectRatio prop that could work I think, but I don't know what I'm talking about in regards to image optimization.

**Comment by styfle** [comment] 2021-07-29 19:36
If `onLoadingComplete()` passed back [`naturalWidth`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/naturalWidth) and [`naturalHeight`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/naturalHeight), would that solve the problem?

**Comment by nickadamson** [comment] 2021-07-30 23:40
@styfle 100% yes, it would. I was unaware of those properties.

**Closed** 2021-08-02 23:14 UTC
Labels: kind: story

**Comment by balazsorban44** [comment] 2022-01-28 01:27
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
