### ISSUE TITLE
Problem with css modules when one component using several times in one page

### ISSUE THREAD

**Issue by adFedorovich** [vercel/next.js#14766] opened 2020-07-01 11:40 UTC
# Bug report

## Problem with css modules when one component using several times in one page

When one component used several times in one page, in chrome dev tools we can see that styles was generated several times also (only for production mode)

## To Reproduce

1. Use css-modules
2. Use one component several times per page

## Expected behavior

css generated only one time, like for development mode

## Screenshots
<img width="284" alt="Screen Shot 2020-07-01 at 2 32 00 PM" src="https://user-images.githubusercontent.com/15676325/86239520-26518d00-bba8-11ea-9fe2-2152ceb3d1c8.png">

## System information

- OS: [macOS]
- all
- Version of Next.js: 9
- Version of Node.js: 10

**Comment by adFedorovich** [comment] 2020-07-01 11:49
Found the same issue: https://github.com/vercel/next.js/issues/11448. Hope my details can help to fix it

**Comment by timneutkens** [comment] 2020-07-01 12:13
Duplicate of #11448

**Closed by timneutkens** 2020-07-01 12:13 UTC

**Comment by balazsorban44** [comment] 2022-01-29 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
