### ISSUE TITLE
Uncaught errors in getServerSideProps is uncaught.

### ISSUE THREAD

**Issue by rhapsodyn** [vercel/next.js#13331] opened 2020-05-25 07:14 UTC
# Feature request

##  Is your feature request related to a problem? Please describe.

During development, Uncaught error in some page's `getServerSideProps` will response with http-200-OK. 

In contrast, after build, the page will response with 500 (or using _error.js) in production, as expected. 

```javascript
// pages/index.js
export default function Index() {
  // while this leads to http 500 err
  // throw new Error('client err')
  return (
    <div>
      <p>Hello Next.js</p>
    </div>
  )
}

export async function getServerSideProps() {
  // response with 200 but a empty document
  throw new Error('server err')
  return { props: {} }
}
```

After reading some source code, found that the only way i can "programmable catch" this error was: 

```javascript
// pages/_document.js
import Document, { Html, Head, Main, NextScript } from 'next/document'

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    console.log('MAGIC! ', ctx.err);
    const initialProps = await Document.getInitialProps(ctx)
    return { ...initialProps }
  }

  render() {
    return (
      <Html>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument
```

But at that time, i can hardly handle the error properly.

## Describe the solution you'd like

Some `App.onServerSideError`?

**Comment by SwarajGK** [comment] 2021-12-21 17:42
Tried with the latest `Next.js` module, it is throwing me error on dev server only,
Have you tried it with the latest version and if it still happening can you please provide a working demo of it. Will be great.

```
import dynamic from "next/dynamic";

export default function Home() {
  const DynamicComponent = dynamic(import("../components/Test"));
  return (
    <div>
      <p>Hello World</p>
      <DynamicComponent />
    </div>
  );
}

export async function getServerSideProps() {
  // response with 200 but a empty document
  const data = await fetch("http://localhost:3000/api/test");
  if (data.status === 500) {
    throw new Error("This is the server error");
  }
  return {
    props: {},
  };
}
```
![Screenshot 2021-12-21 at 11 08 44 PM](https://user-images.githubusercontent.com/52201115/146974461-e3068011-fbe2-4cf1-bc4a-c6e17794e64e.png)

**Comment by SwarajG** [comment] 2021-12-21 17:45
Tried with the latest `Next.js` module, it is throwing me error on dev server only,
Have you tried it with the latest version and if it still happening can you please provide a working demo of it. Will be great.

```
import dynamic from "next/dynamic";

export default function Home() {
  const DynamicComponent = dynamic(import("../components/Test"));
  return (
    <div>
      <p>Hello World</p>
      <DynamicComponent />
    </div>
  );
}

export async function getServerSideProps() {
  // response with 200 but a empty document
  const data = await fetch("http://localhost:3000/api/test");
  if (data.status === 500) {
    throw new Error("This is the server error");
  }
  return {
    props: {},
  };
}
```
![Screenshot 2021-12-21 at 11 08 44 PM](https://user-images.githubusercontent.com/52201115/146974461-e3068011-fbe2-4cf1-bc4a-c6e17794e64e.png)

**Comment by balazsorban44** [comment] 2021-12-21 23:19
Indeed, this has been fixed in a later version.

**Closed by balazsorban44** 2021-12-21 23:19 UTC
Labels: kind: bug, good first issue, area: Routing

**Comment by balazsorban44** [comment] 2022-01-27 02:14
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
