### ISSUE TITLE
Next.js cannot compile with turbo when lowlight is used 

### ISSUE THREAD

**Issue by kalvin807** [vercel/next.js#65106] opened 2024-04-27 07:46 UTC
### Link to the code that reproduces this issue

~https://codesandbox.io/p/devbox/blazing-wood-go8s7s?file=%2Fapp%2Fpage.tsx%3A3%2C10~
https://codesandbox.io/p/devbox/old-resonance-lv6j3x

### To Reproduce

1. Follow instruction to install [lowlight](https://github.com/wooorm/lowlight) 
2. Register a syntax highlight
```javascript
import {createLowlight} from 'lowlight'
import xml from 'highlight.js/lib/languages/xml'

const lowlight = createLowlight()

lowlight.register({xml})

// Note: `html` is an alias for `xml`.
console.log(lowlight.highlight('html', '<em>Emphasis</em>'))
```
3. Start dev server with turbo (`--turbo` defined in package.json) `npm run dev`
4. Server crashes with error `Failed to compile`
```
Module not found: Can't resolve 'highlight.js/lib/languages/typescript'
> 1 | import typescript from 'highlight.js/lib/languages/typescript'
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 | import {common, createLowlight} from 'lowlight'
  3 |
  4 | const lowlight = createLowlight()
```

### Current vs. Expected behavior

I expect it compile without error, because it works correctly when dev server is run without turbopack (without `--turbo` flag). But it is currently failing with module not found. I noticed `--turbo` works if I include `highlight.js` as dependency.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.3.0-canary.26 // There is a newer canary version (14.3.0-canary.28) available, please upgrade! 
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
 ⚠ There is a newer canary version (14.3.0-canary.28) available, please upgrade! 
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

The mvp is based on the instruction of MantineRichEditor Example:
https://mantine.dev/x/tiptap/#code-highlight

<sub>[PACK-3017](https://linear.app/vercel/issue/PACK-3017/nextjs-cannot-compile-with-turbo-when-lowlight-is-used)</sub>

**Comment by timneutkens** [comment] 2024-04-27 14:51
Seems you've copy-pasted the sandbox and didn't add any code into it, in the future please double check that the provided reproduction actually reproduces the issue.

**Comment by timneutkens** [comment] 2024-04-27 14:58
Here's a sandbox of the reproduction steps working fine on `next@latest`: https://codesandbox.io/p/devbox/sleepy-bassi-stw4yq?file=%2Fapp%2Fpage.tsx%3A7%2C1&workspaceId=062b139a-c054-40fe-bbf5-0210d48b9dd0. Also verified `next@canary`.

**Comment by kalvin807** [comment] 2024-04-27 15:12
Sorry for the wrong code sandbox link.
Here is the updated one: https://codesandbox.io/p/devbox/old-resonance-lv6j3x
The reproduction steps only working fine if `highlight.js` is specified as dependencies in `package.json`. 

Without adding `highlight.js` in package.json. `highlight.js` is still installed in node_module and resolved in lockfile. `next dev --turbo` will fail to compile, but `next dev` can.

**Comment by timneutkens** [comment] 2024-04-27 19:13
Thank for the reproduction! Was able to figure out what the problem is based on that.

So the problem is that webpack resolving in this particular case is incorrect, it allows you to import modules from a place that your application code shouldn't have access to, namely the node_modules of a nested dependency. Turbopack has a more correct resolving that matches closer to what Node.js does. If you try running the Node.js repl you'll notice that `import('highlight.js/lib/languages/typescript')`

Looking at the docs for the package you'll want to do something like this instead as lowlight includes the highlight.js data:

```js
import { createLowlight, common } from "lowlight";

const lowlight = createLowlight();
lowlight.register({ typescript: common.typescript });
```

Lowlight also exports `all` for all of the languages, keep in mind those are all bundled, best to keep them in a server component.

**Closed by timneutkens** 2024-04-27 19:13 UTC
Labels: bug, Turbopack, linear: turbopack
