### ISSUE TITLE
Custom pages directory

### ISSUE THREAD

**Issue by PepijnSenders** [vercel/next.js#13540] opened 2020-05-29 09:23 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I'm vouching for the case of supplying a custom path for where the `pages` live. Currently, this is not configurable and it's either, [`./pages` or `./src/pages`](https://github.com/vercel/next.js/blob/canary/packages/next/lib/find-pages-dir.ts#L13). Usually this is not necessary, but I have one use case for it where this feature would come in very handy.

Say you have a couple of websites, all with very similar complex components, yet sometimes they diverge and you need a different page layout or some different modules. We have all the complexity of the modules hidden inside the modules folder and the pages are just simple collections of a layout and the imported modules. When we want one of these websites to diverge we'll end up adding complexity to the page, or we'll be adding a new page that is not necessary for the other websites. Following a CAC approach, it would be great to have a folder per website with very simple pages that connect to the modules folder and that we can compile these separately at build time.

Having different next.js apps could be a simple solution here as well, but I'd rather not duplicate the configuration of our app, I'd rather just change a very simple thing and that is changing the path to the pages folder.

## Describe the solution you'd like

A field in the `next.config.js` where you can set a custom path to your pages folder.

## Describe alternatives you've considered

An alternative could be having several next.js apps.

**Comment by timneutkens** [comment] 2020-05-29 12:02
Duplicate of https://github.com/vercel/next.js/issues/4315#issuecomment-526911472

This has been discussed very in-depth in the issue tracker already and we're not going to allow for a configuration option for this.

**Closed by timneutkens** 2020-05-29 12:02 UTC

**Comment by andormade** [comment] 2021-04-07 12:12
If you found this, while looking for a solution, there is a fork that allows you to set a custom pages directory, you can find the link in this discussion: #23640
