### ISSUE TITLE
Next 9.5.3+ breaks when building inside Electron

### ISSUE THREAD

**Issue by wscotten** [vercel/next.js#18098] opened 2020-10-21 17:58 UTC
# Bug report

## Describe the bug

Building inside Electron no longer works in Next 9.5.3+

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone the Next repository
2. `cd examples/with-electron-typescript/`
3. `yarn dist`
4. Open built dmg inside dist folder.
5. Observe none of the links work.

## Expected behavior

Next would be able to find the route files and serve them correctly.

## Screenshots
<img width="549" alt="Screen Shot 2020-10-21 at 10 55 33 AM" src="https://user-images.githubusercontent.com/24510642/96759551-0fb88700-138d-11eb-80cd-10e726f2a971.png">
<img width="737" alt="Screen Shot 2020-10-21 at 10 55 44 AM" src="https://user-images.githubusercontent.com/24510642/96759554-11824a80-138d-11eb-8dd8-985d4405a6d5.png">

## System information

- OS: [macOS]
- Browser (if applies) [Electron]
- Version of Next.js: [latest]
- Version of Node.js: [12.13.1]

**Comment by Janpot** [comment] 2020-10-21 18:08
Closing as duplicate of https://github.com/vercel/next.js/issues/16595

**Closed by Janpot** 2020-10-21 18:08 UTC

**Comment by balazsorban44** [comment] 2022-01-29 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
