### ISSUE TITLE
11.1.1 on Windows breaks Global CSS Rules

### ISSUE THREAD

**Issue by Benadato** [vercel/next.js#28636] opened 2021-08-31 03:19 UTC
### What version of Next.js are you using?

11.1.1

### What version of Node.js are you using?

14.17.5

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10 Pro 64 bit

### How are you deploying your application?

N/A

### Describe the Bug

Fresh install of Next 11.1.1, create ANY starter project and run dev.   Multiple errors including:

Global CSS cannot be imported from files other than your custom app .... 
 and
"(node:15704) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API"

Falling back to 11.1.0 fixes it.

### Expected Behavior

No error and starter projects work correctly.

### To Reproduce

Fresh install of Next 11.1.1, create ANY starter project and run dev.

**Comment by ijjk** [comment] 2021-08-31 03:28
Hi, this appears to be a duplicate of https://github.com/vercel/next.js/issues/28579 which should be resolved in `v11.1.2-canary.0` of Next.js

**Closed by ijjk** 2021-08-31 03:28 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 21:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
