### ISSUE TITLE
Client side navigation to 404 page in application using middleware leads to application crash in production mode

### ISSUE THREAD

**Issue by wiledal** [vercel/next.js#39260] opened 2022-08-02 16:39 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.4-canary.9
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

When a middleware-file exists, client side navigation does not handle 404 responses correctly, resulting in crashes and failed page upgrades after deployments.

This makes middleware unusable.

### Expected Behavior

Clicking a `notFound: true` link should show the 404 page, or the link should apply a hard navigation to the page if a new page version is available, as outlined in the Next.js documentation.

### Link to reproduction

https://github.com/wiledal/nextjs-middlwares-broken-clientside-404

### To Reproduce

The reproduction repo is simulating fetching data from an api in `getStaticProps`.

The linked repo is deployed here:
https://nextjs-middlwares-broken-clientside-404.vercel.app/

- Click `blog` (should show 404). Clientside crashes every time. `404.json` is never fetched. Instead it seems to load the 404-throwing page twice.
- Refresh page, 404 shows correctly when fetched serverside.

Removing `middleware.ts` solves the issues completely. When clicking `blog`, `blog.json` is fetched, then `404.json` is fetched and 404 is displayed accordingly.

**Comment by thienna** [comment] 2022-08-03 04:13
follow

**Comment by balazsorban44** [comment] 2022-08-03 10:09
<details>
<summary>Note @thienna</summary>
<i>you can subscribe to issue notifications:</i>
<br/>
<img src="https://user-images.githubusercontent.com/18369201/182582845-f8bec523-32dc-4cdf-b1e1-2862fd684da5.png"/>
</details>

**Comment by balazsorban44** [comment] 2022-08-03 11:50
I think this is a duplicate of #39260

**Closed** 2022-08-03 12:48 UTC
Labels: template: bug, area: Middleware, area: Routing
