### ISSUE TITLE
Typescript in custom document with NextJS 12.0.5

### ISSUE THREAD

**Issue by Gulivertx** [vercel/next.js#32118] opened 2021-12-04 11:19 UTC
### What version of Next.js are you using?

12.0.5

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome, Electron

### What operating system are you using?

macOS

### How are you deploying your application?

Docker

### Describe the Bug

From version 12.0.5 I have a typescript error in custom document.

`./pages/_document.tsx`

```
type error: Type '() => any' is not a constructor function type.

   9 | })
  10 |
> 11 | class GynemanagerDocument extends Document {
     |                                   ^
  12 |     static async getInitialProps(ctx: DocumentContext) {
  13 |         stylesheet.reset()
  14 |         resetIds()
error Command failed with exit code 1.
```

If I downgrade NextJS to 12.0.4 the error is gone.

### Expected Behavior

No typescript error :)

### To Reproduce

Create a custom document file. Here is mine :

```typescript
import Document, {Html, Head, Main, NextScript, DocumentContext} from 'next/document';
import {Stylesheet, resetIds, InjectionMode} from '@fluentui/react';

const stylesheet = Stylesheet.getInstance();

stylesheet.setConfig({
    injectionMode: InjectionMode.none,
    namespace: 'server'
})

class GynemanagerDocument extends Document {
    static async getInitialProps(ctx: DocumentContext) {
        stylesheet.reset()
        resetIds()

        const initialProps = await Document.getInitialProps(ctx)
        return {
            ...initialProps,
            styles: [initialProps.styles, <style key="fluentui-css" dangerouslySetInnerHTML={{ __html: stylesheet.getRules(true) }} />]
        }
    }

    render() {
        return (
            <Html lang="fr">
                <Head />
                <body>
                <Main />
                <NextScript />
                </body>
            </Html>
        )
    }
}

export default GynemanagerDocument
```

**Comment by andrew-koltyakov-wmg** [comment] 2021-12-04 11:34
I temporary was able to workaround it by importing from `next/dist/pages/_document` instead of `next/document`.

**Comment by belgattitude** [comment] 2021-12-04 11:37
I can confirm too, here's a pr to reproduce if needed

https://github.com/belgattitude/nextjs-monorepo-example/pull/919

Github action message

https://github.com/belgattitude/nextjs-monorepo-example/runs/4416914831?check_suite_focus=true

**Comment by timneutkens** [comment] 2021-12-04 11:59
Duplicate of #32110

**Closed** 2021-12-04 11:58 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 06:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
