### ISSUE TITLE
Missing page_client-reference-manifest.js files on build (using path grouping)

### ISSUE THREAD

**Issue by Nickman87** [vercel/next.js#53569] opened 2023-08-04 09:33 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.13-canary.13
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/nextjs-missing-manifest-rtgf6d

### To Reproduce

The error occurs when you try to build the application for the first time (when no .next folder exists).
Just running `npm run build` will produce the following output:

```
➜  workspace git:(master) ✗ npm run build

> next-13@0.1.0 build
> next build

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
- info Creating an optimized production build  
- info Compiled successfully
- info Linting and checking validity of types .Pages directory cannot be found at /project/home/nickman87/workspace/pages or /project/home/nickman87/workspace/src/pages. If using a custom path, please configure with the `no-html-link-for-pages` rule in your eslint config file.
- info Linting and checking validity of types  
- info Collecting page data ...Error: Cannot find module '/project/home/nickman87/workspace/.next/server/app/(logged-in)/page_client-reference-manifest.js'
Require stack:
- /project/home/nickman87/workspace/node_modules/next/dist/server/load-components.js
- /project/home/nickman87/workspace/node_modules/next/dist/build/utils.js
- /project/home/nickman87/workspace/node_modules/next/dist/build/worker.js
- /project/home/nickman87/workspace/node_modules/next/dist/compiled/jest-worker/processChild.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at /project/home/nickman87/workspace/node_modules/next/dist/server/require-hook.js:110:36
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadJSManifest (/project/home/nickman87/workspace/node_modules/next/dist/server/load-components.js:64:72)
    at loadComponentsImpl (/project/home/nickman87/workspace/node_modules/next/dist/server/load-components.js:86:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /project/home/nickman87/workspace/node_modules/next/dist/build/utils.js:1006:32
    at async Span.traceAsyncFn (/project/home/nickman87/workspace/node_modules/next/dist/trace/trace.js:103:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/project/home/nickman87/workspace/node_modules/next/dist/server/load-components.js',
    '/project/home/nickman87/workspace/node_modules/next/dist/build/utils.js',
    '/project/home/nickman87/workspace/node_modules/next/dist/build/worker.js',
    '/project/home/nickman87/workspace/node_modules/next/dist/compiled/jest-worker/processChild.js'
  ]
}

> Build error occurred
Error: Failed to collect page data for /
    at /project/home/nickman87/workspace/node_modules/next/dist/build/utils.js:1156:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'Error'
}
- info Collecting page data .                                                                             
```

### Describe the Bug

The build will generate the necessary file `page_client-reference-manifest.js` for the `(logged-out)` group, but not for the `(logged-in)` group folder.
This causes a one-time error during build, in subsequent builds the error does not seem to appear anymore, as well as a missing module error during runtime (as the file is loaded, but does not exist).

The issue appears starting 13.4.10, but it is not shown at compile time, only at runtime.

### Expected Behavior

All necessary files should be generated on build time.

### Which browser are you using? (if relevant)

Chrome, but not relevant

### How are you deploying your application? (if relevant)

Netlify, but the issue also arises locally

**Comment by ztanner** [comment] 2023-08-08 21:56
Hey @Nickman87 -- I believe in this case it's expected that you'd run into an error, it just seems the error we're throwing here isn't helping you identify the cause (which hopefully will be addressed in #53752)

The reason this is failing and shouldn't be possible is because route groups don't affect URL structure, so `/app/(logged-in)/page.tsx` and `/app/(logged-out)/page.tsx` both are referring to your `/` URL. The docs touch on this in the "Good to Know" section of route groups ([link](https://nextjs.org/docs/app/building-your-application/routing/route-groups)).

If you remove those `page.tsx` files in both route groups, you'll see that the error goes away. Here's your forked sandbox to clarify what I mean: https://codesandbox.io/p/sandbox/nextjs-missing-manifest-forked-rhv4m4

**Closed** 2023-08-08 22:56 UTC
Labels: template: bug
