### ISSUE TITLE
Not all Webpack blocks included in Canary install

### ISSUE THREAD

**Issue by maxsteenbergen** [vercel/next.js#29609] opened 2021-10-04 10:52 UTC
### What version of Next.js are you using?

11.1.3-canary.41

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Vivaldi, Firefox

### What operating system are you using?

macOS

### How are you deploying your application?

yarn run dev

### Describe the Bug

In order to test Framer's new Handshake feature, I followed their steps [outlined here](https://www.framer.com/docs/guides/handshake/#environments) and installed the latest Canary build of Next.
However, the build fails because Next `Cannot find module './blocks/images'` 
It seems it's not installed because indeed, the file/folder is not in my node_modules no matter how many times I've clean cache or delete the node_modules
The same issue has already been raised [here](https://github.com/vercel/next.js/issues/29049) but subsequently closed without resolution. I can confirm that somewhere *after* beta 7 this broke.

I've attached a screenshot of the relevant code and file tree.

<img width="992" alt="Screenshot 2021-10-04 at 12 42 01" src="https://user-images.githubusercontent.com/574278/135837751-48a673f6-ad96-43c2-9b72-3c1017eaf7c8.png">

### Expected Behavior

Next installs all its own dependencies

### To Reproduce

Follow the steps outlined in the [Framer Handshake guide](https://www.framer.com/docs/guides/handshake/#environments)

**Comment by maxsteenbergen** [comment] 2021-10-04 12:59
With the help of @mzaien in #29049, I've been able to circumvent this issue by deleting all lock files and re-installing all node-modules with NPM instead of Yarn. I've retried to re-install everything with Yarn after deleting the lock files as well, but then the original issue returns.

**Comment by maxsteenbergen** [comment] 2021-10-04 21:25
I did try that earlier and again just now: the issue persists.

**Comment by kevroadrunner** [comment] 2021-11-02 14:26
@maxsteenbergen Are you using a `.yarnclean` file? In the defaults of this file there is an entry with `images` which is deleting the files in the next package causing your mentioned error. Replacement for this entry could be: `[!next/dist/build/webpack/config/blocks/images]images`

Maybe it makes sense if the directory would be named differently?

**Comment by maxsteenbergen** [comment] 2021-11-02 15:22
@kevroadrunner There is a .yarnclean file, yes. I'll try this workaround ASAP and report back. Thanks!

**Comment by styfle** [comment] 2021-11-02 19:07
@kevroadrunner Nice find! I was able to reproduce.

```
$ yarn init -y && yarn add next
✨  Done in 4.30s.

$ yarn autoclean
info ".yarnclean" does not exist. Autoclean will delete files specified by ".yarnclean". Run "autoclean --init" to create ".yarnclean" with the default entries.
✨  Done in 0.03s.

$ yarn autoclean --init
info Created ".yarnclean". Please review the contents of this file then run "yarn autoclean --force" to perform a clean.
✨  Done in 0.03s.

$ yarn autoclean
info This command required the "--force" flag to perform the clean. This is a destructive operation. Files specified in ".yarnclean" will be deleted.
✨  Done in 0.03s.

$ yarn autoclean --force
info Removed 774 files
info Saved 1.87 MB.
✨  Done in 0.48s.
```

You can see it removed 774 files which are probably all necessary to run Next.js, including `node_modules/next/dist/build/webpack/config/blocks/images/**`

That being said, yarn has a lot of warnings around this behavior explaining its destructive nature and that you should review the contents before running.

So this is not a Next.js bug, this would impact all npm packages in node_modules.

I suggest updating your `.yarnclean` file to delete fewer files.

**Comment by ijjk** [comment] 2021-11-02 21:55
Closing per above as this doesn't seem to be an issue with the Next.js package.

**Closed by ijjk** 2021-11-02 21:55 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
