### ISSUE TITLE
Typescript Lib Ecmascript Version ignored

### ISSUE THREAD

**Issue by PaulKujawa** [vercel/next.js#10932] opened 2020-03-10 13:15 UTC
# Bug report

## Describe the bug
I followed https://nextjs.org/learn/excel/typescript, changed the TS CompilerOption `lib` to only allow `dom` and `ES5`, and used an ES7 feature - `Array.prototype.includes` in a TS file. The project compiles anyway without complaining. However, should I use `window` and remove `dom` from `lib`, it complains properly. I noticed the same pattern in an older full blown NextJs app, too.

Someone on [Gitter](https://gitter.im/Microsoft/TypeScript?at=5e677912a2ccef3232e3e8c2) told me that's an known issue but I found none. 

## To Reproduce

https://github.com/PaulKujawa/nextjs-ts-issue files `foo.ts` and `tsconfig.json`.

## Expected behavior

Compilation error for `Array.prototype.includes` like `error TS2339: Property 'includes' does not exist on type 'string[]'.`

## System information

- OS: macOS
- Happens when executing `tsc` as well as VSC's TS language service.
- Version of Next.js: 9.3.0 (found in 9.0.2 as well)

## Additional context

NextJs [Docs](https://nextjs.org/docs/basic-features/typescript) say it uses Babel but the learn [chapter](https://nextjs.org/learn/excel/typescript) doesn't use it. That's confusing. Also, the [linked Babel plugin](https://babeljs.io/docs/en/babel-plugin-transform-typescript#caveats) states clearly under Caveats Number 4, that tsconfig files are not respected. I am not sure how one is supposed to setup NextJS with TS.

**Comment by Timer** [comment] 2020-09-10 18:13
This should be resolved in the latest Next.js version. Please let us know if it persists.

**Closed by Timer** 2020-09-10 18:13 UTC

**Comment by PaulKujawa** [comment] 2020-11-02 15:20
@Timer this issue still exists for me. I've updated the demo project. When I remove `dom` it complains about `window`, but `Array.includes` is fine despite `lib` only allows ES5. Maybe I just have an incorrect understanding of something.

**Comment by balazsorban44** [comment] 2022-01-29 07:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
