### ISSUE TITLE
getServerProps is not working with app.render

### ISSUE THREAD

**Issue by dercoder** [vercel/next.js#11065] opened 2020-03-14 01:17 UTC
# Bug report

## Describe the bug

Next.js can not resolve the correct path to the server props json file when you use your custom server with `app.render` function: 
https://nextjs.org/docs/advanced-features/custom-server

## To Reproduce

I created a repository to reproduce the issue:
https://github.com/dercoder/nextjs-server-props-issue

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'http://localhost:3000'
2. Click on 'Test Page A'
3. Check your browser console

## Expected behavior

The json request http://localhost:3000/_next/data/development/test-page-a.json
should return the expected server props.

## Screenshots

**Test Page B is working as expected.**

![success](https://user-images.githubusercontent.com/1737685/76671907-69580800-6599-11ea-98dc-da19507e3f7e.png)

**Test Page A is loading the wrong path / Next.js can not handle this path correctly.**

![failure](https://user-images.githubusercontent.com/1737685/76671908-6f4de900-6599-11ea-8b5d-511b649b61e9.png)

## System information

- OS: Windows 10
- Browser chrome
- Version of Next.js: 9.3.0

## Additional context

Take a look into my README file.

**Comment by MicroBenz** [comment] 2020-05-12 10:29
Any update on this? I also got this problem too. (My workaround is to navigate as server-side navigation instead of client-side.)

**Comment by dercoder** [comment] 2020-05-12 10:45
I tried to upgrade to 9.4.0 but the issue still exists.

**Comment by cruzlutor** [comment] 2020-05-17 15:53
same issue here

**Comment by ijjk** [comment] 2020-09-10 20:49
Hi, this behavior has been corrected in the latest version of Next.js v9.5.3 please upgrade and give it try! 

I'm going to close this since it should be resolved if you are still experiencing this feel free to reply with additional info and we can investigate further

**Closed by ijjk** 2020-09-10 20:49 UTC

**Comment by dercoder** [comment] 2020-09-10 23:33
Hi, thx.
The Issue has been fixed :)

**Comment by balazsorban44** [comment] 2022-01-29 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
