### ISSUE TITLE
`next export` doesn't remove unnneeded JS from perfectly static sites.

### ISSUE THREAD

**Issue by Mee42** [vercel/next.js#21292] opened 2021-01-18 17:03 UTC
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

15.5.0

**What browser are you using?**

firefox, but the problem is not browser related

**What operating system are you using?**

Linux

**How are you deploying your application?**

next export

**Describe the Bug**

My website is a static blog. There's no JS that runs on the client, there's nothing that changes, etc. Yet, NextJS still ships roughly 200kb of Javascript to the client. This Javascript code is completely useless, as I can disable JS in my browser and load the page with no ill effect.

**Expected Behavior**

On fully static webpages, NextJS should not ship any Javascript in the final exported version. At the very least, there should be a flag to turn JS off.

**To Reproduce**

Use `create-next-app` to create an app. Remove the `Head` import and the `<Head>` block from `pages/index.js`. Export the page. Run a fileserver on the `out/` directory, and load the page in the browser. Observe how it works identically with and without JS enabled. See how JS takes up roughly 200kb

**Comment by matamatanot** [comment] 2021-01-19 02:12
Check #11949 `unstable_runtimeJS` config

**Comment by lachlanjc** [comment] 2021-01-19 08:45
I wouldn't consider this a bug; Next is not designed as a pure HTML static site generator in the way that frameworks like Jekyll are, & it's not really feasible to _ensure_ nothing about a page or its dependencies is expecting client-side JS. On a per-page basis (see the linked PR for mor), you can add `export const config = { unstable_runtimeJS: false }` to try out this behavior.

**Comment by timneutkens** [comment] 2021-01-19 09:00
Duplicate of #5054

**Closed by timneutkens** 2021-01-19 09:00 UTC
Labels: template: bug

**Comment by Mee42** [comment] 2021-01-19 18:42
Thank you for the help! I wasn't sure whether to file this as a bug or under discussion. That looks perfect for my usecase

**Comment by balazsorban44** [comment] 2022-01-28 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
