### ISSUE TITLE
[Feature Request] Show server address on home network

### ISSUE THREAD

**Issue by VladimirMikulic** [vercel/next.js#36929] opened 2022-05-15 20:30 UTC
### Describe the feature you'd like to request

I would like that Next.js server on start shows the address of my machine on local network.

### Describe the solution you'd like

Here's what the current log on start looks like:

![Screenshot_20220515_222332](https://user-images.githubusercontent.com/35997844/168492511-8a40d1cc-387a-4527-84ec-ef74c089f513.png)

It would be great to have machine address on local network like Vite does as well:

![Screenshot_20220515_221824](https://user-images.githubusercontent.com/35997844/168492526-77b09667-d8ee-43ed-8c6a-7eb6fcde4fc0.png)

This small feature would save me a ton of time. (I believe others as well)
I often test my web app on various devices and each time, I need to go to network panel, find local ip address of my machine, copy it etc. Being able to get it from the get-go would be amazing!

### Describe alternatives you've considered

N/A

**Comment by balazsorban44** [comment] 2022-05-15 20:32
Duplicate of https://github.com/vercel/next.js/issues/11367

**Closed by balazsorban44** 2022-05-15 20:32 UTC
Labels: template: story
