### ISSUE TITLE
NextJS 14 forced to use swc and cannot switch to babel anymore.

### ISSUE THREAD

**Issue by BanDroid** [vercel/next.js#57608] opened 2023-10-27 14:59 UTC
### Link to the code that reproduces this issue

https://github.com/BanDroid/next-swc-android-issue

### To Reproduce

1. `create-next-app` in termux.
2. run dev.
3. create `.babelrc`/`babel.config.js` and use presets "next/babel".

### Current vs. Expected behavior

[SWC](https://swc.rs/) does support Android arm64, but somehow swc in nextjs cannot support it, i always switch to babel for workaround, but now i cant switch to use babel.

### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: android
  Arch: arm64
  Version: #1 SMP PREEMPT Fri Jul 29 23:55:04 CST 2022
Binaries:
  Node: 18.16.1
  npm: 9.5.1
  Yarn: 1.22.19
  pnpm: 8.8.0
Relevant Packages:
  next: 14.0.0
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

CLI (create-next-app), Operating System (Windows, MacOS, Linux), Package manager (npm, pnpm, Yarn), SWC minifier (swcMinify: true), SWC transpilation

### Additional context

fyi, i use termux to code. last version i tested fine was  next 13.4

**Comment by BanDroid** [comment] 2023-10-27 15:01
fyi: i use pnpm, i also try with npm and yarn too, result was the same.

**Comment by gudvinga** [comment] 2023-10-27 16:45
The same issue.
For some reason we have to support older browsers and use Babel for transpiling to ES5.
After updating to version 14, the Babble doesn't work anymore
Is it possible to transpile code to ES5 using SWC?

**Comment by kdy1** [comment] 2023-10-27 21:52
Is `Disabled SWC as replacement for Babel because of custom Babel configuration` printed?

**Comment by BanDroid** [comment] 2023-10-27 23:43
> Is `Disabled SWC as replacement for Babel because of custom Babel configuration` printed?

no, that was the weird part, usually i see this

**Comment by kdy1** [comment] 2023-10-27 23:51
Does it crash? Please post the whole error message

**Comment by BanDroid** [comment] 2023-10-28 00:02
> Does it crash? Please post the whole error message

yes, it does crash.

```shellscript
> next-swc-android-issue@0.1.0 dev /data/data/com.termux/files/home/Projects/NextJS/
> next dev

   ▲ Next.js 14.0.0
   - Local:        http://localhost:3000

 ⚠ Trying to load next-swc for target triple [object Object], but this target is not supported
 ⨯ Failed to load SWC binary for android/arm64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
```

**Comment by jujutsucode** [comment] 2023-10-31 03:57
i want to use android/arm64 too

**Comment by BanDroid** [comment] 2023-10-31 07:41
> i want to use android/arm64 too

use Next v13 for now, we cant use v14 yet.

**Comment by tsanyqudsi** [comment] 2023-10-31 19:29
I can reproduce this in termux.

**Comment by jridgewell** [comment] 2023-11-08 18:32
We've [reintroduced WASM fallback](https://github.com/vercel/next.js/pull/57906) for SWC (and enabled it by [default in web containers](https://github.com/vercel/next.js/pull/58081)).

**Comment by tsanyqudsi** [comment] 2023-11-10 03:42
@jridgewell fix confirmed. 🚀 🎉

**Comment by jujutsucode** [comment] 2023-11-10 04:01
Hoe to use that?

**Comment by tsanyqudsi** [comment] 2023-11-10 04:08
@jujutsucode how to use what ?

**Comment by jujutsucode** [comment] 2023-11-10 04:14
The wasm

Pada Jum, 10 Nov 2023 11.09, Muhammad Tsany Qudsi ***@***.***>
menulis:

**Comment by tsanyqudsi** [comment] 2023-11-10 04:16
@jujutsucode can you clarify your question ? This issue is about NextJS 14 can't be installed in Termux because of SWC issues. Is that your issue as well ?

**Comment by BanDroid** [comment] 2023-11-10 04:17
@jridgewell  it still occuring in termux android, already have .babelrc with `next/babel` as presets, and also set swcMinify to false in next.config.js.

running dev server still trying to load swc binary

**Comment by jridgewell** [comment] 2023-11-14 03:19
Enable `experimental: { useWasmBinary: true }` in your `next.config.js`

**Comment by BanDroid** [comment] 2023-11-14 04:11
> Enable `experimental: { useWasmBinary: true }` in your `next.config.js`

alright, will test it and send the result

**Comment by BanDroid** [comment] 2023-11-14 07:00
> Enable `experimental: { useWasmBinary: true }` in your `next.config.js`

still crashing, now it even worse, no logs about the crash or error, just stopped immedietly.

```bash
~/.../NextJS/test-2 $ pnpm run dev

> test-2@0.1.0 dev /data/data/com.termux/files/home/Projects/NextJS/test-2                                                                  > next dev                                                            
   ▲ Next.js 14.0.2
   - Local:        http://localhost:3000

~/.../NextJS/test-2 $
```

**Comment by jridgewell** [comment] 2023-11-14 21:04
I'm afraid I don't have an Android device to debug this.

**Comment by BanDroid** [comment] 2023-11-14 22:27
> I'm afraid I don't have an Android device to debug this.

do nextjs have log level for debugging crash? more verbose message would be needed

**Comment by GorenganHunter** [comment] 2023-11-17 02:29
> > I'm afraid I don't have an Android device to debug this.
> 
> do nextjs have log level for debugging crash? more verbose message would be needed.
> 
> could you use emulator and install termux so you could reproduce it?

I think its because the package version is stopped at 13
https://www.npmjs.com/package/@next/swc-android-arm64

**Comment by GorenganHunter** [comment] 2023-11-17 02:36
> > I'm afraid I don't have an Android device to debug this.
> 
> do nextjs have log level for debugging crash? more verbose message would be needed.
> 
> could you use emulator and install termux so you could reproduce it?

This is the log at first `npm run dev` after create next app (sorry i cant upload image here)
https://raw.githubusercontent.com/GorenganHunter/static/main/Screenshot_20231117-092131_Termux.png

**Comment by Talent30** [comment] 2023-11-19 07:03
@next/swc-wasm-nodejs is the in sync with nextjs anymore, so we can't even run Next.js 14 in WebContainer 

https://www.npmjs.com/package/@next/swc-wasm-nodejs

> Enable `experimental: { useWasmBinary: true }` in your `next.config.js`

**Comment by zXpro27** [comment] 2023-11-20 23:24
> Enable `experimental: { useWasmBinary: true }` in your `next.config.js`

Not closed fakk!! Still error

**Comment by tsanyqudsi** [comment] 2023-11-21 02:20
> @jridgewell fix confirmed. 🚀 🎉

retracted.. it was a fluke 😢 sorry for the false confirmation

**Comment by loginVeb** [comment] 2023-11-21 06:45
No, and someday the desired problem will disappear: failed to download the SWC binary for Android/arm64

**Comment by loginVeb** [comment] 2023-11-22 09:04
When the problem is fixed, I want to program in termux on nextjs 14 🥺

**Comment by BanDroid** [comment] 2023-12-16 23:57
update: i successfully run next 14.0.4 in termux, the requirements are here:

- proot (i tried with debian 10 buster from Andronix)
- arm64 device
- node >= v18.17

![Screenshot_20231216-235613.png](https://github.com/vercel/next.js/assets/68449470/aadcd8ce-cf4e-4efb-896d-ecdf40804b02)

**Comment by Talent30** [comment] 2023-12-17 01:13
> update: i successfully run next 14.0.4 in termux, the requirements are here:
> 
>     * proot (i tried with debian 10 buster from Andronix)
> 
>     * arm64 device
> 
>     * node >= v18.17
> 
> 
> ![Screenshot_20231216-235613.png](https://private-user-images.githubusercontent.com/68449470/291020391-aadcd8ce-cf4e-4efb-896d-ecdf40804b02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NzU4NjEsIm5iZiI6MTcwMjc3NTU2MSwicGF0aCI6Ii82ODQ0OTQ3MC8yOTEwMjAzOTEtYWFkY2Q4Y2UtY2Y0ZS00ZWZiLTg5NmQtZWNkZjQwODA0YjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDAxMTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3Zjg5MmRiYmU3YjdkM2RjMGJmYjQ0MDcwOWNhMjVjOTMxMzU4Zjc2MTg1ZWY3N2Y4OGZiNzI3ZDhmZGY4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SKxOjMzW98aXoPihTGZMDT3mz4P1DkxOwFqDCFWW5cY)
> 
> i have verified my own solution, so if anyone got this working too, notified me so i could close the issue.

Yes it's fixed in https://github.com/vercel/next.js/commit/bb25edfdd4964994176085f26a9f38434ad66b58 I think we can close this ticket now

**Comment by BanDroid** [comment] 2023-12-17 22:17
> Yes it's fixed in https://github.com/vercel/next.js/commit/bb25edfdd4964994176085f26a9f38434ad66b58 I think we can close this ticket now 

it was not because it was fixed, i found a workaround to make this work. arm64 device would work like a charm, but it still doesn't work for any 32bit device or 32bit mode on 64bit (armv8l).

but yeah, i'll close this issue then.

**Closed** 2023-12-17 22:18 UTC
Labels: area: create-next-app, template: bug, area: SWC transforms, area: SWC Minify, area: OS
