### ISSUE TITLE
Fast Refresh not working with getStaticProps

### ISSUE THREAD

**Issue by kokanek** [vercel/next.js#19230] opened 2020-11-17 07:23 UTC
# Bug report

## Describe the bug

Working with Next.js 10.0. According to the release docs, any changes made in the getStaticProps function will automatically reflect on the page without a need to refresh but that does not seem to be happening. 

## To Reproduce
Create a route with the code supplied below, change/add any key to the object being returned and save. Check whether the page rendered on the browser changes automatically or not.

Steps to reproduce the behavior, please provide code snippets or a repository:

``` jsx
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function TestImage({data}) {
  console.log('props passed :', data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hey There! <code className={styles.codelarge}>I'm {data.name}</code>
        </h1>
        <h1 className={styles.title}>
          I'm a <code className={styles.codelarge}>{data.age}</code> years old {data.job}.
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <img src="/vercel.svg" alt="Vercel Logo" className={styles.logo} />
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  // Get external data from the file system, API, DB, etc.
  const data = {
    name: 'John',
    age: 28,
    job: 'actor'
  }

  // The value of the `props` key will be
  //  passed to the `Home` component
  return {
    props: {data}
  }
}
```

## Expected behavior

Upon changing any value for any key that is returned from inside of getStaticProps, the page should reflect the same upon saving.

## System information

- OS: macOs
- Browser Chrome
- Version of Next.js: 10.0.1
- Version of Node.js: 10.16.0

**Comment by timneutkens** [comment] 2020-11-17 13:07
Changes are correctly displayed based on your reproduction 🤔 Can you provide a full github repository as currently the functionality seems to be working fine.

**Comment by kokanek** [comment] 2020-11-17 17:11
Could you please check this repository and let me know what I am doing wrong?
https://github.com/kokanek/nextjs-10

**Comment by timneutkens** [comment] 2020-11-18 12:11
Your reproduction is working fine if I edit `pages/fast-refresh.js` 🤔

**Comment by kokanek** [comment] 2020-11-18 13:46
Hey @timneutkens I'm still facing the issue. Here are the detailed steps I am following:

- checkout the code from the repo
- run npm install
- run <code>npm run dev</code> to start the dev server at port 3001
- visit localhost:3001
- navigate to the localhost:3001/fast-refresh route
- Here I get the log on line 5 in **fast-refresh.js**
- Now, I change **Hey There** on line 15 to **Hi There** and save. The page reflects **Hi There** without refreshing and I also get the log line **props passed :   ... **
- Now, I change <code>job: 'actor'</code> on line number 41 to <code>job: 'singer'</code> and save again. This time around, it does not reflect on the page. Also I do not see the log **props passed :   ... ** this time which means the function was not called again.
- Am I missing something here? Why are the changes made in the function component honoring fast-refresh but the changes made inside getStaticProps are not honoring fast-refresh?

**Comment by timneutkens** [comment] 2020-11-23 19:50
Hmm I can reproduce sometimes, will mark for investigation!

**Comment by kokanek** [comment] 2020-11-24 18:07
Thanks. I could also observe that the behavior worked as expected around 1-2 out of 10 times. But majority of the time, fast-refresh did not get triggered by changes in getStaticProps function.

**Comment by bondom** [comment] 2021-01-13 09:48
I encountered similar issue when playing around with nextjs learn example, just try to execute steps described here and you will see that page is not fast refreshed: https://nextjs.org/learn/basics/dynamic-routes/render-markdown I need to do a full reload to see the changes

**Comment by rishi-raj-jain** [comment] 2021-04-09 06:01
I tried the same on https://codesandbox.io/s/sweet-carson-lu7ce?file=/pages/fast-refresh.js, seems to work fine. Anything I'm missing here? It logs: "Refreshing page data due to server-side change", so should be refreshing on any changes in getStaticProps.

**Comment by thanders** [comment] 2021-04-18 05:29
I'm not sure if this is the same issue, but I have been seeing issues with getStaticProps where I try to call a function to obtain my initial props and it usually works the first time, but when I refresh the page I will quickly get an error from the getStaticProps saying the assignment of my function is undefined.

Below are my related dependencies:
```
    "@next/mdx": "^10.1.3",
    "next": "10.1.3",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-intl": "^5.15.8"

    pages/index.js @ getStaticProps
```
I'd love to see this fixed or get some help resolving this.

**Comment by rishi-raj-jain** [comment] 2021-04-18 05:40
Is the code open source, or a repo I can refer to?

**Comment by thanders** [comment] 2021-04-18 06:01
Yes, it's public, here is a link to the file - see getStaticProps:
https://github.com/thanders/pedestrian-frontend/blob/feature/ArticleBrowse/pages/index.js

**Comment by thanders** [comment] 2021-04-18 06:01
> Is the code open source, or a repo I can refer to?

Yes, it's public, here is a link to the file - see getStaticProps:
https://github.com/thanders/pedestrian-frontend/blob/feature/ArticleBrowse/pages/index.js

**Comment by rishi-raj-jain** [comment] 2021-04-22 02:13
> > Is the code open source, or a repo I can refer to?
> 
> I've updated my original post above to add the url. See above.
> 
> Normal behavior should be that every time the page is refreshed getStaticProps will run. In this case, I'm not making the function with async/await because I am not using that, but I'm getting an undefined error upon refresh.

Have a look @ https://codesandbox.io/s/focused-jones-ebnef?file=/pages/index.js, I think getStaticProps is being called at every refresh, while the error that you're facing is related to the way primary.module is being used which I feel is subjective in nature. Are you though sure this is related to the current issue?

**Closed** 2022-02-16 22:32 UTC
Labels: kind: bug, type: needs investigation, area: Compiler

**Comment by schickling** [comment] 2022-02-17 08:20
Nice! Does this also address [this issue](https://github.com/vercel/next.js/issues/34054)?

**Comment by ijjk** [comment] 2022-02-17 17:35
@schickling it could potentially help with that issue as well, please update to `v12.1.0` and give it a try!

**Comment by schickling** [comment] 2022-02-28 14:16
Just looked into this and seems like `v12.1.0` does **not** fix https://github.com/vercel/next.js/issues/34054.
