### ISSUE TITLE
i18n and rewrites have lost functionnality

### ISSUE THREAD

**Issue by LeonardDrs** [vercel/next.js#23455] opened 2021-03-27 14:54 UTC
### What version of Next.js are you using?

10.0.9

### What version of Node.js are you using?

12.18.3

### What browser are you using?

Firefox latest, chrome latest

### What operating system are you using?

Linux

### How are you deploying your application?

Docker + kubernetes

### Describe the Bug

Back in 10.0.1, I used the following `next.config.js` configuration without issue:
```js
{
      i18n,
      assetPrefix,
      async rewrites() {
        return [
              {
                source: "/base/:path*",
                destination: "/:path*",
              },
            ]
      },
}
```

When I update to next 10.0.8 or 10.0.9, this kind of rewrite does not work anymore.
When I go to my deployed application, any `base/*` path does not work anymore. Adding `locale: false` to the rewrite does nothing either.

Might be related to https://github.com/vercel/next.js/issues/22984

### Expected Behavior

`base/*` path should work as 10.0.1 used to.

### To Reproduce

I'll push a PR with integration tests. (https://github.com/vercel/next.js/pull/23456)
Otherwise, 
- Head over https://github.com/vercel/next.js/blob/canary/examples/i18n-routing/next.config.js,
- add the following to the configuration:
```js
      async rewrites() {
        return [
              {
                source: "/base/:path*",
                destination: "/:path*",
              },
            ]
      },
```
- Run the example
- Try to access any compiled js file using localhost:3000/base/_next/.... url

**Comment by AlexW-Valtech** [comment] 2021-03-29 08:17
Looks also related to #23270 that I recently raised.

**Comment by LeonardDrs** [comment] 2021-03-29 09:18
@AlexW-Valtech Oh yeah nice catch, didn't saw yours, sorry!

**Comment by LeonardDrs** [comment] 2021-03-29 13:37
@AlexW-Valtech Hey would you mind testing https://github.com/vercel/next.js/pull/23456 on your side and see if anything wrong happens?

**Comment by LeonardDrs** [comment] 2021-03-29 17:28
Hmm, seems like v10.1.0 allow us to do what we want thanks to https://github.com/vercel/next.js/pull/23407 with
```
  async rewrites() {
    return {
      beforeFiles: [
        {
          source: "/base/:path*",
          destination: "/:path*",
        },
      ],
    };
  },
```
Thanks @ijjk. Can you confirm that `beforeFiles` was created for this kind of purpose, and that this issue and related PR can be closed?

**Comment by AlexW-Valtech** [comment] 2021-03-30 08:26
It does look like 10.1.0 addresses the issue. 

Unfortunately it seems that #18080 still remains a problem (unrelated to i18n but in same area).

**Comment by ijjk** [comment] 2021-04-17 16:10
Closing as it looks like this is resolved in the latest version

**Closed by ijjk** 2021-04-17 16:10 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
