### ISSUE TITLE
Fetch Api isn't revalidating data.

### ISSUE THREAD

**Issue by muhammadfaizan027915** [vercel/next.js#58128] opened 2023-11-07 11:03 UTC
### Link to the code that reproduces this issue

https://github.com/muhammadfaizan027915/next-report.git

### To Reproduce

1- Start Application
2- Check home page and netwrok tab to observe the cache issue.

This is how I am calling my fetch function

`fetch(URL, {
      cache: "force-cache",
      next: { revalidate: 120 },
    })
      .then((response) => response.json())`

### Current vs. Expected behavior

I am trying to use fetch revalidation property to revalitate api after 2 minutes but it doesn't work, whenever I referesh the page, the api gets data from disk-space. But it should revalidate the api call after every two minutes.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:        
  Platform: win32        
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 20.9.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.1
  eslint-config-next: 14.0.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Data fetching (gS(S)P, getInitialProps)

### Additional context

I am using pages route and having issues with revalidation of fetch call.

Here's the Loom Link with step by step description
https://www.loom.com/share/36aea2397b69432990feb1057e14c076?sid=b4b9c2d0-0a1f-41aa-b28e-a2a7d499b7aa
 

1- Want to cache a data for certain limit of time.
2- After that time, want that data must be revalidated with updated data from server on page reload.
3- But fetch api is not revalidating the data and always fetches data from disk cache.

**Comment by asimplify** [comment] 2023-11-07 11:06
Yeah, facing the same issue in v13.4. tried multiple props for the fetch call but nothing worked.

**Comment by ztanner** [comment] 2023-11-15 15:57
Hi, your reproduction is using the pages router, which does not support the cache semantics that you are attempting to use.

Can you please share a reproduction that uses the app router?

**Comment by hallatore** [comment] 2023-11-26 15:14
I don't think next. { revalidate } is supported client-side?

It also doesn't work togheter with cache: "force-cache". The fetch is cached forever with no revalidate.

**Comment by ztanner** [comment] 2023-11-29 20:00
Going to close this since no valid reproduction has been provided - but don't hesitate to open a new issue with a valid reproduction and we can take a look!

**Closed by ztanner** 2023-11-29 20:00 UTC
Labels: please add a complete reproduction, template: bug, area: data fetching
