### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'current')

### ISSUE THREAD

**Issue by dincerpece** [vercel/next.js#48964] opened 2023-04-28 15:42 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.2-canary.12
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

sorry i can't upload because my project contains localhost database connections

### To Reproduce

While I get the same error on every page in development mode, I get this error on pages under [slug] in production mode as a result of refreshing the page! I get this error when I run it with my server.js file. While next worked in 13.3.1, it's now broken!

My server.js file looks like this:

![Screenshot_20](https://user-images.githubusercontent.com/57527680/235193368-a212c8d3-affb-4819-9e6d-7b4b38d17e23.png)

```
const { createServer } = require('https')
const { parse } = require('url')
const next = require('next')
const fs = require('fs')
const dev = process.argv[2] !== 'production'
const serverProduct = process.argv[3] === 'server' || undefined

process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'
const hostname = 'localhost'
const port = 443
// when using middleware hostname and port must be provided below
const app = next({ dev, hostname, port })
const handle = app.getRequestHandler()
const httpsOptions = {
key: fs.readFileSync(./server/certificates/${serverProduct ? 'cloudflare.key' : 'server.key'}),
cert: fs.readFileSync(./server/certificates/${serverProduct ? 'cloudflare.pem' : 'server.crt'}),
}
app.prepare().then(() => {
createServer(httpsOptions, async (req, res) => {
try {
const parsedUrl = parse(req.url, true)
await handle(req, res, parsedUrl).then(null)
} catch (err) {
console.error('Error occurred handling', req.url, err)
res.statusCode = 500
res.end('internal server error')
}
})
.once('error', (err) => {
console.error(err)
process.exit(1)
})
.listen(port, () => {
console.log(> Ready on https://${hostname})
})
})
```

### Describe the Bug

What am I missing in my server.js file or what should I do? I got this error in the last 13.3.2-canary.7 and it continued in later versions! Normally, I get this error when I refresh the pages under news-media/[slug] and other pages under news-media/[slug] while opening in production mode. I get this error on every page in development mode!

While in development:
![dev1](https://user-images.githubusercontent.com/57527680/235191282-c2a79a40-53ec-42f2-91fd-06a309ccc3d0.png)
![dev2](https://user-images.githubusercontent.com/57527680/235191289-bb66438f-a24e-40b8-b8c2-be8f045125bf.png)

While in production:
![product1](https://user-images.githubusercontent.com/57527680/235191290-db10dc4a-ff57-4443-a85e-3ae58f706e8c.png)
![product2](https://user-images.githubusercontent.com/57527680/235191292-8bd170c7-1b46-4722-8282-dc32def3364c.png)

### Expected Behavior

I'm waiting for my server.js file and my pages to load properly in both production and development mode.

I had stated the same mistake in my previous notification, but another topic was written under my error report and it must be for that error, my report was closed! Do not do this. I can't understand why my issue is getting closed when another bug is fixed?

### Which browser are you using? (if relevant)

Chrome 112.0.5615.138

### How are you deploying your application? (if relevant)

on my localhost with the command "next build && node server/server.js production".

**Comment by klarstrup** [comment] 2023-04-28 17:41
Maybe related to https://github.com/vercel/next.js/issues/48948 https://github.com/vercel/next.js/issues/48918 and https://github.com/vercel/next.js/issues/48704

**Comment by sophiebits** [comment] 2023-04-29 03:10
I see this too on latest canary. In fact if I open a new clean repro example https://stackblitz.com/fork/github/vercel/next.js/tree/canary/examples/reproduction-template-app-dir then it reproduces immediately.

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/6820/235280814-24c37794-ba6e-4cf6-ac98-4611068055d7.png">

**Comment by sophiebits** [comment] 2023-04-29 03:45
On StackBlitz it appears that react-dom-server.edge.development.js's `require('react-dom')` is resolving to version 18.2.0, instead of the bundled canary ("next") version.

**Comment by shuding** [comment] 2023-04-29 12:10
Thanks @sophiebits for the pointers! I'm wondering if the require hook is affected by how Stackblitz runs (e.g. causing ordering differences)...

**Comment by MR-Addict** [comment] 2023-04-30 15:03
I got the same problem.

I have vafried this issue still exists in latest 13.3.2 version published hours ago. What's interesting is that it's not working on my local machine after I start built project, but it's working well when I deploy it to vercel.

I hope this issue could be fixed.

> My project that got this issue:
> 
> - [https://github.com/MR-Addict/punch-next](https://github.com/MR-Addict/punch-next)

**Comment by shuding** [comment] 2023-05-01 17:41
The problem seems to be related to workers being disable when running on StackBlitz - but I'm not sure about other cases.

**Closed** 2023-05-01 21:40 UTC
Labels: template: bug

**Comment by pierrechevaliercf** [comment] 2023-05-04 14:29
This issue should not be closed, I still have it in the latest canary version in my local project.

And I also encounter it in 13.3.4.

```
error - TypeError: Cannot set properties of undefined (setting 'current')
    at prepareHostDispatcher (C:\Users\picheva1\workspace\iv4\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.development.js:1896:37)
    at createRequest (C:\Users\picheva1\workspace\iv4\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.development.js:8299:3)
    at C:\Users\picheva1\workspace\iv4\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.development.js:10126:19
    at new Promise (<anonymous>)
    at Object.renderToReadableStream (C:\Users\picheva1\workspace\iv4\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.development.js:10092:10)  
    at C:\Users\picheva1\workspace\iv4\node_modules\next\dist\server\node-web-streams-helper.js:195:117
    at NextTracerImpl.trace (C:\Users\picheva1\workspace\iv4\node_modules\next\dist\server\lib\trace\tracer.js:86:20)
    at renderToInitialStream (C:\Users\picheva1\workspace\iv4\node_modules\next\dist\server\node-web-streams-helper.js:195:37)
    at C:\Users\picheva1\workspace\iv4\node_modules\next\dist\server\app-render\app-render.js:937:92
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  page: '/'
}
```

In `\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.development.js` , I can see this code

```js
var ReactDOMSharedInternals = ReactDOM.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;

var ReactDOMCurrentDispatcher = ReactDOMSharedInternals.Dispatcher;
var ReactDOMServerDispatcher = {
  prefetchDNS: prefetchDNS,
  preconnect: preconnect,
  preload: preload,
  preinit: preinit
};
function prepareHostDispatcher() {
  ReactDOMCurrentDispatcher.current = ReactDOMServerDispatcher;
} // Used to distinguish these contexts from ones used in other renderers.
```

ergo: `ReactDOM.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.Dispatcher` is null.

So, should `var ReactDOM = require('react-dom')` not import from `node_modules/react-dom` ?

**Comment by khuezy** [comment] 2023-05-04 20:10
@pierrechevaliercf try 13.4.0. If you're doing a custom request handler + standalone + appdir, you'll need to set `process.env.__NEXT_PRIVATE_PREBUNDLED_REACT = "next"` or else it'll try to load the experimental react-dom

**Comment by pierrechevaliercf** [comment] 2023-05-05 09:45
Thank you @khuezy , it indeed solves my issue in 13.3.4 and 13.4.0 !
