### ISSUE TITLE
Error: true is not a PostCSS plugin

### ISSUE THREAD

**Issue by DopamineDriven** [vercel/next.js#17236] opened 2020-09-20 04:54 UTC
# True is not a PostCSS plugin

## Describe the bug
When running `yarn dev` it returns the following error:
```bash
error - ./styles/index.css (./node_modules/next/node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/next/dist/compiled/postcss-loader??__nextjs_postcss!./styles/index.css)
Error: true is not a PostCSS plugin
```
I have tried using .json instead of .js, that did not resolve the issue. I am using typescript and this is a new bug. I have had the same configuration for tailwind.config.js and postcss.config.js in the root of my projects for months with no prior issues. I even eliminated all content from styles/index.css with the exception of the following:

```css
@tailwind base;

@tailwind components;

@tailwind utilities;
```

## To Reproduce
Install the following:
```git
yarn add tailwindcss next@9.5.4-canary.20 react react-dom && yarn add -D postcss-preset-env autoprefixer @types/react @types/react-dom @types/node postcss-flexbugs-fixes stylelint stylelint-config-recommended typescript
```

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'https://github.com/DopamineDriven/windy-city-next'
2. Click on 'clone repository or download zip'
3. 'install dependencies'
4. run `yarn dev` and the error will flag

## Expected behavior
I expect it to run just as all of my other TS+Nextjs+Tailwindcss repos do, each using next 9.5.x (headless-wp-next-directory, asross-portfolio)

## Screenshots
![image](https://user-images.githubusercontent.com/46355797/93694603-6b180080-fad3-11ea-954d-39e0933841d3.png)

## System information

- OS: Windows
- Browser (if applies): Brave, Chrome
- Version of Next.js: 9.5.4-canary.20
- Version of Node.js: 14.11.0

**Comment by DopamineDriven** [comment] 2020-09-20 06:20
Update: Determined the issue

autoprefixer@10.0.0 breaks next's postcss loader on start

I rolled back to autoprefixer@9.8.6 and the issue was resolved

**Comment by stephanschubert** [comment] 2020-09-20 12:15
Maybe related: https://github.com/webpack-contrib/postcss-loader/issues/482

**Comment by ai** [comment] 2020-09-20 14:35
To fix this issue Next.js need to update PostCSS 7 to 8

**Comment by ai** [comment] 2020-09-20 14:37
I created a separated issue about updating to PostCSS 8 https://github.com/vercel/next.js/issues/17242

**Comment by timneutkens** [comment] 2020-09-21 12:32
Closing as duplicate of #17242

**Closed by timneutkens** 2020-09-21 12:32 UTC

**Comment by DmitryOlkhovoi** [comment] 2020-09-25 13:50
I have the same problem with `postcss-nested`

**Comment by laurivaananen** [comment] 2020-09-26 13:01
@DmitryOlkhovoi I had the same issue and managed to fix it by downgrading the package to `postcss-nested@4.2.3`

**Comment by DmitryOlkhovoi** [comment] 2020-09-27 09:10
@laurivaananen yes, that works :)

**Comment by AWIXOR** [comment] 2020-10-01 18:29
> Update: Determined the issue
> 
> autoprefixer@10.0.0 breaks next's postcss loader on start
> 
> I rolled back to autoprefixer@9.8.6 and the issue was resolved

This worked for me too!

**Comment by dr5hn** [comment] 2020-10-05 08:40
UPDATE: I fixed this issue by adding this to package.json 🎉 
```
   "peerDependencies": {
        "postcss": "^8.0.0"
    },
```

SOURCE: https://github.com/postcss/autoprefixer/releases/tag/10.0.0

**Comment by cascharly** [comment] 2020-10-09 20:21
Thank you very much!!!!

**Comment by pedoch** [comment] 2020-10-11 10:05
Thank you so much

**Comment by giraffesyo** [comment] 2020-11-02 23:51
For me I had to downgrade  postcss-flexbugs-fixes from 5.0.0 to 4.2.1. I did this in the package.json by changing to:
` "postcss-flexbugs-fixes": "4.2.1",`  and rerunning yarn.

**Comment by Fire-Kirin** [comment] 2020-11-14 10:27
> Update: Determined the issue
> 
> autoprefixer@10.0.0 breaks next's postcss loader on start
> 
> I rolled back to autoprefixer@9.8.6 and the issue was resolved

In my case, I not only rolled back to autoprefixer@9.8.6 but also downgrading the package to postcss-nested@4.2.3, and the issue was solved.

**Comment by sfmskywalker** [comment] 2020-11-19 14:55
Following TailwindCSS' guide fixed the issue for me: https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

**Comment by employee451** [comment] 2020-11-24 08:14
To solve the issue, I had to install `postcss ^8.1.10`. I didn't have `postcss` in my dependencies before.

**Comment by lu-zen** [comment] 2020-11-29 18:13
> For me I had to downgrade postcss-flexbugs-fixes from 5.0.0 to 4.2.1. I did this in the package.json by changing to:
> ` "postcss-flexbugs-fixes": "4.2.1",` and rerunning yarn.

If you're using tailwindcss@2 there's no need to keep this module, tw2 dropped IE support anyways

**Comment by sebmellen** [comment] 2021-01-05 04:07
@sfmskywalker Thank you! That finally fixed the issue for me.

Does anyone have an idea when we might be able to move off the compatibility build?

From the TailwindCSS link:
> Once the rest of your tools have added support for PostCSS 8, you can move off of the compatibility build by re-installing Tailwind and its peer-dependencies using the latest tag:
> `npm uninstall tailwindcss @tailwindcss/postcss7-compat
npm install tailwindcss@latest postcss@latest autoprefixer@latest`

**Comment by dannysofftie** [comment] 2021-05-22 07:26
Adding `postcss` as a devDependency solved the issue for me. Version `8.3.0`

**Comment by balazsorban44** [comment] 2022-01-28 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
