### ISSUE TITLE
Example zustand throw a warning

### ISSUE THREAD

**Issue by MatteoGauthier-serli** [vercel/next.js#26557] opened 2021-06-24 07:28 UTC
### What version of Next.js are you using?

11

### What version of Node.js are you using?

v14.17.0

### What browser are you using?

Chrom

### What operating system are you using?

MacOs

### How are you deploying your application?

next start

### Describe the Bug

When i use the `with-zustand` example, it throws this : 

```
Provider initialStore is deprecated and will be removed in the next version.
```

That's it 😃

### Expected Behavior

Nothing

### To Reproduce

```
yarn create next-app --example with-zustand with-zustand-app
```

**Comment by himanshu007-creator** [comment] 2021-06-24 17:34
hi, i would like to work on this issue. Please guide me further what needs to be done.
thanks

**Comment by Tom2522** [comment] 2021-07-01 01:37
ขอบคุณมากครับที่แก้ไขข้อมูลเฟสบุ๊คให้
tomphuwarin32@gmail.com
Phuwarin phogri

**Comment by ijjk** [comment] 2021-07-20 00:11
Hi, this should be fixed in the latest version of this example, see here for latest changes! https://github.com/vercel/next.js/tree/canary/examples/with-zustand

**Closed by ijjk** 2021-07-20 00:11 UTC
Labels: good first issue, type: example

**Comment by balazsorban44** [comment] 2022-01-28 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
