### ISSUE TITLE
next/image should infer image aspect ratio at build time

### ISSUE THREAD

**Issue by gajus** [vercel/next.js#18496] opened 2020-10-29 17:19 UTC
It is not clear why does `next/image` require me to add `width` and `height` values when this information can be easily inferred from the image itself at build time.

If there is a rational reason for it, I would at least briefly mention it in the documentation.

**Comment by danbeneventano** [comment] 2020-10-29 17:44
Width and height are not required. Use the `unsized` prop.

**Comment by Timer** [comment] 2020-10-29 17:54
@danbeneventano  `width` and `height` are required 99.99% of the time and `unsized` should only be used as a last resort as it severely hurts performance.

**Comment by gajus** [comment] 2020-10-29 17:55
I was going to say. There is a comment:

> unsized - When true, the width and height requirement can by bypassed. Should not be used with above-the-fold images. Should not be used with priority.

Thus was my original question – since next.js can infer this information at built time, why doesn't it?

**Comment by Timer** [comment] 2020-10-29 17:56
@gajus Next.js cannot infer this information at build time, as we allow you to pass any image URL you want. It does not have to be from the file system. We also don't do any processing at build time because that'd slow builds down.

We're going to explore a way to **import images** in the future, which will automatically set the width and height.

**Comment by gajus** [comment] 2020-10-29 17:59
> @gajus Next.js cannot infer this information at build time, as we allow you to pass any image URL you want. It does not have to be from the file system. This type of dynamic input cannot be statically analyzed.

I would imagine that 99% of users will want to use `next/image` in a way that explicitly refers to a static asset, e.g.

```js
<Image src={require('../images/foo.png')} />

```

It would seems a simple improvement to `next/image` to detect these cases and infer the width / height.

That said... I believe I can do this myself with a simple wrapper. I think.

**Comment by Timer** [comment] 2020-10-29 18:00
> We're going to explore a way to import images in the future, which will automatically set the width and height.

**Comment by Timer** [comment] 2020-10-29 18:09
Closing in favor of this:
https://github.com/vercel/next.js/issues/18497

**Closed by Timer** 2020-10-29 18:09 UTC
Labels: kind: story, type: feature request

**Comment by balazsorban44** [comment] 2022-01-29 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
