### ISSUE TITLE
German umlauts break image optimization process

### ISSUE THREAD

**Issue by derweili** [vercel/next.js#31148] opened 2021-11-08 13:17 UTC
### What version of Next.js are you using?

11.1.1 (but also happens with 12.0.1)

### What version of Node.js are you using?

16.4.2

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying your application?

next start

### Describe the Bug

When the Image Component is used with the default loader and the loaded image includes a German umlaut (ä,ö,ü) in its filename, following error occurs:
`Invalid character in header content ["Content-Disposition"]`

```
TypeError: Invalid character in header content ["Content-Disposition"]
  File "node:_http_outgoing", line 576, col 3, in ServerResponse.setHeader
  File "/Users/werbeagenten/Code/Kunden/Werbeagenten/werbeagenten-website/node_modules/next/dist/server/image-optimizer.js", line 454, col 13, in setResponseHeaders
    res.setHeader('Content-Disposition', `inline; filename="${fileName}"`);
  File "/Users/werbeagenten/Code/Kunden/Werbeagenten/werbeagenten-website/node_modules/next/dist/server/image-optimizer.js", line 465, col 20, in sendResponse
    const result = setResponseHeaders(req, res, url, etag, maxAge, contentType, isStatic, isDev);
  File "/Users/werbeagenten/Code/Kunden/Werbeagenten/werbeagenten-website/node_modules/next/dist/server/image-optimizer.js", line 408, col 13, in imageOptimizer
    sendResponse(req, res, url, maxAge, upstreamType, upstreamBuffer, isStatic, isDev);
  File "/Users/werbeagenten/Code/Kunden/Werbeagenten/werbeagenten-website/node_modules/next/dist/server/router.js", line 210, col 32, in async Router.execute
    const result = await testRoute.fn(req, res, newParams, parsedUrlUpdated);
  File "/Users/werbeagenten/Code/Kunden/Werbeagenten/werbeagenten-website/node_modules/next/dist/server/next-server.js", line 1088, col 29, in async Server.run
    const matched = await this.router.execute(req, res, parsedUrl);
  File "/Users/werbeagenten/Code/Kunden/Werbeagenten/werbeagenten-website/node_modules/next/dist/server/next-server.js", line 304, col 20, in async Server.handleRequest
    return await this.run(req, res, parsedUrl);
```

You can see details about this error here:
https://sentry.werbeagenten.de/share/issue/93dddfc2448441b3aa548f30794ad0a0/

This error results in the image not showing up on the website but returning a 500 error.

### Expected Behavior

The Image should show up.

### To Reproduce

1. Use the Image Component
2. Load an image with a german umlaut (ä,ö,ü) in its filename (from a remote server via URL not from local)
3. Run `npm run build && npm run start`

**Comment by stefanprobst** [comment] 2021-11-08 13:50
this might have been fixed by  #30287, which is included in 12.0.3

**Comment by ijjk** [comment] 2021-11-08 16:02
Closing per above as this should be fixed in `v12.0.3`, please update and give it a try!

**Closed by ijjk** 2021-11-08 16:02 UTC
Labels: template: bug

**Comment by derweili** [comment] 2021-11-09 09:04
@stefanprobst @ijjk after switching to v12.0.3 the error was resolved. Thank you!

**Comment by balazsorban44** [comment] 2022-01-27 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
