### ISSUE TITLE
.local.env file does not load in development

### ISSUE THREAD

**Issue by mmaksi** [vercel/next.js#43753] opened 2022-12-06 10:20 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

error - Failed to load env from E:\Nextflix\Nextflix\.env.local TypeError: Cannot read properties of undefined (reading 'split')
    at E:\Nextflix\Nextflix\node_modules\@next\env\dist\index.js:1:311
    at Array.reduce (<anonymous>)
    at _interpolate (E:\Nextflix\Nextflix\node_modules\@next\env\dist\index.js:1:125)
    at expand (E:\Nextflix\Nextflix\node_modules\@next\env\dist\index.js:1:709)
    at processEnv (E:\Nextflix\Nextflix\node_modules\@next\env\dist\index.js:1:3706)
    at Module.loadEnvConfig (E:\Nextflix\Nextflix\node_modules\@next\env\dist\index.js:1:4660)
    at Object.loadConfig [as default] (E:\Nextflix\Nextflix\node_modules\next\dist\server\config.js:41:21)
    at NextServer.loadConfig (E:\Nextflix\Nextflix\node_modules\next\dist\server\next.js:146:36)
    at NextServer.getServer (E:\Nextflix\Nextflix\node_modules\next\dist\server\next.js:150:39)
    at NextServer.prepare (E:\Nextflix\Nextflix\node_modules\next\dist\server\next.js:130:35)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/mmaksi/Nextflix

### To Reproduce

Step 1: npm install

Step 2: npm run dev

### Describe the Bug

.env.local file unexpectedly stopped working. It used to be working fine in the morning but no longer works in the morning. It started throwing an error: "Cannot read .local.env file" without any change in the code.

### Expected Behavior

I expect the environment variables to be loaded just fine in my application.

### Which browser are you using? (if relevant)

Google Chrome

**Comment by balazsorban44** [comment] 2022-12-06 11:32
The file needs to be called `.env.local` for Next.js to pick it up. Otherwise, this sounds like a duplicate of: https://github.com/vercel/next.js/issues/36691

If you think it's a different issue, please open a new one with an attached reproduction. (The one you linked to does not have the file in question.)

**Closed by balazsorban44** 2022-12-06 11:32 UTC
Labels: template: bug

**Comment by mmaksi** [comment] 2022-12-06 13:22
> The file needs to be called `.env.local` for Next.js to pick it up. Otherwise, this sounds like a duplicate of: #36691
> 
> If you think it's a different issue, please open a new one with an attached reproduction. (The one you linked to does not have the file in question.)

Yes! Sorry it's `.env.local` but I mistyped it and was too busy to correct it!
