### ISSUE TITLE
A non-existent URL can be accessed.

### ISSUE THREAD

**Issue by Ema38** [vercel/next.js#26909] opened 2021-07-04 06:09 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.15.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

```/[userID]/pages/[pageID]/```  
1. Access the page consisting of the URL above.
2. Change ```[userID]``` or ```[pageID]``` in the address bar to any character string, and access the page again.
3. The same page as the previous one will be displayed.

### Expected Behavior

Go to 404 page.

### To Reproduce

1. Clone [this repository](https://github.com/Ema38/next-route-test.git).
2. Run ```npm i``` or ```yarn``` in a terminal.
3. Run ```npm run dev``` or ```yarn dev``` in a terminal.
4. Press the ```page1``` or ```page2``` link on the top page.
5. Change ```[userID]``` or ```[pageID]``` in the address bar to any character string, and access the page again.

You can also check the operation on the following page.  
https://next-route-test-one.vercel.app/

**Comment by AryanBeezadhur** [comment] 2021-07-05 16:41
From the [`fallback: 'blocking'` Next.js docs](https://nextjs.org/docs/basic-features/data-fetching#fallback-blocking):

> The paths that have not been generated at build time will **not** result in a 404 page. Instead, Next.js will SSR on the first request and return the generated HTML.

So the 404 page will not display.

**Comment by ijjk** [comment] 2021-07-07 21:08
As mentioned in the above comment this is the expected behavior for `fallback: 'blocking'` if you only want specific routes to be generated/accessible via a dynamic route you can you use `fallback: false` instead. 

I'm going to close this since this doesn't appear to be a bug and is working as expected.

**Closed by ijjk** 2021-07-07 21:08 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
