### ISSUE TITLE
Preload of next data json fails with 404 when trailing slash option is enabled

### ISSUE THREAD

**Issue by d3x7r0** [vercel/next.js#19801] opened 2020-12-03 21:50 UTC
# Bug report

## Describe the bug

When doing an export for a project with the trailing slash option enabled the preload of the json file for the linked pages fail with a 404.

## To Reproduce

Repository: https://github.com/d3x7r0/nextjs-trailling-slash-issue/tree/preload-issue

1. Run `npm run build && npm run export && npm run serve`
2. Open your browser at http://localhost:8080
3. Open the browser console and check network requests

## Expected behavior
Preload request should remove the trailing slash before requesting the json

## Screenshots

<img width="951" alt="Screenshot 2020-12-03 at 21 47 45" src="https://user-images.githubusercontent.com/163881/101092209-30414700-35b1-11eb-8744-777e732cfa6e.png">

## System information

- OS: macOS Catalina
- Browser: Tested in Chrome, Firefox, Safari
- Version of Next.js: 10.0.3
- Version of Node.js: v12.19.0
- Deployment: next build && next export

**Comment by timneutkens** [comment] 2020-12-04 10:47
Duplicate of #17813

**Closed by timneutkens** 2020-12-04 10:47 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-29 01:25
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
