### ISSUE TITLE
Next/image by default makes motion gif no longer have motion

### ISSUE THREAD

**Issue by ziyak97** [vercel/next.js#18683] opened 2020-11-02 14:52 UTC
# Bug report

## Describe the bug

Next/image by with a default next.config.js file makes motion gifs no longer have any motion

## To Reproduce

1. Go to https://taskpro-website.vercel.app (no longer has the issue cause I changed back to the img tag).
2. Scroll down to the bottom of the page
3. See the lightbulb gif have no motion

## Expected behavior

The gif should have motion as it does when I use a normal img tag.

## Screenshots

<img width="1402" alt="Screenshot 2020-11-01 at 10 25 19 PM" src="https://user-images.githubusercontent.com/53836911/97881339-46f14580-1d48-11eb-8091-fe2a445c8a93.png">
![lighbulb](https://user-images.githubusercontent.com/53836911/97882115-37263100-1d49-11eb-86d2-e2d10837da63.gif)

## System information

- Version of Next.js: [e.g. 10.0.0]

**Comment by styfle** [comment] 2020-11-05 20:13
@ziyak97 I believe this issue is fixed. Can you confirm with 10.0.1?

**Comment by timneutkens** [comment] 2020-11-09 15:13
Closing, let us know if it works though 🙏

**Closed** 2020-11-09 15:13 UTC
Labels: kind: bug, priority: p0

**Comment by balazsorban44** [comment] 2022-01-29 06:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
