### ISSUE TITLE
Error when using yarn PnP

### ISSUE THREAD

**Issue by Markos-Th09** [vercel/next.js#33023] opened 2022-01-05 09:18 UTC
### Run `next info` (available from version 12.0.8 and up)

Not available because the latest stale version is 12.0.7

### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

not deploying

### Describe the Bug

I am trying to use yarn PnP is my nextjs project. According to the yarn compatibility table is should work but when i do yarn dev I get an error(Edit: the stable version error is duplicate of #32546)
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - ./.yarn/__virtual__/next-virtual-17d35d2fd4/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/dev/dev-build-watcher.js
Error: Failed to read source code from /Users/thomastheocharis/Documents/Code/test/.yarn/__virtual__/next-virtual-17d35d2fd4/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/dev/dev-build-watcher.js

Caused by:
    No such file or directory (os error 2)
wait  - compiling...
error - ./.yarn/__virtual__/next-virtual-17d35d2fd4/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/dev/error-overlay/websocket.js
Error: Failed to read source code from /Users/thomastheocharis/Documents/Code/test/.yarn/__virtual__/next-virtual-17d35d2fd4/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/dev/error-overlay/websocket.js

Caused by:
    No such file or directory (os error 2)
wait  - compiling...
error - ./.yarn/__virtual__/next-virtual-17d35d2fd4/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/dev/error-overlay/websocket.js
Error: Failed to read source code from /Users/thomastheocharis/Documents/Code/test/.yarn/__virtual__/next-virtual-17d35d2fd4/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/dev/error-overlay/websocket.js

Caused by:
    No such file or directory (os error 2)
```
I get different error message in next canary
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - ./.yarn/__virtual__/next-virtual-4db4fcd096/0/cache/next-npm-12.0.8-canary.17-79dd3330d3-3fdd0499b0.zip/node_modules/next/dist/client/route-announcer.js
Error: Failed to read source code from /Users/thomastheocharis/Documents/Code/test/.yarn/__virtual__/next-virtual-4db4fcd096/0/cache/next-npm-12.0.8-canary.17-79dd3330d3-3fdd0499b0.zip/node_modules/next/dist/client/route-announcer.js

Caused by:
    No such file or directory (os error 2)
wait  - compiling...
error - ./.yarn/__virtual__/next-virtual-4db4fcd096/0/cache/next-npm-12.0.8-canary.17-79dd3330d3-3fdd0499b0.zip/node_modules/next/dist/compiled/@next/react-dev-overlay/client.js
Module build failed: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received type number (-2147483639)
    at new Promise (<anonymous>)
wait  - compiling...
error - ./.yarn/__virtual__/next-virtual-4db4fcd096/0/cache/next-npm-12.0.8-canary.17-79dd3330d3-3fdd0499b0.zip/node_modules/next/dist/compiled/@next/react-dev-overlay/client.js
Module build failed: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received type number (-2147483639)
    at new Promise (<anonymous>)
```

### Expected Behavior

It should work out of the box

### To Reproduce

1. Install yarn [](https://yarnpkg.com/getting-started/install)
2. run `yarn create next-app --ts <name>`
3. run `yarn dev`

**Comment by balazsorban44** [comment] 2022-01-05 22:29
Duplicate of #32115

**Closed by balazsorban44** 2022-01-05 22:29 UTC
Labels: template: bug

**Comment by Markos-Th09** [comment] 2022-01-06 11:03
> Duplicate of #32115

It's not exactly duplicate because it has another error that only occurs in next canary

**Comment by balazsorban44** [comment] 2022-02-05 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
