### ISSUE TITLE
DEV Server Glitch

### ISSUE THREAD

**Issue by shadowtime2000** [vercel/next.js#21239] opened 2021-01-17 00:56 UTC
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

12

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**How are you deploying your application?**

N/A

**Describe the Bug**

After a couple changes the dev server kind of glitches and the browser stops adding the changes and when I reload it becomes an empty screen for a while and then I have to kill the dev server and close the tab and wait a few seconds and try again

**Expected Behavior**

it doesn't glitch and the changes just update

**To Reproduce**

Use the default `create-next-app` and launch the dev server and then create some changes and then check and do that a couple times and then it will kind of freeze

**Comment by timneutkens** [comment] 2021-01-17 16:02
This can't be reproduced based on the steps provided. Please provide more information

**Comment by KyleDavisDev** [comment] 2021-01-18 03:14
Just throwing it out there that I am running into this same issue as well. I am on v10.0.5 of nextjs. I noticed this glitch(?) when I was trying to update some text in one of my components and my page would never refresh with the updated content. I am even able to completely remove chunks of code out of my components and nothing changes in my browser.

Seems like the cache isn't getting updated correctly or something.

Thanks,
Kyle

**Comment by KyleDavisDev** [comment] 2021-02-05 00:52
Has there been any movement on this? I am still seeing this caching issue.

Please let m know if you need any more information.

Thanks,
Kyle

**Comment by ijjk** [comment] 2021-09-23 04:11
Hi, this sounds related to some Windows issues that are fixed in the latest version of Next.js `v11.1.3-canary.31`, please update and give it a try!

If you are still experiencing this after updating please respond with additional info to allow investigating further.

**Closed by ijjk** 2021-09-23 04:11 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
