### ISSUE TITLE
TypeError: (e.adapter || a.adapter) is not a function. when enabling concurrentFeatures

### ISSUE THREAD

**Issue by saurabhguptarock** [vercel/next.js#31297] opened 2021-11-11 11:10 UTC
### What version of Next.js are you using?

12.0.4-canary.5

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

> TypeError: (e.adapter || a.adapter) is not a function
    at e.exports (/Users/saurabhgupta/Desktop/Clense/Clense Web/.next/server/chunks/5539.js:1:29926)
    at c.request (/Users/saurabhgupta/Desktop/Clense/Clense Web/.next/server/chunks/5539.js:1:28349)
    at /Users/saurabhgupta/Desktop/Clense/Clense Web/.next/server/chunks/5539.js:1:33895
    at y (/Users/saurabhgupta/Desktop/Clense/Clense Web/.next/server/chunks/2104.js:1:15155)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

also
> ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization

### Expected Behavior

There should be no error and due to the above-mentioned error _middleware.tsx file redirect is also not working

### To Reproduce

Enable concurrentFeatures in next.config.js

**Comment by huozhi** [comment] 2021-11-11 16:14
Do you have the repro link that we can take a look for investigation? 🙏

**Comment by timneutkens** [comment] 2021-11-17 14:43
Closing as no reproduction was provided.

**Closed** 2021-11-17 14:43 UTC
Labels: please add a complete reproduction, template: bug, area: Concurrent Features

**Comment by balazsorban44** [comment] 2022-01-27 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
