### ISSUE TITLE
Image not showing

### ISSUE THREAD

**Issue by nazmulfahim** [vercel/next.js#26759] opened 2021-06-30 14:14 UTC
### What version of Next.js are you using?

^11.0.1

### What version of Node.js are you using?

v14.17.1

### What browser are you using?

Chrome , Edge, Firefox

### What operating system are you using?

Windows 10

### How are you deploying your application?

Vercel

### Describe the Bug

Image is not showing. if I use layout="responsive" property.

### Expected Behavior

Image should be show responsively.

### To Reproduce

I don't know.

**Comment by surjithctly** [comment] 2021-06-30 14:19
Please share your code or a link that reproduces the issue. Otherwise, it will be hard to debug for the maintainers. 

A good start will be re-creating your issue in codesandbox.com and share the link here.

**Comment by nazmulfahim** [comment] 2021-06-30 14:24
```
<Image
          src={`${product?.imageURL.replace(/\+/g,"%2B")}`}
          alt={product?.name}
          width={600}
          height={450}
          quality={80}
          // layout="responsive"
          priority={true}
        />
```

if I comment out the layout responsive field image doesn't show

**Comment by surjithctly** [comment] 2021-06-30 14:41
For "responsive" you also need to add a `width` and `height` to the parent element. 

eg: 

```
<div className="w-24 h-24">
<Image ... />
</div>
```

Hope that helps.

**Comment by nazmulfahim** [comment] 2021-06-30 14:53
Thank You,
my Parent component have width and height

  ```
    <div className={styles.productImage}>
        <Image
          src={`${product?.imageURL.replace( /\+/g,"%2B")}`}
          alt={product?.name}
          width={600}
          height={450}
          quality={80}
          // layout="responsive"
          priority={true}
        />
      </div>
```


image  class


```
 productImage: {
    maxWidth: "98vw",
    height: "auto",
    margin: "auto",
    [theme.breakpoints.up("sm")]: {
      maxWidth: "38vw",
    },
  },```

**Comment by nazmulfahim** [comment] 2021-06-30 14:57
Thanks this code is working

`
productImage: {
    width: "98vw",
    height: "100%",
    margin: "auto",
    [theme.breakpoints.up("sm")]: {
      width: "38vw",
    },
  },`

But is there a way to dynamically set width and height of Image compoent?

**Comment by surjithctly** [comment] 2021-06-30 15:01
Great,. 

From Next 11, Next.js automatically calculates width and height if you import it like:

```js
import SomeImage from "/public/img/img.jpg"
```

If you are loading images from somewhere else, you have to manually calculate width and height using a function.

**Comment by nazmulfahim** [comment] 2021-06-30 15:04
Can you provide any resource from where I can create that function? or perhaps the name of that kind of function

**Comment by surjithctly** [comment] 2021-06-30 16:10
I'm not an expert, but you can google `how to get width & height of an image dynamically in {your_tech_stack}`

**Comment by nazmulfahim** [comment] 2021-06-30 20:38
Yep I did that but it doesn't work properly with nextjs. Btw thanks and this issue is can be closed now as it is solved

**Comment by surjithctly** [comment] 2021-07-01 08:35
You can close it, or will wait for a core member to do that. Since I don't have the ability to close an issue.

**Closed** 2021-07-01 10:39 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
