### ISSUE TITLE
.env values are not available in the next.config.js in dev mode starting from 10.0.8

### ISSUE THREAD

**Issue by iAdramelk** [vercel/next.js#22985] opened 2021-03-11 17:48 UTC
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

15.8.0

### What browser are you using?

CLI

### What operating system are you using?

macOS

### How are you deploying your application?

local

### Describe the Bug

After updating from `10.0.7` to `10.0.8` `next.config.js` and files imported from it stopped seeing ENV variables defined in `.env` files. In production mode it still works correctly.

After downgrading to `10.0.7` it works again.

### Expected Behavior

Ir reads `.env` files content.

### To Reproduce

1. Add `VARIABLE_NAME=123` to `.env` file.
2. Add `console.log(process.env.VARIABLE_NAME)` to `next.config.js`.
3. Run `yarn next dev` in CLI.
4. Check CLI output for a line with `123`.

On `10.0.8` it return `undefined`, on `10.0.7` it returns `123`.

**Comment by underfisk** [comment] 2021-03-11 17:53
I do have the same result, my config is not even passing the image/domains so i assume something is not being correctly loaded from next.config.js

**Comment by ijjk** [comment] 2021-03-11 18:37
Closing as a duplicate of https://github.com/vercel/next.js/issues/22811

**Closed by ijjk** 2021-03-11 18:37 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 15:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
