### ISSUE TITLE
Automatic Language dectection seems to work only in Chrome when locale is only partially in locales

### ISSUE THREAD

**Issue by alveshelio** [vercel/next.js#18334] opened 2020-10-27 20:33 UTC
# Bug report

## In Firefox or Safari, automatic language detection doesn't seem to work properly if in locales we have ["pt-PT"] but Accept-Language is "pt" for example

According to the documentation: https://nextjs.org/docs/advanced-features/i18n-routing#automatic-locale-detection

> When a user visits the application root (generally /), Next.js will try to automatically detect which locale the user prefers based on the Accept-Language header and the current domain.

However, if in `next.config.js` we have `locales: ['en-CA', 'fr-CA', 'pt-PT']` and we've defined the browser language to `pt` then NextJS will fail to set locale as 'pt-PT' and will instead set `locale` as the `defaultLocale`

So unless the browser language is exactly the same as in locales, automatic language detection won't work.

## Clone this example https://github.com/vercel/next.js/tree/canary/examples/i18n-routing

Then change locales to something like ["en-CA", "fr-CA", "pt-PT"] or a language of your choice but it needs to be `xx-XX` and set `defaultLocale: "en-CA"
 
Then change your browser language to one of the languages in `locales` but instead make sure you only have `xx`, for example `en` or `fr` or `pt` or whatever languages you've added to your locales.

Navigate to the index page and you should be redirected to `http://localhost:3000/pt` or the language you've set your browser to.

Instead you stay on `http://localhost:3000`

I'm not sure it's a bug in NextJS though since it works in Chrome but fails in both Firefox and Safari.

**Comment by theostrahlen** [comment] 2020-10-28 09:22
I have the same issue but also in Chrome.
I have `locales: ['en-US', 'sv-SE']` in my `next.config.js` but automatic detection for Swedish only works if I change it to `sv`.

**Comment by ijjk** [comment] 2020-11-17 20:42
Closing in favor of https://github.com/vercel/next.js/issues/18676

**Closed by ijjk** 2020-11-17 20:42 UTC
Labels: kind: bug, point: 2

**Comment by balazsorban44** [comment] 2022-01-29 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
