### ISSUE TITLE
Spurious type errors when using without JSX

### ISSUE THREAD

**Issue by jameshfisher** [vercel/next.js#32032] opened 2021-12-02 09:50 UTC
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

not applicable

### Describe the Bug

As with React, Next.js users should not be forced to use JSX. However, Next.js projects do not currently typecheck without JSX.

The spurious type errors are due to React component typings in Next.js that demand callers to provide a `children` property, e.g. `children: ReactNode`. This is inconsistent with the official React typing, which makes the `children` property optional.

### Expected Behavior

Programs that typecheck should not then fail to typecheck after the JSX is stripped.

It should be possible to use Next.js without JSX.

### To Reproduce

Take any valid TypeScript+Next.js project, e.g. the `with-typescript` example, and desugar the JSX.

**Comment by jameshfisher** [comment] 2021-12-02 10:09
Related: https://github.com/microsoft/TypeScript/issues/46988

**Comment by lfades** [comment] 2021-12-02 14:57
Closing as this is not a Next.js bug, feel free to continue the conversation in the respective TypeScript repo.

**Closed by lfades** 2021-12-02 14:57 UTC
Labels: area: examples, template: bug, area: TypeScript

**Comment by balazsorban44** [comment] 2022-01-27 06:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
