### ISSUE TITLE
Blur placeholder won't switch to original image from placeholder image

### ISSUE THREAD

**Issue by milindsoorya** [vercel/next.js#27719] opened 2021-08-03 05:06 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.15.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

I am trying to enable the placeholder feature for nextjs 11. When using a CDN image link for the image component `src ` everything works fine. But, in my use case the image need to be cropped by the user and the cropped image is in Base64, when I give this to the image component `src ` the blurred placeholder is only being displayed it won't switch to the original image.

I use blurhash to create the hash for the image and then decode it in the client side and serve it to the Image component. 

### Expected Behavior

The placeholder image should switch to original image.

### To Reproduce

`<Image
    src={base64image}
    alt={"test image"}
    layout={"fill"}
    blurDataURL={decodedBlurHash}
    placeholder="blur"
/>`

**Comment by styfle** [comment] 2021-08-04 15:08
Hi @milindsoorya 

Try canary with `yarn add next@canary` and see if that fixes the issue.

If not, please share the the values for each of the props you're passing to `next/image`, thanks!

**Comment by zakiAzfar** [comment] 2021-08-04 15:14
how to use next js image component with framer motion, as we can't use `<motion.img />`

**Comment by milindsoorya** [comment] 2021-08-04 16:38
> Hi @milindsoorya
> 
> Try canary with `yarn add next@canary` and see if that fixes the issue.
> 
> If not, please share the the values for each of the props you're passing to `next/image`, thanks!

Hi, @styfle I will try that. After playing around it a bit the real issue is that a blur of 20% is the villian. It won't get removed even after the full size image is correctly loaded.

**Comment by ijjk** [comment] 2021-09-18 16:38
Closing as this appears to be working correctly in the latest version of Next.js and seems to be resolved per the above comment.

**Closed by ijjk** 2021-09-18 16:38 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
