### ISSUE TITLE
Update footer for next-site

### ISSUE THREAD

**Issue by chibicode** [vercel/next.js#14835] opened 2020-07-03 23:20 UTC
As a follow-up to https://github.com/vercel/next-site/pull/727, per our internal discussion.

**Comment by Timer** [comment] 2020-07-06 19:04
This was merged

**Closed by Timer** 2020-07-06 19:04 UTC
Labels: kind: story, point: 1

**Comment by balazsorban44** [comment] 2022-01-29 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
