### ISSUE TITLE
Example Typo:  Should be GET instead of "POST"

### ISSUE THREAD

**Issue by platocrat** [vercel/next.js#16876] opened 2020-09-05 20:36 UTC
# Bug report
In this [graphql api endpoint](https://github.com/vercel/next.js/blob/canary/examples/with-graphql-faunadb/graphql/api.js), the `useGuestbookEntries` query is a GET query, _not_ a POST query.

## Describe the bug
[On line 38](https://github.com/vercel/next.js/blob/ae7ae0ba68e4aacdad62415482b2179acc9e997c/examples/with-graphql-faunadb/graphql/api.js#L38), the data is fetched from FaunaDB with `useFetch`, but the method defined is "POST" on the following line. 

## To Reproduce

1. Go to https://github.com/vercel/next.js/blob/ae7ae0ba68e4aacdad62415482b2179acc9e997c/examples/with-graphql-faunadb/graphql/api.js#L25
2. Then, look at https://github.com/vercel/next.js/blob/ae7ae0ba68e4aacdad62415482b2179acc9e997c/examples/with-graphql-faunadb/graphql/api.js#L38 and 
https://github.com/vercel/next.js/blob/ae7ae0ba68e4aacdad62415482b2179acc9e997c/examples/with-graphql-faunadb/graphql/api.js#L39

3. See typo

## Expected behavior

Instead, the method should be "GET".

## Screenshots

<img width="507" alt="Screen Shot 2020-09-05 at 3 36 08 PM" src="https://user-images.githubusercontent.com/37757724/92313126-8809eb00-ef8d-11ea-8b73-f1ba7d590a1e.png">

## Additional Context

Compare with the `createGuestbookEntry` query [which is also has a "POST" method](https://github.com/vercel/next.js/blob/ae7ae0ba68e4aacdad62415482b2179acc9e997c/examples/with-graphql-faunadb/graphql/api.js#L73)

**Comment by Timer** [comment] 2020-09-12 05:19
Closing due to https://github.com/vercel/next.js/pull/16877#issuecomment-687872794

**Closed by Timer** 2020-09-12 05:19 UTC

**Comment by balazsorban44** [comment] 2022-01-29 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
