### ISSUE TITLE
Next.js often warning about full refresh

### ISSUE THREAD

**Issue by lmoisz03** [vercel/next.js#33952] opened 2022-02-03 19:21 UTC
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 14.18.1
      npm: 8.1.1
      Yarn: N/A
      pnpm: 6.25.0
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Microsoft edge

### What operating system are you using?

windows

### How are you deploying your application?

next start

### Describe the Bug

Fast refresh doesn't work as expected, ever since I updated to 12.0.9 and then 12.0.10, fast refresh stopped working and constantly warns about full refresh not working. I checked the error that the modal sent, however I did not reach any conclusion. I don't understand if the problem is about the version or a problem within my application.

Sometimes the fast refresh works from after each change without any problem, and then stops to show that annoying error.

### Expected Behavior

The changes should show up after every save without warning about such a problem.

### To Reproduce

- Run the project
- Edit a file
- Save the changes and wait till compile
- Fast refresh warns
![Captura web_3-2-2022_135422_localhost](https://user-images.githubusercontent.com/35237160/152413852-54cf01fc-7b7c-4700-969d-c6bfea6b79df.jpeg)

**Comment by lmoisz03** [comment] 2022-02-03 20:41
I'm checking again. I removed the middleware file and seems to be working.. I'll watch and if thats the problem i will let u know.

**Comment by Ali-Hussein-dev** [comment] 2022-02-03 21:05
yes I can also confirm it

**Comment by ijjk** [comment] 2022-02-03 21:21
Hi, this sounds like a duplicate of https://github.com/vercel/next.js/issues/31827 which is resolved in the latest canary of Next.js `v12.0.11-canary.4`, please update and give it a try!

**Comment by lmoisz03** [comment] 2022-02-03 22:10
> Hi, this sounds like a duplicate of #31827 which is resolved in the latest canary of Next.js `v12.0.11-canary.4`, please update and give it a try!

Yes sir! I figured it out. I was caused because middleware. Thanks, i will update. I will close issue.

**Closed** 2022-02-03 22:25 UTC
Labels: template: bug
