### ISSUE TITLE
Next build doesnt work with png imports

### ISSUE THREAD

**Issue by lucasReghiniM** [vercel/next.js#29308] opened 2021-09-22 21:45 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.17.3

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying your application?

next build

### Describe the Bug

While developing, an error appeared in an image import. However, the image rendered normally and appeared on the screen. However, when giving build, for some reason the script does not go through this step.

Following error:

```
yarn run v1.22.5
$ next build
info  - Loaded env from /media/XXX/ubuntuHD/workspace/XXX/landing/.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
Failed to compile.

./src/pages/index.tsx:8:24
Type error: Cannot find module '../assets/cards.png' or its corresponding type declarations.

   6 | 
   7 | //assets
>  8 | import cardsImage from "../assets/cards.png"
     |                        ^
   9 | import logo from "../assets/logo192.png"
  10 | 
  11 | export default function Home() {
error Command failed with exit code 1.
```

### Expected Behavior

Script build normally

### To Reproduce

Just run `yarn run build` with a png import

**Comment by lucasReghiniM** [comment] 2021-09-22 21:46
OBS: Canary dindt work

```
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN old lockfile styled-icons: No matching version found for styled-icons@10.41.0.
npm WARN old lockfile     at module.exports (/home/lucas/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /home/lucas/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/home/lucas/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:700:9)
npm WARN old lockfile  Could not fetch metadata for styled-icons@10.41.0 styled-icons: No matching version found for styled-icons@10.41.0.
npm WARN old lockfile     at module.exports (/home/lucas/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /home/lucas/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/home/lucas/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:700:9) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '10.41.0',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '0.1.0',  '0.2.0', '1.0.0', '1.1.0', '1.1.1',
npm WARN old lockfile     '1.2.0',  '1.3.0', '1.4.0', '1.5.0', '1.6.0',
npm WARN old lockfile     '1.7.0',  '2.0.0', '2.1.0', '2.2.0', '2.3.0',
npm WARN old lockfile     '2.3.1',  '2.3.2', '2.4.0', '3.0.0', '3.1.0',
npm WARN old lockfile     '3.2.0',  '3.3.0', '3.4.0', '3.5.0', '3.6.0',
npm WARN old lockfile     '3.7.0',  '4.0.0', '4.1.0', '4.2.0', '4.3.0',
npm WARN old lockfile     '5.0.0',  '5.1.0', '5.1.1', '5.2.0', '5.2.1',
npm WARN old lockfile     '5.2.2',  '5.3.0', '5.4.0', '5.5.0', '5.6.0',
npm WARN old lockfile     '5.7.0',  '5.8.0', '6.0.1', '6.1.0', '6.2.0',
npm WARN old lockfile     '6.2.1',  '6.3.0', '6.4.0', '6.5.0', '6.5.1',
npm WARN old lockfile     '6.6.0',  '6.7.0', '6.8.0', '6.9.0', '6.10.0',
npm WARN old lockfile     '6.11.0'
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '6.11.0' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: next@11.1.3-canary.30
npm ERR! node_modules/next
npm ERR!   next@"11.1.3-canary.30" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@">=10.2.0" from eslint-config-next@11.1.2
npm ERR! node_modules/eslint-config-next
npm ERR!   dev eslint-config-next@"11.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/lucas/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lucas/.npm/_logs/2021-09-22T21_40_54_358Z-debug.log

npm failed, show the debug log of the indeed npm wrapper:
command executed: npm install next@canary
command npm  install next@canary
```

**Comment by ijjk** [comment] 2021-09-22 21:54
Hi, we have tests covering this feature that are passing correctly so without a proper reproduction we aren't able to provide much guidance/investigate this.

**Comment by lucasReghiniM** [comment] 2021-09-22 22:04
> Hi, we have tests covering this feature that are passing correctly so without a proper reproduction we aren't able to provide much guidance/investigate this.

More information:

Import:
`import cardsImage from "../assets/cards.png"`

Usage:
`<Img src={liveCGILogo} />`

The babel.config.js:

```
module.exports = {
  presets: ["next/babel"],
  plugins: [
    ["styled-components", { "ssr": true }],
    'inline-react-svg'
  ]
}
```

The next.config.js:

const withImages = require('next-images')

```
module.exports = withImages({
  esModule: true,
  reactStrictMode: true,
  images: {
    disableStaticImages: true
  }

})
```

The next-env.d.ts (I remember in the past, if I put a `<reference types="next-images" />` in this file, it worked. But now the file is no longer editable): 

```
/// <reference types="next" />
/// <reference types="next/types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/basic-features/typescript for more information.

```

**Comment by ijjk** [comment] 2021-09-22 22:13
Ah ok so if `next-images` is being used you want to disable the built-in Next.js image handling here https://nextjs.org/docs/basic-features/image-optimization#disable-static-imports

This is caused by conflicting configs with the custom configuration and Next.js built-in handling. I'm gonna close this as the above config should resolve this.

**Closed by ijjk** 2021-09-22 22:13 UTC
Labels: please add a complete reproduction, template: bug

**Comment by lucasReghiniM** [comment] 2021-09-22 22:15
Thanks, 
just a question. I use that lib a long time ago. 
Do you recommend it to simulate the import of images as it is in react? I installed this lib in my project so I don't need to put assets in public!

**Comment by ijjk** [comment] 2021-09-22 22:18
I would recommend trying out the built-in Next.js image handling and removing `next-images` if you can.

**Comment by lucasReghiniM** [comment] 2021-09-22 22:20
i already removed the `next-images` to solve that build problem. 
Now I will try what you said. Because I want to import the images directly from src
Thanks a lot for the quick answer!!

**Comment by balazsorban44** [comment] 2022-01-27 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
