### ISSUE TITLE
Rewrites pages return 404 when Deploying to Vercel.

### ISSUE THREAD

**Issue by TomasSestak** [vercel/next.js#23782] opened 2021-04-07 18:39 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

12.19

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### How are you deploying your application?

vercel

### Describe the Bug

I'm trying to make custom routes for my multilanguage site. It works on localhost:3000 when running next dev, but when deploying to Vercel the rewrite doesn't work.

### Expected Behavior

When i create rewrite it should work also on page refresh when deploying to Vercel.

### To Reproduce

Clone this basict create-next-app https://github.com/TomasSestak/next-rewrites, visit /o-nas - see it working.
Then visit https://next-rewrites-chi.vercel.app/o-nas and see 404 page.

I'm not sure if I'm not missing something but I couldn't find and good examples on this. 
btw. Thank you for your awesome work on Next.js!

possible duplicate: https://github.com/vercel/next.js/issues/23288

**Comment by ijjk** [comment] 2021-04-07 18:50
Hi, the `destination` should be prefixed with the `locale` when using `locale: false` as mentioned in the documentation here https://nextjs.org/docs/api-reference/next.config.js/rewrites#rewrites-with-i18n-support

**Comment by ijjk** [comment] 2021-04-07 18:56
Going to close this since this doesn't appear to be a bug and is already documented. Please respond with additional information if still encountering problems with this after following the information in the above documentation link.

**Closed by ijjk** 2021-04-07 18:56 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 13:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
