### ISSUE TITLE
Next dev server is not closing when direct terminal close

### ISSUE THREAD

**Issue by thetejasmagade** [vercel/next.js#61284] opened 2024-01-28 13:32 UTC
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/github/vercel/next.js/tree/canary/examples/reproduction-template

### To Reproduce

codesandbox link is provided because field is required, there is no need of it.

1. start the application dev server npm run dev
2. close the terminal without closing dev server
3. now open new terminal and run dev server again

### Current vs. Expected behavior

Should, close dev server when terminal closes.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home Single Language
Binaries:
  Node: 20.11.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.0.0
  react-dom: 18.0.0
  typescript: 5.0.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

CLI (create-next-app)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by subh-cs** [comment] 2024-01-28 14:36
Hey, I don't think this is an valid issue because closing and killing terminal are two different things. In order to close server for every nodejs environment you've to kill the terminal. And yes, this is intentional. I just tested with latest release. I've killed the terminal and server stopped as expected. 

Thanks!!

**Comment by DeyvidJesus** [comment] 2024-01-30 13:06
I don't know whether it is a possibility or not, but I believe it would be a good idea to switch to Vite.js as soon as possible. In my opinion, it is way better than CRA, and it might solve the problems you're having.

Hope it helps!!

**Comment by balazsorban44** [comment] 2024-02-27 22:15
Closing as per: https://github.com/vercel/next.js/issues/61284#issuecomment-1913618431

If you think there is a bug where the process/terminal windows hangs even after trying to close/kill, please open a new bug report with an attached reproduction, as that might be considered a bug. I cannot reproduce given the CodeSandbox example though.

**Closed by balazsorban44** 2024-02-27 22:15 UTC
Labels: area: create-next-app, template: bug
