### ISSUE TITLE
[NEXT-599] Using searchParams in a RSC page component does not bail out to dynamic rendering

### ISSUE THREAD

**Issue by samtgarson** [vercel/next.js#44744] opened 2023-01-10 12:16 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.1.2-canary.4
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/samtgarson/appdir-reproduction-app

### To Reproduce

This could be a misunderstanding from my end, but it appears that the Next.js or Vercel caching behaviour does not take into consideration Search Params when caching pages?

https://appdir-reproduction-app.vercel.app/?page=1

If this is not a misunderstanding, **what is the intended method of supporting server generated pages with pagination, without server rendering every single request?**

To reproduce:
- create a RSC page in the new App Dir
- Use search params from the page props to interact with some data source (e.g. pagination in a database)
- **Do not use `useSearchParams`**, this issue is about server rendered pages not client rendered ones.

### Describe the Bug

- Run `next dev` and the search params are respected
- Run `next start` and the search params are ignored
- In the example reproduction, the page says `Page 0` regardless of the search param

### Expected Behavior

I would expect the page to show a version of the page with the search params respected.

### Which browser are you using? (if relevant)

Not relevant

### How are you deploying your application? (if relevant)

`next start`

<sub>[NEXT-599](https://linear.app/vercel/issue/NEXT-599/using-searchparams-in-a-rsc-page-component-does-not-bail-out-to)</sub>

**Comment by Fredkiss3** [comment] 2023-01-10 14:13
First thing first, you don't need to add `cache` to your function as cache is used to cache data and access in multiple places in your tree in one request. It does not cache data accross multiple requests. 
It is better used for when you want to get the user in a layout and in a page for ex and avoid fecthing it everytime.

Second, normally when you use `searchParams` nextjs should consider your page as dynamic, but in your case it considers the page as static, maybe it is a regression 🤔. You can still force your page to be dynamic by doing `export const dynamic = 'force-dynamic';` in your `page.tsx` file (see docs: https://beta.nextjs.org/docs/api-reference/segment-config#dynamic) .

hope it helps.

**Comment by samtgarson** [comment] 2023-01-10 14:51
Thanks the `cache` was just a desperate attempt to see if it triggered anything to work...

I'm aware of `force-dynamic` but is there no way to statically generate the initial page (with no search params) and enable dynamic for when the params are present?

**Comment by Fredkiss3** [comment] 2023-01-10 15:10
No, either the page is static or dynamic, but you can use `useSearchParams` in clients components to still have access to searchParams on static pages.

**Comment by Fredkiss3** [comment] 2023-01-10 17:12
It is definitely a regression bug, i am using next 13.1.1 on a project and when i build a page with searchParams it is interpreted as a dynamic page.

**Comment by samtgarson** [comment] 2023-01-10 18:17
You're using the `searchParams` prop on the page component, not `useSearchParams`, right? I'll rename the issue.

**Comment by Fredkiss3** [comment] 2023-01-10 18:47
Yes, `searchParams` prop on a server component

**Comment by faradaytrs** [comment] 2023-01-11 09:53
we use useSearchParams and consequence is the same, completely dynamic rendering

**Comment by samtgarson** [comment] 2023-01-11 10:00
@faradaytrs this [behaviour](https://beta.nextjs.org/docs/rendering/static-and-dynamic-rendering#using-dynamic-functions) is [documented](https://beta.nextjs.org/docs/api-reference/use-search-params)

**Comment by denniscual** [comment] 2023-01-11 15:46
Using search params in a segment will make the segment dynamic (render per request as oppose to pre-render it at build time). Due to this, theres no way that you can create a static version of it considering at build time, the value is not known. Thats also the same with cookies and headers, values are determined at the time of the request. [You can read the doc here](https://beta.nextjs.org/docs/rendering/static-and-dynamic-rendering#using-dynamic-functions).

**Comment by denniscual** [comment] 2023-01-11 15:55
`useSearchParams` is a hook that will only be used in Client Components where it renders in client not in the server. So technically speaking, it is not dynamic rendering but client side render.

**Comment by Fredkiss3** [comment] 2023-01-13 19:05
@samtgarson After experimenting to see if it was indeed working with the version i told you (`13.1.1`), it seems it didn't really. 
What i am seeing with `next@13.1.1`  is that even if you pass `searchParams` to the page, sometimes it correctly assume the page is dynamic (at least in my project, i was seeing the output of the page as dynamic), but it still try to pre-render the page at build time. 

So i tried to use your project and downgrade next to `13.1.1` but i was still having the same issue as yours, and i don't really know why... ? 

So i tried to just add `export const dynamic = 'force-dynamic';` to force the page into a dynamic rendering, and what my suprise was that next, even in `13.1.1` still try to pre-render the page at build time !
The only way around it was to also add `export const revalidate = 0`,  or use a request function like `headers()` or `cookies()`, when doing that next skip the pre-rendering all together and mark the page as dynamic.

Reproduction link here : https://stackblitz.com/edit/github-fwjfba?file=app%2Fsearch%2Fpage.tsx
I tweaked your example a little bit 

> **Note**
> I am using the term `pre-render` as a mean to say static site generation (SSG)

**Comment by filipkowal** [comment] 2023-01-26 15:40
I am experiencing the same issue. The page (Server Component) fetches data based on `searchParams`. It does not refetch on `searchParams` change, unfortunately. The fact that it does refetch in `dev` environment is confusing.

Setting the route as dynamic is a trade-off I would rather not take, as most of the time the route is used without searchParams. 
I've chosen the `app` directory mainly because of the performance gain of static rendering, which now is lost. 

Is there any other way to refetch on `searchParams` change in a Server Component? Are there plans to implement such a feature?

**Comment by Fredkiss3** [comment] 2023-01-26 15:59
@filipkowal if you use `searchParams` on your page, it would normally turn your page into a dynamic page.

If you want your page to be static but still be able to use search params, you would have to call `useSearchParams` in a client component and do your search in the client.

If you want to fetch your data with searchParams on a server components it have to be a dynamic page, because server components are only run in the server.

**Comment by balazsorban44** [comment] 2023-02-21 12:05
Thanks, we will look into this! Let me close it as a duplicate of #43077

**Closed by balazsorban44** 2023-02-21 12:05 UTC
Labels: template: bug, area: Routing, area: app, linear

**Comment by samtgarson** [comment] 2023-03-06 21:36
@balazsorban44 are you able to provide any update on the status of that issue? 

The issue has unfortunately been overrun by `+1`s but it does seem to be a critical issue for teams wanting to use RSC with search params (feels like a pretty common pattern for ecom and other pagination use cases)
