### ISSUE TITLE
On-demand revalidation shows outdated data when using <Link>

### ISSUE THREAD

**Issue by jopesh** [vercel/next.js#38306] opened 2022-07-04 19:25 UTC
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.15.1
      npm: 8.13.2
      Yarn: 1.22.19
      pnpm: 7.5.0
    Relevant packages:
      next: 12.2.1-canary.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

When using on-demand revalidation with Sanity.io GROQ webhooks, I encountered an issue similar to the one described in #35195. The revalidation proceeds without any errors. When visiting the page directly, the content updated as intended. But when visiting the page via the `<Link>` component, the page shows the stale data. This does not change after time (I've waited 12+ hours so far). It seems to be affecting dynamic routes especially (though I can't be too sure).

Below is a video of the reproduction repo showing the bug. The fresh dummy post data has no prose, whilst the previous version had. The dummy post shows the fresh data on external navigation or reloading the page. The old data shows on client-side navigation with `<Link>`.

https://user-images.githubusercontent.com/14236210/177207811-3cbeab95-fafa-4f36-ac4e-f917e0cc4929.mp4

### Expected Behavior

Revalidation of both the cached static page and the data route.

### Link to reproduction

https://github.com/jopesh/nextjs-issue-odr

### To Reproduce

- Create a dynamic route with data from Sanity.io based on the slug
- Fill in your data in Sanity Studio for the desired slug
- Build the Next.js app
- Update the content for the desired slug in the Sanity Studio
- Revalidate the desired slug via on-demand revalidation

**Comment by jopesh** [comment] 2022-07-06 15:23
Verified against next@12.2.1-canary.3

**Comment by ijjk** [comment] 2022-07-08 04:15
Hi, can you verify the data being sent as props in `getStaticProps` is different than the existing props?

**Comment by jopesh** [comment] 2022-07-08 12:01
All right, I tried by just logging the data in `getStaticProps`. I repeated the original steps and got the same result as described above in production. 

_Data at build time:_
```js
{
  _createdAt: '2022-07-04T18:48:06Z',
  _id: 'f0386451-352f-476c-a3d9-42614dfececd',
  _rev: 'o1F9UMohcy1KTaXxhtEZjW',
  _type: 'post',
  _updatedAt: '2022-07-08T11:50:45Z',
  body: [
    {
      _key: '9665ccf36e49',
      _type: 'block',
      children: [Array],
      markDefs: [],
      style: 'normal'
    },
    {
      _key: '58010428a71a',
      _type: 'block',
      children: [Array],
      markDefs: [],
      style: 'normal'
    },
    {
      _key: '82635b3e5a64',
      _type: 'block',
      children: [Array],
      markDefs: [],
      style: 'normal'
    },
    {
      _key: 'e385fdfe4fc8',
      _type: 'block',
      children: [Array],
      markDefs: [],
      style: 'normal'
    },
    {
      _key: '6829d75ce89f',
      _type: 'block',
      children: [Array],
      markDefs: [],
      style: 'normal'
    }
  ],
  image: {
    _type: 'image',
    asset: {
      _ref: 'image-a7c0ba547263879831c7d617356d938188090764-1000x500-jpg',
      _type: 'reference'
    }
  },
  slug: { _type: 'slug', current: 'test' },
  title: 'Test'
}
```

Then I updated the post once more, removing the body text.

_Revalidation run data:__
```js
{
  _createdAt: '2022-07-04T18:48:06Z',
  _id: 'f0386451-352f-476c-a3d9-42614dfececd',
  _rev: 'IFAPOPWlCM0oi0S7fHBjQT',
  _type: 'post',
  _updatedAt: '2022-07-08T11:54:49Z',
  image: {
    _type: 'image',
    asset: {
      _ref: 'image-a7c0ba547263879831c7d617356d938188090764-1000x500-jpg',
      _type: 'reference'
    }
  },
  slug: { _type: 'slug', current: 'test' },
  title: 'Test'
}
```

**Comment by jmotes** [comment] 2022-07-11 19:28
Strangely, I am having the opposite issue. Thought I'd mention incase it could help diagnose.

Client-side nav works fine, but on a full page load I briefly see the updated content before it reverts back to the original. Oddly enough, I cannot reproduce the problem on preview deployments - only production ones.

**Comment by ijjk** [comment] 2022-07-11 22:26
@jopesh I'm having trouble reproducing this, are you able to reproduce this on a more minimal example without querying sanity e.g. just returning a timestamp in props and seeing the timestamp fail to update after a revalidation?

**Comment by denisjankovic** [comment] 2022-07-12 07:42
Have the same issue here

**Comment by jopesh** [comment] 2022-07-12 10:35
@ijjk Gotcha, I was able to reproduce the same issue with your idea and put up another repo: https://github.com/jopesh/nextjs-issue-odr-simple (Link: https://nextjs-issue-odr-simple.vercel.app/). 

I've added a non-dynamic route (`/static.tsx`) with its own revalidation API route (`/api/revalidate-static`) and it turns out that the issue only appears on the dynamic route (`/blog/[slug].tsx` with API route `/api/revalidate-dynamic`) as suspected. 

After revalidating both example routes, the following happens in this reproduction _(Build time was 10:25:08)_:

**Dynamic route shows build-time data on client-side navigation**
![CleanShot 2022-07-12 at 12 31 03](https://user-images.githubusercontent.com/14236210/178470549-c37e50f6-7b24-494d-82dc-92ed0d543068.png)

**Dynamic route shows revalidated data on hard reload**
![CleanShot 2022-07-12 at 12 31 29](https://user-images.githubusercontent.com/14236210/178470613-6d71958d-5a03-4d70-a37c-3a707cbd08d7.png)

**The static route shows the revalidated data on both ways as intended** 
![CleanShot 2022-07-12 at 12 32 33](https://user-images.githubusercontent.com/14236210/178470817-91febb4a-65be-4bd4-ab1c-2d383a2f5b9c.png)

**Comment by ijjk** [comment] 2022-07-13 21:51
@jopesh thanks for that reproduction, I've narrowed in on the issue here and will respond here when we have an update!

**Comment by mediabeastnz** [comment] 2022-07-13 22:07
@jopesh i've tested the cms-sanity-example repo and this issue occurs there also just FYI

**Comment by mediabeastnz** [comment] 2022-07-14 21:45
Sorry one last thing I've noticed is that this isn't necessarily a "On demand ISR" issue, it also occurs when you simply rely on ISR (no on demand) to rebuild pages in the background.

**Comment by BrandonNoad** [comment] 2022-07-14 23:20
I am using On-Demand ISR on my site. I have a job that runs daily that adds new data, then calls `revalidate` on any pages that need to be updated. It seemed to be working fine, but at some point today, my site reverted to showing pages that were several days out-of-date.

**Comment by ijjk** [comment] 2022-07-15 16:59
Hi, a related fix for this has now been landed, please re-deploy your project and give it a try!

A new deployment of the reproduction with the fix applied can be seen here https://nextjs-issue-odr-simple-riad3lztu-ijjk-testing.vercel.app/blog/dynamic

**Closed by ijjk** 2022-07-15 16:59 UTC
Labels: template: bug

**Comment by Sinhalite** [comment] 2022-07-15 23:10
I think it's working fine!

Thanks guys😀

**Comment by alexrabin** [comment] 2022-07-20 16:39
Is this issue only fixed on Vercel? I'm using Microsoft Azure and I am having this issue

**Comment by jmotes** [comment] 2022-07-20 16:42
@alexrabin I would say so since v12.2.3 isn't out yet. I think it's in the canary though.

**Comment by alexrabin** [comment] 2022-07-20 16:44
@jmotes this is working for all platforms on latest canary release or just Vercel?

**Comment by jmotes** [comment] 2022-07-20 18:52
@alexrabin I can't say for sure (@ijjk) would be the one to say, but from looking at his PR (https://github.com/vercel/vercel/pull/8158) I'd say it should be working for all platforms if you're on canary.

**Comment by ijjk** [comment] 2022-07-20 19:25
@alexrabin it sounds like you may have a CDN configured in front of your Next.js application causing your Azure deployment not to be able to fetch the updated content. For On-Demand ISR to work properly your CDN either needs to be aware of the feature like on Vercel or disable CDN caching for those paths.

**Comment by alexrabin** [comment] 2022-07-20 20:05
@ijjk we don't have a CDN configured in front of our Next.js application. Are there any other possibilities?

**Comment by ijjk** [comment] 2022-07-20 20:20
@alexrabin it's hard to say without a deployment/reproduction to investigate since it does sound related to your custom setup.
