### ISSUE TITLE
webpack-hmr infinite loop

### ISSUE THREAD

**Issue by Alexn117** [vercel/next.js#20726] opened 2021-01-04 03:21 UTC
# Bug report

## Describe the bug

There seems to be an infinite loop of EventStream data and requests related to webpack-hmr.

## To Reproduce

1. `npx create-next-app`
2. `npm run dev`
3. Navigate to `http://localhost:3000`
4. Inspect the page and go to the Network tab
5. Reload the page to start recording network activity
6. Click on `http://localhost:3000/_next/webpack-hmr?page=/` and go to the EventStream tab
7. There will be an infinite loop of data and the requests will continue over time

## Expected behavior

No infinite loop.

## System information

- OS: macOS Catalina, Version 10.15.7 (19H114)
- Browser: Google Chrome - Version 87.0.4280.88 (Official Build) (x86_64)
- Version of Next.js: 10.0.4
- Version of Node.js: v14.15.3

**Comment by ijjk** [comment] 2021-01-04 04:12
Hi, this isn't an infinite loop per-se and is expected. Periodic data is sent over this connection, one type being a ping which lets us know the connection is still successfully established and then another being the page's status for ondemand entries. Note: this data will only be sent when the tab is active and visible as we close the connection when not being used. 

I'm going to close this since this isn't a bug and is expected.

**Closed by ijjk** 2021-01-04 04:12 UTC
Labels: template: bug

**Comment by Alexn117** [comment] 2021-01-05 18:13
> Hi, this isn't an infinite loop per-se and is expected. Periodic data is sent over this connection, one type being a ping which lets us know the connection is still successfully established and then another being the page's status for ondemand entries. Note: this data will only be sent when the tab is active and visible as we close the connection when not being used.
> 
> I'm going to close this since this isn't a bug and is expected.

Are these connections only in development mode?

I’m using ngrok to test a project on mobile and it’s using up the free 40 connections / minute limit quite fast. It seems because of these connections that are running in the background and repeat.

**Comment by ijjk** [comment] 2021-01-05 18:28
Yes, the webpack-hmr connection is only used in development to provide live updates when making changes in development.

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
