### ISSUE TITLE
Build error - Cannot get final name for export 'encodeXML'

### ISSUE THREAD

**Issue by mr-scrpt** [vercel/next.js#58643] opened 2023-11-19 09:35 UTC
### Link to the code that reproduces this issue

https://github.com/mr-scrpt/stackoverflow/tree/26_06-edit-profile

### To Reproduce

Start app `pnpm build` or `yarn build` or `npm build`

### Current vs. Expected behavior

**Current**
Failed to compile.
```

./node_modules/.pnpm/cheerio@1.0.0-rc.12/node_modules/cheerio/lib/esm/index.js + 69 modules
Cannot get final name for export 'encodeXML' of ./node_modules/.pnpm/entities@4.5.0/node_modules/entities/lib/esm/index.js


> Build failed because of webpack errors
   Creating an optimized production build  . ELIFECYCLE  Command failed with exit code 1.

```
**Expected**
Build app

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: 8.10.0
Relevant Packages:
  next: 14.0.4-canary.4
  eslint-config-next: 14.0.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

Everything was working correctly a few days ago. Today I noticed a problem. Initially the project was on next 14.0.1, later I upgraded it to 14.0.3, tried downgrade to 14.0.1 and upgrade to 14.0.4-canary.4 - didn't solve the problem. Google says that I need to downgrade Resend package to version 1, but I don't use this package
No problems detected in development mode

**Comment by mr-scrpt** [comment] 2023-11-19 18:22
I apologise. The error is gone. I don't understand why, it just gone, there were other errors with clear description, I fixed them and the build works now

**Comment by yannxaver** [comment] 2023-11-24 04:47
> I apologise. The error is gone. I don't understand why, it just gone, there were other errors with clear description, I fixed them and the build works now

I'm facing the same error, but there are no other errors that I could potentially fix.

**Comment by romanwbruce** [comment] 2023-11-24 22:34
> > I apologise. The error is gone. I don't understand why, it just gone, there were other errors with clear description, I fixed them and the build works now
> 
> I'm facing the same error, but there are no other errors that I could potentially fix.

Same, No idea what to look at. Tried using the latest canary versions of nextjs but no luck.

**Comment by dBianchii** [comment] 2023-11-26 14:28
Same issue here.

**Comment by Heechem** [comment] 2023-11-26 14:57
same here , cant proceed to the build

**Comment by jer-k** [comment] 2023-11-27 15:40
> Google says that I need to downgrade Resend package to version 1, but I don't use this package

I am using `resend` and ran into this. I thought I would share the links to the issues over there for anyone else who comes across this issue. It might also help to uncover a root cause?

The resolution from https://github.com/resendlabs/resend-node/issues/256 is to upgrade `resend` to `"^2.1.0-canary.1"`. The PR with the fix - https://github.com/resendlabs/resend-node/pull/259

**Comment by michaelangeloio** [comment] 2023-11-27 16:35
I also have this issue and I do not use `resend`

**Comment by jer-k** [comment] 2023-11-27 16:47
The `resend` issue linked to https://github.com/vercel/next.js/issues/39375 which has a helpful comment https://github.com/vercel/next.js/issues/39375#issuecomment-1380443503

> Alright. I've researched this for quite some while now. What I reported above seems to hold true.

Now for people searching for a SOLUTION only I have exactly 2 proposals for you:

Clean one: Go to the affected repository of the "problematic" library and make sure they export the ESM files with .mjs extension and/or have it set type: "module" in the package.json

Workaround: Abuse your next.config.js:

const nextConfig = {
 experimental: {
    transpilePackages: ["problematic-package", "other-problematic-package", "etc", "..."],
  },
}
Warning: This isn't a clean solution so only do this when you are beyond desperate.

**Comment by mr-scrpt** [comment] 2023-11-29 13:45
I'm getting this error again. I don't understand what the reason is. There is no any explanation for it. The first time it just disappeared, probably due to refactoring, but now I don't see any errors, but I can't look through every file of the project, maybe there are errors somewhere, but there may be thousands of files and where exactly the error is and what it may be is not clear at all

**Comment by mr-scrpt** [comment] 2023-11-29 17:48
I think I found the cause of my problem.
I disabled all pages of my application and left only one page. Then I started disabling components and eventually I found the point where I was having the problem, which is this component```

```
'use client'

import { ActionTypeEnum } from '@/types/shared'
import { FC, HTMLAttributes } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { deleteAnswer } from '@/lib/actions/answer.action'
import { deleteQuestion } from '@/lib/actions/question.action'

interface CardActionBarProps extends HTMLAttributes<HTMLDivElement> {
  type: ActionTypeEnum
  itemId: string
  slug?: string
}

export const CardActionBar: FC<CardActionBarProps> = (props) => {
  const { slug, itemId, type } = props
  const pathname = usePathname()
  const handleDelete = async () => {
    if (type === ActionTypeEnum.QUESTION) {
      await deleteQuestion({ questionId: itemId, path: pathname })
    } else if (type === ActionTypeEnum.ANSWER) {
      await deleteAnswer({ answerId: itemId, path: pathname })
    }
  }
  return (
    <div className="flex items-center justify-end gap-3 max-sm:w-full">
      {type === ActionTypeEnum.QUESTION && (
        <Link href={`/question/edit/${slug}`}>
          <Image
            src="/assets/icons/edit.svg"
            alt="edit"
            width={14}
            height={14}
            className="cursor-pointer object-contain"
          />
        </Link>
      )}

      <Image
        src="/assets/icons/trash.svg"
        alt="delete"
        width={14}
        height={14}
        onClick={handleDelete}
        className="cursor-pointer object-contain"
      />
    </div>
  )
}
```

It has a function that calls the server action
`await deleteAnswer({ answerId: itemId, path: pathname })`
Here is the code of this server action

```
export const deleteAnswer = async (params: IDeleteAnswerParams) => {
  try {
    connectToDatabase()

    const { answerId, path } = params

    const answer = await AnswerModel.findById(answerId)

    if (!answer) throw new Error('Answer not found')

    // delete answer within quesiton and interaction
    await AnswerModel.deleteOne({ _id: answerId })
    await QuestionModel.updateMany(
      { answer: answerId },
      { $pull: { answers: answerId } }
    )
    await InteractionModel.deleteMany({ answer: answerId })

    revalidatePath(path)
  } catch (error) {
    console.log(error)
    throw error
  }
}
```

BUT! The problem is not in it, but in the actions that lie next to it, e.g.
```

export const getAnswerSearchByContent = async (
  content: string,
  limit?: number
): Promise<any> => {
  try {
    connectToDatabase()
    const regexQuery = { $regex: content, $options: 'i' }

    let query = AnswerModel.find({ content: regexQuery }).populate({
      path: 'question',
      model: QuestionModel,
      select: 'slug title',
    })
    if (limit) {
      query = query.limit(limit)
    }
    const response = await query

    return toPlainObject(response)
  } catch (error) {
    console.log(error)
    throw error
  }
}
```
Here, before returning the data from the action, I process it **toPlainObject(response)**
And here is the code for this function
`export const toPlainObject = (obj: any) => JSON.parse(JSON.stringify(obj))`
Why am I doing this? The problem is that I'm using mongoDB which stores, for example, id as objects, and if I try to work with this in client components, I get an error. 
`Warning: Only plain objects can be passed to Client Components from Server Components`
That's why I process the responses from mongoDB immediately in the server action, so that I don't have to do it all the time in the components, because I think it's strange to tie a component to a database implementation. So what to do

**Comment by mr-scrpt** [comment] 2023-11-29 18:06
I found a function that causes an error in my project.
```
import * as cheerio from 'cheerio'

export const parseHTMLToString = (html: string) => {
  const $ = cheerio.load(html)
  return $.text()
}

```

**Comment by romanwbruce** [comment] 2023-11-30 18:01
> > Google says that I need to downgrade Resend package to version 1, but I don't use this package
> 
> I am using `resend` and ran into this. I thought I would share the links to the issues over there for anyone else who comes across this issue. It might also help to uncover a root cause?
> 
> The resolution from [resendlabs/resend-node#256](https://github.com/resendlabs/resend-node/issues/256) is to upgrade `resend` to `"^2.1.0-canary.1"`. The PR with the fix - [resendlabs/resend-node#259](https://github.com/resendlabs/resend-node/pull/259)

this worked for me

**Comment by huozhi** [comment] 2023-12-02 09:36
We landed a [fix](https://github.com/vercel/next.js/pull/58967) in [14.0.4-canary.33](https://github.com/vercel/next.js/releases/tag/v14.0.4-canary.33), I cloned the repro and built successfully with that version. Can you try upgrade?

**Closed** 2023-12-04 10:17 UTC
Labels: template: bug

**Comment by samasri** [comment] 2023-12-05 20:55
@huozhi I just tried this 14.0.4-canary.33 but I'm still having this issue. Specifically having it with `@casl/prisma`

```
   ▲ Next.js 14.0.4-canary.33
   - Environments: .env

Failed to compile.

./node_modules/@casl/prisma/dist/es6m/index.mjs + 7 modules
Cannot get final name for export 'defaultParsers' of ./node_modules/@ucast/mongo/dist/es6m/index.mjs


> Build failed because of webpack errors
   Creating an optimized production build  .
```

**Comment by huozhi** [comment] 2023-12-05 21:15
@samasri does latest canary work for it? if it still doesn't work can you file a new reproduction for your case, thanks.

**Comment by samasri** [comment] 2023-12-05 21:18
It still doesn't. I'll file a new reproduction, thank you

**Comment by devlopersabbir** [comment] 2023-12-14 13:03
I'm facing the same issue, I have already did everything based on #58643 issue also `resend` issue comments. but I still faced that issue.


```
> next build

   ▲ Next.js 14.0.1
   - Environments: .env

Failed to compile.

./node_modules/.pnpm/html-to-text@9.0.5/node_modules/html-to-text/lib/html-to-text.mjs + 24 modules
Cannot get final name for export 'encodeXML' of ./node_modules/.pnpm/entities@4.5.0/node_modules/entities/lib/esm/index.js


> Build failed because of webpack errors
   Creating an optimized production build  . ELIFECYCLE  Command failed with exit code 1.
```

**Comment by huozhi** [comment] 2023-12-14 13:33
@devlopersabbir please upgrade to latest nextjs, you're using the version (14.0.1) without the fix

**Comment by devlopersabbir** [comment] 2023-12-14 20:10
@huozhi no dear,

here is my all dependency.. please check and let me know.

```
"dependencies": {
    "@radix-ui/react-dropdown-menu": "^2.0.5",
    "@radix-ui/react-separator": "^1.0.3",
    "@radix-ui/react-slot": "^1.0.2",
    "@react-email/components": "^0.0.12",
    "@react-email/tailwind": "^0.0.13",
    "@types/node": "^20.10.4",
    "@types/react": "^18.2.45",
    "@types/react-dom": "^18.2.17",
    "autoprefixer": "^10.4.16",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.0.0",
    "eslint": "^8.55.0",
    "eslint-config-next": "^14.0.4",
    "lucide-react": "^0.263.1",
    "next": "v14.0.5-canary.12",
    "next-themes": "^0.2.1",
    "postcss": "^8.4.32",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "resend": "^2.0.0",
    "sonner": "^1.2.4",
    "swiper": "^10.1.0",
    "tailwind-merge": "^1.14.0",
    "tailwindcss": "3.3.3",
    "tailwindcss-animate": "^1.0.6",
    "typescript": "5.1.6"
  }
```

**Comment by johanguse** [comment] 2023-12-23 18:25
> #39375 (comment)

Add transpilePackages: ['html-to-text'], to next config.
works for me!

![image](https://github.com/vercel/next.js/assets/6184866/c522add0-e4cc-4214-b7c2-a54a86518adc)
