### ISSUE TITLE
Custom process.env variables not available in docker standalone output

### ISSUE THREAD

**Issue by florianliebig** [vercel/next.js#53367] opened 2023-07-31 08:03 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:21:34 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8112
    Binaries:
      Node: 18.16.0
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: 8.6.2
    Relevant Packages:
      next: 13.4.13-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: standalone
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Operating System (Windows, MacOS, Linux), Standalone mode (output: "standalone")

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/florianliebig/nextjs-error-docker-13.4.13

### To Reproduce

# Steps to reproduce

```sh
docker build -t next-test --no-cache . && docker run -p 3000:3000 --env API_BASE=https://www.google.com --name next-test next-test
```

Visit any page, check for API_BASE in Node terminal. process.env is console.logged in middleware.ts. API_BASE will not be available in process.env

Downgrade next in package.json to 13.4.12. Run npm i and rerun the commands above. API_BASE will be available.

Also see readme of my repository: https://github.com/florianliebig/nextjs-error-docker-13.4.13

### Describe the Bug

I am using the default docker setup with middleware in app dir. I am defining environment variables using docker context, not .env file.

Beginning from 13.4.13-canary.0 only a few next internal environment variables are available in that position

### Expected Behavior

All node & docker context environment variables are available at that position

### How are you deploying your application? (if relevant)

docker with OrbStack

<sub>[NEXT-1508](https://linear.app/vercel/issue/NEXT-1508/custom-processenv-variables-not-available-in-docker-standalone-output)</sub>

**Comment by florianliebig** [comment] 2023-08-03 13:37
Just tried to avoid process.env in middleware and it seems that the process.env variables are not available in the whole application. Not only middlewares

**Comment by homburg** [comment] 2023-08-07 07:28
Still an issue in released version v13.4.13 AFAICT

And not specific to docker, but any source of environment variables.

**Comment by florianliebig** [comment] 2023-08-07 07:43
Seems to be related / same as https://github.com/vercel/next.js/issues/53579

**Comment by opeologist** [comment] 2023-08-07 17:11
can confirm this issue appeared in `13.4.13` and works as expected in `13.4.12`. having to pin to `13.4.12` until this is resolved

**Comment by balazsorban44** [comment] 2023-08-11 12:35
@markspolakovs tracked https://github.com/vercel/next.js/issues/53579#issuecomment-1671769964 this down to https://github.com/vercel/next.js/commit/1398de9977b89c9c4717d26e213b52bc63ccbe7e, thanks!

**Comment by DominicWrege** [comment] 2023-08-15 06:31
Any timeline when it will be fixed and released?

**Comment by belgattitude** [comment] 2023-08-15 10:29
@DominicWrege by chance have you tried with latest release ?

**Comment by markspolakovs** [comment] 2023-08-15 10:45
> @DominicWrege by chance have you tried with latest release ?

Still reproducible as of `13.4.16-canary.1`.

**Comment by k725** [comment] 2023-08-15 10:48
Yup. Well, currently there doesn't seem to be any workaround other than pinning it to 13.4.12.

https://github.com/florianliebig/nextjs-error-docker-13.4.13
The PoC he created also does not output console logs with the current Canary.

**Comment by DominicWrege** [comment] 2023-08-15 11:22
@belgattitude Yes it is still broken for me in 13.4.13, 13.4.14, 13.4.15 and 13.4.16  😥

**Comment by klarstrup** [comment] 2023-08-15 14:11
Did runtime `process.env` access get deprecated alongside the `getConfig` API?

I wonder what is supposed to be the "correct" way of doing runtime configuration for Next.js these days, if neither of these are tested or supported 🤔

**Comment by timmywil** [comment] 2023-08-15 14:15
It's a bug. Specifically, it's a regression caused by a refactor. I'm not 100% sure which one, but #53579 suggests 1398de9977b89c9c4717d26e213b52bc63ccbe7e

**Comment by nicholasgriffintn** [comment] 2023-08-16 12:30
> Did runtime `process.env` access get deprecated alongside the `getConfig` API?
> 
> I wonder what is supposed to be the "correct" way of doing runtime configuration for Next.js these days, if neither of these are tested or supported 🤔

Fair point on it not being tested or supported though given it happened, and doesn't appear to be a priority.

This blocks a whole range of use cases, not just Docker installs (the other cases are in the related, closed issues)

**Comment by abaracedo** [comment] 2023-08-16 13:53
I tried v13.4.12 and I still have the same issue when building the application in my environment. I tried moving to v13.4.8, the version I started working on the project and stills having the same issue...

**Comment by himrocks33** [comment] 2023-08-16 17:50
I have the issue on v13.4.9 I have not found a version that fixes this issue in 13.4.*   @abaracedo have you found a working version?  Thanks.

**Comment by DominicWrege** [comment] 2023-08-16 21:04
@himrocks33 try 13.4.12

**Comment by himrocks33** [comment] 2023-08-16 22:15
@DominicWrege I cannot get any version of 13.4.* to load environment variables anymore. I’ve tried every one at this point. It’s ridiculous that this issue hasn’t been resolved yet or even worked on.

**Comment by dstarosta** [comment] 2023-08-17 00:52
Also, outside the docker production builds load env files twice in13.4.13+.
https://github.com/vercel/next.js/issues/52641

**Comment by charleskoehl** [comment] 2023-08-17 05:21
I am seeing this bug in an nx monorepo when I serve an app locally using "nx serve myapp"

@florianliebig I'm not sure your [repro repo](https://github.com/florianliebig/nextjs-error-docker-13.4.13) demonstrates the error though, because I don't think process.env alone will contain anything. I believe the build process replaces specific env vars with their values by searching and replacing /\bprocess\.env\.[A-Z_]+\b/ or some similar pattern.

**Comment by florianliebig** [comment] 2023-08-17 05:40
@charleskoehl 

> I believe the build process replaces specific env vars with their values by searching and replacing /\bprocess.env.[A-Z_]+\b/ or some similar pattern.

No only the pattern NEXT_PUBLIC env variables are replaced during build: https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser

In the steps to reproduce, I provide env variables via the docker run --env parameter. It doesn't matter if those come via .env file or docker context. It seems that the standalone server is not able to access them via process.env

**Comment by charleskoehl** [comment] 2023-08-17 05:40
> @DominicWrege I cannot get any version of 13.4.* to load environment variables anymore. I’ve tried every one at this point. It’s ridiculous that this issue hasn’t been resolved yet or even worked on.

I downgraded to next@13.3.4 and same thing.

**Comment by charleskoehl** [comment] 2023-08-17 05:51
well this is interesting: when I asked pi.ai what it thought about the issue, it wrote,

"Yes, I'm familiar with this issue. Essentially, Next.js has a special mechanism for loading environment variables, and it doesn't work with the middleware.js file. This is because the middleware.js file is run before the environment variables are loaded. So, when you try to access the environment variables in middleware.js, they're not available yet. There are a few possible solutions to this problem. You could try using a different mechanism for loading environment variables, like a package like dotenv-webpack."

I asked, "where is it documented that the middleware file is run before any env vars are loaded?"

pi.ai replied, "I haven't found any official documentation from the https://next.js/s team about this, but the community has confirmed this behavior on various forums and chat groups. I think the issue is that the https://middleware.js/s file is run as part of the webpack build process, which happens before the environment variables are loaded. This is because https://next.js/s uses webpack to build the application and load the environment variables. I'd recommend checking out the https://next.js/s docs for more information about the build process."

So, I wonder if the middleware.js file was erroneously able to access process.env and they just "fixed" it so it can't??

**Comment by abaracedo** [comment] 2023-08-17 06:45
> I have the issue on v13.4.9 I have not found a version that fixes this issue in 13.4.* @abaracedo have you found a working version? Thanks.

I didn't...I'm checking all the deps I updated last week in case any can affect env vars... but I don't think that's the cause when we have the same problem :sweat_smile: 

I tried to run every version with `$ MY_ENV_VAR="a value" npm run server` and the env var is `undefined`

**Comment by charleskoehl** [comment] 2023-08-17 06:49
found this related discussion: https://github.com/vercel/next.js/discussions/36338

**Comment by nicholasgriffintn** [comment] 2023-08-17 08:35
If y'all read the other comments rather than adding your own thoughts and asking ai for some reason you'll know that we already know what the issue is...

> It's a bug. Specifically, it's a regression caused by a refactor. I'm not 100% sure which one, but #53579 suggests 1398de9977b89c9c4717d26e213b52bc63ccbe7e

It's a bug introduced in .13 that needs to be resolved.

**Comment by himrocks33** [comment] 2023-08-17 12:48
Frustrating that they release a bug fix version seems like every 2-3 days and this issue does not seem to even be on anyone from the Next team's radar yet.  Not assigned, no pending PR.  CD pipelines are useless without environment variables.

**Comment by himrocks33** [comment] 2023-08-17 13:24
Okay I was able to implement a workaround... It does seem like `13.4.12` is functional.  The problem I was having was that the new route handlers I implemented were caching the response rather than dynamically evaluating.  

In order to fix this I just passed the current time as a query parameter so that it basically would never cache this data and rather evaluate it at runtime.

https://nextjs.org/docs/app/building-your-application/routing/route-handlers#opting-out-of-caching

<pre>export async function GET(request: Request) {

    const { searchParams } = new URL(request.url)
    const requestTime = searchParams.get('request_time')

    return NextResponse.json({
        ... all my other env variables I need on FE,
        REQUEST_TIME: requestTime
    })
}
<pre>

**Comment by pluma** [comment] 2023-08-17 14:28
> well this is interesting: when I asked pi.ai what it thought about the issue

Maybe don't ask LLMs to figure out bugs in software for you because they're literally just built to generate plausible answers not understand your problem or the code itself. They're fully automated improv theater, not expert systems.

If you feed the entire source code into an AI built to reason about code in that language and then ask it to explain the bug, that's a different thing but last time I checked GitHub Copilot wasn't quite there yet and most startups just repackage regular LLMs with custom prompts.

**Comment by klarstrup** [comment] 2023-08-17 20:21
What the fsck did you just say about me you little git I'll have you know that I have over 300 confirmed acquisitions and am trained in consultancy services

**Closed** 2023-08-18 14:04 UTC
Labels: template: bug, area: standalone mode, linear: next, area: OS
