### ISSUE TITLE
Land sharedLambdas in @vercel/next to stable

### ISSUE THREAD

**Issue by timneutkens** [vercel/next.js#14815] opened 2020-07-03 11:05 UTC
@ijjk has been working on this

**Comment by ijjk** [comment] 2020-07-06 13:54
Closing as this has now been landed

**Closed by ijjk** 2020-07-06 13:54 UTC
Labels: kind: story, point: 5

**Comment by balazsorban44** [comment] 2022-01-29 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
