### ISSUE TITLE
Add eslint rule for importing `next/head` in `pages/_document.js`

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#13958] opened 2020-06-09 16:20 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Users should not be allowed to import `next/head` in `pages/_document.js`.

This causes unexpected / broken application behavior.

## Describe the solution you'd like

We should tell the user to import `Head` from `next/document` instead.

---

Fixes #14227
Related #14425

**Comment by TodorTotev** [comment] 2020-06-09 16:22
re [13712](https://github.com/vercel/next.js/issues/13712)

**Comment by Timer** [comment] 2020-06-09 16:29
Edited said issue to remove this step since it can be tackled separately by a contributor!

**Comment by moh12594** [comment] 2020-07-01 19:05
Hi @Timer !
I created this PR [14752](https://github.com/vercel/next.js/pull/14752) that should fix the issue.

I think that we can use this [babel-plugin](https://github.com/moh12594/babel-plugin-disallow-imports) that I've done to have more generic errors and also handle this [issue](https://github.com/vercel/next.js/issues/13712). WDYT ?

**Comment by stefanprobst** [comment] 2021-05-28 12:07
i think this has been fixed by https://github.com/vercel/next.js/pull/24832

**Comment by timneutkens** [comment] 2021-05-28 12:28
Correct 👍

**Closed by timneutkens** 2021-05-28 12:28 UTC
Labels: good first issue, kind: story

**Comment by balazsorban44** [comment] 2022-01-28 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
