### ISSUE TITLE
Duplicate query params on dynamic routes in production

### ISSUE THREAD

**Issue by Regaddi** [vercel/next.js#19704] opened 2020-12-01 10:41 UTC
# Bug report

## Describe the bug

When calling `replace` with a given dynamic `pathname` and a `query` object, e.g.

```js
replace({ pathname: '/people/[id]', query: { id: '123' } });
```

the resulting URL is `/people/123?id=123`.

## To Reproduce

Source: https://codesandbox.io/s/youthful-ellis-0xb69?file=/pages/people/%5Bid%5D.js

1. Go to https://0xb69.sse.codesandbox.io/people/123 (runs development mode)
2. Click on 'Refresh' button
3. URL remains correct (`/people/123`)
4. Go to https://csb-0xb69-abssuf1pc.vercel.app/people/123 (runs production mode)
5. Click on 'Refresh' button
6. Query param is "duplicated" (`/people/123?id=123`)

## Expected behavior

Parameters for dynamic URLs shouldn't end up in `location.search`.

## System information

- OS: macOS 11.0.1
- Browser: Safari 14.0.1, Chrome 87.0.4280.67, Firefox 83.0
- Version of Next.js: 10.0.3
- Version of Node.js: I don't exactly know, but seems unrelated
- Deployment: reproducible via vercel deployment and local `next start`

**Comment by Regaddi** [comment] 2020-12-01 15:06
My current workaround is to manually remove all path params from `query` (by parsing `pathname` for any occurrences of `/\[[^\]]+\]/g`) and passing `asPath.match(/[^?]+/)` as the new pathname.

This changes calls like the following:

```diff
- replace({ pathname: '/people/[id]', query: { id: '123' } });
+ replace({ pathname: '/people/123', query: {} });
```

This still seems to be undesirable, though, since I have to manually change things.
It would be great to not have to add this workaround.

**Comment by eliorivero** [comment] 2021-01-15 12:22
@Regaddi have you found a permanent fix? I'm having this same issue with one of my routes and it doesn't really have nothing special compared to others. It's a perplexing issue.

**Comment by ijjk** [comment] 2021-01-15 16:20
Hi, yeah this should be fixed in the latest version of Next.js `v10.0.5` as mentioned in https://github.com/vercel/next.js/issues/19704#issuecomment-760911411 please update and give it a try!

**Closed by ijjk** 2021-01-15 16:20 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
