### ISSUE TITLE
[turbopack] nav links do not redirect / work _after_ visiting root `not-found.js`

### ISSUE THREAD

**Issue by padmaia** [vercel/next.js#50410] opened 2023-05-26 23:46 UTC
Summary : nav links do not redirect / work _after_ visiting root `not-found.js` 

(next v13.3.0; react v18.2; node v16.19.1; turbo enabled)
 
I have a chakra-ui client component that wraps my root `nav` within `app/layout.js`. I'm seeing that...
- when running under `npm run dev` : non-existent URLs result in me seeing the standard chrome browser 404 page rather than the one I defined.  
- when running under `npm run build/start` : non-existent URLs get successfully redirected to the UI defined in `app/not-found.js` however the main nav bar links subsequently no longer work. The url in the browser changes but the page stays on the not-found.js generated UI rather than redisplaying whichever nav link I click on. This also happens if the Link is written in the `not-found.js` UI code rather than the root nav.

In devtools console I see a 404 error per screenshot below. 

To try and rule out chakra-ui / client component being the cause, I created a noddy simple `nav` within `app/layout.js` (copied below) however this had the same result. 

Is this a bug or a "user error" ? 

Tks vm

`app/not-found.js`  ....
```
import Link from "next/link";

export default function NotFound() {
  return (
    <>
      <h1>404 !</h1>
      <p>Could not find requested resource</p>
      <p><Link href="/">Please click this link to return to home</Link></p>
    </>
  );
}
```

then my noddy simple `nav` in `app/layout.js` ...
```
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/projects">Projects</Link>
          <Link href="/contact">Contact</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
```

![nextjx13-navlink-error-console](https://user-images.githubusercontent.com/4746349/232474428-fa12b62c-831f-4fb2-8f49-6e253df45fdc.png)

_Originally posted by @AC90 in https://github.com/vercel/turbo/discussions/2312#discussioncomment-5636282_

<sub>[WEB-1120](https://linear.app/vercel/issue/WEB-1120/[turbopack]-nav-links-do-not-redirect-work-after-visiting-root-not)</sub>

**Comment by kotx** [comment] 2023-05-27 03:23
I also have this issue, but the same issue happens *navigating* to a `not-found` page. Page url changes but nothing else happens.
![image](https://github.com/vercel/next.js/assets/33439542/71f0b845-02b0-402c-8657-6675b534b062)

**Comment by JamDev0** [comment] 2023-05-28 02:07
Same here

**Comment by CaterJ** [comment] 2023-06-06 20:20
Also experiencing this. Page links work on `not-found.js`, but the links in my nav component change URL with no UI change.

**Comment by GrzegorzZajac000** [comment] 2023-08-09 16:54
Same here

**Comment by padmaia** [comment] 2023-09-19 23:48
@AC90 @kotx @JamDev0 @CaterJ can y'all confirm if you are still seeing this with the most recent version? Also are you all seeing it with just Turbopack, or seeing it with webpack as well?

**Comment by tizips** [comment] 2023-10-20 02:29
next v13.5.6

I have encountered the same problem and have started using <a /> instead of <Link /> to avoid it

**Comment by ForsakenHarmony** [comment] 2023-11-22 16:37
Can't reproduce with Next.js 14, will close this for now.

If you're still running into this, please open a new issue with a reproduction link.

**Closed by ForsakenHarmony** 2023-11-22 16:37 UTC
Labels: area: Turbopack, linear: turbopack
