### ISSUE TITLE
 Interpolation of multiple conditions in styled jsx media query not working after upgrading to nextjs 12

### ISSUE THREAD

**Issue by fmmoret** [vercel/next.js#32384] opened 2021-12-11 07:53 UTC
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.9.1

### What browser are you using?

chrome

### What operating system are you using?

windows

### How are you deploying your application?

n/a

### Describe the Bug

Super similar to https://github.com/vercel/next.js/issues/30480

Almost certainly more AST stuff for @kdy1 

After upgrading to nextjs 12 interpolations in styled jsx media query with multiple conditions stop working. They get wrapped with parenthesis.

On 12.0.7, the emitted style is: -- see parens injected around conditions:
```
@media (only screen and (min-width: 0px)) {
	.container.jsx-2171830629 {
		background-color: red;
	}
}
@media (only screen and (min-width: 576px)) {
	.container.jsx-2171830629 {
		background-color: blue;
	}
}
@media (only screen and (min-width: 992px)) {
	.container.jsx-2171830629 {
		background-color: green;
	}
}
@media (only screen and (min-width: 1200px)) {
	.container.jsx-2171830629 {
		background-color: yellow;
	}
}
@media (only screen and (min-width: 768px)) {
	.title.jsx-2171830629 {
		color: red;
	}
}
@media (only screen and (min-width: 768px) and (max-width: 1199px)) {
	.title.jsx-2674905225 {
		color: red;
	}
}
```

### Expected Behavior

On 11.1.0, the emitted style is:
```
@media only screen and (min-width: 0px) {
	.container.jsx-339317155 {
		background-color: red;
	}
}
@media only screen and (min-width: 576px) {
	.container.jsx-339317155 {
		background-color: blue;
	}
}
@media only screen and (min-width: 992px) {
	.container.jsx-339317155 {
		background-color: green;
	}
}
@media only screen and (min-width: 1200px) {
	.container.jsx-339317155 {
		background-color: yellow;
	}
}
@media only screen and (min-width: 768px) {
	.title.jsx-339317155 {
		color: red;
	}
}
@media only screen and (min-width: 768px) and (max-width: 1199px) {
	.title.jsx-2674905225 {
		color: red;
	}
}
```

### To Reproduce

To reproduce:
1. git clone https://github.com/dim2k2006/nextjs-styled-jsx-bug
1. yarn install
1. yarn dev
1. Open http://localhost:3000/
1. Inspect page heading styles -- see invalid styles with extra parens
1. Resize screen; no response

To reproduce how it used to be:
1. git clone https://github.com/dim2k2006/nextjs-styled-jsx-bug
1. edit package.json and downgrade "next" to "11.1.0"
1. yarn install
1. yarn dev
1. Open http://localhost:3000/
1. Inspect page heading styles -- see valid media queries
1. Resize screen; see crazy colors being applied correctly 👍 

Page source here: https://github.com/fmmoret/nextjs-styled-jsx-bug/blob/main/pages/index.tsx

**Comment by fmmoret** [comment] 2021-12-11 08:06
FWIW -- I'm absolutely amazed that this is the only styled-jsx SWC issue I have in my team's whole codebase spanning multiple next projects. Due to the more strict parsing, it has actually help us catch some spots where we wrote some bad CSS.

**Comment by balazsorban44** [comment] 2021-12-14 17:12
Duplicate of #31562

**Closed by balazsorban44** 2021-12-14 17:12 UTC
Labels: kind: bug, area: SWC transforms

**Comment by balazsorban44** [comment] 2022-01-27 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
