### ISSUE TITLE
"With-sentry" example only brings up server-side errors

### ISSUE THREAD

**Issue by BramDecuypere** [vercel/next.js#18477] opened 2020-10-29 14:12 UTC
# Bug report

## Describe the bug

I've trying to get the with-sentry example to work in my usecase.
The only thing I'm changing in this example is the `env.local` file:

```
NEXT_PUBLIC_SENTRY_DSN=https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx@xxxxxxxx.ingest.sentry.io/xxxxxxxxx
```

and the _app.tsx file in order to have it come up under a certain environment:

```
if (process.env.NEXT_PUBLIC_SENTRY_DSN) {
  const config = getConfig();
  const distDir = `${config.serverRuntimeConfig.rootDir}/.next`;
  Sentry.init({
    enabled: true,
    environment: "staging",
    beforeSend: function (event) {
      console.log("event", event);
      return event;
    },
    integrations: [
      new RewriteFrames({
        iteratee: (frame) => {
          frame.filename = frame.filename.replace(distDir, "app:///_next");
          return frame;
        },
      }),
    ],
    dsn: process.env.NEXT_PUBLIC_SENTRY_DSN,
  });
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by Timer** [comment] 2020-10-29 14:28
duplicate of #18478

**Closed by Timer** 2020-10-29 14:28 UTC

**Comment by balazsorban44** [comment] 2022-01-29 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
