### ISSUE TITLE
[NEXT-1150] [Bug] next/link navigation broken after adding a `not-found` page

### ISSUE THREAD

**Issue by jahirfiquitiva** [vercel/next.js#48367] opened 2023-04-14 01:52 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.20.0
      npm: 8.19.4
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.6
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/jahirfiquitiva/not-found-links-repro/

### To Reproduce

Create a `not-found` page and use `Link` from `next/link` to navigate to a non-existent page.

Or visit https://not-found-links-repro.vercel.app/

### Describe the Bug

After creating a `not-found` file/component/page...

When navigating to a page that does not exist, using `next/link`, the UI does not change. 

When navigating, from `not-found`, to a page that actually exists, using `next/link` the UI does not change (still shows `not-found`).

This is "fixed" by using a simple html `<a>` tag, but I would like to keep using `next/link`

I'm not sure if the issue #42991 is related, but seems similar. Although from my reproduction, the error happens with normal pages too, not just dynamic.

Here's a video showing the issue:

https://user-images.githubusercontent.com/10360816/231920790-1198805f-cf1a-4e01-b710-b22d224c5dc1.mp4

### Expected Behavior

Navigating to any route using `next/link` should make the page render the actual content of the page if it exists, otherwise, render the `not-found` component, but allow to navigate to another existing page and render its actual content.

### How are you deploying your application? (if relevant)

Vercel

<sub>[NEXT-1150](https://linear.app/vercel/issue/NEXT-1150/[bug]-nextlink-navigation-broken-after-adding-a-not-found-page)</sub>

**Comment by jonmountjoy** [comment] 2023-04-15 12:55
This bug is also in 13.3.0

`<Link  href="/" >Home</Link>` in a `not-found.tsx` just doesn't work.  It changes the URL, but not the content.

**Comment by jahirfiquitiva** [comment] 2023-04-15 13:16
right @jonmountjoy I forgot to mention I was using 13.3.0 stable... I used the canary when reporting the issue to make sure that it was still there 😅

**Comment by jahirfiquitiva** [comment] 2023-04-22 08:18
This is still happening with Next.js 13.3.1 😫

**Comment by WoLfulus** [comment] 2023-04-28 22:44
Still happening. Breaks the whole website.

**Comment by evowizz** [comment] 2023-04-29 01:54
Looks like @timneutkens mentioned in another issue (#47862 ) that the problem is known and a fix is planned.

https://github.com/vercel/next.js/issues/47862#issuecomment-1527219652

**Comment by EthanStandel** [comment] 2023-05-04 18:15
This doesn't seem to be happening for dynamic routes. So if you add a `app/[...fallback]/page.tsx` and give it this

```tsx
import { notFound } from "next/navigation";

export default function ForceDynamicNotFound() {
  return notFound();
}

export const dynamic = "force-dynamic";
```

Then `next/link` should work in `not-found.tsx` again. But mind you, this will cause a minor invocation every time you have a 404 hit.

**Comment by jahirfiquitiva** [comment] 2023-05-04 18:29
> this will cause a minor invocation
mind elaborating, i don't understand this part 😬

**Comment by jahirfiquitiva** [comment] 2023-05-04 19:31
i see, thank you for the detailed explanation 😀

**Comment by rovvi** [comment] 2023-05-05 06:18
I am using window.location.href as a temp workaround for now.

```tsx
<a onClick={() => (window.location.href = '/')}>BACK TO HOME</a>
```

**Comment by jahirfiquitiva** [comment] 2023-05-07 18:13
@EthanStandel your solution does not work in the case of:
- going to `/blog/404`
- clicking on a `Link` to `/blog`
- this link does nothing

**Comment by JasonA-work** [comment] 2023-05-11 06:51
I have the same issue today with both the stable release of the app dir (next 13.4.1). When I navigate to a page that doesn't exist, the URL updates correctly but the UI stays at the same page I was at.

For example, from "/", I navigate to "/xyz" (which doesn't exist. The URL updates to "/xyz" but the UI shown is from "/". Only if I refresh the page, it'll show the UI of the not-found.js in my app dir.

Similarly, when I'm inside "/xyz" URL and the 'not-found.js' UI is showing, hitting back on the browser will update the URL to "/", but the UI remains to be from 'not-found.js'. Only if I manually refresh the page, it'll properly show the UI from "/".

Would love to see a fix soon. I definitely cannot use this for production. Right now, I'm seriously thinking of sticking with the pages directory for now since the app dir doesn't seem stable at all even though it has a stable release already.

Thank you!

**Comment by mehediemon007** [comment] 2023-05-28 09:06
https://stackoverflow.com/a/75625136

This works for me!! Check it out.

**Comment by timneutkens** [comment] 2023-05-31 07:42
Verified the provided reproduction is fixed on stable: https://vpxc95-3000.csb.app/

Related PRs: #50047, #49855

**Closed** 2023-05-31 07:42 UTC
Labels: template: bug, linear

**Comment by jahirfiquitiva** [comment] 2023-05-31 12:57
thank you @timneutkens 😀
