### ISSUE TITLE
swcMinify: true - ReferenceError: Can't find variable: excludeEmptyString

### ISSUE THREAD

**Issue by JClackett** [vercel/next.js#30429] opened 2021-10-27 11:51 UTC
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

16.10.0

### What browser are you using?

Safari

### What operating system are you using?

MacOS

### How are you deploying your application?

Vercel

### Describe the Bug

I'm sure its connected to other issues, but thought I'd provide some more context.

Setting the swcMinify config to true seems to break something in the runtime as it successfully builds and deploys, but then when navigating to certain pages I get:

```
ReferenceError: Can't find variable: excludeEmptyString 
  matches — string.js:75
  (anonymous function) — <some-page>.tsx:33
  g — bootstrap:22
  (anonymous function) — _N_E:6
  promiseReactionJob
```

### Expected Behavior

Not error :)

### To Reproduce

Our team has a boilerplate repo we use on all our projects:

https://github.com/NoQuarterTeam/boilerplate

- cd into packages/web
- change the next.config.js file to set swcMinify to true
- yarn build
- yarn start
- Navigate to /login

**Comment by jamesbluecrow** [comment] 2021-11-01 04:53
I'm seeing a similar issue when `swcMinify: true`, the error I see is:

**Version 12.0.2**

```
Uncaught SyntaxError: Missing initializer in const declaration
```

**Comment by MohammedWaheeb** [comment] 2021-11-02 09:44
same issue here with 12.0.1 and yup 0.32.9 swcMinify: true

**Comment by neilpoulin** [comment] 2021-11-03 06:52
This is related to my issue posted here: https://github.com/vercel/next.js/issues/30498

**Comment by mntnv** [comment] 2021-11-03 09:55
I'm having the same issue with `yup` v0.32.9 and the same behavior with the latest version.

for me, a temporary downgrade to `yup` v0.31.1 helped to fix `ReferenceError: Can't find variable: excludeEmptyString` 

On the next.js v12 with enabled `swcMinify`.

**Comment by rpedroni** [comment] 2021-11-06 13:17
Having same issue with email validation with `"yup": "^0.32.9"`
Turning off `swcMinify` for now stability pending

**Comment by Aliemeka** [comment] 2021-11-09 11:19
I think setting `swcMinify: false` solves the issue for me. However, there needs to be support for `yup version ^0.32.11` validations.

**Comment by egaba** [comment] 2021-11-09 13:35
Having a similar issue using v12.0.3 and yup. Going to turn off `swcMinify` for now.

**Comment by nikosantis** [comment] 2021-11-09 14:31
Same issue with Nextjs v12.0.3 and yup 0.32.11.
```
ReferenceError: excludeEmptyString is not defined
    at yc.matches (545-7eafa77df153ad02.js:1)
    at yc.email (545-7eafa77df153ad02.js:1)
    at Object.7669 (index-5f41350bcbc82045.js:1)
    at g (webpack-2bbe73903b6b5b3e.js:1)
    at index-5f41350bcbc82045.js:1
    at main-5a40b9d72bc92c69.js:1
```

**Comment by kdy1** [comment] 2021-11-11 07:55
I think this is fixed by https://github.com/vercel/next.js/pull/31242

**Comment by neilpoulin** [comment] 2021-11-11 07:58
> I think this is fixed by #31242

Great! I'll test it once that commit gets released.

**Comment by timneutkens** [comment] 2021-11-15 13:59
@neilpoulin you can try it using `npm install next@canary` 👍

**Comment by rodilo** [comment] 2021-11-24 08:34
> 

Did you find what was causing your issue? I get the same when I enable `swcMinify`.

**Comment by rodilo** [comment] 2021-11-24 08:35
> I'm seeing a similar issue when `swcMinify: true`, the error I see is:
> 
> **NextJS Version 12.0.2**
> 
> ```
> Uncaught SyntaxError: Missing initializer in const declaration
> ```

Did you find what was causing your issue? I get the same when I enable swcMinify.

**Comment by Aliemeka** [comment] 2021-11-24 08:49
Hey @rodilo!

Yeah, I get that too. If it's yup your using, it seems the swc compiler is incompatible with `yup version >0.32.10`. You can use a lower version like `yup version ^0.32.9` or set `swcMinify: false`

I also think there is a canary version of Next 12 that addresses this issue. You can use install `next@canary` and redeploy to production.

**Comment by rodilo** [comment] 2021-11-24 08:55
> Hey @rodilo!
> 
> Yeah, I get that too. If it's yup your using, it seems the swc compiler is incompatible with `yup version >0.32.10`. You can use a lower version like `yup version ^0.32.9` or set `swcMinify: false`
> 
> I also think there is a canary version of Next 12 that addresses this issue. You can use install `next@canary` and redeploy to production.

I've found what was causing mine, it's `ajv`. So I'll try to upgrade to the latest version, and see if the error still occurs.

**Comment by rodilo** [comment] 2021-11-24 10:34
Yeah, I get the same error with the canary version as well.
Error is thrown from within `ajv` library we use for validation.

**Comment by BluetyIt** [comment] 2021-12-02 14:31
I got same error while using next^12.0.2
Fixed while upgrade to next^12.0.4

**Comment by timneutkens** [comment] 2021-12-23 12:43
The issue with yup has been fixed on the latest stable.

**Closed by timneutkens** 2021-12-23 12:43 UTC
Labels: kind: bug, area: SWC Minify

**Comment by balazsorban44** [comment] 2022-01-27 01:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
