### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by arnaudjnn** [vercel/next.js#21445] opened 2021-01-22 15:03 UTC
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

v14.12.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

next dev

**Describe the Bug**

I'm using Next with i18n-routing.

Here is my next.config.
```
module.exports = {
  i18n: { 
    locales: ["fr", "en"], 
    defaultLocale: "fr"
  },
}
```

When I try a slug which contain the specific keywords 'development' I get the following error:
```
TypeError: Cannot read property 'toLowerCase' of undefined
    at /Users/arnaud/Documents/edflex/node_modules/next/dist/next-server/lib/i18n/normalize-locale-path.js:2:89
    at Array.some (<anonymous>)
    at normalizeLocalePath (/Users/arnaud/Documents/edflex/node_modules/next/dist/next-server/lib/i18n/normalize-locale-path.js:2:55)
    at stripNextDataPath (/Users/arnaud/Documents/edflex/node_modules/next/dist/next-server/server/next-server.js:85:700)
    at DevServer.renderToHTMLWithComponents (/Users/arnaud/Documents/edflex/node_modules/next/dist/next-server/server/next-server.js:87:35)
    at DevServer.renderToHTML (/Users/arnaud/Documents/edflex/node_modules/next/dist/next-server/server/next-server.js:133:934)
    at async DevServer.renderToHTML (/Users/arnaud/Documents/edflex/node_modules/next/dist/server/next-dev-server.js:34:578)
    at async DevServer.render (/Users/arnaud/Documents/edflex/node_modules/next/dist/next-server/server/next-server.js:72:236)
    at async Object.fn (/Users/arnaud/Documents/edflex/node_modules/next/dist/next-server/server/next-server.js:47:704)
    at async Router.execute (/Users/arnaud/Documents/edflex/node_modules/next/dist/next-server/server/router.js:23:67)
    at async DevServer.run (/Users/arnaud/Documents/edflex/node_modules/next/dist/next-server/server/next-server.js:66:1042)
    at async DevServer.handleRequest (/Users/arnaud/Documents/edflex/node_modules/next/dist/next-server/server/next-server.js:34:1081)
```

**Expected Behavior**

I need to use a slug with the keyword `development` inside.

**To Reproduce**

Start the app with `next dev` and try the other locale than the default white the keyword `development` inside the slug

**Comment by ijjk** [comment] 2021-01-22 18:00
Hi, this was already fixed in https://github.com/vercel/next.js/pull/19901 which is available in the latest canary of Next.js `v10.0.6-canary.7`, please update and give it a try!

**Closed by ijjk** 2021-01-22 18:00 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 19:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
