### ISSUE TITLE
Enabling rewrites causes escape-string-regexp to be bundled which is not IE11 compatible

### ISSUE THREAD

**Issue by stefanaxelsson** [vercel/next.js#32429] opened 2021-12-12 21:36 UTC
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

14.17

### What browser are you using?

IE11

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

Adding rewrites to a next.js project results in escape-string-regexp being bundled in the client. escape-string-regexp contains arrow functions which is not supported in IE11:

### Expected Behavior

Bundled code to be functional in IE11.

### To Reproduce

Enable rewrites:

next.config.js
```js
module.exports = {
  reactStrictMode: true,
  experimental: {
    styledComponents: true,
  },
  rewrites: async () => {
    return [
      {
        source: "/rewrite",
        destination: "/",
      },
    ];
  },
};
```
See main.js in deployed example at:
https://styled-components-swc.vercel.app

Or full source code at:
https://github.com/stefanaxelsson/styled-components-swc

**Comment by ijjk** [comment] 2021-12-13 22:10
Hi, this should be resolved by https://github.com/vercel/next.js/pull/32310 which is available in `v12.0.8-canary.4` of Next.js, please update and give it a try!

**Comment by pewallin** [comment] 2021-12-21 11:35
Seems like this still doesn't work in IE11 (tested with v12.0.8-canary.11)

**Comment by stefanaxelsson** [comment] 2021-12-21 12:36
There's still an arrow function left in escape-string-regexp

**Closed** 2022-01-03 17:41 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-02-02 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
