### ISSUE TITLE
next build error on local machine ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization

### ISSUE THREAD

**Issue by humble-barnacle001** [vercel/next.js#33764] opened 2022-01-28 12:07 UTC
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: linux
      Arch: x64
      Version: #15-Ubuntu SMP Wed Jan 12 19:18:58 UTC 2022
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.9
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.9

### What version of Node.js are you using?

v16.13.0

### What browser are you using?

Firefox

### What operating system are you using?

Linux

### How are you deploying your application?

Vercel

### Describe the Bug

The following error occurs when running `next build` but deploys to Vercel are built successfully
```
> Build error occurred
ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
    at Object.Z (/workspace/assignment-monitor/.next/server/chunks/415.js:427:36)
    at /workspace/assignment-monitor/.next/server/chunks/415.js:540:143
    at Function.__webpack_require__.a (/workspace/assignment-monitor/.next/server/webpack-runtime.js:98:13)
    at Object.3409 (/workspace/assignment-monitor/.next/server/chunks/415.js:503:21)
    at __webpack_require__ (/workspace/assignment-monitor/.next/server/webpack-runtime.js:25:42)
    at /workspace/assignment-monitor/.next/server/chunks/415.js:474:67
    at Function.__webpack_require__.a (/workspace/assignment-monitor/.next/server/webpack-runtime.js:98:13)
    at Object.6489 (/workspace/assignment-monitor/.next/server/chunks/415.js:464:21)
    at __webpack_require__ (/workspace/assignment-monitor/.next/server/webpack-runtime.js:25:42)
    at /workspace/assignment-monitor/.next/server/chunks/415.js:730:82 {
  type: 'ReferenceError'
}
```

### Expected Behavior

Build should complete successfully on local machine just as on Vercel

### To Reproduce

next build

**Comment by timneutkens** [comment] 2022-01-28 12:08
Duplicate of #32360

**Closed by timneutkens** 2022-01-28 12:08 UTC
Labels: template: bug
