### ISSUE TITLE
Setting localeDetection (True) does not work in Safari 

### ISSUE THREAD

**Issue by anialamo** [vercel/next.js#26976] opened 2021-07-07 02:23 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

12.3.2

### What browser are you using?

Safari

### What operating system are you using?

maxOS

### How are you deploying your application?

Vercel

### Describe the Bug

Hi! I have a project with this next.config.js with localeDetection as true. When I use a Chrome for testing and type in navigator my url like this www.myurl.com, this inmediately changes to www.myurl.com/es (because I am in Spain and my accepted-lang is Spanish). But if I do this testing in Safari Mobile I write www.myurl.com but I cannot see the automatic locale detection works, because my web doesn't redirect to www,myurl.com/es, this stays in www.myurl.com

Is there any solution for this issue?

This is my next.config.js:

```
const localeLanguages = [
     { label: 'en', name: 'English', abbrev: 'EN'},
     { label: 'es', name: 'Español', abbrev: 'ES' },
     { label: 'pt-BR', name: 'Português Brasil', abbrev: 'PT BR' }
];

// Extend your Next config for advanced behavior
// See https://nextjs.org/docs/api-reference/next.config.js/introduction
let nextConfig = {
     
     publicRuntimeConfig: {
          localeLanguages
     },

     i18n: {
          // These are all the locales you want to support in
          // your application
          locales: ['en', 'es', 'pt-BR'],
          // This is the default locale you want to be used when visiting
          // a non-locale prefixed path e.g. `/hello`
          defaultLocale: 'en',
          localeDetection: true,
     },
     
};

module.exports = nextConfig;
```

As you can see, my Spanish locale is a single "es", but in Safari I can see my Accepted-language is "es-ES". 

### Expected Behavior

In Safari Mobilei if I write www.myurl.com I cannot see the automatic locale detection works, because my web doesn't change to www,myurl.com/es, this keeps in www.myurl.com

### To Reproduce

Clone this project https://github.com/vercel/next.js/tree/canary/examples/i18n-routing

Then change your browser language to one of the languages in locales. Make sure you have something like es-ES, es-MX, for example to test Spanish redirection.

Navigate to the index page and you should be redirected to http://localhost:3000/es 
Instead you stay on http://localhost:3000

**Comment by Gashunkification** [comment] 2021-07-09 18:21
We seem to be having the same issue in Safari, also with the `es-es` locale the browser sends.
When we actually include `es-es` in the next config, then it seems to be working, in that the browser gets redirected to http://localhost:3000/es-es.

However, we do need it to work for all spanish versions, regardless of region so this is not a workaround that is feasible, unfortunately.

Any info would be highly appreciated!

**Comment by ijjk** [comment] 2021-07-09 19:11
Hi, this is a duplicate of https://github.com/vercel/next.js/issues/18676 closing in favor of that one

**Closed by ijjk** 2021-07-09 19:11 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
