### ISSUE TITLE
InferGetStaticPropsType not working as expected

### ISSUE THREAD

**Issue by livelo-app** [vercel/next.js#28638] opened 2021-08-31 06:08 UTC
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

14.17.3

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When attempting to use `InferGetStaticPropsType` I am getting my parameters' type as `never`.

The following link describes my issue.

https://github.com/vercel/next.js/pull/11842#issuecomment-651292487

To better explain the bug - the bug only occurs if I include the following in `getStaticProps`:
```
  if (!res) {
    return {
      notFound: true
    }
  }

  if (res.length === 1) {
    return {
      redirect : {
        destination: `/city/sydney`,
        permanent: false
      }
    }
  }
```

It seems that including:
```
    return {
      notFound: true
    }
```
and:
```
    return {
      redirect : {
        destination: `/city/sydney`,
        permanent: false
      }
    }
```
will not allow for `InferGetStaticPropsType` to infer the _correct_ type.

It also seems that including the type `GetStaticPaths` and `GetStaticProps` will force the `InferGetStaticPropsType` to return  `any` as the type as seen in the thread below.
https://github.com/vercel/next.js/pull/11842#issuecomment-635459597

I believe the most important bug to fix in this case is that the infer for `getStaticProps` only works in the case where we **only** return `props`. Not in the face where we _may_ return `redirect` or `notFound`.
### Expected Behavior

My static props type should be inferred however they currently are not.

### To Reproduce

Set strict mode enabled and attempt to use InferGetStaticPropsType.

**Comment by juanzgc** [comment] 2021-08-31 06:30
I'm facing the same issue - Currently I am getting `any` as the Inferred type

**Comment by ijjk** [comment] 2021-09-18 15:52
Hi, this is a duplicate of https://github.com/vercel/next.js/issues/15913 so closing this in favor of that one.

**Closed by ijjk** 2021-09-18 15:52 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
