### ISSUE TITLE
Internal Server Error only production

### ISSUE THREAD

**Issue by martinezguillaume** [vercel/next.js#15129] opened 2020-07-13 15:03 UTC
# Bug report

## Describe the bug

When I'm trying to access my app, it display "Internal Server Error"
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Push a version of the app
2. Wait for vercel to build it
3. Access the app with url from vercel

## Expected behavior

My app working like in my local env

## Screenshots

<img width="487" alt="image" src="https://user-images.githubusercontent.com/17292331/87319772-0021da80-c522-11ea-97ca-71412888489c.png">

## System information

- OS: MacOS
- Browser Safari
- Version of Next.js: 9.4.4
- Version of Node.js: 12.16.1

## Additional context

I don't know how to debug this kind of errors, I literally don't have any logs or errors... So I don't where to look... I tried to remove things like specific configuration (material ui) in my repo to see it it was the cause of the problem, without luck

**Comment by jamesmosier** [comment] 2020-07-13 16:18
Closing in favor of https://github.com/vercel/next.js/discussions/15128

**Closed by jamesmosier** 2020-07-13 16:18 UTC

**Comment by balazsorban44** [comment] 2022-01-29 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
