### ISSUE TITLE
Make dynamic page with prefix

### ISSUE THREAD

**Issue by beautyfree** [vercel/next.js#15108] opened 2020-07-12 23:44 UTC
I want to have dynamic pages /projectname and /@username
If i create files `[projectAlias].tsx` and `@[username].tsx` it doesnt' work

What about availability of such an approach?

**Comment by jamesmosier** [comment] 2020-07-13 01:03
Duplicate of https://github.com/vercel/next.js/discussions/15079

**Closed by jamesmosier** 2020-07-13 01:03 UTC

**Comment by balazsorban44** [comment] 2022-01-29 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
