### ISSUE TITLE
Back button scroll restoration not working on mobile

### ISSUE THREAD

**Issue by nandorojo** [vercel/next.js#18997] opened 2020-11-09 20:20 UTC
# Bug report

## Describe the bug

I'm navigating from a list-view to a profile, then clicking back. I expect the back button to return to the scroll position from the previous page. 

However, **_on mobile browsers_, going back does not restore scroll position**. Instead, it triggers a full refresh and goes to the top of the page.

## To Reproduce

1) Open my [website](https://beatgig-mono-l83gd0drj.vercel.app/) (that's an immutable deploy URL).
2) Click an artist profile.
3) Go back (using the browser back button, or the one in the UI).
4) Do this on both a mobile browser & desktop browser.

Notice that on a desktop browser, when you click back, it correctly returns you to your previous scroll position. On mobile browsers, however, it incorrectly sends you to the top of the page.

----

I also made a [CodeSandbox](https://codesandbox.io/s/next-router-scroll-restoration-issue-toulm?file=/pages/index.js).
1. Scroll down
2. Click an item
3. Go back

Interestingly, in the CodeSandbox, the scroll doesn't restore on either mobile or desktop. Not sure why. **Is there special configuration needed for scroll restoration?**

## Expected behavior

When you click back on a mobile browser, it should return to the previous scroll position you were in.

The correct behavior can be seen on Vercel's home page ([video](https://imgur.com/a/Ek28ogp)). When you go back, it puts you right where you left off.

## Screenshots

✅ **Desktop (works)** [video link here](https://www.loom.com/share/7f0b556c78b342fda81db99848d1cef9)
- On desktop, the behavior is as expected. When you go back, whether by calling `router.back()` or by using the browser `back` functionality, the page restores its scroll position

🚨 **Mobile (doesn't work)** [video link here](https://imgur.com/OHSvI4l) 
- When you go back, the home page does a full refresh, and the scroll position is never restored.

## System information

- OS: iOS 14 (tested on iOS 13, same issue)
- Browser (if applies) iOS Chrome, iOS Safari
- Version of Next.js: `10.0.1`
- Version of Node.js: 14.2.0

## Additional context

For context, both my home page and my artist profile page are using `getStaticProps` with `revalidate: 1`. I'm not sure if that causes the home page to refresh. In either case, even if the previous page does refresh, I would expect the mobile browser to restore the scroll like the desktop browser does.

Also, I'm storing my data in SWR's cache, in case that's useful info.

I've tried some of the proposed solutions on https://github.com/vercel/next.js/issues/3303, but they led to some weird behavior where going back flashed a blank screen. https://github.com/vercel/next.js/issues/1309 is also relevant, but it was created 3 years ago, so I'm not sure what the current status of this is.

Thanks so much!

**Comment by nandorojo** [comment] 2020-11-10 13:41
It seems like one solution could be to not unmount the previously visited page. Is this possible?

**Comment by timneutkens** [comment] 2020-11-24 08:37
Can you try this experimental option:

```js
module.exports = {
  experimental: { scrollRestoration: true }
}
```

**Comment by fpahl** [comment] 2020-11-25 15:45
Setting the experimental option works great for us in most cases. The only time the back button is still scrolling to the top is, when a Google fullscreen ad is displayed. Guess, this can not be fixed at all...
Feel free to test it here: https://test2.sendungverpasst.de.

**Comment by nandorojo** [comment] 2020-11-25 15:52
Thanks for the suggestion, I'll try that out!

I do have one additional question for this topic.

Some pages use a `div` with `overflow-y: scroll` rather than using window scrolling. That's because I'm using `react-native-web`'s `ScrollView` in some pages, rather than window scrolling.

To see an example of a page that doesn't use window scrolling, you can go to [beatgig.com/search](beatgig.com/search)

Is it possible to restore the scroll of an element inside of the page, and not just the window's scroll position?

**Comment by fpahl** [comment] 2020-11-25 16:15
Did some more testing:
The option seems to work fine on desktop. On mobile (Safari) the application seems to "hang" sometimes:
When I click on a link it is loading endlessly, though I can see that the request got served in the Vercel function logs.
I have to click on the link a second time, before it opens the new page.

Please notify me, if I can support you with a test deployment.

**Comment by meotimdihia** [comment] 2020-12-23 09:08
https://github.com/vercel/next.js/issues/1309#issuecomment-530534417

I am using code in the link and it does work.

**Comment by meotimdihia** [comment] 2020-12-23 10:44
@timneutkens: this experimental option will scroll to the bottom page if the page renders at the client side.

**Comment by Timer** [comment] 2020-12-31 07:43
This should be fixed on `next@canary`, if it's not, we need a **full** reproduction (I tested a few variants of this with the newest scroll changes).

**Closed by Timer** 2020-12-31 07:43 UTC
Labels: kind: story, type: needs investigation

**Comment by Timer** [comment] 2020-12-31 07:46
FYI the code sandbox works as expected, too (on mobile).

Within their container breaks the browser's built in handling, so that's expected to not work for the demo purposes.

**Comment by meotimdihia** [comment] 2021-01-10 14:26
Experimental is still not work for me. I am trying to use this module: 
https://github.com/moxystudio/next-router-scroll
It works well for now.

**Comment by Timer** [comment] 2021-01-11 13:20
Please do not use the experimental feature. The normal behavior should be working now.

**Comment by rbgoncalves** [comment] 2021-01-12 17:22
> Please do not use the experimental feature. The normal behavior should be working now.

Trying next 10.0.5 now and I got a weird behavior. When I press the back button on my details page it restores the scroll first (on the details page yet) and then navigates back to the list page

**Comment by nicolastoulemont** [comment] 2021-02-22 09:21
> > Please do not use the experimental feature. The normal behavior should be working now.
> 
> Trying next 10.0.5 now and I got a weird behavior. When I press the back button on my details page it restores the scroll first (on the details page yet) and then navigates back to the list page

I'm still having this issue on 10.0.7

**Comment by HectorLS** [comment] 2021-06-01 17:16
Hello @rbgoncalves, same behavior here. ¿Have you figure it out a workaround on this?

**Comment by meotimdihia** [comment] 2021-06-01 17:18
Check my comment: 
https://github.com/vercel/next.js/issues/3303#issuecomment-799021522

**Comment by rbgoncalves** [comment] 2021-06-11 08:26
Hey @HectorLS , I did build a scroll manager as I didn't have the best exp with the moxystudio one. Also, it's a bit more  optimized as I'm not listening to every scroll change or use external deps. I will make it public probably.

**Comment by balazsorban44** [comment] 2022-01-28 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
