### ISSUE TITLE
next.config.js - Redirects and catch all pages

### ISSUE THREAD

**Issue by AldoS** [vercel/next.js#28843] opened 2021-09-06 13:51 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.17.5

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

When we land directly on a page, that should redirect, the redirection works fine.
The problem is when you navigate through pages using next/link. The catch-all is taking place instead of redirecting.

### Expected Behavior

Redirection to take place before the catch-all routes.

### To Reproduce

1. Add a catch-all route, e.g. pages/[[...alias]].js
2. Update next.config.js with redirects as described in docs https://nextjs.org/docs/api-reference/next.config.js/redirects
3. Build the project
4. Load a page and then navigate to a page that redirection should take place
5. Redirection is not fired, instead, catch-all routes catch it

**Comment by ijjk** [comment] 2021-09-18 15:55
Hi, redirects are not currently applied with `next/link` only rewrites and the actual destination should be used instead for now. I'm going to close this since this isn't a bug and is currently expected.

**Closed by ijjk** 2021-09-18 15:55 UTC
Labels: template: bug

**Comment by AldoS** [comment] 2021-09-18 16:15
Hi @ijjk, thanks for the response.
I can see that redirects are applied with `next/link` if the page does not exist.
A quick example:  https://codesandbox.io/s/gallant-mahavira-slwks

```module.exports = {
  async redirects() {
    return [
      {
        source: "/about",
        destination: "/test",
        permanent: true
      }
    ];
  }
};
```

If you click on the about link, you can see that the redirect is working because there is no `about.js` page.
If you rename the `1about.js` back to `about.js` the redirect will not be working anymore.

**Comment by ijjk** [comment] 2021-09-18 16:19
In the above case the redirect isn't being applied by `next/link`, it is failing to find the page client-side so it triggers a hard navigation which the server then applies the redirect. We might apply redirects via `next/link` in the future and is something we're keeping track of although currently isn't expected.

**Comment by AldoS** [comment] 2021-09-18 16:53
Ok, that makes sense, thanks. It would be great if `next/link` could handle the redirects in the future.

I found a work around for now. As mentioned above we are using `getStaticPaths` & `getStaticProps`.
So, with the new `redirect` feature in the getStaticProps (https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation) I can search the redirect's array based on the current path and return the redirect if needed:
```
return {
  redirect: {
    destination: '/',
    permanent: false,
  },
}
```

**Comment by balazsorban44** [comment] 2022-01-27 19:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
