### ISSUE TITLE
getServerSideProps redirect does not respect basePath option during client transitions

### ISSUE THREAD

**Issue by jmay4826** [vercel/next.js#28425] opened 2021-08-23 21:18 UTC
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

14

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

When returning a `redirect` in `getServerSideProps`, the `basePath: false` option is ignored for client-side transitions only. When navigating directly to the page with the `redirect`, the `basePath: false` option is used correctly. This leads to different results when accessing a page with a redirect via client-side routing vs. entering the URL directly. The `basePath: false` option is used correctly with `redirect` in all cases in Next v10.2.3.

### Expected Behavior

When navigating to a page using `redirect` in `getServerSideProps`, the `basePath: false` option should always be respected, no matter how the user arrives on the page.

### To Reproduce

v11.1.0 CodeSandbox (with issue):  https://codesandbox.io/s/next-11-basepath-redirect-pbcp6?file=/pages/login.js
v10.2.3 CodeSandbox (same code, no issue): https://codesandbox.io/s/next-10-2-3-basepath-redirect-krprr?file=/pages/login.js

1. Visit https://pbcp6.sse.codesandbox.io/next-app/login.
  a. The project has a `basePath` of `/next-app` set in `next.config.js`. This page contains a client-side transition to `/page-with-server-redirect` via `router.replace`.
2. After the page loads, you will be sent to `/next-app/page-with-server-redirect`, which correctly includes the `basePath`.
3. The `getServerSideProps` function for `page-with-server-redirect` will return a server-side redirect to `/without-basepath` with an option of `basePath: false`. You will be incorrectly redirected to `/next-app/without-basepath`, which incorrectly includes the `basePath`. 
4. Visit https://pbcp6.sse.codesandbox.io/next-app/page-with-server-redirect directly. You will be sent to `/without-basepath`, which correctly omits the `basePath` based on the `basePath: false` option.
5. Repeat steps 1-4 in the v10.2.3 copy of the project: https://krprr.sse.codesandbox.io/next-app/login. The issue is not seen in this version.

**Comment by xiyu23** [comment] 2021-08-30 13:11
Same as you. 

I have the same problem as you do. It shows up when I upgrade nextjs from `v10.0.1` to `v11.1.0`.
After some debugging, the temporary solution comes up with **remove basePath from your target redirect url** if you used it as the prefix.

e.g The **basePath** is `/wework` in my case.

```js
// next.config.js
module.exports = {
  // ...
  basePath: '/wework',
};
```

so just remove that in the target redirect:

```diff
// pages/wemeet-app/home
export async function getServerSideProps(ctx: GetServerSidePropsContext) {
-   const destination = '/wework/wemeet-app/login';
+   const destination = '/wemeet-app/login';

    return {
      redirect: {
        destination,
        permanent: false,
      },
    };
}
```

⚠️ This is the **temporary fix** I came up with, it would be better if this bug was fixed in the further version.

Any better solution will be very much appreciated.

**Comment by jmay4826** [comment] 2021-09-08 18:20
Thanks @xiyu23. In our case, we don't have the `basePath` in our redirect url. The `handleRedirect` function does look like a good place for me to look into more to find the problem though.

**Comment by fastestOrange** [comment] 2021-09-08 18:33
We are also seeing issues with server side redirect in v11

**Comment by skattwood** [comment] 2021-09-10 16:14
Glad to see someone else posted about this issue. We are currently not able to upgrade to v11 and may have to downgrade one of our other applications. How do we get more visibility on this bug for a fix or a potential workaround?

**Comment by DrCaveDev** [comment] 2021-09-10 17:10
Seeing the same issue. Holding off on an upgrade to v11 because of this, but would love to have a fix or workaround so we can work with the latest version.

**Comment by jmay4826** [comment] 2021-09-14 15:17
@timneutkens or @ijjk any ideas on this issue? I dug into the `handleRedirect` function mentioned above, but I didn't find much there. From what I could tell, that function wasn't being called at all and I couldn't find another place where the redirect might be handled.

**Comment by prescottprue** [comment] 2021-09-15 00:04
+1 Also holding off on the v11 upgrade because of this

**Comment by hershmire** [comment] 2021-09-20 17:26
This is an issue for us as well. Could someone from the Next.js team (@leerob) reply on this issue? That would be a good start to help identify what might be happening here so we can see if anyone affected by this would be able to help out. Thanks!

**Closed** 2021-09-21 14:23 UTC
Labels: template: bug

**Comment by ijjk** [comment] 2021-09-21 21:39
Hi, this has been updated in `v11.1.3-canary.29` of Next.js, please update and give it a try!

**Comment by balazsorban44** [comment] 2022-01-27 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
