### ISSUE TITLE
Using getStaticProps() + unstable_revalidate gives a wrong value to router.asPath when homepage is rebuild

### ISSUE THREAD

**Issue by Danetag** [vercel/next.js#15845] opened 2020-08-04 00:05 UTC
# Bug report

## Describe the bug

When using `getStaticProps()` + `unstable_revalidate`, `router.asPath` renders `/index` instead of `/`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create `/src/pages/index.js`
2. Get data from any API, use `getStaticProps()` and `unstable_revalidate`
3. Deploy
4. On the initial static build, the value is correct. Build a few seconds later, when the page is "rebuild" (incremental build), `router.asPath` returns `/index`

## Expected behavior

`router.asPath` should render `/` instead of `/index` when building the page

## System information

- OS: macOS
- Version of Next.js: 9.4.0
- Version of Node.js: 12.6.1

**Comment by Timer** [comment] 2020-08-04 03:36
Could you please upgrade to Next.js 9.5.1 and see if it works? 9.4.0 is a pretty old version.

**Comment by timneutkens** [comment] 2020-08-04 08:13
Quite certain this was fixed already indeed.

**Comment by Timer** [comment] 2020-08-05 06:10
Closing unless you can provide a full reproduction on a modern Next.js version, thanks!

**Closed by Timer** 2020-08-05 06:10 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
