### ISSUE TITLE
Images can't be provided via `getStaticProps`

### ISSUE THREAD

**Issue by eostrom** [vercel/next.js#29571] opened 2021-10-02 23:04 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

16.10.0

### What browser are you using?

Firefox, Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Statically imported images [can be used with `Image`](https://nextjs.org/docs/api-reference/next/image#src) (or regular old `img`), but not if they're statically imported and then passed into the page via `getStaticProps`.

### Expected Behavior

After I converted a page to get its images via `getStaticProps`, I expected to still see them.

### To Reproduce

Here's a minimal-ish example:

```jsx
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import directImportImage from '../public/robert-bye-Fr1t7UHYkJU-unsplash.jpg'
import staticPropImage from '../public/robert-bye--P2SwAbYcbs-unsplash.jpg'

export const getStaticProps = () => ({
  props: { staticPropImage }
})

export default function Home({ staticPropImage }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <table>
          <tr>
            <td>Image with string source</td>
            <td><Image src="/robert-bye-LphK1Oht5NA-unsplash.jpg" alt="[ALT: Image with string source]" width={489.6} height={326.4} layout="fixed" /></td>
          </tr>
          <tr>
            <td>Image from direct import</td>
            <td><Image src={directImportImage} alt="[ALT: Image from direct import]" width={489.6} height={326.4} layout="fixed" /></td>
          </tr>
          <tr>
            <td>Image from static props</td>
            <td><Image src={staticPropImage} alt="[ALT: Image from static props]" width={489.6} height={326.4} layout="fixed" /></td>
          </tr>
        </table>
      </main>
    </div>
  )
}
```

I would have expected all three images to show up, but only the first two do:

![import image screenshot](https://user-images.githubusercontent.com/8683/135733799-249179c9-c04a-402d-8226-7be645c09d08.png)

[Test repo](https://github.com/eostrom/next-image-import-test), [running on Vercel.](https://next-image-import-test.vercel.app/)

**Comment by ijjk** [comment] 2021-10-04 00:28
Hi, this isn't expected to work as `getStaticProps` is dead-code eliminating the static image import that is only used inside of `getStaticProps` so it isn't present in the client build causing the static image to not be included in the static assets. As long as the import is also used outside of `getStaticProps` as well it won't be dead-code eliminated. 

You can see this dead-code elimination taking place here https://next-code-elimination.vercel.app/s/rsBrPDsLe

I'm gonna close this since it doesn't appear to be a bug

**Closed by ijjk** 2021-10-04 00:28 UTC
Labels: template: bug

**Comment by eostrom** [comment] 2021-10-04 00:34
Thanks for the explanation. Would it be worth adding it to the `next/image` docs? It took me a while to figure out what was going on (in a bigger, less contrived app), and a little note would have helped a lot.

**Comment by ijjk** [comment] 2021-10-04 00:43
Yeah it might be good to note this, feel free to open a PR adding a note for this in the `next/image` docs here https://github.com/vercel/next.js/blob/canary/docs/api-reference/next/image.md

**Comment by balazsorban44** [comment] 2022-01-27 16:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
