### ISSUE TITLE
Next 14 - `redirect(<path>)` does not work at all inside intercepting routes

### ISSUE THREAD

**Issue by sannajammeh** [vercel/next.js#58661] opened 2023-11-20 00:01 UTC
### Link to the code that reproduces this issue

https://github.com/sannajammeh/next-intercepting-noredirect

### To Reproduce

1. Install deps with Bun
2. `bun run dev`
3. Navigate to /sites
4. Press `create a new site` anchor tag
5. Observe route is intercepted correctly at `/sites/new`
6. Add any text and press `Submit`
7. Observe nothing happens, form submits fine but `redirect` call will not do navigate back to `/sites`
8. Now set browser url to `http://localhost:3000/sites/new` to load standalone page
9. Repeat step 6 and observe everything work. 

### Current vs. Expected behavior

Current:

`redirect()` called inside server action will never fire on an intercepting route. Redirect works as usual on normal routes. This happens both in `next dev` & `next start`

Expected:

`redirect()` should work on both normal and intercepted route.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103
Binaries:
  Node: 21.0.0
  npm: 10.2.0
  Yarn: 1.22.11
  pnpm: 8.10.5
Relevant Packages:
  next: 14.0.4-canary.5
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Additional context

I have tested this on both Next 13, 14 (current) and 14 (canary). All yield the same bug.

**Comment by pekarja5** [comment] 2023-11-20 13:25
Seems like duplicate of #57665

**Comment by balazsorban44** [comment] 2023-12-06 14:19
Closing as duplicate of #57665

**Closed by balazsorban44** 2023-12-06 14:19 UTC
Labels: template: bug, area: Routing
