### ISSUE TITLE
Link to index page with getServerSideProps and basePath results in full page reload

### ISSUE THREAD

**Issue by bernardop** [vercel/next.js#14282] opened 2020-06-17 18:54 UTC
# Bug report

## Describe the bug

Using the experimental `basePath` and linking from any page back to the index page with `Link` results in a full page reload if the index page uses `getServerSideProps`. Looking at the network tab in Chrome I see a request to `http://localhost:3000/base/_next/data/development.json` that 404s. In the production build, the request that 404s looks like this `http://localhost:3000/base/_next/data/xpCmLw_g1hPw_3b847mWF.json`. I believe there's a `/` missing before `.json`.

## To Reproduce

1. Clone this repo https://github.com/bernardop/next-basepath-repro
1. Install dependencies and `yarn dev`
1. Go to http://localhost:3000/base
1. Click on "a" or "b"
1. Click on "Back" link
1. Index page does a full load and the network tab shows 404 to `.json`

## Expected behavior

Index page should not fully reload.

## System information

- OS: macOS
- All browsers
- Version of Next.js: 9.4.5-canary.8
- Version of Node.js: 14.4.0

## Additional context

I believe this was introduced in `9.4.5-canary.8` and I suspect #13876 is the culprit. `9.4.5-canary.7` does not have this error.

**Comment by ijjk** [comment] 2020-06-22 00:08
Hi, this should have be resolved in v9.4.5-canary.14 of Next.js specifically this PR https://github.com/vercel/next.js/pull/14376

**Comment by ijjk** [comment] 2020-06-22 13:57
Closing as this is resolved on latest canary, please reply with additional details if you are still encountering problems after upgrading

**Closed by ijjk** 2020-06-22 13:57 UTC
Labels: kind: bug

**Comment by bernardop** [comment] 2020-06-22 14:56
Thanks @ijjk, just confirmed it works perfectly now. Also great to see `basePath` out of "experimental"!

**Comment by alecrae** [comment] 2020-07-24 01:53
Also confirming this issue seems to be fixed in latest canary 👍  looking forward to 9.4.5!

**Comment by balazsorban44** [comment] 2022-01-29 20:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
