### ISSUE TITLE
Serverless target specific files not available in webpack done hook

### ISSUE THREAD

**Issue by asterikx** [vercel/next.js#16115] opened 2020-08-12 13:26 UTC
# Bug report

## Describe the bug

Serverless target-specific files, in particular from the prerender-manifest.json manifest, are not accessible in webpack 'done' hook.

## To Reproduce

A custom plugin which prints the contents of the `.next` folder in the `done` hook, e.g.:

```js
class NextLambdaEdgePlugin {
  constructor(nextConfig, options) {
    const { config: { distDir } } = nextConfig;
    this.nextDistDir = distDir;
  }

  apply(compiler) {
    const done = (stats) => {
      const { nextDistDir } = this;

      // return generateHanlderCode(...);

      fse.readdir(nextDistDir, (err, files) => {
        files.forEach((file) => {
          console.log(file);
        });
      });
      return Promise.resolve();
    };

    compiler.hooks.done.tapPromise('NextLambdaEdgePlugin', done);
  }
}
```

This prints:
```
build-manifest.json
cache
react-loadable-manifest.json
routes-manifest.json
serverless
static
```

## Expected behavior

The plugin prints all files, including serverless target-specific ones:

```
BUILD_ID
build-manifest.json
cache
export-marker.json
prerender-manifest.json
react-loadable-manifest.json
routes-manifest.json
serverless
static
```

## System information

- OS: macOS
- Version of Next.js: 9.5.1
- Version of Node.js: 12.16.1

## Additional context

See #16096

**Comment by timneutkens** [comment] 2020-08-13 11:22
Closing as duplicate of #16096

**Closed by timneutkens** 2020-08-13 11:22 UTC

**Comment by balazsorban44** [comment] 2022-01-29 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
