### ISSUE TITLE
Production build fails with: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by eddyw** [vercel/next.js#14227] opened 2020-06-16 15:02 UTC
# Bug report

## Describe the bug

I upgraded to next@9.4.5-canary.12 from next@9.4.4 because of https://github.com/vercel/next.js/issues/14186
Everything works with `next dev`. However, `next build` fails with:
```js
Unhandled error during request: TypeError: Cannot read property 'add' of undefined
    at new _default ([HIDDEN_PATH]/node_modules/next/dist/next-server/lib/side-effect.js:1:407)
    at d ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:320)
    at $a ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToStaticMarkup ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:462)
    at renderDocument ([HIDDEN_PATH]/node_modules/next/dist/next-server/server/render.js:3:594)
    at renderToHTML ([HIDDEN_PATH]/node_modules/next/dist/next-server/server/render.js:48:72)
    at async renderReqToHTML ([HIDDEN_PATH]/.next/serverless/pages/[...slug].js:24441:22)
    at async Object.exportPage [as default] ([HIDDEN_PATH]/node_modules/next/dist/export/worker.js:12:92)
Error occurred prerendering page "/[...slug]". Read more: https://err.sh/next.js/prerender-error
TypeError: Cannot read property 'add' of undefined
    at new _default ([HIDDEN_PATH]/node_modules/next/dist/next-server/lib/side-effect.js:1:407)
    at d ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:320)
    at $a ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToStaticMarkup ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:462)
    at renderDocument ([HIDDEN_PATH]/node_modules/next/dist/next-server/server/render.js:3:594)
    at renderToHTML ([HIDDEN_PATH]/node_modules/next/dist/next-server/server/render.js:48:72)
    at async renderReqToHTML ([HIDDEN_PATH]/.next/serverless/pages/[...slug].js:24441:22)
    at async Object.exportPage [as default] ([HIDDEN_PATH]/node_modules/next/dist/export/worker.js:12:92)
Unhandled error during request: TypeError: Cannot read property 'add' of undefined
    at new _default ([HIDDEN_PATH]/node_modules/next/dist/next-server/lib/side-effect.js:1:407)
    at d ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:320)
    at $a ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToStaticMarkup ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:462)
    at renderDocument ([HIDDEN_PATH]/node_modules/next/dist/next-server/server/render.js:3:594)
    at renderToHTML ([HIDDEN_PATH]/node_modules/next/dist/next-server/server/render.js:48:72)
    at async renderReqToHTML ([HIDDEN_PATH]/.next/serverless/pages/_error.js:10604:22)
    at async Object.exportPage [as default] ([HIDDEN_PATH]/node_modules/next/dist/export/worker.js:12:92)
Error occurred prerendering page "/404". Read more: https://err.sh/next.js/prerender-error
TypeError: Cannot read property 'add' of undefined
    at new _default ([HIDDEN_PATH]/node_modules/next/dist/next-server/lib/side-effect.js:1:407)
    at d ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:320)
    at $a ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToStaticMarkup ([HIDDEN_PATH]/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:462)
    at renderDocument ([HIDDEN_PATH]/node_modules/next/dist/next-server/server/render.js:3:594)
    at renderToHTML ([HIDDEN_PATH]/node_modules/next/dist/next-server/server/render.js:48:72)
    at async renderReqToHTML ([HIDDEN_PATH]/.next/serverless/pages/_error.js:10604:22)
    at async Object.exportPage [as default] ([HIDDEN_PATH]/node_modules/next/dist/export/worker.js:12:92)
> Build error occurred
Error: Export encountered errors on following paths:
	/404
	/[...slug]
    at exportApp ([HIDDEN_PATH]/node_modules/next/dist/export/index.js:22:1166)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async build ([HIDDEN_PATH]/node_modules/next/dist/build/index.js:38:218)
22:36:52.954  
error Command failed with exit code 1.
```
Our projects builds fine up until 9.4.4 (current stable) but canary fails.

## To Reproduce

~I don't understand enough the error to be able to reproduce it.
We don't have a custom 404 not _error pages which makes it even more confusing.
Any hint where to look at would be appreciated so I can try to repro this (project is private, so I can't share it :/)~
*Edit:* Alright, I started moving files around and commenting code and this is what it came down to:
1. Create an empty NextJS app (next@9.4.5-canary.12)
2. Create empty page (this is what I have):
```javascript
// pages/[...slug].js
const CatchAllPages = () => {
  return <div>Test</div>
}
export const getStaticPaths = async () => {
  return {
    paths: [],
    fallback: true,
  }
}
export const getStaticProps = async (ctx) => {
  return {
    props: {},
  }
}
export default CatchAllPages
```
3. Create a custom `_document.js`:
```javascript
import * as React from 'react'
import Document, {
  Html,
  Head as HeadContainer,
  Main,
  NextScript,
} from 'next/document'
import Head from 'next/head'

const SomeComponent = React.memo(() => {
  return (
    <>
      <Head>
        <script
          dangerouslySetInnerHTML={{ __html: '// this does not matter' }}
        ></script>
      </Head>
    </>
  )
})

export default class CustomDocument extends Document {
  render() {
    return (
      <Html>
        <HeadContainer />
        <body>
          <Main />
          <NextScript />
          <SomeComponent />
        </body>
      </Html>
    )
  }
}
```
4. Run `next build`

Apparently this has something to do with using `next/head` when rendering a component (e.g: in above `SomeComponent` which could live outside in `src/components`) in the `Html` tag in `body`.

## Expected behavior

It should build or provide a better error message. If using `next/head` is no longer allowed in `Html` or in `_document` then it should display a better error with a link to some NextJS doc describing the issue (as it does with other error messages)

## System information

- OS: MacOS
- Version of Next.js: next@9.4.5-canary.12
- Version of Node.js: 12.18.0

## Additional context

Works with 9.3.x & 9.4.4

**Comment by timneutkens** [comment] 2020-06-16 15:13
Please provide a complete reproduction

**Comment by eddyw** [comment] 2020-06-17 09:02
@timneutkens I edited the main post to provide a complete reproduction with new empty project with next@9.4.5-canary.12

**Comment by timneutkens** [comment] 2020-06-17 09:05
You can't use next/head in _document, it will not output anything

**Comment by eddyw** [comment] 2020-06-17 09:28
@timneutkens alright, I'm moving this out from `_document`.

However, this actually worked in 9.3.x & 9.4.4 (maybe it did unintentionally 🙈)
```html
<!DOCTYPE html><html><head><script>// this does not matter</script>...
```

**Comment by Timer** [comment] 2020-06-17 14:01
This will be fixed by #13958

**Comment by timneutkens** [comment] 2020-06-21 22:02
Closing this as a duplicate of #14425 and #13958 will completely disallow importing it (given it breaks/does not work as expected)

**Closed by timneutkens** 2020-06-21 22:02 UTC
Labels: type: documentation

**Comment by balazsorban44** [comment] 2022-01-30 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
