### ISSUE TITLE
Middleware + Incremental Regeneration not working

### ISSUE THREAD

**Issue by impactvelocity** [vercel/next.js#37832] opened 2022-06-19 22:27 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

--

### Describe the Bug

res.unstable_revalidate(path)  was working fine when using a _middleware previously, but in the last few days it wasn't working. It would call the get request on the path just fine, but that wasn't causing the cache to break.

I removed the _middleware.js and it all worked fine. I added the _middleware back in, and again, cache wouldn't break.

I feel like something must have changed on vercel / next side? 

( PS. I dont know if this is happening in canary release ) 

( PSS. Sorry about the basic issue, but I just wanted to report the issue )

### Expected Behavior

Invalidate the cached page.

### Link to reproduction

--

### To Reproduce

The _middle wasn't fancy,  just making paths like this: /something-page-PAGEID and it was getting the PAGEID at the end, and doing:

const url = req.nextUrl.clone()
let path = req.nextUrl.pathname
let getId = path.substr(path.lastIndexOf('-') + 1)

url.pathname = `${getId}`
return NextResponse.rewrite(url)

**Comment by ijjk** [comment] 2022-06-20 00:02
Hi, in the latest canary of Next.js of Next.js `unstable_revalidate` no longer triggers middleware. If you were previously rewriting in middleware to the actual path being rewritten this is no longer supported. The path passed to `unstable_revalidate` should be the actual name path being revalidated without a rewrite needed e.g. `pages/blog/[slug]` `res.unstable_revalidate('/blog/first')`

**Comment by balazsorban44** [comment] 2022-06-20 11:07
Closing as the above suggestion should be enough, please test with `canary`.

Let us know if it does not resolve your issue, so we can reopen. In that case, please also attach a simple reproduction so we can investigate more thoroughly.

**Closed by balazsorban44** 2022-06-20 11:07 UTC
Labels: template: bug

**Comment by ijjk** [comment] 2022-06-28 21:49
The same domain information should be available in the API route calling `res.revalidate()` allowing you to build the same path that middleware would, is there a specific issue that isn't allowing the same path to be built there when the `revalidate` method is being called?

**Comment by normdoow** [comment] 2022-06-29 16:28
> The same domain information should be available in the API route calling `res.revalidate()` allowing you to build the same path that middleware would, is there a specific issue that isn't allowing the same path to be built there when the `revalidate` method is being called?

Yep, that makes sense. Same info is available. So I was able to recreate that there. But am getting this error on the backend in `getStaticProps` after calling revalidate.

<img width="889" alt="image" src="https://user-images.githubusercontent.com/21371266/176487616-ff8f117f-16f7-4014-be3d-0f61e3aeaa5a.png">
the page works well before calling revalidate but afterwards there is a client side exception. Could this be an issue with revalidate? or maybe I'm doing something wrong still.

**Comment by ijjk** [comment] 2022-06-29 18:33
The `Failed to update prerender cache` error was fixed in https://github.com/vercel/next.js/pull/38136 and will be on canary soon

**Comment by normdoow** [comment] 2022-06-29 18:43
> The `Failed to update prerender cache` error was fixed in #38136 and will be on canary soon

Thanks!

**Comment by nicosh** [comment] 2022-07-05 10:53
@ijjk i see the PR is merged, however i still have  the same problem in the last canary version.

**Comment by ijjk** [comment] 2022-07-05 17:35
@nicosh which error are you referring to?

**Comment by ijjk** [comment] 2022-07-05 17:59
Can you provide a reproduction on the latest canary of Next.js where this is still occurring?

**Comment by ijjk** [comment] 2022-07-06 16:56
@nicosh that appears to be different as the error is failing to write the file due to the `:` character being used in the filename which isn't allowed on Windows. You could resolve this by ensuring that character is not included in the path e.g. strip the `port` info from the [`currentHost` value](https://github.com/nicosh/37832/blob/f6d425c3890676d5bf3eab1d46947fd43d97d91b/middleware.ts#L16)
