### ISSUE TITLE
Links do not support dynamic routes defined using an object as the documentation states

### ISSUE THREAD

**Issue by bencpeters** [vercel/next.js#17573] opened 2020-10-02 19:18 UTC
# Bug report

I'm trying to use `router.push` to navigate to a dynamic route using [the object syntax](https://nextjs.org/docs/api-reference/next/router#with-url-object). When the page navigates, rather than resolving `/nested/[variable]` to `/nested/123`, the browser goes to `/nested/[variable]?variable=123` and the router inside that component has `query = { variable = "[variable]" }`.

This is happening both with `router.push` and with `<Link href={{ pathname, query }}>`. Both the documentation for [`Link`](https://nextjs.org/docs/api-reference/next/link#with-url-object) and for [`router.push`](https://nextjs.org/docs/api-reference/next/router#with-url-object) suggests that this should be supported?

## To Reproduce

Linking Component (e.g. `pages/index.jsx`)

```jsx
const LinkComponent = () => {
  const router = useRouter()
  return (
    <>
      <span onClick={() => router.push({ pathname: "/nested/[variable]", query: { variable: "123" }})}>
        Click here! (Doesn't work)
      </span>
      <Link href={{ pathname: "/nested/[variable]", query: { variable: "123" }}}>
        This doesn't work either
      </Link>
      <Link href="/nested/123">
        This works
      </Link>
    </>
  )
}
```

Linked To Component (e.g. `pages/nested/[variable].js`):
```jsx
const LinkedTo = () => {
  const router = useRouter()
  const { variable } = router.query
  return (
    <h1>Variable: {variable}</h1>
  )
}
```

## Expected behavior

As laid out in the docs, I expect the page to navigate to the linked component, and for `router.query.variable` to be set to the value given in `query` in `router.push`.

## System information

- OS: Mac OS
- Browser (if applies) Chrome
- Version of Next.js: 9.5.3
- Version of Node.js: 12.x

## Additional context

It's possible that I'm misunderstanding the way this is supposed to work, but if so, the docs seem very misleading?

**Comment by ijjk** [comment] 2020-10-02 19:44
Hi, this is a duplicate of https://github.com/vercel/next.js/issues/17380. I'm going to close this since an existing issue has already been opened for this and details have been provided on that one.

**Closed by ijjk** 2020-10-02 19:44 UTC

**Comment by balazsorban44** [comment] 2022-01-29 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
