### ISSUE TITLE
cannot read properties of undefined on swcMinify

### ISSUE THREAD

**Issue by moshie** [vercel/next.js#35811] opened 2022-04-01 08:28 UTC
I've been getting these kind of errors poping up a lot when using swcMinify on version `12.1.2`

```
Cannot read properties of undefined (reading 'lib')
```

FYI this was working in the previous version. `12.1.0`

The error was happening in auth0.js, cryptojs & I also experienced it in styled-components.

I found this reference to the error and disabling swcMinify does fix it.

https://github.com/brix/crypto-js/issues/415

_Originally posted by @moshie in https://github.com/vercel/next.js/discussions/30237#discussioncomment-2484107_

**Comment by balazsorban44** [comment] 2022-04-01 09:23
I see @kdy1 is already on it https://github.com/vercel/next.js/discussions/30237#discussioncomment-2484174 but could you create a small reproduction and link it here so we can easily verify when the issue is fixed? :pray:

**Comment by moshie** [comment] 2022-04-01 09:26
Yeah sorry I created this issue from the discussion so it skipped the template i'll keep that in mind for the future

**Comment by moshie** [comment] 2022-04-01 10:10
I would love to create a reproduction of this but it's buried deep in private libraries which I can't share. I could re-create the authentication flow in a blank next project only issue is that would take a lot of time which I don't have :(.

I pulled out two screenshots of the minified code one which breaks and the other which is working:

Broken: 
<img width="333" alt="Screenshot 2022-04-01 at 10 49 16" src="https://user-images.githubusercontent.com/3974301/161243376-2e671a18-8e8a-4d74-8bab-4c33da507884.png">


Working:
<img width="500" alt="Screenshot 2022-04-01 at 11 10 13" src="https://user-images.githubusercontent.com/3974301/161243470-779fe13f-ed0a-4240-867c-2ff3abd615e7.png">


I hope that this is somewhat helpful i'd be open to trying anything you suggest and reporting back.

**Comment by kdy1** [comment] 2022-04-01 11:15
@moshie Your code in images does not look like a code emitted by swc minifier.
If you configured correctly, it should be `a`, `b`, `c` and so on instead of `e`, `t`, `n`.

**Comment by moshie** [comment] 2022-04-01 11:29
yep so the broken one is using swcMinifier but the working one is with it disabled.

**Comment by kdy1** [comment] 2022-04-07 09:35
@moshie Can you provide a reproduction?
crypto-js one is fixed, and the causes for such errors are super different from each other so I need ways to reproduce the errors separately

**Comment by kdy1** [comment] 2022-04-12 15:49
I think this is fixed on canary
Can you try it?

**Closed** 2022-04-15 14:34 UTC
Labels: kind: bug, please add a complete reproduction, area: SWC Minify
