### ISSUE TITLE
"No Page Custom Font" eslint rule triggered when importing Document as another name

### ISSUE THREAD

**Issue by brandonchinn178** [vercel/next.js#26301] opened 2021-06-18 07:16 UTC
### What version of Next.js are you using?

11.0.1-canary.4

### What version of Node.js are you using?

14.15.5

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

I use custom fonts in `_document.tsx`, but I import from `next/document` renamed as `NextDocument`, so the eslint rule doesn't recognize the file as the custom document page

### Expected Behavior

This rule should not be triggered in `_document.tsx`, ever.

### To Reproduce

```tsx
import NextDocument from 'next/document'

export default class Document extends NextDocument {
  ...
}
```

**Comment by housseindjirdeh** [comment] 2021-06-18 13:29
Duplicate of #26160. The rule only works right now if you import Document as `Document` and not with any other name unfortunately. 

Submitting a fix soon!

**Closed** 2021-06-18 13:33 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
