### ISSUE TITLE
Documentation about Head.rewind

### ISSUE THREAD

**Issue by lcswillems** [vercel/next.js#9326] opened 2019-11-06 12:37 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I see `Head.rewind()` being used in several examples (e.g. [the apollo example](https://github.com/zeit/next.js/blob/ba246446ef8069e160c3a9a010549e89e222dd1e/examples/with-apollo/lib/apollo.js)) but I don't really understand what it does and can't find documentation about it.

## Describe the solution you'd like

If possible, I would like some documentation about it. What happens if I omit it? Could it be possible to have a concrete example?

**Comment by timneutkens** [comment] 2019-11-06 21:26
We can get rid of `.rewind` by now as the latest `next/head` no longer uses legacy context. I'll open up a PR soon.

**Comment by iFallUpHill** [comment] 2019-11-27 07:17
@timneutkens Could you explain what implications this has from a refactoring perspective? 
Am I safe to simply not call `Head.rewind()` if I'm on a `9.1.x` release?

**Comment by zuqini** [comment] 2019-11-27 07:25
@timneutkens In addition, could you clarify what you mean by legacy context? Is there any other aspects of the code that we need to refactor with this change?

I also see that `next/head` will be deprecated in the near future. What implications will that have? Thanks!

**Comment by dminkovsky** [comment] 2019-12-28 21:35
It's probably got to do with how Head is populated by rendering. In the examples with Head.rewind, the method is called after rendering that is meant to compute side-effects, not produce user output (which must happen later). I'm guessing this undoes changes to Head caused by rendering so it can be populated later.

**Comment by jaydenseric** [comment] 2020-02-25 06:15
@iFallUpHill I have done some digging, and it seems that `next/head` has not used legacy context since [`next@8.0.0-canary.7`](https://github.com/zeit/next.js/releases/tag/v8.0.0-canary.7), here is the PR that was merged: https://github.com/zeit/next.js/pull/6038. From [this comment above](https://github.com/zeit/next.js/issues/9326#issuecomment-550507546), it can be assumed that it’s safe to stop using `Head.rewind()` from that version onward.

**Comment by timneutkens** [comment] 2020-02-25 07:54
@jaydenseric Head.rewind is currently still needed if you do tree rendering, eg getDataFromTree in Apollo

Would highly recommend *not* doing tree rendering as it has **massive** performance implications.

**Comment by jaydenseric** [comment] 2020-02-25 08:09
@timneutkens 

> Head.rewind is currently still needed if you do tree rendering, eg getDataFromTree in Apollo

This is surprising to hear, considering it was deliberately removed from the Next.js example:

https://github.com/zeit/next.js/commit/1a50d99fbd3278aa09f749bf33e1d801bedc5826#diff-c7ee3d6e815d630e8d7be23ea73b6436L107

Are you sure it is necessary; is [your earlier comment](https://github.com/zeit/next.js/issues/9326#issuecomment-550507546) and the Apollo example now incorrect?

> Would highly recommend not doing tree rendering as it has massive performance implications.

I know all about tree rendering, I've worked with the Apollo one and published before using several different techniques:

- https://github.com/jaydenseric/graphql-react/blob/v6.0.1/src/preload.mjs
- https://github.com/jaydenseric/graphql-react/blob/v9.1.0/src/server/ssr.mjs

Are you able to offer an alternative for server side rendering nested query components?

**Comment by timneutkens** [comment] 2020-02-25 08:17
> This is surprising to hear, considering it was deliberately removed from the Next.js example:

> 1a50d99#diff-c7ee3d6e815d630e8d7be23ea73b6436L107

> Are you sure it is necessary; is your earlier comment and the Apollo example now incorrect?

Yes I'm pretty sure it's necessary, so yeah the example should be updated.

My comment is still correct, I said "We can get rid of it" haven't had the time to do so because of other priorities.


> Are you able to offer an alternative for server side rendering nested query components?

Extracting the data requirements out of the React tree like Relay does and then executing it in getStaticProps/getServerProps (new data fetching methods)

**Comment by dminkovsky** [comment] 2020-02-25 14:32
> Would highly recommend not doing tree rendering as it has massive performance implications.

Yes, thanks so much for confirming that. I looked at the Apollo example, played with the technique, and it did seem insane. 

> Extracting the data requirements out of the React tree like Relay does and then executing it in getStaticProps/getServerProps (new data fetching methods)

I hope Apollo 3 provides some canonical guidance in this regard. The current state of the react hooks package leaves very much to be desired.

**Comment by lfades** [comment] 2020-06-11 18:29
Update: There aren't any examples using `Head.rewind` anymore and it will be removed soon.

**Comment by timneutkens** [comment] 2020-06-11 19:09
It's not being removed btw, #14091 is backwards compatible

**Closed** 2020-06-11 22:09 UTC
Labels: kind: story, priority: p3, type: documentation

**Comment by balazsorban44** [comment] 2022-01-27 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
