### ISSUE TITLE
CSS won't load after 13.0.8-canary.2

### ISSUE THREAD

**Issue by rafma0** [vercel/next.js#44243] opened 2022-12-21 21:51 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.4.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.8-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/rafma0/next-csswontload

### To Reproduce

1. Create a new project with `yarn create next-app --experimental-app` and set `next": "13.0.8-canary.2"` (or clone the repo)
2. Load the main page

### Describe the Bug

`<head>` will not include any css

### Expected Behavior

`<head>` to include to include all css

**Comment by amerbilic** [comment] 2022-12-22 17:27
I have the same issue, my tailwind CSS completely is ignored after 13.0.8-canary.1 release

**Comment by jaular** [comment] 2022-12-22 17:30
Same error with Next.js 13.1.0

**Comment by adspacheco** [comment] 2022-12-22 18:56
![image](https://user-images.githubusercontent.com/39010933/209206836-bd924d16-6d17-4780-88d2-461f7ea26867.png)

ready - started server on 0.0.0.0:3000, url: http://localhost:3000/
warn  - You have enabled experimental feature (appDir) in next.config.js.

--

warn  - Port 3000 is in use, trying 3001 instead.
ready - started server on 0.0.0.0:3001, url: http://localhost:3001/

**Comment by quick007** [comment] 2022-12-22 19:50
Thats because we're using the app directory...

**Comment by BahmanTimas** [comment] 2022-12-22 20:24
Updated from 13.0.6 to 13.1.0 and the same issue appeared :(
node v18.12.1, windows 11

**Comment by apavlinovic** [comment] 2022-12-23 00:17
Just to add, it happens on Windows 11, node 18. Tested on Mac OS, same node, couldn’t reproduce there. Maybe windows specific?

**Comment by BahmanTimas** [comment] 2022-12-23 00:53
> Just to add, it happens on Windows 11, node 18. Tested on Mac OS, same node, couldn’t reproduce there. Maybe windows specific?
> 
> happens on 13.1.0

https://github.com/vercel/next.js/issues/44275#issue-1508409245

Looks like it happens on ubuntu too

**Comment by viperxeyes** [comment] 2022-12-23 15:51
Works fine on Arch Linux , doesnt work on windows 11 , also works fine if uploaded to vercel but doesnt work on windows if you use run dev or run build

**Comment by jeffrafter** [comment] 2022-12-23 21:06
Thanks for reporting this bug! This should be fixed in the latest canary release on the canary channel. You can try it out today with `npm install next@canary`

**Comment by AiceGate** [comment] 2022-12-24 04:48
thanks @jeffrafter  it's working 👍 👍 👍 👍 👍 👍

**Closed** 2022-12-24 12:05 UTC
Labels: template: bug
