### ISSUE TITLE
Prefetching SSR Page when Middleware exists

### ISSUE THREAD

**Issue by ethanbonin** [vercel/next.js#39732] opened 2022-08-18 17:17 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.6-canary.1
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 104.0.5112.101

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

When adding the `middleware.ts` to the project, the `getServerSideProps`  runs/prefetches data before ever going to the page. From what I understand, SSR pages fetches data at the time of the request, not before hand.

I attached a photo showing that I am on the index page, and it prefetches the data for the `/ssr-page`. 

<img width="1915" alt="ssr-prefetched" src="https://user-images.githubusercontent.com/20937454/185453562-8c08c1c3-6b58-4fcd-9a79-da25eede5de9.png">

When I remove the `middleware.ts`, it does not prefetch that data and only fetches the data when I click the for the next page.

### Expected Behavior

It should not run `getServerSideProps` data and only load at the time of the request. 

### Link to reproduction

https://github.com/ethanbonin/next-js-ssr-prefetching-middleware

### To Reproduce

This only happens on the production build of the application.

Steps to reproduce:

1. `yarn install`
2. `yarn build`
3. `yarn start`
4. Open up localhost:3000
5. Open up the inspector and view the network logs. You will find `ssr-page.json` in the network logs.
6. Remove the `middleware.ts` file.
7. Rebuild and start the production app
8. Open up localhost:3000
9. Open up the inspector and view the network logs. You will find `ssr-page.json` no longer in the network logs.
10. Click `SSR Page` button
11. View the network logs. You will find `ssr-page.json` in the network logs (as expected)

**Comment by ijjk** [comment] 2022-08-20 13:22
Closing as a duplicate of https://github.com/vercel/next.js/issues/38918

**Closed by ijjk** 2022-08-20 13:22 UTC
Labels: template: bug
