### ISSUE TITLE
future: { webpack5: true } results in OOM issues while building in CI/CD

### ISSUE THREAD

**Issue by kennand** [vercel/next.js#23762] opened 2021-04-07 07:28 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

14.16.0

### What browser are you using?

n/a

### What operating system are you using?

Linux

### How are you deploying your application?

AWS Codebuild

### Describe the Bug

Set future: { webpack5: true } in next.config.js and getting consistent OOM issues when next building in my CI/CD pipeline (AWS Codebuild). Reverted and issue went away.

### Expected Behavior

Does not run out of memory.

### To Reproduce

Tried bigger compute sizes for Codebuild, but only removing the webpack5: true results in consistent builds.

Hi, thanks for the great work! Was curious if anyone else is seeing this?

**Comment by l3aconator** [comment] 2021-05-04 19:29
I am running into this on netlify with `10.2.0`. Downgrading to `10.1.3` fixes, I realize both use webpack 5 as I have the future flag enabled when leveraging `10.1.3`. Works fine locally on an M1 mac when building the site with `next 10.2.0`

My site is pretty large (3600 pages), but have never had OOM problems until now.

See this issue with a similar issue: https://github.com/netlify/netlify-plugin-nextjs/issues/263

**Comment by timneutkens** [comment] 2021-05-05 08:45
Going to close this issue as no reproduction was provided as per the label.

**Closed by timneutkens** 2021-05-05 08:45 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-28 09:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
