### ISSUE TITLE
next/image custom Cache-Control max-age value

### ISSUE THREAD

**Issue by FDiskas** [vercel/next.js#23327] opened 2021-03-23 20:56 UTC
### Describe the feature you'd like to request

Currently every 1min images are regenerated and there is no way to change that

https://github.com/vercel/next.js/blob/361b56b2c2373012051266332905b1dcef085251/packages/next/next-server/server/image-optimizer.ts#L367

### Describe the solution you'd like

I would like to have ability to change `Cache-Control` `max-age` value - currently default is 60 seconds.
As mentioned in the docs https://nextjs.org/docs/basic-features/image-optimization#caching I can change the max-age value by "the upstream server's". As end user I would like more easy way to change this behavior like it is done by image sizes configuration at https://nextjs.org/docs/basic-features/image-optimization#device-sizes
So for example config could look like:
```js
images: {
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    maxAge: 60, // seconds
  },
```

### Describe alternatives you've considered

As alternative is use simple `<img />` tag against `<Imgae />` component.
Or
Adding custom headers within `next.config.js`

```js
  async headers() {
    return [
      {
        source: '/:all*(svg|jpg|png)',
        locale: false,
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, max-age=9999999999, must-revalidate',
          }
        ],
      },
    ]
  },
```

**Comment by FDiskas** [comment] 2021-03-24 07:19
This is probably relevant only in thous case when images are served using nextjs in public directory

**Comment by Timer** [comment] 2021-04-27 04:18
Hi! I'm closing this as a duplicate of https://github.com/vercel/next.js/issues/19914 so we can better prioritize support there. Please add this request as a 👍 to that issue. Thank you!

**Closed by Timer** 2021-04-27 04:18 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-28 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
