### ISSUE TITLE
Docs: How to pass pass down a Server Action to a Client Component as a prop in typescript

### ISSUE THREAD

**Issue by bfovez** [vercel/next.js#54156] opened 2023-08-17 07:38 UTC
### What is the improvement or update you wish to see?

The docs here https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#props shows how to pass pass down a Server Action to a Client Component as a prop.

But as soon as we use typescript instead of plain javascript, things must be typed:

example-server-component.tsx:
```
import { ExampleClientComponent } from "./example-client-component"

type Props = { id: string }

function ExampleServerComponent({ id }: Props) {
  async function updateItem(data: FormData) {
    "use server"
    modifyItem({ id, data })
  }

  return <ExampleClientComponent updateItem={updateItem} />
}
```

example-client-component.tsx:
```
"use client"

type Props = {
  updateItem: (data: FormData) => Promise<void>
}

export function ExampleClientComponent({ updateItem }: Props) {
  return (
    <form action={updateItem}>
      <input type="text" name="name" />
      <button type="submit">Update Item</button>
    </form>
  )
}
```

Then, we get an error from typescript in [the client](example-client-component.tsx:
`Props must be serializable for components in the "use client" entry file, "updateItem" is invalid.ts(71007)`

However, it somehow works anyway.

The docs should be more explicit about how the things must be properly done with typescript.

### Is there any context that might help us understand?

How to implement the example of this part of the docs [pass down a Server Action to a Client Component as a prop](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#props) with typescript.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#props

<sub>[NEXT-1524](https://linear.app/vercel/issue/NEXT-1524/docs-how-to-pass-pass-down-a-server-action-to-a-client-component-as-a)</sub>

**Comment by balazsorban44** [comment] 2023-08-17 11:58
Thanks, this is actually a bug with the TypeScript plugin, not the documentation. We will look into it!

**Comment by SamHep0803** [comment] 2023-10-02 12:58
Is there any update on this? Still seems to be an issue in the latest version

**Comment by lukeberry99** [comment] 2023-10-26 19:36
Any update on this? Still getting it

**Comment by koba04** [comment] 2023-11-10 06:19
Does this still happen? I couldn't reproduce with the following example.

- Form.tsx

```tsx
"use client"

type Props = {
  action: (data: FormData) => Promise<void>
}

export function Form({ action }: Props) {
  return (
    <form action={action}>
      <input type="text" name="name" />
      <button type="submit">Save</button>
    </form>
  )
}
```

- Parent.tsx

```tsx
import { Form } from "./Form"

export function Parent() {
  async function updateItem(data: FormData) {
    "use server"
    console.log(data);
  }
  return <Form action={updateItem} />
}
```

**Comment by JoseVSeb** [comment] 2023-12-06 04:55
Is there a way to disable the rule `ts(71007)` globally?

It's more troublesome than it's worth. There's already a runtime exception thrown if anything other than a server action is passed as prop to a client component from a server component.
Having this rule enabled seems to make it opinionated that you can't have components with `"use client"` to have optional functions as props, which you may choose to pass depending on whether you use it in server component or another client component.

**Comment by ADTC** [comment] 2024-01-28 12:51
I noticed that if you make it optional, the warning goes away. 

```ts
updateItem?: (data: FormData) => Promise<void>
// OR
// Note: Remember the needed bracket enclosure, otherwise the meaning is different.
updateItem: ((data: FormData) => Promise<void>) | undefined
```

But still, it's confusing. Is there a way to distinguish server actions from regular functions? Like by using a hypothetical `ServerAction` type?

```tsx
// HYPOTHETICAL CODE - DO NOT COPY
import type { ServerAction } from 'next'
...
updateItem: ServerAction<(data: FormData) => Promise<void>>
// HYPOTHETICAL CODE - DO NOT COPY
```

This can help to type-check that only server actions are passed to the client as props (not any vanilla function).

**Comment by redbmk** [comment] 2024-02-19 22:10
I found a workaround until the bug is fixed without making it optional. It's still not ideal especially since I couldn't get it to work with generics, but as a stopgap you could create many of these for any flavor of action (`FormData` as input returning `void`, specific params returning some optional error message, etc)

I'm not sure why this works because inspecting the end type still shows an async function (`(data: FormData) => Promise<void>`), but typescript is cool with it now.

**src/actions/index.ts**
```typescript
"use server";

// eslint-disable-next-line @typescript-eslint/no-unused-vars
async function serverAction(data: FormData): Promise<void> {
  throw new Error("Not implemented");
}

export type ServerAction = typeof serverAction;
```

**src/components/Something.tsx**
```tsx
"use client"

import { ServerAction } from '@/actions'
// or 
// import type { ServerAction } from '@/actions'

export const Something = ({ action }: { action: ServerAction }) => (
  <form action={action}>
    <input name="something" />
  </form>
)
```

**Comment by irvin93d** [comment] 2024-03-15 10:55
> I found a workaround until the bug is fixed without making it optional. It's still not ideal especially since I couldn't get it to work with generics, but as a stopgap you could create many of these for any flavor of action (`FormData` as input returning `void`, specific params returning some optional error message, etc)

This seems to work with generics. 
```tsx
export type ServerAction<T> = ((data: T) => Promise<void>) & Function

// in client component
export const TheForm = ({ myAction }: { myAction: ServerAction<{ hey: string }> }) => {
  return (
    <form action={myAction.bind(undefined, { hey: 'you' })}>
      <button>Submit</button>
    </form>
  )
}

// in server component
<TheForm
  myAction={async data => {
    'use server'
    console.info(data)
  }}
/>
```

**Comment by TimotiusAnrez** [comment] 2024-06-26 04:06
is there any update regarding this issue?

**Comment by eps1lon** [comment] 2024-06-26 12:38
The current plan by the React team is to establish the pattern of using the `Action` suffix as a hint that a prop is an Action. We're going to leverage that convention in the Next.js TypeScript plugin:
![Screenshot 2024-06-26 at 14 32 50](https://github.com/vercel/next.js/assets/12292047/8eb483c0-150d-4cf5-b1ce-5e7673db8bb7)

It's not perfect since you could still pass a function that's not a Server function. But we still have runtime type-checking to catch that.

**Comment by ScreamZ** [comment] 2024-07-12 15:55
Looks good

**Closed** 2024-07-15 21:15 UTC
Labels: TypeScript, linear: next
