### ISSUE TITLE
Fast Refresh Dialog Appears frequently

### ISSUE THREAD

**Issue by smo043** [vercel/next.js#33405] opened 2022-01-17 17:53 UTC
### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16.2.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next build with outputStandalone

### Describe the Bug

After upgrading to the latest version of next 12.0.8 and adding a _middleware.ts, always renders a fast Refresh dialog and causes multiple refreshes in local env.

<img width="943" alt="image" src="https://user-images.githubusercontent.com/17010033/149817849-a04ab1a1-94db-40de-8709-8eb6a8162439.png">

### Expected Behavior

The dialog should not appear frequently.

### To Reproduce

Couldn't share the code snippet, as per org policies.

**Comment by klapec** [comment] 2022-01-17 19:41
Looks like this is a duplicate of https://github.com/vercel/next.js/issues/31827

**Comment by smo043** [comment] 2022-01-17 20:20
@klapec - Yup, it's the precisely same one. Please close this issue. I got the problem fixed by removing custom imports as suggested in [#31827](https://github.com/vercel/next.js/issues/31827#issuecomment-1012513968)

**Closed** 2022-01-17 23:23 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-02-17 00:11
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
