### ISSUE TITLE
esling-plugin-next: The exported Page component isn't correctly typed

### ISSUE THREAD

**Issue by Ziothh** [vercel/next.js#45088] opened 2023-01-20 13:19 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 18.2.0
      npm: 8.15.1
      Yarn: 1.22.17
      pnpm: 7.25.0
    Relevant packages:
      next: 13.1.3
      eslint-config-next: 13.1.3
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), ESLint (eslint-config-next), TypeScript

### Link to the code that reproduces this issue

https://github.com/Ziothh/next-typescript-build-issue/blob/main/src/app/page.tsx

### To Reproduce

I made these helper types for better DX.

```ts
interface AsyncFunctionComponent<P extends Object = {}> {
    (props: P, context?: any): Promise<ReactElement<any, any> | null>;
    propTypes?: WeakValidationMap<P> | undefined;
    contextTypes?: ValidationMap<any> | undefined;
    defaultProps?: Partial<P> | undefined;
    displayName?: string | undefined;
}

export type AsyncFC<P extends Object = {}> = AsyncFunctionComponent<P>;

export type OptionalAsyncFC<P extends Object = {}> = AsyncFC<P> | FC<P>

export type WithParams<
    Props extends Object, 
    Params extends Object = {}, 
    SearchParams extends Object = {}
> = Props & {
    params: Params,
    searchParams: SearchParams,
}

/** A better type than the default `NextPage` type, given by next.
 * This should be given to an app dir page component when you need typesafe params.
 *
 * @param Params - Should match the file system routing like `"/user/[userId]/todos/[todoId]/[tab]"`
 * @param SearchParams - Should match the queries in the url like `"?q=hi&other=hi+again"`
 * @param Props - Rroperties this page should have. This is not needed in most cases because pages don't receive props.
 * */
export type NextPage<
    Params extends object = {}, 
    SearchParams extends object = {},
    Props extends Object = {}, 
> = OptionalAsyncFC<WithParams<Props, Params, SearchParams>>
```

And I use them like this:
```ts
const page: NextPage = ({ params, searchParams }) => {
    return null
}
```

### Describe the Bug

I get these errors:

My project:
```
> next build

info  - Loaded env from /Users/digitalastronaut/Projects/DigitalAstronaut/Neapharma_Fuel-Plan/.env
warn  - You have enabled experimental feature (appDir) in next.config.mjs.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
info  - Creating an optimized production build
info  - Compiled successfully
info  - Linting and checking validity of types .Failed to compile.

Type error: Page "src/app/(auth)/auth/forgot-password/[id]/page.tsx" does not match the required types of a Next.js Page.
  Invalid configuration:
    The exported Page component isn't correctly typed.
      The exported Page component isn't correctly typed.
          Expected "{ params: Readonly<Partial<{ id: string; }>>; searchParams: {}; }", got "PageProps".

 ELIFECYCLE  Command failed with exit code 1.
```

The example project:
`Type error: Page "src/app/page.tsx" does not match the required types of a Next.js Page.`

### Expected Behavior

I suspect the new typescript causes next to fail to build on my types. I can't see why.

These error messages are also very cryptic so I can't really debug them myself, sadly.

**Comment by kossnocorp** [comment] 2023-02-13 03:46
It fails for me with the same error on a simple type:

![image](https://user-images.githubusercontent.com/52201/218365629-af26fb6a-a887-420d-bc37-a9723595a422.png)

The problem is in `searchParams`, if I remove it, it builds correctly

**Comment by shuding** [comment] 2023-02-13 22:43
This is likely a bug and I'll investigate, thanks!

**Comment by rklubenspies** [comment] 2023-02-14 05:44
Also having this on a project that uses roughly the following style function in the app directory.

Sample file location: `src/app/(auth)/auth-error/page.tsx`

We're seeing this under Next.JS versions `13.0.7` and `13.1.6`

```ts
export default function ErrorPage({
  searchParams,
}: {
  searchParams: { error?: string }
}) {
  const { error } = searchParams

  if (!error) {
    redirect('/404')
  }

  return(
    // some UI code
  )
}
```

**Comment by rklubenspies** [comment] 2023-02-14 06:20
@Ziothh Here's how we're solving this in our app in the short-term as this gets looked into—we're essentially typing the `searchParams` as any key-value pair per Next.JS beta docs. But this typing allows a string array on our searchParams key—this doesn't work for us, so we're coercing its value to either `string` or `undefined` before using it:

```ts
export function stringOrUndefined(
  value: string | string[] | undefined,
): string | undefined {
  return value === undefined ? undefined : value.toString()
}

export default function ErrorPage({
  searchParams,
}: {
  searchParams: [key: string]: string | string[] | undefined
}) {
  const error = stringOrUndefined(searchParams.error)

  if (!error) {
    redirect('/404')
  }

  return(
    // some UI code
  )
}
```

**Comment by AryanJ-NYC** [comment] 2023-02-14 19:51
I'm running next.js 13.1.6. I had this same error. Fixed with:

```ts
import type { PageComponent } from '../../../../.next/types/app/page';

const InscriptionDetailPage: PageComponent = async ({
  params: { name },
}: {
  params: { name: string };
}) => {
```

next.js should probably export `PageComponent` for us.

**Closed** 2023-02-15 14:49 UTC
Labels: template: bug, area: TypeScript

**Comment by Ziothh** [comment] 2023-02-28 18:31
> 

Thanks! I'll keep that in mind for now.

**Comment by Ziothh** [comment] 2023-02-28 18:32
> @Ziothh Here's how we're solving this in our app in the short-term as this gets looked into—we're essentially typing the `searchParams` as any key-value pair per Next.JS beta docs. But this typing allows a string array on our searchParams key—this doesn't work for us, so we're coercing its value to either `string` or `undefined` before using it:
> 
> ```ts
> export function stringOrUndefined(
>   value: string | string[] | undefined,
> ): string | undefined {
>   return value === undefined ? undefined : value.toString()
> }
> 
> export default function ErrorPage({
>   searchParams,
> }: {
>   searchParams: [key: string]: string | string[] | undefined
> }) {
>   const error = stringOrUndefined(searchParams.error)
> 
>   if (!error) {
>     redirect('/404')
>   }
> 
>   return(
>     // some UI code
>   )
> }
> ```

Thanks! I'll keep that in mind for now.

**Comment by kelvinpraises** [comment] 2023-03-22 20:40
Making searchParams optional fixes it for me

```tsx
export default function Journal({
  params,
  searchParams,
}: {
  params: { journal: string };
  searchParams?: { [key: string]: string | string[] };
}) {
  const bgState = useStore((state) => state.setBackgroundState);

  useEffect(() => {
    bgState({ showBg: true });
  }, []);

  return (
    <SMain>
      <SharedJournalContent params={params} searchParams={searchParams!} />
    </SMain>
  );
}
```

**Comment by kelvinpraises** [comment] 2023-03-22 20:44
> ```ts
> import type { PageComponent } from '../../../../.next/types/app/page';
> ```

The interface for page props is this

```tsx
interface PageProps {
  params: any
  searchParams?: any
}
```
