### ISSUE TITLE
Inconsistent loading order of CSS Modules

### ISSUE THREAD

**Issue by olegKusov** [vercel/next.js#30251] opened 2021-10-25 06:16 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Safari

### What operating system are you using?

MacOS

### How are you deploying your application?

next start

### Describe the Bug

Duplicating issue [#10148](https://github.com/vercel/next.js/issues/10148)

I'm having same problem know and issue #10148 closed by vercel as resolved.

I have imported in _app.tsx global.css file but it loads in browser after local styles in styles.module.css of my component.

### Expected Behavior

global.css file should be imported before local styles.

### To Reproduce

import global.css in _app.tsx and then use local styles.

**Comment by Maczuga** [comment] 2021-11-05 15:09
https://github.com/Maczuga/nextjs-cssmodule-order-bug - sample repo

What's wrong? In debug/dev mode - CSS modules classes are being applied in incorrect order:
![image](https://user-images.githubusercontent.com/544349/140532788-0fc9bb35-3ba9-42b6-a257-a29985c22663.png)

Expected (and working after build and run):
![image](https://user-images.githubusercontent.com/544349/140532680-89165b39-2a56-4797-b174-65fa6597a600.png)

To reproduce:

1. Pull sample repo https://github.com/Maczuga/nextjs-cssmodule-order-bug
2. Install deps
3. npm/yarn dev to see the invalid CSS order
4. Stop dev mode
5. npm/yarn build -> run to see the CSS being different but correct.

**Comment by timneutkens** [comment] 2021-11-17 15:50
Closing as duplicate of #16630

**Closed by timneutkens** 2021-11-17 15:50 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
