### ISSUE TITLE
500 Internal server error for @next/image images when hosting on AWS

### ISSUE THREAD

**Issue by dclipca** [vercel/next.js#27453] opened 2021-07-24 04:36 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

v16.5.0

### What browser are you using?

Brave and Firefox

### What operating system are you using?

Ubuntu

### How are you deploying your application?

AWS EC2

### Describe the Bug

Every ```@next/image``` image isn't loaded. I am getting 500 Internal server errors for every @next/image images when hosting on an AWS EC2. The non-```@next/image``` work fine. Same story on Next 10. Everything works fine on localhost.

I am using the commands

```npx next build```
```npx next start -p 80```

### Expected Behavior

The ```@next/image``` images should load.

### To Reproduce

Create a new website with Next. Run:
```npx next build```
```npx next start -p 80```

**Comment by wadehammes** [comment] 2021-07-24 13:28
Did you add your server host name to the next.config for images?

```
module.exports = {
  images: {
    domains: [
      "images.ctfassets.net",
    ],
  },
}
```

**Comment by stealthd3v** [comment] 2021-07-24 17:47
Faced similar issue, adding the domains solved the issue

**Comment by styfle** [comment] 2021-07-28 15:30
Sounds like missing config. Make sure that `next.config.js` is present when running `next build`.

It also could be related to #23523 which is fixed on canary (`yarn add next@canary`)

**Comment by ijjk** [comment] 2021-09-18 17:11
Closing [per above](https://github.com/vercel/next.js/issues/27453#issuecomment-888406068), if you are still having trouble with this feel free to respond with additional info!

**Closed by ijjk** 2021-09-18 17:11 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
