### ISSUE TITLE
API used in with-apollo is returning a 404 page

### ISSUE THREAD

**Issue by glenngijsberts** [vercel/next.js#32731] opened 2021-12-22 13:18 UTC
### What example does this report relate to?

with-apollo

### What version of Next.js are you using?

latest

### What version of Node.js are you using?

16.12.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

N/A

### Describe the Bug

The with-apollo example is not working, see screenshot. This is because the API that's being used for Apollo is returning a 404 page as response, instead of an API response.

![Screenshot 2021-12-22 at 14 16 26](https://user-images.githubusercontent.com/14276144/147098548-1a2c0f69-7bd1-4e31-93e8-cf7cef2d39f2.png)
 

### Expected Behavior

Would be nice if the example would contain a working dummy API.

### To Reproduce

Create example with `yarn create next-app --example with-apollo with-apollo-app` and verify it's not working after starting. Visit https://nextjs-graphql-with-prisma-simple.vercel.app/api, see that it's returning a 404 error.

**Comment by balazsorban44** [comment] 2021-12-22 23:18
The upstream issue seem to be reported here already: https://github.com/prisma-labs/nextjs-graphql-api-examples/issues/3

**Comment by balazsorban44** [comment] 2021-12-23 20:35
Fixed in #32759

**Closed by balazsorban44** 2021-12-23 20:35 UTC
Labels: good first issue, type: upstream, area: examples

**Comment by balazsorban44** [comment] 2022-01-27 01:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
