### ISSUE TITLE
Allow for nested folders (of images) in ios 13 safari latest

### ISSUE THREAD

**Issue by callsea1** [vercel/next.js#14170] opened 2020-06-14 17:42 UTC
# Bug report

When nesting folders inside `public` more than one level deep, images are NOT interpreted on iOS 13

run nextJS in development mode, and connect to your localhost via your phone's safari webbrowser. If an `<img>` tag references an image more than one level deep, it will NOT render. This goes for `src` and `srcset` tags.

Works: storing in public folder, and accessing like so
`/folder1/image1.png1`

broken: string in public folder, nested, and accessing like so 
`/folder1/folder2/image1.png`

## System information

- OS: iOS13
- Browser Safari
- Version of Next.js: 9.1.3
- Version of Node.js: 12.10.0

## Additional context

I resolved this problem by removing the nested dependencies, reshuffling photos. The frustrating part is it worked in EVERY OTHER context, examples of it working with nested folders:
1. On Chrome (desktop and ios)
2. On Safari (on mac)
3. Simulator iphone x, ios 13, safari

So this one edge case exists, where it barfs on iOS, with nested folders.

**Comment by chuabingquan** [comment] 2020-06-20 13:50
@callsea1 is it possible for you to create a sample repository that reproduces this problem? I'm unable to reproduce your issue despite following the specifications and description of your system information.

**Comment by lachlanjc** [comment] 2021-01-03 07:28
I can’t reproduce this issue :/ can you give more details?

**Comment by Timer** [comment] 2021-01-04 15:59
Closing as 2x people cannot reproduce. Thanks all!

**Closed by Timer** 2021-01-04 15:59 UTC
Labels: good first issue, please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
