### ISSUE TITLE
Unable to parse middleware config when using array and turbopack

### ISSUE THREAD

**Issue by justinh00k** [vercel/next.js#64747] opened 2024-04-18 19:03 UTC
### Link to the code that reproduces this issue

https://github.com/justinh00k/next_middleware_bug_repro

### To Reproduce

1. Tested with next 14.2.2 and v14.3.0-canary.9
2. Add middleware.ts (or .js) and use object in [array syntax](https://nextjs.org/docs/app/building-your-application/routing/middleware#matcher) for config export:
`export const config = {
	matcher: [
		{
			source: '/((?!api|_next/static|.*\\..*|_next/image).*)',
		},
	],
};
`
3. Run `next dev --turbo`

### Current vs. Expected behavior

Console logs error:
`
⚠ ./middleware.js
Unable to parse config export in source file
The exported configuration object in a source file need to have a very specific format from which some properties can be statically parsed at compiled-time.
`

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112
  Available memory (MB): 24576
  Available CPU cores: 8
Binaries:
  Node: 18.18.2
  npm: 10.5.2
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  next: 14.2.2 // Latest available version is detected (14.2.2).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Middleware, Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by kwonoj** [comment] 2024-04-18 19:43
I believe this is dupe of https://github.com/vercel/next.js/issues/63896

**Closed** 2024-04-18 20:06 UTC
Labels: bug, Turbopack
