### ISSUE TITLE
Link import code broken since 9.5.0 (Type error: Cannot use namespace 'Link' as a type.)

### ISSUE THREAD

**Issue by ElvenSpellmaker** [vercel/next.js#16493] opened 2020-08-23 13:49 UTC
# Bug report

## Describe the bug

Since 9.5.0 our app won't compile as the module code contains the Link type followed straight by a Namespace and exports the Namespace instead of the type.
![image](https://user-images.githubusercontent.com/2286713/90979498-559fcd00-e54d-11ea-9a8b-e19a13df4d3b.png)

Module code:
![image](https://user-images.githubusercontent.com/2286713/90979509-5e909e80-e54d-11ea-8e8a-328b9d2bbd8d.png)

## To Reproduce

https://github.com/amido/stacks-webapp-template/blob/master/packages/scaffolding-cli/templates/src/ssr/components/Link/index.tsx

Using code like the above compile the application with `node_modules/.bin/tsc --project tsconfig.server.json` and then `node_modules/.bin/next build`.

## Expected behavior

Compiles correctly.

## System information

- OS: Windows, Cygwin or Ubuntu
- Browser N/A
- Version of Next.js: >9.5.0
- Version of Node.js: v12.13.0 or 12.18.3

**Comment by lfades** [comment] 2020-08-23 19:05
Hi @ElvenSpellmaker - Could you update to latest canary, the types should be:

```
```

**Comment by ElvenSpellmaker** [comment] 2020-08-23 19:12
Hey @lfades, I've just tried the latest canary and get this now:
![image](https://user-images.githubusercontent.com/2286713/90986712-c1e5f500-e57c-11ea-82c7-c2e5e765a1c6.png)

Yeah sorry I didn't write the code that's there and TypeScript isn't really a language I know very well, it's possible I'd need to defer this to someone who uses TypeScript more often than me. 😕

**Comment by lfades** [comment] 2020-08-23 19:32
@ElvenSpellmaker No, `Link["props"]` isn't valid, `Link` is a value, not a type. Meanwhile `LinkProps` is a type designed for this case.

**Comment by Timer** [comment] 2020-08-24 01:31
Closing as this is the intended behavior as explained by @lfades (and OP ack'd).

**Closed by Timer** 2020-08-24 01:31 UTC
Labels: kind: story

**Comment by balazsorban44** [comment] 2022-01-29 16:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
