### ISSUE TITLE
Using writeHead to redirect in `getServerSideProps` fails on Safari

### ISSUE THREAD

**Issue by mirshko** [vercel/next.js#12409] opened 2020-05-02 12:45 UTC
# Bug report

## Describe the bug

Using a Next `Link` component to route to a page where there is a check to see if a cookie is defined, and if so to redirect the user seems to fail on Safari. 

```js
// login.js

export async function getServerSideProps(ctx) {
  // Nookies parse cookies function to get the current cookies
  const cookies = parseCookies(ctx);

  if (cookies.token) {
    ctx.res.writeHead(303, { Location: "/admin" });
    ctx.res.end();
  }

  return { props: {} };
}
```

The `Link` component points to `/login` and is in the global navigation.

It seems that clicking on this on Safari changes the current path to `/login` however nothing happens. 

On Chrome it seems that the page is properly redirected to `/admin` should the token cookie be defined.

## Expected behavior

res.writeHead() behaves the same on Safari as it does on Chrome.

## System information

- OS: macOS Catalina 10.15.4 (19E287)
- Browser (if applies) Safari Version 13.1 (15609.1.20.111.8)
- Version of Next.js: 9.3.5
- Version of Node.js: v14.0.0

**Comment by joaquimds** [comment] 2020-05-04 15:14
I think the same problem occurs with FireFox. I've followed this blog post to implement the same functionality, but a different way:

https://sergiodxa.com/articles/redirects-in-next-the-good-way/

**Comment by mirshko** [comment] 2020-05-05 21:31
Yeah I noticed it happened there too.

**Comment by mirshko** [comment] 2020-05-05 22:07
@joaogranado wondering if there's a new solution to handle this with Next 9.3 new routing stuff with getServerSide, 

I'd rather not use getInitialProps anymore

**Comment by hmtri1011** [comment] 2020-05-06 08:34
![image](https://user-images.githubusercontent.com/16288424/81155193-e195e500-8fae-11ea-8eb6-f718cc5d244b.png)

Happened to me too, here is the console error log

**Comment by justincy** [comment] 2020-05-19 21:18
The line in `router.js` that the error comes from is https://github.com/zeit/next.js/blob/0d05904552dc4ba517ec158446c175d72a78814f/packages/next/next-server/lib/router/router.ts#L493

But that's just where it gets thrown. This is where it originates:

https://github.com/zeit/next.js/blob/0d05904552dc4ba517ec158446c175d72a78814f/packages/next/next-server/lib/router/router.ts#L134

The error being caught there is `SyntaxError: The string did not match the expected pattern.` likely because the client was expecting JSON but received HTML.

But I don't know why setting the `code` property of the `SyntaxError` is readonly. If you create a SyntaxError in the console and try to set the code, it works fine.

**Comment by justincy** [comment] 2020-05-19 21:36
Setting the code throws an error because it's running in [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Converting_mistakes_into_errors).

**Comment by justincy** [comment] 2020-05-19 21:46
In a production build, the error is caught and you are shown the error page. This differs from the behavior exhibited by Chrome where the redirect works after Next triggers a full page reload.

**Comment by jhaemin** [comment] 2020-05-20 01:57
<img width="610" alt="Screen Shot 2020-05-20 at 10 44 19 AM" src="https://user-images.githubusercontent.com/19797697/82395637-e6ff2f00-9a86-11ea-8f4e-e5fb4e92b5c0.png">

Same here.
I just replaced the Next Links with HTML anchor tags where the pages using `res.writeHead()`.

**Comment by revolunet** [comment] 2020-06-18 21:25
i can confirm this issue on Safari and Edge as well. server-side redirections triggers the error page

**Comment by eegli** [comment] 2020-07-01 13:14
Can confirm as well, happens only in production and in Safari on iOS 13.5.1. 
Unfortunately, replacing the `Link` component by `Next.js` is not an option for me.

**Comment by ItsJohnTheDeveloper** [comment] 2020-07-07 19:52
Does anybody know the status of this bug?

**Comment by kachkaev** [comment] 2020-07-07 20:32
@ItsJohnTheDeveloper see https://github.com/vercel/next.js/discussions/14890

**Comment by tiivik** [comment] 2020-07-10 19:31
> I think the same problem occurs with FireFox. I've followed this blog post to implement the same functionality, but a different way:
> 
> https://sergiodxa.com/articles/redirects-in-next-the-good-way/

Thanks for sharing this, was able to work around this issue with that method.

**Comment by revolunet** [comment] 2020-07-22 23:52
Looks like this also affects `Router.push()` when you push some page that return a `30x`

**Comment by justincy** [comment] 2020-08-10 18:23
This issue should be fixed with this PR that was just merged into canary: https://github.com/vercel/next.js/pull/16051

**Comment by ijjk** [comment] 2020-09-10 21:21
Hi, as mentioned above this should be resolved by https://github.com/vercel/next.js/pull/16051 now and we are also aiming to streamline redirecting in these functions with https://github.com/vercel/next.js/discussions/14890.

I'm going to close this since it should be addressed, if you are still having problems with this please reply with additional info

**Closed by ijjk** 2020-09-10 21:21 UTC
Labels: kind: bug, type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-29 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
