### ISSUE TITLE
Dev server is taking too much memory in my Macbook & Windows machine

### ISSUE THREAD

**Issue by sidddev7** [vercel/next.js#64183] opened 2024-04-08 03:33 UTC
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/serene-bogdan-v82nfh

### To Reproduce

1. Start The development server
2. Open the localhost server on browser to start compiling the components
3. Look at the process utilisation
4. You will find next-server utilising so much CPU and memory

### Current vs. Expected behavior

Current
- next-server is taking so big memory space in the machine making other process starve for memory like vscode
Expected Behaviour
- next-server should not take this much memory of a machine during development 

<img width="942" alt="Screenshot 2024-04-08 at 8 45 10 AM" src="https://github.com/vercel/next.js/assets/61483081/ade8c70e-421b-435d-a95d-77af2f692fc3">

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112
Binaries:
  Node: 20.12.1
  npm: 10.5.0
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  next: 14.1.4
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Link to the code that reproduces this issue
https://stackblitz.com/edit/stackblitz-starters-8kqwee

To Reproduce
Start The development server
Open the localhost server on browser to start compiling the components
Look at the process utilisation
You will find next-server utilising so much CPU and memory
Current vs. Expected behavior
Current:

next-server is taking so big memory space in the machine making other process starve for memory like vscode
Screenshot 2024-04-08 at 8 45 10 AM
Provide environment information
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112
Binaries:
  Node: 20.12.1
  npm: 10.5.0
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  next: 14.1.4
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.4
Next.js Config:
  output: N/A
Which area(s) are affected? (Select all that apply)
Not sure

Which stage(s) are affected? (Select all that apply)
next dev (local)

Additional context
I tested it on both Mac and Windows OS and found same behaviour, i am developing a project using next14 and when i save a file, it takes so long to save it on my Brand new macbook pro M2.

Please folks, lets look at this issue as it is hindering the development flow of thousands of developers around the world

**Comment by r34son** [comment] 2024-04-10 18:41
https://github.com/vercel/next.js/issues/54708

**Comment by sidddev7** [comment] 2024-04-12 05:41
I have created a Bare-starter nextjs app with some dependencies like firebase and antd
https://github.com/sidddev7/pasSync
You can run this code and see the memory utilization of the next-server in any machine, you will notice a sudden hike in usage

**Comment by timneutkens** [comment] 2024-04-13 17:12
Duplicate of https://github.com/vercel/next.js/issues/54708.

App Router bundles node_modules, which Pages Router did not do, which might explain slightly more memory usage depending on the amount of modules, in the reproduction, which unfortunately is not really a reproduction as only the package.json is changed, so running it doesn't hold meaningful data. Looking at the package.json you're likely importing all components of antd though, which would hold meaningful memory usage as it's quite a large library if you're importing all of it.

Going to close it as there's already another issue.

**Closed by timneutkens** 2024-04-13 17:12 UTC
Labels: template: bug

**Comment by guillermo-avalos** [comment] 2024-04-25 21:08
Working on an older project with `Pages` directory. `next-server` v14.2.3 idles at around 3 GB of memory, it's nuts. I cannot pin-point the issue yet.

**Comment by mooyg** [comment] 2024-04-26 13:15
![image](https://github.com/vercel/next.js/assets/61348580/a52bed3f-5a1b-4be7-8662-ac8089c9ccb2)
Same issue with me too, on `Pages` router as well takes up way too much resources

**Comment by guillermo-avalos** [comment] 2024-04-26 15:50
I downgraded to **v14.1.3** as I have another - much smaller - project that only consumes around 500 MB and it's using that version.. In this bigger project, however, even 14.1.3 idles at 2.3 GB.  Both use `Pages` dir, both have similar backends. The only difference is that this one is much bigger (lots of components).
