### ISSUE TITLE
Global CSS Compile issue when any page contains getStaticProps

### ISSUE THREAD

**Issue by chasen** [vercel/next.js#28669] opened 2021-08-31 17:36 UTC
### What version of Next.js are you using?

11.1.1

### What version of Node.js are you using?

14.17.5

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

next build

### Describe the Bug

The issue seems to be that you can not run the build command if you have global styles used in _app.js. For what ever reason it thinks that page should be a module.

### Expected Behavior

I would expect this to just build. It seems to be an issue with a directory separator but thats just a guess.

### To Reproduce

Install new project:

```bash
npx create-next-app next-bug-steps
```
then create a new page: `/pages/[test]/index.js`

```
export default function Index({increment}) {
    return <h1>Testing: {increment}</h1>;
}

export function getStaticProps(ctx){
    return {
        props: {
            increment: ctx.params.test
        }
    }
}

export function getStaticPaths(){
    return {
        paths: [],
        fallback: true
    }
}
```

With the other files from the base project still in place run:

```bash
npm run build
```

I get the following error:
```
./styles/globals.css
Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
Location: pages\_app.js
```

**Comment by chasen** [comment] 2021-08-31 20:58
In a project that I initially discovered the issue with im using `dart-sass`.  Latest version 1.38.3 seems to have this issue. However if I downgrade to 1.38.2 everything works as expected. However this doesnt explain why the base project without sass has this issue too

**Comment by ijjk** [comment] 2021-08-31 21:05
This should be fixed in the latest version of Next.js `v11.1.2`, please update and give it a try!

**Closed by ijjk** 2021-08-31 21:05 UTC
Labels: template: bug

**Comment by chasen** [comment] 2021-08-31 21:20
Can confirm this does indeed fix this issue, thank you for the fast update!

**Comment by balazsorban44** [comment] 2022-01-27 21:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
