### ISSUE TITLE
[NEXT-1030] `output: 'export'` with `use client` in dynamic routes doesn't work

### ISSUE THREAD

**Issue by qpre** [vercel/next.js#48022] opened 2023-04-06 14:26 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.32
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Static HTML Export (output: "export")

### Link to the code that reproduces this issue

https://github.com/qpre/next-app-dir-dynamic-with-static-export

### To Reproduce

- run `yarn install`
- run `yarn build`
- open the `out` folder and see that static pages are rendered but `/toto/[toto].html` is missing, based on the [docs](https://beta.nextjs.org/docs/configuring/static-export#dynamic-fetching-with-client-components) it should be exported.

### Describe the Bug

static routes are exported but the ones with dynamic params are not.

### Expected Behavior

based on the [docs](https://beta.nextjs.org/docs/configuring/static-export#dynamic-fetching-with-client-components) dynamic routes using 'use client' should be exported.

<sub>[NEXT-1030](https://linear.app/vercel/issue/NEXT-1030/output-export-in-1331-canary-does-not-export-dynamic-routes-from)</sub>

**Comment by ivoiv** [comment] 2023-04-06 16:37
Can confirm.
I'm still trying to find a version in which this actually works.

**Comment by abduraufsherkulov** [comment] 2023-04-07 11:04
Issue still persists in 13.3.1-canary.0 @qpre

**Comment by hyunjunian** [comment] 2023-04-11 08:42
I am looking forward to this feature very much. Please check and resolve this problem!

**Comment by johnny-mh** [comment] 2023-04-12 15:10
Same here

**Comment by klcantrellsep** [comment] 2023-04-15 00:36
I pulled down the repro project and upgraded it to 13.3.1-canary.7. In addition to the issues described above, I notice that `next build` outputs the dynamic route as server-side rendered:

```
Route (app)                                Size     First Load JS
┌ ○ /                                      178 B          80.2 kB
├ ○ /about                                 178 B          80.2 kB
├ ○ /toto                                  141 B          74.7 kB
└ λ /toto/[toto]                           736 B          75.3 kB        <-- here 
+ First Load JS shared by all              74.5 kB
  ├ chunks/2443530c-d36173516156a79f.js    50.5 kB
  ├ chunks/961-410119e98d707b91.js         22.2 kB
  ├ chunks/main-app-4fd98d23d091d9e6.js    213 B
  └ chunks/webpack-8074fabf81ca3fbd.js     1.61 kB

Route (pages)                              Size     First Load JS
─ ○ /404                                   178 B            86 kB
+ First Load JS shared by all              85.8 kB
  ├ chunks/main-c0915425be0ab499.js        84 kB
  ├ chunks/pages/_app-c544d6df833bfd4a.js  192 B
  └ chunks/webpack-8074fabf81ca3fbd.js     1.61 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
```

**Comment by klcantrell** [comment] 2023-04-15 00:37
I pulled down the repro project and upgraded it to 13.3.1-canary.7. In addition to the issues described above, I notice that `next build` outputs the dynamic route as server-side rendered:

```
Route (app)                                Size     First Load JS
┌ ○ /                                      178 B          80.2 kB
├ ○ /about                                 178 B          80.2 kB
├ ○ /toto                                  141 B          74.7 kB
└ λ /toto/[toto]                           736 B          75.3 kB        <-- here 
+ First Load JS shared by all              74.5 kB
  ├ chunks/2443530c-d36173516156a79f.js    50.5 kB
  ├ chunks/961-410119e98d707b91.js         22.2 kB
  ├ chunks/main-app-4fd98d23d091d9e6.js    213 B
  └ chunks/webpack-8074fabf81ca3fbd.js     1.61 kB

Route (pages)                              Size     First Load JS
─ ○ /404                                   178 B            86 kB
+ First Load JS shared by all              85.8 kB
  ├ chunks/main-c0915425be0ab499.js        84 kB
  ├ chunks/pages/_app-c544d6df833bfd4a.js  192 B
  └ chunks/webpack-8074fabf81ca3fbd.js     1.61 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
```

**Comment by qpre** [comment] 2023-04-18 08:33
The issue is still present in the latest canary (13.3.1-canary.12 at the time of writing).

My only interrogation is if it is on the roadmap for 13.3.1 or if we should just find another way until the subject comes up in vercel's roadmap, which would be perfectly fine seeing the amount of work they put in the new features at the moment, but maybe the beta docs should be updated as to not mislead someone who would invest time in trying this feature :)

**Comment by stefanullinger** [comment] 2023-04-19 05:13
Hi, I am also running into this issue here.
Thanks for looking into it, @styfle!

**Comment by styfle** [comment] 2023-04-19 14:50
I confirmed this is still a bug. Feel free to create a PR with a test. Otherwise I will come back to this in a couple weeks 👍

**Comment by qpre** [comment] 2023-04-19 17:39
thanks for the update @styfle ! looking forward for this !

**Comment by kneza23** [comment] 2023-04-21 08:00
Hi, we are having the same problem, it treats dynamic route as it does not exist and redirects to root page.

**Comment by re-thc** [comment] 2023-05-04 17:51
This still fails as of `13.4.0`. At least there is an error now.

`> Build error occurred
Error: invariant: Undefined export worker for app dir, this is a bug in Next.js.`

**Comment by hopedope** [comment] 2023-05-08 21:33
@styfle any update on this? it's been several weeks. Would love to use NextJS with app dir, static export and client side data fetching but this is a huge blocker and I may need to move away from NextJS or go back to deprecated pages router because of this.

Docs say it should work: https://nextjs.org/docs/app/building-your-application/deploying/static-exports#dynamic-fetching-with-client-components. But it still does not work even with `13.4.2-canary.2`

**Comment by ytsruh** [comment] 2023-05-09 18:33
It would be nice to get some commentary on this issue. Next is now the official way to build React apps yet this quite basic functionality doesn't function. Until this is resolved I think either the[ NextJS](https://nextjs.org/docs/app/building-your-application/deploying/static-exports) docs should be updated OR [React](https://react.dev/learn/start-a-new-react-project) should be updated to reflect that this is not currently a viable option.

**Comment by ytsruh** [comment] 2023-05-09 19:47
OK this has clearly been misinterpreted. If I came across as either passive or agressive that was not my intent. I think my comment was more toward the React team than Next - eg if something is not ready it should be put in the official docs. 

To be clear, I have absolutely no issue with Next having these issues, it is to be expected. However that is not in keeping with it being the first recommended way of starting a React project when, combined with the App Router now being stable & the preferred way of starting a Next project. This issue addresses a very basic React use case. 

This is probably not the best place for further discussion. If I've offended anybody with my last comment then either reach me on Twitter (the_chrishurst) or in [this discussion](https://github.com/vercel/next.js/discussions/49517) that I started.

**Comment by styfle** [comment] 2023-05-10 18:50
I discussed this problem with the team, and we decided it extends beyond `output: 'export'`.

Previously, with Pages Router, the routes manifest was downloaded by client. One of the improvements with App Router is that this is no longer necessary meaning fewer bytes need to download.

What we need is some way to indicate "offline" to prefetch routes, bundles, etc. Then we can use this new mode with `output: 'export'`.

The best you can do today with `output: 'export'` generate the routes at build time using `generateStaticParams()` like this:

https://github.com/qpre/next-app-dir-dynamic-with-static-export/pull/1

We'll follow up here once we have a proper solution, thanks!

**Comment by hopedope** [comment] 2023-05-10 19:05
We should update the docs here https://nextjs.org/docs/app/building-your-application/deploying/static-exports#dynamic-fetching-with-client-components and mention this feature is not supported at all.

**Comment by styfle** [comment] 2023-05-10 19:37
@hopedope Thanks, I must have missed that link in the original post 👍 

I'll talk to the docs team to remove that section and figure out why it was documented in the first place (because we obviously shouldn't document features that aren't implemented 😅)

**Comment by re-thc** [comment] 2023-05-10 23:49
@styfle is it a different bug we need to make if export doesn't work with generateStaticParams? Haven't had it working this way since 13.3.1. Thanks.

**Comment by styfle** [comment] 2023-05-11 02:04
@re-thc Yes, that sounds like a different bug. Please create a new issue with the steps to reproduce, thanks!

**Comment by Ofir-Efraim** [comment] 2023-05-25 06:09
Any updates?

**Comment by mtr1990** [comment] 2023-06-06 09:55
"next": "^13.4.4",

Still not found dynamic routes in out directory after build. 

Will we have this feature or will not support it?

Servers other than deploy only support export. Therefore, the product cannot be deployed.

Do we have any solution?

**Comment by slotZero01** [comment] 2023-06-11 09:37
still have a problem exporting dynamic segment path as a SPA. In this case, how NextJs suppose to replace create react app? Not all use case wants to run server just for Frontend

**Comment by Athrun-Judah** [comment] 2023-06-13 06:14
still have a problem in 13.4.5

**Comment by alessandro-accattoli** [comment] 2023-06-14 11:29
I probably found a tricky workaround for this.
Basically in the Server Component `page.js` inside the `/app/blog/[slug]` folder I added the function `generateStaticParams` that returns just an array like this: `[{ slug: ‘__slug__’ }]` and in the render of the page I call a Client Component `<BlogSinglePost />.`
In this way when I build the app with static export I have the file `__slug__.html` inside the folder `/out/blog`.
Then in nginx I use a location rewrite directive for point to that file.

Notice that for access the url params inside the client component you can’t use the hook `useParams` but you have to use `window.location`.

I know that this way is not a fix, is just a temporarily workaround for use the dynamic route in static export of NextJs with the app folder.
I hope that this thing could be useful for someone.

PS: I have tested but not that much to say that is a safe and compliant way for handle this situation.

**Comment by shainegordon** [comment] 2023-06-14 11:31
> Hi, we are having the same problem, it treats dynamic route as it does not exist and redirects to root page.
> 
> Temporary fix (but ugly one) is to use `useSearchParams` and instead of `item/123` to use` item?id=123`

This IMO is the best “workaround”. Everyone can still understand this model, and does not require infra changes

**Comment by hyunjunian** [comment] 2023-06-16 08:44
In the [nextjs document](https://nextjs.org/docs/app/building-your-application/deploying/static-exports), the introduction of this function is removed.

**Comment by guofei0723** [comment] 2023-06-25 10:39
still have a problem in 13.4.7

**Comment by Last-Autumn-Leaf** [comment] 2023-06-27 06:58
still have the problem in ^13.4.4

**Comment by qpre** [comment] 2023-06-27 13:58
> What we need is some way to indicate "offline" to prefetch routes, bundles, etc. Then we can use this new mode with `output: 'export'`.
> [...]
> We'll follow up here once we have a proper solution, thanks!

Hello @styfle, just asking for news, has the team figured out a way of building this ?

Thanks in advance !

**Comment by styfle** [comment] 2023-06-27 20:10
We hear you! This is not something we are working on at the moment. 

To learn more, see my [previous comment](https://github.com/vercel/next.js/issues/48022#issuecomment-1542654383). Also read about our current focus in the [June 2023](https://nextjs.org/blog/june-2023-update) blog post.

<sub>Remember to upvote the original post at the top by clicking the "👍" button so we have visibility when [sorting](https://github.com/vercel/next.js/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).</sub>

**Comment by qpre** [comment] 2023-06-28 07:43
Thanks for the update !

**Comment by mtr1990** [comment] 2023-07-04 13:03
> We hear you! This is not something we are working on at the moment.
> 
> To learn more, see my [previous comment](https://github.com/vercel/next.js/issues/48022#issuecomment-1542654383). Also read about our current focus in the [June 2023](https://nextjs.org/blog/june-2023-update) blog post.
> 
> Remember to upvote the original post at the top by clicking the "👍" button so we have visibility when [sorting](https://github.com/vercel/next.js/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

Not sure if this is a temporary fix but it works. Thanks!

<img width="296" alt="Screenshot 2023-07-04 at 20 01 59" src="https://github.com/vercel/next.js/assets/13531993/76ea89ca-d6d5-485d-b2a4-a7aa4752d40e">

**Comment by 0zuna** [comment] 2023-07-06 16:59
still have a problem in 13.4.8, this problem is very important for static use

**Comment by AndonMitev** [comment] 2023-07-13 13:48
still problem at 13.4.9 any new updates?

**Comment by steve-haar** [comment] 2023-07-19 21:04
> 

The problem I run into is that changing searchParams with `output: 'export'` causes a hard navigation which will significantly degrade performance in my case.

**Comment by ides15** [comment] 2023-07-20 17:50
This seems like basic functionality for a web app and I think it should be given a higher priority.

Consider the Reddit website. Routing includes:
- `/`
- `/r/:subredditName`
- `/r/:subredditName/new`
- `/r/:subredditName/top`
- `/r/:subredditName/top/?t=all`
- `/r/:subredditName/comments/:postId/:postName/`

If the Reddit site was built as a Next.js static app, using any of the dynamic segments here wouldn't work - and it's not like Reddit can use `generateStaticParams` and rebuild their site for each new subreddit/post/comment that gets created.

This isn't a problem specific to apps as big as Reddit, either. Any small app that contains dynamic content could want routing like this. And the reality of it is that some (most?) web apps will start out **not** needing the server-side features that Next.js provides and will just function as a static site or SPA. Sure, these server-side features can be helpful and very powerful, but I for one was drawn to Next.js purely for the developer experience and routing features.

**I don't want to be forced into using any server-side features when I don't need them yet.** Static sites or SPAs are always going to be cheaper to host and easier to manage **at a low scale** than a web app requiring a server.

I love the framework! Really want to use it, but this is a big blocker for me (and probably others). I think this should also be called out more prominently in the [docs](https://nextjs.org/docs/app/building-your-application/deploying/static-exports) - building an entire app in Next.js then deploying it, only to find that dynamic routing isn't supported for static apps will turn many people off from the framework.

**Comment by jrozbicki** [comment] 2023-07-20 17:56
> This seems like basic functionality for a web app and I think it should be given a higher priority.
> 
> 
> 
> Consider the Reddit website. Routing includes:
> 
> - `/`
> 
> - `/r/:subredditName`
> 
> - `/r/:subredditName/new`
> 
> - `/r/:subredditName/top`
> 
> - `/r/:subredditName/top/?t=all`
> 
> - `/r/:subredditName/comments/:postId/:postName/`
> 
> 
> 
> If the Reddit site was built as a Next.js static app, using any of the dynamic segments here wouldn't work - and it's not like Reddit can use `generateStaticParams` and rebuild their site for each new subreddit/post/comment that gets created.
> 
> 
> 
> This isn't a problem specific to apps as big as Reddit, either. Any small app that contains dynamic content could want routing like this. And the reality of it is that some (most?) web apps will start out **not** needing the server-side features that Next.js provides and will just function as a static site or SPA. Sure, these server-side features can be helpful and very powerful, but I for one was drawn to Next.js purely for the developer experience and routing features.
> 
> 
> 
> **I don't want to be forced into using any server-side features when I don't need them yet.** Static sites or SPAs are always going to be cheaper to host and easier to manage **at a low scale** than a web app requiring a server.
> 
> 
> 
> I love the framework! Really want to use it, but this is a big blocker for me (and probably others). I think this should also be called out more prominently in the [docs](https://nextjs.org/docs/app/building-your-application/deploying/static-exports) - building an entire app in Next.js then deploying it, only to find that dynamic routing isn't supported for static apps will turn many people off from the framework.

This is so true! If we can't fix it at the moment, please at least make it as clear as possible in the docs, so that more people will not fall into this trap...

**Comment by 0zuna** [comment] 2023-07-20 18:23
this bug is so important. and no priority is given. This bug means that there is no compatibility with static sites.
and in the doc it says yes, but this bug proves no.
routing is basic in every application

**Comment by dongoa** [comment] 2023-07-24 04:56
i waiting the bugfixed

**Comment by luminus-xd** [comment] 2023-07-29 13:59
I think this is a basic and very important feature for creating a static site and should be mentioned in the documentation.

**Comment by AlexMcClay** [comment] 2023-08-01 09:26
Encountered the same issue now. Cant believe Next doesn't support this simple feature.

**Comment by crs1138** [comment] 2023-08-02 07:31
To sum up all the previous posts:
1. Am I right to understand that exporting dynamic routes as static pages currently does NOT work with the App Router?
2. Is the preferred solution to stick with the Pages Router for these pages for now?

**Comment by crs1138** [comment] 2023-08-02 09:21
I mean, I'm trying to achieve what is described in the documentation [Deploying > Static Exports > Deploying](https://nextjs.org/docs/app/building-your-application/deploying/static-exports#deploying) but none of the pages with `[slug]` are exported as HTML.

**Comment by MatinAniss** [comment] 2023-08-02 15:50
This is still a issue as of next 13.4.12 (using Page router), the working alternative is to use query parameters instead of dynamic routes. A bit annoying.

**Comment by ides15** [comment] 2023-08-02 15:56
Has anyone replaced Next.js routing with another router like react-router-dom? Not sure if it's even possible to disable the filesystem routing.

**Comment by omozokelvin** [comment] 2023-08-04 18:37
This is still issue

**Comment by mingyeungs** [comment] 2023-08-16 08:28
Encountered the same problem and came up with a workaround. Not sure if there are any unspotted issues though:

## Problem

```jsx
/* /app/test/[slug]/page.jsx */
'use client'
import { useState } from 'react'

const ClientPage = ({ params }: { params: { slug: string } }) => {
  const [value, setValue] = useState(params.slug)
  return (
    <div>
      <p>foo is [{ value }]</p>
      <button type="button" onClick={ () => setValue("foo") }>Set foo</button>
    </div>
  )
}

export function generateStaticParams() {
  return [{ slug: 'hello' }, { slug: 'world' }]
}

export default ClientPage
```

build result
```bash
Route (app)
┌ ○ /
└ λ  /test/[slug] 

λ  (Server)  server-side renders at runtime
```

## Workaround

Move `'use client'` and client-side code into component:

```jsx
/* /app/test/[slug]/page.jsx */
import Foo from './Foo'

const ServerPage = ({ params }: { params: { slug: string } }) => {
  return (
    <Foo slug={ params.slug } />
  )
}
export function generateStaticParams() {
  return [{ slug: 'hello' }, { slug: 'world' }]
}
export default ServerPage
```
```jsx
/* /app/test/[slug]/Foo.jsx */
'use client'
import { useState } from 'react'

const Foo = ({ slug }) => {
  const [value, setValue] = useState(slug)

  return (
    <div>
      <p>foo is [{ value }]</p>
      <button type="button" onClick={ () => setValue("foo") }>Set foo</button>
    </div>
  )
}
export default Foo
```

build result
```bash
Route (app)
┌ ○ /
├ ● /test/[slug]
├   ├ /test/hello
└   └ /test/world

●  (SSG)     automatically generated as static HTML + JSON
```

Using Next.js v13.4.12

**Comment by durchanek** [comment] 2023-08-16 08:33
@mingyeungs Unfortunately, this is not a full workaround because it requires slugs to be static.

**Comment by mingyeungs** [comment] 2023-08-16 08:44
@durchanek indeed...hopefully it would be helpful for someone while we wait for a real fix.

**Comment by GabenGar** [comment] 2023-08-21 16:38
How are you supposed to implement client-only dynamic paths on export then?
With `pages` router it was possible to do, with a caveat that all dynamic segments must be client-only. That also meant the built-in multilang support didn't work, so I had to re-implement a client-only multilang detection similar to what `nextjs` recommends for `app` router. Then I was just constructing route queries usable in a `expressjs` server which mapped to the exported files in an adhoc script, which was basically doing `[lang]/blog/[id]` -> `:lang/blog/:id` transforms with the route mapping to  `[lang]/blog/[id].html` file.

**Comment by slotZero01** [comment] 2023-08-21 16:57
for everyone wondering, this is not and will not be supported because of how the SSR router is designed. In static export, there's no logic to match the dynamic routes with the page returned. it's different with server component where the logic resides in the server and CSR routing (react-router) where the logic resides on the client. 

To solve this, you need to build your own router logic, most likely in the server hosting configuration, ex: NGINX server

**Comment by omozokelvin** [comment] 2023-08-21 16:59
Can you please give a simple nginx config that will work for a basic

loans/:id route? Although I've resorted to using query params coupled with adding trailing slash in config which works just fine

**Comment by styfle** [comment] 2023-08-22 17:08
Thanks for all the feedback!

- 📘 The docs for `output: export` have been updated to describe the [Unsupported Features](https://nextjs.org/docs/app/building-your-application/deploying/static-exports#unsupported-features).
- 📕 Both `next dev` & `next build` will error when an unsupported feature is detected (try `npm install next@canary`)
- 📗 The remaining work is described in this new issue: #54393

I'm going to close this issue since it has been a catch all for several issues.

Please add a 👍 reaction to #54393 if this describes the problem you're having.

If your problem is different, please create a new issue with the steps to reproduce, thanks!

**Closed by styfle** 2023-08-22 17:08 UTC
Labels: kind: story, area: app
