### ISSUE TITLE
Click browser back btn cause add extra url path 

### ISSUE THREAD

**Issue by beihai-shinan** [vercel/next.js#27193] opened 2021-07-15 09:34 UTC
### What version of Next.js are you using?

10.0.5

### What version of Node.js are you using?

12.0.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next string

### Describe the Bug

https://user-images.githubusercontent.com/81277028/125765362-5d8a39cd-27d9-4955-bac4-f99ccd1c3f9c.mp4

first use next-translate@1.0.7
step1. when url has query params(important)
step2. router push to another path
step3. click browser's back btn
step4. the video is result

### Expected Behavior

back will work normal 
when `/en?store=xx` to `/en/xx?xxx=xx` then back to `/en/en?store=xx` unexpected
when case `/en` to `/en/xx?xxx=xx`  then back to `/en` it is works 

### To Reproduce

use next-translate@1.0.7 is the reson ? or next router's problem?

**Comment by ijjk** [comment] 2021-07-15 15:30
Hi, are you able to reproduce this on the latest version of Next.js `v11.0.1`? If so can you provide a repo with a minimal reproduction to allow investigating?

**Comment by beihai-shinan** [comment] 2021-07-22 03:23
same as [#24323](https://github.com/vercel/next.js/pull/24323/files)

**Comment by ijjk** [comment] 2021-07-22 03:27
@beihai-shinan that fix is available in the latest version of Next.js `v11.0.1` or `v11.0.2-canary.18`, is the behavior fixed for you after upgrading to one of those versions?

**Comment by ijjk** [comment] 2021-09-18 17:17
Closing per above as this should be fixed in the latest version of Next.js

**Closed by ijjk** 2021-09-18 17:17 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
