### ISSUE TITLE
Auto patch legacy Next.js App `getInitialProps` opt-out

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#14773] opened 2020-07-01 14:46 UTC
```tsx
import App from 'next/app'

class NextApp extends App {
  static async getInitialProps({ Component, ctx }) {
    let pageProps = {}
    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx)
    }

    return { pageProps }
  }

  render() {
    const { Component, pageProps } = this.props

    return (
      <Component {...pageProps} />
    )
  }
}

export default NextApp
```

When we detect this exact code for `getInitialProps` Next.js should ignore it, as it does not introduce any data dependency. However, it opts the entire site out of automatic static optimization.

This likely will need to be implemented as a babel plugin that identifies the exact AST tree and drops it from the file.

**Comment by moh12594** [comment] 2020-07-01 21:57
Hi @Timer 👋
I could take it !

**Comment by timneutkens** [comment] 2021-12-07 13:56
I'm going to close this issue as there's a lot less _app getInitialProps usage nowadays.

**Closed by timneutkens** 2021-12-07 13:56 UTC
Labels: good first issue, kind: story, area: Compiler

**Comment by balazsorban44** [comment] 2022-01-27 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
