### ISSUE TITLE
router.push returning empty params when running getServerSideProps

### ISSUE THREAD

**Issue by stiveurkel** [vercel/next.js#20528] opened 2020-12-28 09:48 UTC
# Bug report

## Describe the bug

I have a system where people have a cart with products, when they press complete order, I create a draft order under the hood with an order_id and then redirect to the contact information page:

```
 router.push({
    pathname: `/checkout/contact-information`,
    query: {
         order: order.order_id,
    },
});
```

During this step, the contact-information page gets an empty order param object, whereas when I refresh the page it gets the proper order params value. 

**I replaced router.push by window.location.href and it works great**, however this is a workaround not a solution.
It was working as expected with version 9.5.3. I have this problem since I upgraded to 10.0.4.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a button where you have router.push with pathname and query as objects
2. Have getServerSideProps on the destination URL
3. console.log the query parms from the destination URL on the getServerSideProps

## Expected behavior

With version 9.5.3 I was doing router.push with pathname and object url and the destination page was getting the query params propery

## Screenshots
On the screenshot below the order query is empty from router.push but has the right value from window.location.href. So something could have changed in the way the router.push is handling getServerSideProps from version 9.5.3 to 10.0.4

query from page refresh OR window.location.href
![image](https://user-images.githubusercontent.com/42664988/103207147-e3c20080-48fd-11eb-8a84-4e6d3e1e68d2.png)

query from router.push
![image](https://user-images.githubusercontent.com/42664988/103207125-d3118a80-48fd-11eb-853e-8fed24edf394.png)

Code used with router.push
![image](https://user-images.githubusercontent.com/42664988/103205326-96dc2b00-48f9-11eb-8799-311a25b8791a.png)
![image](https://user-images.githubusercontent.com/42664988/103205381-b70bea00-48f9-11eb-81e4-b30530eef01f.png)

## System information

- OS: windows 10
- Browser (if applies) chrome
- Version of Next.js: 10.0.4
- Version of Node.js: v12.18.3
- Deployment: [e.g. next start, next export, Vercel, other platform] localhost for dev / digital ocean for prod

**Comment by Timer** [comment] 2020-12-28 16:31
Please provide a complete reproduction so we can take a look at this.

**Comment by timneutkens** [comment] 2021-01-03 10:41
Closing as no reproduction was provided.

**Closed by timneutkens** 2021-01-03 10:41 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-28 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
