### ISSUE TITLE
Dynamic API routes : explicilty requesting url with dynamic slug as [slug]

### ISSUE THREAD

**Issue by ErnestBrandi** [vercel/next.js#23824] opened 2021-04-08 14:57 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

v12.16.3

### What browser are you using?

Firefox

### What operating system are you using?

Ubuntu

### How are you deploying your application?

next dev

### Describe the Bug

When requesting a url with a dynamic segment (ex : `/my/path/[slug]`) with that slug not being replaced by anything (ex : `https://mysite.web/my/path/[slug]`), I got the following error : 
`The provided `href` (/my/path/[slug]?) value is missing query values (slug) to be interpolated properly. Read more: https://nextjs.org/docs/messages/href-interpolation-failed`

### Expected Behavior

To behave as if the slug was wrong (ex : `/my/path/foo` or  `/my/path/[bar]`).

### To Reproduce

https://codesandbox.io/s/dynamic-routes-slug-k7jui

**Comment by matthewwolfe** [comment] 2021-05-06 17:52
I agree with the expected behavior above. During development it is useful to get the error message about interpolation failing, but I would expect in production that instead of an error,  it should trigger whatever error handling exists in the application, such as 404. As it stands now, the error occurs before things like `getStaticProps` is executed, meaning that I don't see a way for this error to be trapped and handled appropriately.

@timneutkens Do you agree that in production interpolation failure should not throw an error, but instead default to the default error handling mechanism, or at least throw the error after it has a chance to be caught and handled via userland code?

If you point me in the right direction I can take a stab at fixing.

**Comment by power-f-GOD** [comment] 2022-01-12 09:59
Hi. I get this error too. Any fix yet? 😢

**Comment by balazsorban44** [comment] 2022-01-27 14:47
Also reported in #33703

**Comment by jameshfisher** [comment] 2022-01-27 20:57
## Alternative steps to reproduce

1. Use [the official `dynamic-routing` example](https://github.com/vercel/next.js/tree/canary/examples/dynamic-routing). 
2. Visit `/post/[id]`

Deployed here: https://aonivqlqx--github--3000.local.webcontainer.io/post/[id]

## Expected behavior

A page without any error, with the title `Post: [id]`. (For comparison, see https://aonivqlqx--github--3000.local.webcontainer.io/post/[foo])

## Actual behavior

```
Unhandled Runtime Error
Error: The provided `href` (/post/[id]?) value is missing query values (id) to be interpolated properly. Read more: https://nextjs.org/docs/messages/href-interpolation-failed
```

**Comment by jameshfisher** [comment] 2022-01-27 20:58
I'm struggling to imagine how this buggy behavior could even exist if the framework is written sanely ...

**Comment by jameshfisher** [comment] 2022-01-27 20:59
Still reproducible in latest version 12.0.9

**Comment by balazsorban44** [comment] 2022-01-28 10:43
> I'm struggling to imagine how this buggy behavior could even exist if the framework is written sanely ...

There is no need for such commentary, please read our [Code of Conduct](https://github.com/vercel/next.js/blob/canary/CODE_OF_CONDUCT.md).

Let's keep the discussion to the point. :pray: :green_heart:

**Comment by jameshfisher** [comment] 2022-01-30 11:33
I looked into it. The bug is here:

https://github.com/vercel/next.js/blob/138361208c5adbb46313ec3674d79536bdfe5172/packages/next/server/base-server.ts#L1535

[The Next docs]{https://nextjs.org/docs/routing/dynamic-routes#caveats) say "Predefined routes take precedence over dynamic routes, and dynamic routes over catch all routes". E.g. for the URL `/accounts/123`, a predefined route `pages/accounts/123.js` should take precedence over the dynamic route `pages/accounts/[id].js`.

This is implemented by, when resolving the page+params for the URL `/accounts/123`, first looking for a predefined route page e.g. `pages/accounts/123.js`. If it doesn't find one, it falls back to a list of dynamic routes.

So given the URL `/accounts/[id]`, it first looks for a predefined route, and finds the route at `pages/accounts/[id].js`. It then interprets this dynamic route as a predefined route, and executes it with no params (since it thinks it's a predefined route). Panic ensues.

**Comment by jameshfisher** [comment] 2022-01-30 11:43
I think this distinction between "predefined routes" and "dynamic routes" is wrong. The correct distinction is between "predefined segments" and "dynamic segments". E.g. if we have `pages/[directory]/[file].js` and `pages/[directory]/home.js`, which should take precedence? They're both "dynamic routes" in that they have `[...]` segments, so the spec doesn't say. But my expectation would be that `pages/[directory]/home.js` should take precedence, because it has a predefined segment `home` where the other has a dynamic segment `[file]`.

The exact precedence ordering is also vague. E.g. if we had `pages/foo/[x].js` and `pages/[y]/bar.js`, which should be used to serve the URL `/foo/bar`? I would _weakly_ expect `pages/foo/[x].js` to take precedence, because its predefined segment is earlier in the path.

**Comment by jameshfisher** [comment] 2022-01-30 12:25
Okay, this seems to resolve some ambiguities by creating a sensible tree structure:

https://github.com/vercel/next.js/blob/136b75439612bf6f2f0cd3fd0d8226fdaa8c0f95/packages/next/shared/lib/router/utils/sorted-routes.ts#L198

However, it's not described in the docs. And surprisingly, the routing tree is then thrown away, rather than being traversed when a request comes in.

**Closed** 2022-02-02 02:57 UTC
Labels: kind: bug, area: Routing
