### ISSUE TITLE
Server action called from client component is invoked but return data is always undefined (even though network response has data in it)

### ISSUE THREAD

**Issue by RahulBirCodes** [vercel/next.js#69022] opened 2024-08-17 23:17 UTC
### Link to the code that reproduces this issue

https://github.com/RahulBirCodes/server-action-bug

### To Reproduce

1. Start the application with yarn run dev
2. Try navigating to demo.localhost:3000/test

### Current vs. Expected behavior

Current behavior:
The text on the page always says 'Data from server is undefined' and you get a small issue in the browser that says that you are accessing an undefined object.

Expected:
Text on the page should say Data from server is test' and there should be no errors that you are accessing an undefined object.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020
  Available memory (MB): 32768
  Available CPU cores: 12
Binaries:
  Node: 22.2.0
  npm: 10.7.0
  Yarn: 1.22.21
  pnpm: 9.5.0
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

### Additional context

I am building a multi tenant site and this error only occurs when I add the middleware for multi tenancy. If I build a demo app without that middleware, everything works. Additionally, if I go into dev tools and look into network, I can see the data Im expecting from the server is there in the response, but no matter what I do I can't access it from the client.

**Comment by caioalmeida12** [comment] 2024-08-19 14:20
Hello, Rahul. 

Just tried to run your code and, apparently, the error does not occur on my machine (i dont know why)

![image](https://github.com/user-attachments/assets/72f98811-f165-4c1d-b140-4b3b737235ac)

**Comment by RahulBirCodes** [comment] 2024-08-19 17:54
@caioalmeida12 That's because you ran localhost:3000/test without adding the subdomain in front. As per my reproduction steps you need to navigate to demo.localhost:3000/test. I will update the repo to return 404s without subdomain

**Comment by dfltr** [comment] 2024-08-19 20:41
Check your network panel for a CORS error. Having a request/response mysteriously zero itself out is a smell that usually points to a CORS violation, as the browser will ditch the body of the request without any other indication that something went wrong.

**Comment by RahulBirCodes** [comment] 2024-08-19 23:57
@dfltr Route handlers work though and don't see anything

**Comment by RahulBirCodes** [comment] 2024-08-21 08:05
Update on this: regular server actions used in <form> elements return undefined as well even though the action is being performed. This is a pretty critical bug hope it can be resolved or touched upon

**Comment by ztanner** [comment] 2024-08-21 14:17
It looks like your middleware is rewriting the IPC call that power server actions. The `fetch` call associated with your server action is only bundled with the `/[domain]/test` route and it's being rewritten to `localhost:3000/[domain]/test`.

I'm not 100% following your middleware logic but you can avoid rewriting the action handlers by ensuring they aren't called for requests that contain the `next-action` header.

**Comment by RahulBirCodes** [comment] 2024-08-21 20:55
Ahhh that makes sense, thank you @ztanner for the quick response!

What Im trying to do in the middleware is take any subdomain request like test.localhost:3000/ and in the middleware add the domain as a slug that I can use to support multi tenancy. Majority of this middleware code is from the Vercel Platforms Starter Kit. I think this is something that needs to be addressed in the starter kit then since server actions come undefined there as well.

Ill try that out and get back.

**Comment by RahulBirCodes** [comment] 2024-08-22 13:46
Hey @ztanner, can't get redirects within server actions to work even though Im excluding it on the middleware. If I put an absolute url in the redirect as well it'll show a 404 and then upon refresh go to the right place :/

**Comment by ztanner** [comment] 2024-08-22 14:11
Hey @RahulBirCodes -- I took a closer look and realized the rewrite actually isn't the inherent problem, so you can ignore that suggestion. I think what's happening is that the middleware is causing the content-type header that we would normally set on the action to get lost on the response. Could you try something like this in your middleware and let me know if it works for you?

```
  if (req.headers.get('next-action')) {
    newHeaders.set('content-type', 'text/x-component')
  }
  ```

**Comment by RahulBirCodes** [comment] 2024-08-22 14:48
Hey @ztanner, just tested and got the following error on the client:  ⨯ SyntaxError: No number after minus sign in JSON at position 1 (line 1 column 2)
    at JSON.parse (<anonymous>)
digest: "837905482"

**Comment by ztanner** [comment] 2024-08-22 14:56
> Hey @ztanner, just tested and got the following error on the client: ⨯ SyntaxError: No number after minus sign in JSON at position 1 (line 1 column 2) at JSON.parse () digest: "837905482"

Does that happen in your repro, or do you have different code that's causing that behavior? If so could you update your repro?

**Comment by RahulBirCodes** [comment] 2024-08-22 15:16
@ztanner just pushed to my repro. It's throwing the json error as well now

**Comment by ztanner** [comment] 2024-08-23 14:11
> @ztanner just pushed to my repro. It's throwing the json error as well now. i updated it to mimic my actual project a little bit so when you're testing go to demo.localhost:3000/login instead.

Thanks for the repro. I've traced it to when you attempt to pass new headers into `NextResponse.rewrite`. If you don't override the rewrite headers it appears to function properly. I'll dig in on the Next.js side to see why that's happening.

**Comment by RahulBirCodes** [comment] 2024-08-23 16:05
@ztanner Works on my project, thanks a lot!

**Comment by ztanner** [comment] 2024-08-23 20:51
Hey @RahulBirCodes upon digging further into it, I think this is expected behavior.

In your reproduction you're taking request headers, adding a new property, and then sending to the client as response headers. However those request headers aren't meant to be sent to the client, as they overwrite things like content-type etc. 

If you're wanting to add the `x-url` response header, you can do so on a new Headers object, rather than cloning the headers from the request. I confirmed that worked as expected, so I'm going to close this out!

**Closed by ztanner** 2024-08-23 20:51 UTC
Labels: bug
