### ISSUE TITLE
HMR doesn't work when access page with same name but different case

### ISSUE THREAD

**Issue by taneba** [vercel/next.js#8724] opened 2019-09-13 01:46 UTC
# Bug report

## Describe the bug

HMR doesn't work when access page with same name but different case
If you access the page with same name but different case from your actual folder name, HMR doesn't work.

## To Reproduce
I created the minimum repo for reproduction.
https://github.com/taneba/repro-next

1. Go to `localhost:3000/signin`.
2. Edit the `pages/SignIn/index.js`.
3. You can see HMR does not work

## Expected behavior

HMR works fine

## System information

- OS: macOS
- Browser chrome
- Version of Next.js: 9.0.5

**Comment by VictorAssis** [comment] 2020-01-05 06:06
The same happens to me with Next.js 9.1.7. Interestingly, this problem does not happen with non-page components.

**Comment by jcruzdzk** [comment] 2020-01-07 02:41
I added this, do you have any idea?

https://spectrum.chat/next-js/general/i-added-src-folder-and-now-do-not-working-hmr~5da2be9e-998e-41da-862f-02f375eaea09

Regards,

**Comment by ijjk** [comment] 2020-09-10 20:33
Hi, this is resolved in the latest version of Next.js as case-sensitivity has been added when requesting pages

x-ref: https://github.com/vercel/next.js/pull/15444
x-ref: https://github.com/vercel/next.js/pull/8848

**Closed by ijjk** 2020-09-10 20:33 UTC
Labels: kind: bug, type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-29 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
