### ISSUE TITLE
ISR with revalidate does not work when notFound was true on the first build

### ISSUE THREAD

**Issue by la55u** [vercel/next.js#25470] opened 2021-05-25 20:36 UTC
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

Firefox Developer Edition

### What operating system are you using?

Fedora 33

### How are you deploying your application?

on localhost, `next build && next start`

### Describe the Bug

When the initial build in `getStaticProps` returns `notFound: true`, the page will never be rebuilt even if later the notFound condition changes to false. See the reproduction. Console log doesn't show up so I assume the `getStaticProps` function never runs again.

Several people experiencing the same problem in another issue but that one is for dynamic routes specifically: https://github.com/vercel/next.js/issues/21453 
The problem exists on normal pages as well.

### Expected Behavior

If `notFound` becomes false than the page should be rebuilt according to revalidate even if it was true before.

### To Reproduce

1. create a random API endpoint somewhere and return 404 from there 
2. `npx create-next-app isr-test`
3. replace the contents of `pages/index.js` with the following (also set the correct API url)
```js
export default function Home({ data }) {
  return (
      <main>
        <pre>{JSON.stringify(data, null, 4)}</pre>
      </main>
  );
}

export async function getStaticProps() {
  const res = await fetch("http://localhost:1338/test");
  let data = null;
  if (res.ok) {
    data = await res.json();
  }
  console.log("data:", data);
  return {
    props: { data },
    notFound: !data,
    revalidate: 2,
  };
}
```
4. `npm run build && npm run start`
5. visit `http://localhost:3000`, the default 404 page is being rendered as expected since the mock API doesn't work
6. now modify the same API route to return some actual json data
7. refresh your browser a couple times and the page still shows the default 404 error despite `revalidate` should have happened.

**Comment by ijjk** [comment] 2021-09-19 05:43
Hi, this should be fixed in the latest version of Next.js `v11.1.2` please update and give it a try!

**Closed by ijjk** 2021-09-19 05:43 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
