### ISSUE TITLE
NextResponse clearCookie from _middleware page work not incorrect on Production 🎉

### ISSUE THREAD

**Issue by igdev116** [vercel/next.js#34261] opened 2022-02-12 09:30 UTC
### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

16.13.2

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

I want to clear multiple cookies using the built in NextResponse.clearCookie method but in production it is linked together instead of calling 'set-cookie' twice. On local dev it works perfectly 🤔
```js
let response = NextResponse.next();

response.cookie('access_token, '', {
      ...cookieOptions,
      expires: new Date(0),
});
response.cookie('refresh_token', '', {
      ...cookieOptions,
      expires: new Date(0),
});
// Also tried
response.clearCookie('access_token');
response.clearCookie('refresh_token');

return response;
```
![image](https://user-images.githubusercontent.com/70432453/153705320-555539cc-afa3-4eb2-a71e-321107f56ca3.png)

### Expected Behavior

I want it to work like on local dev
![image](https://user-images.githubusercontent.com/70432453/153705354-ea47b909-d002-4a61-aec2-8686fa4fc579.png)

### To Reproduce

My code
![image](https://user-images.githubusercontent.com/70432453/153705748-b008a5ce-35e2-4672-81ef-39a08d8c8dbf.png)

**Comment by balazsorban44** [comment] 2022-02-12 11:17
Duplicate of #34254

**Closed by balazsorban44** 2022-02-12 11:17 UTC
Labels: template: bug
