### ISSUE TITLE
Dynamic Imports require SSR: true flag for Next Export

### ISSUE THREAD

**Issue by conanbatt** [vercel/next.js#18556] opened 2020-10-30 18:22 UTC
# Bug report
The ssr flag in dynamic imports does not match the developer usage of the framework. 

## Describe the bug
This might be a documentation issue, implementational issue or simply API signature, but it is unexpected for next export websites to require ssr: true for dynamic imports. If set to false, it works in dev but not in export.

## To Reproduce
Repo: https://github.com/conanbatt/nextjs-dynamic-imports-export

## Expected behavior
As a developer I expect a dynamic import with ```ssr: false`` to work in next export, as it is a non-ssr deployment of the app.

## System information
- Version of Next.js: [e.g. 9.5.3]]

## Additional context

Looking at the tests for next export, it seems to use SSR to render the pages, but this causes a mismatch of understanding between how the app is deployed and how it is generated.

## Solutions?

1- Make ssr flag work as the intended behavior (albeit it could break API?)
2- Improve documentation on dynamic import AND/OR next export to describe this issue
3- Add additional flag to dynamic imports to handle this case.

**Comment by timneutkens** [comment] 2020-11-02 09:58
Marked as bug (did not verify it's actually a bug though) but what you're describing sound unexpected.

**Comment by eavae** [comment] 2020-12-22 14:20
I met the same issue. The ssr option only works in development mode.

**Comment by cenguidanos** [comment] 2021-06-17 19:52
I can't reproduce this issue. It works fine with the two options of ssr [ **true** | **false** ] on **dev** mode, **build** and **export** .

**Comment by conanbatt** [comment] 2021-06-17 22:36
Even with the then next.js version? I haven't repro'd this one in a while.

**Comment by cenguidanos** [comment] 2021-06-18 09:21
Hi @conanbatt,

It's working on next **v9.5.3**, **v10.0.0** and **v11.0.0** in three modes [ **dev** | **build** | **export** ].

The issue, maybe, is related with a incorrect import path in **pages/index.js** file:

##### Before

```tsx
const DynamicComponent = dynamic(
  () => import("../../next.js-dynamic-import-in-export/components/test"),
  { ssr: false, loading: () => <p>Loading...</p> }
);
```

##### After

```tsx
const DynamicComponent = dynamic(
  () => import("../../nextjs-dynamic-imports-export/components/test"), // <-- here
  { ssr: false, loading: () => <p>Loading...</p> }
);
```

**Comment by timneutkens** [comment] 2021-11-18 08:49
I'm going to close this issue as it was reported as not being a problem anymore, feel free to re-open if you're still running into it 👍

**Closed by timneutkens** 2021-11-18 08:49 UTC
Labels: kind: bug, good first issue, type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-27 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
