### ISSUE TITLE
[NEXT-601] search params object is empty in production with next 13 app dir

### ISSUE THREAD

**Issue by raymclee** [vercel/next.js#43077] opened 2022-11-18 13:37 UTC
### Verify canary release

* [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
Platform: linux
Arch: x64
Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
Binaries:
Node: 18.8.0
npm: 8.19.2se
Yarn: N/A
pnpm: N/A
Relevant packages:
next: 13.0.4
eslint-config-next: 13.0.4
react: 18.2.0
react-dom: 18.2.0

### What browser are you using? (if relevant)

*No response*

### How are you deploying your application? (if relevant)

*No response*

### Describe the Bug

search params object is empty in production with next 13 app dir
Its ok if its a dynamic route

### Expected Behavior

search params object is not empty in production

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

[https://stackblitz.com/edit/nextjs-ncgro9?file=app/page.tsx](https://stackblitz.com/edit/nextjs-ncgro9?file=app/page.tsx)

### To Reproduce

npm run build && npm run start
go to /?page=1
go to /products/1?page=1

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-601](https://linear.app/vercel/issue/NEXT-601/search-params-object-is-empty-in-production-with-next-13-app-dir)</sub>

**Comment by Deploydon** [comment] 2022-11-26 04:56
Strange, 

Your link does seem to have valid search params when running.

However my app on a newer canary version still seems to have the same issue of empty searchParams when running on Vercel.

**Comment by iammatthias** [comment] 2022-11-27 17:34
Ran into this on Next 13.0.5 last night. Works fine locally, but returns `undefined` once it is published on Vercel.

**Comment by neoliao** [comment] 2022-12-06 04:12
Same  problem, but probably fixed in version 1.0.6

**Comment by hyperbolictonic** [comment] 2022-12-14 14:30
Can confirm the same issue. Works fine if I "run dev" but returns empty after "run build" then "run start"

**Comment by baronha** [comment] 2022-12-20 17:46
same +1

**Comment by llorenspujol** [comment] 2022-12-21 22:21
Same, it does not work when deployed on Vercel...

**Comment by abakan26** [comment] 2022-12-22 04:18
Search params object is empty after running commands next build, next start

**Comment by DrMisQ** [comment] 2022-12-24 07:09
any solution for this problem !!

**Comment by yantakus** [comment] 2022-12-24 12:36
The same for me. Latest next (13.1.1 ATM), `app/posts/[id]/page.tsx`, url is http://localhost:3000/posts/1, `searchParams` is an empty object.

**Comment by Waqas-Abbasi** [comment] 2022-12-26 17:04
With nextjs version 13.0.6 searchParams seem to work as expected. The versions after seem to have this bug?

**Comment by LIMPIX31** [comment] 2022-12-30 09:52
Same thing. Any solution other than rolling back the version.

**Comment by yondifon** [comment] 2022-12-30 19:01
+1.

**Comment by Hanskrogh** [comment] 2023-01-02 16:41
+1

**Comment by MahmoudAlawdh** [comment] 2023-01-03 09:45
+1

**Comment by abakan26** [comment] 2023-01-10 07:44
+1

**Comment by simmondsty** [comment] 2023-01-10 08:49
A similar issue is occurring with layout files, when calling an async function, the call is made at build time and then serves the same response on each call. Do not have this issue when dealing with dev.

**Comment by Jose-DallAsta-008** [comment] 2023-01-10 18:29
can confirm the error is happening, can also confirm that the version 13.0.6 is also having this issue in the reproduction link (opposing Waqas-Abbasi comment)
+1

**Comment by hyperbolictonic** [comment] 2023-01-12 09:25
@ijjk is there any update on a fix for this?

**Comment by simmondsty** [comment] 2023-01-12 09:28
@ijjk This is a major issue, breaking essential functionality so I would imagine so.

**Comment by alexis78i** [comment] 2023-01-13 20:48
I noticed that on some pages everything works for me, but on others (mostly where 4-5 requests to the API) it does not work.

**Comment by leerob** [comment] 2023-01-14 00:32
Thanks for flagging this folks, we will investigate 🙏

**Comment by abakan26** [comment] 2023-01-15 05:30
Will the issue be resolved in the next update?

**Comment by barel31** [comment] 2023-01-15 18:16
version 13.1.2 and the bug is still here

**Comment by Trugamr** [comment] 2023-01-16 09:30
You may have to force page to be dynamic to get query params.

This can be done by exporting variable named `dynamic` and it's value as `force-dynamic`

```ts
export const dynamic='force-dynamic';

export default function Home(props: unknown) {
  return (
    <main>
      <pre>
        {JSON.stringify(props, null, 2)}
      </pre>
    </main>
  )
}
```
_Originally posted by @hubertlepicki in https://github.com/vercel/next.js/discussions/44005#discussioncomment-4497881_

**Comment by simmondsty** [comment] 2023-01-17 12:09
Why would you ever want non dynamic props? Isn't that the point of passing them

**Comment by njarraud** [comment] 2023-01-19 05:05
I noticed that at build time, `searchParams` and `params` become a similar object when `generateStaticParams` is used on the page. Is that expected?

I guess it is also expected that `searchParams` does not work when `generateStaticParams` is used as server is not called.

**Comment by RohanDas28** [comment] 2023-01-25 20:17
Having this same issue in 13.1.1.  Waiting for the next update for a fix.

**Comment by LIMPIX31** [comment] 2023-01-28 10:12
I'm surprised this is still open.

**Comment by crushwan** [comment] 2023-01-30 03:08
Got any solution somewhere ?

**Comment by crushwan** [comment] 2023-01-30 03:22
Got any solution somewhere ?

**Comment by crushwan** [comment] 2023-01-30 08:34
> You may have to force page to be dynamic to get query params.
> 
> This can be done by exporting variable named `dynamic` and it's value as `force-dynamic`
> 
> ```ts
> export const dynamic='force-dynamic';
> 
> export default function Home(props: unknown) {
>   return (
>     <main>
>       <pre>
>         {JSON.stringify(props, null, 2)}
>       </pre>
>     </main>
>   )
> }
> ```
> 
> _Originally posted by @hubertlepicki in [#44005 (comment)](https://github.com/vercel/next.js/discussions/44005#discussioncomment-4497881)_

Thanks you, it's working by adding export const dynamic='force-dynamic';

**Comment by IonelLupu** [comment] 2023-02-06 12:07
`export const dynamic='force-dynamic';` doesn't work for me. I use client components.

**Comment by Trugamr** [comment] 2023-02-06 13:43
> `export const dynamic='force-dynamic';` doesn't work for me. I use client components.

On client pages you should be able to get search params  using
```ts
const params = useSearchParams();
```

I have updated start command to build and start instead of running dev command just to make sure it works after being built.
https://stackblitz.com/edit/nextjs-bu8mha?file=app/page.tsx

If you are still running into problems, a reproduction link would be helpful.

**Comment by IonelLupu** [comment] 2023-02-06 14:02
@Trugamr  I used it before but using it introduces this issue: https://github.com/vercel/next.js/issues/45610

**Comment by omer-os** [comment] 2023-02-09 18:43
> ### What browser are you using? (if relevant)

solved by adding 

`export const dynamic='force-dynamic';`

to the top of the component. i think its ridiculous that this bug still exist in nextjs13 i wasted 8 hours trying to solve this error. they have to solve it as soon as possible!

**Comment by turkkan94** [comment] 2023-03-01 10:20
> ```ts
> export const dynamic='force-dynamic';
> ```

I have the same issue. And this solution is working in server components....

thanks...

**Comment by dbbk** [comment] 2023-03-04 17:08
> Why would you ever want non dynamic props? Isn't that the point of passing them

Pagination, for one example? If you have a URL with `?page=2` all of a sudden this means it's not cacheable? Doesn't make sense to me why query params must force dynamic rendering.

**Comment by mmiszy** [comment] 2023-03-04 17:57
The ability to specify static searchParams along with params would be great.

**Comment by simmondsty** [comment] 2023-03-06 09:04
> > > Why would you ever want non dynamic props? Isn't that the point of passing them
> > 
> > 
> > Pagination, for one example? If you have a URL with `?page=2` all of a sudden this means it's not cacheable? Doesn't make sense to me why query params must force dynamic rendering.
> 
> Exactly this. Our users share their searches with each other frequently, having cached versions of those pages takes a load off the server.

I don't think either of you understand what the issue is here, searchParams are empty if you do not force-dynamic, so your page param will never reach your route. Of course for data loading you don't always want it to be dynamic...

**Comment by iamkibeh** [comment] 2023-03-06 17:21
When will they solve this! Should be fixed asap

**Comment by parixscm** [comment] 2023-03-07 04:16
Also having same issue.. !

**Closed** 2023-03-16 20:46 UTC
Labels: kind: bug, area: Routing, area: app, linear

**Comment by IonelLupu** [comment] 2023-03-20 13:40
it still doesn't work on canary for you @Annukul?

**Comment by Annukul** [comment] 2023-03-20 13:44
@IonelLupu Saw that is was just closed 3 days ago. I have upgraded my nextjs version from v13.1.6 to v13.2.4. Let's hope it works

**Comment by IonelLupu** [comment] 2023-03-20 13:47
@Annukul try canary. Not 13.2.4. You will see 13.2.4 was released a week ago and this issue was fixed 3 days ago. Which means the fix is not yet officially released.

**Comment by Annukul** [comment] 2023-03-20 14:26
@IonelLupu It's not working in v13.2.4. How can I use canary?

**Comment by MarkWittens** [comment] 2023-03-30 10:07
The latest canary version (v13.2.5-canary.21) works for the most part, but in dev mode (npm run dev) I get an error message on pages using the searchParams:

Dynamic server usage: searchParams.p

After refreshing the page it works fine and production everything works fine as well.

**Comment by michaelcummings12** [comment] 2023-04-06 00:42
> Even with the latest canary, and force-dynamic, still having issues with this.
> 
> ```
> const searchParams = useSearchParams();
> const formattedQueryParams = `?${searchParams.toString()}`;
> ```
> 
> formattedQueryParams is empty

`useSearchParams` only works in client components. For server components,  use can use the optional `searchParams` page prop.

[](https://beta.nextjs.org/docs/api-reference/file-conventions/page#searchparams-optional)

```
export default function Page({
  params,
  searchParams,
}: {
  params: { slug: string };
  searchParams: { [key: string]: string | string[] | undefined };
}) {
  const formattedQueryParams = `?${searchParams.toString()}`;
  return <p>{formattedQueryParams}</p>;
}
```

**Comment by yamsellem** [comment] 2023-04-14 12:03
@Trugamr [solution](https://github.com/vercel/next.js/issues/43077#issuecomment-1383742153) works fine with next 13.2.x but do not work with 13.3.x. Anyone has experienced this too?

**Comment by mbuffa** [comment] 2023-04-16 21:54
Hello there.

I'm not sure how this is related, but I'm encountering a similar issue, with:
* NextJS 13.3.0
* No app or src dir
* JS setup
* Dev (no production env yet)
* **On the server-side with an Edge API endpoint**
* Using Fetch API on client-side to do the call (`await fetch('/api/dropbox/authorize?auth_code=' + code);`)

Accessing `req.query` works with a NodeJS API endpoint, but it seemed easier to handle cookies, so I switched.

Here's the relevant NextRequest `nextUrl` value:
```
{
  cookies: REDACTED,
  geo: {},
  ip: undefined,
  nextUrl: {
  href: 'http://localhost:3000/api/dropbox/authorize?auth_code=REDACTED',
  origin: 'http://localhost:3000',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'localhost:3000',
  hostname: 'localhost',
  port: '3000',
  pathname: '/api/dropbox/authorize',
  search: '?auth_code=REDACTED',
  searchParams: URLSearchParams {  },
  hash: ''
}
```

If I `toString()` the searchParams object, I get the equivalent of the `search` field (without question mark).

**Comment by Beingbook** [comment] 2023-04-18 10:36
In development, RSC searchParams works without any additional configuration but production build searchParams not work in same conditions.

Only works when I set:
```
export const dynamic = "force-dynamic";
```

Is this intended?

**Comment by davecarlson** [comment] 2023-04-18 10:41
Apparently so.

Personally, I'm not a have of having to use to different apis to get the data and having to figure out which to use in which content ( server / client ). 

It all seems rather, messy

**Comment by DannyPark1** [comment] 2023-05-11 06:04
is this issue solved? at the latest version?

**Comment by MarkWittens** [comment] 2023-05-11 06:14
> In development, RSC searchParams works without any additional configuration but production build searchParams not work in same conditions.
> 
> Only works when I set:
> 
> ```
> export const dynamic = "force-dynamic";
> ```
> 
> Is this intended? I don't so as documentation explains...

I hope not, this makes every page dynamic (i.e. partially uncachable) that **might** have a filter or pager in the query parameters for example.

**Comment by timneutkens** [comment] 2023-05-11 09:16
- `useSearchParams` works in both static / dynamic rendering cases. Keep in mind to wrap a Suspense boundary around the point where you're using it. Docs: https://nextjs.org/docs/app/api-reference/functions/use-search-params#behavior
- When reading `searchParams` on `page.js` (or `.ts`) it will opt-out of static, because searchParams are not know at build time.

If you're running into an issue please open a new one with a reproduction, happy to have a look!
