### ISSUE TITLE
iron-session-example.vercel.app is broken with 5xx errors

### ISSUE THREAD

**Issue by jameshfisher** [vercel/next.js#31959] opened 2021-11-30 11:59 UTC
### What version of Next.js are you using?

https://iron-session-example.vercel.app/

### What version of Node.js are you using?

https://iron-session-example.vercel.app/

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

https://iron-session-example.vercel.app/

### Describe the Bug

"Login" link/button is missing

And error in JS console:

```
_app-b9ae86318186841f.js:1 GET https://iron-session-example.vercel.app/api/user 500
_app-b9ae86318186841f.js:1 SyntaxError: Unexpected token < in JSON at position 0
```

### Expected Behavior

Some way to log in

### To Reproduce

1. Visit https://iron-session-example.vercel.app/
2. Look for "login"; it's missing
3. Open JS console

**Comment by jameshfisher** [comment] 2021-11-30 12:06
Deploying it myself seems to work fine, so it's an issue with the specific instance at https://iron-session-example.vercel.app/

**Comment by vvo** [comment] 2021-11-30 18:28
Hey there, this is now fixed. The issue was the secure flag which now needs to be passed as true (https) or false (HTTP). There's no way to detect 100% of the time if iron-session is used for an HTTP or HTTPs website.

**Closed** 2021-11-30 18:28 UTC
Labels: area: examples, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
