### ISSUE TITLE
[NEXT-1165] [App Router]: Group routes with parallel routes as a page slot, nested route will render NEXT_NOT_FOUND in server side.

### ISSUE THREAD

**Issue by Innei** [vercel/next.js#49569] opened 2023-05-10 05:17 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112
    Binaries:
      Node: 18.15.0
      npm: 8.17.0
      Yarn: 1.22.19
      pnpm: 8.1.0
    Relevant packages:
      next: 13.4.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/Innei/nextjs-group-routes-reproduction

### To Reproduce

1. Start dev
2. Go to home page `/`
3. Click posts, nav to `/posts`
4. Refresh page, got `NEXT_NOT_FOUND`

https://github.com/vercel/next.js/assets/41265413/d1b395f0-01f9-4e84-a045-ce00ef34b974

### Describe the Bug

Render nested route in the server will be got `NEXT_NOT_FOUND`, but it works fine on the client side.

This error will happen in this file structure.

```
├── (root)
│   ├── (site)
│   │   ├── @footer
│   │   ├── @head
│   │   ├── layout.tsx
│   │   ├── page.tsx
│   │   └── posts
│   ├── @headxx
│   │   └── page.tsx
│   ├── error.tsx
│   ├── layout.tsx
│   ├── page.tsx
│   └── providers.tsx
├── favicon.ico
├── globals.css
├── layout.tsx
└── page.tsx
```

### Expected Behavior

No error.

<sub>[NEXT-1165](https://linear.app/vercel/issue/NEXT-1165/[app-router]-group-routes-with-parallel-routes-as-a-page-slot-nested)</sub>

**Comment by mkarajohn** [comment] 2023-05-11 02:24
I am experiencing this error as well. 

I am using a slot for a modal which uses route interception (pretty much like the example in https://github.com/vercel-labs/nextgram) 

I tried to move the slot inside a `(slots)` group and route interception and the slot itself stops working, with the error

```
Unhandled Runtime Error
Error: NEXT_NOT_FOUND

Call Stack
Next.js
notFound
node_modules/next/dist/client/components/not-found.js (26:18)
NoopParallelRouteDefault
node_modules/next/dist/client/components/parallel-route-default.js (13:26)
type
node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js (1447:17)
attemptResolveElement
node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js (1759:20)
resolveModelToJSON
node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js (1249:13)
stringify
<anonymous>
stringify
node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js (181:13)
processModelChunk
node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js (2062:25)
retryTask
node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js (2109:6)
performWork
node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js (1544:13)
listOnTimeout
node:internal/timers (564:17)
process.processTimers
node:internal/timers (507:7)
```

**Comment by bottercode** [comment] 2023-06-07 14:29
do y'all came to a solution to this ?

**Comment by jiwooIncludeJeong** [comment] 2023-06-08 10:14
I encountered same issue. 
And i resolve this issue by using [intercepting-routes](https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes#modals).

Following is my example:
<img width="334" alt="스크린샷 2023-06-08 오후 7 07 53" src="https://github.com/vercel/next.js/assets/63336958/73f42bee-3628-44dd-9a6f-3ea9c6ada93c">

- if you navigate by using soft navigation, `@modals/half-self/(.)find-expert` will intercept your `localhost:3000/half-self/find-expert` url.
- if you navigate by using hard navigation, `/half-self/find-expert` will intercept your `localhost:3000/half-self/find-expert` url.

I hope this comment will help you 😄

**Comment by ztanner** [comment] 2023-06-27 17:39
Based on the [unmatched routes](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#unmatched-routes) section of the parallel routes docs, it looks like what's happening is expected -- since your slots (`@footer, @head, @headxx`) don't contain a `posts` page, when navigating to it from the root, it will use the previously matched slots. On a reload, it will attempt to use the `default.js` file in your slot (if you have one). Otherwise it will 404. 

So to fix [your repro](https://github.com/Innei/nextjs-group-routes-reproduction), you could either add `default.tsx` to each of your slots, or create a `posts/page.tsx` for each slot

**Comment by dennis3124** [comment] 2023-06-30 16:20
@jiwooIncludeJeong  hey jiwool, I'm trying to implement something similar. In my layout.js i have
`
.....
{children}
{modal}
......
`

When my parallel page is rendered, children is no longer displayed. I am trying to implement a Modal component which should render the modal above the children component. Any ideas how to solve this?

**Comment by phelanma** [comment] 2023-07-14 02:01
Possible workaround is have the `default.tsx` and `page.tsx` in the `@slot` directory 
And then import `page.tsx` into `default.tsx`. 


```
// default.tsx

import AppHeader from "./page";
export default function AppHeaderDefault() {
  return <AppHeader />;
}
```  

*Advance use cases are not tested but in the simple case for hard-navigation rendering seems to work

**Comment by kachkaev** [comment] 2023-07-25 18:17
I have just reported a similar bug, which manifests itself when using route groups, parallel routes and route interception. Sharing here for context: https://github.com/vercel/next.js/issues/53170.

**Comment by ztanner** [comment] 2023-12-19 20:10
Going to close this out as the original reproduction appears to be behaving correctly, but has several errors in how the application is structured:

- `/app/(root)/page.tsx` and `/app/(root)/(site)/page.tsx` refer to the same path (`/`) which is not supported. We now properly will throw an error when conflicting pages are detected.
- All of the slots defined in the app are missing a `default` segment. This means that if you load `/posts` but there's no specific `page` component for that slot (ie, `@headxx/posts/page`, `@footer/posts/page`), it will fall back to the nearest default. Since no default is defined, it 404s. This is documented [here](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#defaultjs).

If you think there's still a bug with this specific scenario, please open a new issue with a reproduction and we'll take a look!

**Closed by ztanner** 2023-12-19 20:10 UTC
Labels: area: documentation, template: bug, area: app, linear: next
