### ISSUE TITLE
New aliases feature doesn't work with SVG import

### ISSUE THREAD

**Issue by in-in** [vercel/next.js#13584] opened 2020-05-30 15:29 UTC
# Bug report

## Describe the bug

[New aliases feature](https://nextjs.org/blog/next-9-4#absolute-imports-and-aliases) doesn't work with SVG import
Error message: `Cannot find module '@icons/close.svg'`

## To Reproduce
1. Go to https://github.com/in-in/svg_alias
2. Run `npm run dev`

## Expected behavior

The path must be resolved in the same way as without an alias.
`import Close from '@icons/close.svg';`
https://github.com/in-in/svg_alias/blob/master/components/date.js#L3

## Screenshots

![201511590851868](https://user-images.githubusercontent.com/8797432/83332103-e98d3000-a2a1-11ea-9992-08c92e1063bd.png)

## System information

- OS: Linux Mint
- Browser: chrome
- Version of Next.js: 9.4.4
- Version of Node.js: 12.15.0

## Additional context

For handling inline SVG files, I use [babel-plugin-inline-react-svg](https://github.com/airbnb/babel-plugin-inline-react-svg)

**Comment by timneutkens** [comment] 2020-05-30 18:55
You're using this plugin: https://github.com/in-in/svg_alias/blob/master/.babelrc#L3
Which runs inside of Babel. The new aliases feature runs in the webpack layer and that plugin is not resolving files using webpack. This is not something we can solve in Next.js given you've configured a custom babel plugin.

**Closed by timneutkens** 2020-05-30 18:55 UTC

**Comment by manueltruepill** [comment] 2021-09-06 22:21
> You're using this plugin: https://github.com/in-in/svg_alias/blob/master/.babelrc#L3
> Which runs inside of Babel. The new aliases feature runs in the webpack layer and that plugin is not resolving files using webpack. This is not something we can solve in Next.js given you've configured a custom babel plugin.

Based on this answer I switched from `babel-plugin-inline-react-svg` to `@svgr/webpack` and path aliases for SVG files is working now.

See this [guide](https://dev.to/dolearning/importing-svgs-to-next-js-nna)

**Comment by balazsorban44** [comment] 2022-01-27 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
