### ISSUE TITLE
No response randomly when DEV on Node v14 & v15

### ISSUE THREAD

**Issue by Cow258** [vercel/next.js#18811] opened 2020-11-04 20:27 UTC
# Bug report

## Describe the bug
Should be backend issue.
Only happen when using Node.js v14/v15.
Only happen when the build take time that about half second or more.
Only happen when development mode.
No issue when using other version of Node.js.
No issue when production and static export.

No response when routing to some page that not yet built by hot-reload server.
The `.js` file will keep waiting response.
But Next.js console shown
```
event - build page: /some/issue/page
wait  - compiling...
event - compiled successfully
```
Then when you type the `.js` url of the issued page into browser **on new tab**,
```
127.0.0.1:3000/_next/static/chunks/pages/some/issue/page.js
```
It still no response and waiting response.
After waiting about 1min, 
Next.js console shown again
```
event - build page: /some/issue/page
wait  - compiling...
event - compiled successfully
```
Then the url will response normally.
But when you back to the app,
The page still unable to reach without refresh.

So I need keep refresh many times to test some simple things.
Or downgrade to Node.js v12.

## To Reproduce

I'm still making a repo that can 100% reproduce this issue,
But it is hard,
Coz this issue happen so randomly,
If the bundle size too small, it can't happen.

Any way,
Here are some screen record,
Hope helpful.

### No response 
When `.js` keeping no response and keep clicking the link to that page.
![1_not-work1](https://user-images.githubusercontent.com/14261588/98162473-5f19be00-1f1c-11eb-86b6-a199f43d740b.gif)

### Keep no response after refresh 
Some case, refresh is useless.
![2_not-work2](https://user-images.githubusercontent.com/14261588/98162778-d2233480-1f1c-11eb-8171-e924e3dae7f7.gif)

### Click another link to make it work
```
Links
> A: Some link no yet build since server boot up
> B: The link you want to got to
```
1. Click A link first
2. Click B link
3. When B link will work
4. But A link will still no work
(If you want A link work, refresh and click B link first)
![3_working](https://user-images.githubusercontent.com/14261588/98163339-abb1c900-1f1d-11eb-80eb-a3efd0981b66.gif)

## Expected behavior

The bundle `.js` file should response when built.

## System information

- OS: Any
- Browser: Any
- Version of Next.js: > 9.5.0
- Version of Node.js: v14 / v15

## Additional context

Remember!
All working when using Node.js v12.
All working when production and static export even if Node.js v14/v15.
Any thing and any code is working well.

I hope the above information is helpful.

Feel free to ask me for more information.

Thanks.

**Comment by robschwitzer** [comment] 2020-11-05 06:51
getting similar behaviour but only for a dynamic route with `getInitialProps`

**Comment by rever96** [comment] 2020-11-17 10:10
I have the same problem.
with node v10 all works fine, with node v14 no errors but requests doesn't get response.

**Comment by timneutkens** [comment] 2021-11-17 14:51
Closing as no reproduction was provided.

**Closed by timneutkens** 2021-11-17 14:51 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-27 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
