### ISSUE TITLE
ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization

### ISSUE THREAD

**Issue by CGamesPlay** [vercel/next.js#32360] opened 2021-12-10 08:47 UTC
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

14.18.1

### What browser are you using?

N/A

### What operating system are you using?

macOS, Alpine

### How are you deploying your application?

next start

### Describe the Bug

A module which imports an es module and throws an exception at the top level has the exception swallowed and a different (vastly less helpful) exception thrown instead. I am pretty confident that this is a webpack bug, but since next vendors webpack, I'm reporting here.

### Expected Behavior

When a module throws an exception during initialization, the exception should be passed to the nearest user exception handler, or crash the application. Instead, a different exception is being thrown due to webpack-generated code.

### To Reproduce

Create a file `lib/test.ts` like the following; require it from any page (I used an API page, may be relevant); request that page.

```javascript
import { z } from "zod";
throw new Error("error");
export default { z };
```

You will see the following error in the console, without any stack trace:

```
error - ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
```

Things to note:

1. "zod" could be replaced by any esmodule package. The root cause is that the code generated by webpack uses a dynamic `import` to import the code, causing to to be an async module.
2. Exporting `{ z }` is just so that the import doesn't get tree-shaken-away.

**Comment by davecarlson** [comment] 2021-12-13 19:11
i had the same in https://github.com/vercel/next.js/issues/28440

**Comment by jakubriedl** [comment] 2022-01-06 01:53
We are experiencing the same issue and it is very annoying because the error is can be caused by 3rd party package.

I've also tried to wrap `<Component />` in `_app` in ErrorBoundary and define custom `pages/_error` but neither of those helped.

**Comment by godmar** [comment] 2022-01-10 05:14
I'm seeing this, too. 

How can you find out which package is throwing the exception - is there a way to perhaps get a backtrace or enable debugging?

**Comment by CGamesPlay** [comment] 2022-01-10 13:33
You can start to investigate by setting Chrome to "block on all exceptions" (even caught) and the last caught exception before the uncaught exception will contain the information necessary to find out which script file was being imported.

**Comment by godmar** [comment] 2022-01-10 14:18
This happens server side during the initial SSR, not client side. Would Chrome still be useful in this case?

**Comment by stan-sack** [comment] 2022-01-15 22:27
I'm seeing this as well. I'm pretty sure its a bug that was released in 12.0.2 that blows up the first server side render:
```
$ npm run dev

> <my-project>@1.0.0 dev
> next

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - The `target` config is deprecated and will be removed in a future version.
See more info here https://nextjs.org/docs/messages/deprecated-target-config
warn  - Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
info  - automatically enabled Fast Refresh for 1 custom loader
info  - Using external babel configuration from /<project>/client/apps/website/babel.config.js
event - compiled successfully in 11.5s (978 modules)
wait  - compiling /404...
event - compiled successfully in 3.3s (981 modules)
ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
    at Module.default (webpack-internal:///./<my-file>.ts:5:42)
    at Function.getInitialProps (webpack-internal:///./pages/_document.js:55:58)
    at Object.loadGetInitialProps (/<project>/client/apps/website/node_modules/next/dist/shared/lib/utils.js:69:29)
    at renderDocument (/<project>/client/apps/website/node_modules/next/dist/server/render.js:634:48)
    at Object.renderToHTML (/<project>/client/apps/website/node_modules/next/dist/server/render.js:673:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async doRender (/<project>/client/apps/website/node_modules/next/dist/server/next-server.js:1389:38)
    at async /<project>/client/apps/website/node_modules/next/dist/server/next-server.js:1484:28
    at async /<project>/client/apps/website/node_modules/next/dist/server/response-cache.js:63:36
info  - automatically enabled Fast Refresh for 1 custom loader
```

Try rolling back to 12.0.1 - This fixed it for me.

**Comment by afonsomatos** [comment] 2022-01-22 19:27
I'm also getting this.

**Comment by monokaijs** [comment] 2022-01-23 18:29
I'm also facing this issue.

**Comment by jakubriedl** [comment] 2022-01-24 00:19
In our case the trigger for this error was an issue in internal npm packages that were compiled to commonjs but swc didn't for some reason define `exports`. So the packages were throwing `ReferenceError: exports is not defined` which led to an error that got masked by this one. For us the fix was to opt-out to babel with `@babel/plugin-transform-modules-commonjs`. With it, it works fine. Not sure what's wrong because swc should include this plugin but it helped.

**Comment by vlapo** [comment] 2022-01-24 11:32
We are experiencing similar issue after upgrade from 12.0.1 to 12.0.2.

**Comment by luixo** [comment] 2022-01-26 19:39
Seems like this problem is connected to `esmExternals` [experimental feature](https://github.com/vercel/next.js/discussions/27876), which is [enabled](https://github.com/vercel/next.js/blob/b5d4564cca27dac6b588f26fe21a2439ead89a46/packages/next/server/config-shared.ts#L251) by default.

I have this problem on 12.0.7 without any underlying error, just having ESM module imported in the project. Turning off experimental feature fixed the issue.
```js
// next.config.js
module.exports = {
  ...,
  experimental: {
    esmExternals: false
  }
}
```

**Comment by rozenmd** [comment] 2022-01-28 07:56
Just confirming @luixo's fix worked for me.

**Comment by humble-barnacle001** [comment] 2022-01-28 13:48
I am facing the same issue in v12.0.9 but in my case surprisingly, `next dev` works and also deploy on Vercel platform works but somehow the local build using `next build` fails

**Closed** 2022-02-01 19:27 UTC
Labels: kind: bug, area: Compiler
