### ISSUE TITLE
App Router breaks (pages won't show) when i18n next.js config is active

### ISSUE THREAD

**Issue by tr1s** [vercel/next.js#54717] opened 2023-08-29 13:23 UTC
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.7.0
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/discussions/54714

### To Reproduce

Add i18n config in next.js config.

```
i18n: {
  locales: ['en'],
  defaultLocale: 'en',
},
```

### Describe the Bug

App Router pages return 404 when i18n config is active.

[More info here in next.js discussions](https://github.com/vercel/next.js/discussions/54714).

### Expected Behavior

Pages should be visible when the i18n config is active. This will help with people trying to incrementally adopt and use both pages _and_ app router.

**Comment by balazsorban44** [comment] 2023-08-29 13:26
Duplicate of https://github.com/vercel/next.js/issues/53724

**Closed by balazsorban44** 2023-08-29 13:26 UTC
Labels: template: bug
