### ISSUE TITLE
`router.push` hangs and does not trigger hard reload if `router.prefetch` fails to load a file more than once

### ISSUE THREAD

**Issue by timswalling** [vercel/next.js#28038] opened 2021-08-12 16:27 UTC
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

14.x

### What browser are you using?

Chome - Version 92.0.4515.131 (Official Build) (x86_64)

### What operating system are you using?

macOS 10.15.7

### How are you deploying your application?

Vercel

### Describe the Bug

If `router.prefetch` fails to load a file twice subsequent `router.push` calls for the route do not attempt to load the file and do not resolve. No `routeChangeCompleted` or `routeChangeError` events fire, and a hard reload is not triggered.

### Expected Behavior

The `router.push` call will attempt to load the missing file. If the file still cannot be loaded a `routeChangeError` event will fire, the `router.push` call will resolve with a value of `false`, and a hard reload will be used to load the target route.

### To Reproduce

Example repo: https://github.com/timswalling/next-prefetch-bug

* Go to https://next-prefetch-bug.vercel.app/ in Chrome
* Using devtools, enable network request blocking on `next-prefetch-bug.vercel.app/_next/static/chunks/pages/page-2-*.js`
* Click on the `router.prefetch` button and verify that the `page-2` chunk fails to load
* Click on the `router.prefetch` button and verify that the `page-2` chunk fails to load again
* Click on `router.push` and verify that no further attempt is made to load the `page-2` chunk, and that the `router.push` call does not resolve

**Comment by hotsummmer** [comment] 2021-08-13 00:44
I think other people(including me) are experiencing it too😢 
https://github.com/vercel/next.js/issues/27783

**Comment by timswalling** [comment] 2021-08-13 09:50
I've tried upgrading to [`next@v11.1.1-canary.6`](https://next-prefetch-bug-1wca7dgn9-fotp.vercel.app/), but it doesn't fix this issue.

**Comment by zakariamofaddel** [comment] 2021-08-13 12:16
I'm having a similar issue too with catch all routes.
This is what my pages folder looks:
`pages
       index.js
       [...slug].js`

When navigating using the Link component from the index.js page to a [...slug].js page (e.g. /careers or /blog), everything works fine, BUT when navigating from a [...slug].js page (/contact) to another similar page (/blog) only the URL changes, the content of the page stays the same.
Note: Navigating from a [...slug].js page back to the root file (href="/") works.

**Comment by ijjk** [comment] 2021-09-18 14:50
Hi, this should be fixed in `v11.1.3-canary.24` of Next.js, please update and give it a try!

**Closed by ijjk** 2021-09-18 14:50 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
