### ISSUE TITLE
Next.js 9.5.2 breaks with Yarn 2 PnP

### ISSUE THREAD

**Issue by simnalamburt** [vercel/next.js#16548] opened 2020-08-25 08:50 UTC
# Bug report

## Describe the bug
Next.js 9.5.2 breaks with Yarn 2 PnP.

## To Reproduce
Execute following shell script in an empty directory.

```bash
#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

mkdir -p pages
cat <<'EOF' > pages/index.js
export default function Index() {
  return <h1>Hi</h1>
}
EOF

cat <<'EOF' > package.json
{
  "dependencies": {
    "next": "9.5.2",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  }
}
EOF

yarn set version berry
yarn install
yarn next dev
```

## Expected behavior
Next.js server should be started.

## Screenshots
![image](https://user-images.githubusercontent.com/4435445/91153513-465e8200-e6fb-11ea-84d6-b504332a8fa2.png)

```console
Error: next tried to access caniuse-lite, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: caniuse-lite (via "caniuse-lite")
Required by: next@virtual:dc3fc578bfa5e06182a4d2be39ede0bc5b74940b1ffe0d70c26892ab140a4699787750fba175dc306292e80b4aa2c8c5f68c2a821e69b2c37e360c0dff36ff66#npm:9.5.2 (via /home/simnalamburt/workspace/a/.yarn/$$virtual/next-virtual-7d8f82b49d/0/cache/next-npm-9.5.2-504d9b0249-948ca8f966.zip/node_modules/next/dist/compiled/postcss-preset-env/)

Require stack:
- /home/simnalamburt/workspace/a/.yarn/$$virtual/next-virtual-7d8f82b49d/0/cache/next-npm-9.5.2-504d9b0249-948ca8f966.zip/node_modules/next/dist/compiled/postcss-preset-env/index.js
- /home/simnalamburt/workspace/a/.yarn/$$virtual/next-virtual-7d8f82b49d/0/cache/next-npm-9.5.2-504d9b0249-948ca8f966.zip/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js
- /home/simnalamburt/workspace/a/.yarn/$$virtual/next-virtual-7d8f82b49d/0/cache/next-npm-9.5.2-504d9b0249-948ca8f966.zip/node_modules/next/dist/build/webpack/config/blocks/css/index.js
- /home/simnalamburt/workspace/a/.yarn/$$virtual/next-virtual-7d8f82b49d/0/cache/next-npm-9.5.2-504d9b0249-948ca8f966.zip/node_modules/next/dist/build/webpack/config/index.js
- /home/simnalamburt/workspace/a/.yarn/$$virtual/next-virtual-7d8f82b49d/0/cache/next-npm-9.5.2-504d9b0249-948ca8f966.zip/node_modules/next/dist/build/webpack-config.js
- /home/simnalamburt/workspace/a/.yarn/$$virtual/next-virtual-7d8f82b49d/0/cache/next-npm-9.5.2-504d9b0249-948ca8f966.zip/node_modules/next/dist/server/hot-reloader.js
- /home/simnalamburt/workspace/a/.yarn/$$virtual/next-virtual-7d8f82b49d/0/cache/next-npm-9.5.2-504d9b0249-948ca8f966.zip/node_modules/next/dist/server/next-dev-server.js
- /home/simnalamburt/workspace/a/.yarn/$$virtual/next-virtual-7d8f82b49d/0/cache/next-npm-9.5.2-504d9b0249-948ca8f966.zip/node_modules/next/dist/server/next.js
- /home/simnalamburt/workspace/a/.yarn/$$virtual/next-virtual-7d8f82b49d/0/cache/next-npm-9.5.2-504d9b0249-948ca8f966.zip/node_modules/next/dist/server/lib/start-server.js
- /home/simnalamburt/workspace/a/.yarn/$$virtual/next-virtual-7d8f82b49d/0/cache/next-npm-9.5.2-504d9b0249-948ca8f966.zip/node_modules/next/dist/cli/next-dev.js
- /home/simnalamburt/workspace/a/.yarn/$$virtual/next-virtual-7d8f82b49d/0/cache/next-npm-9.5.2-504d9b0249-948ca8f966.zip/node_modules/next/dist/bin/next
    at internalTools_makeError (/home/simnalamburt/workspace/a/.pnp.js:11411:34)
    at resolveToUnqualified (/home/simnalamburt/workspace/a/.pnp.js:12344:21)
    at resolveRequest (/home/simnalamburt/workspace/a/.pnp.js:12430:29)
    at Object.resolveRequest (/home/simnalamburt/workspace/a/.pnp.js:12496:26)
    at Function.external_module_.Module._resolveFilename (/home/simnalamburt/workspace/a/.pnp.js:11643:34)
    at Function.external_module_.Module._load (/home/simnalamburt/workspace/a/.pnp.js:11507:48)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/home/simnalamburt/workspace/a/.yarn/$$virtual/next-virtual-7d8f82b49d/0/cache/next-npm-9.5.2-504d9b0249-948ca8f966.zip/node_modules/next/dist/compiled/postcss-preset-env/index.js:1:241487)
    at __webpack_require__ (/home/simnalamburt/workspace/a/.yarn/$$virtual/next-virtual-7d8f82b49d/0/cache/next-npm-9.5.2-504d9b0249-948ca8f966.zip/node_modules/next/dist/compiled/postcss-preset-env/index.js:1:154)
```

## System information

- OS: Debian GNU/Linux 10
- Version of Next.js: 9.5.2
- Version of Node.js: 14.6.0

**Comment by simnalamburt** [comment] 2020-08-25 09:01
You can currently workaround this issue with [`packageExtensions`](https://yarnpkg.com/configuration/yarnrc#packageExtensions). Add this codes to your `.yarnrc.yml`

```yml
# Workaround of https://github.com/vercel/next.js/issues/16548
packageExtensions:
  next@*:
    dependencies:
      caniuse-lite: "^1.0.30001117"
```

**Comment by simnalamburt** [comment] 2020-08-25 09:05
I just noticed that this issue has been already fixed with https://github.com/vercel/next.js/pull/16091. Using Next.js v9.5.3-canary.3 or later will fix this issue.

**Comment by timneutkens** [comment] 2020-08-25 10:11
Going to close this as it was already fixed 👍

**Closed by timneutkens** 2020-08-25 10:11 UTC

**Comment by balazsorban44** [comment] 2022-01-29 15:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
