### ISSUE TITLE
Redirection to other locales from gsp and gssp fail

### ISSUE THREAD

**Issue by cvolant** [vercel/next.js#35105] opened 2022-03-07 13:25 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #33-Ubuntu SMP Fri Feb 4 17:03:31 UTC 2022
    Binaries:
      Node: 14.17.0
      npm: 6.14.13
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.6
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Firefox Developer Edition 98.0b10 - Firefox 97.0.2 - Chromium 99.0.4844.51

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

In getServerSideProps and in getStaticProps, if I try to redirect to another locale by adding a locale prefix to the destination, the whole destination is added to the current locale prefix.
Ex.
```
return { redirect: { destination: '/fr/pathname' } }
```
Trying to visit the page containing the above redirection in its getServerSideProps or getStaticProps from the `/nl` page get me redirected to `/nl/fr/pathname` (which fail in the getStaticProps case).

### Expected Behavior

I expected to be correctly redirected to the new locale url, like `/fr/pathname`.

### To Reproduce

Cf. the mininal reproduction here: https://github.com/cvolant/i18n-routing
Steps to reproduce are described in the readme.

**Comment by vinaynair39** [comment] 2022-04-14 19:09
@cvolant any luck with this yet? I'm facing the same issue :(

**Comment by cvolant** [comment] 2022-04-16 12:24
@vinaynair39 Unfortunately not... 😕
If you find a workaround, please post it here.

**Comment by hanneslund** [comment] 2022-05-19 07:23
This got fixed by #36944. I can't reproduce the error with the latest canary release 👍

**Closed by hanneslund** 2022-05-19 07:23 UTC
Labels: template: bug, area: I18n
