### ISSUE TITLE
Unicode URLs don't work

### ISSUE THREAD

**Issue by memark** [vercel/next.js#15896] opened 2020-08-05 09:42 UTC
# Bug report

## Describe the bug

Links within and into the application don't work if they contain unicode characters e.g. `é`.

### To Reproduce

1. Clone repo https://github.com/memark/nextjs-951-unicode-url-bug-repro
2. Run `yarn dev`
3. Browse `localhost:3000`
4. Click on the two links.

None of the links work.

### Expected behavior

I expect both links to work, and the browser to navigate and show the café page.

### To Reproduce

1. Clone repo https://github.com/memark/nextjs-935-unicode-url-bug-repro
2. Run `yarn dev`
3. Browse `localhost:3000`
4. Click on the two links.

The first link works, the second doesn't.

### Expected behavior

I expect both links to work, and the browser to navigate and show the café page.

## System information

- Mac OS 10.15.6
- Google Chrome Version 84.0.4147.105 (Official Build) (64-bit)
- Version of Next.js: 9.5.1 (and 9.3.5)
- Version of Node.js: 12.18.3

## Additional context

It seems the problem got worse somewhere between 9.3.5 and 9.5.1.

Investigating in Chrome Dev Tools shows this:

### 9.5.1

With `<Link />`, a request is made to http://localhost:3000/_next/static/chunks/pages/caf%25C3%25A9.js
Notice how the URL is double encoded! `%25` means `%`, and `%C3%A9` is the code point for `é`.
This doesn't work.
A fallback request is made to http://localhost:3000/caf%C3%A9, which doesn't work either.

### 9.3.5

With `<Link />`, a request is made to http://localhost:3000/_next/static/chunks/pages/caf%C3%A9.js, which works!
However reloading the page, or entering the URL manually doesn't work.

**Comment by midori0507** [comment] 2020-08-06 14:12
@memark Your repo is not accessible (is it still private)?

**Comment by memark** [comment] 2020-08-06 15:05
@midori0507 Right you are. I've made them public now. So sorry.

**Comment by stefanprobst** [comment] 2020-08-15 19:44
i can confirm this does not work.

**Comment by stefanprobst** [comment] 2020-08-15 19:44
related: #16060

**Comment by stfenjobs** [comment] 2021-08-28 13:45
same here

**Comment by klarstrup** [comment] 2022-01-12 14:05
Another peculiar URL character issue:
- https://github.com/vercel/next.js/issues/31523

**Comment by balazsorban44** [comment] 2022-01-19 11:52
Duplicate of #16060, and the reproduction was also not available. If you still have issues, please open a new one with a reproduction.

**Closed by balazsorban44** 2022-01-19 11:52 UTC
