### ISSUE TITLE
Incorrect docs example on `Custom App` and `App.getInitialProps` behaviour

### ISSUE THREAD

**Issue by hgezim** [vercel/next.js#26282] opened 2021-06-17 20:04 UTC
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

v12.7.0

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying your application?

AWS ECS

### Describe the Bug

In the [custom app docs](https://nextjs.org/docs/advanced-features/custom-app), the example app has a comment that says:

> calls page's `getInitialProps` and fills `appProps.pageProps`

Here:

```
// import App from 'next/app'

function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}

// Only uncomment this method if you have blocking data requirements for
// every single page in your application. This disables the ability to
// perform automatic static optimization, causing every page in your app to
// be server-side rendered.
//
// MyApp.getInitialProps = async (appContext) => {
//   // calls page's `getInitialProps` and fills `appProps.pageProps`
//   const appProps = await App.getInitialProps(appContext);
//
//   return { ...appProps }
// }

export default MyApp

```

That comment seems outdated since `getInitalProps` is no longer encouraged for use in pages. Furthermore, a statement below that code block says:

> `pageProps` is an object with the initial props that were preloaded for your page by one of our data fetching methods, otherwise it's an empty object.

Also affects the [typescript docs on custom apps](https://nextjs.org/docs/basic-features/typescript#custom-app).

### Expected Behavior

Docs should say

> // calls page's `getServerSideProps` and `getStaticProps` and fills `appProps.pageProps`

### To Reproduce

See links in the description.

**Comment by timneutkens** [comment] 2021-06-18 13:48
> Expected Behavior
> Docs should say
> // calls page's getServerSideProps and getStaticProps and fills appProps.pageProps

This is not correct, `App.getInitialProps` only calls `getInitialProps` on the page (if it exists). `getServerSideProps` and `getStaticProps` are handled by Next.js and are not exposed to the application.

**Comment by ijjk** [comment] 2021-09-19 05:16
Closing per above as the documentation does appear to be correct, feel free to respond with additional info if we can make this bit a little more clear!

**Closed by ijjk** 2021-09-19 05:16 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
