### ISSUE TITLE
Image optimization incorrectly returns 400

### ISSUE THREAD

**Issue by fulopdaniel** [vercel/next.js#23837] opened 2021-04-08 19:08 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

v12.18.3

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When supplying an AWS S3 URL to the Image component from next/image, an error is returned from the server saying "The requested resource isn't a valid image.". 

This is a new feature, introduced in this commit:
https://github.com/vercel/next.js/commit/98211405a60d286a8769dc1b76723016153355a6

However the content type of an image coming from S3 in my case is 'binary/octet-stream', so 400 status code is returned, because it does not start with "image/", and the picture does not load.

Using Next.js@10.0.1 does load the image, or using a simple img tag also works.

### Expected Behavior

The image should be loaded.

### To Reproduce

import Image from 'next/image';

<Image src={<INSERT_S3_URL>} height={200} width={100} />

**Comment by ElvisWong** [comment] 2021-04-12 07:55
You can change the metadata in headers of your image in S3 from application/octlet-stream to image/jpeg. That will solve the problem.

![image](https://user-images.githubusercontent.com/9835818/114359837-f60f3400-9ba6-11eb-8858-18e63951500d.png)

![image](https://user-images.githubusercontent.com/9835818/114360277-6b7b0480-9ba7-11eb-9d6d-5fe578181046.png)

**Comment by fulopdaniel** [comment] 2021-04-13 07:37
Yes, but it is not possible in every scenario. For example we are using presigned URLs to upload the pictures, and I believe it is not possible to set the content-type automatically with that approach.

**Comment by shuding** [comment] 2021-04-13 08:47
Closing as duplicate of #23523.

**Closed by shuding** 2021-04-13 08:47 UTC
Labels: template: bug

**Comment by jonahallibone** [comment] 2021-04-13 20:18
@fulopdaniel it is 

> Yes, but it is not possible in every scenario. For example we are using presigned URLs to upload the pictures, and I believe it is not possible to set the content-type automatically with that approach.

@fulopdaniel It is, just send it along in the header of the request, or in the options object when creating the presigned URL

**Comment by INFLOWMusic** [comment] 2022-01-01 17:55
@jonahallibone I have passed the content-type in both the header and the options and still when I upload it's setting the type to octet-stream 

for example this 

```
const imagePost = s3.createPresignedPost({
        Bucket: process.env.AWS_SINGLE_IMAGES,
        Fields: { 
          key, 
          ContentType: 'image/jpeg',
        },
        Expires: 120, // seconds
        Conditions: [
          ['content-length-range', 0, 1048576], // up to 1 MB
        ],
      });
```
doesn't solve anything, I'm on next 12

**Comment by balazsorban44** [comment] 2022-01-31 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
