### ISSUE TITLE
next/image isn't a drop in replacement for <img>

### ISSUE THREAD

**Issue by okeybond** [vercel/next.js#18417] opened 2020-10-28 20:17 UTC
```
                      <div style={{height: 90, position: 'relative', flex: '0 0 90px'}}
                         className={"ml-3 pull-right align-self-center"}>
                        <Image
                            width={"100%"}
                            height={"100%"}
                            src={thumbnail}
                            className={'rounded'}
                            alt="thumbnail"
                            style={isGraphicOrProfane ? {filter: 'blur(2px)'} : null}
                        />
                        {
                            (!isEmpty(youtubeIds) || !isEmpty(video)) &&
                            <Icon name={'play'} color={'red'} inverted style={{
                                position: 'absolute',
                                bottom: 0,
                                left: 0,
                            }} bordered size={'tiny'}/>
                        }
                    </div>
```

Image from next/image did not show any image, just the thumbnail alt. Something is wrong with next/image

**Comment by martinowren** [comment] 2020-10-28 20:25
Experiencing the same, style tag does not work properly and the Image component does add a lot of divs with some hefty CSS so old styling does not work.

**Comment by mimoid-prog** [comment] 2020-10-28 20:33
@okeybond btw width and height of the Image component must be integers representing pixels, not string

**Comment by okeybond** [comment] 2020-10-28 20:57
> @okeybond btw width and height of the Image component must be integers representing pixels, not string

not necessarily, please refer to doc

**Comment by jamesmosier** [comment] 2020-10-28 21:17
Hi @okeybond. Please add a complete reproduction with a repository showing the issue.

Also [the docs](https://nextjs.org/docs/api-reference/next/image) say that `width` and `height` must be integers and are required unless `unsized` is true.

**Comment by okeybond** [comment] 2020-10-28 21:27
> Hi @okeybond. Please add a complete reproduction with a repository showing the issue.
> 
> Also [the docs](https://nextjs.org/docs/api-reference/next/image) say that `width` and `height` must be integers and are required unless `unsized` is true.

<img width="825" alt="Screenshot 2020-10-28 at 21 24 49" src="https://user-images.githubusercontent.com/48156152/97498436-15e9cd00-1964-11eb-935f-1def893f452f.png">
It's a string in the pic above,  though I have also tried with Integer no luck

`import React from 'react';
import {Button, Icon} from "semantic-ui-react";
import get from 'lodash/get';
import isEmpty from 'lodash/isEmpty';
import {ListGroup} from "react-bootstrap";
import {approx, getGroupName, timeSince} from "../../utilities/utils";
import Link from "next/link";
import {connect} from "react-redux";
import {readPost, toggleDislikePost, toggleLikePost} from "../../screens/main/postDetails/PostDetailsActions";
import Image from "next/image";


const PostItem = ({post, userId, readPost, toggleLikePost, toggleDislikePost}) => {
    let {title, groupId, groupName, timeStamp, diffVoteCnt, id, isGraphic, isProfane, youtubeIds, thumbnail, isRead, dislikers, likers, video} = post;
    let isGraphicOrProfane = isGraphic || isProfane;

    if (!Boolean(thumbnail) && !isEmpty(youtubeIds)) {
        thumbnail = `https://i.ytimg.com/vi/${youtubeIds[0]}/default.jpg`
    }
    return (
        <ListGroup.Item onClick={() => readPost(id)} className={isRead ? "text-secondary p-2" : 'p-2'}>
            <Link href="/p/[id]" as={`/p/${id}`}>
                <div className={
                    'd-flex justify-content-between'
                }>
                    <div className={'d-flex flex-column justify-content-between'}>
                        <div>
                            <h6 className={'m-0'} style={{fontSize: 14}}>{title}</h6>
                            <div className={'d-flex flex-row py-1 text-secondary'} style={{fontSize: 12}}>
                                <div>
                                    {groupName || getGroupName(groupId)} ∙ {timeSince(new Date(timeStamp))}
                                </div>
                                {isGraphicOrProfane &&
                                <div className={'ml-1'}> ∙ 🔞</div>}
                            </div>
                        </div>
                        <div className={'d-flex flex-row justify-content-between align-items-center'}
                             style={{width: '110px'}}>
                            <Button icon={'arrow up'}
                                    onClick={() => toggleLikePost(post, userId)}
                                    color={likers.includes(userId) ? 'green' : null} circular size={'mini'}/>
                            <div style={{fontSize: 14}}>{approx(diffVoteCnt, 1)}</div>
                            <Button icon={'arrow down'} color={dislikers.includes(userId) ? 'red' : null}
                                    onClick={() => toggleDislikePost(post, userId)} circular size={'mini'}/>
                        </div>
                    </div>
                    {Boolean(thumbnail) &&
                    <div style={{height: 90, position: 'relative', flex: '0 0 90px'}}
                         className={"ml-3 pull-right align-self-center"}>
                        <Image
                            width={90}
                            height={90}
                            src={thumbnail}
                            className={'rounded'}
                            alt="thumbnail"
                            style={isGraphicOrProfane ? {filter: 'blur(2px)'} : null}
                        />
                        {
                            (!isEmpty(youtubeIds) || !isEmpty(video)) &&
                            <Icon name={'play'} color={'red'} inverted style={{
                                position: 'absolute',
                                bottom: 0,
                                left: 0,
                            }} bordered size={'tiny'}/>
                        }
                    </div>
                    }
                </div>
            </Link>
        </ListGroup.Item>
    )
}

const mapStateToProps = (state) => {
    return {
        userId: get(state.firebase, 'auth.uid', ''),
    };
};

export default React.memo(connect(mapStateToProps, {
    readPost,
    toggleLikePost,
    toggleDislikePost
})(PostItem))`

**Comment by klaaz0r** [comment] 2020-10-28 21:45
> Hi @okeybond. Please add a complete reproduction with a repository showing the issue.
> 
> Also [the docs](https://nextjs.org/docs/api-reference/next/image) say that `width` and `height` must be integers and are required unless `unsized` is true.

Side note on that in the types it shows string's as possible type for width and height

```
   width: number | string;
   height: number | string;
```

**Comment by kbrgl** [comment] 2020-10-28 22:54
This is a duplicate of #18414, which I just opened a little while ago. #18414 includes reproduction steps.

**Closed** 2020-10-28 23:02 UTC
Labels: please add a complete reproduction
