### ISSUE TITLE
redirects in next.config.js do not work with next/link when source path exists

### ISSUE THREAD

**Issue by indorock** [vercel/next.js#37889] opened 2022-06-21 18:49 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 14.15.4
      npm: 8.12.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome  102.0.5005.115 

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

According to the documentation: 

> Redirects are checked before the filesystem which includes pages and /public files.

However this does not seem to be the case when using a next/link component.

### Example:

**next.config.js**
<img width="350" alt="Screenshot 2022-06-21 at 19 45 34" src="https://user-images.githubusercontent.com/66767/174865566-07dd1278-da58-4254-af66-7eb130ac9ef4.png">

**index.tsx**
<img width="481" alt="Screenshot 2022-06-21 at 19 47 32" src="https://user-images.githubusercontent.com/66767/174865589-441f39d6-42ca-4f9e-a2b1-ef149edb45f7.png">

Clicking this link does NOT redirect to `/coming-soon`, but just goes to `/special-events`. However, reloading the page once there DOES kick off the redirect.  Only when `/pages/special-events.tsx` exists on the filesystem, does the redirect fail. If I rename that file to anything else , the redirect works. Also, using a plain `<a/>` tag also fixes the problem. The issue only seems to occur when implementing a `next/link` component.

### Expected Behavior

The redirect should work in ALL cases, whether an anchor tag or a next/link component is driving the request, whether or not the source page specified in `next.config.js` exists. 

### Link to reproduction

https://github.com/indorock/nextjs-test/tree/main/redirect

### To Reproduce

Check out the above git repo and run the NextJS app inside the `redirect` folder, click the 4 links on the page. All 4 should observe the redirect, but the first one (next/link component with an existing source path) will not.

**Comment by EvHaus** [comment] 2022-07-02 00:31
I'm seeing a similar problem. Also of note -- I've observed that the same problem occurs if you attempt to do the redirect in `getServerSideProps` too using this code:

```ts
export const getServerSideProps: GetServerSideProps = async (context) => {
    context.res.setHeader('location', ON_SUCCESS_PATH);
    context.res.statusCode = 302;
    context.res.end();
    return {props: {}};
};
```

**Comment by kevintap** [comment] 2022-08-18 18:13
+1 Seeing the same issue here with next/link if you have both a redirect and an actual page on the filesystem with the same source path. The docs indicate that redirects are evaluated before the filesystem, but that is not the case.

**Comment by ijjk** [comment] 2022-08-20 13:18
Closing as a duplicate of https://github.com/vercel/next.js/discussions/26426

**Closed by ijjk** 2022-08-20 13:18 UTC
Labels: template: bug, area: Routing

**Comment by indorock** [comment] 2022-08-20 14:38
> Closing as a duplicate of #26426

Is there any way for people not a part of the Vercel org to follow this discussion?

**Comment by ijjk** [comment] 2022-08-21 15:22
Seems GitHub is breaking the link 🤔 `https://github.com/vercel/next.js/discussions/26426` is the original link posted and should allow subscribing.

**Comment by leerob** [comment] 2023-08-21 19:06
Happy to report that `redirects` defined in `next.config.js` will apply to both server navigations and client navigations (e.g. with `next/link`) in the Next.js App Router.

[Learn more about incrementally adopting it from the Pages Router here.](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration)
