### ISSUE TITLE
process.env is an empty object in _middleware.ts

### ISSUE THREAD

**Issue by rumtraubenuss** [vercel/next.js#30612] opened 2021-10-29 10:20 UTC
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Brave

### What operating system are you using?

macOS 11.5.2

### How are you deploying your application?

npm run dev and Vercel

### Describe the Bug

Accessing `process.env` returns an empty object `{}` in `pages/_middleware.ts`.
This happens locally when running `npm run dev` and also when app is deployed to Vercel.

### Expected Behavior

Following the Vercel edge functions docs, environment variables should be available via `process.env`.
https://vercel.com/docs/concepts/functions/edge-functions#environment

### To Reproduce

Create a middleware file `pages/_middleware.ts`:

```
import { NextResponse } from 'next/server';

export function middleware() {
  console.log(process.env);
  return NextResponse.next();
}
```

Start the app, visit any page of the app and inspect console output.

**Comment by rumtraubenuss** [comment] 2021-10-29 21:45
This is related to how `_middleware.ts` is webpack transformed by the `middleware-plugin.ts`.
Only when you access an env var directly you will get the value. You can't destructure from `process.env` or get the whole object. I am not sure if this behaviour is intended or should be mentioned in the docs.

```
// _middleware.ts
const { NODE_ENV } = process.env
console.log(NODE_ENV) // undefined
console.log(process.env) // {}
console.log(process.env.NODE_ENV) // development (when run locally)
```

**Comment by hugefunwoo** [comment] 2021-10-30 01:23
I believe it's documented here https://nextjs.org/docs/api-reference/next.config.js/environment-variables

> Next.js will replace process.env.customKey with 'my-value' at build time. Trying to destructure process.env variables won't work due to the nature of webpack DefinePlugin.

**Comment by rumtraubenuss** [comment] 2021-10-30 07:20
Ah, right! 👍 I did not see this in the docs and was not expecting this since descrtucturing from `process.env` is possible in `pages/api` routes.

**Comment by timneutkens** [comment] 2021-10-30 12:57
This can have better docs in the middleware section though 👍 Marking it as a docs issue.

**Closed** 2021-11-23 20:55 UTC
Labels: area: documentation, area: Middleware

**Comment by Defite** [comment] 2021-12-07 17:30
Why is this closed? Even trying to access `process.env.MY_TOKEN` results in undefined.

**Comment by molebox** [comment] 2021-12-07 17:40
Hey @Defite where are you defining your env vars?

**Comment by Defite** [comment] 2021-12-07 17:57
> Hey @Defite where are you defining your env vars?

In next.config.js:

```
module.exports = {
  publicRuntimeConfig: {
    NEXT_PUBLIC_API_BASE: process.env.API_BASE,
    NEXT_PUBLIC_API_AUTH: process.env.API_AUTH,
  },
}
```

But then I realise to change vars to API_BASE and API_AUTH. Calling `process.env.API_AUTH` returns it's value.

**Comment by balazsorban44** [comment] 2022-01-27 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
