### ISSUE TITLE
with-sentry error infinite loop

### ISSUE THREAD

**Issue by pooriamo** [vercel/next.js#11001] opened 2020-03-12 13:11 UTC
I used the example [with-sentry](https://github.com/zeit/next.js/blob/canary/examples/with-sentry) But it put the page in infinite loop when an error occured.

The problem is in `getDerivedStateFromError` method.

```
static getDerivedStateFromError() {
    // React Error Boundary here allows us to set state flagging the error (and
    // later render a fallback UI).
    return { hasError: true }
}
```

After each error, `getDerivedStateFromError` is setting `hasError` to true and makes the component re-render!

Is this even a bug?

**Comment by pooriamo** [comment] 2020-03-12 13:26
Turns out to be my problem. I was loading the `Error` component in the render method using `next/dynamic` And it caused the infinite render.

**Comment by pooriamo** [comment] 2020-03-12 15:44
I'm sorry, The problem still exist. It exists only when I use both `componentDidCatch` and `getDerivedStateFromError` together. Having only one of them doesn't make problem.

**Comment by Chastrlove** [comment] 2020-03-13 05:48
same problem. infinite loop when an error occured.

**Comment by yaohuangguan** [comment] 2020-03-18 09:22
Hi, you may wanna use _error.js to handle the cases. but for error boundary, i am using 
```javascript
 state = {
    hasError: false,
    error: ""
  };
  static getDerivedStateFromError(error) {

    return { hasError: true, error: error };
  }

  componentDidCatch(error, errorInfo) {
//to server
  }
```

**Comment by nicobarray** [comment] 2020-04-30 09:27
Hi @pooriamo & @Chastrlove,

Could you give a repo/branch to reproduce the infinite loop? I have been testing on a fresh clone of the with-sentry example and it does not loop apparently.

I'd love to help in resolving this issue 👍

**Comment by BlakeBrown** [comment] 2020-07-14 03:52
I'm not sure if it's a duplicate of this issue, but I'm having the same problem on my project whenever I do

```
export async function getServerSideProps(context) {
  const response = await fetch('...');
  ...
```

and the fetch fails. I'm also using sentry in my node server.

**Comment by ijjk** [comment] 2020-09-10 20:53
Hi, the `with-sentry` example appears to be working correctly as mentioned in the above reply. 

I'm going to close this since doesn't appear to be an issue with the example, if you are still experiencing this please provide a complete reproduction and we can investigate further.

**Closed by ijjk** 2020-09-10 20:53 UTC
Labels: good first issue

**Comment by balazsorban44** [comment] 2022-01-29 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
