### ISSUE TITLE
Missing peerDependency "@babel/core@^7.0.0-0" from next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5

### ISSUE THREAD

**Issue by m1heng** [vercel/next.js#31887] opened 2021-11-28 14:25 UTC
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

16.x

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

next > styled-jsx: @babel/plugin-syntax-jsx@7.14.5 requires a peer of @babel/core@^7.0.0-0 but none was installed.

package `next` requires `styled-jsx` which has a unversioned optional peerDep `@babel/core`, but styled-jsx also requires `@babel/plugin-syntax-jsx` which has a required peerDep `@babel/core`. And `next` does not require `@babel/core`.
This ends up with `@babel/plugin-syntax-jsx` missed his peerDep `@babel/core`.

Although it works for now, but with `pnpm`, it will log warning like above, and I think for sure a clear dependency graph should be maintained.

There are multiple solutions, 
1. `next` add `@babel/core` as dependency, and mark `@babel/core` as required peerDependency in `styled-jsx`.
2. `next` add `@babel/core` as peerDependency, and let user add `@bable/core` in their own project.
3. remove  peerDep `@babel/core` from `@babel/plugin-syntax-jsx` (I had a look into this package, I am not really sure why did they add `@babel/core` as its peerDep)

### Expected Behavior

Clear dependency.

### To Reproduce

No need.

**Comment by rtritto** [comment] 2021-11-29 18:13
Related https://github.com/vercel/styled-jsx/issues/736

**Comment by huozhi** [comment] 2022-01-19 11:50
Resolved by #32742 , you can install latest canary (`next@12.0.9-canary.2`) to get rid of this warning

**Closed by huozhi** 2022-01-19 11:50 UTC
Labels: kind: bug, good first issue, area: Yarn PnP / pnpm, area: styled-jsx

**Comment by balazsorban44** [comment] 2022-02-18 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
