### ISSUE TITLE
Static files under public page doens't work on deployed site.

### ISSUE THREAD

**Issue by RizziSilva** [vercel/next.js#19329] opened 2020-11-19 19:41 UTC
# Bug report

## Describe the bug
As the title says, the static files that are under the public folder in the root of the application doesn't work on deployed app, but it do work as intended locally. 

## To Reproduce
I have tried to reproduce the error deploying a simple app on vvercel, but it work's as expected.

## Expected behavior

Files put under public folder should be avaible on deployed website.

## Screenshots
As you can see the arrow svg doesnt load.
![image](https://user-images.githubusercontent.com/52845549/99715318-706ada80-2a85-11eb-808e-d12504be3a62.png)

## Additional context

All files under public folder are current not working, if you try to acess `host/robots.txt`, for example, it will go to 404 page.
We are current using a custom server with express. Do a have to do something different to deploy a site using custom server or a simple next start would do the trick.

**Comment by jamesmosier** [comment] 2020-11-20 02:39
Duplicate of https://github.com/vercel/next.js/discussions/19308

**Closed by jamesmosier** 2020-11-20 02:39 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-29 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
