### ISSUE TITLE
add type to extend  ParsedUrlQueryInput type in userRouter 

### ISSUE THREAD

**Issue by wildfrontend** [vercel/next.js#20444] opened 2020-12-24 08:18 UTC
if i want to get value form query by typescript 

it alway make typescript error, because typescript can not get vlaue type from `useRouter`

i find  `getStaticProps` or `getServerSideProps`  can define query value Type

so i think nextjs can change `useRouter` type like  `getStaticProps` or `getServerSideProps`   ,to let me to extend query Input in `useRouter`

some issues have a solve

like https://github.com/vercel/next.js/issues/7926#issuecomment-512364189

**Comment by timneutkens** [comment] 2021-01-03 15:09
Closing as the issue template was ignored/removed.

**Closed by timneutkens** 2021-01-03 15:09 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-28 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
