### ISSUE TITLE
Can not use async/await in middleware

### ISSUE THREAD

**Issue by michael-pomelo** [vercel/next.js#35973] opened 2022-04-07 15:25 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information
```
Operating System:
      Platform: linux
      Arch: x64
      Version: #202203111231 SMP PREEMPT Fri Mar 11 12:59:53 UTC 2022
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.4
      react: 17.0.1
      react-dom: 17.0.1
```
### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

N/A

### Describe the Bug

When using middleware, `next build` throws an error when using async/await in the middleware function (or a function imported by the middleware).

Error:

```
Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Middleware pages/library/_middleware
```

### Expected Behavior

No error to be thrown.  I am expecting no error because async/await is fully support as per the middleware documentation.

Also when I change my code to use native Promises instead of async/await, `next build` works fine.

### To Reproduce

I am having a hard time reproducing it, but this is what I found:

To my knowledge, the regenerator-runtime is shim/polyfill/whatever that is used to support async/await both in the browser and node.

I believe the error I am seeing above is from the static code analysis, and not an actual compilation error.

I traced the error back to here: https://github.com/vercel/next.js/blob/canary/packages/next/build/webpack/plugins/middleware-plugin.ts#L239

I noticed that the error is not thrown if the `module.identifier` is regenerator-runtime!  However, the path seems to only be allowed to be a specific path/filename.  I then noticed that (for some reason) my build is pulling in this path as the regenerator-runtime:

```
node_modules/next/dist/compiled/@babel/runtime/regenerator/index.js
```

It looks like that is a valid path because the file is just one line that pulls in the actual regenerator-runtime from `node_modules/next/dist/compiled/regenerator-runtime/runtime.js` (and this is the file path that seems to match the regex).

I'm not sure how to reporduce because I am not sure why Next.js is pulling in this other file for the regenerator-runtime that doesn't match the regex.

**Comment by balazsorban44** [comment] 2022-04-08 07:04
Could you please share your `_middleware` so we can investigate? You might be using some API that is not supported by the Edge Runtime, where Middleware runs.

See: https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis

**Comment by michael-pomelo** [comment] 2022-04-08 13:56
Sure, let me see if I can strip out any sensitive business logic.

I do just want to re-iterate that when I swapped out async/await for native Promises (using the same code, API's, everything), the compilation and the middleware worked.

I don't think its a bug with middleware, I just think its a bug with the detection of the regenerator-runtime.

**Comment by grikomsn** [comment] 2022-04-20 02:53
Here's a repro on my website:

- initial implementation, build failed: https://github.com/grikomsn/griko.id/blob/99a75c8572ab51046459338a68fe7388bed7453c/website/pages/%5Bslug%5D/_middleware.ts
- remove async await, build success, middleware does nothing or unfinished promise: https://github.com/grikomsn/griko.id/blob/a1bd912e6ad4825d14d14603cafcd8362594c8fb/website/pages/%5Bslug%5D/_middleware.ts
- test using `event.waitUntil`, build success, middleware does nothing: https://github.com/grikomsn/griko.id/blob/b52c7f99bd1bfa26a1fbada9789b111b5bef26fc/website/pages/%5Bslug%5D/_middleware.ts

Tested both on stable and canary, both using edge runtime enabled and disabled.

**Comment by grikomsn** [comment] 2022-04-22 17:22
@michael-pomelo any updates on your issue? Seems like my case is the same as yours.

**Comment by michael-pomelo** [comment] 2022-04-22 17:52
No updates, but thank you for adding the reproduction.

We do use the same use case: wanting to use pre-generated graphql codegen queries in middleware.

I really do think this is just a simple case of Next misidentifying the regenerator runtime module. It seems 3rd party code gets put on using the babel one instead of the one Next.js is checking for.

**Comment by grikomsn** [comment] 2022-04-22 17:54
I did try creating a simple middleware utilizing `fetch` and it does the same error. Curious if Vercel's edge examples do work[^1].

[^1]: https://github.com/vercel/examples/blob/main/edge-functions/redirects-upstash/lib/upstash.ts#L11-L17

**Comment by michael-pomelo** [comment] 2022-04-25 19:31
Further development on this:  I now believe this comes from un-transpiled dependencies.  We use a monorepo so we use https://www.npmjs.com/package/next-transpile-modules to transpile our shared code.  If I have a shared function that uses async/await and import it into my middleware, I get this error.

If I copy/paste the same code into my Next.js directory, I don't get an error and it works fine.

**Comment by tmilewski** [comment] 2022-05-02 20:18
Just wanted to follow up on @michael-pomelo's discovery...

### When using Nx...

**Importing from a middleware-specific project:**
On serve: Success
On build: `../../node_modules/next/dist/compiled/regenerator-runtime/runtime.js` error.

**Placing all code from said middleware-specific project directly into the `_middleware.ts` file:**
On serve: Success
On build: Success

**Comment by grikomsn** [comment] 2022-05-03 16:54
From @tmilewski's case, I would assume that the middleware cannot bundle sources outside the middleware scope similar to serverless API functions on Vercel. I'll experiment if that's the case and will post here.

**Comment by tmilewski** [comment] 2022-05-03 17:10
@grikomsn Thanks! I'll try and test a bit myself, but time is a bit of a luxury at the moment.

**Comment by acburdine** [comment] 2022-05-06 16:39
Can confirm I'm seeing this behavior as well (using an NX monorepo + Next.js middleware). The workaround I've got for the moment is to disable insertion of regenerator-runtime by using a custom .babelrc:

```json
{
  "presets": [
    [
      "@nrwl/next/babel",
      {
        "preset-env": {
          "exclude": ["@babel/plugin-transform-regenerator"]
        },
        "transform-runtime": {
          "regenerator": false
        }
      }
    ]
  ],
  "plugins": []
}
```

while this does make the build a bit slower (due to babel usage instead of swc) it fixes the issue.

**Comment by balazsorban44** [comment] 2022-06-24 10:42
Based on the comment here: https://github.com/vercel/next.js/issues/35973#issuecomment-1108957927 I'm closing this issue.

Middleware has been improved a lot lately, please check with the latest `canary`, and if you still have issues, please open a new bug report with an attached minimal reproduction, thanks!

**Closed by balazsorban44** 2022-06-24 10:42 UTC
Labels: type: needs investigation, area: Middleware
