### ISSUE TITLE
Next use-subscription dep doesn't have React 16 support

### ISSUE THREAD

**Issue by nicholaschiang** [vercel/next.js#18757] opened 2020-11-03 18:36 UTC
# Bug report

## Describe the bug
Next.js 10 should support React 16 without any warnings, but when I installed it, I got the following from Yarn:
```
➤ YN0060: │ next@npm:10.0.0 [b17e5] provides react@npm:16.13.1 with version 16.13.1 which doesn't satisfy ^17.0.0 requested by use-subscription@npm:1.5.0
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Upgrade any repository to using Next 10 and React 16
2. Install dependencies (optionally using Yarn Berry)
3. See error

## Expected behavior
There should be no dep warnings when using React 16 with Next 10.

## System information

- OS: PopOS 20.10
- Version of Next.js: 10.0.0
- Version of Node.js: 12.18.3

**Comment by jamesmosier** [comment] 2020-11-04 04:14
Duplicate of https://github.com/vercel/next.js/issues/18518

**Closed by jamesmosier** 2020-11-04 04:14 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-29 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
