### ISSUE TITLE
Upgrade Tailwind CSS Example to Tailwind 2

### ISSUE THREAD

**Issue by Immortalin** [vercel/next.js#19287] opened 2020-11-18 23:46 UTC
Tailwind 2 has been released, the version of Tailwind in the Next.js example folder is now out of date.

**Comment by benyou1969** [comment] 2020-11-19 04:17
same issue in [with-tailwindcss-emotion](https://github.com/vercel/next.js/blob/d47d83d88dc8db43e4b974f8a124794a8e5c9f72/examples/with-tailwindcss-emotion/package.json#L25) is outdated

**Comment by jagreehal** [comment] 2020-11-19 09:08
There is a PR for this https://github.com/vercel/next.js/pull/19278

**Comment by benyou1969** [comment] 2020-11-19 09:47
@jagreehal thanks for replying, will the example `with-tailwindcss-emotion` also be updated?

**Comment by Immortalin** [comment] 2020-11-19 17:49
@yakovlevyuri

**Comment by timneutkens** [comment] 2020-11-22 16:19
Closing as #19278 has been merged.

**Closed by timneutkens** 2020-11-22 16:19 UTC
Labels: template: bug

**Comment by DaniGuardiola** [comment] 2020-11-22 19:53
@timneutkens before I create a new issue could you please take a look at this issue: https://github.com/tailwindlabs/tailwindcss/issues/2870#issuecomment-731811135

I don't know if I'm doing something wrong, but I can't get Tailwind to work with styled-jsx.

Also, it could be useful to add this configuration to the with-tailwind example. I could send a PR for that once I get it working.

Thank you! :)

**Comment by Immortalin** [comment] 2020-11-24 05:02
@timneutkens

**Comment by Arthie** [comment] 2020-11-24 11:44
@benyou1969 I've created [#19476] to update the `with-tailwindcss-emotion` example to tailwind 2.0

**Comment by balazsorban44** [comment] 2022-01-29 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
