### ISSUE TITLE
Lighthouse: preload key requests warning

### ISSUE THREAD

**Issue by jacobarriola** [vercel/next.js#19525] opened 2020-11-25 14:59 UTC
# Bug report

## Describe the bug

I'm getting warnings when running LH tests with regards to preload keys and can't seem to figure out how to troubleshoot. 

There's an closed ticket in #16932 that has asked to create new issues for Next ^10.

Lighthouse report: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fhome-point-financial.vercel.app%2F

## Screenshots
```
A preload <link> was found for "***" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
A preload <link> was found for "***" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
A preload <link> was found for "***" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
A preload <link> was found for "***" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
A preload <link> was found for "***" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
A preload <link> was found for "***" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
A preload <link> was found for "***" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
```

## System information
- Version of Next.js: 10.0.1
- CSS: Chakra 1.0.1
- Deployment: Vercel

## Additional context
I'm using Chakra as my UI library, so not sure if this is an issue related to that project.

**Comment by insivika** [comment] 2020-11-26 06:21
Same 👆

**Comment by awareness481** [comment] 2020-11-26 08:36
Could we have a reproduction please? In my case, upgrading to v10 fixed those warnings.

**Comment by timneutkens** [comment] 2020-12-04 09:59
Closing as no reproduction was provided.

**Closed by timneutkens** 2020-12-04 09:59 UTC
Labels: please add a complete reproduction, template: bug

**Comment by jacobarriola** [comment] 2020-12-06 17:54
Sorry that I didn't respond in time. I can't create a reproduction, so there's probably something unique about my project that's causing the issue. If I nail something down, I'll report it here with a full reproduction. Thanks!

**Comment by olaj** [comment] 2021-02-17 08:00
I've posted this discussion back in October with a link to a project that also have this issue. My project is closed source at the moment so can't share that.

https://github.com/vercel/next.js/discussions/18287

The project  is https://github.com/JoseRFelix/nextjs-starter-blog and it produce this warning in Lighthouse.

https://i.imgur.com/8BwmTPv.png

**Comment by younesea** [comment] 2021-04-27 17:29
Same issue here:
https://yea-website-git-bugfix-imageoptimizations-yea-personalize.vercel.app/

**Comment by balazsorban44** [comment] 2022-01-28 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
