### ISSUE TITLE
Deploy issue with v12 and SWC on Docker

### ISSUE THREAD

**Issue by gabor-at-reed** [vercel/next.js#30742] opened 2021-11-01 14:46 UTC
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

16.13.0

### What browser are you using?

-

### What operating system are you using?

Linux

### How are you deploying your application?

Docker

### Describe the Bug

Hi,

We tried to upgrade our Next.js from v11 to v12 with SWC. For that, we had to get rid of the `.babelrc` file. After that, we did the necessary tweaks with Jest and finally got everything working locally. But...

We are using Docker to build and deploy our app. Within the `Dockerfile` we use the `node:lts-alpine` image as a builder stage. We run the `npm run build` command there, and we got this error:

```
info  - Creating an optimized production build...
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /www/node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/www/node_modules/next/dist/build/swc/index.js:29:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
error - Failed to load SWC binary, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
The command '/bin/sh -c npm run build' returned a non-zero code: 1

```

This is really sad as we cannot use the new, fast SWC stuff and have to roll it back to Babel. 😢 

We hope it will be fixed somehow in the near future.

### Expected Behavior

The expected behaviour is that the build should work without any errors.

### To Reproduce

You can reproduce the issue with the same config as we have and I described above.

**Comment by timneutkens** [comment] 2021-11-01 15:34
Duplicate of #30713

**Closed by timneutkens** 2021-11-01 15:34 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
