### ISSUE TITLE
HTTPS for local dev

### ISSUE THREAD

**Issue by Jared-Dev** [vercel/next.js#22545] opened 2021-02-25 20:55 UTC
**Describe the feature you'd like to request**

I'd like to have the ability to have `https` enabled for local development

**Describe the solution you'd like**

A flag (or have it on by default) that allows for doing local dev under SSL.

**Describe alternatives you've considered**

I have added a custom `server.js` just to enable this, but it feels "dirty."

**Comment by stramel** [comment] 2021-02-26 01:37
Duplicate of #10700

**Closed** 2021-02-26 10:48 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-28 16:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
