### ISSUE TITLE
Env variables not loaded for unit tests purpose

### ISSUE THREAD

**Issue by lipoolock** [vercel/next.js#22936] opened 2021-03-10 08:59 UTC
### What version of Next.js are you using?

v10.0.9-canary.4

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Firefox

### What operating system are you using?

Linux

### How are you deploying your application?

no

### Describe the Bug

If you set some environment variables in `.env` and `.env.test` they are not taken into account while playing unit tests and tests based on these variables fail

### Expected Behavior

With NextJs 10.0.6 it works well

### To Reproduce

You can login to sandbox and play the unit tests set here https://codesandbox.io/s/laughing-leaf-zfp7k?file=/__tests__/testing-library.js

If you run yarn test `__tests__/testing-library.js` you will get `undefined` instead of `fooBar` for the env variable set in `.env.test`

**Comment by ijjk** [comment] 2021-03-10 16:29
Hi, Next.js isn't being invoked at all when running tests in the above set-up, you need to load the env manually with `loadEnvConfig` from `@next/env`. The above reproduction also fails on `v10.0.6` since we never were loading environment variables at a per-page basis. 

Closing as this doesn't appear to be a bug in Next.js and instead with the test set-up

**Closed by ijjk** 2021-03-10 16:29 UTC
Labels: template: bug

**Comment by lipoolock** [comment] 2021-03-11 11:21
Hello @ijjk 
Thanks a lot for explanations
I just forgot that I previously used a workaround in `jest.config` proposed by @timneutkens there https://github.com/vercel/next.js/issues/1790
So I added it to the sandbox shared in this ticket.

But that requires to make the build of NextJs before launching tests
And this workaround doesn't work with the latest release by the way

But, by having a look again on that topic https://github.com/vercel/next.js/issues/1790 and thanks to your help, I have been able to make working my unit test

Below step to fix this issue
* Install `@next/env`
* In `jest.config` add this line `globalSetup: '<rootDir>/test.env.js',`
* in `test.env.js` add the block below
```
import { loadEnvConfig } from '@next/env'
import { resolve } from 'path'

export default async () => {
  const envFile = resolve(__dirname, '.')
  loadEnvConfig(envFile)
}
```

I would suggest to add this example in your doc, that could help all of us (as required by this (still opened) issue
https://github.com/vercel/next.js/issues/17903

**Comment by balazsorban44** [comment] 2022-01-28 15:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
