### ISSUE TITLE
[Experimental] strategy="worker" not loading js file 

### ISSUE THREAD

**Issue by DanielBailey-web** [vercel/next.js#36026] opened 2022-04-09 00:16 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
 Operating System:
      Platform: linux
      Arch: x64
      Version: #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022
    Binaries:
      Node: 14.18.1
      npm: 8.1.4
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.5-canary.4
      react: 18.0.0
      react-dom: 18.0.0
```

### What browser are you using? (if relevant)

Mozilla Firefox 99.0

### How are you deploying your application? (if relevant)

development

### Describe the Bug

Script is not loading test.js file when strategy is set to worker
```js
<Script src="/test.js" strategy="worker" />
```

### Expected Behavior

The script should still load I assume? Or I should start getting proxy town requests

### To Reproduce

```bash
$ yarn create next-app
> test # name repo
$ cd test
$ yarn add next@canary
$ yarn add @builder.io/partytown
```
Update config
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    nextScriptWorkers: true,
  },
};

module.exports = nextConfig;
```
Add a test file to the public directory
```js
// test.js
fetch("/api/hello")
```
Add script tag just below the Head in index.js
```js
<Script src="/test.js" strategy="worker" />
```
Run the server
```bash
$ yarn dev
```
go to `localhost:3000`
go to dev tools > network
test.js is never loaded
no proxytown/partytown requests either

**Comment by balazsorban44** [comment] 2022-04-11 07:44
I'm not able to reproduce this. My script:

```js
fetch("/api/hello")
  .then((res) => res.json())
  .then((data) => console.log(data))
```

seems to load fine, I can verify it from the Network tab as well:

Firefox:
![image](https://user-images.githubusercontent.com/18369201/162688794-01887c0c-77ff-4811-b8a4-b2bf49c80c09.png)

Chrome:
![image](https://user-images.githubusercontent.com/18369201/162688517-aeab8051-cc50-4dde-9c88-33f2bdba3a0f.png)


Could you create a full reproduction?

**Comment by DanielBailey-web** [comment] 2022-04-11 20:41
I tried it in Firefox private, Brave (linux-ubuntu), and google chrome (windows-10, incognito and normal) and still getting the same problem. 

I committed the branch to my github 
```bash
git clone https://github.com/DanielBailey-web/next-script-worker-reproduction1
```

**Comment by DanielBailey-web** [comment] 2022-04-11 21:30
It's not working for me on docker either. I uploaded the basic docker config to the git repo in case you are able to reproduce it in a container environment.

**Comment by DanielBailey-web** [comment] 2022-04-11 23:37
Upgraded OS to ubuntu 21.10 to see if that would do anything... Also reinstalled firefox.
```
Operating System:
      Platform: linux
      Arch: x64
      Version: #44-Ubuntu SMP Thu Mar 24 15:35:05 UTC 2022
    Binaries:
      Node: 14.18.1
      npm: 8.6.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.5-canary.4
      react: 18.0.0
      react-dom: 18.0.0
```

Also upgraded next@canary to 12.1.5-canary.6

The script tag is still not loading the test.js file

**Comment by DanielBailey-web** [comment] 2022-04-11 23:46
Ohh, here is an update, it works if I use localhost:3000 instead of my IP address on my local network. 

http://localhost:3000 Works
http://127.0.0.1:3000 Works
http://10.10.10.X:3000 Does not work

So this might be more of a proxy error than a next/script error

**Comment by housseindjirdeh** [comment] 2022-04-20 17:27
Thanks @DanielBailey-web for all the great details here. It does sound like its a proxy issue and not particularly a problem with next/script. I'll close this for the meantime, but happy to re-open it if you find any issues with the Script component in particular.

**Closed by housseindjirdeh** 2022-04-20 17:27 UTC
Labels: type: needs investigation, area: next/script
