### ISSUE TITLE
Error: Cannot find module './readBuffer' when Experimental option "babelMultiThread" is enabled

### ISSUE THREAD

**Issue by khades** [vercel/next.js#12550] opened 2020-05-06 09:02 UTC
# Bug report
When experimental option "babelMultiThread" is enabled, dev version does not start, giving error
```
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module './readBuffer'
Require stack:
- C:\Users\khades\projects\CODEr\node_modules\next\dist\compiled\thread-loader\worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\khades\projects\CIWD-CorpSites\Frontend\site-editor\node_modules\next\dist\compiled\thread-loader\worker.js:19:19)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\khades\\projects\\CODE\\node_modules\\next\\dist\\compiled\\thread-loader\\worker.js'
  ]
}
```
## Describe the bug
I have project with lots of dynamic modules, that recompilation time was too long, looked through code and found that "babelMultiThread" experimental option enables cache-loader (which i really need).

So i enabled it while using next 9.3.3, it worked. I upgraded to latest canary - it broke. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Do any project with latest canary next.js
2. Enable babelMultiThread
```
 experimental: { babelMultiThread: true },
```
in next.config.js
3. Start dev version

## Expected behavior

It works, like in nextJS 9.3.3

## System information

- OS: Widnows 10
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: ^9.3.7-canary.12
- Version of Node.js: v12.16.3

**Comment by timneutkens** [comment] 2020-05-06 09:08
Feel free to investigate and send a PR to fix it.

**Comment by khades** [comment] 2020-05-06 10:06
New NCC system seem to miss files from "thread-worker" library, while copying "worker.js" itself.

worker.js contains require, that is not copied.

![image](https://user-images.githubusercontent.com/4479443/81164814-a0dfa100-8f99-11ea-954c-3c8d72e42df7.png)

**Comment by khades** [comment] 2020-05-06 11:28
https://github.com/zeit/next.js/commit/84b89c8b24a0f4157cbf38a5d1f09162195a325d this pull request misses that files

**Comment by purpletortoise-choi** [comment] 2020-05-08 08:37
Reference below site.
- https://github.com/webpack-contrib/thread-loader/blob/master/src/readBuffer.js

I did test `babelMultiThread` by using above code. 
Run success.

**Comment by khades** [comment] 2020-05-08 08:51
@purpletortoise-choi This file will be removed after next "yarn dev ncc". Partial fix.

**Comment by khades** [comment] 2020-05-26 13:28
@timneutkens i upgraded to 9.4.2, bug is still there

**Comment by timneutkens** [comment] 2020-05-26 13:43
> @timneutkens i upgraded to 9.4.2, bug is still there

For sure since you didn't send a PR 👍

**Comment by khades** [comment] 2020-05-26 13:47
@timneutkens ugh, ncc is not suitable for multi-file packages. 

I'll see what can i do, but it seems it needs full rewrite.

**Comment by JanKaifer** [comment] 2022-11-24 09:51
This issue is quite old and I can't easily check if it's still relevant. Could you check with the newest canary and provide a reproduction?

**Comment by timneutkens** [comment] 2022-11-25 12:59
This option no longer exists and Babel was superseded by SWC so I'm going to close this issue 👍

**Closed by timneutkens** 2022-11-25 12:59 UTC
Labels: good first issue, please add a complete reproduction
