### ISSUE TITLE
next/image add additional pixels to parent element without a trace

### ISSUE THREAD

**Issue by rayriffy** [vercel/next.js#18911] opened 2020-11-06 21:08 UTC
# Bug report

## Describe the bug

Chrome debugger says that next/image element is an exact square (1st image) but parent element have additional 6px adds up without a trace (2nd image).

This only happens in `10.0.1` not `10.0.0`

<img width="1412" alt="Screen Shot 2020-11-07 at 5 59 00" src="https://user-images.githubusercontent.com/22584594/98414589-033b6a80-20bf-11eb-9b4f-c09b9433a554.png">

<img width="1423" alt="Screen Shot 2020-11-07 at 5 59 10" src="https://user-images.githubusercontent.com/22584594/98414623-0fbfc300-20bf-11eb-8a1a-0dcface5b447.png">

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Checkout [sekai-next](https://github.com/rayriffy/sekai-next) at commit https://github.com/rayriffy/sekai-next/commit/f3bbdbec427b9a028dbbf6c2904403b0a93f2d46
2. `yarn dev` or https://sekai-next-kcv87uh9y.vercel.app/
3. Go to `/music` or click at **Music** tab on navigation
4. Happy debugging

## Expected behavior

This is captured when I revert to `next@10.0.0`

<img width="858" alt="Screen Shot 2020-11-07 at 6 07 10" src="https://user-images.githubusercontent.com/22584594/98414877-80ff7600-20bf-11eb-9d58-388d86ad51f2.png">

## System information

- OS: macOS 11
- Browser (if applies): Chrome 86.0.4240.183
- Version of Next.js: 10.0.1
- Version of Node.js: 14.15.0

**Comment by nicholaschiang** [comment] 2020-11-07 00:49
@rayriffy this is a duplicate of #18915. [Here's a temporary fix](https://stackoverflow.com/a/8262649). All you've got to do is add the following styling to the parent wrapper:
```css
.wrapper {
  letter-spacing: 0;
  word-spacing: 0;
  font-size: 0;
}
```

**Closed** 2020-11-09 15:31 UTC
Labels: template: bug

**Comment by P233** [comment] 2021-07-27 20:30
@nicholaschiang Why not add `vertical-align: bottom` to the `inline-block` built-in image wrapper?  No need to style the parent wrapper.

**Comment by balazsorban44** [comment] 2022-01-28 01:27
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
