### ISSUE TITLE
HeadManager cannot handle null-component

### ISSUE THREAD

**Issue by rokinsky** [vercel/next.js#15141] opened 2020-07-13 23:43 UTC
# Bug report

## Describe the bug

Application crashes when `next/head` gets `null`-component as a child.

## To Reproduce

Repository: [next.js-bug-head-null](https://github.com/rokinsky/next.js-bug-head-null)

1. Go to [http://localhost:3000](http://localhost:3000)
2. See error

## Expected behavior

Don't see the error.

## Screenshots

<img width="1009" alt="Screenshot 2020-07-14 at 01 34 05" src="https://user-images.githubusercontent.com/20644874/87363758-8538de00-c57a-11ea-8976-83399d4109d0.png">

## System information

- OS: macOS
- Browser (if applies): chrome
- Version of Next.js: 9.4.4
- Version of Node.js: 14.2.0

## Additional context

N/A

**Comment by zbialecki** [comment] 2021-01-03 17:33
This seems like a duplicate of #13658

**Closed** 2021-01-03 18:14 UTC

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
