### ISSUE TITLE
Error occured in Server Component render when redirect (next/navigation) is used

### ISSUE THREAD

**Issue by joulev** [vercel/next.js#42800] opened 2022-11-11 16:17 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```yml
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
Binaries:
  Node: 18.12.0
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: 7.15.0
Relevant packages:
  next: 13.0.3
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
```

### What browser are you using? (if relevant)

Firefox 106.0.5, macOS Ventura 13.0.1

### How are you deploying your application? (if relevant)

Locally with `next start`

### Describe the Bug

When `redirect` is used in a Server Component, in the production build there is a mysterious error, although the redirection itself works fine:

> An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.

Furthermore, when the root has a `loading.tsx`, the following error will also be shown (well, not that exact error, but a minified error with a URL leading to this decoded text):

> This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in `startTransition`.

### Expected Behavior

No errors.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/joulev/debug/tree/nextjs-redirect-error

### To Reproduce

1. Clone the repository
2. `npm install`
3. `npm run build` (the bug doesn't appear in dev mode)
4. `npm run start`
5. Navigate to `localhost:3000` with the console open
6. It will automatically redirect to `/test` (of course), but in the console the above error message appears.

#### To reproduce the second error

0. Do steps 1–2 above.
1. Add a file `app/loading.tsx` (not available in the repro repo above) with the following content

    ```tsx
    export default function Loading() {
      return <div>Loading</div>;
    }
    ```

2. Repeat steps 3–6 above.

**Comment by kochie** [comment] 2022-11-13 13:26
I'm also getting the same error when used in a client component.

```tsx
'use client'
import { load, trackPageview } from 'fathom-client'
import { useEffect } from 'react'
import { usePathname, useSearchParams } from 'next/navigation'

export default function Fathom() {
  const pathname = usePathname()
  const searchParams = useSearchParams()
  useEffect(() => {
    load('XXXXXXXX', {
      includedDomains: ['example.com'],
      spa: 'auto',
    })

    // Initialize Fathom when the app loads
    // Example: yourdomain.com
    //  - Do not include https://
    //  - This must be an exact match of your domain.
    //  - If you're using www. for your domain, make sure you include that here.
    trackPageview()

    // Record a pageview when route changes
  }, [pathname, searchParams])

  return null
}
```

**Comment by balazsorban44** [comment] 2022-11-14 08:15
I can reproduce the original report and we will investigate, @kochie however, I cannot see this error using your code snippet, could you add a more complete reproduction?

**Comment by balazsorban44** [comment] 2022-11-14 08:22
https://github.com/vercel/next.js/issues/42587 might be related. :thinking:

**Comment by kochie** [comment] 2022-11-14 08:45
Yeah, interesting. So it _only_ happens on vercel. When I build locally no problems. So it's probably an issue with the edge runtime. I've got a demo on here https://blogkochieio-git-issue-42800-kochie1.vercel.app/.

This is the error as reported via the functions tab
```
Function Status:200
Edge Status:200
Duration:146.31 ms
Init Duration: N/A
Memory Used:175 MB
ID:syd1::sfo1::z9d8m-1668415417318-7f912b41cd0a
User Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0

2022-11-14T08:43:38.441Z	0f29a352-61d6-41f1-9356-c22f4c38003a	ERROR	[Error: Input file is missing: /var/task/public/images/tags/aaron-burden-y02jEX_B0O0-unsplash.jpg]
```

![image](https://user-images.githubusercontent.com/10809884/201615012-56faa57c-82ae-428e-8aac-cc90a5b62288.png)

**Comment by balazsorban44** [comment] 2022-11-14 09:34
Seems to be a different issue, the link you provided works fine for me. Could you open a separate issue with a linked minimal reproduction of your code? Just remove anything unnecessary so it's easier to debug/verify. :pray:

For the original report, I did some digging and it is a duplicate of https://github.com/vercel/next.js/issues/42556. Basically, you can ignore the console in this case, we will make sure it's not shown as an error.

**Closed by balazsorban44** 2022-11-14 09:34 UTC
Labels: kind: bug, area: app

**Comment by lilingxi01** [comment] 2022-11-21 04:40
It seems like this issue does not exist in local development environment (`dev` command), but it can be reproduced using `start` command (running a built version) locally.
