### ISSUE TITLE
Dynamic Routes not displaying intended page and displaying home page instead

### ISSUE THREAD

**Issue by Harrylever** [vercel/next.js#73822] opened 2024-12-12 00:33 UTC
### Link to the code that reproduces this issue

https://github.com/Harrylever/Vercel-Nextjs-Dynamic-Route-Not-Working

### To Reproduce

1. Start the dev server on local
2. Notice that all clicked links redirect to the intended dynamic-route and navigation works perfectly
3. Open vercel deployment at [https://vercel-nextjs-dynamic-route-not-working.vercel.app/](https://vercel-nextjs-dynamic-route-not-working.vercel.app/)
4. Notice that clicking on any link changes the url but the page remains on the home page

Demo:

https://github.com/user-attachments/assets/049d551e-444f-4a9a-91bd-1c7b3c5d84c2

### Current vs. Expected behavior

Following the steps from the previous section, The deployed vercel application is intended to open the clicked links in the right dynamic route instead of remaining on the home page

### Provide environment information

```bash
Operating System:
  Platform: Linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Kali 6.11.2-1kali1 (2024-10-15) x86_64 GNU/Linux
  Available memory (MB): 15894
  Available CPU cores: 4
Binaries:
  Node: 22.11.0
  npm: 10.9.0
  Yarn: 1.22.22
  pnpm: 9.14.4
  bun: 1.1.38
Relevant Packages:
  next: ^15.1.1-canary.1
  eslint-config-next: 15.1.0
  react: ^19
  react-dom: ^19
  typescript: ^5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Developer Experience, Navigation

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

**Comment by lukahartwig** [comment] 2024-12-13 11:31
In your reproduction you got a [`vercel.json`](https://github.com/Harrylever/Vercel-Nextjs-Dynamic-Route-Not-Working/blob/3c0f8dc97500147ac2a86202d67e0b5e57e8d42c/vercel.json) file that configures Vercel to rewrite all requests to serve `/`. Try removing the config.

I'm going to close the issue since this is likely the cause of the behavior. Feel free to re-open if the issue still persists.

**Closed by lukahartwig** 2024-12-13 11:31 UTC
Labels: bug, Navigation, Developer Experience

**Comment by Harrylever** [comment] 2024-12-14 07:35
Yes removing it fixes the issue. Thanks @lukahartwig
