### ISSUE TITLE
App directory root `not-found.tsx` not compiled to `404.html` when using static export

### ISSUE THREAD

**Issue by ky28059** [vercel/next.js#48227] opened 2023-04-11 04:02 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Static HTML Export (output: "export")

### Link to the code that reproduces this issue

https://github.com/ky28059/ky28059.github.io

### To Reproduce

Run `next build`, then navigate to the 404 page.

### Describe the Bug

Wasn't sure if this qualified as a bug report or feature request, but when running `next build` with a global app-directory 404 page (root `not-found.tsx` page), the generated `404.html` in `/out` is Next's default 404 page and not the `not-found` page.

<img width="658" alt="image" src="https://user-images.githubusercontent.com/60120929/231052811-51fc29c7-9362-476a-be85-720d4eed4267.png">

### Expected Behavior

Because `/app/not-found.tsx` handles unmatched URLs like `/pages/404.tsx` formerly did, it makes sense for its HTML contents to be compiled to the static export's `404.html` instead of being ignored in the build output.

<sub>[NEXT-1392](https://linear.app/vercel/issue/NEXT-1392/app-directory-root-not-foundtsx-not-compiled-to-404html-when-using)</sub>

**Comment by cmoog** [comment] 2023-04-15 14:24
Seeing this as well.

**Comment by moshfrid** [comment] 2023-04-24 00:18
still an issue as of 13.3.1

**Comment by shuding** [comment] 2023-05-02 22:55
Since you can have a 404 page inside pages and a not-found file in app at the same time (and they can conflict), we are storing the not-found page in `.next/server/app/_not-found.html`.

**Comment by cmoog** [comment] 2023-05-03 03:28
> Since you can have a 404 page inside pages and a not-found file in app at the same time (and they can conflict), we are storing the not-found page in `.next/server/app/_not-found.html`.

Looks like it's getting lost in the shuffle during static export then?

**Comment by unleashit** [comment] 2023-05-19 02:18
Same problem as of 13.4.2. Works as expected when running in dev mode, but the 404.html that gets exported is the default black one.

Interestingly, it used to work in production mode when run locally with next start. But in a recent update, it stopping working locally as well. The problem I believe is as mentioned, a not-found.tsx in the app directory root should be exported as 404.html (which is the standard for at least Cloudflare Pages, and probably other hosts).

Have tried the [...not-found] catch-all route trick to call a notFound() function, but (no big surprise) it doesn't work server side on a static site.

**Comment by unleashit** [comment] 2023-05-27 22:41
Still ignoring custom not-found.tsx. 404.js is being exported as the stock 404 page. Any timeline for a fix please?

**Comment by unleashit** [comment] 2023-05-30 07:33
Seem to have solved it for now by creating a 404 page (404 directory, with a page.tsx). Doing that exports it as 404.html, which overrides the default. This hack may not work for everyone, but it works for me since I'm hosting on Cloudflare Pages which routes 404s to 404.html.

**Comment by SaveliiLukash** [comment] 2023-06-09 12:46
Same issue using the app router's `app/not-found.tsx`

`next dev` routes to it correctly
`next build` + `next start` also routes correctly

**Vercel** production and preview builds display the default 404 page, **not** `app/not-found.tsx`

<img width="973" alt="image" src="https://github.com/vercel/next.js/assets/78015938/96b9dd9c-7e2e-4466-a12e-b86e75d782b2">

**Comment by azizoid** [comment] 2023-06-15 00:37
I received 400kb of error logs 
```
MissingStaticPage [Error]: Failed to load static file for page: /404 ENOENT: no such file or directory, open '/var/www/quran.az/.next/server/pages/404.html'
    at /var/www/quran.az/node_modules/next/dist/server/require.js:153:19
    at async loadComponentsImpl (/var/www/quran.az/node_modules/next/dist/server/load-components.js:68:26)
    at async NextNodeServer.findPageComponentsImpl (/var/www/quran.az/node_modules/next/dist/server/next-server.js:762:36)
    at async NextNodeServer.renderErrorToResponseImpl (/var/www/quran.az/node_modules/next/dist/server/base-server.js:1506:30)
    at async pipe.req.req (/var/www/quran.az/node_modules/next/dist/server/base-server.js:1461:30)
    at async NextNodeServer.pipeImpl (/var/www/quran.az/node_modules/next/dist/server/base-server.js:642:25)

```

**Comment by AugustinMauroy** [comment] 2023-06-30 11:22
Hey! I'd be interested in resolving this issue. 
If anyone can just guide me through my first contribution.

**Comment by igolskyi** [comment] 2023-07-06 11:26
Still an issue as of 13.4.7

**Closed** 2023-07-11 07:32 UTC
Labels: template: bug, area: app, linear: next

**Comment by styfle** [comment] 2023-07-12 19:56
@Cretezy This issue was created for the "global app-directory 404 page (root not-found.tsx page)". Please create a new issue with the steps to reproduce the problem you're having.

For example, are you using next.config.js with `output: 'export'` and what other options `trailingSlash: true`, etc?

I think this could work with `trailingSlash: true` since it creates directories but its not clear what the expected behavior would be with `trailingSlash: false`. 

So its best to create a new issue with the steps to reproduce the problem, thanks!
