### ISSUE TITLE
Redirect with basePath is not working

### ISSUE THREAD

**Issue by maxtotheguenther** [vercel/next.js#21958] opened 2021-02-08 10:12 UTC
**What version of Next.js are you using?**

"next": "10.0.5"

**What version of Node.js are you using?**

v12.12.0

**What browser are you using?**

Chrome  88.0.4324.96

**What operating system are you using?**

macOS Catalina 10.15.7

**How are you deploying your application?**

next dev (locally) / next start (production environment)

**Describe the Bug**

Hey guys, 

i noticed a strange behavior when i was working with redirects the other day.

About my problem. I have an application where the route / should be protected. For this I make a check of the token in the function getServerSideProps. If the token is not present I return following redirect object

```
 redirect: {
    destination: "https://example.com/login",
  },
```

Without a basePath configuration in next.config.js the redirect works as intended. But if I configure a basePath in next.config.js

```
 basePath: "/i/admin/startpage",
```

 it adds the destination to the current url during the redirect.

http://localhost:3000/i/admin/startpagehttps://example.com/login

**Expected Behavior**

Should redirect to https://example.com/login

**To Reproduce**

Create plain nextjs project.

Add following next.config.js

```
module.exports = {
  basePath: "/i/admin/startpage",
};

```

Change index.js as follows.

```
export default function Home() {
  return <p>Test</p>;
}

export const getServerSideProps = async () => {
  return {
    redirect: {
      destination: "https://example.com/login",
    },
  };
};
```

**Comment by ijjk** [comment] 2021-09-18 15:48
Hi, this should be fixed in the latest version of Next.js `v11.1.2`, please update and give it a try!

**Closed by ijjk** 2021-09-18 15:48 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
