### ISSUE TITLE
STRIPE WEBHOOK - Cannot access request raw body with Javascript (request vs NextApiRequest)

### ISSUE THREAD

**Issue by dirtybirdnj** [vercel/next.js#60002] opened 2023-12-28 19:53 UTC
### Link to the code that reproduces this issue

https://github.com/dirtybirdnj/next-stripe-webhooks-bug

### To Reproduce

`git clone https://github.com/dirtybirdnj/next-stripe-webhooks-bug.git`
.env.default => .env (populate with stripe keys)
`yarn`
`yarn dev`
`stripe login`
`stripe listen --forward-to localhost:3000/api/webhooks/stripe`
`stripe trigger checkout.session.completed`

### Current vs. Expected behavior

Expected behavior:

I should be able to access the raw http request / buffer to pass to the stripe webhook validation

Actual Behavior:

I am unable in any way to stop Next.js from parsing the raw body. This results in it being impossible to perform the validation step stripe recommends for processing webhooks.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
Binaries:
  Node: 18.17.0
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: 7.18.2
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Middleware / Edge (API routes, runtime), Routing (next/router, next/navigation, next/link), TypeScript (plugin, built-in types)

### Additional context

I have tried several different ways to read from the buffer and everything fails.

I have tried upgrading from Next 13.0.7 to 13.5.6 and finally 14.0.4

It's not possible to access the req.text() function I see in some documented solutions. I believe this is because I'm not getting passed a NextAPIRequest instance, but in fact some sort of more vanilla HTTP request object that does not allow me to access the raw request no matter what I do.

Solutions that DID NOT WORK:
https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/nextjs/pages/api/webhooks.ts (TS not helpful)

https://github.com/vercel/next.js/discussions/13405 (Unable to access req.text(), suspect its because of TS / not being passed NextAPIRequest)

https://medium.com/@levi.schouten.werk/building-a-payment-flow-in-next-js-13-using-stripe-mailsender-and-webhooks-291996bf1b24 (more TS, adapted to JS still didn't work)

https://www.codedaily.io/tutorials/Stripe-Webhook-Verification-with-NextJS (buffer / micro solution, fails because Next is modifying the request DESPITE setting `bodyParser: false`)

Beyond frustrated... having a really awful day because of this. I feel like I've thrown everything at the wall and I can't get past some lack of understanding / information.

**Comment by raullarosa** [comment] 2023-12-28 21:05
Calling the `await buffer(req);` as it is done in the Stripe-node NextJs example does the trick for me which I don't see in your latest checked in version. Maybe log what youre getting after that gets called (before you try to constructEvent).
- https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/nextjs/pages/api/webhooks.ts#L56

I am on version `"next": "^12.2.5"` but i doubt that makes a difference.

**Comment by dirtybirdnj** [comment] 2023-12-29 00:01
@raullarosa Thank you so much for your reply. I tried implementing the `buffer()` function without the typescript stuff but it didn't work as intended.

I've made some more progress by passing the `req` that the `handler()` function gets into a `new NextRequest(req)` and this is DEFINITELY a step forward, but I still can't access the raw body.

One of the other changes I made was moving the file, I suspect something about where the file is may be causing next to not respect the `bodyParser: false` that I'm (attempting) to apply to the route.

Previously it was:
`/src/app/api/webhooks/stripe.js`

Once I changed it to this:
`/src/app/api/webhooks/stripe/route.js`

the GET() and POST() stuff started working as expected, before the route wasn't even getting hit

I would like to know if there's something I can do to test / confirm whether the bodyParser setting is actually working. I have tried commenting it out and running these lines but I don't see any different errors.

https://github.com/dirtybirdnj/next-stripe-webhooks-bug/blob/main/src/app/api/webhooks/stripe/route.js#L15-L31

**Comment by Ehtz** [comment] 2024-04-29 17:17
Any new news on this? [dirtybirdnj](https://github.com/dirtybirdnj)

**Comment by dirtybirdnj** [comment] 2024-04-29 18:03
@Ehtz OH DO I! thank you for reminding me about this it had totally fallen off my radar

This is from my personal project so I don't mind sharing, you'll have to remove some of the unnecessary stuff but there's also a link in the comments up top to the source where I found it.

I was stuck on this for SO LONG and I hope others find it, pass it on!

```
dotenv.config();

import { buffer } from 'micro'
import Cors from 'micro-cors'
import Stripe from 'stripe'
import sgMail from '@sendgrid/mail'
import { updateImageMetadata } from '@/scripts/products/setCloudinaryMetadata'

//FROM
//https://github.com/luvagu/next-stripe-elements/blob/main/pages/api/checkout/webhook.js
//WOW IT WORKS??!

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY, { apiVersion: '2020-08-27', })
const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET
const orderCompleteTemplate = process.env.SENDGRID_ORDER_COMPLETE;
const orderShippedTemplate = process.env.SENDGRID_ORDER_SHIPPED;
const orderReplyEmail = process.env.SENDGRID_FROM_EMAIL;

// Stripe requires the raw body to construct the event.
export const config = {
	api: {
		bodyParser: false,
	},
}

const cors = Cors({
	allowMethods: ['POST', 'HEAD'],
})

const webhookHandler = async (req, res) => {
	if (req.method !== 'POST') {
		return res.status(405).json({ message: 'Method Not Allowed' })
	}

	const buf = await buffer(req)
	const sig = req.headers['stripe-signature']

	let event

	try {
		event = stripe.webhooks.constructEvent(buf.toString(), sig, webhookSecret)
	} catch (err) {
		// On error, log and return the error message.
		console.log(`❌ Error message: ${err.message}`)
		res.status(400).send(`Webhook Error: ${err.message}`)
		return
	}

	// Successfully constructed event.
	console.log('✅ Success:', event.id)

	let paymentIntent

	// Handle the event
	switch (event.type) {
		case 'payment_intent.succeeded':
			paymentIntent = event.data.object
			console.log(`💰 PaymentIntent successful: ${paymentIntent.status}`)
			break
		case 'payment_intent.created':
			paymentIntent = event.data.object
			console.log(`👍 PaymentIntent created: ${paymentIntent.status}`)
			break
		case 'payment_intent.payment_failed':
			paymentIntent = event.data.object
			console.log(
				`❌ PaymentIntent failed: ${paymentIntent.last_payment_error?.message}`
			)
			break
		case 'charge.succeeded':
			paymentIntent = event.data.object
			console.log(`💵 Charge succeeded with id: ${paymentIntent.id}`)
			break
    case 'checkout.session.completed':
        paymentIntent = event.data.object
        const customerEmail = paymentIntent.customer_details.email;
        const itemName = paymentIntent.metadata.itemName;
				const chargeDetails = {
					amount_discount: paymentIntent.total_details.amount_discount,
					amount_shipping: paymentIntent.total_details.amount_shipping,
					amount_tax: paymentIntent.total_details.amount_tax,
					amount_subtotal: paymentIntent.amount_subtotal,
					amount_total: paymentIntent.amount_total,
					created: paymentIntent.created,
					shipping: paymentIntent.shipping
				}

        console.log(`💵 Checkout session completed with id: ${paymentIntent.id}`)

				//TODO finish the workflow for purchasing non-lure products (stickers, stock items)
        //const isLure = (paymentIntent.metadata.serial ? true : false);
        if(!paymentIntent.metadata.cloudID) throw new Error('cannot process webhook without cloudinary asset id')
        //AssetID / CloudID is cloudinary dumb stuff
        //const assetID = paymentIntent.metadata.assetID;

        const assetID = paymentIntent.metadata.assetID;
        const updatedMeta = {
          sold: true,
          stripe: paymentIntent.id,
          soldDate: paymentIntent.created
        }
        const markSold = await updateImageMetadata(assetID, updatedMeta);

        console.log(`product ${itemName} marked sold`, markSold);
        //}

        const emailData = {
          item : itemName,
          itemImage: markSold.secure_url,
					chargeDetails: chargeDetails
        }
				sgMail.setApiKey(process.env.SENDGRID_API_KEY);
        const emailResponse = await sendGridTemplateEmail(customerEmail, orderReplyEmail, orderCompleteTemplate, emailData);
        console.log(emailResponse);
				console.log('checkout complete webhook success!')

        break
		default:
			console.warn(`Unhandled event type ${event.type}`)
			break
	}

	// Return a response to acknowledge receipt of the event.
	res.status(200).json({ received: true })
}

function formatUnixTimestamp(unixTimestamp) {
	const date = new Date(unixTimestamp * 1000);
	const year = date.getFullYear();
	const month = String(date.getMonth() + 1).padStart(2, '0');
	const day = String(date.getDate()).padStart(2, '0');
	const hours = String(date.getHours()).padStart(2, '0');
	const minutes = String(date.getMinutes()).padStart(2, '0');
	const weekday = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'][date.getDay()];
	//return `${weekday}, ${year}-${month}-${day} ${hours}:${minutes}:${seconds}.${milliseconds}`;
	return `${weekday}, ${day}/${month}/${year} ${hours}:${minutes}`;
}

async function sendGridTemplateEmail(toEmail,fromEmail, templateID, data) {
  var msg = {
      to: toEmail,
			bcc: fromEmail,
      from: fromEmail,
      templateId: templateID,
      dynamic_template_data: {
          item: data.item,
          itemImage: data.itemImage,
					subtotal: (parseInt(data.chargeDetails.amount_subtotal) / 100),
					total: (parseInt(data.chargeDetails.amount_total) / 100),
					created: formatUnixTimestamp(data.chargeDetails.created),
					shipping: data.chargeDetails.shipping
      },
  };

	if(data.chargeDetails.amount_subtotal != data.chargeDetails.amount_total) msg.dynamic_template_data.tax = (parseInt(data.chargeDetails.amount_tax) / 100);

  try {
      const response = await sgMail.send(msg);
      console.log('Email sent successfully');
      return response;
  } catch (error) {
      console.error('Error sending email:', error);
  }
}

export default cors(webhookHandler)
```

**Comment by Ehtz** [comment] 2024-04-29 18:14
> @Ehtz OH DO I! thank you for reminding me about this it had totally fallen off my radar
> 
> This is from my personal project so I don't mind sharing, you'll have to remove some of the unnecessary stuff but there's also a link in the comments up top to the source where I found it.
> 
> I was stuck on this for SO LONG and I hope others find it, pass it on!
> 
> ```
> dotenv.config();
> 
> import { buffer } from 'micro'
> import Cors from 'micro-cors'
> import Stripe from 'stripe'
> import sgMail from '@sendgrid/mail'
> import { updateImageMetadata } from '@/scripts/products/setCloudinaryMetadata'
> 
> //FROM
> //https://github.com/luvagu/next-stripe-elements/blob/main/pages/api/checkout/webhook.js
> //WOW IT WORKS??!
> 
> const stripe = new Stripe(process.env.STRIPE_SECRET_KEY, { apiVersion: '2020-08-27', })
> const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET
> const orderCompleteTemplate = process.env.SENDGRID_ORDER_COMPLETE;
> const orderShippedTemplate = process.env.SENDGRID_ORDER_SHIPPED;
> const orderReplyEmail = process.env.SENDGRID_FROM_EMAIL;
> 
> // Stripe requires the raw body to construct the event.
> export const config = {
> 	api: {
> 		bodyParser: false,
> 	},
> }
> 
> const cors = Cors({
> 	allowMethods: ['POST', 'HEAD'],
> })
> 
> const webhookHandler = async (req, res) => {
> 	if (req.method !== 'POST') {
> 		return res.status(405).json({ message: 'Method Not Allowed' })
> 	}
> 
> 	const buf = await buffer(req)
> 	const sig = req.headers['stripe-signature']
> 
> 	let event
> 
> 	try {
> 		event = stripe.webhooks.constructEvent(buf.toString(), sig, webhookSecret)
> 	} catch (err) {
> 		// On error, log and return the error message.
> 		console.log(`❌ Error message: ${err.message}`)
> 		res.status(400).send(`Webhook Error: ${err.message}`)
> 		return
> 	}
> 
> 	// Successfully constructed event.
> 	console.log('✅ Success:', event.id)
> 
> 	let paymentIntent
> 
> 	// Handle the event
> 	switch (event.type) {
> 		case 'payment_intent.succeeded':
> 			paymentIntent = event.data.object
> 			console.log(`💰 PaymentIntent successful: ${paymentIntent.status}`)
> 			break
> 		case 'payment_intent.created':
> 			paymentIntent = event.data.object
> 			console.log(`👍 PaymentIntent created: ${paymentIntent.status}`)
> 			break
> 		case 'payment_intent.payment_failed':
> 			paymentIntent = event.data.object
> 			console.log(
> 				`❌ PaymentIntent failed: ${paymentIntent.last_payment_error?.message}`
> 			)
> 			break
> 		case 'charge.succeeded':
> 			paymentIntent = event.data.object
> 			console.log(`💵 Charge succeeded with id: ${paymentIntent.id}`)
> 			break
>     case 'checkout.session.completed':
>         paymentIntent = event.data.object
>         const customerEmail = paymentIntent.customer_details.email;
>         const itemName = paymentIntent.metadata.itemName;
> 				const chargeDetails = {
> 					amount_discount: paymentIntent.total_details.amount_discount,
> 					amount_shipping: paymentIntent.total_details.amount_shipping,
> 					amount_tax: paymentIntent.total_details.amount_tax,
> 					amount_subtotal: paymentIntent.amount_subtotal,
> 					amount_total: paymentIntent.amount_total,
> 					created: paymentIntent.created,
> 					shipping: paymentIntent.shipping
> 				}
> 
>         console.log(`💵 Checkout session completed with id: ${paymentIntent.id}`)
> 
> 				//TODO finish the workflow for purchasing non-lure products (stickers, stock items)
>         //const isLure = (paymentIntent.metadata.serial ? true : false);
>         if(!paymentIntent.metadata.cloudID) throw new Error('cannot process webhook without cloudinary asset id')
>         //AssetID / CloudID is cloudinary dumb stuff
>         //const assetID = paymentIntent.metadata.assetID;
> 
>         const assetID = paymentIntent.metadata.assetID;
>         const updatedMeta = {
>           sold: true,
>           stripe: paymentIntent.id,
>           soldDate: paymentIntent.created
>         }
>         const markSold = await updateImageMetadata(assetID, updatedMeta);
> 
>         console.log(`product ${itemName} marked sold`, markSold);
>         //}
> 
>         const emailData = {
>           item : itemName,
>           itemImage: markSold.secure_url,
> 					chargeDetails: chargeDetails
>         }
> 				sgMail.setApiKey(process.env.SENDGRID_API_KEY);
>         const emailResponse = await sendGridTemplateEmail(customerEmail, orderReplyEmail, orderCompleteTemplate, emailData);
>         console.log(emailResponse);
> 				console.log('checkout complete webhook success!')
> 
>         break
> 		default:
> 			console.warn(`Unhandled event type ${event.type}`)
> 			break
> 	}
> 
> 	// Return a response to acknowledge receipt of the event.
> 	res.status(200).json({ received: true })
> }
> 
> function formatUnixTimestamp(unixTimestamp) {
> 	const date = new Date(unixTimestamp * 1000);
> 	const year = date.getFullYear();
> 	const month = String(date.getMonth() + 1).padStart(2, '0');
> 	const day = String(date.getDate()).padStart(2, '0');
> 	const hours = String(date.getHours()).padStart(2, '0');
> 	const minutes = String(date.getMinutes()).padStart(2, '0');
> 	const weekday = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'][date.getDay()];
> 	//return `${weekday}, ${year}-${month}-${day} ${hours}:${minutes}:${seconds}.${milliseconds}`;
> 	return `${weekday}, ${day}/${month}/${year} ${hours}:${minutes}`;
> }
> 
> async function sendGridTemplateEmail(toEmail,fromEmail, templateID, data) {
>   var msg = {
>       to: toEmail,
> 			bcc: fromEmail,
>       from: fromEmail,
>       templateId: templateID,
>       dynamic_template_data: {
>           item: data.item,
>           itemImage: data.itemImage,
> 					subtotal: (parseInt(data.chargeDetails.amount_subtotal) / 100),
> 					total: (parseInt(data.chargeDetails.amount_total) / 100),
> 					created: formatUnixTimestamp(data.chargeDetails.created),
> 					shipping: data.chargeDetails.shipping
>       },
>   };
> 
> 	if(data.chargeDetails.amount_subtotal != data.chargeDetails.amount_total) msg.dynamic_template_data.tax = (parseInt(data.chargeDetails.amount_tax) / 100);
> 
>   try {
>       const response = await sgMail.send(msg);
>       console.log('Email sent successfully');
>       return response;
>   } catch (error) {
>       console.error('Error sending email:', error);
>   }
> }
> 
> export default cors(webhookHandler)
> ```

Thank you for the share, glad it has been resolved for you!

**Comment by kisshan13** [comment] 2024-11-21 15:04
I am using next js 14.2.3 and using the `export const config` method to get raw request body. But the problem is when i am building it giving me this error :

```
> Build error occurred
Error: Page config in E:\licenseing\app.betide.studio\src\app/api/webhook/stripe/route.ts is deprecated. Replace `export const config=…` with the following:
Visit https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config for more information.
    at getPageStaticInfo (E:\licenseing\app.betide.studio\node_modules\next\dist\build\analysis\get-page-static-info.js:425:27)
    at async getStaticInfoIncludingLayouts (E:\licenseing\app.betide.studio\node_modules\next\dist\build\entries.js:108:28)
    at async E:\licenseing\app.betide.studio\node_modules\next\dist\build\entries.js:411:32
    at async Promise.all (index 102)
    at async Promise.all (index 0)
    at async createEntrypoints (E:\licenseing\app.betide.studio\node_modules\next\dist\build\entries.js:551:5)
    at async Span.traceAsyncFn (E:\licenseing\app.betide.studio\node_modules\next\dist\trace\trace.js:154:20)
    at async webpackBuildImpl (E:\licenseing\app.betide.studio\node_modules\next\dist\build\webpack-build\impl.js:104:25)
    at async Object.workerMain (E:\licenseing\app.betide.studio\node_modules\next\dist\build\webpack-build\impl.js:326:20) {
  type: 'Error'
}
```

```ts
export const config: NextConfig = {
  api: {
    bodyParser: false,
  },
};

```

**Comment by ztanner** [comment] 2024-11-28 00:38
Glad you were able to get it working!

For that configuration error, it's because `bodyParser` isn't a necessary configuration option in app router, it was only used in pages router. In app router, to read the request body, you can use the standard Web APIs.

**Closed by ztanner** 2024-11-28 00:38 UTC
Labels: bug, Navigation, TypeScript, Runtime
