### ISSUE TITLE
next lint not working

### ISSUE THREAD

**Issue by laclance** [vercel/next.js#38138] opened 2022-06-29 03:42 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

0 verbose cli /home/lance/.nvm/versions/node/v14.19.1/bin/node /home/lance/.nvm/versions/node/v14.19.1/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@8.10.0
2 info using node@v14.19.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/home/lance/.nvm/versions/node/v14.19.1/lib/node_modules/npm/npmrc Completed in 16ms
6 timing config:load:builtin Completed in 16ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/lance/nextjs-eslint/.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/lance/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/lance/.nvm/versions/node/v14.19.1/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 27ms
19 timing npm:load:configload Completed in 28ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm exec next info
23 verbose argv "exec" "--yes" "false" "--" "next" "info"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 2ms
26 timing npm:load:display Completed in 4ms
27 verbose logfile logs-max:10 dir:/home/lance/.npm/_logs
28 verbose logfile /home/lance/.npm/_logs/2022-06-29T03_40_33_537Z-debug-0.log
29 timing npm:load:logFile Completed in 5ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 42ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 timing arborist:ctor Completed in 2ms
36 http fetch GET 200 https://registry.npmjs.org/next 23586ms (cache miss)
37 timing arborist:ctor Completed in 0ms
38 timing command:exec Completed in 23756ms
39 verbose stack Error: canceled
39 verbose stack     at exec (/home/lance/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:177:17)
39 verbose stack     at async module.exports (/home/lance/.nvm/versions/node/v14.19.1/lib/node_modules/npm/lib/cli.js:78:5)
40 verbose cwd /home/lance/nextjs-eslint
41 verbose Linux 5.13.0-51-generic
42 verbose node v14.19.1
43 verbose npm  v8.10.0
44 error canceled
45 verbose exit 1
46 timing npm Completed in 24817ms
47 verbose code 1
48 error A complete log of this run can be found in:
48 error     /home/lance/.npm/_logs/2022-06-29T03_40_33_537Z-debug-0.log

### Describe the Bug

I'm confused as to why there is a next lint command if it does not work.
Running yarn lint shows no errors but yarn build shows errors and can also see errors in vscode and the browser.

### Expected Behavior

running lint script should show errors

### Link to reproduction

https://github.com/laclance/nextjs-eslint

### To Reproduce

`yarn && yarn lint`

**Comment by mlarcher** [comment] 2022-06-29 09:04
I have a passing build, but stray 'console.log' which are forbidden by eslint are not seen by `next lint`. I replaced it with `eslint .` for now in the package.json, but something is definitely broken with this feature.

**Comment by cnotethegr8** [comment] 2022-06-29 11:51
I'm coming across the same issue. I created a [sample project](https://github.com/cnotethegr8/nextjs-lint-issue) where you can see that,
* `yarn lint` (`next lint`) shows no issues
* `yarn eslint` (`eslint ./`) shows an issue

**Comment by balazsorban44** [comment] 2022-06-30 09:06
I looked at the OP's reproduction, and I could not find an issue. Our default `next/core-web-vitals` is supposed to catch Next.js related issues, if you want to warn about unused variables, you can try extending your ESLint configuration, eg.:

```js
// .eslintrc.json
{ "extends": ["next/core-web-vitals", "eslint:recommended"] }
```

Please see the docs: https://nextjs.org/docs/basic-features/eslint#additional-configurations


@cnotethegr8 from our docs:

> By default, Next.js will run ESLint for all files in the pages/, components/, and lib/ directories. However, you can specify which directories using the dirs option in the eslint config in next.config.js for production builds

So in your case, since you put the error in the `temp` folder, you need to add it to `dirs` like so:

```js
// next.config.js

module.exports = {
  // ...
  eslint: {
    dirs: ["temp", "pages"]
  }
}
```

https://nextjs.org/docs/basic-features/eslint#linting-custom-directories-and-files


So I'm closing this as it works as intended, thanks!

**Closed by balazsorban44** 2022-06-30 09:06 UTC
Labels: area: ESLint

**Comment by laclance** [comment] 2022-07-02 05:11
OK thanks @balazsorban44 I am using @typescript-eslint/recommended and was still not seeing errors, however errors starting   appearing again and I didn't change anything so I don't know what went wrong.

**Comment by balazsorban44** [comment] 2022-07-04 11:39
Good to know that it works now! Your reproduction did not have `@typescript-eslint/recommended`, so it's hard to tell what the issue was. Maybe VSCode acted up and needed a restart or something similar. Feel free to open a new issue if it appears again, with an updated reproduction!

**Comment by laclance** [comment] 2022-07-04 15:29
Yeah sure thanks, I didn't think it was typescript related.
