### ISSUE TITLE
Global SCSS not working 

### ISSUE THREAD

**Issue by tufail** [vercel/next.js#45052] opened 2023-01-19 16:11 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

inversion less than 13 it was working , but after updating next.js to ^13.0 it is failing to build in dev mode.
```
import '../styles.scss';

export default function App({ Component, pageProps }) {
  return <Component {...pageProps} />;
}
```

error for next.js 13 
```
 unhandledRejection: Error: Cannot find module 'D:\nextjs\node_modules\next\dist\compiled\sass-loader/fibers.js'
.
.
.
.
  code: 'MODULE_NOT_FOUND'
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Script optimization (next/script)

### Link to the code that reproduces this issue

yarn run dev

### To Reproduce

change  version from 12 to 13 ..it is failing to run yarn run dev script

### Describe the Bug

Global SCSS not loading

### Expected Behavior

it should build if we are using next.js 13 and SASS package

**Comment by mmeigs** [comment] 2023-01-19 21:03
@tufail Had the same problem here. I rolled back just to v13.1.1 and everything's fine. 

Must be a bug in the update a week ago.

**Comment by kevintap-idemia** [comment] 2023-01-20 01:13
I'm seeing the same thing, an import of global scss styles is causing the next app to fail to start. There is no error or other output seen, the app just silently fails to start.

Commenting/uncommenting the following line in my pages/_app.tsx file causes this to work/break.

`import '../styles/globals.scss';`

This does not happen with 13.1.1, but does happen with 13.1.2.

**Comment by SeanRenet** [comment] 2023-01-20 02:43
Same issue.  This is a breaking change for me.  I rolled back to 12.3.  to get sass to work again.  I will try 13.1.1

**Comment by samsullivan** [comment] 2023-01-21 07:23
+1; I wasted a lot of time on this one being new to Next.js, but reverting from 13.1.4 to 13.1.1 worked.

**Comment by afief** [comment] 2023-01-21 09:43
+1 I have the same issue and reverting to 13.1.1 works for me as well.

**Comment by raRaRa** [comment] 2023-01-21 11:32
+1 Same issue.

**Comment by cburrows85** [comment] 2023-01-21 15:39
Can also confirm. 13.1.4 broken. 13.1.1 works. Glad it wasn't just me.

**Comment by SparkTech-BSS** [comment] 2023-01-22 11:55
I believe you are putting the --turbo flag in the package.json in the dev script

I didn't have this problem, Next.js v13.1.4

**Comment by raRaRa** [comment] 2023-01-22 12:06
I don't have the turbo flag in my case.

**Comment by SparkTech-BSS** [comment] 2023-01-22 12:15
Weird, this is my package.json file

```{
  "name": "cinemax",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@next/font": "13.1.3",
    "@radix-ui/react-checkbox": "^1.0.1",
    "@radix-ui/react-dropdown-menu": "^2.0.2",
    "@radix-ui/react-popover": "^1.0.3",
    "@radix-ui/react-radio-group": "^1.1.1",
    "@radix-ui/react-select": "^1.2.0",
    "@radix-ui/react-switch": "^1.0.1",
    "@radix-ui/react-tabs": "^1.0.2",
    "@radix-ui/react-toast": "^1.1.2",
    "@radix-ui/react-toggle-group": "^1.0.2",
    "@radix-ui/react-tooltip": "^1.0.3",
    "@types/node": "18.11.18",
    "@types/react": "18.0.27",
    "@types/react-dom": "18.0.10",
    "eslint": "8.32.0",
    "eslint-config-next": "13.1.3",
    "framer-motion": "^8.5.0",
    "immer": "^9.0.18",
    "next": "13.1.4",
    "qrcode.react": "^3.1.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-icons": "^4.7.1",
    "react-toastify": "^9.1.1",
    "sass": "^1.57.1",
    "swiper": "^8.4.6",
    "typescript": "4.9.4"
  },
  "devDependencies": {
    "@types/react-modal": "^3.13.1"
  }
}```

**Comment by SparkTech-BSS** [comment] 2023-01-22 12:16
@raRaRa  Are you using the new app directory format? I'm still in the old...

**Comment by raRaRa** [comment] 2023-01-22 12:37
I'm using the old one, `pages`. I tried setting up clean NextJS project and it started to fail immediately after importing a SCSS file, e.g. 

`import styles from "./index.module.scss";`

**Comment by SparkTech-BSS** [comment] 2023-01-22 12:42
@raRaRa  
Did you install sass?

**Comment by raRaRa** [comment] 2023-01-22 12:42
@SparkTech-BSS How are you importing and using SCSS files in your components?

Yes I have sass installed

`"sass": "^1.57.1",`

**Comment by SparkTech-BSS** [comment] 2023-01-22 12:44
![image](https://user-images.githubusercontent.com/77341205/213916479-14112533-0223-44cf-950a-a4c8d1b534d6.png)

@raRaRa

**Comment by SparkTech-BSS** [comment] 2023-01-22 12:45
![image](https://user-images.githubusercontent.com/77341205/213916495-9a0a0480-b6c0-49bf-abc2-7557a30d2f43.png)
@raRaRa

**Comment by raRaRa** [comment] 2023-01-22 12:48
@SparkTech-BSS Ok the only difference from me is that I don't have a src folder. I'll try adding src folder to see if that changes anything.

**Comment by SparkTech-BSS** [comment] 2023-01-22 12:49
Good!

**Comment by raRaRa** [comment] 2023-01-22 12:54
I did another fresh NextJS install, version 13.1.4, with a `src` folder, and the issue is still there. Could you try doing the same? 

1. `npx create-next-app@latest test123`

2. `yarn add sass`

3. In the pages folder add `index.module.scss` with a simple style, import it in `index.tsx` and reference the style.

**Comment by ionpetro** [comment] 2023-01-24 09:42
Same here

**Comment by Paatrox** [comment] 2023-01-24 16:50
Same here, `npm run build` is hanging forever also on the version 13.1.5 (I don't use react-rainbow-components). For me last working version is 13.1.1

**Comment by raRaRa** [comment] 2023-01-28 12:20
Seems to be working on 13.1.6 :) Can anyone else confirm?

**Comment by samsullivan** [comment] 2023-01-28 22:44
> Seems to be working on 13.1.6 :) Can anyone else confirm?

13.1.6 is working for me w/in Vercel; but, my dev builds are hanging locally (it never starts compiling after loading environment). 

```
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /path/to/project/.env.local
```

I feel like this is user error, though, since I'm new to Next.js and pushing it to a Vercel deployment works.

**Comment by cburrows85** [comment] 2023-01-28 23:04
Wish I could say 13.1.6 works for me locally, but it doesn't. Still hanging but reverting to 13.1.1 works.

**Comment by kejianfeng** [comment] 2023-01-29 09:30
+1,  13.1.6 broken,  and reverting to 13.1.1 works for me as well.

**Comment by Paatrox** [comment] 2023-01-30 13:34
For me version 13.1.6 keeps hanging on `npm run build.` Reverting to 13.1.1 works.

**Comment by eduardochiaro** [comment] 2023-01-30 16:38
Not sure if is good information, but i having the same issue. `13.1.6` hanging on `npm run build` and `npm run dev`. However I have 2 laptop and the second one did not have the issue. only difference is that the one where it hangs use `Node 14`,the other `16`. I switch to `16` and `18` to test and it works fine, revert to `node 14` make the issue return.

**Comment by tomgreeEn** [comment] 2023-01-30 16:46
> Not sure if is good information, but i having the same issue. `13.1.6` hanging on `npm run build` and `npm run dev`. However I have 2 laptop and the second one did not have the issue. only difference is that the one where it hangs use `Node 14`,the other `16`. I switch to `16` and `18` to test and it works fine, revert to `node 14` make the issue return.

Can confirm that updating from Node 14->18 also fixed this issue for me.

**Comment by samsullivan** [comment] 2023-01-30 19:09
Yup, same. That explained why my Vercel builds worked; forgot to setup my `.nvmrc` in this new project.

**Comment by raRaRa** [comment] 2023-01-30 19:11
Ahh that was it, since I was previously using node 14.

**Comment by Trallp** [comment] 2023-02-01 12:27
I think this is the breaking commit https://github.com/vercel/next.js/commit/12bfabd179838918560e058ddf0b5213e87b66c1

**Comment by xxiaobai-ran** [comment] 2023-02-02 02:21
+1, Node 14->16 also fixed this issue for me.

**Comment by kevintap-idemia** [comment] 2023-02-02 02:33
I can confirm the same, these build issues go away with node v16.

However, that said, this gives me significant stability concerns that bumping up a patch release of nextjs would break things this much and require an upgrade of the node runtime. The upgrade guide indicates that node v14.6.0 is the minimum node version supported (https://nextjs.org/docs/upgrading), so I think this underlying issue still needs to be addressed rather than punting and just declaring end of support for node v14.

**Comment by dmitry-js** [comment] 2023-02-03 21:08
Same here. No matter what npm version is

**Comment by thaddydore** [comment] 2023-02-08 06:58
Upgrade your node version and the issue will disappear. 

Node 18.13.0 fixed mine after long hours of trooleshooting.

**Comment by Trallp** [comment] 2023-02-09 06:54
Still an error with 13.1.7-canary.8

**Comment by cburrows85** [comment] 2023-02-11 19:13
Working for me now after upgrading node. Next v13.1.6 and Node v18.14.0. Good find. Thank you.

**Comment by alexdevio** [comment] 2023-02-17 23:33
Can confirm that upgrading from node v14 -> v18 also fixed this issue for me. 🔥🔥🔥

Btw thank you for the answers, was struggling to find a fix for this... they always mess up the dependencies 😅

**Comment by alexdevio** [comment] 2023-02-17 23:34
> Not sure if is good information, but i having the same issue. `13.1.6` hanging on `npm run build` and `npm run dev`. However I have 2 laptop and the second one did not have the issue. only difference is that the one where it hangs use `Node 14`,the other `16`. I switch to `16` and `18` to test and it works fine, revert to `node 14` make the issue return.

Can confirm that upgrading from node **v14 -> v18** also fixed this issue for me. 🔥🔥🔥

Btw thank you for the answers, was struggling to find a fix for this... they always mess up the dependencies 😅

**Comment by reymondar** [comment] 2023-03-02 12:58
I confirm switching from Node 14 to 18 and it fixed it worked. Highly recommend checking your version of Node. 

Thanks!

**Comment by AdamDavidson1** [comment] 2023-03-14 20:06
After digging into the sass-loader, I have discovered an undocumented setting that addresses the issue. It seems that sass-loader conditionally detects the node version and choses to load fibers. The problem is there is a validation step checking for fibers when it was purposefully not loaded.

To turn off fibers completely for lower versions of nodejs you will need to adjust your sassOptions in next.config.js

```
const path = require('path')

module.exports = {
  sassOptions: {
    fiber: false,
    includePaths: [path.join(__dirname, 'styles')],
  },
}
```

**Comment by Paatrox** [comment] 2023-03-14 20:34
Thank You @AdamDavidson1 your solution works. I couldn't update node from 14 to 18 on production (competencies of another team) and stuck on next.js 13.1.1. Now my project run on next.js 12.2.4. Thx

**Comment by Badestrand** [comment] 2023-03-18 04:15
Just adding that my builds worked locally (both `next dev` and `next build`) but it failed on Vercel's infrastructure with the error given in the OP. The fix by @AdamDavidson1 in the next.config.js file fixed it.

**Comment by wayaneco** [comment] 2023-03-20 05:02
> 

This works on me. Thanks!

**Comment by wayaneco** [comment] 2023-03-20 05:03
> After digging into the sass-loader, I have discovered an undocumented setting that addresses the issue. It seems that sass-loader conditionally detects the node version and choses to load fibers. The problem is there is a validation step checking for fibers when it was purposefully not loaded.
> 
> To turn off fibers completely for lower versions of nodejs you will need to adjust your sassOptions in next.config.js
> 
> ```
> const path = require('path')
> 
> module.exports = {
>   sassOptions: {
>     fiber: false,
>     includePaths: [path.join(__dirname, 'styles')],
>   },
> }
> ```

This works on me ! Thanks @AdamDavidson1

**Comment by pioz** [comment] 2023-03-21 15:16
I got the same problem with node v18.13.0 and nextjs v13.2.4. On my local machine all works (also `npm run build`), but when I deploy on Vercel I got this error:

```
Expand 27 Lines
--
16:13:33.493 | unhandledRejection Error: Cannot find module '/vercel/path0/node_modules/next/dist/compiled/sass-loader/fibers.js'
16:13:33.494 | at webpackEmptyContext (/vercel/path0/node_modules/next/dist/compiled/sass-loader/cjs.js:1:11235)
16:13:33.494 | at getSassOptions (/vercel/path0/node_modules/next/dist/compiled/sass-loader/cjs.js:1:5586)
16:13:33.494 | at Object.loader (/vercel/path0/node_modules/next/dist/compiled/sass-loader/cjs.js:1:2683)
16:13:33.494 | at LOADER_EXECUTION (/vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4134)
16:13:33.495 | at runSyncOrAsync (/vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4145)
16:13:33.495 | at iterateNormalLoaders (/vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5782)
16:13:33.495 | at /vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5426
16:13:33.495 | at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:395994
16:13:33.495 | at eval (eval at create (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:13:28771), <anonymous>:14:1)
16:13:33.495 | at /vercel/path0/node_modules/next/dist/build/webpack/plugins/profiling-plugin.js:111:29 {
16:13:33.495 | code: 'MODULE_NOT_FOUND'
16:13:33.495 | }
16:13:33.521 | Error: Command "npm run build" exited with 1
16:13:33.842 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1
```

**Comment by monsieurnebo** [comment] 2023-03-26 11:38
Updating Node version (from `16.x` to `18.x`) did the job as well for me.

**Comment by Saravanakumar96** [comment] 2023-04-01 07:04
Node version update has solved the issue for me.. I used the node standard version of 18.15.0.. Thanks! @monsieurnebo

**Comment by amrutapawar25** [comment] 2023-04-01 16:39
still facing same issue. I am using node v18.15.0, "next": "13.2.4",

**Comment by Saravanakumar96** [comment] 2023-04-03 05:28
Try to downgrade next version from "13.2.4" to "13.2.1". which is worked for me @amrutapawar25

**Comment by joshuatuscan** [comment] 2023-04-04 18:05
> > After digging into the sass-loader, I have discovered an undocumented setting that addresses the issue. It seems that sass-loader conditionally detects the node version and choses to load fibers. The problem is there is a validation step checking for fibers when it was purposefully not loaded.
> > To turn off fibers completely for lower versions of nodejs you will need to adjust your sassOptions in next.config.js
> > ```
> > const path = require('path')
> > 
> > module.exports = {
> >   sassOptions: {
> >     fiber: false,
> >     includePaths: [path.join(__dirname, 'styles')],
> >   },
> > }
> > ```
> 
> @AdamDavidson1 This seems to work for me as well!

I had to do this and drop my next version down to 13.2.1 for this error to stop happening on Vercel deploy.

**Comment by yakuznecov** [comment] 2023-04-13 19:42
> 

thank you, kind man, it helped

**Comment by yakuznecov** [comment] 2023-04-13 19:43
> I got the same problem with node v18.13.0 and nextjs v13.2.4. On my local machine all works (also `npm run build`), but when I deploy on Vercel I got this error:
> 
> ```
> Expand 27 Lines
> --
> 16:13:33.493 | unhandledRejection Error: Cannot find module '/vercel/path0/node_modules/next/dist/compiled/sass-loader/fibers.js'
> 16:13:33.494 | at webpackEmptyContext (/vercel/path0/node_modules/next/dist/compiled/sass-loader/cjs.js:1:11235)
> 16:13:33.494 | at getSassOptions (/vercel/path0/node_modules/next/dist/compiled/sass-loader/cjs.js:1:5586)
> 16:13:33.494 | at Object.loader (/vercel/path0/node_modules/next/dist/compiled/sass-loader/cjs.js:1:2683)
> 16:13:33.494 | at LOADER_EXECUTION (/vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4134)
> 16:13:33.495 | at runSyncOrAsync (/vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4145)
> 16:13:33.495 | at iterateNormalLoaders (/vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5782)
> 16:13:33.495 | at /vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5426
> 16:13:33.495 | at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:395994
> 16:13:33.495 | at eval (eval at create (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:13:28771), <anonymous>:14:1)
> 16:13:33.495 | at /vercel/path0/node_modules/next/dist/build/webpack/plugins/profiling-plugin.js:111:29 {
> 16:13:33.495 | code: 'MODULE_NOT_FOUND'
> 16:13:33.495 | }
> 16:13:33.521 | Error: Command "npm run build" exited with 1
> 16:13:33.842 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1
> ```
> 
> My workaround is to add in `next.config.js` these lines:
> 
> ```js
> module.exports = {
>   sassOptions: {
>     fiber: false
>   }
> }
> ```

thank you, kind man, it helped

**Closed** 2023-05-30 22:24 UTC
Labels: template: bug
