### ISSUE TITLE
Canary Linting uses Next.js ESLint version over workspace ESLint

### ISSUE THREAD

**Issue by ljosberinn** [vercel/next.js#23372] opened 2021-03-24 23:15 UTC
### What version of Next.js are you using?

10.0.10-canary.11

### What version of Node.js are you using?

15.6

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

next dev

### Describe the Bug

adding
```js
eslint: {
  dev: true
}
```
enables linting in dev during compilation as expected.

Using a more up to date version than the [next-included ESLint v7.9](https://github.com/vercel/next.js/blob/canary/packages/next/package.json#L86) makes it crash because it doesn't understand newer rules introduced later than v7.9, in my case [`no-nonoctal-decimal-escape`](https://eslint.org/docs/rules/no-nonoctal-decimal-escape) which was introduced in ESLint v7.14.

![image](https://user-images.githubusercontent.com/29307652/112395763-4f4e1b00-8cff-11eb-8897-0a4fe35a53b3.png)

### Expected Behavior

Linting through next uses workspace ESLint version over its own dependency.

### To Reproduce

- enable dev linting in canary
- create a `.eslintrc.js` file (or any other format with adapted code) and add this:
```js
module.exports = {
  rules: {
    'no-nonoctal-decimal-escape': 'warn',
  },
  extends: ['plugin:@next/next/recommended'],
  parser: '@babel/eslint-parser',
  parserOptions: {
    requireConfigFile: false,
    sourceType: 'module',
    babelOptions: {
      presets: ['next/babel'],
    },
  },
};

```
- run `yarn dev`

**Comment by ijjk** [comment] 2021-04-17 16:46
Closing as this was removed in the latest version of Next.js `v10.1.3`

**Closed by ijjk** 2021-04-17 16:46 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
