### ISSUE TITLE
Building a component library with `tsup` that uses `next/image` breaks when one of the components directly renders `Image` since `13.4.8-canary.9`

### ISSUE THREAD

**Issue by rodrigoehlers** [vercel/next.js#52216] opened 2023-07-04 18:38 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
This outputs seems to have issues with pnpm (?) monorepos. I've corrected the versions.
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.13.0
      npm: 9.3.1
      Yarn: 1.22.19
      pnpm: 8.6.0
    Relevant Packages:
      next: 13.4.8 <-- I'm definitely using 13.4.9-canary.1 in the app (apps/web).
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A <-- 5.1.6 across all apps and packages
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/rodrigoehlers/next-13.4.8-tsup-image-issue

or (quicker)

https://stackblitz.com/github/rodrigoehlers/next-13.4.8-tsup-image-issue?file=README.md

### To Reproduce

See README.md in repository.

### Describe the Bug

See README.md in repository.

### Expected Behavior

See README.md in repository.

<sub>[NEXT-1433](https://linear.app/vercel/issue/NEXT-1433/building-a-component-library-with-tsup-that-uses-nextimage-breaks-when)</sub>

**Comment by CobyPear** [comment] 2023-07-05 13:53
We started seeing the same thing with our component library bundled with tsup, but we're still using the Pages router.

**Comment by igordanchenko** [comment] 2023-07-05 16:59
Same issue here. Reproduces under both `app` and `pages` routers.

> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Here is a minimal repro - https://codesandbox.io/p/sandbox/next-52216-7lrx47?file=%2Fpages%2Findex.tsx

**Comment by stevejcox** [comment] 2023-07-05 17:29
Seeing the same thing, however we bundle with babel.

**Comment by Flaxxas** [comment] 2023-07-05 18:54
Facing the same problem

**Comment by altechzilla** [comment] 2023-07-05 19:46
Same issue here. A transpiled ESM component that uses `next/image` will keep breaking things.

**Comment by angeloashmore** [comment] 2023-07-05 22:36
We're having the same issue with `@prismicio/next`, where we provide a `<PrismicNextImage>` component that wraps `next/image`.

`<PrismicNextImage>` source code: https://github.com/prismicio/prismic-next/blob/186d1b37bf8494f380e27c4dc540bcba3c8bf3c9/src/PrismicNextImage.tsx#L145-L155

The component throws the error described above when server rendered. It does not seem to throw the error when a page is refreshed using Fast Refresh after `<PrismicNextImage>` is added to a page.

**Comment by stevejcox** [comment] 2023-07-10 20:31
Still seeing this in 13.4.9

**Comment by angeloashmore** [comment] 2023-07-10 23:21
See this PR for a (hopefully) temporary workaround: https://github.com/prismicio/prismic-next/pull/79

**Comment by colbyfayock** [comment] 2023-07-11 01:33
thanks @angeloashmore that worked perfect for me! https://github.com/colbyfayock/next-cloudinary/pull/229

**Comment by acalinica** [comment] 2023-07-11 05:44
This issue also happens for us with our internal ui kit after upgrading to `13.4.9` from `13.4.7`. More specifically comes from a package called `@chakra-ui/next-js` that exports a wrapped `Image` component built on top of the `next/image` one.

For now, downgrading `next` to `13.4.7` seems to fix the problem.

**Comment by hk86** [comment] 2023-07-22 08:32
Not sure whether this is related, but starting with `13.4.8-canary.9` I see this error when I try to build:
```
Error: Unsupported Server Component type: {...}
@nextapp:     at T (C:\Projects\nextapp\sites\subapp\.next\server\chunks\148.js:40107:11)
@nextapp:     at Xa (C:\Projects\nextapp\sites\subapp\.next\server\chunks\148.js:40168:21)
@nextapp:     at Object.toJSON (C:\Projects\nextapp\sites\subapp\.next\server\chunks\148.js:39982:20)
@nextapp:     at stringify (<anonymous>)
@nextapp:     at hb (C:\Projects\nextapp\sites\subapp\.next\server\chunks\148.js:40378:9)
@nextapp:     at eb (C:\Projects\nextapp\sites\subapp\.next\server\chunks\148.js:40277:29)
@nextapp:     at Timeout._onTimeout (C:\Projects\nextapp\sites\subapp\.next\server\chunks\148.js:40113:16)
@nextapp:     at listOnTimeout (node:internal/timers:569:17)
@nextapp:     at process.processTimers (node:internal/timers:512:7)
```

This happens when I use `html-react-parser` like this:
```
const options = {
  htmlparser2: {
    decodeEntities: true,
    xmlMode: true,
  },
  trim: true,
  replace: (domNode) => {
    if (domNode.attribs && domNode.name === 'img') {
      const props = attributesToProps(domNode.attribs);
      return <Image className={props.class} {...props} />;
    }
    return null;
  },
};

parse(content, options);
```

With  `13.4.8-canary.8` I do not see the error-

**Comment by SukkaW** [comment] 2023-08-12 12:50
I have created a PR #53943 to fix the issue.

**Comment by acalinica** [comment] 2023-10-12 12:24
It's been a few months now and this is really keeping us stuck at v `13.4.7`. how can we prioritise this? It really does not seem like such a hard thing to solve plus @SukkaW proposed a PR with a potential fix.

**Comment by SukkaW** [comment] 2023-10-12 12:43
> It's been a few months now and this is really keeping us stuck at v `13.4.7`. how can we prioritise this? It really does not seem like such a hard thing to solve plus @SukkaW proposed a PR with a potential fix.

My proposed PR doesn't work. It will break the Next.js built-in compiler. We are still investigating this.

Basically, the issue is just https://github.com/webpack/webpack/issues/7973 all over again.

**Comment by styfle** [comment] 2023-10-12 22:34
>  It really does not seem like such a hard thing to solve

PRs are welcome!

> SukkaW proposed a PR with a potential fix.

Indeed that PR caused many more failures as seen in https://github.com/vercel/next.js/pull/53943

I tried a handful of other solutions but they fail to satisfy all constraints:

- internal CJS
- internal ESM
- external CJS
- external ESM
- server components
- client components

Although, modules like `next/image` are not really available externally as ESM since they use require as seen here:

https://unpkg.com/browse/next@13.4.8/image.js

There is however this additional code from `interopClientDefaultExport` added in https://github.com/vercel/next.js/pull/36082

Perhaps @Brooooooklyn might have an idea how to solve this.

Another option is to move `unstable_getImgProps()` into its own module instead of exporting both default and named from the same module. https://github.com/vercel/next.js/pull/51205

Ultimately, I don't think you should be bundling `next/image` with tsup or any other bundler since it relies on internals to Next.js. Instead, your component library can accept either `<img>` or `<Image>` as prop/param.

**Comment by angeloashmore** [comment] 2023-10-13 04:36
> Ultimately, I don't think you should be bundling next/image with tsup or any other bundler since it relies on internals to Next.js. Instead, your component library can accept either <img> or <Image> as prop/param.

Libraries shouldn't be bundling `next/image`, but using it as a peer dependency should be a supported use case, in my opinion. Libraries should be able to wrap `next/image` to provide things like default styling and props.

For example, `@prismicio/next` provides a `<PrismicNextImage>` component that lets developers pass a CMS content field to the component to easily render a `next/image` with the correct URL and dimensions.

I know CJS/ESM interop is challenging, however, and I unfortunately don't know a solution either.

**Comment by styfle** [comment] 2024-01-04 20:32
This has been fixed in PR https://github.com/vercel/next.js/issues/54777 and will be available in the next stable release.

You can try it out today using the canary release with `npm install next@canary`, thanks!

**Closed by styfle** 2024-01-04 20:32 UTC
Labels: kind: bug, area: next/image, area: app, linear: next, area: Module Resolution
