### ISSUE TITLE
Custom 404 error working locally but not on Vercel

### ISSUE THREAD

**Issue by berkaey** [vercel/next.js#25823] opened 2021-06-06 11:07 UTC
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

All

### What operating system are you using?

All

### How are you deploying your application?

Vercel

### Describe the Bug

Locally it works just fine, but when I deployed to Vercel only shows its default 404 page. I can navigate to /404 and see my error page, but somehow it won't redirect/remap correct 404 url.

example 

https://usemagnetiq.com/404
https://usemagnetiq.com/nothing

btw we are using next i18n support, could it be related? 

### Expected Behavior

When a page not found correctly redirect/open 404 or any other error page.

### To Reproduce

maybe this helps next.config.js
```
 headers: async () => {
        return [
          {
            source: "/api/svg/:name",

            headers: [
              {
                key: "Content-Type",
                value: "image/svg+xml",
              },
              {
                key: "Cache-Control",
                value: "s-maxage=10, stale-while-revalidate",
              },
            ],
          },
        ];
      },
      future: {
        // webpack5: true,
      },
      i18n: {
        locales: [
          "en",
          "en_GB",
          "en_SG",
          "en_AU",
          "en_CA",
          "en_IE",
          "en_IN",
          "en_NZ",
          "en_TT",
          "tr",
        ],
        defaultLocale: "en",
      },
      basePath:"",
      devIndicators: {
        autoPrerender: false,
        poweredByHeader: false,
      },
```

**Comment by Arvind644** [comment] 2021-06-07 09:45
Can I work on this issue. And I am new in open source so will you guide me for this

**Comment by ijjk** [comment] 2021-06-30 20:50
Hi, this should be fixed now please re-deploy your application and give it a try!

**Closed by ijjk** 2021-06-30 20:50 UTC
Labels: template: bug

**Comment by berkaey** [comment] 2021-07-09 11:10
@ijjk thank you!

**Comment by pbartkowiak-fandom** [comment] 2021-11-18 13:39
@ijjk hello,

I'm experiencing a very similar issue like @berkaey did. I'm using Next v. 11.1.2. How this bug can be solved?

**Comment by ijjk** [comment] 2021-11-18 15:29
@pbartkowiak-fandom can you provide a reproduction/deployment where you are seeing the custom 404 page not show properly?

**Comment by pbartkowiak-fandom** [comment] 2021-11-18 20:06
> @pbartkowiak-fandom can you provide a reproduction/deployment where you are seeing the custom 404 page not show properly?

Unfortunately, I cannot as our staging environment is in the private network. I can, however, send you a print screen to demonstrate you the issue:

![image](https://user-images.githubusercontent.com/82457200/142488631-87b352b1-6dbc-4117-8e47-ca897980a323.png)

and in the same time, when I enter the 404 url directly, it shows the customized website:

![image](https://user-images.githubusercontent.com/82457200/142488810-95f89999-b28c-4468-9f2e-bbcd360d958b.png)

Please tell If you need any data.

**Comment by ijjk** [comment] 2021-11-18 20:19
It sounds like there is custom handling client side that is rendering the 404 page from `next/error`, without a reproduction/code access it's hard to say exactly where in your code this is being rendered from. This doesn't sound like a Next.js bug though.

**Comment by pbartkowiak-fandom** [comment] 2021-11-19 07:15
I'll look into it, thank you. 

However, I'm surprised that the default 404 page even exists on our instance. Should't it be replaced by our asset? I fail to see any reason behind keeping both default and customized 404 page. An easy solution to this issue would be to just get rid of default 404 page and replace it with the customized version.

**Comment by pbartkowiak-fandom** [comment] 2021-11-19 13:04
I think I made it, eventually. I added:

```javascript
export async function getStaticProps() {
  return {
    props: {},
  };
}
```

to the 404 customized page so it would be generated statically (SSR). Thank you for your hints, they helped me to find the solution.

**Comment by balazsorban44** [comment] 2022-01-27 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
