### ISSUE TITLE
When a next.js project is running within node_modules, webpack cannot load its loaders

### ISSUE THREAD

**Issue by evantahler** [vercel/next.js#11411] opened 2020-03-27 18:21 UTC
# Bug report

When distributing a next.js application though npm, and installing it within `node_modules`,  building pages (`next build`) or using development mode (`next dev`) fail to compile jsx pages.  

## Describe the bug

```
[ error ] ./pages/index.tsx 2:9
Module parse failed: Unexpected token (2:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export default function Index() {
>   return <h1>Hello from Next</h1>;
| }
|
```

The structure of the project in question is:

```
parent_project -> node_modules -> next_app (NEXT_ROOT) / pages
```

## To Reproduce

I've published [`next-subproject-example` (github)](https://github.com/evantahler/next-subproject-example) to npm which is a very simple next.js application with one page and no custom config. 

1. Make a new project with the following `package.json`, which aims to consume `next-subproject-example`

```json
{
  "name": "my-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "cd node_modules/next-subproject-example && npm run dev",
    "build": "cd node_modules/next-subproject-example && npm run prepare"
  },
  "dependencies": {
    "next-subproject-example": "latest"
  },
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^13.9.5",
    "@types/react": "^16.9.26"
  }
}
```

2. `npm install`
3. `npm run dev`

See that there are errors with next building the pages as you visit http://localhost:3000

```
[ error ] ./pages/index.tsx 2:9
Module parse failed: Unexpected token (2:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export default function Index() {
>   return <h1>Hello from Next</h1>;
| }
|
```

4. `npm run build`

See similar errors

## Expected behavior

Jsx pages can be compiled by Next & Webpack.

## Screenshots

N/A

## System information

- OS: OSX
- Browser N/A
- Version of Next.js: 9.3.2 (latest at the time of this writing)

## Additional context

- If you use `npm link` in this module and then `npm link next-subproject-example` in your project, the next project will build properly. This is not the case when installed from NPM. This is a hint that Next might need help locating the proper wepback modules.
- Switching the page from .tsx to .jsx produces the same errors

**Comment by bleonard** [comment] 2020-03-27 21:30
We realize we could have run `next build` and shipped the statically-compiled site in the node_modules, but we are trying to allow our next code to be compiled in with code from other libraries.

When the root includes the next app, this approaches works as demo'd [here](https://github.com/evantahler/next-plugins), but not when the subproject is the one with the next app.

**Comment by evantahler** [comment] 2020-04-02 18:06
A discussion about this topic was started at https://github.com/zeit/next.js/discussions/11606

**Comment by Timer** [comment] 2020-09-12 04:18
Duplicate of #706

**Closed by Timer** 2020-09-12 04:18 UTC

**Comment by balazsorban44** [comment] 2022-01-29 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
