### ISSUE TITLE
getinitialProps does not work correctly in _document.js on a custom server

### ISSUE THREAD

**Issue by kodermax** [vercel/next.js#23743] opened 2021-04-06 13:53 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

custom server

### Describe the Bug

I cant get req and res in getInitialProps in _document.js method when i use custom server

### Expected Behavior

expect to get req, res like in example https://github.com/vercel/next.js/tree/canary/examples/with-react-intl

### To Reproduce

https://github.com/kodermax/demo-fastify-nextjs

**Comment by ijjk** [comment] 2021-04-17 21:23
Hi, in [the above example](https://github.com/kodermax/demo-fastify-nextjs) the pages are automatically statically optimized so `req` is undefined since `_document` will not be called at runtime and instead called at build time which doesn't have a related request. 

I'm going to close this since it appears to be the expected behavior and not a bug.

**Closed by ijjk** 2021-04-17 21:23 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
