### ISSUE TITLE
.env.local crash due to dollar symbol

### ISSUE THREAD

**Issue by AverTry** [vercel/next.js#37207] opened 2022-05-26 09:25 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

win11

### What browser are you using? (if relevant)

Chrome Engine Brave

### Describe the Bug

running the dev script on a new create-next-app
using .env.local

NEXT_PUBLIC_ANALYTICS_ID=abcdefghijk$

Add a Dollar $ symbol anywhere in the value causes

```
error - Failed to load env from C:\Users\admin\Documents\myapp\.env.local TypeError: Cannot read properties of undefined (reading 'split')
    at C:\Users\admin\Documents\myapp\node_modules\@next\env\dist\index.js:1:311
    at Array.reduce (<anonymous>)
    at _interpolate (C:\Users\admin\Documents\myapp\node_modules\@next\env\dist\index.js:1:125)
    at expand (C:\Users\admin\Documents\myapp\node_modules\@next\env\dist\index.js:1:709)
    at processEnv (C:\Users\admin\Documents\myapp\node_modules\@next\env\dist\index.js:1:3638)
    at Module.loadEnvConfig (C:\Users\admin\Documents\myapp\node_modules\@next\env\dist\index.js:1:4443)
    at Object.loadConfig [as default] (C:\Users\admin\Documents\myapp\node_modules\next\dist\server\config.js:40:21)
    at NextServer.loadConfig (C:\Users\admin\Documents\myapp\node_modules\next\dist\server\next.js:114:48)
    at NextServer.getServer (C:\Users\admin\Documents\myapp\node_modules\next\dist\server\next.js:120:39)
    at NextServer.prepare (C:\Users\admin\Documents\myapp\node_modules\next\dist\server\next.js:96:35)
```

### Expected Behavior

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from C:\Users\admin\Documents\env-test\.env.local
wait  - compiling...
event - compiled client and server successfully in 4.7s (170 modules)
````

### To Reproduce

running the dev script on a new create-next-app
using .env.local

NEXT_PUBLIC_ANALYTICS_ID=abcdefghijk$

Add a Dollar $ symbol anywhere in the value causes

**Comment by balazsorban44** [comment] 2022-05-26 10:33
Duplicate of https://github.com/vercel/next.js/issues/36691

**Closed by balazsorban44** 2022-05-26 10:33 UTC
Labels: template: bug
