### ISSUE TITLE
Cannot build with yarn berry or canary versions

### ISSUE THREAD

**Issue by GrefriT** [vercel/next.js#32843] opened 2021-12-27 12:25 UTC
### What version of Next.js are you using?

12.0.7, don't work also on 12.0.8-canary.13

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

Hello. I cannot build, start development, probably do anything with yarn berry or canary. On yarn berry it throw error during build
```
./.yarn/__virtual__/next-virtual-8da6c1de1a/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/normalize-trailing-slash.js
Error: Failed to read source code from C:\(Alex)\nextjs-bug\.yarn\__virtual__\next-virtual-8da6c1de1a\0\cache\next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip\node_modules\next\dist\client\normalize-trailing-slash.js
```

On yarn canary it just stucks on Checking validity of types...
Unplugging react-dom or next itself don't help.

In other project I unplugged react-dom and installed yarn canary and dev start working, but it stucks on Checking validity of types... during build, I tried to disable linting with `eslint.ignoreDuringBuilds` in `next.config.js` it fixed this problem, but this strange error come out after Collecting page data...
```
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received null
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Module.require (node:internal/modules/cjs/loader:998:3)
    at require (node:internal/modules/cjs/helpers:102:18)
    at execMethod (C:\react\****\.yarn\cache\jest-worker-npm-27.0.0-next.5-6f53fab806-d56bfe67cd.zip\node_modules\jest-worker\build\workers\processChild.js:113:16)
    at process.messageListener (C:\react\***\.yarn\cache\jest-worker-npm-27.0.0-next.5-6f53fab806-d56bfe67cd.zip\node_modules\jest-worker\build\workers\processChild.js:46:7)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
### Expected Behavior

It should work in development, build an application

### To Reproduce

1. Clone https://github.com/GrefriT/nextjs-bug
2. `next build` or `next dev`

**Comment by leonitousconforti** [comment] 2022-01-04 16:19
Also experiencing this problem using nextjs v12.0.4 and yarn v3.2.0-rc.9 (canary)

**Comment by drewdecarme** [comment] 2022-01-04 20:37
For what it's worth, the yarn GitHub repository has a failing status next to NextJS for their nightly 3.x releases. I've had rather good luck with the stable version.`yarn set version stable`

 Scroll down until you see the "Toolchains" table: https://github.com/yarnpkg/berry

**Comment by balazsorban44** [comment] 2022-01-05 02:31
@GrefriT can you confirm that stable works for you?

**Comment by rrroyal** [comment] 2022-01-09 01:01
Still happens with `yarn set version stable` - setting `nodeLinker: node-modules` fixes it though 😃 

### What version of Next.js are you using?
^12.0.4

### What version of Node.js are you using?
v17.3.0 (yarn: 3.1.1)

### What operating system are you using?
macOS

**Comment by balazsorban44** [comment] 2022-01-11 12:13
Seems to be a duplicate of #32115

**Closed by balazsorban44** 2022-01-11 12:13 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-02-10 13:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
