### ISSUE TITLE
"TypeError: Object(...) is not a function" with create-next-app and next dev

### ISSUE THREAD

**Issue by armordecai** [vercel/next.js#22206] opened 2021-02-16 02:02 UTC
**What version of Next.js are you using?**

10.0.7

**What version of Node.js are you using?**

14.15.5

**What browser are you using?**

Firefox

**What operating system are you using?**

Linux Mint 19.3 (Ubuntu 18.04)

**How are you deploying your application?**

next dev

**Describe the Bug**

This was previously reported in #21038 and was closed as not reproducible. Hopefully the additional information in my report proves helpful. The problem is 100% reproducible on my machine with Next.js 10.0.7 (latest), 10.0.6, and 10.0.5. The problem is resolved by downgrading to 10.0.4.

When I create a new Next.js app using `create-next-app` (via `npx`), start it in development mode with `next dev` (via the provided NPM `dev` script), and load `http://localhost:3000` in the browser, the following error is raised:

```
TypeError: Object(...) is not a function
    at MyApp (webpack-internal:///./pages/_app.js:21:91)
    at d (/home/am/www/example/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/home/am/www/example/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/home/am/www/example/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/home/am/www/example/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/home/am/www/example/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/home/am/www/example/node_modules/next/dist/next-server/server/render.js:54:851)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:135:19)
    at loadGetInitialProps (/home/am/www/example/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/home/am/www/example/node_modules/next/dist/next-server/server/render.js:54:1142)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/am/www/example/node_modules/next/dist/next-server/server/next-server.js:107:97
    at async /home/am/www/example/node_modules/next/dist/next-server/server/next-server.js:100:142
    at async DevServer.renderToHTMLWithComponents (/home/am/www/example/node_modules/next/dist/next-server/server/next-server.js:132:387)
    at async DevServer.renderToHTML (/home/am/www/example/node_modules/next/dist/next-server/server/next-server.js:133:522)
```

If I use `next build && next start` instead, no error is raised, and the app loads (in production mode) as expected. I haven't touched any of the files generated by `create-next-app` or run any other commands inside the project directory.

**Expected Behavior**

I expected the app to compile and run in development mode, like Next.js apps usually do.

**To Reproduce**

1. `npx create-next-app example`
2. `cd example`
3. `npm run dev`

**Comment by timneutkens** [comment] 2021-02-16 08:38
This is still not reproducible based on the steps provided. Please provide a full reproduction in a repository.

**Comment by ostseb** [comment] 2021-02-18 18:37
@armordecai I'm

**Comment by armordecai** [comment] 2021-02-18 21:45
@ostseb You're right. `NODE_ENV` is globally set to "production" for some reason; unsetting it allows `npm run dev` to work.

@timneutkens 
Here is the result of the steps listed in my report: https://github.com/armordecai/nextjs-issue-22206

But I think `NODE_ENV` is probably the real issue. `npm run dev` should either work with `NODE_ENV=production` or exit with an informative error if that's not possible anymore in 10.0.5 and up. It works in 10.0.4, and probably in older versions, but I didn't try any more versions after I found one that worked.

**Comment by ijjk** [comment] 2021-09-23 04:16
Closing in favor of https://github.com/vercel/next.js/issues/19046

**Closed by ijjk** 2021-09-23 04:16 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 13:08
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
