### ISSUE TITLE
[NEXT-1240] In Next.js 13, Link component from next/link is not working as expected with baseUrl set. 

### ISSUE THREAD

**Issue by WenboL** [vercel/next.js#45910] opened 2023-02-14 14:59 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Mac M1 pro

next: 13.1.6
react: 18.2.0
react-dom: 18.2.0
typescript: 4.9.5

project created through `create-next-app` 

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/WenboL/next-link-issue

### To Reproduce

You can clone the example code repo for best result. 

Steps:
1. use next 13.1.6
2. set a baseURL in next.config.js config
3. use Link from `next/link`, and set the href with/without baseurl 
4. try to click on the link
5. try to open link in the new tab

### Describe the Bug

next/link has a different href URL than what it routes to via client side routing to when clicked. This behaviour is broken when you basePath set in your next config.

Given a configured basePath of "/demo"

From location /demo/before, I have:

Link that redirects to /demo/before/target. The href is specified as '/demo/before/target'.
Another Link that has href set to '/before/target'.

## Actual behavior:
Link 1: Click to redirect works, but open in a new tab landed on wrong url: `http://localhost:3000/demo/demo/before/target`.
 Link 2: Click to redirect landed on wrong url: `http://localhost:3000/before/target`, open in a new tab works.

By hovering over Link 1, the url hint displayed at bottom left corner is incorrect as well.

### Expected Behavior

Both Link component should redirect user to the same result, no matter click or open in new tab

### Which browser are you using? (if relevant)

Chrome

<sub>[NEXT-1240](https://linear.app/vercel/issue/NEXT-1240/in-nextjs-13-link-component-from-nextlink-is-not-working-as-expected)</sub>

**Comment by nbayat** [comment] 2023-02-15 11:48
This does not appear to be a software bug. It seems that there may be a misunderstanding regarding the concept of a base URL in Next.js. When a base URL is specified, all links receive that prefix, regardless of the current directory. Therefore, any links should be relative to the base URL rather than the current page.

For the first URL, Next.js does not locate another directory named "demo" in the root directory, as it is already in the "demo" directory.
If the URL being requested does not correspond to a valid route or file path within the "demo" directory, then Next.js will return a 404 page as a response of that path.

Regarding the second URL there is already a "before" directory but not specified in the path. However, as there is no directory named "target" present in the root directory,here /demo, it would result in an invalid route.

Your links should be: /before/target whith the baseurl sat to /demo

Let me know if it heled.

**Comment by nbayat** [comment] 2023-02-15 11:48
This does not appear to be a software bug. It seems that there may be a misunderstanding regarding the concept of a base URL in Next.js. When a base URL is specified, all links receive that prefix, regardless of the current directory. Therefore, any links should be relative to the base URL rather than the current page.

For the first URL, Next.js does not locate another directory named "demo" in the root directory, as it is already in the "demo" directory.
If the URL being requested does not correspond to a valid route or file path within the "demo" directory, then Next.js will return a 404 page as a response of that path.

Regarding the second URL there is already a "before" directory but not specified in the path. However, as there is no directory named "target" present in the root directory,here /demo, it would result in an invalid route.

Your links should be: /before/target whith the baseurl sat to /demo

Let me know if it heled.

**Comment by WenboL** [comment] 2023-02-15 15:04
> Your links should be: /before/target whith the baseurl sat to /demo

The second Link component in my example has the href set to /before/target.

Problem I am bringing up here is, behavior of the mouse click to open, and open in new tab is different. Your recommendation of set the href to /before/target will not work upon click (which it should). it will route user to http://localhost:3000/before/target without having the baseURL. 

I agree it should work the way you described, thus this is a bug.

**Comment by putterson** [comment] 2023-02-16 16:16
I'd like to clarify that this issue is observed using the new app dir routing as seen in the code example @WenboL provided

**Comment by edgeadjei** [comment] 2023-02-20 11:52
I'm running into the same issue. I have a base URL of `/store` with one of my pathname being `/settings`.
The generated anchor tag is referencing the correct URL(`/store/settings`) when inspecting the page but I'm navigated to `/store`.

**Comment by WenboL** [comment] 2023-03-02 22:18
Hi team any update on this?

**Comment by asmaa3107** [comment] 2023-04-29 06:06
same here 
I tried to update vercel.json 
but not working as well

**Comment by WiedenhoeverD** [comment] 2023-05-19 12:48
Hey,
I think I have the same problem.
I don't use base URL at all, but when I use a Next Link component and the href is "#screen3". When I hover over the Link in the bottom right corner it shows the right URL.  
![image](https://github.com/vercel/next.js/assets/44267944/2b18c811-b36a-42d2-a900-c64e69eed81d)  
With a middle mouse button the Link opens in new tab and everything is working right. When I click with a left click it redirects to  
![image](https://github.com/vercel/next.js/assets/44267944/9ecf9f3c-5d5f-4e04-a3c5-9599c91c79de)  

This should be the same error. Does anyone have any updates to this issu?

**Comment by huozhi** [comment] 2023-05-26 09:38
Seems the issue is fixed in the latest version (13.4.4) already, can you upgrade to latest version? Thanks

**Closed by huozhi** 2023-05-26 09:38 UTC
Labels: template: bug, linear

**Comment by Baryonae** [comment] 2023-06-11 08:58
i've updated to the latest version, but still im facing the same error.
whenever i try to go to a certain directory like '/auth' it shows a 404 error page,
can somebody help me out

**Comment by huozhi** [comment] 2023-06-11 09:04
@Baryonae can you file a new issue with a reproduction?
