### ISSUE TITLE
JS modules are loaded twice

### ISSUE THREAD

**Issue by Reggino** [vercel/next.js#11107] opened 2020-03-16 14:55 UTC
# Bug report

## Describe the bug

JS modules seem to be loaded twice

## To Reproduce

1. Go to 'https://www.nextjs.org' (or your own built site)
2. Click on 'developer console' in e.g. Chrome
3. See Network tab
4. Do a hard refresh (E.g. CTRL + SHIFT + R)
4. Sort resources by name
5. Look at loaded JS modules. They appear twice in the resource list, but are not retrieved from cache

## Expected behavior

All required resources to be loaded just once.

## Screenshots

![image](https://user-images.githubusercontent.com/174358/76770271-ef44a080-679d-11ea-82e8-aa0b9112d43c.png)

## System information

- OS: Ubuntu Linux
- Browser Chrome
- Version of Next.js: 9.1.1 - 9.3.0

## Additional context

When disabling granular loading in next.js config, the issue seems resolved.

```
    experimental: {
      granularChunks: false,
      css: false
    }
```

**Comment by Timer** [comment] 2020-03-16 15:12
Can you turn off your experimental usage of the modern behavior and see if this persists?

**Comment by Reggino** [comment] 2020-03-16 15:17
> Can you turn off your experimental usage of the modern behavior and see if this persists?

The issue seems resolved using the configuration:

```
    experimental: {
      modern: false
    }
```

**Comment by Reggino** [comment] 2020-03-16 15:26
(I've updated the title, since my assumption of the root cause may be incorrect ;-) )

**Comment by cansin** [comment] 2020-05-09 19:53
I am having the exact same problem and do not have my experimental config turned on. According to the sourcemap, there are 2 places loading the JS files:

```js
// at page-loader.js
.
.
.
function appendLink(href, rel, as) {
    return new Promise((res,rej,link)=>{
        link = document.createElement('link');
        link.crossOrigin = process.crossOrigin;
        link.href = href;
        link.rel = rel;
        if (as)
            link.as = as;
        link.onload = res;
        link.onerror = rej;
        document.head.appendChild(link); // <--- Here
    }
    );
}
.
.
.
```

and at document root (i.e. the HTML served) the actual `<link rel="preload" ... />` tag. I am not sure when this started happening though. Ideas? I can try to create a small reprod repo if you want.

**Comment by cansin** [comment] 2020-05-09 19:57
I am not sure if this is related but the reported First Load JS sizes are also roughly twice the size of First Load JS shared by all:

```bash
Page                                                           Size     First Load JS
┌ λ /                                                          1.73 kB         227 kB
├   /_app                                                      5.92 kB         105 kB
├ ○ /404                                                       769 B           210 kB
├ λ /forgot-password                                           1.32 kB         227 kB
├ λ /login                                                     1.33 kB         227 kB
├ ○ /offline                                                   1 kB            211 kB
├ λ /reset-password                                            2.37 kB         228 kB
├ λ /signup                                                    1.31 kB         227 kB
└ λ /todos                                                     3.11 kB         228 kB
+ First Load JS shared by all                                  105 kB
  ├ static/pages/_app.js                                       5.92 kB
  ├ chunks/3704887d5176932cc40c267af232f229c1b773b4.e8a25d.js  41.7 kB
  ├ chunks/commons.f7f234.js                                   10.5 kB
  ├ chunks/framework.126679.js                                 40.4 kB
  ├ runtime/main.89a34b.js                                     6.02 kB
  └ runtime/webpack.c21266.js                                  794 B

```

**Comment by cansin** [comment] 2020-05-09 20:00
And here is my `next.config.js` in case it helps:

```js
const dotenv = require("dotenv");
const withSourceMaps = require("@zeit/next-source-maps");
const withSitemap = require("next-with-sitemap");

dotenv.config();

module.exports = withSourceMaps()(
  withSitemap({
    compress: true,
    env: {
      GQL_URL: process.env.GQL_URL,
      GQL_AUTHORIZATION: Buffer.from(
        `${process.env.GQL_CLIENT_ID}:${process.env.GQL_CLIENT_SECRET}`
      ).toString("base64"),
      GTM_ID: process.env.GTM_ID,
      GTM_AUTH: process.env.GTM_AUTH,
      GTM_PREVIEW: process.env.GTM_PREVIEW,
    },
    pageExtensions: ["page.js"],
    sitemap: {
      baseUrl: `${
        process.env.SECURE_SSL_REDIRECT !== "false" ? "https" : "http"
      }://${process.env.WEB_DOMAIN}`,
    },
  })
);
```

and some of my library versions:

```
    "@apollo/react-hooks": "^3.1.5",
    "@zeit/next-source-maps": "^0.0.4-canary.1",
    "next": "^9.3.6",
    "next-with-apollo": "^5.0.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
```

**Comment by cansin** [comment] 2020-05-09 20:04
I want to speculate this issue might be related with https://github.com/zeit/next.js/issues/9070

**Comment by cansin** [comment] 2020-05-09 20:10
I have also realized the issue does not happen for `(Static)` pages:

<img width="1792" alt="Screenshot 2020-05-09 23 08 26" src="https://user-images.githubusercontent.com/1921283/81483910-2d17ef80-924a-11ea-9117-a47b1579f013.png">

Which might further signal a hydration problem.

**Comment by cansin** [comment] 2020-05-09 20:16
Huh, this is not happening on actual production, only happens when I run:

```bash
cansin@localhost web % export NODE_ENV=production
cansin@localhost web % yarn build
cansin@localhost web % yarn start
```

locally. So perhaps it is a false alarm? If so, I wonder what is the right way to simulate production locally.

**Comment by cansin** [comment] 2020-05-09 20:23
Ok, I changed ports and back and this problem disappeared. Perhaps some kind of stale module hot-reload shenanigan was happening. Sorry for the misdirection.

**Comment by Timer** [comment] 2020-09-12 04:35
Closing this issue as the issue no longer reproduces on nextjs.org and these experimental features have been enabled by default for a while (minus modern), with no further reports.

**Closed by Timer** 2020-09-12 04:35 UTC

**Comment by andrei-svistunou** [comment] 2020-11-25 11:17
Hi @Timer ,

I still can reproduce this issue on a lot of sites, including nextjs.org
![image](https://user-images.githubusercontent.com/16886492/100220640-b4982800-2f28-11eb-927e-8780de4d9aaa.png)

Could you, please, clarify this behaviour? Is it expected?

**Comment by andrei-svistunou** [comment] 2021-02-02 15:51
Hi @Timer
Could you please take a look at my comment above? May we reopen the ticket or better to open a new one?

**Comment by helfi92** [comment] 2021-02-08 14:45
We're seeing the same behavior as well on the latest version of Next.js 10.0.6.

**Comment by SidOfc** [comment] 2021-03-05 20:17
This seems to be happening in Chrome, or perhaps Chromium based browsers in general (didn't test that) in newer versions of next.js. In Firefox it seems like no request is duplicated. However, older versions of next.js don't seem to suffer from this issue even in Chrome.

For reference I'm testing this on Ubuntu 20.04 using Chrome 88.0.4324.182 and Firefox 86.0. Just specifying this in case it isn't reproducible on macOS / Windows, in which case it might be an issue with Chrome on Ubuntu.

Below some information with screenshots taken in Chrome. 

It happens on [my website](https://sidneyliebrand.io), I'm running `next@10.0.7`. The [repository](https://github.com/SidOfc/sidneyliebrand.io) is public in case anyone is interested in running it locally.
Both requests shown here seem to be fired through the commons chunk if I am to believe the network inspector:

![image](https://user-images.githubusercontent.com/3225058/110164347-8365a880-7df1-11eb-94e6-dd4932faccc1.png)

Additionally I did the same thing @andrei-svistunou  did and can confirm that [nextjs.org](nextjs.org) has this issue:

![image](https://user-images.githubusercontent.com/3225058/110166930-50251880-7df5-11eb-861e-d332c6b7250c.png)

I've also tried setting the experimental options mentioned at the start of this issue to see if that would resolve it, I tried:

```js
{
   experimental: {
        granularChunks: false,
        css: false,
        modern: false,
    }
}
```

but alas, no luck here either.

A friend and colleague of mine also has a [next.js website](https://jschilders.dev/) using `next@9.3.4`, this does not show any duplicated requests. This also has a [public repo](https://github.com/Bakon/portfolio) for those interested.

Let me know if you want me to try anything to see if it resolves the issue and last but certainly not least, thanks for building such an awesome framework, I'm loving every bit of it!

**Comment by Sheraff** [comment] 2021-03-05 23:08
I was looking for the common denominator of all "duplicate" network calls that actually got through (weren't caught by the cache) and it seems that i found it: the first request is always coming from `(index)`
<img width="1208" alt="Screen Shot 2021-03-05 at 23 49 47" src="https://user-images.githubusercontent.com/1325721/110182654-7bb3fd00-7e0d-11eb-95e1-2a5423ac8c17.png">

This means that the behavior we're seeing comes from the `<link rel="preload"` that are initially found in the HTML and not the `<link rel="prefetch"` added by the script afterwards.

The second request (the duplicate one) always comes from the same piece of code (whether caught by the cache or not). It's the last line in the following function, packages/next/client/route-loader.ts, lines 91 - 115 (in the /master branch):
```typescript
function prefetchViaDom(
  href: string,
  as: string,
  link?: HTMLLinkElement
): Promise<any> {
  return new Promise((res, rej) => {
    if (document.querySelector(`link[rel="prefetch"][href^="${href}"]`)) {
      return res()
    }

    link = document.createElement('link')

    // The order of property assignment here is intentional:
    if (as) link!.as = as
    link!.rel = `prefetch`
    link!.crossOrigin = process.env.__NEXT_CROSS_ORIGIN!
    link!.onload = res
    link!.onerror = rej

    // `href` should always be last:
    link!.href = href

    document.head.appendChild(link)
  })
}
```

My guess is that this function might need to extend is DOM selection to also look for `link[rel="preload"]` and not just `prefetch`. But to know for sure, I'd have to test a build with this change and I don't really have the time right now. Anyone who reproduces this issue on one of their current projects is willing to give it a go?

If so, just replace the selector from `link[rel="prefetch"][href^="${href}"]` to `link[rel="prefetch"][href^="${href}"],link[rel="preload"][href^="${href}"]`.

**Comment by Sheraff** [comment] 2021-03-06 13:10
@SidOfc If you want to test it out, the easiest way would be to search for `link[rel="prefetch"][href^="${href}"]` inside of your /node_modules/next folder and replace the string with `link[rel="prefetch"][href^="${href}"],link[rel="preload"][href^="${href}"]`.

If you need a solution that lasts a little longer you could always point your package.json to my fork of nextjs instead of the official one, but I really don't recommend that long term (or even just in production for that matter) because it will be unmaintained.

**Comment by SidOfc** [comment] 2021-03-06 15:01
@Sheraff alright, I did a search and found one occurrence in `dist/client/route-loader.js` which I replaced with the string you provided. After running a new build + export however, I'm still seeing duplicate requests:

![image](https://user-images.githubusercontent.com/3225058/110210953-97aeb180-7e94-11eb-9e2e-ffad3b51e57d.png)

I think the issue lies elsewhere, as I mentioned in my original comment (and can be seen in this screenshot) the requests seem to be coming from the `commons` chunk and neither of the types is `index` but rather `script` or `javascript`.

I hope this helps further narrowing it down a bit, if there's anything else you'd like me to try feel free to suggest, I think I can make any change necessary in the node_modules/next folder.

**Comment by Sheraff** [comment] 2021-03-06 15:20
@SidOfc some duplication is normal and expected w/ nextjs. Some of it will appear from the `preload` or `prefetch` tags, and some of it will come from the actual requests that plan on using the resource. You should look at this with cache enabled and look at whether the resource is actually downloaded twice or just requested twice.

To give you an example, from vercel.com, this is what is normal:
<img width="627" alt="Screen Shot 2021-03-06 at 16 13 48" src="https://user-images.githubusercontent.com/1325721/110211492-0c82eb00-7e97-11eb-8b8b-8c6cdac767d9.png">

And this is what we're trying to avoid:
<img width="622" alt="Screen Shot 2021-03-06 at 16 14 00" src="https://user-images.githubusercontent.com/1325721/110211499-160c5300-7e97-11eb-8dec-889f0f3d61e4.png">

In both cases, one of the requests comes from the `prefetchViaDom` function inside route-loader.js, that gets bundled into the `commons` chunk (this is where I asked you to replace the string). But this is just about prefetching the resource. Later on, a resource might be requested again but the request won't go through the network and be caught by the browser's cache which will answer with the prefetched resource (which is why you can't debug this w/ the "disable cache" option from the devtools toggled on).

**Comment by Sheraff** [comment] 2021-03-06 15:27
And as for CSS, I had looked into it quickly myself, and couldn't find anywhere where it was an issue, since in all the cases of duplication I could find, the duplicate resource came from the cache. Here's an example of this from nextjs.org:
<img width="620" alt="Screen Shot 2021-03-06 at 16 25 27" src="https://user-images.githubusercontent.com/1325721/110211850-c2026e00-7e98-11eb-8145-14e649b937f5.png">

**Comment by SidOfc** [comment] 2021-03-06 16:36
@Sheraff I see, indeed I did have cache disabled while testing this, thanks for pointing this out. After 1 reload I still noticed some requests were duplicated but after a second reload indeed all requests are correctly retrieved from prefetch/disk cache as seen in your screenshots.

The only thing I might add would be that this works flawlessly when using `next start`, however after running `next export`, if I use some other static file server such as `serve` and run `serve out` I do see duplicated CSS requests still. The reason for this seems to be that `serve` does not send appropiate caching headers:

**serve**
![image](https://user-images.githubusercontent.com/3225058/110213727-87e99a00-7ea1-11eb-90ef-97418259bb26.png)

**next start**
![image](https://user-images.githubusercontent.com/3225058/110213744-a059b480-7ea1-11eb-8df8-5761942ad2b4.png)

I'm adding this just to further clarify why some resources might be loading twice in certain scenarios, Next.js has no control over how these static files get served so this is definitely not a Next.js issue.

Thank you for your time, effort, and explanation. It's much appreciated and clears up [my] confusion about how this works. I think I'll be switching back to `next@10.0.7` now as that is the way forward :)

**Comment by Sheraff** [comment] 2021-03-06 17:30
@SidOfc Yeah I haven't tried setting cache headers w/ Next, my current project uses an express server (because it was started before next@10) and all cache headers are written from there.

I'm usually pretty happy w/ magic internet points, but there is always the [buy me a coffee](https://www.buymeacoffee.com/sheraff) thing for special occasions.

**Comment by SidOfc** [comment] 2021-03-06 18:55
More than happy to reward the kindness and constructiveness, enjoy :+1:

**Comment by balazsorban44** [comment] 2022-01-28 16:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
