### ISSUE TITLE
Can't access `NEXT_PUBLIC_` variable in `.env` file in some pages.

### ISSUE THREAD

**Issue by Elshir** [vercel/next.js#25755] opened 2021-06-03 15:25 UTC
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

I want to add Google Analytics to my app and I followed example in this repo called ["with-google-analytics"](https://github.com/vercel/next.js/tree/canary/examples/with-google-analytics), everything seems to be fine until I found the `NEXT_PUBLIC_GA_ID` in `.env` file will be `undefined` in my index page, but not on other pages.
![2021-06-03 at 22 52 59@2x](https://user-images.githubusercontent.com/16758942/120669969-89d3f100-c4c2-11eb-8a76-50b1fd9b07c2.png)
![2021-06-03 at 22 52 19@2x](https://user-images.githubusercontent.com/16758942/120669994-8e98a500-c4c2-11eb-91cf-ab478d85d6bd.png)

### Expected Behavior

NEXT_PUBLIC_GA_ID can be accessed in index page.

### To Reproduce

Just copy codes in ["with-google-analytics"](https://github.com/vercel/next.js/tree/canary/examples/with-google-analytics).

**Comment by davevanhoorn** [comment] 2021-06-24 21:25
@Elshir did you find a solution?

There's also a [Stackoverflow question](https://stackoverflow.com/questions/67802870/using-env-local-file-getting-process-env-next-public-vercel-env-is-undefined-o) regarding the issue, unfortunately without a concise answer.

**Comment by Elshir** [comment] 2021-07-12 07:13
> @Elshir did you find a solution?
> 
> There's also a [Stackoverflow question](https://stackoverflow.com/questions/67802870/using-env-local-file-getting-process-env-next-public-vercel-env-is-undefined-o) regarding the issue, unfortunately without a concise answer.

No bro..

**Comment by lucasoz** [comment] 2021-07-14 02:17
Bro same problem.
How are you adding the env var?

**Comment by Elshir** [comment] 2021-07-14 08:47
> Bro same problem.
> How are you adding the env var?
> #27156

wow, really a same problem, I give up, just add tarcking id to `gtag.js`, it's safe to load in client anyway.

**Comment by ijjk** [comment] 2021-09-19 05:33
Hi, it sounds like the `NEXT_PUBLIC_GA_ID` wasn't set in the environment during build time causing the value to be undefined for automatically statically optimized pages. I'm going to close this since it does appear to be a duplicate of the mentioned issue https://github.com/vercel/next.js/issues/27156

**Closed by ijjk** 2021-09-19 05:33 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
