### ISSUE TITLE
Next.js dynamic link with catch-all (ie. [[...slug]]) does not work when using the "as" prop in Link component

### ISSUE THREAD

**Issue by mwolfeio** [vercel/next.js#37094] opened 2022-05-21 13:10 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.12.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Brave

### How are you deploying your application? (if relevant)

This is happening locally but I am using Vercel for deployment

### Describe the Bug

I am building a Next.js app where some of the pages have in-page-routes one them. To accommodate this, I am using a catch-all (i.e. [[...slug]]) and handling the routes on that page itself. My folder structure looks like this:

```
pages/
└── index
└── deposits
└── crash/
    └── [[...crash]]
└── double/
    └── [[...double]]
└── mines/
    └── [[...mines]]
└── profile/
    └── [[...profile]]
```

While these routes work as expected, I am running into an issue where if I include an "as" prop to the Next.js Link component when referencing one of these catch-all pages, the href breaks, and the page refreshes to the "as" url. Here is my code:

```
import { useRouter } from "next/router";
import Link from "next/link";

export default function Header() {
  const router = useRouter();

  return (
    <header>
      <nav>
        <ul>
          <NavItem link="/">Logo</NavItem>
          <NavItem link="/crash">Link Text</NavItem>
          <NavItem link="/double">Link Text</NavItem>
          <NavItem link="/mines">Link Text</NavItem>
          <NavItem link="/profile">
            <Profile />
          </NavItem>
          <NavItem link={router.asPath} as="/deposit">
            <RoundPurpleButton />
          </NavItem>
          <MoreButton />
        </ul>
      </nav>
    </header>
  );
}

function NavItem({ children, link, as }) {
  return (
    <li>
      <Link href={link} as={as}>
        <a> {children}</a>
      </Link>
    </li>
  );
}
```
All header elements link to their own page except the ` <RoundPurpleButton />`. For reasons (modal functionality) it links to the current page but displays a different url. I am using dynamic link building, passing an href and an as prop to the Next.js Link component. This is where I am getting strange behavior.

1. If I pass just an href everything works fine. Each NavItem, when clicked, takes the user to the specified link. Both static and dynamic links work as expected.

3. The moment I add an "as" prop however,  ` <RoundPurpleButton />` receives the correct "link" and "as" attributes (I can confirm this from the console) but when you click on it you see this message in the console: `GET http://localhost:3001/_next/static/chunks/pages/games/double.js net::ERR_ABORTED 404 (Not Found)` then the page refreshes to the "as" url.enter image description here

I believe this issue has something to do with the Next.js catch-all links because I do not get this issue on statically typed link like "/", it's only on the catch-all links like "profile/[[...profile]]." It seems to me that the issue occurs when Next.js has to programmatically handle linking to a catch-all route.

Does anyone have any ideas on how to fix this issue or how to properly structure the routes to allow for this functionality?

### Expected Behavior

The expected behavior is that a Link element with an href pointing to one of these catch-all routes as well as an as prop pointed to somewhere else will still load the href page when clicked (without running into any errors).

### To Reproduce

Create the same file structure and run the code.

**Comment by JanKaifer** [comment] 2023-01-17 14:56
Closing as duplicate of https://github.com/vercel/next.js/issues/37852

**Closed by JanKaifer** 2023-01-17 14:56 UTC
Labels: please add a complete reproduction, template: bug
