### ISSUE TITLE
npm run build overwrites tsconfig.json and cannot compile

### ISSUE THREAD

**Issue by TSiege** [vercel/next.js#14539] opened 2020-06-24 20:50 UTC
# Bug report

## Describe the bug
npm run build overwrites my tsconfig.json, enforcing `isolatedModules`, which then cannot compile. I am also using apollo codegen to create typescript files for my queries. This creates several files, one of which is called `globalTypes.ts`. Currently it is an empty file; however, it being an empty files conflicts with the `isolatedModules` flag and blows up. I've tried switching this, but my hack at the moment is deleting the file during prebuild. I'd to have the ability to overwrite this. I've seen this issue (https://github.com/vercel/next.js/issues/8128) from a year ago, and I'm not sure where along in the process this is. I'd like to have something less hacky then blowing away files to make my build work, and share my use case of why I need to this to not be overwritten.

Here's the error
```
/Users/tristan/code/thedipp/www.thedipp.com/types/generated/globalTypes.ts
ERROR in /Users/tristan/code/thedipp/www.thedipp.com/types/generated/globalTypes.ts(1,1):
1:1 All files must be modules when the '--isolatedModules' flag is provided.
  > 1 | /* tslint:disable */
      | ^
    2 | /* eslint-disable */
    3 | // @generated
    4 | // This file was automatically generated and should not be edited.
```
Here's the contents of the file
```
/* tslint:disable */
/* eslint-disable */
// @generated
// This file was automatically generated and should not be edited.

//==============================================================
// START Enums and Input Objects
//==============================================================

//==============================================================
// END Enums and Input Objects
//==============================================================
```

## Expected behavior

I'd expect my tsconfig to not be overwritten.

**Comment by timneutkens** [comment] 2020-06-26 13:15
Duplicate of #8128

**Closed by timneutkens** 2020-06-26 13:15 UTC

**Comment by balazsorban44** [comment] 2022-01-30 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
