### ISSUE TITLE
next/image high memory usage on Heroku server

### ISSUE THREAD

**Issue by JKrol** [vercel/next.js#24052] opened 2021-04-14 12:35 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu (Heroku version)

### How are you deploying your application?

Heroku, using next start

### Describe the Bug

My website is using 4 images, displaying 1 or 2 on each page. I am using `next/image` to display the images. When running on Heroku, I often reach the memory usage limit, which is 512MB for my server.

I am almost sure that the problem is with `next/image` because after changing it to the standard HTML `img` tag, the maximum memory usage I was able to produce was about 120MB.

The images I am displaying are:
1. PNG - 18KB
2. PNG - 61.4KB
3. PNG - 47.8KB
4. SVG - 7.27KB

Those are not very big images, and loading them into the memory shouldn't use 300MB, so I'm not sure what happened.

I was also trying to reproduce it in my local environment, where I'm using Windows, but I could not reach more than 200MB usage, so I think the problem may be only on Linux.

### Expected Behavior

Next.js memory usage should not be this high when using a few small images with `next/image`. 

Also, it does not release the memory after some time. When it reaches 300-400MB, it stays like that until the restart.

### To Reproduce

1. Download my images:
[images.zip](https://github.com/vercel/next.js/files/6310766/images.zip)

2. Display them on the website. I am doing it like that (not exactly one under another - on my website, other components surround them):
```
<Image src="/base_logo_transparent.png" alt=""  width={134} height={80} priority={true} quality={100} />
<Image src="/base_icon_transparent.png" alt=""  width={55} height={40} priority={true} quality={100} />
<Image src="/hero.svg" alt="" width={630} height={540} quality={100} />
<Image src="/react-logo.png" alt="React plugin" width={182} height={182} />
```

3. Deploy the website to Heroku (maybe running on Linux is enough - I'm not sure)
4. After using the website for a short moment, verify memory usage - it is very high compared to the same website using `img` instead of `next/image`.

My application is also using other libraries, like MongoDB, which may also use some of the memory, but only removing `next/image` reduced the memory usage by >200MB, so I think this is the problem.

**Comment by joshdavenport** [comment] 2021-04-14 12:45
Seeing this issue manifest locally with no tweaking to memory limits or anything as straight up crashes (i.e. "Allocation failed - JavaScript heap out of memory") and the dev server dies.

Almost certainly the issue described here https://github.com/vercel/next.js/issues/23637. Best bet is to downgrade for now. I've had success going down to 10.0.7 myself.

**Comment by cakoose** [comment] 2021-05-15 02:49
In case it's useful, here's a small repro with a 13MB PNG: https://github.com/cakoose/render.com-big-image-oom

**Comment by nring** [comment] 2021-09-17 13:06
More anecdotal evidence, here is the Memory usage for our app over the past 72 hours. Our app had been sitting around the 350mb mark consistently for weeks on 10.2.3. There are two close deploys on the right side of the image. The first introduced 11.1.0 and the `<Image>` component. We saw a rapid increase in Memory usage due to using the `<Image>` component for user Avatars across the app. The deploy after that removed `<Image>` for avatars, but kept it in other places throughout the app. Still, the memory usage increases to about 950mb.

![image](https://user-images.githubusercontent.com/801071/133785844-553bcaf2-4d7a-4755-a2d5-377ec3326f49.png)

**Comment by pconcurrently** [comment] 2021-11-15 02:37
At my company, we did see a very high memory usage with next/image. Correct me if I'm wrong but next/image will send requests directly to nodejs server right? How are we gonna deal with that when having a high traffic?

**Comment by styfle** [comment] 2022-02-18 21:24
@cakoose Thanks for providing the repo! I was able to reproduce following the steps in the [readme](https://github.com/cakoose/render.com-big-image-oom).

I also confirmed that the issue is no longer present when upgrading to the latest version of `next` and `sharp`.

For example: https://github.com/cakoose/render.com-big-image-oom/pull/1

Furthermore, I tried lowering the memory from `--memory=1g` to `--memory=128m` and it still works on the latest version, so I think its safe to close this issue, thanks!

**Closed by styfle** 2022-02-18 21:24 UTC
Labels: template: bug, area: next/image
