### ISSUE TITLE
SSR cache example breaks l18n

### ISSUE THREAD

**Issue by jacksbox** [vercel/next.js#21446] opened 2021-01-22 15:21 UTC
**What version of Next.js are you using?**

10.0.2

**What version of Node.js are you using?**

13.7.0

**What browser are you using?**

chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

gcp

**Describe the Bug**

The provided ssr cache example (with the proposed fixes/workarounds, see open issues) causes the automatic l18n  locale detection to break.
More precisely it is not invoked at all, as it is done in the the request handler which is not used by the ssr cache example.

**Expected Behavior**

There should be an entry point to the app where the request is completely analysed and all detections run, but the response is not send, but returned to the caller. This would enable a broader implementation of the ssr cache solution with cacheable-response as well as other things which make use of a custom `server.js`

**To Reproduce**

Use the ssr cache example with some i18n settings defined in the `next.config.js` and inspect the `context` in `getServerSideProps`, e.g. `defaultLocale` and `locale` are empty

**Comment by ijjk** [comment] 2021-01-22 15:27
Closing as a duplicate of https://github.com/vercel/next.js/issues/20761

**Closed by ijjk** 2021-01-22 15:27 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
