### ISSUE TITLE
Error 400 and 500 works fine at local but not in Vercel

### ISSUE THREAD

**Issue by cococov** [vercel/next.js#27361] opened 2021-07-21 05:36 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14

### What browser are you using?

chrome, firefox

### What operating system are you using?

Windows, Linux

### How are you deploying your application?

Vercel

### Describe the Bug

When I force an error in my local machine the error 400 works fine and also when I access to the 400 and 500 page on Vercel. But, when The error occurs on Vercel, the error page doesn't show. [Error 404 works fine]

![image](https://user-images.githubusercontent.com/19384973/126436054-b7376c17-ee80-47fe-95da-bf09852a371b.png)
 

### Expected Behavior

Should show the custom error page when it occurs.

![image](https://user-images.githubusercontent.com/19384973/126436126-8967fa5d-ea1f-4ba3-8cb0-ae0f733badf4.png)

### To Reproduce

`MY_URL/%`  should be an 400 error and show the 400 error page.

**Comment by ijjk** [comment] 2021-07-21 17:12
Hi, it is currently expected that the custom 400 page won't show but the custom 500 should show. Are you using `pages/500` as documented here https://nextjs.org/docs/advanced-features/custom-error-page#customizing-the-500-page?

**Comment by cococov** [comment] 2021-07-22 23:05
Yes, I have the same configuration described in the doc, but nvm. Iis not really important to show the custom error anyway, but it could be great. Thanks.

Why is expected not to show the 400 custom error?

**Comment by ijjk** [comment] 2021-07-22 23:13
For the 500 page to be shown on Vercel it has to be statically optimized or prerendered and we don't currently do this for a `pages/400` file only `pages/404` and `pages/500`.

**Comment by leerob** [comment] 2021-08-12 03:19
Closing this as a solution has been provided (500 page) and it's documented 👍

**Closed by leerob** 2021-08-12 03:19 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 23:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
