### ISSUE TITLE
Importing a CSS file from node_modules is permitted in anywhere your application.

### ISSUE THREAD

**Issue by mylastore** [vercel/next.js#17502] opened 2020-09-30 23:39 UTC
This is on the docs `Importing a CSS file from node_modules is permitted in anywhere your application.`, but I get an error when importing CSS from node_mudules like this `import 'react-quill/dist/quill.snow.css'` and if I use the `@zeit/next-css` then that works but the Built-In CSS Support by nex.js breaks. So we need both module/css and default node modules imports by default. I am new to react and nex.js and I can't believe that this is still an issue. Learning how to use CSS with react is more frustrating than learning react :(

**Comment by lfades** [comment] 2020-10-01 02:31
@mylastore Just checked and you're right. Our docs are currently showing some features that are only available in `next@canary`, including global CSS imports from `node_modules` (I'm very sorry for the confusion here 🙏).

You can either wait for a new release that's coming out very soon or update to `next@canary` for the moment.

I'm going to close the issue for now, and thank you for letting us know! I'll try to do better next time.

**Closed by lfades** 2020-10-01 02:31 UTC

**Comment by nathsimpson** [comment] 2020-10-02 23:51
Glad I found this as I'm having the same issue. Thanks @mylastore for posting and @lfades for answering!

**Comment by balazsorban44** [comment] 2022-01-29 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
