### ISSUE TITLE
Problem loading css: Cannot read properties of undefined

### ISSUE THREAD

**Issue by levinunnink** [vercel/next.js#34652] opened 2022-02-21 21:19 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:38 PDT 2021; root:xnu-7195.141.8~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 17.5.0
      npm: 8.4.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.1
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

Using the basic `create-next-app` nextjs, I get an error loading global.css:

```
error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!./styles/globals.css
TypeError: Cannot read properties of undefined (reading 'config')
```

### Expected Behavior

Next.JS should load the css without throwing an error.

### To Reproduce

I'm getting this error just by running:

- `npx create-next-app@latest`
- `npm run dev`

**Comment by balazsorban44** [comment] 2022-02-22 09:57
I could not reproduce this, could you attach a repository?

**Comment by levinunnink** [comment] 2022-02-22 15:14
Dang, when I run this in a clean docker container, the error disappears. I assume it's something to do with my local environment and not a problem with Next. 

I've seen other people reporting this issue without resolution. Any guidance on how I'd find the root cause of this error?

**Comment by balazsorban44** [comment] 2022-02-22 15:54
Make sure you don't have a stray symlink, or a global install of `next` or `create-next-app` that could interfere somehow. 

Try different package managers, npm, Yarn, pnp. See if all of them reproduces the issue.

Try different Node.js versions. Try deleting `node_modules` and `.next` between different runs to avoid bad cache.

Make sure you don't somehow initialize the project inside a node_modules folder either.

That's it from the top of my head. I'll close this for now, feel free to report back when you found a solution. 👍

**Closed by balazsorban44** 2022-02-22 15:54 UTC
Labels: please add a complete reproduction, template: bug
