### ISSUE TITLE
Refresh "sibling" elements (same route, different language) while using i18n routing and incremental static regeneration

### ISSUE THREAD

**Issue by wiesson** [vercel/next.js#18634] opened 2020-11-01 19:17 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I use incremental static regeneration to update product information. If a product has been reserved or sold, the status will be updated and it is visible on the next page refresh - independent from the locale/language.

Example
`/products/:id`

With the current state of i18n routing, I have the same product 5 (or n) times and 4 might be out of sync despite the page has been refreshed for one language.

```
/en/products/:id
/de/products/:id
/fr/products/:id
/it/products/:id
/pl/products/:id
/(...)/products/:id
```

## Describe the solution you'd like

I'd like to keep the other languages in sync. That means, if a product receives an update, I'd like to refresh all other "sibling" locales of that product, not only that one, that has been visited right now.

I don't have a good term for that, but e.g. something like `revalidateSiblings` is the closest term that came to my mind to  describe the idea.

```Javascript
export async function getStaticProps() {
  const res = await fetch('https://.../posts')
  const posts = await res.json()

  return {
    props: {
      posts,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every second
    revalidate: 1, // In seconds
    // Next.js will attempt to re-generate the page siblings as well
    revalidateSiblings: true 
  }
}
```

## Describe alternatives you've considered

I could help myself with a HTTP hook that allows incremental static regeneration for certain pages and or locales.

**Comment by ijjk** [comment] 2021-09-21 03:41
Hi, I'm gonna close this in favor of https://github.com/vercel/next.js/discussions/21903

**Closed by ijjk** 2021-09-21 03:41 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-27 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
