### ISSUE TITLE
[NEXT-907] Use client break composite components.

### ISSUE THREAD

**Issue by lelabo-m** [vercel/next.js#44030] opened 2022-12-14 15:28 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

   Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Nov 23 01:01:46 UTC 2022
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: N/A
      pnpm: 7.18.1
    Relevant packages:
      next: 13.0.7-canary.6
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

NA

### To Reproduce

`MobileMenu.tsx`
```jsx
"use client";

export const MobileMenu = () => {
  return (
    <div>
      MobileMenu 
    </div>
  );
};

const MobileMenuContainer = ({ children }: PropsWithChildren) => {
  return <div className="relative">{children}</div>;
};

const MobileMenuTrigger = () => {
  return (
    <div>
      Button
    </div>
  );
};

MobileMenu.Container = MobileMenuContainer;
MobileMenu.Trigger = MobileMenuTrigger;
MobileMenu.RandomProps = true;
```

`Component.tsx`
```jsx
import { MobileMenu } from "./MobileMenu";

export default function Component() {
  console.log(MobileMenu, MobileMenu.Container, MobileMenu.RandomProps);

  return (
    <div >
      App
    </div>
  );
}

```
`Output`
```
{
  '$$typeof': Symbol(react.module.reference),
  filepath: '/home/.../app/(marketing)/MobileMenu.tsx',
  name: 'MobileMenu',
  async: false
} undefined undefined
```

### Describe the Bug

If I add `use client` on a component file, then any extra properties added get undefined.
This make creating composite client component impossible.

### Expected Behavior

If I remove the `use client` statement, every thing works fine and every props get defined properly.
`Output`
```
[Function: MobileMenu] {
  Container: [Function: MobileMenuContainer],
  Trigger: [Function: MobileMenuTrigger],
  RandomProps: true
} [Function: MobileMenuContainer] true
```

### Which browser are you using? (if relevant)

NR

### How are you deploying your application? (if relevant)

pnpm run dev (next dev)

<sub>[NEXT-907](https://linear.app/vercel/issue/NEXT-907/use-client-break-composite-components)</sub>

**Comment by darklight9811** [comment] 2023-03-16 20:35
Any updates on this? Still happening on `13.2.5-canary.4`

**Comment by Fredkiss3** [comment] 2023-03-16 22:58
I think it is how server components work under the hood, they reference client components as files and modules to be serialized. And it seems that composite components is not supposed to work with server components. When trying to use the component i get this error :  

```
Error: Cannot access .Container on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.
```

The code : 

```tsx
import { MobileMenu } from './MobileMenu';

export default function Component() {
  return (
    <div>
      <MobileMenu.Container>App</MobileMenu.Container>
    </div>
  );
}
```

So instead of using it, i think it is better to use a different component instead of a composite one, i.e : `MobileMenuContainer`.

**Comment by Kinbaum** [comment] 2023-04-26 12:50
As a workaround, you can use something like `Object.assign` to achieve the same behavior.

```tsx
"use client";

const Menu = () => {
  return (
    <div>
      MobileMenu 
    </div>
  );
};

const Container = ({ children }: PropsWithChildren) => {
  return <div className="relative">{children}</div>;
};

const Trigger = () => {
  return (
    <div>
      Button
    </div>
  );
};

const MobileMenu = Object.assign(Menu, {
  Container,
  Trigger,
  RandomProps: true
});

export { MobileMenu };
```

**Comment by darklight9811** [comment] 2023-05-02 06:24
@Kinbaum very clever, I think this is the way to go since the bug is still happening

**Comment by darklight9811** [comment] 2023-05-04 17:06
Really sad of seeing app router reaching stable without fixing this. Hope it gets fixed soon

**Comment by acdlite** [comment] 2023-05-10 17:58
This behavior is intentional. `'use client'` creates a boundary in the module graph. When you import _from_ a client module _into_ a server module, what you're actually importing is a special, opaque client reference that the RSC runtime knows how to send down to the browser. You can't actually access the export itself — it's only useful for passing to the client.

To make this work, we rely on the client exports being statically known at build time, using JavaScript `export` syntax.

Keep in mind that assigning to an export alone actually works fine. It's probably not a great idea for other reasons, because module side effects complicate your bundle graph and make it harder to perform optimizations like tree shaking. The error only happens when you attempt to _access_ it on the server. (If you import the same thing into a client module, and access it there, it works fine.)

Instead what you should do is export each thing separately.

Because this is working as designed, I'm going to close the issue.

@Kinbaum I'd be curious to learn what you mean about `Object.assign` being a workaround. As far as I know the behavior shouldn't be any different; again, the error is thrown when you attempt to _access_ the property on the server, not when you assign to it.

**Closed by acdlite** 2023-05-10 17:58 UTC
Labels: type: needs investigation, template: bug, area: Server Components, area: Developer Experience

**Comment by darklight9811** [comment] 2023-05-10 18:03
@acdlite since its intentional, I believe there should be a specific error message warning about this. Because it left me clueless of how and why that happened.

**Comment by acdlite** [comment] 2023-05-10 18:04
You should get this error message:

> Error: Cannot access .Container on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.

Are you not seeing that? Maybe it was added recently?

**Comment by darklight9811** [comment] 2023-05-10 18:14
`13.4.1`
![image](https://github.com/vercel/next.js/assets/20667774/b16ffd39-8863-4484-baac-64ecd8cd543a)

Now it actually runs on the browser, it just throws on the server terminal (its parcially working)

**Comment by acdlite** [comment] 2023-05-10 18:18
Ah ok, could you open a separate issue with a repro please so we can figure out why it's not erroring?
