### ISSUE TITLE
'isAutoExport' is clearing query object, it only keeps the 'amp' object

### ISSUE THREAD

**Issue by Ruchika-saini** [vercel/next.js#29162] opened 2021-09-16 23:17 UTC
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

14.17.4

### What browser are you using?

Chrome v92

### What operating system are you using?

Windows

### How are you deploying your application?

next custom server

### Describe the Bug

I am trying to pass the context query from server-side which I need to access in document .tsx

**Example: When passing like this, I am getting the empty query object in the document.tsx**
return nextapp.render(req, res, '/welcome', **{lang: {staticGNAV}}**);

**Example: When passing like this, I am getting the query value through amp object in the document.tsx**
return nextapp.render(req, res, '/welcome', **{amp: {staticGNAV}}**);

On debugging, what I have noticed is, in render.js,  there is an "isAutoExport " boolean when its value is true, it's clearing the query object and only keeping the amp object value. What's the purpose of this code? or it's a bug which needs to be fixed?

**node_modules\next\dist\server\render.js**
  const isAutoExport = !hasPageGetInitialProps && defaultAppGetInitialProps && !isSSG && !getServerSideProps;

 if (isAutoExport || isFallback1) {
            // remove query values except ones that will be set during export
            query1 = {
                ...query1.amp ? {
                    amp: query1.amp
                } : {
                }
            };

### Expected Behavior

context query should be propagated to document.tsx with any object name.

### To Reproduce

Add custom server and pass the context query with any object name except 'amp'

**Comment by ijjk** [comment] 2021-09-17 01:02
Hi, this is the expected behavior for automatically statically optimized pages since they are prerendered during build time and can't be re-rendered on the server with new query information until it's rendering on the client. 

I'm gonna close this since this isn't a bug and is expected.

**Closed by ijjk** 2021-09-17 01:03 UTC
Labels: template: bug

**Comment by Ruchika-saini** [comment] 2021-09-17 15:12
https://nextjs.org/docs/advanced-features/automatic-static-optimization
As documented, on the above-mentioned link:
"Next.js automatically determines that a page is static (can be prerendered) if it has no blocking data requirements. This determination is made by the absence of getServerSideProps and getInitialProps in the page."


But in my case, I have getInitialProps in document.tsx.
On debugging, these are the boolean values I am getting:

**hasPageGetInitialProps false
defaultAppGetInitialProps true
isSSG false
getServerSideProps undefined
isAutoExport true**

I am passing the context query for my "/welcome" page, even in this case query object is deleted but it should keep the query object.

**Comment by ijjk** [comment] 2021-09-17 15:21
The `getInitialProps` referenced there is on the specific page, `getInitialProps` in `_document` does not disable the automatic static optimization but in `_app` it does for all pages and then in each specific page it does.

**Comment by balazsorban44** [comment] 2022-01-27 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
