### ISSUE TITLE
using  PageComponent.getLayout triggers a typescript error

### ISSUE THREAD

**Issue by neilnahid** [vercel/next.js#27524] opened 2021-07-27 07:55 UTC
### What version of Next.js are you using?

11

### What version of Node.js are you using?

14

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04

### How are you deploying your application?

next start

### Describe the Bug

When following the documentation for the `Layouts` using typescript, I get this error
![image](https://user-images.githubusercontent.com/25801890/127117402-a46fbcbd-4946-4a97-b773-a4e8d75d7970.png)

### Expected Behavior

Should not get a typescript error

### To Reproduce

1. create a new file under /pages
2. define your page component
3. set the getLayout() function for the component
4. see error

**Comment by stefanprobst** [comment] 2021-07-27 10:34
you could look into how it is done in #27488

**Comment by stefanprobst** [comment] 2021-07-30 16:41
there is now an example w/ typescript documented at https://github.com/vercel/next.js/blob/canary/docs/basic-features/layouts.md#with-typescript

**Comment by ijjk** [comment] 2021-07-30 16:45
Closing per above comment

**Closed by ijjk** 2021-07-30 16:45 UTC
Labels: kind: story, type: documentation

**Comment by balazsorban44** [comment] 2022-01-28 01:27
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
