### ISSUE TITLE
When I add a script tag in the Head tag (exported via next/head) and add a defer or async attribute, js will be executed twice

### ISSUE THREAD

**Issue by lvzegeng** [vercel/next.js#15452] opened 2020-07-24 04:52 UTC
![image](https://user-images.githubusercontent.com/26923315/88361594-20685980-cdac-11ea-91da-7fb5f2741eee.png)
![image](https://user-images.githubusercontent.com/26923315/88361615-3249fc80-cdac-11ea-8d45-4525fa99cbb5.png)
![image](https://user-images.githubusercontent.com/26923315/88361629-44c43600-cdac-11ea-9cba-5e44f78ab351.png)

**Comment by Janpot** [comment] 2020-07-24 11:20
Closing as a duplicate https://github.com/vercel/next.js/issues/9070

**Closed by Janpot** 2020-07-24 11:20 UTC

**Comment by balazsorban44** [comment] 2022-01-29 20:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
