### ISSUE TITLE
trailingSlash + unexistent page should return 404 instead of 308 + 404

### ISSUE THREAD

**Issue by aralroca** [vercel/next.js#16586] opened 2020-08-26 07:24 UTC
# Bug report

## Describe the bug

When a route does not exist and does not have the trailingSlash, for example:

```
localhost:3000/whatever
```

First it's redirecting with 308 to:

```
localhost:3000/whatever/
```

And then is displaying the 404 page with the status 404.

## To Reproduce

1. Add `trailingSlash: true` on the next.js config
2. Curl an unexisting URL without trailingSlash

## Expected behavior

Would be better to directly display the 404 page avoiding the 308 redirecting for these cases.

## Screenshots

![image](https://user-images.githubusercontent.com/13313058/91274250-b3672b80-e77e-11ea-85d3-f637acc4a702.png)

## System information

- OS:  macOS
- Version of Next.js: 9.5.2
- Version of Node.js: 14.8.0

**Comment by timneutkens** [comment] 2020-08-26 11:21
This is expected behavior. Given that there's no explanation of why this change would be needed (doesn't seem like it is needed) I'll close the issue as it's not a bug.

**Closed by timneutkens** 2020-08-26 11:21 UTC

**Comment by aralroca** [comment] 2020-08-26 13:42
I thought that for SEO as fewer redirects possible better, and showing the page 404 directly made sense in this case. I have reported it because we had implemented it with a custom server before this feature landed in the new version of Next. But it is likely that I am wrong, so if it is done so because it is considered better, ok 👍

**Comment by jordic** [comment] 2020-08-27 08:57
I can confirm what @aralroca is saying, 
when you manage a large set of urls, and you want to improve the performance of googlebot indexing them, that's an small improvement, because serving a 308 triggers a new crawl actoin, to finally fetch a 404. (It's better, in terms of performance to just serve the 404).

**Comment by aralroca** [comment] 2020-08-31 12:53
I commented here https://github.com/vercel/next.js/issues/15867#issuecomment-683748417. Hope that this issue will be reconsidered to reopen 😊

**Comment by balazsorban44** [comment] 2022-01-29 15:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
