### ISSUE TITLE
favicon.ico request returns status 500 locally

### ISSUE THREAD

**Issue by federicolopezeikilis** [vercel/next.js#52632] opened 2023-07-13 09:40 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.14.0
      npm: N/A
      Yarn: N/A
      pnpm: 7.27.0
    Relevant Packages:
      next: 13.4.10-canary.6
      eslint-config-next: 13.4.8
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Metadata (metadata, generateMetadata, next/head)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/federicolopezeikilis/favicon-nextjs-issue-example

### To Reproduce

npm run dev
check the network http://localhost:3000/favicon.ico returns status 500

### Describe the Bug

favicon is not being load

### Expected Behavior

favicon should be loaded

### Which browser are you using? (if relevant)

Chrome / Canary / Mo<illa

### How are you deploying your application? (if relevant)

No

**Comment by huozhi** [comment] 2023-07-13 11:05
I can't repro it on my windows (as you're using windows) neither on mac with both 13.4.8 and canary. can you confirm it's breaking with canary and share more about the error trace

**Comment by balazsorban44** [comment] 2023-07-13 11:17
I could not reproduce this either. The reproduction repository states a different version than what is reported in the issue template, so it's hard to narrow down. FWIW, I cannot reproduce using the latest `canary` (`13.4.10-canary.6` as of writing) either.

I'll close this issue for now, but if you still think it's a Next.js bug, please open a new issue with a complete reproduction, and all the steps necessary to recreate it, thanks! :pray:

**Closed by balazsorban44** 2023-07-13 11:17 UTC
Labels: template: bug
