### ISSUE TITLE
intermittent: Cannot find module for page

### ISSUE THREAD

**Issue by habermanUIUC** [vercel/next.js#15880] opened 2020-08-04 19:39 UTC
# Bug report

## Describe the bug
While running in dev mode (npm run dev), I get '{ Error: Cannot find module for page: /lessons/[album]/[slug]'.  This happens occasionaly and I can't reproduce it on demand.

Once it happens, the Error page will be displayed and then after a few seconds the page will be re-displayed without the error -- rendered as it should be.

My page set up:
```
pages ->
   lessons ->
      [album] ->
         [slug].tsx
```

The page [slug].tsx indeeds exports all the necessary paths via `getStaticPaths` (e.g. `[ .. {"params":{"album":"mlu","slug":"association-rules"}} .. ]`)

## To Reproduce
I am unable to find a reliable way to demonstrate this on demand.

## Screenshots
![Screen Shot 2020-08-04 at 12 10 08 PM](https://user-images.githubusercontent.com/14237134/89337034-29301980-d64f-11ea-9bf9-7e07456249f2.png)

## System information

- OS: mac/10.15.6
- Version of Next.js: 9.5  (although I noticed this happening since 9.3)
- Version of Node.js: 10.16.3

**Comment by Timer** [comment] 2020-08-04 19:41
Please add a complete reproduction so we can look into this.

**Comment by habermanUIUC** [comment] 2020-08-04 19:45
that's the issue ... Most of the time it will work flawlessly, then the Error will show up.  It happens maybe on 5% of all page refresh/requests.  Getting this to happen on demand is what I am working on. But I am hoping perhaps others have seen this behavior as well.

**Comment by connoredward** [comment] 2020-08-12 18:34
I'm also getting the same error. It's not happening consistently, as sometimes I'm also getting instead ```Error: request to http://localhost:8080/... failed, reason: connect ECONNREFUSED 127.0.0.1:8080```.

**Comment by nick-myers-dt** [comment] 2020-12-23 15:19
I ran into this error today using `next build`:

```bash
info  - Creating an optimized production build  
info  - Compiled successfully

> Build error occurred
Error: Cannot find module for page: /accounts/create/[companyId]
    at pageNotFoundError (/Users/nickmyers/repos/rebuild/admin/node_modules/next/dist/next-server/server/require.js:1:384)
    at getPagePath (/Users/nickmyers/repos/rebuild/admin/node_modules/next/dist/next-server/server/require.js:1:917)
    at /Users/nickmyers/repos/rebuild/admin/node_modules/next/dist/build/index.js:15:3168
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 3)
    at async build (/Users/nickmyers/repos/rebuild/admin/node_modules/next/dist/build/index.js:15:2729) {
  code: 'ENOENT'
}
```

I ran `next build` again and it completed without issue.

**Comment by DiFuks** [comment] 2020-12-23 19:28
@nick-myers-dt this helped for me https://stackoverflow.com/a/57503454/7048638

**Comment by timneutkens** [comment] 2021-01-03 10:27
Closing as no reproduction was provided.

**Closed by timneutkens** 2021-01-03 10:27 UTC
Labels: please add a complete reproduction

**Comment by chineduogada** [comment] 2021-03-29 00:06
I'm getting the same Error on dynamic pages as well, but it is `flaky`(doesn't happen all the time)

### Error: Cannot find module for page: /products/[slug]

How do I fix the issue????

**Comment by aMoniker** [comment] 2021-04-05 07:48
Ran into this just now as well. Worked the second time. Maybe a race condition somewhere.

**Comment by alexkreidler** [comment] 2021-04-22 03:55
For me, I had the `yarn dev` (`next`) command running in another terminal. Once I killed that process and ran `yarn build && yarn export`, the issue went away.

**Comment by dasblitz** [comment] 2021-04-22 12:31
Same here. The reason I have `yarn dev` running while also doing a `yarn build` is because on `git push` a git hook first runs Cypress tests. Cypress obivously needs a running server instance, so I just had a terminal tab open that runs `yarn dev` and ran `git push` from another tab in the terminal.

I can probably make it so that I run and quit `yarn dev` before and after the Cypress tests but it's a bit annoying that I have to remember to close any open `yarn dev` instance before doing a git push/next build.

**Comment by balazsorban44** [comment] 2022-01-28 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
