### ISSUE TITLE
tsconfig rewrite not respecting extends

### ISSUE THREAD

**Issue by zefexdeveloper** [vercel/next.js#13616] opened 2020-05-31 17:03 UTC
# Bug report

## Describe the bug

I have a monorepo configured with a `tsconfig.json` file that shares common information but whenever I run the Next app it rewrites my `tsconfig.json` in the package and doesn't respect the extended one.

For example in the root I have a `tsconfig.json` file with `excluded` which has the `node_modules` folder, but when I run my `client` package which also has a `tsconfig.json` file it rewrites the `excluded` even tho it's extending the root config which already has this option.

---

I just noted something else, it's enforcing `moduleResolution` but it has been deprecated.

## To Reproduce

You just need to have a `tsconfig` file somewhere and extend in the `tsconfig.json` file inside the next application.

## Expected behavior

It should respect the extended config file and don't overwrite. I don't see forcing a `tsconfig.json` as the best solution here it would be nice to have at least warnings instead.

## System information

- OS: Windows
- Version of Next.js: 9.4.4
- Version of Node.js: 12.16.3

**Comment by timneutkens** [comment] 2020-06-01 07:27
This will be fixed by #13542

**Comment by zefexdeveloper** [comment] 2020-06-01 12:27
Thank you very much

**Closed** 2020-07-28 10:00 UTC
Labels: kind: story

**Comment by Timer** [comment] 2020-07-30 03:27
This was just fixed in 9.5.1, please upgrade!

**Comment by balazsorban44** [comment] 2022-01-29 20:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
