### ISSUE TITLE
Middleware causes post requests larger than 64kb to hang

### ISSUE THREAD

**Issue by arvind-agarwal** [vercel/next.js#39593] opened 2022-08-14 19:58 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Aug 25 23:20:18 UTC 2021
    Binaries:
      Node: 18.3.0
      npm: 8.11.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.6-canary.0
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Not relevant

### How are you deploying your application? (if relevant)

Not relevant

### Describe the Bug

I am facing an issue with large post body with middleware, If the post body size is larger than 64k it hangs the client for a long time and is not processed. I zeroed it down on issue with middleware. If I introduce the middleware (even that does not do anything), than the post request does not succeed.

Steps to reproduce.
1. Create a brand new project using create-next-app
2. Create a middleware.js file in root of the project
```
export function middleware(request) {
  console.log(request.url);
}
```
3. Start the above server using 
```
npm run dev
```
4. Start another terminal session
5. Install axios
```
npm install axios 
```
6. Create a file in root testRequest.js, needs axios as dependency
```
const axios=require("axios");

axios.post("http://localhost:3000/test", {
  "x": '1'.repeat(1024*64)
}).then(function (response) {
  console.log(response);
})
.catch(function (error) {
  console.log(error);
});
```
7. Run the file using node testRequest.js. This process will hang and will not finish.

If I reduce the request size by changing multiple in repeat to 63, the request will not hang and 404 error response will be returned.

### Expected Behavior

Expected behavior is that on running the testRequest, I should immediately get 404 response and an error message should be consoled. 

However if the request is larger than 64k, it hangs and does not print the error.

### Link to reproduction

https://codesandbox.io/s/mutable-flower-z3qgzd?file=/testRequest.js

### To Reproduce

1. Codesandbox, will automatically run the base nextjs project.
2. Open another terminal tab in Codesandbox.
3. Execute node testRequest.js, it should print the url in nextjs terminal tab, however the execution of the node program will hang. Kill this program. This file generates request of 100kb in size hence it hangs.
4. Execute node testRequestLessThan64.js, this should succeed and print a message in console.

**Comment by Marcelx8** [comment] 2022-08-14 21:58
A similar issue was raised here https://github.com/vercel/next.js/issues/39262#issue-1326143015 where a post request of 16kb and larger body resulted in a pending state. See if v12.2.2 works if you can downgrade temporarily. That version has fixed my issue.

**Comment by hmdnprks** [comment] 2022-08-15 21:22
Downgrading to v12.2.2 resolve my issue with uploading a file larger than 64kb. In v12.2.3, I have to remove the middleware file.

**Comment by ijjk** [comment] 2022-08-16 00:09
Closing as a duplicate of https://github.com/vercel/next.js/issues/39262

**Closed by ijjk** 2022-08-16 00:09 UTC
Labels: template: bug
