### ISSUE TITLE
API routes don't return with concurrentFeatures

### ISSUE THREAD

**Issue by bduff9** [vercel/next.js#30586] opened 2021-10-28 23:49 UTC
### What version of Next.js are you using?

12.0.2-canary.6

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

A freshly generated next app does not seem to allow API routes when concurrentFeatures is turned on.  The browser never loads anything and the console displays output similar to the following:
```
wait  - compiling /api/hello (server only)...
wait  - compiling...
event - compiled successfully in 498 ms (281 modules)
error - Error: Cannot find module for page: /api/hello
wait  - compiling /_error...
wait  - compiling...
event - compiled successfully in 160 ms (284 modules)
```

### Expected Behavior

API routes to not be affected by concurrentFeatures.  If I turn them off, the API routes load as expected.

### To Reproduce

1. Generate a new next app with `npx create-next-app --ts --use-npm`
2. `cd` into the new app directory and edit the next.config.js file to add the concurrentFeatures flag like so:
```js
module.exports = {
  experimental: {
    concurrentFeatures: true
  }
}
```
3. Save and run `npm run dev`
4. Try to navigate to localhost:3000/api/hello
5. The page will never load and you will see the following error in the console:
```
Error: Cannot find module for page: /api/hello
```

**Comment by shuding** [comment] 2021-11-09 22:11
Hey! I tested locally that with the latest `next@canary` (>= 12.0.4-canary.3) API routes are now working as expected, so this should have been fixed by a previous PR. Also adding #31227 to avoid future regression.

Please let us know if you can still reproduce this issue :)

**Closed** 2021-11-09 22:48 UTC
Labels: kind: bug, type: needs investigation, area: Concurrent Features

**Comment by balazsorban44** [comment] 2022-01-27 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
