### ISSUE TITLE
[NEXT-1168] useFormStatus doesn't seem to work with server actions

### ISSUE THREAD

**Issue by rliang** [vercel/next.js#49232] opened 2023-05-04 18:35 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Binaries:
      Node: 20.0.0
      npm: 9.6.4
      Yarn: 1.22.17
      pnpm: 7.27.0
    Relevant packages:
      next: 13.4.0
      eslint-config-next: N/A
      react: 0.0.0-experimental-aef7ce554-20230503
      react-dom: 0.0.0-experimental-aef7ce554-20230503
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/rliang/next-use-form-status-bug-reproduction

### To Reproduce

- run `npm run dev`
- open `localhost:3000` in the browser
- click on the `submit` button

### Describe the Bug

`useFormStatus` doesn't work, such that its return value is never updated when submitting a form.

### Expected Behavior

The page should update the `formStatus` after clicking on `submit`.

<sub>[NEXT-1168](https://linear.app/vercel/issue/NEXT-1168/useformstatus-doesnt-seem-to-work-with-server-actions)</sub>

**Comment by rliang** [comment] 2023-05-04 23:13
Moreover, the terminal also logs an error:

```
error - TypeError: (0 , react_dom__WEBPACK_IMPORTED_MODULE_1__.experimental_useFormStatus) is not a function
```

Even though the initial state is correctly displayed in the browser.

**Comment by john-griffin** [comment] 2023-05-05 01:15
Just hit this too

**Comment by mauricekleine** [comment] 2023-05-05 09:39
I was able to get rid of the error by installing the `next`/`canary` builds of React and ReactDOM, however I still don't see updated values from `useFormStatus` after I submit my form

**Comment by rliang** [comment] 2023-05-05 20:11
Found out that `useFormStatus` in fact looks up the status of the nearest `<form>` parent element, i.e. the element that uses this hook must be a child of a `<form>`.

Still getting the error in the server console though, even after upgrading next/react/react-dom.

**Comment by megadrive** [comment] 2023-05-09 04:27
I have an incredibly simple component, hitting the `Error: (0 , react_dom__WEBPACK_IMPORTED_MODULE_3__.experimental_useFormStatus) is not a function` issue.

Installed react@next and react-dom@next and no change unfortunately.

**Comment by ElvarP** [comment] 2023-05-10 18:43
Also having the same issue.

**Comment by felipebarcelospro** [comment] 2023-05-10 19:57
Same error here!

**Comment by harrybawsac** [comment] 2023-05-10 20:17
@mauricekleine 

How did you manage to get rid of `experimental_useFormStatus is not a function` exactly? The following way?

```json
{
    "react": "next",
    "react-dom": "next",
    "next": "canary"
}
```

**Comment by Gregoor** [comment] 2023-05-16 14:45
> Found out that `useFormStatus` in fact looks up the status of the nearest `<form>` parent element, i.e. the element that uses this hook must be a child of a `<form>`.
> 
> Still getting the error in the server console though, even after upgrading next/react/react-dom.

Thanks, I got it to work with this comment without having to resort to full-experimental mode, i.e. this works:

```jsx
// app/.../page.tsx
"use server";
import { ClientComponent } from "./ClientComponent";

async function doSomething() {}

export default function Page() {
  return <form action={doSomething}><ClientComponent /></form>;
}
```

```jsx
// app/.../ClientComponent.tsx
"use client";
import { experimental_useFormStatus as useFormStatus } from "react-dom";

export function ClientComponent() {
  const formStatus = useFormStatus();
  return <input type="submit" disabled={formStatus.pending}>Go</input>;
}
```

**Comment by harrybawsac** [comment] 2023-05-16 14:50
@Gregoor Yeah that works because you're using it in a client component. [Documentation doesn't state that](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#experimental-useformstatus):

<img width="636" alt="image" src="https://github.com/vercel/next.js/assets/98596391/b07df747-b357-4893-aa28-a72d8625dbf0">

**Comment by Gregoor** [comment] 2023-05-16 15:13
> @Gregoor Yeah that works because you're using it in a client component. [Documentation doesn't state that]

Yes-ish, but it did not work when `<form>` was within `ClientComponent`. I'm sensing there is sth like React's Context going on here.


> @Gregoor You found a way to retrieve the response from the server action? I want to receive if had an error on server-side, and display that on my client component.
Not yet, but I'd like to know that too

**Comment by sebastianpikand** [comment] 2023-05-17 21:22
So... what is the recommended way of showing a loading status for server-component form submissions?

**Comment by arjunkomath** [comment] 2023-05-17 21:47
> So... what is the recommended way of showing a loading status for server-component form submissions?

The only solution that has worked for me is having the `form` and server action in a server component, then have a client component inside the form (should be a child of the form) consuming `useFormStatus`.

You can find a full working example here: https://github.com/techulus/manage-prompt/blob/c9dad49a802c2192d1553d62e4b3151dda134fdf/app/console/workflows/new/page.tsx#L7

**Comment by dvrd** [comment] 2023-05-26 14:05
Is there a way for the form to avoid rerender & the `useFormStatus` hook to work? It seems to be connected to the request sent by the form but it rerender the entire form once the request is returned & if you avoid the post by handling the server action and passing false to the on submit the `useFormStatus` hook does not changes state

**Comment by harrybawsac** [comment] 2023-06-11 09:09
[Documentation has been updated](https://github.com/vercel/next.js/pull/50991) with NextJS v13.4.5.

**Comment by JLarky** [comment] 2023-06-20 03:44
Just in case if anyone is getting caught on the part where return value is not updated for a submitted form, I wrote a small utility that could help you with that. It allows you to lift the state of `useFormStatus` from child component up to the parent.

https://gist.github.com/JLarky/190bab52ff13c44f9420523d1792fbf0

**Comment by malith7597** [comment] 2023-07-15 17:09
In next.config.js enable server actions. This worked for me !.

 `const nextConfig = {
    experimental:{
        serverActions:true,
    },
}
`

**Comment by sojinsamuel** [comment] 2023-07-31 06:43
> In next.config.js enable server actions.Don't forget to use npm run dev to build the project again. This worked for me.
> 
> `const nextConfig = { experimental:{ serverActions:true, }, } `

This worked for me too

**Comment by MincePie** [comment] 2023-08-15 04:41
Did anyone figure this out? I'm struggling to get this repo working with this error: https://github.com/steven-tey/prisma-server-actions

**Comment by ahmadawais** [comment] 2023-09-23 14:08
I have tried a lot of different ways, but the API is definitely experimental and breaks. So, reverted back to not using form action for complex form processing.

**Comment by maornissan** [comment] 2023-10-11 18:02
I got a TS error when trying to import:
```ts
import { experimental_useFormStatus as useFormStatus } from "react-dom";
```
When ignoring this error, problem seems to be solved

```ts
// ts-ignore because experimental_useFormStatus is not in the types
// @ts-ignore
import { experimental_useFormStatus as useFormStatus } from "react-dom";
```

**Comment by MiguelGuerreroGoodRx** [comment] 2023-10-12 14:35
Does anyone knows how to make this work with jest+testing library and with storybook, in both integration and visual tests i am getting `(0 , react_dom__WEBPACK_IMPORTED_MODULE_1__.experimental_useFormState) is not a function`

**Comment by panoskouff** [comment] 2023-10-14 08:08
> Found out that `useFormStatus` in fact looks up the status of the nearest `<form>` parent element, i.e. the element that uses this hook must be a child of a `<form>`.
> 
> Still getting the error in the server console though, even after upgrading next/react/react-dom.

Has anyone found a way to get around that ?

what if I want to have

```tsx
export default function Contact() {
  const [state, formAction] = useFormState(myAction, initialState);
  const { pending } = useFormStatus();
  
  return <div>
    {pending ? <h1>Loading...<h1> : ''}
    <div>
      ...
        <form action={formAction}>
        ....
```

**Comment by kuijpie** [comment] 2023-10-14 13:59
> Has anyone found a way to get around that ?
> 
> what if I want to have
> 
> ```tsx
> export default function Contact() {
>   const [state, formAction] = useFormState(myAction, initialState);
>   const { pending } = useFormStatus();
>   
>   return <div>
>     {pending ? <h1>Loading...<h1> : ''}
>     <div>
>       ...
>         <form action={formAction}>
>         ....
> ```


@panoskouff `useFormStatus` can only be used in client component that is a child of a `<form>`
So what you can do is create a separate loading client component and place that inside your form.

```tsx
"use client"

export default function SubmitButton() {
  const { pending } = useFormStatus()

  return (
    <button type="submit" disabled={pending}>{pending ? 'Loading...' : 'Submit'}</button> 
  )
}
```

```tsx
export default function Contact() {
  return (
    <form action={formAction}>
       ...
       <SubmitButton />
    </form>
  )
}
```

If you don't want anything to be visible from the form, you could make all your inputs part of a client component. 

```tsx
"use client"

export default FormInputs() {
  const { pending } = useFormStatus()

  return (
    <>
      {pending ? (
        <h1>Loading...<h1>
      ) : (
         <>
           <label><input /></label>
           ...
         </>
      )}
    </>
  )
}
```

**Comment by Anmol-dev45** [comment] 2023-10-18 13:18
> So... what is the recommended way of showing a loading status for server-component form submissions?
Use it like this 
`"use client";

import { ComponentProps } from "react";
import { useFormStatus } from "react-dom";

type FormSumbmitButtonProps = {
  children: React.ReactNode;
  className?: string;
} & ComponentProps<"button">;
export default function FormSumbmitButton({
  children,
  className,
  ...props
}: FormSumbmitButtonProps) {
  const { pending } = useFormStatus();
  return (
    <button
      {...props}
      disabled={pending}
      type="submit"
      className={`btn btn-primary ${className}`}
    >
      {children}
      {pending && <span className="loading loading-spinner" />}
    </button>
  );
}
`

**Comment by Anmol-dev45** [comment] 2023-10-18 13:24
> > Found out that `useFormStatus` in fact looks up the status of the nearest `<form>` parent element, i.e. the element that uses this hook must be a child of a `<form>`.
> > Still getting the error in the server console though, even after upgrading next/react/react-dom.
> 
> Has anyone found a way to get around that ?
> 
> what if I want to have
> 
> ```tsx
> export default function Contact() {
>   const [state, formAction] = useFormState(myAction, initialState);
>   const { pending } = useFormStatus();
>   
>   return <div>
>     {pending ? <h1>Loading...<h1> : ''}
>     <div>
>       ...
>         <form action={formAction}>
>         ....
> ```

[https://github.com/vercel/next.js/issues/49232#issuecomment-1768444105](url)

**Comment by micheltucker** [comment] 2023-10-18 14:58
Adding my learnings going through this. The documentation of NextJS is really not complete. Best would be to watch the video on Youtube: https://www.youtube.com/watch?v=dDpZfOQBMaU and check its repo here: https://github.com/vercel/next.js/tree/canary/examples/next-forms

Maybe I am missing something, but the [docs](https://nextjs.org/docs/app/building-your-application/data-fetching/forms-and-mutations#displaying-loading-state) say `import { useFormStatus } from 'react-dom'` whilst the repo includes it experimentally `import { experimental_useFormStatus as useFormStatus } from 'react-dom'`. Plus, y'all need to either update [typescript definitions](https://github.com/vercel/next.js/issues/55919) or `// @ts-expect-error`.

Am I missing something here?

**Comment by hyper-dot** [comment] 2023-10-21 05:05
> I got a TS error when trying to import:
> 
> ```ts
> import { experimental_useFormStatus as useFormStatus } from "react-dom";
> ```
> 
> When ignoring this error, problem seems to be solved
> 
> ```ts
> // ts-ignore because experimental_useFormStatus is not in the types
> // @ts-ignore
> import { experimental_useFormStatus as useFormStatus } from "react-dom";
> ```

But while deploying in vercel I will throw same error. Locally it runs despite of typescript error.

**Comment by WilsonKinyua** [comment] 2023-10-23 15:07
> > I got a TS error when trying to import:
> > ```ts
> > import { experimental_useFormStatus as useFormStatus } from "react-dom";
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When ignoring this error, problem seems to be solved
> > ```ts
> > // ts-ignore because experimental_useFormStatus is not in the types
> > // @ts-ignore
> > import { experimental_useFormStatus as useFormStatus } from "react-dom";
> > ```
> 
> But while deploying in vercel I will throw same error. Locally it runs despite of typescript error.

This will work locally but for vercel error to be solved, have it like this:
`// @ts-expect-error
import { experimental_useFormStatus as useFormStatus } from "react-dom";`

**Comment by devmetal** [comment] 2023-10-23 16:25
Hi, the documentation needs to be updated in nextjs. They even did not mention this experimental stuff. Also i'm kinda start get frustrated these days. I'm currently in a migration to nextjs with my pet project and keep hit these kind of walls. Started with prisma and edge runtime. I know this is not easy and i'm really appriciate the work behind this meta framework but this server side action things needs to be clearified. Most of these kind of frameworks already can provide a single loading state from server side action. I think the workaround maybe the startTransition hook but i don't know because this is very under documented. Sorry for this but i'm overall kinda frustrated the current frontend era....

**Comment by AccelKing12** [comment] 2023-10-25 00:41
I see that this nextjs product have import { experimental_useFormStatus as useFormStatus } from "react-dom";
in the addButton.tsx with no error and no // @ts-expect-error
https://github.com/saleor/storefront

**Comment by leonardopavanello** [comment] 2023-10-25 02:29
Look at this:
https://react.dev/reference/react-dom/hooks/useFormStatus#useformstatus-will-not-return-status-information-for-a-form-rendered-in-the-same-component

**Comment by WallisMark** [comment] 2023-10-26 01:10
how was this problem solved im still very much confused

**Comment by xmayukx** [comment] 2023-10-26 19:45
I updated NextJS 13.5.5 to 13.5.7, it worked for me.
Just run `npm i next@canary` 

> how was this problem solved im still very much confused

**Comment by nebrekab** [comment] 2023-10-27 12:08
This does work in NextJS 13.5.6, but now seems to be broken in NextJS 14.0.0.

Anyone else having this issue?

**Comment by micheltucker** [comment] 2023-10-27 12:39
> This does work in NextJS 13.5.6, but now seems to be broken in NextJS 14.0.0.

Can you be more specific. What I shared above (https://github.com/vercel/next.js/issues/49232#issuecomment-1768650794) works for me.

**Comment by ajiohjesse** [comment] 2023-10-28 16:20
I just updated to next.js 14. I had to add `@ts-expect-error`

```javascript
// @ts-expect-error
import { useFormStatus } from 'react-dom';
```
else typescript throws an error that useFormStatus is not exported . It works fine for me now though.

**Comment by ilia-luk** [comment] 2023-10-31 05:57
In my case the TS module resolution error was solved  by adding `yarn add -D @types/react-dom` instead of using `// @ts-expect-error`

**Comment by omburj** [comment] 2023-11-03 03:56
for the example code from NextJS https://github.com/vercel/next.js/tree/canary/examples/next-forms
correcting the verion of reac-dom to latest resolves the pnpm run build error
"@types/react-dom": "^18.2.14",

**Comment by omburj** [comment] 2023-11-03 03:58
refer to the NextJS latest example https://github.com/vercel/next.js/tree/canary/examples/next-forms
in that use correct the verion of react-dom in package.json to latest. This will resolve the pnpm run build error
"@types/react-dom": "^18.2.14",

**Comment by micheltucker** [comment] 2023-11-03 08:53
> refer to the NextJS latest example https://github.com/vercel/next.js/tree/canary/examples/next-forms in that use correct the verion of react-dom in package.json to latest. This will resolve the pnpm run build error "@types/react-dom": "^18.2.14",

Yes! See above: https://github.com/vercel/next.js/issues/49232#issuecomment-1768650794

**Comment by omburj** [comment] 2023-11-03 09:43
Maybe not the Not the "experimental" nor "canary" versions

But the "latest"
Or still better to use specific versions as in the official example
ammended with the type react-dom version I have mentioned above.
Cheers!

**Comment by mtt786** [comment] 2023-11-15 07:02
Started working for me after running `yarn add next@latest` 👻.

**Comment by Nlferu** [comment] 2023-11-16 15:28
I still cannot get rid of this error `TypeError: (0 , react_dom__WEBPACK_IMPORTED_MODULE_2__.useFormStatus) is not a function`. I have tried all solutions mentioned above, but none had effect, experimental or not did not matter. I'm using this function in my other project and it is working perfectly fine. I have copied all dependencies versions from there but still no effect on my current project...

Any other ideas how to get rid of this error?

**Comment by Steravy** [comment] 2023-11-18 01:23
Hi in my case i was using the useFormStatus in the same component as the form to disable the submit button when the for is submiting. and i got that issue: `TypeError: (0 , react_dom__WEBPACK_IMPORTED_MODULE_2__.useFormStatus) is not a function`.

I created a separate component, lets called SubmitButton and i placed the useFormStatus and call it there, then i import the component and used as a child of the form, and then i used the ts annotation: `// @ts-ignore
import { experimental_useFormStatus as useFormStatus } from "react-dom";` mentioned by @WilsonKinyua 

The button component:

`
const SubmitButton = () => {

    const {pending} = useFormStatus();

    return (
        <Button type="submit"
                className="group rounded-full h-[3rem] w-[8rem] flex gap-2 outline-none transition-all focus:scale-110 hover:scale-110 hover:bg-gray-950 active:scale-105 dark:bg-white dark:bg-opacity-10 disabled:scale-100 disabled:bg-opacity-65">
            {
                pending
                    ?
                    (
                        <div className="h-5 w-5 rounded-full border-b-2 border-white animate-spin"/>
                    )
                    :
                    (
                        <>
                            Submit{" "}
                            <FaPaperPlane
                                className="text-xs opacity-70 transition-all group-hover:translate-x-1 group-hover:-translate-y-1"/>{" "}
                        </>
                    )
            }

        </Button>
    )
}
`

**Comment by mertthesamael** [comment] 2023-11-29 11:51
I just fixed it by changing versions of:

```js
"@types/react-dom": "18.2.17",
"@types/react": "18.2.39",
"next": "canary",
"eslint-config-next": "canary",
"react": "next",
"react-dom": "next",
```

with the given values. I hope that works.

**Comment by dospolov** [comment] 2023-12-02 05:03
@kuijpie thank you 🙏🏻

the only thing that helped me is to place **action and form tag** in a Server component, but the **form content** in JSX.fragment inside Client component.

**Comment by hsglc** [comment] 2023-12-09 16:29
If you're using the next and react libraries with their experimental version, you should upgrade your `@types/react-dom `to `18.2.7 `version, and error goes to void. I mean it worked for me!

**Comment by LassazVegaz** [comment] 2023-12-17 06:08
I got the error `TypeError: (0 , react_dom__WEBPACK_IMPORTED_MODULE_1__.useFormStatus) is not a function`

For me `useFormStatus` is shown as stable.

```tsx
"use client";
import { Button, ButtonProps } from "@mui/material";
import { useFormStatus } from "react-dom";

const FormButton = (props: ButtonProps) => {
  const { pending } = useFormStatus();

  return <Button disabled={pending} {...props} />;
};

export default FormButton;
```
The above code does not give a TS error but gives the runtime error mentioned earlier. The reason is types and the implementations do not match. In implementation, it is still experimental. So I had to do this,

```tsx
"use client";
import { Button, ButtonProps } from "@mui/material";
// import { useFormStatus } from "react-dom";
// @ts-expect-error Types and implementations do not match
import { experimental_useFormStatus as useFormStatus } from "react-dom";

const FormButton = (props: ButtonProps) => {
  const { pending } = useFormStatus();

  return <Button disabled={pending} {...props} />;
};

export default FormButton;
```
Now the runtime error goes away and `useFormStatus` works (functionally) as expected.

in `package.json` versions look like this,
```json
  "dependencies": {
    "next": "13.5.4",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/react": "^18",
    "@types/react-dom": "^18"
  }
```

I have no idea how to do version matching here because they all have the same major release version.

**Comment by LassazVegaz** [comment] 2023-12-17 10:32
After upgrading to Next 14 (14.0.4 to be exact), I could import `useFormStatus` (the stable one).

**Comment by johnsonfash** [comment] 2023-12-20 20:14
The only way useFormStatus work is As a hook, it can only live in a client component and can only be used as a child of a form element using a Server Action.

So convert the button, input to a seperate client component and place the component inside a form







ie. 
submitHandle.tsx

''use server'
export const submit = (e: FormData)=> {
const name = e.get('name')
}

customButton.tsx
export const CustomButton = ()=> {
const {pending} = useFormStatus();
return <button disabled={pending}>submit</button>
}

login.tsx
"use client"
 <form action={submit}>
<CustomButton/>
</form>

**Comment by leerob** [comment] 2023-12-30 20:24
We now have an example of forms + `useFormStatus` + `useFormState` using TypeScript and all of the latest versions of the packages. This is linked in the docs and we've made quite a few iterations there since this issue was opened. Since the originally reproduction is solved, going to close this out – if there are any new issues, let's start a new thread with a new reproduction. Thank you!

- https://github.com/vercel/next.js/tree/canary/examples/next-forms
- https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations

**Closed by leerob** 2023-12-30 20:24 UTC
Labels: template: bug, area: app, linear: next
