### ISSUE TITLE
Eslint `plugin:@next/next/recommended` does not work 

### ISSUE THREAD

**Issue by vicasas** [vercel/next.js#26907] opened 2021-07-03 22:41 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

16.3.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

npm run lint

### Describe the Bug

Extending the recommended configuration of next eslint (`plugin:@next/next/recommended` https://nextjs.org/docs/basic-features/eslint#migrating-existing-config) and executing` npm run lint` does not work correctly the linter.

Instead using in extends `next` works as expected.

### Context

I have eslint set using Airbnb style rules and I want to add the corresponding style rules to Next.js

```json
{
    ...
    "extends": [
        "plugin:react/recommended",
        "airbnb",
        "airbnb/hooks",
        // "next" // This works
        "plugin:@next/next/recommended" // Not work
    ],
    ...
}
```

Could we provide a template in the "correct" or "recommended" way to extend `plugin:@next/next/recommended` using it with the Airbnb style guide?

### Expected Behavior

It should work as stated in the documentation.

### To Reproduce

1. Create a new application `npx create-next-app`
2. Start it with eslint following the Airbnb style guide `npx eslint --init`
3. Add the `"lint: next lint"` script to your package.json
4. Add the `plugin:@next/next/recommended` in the configuration Eslint.
5. Make changes to cause an error (eg add <img> tag in the page)
6. Run `npm run lint`

**Comment by likerRr** [comment] 2021-07-05 12:55
Not sure if I have the same issue, but let me describe. I also have my own eslint setup extended from airbnb. When I add `next` to `extends` array and run `npx next lint`, I get this error:

```
Plugin "react" was conflicted between "../../.eslintrc » eslint-config-next" and "../../.eslintrc » eslint-config-airbnb » /home/alizurchik/projects/avby/avby-web/node_modules/eslint-config-airbnb/rules/react-a11y.js".
```

Minimal eslint config which lets to reproduce the error:

```
{
  "extends": [
    "airbnb",
    "next"
  ]
}
```

**Comment by housseindjirdeh** [comment] 2021-07-07 16:25
> Extending the recommended configuration of next eslint (plugin:@next/next/recommended https://nextjs.org/docs/basic-features/eslint#migrating-existing-config) and executing npm run lint does not work correctly the linter.

@vicasas Can you share what issue you're seeing? Are warnings and errors from `plugin:@next/next/recommended` not showing like they should, or are you seeing a build/lint error?

`plugin:@next/next` only contains new custom rules that are [Next.js specific](https://github.com/vercel/next.js/blob/canary/packages/eslint-plugin-next/lib/index.js). Extending it's recommended configuration shouldn't have any impact to other shareable configurations you're extending. Please provide more details on the issue you're seeing and I'll try to help!

**Comment by vicasas** [comment] 2021-07-10 22:12
@housseindjirdeh  Hi! sorry for the delay in my reply.

Apparently it works fine now, only extending from the recommended setting disables the React scope rules (I think this is expected).

Regarding the documentation it seems to have improved, but an example should accompany it. an eslint configuration with Airbnb `npx eslint --init` extending the recommended next configuration.

The latter add a lot of value for developers, always having a quick guide is a great plus.

For those who already started with a previous Eslint configuration, we could indicate or guide whether to use `next lint` or its own commands, pros and cons.

If you like, you could support with the example of airbnb.

**Comment by housseindjirdeh** [comment] 2021-07-14 17:17
No worries at all @vicasas!

> Apparently it works fine now, only extending from the recommended setting disables the React scope rules (I think this is expected).

Okay that's great to hear! Yes, extendind from the recommended plugin (`plugin:@next/next/recommended`) _only_ includes new Next.js rules, so no `react`, `react-hooks`, or `import` checks will be included. All of that is bundled within the configuration itself however (`next`)

> Regarding the documentation it seems to have improved, but an example should accompany it. an eslint configuration with Airbnb npx eslint --init extending the recommended next configuration.
> 
> The latter add a lot of value for developers, always having a quick guide is a great plus.
> 
> For those who already started with a previous Eslint configuration, we could indicate or guide whether to use next lint or its own commands, pros and cons.
> 
> If you like, you could support with the example of airbnb.

Thanks, this is great feedback so I appreciate it. We're always hoping to improve the docs moving forward so as soon as the new changes land, I'll try and include a section that shows a more specific example of how to combine it with other configurations (how to use it along with `airbnb` for example).

Closing this since the issue is resolved!

**Closed by housseindjirdeh** 2021-07-14 17:17 UTC
Labels: template: bug

**Comment by raphaelpc** [comment] 2021-09-01 19:47
> Not sure if I have the same issue, but let me describe. I also have my own eslint setup extended from airbnb. When I add `next` to `extends` array and run `npx next lint`, I get this error:
> 
> ```
> Plugin "react" was conflicted between "../../.eslintrc » eslint-config-next" and "../../.eslintrc » eslint-config-airbnb » /home/alizurchik/projects/avby/avby-web/node_modules/eslint-config-airbnb/rules/react-a11y.js".
> ```
> 
> Minimal eslint config which lets to reproduce the error:
> 
> ```
> {
>   "extends": [
>     "airbnb",
>     "next"
>   ]
> }
> ```

This error is still happening on NextJS 11.1.0.

**Comment by vicasas** [comment] 2021-09-12 23:39
@housseindjirdeh When could we have an example of integration with airbnb? Given this, I am having to put aside the use of eslint-config-next because it doesn't work as expected.

This part of the documentation is still somewhat tangled. https://nextjs.org/docs/basic-features/eslint#recommended-plugin-ruleset

**Comment by tettoffensive** [comment] 2021-10-22 01:40
@housseindjirdeh @vicasas I see that this is closed, but I'm not sure I see a solution. I'm on 11.1.2.

When I include the line `"plugin:@next/next/recommended"` I get `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined`, When I remove it, it's fine other than the warning that I'm not using the Next.js plugin in my configuration.


```js
    extends: [        
        "plugin:react/recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "airbnb",
        "plugin:jest/recommended",
        "plugin:jest/style",
        "plugin:prettier/recommended",
        "plugin:@next/next/recommended"
    ],
```

**Comment by noyanyan** [comment] 2021-10-30 16:59
> plugin:@next/next only contains new custom rules that are Next.js specific. Extending it's recommended configuration shouldn't have any impact to other shareable configurations you're extending.
@housseindjirdeh
How about adding this sentence to the Migrating Existing Config documentation? If someone wants to add this ruleset to an existing configuration, I think this sentence would be very useful. I was about to file a bug report because I assumed that this configuration also managed jsx-a11y.

**Comment by balazsorban44** [comment] 2022-01-27 13:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
