### ISSUE TITLE
next build wont work after updating from next@9.5.3 to next@9.5.4

### ISSUE THREAD

**Issue by tairosonloa** [vercel/next.js#17744] opened 2020-10-09 11:05 UTC
# Bug report

## Describe the bug

The command `next build` fails on `next@9.5.4` but works fine in `next@9.5.3`. 
The error log is the following:

```sh
$ next build
Loaded env from /home/aalonso/workspaces/aalonso.dev/.env.local
info  - Using external babel configuration from /home/aalonso/workspaces/aalonso.dev/.babelrc
info  - Creating an optimized production build  
Failed to compile.

./src/containers/Cover/Cover.module.scss
Error: Can't resolve '/images/cover.webp' in '/home/aalonso/workspaces/aalonso.dev/src/containers/Cover'
    at runMicrotasks (<anonymous>)


> Build error occurred
Error: > Build failed because of webpack errors
    at build (/home/aalonso/workspaces/aalonso.dev/node_modules/next/dist/build/index.js:15:918)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This happens when resolving an image URL from SCSS. The SCSS (`./src/containers/Cover/Cover.module.scss`):
```
.container {
  ...
  background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('/images/cover.webp');
  ...
}
```
The folders structure of the repository:
```
./
|- package.json
|- .babelrc
|   ...
|- src/
   |- containers/
      |- Cover/
         |- Cover.module.scss
|- public/
   |- images/
      |- cover.webp
```
`.babelrc`
```
{
  "presets": ["next/babel"],
  "plugins": []
}
```
## To Reproduce

Just run `next build` on this branch of this public repository:
https://github.com/tairosonloa/aalonso.dev/tree/dependabot/npm_and_yarn/next-9.5.4
**NOTE:** if you run `yarn build` or `npm run build`, process will throw if you don't set the env variable `DOMAIN`, as it tries to execute also the npm `prebuild` command, which requires the env variable to be set.
To fix it, just run `export DOMAIN=aalonso.dev` on your terminal.

Here is the GitHub actions log with the failing build stage:
https://github.com/tairosonloa/aalonso.dev/pull/115/checks?check_run_id=1230832954

Here is the GitHub actions log passing build step for the previous commit (before the `next` dependency update):
https://github.com/tairosonloa/aalonso.dev/runs/1230831205?check_suite_focus=true

## Expected behavior

The build process should resolve the image path and finish without errors, like in the previous build processes.

## System information

- OS: Ubuntu-Latest (GitHub Actions and WSL)
- Version of Next.js: 9.5.4
- Version of Node.js: v12.X (GitHub Actions) and v12.19.0 (WSL)

**Comment by vgribdev** [comment] 2020-10-09 11:11
I have the same problem with fonts,
`Error: Can't resolve '/fonts/PoppinsRegular.woff2'`,
It was working with 9.5.3

**Comment by madsfaerch** [comment] 2020-10-09 11:26
Duplicate of #17701

Install `next@9.5.5-canary.0` until stable

**Comment by timneutkens** [comment] 2020-10-09 14:14
Duplicate of #17701, this was already fixed pending a stable release.

**Closed by timneutkens** 2020-10-09 14:14 UTC

**Comment by tairosonloa** [comment] 2020-10-09 16:32
I'm sorry, as issue #17701 was closed I didn't see it was a duplicated. Best regards

**Comment by tairosonloa** [comment] 2020-10-09 16:32
I'm sorry, as issue #17701 was closed I didn't see it was a duplicated. Best regards

**Comment by tairosonloa** [comment] 2020-10-09 16:33
I'm sorry, as issue #17701 was closed I didn't see it was a duplicated. Best regards

**Comment by balazsorban44** [comment] 2022-01-29 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
