### ISSUE TITLE
Client bundle contains server code

### ISSUE THREAD

**Issue by ihmpavel** [vercel/next.js#33791] opened 2022-01-29 21:47 UTC
### Run `next info` (available from version 12.0.8 and up)

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.9-canary.11
      react: 17.0.2
      react-dom: 17.0.2
```

### What version of Next.js are you using?

`12.0.9-canary.11`

### What version of Node.js are you using?

`16.13.1`

### What browser are you using?

`Chrome`

### What operating system are you using?

`macOS`

### How are you deploying your application?

`yarn next build`

### Describe the Bug

Client bundle contains server code.

### Expected Behavior

Client bundle should not contain server code. In this case bundled `crypto` module

### To Reproduce

1) create file `/utils/jwt.ts`
```
import crypto from 'crypto'

// client without 'crypto'
const decode = (token: string) => JSON.parse(atob(token.split('.')[1]))

// server with 'crypto'
const sign = (payload: string) => crypto.createHmac('sha256', 'secret').update(payload).digest('base64')

export { sign, decode }
```

2) create file `/pages/index.tsx`
```
import { decode } from '../utils/jwt'

const Home = () => {
   const [value, setValue] = useState(``)

   useState(() => setValue(decode('something')), [])

   return <h1>Decoded: {value}</h1>
}

export default Home
```

3) Analyze client bundle with `@next/bundle-analyzer`
4) The client bundle contains `node_modules/next/dist/compiled/crypto-browserify`, which is way bigger than anything else. 
Removing the function from the file and inlining it to `index.tsx` makes the bundle small again

**Comment by goremented** [comment] 2022-01-31 12:43
If you use any of the server code in a component, it is going to be included in client bundles. You should calculate that state on server and pass it to the client via `getServerSideProps` or other data fetching functions. https://nextjs.org/docs/basic-features/data-fetching/overview

**Comment by enesTufekci** [comment] 2022-01-31 12:44
If you use any of the server code in a component, it is going to be included in client bundles. You should calculate that state on server and pass it to the client via getServerSideProps or other data fetching functions. https://nextjs.org/docs/basic-features/data-fetching/overview

**Comment by ihmpavel** [comment] 2022-01-31 16:32
Hi, I understand that, but if you look closely, function `decode` only contains plain JS without `crypto` module. That makes no sense in clients bundle. And `crypto` is not imported in components, that means we do not need to polyfill that for browser environment.

**Comment by michalmalota** [comment] 2022-04-25 16:50
I found this useful to see what gets bundled into the client. https://next-code-elimination.vercel.app/

**Comment by timneutkens** [comment] 2022-04-28 10:09
Duplicate of https://github.com/vercel/next.js/issues/16153

**Closed by timneutkens** 2022-04-28 10:09 UTC
Labels: template: bug
