### ISSUE TITLE
Allow disabling pre-rendering, even in absence of getServerSideProps

### ISSUE THREAD

**Issue by cdaringe** [vercel/next.js#16124] opened 2020-08-12 16:43 UTC
# Feature request

Add a configuration option to globally disable pre-rendering.

## Is your feature request related to a problem? Please describe.

Pre-rendering takes memory, build cycles, and requires that in our that we handle cases where `getInitialProps` is _not_ called by next.js. We are fully dependent on `getInitialProps` to be called on our pages during SSR, and thus must detect and noop when next is pre-rendering on load or on build. It adds complexity and cost to our dev/build cycles for a feature we do not use.

We use SSR, but strictly via `getInitialProps`. This is to avoid the high cost penalty of hitting the server on every client-side navigation. By using getInitialProps, we offload all work to our user's browsers & CDNs post-browser-application-hydration, and not burden our otherwise busy servers. We understand why `getServerSideProps` is a great API, but have opted _not to use it_ for our performance-concerned architecture.

https://nextjs.org/docs/basic-features/pages#pre-rendering implicitly states that "you can use SSR" as an alt method to pre-rendering. However, I _am using SSR_, just not via the `getServerSideProps` API.

## Describe the solution you'd like

- an option to disable pre-rendering, likely in the root of next.config.js
- documented option, likely here: https://nextjs.org/docs/basic-features/pages#pre-rendering ?

## Describe alternatives you've considered

- using getServerSideProps, but deemed it to not be an option

## Additional context

n/a

Thanks for your time and consideration.

**Comment by timneutkens** [comment] 2020-08-13 11:20
Using `getInitialProps` already opts-out of pre-rendering.

**Comment by cdaringe** [comment] 2020-08-14 18:55
cool. thanks! i'd still like to disable it globally. my application expects resources that are not available during the pre-render phase, and to bypass, i must add a server method to each page. not a big deal, but not ideal either.

**Comment by timneutkens** [comment] 2020-08-15 11:45
Adding `getInitialProps` to `_app` does that. However keep in mind that if a page does not have blocking data requirements (e.g. getServerSideProps / getInitialProps) it's not going to need SSR.

Going to close this as it's already possible.

**Closed by timneutkens** 2020-08-15 11:45 UTC

**Comment by caub** [comment] 2020-12-07 12:42
It doesn't seem to work, as shown in this small example: https://repl.it/@caub/nextjs-server-side#pages/index.js

If there was to pre-rendering, there wouldn't be the console warning: "Warning: Did not expect server HTML to contain the text node "Hello" in <main>."

**Comment by balazsorban44** [comment] 2022-01-29 01:24
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
