### ISSUE TITLE
Next/Image breaking unoptimized with patch 12.1.4 to 12.1.5

### ISSUE THREAD

**Issue by supposedlysam-bb** [vercel/next.js#36128] opened 2022-04-13 17:28 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.5-canary.7
      react: 17.0.2
      react-dom: 17.0.2

warn  - Latest canary version not detected, detected: "12.1.5-canary.7", newest: "12.1.5".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.

### What browser are you using? (if relevant)

Chrome 100.0.4896.75 (Official Build) (x86_64)

### Describe the Bug

Previously when running Cypress tests with 12.1.4 all images appeared and the `src` attribute was as expected

### Next Image on 12.1.4
```html
<img alt="Rolling hills of a coffee farm in the mist" src="https://res.cloudinary.com/dqbiuatkh/image/upload/c_fill,h_692,w_1230/v1633381597/BBC_desktop-hero-video-V1_071521_1_nuogd0.jpg" decoding="async" data-nimg="fill" style="position: absolute; inset: 0px; box-sizing: border-box; padding: 0px; border: none; margin: auto; display: block; width: 0px; height: 0px; min-width: 100%; max-width: 100%; min-height: 100%; max-height: 100%; object-fit: cover;">
```

### Next Image on 12.1.5
after upgrading to 12.1.5 the images no longer load and show a `src` as follows

``` html
<img alt="Rolling hills of a coffee farm in the mist" sizes="100vw" srcset="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdqbiuatkh%2Fimage%2Fupload%2Fc_fill%2Ch_692%2Cw_1230%2Fv1633381597%2FBBC_desktop-hero-video-V1_071521_1_nuogd0.jpg&amp;w=640&amp;q=75 640w, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdqbiuatkh%2Fimage%2Fupload%2Fc_fill%2Ch_692%2Cw_1230%2Fv1633381597%2FBBC_desktop-hero-video-V1_071521_1_nuogd0.jpg&amp;w=750&amp;q=75 750w, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdqbiuatkh%2Fimage%2Fupload%2Fc_fill%2Ch_692%2Cw_1230%2Fv1633381597%2FBBC_desktop-hero-video-V1_071521_1_nuogd0.jpg&amp;w=828&amp;q=75 828w, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdqbiuatkh%2Fimage%2Fupload%2Fc_fill%2Ch_692%2Cw_1230%2Fv1633381597%2FBBC_desktop-hero-video-V1_071521_1_nuogd0.jpg&amp;w=1080&amp;q=75 1080w, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdqbiuatkh%2Fimage%2Fupload%2Fc_fill%2Ch_692%2Cw_1230%2Fv1633381597%2FBBC_desktop-hero-video-V1_071521_1_nuogd0.jpg&amp;w=1200&amp;q=75 1200w, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdqbiuatkh%2Fimage%2Fupload%2Fc_fill%2Ch_692%2Cw_1230%2Fv1633381597%2FBBC_desktop-hero-video-V1_071521_1_nuogd0.jpg&amp;w=1920&amp;q=75 1920w, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdqbiuatkh%2Fimage%2Fupload%2Fc_fill%2Ch_692%2Cw_1230%2Fv1633381597%2FBBC_desktop-hero-video-V1_071521_1_nuogd0.jpg&amp;w=2048&amp;q=75 2048w, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdqbiuatkh%2Fimage%2Fupload%2Fc_fill%2Ch_692%2Cw_1230%2Fv1633381597%2FBBC_desktop-hero-video-V1_071521_1_nuogd0.jpg&amp;w=3840&amp;q=75 3840w" src="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fdqbiuatkh%2Fimage%2Fupload%2Fc_fill%2Ch_692%2Cw_1230%2Fv1633381597%2FBBC_desktop-hero-video-V1_071521_1_nuogd0.jpg&amp;w=3840&amp;q=75" decoding="async" data-nimg="fill" style="position: absolute; inset: 0px; box-sizing: border-box; padding: 0px; border: none; margin: auto; display: block; width: 0px; height: 0px; min-width: 100%; max-width: 100%; min-height: 100%; max-height: 100%; object-fit: cover;">
```

The `src` attr is now url encoded and prepended with `/_next/image?url=`

### Expected Behavior

The image should load when passing in a url matching a registered domain in the `next.config.js`

### Next Config
```js
module.exports = {
  images: {
    domains: ["res.cloudinary.com"],
  },
};
```

#### next.config.js
```js
module.exports = {
  images: {
    domains: ["res.cloudinary.com"],
  },
};
```

### Cypress Test
```tsx
it("renders the 16:9 desktop image", () => {
      const src = "https://res.cloudinary.com/dqbiuatkh/image/upload/c_fill,h_692,w_1230/v1633381597/BBC_desktop-hero-video-V1_071521_1_nuogd0.jpg"

      cy.mount(
        <Image
            layout="fill"
            objectFit="cover"
            src={src}
            unoptimized={false}
        />
      );
      cy.waitForReact();
      cy.viewport("macbook-15");
      cy.get("img").should("have.attr", "src", src)
    });
```

Run the above test (or however you want to render the Image with the provided URL) without modification from 12.1.4 to 12.1.5 and 12.1.5 breaks.

**Comment by bonesoul** [comment] 2022-04-14 14:53
same here..

**Comment by styfle** [comment] 2022-04-20 13:51
In the code snippet above, `unoptimized={false}` is the default behavior which is to optimize the image.

Did you mean `unoptimized={true}` which will bypass optimization and serve the image as-is?

**Comment by supposedlysam-bb** [comment] 2022-04-20 16:51
I think the problem is that, without changes to the code, I updated from 12.1.4 to 12.1.5 and things started breaking. They were passing in 12.1.4 but not in 12.1.5. Since this was a patch update I wouldn't have expected this.

**Comment by styfle** [comment] 2022-04-20 18:58
It sounds like `unoptimized` was not actually reading the value and just checking for existence of the prop. So the change would be considered a bug fix which would be suitable for semver patch.

**Comment by timneutkens** [comment] 2022-04-21 08:57
Basically in 12.1.4 there was a bug where you app was running with unoptimized images even though your code is indicating to optimize the images (`unoptimized={false}`) so that was fixed. If you want to use unoptimized images you have to set `unoptimized` or `unoptimized={true}` as both hold the `true` value, that would match with what you accidentally had previously.

Going to close this issue as the 12.1.5 behavior is not a bug 👍

**Closed by timneutkens** 2022-04-21 08:57 UTC
Labels: template: bug
