### ISSUE TITLE
Experimental rewrites don't work on iOS devices

### ISSUE THREAD

**Issue by sospedra** [vercel/next.js#13655] opened 2020-06-02 07:29 UTC
# Bug report

## Describe the bug

The new experimental feature of rewrites messes up on iOS devices.

Given this rewrite `domain.tld/a` to `other.tld/path/to`.
If consumed with a laptop, Android, _et altri_ it redirects correctly.
If consumed with iOS (iPhone/iPad) it redirects to `domain.tld/path/to` (mixes the domain and pathname).

## To Reproduce

1. Rewrites [are here](https://github.com/sospedra/sospedra.me/blob/master/next.config.js#L37-L41)
2. Go to https://sospedra.me/r/rjpr with a laptop (you're gonna end up in Spotify)
3. Go to the same address with an iOS device (you're gonna end up in a nextjs 404)

## Expected behaviour

It should redirect properly regarding the OS.

## Additional context

I assume this has something to do with Vercel's machinery because it works great in `yarn dev` and `yarn start`. It only goes crazy when deployed.

**Comment by vijendramisra** [comment] 2020-06-02 10:04
fdsfsdd

**Comment by ijjk** [comment] 2020-06-12 18:59
Hi, this appears to be due to the handling of the resource you are rewriting to and not from the `rewrites` feature itself. You are rewriting to Spotify which attempts to handle the link differently on iOS in production. 

This should be a redirect instead of a rewrite to ensure the resource you are pointing the user to can work as expected. 

I'm going to close this since it doesn't appear to be a bug in Next.js/Vercel, if this seems incorrect feel free to reply with additional info and we can look into it further

**Comment by ijjk** [comment] 2020-06-12 19:06
Hi, this appears to be due to the handling of the resource you are rewriting to and not from the `rewrites` feature itself. You are rewriting to Spotify which attempts to handle the link differently on iOS in production. 

This should be a redirect instead of a rewrite to ensure the resource you are pointing the user to can work as expected. 

I'm going to close this since it doesn't appear to be a bug in Next.js/Vercel, if this seems incorrect feel free to reply with additional info and we can look into it further

**Closed by ijjk** 2020-06-12 19:06 UTC
Labels: type: needs investigation

**Comment by sospedra** [comment] 2020-06-13 09:25
I see what you mean @ijjk
Thanks for the analysis and reply.

I understand the issue is closed now, but may I asked if there's any way to do the redirect within the context of Vercel nextjs/now?🤔

Ty again

**Comment by ijjk** [comment] 2020-06-13 23:50
@sospedra you can create a redirect in a similar way to how you are adding the rewrites in your `next.config.js` e.g.

```js
module.exports = {
  experimental: {
    async redirects() {
      return [
        {
          source: '/r/rjpr',
          destination: 'https://open.spotify.com/playlist/26NYRcXPyIVrItOtlJ5ahO',
          permanent: false
        }
      ]
    }
  }
}
```

**Comment by sospedra** [comment] 2020-06-15 09:46
Damn boy! Didn't know about `rewrites`/`redirects`
Super appreciated @ijjk that works like a charm ☺️

**Comment by balazsorban44** [comment] 2022-01-29 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
