### ISSUE TITLE
[Next.js Site] Improve usability in the feedback input on mobile

### ISSUE THREAD

**Issue by lfades** [vercel/next.js#16911] opened 2020-09-07 17:42 UTC
This is our feedback input at the bottom of all of our documentation pages and blog posts:

![image](https://user-images.githubusercontent.com/4278345/92409760-5583fd80-f107-11ea-91a5-ff72f44db86a.png)

Currently it has some issues on mobile:

- After selecting an emoji the email input is not focused properly on iOS and the page doesn't scroll down to focus the form
- On iOS, scrolling down can make the form disappear (this one is probably related to the issue above)
- Changing the emoji doesn't focus the email input again (in some cases it works)

**Comment by weichienhung** [comment] 2020-09-08 06:02
Just wonder why not report this on [next-site](https://github.com/vercel/next-site) repo. Looks like the code is not in this repo.

**Comment by timneutkens** [comment] 2020-09-08 07:24
> Just wonder why not report this on [next-site](https://github.com/vercel/next-site) repo. Looks like the code is not in this repo.

All Next.js issues including for the website are tracked in this repository.

**Comment by malitov** [comment] 2020-09-10 12:42
I'll take this issue.

**Comment by leerob** [comment] 2020-09-15 23:13
Merged! Thanks so much for helping @malitov ❤️

**Closed by leerob** 2020-09-15 23:13 UTC
Labels: good first issue, kind: bug, type: website

**Comment by balazsorban44** [comment] 2022-01-29 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
