### ISSUE TITLE
Not all styled components working in development

### ISSUE THREAD

**Issue by DaTurboD** [vercel/next.js#18219] opened 2020-10-25 10:37 UTC
# Bug report

## Describe the bug

After i run `next` not all styled components are working in development mode. Everything was fine like a week ago but suddenly some components are not passing any css anymore. In production everything works as expected.

## To Reproduce

I followed the example [with-styled-components](https://github.com/vercel/next.js/tree/canary/examples/with-styled-components), so my `_document.js`, `_app.js` and `.babel.rc` are looking like the following

_document.js
```
import Document from 'next/document';
import { ServerStyleSheet } from 'styled-components';

export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const sheet = new ServerStyleSheet();
    const originalRenderPage = ctx.renderPage;

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: App => props => sheet.collectStyles(<App {...props} />)
        });

      const initialProps = await Document.getInitialProps(ctx);
      return {
        ...initialProps,
        styles: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        )
      };
    } finally {
      sheet.seal();
    }
  }
}
```

_app.js
```
import Router from "next/router";
import React, { useEffect } from "react";
import App from "next/app";
import { init } from '@socialgouv/matomo-next';
import GlobalStyle from '@/styles/global.js'
//import CookieBanner from '@/components/cookies/cookie-banner' not used due to no cookies
import "prismjs/themes/prism-tomorrow.css";
import 'lazysizes';

const MATOMO_URL = process.env.NEXT_PUBLIC_MATOMO_URL;
const MATOMO_SITE_ID = process.env.NEXT_PUBLIC_MATOMO_SITE_ID;

class MyApp extends App {
  componentDidMount() {
    if (window.location.href.includes("mxd.codes")) {
      init({ url: MATOMO_URL, siteId: MATOMO_SITE_ID });
    }
  }
  render() {
    const { Component, pageProps } = this.props;
    return (
      <>
        <GlobalStyle/>
        <Component {...pageProps} />
      </>
    )
  }
}

export default MyApp;
```

.babelrc
```
{
    "presets": ["next/babel"],
    "plugins": [
        ["styled-components", { "ssr": true }]
    ]
}
```

## Expected behavior

Css properties should be passed to components.

## Screenshots

Production:
![grafik](https://user-images.githubusercontent.com/40794289/97104714-499fcb00-16b6-11eb-827b-c48d4122266b.png)

Development:
![grafik](https://user-images.githubusercontent.com/40794289/97104723-5e7c5e80-16b6-11eb-8094-8e429c4aa515.png)

## System information

- OS: [Windows]
- Version of Next.js: [e.g. 9.5.5]
- Version of Node.js: [e.g. 12.19.0]

**Comment by jamesmosier** [comment] 2020-10-25 19:10
Hi @DaTurboD. Could you create a repository with a reproduction of this? I wasn't able to reproduce as described.

**Comment by DaTurboD** [comment] 2020-10-25 20:31
Hi @jamesmosier. The problem is existing in my current repository https://github.com/DaTurboD/mxd-codes-frontend

**Comment by filingroove** [comment] 2020-10-26 16:12
I too have this issue. `styled-components` broke with no warning in development, but working just fine in production :) My setup is also based on [with-styled-components](https://github.com/vercel/next.js/tree/canary/examples/with-styled-components) example  

![](https://i.imgur.com/fQumYOa.png)

I'm trying to narrow it down to something reproducible, but haven't managed it just yet. It's an SSR issue for sure because when I add `{ ssr: false }` to my dynanic import, the issue goes away.

Console doesn't show any errors related to these specific components, but other component logs this:
```
webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:88 Warning: Prop `className` did not match. Server: "sc-1bt15ef-0 dQwXrj" Client: "sc-1bt15ef-0 fyNZCT"
    in header (created by styled.header)
    in styled.header (created by Header)
    in Header (created by Root)
    in section (created by styled.section)
    in styled.section (created by Root)
    in SlotProvider (created by Root)
    in ToastProvider (created by Root)
    in Be (created by Root)
    in AuthProvider (created by Root)
    in ResponsiveProvider (created by Root)
    in Root (created by withRouter(Root))
    in withRouter(Root) (created by e)
    in e
    in ErrorBoundary (created by ReactDevOverlay)
    in ReactDevOverlay (created by Container)
    in Container (created by AppContainer)
    in AppContainer
    in Root
printWarning @ webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:88
```

**Comment by filingroove** [comment] 2020-10-26 16:23
Downgrading to `styled-components@5.1.0` fixed the issue :) Not sure if this is an issue with Next.js

**Comment by jamesmosier** [comment] 2020-10-26 17:14
Closing for now. If anyone has a reproduction feel free to post it 🚀

**Comment by DaTurboD** [comment] 2020-10-26 19:00
Hi @jamesmosier. You can use this repository as reproduction of this issue: https://github.com/DaTurboD/mxd-codes-frontend

**Comment by jamesmosier** [comment] 2020-10-26 19:18
I wasn't able to reproduce with the [with-styled-components](https://github.com/vercel/next.js/tree/canary/examples/with-styled-components) repository, so it must be something specific to your setup. 

It'll take some time to dig in as it is quite a large repository.

**Comment by DaTurboD** [comment] 2020-10-26 20:50
Downgrading to styled-components@5.1.1 or 5.1.0 unfortunately didn't fix the issue for me. Also setting ssr to false in `.babelrc` had no effect. Please let me know if i can help in any way.

**Closed** 2020-10-27 23:18 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
