### ISSUE TITLE
Get react-refresh-utils/runtime.js Error:react-refresh-runtime.development.js:465 Uncaught TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by XShellv** [vercel/next.js#16005] opened 2020-08-08 15:21 UTC
# Bug report

## Describe the bug

I am ready to set up  next.js by `npx create-next-app` and  `yarn run dev`,howerver I got a js error in chrome,while it works well in firefox. what happend ????

## Screenshots

![image](https://user-images.githubusercontent.com/45475139/89713903-730d5c80-d9cd-11ea-9339-266f33efff3c.png)

## Dependency
```json
{
  "name": "blog",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "next": "^9.5.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  }
}
```
- win64
- node 12.3.0
- Chrome 84.0.4147.105（正式版本） （64 位）

**Comment by timneutkens** [comment] 2020-08-08 15:32
Please provide a reproduction repository

**Comment by XShellv** [comment] 2020-08-08 17:21
> Please provide a reproduction repository

git@github.com:XShellv/blog.git

**Comment by matamatanot** [comment] 2020-08-08 19:25
https://github.com/XShellv?tab=repositories

Not found.
Is it a private repository?

**Comment by XShellv** [comment] 2020-08-09 00:12
> https://github.com/XShellv?tab=repositories
> 
> Not found.
> Is it a private repository?

sorry,I just change it from private to public,please try again.

**Comment by XShellv** [comment] 2020-08-09 00:16
I think it should works well in your computer.because it is nextjs example. I have tried to change the React version and next version many times but not work.

**Comment by XShellv** [comment] 2020-08-10 14:49
I have solved this problem, the React dev tools is not compatible with latest next version. unstall it !!!!

**Comment by Timer** [comment] 2020-08-10 15:27
@XShellv were you on an old dev tools version? Can you try re-installing the extension (which should update it)? Thanks!

**Comment by XShellv** [comment] 2020-08-11 15:22
> @XShellv were you on an old dev tools version? Can you try re-installing the extension (which should update it)? Thanks!

I downloaded it on November 14, 2019 and the version is v16.12.0.

**Comment by Timer** [comment] 2020-08-11 16:12
This is the latest version of the extension:
![image](https://user-images.githubusercontent.com/616428/89921603-ec729e00-dbcb-11ea-9ee9-a433522d340a.png)

**Comment by Timer** [comment] 2020-09-03 02:36
Closing as no reproduction provided and it's been 22 days, assuming this is solved!

**Closed by Timer** 2020-09-03 02:36 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
