### ISSUE TITLE
Middlewares only work when the page directory exists

### ISSUE THREAD

**Issue by marcospassos** [vercel/next.js#42814] opened 2022-11-11 22:45 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

  Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.3
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Middlewares are completely ignored if the page directory doesn't exist. When using Next 13, you don't need it most of the time, so it is counterintuitive that it is required for the middleware to work – even if it's intended, it should at least be documented somewhere. I spent quite some time debugging it before finding the root cause.

### Expected Behavior

To work regardless of the page directory existence.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://codesandbox.io/s/magical-proskuriakova-edh1hn

### To Reproduce

- Start the service
- Open the index
- Nothing is logged (the middleware logs a message)

**Comment by balazsorban44** [comment] 2022-11-14 11:00
Duplicate of #41995

**Closed by balazsorban44** 2022-11-14 11:00 UTC
Labels: template: bug
