### ISSUE TITLE
unable to successfully run `yarn dev` after `npx create-next-app`

### ISSUE THREAD

**Issue by bluesatyr** [vercel/next.js#26917] opened 2021-07-04 16:39 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.17.2

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

yarn dev

### Describe the Bug

When I do a clean install using `npx create-next-app` then immediately cd into the directory and run `yarn dev` I get two errors and the app fails to render.

### Expected Behavior

Next.js start page should render in the browser at localhost:3000

### To Reproduce

I do the following:
1. `npx create-next-app`
2. cd to my project
3. `yarn dev`
4. open localhost:3000 in Chrome

I get two errors:
![image](https://user-images.githubusercontent.com/3218539/124392596-96678700-dcc4-11eb-8167-4574f2d13be1.png)
![image](https://user-images.githubusercontent.com/3218539/124392607-ad0dde00-dcc4-11eb-8b5a-486aad7000f7.png)

**Comment by AryanBeezadhur** [comment] 2021-07-05 17:27
Here is the solution for now:

> Click on open folder from the sidebar (for VSCode users) , then navigate to the folder of the just created Next.js project.
> This will open the project in a new VSCode window.
> Now you can run `npm run dev`

Source: https://github.com/vercel/next.js/issues/16535#issuecomment-738857277

**Comment by timneutkens** [comment] 2021-07-05 17:28
Closing as duplicate of #16535

**Closed by timneutkens** 2021-07-05 17:28 UTC
Labels: template: bug

**Comment by SchramlTim** [comment] 2021-07-05 17:36
I had the same issue under windows.
For me its helped to run the command with admin permissions.

**Comment by balazsorban44** [comment] 2022-01-28 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
