### ISSUE TITLE
Dockerized NextJS running on Cloud Run

### ISSUE THREAD

**Issue by danny-fallas** [vercel/next.js#29284] opened 2021-09-22 04:05 UTC
### Describe the feature you'd like to request

Hello all, I want to be able to use the environment variables set on the revision of the container on Cloud Build.
Basically using the env variables passed on local using a custom docker-compose file:

`- environment:
     - NEXT_PUBLIC_=value`

I have to use a solution copying an env file to the .env.production file during the image build time. It should allow you to get the env variables from the container settings here.

### Describe the solution you'd like

Being able to access the Cloud Run variables settings and setting them up for usage on the nextjs environment.
https://cloud.google.com/run/docs/configuring/environment-variables

### Describe alternatives you've considered

Something similar to how heroku works. Not sure if this is not possible because of the multistage deployment offered by default on the documentation.

**Comment by ijjk** [comment] 2021-09-22 04:15
Closing as a duplicate of https://github.com/vercel/next.js/discussions/29286 please only open one thread.

**Closed by ijjk** 2021-09-22 04:15 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-27 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
