### ISSUE TITLE
next/image img elements missing width and height

### ISSUE THREAD

**Issue by tairosonloa** [vercel/next.js#35953] opened 2022-04-06 21:56 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.5-canary.3
      react: 17.0.2
      react-dom: 17.0.2

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Image elements missing `width` and `height` when using `next/image`. Failing in Google Lighthouse checks.
<img width="628" alt="Captura de pantalla 2022-04-06 a las 23 55 04" src="https://user-images.githubusercontent.com/14878189/162078463-5c0681f5-3205-4ee6-bde4-afc23e90272b.png">

### Expected Behavior

`width` and `height` to be set.

### To Reproduce

1. Build an app with images served using next/image
2. Go to app in Chrome browser
3. Open devtools
4. Run Lighthouse on desktop
5. Scroll down to Performance section
6. See error: "Image elements do not have explicit width and height"

**Comment by balazsorban44** [comment] 2022-04-07 07:15
I believe this is a duplicate of https://github.com/vercel/next.js/issues/35091, a false-positive by Lighthouse.

A fix has been merged already: https://github.com/GoogleChrome/lighthouse/pull/13737 but there is no ETA.

**Closed by balazsorban44** 2022-04-07 07:15 UTC
Labels: template: bug, area: next/image
