### ISSUE TITLE
Router push with URL object doesn't replace path parameter by the query property value

### ISSUE THREAD

**Issue by souzantero** [vercel/next.js#18409] opened 2020-10-28 18:55 UTC
# Bug report

## Description

The router doesn't be replacing the first parameter from the `pathname` by the property value defined in `query` object 

## Example

If I have the following pages directory tree `/pages/posts/[postId]/edit` and use router push with the following parameters

```
{
    pathname: '/posts/[postId]/edit',
    query: { postId: 1 }
}
```

It's ok, the router sends to the browser the following path `/posts/1/edit`

But, if I have a pages directory tree like `/pages/posts/[postId]/comments/[commentId]` and use router push with the following parameters

```
{
    pathname: '/posts/[postId]/comments/5',
    query: { postId: 1 }
}
```

The router sends to the browser the following path `/posts/[postId]/comments/5?postId=1`. The router doesn't replace the parameter `postId` by the query property value.

My Next.js version is `10.0.0`

**Comment by ijjk** [comment] 2020-10-28 19:38
Hi, the `pages` folder name should not be included in the pathname, e.g. if you have `pages/posts/[postId].js` then the pathname should be `/posts/[postId]`. We have tests covering this feature [here](https://github.com/vercel/next.js/blob/44fe971e6b3ba240ecd8f2d2d92025d831bc609d/test/integration/dynamic-routing/pages/index.js#L25-L32) which are passing so if you're still encountering this with the corrected `pathname` then a repo with a minimal reproduction would be needed for further investigation

**Comment by souzantero** [comment] 2020-10-28 19:52
> Hi, the `pages` folder name should not be included in the pathname, e.g. if you have `pages/posts/[postId].js` then the pathname should be `/posts/[postId]`. We have tests covering this feature [here](https://github.com/vercel/next.js/blob/44fe971e6b3ba240ecd8f2d2d92025d831bc609d/test/integration/dynamic-routing/pages/index.js#L25-L32) which are passing so if you're still encountering this with the corrected `pathname` then a repo with a minimal reproduction would be needed for further investigation

Sorry, I don't be using the `pages` folder name in the `pathname` on my code, only in the example, I already fix it.

**Comment by ijjk** [comment] 2020-10-28 19:59
@souzantero yeah if you are still encountering this issue after double checking the `pathname` then a minimal reproduction will be needed to help investigate

**Comment by souzantero** [comment] 2020-10-28 20:35
> @souzantero yeah if you are still encountering this issue after double checking the `pathname` then a minimal reproduction will be needed to help investigate

@ijjk I create this [repo](https://github.com/souzantero/nextjs-router-push-issue) that reproduce the issue.

**Comment by ijjk** [comment] 2020-10-28 20:40
So it looks like you are trying to mix prepared paths and interpolation which isn't an intended use of the feature. You should either provide the path with values already inserted `/posts/1/comments/5` or use interpolation `{ pathname: '/posts/[postId]/comments/[commentId], query: { postId: 1, commentId: 5 } }` not a combination of the two

**Comment by souzantero** [comment] 2020-10-28 21:13
Ok, thank you so much for the support @ijjk .

**Comment by ijjk** [comment] 2020-10-28 21:15
@souzantero happy to help, I'm gonna close this since it seems to be resolved.

**Closed by ijjk** 2020-10-28 21:15 UTC

**Comment by power-f-GOD** [comment] 2022-01-12 10:49
Hi, @ijjk .
I get this error whenever I use href directly without interpolation. According to the examples in the link you sent above, it's supposed to work, but this error ensues every time:
```
Unhandled Runtime Error
Error: The provided `href` (/orders/[order_id]) value is missing query values (order_id) to be interpolated properly. Read more: https://nextjs.org/docs/messages/href-interpolation-failed
```

I'm passing href directly like so: `<Link href={`/orders/some_uuid`}>Order</Link>` and then it throws the error above.

Kindly, what am I doing wrong here? And how do I fix?

Thanks for your swift response.
