### ISSUE TITLE
getting error on leaflet dynamic import on Next.js 10

### ISSUE THREAD

**Issue by Sly777** [vercel/next.js#18336] opened 2020-10-27 20:43 UTC
# Bug report

## Describe the bug

After updating the project we are working on, we started to get a critical error on dynamic load level of leaflet. The important part is that we are loading the script with SSR: false. Possibly, it can be related to leaflet images inside of the package.

Error message:
```
event - compiled successfully
dyld: lazy symbol binding failed: Symbol not found: _g_once_impl
  Referenced from: xxxx/node_modules/sharp/build/Release/sharp.node
  Expected in: xxxx/node_modules/optimized-images-loader/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib

dyld: Symbol not found: _g_once_impl
  Referenced from: xxxx/node_modules/sharp/build/Release/sharp.node
  Expected in: xxxx/node_modules/optimized-images-loader/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib

error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## To Reproduce

Example usage;
```
// componentA.tsx
const FullMap: any = dynamic(() => import('@components/componentB') as any, {
  ssr: false,
});

// componentB.tsx
import {
  TileLayer,
  Map as LeafletMap,
  Marker,
  Tooltip,
  CircleMarker,
} from 'react-leaflet-universal';
import L from 'leaflet';
import MarkerClusterGroup from 'react-leaflet-markercluster';

```

## Expected behavior

Next.js needs to run it with lazy-load as work proper before on next.js 9.5.x

## System information

- OS: macOS
- Browser: all
- Next.js: 10.0.0
- Node.js: 12.18.2

**Comment by wbunting** [comment] 2020-10-30 10:40
I have the same error in some test code of next/image, but think it is likely due to a different dependency conflict

**Comment by wbunting** [comment] 2020-10-31 10:21
My problem here was indeed a conflicting dependency -- using "resolutions" to peg sharp to the next.js current optional dependency version fixed this

**Comment by PaulSenon** [comment] 2021-02-27 15:01
@Sly777 I had the same issue, I fond my answer here: https://github.com/vercel/next.js/issues/18946. Not sure it is exactly the same problem, but it might help...

1) `yarn add sharp`
2) add the following snippet in your package.json file with the same sharp version installed from step 1
```
"resolutions": {
 "sharp": "0.27.0"
}
```
3) rebuild sharp binaries using `npm rebuild sharp`

If it's really not helping let me know, I'll delete this post to not spam this issue history with useless stuff...

**Comment by ijjk** [comment] 2021-09-19 16:34
Closing as a duplicate of https://github.com/vercel/next.js/issues/18946 per above

**Closed by ijjk** 2021-09-19 16:34 UTC
Labels: good first issue, please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
