### ISSUE TITLE
Incorrect router "asPath" property on server-side when trailing slashes are enabled

### ISSUE THREAD

**Issue by jleck** [vercel/next.js#16929] opened 2020-09-08 12:36 UTC
# Bug report

## Describe the bug

When `trailingSlashes: true` is added to `next.config.js`, server-side generation does not include the trailing slash in the router `asPath` property.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Enable trailing slashes
2. Add `useRouter()` to component
3. Log `asPath` property

## Expected behavior

Server-side should include a trailing slash when generating.

**Comment by tsriram** [comment] 2020-09-08 16:22
I'd like to work on this if no one has started on this yet :)

**Comment by tsriram** [comment] 2020-09-08 17:36
Well, I tried to reproduce this but couldn't. Not sure if I understand the issue correctly.

Here's the basic repro - https://github.com/tsriram/next-16929 (and deployed here - https://next-16929.vercel.app/). I have set `trailingSlash: true` (not `trailingSlashes: true` as mentioned above) and I see the trailing slash in both client & server rendered pages. 

@jleck - could you check if this is working as expected?

**Comment by jleck** [comment] 2020-09-09 10:46
Hi @tsriram, will see if I can cause this error.

**Comment by tsriram** [comment] 2020-09-21 10:23
@jleck did you get a chance to check this? :)

**Comment by vitaliemiron** [comment] 2020-09-24 14:55
I also can't reproduce. @jleck  could you provide a repo ?

**Comment by fostyfost** [comment] 2020-10-09 09:54
Hello, please see my issue https://github.com/vercel/next.js/issues/17740

**Comment by timneutkens** [comment] 2020-10-09 10:54
Duplicate of #17740

**Closed by timneutkens** 2020-10-09 10:54 UTC
Labels: good first issue, kind: story

**Comment by balazsorban44** [comment] 2022-01-29 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
