### ISSUE TITLE
Using the future flag, the build fails (including next dev and other runtimes)

### ISSUE THREAD

**Issue by rubybb** [vercel/next.js#23517] opened 2021-03-29 19:27 UTC
Using the future flag, the build fails (including next dev and other runtimes)
```
info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
Error: Cannot find module 'webpack/lib/dependencies/ConstDependency'
```

_Originally posted by @rubybb in https://github.com/vercel/next.js/discussions/23498#discussioncomment-545249_

**Comment by timneutkens** [comment] 2021-03-30 07:59
Closing as this is not actionable. Please follow the issue template.

**Closed by timneutkens** 2021-03-30 07:59 UTC

**Comment by balazsorban44** [comment] 2022-01-28 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
