### ISSUE TITLE
Is throwing an unnecessary error when getStaticProps & getServerSideProps are undefined

### ISSUE THREAD

**Issue by aralroca** [vercel/next.js#11309] opened 2020-03-24 00:44 UTC
# Bug report

## Describe the bug

When `getStaticProps` and `getServerSideProps` exist both as an export, is throwing an error.

```
You can not use getStaticProps with getServerSideProps. To use SSG, please remove getServerSideProps
```

Looks OK, however, IMO it should throw this error only when both are functions. With this, it will be possible to use conditional exports. 

```js
export let getStaticProps
export let getServerSideProps

if(process.env.SSG) {
  getStaticProps = loadData
} else { 
  getServerSideProps = loadData
}

```

## To Reproduce

```js
export const getStaticProps = undefined
export const getServerSideProps = undefined
```

## Expected behavior

With this:

```js
export const getStaticProps = undefined
export const getServerSideProps = async ctx => ({ props: { itWorks: false } })
```

I expect that `getServerSideProps` is executed because `getStaticProps` is not defined.

With this:

```js
export const getStaticProps = async ctx => ({ props: { itWorks: false } })
export const getServerSideProps = undefined
```

I expect that `getStaticProps` is executed because `getServerSideProps` is not defined.

**Comment by Timer** [comment] 2020-03-24 00:51
This behavior will not / should not work by design:
```js
export let getStaticProps
export let getServerSideProps

if(process.env.SSG) {
  getStaticProps = loadData
} else { 
  getServerSideProps = loadData
}
```

You *must* export a function.

If the above works when you're not mixing the two, we need to issue a patch release to disallow such behavior.

**Comment by aralroca** [comment] 2020-03-24 00:59
Ok! But why this restriction instead of just ignore when there aren't functions?

**Comment by timneutkens** [comment] 2020-03-24 09:05
Because getStaticProps en getServerSideProps are tree shaken from browser bundles and what you're trying to do (dynamic assignment) makes it impossible to tree shake it.

**Comment by aralroca** [comment] 2020-03-24 09:36
Ok. In that case, it makes sense to me! Thanks to clarifying this @timneutkens

**Comment by felipenmoura** [comment] 2020-10-11 19:06
Is there a way to use them both together?
I mean...my first thought was to use static props for some info (like version, port, path, envType, etc) and serverside props to api values.

**Comment by timneutkens** [comment] 2021-11-18 09:39
Going to close this issue as it's using getStaticProps/getServerSideProps in an unsupported way. 

@felipenmoura there are some feature requests for a behavior like that but getServerSideProps and getStaticProps are two different methods intentionally, they enable completely different behaviors.

**Closed by timneutkens** 2021-11-18 09:39 UTC
Labels: type: needs investigation, kind: story

**Comment by balazsorban44** [comment] 2022-01-27 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
