### ISSUE TITLE
Using middleware prevents correct 404 page for not existing statically generated pages

### ISSUE THREAD

**Issue by FelHa** [vercel/next.js#39654] opened 2022-08-16 11:57 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

  Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.13.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.6-canary.0
      eslint-config-next: N/A
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

If a page with `getStaticProps` returns `{ notFound: true }` this will only work if that page is requested via `GET` request type `document`. As soon as it is a request of type fetch for Link/router the app performs a `HEAD` request which returns 200 and results in a pageload without static data.

This results in a behaviour where opening a link to a page which should redirect to 404 or using the next router to do so, the existing middleware function prevents a correct redirect to 404. 

### Expected Behavior

Using Link/router should also redirect to 404 if the page returns `{ notFound: true }` in  `getStaticProps` when the app uses a middleware function.

### Link to reproduction

https://github.com/FelHa/nextjs-middleware-404.git

### To Reproduce

1. Clone repo: https://github.com/FelHa/nextjs-middleware-404.git
2. Build app: `npm run build`
3. Start app: `npm run start`
4. Go to http://localhost:3000/dynamic/dynamic-to-nowhere > 404
5. Go to http://localhost:3000/dynamic/foo and click on 'to dynamic nowhere' > 200

**Comment by ijjk** [comment] 2022-08-16 13:26
Hi, this sounds like a duplicate of https://github.com/vercel/next.js/issues/39654 so gonna close this, let us know if this isn't the case.

**Closed by ijjk** 2022-08-16 13:26 UTC
Labels: template: bug
