### ISSUE TITLE
`next build` freezes right after `npm:load`

### ISSUE THREAD

**Issue by ntd** [vercel/next.js#32399] opened 2021-12-11 18:17 UTC
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Irrelevant

### What operating system are you using?

ArchLinux

### How are you deploying your application?

Irrelevant

### Describe the Bug

Whenever I trigger a `npm run build` command, the node process hogs one core of my CPU and it freezes indefinitely. `npm run dev` works fine.

After a `npm install next@canary`, the outcome did not change.

### Expected Behavior

An error message or a successful build.

### To Reproduce

The project is public, so you can clone it:
```
git clone https://github.com/ntd/adg.entidi.com.git -b issue-32399
cd adg.entidi.com
npm install
npm run build --verbose
```
And this is what I get:
```
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build', '--verbose' ]
npm info using npm@8.3.0
npm info using node@v16.13.1
[ ... snip ...]

> build
> next build

(( ...emtpy... )) timing npm:load Completed in 21ms
```
... then the spinner stops and I cannot exit with <kbd>Ctrl</kbd><kbd>C</kbd> (I need to send a `SIGKILL` to the node process).

**Comment by ntd** [comment] 2021-12-12 09:05
I just reduced my testcase. The following code triggers the issue: 
```
import { visit } from 'unist-util-visit'
visit(whatever, '2', (node, _, parent) => {})
```
The full repository with the above code in `lib/api.ts` is in the [issue-32399](/ntd/adg.entidi.com/tree/issue-32399) branch.

**Comment by balazsorban44** [comment] 2021-12-13 13:46
Duplicate of #32139

This is a bug in TypeScript.

 https://github.com/vercel/next.js/issues/32193#issuecomment-987486975

**Closed by balazsorban44** 2021-12-13 13:46 UTC
Labels: template: bug

**Comment by ntd** [comment] 2021-12-13 14:01
Upstream bug report: microsoft/TypeScript#46900

**Comment by balazsorban44** [comment] 2022-01-27 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
