### ISSUE TITLE
Impossible to deploy v13.1.6

### ISSUE THREAD

**Issue by Supertinypeanut** [vercel/next.js#45708] opened 2023-02-08 14:47 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### **What version of Next.js are you using?**
 v13.1.6

### **What version of Node.js are you using?**
v14.17.6

### What browser are you using?
Chrome

### What operating system are you using?
iOS

### Which example does this report relate to?

https://github.com/vercel/next.js/issues/30543

### Describe the Bug

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ledou-cultural-creation@0.1.0~prebuild: ledou-cultural-creation@0.1.0
6 info lifecycle ledou-cultural-creation@0.1.0~build: ledou-cultural-creation@0.1.0
7 verbose lifecycle ledou-cultural-creation@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle ledou-cultural-creation@0.1.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/huasheng/VSCode/03-Student/ledou-cultural-creation/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle ledou-cultural-creation@0.1.0~build: CWD: /Users/huasheng/VSCode/03-Student/ledou-cultural-creation
10 silly lifecycle ledou-cultural-creation@0.1.0~build: Args: [ '-c', 'next build' ]
11 silly lifecycle ledou-cultural-creation@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle ledou-cultural-creation@0.1.0~build: Failed to exec build script
13 verbose stack Error: ledou-cultural-creation@0.1.0 build: `next build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid ledou-cultural-creation@0.1.0
15 verbose cwd /Users/huasheng/VSCode/03-Student/ledou-cultural-creation
16 verbose Darwin 21.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error ledou-cultural-creation@0.1.0 build: `next build`
22 error Exit status 1
23 error Failed at the ledou-cultural-creation@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

### Expected Behavior

Hope to compile successfully

### To Reproduce

Hi teams, compiled successfully the first time, but failed the second time

**Comment by nbayat** [comment] 2023-02-08 15:06
I'm sorry, but the log does not contain enough information. To determine if the problem is really related to npm or not, could you try running the build process directly using the Next.js CLI?
you can find more information here: [https://nextjs.org/docs/api-reference/cli](url)

**Comment by meadow-tulips** [comment] 2023-02-09 12:03
Hello, I am also facing issues in deploying my nextjs . 
I am able to build the nextjs app locally but it fails in docker (Running exactly the same steps).

It keeps giving me 

`Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'registered')
    at /usr/src/app/node_modules/@emotion/styled/base/dist/emotion-styled-base.cjs.prod.js:131:53
    at /usr/src/app/node_modules/@emotion/react/dist/emotion-element-20108edd.cjs.prod.js:62:16
    at Wc (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:73:437)
    at Z (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)`
    
    
    I don't even have /404 page . It says the same for every page route.  ('/500', '/' ). Does not matter the page is dynamic or not. It was building just 3-4 days back ..and now the same builld step when I run ..it fails with the above mentioned error.

**Comment by meadow-tulips** [comment] 2023-02-09 16:47
It was material ui Css not getting injected during prerendering. I was using initially the StyledEngineProvider
Now using the cache solution mentioned in the below link. Looking good now.
This helped me. 

https://mui.com/material-ui/guides/interoperability/#css-injection-order

**Comment by ijjk** [comment] 2023-02-09 17:39
Closing [per above](https://github.com/vercel/next.js/issues/45708#issuecomment-1424496766)

**Closed by ijjk** 2023-02-09 17:39 UTC
Labels: please add a complete reproduction, area: examples, type: needs triage
