### ISSUE TITLE
With webpack 5 and once deployed, local files are not readable from APIs anymore

### ISSUE THREAD

**Issue by QuentinRoy** [vercel/next.js#24700] opened 2021-05-02 03:18 UTC
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14.0.0

### What browser are you using?

Chrome,Firefox,Safari

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Since updating to 10.2.0, local files are not accessible from apis anymore once deployed on Vercel. I do not know if it was on purpose, but it used to work fine before upgrading.

In both case, an internal server error is returned. After closer inspection of the logs, the error message is as follows:
```
[Error: ENOENT: no such file or directory, open '/app/data/metadata.yml'] {

errno: -2,

code: 'ENOENT',

syscall: 'open',

path: '/app/data/metadata.yml'

}
```

It went back to normal after downgrading to next 10.1.3.

**EDIT:** It seems the problem comes from webpack 5, it is working fine if webpack5 is disabled in `next.config.js`.

**EDIT:** It does not fail if there is only one API trying to read only one local file. It is possible the problem occurs when multiple files have to be available for reading.

**EDIT:** According to @jacksonhardaker, this also fails when reading files from `getServerSideProps`.

### Expected Behavior

Local files should be readable from apis. If these are not embedded by default anymore, maybe an option could be used to indicate what files should be available?

### To Reproduce

Here is an example showing APIs failing: https://github.com/QuentinRoy/vercel-local-min-example deployed at https://vercel-local-min-example.vercel.app.

Here is another example from @jacksonhardaker showing `getServerSideProps` failing: https://github.com/jacksonhardaker/next-webpack-5-fs-bug deployed at https://next-webpack-5-fs-bug-jwegk8q1o-jacksonhardaker1.vercel.app/.

**Comment by QuentinRoy** [comment] 2021-05-02 14:19
Following @mmazzarolo suggestion in #8251, I can attest the problem actually comes with webpack 5. Disabling webpack 5 after updating fixes it.

**Comment by joe-bell** [comment] 2021-05-02 17:44
I manually opted into webpack5 and can confirm I'm also seeing this behaviour inside API routes

**API Route**
```tsx
const CONTENT_DIR = path.join(process.cwd(), "src", "content");

export const getContentByDir = async (
  dir: string,
  options?: IGetContentOptions
) => {
  const srcDir = path.join(CONTENT_DIR, dir);

  if (!fs.lstatSync(srcDir)?.isDirectory()) {
    // Error thrown to Vercel
    throw Error(`${srcDir} is not a valid directory`);
  }
  // other unrelated code
};
```

**Vercel Logs**
```sh
Error: ENOENT: no such file or directory, lstat '/var/task/src/content/blog'
    at Object.lstatSync (fs.js:1077:3)
    at getContentByDir (/var/task/.next/server/pages/api/sitemap.js:283:49)
    at getBlogPaths (/var/task/.next/server/pages/api/sitemap.js:292:23)
    at getAllPaths (/var/task/.next/server/pages/api/sitemap.js:313:67)
    at getSitemapPaths (/var/task/.next/server/pages/api/sitemap.js:314:43)
    at exports.modules.3692.__webpack_exports__.default (/var/task/.next/server/pages/api/sitemap.js:331:96)
    at apiResolver (/var/task/node_modules/next/dist/next-server/server/api-utils.js:8:7)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Server.handleApiRequest (/var/task/node_modules/next/dist/next-server/server/next-server.js:66:462)
    at async Object.fn (/var/task/node_modules/next/dist/next-server/server/next-server.js:58:580) {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/var/task/src/content/blog'
}
```

## Additional Context

I tried adding this to my `next.config.js`, but had no luck:
```js
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve.fallback.fs = false;
    }

    return config;
  },
```

This behaviour **doesn't** occur when I opt-out of `webpack5`

**Comment by QuentinRoy** [comment] 2021-05-05 17:06
Hi,
I investigated the problem a bit more. It seems if there is only one api reading one local file, this is working. However, if there are two apis reading two local files, then it breaks.
Here is a minimal reproduction repository: https://github.com/QuentinRoy/vercel-local-min-example.

**Comment by jacksonhardaker** [comment] 2021-05-05 18:02
Good tip @QuentinRoy I can confirm that the addition of a second _read_ appears to reveal the issue.
Repo: https://github.com/jacksonhardaker/next-webpack-5-fs-bug
Deployment: https://next-webpack-5-fs-bug-jacksonhardaker1.vercel.app/

**Comment by wworrall** [comment] 2021-05-06 09:06
This is a major issue causing Vercel deployments to break silently (build completing successfully). Rolling back to webpack 4 for now - please fix asap, Vercel  😍. Also, perhaps add this to your tests as to which projects are automatically compatible with webpack5

**Comment by joe-bell** [comment] 2021-05-06 15:35
@wworrall that tone is super unproductive and contributes nothing to this issue

**Comment by QuentinRoy** [comment] 2021-05-06 17:22
@jacksonhardaker, does your deployment match the code in your repo? The deployed app appears functional.

**Comment by jacksonhardaker** [comment] 2021-05-06 19:12
@QuentinRoy Thanks for the ping, I must have pasted the incorrect url. Updated.

**Comment by marbiano** [comment] 2021-05-25 01:13
We have a [slightly similar case](https://github.com/vercel/next.js/issues/25431). We can read files but only if one API endpoint is doing the `fs.readFile`. The moment we add a second endpoint it fails! 

Thanks for taking a look and providing help, Vercel crew. 🙏

**Comment by adrai** [comment] 2021-06-27 18:52
I found a temporary fix until https://github.com/vercel/next.js/issues/24700 gets addressed in Next.js Iteration 22 or 23, 24, 25, etc...

1. in next-i18next: `serverSideTranslations.ts` line 42, check for `!userConfig` before importing from `DEFAULT_CONFIG_PATH`
2. in userland: for every `serverSideTranslations()` call, `import nextI18NextConfig from '../next-i18next.config.js'` and pass it as last argument to `serverSideTranslations` => `await serverSideTranslations(locale, ['common', 'footer'], nextI18NextConfig)`

I just tested this on Next.js v11.0.1 and it seems to work.

`serverSideTranslations.ts`
![image](https://user-images.githubusercontent.com/1086194/123556003-4dc24200-d789-11eb-80f0-fba1a80105e2.png)

i.e. `second-page.js`
![image](https://user-images.githubusercontent.com/1086194/123556030-63376c00-d789-11eb-80c0-d1c8131c3d62.png)

**Comment by nath-green** [comment] 2021-08-17 19:14
I'm not sure if this is related but the value of `process.cwd()` changes after first render to a refresh. From `/vercel/path0` to `/var/task` which causes my files not to be read after a refresh as the path is different.

One thing I did notice is that if the `revalidate` prop is removed, it appears to work correctly.

**Comment by ijjk** [comment] 2021-08-25 14:22
Hi, this has been updated and can now be tested in `v11.1.1-canary.14` of Next.js by adding the below config to your `next.config.js` and re-deploying. Please update and give it a try!

```js
module.exports = {
  experimental: {
    nftTracing: true
  }
}
```

**Comment by carl0s** [comment] 2021-10-02 00:56
Any update on this?

**Comment by ijjk** [comment] 2021-10-02 03:47
@carl0s did you try the `experimental.nftTracing` config already and experienced issues still? If so you can try the latest version of Next.js `v11.1.3-canary.41` with the now renamed `experimental.outputFileTracing`.

**Comment by carl0s** [comment] 2021-10-05 19:48
I will totally try that!

**Comment by carl0s** [comment] 2021-10-06 08:06
I tried that with the mentioned version of Next.js, v11.1.3-canary.45.
I'm trying to have a next build with next-18n and I have this error.

`Error occurred prerendering page "/de/article/test-article". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Cannot find module '[redacted]/next-i18next.config.js'
    at webpackEmptyContext ([redacted]/.next/serverless/pages/[...slug].js:11:10)
    at [redacted]/.next/serverless/chunks/709.js:245:72
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

I removed some reference to local paths, as they might be confusing.
Without I18n works fine, and with webpack 4 it builds fine. Though we need webpack 5 to work correctly.

**Comment by eric-burel** [comment] 2021-10-15 08:01
The update to 11.3 with `experimental.outputFileTracing` seems to stop this error message to happening but leads to new issues with Material UI v5 / Emotion, I get this:

```
/node/index.js',
    '/var/task/node_modules/@mui/system/index.js',
    '/var/task/node_modules/@mui/material/node/styles/adaptV4Theme.js',
    '/var/task/node_modules/@mui/material/node/styles/index.js',
    '/var/task/.next/server/pages/_document.js',
    '/var/task/node_modules/next/dist/server/require.js',
    '/var/task/node_modules/next/dist/server/load-components.js',
    '/var/task/node_modules/next/dist/server/api-utils.js',
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/___next_launcher.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
2021-10-15T07:57:31.238Z	f5ecb81a-7cb9-49fa-9f66-4595e6f427d0	ERROR	Error: Cannot find module 'stylis'
Require stack:
- /var/task/node_modules/@emotion/cache/dist/emotion-cache.cjs.prod.js
- /var/task/node_modules/@emotion/cache/dist/emotion-cache.cjs.js
... // etc.
```
Seems similar to this ticket: https://github.com/emotion-js/emotion/issues/850

Only one route of my app is affected I don't really get why specifically, probably because it's an MDX file.

**Comment by adrai** [comment] 2021-10-20 07:12
`v11.1.3-canary.86` behaves still the same for next-i18next issue: https://github.com/vercel/next.js/issues/24700#issuecomment-935735270

**Comment by eric-burel** [comment] 2021-10-20 19:01
Much thanks for the help @ijjk I've made some progress.

I ended up with the config described there in the relevant next-i18next ticket https://github.com/isaachinman/next-i18next/issues/661#issuecomment-947945079

However, I have a new issue :/
```
2021-10-20T18:55:03.846Z	63b14614-4efe-45fb-877f-d362013ab373	ERROR	Error: Cannot find module '@mdx-js/react'
Require stack:
- /var/task/.next/server/pages/learn/intro-online.js
- /var/task/node_modules/next/dist/server/require.js
- /var/task/node_modules/next/dist/server/load-components.js
- /var/task/node_modules/next/dist/server/api-utils.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/___next_launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.7425 (/var/task/.next/server/pages/learn/intro-online.js:144:18)
    at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
    at Object.8373 (/var/task/.next/server/pages/learn/intro-online.js:19:71)
    at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/var/task/.next/server/pages/learn/intro-online.js:399:39)
    at /var/task/.next/server/pages/learn/intro-online.js:400:91 {
  code: 'MODULE_NOT_FOUND',
  ```
   - this happens if I refresh the page https://vulcan-next.vercel.app/learn/intro-online
   - this doesn't happen if I go to another page, and just add `/learn` in the URL => as far as I can tell Next is doing a kind of client page transition in this case. So basically only the server render fails.

The package is correctly listed in the dependencies.
  
Sorry I'd like to help more but I don't fully understand what happens, and the error message is kinda vague here. That's maybe a different issue.

**Comment by ijjk** [comment] 2021-11-17 16:30
I'm going to close this as this should be working properly in the latest version of Next.js `v12.0.4`, if you are still encountering issues with this in the latest version please open a fresh issue with reproduction.

**Closed by ijjk** 2021-11-17 16:30 UTC
Labels: kind: bug, area: Output File Tracing

**Comment by balazsorban44** [comment] 2022-01-27 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
