### ISSUE TITLE
Unable to debug with '--inspect' on 10.0.8 and 10.0.9

### ISSUE THREAD

**Issue by imjamespond** [vercel/next.js#23494] opened 2021-03-29 04:15 UTC
### What version of Next.js are you using?

10.0.8 and 10.0.9

### What version of Node.js are you using?

v12.16.3

### What browser are you using?

...

### What operating system are you using?

macOS

### How are you deploying your application?

...

### Describe the Bug

I have tested 10.0.8 and 10.0.9 and both version unable to launch next
But 10.0.7 is OK

### Expected Behavior

...

### To Reproduce
```
npm install next react react-dom
edit scripts of package.json
"dev": "NODE_OPTIONS='--inspect' next",
npm run dev
```

And I got Error
```
...
Debugger listening on ws://127.0.0.1:9229/5557aa3f-afee-432a-8a33-5ee2626e1e33
For help, see: https://nodejs.org/en/docs/inspector
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:677:19)
...
```

**Comment by Abd-ksr** [comment] 2021-03-29 07:24
Try removing single quote(') around '--inspect'
```
"dev": "NODE_OPTIONS=--inspect next dev"
```

**Comment by imjamespond** [comment] 2021-03-29 07:38
@Abd-ksr  Still got the same error....🙈

**Comment by Abd-ksr** [comment] 2021-03-29 07:48
> 
> 
> @Abd-ksr Still got the same error....🙈
May be some other issue

i tried in nextjs v10.0.5. woking fine for me

**Comment by gierachjg** [comment] 2021-03-30 11:02
It seems that it fails on 10.1.2 too 😔

**Comment by amisteriousdeveloper** [comment] 2021-04-13 20:27
Same here, 10.1.3 😔

```
  events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:677:19)
    at ChildProcessWorker.initialize (/path-to-my/project/node_modules/next/node_modules/jest-worker/build/workers/ChildProcessWorker.js:181:11)
    at ChildProcessWorker._onExit (/path-to-my/project/node_modules/next/node_modules/jest-worker/build/workers/ChildProcessWorker.js:275:12)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
Emitted 'error' event on ChildProcess instance at:
    at internal/child_process.js:810:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}


```

**Comment by ppalmeida** [comment] 2021-04-13 20:32
Same here: 10.1.3

```
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:677:19)
    at ChildProcessWorker.initialize (/path-to-my/project/node_modules/next/node_modules/jest-worker/build/workers/ChildProcessWorker.js:181:11)
    at ChildProcessWorker._onExit (/path-to-my/project/node_modules/next/node_modules/jest-worker/build/workers/ChildProcessWorker.js:275:12)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
Emitted 'error' event on ChildProcess instance at:
    at internal/child_process.js:810:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
```

Node: v12.16.2
OSX: 10.15.7
Yarn: 1.22.10

**Comment by mamadOuologuem** [comment] 2021-04-13 21:00
+1

**Comment by ijjk** [comment] 2021-04-17 16:17
Closing as a duplicate of https://github.com/vercel/next.js/issues/22835

**Closed by ijjk** 2021-04-17 16:17 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
