### ISSUE TITLE
from nextjs 13.3.0 to 13.4 socket.io not working

### ISSUE THREAD

**Issue by flipUp02** [vercel/next.js#49249] opened 2023-05-04 21:37 UTC
### Summary

With the same code, socket IO only works on Nextjs version 13.2.4. As for any other version that shows error number 404 for the page http://localhost:3000/socket.io/?EIO= I hope to solve the problem quickly and see the following code: https://github.com/flipUp02/nextjs-socket.io

13 3 1-canary 11
![13 3 1-canary 11](https://user-images.githubusercontent.com/80167896/232636454-a9a9ddd4-2a7b-4e58-a32a-716b129a5004.png)

13.2.4
![13 2 4](https://user-images.githubusercontent.com/80167896/232636520-d54ae6e3-fcb9-4e5a-81f5-88d324588281.png)

please fix this

### Example

https://github.com/flipUp02/nextjs-socket.io

_Originally posted by @flipUp02 in https://github.com/vercel/next.js/discussions/48510_

**Comment by flipUp02** [comment] 2023-05-04 21:38
@leerob

**Comment by CKGrafico** [comment] 2023-05-06 13:55
Same to me, only in localhost :/

**Comment by leerob** [comment] 2023-05-06 23:41
Duplicate of https://github.com/vercel/next.js/issues/49249, merging with it.

**Closed by leerob** 2023-05-06 23:41 UTC
