### ISSUE TITLE
Next.js.13 next/link ignores basePath when app/layout is present

### ISSUE THREAD

**Issue by michvh-dev** [vercel/next.js#44197] opened 2022-12-20 16:46 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

next@13.0.8

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/michvh-dev/next-js13-issue-link

### To Reproduce

Setted the basePath in next.config.js

PS: Its working when no layout in root app folder

``
const nextConfig = {
  basePath: '/gallery',
};
``

### Describe the Bug

Example of the link 
`<Link href="/staff-picks"></Link>`

Rendered html (Anchor href is correct)
`<a class="" href="/gallery/staff-picks">`

When clicking on link it goes to  `/staff-picks` instead of `/gallery/staff-picks`

Also got console errors
![Screenshot 2022-12-20 at 16 37 19](https://user-images.githubusercontent.com/9009231/208705603-d5db79a4-a4ce-46ad-bf39-9c5f17132ce2.png)

### Expected Behavior

Expected behavior
The app router takes the base path in acount

**Comment by sujoyduttajad** [comment] 2022-12-23 12:51
I'm also facing a similar issue

**Comment by maxprilutskiy** [comment] 2023-02-03 23:39
I believe the issue is along these lines: https://github.com/vercel/next.js/blob/canary/packages/next/src/client/link.tsx#L597

And the problem seems to also be related to https://github.com/vercel/next.js/issues/43852

**Comment by 8bittitan** [comment] 2023-06-14 19:29
Seems like this is fixed in the 13.4.5 version now?

**Comment by michvh-dev** [comment] 2023-06-15 07:23
Confirmed indeed working in 13.4.5

**Closed** 2023-06-15 07:23 UTC
Labels: template: bug
