### ISSUE TITLE
Upgrade from 13.1.6 to 13.2.1 breaks production build (Cannot find module font-loader-manifest.json)

### ISSUE THREAD

**Issue by ryandegruyter** [vercel/next.js#46473] opened 2023-02-27 10:19 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.1
      npm: 9.2.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.1
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

nx workspace
    "@nrwl/next": "15.7.2",

### Which area(s) of Next.js are affected? (leave empty if unsure)

Fonts

### Link to the code that reproduces this issue

/

### To Reproduce

Upgrade from 13.1.6 to 13.2.1
run nx export ...

### Describe the Bug

**SSG generated website**
When running a production build we get the following error:

```
 NX   Cannot find module '/Users/.../dist/apps/website/.next/server/font-loader-manifest.json'

   Require stack:
   - /Users/.../node_modules/next/dist/export/index.js
   - /Users/.../node_modules/@nrwl/next/src/executors/export/export.impl.js
   - /Users/.../node_modules/nx/src/config/workspaces.js
   - /Users/.../node_modules/nx/src/command-line/run.js
   - /Users/.../node_modules/nx/bin/run-executor.js
 ```

But the file is present:
![image](https://user-images.githubusercontent.com/12190633/221536734-8b18e0e6-af2a-40d3-98e9-9e2a6a1d3120.png)

### Expected Behavior

Same behavior as v13.1.6, no build error.
Or an explanation of the breaking change.

**Comment by balazsorban44** [comment] 2023-02-27 10:39
Duplicate of #46374

**Closed by balazsorban44** 2023-02-27 10:39 UTC
Labels: template: bug
