### ISSUE TITLE
yarn build hangs on "Creating an optimized production build" on centos7

### ISSUE THREAD

**Issue by Fity** [vercel/next.js#35130] opened 2022-03-08 09:09 UTC
### Verify canary release

- [x] I verified that the issue exists in Next.js canary release

### Provide environment information

same as #9410
My Environment:

- node v16.14.0, installed via yum
- npx 6.13.4
- glibc:  ldd (GNU libc) 2.18, build from source
- yarn 1.22.15
- create-next-app@12.1.0
- Next.js 
- os release
```
$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### What browser are you using? (if relevant)

not related

### How are you deploying your application? (if relevant)

not related

### Describe the Bug

when running `yarn build`, it hangs on "Creating an optimized production build"

### Expected Behavior

finishing the building process and get the `.next` output

### To Reproduce

1. create a sample project via `yarn create next-app`  with default settings(`my-app` as the project name)
2. `cd my-app && yarn build`
3. it hangs
![image](https://user-images.githubusercontent.com/1326741/157203960-15dd9def-5e6a-4b13-98d8-51b4088407aa.png)

the `package.json` content

```json
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "12.1.0",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "eslint": "8.10.0",
    "eslint-config-next": "12.1.0"
  }
}
```

**Comment by balazsorban44** [comment] 2022-03-08 15:30
Seems like a duplicate of #33854. This should be fixed on `canary` already, please try it out.

You checked:

>  I verified that the issue exists in Next.js canary release

but your reproduction suggested otherwise. Please make sure you only check it if you have verified with `canary`, thanks! :pray:

Note, you shouldn't need to build glibc 2.18 from the source either. :+1:

**Closed by balazsorban44** 2022-03-08 15:30 UTC
Labels: template: bug
