### ISSUE TITLE
Scroll reset happens at end of `Link` routing rather than beginning

### ISSUE THREAD

**Issue by zackdotcomputer** [vercel/next.js#6462] opened 2019-02-27 05:03 UTC
# Bug report

## Describe the bug

The next.js `Router` resets the scroll position to 0,0 at the end of navigation if it is navigating to a href without a fragment via the included `Link` tag. However, because of the late timing of the reset, the incoming page renders and begins its lifecycle with the viewport position at the point it was at on the previous page before being reset to the new value. This can cause confusing errors when components on the new page use scroll position to trigger behaviors and events.

## To Reproduce

1. In any next site using the default Router with two pages... we'll call one `A` and one `B`.
2. Add an override in `B` of `componentDidMount` that calls `console.log(window.scrollY)`
3. Go to `A` and scroll so that you are no longer at scroll position (0,0).
4. Click a `Link` element to navigate to `B`. Notice that your log will log a value other than 0, though the page will then reset to the top.

## Expected behavior
I would expect this to mirror the behavior found with "true http routing". If you perform the navigation using normal `<a>` tags instead of `<Link>` elements, the viewport is reset to (0, 0) before the React elements receive their call to `componentDidMount`.

## System information
 - OS: Mac OS
 - Browser (if applies) Firefox (I'm assuming this applies to all browsers, though)
 - Version of Next.js: 8.0.1

## Additional context

I was able to fix this problem for my code using the following snippet (in typescript):
```typescript
let hasAttachedRouteListener: boolean = false;

export function attachListener() {
  // Only actually attach once
  if (hasAttachedRouteListener) {
    return;
  }
  hasAttachedRouteListener = true;

  // This event fires before the incoming route is loaded or rendered,
  // so by resetting the viewport without animation at this point we avoid
  // the incoming route getting the incorrect viewport at any point.
  const handleRouteChange = () => {
    window.scrollTo({
      top: 0,
      left: 0,
      behavior: "auto"
    });
  };

  Router.events.on("routeChangeStart", handleRouteChange);
}
```

**Comment by MarchWorks** [comment] 2019-03-23 13:34
@timneutkens updating [./packages/next-server/lib/router](https://github.com/zeit/next.js/blob/08b7a24925f1c73b51a8a29082561496bdc1c316/packages/next-server/lib/router/router.ts#L246-L267) to 

```
this.getRouteInfo(route, pathname, query, as, shallow).then((routeInfo) => {
        const { error } = routeInfo

        if (error && error.cancelled) {
          return resolve(false)
        }

        Router.events.emit('beforeHistoryChange', as)
        this.changeState(method, url, as, options)
        const hash = window.location.hash.substring(1)

        // @ts-ignore pathname is always defined
        setTimeout(()=>{
        	this.set(route, pathname, query, as, { ...routeInfo, hash })
        }, 0)

        if (error) {
          Router.events.emit('routeChangeError', error, as)
          throw error
        }

        Router.events.emit('routeChangeComplete', as)
        return resolve(true)
      }, reject)
```
should I make a PR?

**Comment by MarchWorks** [comment] 2019-03-24 14:20
Just a simple note using `useEffect` instead of `componentDidMount` will log 0

**Comment by zackzachariah** [comment] 2019-03-24 19:37
Acknowledged! I think ideally, though, the behavior of the check should be consistent between `useEffect`, `useLayoutEffect`, and `componentDidMount`. This would be helpful both because the effect hooks are a very new feature, so a ton of existing knowledge and code don't reference them, and because it would be nice to avoid "it works this way but not this way" issues especially when React's own documentation says effect hooks are "basically equivalent" to the lifecycle methods.

Also, I'm not near my code at the moment but I'm now very curious to know what the scroll offset reads as if you use `useLayoutEffect` instead, since it blocks the browser update cycle like the lifecycle methods?

**Comment by MarchWorks** [comment] 2019-04-12 20:38
Sorry for all this PR the last one is absolutely the right solution

**Comment by yanyixin** [comment] 2019-12-19 10:24
sorry, Can it be solved?

**Comment by Timer** [comment] 2020-06-30 17:30
I believe this was fixed by @devknoll but we need to confirm.

**Comment by rjvim** [comment] 2020-07-14 08:23
Hi,

Not sure if the issue reposted is the root cause of the issue we are facing.

We have multiple pages in a NextJS codebase, and whenever we try to navigate to a page by selecting a Link from the footer, the new page loads and page scrolls to top.

Our example is hosted here: 

https://website-nextjs-git-develop.aham-learning.vercel.app/

Steps to reproduce:

1. Go to https://website-nextjs-git-develop.aham-learning.vercel.app/
2. Go to footer
3. Click on "Terms"
4. Page renders and then scrolls to the top

Is this already fixed or is there a solution for it? We are using the "Link" component.

**Comment by Shawn-Noruzi** [comment] 2020-12-07 07:11
Any update to this?

**Closed** 2020-12-30 04:33 UTC
Labels: kind: bug, point: 3, type: needs investigation

**Comment by alextseitlin** [comment] 2021-02-06 16:25
Issue not fixed on my end

**Comment by balazsorban44** [comment] 2022-01-28 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
