### ISSUE TITLE
with-tailwindcss-emotion: Invalid package config.

### ISSUE THREAD

**Issue by agallio** [vercel/next.js#19770] opened 2020-12-03 08:16 UTC
# Bug report

## Describe the bug

Emotion 11 throws an error during the compilation. The issue is similar with the issue number #19746.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Execute create-next-app command in this repo `https://github.com/vercel/next.js/tree/canary/examples/with-tailwindcss-emotion`
2. Run `yarn dev`

## Expected behavior

It should work.

## Screenshots

```
ready - started server on http://localhost:3000
error - ./node_modules/next/dist/client/polyfills.js
Error [ERR_INVALID_PACKAGE_CONFIG]: Invalid package config /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/@emotion/babel-plugin/node_modules/stylis/package.json. "exports" cannot contain some keys starting with '.' and some not. The exports object must either be an object of package subpath keys or an object of main entry condition name keys only.
event - build page: /next/dist/pages/_error
wait  - compiling...
error - ./node_modules/next/dist/client/next-dev.js
Error [ERR_INVALID_PACKAGE_CONFIG]: Invalid package config /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/@emotion/babel-plugin/node_modules/stylis/package.json. "exports" cannot contain some keys starting with '.' and some not. The exports object must either be an object of package subpath keys or an object of main entry condition name keys only.
Error: Cannot find module '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/.next/server/pages-manifest.json'
Require stack:
- /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/require.js
- /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/load-components.js
- /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/api-utils.js
- /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/next-server.js
- /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/server/next.js
- /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/server/lib/start-server.js
- /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/cli/next-dev.js
- /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at getPagePath (/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/require.js:1:657)
    at requirePage (/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/require.js:1:1062)
    at loadComponents (/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/load-components.js:1:807)
    at DevServer.findPageComponents (/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/next-server.js:73:296)
    at DevServer.renderErrorToHTML (/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/next-server.js:125:120)
    at DevServer.renderErrorToHTML (/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/server/next-dev-server.js:34:974) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/require.js',
    '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/load-components.js',
    '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/api-utils.js',
    '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/next-server.js',
    '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/server/next.js',
    '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/server/lib/start-server.js',
    '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/cli/next-dev.js',
    '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/bin/next'
  ]
}
Error: Cannot find module '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/.next/server/pages-manifest.json'
Require stack:
- /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/require.js
- /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/load-components.js
- /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/api-utils.js
- /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/next-server.js
- /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/server/next.js
- /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/server/lib/start-server.js
- /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/cli/next-dev.js
- /Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at getPagePath (/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/require.js:1:657)
    at requirePage (/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/require.js:1:1062)
    at loadComponents (/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/load-components.js:1:807)
    at DevServer.findPageComponents (/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/next-server.js:73:296)
    at DevServer.renderErrorToHTML (/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/next-server.js:125:120)
    at DevServer.renderErrorToHTML (/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/server/next-dev-server.js:34:974) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/require.js',
    '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/load-components.js',
    '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/api-utils.js',
    '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/next-server/server/next-server.js',
    '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/server/next.js',
    '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/server/lib/start-server.js',
    '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/cli/next-dev.js',
    '/Users/agalliosamai/Developer/playground/react/with-tailwindcss-emotion-app/node_modules/next/dist/bin/next'
  ]
}
```

## System information

- OS: macOS 11.0.1 Big Sur
- Version of Next.js: 10.0.3
- Version of Node.js: 12.19.0
- Deployment: Local

**Comment by ciruz** [comment] 2020-12-07 13:06
Works for me, dev and build.

![image](https://user-images.githubusercontent.com/987947/101354416-6e7e8500-3895-11eb-96dd-f7f78f52d3bd.png)

**Comment by yann120** [comment] 2021-02-03 18:37
We tried with different computers to reproduce it and it worked perfectly.
I think we can close this issue, seems it's only on your computer

**Comment by leerob** [comment] 2021-02-03 18:42
Confirmed, I was working with @yann120. Thank you so much for investigating! 🙏

**Closed by leerob** 2021-02-03 18:42 UTC
Labels: good first issue, type: example

**Comment by balazsorban44** [comment] 2022-01-28 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
