### ISSUE TITLE
freshly `npx create-next-app` app doesn't compile

### ISSUE THREAD

**Issue by tawfik741** [vercel/next.js#27396] opened 2021-07-22 11:40 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

chrome

### What operating system are you using?

windows

### How are you deploying your application?

no deployment

### Describe the Bug

I wanted to create a next app by running `npx create-next-app hulu`

when running `yarn run dev`

I get 

```
Error: Cannot find module 'C:\Users\Tawfik\dev\learning\frontend\hulu\.next\server\pages-manifest.json'
``` 

and 

```
error - ../../../../Desktop/dev/learning/frontend/hulu/pages/_app.js
Module parse failed: Unexpected token (4:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| function MyApp({ Component, pageProps }) {
>   return <Component {...pageProps} />
| }
|
```

After investigating some answers, I got that it's due to versioning and that I need to downgrade webpack or npm to make it function but nextjs is a mature environment and they don't state any required downgrade for running the app. 

is the `create-next-app` tool broken or is there another explanation to this?

### Expected Behavior

to compile correctly 

### To Reproduce

run `npx create-next-app hulu`

then run `yarn run dev`

**Comment by Dagmawi-Beyene** [comment] 2021-07-23 00:29
I am having the same issue

**Comment by ijjk** [comment] 2021-07-23 19:52
Hi, the default `create-next-app` should be working without any additional steps. I'm not able to reproduce the error shown using the above command. Can you share more information about your environment and any additional steps being taken when running the command?

What's the output of `npx create-next-app --version`? What's the output of running `npm ls next` inside of the folder created?

**Comment by tawfik741** [comment] 2021-07-24 01:10
@ijjk  they both output `-- next@11.0.1`

**Comment by ijjk** [comment] 2021-07-24 01:17
@tawfik741 did you provide any flags when running `npx create-next-app` like a specific example? Also can you try `rmdir /s .next` and then running `yarn dev`?

**Comment by tawfik741** [comment] 2021-07-24 09:16
I didn't use any flag for `npx create-next-app`

I tried to remove the `.next` folder and running `yarn dev` multiple times but it still doesn't work

**Comment by ijjk** [comment] 2021-07-24 16:32
Hmm I'm still not able to reproduce this on macOS or Windows, can you provide any more information on the environment you're running this in? I added a screenshot of testing on Windows with latest `create-next-app` below to show it working as expected. 

<img width="1651" alt="Screen Shot 2021-07-24 at 11 29 45 AM" src="https://user-images.githubusercontent.com/22380829/126874976-5a96616c-86ce-4d75-94eb-5908471fe9c5.png">

**Comment by megawawa** [comment] 2021-07-30 04:51
i ran into the same issue and resolved by following this comment: https://github.com/vercel/next.js/issues/16535#issuecomment-746917659

**Closed** 2021-09-22 21:29 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
