### ISSUE TITLE
How to Integrate React Epub Reader with next js

### ISSUE THREAD

**Issue by sadam1807** [vercel/next.js#20569] opened 2020-12-29 11:31 UTC
Hello 
I am trying to integrate [react epub reader ](https://www.npmjs.com/package/react-reader) with Next Js  but getting one error and  works  well with react js,  **I need your help to integrate epub reader with next js**

![image](https://user-images.githubusercontent.com/42937204/103280841-64185c80-49f7-11eb-8ec8-5d240f7ced51.png)

 
this is my code

> import React from 'react'
import { ReactReader } from "react-reader";

export default function Home() {
  return (
    <div>
         <div style={{ position: "relative", height: "330px" }}>
          
          <ReactReader
            url="./Boy without a name English.epub"
            title={"Alice in wonderland"}
            location={"epubcfi(/6/2[cover]!/6)"}
            locationChanged={epubcifi => console.log(epubcifi)}
          />
        </div>
      </div>
  )
}
@leerob 
_Originally posted by @sadam1807 in https://github.com/vercel/next.js/discussions/20568_

**Comment by leerob** [comment] 2020-12-30 13:59
Based on that error message, it's an issue with that library - not Next.js. 

You could try using dynamic imports? Maybe there's some non-SSR functionality included in that library.

**Comment by sadam1807** [comment] 2020-12-31 06:39
Thanks, @leerob issue is resolved, the below code worked

`import React from 'react'
import dynamic from 'next/dynamic'

export default function Home() {

  const EpubReader = dynamic( {
    loader : () => import('react-reader'),
    ssr: false,
    render(props, reactRe) {
      return <reactRe.ReactReader 
      url={props.filePath}
      title={"Alice in wonderland"}
      location={"epubcfi(/6/2[cover]!/6)"}
      locationChanged={epubcifi => console.log(epubcifi)}
      />
    }
  });
  return (
    <div>
         <div  style={{ position: "relative", height: "500px", width: "100%" }}>
          <EpubReader filePath="./sample1.epub" />
        </div>
      </div>
  )
}
`

**Comment by lachlanjc** [comment] 2020-12-31 16:06
Awesome! Let’s close this then?

**Comment by leerob** [comment] 2020-12-31 16:07
@lachlanjc Yep, agreed 👍 Glad it works @sadam1807!

**Closed by leerob** 2020-12-31 16:07 UTC

**Comment by balazsorban44** [comment] 2022-01-28 23:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
