### ISSUE TITLE
i18n doesn't prevent devs from creating broken pages with the locale prefix

### ISSUE THREAD

**Issue by sebastian-nowak** [vercel/next.js#21209] opened 2021-01-15 20:41 UTC
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

15.6.0

**What browser are you using?**

n/a

**What operating system are you using?**

n/a

**How are you deploying your application?**

next build && next start

**Describe the Bug**

It's possible to create pages that include a locale prefix (e.g. `pages/en/index.js`) and `next build` doesn't complain about it.

**Expected Behavior**

Build should fail

**To Reproduce**

Run `npx create-next-app`, then enable i18n in `next.config.js`:

```js
module.exports = {
  i18n: {
    locales: ['en', 'pl'],
    defaultLocale: 'en'
  }
};
```

Create a `pages/en/index.js` file:

```js
export default function Unreachable() {
  return <div>unreachable</div>;
}
```

Run `next build`, it should fail because of a conflict with the existing locale but it doesn't. If you start the server and navigate to `/en` you'll get a 404.

**Comment by ijjk** [comment] 2021-09-21 03:15
Hi, this appears to be a duplicate of https://github.com/vercel/next.js/issues/19930 so I'm gonna close this in favor of that one.

**Closed by ijjk** 2021-09-21 03:15 UTC
Labels: kind: bug

**Comment by balazsorban44** [comment] 2022-01-27 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
