### ISSUE TITLE
Link (next/link) for dynamic path with query sting parameters are not working properly on production

### ISSUE THREAD

**Issue by mr-ravi26** [vercel/next.js#26721] opened 2021-06-29 11:30 UTC
### What version of Next.js are you using?

9.3.4

### What version of Node.js are you using?

12.22.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

next start

### Describe the Bug

We are having a dynamic path as `/topic/[slug]/[id].js` where topic and [slug] are folder name and [id].js is the file inside pages folder. From any other location when are are trying to create a link to this path 

```
<Link href={'/topic/[slug]/[id]} as={'/topic/league/2361?lang=es-co?'}>
 {children}
</Link>
```

now while working on local the path formation is as below and its working fine too
http://localhost:3050/_next/data/development/topic/league/2361.json?lang=es-co

where as from deployment path changed and we are not able to access query string value (lang=es-co) at all, path formation on server is as below
https://7westtaphouse.teamlocal.ws/_next/data/4s-3ihSqMynT818D9ply7/topic/league/2361.json?slug=league&id=2361

Is there something I am doing wrong, or since its working on local but not on production it looks like a bug

### Expected Behavior

Query sting parameter should be available too with other parameters

### To Reproduce

```
<Link href={'/topic/[slug]/[id]} as={'/topic/league/2361?lang=es-co?'}>
 {children}
</Link>
```

**Comment by ijjk** [comment] 2021-09-19 04:58
Hi, this should be fixed in the latest version of Next.js `v11.1.2` please update and give it a try!

**Closed by ijjk** 2021-09-19 04:58 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
