### ISSUE TITLE
Update examples to use next/image for cover-image component

### ISSUE THREAD

**Issue by marcofranssen** [vercel/next.js#20417] opened 2020-12-23 13:16 UTC
The `component/cover-image.js` could make use of the next/image component with lazyloading etc. It would be great if the examples utilize this.

**Comment by timneutkens** [comment] 2021-01-03 15:08
Closing as the issue template was ignored.

**Closed by timneutkens** 2021-01-03 15:08 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-28 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
