### ISSUE TITLE
Next Link + Redirect + Rewrite Issue

### ISSUE THREAD

**Issue by lucasbasquerotto** [vercel/next.js#27425] opened 2021-07-22 20:54 UTC
### What example does this report relate to?

redirects

### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

16.5.0

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04

### How are you deploying your application?

next start

### Describe the Bug

I have a rewrite that maps a path in the url to a folder inside the pages directory, and I also have a redirect that also applies to this path, but only if the user is logged (has the cookie `me`).

If I enter the path in the browser url, it correctly redirects if the cookie is present, and doesn't redirect if the cookie is not present, using the rewrite instead.

But if I use a next link to redirect, it instead uses the rewrite, even if I have the cookie (if I remove the rewrite, the redirect occurs successfully).

This error occurs when running `npm run start` and `npm run dev`.

### Expected Behavior

The redirect should occur with the next link, just like when entering the url in the browser.

### To Reproduce

_next.config.js:_

```js
module.exports = {
    async redirects() {
        return [
            {
                source: '/page1',
                destination: '/page2',
                permanent: false,
                has: [{ type: 'cookie', key: 'me' }],
            },
        ];
    },
    async rewrites() {
        return [
            {
                source: '/page1',
                destination: '/test',
            },
        ];
    }
}
```

_page.tsx:_

```tsx
<Link href="/page1">
    <a>Text</a>
</Link>
```

**Comment by ijjk** [comment] 2021-07-22 21:00
Hi, this appears to be a duplicate of https://github.com/vercel/next.js/discussions/26426, redirects are not currently considered by `next/link` only rewrites are.

**Closed by ijjk** 2021-07-22 21:00 UTC
Labels: template: bug, type: example

**Comment by balazsorban44** [comment] 2022-01-28 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
