### ISSUE TITLE
.env file not working on v9.5.5

### ISSUE THREAD

**Issue by shockw4ver** [vercel/next.js#18033] opened 2020-10-20 02:15 UTC
# Bug report

## Describe the bug
.env or .env.development didn't work.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create `.env`(or `.env.development`)
2. define like this
```env
# dev only

HOSTNAME=localhost
PORT=8080
HOST=http://$HOSTNAME:$PORT
```
3. run `yarn dev`
4. variables didn't work
```shell
Loaded env from /Users/zyc/workspace/edu-web-v3-ssr/.env.development
ready - started server on http://localhost:3000
```

## Expected behavior
start server on http://localhost:8080

## System information

- OS: macOS
- Browser (if applies): chrome
- Version of Next.js: 9.5.5
- Version of Node.js: 12.6.0

**Comment by balazsorban44** [comment] 2020-10-20 05:30
Do you have a code example how and when you are trying to access your variables?

When on client-side, your env variables should be prepended with `NEXT_PUBLIC_` for example.

But please provide a code snippet for further assistance.

**Comment by Xairoo** [comment] 2020-12-21 21:22
Sample https://github.com/Xairoo/nextjs-env-port-test

Should use port 3001 from .env files.

`npm run dev` - will use port 3000 (default port)

`npm run devPort` - works, but it's hardcoded in package.json: `"devPort": "next dev -p 3001"`

`"devPortArg": "next dev -p $PORT"` - didn't work (or %PORT%)

`npm run dev -- -p 3001` from the console works

**Comment by timneutkens** [comment] 2020-12-22 12:44
Closed as no reproduction was provided.

> Sample [Xairoo/nextjs-env-port-test](https://github.com/Xairoo/nextjs-env-port-test)
> 
> Should use port 3001 from .env files.
> 
> `npm run dev` - will use port 3000 (default port)
> 
> `npm run devPort` - works, but it's hardcoded in package.json: `"devPort": "next dev -p 3001"`
> 
> `"devPortArg": "next dev -p $PORT"` - didn't work (or %PORT%)
> 
> `npm run dev -- -p 3001` from the console works

This is expected, you're reading `$PORT` in package.json, before Next.js even boots up.

**Closed** 2020-12-22 12:43 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 00:11
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
