### ISSUE TITLE
Images not dynamically loading when deploying website to Vercel

### ISSUE THREAD

**Issue by MacCode7110** [vercel/next.js#27317] opened 2021-07-20 02:24 UTC
### What version of Next.js are you using?

10.1.1

### What version of Node.js are you using?

12.0.0

### What browser are you using?

Internet Explorer

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

I have 4 different images that need to be dynamically loaded onto one of my webpages where I list album reviews. In localhost, the images dynamically load just fine, but when I deployed my website to Vercel, the images of the album covers do not dynamically load.

### Expected Behavior

I expect all four album images to dynamically load in the deployment to Vercel.

I would appreciate any help that I can get from someone who is more experienced with Next.js as this is my first time making a website.

### To Reproduce

![NuMetalPowerZoneProductionScreenshot1](https://user-images.githubusercontent.com/67719286/126252474-fd6c2b6d-c696-4970-a422-4996438313b5.PNG)

Here is a link to my github page for the project: 

https://github.com/MacCode7110/TheNuMetalPowerZone/tree/main

**Comment by cyrus-za** [comment] 2021-07-21 10:19
Also running into this after upgrading to next 11. Local images seem fine, but remote images do not load. The url is exactly the same. If I copy the url in the src attr of the html element in dev tools and paste it in a different app (on next 10) it works just fine.

**Comment by ijjk** [comment] 2021-07-21 17:25
Hi can you provide more information on what isn't loading, it looks like the images are correctly loading on the above deployment: <img width="1401" alt="Screen Shot 2021-07-21 at 12 24 25 PM" src="https://user-images.githubusercontent.com/22380829/126532459-b0714c53-85ae-4b1f-ba20-faea99d68790.png">

**Comment by cyrus-za** [comment] 2021-07-21 17:55
@ijjk please check out github.com/invisible-tech/invisible repo (you already have access).

Run `nx serve admin` and open the app and login with google. You should see your profile picture on the left trying to load but throwing an error. If you checkout commits from a week ago you will see that it loads just fine before we upgraded to next 11

**Comment by ijjk** [comment] 2021-07-21 18:27
@cyrus-za I wasn't able to login to reproduce, I asked our CS team to reach out to invite you our slack so we can investigate your case closer!

**Comment by MacCode7110** [comment] 2021-07-21 19:51
Yes, all of the dynamic imaging is working as of now, one of the paths to the 3rd image down was very slightly incorrect.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: JJ Kasper ***@***.***>
Sent: Wednesday, July 21, 2021 1:25:13 PM
To: vercel/next.js ***@***.***>
Cc: McAlarney, Matthew E. ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [vercel/next.js] Images not dynamically loading when deploying website to Vercel (#27317)


Hi can you provide more information on what isn't loading, it looks like the images are correctly loading on the above deployment: [Screen Shot 2021-07-21 at 12 24 25 PM] <https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F22380829%2F126532459-b0714c53-85ae-4b1f-ba20-faea99d68790.png&data=04%7C01%7Cmemcalarney%40wpi.edu%7C62f0a96ad0fc40a4b6bd08d94c6c8007%7C589c76f5ca1541f9884b55ec15a0672a%7C0%7C0%7C637624851169435482%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lGVByZRWTrvYFA9weXAokfx3nfyOgHBv5NTmBFThbaw%3D&reserved=0>

**Comment by cyrus-za** [comment] 2021-07-24 09:03
@ijjk see message on slack. I've noticed it works in dev

**Comment by ijjk** [comment] 2021-07-26 16:49
Closing as this appears to be working correctly now after investigation

**Closed by ijjk** 2021-07-26 16:49 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 01:27
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
