### ISSUE TITLE
[NEXT-975] Renaming file from `file.jsx` to `file.tsx` is not picked up by dev server

### ISSUE THREAD

**Issue by jankaifer** [vercel/next.js#48145] opened 2023-04-08 20:36 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Mar  3 10:56:18 UTC 2023
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: 7.25.0
    Relevant packages:
      next: 13.3.0
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

arst

### To Reproduce

1. Create `page.jsx` file.
2. start dev server
3. rename that file to `page.tsx`

It errors that `page.jsx` wasn't found

### Describe the Bug

I need to restart the server after rename which sucks

### Expected Behavior

It could just purge cache and pickup the new file.

<sub>[NEXT-975](https://linear.app/vercel/issue/NEXT-975/renaming-file-from-filejsx-to-filetsx-is-not-detected)</sub>

**Comment by sumitshinde-84** [comment] 2023-04-09 06:12
i would like to work on this issue , can you assign it to me?

**Comment by jankaifer** [comment] 2023-04-18 09:04
Restarting the development server when you change the file extension is enough.
If not, you can clear the cache by deleting `.next`.

**Comment by koba04** [comment] 2023-05-07 06:01
@jankaifer I've checked this issue, but I couldn't reproduce it with the canary branch. Renaming `page.tsx` to `page.jsx` and vice versa works fine. This seems to be already fixed.

**Closed** 2023-05-07 06:51 UTC
Labels: kind: bug, template: bug, area: Developer Experience
