### ISSUE TITLE
getStaticProps overrides exportPathMap

### ISSUE THREAD

**Issue by creativiii** [vercel/next.js#15315] opened 2020-07-20 08:41 UTC
# Bug report

## Describe the bug

Adding `getStaticProps` overrides folder settings set within `exportPathMap` in `next.config.js`. 

I'm essentially trying to get my html files to be output in `/directory/index.html` rather than `/directory.html`. Unfortunately even I set my `exportPathMap` to do so, as soon as the `getStaticProps` function is added in my script, the setting is overridden and the file will be output at `directory.html`

## To Reproduce

```
git clone https://github.com/creativiii/next-js-export-bug
cd next-js-export-but
npm run build
npm run export
```

Then check the `out` directory.

## Expected behavior

`page-1` and `page-2` should be respectively exported in `/page-1/index.html` and `/page-2/index.html`. Instead `page-2` is exported as `page-2.html`.

## System information

- OS: [e.g. macOS, Windows]: WSL Ubuntu 20.04
- Version of Next.js: [e.g. 6.0.2] 9.4.4
- Version of Node.js: [e.g. 10.10.0] LTS 12

**Comment by Timer** [comment] 2020-07-20 14:28
Thanks for the issue!

`getStaticProps` overrides anything configured in `exportPathMap`, this is by design. We should probably warn when you try to define a `exportPathMap` for a page that has `getStaticProps`.

We should probably also [document this](https://nextjs.org/docs/advanced-features/static-html-export).

**Comment by creativiii** [comment] 2020-07-20 16:01
> Thanks for the issue!
> 
> `getStaticProps` overrides anything configured in `exportPathMap`, this is by design. We should probably warn when you try to define a `exportPathMap` for a page that has `getStaticProps`.
> 
> We should probably also [document this](https://nextjs.org/docs/advanced-features/static-html-export).

Is there a way around this? Or is it impossible to tell Next where to output my html files if I use `getStaticProps`?

**Comment by Timer** [comment] 2020-07-20 17:59
Can you provide a more concrete example? You should rename the page if you need the file to be named differently.

**Comment by creativiii** [comment] 2020-07-20 18:13
> There is no way around this. Can you provide a more concrete example? You should rename the page if you need the file to be named differently.

Well that's exactly the problem. I can't name my files index. If I create a file at `/page-1/index.js`, it won't be exported as `/page-1/index.html`, instead it will be called `/page-1.html`.

`exportPathMap` is the only way to get my exports named `index.html` unfortunately.

What you're saying work on literally every situation, except for naming files index.html.

**Comment by Timer** [comment] 2020-07-20 18:18
Have you [tried enabling this option](https://nextjs.org/docs/api-reference/next.config.js/exportPathMap#adding-a-trailing-slash)?

```js
// next.config.js
module.exports = {
  exportTrailingSlash: true,
}
```

**Comment by creativiii** [comment] 2020-07-20 18:34
> Have you [tried enabling this option](https://nextjs.org/docs/api-reference/next.config.js/exportPathMap#adding-a-trailing-slash)?
> 
> ```js
> // next.config.js
> module.exports = {
>   exportTrailingSlash: true,
> }
> ```

Oh, I had not tried that. From the docs I thought that just added trailing slashes! 
Thank you for the help.

**Comment by marlonmarcello** [comment] 2020-07-22 03:55
I have a use case for this.
I'm trying to localize a website and I have the following config:
```js
module.exports = {
  exportTrailingSlash: true,
  exportPathMap: async function (
    defaultPathMap,
    { dev, dir, outDir, distDir, buildId }
  ) {
    const locales = ["fr", "es"];
    let newPathMap = { ...defaultPathMap };

    for (let locale of locales) {
      for (let key of Object.keys(defaultPathMap)) {

        newPathMap[`/${locale}${key}`] = {
          ...defaultPathMap[key],
          query: {
            localeKey: locale,
          },
        };
      }
    }

    return newPathMap;
  },
};
```

I wanna use the `localeKey` inside `getStaticProps` so I can fetch the props locale `json` using `fs`, something like the example on the docs here: https://nextjs.org/docs/basic-features/data-fetching#reading-files-use-processcwd

In summary, I wanna have 1 template file that gets outputted 3 times, one for each language, without duplicating the template file and using `exportPathMap`.

**Comment by aaranmcguire** [comment] 2020-08-08 21:52
> Have you [tried enabling this option](https://nextjs.org/docs/api-reference/next.config.js/exportPathMap#adding-a-trailing-slash)?
> 
> ```js
> // next.config.js
> module.exports = {
>   exportTrailingSlash: true,
> }
> ```

Just wanted to follow up and say this worked.

**Comment by sean256** [comment] 2020-10-27 20:51
@marlonmarcello did you find a solution to your locale problem?

**Comment by marlonmarcello** [comment] 2020-10-28 17:07
Ended using a combination of templates @sean256 
Something like:
```
pages/
  about/
    index.js
    fr/
      index.js
page-templates/
  about/
    index.js
```

Inside the `pages/` files I would import the proper JSON locale and pass that to the template.
So my `about/fr/index.js` would look something like this:
```js
import AboutTemplate from 'page-templates/about';
import locale from 'i18/fr/about.json';

export default function AboutPage() {
  return <AboutTemplate locale={locale} />
}
```

So in the end I had a bunch of files inside `pages/` that would just do that. It also allowed me to NOT localize a page in case the copy writer hadn't make copy for it.
Wasn't as automated as I wanted but it worked.

**Comment by oliviertassinari** [comment] 2020-11-28 18:51
It seems that we have fallen into this issue in https://github.com/mui-org/material-ui/pull/23726. We have the following structure:

- `_app.js` uses `getInitialProps` to read the *request* and set the locale in a React context, we have a custom locale negotiation logic.
- `pages/docs-api/COMPONENT_NAME.js` uses `getStaticProps` as the content is static, we don't need to use `getInitialProps`. It's also interesting so we can read the filesystem and only send to the client a subset of the data.

It works almost great. When we build the static export, the `exportPathMap` isn't respected. The default path/locale is generated and work correctly, however, the `/:locale/docs-api/COMPONENT_NAME` pages aren't generated.

**Comment by jimisaacs** [comment] 2021-03-16 22:49
So I gather, that any page with `getStaticProps` defined, regardless of being returned in `exportPathMap` still gets exported?

If so this https://nextjs.org/docs/api-reference/next.config.js/exportPathMap needs a serious update, because I'm wondering how many people outside of just myself have wasted hours on this.

**Comment by jimisaacs** [comment] 2021-03-19 07:59
For this reason, and #16090, I ended up removing all usages of `getStaticProps`

**Comment by cytronn** [comment] 2021-04-15 09:48
I'm currently using exportPathMap for this kind of case 
`pathMap['/a-propos'] = { page: '/about', query: { language: 'fr' } }
    pathMap['/about'] = { page: '/about', query: { language: 'en' } }`

What would be the correct way to do it using only the getStaticProps way?

**Comment by devdpontes** [comment] 2021-05-04 11:22
I have a similar problem. We are exclusively using `exportPathMap`, but recently started to migrate to `getStaticProps`. One of our use cases with `exportPathMap` is to export only 1 page, when we want to. Moving to `getStaticProps` makes this impossible.

**Comment by devdpontes** [comment] 2021-07-19 08:51
Any news on this one? This is quite critical for us as migrating to `getStaticProps` doesn't allow us to keep our 1 page export flow. With `exportPathMap` and `getInitialProps` we can just re-export any give page individually without doing a new build, but that's not possible with `getStaticProps`, because we rely on an env var that gets read during the export. Because `exportPathMap` lives in the config file, that works fine, but not with `getStaticProps`.

**Comment by oliviertassinari** [comment] 2021-07-20 14:17
@devdpontes Could you upvote the issue? The more feedback, the likely the core team will prioritize this problem.

**Comment by devdpontes** [comment] 2021-07-21 13:32
I get that the core team probably prefer if people end up using ISR, but it's overkill for us. We have a system in place where we can export pages individually on demand. All we want is for `exportPathMap` to take over when it returns a list of paths during an export. If it's supposed to be used for more advanced cases, I think it would make sense. If there are no plans or any possibility of that happening, we need to consider alternatives.

**Comment by furcan** [comment] 2021-07-22 21:40
`getStaticProps` is completely useless with `next export`. (Also `exportPathMap`)

I think the Next.js dev team is thinking the people around the world using the Next.js just to create a single "index.js" file, and print a "hello world!"

All the communication between the dev team and us is just like that: "We will not create a solution, use the Next.js just like that or else..."

Anyway,
Thanks.

**Closed** 2021-12-20 11:18 UTC
Labels: area: documentation, kind: story

**Comment by balazsorban44** [comment] 2022-01-27 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
