### ISSUE TITLE
Page was incorrectly cached when Route parameter contains `:` 

### ISSUE THREAD

**Issue by Coxxs** [vercel/next.js#38581] opened 2022-07-13 09:00 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.4.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.3-canary.3
      eslint-config-next: 12.2.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Google Chrome Version 103.0.5060.114 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

```
npm run build
npm run start
```

### Describe the Bug

When the Route parameter contains the `:` character, page uses getServerSideProps will be incorrectly cached in the browser by next.js.

This is because an encoding error in `cacheKey` causing next.js unable to `delete _this.sdc[cacheKey]` (Server Data Cache)

https://github.com/vercel/next.js/blob/13557eac6fb599bb9b29c076c59c7117498ad0c5/packages/next/shared/lib/router/router.ts#L1841-L1847

### Expected Behavior

Even if Router parameter contains the `:` character, page uses getServerSideProps should not be cached.

### Link to reproduction

https://next-cache-test-fawn.vercel.app/

### To Reproduce

Click the second & fourth link repeatedly, the server generated content will not change because it's cached in browser.

**This is only reproducible in `production` build.**

I've disabled the minimize (`config.optimization.minimize = false`) to make it easy to debug.

Demo: https://next-cache-test-fawn.vercel.app/
Demo source: https://github.com/Coxxs/next-cache-test/commit/fe30c1abf8e713b601634fda3e1016d7ad02d77b

**Comment by visnup** [comment] 2022-08-12 16:24
I think duplicate of #39271

**Comment by visnup** [comment] 2022-08-12 16:38
Going to attempt to fix this. I think I also narrowed down the regression to #37646, which has related code to what you pointed out.

**Comment by GioLogist** [comment] 2022-08-17 20:16
@visnup If it helps, we're experiencing this issue as well. On SSR pages and when the `@` is present. It makes the specific query parameter that has `@` be removed on subsequent (client-side) navigations.

**Comment by Coxxs** [comment] 2022-08-18 18:26
[patch-package](https://github.com/ds300/patch-package) is a good way to fix your project before next.js merging the PR

**Closed** 2022-09-02 04:22 UTC
Labels: template: bug
