### ISSUE TITLE
Bug: Suspense | client component should have a queue

### ISSUE THREAD

**Issue by xiel** [vercel/next.js#44686] opened 2023-01-07 18:14 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

React version: 18.2.0
Next version: 13.1.1

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/s/github/xiel/app-playground/tree/suspense-error/?from-embed=&file=/app/page.tsx

### To Reproduce

1. Suspend using a (fake) promise in a client component in app dir (next)
2. Try to useState after the use() call

````tsx
'use client';

import { use, useState } from 'react';

const testPromise = new Promise((resolve) => {
  setTimeout(() => {
    resolve('use test promise');
  });
});

export default function Page() {
  use(testPromise);
  useState(0);

  return <h1>Test</h1>;
}

````

### Describe the Bug

Suspending for a promise in a client component and using state/reducer after results in errors during hydration:

```
react-dom.development.js?9d87:94 Warning: An error occurred during hydration. The server HTML was replaced with client 

react-dom.development.js?9d87:94 Warning: You are accessing "digest" from the errorInfo object passed to onRecoverableError. 

on-recoverable-error.js?eb92:17 Uncaught Error: Should have a queue. This is likely a bug in React. Please file an issue.
```

### Expected Behavior

No error during hydration.

**Comment by govind15496** [comment] 2023-01-07 18:19
It sounds like you are trying to use a value that is being set in a Promise in a React component, and that you are getting an error when the component is hydrated (that is, when the client-side React app takes over from the server-side rendering).

One thing that can cause this error is if the value that you are trying to access from the Promise has not yet been resolved when the component is rendered on the server. If this is the case, the value will be undefined when the component is initially rendered, and then it will be updated with the resolved value when the Promise is fulfilled. However, during the hydration process, React will see that the value is different on the client than it was on the server, and it will raise an error.

To fix this issue, you can try wrapping the code that accesses the value from the Promise in a useEffect hook, and make sure to include the value from the Promise in the dependency array. This will ensure that the component is re-rendered when the value is updated, and it should prevent the hydration error from occurring.

It's also possible that the error is being caused by something else, so if this suggestion doesn't help, it might be helpful to provide more context about your code and how you are using the Promise and the state/reducer.

**Comment by xiel** [comment] 2023-01-07 18:24
@govind15496 Did ChatGPT write this for you? No need to spam my issues, thank you.

**Comment by eps1lon** [comment] 2023-01-18 20:36
We can close this in favor of https://github.com/facebook/react/issues/25964 since we've confirmed this is a bug and a fix is being worked on.

**Closed** 2023-01-19 08:08 UTC
Labels: template: bug
