### ISSUE TITLE
Link in  description for `next-script-for-ga` eslint-rule is dead

### ISSUE THREAD

**Issue by lforst** [vercel/next.js#28834] opened 2021-09-06 11:15 UTC
### What version of Next.js are you using?

Next: 11; @next/eslint-plugin-next: 11.1.2

### What version of Node.js are you using?

14

### What browser are you using?

irrelevant

### What operating system are you using?

irrelevant

### How are you deploying your application?

irrelevant

### Describe the Bug

1) The link in the documentation for the nex.js eslint rule "next/next-script-for-ga" at https://nextjs.org/docs/basic-features/eslint#eslint-plugin is broken. It leads to a 404 page.

2) The actual eslint warning message contains the same link.

### Expected Behavior

I would expect the links not to lead to a 404 page but to a page explaining the eslint rule.

### To Reproduce

First:
- [ ] Visit https://nextjs.org/docs/basic-features/eslint#eslint-plugin.
- [ ] Go to section "ESLint Plugin".
- [ ] Klick on the link "next/next-script-for-ga"
- [ ] See 404 page

Second:
- [ ] Install @next/eslint-plugin-next eslint plugin
- [ ] Use a normal script tag instead of a `next/script` tag
- [ ] See eslint warning
- [ ] Try to visit link in eslint warning
- [ ] See 404 page

**Comment by stefanprobst** [comment] 2021-09-06 11:25
i think this was already fixed in https://github.com/vercel/next.js/pull/28643 and should go live with the next release.

**Closed** 2021-09-06 11:41 UTC
Labels: template: bug

**Comment by lforst** [comment] 2021-09-06 11:44
> i think this was already fixed in #28643 and should go live with the next release.

Nice to hear! Thanks!

**Comment by balazsorban44** [comment] 2022-01-27 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
