### ISSUE TITLE
Example for RSS/Atom feed utilizing SSR

### ISSUE THREAD

**Issue by marcofranssen** [vercel/next.js#20457] opened 2020-12-24 13:25 UTC
There are many examples out there on the internet showing some RSS feed generation using strings and custom build processes to store the rss in the public folder.

I do think there should be a way to do this via static site generation, but there isn't a documented approach for this. It would be great to have an example worked out on the blog example that shows how to do this if possible at all.

If this capability doesn't work today I think it would be a great feature to be able to generate the atom/rss feed at build time.

**Comment by timneutkens** [comment] 2021-01-03 15:09
Closing as the issue template was ignored/removed.

**Closed by timneutkens** 2021-01-03 15:09 UTC
Labels: template: story

**Comment by marcofranssen** [comment] 2021-01-04 11:45
Sorry for not following the template. #20736

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
