### ISSUE TITLE
Cannot build and export automatically optimized pages, I get "error ocurred prerendering page...

### ISSUE THREAD

**Issue by arochadaniel** [vercel/next.js#13462] opened 2020-05-27 18:51 UTC
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by Timer** [comment] 2020-05-27 19:07
Closing as issue template was not followed.

**Closed by Timer** 2020-05-27 19:07 UTC

**Comment by balazsorban44** [comment] 2022-01-30 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
