### ISSUE TITLE
blurDataUrl error when using correct file format

### ISSUE THREAD

**Issue by AsherWright** [vercel/next.js#42274] opened 2022-11-01 05:02 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

I get this error:

```
Error: Image with src "/dice.png" has "placeholder='blur'" property but is missing the "blurDataURL" property.
          Possible solutions:
            - Add a "blurDataURL" property, the contents should be a small Data URL to represent the image
            - Change the "src" property to a static import with one of the supported file types: jpeg,png,webp,avif
            - Remove the "placeholder" property, effectively no blur effect
          Read more: https://nextjs.org/docs/messages/placeholder-blur-data-url
```

When I run my dev server, even though the image I'm using _is_ one of the supported file types (png). I may be missing something obvious, but I can't figure it out from the message above.

### Describe the Bug

When I run my dev server, I get an error about using the `blur` prop with Next Image. It tells me that I can't use it unless I'm using a supported file type, but I am using a supported file type.

### Expected Behavior

The blur prop should work with a `png`.

### Link to reproduction

https://codesandbox.io/s/gracious-haze-uy1w8p?file=/pages/index.tsx

### To Reproduce

Start the dev server and look at the error.

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/8315137/199162701-28703a9a-cf5f-4d47-b270-e930fe0f2490.png">

**Comment by styfle** [comment] 2024-05-17 20:48
Closing since this is expected behavior. The error message explains it:

Possible solutions:
  - Add a "blurDataURL" property, the contents should be a small Data URL to represent the image
  - Change the "src" property to a static import with one of the supported file types: jpeg,png,webp,avif
  - Remove the "placeholder" property, effectively no blur effect
Read more: https://nextjs.org/docs/messages/placeholder-blur-data-url

**Closed by styfle** 2024-05-17 20:48 UTC
Labels: bug
