### ISSUE TITLE
dynamic nested route matches where it should 404

### ISSUE THREAD

**Issue by Janpot** [vercel/next.js#10550] opened 2020-02-16 14:29 UTC
# Bug report

## Describe the bug

Give the pages structure

```js
/pages
  /[post]
    /[comment].js
  /user
    /home.js
```

When you visit the url `/user/non-existing` it will render `/[post]/[comment].js` instead of 404. It's clear that the developer intends for the `/user` prefix to be its own subsection, so when visiting routes in that subsection it is unexpected to match anything form the `/[post]` folder.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Example at https://codesandbox.io/s/goofy-moore-mmi49
2. Go to `/user/non-existing`
3. Observe

## Expected behavior

It should 404

**Comment by timneutkens** [comment] 2020-02-16 15:20
This is expected behavior imo. You have a dynamic top level route and it matches that.

**Comment by Janpot** [comment] 2020-02-16 15:41
Imagine the following situation:
```
/pages
  /[post]
    /hello.js
  /user
    /home.js
```
Imagine team A is mainly working on `/user/...` code and team B is mainly working on `/[post]/...` code.
Now team B can just break team A's code without touching anything in the `/user/...` tree. All they have to do is add a `/[post]/[comment].js` and team A's code breaks.
I think it's quite expected behavior that sibling folders have a relatively high level of isolation.

**Comment by Janpot** [comment] 2020-02-16 15:48
Imagining zeit.co looks more or less like
```
/pages
  /dashboard
    /index.js
    /projects.js
    /integrations.js
    /activity.js
  /[userid]
    /index.js
```
Which route would break when my proposal was inplemented? Because right now, when I go to `/my-username/projects` I get a 404. Which is exactly what I propose here. But maybe that's a bug on zeit.co?

**Comment by Timer** [comment] 2020-09-10 18:26
Closing as this is the intended behavior and we cannot break it now.

**Closed by Timer** 2020-09-10 18:26 UTC

**Comment by balazsorban44** [comment] 2022-01-29 13:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
