### ISSUE TITLE
Hydration errors should trigger the dev-error-overlay

### ISSUE THREAD

**Issue by ijjk** [vercel/next.js#8417] opened 2019-08-18 19:51 UTC
Currently hydration warnings only appear in the console and can be easy to miss. Since hydration errors can have very bad effects we should trigger the dev-error-overlay to make sure the user is aware of them

**Comment by lachlanjc** [comment] 2021-01-08 06:38
Duplicate of #13950?

**Comment by timneutkens** [comment] 2021-01-11 12:47
Yep! Duplicate of #13950

**Closed by timneutkens** 2021-01-11 12:47 UTC
Labels: kind: story, priority: p2

**Comment by balazsorban44** [comment] 2022-01-28 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
