### ISSUE TITLE
not working tailwind (turbopack + pnpm )

### ISSUE THREAD

**Issue by kimjh0813** [vercel/next.js#72174] opened 2024-11-01 07:32 UTC
### Link to the code that reproduces this issue

https://github.com/kimjh0813/turbopack-tailwind-bug

### To Reproduce

1. Initialize a New Next.js Project:
```
npx create-next-app@latest
```
2. Configure Project Settings:
TypeScript: Yes
ESLint: Yes
Tailwind CSS: Yes
src/ Directory: Yes
App Router: Yes
Turbopack for Next Dev: Yes
Customize Import Alias: No

3. delete node_modules folder, .next folder, package-lock.json file and then pnpm install

4. pnpm dev (next dev --turbopack)

### Current vs. Expected behavior

Current behavior
Tailwind doesn't apply in pnpm
<img width="1822" alt="nextjs-pnpm-tailwind" src="https://github.com/user-attachments/assets/1ef9a727-84c4-47c0-9c31-fbc13c3e4499">

Expected behavior

<img width="1822" alt="nextjs-npm-tailwind" src="https://github.com/user-attachments/assets/5ac150cc-2491-4e8f-af0a-48fc90eb1478">
tailwind works well with yarn and npm, tailwind does not work with pnpm

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Tue Sep 17 07:48:04 PDT 2024; root:xnu-11215.40.59~38/RELEASE_ARM64_T8112
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 8.6.7
Relevant Packages:
  next: 15.0.1 // There is a newer version (15.0.2) available, upgrade recommended! 
  eslint-config-next: 15.0.1
  react: 19.0.0-rc-69d4b800-20241021
  react-dom: 19.0.0-rc-69d4b800-20241021
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

If you run next dev --turbopack in pnpm, tailwind is not applied, but if you run next dev without turbopack, tailwind works fine.
I don't have this problem with npm and yarn, but only with pnpm.

**Comment by timneutkens** [comment] 2024-11-01 09:54
Checked the reproduction repository but can't reproduce it either. Here's a codesandbox of the repo: https://codesandbox.io/p/github/kimjh0813/turbopack-tailwind-bug/main

Going to close this issue as it's not actionable right now.

**Closed by timneutkens** 2024-11-01 09:54 UTC
Labels: bug, Turbopack

**Comment by kimjh0813** [comment] 2024-11-01 13:41
I found the exact cause of the problem. 
In pnpm 8.6.7 version, tailwind is not applied when following the example
However, it doesn't seem to be a version 8 issue, so I'll have to raise the pnpm version
