### ISSUE TITLE
Next 12 Module Resolution broken for Yarn 2 PNP

### ISSUE THREAD

**Issue by sicarius97** [vercel/next.js#32546] opened 2021-12-15 18:07 UTC
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.9.0

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu, Windows

### How are you deploying your application?

next start

### Describe the Bug

I upgraded from next 11.1.0 to the most recent next release 12.0.7 after the eslint issues got fixed and found that deps resolution seems to be slightly broken for yarn 2 pnp. Next 11 was mostly compatible with yarn 2 pnp and various other yarn 2 resolution methods, but next 12 seems to have broken that system. I can't confirm that this holds true for all next 12 releases, but has been confirmed on 12.0.7 and 12.0.6. When running my local dev server, these are some of the errors I am getting: 

![image](https://user-images.githubusercontent.com/73046273/146240069-880671f0-effa-4475-9c10-1acd7ec20e38.png)
![image](https://user-images.githubusercontent.com/73046273/146240129-ad4432a6-4a72-4afa-bd09-881299abad4f.png)

I have also confirmed in a separate project that next 12 DOES work with yarn 2 nodeLinker resolution mode, but I prefer a zero install method that uses solely yarn cache with no node_modules in pretty much all my projects, that way all deps can be packaged with my repo, which is becoming a more and more popular method with many javascript/nodejs devs with the advent of yarn 2.

### Expected Behavior

The expected behavior would be for the nextjs application to compile as normal, as this issue is preventing the whole app from compiling. 

### To Reproduce

The following steps would allow someone to quickly bootstrap a project like this one:

`npm install -g yarn`

`yarn set version berry`

`yarn dlx create-next-app .`

(If you have to, put the app in a child directory and then re copy paste everything into the parent directory as I dont think my PR that would fix yarn dlx create-next-app . on this repo has been merged. Also make sure version is next 12.0.7)

Ensure that the .yarnrc.yml nodeLinker setting does not have any entry or is set to pnp. Then run the following:

`yarn install`

`yarn dev`

**Comment by sicarius97** [comment] 2021-12-15 20:48
Tried some further investigating, though I will need to look more into the pnp api, and found that the virtual mapping appears to be part of the issue. Though, webpack used to have some issues that gave very similar output, so I will also be looking into what is going on with webpack when the dev server starts to see if it gives me any further ideas on why these modules are showing  that they cannot be resolved or dont exist. I took a look at the pnp.cjs as well and it looks like pretty much everything is mapped the same as it was in 11.1.0, so I am unsure yet where this issue is stemming from

**Comment by rtritto** [comment] 2021-12-16 19:53
This issue is related also to yarn v3 (`yarn set version berry` command will install latest yarn version, currently it's v3).

Related issue: #31812

Temporary workaround: https://github.com/vercel/next.js/issues/31812#issuecomment-985034251

**Comment by sicarius97** [comment] 2021-12-18 01:23
I did not see the related issue @rtritto mentioned, but the version of yarn I am using is also 3.0.2. I believe all new versions are colloquially referred to as "yarn 2"

**Comment by rtritto** [comment] 2021-12-18 11:58
_yarn_  _v2_ and  _v3_ are both versions of _yarn berry_.

**Comment by sicarius97** [comment] 2021-12-21 16:32
> _yarn_  _v2_ and  _v3_ are both versions of _yarn berry_.

@rtritto that's the name of their repo and release cycle, the proper names are yarn 1 or yarn classic and yarn 2. They refer to all post classic versions as yarn 2 all over their docs and in most of their news releases. Anyway, it doesn't matter, semantics. The point is, yarn (berry or 2 or 3.0.x) pnp resolution is currently broken on next 12

**Comment by balazsorban44** [comment] 2022-01-11 12:14
Seems to be a duplicate of #32115

**Closed by balazsorban44** 2022-01-11 12:14 UTC
Labels: template: bug, area: Yarn PnP / pnpm
