### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by ajmeraaxesh** [vercel/next.js#23757] opened 2021-04-07 04:12 UTC
### What version of Next.js are you using?

10.1.1

### What version of Node.js are you using?

15.13.0

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

09:29:21.810  	> Build error occurred
09:29:21.812  	ReferenceError: regeneratorRuntime is not defined
09:29:21.812  	    at create (/vercel/path0/node_modules/zustand/index.js:156:31)
09:29:21.812  	    at Object.Bl7J (/vercel/path0/.next/server/pages/index.js:648:50)
09:29:21.813  	    at __webpack_require__ (/vercel/path0/.next/server/pages/index.js:23:31)
09:29:21.813  	    at Module.RXBc (/vercel/path0/.next/server/pages/index.js:1352:14)
09:29:21.813  	    at __webpack_require__ (/vercel/path0/.next/server/pages/index.js:23:31)
09:29:21.813  	    at Object.9 (/vercel/path0/.next/server/pages/index.js:498:18)
09:29:21.813  	    at __webpack_require__ (/vercel/path0/.next/server/pages/index.js:23:31)
09:29:21.814  	    at /vercel/path0/.next/server/pages/index.js:91:18
09:29:21.814  	    at Object.<anonymous> (/vercel/path0/.next/server/pages/index.js:94:10)
09:29:21.814  	    at Module._compile (internal/modules/cjs/loader.js:999:30) {
09:29:21.814  	  type: 'ReferenceError'
09:29:21.814  	}

### Expected Behavior

Should work without any issues

### To Reproduce

Tryin to redeploy this on Vercel

I am completely clueless as to why this is happening on Vercel. The same commit I reverted back and try redeploying and I am seeing a similar error in Vercel. I have no babel.rc file. 

09:29:21.810 | > Build error occurred
-- | --
09:29:21.812 | ReferenceError: regeneratorRuntime is not defined
09:29:21.812 | at create (/vercel/path0/node_modules/zustand/index.js:156:31)
09:29:21.812 | at Object.Bl7J (/vercel/path0/.next/server/pages/index.js:648:50)
09:29:21.813 | at __webpack_require__ (/vercel/path0/.next/server/pages/index.js:23:31)
09:29:21.813 | at Module.RXBc (/vercel/path0/.next/server/pages/index.js:1352:14)
09:29:21.813 | at __webpack_require__ (/vercel/path0/.next/server/pages/index.js:23:31)
09:29:21.813 | at Object.9 (/vercel/path0/.next/server/pages/index.js:498:18)
09:29:21.813 | at __webpack_require__ (/vercel/path0/.next/server/pages/index.js:23:31)
09:29:21.814 | at /vercel/path0/.next/server/pages/index.js:91:18
09:29:21.814 | at Object.<anonymous> (/vercel/path0/.next/server/pages/index.js:94:10)
09:29:21.814 | at Module._compile (internal/modules/cjs/loader.js:999:30) {
09:29:21.814 | type: 'ReferenceError'
09:29:21.814 | }

I am running locally and I am not seeing any error. I am not even sure if this is next's specific or how Vercel is deploying the builds

**Comment by timneutkens** [comment] 2021-04-07 08:30
Duplicate of #23720

**Comment by timneutkens** [comment] 2021-04-07 08:30
Please provide a complete reproduction on the other issue so that it can be investigated.

**Closed by timneutkens** 2021-04-07 08:30 UTC
Labels: template: bug

**Comment by ajmeraaxesh** [comment] 2021-04-07 10:20
I figured out, this is not an issue with the Nextjs library but more like Zustand lib. I reverted back to old version and it works again. Thanks for your response

**Comment by Yuripetusko** [comment] 2021-04-07 14:05
> I figured out, this is not an issue with the Nextjs library but more like Zustand lib. I reverted back to old version and it works again. Thanks for your response

Got the same problem this morning by updating zutsang

**Comment by balazsorban44** [comment] 2022-01-28 13:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
