### ISSUE TITLE
Type Error on next/image: Types of property 'placeholder' are incompatible.

### ISSUE THREAD

**Issue by tpae** [vercel/next.js#25344] opened 2021-05-21 23:45 UTC
### What version of Next.js are you using?

10.2.2

### What version of Node.js are you using?

v12.4.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

```
import Image, { ImageProps } from 'next/image';
import React from 'react';

const NetworkImage: React.FC<Partial<ImageProps>> = (props) => {
  return (
    <Image
      width={24}
      height={24}
      objectFit="contain"
      layout="fixed"
      {...props}
    />
  );
};

export default NetworkImage;
```

Getting this error on build:

```
Type error: Type '{ layout: "fixed"; src: string; placeholder: "empty"; color?: string | undefined; translate?: "yes" | "no" | undefined; hidden?: boolean | undefined; defaultChecked?: boolean | undefined; ... 264 more ...; blurDataURL?: undefined; } | ... 4 more ... | { ...; }' is not assignable to type 'IntrinsicAttributes & ImageProps'.
  Type '{ layout: "fixed"; src: string; placeholder: "empty"; color?: string | undefined; translate?: "yes" | "no" | undefined; hidden?: boolean | undefined; defaultChecked?: boolean | undefined; ... 264 more ...; blurDataURL?: string | undefined; }' is not assignable to type 'IntrinsicAttributes & ImageProps'.
    Type '{ layout: "fixed"; src: string; placeholder: "empty"; color?: string | undefined; translate?: "yes" | "no" | undefined; hidden?: boolean | undefined; defaultChecked?: boolean | undefined; ... 264 more ...; blurDataURL?: string | undefined; }' is not assignable to type '{ placeholder: "blur"; blurDataURL: string; }'.
      Types of property 'placeholder' are incompatible.
        Type '"empty"' is not assignable to type '"blur"'.
```

### Expected Behavior

Should not get the type error

### To Reproduce

```
import Image, { ImageProps } from 'next/image';
import React from 'react';

const NetworkImage: React.FC<Partial<ImageProps>> = (props) => {
  return (
    <Image
      width={24}
      height={24}
      objectFit="contain"
      layout="fixed"
      {...props}
    />
  );
};

export default NetworkImage;
```

**Comment by brandonchinn178** [comment] 2021-05-23 02:07
I've had a similar problem even on earlier versions of Next (e.g. 10.0). I'm trying to wrap the `Image` component for an icon; e.g.
```ts
function MyImage(props: Omit<ImageProps, 'src'>) {
  return <Image src="path/to/image.svg" {...props} />
}
```
which gets me
```
 Types of property 'width' are incompatible.
  Type 'string | number | undefined' is not assignable to type 'string | number'.
    Type 'undefined' is not assignable to type 'string | number'.
```
So I've been forced to copy and paste part of the `ImageProps` definition:
```ts
// copied from https://github.com/vercel/next.js/blob/9b3edd3b2476b9915fe8c94071a77ac8e8f14499/packages/next/client/image.tsx#L48-L59
// need to rewrite for typescript
type LayoutValue = 'fill' | 'fixed' | 'intrinsic' | 'responsive' | undefined
type ImageSize =
  | {
      width?: never
      height?: never
      /** @deprecated Use `layout="fill"` instead */
      unsized: true
    }
  | { width?: never; height?: never; layout: 'fill' }
  | {
      width: number | string
      height: number | string
      layout?: Exclude<LayoutValue, 'fill'>
    }

type MyImageProps = Omit<ImageProps, 'src'> & ImageSize
function MyImage(props: MyImageProps) {
  return <Image src="path/to/image.svg" {...props} />
}
```
which worked up until upgrading 10.0.9 => 10.2.2, where I get the error posted above. The workaround for now is to also copy the placeholder type:
```ts
type LayoutValue = 'fill' | 'fixed' | 'intrinsic' | 'responsive' | undefined
type ImageSize =
  | {
      width?: never
      height?: never
      /** @deprecated Use `layout="fill"` instead */
      unsized: true
    }
  | { width?: never; height?: never; layout: 'fill' }
  | {
      width: number | string
      height: number | string
      layout?: Exclude<LayoutValue, 'fill'>
    }
type PlaceholderValue = 'blur' | 'empty'
type ImagePlaceholder =
  | {
      placeholder?: Exclude<PlaceholderValue, 'blur'>
      blurDataURL?: never
    }
  | { placeholder: 'blur'; blurDataURL: string }

type MyImageProps = Omit<ImageProps, 'src'> & ImageSize & ImagePlaceholder
function MyImage(props: MyImageProps) {
  return <Image src="path/to/image.svg" {...props} />
}
```
It would be really nice for Next to either:
1. Make the types work so that `Omit<ImageProps, 'src'>` just works, or
2. Export `ImageSize` and `ImagePlaceholder` as defined above, so we can reference them

**Comment by kristian240** [comment] 2021-05-24 13:43
Yeah, I can agree, with current typing, Next Image is really hard to expand. Maybe we are wrong and this is possible, but if we are, it would be cool if there is an example of how to do this.

Next team, please help us out here 🙏🏼

**Comment by deadcoder0904** [comment] 2021-05-25 10:32
Is [my error](https://github.com/vercel/next.js/issues/25440) related as well?

**Comment by brandonchinn178** [comment] 2021-05-25 15:18
Oh yeah, maybe!

**Comment by Vandivier** [comment] 2021-05-31 18:12
seems related... https://www.typescriptlang.org/docs/handbook/2/mapped-types.html#further-exploration

**Comment by ijjk** [comment] 2021-07-20 20:38
Hi, this has been updated in `v11.0.2-canary.18` of Next.js specifically https://github.com/vercel/next.js/pull/26991, please update and give it a try!

I'm gonna close this since it should be resolved, if you are still having issues with this please respond with additional info and we can investigate further!

**Closed by ijjk** 2021-07-20 20:38 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
