### ISSUE TITLE
"ReferenceError: global is not defined" with concurrentFeatures: true and relay.dev

### ISSUE THREAD

**Issue by bbigras** [vercel/next.js#30968] opened 2021-11-04 16:09 UTC
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

v14.18.0

### What browser are you using?

Firefox

### What operating system are you using?

NixOS

### How are you deploying your application?

npm run dev

### Describe the Bug

I got this error while trying concurrentFeatures with relay.dev.

It's fine with `concurrentFeatures: false`.

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/bbigras/dev/my_test/.env
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

info  - Using the createRoot API for React
warn  - You are using an unsupported prerelease of 'react-dom' which may cause unexpected or broken application behavior. Continue at your own risk.
info  - Using the experimental web runtime.
warn  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from /home/bbigras/dev/my_test/.babelrc

warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
wait  - compiling...
event - compiled successfully in 20.1s (449 modules)
warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
wait  - compiling /...
wait  - compiling...
event - compiled successfully in 2.1s (810 modules)
error - ReferenceError: global is not defined
wait  - compiling /_error...
wait  - compiling...
event - compiled successfully in 504 ms (813 modules)
```

### Expected Behavior

No error

### To Reproduce

I could provide one.

**Comment by kesne** [comment] 2021-11-10 21:58
It appears that relay looks for a global named `global`, which works fine in Node, but not in the sandbox environment that edge functions run in. I verified that exposing a global named `global` fixes Relay (essentially what this PR does, but with the name `global`: https://github.com/vercel/next.js/pull/30877/files).

**Comment by huozhi** [comment] 2021-11-10 22:08
Thanks @kesne 
It works with next version above 12.0.3, could you please try it again? @bbigras

**Comment by kesne** [comment] 2021-11-12 04:43
@huozhi That PR doesn't fix it, Relay depends on a global named `global`, not `globalThis`, so this is still a bug.

**Comment by Hectordeluna** [comment] 2021-11-12 04:45
I'm having the same problem, adding context.global = context does fix the problem like the pr above

**Comment by huozhi** [comment] 2021-11-12 10:55
@bbigras @kesne Could you provide a minimal reproduction for this? Would be helpful that we can investigate the error trace based on the repro 🙏 Thanks

If tried with latest canary that `global` is accessible. Wonder how the error is thrown.
<img with="100" src="https://user-images.githubusercontent.com/4800338/141455671-f7e822ad-e30b-4de6-92ab-daaf098bb3d5.png">

**Comment by rrdelaney** [comment] 2021-11-16 00:41
@huozhi I created a repro at [rrdelaney/react-18-relay-nextjs-repro](https://github.com/rrdelaney/react-18-relay-nextjs-repro). To reproduce:

1. Clone repo and `npm i`
2. Run `npm run dev`
3. Load [`http://localhost:3000`](http://localhost:3000). Should get something like:

```
wait  - compiling...
warn  - ./node_modules/next/dist/build/webpack/loaders/next-middleware-ssr-loader/index.js?page=%2F&absoluteAppPath=private-next-pages%2F_app&absoluteDocumentPath=private-next-pages%2F_document&absoluteErrorPath=private-next-pages%2F_error&absolutePagePath=%2FUsers%2Fryan%2FDevelopment%2Frelay-sc%2Fsrc%2Fpages%2Findex.tsx&isServerComponent=false&buildId=development&basePath=&assetPrefix=!
Module not found: Can't resolve './pages/500' in '/Users/ryan/Development/relay-sc'
error - ReferenceError: global is not defined
```

**Comment by huozhi** [comment] 2021-11-16 16:03
Thanks for providing the reproduction!

Currently, when you enable experimental flag `concurrentFeatures` as `true`, it will use the "custom web rumtime". That's the one which we polyfilled some browser runtime API and pack code as web bundle to run there. This is now supported both in local development and production if you deployed to vercel, as it's still "experimental". This requires library to be better compatible across environment, like the case that `globalThis` is as a cross environment reference instead of `global` / `self` / etc.

I'm not sure if relay can just change `global` to `globalThis` since it's a huge breaking change and if it will bring more issues. I just tried if I change `global` to `globalThis` in [this line](https://github.com/facebook/relay/blob/38f1c96e7696378b55f68509a320a36846457bbe/packages/relay-runtime/store/RelayPublishQueue.js#L61) and it works locally for the reproduction.

We're working on the next step to provide user more flexibility to try it with node.js libs with `concurrentFeatures` is enabled. Fully supporting it on production might be longer. In short term it's kind a trade-off that you might not easily bring node runtime code to streaming. IMO it would be nicer to make the library more cross-env compatible if it could be.

**Comment by rrdelaney** [comment] 2021-11-16 17:50
@huozhi Great, thanks! That's super helpful. I opened a PR in Relay to hopefully fix this issue. They have another place where they check if `global` is defined so I added it there too.

**Comment by supriome** [comment] 2021-12-09 10:02
I still have this problem.

**Comment by huozhi** [comment] 2022-02-18 09:09
Next.js 12.1.0 is released with a new experimental flag `runtime: 'nodejs' | 'edge'` to replace `concurrentFeatures`. Can you folks try `runtime: 'nodejs'` to see if that works for you? Checkout the [doc](https://nextjs.org/docs/advanced-features/react-18/streaming). Thanks 🙏

Looks like [someone has already make nextjs work with relay](https://github.com/vercel/next.js/discussions/32502#discussioncomment-2197631)

**Comment by huozhi** [comment] 2022-07-26 14:01
Going to close this issue as the original request is resolved.

@pranshu1995 Could you open a new issue with a reproduction for it so we can check what's going on deep in the code and track it separately?

**Closed by huozhi** 2022-07-26 14:01 UTC
Labels: template: bug, area: Concurrent Features
