### ISSUE TITLE
Warn when a query is provided to `as` but not `href`

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#8026] opened 2019-07-18 11:55 UTC
Pointed out in https://github.com/zeit/next.js/pull/8022, Next.js doesn't provide guidance that the `href` must also provide the query string used in `as`. We should add a useful warning or suggestion in this case.

**Comment by HosseinAgha** [comment] 2020-02-10 15:34
I've encountered this error many times when developing NextJS apps. The terrible thing about this is that everything works when you make this mistake but the `Link` acts like an actual link and initiates a serverside request (clearing ApolloClient cache, etc).   
This turns into a headache when every new developer keeps bumping into this error and silently breaks the production cache.

**Comment by mikhalev-im** [comment] 2020-08-31 17:28
I would like to try to work on this issue. I see that there is a closed merge request linked, but it doesn't say why exactly it was not merged. Is there something I need to be aware of?

**Comment by timneutkens** [comment] 2020-09-01 07:19
This issue is no longer needed since `as` is no longer needed in most cases on the current canary release (soon stable)

**Closed by timneutkens** 2020-09-01 07:19 UTC
Labels: good first issue, kind: story

**Comment by balazsorban44** [comment] 2022-01-29 15:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
