### ISSUE TITLE
[Doc] Discord channel invite is not working

### ISSUE THREAD

**Issue by emil-wearealldigital** [vercel/next.js#26239] opened 2021-06-17 04:18 UTC
### What version of Next.js are you using?

11

### What version of Node.js are you using?

14

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

I can't access discord through the invite from the documentation.

### Expected Behavior

The invite should be working.

### To Reproduce

Click on the Discord invite link in the README.

**Comment by awareness481** [comment] 2021-06-17 07:11
Create a temporary [invite link](https://discord.gg/sAce5BsD) until this gets fixed on the repo.

**Closed** 2021-06-17 18:43 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 06:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
