### ISSUE TITLE
CSS with duplicate variables is minified unsafely

### ISSUE THREAD

**Issue by adamwathan** [vercel/next.js#26902] opened 2021-07-03 19:11 UTC
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

15

### What browser are you using?

N/A

### What operating system are you using?

macOS

### How are you deploying your application?

N/A

### Describe the Bug

Given this CSS input:

```css
.a {
  --var-1: 0;
  --var-2: 0;
  --var-1: -50%;
  --var-2: -50%;
}

.b {
  --var-1: 0;
  --var-2: 0;
  --var-2: -50%;
}
```

...when the CSS is minified for production, the output is incorrect (pretty printed so easier to read): 

```css
.a {
  --var-2: 0;
  --var-1: -50%;
  --var-2: -50%;
}
.a,
.b {
  --var-1: 0;
}
.b {
  --var-2: 0;
  --var-2: -50%;
}
```

The `--var-1` variable ends up being `0` for `.a` when it should be `-50%`.

### Expected Behavior

The output should look more like this:

```css
.a {
  --var-1: 0;
  --var-2: 0;
  --var-1: -50%;
  --var-2: -50%;
}
.b {
  --var-1: 0;
  --var-2: 0;
  --var-2: -50%;
}
```

This is what cssnano produces when using cssnano directly rather than through Next.

### To Reproduce

1. Clone this repository: https://github.com/adamwathan/next-css-minification-bug
2. Run `yarn build`
3. Inspect the output CSS, see it's incorrect

This is the underlying problem behind this bug reported on the Tailwind CSS repo: https://github.com/tailwindlabs/tailwindcss/issues/4755

We may be able to work around it on our side by trying to produce slightly different output that avoids this bug but ideally it would get fixed here — hoping it's just a matter of using an outdated version of cssnano or something since cssnano itself seems to work as expected.

**Comment by timneutkens** [comment] 2021-07-05 17:26
Seems this just requires updating cssnano in Next.js.

**Comment by styfle** [comment] 2021-07-14 19:14
Thanks for reporting this issue with great repro steps!

This will be fixed in #27150 👍

**Closed** 2021-07-14 21:16 UTC
Labels: kind: bug

**Comment by styfle** [comment] 2021-07-15 22:00
The fix is available in [v11.0.2-canary.16](https://github.com/vercel/next.js/releases/tag/v11.0.2-canary.16).

You can try it out today with `yarn add next@canary`, thanks!

**Comment by adamwathan** [comment] 2021-07-16 03:19
Thank you! 🙌🏻

**Comment by balazsorban44** [comment] 2022-01-28 02:16
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
