### ISSUE TITLE
Next/link is very slow sometimes it doesn't work

### ISSUE THREAD

**Issue by AsitDixit** [vercel/next.js#53624] opened 2023-08-06 04:25 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home Single Language
    Binaries:
      Node: 18.16.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.12
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

--

### To Reproduce

create a dashboard file inside app create layout.tsx in the dashboard add side nav component in it. now add the tab1,2,3,4,5 file inside dashboard and add page.tsx to each tab file.

Now add the react-apexcharts and react-table( install it).

create random table & charts inside the page.tsx of tabs (requires use client).

Now add the Link of all tabs in the side nav components:

Side nav:

```
export default function SideNavigation() {
  const pathname = usePathname();

  const { isCollapsed, toggleSidebarcollapse } = useContext(SidebarContext);

  return (
    <div className="flex flex-col gap-3 relative ml-3">
      <div className="flex justify-center items-center py-1 rounded-md mt-2">
        <Image src={logo} alt={""} width={28} height={28} />
        <b className={`text-xl ml-3 ${isCollapsed ? "hidden" : "visible"}`}>
          APP NAME
        </b>
      </div>

      <div
        className="absolute rounded-r-full w-5 h-8 -right-[21px] top-20 bg-black flex justify-center items-center"
        onClick={toggleSidebarcollapse}
      >
        {isCollapsed ? (
          <AiFillCaretRight color="white" />
        ) : (
          <AiFillCaretLeft color="white" />
        )}
      </div>

      <Link href={"/dashboard/tab1"}>
        <div
          className={`flex pl-4 pr-4 gap-2 text-sm ${
            isCollapsed ? "justify-center" : "justify-start"
          }  items-center rounded-lg py-2 ${
            pathname == "/dashboard/home"
              ? "bg-green-600 text-zinc-950"
              : "hover:bg-zinc-800"
          }`}
        >
          <BiSolidHomeSmile size={22} />
          <h1
            className={`text-sm font-semibold ml-1 ${
              isCollapsed ? "hidden" : "visible"
            }`}
          >
            Tab1
          </h1>
        </div>
      </Link>

      <div
        className={`h-[0.5px] py-1 border-t-[0.5px] border-zinc-600 ${
          !isCollapsed ? "hidden" : "visible"
        }`}
      ></div>
      <h1
        className={`pl-8 text-sm text-zinc-400 ${
          isCollapsed ? "hidden" : "visible"
        }`}
      >
        SERVICES
      </h1>

      <Link href={"/dashboard/tab2"}>
        <div
          className={`flex pl-4 pr-4 gap-2 text-sm ${
            isCollapsed ? "justify-center" : "justify-start"
          } items-center rounded-lg py-2 ${
            pathname == "/dashboard/analytics"
              ? "bg-green-600 text-zinc-950"
              : "hover:bg-zinc-800"
          }`}
        >
          <IoMdAnalytics size={22} />
          <h1
            className={`text-sm font-semibold ml-1 ${
              isCollapsed ? "hidden" : "visible"
            }`}
          >
            Tab2
          </h1>
        </div>
      </Link>

      <Link href={"/dashboard/tab3"}>
        <div
          className={`flex pl-4 pr-4 gap-2 text-sm ${
            isCollapsed ? "justify-center" : "justify-start"
          } items-center rounded-lg py-2 ${
            pathname == "/dashboard/financial"
              ? "bg-green-600 text-zinc-950"
              : "hover:bg-zinc-800"
          }`}
        >
          <MdPayments size={22} />
          <h1
            className={`text-sm font-semibold ml-1 ${
              isCollapsed ? "hidden" : "visible"
            }`}
          >
            Tab 3
          </h1>
        </div>
      </Link>
      <Link href={"/dashboard/tab4"}>
        <div
          className={`flex pl-4 pr-4 gap-2 text-sm ${
            isCollapsed ? "justify-center" : "justify-start"
          } items-center rounded-lg py-2 ${
            pathname == "/dashboard/payroll"
              ? "bg-green-600 text-zinc-950"
              : "hover:bg-zinc-800"
          }`}
        >
          <MdOutlineCurrencyExchange size={22} />
          <h1
            className={`text-sm font-semibold ml-1 ${
              isCollapsed ? "hidden" : "visible"
            }`}
          >
            Tab 4
          </h1>
        </div>
      </Link>

      <Link href={"/dashboard/tab5"}>
        <div
          className={`flex pl-4 pr-4 gap-2 text-sm ${
            isCollapsed ? "justify-center" : "justify-start"
          } items-center rounded-lg py-2 ${
            pathname == "/dashboard/legal-consulting"
              ? "bg-green-600 text-zinc-950"
              : "hover:bg-zinc-800"
          }`}
        >
          <FaHammer size={22} />
          <h1
            className={`text-sm font-semibold ml-1 ${
              isCollapsed ? "hidden" : "visible"
            }`}
          >
            Tab 5
          </h1>
        </div>
      </Link>
      <div
        className={`h-[0.5px] py-1 border-t-[0.5px] border-zinc-600 ${
          !isCollapsed ? "hidden" : "visible"
        }`}
      ></div>
      <h1
        className={`pl-8 text-sm text-zinc-400 ${
          isCollapsed ? "hidden" : "visible"
        }`}
      >
        GENERAL
      </h1>

      <Link href={"/dashboard/tab6"}>
        <div
          className={`flex pl-4 pr-4 gap-2 text-sm ${
            isCollapsed ? "justify-center" : "justify-start"
          } items-center rounded-lg py-2 ${
            pathname == "/dashboard/customization"
              ? "bg-green-600 text-zinc-950"
              : "hover:bg-zinc-800"
          }`}
        >
          <MdDashboardCustomize size={22} />
          <h1
            className={`text-sm font-semibold ml-1 ${
              isCollapsed ? "hidden" : "visible"
            }`}
          >
            Tab 6
          </h1>
        </div>
      </Link>

      <Link href={"/dashboard/tab7"}>
        <div
          className={`flex pl-4 pr-4 gap-2 text-sm ${
            isCollapsed ? "justify-center" : "justify-start"
          } items-center rounded-lg py-2 ${
            pathname == "/dashboard/settings"
              ? "bg-green-600 text-zinc-950"
              : "hover:bg-zinc-800"
          }`}
        >
          <AiTwotoneSetting size={22} />
          <h1
            className={`text-sm font-semibold ml-1 ${
              isCollapsed ? "hidden" : "visible"
            }`}
          >
            Tab 7
          </h1>
        </div>
      </Link>
    </div>
  );
}
```

### Describe the Bug

```react-apexcharts & react-table``` make next/link navigation slow, when I removed all the codes of react-apexcharts & react-table form the pages and added simple div tag with a text, the next/link navigation worked very fast. also removed the "use client"

I figured out it is showing 5-10 second delay sometimes it does not load the page, and when click back the URL is changing but the content are not re-rendering. and when I tried to remove the ```react-apexcharts & react-table``` code it worked as expected. I don't know, is this a bug of Next/link ?

and I am sure I have implemented it properly because when I hover over the Link wrapped div I see the URL in the left-bottom.  the reason might be chart and table making the code heavy and render takes time in client side.

My code:

Layout:

```
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className= 'bg-black'>
        <div className="flex flex-row relative overflow-hidden">

          <div className="sticky top-0 left-0 bottom-0">
            <SidebarProvider>
              <SideNavigation />
            </SidebarProvider>
          </div>

          <div className="flex-1 bg-white overflow-scroll m-2 overflow-x-hidden rounded-xl h-[97.8vh]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
```

Sidebar Link tag:
```
      <Link href={"/dashboard/analytics"}>
        <div
          className={`flex pl-4 pr-4 gap-2 text-sm ${
            isCollapsed ? "justify-center" : "justify-start"
          } items-center rounded-lg py-2 ${
            pathname == "/testboard/analytics"
              ? "bg-green-600 text-zinc-950"
              : "hover:bg-zinc-800"
          }`}
        >
          <IoMdAnalytics size={22} />
          <h1
            className={`text-sm font-semibold ml-1 ${
              isCollapsed ? "hidden" : "visible"
            }`}
          >
            Analytics
          </h1>
        </div>
      </Link>
```

Analytics page:

```
"use client";

import dynamic from "next/dynamic";

const Chart = dynamic(() => import("react-apexcharts"), { ssr: false });

import { StackedBarOptions } from "@/graph-style/StackedBarOptions";
import { LineBarOptions } from "@/graph-style/LineBarOptions";
import { Horizontal100Options } from "@/graph-style/Horizontal100Options";
import FinanceDetailsCard from "@/components/FinanceDetailsCard";
import CompactViewCard from "@/components/CompactViewCard";
import CommonHeader from "@/components/CommonHeader";

export default function Analytics() {
  const data = [
    {
      name: "Previous week",
      data: [44, 55, 41, 67, 22, 43],
    },
    {
      name: "This week",
      data: [13, 23, 20, 8, 13, 27],
    },
  ];

  const tree = [
    {
      data: [
        {
          x: "New Delhi",
          y: 218,
        },
        {
          x: "Kolkata",
          y: 149,
        },
        {
          x: "Mumbai",
          y: 184,
        },
        {
          x: "Ahmedabad",
          y: 55,
        },
        {
          x: "Bangaluru",
          y: 84,
        },
        {
          x: "Pune",
          y: 31,
        },
        {
          x: "Chennai",
          y: 70,
        },
        {
          x: "Jaipur",
          y: 30,
        },
        {
          x: "Surat",
          y: 44,
        },
        {
          x: "Hyderabad",
          y: 68,
        },
        {
          x: "Lucknow",
          y: 28,
        },
        {
          x: "Indore",
          y: 19,
        },
        {
          x: "Kanpur",
          y: 29,
        },
      ],
    },
  ];

  return (
    <>
      <CommonHeader heading={"Analytics"} />

      <div className="flex h-[300px] text-black justify-center  items-center px-2 pt-2 gap-4">
        <div className="grid grid-cols-2 h-full w-[35%] gap-4">
          <CompactViewCard
            heading="Customers"
            amount="3,781"
            growth="+5.27%"
            status="rise"
            bgColor="bg-emerald-400"
          />
          <CompactViewCard
            heading="Order"
            amount="3,219"
            growth="+1.78%"
            status="rise"
            bgColor="bg-red-700"
          />
          <CompactViewCard
            heading="Revenue"
            amount="$695"
            growth="-0.56%"
            status="fall"
            bgColor="bg-sky-400"
          />
          <CompactViewCard
            heading="Growth"
            amount="30.1%"
            growth="+1.48%"
            status="rise"
            bgColor="bg-purple-800"
          />
        </div>
        <div className="flex justify-center items-center w-[65%] h-full bg-zinc-100 rounded-2xl">

      
          <Chart
            // @ts-ignore:next-line
            options={StackedBarOptions}
            series={data}
            type="bar"
            width={800}
            height={250}
          />
   



        </div>
      </div>

      <div className="flex h-[34%] text-black justify-center items-center p-2 gap-4">
        <div className="flex justify-center items-center w-[75%] h-full bg-zinc-100 rounded-2xl">
          <Chart
            // @ts-ignore:next-line
            options={LineBarOptions}
            series={data}
            type="line"
            width={900}
            height={200}
          />
        </div>
        <div className="w-[25%] h-full bg-zinc-100 rounded-2xl flex justify-center items-center">
          <Chart
            options={Horizontal100Options}
            series={tree}
            type="treemap"
            width={300}
            height={200}
          />
        </div>
      </div>

      <div className=" flex h-[20%] gap-3 px-2 pb-2">
        <FinanceDetailsCard
          heading="International Merchant Account"
          net_earning="$6840"
          change="80%"
          fees="$1240"
          message="Last 30 day earnings calculated. Apart from arranging the order of topics."
        />

        <FinanceDetailsCard
          heading="International Merchant Account"
          net_earning="$6840"
          change="80%"
          fees="$1240"
          message="Last 30 day earnings calculated. Apart from arranging the order of topics."
        />

        <FinanceDetailsCard
          heading="International Merchant Account"
          net_earning="$6840"
          change="80%"
          fees="$1240"
          message="Last 30 day earnings calculated. Apart from arranging the order of topics."
        />
      </div>
    </>
  );
}
```

### Expected Behavior

I was expecting smooth delay free navigation.

### Which browser are you using? (if relevant)

Google Chrome Version 115.0.5790.110 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

npm run dev

**Comment by mareksuscak** [comment] 2023-09-09 02:56
I think we're currently experiencing this outside of Vercel, in standalone mode where Next is deployed in a Docker container running on Cloud Run (in CPU always allocated configuration with minimum number of instances set to 1 so cold starts should be minimal). There's got to be something else that's causing this - either the number of dependencies or getInitialProps in the custom Document? Could that be the culprit. We are pulling some data but navigating between pages takes 2-4s when clicking a Next Link whereas reloading the page directly takes a lot less time (~1s). We tried the latest Canary release (13.4.20) to no avail. We use Pages Router, not the App Router. This app uses CSS-in-JS (via Emotion) and Mantine UI (+[SSR](https://mantine.dev/guides/ssr/)). We use Next Auth for authentication. This is a fairly complex and robust app and I don't think I'd be able to provide a minimum reproducible example but I can provide a Trace from Chrome and a screenshot that shows `Next.js-render` phase taking over 5s.

![CleanShot 2023-09-09 at 04 55 43](https://github.com/vercel/next.js/assets/613647/c243cce6-1642-4ec5-9167-91c63d231986)

[Trace-20230909T045419.json.zip](https://github.com/vercel/next.js/files/12564454/Trace-20230909T045419.json.zip)

**Comment by monolithed** [comment] 2023-09-11 07:00
[mareksuscak](https://github.com/mareksuscak), I have a similar issue where [my page](https://pergum.com) is mostly static, and the initial load takes 2-5 seconds. I can't reproduce it locally; it only occurs on the Vercel server.

**Comment by mareksuscak** [comment] 2023-09-11 10:07
We just figured it out - we were using mobx v6 and mobx-react-lite v4 w/ Server-Side State Hydration on the client that's based on [the official example](https://github.com/vercel/next.js/tree/canary/examples/with-mobx). We determined a difference in behavior between v3 and v4 of mobx-react-lite where the latter causes this siginificant performance issue when hydrating the server-side state on the client. A workaround was to downgrade to v3. The mobx team doesn't seem to be aware of this issue so we'll be reporting this. My recommendation to you @monolithed would be to profile your app and check for things in the critical rendering path (custom document, custom app, pages) that might be causing a similar performance issue.

**Comment by balazsorban44** [comment] 2024-02-27 21:02
I'm going to close this for now. Investigating slow cases is different from codebase to codebase, so we _really_ need a reproduction to be able to effectively find the root cause. If you are having this issue, we ask you to open a new bug report with a provided code example, and any trace information you might have. Thanks!

(Feel free to reach out to me with private examples/repros if that's a blocker)

**Closed by balazsorban44** 2024-02-27 21:02 UTC
Labels: please add a complete reproduction, template: bug, area: Routing, type: needs triage
