### ISSUE TITLE
next build: .env.production gets loaded even if .env.local is present

### ISSUE THREAD

**Issue by vvo** [vercel/next.js#22940] opened 2021-03-10 12:30 UTC
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Not relevant

### What operating system are you using?

macOS

### How are you deploying your application?

yarn dev

### Describe the Bug

When using `yarn build`, Next.js reads env variables from `.env.local` AND `.env.production`.

### Expected Behavior

I expect `.env.production` to only be used if `.env.local` is not present.

### To Reproduce

```sh
create-next-app
```

.env.production
```txt
TEST=production
DANGEROUS_VALUE=true
```

.env.local
```txt
TEST=local
```

next.config.js
```js
module.exports = function(config) {
  console.log(process.env.DANGEROUS_VALUE);
  return config;
}
```

```sh
> yarn build
yarn run v1.22.4
$ next build
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Loaded env from /Users/vvo/Dev/test-nextjs-env-production/.env.local
Loaded env from /Users/vvo/Dev/test-nextjs-env-production/.env.production
yes # < dangerous value
```

Hi there, I find it not obvious that `.env.production` gets loaded by yarn build even if .env.local is present.

1. This is not the case of `next dev`
2. I am using `next build` as part of my `yarn test` command and this triggered some weird errors because we only activate SENTRY in the production.

I always felt very cautious about not trying to merge values from "local" and "production" envs. But rather enforce every env variable to be set. Less error-prone, more obvious.

What if someone applies database migrations in `next build` and those get applied to the production environment because they removed DATABASE_URL from their .env by mistake?

What do you think?

**Comment by mercteil** [comment] 2021-03-10 13:42
since 10.0.8

```javascript
const {
  URL,
  API_URL,
} = publicRuntimeConfig;

console.log(URL); //undefined
console.log(API_URL); // undefined

**Comment by kachar** [comment] 2021-03-11 08:31
@vvo As I see you're doing an assignment when logging the value and this will always log `true`

```diff
-console.log(process.env.DANGEROUS_VALUE=true);
+console.log(process.env.DANGEROUS_VALUE===true);
```

![image](https://user-images.githubusercontent.com/893608/110758154-d954a900-8254-11eb-90d4-68d0e8a9b879.png)

**Comment by vvo** [comment] 2021-03-11 08:56
@kachar you're right, I just updated my comment, the issue remains the same (production env variables read even if .env.local is present)

**Comment by mattcarlotta** [comment] 2021-03-19 16:03
It's loading `.env` files as [intended](https://github.com/vercel/next.js/blob/canary/packages/next-env/index.ts#L80-L90).

The following files take presidence by their order:
1.) .env.{mode}.local (`.env.development.local`/`.env.production.local`/`.env.test.local`)
2.) .env.local (if present, loaded regardless of mode except not in a `test` environment)
3.) .env.{mode} (`.env.development`/`.env.production`/`.env.test`)
4.) .env (if present, loaded regardless of mode)

Next loads their Envs variables according to the above hierarchy, where parsed Envs will only be assigned to **undefined variables** in `process.env`. All parsed Envs variables are compared against any defined/predefined Envs in `process.env`. If an Env variable has already been assigned to `process.env`, then the variable is ignored. Therefore, you should either be using `env.mode.local` to prevent `.env.local` Env variables from being assigned OR you shouldn't be using `env.local` for Env variables that aren't shared across multiple environments as they take presidence over Env variables in `.env.{mode}`.

**Comment by ijjk** [comment] 2021-04-17 17:27
As mentioned in https://github.com/vercel/next.js/issues/22940#issuecomment-802939917 this is the expected behavior and is documented here https://nextjs.org/docs/basic-features/environment-variables#default-environment-variables. 

I'm going to close this since this doesn't appear to be a bug and is documented already.

**Closed by ijjk** 2021-04-17 17:27 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
