### ISSUE TITLE
Middleware: nextUrl.protocol is always https

### ISSUE THREAD

**Issue by mismosmi** [vercel/next.js#31014] opened 2021-11-05 09:42 UTC
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

17.0.1

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

When running the dev server of nextjs 12
In custom middleware at `pages/_middleware.ts`, `req.nextUrl.protocol` is 'https:' even though I'm on `http://localhost:3000`.

Same goes for `req.nextUrl.href` and `req.nextUrl.origin`.

### Expected Behavior

The protocol should match the request protocol (or be undefined if unavailable)

### To Reproduce

```ts
// pages/_middleware.ts
import { NextRequest } from 'next/server'

export default function middleware(req: NextRequest) {
  console.log(req.nextUrl.protocol)
}
```

**Comment by mismosmi** [comment] 2021-11-05 09:44
Sorry if there's a good reason for this that I don't know about...

**Comment by hi-ogawa** [comment] 2021-11-06 03:57
I can't see the reason yet, but I suspect these lines are the cause of the issue:

https://github.com/vercel/next.js/blob/d2c1888a257b4a5390a11bf1850eb10434ce967f/packages/next/server/web/adapter.ts#L9-L16

In some simple cases I tried with `next dev`, `params.request.url` seems to be always a path, i.e. starts with `/`.

**Comment by javivelasco** [comment] 2022-06-21 14:29
Duplicate of https://github.com/vercel/next.js/issues/36334

**Closed by javivelasco** 2022-06-21 14:29 UTC
Labels: template: bug, area: Middleware
