### ISSUE TITLE
Unable to turn off automatic compilation

### ISSUE THREAD

**Issue by DavidHayek** [vercel/next.js#10918] opened 2020-03-10 03:54 UTC
# Bug report

## Describe the bug

Code under the /pages directory is recompiled every 60 seconds regardless of whether the file has changed. This is causing error issues with re-initialization of a database connection pool. Moreover, once the error occurs the server will not stop with the normal CTRL-C signal. I did not see any documentation on how to configure this behavior or turn it off.

## To Reproduce

I created a basic next project following the tutorials online. The file which keeps getting recompiled is /pages/api/graphql.ts

## Expected behavior

I would expect that only a changed file would be re-compiled.

## Screenshots

![image](https://user-images.githubusercontent.com/62001679/76278147-de090a80-6258-11ea-8fb1-be22a11f70c4.png)

## System information

- OS: Linux Ubuntu 18.04.3 VM running on Oracle's VirtualBox
- Browser NA
- Version of Next.js: "latest", which at the time of writing is 9.3.

**Comment by timneutkens** [comment] 2020-03-10 09:33
Please add a complete reproduction so that we can investigate.

**Comment by vvo** [comment] 2020-04-10 21:54
Related maybe: https://github.com/zeit/next.js/issues/7811#issuecomment-612234565

**Comment by Timer** [comment] 2020-09-03 02:31
Closing as no reproduction provided.

**Closed by Timer** 2020-09-03 02:31 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
