### ISSUE TITLE
Invalid hook when upgrading from 9.4.4 to 9.5.0

### ISSUE THREAD

**Issue by mateuspv** [vercel/next.js#16657] opened 2020-08-28 17:52 UTC
# Bug report
Looking for any advices about how to solve this.

## Describe the bug

Invalid hook call error when upgrading from 9.4.4 to 9.5.0(or even 9.5.2):

> Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app 

**1.** Mismatching React / React-DOM: No, both are using `16.13.1`
**2.** Breaking hook rules: No, I've remove all my custom `pages` `public` `_app.tsx` and `_document.tsx` files and created a simple hello-world page and yet received the error.
**3.** More than one copy of react: No `npm ls react` returns only ``-- react@16.13.1`

## To Reproduce

Should I provide a docker container?

## Screenshots
<img width="1143" alt="Invalid hook call" src="https://user-images.githubusercontent.com/4995440/91599062-0f2ae380-e93c-11ea-9a8c-37815384c4cd.png">

## System information

- OS: macOS, Docker linux
- Version of Next.js: [e.g. 9.5.0]
- Version of Node.js: [e.g. 12.18.3]

## Additional context
Package:
```json
{
  "license": "UNLICENSED",
  "private": true,
  "dependencies": {
    "@babel/core": "7.11.4",
    "@babel/preset-env": "7.11.0",
    "clsx": "1.1.1",
    "country-list": "2.2.0",
    "dinero.js": "1.8.1",
    "formik": "2.1.5",
    "i18next": "19.7.0",
    "immer": "7.0.8",
    "lodash": "4.17.20",
    "nanoid": "3.1.12",
    "next": "9.5.2",
    "next-cookies": "2.0.3",
    "next-i18next": "6.0.2",
    "normalize.css": "8.0.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-phone-number-input": "3.0.25",
    "react-transition-group": "4.4.1",
    "reselect": "4.0.0",
    "sass": "1.26.10",
    "stent": "8.0.4",
    "typescript": "4.0.2",
    "universal-cookie": "4.0.3",
    "yup": "0.29.3"
  },
  "devDependencies": {
    "@svgr/webpack": "5.4.0",
    "@types/node": "14.6.1",
    "@types/react": "16.9.48",
    "@typescript-eslint/eslint-plugin": "3.10.1",
    "@typescript-eslint/parser": "3.10.1",
    "eslint": "7.7.0",
    "eslint-plugin-react": "7.20.6",
    "eslint-plugin-react-hooks": "4.1.0",
    "jest": "26.4.2",
    "prettier": "2.1.1",
    "ts-jest": "26.3.0"
  },
  "browser": {},
  "browserslist": [
    "> 1%",
    "last 3 versions",
    "Firefox ESR",
    "Safari >= 10",
    "iOS >= 10"
  ],
  "esm": {
    "mode": "all"
  },
  "scripts": {
    "dev": "next dev"
  }
}
```

**Comment by mateuspv** [comment] 2020-08-28 17:57
Possible related:
#16535 
#10162

**Comment by Timer** [comment] 2020-08-30 01:49
Duplicate of #9022

**Closed by Timer** 2020-08-30 01:49 UTC

**Comment by illarionvk** [comment] 2020-09-01 15:45
Related pull-request https://github.com/vercel/next.js/pull/16369

**Comment by illarionvk** [comment] 2020-09-10 10:28
This issue can occur if the `node_modules` folder itself is symlinked to another location; see #16988

**Comment by carlosalv098** [comment] 2021-04-23 19:49
i had the same issue and this worked for me:

npx next dev -p 4000

you will have to open in your browser: 
localhost:4000

hope it helps

**Comment by balazsorban44** [comment] 2022-01-28 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
