### ISSUE TITLE
Custom Rewrites Breaks in Production mode

### ISSUE THREAD

**Issue by simmbiote** [vercel/next.js#25097] opened 2021-05-13 13:04 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

12.13.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

With custom rewrites in next.config.js, the application breaks when hitting /api/ routes in Production mode.

### Expected Behavior

The application should not break on /api routes.
A break that occurs in production mode should have occurred in development mode.

### To Reproduce

1. Add a custom rewrite to next.config.js:
```
const rewrites = async () => [
  {
    source: "/:path*",
    has: [
      {
        type: "host",
        value: "(?<host>.*)",
      },
    ],
    destination: "/:path*?host=:host",
  },
];
```
(`rewrites ` is then used in config...)

2. During development mode, running is fine.
3. Build the application.
4. Start the application and hit any route except home.

An error as follows is experienced:

> TypeError: Cannot read property '__nextLocale' of undefined
>     at Router.execute (C:\....\node_modules\next\dist\next-server\server\router.js:19:712)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async Server.run (C:\....\node_modules\next\dist\next-server\server\next-server.js:69:1042)
>     at async Server.handleRequest (C:\....\node_modules\next\dist\next-server\server\next-server.js:34:504)

**Comment by danielsimao** [comment] 2021-05-14 14:41
Hey @simmbiote, I opened an issue with a similar behaviour but when on purpose open the page with 2 slashes ("//"), to see if it would go to error page.

https://github.com/vercel/next.js/issues/23772

Checkout the codesandboxes

**Comment by ijjk** [comment] 2021-09-19 16:42
Hi, I'm gonna close this as this appears to be working correctly in the latest version of Next.js `v11.1.2` please update and give it a try!

**Closed by ijjk** 2021-09-19 16:42 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
