### ISSUE TITLE
Unintentional page query overriding when using getServerSideProps

### ISSUE THREAD

**Issue by PepijnSenders** [vercel/next.js#21641] opened 2021-01-28 21:42 UTC
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

15

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

next start

**Describe the Bug**

When using `getServerSideProps` and a dynamic page name, the name of the dynamic page unintentionally (I think), becomes a reserved keyword as you can't use the same for a query string value anymore. This can cause some unexpected bugs like marketing adding a query string that has the same name as the page, and this query string value not being available in the `next/router`.

**Expected Behavior**

The dynamic page name value not being in `router.query` and the query string value still being available.

**To Reproduce**

Create a page with name `[page].js`:

```js
import { useRouter } from 'next/router';

const Page = () => {
  console.log(useRouter());
  return <h1>Hello world</h1>
};

export const getServerSideProps = () => {
  return {
    props: {},
  };
};

export default Page;
```

Request the page with [`localhost:3000/inthequery?page=notinthequery`](localhost:3000/inthequery?page=notinthequery).

<img width="421" alt="Screen Shot 2021-01-28 at 4 42 29 PM" src="https://user-images.githubusercontent.com/2052659/106202378-d364a600-6187-11eb-831b-b4e8bbabd691.png">

**Comment by ijjk** [comment] 2021-01-28 22:48
Hi, this is the expected behavior and is intended to prevent users from accidentally or purposefully overriding the dynamic route param names, e.g. in the above case you showed you would no longer have access to the dynamic route param `page` since you want the query to override it. To prevent the above from accidentally happening, less common dynamic route params can be used. 

I'm going to close this since this is the expected behavior.

**Closed by ijjk** 2021-01-28 22:48 UTC
Labels: template: bug

**Comment by PepijnSenders** [comment] 2021-01-28 23:30
Maybe I don't understand, but why is the `[page]` in the query object anyways? Is that something that needs to be like this by design? Like if we separate `.query` for `?query=test` query strings and dynamic page names?

**Comment by balazsorban44** [comment] 2022-01-28 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
