### ISSUE TITLE
ambiguous Error During compile whole app 

### ISSUE THREAD

**Issue by pooooriya** [vercel/next.js#30683] opened 2021-10-31 07:49 UTC
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

14.0.0

### What browser are you using?

microsoft edge

### What operating system are you using?

windows 11

### How are you deploying your application?

next dev

### Describe the Bug

after compile my page it shows an error that said:
wait  - compiling...
thread '<unnamed>' panicked at 'not implemented: regenerator: complex pattern in catch clause', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\swc_ecma_transforms_compat-0.47.1\src\es2015\regenerator\case.rs:1232:30
error - ./pages/auth/index.tsx
Error: failed to process not implemented: regenerator: complex pattern in catch clause

maybe its cause by SWC but it so ambiquous and nothing help me to figure out what exactly caused this error !

### Expected Behavior

compiled my code without error because on next 11 we don't have this error

### To Reproduce

![image](https://user-images.githubusercontent.com/65160744/139573510-ec62576c-2b6f-41eb-bf6c-8fe469e42b78.png)

**Comment by pooooriya** [comment] 2021-10-31 08:43
I Downgrade To 11.1.2 , Everything Now Works Fine! :/

**Comment by Sridatta19** [comment] 2021-10-31 09:33
I'm facing this same issue in my Nextjs typescript project

**Comment by timneutkens** [comment] 2021-10-31 12:16
@pooooriya @Sridatta19 please provide the input files so that we can investigate this

**Comment by petrbela** [comment] 2021-10-31 14:44
@timneutkens In my case, the catch clause looks like this:

```js
        catch ({ message }) {
            return handleGetUserMediaError(message);
        }
```

Changing it to

```js
        catch (e) {
            return handleGetUserMediaError(e.message);
        }
```

fixed the problem, so it looks like swc doesn't know how to parse a deconstructor in a catch?

**Comment by pooooriya** [comment] 2021-10-31 15:07
```
   const handleSubmit = useMutation(async () => {
        try {
            const res = await gate.register({ username: phoneNumber });
            setstep((prev) => prev + 1);
            toast.success(res.message);
        } catch ({ data: { errors } }) {
            showErrorMessage(errors);
        }
    });

```
I face the same issue with this line of code 
I figure when I use just error property an then get error.data its work fine but when destructure it, Swc can't destructure  when use trycatch block.

any wrong implemention in SWC config for nextjs ? or we have to create new issue in Swc repo ?

**Comment by pooooriya** [comment] 2021-10-31 15:21
by this thread , I think Swc cant handle this !! 
https://github.phala.one/swc-project/swc/issues/2413
is this need to update documentation maybe its worst for some projects and maybe they have to handle all those catch blockes and maybe they ignore to update to next 12 !!

**Comment by timneutkens** [comment] 2021-10-31 15:23
Thanks! We'll have a look and fix it 👍

**Comment by matthewwolfe** [comment] 2021-10-31 17:18
@timneutkens FYI that link that @pooooriya posted is a fake github...

**Comment by Sridatta19** [comment] 2021-10-31 17:34
I too got the issue due to destructuring in catch block parameters

**Comment by timneutkens** [comment] 2021-10-31 20:45
> @timneutkens FYI that link that @pooooriya posted is a fake github...

I've changed the link, thanks for checking 👍

**Comment by kdy1** [comment] 2021-11-03 03:36
It's an issue of the order of passes and it's now fixed on upstream by https://github.com/swc-project/swc/pull/2629

**Comment by pooooriya** [comment] 2021-11-03 08:25
Good News! Thanks, Man

**Closed** 2021-11-03 08:31 UTC
Labels: kind: bug, area: SWC transforms

**Comment by balazsorban44** [comment] 2022-01-27 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
