### ISSUE TITLE
Error: Route did not complete loading: /projects

### ISSUE THREAD

**Issue by DevDaksh** [vercel/next.js#21543] opened 2021-01-26 12:57 UTC
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

14.15.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows 10

**How are you deploying your application?**

Vercel

**Describe the Bug**

I am trying to build a simple route for my portfolio. The route is '/projects'. I've added a projects.js file in the pages directory with the logical code and when I use next/link for client side transition, I get an error: Route did not complete loading: "projects".
When I use regular anchor tag for routing, there is no issue.

**Expected Behavior**

It should change the route to the destined page without any error.

**To Reproduce**

```
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Footer() {
    return (
        <>
            <div className={styles.link}>
                <a href="https://github.com/devdaksh" target="__blank">github</a>
                <a href="https://twitter.com/dawksh" target="__blank">twitter</a>
                <a href="https://devdaksh.hashnode.dev" target="__blank">blogs</a>
                <a href="mailto:akshd@outlook.com">email</a>
                <Link href="/projects" >
                    <a>projects</a>
                </Link>
            </div>
        </>
    )
}
```

![Screenshot (130)](https://user-images.githubusercontent.com/20741933/105847787-1433b200-6004-11eb-9331-62681d1a4865.png)

This is a screenshot of the error

**Comment by donpark** [comment] 2021-01-28 16:33
Seeing the same on macOS with:

- development build
- production build
- on page with `<Link>` tag
- on page routed to via `<Link>` tag.
 
Same `10.0.5` version of Next.js running on Node 14.15.4.

**Comment by mikkelramlov** [comment] 2021-01-28 20:12
Same error here. +1

**Comment by retr00exe** [comment] 2021-01-29 10:17
I'm facing the same error too on my project. The official [next.js](https://nextjs.org/) website also has this issue if you open chrome developer tools and click one of its routes a couple of times.

**Comment by GaddMaster** [comment] 2021-01-29 17:22
I am also getting this error. I am not far off the official tutorials. I am pretty sure I was getting it while following the site basic tutorial.

**Comment by bpas247** [comment] 2021-02-04 01:57
This error seems to be originated from [here](https://github.com/vercel/next.js/blob/575fcf3fcf09c277a8d33df7dd5395cda6f18fde/packages/next/client/route-loader.ts#L301-L309), which was added in #19006 (and was released in [v10.0.2](https://github.com/vercel/next.js/releases/tag/v10.0.2)).

I'm not entirely sure if this code itself is what's causing the error to be thrown, I would assume not since we would have noticed it earlier on, so something else seems to be causing the `idleTimeout` promise to be resolved _earlier_ than the `onBuildManifest` promise being resolved.

**Comment by dbo** [comment] 2021-02-10 10:24
IMO this is not a real issue, but rather annoying if you've enabled `Pause on exceptions` in devtools. The Promise.race correctly resolves the route loading, the timeout promise is just dangling after and devtools stops on it.

**Comment by GaddMaster** [comment] 2021-02-10 10:25
Yep, pause on exception triggers it

**Comment by donpark** [comment] 2021-02-10 14:22
Chrome has a similar ['ghost' exception bug with `FileSystemWritableFileStream`](https://bugs.chromium.org/p/chromium/issues/detail?id=1132506) when `close` (sometimes `write`) is called that also goes away when "Pause on exceptions" is enabled.

I'd treat this as a real bug because:
1. It's not a corner case.
2. It's a fixable bug AFAIK.
3. Developers among users of apps built using Next.js may see it and report it as a bug which multiplies unnecessary waste of resources.

My advice is to make `idletTimeout` cancellable and have the good path cancel timeout when it finishes first. It's a common enough pattern and cancellable Promise is not expected to arrive for a while so I think it's worth investing some time on.

**Comment by dbo** [comment] 2021-02-10 15:50
I agree, you could look at it as a dev issue, even though it does not have impact on production sites, and I totally agree about (3), unnecessary issue noise.

**Comment by timkindberg** [comment] 2021-02-24 16:54
We are experiencing this issue in our automated tests, it's failing our suite. I was able to reproduce this error without having "pause on exception" turned on.

**Comment by DevDaksh** [comment] 2021-02-25 10:26
same @timkindberg

**Comment by florianmartens** [comment] 2021-02-25 18:24
Same here. I'm seeing the same issue on next@10.0.2

**Closed** 2021-03-05 16:32 UTC
Labels: kind: bug

**Comment by CAIOHOBORGHI** [comment] 2021-05-06 17:34
I'm also seeing this error on next@10.0.2

**Comment by SheikYerbouty** [comment] 2021-05-20 13:21
The exception is annoying and wastes developer's time. It would be lovely to have it fixed, rather than having to ignore it. Here is next@10.2.2

**Comment by josemasrijf** [comment] 2021-07-15 06:50
Having this same issue next@10.0.3

**Comment by timneutkens** [comment] 2021-07-16 19:17
Please open a new issue with a complete reproduction and we'll have a look!

**Comment by balazsorban44** [comment] 2022-01-28 02:16
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
