### ISSUE TITLE
New release broke dynamic API routes

### ISSUE THREAD

**Issue by VladimirMikulic** [vercel/next.js#28093] opened 2021-08-14 00:36 UTC
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

14.0.0

### What browser are you using?

Chrome, Safari, Firefox

### What operating system are you using?

Android, IOS, macOS, Windows, Linux

### How are you deploying your application?

Vercel

### Describe the Bug

With the recent upgrade from `11.0.1` to `11.1.0`, dynamic API routes no longer work. (they just return 404 page)
For example:
`/api/newsletter` - works
`/api/posts/[id].ts` - doesn't work

The important thing to note here is that they all work locally, but when deployed to Vercel, dynamic routes keep returning 404.

### Expected Behavior

I would expect dynamic API routes to work.

### To Reproduce

Feel free to create the folder structure from above and push it to Vercel.
Once again, everything will work locally, but dynamic routes will stop working once deployed on Vercel.

**Comment by ijjk** [comment] 2021-08-14 00:59
Hi, this should be corrected now, please re-deploy your application and give it a try!

**Comment by ijjk** [comment] 2021-08-16 15:09
Closing as this should be resolved after re-deploy per above comment

**Closed by ijjk** 2021-08-16 15:09 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
