### ISSUE TITLE
Build error occurred - cannot find module for page: /_error

### ISSUE THREAD

**Issue by fouad** [vercel/next.js#21882] opened 2021-02-05 01:59 UTC
**What version of Next.js are you using?**

10.0.6

**What version of Node.js are you using?**

v12.18.4

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

Vercel

**Describe the Bug**

After upgrading from (`9.2.x` to `10.0.6`) when building (`yarn build`) there is an unexpected error:

```
$ cross-env NODE_ENV=production next build
info  - Using external babel configuration from /Users/fouad/dev/src/my-app/.babelrc.js
info  - Creating an optimized production build
info  - Compiled successfully

> Build error occurred
Error: Cannot find module for page: /_error
    at pageNotFoundError (/Users/fouad/dev/src/my-app/node_modules/next/dist/next-server/server/require.js:1:384)
    at getPagePath (/Users/fouad/dev/src/my-app/node_modules/next/dist/next-server/server/require.js:1:917)
    at /Users/fouad/dev/src/my-app/node_modules/next/dist/build/index.js:15:2847
    at /Users/fouad/dev/src/my-app/node_modules/next/dist/build/tracer.js:1:1447
    at NoopTracer.withSpan (/Users/fouad/dev/src/my-app/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:47:16)
    at ProxyTracer.withSpan (/Users/fouad/dev/src/my-app/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:34)
    at traceAsyncFn (/Users/fouad/dev/src/my-app/node_modules/next/dist/build/tracer.js:1:1406)
    at /Users/fouad/dev/src/my-app/node_modules/next/dist/build/index.js:15:2698
    at /Users/fouad/dev/src/my-app/node_modules/next/dist/build/tracer.js:1:1447
    at NoopTracer.withSpan (/Users/fouad/dev/src/my-app/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:47:16)
    at ProxyTracer.withSpan (/Users/fouad/dev/src/my-app/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:34)
    at traceAsyncFn (/Users/fouad/dev/src/my-app/node_modules/next/dist/build/tracer.js:1:1406)
    at /Users/fouad/dev/src/my-app/node_modules/next/dist/build/index.js:15:2176
    at async /Users/fouad/dev/src/my-app/node_modules/next/dist/build/tracer.js:1:1441 {
  code: 'ENOENT'
}
```

This issue persists when nearly everything is deleted from `pages/_error.js` and becomes:

```
import Error from 'next/error'
export default Error
```

The same error from above persists. When the page is deleted entirely, the error continues on a different page:

```
$ rm pages/_error.js 
$ cross-env NODE_ENV=production next build
info  - Using external babel configuration from /Users/fouad/dev/src/my-app/.babelrc.js
info  - Creating an optimized production build
info  - Compiled successfully

> Build error occurred
Error: Cannot find module for page: /about
    at pageNotFoundError (/Users/fouad/dev/src/my-app/node_modules/next/dist/next-server/server/require.js:1:384)
    at getPagePath (/Users/fouad/dev/src/my-app/node_modules/next/dist/next-server/server/require.js:1:917)
    at /Users/fouad/dev/src/my-app/node_modules/next/dist/build/index.js:15:3428
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/fouad/dev/src/my-app/node_modules/next/dist/build/tracer.js:1:1441
    at async Promise.all (index 2)
    at async /Users/fouad/dev/src/my-app/node_modules/next/dist/build/index.js:15:2910
    at async /Users/fouad/dev/src/my-app/node_modules/next/dist/build/tracer.js:1:1441
    at async /Users/fouad/dev/src/my-app/node_modules/next/dist/build/index.js:15:2147
    at async /Users/fouad/dev/src/my-app/node_modules/next/dist/build/tracer.js:1:1441 {
  code: 'ENOENT'
}
```

**Expected Behavior**

In development (`next dev`) I went to most pages (including error) and it all seems to work fine.

**To Reproduce**

Unfortunately this is a private repository, but happy to answer more questions and share non-sensitive details

**next.config.js**

```js
const {
  PHASE_DEVELOPMENT_SERVER,
  PHASE_PRODUCTION_BUILD,
  PHASE_EXPORT
} = require('next/constants')
const webpack = require('webpack')

module.exports = phase => {
  let isNow = process.env.IS_NOW
  let target = isNow ? 'serverless' : ''

  const config = {
    target,

    env: { VERCEL_URL: process.env.VERCEL_URL || '' },

    // Allow mdx and md files to be pages
    pageExtensions: ['ts', 'jsx', 'js', 'mdx', 'md'],

    distDir:
      !isNow && (phase === PHASE_PRODUCTION_BUILD || phase === PHASE_EXPORT)
        ? '.next-export'
        : '.next',

    outDir: phase === PHASE_EXPORT ? 'dist-export' : 'dist',

    assetPrefix: '',

    webpack: (config, options) => {
      if (!options.isServer) {
        config.resolve.alias['@sentry/node'] = '@sentry/browser'
      }

      config.plugins.push(
        new webpack.EnvironmentPlugin({
          VERCEL_URL: process.env.VERCEL_URL || ''
        })
      )

      return { ...config, node: { fs: 'empty' } }
    }
  }

  // This makes sure we only require build-time plugins at build time
  if (phase !== PHASE_DEVELOPMENT_SERVER && phase !== PHASE_PRODUCTION_BUILD) {
    return config
  }

  const withMDX = require('@next/mdx')({
    extension: /\.(md|mdx)?$/
  })

  config.node = { fs: 'empty' }

  return withMDX(config)
}
```

**pages/_error.js**

```jsx
import Head from 'next/head'
import { Footer } from '../components/layout/footer'

export function getInitialProps({ res, err }) {
  const statusCode = res ? res.statusCode : err ? err.statusCode : 404
  return { statusCode }
}

function ErrorPage({ statusCode }) {
  let errorMessage = `This page isn't available`

  return (
    <div>
      <Head title="Uh oh!">
        <meta name="viewport" content="initial-scale=1, viewport-fit=cover" />
      </Head>
      <pre>{errorMessage}</pre>
      <Footer />
    </div>
  )
}

export default ErrorPage
```

**Comment by sohhamm** [comment] 2021-05-20 14:17
Facing the same issue in AWS Elastic Beanstalk

**Comment by ijjk** [comment] 2021-09-23 04:23
Hi, I'm not able to reproduce this with the above information in the latest version of Next.js `v11.1.2` so I'm gonna close this, if you are still having issues with this after updating please respond with additional info and we can investigate further!

**Closed by ijjk** 2021-09-23 04:23 UTC
Labels: template: bug

**Comment by yaguchi109** [comment] 2021-10-01 08:21
I have a similar problem. Wake up once every few times.
```
...
info  - Generating static pages (1429/1429)

> Build error occurred
Error: Cannot find module for page: /404
    at pageNotFoundError (.../node_modules/next/dist/server/require.js:15:17)
    at Object.getPagePath (.../node_modules/next/dist/server/require.js:38:15)
    at .../node_modules/next/dist/build/index.js:840:56
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (.../node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async .../node_modules/next/dist/build/index.js:707:13
    at async Span.traceAsyncFn (.../node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async Object.build [as default] (.../node_modules/next/dist/build/index.js:77:25) {
  code: 'ENOENT'
}
info  - Finalizing page optimization
```

node v16.10.0
next 11.1.2

**Comment by balazsorban44** [comment] 2022-01-27 16:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
