### ISSUE TITLE
Basepath not working with public folder

### ISSUE THREAD

**Issue by onopko81** [vercel/next.js#20097] opened 2020-12-11 15:07 UTC
# Bug report

Basepath not working with public folder

## Describe the bug

Basepath not working with public folder, the project go to production in a subfolder: igtown.

 basePath: '/igtown'

if set basepath in next.config.js and export in prod, the images in public folder go to 404.
link and file js working finally.

 

## System information

- Version of Next.js: 10.0.3
- Version of Node.js: [e.g. 12.0.0]
- Deployment: next export

**Comment by thiagocavaloti** [comment] 2020-12-15 00:53
@onopko81 also for me. If basePath on next config is set like '/path', public folder does not work. It looks like stay on '/images/' and not '/path/images/'  :(

**Comment by onopko81** [comment] 2020-12-15 12:27
@thiagocavaloti it's a problem for me. @timneutkens how resolve it?

**Comment by ddazal** [comment] 2020-12-15 17:30
Hi @onopko81. I also found this issue, like, yesterday. To solve it I required the config file into `_app.js` and add a base tag with a trailing slash
```js
// pages/_app.js
const config = require('../next.config')

function App({ Component, pageProps }) {
    return (
      <>
        <Head>
          <base href={config.basePath + '/'} />
        </Head>
        <Component {...pageProps} />
      </>
    )
}
```
I could then reference my static files **without a leading slash** `<img src="images/pic.jpg" />` instead of `<img src="/images/pic.jpg" />`. As a disclaimer, I'm using this approach with a really simple app so I don't know if it is the best solution. Anyway, hope it helps.

**Comment by thiagocavaloti** [comment] 2020-12-15 21:19
> @thiagocavaloti it's a problem for me. @timneutkens how resolve it?

it is also form me :(

**Comment by realw5** [comment] 2020-12-16 12:24
Me too, only when deploying to Vercel with 10.0.4-canary versions and running Webpack 5.10
```
21:46:13.075 | > Build error occurred
-- | --
21:46:13.076 | Error: > webpack config.resolve.alias was incorrectly overridden. https://err.sh/vercel/next.js/invalid-resolve-alias

```

**Comment by onopko81** [comment] 2020-12-21 15:06
hi, a solution is a global variable PATH, for images and assets in public folder

**Comment by timneutkens** [comment] 2020-12-22 12:43
Note that this issue is not actionable until you add a reproduction.

**Comment by Damex989** [comment] 2020-12-30 18:47
@timneutkens Here is a reproduction demo for the error that is happening when adding **basePath** config.

### NextJS Configuration
``` javascript
module.exports = {
  basePath: '/auth',
  async redirects() {
    return [
      {
        source: '/auth',
        destination: '/auth/signin',
        permanent: true,
        basePath: false
      }
    ]
  }
}
```
### Static Files
It also happens if the image is in the root of public folder

```bash
├── public
│   ├── images
│   │   ├── signup_cover.jpg
│   ├── favicon.ico
├── pages
├── node_modules
```
### Calling next/Image
```jsx
import Image from 'next/image'

<Image
  className='absolute inset-0 h-full w-full object-cover'
  layout='fill'
  src='/images/signup_cover.jpg'
  alt=''
/>
```
### Error 404 not Found
![Captura de Pantalla 2020-12-30 a la(s) 12 37 55](https://user-images.githubusercontent.com/17620479/103374075-3a654100-4a9c-11eb-986e-d2473594c5d7.png)
![Captura de Pantalla 2020-12-30 a la(s) 12 38 11](https://user-images.githubusercontent.com/17620479/103374077-3c2f0480-4a9c-11eb-99c0-b6d4fed1204c.png)

**Comment by Timer** [comment] 2020-12-30 19:11
This has been fixed on `next@canary`. Note, you must provide the `/auth` prefix for the `src` passed to the `<Image />` component.

**Closed by Timer** 2020-12-30 19:11 UTC
Labels: kind: bug

**Comment by vidjul** [comment] 2021-01-03 13:19
Hello,
Dunno if I'm doing it wrong but I've moved to `next@canary` and `<Image />` does work on dev server but when I try to deploy it, it still cannot be fetched. What am I missing?

**Comment by jfrantzius** [comment] 2021-08-18 14:46
Hi @Timer , both @vidjul and me still see the issue in production mode. I'm seeing it with Next.js 11.0.1 , while vidjul saw it with some canary build after the alleged fix.

Maybe this issue should be reopened?

**Comment by itsthekeming** [comment] 2021-08-21 02:28
Just to add a use case to this issue:

I am hosting a statically exported Next.js site on GitHub pages on a project page. I'm able to access the site via `basePath`, but my images that use a source from the `public` directory are not found when I run the build site.

In the meantime, I will add the string I used for `basePath` to my image source URLs.

**Comment by m-sterspace** [comment] 2021-09-22 20:38
Hey for the record, you solve this by accessing the basePath through the router in your code.

```jsx
export function useBasePath(){
  const { basePath } = useRouter();
  return basePath;
}

export function Img({
    src, 
    children,
    ...rest
}) {
    const basePath = useBasePath();
    const finalSrc = basePath?.charAt(0) === "/" ? basePath + src : src;
    return (
        <img
            src={finalSrc}
            {...rest}
        >
            {children}
        </img>
    )
}
```

**Comment by balazsorban44** [comment] 2022-01-27 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
