### ISSUE TITLE
webpack5 non-existent type export

### ISSUE THREAD

**Issue by gajus** [vercel/next.js#31218] opened 2021-11-09 18:00 UTC
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

16.11.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

N/A

### Describe the Bug

TypeScript error:

```
node_modules/next/dist/server/config-shared.d.ts:1:15 - error TS2724: '"next/dist/compiled/webpack/webpack"' has no exported member named 'webpack5'. Did you mean 'webpack'?

1 import type { webpack5 } from 'next/dist/compiled/webpack/webpack';
```

### Expected Behavior

No TypeScript error.

### To Reproduce

Use `tsc` with `{"skipLibCheck": false}`.

**Comment by ijjk** [comment] 2021-11-09 18:25
Closing as a duplicate of https://github.com/vercel/next.js/issues/30167

**Closed by ijjk** 2021-11-09 18:25 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
