### ISSUE TITLE
strange error message when build fails in a non-writable directory

### ISSUE THREAD

**Issue by jokester** [vercel/next.js#15218] opened 2020-07-16 10:26 UTC
# Bug report

## Describe the bug

When I attempt to build app in a non-writable directory (run `next build` as non-root user, on source files owned by `root`), the build fails with the following strange error message:

```text
./src/app.scss
Global CSS cannot be imported from files other than your Custom <App>. Please move all global CSS imports to pages/_app.js.
Read more: https://err.sh/next.js/css-global
Location: pages/_app.tsx
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. find a pc with `docker`
2. clone `https://github.com/jokester/typescript-boilerplate`, checkout `reproduce-nextjs-strange-error` branch and cd into `web-nextjs`
3. run `docker build .`

The build error itself can be fixed like:

```diff
diff --git a/web-nextjs/Dockerfile b/web-nextjs/Dockerfile
index c5efe7..e3899f 100644
--- a/web-nextjs/Dockerfile
+++ b/web-nextjs/Dockerfile
@@ -5,7 +5,7 @@ RUN adduser --shell /bin/bash app-worker \
     && chown -v app-worker:app-worker /app

 USER app-worker
-COPY . /app/
+COPY --chown=app-worker:app-worker . /app/
 WORKDIR /app/
 RUN whoami && id && find $PWD && ls -alh /app/ && yarn && yarn build && yarn --production && rm -rf ~/.cache
 CMD yarn start
```

## Expected behavior

To fail with better a description of the real error, or to build successfully.

**Comment by zzzze** [comment] 2020-09-27 06:08
I have zhe same problem. It's due to `next` don't admit your `pages/_app.tsx` as custom app file.
The souce reuse [isWriteable](https://github.com/vercel/next.js/blob/a4c97c5c4adb66d733f617ce200535a968e12ba5/packages/next/server/lib/find-page-file.ts#L34) to determine whether `pages/_app.js` exists.
I think it is really a bug, or error message is not clearable.
@jokester

**Comment by zzzze** [comment] 2020-09-27 06:18
@jokester to reproduce the problem, don't need to use `docker`, just run zhe command below.
`chmod -w pages/_app.js`

**Comment by JanKaifer** [comment] 2022-11-24 13:53
Looks like this was fixed with https://github.com/vercel/next.js/issues/22806

**Closed by JanKaifer** 2022-11-24 13:53 UTC
