### ISSUE TITLE
`fetchNextData` error handling fails with TypeError: Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by pjaws** [vercel/next.js#11608] opened 2020-04-02 18:21 UTC
# Bug report

## Describe the bug

I woke up this morning to find that some of our site's CTA links (using 'next/link') were broken in mobile browsers, displaying "An unexpected error has occurred" to the user. The only thing I could find in Rollbar was this error: `TypeError: Attempted to assign to readonly property.`.

Testing locally with iOS Simulator, I traced it to this line in `.next/static/development/pages/_app.js`:
```
      err.code = 'PAGE_LOAD_ERROR';
```

Here is the full function where the error is occurring:
```
function fetchNextData(pathname, query, isServerRender, cb) {
  var attempts = isServerRender ? 3 : 1;

  function getResponse() {
    return fetch(utils_1.formatWithValidation({
      // @ts-ignore __NEXT_DATA__
      pathname: "/_next/data/".concat(__NEXT_DATA__.buildId).concat(pathname, ".json"),
      query: query
    }), {
      // Cookies are required to be present for Next.js' SSG "Preview Mode".
      // Cookies may also be required for `getServerSideProps`.
      //
      // > `fetch` won’t send cookies, unless you set the credentials init
      // > option.
      // https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
      //
      // > For maximum browser compatibility when it comes to sending &
      // > receiving cookies, always supply the `credentials: 'same-origin'`
      // > option instead of relying on the default.
      // https://github.com/github/fetch#caveats
      credentials: 'same-origin'
    }).then(function (res) {
      if (!res.ok) {
        if (--attempts > 0 && res.status >= 500) {
          return getResponse();
        }

        throw new Error("Failed to load static props");
      }

      return res.json();
    });
  }

  return getResponse().then(function (data) {
    return cb ? cb(data) : data;
  })["catch"](function (err) {
    // We should only trigger a server-side transition if this was caused
    // on a client-side transition. Otherwise, we'd get into an infinite
    // loop.
    if (!isServerRender) {
      err.code = 'PAGE_LOAD_ERROR';
    }

    throw err;
  });
}
```

The page I am attempting to transition to is using `getServerSideProps` to check the user's a/b test cookie and redirect them based on the result:

```
export const getServerSideProps = async (ctx) => {
  const expVariantId = getOrSetGoCookie(ctx);

  if (expVariantId === '1') {
    const { res, query } = ctx;

    res
      .writeHead(307, {
        Location: `${process.env.HI_BASE_URL}/signup?${queryString.stringify(query)}`,
      })
      .end();

    return { props: {} };
  }

  return { props: { expVariantId } };
};
```

This issue never occurs when navigating to the page directly or using a standard anchor tag - _only_ when using 'next/link'.

Here is the link for reference:
```
            <Link href="/start" as={`${process.env.HI_BASE_URL}/start`} passHref>
              <Button as="a" variant="green" width={1} mt={6} data-testid="GetStartedA">
                Get Started
              </Button>
            </Link>
```

## To Reproduce

Obviously, this is a sort of complicated example, and I'm not exactly sure what's causing the initial error. Let me know if you need more information, and I can try to create an example repo when I'm able to.

## Expected behavior

It would seem there are 2 issues here. One is that an error is occurring during when clicking a `next/link` to a page using `getServerSideProps` to redirect. The other is that during the handling of this error, another error is thrown when attempting to set the value of `err.code`.

I would expect to get information about what the error is, if it's something caused by my code, but we never make it that far.

## System information

- OS: iOS
- Browser: Safari (reported on Chrome too)
- Version of Next.js: 9.3.3

## Additional context

Thank you! Again, happy to provide any more detail necessary.

**Comment by marco-koenen** [comment] 2020-05-01 10:16
Have you been able to correct this bug yet? I have encountered the same error and have not yet been able to correct it.

**Comment by pjaws** [comment] 2020-05-01 18:40
I actually switched to `getInitialProps` for other reasons, but the solution for the error that was causing this error was to stop using 'next/link'/client-side routing. I have had so many issues with those links - especially on mobile devices. "An unexpected error has occurred", links just plain doing nothing when you click them, etc.

**Comment by saleebm** [comment] 2020-05-09 16:07
Same problem here, ended up using the normal html anchor instead of the Link from 'next/link' and no problem. 

I received the same error as above, PAGE_LOAD_ERROR. Redirect on getServerSideProps did not redirect, initial error showed up as "attempt to assign to readonly type... native code"

**Comment by marco-koenen** [comment] 2020-05-09 17:17
Oh, I forgot to answer that. I have solved the problem in the meantime - I have executed Next in a different folder. (`/frontend` instead of `/src`) By switching back, it also worked in production mode.

**Comment by saleebm** [comment] 2020-05-27 15:40
I can confirm that this is no longer an issue with the latest canary, 9.4.3-canary.1

Thank you!

**Comment by revolunet** [comment] 2020-06-17 15:57
Having the same fatal error on Safari/Edge with next@9.4.4 when:

 - trying to click a `next/link` that has `href="/projects"` 
 - that `/projects` returns a non JSON value so that the `res.json()` in `getResponse` fails (a 302 in my case)

this ultimately triggers  the `catch` where `error.code` is rewritten which seems not allowed in Edge/Safari

**Comment by revolunet** [comment] 2020-06-18 21:20
Ok so for me this was related to this issue : https://github.com/vercel/next.js/issues/12409

**Closed** 2020-08-10 17:15 UTC
Labels: kind: bug, point: 2, priority: p0

**Comment by Timer** [comment] 2020-08-10 17:55
This was fixed in `next@^9.5.2-canary.15` and newer. Please upgrade and let us know if it works for you!

**Comment by luismramirezr** [comment] 2020-09-04 11:26
I had this problem in `next@9.5.1`. It works with `next@9.5.3`. Thanks!

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
