### ISSUE TITLE
`next/image` fails in local dev mode with node@16

### ISSUE THREAD

**Issue by nico-bachner** [vercel/next.js#24565] opened 2021-04-28 17:07 UTC
### What version of Next.js are you using?

10.1.3 & 10.2.0

### What version of Node.js are you using?

16.0.0

### What browser are you using?

Safari - not sure if that's relevant though

### What operating system are you using?

macOS

### How are you deploying your application?

next dev (via pnpm)

### Describe the Bug

When navigating to a page containing an `<Image>` component, the dev server crashes and the image doesn't load. 
Error message: Job 1, 'pnpm dev' terminated by signal SIGSEGV (Address boundary error)

Additional info: this seems to be an issue with node@16 since there is no issue in production (node@14)

### Expected Behavior

The behaviour should match that of the `next/image` component using previous node versions (<=v15)
Which is to say that the image component should not crash the dev server

### To Reproduce

On macOS:

1. Install node@16:
    ```sh
    brew install node
    ```
2. Go to a project using the `next/image` component
3. Start the dev server (`next dev`)
4. Navigate to the image

**Comment by angusryer** [comment] 2021-04-29 00:14
I just downgraded `node` to `15.12.0`, followed the exact steps as written in the similar bug report #24564, and I am no longer getting the Seg Fault error when using the `<Image>` tag.  😅

**Comment by nico-bachner** [comment] 2021-04-29 07:19
Yeah that makes sense - I had problems with `next/image` in next.js v10.0.x, but 10.1 solved those issues. It's only when upgrading node to v16 that the issue resurfaced.

**Comment by nico-bachner** [comment] 2021-04-29 07:20
Also worth noting that the issues seem slightly different from each other. The current issue causes the dev server to crash immediately, whereas if I remember correctly the previous issue only caused the server to become unreliable and potentially crash.

**Comment by DavidChouinard** [comment] 2021-05-23 04:55
Similar issue: https://github.com/vercel/vercel/issues/6243

**Comment by timneutkens** [comment] 2021-05-24 09:37
Duplicate of #24421, provided a workaround there as well so please have a look there 👍

**Closed by timneutkens** 2021-05-24 09:37 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
