### ISSUE TITLE
Error's doesnt use my custom error page

### ISSUE THREAD

**Issue by maraisr** [vercel/next.js#15143] opened 2020-07-14 03:34 UTC
# Bug report

## To Reproduce

1. Clone https://github.com/maraisr/nextjs-repro-repo/tree/error-repro
2. run `yarn`
3. run `yarn build`
4. run `yarn start`
5. inspect in devtools

## Expected behavior

Expect to see http 404, as well as my custom error page

## Screenshots

![image](https://user-images.githubusercontent.com/599459/87380820-a202ff00-c5d6-11ea-9003-bfbfa2451856.png)

expect to see this component: 
![image](https://user-images.githubusercontent.com/599459/87380840-acbd9400-c5d6-11ea-83c5-e765e4debbf3.png)

## System information

- OS: Windows
- Browser: Firefox
- Version of Next: 9.4.4
- Version of Node.js: 14.0.0

## Additional context

Please make sure you clone the `error-repro` branch of that repro.

Followed: https://nextjs.org/docs/advanced-features/custom-error-page#customizing-the-error-page

**Comment by jamesmosier** [comment] 2020-07-14 14:14
Hi @maraisr. The `pages/_error.js` won't display your 404 page, only `pages/404.js` will. 

> **500 page**
> By default Next.js provides a 500 error page that matches the default 404 page’s style. This page is not statically optimized as it allows server-side errors to be reported. This is why 404 and 500 (other errors) are separated.

https://nextjs.org/docs/advanced-features/custom-error-page#customizing-the-404-page

**Comment by timneutkens** [comment] 2020-07-14 15:34
https://github.com/maraisr/nextjs-repro-repo/blob/error-repro/pages/index.js#L2

`next/error` is the default error component from Next.js as documented here: https://nextjs.org/docs/advanced-features/custom-error-page#reusing-the-built-in-error-page so this doesn't sound like a bug.

**Comment by Timer** [comment] 2020-07-14 16:58
Closing this per comment above from @timneutkens

**Closed by Timer** 2020-07-14 16:58 UTC

**Comment by balazsorban44** [comment] 2022-01-29 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
