### ISSUE TITLE
React 18RC Upgrade not working

### ISSUE THREAD

**Issue by adesugbaa** [vercel/next.js#32587] opened 2021-12-16 20:16 UTC
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

17.2.0

### What browser are you using?

Chrome

### What operating system are you using?

MacOS Monterey

### How are you deploying your application?

Vercel

### Describe the Bug

I have an existing application (in production), and wanted to try out the React18 features.

When I upgrade the rear versions using:

`yarn add react@rc react-dom@rc`

The application refuses to compile/start:
```sh
yarn dev                      
yarn run v1.22.17
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /Users/ayorinde/Dev/Git/Others/jtv.nextjs/.env.local
info  - Using the createRoot API for React
warn  - You are using an unsupported prerelease of 'react-dom' which may cause unexpected or broken application behavior. Continue at your own risk.
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/ayorinde/Dev/Git/Others/jtv.nextjs/node_modules/react/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.mod._resolveFilename (/Users/ayorinde/Dev/Git/Others/jtv.nextjs/node_modules/next/dist/build/webpack/require-hook.js:171:28)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at getPackagePath (/Users/ayorinde/Dev/Git/Others/jtv.nextjs/node_modules/next/dist/build/webpack-config.js:601:41)
    at Object.getBaseWebpackConfig [as default] (/Users/ayorinde/Dev/Git/Others/jtv.nextjs/node_modules/next/dist/build/webpack-config.js:617:9) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

How do we opt in to React18, and try out the new features?

### Expected Behavior

I expect the application to compile, and start accepting/responding to requests.

### To Reproduce

Create a next application, and upgrade to React18 following [this link](https://nextjs.org/docs/advanced-features/react-18)

**Comment by chuvikovd** [comment] 2021-12-18 11:20
Experienced same issue. However, works fine with node@16.

**Comment by balazsorban44** [comment] 2021-12-18 12:08
This seems to be coming from `react` itself.

PR already merged https://github.com/facebook/react/pull/22783, probably released soon.
Another potentially relevant PR: https://github.com/facebook/react/pull/22954

**Closed by balazsorban44** 2021-12-18 12:08 UTC
Labels: kind: bug

**Comment by balazsorban44** [comment] 2022-01-27 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
