### ISSUE TITLE
Failed to load SWC binary,

### ISSUE THREAD

**Issue by abhishekpandeykr** [vercel/next.js#30706] opened 2021-10-31 18:04 UTC
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

14.17.3

### What browser are you using?

Chro,e

### What operating system are you using?

Windows

### How are you deploying your application?

N/A

### Describe the Bug

I created a new Project using **npx create-next-app**, when i created  this Project it was running perfectly, but when i installed the **sass**, it has started throwing this error  _Failed to load SWC binary, see more info here: https://nextjs.org/docs/messages/failed-loading-swc_.

I have made these changes to the next.config file

```module.exports = {
  reactStrictMode: true,
  sassOptions:{
    includePaths:[path.join(__dirname,"styles")]
    }
  }
```

the console output

```
 next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - Failed to load SWC binary, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

It suppose to run the application instead it is showing error.

### To Reproduce

1. Install the sass via command `npm i sass`
2.  configure the next.config.js with following configuration
```
module.exports = {
  reactStrictMode: true,
  sassOptions:{
    includePaths:[path.join(__dirname,"styles")]
  }
}
```

**Comment by mlnima** [comment] 2021-11-01 13:06
I have the same error, just updated from 12.0.1 to 12.0.2, and the app crashed

**Comment by ahsankhan201010** [comment] 2021-11-02 08:17
facing the same issue with next@12.0.2

**Comment by timneutkens** [comment] 2021-11-02 08:25
Duplicate of #30713

**Closed by timneutkens** 2021-11-02 08:25 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
