### ISSUE TITLE
App Router does not work in docker container

### ISSUE THREAD

**Issue by dmpx** [vercel/next.js#54659] opened 2023-08-28 08:46 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Thu May 25 07:17:40 UTC 2023
    Binaries:
      Node: 17.3.0
      npm: 8.3.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: standalone
```

### Which example does this report relate to?

with-docker

### What browser are you using? (if relevant)

116.0.5845.111

### How are you deploying your application? (if relevant)

Docker version 24.0.5

### Describe the Bug

 App Router

```
'use client'
import React from 'react'

function Test() {
  const [open, setOpen] = React.useState(false)

  const handleOPen = () => {
    setOpen(open => !open)
  }

  return (
    <>
      <button onClick={handleOPen}>Button</button>
      {open ? 'block' : 'none'}
    </>
  )
}

export default Test
```

Invalid onclick

### Expected Behavior

toggle block / none

### To Reproduce

https://github.com/dmpx/nextjs-with-docker.git

**Comment by balazsorban44** [comment] 2023-08-29 11:25
Sounds like a duplicate of https://github.com/vercel/next.js/issues/54328, could you upgrade the Node.js version to see if that helps?

**Closed** 2023-08-30 13:50 UTC
Labels: area: examples

**Comment by ygqygq2** [comment] 2023-08-30 13:56
The same issue. I have mapped the port, which is accessible inside the container but not on the host.

**Comment by ygqygq2** [comment] 2023-08-31 01:40
> The same issue. I have mapped the port, which is accessible inside the container but not on the host.

#54342
 HOSTNAME env need to be set.
