### ISSUE TITLE
Safari on Mac Focus Issue

### ISSUE THREAD

**Issue by geometricpanda** [vercel/next.js#26921] opened 2021-07-04 20:58 UTC
### What example does this report relate to?

next.js

### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.15.1

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When using Safari on Mac, pressing the Tab Key doesn't focus on interactive elements within the page.
When focussing on an interactive element using the mouse, :active state is being list.

This is also happening on iPad with a keyboard connected in Safari, Chrome and Firefox.

https://youtu.be/N0rdqkIlUtI

### Expected Behavior

When tagging to an interactive element, focus is moved

https://youtu.be/cyUMVSvQCqQ

### To Reproduce

Create next app using `yarn create next-app --typescript`.
Once created, CD into the folder and run `yarn dev`.
(also available at https://next-js-minimal-indol.vercel.app)

Open the app in Safari, and attempt to tab into the page.
Tab focus never moves out of the toolbar.

This also causes accessibility issues when using Voiceover

**Comment by geometricpanda** [comment] 2021-07-04 21:18
Oh the code repo is here, but it's a standard next app.

https://github.com/geometricpanda/next-js-minimal

**Comment by timneutkens** [comment] 2021-07-05 15:12
Both videos are not available as they're private. I just had a look at this and it seems to be a bug (or maybe expected) in Safari, you can try opening https://google.com and you won't be able to `tab` to links like `gmail` and `images`. Only `input` can be focused on.

Update:
Just did a search on Google for `safari tab focus not working` and found this: https://stackoverflow.com/questions/8747689/safari-tabbing-focus-doesnt-work-in-5-1-2. Looks like `option + tab` is the way to select any element and `tab` only selects inputs. Interesting choice by Apple.

I'll close this issue as it's not related to Next.js.

**Closed by timneutkens** 2021-07-05 15:12 UTC
Labels: template: bug, type: example

**Comment by balazsorban44** [comment] 2022-01-28 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
