### ISSUE TITLE
Not found on direct navigation to routes with non-latin characters

### ISSUE THREAD

**Issue by tacomanator** [vercel/next.js#16060] opened 2020-08-11 01:06 UTC
# Bug report

## Describe the bug

It's possible to create a <Link> to a url with non-latin characters:

        <Link as="/fruit/バナナ" href="/fruit/[type]">バナナ</Link>

It works and the page loads as expected. However, directly navigating to the same link (e.g. refresh page) results in 404.

## To Reproduce

https://github.com/tacomanator/nextjsissue-nonlatinurl

1. Clone https://github.com/tacomanator/nextjsissue-nonlatinurl
2. npm run dev
3. Click on バナナ or 桃
4. (Notice page loads fine)
5. Now refresh browser
6. Receive 404

## Expected behavior

Should be able to directly navigate to the URL.

## Screenshots

![Screen Recording 2020-08-11 at 9 56 30 AM](https://user-images.githubusercontent.com/63794/89845456-7bc28600-dbb9-11ea-9b35-c2414bad923f.gif)

## System information

- OS: macOS
- Version of Next.js: 9.5.2
- Version of Node.js: v14.7.0

## Additional context

The same behavior happens on non-dynamic links as well.

**Comment by stefanprobst** [comment] 2020-08-13 09:52
hi, i checked out your repo, two observations:
- it seems to break in development, but the production build is ok (i.e. `yarn build && yarn start`). can you confirm?
- adding `encodeURI` to `getStaticPaths` makes dev mode work as well - i think this should either be documented [here](https://nextjs.org/docs/basic-features/data-fetching#the-paths-key-required), or handled by `getStaticPaths` automatically

**Comment by tacomanator** [comment] 2020-10-01 06:14
@stefanprobst sorry for the late reply.

- Confirmed, works on production build
- Confirmed, adding `encodeURI` to `getStaticPaths` fixes dev. However, it seems to me that as a goal, dev should behave as closely as possible to build. Unless there is a good reason not to, automatically handling encoding in `getStaticPaths` seems like a prudent thing to do. What do you think?

**Comment by stefanprobst** [comment] 2020-10-01 07:09
>     automatically handling encoding in `getStaticPaths` seems like a prudent thing to do. What do you think?

totally agree!

**Comment by balazsorban44** [comment] 2022-01-19 11:51
Hi, this should have been fixed in later releases of Next.js (tested with 10, but as of writing 12 is stable now, so I recommend upgrading to that), as I am not able to reproduce it anymore.

**Closed by balazsorban44** 2022-01-19 11:51 UTC
