### ISSUE TITLE
[NEXT-1181] DynamicServerError: Dynamic server usage: cookies

### ISSUE THREAD

**Issue by focux** [vercel/next.js#49373] opened 2023-05-06 17:06 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.2
      npm: 9.3.0
      Yarn: 1.22.19
      pnpm: 7.25.1
    Relevant packages:
      next: 13.4.1
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/focux/next-cookies-bug

### To Reproduce

1. Clone the repository
2. Run `npm run build`

### Describe the Bug

After upgrading to Next from `13.3.5` to `13.4.1`, I'm getting a lot of errors that say:
```
- info Creating an optimized production build ..node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

DynamicServerError: Dynamic server usage: cookies
    at staticGenerationBailout (/Users/[redacted]/Projects/[redacted]/apps/web-app/.next/server/chunks/3311.js:46379:21)
    at cookies (/Users/[redacted]/Projects/[redacted]/apps/web-app/.next/server/chunks/6647.js:172:62)
    at getAccessToken (/Users/[redacted]/Projects/[redacted]/apps/web-app/.next/server/chunks/9041.js:30473:40)
    at /Users/[redacted]/Projects/[redacted]/apps/web-app/.next/server/chunks/9041.js:30505:55
    at /Users/[redacted]/Projects/[redacted]/apps/web-app/.next/server/chunks/6647.js:2598:44 {
  digest: 'DYNAMIC_SERVER_USAGE'
}
```

The app works good when running it on development mode.

### Expected Behavior

According to the docs, using the `cookies` function automatically opt-ins my pages to dynamic rendering.

So I would expect the build to succeed as before and also those errors to be clearer to at least know in what page is originating.

<sub>[NEXT-1181](https://linear.app/vercel/issue/NEXT-1181/dynamicservererror-dynamic-server-usage-cookies)</sub>

**Comment by sinclairnick** [comment] 2023-05-19 05:06
Am getting this issue too. @timneutkens do you have any guidance on workarounds prior to this being fixed? I couldn't find docs about how to use the `export const dynamic` stuff, which I imagine may help here.

**Comment by naseef0** [comment] 2023-05-25 07:43
I have a similar issue [https://github.com/vercel/next.js/discussions/50271](https://github.com/vercel/next.js/discussions/50271)

**Comment by Ismet1999** [comment] 2023-05-27 15:28
I solved this problem simply by adding this line to the app/layout.tsx file
`export const dynamic = 'force-dynamic'`

**Comment by naseef0** [comment] 2023-05-29 02:24
> I solved this problem simply by adding this line to the app/layout.tsx file `export const dynamic = 'force-dynamic'`

Is that the correct way?

**Comment by weilueluo** [comment] 2023-06-01 21:35
any update?

**Comment by Jordaneisenburger** [comment] 2023-06-05 12:01
Running into the same issue, `export const dynamic = 'force-dynamic'` does "fix" the issue but it's not an ideal solution I think. Also seems like https://github.com/vercel/next.js/issues/49066 and https://github.com/vercel/next.js/issues/50634 and are related

**Comment by martin-coded** [comment] 2023-06-12 19:43
I had a similar problem with `draftMode()` and as a quick workaround I just added a try catch block to make sure that I can access the cookies. With this I can still generate the pages with `generateStaticParams`

```tsx
function isDraftModeTrue(): boolean {
  try {
    const {isEnabled} = draftMode()
    return isEnabled;
  } catch (error) {
    return false;
  }
}
```

```tsx
const isDraftMode: boolean = isDraftModeTrue();
if(isDraftMode){
 // fetch some data and set header with jummy cookie data
}
```

I think you could do the same only for cookies.

```tsx
function isCookieAvailable(): boolean {
  try {
    const cookieStore = cookies();
    return true;
  } catch (error) {
    return false;
  }
}
```

I just started with next.js. I know it doesn't make sense to access cookies when the pages are getting pre-generated, but I also didnt't figure out a better way to solve this.

**Comment by SamKomesarook** [comment] 2023-06-13 19:38
The `export const dynamic = 'force-dynamic` line worked for me when placed in my `layout.tsx` file, but when I navigate to a different page using the `useRouter` hook, I get the following err:

`Error: Dynamic server usage: force-dynamic`

**Comment by muhaimincs** [comment] 2023-06-14 03:59
any work around?

**Comment by ariesclark** [comment] 2023-06-22 05:16
The same happens for other "dynamic" opt-in functions like ``searchParams`` and ``headers``.
Maybe rename this issue to reflect as such?

**Comment by brocchirodrigo** [comment] 2023-06-24 03:59
This solution temporarily fixed the issue, but we need to remove after bug fix.
I'm also waiting for the fix.

I also noticed that the dynamicParams to False is also in trouble. This reflects the "fallback" used in ISR.

**Comment by danger-ahead** [comment] 2023-06-28 03:48
Facing this app router next 13.4.5: in route.ts

**Comment by DanielhCarranza** [comment] 2023-06-28 06:50
I solved it by adding `export const revalidate = 0;` to the `layout.tsx`

**Comment by filipkowal** [comment] 2023-06-28 09:20
@DanielhCarranza wouldn't it opt the layout out of the static generation?
If so, there's no point in using generateStaticParams there in the first place if I am not mistaken.

**Comment by nick4fake** [comment] 2023-07-02 16:43
````typescript
export const dynamic = 'force-dynamic';
export const revalidate = 0;
````

This helps with dev server on initial load, but any change to any file immediately shows this:
````
Unhandled Runtime Error
Error: Dynamic server usage: force-dynamic
````

**Comment by BenLyddane** [comment] 2023-07-04 16:08
Everywhere I was passing cookies on a server component was giving me this issue. It was mainly on the Supabase getSession() funciton that used createServerComponentClient() function. To fix, I added 'use server' to the getSession() function and was able to clear the issue.

**Comment by Jordaneisenburger** [comment] 2023-07-04 17:46
> Everywhere I was passing cookies on a server component was giving me this issue. It was mainly on the Supabase getSession() funciton that used createServerComponentClient() function. To fix, I added 'use server' to the getSession() function and was able to clear the issue.

Thanks you sir that indeed does fix the issue for me as well.

**Comment by danya0365** [comment] 2023-07-08 02:01
I face this issue when suddenly add 'use client' in my page file in app directory

for example

app/dashboard/page.tsx

```
'use client';

import Main from './main';

export default () => {
  return (
    <div className="flex items-center mx-auto min-h-screen justify-center">
      <div className="flex flex-col items-center justify-center w-full h-full">
        <Main />
      </div>
    </div>
  );
};
```

this will show error 

you must removed 'use client' in page.tsx

then add 'use client' in <Main /> component instead

**Comment by jrobsontull** [comment] 2023-07-13 14:55
Does anyone have an update on this issue? Is this expected behaviour of Next.js or something we can hope to change in the future?

Currently facing the same issue with Supabase when it consumes `cookies` from `next/header` in a server component.

**Comment by jrobsontull** [comment] 2023-07-13 21:07
> Some extra info for others who have the same issue, I had to add `export const dynamic = 'force-dynamic'` to **every** page or layout that uses cookies / createServerComponentClient. The issue is also not 100% consistent for me, sometimes the build passes fine even without the `force-dynamic` which made this so hard to find.

Ideally though we would want to cache where we can and `force-dynamic` would [prevent this,](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic) correct? Hopefully there will be a way to do this in future with caching!

**Comment by verheyenkoen** [comment] 2023-07-14 06:44
> I had to add `export const dynamic = 'force-dynamic'` to **every** page or layout that uses cookies / createServerComponentClient.

In my case, the whole site is backend with Clerk-auth (which server method `currentUser()` uses cookies obviously) so every page (and the middleware) is doing that. Does the `app dir` setup not allow to set `force-dynamic` on the site level (in `next.config.js`)?

Also, as I understand it correctly, this is just a warning from Next.js build tools (like eg. when you are using experimental API's). So I don't really understand why this is throwing errors. In my case I don't see the errors in build output as they are caught by Sentry.

**Comment by mertafor** [comment] 2023-07-15 06:56
In case it helps someone, my problem with using cookies was about using generateStaticParams in layout.tsx. Using generateStaticParams prevents accessing cookies and headers since it generates paths at build time rather than runtime. Once I removed it, I was able to access cookies without any problem. Also note that revalidate and force-dynamic will be ignored if generateStaticParams defined.

**Comment by wontondon** [comment] 2023-07-16 20:29
In my case, using the latest NextJS (13.4.9) and `@supabase/auth-helpers-nextjs@0.7.3` my issue was related to the using supabase server component client on page routes that were not dynamic (i.e. /home, /settings instead of /task/[taskId]). 

I thought including `import { cookies } from 'next/headers';` on a `page.tsx` automagically opted into dynamic rendering it seems like during the next build process if the route isn't dynamic it may be trying to render it statically. 🤷 

I was able to workaround it by finding the pages that used the the supabase server component client and added a force-dynamic.
```
export const dynamic = 'force-dynamic';
```

In my case I wanted them to always be dynamic, so it worked well.

**Comment by AbhishekAglave** [comment] 2023-07-18 15:03
My problem is solved by using this line in every API Route.js `export const dynamic = "force-dynamic";
` 
Ex.

**Comment by edgarasben** [comment] 2023-07-18 17:29
For statically pre-rendered pages I used, e.g.:

```tsx
export const dynamic = 'force-static'
export const revalidate = 60
```

**Comment by jrobsontull** [comment] 2023-07-18 18:15
> For statically pre-rendered pages I used, e.g.:
> 
> ```tsx
> export const dynamic = 'force-static'
> export const revalidate = 60
> ```
> 
> But this feels like a temporary solution. I don't want to put "force-static" to every ISR page.

A nice solution to this might be to have these automatically set as default options for pages that consume dynamic functions like `cookies`.

**Comment by Zazell** [comment] 2023-07-19 11:54
I was facing the same issue, but i eventually found out that the error only showed when the 'dynamic' page (in my case, because i am using the cookies) was rendered through the router (using the Link component from next-intl). When i simply replaced the Link with a normal "a" tag, the error message not longer shows.

**Comment by tatwater** [comment] 2023-07-19 19:37
I'm facing the same issue, but none of the above solutions seem to be resolving it for me.

`next@13.4.10` and `@supabase/auth-helpers-nextjs@0.7.3`

`npm run build` fails with `Error: Call rentries were exceeded` after printing the following error 17 times:

```
DynamicServerError: Dynamic server usage: cookies
--
at staticGenerationBailout (/vercel/path0/.next/server/chunks/399.js:81:21)
at Object.cookies (/vercel/path0/.next/server/chunks/763.js:16966:62)
at NextServerComponentAuthStorageAdapter.getCookie (/vercel/path0/.next/server/chunks/763.js:203:42)
at NextServerComponentAuthStorageAdapter.getItem (/vercel/path0/.next/server/chunks/763.js:572:28)
at getItemAsync (/vercel/path0/.next/server/chunks/763.js:3720:33)
at SupabaseAuthClient.__loadSession (/vercel/path0/.next/server/chunks/763.js:2098:71)
at async /vercel/path0/.next/server/chunks/763.js:2069:36
at async Object.__stack_guard___useSession__ (/vercel/path0/.next/server/chunks/763.js:3939:32)
at async stackGuard (/vercel/path0/.next/server/chunks/763.js:3941:12)
at async /vercel/path0/.next/server/chunks/763.js:2067:24 {
digest: 'DYNAMIC_SERVER_USAGE'
```

I have one server layout calling `createServerComponentClient<Database>({ cookies })` as well as two server-rendered pages and one server-rendered component. The layout is shared by three more pages, and the component is on every page.

Every file that imports cookies from `next/headers` has been given `export const dynamic = 'force-dynamic';` but without success.

**Comment by jrobsontull** [comment] 2023-07-19 20:32
@tatwater As far as I remember with my errors, it didn't tell me which page was erroring during build. Is this correct on your end as well?

If so, would be great if Next.js told us what page was failing during build for `DynamicServerError` errors.

**Comment by tatwater** [comment] 2023-07-19 20:58
@jrobsontull Yeah unfortunately that's the case for me as well, just a pile of identical errors with no indication which of my files are to blame :/

Time to start commenting things out!

**Comment by tatwater** [comment] 2023-07-19 21:11
Okay progress: Turns out `export const dynamic = 'force-dynamic'` is exactly the correct current workaround on pages & layouts.

My problem lies with that one server component (a navbar) that's on every page, so looks like I'll be moving the db call to a client component within it and see if that helps

**Comment by sebpowell** [comment] 2023-07-19 21:43
I've run into a similar issue when attempting to implement a currency switching function for an eCommerce site, described the issue in a little more detail here: https://github.com/vercel/next.js/discussions/52911

The approach discussed above did solve the issue, but seems to have resulted in the pages now being dynamically – which I suppose makes sense, but I wrote some notes up anyway as curious to get people's thoughts on the overall approach.

**Comment by gabi789** [comment] 2023-07-19 22:55
> For statically pre-rendered pages I used, e.g.:
> 
> ```tsx
> export const dynamic = 'force-static'
> export const revalidate = 60
> ```
> 
> But this feels like a temporary solution. I don't want to put "force-static" to every ISR page.

This, plus 'force-dynamic' on non-static pages does remove all errors for me. It feels a bit hacky, though.

**Comment by Jordaneisenburger** [comment] 2023-07-20 08:59
> For statically pre-rendered pages I used, e.g.:
> 
> ```tsx
> export const dynamic = 'force-static'
> export const revalidate = 60
> ```
> 
> But this feels like a temporary solution. I don't want to put "force-static" to every ISR page.

I tried this and it seems to work as expected. When you have pages where you want to use generateStaticParams but one of the components on the page uses cookies, for example a connection to supabase the whole page will be marked as dynamic. The force-static will prevent crashing of the page/build but I don't think this is the way it's intended to be used.

**Comment by oldbettie** [comment] 2023-07-20 09:32
same issue adding `export const dynamic = "force-dynamic"` to the layout fixed it but seems like a shitty work around

**Comment by sebpowell** [comment] 2023-07-20 14:42
@Jordaneisenburger – I'm experiencing this very issue as well, described it in a bit more detail here: https://github.com/vercel/next.js/discussions/52911. So I'm guessing your understanding is the same as mine that there's currently no way to use cookies in this way whilst using statically generated pages, and I guess the only way round it would be to get the cookies client side and deal with things that way.

**Comment by Jordaneisenburger** [comment] 2023-07-20 14:52
> @Jordaneisenburger ah great, thank you! Yes ok, it seems that way then. But I'm actually wondering whether such an approach even makes sense – if the page is statically generated, then by definition it cannot incorporate dynamic elements, right? Or perhaps I don't understand how this works, which is also possible 😅

You are correct as far as I understand either a page is static or dynamic. I used to think we can mix those components to get best of both worlds.

**Comment by sebpowell** [comment] 2023-07-20 15:09
Thank you! That's good to know – that was my understanding too, but guess that's not right.

**Comment by ariesclark** [comment] 2023-07-21 01:29
> You are correct as far as I understand either a page is static or dynamic. I used to think we can mix those components to get best of both worlds.

As far as I'm aware, you can mix static and dynamic down to the layout level, ie, a layout could be static, with dynamically pages iirc. I may be wrong though.

**Comment by kien-ngo** [comment] 2023-07-24 04:16
Just had this issue today after upgrading my package.json. Can confirm that exporing "force-dynamic" makes the issue go away
![image](https://github.com/vercel/next.js/assets/26052673/5243f91b-49b3-459c-b0c9-c0d3e6e47a2a)

**Comment by h0tw4t3r** [comment] 2023-07-25 17:30
> I was facing the same issue, but i eventually found out that the error only showed when the 'dynamic' page (in my case, because i am using the cookies) was rendered through the router (using the Link component from [next-intl](https://linear.app/vercel/issue/NEXT-intl)). When i simply replaced the Link with a normal "a" tag, the error message not longer shows.

I do have the same specific error case with `next-intl`.

**Comment by kien-ngo** [comment] 2023-07-26 02:00
> Just had this issue today after upgrading my package.json. Can confirm that exporing "force-dynamic" makes the issue go away ![image](https://user-images.githubusercontent.com/26052673/255477886-5243f91b-49b3-459c-b0c9-c0d3e6e47a2a.png)
> 
> ```
> "@supabase/auth-helpers-nextjs": "^0.7.3",
> "@supabase/supabase-js": "^2.27.0",
> "next": "^13.4.12",
> ```

So apparently after adding `force-dynamic` the code above will build but when deployed to Vercel somehow `supabase.from(...).select()` no longer return any items - even tho it works perfectly in localhost

**Comment by emrecoban** [comment] 2023-07-26 15:17
> In my case, using the latest NextJS (13.4.9) and `@supabase/auth-helpers-nextjs@0.7.3` my issue was related to the using supabase server component client on page routes that were not dynamic (i.e. /home, /settings instead of /task/[taskId]).
> 
> I thought including `import { cookies } from 'next/headers';` on a `page.tsx` automagically opted into dynamic rendering it seems like during the next build process if the route isn't dynamic it may be trying to render it statically. shrug
> 
> I was able to workaround it by finding the pages that used the the supabase server component client and added a force-dynamic.
> 
> ```
> export const dynamic = 'force-dynamic';
> ```
> 
> In my case I wanted them to always be dynamic, so it worked well.

I added `export const dynamic = "force-dynamic"` to supabase-server.js, but it didn't work. Do I have to add all of pages?

@kien-ngo @wontondon 

```javascript
import { cookies } from 'next/headers';
import { cache } from 'react';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';

export const dynamic = "force-dynamic" //clodflare solution

export const createServerSupabaseClient = cache(() =>
    createServerComponentClient({ cookies })
)

export async function getSession() {
    const supabase = createServerSupabaseClient()
    try {
        const {
            data: { session }
        } = await supabase.auth.getSession()
        return session
    } catch (error) {
        console.error('Error:', error)
        return null
    }
}
```

**Comment by kien-ngo** [comment] 2023-07-26 15:33
@emrecoban I only needed to add it to one single page (as seen in my code above)

**Comment by wontondon** [comment] 2023-07-26 16:45
@emrecoban I added to all the pages I was experiencing the message.

**Comment by mbret** [comment] 2023-07-28 08:35
Interesting, I got the error while using cookies inside another function from my Page. If I make a call to cookies directly in the page component it's fine.

**Comment by emrecoban** [comment] 2023-07-28 08:50
> Interesting, I got the error while using cookies inside another function from my Page. If I make a call to cookies directly in the page component it's fine.

Interesting. I am using `cookies` with Supabase. It didn't work unfortunately (runtime is edge, in prod).

```javascript
import { cookies } from 'next/headers';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';

export default async function Dashboard() {
    const supabase = createServerComponentClient({ cookies })
    async function getSession() {
        try {
            const {
                data: { session }
            } = await supabase.auth.getSession()
            return session
        } catch (error) {
            console.error('Error:', error)
            return null
        }
    }
    const serverSession = await getSession()
    const userInfo = serverSession?.user
    return ()
}
```

**Error message:**
```bash
Error: Invariant: Method expects to have requestAsyncStorage, none available
```

**Comment by mbret** [comment] 2023-07-28 09:07
by the way my code was working correctly before, it has to be since a specific next version.

**Comment by emrecoban** [comment] 2023-07-28 09:08
@mbret thanks for the response. Everything is up to dated (https://github.com/vercel/next.js/issues/52176#issuecomment-1653264986). I guess `cookies` doesn't work in edge runtime, but it doesn't build my app if I change runtime to nodejs. It want me to make runtime edge. Interesting.

**Comment by emrecoban** [comment] 2023-07-28 12:11
My issue was **solved** through this way: https://github.com/vercel/next.js/issues/45371#issuecomment-1655408690

```javascript
import { cookies } from 'next/headers';
import { cache } from 'react';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';

export const createServerSupabaseClient = cache(() => {
    const cookieStore = cookies()
    return createServerComponentClient({ cookies: () => cookieStore })
})

export async function getSession() {
    const supabase = createServerSupabaseClient()
    try {
        const {
            data: { session }
        } = await supabase.auth.getSession()
        return session
    } catch (error) {
        console.error('Error:', error)
        return null
    }
}
```

**Comment by vishal-sarg** [comment] 2023-07-29 06:26
I am getting this same error while trying to use Supabase auth using Cookies in Next

**Comment by arthureberledev** [comment] 2023-08-02 13:58
Going from 

```
export const createServerComponentClient = cache(() =>
  _createServerComponentClient<Database>({ cookies })
);
```
to 
```
export const createServerComponentClient = cache(() => {
  const cookieStore = cookies();
  return _createServerComponentClient<Database>({ cookies: () => cookieStore });
});
```
fixed it for me.

**Comment by vishal-sarg** [comment] 2023-08-02 14:41
Thanks @arthureberledev, this fixed it!

**Comment by mbret** [comment] 2023-08-02 16:01
> Going from
> 
> ```
> export const createServerComponentClient = cache(() =>
>   _createServerComponentClient<Database>({ cookies })
> );
> ```
> 
> to
> 
> ```
> export const createServerComponentClient = cache(() => {
>   const cookieStore = cookies();
>   return _createServerComponentClient<Database>({ cookies: () => cookieStore });
> });
> ```
> 
> fixed it for me.

that's also how I fixed it. well done

**Closed** 2023-08-08 10:49 UTC
Labels: template: bug, area: app, linear: next
