### ISSUE TITLE
In simple NextJS project building on my mac and codesandbox, Getting worry-some warning

### ISSUE THREAD

**Issue by pkellner** [vercel/next.js#15002] opened 2020-07-09 00:28 UTC
# Bug report

Getting this warning making me feel like I'm building a time-bomb.

warning next > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to
chokidar 3 with 15x less dependencies.
warning next > mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported
. Please update to mkdirp 1.x. (Note that the API surface has changed to use P
romises in 1.x.)
warning next > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Cho
kidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependenc
ies.

## Describe the bug

The simple project at this codesandbox
https://codesandbox.io/s/bold-elion-qqwdk

generates these warnings:

warning next > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to
chokidar 3 with 15x less dependencies.
warning next > mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported
. Please update to mkdirp 1.x. (Note that the API surface has changed to use P
romises in 1.x.)
warning next > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Cho
kidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependenc
ies.

## To Reproduce

Build with this CodeSandBox
https://codesandbox.io/s/bold-elion-qqwdk

**Comment by jamesmosier** [comment] 2020-07-09 01:52
Looks like it is on the radar and [upgrading to webpack 5, which is underway, will resolve this](https://github.com/vercel/next.js/issues/13341).

Issue with other links with more info: https://github.com/vercel/next.js/issues/14670#issuecomment-651034901

**Comment by timneutkens** [comment] 2020-07-09 10:51
Closing as duplicate of #14670

**Closed by timneutkens** 2020-07-09 10:51 UTC

**Comment by balazsorban44** [comment] 2022-01-29 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
