### ISSUE TITLE
With-Zones blog not working

### ISSUE THREAD

**Issue by cosydney** [vercel/next.js#25731] opened 2021-06-02 17:26 UTC
### What example does this report relate to?

with-zones

### What version of Next.js are you using?

latest

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Running the example there are two things that are not working for me: 

```
The blog app should be up and running in http://localhost:4000!
```

=> I get a 404.

BUT on localhost:3000 I can go to the blog. 

```
With the home app deployed you should now be able to see both apps running under the same domain!

```
=> I only get the home page and not the blog

### Expected Behavior

I expect to see the blog on vercel => https://with-zones-sable.vercel.app/

The blog doesn't seem to work => https://blogzone.vercel.app/

(I've followed the example and changed variables where I need to)	

### To Reproduce

Follow this example: https://github.com/vercel/next.js/tree/canary/examples/with-zones

**Comment by ijjk** [comment] 2021-09-19 05:58
Hi, the current version of the example appears to be working fine so I'm going to close this, if you're still having trouble with this feel free to respond with additional info and we can look into this more.

**Closed by ijjk** 2021-09-19 05:58 UTC
Labels: type: example, template: bug

**Comment by gsambrotta** [comment] 2021-11-18 11:05
Hi @ijjk I cannot find the actual issue that describe this problem anymore so I just gonna tag along this issue. Hopefully is ok.

Maybe I'm worng but I think With-zone example does not work properly. 
I think it work ok if the two repo are under the same domain but if they are in separate domain, static resource are not loaded.

In the example it work just because the image is in both static folder. 
But if you go to `localhost:3000/blog` in the webconsole we can see that the image that is actually loaded, is loaded from the `home/static` folder. And not from `blog/static`

Please correct me if I'm wrong. 
I have home and blog repo deployed in two different place therefor with two different domain. Following your example, I can see my blog index page but I don't see the css and js.

For the same reason, rewrites doesn't seems to work when using `npm export`. Is that correct?

**Comment by balazsorban44** [comment] 2022-01-27 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
