### ISSUE TITLE
Incorrect ESLint Error: `next/document should not be imported outside of pages/_document.js`

### ISSUE THREAD

**Issue by AryanBeezadhur** [vercel/next.js#28958] opened 2021-09-09 12:01 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.15.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

Vercel

### Describe the Bug

As you can see, the file I am getting the error `next/document should not be imported outside of pages/_document.js` when I am inside of `pages/_document.js`.

![image](https://user-images.githubusercontent.com/34424160/132681945-6f802a63-cab9-41fe-9c24-3e790c8ac137.png)

**Comment by AryanBeezadhur** [comment] 2021-09-09 13:06
This is a bug in Next.js 11, because when I downgraded to Next.js 10 by using the commands `npm i next@10` and `npm i eslint-config-next@10 -D` I stopped getting the error.

**Comment by housseindjirdeh** [comment] 2021-09-14 13:19
Hi @AryanBeezadhur, this might just be a duplicate of #28596. Is `eslint-config-next` (or `@next/eslint-plugin-next`) installed with version `11.1.3-canary.7` or later? If not, upgrading it and then clearing the cache (`next lint --no-cache`) should fix this issue.

**Comment by ijjk** [comment] 2021-09-18 15:28
Closing per above as this is most likely a duplicate of https://github.com/vercel/next.js/issues/28596 and can be resolved by updating to the latest canary.

**Closed by ijjk** 2021-09-18 15:28 UTC
Labels: template: bug

**Comment by AryanBeezadhur** [comment] 2021-09-30 16:03
@housseindjirdeh I followed your instructions but I got this error when I ran `npx next lint --no-cache`:

```bash
Installing devDependencies:
- eslint-config-next 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: aryanbeezadhur.com@0.1.0
npm ERR! Found: next@11.1.3-canary.38
npm ERR! node_modules/next
npm ERR!   next@"^11.1.3-canary.38" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer next@">=10.2.0" from eslint-config-next@11.1.2
npm ERR! node_modules/eslint-config-next
npm ERR!   dev eslint-config-next@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\aryan\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aryan\AppData\Local\npm-cache\_logs\2021-09-30T15_57_22_144Z-debug.log
undefined
```

Initially I got this error when I was trying to update `next`, so I deleted `package-lock.json` and `node_modules` and cleared npm's cache and now `next` is working but `eslint` isn't.

**Comment by anikaa137** [comment] 2021-10-02 15:00
![image](https://user-images.githubusercontent.com/76861919/135722071-3f0a34d4-f8bf-4e0c-8f53-159cbc97204b.png)

I got the same problem.How to solve it ?

**Comment by AryanBeezadhur** [comment] 2021-10-09 18:24
I found how to solve this problem @anikaa137:

1. Delete `package-lock.json`
2. Delete `node_modules`
3. Change `next` version to `latest` in `package.json`
4. Change `eslint-config-next` version to `latest` in `package.json`
5. Run `npm install`

**Comment by anikaa137** [comment] 2021-10-09 19:12
Thank You

**Comment by balazsorban44** [comment] 2022-01-27 15:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
