### ISSUE TITLE
"body exceeded 1mb limit" in  nextjs api routes

### ISSUE THREAD

**Issue by thatanjan** [vercel/next.js#27595] opened 2021-07-29 10:21 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

v16.5.0

### What browser are you using?

Brave

### What operating system are you using?

Arch Linux

### How are you deploying your application?

next 

### Describe the Bug

I am trying to build a react image uploader application with nextjs api routes. 

The `/api/upload` api file: 

```javascript
import cloudinary from 'cloudinary'

export const uploadDir = 'cules-uploader/'

const handler = async ({ body, method }, res) => {
	try {
		if (method !== 'POST')
			return res.status(400).json({ message: 'Invalid method' })

		const cloudinaryV2 = cloudinary.v2

		cloudinaryV2.config({
			cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
			api_key: process.env.CLOUDINARY_API_KEY,
			api_secret: process.env.CLOUDINARY_API_SECRET,
		})

		const { src } = body

		const imageConfig = {
			width: 1920,
			height: 1080,
			crop: 'fit',
			quality: 80,
			folder: uploadDir,
		}

		const { public_id } = await cloudinaryV2.uploader.upload(src, imageConfig)

		return res.json({ success: true, public_id })
	} catch (e) {
		return res.status(400).send({ message: 'Error processing request' })
	}
}

export default handler
```
I try to send a request from my client side code with axios:

```javascript
const handleUpload = async () => {
	  const { data } = await axios.post('/api/upload', {
		src: base64File,
	})
  }

```
It works fine if the file size is less than 1mb. But if file is more than 1mb, I get 413 error.
![Screenshot_20210729_155808](https://user-images.githubusercontent.com/71136371/127472477-02591d50-ae33-4413-831f-2057c585d53f.png)

I also extend the body parser size limit on `next.config.js` file.
```javascript
module.exports = {
	reactStrictMode: true,
	api: {
		bodyParser: {
			sizeLimit: '50mb',
		},
	},
}
```
But I still get 413 error. If I send a request with postman, then it works. 
![Screenshot_20210729_161432](https://user-images.githubusercontent.com/71136371/127474707-d3b5506d-0759-4402-ac7d-2eb0d6ee8df3.png)

### Expected Behavior

When I want to send request body more than 1mb, I don't want to get the following 413 error.
![Screenshot_20210729_155808](https://user-images.githubusercontent.com/71136371/127472477-02591d50-ae33-4413-831f-2057c585d53f.png)

### To Reproduce

`/api/upload` file: 
```javascript
import cloudinary from 'cloudinary'

export const uploadDir = 'cules-uploader/'

const handler = async ({ body, method }, res) => {
	try {
		if (method !== 'POST')
			return res.status(400).json({ message: 'Invalid method' })

		const cloudinaryV2 = cloudinary.v2

		cloudinaryV2.config({
			cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
			api_key: process.env.CLOUDINARY_API_KEY,
			api_secret: process.env.CLOUDINARY_API_SECRET,
		})

		const { src } = body

		const imageConfig = {
			width: 1920,
			height: 1080,
			crop: 'fit',
			quality: 80,
			folder: uploadDir,
		}

		const { public_id } = await cloudinaryV2.uploader.upload(src, imageConfig)

		return res.json({ success: true, public_id })
	} catch (e) {
		return res.status(400).send({ message: 'Error processing request' })
	}
}

export default handler
```
Client side code: 
```javascript
const handleUpload = async () => {
	  const { data } = await axios.post('/api/upload', {
		src: base64File,
	})
  }

```

**Comment by timneutkens** [comment] 2021-07-29 10:45
Duplicate of https://github.com/vercel/next.js/issues/19684#issuecomment-735897241

**Closed by timneutkens** 2021-07-29 10:45 UTC
Labels: template: bug

**Comment by jose-donato** [comment] 2021-07-29 11:19
@thatanjan the config snippet should be added to the API function file, not in next.config.js

**Comment by Soujiro17** [comment] 2021-08-28 17:57
Who can explain me how can i add the config? I loaded the config file in the API function file, but doesn't work. What more i need to do?

**Comment by Veshal-Maniam** [comment] 2021-11-09 11:05
> Who can explain me how can i add the config? I loaded the config file in the API function file, but doesn't work. What more i need to do?
> 
> ![image](https://user-images.githubusercontent.com/13888213/131226832-bc5e3fde-df94-4b60-b5be-5ecd7b2cb8ca.png)

Paste the following code before the handler function.

`export const config = {
  api: {
    bodyParser: {
      sizeLimit: '25mb' // Set desired value here
    }
  }
}`

**Comment by Mahdi-Soultana** [comment] 2021-12-07 17:08
thank you  very much it's solve the problem thank's a lot

**Comment by balazsorban44** [comment] 2022-01-27 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
