### ISSUE TITLE
When I set reactStricMode to true in Next.js v13.4, rendering is not performed.

### ISSUE THREAD

**Issue by in-ch** [vercel/next.js#55427] opened 2023-09-15 08:12 UTC
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/in-ch/report-reactStrict-mode-bug

### To Reproduce

<code>next.config.js</code>

```javascript
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    serverActions: true,
  },
  reactStrictMode: true,
};
  
module.exports = nextConfig;
```

### Current vs. Expected behavior

When I set reactStricMode is true in Next.js v13.4 version, rendering is not performed.

Starting with v13.4 and later, I was able to resolve the issue by deleting the feature after confirming that reactStricMode is provided by default as true. But I'm reporting it because I think it's a bug.

- Before deleting the reactStrictMode option
![prev](https://github.com/vercel/next.js/assets/49556566/a6a0d279-61fa-4a08-a99b-bf33f0cb0201)

- After deleting the reactStrictMode option
![after](https://github.com/vercel/next.js/assets/49556566/37afebb8-4039-4d92-83fe-9050e09e62ac)

- reference
[reactStrictMode](https://nextjs.org/docs/pages/api-reference/next-config-js/reactStrictMode)

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
macOS: Ventura v13.2.1 
node: v16.17.1
react: v18.2.0
next: canary
```

### Which area(s) are affected? (Select all that apply)

Not sure, App Router

### Additional context

in localhost

**Comment by JesseKoldewijn** [comment] 2023-09-15 08:42
This is probably caused by the combination of the experimental.serverActions flag together with reactStrict. Since any experimental flag in the Next.js config also runs the experimental channel of React.js 

Though I'm not sure about any fix for this outside of not using serverActions or StrictMode at this point. At least, as long as serverActions are experimental. 

Ps. don't strictly quote me on the React.js experimental channel part since this at least in the past used to be the case, but not sure if it still is.

**Closed** 2023-09-16 07:25 UTC
Labels: template: bug
