### ISSUE TITLE
LF to CRLF in `next-env.d.ts`

### ISSUE THREAD

**Issue by estorski** [vercel/next.js#27980] opened 2021-08-11 20:56 UTC
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

16.4.0

### What browser are you using?

does not matter

### What operating system are you using?

Windows

### How are you deploying your application?

next build

### Describe the Bug

For whatever reason, when running `next build` or starting a dev server with `next dev` or whatever, it always changes the `LF` line endings in the `next-env.d.ts` file to `CRLF` while making no other meaningful changes in it. That has a few further negative effects:
- the file gets marked as changed while obviously contains no meaningful changes (which is already irritating enough)
- your ESLint rules break on this file (if your setup expects LF only) which could be double-irritating if you have a pre-commit hook checking your project against ESLint
- if get around your pre-commit hook and your `git` is set up to transform any possible `CRLF` to `LF` automatically, then eventually you'll end-up with the proper format being pushed into repo. However once you re-launch the app locally, the story starts over again

Am I missing some important configuration detail in next.js? Or am I the only one affected by this?

### Expected Behavior

The file is NOT touched by `next.js` unless it has any meaningful changes to be applied there. Also, it should respect the line-endings that already exist in that file.

### To Reproduce

Please inquire if this is necessary, but running any setup on Windows having the file with LF endings should already be enough.

**Comment by estorski** [comment] 2021-08-11 20:59
Just now realized this is basically the same as https://github.com/vercel/next.js/issues/27324, I can just confirm this issue still exists in `next.js` version `11.1.0`

**Comment by ijjk** [comment] 2021-09-20 02:42
Closing as a duplicate of https://github.com/vercel/next.js/issues/27324 per above

**Closed by ijjk** 2021-09-20 02:42 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
