### ISSUE TITLE
False positive in circular structure detection

### ISSUE THREAD

**Issue by m-lautenbach** [vercel/next.js#16393] opened 2020-08-20 12:27 UTC
# Bug report

## Describe the bug

Dev server interprets arrays containing the same object multiple times as circular structure.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. call `isSerializableProps` on an object containing an array which contains the same object twice
2. this happened to us during development (presumably because ApolloJS in-memory cache)

## Expected behavior

An array which contains the same object twice should not be rejected a cyclical.

## Screenshots

<img width="1904" alt="Screenshot 2020-08-20 at 14 25 21" src="https://user-images.githubusercontent.com/2509770/90769782-15dca980-e2f1-11ea-9c4b-7d5e2084b56c.png">

## System information

should be system independent, but happy to provide if it can't be reproduced.

## Additional context

I opened a pull request with a fix and a test case to cover it: https://github.com/vercel/next.js/pull/16380

**Comment by jamesmosier** [comment] 2020-10-25 19:06
Closing as https://github.com/vercel/next.js/pull/16380 was merged.

**Closed by jamesmosier** 2020-10-25 19:06 UTC

**Comment by m-lautenbach** [comment] 2020-10-25 19:34
thanks 👍

**Comment by balazsorban44** [comment] 2022-01-29 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
