### ISSUE TITLE
404 for help link shown in next/image error message

### ISSUE THREAD

**Issue by jasonharrison** [vercel/next.js#19212] opened 2020-11-16 16:20 UTC
# Bug report

## Describe the bug

When an invalid `src` prop is passed to the `<Image>` component, I am presented with this error message:
> Error: Invalid src prop (http://www.example.com/foo.jpg) on `next/image`, hostname "www.example.com" is not configured under images in your `next.config.js`
>
> See more info: https://err.sh/nextjs/next-image-unconfigured-host

**https://err.sh/nextjs/next-image-unconfigured-host 404s.**

## Expected behavior

I expected a working link to a help page or documentation.

## Screenshots

![image](https://user-images.githubusercontent.com/304383/99278909-a39b3880-27fd-11eb-888a-9ef5b91b80b3.png)

## System information

- OS: [MacOS]
- Version of Next.js: next@10.0.1
- Version of Node.js: v14.8.0

**Comment by Christopher-Warren** [comment] 2020-11-18 18:28
Came across this while searching for a solution to my identical issue. It was fixed by creating a next.config.js file in the root folder and adding

`module.exports = {
  images: {
    domains: ["www.example.com"],
  },
};
`

**Comment by hypersundays** [comment] 2020-11-20 09:00
Ran into this and there's a pending PR for this [https://github.com/vercel/next.js/pull/19280](#19280)

**Comment by timneutkens** [comment] 2020-11-27 15:27
This was fixed in #18787 and #19280

**Closed** 2020-11-27 15:27 UTC
Labels: kind: story, point: 1

**Comment by balazsorban44** [comment] 2022-01-29 02:12
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
