### ISSUE TITLE
when using custom server beside i18n firs load is not single page application and all redirect will refresh the browser

### ISSUE THREAD

**Issue by mlnima** [vercel/next.js#23765] opened 2021-04-07 08:32 UTC
### What version of Next.js are you using?

10.0.9

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows,|Ubuntu

### How are you deploying your application?

next start

### Describe the Bug

It's a bit complicated, I wanna cache the pages, in order to do that I need to use a custom route in the express backend so I cache the response. when I add i18n config no matter I cache or use a normal app.render when the site load if I click on any links it will hard redirect the user and the app is not single page application, I know that we have to use rewrites in next config and I have that also, I tried with app.render and app.rendertohtml, just I repeat once again this happen when i18n config is added, without that everything works fine and I can have custom route in express

### Expected Behavior

I expect when we use app, render along i18n config app work normal and be a single page application and not redirect the user like hard refers the page

### To Reproduce

server.get('/', (req, res) => app.render(req, res,'/'))
or 
server.get('/', (req, res) => ssrCache({ req, res,'/' }))

**Comment by mlnima** [comment] 2021-04-07 08:40
![image](https://user-images.githubusercontent.com/39328836/113836798-7f7ccb80-978d-11eb-9711-29168f342b9f.png)
the default locale and locales are undefined when I use the custom route in express

**Comment by weishiji** [comment] 2021-04-16 12:44
Same with this issue

**Comment by ijjk** [comment] 2021-04-17 15:39
Closing as this sounds like a duplicate of https://github.com/vercel/next.js/issues/20761 if this isn't a duplicate please provide a minimal reproduction and it can be investigated further here.

**Closed by ijjk** 2021-04-17 15:39 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
