### ISSUE TITLE
Misleading error message when using `getServerSideProps` and `getStaticPaths`

### ISSUE THREAD

**Issue by jedrzejchalubek** [vercel/next.js#11198] opened 2020-03-19 12:16 UTC
# Bug report

## Describe the bug

We are getting a misleading error message when have `getStaticPaths` with `getServerSideProps` instead of `getServerSidePaths`

> Error: You can not use getStaticProps with getServerSideProps. To use SSG, please remove getServerSideProps

## To Reproduce

Prepare a page at `/page/[slug].js` with following content:

```

export async function getServerSideProps ({ req, params }) {
  //
}

export async function getStaticPaths () {
  //
}

export default Index = () => {
  return (
    <div></div>
  )
}

```

## Expected behavior

Getting a valid error message about using `getServerSidePaths` instead of `getStaticPaths`

## System information

- OS: macOS
- Version of Next.js: 9.3.0

**Comment by Timer** [comment] 2020-06-11 13:56
This has already been fixed on `next@canary`. Thanks!

**Closed by Timer** 2020-06-11 13:56 UTC

**Comment by balazsorban44** [comment] 2022-01-29 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
