### ISSUE TITLE
unstable_skipClientCache missing in next/link

### ISSUE THREAD

**Issue by Hegde45** [vercel/next.js#46016] opened 2023-02-16 20:33 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
  Platform: linux
  Arch: x64
  Version: #66~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023
Binaries:
  Node: 14.17.5
  npm: 6.14.14
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 13.1.6
  eslint-config-next: 13.1.6
  react: 18.2.0
  react-dom: 18.2.0

### Which area(s) of Next.js are affected?

Data fetching (gS(S)P, getInitialProps), Routing (next/router, next/navigation, next/link)

### Link to the site that reproduces this issue

https://on-demand-isr-no-cache.vercel.app/

### To Reproduce

1. Navigate from home page to ssg page - static page
2. Shows Current date (of last build / revalidation)
3. Navigate back to home page
4. Navigate to ssr page
5. Shows current date (latest)
6. Click on the date
7. api request is made which revalidates ssg page - ON DEMAND ISR
8. Navigate back to home page
9. Navigate to ssg
10. Still shows Current date(of last build / revalidation) - not current date after revalidation

### Describe the Bug

After revalidating the page with ON DEMAND ISR,
When user hovers the mouse on the to ssg page, api request is made to getStaticProps to get data
If the user clicks on the link before the request is completed(usually this is the case) and navigates - he gets the old data(date)

Upon subsequent visits to the page or on reload, content of the static page is updated

### Expected Behavior

to avoid above scenario

next/link should provide an option to skip client cache (i.e., unstable_skipClientCache as compared to router.push)

using router push does not allow prefetching, web crawling but allows unstable_skipClientCache

next/link allows prefetching, web crawling but not unstable_skipClientCache

**Comment by ijjk** [comment] 2023-02-22 02:28
Closing as duplicate of https://github.com/vercel/next.js/issues/46017

**Closed by ijjk** 2023-02-22 02:28 UTC
Labels: template: bug
