### ISSUE TITLE
Getting "Error: Cannot find module '/app/.next/server/font-manifest.json'" on production build

### ISSUE THREAD

**Issue by ghost** [vercel/next.js#24605] opened 2021-04-29 15:47 UTC
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

12.20.0

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying your application?

Code Build

### Describe the Bug

I am getting the following error on 10.2, working on 10.1.3

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: no next.config.js https://nextjs.org/docs/messages/webpack5
Error: Cannot find module '/app/.next/server/font-manifest.json'

The font-manifest.json does not exist after a build. This happens on a fresh build in our CD pipeline.

Is there something needed to migrate to v 10.2?

### Expected Behavior

The server should stay up at port 3000

### To Reproduce

Just build and serve the current codebase.

**Comment by timneutkens** [comment] 2021-04-29 16:19
> Just build and serve the current codebase.

Just build your application? How 🤔

**Comment by PavelDemyanenko** [comment] 2021-04-29 16:54
Same issue for me:
```
ready - started server on 0.0.0.0:8080, url: http://localhost:8080
info - Using webpack 5. Reason: no next.config.js https://nextjs.org/docs/messages/webpack5
Error: Cannot find module '/web/.next/server/font-manifest.json'
Require stack:
- /web/node_modules/next/dist/next-server/server/require.js
- /web/node_modules/next/dist/next-server/server/load-components.js
- /web/node_modules/next/dist/next-server/server/api-utils.js
- /web/node_modules/next/dist/next-server/server/next-server.js
- /web/node_modules/next/dist/server/next.js
- /web/node_modules/next/dist/server/lib/start-server.js
- /web/node_modules/next/dist/cli/next-start.js
- /web/node_modules/next/dist/bin/next
```

**Comment by grnwld** [comment] 2021-04-29 17:28
I'm getting same error on 10.0.3 😟

**Comment by jc-delvalle** [comment] 2021-04-29 17:33
@timneutkens for some inexplicable reason, the issue is not happening anymore, even I just re-ran a failing deploy task, and seems to be working now, I think something broke in the package versions downloaded from npm between yesterday around this time and today. As it randomly started to happen it went away for me...

**Comment by timneutkens** [comment] 2021-04-30 11:28
@PavelDemyanenko @grnwld please provide a reproduction, these comments are not useful and will not help with solving the issue you're running into.

**Comment by cherepanov** [comment] 2021-04-30 16:16
the same after update to 10.1.3 => 10.2.0. workaround is to disable font processing via config
```
optimizeFonts: false,
```

**Comment by DarkCode01** [comment] 2021-05-04 15:45
i have the same issues

**Comment by DarkCode01** [comment] 2021-05-04 15:48
> the same after update to 10.1.3 => 10.2.0. workaround is to disable font processing via config
> 
> ```
> optimizeFonts: false,
> ```

Tha fix it 👍🏽

**Comment by timneutkens** [comment] 2021-05-04 15:58
Again, please provide a reproduction for your particular issue so that it can be investigated.

**Comment by lxn07122945** [comment] 2021-05-06 07:21
> the same after update to 10.1.3 => 10.2.0. workaround is to disable font processing via config
> 
> ```
> optimizeFonts: false,
> ```

**Comment by lxn07122945** [comment] 2021-05-06 07:21
I want to know reason

**Comment by timneutkens** [comment] 2021-11-17 15:39
Closing as no reproduction was provided.

**Closed** 2021-11-17 15:39 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-27 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
