### ISSUE TITLE
Guide for creating forms with Next.js

### ISSUE THREAD

**Issue by molebox** [vercel/next.js#29602] opened 2021-10-04 09:12 UTC
### Describe the feature you'd like to request

We don't currently document how to create forms using Next.js. We _do_ have a blog post however.

### Describe the solution you'd like

Turn the blog post (https://nextjs.org/blog/forms) into a guide for the new guides section

### Describe alternatives you've considered

N/A

**Comment by molebox** [comment] 2021-11-23 09:05
For now, lets create a top level Guides section on the left nav and add this there. We can use that as a base for further Guides moving forward. Eventually we will mimic the Vercel new navigation and have the Guides in the top nav.

**Comment by unbelivr** [comment] 2021-11-26 08:45
There’s nothing special in Next.js forms, they should be created the same way as everyone does with React.

I don’t think Next.js should teach the react basics. API routes are good described already.

**Comment by MaedahBatool** [comment] 2021-12-20 13:07
Closing this issue for now. Treating this as a working document https://github.com/vercel/documentation/issues/35

**Closed by MaedahBatool** 2021-12-20 13:07 UTC
Labels: area: documentation, kind: story

**Comment by balazsorban44** [comment] 2022-01-27 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
