### ISSUE TITLE
Prevent scrolling to top when using router.replace()

### ISSUE THREAD

**Issue by bgoyarts** [vercel/next.js#21625] opened 2021-01-28 13:43 UTC
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

12

**What browser are you using?**

Firefox

**What operating system are you using?**

Windows

**How are you deploying your application?**

Other platform

**Describe the Bug**

When using the router to replace the query parameters, the page is scrolled to the top. I have created an example of this on [codesandbox](https://codesandbox.io/s/magical-poitras-n5nop?file=/pages/index.js)

In our scenario we have a listing page with a pagination button. When clicking the pagination button, new items are being loaded and rendered on screen. We store the page-number in the query parameters so we can determine how many items to load when navigating between item detail page and the listing page. 

However, this [PR](https://github.com/vercel/next.js/pull/20595) seems to have introduced unexpected behavior to our implementation.

Is there a way to prevent the page from scrolling?

**Expected Behavior**

The page should not scroll. 

**To Reproduce**

I have created a codesandbox [here](https://codesandbox.io/s/magical-poitras-n5nop) where you will see a list of items. All the way to the bottom of the list is a button which updates the pageNumber, and with it, the amount of items on the page. 
When updating the pageNumber, the url parameters are updated through `router.replace`. This causes the page to scroll to the top.

**Comment by Timer** [comment] 2021-01-28 16:49
Fixed in https://github.com/vercel/next.js/pull/21437

**Closed by Timer** 2021-01-28 16:49 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
