### ISSUE TITLE
next/image is not working after export (Next.js v10.0.0)

### ISSUE THREAD

**Issue by odemian** [vercel/next.js#18460] opened 2020-10-29 10:51 UTC
# next/image is not working after export (Next.js v10.0.0)
`next/image` works well in development, but it is not working after static export (`next export`)

## To Reproduce
Do the `next export` on the website that uses next/images (ex: https://github.com/vercel/next.js/tree/canary/examples/image-component)

## Expected behavior
Have optimized images after export

## Screenshots
![image](https://user-images.githubusercontent.com/63239475/97558584-9c41f580-19dc-11eb-8da6-7d78bc501a92.png)

**Comment by timneutkens** [comment] 2020-10-29 11:20
Duplicate of #18356

**Closed by timneutkens** 2020-10-29 11:20 UTC

**Comment by balazsorban44** [comment] 2022-01-29 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
