### ISSUE TITLE
When I type a url to carry parameters, the component automatically performs an update action after mounting. Why?

### ISSUE THREAD

**Issue by hjyyang** [vercel/next.js#20530] opened 2020-12-28 10:56 UTC
# Bug report

When I type a url to carry parameters, the component automatically performs an update action after mounting. Why?

## Describe the bug

When I type http://localhost:3000 in my browser page, my component performs the mount, which is normal.But when I say http://localhost:3000?userId =12580 to my browser. When it comes to the page, my component performs a mount, followed by an update, but I don't change any state

Different urls enter the page, and lifecycle functions execute differently

## To Reproduce
When NPM run dev opens the development environment, type http://localhost:3000?userId =12580 in your browser. goes to the page and sees the result printed by the componentDidMount method and the componentDidUpdate method

Steps to reproduce the behavior, please provide code snippets or a repository:

1. npm run dev
2. Browser input http://localhost:3000?userId =12580
3. ComponentDidMount and componentDidUpdate lifecycle functions are written in the component and this is Mount and this is Update are printed respectively
4. See that this is Mount and this is Update are printed

## Expected behavior
You want to execute only the componentDidMount method

## System information

- OS: [e.g. macOS, Windows]    
- Windows
- Browser (if applies) [e.g. chrome, safari]   
- chrome
- Version of Next.js: [e.g. 10.0.1]
- 10.0.1
- Version of Node.js: [e.g. 12.0.0]
- 12.16.3
- Deployment: [e.g. next start, next export, Vercel, other platform]

**Comment by giupas** [comment] 2020-12-28 15:11
Same as #20201

**Comment by Timer** [comment] 2020-12-28 15:24
Duplicate of #20201

**Closed by Timer** 2020-12-28 15:24 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-29 00:11
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
