### ISSUE TITLE
Add migration guide from cta to Next.js to docs

### ISSUE THREAD

**Issue by lfades** [vercel/next.js#16361] opened 2020-08-19 17:58 UTC
A migration guide for a common application with detailed steps of what has to be done if you want to move your current app in create-next-app to Next.js would be very useful for a lot of new users.

**Comment by leerob** [comment] 2020-10-08 22:28
Looks like we accidentally duplicated this one. Closing for the newer issue https://github.com/vercel/next.js/issues/17454

**Closed by leerob** 2020-10-08 22:28 UTC
Labels: good first issue, kind: story, type: documentation

**Comment by balazsorban44** [comment] 2022-01-29 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
