### ISSUE TITLE
Component gives Module parse failed:  Unexpected token

### ISSUE THREAD

**Issue by skar07** [vercel/next.js#28255] opened 2021-08-18 12:18 UTC
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

14.17.3

### What browser are you using?

Opera

### What operating system are you using?

Windows

### How are you deploying your application?

next dev

### Describe the Bug

I had created a React component file within the component directory and had it run successfully. The component file on being deployed gives the following error all of a sudden,

Things that have been tried:
Changed directories
Changed names 
Changed function name
Re-added file

```error - ../components/CallToAction.tsx
Module parse failed: Unexpected token (2:29)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import React from 'react';
 export const CallToAction = (): React.ReactElement => {
|       return (
|               <div className='bg-gradient-to-r from-green-400 via-blue-500 to-blue-500 animate-gradient-x transform -skew-y-3 md:mr-8 px-8 py-12 w-full mt-8
```

### Expected Behavior

For the component to be rendered, and not give out an error regarding the loader.

### To Reproduce

Occurs on deploying the following code, regardless of  the file destination:
``` import React from 'react';
export const CallToAction = (): React.ReactElement => {
	return (
		<div className='bg-gradient-to-r from-green-400 via-blue-500 to-blue-500 animate-gradient-x transform -skew-y-3 md:mr-8 px-8 py-12 w-full mt-8'>
			<div className='flex flex-col md:flex-row justify-between max-w-3xl m-auto transform skew-y-3'>
				<div className='text-lg md:text-2xl font-semibold cursor-default md:mr-12 text-white self-end pb-2'>
					Sign up with us to experience our service.
				</div>
				<div className='flex justify-center'>
					<button className='px-6 py-3 rounded bg-blue-600 hover:bg-blue-800 transition text-white m-2'>Sign Up &rarr;</button>
				</div>
			</div>
		</div>
	)
}````

next.config.js:
``` module. exports = {
}
```
React version:  17.0.2
Typescript: 4.3.5
tailwindcss:  2.2.7

**Comment by timneutkens** [comment] 2021-08-18 13:05
Can you add a github repository for this to ensure we get the exact same code you're trying to run. Thanks!

**Comment by ijjk** [comment] 2021-09-23 04:11
Hi, this sounds related to some Windows issues that are fixed in the latest version of Next.js `v11.1.3-canary.31`, please update and give it a try!

If you are still experiencing this after updating please respond with additional info to allow investigating further.

**Closed by ijjk** 2021-09-23 04:11 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
