### ISSUE TITLE
ParsedUrlQuery typings should allow undefined values

### ISSUE THREAD

**Issue by martpie** [vercel/next.js#10284] opened 2020-01-27 15:10 UTC
# Bug report

## Describe the bug

I am not sure if this is an upstream bug or not. This is about the `ctx.query` object.

The type `ParsedUrlQuery` exported from `@types/node/querystring` looks wrong. It is `string | string[]` but in theory could be `undefined` as well.

## To Reproduce

```tsx
// /user.tsx
UserPage.getInitialProps = async (ctx) => {
  const user = ctx.query.user; // CAN be undefined, but is shown as string | string[]

  return {
    // ...
  };
};
```

```ts
Router.push('/user', {
  query: {
    somethingElse: 'blabla' 
    // not defining 'user' here
  }
})
```

## Expected behavior

The types for the `query` object should be less permissive and includes `undefined` in order to write safer code.

## Screenshots

<img width="452" alt="Screen Shot 2020-01-27 at 16 09 10" src="https://user-images.githubusercontent.com/1311607/73186035-6acf8d00-411f-11ea-9bf0-550a78ae4e02.png">

## System information

- OS: n/a
- Browser (if applies): n/a
- Version of Next.js: 6.2.1

## Additional context

The current way of solving it is to extend the `querystring` module by re-declaring it. It is fine, but annoying.

**Comment by andrasnyarai** [comment] 2020-03-17 16:40
also: How is possible to pass a `string[]` value?
@martpie do you happened to know

**Comment by martpie** [comment] 2020-03-17 17:06
@andrasnyarai It can happen if you use the `[...slug].ts` notation for your pages. You don't pass a `string[]` value explicitely, but Next.js gives you this value.

you will get a `ctx.query.slug` that will be an array of the elements of your pathname without the slashes.

Example: `/pages/[...slug].js` -> if you go to `/my/super/page`, `ctx.query.slug` will be `['my', 'super', 'page']`.

All of this is in the docs ;) (routing section)

**Comment by frontsideair** [comment] 2020-04-13 12:52
I had to wrap my query access functions to better reflect the existence of `undefined` values. I found two related issues; https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32022 and more generally https://github.com/microsoft/TypeScript/issues/13778.

The problem seems like before the introduction of `--strict` flag everything could be `undefined` they couldn't keep up with that. Since an upstream solution doesn't seem likely to happen anytime soon Next.js can ship with its own overriding declaration for this and possibly other similarly problematic type definitions.

**Comment by msheakoski** [comment] 2020-04-14 14:32
I ran into this issue as well. It was actually in the Node.js typings at one point:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25818

but undefined was later removed in this commit:
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/2b7def6f58415d444b84aca6f6cb1c4b216bd403#diff-7d84e08967cded0b99ed4328aab0a1a8

**Comment by msheakoski** [comment] 2020-04-15 19:31
A PR on the Node.js typings is in progress: DefinitelyTyped/DefinitelyTyped#43931

**Comment by msheakoski** [comment] 2020-04-18 14:44
The changes are live as of `@types/node 13.13.0`

**Comment by neefrehman** [comment] 2020-04-30 09:45
I'm having a related issue when trying to extract a query in a dynamic route. I'm destructuring a variable (which will be a string) from the `router.query` object, which later I'll need to use some string-specific properties on such as `.substr`. I'm getting errors from this as the variable could also be of type `string[]`:

![image](https://user-images.githubusercontent.com/29544565/80696216-ffef7280-8ace-11ea-923e-a03b0f5a9fd0.png)

When trying to be explicit about the type, I'm getting another saying that I cant assign type `string` to `ParsedUrlQuery` (renaming the variable in the destructuring assignment doesn't cause the issue):

![image](https://user-images.githubusercontent.com/29544565/80695907-822b6700-8ace-11ea-800d-8c36db4b7891.png)

Currently the only workaround is to assign a type of `any`, which isn't ideal:

`const { sketch: sketchId }: any = router.query;`

Is there a way to assign a type of only `string` to `ParsedUrlQuery` so I can continue treating it as such?

Happy to open another issue if needed, but I felt this one was close!

**Comment by msheakoski** [comment] 2020-04-30 14:55
@neefrehman If you use something like Yup or Joi to validate your input, it will conveniently set the correct types:

```typescript
const querySchema = yup.object({
  sketch: yup.string().required().matches(/^[0-9]{6}$/),
})

const { sketch: sketchId } = querySchema.validateSync(req.query)
```

You can also use a [type guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) to prove that sketchId is actually a string:

```typescript
function isString(value: unknown): value is string {
  return typeof value === "string"
}

// sketchId is currently string | string[] | undefined
const { sketch: sketchId } = router.query

//                         sketchId is now typed as string --------v
const isValidSketchId = isString(sketchId) && /^[0-9]{6}$/.test(sketchId)
```

**Comment by neefrehman** [comment] 2020-04-30 15:13
@msheakoski Thanks for this! I actually solved the issue by creating a new variable as asserting it's type, instead of renaming `sketch` while destructuring. I prefer this way as it's slightly cleaner, and I can use `string` properties on `sketchId` in multiple places without having to use a type guard.

```js
const { sketch } = router.query;
const sketchId = sketch as string;

const isValidSketchId = RegExp(/^[0-9]{6}$/).test(sketchId);
const year = sketchId?.substr(4, 2);
const month = sketchId?.substr(2, 2);
```

I hadn't come across Yup or Joi before though, so will check those out.

**Comment by msheakoski** [comment] 2020-04-30 15:35
@neefrehman You're welcome. You can use the type guard once and anything that comes after in the same context will be considered a string:

```typescript
const sketchId = isString(router.query.sketch) ? router.query.sketch : ""
// or inline the check
const sketchId = typeof router.query.sketch === "string" ? router.query.sketch : ""
```

The type assertion in your example is a risky approach because it can still lead to errors. For example, `/^[0-9]{6}$/).test(["123456"])` will return `true`, and any code that depends on sketchId being a string without checking will fail.

In my own code, whenever I feel the need to use a forced type assertion, it usually means that I am missing a necessary check or need to change my logic flow. I only use it as a last resort when I know that I am being smarter than TypeScript.

**Comment by Timer** [comment] 2020-09-12 04:30
Closing as this was fixed in newer Node.js typing versions.

**Closed by Timer** 2020-09-12 04:30 UTC

**Comment by balazsorban44** [comment] 2022-01-29 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
