### ISSUE TITLE
Custom error handling differences on Vercel vs local

### ISSUE THREAD

**Issue by Ehesp** [vercel/next.js#19826] opened 2020-12-04 14:49 UTC
# Bug report

## Describe the bug

Throwing custom errors within a `getStaticProps` call works as expected whilst running NextJS locally:

- In development, a red box with the thrown error appears.
- In production (locally), errors are forwarded to the `_error` page.

When deploying to Vercel however, the default 502 gateway error message appears instead of the custom error page. 

Locally:

![image](https://user-images.githubusercontent.com/842078/101177258-82c94480-363f-11eb-9255-57ed1899dcd2.png)

Vercel:

![image](https://user-images.githubusercontent.com/842078/101177281-8a88e900-363f-11eb-9829-a041c8b977aa.png)

## To Reproduce

1. Clone https://github.com/Ehesp/nextjs-custom-error-repro
2. Run `npm run serve`
3. Go to http://localhost:3000/error

The error thrown from the `[...slug].js` page is correctly passed down and rendered on the `_error` page. On Vercel, it is not handled.

The error logs on Vercel:

![image](https://user-images.githubusercontent.com/842078/101177864-316d8500-3640-11eb-8816-a168179cbd1d.png)

## Expected behavior

That the _error page handler runs on Vercel, and catches the error as it does locally.

## Screenshots

See above

## System information

- OS: macOS
- Version of Next.js: 10.0.1
- Version of Node.js: 12.9.1
- Deployment: Vercel

**Comment by teppeis** [comment] 2021-01-02 01:27
I think https://github.com/vercel/next.js/issues/15981 is the cause.

**Comment by timneutkens** [comment] 2021-01-03 16:11
Duplicate of #15981

**Closed by timneutkens** 2021-01-03 16:11 UTC
Labels: template: bug

**Comment by Ehesp** [comment] 2021-01-03 16:15
Awesome, thanks didn't know what to search for this one!

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
