### ISSUE TITLE
Next build error with webpack 

### ISSUE THREAD

**Issue by veritem** [vercel/next.js#30620] opened 2021-10-29 13:23 UTC
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows(WSL)

### How are you deploying your application?

Vercel

### Describe the Bug

I was upgrading my app to use Nextjs 12, but it's can't build due to this webpack error

![image](https://user-images.githubusercontent.com/53856673/139442394-bd72142a-ca0b-41fe-8804-2cf348cc5b8f.png)

### Expected Behavior

Should build the app 

### To Reproduce

run `next build` in nextjs 12.0.1 app

**Comment by fadi-mimi** [comment] 2021-11-02 09:32
I'm facing the same bug. It is coming from Next internal files in `node_modules`. Webpack is not additionally installed in the project.

**Comment by fadi-mimi** [comment] 2021-11-02 09:46
Related to #30352 #30167

**Comment by timneutkens** [comment] 2021-11-02 09:49
Duplicate of #30352 #30167

**Closed by timneutkens** 2021-11-02 09:49 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
