### ISSUE TITLE
Next.js App Router doesn't work with google cache (http://webcache.googleusercontent.com/)

### ISSUE THREAD

**Issue by pogran** [vercel/next.js#55231] opened 2023-09-11 12:54 UTC
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel-labs/ai-chatbot

### To Reproduce

Go to cache page http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fchat.vercel.ai&oq=cache%3Ahttps%3A%2F%2Fchat.vercel.ai&gs_lcrp=EgZjaHJvbWUqBggAEEUYOzIGCAAQRRg7MgYIARBFGDwyBggCEEUYOtIBCDQxMDFqMGo0qAIAsAIA&sourceid=chrome&ie=UTF-8 and see a lot of errors in devtools 

![image](https://github.com/vercel/next.js/assets/5382042/406effc3-87e0-46a6-8231-04ab2e22048a)

### Current vs. Expected behavior

this not ok behavior only in google cache http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fchat.vercel.ai&oq=cache%3Ahttps%3A%2F%2Fchat.vercel.ai&gs_lcrp=EgZjaHJvbWUqBggAEEUYOzIGCAAQRRg7MgYIARBFGDwyBggCEEUYOtIBCDQxMDFqMGo0qAIAsAIA&sourceid=chrome&ie=UTF-8 and see a lot of errors in devtools 

In real site everything is ok https://chat.vercel.ai/

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
"next": "13.4.7-canary.1"
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

Also I can show my real project with the same problems

<sub>[NEXT-1810](https://linear.app/vercel/issue/NEXT-1810/nextjs-app-router-doesnt-work-with-google-cache)</sub>

**Comment by pogran** [comment] 2023-09-12 05:41
> 

@BryceCYB , @Gunt3r-Tp any ideas?

**Comment by pogran** [comment] 2023-09-12 05:44
> ### Link to the code that reproduces this issue or a replay of the bug
> https://github.com/vercel-labs/ai-chatbot
> 
> ### To Reproduce
> Go to cache page http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fchat.vercel.ai&oq=cache%3Ahttps%3A%2F%2Fchat.vercel.ai&gs_lcrp=EgZjaHJvbWUqBggAEEUYOzIGCAAQRRg7MgYIARBFGDwyBggCEEUYOtIBCDQxMDFqMGo0qAIAsAIA&sourceid=chrome&ie=UTF-8 and see a lot of errors in devtools
> 
> ![image](https://user-images.githubusercontent.com/5382042/267024699-406effc3-87e0-46a6-8231-04ab2e22048a.png)
> 
> ### Current vs. Expected behavior
> this not ok behavior only in google cache http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fchat.vercel.ai&oq=cache%3Ahttps%3A%2F%2Fchat.vercel.ai&gs_lcrp=EgZjaHJvbWUqBggAEEUYOzIGCAAQRRg7MgYIARBFGDwyBggCEEUYOtIBCDQxMDFqMGo0qAIAsAIA&sourceid=chrome&ie=UTF-8 and see a lot of errors in devtools
> 
> In real site everything is ok https://chat.vercel.ai/
> 
> ### Verify canary release
> * [x]  I verified that the issue exists in the latest Next.js canary release
> 
> ### Provide environment information
> ```shell
> "next": "13.4.7-canary.1"
> ```
> 
> ### Which area(s) are affected? (Select all that apply)
> App Router
> 
> ### Additional context
> Also I can show my real project with the same problems

@timneutkens can you view this problem? its very important problem for seo in google

**Comment by Gunt3r-Tp** [comment] 2023-09-12 14:41
@pogran I am facing the same issue, the webcache always behave in unexpected ways (different after a refresh or sometime after a click event...) eventhough everything seems fine in the live version. Same goes for the Nextjs website, which also lead me to believe that this isn't some kind of misconfiguration:
https://webcache.googleusercontent.com/search?q=cache:7I58Nxfiu5IJ:https://nextjs.org/

After replicating Google webcache site locally to run nextjs in dev mode, I got the following errors:

Page Router:
`Uncaught (in promise) Error: Invariant: attempted to hard navigate to the same URL /preview?q=http://localhost:3000/ http://localhost:1337/preview?q=http://localhost:3000/`

App Router:
`Warning: Expected server HTML to contain a matching <main> in <body>.`
`Warning: An error occurred during hydration. The server HTML was replaced with client content in <#document>.`
`Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.`
`Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.`

On other websites using Page Router, I saw a different error but the rendering is stable:

`DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL`

As opposed to 423 and 418 minified React error when using the App Router.
It's also worth noticiting that the document.baseURI points to webcache when using the App Router, but when using the Page router it does point to the proper app url.

**Comment by pogran** [comment] 2023-09-12 14:53
@Gunt3r-Tp Page router is working more stable than App router. And as I see sites with App router don't have problem with seo. with page router they have problems. don't want to use depricated page router because seo. mb its connected with document.baseURI as you told . As I saw some sites in cache load great and after 2-3 sec they recieve this errors 423 and 418 and after that we have view without css

**Comment by pogran** [comment] 2023-09-13 07:45
@ijjk , @Timer could you help with this bug? i think its very important bug for seo

**Comment by timneutkens** [comment] 2023-09-13 08:12
We'll take a look but there is no urgency around this. What you are claiming is wrong, there is no effect on SEO. 
Google's old page cache is an entirely different service than the crawler and it does not affect SEO. 

The GoogleBot crawler is much more advanced than the page cache service, it runs a real browser (Chrome) and you can view exactly how your pages are indexed, including a screenshot of the page on Google Search Console by putting the url in the search bar and then clicking `view tested page` -> screenshot tab.

Here's an example of how nextjs.org/docs which uses App Router are indexed:

<img width="952" alt="CleanShot 2023-09-13 at 10 10 05@2x" src="https://github.com/vercel/next.js/assets/6324199/9be6d5f6-1fcf-4808-aa44-cbb7e27571ad">

As you can see the page loads correctly so it has been indexed correctly.

**Comment by timneutkens** [comment] 2023-09-13 08:30
Try disabling JavaScript. Could be that you're using a css-in-js library and it's not set up correctly for example.

**Comment by pogran** [comment] 2023-09-13 08:32
@timneutkens The same result ... 
![image](https://github.com/vercel/next.js/assets/5382042/dcdf1238-9ee5-4408-82a3-b2e3402a4a3a)

**Comment by timneutkens** [comment] 2023-09-13 08:53
That's because JS is required for hydration for that case (suspense boundaries and such).

**Comment by pogran** [comment] 2023-09-13 09:07
> Try disabling JavaScript. Could be that you're using a css-in-js library and it's not set up correctly for example.

any ideas yet?

**Comment by balazsorban44** [comment] 2023-09-13 09:48
> Also I can show my real project with the same problems

@pogran could you please add a **minimal** reproduction of your own that simply reproduces the issue you are having? Please don't just point to a full/complex codebase. The less code/dependencies the better. This could help the investigation greatly, avoiding any external factors.

_Note: Please refrain from tagging the maintainers for a quicker reply, as it might have the opposite effect_

**Comment by Gunt3r-Tp** [comment] 2023-09-19 22:42
@balazsorban44 the issue seems to happen with any starter project that use create-next-app with app router enabled. As mentioned above, the ai chat sample, which uses the default nextjs configurations, is also affected by this.

**Comment by pogran** [comment] 2023-09-26 05:32
any ideas how to solve this?

**Comment by pogran** [comment] 2023-10-09 08:57
@balazsorban44 @timneutkens  this problem annoying. I don't have any errors when I use also vercel, but with google console I see problems... 
![image](https://github.com/vercel/next.js/assets/5382042/76fcfd90-4ee6-4890-a7c4-5a1e89367836) any ideas?

**Comment by mehmetkursataydin** [comment] 2023-10-09 09:00
Unfortunately on the same track, waiting badly for this to be fixed

**Comment by nitinTJ** [comment] 2023-10-16 05:49
![image](https://github.com/vercel/next.js/assets/131652690/29c7988d-84df-4e4c-8386-3d4775031e6b)

I am facing this issue. Wherin I am getting Client side Application error, when I am trying to open my website with cache:https://bikes.tractorjunction.com

Any help will be appreciated.

**Comment by jrsakizci** [comment] 2023-12-04 11:54
This issue needs to be fixed asap. Google will hate NextJS projects. How can we fix this issue?

I've migrated my Next App from pages directory to app and this started to happen. When I click cache in google i can see my website for 1 sec and then getting these errors.

**Comment by studentIvan** [comment] 2023-12-06 13:02
@timneutkens this is awful critical issue. At least the next.js site doesn't throw the **Application error: a client-side exception has occurred (see the browser console for more information).** but our own site does. I haven't figure out yet how to opt out this "application cache error feature". This is our site what does. The latest and stable next.js is using https://webcache.googleusercontent.com/search?q=cache:FtWV3LZVkTsJ:https://www.ridestore.se/skidjackor-dam&hl=en&gl=it

@jrsakizci @nitinTJ thank you guys, it's strange the other devs ignore it

**Comment by chk7964** [comment] 2024-01-05 11:27
Facing same issue 
After disable browser javascript then work fine but with Javascript css not apply

**Comment by Cantinaband** [comment] 2024-02-19 12:11
any news about this issue? We facing the same problems....

**Comment by abaracedo** [comment] 2024-02-21 12:40
> After replicating Google webcache site locally to run nextjs in dev mode, I got the following errors:

@Gunt3r-Tp, can you explain how to run it locally? :thinking:

**Comment by mehmetkursataydin** [comment] 2024-02-21 13:47
Maybe there is no more need to this anymore since Google removed caching. https://twitter.com/searchliaison/status/1753156161509916873

**Comment by samcx** [comment] 2024-04-23 21:20
Hi everyone, since Google removed this, I will going ahead with closing this issue.

Feel free to create a new [bug report](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml) if something similar arises!

**Closed by samcx** 2024-04-23 21:20 UTC
Labels: bug, linear: next
