### ISSUE TITLE
Error: Cannot find module 'next/dist/compiled/jest-worker'  - On Docker

### ISSUE THREAD

**Issue by Storxy** [vercel/next.js#48173] opened 2023-04-09 22:03 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Error: Cannot find module 'next/dist/compiled/jest-worker'
Require stack:
- /app/node_modules/next/dist/server/lib/squoosh/main.js
- /app/node_modules/next/dist/server/image-optimizer.js
- /app/node_modules/next/dist/server/next-server.js
- /app/server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/app/node_modules/next/dist/server/lib/squoosh/main.js:8:19)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/next/dist/server/lib/squoosh/main.js',
    '/app/node_modules/next/dist/server/image-optimizer.js',
    '/app/node_modules/next/dist/server/next-server.js',
    '/app/server.js'
  ]
}
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/Storxy/storxy-business-erp

### To Reproduce

Trying to dockerize next application using with docker and the docker file can be found on the repo but it throws an errors when ever I run the containers and visit any page that contain an optimized image while sharp is already been installed and the image not shown

### Describe the Bug

images not working in docker apps

### Expected Behavior

to show optimized image?

**Comment by yassinebridi** [comment] 2023-04-10 01:55
the same issue `next@13.3.0`

**Comment by phongitus** [comment] 2023-04-10 03:50
the same `next@13.0.0`

**Comment by Podfelix** [comment] 2023-04-10 04:20
┌─[zhuxian@zhuxiandeMacBook-Pro] - [~/Documents/projects/learn/next-app] - [Mon Apr 10, 10:03]
└─[$]> next info      

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
    Binaries:
      Node: 16.17.1
      npm: 9.6.2
      Yarn: 1.22.19
      pnpm: 8.1.0
    Relevant packages:
      next: 13.3.0
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.3.0", newest: "13.3.1-canary.3".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

**Comment by kelvin-du** [comment] 2023-04-10 06:53
> 

Try to downgrade `sharp` to `^0.31.3`. It works for me.

**Comment by phongitus** [comment] 2023-04-10 09:50
> > 
> 
> Try to downgrade `sharp` to `^0.31.3`. It works for me.

I've tried 0.31.3 and 0.30.7. Both is not work for me

**Comment by phongitus** [comment] 2023-04-10 10:35
> 

I've tried canary and not work :(  
in both node ver 16 & 17

**Comment by axelhzf** [comment] 2023-04-10 13:23
I am having the same problem, it looks like the bug was introduce in [v13.2.5-canary.27](https://github.com/vercel/next.js/releases/tag/v13.2.5-canary.27). I think the problem was introduced with this https://github.com/vercel/next.js/pull/47788

Previous version, `v13.2.5-canary.26`, works for me.

**Comment by phongitus** [comment] 2023-04-11 07:25
Oh hey, 
we've updated `node18-alpine` in Dockerfile, and next v13.2.4, it works for me.

**Comment by rahul799** [comment] 2023-04-11 07:43
use **next@13.2.4** and the issue will be fixed.

**Comment by OmkoBass** [comment] 2023-04-11 13:52
Downgrade `next` to `13.2.4` and it should work fine. It didn't work for me on `13.3.0`. I've also tried downgrading `sharp` but to no avail.

**Comment by diegoaguilar** [comment] 2023-04-12 01:14
Was this reported as a bug?

**Comment by motopods** [comment] 2023-04-12 01:16
same issue 13.3.1-canary.4

**Comment by nhatncb** [comment] 2023-04-12 12:24
same issue with #48077 and there is a workaround.

**Comment by didemkkaslan** [comment] 2023-04-14 17:52
next `13.2.4` didn't work for me, images are not showing up in production

**Comment by bogoevskid** [comment] 2023-04-16 03:08
Had the same issue with loading images on an app hosted with Amplify and downgrading next to `13.2.4` solved it for me

**Comment by RiccardoBiosas** [comment] 2023-04-18 03:11
I can confirm that downgrading to `next 13.2.4` worked for me (I am using node:18.14.0-alpine as a base docker image)

**Closed** 2023-04-18 11:56 UTC
Labels: template: bug, area: Edge, area: app

**Comment by masterkain** [comment] 2023-04-19 23:16
I also have a weird behavior on the app/favicon.ico beside this one:

```
Error: Cannot find module 'next/dist/compiled/jest-worker'
Require stack:
- /app/node_modules/next/dist/server/lib/squoosh/main.js
- /app/node_modules/next/dist/server/image-optimizer.js
- /app/node_modules/next/dist/server/next-server.js
- /app/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/app/node_modules/next/dist/server/lib/squoosh/main.js:8:19)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/next/dist/server/lib/squoosh/main.js',
    '/app/node_modules/next/dist/server/image-optimizer.js',
    '/app/node_modules/next/dist/server/next-server.js',
    '/app/server.js'
  ]
}
Error: ENOENT: no such file or directory, open '/app/app/favicon.ico'
    at Object.openSync (node:fs:589:3)
    at Object.readFileSync (node:fs:457:35)
    at 6430 (/app/.next/server/app/favicon.ico/route.js:156:38)
    at __webpack_require__ (/app/.next/server/webpack-runtime.js:25:43)
    at __webpack_exec__ (/app/.next/server/app/favicon.ico/route.js:205:39)
    at /app/.next/server/app/favicon.ico/route.js:206:82
    at __webpack_require__.X (/app/.next/server/webpack-runtime.js:138:21)
    at /app/.next/server/app/favicon.ico/route.js:206:47
    at Object.<anonymous> (/app/.next/server/app/favicon.ico/route.js:209:3)
    at Module._compile (node:internal/modules/cjs/loader:1275:14) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/app/app/favicon.ico'
}
```

**Comment by dacitto** [comment] 2023-04-26 14:02
same problem here, images don't work in production after I upgraded next from  **13.1.6** to **13.1.1**

**Comment by Leave-it-blank** [comment] 2023-04-26 17:29
same issue here, images don't work properly with docker or on digital occean app platform

Error: Cannot find module 'next/dist/compiled/jest-worker'
Require stack:
- /app/node_modules/next/dist/server/lib/squoosh/main.js
- /app/node_modules/next/dist/server/image-optimizer.js
- /app/node_modules/next/dist/server/next-server.js
- /app/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/app/node_modules/next/dist/server/lib/squoosh/main.js:8:19)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/next/dist/server/lib/squoosh/main.js',
    '/app/node_modules/next/dist/server/image-optimizer.js',
    '/app/node_modules/next/dist/server/next-server.js',
    '/app/server.js'
  ]
}
Error: Cannot find module 'next/dist/compiled/jest-worker'
Require stack:
- /app/node_modules/next/dist/server/lib/squoosh/main.js
- /app/node_modules/next/dist/server/image-optimizer.js
- /app/node_modules/next/dist/server/next-server.js
- /app/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/app/node_modules/next/dist/server/lib/squoosh/main.js:8:19)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/next/dist/server/lib/squoosh/main.js',
    '/app/node_modules/next/dist/server/image-optimizer.js',
    '/app/node_modules/next/dist/server/next-server.js',
    '/app/server.js'
  ]
}
Error: Cannot find module 'next/dist/compiled/jest-worker'
Require stack:
- /app/node_modules/next/dist/server/lib/squoosh/main.js
- /app/node_modules/next/dist/server/image-optimizer.js
- /app/node_modules/next/dist/server/next-server.js
- /app/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/app/node_modules/next/dist/server/lib/squoosh/main.js:8:19)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/next/dist/server/lib/squoosh/main.js',
    '/app/node_modules/next/dist/server/image-optimizer.js',
    '/app/node_modules/next/dist/server/next-server.js',
    '/app/server.js'

**Comment by MattEagle95** [comment] 2023-05-06 13:17
I got the same error on nextjs **13.4.1** _Error: Cannot find module 'next/dist/compiled/jest-worker'_

**Comment by team172011** [comment] 2023-05-07 11:50
@ijjk  The [README.md](https://github.com/vercel/next.js/tree/canary/examples/with-docker#in-existing-projects) says

> To add support for Docker to an existing project, just copy the Dockerfile into the root of the project and add the following to the next.config.js file:

I think this issue should not be closed until it is fixed for the latest version of nextjs or we should add a version hint to the README. 
Otherwise users will face this problem not just with existing apps > 13.2.4 but also with new created project through `npx create-next-app@latest`

**Comment by wowissu** [comment] 2023-05-08 06:22
Got same error on nextjs 13.3.0, node:18-alpine

```bash
Error: Cannot find module 'next/dist/compiled/jest-worker'
```

**Comment by kyun** [comment] 2023-06-01 14:25
I've just found that my package.json doesn't have `next` dependency.
I've just added `next` on my package.json and it works.

**Comment by diegorafael** [comment] 2023-06-09 13:33
I ran into the exact same problem when I tried adding Docker after creating my app with `npx create-next-app@latest`. The version I had was `13.4.4` at the time. Unfortunately, `13.2.4` wasn't even an option because of some pesky compatibility issues.

My way to make things work was downgrading to version `13.4.0`. Problem solved for now.

**Comment by hydRAnger** [comment] 2023-06-27 06:50
the same issue ```next@13.4.7``` + ```output: 'standalone'```

**Comment by damgel** [comment] 2023-06-27 15:14
> same issue with #48077 and there is a workaround.

I confirm the same problem with this version as well. `next@13.4.7`

**Comment by carlosbaraza** [comment] 2023-07-05 09:18
The problem persists in newer versions @ijjk. Could you reopen the ticket to track it? 13.4.0 works, 13.4.3 doesn't. Somewhere in that diff you can find the regression.

**Comment by viktordanov** [comment] 2023-07-05 18:46
It appears `next@13.4.8` doesn't suffer from the issue, can somebody else confirm this?

**Comment by benmkramer** [comment] 2023-07-05 19:08
> It appears `next@13.4.8` doesn't suffer from the issue, can somebody else confirm this?

I am also seeing this not occur on 13.4.8 in a test deployment this morning.

**Comment by diegorafael** [comment] 2023-07-05 19:46
Same here. Just updated recently to 13.4.8 and that error apparently was fixed 😊

**Comment by diegorafael** [comment] 2023-07-05 19:48
> It appears `next@13.4.8` doesn't suffer from the issue, can somebody else confirm this?

Same here. Just updated recently to 13.4.8 and that error apparently was fixed 😊

**Comment by emrecoban** [comment] 2023-07-07 22:22
I'm stuck.

```bash
Error: Cannot find module '../../next@13.4.8_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/constants.js'
code: 'MODULE_NOT_FOUND',
```

next@13.4.8

**Comment by clarkedb** [comment] 2023-07-10 21:19
> The problem persists in newer versions @ijjk. Could you reopen the ticket to track it? 13.4.0 works, 13.4.3 doesn't. Somewhere in that diff you can find the regression.

There appears to be an even tighter window to find the regressions now because `next@13.4.9` has the same error. As mentioned above `next@13.4.8` works just fine, but the newest patch version `next@13.4.9` yields the old error.

```
Error: Cannot find module 'next/dist/compiled/jest-worker'
Require stack:
- /app/node_modules/next/dist/server/lib/render-server-standalone.js
- /app/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/app/node_modules/next/dist/server/lib/render-server-standalone.js:12:21)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/next/dist/server/lib/render-server-standalone.js',
    '/app/server.js'
  ]
}
```

**Comment by diegorafael** [comment] 2023-07-10 22:49
That's it so. Avoid odd version, guys 🤡

**Comment by skd6150** [comment] 2023-07-11 09:00
It solved after install jest-worker manually

`yarn add jest-worker --save-dev`

**Comment by Clovel** [comment] 2023-07-13 10:43
> > The problem persists in newer versions @ijjk. Could you reopen the ticket to track it? 13.4.0 works, 13.4.3 doesn't. Somewhere in that diff you can find the regression.
> 
> There appears to be an even tighter window to find the regressions now because `next@13.4.9` has the same error. As mentioned above `next@13.4.8` works just fine, but the newest patch version `next@13.4.9` yields the old error.

I actually have the error using both `^13.4.8` and `13.4.8`.

I am currently trying to dockerize my app using the following `next.config.js` :

```js
const path = require('path');

module.exports = {
  reactStrictMode: true,
  output: 'standalone',
  transpilePackages: [
    'ui',
  ],
  eslint: {
    // Warning: This allows production builds to successfully complete even if
    // your project has ESLint errors.
    ignoreDuringBuilds: true,
  },
  // https://nextjs.org/docs/advanced-features/output-file-tracing#caveats
  experimental: {
    // this includes files from the monorepo base two directories up
    outputFileTracingRoot: path.join(__dirname, '../../'),
  },
};
``` 

I have tried commenting the `experimental` section to no avail. 

I am using `turbo@^1.10.7` and the `turbo prune @monorepo/my-app --docker` in the `Dockerfile`

**Comment by Clovel** [comment] 2023-07-13 10:49
> It solved after install jest-worker manually
> 
> `yarn add jest-worker --save-dev`

I tried this too, didn't work for me. 

My config is available in the comment above, tried w/ `13.4.8`, `^13.4.8`, `13.4.9` & `^13.4.9` (I know some of these are equivalent, these tests are just to be thorough)

**Comment by ianldgs** [comment] 2023-07-13 11:21
@Clovel out of curiosity:
do you see a warning about image optimization in the build output?
I'm pretty sure it says something if you don't have `sharp` installed.

There is a "Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production" during startup, but on my project everything works great 🤔  (even with 13.4.9)

**Comment by Clovel** [comment] 2023-07-13 11:41
@ianldgs nope, no warning about `sharp`. Here is my build output using `yarn turbo run build --scope @monorepo/my-app` :

```log
cache miss, executing 2df99f8be5f4d3b5
$ next build
- info Creating an optimized production build...
- info Compiled successfully
- info Skipping linting
- info Checking validity of types...
- info Collecting page data...
- info Generating static pages (0/4)
- info Generating static pages (1/4)
- info Generating static pages (2/4)
- info Generating static pages (3/4)
- info Generating static pages (4/4)
- info Finalizing page optimization...

Route (app)                                Size     First Load JS
┌ ○ /                                      203 B          77.7 kB
├ ○ /client                                827 B           130 kB
└ λ /client/[clientId]                     815 B           130 kB
+ First Load JS shared by all              77.5 kB
  ├ chunks/7d8153d6-536594fdb27ed14b.js    50.5 kB
  ├ chunks/87-5ee5d3c272ad975f.js          25.1 kB
  ├ chunks/main-app-e82e76ea72f8ba20.js    215 B
  └ chunks/webpack-5e9bedb58c3695d7.js     1.71 kB

Route (pages)                              Size     First Load JS
─ ○ /404                                   182 B          75.5 kB
+ First Load JS shared by all              75.4 kB
  ├ chunks/framework-0857c1c24dbfb1d6.js   45 kB
  ├ chunks/main-1ee850a0b31c0d58.js        28.4 kB
  ├ chunks/pages/_app-64f57b430543ef5d.js  194 B
  └ chunks/webpack-5e9bedb58c3695d7.js     1.71 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
```

Am I missing something ?

**Comment by ianldgs** [comment] 2023-07-13 11:45
> Am I missing something ?

No idea... my bet was `sharp` missing.
You do have it btw, right?
On the root package.json or on the app's package.json?
Regular deps or dev deps?

**Comment by ycalm** [comment] 2023-07-24 09:45
> It solved after install jest-worker manually
> 
> `yarn add jest-worker --save-dev`

I'm using `next@13.4.9` and has the same issue, this work for me

**Comment by micktg** [comment] 2023-07-30 00:03
> It solved after install jest-worker manually
> 
> `yarn add jest-worker --save-dev`

This helped me as well. But your command is not correct

Its
`yarn add jest-worker --dev`

`--save-dev` is for npm as far as I know

**Comment by winter-olaf** [comment] 2023-08-05 17:58
> Downgrade `next` to `13.2.4` and it should work fine. It didn't work for me on `13.3.0`. I've also tried downgrading `sharp` but to no avail.

This helped me.

I'm on next@13.2.4 + output: 'standalone' and after downgrading to 13.2.4, it solved.

**Comment by ReynardFox99** [comment] 2023-08-10 02:54
> It solved after install jest-worker manually
> 
> `yarn add jest-worker --save-dev`

worked for me. `next@13.4.7` and `node:18-alpine `
