### ISSUE TITLE
dynamic routes param value is not defined for server side render when literal dynamic route value is provided as the pathname

### ISSUE THREAD

**Issue by tatethurston** [vercel/next.js#17096] opened 2020-09-14 23:29 UTC
# Bug report

## Describe the bug

When using [dynamic routes](https://nextjs.org/docs/routing/dynamic-routes) the `param` value is not defined when navigating to a page whose pathname is the string literal value for the dynamic route. 

From the dynamic routes example:

Given a page defined as `pages/post/[pid].js`, navigating to `/post/[pid]` will _not_ set the `pid` param value for the server side render _if_ `getInitialProps` is defined for the page.

If `getInitialProps` is not provided, then the router correctly extracts the `pid` `param`. When `getInitialProps` is provided, the router does not extract the `pid` param, and the `context` argument for `getInitialProps` will not include `pid` in the `query` attribute. 

Note: This only occurs for the server side render. When navigating client side, everything works as expected.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://3q2nu.sse.codesandbox.io/
2. Click on the `[day]` link
3. Observe the values for `router` and `gIP` (both are `[day]` as expected)
4. Reload the page (https://3q2nu.sse.codesandbox.io/days/[day])
5. Observe the values for `router` and `gIP` (both are `undefined`)

codesandbox: https://codesandbox.io/s/romantic-raman-3q2nu

Note:
Removing `DayPage.getInitialProps` from the sandbox above will cause the `router` value to be correct both when navigating on the client and on the sever side render.

## Expected behavior

The query param value should always be set.

Given a page defined as `pages/post/[pid].js`, navigating to `/post/[pid]` should set the `pid` param value to `[pid]` in both server and client side contexts.

## System information

- OS: [macOs]
- Browser [N/A]
- Version of Next.js: [9.5.3, present on latest]
- Version of Node.js: [12.x]

**Comment by jkjustjoshing** [comment] 2020-11-19 20:14
This issue presents itself a little differently in Next.js v10.0.2 compared to v9.5.3 that this issue was submitted against.

In v9.5.3, this issue only comes up for routes with `getInitialProps`, and does not cause any errors. Routing works as expected client side.
In v10.0.2, this issue *also* comes up for routes that qualify for ASG (no `getX` data loading methods), and causes a 500 error (see my "closed as duplicate" issue, #19296, for screenshot). Routing does *not* work as expected client side, and exhibits the same issue.

@ijjk should this case be added to this issue, or should #19296 be reopened?

**Comment by ijjk** [comment] 2020-11-19 20:38
@jkjustjoshing I think we can keep these issues together since they are related

**Comment by rmsheppard** [comment] 2021-04-23 03:33
I'm having same issue.  When using dynamic routes /pages/account/info/[tab]

When I reload the page as such localhost:3000/account/info/user.  The correct page is displayed however the querystring tab is not passed to the page.  That is at least how I expected it to work.  If I do use the useRouter hook it does provide a router object with the correct querystring params.

**Comment by jkjustjoshing** [comment] 2021-05-13 14:19
@rmsheppard I think you're talking about a different issue. With your example, `pages/account/info/[tab].js`, you would reproduce the bug by going to http://localhost:3000/account/info/[tab]. Any problems with any other URL is out of scope for this ticket.

**Comment by sb-saksham** [comment] 2021-09-27 06:01
Any updates on this issue? Experiencing it on NextJS v11.1.2

**Closed** 2022-02-02 02:57 UTC
Labels: kind: bug, type: needs investigation, area: Routing
