### ISSUE TITLE
Handling failed dynamic imports

### ISSUE THREAD

**Issue by realestninja** [vercel/next.js#10495] opened 2020-02-11 17:29 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Example: A website with lazy loading components. While scrolling down, your mobile internet might be cut off. Once you get to the bottom, parts of the website won't be displayed because fetching the chunks failed. Those components will remain stuck in their loading state, even when internet connectivity is back.

## Describe the solution you'd like

In our case we would like to catch the error and maybe display an error message and also a button that lets users try again on fetching the chunks.

```
const DynamicComponent = dynamic(
  () => import("../../components/DynamicComponent"),
  { 
    loading: () => <span>loading...</span>,
    errorMsg: () => <span>Network interruption detected</span>,
    retry: () => <button>Try again</button>,
  },
);
```

## Additional context

![2020-02-11_18-01](https://user-images.githubusercontent.com/17706747/74260812-75cb1580-4cfa-11ea-91e3-78d18dcab3b5.png)

**Comment by Janpot** [comment] 2020-02-11 19:04
Wouldn't this work?
```jsx
const DynamicComponent = dynamic(() => {
  return import("../../components/DynamicComponent")
    .catch(() => <span>Network interruption detected</span>)
});
```

**Comment by realestninja** [comment] 2020-02-13 09:42
> Wouldn't this work?
> 
> ```js-jsx
> const DynamicComponent = dynamic(() => {
>   return import("../../components/DynamicComponent")
>     .catch(() => <span>Network interruption detected</span>)
> });
> ```

This works and is a nice way to get out of the loading state and show an error.

I'm still looking for a solution for fetching the chunk/chunks after it has failed.

**Comment by Janpot** [comment] 2020-02-13 09:54
@realestninja I'm not 100% sure whether dynamic import caches failures, but I'd expect something like the following to work:
```jsx
async function withRetryAndFallback (asyncFn, fallback) {
  try {
    return await asyncFn();
  } catch (err) {
    try {
      // retry
      return await asyncFn();
    } catch (err) {
      return fallback(err);
    }
  }
}

const DynamicComponent = dynamic(withRetryAndFallback(
  () => import("../../components/DynamicComponent"),
  () => <span>Network interruption detected</span>
), {
  loading: () => <span>Loading...</span>
});
```

**Comment by Timer** [comment] 2020-09-10 18:27
Closing due to answer given above.

**Closed by Timer** 2020-09-10 18:27 UTC

**Comment by balazsorban44** [comment] 2022-01-29 13:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
