### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by pablolucio97** [vercel/next.js#26055] opened 2021-06-13 19:36 UTC
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

I'm trying to get the current url of the page to render conditionally a React component, but the object window is like undefined.

### Expected Behavior

Return the current url, example: http://localhost:3000/library.

### To Reproduce

```
import {ChangeEvent} from 'react'
import {
    Container,
    MenuContainer,
    Search,
} from './styles'

type SearchProps = {
    search?: (e: ChangeEvent<HTMLInputElement>) => void;
}

const Index = ({search} : SearchProps) => {

    const currentUrl = window.location.href
    
    return (
        <Container>
            <MenuContainer>
                {currentUrl === 'http://localhost:3000/library' ?  null 
                : <Search placeholder='find a game' onChange={search} />}
            </MenuContainer>
        </Container>
    )
}

export default Index;

**Comment by gdavidetanca** [comment] 2021-06-13 20:08
Not a bug, the **window** object is not available server-side, you need to check if your code is running client-side, for example: 

`if (typeof window != 'undefined') {
    // Client side
}`

However, I suggest you to use **'next/router'** to do anything related to routing in Next: https://nextjs.org/docs/api-reference/next/router

**Comment by pablolucio97** [comment] 2021-06-13 21:04
Thanks man.

I solved it using useRouter.

**Comment by ats1999** [comment] 2021-06-14 00:23
@pablolucio97 
Close the issue, if it resolved!

**Closed** 2021-06-14 01:14 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
