### ISSUE TITLE
Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Middleware pages/_middleware with apollo graphql

### ISSUE THREAD

**Issue by vadimsabadosh** [vercel/next.js#32532] opened 2021-12-15 11:07 UTC
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

Google Chrome 96.0.4664.93

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

I have this code in _middleware.ts to check URL validation using graphql.
![image](https://user-images.githubusercontent.com/72106830/146174688-2fb12423-360f-4a4d-8cd6-fb5c15f87efb.png)

Whenever I use "next start" it works fine, but whenever I use "next build" I get the error:
Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Middleware pages/_middleware

### Expected Behavior

I want to use graphql requests in middleware. What do I need to change?

### To Reproduce

1. Create a project with graphql
2. Create middleware.ts with graphql request and put variables into a request.
3. Run "npm run build" or "next build"
4. Get an error

**Comment by balazsorban44** [comment] 2021-12-15 12:48
Duplicate of #31694

**Closed by balazsorban44** 2021-12-15 12:48 UTC
Labels: template: bug

**Comment by vadimsabadosh** [comment] 2021-12-17 15:01
> Duplicate of #31694

I'm not sure about duplicate

I'm still having the issue even if I don't use anything in the middleware

![image](https://user-images.githubusercontent.com/72106830/146563877-6b44a382-8470-40dc-95bf-f0a30c0b6dd5.png)
![image](https://user-images.githubusercontent.com/72106830/146563949-c5be0baf-aa2a-4c73-b76c-59e2ea00d038.png)

**Comment by balazsorban44** [comment] 2022-01-27 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
