### ISSUE TITLE
If you deploy to Vercel, the API using node-canvas will not work.

### ISSUE THREAD

**Issue by Gullinkambi-Whip** [vercel/next.js#27228] opened 2021-07-16 13:09 UTC
### What version of Next.js are you using?

latest

### What version of Node.js are you using?

14.15.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

The API to generate og:image, which works on localhost (yarn dev), shows a 500 error when deployed to Vercel.  
The API uses [node-canvas](https://github.com/Automattic/node-canvas).

### Expected Behavior

I expect the API to work on pages deployed to Vercel, just as it works on localhost.

### To Reproduce

[Repository](https://github.com/Gullinkambi-Whip/with-typescript-app)  
[Deployed page](https://with-typescript-app-theta.vercel.app/foo)  
[API](https://with-typescript-app-lah1wlb6n-gullinkambi.vercel.app/api/foo/ogimage)

1. Clone the above repository
2. Run ```npm i``` or ```yarn```
3. ```./pages/[pageID].tsx```
```tsx
const MyPage: VFC<PageStaticProps> = ({ page }) => {
  const ogpImage = `${dev}/api/${page.pageID}/ogimage`; // Chage ${prod} to ${dev}
  ...
```
4. Run ```yarn dev```
5. Run the API and make sure that og:image is generated(```http://localhost:3000/api/foo/ogimage```)
<img src="https://user-images.githubusercontent.com/78286433/125952304-f026c479-feef-4d4c-9486-adbffb363cf0.JPG" width="300">

6. ```./pages/[pageID].tsx```
```tsx
const MyPage: VFC<PageStaticProps> = ({ page }) => {
  const ogpImage = `${prod}/api/${page.pageID}/ogimage`; // Chage ${dev} to ${prod}
  ...
```
7. Deploy it and run the API to confirm that it displays a 500 error.

**Comment by styfle** [comment] 2021-07-27 14:47
See this issue: https://github.com/vercel/vercel/issues/3460

**Comment by ijjk** [comment] 2021-09-21 04:46
Closing in favor of above mentioned issue

**Closed by ijjk** 2021-09-21 04:46 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
