### ISSUE TITLE
Docs: Folder name should be @authModal not @auth 

### ISSUE THREAD

**Issue by MaherSaleem** [vercel/next.js#53102] opened 2023-07-24 10:21 UTC
### What is the improvement or update you wish to see?

On this page https://nextjs.org/docs/app/building-your-application/routing/parallel-routes

the image shows @auth, but down it shows @authModal. it confused me for a min why they're different
![image](https://github.com/vercel/next.js/assets/14930756/db13b62b-3f84-483e-ab50-1e15d2b2cb00)

### Is there any context that might help us understand?

We have to update the image to have @authModal as a folder name

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/routing/parallel-routes

**Comment by balazsorban44** [comment] 2023-07-24 10:26
Duplicate of #52037

**Closed by balazsorban44** 2023-07-24 10:26 UTC
Labels: template: documentation
