### ISSUE TITLE
Error occurred when using dynamic routing and Rewrite together

### ISSUE THREAD

**Issue by shu1007** [vercel/next.js#26074] opened 2021-06-14 12:31 UTC
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

I'm using rewrites to access a page with dynamic routing, using the Link component.
It is possible to go to the target page with a click. However, when I go back or forward in the browser, an following error occurs.
This error does not occur until 10.2.0, and is seen in 10.2.1 and later versions.
```
Error: The provided `as` value (/foo) is incompatible with the `href` value (/[slag1]/[slag2]/foo).
```

### Expected Behavior

?

### To Reproduce

I wrote the following sample code in code sandbox.
Please try the following steps for each.
1.  Click on Foo
2. Go back in the browser
3. Go forward in the browser

- [error (latest)](https://codesandbox.io/s/rewrite-and-link-latest-nef4w)
- [no error (10.2.0)](https://codesandbox.io/s/rewrite-and-link-1020-0f31t)

**Comment by myteax** [comment] 2021-06-14 13:40
I will like to work on this.

**Comment by myteax** [comment] 2021-06-14 14:11
This is what I did to solve the error:

https://1bxb9.sse.codesandbox.io/

**Comment by shu1007** [comment] 2021-06-14 14:23
Thanks for the quick response!

The point is to rewrite the url, we want to have access with /foo.
And the structure of pages remains unchanged.

**Comment by myteax** [comment] 2021-06-14 14:39
ok, I get you, I really do not understand your project 100% and why you have those dynamic paths [folder]. What I did now was to take out the foo.js and put in the page folder and then it works. Again, this might not be what you want to achieve as I really do not  have more information about the project. Another way to do that is :
import Link from "next/link";

export default function IndexPage() {
  return (
    <div>
      <Link href="/[foo]" as="/foo">
        <a>Foo</a>
      </Link>
    </div>
  );
}

That will disable the backward and forward button. Then you can add a button to go back; which will lead directly to the home page.

**Comment by shu1007** [comment] 2021-06-14 14:57
Thank you.
Talking about my project a bit, I want to provide multiple services from a common code. One service will have branches with dynamic routing and another service will not have those branches.
The actual code is much larger and more complex, and rewrite was helpful in building them with minimal changes. However, when I upgraded the next version, it stopped working, so I wrote an issue.

**Comment by ijjk** [comment] 2021-06-14 15:03
Closing as this is fixed in `v10.2.4-canary.2` of Next.js, specifically in https://github.com/vercel/next.js/pull/25666 and https://github.com/vercel/next.js/pull/25495

**Closed by ijjk** 2021-06-14 15:03 UTC
Labels: template: bug

**Comment by PsyGik** [comment] 2021-06-23 07:09
Will this fix land in Next 11 or a minor version of 10?

**Comment by shu1007** [comment] 2021-06-23 07:18
It's working correctly in Next 11

**Comment by balazsorban44** [comment] 2022-01-28 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
