### ISSUE TITLE
`yarn storybook` stuck when using `styled-jsx-plugin-less`

### ISSUE THREAD

**Issue by yoongti** [vercel/next.js#19058] opened 2020-11-11 15:09 UTC
# Bug report

## Describe the bug

`yarn storybook` will stuck at 69% using together with `styled-jsx-plugin-less`.

It works fine with `styled-jsx-plugin-sass`.

I have created a demo linked down below.

## To Reproduce

1. `git clone https://github.com/yoongti/nextjs-storybook.git`
2. `yarn install`
3. `yarn storybook`
4. Build stuck at 69%

## Expected behavior

It should build successfully and launch Storybook on browser.

## Screenshots

![image](https://user-images.githubusercontent.com/15006252/98828169-b5ce4d00-2472-11eb-9c2b-5a2917330fde.png)

## System information

- OS: macOS Catalina
- Browser: Chrome 86.0.4240.193
- Version of Next.js: 10.0.1
- Version of Node.js: 12.19.0

## Additional context

None.

**Comment by radekmikeska** [comment] 2020-11-15 23:31
The difference between those two plugins is that _less_ is trying to be async. It uses https://github.com/abbr/deasync to achiev it but this library has some troubles on newer versions of Node.js. For me it does not work on node 14 nor 12 but the build passes on version 10.

Thus your problem can be solved by switching to Node 10 LTS or using your own plugin - https://github.com/vercel/styled-jsx#css-preprocessing-via-plugins. For me this piece of code works - it is copied from that plugin and rewritten to be sync.

```javascript
const less = require("less");

module.exports = (css, settings) => {
    const cssWithPlaceholders = css
        .replace(
            /\:\s*%%styled-jsx-expression-(\d+)%%/g,
            (_, id) => `: styled-jsx-expression-${id}()`
        )
        .replace(
            /%%styled-jsx-expression-(\d+)%%/g,
            (_, id) => `/*%%styled-jsx-expression-${id}%%*/`
        );

    let result;

    less.render(cssWithPlaceholders, settings, (error, output) => { result = output.css });

    return result.replace(
            /\:\s*styled-jsx-expression-(\d+)\(\)/g,
            (_, id) => `: %%styled-jsx-expression-${id}%%`
        )
        .replace(
            /\/\*%%styled-jsx-expression-(\d+)%%\*\//g,
            (_, id) => `%%styled-jsx-expression-${id}%%`
        );
};
```

**Comment by JanKaifer** [comment] 2022-11-24 14:31
Hey, It looks like there is not much we can do in next.js (looks like `node` - `styled-jsx-plugin-less` issue).
I'll close this issue, but feel free to open a new one if this issue is caused by next.js.

**Closed by JanKaifer** 2022-11-24 14:31 UTC
Labels: good first issue
