### ISSUE TITLE
Passing args in URL with `experimental.basePath` causes the page to constantly being reloaded.

### ISSUE THREAD

**Issue by robertovg** [vercel/next.js#13132] opened 2020-05-20 10:16 UTC
# Bug report

## Describe the bug

We are using next: "^9.4.1" in a project with `experimental.basePath` and when working with the project on development and we have params on URL the page constantly reloads making impossible to work on dev mode.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

I generated a simple [repo](https://github.com/robertovg/next-base-path-example) & [code-sandbox](https://codesandbox.io/s/github/robertovg/next-base-path-example) to show the problem. 
- Contains a basepath set to `myPath`
- Only contains a simple `index` page with a link to add params to the URL,

When you load the visit the project with params: [Live Sandbox](https://1mzx6.sse.codesandbox.io/myPath) and click on the link, o directly go to the URL with params on the [URL](https://1mzx6.sse.codesandbox.io/myPath?reloadsWithAnyParam=true)

The page loads correctly, but after a second it starts to reload from time to time.

If no params in the URL or `experimental.basePath` set, it works like as expected.

## Expected behavior

I would like to work with `experimental.basePath` without unexpected page reloads.

## Additional context

Obviously this is an experimental feature based on this [PR](https://github.com/zeit/next.js/pull/9872) but we will need sooner than later in our projects.

Thanks in advance 🙏

**Comment by ijjk** [comment] 2020-05-20 15:14
Hi, it looks like you are setting both `assetPrefix` and `basePath` to the same path [here](https://github.com/robertovg/next-base-path-example/blob/a8fd7cde020551a4d19f272941f217b8abd113a3/next.config.js#L5-L70). You only need to set `basePath` in this case since `/_next` requests will automatically be prefixed with the `basePath`

**Comment by DrUNE** [comment] 2020-05-20 15:52
Hi, I think this is related problem https://github.com/zeit/next.js/issues/11992#issuecomment-621974763 here basePath used instead assetPrefix. Problem surface when basePath and assetPrefix used at the same time in the project for generating SSG for example for static site which need basePath for routing prefixes and the same time all static assets should be hosted on another domain or CDN

**Comment by robertovg** [comment] 2020-05-20 16:59
> Hi, it looks like you are setting both `assetPrefix` and `basePath` to the same path [here](https://github.com/robertovg/next-base-path-example/blob/a8fd7cde020551a4d19f272941f217b8abd113a3/next.config.js#L5-L70). You only need to set `basePath` in this case since `/_next` requests will automatically be prefixed with the `basePath`

Yeah, but in our real case, we are routing this next.js application through `Traefik` through the same `base_path`, and we need both the app and the assets to be served inside the same base_path.
That's why we need to change both.

**Comment by designbyadrian** [comment] 2020-05-20 17:30
I'm having the same issue without setting assetPrefix. I'm trying to narrow down the problem.

**Comment by tywmick** [comment] 2020-05-27 18:44
Okay this is weird: after cloning @robertovg's [repo](https://github.com/robertovg/next-base-path-example), I experience those same reloading issues when I `yarn dev`, but when I `yarn build && yarn start`, going to `http://localhost:3000/myPath?reloadsWithAnyParam=true` no longer causes reloading.

I then thought that it must be a server-side rendering issue, but then I tried adding a `getServerSideProps()` to `src/pages/index.js`...

```js
export async function getServerSideProps(context) {
  return {
    props: {},
  };
}
```

...and after `yarn build` confirmed for me that the index page would be server-side rendered at runtime, I still experienced no reloading issues after `yarn start` and visiting `http://localhost:3000/myPath?reloadsWithAnyParam=true`. So I am *only* experiencing the reloading bug in dev mode, regardless of how the page is rendered. 🤔

**Comment by tywmick** [comment] 2020-05-28 20:37
Found which reload we're dealing with:

https://github.com/vercel/next.js/blob/ad145d347f7fed2b8200708d1f9d2040e71da07c/packages/next/client/dev/on-demand-entries-utils.js#L37

Continuing to investigate around there...

**Comment by julian-sf** [comment] 2020-06-08 17:10
Also, looks like Kodiak might have accidentally closed this issue?

**Closed** 2020-06-08 17:53 UTC
Labels: good first issue, kind: bug, type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-30 02:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
