### ISSUE TITLE
Bug: List items duplication in the with-Apollo example setup using GetStaticProps

### ISSUE THREAD

**Issue by felixmeziere** [vercel/next.js#19759] opened 2020-12-02 19:36 UTC
# Bug report

## Describe the bug

The Apollo Client's cache arrays get filled with duplicated items when using the setup provided in `examples/with-Apollo`, leading to my website displaying lists with twice (or even 3, 4... etc) times each item (and getting the infamous react duplicated key error, obviously 🙂).

## To Reproduce

1. Implement the `examples/with-Apollo` setup in a project where the schema has an array of items (a Relay connection field for example).
2. On a Next.js page (Page 1), make an apollo `useQuery` fetch the list of items and display it.
3. Add a GetStaticProps to the page, following exactly the with-Apollo example
4. In another page of the project (Page 2), create a link navigating to this page.
5. Run the project, go to Page 2. Click the button that takes you to Page 1.
6. Navigate back to Page 2 with back arrow of your browser. Open your console.
7. Navigate forward to Page 1 again. See the duplicated items and error messages about duplicate keys in your console.
8. If you repeat this operation x times, you will see the items repeated x times.

```jsx
HOSTING_SEARCH_HOSTING_PROVIDERS = gql`
query HostingSearchHostingProviders {
    bookableHostingProviders {
      edges {
        node {
          id
          name
        }
      }
    }

const Page = ()=> {
  const { data, error, loading } = useQuery(HOSTING_SEARCH_HOSTING_PROVIDERS);

  return <>{data.bookableHostingProviders.edges.map(edge => <div key=>{edge.node.name} {edge.node.id}</div>)}</>
}

export const getStaticProps = async () => {
  const apolloClient = initializeApollo();

  await apolloClient.query({
    query: HOSTING_SEARCH_HOSTING_PROVIDERS,
  });

  return addApolloState(apolloClient, {
    props: {},
    revalidate: 20,
  });
};

export default Page
```

## Expected behavior

The elements of the array are not duplicated and I don't see duplicated key error messages in my console.

## Screenshots

![image](https://user-images.githubusercontent.com/11617630/100920087-8be8d300-34d2-11eb-8d13-7a0fb781b86d.png)

## System information

- OS: macOS
- Browser: all
- Version of Next.js: 10.0.0
- Version of Node.js: 12.16.2
- Deployment: Vercel and `next dev`

## Likely solution

I **think** that the problem comes from the fact that the official example uses [deepmerge](https://github.com/TehShrike/deepmerge) in a way that is not OK for the use case (the use case being to merge the client cache into the server cache).
By default, and as used in the `with-apollo` example, `deepmerge` concatenates arrays when trying to merge 2 arrays at the same key of an object (this is why, when I repeat the manipulation x times, the list has been concatenated x times).
I **guess** that the expected behaviour here would be that the array coming from the client cache would *overwrite* the array from the server cache, but I'm really not sure as I'm not expert enough in terms of the apollo internals here.

`deepmerge` has a way to overwrite instead of concatenating in their docs so I guess this is quite common:

![image](https://user-images.githubusercontent.com/11617630/100922904-5219cb80-34d6-11eb-9c0a-d69d9260883c.png)

So, moving the use of `deepmerge` from 

```ts
if (initialState) {
    // Get existing cache, loaded during client side data fetching
    const existingCache = _apolloClient.extract();

    // Merge the existing cache into data passed from getStaticProps/getServerSideProps
    const data = merge(initialState, existingCache);

    // Restore the cache with the merged data
    _apolloClient.cache.restore(data);
  }
```

to

```ts
if (initialState) {
    // Get existing cache, loaded during client side data fetching
    const existingCache = _apolloClient.extract();

    // Merge the existing cache into data passed from getStaticProps/getServerSideProps
    const data = merge(initialState, existingCache, {
      arrayMerge: (destinationArray, sourceArray) => sourceArray,
    });

    // Restore the cache with the merged data
    _apolloClient.cache.restore(data);
  }
```

in the `with-apollo` example code fixes the issue for me. However I struggle to understand if this is going to have adverse consequences for other use cases.

Could someone that had something to do with the `with-apollo` example examine this and give me their thoughts please?

Thanks a lot! ❤️

**Comment by felixmeziere** [comment] 2020-12-04 08:04
I've made a PR that fixes this (though needs to be double-checked by someone from with-apollo example) https://github.com/vercel/next.js/pull/19812

**Comment by stephent** [comment] 2020-12-05 01:32
It seems this bug was already addressed in the with-apollo-and-redux example, using the following approach:

```
import isEqual from 'lodash/isEqual'
...

const data = merge(initialState, existingCache, {
      arrayMerge: (destinationArray, sourceArray) => [
        ...sourceArray,
        ...destinationArray.filter((d) =>
          sourceArray.every((s) => !isEqual(d, s))
        ),
      ],
    })
```

**Comment by felixmeziere** [comment] 2020-12-09 19:32
@stephent Amazing! Thanks for the tip!

**Comment by felixmeziere** [comment] 2020-12-09 19:33
Can someone from Next confirm this please?

**Closed** 2020-12-09 23:35 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-29 01:24
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
