### ISSUE TITLE
[next/image] On IE11, with layout="responsive" | "fill" + sizes prop, object doesn't support property "matchAll"

### ISSUE THREAD

**Issue by adrienharnay** [vercel/next.js#24473] opened 2021-04-26 14:27 UTC
### What version of Next.js are you using?

10.1.3, also tried 10.1.4-canary.16

### What version of Node.js are you using?

14.15.0

### What browser are you using?

IE11

### What operating system are you using?

Windows 10

### How are you deploying your application?

next start, locally

### Describe the Bug

On IE11, when using `<Image layout="responsive" />` (or fill) in addition to the `sizes` prop, I get the following error:

`Object doesn't support property "matchAll"`

The stacktrace points to this code:

```
function(e,t,r){if(r&&("fill"===t||"responsive"===t)){var n=o(r.matchAll(/(^|\s)(1?\d?\d)vw/g)).map(
```

If I remove the `sizes` prop, no error occurs.

### Expected Behavior

The docs state that "Next.js supports IE11 and all modern browsers (Edge, Firefox, Chrome, Safari, Opera, et al) with no required configuration.".

### To Reproduce

```
        <Image
          src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/golden-retriever-royalty-free-image-506756303-1560962726.jpg?crop=0.672xw:1.00xh;0.166xw,0&resize=640:*"
          layout="fill"
          sizes="
              (min-width: 85.375rem) 17.5rem,
              (min-width: 64rem) 25vw,
              (min-width: 37.5rem) 50vw,
              100vw
           "
        />
```

next build
next start

**Comment by shuding** [comment] 2021-04-29 11:53
Closing as fixed by #24569.

**Closed by shuding** 2021-04-29 11:53 UTC
Labels: template: bug

**Comment by adrienharnay** [comment] 2021-04-29 11:57
Thank you so much 🙏

**Comment by balazsorban44** [comment] 2022-01-28 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
