### ISSUE TITLE
When using a function from the page you are on, next crashes sometimes

### ISSUE THREAD

**Issue by reckter** [vercel/next.js#39127] opened 2022-07-28 09:43 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

(See Stackblitz);
- Current (and canary) nextjs version

### Describe the Bug

Under certain circumstances, nextjs crashes on reloading on a page.

- The page exports an additional function (`getTestpageLink()` in the Stackblitz)
- This function imports another function from a different file (`someFunction()` in the Stackblitz)
- The Page somewhere uses a Component, that uses `getTestpageLink()`, BUT uses it in the toplevel of the file, not the components. (I don't know how to describe this better, see `Layout.tsx` in the Stackblitz.)

Now when reloading the Webpage while on said page, nextjs crashes with `TypeError: Cannot read properties of undefined (reading 'someFunction')`.

It does not crash while first navigating to the page.
There is no Typescript or Build error, but it also crashes on a production build.

### Expected Behavior

It doesn't crash

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-ttqpuc?file=pages%2Ftestpage.tsx,Layout.tsx,pages%2Findex.tsx,package.json

### To Reproduce

(This is the same setup as the StackBlitz above)

```ts
// pages/testpage.tsx
import React from 'react';
import { Layout } from '../Layout';
import { someFunction } from '../util';

export default function Page() {
  return <Layout>"This is a page"</Layout>;
}

export function getTestpageLink() {
  return {
    pathname: '/testpage',
    query: {
      // This breakes, whenver the Page above uses `Layout` somewhere.
      foo: someFunction(),
    },
  };
}

```

```ts
// Layout.tsx
import Link from 'next/link';
import { getTestpageLink } from './pages/testpage';

// If this is "inlined" into the Component below it works
const link = getTestpageLink();

export function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <div>
        <Link href={link}>testPage</Link>
      </div>
      <div>{children}</div>
    </div>
  );
}
```

```ts
// util.ts
export function someFunction() {
  return '/testpage';
}
```

Now go to `/testpage`, it should crash.
When you add an `Index.tsx` with a link to testpage, navigating there should work fine, until you reload.

**Comment by JanKaifer** [comment] 2023-01-18 16:55
Closing as duplicate of https://github.com/vercel/next.js/issues/22283
I think the issues is that you are using cyclic imports.

**Closed by JanKaifer** 2023-01-18 16:55 UTC
Labels: template: bug
