### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by dincerpece** [vercel/next.js#52150] opened 2023-07-03 20:40 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.8
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

i am running my project on big localhost

### To Reproduce

![Screenshot_3](https://github.com/vercel/next.js/assets/57527680/ebf8b4e4-107d-4967-b9db-947ba259f5d3)
![Screenshot_4](https://github.com/vercel/next.js/assets/57527680/c7cd89c3-1a0f-4e11-9c13-18aaf9920342)

### Describe the Bug

I get an error on next custom server both in production and development mode for nextjs 13.4.7 and later.

### Expected Behavior

I expect it to work normally on my nextjs custom server like next dev and next start. 13.4.6 works fine on 13.4.7 and later I get this error.

### Which browser are you using? (if relevant)

Chrome 114.0.5735.199

### How are you deploying your application? (if relevant)

localhost, next custom server

**Comment by oriolgm** [comment] 2023-07-03 21:47
I got this error too,  I was able to fix it by changing host from localhost to 127.0.0.1 while creating the app on the custom server, but it seemed to me a breaking change.

**Comment by schimi-dev** [comment] 2023-07-04 08:13
It seems that this problem occurrs since the below pull request that was added in [v13.4.7-canary.0](https://github.com/vercel/next.js/releases/tag/v13.4.7-canary.0):
https://github.com/vercel/next.js/pull/51378

It seems that some part of the application's IPC still tries to use IPv6 if localhost resolves to an IPv6 address but cannot do so (for a reason I don't understand). In the [Pull Request](https://github.com/vercel/next.js/pull/51378) the  IP address used for IPC was locked to 0.0.0.0, so my understanding is that this issue occurrs when localhost resolves to an IPv6 address while IPC seems locked to IPv4. You can see in your log that the address in your case  is an IPv6 address.

Setting the HOSTNAME environment variable to an IPv4 address solves this problem, but I think that this might be something that is worth looking into by the maintainers.

Best regards,

Michael

**Comment by schimi-dev** [comment] 2023-07-04 08:28
Moreover, this issue seems related to: [https://github.com/vercel/next.js/issues/51684](https://github.com/vercel/next.js/issues/51684)

**Comment by dincerpece** [comment] 2023-07-04 11:40
Yes, on my custom server, when I set the hostname to 127.0.0.1, I was able to connect with localhost.Thanks.
![Screenshot_5](https://github.com/vercel/next.js/assets/57527680/2eadf530-cce0-420d-a9ba-6dfe1cad2124)

**Comment by vinceve** [comment] 2023-07-04 14:52
Even without a custom server and/or https it is occuring.

**Comment by michaelangrivera** [comment] 2023-07-05 12:50
> Yes, on my custom server, when I set the hostname to 127.0.0.1, I was able to connect with localhost.Thanks. ![Screenshot_5](https://user-images.githubusercontent.com/57527680/250890696-2eadf530-cce0-420d-a9ba-6dfe1cad2124.png)

I don't think setting it to `127.0.0.1` is the solution. What about when you deploy it? How will it bind to `0.0.0.0`?

**Comment by dincerpece** [comment] 2023-07-06 02:42
If I connect with ip in local, it works naturally, even though it gives a certificate problem with 127.0.0.1. localhost is already fine. I don't have any problems on the server side either. This is fixed anyway, as a temporary solution, at least I can work like this right now.

**Comment by balazsorban44** [comment] 2023-07-06 12:08
I'll close it as a duplicate of #51684 which we already track internally. Follow that thread for updates, and leave comments there, thanks!

**Closed by balazsorban44** 2023-07-06 12:08 UTC
Labels: template: bug
