### ISSUE TITLE
Swc causing error in production. Related to citation-js and citeproc.

### ISSUE THREAD

**Issue by igloo1505** [vercel/next.js#69150] opened 2024-08-21 16:45 UTC
### Link to the code that reproduces this issue

https://github.com/igloo1505/ulldApp

### To Reproduce

I'm building two separate but related projects that are intended to work together. One is a large monorepo, the other is a single Next app currently on 14.2.5. You can clone the single app at the repo [here](https://github.com/igloo1505/ulldApp), but it will require an `appConfig.ulld.json` file at the root of that project that would look something like 
[appConfig.ulld.json](https://github.com/user-attachments/files/16695344/appConfig.ulld.json) to build and run without blowing up.

### Current vs. Expected behavior

The app would produce an error that was related to one of `citation-js`'s dependencies, `citeproc` which was apparently generated by swc. It ran flawlessly in development, but output this error in production:

```
TypeError: Cannot read properties of undefined (reading 'name')
    at t.XmlJSON.addMissingNameNodes (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/chunks/34354.js:17:43244)
    at new t.Engine (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/chunks/34354.js:17:67469)
    at u (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/chunks/34354.js:1:373946)
    at c (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/chunks/34354.js:1:374213)
    at bibliography (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/chunks/34354.js:1:374923)
    at tl (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/chunks/34354.js:1:28027)
    at g.tm [as format] (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/chunks/34354.js:1:28107)
    at d (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/chunks/34354.js:17:2746)
    at async v (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/app/api/events/onSync/route.js:1:12672)
    at async /Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36258
```

Disabling swc with `swcMinify: false` resolved the issue, but I'm posting here so that you're aware for `next@15.x.x` when that option won't be available. 

There was a related issue submitted by the `citation-js` author [here](https://github.com/vercel/next.js/issues/48731#issue-1679757939), but it was close due to inactivity.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 22.4.1
  npm: 10.8.1
  Yarn: 4.3.1
  pnpm: 9.7.1
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.2.5
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Runtime, SWC

### Which stage(s) are affected? (Select all that apply)

next build (local), next start (local)

**Comment by jonluca** [comment] 2024-08-23 20:02
![CleanShot 2024-08-23 at 12 59 33@2x](https://github.com/user-attachments/assets/86262fa3-8831-48b1-bc85-62f5a8c2fb8d)

We're also seeing this issue as well for what its worth. Disabling `swcMinify` fixes it.

**Comment by darthmaim** [comment] 2024-08-23 20:15
@jonluca The `invalid unicode point` error is caused by Node.js 22.7.0, downgrading to Node.js 22.6.0 fixes that error. This is not caused by Next.js.

**Comment by jonluca** [comment] 2024-08-23 20:17
That would do it! thanks @darthmaim

**Comment by RaenonX** [comment] 2024-08-24 03:16
> @jonluca The `invalid unicode point` error is caused by Node.js 22.7.0, downgrading to Node.js 22.6.0 fixes that error. This is not caused by Next.js.

This is a life saver because all my new builds are failing deterministically and I am scrathcing head finding the root cause, only to notice that it's node new version release breaking it.

I have filed https://github.com/nodejs/node/issues/54532 so hopefully node.js team can fix it.

**Comment by ncostaramos** [comment] 2024-08-28 13:44
Got Tenser errors with node.js -v 22.7.0.

No error when using node.js -v 20.17.0.

**Comment by kdy1** [comment] 2024-08-29 03:52
Did you try the latest canary?

**Comment by kdy1** [comment] 2024-08-30 01:55
I can't run your repro because of `ulldBuildData.json"`.

**Comment by crazyWolf-cz** [comment] 2024-09-04 05:44
Node 22.8. fixed this 🥳

**Comment by lightify97** [comment] 2024-09-15 10:18
@crazyWolf-cz Just experienced this with v22.8.0 (Next v14.2.11)

**Comment by kdy1** [comment] 2024-09-20 04:36
Can you try 15 canary? I couldn't backport the SWC minifier because of some Rust-side restrictions related to swc_core, but those issues should be fixed already in the upstream.

**Closed** 2024-11-14 18:45 UTC
Labels: bug, SWC, Runtime, linear: next
