### ISSUE TITLE
Context object is undefined in handleRouteChange

### ISSUE THREAD

**Issue by Gh05d** [vercel/next.js#20745] opened 2021-01-04 17:38 UTC
**What version of Next.js are you using?**

10.0.3

**What version of Node.js are you using?**

12.18.2

**What browser are you using?**

Firefox

**What operating system are you using?**

Ubuntu

**How are you deploying your application?**

next start

**Describe the Bug**

I basically tried to follow the example here: https://nextjs.org/docs/api-reference/next/router#usage-6 to the point. When the handleRouteChange listener fires, the app crashes with this error message:

`Uncaught (in promise) TypeError: _ref is undefined`

The problem is that the destructored object which contains the shallow property is undefined. Changing it from `const handleRouteChange = (url, { shallow }) => {` to `const handleRouteChange = (url, ctx) => {` fixed the issue. So basically the docs should be updated.

**Expected Behavior**

The console log from the example should fire.

**To Reproduce**

Copy the example from the above mentioned link and try to execute a route change.

``

**Comment by ijjk** [comment] 2021-01-04 19:47
Hi, I'm not able to reproduce this on the latest version of Next.js `v10.0.4` (or `10.0.5-canary.9`), this value should not be `undefined` as it is set to an object [here](https://github.com/vercel/next.js/blob/fc75baeb3c42e83ebed3d08e05ef06fb50a2d17b/packages/next/next-server/lib/router/router.ts#L827) I'm going to close this, if you are still experiencing this on the latest version of Next.js please update with additional details.

**Closed by ijjk** 2021-01-04 19:47 UTC
Labels: template: bug

**Comment by Gh05d** [comment] 2021-01-05 09:49
Can confirm that it is an object in v10.0.4. Thanks for the reply.

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
