### ISSUE TITLE
HMR failing before dev build

### ISSUE THREAD

**Issue by minlare** [vercel/next.js#16813] opened 2020-09-03 09:32 UTC
# Bug report

## Describe the bug

When a browser tab is open whilst running `next dev`, I think next is attempting to hot update something before being built causing an error.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Have browser tab open on `http://localhost:3000`
2. Run `next dev`
3. First `req.url` is `/_next/static/webpack/xxxxxxxxxxxx.hot-update.json` which does not exist in filesystem
4. Output shows `event - build page: /404`
5. Browser tab reloads
6. Page is then built `event - build page: /`

## Expected behavior

No attempt to HMR before page is built.

## Screenshots

![next-hot-update-issue](https://user-images.githubusercontent.com/1862882/92097679-47b13e00-edd0-11ea-9f9a-7f8e0e4948d3.png)

I have outputted the `req.url` in between the next logs

## System information

- OS: WSL2 on Windows10
- Browser: chrome
- Version of Next.js: 9.5.3
- Version of Node.js: 12.18.1

**Comment by timneutkens** [comment] 2020-09-03 12:25
Please provide a minimal reproduction in a github repository.

**Comment by felixmosh** [comment] 2020-09-06 11:51
The same here... 
When navigating using `Link` (even when navigating to the current page), it tries to load `/_next/static/webpack/f5bb416d37fc4ca84999.hot-update.json` fails with 404, and the app get reloaded.

Searched `f5bb416d37fc4ca84999` in the entire app, found it on the "init" section of webpack bundle, 
![image](https://user-images.githubusercontent.com/9304194/92325080-72112e80-f050-11ea-9535-c9bb35742c23.png)

**Comment by felixmosh** [comment] 2020-09-07 10:54
@minlare can you check if you click on a `<Link>` that links to the current page it still reproduces?

**Comment by minlare** [comment] 2020-09-07 11:09
@felixmosh - I **cannot** reproduce by using a `<Link>` to the current page...

**Comment by felixmosh** [comment] 2020-09-08 13:46
Restart of the machine solved it for now 🤷🏽‍♂️

**Comment by ijjk** [comment] 2021-09-19 19:34
Hi, this sounds related to an issue that is fixed in the latest canary of Next.js `v11.1.3-canary.24` so I'm gonna close this feel free to respond with additional info if you are still seeing this after updating to the latest canary.

**Closed by ijjk** 2021-09-19 19:34 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
