### ISSUE TITLE
useRouter returns null when used in <Head /> Component

### ISSUE THREAD

**Issue by alveshelio** [vercel/next.js#23559] opened 2021-03-30 17:13 UTC
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

15.3.0

### What browser are you using?

Chrome/Firefox

### What operating system are you using?

macOS

### How are you deploying your application?

Doesn't apply

### Describe the Bug

useRouter returns null when called inside `<Head />` component

### Expected Behavior

I would expect that useRouter would be available.

### To Reproduce

This 

I am working on a package to provide better internationalization for Next.js projects. One of our goals is to create alternate links based on the locales defined and the route.

I have this hook:

```ts
export function useAlternateLinks(): AlternateLink[] {
  const { basePath, pathname, locales } = useRouter();
  const rewrites = useRewrites();

  const origin = getOrigin();
  const alternateLinks = locales.map((lang) => {
    const alternateLink = getSourceUrl({ rewrites, locale: lang, path: pathname });

    return {
      href: `${origin}${getBasePath(basePath)}${removeInitialSlash(alternateLink)}`,
      hrefLang: lang,
    };
  });

  const withPathname = pathname !== '/' ? removeInitialSlash(pathname) : '';

  const _href = `${origin}${getBasePath(basePath)}${withPathname}`;

  return [...alternateLinks, { href: _href, hrefLang: 'x-default' }];
}
```
This will return a list of alternate links

I use this hook to create a component `<AlternateLinks />`
```tsx
import { ReactElement } from 'react';
import { useAlternateLinks } from './hooks/useAlternateLinks';

export function AlternateLinks(): ReactElement {
  const alternateLinks = useAlternateLinks();
  return (
    <>
      {alternateLinks.map(({ href, hrefLang }) => (
        <link rel="alternate" href={`${href}`} hrefLang={hrefLang} key={hrefLang} />
      ))}
    </>
  );
}
```
Then I import the component and try to render it in the `<Head  />` component:

```tsx
import Head from 'next/head';
import { AlternateLinks } from 'next-intl-router/lib/alternate-links';

import { IntlLink } from 'next-intl-router/lib/intl-link';
import { useRouter } from 'next/router';

export default function IndexPage() {
  const router = useRouter();
  const { locale, locales, defaultLocale } = router;

  return (
    <div>
      <Head>
        <title>Example HomePage</title>
        <AlternateLinks />
      </Head>
      <h1>Homepage</h1>
      <p>Current locale: {locale}</p>
      <p>Default locale: {defaultLocale}</p>
    </div>
  );
}

```
Doing so will return this error:
TypeError: Cannot destructure property 'basePath' of 'router_1.useRouter(...)' as it is null.
    at Object.useAlternateLinks (webpack-internal:///../lib/hooks/useAlternateLinks.js:13:13)

It looks like next/head is doing some really rather odd things when rendering its children, and that ends up meaning that said render happens outside the RouterContext.Provider that should be wrapping everything, and therefore useRouter() is returning null.

**Comment by ijjk** [comment] 2021-04-28 01:52
React components are not meant to be used inside of `next/head` as mentioned here https://nextjs.org/docs/api-reference/next/head

> title, meta or any other elements (e.g. script) need to be contained as direct children of the Head element, or wrapped into maximum one level of <React.Fragment> or arrays—otherwise the tags won't be correctly picked up on client-side navigations.

related issue https://github.com/vercel/next.js/issues/17721

I'm going to close this since it doesn't appear to be a bug and isn't expected to work currently.

**Closed by ijjk** 2021-04-28 01:52 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
