### ISSUE TITLE
37-5b82c79181d94cdf.js:1 Uncaught (in promise) TypeError: number 0 is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by tohsaka888** [vercel/next.js#40889] opened 2022-09-26 01:47 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Binaries:
      Node: 16.17.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.3.1
      eslint-config-next: 12.3.1
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

chrome 105.0.5195.127

### How are you deploying your application? (if relevant)

next start,vercel, netlify

### Describe the Bug

When i use `next start` or use vercel/netlify to deploy my website,i got an error in console.
![image](https://user-images.githubusercontent.com/58759688/192177266-de58c563-7d2d-499b-8af1-d37fa5d9a307.png)
 
![image](https://user-images.githubusercontent.com/58759688/192177367-8343f28e-b411-4f33-ac1e-bcaef2ea62f0.png)

When i switch `next.js` to version `12.3.0`,it does't have any error.

### Expected Behavior

no error.

### Link to reproduction

https://codesandbox.io/s/github/tohsaka888/coder-home

### To Reproduce

first, build the application.

run `next start`.

see the console, it will have an error.

click, this button.

![image](https://user-images.githubusercontent.com/58759688/192177996-74e7138d-ae18-4c8c-9d81-835834e57bbf.png)

it will have another error.

[repo](https://github.com/tohsaka888/coder-home)

**Comment by balazsorban44** [comment] 2022-09-26 11:27
From the looks of it, this might be an SWC minifier bug, but I cannot reproduce it currently, as the reproduction just produces CORS errors.

Could you try to create a more minimal reproduction of the issue? That would mean removing anything that is not directly contributing to the issue that you see. pages, APIs, packages, etc.

Can you try setting the `swcMinfy: false` option in your `next.config.js` to see if it makes a difference?

**Comment by tohsaka888** [comment] 2022-09-27 01:33
> From the looks of it, this might be an SWC minifier bug, but I cannot reproduce it currently, as the reproduction just produces CORS errors.
> 
> Could you try to create a more minimal reproduction of the issue? That would mean removing anything that is not directly contributing to the issue that you see. pages, APIs, packages, etc.
> 
> Can you try setting the `swcMinfy: false` option in your `next.config.js` to see if it makes a difference?

Thanks for your reply.When i switch `swcMinify` to `false`, the error is missing.

I think this error is acturally caused by SWC,should i close the issue?

**Comment by angelbeatsying** [comment] 2022-09-27 07:48
when i upgrade to Next version 12.3.1, meet the same problem. when i use next/router jump to login page

**Comment by balazsorban44** [comment] 2022-09-27 16:39
@tohsaka888 if it's an SWC bug, we still need to investigate to be able to fix the issue.

**Comment by tohsaka888** [comment] 2022-09-28 03:06
@balazsorban44 Maybe the version 12.3.1 of `next.js` is conflict with `antd` Menu component.When i remove the Menu of `antd`,the error is missing.By the way,the error is just occured in `production mode`.

**Comment by balazsorban44** [comment] 2022-09-28 10:10
The error occurring only in production (deployed or `next build && next start`) means that it's a minifier bug since we don't minify in development (`next dev`).

Thanks for trying to narrow the problem down. Minimizing the reproduction repository is important for us to be able to identify the bug. If you have time to do so, please try removing any unnecessary code (pages, components, API, etc.) that does not contribute to the issue and post a simplified reproduction. :pray: I tried yesterday, but your repository gave different errors than before, likely because you have pushed some new commits to it.

**Comment by tohsaka888** [comment] 2022-09-28 10:59
@balazsorban44 I create a new [repo](https://github.com/tohsaka888/next-swc-bug) to reproduce the error.Just use [antd Menu component](https://ant.design/components/menu/#header) then i `build` this project and `start` it,you will see the error in console.

**Comment by balazsorban44** [comment] 2022-09-29 10:53
Thanks! I could now confirm that the issue is fixed on the latest `canary` release! You can test it by running `npm i next@canary`, or wait for the fix to appear in the `latest` release.

**Closed by balazsorban44** 2022-09-29 10:53 UTC
Labels: kind: bug, type: needs investigation, area: SWC Minify

**Comment by tohsaka888** [comment] 2022-09-29 12:37
> Thanks! I could now confirm that the issue is fixed on the latest `canary` release! You can test it by running `npm i next@canary`, or wait for the fix to appear in the `latest` release.

Thanks for your help!
