### ISSUE TITLE
Error: invariant: progress total can not be zero

### ISSUE THREAD

**Issue by NikhilVerma** [vercel/next.js#23834] opened 2021-04-08 18:25 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

12.18.4

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Other platform

### Describe the Bug

When I build by next app I get this error: Error: invariant: progress total can not be zero.

It's caused by the following commit: https://github.com/vercel/next.js/commit/7e63bd7d54901103681e64982282990cb5a8c2d6

I have left a comment in the line - https://github.com/vercel/next.js/commit/7e63bd7d54901103681e64982282990cb5a8c2d6#r49278558

It happens because I am doing getStaticPaths with blocking. And it's the only static page in my app.

```
export async function getStaticPaths() {
    return {
        paths: [],
        fallback: 'blocking',
    };
}
```

### Expected Behavior

The build should accept 0 static pages generated at build time.

### To Reproduce

1. Make a next app with a single static page with params. 
2. Add the following export.

```
export async function getStaticPaths() {
    return {
        paths: [],
        fallback: 'blocking',
    };
}
```

**Comment by ijjk** [comment] 2021-04-08 18:35
Hi, this is a duplicate of https://github.com/vercel/next.js/issues/23724 which is fixed in the latest canary of Next.js  `v10.1.4-canary.2`

**Closed by ijjk** 2021-04-08 18:35 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 13:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
