### ISSUE TITLE
TrailingSlash issue

### ISSUE THREAD

**Issue by edmgithub** [vercel/next.js#22210] opened 2021-02-16 08:10 UTC
**What version of Next.js are you using?**

10.0.7

**What version of Node.js are you using?**

14.x on Vercel. Also tried with 12.x

**What browser are you using?**

Chrome, Safari

**What operating system are you using?**

macOS

**How are you deploying your application?**

Vercel

**Describe the Bug**

When you visit the following page (https://koinly-i18next-test-1hjdcz1oz.vercel.app/gsp/first/) there is a request to 'https://koinly-i18next-test-1hjdcz1oz.vercel.app/_next/data/.../en/.json' with 404 response (checking under the network tab in Chrome or Safari)
When you hover on the 'To index page' link another '.json' 404 request displayed.
This issue causes a slower page load when we click on the link.
The issue is on Vercel only, the project works on localhost in production mode.

**Expected Behavior**

The '.json' request should return with 200 status code. The index page should load quickly when we click on the 'To index page' link.

**To Reproduce**

I forked the sample i18n NextJs repo and made minimal changes to demonstrate the issue.
Please find here the changes: https://github.com/vercel/next.js/compare/canary...edmgithub:canary
You can see the error on the console here: https://koinly-i18next-test-1hjdcz1oz.vercel.app/gsp/first/
So when we add the trailingSlash config in next.config.js and a getStaticProps method to index.js the error occures on Vercel.
Thank you for your help!

**Comment by robinsingh-bw** [comment] 2021-02-17 19:23
+1

**Comment by mekanics** [comment] 2021-08-03 12:00
I had the same issue with next.js v10.0.3. 

It has been fixed in v10.0.4 (https://github.com/vercel/next.js/pull/19474)

**Closed** 2021-08-03 12:15 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
