### ISSUE TITLE
Ocasianally adding file to static folder with wrong casing causing "there are multiple modules with names that only differ in casing"

### ISSUE THREAD

**Issue by Andrew199617** [vercel/next.js#20021] opened 2020-12-09 13:20 UTC
# Bug report

## Describe the bug

https://stackoverflow.com/questions/47534267/webpack-there-are-multiple-modules-with-names-that-only-differ-in-casing-but

## To Reproduce

Randomly happens where next will stop hot reloading a page. Ill have to force a rebuild of the page.

## Expected behavior

Hot-Reload does not stop failing and i dont have to manually delete messed up file.

## Screenshots

![image](https://user-images.githubusercontent.com/10506965/101634818-3727e980-39f7-11eb-8704-c33758511fe4.png)
That addpage is named AddPage in my project.

## System information

- OS: Windows 10
- Browser chrome
- Version of Next.js: 9.3.4
- Version of Node.js: 9.3.4
- Deployment: Custom Server. node server

**Comment by jamesmosier** [comment] 2020-12-13 04:16
Hi @Andrew199617. It appears as if that is a webpack issue according to the link you posted. Could you elaborate a bit on what the issue is and what you see the fix to be? Maybe even include a repository to show the issue.

**Comment by Andrew199617** [comment] 2020-12-13 04:57
Hello @jamesmosier

I dont think it is a webpack isssue since the naming problem is occurring in next.js folder. Unless webpack is the one that handles creating the files in next.js static folder. The files i see in Webpack folder have the correct casing.

The problem is i will be on a page and occasionally that page will stop being able to be reloaded. It will just be a blank screen and throw and error in the console. I have to go to another page on the site and reopen the page for it to work again. Basically forcing next.js to rebuild the page. 

My current workaround is deleting the .next folder. That only works for a couple days before the error comes back. 

No repo sorry its private. Would my next.config.js be useful?

**Comment by jamesmosier** [comment] 2020-12-14 14:22
You do not need to include the *actual* repo, you could recreate this in a *new* repo. Otherwise this will be hard to help with...

**Comment by lachlanjc** [comment] 2021-01-03 07:21
Possibly related: #11742

**Comment by timneutkens** [comment] 2021-01-03 10:14
Going to close this as no reproduction was provided.

**Closed by timneutkens** 2021-01-03 10:14 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-01-28 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
