### ISSUE TITLE
Partial Hydrtion failed with Error Boundary

### ISSUE THREAD

**Issue by amm834** [vercel/next.js#44481] opened 2023-01-01 16:07 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
   Operating System:
      Platform: linux
      Arch: x64
      Version: #27-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov 23 20:44:15 UTC 2022
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: 7.20.0
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0


```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Head component/file (next/head / head.js)

### Link to the code that reproduces this issue

https://github.com/amm834/aungmyatmoe.me

### To Reproduce

- Go to the the `about` page 
- Open responsive devtool
- Refresh about page 
- see partial hydration error

### Describe the Bug

Partial hydration error occurred when I inject about page layout with Footer component. And then I removed and try it again. It is still happening with following error

```
The above error occurred in the <NotFoundErrorBoundary> component:

    at NotFoundErrorBoundary (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/layout-router.js:371:9)
    at NotFoundBoundary (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/layout-router.js:378:11)
    at LoadingBoundary (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/layout-router.js:290:11)
    at ErrorBoundary (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/error-boundary.js:76:11)
    at RenderFromTemplateContext (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/render-from-template-context.js:12:34)
    at OuterLayoutRouter (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/layout-router.js:20:11)
    at div
    at body
    at html
    at ReactDevOverlay (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:58:9)
    at HotReload (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:19:11)
    at Router (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/app-router.js:99:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/error-boundary.js:63:9)
    at ErrorBoundary (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/error-boundary.js:76:11)
    at AppRouter (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/app-router.js:20:13)
    at ServerRoot (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/app-index.js:126:11)
    at RSCComponent
    at Root (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/app-index.js:143:11)

React will try to recreate this component tree from scratch using the error boundary you provided, ReactDevOverlay.
overrideMethod @ react_devtools_backend.js:4012
logCapturedError @ react-dom.development.js?9e80:21544
callback @ react-dom.development.js?9e80:21610
callCallback @ react-dom.development.js?9e80:17363
commitCallbacks @ react-dom.development.js?9e80:17410
commitClassCallbacks @ react-dom.development.js?9e80:26829
commitLayoutEffectOnFiber @ react-dom.development.js?9e80:26931
recursivelyTraverseLayoutEffects @ react-dom.development.js?9e80:28382
commitLayoutEffectOnFiber @ react-dom.development.js?9e80:26913
recursivelyTraverseLayoutEffects @ react-dom.development.js?9e80:28382
commitLayoutEffectOnFiber @ react-dom.development.js?9e80:27083
recursivelyTraverseLayoutEffects @ react-dom.development.js?9e80:28382
commitLayoutEffectOnFiber @ react-dom.development.js?9e80:27083
recursivelyTraverseLayoutEffects @ react-dom.development.js?9e80:28382
commitLayoutEffectOnFiber @ react-dom.development.js?9e80:27083
recursivelyTraverseLayoutEffects @ react-dom.development.js?9e80:28382
commitLayoutEffectOnFiber @ react-dom.development.js?9e80:27083
recursivelyTraverseLayoutEffects @ react-dom.development.js?9e80:28382
commitLayoutEffectOnFiber @ react-dom.development.js?9e80:27083
recursivelyTraverseLayoutEffects @ react-dom.development.js?9e80:28382
commitLayoutEffectOnFiber @ react-dom.development.js?9e80:26913
recursivelyTraverseLayoutEffects @ react-dom.development.js?9e80:28382
commitLayoutEffectOnFiber @ react-dom.development.js?9e80:26924
recursivelyTraverseLayoutEffects @ react-dom.development.js?9e80:28382
commitLayoutEffectOnFiber @ react-dom.development.js?9e80:26913
recursivelyTraverseLayoutEffects @ react-dom.development.js?9e80:28382
commitLayoutEffectOnFiber @ react-dom.development.js?9e80:26913
recursivelyTraverseLayoutEffects @ react-dom.development.js?9e80:28382
commitLayoutEffectOnFiber @ react-dom.development.js?9e80:26913
recursivelyTraverseLayoutEffects @ react-dom.development.js?9e80:28382
commitLayoutEffectOnFiber @ react-dom.development.js?9e80:26913
recursivelyTraverseLayoutEffects @ react-dom.development.js?9e80:28382
commitLayoutEffectOnFiber @ react-dom.development.js?9e80:26913
recursivelyTraverseLayoutEffects @ react-dom.development.js?9e80:28382
commitLayoutEffectOnFiber @ react-dom.development.js?9e80:27083
recursivelyTraverseLayoutEffects @ react-dom.development.js?9e80:28382
commitLayoutEffectOnFiber @ react-dom.development.js?9e80:27083
recursivelyTraverseLayoutEffects @ react-dom.development.js?9e80:28382
commitLayoutEffectOnFiber @ react-dom.development.js?9e80:26943
commitLayoutEffects @ react-dom.development.js?9e80:28368
commitRootImpl @ react-dom.development.js?9e80:31476
commitRoot @ react-dom.development.js?9e80:31330
performSyncWorkOnRoot @ react-dom.development.js?9e80:30406
flushSyncCallbacks @ react-dom.development.js?9e80:14254
eval @ react-dom.development.js?9e80:29896
```

### Expected Behavior

I think partial hydration should work fine. I cannot figure out form dynamic importing in next app dir. It is so difference from normal pages directory to resolve that issue.

See live error at the production.

https://www.aungmyatmoe.me/about

### Which browser are you using? (if relevant)

Chrome Version 108.0.5359.124 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

default  commands

**Comment by gfpacheco** [comment] 2023-02-28 00:28
I was able to reproduce this with a fresh new app. This is what I did:

- Created a new app with `yarn create next-app --typescript my-app`
- Ran dev server with `yarn dev`
- Kept refreshing the page quickly
- Most times I don't see any error, but sometimes I get this error:

```
The above error occurred in the <NotFoundErrorBoundary> component:

    at NotFoundErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:397:9)
    at NotFoundBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:404:11)
    at LoadingBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:317:11)
    at ErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:72:11)
    at RenderFromTemplateContext (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/render-from-template-context.js:12:34)
    at OuterLayoutRouter (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/layout-router.js:23:11)
    at body
    at html
    at ReactDevOverlay (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:61:9)
    at HotReload (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:20:11)
    at Router (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/app-router.js:48:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:59:9)
    at ErrorBoundary (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/error-boundary.js:72:11)
    at AppRouter (webpack-internal:///(app-client)/./node_modules/next/dist/client/components/app-router.js:24:13)
    at ServerRoot (webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:126:11)
    at RSCComponent
    at Root (webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:143:11)
```

**Comment by timneutkens** [comment] 2023-02-28 11:58
@gfpacheco I tried to reproduce it by refreshing ~85 times and it didn't happen.
Similarly I went to [aungmyatmoe.me/about](https://www.aungmyatmoe.me/about) and did 62 refreshes without an error happening.

**Comment by amm834** [comment] 2023-03-03 02:50
Could you please try this URL https://www.aungmyatmoe.me/projects in small size screen view.

**Comment by itoutcome** [comment] 2023-03-12 00:35
Can confirm it in the lastest version. Just install a fresh copy and enable appDir.
Open the console and just keep pressing F5 over and over again. You'll see it, it won't take long.

Tested on Chrome and Firefox.

And I've been waiting for months for this to be fixed.

**Comment by timneutkens** [comment] 2023-03-17 17:39
Tried again, doesn't reproduce, my guess is that you have a browser extension that is modifying the html.

**Comment by itoutcome** [comment] 2023-03-17 17:55
So I tried it on chrome, in incognito. All extensions disabled. And I also tried it on firefox (no extensions installed).

And again, I'm talking about a fresh install of a next app. The default one when installing next (npx create-next-app@latest) and that's it (appDir enabled, of course). I don't even have to open the files. Just "npm run dev".

I think the refreshing part is confusing. So keep the console open in chrome. Because the error appears and if you blink, you miss it. The error occures before it reloads. Let's say you have the app open for a minute. When you press F5, the error shows up before it reloads. As if it's an error on closing an app or something. So the next time it loads, it loads fine. Maybe not the best explanation.

Anyway, keep the dev tools open, on console, and press F5. Like a double click, a quick double tap on F5. As if you'd want to refresh it before it finished loading. So press F5 twice, let it site for a second, try again, you'll catch it.

If you still find it confusing, maybe I can record it if I'm not explaining it right

**Comment by timneutkens** [comment] 2023-04-09 17:11
There were some fixes in React regarding hydration, can you try again using Next.js 13.3?

**Comment by amm834** [comment] 2023-04-10 12:14
I'll test with latest version in my site tonight.

**Comment by timneutkens** [comment] 2023-04-10 19:32
Thanks!

**Comment by timneutkens** [comment] 2023-04-18 15:34
Going to close this issue as duplicate of https://github.com/vercel/next.js/issues/45047#issuecomment-1492878909, let me know if you're still running into it on the latest version / canary.

**Closed by timneutkens** 2023-04-18 15:34 UTC
Labels: template: bug
