### ISSUE TITLE
axios & middleware error - adapter is not a function

### ISSUE THREAD

**Issue by SKumarSpace** [vercel/next.js#30932] opened 2021-11-04 03:54 UTC
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Microsoft Edge (Chromium)

### What operating system are you using?

Windows

### How are you deploying your application?

```next dev```

### Describe the Bug

Unable to call axios from middleware.
When I do, I receive the following error:
```
error - node_modules\axios\lib\core\dispatchRequest.js (58:0) @ dispatchRequest
TypeError: adapter is not a function
```
![image](https://user-images.githubusercontent.com/8459900/140254926-cdfab72e-bcdf-43d2-b429-48bcba213adc.png)

I also tried this with ```next@canary```, but it also has the same issue.

### Expected Behavior

Http Request from Axios should go through

### To Reproduce

- Create _middleware.ts file
- Call Axios Get request inside middleware
```
const resp = await axios.get('https://httpbin.org/ip');
```

**Comment by davidecutrupi** [comment] 2021-11-07 11:27
I have the same problem.
Using the fetch function it works.

**Comment by Kikobeats** [comment] 2021-11-12 10:14
Probably the thing that is happening there is `axios` is using some Node.js modules and the Edge Function is running in a Web Runtime where Node.js APIs are missing.

Why not just use `fetch`? It's global, it's standard, it's expected.

**Comment by Kikobeats** [comment] 2021-11-17 11:08
After investigation, we determine what is happening is axios delegates into `XMLHttpRequest` and it's missing on the Edge Function; this is a limitation right now can't be resolved in the short term; also Axios is [working](https://github.com/axios/axios/issues/4209) in a new version that uses fetch instead, so there is not too much we can do right now.

I recommend you to use native fetch or [ky](https://github.com/sindresorhus/ky) in case you want some sugar syntactic over fetch API.

**Closed** 2021-11-18 08:38 UTC
Labels: template: bug, area: Middleware

**Comment by balazsorban44** [comment] 2022-01-27 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
