### ISSUE TITLE
Updating to next 13.5.2 breaks instrumentation if middlware.ts file exists

### ISSUE THREAD

**Issue by cabbage-cart** [vercel/next.js#55752] opened 2023-09-21 16:54 UTC
### Link to the code that reproduces this issue

https://github.com/cabbage-cart/my-minimal-nextjs-issue-reproduction

### To Reproduce
run `docker-compose --profile test-app up` 
or run locally by `npm install` then `docker-compose up -d && npm run dev`

then visit localhost:3000 or localhost:3000/b/[slug]

then visit http://localhost:16686/search, select the `test-app` service and click `Find traces` and you'll see almost every trace is throwing an error
![Screenshot 2023-09-22 at 2 45 40 am](https://github.com/vercel/next.js/assets/53833727/35d4126d-9479-46c0-a668-2f3f96f1468d)

inspecting the event logs on any trace shows the handleCatchallMiddlewareRequest is throwing an error and not allowing the other spans to come through

event | exception |  
-- | -- | --
exception.stacktrace | Error     at DevServer.handleCatchallMiddlewareRequest (/my-minimal-nextjs-issue-reproduction/node_modules/next/dist/server/next-server.js:1067:33)     at async DevServer.handleRequestImpl (/my-minimal-nextjs-issue-reproduction/node_modules/next/dist/server/base-server.js:735:32) |  
exception.type | Error

## Current behaviour @canary
Every trace throwing error

<img width="1300" alt="Screenshot 2023-09-22 at 2 37 56 am" src="https://github.com/vercel/next.js/assets/53833727/1bdd02df-898c-4d6d-b8d2-ab64d0629c3d">

## Expected behaviour v13.4.19
traces should not throw error

<img width="1313" alt="Screenshot 2023-09-22 at 2 35 52 am" src="https://github.com/vercel/next.js/assets/53833727/a830a12a-d2d4-4da5-bf64-278b68c4208d">

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
    Binaries:
      Node: 20.6.0
      npm: 9.8.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.5.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Middleware / Edge (API routes, runtime)

### Additional context

reverting back to 13.4.19. fixes the issue as well as deleting the middleware.ts file.

**Comment by valkum** [comment] 2023-09-26 10:22
The `Error` creation was created earlier in this commit https://github.com/vercel/next.js/commit/9be1386a253cc55282fb3966738814a5fcb8b631
But it contains more `Error` creation that looks weird and probably should have some comments explaining why it creates the `Error`. It looks like `Error` is used to return the middleware response. Which really looks like there should be a better solution. 
This issue suggests that  `handleCatchallMiddlewareRequest` is called from another place that is not wrapped into the try catch block that is used in `handleRoute`.

**Comment by oriolgm** [comment] 2023-09-27 17:51
Something similar happened to me while updating from 13.4.19 to 13.5.3

I get successful DataDog traces wit 200 status code but there is a span with an empty Error.

This is the trace I get
```
Error
    at NextNodeServer.handleCatchallMiddlewareRequest (/home/node/node_modules/next/dist/server/next-server.js:1067:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.handleRequestImpl (/home/node/node_modules/next/dist/server/base-server.js:735:32)
```

APM detected successful requests as errors

<img width="599" alt="image" src="https://github.com/vercel/next.js/assets/919328/8d47dc43-1d27-4ab1-91fd-b60c01ed0ac4">

**Comment by cabbage-cart** [comment] 2023-09-29 06:33
> Something similar happened to me while updating from 13.4.19 to 13.5.3
> 
> I get successful DataDog traces wit 200 status code but there is a span with an empty Error.
> 
> This is the trace I get
> 
> ```
> Error
>     at NextNodeServer.handleCatchallMiddlewareRequest (/home/node/node_modules/next/dist/server/next-server.js:1067:33)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async NextNodeServer.handleRequestImpl (/home/node/node_modules/next/dist/server/base-server.js:735:32)
> ```
> 
> APM detected successful requests as errors
> 
> <img alt="image" width="599" src="https://user-images.githubusercontent.com/919328/271070034-8d47dc43-1d27-4ab1-91fd-b60c01ed0ac4.png">

same here. Found out after a monitor went off for error tracking.`200` responses, but this line just disrupts the rest of the request flow from coming through due to the middleWare flag

https://github.com/vercel/next.js/blob/a2df451fa8323b4b2eb1e48337243180ac159c69/packages/next/src/server/next-server.ts#L1638-L1642

I tried commenting it out in my node_modules and it seemed to fix the issue. Just hoping this gets taken a look at soon.

**Comment by stephanbakker** [comment] 2023-10-06 09:20
Same here! 
We are using application insights, and our 'success' logs are polluted with Error logs (error: true and resultCode: 200).

**Comment by szympajka** [comment] 2023-10-18 17:00
I can confirm the same. DataDog `200` logs are being polluted with error:

![image](https://github.com/vercel/next.js/assets/19807209/956d6fff-8a63-4cfd-8d3a-5287f40fd743)

**Comment by cabbage-cart** [comment] 2023-11-01 05:36
looks like this got addressed in next 14.0.0

**Comment by szympajka** [comment] 2023-11-01 11:41
Hey @cabbage-cart, this still seems to be an issue for us. We upgraded to `14.0.0` on our test environment and still pretty much every request gets error response, despite being successful. There is something significantly wrong somewhere.

I looked through our usage of middleware and I cannot see anything out of ordinary in our usage. I know saying that is subjective though. 

<img width="1165" alt="Screenshot 2023-11-01 at 11 36 16" src="https://github.com/vercel/next.js/assets/19807209/bb86a786-b199-4df0-886c-a54746315152">

Would be great to get @ijjk or someone else from next team/vercel to have a look.

**Comment by cabbage-cart** [comment] 2023-11-01 12:25
> Hey @cabbage-cart, this still seems to be an issue for us. We upgraded to `14.0.0` on our test environment and still pretty much every request gets error response, despite being successful. There is something significantly wrong somewhere.
> 
> I looked through our usage of middleware and I cannot see anything out of ordinary in our usage. I know saying that is subjective though.
> 
> <img alt="Screenshot 2023-11-01 at 11 36 16" width="1165" src="https://user-images.githubusercontent.com/19807209/279662487-bb86a786-b199-4df0-886c-a54746315152.png">
> Would be great to get @ijjk or someone else from next team/vercel to have a look.

re-opening issue

**Comment by gabor-at-reed** [comment] 2023-11-22 13:45
Same issue here with the current latest 14.0.3 😭

**Comment by szympajka** [comment] 2023-11-22 16:37
After investigation in my team, we concluded except the noice, this does not create any actual errors for us. It would still be good to remove the cause such error is dispatched though.

@gabor-at-reed, do you have any additional issues caused by it?

**Comment by gabor-at-reed** [comment] 2023-11-23 08:41
> After investigation in my team, we concluded except the noice, this does not create any actual errors for us. It would still be good to remove the cause such error is dispatched though.
> 
> @gabor-at-reed, do you have any additional issues caused by it?

@szympajka This issue eats up our DD logs limit in a blink. It's a serious issue at least financial-wise.

**Comment by gabor-at-reed** [comment] 2023-11-23 10:51
> It seems that dd-trace 4.18 introduced some fixes to avoid logging that : https://github.com/DataDog/dd-trace-js/releases/tag/v4.18.0
> 
> I'm on Next.js 14.0.1 and dd-trace 4.18.0 and I no longer receive those errors.

Thanks! I tried with next.js 14.0.3 and dd-trace 4.21.0, and the error has gone.

**Comment by szympajka** [comment] 2023-11-29 00:26
Amazing news @oriolgm! I will try this tomorrow! :)

**Comment by szympajka** [comment] 2023-11-30 12:22
Nice! I updated `dd-trace` and the error is gone 🙇 

@cabbage-cart, I think we can close this issue now 🙌

**Comment by stephanbakker** [comment] 2023-12-04 08:50
@cabbage-cart Is this issue now closed because of a work-around/fix in dd-trace? I think this was not per-se related to dd-trace, right? We are using application-insights, so the dd-trace change will not help us.

**Comment by cabbage-cart** [comment] 2023-12-04 11:16
@stephanbakker fair enough. Will leave the issue open still someone from vercel has acknowledged this issues

**Closed** 2024-06-26 13:45 UTC
Labels: bug, Runtime, Instrumentation
