### ISSUE TITLE
i18n with next export calls getStaticProps for each defined lang, but then errors

### ISSUE THREAD

**Issue by sean256** [vercel/next.js#18318] opened 2020-10-27 18:26 UTC
# Bug report

## Describe the bug

I'm attempting to use the brand new i18n feature for a static exported site. During build time it calls `getStaticProps` once for each lang defined in `next.config.js` and in some cases even builds the page, but at the end it fails with:

`i18n support is not compatible with next export.`

It feels like a tease having it _almost build_ lol.

## To Reproduce

Add langs to config

```js
module.exports = {
	i18n: {
		locales: ['en-US', 'fr', 'nl-NL'],
		defaultLocale: 'en-US',
	},
}
```

Add `getStaticProps` to a page, like `/content.tsx`

```js
export async function getStaticProps(context) {
	console.log('getStaticProps', context); // context will include the `locale` for each lang defined
	return {
		props: {},
	};
}
```

## Expected behavior

To either:

Export all lang paths
OR
Fail early until this is better supported for `next export`

## System information

- OS: macOS
- Version of Next.js: 10.0.0
- Version of Node.js: 12.x

## Additional context

```
Loaded env from /Users/REDACTED/gits/REDACTED/src/.env.production
info  - Using external babel configuration from /Users/REDACTED/gits/REDACTED/src/.babelrc
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
[   =] info  - Generating static pages (0/19){}
{}
{}
{}
[  ==] info  - Generating static pages (0/19)getStaticProps {
  locales: [ 'en-US', 'fr', 'nl-NL' ],
  locale: 'en-US',
  defaultLocale: 'en-US'
}
getStaticProps {
  locales: [ 'en-US', 'fr', 'nl-NL' ],
  locale: 'fr',
  defaultLocale: 'en-US'
}
getStaticProps {
  locales: [ 'en-US', 'fr', 'nl-NL' ],
  locale: 'nl-NL',
  defaultLocale: 'en-US'
}
{}
{}
{}
{}
info  - Generating static pages (19/19)
info  - Finalizing page optimization  

Page                                                           Size     First Load JS
┌ ○ /                                                          300 B           168 kB
├   /_app                                                      0 B             167 kB
├ ○ /404                                                       3.44 kB         171 kB
├ ● /content                                                   310 B           168 kB
├ ○ /foo                                                       300 B           168 kB
└ ○ /performance                                               297 B           168 kB
+ First Load JS shared by all                                  167 kB
  ├ chunks/d5fb258340a338fc09455890a68100a3d216cee4.6dfcc7.js  71 kB
  ├ chunks/f6078781a05fe1bcb0902d23dbbb2662c8d200b3.6547a9.js  11.4 kB
  ├ chunks/framework.a3ab6d.js                                 42.1 kB
  ├ chunks/main.fde44f.js                                      8.02 kB
  ├ chunks/pages/_app.6a0339.js                                34 kB
  ├ chunks/webpack.e06743.js                                   751 B
  └ css/afd7172b7cfc566ac23d.css                               20 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

Loaded env from /Users/REDACTED/gits/REDACTED/src/.env.production
info  - using build directory: /Users/REDACTED/gits/REDACTED/src/.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "next.config.js". Generating map from "./pages"
Error: i18n support is not compatible with next export. See here for more info on deploying: https://nextjs.org/docs/deployment
    at exportApp (/Users/REDACTED/gits/REDACTED/src/node_modules/next/dist/export/index.js:14:296)
```

**Comment by ijjk** [comment] 2020-10-30 19:04
Hi, as mentioned in the [initial RFC](https://github.com/vercel/next.js/discussions/17078) `next export` wasn't planned for initial support. When doing a build we don't know that you're going to call `next export` so we can't show this error message earlier. 

I'm going to close this since this is the expected behavior currently

**Closed by ijjk** 2020-10-30 19:04 UTC
Labels: kind: story, point: 2

**Comment by caribou-code** [comment] 2020-11-08 21:51
@ijjk the link referenced in that comment says `Support the hybrid server-side rendering and static generation use case`. Does that not mean static generation would be supported or am I misinterpreting this?

I think I'm also a little confused because i18n support is one of the biggest features of Next.js 10 and Vercel seem to really be pushing SSG as the way forward, so I don't know why a big new feature like this wouldn't support the suggested static export method (and why the static lifecycle methods seem to already support it). Is there any additional information available?

Also, if it really isn't currently supported, is there either a work around or timeline for a new release with SSG support for i18n?

**Comment by a14m** [comment] 2020-11-09 12:32
@ijjk sorry I'm a bit confused, the documentation suggests that it's supported here: https://nextjs.org/docs/advanced-features/i18n-routing#how-does-this-work-with-static-generation (if I'm not mistaken)... but I run into the same issue running `next export`

**Comment by caribou-code** [comment] 2020-11-09 12:54
I'm also very confused. Both the docs and RFC suggest SSG support for i18n, and the SSG functions seem to support it on the surface (exposing locale in the context params) but not during export. This looks like a valid bug to me.

**Comment by timneutkens** [comment] 2020-11-09 13:26
It's supported in the hybrid approach which the majority of Next.js applications uses. We can investigate adding `next export` support for it for you under enterprise support, feel free to reach out to enterprise@vercel.com

**Comment by a14m** [comment] 2020-11-09 13:41
Will try to reach out, but it is definitely an important feature since we need to deploy static websites to client managed infrastructure (S3 or hosting provider, which usually cannot support the hybrid approach, they usually serve static files)

**Comment by caribou-code** [comment] 2020-11-09 14:39
@timneutkens that's a shame. Is there any kind of roadmap/timeline for adding full SSG support for i18n (even if it's with language detection not supported)? Perhaps it's worth updating the documentation to reflect the current level of support, because it definitely looks like it's supported in the link above.

On a side note, I think this feature and the other new ones in Next.js 10 are totally awesome! Keep up the good work.

**Comment by a14m** [comment] 2020-11-09 15:08
@caribou-code I did a quick investigation and it seems to be possible (but requires manual work, probably have to depend on a fork)...
first of all you can disable the error that raises in `next export` command, this can be done by commenting out this block:
https://github.com/vercel/next.js/blob/canary/packages/next/export/index.ts#L288-L292
(you can do that in the resulted file in node_modules too for testing (`node_modules/next/dist/export/index.js` -part of line 14-)

Then running `yarn build` and `yarn export` should work.
The last step is that you need to change the `out` directory content, the `export` command generates the configurations for every language in your `locales` configuration correctly, but you need to move the `default_locale` to be in the root directory (to imitate nextjs default behaviour)...
for example if your `next.config.js` have the following

```
  i18n: {
    locales: ["en", "de"],
    defaultLocale: "en",
  },
```
you need run the following commands 
```
mv ./out/en.html ./out/index.html
mv .out/en/*.html ./out/
```
then serving the `out` directory should work as expected

**Comment by timneutkens** [comment] 2020-11-09 15:16
You're welcome to PR support for it to `next export`, however keep in mind it would have a bunch of edge cases, e.g. `domains` does not work, locale detection does not work etc.

**Comment by a14m** [comment] 2020-11-09 15:23
yeah I know that there will probably be many edge cases... thanks for naming some

**Comment by kylekirkby** [comment] 2020-11-15 22:18
I've just spent some time implementing this to only realise you can't use the `next export` command... why do the docs mislead us? 

![image](https://user-images.githubusercontent.com/4564433/99198407-56cd4880-2790-11eb-8430-86a87ce927eb.png)

You can't tell me that **doesn't** suggest you can statically generate the i18n supported pages?

**Comment by tomijovanoski** [comment] 2020-11-19 13:14
@kylekirkby it definitely **doesn't.**

I too got lost optimizing an existing website for i18n support, just to encounter that I cannot statically generate the pages.
I've tried the @a14m solution, but I got weird, mixed, and non-complete export.

I'll continue investigating, and will report here if I find some solution.

**Comment by ListeH** [comment] 2020-11-22 16:16
> @kylekirkby it definitely **doesn't.**
> 
> I too got lost optimizing an existing website for i18n support, just to encounter that I cannot statically generate the pages.
> I've tried the @a14m solution, but I got weird, mixed, and non-complete export.
> 
> I'll continue investigating, and will report here if I find some solution.

Have you find some solution? I run into same issue, need to export static next page with locales.. :(

**Comment by winston0410** [comment] 2020-11-23 03:30
This is really disappointing. Is there any workaround for using i18n with SSG in next?

**Comment by tomijovanoski** [comment] 2020-11-23 09:21
@ListeH sadly no. Time was an issue, so I temporarily deployed the i18n version to Vercel (on the free tier) and reconfigured the domain DNS entries.

Hopefully, I will get back at it soon.
Following if someone else will have a breakthrough.

**Comment by ekawatani** [comment] 2020-11-26 23:19
I just sent this whole week trying set up a repository for production and just found out that `next export` doesn't support this. What a waste of time...

I noticed it's actually mentioned at the very last paragraph in the [documentation](https://nextjs.org/docs/advanced-features/i18n-routing#locale-strategies), but I wouldn't have noticed that. Other pages have a dedicated section like "Caveats". I believe this page should also have it and state more clearly that i18n is not supported with `next export`. I could have saved a lot of days.

**Comment by Xairoo** [comment] 2020-11-29 13:56
> I just sent this whole week trying set up a repository for production and just found out that `next export` doesn't support this. What a waste of time...
> 

Nearly the same for me. I wasted a lot of time with Gatsby. Until I decided to make the site a SEO friendly multi language site. Now trying Next.js because I think Gatsby is terrible for such cases if you want to have SEO friendly URLs (more or less dead i18n plugins).

I wanted to use SSG with react-intl, but now I am going with Next.js and using SSR.

It would be really awesome (and logic) that we could use internationalizing with SSG. react-intl also because of formatting numbers/dates.

> Note: i18n routing does not currently support next export mode as you are no longer leveraging Next.js' server-side routing.

This note should be on top of the site: https://nextjs.org/docs/advanced-features/i18n-routing

**Comment by timneutkens** [comment] 2020-11-30 10:22
> You can't tell me that doesn't suggest you can statically generate the i18n supported pages?

Next.js does statically generate pages when using the hybrid Next.js approach, which is the default and what the majority of Next.js applications uses. The i18n support goes much further than outputting static files for statically generated content, it also adds a routing layer and language detection layer which can't be replicated with `next export` in a meaningful optimized way.

I've moved the note about `next export` up in the static generation section: https://github.com/vercel/next.js/commit/ad8999356d8c246619cace4e777acc0a7222c834


As said if your company really needs this we can investigate building it out for you. I can't prioritize adding `next export` support to i18n routing based on the current interest (18 👍's on this issue) as there are much bigger optimizations on the roadmap. Furthermore, all the companies we talked to while building i18n support did not use `next export`.

> We can investigate adding next export support for it for you under enterprise support, feel free to reach out to enterprise@vercel.com

**Comment by kylekirkby** [comment] 2020-11-30 11:02
Hi @timneutkens,

> Next.js does statically generate pages when using the hybrid Next.js approach, which is the default and what the majority of Next.js applications uses. The i18n support goes much further than outputting static files for statically generated content, it also adds a routing layer and language detection layer which can't be replicated with `next export` in a meaningful optimized way.

I understand that most Next.js apps are probably being hosted with Vercel or Netlify which will utilize the `next build` command only. My specific use case for `next export` is due to using the `serverless-nexjts` component to host a Next.js app with AWS directly. My build steps for this include `next build && next export`. I do think that there is a very valid need for being able to generate a simple purely static Next.js website that has i18n support. 

> I've moved the note about `next export` up in the static generation section: ad89993

Thank you for this! 

> As said if your company really needs this we can investigate building it out for you. I can't prioritize adding next export support to i18n routing based on the current interest (18 👍's on this issue) as there are much bigger optimizations on the roadmap. Furthermore, all the companies we talked to while building i18n support did not use next export.

Let the power of open-source go to work, then! 

>We can investigate adding next export support for it for you under enterprise support, feel free to reach out to enterprise@vercel.com

Appreciate the "plug"! 😂 But let's keep this awesome framework focused on solving issues through open-source collaboration! I appreciate that others may be willing to pay for support on this, however, it's not mission-critical enough for us right now. 

Cheers! 

Kyle

**Comment by timneutkens** [comment] 2020-11-30 11:15
> Let the power of open-source go to work, then!

https://github.com/vercel/next.js/issues/18318#issuecomment-724077172

**Comment by kylekirkby** [comment] 2020-11-30 11:19
> > Let the power of open-source go to work, then!
> 
> [#18318 (comment)](https://github.com/vercel/next.js/issues/18318#issuecomment-724077172)

Thank you, I appreciate your help on this!

**Comment by chiqui3d** [comment] 2020-12-01 23:56
I hope you don't feel bad about the following words, but it's a totally meaningless thing that has happened to me with the language issue.

So far I have created two landing pages with Next.js a simple one without languages that goes quite well, and another one that goes in 3 languages which I have not been able to generate anything **statically**. My problem here is that I'm going to have to go back to PHP, and I mean it. I was slowly migrating from `PHP `to `Next.js`, but the result with the languages (I18n) is quite bad, it does not support Export is a simple disappointment.

Based on my little experience with Next.js. The three solutions that can be seen here are:

1. `getStaticProps `supports query params and you can use it with `exportPathMap`, then you could perfectly generate anything without the help of `I18n`.
2. Export has `I18n` support.
3. A simple file that supports `params `or anything else related to paths as in Vue https://nuxtjs.org/docs/2.x/features/file-system-routing#extending-the-router, really the same as in the first request.

I've been reviewing the code and trying to help like @a14m said and it's not that easy (Since the real process seems to be generated in the build, since the routes with the locale prefix are not generated). Obviously avoiding the topic of edge cases: domains and locale detention, that really I don't care about this. 



Really if there was a collection of money to fix this, I would help completely with everything I could.

**Comment by Xairoo** [comment] 2020-12-02 22:17
@chiqui3d check my starter, works with `next export` https://github.com/Xairoo/nextjs-i18n-static-page-starter
I was looking for a static site solution to host the content anywhere. Also thought I will change back to PHP after trouble with Gatsby and Next.js, but I got a working solution. I tried to implement a i18n wrapper too, but stopped it fast until I run into problems. The current solution works and is totally okay for me, so no need to waste more time =)

The i18next-browser-languagedetector options are great if you need them.

**Comment by chiqui3d** [comment] 2020-12-02 22:53
Umm, I'll check it out tomorrow and let you know. Thank you very much in advance for sharing 👍

**Comment by Xairoo** [comment] 2020-12-06 09:55
I have added a Format.JS starter for Next.JS SSG too, but I use the i18next version (no need to add polyfill...).
Personally I'd like to use Format.JS, but I want a small file size, so I stay with i18next.

- https://github.com/Xairoo/nextjs-i18n-static-page-starter (i18next)
- https://github.com/Xairoo/nextjs-i18n-formatjs-static-page-starter

**Comment by chiqui3d** [comment] 2020-12-08 03:33
I just tried your method, and it works, but since I use languages it makes me duplicate the code, that is, I use the index page as the default language, I don't redirect the default language to a subdirectory, but good. Also I have seen that I could use the method "Call all routes" https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes and manage there all my routes and showing dynamically the component I want . That would be correct and simpler way. But still it is not generating me a completely static page, it is generating me an SSG with JSON, I don't understand the truth that JSON paints here, when I am generating a simple HTML page.

Have you tried Rosseta https://github.com/lukeed/rosetta? I think it's the smallest for handling translations

I've already done thousands of tests with Next.js to generate a simple static page in several languages and the only thing I've done has been to give me headaches, for now I'm going back to PHP and with less Javascript, of course.

Thank you very much for your contribution, That's going to help a lot of people.

**Comment by Xairoo** [comment] 2020-12-08 09:52
I can understand the headaches =)
Using the subdir makes sense for me. `/` will call /index and `/en` just the site with the language. Otherwise how to split the files? Even with PHP you have to pass the requested language to your file. Like JS it doesn't matter if you use a path, cookie, localStorage, query.
Every path without a given language will (should) result in a redirect. Of course you could just include the wanted file and don't show the language in the path. But think about SEO.

Never tried rosetta.

What do you mean with duplicate the code? `next export` generates the files like en.html and de.html for me. (based on [lang]/index.js).

**Comment by chiqui3d** [comment] 2020-12-10 15:36
I say the duplicate because the default language I use in the root of the domain, in addition to each URL in different language, I do not use the same slug for all languages, that for me is to go a step back, go from PHP to Next.js to use the same URL.

I have to say openly that currently Next.js has the **worst system of routes** that I have seen in my life. I hope it changes, now I'm going to check Eleventy https://github.com/11ty/eleventy, and if I don't go back to PHP, where everything is much easier and where there are better resources.

PHP is Dead, haha.

**Comment by mukarramali** [comment] 2021-02-09 16:25
@Xairoo Thank you for the workaround. Although I'm stuck at one place, posted here: https://discord.com/channels/752553802359505017/752668543891276009/808707144551104512
Do you have any idea what could be the reason?

**Comment by herrherrmann** [comment] 2021-04-08 10:56
@ijjk You closed this issue a few months ago but it looks like many peeps still have an issue with this (myself included). What’s the preferred way to track interest in this feature (ideally publicly and not by sending emails around)? Should we create a new issue or feature request specifically for `next export` to support internationalized routing?

I see this as a huge drawback because it basically means that many companies (who want to host their Next.js projects on one of the many non-Vercel providers) cannot use Next.js with any modern i18n library anymore.

**Comment by chiqui3d** [comment] 2021-04-13 15:28
Next.js is currently not suitable for scaling projects.

**Comment by saadaouad** [comment] 2021-04-14 11:45
I'm getting the same error and there is a lot of people who have the same issue. 

It would be great to open this issue and take a look on it, because there is a lot of people that want to deploy their Next.js app using a **non-Vercel** CDN.

**Comment by Yuripetusko** [comment] 2021-04-29 16:56
I was using static export to run nextjs app in capacitor project (hybrid app) and it worked well, but now it seems I cannot add i18n if next export won't work, 🤔

**Comment by sven-ra** [comment] 2021-05-07 13:04
Is there any plan on adding i18n support with export?

**Comment by qoala-github** [comment] 2021-05-17 15:09
we also have this issue.. tried the workaround.. it isnt working.. please help

**Comment by kayosouza** [comment] 2021-05-20 15:26
We are also facing this issue, did any one find a way to make localized pages be exported? we only need this on our mobile app that currently uses capacitor, so exporting localized pages would be important for us

**Comment by miloshavlicek** [comment] 2021-05-24 20:01
I face this issue when I use next.js with https://github.com/isaachinman/next-i18next which is compatible with SSR. Is there any workaround for this error?

**Comment by johndev0711** [comment] 2021-06-07 01:33
exporting i18n in next includes a big issues, but we couldn't any right solution for a long time.
Who should solve this problem?
Should we give up using Next export?
Smh.... 🤣
There are a lot of questions about the next i18n export, but they didn't answer with correct solution.
Hoping there is a good news for them(including me) soon. 😥

**Comment by packetstracer** [comment] 2021-06-12 21:43
Also with the same i18n issue with export, quite disapointing, I thought Next.js was a nice alternative for small static sites, after a couple weeks of building my site I find that I cannot use the export option and the need to setup a node server. 

Seems like you want devs to into Vercel one way or another. Next I'll give Nuxt a try.

**Comment by gancena** [comment] 2021-07-12 19:57
@ijjk SSG with i18n needs to be in the roadmap if it isn't already. This issue is blocking us from using or recommending NextJS as the framework of choice for statically hosted applications requiring i18n.

**Comment by raphjatteau** [comment] 2021-07-25 07:50
SSG with i18n is a must indeed, for me to continue using nextjs.

**Comment by baeteja** [comment] 2021-08-01 14:12
Can't believe this is not possible... Also can't rely on next anymore without 18n support

**Comment by pedrovagner** [comment] 2021-08-10 05:34
I spent the day implementing **i18n** support in a project. Everything worked great during development. At the end of the day I went to generate the static files `next export` and found out the project would only work if it is hosted on Vercel's platform. It is very sad to know that development is biased towards Vercel's hosting :(

**Comment by caribou-code** [comment] 2021-08-11 09:11
> I spent the day implementing **i18n** support in a project. Everything worked great during development. At the end of the day I went to generate the static files `next export` and found out the project would only work if it is hosted on Vercel's platform. It is very sad to know that development is biased towards Vercel's hosting :(

I don't think anyone is limited to using the Vercel platform. Ultimately a Next.js project will either output static HTML files (which can be hosted anywhere, including an AWS S3 bucket for example) or it will require a running server (could be an AWS EC2 instance for example). The benefit of Vercel is it covers a lot of the hard work of doing the build and deployment correctly for you, and it handles the server-side stuff with Lambda@Edge functions, which is faster and cheaper to run. The issue in this particular case is that `next export` specifically doesn't work with the new i18n integration.

**Comment by Nemo64** [comment] 2021-08-11 09:59
The problem is larger scale than this.

What is the [i18n](https://nextjs.org/docs/advanced-features/i18n-routing) option?
1. It is a routing shortcut. Somewhat equivalent to `[locale]/normal/page/tree`
2. It adds utility methos for switching between languages.
3. It is a server side feature to auto detect the language and redirect automatically.

But then there are plugins like [i18next](https://github.com/isaachinman/next-i18next) and [next-translate](https://github.com/vinissimus/next-translate)
- both force you to use the fairly new [i18n routing](https://nextjs.org/docs/advanced-features/i18n-routing) feature ~ disabling the export feature
- next-translate also uses rewrite rules to translate urls ~ putting an extra stop to the export feature

So what you actually want to do is ignore all the next plugins and the i18n routing option.
Just build your page like this:
```
pages/
  [locale]/
    product/
      [id].js
```
And in the `[locale]/product/[id].js`, you define the routes like this:
```js
export async function getStaticPaths() {
  const paths = [];
  for (const product of await somehowFetch('products')) {
    for (const locale of ['en', 'de']) {
      paths.push({params: {locale, id: product.id}})
    }
  }

  return {paths, fallback: false};
}

export async function getStaticProps({params: {id, locale}}) {
  const product = await somehowFetch(`product ${id}`);
  const translations = JSON.parse(await readFile(`translations.${locale}.json`));
  return {
    props: {product, translations, locale, locales: ['en', 'de']}
  };
}
```

And then you can decide if you need additional translation libraries like [i18next](https://www.i18next.com/) or if you decide to just run `props.translations.headline?.replace('%name%', props.product.name)`

**Comment by myWsq** [comment] 2021-08-13 07:10
As @Nemo64 said, dynamic routing can be used to export static pages. I have a demo that uses react-i18next. 

https://github.com/myWsq/nextjs-static-i18n

```tsx
import { StaticI18nLink } from "../i18n-browser";
import { useTranslation } from "react-i18next";

const Layout: React.FunctionComponent = ({ children }) => {
  const { t } = useTranslation("common");

  return (
    <>
      <nav>
        <StaticI18nLink href="/">{t("home")}</StaticI18nLink>{" "}
        <StaticI18nLink href="/about">{t("about")}</StaticI18nLink>
      </nav>
      <main>{children}</main>
      <footer>
        <li>
          <StaticI18nLink locale="zh">简体中文</StaticI18nLink>
        </li>
        <li>
          <StaticI18nLink locale="en">English</StaticI18nLink>
        </li>
      </footer>
    </>
  );
};

export default Layout;

```

I've wrapped `next/link` to avoid using next routing, but there are still boundary cases when using `next/router`. It's a rudimentary approach, but it works well enough for me.

It also supports setting the basePath, and here is a deployment on Github Pages.

https://mywsq.github.io/nextjs-static-i18n

**Comment by adrai** [comment] 2021-08-13 07:17
> As @Nemo64 said, dynamic routing can be used to export static pages. I have a demo that uses react-i18next.
> 
> https://github.com/myWsq/nextjs-static-i18n
> 
> ```tsx
> import { StaticI18nLink } from "../i18n-browser";
> import { useTranslation } from "react-i18next";
> 
> const Layout: React.FunctionComponent = ({ children }) => {
>   const { t } = useTranslation("common");
> 
>   return (
>     <>
>       <nav>
>         <StaticI18nLink href="/">{t("home")}</StaticI18nLink>{" "}
>         <StaticI18nLink href="/about">{t("about")}</StaticI18nLink>
>       </nav>
>       <main>{children}</main>
>       <footer>
>         <li>
>           <StaticI18nLink locale="zh">简体中文</StaticI18nLink>
>         </li>
>         <li>
>           <StaticI18nLink locale="en">English</StaticI18nLink>
>         </li>
>       </footer>
>     </>
>   );
> };
> 
> export default Layout;
> ```
> 
> I've wrapped `next/link` to avoid using next international routing, but there are still boundary cases when using `next/router`. It's a rudimentary approach, but it works well enough for me.
> 
> It also supports setting the basePath, and here is a deployment on Github Pages.
> 
> https://mywsq.github.io/nextjs-static-i18n

Have you ever thought about creating a (static-)next-i18next module or trying to contribute to https://github.com/isaachinman/next-i18next to check if there's a possibility to offer your way as an alternative option?

**Comment by Nemo64** [comment] 2021-08-16 10:41
I haven't, and I don't think there is much an external package can do.

- If you export a completely static site: use the approach I showed above.
- If you export a fully dynamic page (backend without SSR), use i18next directly and ignore all static props features.
- If you don't export but use the server side, use the existing next-i18next package

Those are the use cases I know of. 

Most needed improvements are within next here:

- If getStaticProps would work in every situation (they don't work with dynamic routing without staticPaths), then it would be easier to make one of the existing packages work without the i18n routing feature.
- Of course it would be nice if the i18n routing feature would work as well, but I guess the first issue prevents that.

And I don't work long enough with next to address those.

**Comment by adrai** [comment] 2021-08-16 10:47
all ok, I have tried to change the next-i18next example to work with your approach: https://github.com/isaachinman/next-i18next/issues/1202#issuecomment-898581252

**Comment by herrherrmann** [comment] 2021-09-08 17:08
I’ve just responded to the Vercel support with this (sharing this here mostly to inform you peeps about my implementation suggestion):

> In my opinion, `next export` should simply export the properly-routed pages as static pages. This would restore a functionality that was working before when using Next.js in combination with [next-i18next](https://github.com/isaachinman/next-i18next). I think what is happening now is that many people (there are 100 upvotes on the related issue today) migrated their projects to Next.js version 10 which required the new i18n routing, even when using a third-party library like next-i18next. I think it is fair to expect that there should be at least feature parity between those Next.js versions but a major feature (next export) is now unusable for many – hence the disappointment.
> 
> So, I’d really appreciate if the Next.js team considers to add exporting of i18n-enabled routes (without the language detection layer and whatever else cannot be replicated during the export). This would be my suggestion.

**Comment by adrai** [comment] 2021-09-08 17:31
@herrherrmann this works also with next-i18next 😉

https://github.com/adrai/next-static-i18n-test

**Comment by iamchathu** [comment] 2021-09-20 12:36
> Hi, as mentioned in the [initial RFC](https://github.com/vercel/next.js/discussions/17078) `next export` wasn't planned for initial support. When doing a build we don't know that you're going to call `next export` so we can't show this error message earlier.
> 
> I'm going to close this since this is the expected behavior currently

How are we going to host this in netlify?

**Comment by patrick-mcdougle** [comment] 2022-01-26 03:25
Could someone who has a local fork of Next try changing: https://github.com/vercel/next.js/blob/canary/packages/next/export/index.ts#L333

to `if (i18n && !options.buildExport && !!i18n.localeDetection) {`

That is, force a user using next export to opt out of localeDetection (i.e. we know we're opting out of locale cookie / server redirects / domains) that it works? Do we run into the issue [mentioned above](https://github.com/vercel/next.js/issues/18318#issuecomment-724071925)?

Perhaps we can re-write how the server and router code behaves so we can get this working. Anyone know the code intimately enough to try this? This doesn't feel like it should be too hard. The [initial i18n routing PR](https://github.com/vercel/next.js/pull/17370/files) isn't that big.
