### ISSUE TITLE
[turbopack] dynamic import with path alias not working

### ISSUE THREAD

**Issue by stefanprobst** [vercel/next.js#61279] opened 2024-01-28 10:12 UTC
### Link to the code that reproduces this issue

https://github.com/stefanprobst/issue-turbopack-imports

### To Reproduce

1. clone reproduction repo, install deps
2. `npm run dev`
3. open http://localhost:3000 and see error message

### Current vs. Expected behavior

i have [the following dynamic imports](https://github.com/stefanprobst/issue-turbopack-imports/blob/main/lib/i18n.ts), which work with `webpack`, but not with `turbopack`:

```ts
export async function i18n(locale: string) {
  /** This works with both turbopack and webpack. */
  // const messages = await import(`../messages/${locale}.json`)

  /** This works with webpack, but fails with turbopack. */
  const messages = await import(`@/messages/${locale}.json`)

  return messages
}
```

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #202312131837 SMP PREEMPT_DYNAMIC Wed Dec 13 19:05:40 UTC 2023
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 8.14.1
Relevant Packages:
  next: 14.1.1-canary.17 // Latest available version is detected (14.1.1-canary.17).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by sokra** [comment] 2024-01-29 16:32
This is currently work in progress: https://github.com/vercel/turbo/pull/7153

**Comment by ForsakenHarmony** [comment] 2024-02-05 17:29
Closing as a duplicate of #56531

**Closed by ForsakenHarmony** 2024-02-05 17:29 UTC
Labels: template: bug, area: Turbopack
