### ISSUE TITLE
[NEXT-1103] Cannot read properties of null (reading 'useState') with Context Wrapper

### ISSUE THREAD

**Issue by SamKomesarook** [vercel/next.js#48518] opened 2023-04-18 08:10 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 19.1.0
      npm: 8.19.3
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.11
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://github.com/Kiwi-Biosciences/debug

### To Reproduce

When trying to build the project, it will fail with the following error:

`TypeError: Cannot read properties of null (reading 'useState')`

### Describe the Bug

The build fails.

### Expected Behavior

The build should succeed, as there are no visible logic or syntax errs.

### Which browser are you using? (if relevant)

Firefox 112.0

### How are you deploying your application? (if relevant)

AWS Amplify

<sub>[NEXT-1103](https://linear.app/vercel/issue/NEXT-1103/cannot-read-properties-of-null-reading-usestate-with-context-wrapper)</sub>

**Comment by elrumordelaluz** [comment] 2023-05-05 09:58
This is now happening when upgrading `next` from `v13.3.4` into `v13.4.0`. Not necessarily with 

> …(reading 'useState')

in the message, but all other hooks coming from `react`.

**Comment by Kuchasz** [comment] 2023-05-05 23:32
The same thing happens on v13.4.0 with self-hosted apps.

**Comment by huozhi** [comment] 2023-05-05 23:39
Have you tried latest patch 13.4.1 as we had a fix for that included in the patch? People mentioned in the [thread](https://github.com/vercel/next.js/discussions/43577#discussioncomment-5817906) that fixed their issue?

**Comment by jungpaeng** [comment] 2023-05-06 15:36
I am experiencing the same issue with version 13.4.1.

**Comment by SamKomesarook** [comment] 2023-05-07 10:10
@huozhi I have upgraded the demo to 13.4.1, tried building, and unfortunately it is still failing with the same er...

**Comment by jungpaeng** [comment] 2023-05-08 15:54
As an aside, I'm using pages routing and it happened in a development environment, not a build environment.

**Comment by qiangfoo** [comment] 2023-05-10 16:40
Same thing here, the build works locally, but fails on vercel.

**Comment by anil1712** [comment] 2023-05-11 12:33
Any solution? I am getting the same since one week, using next 13.2.5

**Comment by simonmares** [comment] 2023-05-16 11:57
Hi, another dev trying to **use app dir alongside existing pages** on a production app here.

I can reproduce this error using latest relevant packages:

```json
"next": "^13.4.2",
"react": "^18.2.0",
"react-dom": "^18.2.0",
```

Build does only fail on Vercel, local `next build` is fine.

**Specifics**

We encountered this issue with [swiper](https://github.com/nolimits4web/swiper) package, however the specific package is irrelevant, it's caused probably by Next bundling the third-party packages. This package is used only in pages routes.

**Workaround**

I added this package to [transpilePackages](https://nextjs.org/docs/app/api-reference/next-config-js/transpilePackages) which made the build finish. 

**Similar issues**
- https://github.com/vercel/next.js/issues/49753
- https://github.com/vercel/next.js/issues/49355

**Comment by shuding** [comment] 2023-05-16 18:00
For the original bug reproduction (https://github.com/Kiwi-Biosciences/debug), the cause was using async components inside a "use client" file, which is disallowed.

**Comment by anil1712** [comment] 2023-05-17 18:31
Older versions are also not working for me, btw I am deploying the changes into AWS Lambda Serverless Stack

**Comment by benry1** [comment] 2023-05-17 20:45
Same issue here.

App runs locally on NextJS 13.4.x, but fails with the same error after deploying to Lambda via SST. I am using 'next-auth', which I believe uses a Context wrapper.

My `getServerSideProps` completes with no issues, but before displaying the page the server throws the above as a 500 error.

Downgrading NextJS did not solve.

**Comment by anil1712** [comment] 2023-05-18 04:10
@benry1 Yes, exactly same behavior I am experiencing.

**Comment by florianbress** [comment] 2023-05-22 12:29
https://github.com/vercel/next.js/issues/50158 is this issue related? Literally getting the same issue with the pages directory. Any update on this?

**Comment by benry1** [comment] 2023-05-24 13:27
@huozhi Please find my minimal reproduction here: 
https://github.com/benry1/nextjs-ssr-fails

This requires SST to show the failure, but I am not sure if this is a NextJS or an SST issue.

**Comment by huozhi** [comment] 2023-05-24 13:56
@benry1 have you tried with the canary version? it's still using the latest. Please provide a minimal reproduction that can be deploy on codesandbox or can develop locally, the one you linked requires aws credentials etc.

**Comment by benry1** [comment] 2023-05-24 14:05
I tried the same after building the latest canary version locally, had the same issue. I wasn't sure how to embed that into the repo, so I left it as latest.

I can't reproduce this locally, it only happens when deployed on AWS, but it happens very consistently. Testing it will require aws credentials unfortunately. If that's not sufficient, feel free to re-tag this with `please add a complete reproduction`

**Comment by benry1** [comment] 2023-05-24 16:59
Update: My issue was an SST related issue. It was using an incorrect version of open-next, this has been solved in SST 2.10.1.

**Comment by jeffrafter** [comment] 2023-05-25 00:03
@benry1 I think I have run into the same issue but updating SST and any combination of next/next-auth isn't working for me. Any chance you could add some notes on how you debugged this and how you got the fix to work?

**Comment by jeffrafter** [comment] 2023-05-25 03:11
Update: I've got this working now. I'm not positive what fixed it but @gavinzanerafter and I did the following:

1. Clean install (remove node_modules, reinstall) the following:
  - `"sst": "^2.10.2",`
  - `"next": "13.4.2",`
  - `"next-auth": "4.22.1",`
2. rm -rf .next
3. rm -rf .open-next
4. Add `"use-client"` to every page tsx in the `src/pages` legacy folder
5. Redeploy

Hopefully this helps other folks <3

**Comment by dprothero** [comment] 2023-05-25 16:36
I'm running into this issue on local builds. I'm not using sst:

Reproduced on [this codesandbox](https://codesandbox.io/p/github/dprothero/mdx-remote-error/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cli2xef9p000a3t6kvei2ql01%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cli2xef9p000a3t6kvei2ql01%2522%253A%257B%2522id%2522%253A%2522cli2xef9p000a3t6kvei2ql01%2522%252C%2522activeTabId%2522%253A%2522cli2xntl200mf3t6k92vd4ogk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cli2xef9p00093t6k2iplb59y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522EMPTY_DEVTOOL%2522%252C%2522id%2522%253A%2522cli2xg7pz00qm3t6kt0sxip5d%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522cli2xn2t5000a3t6kze7ukk93%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npx%2520nx%2520serve%2520twilio-cli%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522npx%2520nx%2520serve%2520twilio-cli%2522%252C%2522port%2522%253A4200%252C%2522id%2522%253A%2522cli2xntl200mf3t6k92vd4ogk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fdocs%252Ftwilio-cli%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D):

Define the starting process: npx nx serve twilio-cli
Try to load the /docs/twilio-cli route.

**Comment by jeffrafter** [comment] 2023-05-25 16:46
This gives more info than I was seeing... 

![image](https://github.com/vercel/next.js/assets/4064/1fdb91b9-bcfa-4797-a144-6d4b4cc6826e)

**Comment by jeffrafter** [comment] 2023-05-25 18:25
@dprothero I was able to reproduce the error with your CodeSandbox.

I've tried a variety of version combinations and was still running into issues. In the end downgrading Next to ~13.2.4 solved it for me. There is likely another version in between that works. I've tested the latest canaries and still see the issue.

In the end 

* `sst@2.10.4`
* `next-auth@4.22.1`
* `next@13.2.4`

Another note for the SST case. The deployment between newer and older versions changed pretty dramatically and the caching made things tough to debug. Hitting the lambda url directly made everything considerably easier. I was never able to reproduce this locally in any configuration.

**Comment by huozhi** [comment] 2023-05-25 22:31
Feel related fixes are released in [13.4.4](https://www.npmjs.com/package/next/v/13.4.4), please try to upgrade to latest and test to see if the issue still existed. Will close this issue as there's no new reproduction testing against latest canary. If you still bumped to troubles, please file a new issue with **minimal** reproduction with latest **canary**.

**Comment by dprothero** [comment] 2023-05-26 15:17
@huozhi No, the problem still exists with 13.4.4:

[Updated codesandbox](https://codesandbox.io/p/github/dprothero/mdx-remote-error/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cli2xef9p000a3t6kvei2ql01%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cli2xef9p000a3t6kvei2ql01%2522%253A%257B%2522id%2522%253A%2522cli2xef9p000a3t6kvei2ql01%2522%252C%2522activeTabId%2522%253A%2522cli2xn2t5000a3t6kze7ukk93%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cli2xef9p00093t6k2iplb59y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cli2xg7pz00qm3t6kt0sxip5d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cli4pag0q0020fwkoboo164k3%2522%257D%252C%257B%2522id%2522%253A%2522cli2xn2t5000a3t6kze7ukk93%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npx%2520nx%2520serve%2520twilio-cli%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522npx%2520nx%2520serve%2520twilio-cli%2522%252C%2522port%2522%253A4200%252C%2522id%2522%253A%2522cli2xntl200mf3t6k92vd4ogk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fdocs%252Ftwilio-cli%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522cli4pbdtw017v3t6lq2wlegfg%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%252C%257B%2522type%2522%253A%2522EMPTY_DEVTOOL%2522%252C%2522id%2522%253A%2522cli4pbjyv01913t6laq5qfpbe%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by huozhi** [comment] 2023-05-26 15:55
@dprothero can you provide some repro steps? couldn't download from codesandbox and I found the repo, but there's no steps in readme how to start and how to repro the errors

**Comment by huozhi** [comment] 2023-05-28 10:20
Sorry for missing the steps [here](https://github.com/vercel/next.js/issues/48518#issuecomment-1563200690), looks like it because of `next-mdx-remote` is esm module and the react is not aliased

**Comment by huozhi** [comment] 2023-05-28 10:48
@dprothero it's a nx problem for their current latest version (16.2.2) as they set `__NEXT_PRIVATE_PREBUNDLED_REACT` as process env which is shouldn't be set, I think it was a workaround for previous nextjs react mismatch issue. 

```js
function withNx(_nextConfig = {}, context = getWithNxContext()) {
    // If this is not set user will see compile errors in Next.js 13.4.
    // See: https://github.com/nrwl/nx/issues/16692, https://github.com/vercel/next.js/issues/49169
    // TODO(jack): Remove this once Nx is refactored to invoke CLI directly.
    forNextVersion('>=13.4.0', () => {
        var _a;
        process.env['__NEXT_PRIVATE_PREBUNDLED_REACT'] =
            // Not in Next 13.3 or earlier, so need to access config via string
            ((_a = _nextConfig.experimental) === null || _a === void 0 ? void 0 : _a['serverActions']) ? 'experimental' : 'next';
    });
```

Looked at their code it's remove in the code, but not published yet. I think you can wait for the next version or switch to a nx version without `__NEXT_PRIVATE_PREBUNDLED_REACT` env overriden

**Closed by huozhi** 2023-05-28 10:48 UTC
Labels: please add a complete reproduction, area: app, area: data fetching, linear, type: needs triage
