### ISSUE TITLE
[i18n] getServerSideProps query parameter has gone when history back.

### ISSUE THREAD

**Issue by myriky** [vercel/next.js#20735] opened 2021-01-04 11:37 UTC
# Bug report

## Describe the bug

the query value fly away from the getServerSideProps when history back and no default Language.

(history.back && !defaultLanguage)

## To Reproduce

```
i18n: {
    locales: ['en', 'es'],
    defaultLocale: 'en',
  },
```

defaultLocale works fine.
but when set another language, getServerSideProps hasn't query parameter when history back in browser.

## Screenshots

https://user-images.githubusercontent.com/581861/103531185-28d0ce80-4ecc-11eb-99b3-e83b4fc09b7e.mov

## System information

- OS: OS X
- Browser: Chrome
- Version of Next.js: Next.js 10.0.4

**Comment by ijjk** [comment] 2021-01-04 17:13
Hi, this appears to be a duplicate of https://github.com/vercel/next.js/issues/20212 which is fixed in the latest version of Next.js `v10.0.5-canary.8` specifically [this PR](https://github.com/vercel/next.js/pull/20441), please update and give it a try!

**Closed by ijjk** 2021-01-04 17:13 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
