### ISSUE TITLE
publicRuntimeConfig is undefined when routing from ASO page

### ISSUE THREAD

**Issue by nickelghost** [vercel/next.js#23079] opened 2021-03-15 18:07 UTC
### What version of Next.js are you using?

10.0.7

### What version of Node.js are you using?

15.6.0

### What browser are you using?

Chrome & Safari

### What operating system are you using?

macOS

### How are you deploying your application?

Containers

### Describe the Bug

The publicRuntimeConfig doc states the following:

"A page that relies on publicRuntimeConfig must use getInitialProps to opt-out of Automatic Static Optimization. Runtime configuration won't be available to any page (or component in a page) without getInitialProps."

However, even if a page that uses getConfig is SSR (with getServerSideProps in my case), the config options of publicRuntimeConfig will be undefined when routing from a page that uses ASO. This is impossible to prevent since there is forced ASO for the 404 page. The only option left for people deploying configurable containerised apps is not using publicRuntimeConfig and building the app on every container start. All this makes publicRuntimeConfig useless.

### Expected Behavior

publicRuntimeConfig should be populated when navigating to SSR pages

### To Reproduce

1. Create Page A that has getServerSideProps and uses publicRuntimeConfig
2. Create Page B that uses ASO and has a Next Link to Page A
3. Create a production build of the app without any ENV variables present
4. Run the app with ENV variables injected on runtime
5. Open Page B
6. Navigate to Page A through a Next Link component

**Comment by ng-hai** [comment] 2021-03-16 16:39
I have the same issue. 
I have tried to upgrade Next to 10.0.9, or even changed `getServerSideProps` to `getInitialProps`, but nothing worked.

**Comment by ng-hai** [comment] 2021-03-23 04:27
I have resolved the issue by invoking `getConfig` inside `getServerSideProps`

**Comment by ijjk** [comment] 2021-04-28 02:55
Hi, `publicRuntimeConfig` appears to be exposed correctly for automatically statically optimized pages in the latest version of Next.js `v10.1.3` so I'm going to close this, if you're still encountering problems with this please respond with additional info to allow investigation!

**Closed by ijjk** 2021-04-28 02:55 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
