### ISSUE TITLE
Link should support relative href in dynamic routes

### ISSUE THREAD

**Issue by webdeb** [vercel/next.js#16396] opened 2020-08-20 13:34 UTC
# Feature request

The problem is that for Links inside a particular dynamic route like "/site/[slug]/comments" you have to always use the 
additional `as` prop and somehow grab the `slug` variable.

## Describe the solution you'd like

It should be possible to use relative hrefs inside dynamic routes. For example we are on some page `/site/123`
And we want to provide a Link to the comments `/site/123/comments`. Instead of writing 

```
<Link href="/site/[slug]/comments" as={`/site/${slug}/comments`}>
  <a>Comments</a>
</Link>
```

We should be able to tell the router, that `comments` is a relative path of the current page. For example:

```
<Link href="./comments">
  <a>Comments</a>
</Link>
```

**Comment by ConsoleTVs** [comment] 2020-08-21 01:10
As long as I know they already worked on reducing the boilerplate to:

```jsx
<Link href={`/site/${slug}/comments`}>
  <a>Comments</a>
</Link>
```

**Comment by yordis** [comment] 2020-09-11 15:52
We would like to have this as well,

We have dynamic interfaces where the backend configures some slugs, and mounting paths so the components don't know the mounting path.

**Comment by Timer** [comment] 2020-09-12 04:10
This is fixed in the latest Next.js version.

**Closed by Timer** 2020-09-12 04:10 UTC

**Comment by yordis** [comment] 2020-09-12 20:50
@Timer would you mind linking some link to the documentation? I am sorry if I missed it.

**Comment by Timer** [comment] 2020-09-14 02:38
https://github.com/vercel/next.js/pull/16634

**Comment by balazsorban44** [comment] 2022-01-29 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
