### ISSUE TITLE
Next/image does not work with position attributes such as "absolute", "relative", etc.

### ISSUE THREAD

**Issue by dancherb** [vercel/next.js#23087] opened 2021-03-15 20:47 UTC
### What version of Next.js are you using?

10.0.7

### What version of Node.js are you using?

12.18.3

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Local development

### Describe the Bug

The "position" key in the style object supplied to next's Image component has no effect.

### Expected Behavior

Next's Image component was expected to behave the same as the standard img component with regards to styles.

### To Reproduce

```
<NextImage width={100} height={100} src={image} style={{
                                position: "absolute",
                                top: 0,
                                left: 0
}}/>
```

**Comment by ronfogel** [comment] 2021-03-15 23:55
Instead all your props that you currently have, use `layout="fill"`

**Comment by awareness481** [comment] 2021-03-18 09:49
These are probably overwritten by `next/image`'s default inline styles. You could try using `!important`. Moreover `next/image` doesn't accept a `style` prop, you can try using `className` instead. https://nextjs.org/docs/api-reference/next/image#other-props

However, this isn't a bug.

**Comment by nersoh** [comment] 2021-03-23 00:46
Duplicate of #23095 23095

**Comment by MoOx** [comment] 2021-04-15 11:19
Not a bug indeed, per documentation.

**Closed** 2021-04-15 12:14 UTC
Labels: template: bug
