### ISSUE TITLE
Standalone export Sharp executable is not present with pnpm

### ISSUE THREAD

**Issue by dogukanoksuz** [vercel/next.js#59346] opened 2023-12-07 05:10 UTC
### Link to the code that reproduces this issue

https://github.com/limanmys/website/blob/7e9d2c005e7d3197c8aecbfc98fa458a4ee40252/.github/workflows/main.yml#L45

### To Reproduce

1. Set output to standalone on next.config.ts
2. npm run build
3. Move to standalone folder to external source for using
4. node server.js
5. Get  "Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly."
6. Move @img folder from project path node_modules to .next/standalone/node_modules
7. Problem solved

### Current vs. Expected behavior

When i build and use export, i get "Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly." error. I fixed it by myself at https://github.com/limanmys/website/blob/7e9d2c005e7d3197c8aecbfc98fa458a4ee40252/.github/workflows/main.yml#L45 but isn't it supposed to move node_modules/\@img folder to .next/standalone/node_modules?

Expected behavior is .next/standalone/node_modules folder to contain \@img folder for Sharp after exporting but at this time it is not.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 3.3.0
  pnpm: 8.10.2
Relevant Packages:
  next: 14.0.3
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Standalone mode (output: "standalone")

### Additional context

I also tested latest 14.0.4-canary.47 version still happens.

I am deploying to Ubuntu 22.04 with standalone export.

**Comment by rusted-love** [comment] 2023-12-07 08:00
Same here. Deploying with Docker + DigitalOcean App Platform.

**Comment by dafengzhen** [comment] 2023-12-07 08:14
Try using version 0.32.6 of Sharp

**Comment by dogukanoksuz** [comment] 2023-12-07 08:47
> Same here. Deploying with Docker + DigitalOcean App Platform. Docker configs based on official examples have the same error.

https://github.com/limanmys/website/blob/7e9d2c005e7d3197c8aecbfc98fa458a4ee40252/.github/workflows/main.yml#L45

@rusted-love I fixed it temporarily with this way.

**Comment by lovell** [comment] 2023-12-07 08:48
This is caused by https://github.com/vercel/nft/issues/371

**Comment by Hyodori04** [comment] 2023-12-13 02:13
Same here. I think sharp version is related.

**Comment by chrisneven** [comment] 2023-12-13 15:03
> Try using version 0.32.6 of Sharp

Yes, this works for us. Hopefully, it's a temporary solution...

@duvillierA why did you downvote?

**Comment by kasem-sm** [comment] 2023-12-17 13:41
> I tried version 0.32.6 of Sharp, but it unfortunately didn't resolve the issue for my project

v0.32.6 doesn't works for me as well :/

**Comment by Hyodori04** [comment] 2023-12-18 06:25
@ui-jb @kasem-sm 

standalone + sharp 0.32.6 not working? It works for me

**Comment by ui-jb** [comment] 2023-12-27 17:28
> @ui-jb @kasem-sm
> 
> standalone + sharp 0.32.6 not working? It works for me

I've updated my previous comment as it turned out a Dockerfile was overriding the version of sharp specified in my package.json.
I can now confirm that reverting to version 0.32 of sharp resolves the issue.

**Comment by marc0olo** [comment] 2024-01-11 23:25
finally found that issue here 🙏 any ETA to get the issue resolved? I assume a lot of people running in standalone mode will face this issue 😅

**Comment by darthmaim** [comment] 2024-01-11 23:36
> finally found that issue here 🙏 any ETA to get the issue resolved? I assume a lot of people running in standalone mode will face this issue 😅

It should already be fixed in [v14.0.5-canary.36](https://github.com/vercel/next.js/releases/tag/v14.0.5-canary.36)

**Comment by marc0olo** [comment] 2024-01-11 23:42
> It should already be fixed in [v14.0.5-canary.36](https://github.com/vercel/next.js/releases/tag/v14.0.5-canary.36)

good to know, thanks! wondering why the fix isn't linked to this issue 🤔

**Comment by darthmaim** [comment] 2024-01-11 23:47
These are the related issues/prs:
- https://github.com/vercel/next.js/pull/60172
- https://github.com/vercel/nft/pull/372
- https://github.com/vercel/nft/issues/371
- https://github.com/lovell/sharp/issues/3870

**Comment by FredTreg** [comment] 2024-01-16 10:45
Same in standalone mode, I had to revert to 0.32.6

**Comment by naminator** [comment] 2024-01-17 21:42
This worked for me:
`yarn add sharp@0.32.6 --ignore-engines`. 

Took me a while to figure this out, but it says in their installation instructions that if you're using `yarn v1`, you should install with `--ignore-engines`. 

https://sharp.pixelplumbing.com/install

**Comment by styfle** [comment] 2024-02-01 20:40
Looks like the issue in this case was pnpm has slightly different node_modules behavior than npm so some of the relevant binary files were not copied correctly.

This will be fixed in https://github.com/vercel/next.js/pull/61538 thanks!

**Closed** 2024-02-01 21:46 UTC
Labels: template: bug, area: standalone mode
