### ISSUE TITLE
[i18n] wrong extract locale from Accept-Language in Request Header

### ISSUE THREAD

**Issue by myriky** [vercel/next.js#20705] opened 2021-01-03 06:34 UTC
## Describe the bug

incorrect routing due to wrong extract locale from HTTP header.

## Expected behavior

http://localhost:3000 redirect to http://localhost:3000/ko

## System information

- Version of Next.js: 10.0.4

```
i18n: {
    locales: ['ko', 'en', 'fr', 'nl'],
    defaultLocale: 'en',
  }
```
i'm prefer using in ko-kr.
each browser sent difference format in Accept-Language Header like this.

os x, chrome ✅
Accept-Language: ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7
![스크린샷 2021-01-01 오후 6 46 47](https://user-images.githubusercontent.com/581861/103436672-bfe61e00-4c61-11eb-88a5-3039211baa30.png)

os x, safari ❌
Accept-Language: ko-kr
![스크린샷 2021-01-01 오후 6 46 37](https://user-images.githubusercontent.com/581861/103436674-c8d6ef80-4c61-11eb-81c5-67858ae6d1b9.png)

ios, chrome ❌
Accept-Language: ko-kr
![스크린샷 2021-01-01 오후 6 50 19](https://user-images.githubusercontent.com/581861/103436709-37b44880-4c62-11eb-8838-c0cee03667b8.png)

windows 10, edge ✅
Accept-Language: ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7
![KakaoTalk_Photo_2021-01-01-18-57-07](https://user-images.githubusercontent.com/581861/103436823-333c5f80-4c63-11eb-8bf7-2361ba407cf7.png)

windows 10, chrome ✅
Accept-Language: ko,en;q=0.9,en-US;q=0.8
![KakaoTalk_Photo_2021-01-01-18-57-03](https://user-images.githubusercontent.com/581861/103436831-4e0ed400-4c63-11eb-9156-bc19ffad9093.png)

windows 10, internet explorer 11 ❌
Accept-Language: ko-kr
![KakaoTalk_Photo_2021-01-01-18-57-10](https://user-images.githubusercontent.com/581861/103436841-772f6480-4c63-11eb-99b8-9599c3b4b067.png)

Except OS X Chrome, all browsers are sending not include region code.

Temporally, I put a 'ko-KR' also.

```
i18n: {
    locales: ['ko','ko-KR','en', 'fr', 'nl'],
    defaultLocale: 'en',
  }
```

but really annoying..

_Originally posted by @myriky in https://github.com/vercel/next.js/issues/18676#issuecomment-753295967_

**Comment by timneutkens** [comment] 2021-01-03 10:16
Duplicate of comment: https://github.com/vercel/next.js/issues/18676#issuecomment-753295967. There's no need to open a new issue for a comment on an existing issue that covers your case.

**Closed by timneutkens** 2021-01-03 10:16 UTC

**Comment by balazsorban44** [comment] 2022-01-28 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
