### ISSUE TITLE
Placeholder/Blurry/LQP images for Next/Image and possibility for static export

### ISSUE THREAD

**Issue by gauravkrp** [vercel/next.js#20230] opened 2020-12-16 14:02 UTC
Hi NextJS team, the Image component is really great. Thanks!
Earlier I had written a custom module for the same using the sharp and next-optimised-images

I've started using it in all my new projects but there are two important things that are still missing to make this Image component even greater!

1. Options to generate blurred preview or low quality placeholder images so that the container area doesn't look blank. Currently I'm using layout="responsive" and when new image area appears on the screen, it remains blank until the image downloads. And if the internet is slow at that time, it gives a very bad experience as it remains empty for so long and doesn't feel like if there is an image.

2. Currently I cannot run ````next export````. I read that vercel is only supported. 
I will like provision to readily export some predefined optimized image sizes for next/export in the next.config.js as not all of my websites will go live on a nodejs server.

3. Provision for background image optimisation.

4. Option to preload nearby images, that is, images next to viewport.

**Comment by lachlanjc** [comment] 2021-01-02 05:02
Hey! Combined issues like this don't usually get attention—I recommend splitting them up :)

1. This issue is covered by #18858.
2. > The next/image component's default loader is not supported when using `next export`. However, [other loader options](https://nextjs.org/docs/basic-features/image-optimization#loader) will work.
3. I think this was a design choice, so they don't slow down builds or build up an unnecessary cache.
4. You'll have better luck with this as a separate issue I think :+1: would certainly be handy in certain situations.

**Comment by timneutkens** [comment] 2021-01-03 15:16
Closing as the issue template was ignored/removed.

**Closed by timneutkens** 2021-01-03 15:16 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-28 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
