### ISSUE TITLE
Preview Mode has getServerSideProps({ preview, previewData }) in dev builds, not production builds.

### ISSUE THREAD

**Issue by xiata** [vercel/next.js#17958] opened 2020-10-16 20:14 UTC
# Bug report

## Describe the bug

Preview Mode does not work correctly in production.

In development mode, /[...slug].js endpoint's `getServerSideProps(props)` receives props `preview` and `previewData` as mentioned by documentation.
In production mode, /[...slug].js endpoint's `getServerSideProps(props)` does not receive those props, despite `__next_preview_data` and `__prerender_bypass` cookies present in the request.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Setup preview mode per docs.
1. Build /[...slug].js endpoint that uses getServerSideProps({ params, preview, previewData }). This page should send preview and previewData as props to be rendered so you can see it working or not.
2. Start server in development mode
3. Hit your /api/preview endpoint.
4. Observe preview and previewData are present on your test page, as well as the preview mode cookies.
5. Clear your cookies.
6. Stop the server
7. Build for production.
8. Start the server in production mode
9. Hit your /api/preview endpoint again to start preview mode again.
10. **Observe preview and previewData are NOT present on your test page, but the cookies are present.**

## Expected behavior

Development and production mode to actually behave the same instead of being completely broken in production builds.

## System information

- OS: macOS 10.15.7
- Browser: Chrome stable
- Version of Next.js: 9.5.5
- Version of Node.js: 12.18.4

**Comment by jamesmosier** [comment] 2020-10-26 01:46
Hi @xiata. Could you create a repository that reproduces this?

**Comment by sathovsepyan** [comment] 2020-11-06 16:19
Hi @xiata. Did you find any solution for this? I'm facing the same problem.

**Comment by anthwinter** [comment] 2021-01-13 14:53
I'm also having the same issue. Reproduction repo with instructions in the README.

https://github.com/anthwinter/nextjs-ssr-preview-bug

**Comment by anthwinter** [comment] 2021-01-20 23:02
The resolution for me was to run a production build with HTTPS protocol and not HTTP.

https://github.com/vercel/next.js/issues/15972

**Comment by ijjk** [comment] 2021-09-19 06:06
Hi, this appears to be working correctly in the latest version of Next.js `v11.1.2` so I'm going to close this. Note: as mentioned above HTTPS is required for the preview mode cookie to be set correctly with `next start`.

**Closed by ijjk** 2021-09-19 06:06 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
