### ISSUE TITLE
Build issue with subpath imports of internal "compiled" package

### ISSUE THREAD

**Issue by OllieJennings** [vercel/next.js#67095] opened 2024-06-21 08:07 UTC
### Link to the code that reproduces this issue

[https://codesandbox.io/p/github/shaunjohann/turbo-starter/main](https://codesandbox.io/p/github/shaunjohann/turbo-starter/main?file=%2Fapps%2Fdocs%2Fpackage.json%3A12%2C17&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxode4w80007356jelno35k2%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxode4w80002356jpvio8saz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxode4w80004356j970xja2g%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxode4w80006356jegxoov8u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxode4w80002356jpvio8saz%2522%253A%257B%2522id%2522%253A%2522clxode4w80002356jpvio8saz%2522%252C%2522activeTabId%2522%253A%2522clxoepz1z02u4356jc8odplzf%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxode4w80001356jsmj227u1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxodf1oy0037356j6u7cotw6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A17%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A17%257D%255D%252C%2522filepath%2522%253A%2522%252Fapps%252Fdocs%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapps%252Fdocs%252Fapp%252Flayout.tsx%2522%252C%2522id%2522%253A%2522clxoepz1z02u4356jc8odplzf%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clxode4w80006356jegxoov8u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxode4w80005356jp8tawmd1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxode4w80006356jegxoov8u%2522%252C%2522activeTabId%2522%253A%2522clxode4w80005356jp8tawmd1%2522%257D%252C%2522clxode4w80004356j970xja2g%2522%253A%257B%2522id%2522%253A%2522clxode4w80004356j970xja2g%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxodh3mq00h8356jpb0oa2lb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxodh3bb000rd9j7hgtwegax%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%252C%2522id%2522%253A%2522clxoedjxb027j356jey1xvlo9%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxoedjxb027j356jey1xvlo9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### To Reproduce

1. In the repo above run `next dev` and everything will run fine.
2. Run `next build` and the build with error

---

Below is for doing it locally

1. Define subpath imports for an internal package in a turborepo monorepo:

```json
"imports": {
    "#utils/*": "./src/utils/*",
    "#organization/*": "./src/organization/*",
    "#organization-role/*": "./src/organization-role/*"
  },
```

2. Utilize this in some file: `import { StringOrDateSchema, timezone } from "#utils/index.js";`

3. Compile internal package via `tsc` into internal "compiled" package

4. Run `next dev` in a nextjs project which deps on the above, which will run perfectly fine (no issues)

5. Run `next build` which throws the issue:

```
Failed to compile.
Module not found: Can't resolve '#utils/index.js'
```

### Current vs. Expected behavior

Current Behaviour: nextjs will run the dev server just fine, but any build will fail.

Expected Behaviour: it should just work.

As per the docs of turborepo, you recommend subpath imports over tsconfig paths.

However it seems like nextjs does not support these.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Mar 29 23:14:13 UTC 2024
  Available memory (MB): 31698
  Available CPU cores: 32
Binaries:
  Node: 21.0.0
  npm: 10.2.0
  Yarn: N/A
  pnpm: 9.3.0
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Module Resolution

### Which stage(s) are affected? (Select all that apply)

next build (local), Vercel (Deployed)

**Comment by boylec** [comment] 2024-07-29 20:15
I'm getting the same behavior with webpack on Next.JS 14.2.5

**Comment by OllieJennings** [comment] 2024-08-07 15:03
Summoning @leerob or @timneutkens as l think the turbo-repo docs are recommending something that nextjs doesn't support yet: 

E.g. https://turbo.build/repo/docs/guides/tools/typescript#use-nodejs-subpath-imports-instead-of-typescript-compiler-paths

**Comment by lubieowoce** [comment] 2024-08-13 14:31
Hey @OllieJennings, thanks for opening the issue. I can't find an `"imports"` field or usage of `"'#utils/index.js'"` anywhere in the linked codesandbox. Could you please update the code to reproduce the issue you're describing?

(Also removing some of packages not relevant to the repro would be appreciated, that starter contains a lot of code)

**Comment by OllieJennings** [comment] 2024-08-13 17:22
@lubieowoce let me re-create one, it seems like my sandbox link is now broken somehow, will do it within the next hr

**Comment by OllieJennings** [comment] 2024-08-14 07:57
@lubieowoce i almost have the full repo working: https://codesandbox.io/p/github/BJR-developer/basic-turborepo/csb-25k8gf/subpath-imports-repo.

Just a few tweaks but it should help you get started on debugging

**Comment by lubieowoce** [comment] 2024-08-14 12:07
I believe this is not a Next.js issue, but an incorrectly configured/build package. It looks like `imports` act unintuitively in typescript. The issue here is that the alias makes code from `dist` (js) try to import code from `src` (ts) which obviously fails. Examples in the TS docs also show that [`imports` should point to files in `dist`, not in `src`](https://www.typescriptlang.org/docs/handbook/modules/reference.html#packagejson-imports-and-self-name-imports).

---

Here's a more detailed explanation.

If you compile `@repo/test-pkg` and try to import it in Node, it fails too:
```console
$ pnpm turbo build --filter='@repo/test-pkg'
<snip>
$ ( cd apps/web && node -p 'import("@repo/test-pkg/somefile")' )

Promise { <pending> }
node:internal/modules/esm/resolve:264
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '<REPO>/packages/test-pkg/src/utils/some-thing.js' imported from <REPO>/packages/test-pkg/dist/some-file.js
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///<REPO>/packages/test-pkg/src/utils/some-thing.js'
}
```

If we look closely, we'll see that this is because `dist/some-file.js` still contains the `"#utils/some-thing.js"` import...
```js
import { helloSomething } from "#utils/some-thing.js";
export function somefile() {
    helloSomething();
    console.log("IN HERE");
    return "return from some file";
}
```
and out `imports` look like this...
```json
  "imports": {
    "#utils/*": "./src/utils/*"
  },
```
...so the import alias in package.json makes `#utils/some-thing.js` point to `src/utils/some-thing.js`, **which doesn't exist**! for the compiled output, we should be aliasing to `dist/utils/some-thing.js` instead.

So this is annoying, and honestly, I'm not sure what the right way to work around it is. Of course you can just make `imports` point into `dist`, but that'll probably requires running a `tsc --watch` to have editor stuff work right.

One possible trick is an `imports` like this. It seems to work (TS resolves it fine in vscode, and the import works in Node)
```json
  "imports": {
    "#utils/*": {
      "types": "./src/utils/*",
      "default": "./dist/utils/*"
    }
  },
```

**Comment by lubieowoce** [comment] 2024-08-15 12:59
@OllieJennings does that work for you?

**Comment by OllieJennings** [comment] 2024-08-15 14:14
@lubieowoce l feel like a bit of an idiot, it seems to be working, but am just testing by migrating some of my internal packages in my monorepo to this.

**Comment by lubieowoce** [comment] 2024-08-16 08:35
Okay, I'm gonna close this, let us know if you find any Next.js-specific problems with this

**Closed by lubieowoce** 2024-08-16 08:35 UTC
Labels: Module Resolution

**Comment by nathan1530** [comment] 2024-08-20 03:21
@lubieowoce But the main point of [Just-in-Time Packages](https://turbo.build/repo/docs/core-concepts/internal-packages#just-in-time-packages) is not to build/tranpile the `tsx` or `ts` files. So directly export typescript from `src/*` should be fine.

**Comment by lubieowoce** [comment] 2024-08-20 10:26
If you're using  Next.js's `transpilePackages`, then `"imports": { "#utils/*": "./src/utils/*" }` works fine. In fact that's the only one that will work, because no `dist` folder will be created (unlike `tsc`).

Maybe we should consider supporting`imports` that point to files in `tsconfig.json#compilerOptions.outDir` even if they don't exist on disk -- TSC already seems to resolve things this way when typechecking.

**Comment by lubieowoce** [comment] 2024-08-20 12:33
I've also forwarded this to the Turborepo team, so their docs should include some info about this soon :)

**Comment by geclos** [comment] 2024-08-28 09:56
Hi,

I'm pretty sure `next build` does not support subpath imports. I've done this [example repo](https://github.com/geclos/subpath-imports-example) to demonstrate it.

**Comment by lubieowoce** [comment] 2024-09-05 08:44
@geclos I looked at your repo, and AFAICT your issue only appears **if using `transpilePackages` on a package that uses `#imports`**. if we disable `transpilePackages` and convert  `packages/ui` to be compiled with `tsc`, then `next build` runs fine.

<details>

<summary>What to change to see this</summary>

```diff
diff --git a/apps/web/next.config.mjs b/apps/web/next.config.mjs
index 6dcda59..4678774 100644
--- a/apps/web/next.config.mjs
+++ b/apps/web/next.config.mjs
@@ -1,6 +1,4 @@
 /** @type {import('next').NextConfig} */
-const nextConfig = {
-  transpilePackages: ['@repo/ui']
-};
+const nextConfig = {};
 
 export default nextConfig;
diff --git a/packages/ui/package.json b/packages/ui/package.json
index 0e51c09..06284ad 100644
--- a/packages/ui/package.json
+++ b/packages/ui/package.json
@@ -3,14 +3,15 @@
   "version": "0.0.0",
   "private": true,
   "exports": {
-    "./button": "./src/button.tsx",
-    "./card": "./src/card.tsx",
-    "./code": "./src/code.tsx"
+    "./button": "./dist/button.js",
+    "./card": "./dist/card.js",
+    "./code": "./dist/code.js"
   },
   "imports": {
-    "#*": "./src/*"
+    "#*": "./dist/*"
   },
   "scripts": {
+    "build": "tsc",
     "lint": "eslint . --max-warnings 0",
     "generate:component": "turbo gen react-component"
   },
diff --git a/packages/ui/tsconfig.json b/packages/ui/tsconfig.json
index ca86687..b21e74a 100644
--- a/packages/ui/tsconfig.json
+++ b/packages/ui/tsconfig.json
@@ -1,6 +1,7 @@
 {
   "extends": "@repo/typescript-config/react-library.json",
   "compilerOptions": {
+    "rootDir": ".",
     "outDir": "dist"
   },
   "include": ["src"],
```

(to apply this change easily, you can download this file: [compile-ui-with-tsc.patch](https://github.com/user-attachments/files/16886390/compile-ui-with-tsc.patch), and `git apply PATH_TO_THAT_FILE` in the root of your repo)

</details>

So yeah, I'd open a separate issue regarding `transpilePackages` specifically. Thanks!
(Also, please remove redundant packages/apps like `apps/docs` from the repro, it makes our work easier)
