### ISSUE TITLE
Default locale behavior changes when adding any rewrites

### ISSUE THREAD

**Issue by jvarho** [vercel/next.js#25019] opened 2021-05-12 04:15 UTC
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04

### How are you deploying your application?

next start

### Describe the Bug

Subpath locale works differently if any rewrites are defined. With a create-next-app test application, if the only change I made is:

```
module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en']
  }
}
```
Now I can build, start and open localhost:3000/en successfully.

However, if I add any rewrites, e.g.

```
module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en']
  },
  async rewrites() {
    return [
      {
        source: '/foo',
        destination: '/bar'
      }
    ]
  }
}
```

Now when after a rebuild and start I open localhost:3000/en the location changes to localhost:3000 – i.e. the default locale is dropped.

With more complex applications I have tested that this only happens with static pages (html or ssg). SSR pages leave the locale untouched.

This unexpected location change does not happen with 10.0.7, but does with at least 10.2.0 and 10.0.9 and 10.2.1-canary.5.

### Expected Behavior

All pages should work the same and having rewrites should not change things. Preferably default locale would always be added or always be stripped, but even leaving it alone would be fine.

### To Reproduce

1. create-next-app
2. downgrade react 17.0.2 to 17.0.1 (I get an exception in js console when using 17.0.2)
3. copy the next.config.js content from above
4. npm run build
5. npm start
6. navigate to http://localhost:3000/en

**Comment by ijjk** [comment] 2021-09-21 02:27
Closing in favor of https://github.com/vercel/next.js/discussions/18419

**Closed by ijjk** 2021-09-21 02:27 UTC
Labels: template: bug

**Comment by jvarho** [comment] 2021-09-21 05:15
@ijjk This is a bug/inconsistency in current behavior. Implementing that feature might fix this in the process, but I don't see that the two are dependent. This could be fixed by always removing the default prefix, always adding it, or leaving the address as is.

**Comment by balazsorban44** [comment] 2022-01-27 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
