### ISSUE TITLE
Optional catch all routes and getStaticPaths

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#13467] opened 2020-05-27 21:45 UTC
How should one prerender the rootmost route when using optional catch all routes and `getStaticPaths`?

`undefined`? `null`? An empty Array `[]`?

---

Also reported:
```
Page                                                           Size     First Load JS
┌ ● /[[...slug]]                                               335 B            59 kB
├   ├ /[]
├   ├ /[one]
├   ├ /[one/two]
├   └ /[one/two/three]
```

https://github.com/zackkrida/next-experimental-catchall-bug/blob/master/pages/%5B%5B...slug%5D%5D.js

**Comment by dohomi** [comment] 2020-05-27 23:52
@Timer I tried `[], ["/"]` but both without success yet.

**Comment by esteban89** [comment] 2020-06-04 22:26
Hi, did you find a solution to this?

**Comment by Timer** [comment] 2020-06-05 00:43
cc @Janpot is this fixed now?

**Comment by Janpot** [comment] 2020-06-05 05:41
This was fixed by https://github.com/vercel/next.js/pull/13559
any of these will prerender the root:
```js
[
  { params: { slug: [] } },
  { params: { slug: null } },
  { params: { slug: false } },
  { params: { slug: undefined } }
]
```

**Closed** 2020-06-05 06:18 UTC
Labels: type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-29 15:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
