### ISSUE TITLE
Export with v13 appDir uses wrong paths 

### ISSUE THREAD

**Issue by echowarp** [vercel/next.js#43417] opened 2022-11-26 21:12 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 19.1.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.6-canary.1
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Firefox 107

### How are you deploying your application? (if relevant)

Static Export

### Describe the Bug

`next dev` and `next build` both work, but `next export` fails. 

```
info  - Copying "static build" directory
info  - No "exportPathMap" found in "\next.config.js". Generating map from "./pages"
info  - Launching 19 workers
info  - Copying "public" directory
info  - Exporting (2/2)
PageNotFoundError: Cannot find module for page: /r
    at Object.getPagePath (\next\dist\server\require.js:77:15)
    at \next\dist\export\index.js:375:48
    at Array.map (<anonymous>)
    at \next\dist\export\index.js:366:69
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (\node_modules\next\dist\trace\trace.js:79:20) {
  code: 'ENOENT'
}
```

The main issue seems to be that the appPathsManifest includes "/page" at the end of every path in the dictionary in /dist/server/require.js -> getMaybePagePath()
```
appPathsManifest {
  '/page': 'app/page.js',
  '/r/page': 'app/r/page.js',
  '/r/[slug]/page': 'app/r/[slug]/page.js',
  '/upcoming/page': 'app/upcoming/page.js'
}
```

I was able to get export working again by adding two things which are undoubtedly not the right way to fix it. 

First, in /dist/server/require.js - getMaybePagePath() I rewrite the appPathsManifest to have both versions of the path, both with and without the "/page" suffix:
```
for (const key in appPathsManifest) {
    let newkey = key.replace(/\/page$/, "");
    if (newkey === "") {newkey = "/"}
    appPathsManifest[newkey] = appPathsManifest[key];
}
```

Second, in dist/export/index.js - exportApp() I modified the line:
`const orig = (0, _path).join(distPagesDir, route);`
to
`const orig = (0, _path).join(distDir, "server/app", route);`
because distPagesDir started from a sub directory in the app (in my case "/r") and then duplicated that subdirectory again.
`distPagesDir = "\build\server\app\r"; distDir="\build`

### Expected Behavior

Running `next export` should build the static site without errors.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/vercel/app-playground

### To Reproduce

1. Setup the V13 appDir playground with npm i
   - on Windows, you have to remove "@vercel/git-hooks" from `package.json` first, since it requires symlinks.
2. Add `"export": "next export"` to the `package.json` scripts.
3. Run `npm build`
4. Run `npm export`

```
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

info  - using build directory: \next-app-playground\.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "\next-app-playground\next.config.js". Generating map from "./pages"
info  - Launching 19 workers
info  - Copying "public" directory
info  - Exporting (2/2)
PageNotFoundError: Cannot find module for page: /isr
    at Object.getPagePath (\next-app-playground\node_modules\next\dist\server\require.js:77:15)
    at \next-app-playground\node_modules\next\dist\export\index.js:375:48
    at Array.map (<anonymous>)
    at \next-app-playground\node_modules\next\dist\export\index.js:366:69
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (\next-app-playground\node_modules\next\dist\trace\trace.js:79:20) {
  code: 'ENOENT'
}
```

**Comment by angkarn** [comment] 2022-11-28 09:11
#42282

**Comment by otrebu** [comment] 2023-02-01 15:03
Is there an issue that tracks all the issues related to app dir and the export functionality?
I am just trying to work out when it might be ready by.

**Comment by cseas** [comment] 2023-02-18 17:00
> Is there an issue that tracks all the issues related to app dir and the export functionality? I am just trying to work out when it might be ready by.

- https://github.com/vercel/next.js/issues/42282 has been closed.
- This issue probably will be closed too.
- Another duplicate is: https://github.com/vercel/next.js/issues/44002
- Another duplicate reported in app directory feedback: https://github.com/vercel/next.js/discussions/41745#discussioncomment-5017474

Supporting `next export` in app directory is a planned feature not supported yet. So the Next.js team doesn't consider this a bug.

Best we can do is keep an eye on the roadmap: 
https://beta.nextjs.org/docs/app-directory-roadmap#supported-and-planned-features

@leerob @timneutkens Can the error message be somehow changed to indicate the feature is not supported? There have been multiple duplicate reports of this and the error message really looks like a bug instead of an unsupported feature.

**Comment by Kosta-Github** [comment] 2023-02-28 08:00
It would also be very helpful it it would be mentioned within the documentation here: https://nextjs.org/docs/advanced-features/static-html-export

**Comment by jlarmstrongiv** [comment] 2023-04-14 12:09
Was this resolved in https://nextjs.org/blog/next-13-3#static-export-for-app-router and https://beta.nextjs.org/docs/configuring/static-export ?

**Comment by leerob** [comment] 2023-04-16 03:32
Indeed, this should be fixed now! 🙏 Please open a new issue with a reproduction if you're seeing this still. Thanks!

**Closed by leerob** 2023-04-16 03:32 UTC
Labels: template: bug, area: app
