### ISSUE TITLE
i18n routing with getStaticProps and getStaticPaths, first item provided to getStaticProps is empty

### ISSUE THREAD

**Issue by wiesson** [vercel/next.js#18404] opened 2020-10-28 17:53 UTC
# Bug report

## Describe the bug

It looks like that the first element provided to `getStaticProps` is empty while using i18n and `getStaticPaths`:

```Javascript
export const getStaticPaths = async ({ locales }) => {
  // generate dummy pages
  const items = [
    "123_a", "234_b", "345_c", "456_d",
  ];

  // create paths
  const paths = locales.reduce(
    (acc, next) => [
      ...acc,
      ...items.map((slug) => ({
        params: {
          slug,
        },
        locale: next,
      })),
    ],
    []
  );

  return {
    paths,
    fallback: true,
  };
```

Generated paths:
```Javascript
[
  { params: { slug: "123_a" }, locale: "de" },
  { params: { slug: "234_b" }, locale: "de" },
  { params: { slug: "345_c" }, locale: "de" },
  { params: { slug: "456_d" }, locale: "de" },
  { params: { slug: "123_a" }, locale: "en" },
  { params: { slug: "234_b" }, locale: "en" },
  { params: { slug: "345_c" }, locale: "en" },
  { params: { slug: "456_d" }, locale: "en" },
  { params: { slug: "123_a" }, locale: "fr" },
  { params: { slug: "234_b" }, locale: "fr" },
  { params: { slug: "345_c" }, locale: "fr" },
  { params: { slug: "456_d" }, locale: "fr" },
  { params: { slug: "123_a" }, locale: "it" },
  { params: { slug: "234_b" }, locale: "it" },
  { params: { slug: "345_c" }, locale: "it" },
  { params: { slug: "456_d" }, locale: "it" },
];
```

getStaticProps
```Javascript
export const getStaticProps = async ({ params, locale }) => {
  const { slug } = params;

  const id = slug.match(/\d{3}/)[0]; // fails, because slug is undefined

  return {
    props: { slug, id, locale },
    revalidate: 1,
  };
};
```

With the first item, params is empty, but locale is set (de).

Error message: 

```
18:24:27.197  	info  - Generating static pages (0/46)
18:24:27.444  	info  - Generating static pages (11/46)
18:24:27.446  	Unhandled error during request: TypeError: Cannot read property 'match' of undefined
18:24:27.447  	    at getStaticProps (/vercel/workpath0/.next/serverless/pages/items/[slug].js:1059:19)
18:24:27.447  	    at renderToHTML (/vercel/workpath0/node_modules/next/dist/next-server/server/render.js:26:115)
18:24:27.447  	    at async renderReqToHTML (/vercel/workpath0/.next/serverless/pages/items/[slug].js:890:22)
18:24:27.447  	    at async Object.exportPage [as default] (/vercel/workpath0/node_modules/next/dist/export/worker.js:12:92)
18:24:27.447  	Error occurred prerendering page "/items/[slug]". Read more: https://err.sh/next.js/prerender-error
18:24:27.447  	TypeError: Cannot read property 'match' of undefined
18:24:27.448  	    at getStaticProps (/vercel/workpath0/.next/serverless/pages/items/[slug].js:1059:19)
18:24:27.448  	    at renderToHTML (/vercel/workpath0/node_modules/next/dist/next-server/server/render.js:26:115)
18:24:27.448  	    at async renderReqToHTML (/vercel/workpath0/.next/serverless/pages/items/[slug].js:890:22)
18:24:27.448  	    at async Object.exportPage [as default] (/vercel/workpath0/node_modules/next/dist/export/worker.js:12:92)
18:24:27.455  	info  - Generating static pages (22/46)
18:24:27.464  	info  - Generating static pages (34/46)
18:24:27.494  	info  - Generating static pages (46/46)
18:24:27.494  	> Build error occurred
18:24:27.496  	Error: Export encountered errors on following paths:
18:24:27.496  		/items/[slug]
18:24:27.496  	    at exportApp (/vercel/workpath0/node_modules/next/dist/export/index.js:25:1103)
18:24:27.496  	    at runMicrotasks (<anonymous>)
18:24:27.496  	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
18:24:27.496  	    at async build (/vercel/workpath0/node_modules/next/dist/build/index.js:39:69)
18:24:27.510  	npm ERR! code ELIFECYCLE
18:24:27.510  	npm ERR! errno 1
18:24:27.511  	npm ERR! nextjs-i18n-static-error@0.1.0 build: `next build`
18:24:27.511  	npm ERR! Exit status 1
18:24:27.511  	npm ERR! 
18:24:27.511  	npm ERR! Failed at the nextjs-i18n-static-error@0.1.0 build script.
18:24:27.512  	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
18:24:27.518  	npm ERR! A complete log of this run can be found in:
18:24:27.518  	npm ERR!     /vercel/.npm/_logs/2020-10-28T17_24_27_512Z-debug.log
18:24:27.523  	Error: Command "npm run build" exited with 1
18:24:29.426  	Done with "package.json"
```

## To Reproduce

Example: https://github.com/wiesson/nextjs-i18n-static-error

## Expected behavior

I expect that getStaticProps only receives items that has been defined by `getStaticPaths`

## System information

Deployed on vercel.

**Comment by wiesson** [comment] 2020-10-28 19:55
In addition, If I add 

```Javascript
  if (!slug) {
    return {
      notFound: true,
      props: {},
      revalidate: 1,
    };
  }
```
It looks like that revalidation has been disabled for the whole locale.

**Comment by domcoleman** [comment] 2020-10-29 05:31
This is failing because you have `fallback: true` along with the reason you commented in the code above.
Make sure that you can call the index of `slug.match` first and it builds everything for me.

```js
const slugMatch = slug.match(/\d{3}/);
const id = slugMatch ? slugMatch[0] : '';
```

**Comment by wiesson** [comment] 2020-10-29 05:57
Yes, `fallback: true` to enable statically generate additional pages. I did not expect that data empty data is passed during the build and if I remember it correctly, it wasn't the case for Next < v10.

It looks like that the correct way to handle it is `notFound: true`. With your approach, I'm passing wrong parameters because I expect that a slug is given

**Comment by timneutkens** [comment] 2020-10-29 12:48
> I did not expect that empty data is passed during the build and if I remember it correctly, it wasn't the case for Next < v10.

Rendering the page without data was already the default behavior when using fallback. However this can be handled better so marked it as a bug 👍

**Closed** 2020-11-02 20:41 UTC
Labels: kind: bug, point: 3

**Comment by SalahAdDin** [comment] 2021-04-17 23:09
What's the solution for this problem?

**Comment by balazsorban44** [comment] 2022-01-28 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
