### ISSUE TITLE
Javascript doesn't work when Next JS runs inside iframe in Storyblok CMS

### ISSUE THREAD

**Issue by jon64digital** [vercel/next.js#13680] opened 2020-06-02 16:56 UTC
# Bug report

## Describe the bug

When I run my site (Next JS 9.4.4) inside the Storyblok content editor (which places it inside an iframe) then no Javascript is run on the site and as such the screen stays blank because of a fix added to a recent Next release to hide the FOUC.

I think javascript execution stops because of the following error:

```
Error was not caught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at initializeBuildWatcher (http://localhost:3000/_next/static/runtime/main.js?ts=1591116741992:11757:38)
    at http://localhost:3000/_next/static/runtime/main.js?ts=1591116741992:13020:40
(anonymous) @ next-dev.js:48
Promise.catch (async)
(anonymous) @ next-dev.js:30
./node_modules/next/dist/client/next-dev.js @ next-dev.js:30
__webpack_require__ @ bootstrap:797
checkDeferredModules @ bootstrap:44
webpackJsonpCallback @ bootstrap:31
(anonymous) @ main.js?ts=1591116741992:1
```

## To Reproduce

It is not possible to reproduce the problem without logging into a private Storyblok account to see it.

## System information

- OS: [Windows]
- Browser [chrome]
- Version of Next.js: [9.4.4]

**Comment by marbiano** [comment] 2020-06-02 19:19
I think this is related to [this one](https://github.com/vercel/next.js/issues/7426). I'm working on a solution for it as we speak.

**Comment by dohomi** [comment] 2020-06-11 12:56
possibly related to https://github.com/vercel/next.js/issues/11356#issuecomment-632736283

**Comment by jon64digital** [comment] 2020-06-16 12:36
@timer - I see the "needs investigation" tag has been added to this ticket. If I can do anything to help then please let me know. I'd be happy to give somebody with a Vercel email address access to the CMS.

**Comment by jon64digital** [comment] 2020-06-29 12:21
A little more info, this only seems to happen on localhost. I published to an Azure url today and it doesn't seem to happen. Very odd.

**Comment by dohomi** [comment] 2020-06-30 00:16
@jon64digital I have this issue deployed to Vercel as well as on localhost

**Comment by timneutkens** [comment] 2021-11-18 09:41
Next.js no longer uses localStorage, I believe since Next.js 11 or so. Could you try again with the latest version?

**Comment by balazsorban44** [comment] 2022-01-20 00:15
Gentle push @jon64digital if you are still interested in this, could you please check out a newer version of Next.js? (as of writing it is `12.0.8`)

**Comment by jon64digital** [comment] 2022-01-20 00:16
Hi.

I'm not currently working on that site unfortunately, but I will be starting a new site using Next/Storyblok, so I will know soon.

**Comment by dohomi** [comment] 2022-01-20 01:37
I use Next/Storyblok and the issue is no longer present. I think the issue can be safely closed.

**Comment by balazsorban44** [comment] 2022-01-20 01:49
Closing for now since @dohomi could not see this issue anymore, but feel free to report back @jon64digital

**Closed by balazsorban44** 2022-01-20 01:49 UTC
Labels: please add a complete reproduction, type: upstream, type: needs investigation, kind: story
