### ISSUE TITLE
next/image build error with typescript

### ISSUE THREAD

**Issue by mattiaz9** [vercel/next.js#28707] opened 2021-09-01 13:08 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14

### What browser are you using?

not relevant

### What operating system are you using?

macOS

### How are you deploying your application?

next start 

### Describe the Bug

After upgrading from 11.1.0 to 11.1.2, I get this TS error when trying to compile with `next build`:
`Type error: Subsequent property declarations must have the same type.  Property 'loading' must be of type '"eager" | "lazy" | undefined', but here has type '"auto" | "eager" | "lazy" | undefined'.`

file: `./node_modules/next/types/index.d.ts:46:5`

This doesn't happen when `skipLibCheck: true` is set in the `tsconfig.json`

### Expected Behavior

To compile without errors!

### To Reproduce

First put the Image component in any page. This is how I use the `next/image` in my components:
```
<Image
  src={bgImage.url}
  placeholder="blur"
  blurDataURL={bgImage.responsiveImage!.base64}
  layout="fill"
  loading="eager"
  alt={bgImage.responsiveImage!.alt}
/>
```

 Then try to build with `next build`

**Comment by Jhappy77** [comment] 2021-09-02 03:29
I have the same issue, and same versions, but I didn't need to include next/image in my project for the issue to occur

**Comment by timneutkens** [comment] 2021-09-02 08:33
This has been fixed on next@canary, can you give it a try?

**Closed by timneutkens** 2021-09-02 08:33 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 21:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
