### ISSUE TITLE
Reading file works differently on getStaticProps during build time and during ISR - Works fine in local - Issue only on vercel

### ISSUE THREAD

**Issue by MiltonAkash** [vercel/next.js#27065] opened 2021-07-10 08:04 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

15.12.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

![image](https://user-images.githubusercontent.com/21121073/125156444-070a1a00-e183-11eb-9107-1ca4ff68aaa8.png)

I have a folder in the root data/dist with many json files inside. I read them in my `getStaticProps` . Some important paths are given in `getStaticPaths` which are working fine.  Wtih fallback as true/blocking Everything working properly in local both in dev and production mode. but on Vercel it is throwing the above error

![image](https://user-images.githubusercontent.com/21121073/125156505-67995700-e183-11eb-8f36-2017e43c920e.png)

### Expected Behavior

It should work same as local 

### To Reproduce

The repo is public. You can try reading a json file in build vs during runtime from getstaticprops on vercel

**Comment by ijjk** [comment] 2021-07-10 19:53
Hi, this appears to be a duplicate of https://github.com/vercel/next.js/issues/24700

**Closed** 2021-12-23 02:50 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 01:27
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
