### ISSUE TITLE
Allow configuring `localsConvention` in CSS-loader

### ISSUE THREAD

**Issue by ricokahler** [vercel/next.js#14295] opened 2020-06-18 00:23 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

We love the improvements y'all have been making in SSG and we opted to migrate from Gatsby to Next.js!

However, a relatively small semi-blocker is the inability to configure the [`localsConvention`](https://github.com/webpack-contrib/css-loader#localsconvention) option within `css-loader`. In Gatsby, they use [`css-loader` 1.x](https://github.com/gatsbyjs/gatsby/blob/777ab658ab46414377fc8b92610898446bd0714b/packages/gatsby/package.json#L51) with the option [camelCase:](https://github.com/webpack-contrib/css-loader/tree/v1.0.1#camelcase) [dashesOnly](https://github.com/gatsbyjs/gatsby/blob/777ab658ab46414377fc8b92610898446bd0714b/packages/gatsby/src/utils/webpack-utils.ts#L202) [(described here)](https://github.com/gatsbyjs/gatsby/blob/075e2da3ed856486eafbd935195d72e6facbcd85/docs/docs/migrating-from-v1-to-v2.md#update-css-modules-class-names-that-use-dashes).

## Describe the solution you'd like

I see that y'all are [using the latest css-loader](https://github.com/vercel/next.js/blob/a841d109542026f1beb61c87bc409b98eea9b680/packages/next/package.json#L87), and the feature request I'm looking for is the possibility of configuring the options of the loader or some similar effect.

## Describe alternatives you've considered

I could probably make it work by editing the css chain via next's webpack config.

---

Let me know what you think! I would also be wiling to work on this feature if you're accepting PRs. Thanks a bunch!

Sorry if I missed anything, I'm new here :D

**Comment by illuminist** [comment] 2020-06-18 05:13
Check this  https://github.com/vercel/next.js/discussions/14156#discussioncomment-26086, it's a way to find and config css-loader in webpack.

**Comment by TroyTae** [comment] 2020-08-04 02:49
If you still interest in this feature, please participate in this discussion :)
https://github.com/vercel/next.js/discussions/15818

**Comment by timneutkens** [comment] 2020-08-04 08:17
Closing in favor of #15818

**Closed by timneutkens** 2020-08-04 08:17 UTC

**Comment by balazsorban44** [comment] 2022-01-29 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
