### ISSUE TITLE
After updating to nextjs 12.0.1, next-middleware-ssr-loader gives an error saying _document not found.

### ISSUE THREAD

**Issue by 0xBono** [vercel/next.js#30501] opened 2021-10-28 01:34 UTC
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### How are you deploying your application?

next dev (development mode)

### Describe the Bug

After updating to 12.0.1 version

```
  // nextjs-12 version setup
  experimental: {
    reactRoot: true,
    esmExternals: true,
    concurrentFeatures: true,
    serverComponents: true,
  },
  swcMinify: true,
```

```bash
error - ./node_modules/next/dist/build/webpack/loaders/next-middleware-ssr-loader/index.js?page=-web%2F&absolutePagePath=%2FUsers%2Fjam%2FDesktop%2issue%2Fexample-react%2Fsrc%2Fpages%2Findex.tsx&isServerComponent=false&buildId=development&basePath=&assetPrefix=!
Module not found: Can't resolve '/Users/jam/Desktop/issuesssss/issue/pages/_document' in '/Users/jam/Desktop/issuesssss/issue'
```

### Expected Behavior

There seems to be a problem with the ServerComponent side.
However, when the **ServerComponent** is false, an error occurs on the other side.
When it is terminated, there seems to be a problem in **SSR**.

### To Reproduce

```
  // nextjs-12 version setup
  experimental: {
    reactRoot: true,
    esmExternals: true,
    concurrentFeatures: true,
    serverComponents: true,
  },
  swcMinify: true,
```

```
    "next": "^12.0.2-canary.2",
    "react": "npm:react@18.0.0-alpha-3c4c1c470-20211021",
    "react-dom": "npm:react-dom@18.0.0-alpha-3c4c1c470-20211021",
    "@next/eslint-plugin-next": "^12.0.1",
```

**Comment by shuding** [comment] 2021-10-30 00:11
Closing as it's duplicated with #30424, will track there 👍

**Closed by shuding** 2021-10-30 00:11 UTC
Labels: template: bug, area: Concurrent Features

**Comment by balazsorban44** [comment] 2022-01-27 13:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
