### ISSUE TITLE
Prevent headers from overwriting immutable assets

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#19114] opened 2020-11-12 18:00 UTC
For Vercel, leverage:
https://github.com/vercel/vercel/pull/5409

**Comment by ijjk** [comment] 2020-12-01 22:09
Closing as this was addressed in https://github.com/vercel/vercel/pull/5452

**Closed by ijjk** 2020-12-01 22:09 UTC
Labels: kind: bug, point: 2

**Comment by balazsorban44** [comment] 2022-01-29 02:12
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
