### ISSUE TITLE
Image component unsized => dangerouslyUseUnsizedImage

### ISSUE THREAD

**Issue by styfle** [vercel/next.js#18469] opened 2020-10-29 12:51 UTC
- Deprecate `unsized` property
- Rename `unsized` to `dangerouslyUseUnsizedImage` to make it clear this should rarely be used
- Add support for more layout options

**Comment by Timer** [comment] 2020-10-29 12:57
IMO `dangerouslyUseUnsizedImage` might be a bit verbose. Maybe `dangerouslyUnsized` is short enough?

We should also console log in dev for every image that uses `dangerouslyUnsized` saying that it should pretty much **never** be used, as a different `layout` mode is the way to go.

**Comment by Timer** [comment] 2020-10-31 05:46
Duplicate of #18541 as we're eliminating the property.

**Closed by Timer** 2020-10-31 05:46 UTC
Labels: kind: bug, point: 2

**Comment by balazsorban44** [comment] 2022-01-29 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
