### ISSUE TITLE
using revalidatePath but getting error for revalidateTag just in vercel not in local

### ISSUE THREAD

**Issue by iamsoltan** [vercel/next.js#49861] opened 2023-05-16 14:13 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.3-canary.1
      eslint-config-next: 13.3.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue
https://gitlab.com/khemeri.med.khalil/test-revalidation
### To Reproduce

Created an api revalidation endpoint to handle single post revalidation from webhooks 
and this is the code app/api/revalidate/post/route.ts :
`
import { NextRequest, NextResponse } from "next/server";
import { revalidatePath } from "next/cache";

export async function POST(request: NextRequest) {
  const body = await request.json();
  console.log("post revalidation body : ", JSON.stringify(body));
  revalidatePath("/post/" + body?.slug?.current);
  return NextResponse.json({ revalidated: true, now: Date.now() });
}
`

### Describe the Bug

so instead of working normally or getting an error related to revalidatePath , I got an error that seems related to revalidateTag :
**I got this error after triggering a webhook to vercel, local prod mode no issue detected :**
`
post revalidation body :  {"_id":"60e008f3-5a71-486f-a645-10ade5630450","slug":{"current":"how-to-create-a-revalidation-api-endpoint-in-next-js-using-the-app-router","_type":"slug"}}
Failed to revalidate tag post/how-to-create-a-revalidation-api-endpoint-in-next-js-using-the-app-router Error: Request failed with status 500.
    at FetchCache.revalidateTag (/var/task/node_modules/next/dist/server/lib/incremental-cache/fetch-cache.js:92:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async /var/task/.next/server/chunks/3616.js:2786:25
` 

### Expected Behavior

returned error should be related to revalidatePath not to revalidateTag

### How are you deploying your application? (if relevant)

Vercel

**Comment by iamsoltan** [comment] 2023-05-17 12:15
The problem mentioned had already existed in a previous version of Next.js a year ago and was successfully resolved at that time. However, with the introduction of the latest version of the app route, the issue has resurfaced once again.
this is the last year issue : [https://github.com/vercel/next.js/issues/38306](url)
More clarification about the issue : 
problem does not occur when revalidating '/' or static route , but it occurs with dynamic route "/post/[slug]" for example

**Comment by ijjk** [comment] 2023-05-18 04:50
Closing in favor of https://github.com/vercel/next.js/issues/49387 as this appears to be a duplicate of that

**Comment by ijjk** [comment] 2023-05-18 04:51
Hi, can you share a reproduction/deployment where you are seeing the `revalidatePath()` throw a 500 error?

**Comment by iamsoltan** [comment] 2023-05-18 10:12
This is the repo ( no special code included ) : `https://gitlab.com/khemeri.med.khalil/test-revalidation`
**Update : ( problem found in the revalidationPath() !)**
     ```
After conducting several tests, I have found that including more than 58 characters in the [slug] parameter will produce the error:
     case 1 :  ?path=understanding-inversion-of-control-dependency-inversion-pr === no problem (58 char)
     case 2 :  ?path=understanding-inversion-of-control-dependency-inversion-pri === Error thrown (59 char) addded the "i" char.

     I created get method to test the revalidatePath()

     1.Get : problem detected on vercel
     /api/revalidate/get_method?path=

**Comment by iamsoltan** [comment] 2023-05-19 08:57
> Hi, can you share a reproduction/deployment where you are seeing the `revalidatePath()` throw a 500 error?

Please check the previous comment

**Comment by nabildroid** [comment] 2023-05-24 08:44
i got this issue
 static generation store missing in revalidateTag

**Comment by mavic111** [comment] 2023-05-24 21:28
i got this issue recently. But it only raising error on dynamic route that created at build time. 

If you create a dynamic route on demand by creating new post in the CMS, then after that you make changes in the content, it does not raising error. But yeah, the revalidating itself still failed (data not updated)

**Comment by nabildroid** [comment] 2023-05-24 21:34
I wonder why they don't write tests to insure everything is working before releasing new version that suppose to be Stable!

**Comment by mavic111** [comment] 2023-05-24 21:36
> This is the repo ( no special code included ) : `https://gitlab.com/khemeri.med.khalil/test-revalidation` I've made a deploy on vercel if that usefull : https://test-revalidation.vercel.app/ **Update : ( problem found in the revalidationPath() !)** ``` After conducting several tests, I have found that including more than 58 characters in the [slug] parameter will produce the error: case 1 : ?path=understanding-inversion-of-control-dependency-inversion-pr === no problem (58 char) case 2 : ?path=understanding-inversion-of-control-dependency-inversion-pri === Error thrown (59 char) addded the "i" char.
> 
> ```
>  I created get method to test the revalidatePath()
> 
>  1.Get : problem detected on vercel
>  /api/revalidate?path=
> ```
> 
> ![Screenshot from 2023-05-18 13-44-12](https://user-images.githubusercontent.com/61824434/239238173-8e6a9a88-fa21-4da6-a51c-c7bb1f870061.png)

i can confirm this. But the revalidation itself still failed right? even the slug is below 58 char.

**Comment by nabildroid** [comment] 2023-05-24 21:38
You can solve this by moving the revalidation route to app folder if you are using it

**Comment by pookmish** [comment] 2023-05-24 22:35
I'm not encountering the 500 error, but the revalidation doesn't actually occur. I'm not sure if my issue is related. App directory w/ Next 13.4.3. Both Vercel and Local

**Comment by lubakravche** [comment] 2023-05-24 23:33
We have a fix going out for the unexpected 500 issue and are still investigating single path revalidate.

**Comment by mavic111** [comment] 2023-05-26 06:44
The 500 error seems already fixed in 13.4.4 stable 👍. But revalidatePath still not fixed.

**Comment by iamsoltan** [comment] 2023-05-26 08:40
> The 500 error seems already fixed in 13.4.4 stable +1. But revalidatePath still not fixed.

yes there is no error throwing but revalidation still not working.

**Comment by iamsoltan** [comment] 2023-06-12 11:34
@swarnava 
Hi , after testing , it doesn't seem to be working, failed to revalidate a route and there is no error throwing in vercel.

**Comment by iamsoltan** [comment] 2023-06-13 10:20
@swarnava @ijjk @lubakravche 
Today the blog article is refreshed on every request , the same as using getServerSideProps, no cache is used , this is the article page code :
`/** Add your relevant code here for the issue to reproduce */
export default async function Home() {
  const posts = (await (await fetch("https://api.jsonbin.io/v3/b/648700e79d312622a36e46cd")).json())?.record;
  return (
    <>
      {posts.map((e) => (
        <div key={e.id}>{e.content}</div>
      ))}
      <div>{JSON.stringify(posts)}</div>
    </>
  );
}
` 

[https://gitlab.com/khemeri.med.khalil/test-revalidation/-/blob/main/app/blog/%5Bslug%5D/page.tsx](url)

**Comment by elie222** [comment] 2023-07-07 17:49
This really needs some attention. Critical and basic functionality.

**Comment by palmamartin** [comment] 2023-07-18 08:43
Any updates on this issues. Revalidation is still broken on Vercel.

**Comment by wscotten** [comment] 2023-07-20 06:37
Any updates on this?  Not sure how such a critical feature like cache invalidation can be broken for multiple months.

**Comment by leerob** [comment] 2023-07-23 17:32
If you are seeing an issue, please attach a reproduction using _the latest canary_ to ensure this is not already fixed. The reproduction at the start of this issue is using a much older version, for example.

**Comment by wscotten** [comment] 2023-07-23 18:34
Hey @leerob!  The issue I was running into a few days ago was that `revalidatePath`/`revalidateTag` wasn't working with regular functions, only arrow functions in a route handler.

For example this wouldn't work:
```js
export async function GET() {
  revalidateTag('tag1');

  return NextResponse.json({ revalidated: true });
}
```

However this would:
```js
export const GET = () => {
  revalidateTag('tag1');

  return NextResponse.json({ revalidated: true });
}
```

I just tried to create a minimal demo showing this bug in action but it wouldn't repro for whatever reason.  You can close this issue in my opinion.

**Comment by leerob** [comment] 2023-07-24 19:50
> I just tried to create a minimal demo showing this bug in action but it wouldn't repro for whatever reason. 

If anyone stumbles onto here and has a reproduction of this still happening, please open a new issue with full details and we can dig in 😄

**Closed by leerob** 2023-07-24 19:50 UTC
Labels: please add a complete reproduction, template: bug, area: Edge, type: needs triage

**Comment by iamsoltan** [comment] 2023-07-26 09:21
@leerob this is the repo : https://gitlab.com/khemeri.med.khalil/test-revalidation
it does not work with the latest canary version

**Comment by iamsoltan** [comment] 2023-07-26 09:24
@leerob  in this blog post page I am just using a simple rest api to mock a change in data:
https://gitlab.com/khemeri.med.khalil/test-revalidation/-/blob/main/app/blog/[slug]/page.tsx?ref_type=heads

you can use any other rest api service or you can create one with nextjs then deploy it

**Comment by palmamartin** [comment] 2023-07-26 10:15
@iamsoltan looking at the [revalidation API endpoint](https://gitlab.com/khemeri.med.khalil/test-revalidation/-/blob/main/app/api/revalidate/route.ts?ref_type=heads#L8) of your repo, I assume you try to revalidate the path with a literal route segment e.g. `/blog/my-first-blog-post` or `/blog/123`.  

But `revalidatePath` needs instead a path to the filesystem, in your case it should be `revalidatePath("/blog/[slug]")`. Here the [link](https://nextjs.org/docs/app/api-reference/functions/revalidatePath#parameters) to the docs where it is explained.

**Comment by iamsoltan** [comment] 2023-07-26 11:09
@palmamartin Thanks a lot for your intervention, so by consequences , all paths under "/blog" will be revalidated in this case. 
=> so single path will trigger all paths ?
@leerob  Hopes that nextjs could rethink about.

**Comment by iamsoltan** [comment] 2023-07-26 11:22
@palmamartin @leerob , revalidatePath works perfectly after @palmamartin remark, it revalidate all paths

**Comment by adxxtya** [comment] 2023-07-27 20:25
@palmamartin, I have a modal form which when submitted updates the data on my "/" path, obviously using `revalidatePath("/")` won't work, but I am using the (site) file naming convention [this](https://nextjs.org/docs/app/building-your-application/routing/route-groups#convention) for the home "/" path. I tried using (site) but it doesn't work, what could be done in such scenario?
