### ISSUE TITLE
next/image + Typescript + styled-components = ??

### ISSUE THREAD

**Issue by FMGordillo** [vercel/next.js#19764] opened 2020-12-03 03:20 UTC
# Bug report

## Describe the bug

Using the libraries above, I've found something weird: I cannot put `layout="fixed"` because it is not recognized as a prop.

## To Reproduce

1. Create your project with Typescript
2. Add `styled-components`
3. Make your component like Expected behavior
4. See the error for yourself
```

## Expected behavior

```jsx
import Image from "next/image
const MyImage = styled(Image)`
  grid-area: left-image;
`;
// ...
    <LeftHandImage
      width={350}
      height={330}
      layout="fixed"    // This will throw a ts error
      src="/images/my-image.png"
    />
```

Layout should show itself as an error:

```
Property 'layout' does not exist on type 'IntrinsicAttributes & Pick<Pick<ImageProps, "slot" | "title" | "children" | "src" | "width" | "height" | "loading" | "key" | "alt" | "crossOrigin" | ... 258 more ... | "objectPosition"> & Partial<...>, "slot" | ... 267 more ... | "objectPosition"> & { ...; } & { ...; }'
```

## Screenshots

![image](https://user-images.githubusercontent.com/7970174/100959461-0f1f1e80-34fd-11eb-81d0-db64841de59b.png)

## System information

- OS: Pop!_OS 20.10
- Browser -
- Version of Next.js: 10.0.3
- Version of Node.js: 14.15.0
- Deployment: next

## Additional context

https://github.com/vercel/next.js/issues/18949#issue-738480321 might be a related

**Comment by johnnyomair** [comment] 2020-12-03 07:14
I'm experiencing the same issue when creating a wrapper component around `Image`

```typescript
const WrappedImage: React.FunctionComponent<Omit<NextImageProps, "src" | "width" | "height">> = (nextImageProps) => {
    console.log(nextImageProps.layout);
    ...
};
```

I receive the following error message: `Property 'layout' does not exist on type 'PropsWithChildren<Pick<ImageProps, "loading" | "key" | "alt" | "crossOrigin" | "decoding" | "referrerPolicy" | "sizes" | "useMap" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | ... 254 more ... | "objectPosition">>'`.

I believe this might have to do something with the `layout` prop missing in the [`unsized` branch](https://github.com/vercel/next.js/blob/20949612dfb56e44a623498eb3237a69177229e5/packages/next/client/image.tsx#L48) of `ImageProps`.

Any ideas? I'd be willing to submit a PR to resolve the issue.

**Comment by sctgraham** [comment] 2020-12-04 10:45
I've got the same issue and can confirm the johnnyomair's diagnosis. A PR would be welcome.

**Comment by AjitZero** [comment] 2020-12-04 12:56
> * Version of Next.js: 10.0.2

Try with 10.0.3. Seems to be fixed.

**Comment by FMGordillo** [comment] 2020-12-05 18:07
> > * Version of Next.js: 10.0.2
> 
> Try with 10.0.3. Seems to be fixed.

Nope, still with the same error. I will update this issue to the latest.
Can you provide us with the snippet that might've solved this? Just curious

**Comment by lqze** [comment] 2020-12-09 23:51
You could try `Exclude<ImageProps, { width?: never; height?: never; unsized: true }>` as a workaround in the meantime.

**Comment by damla** [comment] 2021-01-02 22:15
I got a similar problem with the usage of **objectFit** property. I solved it with giving prop type of **objectFit**  as **ImageProps["objectFit"]**, which is shown in below.

```jsx
import React from "react";
import styles from "./image-box.module.scss";
import Image, { ImageProps } from "next/image";
import classNames from "classnames";

interface Props {
  src: string,
  alt: string,
  objectFit: ImageProps["objectFit"],
  wider?: boolean,
  priority?: boolean
}

export default function ImageBox({ src, alt, objectFit, wider, priority }: Props) {

  return (
    <div className={classNames(styles.container, wider && styles.container__wider)} >
      <Image
        src={src}
        alt={alt}
        layout="fill"
        objectFit={objectFit}
        priority={priority}
      />
    </div>
  );
}
```

**Comment by Timer** [comment] 2021-01-04 19:38
It sounds like styled components' types may be clobbering our `layout` property. I'd suggest opening an issue with them to fix their types, if that's the case.

I'll close this issue because there's nothing actionable we can take / our types are correct and work fine without styled-components.

**Closed by Timer** 2021-01-04 19:38 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
