### ISSUE TITLE
New Project - jemalloc: Unsupported system page size

### ISSUE THREAD

**Issue by Jao8** [vercel/next.js#39311] opened 2022-08-04 01:15 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

npx --no-install next info

 Operating System:
      Platform: linux
      Arch: arm64
      Version: #2 SMP Mon Jun 13 21:08:46 PDT 2022
    Binaries:
      Node: 18.7.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.4-canary.11
      eslint-config-next: 12.2.3
      react: 18.2.0
      react-dom: 18.2.0

Other infos:
  Image: Oracle-Linux-8.6-aarch64-2022.06.30-0 (CentOS based distro)
  uname -a: 
      Linux virtualmachine 5.4.17-2136.308.9.el8uek.aarch64 #2 SMP Mon Jun 13 21:08:46 PDT 2022 aarch64 aarch64 aarch64 GNU/Linux

### What browser are you using? (if relevant)

Not relevant

### How are you deploying your application? (if relevant)

yarn dev

### Describe the Bug

When I run the project(freshly created) it does not start, instead  the following output is given:
```bash
yarn run v1.22.19
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - SWC minify release candidate enabled. https://nextjs.link/swcmin
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 10 bytes failed
error Command failed with signal "SIGABRT".
```

Complementary info:
```sh
$ getconf PAGESIZE 
65536(64k)
```
I've found this [issue](https://github.com/fluent/fluent-bit/issues/4270) thats seems to be the same problem in a docker project(not related to next.js), not sure if can be of any help.

### Expected Behavior

The project start with the default next.js page

### Link to reproduction

https://github.com/Jao8/projects-hub

### To Reproduce

```sh
yarn create next-app --typescript <project-name>;
yarn dev;
```

**Comment by kwonoj** [comment] 2022-08-04 02:23
The link you referred seems to be the correct root cause for the issue. Solving problem seems not easy though. There is way to configure specific page size at compile time, but jemalloc seems not support it for runtime and our build target is not per-distro but more of platform (linux) + arch, which means we don't have fine grained targets for specific linux distro like oracle.

I presume this is SWC's upstream issue. /cc @kdy1 to double confirm just in case.

**Comment by kdy1** [comment] 2022-08-04 04:11
I also think it's an upstream issue

**Comment by balazsorban44** [comment] 2022-08-04 21:31
I'm closing this as this is currently unactionable in Next.js. I would suggest to reopen this in SWC or even in the upstream dependency. 🙏

**Closed by balazsorban44** 2022-08-04 21:31 UTC
Labels: type: upstream, template: bug, area: SWC Minify
