### ISSUE TITLE
ChunkLoadError: Loading chunk node_modules_next_dist_client_dev_noop_js failed

### ISSUE THREAD

**Issue by paales** [vercel/next.js#29455] opened 2021-09-28 10:21 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.x

### What browser are you using?

Chrome

### What operating system are you using?

MacOX

### How are you deploying your application?

vercel

### Describe the Bug

I couldn't find a bug reported yet.

Sometimes while starting the development environment it seems that the .next cache gets corrupted.

<img width="992" alt="Screenshot 2021-09-28 at 12 06 52" src="https://user-images.githubusercontent.com/1244416/135069100-fc720336-5d57-4ecf-959f-2bc7ef0aabc5.png">
<img width="974" alt="Screenshot 2021-09-28 at 12 06 57" src="https://user-images.githubusercontent.com/1244416/135069154-71c5fe12-934d-49a7-a0f6-d5cba64add7c.png">
<img width="971" alt="Screenshot 2021-09-28 at 12 07 04" src="https://user-images.githubusercontent.com/1244416/135069168-bb8bfb24-d901-45a1-a829-b5f5dc42977d.png">

https://stackoverflow.com/questions/67652612/chunkloaderror-loading-chunk-node-modules-next-dist-client-dev-noop-js-failed

### Expected Behavior

I wouldn't expect this error to occur.

### To Reproduce

I'm not exactly sure..

**Comment by samymedia** [comment] 2021-09-28 14:42
try to delete the next build folder, it worked for me.

**Comment by paales** [comment] 2021-09-29 07:21
That indeed works, maybe I didn't make it clear: There is a workaround, delete the `.next` folder and it will work. However, it shouldn't happen or the error should be more clear, right? 🙂

**Comment by neilDuToit133** [comment] 2022-08-04 14:48
Almost a year later. Stackoverflow answer now at 54 000 views 518 upvotes. How anything at all is a higher priority that this is beyond me. This bug alone is a good enough reason for me to want to start migrating off Next.

**Comment by ijjk** [comment] 2022-08-05 02:03
Hi, can someone who has experienced this confirm this is still being encountered in the latest version of Next.js `v12.2.4`? We have updated webpack a few times since this was opened and I am not able to reproduce this currently in the latest version.

**Comment by paales** [comment] 2022-08-30 15:24
I have never seen this in the last half year I think and for me it is resolved. Maybe since SWC, I don't know for sure.

**Comment by eFFeeMMe** [comment] 2022-09-05 09:27
> can someone who has experienced this confirm this is still being encountered in the latest version of Next.js

I'm experiencing this issue (I mean `ChunkLoadError`, not necessarily of the `node_modules_next_dist_client_dev_noop_js` chunk) on production deploys using Next 12.2.5. Unfortunately I'm still unable to reproduce the issue reliably.

**Comment by ijjk** [comment] 2022-09-05 16:21
@eFFeeMMe the mentioned error doesn't sound related to this issue as this is specific to the dev error `node_modules_next_dist_client_dev_noop_js`. The `ChunkLoadError` itself can occur in production due to network issues or similar that cause the chunk to fail to load. This can be caught by adding a `.catch()` to dynamic imports and then optionally doing a hard navigation or rendering an error state. 

If a `ChunkLoadError` occurs for any internal Next.js requests we will automatically do a full page navigation to tolerate this. 

I'm gonna close this specific issue now as it appears to be resolved. If you are having separate issues from this please open a new issue and we can investigate those further!

**Closed by ijjk** 2022-09-05 16:21 UTC
Labels: kind: bug
