### ISSUE TITLE
next dev --turbo not working with `aws-amplify`

### ISSUE THREAD

**Issue by adarsh-drishya** [vercel/next.js#56844] opened 2023-10-14 18:28 UTC
### Link to the code that reproduces this issue

https://github.com/adarsh-drishya/next-turbo-bug

### To Reproduce

1. Do npx create-next-app@latest
2. npm install aws-ampliy
3. in the page.js inside of app folder, do import { Auth } from 'aws-amplify'
4. then in useEffect, add this line     Auth.currentAuthenticatedUser().then(res=>console.log(res))
5. now run next dev --turbo,

### Current vs. Expected behavior

Bug: the error clearly comes out as below on the browser tab.
`
Error resolving EcmaScript Modules request
unable to resolve module "fs"
It was not possible to find the requested file.
    Parsed request as written in source code: module "fs"
    Path where resolving has started: [project]/node_modules/@aws-sdk/util-
defaults-mode-node/node_modules/@aws-sdk/shared-ini-file-loader/dist-es/get
SSOTokenFromFile.js
    Type of request: EcmaScript Modules request
    Import map: No import map entry
`
Expectation: The page should render without anything.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows Server 2019 Datacenter
Binaries:
  Node: 16.16.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.7-canary.14
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Turbopack (--turbo)

### Additional context

I verified in the latest canary version as well. does not work there.

**Comment by adarsh-drishya** [comment] 2023-10-14 18:36
![image](https://github.com/vercel/next.js/assets/108795907/5c75b3e7-9b55-4f07-b8af-7b511812efac)

**Comment by adarsh-drishya** [comment] 2023-10-15 14:56
hi @timneutkens i have created the issue here, please clone and see for yourself. this is blocking me to use the --turbo mode. I trust you are prioritizing this issue as i just cant use it and likewise all the amplify developers are facing the same issue.

**Comment by GarryOne** [comment] 2023-10-19 00:27
It's the same as:

https://github.com/vercel/next.js/issues/51157

**Comment by adarsh-drishya** [comment] 2023-10-19 02:05
there has been no traction on this for long time now @GarryOne

**Comment by Quix44** [comment] 2023-11-04 11:05
Bump - still facing this issue.

**Comment by ForsakenHarmony** [comment] 2024-01-16 14:34
Closing as a duplicate of #51157

It does seem like the issue is fixed though

**Closed by ForsakenHarmony** 2024-01-16 14:34 UTC
Labels: template: bug, area: Turbopack
