### ISSUE TITLE
Why can't I have an option of {fallback: true} and keeping static site generation with front-end fetching?

### ISSUE THREAD

**Issue by dev-cyprium** [vercel/next.js#22897] opened 2021-03-09 09:02 UTC
### Describe the feature you'd like to request

For my client, I have a Next.JS app that I statically inject into the Laravel project and then serve it, as a static web-site. Thanks to Next this allows me to get the benefits of SEO. However, I came across a weird problem.

I have 100+ projects in the backend that I render as cards on the site, and users can click those cards to go on the project view page. So it's a typical route `projects/[id].js]`

```jsx
import projectService from "@/utils/projects";

export async function getStaticProps({ params }) {
   const project = await projectService.get(params.id);
   return { props: { project } };
}

export async function getStaticPaths() {
    const projects = await projectService.listPub();
    const paths = projects.data.projects.map((project) => ({ paarms: { id: `${project.id}` }}));

    return { paths, fallback: false };
}
```

This works, because `projects.listPub()` only gets me the first 10 latest projects. And for the other 90+ projects, I get 404.

### Describe the solution you'd like

Why can't I have a solution that still allows me to render a project that's not pre-rendered, and fetch it at **client-side**?

This will:
  1) allow me to keep my stack
  2) allow me good SEO for the 10 latest projects, and fetch from the archive on the front end

I propose something like this:
```javascript
export async function getStaticPaths() {
   // fetching code...
   return { paths, fallback: 'client-side' }; // or similar
}
```

Then, the `getSaticProps()` function would only be called for the 10 projects that are returned by the paths, and for the other ones, we would just call the react component with null or something similar, and then I would be able to "fall-back" fetching the data on front-end. This even works with export, as it would generate a "fallback.html" page, which will be able to have this logic.

```jsx
export default function Project({ project }) {
   useEffect(() => {
      if (project === null)  {
          // okay, we didn't statically render for this project, let's render it on front-end
          // we can still show the client a "loader" and get them something so they know something is happening
          // the data wouldn't just be populated.
      ]
   }, [project]);
}
```

### Describe alternatives you've considered

The only thing I can do in this case is picked between:
 - just opt-in and generate 100+ pages at build time to keep my static export
 - completely discuss with the client and make him change his mind about his hosting stack, which is kinda impossible since another compy is responsible for this. ( After I can use `{falback: true}` and use `node.js` to serve the app

**Comment by M1ck0** [comment] 2021-03-09 09:36
You can. 

You need to read `fallback` from docs more carefully. I had a project with 100k+ pages on it. I decided to render 100 of them on build time and others on run time.

https://nextjs.org/docs/basic-features/data-fetching#fallback-true

This will allow you to load pages that are not created on the build time

**Comment by dev-cyprium** [comment] 2021-03-09 09:48
Though, one important note that's part of my question. Yes, you can set `fallback: true` but this **removes the ability to use export** as stated by the docs:

> `fallback: true` is not supported when using `next export`

This is stated by the docs, and for this client, the way I'm serving this application **relies on having** `next export` work, because that's how I tie the projects together. 

I wanted to suggest a way to use "fallback" and still preserve the `next export` command, and the way I suggested that is solved is by rendering the data on the front-end.

**Comment by ijjk** [comment] 2021-04-28 03:05
Hi, with `fallback: true` a server is required to generate the pages at runtime, if you use `fallback: false` with `next export` you can configure your custom set-up to fall-back to the `/post/[slug].html` file and handle loading the data custom although once you use `next export` handling this configuration is outside of the scope of Next.js as it's server is no longer being used. 

I'm going to close this as it doesn't sound like a bug and appears to be working as expected.

**Closed by ijjk** 2021-04-28 03:05 UTC
Labels: template: story

**Comment by icy-meteor** [comment] 2022-01-26 09:41
@dev-cyprium Did you manage to find any workaround to achieve the intended behaviour?
