### ISSUE TITLE
_resolveRewrites["default"] exception when using rewrites() config

### ISSUE THREAD

**Issue by mpiorowski** [vercel/next.js#25024] opened 2021-05-12 06:40 UTC
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

15.2.0

### What browser are you using?

firefox

### What operating system are you using?

popos

### How are you deploying your application?

next dev

### Describe the Bug

I have this config set up ->
`module.exports = {
  async rewrites() {
    return [
      {
        source: '/api',
        destination: 'http://localhost:4000/graphql',
      },
    ];
  },
  pageExtensions: ['page.tsx', 'api.ts']
};
`

No matter which page i load now, even with only text, without any api, i got the following exception:
`
Unhandled Runtime Error
TypeError: _resolveRewrites["default"] is not a function
`

After deleting rewrites() inside config the error dissaper.

### Expected Behavior

Working proxy setup.

### To Reproduce

Set the current config and try to load any page.

**Comment by timneutkens** [comment] 2021-05-12 11:56
Can you try `next@canary`, we landed a patch for a similar issue yesterday.

**Comment by nmcdaines** [comment] 2021-05-12 12:13
@mpiorowski I was having this issue the other day and found a way of getting around proxying requests through next was to add the cors header in the next.config.js and also on your api server. You would want to remove this in production.

Hope it helps!

```
// next.config.js
module.exports = {
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "Access-Control-Allow-Credentials", value: "true" },
          { key: "Access-Control-Allow-Origin", value: "localhost" },
          { key: "Access-Control-Allow-Methods", value: "*" },
          { key: "Access-Control-Allow-Headers", value: "*" },
        ]
      },
    ]
  }
}
```

**Comment by mpiorowski** [comment] 2021-05-12 16:39
Don't know if i should lcose it as it it not ine the main branch yet :)

**Comment by timneutkens** [comment] 2021-05-12 16:46
Yeah this should be closed 👍

**Closed by timneutkens** 2021-05-12 16:46 UTC
Labels: template: bug

**Comment by minhoyooDEV** [comment] 2021-05-13 02:19
same here

**Comment by balazsorban44** [comment] 2022-01-28 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
