### ISSUE TITLE
Standalone output + outputFileTracingExcludes: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by revmischa** [vercel/next.js#60301] opened 2024-01-06 07:08 UTC
### Link to the code that reproduces this issue

https://github.com/revmischa/next-repro-outputFileTracingExcludes

### To Reproduce

I have a couple medium-sized Next projects, one pages and one app router. My output bundle contains many dev dependencies like webpack and sass and esbuild. I tried adding patterns to remove them using:
```ts
    outputFileTracingExcludes: {
      "*": [
        "node_modules/@esbuild*",
        "node_modules/sass*",
       ]
   }
``` 
and many variants thereof. This works okay but if I do 
```ts
 outputFileTracingExcludes: {
      "*": [
        "node_modules/@esbuild*",
        "node_modules/sass*",
        "node_modules/webpack*",
       ]
   }
```

Then I get this error:

```
> my-app@0.1.0 build /Users/cyber/dev/next-tracing-excludes/my-app
> next build

   ▲ Next.js 14.0.4
   - Experiments (use at your own risk):
     · outputFileTracingRoot

 ✓ Creating an optimized production build
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
 ✓ Generating static pages (5/5)
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at parse (/Users/cyber/dev/next-tracing-excludes/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:9078)
    at picomatch.makeRe (/Users/cyber/dev/next-tracing-excludes/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:21670)
    at picomatch (/Users/cyber/dev/next-tracing-excludes/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:19637)
    at /Users/cyber/dev/next-tracing-excludes/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:19294
    at Array.map (<anonymous>)
    at picomatch (/Users/cyber/dev/next-tracing-excludes/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:19286)
    at micromatch.isMatch (/Users/cyber/dev/next-tracing-excludes/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/micromatch/index.js:15:1090)
    at /Users/cyber/dev/next-tracing-excludes/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/collect-build-traces.js:245:48
    at shouldIgnore (/Users/cyber/dev/next-tracing-excludes/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/collect-build-traces.js:75:9)
    at /Users/cyber/dev/next-tracing-excludes/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/collect-build-traces.js:86:23
    at Array.every (<anonymous>)
    at shouldIgnore (/Users/cyber/dev/next-tracing-excludes/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/collect-build-traces.js:86:7)
    at /Users/cyber/dev/next-tracing-excludes/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/collect-build-traces.js:86:23
    at Array.every (<anonymous>)
```

It happens regardless of what kind of minimatch patterns I specify, even if there are no wildcards in the patterns.

### Current vs. Expected behavior

I expect build to complete without an error.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:32:11 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T6030
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.17
  pnpm: 8.8.0
Relevant Packages:
  next: 14.0.5-canary.41
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: standalone
```
```


### Which area(s) are affected? (Select all that apply)

Standalone mode (output: "standalone")

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

A few more notes here: https://github.com/vercel/next.js/issues/42641#issuecomment-1872592551

**Comment by 1Ghasthunter1** [comment] 2024-01-12 23:27
Same issue:


```
RangeError: Maximum call stack size exceeded
--
15:26:04.399 | at parse (/vercel/path1/node_modules/next/dist/compiled/micromatch/index.js:15:6313)
15:26:04.400 | at picomatch.makeRe (/vercel/path1/node_modules/next/dist/compiled/micromatch/index.js:15:21670)
15:26:04.400 | at picomatch (/vercel/path1/node_modules/next/dist/compiled/micromatch/index.js:15:19637)
15:26:04.400 | at /vercel/path1/node_modules/next/dist/compiled/micromatch/index.js:15:19294
15:26:04.400 | at Array.map (<anonymous>)
15:26:04.400 | at picomatch (/vercel/path1/node_modules/next/dist/compiled/micromatch/index.js:15:19286)
15:26:04.401 | at micromatch.isMatch (/vercel/path1/node_modules/next/dist/compiled/micromatch/index.js:15:1090)
15:26:04.401 | at /vercel/path1/node_modules/next/dist/build/collect-build-traces.js:245:48
15:26:04.401 | at shouldIgnore (/vercel/path1/node_modules/next/dist/build/collect-build-traces.js:75:9)
15:26:04.401 | at /vercel/path1/node_modules/next/dist/build/collect-build-traces.js:86:23
15:26:04.461 | Error: Command "npm run build" exited with 1
```

**Comment by austintoddj** [comment] 2024-01-13 13:47
Same issue for me.

```
RangeError: Maximum call stack size exceeded
--

> build
--
07:43:34.706 | > next build
07:43:34.706 |  
07:43:35.366 | ▲ Next.js 14.0.4
07:43:35.367 |  
07:43:35.367 | Creating an optimized production build ...
07:43:40.169 | ✓ Compiled successfully
07:43:40.169 | Linting and checking validity of types ...
07:43:42.447 | Collecting page data ...
07:43:43.936 | Generating static pages (0/17) ...
07:43:44.737 | Generating static pages (4/17)
07:43:45.233 | Generating static pages (8/17)
07:43:45.491 | Generating static pages (12/17)
07:43:46.135 | ✓ Generating static pages (17/17)
07:43:46.629 | Finalizing page optimization ...
07:43:46.630 | Collecting build traces ...
07:43:55.184 | RangeError: Maximum call stack size exceeded
07:43:55.184 | at RegExp.exec (<anonymous>)
07:43:55.184 | at create (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:18889)
07:43:55.184 | at create (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:18918)
07:43:55.184 | at create (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:18918)
07:43:55.184 | at parse.fastpaths (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:18997)
07:43:55.185 | at picomatch.makeRe (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:21635)
07:43:55.185 | at picomatch (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19637)
07:43:55.185 | at /vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19294
07:43:55.185 | at Array.map (<anonymous>)
07:43:55.185 | at picomatch (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19286)
07:43:55.227 | Error: Command "npm run build" exited with 1
```

**Comment by MonstraG** [comment] 2024-01-13 14:30
Recently updated dependencies of my small project, and suddenly build started failing, but only on vercel:

<details>
<summary>Details</summary>


```
[14:48:31.114] Running build in Washington, D.C., USA (East) – iad1
[14:48:31.292] Cloning github.com/MonstraG/my-page (Branch: master, Commit: db0d89f)
[14:48:31.301] Skipping build cache, deployment was triggered without cache.
[14:48:31.904] Cloning completed: 611.066ms
[14:48:32.190] Running "vercel build"
[14:48:33.288] Vercel CLI 33.1.0
[14:48:33.713] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8
[14:48:33.732] Installing dependencies...
[14:48:34.635] Lockfile is up to date, resolution step is skipped
[14:48:34.743] Progress: resolved 1, reused 0, downloaded 0, added 0
[14:48:34.946] Packages: +730
[14:48:34.946] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[14:48:35.743] Progress: resolved 730, reused 0, downloaded 43, added 27
[14:48:36.744] Progress: resolved 730, reused 0, downloaded 73, added 62
[14:48:38.617] Progress: resolved 730, reused 0, downloaded 74, added 62
[14:48:39.617] Progress: resolved 730, reused 0, downloaded 81, added 71
[14:48:40.618] Progress: resolved 730, reused 0, downloaded 89, added 73
[14:48:43.764] Progress: resolved 730, reused 0, downloaded 89, added 74
[14:48:44.765] Progress: resolved 730, reused 0, downloaded 97, added 81
[14:48:45.768] Progress: resolved 730, reused 0, downloaded 142, added 130
[14:48:46.768] Progress: resolved 730, reused 0, downloaded 160, added 146
[14:48:47.769] Progress: resolved 730, reused 0, downloaded 165, added 153
[14:48:48.771] Progress: resolved 730, reused 0, downloaded 217, added 204
[14:48:49.771] Progress: resolved 730, reused 0, downloaded 283, added 268
[14:48:50.772] Progress: resolved 730, reused 0, downloaded 495, added 490
[14:48:51.771] Progress: resolved 730, reused 0, downloaded 559, added 550
[14:48:52.777] Progress: resolved 730, reused 0, downloaded 649, added 634
[14:48:53.697] Progress: resolved 730, reused 0, downloaded 730, added 730, done
[14:48:53.986] .../sharp@0.33.2/node_modules/sharp install$ node install/check
[14:48:55.961] .../sharp@0.33.2/node_modules/sharp install: Done
[14:48:56.120] 
[14:48:56.121] dependencies:
[14:48:56.121] + @emotion/cache 11.11.0
[14:48:56.121] + @emotion/react 11.11.3
[14:48:56.121] + @emotion/styled 11.11.0
[14:48:56.121] + @mui/base 5.0.0-beta.26
[14:48:56.121] + @mui/icons-material 5.15.4
[14:48:56.121] + @mui/joy 5.0.0-beta.17
[14:48:56.122] + @mui/material <- @mui/joy 5.0.0-beta.17
[14:48:56.122] + @vercel/kv 1.0.1
[14:48:56.122] + next 14.0.4
[14:48:56.122] + react 18.2.0
[14:48:56.122] + react-dom 18.2.0
[14:48:56.122] + remark 15.0.1
[14:48:56.122] + remark-html 16.0.1
[14:48:56.123] + sharp 0.33.2
[14:48:56.123] + zustand 4.4.7
[14:48:56.123] 
[14:48:56.123] devDependencies:
[14:48:56.123] + @next/bundle-analyzer 14.0.4
[14:48:56.126] + @testing-library/jest-dom 6.2.0
[14:48:56.126] + @testing-library/react 14.1.2
[14:48:56.126] + @types/jest 29.5.11
[14:48:56.126] + @types/node 20.11.0
[14:48:56.126] + @types/react 18.2.47
[14:48:56.126] + @types/react-dom 18.2.18
[14:48:56.126] + @typescript-eslint/eslint-plugin 6.18.1
[14:48:56.126] + @typescript-eslint/parser 6.18.1
[14:48:56.126] + eslint 8.56.0
[14:48:56.127] + eslint-config-next 14.0.4
[14:48:56.127] + eslint-config-prettier 9.1.0
[14:48:56.127] + eslint-plugin-import 2.29.1
[14:48:56.127] + eslint-plugin-jest 27.6.3
[14:48:56.127] + eslint-plugin-testing-library 6.2.0
[14:48:56.127] + jest 29.7.0
[14:48:56.127] + jest-environment-jsdom 29.7.0
[14:48:56.127] + prettier 3.2.1
[14:48:56.127] + sass 1.69.7
[14:48:56.128] + typescript 5.3.3
[14:48:56.139] 
[14:48:56.145] Done in 22.2s
[14:48:56.178] Detected Next.js version: 14.0.4
[14:48:56.225] Running "pnpm run build"
[14:48:56.711] 
[14:48:56.711] > cv@0.19.0 build /vercel/path0
[14:48:56.711] > next build
[14:48:56.712] 
[14:48:57.326] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[14:48:57.327] This information is used to shape Next.js' roadmap and prioritize features.
[14:48:57.329] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[14:48:57.329] https://nextjs.org/telemetry
[14:48:57.329] 
[14:48:57.434]    ▲ Next.js 14.0.4
[14:48:57.435] 
[14:48:57.435]    Creating an optimized production build ...
[14:49:19.942]  ✓ Compiled successfully
[14:49:19.944]    Linting and checking validity of types ...
[14:49:48.248]    Collecting page data ...
[14:49:50.147]    Generating static pages (0/13) ...
[14:49:51.496] 
   Generating static pages (3/13) 
[14:49:51.759] 
   Generating static pages (6/13) 
[14:49:52.351] 
   Generating static pages (9/13) 
[14:49:53.134] 
 ✓ Generating static pages (13/13) 
[14:49:53.570]    Finalizing page optimization ...
[14:49:53.570]    Collecting build traces ...
[14:50:01.861] RangeError: Maximum call stack size exceeded
[14:50:01.862]     at parse (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0_sass@1.69.7/node_modules/next/dist/compiled/micromatch/index.js:15:6313)
[14:50:01.862]     at picomatch.makeRe (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0_sass@1.69.7/node_modules/next/dist/compiled/micromatch/index.js:15:21670)
[14:50:01.862]     at picomatch (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0_sass@1.69.7/node_modules/next/dist/compiled/micromatch/index.js:15:19637)
[14:50:01.862]     at /vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0_sass@1.69.7/node_modules/next/dist/compiled/micromatch/index.js:15:19294
[14:50:01.862]     at Array.map (<anonymous>)
[14:50:01.862]     at picomatch (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0_sass@1.69.7/node_modules/next/dist/compiled/micromatch/index.js:15:19286)
[14:50:01.863]     at micromatch.isMatch (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0_sass@1.69.7/node_modules/next/dist/compiled/micromatch/index.js:15:1090)
[14:50:01.863]     at /vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0_sass@1.69.7/node_modules/next/dist/build/collect-build-traces.js:245:48
[14:50:01.863]     at shouldIgnore (/vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0_sass@1.69.7/node_modules/next/dist/build/collect-build-traces.js:75:9)
[14:50:01.863]     at /vercel/path0/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0_sass@1.69.7/node_modules/next/dist/build/collect-build-traces.js:86:23
[14:50:01.909]  ELIFECYCLE  Command failed with exit code 1.
[14:50:01.927] Error: Command "pnpm run build" exited with 1
```

</details>

Locally: everything is fine. I'm using sass, but not using output standalone nor outputFileTracingExcludes.

**Comment by MonstraG** [comment] 2024-01-13 15:23
Found it, vercel build fails if I update  "sharp": "0.33.1" ->  "sharp": "0.33.2",

**Comment by levipadre** [comment] 2024-01-13 17:04
Same issue here. Can't deploy on Vercel. I need this urgently

Used plugins:
```
"dependencies": {
        "@emotion/react": "^11.11.3",
        "@next/bundle-analyzer": "^14.0.4",
        "@next/third-parties": "^14.0.4",
        "@types/node": "^20.11.0",
        "@types/react": "^18.2.47",
        "@types/react-dom": "^18.2.18",
        "bootstrap": "^5.3.2",
        "eslint-config-next": "^14.0.4",
        "html-react-parser": "^5.1.0",
        "next": "^14.0.4",
        "react": "^18.2.0",
        "react-awesome-reveal": "^4.2.7",
        "react-bootstrap": "^2.9.2",
        "react-dom": "^18.2.0",
        "react-hot-toast": "^2.4.1",
        "react-player": "^2.14.1",
        "react-scroll-parallax": "^3.4.5",
        "resend": "^2.1.0",
        "sharp": "^0.33.2",
        "swiper": "11.0.5",
        "typescript": "^5.3.3"
    },
    "devDependencies": {
        "@svgr/webpack": "^8.1.0",
        "sass": "^1.69.7"
    }
```

Next info:
```
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64
    Binaries:
      Node: 18.17.0
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.5.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

**Comment by a-rustacean** [comment] 2024-01-13 17:08
> Same issue here. Can't deploy on Vercel. I need this urgently
> 
> Used plugins:
> 
> ```
> "dependencies": {
>         "@emotion/react": "^11.11.3",
>         "@next/bundle-analyzer": "^14.0.4",
>         "@next/third-parties": "^14.0.4",
>         "@types/node": "^20.11.0",
>         "@types/react": "^18.2.47",
>         "@types/react-dom": "^18.2.18",
>         "bootstrap": "^5.3.2",
>         "eslint-config-next": "^14.0.4",
>         "html-react-parser": "^5.1.0",
>         "next": "^14.0.4",
>         "react": "^18.2.0",
>         "react-awesome-reveal": "^4.2.7",
>         "react-bootstrap": "^2.9.2",
>         "react-dom": "^18.2.0",
>         "react-hot-toast": "^2.4.1",
>         "react-player": "^2.14.1",
>         "react-scroll-parallax": "^3.4.5",
>         "resend": "^2.1.0",
>         "sharp": "^0.33.2",
>         "swiper": "11.0.5",
>         "typescript": "^5.3.3"
>     },
>     "devDependencies": {
>         "@svgr/webpack": "^8.1.0",
>         "sass": "^1.69.7"
>     }
> ```
> 
> Next info:
> 
> ```
> Operating System:
>       Platform: darwin
>       Arch: x64
>       Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64
>     Binaries:
>       Node: 18.17.0
>       npm: 9.6.7
>       Yarn: 1.22.19
>       pnpm: N/A
>     Relevant Packages:
>       next: 13.5.1
>       eslint-config-next: N/A
>       react: 18.2.0
>       react-dom: 18.2.0
>       typescript: 5.2.2
>     Next.js Config:
>       output: N/A
> ```
> 
> Error message: <img alt="Screenshot 2024-01-13 at 17 06 18" width="931" src="https://private-user-images.githubusercontent.com/357974/296505206-7182af7c-49ac-4ff7-ab1f-7385c8c3f960.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNjU5MTMsIm5iZiI6MTcwNTE2NTYxMywicGF0aCI6Ii8zNTc5NzQvMjk2NTA1MjA2LTcxODJhZjdjLTQ5YWMtNGZmNy1hYjFmLTczODVjOGMzZjk2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExM1QxNzA2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjA0M2I2YjczNDdlY2U3NGQxZjEwMDRiNWJmNjA2NmNlNjVhNTI1ZmNjYzZlYWQ2NWVmZDNmMDk2NzY0YjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rcbJ8IxgdH7EnHJ6pFff4twx-MAUst14Et4CG-2W4a8">

getting the same error :cry:

**Comment by a-rustacean** [comment] 2024-01-13 17:13
using sharp v0.33.1 resolved the issue

**Comment by 1Ghasthunter1** [comment] 2024-01-13 17:43
> using sharp v0.33.1 resolved the issue

Agreed, going to sharp 0.33.1 solved for me as well.

**Comment by levipadre** [comment] 2024-01-13 17:45
Thanks, @a-rustacean, for figuring it out. It did help!

**Comment by SharadKumar** [comment] 2024-01-13 22:40
Yess, that fixed it. To pin to `v0.33.1`

**Comment by InoXiT-DE** [comment] 2024-01-14 18:12
Thanks, this fixed it for me too! Downgrading from v0.33.2 -> v0.33.1

**Comment by 1Ghasthunter1** [comment] 2024-01-14 23:12
For any next devs who manage the thread: this is a duplicate of [this issue](https://github.com/vercel/next.js/issues/59075)

**Comment by MonstraG** [comment] 2024-01-15 06:36
> For any next devs who manage the thread: this is a duplicate of [this issue](https://github.com/vercel/next.js/issues/59075)

No, it is not. It got taken over by recent posters about sharp, but issue was created 2 months ago, far before 0.33.2 release, and original poster doesn't even have sharp in dependencies.

**Comment by 1Ghasthunter1** [comment] 2024-01-15 06:37
> > For any next devs who manage the thread: this is a duplicate of [this issue](https://github.com/vercel/next.js/issues/59075)
> 
> No, it is not. It got taken over by recent posters about sharp, but issue was created 2 months ago, far before 0.33.2 release, and original poster doesn't even have sharp in dependencies.

You're right, deleting older post.

**Comment by AtomicCow87** [comment] 2024-01-15 23:48
Downgrading from v0.33.2 -> v0.33.1 did not work for me.

```
[18:44:18.140] 
[18:44:18.302]    ▲ Next.js 14.0.4
[18:44:18.302] 
[18:44:18.302]    Creating an optimized production build ...
[18:44:30.903]  ✓ Compiled successfully
[18:44:30.905]    Linting and checking validity of types ...
[18:44:35.451]    Collecting page data ...
[18:44:36.898]    Generating static pages (0/7) ...
[18:44:37.092] 
   Generating static pages (1/7) 
[18:44:37.138] 
   Generating static pages (3/7) 
[18:44:37.780] 
   Generating static pages (5/7) 
[18:44:37.955] 
 ✓ Generating static pages (7/7) 
[18:44:38.180]    Finalizing page optimization ...
[18:44:38.180]    Collecting build traces ...
[18:44:45.179] RangeError: Maximum call stack size exceeded
[18:44:45.180]     at parse (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:6313)
[18:44:45.180]     at picomatch.makeRe (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:21670)
[18:44:45.180]     at picomatch (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19637)
[18:44:45.181]     at /vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19294
[18:44:45.181]     at Array.map (<anonymous>)
[18:44:45.181]     at picomatch (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19286)
[18:44:45.181]     at micromatch.isMatch (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:1090)
[18:44:45.181]     at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:245:48
[18:44:45.181]     at shouldIgnore (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:75:9)
[18:44:45.182]     at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:23
[18:44:45.224] Error: Command "npm run build" exited with 1
[18:44:45.492] 
```

**Comment by a-rustacean** [comment] 2024-01-16 03:51
> Downgrading from v0.33.2 -> v0.33.1 did not work for me.
> 
> ```
> [18:44:18.140] 
> [18:44:18.302]    ▲ Next.js 14.0.4
> [18:44:18.302] 
> [18:44:18.302]    Creating an optimized production build ...
> [18:44:30.903]  ✓ Compiled successfully
> [18:44:30.905]    Linting and checking validity of types ...
> [18:44:35.451]    Collecting page data ...
> [18:44:36.898]    Generating static pages (0/7) ...
> [18:44:37.092] 
>    Generating static pages (1/7) 
> [18:44:37.138] 
>    Generating static pages (3/7) 
> [18:44:37.780] 
>    Generating static pages (5/7) 
> [18:44:37.955] 
>  ✓ Generating static pages (7/7) 
> [18:44:38.180]    Finalizing page optimization ...
> [18:44:38.180]    Collecting build traces ...
> [18:44:45.179] RangeError: Maximum call stack size exceeded
> [18:44:45.180]     at parse (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:6313)
> [18:44:45.180]     at picomatch.makeRe (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:21670)
> [18:44:45.180]     at picomatch (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19637)
> [18:44:45.181]     at /vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19294
> [18:44:45.181]     at Array.map (<anonymous>)
> [18:44:45.181]     at picomatch (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19286)
> [18:44:45.181]     at micromatch.isMatch (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:1090)
> [18:44:45.181]     at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:245:48
> [18:44:45.181]     at shouldIgnore (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:75:9)
> [18:44:45.182]     at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:23
> [18:44:45.224] Error: Command "npm run build" exited with 1
> [18:44:45.492] 
> ```
> 
> EDIT: I had `"sharp": "^0.33.1"` but changing it to `"sharp": "0.33.1"` worked.

yep, you have to set the exact version

**Comment by piyushchauhan2011** [comment] 2024-01-16 11:42
Setting `"sharp": "0.33.1"` to exact version works with me also 💯

**Comment by lovell** [comment] 2024-01-16 13:47
This problem appears to be caused by uncontrolled recursive behaviour within Next.js.

https://github.com/vercel/next.js/blob/dc394483b807e5e111c175ad9afd1f09220da7ce/packages/next/src/build/collect-build-traces.ts#L59

Pinning dependencies is merely perendinating the problem.

**Comment by samuellembke** [comment] 2024-01-16 16:05
> Downgrading from v0.33.2 -> v0.33.1 did not work for me.
> EDIT: I had `"sharp": "^0.33.1"` but changing it to `"sharp": "0.33.1"` worked.

DUDE THIS WAS THE FIX

**Comment by BitYoungjae** [comment] 2024-01-18 02:39
I understand that downgrading to sharp version 0.33.1 resolves the issue. 
However, looking at the commit history for 0.33.2, it only shows documentation changes. Why would this cause such a problem?

**Comment by VitaliyPotapov** [comment] 2024-01-18 10:17
> I understand that downgrading to sharp version 0.33.1 resolves the issue. However, looking at the commit history for 0.33.2, it only shows documentation changes. Why would this cause such a problem?

It's not only documentation change per [diff 0.33.1 .. 0.33.2](https://github.com/lovell/sharp/compare/v0.33.1...v0.33.2)

**Comment by VitaliyPotapov** [comment] 2024-01-18 16:29
> EDIT: I got rid of `sharp` and it solved the problem. Command to run:
> 
> > # npm uninstall sharp

@ADTC doesn't it needed for local development?

**Comment by ADTC** [comment] 2024-01-19 06:02
@VitaliyPotapov no, why? 🤷

**Comment by a-rustacean** [comment] 2024-01-19 14:42
@VitaliyPotapov 

When attempting to locally build (`npm run build`) without the `sharp` package installed, you may encounter the following warning:

```
⚠ For optimal Image Optimization in production with Next.js, we strongly recommend installing the optional 'sharp' package. Simply run 'npm i sharp', and Next.js will automatically utilize it during the build process.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
```

It's worth noting that `sharp` is specifically utilized during production builds (`npm run build`), and it is not necessary for the development server (`npm run dev`). Additionally, if you plan to deploy your application using Vercel, there's no need to worry as Vercel automatically handles the installation of `sharp` for you.

**Comment by VitaliyPotapov** [comment] 2024-01-22 09:31
@a-rustacean thanks for the info!
We use `npm run build` locally for different reasons, for example when testing error pages. I decided to pin `"sharp": "0.33.1"` as suggested above.

**Comment by IAmYoungbossy** [comment] 2024-01-24 18:43
I don't know how it worked, but for me running the cammand `npm i`, the issue was resolved. The only file changes was in my package-lock.json file as seen in the screenshot below after running `npm i`. After that tried redeploying again and it worked.

![image](https://github.com/vercel/next.js/assets/99342564/f5d1a06d-aeda-4d90-8253-58f4ee359722)

**Comment by piyushchauhan2011** [comment] 2024-01-26 02:55
> In my case, next@14.1.0 fixed it with sharp@0.33.2. #60740

Confirming next 14.1.0 works with sharp 0.33.2 now

**Comment by a-rustacean** [comment] 2024-01-26 06:49
So, the issue is resolved?

**Comment by revmischa** [comment] 2024-01-28 21:10
14.1.0 works for me!

**Closed** 2024-01-30 04:30 UTC
Labels: template: bug, area: standalone mode

**Comment by trishan9** [comment] 2024-02-04 14:56
> using sharp v0.33.1 resolved the issue

This worked for me!

**Comment by vishalkatsa** [comment] 2024-02-07 00:32
issue is here "sharp": "^0.33.1" , replace this "sharp": "^0.33.1" with this "sharp": "0.33.1"
`"sharp": "^0.33.1", /// remove this 
    "sharp": "0.33.1", // add this `

**Comment by Rajvirnahar** [comment] 2024-02-16 19:45
i tried everyrthing you guys wrote above but when i do "sharp": "0.33.1", my whole website gets deleted and gives Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

> using sharp v0.33.1 resolved the issue

 i tried everyrthing you guys wrote above but when i do "sharp": "0.33.1", my whole website gets deleted and gives Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by Rajvirnahar** [comment] 2024-02-16 19:46
> Setting `"sharp": "0.33.1"` to exact version works with me also 💯

i tried that but then my whole website gets deleted and gives error Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by Rajvirnahar** [comment] 2024-02-16 19:52
> > Downgrading from v0.33.2 -> v0.33.1 did not work for me.
> > EDIT: I had `"sharp": "^0.33.1"` but changing it to `"sharp": "0.33.1"` worked.
> 
> DUDE THIS WAS THE FIX

i try this but it still doesnt work. shows a whole big error on my website saying Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by Rajvirnahar** [comment] 2024-02-16 19:53
> issue is here "sharp": "^0.33.1" , replace this "sharp": "^0.33.1" with this "sharp": "0.33.1" `"sharp": "^0.33.1", /// remove this "sharp": "0.33.1", // add this `
i try this but it still doesnt work. shows a whole big error on my website saying Minified React error https://github.com/vercel/next.js/issues/130; visit [https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]=](https://reactjs.org/docs/error-decoder.html?invariant=130&args%5B%5D=object&args%5B%5D=) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by owncrafts** [comment] 2024-02-26 10:19
> Found it, vercel build fails if I update "sharp": "0.33.1" -> "sharp": "0.33.2",

Thank you so much, i was stuck due to this thing, it's solved

**Comment by carlosromanxyz** [comment] 2024-02-27 15:42
I solved it, but using another way, thanks @kondei:

**Please update NextJS from 14.0.x into 14.1.x**

Run inside your project application `npx npm-check-updates -u` you'll see your `package.json` with new package versions, update using `npm install` (or `npm i`)

Then deploy on Vercel and excuse my english :)
