### ISSUE TITLE
Nextjs route matching doesn't match in vercel but does locally

### ISSUE THREAD

**Issue by Artrix9095** [vercel/next.js#39411] opened 2022-08-09 06:43 UTC
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

   Operating System:
      Platform: linux
      Arch: x64
      Version: #653-Microsoft Wed Apr 27 16:06:00 PST 2022
    Binaries:
      Node: 17.3.0
      npm: 8.3.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.2.2
      eslint-config-next: 12.2.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 104.0.5112.81

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

When having a simple file system route like such

/pages    
- /api
-  /user
    -  [id].ts
    -  login.ts

I've noticed that when running the following configuration locally it works fine. and even when running `yarn build && yarn start` it still works fine. But when running on vercel. I always get the following error 
![image](https://user-images.githubusercontent.com/39530102/183579923-472f3552-9582-41c1-aa3b-d4b7b3eb38ea.png)

You will see that the path is being matched to the [id] field and not the login field. But when run locally 
![image](https://user-images.githubusercontent.com/39530102/183580181-b536bd95-2876-4d4f-9766-4abe455481c3.png)

which is extremely odd. A piece of useful information may be that [id].ts is an edge function while login.ts is a serverless function.

### Expected Behavior

/api/user/login should match to login.ts and not [id].ts in vercel.

### Link to reproduction

None

### To Reproduce

```
npx create-next-app my-app
```

```js
// /api/user/login.ts

export default async function handler(req, res) {

res.json({hello: 'world'});

}
```
```js
// /api/user/[id].ts

export const config = {

runtime: 'experimental-edge',

};
export default async function handler(req) {

return new Response('Hello World');

}
```

```
npx vercel
```

**Comment by Artrix9095** [comment] 2022-08-09 06:48
The 500 error is from the code i have in the [id].ts not taking login as a valid id. in the replication example it will still return 200 but with 'hello world' as the response instead of
 ```js
{ hello: 'world' }
```

**Comment by Winwardo** [comment] 2022-08-09 08:44
Hi, I was seeing a similar issue #39266 which appears to be fixed in `12.2.5-canary.0`, and you've said you're testing on `12.2.2`. Does the issue still happen on the latest canary?

**Comment by Artrix9095** [comment] 2022-08-09 17:35
I just tested `12.2.5-canary.0`. Still no good

**Comment by Artrix9095** [comment] 2022-08-09 17:38
My main issue is why it this happening *specifically* on vercel but works fine locally

**Comment by balazsorban44** [comment] 2022-08-10 12:16
I could actually reproduce this locally, so investigating. :+1: Looks like the edge dynamic routes have different priority than non edge routes

**Closed** 2022-08-16 18:05 UTC
Labels: kind: bug, type: needs investigation, area: Routing
