### ISSUE TITLE
"NODE_OPTIONS='--inspect' next dev" won't work correctly, debugging server-side not possiable

### ISSUE THREAD

**Issue by Dkogan90** [vercel/next.js#47561] opened 2023-03-27 11:49 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:49:43 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 17.9.1
      npm: 8.11.0
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.19
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/Dkogan90/next-bug

### To Reproduce

Starting next: `yarn run dev`
try to debugging `pages/api/hello.ts` with chrome node inspector

### Describe the Bug

Inspector is already running.
Unable to debug server-side code.
```
$ NODE_OPTIONS='--inspect' next dev
Debugger listening on ws://127.0.0.1:9229/9a701303-c48a-4785-9ee0-8bea5a0e4cff
For help, see: https://nodejs.org/en/docs/inspector
warn  - the --inspect option was detected, the Next.js server should be inspected at port 9230.
Debugger listening on ws://127.0.0.1:9230/33c493f4-afba-4ac8-b7af-7c18e6e56b11
For help, see: https://nodejs.org/en/docs/inspector
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Starting inspector on 127.0.0.1:9229 failed: address already in use
```

### Expected Behavior

Able to debug server side code with the node.js inspector via chrome

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

not relevant

**Comment by icyJoseph** [comment] 2023-03-29 11:56
Hi @Dkogan90 

I've managed to get this to work, but it was really weird.

To me it stood out:

```console
warn  - the --inspect option was detected, the Next.js server should be inspected at port 9230.
```

In spite of the line that points to 9229:

```console
Debugger listening on ws://127.0.0.1:9229/9a701303-c48a-4785-9ee0-8bea5a0e4cff
```

So in the `chrome://inspect` UI I clicked on `Configure`, and added localhost:9230 to the debug list:

![Screenshot 2023-03-29 at 13 46 45](https://user-images.githubusercontent.com/21013447/228525837-05f7a9fc-31a3-495d-ae47-94e972b30734.png)

And then I was able to debug:

![Screenshot 2023-03-29 at 13 51 38](https://user-images.githubusercontent.com/21013447/228526958-a54b8e66-d035-4d8f-a2bc-3bcb75cf361c.png)

It also works with `api/hello.ts`:

![Screenshot 2023-03-29 at 13 53 23](https://user-images.githubusercontent.com/21013447/228527387-07dc10f4-b03a-435c-a038-ade7780560c4.png)

And it also works with middleware:

![Screenshot 2023-03-29 at 13 54 26](https://user-images.githubusercontent.com/21013447/228527674-7ce79408-5755-4925-b14e-66f3fa9eb268.png)

To me the weird thing is that it'd bump from 9229 to 9230, and I wonder if it is related to this from the [docs](https://nextjs.org/docs/advanced-features/debugging#server-side-code):

> Be aware that running NODE_OPTIONS='--inspect' npm run dev or NODE_OPTIONS='--inspect' yarn dev won't work. This would try to start multiple debuggers on the same port: one for the npm/yarn process and one for Next.js. You would then get an error like Starting inspector on 127.0.0.1:9229 failed: address already in use in your console.

Even if we do as they instruct, that seems to happen, could it be that there's some binary under the hood, that triggers this issue anyway?

**Comment by edorgeville** [comment] 2023-03-29 20:08
Duplicate of #47083

**Comment by Cow258** [comment] 2023-04-05 08:54
13.2.4 is working well, but it not working on the latest Next.js canary release.

Expected(v13.2.4): both 9229 and 9230 should be used
![image](https://user-images.githubusercontent.com/14261588/230031602-827be428-bfed-4659-918b-107994974ad5.png)
![image](https://user-images.githubusercontent.com/14261588/230031728-82a1529d-19d3-4772-a734-0b78a2f6c11f.png)


Currently(v13.2.5): only 9229 used, 9230 is missing
![image](https://user-images.githubusercontent.com/14261588/230032034-22a75b15-5e80-407b-b723-5b7813bfb579.png)
![image](https://user-images.githubusercontent.com/14261588/230032112-5e6a6aaf-2a20-4dd1-8d3f-3c73bd5d2d66.png)

**Comment by wowczarczyk** [comment] 2023-05-16 08:38
I was successful debugging in VS Code using the following launch configuration:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/node_modules/next/dist/bin/next",
            "runtimeArgs": [
                "--inspect"
            ]
        }
    ]
}
```

**Comment by Cow258** [comment] 2023-05-16 09:02
> I was successful debugging in VS Code using the following launch configuration:
> 
> ```
> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "type": "node",
>             "request": "launch",
>             "name": "Launch Program",
>             "skipFiles": [
>                 "<node_internals>/**"
>             ],
>             "program": "${workspaceFolder}/node_modules/next/dist/bin/next",
>             "runtimeArgs": [
>                 "--inspect"
>             ]
>         }
>     ]
> }
> ```

Which version of Next.js are you using?
Will it break when you added breakpoint into API or Page routes?

**Comment by wowczarczyk** [comment] 2023-05-16 09:17
13.4.2

I am only using the new app dir and breakpoints work fine in various places
of my server-side code, e.g. Route handlers.

wt., 16 maj 2023, 11:02 użytkownik Cowboy Ho ***@***.***>
napisał:

**Closed** 2023-05-23 18:03 UTC
Labels: template: bug, area: Edge
