### ISSUE TITLE
next-eslint-plugin: aborts when facing a <Link><a/></Link>

### ISSUE THREAD

**Issue by polesapart** [vercel/next.js#26206] opened 2021-06-16 17:48 UTC
### What version of Next.js are you using?

11.0

### What version of Node.js are you using?

14.16.1

### What browser are you using?

N/A

### What operating system are you using?

Linux

### How are you deploying your application?

N/a

### Describe the Bug

I have this on a tsx file:

```
const CustomLink = (props) => {
  const href = props.href
  const isInternalLink = href && (href.startsWith('/') || href.startsWith('#'))

  if (isInternalLink) {
    return (
      <Link href={href} passHref>
        <a {...props}/>
      </Link>
    )
  }

  return <a target="_blank" rel="noopener noreferrer" {...props} />
}
```

enabling eslint as document in next 11 fails with:

`$ pnpx next lint
Cannot read property 'name' of null
Occurred while linting '...'/mdx-settings.tsx:13`

### Expected Behavior

next lint should work. In fact, changing the <a> tag to:
`<a {...props}></a>`

works.

The offending code is in link-passhref.js:49:
`const hasAnchorChild = children.some(
          (attr) =>
            attr.type === 'JSXElement' &&
            attr.openingElement.name.name === 'a' &&
            attr.closingElement.name.name === 'a'
        )`

### To Reproduce

Put the above code in a new tsx file and follow next lint install instructions.

**Comment by housseindjirdeh** [comment] 2021-06-18 13:21
Fixed in #26280

**Closed by housseindjirdeh** 2021-06-18 13:21 UTC
Labels: template: bug

**Comment by NickCrews** [comment] 2021-07-03 07:51
Thanks for the great description of how to sidestep the bug @polesapart, and thanks @housseindjirdeh for the fix!

**Comment by balazsorban44** [comment] 2022-01-28 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
