### ISSUE TITLE
Link component broken on error and not-found pages

### ISSUE THREAD

**Issue by cipriancaba** [vercel/next.js#48073] opened 2023-04-07 11:58 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.13.1
    Relevant packages:
      next: 13.3.0
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-fzljky?file=app%2Fnot-found.tsx

### To Reproduce

Go to any not-found page. Happens also on regular error pages
Click the link to go to homepage

### Describe the Bug

Navigation doesn't work

### Expected Behavior

I go to the homepage

**Comment by jinojacob15** [comment] 2023-04-07 18:43
Same issue for me as well , Link component in global not-found.js is not working . Tried with router.push() still didnt work

**Comment by grzegorzpokorski** [comment] 2023-04-09 14:12
I also want to confirm that something is broken with links on `not-found.tsx` page - when I click link on not-found.tsx page eg. `<Link href="/contact">contact</Link>`, in the search bar url changes to `{mydomain}/contact` but the content of the page stays the same as the one that was rendered on the `not-found.tsx` page.

In addition I also want to point that when `not-found.tsx` page is rendered on development mode it constantly rerenders on every ~2 seconds - I am not sure it is expected behaviour.

**Comment by TheEdoRan** [comment] 2023-04-10 13:02
Related to #47862

**Comment by digitaltopo** [comment] 2023-04-14 20:51
Seeing exactly the same thing as described here: https://github.com/vercel/next.js/issues/48073#issuecomment-1501138638

Links in other parts of the layout (header etc) also only change the url but nothing re-renders and we're stuck on the not-found page.

**Comment by timneutkens** [comment] 2023-05-09 18:53
Duplicate of #47862

**Closed by timneutkens** 2023-05-09 18:53 UTC
Labels: template: bug, area: app

**Comment by shubh140601** [comment] 2023-05-25 05:44
> Duplicate of #47862
i m gettting re-renders on not-found.tsx page
