### ISSUE TITLE
[NEXT-560] Dynamic import exception cannot be caught

### ISSUE THREAD

**Issue by fmotlagh03** [vercel/next.js#45934] opened 2023-02-15 08:33 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023
    Binaries:
      Node: 18.14.0
      npm: 9.4.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.1.7-canary.14
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://github.com/fmotlagh03/NextDynamicImportBug

### To Reproduce

- Create a new Next app using `npx create-next-app --use-npm`
- Inside the `page.js`
  - Make the page component `async`
  - Use `await import()` inside a `try/catch`
  - You still see the error

### Describe the Bug

I want to dynamically import something. That file (component) might be there, or it might not be there. That's the main reason that I'm using dynamic `import()` function.

However, I need to suppress the error so that if that component/file does not exist, I provide a fallback.

But Next.js somehow does not let the `catch` block do its job.

### Expected Behavior

I expect the code inside `try/catch` to be suppressed if swallowed intentionally.

<sub>[NEXT-560](https://linear.app/vercel/issue/NEXT-560/dynamic-import-exception-is-not-swallowed-when-put-inside-trycatch)</sub>

**Comment by vjcspy** [comment] 2023-02-15 09:01
I am also getting error with dynamic import when using with apollo ssr. It is not able to load components which using dynamic import.
```typescript
            const { getDataFromTree } = await import('@apollo/react-ssr');
            logger.debug('>>> Apollo getDataFromTree');
            await getDataFromTree(
              <ctx.AppTree
                pageProps={{
                  ...pageProps,
                  apollo: { client },
                }}
              />
            );
```

**Comment by stmtk1** [comment] 2023-02-15 09:18
This error didn't reproduced in my environment. My environment is linux mint.

**Comment by fmotlagh03** [comment] 2023-02-19 10:32
@stmtk1  you should not have that component on your file system. The whole point is to try to import a component from a file that might exist, or might not exist. When it does exist, then of course there would be no problem whatsoever. But if the file does not exist, then you get the error.

**Comment by JanKaifer** [comment] 2023-02-23 10:37
We will take a look, but either way, I'd recommend not using this pattern.

Could you describe your use-case @fmotlagh03? Maybe there is a more idiomatic solution.

**Comment by vjcspy** [comment] 2023-02-23 10:54
Don't use this, use react error boundary instead

**Comment by fmotlagh03** [comment] 2023-03-06 13:00
@JnKaifer, we're developing a modern CMS. The point is, a system dynamically collects modules inside a docker container. This collection is made using some parameters.

Some modules might be overriden, and some might not.

Those modules that are not overriden, will use their own components to present data.

For example, let's say a website has a blog and a photo gallery. The customer does not want to have a custom blog, but wants a custom gallery.

Our base collects Blog and Galleries modules in a docker container, and there, our default blog page would import the overriden blog page using dynamic imports. If it fails, this means the blog is not overriden so the default page would be used.

**Comment by Himself65** [comment] 2023-04-11 15:14
![image](https://user-images.githubusercontent.com/14026360/231208376-be77ce1e-84de-4ed1-ac32-a10b2233d8be.png)
![image](https://user-images.githubusercontent.com/14026360/231208552-f78c3c4b-6297-482f-ba72-8bc979c169a8.png)


The minimum code here

```tsx
const Editor = dynamic(
  async () => {
    await new Promise(
      (resolve, reject) => setTimeout(reject(new Error('test')), 1000
      )
    );
  },
  {
    ssr: false,
  }
);
```

**Comment by Himself65** [comment] 2023-04-11 15:18
`pastDelay` will be the false in the last call, which will make the component blank because it's null

**Comment by ztanner** [comment] 2023-07-17 22:05
As this is a Webpack-specific issue, you'd need to use [`__non_webpack_require__`](https://webpack.js.org/api/module-variables/#__non_webpack_require__-webpack-specific) which will tell Webpack to skip the static analysis that it does on imported modules. Keep in mind this will transform it into a native `require` and can't be used on the client. Closing since Next.js isn't doing anything special to cause this behavior.

**Closed by ztanner** 2023-07-17 22:05 UTC
Labels: type: needs investigation, template: bug
