### ISSUE TITLE
Server action in 18.2.6 vs 18.2.8 is not longer able to import server action in client component

### ISSUE THREAD

**Issue by pawanrana1992** [vercel/next.js#69818] opened 2024-09-07 07:24 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32524
  Available CPU cores: 32
Binaries:
  Node: 20.14.0
  npm: N/A
  Yarn: N/A
  pnpm: 9.4.0
Relevant Packages:
  next: 14.2.8 // Latest available version is detected (14.2.8).
  eslint-config-next: 14.2.8
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

any fresh project

### Describe the Bug

My project is running in 14.2.6 nextjs version and actions api working fine when importing into client component. But when updating to 14.2.8 version, I am getting import error

Error: Cannot access AuthTemplate.then on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.
    at Object.get (*\node_modules\.pnpm\next@14.2.8_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:125427) {
  digest: '815452591'
}

I validate the Server action import with 18.2.8 version in client component using "use client" and in actions file "use server".
The same is working fine in 18.2.6 but not in 18.2.8 version.

and I have to revert my app to again 18.2.6 to work as expected.

### Expected Behavior

The actions functions should import in client component smoothly without any error, as per documentations.

### To Reproduce

1. create a project with nextjs 18.2.8 version
2. create file which will use server actions with "use server" as required
3. Add any 2 server actions and export as object = ( **export const abcAction and efgAction**) with full action api return logic and data handeling
4. Create a client side component "use client"
5. Import the action in the client component
6. run the app

You will see the error

Change the nextjs version to 18.2.6
1. create a project with nextjs 18.2.6 version
2. create file which will use server actions with "use server" as required
3. Add any 2 server actions and export as object = ( **export const abcAction and efgAction**) with full action api return logic and data handeling
4. Create a client side component "use client"
5. Import the action in the client component
6. run the app => It will work without any error

**Comment by fabicsp** [comment] 2024-09-07 11:28
For me had something similar issue:
I have upgrade from 14.2.7 => 14.2.8, and locally had no problems with the prod build, but at staging the server actions returned some html response, and was messed up everything.

**Comment by terrymun** [comment] 2024-09-08 08:36
You aren't the only one affected by this issue, and it does not seem to be localized to server actions.

We have an in-house component library that uses the same compound component compoisiton pattern like you see in Radix UI, e.g. `<Form.Control>`, and this seems to be causing issues with the latest version of 14.2.8 when building. Downgrading back to 14.2.7 causes the build step to work.

```text
▲ Next.js 14.2.8
- Experiments (use with caution):
  · outputFileTracingRoot

  Creating an optimized production build ...
✓ Compiled successfully
  Skipping linting
✓ Checking validity of types    
  Collecting page data  ...Error: Cannot access Form.Control on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.
  at Object.get (<PROJECT_ROOT>/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:125427)
  at <PROJECT_ROOT>/dist/apps/portal/.next/server/chunks/9394.js:1:7411
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Cannot access Form.Control on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.
  at Object.get (<PROJECT_ROOT>/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:125427)
  at <PROJECT_ROOT>/dist/apps/portal/.next/server/app/sitemap.xml/route.js:134:10521
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I've checked through our code and removed all references to `<Form.Control>` in our code in an attempt to debug the issue, but the issue still appears.

**Comment by huozhi** [comment] 2024-09-09 08:55
The error message looks like gonna be fixed in #69749 and we will release a patch to get it fixed. I still like to ask for a reproduction that can help us reproduce it. It could either be a missing case or bad usage that might require changes in the future.

**Comment by huozhi** [comment] 2024-09-09 19:25
We patched a fix in 14.2.9, if it's the same issue with #69720, please upgrade to the new version 🙏

**Closed** 2024-09-09 19:26 UTC
Labels: please add a complete reproduction

**Comment by terrymun** [comment] 2024-09-09 20:53
@huozhi Can confirm that upgrading to 14.2.9 fixes this.

The curious thing is, we are not using compound components anywhere in our server actions, so I wonder how #69720 fixed the bug... but I'm not complaining as the build works now :) thanks again!
