### ISSUE TITLE
fetch request is not re-executed after revalidatePath call

### ISSUE THREAD

**Issue by nilshartmann** [vercel/next.js#56472] opened 2023-10-05 09:51 UTC
### Link to the code that reproduces this issue

https://github.com/nilshartmann/nextjs-fetch-cache

### To Reproduce

With `revalidatePath`:
1. Start the application in dev mode (`npm run dev`)
2. open the root page in browser
3. Note the timestamp displayed on that page (and also console.log output). The timestamp is received from a `fetch` call.
4. Click on "Form" button
5. Click on "Action with revalidatePath" button (triggers server action, that calls `revalidatePath(/)`)
6. Click on "Home" link
7. Note displayed timestamp. It is the old one (also the console.log output shows two identical timestamps, indicating that the response comes from the cache)

With `revalidateTag` (working correctly):
1. Start the application in dev mode (`npm run dev`)
2. open the root page in browser
3. Note the timestamp displayed on that page (and also console.log output)
4. Click on "Form" button
5. Click on "Action with revalidateTag button (triggers server action with `revalidateTag("datetime")`)
6. Click on "Home" link
7. Note displayed timestamp. It is a new one (also the console.log output shows the result of two requests, both returning different data)

### Current vs. Expected behavior

**Current:**
- a route is "invalidated" using `revalidatePath` in a server action. 
- The client is navigating to the invalidated route
- The route is re-rendered on server side, but the `fetch` request is not run, but it's data is taken from the cache

**Expected:**
- The route is re-rendered on server side, and also the `fetch` request is executed to get fresh data

When using `revalidateTag` instead of `revalidatePath` the expected behaviour is working.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
> info
> next info


Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Binaries:
  Node: 18.15.0
  npm: 9.5.0
  Yarn: 1.22.19
  pnpm: 8.7.5
Relevant Packages:
  next: 13.5.5-canary.2
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A


next.config.js:
module.exports = {
  reactStrictMode: true,
  experimental: {
    serverActions: true,
  },
};
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Additional context

I also tried Next.js 13.5.4 with same behaviour.

It seems to happen if you're using `useRouter` and then `push` or (as in my example) when using the `Link` component.

In `dev` mode, if you open the app, open the form click on `Action with revalidatePath` and then open the root page (that should have been invalidated) it fetches again. In a prod build it is also **not** executing the `fetch` call.

**Comment by gaetansenn** [comment] 2023-10-18 14:33
I agree with you @nilshartmann only working with revalidateTag

**Comment by ChendayUP** [comment] 2023-10-26 02:57
> 2\. open the root page in browser

when open the root page in browser, show error info below

 ⨯ TypeError: fetch failed
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
digest: "1512168557"
 ⨯ TypeError: fetch failed
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
Cause: ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (D:\work_future\nextjs\reproduce-demo\nextjs-fetch-cache\node_modules\.pnpm\next@13.5.6_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\compiled\undici\index.js:1:93144)
    at D:\work_future\nextjs\reproduce-demo\nextjs-fetch-cache\node_modules\.pnpm\next@13.5.6_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\compiled\undici\index.js:1:92636
    at Immediate._onImmediate (D:\work_future\nextjs\reproduce-demo\nextjs-fetch-cache\node_modules\.pnpm\next@13.5.6_biqbaboplfbrettd7655fr4n2y\node_modules\next\dist\compiled\undici\index.js:1:93015)
    at process.processImmediate (node:internal/timers:471:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'UND_ERR_CONNECT_TIMEOUT'
}

**Comment by ChendayUP** [comment] 2023-10-26 02:57
> ### Link to the code that reproduces this issue
> https://github.com/nilshartmann/nextjs-fetch-cache
> 
> ### To Reproduce
> With `revalidatePath`:
> 
> 1. Start the application in dev mode (`npm run dev`)
> 2. open the root page in browser
> 3. Note the timestamp displayed on that page (and also console.log output). The timestamp is received from a `fetch` call.
> 4. Click on "Form" button
> 5. Click on "Action with revalidatePath" button (triggers server action, that calls `revalidatePath(/)`)
> 6. Click on "Home" link
> 7. Note displayed timestamp. It is the old one (also the console.log output shows two identical timestamps, indicating that the response comes from the cache)
> 
> With `revalidateTag` (working correctly):
> 
> 1. Start the application in dev mode (`npm run dev`)
> 2. open the root page in browser
> 3. Note the timestamp displayed on that page (and also console.log output)
> 4. Click on "Form" button
> 5. Click on "Action with revalidateTag button (triggers server action with `revalidateTag("datetime")`)
> 6. Click on "Home" link
> 7. Note displayed timestamp. It is a new one (also the console.log output shows the result of two requests, both returning different data)
> 
> ### Current vs. Expected behavior
> **Current:**
> 
> * a route is "invalidated" using `revalidatePath` in a server action.
> * The client is navigating to the invalidated route
> * The route is re-rendered on server side, but the `fetch` request is not run, but it's data is taken from the cache
> 
> **Expected:**
> 
> * The route is re-rendered on server side, and also the `fetch` request is executed to get fresh data
> 
> When using `revalidateTag` instead of `revalidatePath` the expected behaviour is working.
> 
> ### Verify canary release
> * [x]  I verified that the issue exists in the latest Next.js canary release
> 
> ### Provide environment information
> ```shell
> > info
> > next info
> 
> 
> Operating System:
>   Platform: darwin
>   Arch: arm64
>   Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
> Binaries:
>   Node: 18.15.0
>   npm: 9.5.0
>   Yarn: 1.22.19
>   pnpm: 8.7.5
> Relevant Packages:
>   next: 13.5.5-canary.2
>   eslint-config-next: N/A
>   react: 18.2.0
>   react-dom: 18.2.0
>   typescript: 5.1.3
> Next.js Config:
>   output: N/A
> 
> 
> next.config.js:
> module.exports = {
>   reactStrictMode: true,
>   experimental: {
>     serverActions: true,
>   },
> };
> ```
> 
> ### Which area(s) are affected? (Select all that apply)
> App Router, Routing (next/router, next/navigation, next/link)
> 
> ### Additional context
> I also tried Next.js 13.5.4 with same behaviour.
> 
> It seems to happen if you're using `useRouter` and then `push` or (as in my example) when using the `Link` component.
> 
> In `dev` mode, if you open the app, open the form click on `Action with revalidatePath` and then open the root page (that should have been invalidated) it fetches again. In a prod build it is also **not** executing the `fetch` call.

when open the root page in browser, show error info below

⨯ TypeError: fetch failed
at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
digest: "1512168557"
⨯ TypeError: fetch failed
at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
Cause: ConnectTimeoutError: Connect Timeout Error
at onConnectTimeout (D:\work_future\nextjs\reproduce-demo\nextjs-fetch-cache\node_modules.pnpm\[next@13.5.6_biqbaboplfbrettd7655fr4n2y](mailto:next@13.5.6_biqbaboplfbrettd7655fr4n2y)\node_modules\next\dist\compiled\undici\index.js:1:93144)
at D:\work_future\nextjs\reproduce-demo\nextjs-fetch-cache\node_modules.pnpm\[next@13.5.6_biqbaboplfbrettd7655fr4n2y](mailto:next@13.5.6_biqbaboplfbrettd7655fr4n2y)\node_modules\next\dist\compiled\undici\index.js:1:92636
at Immediate._onImmediate (D:\work_future\nextjs\reproduce-demo\nextjs-fetch-cache\node_modules.pnpm\[next@13.5.6_biqbaboplfbrettd7655fr4n2y](mailto:next@13.5.6_biqbaboplfbrettd7655fr4n2y)\node_modules\next\dist\compiled\undici\index.js:1:93015)
at process.processImmediate (node:internal/timers:471:21)
at process.callbackTrampoline (node:internal/async_hooks:130:17) {
code: 'UND_ERR_CONNECT_TIMEOUT'
}

**Comment by nilshartmann** [comment] 2023-10-27 07:43
I updated the example to Next.js 14 (canary with stable server actions) and it still does not revalidate.

Would be helpful to know if this is actually intended behaviour and my code is wrong?

**Comment by flextremedev** [comment] 2023-10-30 10:36
I would like to add my observation:

1. Open the root page in browser
2. Note the timestamp displayed on that page (and also console.log output). The timestamp is received from a fetch call.
3. Click on "Form" button
4. Click on "Action with revalidatePath" button (triggers server action, that calls revalidatePath(/))
5. Click on "Home" link
6. Note displayed timestamp. It is the old one (also the console.log output shows two identical timestamps, indicating that the response comes from the cache)
7. **Refresh browser or open home in a new tab**
8. **New timestamp is shown**

To me this means revalidateTag differs from revalidatePath by instantly refetching the data whereas with revalidatePath you have to request the page manually again.

I would work around this by calling redirect("/") after revalidatePath("/") if possible but it would be great to hear if this is intended. 
Also https://github.com/vercel/next.js/discussions/54075 doesn't answer this for me as revalidatePath and revalidateTag seem to be mentioned interchangeably with the only difference being what revalidation is based up on (tag or path). Maybe I missed it.

**Comment by nilshartmann** [comment] 2023-11-01 08:13
Just to see, if it's a problem with a local running nextjs server, I deployed the example to vercel, but results are the same. If any one wants to test: https://nextjs-fetch-cache.vercel.app/

I also aligned my example code more to the examples [in the docs](https://nextjs.org/docs/app/building-your-application/data-fetching/forms-and-mutations#revalidating-data). And cannot find any substantial difference:

**Docs**
```
'use server'
 
import { revalidatePath } from 'next/cache'
 
export default async function submit() {
  await submitForm()
  revalidatePath('/')
}
```

**My code:**


```
"use server";

import { revalidatePath } from "next/cache";

export default async function clearCacheWithRevalidatePath() {
  console.log("Trigger revalidatePath('/') and return");
  revalidatePath("/");
}

```

beside the fact that they call a `submitForm` method and in my code only `console.log` is called. I assume (maybe I'm wrong), that `submitForm` in the docs example is just a "placeholder" for a method in a real application that would  do the actual form data handling (validating, saving etc).

In the mean time I also tried:
- adding a `formData` argument to my server action, as shown [here](https://nextjs.org/docs/app/building-your-application/data-fetching/forms-and-mutations#form-validation)
- adding a `return` statement as shown [here](https://nextjs.org/docs/app/building-your-application/data-fetching/forms-and-mutations#form-validation)
- add another `fetch`call in my action (to a different endpint, but to have an `await` in my function as it is in the example)

...but nothing changes. 

I'm running out of ideas now. It might be helpful to have the complete example code from the docs to compare with my app and find differences, but I don't know if it is available. 

If anyone has an idea what could be wrong, please let me know 🙏

**Comment by leerob** [comment] 2024-01-15 15:49
Good news! I just tested your reproduction on the latest `canary` and could not reproduce. So this appears to be fixed after the referenced PR above was merged 😄

**Closed by leerob** 2024-01-15 15:49 UTC
Labels: template: bug, area: Routing
