### ISSUE TITLE
Link memory leak

### ISSUE THREAD

**Issue by mycolaos** [vercel/next.js#21028] opened 2021-01-12 16:09 UTC
**What version of Next.js are you using?**

10.0.3

**What version of Node.js are you using?**

14.3.0

**What browser are you using?**

Firefox

**What operating system are you using?**

Windows

**How are you deploying your application?**

yarn dev

**Describe the Bug**

A component with Links is unmounted and this error appears:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
Link@http://localhost:3001/_next/static/chunks/pages/_app.js?ts=1610463142312:92630:19
```

It points to `useIntersection`:

```current use-intersection.tsx:31```

I assume that it calls `setVisible`  when component, and therefore this hook, is unmounted.

**Expected Behavior**

`setIntersection` should clean correctly its side-effects.

**To Reproduce**

```
export const Nav = () => {
  const [show, setShow] = React.useState(true);

  React.useEffect(() => {
    setShow(false);
  }, []);

  return  show ? <Link href="/"><a>Home</a></Link> : null
}
```

**Comment by kaykdm** [comment] 2021-01-13 08:04
I think this is fixed in https://github.com/vercel/next.js/pull/20407
try latest Next.js

**Comment by timneutkens** [comment] 2021-01-13 13:33
Yep that was fixed, please try the latest Next.js version.

**Closed by timneutkens** 2021-01-13 13:33 UTC
Labels: template: bug

**Comment by filipesmedeiros** [comment] 2021-04-26 12:25
Hey, is it possible to know what version includes a given PR? Or should we just always update to the latest one?

**Comment by balazsorban44** [comment] 2022-01-28 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
