### ISSUE TITLE
Module not found: Can't resolve '../build/Release/xxhash'

### ISSUE THREAD

**Issue by isaced** [vercel/next.js#62193] opened 2024-02-17 15:21 UTC
### Link to the code that reproduces this issue

https://github.com/isaced/nextjs-lz4-issue-reproduction

### To Reproduce

1. npm i
2. npm run dev
3. open `http://localhost:3001`
4. got error:

```
➜  nextjs-lz4-test git:(main) ✗ npm run dev

> nextjs-lz4-test@0.1.0 dev
> next dev

 ⚠ Port 3000 is in use, trying 3001 instead.
   ▲ Next.js 14.1.0
   - Local:        http://localhost:3001

 ✓ Ready in 1229ms
 ⨯ ./node_modules/lz4/lib/utils.js:4:10
Module not found: Can't resolve '../build/Release/xxhash'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/lz4/lib/static.js
./node_modules/lz4/lib/lz4.js
./app/page.tsx
 ○ Compiling / ...
 ⨯ ./node_modules/lz4/lib/utils.js:4:10
Module not found: Can't resolve '../build/Release/xxhash'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/lz4/lib/static.js
./node_modules/lz4/lib/lz4.js
./app/page.tsx
 ⨯ ./node_modules/lz4/lib/utils.js:4:10
Module not found: Can't resolve '../build/Release/xxhash'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/lz4/lib/static.js
./node_modules/lz4/lib/lz4.js
./app/page.tsx
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
^C
```

### Current vs. Expected behavior

Translation: "If I directly execute `lz4-test.js`([node-lz4](https://github.com/pierrec/node-lz4)) in the root directory using Node, it works fine, but when I put it into Next.js, it throws an error `Module not found: Can't resolve '../build/Release/xxhash'...`.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: 8.12.1
Relevant Packages:
  next: 14.1.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by isaced** [comment] 2024-02-18 03:13
It looks like I can fix this by adding the following configuration to `next.config.mjs`.

```ts
const nextConfig = {
  output: "standalone",
  experimental: {
    serverComponentsExternalPackages: ["lz4"],  // <-add this
  },
};

export default nextConfig;
```

**Comment by samcx** [comment] 2024-02-21 06:51
@isaced Since this is not a bug issue (the expected behavior), I will be closing this issue!

**Closed by samcx** 2024-02-21 06:51 UTC
Labels: template: bug
