### ISSUE TITLE
External image broken on Vercel builds with next/image

### ISSUE THREAD

**Issue by wobsoriano** [vercel/next.js#19630] opened 2020-11-28 16:28 UTC
# Bug report

## Describe the bug

When using an external image with dynamic query params like what Reddit has, it works on development but when deployed to Vercel, `INTERNAL_UNEXPECTED_ERROR` will be thrown.

## To Reproduce

Create a fresh Next app and paste this on your `index.js` file and deploy to Vercel.

```javascript
import Image from 'next/image'

export default function Home() {
  const src = "https://preview.redd.it/p4nxklz18z161.jpg?width=640&crop=smart&auto=webp&s=0cc1daae30269488f127e29e2db48e201456bf40";

  return (
    <div>
      <Image width="640" height="853" src={src} />
    </div>
  )
}
```

Repo:  https://github.com/wobsoriano/next-image-error
Demo: https://image-error-next.vercel.app/
Vercel image URL: https://bit.ly/3mhJdrc

## Expected behavior

I expect it to work on Vercel just as it does on local development.

## System information

- OS: Mac OS
- Version of Next.js: 10.0.3
- Deployment: Vercel

**Comment by wobsoriano** [comment] 2020-11-28 16:30
Might be related to this issue https://github.com/vercel/next.js/issues/19374

**Comment by timneutkens** [comment] 2020-12-01 09:34
Hey! Thanks for the report, the issue was querystring parameters being reordered and reddit not being able to handle that. We've deployed a patch for this behavior so that querystring order is preserved and the images now work, e.g.: `https://image-error-next.vercel.app/_next/image?url=https://preview.redd.it/p4nxklz18z161.jpg%3Fwidth%3D640%26crop%3Dsmart%26auto%3Dwebp%26s%3D0cc1daae30269488f127e29e2db48e201456bf40&w=640&q=75`

I'll close this issue as it's been resolved 👍

**Closed** 2020-12-01 09:34 UTC
Labels: kind: bug

**Comment by balazsorban44** [comment] 2022-01-29 02:12
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
