### ISSUE TITLE
err is not typed in AppProps

### ISSUE THREAD

**Issue by nsylke** [vercel/next.js#14345] opened 2020-06-18 23:30 UTC
# Bug report

## Describe the bug

I was looking at the [with-sentry](https://github.com/vercel/next.js/blob/canary/examples/with-sentry) example and when I was going to add the `err` to my _app.tsx, I noticed there are no typings and I receive the following error:

```
Property 'err' does not exist on type 'AppPropsType<Router, {}>'.ts(2339)
```

## To Reproduce

1. Create new next.js app with typescript
2. Try to add `err` in `_app.tsx`

## Expected behavior

`err` to have typings in `AppProps`

## Screenshots

```ts
import { AppProps } from 'next/app';

const MyApp = ({ Component, pageProps, err }: AppProps) => (
    <Component {...pageProps} err={err}/>
)
```

## System information

- OS: Windows 10
- Browser (if applies): Brave
- Version of Next.js: 9.4.4
- Version of Node.js: 12.14.1

**Comment by ijjk** [comment] 2020-09-10 22:28
Hi, `err` is not a default `prop` passed to `_app` so the type appears to be correct. If you would like to extend the type to include this you can do `AppProps & { err: ErrorType }`. 

I'm going to close this since it doesn't appear to require changes from Next.js

**Closed by ijjk** 2020-09-10 22:28 UTC
Labels: kind: story, type: needs investigation

**Comment by pc-beast** [comment] 2021-04-13 14:30
I am getting this error ```Cannot find name 'ErrorType'```
@ijjk

**Comment by balazsorban44** [comment] 2022-01-28 13:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
