### ISSUE TITLE
Navigating away from parallel route with router.push() doesn't trigger catch-all

### ISSUE THREAD

**Issue by wesferoli** [vercel/next.js#64807] opened 2024-04-19 23:13 UTC
### Link to the code that reproduces this issue

https://github.com/wesferoli/parallel-routes-bug-example

### To Reproduce

1. Run the application (`npm run dev`).
2. Click the button 'Go to /details'. The `/details` parallel route will be rendered.
3. Click the button 'Go to /'.
4. The application is redirected to the root route but the parallel route is not unmounted.

### Current vs. Expected behavior

I expected the parallel route to be unmounted when navigating to a different route, just like using `router.back()`. Instead, the parallel route is not unmounted, keeping an unwanted component on the screen. My real use case is a modal on a parallel route that is not able to be closed due to this bug.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home Single Language
  Available memory (MB): 20260
  Available CPU cores: 8
Binaries:
  Node: 18.17.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.3.0-canary.12 // Latest available version is detected (14.3.0-canary.12).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Parallel & Intercepting Routes

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

The first time I encountered this problem was at v14.2.0, previously at v14.1.4 I didn't have this issue.

**Comment by ztanner** [comment] 2024-04-20 01:19
Hi @wesferoli! I took a look at the reproduction and it looks like this is the expected behavior. A catch-all route will match all routes except for the "index" route that it's defined in. Meaning `/foo`, `/bar`, `/foo/bar`, ...etc, but not `/`. 

With parallel routes, during a soft navigation (ie when clicking a `Link`) the router will attempt to match the page to a corresponding parallel route. If one doesn't exist, it'll keep whatever was previously in that slot, until you refresh the page. You can learn about that behavior [here](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#active-state-and-navigation).

To get the behavior you're looking for, you can create a `@details/page.tsx` component that returns `null`. That way when the `/` is navigated to, it'll match to this component, where you're telling it to render `null`.

Here's a quick video after adding that file to your reproduction:


https://github.com/vercel/next.js/assets/1939140/fdf7c495-9f5b-46c1-956d-9d45819f3a0a



I'm going to close this issue but feel free to follow-up with any questions about it!

**Closed by ztanner** 2024-04-20 01:19 UTC
Labels: bug, Parallel & Intercepting Routes
