### ISSUE TITLE
Yarn 2 PnP support

### ISSUE THREAD

**Issue by balazsorban44** [vercel/next.js#20955] opened 2021-01-10 22:09 UTC
**Describe the feature you'd like to request**

Referencing this tweet https://twitter.com/balazsorban44/status/1348374181268910085?s=19

We got asked for better Yarn 2 PnP support at `next-auth`, but according to my understanding, the changes should be done in Next.js instead. 

This issue has been raised at our repository first: https://github.com/nextauthjs/next-auth/pull/1034

**Describe the solution you'd like**

@arcanis had a suggestion how to resolve this, see https://github.com/nextauthjs/next-auth/pull/1034#issuecomment-757546105

**Describe alternatives you've considered**

Haven't used Yarn 2 PnP myself so couldn't have considered alternatives.

**Comment by merceyz** [comment] 2021-01-10 23:44
Next.js already supports PnP, this is just a bug in general and not specific to PnP, it's just that PnP highlights it

**Comment by iaincollins** [comment] 2021-01-11 00:17
Hi folks! Thanks for raising! Having reviewed I think we can safely close this one.

I have rejected the request to update NextAuth.js in relation to this PR.

[Process is a built-in in Node.js](https://nodejs.org/en/knowledge/getting-started/the-process-module/) and is being used correctly. Suggest taking this up with the Yarn folks.

**Comment by arcanis** [comment] 2021-01-11 00:25
@iaincollins You're incorrect, please read my comments on the issue you closed. Next transforms `process.xxx` into `require('process').xxx`. This has nothing to do with Yarn, except that the problem is highlighted there:

- https://github.com/nextauthjs/next-auth/pull/1034#issuecomment-757546105
- https://github.com/nextauthjs/next-auth/pull/1034#issuecomment-757568405

**Comment by iaincollins** [comment] 2021-01-11 00:48
It's correct usage according to the Node.js documentation (linked to above) and it works absolutely fine with the package manager that ships with Node.js. If you are asserting the Node.js documentation incorrect or outdated, that's interesting...

We won't be addressing this issue NextAuth.js without better justification.

As this issue isn't specific to Next.js I don't want to comment about it further on here.

**Comment by arcanis** [comment] 2021-01-11 07:39
> As this issue isn't specific to Next.js I don't want to comment about it further on here.

Fair enough, but I'm not writing specifically to you; I don't want to let misunderstanding spread to other readers.

As I mentioned in the other issue, your code is executed both in the browser and in Node. The `process` global indeed exists in Node, but not in the browser. As a result, and as I've been telling you repeatedly, Next.js transpiles it into `require('process')`, with this module being a shim. Since it's a `require` call, it goes through the Webpack resolution pipeline. And since Webpack currently has no information relative to its origin, it resolves it relative to the package that uses it, ie `next-auth` in this case.

It's likely not a `next-auth` issue, I assume that Next.js will want to fix that to make it an absolute import instead, but please stop affirming that it's a bug in Yarn when it should be really clear it isn't.

**Comment by iaincollins** [comment] 2021-01-11 10:19
> As I mentioned in the other issue, your code is executed both in the browser and in Node. 

I've clarified this for you in the PR.

> It's likely not a next-auth issue, I assume that Next.js will want to fix that to make it an absolute import instead, but please stop affirming that it's a bug in Yarn when it should be really clear it isn't.

Where did I do that?

**Comment by Timer** [comment] 2021-01-11 12:48
Reopening because the PR was merged without tests. We need tests so we don't regress.

**Comment by Timer** [comment] 2021-01-22 17:39
Since it's not immediately clear how to test this, I'll close this for now.

**Closed by Timer** 2021-01-22 17:39 UTC
Labels: kind: story

**Comment by merceyz** [comment] 2021-01-22 17:42
Adding any `example` that uses `process` (but not `process.env`) to the pnp test list should cover it
https://github.com/vercel/next.js/blob/74b6389bd60505d3a2a8d902241e344b65356f1a/test-pnp.sh#L1-L8

**Comment by balazsorban44** [comment] 2022-01-28 19:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
