### ISSUE TITLE
Live Next.js docs are showing canary branch

### ISSUE THREAD

**Issue by jtaaa** [vercel/next.js#27662] opened 2021-08-01 13:12 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

[v11.0.2-canary.21](https://github.com/vercel/next.js/releases/tag/v11.0.2-canary.21) introduced the `onLoadingComplete` callback to the docs according to the release notes.

This callback is not yet available on my version v11.0.1 but documentation for it is live here https://nextjs.org/docs/api-reference/next/image#onloadingcomplete.

Could be related to: https://github.com/vercel/next.js/issues/27651

Please let me know if this is intentional. I know this is not a Next.js core bug but the other categories were less suitable.

### Expected Behavior

I expect to see the documentation for the latest stable version of Next.js on https://nextjs.org/docs or I expect to be able to change what version I am looking at.

I have tried in an incognito tab to confirm I am not viewing the canary documentation unintentionally.

### To Reproduce

1. [Visit this link](https://nextjs.org/docs/api-reference/next/image#onloadingcomplete) and read documentation
2. Try using the `onLoadingComplete` callback in the example project on v11.0.1 (not next@canary)

**Comment by timneutkens** [comment] 2021-08-03 12:11
This is intentional right now given that we wanted to deploy some other docs updates earlier than the next stable release. A new stable version that supports `onLoadingComplete` will be released soon.

**Closed by timneutkens** 2021-08-03 12:11 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
