### ISSUE TITLE
Nextjs not pre-rendering the markup.

### ISSUE THREAD

**Issue by jaisharx** [vercel/next.js#24173] opened 2021-04-17 13:47 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

14.15.5

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

I created a simple website with nextjs and chakra UI. The github repo is [this](https://github.com/jaisharx/designwiz-resketched), and deployed version of the website is [this](https://designwiz-resketched.vercel.app/).

There were some layout shifts happening when the page was loading, so I decided to check the source code generated, and to my curiosity, there was no markup being pre-rendered. Even though I have no data blocking requests for the page.

I'm using the component library - chakra UI for the website, according to their website I have configured it as it say. So I don't think this is some misconfiguration issue. I also tried putting some regular markup in my index.js. That too was not being pre-rendered. What's wrong??? Please help!

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <meta name="next-head-count" content="2" />
        <noscript data-n-css=""></noscript>
        <link
            rel="preload"
            href="/_next/static/chunks/webpack-50bee04d1dc61f8adf5b.js"
            as="script"
        />
        <link
            rel="preload"
            href="/_next/static/chunks/framework.e3de07479da4f2477dea.js"
            as="script"
        />
        <link
            rel="preload"
            href="/_next/static/chunks/f6078781a05fe1bcb0902d23dbbb2662c8d200b3.579220d75ca80485fda3.js"
            as="script"
        />
        <link
            rel="preload"
            href="/_next/static/chunks/main-8e2d0760268ce71607e7.js"
            as="script"
        />
        <link
            rel="preload"
            href="/_next/static/chunks/71247caf95475e3ea7f9a0f8a30beb258b23d005.4bcd1e5f5a3dd167b1df.js"
            as="script"
        />
        <link
            rel="preload"
            href="/_next/static/chunks/pages/_app-64195b0ff569ce8f9fb4.js"
            as="script"
        />
        <link
            rel="preload"
            href="/_next/static/chunks/pages/index-6b6f17623785eabb42df.js"
            as="script"
        />
    </head>
    <body>
        <div id="__next"><span></span></div>
        <script id="__NEXT_DATA__" type="application/json">
            {
                "props": { "pageProps": {} },
                "page": "/",
                "query": {},
                "buildId": "exlLeKFE1JEKKR-bHeVzI",
                "nextExport": true,
                "autoExport": true,
                "isFallback": false
            }
        </script>
        <script
            nomodule=""
            src="/_next/static/chunks/polyfills-4f14e8c8ea1352d3ef0d.js"
        ></script>
        <script
            src="/_next/static/chunks/webpack-50bee04d1dc61f8adf5b.js"
            async=""
        ></script>
        <script
            src="/_next/static/chunks/framework.e3de07479da4f2477dea.js"
            async=""
        ></script>
        <script
            src="/_next/static/chunks/f6078781a05fe1bcb0902d23dbbb2662c8d200b3.579220d75ca80485fda3.js"
            async=""
        ></script>
        <script
            src="/_next/static/chunks/main-8e2d0760268ce71607e7.js"
            async=""
        ></script>
        <script
            src="/_next/static/chunks/71247caf95475e3ea7f9a0f8a30beb258b23d005.4bcd1e5f5a3dd167b1df.js"
            async=""
        ></script>
        <script
            src="/_next/static/chunks/pages/_app-64195b0ff569ce8f9fb4.js"
            async=""
        ></script>
        <script
            src="/_next/static/chunks/pages/index-6b6f17623785eabb42df.js"
            async=""
        ></script>
        <script
            src="/_next/static/exlLeKFE1JEKKR-bHeVzI/_buildManifest.js"
            async=""
        ></script>
        <script
            src="/_next/static/exlLeKFE1JEKKR-bHeVzI/_ssgManifest.js"
            async=""
        ></script>
    </body>
</html>
```

Above is what is being served as the markup, you can check the markup on the live website too.

### Expected Behavior

Pre-rendering markup is like the thing of nextjs, and that is not working even though I have no data blocking requests like getStaticProps or getServerSideProps in my index.js page. Getting pre-rendering up and working would be good.

### To Reproduce

My github repo for the nextjs website is public, the link is [https://github.com/jaisharx/designwiz-resketched](https://github.com/jaisharx/designwiz-resketched). Please help.

**Comment by ijjk** [comment] 2021-04-17 22:06
This appears to be from the handling in the chakra-ui EnvironmentProvider component and not related to Next.js, here's a related upstream issue you can follow https://github.com/chakra-ui/chakra-ui/issues/3844

I'm going to close this since it's an upstream provider and not related to Next.js itself.

**Closed by ijjk** 2021-04-17 22:06 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
