### ISSUE TITLE
Nextjs / SWC + Deckgl compile issue

### ISSUE THREAD

**Issue by brandonjpierce** [vercel/next.js#30904] opened 2021-11-03 17:57 UTC
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome 95

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

This appears to be a resurfacing of https://github.com/vercel/next.js/issues/8973 except with SWC as the potential culprit.

Full detail included in this issue: https://github.com/visgl/deck.gl/issues/6357

### Expected Behavior

Full detail included in this issue: https://github.com/visgl/deck.gl/issues/6357

### To Reproduce

Full detail included in this issue: https://github.com/visgl/deck.gl/issues/6357

**Comment by jbergstroem** [comment] 2021-11-04 11:58
Looks similar to the issue I am running into (#30839).

**Comment by balazsorban44** [comment] 2021-12-24 00:16
Closing since this is resolved according to the OP: https://github.com/visgl/deck.gl/issues/6357#issuecomment-982731254

**Closed by balazsorban44** 2021-12-24 00:16 UTC
Labels: template: bug, area: SWC transforms

**Comment by balazsorban44** [comment] 2022-01-27 01:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
