### ISSUE TITLE
Custom loaders are not recognized by next export

### ISSUE THREAD

**Issue by janhoogeveen** [vercel/next.js#21079] opened 2021-01-13 19:50 UTC
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

v15.5.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

next export

**Describe the Bug**

I'm using next/image with a custom loader. The reason for the custom loader is that I've optimised all images on build-time.

When I run `next export` I will get this message:

> Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
> Possible solutions:
>   - Use `next start`, which starts the Image Optimization API.
>   - Use Vercel to deploy, which supports Image Optimization.
>   - Configure a third-party loader in `next.config.js`.

**Expected Behavior**

Next.js understands that I'm using a custom loader, and that a static export would work fine.

Maybe an option is to pass the custom loader as a function to next.config.js?

```js
module.exports = {
  images: {
    loader: (width, src, quality) => `/preprocessed-images/${filename}-${width}.jpg`
  },
}

```

I would also be fine with an API like this:

```js
module.exports = {
  images: {
    loader: 'static'
  },
}

```

**To Reproduce**

- Use next/image with a custom loader (see body for examples)
- Run next export

This is all possibly related to https://github.com/vercel/next.js/issues/19612, although I didn't get the impression that the issue was recognized as such.

**Custom loader**
I've got a custom loader defined:
For the example I'm just a default return statement, but normally I'm using some props and helpers here

```ts
const myLoader = ({src}) => {
  return `/preprocessed-images/${src}`;
};
```

**Image component**
```jsx
<Image
	loader={myLoader}
    src={`e72657a9019403244cd61aebf1a5752ce1d03b51.jpg`}
    width="640"
    height={480}
/>
```

**Preprocessed images**

My folder of preprocessed images looks like this:
![image](https://user-images.githubusercontent.com/882219/104502198-9bcef900-55e0-11eb-8bd5-799d2b041886.png)

In my mind, this should work, but I can't tell Next.js that I don't need a Node server.

Let me know if you need a reduced test case or an example (I already have one). I can't publicly post the full example here, _yet_.

**Comment by MrSaints** [comment] 2021-02-03 00:25
Potentially related https://github.com/vercel/next.js/discussions/19372

**Comment by andrekutianski** [comment] 2021-03-06 05:08
same here, no settings from docs works or anything that can un-set the 'default' image loader or possibility to create a custom. I will abandon the use of this framework just because the enforcement of use vercel 'image optimation

**Comment by leerob** [comment] 2021-03-12 01:04
This does appear to be an issue, also reported with https://github.com/vercel/next.js/discussions/22980. Moving convo here!

> I will abandon the use of this framework just because the enforcement of use vercel 'image optimation

It's not enforcing you to use Vercel, this is just a bug 👍

**Comment by Simply007** [comment] 2021-03-30 07:40
Hello everybody,

@leerob - do you have any further info about the ETA?

**Comment by Simply007** [comment] 2021-03-30 07:46
BTW: to make my custom loader working correctly, I needed
 to set a path to an empty string - @MrSaints "https://noop/" was prepending this to the final image URLs" :
 
 https://github.com/Kentico/kontent-starter-corporate-next-js/blob/186d3ca678583cdd01fe845eb8bbe3f5d118ea4b/next.config.js#L6
 
 ```js
   images: {
    loader: "imgix",
    path: "",
  }
```

[the custom loader logic](https://github.com/Kentico/kontent-starter-corporate-next-js/blob/main/utils/kontentImageLoader.js) (should be irrelevant but for the context)

**Comment by ptcampbell** [comment] 2021-04-06 03:12
`The next/image component's default loader is not supported when using next export. However, other loader options will work.`

Is this supposed to have been fixed in 10.1? I get the same error whether I use the above workaround or supply my own custom loader.

**Comment by superbull** [comment] 2021-04-17 03:20
Vote for this api:

> Maybe an option is to pass the custom loader as a function to next.config.js?
> 
> ```
> module.exports = {
>   images: {
>     loader: (width, src, quality) => `/preprocessed-images/${filename}-${width}.jpg`
>   },
> }
> ```

**Comment by PatrickMcLennan** [comment] 2021-04-18 03:51
+1 to receiving this.  Custom loader works great with dev and production servers, but running `next export` gives me the warning that there is no custom loader.

**Comment by dougaraujos** [comment] 2021-04-20 21:08
+1

**Comment by richstokes** [comment] 2021-05-03 04:09
+1

Adding 

```
images: {
   loader: "imgix",
   path: "",
 }
```

It will export, but when I open the resultant index.html, none of the images or JS load :(

**Comment by MuhammadArslan118** [comment] 2021-05-18 10:46
add this into your next.config.js
module.exports = {
  images: {
    loader: "imgix",
    path: "",
  },
};
and this
yarn add --dev replace-in-files-cli

Then, add these two scripts to your package.json

"build-static": "next build && next export && npm run build-static-repair-index",

"build-static-repair-index": "replace-in-files --string \"/_next/static\" --replacement \"./_next/static\" out/index.html"

Then just call

npm run build-static

its working in my app---

**Comment by robbie-c** [comment] 2021-05-24 21:35
+1 was investigating using next.js for our company site but decided not to because of this

This would have been fine:
```
module.exports = {
  images: {
    loader: 'static'
  },
}
```

**Comment by EngAhmedMahmoud** [comment] 2021-06-01 13:12
> +1
> 
> Adding
> 
> ```
> images: {
>    loader: "imgix",
>    path: "",
>  }
> ```
> 
> It will export, but when I open the resultant index.html, none of the images or JS load :(

Yes it's working with me also thanks 👍

**Comment by franklinjavier** [comment] 2021-06-25 16:36
> +1
> 
> Adding
> 
> ```
> images: {
>    loader: "imgix",
>    path: "",
>  }
> ```
> 
> It will export, but when I open the resultant index.html, none of the images or JS load :(

it worked for me

```jsx
module.exports = {
  images: {
    loader: 'imgix',
    path: '/',
  },
}
```

**Comment by vitaminac** [comment] 2021-06-26 14:38
I faced the same problem when using `next/image` with `next export` command, even in every usage of `next/image` I've specified the loader option. I still receive the error of

> Error: Image Optimization using Next.js' default loader is not compatible with next export.
> Possible solutions:
> 
> Use next start, which starts the Image Optimization API.
> Use Vercel to deploy, which supports Image Optimization.
> Configure a third-party loader in next.config.js.

The solution is to add following config inside the next.config.js

```
module.exports = {
  images: {
    loader: 'imgix',
    path: '',
  },
}
```

But I don't think it is good to says `imgix `when we don't use it. If I changed to


```
module.exports = {
  images: {
    loader: 'static'
  },
}
```

I will receive error of

```
Error: Specified images.loader should be one of (default, imgix, cloudinary, akamai), received invalid value (static).
See more info here: https://nextjs.org/docs/messages/invalid-images-config
```

Checking the code only a subset of value is allowed https://github.com/vercel/next.js/blob/0750092cf1a0e4f0c643e15b0608607884a3e4eb/packages/next/next-server/server/config.ts#L267 and https://github.com/vercel/next.js/blob/62a4de9f8c23fe753650b78d4bd892d0081bc6b7/packages/next/next-server/server/image-config.ts#L1.

Maybe we can just add static to this list and update the doc to solve the problem https://github.com/vercel/next.js/blob/62a4de9f8c23fe753650b78d4bd892d0081bc6b7/packages/next/next-server/server/image-config.ts#L1

**Comment by MohanSai1997** [comment] 2021-06-30 17:48
> same here, no settings from docs works or anything that can un-set the 'default' image loader or possibility to create a custom. I will abandon the use of this framework just because the enforcement of use vercel 'image optimation

I think they are holding this feature to force the developers to use Vercel platform 😂

**Comment by rohan-deshpande** [comment] 2021-07-01 00:40
I want to chime in here and say that I currently do not understand how this API is supposed to work as the docs indicate. 

I'm building an app with Firebase and my images are stored in their Cloud Storage layer. My app uses Firebase's API to retrieve the the absolute URL for the image from Cloud Storage. 

To get things to work I have done configured my `next.js.config` like so

```js
        images: {
          domains: ['firebasestorage.googleapis.com'],
        },
```

This works in dev, but when I try to export, I get the same error as everyone else saying I need to configure a custom loader. So I've done that

```js
  const myLoader = ({ src, width, quality }) => {
    return `${src}?w=${width}&q=${quality || 75}`;
  };
```

However, this still does not let me run the `export` function. I might be missing something but not sure how to get it to work currently.

**Comment by ArekBartnik** [comment] 2021-07-01 15:40
@rohan-deshpande this bug wasn't fixed. If you use custom loader for `Image` you can add this to `next.config.js`:

```
module.exports = {
  images: {
    domains: ['firebasestorage.googleapis.com'],
    loader: 'imgix' // this is a hack until the bug is fixed
  },
}
```

and the export command should work.

**Comment by rohan-deshpande** [comment] 2021-07-01 23:52
That causes the images to 404 with `_next/image` appended to their URLs. What's odd is that the custom loader function does not seem to get hit in dev

```
  const customLoader = ({ src, width, quality }) => {
    console.log('SRC', src); // this never logs
    return `${src}?w=${width}&q=${quality || 75}`;
  };

  return <Image src={firebaseCloudStorageAbsoluteURL} layout="fill" loader={customLoader} />;
```

**Comment by darshkpatel** [comment] 2021-07-02 08:13
Started a discussion for the RFC here: https://github.com/vercel/next.js/discussions/26850

**Comment by MartinVandersteen** [comment] 2021-07-07 12:54
@rohan-deshpande @ArekBartnik You need to specify the path property to avoid having your url prefixed with `_next/image`, like so : 

```
module.exports = {
  images: {
    domains: ['firebasestorage.googleapis.com'],
    loader: 'imgix', // this is a hack until the bug is fixed
    path: ''
  },
}
```

**Comment by leerob** [comment] 2021-07-07 19:42
Please follow the PR here! https://github.com/vercel/next.js/pull/26847

**Closed** 2021-07-08 19:35 UTC
Labels: good first issue, kind: bug

**Comment by styfle** [comment] 2021-07-09 13:23
PR #26998 is available in [11.0.2-canary.8](https://github.com/vercel/next.js/releases/tag/v11.0.2-canary.8).

You can try it out today with `yarn add next@canary`, thanks!

**Comment by kiranmarshall** [comment] 2021-08-07 00:02
> Potentially related https://github.com/vercel/next.js/discussions/19372
> 
> FWIW, the check isn't doing anything smart
> 
> https://github.com/vercel/next.js/blob/41b7c524fa38f92a656b559809fd14fe23112c1e/packages/next/export/index.ts#L333-L343
> 
> You can set:
> 
> ```
> images: {
>     loader: "imgix",
>     path: "https://noop/",
> },
> ```
> 
> And it'll pass.

Can you make it so we can pass 'custom' as a key (alternatively to passing the loader function) and not have it fail please? It's a small thing but this caught me out on the docs for ages because it infers that custom is an accepted value - I ended up passing cloudinary personally, despite the fact I'm using Contentful, and it works fine.

**Comment by leerob** [comment] 2021-08-08 15:46
@kiranmarshall Did you try this? https://github.com/vercel/next.js/issues/21079#issuecomment-877184867

**Comment by jcollum** [comment] 2021-08-13 21:17
For a brand new app created with `npm init next-app` I ran into an error when exporting to static with `path: ""` but `path: "https://noop/",` worked

**Comment by styfle** [comment] 2021-08-13 21:28
The `path` config option doesn't affect that error message.

You need to set `loader: "custom"` in next.config and then set a `loader` prop on image component to configure your 3rd party image optimization service.

See the Next.js 11.1.0 blog post here: https://nextjs.org/blog/next-11-1#other-image-improvements

**Comment by jcollum** [comment] 2021-08-13 21:35
This fix worked for me: 

```
  images: {
    loader: "imgix",
    path: "https://noop/",
  }
```

**Comment by Simply007** [comment] 2021-08-16 09:13
I have tested the `custom` loader and I am getting this error:

https://github.com/Kentico/kontent-starter-corporate-next-js/pull/51/checks?check_run_id=3338395712#step:6:46
```
Unhandled error during request: Error: Image with src "https://assets-us-01.kc-usercontent.com:443/***/32212623-9886-4799-a843-df36b46f4c17/pexels-fauxels-3184339.jpg" is missing "loader" prop.
Read more: https://nextjs.org/docs/messages/next-image-missing-loader
```

I have double-checked that the loader property is passed in my implementation: https://github.com/Kentico/kontent-starter-corporate-next-js/blob/custom-loader/components/Image.js

I have tested Next.js v11.1.0. 

My pull request with CI set to static export: https://github.com/Kentico/kontent-starter-corporate-next-js/pull/51

**Comment by styfle** [comment] 2021-08-16 14:01
@Simply007 You need to do two things:

1. Configure [`images.loader: "custom"`](https://nextjs.org/docs/basic-features/image-optimization#loader) in next.config.js
2. Add the [`loader`](https://nextjs.org/docs/api-reference/next/image#loader) prop to each image component

That error message looks like you did number 1 but not number 2.

If you visit the error message url printed there you'll find more info: https://nextjs.org/docs/messages/next-image-missing-loader

**Comment by Simply007** [comment] 2021-08-16 14:06
> but not number 2.

As I said - I have checked that I am passing `loader` property in Next Image component -> code here https://github.com/Kentico/kontent-starter-corporate-next-js/blob/custom-loader/components/Image.js#L21

I have debugged the process and the loader was initialized.

**Comment by Simply007** [comment] 2021-08-16 14:55
> > but not number 2.
> 
> As I said - I have checked that I am passing `loader` property in Next Image component -> code here https://github.com/Kentico/kontent-starter-corporate-next-js/blob/custom-loader/components/Image.js#L21
> 
> I have debugged the process and the loader was initialized.
> 
> -> I will add logging so that it is visible in CI log.
> 
> EDIT: @styfle
> Logging discovered that sometimes the loader is not set: https://github.com/Kentico/kontent-starter-corporate-next-js/pull/51/checks?check_run_id=3340892798#step:6:47 - I will dig deeper and describe the root cause in that comment - thx.

@styfle 

Just to share my conclusion. The problem was on my side 🤦‍♂️. I was not passing `loader` on a couple of places, because [I have been using bad react prop as a URL](https://github.com/Kentico/kontent-starter-corporate-next-js/pull/51/commits/60f3b9982b1c49d552bf2d5c490f2e63aaa0abaf).

**Comment by omarabid** [comment] 2021-09-07 16:39
This is annoying. I wasted a couple of hours for something that could have been disabled with a simple configuration line. Should add something like "image-optimization: false".

**Comment by balazsorban44** [comment] 2022-01-27 14:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
