### ISSUE TITLE
upload file and images

### ISSUE THREAD

**Issue by adammartiniri** [vercel/next.js#20661] opened 2021-01-01 13:33 UTC
# uploading file through nextjs api is tought 
people usaully have 2 choices 

1-import formidable 
then creating instance of FormDate and using formidable in api function

2-adding express js
creating a express.js custom server then adding multer or express-file-upload then doing the stuff

if you can make the job eaiser that' s good .

**Comment by lachlanjc** [comment] 2021-01-01 19:02
Hey! Check out https://github.com/leerob/nextjs-gcp-storage & https://github.com/leerob/nextjs-aws-s3. It's definitely not super straightforward but it's probably somewhere we should focus more on examples/documentation than building it into the framework imo

**Comment by timneutkens** [comment] 2021-01-03 15:15
Closing as the issue template was ignored/removed.

**Closed by timneutkens** 2021-01-03 15:15 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-28 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
