### ISSUE TITLE
Application lifecycle hooks

### ISSUE THREAD

**Issue by nickrttn** [vercel/next.js#20899] opened 2021-01-08 13:40 UTC
**Describe the feature you'd like to request**

I would like some way to hook into the lifecycle of the application, particularly running code on the client before mount.

My use case is testing whether I need to apply a certain polyfill and only loading its bundle asynchronously when it is actually required and only then mounting the application.

**Describe the solution you'd like**

The most frictionless solution would likely be to open up the file where the `ReactDOM.render` statement for the application is to users. I'm not entirely sure about where that would need to fit into the filesystem as it currently stands.

**Describe alternatives you've considered**

Some alternatives:
- An import `next/before-mount` that you can call `beforeMount(mount => { ... do stuff...;  mount() }`
- A new 'special' file, `_before-mount` in `pages/` with an exported function `export async function beforeMount()` similar to how `getStaticProps` and friends work.

**Comment by balazsorban44** [comment] 2021-01-10 22:37
https://github.com/vercel/next.js/discussions/9133 might be related

**Comment by timneutkens** [comment] 2021-01-11 09:08
Yep duplicate of #9133 and note that Next.js already automatically polyfills most basic JS features. If you're looking to polyfills IntersectionObserver you can also import the polyfill before executing the function in `useEffect`, which has the added benefit of only being loaded when the certain component is being used.

**Closed by timneutkens** 2021-01-11 09:08 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-28 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
