### ISSUE TITLE
ClassNames  col-gap-XX and row-gap-XX is not present in Tailwind

### ISSUE THREAD

**Issue by Babu-Mohammed-Izhan** [vercel/next.js#31578] opened 2021-11-18 14:43 UTC
### What example does this report relate to?

All cms- examples

### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

14.17.4

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

The TailwindCSS classnames for all the CMS examples have the classnames of col-gap-16 and col-gap-32 which are not present in Tailwind CSS and so the grid-gap is not working for the posts.

In the file components/more-stories.js it is:

```javascript
    <section>
      <h2 className="mb-8 text-6xl md:text-7xl font-bold tracking-tighter leading-tight">
        More Stories
      </h2>
      <div className="grid grid-cols-1 md:grid-cols-2 md:col-gap-16 lg:col-gap-32 row-gap-20 md:row-gap-32 mb-32">
        {posts.map((post) => (
          <PostPreview
            key={post.slug}
            title={post.content.title}
            coverImage={post.content.image}
            date={post.first_published_at || post.published_at}
            author={post.content.author}
            slug={post.slug}
            excerpt={post.content.intro}
          />
        ))}
      </div>
    </section>
```

As well as for components/cover-image.js:

```javascript
 <section>
      <div className="mb-8 md:mb-16">
        <CoverImage title={title} url={coverImage} slug={slug} />
      </div>
      <div className="md:grid md:grid-cols-2 md:col-gap-16 lg:col-gap-8 mb-20 md:mb-28">
        <div>
          <h3 className="mb-4 text-4xl lg:text-6xl leading-tight">
            <Link href={`/posts/${slug}`}>
              <a className="hover:underline">{title}</a>
            </Link>
          </h3>
          <div className="mb-4 md:mb-0 text-lg">
            <Date dateString={date} />
          </div>
        </div>
        <div>
          <p className="text-lg leading-relaxed mb-4">{excerpt}</p>
          <Avatar name={author.name} picture={author.content.picture} />
        </div>
      </div>
    </section>
```

### Expected Behavior

The  correct classnames should be gap-x-16 and gap-y-32 instead of col-gap-16 and row-gap-32.

The correct code for this file is:

```javascript
import PostPreview from "../components/post-preview";

export default function MoreStories({ posts }) {
  return (
    <section>
      <h2 className="mb-8 text-6xl md:text-7xl font-bold tracking-tighter leading-tight">
        More Stories
      </h2>
      <div className="grid grid-cols-1 md:grid-cols-2 md:gap-x-16 lg:gap-x-32 gap-y-20 md:gap-y-32 mb-32">
        {posts.map((post) => (
          <PostPreview
            key={post.slug}
            title={post.title}
            coverImage={post.coverImage}
            date={post.date}
            author={post.author}
            slug={post.slug}
            excerpt={post.excerpt}
          />
        ))}
      </div>
    </section>
  );
}

```

```javascript
 <section>
      <div className="mb-8 md:mb-16">
        <CoverImage title={title} url={coverImage} slug={slug} />
      </div>
      <div className="md:grid md:grid-cols-2 md:gap-x-16 lg:gap-x-8 mb-20 md:mb-28">
        <div>
          <h3 className="mb-4 text-4xl lg:text-6xl leading-tight">
            <Link href={`/posts/${slug}`}>
              <a className="hover:underline">{title}</a>
            </Link>
          </h3>
          <div className="mb-4 md:mb-0 text-lg">
            <Date dateString={date} />
          </div>
        </div>
        <div>
          <p className="text-lg leading-relaxed mb-4">{excerpt}</p>
          <Avatar name={author.name} picture={author.content.picture} />
        </div>
      </div>
    </section>
```

### To Reproduce

This bug is present in all the cms examples in the component/more-stories.js files. as well as the components/cover-image.js file for all the cms examples.

**Comment by harish-sethuraman** [comment] 2022-01-03 11:12
I see that the examples work fine since it uses an older tailwind version (2.2.4).

Also, col-gap and row-gap were deprecated in a later version (~3).

Commit reference of deprecation:
https://github.com/tailwindlabs/tailwindcss/commit/338dc12eea8c2330bbb593cdb95822974adb600b

Live site working CSS:
 ![Screenshot 2022-01-03 at 4 32 01 PM](https://user-images.githubusercontent.com/32865581/147923461-e7dc5019-b8a4-44e4-9a5f-9a37cab83cff.png)

This issue can be marked as invalid I guess 😄

**Comment by balazsorban44** [comment] 2022-01-05 02:49
Until those examples are upgraded to Tailwind 3, I agree that this is not an issue. Feel free to upgrade Tailwind for those examples.

**Closed by balazsorban44** 2022-01-05 02:49 UTC
Labels: good first issue, area: examples

**Comment by balazsorban44** [comment] 2022-02-04 03:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
