### ISSUE TITLE
Development performance improvements

### ISSUE THREAD

**Issue by vjpr** [vercel/next.js#4844] opened 2018-07-25 20:29 UTC
After discussions with @timneutkens, here are several ways to make Next.js faster to work with during development.

- [hard-source-webpack-plugin](https://github.com/mzgoddard/hard-source-webpack-plugin)
- [`resolve.unsafeCache`](https://webpack.js.org/configuration/resolve/#resolve-unsafecache)
- [autodll-webpack-plugin](https://github.com/asfktz/autodll-webpack-plugin) - Share common deps with disk caching.
- Webpack@5 module disk cache (https://github.com/webpack/webpack/issues/6527)
- [cache-loader](https://github.com/webpack-contrib/cache-loader) - Caches the result of following loaders on disk
- [Prebuild next.js pages on server start](https://github.com/zeit/next.js/issues/4843)
- [Allow multiple pages in the same bundle](https://github.com/zeit/next.js/issues/4841)
- Reduce size of common deps
  - Lodash = babel-plugin-lodash + lodash-webpack-plugin + https://medium.com/making-internets/why-using-chain-is-a-mistake-9bc1f80d51ba

## Metrics

- Server start time.
- Incremental build time for changes on same page (HMR).
- Direct page visit (typing in url).
- Navigating to new page via a link.
- SSR of React Component

## Profiling tools

- Chrome DevTools `--inspect` - profile any part of the app (including flamecharts with a slightly easier workflow than ProfilerPlugin I think)
- ProfilerPlugin in Webpack@4 - generates flamecharts for builds
- `webpackDevMiddleware.stats = 'verbose'`
- Monkey-patch next build to show `stats.toString()`
- WebpackAnalyzePlugin
- require('perf_hooks') - https://nodejs.org/api/perf_hooks.html

**Comment by vjpr** [comment] 2018-07-25 20:29
## autodll-webpack-plugin

I tried this and it works quite well out of the box. The website says it will become obsolete soon because of hard-source and webpack@5, but its still quite useful today, especially for sharing deps between Next.js page bundles.

**Comment by timneutkens** [comment] 2018-09-07 10:57
`autodll-webpack-plugin` has been implemented for react and react-dom at least 👍

**Comment by timneutkens** [comment] 2018-09-07 12:51
`resolve.unsafeCache` is `true` by default apparently, so there's no gain there, unfortunately.

**Comment by timneutkens** [comment] 2018-09-16 15:06
Implemented hard-source-webpack-plugin in #5181. Releasing it on canary right now.

**Comment by vjpr** [comment] 2018-12-10 12:54
@timneutkens We should try webpack 5 with built-in disk cache https://twitter.com/TheLarkInn/status/1069246795031576576

**Comment by timneutkens** [comment] 2018-12-10 13:14
@divmain is working on build optimizations, starting with this PR: https://github.com/zeit/next.js/pull/5810

**Comment by bz-stripe** [comment] 2019-11-14 18:34
Have there been any updates on this work? Especially https://github.com/zeit/next.js/issues/4843

**Comment by kachkaev** [comment] 2019-11-14 18:44
Possibly related issue (still needs investigation): https://github.com/zeit/next.js/issues/9153

**Comment by timneutkens** [comment] 2019-11-14 18:51
We're investigating other optimizations currently.

**Comment by glopezep** [comment] 2020-04-01 16:11
@timneutkens is it will be possible Allow multiple pages in the same bundle for development performance improvement #4843 ? because navigating is really slowly but only on development

**Comment by glopezep** [comment] 2020-04-16 04:05
> After discussions with @timneutkens, here are several ways to make Next.js faster to work with during development.
> 
> * [hard-source-webpack-plugin](https://github.com/mzgoddard/hard-source-webpack-plugin)
> * [`resolve.unsafeCache`](https://webpack.js.org/configuration/resolve/#resolve-unsafecache)
> * [autodll-webpack-plugin](https://github.com/asfktz/autodll-webpack-plugin) - Share common deps with disk caching.
> * Webpack@5 module disk cache ([webpack/webpack#6527](https://github.com/webpack/webpack/issues/6527))
> * [cache-loader](https://github.com/webpack-contrib/cache-loader) - Caches the result of following loaders on disk
> * [Prebuild next.js pages on server start](https://github.com/zeit/next.js/issues/4843)
> * [Allow multiple pages in the same bundle](https://github.com/zeit/next.js/issues/4841)
> * Reduce size of common deps
>   
>   * Lodash = babel-plugin-lodash + lodash-webpack-plugin + https://medium.com/making-internets/why-using-chain-is-a-mistake-9bc1f80d51ba
> 
> ## Metrics
> * Server start time.
> * Incremental build time for changes on same page (HMR).
> * Direct page visit (typing in url).
> * Navigating to new page via a link.
> * SSR of React Component
> 
> ## Profiling tools
> * Chrome DevTools `--inspect` - profile any part of the app (including flamecharts with a slightly easier workflow than ProfilerPlugin I think)
> * ProfilerPlugin in Webpack@4 - generates flamecharts for builds
> * `webpackDevMiddleware.stats = 'verbose'`
> * Monkey-patch next build to show `stats.toString()`
> * WebpackAnalyzePlugin
> * require('perf_hooks') - https://nodejs.org/api/perf_hooks.html

**Comment by timneutkens** [comment] 2020-04-16 08:03
We're currently working on upgrading to webpack 5 incrementally. webpack 5 has a built-in disk cache which will help with a lot of the slowdowns that were previously noted with webpack 4.

**Comment by chaddjohnson** [comment] 2020-06-19 19:31
Would these improvements also help reduce production build time, or are they specifically targeted at development?

**Comment by remorses** [comment] 2020-09-23 10:19
I noticed that in developement some packages that expose both `main` and `module` entrypoints get loaded 2 times by webpack, the client webpack config loads the `module` esm entrypoint, the server webpack config loads the `main` cjs entrypoint instead

It would be faster to only use the `main` entrypoint in developement to not run loaders twice (use the same cache)

**Comment by timneutkens** [comment] 2020-09-23 11:07
> It would be faster to only use the main entrypoint in developement to not run loaders twice (use the same cache)

This is a misconception. The loaders have different settings between the 2 configs as well. `node_modules` are not compiled for the server bundle btw.

**Comment by malixsys** [comment] 2021-02-26 15:40
This happens on first access, but can we trigger it via an api call to NextServer?
```bash
event - build page: /
event - compiled successfully
```

**Comment by timneutkens** [comment] 2021-11-17 14:32
Now that Next.js 12 is out I'm going to close this issue: https://nextjs.org/blog/next-12#faster-builds-and-fast-refresh-with-rust-compiler

Note that closing this issue does not mean that we're going to stop optimizing Next.js performance, just that the things mentioned in this issue have been (mostly) implemented as well as many other optimizations that improve speed. We're still working on many other performance improvements on top of the new Rust-based compiler.

If you're experiencing slowdowns with your application please see https://github.com/vercel/next.js/issues/29559#issuecomment-938431883 where I'm keeping track of common cases that apps take longer to compile.

**Closed by timneutkens** 2021-11-17 14:32 UTC
Labels: kind: story

**Comment by balazsorban44** [comment] 2022-01-27 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
