### ISSUE TITLE
[NEXT-437] AppDir: Link to Route with Head requires two clicks 

### ISSUE THREAD

**Issue by cachho** [vercel/next.js#43972] opened 2022-12-12 17:53 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.7-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Head component/file (next/head / head.js), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://codesandbox.io/s/app-dir-press-twice-r7rep3?file=/app/page.tsx

### To Reproduce

Create an app folder route that contains a head.tsx file.
I provided 3 routes in the sandbox.

1. no head
2. with head
3. head but without fetch in head

### Describe the Bug

Link components have to be clicked twice if the target route contains a head file.  It does not matter if the head file contains a fetch or not. This can be reproduced.

I know the whole head  topic is WIP, I found another crucial bug that I couldn't reproduce in the sandbox yet:
In my project I have a fetch in a head.tsx file. When I try to open that route it gets stuck on the loading screen. When I refresh or access via direct URL it loads instantly. The fetch in head takes takes >1 sec, maybe that has something to do with it.  

### Expected Behavior

Open the link with a single click.

<sub>[NEXT-437](https://linear.app/vercel/issue/NEXT-437/appdir-link-to-route-with-head-requires-two-clicks)</sub>

**Comment by ekafyi** [comment] 2022-12-13 07:24
I have no time to make a repro yet, but experiencing this part:

> I know the whole head topic is WIP, I found another crucial bug that I couldn't reproduce in the sandbox yet:
In my project I have a **fetch in a head.tsx file**. When I try to open that route it **gets stuck on the loading screen**. When I refresh or access via direct URL it loads instantly.

In addition to refreshing/accessing via direct URL, anything that **triggers re-render** of that segment layout will replace the "stuck" loading UI with the correct content. (example if using the sample app: adding `ClickCounter` https://github.com/vercel/app-playground/blob/main/ui/ClickCounter.tsx to the layout and clicking it while stuck in loading UI)

Other details:
- Only occurs when not cached, ie. `x-vercel-cache: MISS` in header.
- I'm using Prisma, not regular `fetch`, if that matters.

**Comment by mzavattaro** [comment] 2022-12-13 23:03
> I have no time to make a repro yet, but experiencing this part:
> 
> > I know the whole head topic is WIP, I found another crucial bug that I couldn't reproduce in the sandbox yet:
> > In my project I have a **fetch in a head.tsx file**. When I try to open that route it **gets stuck on the loading screen**. When I refresh or access via direct URL it loads instantly.
> 
> Other than refreshing/accessing via direct URL, anything that **triggers re-render** of that segment layout will get the loading UI "unstuck" and render the correct content. (Example if using the demo app: Add `ClickCounter` https://github.com/vercel/app-playground/blob/main/ui/ClickCounter.tsx to the layout; click it while stuck in loading UI)
> 
> Other details:
> 
> * Only occurs when not cached, ie. `x-vercel-cache: MISS` in header.
> * I'm using Prisma, not regular `fetch`, if that matters.

I'm having this stuck on Loading UI issue. My steps to reproduce are:
1. From dashboard click on Next Link that navigates me to another page.
2. Click the back button in the browser - This redirects me back to the previous page, but the Loading UI is stuck.

I would have thought the back button would cause Next to trigger a re-render? How would you work around this?

**Comment by lucasmerlin** [comment] 2022-12-14 21:18
I'm also experiencing the issue where a page is stuck on the loading spinner until refresh. My _really really ugly_ workaround for now is this: 

```tsx
'use client';

import {useEffect} from 'react';
import {usePathname, useRouter} from 'next/navigation';

export default function FixLoading() {
  const path = usePathname();
  const router = useRouter();

  useEffect(() => {
    const timeouts = [100, 500, 1000, 2000, 3000, 5000, 10000].map(t => setTimeout(() => router.replace(path), t));
    return () => {
      timeouts.forEach(t => clearTimeout(t));
    };
  }, [path]);

  return <></>;
}
```
The different timeouts are so if the page has not been prefetched yet it will rerender once it's loaded. Of course this will lead to unnecessary rerenders and if a page takes > 10s to load it won't help at all.
I also tried to use a useState to cause a rerender but that didn't help.


When I include this component in my root layout.tsx the pages load as expected (although with a delay).

**Comment by mzavattaro** [comment] 2022-12-15 00:35
@lucasmerlin That definitely works haha. I do like a good filthy work around.

**Comment by brvnonascimento** [comment] 2022-12-15 11:05
I'm experiencing this too and is only happening on Vercel/production as well

**Comment by christo9090** [comment] 2022-12-23 17:31
I am experiencing the same thing. If a route has its own head.js file, then you get stuck on the loading.js file until you click again. This is on Next 13.1. This didnt happen on Next 13.02, but in that version, the head didnt actually change on routes.

**Comment by qpavy** [comment] 2023-01-04 16:51
I have the same issue with `13.1.1` and `13.1.2-canary.0`: 
- If I use head.tsx without fetch inside I have no issue
- If I use head.tsx with fetch inside I get stuck on loading page until I click again

**Comment by samuelcotterall** [comment] 2023-01-04 19:14
I encountered a similar problem, albeit without the Head file.

This occurred intermittently, and in production mode only (`13.1.2-canary.0`). Development mode was fine. 

It seemed to be caused by my routing setup (below), where I suspect the router was unable to differentiate between the dynamic `[teamId]` route and the static `create-team` page. 

`/app/[teamId]/page.tsx`
`/app/create-team/page.tsx`

Moving the dynamic route to `/team/[teamId]/page.tsx` resolved the problem for me. 

I’m not sure whether this is expected behaviour as I expected the router to check for `create-team` first, and fall through to the dynamic route.

**Comment by qpavy** [comment] 2023-01-04 19:51
I had the same routing setup 
`/app/[pageslug]/app.tsx` and `/app/destinations/page.tsx` 
I change it with `/app/page/[pageslug]` but I still have the problem

**Comment by christo9090** [comment] 2023-01-08 18:03
> I have the same issue with `13.1.1` and `13.1.2-canary.0`:
> 
> * If I use head.tsx without fetch inside I have no issue
> * If I use head.tsx with fetch inside I get stuck on loading page until I click again

After more testing, this is the exact issue I am experiencing as well. `13.1.1`. Calling data in the head to create meta data causes a hang up on the loading page.

**Comment by larsgaardsoe** [comment] 2023-01-18 07:14
I have the same issue, without a fetch in Head, but with me default tags includes in Head. When I click a `<Link />` to the path the Browser console give me a `Uncaught TypeError: Cannot read properties of null (reading 'type') at releaseResource (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:12173:20)`

I'm on `13.1.1`

**Comment by timneutkens** [comment] 2023-02-01 08:35
Going to close this issue in favor of #45106 (they're the same). Moved over the reproduction from this issue to #45106 and updated it to the latest version.

**Closed by timneutkens** 2023-02-01 08:35 UTC
Labels: kind: bug, linear
