### ISSUE TITLE
Parsing error: Cannot find module 'next/babel'

### ISSUE THREAD

**Issue by JoseGarciaM** [vercel/next.js#26127] opened 2021-06-15 16:48 UTC
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

14.0.0

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

every file underlines imports and aslant gives me this message: Parsing error: Cannot find module 'next/babel'

### Expected Behavior

nextjs 10 didn't show this message

### To Reproduce

just import something into any file in nextjs 11

**Comment by BenjaminWFox** [comment] 2021-06-15 22:00
As a temporary workaround, you can:
`npm i -D @babel/eslint-plugin`

and in `.eslintrc` add:
```
{
  "extends": "next",
  "plugins": [
    "@babel"
  ]
}
```

**Comment by cromosom** [comment] 2021-06-16 08:25
I have the same issue

**Comment by timneutkens** [comment] 2021-06-16 11:53
This can't be investigated as no reproduction was provided. Please provide it.

**Comment by BenjaminWFox** [comment] 2021-06-16 13:49
This appears to be (for me at least) a bug related to Visual Studio where the Next.js project is a sub-project of another project and the parent project has a node_modules folder where Next is not installed. Here are steps to reproduce:

## Repro

```
# In console:

➜  Personal mkcdir next-babel-repro
➜  next-babel-repro npm init
➜  next-babel-repro npx create-next-app my-next-app
➜  next-babel-repro cd my-next-app
➜  my-next-app git:(main) npx next lint

# In Visual Studio
- Open the `next-babel-repro` folder
- Open the `index.js` file from `my-next-app`
```

The error should now be visible.

## VSCode Info:

Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:22:31.215Z (6 days ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.1.0

## Repro Repo:

https://github.com/BenjaminWFox/next11-babel-repro

## Fixes/Workarounds

Open the Next.js project directly in VSCode
~ or ~
Install `next` in the parent project

**Comment by rochdev** [comment] 2021-06-16 13:53
For us it happens even in CircleCI as well with just the hello world example from Next documentation, so I don't think it's related to VSCode. I will provide a reproduction a bit later.

**Comment by rochdev** [comment] 2021-06-16 19:41
It looks like when you're using a copy of Next that lives outside of your app it results in the above error in Next 11.0.0 if you don't have all the devDependencies installed in your own `node_modules`. I'm playing around with `NODE_PATH` and it looks like I'm on my way to make this work, but it would be awesome if there is a way the old behaviour could be restored where the the library would use its own copy.

Our use case: we test compatibility of Datadog APM with every version of the libraries we support, so we install every version externally and then load them in multiple runs of the same test, so there is no local `node_modules` since there is an external one for each version. You can see what this looks like [here](https://github.com/DataDog/dd-trace-js/blob/bff8fc8751412f6b062d5802d51258c255f778ad/packages/datadog-plugin-next/test/index.spec.js#L36-L43).

**Comment by rochdev** [comment] 2021-06-16 20:19
Switching to Webpack 4 with `webpack5: false` in `next.config.js` also seems to resolve the issue, at least for us, although this will not be an option for Next 12.

**Comment by cromosom** [comment] 2021-06-17 09:05
@rochdev interesting find. We are using next in a monorepo setup. So this could actually be the reason

**Comment by lgh06** [comment] 2021-06-20 03:28
happens on lerna + create-next-app (next 11.0.0) + Node 14 + VSCode 1.57 + macOS 10.14.5

**Comment by housseindjirdeh** [comment] 2021-07-15 17:53
Reproduced this issue quite quickly. Thanks for the detailed repro steps @BenjaminWFox.

For folks running into this problem in VSCode, The vscode/eslint extension runs a server on the same directory opened and it isn't resolving dependencies for instances where the Next.js is within a subfolder. There are a few workarounds mentioned above (open the Next.js folder directly in VSCode or install `next` in the parent directory), but you can also set your working directory in your [workspace settings](https://code.visualstudio.com/docs/getstarted/settings). If you have a folder structure that looks like:

```
- parent-folder
  - next-app
  - ...
```

And you've opened `parent-folder` in VSCode, add the following to your workspace settings (JSON):

```json
{
  "eslint.workingDirectories": [
    "next-app"
  ]
}
```

That should resolve the issue!

**Comment by housseindjirdeh** [comment] 2021-07-15 18:28
@rochdev Hmm, interesting to hear that switching to webpack 4 via `webpack5: false` solved the issue for you although that wouldn't necessarily apply to folks running into this problem in VSCode. Have you tried modifying `working_directory` within your CircleCI config to point to the folder with `node_modules`? I _think_ that should solve the problem but chances are you may have tried that already 😅 

> I'm playing around with NODE_PATH and it looks like I'm on my way to make this work

I've seen [multiple](https://github.com/microsoft/vscode-eslint/issues/696#issuecomment-559275985) [instances](https://github.com/vuejs/eslint-plugin-vue/issues/976#issuecomment-659954130) of people doing the same and it working for them. Let me know if that ends up being the solution.

**Comment by housseindjirdeh** [comment] 2021-07-15 18:28
I'll close this since this is an issue specific to how tooling (VSCode, CircleCI) is resolving linting dependencies in a monorepo or Next.js-within-a-subfolder setup and directly a result of something configured wrongly within Next.js. Happy to re-open if there's something specific we could/should be fixing however!

**Closed by housseindjirdeh** 2021-07-15 18:28 UTC
Labels: kind: bug

**Comment by rochdev** [comment] 2021-07-16 19:32
> Have you tried modifying working_directory within your CircleCI config to point to the folder with node_modules?

Unfortunately it's not really an option for us since it's actually a Mocha test, so unrelated to CircleCI since Next is installed in a separate directory from the test files. It fails both locally and in CircleCI. I will admit that our use case is a bit uncommon (testing our library with multiple versions of Next), but it definitely sounds like there are many use cases and tools where this could be problematic.

> I'll close this since this is an issue specific to how tooling (VSCode, CircleCI) is resolving linting dependencies in a monorepo or Next.js-within-a-subfolder setup and directly a result of something configured wrongly within Next.js.

While it's not necessarily an issue with Next per-se, the fact that it's not working properly for so many people indicates to me that Next should still handle this properly, because even if the limitation is documented, it's likely that more people will hit the issue and not everyone will find the workaround, or it may not apply for their use case (like for us).

**Comment by balazsorban44** [comment] 2022-01-28 02:16
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
