### ISSUE TITLE
sass import inside component fails with "SassError: Can't find stylesheet to import"

### ISSUE THREAD

**Issue by thisdarktao** [vercel/next.js#28325] opened 2021-08-20 10:44 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

16.3.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

After following [the instructions](https://nextjs.org/docs/basic-features/built-in-css-support#customizing-sass-options) on including the root `styles` directory for sass imports, the config option doesn't seem to work.

### Expected Behavior

I expect the `variables.scss` file to be imported correctly, using either `prependData` or importing it directly in `Button.module.scss`.

### To Reproduce

The project's `next.config.js` contains:

```js
const path = require('path');

module.exports = {
  reactStrictMode: true,
  sassOptions: {
    includePaths: [path.join(__dirname, 'styles')]
  },
};
```

I have a component in `./src/components/button`, which imports `Button.module.scss`:

```js
import styles from "./Button.module.scss";
```

Running the project locally using `npm run dev` results in:

```
./src/components/button/Button.module.scss
SassError: Can't find stylesheet to import.
  ╷
1 │ @import "variables.scss";
  │         ^^^^^^^^^^^^^^^^
  ╵
  src/components/button/Button.module.scss 1:9  root stylesheet
```

At first I wasn't sure the `sassOptions` config was being picked up, so I added the `prependData` option and removed the import from inside `Button.module.scss`:

```js
prependData: '@import "variables.scss";'
```

This resulted in:

```
./src/components/button/Button.module.scss
SassError: Can't find stylesheet to import.
  ╷
1 │ @import "variables.scss";
  │         ^^^^^^^^^^^^^^^^^^
  ╵
  src/components/button/Button.module.scss 1:9  root stylesheet
```

With no further instructions to go on, I'm not sure what I can try to resolve the issue.

**Comment by thisdarktao** [comment] 2021-08-20 16:24
Managed to get this working after moving the contents of the `./styles` directory to `./src/styles` and changed the `includePath` to `[path.join(__dirname, 'src/styles')]`.

No idea why that resolved the issue but assuming it must be something unique to my setup. Happy to close if there's no further investigation required?

**Comment by timneutkens** [comment] 2021-08-21 14:07
Likely something in your configuration indeed, feel free to close the issue 👍

**Closed** 2021-08-21 19:10 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 22:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
