### ISSUE TITLE
useSearchParams is including the path param

### ISSUE THREAD

**Issue by hywook4** [vercel/next.js#51802] opened 2023-06-26 02:49 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.20.0
      npm: 8.19.4
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.8-canary.2
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
    Next.js Config:
      output: standalone
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

It's simple to reproduce so I'll leave the way below

### To Reproduce

use useSearchParams() hook when current url is using path param.

### Describe the Bug

useSearchParams() is described to be used to get "query string" from the URL
(https://nextjs.org/docs/app/api-reference/functions/use-search-params)

But, it's including "path param".

### Expected Behavior

useSearchParams() should only return "query string", not including "path param"

**Comment by balazsorban44** [comment] 2023-06-26 17:56
> It's simple to reproduce so I'll leave the way below

Please never assume this. Adding a reproduction of any sort helps us help you resolving any issues much more efficiently. 🙏

**Comment by themagickoala** [comment] 2023-06-28 10:34
Reproduction steps for this:
1. Create a page with a dynamic route in the pages dir (e.g. /[dynamic]);
2. In the page, log out `useSearchParams().toString()`;
3. Navigate to your dynamic route with (or without) a query string parameter (e.g. /test?a=b);
4. See the page params logged (e.g. '?dynamic=test&a=b`).

**Comment by mxswat** [comment] 2023-06-28 10:42
Since a code sandbox was not provided, I made one: https://codesandbox.io/p/sandbox/brave-kepler-w96myn?file=%2Fpages%2F%5BgameName%5D%2Findex.tsx%3A10%2C11

* Open the code sandbox
* Click on "Click me for the bug"
* It will lead you to `/GAMENAME/?queryParam1=queryParam1Value` where the value of `searchParams.toString()` is printed
* The printed value will be `Search Params is: queryParam1=queryParam1Value&gameName=GAMENAME`
* `gameName=GAMENAME` Should NOT be present

**Closed** 2024-02-27 21:28 UTC
Labels: please add a complete reproduction, template: bug, area: Routing, type: needs triage, resolved
