### ISSUE TITLE
[Large bug] Yarn workspaces is broken with NextJS.

### ISSUE THREAD

**Issue by SaavanNanavati** [vercel/next.js#52224] opened 2023-07-05 00:12 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020
    Binaries:
      Node: 20.0.0
      npm: 9.6.4
      Yarn: 1.22.19
      pnpm: 8.6.6
    Relevant Packages:
      next: 13.4.8
      eslint-config-next: 13.4.8
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Package manager (npm, pnpm, Yarn), SWC transpilation, TypeScript (plugin, built-in types)

### Link to the code that reproduces this issue or a replay of the bug

https://gitlab.com/FrozenFury/yarn-workspaces-nextjs

### To Reproduce

I have built a sample repository for reproducing this bug - clone it and run the following commands:
1. Run `cd packages/root`.
2. Run `yarn dev`.

You will get this error:
```
../common/Header.tsx
Module parse failed: Unexpected token (4:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| export const Header = () => {
>   return <div>Header</div>;
| };
|
```

It is the `"use client"` line inside `Toggle.tsx` which is causing the issue. If you remove it and the Toggle component entirely, this code runs fine.

Both repositories were created using ```npx create-next-app@latest```.

### Describe the Bug

Any file inside of a Yarn workspace that uses the `"use client"` directive causes an error.

### Expected Behavior

This should compile properly. Please assist on how to fix.

**Comment by joulev** [comment] 2023-07-05 03:31
Try [transpiling](https://nextjs.org/docs/app/api-reference/next-config-js/transpilePackages) your `@extravagant-spaces/common` package.

**Comment by kdy1** [comment] 2024-01-31 03:31
Closing as this is not a bug but rather a wrong configuration. You need to configure `transpilePackages` when you are using monorepo.

**Closed by kdy1** 2024-01-31 03:31 UTC
Labels: template: bug, area: SWC transforms, area: TypeScript
