### ISSUE TITLE
Route params outside of SSG

### ISSUE THREAD

**Issue by herrstucki** [vercel/next.js#10981] opened 2020-03-11 16:19 UTC
# Feature request

Hi! Great job on the SSG improvements!

I was wondering – since we now have `params` (in addition to `query`) available in `getStaticProps`, that it would be great to add those to other Router-related things as well. 

## Describe the solution you'd like

For example:

```js
const { params } = useRouter();
// and
<Link href="/blog/[slug]" params={{ slug: "welcome" }}>...</Link>
// and
exportPathMap: () => ({ "/blog/welcome": { page: "/blog/[slug]", params: { slug: "welcome" } })
// ...
```

**Comment by Timer** [comment] 2020-03-11 16:35
All of this will likely be handled as part of #8207.

**Comment by Timer** [comment] 2020-09-10 18:12
Closing in favor of above.

**Closed by Timer** 2020-09-10 18:12 UTC

**Comment by balazsorban44** [comment] 2022-01-29 13:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
