### ISSUE TITLE
Update some packages for Node 14 support

### ISSUE THREAD

**Issue by jewkub** [vercel/next.js#13596] opened 2020-05-30 20:02 UTC
# Bug report

## Describe the bug

I use Node v14.3 and `yarn create` got a lot of warnings. Logs below

yarn add v1.22.4
info No lockfile found.
[1/4] Resolving packages...
warning next > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning next > mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning next > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning next > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning next > resolve-url-loader > rework > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning next > chokidar > braces > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning next > chokidar > braces > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

## To Reproduce

`yarn create next-app`

## Expected behavior

Actually, there are no error right now but I am aware of those bunch of warnings

## Screenshots

^Logs above

## System information

- OS: Windows 10
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: create-next-app@9.4.4
- Version of Node.js: 14.3.0

**Comment by timneutkens** [comment] 2020-05-30 20:08
Duplicate of #12857

**Closed by timneutkens** 2020-05-30 20:08 UTC

**Comment by jewkub** [comment] 2020-05-30 20:10
Oh I dont see that issue before, sorry.

**Comment by balazsorban44** [comment] 2022-01-30 02:14
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
