### ISSUE TITLE
Plans to add esbuild?

### ISSUE THREAD

**Issue by karanpratapsingh** [vercel/next.js#27412] opened 2021-07-22 17:27 UTC
### Describe the feature you'd like to request

Hi, is there any plans to use `esbuild-loader` as default?

### Describe the solution you'd like

adding `esbuild-loader` to default webpack config

### Describe alternatives you've considered

not as such

**Comment by ijjk** [comment] 2021-07-22 17:32
Closing as a duplicate of https://github.com/vercel/next.js/discussions/16152

**Closed by ijjk** 2021-07-22 17:32 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-28 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
