### ISSUE TITLE
Importing client components in MDX fails in dev mode

### ISSUE THREAD

**Issue by pomber** [vercel/next.js#56153] opened 2023-09-28 11:35 UTC
### Link to the code that reproduces this issue

https://github.com/pomber/nextjs-mdx-use-client-bug

### To Reproduce

1. Start the app with `next dev` (it only happens in development mode)

### Current vs. Expected behavior

Fails with this error:

```
Unhandled Runtime Error
Error: Cannot access Test.propTypes on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.

Call Stack
Object.get
/workspace/nextjs-mdx-use-client-bug/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (22:23981)
React
_createMdxContent
webpack-internal:///(rsc)/./app/hello.mdx (25:74)
MDXContent
webpack-internal:///(rsc)/./app/hello.mdx (45:16)
ej
/workspace/nextjs-mdx-use-client-bug/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (22:35053)
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
$ npx --no-install next info

Operating System:
  Platform: linux
  Arch: x64
  Version: #202309200834 SMP PREEMPT_DYNAMIC Wed Sep 20 09:14:42 UTC 2023
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.7.6
Relevant Packages:
  next: 13.5.4-canary.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, MDX (@next/mdx)

### Additional context

I'm having problems using any client component directly from mdx files:

```mdx
import { Test } from "./test";

# Hello

<Test />
```

If `./test.js` has `"use client"` this fails in dev mode. 

A workaround is to re-export the `Test` component from a file without `"use client"`.

The same example works with `next@13.4.19` and fails with `next@13.5.1`.

Similar to #52415 but now in v13.5 it happens for every client component.

<sub>[NEXT-1666](https://linear.app/vercel/issue/NEXT-1666/importing-client-components-in-mdx-fails-in-dev-mode)</sub>

**Comment by balazsorban44** [comment] 2023-09-29 12:39
Seems like a regression in https://github.com/vercel/next.js/compare/v13.4.20-canary.31...v13.4.20-canary.32

I think this is related to https://github.com/vercel/next.js/pull/55362, we will have a look!

**Comment by mnlfischer** [comment] 2023-10-04 19:18
I run into that issue using custom components in the useMDXComponents hook.

```jsx
import * as mdxComponents from '@/components/mdx'
import { type MDXComponents } from 'mdx/types'

export function useMDXComponents(components: MDXComponents) {
  return {
    ...components,
    ...mdxComponents,
  }
}
```

If I declare custom components inside the file it works.

**Comment by ealexhaywood** [comment] 2023-10-16 21:31
This is happening in v13.5.5 for me too for any client component in MDX.  Downgrading to 13.4 fixes it

**Comment by MananTank** [comment] 2023-10-19 09:25
I'm also facing the same issue. Downgrading to 13.4 fixed it

**Comment by ealexhaywood** [comment] 2023-10-25 15:06
This _may_ be fixed in the latest canary release of 13.5.7.  So far so good!

**Comment by pomber** [comment] 2023-11-03 18:15
Just tried `v14.0.1` and looks like it is fixed.

**Comment by GrowthWizard** [comment] 2023-11-03 20:05
Sadly still run into the same problem, even after the v14.0.1 next.js Update :-/

![Uploading Bildschirmfoto 2023-11-03 um 20.03.40.png…]()

**Comment by azdanov** [comment] 2023-11-04 05:49
I'm using this custom component instead of `Image` in mdx files. Hacky, but works.

```tsx
import Image, { ImageProps } from "next/image";

export function MdxImage(props: ImageProps) {
  return <Image {...props} />;
}
```

**Comment by victorteokw** [comment] 2024-02-05 15:36
This bug still exists in 14.1

**Comment by hbmuller** [comment] 2024-03-19 21:24
I can still reproduce it on the latest version of next.

**Comment by bilal-baig-dev** [comment] 2024-06-23 14:03
> This _may_ be fixed in the latest canary release of 13.5.7. So far so good!
> 
> I'm also using the experimental rust compiler in my next config
> 
> ```js
> const nextConfig = {
>   experimental: {
>     mdxRs: true
>   }
> }
> ```
> 
> Edit: things also seem to work well on the default compiler

Hey @ealexhaywood, I was using next js v14.1.4 with app router and configured MDX as per the documentation but was getting error while importing MDX file in a component - after adding `mdxRs:true` it worked. Thanks for sharing

**Comment by devjiwonchoi** [comment] 2024-08-04 16:04
@pomber Hi, the latest canary works as expected, but needs a few changes on your current repro.
Opened a [PR for the fix](https://github.com/pomber/nextjs-mdx-use-client-bug/pull/1) to your repro branch, please take a look if you find interested!

The main changes:
1. Use `hello/page.mdx` instead of `hello.mdx` just like the migration from Pages Router to App Router.
2. Configure `pageExtensions` at the next config. It is also [documented here](https://nextjs.org/docs/app/building-your-application/configuring/mdx#getting-started).

Please check out the MDX docs as it had several updates!
Doc: https://nextjs.org/docs/app/building-your-application/configuring/mdx

**Comment by devjiwonchoi** [comment] 2024-08-09 17:37
@victorteokw @t6adev @GrowthWizard @MananTank @ealexhaywood 
Were you guys able to manage it to work?

**Comment by MananTank** [comment] 2024-08-12 23:37
@devjiwonchoi Update to latest version, The issue is fixed

**Closed** 2024-08-14 08:59 UTC
Labels: bug, linear: next, Markdown (MDX)
