### ISSUE TITLE
not found doesn't catch after dynamic param

### ISSUE THREAD

**Issue by darklight9811** [vercel/next.js#48763] opened 2023-04-24 05:53 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Mon Apr 24 2023 02:05:22 GMT-0300 (Horário Padrão de Brasília)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 8.2.0
    Relevant packages:
      next: 13.3.1-canary.19
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-pqwxgu?file=app/[locale]/not-found.tsx

### To Reproduce

Create a not-found file after a dynamic param `[locale] for example`, like this: `[locale]/not-found.tsx`, visit any route like `/en-US/yay`, it will show next default not found route.

### Describe the Bug

It shows next default not found route instead of the custom one created.

### Expected Behavior

To show the not found created by the not-found file.

**Comment by zartinn** [comment] 2023-04-24 06:37
I am also struggeling with this problem and created a discussion to see how others have solved the problem: https://github.com/vercel/next.js/discussions/48725

I think there is right now no real solution for it when you want to have a not-found page which is probably utilizing the language and based on that the layout that is shared in a [lang] folder.

**Comment by darklight9811** [comment] 2023-04-24 15:23
@zartinn I saved it as a component and I do both `not-found.tsx` and `[...notfound]/.page.tsx` as a fallback. I need both because the second one is not triggered when I call `notFound()`. But this is indeed a bug to be solved.

**Comment by zartinn** [comment] 2023-05-04 23:44
Newest 13.4.0 version does NOT fixed this. The PR https://github.com/vercel/next.js/pull/49095 sounded kind of promising.

**Comment by leonbe02** [comment] 2023-05-19 22:48
Kind of crazy that Next doesn't support localized 404 pages out of the box. Is there any ETA on a fix for this?

**Comment by zartinn** [comment] 2023-05-30 16:54
13.4.4 version did not fixed that.

**Comment by kyleatcolenso** [comment] 2023-06-14 23:34
We need this resolved asap too, `not-found.tsx` was working until we added a top level [lang] folder. Now we're getting the default Nextjs 404 page.

**Comment by Israeltheminer** [comment] 2023-07-03 09:05
Came across this same problem using the [locale] directory within the app directory. This should be tagged as important

**Comment by p00000001** [comment] 2023-07-06 14:06
A possible to workaround this if you don't have any dynamic routes directly below the [lang] is to add a catch-all route (will match only if static routes don't match):

`/[lang]/[...notFound]/page.js`

Then inside `page.js` have a method call:

`export default function NotFoundCatchAllPage() {
    notFound();
}`

This will then trigger the segment's `not-found.js` instead of the default root one.

**Comment by MuhammadMinhaj** [comment] 2023-07-08 21:48
Still not resolved?😒 Waiting for this fixing! I think it should be important, especially for i18n!

**Comment by MuhammadMinhaj** [comment] 2023-07-09 16:48
Regarding the custom metadata for the not-found.js page, maybe I've found a workaround! here you can go:
https://github.com/vercel/next.js/issues/45620#issuecomment-1627769331

**Comment by trickreich** [comment] 2023-08-01 13:52
<img width="244" alt="CleanShot 2023-08-01 at 15 49 28@2x" src="https://github.com/vercel/next.js/assets/16644200/96877fe8-0544-46af-b183-e69e9d75ab91">

this case isn't working.. 

@timneutkens @leerob we have this issue in production sites.. could we have a hint how we can solve this?
thanks!

**Comment by timneutkens** [comment] 2023-08-02 09:41
Looking at the reproduction it seems there's a misunderstanding about how/when `not-found.tsx` is triggered. The `not-found.tsx` boundaries currently only apply to calling `notFound()`. Only `app/not-found.tsx` is used to render the default 404 page (i.e. when you go to `/my-non-existent-page` or `/dashboard/my-non-existent-page`). 

Calling `notFound()` correctly triggers the not-found boundary in `app/[locale]/not-found.tsx`. The reproduction did not have any `notFound()` calls so I've added one here: https://stackblitz.com/edit/vercel-next-js-sbvl7a?file=app%2F[locale]%2Fpage.tsx and you can see it working when going to `/en`. It's currently expected that `/en/my-non-existent-page` does not match/render `app/[locale]/not-found.tsx`.

This is definitely something we're going to add support for in the future but it's working as expected currently. Would recommend opening a discussion feature request for this change so that we can keep track of interest in the feature.

**Closed by timneutkens** 2023-08-02 09:41 UTC
Labels: template: bug, area: app

**Comment by darklight9811** [comment] 2023-08-02 11:29
@timneutkens, discussion created for this: https://github.com/vercel/next.js/discussions/53486

**Comment by trickreich** [comment] 2023-08-08 06:46
@timneutkens Sorry, but it's still not working. I think the problem is now (next 13.4.13), when the layout is a async component. For me it looks like it's not awaited.

**Comment by timneutkens** [comment] 2023-08-09 07:45
@trickreich Feel free to open an issue and provide a reproduction. Please don't @ mention me with comments that are not actionable. Try reading your comment by itself, there is no context on what you're doing besides "I'm on the latest version and have a component".
