### ISSUE TITLE
generateStaticParams breaks <Suspense>

### ISSUE THREAD

**Issue by OtisTemler** [vercel/next.js#43350] opened 2022-11-24 20:12 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.6-canary.0
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

As described in the discussion: https://github.com/vercel/next.js/discussions/41745#discussioncomment-4196127 whenever I add `generateStaticParams` on either a `page.tsx` or `layout.tsx` `<Suspense>` stops working and NextJS will wait for the requests in any component to be finished before any content is displayed.

### Expected Behavior

generateStaticParams should not break the Suspense functionality

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://codesandbox.io/s/suspense-bug-c0w2xv?file=/app/page.tsx

### To Reproduce

I've added a codesandbox that reproduces the problem. If you want `<Suspense>` to work just comment out `generateStaticParams` in `page.tsx` and `<Suspense>` will magically work again and the fallback `<LoadingComponent />` will be displayed correctly.

**Comment by Jordaneisenburger** [comment] 2022-11-25 08:14
I'm also experiending this issue +1

**Comment by OtisTemler** [comment] 2023-01-11 18:37
Problem still there with latest canary (13.1.2-canary.4).

**Comment by mayankchhabra** [comment] 2023-02-14 09:39
Also experiencing this issue. @OtisTemler were you able to figure out a solution to make it work in the meantime?

**Comment by Jordaneisenburger** [comment] 2023-03-08 18:06
Issue still persists in v13.2.4-canary.6 which makes we wonder if this is really an issue or a complete misunderstanding from our side ?

**Comment by timneutkens** [comment] 2023-03-09 10:21
This is a misunderstanding indeed. The default is still static rendering until you opt-in to dynamic rendering through e.g. `cookies()`, `headers()`, or `export const dynamic = 'force-dynamic'`.

When static rendering the whole page is rendered to HTML and served from e.g. a CDN as a full page, this is what you're seeing when you add `generateStaticParams` where development mirrors production, the static HTML is streamed.

When dynamic rendering the page is streamed and suspense boundaries will trigger while waiting for data to load. With Next.js 13.2 we've added the Next.js Cache which allows you to use dynamic rendering with many of the benefits of static: https://nextjs.org/blog/next-13-2#nextjs-cache

**Comment by Jordaneisenburger** [comment] 2023-03-09 11:09
Hey Tim,

Thanks for the quick response! Managed to fix our "issue"

**Comment by timneutkens** [comment] 2023-04-09 17:09
Going to close this issue as it's not a bug 👍

**Closed by timneutkens** 2023-04-09 17:09 UTC
Labels: template: bug, area: app
