### ISSUE TITLE
App re-renders with query params

### ISSUE THREAD

**Issue by luciovilla** [vercel/next.js#17021] opened 2020-09-11 14:50 UTC
# Bug report

## Describe the bug

`_app.js` is getting rendered twice when adding a random query param to the URL. For example **http://localhost:3000/?asdfsf** which causes index.js to get rendered twice and components imported there rendered twice as well.

## To Reproduce

1. Create a new Next project with `npx create-next-app`
2. Add a console log to `_app.js` to print how many times its being rendered
3. Run `yarn dev` to start the server
4. Open http://localhost:3000/?asdfsf and you will see that the console.log is in there twice.

## Expected behavior

Expected to render once, just like in http://localhost:3000 without the url query params.

## System information

- OS: macOS
- Version of Next.js: 9.5.3
- Version of Node.js: 14.5.0

**Comment by HaNdTriX** [comment] 2020-09-11 16:35
Afaik this on propose. 

1. Render (caused by hydration of static app wich had no query params at compile time)
2. Render (caused by a query params state change)

If you want to get rid of this render you should check out the docs on static rendering especially the docs on [getStaticPaths](https://nextjs.org/docs/basic-features/data-fetching#getstaticpaths-static-generation).

**Comment by ijjk** [comment] 2020-09-11 18:06
Hi, as mentioned above this is the expected behavior and is to prevent hydration mismatching due to the query parameters being provided to early. For specific docs related to this behavior the automatic static optimization see here https://nextjs.org/docs/advanced-features/automatic-static-optimization#how-it-works

I'm going to close this since it's not an issue and the docs do mention this behavior already.

**Closed by ijjk** 2020-09-11 18:06 UTC

**Comment by balazsorban44** [comment] 2022-01-29 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
