### ISSUE TITLE
Dynamic routes with multiple variables per path segment

### ISSUE THREAD

**Issue by lucacasonato** [vercel/next.js#11647] opened 2020-04-03 23:32 UTC
# Feature request

It is currently not possible to create advanced dynamic routes which have multiple variables in a single path segment.

An example of such a route would be `unpkg.com/nextjs@v0.1.0`. This URL has variables in the first path segment: the package name and the package version. Currently the only way to handle cases like these in NextJS are to have a `pages/[identifier].js` file, and then manually split the identifier in the page component. Let's say you also have a page `unpkg.com/nextjs` which has different content to the first route. In this case you now have to deal with the extra case for `[identifier]` because you have a shared route for both, and you need and you might be shipping unnecessary code in a bundle because NextJS is not aware of the difference between these routes.

## Describe the solution you'd like

It would be great if you could just create a page like this: `pages/[package]@[version].js` and also `pages/[package].js`. Now NextJS will match these routes in the order of most specific to least specific, so `unpkg.com/nextjs@v0.1.0` would be matched by `pages/[package]@[version].js` and not `pages/[package].js`. The specificity would work similar to how specificity works for dynamic routes now. In the case of `unpkg.com/nextjs@v0.1.0` the params passed to the page would be `{"package": "nextjs", "version: "v0.1.0"}` 

## Describe alternatives you've considered

Manually doing routing in the page component, but this is bad for bundle size and also less nice for the developer. This is especially true if different multiple variables path segment paths have different subpages because then you manually have to do a lot of routing.

**Comment by overlookmotel** [comment] 2020-04-22 16:56
Hi @lucacasonato. Please see #12113 - a request for a related but distinct feature. Please let me know if you have any thoughts on how your use case and mine could both be fulfilled.

**Comment by Timer** [comment] 2020-09-10 19:12
Closing as this is better handled by Next.js' support for rewrites:
https://nextjs.org/docs/api-reference/next.config.js/rewrites

**Closed by Timer** 2020-09-10 19:12 UTC
Labels: type: feature request

**Comment by balazsorban44** [comment] 2022-01-29 13:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
