### ISSUE TITLE
Server actions no longer working when developing using local version of Next.js

### ISSUE THREAD

**Issue by viktorronnback** [vercel/next.js#57054] opened 2023-10-19 12:55 UTC
### Link to the code that reproduces this issue

https://github.com/viktorronnback/server-actions

### To Reproduce

1. Clone the reproduction repository provided above
2. Follow the steps in the [Developing Using Your Local Version of Next.js](https://github.com/vercel/next.js/blob/canary/contributing/core/developing-using-local-app.md#developing-using-your-local-version-of-nextjs) guide (either *Develop inside the monorepo* or *Set as a local dependency in package.json*)
3. Go to http://localhost:3000/
4. Press the `Action` button
5. Notice the terminal output

### Current vs. Expected behavior

A console log "Hello World!" should be printed in the terminal, instead `Failed to find Server Action "[server action id]". This request might be from an older or newer deployment.` is shown. Server actions work as usual on canary and release versions (when not using the local version of Next.js) so this is only an issue when using local version of Next.js.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2
Binaries:
  Node: 18.18.2
  npm: 10.2.0
  Yarn: N/A
  pnpm: 8.9.0
Relevant Packages:
  next: 13.5.6
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

Server actions stopped working after [v13.5.5-canary.3](https://github.com/vercel/next.js/releases/tag/v13.5.5-canary.3) (throws an error). After [v13.5.5-canary.5](https://github.com/vercel/next.js/releases/tag/v13.5.5-canary.5) `Failed to find Server Action "[server action id]". This request might be from an older or newer deployment.` is shown in the terminal (probably [#56618](https://github.com/vercel/next.js/pull/56618)).

This is a somewhat minor issue, but it is hard to diagnose issues related to server actions if this does not work (unless there is some workaround or other way of making server actions work when developing with a local version of Next.js).

**Comment by AlandSleman** [comment] 2023-10-20 02:28
I've cloned your repository and tested it with canary version 13.5.7-canary.11, and it worked as expected.

Could you please verify if the issue still exists in the latest version?  there might be a possibility that the issue is specific to your local environment.

**Comment by viktorronnback** [comment] 2023-10-20 08:56
Sorry my bad, it was my local version. It now works after I ran `pnpm clean`.

However I feel like there should be a mention of the need to run this command when switching versions/pulling down new changes in any of the contributing-guides. I can submit a PR with suggested additions to the docs.

**Comment by balazsorban44** [comment] 2023-10-20 20:01
closing as per the above

**Closed by balazsorban44** 2023-10-20 20:01 UTC
Labels: template: bug
