### ISSUE TITLE
Dev error overlay not working properly in Chrome when using custom `assetPrefix`

### ISSUE THREAD

**Issue by genetschneider** [vercel/next.js#29290] opened 2021-09-22 09:56 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

npm run dev

### Describe the Bug

Nextjs dev error overlay is not showing in Chrome browser when using an `assetPrefix` in `next.config.js`. In Safari and Firefox, the dev error overlay is working perfectly fine and shows the error with the stacktrace. In Chrome, if code runs into an error, the screen is blank. 

Dev error overlay in chrome
![chrome-blank](https://user-images.githubusercontent.com/19775351/134322859-09160c07-df93-483d-be1b-6b465586d9b2.png)

Dev error overlay in Safari (same code)
![safari-works](https://user-images.githubusercontent.com/19775351/134322890-03a5a69d-1a27-406b-9fcf-e3bb086268d8.png)

### Expected Behavior

Nextjs dev error overlay works in Chrome with a custom `assetPrefix`

### To Reproduce

Full reproduction repository can be found [here](https://github.com/genetschneider/nextjs-dev-overlay-bug-chrome). Made using custom-server-typescript example. 

- Have a simple mock cdn server running locally
- Point `assetPrefix` in nextjs app to hit that mock cdn server
- Proxy assets back to nextjs app from mock cdn server
- Simulate an error in nextjs app code (e.g in `getServerSideProps` first line)

**Comment by ijjk** [comment] 2021-09-23 03:24
Hi, it sounds like you are looking for the `basePath` config instead. The `assetPrefix` is meant to be used with serving static assets only. If you want to emulate this in your custom server and not use the `basePath` config you need to make sure `req.url` is updated to remove the `assetPrefix` before parsing the URL and calling Next.js request handler. This is not required with the `basePath` config as Next.js handles the prefix being present automatically.  

I'm gonna close this as this dosn't appear to be a bug and is the expected behavior with `assetPrefix`.

**Closed by ijjk** 2021-09-23 03:24 UTC
Labels: template: bug

**Comment by genetschneider** [comment] 2021-09-23 07:11
I think there's a little misunderstanding. I'm in fact looking for assetPrefix. In the example I have a local "mock cdn" server that acts as an asset cdn. In dev environment, we have a local cdn server provided and we want to use that, similar to how in the production environment the same cdn (dynamic cdn address) is used.
In the example, I'm still only serving static assets only. And still the question remains, why is the dev overlay shown in Firefox and Safari, **but not Chrome**?

**Comment by ijjk** [comment] 2021-09-23 14:16
If you want to use `assetPrefix` in this way the `req.url` needs to strip it away before passing it to the Next.js request handler as mentioned e.g. add `req.url = req.url!.replace(/^\/assets/, '')` above [this line](https://github.com/genetschneider/nextjs-dev-overlay-bug-chrome/blob/69affd2a855b85fa1cc42d03a46cd86a7346ae49/server/index.ts#L12). 

The above reproduction does not work in Firefox, Safari, or Chrome (possibly a config was changed between testing these). They all work as expected after adding the above mentioned handling.

**Comment by genetschneider** [comment] 2021-09-23 17:00
After adding the mention line `req.url = req.url!.replace(/^\/assets/, '')` above [this line](https://github.com/genetschneider/nextjs-dev-overlay-bug-chrome/blob/main/server/index.ts) the issue still can be reproduced (overlay shows in Firefox, not in Chrome). Please note that the asset path passed back to Next.js request handler is without the `/assets/` part as seen [here](https://github.com/genetschneider/nextjs-dev-overlay-bug-chrome/blob/main/asset-cdn.js#L7). You can also see this via console logs when you're running asset-cdn.js yourself

**Comment by ijjk** [comment] 2021-09-23 17:26
Why is app CDN needed along with the normal server in development? This is creating an extra hop slowing down static asset requests which are going to change a lot in development. The problem is from trying to re-route the requests in the `app-cdn` file since it isn't persisting connections and stuff as needed. Changing the `assetPrefix` to use the same port as [the server](https://github.com/genetschneider/nextjs-dev-overlay-bug-chrome/blob/main/server/index.ts) works fine in development.

**Comment by genetschneider** [comment] 2021-09-23 17:46
In our project the assetPrefix is dynamic (per region) since our nextjs app is deployed to multiple regions. We don't know the cdn url during build time so we need to have a workaround where the assetPrefix value is taken from the server side. Once the app starts, the cdn url is known and assetPrefix can be set using an env variable.
That being said, testing such workaround with a proper local cdn server is much safer as it will reveal any issues that there might be regarding that setup **(local env is very close to prod env in that regard).** So far everything has been working fine except we noticed the dev overlay doesn't work **in chrome only** for some odd reason. Since it's easily reproducible with that example repository, we were wondering why is it that in Chrome the dev overlay doesn't work in that case?

**Comment by ijjk** [comment] 2021-09-23 17:53
It looks like Chrome handles the HMR server-sent events connection differently than Firefox. To ensure these persistent connections are handled correctly using something like https://www.npmjs.com/package/http-proxy instead of axios should resolve this.

**Comment by genetschneider** [comment] 2021-09-24 07:52
Thanks for the suggestion! I updated my reproduce repository to use [http proxy and even enabled WS support](https://github.com/genetschneider/nextjs-dev-overlay-bug-chrome/blob/main/asset-cdn.js). I'm still experiencing the same issue however, overlay works in Firefox but not in Chrome. 
I started logging out the requests Next.js request handler receives on pageload and they are the following
**Chrome:**
```
Incoming request /_next/static/chunks/webpack.js?ts=1632469786885
Incoming request /_next/static/chunks/main.js?ts=1632469786885
Incoming request /_next/static/chunks/react-refresh.js?ts=1632469786885
Incoming request /_next/static/chunks/pages/_error.js?ts=1632469786885
Incoming request /_next/static/development/_buildManifest.js?ts=1632469786885
Incoming request /_next/static/development/_ssgManifest.js?ts=1632469786885
Incoming request /_next/static/chunks/pages/_app.js?ts=1632469786885
Incoming request /_next/static/chunks/node_modules_next_dist_client_dev_noop_js.js
Incoming request /_next/webpack-hmr?page=%2F
...stops here and no further requests
```

**Firefox:**
```
Incoming request /_next/static/chunks/webpack.js?ts=1632469808425
Incoming request /_next/static/chunks/pages/_app.js?ts=1632469808425
Incoming request /_next/static/chunks/pages/_error.js?ts=1632469808425
Incoming request /_next/static/chunks/main.js?ts=1632469808425
Incoming request /_next/static/development/_buildManifest.js?ts=1632469808425
Incoming request /_next/static/development/_ssgManifest.js?ts=1632469808425
Incoming request /_next/static/chunks/react-refresh.js?ts=1632469808425
Incoming request /_next/static/chunks/node_modules_next_dist_client_dev_noop_js.js
Incoming request /_next/webpack-hmr?page=%2F
Incoming request /__nextjs_original-stack-frame?isServerSide=true&file=webpack-internal%3A%2F%2F%2F.%2Fpages%2Findex.tsx&methodName=getServerSideProps&arguments=&lineNumber=29&column=9
Incoming request /__nextjs_original-stack-frame?isServerSide=true&file=file%3A%2F%2F%2FUsers%2Fgenetschneider%2Fgit%2Fcustom-server-typescript-nextjs%2Fnode_modules%2Fnext%2Fserver%2Frender.tsx&methodName=Object.renderToHTML&arguments=&lineNumber=733&column=22
```

[This](https://github.com/vercel/next.js/blob/canary/packages/react-dev-overlay/src/internal/helpers/stack-frame.ts#L59) request doesn't seem to be firing in case of Chrome. What should I try next?

**Comment by genetschneider** [comment] 2021-10-12 10:32
Solved by adding [`crossOrigin: 'anonymous'`](https://nextjs.org/docs/messages/doc-crossorigin-deprecated#possible-ways-to-fix-it) in `PHASE_DEVELOPMENT_SERVER` phase. 
This error happens due to [same-origin policy](https://stackoverflow.com/a/7778424). The error intercepted with the event listener reveals a `Script error.` as seen on the screensho
![Markup 2021-10-12 at 13 29 13](https://user-images.githubusercontent.com/19775351/136939991-a1aa72ac-0b09-4a5c-941f-8bdb9c6528db.png)

**Comment by balazsorban44** [comment] 2022-01-27 15:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
