### ISSUE TITLE
React's use() hook does not work

### ISSUE THREAD

**Issue by hosseinitabar** [vercel/next.js#46084] opened 2023-02-18 06:26 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Sat Feb 18 2023 09:54:41 GMT+0330 (Iran Standard Time)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.1.7-canary.19
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://stackblitz.com/edit/nextjs-hdvthr?file=next.config.js,package.json

### To Reproduce

- Create a default Next.js 13 application
- Enable app directory
- Enable `use client` inside the `page.js`
- Import `use` from `react`
- Use `use` to fetch data at client side
- You will see an error

### Describe the Bug

I am not able to load data at the client side when I choose to use `use()` hook and `use client` directive.

### Expected Behavior

It should work the way it's described in your docs and React's docs. 

Also there is not enough information and examples about it.

**Comment by Fredkiss3** [comment] 2023-02-18 15:23
the `use` hook is not stable yet to use in client components to fetch data. That's why the next team recommend to use it server components or use async components directly.

**Comment by hosseinitabar** [comment] 2023-02-22 11:12
@Fredkiss3 thank you for the explanation. So, what should I do to load data in my client component?

**Comment by Fredkiss3** [comment] 2023-02-22 11:17
You can fetch data in your server-component and pass it as props to your client component. 

Something like this : 
```jsx
// app/page.jsx
import { use } from 'react';
import { ProductCard } from './product-card';

const Index = () => {
  const product = use(
    fetch('https://dummyjson.com/products/1').then((res) => res.json())
  );

  return <ProductCard title={product.title} />;
};

export default Index;

// app/product-card.jsx
'use client';

export function ProductCard({title}) {
  return <div>{title}</div>
}
```

**Comment by timneutkens** [comment] 2023-02-28 12:04
Especially in the example the way @Fredkiss3 shared is much better than fetching client-side.

I'm going to close this issue as it's indeed not a bug but simply not implemented in React. `use()` can be used to unwrap promises (similar to `await`) already.

**Closed by timneutkens** 2023-02-28 12:04 UTC
Labels: template: bug
