### ISSUE TITLE
serverRuntimeConfig can no longer contain functions during build step

### ISSUE THREAD

**Issue by matt-way** [vercel/next.js#23855] opened 2021-04-09 13:42 UTC
### What version of Next.js are you using?

10.0.6

### What version of Node.js are you using?

12.18.2

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

When upgrading from 10.0.5 -> 10.0.6 you can no longer pass functions into `serverRuntimeConfig` for the build step (dev is fine).

We use serverRuntimeConfig (in next.config.js) as a way of initialising and accessing modules within pages for things like DB access and custom caching. For example:

```
const DB = require('our-db-lib')

DB.initialise(someKey)

module.exports = {
  poweredByHeader: false,
  serverRuntimeConfig: {
    DB,
  },
})

```

From 10.0.5 and back, this has been no problem, but from 10.0.6, we get this sort of error.

```
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  

> Build error occurred
DOMException [DataCloneError]: function (params) {
  ...<omitted>...
} could not be cloned.
    at Worker.postMessage (internal/worker.js:279:23)
```

It looks as though the config is now moved using postMessage, and so the objects needs to be serialisable, breaking our current setup. 

### Expected Behavior

Either that it just works as before, or that there is a nicer approach for this sort of pattern. I'm sorry if I've missed the more appropriate way to do this, but it seems many others have this issue.

### To Reproduce

Install 10.0.6 or later, and put a function into a serverRuntimeConfig key, and then run the build step.

**Comment by ijjk** [comment] 2021-04-17 22:24
Hi, `serverRuntimeConfig` is not meant to contain functions and this working previously was unintentional. we spread tasks among workers to speed up tasks and this config needs to be able to be passed between these workers and as such needs to be serializable. 

The pattern we recommend for sharing a function like this is to create a shared lib file which can be seen in this example https://github.com/vercel/next.js/blob/2e7d405fedbc9c07135ece14c6f7f2ac18a81a2a/examples/with-mysql/lib/db.ts

I'm going to close this since it doesn't appear to be a bug and is currently the expected behavior.

**Closed by ijjk** 2021-04-17 22:24 UTC
Labels: template: bug

**Comment by matt-way** [comment] 2021-04-21 06:27
I originally used the pattern above, but had lots of issues (like bundling problems). If anyone comes to this thread, I fixed it by simply changing the object by looking for the BUILD_PHASE vs server.

**Comment by balazsorban44** [comment] 2022-01-28 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
