### ISSUE TITLE
NextJS installation size is extremely big

### ISSUE THREAD

**Issue by abriginets** [vercel/next.js#32252] opened 2021-12-07 18:46 UTC
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

14.18.2

### What browser are you using?

-

### What operating system are you using?

WSL 2

### How are you deploying your application?

Heroku

### Describe the Bug

I was trying to deploy my NextJS app to Heroku and I mentioned that my slug size is too big even in compressed state. I downloaded the slug and it appears that NextJS takes the most space:
![image](https://user-images.githubusercontent.com/17240507/145087492-95c07296-0186-499d-9755-2ba5097c22f4.png)

Mostly because swc binaries are bundled for all possible operating systems and archs. @ijjk does that makes sense to determine OS and processor arch in `preinstall` phase and download only required binaries?
![image](https://user-images.githubusercontent.com/17240507/145087752-1889c8e6-5b11-4a24-a80b-4db2686d7a95.png)

### Expected Behavior

NextJS should determine which OS and processor arch developer is using and download only what's required in `preinstall` phase. Or maybe do not install anything at all if Babel config is detected in the repo.

### To Reproduce

-

**Comment by balazsorban44** [comment] 2021-12-07 23:35
Duplicate of #32183

**Closed by balazsorban44** 2021-12-07 23:35 UTC
Labels: template: bug

**Comment by carlosbaraza** [comment] 2021-12-08 11:52
Workaround: https://github.com/vercel/next.js/issues/32183#issuecomment-988742663

**Comment by balazsorban44** [comment] 2022-01-27 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
