### ISSUE TITLE
Can't provide multiple meta tags with the same name

### ISSUE THREAD

**Issue by rchandu** [vercel/next.js#10183] opened 2020-01-21 12:13 UTC
# Bug report

## Describe the bug
Ability to support multiple meta tags with same name. I see that there was an effort to support multiple meta tags with same property in https://github.com/zeit/next.js/pull/5800 but this still doesn't allow multiple meta tags with same name. 
This is useful to supporting _"citation_author"_  for SEO indexing in Google Scholar https://scholar.google.com/intl/en-us/scholar/inclusion.html#indexing

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Provide multiple meta tags with the same name in <Head>
2. Check the output

## Expected behavior

`<meta name="citation_author" content="Rannels, Stephen R.">
<meta name="citation_author" content="Falconieri, Mary">`

should give markup as such but, currently it produces

`<meta name="citation_author" content="Falconieri, Mary">`

## System information

- Version of Next.js: 9.1.6

**Comment by velvetkevorkian** [comment] 2020-02-27 15:52
It looks like this used to work. We're using Swiftype meta tags to let our site be crawled but upgrading from `9.1.4` to `9.1.5` has broken (changed?) this behaviour.

```
const categories = ['foo', 'bar']
<Head>
  { categories.map(category => (
    <meta name="category" content={category} key={category} />
  ))}
</Head>
```

In `9.1.4`, you get
```
<meta name="category" content="foo"></meta>
<meta name="category" content="bar"></meta>
```

In 9.1.5 +, you get 
```
<meta name="category" content="bar"></meta>
```

Is this use case supposed to be supported? I'm not 100% clear whether this is a regression or not. Based on #9315 it looks like it should be supported.

**Comment by rchandu** [comment] 2020-03-21 14:57
Apologies for my delayed response. It should work because lot of scholar based tags are used as such.

Examples:  
https://appliedcr.biomedcentral.com/articles/10.1186/s41241-020-00085-y
```
    <meta name="citation_reference" content="citation_journal_title=Oral Oncol; citation_title=Predictive factors of occult metastasis and prognosis of clinical stages I and II squamous cell carcinoma of the tongue and floor of the mouth; citation_author=TM Pimenta Amaral, AR Silva Freire, AL Carvalho, CA Pinto, LP Kowalski; citation_volume=40; citation_issue=8; citation_publication_date=2004; citation_pages=780-786; citation_doi=10.1016/j.oraloncology.2003.10.009; citation_id=CR2"/>
    <meta name="citation_reference" content="citation_journal_title=Oral Oncol; citation_title=Increase in head and neck cancer in younger patients due to human papillomavirus (HPV); citation_author=D Young, CC Xiao, B Murphy, M Moore, C Fakhry, TA Day; citation_volume=51; citation_issue=8; citation_publication_date=2015; citation_pages=727-730; citation_doi=10.1016/j.oraloncology.2015.03.015; citation_id=CR3"/>
    <meta name="citation_reference" content="citation_journal_title=Int J Exp Pathol; citation_title=Molecular predictors of clinical outcome in patients with head and neck squamous cell carcinoma; citation_author=GR Thomas, H Nadiminti, J Regalado; citation_volume=86; citation_issue=6; citation_publication_date=2005; citation_pages=347-363; citation_doi=10.1111/j.0959-9673.2005.00447.x; citation_id=CR4"/>
```

https://link.springer.com/article/10.1007/s10528-020-09951-4
https://www.academia.edu/42258245/AtCDC5_regulates_the_G2_to_M_transition_of_the_cell_cycle_and_is_critical_for_the_function_of_Arabidopsis_shoot_apical_meristem

**Comment by justin-schroeder** [comment] 2020-05-26 14:57
Same issue, we're also struggling to get multi-value meta tags indexed by Swiftype which uses this exact mechanism. The next/head code makes it clear why this is happening:

https://github.com/zeit/next.js/blob/86160a5190c50ea315c7ba91d77dfb51c42bc65f/packages/next/next-server/lib/head.tsx#L50-L103

I think this is actually the correct default behavior since duplicate meta tags is a real pain that is solved here. I would suggest that if unique `key` props are provided we should be able to override this behavior and output multiple tags with the same `METATYPES`.

**Comment by melisabok** [comment] 2020-08-18 19:56
Is there a workaround for this? 

We are facing the same issue in OpenReview: https://openreview.net/forum?id=HygBZnRctX

Google Scholar is using these meta tags to read the paper metadata.

**Comment by zbialecki** [comment] 2020-08-18 21:04
I have created a minimal test case for this issue: https://github.com/zbialecki/next-meta-tag-issue

I verified that it is still present in Next.js v9.5.3-canary.9, both in dev and production mode.

> I would suggest that if unique `key` props are provided we should be able to override this behavior and output multiple tags with the same `METATYPES`.

I agree with @justin-schroeder that this should be the default behavior.

**Comment by kilburn** [comment] 2020-11-18 18:05
Since the attached PR has not been merged for now, I've found a work-around.

The basic idea is:
1. Declare your meta tags using `data-name` instead of `name`. Example:
  ```jsx
  <meta data-name="citation_author" value="whatever" />
  ```
2. Use a customized `Head` component in `_document.js` that transforms the `data-name` to `name` for these tags when rendering the `html` file. Here's my `_dcument.js`:
  ```jsx
  import Document, { Head, Main } from 'next/document';
  import React from 'react';

  class CustomHead extends Head {
    render() {
      const res = super.render();

      function transform(node) {
        /**
         * Hack to allow multiple meta tags with the same name.
         *
         * This is a hack that transforms meta tags specified as:
         *   <meta data-name="something" ... />
         * to
         *   <meta name="something" ... />
         *
         * This is to avoid next's Head component from removing all
         * instances but one of these tags (needed for citation_author tags).
         *
         * See https://github.com/vercel/next.js/issues/10183
         */
        if (node && node.type === 'meta' && node.props['data-name']) {
          node.props.name = node.props['data-name'];
          delete node.props['data-name'];
        }

        // This ensures that we recurse into child components/arrays
        // in case our metas are nested in fragments/arrays
        if (node && node.props && node.props.children) {
          return {
            ...node,
            props: {
              ...node.props,
              children: Array.isArray(node.props.children)
                ? node.props.children.map(transform)
                : transform(node.props.children),
            },
          };
        }
        if (Array.isArray(node)) {
          return node.map(transform);
        }

        return node;
      }

      return transform(res);
    }
  }

  class FixedDocument extends Document {
    render() {
      return (
        <html lang="en">
          <CustomHead />
          <body>
            <Main className="container" />
          </body>
        </html>
      );
    }
  }

  export default process.env.NODE_ENV === 'production' ? FixedDocument : Document;
```

**Closed** 2021-01-03 10:35 UTC
Labels: kind: story, type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-28 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
