### ISSUE TITLE
not-found.tsx does not work with edge runtime

### ISSUE THREAD

**Issue by 8bit-echo** [vercel/next.js#52648] opened 2023-07-13 14:33 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.3.1
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: 8.6.3
    Relevant Packages:
      next: 13.4.10-canary.6
      eslint-config-next: 13.4.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Middleware / Edge (API routes, runtime), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/8bit-echo/next-minimal-repro

### To Reproduce

1. Define `export const runtime = 'edge';` in layout.tsx
2. create `not-found.tsx`
3. start server
4. visit a page that should 404 (`/foobar`)

### Describe the Bug

The Edge runtime throws an error when using a custom 404 page (or error.tsx, global-error.tsx) when visiting a page that should return 404. 

Stack Trace:

```
ReferenceError: self is not defined
    at Object.<anonymous> (vercel-minimal-repro/.next/server/app/not-found.js:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Module._load (node:internal/modules/cjs/loader:962:12)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)
    at requirePage (vercel-minimal-repro/node_modules/.pnpm/next@13.4.10-canary.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js:112:75)
    at vercel-minimal-repro/node_modules/.pnpm/next@13.4.10-canary.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js:80:84
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadComponentsImpl (vercel-minimal-repro/node_modules/.pnpm/next@13.4.10-canary.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js:80:26)
    at async DevServer.findPageComponentsImpl (vercel-minimal-repro/node_modules/.pnpm/next@13.4.10-canary.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:772:36)
```

Minimal Reproduction Repo: https://github.com/8bit-echo/next-minimal-repro
Deployment: https://next-minimal-repro.vercel.app/

### Expected Behavior

Server should display custom 404, or error pages.

**Comment by JesseKoldewijn** [comment] 2023-07-14 11:29
Hey man, could you maybe check if this issue still shows up when running the latest canary release?

**Comment by ctkc** [comment] 2023-07-14 17:24
I'm getting a similar error during the productive build with the latest `13.4.10` version. Rolling back to `13.4.9` solves the issue

```
#24 146.8 Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
#24 146.8 TypeError: Cannot read properties of undefined (reading 'v2')
#24 146.8     at /bigspring/packages/app/.next/server/chunks/8887.js:1424:50
#24 146.8     at /bigspring/packages/app/.next/server/chunks/5003.js:50798:18
#24 146.8     at handleInterpolation (/bigspring/packages/app/.next/server/chunks/5003.js:16830:24)
#24 146.8     at serializeStyles (/bigspring/packages/app/.next/server/chunks/5003.js:16934:15)
#24 146.8     at /bigspring/packages/app/.next/server/chunks/5003.js:17148:72
#24 146.8     at /bigspring/packages/app/.next/server/chunks/5003.js:15933:12
#24 146.8     at Ue (/bigspring/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:113:273)
#24 146.8     at Z (/bigspring/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:120:91)
#24 146.8     at Ue (/bigspring/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:114:9)
#24 146.8     at Z (/bigspring/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:120:91)
```

`v2` is coming from `theme` in a component styled with `emotion`

**Comment by martinmiglio** [comment] 2023-07-14 17:30
> could you maybe check if this issue still shows up when running the latest canary release?

Using 13.4.10, the issue still seems to be present

**Comment by 0zuna** [comment] 2023-07-14 17:36
not-found.js not working on output: "export"
Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot destructure property 'user' of '(0 , react__WEBPACK_IMPORTED_MODULE_1__.useContext)(...)' as it is undefined.
    at Nav (/home/dimitri/kangoru/kangoru-shop/kangoru-shop-web/.next/server/chunks/9487.js:252:13)
    at Ue (/home/dimitri/kangoru/kangoru-shop/kangoru-shop-web/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:113:273)
    at Ue (/home/dimitri/kangoru/kangoru-shop/kangoru-shop-web/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:119:11)
    at Z (/home/dimitri/kangoru/kangoru-shop/kangoru-shop-web/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:120:91)
    at Ve (/home/dimitri/kangoru/kangoru-shop/kangoru-shop-web/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:123:155)
    at Xe (/home/dimitri/kangoru/kangoru-shop/kangoru-shop-web/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:122:289)
    at Z (/home/dimitri/kangoru/kangoru-shop/kangoru-shop-web/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:120:350)
    at Ve (/home/dimitri/kangoru/kangoru-shop/kangoru-shop-web/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:123:155)
    at Ue (/home/dimitri/kangoru/kangoru-shop/kangoru-shop-web/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:114:215)
    at Z (/home/dimitri/kangoru/kangoru-shop/kangoru-shop-web/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:120:91)
- info Generating static pages (29/29)

> Export encountered errors on following paths:
	/_not-found


this bug is in 13.4.10 i return to 13.4.9

**Comment by IgorBadanyuk** [comment] 2023-07-17 06:51
I also encountered this problem without using edge. It seems that an error occurs when using client components that require context.  The error is not present in 13.4.9

**Comment by ijjk** [comment] 2023-07-19 17:19
Hi, this should now be resolved in the latest version of Next.js `v13.4.11-canary.0`, please update and give it a try!

Related fixes: 

https://github.com/vercel/next.js/issues/52648
https://github.com/vercel/vercel/pull/10223

**Closed by ijjk** 2023-07-19 17:19 UTC
Labels: template: bug, area: Routing, area: Edge

**Comment by francofantini** [comment] 2023-07-22 03:23
Hi there, i'm seeing a lot of 504 errors in my prod logs from path that should result in 404s.
I'm currently using next v13.4.12.

<img width="1065" alt="image" src="https://github.com/vercel/next.js/assets/11973156/07e4eb18-6264-4daa-9ade-6cc38912c84e">


To Reproduce
1. Define export const runtime = 'edge'; in layout.tsx
1. create not-found.tsx
1. `npm run build && npm start`
1. visit a page that should 404 (/foobar)
1. no response

Minimal Reproduction Repo: https://github.com/francofantini/next-test-not-found

**Comment by azvyae** [comment] 2023-08-05 14:02
Can confirm this, when accessing /notfound page it will take forever to load

**Comment by francofantini** [comment] 2023-08-07 01:06
@ijjk Could you re-open this issue?

**Comment by azvyae** [comment] 2023-08-07 03:51
Just rementioned this issue on #53652 which has more impact involving 3rd party deployment that needs edge runtime @francofantini
