### ISSUE TITLE
Possible bug: 308 redirects for assets when using trailing slashes option

### ISSUE THREAD

**Issue by ianflorian** [vercel/next.js#14748] opened 2020-06-30 20:00 UTC
# Bug report

We are using a `pre-release` version to make use of #13333 for trailing slashes. The routes work fine with trailing slashes but we noticed that the server now redirects asset requests to include trailing slashes, too. We are not sure if we are doing something wrong or if this is a bug. In case it is a bug, we wanted to bring this to your attention so that it can be fixed before the `9.4.5` release.

## Expected behavior

The server does not redirect the requests, i.e. responds with status code `200` instead of `308`.

## Screenshots

![Screenshot 2020-06-30 at 21 39 13](https://user-images.githubusercontent.com/63334/86171483-13de4180-bb1d-11ea-8152-c00ea3054ccf.png)

## System information

- Version of Next.js: `9.4.5-canary.20`
- Version of Node.js: `14.0.5`

## Additional context

@Janpot for visibility.

**Comment by Janpot** [comment] 2020-06-30 21:07
there have been some fixes in the latest canary. Can you try to upgrade?

**Comment by timneutkens** [comment] 2020-07-01 07:48
Yep this was already fixed by @Janpot 👍

**Closed by timneutkens** 2020-07-01 07:48 UTC
Labels: kind: bug, priority: p0

**Comment by ianflorian** [comment] 2020-07-01 08:50
Thank you, can confirm that it was fixed in a later version and works now for us. :-)

**Comment by balazsorban44** [comment] 2022-01-29 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
