### ISSUE TITLE
HeadManager removes elements added by non-next scripts

### ISSUE THREAD

**Issue by jarib** [vercel/next.js#10692] opened 2020-02-25 17:46 UTC
# Bug report

## Describe the bug

After upgrading from Next 8 to Next 9, charts embedded from https://infogram.com/ stopped working for us.

My investigation shows that Infogram's loader adds a `<script>` element to `<head>` which is then removed by next's `HeadManager`. This causes the Infogram script to fail.

Infogram's embedding scripts expects the ability to:

1. Add a new `<script ... />` right _before_ the currently first `<script .../>` in the DOM.
2. Find this element (by id) at any point later.

## To Reproduce

1. Clone https://github.com/jarib/next-js-9-embed-bug
2. Run `npm install && npm run dev`
3. Visit http://localhost:3000 for a minimal example, check the console.
4. Visit http://localhost:3000/infogram for a full example (using Infogram), check the console.

## Expected behavior

The console should show "all ok" for step 3 and render an Infogram chart for step 4.
Instead, the added `script` element is removed. The script being loaded assumes that the `script` element that loaded it exists in the DOM, and when it cannot find it, it fails.

You can get the expected behaviour by removing the initial `script` element from `<Head>` in both examples, or by downgrading to Next 8 (and moving `public/` to `static/`).

## System information

- OS: macOs
- Browser (if applies): Chrome
- Version of Next.js: >= 9

## Additional context

Since the embed codes unfortunately are saved as HTML in our CMS, we use `createContextualFragment` to load it, including the `script` tag. This has served us well so far, including for client-side navigation, and covers our embed use cases outside of Infogram as well. It also worked perfectly in Next 8.

Possibly related to https://github.com/zeit/next.js/issues/9573

**Comment by Timer** [comment] 2020-09-03 02:25
Closing as duplicate of https://github.com/vercel/next.js/issues/9573

**Closed by Timer** 2020-09-03 02:25 UTC

**Comment by jarib** [comment] 2020-12-20 10:05
@Timer That issue is closed as fixed, but my [reprodcution repo](https://github.com/jarib/next-js-9-embed-bug) still fails using 10.0.4-canary.8.

**Comment by jarib** [comment] 2020-12-20 10:59
Bug does not reproduce on 9.5.4, 9.5.5, 10.0.0, 10.0.1
Bug _does_ reproduce on 9.5.2, 10.0.2, 10.0.4-canary.8

**Comment by jarib** [comment] 2021-01-29 10:31
Still fails on 10.0.5 and 10.0.6-canary.9. 

This bug completely breaks one of my sites and prevents me from upgrading.

@Timer Please consider reopening this.

**Comment by jarib** [comment] 2021-04-08 13:46
Still fails on 10.1.3

**Comment by balazsorban44** [comment] 2022-01-28 13:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
