### ISSUE TITLE
Tree shaking for `getStaticProps` not working

### ISSUE THREAD

**Issue by nicholaschiang** [vercel/next.js#27741] opened 2021-08-03 19:37 UTC
### What version of Next.js are you using?

10.1.2

### What version of Node.js are you using?

12.18.3

### What browser are you using?

Firefox

### What operating system are you using?

Ubuntu 20.04 LTS (Pop_OS! 20.04 LTS)

### How are you deploying your application?

Vercel

### Describe the Bug

Tree shaking for `getStaticProps` doesn't work properly when re-exporting reusable props functions:

```typescript
// lib/page.ts
import { GetStaticPathsResult } from 'next';

import { OrgJSON } from 'lib/model/org';
import { getOrgs } from 'lib/api/db/org';

export interface PageProps {
  orgs?: OrgJSON[];
}

export async function getPageProps(): Promise<{ props: PageProps }> {
  const orgs = (await getOrgs()).map((o) => o.toJSON());
  return { props: { orgs } };
}

export async function getPagePaths(): Promise<GetStaticPathsResult> {
  return { paths: [], fallback: true };
}
```
I then re-export those `getPageProps` and `getPagePaths` from that file in my pages:
```typescript
// pages/[org]/settings/index.tsx
import { getPagePaths, getPageProps } from 'lib/page';
...
export const getStaticProps = getPageProps;
export const getStaticPaths = getPagePaths;
```
And the `getPagePaths` and `getPageProps` aren't properly tree shaken. They still try to appear in the client-side bundle; I know this because my build fails with the error:
```
12:15:38.782 | Failed to compile.
12:15:38.783 | ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '/vercel/path0/node_modules/winston/dist/winston/transports'
12:15:38.783 | > Build error occurred
12:15:38.784 | Error: > Build failed because of webpack errors
12:15:38.784 | at /vercel/path0/node_modules/next/dist/build/index.js:17:924
12:15:38.784 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:5:584)
12:15:38.880 | Error: Command "yarn run build" exited with 1
```
That :point_up: error occurs because my API logger (Winston which uses `fs` which is only available in server-side environments) is being imported into `lib/api/db/org.ts` which is imported by `lib/page.ts` which is (incorrectly) not tree shaken by Next.js even though it is only used in `getStaticProps`.

### Expected Behavior

Next.js should tree shake imports that are re-exported as `getStaticProps` or `getStaticPaths` (and not include them in the client-side bundle).

### To Reproduce

See issue description.

**Comment by masx200** [comment] 2021-08-04 10:16
```ts
// pages/[org]/settings/index.tsx
import { getPagePaths, getPageProps } from 'lib/page';
//...
export {  getPageProps as getStaticProps};
export  {  getPagePaths as getStaticPaths};
```

**Comment by masx200** [comment] 2021-08-04 10:38
I also encountered a similar problem. I used the refactoring function of vscode to extract all the code that only runs on the server to a new file, and the problem was solved.

**Comment by masx200** [comment] 2021-08-04 10:39
I also encountered a similar problem. I used the refactoring function of vscode to extract all the code that only runs on the server to a new file, and the problem was solved.

**Comment by timneutkens** [comment] 2021-08-04 15:09
Can you share a full reproduction? You can check the tree shaking here: https://next-code-elimination.vercel.app/. Your example of:
```
import { getPagePaths, getPageProps } from 'lib/page';

export const getStaticProps = getPageProps;
export const getStaticPaths = getPagePaths;
```

Is correctly shaken from the page file, so it's likely something else.

A separate module can't contain both client-side JS and server-side JS as the tree shaking of `getStaticProps`, `getStaticPaths`, and `getServerSideProps` only runs on the page file itself, if you end up doing something like:

```
import { getPagePaths, getPageProps, SomeComponent } from 'lib/page';

export const getStaticProps = getPageProps;
export const getStaticPaths = getPagePaths;

export default function Home() {
  // Note that SomeComponent is imported from `lib/page` which imports server-only modules like `fs`
  return <SomeComponent />
}
```

It will not work because the tree shaking only removes the `getPagePaths` and `getPageProps` import and does not actually change `lib/page`.

**Comment by glantucan** [comment] 2021-09-15 08:52
> Can you share a full reproduction? You can check the tree shaking here: https://next-code-elimination.vercel.app/. Your example of:
> 
> ```
> import { getPagePaths, getPageProps } from 'lib/page';
> 
> export const getStaticProps = getPageProps;
> export const getStaticPaths = getPagePaths;
> ```
> 
> Is correctly shaken from the page file, so it's likely something else.
> 
> A separate module can't contain both client-side JS and server-side JS as the tree shaking of `getStaticProps`, `getStaticPaths`, and `getServerSideProps` only runs on the page file itself, if you end up doing something like:
> 
> ```
> import { getPagePaths, getPageProps, SomeComponent } from 'lib/page';
> 
> export const getStaticProps = getPageProps;
> export const getStaticPaths = getPagePaths;
> 
> export default function Home() {
>   // Note that SomeComponent is imported from `lib/page` which imports server-only modules like `fs`
>   return <SomeComponent />
> }
> ```
> 
> It will not work because the tree shaking only removes the `getPagePaths` and `getPageProps` import and does not actually change `lib/page`.

Is that stated somewhere in the Next docs, because I looked for it and didn't find it. I have some somewhat complex logic that has to be run on the `getStaticProps` and `getStatcPaths` of several pages and I abstracted it and encapsulated it in several external modules that I import on my pages and invoke from those functions as needed, Those imported modules use `fs` and some database connectors.

I get a similar error on build.

Is there a nicer, DRY way to do that than copying all that logic on each `getStaticProps` or `getStatcPaths`?

**Comment by timneutkens** [comment] 2021-11-17 15:48
@glantucan you can import external files, you just have to make sure the files with server code are not also exporting client-side code.

Going to close this issue as my previous comment got a 👍

**Closed by timneutkens** 2021-11-17 15:48 UTC
Labels: please add a complete reproduction, template: bug

**Comment by denis-sokolov** [comment] 2021-11-23 07:09
This seems to possibly be a duplicate of #16153.

**Comment by balazsorban44** [comment] 2022-01-27 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
