### ISSUE TITLE
Web workers doesn't work in production build with webpack 5

### ISSUE THREAD

**Issue by Cyral** [vercel/next.js#24624] opened 2021-04-29 21:40 UTC
### What version of Next.js are you using?

10.2

### What version of Node.js are you using?

14.16

### What browser are you using?

N/A

### What operating system are you using?

N/A

### How are you deploying your application?

next build && next start

### Describe the Bug

When creating a build, the webworker file is referenced as 217.undefined.js which 404's, preventing the web worker script from loading. Note that the script (with the correct numbers) is outputted to /chunks/

### Expected Behavior

Script name is referenced properly

### To Reproduce

yarn create next-app --example with-web-worker with-web-worker-app
cd next-app
yarn build
yarn start

Open devtools and see how web worker fails to load
`Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:3000/_next/static/chunks/217.undefined.js`

**Comment by ijjk** [comment] 2021-04-30 00:51
Duplicate of https://github.com/vercel/next.js/issues/22813

**Closed by ijjk** 2021-04-30 00:51 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
