### ISSUE TITLE
Page styles are unloaded before unmount on page transition

### ISSUE THREAD

**Issue by mrgnou** [vercel/next.js#18586] opened 2020-10-31 13:51 UTC
# Bug report

## Describe the bug

When we delay current page unmounting in a page transition context, I noticed that the current page style chunks are unloaded right after route change, which causes page jump. 

This issue exists since since v9.5.3 and happens on production build, I'm stuck on v9.5.2.

## Expected behavior

Pages should unload their styles only when they are fully unmounted, therefore preventing any style jump on route update.

## Screenshots

Screencast available [here](https://www.dropbox.com/s/rsdpfdvzmile6rn/Screen%20Recording%202020-10-31%20at%2014.35.42.mp4?dl=0).

## System information

- OS: macos
- Browser: Chrome 86
- Version of Next.js: 10.0.0
- Version of Node.js: 12.19

**Comment by clieee** [comment] 2020-10-31 22:29
How are you doing this ”prevent to unmount”?

**Comment by awareness481** [comment] 2020-11-01 06:23
Relevant issue https://github.com/vercel/next.js/issues/17464

**Comment by Mike-Koech** [comment] 2020-11-01 06:55
> How are you doing this ”prevent to unmount”?

#prevent to unmount#fixissue"*/

**Comment by Timer** [comment] 2020-11-01 16:17
Duplicate of https://github.com/vercel/next.js/issues/17464

**Closed by Timer** 2020-11-01 16:17 UTC

**Comment by balazsorban44** [comment] 2022-01-29 07:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
