### ISSUE TITLE
Could not resolve dependency: peer react@"^16.11.0" from swr@0.1.18 (next.js/examples/api-routes-rest/package.json)

### ISSUE THREAD

**Issue by hiro345g** [vercel/next.js#30934] opened 2021-11-04 05:04 UTC
### What example does this report relate to?

api-routes-rest

### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

14.17.3

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying your application?

npx create-next-app -e api-routes-rest api-routes-rest

### Describe the Bug

Trying to install api-routes-rest, but I get dependency errors.

```
$ npx create-next-app -e api-routes-rest api-routes-rest
(snip)
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.11.0" from swr@0.1.18
npm ERR! node_modules/swr
npm ERR!   swr@"^0.1.18" from the root project
npm ERR! 
(snip)
```

### Expected Behavior

Trying to install api-routes-rest, but I get dependency errors.

```
$ npx create-next-app -e api-routes-rest api-routes-rest
(snip)
Success! Created api-routes-rest at
(snip)
```

### To Reproduce

Modifying api-routes-rest / package.json to fix this issue

```
{
  "private": true,
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "latest",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "swr": "^1.0.1"
  }
}
```

**Comment by balazsorban44** [comment] 2021-12-24 00:06
I could not reproduce this, probably fixed in a later iteration.

**Closed by balazsorban44** 2021-12-24 00:06 UTC
Labels: area: examples, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 01:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
