### ISSUE TITLE
Segmentation error when using on latest node js on m1 with Image component

### ISSUE THREAD

**Issue by vipanpreet** [vercel/next.js#26382] opened 2021-06-20 11:19 UTC
### What version of Next.js are you using?

11.0

### What version of Node.js are you using?

16.3.0

### What browser are you using?

chrome,safari

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

As, i have installed node js version 16.3.0 which supports apple silicon, but next js is not working and producing **segmentation error** when **next/image** component is being loaded and exiting. i have tried all node js versions supports apple silicon, older versions however with intel architecture is working ok.

### Expected Behavior

it should work with next/image component on m1 chips

### To Reproduce

Just done npm run dev / build & start gives same issue.

**Comment by timneutkens** [comment] 2021-06-21 09:37
Duplicate of #24421

**Closed by timneutkens** 2021-06-21 09:37 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
