### ISSUE TITLE
next lint should fail with code !=0 when eslint is not installed

### ISSUE THREAD

**Issue by mercuriete** [vercel/next.js#31605] opened 2021-11-19 11:39 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

LTS

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying your application?

eks

### Describe the Bug

When you have on devDependencies an incompatible version of eslint,
next lint fails with the following message

```
$ next lint
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
error - ESLint must be installed: yarn add --dev eslint
Done in 1.06s.
```
and exits with code 0.

When this is combined with continuous integration and a bot that updates dependencies like "renovatebot"

you could end up with breaking the project inadvertedly

### Expected Behavior

next lint should exit with code different to 0

### To Reproduce

have a nextjs proyect working

1- yarn add --dev eslint ^7.0.0
2- yarn next lint
3- check that lint works
4- update eslint to 8.X.X
5- yarn next lint
6- check that lint fails with code 0 and should fail with code != 0

**Comment by housseindjirdeh** [comment] 2021-12-29 16:38
Thanks for logging this @mercuriete!

> next lint should exit with code different to 0

The current behavior of erroring when an incompatible version of eslint is installed is expected in my opinion. Is the expectation here that `next lint` should never exit with code 0 or only do so when actual lint errors are present?

> When this is combined with continuous integration and a bot that updates dependencies like "renovatebot" you could end up with breaking the project inadvertedly

Just trying to clarify here, but wouldn't `next build --no-lint` be a better option for you to run during CI if you wouldn't want linting to break builds?

**Comment by mercuriete** [comment] 2021-12-29 19:51
The expectation is code 0 means success and any other number is error.

that is how github actions works and another CICD systems to know if a step failed or not.

So summarizing:
1. next lint should exit with code 0 if eslint is installed and there are no error in linting.
2. next lint should exit with code != 0 when eslint is installed and there are errors in linting
3. next lint should exit with code != 0 if eslint is not installed or any other error.

Sorry about my english I am not a native english speaker.

Thanks for your amazing project.

**Comment by samcx** [comment] 2024-02-22 05:12
Hi @mercuriete!

Unfortunately, we cannot exit with a `process.exit(1)` since we need to let the process continue after a failed lint, otherwise it will behave unexpectedly (failing our tests).

![CleanShot 2024-02-21 at 21 10 10@2x](https://github.com/vercel/next.js/assets/28912696/c07c6683-7f07-4d37-9d80-0a2e6fe99ca7)

Since this is the expected behavior, we will be closing this issue!

**Closed** 2024-02-28 01:06 UTC
Labels: kind: bug, area: ESLint
