### ISSUE TITLE
css.resolve error in react17

### ISSUE THREAD

**Issue by gtolarc** [vercel/next.js#18624] opened 2020-10-27 08:58 UTC
The following error seems to occur when using the css.resolve function from react17. Does anyone have the same issue?
![스크린샷 2020-10-27 오후 5 58 59](https://user-images.githubusercontent.com/8623798/97279263-20319b80-187e-11eb-9988-b4134fcbf211.png)

**Comment by iprignano** [comment] 2020-11-03 10:29
Same issue as https://github.com/vercel/next.js/issues/18134

**Comment by Timer** [comment] 2020-11-12 06:08
Duplicate of #18134

**Closed by Timer** 2020-11-12 06:08 UTC
Labels: kind: bug

**Comment by balazsorban44** [comment] 2022-01-29 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
