### ISSUE TITLE
next/image in non-next environments

### ISSUE THREAD

**Issue by saiichihashimoto** [vercel/next.js#22987] opened 2021-03-11 18:35 UTC
### Describe the feature you'd like to request

When next/image is used in non nextjs environments, it should function like a normal img. Our team uses storybook which renders next/image useless, since all of the images point to a `/_next/image` that can't exist.

### Describe the solution you'd like

When next/image is used in non nextjs environments, it should function like a normal img

### Describe alternatives you've considered

We simply can't use next/image, so our "alternative" is to just use img. I don't want to write our own wrapper around next/image to detect the environment and swap it out for an img.

**Comment by dohomi** [comment] 2021-03-12 00:31
@saiichihashimoto this is a duplicate of https://github.com/vercel/next.js/issues/18393. There is a solution provided here which works pretty alright for the moment: issue: https://github.com/vercel/next.js/issues/18393#issuecomment-783269086

**Closed** 2021-03-12 08:21 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-28 15:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
