### ISSUE TITLE
Web worker initialization is throwing 404 error

### ISSUE THREAD

**Issue by rishimohan** [vercel/next.js#26144] opened 2021-06-15 19:11 UTC
### What version of Next.js are you using?

11

### What version of Node.js are you using?

12.18.3

### What browser are you using?

Safari

### What operating system are you using?

macOS Monterey

### How are you deploying your application?

Netlify

### Describe the Bug

I just upgraded to Next.js v11. On first load I got the following error: 

![2021-06-16 at 00 35](https://user-images.githubusercontent.com/14031295/122109250-c5fc3f80-ce3a-11eb-9095-2d980c7d96e5.png)

After some debugging I found out that it's happening at:

```
workerRef.current = new Worker(new URL("workers/loadFeed.js", import.meta.url));
```

The file is at `/workers/loadFeed.js`. 

My `next.config.js` configuration: 

```
module.exports = {
  target: "experimental-serverless-trace",
  webpack: (config, { isServer, webpack }) => {
    config.output.hotUpdateMainFilename =
      "static/webpack/[fullhash].[runtime].hot-update.json";
      config.optimization.splitChunks.chunks = "all";
      
      if (!isServer) {
        config.resolve.fallback.fs = false;
    }

    return config;
  },
};
```

It was working fine with last release version. Seems like issue with initialisation or something that's change in 11.

### Expected Behavior

The worker should be initialized instead of throwing 404 error.

### To Reproduce

1: `npx create-next-app`
2: create a simple web worker in root of folder `/worker.js`
3: Try to intiialize the web worker using: 

`workerRef.current = new Worker(new URL("worker.js", import.meta.url));`

**Comment by timneutkens** [comment] 2021-06-17 12:41
Duplicate of #26152

**Closed** 2021-06-17 12:41 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 06:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
