### ISSUE TITLE
Image component fails when using image data URI

### ISSUE THREAD

**Issue by jecassis** [vercel/next.js#18372] opened 2020-10-28 09:00 UTC
# Bug report

## Describe the bug

When passing an image data URI to the Next.js image component an error is thrown.

## To Reproduce

Pass data URI to the Next.js image component:

Example:

```javascript
import Image from 'next/image';
<Image src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=">
```

## Expected behavior

The simplest solution and expectation would be to pass the URI directly to the `img` tag without any modification or optimization.

## Screenshots

Not applicable but error reported on the debug overlay is:

```
Error: Invalid src prop (data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=) on `next/image`, hostname is not configured under images in your `next.config.js`
```

## System information

- OS: Windows
- Browser (if applies) Chrome, Firefox, Edge
- Version of Next.js: 10.0.0
- Version of Node.js: 12.9.0

## Additional context

None.

**Comment by AlexSapoznikov** [comment] 2020-10-28 11:54
1) Also can not load static image: https://github.com/vercel/next.js/discussions/18311
2) Image with empty src should probably not throw an error as well... `<Image src="" ...`

**Comment by fzembow** [comment] 2020-10-30 16:18
Assuming that this is a bug that will be fixed, a temporary workaround would be to disable the base64-inlining behavior of `next/image`, by setting [`inlineImageLimit`](https://github.com/twopluszero/next-images#inlineimagelimit) to `0` in your `next.config.js`

That way you don't have to replace all the `Image` with `img` throughout a codebase just to workaround this -- just remove the limit later.

**Comment by styfle** [comment] 2020-10-31 22:54
The workaround today is to add the [`unoptimized`](https://nextjs.org/docs/api-reference/next/image) property to indicate that this image should not be optimized.

We can probably detect when `src` is using the `data:` protocol to make this opt-out without additional attributes.

**Closed** 2020-11-04 21:14 UTC
Labels: kind: bug, point: 2

**Comment by diegoulloao** [comment] 2021-05-26 21:03
any solution for this?

**Comment by ndom91** [comment] 2021-06-27 01:49
Unfortunately enabled `unoptimized` doesn't do the trick atm (using `next@11.0.1-canary.4`).

**Comment by brnyza** [comment] 2021-08-19 20:45
> Unfortunately enabling `unoptimized` doesn't do the trick atm (using `next@11.0.1-canary.4`).

For me it worked writing like this on Next.js v11.0.1:
`<Image unoptimized src={`data:image/jpeg;base64,${imageBase64}`} alt="Landscape picture" width={300} height={300} />`

**Comment by balazsorban44** [comment] 2022-01-27 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
