### ISSUE TITLE
Headers already sent on dynamic routes fallback

### ISSUE THREAD

**Issue by BernardA** [vercel/next.js#14846] opened 2020-07-04 12:29 UTC
# Bug report
Throwing error below when attempting to serve  dynamic routes:

      Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:526:11)
    at DevServer.sendHTML (/Users/quiamo/Sites/quiamo-next/node_modules/next/dist/server/next-dev-server.js:23:5)
    at DevServer.render (/Users/quiamo/Sites/quiamo-next/node_modules/next/dist/next-server/server/next-server.js:49:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.fn (/Users/quiamo/Sites/quiamo-next/node_modules/next/dist/next-server/server/next-server.js:35:852)
    at async Router.execute (/Users/quiamo/Sites/quiamo-next/node_modules/next/dist/next-server/server/router.js:28:28)
    at async DevServer.run (/Users/quiamo/Sites/quiamo-next/node_modules/next/dist/next-server/server/next-server.js:44:494)
    at async DevServer.handleRequest (/Users/quiamo/Sites/quiamo-next/node_modules/next/dist/next-server/server/next-server.js:13:133) {
       code: 'ERR_HTTP_HEADERS_SENT'

## Describe the bug

It finally ends up in the 404 page if the URL is invalid ( have not tested with valid fallbacks as yet ), but throws the above error in terminal.

Also it does take an enormous amount to finally reach the 404 page and the behavior is inconsistent at times. It sometimes get stuck in the IS FALLBACK UI. 

IMPORTANT: note that the solution of redirecting to 404 in `componentDidMount` is far from ideal, but I could not find a better way to handle it.

Please see my comment on issue https://github.com/vercel/next.js/issues/11646

## To Reproduce

At `/src/pages/search/[city]/[rootCategory]/[parentCategory]/[category].js`

       class SearchCat extends React.Component {
               ....
                componentDidMount() {
                    const { ads, router, is404 } = this.props;
                    console.log('SEARCH CATEGORY MOUNT', this.props);
                    if (is404) {
                        router.push('/404');
                    } else if (router.isFallback) {
                        console.log('ROUTER IS FALLBACK');
                    } else {
                           this.updateState(ads, this.state.itemsPerPage);
                          this.setState({ currentAds: ads.edges });
                   }
              }
             .....
             render() {
                  console.log('SEARCH CATS RENDER', this.props);
                  const {
                      categories,
                      cities,
                      router,
                      isLoading,
                      is404,
                   } = this.props;
                   if (is404) {
                        return <h2>IS 404</h2>;
                   }
                   if (router.isFallback ) {
                        return <h2>IS FALLBACK</h2>;
                   }
                    return (
                     ... ads list
                    )
             }
       }

       export async function getStaticPaths() {
             let categories = await getCategories();
             let cities = await getCities();
             categories = categories.data.categories;
             cities = cities.data.collectionQueryAddresses;
             const paths = [];
             cities.forEach((city) => {
                  categories.forEach((cat) => {
                       if (cat.root && cat.root.title === cat.parent.title) {
                           paths.push({
                               params: {
                                  city: 'country',
                                  rootCategory: urlWriter(cat.root.title),
                                  parentCategory: urlWriter(cat.title),
                                  category: '0',
                             },
                         })
                         paths.push({
                             params: {
                                city: urlWriter(city.city),
                                rootCategory: urlWriter(cat.root.title),
                                 parentCategory: urlWriter(cat.title),
                                 category: '0',
                            },
                        });
                  }
                  if (cat.root && cat.root.title !== cat.parent.title) {
                        paths.push({
                           params: {
                              city: urlWriter(city.city),
                              rootCategory: urlWriter(cat.root.title),
                              parentCategory: urlWriter(cat.parent.title),
                             category: urlWriter(cat.title),
                          },
                       });
                   }
              });
           });

         return {
             paths,
             fallback: true,
          };
       }

        export async function getStaticProps({ params }) {
             console.log('GET STATIC PROPS params', params);
             let categories = await getCategories();
             let cities = await getCities();
             categories = categories.data.categories;
             cities = cities.data.collectionQueryAddresses;
             const { city, rootCategory, parentCategory, category } = params;

             // validate parameters, set 404 if fail
            let is404 = false;
            .... validation here.....
           console.log('is404', is404);
           let ads = [];
          if (!is404) { // only fetch data if URL is valid
              ... code to set variables here .....
                const data = await apiQl(queryQl, variables);
               ads = data.data.ads;
          }

          return {
               props: {
                  ads,
                 categories,
                 cities,
                 is404,
             },
          };
       }
Steps to reproduce the behavior, please provide code snippets or a repository:

## Expected behavior

Should handle without error and, hopefully, more gracefully. 

## System information

- OS: [e.g. macOS, Windows] macOS 
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: 9.4.4
- Version of Node.js: 12.16.0

**Comment by timneutkens** [comment] 2020-07-04 14:59
Duplicate of https://github.com/vercel/next.js/issues/14577

**Closed by timneutkens** 2020-07-04 14:59 UTC

**Comment by balazsorban44** [comment] 2022-01-29 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
