### ISSUE TITLE
New app directory crashes on Range requests if `next/navigation` or `next/headers` is used

### ISSUE THREAD

**Issue by smaeda-ks** [vercel/next.js#42611] opened 2022-11-08 03:00 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

- 13.0.2, 13.0.3-canary.1
- Deployed on Vercel

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

The new app directory (Next.js 13) returns `INTERNAL_SERVER_ERROR` 500 error when using `useSearchParams` from `next/navigation` AND if a `Range` request header is sent.

**UPDATE:**
Looks like using [`next/headers`](https://beta.nextjs.org/docs/api-reference/headers) also triggers the same error. which let me think [`staticGenerationBailout`](https://github.com/vercel/next.js/blob/canary/packages/next/client/components/static-generation-bailout.ts) is somewhat related (it’s referenced by next/navigation or next/headers).

This is causing an issue with some crawlers such as Facebook Crawler as they send a `Range` request header:
https://developers.facebook.com/docs/sharing/webmasters/crawler/

### Expected Behavior

Should not return 500. The response should be either 200/206/416:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests#partial_request_responses

### Link to reproduction

- https://next13-plane-500-test-2.vercel.app/
- https://app-dir.vercel.app/

### To Reproduce

```bash
curl -svo /dev/null 'https://next13-plane-500-test-2.vercel.app/' -H 'range: bytes=0-1'
```

```bash
curl -svo /dev/null 'https://app-dir.vercel.app/' -H 'range: bytes=0-1'
```

\* https://github.com/vercel/app-playground/blob/main/ui/AddressBar.tsx#L4-L8

Create a new app with `npx create-next-app@latest --experimental-app` and make the following changes:

```diff
diff --git a/app/page.tsx b/app/page.tsx
index 35bd264..2a1b72d 100644
--- a/app/page.tsx
+++ b/app/page.tsx
@@ -1,7 +1,9 @@
 import Image from 'next/image'
 import styles from './page.module.css'
+import { headers } from 'next/headers';

 export default function Home() {
+  const headersList = headers();
   return (
     <div className={styles.container}>
       <main className={styles.main}>
```

Can't reproduce locally (`$ vercel dev`).

**Comment by cly** [comment] 2022-11-09 02:05
Thanks for looking into this!

**Comment by Commita-inf** [comment] 2023-01-27 20:10
I am facing the same issue using Next": "^13.0.8-canary.0, Facebook sharing debugger keeps giving "Response Code 500" for my Vercel deployed website: https://commita-inf.vercel.app
Neither the header component nor the body are  scraped properly (<html>
<head><meta http-equiv="content-type" content="text/html; charset=utf-8"></head>
<body><p>A server error has occurred
INTERNAL_SERVER_ERROR
</p></body>
</html>)
I need the debugger to give answer 200 in order to be able to use Facebook provider (next-auth)
any support would be appreciated. thank you

**Comment by vic9511** [comment] 2024-01-12 19:03
same thing, i just added  `import { headers } from 'next/headers';`  `const headersList = headers();` and the app crashed on vercel deployment (Can't reproduce locally)

**Comment by samcx** [comment] 2024-11-13 01:04
@smaeda-ks Getting a `206` when I test this now with stable v15.

(tested this path)

```
'use client'
 
import { useSearchParams } from 'next/navigation'
 
export default function SearchBar() {
  const searchParams = useSearchParams()
 
  const search = searchParams.get('search')
 
  // URL -> `/bruh?search=my-project`
  // `search` -> 'my-project'
  return <>Search: {search}</>
}
```

```
import { Suspense } from 'react'
import SearchBar from '@/components/search-bar'

export default function Home() {
  return (
    <main>
      <div>Hello world!</div>
      <Suspense fallback={<div>Loading...</div>}>
        <SearchBar />
      </Suspense>
    </main>
  );
}
```

Will be closing!

**Closed by samcx** 2024-11-13 01:04 UTC
Labels: bug, area: app
