### ISSUE TITLE
Add a way to set the status code in getServerSideProps

### ISSUE THREAD

**Issue by Jarred-Sumner** [vercel/next.js#11644] opened 2020-04-03 22:13 UTC
# Feature request

When the API call in `getServerSideProps` returns a `404` or null, I want the route to 404 in the website. I want to be able to manually tell `getServerSideProps` that an error has occurred and to render a specific status code.

I searched the docs, tried calling `res.status(404)` and it didn't work, so I'm filing this feature request

## Describe the solution you'd like

The 2nd solution probably fits best from an API design perspective with the rest of Next.js, but the first is probably what most JS developers would expect

###  Ideal solution

Inside `getServerSideProps`, if I call `res.status(404)`, the Network tab should show the current document's status is 404 and the Next.js would render `_error` or `next/error` instead of the page it was going to render.

This is ideal, for me at least, because this requires nothing new to learn. It's how I expected it to work before I filed this issue. However, this might not make as much sense in other cases (getStaticProps).

### Alternative solution

Add `statusCode` to the object we return in `getServerSideProps`.

For example:
```patch
export const getServerSideProps = async ({ query: { id: username }, res }) => {
  const profile = await fetchProfileByUsername(username);
  const profileId = profile?.id ?? null;

  return {
+   statusCode: profileId ? 200 : 404,
    props: {
      profile,
      profileId: profile?.id ?? null,
      username
    }
  };
};
```

When the status code is > 299, render the appropriate error page with the status code, but default it to `200`

### Another alternative solution

When you want to manually trigger a 404 error in Ruby on Rails, you raise `ActionController::RoutingError` inside your controller, for example: 
```ruby
raise ActionController::RoutingError.new('Not Found')
```

A Next.js version of that might look like this:
```tsx
import {NotFoundError} from 'next/error';

export const getServerSideProps = async ({ query: { id: username }, res }) => {
  const profile = await fetchProfileByUsername(username);
  const profileId = profile?.id ?? null;
  
   if (!profileId) {
     throw new NotFoundError();
   }

  return {
    props: {
      profile,
      profileId: profile?.id ?? null,
      username
    }
  };
};
```

This would naturally mean you could render the 404 page easily from non-page parts of your app, too.

My personal preference is I don't like throwing errors this way, so I put it at the end. But that's just my opinion

## Describe alternatives you've considered

I can do this right now, however the status code it returns is still 200 when it really should 404.

```tsx
import * as React from "react";
import { Page } from "../../src/components/Page";
import { fetchProfileByUsername } from "../../src/lib/api";
import NotFoundPage from "../404";

export const getServerSideProps = async ({ query: { id: username }, res }) => {
  const profile = await fetchProfileByUsername(username);

  return {
    props: {
      profile,
      profileId: profile?.id ?? null,
      username
    }
  };
};

export const ShowProfilePage = ({ profile, username, profileId }) => {
  if (!profile || !profileId) {
    return <NotFoundPage statusCode={404} />;
  }
  return (
    <Page header={<div className="Header-title">{username}</div>}>
      {...notRelevantToCodeSnippet}
    </Page>
  );
};

export default ShowProfilePage;
```

**Comment by claus** [comment] 2020-04-03 22:32
Doesn't `res` has a `statusCode` property that you can set?
```
export const getServerSideProps = async ({ res }) => {
  res.statusCode = 404
  return {
    error: 'oops'
  };
};
```

**Comment by Jarred-Sumner** [comment] 2020-04-03 22:35
@claus I'm not sure, but when I tried that it still renders as 200:
![image](https://user-images.githubusercontent.com/709451/78410322-c8b99e80-75c0-11ea-8104-94c76877c027.png)

**Comment by claus** [comment] 2020-04-03 22:41
Weird. I just tried it here and it worked just fine
<img width="455" alt="Screen Shot 2020-04-03 at 19 40 21" src="https://user-images.githubusercontent.com/2277/78410542-09c2aa80-75e3-11ea-85a5-4cb543bbd369.png">

**Comment by Jarred-Sumner** [comment] 2020-04-03 23:15
Oh, my code was wrong – it returns 404 now. Thanks for the example @claus.

In that case, maybe the ask here is:
1. Consider adding a note in the docs for `getServerSideProps` on how to set a status code on the `res` object
2. Consider rendering the `<Error />` page by default when the `res` is non-200. This would be a breaking change though, so making it a default is questionable. 

One interesting thing Rails does to make it easier to ship breaking changes:  `config/application.rb` has a `config.load_defaults(6.0)` function included in every rails app. It loads defaults for a specific version of Rails (`6.0`), so that if they decide to change defaults later, it makes it easier to upgrade

**Comment by ingoclaro** [comment] 2020-04-10 23:59
I don't think 2. is a good idea, it would force you to always render the standard error page, there would be no way to have a different error page for a specific page. In that sense throwing a specific error might be better to trigger a default error page that way, but if the status code is set manually, then do whatever you want in your page component.

pd: since you clarified the issue, it would be good if you can edit the issue title and description to reflect your new request, or create a new issue and close this one :)

**Comment by ntnbst** [comment] 2020-04-27 11:26
> Doesn't `res` has a `statusCode` property that you can set?
> 
> ```
> export const getServerSideProps = async ({ res }) => {
>   res.statusCode = 404
>   return {
>     error: 'oops'
>   };
> };
> ```

Shouldn't It be
```
return {
    props: { 
      error: 'oops' 
    }
};
```
Cuz it throws `additional keys were returned from `getServerSideProps`. Properties intended for your component must be nested under the `props` key,`

**Comment by claus** [comment] 2020-04-27 11:29
Yes @ntnbst, sorry.

**Comment by justincy** [comment] 2020-05-19 21:53
Two other related feature requests for `getServerSideProps`:

* [Error responses](https://github.com/zeit/next.js/discussions/12652)
* [Redirects](https://github.com/zeit/next.js/discussions/11281)

**Comment by vlatkodrljin** [comment] 2020-07-09 21:34
```
export const getServerSideProps = async ({ res }) => {
  res.statusCode = 404
  return {
    props: {
       error: 'oops'
    }
  };
};
```

When I use Link from 'next/link' to navigate to a page which has this getServerSideProps with custom res.statusCode set, page is fully refreshed. Does anybody also have that issue?

**Comment by creativiii** [comment] 2020-08-20 14:09
For anyone that has found this page looking at how to redirect in `getServerSideProps`, the code on this page seems to be outdated and did not work for me.

This, however, worked:
```
export const getServerSideProps = async ({ res }) => {
  res.statusCode = 404
  res.end();
  return {
    props: {
       error: 'oops'
    }
  };
};
```

**Comment by MattHsiung** [comment] 2020-09-01 19:37
So is the recommended practice for handling `getServerSideProps` errors to catch them, and then render appropriately in that page's component as opposed to throwing the appropriate error and having it caught by the `_error` page?
Should we be treating the `_error` page as solely for unhandled errors?

**Comment by KotoriK** [comment] 2020-09-03 17:27
> For anyone that has found this page looking at how to redirect in `getServerSideProps`, the code on this page seems to be outdated and did not work for me.
> 
> This, however, worked:
> 
> ```
> export const getServerSideProps = async ({ res }) => {
>   res.statusCode = 404
>   res.end();
>   return {
>     props: {
>        error: 'oops'
>     }
>   };
> };
> ```

Thanks. It's at least working on Next.js v9.5.2.
if not add ```res.end()``` , Nextjs will keep trying to render the page.
However, with this method Error Page Redirecting will failed.

**Comment by creativiii** [comment] 2020-09-03 17:31
> > For anyone that has found this page looking at how to redirect in `getServerSideProps`, the code on this page seems to be outdated and did not work for me.
> > 
> > This, however, worked:
> > 
> > ```
> > export const getServerSideProps = async ({ res }) => {
> >   res.statusCode = 404
> >   res.end();
> >   return {
> >     props: {
> >        error: 'oops'
> >     }
> >   };
> > };
> > ```
> 
> Thanks. It's at least working on Next.js v9.5.2.
> if not add ```res.end()``` , Nextjs will keep trying to render the page.
> However, with this method Error Page Redirecting will failed.

I'll be honest I'm still very confused on how to redirect to an error page, but at least this solution pleases google.

An official docs page would be great, cause there's clearly not enough information...

**Comment by KotoriK** [comment] 2020-09-03 17:52
> > > For anyone that has found this page looking at how to redirect in `getServerSideProps`, the code on this page seems to be outdated and did not work for me.
> > > 
> > > This, however, worked:
> > > 
> > > ```
> > > export const getServerSideProps = async ({ res }) => {
> > >   res.statusCode = 404
> > >   res.end();
> > >   return {
> > >     props: {
> > >        error: 'oops'
> > >     }
> > >   };
> > > };
> > > ```
> > 
> > Thanks. It's at least working on Next.js v9.5.2.
> > if not add ```res.end()``` , Nextjs will keep trying to render the page.
> > However, with this method Error Page Redirecting will failed.
> 
> I'll be honest I'm still very confused on how to redirect to an error page, but at least this solution pleases google.
> 
> An official docs page would be great, cause there's clearly not enough information...

Thanks for mention. I've googled the resolution but many of them handle the error in Page Render Function, which is not gracefully to me.
In my opinion Nextjs should take care of things like this, and getServerSiteProps() has enough space to both support error handling and keep its backward capability.

**Comment by fabioespinosa** [comment] 2020-09-25 12:04
In Next v 9.5.3 it seems you no longer need res.end() at least it's working for me without it.

**Comment by Zauberfisch** [comment] 2020-10-24 07:00
@vlatkodrljin I've noticed the same behaviour and created a bug report for it: https://github.com/vercel/next.js/issues/18185 plus a possible hacky but working workaround

**Comment by creativiii** [comment] 2020-10-24 09:31
> @vlatkodrljin I've noticed the same behaviour and created a bug report for it: https://github.com/vercel/next.js/issues/18185 plus a possible hacky but working workaround

Already tried this #17778 🤷‍♂️

**Comment by Zauberfisch** [comment] 2020-10-24 11:27
@creativiii uhm, if I am reading this correctly, you're bug-report/discussion is the same as this issue here which talks about not being able to set the status code.

However, that is not true. The example I provide in #18185 actually works and does set the correct http status code.

**Comment by creativiii** [comment] 2020-10-24 11:35
> @creativiii uhm, if I am reading this correctly, you're bug-report/discussion is the same as this issue here which talks about not being able to set the status code.
> 
> However, that is not true. The example I provide in #18185 actually works and does set the correct http status code.
> 
> I'm also not quiet sure why this issue is stipp open, the primary "bug" is actually not a bug. The only thing worth looking into might be better documentation

The issue is the same, I'm saying the docs should better explain how to set the status code. 

But instead they're presented as if the component already was setting a status code.

**Comment by Zauberfisch** [comment] 2020-10-25 05:33
@creativiii I agree with you that the docs should be better on this. But I'd recommend you create a new issue for it. This issue here is a feature request, your discussion has been marked as answered so I doubt any next maintainer will look at it (even though the answer is wrong and not what you wanted). And your quote of my statement is misleading because my issue is not directly related to yours.

@Jarred-Sumner perhaps you should close this issue as your requirement is already fulfilled (unless I am mistaken)

**Comment by timneutkens** [comment] 2021-01-06 12:24
This has been solved in Next.js 10: https://nextjs.org/blog/next-10#notfound-support

**Closed by timneutkens** 2021-01-06 12:24 UTC
Labels: kind: story, type: needs investigation

**Comment by shobhitsharma** [comment] 2021-07-01 11:02
@timneutkens What if I want to set other than 404 and without redirection?

**Comment by felixmeziere** [comment] 2021-07-27 18:31
Yes, @shobhitsharma for example I would like to return a 403 when someone is not allowed to see my sitemap, not a 404 :)

**Comment by steelbrain** [comment] 2022-01-04 15:53
Bump. I've got a usecase where I want to return 403 status code, instead of 200. It's not exactly 404, and there seems to be no remedy for this in given API.

**Comment by balazsorban44** [comment] 2022-01-04 16:40
The OP explicitly was interested in 404, which is now resolved. Feel free to open a different feature request, with a detailed explanation.

There might be better ways to mitigate those use cases though, for example using a Middleware: https://nextjs.org/docs/middleware
