### ISSUE TITLE
CSS module removed when transitioning through pages

### ISSUE THREAD

**Issue by dbismut** [vercel/next.js#33785] opened 2022-01-29 16:40 UTC
### Run `next info` (available from version 12.0.8 and up)

``` 
Operating System:
      Platform: linux
      Arch: x64
      Version: #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020
Binaries:
      Node: 14.18.1
      npm: 6.14.15
      Yarn: 1.22.17
      pnpm: N/A
Relevant packages:
      next: 12.0.9
      react: 17.0.2
      react-dom: 17.0.2
```

### What version of Next.js are you using?

12.0.9

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

I'm using [react-transition-group](https://reactcommunity.org/react-transition-group/) to transition through pages (let's say a fade).

The transition works fine in dev mode, but when built, it looks like the CSS module included in the transitioned page (the one the user is leaving) is aggressively detached from the page head, resulting in the transitioned page missing styles.

### Expected Behavior

**This is how it looks like in dev mode (OK):**
![ok](https://user-images.githubusercontent.com/5003380/151669224-8eddf4ef-8ad8-48cf-9212-040e0b31580e.gif)

**This is how it looks like in production mode (NOK):**
![nok](https://user-images.githubusercontent.com/5003380/151669230-7eb54661-dbf3-4174-b552-b5659fe7cd43.gif)

This doesn't seem to happen when using CSS in JS fortunately.

### To Reproduce

The sandbox (dev mode): https://codesandbox.io/s/next-transitions-bug-dynt9
The deployed sandbox (prod mode): https://csb-dynt9-a98i93n15-dbismut.vercel.app/

**Comment by balazsorban44** [comment] 2022-02-16 23:44
This is a duplicate of #17464, thanks for reporting anyway!

**Closed by balazsorban44** 2022-02-16 23:44 UTC
Labels: template: bug
