### ISSUE TITLE
[NEXT-939] SIGSEGV on `next build` with 13.2.4

### ISSUE THREAD

**Issue by aplr** [vercel/next.js#46989] opened 2023-03-10 09:56 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.26.0
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected?

`next build` CLI

### To Reproduce

I'll dig into it, maybe I can reproduce it easily. However I'd expect `next build` not to segfault on my existing codebase which works on 13.2.3 without changes other than upgrading next.

### Describe the Bug

After upgrading next to 13.2.4, when running `next build`, I'm running into a segfault.

As you can see, I'm using the app dir (only). Tell me if you need more info.

```
$ next build --experimental-app-only
info  - Loaded env from /next/apps/web/.env.local
info  - Loaded env from /next/apps/web/.env.production
warn  - You have enabled experimental features (appDir, swcPlugins, serverComponentsExternalPackages) in next.config.mjs.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

(node:83878) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
error Command failed with signal "SIGSEGV".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /user/.nvm/versions/node/v18.13.0/bin/node
Arguments: /user/.cache/node/corepack/yarn/1.22.19/lib/cli.js build
Directory: /next
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```

### Expected Behavior

No Segfault when running `yarn build`

### How are you deploying your application? (if relevant)

On Vercel, where it's also segfaulting. (Also in my Docker build)

<sub>[NEXT-939](https://linear.app/vercel/issue/NEXT-939/sigsegv-on-next-build-with-1324)</sub>

**Comment by jinojacob15** [comment] 2023-03-10 13:07
Same issue with me ,  After updating to 13.2.4 ,dev  is working fine but yarn build and yarn start (prod build)  gives me error 

![DeepinScreenshot_select-area_20230310183614](https://user-images.githubusercontent.com/69616951/224323717-e40e176c-aa12-47b1-9954-7211260fba57.png)

**Comment by jinojacob15** [comment] 2023-03-11 18:05
@aplr  is **@graphql-codegen/client-preset-swc-plugin** in built with apollo client ??. I am not using @graphql-codegen/client-preset-swc-plugin in my code i checked.

**Comment by SuttonJack** [comment] 2023-03-12 02:45
Getting the same error. It was introduced for me at `next@13.2.4-canary.6`

Version `next@13.2.4-canary.5` and below all work fine

**Comment by SuttonJack** [comment] 2023-03-12 02:46
@shuding Could this stem from https://github.com/vercel/next.js/pull/46881 ? These `ChunkLoadError` messages in the console seem to be coming from react rather than next

**Comment by martinnabhan** [comment] 2023-03-13 04:10
I can confirm I get the same issue using `next-superjson-plugin` (which is a SWC plugin). If I remove the plugin from `next.config.js` building works again. I'll look into this some more. SWC seems to be the common link.

**Comment by icyJoseph** [comment] 2023-03-13 15:32
Hi,

Do you guys have 32 bits architecture? or if you run `node -p "process.arch"`, does it match your OS?

**Comment by Timothee-P** [comment] 2023-03-15 19:00
@jinojacob15  and @SuttonJack: 
The same errors occur in my project after updating next to `13.2.4`. It doesn't seems related to this issue and SWC, but more to dynamic imports.
Just to let you know I have created a new issue https://github.com/vercel/next.js/issues/47173

**Comment by jinojacob15** [comment] 2023-03-16 04:38
@Timothee-P  @SuttonJack   @aplr    I Spent two days in debugging the issue , finally code was working when i removed dynamic imports with ssr:false . 
But there was a bizarre issue that even when i downgraded the next version to 13.2.3 and still issue persisted .

**Comment by Himself65** [comment] 2023-03-18 08:07
seems like `swcPlugins` won't work

**Comment by orionmiz** [comment] 2023-03-19 07:58
This appears to be an bug derived from #46971.

**Comment by kevin-courbet** [comment] 2023-03-20 11:36
I'm on a M2 mac and also have this issue if I have a SWC plugin enabled (next-superjson)

**Comment by yangricardo** [comment] 2023-03-28 00:23
> I'm on a M2 mac and also have this issue if I have a SWC plugin enabled (next-superjson)

Also have disabled this `next-superjson-plugin`. It is building with success again. In my case, i think have never worked as expected, so i am removing it.

**Comment by kdy1** [comment] 2023-03-28 14:13
Please see https://swc.rs/docs/plugin/selecting-swc-core

**Comment by kdy1** [comment] 2023-03-28 14:55
I'm checking if `rkyv@0.7.40` fixes this issue.

https://github.com/swc-project/swc/pull/7154

**Comment by simonknittel** [comment] 2023-03-29 12:04
I'm having a similar issue but not quite the same.
I'm also using the `next-superjson-plugin` with `swcPlugins`. Disabling that plugin makes `next build` work again.
However, having the plugin enabled results for me in a different error.
Also, downgrading to `13.2.3` like you suggested is not working.

```
warn  - You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
info  - Loaded env from /Users/simon.knittel/Documents/hmmh/snivy/app/.env
warn  - You have enabled experimental features (outputFileTracingRoot, swcPlugins) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

info  - Skipping validation of types
info  - Skipping linting
info  - Creating an optimized production build .zsh: bus error  npx next build
```

**Comment by kdy1** [comment] 2023-03-30 04:19
Https://github.com/swc-project/swc/pull/7163 will fix this.

I'll update turbopack and next-swc ASAP once it's merged.

**Comment by darthmaim** [comment] 2023-04-03 08:28
Hi @kdy1, what is left to fix this issue? Can the community somehow help?

**Comment by kdy1** [comment] 2023-04-03 08:38
https://github.com/swc-project/swc/pull/7170 fixed this, and https://github.com/vercel/turbo/pull/4358 should be merged into turbopack first

**Comment by tacomanator** [comment] 2023-04-05 23:19
> Also, downgrading to `13.2.3` like you suggested is not working.

@simonknittel  Did you remove the `.next` directory? downgrading to 13.2.3 works but you need to remove `.next` and restart. This is working with `next-superjson-plugin` for me.

**Comment by Himself65** [comment] 2023-04-07 20:51
still happened on 13.3.0

**Closed** 2023-04-18 06:59 UTC
Labels: kind: bug, template: bug, area: SWC transforms

**Comment by Himself65** [comment] 2023-04-18 08:27
> Looks like [v13.3.1-canary.12](https://github.com/vercel/next.js/releases/tag/v13.3.1-canary.12) will fix the issue

I think no

**Comment by sFritsch09** [comment] 2023-05-15 16:47
Removing sharp from dependencies worked for me!
`yarn remove sharp`
