### ISSUE TITLE
Missing component crashes computer

### ISSUE THREAD

**Issue by pkail** [vercel/next.js#19210] opened 2020-11-16 13:20 UTC
#18599 Bug report

## Describe the bug
Missing out a component causes the computer to slow down to a crawl, such that it has to be re-booted.

Missing out a component causes the computer to slow down to a crawl, such that it has to be re-booted.
## To Reproduce
Miss out a component.

Steps to reproduce the behavior, please provide code snippets or a repository:

import Layout from '../components/Layout';
import SpeedText from '../components/speedText';

const Speed = () => (
	<Layout title="Speed">
		<Speed/>  <<<<missing component
	</Layout>
);

export default Speed;
then run yarn dev and navigate to localhost:3000/speed in FF or Chrome.
## Expected behavior
localhost:3000/speed "compiled successfully".  Expected to see it in the browser.

## System information

- OS: [e.g. macOS, Windows]
Mint 19.3
- Browser (if applies) [e.g. chrome, safari]
FF, Chrome.  
- Version of Next.js: [e.g. 6.0.2]
10
- Version of Node.js: [e.g. 10.10.0]
12.10
## Additional context
All other pages work fine.  Display of active processes with top shows 'code' (i.e., VS Code) taking massive amounts of CPU time.
This has been extremely annoying.  It failed silently, in such a way that I assumed the problem was something else (such as the Image component, the hardware, etc.)

**Comment by timneutkens** [comment] 2020-11-16 15:11
This is impossible to investigate without a complete reproduction and even then it seems like it could be an issue with vscode + custom plugins that are potentially installed 🤔

**Comment by pkail** [comment] 2020-11-16 15:30
>>This is impossible to investigate without a complete reproduction
Yes, that would be the next step.
>>it seems like it could be an issue with vscode + custom plugins that are potentially installed
It's hard to think of a plug-in which would crash the computer because a component has been spelled wrongly.  If you have any suggestions I will disable some of them to see what happens.

**Comment by pkail** [comment] 2020-11-16 15:33
Bear in mind that the problem comes after the code is compiled, at the point when I try to access the page in the browser.  Nothing different is happening in VS Code at this point (the code isn't even being displayed in VS Code).

**Comment by pkail** [comment] 2020-11-17 01:49
In any case, this bug causes the browser to gum up completely *even when VS Code is closed*.

**Comment by timneutkens** [comment] 2020-11-17 13:02
This still can't be investigated without a complete reproduction.

**Comment by pkail** [comment] 2020-11-18 20:14
The problem has nothing to do with the Linux kernel, nor with the rest of my code.  It's actually the following: I accidentally referenced the Component <Speed /> in the definition of itself, hence creating a endless loop:

import Layout from '../components/Layout';
import SpeedText from '../components/speedText';

const Speed = () => (
	<Layout title="Speed">
		<Speed />
	</Layout>
);

export default Speed;

The problem was introduced by Next.js, which replaced all the anonymous components with named components.  I incorrectly referenced <SpeedText /> as <Speed /> and then Next.js introduced this as the name of the (previously anonymous) component.

It might be a good idea to have some code which recognizes this type of error and produces an error message rather than crashing the computer, and also something which stops Next.js from creating this problem in the first place.

**Comment by timneutkens** [comment] 2020-11-24 10:20
Please provide a full reproduction as asked for so that we can have a look, otherwise this issue will remain open / will be closed in a while.

**Comment by timneutkens** [comment] 2020-11-24 10:23
Going to close this issue until a reproduction is provided, thanks!

**Closed by timneutkens** 2020-11-24 10:23 UTC
Labels: please add a complete reproduction, template: bug

**Comment by pkail** [comment] 2020-11-24 17:18
import Layout from '../components/Layout';
import SpeedText from '../components/speedText';

const Speed = () => (
	<Layout title="Speed">
		<Speed />
	</Layout>
);

export default Speed;

**Comment by pkail** [comment] 2020-11-24 17:20
I have pasted the full code in twice.  Each time, GitHub has removed most of it.  Maybe you can work out your own example in which a component references itself.

**Comment by balazsorban44** [comment] 2022-01-29 02:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
