### ISSUE TITLE
App A is serving pages from unrelated app B

### ISSUE THREAD

**Issue by olavfosse** [vercel/next.js#25724] opened 2021-06-02 11:23 UTC
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

Google Chrome 90.0.4430.212

### What operating system are you using?

Fedora 34 (Workstation Edition)

### How are you deploying your application?

not relevant

### Describe the Bug

I have app A running on localhost:3000. I have another app B stored on the same machine, but not currently running.  
When I open `http://localhost:3000` in my machine 50% of the time I get the pages/index.js page of app B wrapped in the app.js of app A.

### Expected Behavior

I expect to always get the index.js page from app A.

### To Reproduce

TODO

**Comment by fossegrim** [comment] 2021-06-02 11:28
reproduction is TODO, because the app is propietary and I don't have time to try reproducing this in a new app right now.

**Comment by myteax** [comment] 2021-06-02 23:03
Hi, which of your repo?

**Comment by ijjk** [comment] 2021-09-19 05:40
Hi, I'm not able to reproduce this from the information provided and sounds unlikely to be a bug in Next.js and more likely a caching issue with the local setup so I'm going to close this. If you are still having trouble with this feel free to respond with more information to allow further investigation.

**Closed by ijjk** 2021-09-19 05:40 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
