### ISSUE TITLE
I have the same problem as #14872 #16253 #16253 

### ISSUE THREAD

**Issue by SelmiAhmed** [vercel/next.js#16330] opened 2020-08-18 22:18 UTC
when modifying the mobx state data, the latest data is not rendered

**Comment by jamesmosier** [comment] 2020-08-19 00:46
Closing in favor of #16253. Feel free to add a repository that reproduces this over there to help centralize this issue and help others track down the issue.

**Closed by jamesmosier** 2020-08-19 00:46 UTC

**Comment by balazsorban44** [comment] 2022-01-29 16:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
