### ISSUE TITLE
AsPath is incorrect on Server if you use rewrites and getInitialProps

### ISSUE THREAD

**Issue by roman-may** [vercel/next.js#20370] opened 2020-12-21 16:21 UTC
# Bug report

## Describe the bug

AsPath is incorrect on Server if you use rewrites and getInitialProps. On the server, asPath is the rewritten asPath while on the client asPath ist as given in the request URL.

## To Reproduce

Start with a new next typescript project. And add:

Next.config.js
```
module.exports = {
  async rewrites() {
    return [
      {
        source: "/:sector(s1|s2)/product/:pid",
        destination: "/product/:pid",
      },
    ];
  },
};
```
/pages/product/[pid].tsx
```
import { NextPage } from 'next';
import { useRouter } from 'next/router';

const Product: NextPage = () => {
  const { asPath } = useRouter();
  console.log({ asPath });
  return <h1>Product</h1>;
};


Product.getInitialProps = ({ asPath, query }) => {
  // dataFetch
  return {};
};

export default Product;
```

1. Go to `/s1/product/42`
2. Compare logs on server and clientside.

## Expected behavior
AsPath on server and client ist `/s1/product/42`

## System information

- OS: Windows
- Version of Next.js: 10.0.3
- Version of Node.js: 12.18.3

## Additional Information
If you use getServerSideProps instead of getInitialProps it works as expected. You can test this by replacing 
```
Product.getInitialProps = ({ asPath, query }) => {
  // dataFetch
  return {};
};
```
with 
```
export const getServerSideProps: GetServerSideProps = async () => {
  // datafetch
  return { props: {} };
};
```

**Comment by nghiepit** [comment] 2020-12-22 16:49
Duplicate of #17113 and #17143

**Comment by roman-may** [comment] 2020-12-23 09:39
Im not sure if this is a duplicate as https://github.com/vercel/next.js/issues/17143 seems to be an issue with pages using static optimization / getStaticProps. 
In this case, static optimization ist not used and the path including parameters is known on the server. 
Since it works if you use  getServerSideProps instead of getInitialProps i think it is of different origin, but I can close it if I'm mistaken and this is not the case.

**Comment by kaykdm** [comment] 2020-12-29 08:46
I think same issue was used to happen on `getServerSideProps`, but it was fixed in this PR (https://github.com/vercel/next.js/pull/17121).

`getInitialProps` needs same fix, and I am going to work on this.

**Comment by roman-may** [comment] 2021-01-04 06:09
Thank you very much @kaykdm

**Comment by kaykdm** [comment] 2021-01-23 12:27
I think this is fixed in [this](https://github.com/vercel/next.js/pull/21410)

**Comment by nghiepit** [comment] 2021-01-23 13:29
@kaykdm PR just fix asPath for getServersideProps .
getInitialProps and const {asPath} = useRouter() still incorrect 😭

**Comment by kaykdm** [comment] 2021-01-23 13:30
@nghiepit
Have you tried with v10.0.6-canary.7 ?

**Comment by nghiepit** [comment] 2021-01-23 13:35
@kaykdm 
Reproduction `v10.0.6-canary.7` https://codesandbox.io/s/sharp-cannon-kcsio?file=/pages/post.js

**Comment by kaykdm** [comment] 2021-01-23 13:40
@nghiepit 
Thanks for reproduction!
I just realized that I was testing with different branch.

You are right. This issue still exists, so I reopened my PR.
Thanks again!

**Comment by nghiepit** [comment] 2021-01-23 13:42
@kaykdm Does your PR have a fix for `useRouter()`?

**Comment by kaykdm** [comment] 2021-01-23 13:53
@nghiepit 
I just tested, and it didn't fix for `useRouter()`
I will try to fix that when I have time.

**Closed** 2021-01-25 18:26 UTC
Labels: good first issue, kind: bug, type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-28 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
