### ISSUE TITLE
Experimental: TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by raghav0622** [vercel/next.js#12774] opened 2020-05-12 08:01 UTC
# Bug report

Unhandled Runtime Error:- TypeError: Cannot read property 'call' of undefined

## Describe the bug

No idea of what the bug is or where the bug originates from.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
Github Repo: https://github.com/raghav0622/personal-finance-app
1. enable suspense mode in experimental.reactMode in next.config.js
2. do suspense stuff 
3.  sometimes there is this error and sometimes there is not.

## Expected behavior

It should work as it works in production

## Screenshots
![screencapture-localhost-3000-2020-05-12-13_23_44](https://user-images.githubusercontent.com/29769428/81656200-73d93580-9454-11ea-8544-c58c280b04dc.png)

## System information

- OS: Windows 10
- Browser (if applies) : chrome, firefox
- Version of Next.js: [e.g. 9.4]
- Version of Node.js: [e.g. 10.10.0]

## Additional context
I googled about it alot but can't relate anything as i am not using any custom webpack config / loaders etc., just the nextjs' predefined stuff. I can't find the root of this error, this error has been killing me, it sometimes shows up and sometimes doesn't shows up in development mode. In production when i run 'yarn build' and 'yarn start' it works fine and is even deployed to now v2 (https://personal-finance-app.now.sh/)

**Comment by GainorB** [comment] 2020-05-15 01:36
I am getting this same error, randomly, it started happening after trying to setup i18next

**Comment by istvanjkb** [comment] 2020-05-15 10:33
I have experienced the same issue. There might be some issue with the `Fast Refresh` feature. If I remove then readd a child component, the states are not set properly.

**Comment by raghav0622** [comment] 2020-05-15 13:26
I found a temporary hack, i clear cache from localhost and then reload, it sometimes work but not sure if issue is related to cache

**Comment by tonxxd** [comment] 2020-05-16 16:24
I have the same issue, happens only in dev mode and it started happening only few days ago after upgrading to next@canary

**Comment by jackblackCH** [comment] 2020-08-05 18:39
Can be caused from third party libs, e.g they throw an Error. in my case it is a 'aws' module. Is there a way to tell nextjs to ignore some libs?

**Comment by m-torin** [comment] 2021-02-17 13:50
For whatever it's worth, this error shows up in Sidekick/Chrome Version 87.7.42.7010 (Official Build) (x86_64), but is not reproducing in Firefox 86 (developer).

**Comment by timneutkens** [comment] 2021-11-18 09:08
This has probably been fixed after we've adopted webpack 5 in Next.js, unfortunately I can't verify this because the repository is no longer available. I'll close this issue now. If you're still running into this please create a new issue.

**Closed by timneutkens** 2021-11-18 09:08 UTC
Labels: kind: bug, good first issue
