### ISSUE TITLE
Add a require hook for webpack backwards compatibility

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#21789] opened 2021-02-02 19:47 UTC
Next.js no longer ships with the `webpack` dependency, however, lots of plugins (improperly) require `webpack` without a peer dependency setup. To prevent them from breaking, we need to inject a require hook to intercept this request and vendor Next.js' built-in version.

**Comment by ramasilveyra** [comment] 2021-02-02 21:29
I was about to submit an issue reporting that worker-loader no longer works with webpack 5. This is the bug repro in case that you want to check https://github.com/ramasilveyra/bug-repro-next-w5-inline-worker but it seems that my draft issue is a duplication of this

**Comment by ramasilveyra** [comment] 2021-02-02 22:36
FYI some things that I found while trying to make worker-loader work:
- worker-loader specifies webpack as peer dep.
- worker-loader uses internal webpack modules like `webpack/lib/node/NodeTargetPlugin`, see https://github.com/webpack-contrib/worker-loader/blob/v3.0.7/src/index.js for more examples.

**Comment by ijjk** [comment] 2021-02-08 16:27
Closing as this was landed in https://github.com/vercel/next.js/pull/21802

**Closed by ijjk** 2021-02-08 16:27 UTC
Labels: kind: bug, priority: p0

**Comment by ramasilveyra** [comment] 2021-02-08 16:41
FYI worker-loader is still broken, created ticket https://github.com/vercel/next.js/issues/21972.

**Comment by balazsorban44** [comment] 2022-01-28 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
