### ISSUE TITLE
jsx file doesnt like jsx?

### ISSUE THREAD

**Issue by maraisr** [vercel/next.js#15251] opened 2020-07-17 06:57 UTC
# Bug report

## To Reproduce

1. Clone https://github.com/maraisr/nextjs-repro-repo/tree/monorepo
2. run `yarn`
3. run `yarn workspace next-repro start`

## Expected behavior

Not to see error

## Screenshots

![image](https://user-images.githubusercontent.com/599459/87757737-7a1dd080-c84e-11ea-9825-64036682aca9.png)

## System information

- OS: Windows
- Browser: Firefox
- Version of Next: 9.4.4
- Version of Node.js: 14

## Additional context

Related: #13197, #706, #9474

**Comment by timneutkens** [comment] 2020-07-17 09:13
Looks like you're not compiling the repo-components package that is imported here: https://github.com/maraisr/nextjs-repro-repo/blob/monorepo/packages/app/pages/index.js#L2 

This is indeed a duplicate of #706 and #9474

**Closed by timneutkens** 2020-07-17 09:13 UTC

**Comment by maraisr** [comment] 2020-07-17 09:24
Typically though in a monorepo you don't compile things. And besides isn't the compilation part, the job of next? @timneutkens

**Comment by timneutkens** [comment] 2020-07-17 09:35
This change will potentially help with your particular use case: https://github.com/vercel/next.js/pull/13542#discussion_r453329025

**Comment by balazsorban44** [comment] 2022-01-29 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
