### ISSUE TITLE
[NEXT-834] Regression in 13.2: 404 on pages with dynamic routes and i18n enabled

### ISSUE THREAD

**Issue by jleclanche** [vercel/next.js#46841] opened 2023-03-06 18:20 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 16.19.1
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.2.4-canary.4
      eslint-config-next: 13.2.3
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

-

### To Reproduce

Use dynamic routing for URLs such as /test/[uuid]/page.tsx

### Describe the Bug

This broke specifically in `next@13.1.7-canary.14`, as it was still working in `next@13.1.7-canary.13`. Currently reviewing all the commits between the two versions to see what might be causing it.

I get nothing in the logs, very mysterious.

### Expected Behavior

No 404

<sub>[NEXT-834](https://linear.app/vercel/issue/NEXT-834/regression-in-132-404-on-pages-with-dynamic-routes-and-i18n-enabled)</sub>

**Comment by jleclanche** [comment] 2023-03-06 18:36
- Removing use of `params` in the function doesn't fix it
- Even a simple `<div>Test</div>` reproduces it

```tsx
const Page = async () => {
	return <div>Test</div>;
};

export default Page;
```

**Comment by mdrayer** [comment] 2023-03-06 18:48
Hmm, I am using the latest `13.2.4-canary.4` and my dynamic pages (`/app/foo/[slug]/page.tsx`) are responding just fine (`200` status). Any other instructions here to get the unwanted `404` behavior to happen?

**Comment by jleclanche** [comment] 2023-03-06 18:48
Currently trying to reduce my use case, because yeah I suspect there's more to it.

**Comment by jleclanche** [comment] 2023-03-06 19:03
The following is needed in next.config.js to trigger it

```js

	i18n: {
		locales: ["en"],
		defaultLocale: "en",
	},
```

**Comment by jleclanche** [comment] 2023-03-06 19:07
Minimal reproduction case. 

[nextjs-issue-46841.zip](https://github.com/vercel/next.js/files/10901992/nextjs-issue-46841.zip)

**Comment by pveyes** [comment] 2023-03-06 23:34
this is probably duplicate of #46814

**Comment by kulikov92** [comment] 2023-03-07 15:27
I have the same problem, dynamic routes do not work with non-default locale

**Comment by jleclanche** [comment] 2023-03-07 16:12
@pveyes yeah seems like it is.

**Comment by kespinola** [comment] 2023-03-16 09:57
Confirming route segments don't work when have i18n enabled in next.config. for next@13.2.x

**Closed** 2023-03-24 12:06 UTC
Labels: template: bug, linear
