### ISSUE TITLE
Cannot install Next.js 9.4.4 with Yarn PnP/Berry: '@ampproject/toolbox-optimizer@npm:2.4.0 Cannot be built'

### ISSUE THREAD

**Issue by mxro** [vercel/next.js#15476] opened 2020-07-25 21:59 UTC
# Bug report

## Describe the bug

On trying to add Next.js dependency, the following error is reported:

```
➤ YN0000: ┌ Link step
➤ YN0007: │ @ampproject/toolbox-optimizer@npm:2.4.0 [717c6] must be built because it never did before or the last one failed
➤ YN0009: │ @ampproject/toolbox-optimizer@npm:2.4.0 [717c6] couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/xb/mkvj52yn6f174632nfmgf5f1nfkbf4/T/xfs-7cf27f17/build.log)
➤ YN0009: │ @ampproject/toolbox-optimizer@npm:2.4.0 [717c6] couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/xb/mkvj52yn6f174632nfmgf5f1nfkbf4/T/xfs-7cf27f17/build.log)
➤ YN0000: └ Completed in 11.37s
```

The error in the build log is:

```
Error: @ampproject/toolbox-optimizer tried to access dom-serializer, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: dom-serializer (via "dom-serializer")
Required by: @ampproject/toolbox-optimizer@virtual:717c60bb7e1f18db4fa28a328136d908d2f0be772ac81744071e39e823bce1152cb8cd598e20574dd33c9c21bf4563290d0b9cc940ed521d64045a52208cdc1f#npm:2.4.0 
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Configure project to use Yarn 2 / Berry / PnP resolution https://yarnpkg.com/getting-started/install
2. Run `yarn add next@9.4.4 react react-dom`
3. Errors above are reported, Next.js dependency is not installed.

## Expected behavior

Next.js dependency can be installed without errors.

## System information

- OS: mac os
- Version of Next.js: 9.4.4
- Version of Node.js: 12.18.0

## Additional context

There is a workaround. I found the installation works just fine when using `next@9.4.0`

**Comment by merceyz** [comment] 2020-07-31 19:47
Fixed in v9.4.5-canary.3 (https://github.com/vercel/next.js/pull/13547)

**Closed** 2020-08-01 16:28 UTC
Labels: good first issue

**Comment by mxro** [comment] 2020-08-08 03:12
Confirming this works in v9.4.5-canary.3. Thank you 👍

**Comment by balazsorban44** [comment] 2022-01-29 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
