### ISSUE TITLE
"next/image" conflicts with "rewrite"

### ISSUE THREAD

**Issue by alithecodeguy** [vercel/next.js#26993] opened 2021-07-07 17:08 UTC
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

16.3.0

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying your application?

local , vercel

### Describe the Bug

I enabled "rewrite" feature for my own project , but next/image (<Image/>) doesn't work anymore.

### Expected Behavior

It should be ok as before.

### To Reproduce

1- npx create-next-app <something>
2- add next/image and show some image with <Image/>
3- enable rewrite.
4- you should see can't load image anymore and give 404 status code.

after a few minutes you should see this error on your ide console :
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
![Screen Shot 2021-07-07 at 21 36 58](https://user-images.githubusercontent.com/65894067/124800989-8a512300-df6b-11eb-95b5-25f24f74cd74.png)

**Comment by styfle** [comment] 2021-07-07 17:16
This sounds like a duplicate of #24421

**Closed** 2021-07-12 22:58 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
