### ISSUE TITLE
Example progressive-web-app does not compile

### ISSUE THREAD

**Issue by richardthombs** [vercel/next.js#22798] opened 2021-03-05 10:44 UTC
### What example does this report relate to?

progressive-web-app

### What version of Next.js are you using?

Next.js v10.0.7

### What version of Node.js are you using?

v14.15.5

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

npm run dev

### Describe the Bug

Application fails to build and instead produces this error:

```
Error: Cannot find module 'webpack'
Require stack:
- C:\dev\pwa\node_modules\workbox-webpack-plugin\build\lib\get-manifest-entries-from-compilation.js
- C:\dev\pwa\node_modules\workbox-webpack-plugin\build\generate-sw.js
- C:\dev\pwa\node_modules\workbox-webpack-plugin\build\index.js
- C:\dev\pwa\node_modules\next-pwa\index.js
- C:\dev\pwa\next.config.js
- C:\dev\pwa\node_modules\next\dist\next-server\server\config.js
- C:\dev\pwa\node_modules\next\dist\next-server\server\next-server.js
- C:\dev\pwa\node_modules\next\dist\server\next.js
- C:\dev\pwa\node_modules\next\dist\server\lib\start-server.js
- C:\dev\pwa\node_modules\next\dist\cli\next-dev.js
- C:\dev\pwa\node_modules\next\dist\bin\next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\dev\pwa\node_modules\workbox-webpack-plugin\build\lib\get-manifest-entries-from-compilation.js:12:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\dev\pwa\node_modules\workbox-webpack-plugin\build\generate-sw.js:24:43)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\dev\\pwa\\node_modules\\workbox-webpack-plugin\\build\\lib\\get-manifest-entries-from-compilation.js',
    'C:\\dev\\pwa\\node_modules\\workbox-webpack-plugin\\build\\generate-sw.js',
    'C:\\dev\\pwa\\node_modules\\workbox-webpack-plugin\\build\\index.js',
    'C:\\dev\\pwa\\node_modules\\next-pwa\\index.js',
    'C:\\dev\\pwa\\next.config.js',
    'C:\\dev\\pwa\\node_modules\\next\\dist\\next-server\\server\\config.js',
    'C:\\dev\\pwa\\node_modules\\next\\dist\\next-server\\server\\next-server.js',
    'C:\\dev\\pwa\\node_modules\\next\\dist\\server\\next.js',
    'C:\\dev\\pwa\\node_modules\\next\\dist\\server\\lib\\start-server.js',
    'C:\\dev\\pwa\\node_modules\\next\\dist\\cli\\next-dev.js',
    'C:\\dev\\pwa\\node_modules\\next\\dist\\bin\\next'
  ]
}
```

### Expected Behavior

Application builds without errors

### To Reproduce

npx create-next-app --example progressive-web-app pwa
cd pwa
npm run dev

**Comment by timneutkens** [comment] 2021-03-06 17:46
Duplicate of #21679

This has been fixed in `10.0.8` (released yesterday) 🎉

**Closed by timneutkens** 2021-03-06 17:46 UTC
Labels: template: bug, type: example

**Comment by lvkins** [comment] 2021-03-07 00:50
> 
> 
> Duplicate of #21679
> 
> This has been fixed in `10.0.8` (released yesterday) 🎉

Doesn't look like it's fixed. Just experienced same issue. Been upgrading from `10.0.4` to `10.0.8`.

**Comment by kachkaev** [comment] 2021-03-24 14:33
Same issue in next `10.0.9` after upgrading from `10.0.4`.

```
Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
Require stack:
- /path/to/project/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js
- /path/to/project/node_modules/next/dist/compiled/webpack/bundle4.js
- /path/to/project/node_modules/next/dist/compiled/webpack/webpack.js
- /path/to/project/node_modules/next/dist/next-server/server/config-utils.js
- /path/to/project/node_modules/next/dist/next-server/server/config.js
- /path/to/project/node_modules/next/dist/next-server/server/next-server.js
- /path/to/project/node_modules/next/dist/server/next.js
- /path/to/project/node_modules/next/dist/server/lib/start-server.js
- /path/to/project/node_modules/next/dist/cli/next-dev.js
- /path/to/project/node_modules/next/dist/bin/next
overrideMethod @ react_devtools_backend.js:2430
handleErrors @ hot-dev-client.js?647e:162
processMessage @ hot-dev-client.js?647e:208
eval @ hot-dev-client.js?647e:54
eval @ eventsource.js?9b42:39
handleMessage @ eventsource.js?9b42:37
```

**Comment by haiifeng** [comment] 2021-05-18 09:49
@kachkaev thank you very much.
that helps me.

**Comment by balazsorban44** [comment] 2022-01-28 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
