### ISSUE TITLE
Next app can not run in Yarn berry/pnp mono project

### ISSUE THREAD

**Issue by juuyan** [vercel/next.js#16235] opened 2020-08-16 18:14 UTC
# Bug report

## Describe the bug
In a yarn berry/pnp project, run Next app with `yarn dev` get the following error:
`next tried to access caniuse-lite, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a mono repo with yarn berry, use default pnp model.
2. Create a next app as a workspace of this mono rep, with `yarn create next-app`
3. Run `yarn dev` in the app folder.

## Expected behavior
It should work well in a local portal, as pnp should be supported out of box.

- Version of Next.js: [9.5.2]
- Version of Node.js: [14.4.0]

**Comment by timneutkens** [comment] 2020-08-16 19:30
Fixed in #16091

**Closed by timneutkens** 2020-08-16 19:30 UTC

**Comment by balazsorban44** [comment] 2022-01-29 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
