### ISSUE TITLE
Dependency version restrictions in package.json

### ISSUE THREAD

**Issue by csirkeee** [vercel/next.js#15405] opened 2020-07-22 10:24 UTC
Reopens #6465 and #2993.

# Feature request

Please loosen dependency version restrictions

## Is your feature request related to a problem? Please describe.

The current way of pinning exact versions makes the node_modules folder very bloated, because packages can't be deduped.

It needs effort from members of the Vercel team for any patches to propagate into Next.js project.

For example, the version of @babel/core that is pinned in the current latest stable Next.js release (9.4.4) is a 7 month old version (7.7.7). For us, many other indirect dependencies required a higher version, and we ended up with more than a 100 copies of @babel/core in our node_modules folder.

## Describe the solution you'd like

Pin dependencies to major version (i.e. ^)

## Describe alternatives you've considered

Keep your dependencies more up to date, maybe with some automatic process.

## Additional context

I understand the reasoning on the previous tickets, but I think you're fighting an uphill battle. Most of your dependencies are indirect, a freshly created `npx create-next-app --example with-typescript` app will have more than 2000 dependencies in its `yarn list`, more than two thirds of which are locked to major version, you only pin the 50 that you directly depend on.

I understand that you hear about it every time a dependancy breaks their contract, and breaks on a minor version upgrade, but I think you might be underestimating the issues caused by pinning the versions. For one, since there are existing closed tickets for this issue, and there is no way to interact with closed tickets on this repo, more polite people might just give up even if they do have problems. Also, the problems caused by the pinning are mostly just bloat and slowness, less obvious to notice.

**Comment by Timer** [comment] 2020-07-22 16:15
This issue has been debated very extensively in the issues you mentioned, and more.

Unfortunately, the npm ecosystem does not follow semver and not pinning dependencies would result in constant breakages.

For example, the latest Babel version breaks Next.js, which is why we're **intentionally** pinned to and older version.

I'm closing this issue as we keep dependencies up to date as quickly as possible when we're able! Feel free to send PRs upgrading package versions, we'll happily merge if all tests pass.

**Closed by Timer** 2020-07-22 16:15 UTC

**Comment by balazsorban44** [comment] 2022-01-29 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
