### ISSUE TITLE
(Webpack 5) Caching failed for pack: Error: Can't resolve 'fsevents'

### ISSUE THREAD

**Issue by aXenDeveloper** [vercel/next.js#23533] opened 2021-03-30 09:35 UTC
### What example does this report relate to?

npm run build / npm run dev

### What version of Next.js are you using?

10.1.2

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next build

### Describe the Bug

When I run npm run build (next build) and when I npm run dev (next dev) then I got this warning:
"[webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'fsevents' in 'C:\Users\aXen\Desktop\test123\node_modules\chokidar'"

### Expected Behavior

The app is working fine, but there are warnings in Webpack 5.
In Webpack 4 works fine.

### To Reproduce

1. npx create-next-app test123
2. Create next.config.js and paste:
```
module.exports = {
  future: {
    webpack5: true,
  },
}
```
2. npm run dev
3. Stop app
4. npm run build

info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types
info  - Creating an optimized production build ..<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'fsevents' in 'C:\Users\aXen\Desktop\test123\node_modules\chokidar'
<w> while resolving 'fsevents' in C:\Users\aXen\Desktop\test123\node_modules\chokidar to a directory
info  - Creating an optimized production build .<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'fsevents' in 'C:\Users\aXen\Desktop\test123\node_modules\chokidar'
<w> while resolving 'fsevents' in C:\Users\aXen\Desktop\test123\node_modules\chokidar to a directory
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'fsevents' in 'C:\Users\aXen\Desktop\test123\node_modules\chokidar'
<w> while resolving 'fsevents' in C:\Users\aXen\Desktop\test123\node_modules\chokidar to a directory
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data  
info  - Generating static pages (3/3)
info  - Finalizing page optimization

**Comment by EladTal14** [comment] 2021-04-04 13:11
@aXenDeveloper I Talked with someone that work on webpack they said they will fix this bug after holidays, its only a warning but persistent caching won't work.

**Comment by mutuadavid93** [comment] 2021-04-05 07:06
@EladTal14  does this mean we can confortably deploy to Production with that Webpack option set to true?

**Comment by EladTal14** [comment] 2021-04-05 07:11
@mutuadavid93 Hi, yes you can deploy your build will work but the persistent caching feature won't work until bug is fixed.

**Comment by sivaraj-v** [comment] 2021-04-10 09:39
Webpack 5 not working,

```
module.exports = {
  future: {
    **webpack5: false,**
  },
}
```
Use 4 untill webpack fix the issue or add the fsevents package

**Comment by timneutkens** [comment] 2021-04-12 08:35
This is fixed on next@canary: https://github.com/vercel/next.js/releases/tag/v10.1.4-canary.4

**Closed** 2021-04-12 08:35 UTC
Labels: kind: bug

**Comment by balazsorban44** [comment] 2022-01-28 13:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
