### ISSUE TITLE
next/image cloudinary loader not setting quality=auto

### ISSUE THREAD

**Issue by rafi-fisker** [vercel/next.js#20278] opened 2020-12-17 20:07 UTC
# Bug report

## Describe the bug

Using the `cloudinary` loader does not set the cloudinary quality parameter to "auto" if unset or if set to "auto"

## To Reproduce

next.config.js
```
  images: {
    loader: 'cloudinary',
    path: 'https://my.domain.com/image/upload/',
    deviceSizes: [640, 750, 828, 1080, 1200, 1920]
  },
```
code
```
import Image from 'next/image'

<Image
  src='/path/to/my/image.jpg'
  alt=''
  layout='responsive'
  width={1440}
  height={1080}
  quality='auto'    /* also tried removing this line */
/>
```

Generated URL: https://my.domain.com/image/upload/f_auto,c_limit,w_1920/path/to/my/image.jpg
## Expected behavior

Expected URL: https://my.domain.com/image/upload/f_auto,c_limit,w_1920,q_auto/path/to/my/image.jpg

## System information

- Version of Next.js: 10.0.3
- Version of Node.js: 12.x
- Deployment: next start

## Additional context

The loader appears to set a default of `q_auto` if not set, but doesn't seem to work correctly
https://github.com/vercel/next.js/blob/72fae8bed45760e2f8c13e6e759a149156f4b5d7/packages/next/client/image.tsx#L429-L434

Setting an integer value does, however, work correctly. 
```
<Image
  src='/path/to/my/image.jpg'
  alt=''
  layout='responsive'
  width={1440}
  height={1080}
  quality={75}
/>
```
Correctly generates https://my.domain.com/image/upload/f_auto,c_limit,w_1920,q_75/path/to/my/image.jpg

**Comment by ablax** [comment] 2020-12-18 11:11
The code block you have shared is from the canary (test) version.
The issue is reproducable on 10.0.3 and already fixed on the canary version
https://github.com/vercel/next.js/commit/fddad89cbccd74d74553986c79f387d2369e6185

**Comment by timneutkens** [comment] 2020-12-18 12:18
Thanks @ablax!

**Closed** 2020-12-18 12:18 UTC
Labels: good first issue, kind: bug, type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-29 00:11
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
