### ISSUE TITLE
router.push prefixes links with Vercel's 18n domain

### ISSUE THREAD

**Issue by kmkr** [vercel/next.js#20972] opened 2021-01-11 11:10 UTC
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

12

**What browser are you using?**

Chrome, Firefox (doesn't matter)

**What operating system are you using?**

Linux (don't think it matters)

**How are you deploying your application?**

Vercel

**Describe the Bug**

We're running a multi locale site. Starting from Next 10.0.5, links in the applications are prefixing the locale's domain when we click on them. We have a CDN in front of Vercel, so that's not the intended behavior. 

More specifically:

- We have a CDN serving www.otovo.no, www.otovo.se and others. We do that because only a subset of URLs on that domain are handled by Vercel.
- The CDN forwards some of the traffic to Vercel, and we've setup separate subdomains on Vercel to handle the different locales.
- When clicking on a link on www.otovo.no, for example with href "/about", the user is sent to to the Vercel domain instead of the CDN domain.

The consequence of this bug is that we're incorrectly exposing Vercel's domain to the user and in that subsequent requests go directly to Vercel. 

**Expected Behavior**

When clicking on a link on www.otovo.no, for example with href "/about", the user is staying to the domain they're currently on (in this example www.otovo.no/about).

**To Reproduce**

# Set up an app on Vercel

Set on an app with two locale specific domains, for example "foo.bar.no" and "foo.bar.se"

Set up locale config via `next.config.js`:

```javascript
i18n: {
    localeDetection: false,
    locales: ['nb-NO', 'sv-SE'],
    defaultLocale: 'nb-NO',
    domains: [
        {
            domain: 'foo.bar.no',
            defaultLocale: 'nb-NO'
        },
        {
            domain: 'foo.bar.se',
            defaultLocale: 'sv-SE'
        }
    ]
},
```

# Set up a reverse proxy in front of Vercel

Set up a domain at a reverse proxy in front of Vercel. Send domains "www.bar.no" and "www.bar.se" to that site, and forward them to Vercel's "foo.bar.no" and "foo.bar.se", respectively.

# Create pages in your app

Create an index page in your app: `pages/index.js`. In that, include this button:

```javascript
<button onClick={() => { router.push("/hello"); }} />
```

Create the hello route in your app: `/pages/hello.js`.

Deploy the app, visit www.bar.no and click the link. You're sent to foo.bar.no/hello instead of www.bar.no/hello.

**Comment by ijjk** [comment] 2021-01-15 16:11
Hi, this sounds like the currently expected behavior. The domains configured in the `i18n` config are the ones used when navigating between locales, the config is not aware of the original domains that are being proxied from since they aren't configured. 

It sounds like since you are proxying the requests to Vercel you don't need to leverage the i18n domains feature and can just proxy to the locale path e.g. original locale domain at top-most CDN -> `/${locale}/${path}`. If you didn't have the extra layer between Next.js and Vercel then the domains config would make sense to use here but that doesn't seem to be the case. 

I'm going to close this since it doesn't appear to be a bug and is currently the expected behavior, if you are still encountering problems with this feel free to reply with additional information.

**Closed by ijjk** 2021-01-15 16:11 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
