### ISSUE TITLE
ES Module error with Next.js

### ISSUE THREAD

**Issue by nenadfilipovic** [vercel/next.js#26568] opened 2021-06-24 11:51 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14

### What browser are you using?

Brave

### What operating system are you using?

Linux

### How are you deploying your application?

next start

### Describe the Bug

I am having this error:

```
Error: Must use import to load ES Module: /sandbox/node_modules/@rtk-query/graphql-request-base-query/dist/index.modern.js
require() of ES modules is not supported.
require() of /sandbox/node_modules/@rtk-query/graphql-request-base-query/dist/index.modern.js from /sandbox/.next/server/pages/_app.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.modern.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /sandbox/node_modules/@rtk-query/graphql-request-base-query/package.json.
```
I am trying to import this module [@rtk-query/graphql-request-base-query](https://unpkg.com/browse/@rtk-query/graphql-request-base-query@1.0.3/) into my Next.js app and it throws me error above, I have already contacted author of that module and conclusion is that it is Next.js problem as it is throwing same error inside codesandbox, here is issue https://github.com/reduxjs/redux-toolkit/issues/1176.

### Expected Behavior

It should compile and not throw error.

### To Reproduce

Here: https://codesandbox.io/s/gallant-rosalind-h5d9v

**Comment by housseindjirdeh** [comment] 2021-06-28 20:54
Closing as it's a duplicate

**Closed by housseindjirdeh** 2021-06-28 20:54 UTC
Labels: kind: bug, type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-28 04:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
