### ISSUE TITLE
Configuring `basePath` and using query parameters breaks routing in frontend.

### ISSUE THREAD

**Issue by Lynbarry** [vercel/next.js#19437] opened 2020-11-23 10:51 UTC
# Bug report

## Describe the bug

When configuring the `basePath` in the `next.config.js` and then accessing the index page with a query parameter, the next frontend rewrites the URL in a broken way. The configured `basePath` is appended a second time, so that we are on `/basePath/basePath?foo=bar`, which is not actually a working page.

## To Reproduce

I created a repository here: https://github.com/Lynbarry/next-basepath-bug

All I did in there was use `npx create-next-app` and add a `next.config.js` with the following content:

```
module.exports = {
  basePath: "/basePath",
};
```

To reproduce the behavior:
1. Run `npm run dev`
2. Go to `localhost:3000/basePath?foo=bar`
3. Notice that the URL changes to `localhost:3000/basePath/basePath?foo=bar` in the frontend
4. Reload the page to get a 404

## Expected behavior

Don't add the basePath a second time. The URL should stay `localhost:3000/basePath?foo=bar`

## System information

- OS: macOS
- Browser: chrome, firefox (probably any browser)
- Version of Next.js: 10.0.2
- Version of Node.js: v12.13.1

**Comment by Tomburgs** [comment] 2020-11-23 15:03
I created PR #19444 to fix this, let's hope it gets merged soon :eyes:.

**Comment by acfasj** [comment] 2020-11-29 12:11
@timneutkens @Tomburgs  any workaround for this ? I have an app currently need basePath, and it seems this bugfix would take a while

**Comment by acfasj** [comment] 2020-11-29 12:55
@Tomburgs Thanks for your quick and reliable response

**Closed** 2020-12-30 05:37 UTC
Labels: kind: bug

**Comment by ijjk** [comment] 2020-12-30 17:08
Hi, this has been updated in the latest version of Next.js `v10.0.5-canary.4`, please update and give it a try!

**Comment by Lynbarry** [comment] 2021-01-02 20:57
Thanks a lot! Will give it a try!

**Comment by balazsorban44** [comment] 2022-01-28 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
