### ISSUE TITLE
 Optional catch-all routes enabled but throws error on yarn dev

### ISSUE THREAD

**Issue by dragGH102** [vercel/next.js#17696] opened 2020-10-07 17:22 UTC
# Bug report

## Describe the bug

**./nextjs.config.js**

```
module.exports = {
  experimental: {
    optionalCatchAll: true,
  },
};
```

`yarn dev` shows `Error: Optional catch-all routes are currently experimental and cannot be used by default`

## To Reproduce

1. Clone https://github.com/dragGH102/nextjs-ts-playground (commit: `ad890fe2510d756cbb3f02cc7bcbbdb1b02488f7`)
2. yarn install
3. yarn dev

## Expected behavior

The app should run normally with `yarn dev`

- Version of Next.js: 9.4.2
- Version of Node.js: 12.18.3

**Comment by ijjk** [comment] 2020-10-07 17:25
Hi, the expected filename is `next.config.js` which is why the config isn't being detected. This feature is also enabled by default in the latest version of Next.js https://nextjs.org/docs/routing/dynamic-routes#optional-catch-all-routes

**Comment by ijjk** [comment] 2020-10-07 22:00
I'm going to close this per the previous comment as it's not an issue in Next.js

**Closed by ijjk** 2020-10-07 22:00 UTC

**Comment by balazsorban44** [comment] 2022-01-29 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
