### ISSUE TITLE
Custom attributes like `repo` on Next/Script for using Utterances gives TypeScript error

### ISSUE THREAD

**Issue by deadcoder0904** [vercel/next.js#26236] opened 2021-06-17 03:28 UTC
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

16.1.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

I am using Utterances → https://utteranc.es/ to display comments on my blog & thought of using the new `Script` tag as follows:

```tsx
import Head from 'next/head'
import Script from 'next/script'

export const Comments = () => {
	return (
		<Head>
			<Script
				src="https://utteranc.es/client.js"
				strategy="lazyOnload"
				repo="deadcoder0904/comments.akshaykadam.com"
				issue-term="pathname"
				theme="photon-dark"
				crossorigin="anonymous"
			/>
		</Head>
	)
}
```

I plan to include this `Comments` component under my blog post but it gives **red-squiggly lines** on `repo`.

Idk how to use `Script` tag but the above code seems okay.

The TS error I get in VSCode is:

> Type '{ src: string; strategy: "lazyOnload"; repo: string; "issue-term": string; theme: string; crossorigin: string; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Property 'repo' does not exist on type 'IntrinsicAttributes & Props'.ts(2322)

How do I get it working?

### Expected Behavior

It should work.

### To Reproduce

Just try pasting the above code in a Next.js app :)

**Comment by styfle** [comment] 2021-07-07 17:14
Closing, see https://github.com/vercel/next.js/pull/26290#issuecomment-875660337

**Closed by styfle** 2021-07-07 17:14 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 03:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
