### ISSUE TITLE
The app renders twice when using rewrites in `next.config.js`

### ISSUE THREAD

**Issue by meotimdihia** [vercel/next.js#27224] opened 2021-07-16 10:34 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14

### What browser are you using?

chrome

### What operating system are you using?

Windows, Linux

### How are you deploying your application?

yarn dev, yarn build && yarn start

### Describe the Bug

The app renders twice when using rewrites in `next.config.js`. This is the demo: 
https://stackblitz.com/edit/github-xxgqsj?file=next.config.js

### Expected Behavior

It should render once only

### To Reproduce

```js
const moduleExports = {
  async rewrites() {
    return [
      {
        source: '/index2',
        destination: '/index3'
      }
    ];
  }
};

module.exports = moduleExports;
```

**Comment by ijjk** [comment] 2021-07-16 13:20
Hi, this is currently expected since the page being rewritten to is an automatically statically optimized page which means we need to ensure we parse the rewrites on the client and collect any params after hydration so that they can be provided in `router.query`. 

I'm going to close this since it doesn't appear to be a bug

**Closed by ijjk** 2021-07-16 13:20 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 02:16
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
