### ISSUE TITLE
Strange error `Cannot read property '__html' of undefined`, when using AMP on a page

### ISSUE THREAD

**Issue by himanshu-dhiman26** [vercel/next.js#9903] opened 2020-01-02 07:45 UTC
Hi, 

I am facing an issue in my code while trying to make a page AMP. 

Here are the code samples:

`next.config.js`

```
const withOffline = require('next-offline');
const withCSS = require('@zeit/next-css');

module.exports = withOffline(withCSS({
    webpack(config) {
        config.module.rules.push({
            test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
            use: {
                loader: 'url-loader',
                options: {
                    limit: 100000,
                    name: '[name].[ext]',
                },
            },
        });
        return config;
    },
    transformManifest: (manifest) => ['/'].concat(manifest),
    workboxOpts: {
        swDest: 'service-worker.js',
        runtimeCaching: [
            {
                urlPattern: /^https?.*/,
                handler: 'NetworkFirst',
                options: {
                    cacheName: 'https-calls',
                    networkTimeoutSeconds: 15,
                    expiration: {
                        maxEntries: 150,
                        maxAgeSeconds: 30 * 24 * 60 * 60, // 1 month
                    },
                    cacheableResponse: {
                        statuses: [0, 200],
                    },
                },
            },
        ],
    },
}));
```

AMP page: `pages/amp.js`

```
export const config = { amp: true }

function Amp(props) {
    return <h3>My AMP Page!</h3>
}

export default Amp
```

**Expected result :**
Should be an AMP powered page

**Outcome receiving:**
![Screenshot 2020-01-02 at 1 14 25 PM](https://user-images.githubusercontent.com/39363104/71656600-d6f9e380-2d61-11ea-8626-d1316f36319b.png)

Let me know if anything more is required to get more clarity.

**Comment by Timer** [comment] 2020-09-03 02:28
Closing as no reproduction provided.

**Closed by Timer** 2020-09-03 02:28 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
