### ISSUE TITLE
Suddently can't build "Can't resolve ffmpeg-static"

### ISSUE THREAD

**Issue by Glutch** [vercel/next.js#23440] opened 2021-03-26 23:09 UTC
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

15.4.0

### What browser are you using?

chrome

### What operating system are you using?

macos / vercel

### How are you deploying your application?

vercel

### Describe the Bug

npm run build results in

"ModuleNotFoundError: Module not found: Error: Can't resolve 'ffmpeg-static' in '/Users/glutch/Documents/dev/javascript/xxx/node_modules/prism-media/src/core'"

Recently i just added markdown-it, then it started crashing. But removing markdown-it, node_modules and re-installing makes no difference. I have no idea what ffmpeg-static or "prism-media" is.

How can i solve this?

These are my dependencies
```
"dependencies": {
    "@sendgrid/mail": "^7.4.2",
    "discord.js": "^12.5.1",
    "markdown-it": "^12.0.4",
    "moment": "^2.29.1",
    "mongoose": "^5.11.20",
    "next": "10.0.8",
    "next-auth": "^3.11.2",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "styled-components": "^5.2.1"
  },
  "peerOptionalDependencies": {
    "mongodb": "^3.6.0"
  },
  "devDependencies": {
    "babel-plugin-styled-components": "^1.12.0"
  }
```

### Expected Behavior

To build

### To Reproduce

if i knew i wouldnt be having this problem

**Comment by timneutkens** [comment] 2021-03-30 08:16
Please add a complete reproduction.

**Comment by ijjk** [comment] 2021-04-28 02:33
Closing as no actionable information was provided, if you are still encountering this please respond with additional information to allow investigating!

**Closed by ijjk** 2021-04-28 02:33 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-28 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
