### ISSUE TITLE
Expose i18n data in DocumentContext

### ISSUE THREAD

**Issue by IskanderMustafin** [vercel/next.js#18667] opened 2020-11-02 13:10 UTC
# Feature request

I'm creating this feature request in continuation of [this](https://github.com/vercel/next.js/discussions/18329) discussion for easier tracking and in order not to forget.

Right now I18n feature automatically adds `lang` attribute to the `<html>` tag.
It's cool but there more cases when current `locale` can be handy in `DocumentContext`. 

In discussion mentioned above people have different reasons why they need it, but in my concrete case I need to do following: 
- detect if it's RTL or LTR `direction` based on current locale. And add it as `dir` attribute to the `<html>` tag;
- include Intl polyfill for current locale: 
```
 const polyfill = `https://cdn.polyfill.io/v3/polyfill.min.js?features=Intl.~locale.${locale}`;
...
<script src={polyfill} />
```

As fow now I'm using a bit hacky and less idiomatic way of setting direction in `_app.tsx`: 
```
const langDir = getLangdirByLocale(locale);
...
<div dir={langDir}>
    <Component {...pageProps} />
</div>
```

## Describe the solution you'd like
Please provide `locale`, `defaultLocale` and `locales` properties in `DocumentContext`. I.e. in same way as it done in `GetServerSidePropsContext` and `GetStaticPropsContext`.

**Comment by dmitrykozyrenko** [comment] 2020-11-04 08:20
@IskanderMustafin current locale already available as prop in document, check `this.props`

**Comment by IskanderMustafin** [comment] 2020-11-04 09:59
@dmitrykozyrenko  thanks a lot, it works!

**Comment by santialbo** [comment] 2020-11-16 08:43
I would like to #18329 as a reference for more examples.

Would you consider reviewing a PR adding `locale`, `locales` and `defaultLocale` to the `NextPageContext` type?

**Comment by ijjk** [comment] 2021-09-21 03:20
Closing as this was updated in https://github.com/vercel/next.js/pull/21930 which is available in the latest version of Next.js `v11.1.2`, please update and give it a try!

**Closed by ijjk** 2021-09-21 03:20 UTC
Labels: kind: story

**Comment by balazsorban44** [comment] 2022-01-27 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
