### ISSUE TITLE
Support sitemap and rss pages.

### ISSUE THREAD

**Issue by marcofranssen** [vercel/next.js#20736] opened 2021-01-04 11:43 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

There is currently no support for pages other than react rendered pages. It would be great if we can utilize serverside and static page rendering for RSS/Atom feeds and sitemaps.

## Describe the solution you'd like

It would be great if RSS/Atom feeds and sitemaps can be implemented using `getStaticProps` and `getStaticPaths` to fully utilize **Next.js** capabilities of static page rendering and server side rendering.

## Describe alternatives you've considered

Have a separate script to build the rss feeds and sitemaps outside of next.js and statically generate them deploy time. This doesn't work for content dynamically updated after deploy, causing those files to be outdated until the next deploy.

## Additional context

Not relevant.

**Comment by Timer** [comment] 2021-01-04 20:28
duplicate of #15508

**Closed by Timer** 2021-01-04 20:28 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
