### ISSUE TITLE
Armv7 support for @next/swc

### ISSUE THREAD

**Issue by melsiir** [vercel/next.js#33804] opened 2022-01-30 09:36 UTC
### Describe the feature you'd like to request

Please add armv7 support for@next/swc !

https://www.npmjs.com/package/@swc/core-android-arm-eabi

### Describe the solution you'd like

Just add this binary to nextjs

https://www.npmjs.com/package/@swc/core-android-arm-eabi

### Describe alternatives you've considered

I use babel for now

**Comment by balazsorban44** [comment] 2022-01-30 11:59
Duplicate of #33530

**Closed by balazsorban44** 2022-01-30 11:59 UTC
Labels: template: story

**Comment by melsiir** [comment] 2022-01-30 14:15
> Duplicate of #33530

Sir you don't do anything about my request you just keep throws it must get view by next developers !

**Comment by balazsorban44** [comment] 2022-02-02 23:18
Thank you for your concern. I am a "next developer". We are looking into every single issue, but opening the same issue multiple times does not increase the likelihood of being considered immediately. On the contrary, it gives the slight impression of impatience and produces maintenance overhead.

I converted your initial issue to a discussion (Idea) since we are doing the same with all feature requests. We try to prioritize feature requests based on community engagement, as it indicates more widespread interest for a feature.

See our values in the [Code of Conduct](https://github.com/vercel/next.js/blob/canary/CODE_OF_CONDUCT.md)
