### ISSUE TITLE
onClick event is triggered with delay on touchable devices

### ISSUE THREAD

**Issue by deebov** [vercel/next.js#10524] opened 2020-02-13 20:18 UTC
# Bug report

## Describe the bug

onClick event is triggered with 200-250ms delay on touchable devices. If I change onClick, for example, to onTouchEnd it works as usual ( without delay )

## To Reproduce

Please go to this codesandbox https://codesandbox.io/s/vigorous-torvalds-p8154?fontsize=14&hidenavigation=1&theme=dark

Open the preview window in a new tab
Switch to mobile debugger via devtools
Press the element and you should be able to notice the delay
If not try to track the performance

## Expected behavior

onClick is triggered immediately on touchable devices

**Comment by hugentobler** [comment] 2020-03-26 02:47
Same problem.

**Comment by Timer** [comment] 2020-09-10 19:35
Closing this as it's a very common problem on the web with well documented solutions:
https://stackoverflow.com/questions/12238587/eliminate-300ms-delay-on-click-events-in-mobile-safari

**Closed by Timer** 2020-09-10 19:35 UTC

**Comment by balazsorban44** [comment] 2022-01-29 13:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
