### ISSUE TITLE
Server start always generates new `.gitignore` & `.vscode/settings.json`

### ISSUE THREAD

**Issue by NuroDev** [vercel/next.js#41966] opened 2022-10-27 12:09 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: 7.13.4
    Relevant packages:
      next: 13.0.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

With the release of v13 every time a command / script is run, whether that be `dev`, `build`, etc, Next.js will always generate a new `.gitignore` & `.vscode/settings.json` file.

Not breaking in anyway but really not needed. Especially when using a monorepo, like Turborepo & I already have these files top level so Next.js is just generating extra files that are not needed.

### Expected Behavior

Either not generate them at all (Though I know there is of course a reason to actually provide these files / config to users) or not generate them if it is (somehow) detected to be running inside a monorepo.

### Link to reproduction

https://codesandbox.io/s/next-vscode-settings-generation-bug-c9ouvj?file=/package.json

### To Reproduce

Create a new Next.js project & run either `next dev` or `next build` & it will generate a new `.gitignore` if one does not already exist or append `.vscode` to your existing `.gitignore` & similarly either create or append to `.vscode/settings.json`

**Comment by milanbgd011** [comment] 2022-10-27 19:05
+1

Also, it OVERWRITES my .vscode/settings.json corrupting my entire layout and settings for VS CODE. 

I suppose that the script should check if needed params are present, if not then "append" to the end of JSON, not replace entire settings.json file..

**Comment by balazsorban44** [comment] 2022-10-27 20:58
Duplicate of #41808

**Closed by balazsorban44** 2022-10-27 20:58 UTC
Labels: template: bug
