### ISSUE TITLE
In API folder if i pass data in body, it's not recognizing headers and returning as null

### ISSUE THREAD

**Issue by Raghu-M-S** [vercel/next.js#50160] opened 2023-05-22 12:38 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
- error Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:372:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse._res.setHeader (D:\devlopment\viz-frontend\node_modules\next\dist\server\base-server.js:300:24)
    at sendJson (D:\devlopment\viz-frontend\node_modules\next\dist\server\api-utils\node.js:226:9)
    at ServerResponse.apiRes.json (D:\devlopment\viz-frontend\node_modules\next\dist\server\api-utils\node.js:445:31)
    at handler (webpack-internal:///(api)/./pages/api/project-list.js:56:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  digest: undefined
}
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error undefined {
  error: {},
  url: 'http://localhost:3000/api/auth/session',
  message: undefined
}
```

### Link to the code that reproduces this issue or a replay of the bug

create-next-app

### To Reproduce

import axios from "axios";
import { getSession } from "next-auth/react";

export default async (req, res) => {
  // const bodyData = req.body;
  // console.log("bodyData", bodyData);
  const session = await getSession({ req });
  console.log("session in list api", session);

  if (req.method === "POST") {
    if (!session?.accessToken) {
      res.status(401).json({ error: "Unauthorized" });
      return;
    }
    let a = {
      project_name: "name",
      camera_type: "camera",
      accessibility: 1,
    };
    try {
      const response = await fetch(
        `${BASE_URL}/apiname`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${session?.accessToken}`,
          },
          body: a,
        }
      );
      console.log("response", response.status);
      res.status(200).json({ message: response });
    } catch (error) {
      res.status(500).json({ error: error });
    }
  }
};

### Describe the Bug

we can't access token from next-auth if we pass data in body

### Expected Behavior

It must accept both headers and body data inside api 

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

vercel

**Comment by balazsorban44** [comment] 2023-05-22 13:37
This looks like an issue better reported in https://github.com/nextauthjs/next-auth not in the Next.js repo. Regardless, check out https://next-auth.js.org/configuration/nextjs#getserversession for server-side authentication instead of `getSession`.

It's hard to give more advice without a reproduction, but this does not seem like a bug in either Next.js or NextAuth.js, so I'm closing.

If you have project-specific questions, try [Next.js discussions](https://github.com/nextauthjs/next-auth/discussions/new?category=questions) or the [Next.js Discord](https://discord.com/invite/nextjs)

**Closed by balazsorban44** 2023-05-22 13:37 UTC
Labels: template: bug
