### ISSUE TITLE
Putting `_document.tsx` inside `./src/pages` causes error

### ISSUE THREAD

**Issue by amir-mln** [vercel/next.js#29343] opened 2021-09-23 23:44 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.15.3

### What browser are you using?

chrome

### What operating system are you using?

windows

### How are you deploying your application?

Other

### Describe the Bug

So based on the [Docs](https://nextjs.org/docs/advanced-features/src-directory), we can use `./src/pages/` instead of `./pages/`. Everything is fine when i do this but as I put the `_document.tsx` inside `./src/pages/` i get this error:

```
next/document should not be imported outside of pages/_document.js
```

So far I'm disabling this with comment (`// eslint-disable-next-line @next/next/no-document-import-in-page
`). But this shouldn't give error since `./src/pages/_document.tsx` and `./pages/_document.tsx` are the same. Aren't they?

### Expected Behavior

I'm simply expecting to receive no error.

### To Reproduce

Just put the `_document` inside `./src/pages/`.

**Comment by ijjk** [comment] 2021-09-24 00:00
Hi, this is a duplicate of https://github.com/vercel/next.js/issues/29021 which is fixed in the latest canary, please update to the latest version of the eslint configs as mentioned [here](https://github.com/vercel/next.js/issues/29021#issuecomment-919143079)

**Closed by ijjk** 2021-09-24 00:00 UTC
Labels: type: example, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
