### ISSUE TITLE
`next/export` will not work with `Image` when using `unoptimized`

### ISSUE THREAD

**Issue by thathurtabit** [vercel/next.js#27231] opened 2021-07-16 13:40 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.15.5

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next export

### Describe the Bug

When running `next export` using the `Image` from `next/image`, I set the `unoptimized` prop on `Image`, but still get the following error meaning I cannot export my app.

```
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
  Possible solutions:
    - Use `next start` to run a server, which includes the Image Optimization API.
    - Use any provider which supports Image Optimization (like Vercel).
    - Configure a third-party loader in `next.config.js`.
    - Use the `loader` prop for `next/image`.
```

Also, using normal JSX img gives error saying `next/image` must be used instead.

### Expected Behavior

`next export` using `next/image` will work when `<Image unoptimized ... />` prop is added.

### To Reproduce

Use `Image` with `unoptimized` set (to true) from `next/image` and run `next build && next export`

**Comment by styfle** [comment] 2021-07-28 15:42
The default loader is not compatible with `next export`.

You'll need to set `images.loader: 'custom'` in `next.config.js` in order to use `next export`.

Try it out on the canary channel with `yarn add next@canary`.

**Comment by thathurtabit** [comment] 2021-07-29 17:58
@styfle thanks for the response. Does that mean that the [unoptimized]( https://nextjs.org/docs/api-reference/next/image#unoptimized) prop doesn't do all that much?

Also, for users wanting to make use of `next export`, it will mean they get the error: `Error: Do not use <img>. Use Image from 'next/image' instead` if they use a standard `img` tag.

They'll need to do something like the below in their `.eslintrc`

```
{
  // ...
  "rules": {
    // Other rules
    "@next/next/no-img-element": "off"
  }
}
```

I guess ideally it should be easier for people to use standard `img` or `picture` tags if they prefer. 👍

**Comment by styfle** [comment] 2021-07-29 19:25
The `unoptimized` prop is per <Image> usage so one image might be optimized and another might be unoptimized.

Since `next export` can't know if all <Image> usages have `unoptimized` enabled without running the app (imagine this is dynamically passed in as a variable), you'll need to use `images.loader: 'custom'`.

That said, the lint rule is still valid and you should use a custom [`loader`](https://nextjs.org/docs/api-reference/next/image#loader) prop with an upstream image optimization service when using `next export` OR use `next start` with the default loader.

**Comment by klujanrosas** [comment] 2021-08-05 15:32
Even setting `images.loader` to `custom` is not doing it for me, not sure why

```
Error: Specified images.loader should be one of (default, imgix, cloudinary, akamai), received invalid value (custom).
See more info here: https://nextjs.org/docs/messages/invalid-images-config
    at assignDefaults (/home/kenneth/kw/next-applet-boilerplate/node_modules/next/dist/next-server/server/config.js:5:4744)
    at loadConfig (/home/kenneth/kw/next-applet-boilerplate/node_modules/next/dist/next-server/server/config.js:8:878)
    at async Span.traceAsyncFn (/home/kenneth/kw/next-applet-boilerplate/node_modules/next/dist/telemetry/trace/trace.js:6:584)
    at async /home/kenneth/kw/next-applet-boilerplate/node_modules/next/dist/export/index.js:3:126
    at async Span.traceAsyncFn (/home/kenneth/kw/next-applet-boilerplate/node_modules/next/dist/telemetry/trace/trace.js:6:584)
```

**Comment by klujanrosas** [comment] 2021-08-05 15:33
Even setting `images.loader: custom` does not work as expected. I'm getting:
```
Error: Specified images.loader should be one of (default, imgix, cloudinary, akamai), received invalid value (custom).
See more info here: https://nextjs.org/docs/messages/invalid-images-config
```

**Comment by styfle** [comment] 2021-08-05 16:26
@klujanrosas Please try `yarn add next@canary`

**Comment by leerob** [comment] 2021-08-12 03:21
Closing as this has been resolved with `11.1` as mentioned above (no longer on canary channel, but stable) 👍

**Closed by leerob** 2021-08-12 03:21 UTC
Labels: template: bug

**Comment by Cesarioo** [comment] 2021-12-27 20:10
Hi, it seems this issue is still ongoing for me and I have the latest version. 

Error:` Image Optimization using Next.js' default loader is not compatible with `next export`.
  Possible solutions:
    - Use `next start` to run a server, which includes the Image Optimization API.
    - Use any provider which supports Image Optimization (like Vercel).
    - Configure a third-party loader in `next.config.js`.
    - Use the `loader` prop for `next/image`.

How can I solve this issue ?

**Comment by styfle** [comment] 2022-01-12 17:43
@Elir-Mahad 

```js
module.exports = {
  assetPrefix: !debug ? "/notes/" : "",
  images: { loader: "custom" },
};
```

**Comment by Elir-Mahad** [comment] 2022-01-14 04:33
@styfle
Thanks 👍🏾

**Comment by balazsorban44** [comment] 2022-02-13 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
