### ISSUE TITLE
Custom Document not working with Next.js 13 + Edge

### ISSUE THREAD

**Issue by elizabeth-dev** [vercel/next.js#42125] opened 2022-10-29 10:58 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

$ /fakepath/repro-nextjs/node_modules/.bin/next info

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Wed, 26 Oct 2022 15:25:45 +0000
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 13.0.1-canary.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

When using a custom `_document` on Next.js 13 while using the experimental Edge runtime, the server fails at runtime with the error:
```
[TypeError: Cannot destructure property 'inAmpMode' of '(0 , _react).useContext(...)' as it is null.]
```
This worked with Edge under Next.js 12, and without Edge under Next.js 13.

### Expected Behavior

The page loads correctly with the settings defined in the custom document.

### Link to reproduction

https://github.com/elizabeth-dev/repro-nextjs

### To Reproduce

Add a custom `_document` file to the `pages` directory and enable the experimental Edge runtime in the `next.config.js` file.

**Comment by eolme** [comment] 2022-10-30 19:56
IThe problem is that esm alias (#41034) does not work correctly and and different html contexts are used

**Comment by ericmatthys** [comment] 2022-11-23 16:55
Fixed by https://github.com/vercel/next.js/pull/43192

**Comment by ijjk** [comment] 2022-11-23 20:08
Closing as mentioned above this should now be fixed

**Closed by ijjk** 2022-11-23 20:08 UTC
Labels: template: bug
