### ISSUE TITLE
[NEXT-1129] using nextjs `redirect()` function causes flashing UI

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#49424] opened 2023-05-08 00:41 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Tue Apr 25 04:07:22 PDT 2023; root:xnu-8796.121.2~8/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.18
      pnpm: 7.1.0
    Relevant packages:
      next: 13.4.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/Fredkiss3/bug-next-redirect-flashing-ui

### To Reproduce

Go to the app, submit the form by clicking on the button, you will see the UI flash everytime there is a redirect. 
You can also click on the link and in the first navigatino you will see that the ui will flash.

### Describe the Bug

You can see in the video below, the UI flashes when we use redirect either within a server action or during a client navigation with `<Link>` :

https://user-images.githubusercontent.com/38298743/236710727-7ba6a40e-d6a1-403f-94d2-5cefebd73c0c.mov

### Expected Behavior

There should not be flash in the UI, and i don't know there is in the first place, one thing though is that if you use `revalidatePath(...)` in the action instead of `redirect(...)`, you will see the UI update in place without any flash, you can see in the video attached : 

```tsx
import { revalidatePath } from "next/cache";

export default function Home() {
  async function action() {
    "use server";
    revalidatePath("/");
  }
  return (
    <main>
      <h1>Flashing UI ? {new Date().valueOf()} </h1>
      <form action={action}>
        <button>Revalidate with form</button>
      </form>
    </main>
  );
}

```

https://user-images.githubusercontent.com/38298743/236711147-ad6a8ee2-cc64-4b78-ad57-4693a88a17e7.mov

<sub>[NEXT-1129](https://linear.app/vercel/issue/NEXT-1129/using-nextjs-redirect-function-causes-flashing-ui)</sub>

**Comment by asimplify** [comment] 2023-05-08 08:27
You are using onclick event on server component which cuases your whole page to rereder. You may wanna try "use client" on the component. Refer to docs for more clarification   []("https://nextjs.org/docs/getting-started/react-essentials")

**Comment by Fredkiss3** [comment] 2023-05-11 11:26
Tested in production, I still have the flashing UI. 
I use `redirect` as it works great for form handling without JS, if you disable JS, and use `revalidatePath` when you submit the form, multiple times your browser will show you the confirm dialog to submit again. I just want to avoid multiple unwanted submissions by the user on every page reload.

Besides `redirect` also does invalidation of the current page I think.

**Comment by activenode** [comment] 2023-05-11 11:27
Can you determine what causes the flash? Like in my case it was clearly the layout.css being updated with `layout.css?v=1234...` . What happens in the network that might cause the flash?

**Comment by Fredkiss3** [comment] 2023-05-11 11:31
Is is how the redirect is handled, 
You can see that there is a PR that adresses this : https://github.com/vercel/next.js/pull/49439

> This PR fixes the flickering when a redirect was caught on the client-side.

> This was caused by the redirect error boundary catching the error and rendering a component that would trigger the redirect via a router dispatch but then return null. It was probably written this way to avoid re-rendering the children and causing that component to run again and trigger an infinite redirect loop.

**Comment by activenode** [comment] 2023-05-11 11:33
Missed that one, thanks for the hint, good to know! I misread the first comment about it potentially happening with `revalidatePath` instead of `redirect` which is what I adressed. Thanks.

**Comment by h3rmanj** [comment] 2023-07-11 13:28
I'm running into this as well. Looking at the network log, it seems the action that revalidates, returns empty content which makes the client throw out all UI, before getting the new UI in a new call to the server.
![image](https://github.com/vercel/next.js/assets/11387548/4366c845-e035-4dbd-89e0-2b432d299784)

Ironically, disabling javascript on the client results in a better user experience, because the actions returns a `303`, meaning the browser doesn't switch out the UI before it actually has it in the next request;
![image](https://github.com/vercel/next.js/assets/11387548/0334fd0b-a115-43d0-be02-2f8340b9acc2)

Seems to be that progressive enhancement is failing here. I feel like when next knows a server action result in a redirect, it should be able to return the result of that redirect in the same response, thereby removing a network waterfall.

**Comment by Fredkiss3** [comment] 2023-07-11 14:01
It seems, it will be fixed by a react update : 

from the PR: 
> we have a better alternative from React coming soon ish, so closing this

**Comment by ogmzh** [comment] 2023-08-05 20:54
I can confirm, happens to me as well. Very noticeable if you have a dark themed app and the screen will just flash white for a millisecond while revalidating (epilepsy warning)

**Comment by baked-dev** [comment] 2023-08-12 19:35
@timneutkens can we just make it return the loading.tsx from the redirect instead of returning null? at least until the react Catch component is ready? That PR seems rather stale at the moment and the redirect flashing is becoming more and more of a pain point for us

**Comment by NemanjaJupiterLabs** [comment] 2023-09-22 09:47
I have the same problem. I want to redirect to an external link and my website is flashed for a second.

I am trying to redirect inside of page.tsx after I fetch some data.

I have this in code:
export const dynamic = 'force-static'
export const revalidate = 300
....
const [someData] = await Promise.all(apiCalls)
  if (condition) {
    redirect('https://www.google.com', RedirectType.replace)
  }
  ...
    return (
    <Layout layoutProps={...} modalsProps={...}>
      <SectionsContainer sections={sections} />
    </Layout>
  )

**Comment by balazsorban44** [comment] 2023-09-28 15:57
Hi, this should have been fixed on newer versions, please upgrade and let us know! Feel free to open a new issue if you still experience this.

**Closed by balazsorban44** 2023-09-28 15:57 UTC
Labels: template: bug, area: app, linear: next

**Comment by Fredkiss3** [comment] 2023-09-28 23:30
Hi @balazsorban44 , the bug is indeed fixed but only for server actions, when using link navigation, it still shows a flash of white before redirecting to the correct route, at least on the first navigation. 

https://github.com/vercel/next.js/assets/38298743/415037db-31a9-4cde-9b13-4f7c6eb99c3a

**Comment by 4lejandrito** [comment] 2023-10-01 06:51
Hi! I observe the same as @Fredkiss3. When using redirect inside a server page from a link navigation the flashing still occurs.
