### ISSUE TITLE
segfault running custom next server within jest unit test after upgrading nextjs 11 -> 12

### ISSUE THREAD

**Issue by Kauabunga** [vercel/next.js#33008] opened 2022-01-05 02:03 UTC
### Run `next info` (available from version 12.0.8 and up)

N/A

### What version of Next.js are you using?

11.1.3 + 12.0.7

### What version of Node.js are you using?

16.13.1

### What browser are you using?

N/A

### What operating system are you using?

macOS

### How are you deploying your application?

N/A

### Describe the Bug

Within a custom server application there are some unit tests using the jest framework along with supertest to mimic http requests [(See replication repo)](https://github.com/Kauabunga/nextjs-replicate-segfault-custom-server-v12). This has been working as expected up until trying to upgrade to multiple 12.X nextjs versions including `12.0.0`, `12.0.1`, and `12.0.7`.

When running version 12 with a `next.config.js` configuration present and a custom server with `dev: false`, the jest execution exits with a segfault when calling `app.prepare()`.

```javascript
const app = next({
      dev: false,
});

await app.prepare(); // Goes 💥
```

```sh
zsh: segmentation fault  npm test
```

It is possible to workaround this issue by importing the nextjs config manually and passing it as the `conf` option to the custom next application.

example workaround

```javascript
const app = next({
      dev: false,
      conf: require('./next.config'), // this fixes the seg fault
});

await app.prepare(); // No 💥 this time

await request(app.getRequestHandler())
      .get("/")
      .expect(200);
```

### Expected Behavior

I would expect this not to crash and nextjs to be able to resolve the `next.config.js` automatically without the conf option

### To Reproduce

I have published a public GitHub repo that reproduces the following scenarios along with setup instructions

[https://github.com/Kauabunga/nextjs-replicate-segfault-custom-server-v12](https://github.com/Kauabunga/nextjs-replicate-segfault-custom-server-v12)

1. [✓] jest unit test with version 11.1.3 without a `next.config.js`
2. [✓] jest unit test with version 11.1.3 with a `next.config.js`
3. [✓] jest unit test with version 12.0.7 without a `next.config.js`
4. [✗] jest unit test with version 12.0.7 with a `next.config.js`
5. [✓] jest unit test with version 12.0.7 with a `next.config.js` with custom server options `conf: require('next.config')`
6. [✗] jest unit test with version canary with a `next.config.js` and `segfault-handler`

**Comment by peterbe** [comment] 2022-01-05 21:25
Me too! I'm trying next 12.0.7 with Node 17 and 16. Your fix solved it. Except, instead of `require()` I use:
```js
import conf from '../next.config.js'
...
export const nextApp = next({ dev: isDevelopment, conf })
```
and now, 100% less seg faults.

**Comment by ide** [comment] 2022-01-11 17:36
It looks like error comes from here: https://cs.github.com/v8/v8/blob/17a99fec258bcc07ea9fc5e4fabcce259751db03/src/runtime/runtime-module.cc?q=RunHostImportModuleDynamicallyCallback+DynamicImportCall#L43-L44

I haven't looked very closely at it since this isn't an urgent/significant issue for me but I suspect using d8 will be helpful to inspect program state since the call stack is in an async/await trampoline.

**Comment by khasty720** [comment] 2022-01-18 21:30
Same issue reported here https://github.com/vercel/next.js/issues/31162

**Comment by balazsorban44** [comment] 2022-01-19 12:11
Duplicate of #31162

**Closed by balazsorban44** 2022-01-19 12:11 UTC
Labels: template: bug
