### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client when using getStaticProps

### ISSUE THREAD

**Issue by mmahalwy** [vercel/next.js#14577] opened 2020-06-26 06:10 UTC
# Bug report

## Describe the bug
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client when using `getStaticProps`. See component below:
```typescript
const Profile = ({ profileId }) => {
  console.log('log');
  return <div>hello</div>;
};

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: [],
    fallback: true,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  return {
    props: {},
  };
};

export default Profile;
```

This seems to only happen if there is a miss on `getStaticPaths` where the param is not present. I also see a few times where the `console.log` is called on on SSG

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to localhost:3000/profile
2. See console error in terminal

## Expected behavior
Should not throw error.

## Screenshots
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:526:11)
    at DevServer.sendHTML (/Users/mmahalwy/Desktop/code/startups/shepherd/shepherd-landing/node_modules/next/dist/server/next-dev-server.js:23:5)
    at DevServer.render (/Users/mmahalwy/Desktop/code/startups/shepherd/shepherd-landing/node_modules/next/dist/next-server/server/next-server.js:49:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.fn (/Users/mmahalwy/Desktop/code/startups/shepherd/shepherd-landing/node_modules/next/dist/next-server/server/next-server.js:35:852)
    at async Router.execute (/Users/mmahalwy/Desktop/code/startups/shepherd/shepherd-landing/node_modules/next/dist/next-server/server/router.js:28:28)
    at async DevServer.run (/Users/mmahalwy/Desktop/code/startups/shepherd/shepherd-landing/node_modules/next/dist/next-server/server/next-server.js:44:494)
    at async DevServer.handleRequest (/Users/mmahalwy/Desktop/code/startups/shepherd/shepherd-landing/node_modules/next/dist/next-server/server/next-server.js:13:133) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

```

## System information

- OS: macOS
- Version of Next.js: ^9.4.4
- Version of Node.js: 12.16.0

**Comment by balazsorban44** [comment] 2020-06-26 07:12
Fixed on canary, either update to that, or wait for it to get into stable :)

https://github.com/vercel/next.js/issues/14489#issuecomment-648063368

**Closed** 2020-06-26 13:07 UTC

**Comment by balazsorban44** [comment] 2022-01-30 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
