### ISSUE TITLE
next/image webp not falling back for some unsupported browser

### ISSUE THREAD

**Issue by AmazingDevTeam** [vercel/next.js#18681] opened 2020-11-02 14:44 UTC
# Bug report

## Describe the bug

next/image (WebP) not falling back to .jpg/.png for unsupported browser.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. git clone [Image Component Example](https://github.com/vercel/next.js/tree/canary/examples/image-component)
2. npm run dev
3. Use iphone to access http://ip:3000 (same network)

## Expected behavior

Should be able to fall back to show vercel.png instead of a blank area.

## Screenshots

**iPhone6 iOS 11**
![iPhone6](https://user-images.githubusercontent.com/56999169/97880777-8cb80900-1d5c-11eb-8d2b-a1990e0b2827.gif)

**iPhone11 iOS 11**
![iPhone11](https://user-images.githubusercontent.com/56999169/97880820-95a8da80-1d5c-11eb-83d7-0be8f9397e16.gif)

## System information

- OS: [e.g. iOS <= 11]
- Browser (if applies) [e.g. safari (iPhone 6 to 11)]
- Version of Next.js: [e.g. 10.0.0]
- Version of Node.js: [e.g. v14.4.0]

**Comment by wilbsy** [comment] 2020-11-09 21:28
Any movement on this?

Same issue in desktop Safari <= 11.1, OSX <= HighSierra (I realize it's an old browser version, but unfortunately it's the browser one of my current clients uses).  

Screen recording if it's helpful: 
 https://drive.google.com/file/d/1J_Y6QSmywDR2-sawWaVBXZgYYTVRtggZ/view?usp=sharing

Thanks!

**Comment by styfle** [comment] 2020-11-09 22:22
This should be fixed on canary.

Can you confirm by trying [the example](https://github.com/vercel/next.js/tree/canary/examples/image-component) locally or visit https://image-component.nextjs.gallery with your old device?

**Comment by styfle** [comment] 2020-11-09 23:17
Confirmed, it was fixed in PR #18868

**Closed by styfle** 2020-11-09 23:17 UTC
Labels: kind: bug, point: 3

**Comment by mattjis** [comment] 2020-11-10 02:38
@styfle that https://image-component.nextjs.gallery example does not work for me in Safari

**Comment by wilbsy** [comment] 2020-11-10 19:17
Woohoo!  It's working for me now...  @styfle  Thanks!

**Comment by mattjis** [comment] 2020-11-11 01:18
> Woohoo!  It's working for me now...  @styfle  Thanks!

I see no change.. is this really fixed

**Comment by mglavall** [comment] 2020-11-11 08:43
I also see no change, it works if I deactive lazyloading, but if I don't, it's not aware that I'm not on IE

**Comment by styfle** [comment] 2020-11-12 14:46
Its likely extensions causing issues. Try using Safari with default preferences.

See https://github.com/vercel/next.js/issues/19038#issuecomment-725738537

**Comment by mattjis** [comment] 2020-11-12 14:49
@styfle you're right. It was my only content blocker [Wipr](https://giorgiocalderolla.com/wipr.html)

**Comment by Timer** [comment] 2020-11-17 17:20
Wipr has fixed their block list:
https://twitter.com/mipstian/status/1328747255407448064

**Comment by balazsorban44** [comment] 2022-01-29 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
