### ISSUE TITLE
Triggering `validateDOMNesting` causes `Hydration failed`

### ISSUE THREAD

**Issue by icyJoseph** [vercel/next.js#36765] opened 2022-05-09 08:47 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```shell

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.9.0
      npm: 7.21.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.3
      react: 18.1.0
      react-dom: 18.1.0
```

### Describe the Bug

Any invalid DOM structure causes `hydration` problems. I presume this is a React bug, but I don't have the time to collect more evidence, other than I can trigger this in Next.js, if other SSR frameworks show the bug, then it must definitely be upstream to React itself.

> One can argue that this is expected behaviour as well, but that invalid DOM nesting should throw while doing SSR, is not documented anywhere.

```tsx
import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <p>
      <p>Hello</p>
    </p>
  );
};

export default Home;
```

Take the above for instance, or a table without proper tags, and in general any DOM validation problems that trigger a message like: `Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.`, or any that applies.

Both with `next dev`, and `next build && next start` this result in React errors, that claim mismatched DOM nodes.

It seems that the server side rendering expects and error boundary to catch this validation errors, but none happens on the client, so the claim is made. Note that both errors (invalid nesting and mismatched UI) are logged.

### Expected Behavior

The error/warnings should still be logged, but the HTML should be produced, although it is invalid.

Or, alternatively, this behaviour should be document somewhere.

### To Reproduce

1. `yarn create next-app test-app --typescript`
2. Fill `pages/index.tsx` with:
```tsx
import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <p>
      <p>Hello</p>
    </p>
  );
};

export default Home;
```
3. `yarn dev` (or `npm run dev`)
4. Open in browser, an Error overlay pops, and the console is full with errors/warnings.

**Comment by icyJoseph** [comment] 2022-05-09 09:13
It looks like when React tries to render this:

```jsx
 <p>
      <p>Hello</p>
 </p>
```

It resolves to:

```
 [<p />, <p>Hello</p>, <p />]
```

I doubled checked this on a React test (from their repo), which ends up with this output:

```shell
 Expected: <p><p>initial</p></p>
 Received: [<p />, <p>initial</p>, <p />]
```

Still not sure, if the error should be handled by Next.js? It looks a lot like it is a React issue though.

**Comment by hengwangsay** [comment] 2022-05-30 04:01
i think this is cause by browser parse html, server side render get correct html structure:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/89381306/170914621-7ae78665-751f-4595-ac4d-811399418c1b.png">

but for browser, it is invalid, so after parse, it is become
<img width="490" alt="image" src="https://user-images.githubusercontent.com/89381306/170914697-51701d10-e8d5-44ea-b901-ce4101606831.png">

when react hydrate, client render a same structure like server side, but not match current browser element structure, so react get a hydrate error. it is not a bug for react, just invalid element structure cause browser change it by them self

**Comment by balazsorban44** [comment] 2023-02-18 23:43
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.

**Comment by karlhorky** [comment] 2023-02-19 17:21
Still happens on `next@13.1.7-canary.21`:

![Screenshot 2023-02-19 at 18 20 44](https://user-images.githubusercontent.com/1935696/219963996-4e52fa44-97f9-49f5-9608-908433990292.png)

https://stackblitz.com/edit/vercel-next-js-yxke99?file=pages%2Findex.tsx&file=package-lock.json

**Comment by karlhorky** [comment] 2023-02-20 08:39
@balazsorban44 maybe this can be reopened?

**Comment by timneutkens** [comment] 2023-02-22 12:11
We've improved the error overlay in a bunch of ways for the hydration error case recently: https://github.com/facebook/react/issues/24519#issuecomment-1439915463

**Comment by karlhorky** [comment] 2023-02-22 19:21
Nice, thanks @timneutkens . I don't see this improved UI showing on a first load of the latest canary (`next@13.1.7-canary.26`) during verification of the latest canary - am I doing something wrong?

StackBlitz Demo: https://stackblitz.com/edit/vercel-next-js-kcesr7?file=pages%2Findex.tsx&file=package-lock.json

<img width="1438" alt="Screenshot 2023-02-22 at 20 18 57" src="https://user-images.githubusercontent.com/1935696/220736281-88dbc2aa-da5a-494b-b02d-79cebb139f0d.png">

**Comment by karlhorky** [comment] 2023-02-22 19:29
Also, it seems like @icyJoseph opened this issue in order to improve the message beyond what the new UI in https://github.com/facebook/react/issues/24519#issuecomment-1439915463 provides:

> Any invalid DOM structure causes `hydration` problems. I presume this is a React bug, but I don't have the time to collect more evidence, other than I can trigger this in Next.js, if other SSR frameworks show the bug, then it must definitely be upstream to React itself.
> 
> > One can argue that this is expected behaviour as well, but that invalid DOM nesting should throw while doing SSR, is not documented anywhere.

> The error/warnings should still be logged, but the HTML should be produced, although it is invalid.
>
> Or, alternatively, this behaviour should be document somewhere.

This is the new UI from @hanneslund / https://github.com/facebook/react/issues/24519#issuecomment-1439915463, which does reduce the verbosity a bit:

![220614285-972b4e42-ff5b-4d1e-9d0f-99360e95ee3e](https://user-images.githubusercontent.com/1935696/220737413-bf2050ea-b969-4fcf-b02f-26721106d839.png)

But arguably this still does not help developers find the origin of the problem easily and fix it.

---

I originally suggested that `eslint-plugin-react` could have a rule for this:

- https://github.com/jsx-eslint/eslint-plugin-react/issues/3310

But Dan Abramov mentioned that this was not a great approach, and that this should instead be fixed in Next.js itself. So I opened this similar issue:

- https://github.com/vercel/next.js/issues/37847

So maybe a further improvement on the `validateDOMNesting` + `Hydration failed` errors could be considered by Next.js.

**Comment by timneutkens** [comment] 2023-02-23 15:12
<img width="132" alt="CleanShot 2023-02-23 at 16 07 16@2x" src="https://user-images.githubusercontent.com/6324199/220946215-924e88eb-c7fe-4076-80e6-39d74f89a531.png">

As said in the message this only works for `app`, seems your demo uses `pages`.

Dan replied on your issue with this response: 

> I wonder if this is a good time to consider showing console.error from React in the box. Because conceptually they are errors and typically contain the actual cause before something throws.

That's what the error message includes now, it includes all data coming from React:
- Component stack, which allows you to see exactly which component / element caused it
- Actual validation message: e.g. `client` was provided instead of `server`, they mismatch.

Beyond this we don't have more info coming from React currently to highlight it further, e.g. we don't get a DOM node passed or anything like that. It's something I've been discussing with Josh and Sebastian though, it can be improved further but needs work from the React side of things.

**Comment by dcheng1290** [comment] 2023-03-26 08:02
@timneutkens any idea when this will be available for `pages` too?

**Closed** 2023-06-01 19:28 UTC
Labels: template: bug, type: needs triage
