### ISSUE TITLE
HookWebpackError: Unexpected '/'. Escaping special characters with \ may help.

### ISSUE THREAD

**Issue by Parth909** [vercel/next.js#50989] opened 2023-06-08 18:34 UTC
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #2311-Microsoft Tue Nov 08 17:09:00 PST 2022
    Binaries:
      Node: 16.20.0
      npm: 8.19.4
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 13.4.4
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC minifier (swcMinify: true)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/ (Sorry but it is a private repo. the configuration is mentioned below)

### To Reproduce

This is my next.config.js file
```js
const path = require("path");
const loaderUtils = require("loader-utils");
const MangleCssClassPlugin = require("mangle-css-class-webpack-plugin");

// based on https://github.com/vercel/next.js/blob/992c46e63bef20d7ab7e40131667ed3debaf67de/packages/next/build/webpack/config/blocks/css/loaders/getCssModuleLocalIdent.ts
// const hashOnlyIdent = (context, _, exportName) =>
//   loaderUtils
//     .getHashDigest(
//       Buffer.from(
//         `filePath:${path
//           .relative(context.rootContext, context.resourcePath)
//           .replace(/\\+/g, "/")}#className:${exportName}`
//       ),
//       "md4",
//       "base64",
//       6
//     )
//     .replace(/^(-?\d|--)/, "_$1")
//     .replaceAll("+", "_")
//     .replaceAll("/", "_");

module.exports = {
  serverRuntimeConfig: {},
  publicRuntimeConfig: {
    APP_NAME: "COIN_PLANET",
    API: "http://localhost:8081/api",
    PRODUCTION: true,
    DOMAIN: "http://localhost:3000",
  },
  images: {
    domains: [""],
  },
  webpack(config, { dev }) {
    const rules = config.module.rules
      .find((rule) => typeof rule.oneOf === "object")
      .oneOf.filter((rule) => Array.isArray(rule.use));

    if (!dev)
      rules.forEach((rule) => {
        rule.use.forEach((moduleLoader) => {
          if (
            moduleLoader.loader?.includes("css-loader") &&
            !moduleLoader.loader?.includes("postcss-loader")
          )
            moduleLoader.options.modules.getLocalIdent = (
              context,
              _,
              exportName
            ) =>
              loaderUtils
                .getHashDigest(
                  Buffer.from(
                    `filePath:${path
                      .relative(context.rootContext, context.resourcePath)
                      .replace(/\\+/g, "/")}#className:${exportName}`
                  ),
                  "md4",
                  "base64",
                  6
                )
                .replaceAll("/", "_")
                .replace(/^(-?\d|--)/, "_$1")
                .replaceAll("+", "_");
        });
      });

    if (!dev) {
      config.plugins.push(
        new MangleCssClassPlugin({
          classNameRegExp:
            "((hover|focus|sm|md|lg|xl)[\\\\]*:)*(tw)-[a-zA-Z0-9-[#-_-]*",
          ignorePrefixRegExp: "",
          log: false,
          classGenerator: (original) => {
            const newClass = original
              .replace(/tw-/g, "")
              .replace(/grid/, "g")
              .replace(/auto/, "au")
              .replace(/border/g, "b")
              .replace(/center/g, "ctr")
              .replace(/rounded/g, "rd")
              .replace(/max-content/, "mc")
              .replace(/maxcontent/, "mc")
              .replace(/-/g, "NEGATIVE")
              .replace(/#/g, "")
              .replace(/sm:/, "1")
              .replace(/md:/, "2")
              .replace(/lg:/, "3")
              .replace(/xl:/, "4")
              .replace(/\[/, "")
              .replace(/\]/, "");

            // return btoa(newClass).replace(/=/g, '');
            return Buffer.from(newClass).toString("base64").replace(/=/g, "");
          },
        })
      );
    }

    return config;
  },
};
```

### Describe the Bug

It was successfully built during the initial build, but on building it again it started throwing this error. BTW I don't have any unending comment or unescaped "/" as mentioned in stackoverflow answers. I have removed all the comments.

Using `MangleCssClassPlugin` plugin to mangle tailwind classes

I have encountered this bug in version twelve so bumped it to version 13, but still encountering the same bug.

```
Failed to compile.

HookWebpackError: Unexpected '/'. Escaping special characters with \ may help.
    at makeWebpackError (/mnt/c/Users/Parth979/Documents/workspace/CoinPlanet/cp-front/node_modules/next/dist/compiled/webpack/bundle5.js:28:308185)
    at /mnt/c/Users/Parth979/Documents/workspace/CoinPlanet/cp-front/node_modules/next/dist/compiled/webpack/bundle5.js:28:105236
    at eval (eval at create (/mnt/c/Users/Parth979/Documents/workspace/CoinPlanet/cp-front/node_modules/next/dist/compiled/webpack/bundle5.js:13:28771), <anonymous>:34:1)
-- inner error --
Error: Unexpected '/'. Escaping special characters with \ may help.
    at /mnt/c/Users/Parth979/Documents/workspace/CoinPlanet/cp-front/static/css/ea7b02abdd926ea6.css:78:1
    at Root._error (/mnt/c/Users/Parth979/Documents/workspace/CoinPlanet/cp-front/node_modules/next/dist/compiled/cssnano-simple/index.js:190:79280)
```

```
caused by plugins in Compilation.hooks.processAssets
Error: Unexpected '/'. Escaping special characters with \ may help.
    at /mnt/c/Users/Parth979/Documents/workspace/CoinPlanet/cp-front/static/css/ea7b02abdd926ea6.css:78:1
```

### Expected Behavior

I expected the production build to be created. I have spent the whole day switching between versions. Finally when it started working after the initial build again it is showing the above error.

### Which browser are you using? (if relevant)

Not relevant

### How are you deploying your application? (if relevant)

Testing it locally

**Comment by nitesh-000** [comment] 2023-08-19 07:12
Getting the same error!
How to tackle this?

Help much appreciated.

**Comment by Arshiash80** [comment] 2023-08-31 05:15
Quick update on that problem I ran into while building. Normally, error messages tell us where they're from, but this time, that info was missing. Spent quite a bit of time on it.

Following the build logs closely, I caught something interesting. The error popped up when the CSS files were getting built. After some digging, turns out I made a typo in my `global.css file` - wrote `* / html {...}` by mistake.

Since you didn't give more code details, my suggestion is to check the logs to trace where the issue really started. Might help you track things down next time.

Just wanted to update this on the GitHub issue thread. Any questions, feel free to ask.

**Comment by nitesh-000** [comment] 2023-08-31 05:55
Thnx man @Arshiash80,
Actually fix that a long time ago, it was the same `global.css` file issue. but forgot to update here.
Appreciate the response!

**Comment by crathert** [comment] 2023-09-13 14:03
@Arshiash80 How exactly would I trace the file where this error comes from? I have the same issue but it only started appearing after upgrading from Next js 10 to next js 12. Also, I have a webpack config setup that compiles LESS to CSS so I can work with ANTD. Currently I can't find where the issue is coming from. Any chance you can tell me how I can do this?

Thanks

**Comment by nitesh-000** [comment] 2023-10-01 05:28
@crathert For me.. i just went through the css file.. and found out a warning was there... and fix it.
I too have no idea how to trace it.
If you have found a way, please share it with us too.

**Comment by kdy1** [comment] 2023-10-24 04:16
I think this is fixed, but I can't very as there's no repro. Can you check if it's fixed?

**Comment by kdy1** [comment] 2023-10-30 01:45
Closing as it's expected to be fixed in canary

**Closed by kdy1** 2023-10-30 01:45 UTC
Labels: template: bug, area: SWC Minify
