### ISSUE TITLE
webpack cannot find module /.undefined

### ISSUE THREAD

**Issue by Manubi** [vercel/next.js#27173] opened 2021-07-14 16:46 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

16.3.0

### What browser are you using?

chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When I send a query to the /api route sometimes - not always. This error happens:
`event - compiled successfully
event - build page: /api
wait  - compiling...
event - compiled successfully
Error: Cannot find module './undefined'
Require stack:
- /Users/mbichler/dev/impfi-web/.next/server/webpack-runtime.js
- /Users/mbichler/dev/impfi-web/.next/server/pages/api.js
- /Users/mbichler/dev/impfi-web/node_modules/next/dist/next-server/server/next-server.js
- /Users/mbichler/dev/impfi-web/node_modules/next/dist/server/next.js
- /Users/mbichler/dev/impfi-web/node_modules/next/dist/server/lib/start-server.js
- /Users/mbichler/dev/impfi-web/node_modules/next/dist/cli/next-dev.js
- /Users/mbichler/dev/impfi-web/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.mod._resolveFilename (/Users/mbichler/dev/impfi-web/node_modules/next/dist/build/webpack/require-hook.js:4:1855)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.__webpack_require__.f.require (/Users/mbichler/dev/impfi-web/.next/server/webpack-runtime.js:163:28)
    at /Users/mbichler/dev/impfi-web/.next/server/webpack-runtime.js:81:40
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (/Users/mbichler/dev/impfi-web/.next/server/webpack-runtime.js:80:67)
    at Array.map (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mbichler/dev/impfi-web/.next/server/webpack-runtime.js',
    '/Users/mbichler/dev/impfi-web/.next/server/pages/api.js',
    '/Users/mbichler/dev/impfi-web/node_modules/next/dist/next-server/server/next-server.js',
    '/Users/mbichler/dev/impfi-web/node_modules/next/dist/server/next.js',
    '/Users/mbichler/dev/impfi-web/node_modules/next/dist/server/lib/start-server.js',
    '/Users/mbichler/dev/impfi-web/node_modules/next/dist/cli/next-dev.js',
    '/Users/mbichler/dev/impfi-web/node_modules/next/dist/bin/next'
  ]
}
wait  - compiling...
event - compiled successfully`

### Expected Behavior

I expect the server to respond. 

### To Reproduce

<img width="890" alt="CleanShot 2021-07-14 at 18 45 55@2x" src="https://user-images.githubusercontent.com/20935138/125660683-5eeb1d9e-2724-4323-a488-11e65d52f45c.png">

**Comment by timneutkens** [comment] 2021-11-17 15:46
Closing as there was no reproduction provided.

**Closed by timneutkens** 2021-11-17 15:46 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-27 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
