### ISSUE TITLE
Multiple issues related to ii18n (redirects, localeDetection)

### ISSUE THREAD

**Issue by suckydev** [vercel/next.js#20488] opened 2020-12-26 12:44 UTC
next.config.js:

```
module.exports = {
  trailingSlash: true,
  i18n: {
    locales: ["en", "de"],
    defaultLocale: "en",
  },
  async redirects() {
    return [
      {
        source: "/en/:path*",
        destination: "/:path*",
        permanent: true,
      },
    ];
  },
}
```

**1st Issue**
the issue I mentioned in #20165 is still not working for me (upgraded to 10.0.4). only the issue related to the trailingSlash seems to be fixed for me.

Examples:
- I go to **/en/**, I am not redirected to **/**, instead I stay on **/en/**
- I go to **/en/some-page/**, I am not redirected to **/some-page/**, instead I stay on **/en/some-page/**

<img width="558" alt="en-imprint-redirect" src="https://user-images.githubusercontent.com/75957128/103151775-67a2ae00-4781-11eb-9742-2fd957f11592.png">

<img width="556" alt="en-redirect" src="https://user-images.githubusercontent.com/75957128/103151776-696c7180-4781-11eb-8f10-0dc43fa1eec4.png">

**2nd Issue**
In my opinion, **localeDetection** is not working properly, when it includes a region.

Example:
- I set the browser language to "de-at" in FF
- I go to **/**, I am not redirected to **/de/**, instead I stay on **/**

however, it works when the browser language is explicitly set to "de" only. but when it includes a region (e.g. Austria) like in the example above, it is not working.

<img width="551" alt="accept-language" src="https://user-images.githubusercontent.com/75957128/103151721-f6fb9180-4780-11eb-86a2-60a7a76c7f79.png">

**3rd Issue**
In my opinion, **localeDetection** also creates a bad user experience.

Example:
- I set the browser language to "de" in FF
- I go to **/** it redirects to **/de/** (this is fine)
- I click the link "Go to EN", I am redirected to **/** (this is fine, as I explicitly want to browse the EN version)
- I refresh the browser (for whatever reason), I get redirected back to **/de/** instead of staying on **/**

`<Link href="/" locale="en">Go to EN version</Link>`

is this intended?

I feel like when a user explicitly decides to navigate to a different locale, **localeDetection** should be deactivated during that session, or preferably even set a cookie that prevents **localeDetection** when the user comes back to the site in the future. this also shouldn't be any issue for SEO.

**Comment by iDuuck** [comment] 2020-12-26 13:15
**Regarding first issue:** This goes in one with the third issue you are talking about. So, you tell in the third issue, that there is a "bad user experience". But the first issue states the complete opposite (as far as I understand your issues). If you are explicitly navigating to the "/en" route, I – as a user – don't want to be redirected to the "de" route. Instead, it would be nice by *you* to create something like a banner, and tell the user "Hey, we saw that you are german, would you like to view the page in german".

> apple.com has a client-side detection which then shows a message asking if you want to change to a different locale. If there's enough interest in this type of solution we can provide tools for this approach as well.

– Quote from [I18n RFC](https://github.com/vercel/next.js/discussions/17078)

**Regarding second issue:** I *suppose* (as far as I can read from the [official specs](https://tools.ietf.org/html/rfc7231#section-5.3.5)) that this is indeed the right behavior. However, I am completely with you, that this should not be the case.
I don't know completely how the browsers treat the headers explicitly, but normally browsers like Chrome and Firefox should also send the "de" flag as a lower quality to the user agent. So it would look somehow like this:

```
de-AT,de;q=0.9,en-US;q=0.8,en;q=0.8
```

**Regarding your third issue:** Indeed [there is a cookie, that should be set](https://github.com/vercel/next.js/blob/788183e8d3c6e354e24a89febcfdc482fc55640b/packages/next/next-server/server/next-server.ts#L419), when the user visits a locale specifically. However, I am also not able to make it work for me on my application.

**Comment by suckydev** [comment] 2020-12-26 14:07
hi iDuuck,

thanks for your response & help! :)

**Regarding first issue:** the first issue and the third issue are not related. the first issue says /en/ should default to /, because "en" is set as the **defaultLocale**, so there's no need to have:

- /en/ and /, or
- /en/some-page/ and /some-page/

because they all serve the same language version.

**Regarding second issue:** hmm, not sure then, to be honest. I just set the browser language to "de-at" in FF and it did not work, only when I added "de" as well.

**Regarding third issue:** I think I'll just set **localeDetection** to false for now, and simply show a banner to the user notifying them that they can browse the site in a different locale, providing them a link.

**Comment by kiriorange** [comment] 2021-01-12 06:01
Hey regarding issue 1, I saw that ijjk fixed it 2 weeks ago and should be resolved in `v10.0.5-canary.3`
https://github.com/vercel/next.js/issues/18335#issuecomment-751959598

I've tested and it works for me. See if it fixes your problem!

**Comment by suckydev** [comment] 2021-01-12 20:35
hi,

thanks for the message.
issue still persists, though.

not sure if it will ever be fixed. I’ll just avoid the issue for now by setting the correct canonical tag in order to avoid duplicate content.

cheers

**Comment by strangedev** [comment] 2021-02-01 14:18
We're also experiencing problems related to the locale detection.
In our example, our content is in `de-de` and we request `de-LI,de`. According to [RFC 4647](https://tools.ietf.org/html/rfc4647#section-3.3.1) this should match `de-de`, because `de` is a prefix of `de-de`.
It seems, however, that only exact matches work at the moment.

Our `next.config.js` looks like this:
```
// eslint-disable-next-line strict
'use strict';

const { processenv } = require('processenv');
const trailingSlash = processenv('TRAILING_SLASH', false);
const i18n = {
  locales: [ 'en-us', 'de-de' ],
  defaultLocale: 'en-us'
};

const configuration = {
  trailingSlash,
  i18n
};

module.exports = configuration;
```
Our `accept-language` header looks like this:

```
de-LI,de;q=0.9,en-US;q=0.8,en;q=0.7
```

**Comment by strangedev** [comment] 2021-02-02 09:52
There's now a PR in https://github.com/hapijs/accept/pull/64 which fixes matching of a more specific language tag if a less specific one is requested :tada:

**Comment by dotKuro** [comment] 2021-02-08 14:52
The Problem is now fixed in `@hapi/accept v5.0.2`. Updating the dependency should fix the faulty detection, when only requesting a prefix. i.e: When requesting `de` your page will now also ship `de-de`.

**Comment by chrillep** [comment] 2021-04-23 07:11
any update on this?  "next": "^10.1.3" using "@hapi/accept": "5.0.1",

**Comment by chrillep** [comment] 2021-05-06 15:53
next v10.2.0 still  "@hapi/accept": "5.0.1",  😊 https://github.com/vercel/next.js/commit/6b97bcea5ba851740404e8192fc9ebff711e1b83#diff-9c1a3867443c54525b4f24ef171f231a6e8bb065ffc8b7b62c4843d5ff62dd42L66

**Comment by timneutkens** [comment] 2021-05-07 08:59
> next v10.2.0 still "@hapi/accept": "5.0.1", 😊 [6b97bce#diff-9c1a3867443c54525b4f24ef171f231a6e8bb065ffc8b7b62c4843d5ff62dd42L66](https://github.com/vercel/next.js/commit/6b97bcea5ba851740404e8192fc9ebff711e1b83#diff-9c1a3867443c54525b4f24ef171f231a6e8bb065ffc8b7b62c4843d5ff62dd42L66)

Feel free to open a PR

**Comment by Lunnatica** [comment] 2021-05-16 10:35
@timneutkens there seem to be two PRs already created for this: https://github.com/vercel/next.js/pull/24283 and https://github.com/vercel/next.js/pull/23142

I can open a new one if these are outdated.

**Closed** 2021-05-16 19:01 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
