### ISSUE TITLE
[NEXT-526] appDir on Vercel: Cannot read properties of undefined (reading 'getReader')

### ISSUE THREAD

**Issue by pudo** [vercel/next.js#45627] opened 2023-02-06 18:19 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

**This issue only occurs when deployed on Vercel, I cannot reproduce it locally**

Local next info:

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103
    Binaries:
      Node: 19.5.0
      npm: 9.3.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.6
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/opensanctions/site/tree/main/app/entities/%5BentityId%5D

### To Reproduce

I cannot reproduce this bug on my own computer. I've tried the `vercel` command. I've contacted Vercel support but they told me I should go here because it's `appDir`. I've tried the following to narrow it down, without success:

* Removing/commenting out everything in the `head.tsx`
* Removing/commenting out everything in the `loading.tsx`
* Removing/commenting out everything in the `page.tsx`
* Checked all routes to see if `null` is returned anywhere

The only thing that works is downgrading to **next 13.1.1**

### Describe the Bug

When deploying this site to Vercel, the following error is all over the logs - and API request usage goes up 10x:

```
[GET] /entities/Q4532737/
19:07:51:88
2023-02-06T18:07:52.006Z	41727f4c-cfa6-48ec-88d3-e451cce93603	ERROR	TypeError: Cannot read properties of undefined (reading 'getReader')
    at /var/task/node_modules/next/dist/server/render-result.js:27:37
    at RenderResult.pipe (/var/task/node_modules/next/dist/server/render-result.js:46:11)
    at Object.sendRenderResult (/var/task/node_modules/next/dist/server/send-payload/index.js:69:22)
    at NextNodeServer.sendRenderResult (/var/task/node_modules/next/dist/server/next-server.js:394:34)
    at NextNodeServer.pipe (/var/task/node_modules/next/dist/server/base-server.js:419:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:759:21)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:253:36)
    at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:384:29)
    at async NextNodeServer.handleRequest (/var/task/node_modules/next/dist/server/base-server.js:322:20)
RequestId: 41727f4c-cfa6-48ec-88d3-e451cce93603 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

Whenever I open the erroring page in the browser, it is displayed without error. 

Sometimes the error is also just:

```
[GET] /entities/NK-c55S959ZVS6JnyQZCzjPPN/
19:07:53:19
RequestId: 73ea2414-0a59-4769-b913-2327be28c231 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

### Expected Behavior

I expect the page to be rendered without error. 

### How are you deploying your application? (if relevant)

Vercel

<sub>[NEXT-526](https://linear.app/vercel/issue/NEXT-526/appdir-on-vercel-cannot-read-properties-of-undefined-reading-getreader)</sub>

**Comment by skwinnik** [comment] 2023-02-08 22:16
I also experience this issue on Vercel and cannot reproduce it locally. In my case, I see these errors only when google or another search engine crawls my website. But, my app doesn't have a lot of visitors, so may be it's not really specific to crawlers.

**Comment by pudo** [comment] 2023-02-09 09:24
I've subjectively also noticed that a lot of the error messages seem to show a crawler UA. Weird.

**Comment by venables** [comment] 2023-02-09 10:58
Thank you!  I have been experiencing this issue as well.  Anecdotally, it also appears that crawlers receive the most errors, but I have noticed this occurring to (seemingly) regular users as well.  Similarly, the API usage reported by Vercel skyrocketed.

**Downgrading to next 13.1.1 appears to have fixed the issue.**  I will slowly increment patch version by patch version to see if I can provide assistance to locating the bug.

**Comment by skwinnik** [comment] 2023-02-09 20:52
@venables Thank you for the research! Can you share with us how exactly you tested this? It may be helpful for further research.

**Comment by venables** [comment] 2023-02-09 21:57
@skwinnik I tested by simply locking in a version of next and deploying it to my sites on Vercel.  The function logs would immediately turn red with the error described in this ticket (`TypeError: Cannot read properties of undefined (reading 'getReader')`).  I was unable to get this error to occur locally, but it's pretty immediate when deployed to production.

**Comment by dluan** [comment] 2023-02-17 13:55
An error is occurring, and the feedback is not very clear on how I should resolve it.
When I run 'yarn build' sometimes it works, other times it doesn't with the same code.

```
// package.json
{
...
"next": "13.1.1"
react": "18.2.0"
...
}
```

```
// app/page.tsx
...
async function Carousel() {
   const { Banner } = await request<BannerResponse>(GET_BANNER)

   return <Hero banners={Banner} data-superjson />
}

export default function Home() {
   return (
      <>
         <div>
            <Suspense fallback={<SkeletonHero />}>
               {/* @ts-expect-error Server Component */}
               <Carousel />
            </Suspense>
...
```

```
// components/home/Hero.tsx
'use client'
...
export default function Hero({ banners }: HeroProps) {
   return (
      <div className="border-y-2 border-indigo-600 max-h-[70vh] overflow-hidden">
         <CarouselProvider
            naturalSlideWidth={1920}
            naturalSlideHeight={652}
            totalSlides={banners ? banners.length : 2}
            infinite={true}
            dragEnabled={false}
         >
            <Slider>
            {banners.map((banner, index) => (
...
```

The following error appears in the terminal: "TypeError: Cannot read properties of undefined (reading 'map')"
![image](https://user-images.githubusercontent.com/1024699/219667164-2ec65450-55a1-47f0-8f17-b892aedc5815.png)


The same happens when I try to publish on Vercel, the same code may or may not work.

Did I do something wrong?

**Comment by skwinnik** [comment] 2023-02-17 18:00
@dluan the error you're facing doesn't appear to be related to the discussion here. It looks like the API you're calling sometimes returns null values, but perhaps it is better to discuss this in another issue.

**Comment by shuding** [comment] 2023-02-23 15:02
Hi @venables could you test it with the latest canary? I think the bug should be fixed in #46265.

**Comment by venables** [comment] 2023-02-23 16:14
@shuding That worked! 🎉  I upgraded to the latest canary (`13.1.7-canary-30`) and have not seen any errors come through, which used to happen almost immediately upon upgrading past 13.1.1.  

Thank you, and everyone else who helped solve this!

**Comment by shuding** [comment] 2023-02-23 23:26
Thank you!

**Closed by shuding** 2023-02-23 23:26 UTC
Labels: type: needs investigation, template: bug, area: app, linear
