### ISSUE TITLE
Failed to load next.config.js with ES Modules

### ISSUE THREAD

**Issue by jinsley8** [vercel/next.js#30643] opened 2021-10-30 01:10 UTC
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

14.7.1

### What browser are you using?

Brave/Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

I upgraded to v12.0.1 and I am trying to enable ES Modules. I'm also using a custom express server in a monorepo with Next.js. I have `"type": "module"` in package.json.

I replaced all `exports` and `require()` with ES Module equivalents `import` and `export const`. 

Now the last issue is when I run `next start` I get the following error:

```Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and 'package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.```

I read in another issue to remove  `"type": "module"` in package.json but that just causes issues in the custom server like:

```Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/server/app.js:2
import { config } from 'dotenv';
^^^^^^

SyntaxError: Cannot use import statement outside a module```

### Expected Behavior

I thought ES Modules were fully supported now so I was expecting not to have issues with files like next.config.js.

### To Reproduce

If you changed the imports and exports in this example to use ES Modules and added next.config.js it would likely produce the same issue:

[https://github.com/vercel/next.js/tree/canary/examples/custom-server-express](https://github.com/vercel/next.js/tree/canary/examples/custom-server-express)

**Comment by rnarkk** [comment] 2021-10-31 15:01
Duplicate https://github.com/vercel/next.js/issues/30335. Please read this comment https://github.com/vercel/next.js/issues/30335#issuecomment-953506104.

**Comment by timneutkens** [comment] 2021-10-31 16:23
Duplicate of #9607

**Closed by timneutkens** 2021-10-31 16:23 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
