### ISSUE TITLE
SSG dev server 404 after refresh

### ISSUE THREAD

**Issue by foxundermoon** [vercel/next.js#11253] opened 2020-03-21 09:26 UTC
# Bug report

## Describe the bug

when dev, always response 404-page aftr refresh page.
`9.2.3 canary` is ok

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

https://github.com/WeFoxTech/wefox-site

1. clone
2.  `y boot`
3. `y dev`
2. open a page, not root index,  eg `/en/about`

## Expected behavior

![image](https://user-images.githubusercontent.com/2764106/77223626-4b8e3280-6b99-11ea-86f4-1f674c4967d5.png)

## Screenshots

![image](https://user-images.githubusercontent.com/2764106/77223621-36190880-6b99-11ea-843c-97aeade8d890.png)

## System information

- OS: [macOS 10.14.6]
- Browser (if applies) [chrome, safari,ff]
- Version of Next.js: [ 9.3.0,9.3.1]

**Comment by chaddjohnson** [comment] 2020-04-12 04:37
I'm seeing this same error with 9.3.4.

When I click a link to go to, say, /products/, and then I refresh the browser, I get a 404. This is a very annoying problem during development.

**Comment by alexdevero** [comment] 2020-05-09 08:23
I have the same problem. I go to a specific page using Link component from next.js. Page loads successfully. When I refresh the page I get 404.

**Comment by Timer** [comment] 2020-09-12 04:32
This was fixed in the latest version of Next.js!

**Closed by Timer** 2020-09-12 04:32 UTC

**Comment by pedroview** [comment] 2020-10-30 07:38
> This was fixed in the latest version of Next.js!

are you sure

**Comment by balazsorban44** [comment] 2022-01-29 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
