### ISSUE TITLE
NextConfig not exported from next

### ISSUE THREAD

**Issue by stramel** [vercel/next.js#27548] opened 2021-07-27 22:41 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

16.5.0

### What browser are you using?

Chrome

### What operating system are you using?

Mac OSX

### How are you deploying your application?

N/A

### Describe the Bug

Unable to type-check my `next.config.js` file due to `NextConfig` not being defined in `next`. Documented https://nextjs.org/docs/basic-features/typescript#type-checking-nextconfigjs

### Expected Behavior

I expect to be able to use 

```js
// @ts-check

/**
 * @type {import('next').NextConfig}
 **/
const nextConfig = {
  // ...
}
```

to type-check my config file

### To Reproduce

- Scaffold a new project `yarn create next-app --typescript`
- Add snippet to top of `next.config.js`
  ```js
  // @ts-check

  /**
   * @type {import('next').NextConfig}
   **/
  ```

**Comment by stramel** [comment] 2021-07-27 22:43
Currently, using this as my workaround.

```js
// @ts-check

/**
 * @type {import('next/dist/next-server/server/config').NextConfig}
 **/
```

**Comment by stefanprobst** [comment] 2021-07-28 05:01
in the current `canary` version you can import directly from

```js
/** @typedef {import('next').NextConfig} NextConfig */
```

**Comment by timneutkens** [comment] 2021-07-28 10:37
It's currently on next@canary, we updated the docs to a canary version to ensure some other links did not break. This will be released soon.

**Closed by timneutkens** 2021-07-28 10:37 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 01:27
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
