### ISSUE TITLE
Custom Redirects i18n: Accept Language and NEXT_LOCALE cookie are ignored

### ISSUE THREAD

**Issue by lorenzomigliorero** [vercel/next.js#20375] opened 2020-12-21 19:26 UTC
# Bug report

```js
i18n: {
  locales: ["en", "it"],
  defaultLocale: "it",
},
async redirects() {
  return [
     {
        source: '/pay/',
        destination: '/payments/',
        permanent: true,
      },
  ]
}
```

```
GET /pay HTTP/1.1
Host: localhost:3000
User-Agent: curl/7.64.1
Accept: */*
Cookie: NEXT_LOCALE=en
```

**Produces:** 

- /pay
- /it/pay/
- /it/payments/

**Expected result:**

- /pay
- /en/pay/
- /en/payments/

```
GET /pay HTTP/1.1
Host: localhost:3000
User-Agent: curl/7.64.1
Accept: */*
Accept-language: en
```

**Produces:**

- /pay
- /it/pay/
- /it/payments/

**Expected result:**

- /pay
- /en/pay/
- /en/payments/

## System information

- Version of Next.js: 10.0.3
- Version of Node.js: 12.19.0

**Comment by ijjk** [comment] 2020-12-22 03:54
Hi, the `NEXT_LOCALE` cookie is currently used to override the `accept-language` header detected locale when redirecting from the index route `/`. When visiting a non-index route the locale is detected from the domain or pathname so the above behavior does seem correct. We do plan to investigate locale redirects from non-index routes in future iterations on this feature.

**Comment by ijjk** [comment] 2021-01-05 05:05
I'm going to close this per the above comment since this is currently the expected behavior and is documented here https://nextjs.org/docs/advanced-features/i18n-routing

**Closed by ijjk** 2021-01-05 05:05 UTC
Labels: template: bug

**Comment by bbigras** [comment] 2021-02-27 18:50
Does `NEXT_LOCALE` work with Domain Routing?
