### ISSUE TITLE
Unhandled Runtime Error TypeError: Cannot read property 'tagName' of null

### ISSUE THREAD

**Issue by prathameshkoshti** [vercel/next.js#19388] opened 2020-11-21 13:22 UTC
# Bug report

## Description

After updating the next.js from v10.0.1 to v10.0.2 or 10.0.3, I started getting this issue on each page: 
**Unhandled Runtime Error 
TypeError: Cannot read property 'tagName' of null**.

## To Reproduce

1. Clone this repo: https://github.com/prathameshkoshti/phi-css-documention
2. Currently this is on the next js version 10.0.1, run `npm update` after `npm install`
3. Once next.js is updated to version 10.0.2 or 10.0.3, run the dev server `npm run dev`, the error pop up can be seen on each page.

While updating the npm packages only next.js package was updated.

## Expected behavior

This error should not occur.

## Screenshots

![Screenshot 2020-11-21 at 6 40 37 PM](https://user-images.githubusercontent.com/25136464/99878159-726d9e80-2c29-11eb-90ff-f91751634aac.png)

## System information

- OS: macOS 
- Version of Next.js: v10.0.2 or 10.0.3
- Version of Node.js: v12.19.0
- Deployment: local env

**Comment by timneutkens** [comment] 2020-11-22 16:54
Please add a complete reproduction for the issue you're running into. We can't run `npm update` in your application.

**Comment by timneutkens** [comment] 2020-11-23 16:02
Closing as there is no reproduction. Happy to re-open if a reproduction is provided.

**Comment by prathameshkoshti** [comment] 2020-11-24 13:05
@timneutkens Shall I post my repo link here? On the repo you can try this steps.

**Comment by timneutkens** [comment] 2020-11-24 13:26
Yes definitely

**Comment by prathameshkoshti** [comment] 2020-11-24 14:15
@timneutkens I have added the repo link in the steps to reproduce section. One more thing I tried this again and I noticed that it is occurring on the v10.0.3 version as well.

**Comment by timneutkens** [comment] 2020-12-04 10:18
```
componentDidMount() {
        const matcher = window.matchMedia('(prefers-color-scheme: dark)');
        matcher.addListener(onUpdate);
        onUpdate();
        function onUpdate() {
            const lightSchemeIcon = document.querySelector('link#light-scheme-icon');
            const darkSchemeIcon = document.querySelector('link#dark-scheme-icon');
            if (matcher.matches) {
                if(lightSchemeIcon) lightSchemeIcon.remove();
                document.head.append(darkSchemeIcon);
            } else {
                if(darkSchemeIcon) darkSchemeIcon.remove();
                document.head.append(lightSchemeIcon);
            }
        }
    }
```

This code causes the error, probably because of removing nodes that should be preserved. Definitely not a bug in Next.js as you're changing elements that were rendered through Next.js outside of the React rendering lifecycle.

Looking at the code that document.querySelector etc is really not needed, you can setState and change the rendering, that makes the component simpler too:

```js
export default function HeadComponent() {
    const [darkIcon, setDarkIcon] = useState(true)
    useEffect(() => {
        const matcher = window.matchMedia('(prefers-color-scheme: dark)');
        function onUpdate() {
            setDarkIcon(matcher.matches)
        }

        matcher.addListener(onUpdate)

        return () => matcher.removeListener(onUpdate)
    }, [])
    return (
        <Head>
            {darkIcon ? <link rel="icon" href="/logo-dark.png" id="light-scheme-icon" type="image/x-icon" /> : <link rel="icon" href="/logo-light.png" id="dark-scheme-icon" type="image/x-icon" />}
            <meta name="viewport" content="initial-scale=1.0, width=device-width" />
            <meta name="description" content="a css framework based on the golden ratio (1.618)" />
            <meta name="theme-color" content="" />
            <title>Phi: CSS framework</title>
        </Head>
    )
}
```

**Closed** 2020-12-04 10:18 UTC
Labels: please add a complete reproduction, template: bug

**Comment by prathameshkoshti** [comment] 2020-12-07 05:29
Thanks a lot for your time and letting me know about the issue, really appreciate the efforts.

**Comment by ninsau** [comment] 2021-07-07 00:59
```
import Script from 'next/script'
import Head from "next/head";


export default SomeFunction () {

return (

<>
<Head>
        <Script src="https://third-party-script.js"></Script>
</Head>
</>
)

}
```


This gave me the error 

```
Unhandled Runtime Error
TypeError: Cannot read property 'tagName' of null

Call Stack
updateElements
node_modules/next/dist/client/head-manager.js (2:964)
eval
node_modules/next/dist/client/head-manager.js (4:577)
Array.forEach
<anonymous>
eval
node_modules/next/dist/client/head-manager.js (4:562)

```

**Comment by umtdemr** [comment] 2021-08-19 07:17
I got same error with above.

**Comment by ninsau** [comment] 2021-08-19 10:40
I switched to this instead instead my head tags and it worked 


 ```
<script
          dangerouslySetInnerHTML={{
            __html: `
         Some js function here
                   `,
          }}
        ></script>
```

**Comment by balazsorban44** [comment] 2022-01-27 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
