### ISSUE TITLE
SSG with custom i18n express server not working.

### ISSUE THREAD

**Issue by maxtotheguenther** [vercel/next.js#29357] opened 2021-09-24 09:17 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

custom: "start": "cross-env NODE_ENV=production node dist/server/index.js",

### Describe the Bug

Hello guys,

im currently working on a nextjs typescript project with a custom express server.

Why custom express server?
Custom internationalization with basePath
Express middlewares

My file structure is as follows:
```
pages
   - _app.tsx
   - [pid].tsx
   - about.tsx
   - index.tsx
   - profile.tsx
```

My express server is configured as follows:

```
server.get(
  `/:locale?/${finalBasePath}/:path?`,
  ...finalMiddleware,
  (req, res) => {
    const finalPath = req.params?.path ? `/${req.params.path}` : "/";
    return app.render(req, res, finalPath);
  }
);

server.get(
  `(/${finalAssetPrefix}|/${finalAssetPrefix}/_next)/*`,
  ...finalMiddleware,
  (req, res) => {
    req.url = req.url.replace(`/${finalAssetPrefix}`, "");
    return handle(req, res);
  }
);

server.all("*", (req, res) => {
  return handle(req, res);
});

server.listen(finalPort, () => {
  console.log(
    chalk.yellowBright(
      `${finalName} - 🚀 on http://localhost:${finalPort}/${finalBasePath}`
    )
  );
});
```

When i try to static generate [pid].tsx file 

```
export const getStaticProps: GetStaticProps<Props, { pid: string }> = async ({
  params,
}) => {
  if (!params?.pid)
    return {
      notFound: true,
    };
  // ... some further backend calls. and return of props.
};

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: ["/de-en/training/4526030"],
    fallback: "blocking",
  };
};
```

I get the following error
**Error: The provided path `/de-en/training/4526030` does not match the page: `/[pid]`.**

On the other hand ISR is working as expected...
When i call `/de-en/training/4526030` the site gets successfully generated.

```
.next
- server
   - pages
     - de-en
        - training
           -  4526030.(html | json)
```

### Expected Behavior

SSG should work as ISR.

### To Reproduce

If needed I can provide an example.

**Comment by ijjk** [comment] 2021-09-24 18:30
Closing as a duplicate of https://github.com/vercel/next.js/issues/20761

**Closed by ijjk** 2021-09-24 18:30 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
