### ISSUE TITLE
Dev mode keeps refreshing

### ISSUE THREAD

**Issue by TrueWill** [vercel/next.js#29184] opened 2021-09-17 17:09 UTC
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

14.17.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

Regularly I'm working along in dev mode, testing my application, NOT making any changes to the code, when suddenly:

> event - build page: /[customer]/[config]/[[...index]]
> wait  - compiling...
> event - compiled successfully

...and now all of my in-memory application state is gone - Context, useState, etc. - and I have to start all over.

I haven't even done navigation - I'm sitting on a page.

This isn't about hot reloading; this is about rebuilding when nothing has changed (and losing state).

This has happened with multiple versions of Next.js for months, and has cost many hours.

### Expected Behavior

Application in dev mode only refreshes when code changes are made (and then hot reloads if possible).

### To Reproduce

Work with any Next.js application in dev mode for half an hour or more.

**Comment by KRIMOD** [comment] 2021-09-19 00:15
Do you happen to use Link from next/Link component in your dynamic pages ? If so, maybe it's related to the "as" property of the api. I ve see similar issues on stackoverflow and they fixed it with explicitly setting "as" like so : 
```javascript
<Link
  href={'/slot/[key]'}
  as = {`/slot/${your_dynamic_variable}`}
>
    <a>
      Go to the slot route
    </a>
</Link>
```
Check this [link](https://stackoverflow.com/questions/56817613/next-js-links-refresh-the-page) for further reading.

**Comment by balazsorban44** [comment] 2021-09-20 10:43
This (or something very similar) has come up for me as well, with the following error:

![image](https://user-images.githubusercontent.com/18369201/133989446-ffdfc1f6-52b5-4644-a7ad-31f121166a8e.png)

Without changing anything, the page decides to do a hard reload, busting all the in-memory state.

I believe upgrading to the latest canary helped at some point, but it still happens from time to time. 
Could you try upgrading to a `canary` release (As of this writing, the latest is `11.1.3-canary.24`)?

It happens irregularly, so creating a reproduction for me is hard, but if you have a simple repo that has this problem consistently, linking it here might help!

Could you also try an incognito window without any extensions to verify it's not related to that?

**Comment by ivanmaeder** [comment] 2021-09-20 16:26
Something similar has been happening to me, maybe since I started using Next.js a few months ago. I thought it was the expected behaviour!

Typically I'll be on a different tab for a while, then when I switch back to the Next.js page, the browser logs will show:

```
[Fast Refresh] rebuilding hot-dev-client.js:196:6
Refreshing page data due to server-side change
```

The server logs will show:

```
event - build page: /api/auth/[...nextauth]
wait  - compiling...
event - compiled successfully
```

This is without making any changes to the code. This page also uses `getServerSideProps()` which will also run (this is the most frustrating thing at the moment because of some side effects in that code; the form data on the page isn't actually lost).

Other times this compile-refresh cycle will run without even opening the page in question:

```
wait  - compiling...
event - compiled successfully
```

It's also not uncomon for the cycle to run twice in quick succession.

I also have a webhook that recompiles when it gets invoked sometimes, again without changing any files and I'm not sure if that's normal.

```
event - build page: /api/v1/webhook
wait  - compiling...
event - compiled successfully
```

I'm using Next.js 10.2.3 with `next dev` within a node:16.0.0-alpine3.11 Docker container. I see this behaviour in Chrome and Firefox.

I use `<Link>` in other parts of the app, but not to or from the page mentioned above (and never with the `as` attribute).

I haven't noticed anything like this in the bundle, only in development.

Thanks.

**Comment by ivanmaeder** [comment] 2021-09-20 20:03
I've tried to put together a stripped down version of my repo but I can't quite replicate the issue the same way, not even in the original repo.

Right now:

1 minute after having opening (not loading) the relevant tab/page in my browser, this shows up in the server logs:

```
wait  - compiling...
event - compiled successfully
```

(This only shows up again if I continue to the next step; it doesn't happen every minute.)

So then, if I've previously activated a different tab and now I come back, I'll get:

```
event - build page: /api/auth/[...nextauth]
wait  - compiling...
event - compiled successfully
```

If I repeat this last step without waiting the full minute, it won't recompile (the full minute has to pass, with the compilation step at the top).

I'm not sure if that helps, but if anyone has any ideas on how to continue debugging this, I'm all ears.

**Comment by balazsorban44** [comment] 2021-09-20 20:08
Interestingly, we also use `next-auth`... Could be a common denominator? @TrueWill do you happen to use `next-auth` as well?

(Fun fact, `next-auth` maintainer here... :sweat_smile: :wave:)

**Comment by ijjk** [comment] 2021-09-20 20:18
Hi, we dispose of inactive pages in development per the config documented here https://nextjs.org/docs/api-reference/next.config.js/configuring-onDemandEntries so the behavior you're describing @ivanmaeder sounds expected,

**Comment by ivanmaeder** [comment] 2021-09-21 07:39
Thanks @ijjk, I had no idea. I'll play around with this setting.

For what it's worth, I'd rather be in control of when a page (especially with `getServerSideProps()`) refreshes. Either because I've changed or reloaded it (definitely not because of a timeout, or because the page has come into focus).

For example right now I'm working on a Stripe integration and this refresh scenario is causing some dev issues: duplicate customers on Stripe, and—I think—some events coming through via webhooks are being skipped because the webhook is called just as the endpoint "page" is refreshed.

I've found this so I'll copy my comments there:

https://github.com/vercel/next.js/discussions/25712

**Comment by ijjk** [comment] 2021-09-23 03:26
I'm gonna close this per above as it sounds like this is the expected behavior and a bug isn't present here, feel free to respond with additional info if you are still experiencing unexpected behavior after modifying the above mentioned `onDemandEntries` config.

**Closed by ijjk** 2021-09-23 03:26 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2021-09-23 09:53
Update from my side, my problem seems to be related to a Chrome version, not my code. I'll have to investigate further.

Chrome stable/Firefox works fine, while Chrome `Version 95.0.4638.17 (Official Build) dev (64-bit)` produces my errors. So for future people, ignore my comments above, not related to OP's problem.

**Comment by ijjk** [comment] 2021-10-14 14:51
@lunatiqqc the behavior you are seeing is due to un-named exports with fast refresh, related documentation here https://nextjs.org/docs/basic-features/fast-refresh#how-it-works

**Comment by fabien** [comment] 2021-12-14 08:52
@balazsorban44 I'm using `next-auth` as well, and I think this issue started when I introduced it into my app. Any thoughts?

**Comment by chamamme** [comment] 2021-12-20 15:24
@balazsorban44  mine also started right after i set up ```next-auth```. For me there are random hard refresh when a link is clicked (both static and dynamic). The redirect first hits the destination path and then gets back to the previous path. After that all subsequent clicks  to the same link work as expected.

**Comment by fabien** [comment] 2021-12-22 19:34
@chamamme @balazsorban44 I can confirm this exact behavior and it’s driving me nuts by now ;-) ... unfortunately it completely negates Next’s instant refresh experience while developing.

**Comment by balazsorban44** [comment] 2021-12-22 23:06
I don't have access to the project that had this issue anymore. As mentioned, my issue turned out to be related to a Chrome version, not `next-auth`. I kindly ask people to stop tagging me. I recommend opening a new issue with _minimal_ reproduction instead. I'm happy to investigate further then.
