### ISSUE TITLE
Failed to load the correct optional catch all route (9.5.4)

### ISSUE THREAD

**Issue by KieraDOG** [vercel/next.js#17732] opened 2020-10-09 02:46 UTC
# Bug report

## Describe the bug

There are two routes in our project

- `[destintionName]/[[...params]]` - **DestinationPage**
- `[desitntionName]/properties/[propertyId]/package/[[...params]]` - **PackagePage**

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. On **DestinationPage** `/cairns`

2. Click `<Link href="/cairns/properties/123451/package" />` to go to **PackagePage**

3. It updates browser url to `/cairns/properties/123451/package`

## Expected behavior

4. Expects to go and load **PackagePage**, but it refreshes and load **DestinationPage**

## System information

- OS: macOS
- Browser (if applies) chrome
- Version of Next.js: 9.5.4
- Version of Node.js: 10.16.3

**Comment by ijjk** [comment] 2020-10-09 05:36
Hi, I'm not able to reproduce this on v9.5.4 of Next.js on a minimal project using the above page set-up. Can you provide a repo with a minimal reproduction that shows the issue?

**Comment by KieraDOG** [comment] 2020-10-11 23:53
> Hi, I'm not able to reproduce this on v9.5.4 of Next.js on a minimal project using the above page set-up. Can you provide a repo with a minimal reproduction that shows the issue?
> 
> ![Kapture 2020-10-09 at 00 42 52](https://user-images.githubusercontent.com/22380829/95547370-7e2e3a00-09c8-11eb-9bad-da6cd0e47c28.gif)

Hi, thx for reply, please have a look on this reproduction example repo.

https://github.com/KieraDOG/my-app

It does not work when
- **with baseBase config**
- **link to PackagePage with query**

**Comment by ijjk** [comment] 2020-10-12 01:58
Thanks for the reproduction, it looks like this is from a conflict with the `basePath` config and the automatic `href` resolving. 

To get around this for now you should be able to use the manual `href` and `as` logic previously used for dynamic routes e.g. `href="/[destinationName]/properties/[propertyId]/package" as="/cairns/properties/413969/package"`

**Comment by KieraDOG** [comment] 2020-11-09 03:15
@ijjk This is the release that introduce this bug

**Comment by KieraDOG** [comment] 2020-11-09 03:17
@ijjk This is the release that causes bug 
https://github.com/vercel/next.js/releases/tag/v9.5.6-canary.9

**Comment by ijjk** [comment] 2020-12-30 02:11
Hi, this appears to be working as expected on the latest canary of Next.js `v10.0.5-canary.3`, please update and give it a try!

**Closed by ijjk** 2020-12-30 02:11 UTC
Labels: kind: bug

**Comment by balazsorban44** [comment] 2022-01-28 23:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
