### ISSUE TITLE
Add Example Project (Typescript + Jest + ESLint)

### ISSUE THREAD

**Issue by cnajeraz** [vercel/next.js#11834] opened 2020-04-11 20:44 UTC
# WithTypescript + Jest + ESLint

I was trying to get this setup for my own but I want to share it with you because I couldn’t find that exact setup in your `examples` folder

### It's ready to deliver 😗

**Comment by timneutkens** [comment] 2020-04-11 21:17
Overall I'd say that would be too specific of an example to add into the examples directory, but happy to review a PR for it.

**Comment by najera16** [comment] 2020-04-11 23:24
- I just created the PR https://github.com/zeit/next.js/pull/11838 @timneutkens

**Comment by Timer** [comment] 2020-09-12 04:53
Closing this issue for same reason as above PR!

**Closed by Timer** 2020-09-12 04:53 UTC
Labels: good first issue

**Comment by balazsorban44** [comment] 2022-01-29 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
