### ISSUE TITLE
metadata doesn't change with <Link /> component in navbar, it does change while navigating from the browser

### ISSUE THREAD

**Issue by saver711** [vercel/next.js#51749] opened 2023-06-24 12:15 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
"dependencies": {
    "@apollo/client": "^3.8.0-beta.3",
    "@apollo/experimental-nextjs-app-support": "^0.2.1",
    "@types/node": "20.3.1",
    "@types/react": "18.2.13",
    "@types/react-dom": "18.2.6",
    "autoprefixer": "10.4.14",
    "eslint": "8.43.0",
    "eslint-config-next": "13.4.6",
    "graphql": "^16.6.0",
    "next": "^13.4.7",
    "next-auth": "^4.22.1",
    "postcss": "8.4.24",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwindcss": "3.3.2",
    "typescript": "5.1.3"
  },
  "devDependencies": {
    "@tailwindcss/aspect-ratio": "^0.4.2",
    "tailwindcss-rtl": "^0.9.0"
  }
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/saver711/nextjs13-starpi

### To Reproduce

yarn
yarn dev

### Describe the Bug

While navigating from the navbar with links, meta data doesn't change

### Expected Behavior

to change ~

**Comment by KingBael09** [comment] 2023-06-24 16:45
In my case the problem seem to be that navigation with link (after a fresh reload) changes the metadata once but after that metadata doesn't seem to get updated on any route change.

NextJS ver. 13.4.7

**Comment by IbnDaanis** [comment] 2023-06-25 01:54
I am having the same issue. Hopefully it gets fixed soon!

**Comment by shuding** [comment] 2023-06-26 11:16
This should be caused by `serverActions: true`, duplicate of #49409. Closing this one for now.

**Closed by shuding** 2023-06-26 11:16 UTC
Labels: template: bug
