### ISSUE TITLE
Next.JS environment variables break when I have target serverless and "!" in values

### ISSUE THREAD

**Issue by Adrian3PG** [vercel/next.js#15404] opened 2020-07-22 10:10 UTC
# Bug report

## Describe the bug

I'm not sure if I configured something wrong or if this is a bug, but I made a minimal repo to show the issue:
https://github.com/Adrian3PG/next-serverless-env-issue

In it I have a minimal Next.JS setup with:
````
const webpack = require("webpack");

module.exports = {
  target: "serverless",
  webpack: config => {
    const definePlugin = new webpack.DefinePlugin({
      AUTH_PASSWORD: JSON.stringify(process.env.AUTH_PASSWORD)
    });

    config.plugins.push(definePlugin);

    return config;
  }
};
````

I also have an env file with: AUTH_PASSWORD=abc!sfd

When I run `yarn dev`, it works fine. But when I run `yarn build` I get:

`Entry module not found: Error: Can't resolve 'sfd%22%7D%5D' in '/Users/adrian.uglean/workspace/next-serverless-env-issue'`.

I know ! is a special character for webpack imports (you can configure loaders with it). But I don't get why something is trying to import via the value of the environment variable. Might have nothing to do with the issue, but seems close to it.

**NOTE**: If I remove `target: "serverless"` everything works fine
 
Did I configure something wrong or is this a bug with target serverless? 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone 'https://github.com/Adrian3PG/next-serverless-env-issue' and install dependencies
2. Run 'yarn build' or 'npm run build'

## Expected behavior

Build works fine

## System information

- OS: macOS
- Version of Next.js: latest
- Version of Node.js: v10.15.0

**Comment by Timer** [comment] 2020-07-22 16:11
Can you please try `next@canary`?

**Comment by Adrian3PG** [comment] 2020-07-23 08:55
`yarn build` worked ok for the canary version. 

Will this make the 9.4.5 cut? It would help a lot if I had some sense of when this gets released, since we have a password that uses "!", and depending on the timeline, we might need to change it.

**Comment by Timer** [comment] 2020-07-23 15:14
`next@9.4.5-canary.43` is considered production ready and will be tagged as a stable version on Monday. You can safely ship it to production, so I'm closing this issue.

**Closed by Timer** 2020-07-23 15:14 UTC

**Comment by balazsorban44** [comment] 2022-01-29 20:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
