### ISSUE TITLE
Custom error page being reloaded every ~3 seconds

### ISSUE THREAD

**Issue by jooj123** [vercel/next.js#10024] opened 2020-01-09 23:44 UTC
# Bug report

I am currently using nextjs alongside express 
I have a custom error page (`_error.js`) and each time the error page is triggered it reloads itself every 3 seconds or so for some strange reason

I believe this is a bug with nextjs as i dont have anything special in my express app outside of next which would suggest it should reload every 3 seconds.

## Describe the bug

I have a custom error page (`_error.js`) and each time the error page is triggered it reloads itself every 3 seconds or so for some strange reason

## To Reproduce

Create an express app which has a router and route like:

```JavaScript
const next = require('next');

const dev = process.env.NODE_ENV !== 'production';
const nextApp = next({ dev });

const router = new express.Router({
  strict: true,
  caseSensitive: true,
});

// for simplicity use a basic route here /unknown/
router.get(`/unknown/`, (req, res) =>
  nextApp.render(req, res, '/error', {}),
);
```

then in my error page i have something like:

```JavaScript
function Error({ statusCode, message }) {
  return <div>Error Message: {message}</div>;
}

Error.getInitialProps = ({ res, err }) => {
  const statusCode = res ? res.statusCode : err ? err.statusCode : 404;

  return {
    statusCode,
    message: err ? err.message : 'Oops...',
  };
};

export default Error;
```

As soon as i goto /unknown/ route - the error page displays but next seems to reload it every ~3 seconds for some weird reason.

## Expected behavior

I expect it to goto the custom error page and not reload every 3 seconds.
This is bad because I dont want to overload the server with never ending requests from users to error pages (they should only get a loaded error page once)

## System information

- OS: macOS
- Browser: any
- Version of Next.js: ^9.1.7

<sub>[NEXT-1372](https://linear.app/vercel/issue/NEXT-1372/custom-error-page-being-reloaded-every-3-seconds)</sub>

**Comment by jooj123** [comment] 2020-01-09 23:48
Note - it looks similar to this one: https://github.com/zeit/next.js/issues/6973 but there is no error thrown in the custom error component
I have even tried to add a Error Boundary but that didnt make a difference

**Comment by jooj123** [comment] 2020-01-09 23:49
I guess i can try and fix this in a PR if i can be given some pointers - as i have never contributed to nextjs before

**Comment by jamesmosier** [comment] 2020-01-10 02:40
I followed your steps but was not able to reproduce. When I navigated to `/unknown/` the custom error page was shown as expected but there was no reload of the page every 3 seconds.

Is there any other code or steps I could follow to try to reproduce? Does this happen for you with a new Next project?

**Comment by jooj123** [comment] 2020-01-14 00:59
Hi - i have added a repo here which is based off a basic express generator and basic next setup - https://github.com/jooj123/test-nextjs

Added how to reproduce in the readme

**Comment by mattcarlotta** [comment] 2020-01-21 05:52
Same problem here. I'm not using a custom express server, but I noticed the `_error` page seems to trigger `getInitialProps` in the `_app.js` file over and over while in development.

Example repo: https://github.com/mattcarlotta/nextjs-ssr-kit

Steps to reproduce:
1. Clone the repo and install dependencies.
2. Add a `console.log("triggered _app.js getInitialProps")` to the `_app.js` file in its `getInitialProps`.
2. Go to http://localhost:3000/error
3. Check console for repetitive getInitialProps calls.

**Comment by jooj123** [comment] 2020-01-22 03:41
This one can be reproduced, can we remove the "Can't Reproduce" tag please?

**Comment by aoshi321** [comment] 2020-04-28 22:36
I'm also experiencing the same in development mode. @jooj123 were you able to resolve this.
@timneutkens is this currently being looked at thx

**Comment by mattcarlotta** [comment] 2020-04-29 01:27
A workaround I've found is to set up a custom [404 page](https://nextjs.org/docs/advanced-features/custom-error-page#customizing-the-404-page) so that if a user navigates to a page that doesn't exist, then they will land on the this 404 page instead of the server-side 500 page. That said, if the server itself has an error, then the problem will still occur in development.

**Comment by timneutkens** [comment] 2020-04-29 08:45
> @timneutkens is this currently being looked at thx

Not actively, it's on the backlog. There's hundreds of open issues currently so feel free to contribute and investigate this issue.

**Comment by Nefcanto** [comment] 2022-07-24 10:00
Still happening. Next.js 12.2.3 here. And it's extremely annoying.

**Comment by khtruong** [comment] 2022-08-31 17:38
Also running into this issue (Next.js 12.2.5).

**Comment by lodisy** [comment] 2022-11-21 11:03
Also happens with 13.0.3

**Comment by BrandNewLifeJackie26** [comment] 2023-01-10 04:18
> Also happens with 13.0.3

Hi @lodisy I am trying to solve this issue, could you please provide a repo that could reproduce this? I think it may be related to HMR, but I want to check if the newest version has fixed this issue. Thanks!

**Comment by majid-amiri** [comment] 2023-01-27 16:11
Hey, any updates on this?

**Comment by NOOBBase** [comment] 2023-02-06 13:47
A few years back they had the same issue:

https://github.com/vercel/next.js/issues/6973

Apparently it's tough to fix.....

**Comment by limury** [comment] 2023-02-08 13:09
As a temporary solution, using turbopack with the `npm next dev --turbo` command seems to fix it for me.

**Comment by iamshour** [comment] 2023-06-05 05:52
Encountering the same issue in Next 13.4.4. Very annoying tbh. Anything on this yet?

**Comment by SimonR07** [comment] 2023-06-06 08:51
hello, same for me ; (

**Comment by rlvk-tc** [comment] 2023-06-06 08:56
For me specifically, I was using the [next-translate](https://www.npmjs.com/package/next-translate) v1.6 in my project. But as soon as I updated to v2 the refreshing error stopped.

I'm not saying that it is caused by that package, but probably because of the error handling logic and incompatible packages.

**Comment by SimonR07** [comment] 2023-06-06 09:05
Hi @rlvk-tc  I use p5 on my not-found.js page, I thought it might come from that, but I also created a component just with a Hello and I have the same result, it reloads constantly. However, I also tried to build as you indicated in your previous message and the reloading stopped, strange!!!!

**Comment by 13kz** [comment] 2023-06-06 15:02
Hi there I've got this behaviour only in dev mode (npm run dev)

**Comment by studiolama** [comment] 2023-06-08 12:30
any solution ? and anyone know how to create 500 page in app structure ?

**Comment by jcsabin** [comment] 2023-06-10 09:34
Same issue for me thought it was my computer at first but it's not. Only happens when in npm run dev

**Comment by Gr33nLight** [comment] 2023-06-10 11:03
Same error Next 13.4.4. any updates?

**Comment by TunjiDev** [comment] 2023-06-10 16:23
Experiencing the same issue with next 13.4 in development

**Comment by ExHiraku** [comment] 2023-06-11 20:21
Experiencing this issue on 13.4.5, here are the packages I have installed if that helps:

- `@headlessui/react` **v1.7.15**
- `@heroicons/react` **v2.0.18**
- `autoprefixer` **v10.4.14**
- `eslint` **v8.42.0**
- `eslint-config-next` **v13.4.5**
- `next` **v13.4.5**
- `postcss` **v8.4.24**
- `react` **v18.2.0**
- `react-dom` **v18.2.0**
- `react-hot-toast` **v2.4.1**
- `tailwindcss` **v3.3.2**

**Comment by nicolaslima321** [comment] 2023-06-16 04:19
I got the same on Next 13.4.6

**Comment by Adnanear** [comment] 2023-06-22 14:32
Next 13.4.7 which is the latest today (2023-06-22) still has the same issue.

**Comment by e-lobo** [comment] 2023-07-01 13:34
this is still an issue.. my nextjs version is "next": "13.1.1"

**Comment by mryechkin** [comment] 2023-07-02 21:47
Just ran into this issue after upgrading to `13.4.7` from `13.1.1` and migrating to `app` dir. Never had this happen before with `pages`

**Comment by Sothatsit** [comment] 2023-07-05 10:25
I am also experiencing this issue with `Next.js v13.4.4`... very annoying

**Comment by einbulinda** [comment] 2023-07-11 15:59
also encountering the same in Next.js v13.4.7

**Comment by judeclark19** [comment] 2023-07-18 02:22
Allow me to be this week's commenter to report I am experiencing this behavior on 13.4.7

**Comment by timneutkens** [comment] 2023-07-18 08:22
This issue has already been triaged, we're going to work on it, there's other issues that have a higher priority though. Please don't post further comments if there is no additional information being provided. That includes not posting "version x still has this", it's not helpful, the issue is still open so you can assume it's not fixed in version x. Every comment pings everyone on the thread and takes time away from us investigating/fixing this issue. These will be hidden automatically.

**Comment by nicolaslima321** [comment] 2023-08-01 23:27
Ian found a way to make it works, just sharing fyi
https://github.com/vercel/next.js/discussions/40000#discussioncomment-6291368

**Comment by nicolaslima321** [comment] 2023-08-01 23:29
While the solution still in progress, Ian found a way to make it works, just sharing fyi
https://github.com/vercel/next.js/discussions/40000#discussioncomment-6291368

**Closed** 2023-08-23 23:25 UTC
Labels: good first issue, type: needs investigation, linear: next
