### ISSUE TITLE
ERR_HTTP_HEADERS_SENT when using getStaticProps

### ISSUE THREAD

**Issue by jon64digital** [vercel/next.js#14292] opened 2020-06-17 22:49 UTC
# Bug report

## Describe the bug

Compiling in dev mode when using getStaticProps produces the following error on the server:

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at DevServer.sendHTML (pathTo...\node_modules\next\dist\server\next-dev-server.js:23:5)
    at DevServer.render (pathTo...\node_modules\next\dist\next-server\server\next-server.js:49:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)

## System information

- OS: Windows
- Version of Next.js: 9.4.4
- Version of Node.js: 10.16.2

## Additional context

I'm not sure entirely what's happening but I know it's something to do with getInitialProps and I know it's showing in my VSCode console, not the browser console so it's happening as part of the server run of getStaticProps so here's my function....

```
export async function getStaticProps({ params, preview = false, previewData = {} }) {

    // Create full slug
    let slug = params.slug
    slug = slug.join('/')

    // Get Story
    const sbResult = await storyblokService.get(`cdn/stories/${slug}`, {})
    let story = sbResult && sbResult.data && sbResult.data.story ? sbResult.data.story : undefined


    // Return props
    return {
        unstable_revalidate: 1,
        props: { 
            story
        },
    }
```

**Comment by balazsorban44** [comment] 2020-06-18 08:06
Probably fixed on `canary`, either upgrade, or wait for it to get to stable. See https://github.com/vercel/next.js/issues/14186

**Closed** 2020-06-22 04:05 UTC

**Comment by balazsorban44** [comment] 2022-01-30 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
