### ISSUE TITLE
router.back() causes an error on intercepted route

### ISSUE THREAD

**Issue by Neutrlno** [vercel/next.js#65162] opened 2024-04-29 12:48 UTC
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/shy-sky-lnkhzt

### To Reproduce

1. Click "link to secondary"
2. Click "to signin" button
3. Click "back" button

### Current vs. Expected behavior

Current: on step 3 error occures. Expected: no error

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.3.0-canary.26 // There is a newer canary version (14.3.0-canary.29) available, please upgrade! 
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
```

### Which area(s) are affected? (Select all that apply)

Parallel & Intercepting Routes

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

### Additional context

The yellow error that occures in the sandbox console is like this(copied from my VSCode console):
Performing hard navigation because your application experienced an unrecoverable error. If this keeps occurring, please file a Next.js issue.

Reason: Segment mismatch
Last Action: server-patch

Current Tree: ["",{"children":["(auth)",{"children":["forgot-password",{"children":["__PAGE__",{},"/forgot-password","refresh"]},null,null]},null,null],"authModal":["__PAGE__",{"children":["__PAGE__",{},"/","refresh"]},"/","refresh"]},null,null,true]

Tree Patch Payload: ["__PAGE__",{}]

**Comment by shubhankartrivedi** [comment] 2024-05-03 22:08
```jsx
 <button
        onClick={() => {
          router.push("/signin");
          router.refresh();
        }}
      >
        {"to signin"}
      </button>
      ```
      
      Why you have `router.refresh()` after push?

**Comment by AbhiShake1** [comment] 2024-05-04 04:14
hello, i am unable to reproduce it in 14.3.0-canary.37. could you try and give a quick update on that version please?

**Comment by Neutrlno** [comment] 2024-05-06 10:00
#  Why you have `router.refresh()` after push?
Because it is a part of the issue. Actually, that is the way i tried to make intercepted routes work in my main app. If i didnt use router.refresh(); then i couldnt navigate to the intercepted page in some cases.

**Comment by Neutrlno** [comment] 2024-05-06 10:02
> ```js
>  <button
>         onClick={() => {
>           router.push("/signin");
>           router.refresh();
>         }}>
>         {"to signin"}
> </button>
> ```
> 
> ```
>   Why you have `router.refresh()` after push?
> ```

Because it is a part of the issue. Actually, that is the way i tried to make intercepted routes work in my main app. If i didnt use router.refresh(); then i couldnt navigate to the intercepted page in some cases.

**Comment by Neutrlno** [comment] 2024-05-06 10:19
> hello, i am unable to reproduce it in 14.3.0-canary.37. could you try and give a quick update on that version please?
error still exist both in the sandbx with the mentioned next version and in my main app

**Comment by ztanner** [comment] 2024-05-09 14:27
Hi @Neutrlno -- both of your reproductions seem to have this pattern of routing to a new page and triggering `router.refresh()` simultaneously. I think this is the source of the bugs, so I'd like to better understand why you added it so we can look into that, since I don't think it should be necessary and I could see it leading to confusing results. 

You mentioned:
> Actually, that is the way i tried to make intercepted routes work in my main app. If i didnt use router.refresh(); then i couldnt navigate to the intercepted page in some cases.

To me, that sounds like maybe you were having trouble with the soft navigation behavior described [here](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#active-state-and-navigation). Are you able to share an updated repro of what you weren't able to get working, without `router.refresh()`?

**Comment by Neutrlno** [comment] 2024-05-11 12:36
@ztanner i updated https://codesandbox.io/p/devbox/shy-sky-lnkhzt sandbox with extra buttons that don't use refresh. When using them, the modal closing and navigating from it work as expected just for the first time. When you continue navigating back and forward between secondary and signin - navigation just stops to work. I tried to add [...catchAll] with a page.tsx file that returns null in a @modal slot with no effect. I just want to implement a intercepted route modal window from which i can navigate to other routes. But i always fail. Help me achieve that By the way, `router.refresh()` approach works in a next 14.1.4 (except some 2% rare occasions).

**Comment by ztanner** [comment] 2024-05-13 21:16
Hi @Neutrlno -- it seems there was still a `router.refresh()` inside the "to secondary (no refresh)" button in `(.)signin/modal.tsx`.

I forked your Sandbox here, and added the catch-all, and it seems to work consistently for me:

https://codesandbox.io/p/devbox/fervent-currying-2m7dlz

**Comment by ztanner** [comment] 2024-05-20 21:07
I'm going to close this issue as I cannot reproduce and the above sandbox demonstrates correct behavior, but feel free to reach back out if you're unable to get it to work.

**Closed by ztanner** 2024-05-20 21:07 UTC
Labels: bug, Parallel & Intercepting Routes

**Comment by Neutrlno** [comment] 2024-05-21 09:08
> I'm going to close this issue as I cannot reproduce and the above sandbox demonstrates correct behavior, but feel free to reach back out if you're unable to get it to work.

Just tested it in my main app with [...catchAll] pattern - it works as expected and no issue arises.

> Hi @Neutrlno -- it seems there was still a `router.refresh()` inside the "to secondary (no refresh)" button in `(.)signin/modal.tsx`.
> 
> I forked your Sandbox here, and added the catch-all, and it seems to work consistently for me:
> 
> https://codesandbox.io/p/devbox/fervent-currying-2m7dlz

The router.refresh() method was used because, without [...catchAll] I couldn't navigate to the path; only the address bar was changed
