### ISSUE TITLE
experimental-edge unexpected error 500

### ISSUE THREAD

**Issue by willin** [vercel/next.js#43509] opened 2022-11-29 11:32 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

https://willin-wang-45sb83kse-willin.vercel.app/about

### Describe the Bug

![image](https://user-images.githubusercontent.com/1890238/204517877-6e9a35fd-7f35-4f45-b3b9-b694cd5e50f0.png)

Hi,

It looks like you are using App directory which is currently in beta release. We don't support it via official support channel. Please reach out using this link : https://github.com/vercel/next.js/issues/new/choose

Regards,
Swarnava Sengupta
▲ Customer Success Engineer at Vercel

### Expected Behavior

local works.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/willin/beta.willin.wang/commit/fd29f25f8835b2385c71b3f7f290b7f2cfa8088b

### To Reproduce

add runtime: 'experimental-edge’ 
 
default node works. (deployed to vercel)

**Comment by balazsorban44** [comment] 2022-11-29 15:27
Confirmed as a duplicate of #43458

**Closed by balazsorban44** 2022-11-29 15:27 UTC
Labels: template: bug, area: app
