### ISSUE TITLE
Default Locale is Generated Twice? Once with route, once without

### ISSUE THREAD

**Issue by knightspore** [vercel/next.js#26512] opened 2021-06-23 05:19 UTC
### What version of Next.js are you using?

11.0.1-canary.5

### What version of Node.js are you using?

12.21.0

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying your application?

Netlify

### Describe the Bug

When using a list of locales with sub-path routing, my designated default domain is generated twice - once with the sub-path added in, and once without as it should be.

### Expected Behavior

I expected the following paths to be generated:
```
/{path} (Default Locale)
/en-NZ/{path}
/en-CA/{path}
/fr-CA/{path}
/en-US/{path}
/en-GB/{path}
```

But instead I get the addition path `/en-AU/{path}` which renders all the standard non-prefixed pages a second time. 

When I checked other Next.js sites to see if they had the same issue, I was able to see the issue on none of them. 

### To Reproduce

This is my `next.config.js`:
```js
module.exports = {
  ...
  i18n: {
    locales: ["en-AU", "en-NZ", "en-CA", "fr-CA", "en-US", "en-GB"],
    defaultLocale: "en-AU",
  },
  ...
};
```

**Comment by Bast1onCZ** [comment] 2021-08-14 09:05
I've also encountered this issue with `next: 11.1.0`.

Moreover, when trying to redirect to cut `/en` unwanted default language prefix using `next.config.js`, I always get infinite redirect error for:
```
    redirects: () => {
        return [{
            source: '/en/:path',
            destination: '/:path',
            permanent: false,
            locale: false
        }]
    }
```

**Comment by ijjk** [comment] 2021-09-19 05:03
Hi, the default locale isn't generated twice (as can be seen by looking in the build output in `.next/server`) but doesn't currently force the default locale to be prefixed in the path or to not be which is a requested feature and is something we're tracking. 

I'm going to close this in favor of this feature request https://github.com/vercel/next.js/discussions/18419

**Closed by ijjk** 2021-09-19 05:03 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
