### ISSUE TITLE
Please Re-Open Issue #9851

### ISSUE THREAD

**Issue by machineghost** [vercel/next.js#24202] opened 2021-04-18 16:48 UTC
### What version of Next.js are you using?

Latest

### What version of Node.js are you using?

Latest

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying your application?

export

### Describe the Bug

Please re-open https://github.com/vercel/next.js/issues/9851.  It was marked fixed erroneously, and there are multiple comments to that effect.

This is a serious bug: lots of people have iPhones!

### Expected Behavior

Please see original ticket

### To Reproduce

Please see original ticket

**Comment by ijjk** [comment] 2021-04-19 01:52
Closing as no new information was provided, we have tests covering Safari 10.1 here https://github.com/vercel/next.js/runs/2374476653 which are passing correctly. If you are encountering problems on this version a minimal reproduction will be needed to allow investigating.

**Closed by ijjk** 2021-04-19 01:52 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 11:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
