### ISSUE TITLE
ImageProps type are not assignable to next/image

### ISSUE THREAD

**Issue by vinicius507** [vercel/next.js#26531] opened 2021-06-23 15:18 UTC
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

16.0.0

### What browser are you using?

Firefox

### What operating system are you using?

Arch Linux

### How are you deploying your application?

Vercel

### Describe the Bug

I made an Image component with `chakra-ui` Box as a wrapper for `next/image`. When I try to assign the props type, it gives me a TypeScript type error:

> Type '{ objectFit: "cover"; layout: "fill"; src: string | StaticImport; alt: string | undefined; }' is not assignable to type 'IntrinsicAttributes & ImageProps'.

`@chakra-ui/react` version: 1.6.3

### Expected Behavior

No type error.

### To Reproduce

Here's the component:

```ts
import { Box, BoxProps } from '@chakra-ui/react'
import NextImage, { ImageProps } from 'next/image'

export type NextChakraImageProps = Omit<BoxProps, 'as'> & ImageProps

export function NextChakraImage({ src, alt, ...rest }: NextChakraImageProps) {
	return (
		<Box {...rest}>
			<NextImage objectFit="cover" layout="fill" src={src} alt={alt} />
		</Box>
	)
}
```

**Comment by LamseyD** [comment] 2021-06-25 02:31
I think the issue should be relatively easy to fix. [The static import check is right here,](https://github.com/vercel/next.js/blob/canary/packages/next/client/image.tsx#L77). If you do src={`whatever`}, type of src is always object since you're wrapping the string with braces.

**Comment by LamseyD** [comment] 2021-06-25 02:41
I'm pretty sure that [the issue is here](https://github.com/vercel/next.js/blob/canary/packages/next/client/image.tsx#L77). Should be relatively easy to fix, whoever wrote that probably was going under the assumption that if the type is object then it must be a StaticImport. If you put `src = {imageURL}`, even though imageURL is a string, src is an object.

**Comment by Clee681** [comment] 2021-06-25 18:12
Yep, I'm hitting a similar issue as well.

### Basic Wrapper Component

```js
import Image, { ImageProps } from "next/image";

interface Props {
  imageProps: ImageProps;
}

export const ImageCard: React.FC<Props> = ({
  children,
  imageProps,
}) => {
  return (
    <div className="flex flex-col">
      <Image {...imageProps} />
      {children}
    </div>
  );
};
```

### Example Usage

I think using `ImageProps` should allow passing either the static image or a string `src` with `width` and `height`.

```js
import img from "public/img.png";

<ImageCard imageProps={img}>
```

**Comment by deadcoder0904** [comment] 2021-06-28 12:55
I faced the same issue & here is a temporary fix 🤜 https://github.com/vercel/next.js/issues/25440#issuecomment-852923894

There's another temporary fix by me if the above one doesn't work out 🤜 https://github.com/vercel/next.js/issues/25440#issuecomment-851421445

**Comment by styfle** [comment] 2021-06-28 21:09
@Clee681 Looks like you're passing incorrect types. It should be:

```ts
import img from "public/img.png";

<ImageCard imageProps={{src: img}}  />
```

**Comment by styfle** [comment] 2021-06-28 21:23
As @deadcoder0904 pointed out, the original post is a duplicate of #25440.

We could maybe improve this case at the expense of making the direct usage worse by making `width` & `height` optional when `layout=fill`.

Today this will error which is really nice because we don't use those props:

```jsx
<Image src="/me.jpg" layout="fill"  width={100} height={100} />
```

**Closed** 2021-07-07 19:15 UTC
Labels: kind: bug

**Comment by vinicius507** [comment] 2021-07-07 19:36
Thank you all for the attention and the fix. I know it was a minor issue but it is good to see such a fast fix.

**Comment by balazsorban44** [comment] 2022-01-28 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
