### ISSUE TITLE
Using recommended file extension to import TypeScript file causes error "Module not found"

### ISSUE THREAD

**Issue by jameshfisher** [vercel/next.js#33056] opened 2022-01-06 10:37 UTC
### Run `next info` (available from version 12.0.8 and up)

```
$ npx --no-install next --version
Next.js v12.0.7
```

### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.13.1

### What browser are you using?

n/a

### What operating system are you using?

Windows

### How are you deploying your application?

n/a

### Describe the Bug

When importing a TypeScript file using a `.js` file extension, Next fails with "Module not found"

```
$ npm run build

> build
> next build

info  - Checking validity of types...
info  - Creating an optimized production build...
Failed to compile.

./pages/index.tsx
Module not found: Can't resolve '../lib/helper.js' in 'C:\Users\james\dev\foobar\pages'


> Build failed because of webpack errors
```

### Expected Behavior

Next.js should resolve TypeScript imports. TypeScript recommends using the `.js` file extension to import TypeScript files:

* See examples at https://www.typescriptlang.org/docs/handbook/2/modules.html
* https://github.com/microsoft/TypeScript/issues/40878
* https://github.com/microsoft/TypeScript/issues/15479#issuecomment-300240856

My Next.js application is not an isolated project; it shares TypeScript modules with other environments that rely on this `.js` file extension.

### To Reproduce

1. `echo 'export const n = 5' > lib/helper.ts`
2. In `pages/index.tsx`, add: `import {n} from '../lib/helper.js'`
3. Run `next build` or `next dev`

**Comment by sigma54-ca** [comment] 2022-01-18 03:41
I'm having the same issue... have you found any temporary workarounds?

**Comment by jameshfisher** [comment] 2022-01-18 08:25
No workarounds - other than changing the import to `.ts` or removing the extension. Which then breaks other things that expect the `.js` extension. Not a good situation.

**Comment by timneutkens** [comment] 2022-01-18 08:43
Duplicate of #32237

**Closed by timneutkens** 2022-01-18 08:43 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-02-17 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
