### ISSUE TITLE
'Error: Invalid hook call. Hooks can only be called inside of the body of a function component'

### ISSUE THREAD

**Issue by olalekanteeblaze** [vercel/next.js#17592] opened 2020-10-03 17:37 UTC
# Bug report

## Describe the bug
I keep 'Error: Invalid hook call. Hooks can only be called inside of the body of a function component' after starting the next development server. This is the default next app with no configuration from me at all

## To Reproduce

1. Start a new next app with `npx create-next-app moshood.dev`
2. Start the next development server with `yarn dev`
3. Navigate to localhost:3000 in the browser after starting development server
4. Browser shows 'internal server Error' and terminal shows 'Error: Invalid hook call. Hooks can only be called inside of the body of a function component'

## Expected behavior
Start default next app in the browser successfully.

## Screenshots
![next error](https://user-images.githubusercontent.com/29545372/94998005-d5867180-05a6-11eb-8da0-0875ec22c9e6.png)
![scrnli_10_3_2020_6-29-40 PM](https://user-images.githubusercontent.com/29545372/94998013-e33bf700-05a6-11eb-80e3-cc32dffa71b6.png)

## System information

- OS: [Windows]
- Browser [chrome]
- Version of Next.js: [9.5.3]
- Version of Node.js: [e.g. 12.18.2]
- Version of React [16.13.1]
-Version of React-dom [16.13.1]

**Comment by timneutkens** [comment] 2020-10-05 09:16
```
Start a new next app with npx create-next-app moshood.dev
Start the next development server with yarn dev
Navigate to localhost:3000 in the browser after starting development server
```

These are the steps that set up a completely new Next.js application. Please provide a complete reproduction instead.

**Comment by mohesem** [comment] 2020-10-05 13:50
same error here

**Comment by olalekanteeblaze** [comment] 2020-10-05 14:25
Maybe I didn't explain this well. This error is exactly what I get immediately I navigate to localhost:3000 after starting a new Next.js application. The reproduction process is just starting a new Next.js App. Might be peculiar to me though

**Comment by iliasbhal** [comment] 2020-10-06 13:46
We experience the same issue as soon as we use the ^9.5 version. We had to downgrade to a 9.4(ish) version. 
We were relying on a [feature](https://nextjs.org/docs/api-reference/next.config.js/rewrites) only available on 9.5, so it makes me sad 😢 .

it is strange because when developing locally, everything is working fine.
But it's only when we deployed the app to our servers that we see the error. ( build and running locally works fine )

**Comment by einaralex** [comment] 2020-10-11 22:11
@iliasbhal Are you symlinking your `node_modules`in the deployment?
We were having the exact problem and skipping the symlink worked.
See more here: https://github.com/vercel/next.js/issues/16988

**Comment by nickpassarella** [comment] 2020-10-19 15:34
I'm getting this same issue on an existing project. I didn't make any major changes aside from an `npm install` so I don't understand it. I only have the issue when running `next dev`. `next build && next start` works without any issues.

I did a little debugging, and it looks like something is setting `ReactCurrentDispatcher.current` to `null`. It is initially defined, but eventually is set to `null` and triggers the invariant hook warning when `useContext` is called in the Document `Html` component.

I'm fairly new to Next, so I'm not sure if this is an issue with Next or React.

**Comment by nickpassarella** [comment] 2020-10-19 21:08
It looks like my issue is unrelated to @olalekanteeblaze's. I had a mistake in my `next.config.js` that I think was writing over `next` webpack externals. Perhaps this was affecting react versions under the hood?

**Comment by StEvUgnIn** [comment] 2020-10-26 13:36
Same problem since three days, after succesful build. Here the log: https://gist.github.com/StEvUgnIn/c74757a9efc9a3dbba6fb3c094f39bb0

**Comment by max-mayorov** [comment] 2020-12-08 21:20
Same problem here... Next.js 10.0.3...

**Comment by StEvUgnIn** [comment] 2020-12-13 20:04
This error was due to special characters (`.`) in the repository name. Change it to `www` and it should build successfully. If so, I invite to correct this mistake and close this issue.

**Comment by InsOpDe** [comment] 2020-12-31 12:30
#16369 fixed it for me.
Ive upgraded to `next@10.0.4` and `react@17.0.1` and now it works

**Comment by valentinoPereira** [comment] 2021-06-24 16:42
It's funny.. I get this error only when I run my nextjs project in https://github.com/Eugeny/terminus command line using powershell profile.

However when I run my project in powershell, I don't get this error.

**Comment by stereobooster** [comment] 2021-09-15 22:18
This is what solved problem for me.

In `next.config.js`:

```js
/** @type {import('next').NextConfig} */
module.exports = {
  webpack: (config, options) => {

    config.resolve.alias = {
      ...config.resolve.alias,
      react: require.resolve('react').replace('index.js', ''),
    };

    return config;
  },
};
```

**Comment by ijjk** [comment] 2021-09-19 16:47
Hi, this appears to be a duplicate of https://github.com/vercel/next.js/issues/16535 so I'm gonna close this in favor of that one for tracking this.

**Closed by ijjk** 2021-09-19 16:47 UTC
Labels: please add a complete reproduction
