### ISSUE TITLE
Adding middleware breaks 404 functionality on dynamic page for client side

### ISSUE THREAD

**Issue by TheMatrixan** [vercel/next.js#43953] opened 2022-12-12 08:30 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.7-canary.4
      eslint-config-next: N/A       
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/TheMatrixan/next-bug-middleware-dynamic-page

### To Reproduce

1. Go to home page, you will see list of links to 404, dynamic pages that exists and do not exists.
2. Go to `/dynamic/123` - this url should exists and should return dynamic component content - `DynamicPage`
3. Go to `/dynamic/789` - this url doesn't exist in dynamic path routes and when you go to that page, it will display `DynamicPage` instead of custom 404 page. BUT, when you refresh the page, it will display correct custom 404 page. 
4. When you delete that empty middleware, above mentioned bug will not occur. Just delete `middleware.ts` file and when you will click on link `/dynamic/789`, it will display correct 404 page.

### Describe the Bug

By adding just empty function as a middleware, when we navigate to page that doesn't exist in static paths, next will show empty dynamic page content on client side instead of 404. When we delete middleware, Next will correctly show 404 page for page that doesn't exist.

### Expected Behavior

link `/dynamic/789` should display custom 404 page on client side while navigating between pages.

### Which browser are you using? (if relevant)

Chrome 108.0.5359.95 (64-bits)

**Comment by TheMatrixan** [comment] 2022-12-27 12:27
Any updates?

**Comment by mataspetrikas** [comment] 2023-01-03 15:09
might be related or duplicate of the https://github.com/vercel/next.js/issues/44293.
it seems that that the default middleware respsonse handler from `NextResponse.next()` chokes on the 404 pages since the 13.0 (reproducible in 13.1.1 as well)

**Comment by kingdutch001** [comment] 2023-01-12 13:21
in Next.js, going from 17 to 18 changes the rendering code path to stop using renderToString for its streamable equivalent. The reason for this is that as indicated in the doc, renderToString does not support well Suspense and streaming, and we want Next.js to be able to use the full power of concurrent React, so we can't go back to renderToString
the streaming version of React is slower and that is corroborated by the React benchmark you linked, thus we can expect Next to also be slightly slower as well.
There's not much that is actionable here so I'm gonna go ahead and close the issue!

**Comment by dgtllion** [comment] 2023-01-19 14:01
+1 will be nice to have it fixed!

**Comment by JanKaifer** [comment] 2023-01-19 14:42
Closing as duplicate of https://github.com/vercel/next.js/issues/44293.

**Closed by JanKaifer** 2023-01-19 14:42 UTC
Labels: template: bug
