### ISSUE TITLE
sharp no longer optional since 10.0.4-canary.7

### ISSUE THREAD

**Issue by jorrit** [vercel/next.js#20456] opened 2020-12-24 12:34 UTC
# Bug report

## Describe the bug

Next.js has an optional dependency on sharp. This means that it should run without sharp present in node_modules.

PR #20035 broke this by adding `require.resolve('sharp')` without a try/catch to catch `MODULE_NOT_FOUND`.

I discovered this because sharp no longer installs with NPM 7 (see #20432).

## To Reproduce

npm i next@10.0.4-canary.7
rimraf node_modules/sharp
npm run build

> > Build error occurred
> Error: Cannot find module 'sharp'
> Require stack:
> - C:\Projects\ANWB\Travelhome-git\camper2-website\node_modules\next\dist\build\index.js
> - C:\Projects\ANWB\Travelhome-git\camper2-website\node_modules\next\dist\cli\next-build.js
> - C:\Projects\ANWB\Travelhome-git\camper2-website\node_modules\next\dist\bin\next
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
>     at Function.resolve (internal/modules/cjs/helpers.js:94:19)
>     at build (C:\Projects\ANWB\Travelhome-git\camper2-website\node_modules\next\dist\build\index.js:11:794) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'C:\\Projects\\ANWB\\Travelhome-git\\camper2-website\\node_modules\\next\\dist\\build\\index.js',
>     'C:\\Projects\\ANWB\\Travelhome-git\\camper2-website\\node_modules\\next\\dist\\cli\\next-build.js',
>     'C:\\Projects\\ANWB\\Travelhome-git\\camper2-website\\node_modules\\next\\dist\\bin\\next'
>   ]
> }

## Expected behavior

The site builds OK.

- OS: Windows or Linux (alpine in docker)
- Version of Next.js: 10.0.4-canary.7 and up
- Version of Node.js: 14 (latest)
- Deployment: fails on build

**Comment by jorrit** [comment] 2020-12-24 12:35
Perhaps a CI test that removes `sharp` after installing the dependencies would prevent this in the future.

**Comment by timneutkens** [comment] 2021-01-03 16:20
Feel free to send a PR!

**Comment by thien-do** [comment] 2021-01-04 17:24
Tks for the report and PR @jorrit !

> npm i next@10.0.4-canary.7

I don't really know why but this happens in 10.0.4 (the latest version, not the canary one) too

**Comment by jorrit** [comment] 2021-01-04 18:17
Canary-7 was the version the bug got introduced in, it is also in the later canary versions and the final version.

**Comment by iou90** [comment] 2021-01-07 07:24
> Tks for the report and PR @jorrit !
> 
> > npm i next@10.0.4-canary.7
> 
> I don't really know why but this happens in 10.0.4 (the latest version, not the canary one) too
> 
> ![image](https://user-images.githubusercontent.com/5953369/103561626-5ded1900-4eec-11eb-89ca-ab324d1512be.png)

The issue occurs with 10.0.4 & 10.0.5. But 10.0.3 is ok (build without sharp installed).

**Comment by davidgilbertson** [comment] 2021-01-08 01:50
I'm seeing this too. Everything builds fine on Windows and Mac, but fails when we deploy.

OS: Amazon Linux 2
Node: 12.20.0
npm: 6.14.8
Next: 10.0.4

**Comment by jhonalino** [comment] 2021-02-03 08:17
same issue. could not deploy to aws

**Comment by jhonalino** [comment] 2021-02-03 08:23
is there a temporary fix for this?

**Comment by ChristianPraiss** [comment] 2021-02-03 08:24
Downgrading to ```{"next": "10.0.3",}``` worked wonders for me ;)

**Comment by jhonalino** [comment] 2021-02-03 09:21
thank you much brother! unfortunately, it didn't work. I spent 8 hours trying to make this work on the beanstalk. no luck
went back to vercel and it worked in less than a minute. hopefully, there is official a guide for aws

**Comment by FireFart** [comment] 2021-02-08 15:34
Any update on this? This introduces so many new dependencies that previous docker images fail to build because this now requires sharp which reuqires python3 and so on. This currently prevents us from upgrading to the latest next.js version

**Comment by davidbailey00** [comment] 2021-02-08 15:36
@FireFart a PR is open to fix this (#20738) although the Next.js maintainers haven't responded to it yet

**Comment by genemators** [comment] 2021-02-08 21:54
brew install libvips and voila!

**Comment by onigoetz** [comment] 2021-02-08 21:59
@genemators If only that was that easy.

What about corporate environments that just can't download things from the internet for builds, only from an npm mirror ?
That's the reason this dependency was made optional in the first place.

**Comment by genemators** [comment] 2021-02-08 22:14
> @genemators If only that was that easy.
> 
> What about corporate environments that just can't download things from the internet for builds, only from an npm mirror ?
> That's the reason this dependency was made optional in the first place.

I dunno dude, this is just a temporary solution.

**Comment by cseas** [comment] 2021-02-12 10:37
Having "sharp" as a dependency is a bit of a problem on corporate systems because those terminals usually aren't allowed to fetch anything directly from GitHub which is exactly what the sharp install keeps trying to do.

Related StackOverflow thread:
https://stackoverflow.com/questions/65894000/install-sharp-without-github-fetch-for-nextjs-error-cannot-find-module-sharp

**Closed** 2021-02-18 10:23 UTC
Labels: kind: bug, point: 5

**Comment by robertveloso** [comment] 2021-02-20 03:25
Thanks for kodiakhq for the effort to replace sharp, but this was closed and the problem persist in the latest version.

Best regards.

**Comment by davidbailey00** [comment] 2021-02-20 10:22
@robertveloso A new stable version hasn't yet been released since the fix, but if you install the latest preview version (currently `10.0.8-canary.5`) you'll find it fixes the issue :)

**Comment by EduardoHidalgo** [comment] 2021-02-22 18:56
> brew install libvips

Thank you :D now im downloading all the deep web and google server files on my desktop <3

**Comment by genemators** [comment] 2021-02-25 08:21
> > brew install libvips
> 
> 
> 
> Thank you @genemators :D now im downloading all the deep web and google server files on my desktop <3

Bruh, it was just an option ...

**Comment by lewyuburi** [comment] 2021-02-26 18:10
For Arch Linux or Arch Linux based distro, try `sudo pacman -S  libvips`

**Comment by balazsorban44** [comment] 2022-01-28 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
