### ISSUE TITLE
Static site generation doesn't recognise correctly /{locale}/{locale} routes

### ISSUE THREAD

**Issue by MariannaKrzewinska** [vercel/next.js#33739] opened 2022-01-27 15:28 UTC
### Run `next info` (available from version 12.0.8 and up)

 Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.4.0 LTS Thu Jan 27 2022 16:14:22 GMT+0100 (Central European Standard Time)
    Binaries:
      Node: 14.16.0
      npm: 7.17.0
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 12.0.9
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.9

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Linux/MacOS

### How are you deploying your application?

next start

### Describe the Bug

I have an app that uses one locale for i18n, and then a two letter country code. Example URL: `/de/de`. 
The setup works correctly for routes where the country code is not one of the locales (e.g `/en/fr`) but fails for all country codes that are also locales (e.g. `/en/de`). 
It fails only for statically generated pages (with `getStaticPaths/Props` or without), server side rendered pages work correctly. 

### Expected Behavior

The app renders correctly statically generated pages for routes with two locales, the same way it does for server side rendered pages.

### To Reproduce

Link to the example code: https://stackblitz.com/edit/github-vc5urc-g5bzdn

1. Start the app with command `npm install && npx next dev`
2. Go to the path `/en/de/ssr` - works correctly
3. Go to the path `/en/de/static` - throws an error
4. Go to the path `/en/de/static-props` - page not found
5. Go to the path `/en/fr/static`- works correctly
6. Go to the path `/en/fr/static-props`- works correctly

**Comment by rebzden-baracoda** [comment] 2022-01-28 09:20
Same here: https://github.com/rebzden/i18n-test. I've been trying to debug it for two whole days 😞. The links to https://i18n-test-eta.vercel.app/en/test/en or https://i18n-test-eta.vercel.app/en/test/de fail but https://i18n-test-eta.vercel.app/en/test/randomtext work. 

Also is there really a need for getStaticPaths for the SSG? why can't we skip it and compile at build time props that will be added to all pages? If you don't provide getStaticProps then the [id] path is a static html page, that handles all "ids", but when you would want to add locale support you suddenly have to compile each new page even if you only need client side code + static json per locale. The requirement for getStaticPaths seems weird to me.

**Comment by rebzden-baracoda** [comment] 2022-01-28 09:23
This is an error that occurs on the serverless function. Please note that this error doesn't appear on the local reproduction after npm run build && npm start.
![image](https://user-images.githubusercontent.com/76430732/151520881-0c5f4f92-f9e5-406e-9f3c-99ec21f34e71.png)

**Comment by balazsorban44** [comment] 2022-02-16 22:50
This seems to be a duplicate of #21714, closing in favor. Thanks for reporting anyway! :pray:

**Closed by balazsorban44** 2022-02-16 22:50 UTC
Labels: template: bug, area: I18n

**Comment by rebzden-baracoda** [comment] 2022-02-17 06:59
thanks @balazsorban44, could you also explain why is there a requirement for getStaticPaths for the SSG? why can't we skip it and compile at build time props that will be added to all pages? If you don't provide getStaticProps then the [id] path is a static html page, that handles all "ids", but when you would want to add locale support you suddenly have to compile each new page even if you only need client side code + static json per locale. The requirement for getStaticPaths seems weird to me.
