### ISSUE TITLE
[NEXT-1144] Parallel Routes do not apply individual `loading.tsx` as described in documentation

### ISSUE THREAD

**Issue by brunocangs** [vercel/next.js#49243] opened 2023-05-04 20:15 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.19.1
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.3.0
    Relevant packages:
      next: 13.3.5-canary.12
      eslint-config-next: 13.4.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/brunocangs/next-app-parallel-issue

### To Reproduce

Run the project with `yarn dev` and navigate to `http://localhost:3000`

### Describe the Bug

When using Parallel Routes (e.g. `/app/@slot/page.tsx`), the `@slot`'s `loading.tsx` states are never called or displayed.

The current beahviours observed even differ in `dev` and `prod`, as seen in the videos references.

**Prod Link: https://next-app-parallel-issue.vercel.app/**

Dev behaviour:
- Layout displays:
  - First slot (`@slot/page.tsx`) is async, so it displays a loading state. However this is the page's loading state, not the slot loading state.
  - Second slot is not async, so it immediately displays. The Suspended component displays it's loading state correctly
- Suspended component on second slots loads
- Eventually First slot loads and displays it's suspended component correctly.
- Suspended component on first slot loads

https://user-images.githubusercontent.com/30100875/236318280-294f6a0f-1809-4756-bdd1-da1ca7f2d792.mov

Prod behaviour:

- Everything gets server loaded and awaited. The parts that would require basic suspending get optimized and no loading states are displayed.

I didn't include a prod video as it would only be a page reload

### Expected Behavior

It is expected that, as mentioned in the documentation, the loading state for each of the slots will be correctly displayed per the image below
![image](https://user-images.githubusercontent.com/30100875/236316511-29695ff0-4051-4fe9-b565-7a8be44f5302.png)

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

<sub>[NEXT-1144](https://linear.app/vercel/issue/NEXT-1144/parallel-routes-do-not-apply-individual-loadingtsx-as-described-in)</sub>

**Comment by satarovbekzhan** [comment] 2023-05-10 05:52
Same for me!

**Comment by luisorbaiceta** [comment] 2023-05-10 10:21
Yes. In this case the documentation is not describing the current behavior and is misleading. The loading and error components are being applied as follows:

![image](https://github.com/vercel/next.js/assets/44276180/afb8c147-b3d4-452b-84cc-28c5cbeb3499)
![image](https://github.com/vercel/next.js/assets/44276180/48eb65f6-4229-4eb7-b6a2-f2e34dbf2155)

Seems that the root loading and error components are applied separately to each parallel route. This is inconvenient as precisely the goal of parallel routing is being able to manage separate parts of the UI that are not related with each other at the same time.

**Comment by satarovbekzhan** [comment] 2023-05-15 13:06
Any updates @timneutkens?

**Comment by timneutkens** [comment] 2023-05-15 15:47
You can temporarily put it in a route group `app/@something/(myroutegroup)/loading.tsx`.

**Comment by tomsseisums** [comment] 2023-05-17 09:12
It seems that `error.tsx` is also affected?

**Comment by tomsseisums** [comment] 2023-05-17 09:24
And @timneutkens the route group doesn't work for me on `v13.4.2`, for neither, both `loading.tsx` and `error.tsx` seem to be ignored.

**Comment by zanzlender** [comment] 2023-05-22 09:48
Can confirm... But isn't this supposed to work like this? It just hidrates the component with the new data?

https://github.com/vercel/next.js/assets/44570474/24eb4256-6dde-45f3-b7ec-a269a9e84b5b

**Comment by tresorama** [comment] 2023-05-22 12:14
#49588 
#50107

**Comment by cprussin** [comment] 2023-05-25 17:07
FWIW in my testing using a default state (i.e. `default.jsx`) in a parallel route also doesn't trigger a loading state, even with the temporary route group fix that @timneutkens suggested.

**Comment by FranzaLeny** [comment] 2023-06-02 08:03
I am functioning normally

https://github.com/vercel/next.js/assets/66564146/9d83ac0b-b853-4be9-b184-3e236eb9f3cc

![image](https://github.com/vercel/next.js/assets/66564146/d75f9dc3-6dae-4f8f-a902-59f63d036bba)

**Comment by danielvanc** [comment] 2023-06-18 14:04
> You can temporarily put it in a route group `app/@something/(myroutegroup)/loading.tsx`.

Hey @timneutkens, could we have an estimate of timeline on this feature, please? 

It shouldn't be in the docs if you can't currently do what the docs are demonstrating (without resorting to a work around).

**Comment by Jon1VK** [comment] 2023-06-18 19:26
Also the layout file inside a parallel route is ignored. For example /@team/layout.tsx will not be rendered. With /@team/(__workaround)/layout.tsx it works currently, but it is not optimal to use such hacks.

**Comment by jvanmaaren** [comment] 2023-06-21 09:29
FYI the route group hack doesn't seem to work in combination with a default.tsx:
https://github.com/vercel/next.js/issues/48090

**Comment by TommySorensen** [comment] 2023-06-22 12:18
I'm not sure its fixed since i haven't had time to check. But they fixed some issues lately https://github.com/vercel/next.js/pull/51413

**Comment by caturbgs** [comment] 2023-06-22 15:50
I think it's finally getting fixed, my current code that using `React.Suspense` is getting overwritten using loading component `loading.tsx` on the recent version _**13.4.7**_.

**Comment by danielvanc** [comment] 2023-06-22 19:51
I can confirm that #51413 has fixed these issues. 🥳

**Comment by tresorama** [comment] 2023-06-23 03:11
It's fixed with 13.4.7 for me to
[codesandbox demo](https://codesandbox.io/p/github/tresorama/test-next-app-directory/draft/test-parallel-routes-error-with13-4-7?file=%2Fpackage.json%3A19%2C14&selection=%5B%7B%22endColumn%22%3A49%2C%22endLineNumber%22%3A6%2C%22startColumn%22%3A49%2C%22startLineNumber%22%3A6%7D%5D&layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clj7z93ow009m3b6nfoiv66p5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clj7z93ow009n3b6nsjf1co79%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B42.96849640018311%252C57.03150359981689%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clj7z93ow009m3b6nfoiv66p5%2522%253A%257B%2522id%2522%253A%2522clj7z93ow009m3b6nfoiv66p5%2522%252C%2522activeTabId%2522%253A%2522clj7zpq8c04jn3b6nylerrn77%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clj7zb1vc01bs3b6n6y7dcn2w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fapp%252Fjsonplaceholders%252F%2540todos%252Ferror.tsx%2522%252C%2522id%2522%253A%2522clj7znsmp042u3b6n29fabxtw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fapp%252Fjsonplaceholders%252F%2540posts%252Ferror.tsx%2522%252C%2522id%2522%253A%2522clj7zojib049d3b6nv5mgvv4k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fapp%252Fjsonplaceholders%252F%2540todos%252Floading.tsx%2522%252C%2522id%2522%253A%2522clj7zpq8c04jn3b6nylerrn77%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clj7z93ow009n3b6nsjf1co79%2522%253A%257B%2522id%2522%253A%2522clj7z93ow009n3b6nsjf1co79%2522%252C%2522activeTabId%2522%253A%2522clj7zhkx303le3b6nkww12vgp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clj7zdtyl02zn3b6nm4b9mzhh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clj7zdymy001nfoj52cr61l41%2522%257D%252C%257B%2522id%2522%253A%2522clj7zhcmi03e23b6n3r2sw7wg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clj7zhkx303le3b6nkww12vgp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fjsonplaceholders%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A13.371757750135941%257D)

**Comment by run4w4y** [comment] 2023-06-23 09:28
Cannot confirm that it works for me on `13.4.7` with `default.tsx` present :(
So I don't think the issue is completely resolved unfortunately

**Comment by MaKTaiL** [comment] 2023-08-30 21:26
I'm having the same issue but with layout.tsx. I had to apply the solution on https://github.com/vercel/next.js/issues/49243#issuecomment-1548111858 of creating a (group) inside each of the parallel routes so the nested layouts could finally work:

home
├── @dashboard
│   └── (dashboard)
│        ├── layout.tsx
│        └── page.tsx
├── @login
│   └── (login)
│        ├── layout.tsx
│        └── page.tsx
└─ layout.tsx

**Comment by hckhanh** [comment] 2023-09-02 04:30
In my case, only production build is affected. I can run correctly in dev mode.

**Comment by Sh031224** [comment] 2023-09-04 04:39
```
/home
├── @categories
│        ├── layout.tsx
│        └── page.tsx
├── @posts
│        ├── layout.tsx
│        └── page.tsx
└─ layout.tsx
```

For me the layout didn't work only on production builds either.

**Comment by NCSmit** [comment] 2023-10-07 18:39
Still encountering this error on v13.5^
This routing method works correctly in 13.4.7 but it seems the bug has re-appeared in 13.5^.

Hoping for a fix soon :(

**Comment by Shameekh-Naveed** [comment] 2023-10-16 00:19
Still encountering on v13.5.2

**Comment by LuisRuda** [comment] 2023-11-28 18:45
In version 13.5.7 it's working here.

**Comment by NCSmit** [comment] 2023-11-30 22:37
@Shameekh-Naveed @jonatassales 
Hey guys, mind sharing your folder structures or code? Perhaps I am able to help resolve the issues you're encountering!

**Comment by ztanner** [comment] 2023-12-05 23:28
Hi all -- the original reproduction in this thread seems to be behaving correctly (testing against the latest Next.js canary). 

For those commenting on the loading state not appearing in production builds: the examples that have been shared indicate that your pages can be statically generated (learn more about dynamic rendering [here](https://nextjs.org/docs/app/building-your-application/rendering/server-components#dynamic-rendering)). In other words, at build time, Next.js is prefetching your routes and generating static HTML. Once served to the user, since the page could be completely statically generated, there's no loading boundary served to the user as there's nothing to wait for.

If anyone is still running into problems here, please open a new issue with a minimal reproduction and we'll take a look. As the original reproduction shared in this issue is now working, I'm going to close this.

**Closed by ztanner** 2023-12-05 23:28 UTC
Labels: template: bug, area: Routing, area: app, linear: next

**Comment by Jon1VK** [comment] 2023-12-06 14:54
@ztanner What about a situation where a site has dynamic routes and not all of the dynamic routes are prerendered on build time. Let's say we have a dynamic route `/[page]` and only routes `/1` and `/2` were generated on build. Now when the first user navigates to `/3`, they have to wait for the whole page to be generated without any shown loading states. 

In my opinion the loading states should be also rendered in that situation but now the UI is just stuck waiting for the whole page generation to be finished and sent to the client after which the site navigates to the page. It is quite horrible UX for the first user that tries to navigate to a page which is static but was not generated on build time.

**Comment by jainmohit2001** [comment] 2023-12-12 09:35
Hi @ztanner.
I have the same problem listed in this GitHub issue https://github.com/vercel/next.js/issues/59463. I have created a vercel deployment as well for the same.

**Comment by MohammadElokour** [comment] 2023-12-13 11:26
I'm on next 14.0.0,  and the "layout.tsx" also sometimes doesn't work.

I have multiple parallel routes all with "page.tsx" and "layout.tsx" and one of these routes out of all of them wont render the "layout.tsx" (definitely a head scratcher), my use case is mainly to have a parent layout with multiple children as appose to giving each parallel layout separate "error.tsx" and "loading.tsx"

I ended up using the same route group hack as suggested above to solve the issue, here is my folder structure as of now:
![image](https://github.com/vercel/next.js/assets/48622340/f4d43c8a-8134-4910-947b-5c2d07ff2eb9)

**Comment by fiasco** [comment] 2023-12-20 20:17
I have the same issue with 13.5.6
