### ISSUE TITLE
Custom Logger

### ISSUE THREAD

**Issue by DoroGi** [vercel/next.js#16314] opened 2020-08-18 15:20 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Hi, we are using Next.js with a custom express server, with a solution similar to https://nextjs.org/docs/advanced-features/custom-server. We noticed that the error middleware of express was never invoked even when deliberately throwing inside a getInitialProps or a getServerSideProps.

Snooping around Next source code, we found these lines: https://github.com/vercel/next.js/blob/8a489e24bcb6141ad706e1527b77f3ff38940b6d/packages/next/next-server/server/next-server.ts#L285-L291
This effectively prevents us from formatting the logs like we would like, for example in JSON, adding context info from express.js.

## Describe the solution you'd like

We would like a way to done at least one of the two:
1) Tell Next Handler to throw on Error, so we can catch it from Express.
2) Inject some kind of logger configuration, for example to specify the format or some additional infos.

## Describe alternatives you've considered

The solution we are trying now is to silence the logs of next (using the quiet option) and adding a "try catch" to the getInitialProps of our custom App.js. We are kinda scared to use the quiet option though, and we would like a more "official" solution to this.

**Comment by Janpot** [comment] 2020-08-18 15:53
duplicate of https://github.com/vercel/next.js/issues/4808

**Closed by Janpot** 2020-08-18 15:53 UTC

**Comment by balazsorban44** [comment] 2022-01-29 17:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
