### ISSUE TITLE
Postcss config broken in next@10

### ISSUE THREAD

**Issue by jescalan** [vercel/next.js#18808] opened 2020-11-04 19:27 UTC
# Bug report

## Describe the bug

In version 10, next.js upgraded the postcss version from `7` to `8`. This version unfortunately [is not compatible with postcss-preset-env](https://github.com/csstools/postcss-preset-env/issues/191), which is [used as a default by nextjs internally](https://github.com/vercel/next.js/blob/canary/packages/next/build/webpack/config/blocks/css/plugins.ts#L89).

This is kind of a big problem for anyone using postcss. Assuming that we don't want to back out and downgrade the postcss version in nextjs, and that preset-env will not soon become compatible with `postcss@8`, which i think is a safe assumption judging by [this issue](https://github.com/csstools/postcss-preset-env/issues/191), I think the only remaining option may be to either not default preset-env within nextjs at all, or break apart preset-env to its parts and build our own postcss-8-comptible preset-env, then include that with next.js.

## To Reproduce

I have created a full reproduction based on `create-next-app` here: https://github.com/jescalan/next-10-postcss-bug-repro/tree/main

Just run it with `next dev` to see the error. In this case, I turned on nesting and added a single nested selector -- the css breaks immediately as nesting is not processed by postcss. If you run the same thing with `next@9` it will work fine.

## System information

- OS: macOS
- Version of Next.js: 10.0.0
- Version of Node.js: 12.13.0

**Comment by Timer** [comment] 2020-11-06 18:09
cc @ai

**Comment by ai** [comment] 2020-11-06 18:37
PostCSS 8 supports all PostCSS 7 plugins. It should work with `postcss-preset-env` as well.

Do we have some exact problems? Or you just worry that `postcss-preset-env` was not updated to PostCSS 8 API?

**Comment by Timer** [comment] 2020-11-12 17:47
This seems to be working as expected @jescalan. Next.js does not support the extensionless `.postcssrc` file.

See the documentation:
https://nextjs.org/docs/advanced-features/customizing-postcss-config#customizing-plugins

If the `.postcssrc` file was previously working, this must've been a bug in `postcss-loader` that was fixed by upgrading (we told `postcss-loader` not to try to autoload configuration).

When I follow our docs on customization, it works as expected:
![image](https://user-images.githubusercontent.com/616428/98976089-eea70a00-24e4-11eb-9cce-a137e6e61702.png)


With `.postcssrc.json`:
```json
{
  "plugins": [
    "postcss-flexbugs-fixes",
    [
      "postcss-preset-env",
      {
        "autoprefixer": {
          "flexbox": "no-2009"
        },
        "stage": 3,
        "features": {
          "custom-properties": false,
          "nesting-rules": true
        }
      }
    ]
  ]
}
```

You could also use [`postcss-nested`](https://github.com/postcss/postcss-nested) instead:
```json
{
  "plugins": [
    "postcss-flexbugs-fixes",
    "postcss-nested"
  ]
}
```

I'm not sure what in the pipeline was respecting `.postcssrc` before. But, since this was always the intended behavior, we'll leave it for Next.js 10.

**Closed by Timer** 2020-11-12 17:47 UTC
Labels: kind: bug, point: 3, priority: p1

**Comment by deadcoder0904** [comment] 2021-05-18 10:37
@Timer I am using a similar config & I tried both `postcss-preset-env` & `postcss-nested` → https://github.com/vercel/next.js/discussions/25222 but it doesn't work.

**Comment by balazsorban44** [comment] 2022-01-28 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
