### ISSUE TITLE
NextJS production CSS build

### ISSUE THREAD

**Issue by amirh3n** [vercel/next.js#14624] opened 2020-06-27 12:04 UTC
Hello,
I have Custom CSS files for different layouts and there is no problem in dev mode but when I publish my app in production mode Nextjs combine all CSS and makes problem for my layouts.

**Comment by IamLizu** [comment] 2020-06-27 14:30
> makes problem for my layouts

I am guess your are using CSS modules ([component level css](https://nextjs.org/docs/basic-features/built-in-css-support#adding-component-level-css:~:text=Adding%20Component%2DLevel%20CSS)). Please explain or demonstrate what problem are you facing exactly.

**Comment by jamesmosier** [comment] 2020-06-27 18:54
Duplicate of https://github.com/vercel/next.js/discussions/14625. Closing in favor of that Discussion.

**Closed by jamesmosier** 2020-06-27 18:54 UTC

**Comment by balazsorban44** [comment] 2022-01-30 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
