### ISSUE TITLE
Parallel route still rendered when check condition already checked

### ISSUE THREAD

**Issue by duypham90** [vercel/next.js#60418] opened 2024-01-09 10:27 UTC
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/nextjs-14-parallel-routes-bu-7r7j9m?file=%2Fapp%2Flayout.tsx%3A6%2C8

### To Reproduce

1.  Visit my codesanbox
2. View terminal console
3. See the console log message: `CALL API and RENDER Login MODAL`

![CleanShot 2024-01-09 at 17 26 46@2x](https://github.com/vercel/next.js/assets/24804332/4f49a481-1915-4cb2-b1e7-58a9977c4a72)

### Current vs. Expected behavior

Expected:
When visit home page I expected if we use condition to check render Login Modal  page the modal Login will not render

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.0.5-canary.45
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by ali-idrizi** [comment] 2024-01-12 20:25
Related https://github.com/vercel/next.js/issues/53292

**Comment by pumkindev** [comment] 2024-01-14 16:04
checkout this article could be related: https://dev.to/zmzlois/troubleshooting-parallel-routing-in-nextjs-pdo

**Comment by samcx** [comment] 2024-05-04 01:25
Closing since this is a duplicate of this → https://github.com/vercel/next.js/issues/53292.

**Closed by samcx** 2024-05-04 01:25 UTC
Labels: bug
