### ISSUE TITLE
TypeError: Object(...) is not a function | Error occurs after running default project created using create-next-app 

### ISSUE THREAD

**Issue by keshav2010** [vercel/next.js#21038] opened 2021-01-12 19:12 UTC
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

12.18.3

**What browser are you using?**

firefox

**What operating system are you using?**

windows 10 home

**How are you deploying your application?**

localhost

**Describe the Bug**

1. ran "create-next-app my_project" 
2. executed the default template code

**Expected Behavior**

the webpage opens up

**To Reproduce**
 >> Must have 10.0.5 version, Issue not found when using 9.5.1 version of nextjs.

**Comment by timneutkens** [comment] 2021-01-13 16:50
This is not reproducible. Going to close the issue as there is no reproduction provided.

**Closed by timneutkens** 2021-01-13 16:50 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 20:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
