### ISSUE TITLE
Internet Explorer 11 doesn't work

### ISSUE THREAD

**Issue by tomaskallup** [vercel/next.js#30262] opened 2021-10-25 12:59 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

12.18.1

### What browser are you using?

Internet Explorer 11

### What operating system are you using?

Linux (using Win 10 VM for IE)

### How are you deploying your application?

This happens on localhost

### Describe the Bug

Few months ago we updated next 10 and enabled webpack 5 support. We also updated `react-int` which required use of `sanitize-html` and it seems that broke our builds for IE 11. I've tried to add `sanitize-html` along with `escape-string-regexp` to `transpile-modules` to make sure it's IE compatible, but it still creates a weird build. Right now it crashes because of a syntax error which seems to come from `postcss`, but adding that into `transpile-modules` does nothing.

Also looking into the resulting build, there is a bunch of arrow functions and other suff, that hasn't been there before. Is it possible webpack 5 somehow breaks the IE compatibility?

### Expected Behavior

Production build should be IE 11 compatible.

### To Reproduce

I've created a [discussions post](https://github.com/vercel/next.js/discussions/29327#discussion-3588701) which contains reproduction, but I got no response.

**Comment by timneutkens** [comment] 2021-10-31 10:50
This has been fixed on next@canary. Thanks for your report.

**Closed by timneutkens** 2021-10-31 10:50 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
