### ISSUE TITLE
`src/pages/_middleware` running for requests outside of `pages` folder

### ISSUE THREAD

**Issue by jonahallibone** [vercel/next.js#31361] opened 2021-11-12 22:04 UTC
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Our project utilizes a `src` folder to hold our `pages` directory. Inside we added a `_middleware.js`. If I log the `req` object inside the middleware, it seems to be running for not only our pages, but for our assets as well.

<img width="1277" alt="Screen Shot 2021-11-12 at 5 01 29 PM" src="https://user-images.githubusercontent.com/8886318/141539762-675d0633-46cf-4aba-860d-92ac020e5f7d.png">

This has had the effect of breakout out `site.webmanifest` failing requests on URLs inside our `next.config.js` rewrites array, and causing certain edge functions to time out.

<img width="436" alt="Screen Shot 2021-11-12 at 5 15 08 PM" src="https://user-images.githubusercontent.com/8886318/141540980-ec6dd492-e92d-421d-a9ad-abd1cdd58ed6.png">
This is our middleware which ignores a rewrite to `/system` and only attempts to run on req objects containing a page name. This works locally however fails when deployed to Vercel.

```js
import { NextResponse } from "next/server";

const middleware = (req) => {
  const { page, nextUrl } = req;

  const isActualPage = !!page.name;

  const hasCookies =
    req.cookies.refresh && req.cookies.payload && req.cookies.access;

  const publicPage = /^\/(signin|signup).*$/.test(nextUrl.pathname);

  const companyOrInvestorPage = /^\/(company|investor)\/.*$/.test(
    nextUrl.pathname
  );

  const systemUrl = /^\/(system).*$/.test(nextUrl.pathname);

  if (systemUrl || !isActualPage) {
    return NextResponse.next();
  }

  if (isActualPage && !publicPage && !companyOrInvestorPage && !hasCookies) {
    return NextResponse.redirect(`/signin?redirect=${nextUrl.pathname}`);
  }

  if (isActualPage && publicPage && hasCookies) {
    return NextResponse.redirect(`/`);
  }

  return NextResponse.next();
};

export default middleware;


```

### Expected Behavior

We expected this to only run on the request to the page, so we would not have to ignore certain path names

### To Reproduce

Create a project with a rewrite, a `src/pages` folder with a `_middleware.js` inside.

**Comment by edelfrade** [comment] 2021-11-14 16:50
Possible duplicate of #31324

**Comment by will-stone** [comment] 2021-11-17 16:24
@jonahallibone are you finding your `const isActualPage = !!page.name;` check is still working for you? I was doing this too but now I'm getting `undefined` 😖

**Comment by jonahallibone** [comment] 2021-11-17 18:36
> @jonahallibone are you finding your `const isActualPage = !!page.name;` check is still working for you? I was doing this too but now I'm getting `undefined` 😖

Yea it seems to be working for me. Is your problem local or deployed?

**Comment by jonahallibone** [comment] 2021-11-17 20:13
As an addendum to the above issue, I sometimes get a timeout on that middleware which seems suspect because it's a pretty simple script

**Comment by will-stone** [comment] 2021-11-17 20:45
@jonahallibone Was just on local `next dev`.

**Comment by javivelasco** [comment] 2022-06-17 18:06
With the most recent canary this became obsolete as we revamped the way you define middleware to avoid tightening it to `pages`. Instead you can define a matcher in a similar way it works for configuration rewrites and redirects so this shouldn't be an issue anymore.

Thanks for reporting!

**Closed by javivelasco** 2022-06-17 18:06 UTC
Labels: template: bug

**Comment by jonahallibone** [comment] 2022-06-20 05:57
@javivelasco great! Is this documented anywhere yet?
