### ISSUE TITLE
nextjs 13 uses () in the app folder, and the size is 0 after packaging

### ISSUE THREAD

**Issue by Toursslivers** [vercel/next.js#49579] opened 2023-05-10 09:03 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.17
      pnpm: 7.5.2
    Relevant packages:
      next: 13.4.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/vercel/next.js/tree/canary/examples/reproduction-template-app-dir

### To Reproduce

yarn build

### Describe the Bug

![image](https://github.com/vercel/next.js/assets/71162666/1278c81e-d17f-46ee-a948-525237621ced)

### Expected Behavior

have size

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

docker

**Comment by timneutkens** [comment] 2023-05-11 12:34
Duplicate of #48404

**Closed by timneutkens** 2023-05-11 12:34 UTC
Labels: template: bug, area: app
