### ISSUE TITLE
`Error: Cannot access .prototype on the server` when rendering a dotted client component without a key

### ISSUE THREAD

**Issue by tom-sherman** [vercel/next.js#52415] opened 2023-07-07 19:44 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.13.0
      npm: 8.13.2
      Yarn: 1.22.19
      pnpm: 8.6.6
    Relevant Packages:
      next: 13.4.10-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/tom-sherman/nextjs-key-prototype-bug

### To Reproduce

1. `import *` a "use client" module
2. Render an exported component from that module without a key in a server component eg. `<Client.Component>` in an array without a key
3. `next dev`

### Describe the Bug

Receive an error on first load after starting the dev server

```
 error node_modules/.pnpm/next@13.4.10-canary.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-flight-loader/module-proxy.js (51:14) @ Object.get
- error Error: Cannot access .prototype on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.
    at Component (./app/component.tsx:11:87)
    at stringify (<anonymous>)
```

This error goes away after refresh

### Expected Behavior

The component should render without errors and I should receive a missing key warning.

<sub>[NEXT-1452](https://linear.app/vercel/issue/NEXT-1452/error-cannot-access-prototype-on-the-server-when-rendering-a-dotted)</sub>

**Comment by sreuter** [comment] 2023-07-18 09:07
This also happened to me when doing a `.map` over some images using and then returning the `next/image` component. It seems like adding the missing `key` attribute fixed it, but the error was super confusing.

**Comment by timneutkens** [comment] 2023-07-18 12:14
Did some digging and found why this happens, it's specifically related to the way [`setCurrentlyValidatingElement` is called here](https://github.com/facebook/react/blob/9f4fbec5f7bb639be6dac438f9da5f032ae12c15/packages/react/src/ReactElementValidator.js#L149-L156) in React reads `.prototype` in [`shouldConstruct`](https://github.com/facebook/react/blob/main/packages/react-devtools-shared/src/backend/DevToolsComponentStackFrame.js#L220-L223). Specifically [here](https://github.com/facebook/react/blob/main/packages/react-devtools-shared/src/backend/DevToolsComponentStackFrame.js#L239).

I'll ask @acdlite to have a look, seems like a bug in React 👍

**Comment by kunwar-11** [comment] 2023-08-01 15:07
any fix for this issue ?

**Comment by tom-sherman** [comment] 2023-08-01 15:32
The error goes away if you ensure that you are assigning unique keys to array child elements, as is required by React.

I believe this issue is more about making sure the correct error message is shown to the user.

**Comment by tom-sherman** [comment] 2023-08-01 15:44
Can you share a minimal reproduction?

**Comment by kunwar-11** [comment] 2023-08-01 16:21
i have sent the env to your twitter

**Comment by GoodbyeNJN** [comment] 2023-09-20 16:12
Any further updates on this issue? I also encountered this error on v15.0.1 and it returned to normal after rolling back to v13.4.19.

I used "@next/mdx" and defined some components in "mdx-components.tsx" and the error message is pointing to these components.

**Comment by recallwei** [comment] 2023-10-13 05:16
+1, I'm using shadcn/ui.

**Comment by JulianKingman** [comment] 2023-10-18 00:54
I'm encountering this as well, using shadcn/ui in NextJS 13.5.5

**Comment by Poylar** [comment] 2023-10-18 11:33
My error was related to the reactReplaceString library. Adding to the Image key fixed the problem

` <h1 className="flex flex-col font-display text-xl md:text-3xl lg:text-6xl">
                        {splitTitle.map((item, index) => {
                            return (
                                <span
                                    className="flex flex-wrap items-center gap-2 md:gap-4"
                                    key={item}
                                >
                                    {reactStringReplace(item, '[flag]', () => (
                                        <Image
                                            key={1}
                                            className="h-6 w-7 object-contain"
                                            src="/icons/germanyFlag.svg"
                                            alt=""
                                            width={60}
                                            height={48}
                                        />
                                    ))}
                                </span>
                            );
                        })}
                    </h1>`

**Comment by Songkeys** [comment] 2023-10-19 03:06
still on 13.5.5

Error goes:

```
⨯ Error: Cannot access Button.prototype on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.
```

For me, this happens on every **un-keyed** and **arrayed** client components.

```tsx
import { Button } from "@mantine/core";

export default async function Page() {
	return (
		<>
			<Button /> ✅
			{[<Button />]} ❌
			{[<Button key="123" />]} ✅
		</>
	);
}
```

I think we should make this error message more clear.

**Comment by lamualfa** [comment] 2023-10-19 15:02
> still on 13.5.5
> 
> Error goes:
> 
> ```
> ⨯ Error: Cannot access Button.prototype on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.
> ```
> 
> For me, this happens on every **un-keyed** and **arrayed** client components.
> 
> ```tsx
> import { Button } from "@mantine/core";
> 
> export default async function Page() {
> 	return (
> 		<>
> 			<Button /> ✅
> 			{[<Button />]} ❌
> 			{[<Button key="123" />]} ✅
> 		</>
> 	);
> }
> ```
> 
> I think we should make this error message more clear.

Giving a `key` to the element inside a loop is works for me. Thanks.

**Comment by shivam-sharma7** [comment] 2023-10-23 05:18
> This also happened to me when doing a `.map` over some images using and then returning the `next/image` component. It seems like adding the missing `key` attribute fixed it, but the error was super confusing.

@sreuter This is worked for me.

**Comment by huozhi** [comment] 2024-01-09 13:05
Tested against the latest canary (14.0.5-canary.45) the issue is resolved for me now

**Closed by huozhi** 2024-01-09 13:05 UTC
Labels: template: bug, linear: next
