### ISSUE TITLE
Navigation from 404 page doesn't work

### ISSUE THREAD

**Issue by marek-miotelka** [vercel/next.js#49732] opened 2023-05-12 21:51 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.3-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/marek-miotelka/nextjs-13.4-app-404-link-error

### To Reproduce

Create next app, add global `not-found.tsx` file with the `Link` component to any existing page (eg Home). 
Open any URL that would trigger 404 error and try to navigate out of this page.

### Describe the Bug

After landing on 404 page navigation with `Link` component will update the URL in the browser, but won't change the page content.

### Expected Behavior

Navigate out of 404 page to an existing page.

**Comment by grzegorzpokorski** [comment] 2023-05-12 22:46
Duplicate of https://github.com/vercel/next.js/issues/47862

Let's be patient and trust that the Next.js team will quickly resolve this problem.

**Closed** 2023-05-12 23:24 UTC
Labels: template: bug, area: Routing, area: app

**Comment by sanskar-19** [comment] 2023-05-13 14:05
> Duplicate of #47862
> 
> Let's be patient and trust that the Next.js team will quickly resolve this problem 🙂

I see many of the Issues marked as closed. When to expect this to be released :( Hoped that they moved to stable release and we could use it in prod. :(
