### ISSUE TITLE
Dynamic Routes with suffix

### ISSUE THREAD

**Issue by mieszko4** [vercel/next.js#12051] opened 2020-04-20 15:52 UTC
# Feature request
Dynamic Routes with suffix

## Is your feature request related to a problem? Please describe.

Currently it is possible to have dynamic routes defined as:
```
pages/post/[pid].js
```
I am not able to define suffix for dynamic route.

## Describe the solution you'd like

I would like to have possibility to put suffixes on two dynamic urls:
```
pages/post/[pid]-Suffix1.js
pages/post/[pid]-Suffix2.js
```

## Describe alternatives you've considered

Alternative is dynamic imports but that limits me from being able to pregenerate all possible routes.

**Comment by Aviortheking** [comment] 2020-07-17 13:46
even with prefix it would be awesome

**Comment by timneutkens** [comment] 2020-09-17 09:16
We recently introduced `rewrites` support which should cover your particular use-case: https://nextjs.org/docs/api-reference/next.config.js/rewrites

**Comment by 700software** [comment] 2021-01-06 15:48
I'm using `rewrites` but it does complicate things. Dynamic Routes with prefix and/or suffix would be better.

**Comment by Timer** [comment] 2021-01-06 15:55
Closing as this feature is supported via rewrites.

**Closed by Timer** 2021-01-06 15:55 UTC

**Comment by alekskorovin** [comment] 2021-11-17 11:36
Let me show some working approaches for routes with suffixes. For example, you need some pages to be SSR, then you can create under the'**pages** an **ssr** folder where you could put the page **[[...path]].js** with getServerSideProps. Then you could use such rewrite in the next.config.js under `async rewrites() {`:
`          source: '/:path*/:key-ssr',
          destination: '/ssr/:path*/:key-ssr'`
that covers such URLs:
/en/page1/page-ssr 
/en/page1/page2/page-ssr 
/en/page1/page2/page3/page-ssr 
etc.

**Comment by balazsorban44** [comment] 2022-01-27 09:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
