### ISSUE TITLE
Custom server with dynamic routing, incompatible as and href

### ISSUE THREAD

**Issue by pacxiu** [vercel/next.js#23597] opened 2021-04-01 10:23 UTC
### What version of Next.js are you using?

10.1.2

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Chromium

### What operating system are you using?

Ubuntu

### How are you deploying your application?

-

### Describe the Bug

I'm trying to achieve rewrites on custom express server (it is convenience in our real app to do it there rather than in next.config.js as we use `vhost` middleware).
So as user visits `/product/:id` we should server `baseFolder/product/:id`, like so:
```
else if (pathname?.includes('product')) {
  app.render(req, res, '/baseFolder/product/:id', query)
}
```
However I see error about incompatibility of `as` and `href` (screen in comment). (I'm able to operate on static paths, eg. `/about` can be served from `baseFolder/about` and I don't get this error)

I tried to achieve that with next.config.js and succeeded like:
```
module.exports = {
  async rewrites() {
    return [{
      source: '/product/:id',
      destination: '/baseFolder/product/:id'
    }]
  }
}
```

### Expected Behavior

Rewrites from next.config.js should work similarly to the ones from custom express server and don't complain about `as` and `href`

### To Reproduce

Repository:
https://github.com/pacxiu/next-custom-rewrites

(if you want to check how it works with next.config.js, you also have to modify `dev` script to `next dev`, otherwise server hanged)

![image](https://user-images.githubusercontent.com/19193499/113280401-85356580-92e4-11eb-93e2-1b46510cfc78.png)

**Comment by m235** [comment] 2021-04-01 13:43
Same issue here: 

```
The provided `as` value (/product/123456/789101112) is incompatible with the `href` value (/oduct/[pid]/[sid]). Read more: https://nextjs.org/docs/messages/incompatible-href-as
```

**Comment by ijjk** [comment] 2021-04-17 15:57
The provided reproduction appears to be working correctly, I'm going to close this since it doesn't seem to be occurring on the latest version. If you are still encountering this please provide a complete reproduction and we can investigate further.

**Closed by ijjk** 2021-04-17 15:57 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
