### ISSUE TITLE
Document how Next and ts-jest coexist

### ISSUE THREAD

**Issue by jyasskin** [vercel/next.js#12086] opened 2020-04-21 23:09 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

From https://github.com/zeit/next.js/issues/3663#issuecomment-385361537 and https://github.com/zeit/next.js/issues/8663, it looks like no single value for the tsconfig's `compilerOptions.jsx` works for both Next.js (which requires `"preserve"`) and Jest (which requires `"react"`). Those issues suggest configuring ts-jest to use a separate `tsconfig.jest.json`, but their guidance hasn't made it into any actual documentation that I can find.

## Describe the solution you'd like

Write a page in https://nextjs.org/docs/ saying how to get started testing.

## Describe alternatives you've considered

* The documentation could also go in https://kulshekhar.github.io/ts-jest/user/config/.
* The solution in https://github.com/zeit/next.js/tree/canary/examples/with-jest (1) doesn't use typescript and (2) according to https://kulshekhar.github.io/ts-jest/user/babel7-or-ts would fail to typecheck the tests.
* An even better alternative would be to improve ts-jest somehow to cope with JSX tags in its source, but that seems more work than just documenting the workaround.

**Comment by Timer** [comment] 2020-04-22 02:49
You should be using the `with-jest` example, which supports TypeScript files, and be relying on `next build` to run the type checking (which it does)!

**Comment by jyasskin** [comment] 2020-04-25 02:57
I tried the `with-jest` example, introduced a type error, and neither `npm test` nor `npm run build` failed. A type error did cause `npm test` to fail when I followed the linked issues' advice.

Even if `with-jest` did work for typescript, an example isn't a complete substitute for a documentation page that describes how you intend folks to test their projects.

**Comment by timneutkens** [comment] 2020-05-25 14:10
Feel free to send a PR.

**Comment by adelnizamutdinov** [comment] 2020-07-15 11:35
does anybody know any workarounds?

**Comment by bobstrange** [comment] 2020-07-22 15:09
@meoyawn 
There is already an example [`with-typescript-eslint-jest`](https://github.com/vercel/next.js/tree/canary/examples/with-typescript-eslint-jest).

So, I think this issue should have closed :thinking:

**Comment by Timer** [comment] 2020-07-22 15:39
Closing per above and that we allow `module: 'commonjs'` on `next@canary`!

**Closed by Timer** 2020-07-22 15:39 UTC
Labels: good first issue

**Comment by bobstrange** [comment] 2020-07-22 16:46
@Timer 
Thank you for closing this issue :bow: 
Do you think if we should put a the [`with-typescript-eslint-jest`](https://github.com/vercel/next.js/tree/canary/examples/with-typescript-eslint-jest) example link on [`with-jest`](https://github.com/vercel/next.js/tree/canary/examples/with-jest)'s README ?

**Comment by Timer** [comment] 2020-07-22 16:52
I don't think it's necessary, the `with-jest` example covers TypeScript usage already.

**Comment by meoyawn** [comment] 2020-07-23 02:22
thanks @bobstrange @Timer

**Comment by balazsorban44** [comment] 2022-01-29 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
