### ISSUE TITLE
Ability to rewrite to dynamic SSG paths

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#14695] opened 2020-06-30 01:36 UTC
# Feature request

You should be able to use rewrites and dynamic SSG-generated together. Currently, this isn't possible due to not shipping a full routing manifest, but we nearly do on the newest Next.js versions.

## Describe the solution you'd like

Using rewrites with dynamic SSG pages should "just work," the same way it does with SSR pages.

**Comment by timneutkens** [comment] 2020-08-17 14:20
Landed in #15231

**Closed by timneutkens** 2020-08-17 14:20 UTC
Labels: kind: story, point: 13, priority: stretch

**Comment by balazsorban44** [comment] 2022-01-29 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
