### ISSUE TITLE
next/image srcset - to allow for changing the src to a lighter coloured image when dark mode is enabled.

### ISSUE THREAD

**Issue by machooper** [vercel/next.js#20693] opened 2021-01-02 19:05 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

A clear and concise description of what you want and what your use case is.

**Comment by lachlanjc** [comment] 2021-01-03 07:09
Duplicate of #20694?

**Comment by Timer** [comment] 2021-01-04 15:59
Duplicate of #20694 which has more activity

**Closed by Timer** 2021-01-04 15:59 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
