### ISSUE TITLE
ModuleError: Cannot Resolve 'fs' used in markdown blog-starter example

### ISSUE THREAD

**Issue by dillionmegida** [vercel/next.js#20814] opened 2021-01-06 14:41 UTC
**What version of Next.js are you using?**

9.5.1

**What version of Node.js are you using?**

12.18.4

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

Vercel

**Describe the Bug**

Following the [markdown blog starter](https://github.com/vercel/next.js/tree/canary/examples/blog-starter), the `fs` module was used in the [lib/api.js file](https://github.com/vercel/next.js/blob/canary/examples/blog-starter/lib/api.js) to do some reading from a directory.

On running `npm run dev`, and accessing the blog page, I get:

```shell
event - build page: /blog/[slug]
event - build page: /blog/[slug]
event - compiled successfully
error - ./utils/posts/index.ts
Module not found: Can't resolve 'fs' in ...
```

**Expected Behavior**

I followed everything in the blog-starter, so I expected the page to load without errors.

**To Reproduce**

The [markdown blog starter](https://github.com/vercel/next.js/tree/canary/examples/blog-starter) template was what I used before getting the error.

Actually, I discovered a solution that worked for me, but I'm just surprised that the blog-starter did not use the solution.

[In this discussion](https://github.com/vercel/next.js/issues/7755#issuecomment-508633125), the solution was to have a `next.config.js` configured like so:

```js
module.exports = {
  webpack: (config, { isServer }) => {
    // Fixes npm packages that depend on `fs` module
    if (!isServer) {
      config.node = {
        fs: 'empty'
      }
    }

    return config
  }
}
```

But the blog starter did not have any `next.config.js` file so I'm wondering how it deployed successfully.

I've got the solution already but I think the starter working without the next config file should be addressed documentation-wise or any ways at all.

Awesome job, team. Thank you!

**Comment by Timer** [comment] 2021-01-06 15:35
This was likely caused by an edit you made to the example. Could you please share your project?

**Comment by dillionmegida** [comment] 2021-01-06 15:38
Hi @Timer, the project is currently private in development. I'm sorry I can't share.
But I followed the `blog-starter` template and expected it to work without further configurations.

**Comment by Timer** [comment] 2021-01-06 15:41
It does work fine! The two files you referenced in your logs above do not belong to that example:
```
event - build page: /blog/[slug]
error - ./utils/posts/index.ts
```

This would indicate you have `pages/blog/[slug].ts` and `utils/posts/index.ts`, neither of which exist in the example you linked.

I'll close this issue since it's not actionable without you sharing a reproduction.

**Closed by Timer** 2021-01-06 15:41 UTC
Labels: please add a complete reproduction

**Comment by dillionmegida** [comment] 2021-01-06 15:46
I'm sorry about that.

The main issue was the `fs` module throwing errors until I added `next.config.js`. I didn't expect to have any more configurations since the template didn't have them too.

Thank you, once again.

**Comment by Timer** [comment] 2021-01-06 15:54
This is caused to an error in your user code. No `next.config.js` is necessary if you fix the issue in your application. Happy to help you find it if you can share some code!

**Comment by balazsorban44** [comment] 2022-01-28 21:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
