### ISSUE TITLE
Documentation  - Difference b/w fallback:true on getStaticProps and getServerSideProps

### ISSUE THREAD

**Issue by kushalmahajan** [vercel/next.js#17292] opened 2020-09-22 20:23 UTC
Reading the documentation on [Data Fetching](https://nextjs.org/docs/basic-features/data-fetching#only-runs-at-build-time), I am not clear for what is the difference apart from CDN caching if I choose `fallback:true` in static rendering for my dynamic routes. 

Here is my understanding -:

Let's say I have `[someDynamicPageSlug].js` and I will need to have `getStaticPaths` to render top 10 slug pages and `getStaticProps` with `fallback:true` will serve rest of the pages generating them on demand for first time and then next time it will serve it right out of CDN. 

Now, it is mentioned under `getServerSideProps` when to use section that  in increases the Time to first Byte (TTFB ). My first question is will not `fallback:true` do the same for first time render of a page which doesn't exists in `getStaticPaths` and have same TTBF?

I'm asking because, I'm evaluating if I can simply use `getServerSideProps` with manual caching option instead of defining `getStaticPaths` and `getStaticProps` with `fallback:true`.

Second question is that is there any SEO impact in picking one strategy over the other. The way docs are put up there doesn't seems to be but if someone has worked on the scale of million metrics and have seen any difference please let me know.

I will appreciate to sufficiently deep these about it. How they work internally (if possible) as reading the docs, gives a black box to people like me for inner workings of it.

Thanks in advance!

and update the docs of course to avoid confusion.

**Comment by lfades** [comment] 2020-09-22 22:22
Closing in favor of https://github.com/vercel/next.js/discussions/17291

**Closed by lfades** 2020-09-22 22:22 UTC

**Comment by balazsorban44** [comment] 2022-01-29 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
