### ISSUE TITLE
Persistent `next/image` flickers on route change

### ISSUE THREAD

**Issue by mvllow** [vercel/next.js#26509] opened 2021-06-23 03:59 UTC
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

16.3.0

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Using `next/image` flickers every time a route changes.

### Expected Behavior

When not using the `next/image` component, eg. setting an image as a background image on a div, there is a flicker only on first page render, but not subsequent visits. I would expect `next/image` to not flicker on subsequent route visits.

### To Reproduce

```js
import Image from "next/image";

export default function Layout() {
  return (
    <Image
      src="https://images.unsplash.com/photo-1612480797665-c96d261eae09?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
      alt="Lorem Ipsum"
      width="256"
      height="256"
    />
  );
}
```

See the avatar image in the header [with `next/image`](https://next-pwa-template-4t6659k1t-mellow.vercel.app) and [without](https://next-pwa-template.now.sh). To replicate the flicker, navigate between /story and /recipes a few times.

[Source PR](https://github.com/mvllow/next-pwa-template/pull/17)

**Comment by timneutkens** [comment] 2021-06-24 13:18
Duplicate of #19074

**Closed by timneutkens** 2021-06-24 13:18 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
