### ISSUE TITLE
Preview mode doesn't work for pages not specified by getStaticPaths

### ISSUE THREAD

**Issue by benyap** [vercel/next.js#16681] opened 2020-08-29 15:39 UTC
# Bug report

## Describe the bug

Trying to access dynamic/catch-all routes in preview mode that are not specified by `getStaticPaths` returns 404 Not Found in production. I have verified that preview mode cookies are being sent on the requests, so that's not the issue.

In development, the behaviour works as expected, though this might be due to the fact that `getStaticProps` is called on every request when in development mode.

## To Reproduce

Repository: https://github.com/nextjs-preview-issue/nextjs-preview-issue

Demo: https://nextjs-preview-issue-demo.vercel.app

* Accessing any pages **not** marked with "preview only" should render a page that has an appropriate title.
* Accessing any pages marked with "preview only" should render a not found page.

Enable preview mode by clicking the "PREVIEW MODE" button and enter `token1` or `token2` into the prompt.

* Accessing pages **not** marked with "preview only" should render a page that has an appropriate title with "(preview)" appended to it.
* Accessing pages marked with "preview only" should render a draft page in preview mode, but it returns a not found page.

See "Additional context" for notable code snippets from the demo repository.

## Expected behaviour

From the [blog post](https://nextjs.org/blog/next-9-3#preview-mode):
> Preview Mode allows users to bypass the statically generated page to on-demand render (SSR) a draft page from for example a CMS.

When trying to access pages that match a dynamic or catch-all route, I would expect that it always renders the page when in preview mode, even if it is not specified by `getStaticPaths`, because preview mode is intended for on-demand render of **draft pages**. 

I considered using `fallback: true` in `getStaticPaths`, but that slightly changes behaviour in production regardless of preview mode - I shouldn't need the server to check and render pages when not in preview mode.

Running the demo on a local machine in development mode using `yarn dev` exhibits the behaviour I expected.

## System information

- OS: macOS
- Browser: tested on Chrome, Safari, Firefox
- Version of Next.js: 9.5.2
- Version of Node.js: 10.15.3

#### Frontend: [src/components/Preview.tsx](https://github.com/nextjs-preview-issue/nextjs-preview-issue/blob/master/src/components/Preview.tsx#L7)

This function is attached to a button's `onClick` handler which enables preview mode.

```js
const previewMode = () => {
  const token = prompt("Enter preview token.");
  if (token) push(`/api/preview?token=${token}`)
};
```

#### Backend: [src/pages/api/preview.ts](https://github.com/nextjs-preview-issue/nextjs-preview-issue/blob/master/src/pages/api/preview.ts)

This API route enables preview mode and redirects the user to a page that matches the specified `pageId` if given, otherwise it redirects them to the index page. In the demo, the `pageId` parameter is not used (see above) so the user will always redirected to the index page when enabling preview mode.

#### Backend: [src/utils.ts](https://github.com/nextjs-preview-issue/nextjs-preview-issue/blob/master/src/utils.ts)

This file contains the `getStaticPaths` and `getStaticProps` implementations used by the dynamic route (`blog/[id].tsx`) and the catch all route (`[...slug].tsx`).

The `getStaticPaths` implementations only lists pages/posts that have `published: true` because I do not want draft pages rendered at build time. `getStaticProps` retrieves the page's/post's data using the slug in the route params regardless of preview mode or not.

When in preview mode, `getStaticProps` passes the preview data to the page as the `preview` prop. The page will check this prop and render "(preview)" in the title when this is a non-null value.

See: 
[Index page](https://github.com/nextjs-preview-issue/nextjs-preview-issue/blob/master/src/pages/index.tsx)
[Blog post page](https://github.com/nextjs-preview-issue/nextjs-preview-issue/blob/master/src/pages/blog/%5Bid%5D.tsx)
[Catch-all page](https://github.com/nextjs-preview-issue/nextjs-preview-issue/blob/master/src/pages/%5B...slug%5D.tsx)

#### Backend: [src/data.ts](https://github.com/nextjs-preview-issue/nextjs-preview-issue/blob/master/src/data.ts)

This file contains the mock data used in the demo. In a real project these values would be retrieved from a database.

### My use case and how I came across this issue

I'm building a page builder interface in my project and I want to allow users to preview pages they've created in the CMS that have not been published yet. Pages in my CMS database have a `publishState` flag. My `getStaticPaths` function only lists pages that have `publishState` set to `"published"` as I do not want draft pages to be rendered at build time. When draft pages are created, they have a `publishState` of `"draft"`.

I deploy my project to Vercel and allow the users to publish new content by using a deploy hook to rebuild the project. Before the deploy hook is called, pages that are to be published have the state set to `"published"` so that `getStaticPaths` returns their ids for rendering during build time.

**Comment by Timer** [comment] 2020-08-30 01:01
There's two ways to solve this:

- Development should also 404 in preview mode for a `fallback: false` page and an unmatched slug
- Production should match a path not returned from `paths: []` even if `fallback: false`, making preview mode work like `fallback: true`

I'm not sure which is the most optimal fix, but we'll think about this. Thanks for the issue!

**Comment by benyap** [comment] 2020-08-30 02:19
> There's two ways to solve this:
> 
> * Development should also 404 in preview mode for a `fallback: false` page and an unmatched slug
> * Production should match a path not returned from `paths: []` even if `fallback: false`, making preview mode work like `fallback: true`
> 
> I'm not sure which is the most optimal fix, but we'll think about this. Thanks for the issue!

I personally think the second option is more flexible and gives more control to what can be done in preview mode, so my vote would be for that one haha

**Comment by xiata** [comment] 2020-10-16 19:48
Somewhat related, on a /[...slug].js route I have, `getServerSideProps({ params, preview })`, `preview` is filled in on development builds, but is always undefined in production builds, despite `__prerender_bypass` and `__next_preview_data` cookies being present.

**Comment by ericclemmons** [comment] 2020-10-20 05:41
I just ran into this issue myself and was a bit surprised that it didn't work.

I do believe that `development` should match `production` behavior, which means (today) it should `404`.

My expectation was that `fallback: true` and preview mode would both behave about the same: deferring to the server like `getServerSideProps` for new paths.

**Comment by shinesingh1994** [comment] 2020-10-23 15:44
After curl I found out that cookies are being set but in **SameSite=None** mode. Is that the issue?
I am using Next JS v9.5.2

```
 HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Set-Cookie: __prerender_bypass=e00e4ba3b660386df18eea2687f9b75; Path=/; HttpOnly; Secure; SameSite=None
Set-Cookie: __prerender_bypass=e00e4ba3b660386ef18eea2687f9b75; Path=/; HttpOnly; Secure; SameSite=None
< Set-Cookie: __next_preview_data=eyJhbGciOiJIUzI1NiIsInR5cI6IkpXVCJ9.eyJkYXRhIjoiYTU0NWQyN2RkZTM1ZTBiNjhiNzE3MTBkOWMxZjBmMGVlZDU3ZjEwMGQ5ZmExZTIxYmRjMDliMDY4Yjc5ODA1MWNlYzdhYWU1OWY5MzY1MTI5Y2RiMTNlZTA2OTM3M2ZhYjVkYjQ3NjYxYjdlMTkzMThhNmM4N2MxY2MzZTI3NDVhND4YjI0ZjllODgxN2I2OWYxODdhMTFhYjE0YzUyNzE0ZDQ0NDI4OTI1MWVhOTg1MDdkNWZlMDZkNThiNmUzMzI2MSIsImlhdCI6MTYwMzQ2NzA2Nn0.V4IpUW7V_goPgiJ5mV6-axAKQcMFxqNXwUQqVp6nfA; Path=/; HttpOnly; Secure; SameSite=None
Set-Cookie: __next_preview_data=eyJhbGciOiJIUzI1NisInR5cCI6IkpXVCJ9.eyJkYXRhIjoiYTU0NWQyN2RkZTM1ZTBiNjhiNzE3MTBkOWMxZjBmMGVlZDU3ZjEwMGQ5ZmExZTIxYmRjMDliMDY4Yjc5ODA1MWNlYzdhYWU1OWY5MzY1MTI5Y2RiMTNlZTA2OTM3M2ZhYjVkYjQ3NjYxYjdlMTkzMThhNmM4N2MxY2MzZTI3NDVhNDk4YjI0ZjllODgxN2I2OWYxODdhMTFhYjE0YzUyNzE0ZDQ0NDI4OTI1MWVhOTg1MDdkNWZlMDZkNThiNmUzMzI2MSIsmlhdCI6MTYwMzQ2NzA2Nn0.V4IpUW7V_goPgiJ5mV6-axAKQcMFxqNXwWQqVp6nfA; Path=/; HttpOnly; Secure; SameSite=None
< Date: Fri, 23 Oct 2020 15:31:06 GMT
Date: Fri, 23 Oct 2020 15:31:06 GMT
< Connection: keep-alive
Connection: keep-alive
< Transfer-Encoding: chunked
Transfer-Encoding: chunked

< 
<!DOCTYPE html><html><head><meta http-equiv="Refresh" content="0; url=/posts/everything-you-want-to-know" />
    <script>window.location.href = '/posts/everything-you-want-to-know'</script>
* Connection #0 to host localhost left intact
    </head>* Closing connection 0
```

**Comment by josias-r** [comment] 2020-10-27 10:14
If getStaticPaths would receive a context parameter similar to getStaticProps including the preview boolean, you could control the behaviour yourself as a dev, whether fallback should be enabled in preview mode or not. 🤷🏻‍♂️

**Comment by joshuabaker** [comment] 2020-11-30 12:32
#10995

**Comment by tremby** [comment] 2021-01-06 00:17
I was auditing my app just now to make sure `previewData` is always passed through to API queries, and was surprised that `previewData` is not part of `GetStaticPathsContext`. What's the reason for that? If it were present, I'd be able to tell Next the correct list of paths for a given preview, no? Then there wouldn't be any need for special behavior or `fallback:true` in my use case.

**Comment by vajajak** [comment] 2021-02-04 16:29
I've also stumbled upon this issue today, which I have never noticed earlier.
The reason behind that is because I was only testing this locally (either with `npm run dev` or `npm run build && npm run start`). [This comment ](https://github.com/vercel/next.js/discussions/10995#discussioncomment-1272) also reassured me that I'm doing everything right and that there's no need to have a preview mode aware getStaticPaths, since they're not designed to run at runtime and Next.js is treating every request as if it had `fallback: true` set.
As far as i know, this problem is unique to the Vercel environment as that's the only place where I was able to reproduce this issue. @Timer perhaps this might be more of a Vercel problem?

**Comment by ambrauer** [comment] 2021-02-04 17:36
I can confirm @vajajak's findings, which we just stumbled on today as well. This issue only appears to surface when deployed on Vercel. Running locally in production mode (with `next build && next start`), preview mode is working as expected (calling getStaticProps for all requests regardless of presence in getStaticPaths) with `fallback: false`.

**Comment by alexburner** [comment] 2021-03-07 02:09
We're having this same experience, we're using `getStaticPaths` and can't preview pages without publishing them and running a site build. We're also hosting on Vercel. 

The preview docs make it sound like this specific use case should work:
>In the Pages documentation and the Data Fetching documentation, we talked about how to pre-render a page at build time (Static Generation) using getStaticProps and **getStaticPaths**.
>
>Static Generation is useful when your pages fetch data from a headless CMS. However, it’s not ideal when you’re writing a draft on your headless CMS and want to preview the draft immediately on your page. **You’d want Next.js to render these pages at request time instead of build time and fetch the draft content instead of the published content. You’d want Next.js to bypass Static Generation only for this specific case.**
>
>Next.js has a feature called Preview Mode which solves this problem. Here are instructions on how to use it.

https://nextjs.org/docs/advanced-features/preview-mode

Reading between the lines, it seems like this is indicating it should behave like @Timer's second option?
> * Production should match a path not returned from `paths: []` even if `fallback: false`, making preview mode work like `fallback: true`

And that a page could be previewed, even if it's unpublished (its path isn't returned by `getStaticPages`) and no site build has been run since creating the page draft.

**Comment by alexburner** [comment] 2021-03-07 17:23
**Update:** I was able to enable the desired preview behavior, with only two small changes!

In this case, for a `[slug].tsx` page:
1. Change `fallback: false` to `fallback: 'blocking'` in `getStaticPaths()`
2. Return `{ notFound: true }` from `getStaticProps()` if querying with `context.params.slug` fails to find data

Since our site is small, we're doing full SSG instead of ISR, and this code has no impact on the normal production site.

**Comment by vajajak** [comment] 2021-05-20 10:49
> **Update:** I was able to enable the desired preview behavior, with only two small changes!
> 
> In this case, for a `[slug].tsx` page:
> 
> 1. Change `fallback: false` to `fallback: 'blocking'` in `getStaticPaths()`
> 2. Return `{ notFound: true }` from `getStaticProps()` if querying with `context.params.slug` fails to find data
> 
> Since our site is small, we're doing full SSG instead of ISR, and this code has no impact on the normal production site.

@alexburner This might be a useful workaround for now but is certainly not ideal. When you quit the preview mode, the page stays generated and can be accessed publicly with a url, even though it's still a draft, essentially defeating the purpose of Preview Mode.

**Comment by joshuabaker** [comment] 2021-05-20 11:05
@vajajak That’s a valid point. Thinking out loud here, would passing `revalidate` in combo with @alexburner’s approach sort that?

**Comment by alexburner** [comment] 2021-05-20 21:00
>When you quit the preview mode, the page stays generated (more specifically - the first generated version - if you're not also using ISR) and can be accessed publicly with a url, even though it's still a draft, essentially defeating the purpose of Preview Mode.
 
@vajajak I hadn't considered this — not an ideal situation

**Comment by joshuabaker** [comment] 2021-05-25 10:55
@Timer This might be considered a serious concern for organisations that aren’t legally allowed to publish information ahead of a date (e.g. earnings reports). Is there an option available for us not mentioned above?

**Comment by ijjk** [comment] 2021-05-25 17:12
Hi, this has been updated, please give it a try by re-deploying your application! 

Note: with `fallback: false` pages and previewing a non-prerendered path a 404 status will be shown on Vercel to prevent crawlers indexing the 404 page although this will be updated in the future to only have the 404 status when not in preview mode.

**Comment by ijjk** [comment] 2021-09-20 02:20
Closing as this should be working correctly now per above

**Closed by ijjk** 2021-09-20 02:20 UTC
Labels: kind: bug

**Comment by nickwesselman** [comment] 2021-11-09 20:42
@ijjk To close the loop, indeed we just needed to gracefully handle the 404 response when fetching the preview. Thanks!

**Comment by balazsorban44** [comment] 2022-01-27 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
