### ISSUE TITLE
[NEXT-1189] metadata not updated on navigation with `experimental.serverActions` set to true

### ISSUE THREAD

**Issue by TheEdoRan** [vercel/next.js#49409] opened 2023-05-07 16:18 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
Binaries:
  Node: 18.16.0
  npm: 9.6.5
  Yarn: 1.22.19
  pnpm: 8.4.0
Relevant packages:
  next: 13.4.1
  eslint-config-next: 13.4.1
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue

https://github.com/TheEdoRan/nextjs-metadata-bug

### To Reproduce

- Create a Next project
- Set `experimental.serverActions` to true in next.config.js
- Export `metadata` objects from pages
- Use `<Link>` to navigate between them

### Describe the Bug

When enabling `experimental.serverActions` flag in next.config.js, metadata updating on navigation breaks.
The first time you navigate to a page it works as it should, but then if you try again it breaks and meta tags stay the same.

### Expected Behavior

Meta tags are updated on navigation.

<sub>[NEXT-1189](https://linear.app/vercel/issue/NEXT-1189/metadata-not-updated-on-navigation-with-experimentalserveractions-set)</sub>

**Comment by TheEdoRan** [comment] 2023-05-10 00:35
After some tests, I found out that this bug first appeared in version **13.3.5-canary.6**

**Comment by switz** [comment] 2023-05-14 15:34
also seeing this. this is a major bug.

**Comment by colenh** [comment] 2023-05-14 15:37
also having the same bug in 13.4

**Comment by Josehower** [comment] 2023-05-23 12:34
Issue confirmed in `13.4.4-canary.0`

**Comment by timneutkens** [comment] 2023-05-24 19:57
Tip: If the issue is open, it's unfortunately not fixed yet. 

You don't have to add additional comments saying "Version x" has the same, because the issue is open, the special case is if the issue is fixed but still open, then it's useful to post a comment saying it has been fixed.

Thank you!

**Comment by naseef0** [comment] 2023-06-06 02:28
I'm using "next": "^13.4.4"

I have the same issue!

**Comment by almirjakubaitis** [comment] 2023-06-15 13:15
I also have the same issue! - Using Next.js ("next": "^13.4.4",)

**Comment by TheAggressive** [comment] 2023-06-15 14:49
Also facing this issue. If I hard refresh then it will show the correct title.

**Comment by FranzaLeny** [comment] 2023-06-17 03:49
I also have the same issue! - Using Next.js ("next": "^13.4.6",)

**Comment by shuding** [comment] 2023-06-25 11:58
This issue will be fixed by #51779.

It's not helpful to reply with "I also have this issue", for things that are already recognized as a bug with assignee. It won't help addressing the root cause, and will only increase the number of notifications for maintainers (so they spend more time reading them, and less time fixing the actual thing). To express the need of a fix you can react with an emoji (👍), or you can provide a helpful reproduction or even try to share you findings.

Thank you!

**Comment by karlhorky** [comment] 2023-06-30 12:16
New PR from @styfle open here:

- #52005

**Comment by TheEdoRan** [comment] 2023-07-04 16:17
There's a commit after PR merge that reverts React update. Do we have to reopen this issue?

**Comment by TheEdoRan** [comment] 2023-07-05 21:04
May be fixed by #52282, not sure

**Closed** 2023-07-06 12:04 UTC
Labels: template: bug, area: Metadata, area: app, linear: next

**Comment by pat22292** [comment] 2023-07-07 13:33
[v13.4.9](https://github.com/vercel/next.js/releases/tag/v13.4.9) fixed the problem.. 

@TheEdoRan is right. thanks...

**Comment by houariDz95** [comment] 2023-08-05 10:34
upgrade your Next.js project to 13.4.9
