### ISSUE TITLE
Feature request: enable file-loader for images imported in javascript files

### ISSUE THREAD

**Issue by Janpot** [vercel/next.js#10105] opened 2020-01-15 12:18 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I'd like to have images in my project that are served to the browser in the most efficient way possible.

## Describe the solution you'd like

Currently this is [enabled for the new CSS support](https://github.com/zeit/next.js/blob/d9d9545f30073507d57fb06b3d1e9568b4ff56be/packages/next/build/webpack/config/blocks/css/index.ts#L332). I'd like this `file-loader` to be enabled for .js, .jsx, .ts and .tsx as well. So that I can do:

```jsx
import myImageUrl from '../images/my-image.png';
// ...
<img src={myImageUrl}/>
```

It'd also require an update to the typings for typescript.

## Describe alternatives you've considered

There are
https://www.npmjs.com/package/next-images
https://www.npmjs.com/package/next-optimized-images
and I've used a custom setup as well. But if `file-loader` is already enabled an configured for images in the project for CSS, why not enable it for javascript as well?

## Additional context

https://github.com/zeit/next.js/issues/9524#issuecomment-574628736

**Comment by Timer** [comment] 2020-09-03 02:19
We're currently planning to post an RFC for image loading soon. I'll close this in favor of that. Thanks!

**Closed by Timer** 2020-09-03 02:19 UTC

**Comment by karlhorky** [comment] 2020-09-03 08:06
@Timer cool, sounds great! Can you post the link when it's available?

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
