### ISSUE TITLE
Client Side Rendering using Layouts without Reloading the entire page?

### ISSUE THREAD

**Issue by jfarris587** [vercel/next.js#8193] opened 2019-07-31 20:02 UTC
# Client side rendering without reinitializing entire nextJS page

Typical Client Side Routers like React Router have the ability to route subsections of the app. For example, you can have the below...

```
<App>
   <Header/>
   <Page>
   <Footer/>
</App>
```

And using a router, you can change what `Page` is rendered on the client. With this, the `Header` and `Footer` are *not re-rendered* and keep their state and are not re-painted onto the page. Only the `Page` changes`

---

Using NextJS's Client Side Routing capabilities, it is possible to route from the client and not go to the server. However, this is technically just routing between pages. Routing between pages re-renders the entire page including `_app` file. 

I am looking for a way to route client side without re-initializing the entire NextJS process (running `_document`, `getInitialProps`, `_app`, then `page`).

**Comment by Yuripetusko** [comment] 2019-08-22 09:50
Would love this, especially with static export there's more cases of not re-rendering whole page, We have a mobile menu tabs in footer for example and change the active button on that menu, and re-rendering of whole page when page changes with next router blocks rendering of new active menu button, which just doesn't look really snappy

**Comment by tky5622** [comment] 2019-10-15 17:25
any progress or answer about it ?

**Comment by lifeiscontent** [comment] 2020-02-22 04:08
@Timer @timneutkens any updates on this? I didn’t realize next js doesn’t do this already

**Comment by boraikizoglu** [comment] 2020-02-25 01:26
Unfortunately, NextJS doesn't support persistent layouts yet but there is a nice article about how you can implement SPA user experience with NextJS. 

[https://adamwathan.me/2019/10/17/persistent-layout-patterns-in-nextjs/](url)

**Comment by JerryGreen** [comment] 2020-02-25 02:48
There are several examples of how to layout, but afaik this one does not cause root re-rendering:

https://github.com/zeit/next.js/tree/canary/examples/with-dynamic-app-layout

## Little overview of the code:

https://github.com/zeit/next.js/blob/c57cdbb31de6143b86b9091afb8d4dc2a2f46cc5/examples/with-dynamic-app-layout/pages/_app.js#L6-L17

https://github.com/zeit/next.js/blob/c57cdbb31de6143b86b9091afb8d4dc2a2f46cc5/examples/with-dynamic-app-layout/pages/red.js#L6-L23

**Comment by rayronvictor** [comment] 2020-05-01 01:07
I like the UmiJS strategy to solve this problem.

https://v2.umijs.org/guide/router.html#nested-routing

**Comment by revskill10** [comment] 2020-05-03 22:38
I have a demo for this issue [here](https://checkraiser-blog.now.sh/about ) 
As you click link to switch between pokemon, only a part of a page is re-rendered.
Wanna see such example with Next.js, too. (I'm using `react-router`) for the demo.

**Comment by laurencefass** [comment] 2020-05-25 08:03
I've only used Next js router for basic page routing. How do I achieve client side component based (lazy-load?) routing? I can't imagine writing an app without it. How would you?

**Comment by laurencefass** [comment] 2020-05-27 12:36
revskill10: link in https://github.com/zeit/next.js/issues/8193#issuecomment-623194233 is a 404.

**Comment by odysseymemoirs** [comment] 2020-07-21 17:38
The solution i came across is to use [dynamic app layouts](https://github.com/vercel/next.js/tree/canary/examples/with-dynamic-app-layout) with `React.memo` method wrapped around `<NavBar/>` and `</Footer> `components which caused my NavBar and Footer render only one time during url changings

For example when i navigate through:
```
mysite.com/ 
mysite.com/me 
mysite.com/questions
``` 
and so on, clicking `<Link>` component from `'next/link'` ,

the only time my NavBar and Footer did render is first time - `mysite.com/`

So, doing this i achieved the same thing like if we use React Router's `switch` method

![Alt Text](https://i.imgur.com/o8Dmjv2.gif)

**Comment by abhijithvijayan** [comment] 2020-07-22 15:45
What about having a layout page(which doesnt render more than once) that connects to a socket server?

I tried this connection in `useEffect` hook for `_app.js`, but on routing to another page, the `_app.js` gets re-rendered causing to establish a new socket connection!

Does anyone have an effective way to tackle this issue?

**Comment by Exelord** [comment] 2020-08-11 22:07
Can't wait for the solution  🥰

**Comment by neekey** [comment] 2020-09-08 13:39
second UmiJS's solution, it makes sense as nextJS is already using conventional routes (based on the file/folder names):

```
+ pages/
  - _layout.js
  - index.js
  + users
    - index.js
    + [id]
      - _layout.js
      - posts.js
      - orders.js
  - about.js
```

It also makes permission control fairly easy, you just need to put the permission check logic in a certain level layout file then all the children pages will inherit the check.

**Comment by hacknlove** [comment] 2020-09-11 06:52
I might be wrong, but I thought react takes care of this.

Yes, surely react will "calculate" the whole _app, but in the end, it is only updating the parts of the dom that have changed, so from the user point of view, there only is re-rendered the page, not the header or the footer.

Am I right?

**Comment by Yuripetusko** [comment] 2020-09-11 07:22
> I might be wrong, but I thought react takes care of this.
> 
> Yes, surely react will "calculate" the whole _app, but in the end, it is only updating the parts of the dom that have changed, so from the user point of view, there only is re-rendered the page, not the header or the footer.
> 
> Am I right?

Not for Nextjs where each page is almost like a separate app

**Comment by JerryGreen** [comment] 2020-09-13 20:15
> I might be wrong, but I thought react takes care of this.

You can try it yourself. Btw “each page is almost like a separate app” from a comment above sounds fair enough. Though, there’s already an answer of how to hack it so no rerendering will happen:

https://github.com/vercel/next.js/issues/8193#issuecomment-590654825

It works in modern versions of Next even though I heard that this should stop working at some newer versions of react (and next) because of "fast refresh" feature... But fast refresh has come out, and this "layouting through page properties" seems to be working, still (so I would even close the issue, since it’s not an issue if you do it properly).

**Comment by JerryGreen** [comment] 2020-11-27 13:24
I confirm that with newer versions of React, this workaround doesn't work anymore: https://github.com/vercel/next.js/issues/8193#issuecomment-590654825

Might consider using other solutions like https://github.com/moxystudio/next-layout, I haven't tried it, but looks promising, despite of being HOC (high order-component).

**Comment by Wolfleader101** [comment] 2021-03-23 23:54
Any update on when and or if this will be added?

**Comment by JerryGreen** [comment] 2021-03-24 00:04
@Wolfleader101 theres nothing to be added actually. It just works a little different than create-react-app, and it IS POSSIBLE to use layouts without rerendering the whole tree ([read my previous comment](https://github.com/vercel/next.js/issues/8193#issuecomment-590654825))

IMO this issue might be closed, though it might be good idea to add some section about how to properly deal with layouts in NextJS, to official tutorials and/or docs

**Comment by Svish** [comment] 2021-03-24 00:49
@JerryGreen Of there's nothing to be added here, just documentation, then I really think closing #10361 as a duplicate of this one is incorrect.

For sure, official documentation on how to do it, if there is a way already, would be great, but yeah...

**Comment by sam3d** [comment] 2021-04-03 12:57
Hi all,

I'm working on a PR/RFC for integrating persistent behaviour as a first class feature in Next.js. As far as I can tell, these are the main areas of discussion:

1. Persistent layouts
2. Custom wrapper logic like `_app` that provides multiple levels of nesting
3. Greater ease of use for the above

Point 3 is mostly what we're talking about here. As many people have pointed out, 1 and 2 are already possible. Custom wrapper components can be exported from each page component as a static property that can then be used in `_app` . However there are some clear quality of life improvements being asked for to make this feature more integrated:

1. Hot reloading support (exporting a static property isn't currently supported by HMR)
2. Automatically applying a layout to every file in a directory (using a `_layout` or nested `_app` file)

Currently the `_app`, `_document` and `_error` pages aren't part of the "convention-routing" that Next.js otherwise uses. Rather, they are specific individual files that just so happen to be placed in the `pages` directory. The introduction of a nested `_app` or `_layout` would fundamentally alter the way Next.js treats the directory tree. There would also need to be some bail-out mechanism so that pages that wanted to be routable from the directory tree but exempt from a nested layout would have a way to do that (that isn't some manual check in each `_layout` file for exempt pages, as that would exacerbate the current problem).

Each page could also export (or re-export) its own `Layout` function or component (similar to `getStaticProps` & `getServerSideProps`) to prevent messing with the Next.js directory structure _and_ make it supported behaviour (enabling HMR). That could look something like this:

```jsx
// layouts/Main.jsx
export default function MainLayout({ children }) {
  return (
    <div>
      <h1>Main layout wrapper</h1>
      {children}
    </div>
  );
}
```

```jsx
// pages/index.jsx
export default function IndexPage() {
  return <div>Index page</div>;
}
export { default as Layout } from "../layouts/Main";
```

Though admittedly this isn't a big change from where we are right now.

```jsx
// pages/nested/index.jsx
export default function NestedPage() {
  return <div>Index page</div>;
}
```

If we are to have a `_layout` file that resembles something like this:

```jsx
// pages/nested/_layout.jsx
export default function NestedLayout({ children }) {
  return (
    <div>
      <h1>Nested layout wrapper</h1>
      {children}
    </div>
  );
}
```

Or even something like this:

```jsx
// pages/nested/_layout.jsx
export default function NestedLayout({ Component, pageProps }) {
  return (
    <div>
      <h1>Nested layout wrapper</h1>
      <Component {...pageProps} />
    </div>
  );
}
```

Then a way to bail out would need to become part of convention routing too. [Remix](https://blog.remix.run/p/remix-preview) solves this by using `.` to bail out of using the layout. However, as Next.js will be introducing server components (as well as many apps already written in a way that use the `.` in page names), this would be a _really_ breaking change that requires heavy consideration.

Ultimately the answer to the question of "what should this look like?" needs a bit more discussion around the pros and cons of each implementation. Any feedback would be appreciated

**Comment by dbbk** [comment] 2021-04-03 13:01
Am I missing something here, is there a reason pages couldn't just work in the same way routes do in React Router? Where nested pages are rendered into the `children` or an Outlet component of a parent page?

Think of a master/detail view for example, where you have a list of pages and want to drill down into a child page.

**Comment by laurencefass** [comment] 2021-04-03 13:07
Plus one on comment above why are there no children or outlets in Next?

**Comment by sam3d** [comment] 2021-04-03 13:16
Well I mean that's just a syntax thing. The behaviour change still has the same considerations regardless of how it's expressed.

Currently each page is solely responsible for how it is displayed and doesn't have to consider children. Nesting like that has technical challenges (`getStaticProps` and `getServerSideProps` would have to be recursive and `children` would have to be passed as its own case). It means pages using `children` would have to handle both default and detail-view cases (e.g. `{children ? children : <div>index</div>}` for every parent page instead of a dedicated layout), and still wouldn't support easy bail out behaviour from the nested pages themselves.

**Comment by dlindenkreuz** [comment] 2021-04-03 13:17
> Am I missing something here, is there a reason pages couldn't just work in the same way routes do in React Router? Where nested pages are rendered into the children or an Outlet component of a parent page?

The current way of defining routes does not specify whether a nested route should be handled as a nested layout or as a separate, independent page.

I don't think this can ever be achieved via filesystem paths only. The way that Next.js builds, bundles and serves React Apps has deep ties into the router. Every bit of customization needs to be firmly integrated. There is an increasingly pressing requirement to open up this system (and I myself am all for it), so let's wait and see.

**Comment by Svish** [comment] 2021-04-03 17:19
I think if you want ReactRouter-like routing, then just use ReactRouter? What Next.js could do for that though, is document how to turn a next.js page into a "react-router-spa". And if there are things in next.js that makes it really awkward/hard to use ReactRouter for routing within a particular page, maybe try clean those up a bit?

Either way, for Next.js, I think the file-based routing is simple and excellent. All I really need is the ability to wrap certain sections, the same exact way I do with the whole app with `_app.ts`. Setting static props and such to layout components is really awkward I feel, especially with Typescript.

I'm not a pro api-designer, nor super experienced in next.js, but I think a `_layout.ts` or `_section.ts` or whatever that worked the same as `_app.ts` does could solve the needs I have at least. For example to introduce common auth-stuff for an admin section, or some common UI or react context in a master-detail section.

Would be great (necessary, even?) if the `_layout` supported `getServerSideProps` and `getStaticProps` too. I see `_app` actually doesn't do that now, but hopefully you're already working on that. Shouldn't be too complicated, as long as it's for example required that if you use `getStaticProps` in a `_layout`, then all "sub-routes" must also be static, and if using `getServerSideProps`, then all will be server-side rendered?

**Comment by laurencefass** [comment] 2021-04-03 17:36
Ive been following this thread for some time and I mainly work with React Router 5+ quite frankly it is brilliant

As Next.js is still a react app is there  a reason i cant just yarn install react-router and just embed it in my next routed pages?

Perhaps i am being over-simplistic or naive, but its just after all just another a package of various useful components.

I dont find myself asking the "either or" question of other packages and course i can install what i like from the React ecosystem into next or CRA,, so is it actually a lot of work to use both Routers side by side?

**Comment by dantman** [comment] 2021-04-03 17:39
> I think if you want ReactRouter-like routing, then just use ReactRouter? What Next.js could do for that though, is document how to turn a single next.js page into a "react-router-spa".

React Router supports [server rendering](https://reactrouter.com/web/guides/server-rendering). Making the answer to "I want a better router that handles layouts better" be "Why don't you just make an SPA and ditch server rendering despite the router supporting it?" isn't really a fair answer to the issue.

**Comment by Svish** [comment] 2021-04-03 17:46
> React Router supports [server rendering](https://reactrouter.com/web/guides/server-rendering). Making the answer to "I want a better router that handles layouts better" be "Why don't you just make an SPA and ditch server rendering despite the router supporting it?" isn't really a fair answer to the issue.

Didn't mean to ditch ssr, I meant to use react-router on a page and make that page a spa. The main thing for me with Next.js, isn't just that it's ssr (which react-router supports too, as you say), but that it deals with both that, routing, and data fetching, out of the box in a clear and easy way to follow (to me anyways).

**Comment by yassinebridi** [comment] 2021-04-03 19:41
You can check these resources here:
https://twitter.com/DavidWells/status/1377440317687750656
Especially this one:
https://gist.github.com/tannerlinsley/65ac1f0175d79d19762cf06650707830
It needs a little bit of configuration ofc, but the ending results are not bad.

**Comment by JerryGreen** [comment] 2021-04-04 05:21
I actually a little shocked that people try to turn NextJS app into SPA. NextJS is improved SPA, SEO-friendly, and user-experience friendly (since initial loading times are better, etc). And you try to make a step back? Lol.

I especially shocked since there are no problems with making layouts for your app. You just have to use it differently and instead of this:

```jsx 
const YourComponent = () => {
  return <Layout>
    <div>Your component body</div>
  </Layout>
}

export default YourComponent
```

You have to do this:

```jsx 
const YourComponent = () => {
  return <div>Your component body</div>
}

YourComponent.Layout = Layout

export default YourComponent
```

And I already mentioned it here already, with a link to OFFICIAL example, with more details, so please just read the issue.

[my previous comment (maybe like it so it’s more noticeable by people idk)](https://github.com/vercel/next.js/issues/8193#issuecomment-590654825)

**Comment by laurencefass** [comment] 2021-04-04 08:20
@JerryGreen thanks for info does the _app.js (used in conjunction with layouts) solve the issue and provide partial re-rendeing of pages on re-routes? Are there any examples using layouts in conjunction with Next router?

**Comment by sam3d** [comment] 2021-04-04 08:33
@JerryGreen Adding persistent layouts !== turning Next.js a SPA. You'd still get all of those benefits - It's an additional feature, not a regression. How exactly are you defining a "step back" lol

**Comment by sam3d** [comment] 2021-04-04 08:36
@JerryGreen It's not a regression. This feature only enhances the functionality of Next.js. Also in your example HMR doesn't work for the `Layout` component, so developing and maintaining layouts requires either manual page reloads or putting the `Layout` component in the page tree. Not ideal.

**Comment by Svish** [comment] 2021-04-04 16:44
> I actually a little shocked that people try to turn NextJS app into SPA. NextJS is improved SPA, SEO-friendly, and user-experience friendly (since initial loading times are better, etc). And you try to make a step back? Lol.

It's not about turning next into a spa. It's about sharing ui, or access rights, or something else, in a smaller section of the site. Like an admin panel or whatever.

The page-based routing of next is great, especially with the built-in data fetching methods, and makes sense for a lot of pages,  but not _all_ pages.

**Comment by sam3d** [comment] 2021-04-09 09:19
I like the way [Routify](https://routify.dev/) for svelte solves the bail-out problem. Use a `_layout` which _does_ use any parent layout, or `_reset` which behaves the same as a `_layout` except it doesn't use any parent layouts.

**Comment by dwilt** [comment] 2021-06-20 18:42
@JerryGreen I'm confused why you say the solution you presented "DOES NOT CAUSE re-rendering of whole component tree". I [forked your code sample](https://stackblitz.com/edit/github-g5bxe3?file=pages%2F_app.js) and just put a `console.log('_app rendered')` inside of the `_app` component and it fires on every page transition:

![2021-06-20 14 41 01](https://user-images.githubusercontent.com/1065539/122684795-acaa1900-d1d5-11eb-958b-c8067fa5098b.gif)

Am I missing something?

**Comment by Svish** [comment] 2021-06-20 20:00
Pretty sure that's just how React works. Re-renders, are not a problem. Losing state, is.

**Comment by leerob** [comment] 2021-07-02 22:14
As others have mentioned, there are solutions for this, but it's lacking documentation. In the meantime, I have [updated the layouts example](https://github.com/vercel/next.js/tree/canary/examples/layout-component) to persist state across page transitions. 

I will also be adding docs + a video on this shortly. Thank you!

**Closed by leerob** 2021-07-02 22:14 UTC
Labels: kind: story, point: 21, type: feature request

**Comment by JerryGreen** [comment] 2021-07-02 22:36
@leerob so these two examples are basically equivalent now:

https://github.com/zeit/next.js/tree/canary/examples/with-dynamic-app-layout
https://github.com/vercel/next.js/tree/canary/examples/layout-component (yours)

**Comment by Svish** [comment] 2021-07-02 22:49
Neither of them are in Typescript though... and neither of them deal with any shared loaded data from what I can see. Maybe outside the scope of this particular issue, but a "shared layout hack" like this on its own is pretty useless for me. 😕

Really hope for something like nested `_app` / `_layout` files, supporting both `getServerSideProps` and `getStaticProps`, or something like that. Having to replicate/specify layouts per file, and no data loading...  rather clunky in my opinion, and not a lot of value to me. Could maybe use it to hide the sidebar at certain pages, but feel like I could just as well do that with some simple context/state. 🤷‍♂️

**Comment by Vadorequest** [comment] 2021-07-03 04:00
@Svish is making a good point regarding shared/static data. 

It can be solved for static data using something like what [I've explained here](https://github.com/vercel/next.js/discussions/10949#discussioncomment-959057). 

It's great to see this issue is not forgotten, I hope we get first-class support for doing this in a built-in way at some point though (data fetched at build time, once, even before the pages are built).

**Comment by leerob** [comment] 2021-07-08 13:27
@Svish 

> Neither of the examples are in Typescript though

Feel free to open a PR and add some!

> Neither of them deal with any shared loaded data from what I can see.

Please see [getStaticProps on _app](https://github.com/vercel/next.js/discussions/10949) for current solutions.

> Really hope for something like nested _app / _layout files, supporting both getServerSideProps and getStaticProps, or something like that.

This is something we've been actively exploring solutions for, which will likely be related to [React Server Components](https://vercel.com/blog/everything-about-react-server-components).

>  Having to replicate/specify layouts per file, and no data loading... rather clunky in my opinion, and not a lot of value to me.

You can do data loading on the client-side, see the above link for getStaticProps solutions currently. What you're asking for isn't directly related to this issue though, which is why I closed this one as a solution now exists. That doesn't mean that we're not going to make it better (we are!), but there isn't a bug here and documentation is being added.

I'd recommend following the linked discussion to keep up to date! Thanks.

**Comment by Svish** [comment] 2021-07-08 23:51
> > Neither of the examples are in Typescript though
> 
> Feel free to open a PR and add some!

If I knew how to do that, I wouldn't need the examples? 🤔 Typescript is so important these days, that personally I kind of think that all examples should be in Typescript. Could even help the the Next.js team uncover typing issues and various awkward usage/developer experience as well.

**Comment by JerryGreen** [comment] 2021-07-09 01:49
> I closed this one as a solution now exists

A solution already existed pretty much from the beginning of creation of this issue ([and it was posted in 6th message of this slightly too attention-grabbing issue](https://github.com/vercel/next.js/issues/8193#issuecomment-590654825)

Before creating this layout example of yours, you should have looked at existing ones ;) because those two solutions are exactly the same, nearly a copy. Your example is just slightly better: it uses a simple function, rather than a class (and functions are preferable).

I can’t tell why Timer didn’t close the issue though... I mean, I know why initially: he once said elsewhere that this layout example should stop working at some point, with new react (with fast refresh feature, etc). But react fast refresh is here for a long time already, and layout example still works as intended. So probably Timer was wrong, and the issue might’ve been closed for a long time ago.
