### ISSUE TITLE
Custom fonts not added at the document level will only load for a single page.

### ISSUE THREAD

**Issue by deadcoder0904** [vercel/next.js#26894] opened 2021-07-03 12:11 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

16.3.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

I am getting a warning:

> Custom fonts not added at the document level will only load for a single page. This is discouraged. See https://nextjs.org/docs/messages/no-page-custom-font.eslint(@next/next/no-page-custom-font)

When I visit [the link](https://nextjs.org/docs/messages/no-page-custom-font) in the error, it mentions to me that I create a `pages/_document.js` file to paste the following content:

```js
// pages/_document.js

import Document, { Html, Head, Main, NextScript } from 'next/document'

class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head>
          <link
            href="https://fonts.googleapis.com/css2?family=Inter&display=optional"
            rel="stylesheet"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument
```

I am using similar content mentioned on the error page.

```tsx
// pages/_document.tsx

import NextDocument, { Html, Head, Main, NextScript, DocumentContext } from 'next/document'

class MyDocument extends NextDocument {
	static async getInitialProps(ctx: DocumentContext) {
		const initialProps = await NextDocument.getInitialProps(ctx)
		return { ...initialProps }
	}

	render() {
		return (
			<Html lang="en">
				<Head>
					<link rel="preconnect" href="https://fonts.googleapis.com" />
					<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
					<link
						href="https://fonts.googleapis.com/css2?family=Lora:wght@700&display=swap"
						rel="stylesheet"
					/>
				</Head>
				<body
					className="dark:bg-primary dark:text-white"
				>
					<Main />
					<NextScript />
				</body>
			</Html>
		)
	}
}

export default MyDocument
```

### Expected Behavior

It shouldn't give a warning in VSCode.

### To Reproduce

Just create a simple Next + TS project & paste the above thing in `_document.tsx`

**Comment by JClackett** [comment] 2021-07-04 15:19
Have the same issue, seems the next lint package is recognizing _document as a custom page.

**Comment by housseindjirdeh** [comment] 2021-07-07 15:47
Duplicate of #26160. The issue is the rule is (incorrectly) checking for the name `Document` as the default export. If you change `NextDocument` to `Document`, you won't see the issue anymore.

Fix is here #26331. Once that's merged, you'll be able to use any name for the default export and not see the warning anymore.

**Closed** 2021-07-08 19:43 UTC
Labels: template: bug

**Comment by deadcoder0904** [comment] 2021-07-10 13:02
> Duplicate of #26160. The issue is the rule is (incorrectly) checking for the name `Document` as the default export. If you change `NextDocument` to `Document`, you won't see the issue anymore.

That is weird but it works after changing to `Document` :)

**Comment by balazsorban44** [comment] 2022-01-27 15:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
