### ISSUE TITLE
sometimes the image component throws a ts error on layout="fill"

### ISSUE THREAD

**Issue by alicerocheman** [vercel/next.js#24300] opened 2021-04-21 09:09 UTC
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

next/image component shows a type error on layout="fill" sometimes. In my case, if the layout is conditional, and if width/height are set, even with undefined.

Without condition or width/height
<img width="579" alt="Screenshot 2021-04-22 at 09 00 28" src="https://user-images.githubusercontent.com/21168856/115670093-52ade400-a349-11eb-9abc-45ca81b63609.png">

With condition:
<img width="918" alt="Screenshot 2021-04-22 at 09 00 54" src="https://user-images.githubusercontent.com/21168856/115670142-5e99a600-a349-11eb-90cf-4c51f0e63814.png">

With width/height:
<img width="830" alt="Screenshot 2021-04-22 at 09 04 35" src="https://user-images.githubusercontent.com/21168856/115670517-c9e37800-a349-11eb-962c-d1101ec12985.png">

With both:
<img width="844" alt="Screenshot 2021-04-22 at 09 04 17" src="https://user-images.githubusercontent.com/21168856/115670506-c819b480-a349-11eb-9182-6364b9bcd8fc.png">

### Expected Behavior

layout="fill" should work regardless of the condition

### To Reproduce

```tsx

          <Image
            src={media.path}
            alt={media.caption}
            layout={isFullScreen ? 'intrinsic' : 'fill'}
            objectFit={isFullScreen ? undefined : 'cover'}
            width={isFullScreen && imageSize ? imageSize.width : undefined}
            height={isFullScreen && imageSize ? imageSize.height : undefined}
            sizes="
              (min-width:1024px) 1500,
              (min-width:768px) 1024px,
              (min-width:500px) 768px, 
              500px
            "
            onLoad={handleLoaded}
          />·
```

**Comment by alicerocheman** [comment] 2021-04-22 09:20
For those who encounter this issue, I temp fixed it like this:
```tsx
        <Image
            src={media.path}
            alt={media.caption}
            /* @ts-expect-error issue with next/image layout types */
            layout={isFullScreen ? 'responsive' : 'fill'}
            objectFit={isFullScreen ? undefined : 'cover'}
            width={isFullScreen && imageSize ? imageSize.width : undefined}
            height={isFullScreen && imageSize ? imageSize.height : undefined}
            sizes="
              (min-width:1024px) 1500,
              (min-width:768px) 1024px,
              (min-width:500px) 768px, 
              500px
            "
            onLoad={handleLoaded}
          />·
```

**Comment by ijjk** [comment] 2021-04-28 01:09
The types look correct as `fill` doesn't allow the `height` prop while other layout values do so TypeScript is showing this error. 

I'm going to close this since it appears to be correct.

**Closed by ijjk** 2021-04-28 01:09 UTC
Labels: template: bug

**Comment by alicerocheman** [comment] 2021-04-30 07:08
> The types look correct as `fill` doesn't allow the `height` prop while other layout values do so TypeScript is showing this error.
> 
> I'm going to close this since it appears to be correct.

My code only allows for correct configurations, but there still is a ts error, that doesn't seem correct to me...

**Comment by balazsorban44** [comment] 2022-01-28 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
