### ISSUE TITLE
App dir unmount all components instead of rehydrate

### ISSUE THREAD

**Issue by joacub** [vercel/next.js#49185] opened 2023-05-04 02:50 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Latest canary version as per today
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

No response 

### To Reproduce

In the latest canary version with the new app dir layouts navigate from /en/page2/page2 to for example /es/page2/page2

route: [lang][slug][slug2]

### Describe the Bug

The same segment get unmount and mounted when a segment changes and remount everything from the segment that was change down the three

### Expected Behavior

The same segment should not get remounted as the component is already in the view and can be reused. I don’t know if is like that by design or not but if is by design there should be a option in the routing to opt out for unmount them, and then instead reuse the component that is already mount. Keeping all the state that this components has.

Again if this is by design and you want to keep the granular configuration you can add this to the pages and layouts as you are doing now for the revalidating cache and other options you are already pulling from this files as well as the routing push and or replace to invalidate this by params to specific cases.

### Which browser are you using? (if relevant)

Does not matter

**Comment by timneutkens** [comment] 2023-05-10 13:49
Duplicate of https://github.com/vercel/next.js/issues/48082#issuecomment-1540060041

**Closed by timneutkens** 2023-05-10 13:49 UTC
Labels: template: bug, area: Routing, area: app

**Comment by remorses** [comment] 2023-05-13 12:30
I created an [RFC](https://github.com/vercel/next.js/discussions/49749) to add an option to not reset state on navigation

**Comment by joacub** [comment] 2023-05-13 16:13
> I created an [RFC](https://github.com/vercel/next.js/discussions/49749) to add an option to not reset state on navigation

I like your idea, I leave one suggestion more you may for got to mention if you want to add to the rfc.
