### ISSUE TITLE
Docs: Support docs versioning out of the box

### ISSUE THREAD

**Issue by manojadams** [vercel/next.js#64514] opened 2024-04-15 17:09 UTC
### What is the improvement or update you wish to see?

Nextra can provide support for versioning docs

## Provide doc versioning support like the following site:

<img width="1516" alt="Screenshot 2024-04-15 at 10 32 17 PM" src="https://github.com/vercel/next.js/assets/1009561/10257180-5200-4ac1-9592-146407bb9c7d">

**Comment by balazsorban44** [comment] 2024-04-18 08:53
Duplicate of #64714

**Closed by balazsorban44** 2024-04-18 08:53 UTC
Labels: Documentation
