### ISSUE TITLE
CSS files in root app layout are not combined into single CSS file

### ISSUE THREAD

**Issue by switz** [vercel/next.js#45081] opened 2023-01-20 10:39 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
$ npx next info

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.7.0
      npm: 8.1.0
      Yarn: 3.2.2
      pnpm: 6.20.3
    Relevant packages:
      next: 13.1.4-canary.0
      eslint-config-next: 13.1.2
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-lzpknd?file=app/layout.tsx

### To Reproduce

https://stackblitz.com/edit/vercel-next-js-lzpknd?file=app/layout.tsx

```
// layout.tsx
import '../file1.css';
import '../file2.css';

export default function Layout() {
  return 'layout!';
}
```

### Describe the Bug

![image](https://user-images.githubusercontent.com/990166/213675173-1016ad96-7fe0-424c-9cd9-ef7ed8f14ebf.png)

css files are individually generated in production, when they should be concatenated into a single file together.

### Expected Behavior

According to the stable next docs (https://nextjs.org/docs/basic-features/built-in-css-support):

> In production, all CSS files will be automatically concatenated into a single minified .css file.

That's what I would expect.

### How are you deploying your application? (if relevant)

self-hosted

**Comment by shuding** [comment] 2023-05-26 21:07
I just confirmed that this issue has been fixed in the latest version of Next.js. But keep in mind that if you have CSS imported in different layouts, they're merged per layout. That's because 2 layouts can be rendered separately.

**Closed by shuding** 2023-05-26 21:07 UTC
Labels: template: bug
