### ISSUE TITLE
with-emotion: Invalid package config

### ISSUE THREAD

**Issue by gu-stav** [vercel/next.js#19746] opened 2020-12-02 14:21 UTC
# Bug report

## Describe the bug

Emotion 11 throws an error during the compilation.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone https://github.com/vercel/next.js/tree/canary/examples/with-emotion
2. Run `yarn dev`

## Expected behavior

It should work.

## Screenshots

```bash
kolle-on-xps :: moving-cities/with-emotion-app » yarn dev
yarn run v1.22.4
$ next
ready - started server on http://localhost:3000
error - ./node_modules/next/dist/client/polyfills.js
Error [ERR_INVALID_PACKAGE_CONFIG]: Invalid package config ~/with-emotion-app/node_modules/@emotion/babel-plugin/node_modules/stylis/package.json. "exports" cannot contain some keys starting with '.' and some not. The exports object must either be an object of package subpath keys or an object of main entry condition name keys only.
event - build page: /next/dist/pages/_error
wait  - compiling...
error - ./node_modules/next/dist/client/next-dev.js
Error [ERR_INVALID_PACKAGE_CONFIG]: Invalid package config ~/with-emotion-app/node_modules/@emotion/babel-plugin/node_modules/stylis/package.json. "exports" cannot contain some keys starting with '.' and some not. The exports object must either be an object of package subpath keys or an object of main entry condition name keys only.
Error: Cannot find module '~/with-emotion-app/.next/server/pages-manifest.json'
Require stack:
- ~/with-emotion-app/node_modules/next/dist/next-server/server/require.js
- ~/with-emotion-app/node_modules/next/dist/next-server/server/load-components.js
- ~/with-emotion-app/node_modules/next/dist/next-server/server/api-utils.js
- ~/with-emotion-app/node_modules/next/dist/next-server/server/next-server.js
- ~/with-emotion-app/node_modules/next/dist/server/next.js
- ~/with-emotion-app/node_modules/next/dist/server/lib/start-server.js
- ~/with-emotion-app/node_modules/next/dist/cli/next-dev.js
- ~/with-emotion-app/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at getPagePath (~/with-emotion-app/node_modules/next/dist/next-server/server/require.js:1:657)
    at requirePage (~/with-emotion-app/node_modules/next/dist/next-server/server/require.js:1:1062)
    at loadComponents (~/with-emotion-app/node_modules/next/dist/next-server/server/load-components.js:1:807)
    at DevServer.findPageComponents (~/with-emotion-app/node_modules/next/dist/next-server/server/next-server.js:73:296)
    at DevServer.renderErrorToHTML (~/with-emotion-app/node_modules/next/dist/next-server/server/next-server.js:125:120)
    at DevServer.renderErrorToHTML (~/with-emotion-app/node_modules/next/dist/server/next-dev-server.js:34:974) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '~/with-emotion-app/node_modules/next/dist/next-server/server/require.js',
    '~/with-emotion-app/node_modules/next/dist/next-server/server/load-components.js',
    '~/with-emotion-app/node_modules/next/dist/next-server/server/api-utils.js',
    '~/with-emotion-app/node_modules/next/dist/next-server/server/next-server.js',
    '~/with-emotion-app/node_modules/next/dist/server/next.js',
    '~/with-emotion-app/node_modules/next/dist/server/lib/start-server.js',
    '~/with-emotion-app/node_modules/next/dist/cli/next-dev.js',
    '~/with-emotion-app/node_modules/next/dist/bin/next'
  ]
}
```

I've also setup another project based on the example. There it compiles, but throws the following error in the browser:

```bash
Error [ERR_INVALID_PACKAGE_CONFIG]: Invalid package config ~/web/node_modules/@emotion/cache/node_modules/stylis/package.json. "exports" cannot contain some keys starting with '.' and some not. The exports object must either be an object of package subpath keys or an object of main entry condition name keys only.
    at isConditionalExportsMainSugar (internal/modules/esm/resolve.js:449:13)
    at packageExportsResolve (internal/modules/esm/resolve.js:470:7)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (~/web/node_modules/@emotion/cache/dist/emotion-cache.cjs.dev.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'ERR_INVALID_PACKAGE_CONFIG'
}
```

## System information

- OS: Ubuntu 20.10
- Version of Next.js: 10.0.3
- Version of Node.js: 14.15.1
- Deployment: local

**Comment by SamtheSaint** [comment] 2020-12-04 00:42
tried to reproduce the error but it works just fine

**Comment by gustavpursche** [comment] 2020-12-04 10:09
Alright, I found out that removing [this line](https://github.com/thysultan/stylis.js/blob/master/package.json#L20) from stylis actually fixes the issue., but to be honest I have no idea to properly apply the fix. Is this even an issue of next, oder rather stylis?

@SamtheSaint can you help here?

**Comment by SamtheSaint** [comment] 2020-12-04 10:31
What version of the stylis package did you install because I tried installing stylis@4.0.6 and I was able to start the development server with no issues.

**Comment by gustavpursche** [comment] 2020-12-04 11:28
@SamtheSaint Thanks for your reply!

I didn't install stylis explicitly, but as dependency of emotion.

```
"@emotion/babel-preset-css-prop": "^11.0.0",
"@emotion/react": "^11.1.1",
"@emotion/styled": "^11.0.0",
```

came with

```
stylis@3.5.0
```

**Comment by SamtheSaint** [comment] 2020-12-04 13:49
Can you provide your full package.json and lock file so I can try to reproduce exactly because I've tried setting up a project with the following package.json and it works just fine:
```javascript
{
  "name": "with-emotion",
  "version": "1.0.0",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "license": "MIT",
  "devDependencies": {
    "@emotion/babel-preset-css-prop": "^11.0.0"
  },
  "dependencies": {
    "@emotion/react": "^11.1.1",
    "@emotion/styled": "^11.0.0",
    "next": "10.0.3",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  }
}
``` 

The stylis package config that is causing the error for you has the following package.json in my project. Could you provide the corresponding package.json located at `node_modules/@emotion/cache/node_modules/stylis/package.json`:
```javascript
{
  "name": "stylis",
  "version": "4.0.6",
  "license": "MIT",
  "description": "A Light–weight CSS Preprocessor",
  "homepage": "https://github.com/thysultan/stylis.js",
  "author": "Sultan Tarimo <sultantarimo@me.com>",
  "repository": "https://github.com/thysultan/stylis.js",
  "bugs": "https://github.com/thysultan/stylis.js/issues",
  "sideEffects": false,
  "type": "module",
  "main": "dist/umd/stylis.js",
  "module": "dist/stylis.mjs",
  "react-native": "./index.js",
  "exports": {
    ".": {
      "import": "./index.js",
      "require": "./dist/umd/stylis.js"
    },
    "./package.json": "./package.json"
  },
  "files": [
    "index.js",
    "dist/",
    "src/"
  ],
  "scripts": {
    "lint": "eslint ./",
    "pretest": "npm run lint && npm run build",
    "test": "nyc npm run spec",
    "spec": "mocha --harmony --require esm script/setup.js --recursive test",
    "prebuild": "rimraf dist",
    "build": "rollup --config script/build.js --configSrc ./",
    "start": "npm run build -- --watch",
    "prepare": "npm run build",
    "postversion": "git push --follow-tags && npm publish",
    "release-major": "npm version major -m '%s'",
    "release-minor": "npm version minor -m '%s'",
    "release-patch": "npm version patch -m '%s'"
  },
  "devDependencies": {
    "chai": "4.2.0",
    "eslint": "6.8.0",
    "esm": "3.2.25",
    "mocha": "7.0.0",
    "nyc": "15.0.0",
    "rimraf": "3.0.2",
    "rollup": "1.28.0",
    "rollup-plugin-size": "0.2.1",
    "rollup-plugin-terser": "5.1.3",
    "stylis": "./"
  },
  "nyc": {
    "temp-dir": "./coverage/.nyc_output",
    "exclude": [
      "**/dist/",
      "**/test/",
      "**/script/"
    ],
    "reporter": [
      "lcov",
      "text"
    ]
  },
  "esm": {
    "cjs": true,
    "cache": false
  },
  "eslintIgnore": [
    "script/",
    "test/",
    "dist/",
    "docs/"
  ],
  "eslintConfig": {
    "env": {
      "commonjs": true,
      "browser": true,
      "node": true,
      "es6": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
      "ecmaVersion": 7,
      "sourceType": "module",
      "ecmaFeatures": {
        "impliedStrict": true
      }
    },
    "rules": {
      "indent": [
        "error",
        "tab",
        {
          "SwitchCase": 1
        }
      ],
      "linebreak-style": [
        "error",
        "unix"
      ],
      "quotes": [
        "error",
        "single"
      ],
      "semi": [
        "error",
        "never"
      ],
      "no-cond-assign": [
        "off"
      ],
      "no-redeclare": [
        "off"
      ],
      "no-fallthrough": [
        "off"
      ],
      "no-console": [
        "off"
      ],
      "no-unsafe-finally": [
        "off"
      ],
      "no-shadow-restricted-names": [
        "error"
      ],
      "no-whitespace-before-property": [
        "error"
      ],
      "eol-last": [
        "error"
      ],
      "func-call-spacing": [
        "error",
        "never"
      ],
      "brace-style": [
        "error",
        "1tbs",
        {
          "allowSingleLine": true
        }
      ],
      "require-jsdoc": [
        "error",
        {
          "require": {
            "FunctionDeclaration": true
          }
        }
      ],
      "no-trailing-spaces": [
        "error",
        {
          "skipBlankLines": true
        }
      ],
      "no-constant-condition": [
        "off"
      ]
    }
  }
}
```

Also, try clearing your cache by running `yarn cache clean` or `npm cache clean --force`, deleting node_modules, and reinstalling the entire project.

**Comment by gustavpursche** [comment] 2020-12-04 13:56
@SamtheSaint I've pushed the repo just now, that I'm working on: https://github.com/gustavpursche/moving-cities Let's see if you can replicate the issue there.

Cleaning the cache and removing all cached node_modules didn't help.

**Comment by SamtheSaint** [comment] 2020-12-04 14:43
@gustavpursche I was able to reproduce and track the error this time. The issue is that the @emotion/cache version of stylis retrieves the 4.0.5 version of the package which had a bug in the package.json, but was fixed in the subsequent 4.0.6 release. Applying the fix to the node modules fixes the problem locally:

```javascript
  "exports": {
    ".": {
      "import": "./index.js",
      "require": "./dist/umd/stylis.js"
    },
    "./package.json": "./package.json"
  },
```

**Comment by SamtheSaint** [comment] 2020-12-04 14:49
@gustavpursche A more permanent fix seems to be making the babel packages dev dependencies. The following package.json works without any modification. Delete your package.json and node_modules and reinstall before running.

```javascript
{
  "name": "web",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@emotion/react": "^11.1.1",
    "@emotion/styled": "^11.0.0",
    "mapbox-gl": "^1.13.0",
    "next": "10.0.3",
    "react": "17.0.1",
    "react-dom": "^17.0.1",
    "react-draggable": "^4.4.3",
    "react-mapbox-gl": "^5.1.1",
    "react-use": "^15.3.4"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@emotion/babel-preset-css-prop": "^11.0.0",
    "@emotion/babel-plugin": "^11.0.0"
  }
}
```

**Comment by gustavpursche** [comment] 2020-12-04 15:06
@SamtheSaint Wooow, you are right :rocket: Thank you so much! If you don't mind: why does moving it into the dev dependencies actually solve the issue?

**Comment by talentlessguy** [comment] 2020-12-11 15:50
same error, installing babel/core as a dev dep didn't help it

**package.json**

```
{
  "dependencies": {
    "@chakra-ui/react": "^1.0.3",
    "@emotion/react": "^11.1.2",
    "@emotion/styled": "^11.0.0",
    "@nexus/schema": "^0.19.2",
    "@prisma/client": "^2.13.0",
    "apollo-server-micro": "^2.19.0",
    "graphql": "^15.4.0",
    "next": "^10.0.3",
    "next-auth": "^3.1.0",
    "nexus-plugin-prisma": "^0.26.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@emotion/babel-plugin": "^11.1.2",
    "@emotion/babel-preset-css-prop": "^11.0.0",
    "@prisma/cli": "^2.13.0",
    "@types/node": "^14.14.12",
    "@types/react": "^17.0.0",
    "typescript": "^4.1.2"
  },
}
```

- `node -v`: 15.2.1
- `pnpm -v`: 5.13.5

**Comment by karlhorky** [comment] 2020-12-15 13:31
Nice investigation! Should the example also be changed?

**Comment by JanKaifer** [comment] 2022-11-24 15:05
So this is non-issue if I understood conversation here and this comment:

https://github.com/vercel/next.js/pull/21118#pullrequestreview-569071174


I'll close this old issue but feel free to open a new one if you think that it's still relevant.

**Closed by JanKaifer** 2022-11-24 15:05 UTC
Labels: good first issue, area: examples
