### ISSUE TITLE
Too many filesystem checks error

### ISSUE THREAD

**Issue by ahmedB7r** [vercel/next.js#22799] opened 2021-03-05 12:22 UTC
### What version of Next.js are you using?

10.0.5

### What version of Node.js are you using?

12.0.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

I have the same problem here 
[my deployed site](https://store-alpha.vercel.app/admin/signin)
I have create-react-app build and want to serve it in my nextjs app
so I make just one rewrite in my next.config.js
```
  rewrites: async () => [
    {
      source: "/admin/:page*",
      destination: "/api/static/admin/:page*",
    },
  ],
```
pages/api/static/admin/[page].js
```
// import

import fs from "fs";

// vars

const filename = "./public/dashboard/index.html";

// export

export default async function api(req, res) {
  res.setHeader("Content-Type", "text/html; charset=utf-8");
  res.write(await fs.readFileSync(filename, "utf-8"));
  res.end();
}
```
and worked prefectly local
and get this error with vercel
working normally with heroku !!!
https://store-client-b7r.herokuapp.com/admin/signin

### Expected Behavior

working normally like heroku 
https://store-client-b7r.herokuapp.com/admin/signin

### To Reproduce

1- make a build of client-side app with nested routing like (create-react-app)
2- put it in  public folder to serve it 
3- make api route to serve all nested routes
4- make rewrites change in next-config.js file to prettify the URL

**Comment by ijjk** [comment] 2021-03-05 16:08
Hi, can you try upgrading to the latest version of Next.js `v10.0.8`?

**Comment by ahmedB7r** [comment] 2021-03-05 18:43
> Hi, can you try upgrading to the latest version of Next.js `v10.0.8`?

thanks for replying 
facing this error 

error - ./node_modules/antd/lib/message/style/index.less
 Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'

after upgrading and can't skip from it

**Comment by ijjk** [comment] 2021-03-05 18:51
Thanks for trying to upgrade, please provide a repo with a minimal reproduction for the above error and we'd be happy to investigate it!

**Comment by ahmedB7r** [comment] 2021-03-05 19:06
> Thanks for trying to upgrade, please provide a repo with a minimal reproduction for the above error and we'd be happy to investigate it!

that is it 
https://github.com/ahmedB7r/nextTest

**Comment by ijjk** [comment] 2021-03-05 19:21
It looks like you're using legacy dependencies `@zeit/next-less` so you'll need to manually install `webpack@4.46.0` or migrate away from those dependencies on the latest version of Next.js. 

It also looks like you are using an API route to serve content from the public folder which isn't necessary and less performant than just adding the rewrite to the static file in your `next.config.js` itself e.g. `{ source: '/admin/:path*', destination: '/dashboard/index.html' }`

**Comment by ahmedB7r** [comment] 2021-03-05 19:43
> It looks like you're using legacy dependencies `@zeit/next-less` so you'll need to manually install `webpack@4.46.0` or migrate away from those dependencies on the latest version of Next.js.

just removed all legacy  dependencies like @zeit/next-less 

> 
> It also looks like you are using an API route to serve content from the public folder which isn't necessary and less performant than just adding the rewrite to the static file in your `next.config.js` itself e.g. `{ source: '/admin/:path*', destination: '/dashboard/index.html' }`

and I just was trying to escape from my problem and after make this edit give me 404 know 
I updated the repo now 
please look at it :)

**Comment by ijjk** [comment] 2021-03-05 20:33
Ah ok it looks like the rewrite needs to be this since i18n is being used: 
```js
{
  source: '/:locale?/admin/:path*',
  destination: '/dashboard/index.html',
  locale: false
}
```

Note: `vercel.json` file should be removed and all rewrites/headers and `trailingSlash` config moved to `next.config.js` instead.

**Comment by ahmedB7r** [comment] 2021-03-05 21:22
thank u very much,
it's working now perfectly :)

**Comment by ijjk** [comment] 2021-03-05 21:38
Closing per https://github.com/vercel/next.js/issues/22799#issuecomment-791718236

**Closed by ijjk** 2021-03-05 21:38 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-01-28 16:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
