### ISSUE TITLE
Docs: examples for the migration of <link rel='preconnect' href='...' /> to new Metadata API

### ISSUE THREAD

**Issue by patshologram** [vercel/next.js#47399] opened 2023-03-22 14:25 UTC
### What is the improvement or update you wish to see?

Based on https://beta.nextjs.org/docs/api-reference/metadata#unsupported-metadata the `preconnect` Metadata is not supported and a link to https://beta.nextjs.org/docs/optimizing/scripts is provided. We tried to replicate our old `head.tsx` file but couldn't with `<Script>` so we ended up with a hacky solution using the ability from `icons` to override the `rel` value: 
```
 icons: {
    icon: [...],
    other: [
      {
        rel: 'preconnect',
        url: 'test.com',
      },
    ],
  },
```

This is clearly not intended from the API but it works. I would rather have a recommended example from the nextjs team with a clean solution. 

### Is there any context that might help us understand?

We currently migrate to the Metadata API and would like to have a example how `preconnect` tags should be handled. 

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/api-reference/metadata#unsupported-metadata

**Comment by huozhi** [comment] 2023-03-30 11:56
You can use `ReactDOM.preconnect` API in a client component to achieve it. Also `ReactDOM.preload` and `ReactDOM.prefretchDNS` are also available. You have to put them into client component atm, using them in server components are not available yet.

Example
```js
'use client'
import ReactDOM from 'react-dom'

function Comp() {
  ReactDOM.preload('/preload-url', { as: 'script' })
  ReactDOM.preconnect('/preconnect-url', { crossOrigin: 'use-credentials' })
  ReactDOM.prefetchDNS('/dns-prefetch-url')
}
```

We're working on the documentation now, will update it soon

**Comment by philipheinser** [comment] 2023-05-06 16:45
@huozhi `ReactDOM.preload('/preload-url', { as: 'image' })` seams to don't like `image` do you know why?

**Comment by huozhi** [comment] 2023-05-07 12:04
@philipheinser not sure how you tried it, it works for me in app directory. Can you provide a full reproduction in a new issue? Thanks

**Comment by huozhi** [comment] 2023-05-07 12:05
Close this issue as it's documented in [nextjs metadata docs](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#resource-hints now)

**Closed by huozhi** 2023-05-07 12:05 UTC
Labels: template: documentation
