### ISSUE TITLE
with-http2 example exposes problems when converted to typescript

### ISSUE THREAD

**Issue by kobenauf** [vercel/next.js#8625] opened 2019-09-04 20:07 UTC
# Bug report

## Describe the bug

Using the with-http2 example, and then converting server.js to server.ts, the following line has two problems:
 `  return app.render(req, res, '/about', req.query) `

Error 1:
```
Argument of type 'Http2ServerRequest' is not assignable to parameter of type 'IncomingMessage'.
  Type 'Http2ServerRequest' is missing the following properties from type 'IncomingMessage': httpVersionMajor, httpVersionMinor, complete, connectionts(2345)
```
Error 2:
 `Property 'query' does not exist on type 'Http2ServerRequest'.ts(2339)`

## To Reproduce
Create a new project following instructions at [with-http2](https://github.com/zeit/next.js/tree/canary/examples/with-http2):
1. npx create-next-app --example with-http2 my-app
2. Rename server.js to server.ts.
3. Optional: convert the require statements to import statements.
4. See ts errors listed above.

## Expected behavior

The with-http2 probably has some bugs that are not visible until being converted to typescript.  The idea of with-http2 is useful, and ideally there would be an http2 template like this.

## System information

Node 12.8.0

**Comment by ragingwind** [comment] 2019-09-04 23:27
Error1, I might be need that render() support http2 types. like this
```
req: IncomingMessage | Http2ServerRequest,
res: ServerResponse | Http2ServerResponse,
```

Error2, using querystring

```
const parsedUrl = querystring.parse(req.url);
```

**Comment by kobenauf** [comment] 2019-09-05 15:11
I made these changes:
```
import http2, { Http2ServerRequest, Http2ServerResponse } from 'http2'
import { IncomingMessage, ServerResponse } from 'http'
```
```
  server.on('request', (req: IncomingMessage | Http2ServerRequest, res: ServerResponse | Http2ServerResponse) => {
    switch (req.url) {
      case '/about':
        return app.render(req, res, '/about', querystring.parse(req.url))
      default:
        return app.render(req, res, '/', querystring.parse(req.url))
    }
  })
```
The second error is fixed now, but the first error is still there, with a different message now but same underlying problem:
```
Argument of type 'IncomingMessage | Http2ServerRequest' is not assignable to parameter of type 'IncomingMessage'.
  Type 'Http2ServerRequest' is missing the following properties from type 'IncomingMessage': httpVersionMajor, httpVersionMinor, complete, connectionts(2345)
```

**Comment by kobenauf** [comment] 2019-09-05 15:58
I suspect this issue might be related to this underlying Express issue:
https://github.com/expressjs/express/pull/3730

**Comment by ragingwind** [comment] 2019-09-05 19:01
for 1 issues, next-server.d.ts might be changed to

```
render(
    req: IncomingMessage | Http2ServerRequest,
    res: ServerResponse | Http2ServerResponse,
    pathname: string,
    query?: ParsedUrlQuery,
    parsedUrl?: UrlWithParsedQuery
  ): Promise<void>;
```

but I'm not sure it is the best solution

**Comment by balazsorban44** [comment] 2022-01-12 01:08
We now take PRs to convert existing examples to TS, but `with-http2` is an exception, as custom servers are discouraged and thus we are not prioritizing work on them.

> Before deciding to use a custom server, please keep in mind that it should only be used when the integrated router of Next.js can't meet your app requirements. A custom server will remove important performance optimizations, like serverless functions and Automatic Static Optimization.

https://nextjs.org/docs/advanced-features/custom-server

Since th example is working as expected in its current form, I'm closing this issue.

**Closed by balazsorban44** 2022-01-12 01:08 UTC
Labels: good first issue

**Comment by balazsorban44** [comment] 2022-02-11 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
