### ISSUE TITLE
@react-three/drei Text module stopped working starting from 14.0.5-canary.20

### ISSUE THREAD

**Issue by alyustik** [vercel/next.js#61351] opened 2024-01-29 22:35 UTC
### Link to the code that reproduces this issue

https://github.com/alyustik/next-troika-bug

### To Reproduce

1. Start the app via "npm run dev"
2. Open the main page in browser

### Current vs. Expected behavior

**Current**:  
Text isn't rendered and there are multiple console errors (https://next-troika-bug.vercel.app/): 
 - ReferenceError: window is not defined 
 - Uncaught (in promise) Error: Error in worker registerModule call: window is not defined

**Expected**: 
No errors, "hello world" text is rendered inside canvas

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home Single Language
Binaries:
  Node: 18.17.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.20 // Latest available version is detected (14.1.1-canary.20).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

SWC transpilation

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed), Other (Deployed)

### Additional context

the first release introducing the bug is "14.0.5-canary.20"

Given the error messages I got - first of all I've checked if a dynamic import with "ssr: false" will fix the issue, but it doesn't

**Comment by kdy1** [comment] 2024-01-30 07:36
Closing as duplicate of https://github.com/vercel/next.js/issues/60644

**Closed by kdy1** 2024-01-30 07:36 UTC
Labels: template: bug, area: SWC transforms
