### ISSUE TITLE
Port babel-plugin-styled-components to SWC

### ISSUE THREAD

**Issue by timneutkens** [vercel/next.js#30802] opened 2021-11-02 11:48 UTC
This Babel plugin is the most used customization of `.babelrc`.

The plugin is split up in multiple separate transforms:

[https://github.com/styled-components/babel-plugin-styled-components/blob/a26774e599c82c72e8793989f60310d29c181fac/src/index.js](https://github.com/styled-components/babel-plugin-styled-components/blob/a26774e599c82c72e8793989f60310d29c181fac/src/index.js)

The defaults are here: [https://github.com/styled-components/babel-plugin-styled-components/blob/950692b92855f17609e4281d5081e3d2acbf4b6b/src/utils/options.js](https://github.com/styled-components/babel-plugin-styled-components/blob/950692b92855f17609e4281d5081e3d2acbf4b6b/src/utils/options.js)

The critical one which makes styled-components not have hydration issues with Next.js is `displayNameAndId`. All the other ones seem to be optimizations. Because of this I'd start by porting the `displayNameAndId` transform and then check what else can be ported.

Looking at the defaults the only transform that is disabled by default is the pure annotations one.

List of transforms:
- [x] ssr -- enabled when `styledComponents: true`
- [x] displayName -- enabled when `styledComponents: true`, disabled in production to reduce file size
- [x] css prop
- [x] fileName
- [x] minify
- [x] transpileTemplateLiterals
- [x] pure
- [x] namespace

**Comment by switz** [comment] 2021-11-02 18:27
https://github.com/swc-project/swc/issues/2506

Unclear if this is relevant, but it looks like SWC fixed the compiler to not break with styled-components. Still probably not enough to close this issue for customization/optionality, but maybe if updated, swc can compile SC at a base level now?

**Comment by timneutkens** [comment] 2021-11-02 19:00
> [swc-project/swc#2506](https://github.com/swc-project/swc/issues/2506)
> 
> Unclear if this is relevant, but it looks like SWC fixed the compiler to not break with styled-components. Still probably not enough to close this issue for customization/optionality, but maybe if updated, swc can compile SC at a base level now?

The linked issue is unrelated as that one is about the minifier. This issue is about implementing the transforms that are critical for running styled-components correctly when doing SSR.

**Comment by timneutkens** [comment] 2021-11-10 18:32
Posted an update on the feedback thread: https://github.com/vercel/next.js/discussions/30174#discussion-3643870. It's available to try now.

**Comment by cahbb** [comment] 2021-11-22 07:14
Awesome ⭐ 

I'm a bit confused on how to actually implement. Not sure if this is on a "normal" `next@12` version or if I still have to install `next@canary`. https://github.com/vercel/next.js/discussions/30174#discussion-3643870

I'm running version `12.0.2`. Do I still need to use the `experimental` key in `next.config.js`?

This actually works, but am getting no displayNames (component names) on the components. 
```javascript
{
  styledComponent: true
}
```

This works as expected. Do you guys have an estimate on when this is not experimental any more?
```javascript
{
  experimental: {
    styledComponent: true
  }
}
```

**Comment by romulovalez** [comment] 2021-11-22 15:07
Right now is available only on `next@canary` and inside experimental.

Thanks to @kdy1 and @timneutkens for this contribution!

I'll wait for `css prop` to be ready and I will adopt in a blink of an eye!

**Comment by matwii** [comment] 2021-11-23 12:08
Ahh this explains why css prop failed.. I thought it was supported. Is it planned later?

**Comment by janro1** [comment] 2021-11-24 12:00
Hi @kdy1, are you planning to publish the styled-components swc plugin to npm as well? Would be cool if it could also be used with the swc-loader

**Comment by samuelhnrq** [comment] 2021-11-25 12:41
> I'll wait for css prop to be ready and I will adopt in a blink of an eye!

Wait you mean like Emotion's css prop? I've been using it on next 12 already. You can change the JSX pragma trough [jsconfig.json](https://github.com/samuelhnrq/hnrq.dev.br/blob/main/jsconfig.json#L3)

**Comment by nwesthoff** [comment] 2021-11-25 14:47
Thank you @timneutkens, we're all very excited about the work you all have been doing with SWC. 

Our main blocker right now is 'referring to other components' [feature](https://styled-components.com/docs/advanced#referring-to-other-components) of styled-components. I'm not exactly sure what transform this is using, but I wanted to flag it in case it's not on your roadmap already.

**Comment by timneutkens** [comment] 2021-11-26 14:28
> Our main blocker right now is 'referring to other components' feature of styled-components. I'm not exactly sure what transform this is using, but I wanted to flag it in case it's not on your roadmap already.

That feature doesn't seem to rely on any compilation, it's just leveraging tagged template literals. Are you running into an issue with that feature or just checking if it's supported?

**Comment by agriffis** [comment] 2021-11-29 16:01
Do you expect to support `topLevelImportPaths`? We need this for [xstyled](https://xstyled.dev) or any other lib that wraps styled-components. More info:

https://xstyled.dev/docs/migrate-from-styled-components/#babel-plugin
https://github.com/styled-components/babel-plugin-styled-components/pull/288

**Comment by kdy1** [comment] 2021-11-30 09:32
@janro1 

> Hi @kdy1, are you planning to publish the styled-components swc plugin to npm as well? Would be cool if it could also be used with the swc-loader

Sorry for the late response. I finally managed to handle issue emails and saw this.
Of course, although not polished/documented yet but `@swc/core` now supports rust plugins under experimental flags.

But it will require some more work because currently only `displayNameAndId` is ported to rust.

**Comment by janro1** [comment] 2021-11-30 10:28
> @janro1
> 
> > Hi @kdy1, are you planning to publish the styled-components swc plugin to npm as well? Would be cool if it could also be used with the swc-loader
> 
> Sorry for the late response. I finally managed to handle issue emails and saw this. Of course, although not polished/documented yet but `@swc/core` now supports rust plugins under experimental flags.
> 
> But it will require some more work because currently only `displayNameAndId` is ported to rust.

Nice, thank you @kdy1! From what I see, `displayNameAndId` is all we need currently.

**Comment by KimPaow** [comment] 2021-12-01 13:37
When opting in to use SWC I noticed that media-queries like below have a new behaviour. Before the query would take precedence but now the `margin: 23px auto` overwrites `margin: auto auto 120px` even while in that state.

```js
const P = styled(BaseP)`
  margin-bottom: 60px;

  ${mq.breakpoint('sm')} {
    margin: auto auto 120px;
  }
`;

const CenterP = styled(P)`
  text-align: center;
  margin: 23px auto;
`;
```

**Comment by roxeteer** [comment] 2021-12-01 13:40
@KimPaow That has happened randomly in our applications even with babel. Styled-components FAQ has a solution: https://styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity

**Comment by KimPaow** [comment] 2021-12-01 13:51
@roxeteer That seems to be working, thanks for the tip!

**Comment by agriffis** [comment] 2021-12-01 13:59
@roxeteer It's not random. [Media queries don't increase specificity. ](https://css-tricks.com/how-much-specificity-do-rules-have-like-keyframes-and-media/) The wrapping styled-component overrides the wrapped one because the rules come later.

@KimPaow The behavior you describe happens with Babel too, it's not related to SWC. https://codesandbox.io/s/stupefied-grass-e0cox?file=/src/App.js

**Comment by kdy1** [comment] 2021-12-01 14:01
@agriffis I think it's related to the fact only `displayNameAndId` is ported. There were some babel transforms which can modify css, but those are not ported.

**Comment by roxeteer** [comment] 2021-12-01 14:07
@agriffis It's random in the sense that it depends on the order that styled-components outputs the rules, and it doesn't seem to be constant.

**Comment by kdy1** [comment] 2021-12-01 14:22
@agriffis Yes, if you are correct, I think you can compare the output of babel and swc.

**Comment by kdy1** [comment] 2021-12-01 14:32
I think production build will not use `swc` for transpiling because not all passes are ported yet and it can affect bundle size. Production builds should use babel AFAIK.

**Comment by timneutkens** [comment] 2021-12-02 12:44
@kdy1 when experimental.styledComponents is enabled the SWC transform is used for all cases.

**Comment by stefanaxelsson** [comment] 2021-12-10 13:10
When combining a globalClass and a psuedo element the  selector gets defined with an added space

```js
const StyledComponentWithGlobal = styled.div`
  background: red;
  width: 100px;
  height: 100px;

  .globalClass & ::after {
    color: white;
    display: block;
    content: "Only visible using babelrc";
    background: blue;
  }
`;
```
Generated selector using SWC:
```css 
.globalClass .sc-c4e8cc46-0 ::after
```
Generated selector using babel:
```css
.globalClass .sc-izhiy-0::after
```

Full code example: https://github.com/stefanaxelsson/styled-components-swc/blob/main/pages/index.tsx
Deployment: https://styled-components-swc.vercel.app/

**Comment by agriffis** [comment] 2021-12-10 16:51
@stefanaxelsson Ignoring the discrepancy between babel and SWC for the moment, why do you have a space between `&` and `::after` in your styled div?

**Comment by stefanaxelsson** [comment] 2021-12-12 21:42
@agriffis It's an example from an existing codebase so I can't give you an answer to why, I'm afraid.

**Comment by agriffis** [comment] 2021-12-13 18:48
@stefanaxelsson I think the SWC plugin is right, and the bug is in babel-plugin-styled-components, specifically the [minimizer](https://github.com/styled-components/babel-plugin-styled-components/blob/main/src/minify/index.js)

Here's a [sandbox](https://codesandbox.io/s/with-without-babel-plugin-gkrqd?file=/src/Foo.js). `Foo.js` uses styled-components without the plugin. `Bar.js` uses styled-components with the plugin via `styled-components/macro`. You can see the behavior is different between them, when it should always be the same.

So you probably want to fix your code to use `&::after` without a space, because right now it's relying on a bug in the plugin. Then we should file an issue at https://github.com/styled-components/babel-plugin-styled-components, and finally, don't change how SWC works in this regard :smile:

**Comment by FlyingTigerReally** [comment] 2021-12-23 13:40
Do my still need _document.js？

**Comment by kritika-agrawal-dunzo** [comment] 2022-02-08 10:23
@timneutkens when are you planning to release support for `css` prop?

**Comment by refactorized** [comment] 2022-02-15 19:59
From my brief experience of axing our .babelrc (which only had next/babel and "babel-plugin-styled-components), the transform doesn't seem production ready.  

We had several class names fail to hydrate correctly, it seems, and styles were broken in random places around the site.  We don't use the css prop, just regular styled components.  There are a couple places that use styled-system, but that just leverages plain styled components too, iirc. 

Putting the .babelrc back fixed all the issues we were seeing.  I dunno.

**Comment by timneutkens** [comment] 2022-02-18 15:41
@refactorized please provide a reproduction we can look at so that if there is a problem we can fix it in the transform, there are tests in place that verify the hydration works for the normal use-cases shown in the docs. The transform only matches styled-components so if you're using another library that leverages styled-components somehow it'll likely not work. 

Unfortunately just saying "it's not production ready" without examples of your particular case is not going to resolve the issue you're running into.

@kritika-agrawal-dunzo it's on the list of transforms to port and we're going to work on that one very soon, same goes for the Emotion transform.

@Poitrin no configuration is provided for this transform, however for the testing case there is a separate transform that removes specific properties: https://nextjs.org/docs/advanced-features/compiler#remove-react-properties

**Comment by refactorized** [comment] 2022-02-18 16:21
> Unfortunately just saying "it's not production ready" without examples of your particular case is not going to resolve the issue you're running into.

Fair enough, and I why I tried to qualify my claim a bit. But by production ready, I mean I can use this thing, in production, instead of the babel transform.  The other package shouldn't be doing anything differently than I would myself writing functions that execute inside the template literal, but It would be good news all around if it were merely something in that package.

I wasn't looking for a specific resolution (yet) so much as wanted to call out a caveat.  Next is a trusted name in the space, and I know a lot of people are (were) waiting for this to drop, so I wanted to get the warning out right away. Though if "not production ready" came off a little rough I apologize, I'm not trying to ruffle any feathers.

I don't have an easy route to creating a minimal reproduction for this, but I am working on generalizing our internal platform and will have an opportunity to look into this in more depth, and also without that other library. I will create an actual issue for this if I have more trouble and can narrow it down to something reproducible.

Thanks

**Comment by Jongyeol91** [comment] 2022-02-21 09:42
`displayName -- enabled when styledComponents: true, disabled in **production** to reduce file size`
What value determines if it is in production? because i want to show display name in localhost and staging server.

**Comment by timneutkens** [comment] 2022-03-16 10:59
> Is it expected that babel-plugin-styled-components generates different class names then the SWC variant, even if in next.js? Is there any way to let them generate the same classes?

This is expected, the transforms will not generate the same hashes as it's generated by a different programming language and has different inputs for the hash.

**Comment by chentsulin** [comment] 2022-03-22 03:37
Hi @timneutkens, is there any plan to support the `minify` and `pure` options? We would switch our sites to SWC entirely if these options got implemented.

**Comment by agriffis** [comment] 2022-04-07 14:46
@stefanaxelsson Just a heads up that the [minifier bug](https://github.com/styled-components/babel-plugin-styled-components/issues/366) in babel-plugin-styled-components was [fixed in v2.0.7](https://github.com/styled-components/babel-plugin-styled-components/releases/tag/v2.0.7). If you still have code that depends on that bug, you'll want to fix it before you upgrade. Additionally this means that SWC matches the plugin behavior at this point. Ref https://github.com/vercel/next.js/issues/30802#issuecomment-990960985

**Comment by pjaws** [comment] 2022-05-23 20:45
We also need to enable `displayName` in production, since tools like Optimizely and Mutiny use class selectors to target elements.

**Comment by vip30** [comment] 2022-05-24 11:45
We also need this flag in production as we would like to perform end to end test in production env

**Comment by jarvelov** [comment] 2022-05-31 09:49
Hate to be a +1 but being able to configure `displayName` for the production build is important for us as well.

**Comment by ForsakenHarmony** [comment] 2022-06-28 16:06
^ the changes are now in https://github.com/vercel/next.js/releases/tag/v12.2.0

**Comment by AllanOliveiraM** [comment] 2022-10-25 22:52
Hey guys
I'm really looking forward to it, but I'd really like support for xstyled
Can anyone tell me if this will be covered?
I have a lot of big projects that rely heavily on xstyled, and that's all that prevents me from using swc today
Is there already a solution for this?

**Comment by tmb-github** [comment] 2022-11-12 20:56
I'm using Next.js 13.0.3 beta, and I've added to next.config.js:

  ```
compiler: {
    styledComponents: true,
  },
```

However, when my own client-side JavaScript adds classes to elements, I'm getting the warning `"Prop "className" did not match. Server: "<myclass, etc.>"`

How do I prevent this warning? I do want to use ssr and rust, and I need to add classes to elements in the client, classes that are not present on the component expressed in the server-side JSX. Adding `styledComponents: true` is not fixing it.

**Comment by aleksanderd** [comment] 2022-11-17 12:46
@tmb-github same here, but only for cases where use `css` prop (https://styled-components.com/docs/api#css-prop)

anyone use `css` prop successfully or it is not possible for now?

**Comment by cjimmy** [comment] 2022-11-17 15:38
@aleksanderd in my experience, after updating to next 12, you have to use template string literals when using the `css` prop:

see https://github.com/vercel/next.js/issues/38891

```
<div css={`padding-left: 4px`} />
```

**Comment by tmb-github** [comment] 2022-11-17 17:57
How do we create a custom 404 page, similar to the custom 404.js file that is used in version 12? The docs do not clarify how this can be done in version 13. Creating an explicit `_error` directory seems to be part of the equation, but it's not clear what to do beyond that.

If you create `app/_error/page.js`, then when running the app the following message is sent to the terminal:

`You have added a custom /_error page without a custom /404 page. This prevents the 404 page from being auto statically optimized.` 

It suggests looking at https://nextjs.org/docs/messages/custom-error-no-custom-404, but that document is specific to the 'pages' paradigm of version 12, not the 'app' paradigm of version 13.

**Comment by xgqfrms** [comment] 2022-12-01 18:35
# not work

![image](https://user-images.githubusercontent.com/7291672/205132849-ea3da530-eaee-4db1-a3e5-cf33b65b920d.png)

> `next.config.js`

```js
/** @type {import('next').NextConfig} */

const nextConfig = {
  // reactStrictMode: true,
  reactStrictMode: false,
  compiler: {
    styledComponents: true,
  },
}

// CJS
// module.exports = nextConfig

// ESM ✅
export default nextConfig;

```

**Comment by machineghost** [comment] 2023-01-13 19:01
Like @tmb-github I have Styled Components enabled in `next.config.js`, but am still getting:

>next-dev.js?3515:20 Warning: Prop `className` did not match. Server: "sc-gfzQCe kcKMgT" Client: "sc-kgTSHT cEirDk"

**Comment by jt3k** [comment] 2023-01-24 13:37
excuse me for being toxic. but I have always told everyone that styled is garbage, deciding to use it for large projects, you doom your future colleagues to misfortune and suffering.

**Comment by kiki1027** [comment] 2023-02-08 07:47
> I'm using Next.js 13.0.3 beta, and I've added to next.config.js:
> 
> ```
> compiler: {
>   styledComponents: true,
> },
> ```
> 
> However, when my own client-side JavaScript adds classes to elements, I'm getting the warning `"Prop "className" did not match. Server: "<myclass, etc.>"`
> 
> How do I prevent this warning? I do want to use ssr and rust, and I need to add classes to elements in the client, classes that are not present on the component expressed in the server-side JSX. Adding `styledComponents: true` is not fixing it.

I fixed the warning `"Prop "className" did not match. Server: "<myclass, etc.>"`  by setting `next.config.js` like this:

```js
// @ts-check
const { i18n } = require('./next-i18next.config.js');

/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {
  reactStrictMode: true,
  compiler: { styledComponents: { ssr: true } },  // ✅
  i18n,
  trailingSlash: true,
};

module.exports = nextConfig;
```

- Nextjs@12 +
- styled-components

Trouble Shooting:

only set `compiler: { styledComponents: true }` is not enough ❌

**Comment by aleksanderd** [comment] 2023-02-08 12:00
> 

@kiki1027 its strange since it is enabled by default https://nextjs.org/docs/advanced-features/compiler

![image](https://user-images.githubusercontent.com/5766592/217523789-37669f94-2612-4afb-89f3-e2e71f968d2d.png)

**Comment by machineghost** [comment] 2023-02-08 16:44
It's been four months now, and we haven't heard a peep from the Next maintainers.  Meanwhile, I asked the Styled Components maintainer if he could just take a look at what Next was doing, and he emphatically told me that it wasn't his library, and therefore not his problem.

So, until someone at Next decides to care about Styled Components, it looks like the only "fix" is my (terrible) one.

**Comment by ekaterina4952** [comment] 2023-05-15 13:30
I have still same issue on the nextjs 13.4.1 even though I configured such as [document](https://nextjs.org/docs/architecture/nextjs-compiler#styled-components) of nextjs.
`compiler: {
        styledComponents: { ssr: true}
    }`

`Prop "className" did not match. Server: "mui-style-1ggikmx" Client: "css-1ggikmx" `

**Comment by thexpand** [comment] 2023-05-15 13:55
I know this is probably not very relevant to the issue at hand, but I'll give you my 2 cents. It's been a very long time since this issue was opened. At some point, I just decided not to use SWC on the project that used the `styled-components` package. Later on, I started using CSS Modules with `sass` support and got completely hooked up. It's so much lighter on the final bundle and pages load definitely faster. For conditional switching of CSS classes, I use the `classnames` npm package. For me, CSS-in-JS puts too much pressure on the bundle and bloats it unnecessarily. Since I ditched it, I never looked back.

**Comment by utikati** [comment] 2023-08-07 15:36
> I know this is probably not very relevant to the issue at hand, but I'll give you my 2 cents. It's been a very long time since this issue was opened. At some point, I just decided not to use SWC on the project that used the `styled-components` package. Later on, I started using CSS Modules with `sass` support and got completely hooked up. It's so much lighter on the final bundle and pages load definitely faster. For conditional switching of CSS classes, I use the `classnames` npm package. For me, CSS-in-JS puts too much pressure on the bundle and bloats it unnecessarily. Since I ditched it, I never looked back.

Can you just tell me if in dev you can trace the file where your style is? 
Im using SASS and in dev in browser i try to debug but all I see is "layout.css" with all the styles, did you had the same problem?

**Comment by 2Pacalypse-** [comment] 2023-08-21 17:58
Hey guys, I'm using the newest Next.js with the SWC compiler and styled-components work fine, but I don't see the more useful class names in the developer tools, which is supposed to be controlled with the `displayNames` config property. Nothing I do seem to fix this, and even more weirdly this used to work fine with the pages router, but doesn't work now with the app router. Does anyone know what might be wrong, or what's the best way to debug this in case it's a bug in Next.js's code?

**Comment by machineghost** [comment] 2023-08-21 18:21
Honestly, the fact that this ticket has been open for almost two years should tell you everything you need to know: the Next.js team just doesn't care about supporting Styled Components.

Similarly, don't expect the Styled Components devs to help out in any way: when I asked the guy who answered basically said that he was the only developer left, and he could barely keep the library maintained on his own, so he doesn't have time to help out other projects.

Sadly, in 2023, if you want to use Next.js, you either have to abandon Styled Components (as I did), or live with a flawed integration.

**Comment by Lwdthe1** [comment] 2023-08-27 01:32
> > I'm using Next.js 13.0.3 beta, and I've added to next.config.js:
> > ```
> > compiler: {
> >   styledComponents: true,
> > },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, when my own client-side JavaScript adds classes to elements, I'm getting the warning `"Prop "className" did not match. Server: "<myclass, etc.>"`
> > How do I prevent this warning? I do want to use ssr and rust, and I need to add classes to elements in the client, classes that are not present on the component expressed in the server-side JSX. Adding `styledComponents: true` is not fixing it.
> 
> I fixed the warning `"Prop "className" did not match. Server: "<myclass, etc.>"` by setting `next.config.js` like this:
> 
> ```js
> // @ts-check
> const { i18n } = require('./next-i18next.config.js');
> 
> /**
>  * @type {import('next').NextConfig}
>  */
> const nextConfig = {
>   reactStrictMode: true,
>   compiler: { styledComponents: { ssr: true } },  // ✅
>   i18n,
>   trailingSlash: true,
> };
> 
> module.exports = nextConfig;
> ```
> 
> * Nextjs@12 +
> * styled-components
> 
> 🔎 Trouble Shooting:
> 
> 1. Only set `compiler: { styledComponents: true }` is not enough ❌
> 2. If used nextjs@12+，**no need** to import babel plugin `babel-plugin-styled-components`

This got me to a solution, but mine is slightly different. I'm using:
* `"next": "^13.1.6"`, 
* `"react": "^18.2.0",`, 
* `"styled-components": "^6.0.7",` ,
* `"babel-plugin-styled-components": "^1.13.3",`
* `"webpack": "^5.88.2"`

The following are my `next.config.js` and `.babelrc` setups:

```js
// next.config.js
module.exports = {
  return {
    env,
    useFileSystemPublicRoutes: false,
    typescript: {
	// TODO: Remove once project is fully typed
	ignoreBuildErrors: true,
    },
    compiler: {
	styledComponents: true,
    },
  }
}
```

```
// .babelrc
"plugins": [
		// ... other plugins
		[
			"babel-plugin-styled-components",
			{
				"ssr": true,
				"displayName": true,
				"preprocess": false
			}
		]
	]
```

**Comment by kdy1** [comment] 2023-08-27 04:09
@Lwdthe1 If you have `.babelrc`, `compiler.styledComponents` has no effect.

**Comment by Lwdthe1** [comment] 2023-08-27 21:21
> @Lwdthe1 If you have `.babelrc`, `compiler.styledComponents` has no effect.

That's what I heard elsewhere, but that's not true. If I remove `compiler.styledComponents`, my css props stop working completely.

However, it does appear the `babel-plugin-styled-components` has no effect if I keep it or remove it so long as I have `compiler.styledComponents`.

**Comment by 2Pacalypse-** [comment] 2023-08-29 12:57
>Hey guys, I'm using the newest Next.js with the SWC compiler and styled-components work fine, but I don't see the more useful class names in the developer tools, which is supposed to be controlled with the displayNames config property. Nothing I do seem to fix this, and even more weirdly this used to work fine with the pages router, but doesn't work now with the app router. Does anyone know what might be wrong, or what's the best way to debug this in case it's a bug in Next.js's code?

In case someone else faces the same issue, I've fixed it by doing what this comment suggested: https://github.com/vercel/next.js/issues/46605#issuecomment-1639900755

Sounds ridiculous, but it works.

**Comment by S-YOU** [comment] 2023-09-16 02:11
> pure, minify and transpileTemplateLiterals are not implemented yet

May I know why minify is not supporting? I am seeing standalone/.build folder js contents not getting minified.

**Comment by fnwbr** [comment] 2023-10-24 17:41
Hey @kdy1 👋 
Thank you very much for your continued efforts on this. As I'm seeing some movement in the [@swc/plugin-styled-components](https://www.npmjs.com/package/@swc/plugin-styled-components) package, can you maybe enlighten the rest of us?

As referred to by @2Pacalypse- and @d-nakajima, **how come that this is the case**?

> I faced same problem when I use `import { styled } from 'styled-components'`. I change to `import styled from 'styled-components'` and it is fixed. Please try this change If your code is like first one.
> 
> (I don't know why it is fixed. The code for export in 'styled-components' file is `export { styled, styled as default }` ...)

Is there any chance you can fix this behavior going forward, and allow us to also use the following style of importing as well?
```js
import { styled } from 'styled-components';
```
(This is the recommended way as of https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-named-as-default.md)

**Comment by kdy1** [comment] 2023-10-25 20:03
Okay. I think at least the recommended way should work out of the box. I'll work on it. Thank you for the notice. I didn't know that it's the recommended way.

**Comment by kdy1** [comment] 2023-10-25 20:05
Filed https://github.com/swc-project/plugins/issues/224 anyway, but I have lots of tasks with higher priority

**Closed** 2023-11-27 10:02 UTC
Labels: kind: story, area: SWC transforms

**Comment by fnwbr** [comment] 2023-12-05 16:26
Can confirm that `import { styled } from 'styled-components';` is now also working as expected. (Tested Next.js `14.0.4-canary.41`)
Thank you @kdy1! 🙌
