### ISSUE TITLE
Internationalization example doesn't work

### ISSUE THREAD

**Issue by emmgfx** [vercel/next.js#52987] opened 2023-07-21 08:04 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Fri Jul 21 2023 10:02:05 GMT+0200 (hora de verano de Europa central)
    Binaries:
      Node: 16.20.0
      npm: 9.4.2
      Yarn: 1.22.19
      pnpm: 8.6.3
    Relevant Packages:
      next: 13.4.11
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which example does this report relate to?

app-dir-i18n-routing

### What browser are you using? (if relevant)

Chrome 114.0.5735.198

### How are you deploying your application? (if relevant)

stackblitz

### Describe the Bug

Everything is broken, don't event launch, it only shows the error:

    TypeError: runtime.context.addEventListener is not a function

### Expected Behavior

To show the example without issues

### To Reproduce

Open the [Stackblitz](https://stackblitz.com/github/vercel/next.js/tree/canary/examples/app-dir-i18n-routing) demo.

**Comment by icyJoseph** [comment] 2023-07-21 08:44
Could you please try with Node 18.16?

**Comment by emmgfx** [comment] 2023-07-21 10:06
> 

I don't know how to change the version in Stackblitz 😔

**Comment by icyJoseph** [comment] 2023-07-21 11:24
You know what, I wonder if the problem is running middleware in Stackblitz. Let me try a couple of things.

**Comment by icyJoseph** [comment] 2023-07-21 11:27
Yeah, @emmgfx, if you rename middleware to `_middleware` on this project: https://stackblitz.com/edit/github-akrn1e?file=app%2Flayout.tsx,package.json,README.md,app%2Fpage.tsx,middleware.ts, and save, you'll see it works again

**Comment by emmgfx** [comment] 2023-07-21 11:51
But without middleware, @icyJoseph , the entire demo has no sense.

**Comment by icyJoseph** [comment] 2023-07-21 11:55
Clearly, but my point is that somehow, the Stackblitz environment has stopped being compatible with having middleware. If you were to run the project locally on your machine, I think it'll just work. I will give it a go later, but if you can test that. 

Run: `npx create-next-app --example app-dir-i18n-routing i18n-app` and check it out locally.

**Comment by emmgfx** [comment] 2023-07-21 11:57
Yes @icyJoseph you're correct, I've deployed on Vercel and it works.

**Comment by icyJoseph** [comment] 2023-07-21 12:02
Nice, but uff, I wonder what's changed to break middleware in Stackblitz... We'll need to do a binary search between canaries to see where the issue was introduced 🐌 🥱 not a very nice thing to do I must say

**Comment by balazsorban44** [comment] 2023-07-21 12:21
Thanks for digging into this @icyJoseph, I'll close this issue as it doesn't appear to be a Next.js issue. I'll ping the team at Stackblitz about this.

**Closed by balazsorban44** 2023-07-21 12:21 UTC
Labels: area: examples
