### ISSUE TITLE
Inconsistent CSS between dev and build

### ISSUE THREAD

**Issue by loteoo** [vercel/next.js#16723] opened 2020-08-31 14:21 UTC
# Bug report

## Describe the bug
When using the "Built-in CSS support", the ordering of the CSS classes (and number of times a class is declared) is not consistent between development and production.

Because of this, you can see some CSS styling "pop" around when navigating between pages.

I believe the order is correct in SSR, but not in the client-side loaded bundles (as more CSS is loaded asynchronously, the ordering is lost and duplicated styles are loaded)

## To Reproduce

Just run `next build`, the issue seems to be out-of-the-box with CSS modules?

## Expected behavior

The resulting CSS styles ordering should be identical between dev and prod.

## Screenshots

**Dev**: (Desired behaviour):
![image](https://user-images.githubusercontent.com/14101189/91729899-35869400-eb73-11ea-9220-3dd284143ab5.png)

**Build**: (Duplicated styles, inconsistent result:)
![image](https://user-images.githubusercontent.com/14101189/91730021-64046f00-eb73-11ea-8849-c6f14562a40d.png)

**Comment by timneutkens** [comment] 2020-08-31 15:51
Can you try next@canary? Many issues with CSS / ordering of CSS were solved recently.

**Comment by phildeschaine0** [comment] 2020-09-05 08:33
Can confirm, having an issue with styles not appearing in `next start` where they did appear on `next dev`.  Issue happens in `9.5.3` and in `9.5.4-canary.3` but **not** in `9.5.0`.

**Comment by Timer** [comment] 2020-09-08 13:43
OP responded with 👍 to the comment above so closing as fixed. If anyone has new reproductions, please file a new issue. Check #16630 as a duplicate first!

**Closed by Timer** 2020-09-08 13:43 UTC
Labels: kind: story

**Comment by Blagoj5** [comment] 2020-09-22 19:12
I'm having same issue with sass. I found one **workaround** here: https://medium.com/iryl/control-css-imports-order-for-next-js-webpack-based-production-applications-3b69765444fd. You import all .scss parts of your app into one main app by the order you want and everything should work fine. However my app is pretty big so i don't play to do that. I can confirm on 9.5.4-carnary.3 is not WOKRING properly

**Comment by iksent** [comment] 2020-12-15 07:15
I can confirm this bug exists at 10.0.3 also!
Reproduction is here: https://github.com/vercel/next.js/discussions/19055
Just can't use Next.js due to such annoying bug: I am using CSS Modules so can't order styles manually and only one possible fix is to add "!important", but for some projects this is a really inconvenient, for some - just impossible.

**Comment by uixcrazy** [comment] 2021-03-16 07:54
I've used next v.10.0.6, and having the same. I can't find any solutions for this.

[10148](https://github.com/vercel/next.js/issues/10148)

**Comment by MartinVandersteen** [comment] 2021-04-07 12:42
Same here, same issue with Next V.10.0.7, sass: ^1.32.8

**Comment by yenicelik** [comment] 2021-06-20 14:03
Using Next V 11.0.0 and having the same issue

**Comment by oaa97181** [comment] 2021-06-28 19:09
Saaaame
"next": "^11.0.1",
"react": "^17.0.2",

Only hotfix i found out is to throw an `!important` on every css module class that's broken.

**Comment by MartinVandersteen** [comment] 2021-07-08 08:01
@Timer Can we re-open or should we re-create a new issue ?

**Comment by timneutkens** [comment] 2021-07-08 15:41
Please open a new issue with a full reproduction.

**Comment by dotsinspace** [comment] 2021-08-30 12:16
please do something of it...all websites are looking joke to my clients.
