### ISSUE TITLE
Non-english url page loaded only for client navigation

### ISSUE THREAD

**Issue by ZiiMakc** [vercel/next.js#9804] opened 2019-12-21 16:43 UTC
**Bug report**

Non-english urls like this:

> `http://localhost/чит`

That get converted in get request to:

> `http://localhost/%D1%87%D0%B8%D1%82`

Works only using client-side navigation for pages structure:

> `/pages/чит`

**Example**

If you push reload button to update from server, you will get not found error.

[Codesandbox example](https://codesandbox.io/s/adoring-swirles-4fsg5).

---

I was able to resolve it using new rewrites in next.config, but it don't feels right:
```
 experimental: {
    async rewrites() {
      return [{ source: encodeURI('/чит'), destination: '/чит' }] //NOT WORKING ANYMORE
    }
  }
```
```
{ source: '/:rest*', destination: '/:rest*' } // or even this, without encodeURI. NOT WORKING ANYMORE
```

**Comment by kachkaev** [comment] 2019-12-21 23:47
This looks like an expected behaviour to me – character encoding is probably the responsibility of developers.

Next.js could assist here though. For example, it could autoconvert url arguments in dev and show a meaningful message if `providedValue !== encodeURI(providedValue)` 🤔

**Comment by ReTWi** [comment] 2019-12-22 10:46
@kachkaev i think that it should work out of the box for any language. I'm noe an expert, but it can be fixed with filename encoding, or request url decoding by default.

**Comment by Timer** [comment] 2020-09-10 18:23
Closing as stale, we made a lot of improvements to this logic recently. Please let us know if this still reproduces and we'd be happy to take a look.

**Closed by Timer** 2020-09-10 18:23 UTC

**Comment by balazsorban44** [comment] 2022-01-29 13:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
