### ISSUE TITLE
Incorrect query object in next/router when navigating a page with next/link

### ISSUE THREAD

**Issue by rokinsky** [vercel/next.js#15995] opened 2020-08-08 07:50 UTC
# Bug report

## Describe the bug

I'm trying to use `next/link` to refer to a dynamic route with query params. I cannot access query params in `next/router` after the transition. Direct navigation to the page with query params works fine.

## To Reproduce

Repository: [next.js-bug-query-link](https://github.com/rokinsky/next.js-bug-query-link)

1. Go to [http://localhost:3000](http://localhost:3000)
2. Click on any link
3. See `router.query` object: 
```json 
{
  "locale": "en-gb"
}
```
4. Reload the page or navigate directly to [http://localhost:3000/en-gb?q=hello-world](http://localhost:3000/en-gb?q=hello-world)
5. See `router.query` object:
```json
{
  "q": "hello-world",
  "locale": "en-gb"
}
```

## Expected behavior

I would like to have in both cases
```json
{
  "q": "hello-world",
  "locale": "en-gb"
}
```

## Screenshots

N/a

## System information

- OS: macOS
- Browser (if applies): chrome
- Version of Next.js: 9.5.1
- Version of Node.js: 14.2.0

## Additional context

N/a

**Comment by Janpot** [comment] 2020-08-08 12:00
`as` must include the query as well

**Comment by rokinsky** [comment] 2020-08-08 12:12
@Janpot this is super weird api, don't you think so? Is it possible to add handling of such cases under the hood to the framework?

**Comment by Janpot** [comment] 2020-08-08 12:19
I agree, You can follow https://github.com/vercel/next.js/issues/8207. Will close this issue as a duplicate.

**Closed by Janpot** 2020-08-08 12:19 UTC

**Comment by balazsorban44** [comment] 2022-01-29 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
