### ISSUE TITLE
Middleware x Rewriting url without locale prefix returns 404

### ISSUE THREAD

**Issue by youminkim** [vercel/next.js#32991] opened 2022-01-04 17:41 UTC
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

v14.15.4

### What browser are you using?

chrome

### What operating system are you using?

macOS

### How are you deploying your application?

vercel

### Describe the Bug

While rewriting subdomain in middleware, page is not loaded based on locale prefix. 

```
import { NextResponse } from 'next/server';

export function middleware(req, ev) {
    ...

    // rewrite
    if (
        !pathname.includes('.') && // exclude all files in the public folder
        !pathname.startsWith('/api') // exclude all API routes
    ) {
        return NextResponse.rewrite(`/a/${subdomain}`); // return 404 not found
    }

    return response;
}

```

I tried `return NextResponse.rewrite("/en/a/support")` instead. In this case, the first hit returns white screen. second hit returns proper page.

Note that `/a/support` page use `getStaticProps` and `getStaticPaths` with `fallback=true`.

Sharing next.config.js
```
const moduleExports = {
    ...
    i18n: {
        locales: ['en', 'id', 'es'],
        defaultLocale: 'en'
    }
    ...
}
```

### Expected Behavior

return NextResponse.rewrite(`/en/a/${subdomain}`) should work 

### To Reproduce

`i18n` setting in next.config.js

prepare ISR page 

In middleware, rewrite without locale preifx. e.g. `return NextResponse.rewrite(`/a/abc`)`

**Comment by balazsorban44** [comment] 2022-01-05 02:12
This might have already been fixed in #31174. Could you verify by using `npm i next@canary`

**Comment by youminkim** [comment] 2022-01-05 07:20
Thanks @balazsorban44
it works well after upgrading

**Closed** 2022-01-05 11:49 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-02-04 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
