### ISSUE TITLE
Rendering an error, doesnt have correct http codes

### ISSUE THREAD

**Issue by maraisr** [vercel/next.js#15142] opened 2020-07-14 03:28 UTC
# Bug report

## To Reproduce

1. Clone the repo https://github.com/maraisr/nextjs-repro-repo
2. run `yarn`
3. run `yarn next dev`
4. inspect DevTools, and notice the document is 200 and not **404**

The same happens under a build/start.

## Expected behavior

Have the response be 404.

## System information

- OS: Windows
- Browser: Firefox
- Version of Next: 9.4.4
- Version of Node.js: 14.0.0

## Additional context

Followed: https://nextjs.org/docs/advanced-features/custom-error-page#customizing-the-error-page

**Comment by jamesmosier** [comment] 2020-07-14 14:19
Hi @maraisr. Running the application via `yarn dev` or `yarn build` and `yarn start` I was able to see a 404 status code in my network tab. 

![Screen Shot 2020-07-14 at 10 17 15 AM](https://user-images.githubusercontent.com/2854919/87436604-4414ee00-c5bb-11ea-8a8c-43f912191533.png)

**Comment by timneutkens** [comment] 2020-07-14 15:30
https://github.com/maraisr/nextjs-repro-repo/blob/main/pages/index.js#L11

The `Error` component is just a React component that renders something based on properties. It does not have any magic behavior.

We're planning to add something that allows for returning "this is a 404" to getStaticProps/getServerSideProps though which should cover your use case.

**Comment by Timer** [comment] 2020-08-05 17:00
Closing in favor of above two issues.

**Closed by Timer** 2020-08-05 17:00 UTC
Labels: kind: story

**Comment by balazsorban44** [comment] 2022-01-29 18:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
