### ISSUE TITLE
Telemetry needs to be disabled without voodoo

### ISSUE THREAD

**Issue by Paratron** [vercel/next.js#10713] opened 2020-02-27 00:17 UTC
# Bug report
We do not want to have telemetry enabled when performing a next build inside a docker container in our build pipeline. It seems like the npx command described in the documentation does not work here. Also its very opaque _what_ that command actually does and where the information that no telemetry is desired is actually stored.

It should be possible to disable telemetry by passing a flag to `npm run build` instead of executing a npx command beforehand.

## Describe the bug

Inside our dockerfile, we try to disable telemetry, then performing the build:

```
...
# We do not want to be tracked
RUN npx next telemetry disable

# Building app
RUN npm run build
...
```

According to our pipeline logs, telemetry seems to be re-enabled when the actual build is performed:

```
Step 13/25 : RUN npx next telemetry disable
 ---> Running in 3cee707075fa
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

Your preference has been saved.

Status: Disabled

You have opted-out of Next.js' anonymous telemetry program.
No data will be collected from your machine.
Learn more: https://nextjs.org/telemetry

Removing intermediate container 3cee707075fa
 ---> f765f98e92b1
Step 14/25 : RUN npm run build
 ---> Running in 0c0c4f9963b2

> stroeer-finance@1.0.0 build /app
> cross-env NODE_ICU_DATA=node_modules/full-icu next build

Creating an optimized production build...
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry
```

## To Reproduce

Try disabling telemetry and then build inside a docker container.

## Expected behavior

I expected telemetry to be disabled.

## System information

- Docker with node:12-alpine
- Gitlab CI
- nextJS 6.13.4

**Comment by Paratron** [comment] 2020-02-27 00:17
Also related to this issue is my comment from another issue:

https://github.com/zeit/next.js/issues/8851#issuecomment-591710955

**Comment by Janpot** [comment] 2020-02-27 09:33
Not sure if helpful, but according to [the doc](https://nextjs.org/telemetry):
> You may also opt-out by setting an environment variable: `NEXT_TELEMETRY_DISABLED=1`.

**Comment by timneutkens** [comment] 2020-02-27 09:49
You can add the environment variable `NEXT_TELEMETRY_DISABLED=1` as per the documentation.

The command writes a file into the home directory, I guess in docker that's not preserved in between steps 🤔

**Comment by rafaelalmeidatk** [comment] 2020-02-27 14:21
Try to add the env var in your Dockerfile: `ENV NEXT_TELEMETRY_DISABLED 1`

**Comment by Timer** [comment] 2020-09-10 18:20
Closing this as the `npx next telemetry disable` command is to disable collection system-wide, meaning for all Next.js projects a user works on.
Viewing your docker logs, you are throwing away the intermediate container which is why the setting is being lost.

---

To disable this in your Dockerfile, you can add the following line for each of your build stages:

```Dockerfile
ENV NEXT_TELEMETRY_DISABLED 1
```

**Closed by Timer** 2020-09-10 18:20 UTC

**Comment by kolpav** [comment] 2021-01-26 18:02
@Timer I want to be able to push this option to my repo and never worry about it again. Setting ENVs for every build stage or running special commands post every clean install is kind of nuts and I can't help to think it was done intentionally this way.
Are you/vercel actively going to fight against making it part of `next.config.js` so we know if we should bother with PR. Its not so far fetched to think it would need to be approved somewhere higher on your corporate ladder as it would make opting out a little bit too easy and more importantly permanent that would surely bring some of you internal metrics down which is always touchy subject.

**Comment by balibebas** [comment] 2021-02-04 12:08
@kolpav we need to keep dumping on them until they figure out they need to disable telemetry by default. @Timer @rafaelalmeidatk could one of you please reopen this because "without voodoo" really means "by default". we're developers please treat us with respect.

**Comment by balibebas** [comment] 2021-02-04 12:10
@kolpav we need to keep dumping on them until they figure out they need to disable telemetry by default. @Timer @rafaelalmeidatk could one of you please reopen this because "without voodoo" really means "by default".

telemetry in a build pipeline is like MIDI on the web. no one wants to hear it so please just turn it off.

**Comment by balibebas** [comment] 2021-02-04 12:12
```
❯ npx next telemetry disable
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-darwin-x64.tar.br
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
The module 'react' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install react'
The module 'react-dom' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install react-dom'
Cannot find module 'react'
Require stack:
- /Users/jos/.npm/_npx/71445/lib/node_modules/next/dist/bin/next
```

oof you guys... oof ><

**Comment by balibebas** [comment] 2021-03-17 07:20
Here's some more voodoo for you. Next [maintainers delete issues](https://github.com/vercel/next.js/issues/21866) requesting to disable telemetry by default. That way no one can read and respond to my rationalle and they can just keep on usurping data that's wildly difficult to disable. If anyone's interested in maintaining a fork with me to stay in line-with master but strip out the telemetry please [ping me](https://habd.as/contact).

<img width="816" alt="Screen Shot 2021-03-17 at 3 17 53 PM" src="https://user-images.githubusercontent.com/65664227/111429509-0c56db00-8734-11eb-907f-5c695d23e7d6.png">

**Comment by Paratron** [comment] 2021-03-17 07:32
That wont help anything tough. The problem is that when I don't know about the telemetry, I neither will disable it nor use the fork without telemetry.

And WHEN I know about it, I just disable it. The fork would not help but cause different problems.

**Comment by balibebas** [comment] 2021-03-17 07:48
> The problem is that when I don't know about the telemetry, I neither will disable it nor use the fork without telemetry.

The telemetry is advertised in pretty much every build pipeline. If someone doesn't know about it, they don't understand their tool well enough. As for causing other problems, that's precisely my intention.

**Comment by kolpav** [comment] 2021-03-18 15:10
Well, I guess I got an answer to my question.

**Comment by VojtechVitek** [comment] 2021-03-19 16:43
`ENV NEXT_TELEMETRY_DISABLED 1` doesn't work.

**Comment by opiation** [comment] 2021-11-15 20:17
I requested the _feature_ of disabling telemetry via a version-controllable `next.config.json` in #31360 which was closed shortly thereafter and moved to discussion https://github.com/vercel/next.js/discussions/31400. Sharing this in case interested parties in this thread want voice their concerns there or upvote.

**Comment by balazsorban44** [comment] 2022-01-27 09:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
