### ISSUE TITLE
Getting Flash of Unstyled Text in production mode

### ISSUE THREAD

**Issue by gauravkrp** [vercel/next.js#13238] opened 2020-05-22 16:42 UTC
# Bug report
I'm getting Flash of Unstyled Text in production mode on my website - https://accessgatelabs.com

## Describe the bug
When the website is first loaded in a browser, unstyled content flashes and then css loads. In my case you can see that header menu appears for a while when the website is first browsed.

## To Reproduce
- Using Next.js 9.4.2
- Utilizing integrated SASS options
- index.scss is imported in _app.js
- production mode using next build and node server.js (server.js is for extra code of trailing slashes only)
- Browser tested - Chrome 83

## Expected behavior
No FOUT should happen.

## Screenshots
![image](https://user-images.githubusercontent.com/12250556/82689970-fba31900-9c78-11ea-87c5-f222dfbca525.png)

**Comment by joe-bell** [comment] 2020-05-25 08:05
Hey @gauravkrp, I thought this might be a dupe of my ticket where I'm having the same issue (#12984) but I think you can actually fix this with a small change in your CSS

In your preview link I can see the following styles:
```suggestion
@font-face {
 font-family:RNS Sanz;
 font-display:auto;
 font-style:normal;
 font-weight:300;
 src:url(/assets/fonts/sanz/RNSSanz-Light.woff2) format("woff2")
}
@font-face {
 font-family:RNS Sanz;
 font-display:auto;
 font-style:normal;
 font-weight:400;
 src:url(/assets/fonts/sanz/RNSSanz-Normal.woff2) format("woff2")
}
@font-face {
 font-family:RNS Sanz;
 font-display:auto;
 font-style:normal;
 font-weight:500;
 src:url(/assets/fonts/sanz/RNSSanz-Medium.woff2) format("woff2")
}
@font-face {
 font-family:RNS Sanz;
 font-display:auto;
 font-style:normal;
 font-weight:600;
 src:url(/assets/fonts/sanz/RNSSanz-SemiBold.woff2) format("woff2")
}
@font-face {
 font-family:RNS Sanz;
 font-display:auto;
 font-style:normal;
 font-weight:700;
 src:url(/assets/fonts/sanz/RNSSanz-Bold.woff2) format("woff2")
}
@font-face {
 font-family:RNS Sanz;
 font-display:auto;
 -font-style:normal;
 font-weight:800;
 src:url(/assets/fonts/sanz/RNSSanz-ExtraBold.woff2) format("woff2")
}
@font-face {
 font-family:RNS Sanz;
 font-display:auto;
 font-style:normal;
 font-weight:900;
 src:url(/assets/fonts/sanz/RNSSanz-Black.woff2) format("woff2")
}
```

**Comment by gauravkrp** [comment] 2020-05-25 09:00
> Hey @gauravkrp, I thought this might be a dupe of my ticket where I'm having the same issue (#12984) but I'm pretty confident this is not a Next.js issue and something you can actually fix with a small change to your CSS
> 
> In your preview link I can see the following styles:
> 
> ```css
> @font-face {
>  font-family:RNS Sanz;
>  font-display:auto;
>  font-style:normal;
>  font-weight:300;
>  src:url(/assets/fonts/sanz/RNSSanz-Light.woff2) format("woff2")
> }
> @font-face {
>  font-family:RNS Sanz;
>  font-display:auto;
>  font-style:normal;
>  font-weight:400;
>  src:url(/assets/fonts/sanz/RNSSanz-Normal.woff2) format("woff2")
> }
> @font-face {
>  font-family:RNS Sanz;
>  font-display:auto;
>  font-style:normal;
>  font-weight:500;
>  src:url(/assets/fonts/sanz/RNSSanz-Medium.woff2) format("woff2")
> }
> @font-face {
>  font-family:RNS Sanz;
>  font-display:auto;
>  font-style:normal;
>  font-weight:600;
>  src:url(/assets/fonts/sanz/RNSSanz-SemiBold.woff2) format("woff2")
> }
> @font-face {
>  font-family:RNS Sanz;
>  font-display:auto;
>  font-style:normal;
>  font-weight:700;
>  src:url(/assets/fonts/sanz/RNSSanz-Bold.woff2) format("woff2")
> }
> @font-face {
>  font-family:RNS Sanz;
>  font-display:auto;
>  font-style:normal;
>  font-weight:800;
>  src:url(/assets/fonts/sanz/RNSSanz-ExtraBold.woff2) format("woff2")
> }
> @font-face {
>  font-family:RNS Sanz;
>  font-display:auto;
>  font-style:normal;
>  font-weight:900;
>  src:url(/assets/fonts/sanz/RNSSanz-Black.woff2) format("woff2")
> }
> ```
> 
> To resolve this issue, you need to replace each `font-display` property to:
> 
> ```css
>  font-display: swap;
> ```
> 
> Some more info on that here:
> https://css-tricks.com/almanac/properties/f/font-display/

Hey @joe-bell , it is not just the fonts but other css properties should also render after the html.
IF you can have a look at my site - https://accessgatelabs.com you will see that menu image appears for few ms. Menu Images have css of {opacity: 0; visibility: hidden}

**Comment by joe-bell** [comment] 2020-05-25 11:11
Unfortunately I can't reproduce that, but I'm confident if you change your font properties this will make a big difference.

**Comment by timneutkens** [comment] 2020-05-25 12:05
Please add a complete reproduction including a repository so that it can be investigated properly. Thanks 🙏

**Comment by gauravkrp** [comment] 2020-05-27 19:16
> Please add a complete reproduction including a repository so that it can be investigated properly. Thanks 🙏

Hi @timneutkens , I've done a complete reproduction repo here_
https://github.com/gauravkrp/test

I've used the code from my original project and created a minimum working repo.
deployed using vercel - https://test-klaky5btz.now.sh

**Comment by balibebas** [comment] 2020-08-31 11:25
This is not a NextJS issue and should be closed along with https://github.com/vercel/next.js/issues/13238. As @joe-bell mentions you can use the `font-display` rule to combat the FOUT. This issue is as old as web fonts themselves. Check out Paul Irish's website if you want to research the history.

**Closed** 2020-08-31 18:44 UTC
Labels: please add a complete reproduction

**Comment by praveen7557** [comment] 2020-11-10 10:45
@gauravkrp Did you find a solution for this?

**Comment by gauravkrp** [comment] 2020-11-12 04:11
> @gauravkrp Did you find a solution for this?

Hey praveen! I didn't find an exact solution but a better way to deal the issue.
I put all the render blocking css into the head tag.
But Remember this is not the ideal solution as for the header/nav components' css you don't need to put them in head, only the viewport's css should be there.
