### ISSUE TITLE
Render a low-resolution placeholder image as the default for the next/image component

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [vercel/next.js#18785] opened 2020-11-04 12:19 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Sort of related to the bug reported here: #18727. It seems `next/image` is currently loading the largest resolution for the placeholder image when the image is out of the viewport. This is not optimal for performance.

## Describe the solution you'd like

The `next/image` component should accept a configuration specifying a low-resolution size (e.g., `32`) to use as the default placeholder size before the image intersects with the browser viewport.

As an example, this is what I do on my [current website](https://www.aleksandrhovhannisyan.com/) (created w/ Jekyll). With a 32x32 placeholder for my profile photo, for example, I only use 1-3 KB of data before the intersection, whereas Next's current approach is loading the WebP version at the largest resolution and consuming 15 KB. That's a huge difference for image-intensive pages.

![image](https://user-images.githubusercontent.com/19352442/98110913-d80e0c80-1e6d-11eb-8f85-e8d2c3b13b32.png)

## Describe alternatives you've considered

N/A

**Comment by pedroapfilho** [comment] 2020-11-04 14:17
There is an implementation of it here: https://github.com/joe-bell/next-placeholder

We could use `blurhash` to make it work properly, and give it as a prop (and make it the default behavior, maybe?.

**Comment by lachlanjc** [comment] 2020-11-18 00:42
Looks like #18858 is tracking this same request & has some more details

**Comment by timneutkens** [comment] 2020-11-18 11:50
Yep, closing in favor of #18858

**Closed by timneutkens** 2020-11-18 11:50 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-29 03:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
