### ISSUE TITLE
Dynamic routing doesn't works with internationnalized routes

### ISSUE THREAD

**Issue by Hargoze** [vercel/next.js#19753] opened 2020-12-02 16:42 UTC
# Bug report

## Describe the bug

Dynamic routing doesn't works with internationnalized routes

## To Reproduce

the problem happen when you use a dynamic route like [slug].js with a next 10.0.X internationalized route
the default language works : /en/blog/blog1 or /blog/blog1 works but /fr/blog/blog1 doesn't  

here is a sandbox : https://codesandbox.io/s/hopeful-lalande-bijk4?file=/pages/index.js

## Expected behavior

/fr/blog/blog1 should work, in fact on our similar example, it worked in localhost but not once online (deployed in vercel)

## Screenshots

![image](https://user-images.githubusercontent.com/60386882/100898792-6b644d00-34c1-11eb-887a-7459b6bd4bd6.png)

**Comment by ijjk** [comment] 2020-12-02 20:47
Hi, it looks like you aren't returning paths for the non-default locale in `getStaticPaths`. If a locale isn't provided for a path from `getStaticPaths` the default locale is used. See more info on this [in the docs](https://nextjs.org/docs/advanced-features/i18n-routing#dynamic-getstaticprops-pages). 

I'm going to close this since it doesn't appear to be a bug and is documented already, feel free to reply with additional info if you are still encountering trouble with this!

**Closed by ijjk** 2020-12-02 20:47 UTC
Labels: template: bug

**Comment by Hargoze** [comment] 2020-12-04 13:43
thanks for your help @ijjk, However in our case, we read md files in blog/[slug].js, it works on local but when deployed to vercel, we can't read md files in french but in english (the default language) it works even with the same path,
do you any idea why it happen ? and how to fix this ?

**Comment by ijjk** [comment] 2020-12-04 15:15
@Hargoze when reading files you need to use `proces.cwd()` for the files to be detected properly. See more on this [in the docs here](https://nextjs.org/docs/basic-features/data-fetching#reading-files-use-processcwd)

**Comment by Hargoze** [comment] 2020-12-08 09:49
i will take a look, thanks

**Comment by Bexy-Lyn** [comment] 2021-06-02 08:08
Hey everyone. It appears, that I have a similar issue with the difference of using ```getServerSideProps``` not ```getStaticProps```. Therefore ```getStaticPaths``` wont work with that, am I right? Is there an alternative for SSR or do I need to change my data fetching to Static Generation?
Thanks!

**Comment by balazsorban44** [comment] 2022-01-28 07:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
