### ISSUE TITLE
Cookies set in middleware are not available in App Server Components on first load.

### ISSUE THREAD

**Issue by Angusross111** [vercel/next.js#44041] opened 2022-12-14 22:10 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #202210290932~1669062050~22.04~d94609a SMP PREEMPT_DYNAMIC Mon N
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.7-canary.6
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/Angusross111/reproduction-app-middleware-cookies

### To Reproduce

https://reproduction-app-middleware-cookies.vercel.app/

1. On every path middleware checks if `vercel-cookie` cookie exists. if not it sets the cookie with a 30s max age on the response and returns.
2. In `app/layout.tsx` it check for the `vercel-cookie` cookie and if not found call the `notFound()` function.
3. If you refresh within 30 seconds the page loads as expected as the Cookie is found in `app/layout.tsx`

### Describe the Bug

Cookies set  in the Middleware are not available in any of the `app/*` files on first load. 

### Expected Behavior

My understanding is Middleware runs on every request, so if a cookie is set there, it should be available before it gets to the Server Components. Is the `NextRequest` object the Middleware receives the same one that the Server Component will see? Am I able to set the cookie on the Request instead?

### Which browser are you using? (if relevant)

Chrome 108.0.5359.98

### How are you deploying your application? (if relevant)

Vercel

**Comment by Angusross111** [comment] 2022-12-14 22:52
As is always the case when setting up a reproduction, I manage to find a solution after the fact. 
https://reproduction-app-middleware-cookies-h1fb6mfbj.vercel.app/

https://github.com/Angusross111/reproduction-app-middleware-cookies/commit/9e57b3bdc33379b3f8157c774ef3a063d7576ebb

https://nextjs.org/docs/advanced-features/middleware#setting-headers

I solved it by setting a header on the request as well as the cookie on the response, and then checking for both on the Server component. 

```
    const vercelCookie =
        cookies().get("vercel-cookie")?.value || headers().get("vercel-cookie");
```

If the cookie has not expired in the Browser, then the server component can see it. otherwise the middleware will refresh the cookie, plus pass down the access token to the Server component in the request as a header, while also setting the new cookie on the browser.

I assume its because setting a Cookie requires the special Set-Cookie header, so the cookie doesnt actually exist until it hits the Browser and creates it.

**Comment by zeckdude** [comment] 2023-01-19 10:12
If anyone comes across this thread, I found a great workaround here: https://github.com/vercel/next.js/discussions/38650#discussioncomment-3148772

**Comment by JanKaifer** [comment] 2023-01-19 13:48
https://knowyourmeme.com/memes/obama-awards-obama-a-medal
[
![Screenshot from 2023-01-19 14-47-48](https://user-images.githubusercontent.com/12820484/213459081-ced40a92-da24-4ee1-a907-3338bd379287.png)
](url)

Anyway, closing this as a duplicate of that thread.

**Closed by JanKaifer** 2023-01-19 13:48 UTC
Labels: template: bug
