### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by SalahAdDin** [vercel/next.js#14849] opened 2020-07-04 16:21 UTC
# Bug report
I'm following the [CMS Strapi Example](https://github.com/vercel/next.js/tree/canary/examples/cms-strapi) but adapting it to my needs, it involves to use `page` folder instead of `post`, for instance.

Each time I want to see any page by slug I get the next error and it sends me to the `404`:
```
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Debugger attached.
Debugger attached.
Debugger attached.
Debugger attached.
event - compiled successfully
event - build page: /page/[slug]
wait  - compiling...
event - compiled successfully
Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `Layout`, expected `array`.
    in Layout (at [slug].js:35)
    in Page (at _app.js:28)
    in Fragment
    in App
    in Unknown
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in AppContainer
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:533:11)
    at DevServer.sendHTML (/home/joselito92/Proyectos/Work/portfolio/frontend/node_modules/next/dist/server/next-dev-server.js:23:5)
    at DevServer.render (/home/joselito92/Proyectos/Work/portfolio/frontend/node_modules/next/dist/next-server/server/next-server.js:49:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.fn (/home/joselito92/Proyectos/Work/portfolio/frontend/node_modules/next/dist/next-server/server/next-server.js:35:852)
    at async Router.execute (/home/joselito92/Proyectos/Work/portfolio/frontend/node_modules/next/dist/next-server/server/router.js:28:28)
    at async DevServer.run (/home/joselito92/Proyectos/Work/portfolio/frontend/node_modules/next/dist/next-server/server/next-server.js:44:494)
    at async DevServer.handleRequest (/home/joselito92/Proyectos/Work/portfolio/frontend/node_modules/next/dist/next-server/server/next-server.js:13:133) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

## To Reproduce

1. Run dev.
2. Go to `/page/education`

## Expected behavior

It should render the expected page.

## System information

- OS: Linux
- Browser Chrome
- Version of Next.js: 9.4
- Version of Node.js: 14

## Additional context
You can get the full code [here](https://github.com/SalahAdDin/frontend/tree/develop). 

I also want to say it could be great if you make a very deep blog explaining the example, because alas i don't get so much here, maybe that's why i cannot understand what is going on with this bug.

**Comment by timneutkens** [comment] 2020-07-04 16:54
Duplicate of #14846

**Closed by timneutkens** 2020-07-04 16:54 UTC

**Comment by balazsorban44** [comment] 2022-01-29 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
