### ISSUE TITLE
npm run build error on AzureDevops

### ISSUE THREAD

**Issue by ngochieuvnu** [vercel/next.js#10410] opened 2020-02-04 03:45 UTC
# Bug report
npm run build error on AzureDevops but work fine in local
## Describe the bug

When commit code and run pipeline in AzureDevops i get the following error

> next build
Creating an optimized production build ...
> Build error occurred
ReferenceError: Element is not defined
    at D:\a\1\s\node_modules\wicg-inert\dist\inert.js:24:17
    at D:\a\1\s\node_modules\wicg-inert\dist\inert.js:2:66
    at Object.<anonymous> (D:\a\1\s\node_modules\wicg-inert\dist\inert.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\a\1\s\node_modules\nuka-carousel\lib\index.js:28:1)`

I don't use moduels "wicg-inert" in project, and there are no changes in file "package.json"
I had not encountered this error before

![azuredevops](https://user-images.githubusercontent.com/45206653/73712006-556beb80-473b-11ea-8be6-6c7369f8e5dd.PNG)

## System information

- OS: Azure Devops
- Version of Next.js: 8.1.0

**Comment by tamir61** [comment] 2020-02-04 10:33
happend to me also, i found a problem with library called nuka-carousel.
you can read about it here
https://github.com/FormidableLabs/nuka-carousel/issues/658

**Comment by ngochieuvnu** [comment] 2020-02-04 10:44
> happend to me also, i found a problem with library called nuka-carousel.
> you can read about it here
> [FormidableLabs/nuka-carousel#658](https://github.com/FormidableLabs/nuka-carousel/issues/658)

thanks for reply,
but i still can build success in local, error only appear in Azure Devops

**Comment by timneutkens** [comment] 2020-02-04 12:52
This issue is not actionable so I'm not sure what to do with it.

**Comment by Timer** [comment] 2020-09-03 02:27
Closing as no reproduction provided.

**Closed by Timer** 2020-09-03 02:27 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
