### ISSUE TITLE
Runtime Edge throws an "Invariant: Method expects to have requestAsyncStorage, none available"

### ISSUE THREAD

**Issue by NastykSwED** [vercel/next.js#52176] opened 2023-07-04 07:47 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.8
      eslint-config-next: 13.4.8
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/NastykSwED/next-edge-invariant-error

### To Reproduce

1. pnpm install
2. pnpm dev
3. Go to [localhost:3000](http://localhost:3000/)

4. Look at terminal, see error:
```
error Error: Invariant: Method expects to have requestAsyncStorage, none available
    at RootLayout (./src/app/layout.tsx:23:71)
    at stringify (<anonymous>)
digest: "3964514174"
```

### Describe the Bug

When using the runtime edge, if we use the `headers()` functions from "`import { headers } from 'next/headers'`", this error occurs, not only in `layout.tsx | jsx `files but also in `page.tsx | jsx` files and in` generateMetadata` functions. The error does not occur in older versions such as `next@13.4.7`:
layout.tsx file
![Screenshot_1](https://github.com/vercel/next.js/assets/102027097/4ea2cb94-14b5-4d88-adfe-1f887668a5ff)

page.tsx file
![Screenshot_2](https://github.com/vercel/next.js/assets/102027097/b6104146-4967-4dcc-a708-afb910acf343)

generateMetadata function 
![Screenshot_3](https://github.com/vercel/next.js/assets/102027097/f41ceeab-7c5a-4a45-b571-5b7e71598203)

### Expected Behavior

It would be expected that when using the runtime edge this error would not occur. In earlier versions such as next@13.4.7 it works correctly.

### Which browser are you using? (if relevant)

Microsoft Edge 114.0.1823.67

**Comment by HotCustard** [comment] 2023-07-04 08:27
Same deal with cookies()
I noticed that when deployed to Vercel it runs fine, it only appears to be an issue on localhost.

**Comment by balazsorban44** [comment] 2023-07-05 13:54
@HotCustard do you have a reproduction? I tried running the one in the description, but I could not reproduce this. :thinking:

**Comment by balazsorban44** [comment] 2023-07-05 13:56
@NastykSwED the screenshots look different from the linked reproduction (`page.tsx`) could you update it so it is the same code?

**Comment by NastykSwED** [comment] 2023-07-05 14:08
@balazsorban44 Fixed!

**Comment by walljalen** [comment] 2023-07-06 19:46
Is there a solution for this issue? I'm on Windows as well.

**Comment by BenBab** [comment] 2023-07-07 01:05
I am getting the same issue 'Invariant: Method expects to have requestAsyncStorage, none available' When using headers().
Happening in next 13.4.8 and 13.4.9

**Comment by StockBet** [comment] 2023-07-07 17:10
Having the same issue. using cookies for supabase on server side api to receive a webhook.

`import { cookies } from 'next/headers'`
`const supabase = createServerActionClient({ cookies })`

Getting this error when deployed on vercel `Error: Invariant: Method expects to have requestAsyncStorage, none available`

**Comment by joulev** [comment] 2023-07-10 07:10
@balazsorban44 The error can be reproduced by using `cookies` in middleware

```ts
import { cookies } from "next/headers";

export function middleware() {
  cookies();
}
```

<details>
<summary><code>next info</code> output (macOS)</summary>

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:21:34 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8112
    Binaries:
      Node: 20.3.1
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: 8.6.5
    Relevant Packages:
      next: 13.4.10-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A

</details>

<details>
<summary><code>next info</code> output (Linux)</summary>

    Operating System:
      Platform: linux
      Arch: x64
      Version: #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.6
    Relevant Packages:
      next: 13.4.10-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A

</details>

Using `cookies()` in `page.tsx` files with `runtime = "edge"` works fine in both places in my case. So I think a significant portion of the reports on this issue is due to users using `cookies()` inside the middleware file ([a user is also similarly confused in the Next.js Discord server](https://nextjs-forum.com/post/1127548774932287509)).

If `cookies()` is not supposed to work in middleware I think it's necessary to provide a clearer error message than an invariant error like this one.

For other people encountering this issue with using `cookies()` in edge runtime *page files* (not middleware), maybe try to reproduce it in macOS or Linux, and see if it's still there? I don't have a Windows machine to test with me.

**Comment by alrightsure** [comment] 2023-07-11 16:05
I'm getting this same issue now even on 13.4.7, but only when deployed. It works fine locally.

**Comment by aabassiouni** [comment] 2023-07-12 23:56
I had this issue trying to run Clerk Auth on edge on the newest version (13.4.9). It seems to be only in windows environments. I tested the repo in WSL2 and I stopped getting the error. Windows will only work up til 13.4.7.

**Comment by BenBab** [comment] 2023-07-13 01:13
> I had this issue trying to run Clerk Auth on edge on the newest version (13.4.9). It seems to be only in windows environments. I tested the repo in WSL2 and I stopped getting the error. Windows will only work up til 13.4.7.

Yeah I was also having issues with both clerk Auth and also getting the Invariant: Method expects to have requestAsyncStorage when using headers() on a server components or middleware. 

It only happens on my windows environment though. 

Using wsl2 in dev it works okay on version 13.4.9

**Comment by alexeygorbachevskiy** [comment] 2023-07-13 07:29
Version 13.4.9, have same issue only locally (Windows), evrth is okay when deployed.

![image](https://github.com/vercel/next.js/assets/37103509/2203d14d-2135-4698-a2c8-b521a9248206)

**Comment by NastykSwED** [comment] 2023-07-21 10:26
The error still occurs in the latest version of next@13.4.11 on Windows OS.

**Comment by AirmanEpic** [comment] 2023-07-26 06:04
Reproduced on 13.4.12

**Comment by emrecoban** [comment] 2023-07-27 09:41
### I have the same issue with Supabase. It's very important bug! My app is down because of that. Really stuck.

#### The issue:
In prod, Next.js throws that error message: `Invariant: Method expects to have requestAsyncStorage, none available`. This error message occurs only server components and also in prod (Deploy on Cloudflare). No issue in local.

**When it throws the error:**

When it was fetching data from Supabase database in the server components in prod, not local.

**Dependencies:**
```json
"@supabase/auth-helpers-nextjs": "^0.7.3",
"@supabase/supabase-js": "^2.31.0",
"next": "13.4.12",
```

**`next-info`:**
```bash
    Operating System:
      Platform: linux
      Arch: x64
      Version: #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.7
    Relevant packages:
      next: 13.3.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

**Dashboard component:**
```javascript
import { createServerSupabaseClient, getSession } from "@/components/supabase/supabase-server";

export default async function Dashboard() {
    const supabase = createServerSupabaseClient() // this line works well.
    const serverSession = await getSession() // this line works well.
    const userInfo = serverSession?.user

    const pending = await supabase
        .from('table')
        .select('*', { count: 'exact', head: true })
        .eq('username', userInfo.user_metadata.username)
        .eq('status', 0)

    // Here's the error:
    console.log("ERROR [PENDING] DETAILS: ", JSON.stringify(pending, null, 2))
}
```

**supabase-server.js:**
```javascript
import { cookies } from 'next/headers';
import { cache } from 'react';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';

export const createServerSupabaseClient = cache(() =>
    createServerComponentClient({ cookies })
)

export async function getSession() {
    const supabase = createServerSupabaseClient()
    try {
        const {
            data: { session }
        } = await supabase.auth.getSession()
        return session
    } catch (error) {
        console.error('Error:', error)
        return null
    }
}
```

#### Additional:
I guess the problem comes from the `next/headers` package. But why is it working in local? Everything is perfect in the client components, also in local. I don't want to do prop drilling.

A comment about this issue from GitHub: https://github.com/vercel/next.js/issues/45371#issuecomment-1652192961

- Used `server-only` package
- Removed the `cache()` from `react`
- Run `createServerComponentClient` directly in the Dashboard component, not imported

**Comment by NastykSwED** [comment] 2023-08-07 08:52
The error still occurs in version 13.4.13

**Comment by Enalmada** [comment] 2023-08-08 18:38
Issue remains in version 13.4.14-canary.1.  It is a windows only bug.  It works fine in WSL.  

reproduction:
```
import { cookies } from "next/headers";

export const runtime = "edge";

export default function Page() {
  const cookieStore = cookies();
  return null;
}
```

<img width="723" alt="image" src="https://github.com/vercel/next.js/assets/1892132/af5ed9c9-c861-4711-bfd5-4cac51bca03e">

reproduction where I am actually trying to get this to work: https://github.com/awinogrodzki/next-firebase-auth-edge/issues/80

```
npx next info

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.14-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A

```

**Comment by EliotCampbell** [comment] 2023-08-11 18:11
Also have this on windows localy 
`if (request.method !== 'OPTIONS') {
      const token = getCookies()
      console.log(token)
      return NextResponse.next()
    }`

- error node_modules\next\dist\client\components\headers.js (50:14) @ cookies
- error Invariant: Method expects to have requestAsyncStorage, none available

**Comment by NastykSwED** [comment] 2023-08-14 20:56
The error still occurs in version 13.4.15 and 13.4.15-canary.0

**Comment by christophmeise** [comment] 2023-08-16 21:38
Still facing the error on Windows 11 in version 13.4.16

**Comment by NastykSwED** [comment] 2023-09-01 08:58
The error still occurs in version 13.4.19 and 13.4.20-canary.15

**Comment by NastykSwED** [comment] 2023-09-19 07:07
The error still occurs in version 13.4.20-canary.40

**Comment by eduardo-amaro-maciel** [comment] 2023-09-19 23:31
I'm using next 13.4.19 with supabase, with app directory... I'm doing a simple GET route and I got the same error...

`throw new Error("Invariant: cookies() expects requestAsyncStorage, none available.");`

The simple code:

```
export async function GET(req: NextRequest, res: NextResponse) {
   headers();
   const { data, error } = await supabase.from("usuario_empresa").select(`
      usuario:usuario_id ( id, nome, email, telefone, data_nascimento, cidade_nascimento ),
      empresa:empresa_id ( id, nome, cnpj, endereco )
   `);

   if (error) {
      return NextResponse.json({ message: "Erro ao obter usuários" });
   }

   return NextResponse.json({ data });
}
```

**Comment by oliver-oloughlin** [comment] 2023-09-21 15:38
Error still persists on version 13.5.2. I'm on windows and have tried running it normally and using WSL.

**Comment by oliver-oloughlin** [comment] 2023-09-21 15:45
Error also persists in version v13.5.3-canary.0

**Comment by blackpill** [comment] 2023-09-26 22:42
Error also persists in version v13.5.3
The bug only occurs on windows.
The same code can run correctly on MacOS and vercel.

**Comment by anuraagvaidya** [comment] 2023-10-08 08:17
Same error for me. Has a fix been identified?

Node version = v18.12.1
Package version: next@13.5.4-canary.11
OS: Windows 11

Use case:

```
import { cookies } from 'next/headers'
export async function GET(request) {
  const requestUrl = new URL(request.url)
  const code = requestUrl.searchParams.get('code')

  if (code) {
    const supabase = createRouteHandlerClient({ cookies })
    await supabase.auth.exchangeCodeForSession(code)
  }
//irrelevant code
}
```

**Comment by w3nder** [comment] 2023-10-08 18:56
I downgraded next to 13.5.3 and it works.
Node 18 
Windows 11

**Comment by oliver-oloughlin** [comment] 2023-10-08 19:11
Tried Next 13.5.3 with Node 18 on Windows 11, still no luck for me.
Latest version that works is 13.4.7

**Comment by christophmeise** [comment] 2023-10-09 10:56
I am still facing the same issue with Next 13.5.5-canary.4 with Node 18 and Windows 11.
The same code is working fine on MacOS. 

With this bug, I can not declare any page as runtime edge for local development when working on Windows.

**Comment by anuraagvaidya** [comment] 2023-10-09 11:25
I can confirm that @oliver-oloughlin's solution is right. It worked for me as well on 13.4.7.
Obviously, --experimental-https flag wasn't supported on 13.4.7, so I ended up using `local-ssl-proxy` as described in [this issue](https://github.com/vercel/next.js/discussions/10935#discussioncomment-6505990)

**Comment by benjick** [comment] 2023-10-10 16:53
I'm getting this error running `bun test`, bun version 1.0.4, next version 13.5.2

**Comment by w3nder** [comment] 2023-10-15 20:16
"next": "13.5.5-canary.14",also solves the problem

**Comment by benjick** [comment] 2023-10-15 20:35
@w3nder thank you, but it's not working for me, still failing with `bun test`

> "version": "13.5.5-canary.14",

**Comment by christophmeise** [comment] 2023-10-16 08:33
Also still broken for me, tested with 13.5.5-canary.17

> "next": "13.5.5-canary.14",also solves the problem

**Comment by heblol** [comment] 2023-10-16 18:55
I got the same error and I got it working somehow. I tried many things, but these were my last two steps.

I did:
1. Downgraded to `"next:" 13.4.7`
2. Added `"use server"` to the component that called `cookies` and also made it a async function (which was required for the "use server" flag).

```
"use server"; // added "use server"
// This only works server-side!
import { Database } from "@/types/supabase";
import { createServerActionClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";

async function supabaseServerSide() { //Made an async export function
  const cookiesStore = cookies();

  const supabase = createServerActionClient<Database>({
    cookies: () => cookiesStore,
  });

  return supabase;
}

export default supabaseServerSide;
```

Now calling the supabase server function like this in my React component. It looks a bit ugly because of the await (await ..)

```
const { data: currentUser, error } = await (await supabaseServerSide())
    .schema("public")
    .from("user_profile")
    .select("*");
```

I hope this works for others as well

**Comment by azeemasim01** [comment] 2023-11-15 16:54
This is more a platform related issue. So the localhost was having this issue. I was able to resolve it by adding this line in **app/page.js** file

export const runtime = 'nodejs';

**Comment by oliver-oloughlin** [comment] 2023-11-15 17:02
@azeemasim01 Yeah, but that's exactly the issue, runtime edge on windows causes the bug. I am using the edge runtime, so switching to nodejs is not a solution for me or anyone committed to edge.

**Comment by joachimjusth** [comment] 2023-11-30 04:31
I'm also facing this issue.
But more specificly.

The error only occured on dynamic route (app router).

Example:

Works perfectly:
```
// apps/dashboard/page.tsx

export default async function Dashboard() {
  const data = await api.myApiRoute.myProcedure();
  return <>Dashpage</>
}
```

On dynamic route, it throws the error `Error: Invariant: headers() expects to have requestAsyncStorage, none available.`
```
// apps/dashboard/posts/[postId]/page.tsx

type Props = {
  readonly params: {
    readonly postId: string;
  }
}

export default async function PostDetail({params: { postId }}: Props) {
  const data = await api.myApiRoute.myProcedure();
  return <>PostDetail page {postId}</>
}
```

the `api` is a simple trpc caller:

```
import "server-only";

import { headers } from "next/headers";
import { appRouter } from "~/server/api/root";
import { db } from "~/server/db";
import { auth } from "@clerk/nextjs";

export const api = appRouter.createCaller({
  db,
  headers: headers(), // here the error is throw
  auth: auth(),
});
```

there is my `next info` output:

```
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Thu Oct 5 21:02:42 UTC 2023
Binaries:
  Node: 18.14.2
  npm: 9.5.0
  Yarn: N/A
  pnpm: 8.10.2
Relevant Packages:
  next: 14.0.3
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

I'm working with `clerk` for the auth part.

What I found until now:

The ```return new maybeGlobalAsyncLocalStorage();``` seems different regarding a request where it's ok.
the value of the return:
```
AsyncLocalStorage {
  kResourceStore: Symbol(kResourceStore),
  enabled: false,
  _onPropagate: null
}
```
comparing to an ok:
```
AsyncLocalStorage {
  kResourceStore: Symbol(kResourceStore),
  enabled: true,
  _onPropagate: null
}
```

so it seems that the AsyncLocalStorage is disabled
I was going deeper when I found out this type definition (from node):
```
        /**
         * Returns the current store.
         * If called outside of an asynchronous context initialized by
         * calling `asyncLocalStorage.run()` or `asyncLocalStorage.enterWith()`, it
         * returns `undefined`.
         * @since v13.10.0, v12.17.0
         */
        getStore(): T | undefined;
```

I prepared a little repository to replicate the issue

I hope it'll help

**Comment by nickverstocken** [comment] 2024-02-07 18:50
I have the exact same issue with Next 14.0.4 where a catch all route that only returns a "NotFound" page causes the issue... 
The application is completely server side renderen (except a few client side components). The issue only happen when I try to access `draftMode` which is related to headers as discussed here. 

I am still looking for a workaround because it is annoying because I use a headless CMS and this is the entry point for editors to see their changes that are not approved an published yet

**Comment by balazsorban44** [comment] 2024-02-27 21:22
We've added a lot of improvements since this issue was opened, `cookies()` and `headers()` are supported in more places (for example Middleware, but also cannot reproduce issues with pages marked with `export const runtime = "edge"`).

It looks like that comments have somewhat deviated from the original report, (which I verified working fine on `next@canary`) or did not add a reproduction. (we cannot investigate "same issue" comments).

In most cases, the issue is that you are calling `headers()` or `cookies()` outside the request context, so the error would be expected. I recently made a docs improvement that explains this with a better error message: https://github.com/vercel/next.js/pull/62143. See the rendered error explanation (and how to fix it) here: https://nextjs.org/docs/messages/next-dynamic-api-wrong-context

Please upgrade, and if you are still having issues, open a new bug report with a minimal reproduction, thanks! :pray: (Note, a minimal reproduction means you don't assume the maintainer to register for third-party services, setting up env. secrets etc., unless it's really necessary to reproduce the bug.)

**Closed by balazsorban44** 2024-02-27 21:22 UTC
Labels: please add a complete reproduction, template: bug, area: Metadata, area: Edge, area: app, type: needs triage
