### ISSUE TITLE
Requests to next internals (/_next/...) should never trigger app routes. 

### ISSUE THREAD

**Issue by r00dY** [vercel/next.js#19270] opened 2020-11-18 14:41 UTC
# Bug report

## Describe the bug / reproduction

We've had very time-consuming bug to find. We have `pages/[...redirect].js` fallback page which purpose is redirecting for languages (it was before Next 10).

Let's assume next.js does a request to a file `/_next/.../my-page.json` (via Next Link) and the file doesn't exist. This happens when page was rebuilt and we have new build ID and user still keeps old session in the browser. In that scenario, next.js will trigger `/[...redirect].js` route, although it's pretty obvious that none of the `/_next/...` calls should really do this.

Because of that, instead of 404 for `/_next/.../my-page.json` which would trigger hard reload (which would in turn reset build ID to the new one), we get something that is completely random because our `[...redirect].js` got `/_next/.../my-page.json` path which it didn't even take into account. This has far reaching consequences of weird and unexpected behaviours.

## Expected behavior

If `/_next/.../my-page.json` doesn't exist, next.js should simply return 404. Paths from `/_next` should never trigger app routing.

## System information

- OS: any
- Browser: any
- Version of Next.js: 9.5.3
- Version of Node.js: (vercel default) 
- Deployment: Vercel

**Comment by Timer** [comment] 2020-11-18 14:47
Please fill out the issue template in its entirety. You excluded vital information like your Next.js version, how you're building your app, and where you're hosting it:

```
# Bug report

## Describe the bug

A clear and concise description of what the bug is.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior

A clear and concise description of what you expected to happen.

## Screenshots

If applicable, add screenshots to help explain your problem.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 10.0.1]
- Version of Node.js: [e.g. 12.0.0]
- Deployment: [e.g. next start, next export, Vercel, other platform]

## Additional context

Add any other context about the problem here.
```

**Comment by r00dY** [comment] 2020-11-18 14:50
@Timer thanks for the response, fixed.

**Comment by kachkaev** [comment] 2020-11-18 15:20
I'm not sure that changing the behaviour won’t cause any negative side effects. For instance, I have a project using [`next-optimised-images`](https://github.com/cyrilwanner/next-optimized-images), which dumps files to `/_next/static/images/image.hash.ext`. With a catch-all route I can potentially redirect from `old-hash` to `new-hash` without having to rely on a custom server.

What if you add an if statement in your `get*Props` function and return `{ notFound: true }` for any path that starts with `/_next/`?

**Comment by r00dY** [comment] 2020-11-18 15:33
@kachkaev you're right, my suggestion is probably burdened with potential side effects. And we've fixed this anyway, the problem is how long it took and how unintuitive next behaviour was.

Maybe we should simply limit my report to the case of downloading page props JSON files and leave `/_next/static` untouched? Page props json files are by definition "next.js internals" and it's hard to imagine someone want to catch them in routing. By definition they "should always be there anyway", the only edge-case I see is project was rebuilt and someone keeps browser session with old build_id -> in such case they can "disappear". Have no idea if other internals are susceptible to this behaviour too.

**Comment by Timer** [comment] 2020-11-18 15:34
@kachkaev FYI putting anything in `/_next` is highly discouraged as it's a "system directory" in Next.js. You're not supposed to put anything custom in it.

**Comment by Timer** [comment] 2020-11-18 15:34
I think we can patch this for at least `/_next/data` though.

**Comment by vdhpieter** [comment] 2020-12-17 13:00
I have a similar problem but different. I filled in the template for clarity:

# Bug report

## To Reproduce

1. Create a Next page with a dynamic route `pages/books/[id].tsx`
2. Return `{ notFound: true }` from gSSP if the page does not exist (if the app couldn't find a book with that id)
3. When an internal route (like `/_next/data/[hash]/book/1234.json`) is called with a non existing id (so gSSP returns `notFound`) it returns the fully built 404 page instead of a JSON response.

## Describe the bug

Next internal API routes return an HTML response when gSPP returns `{ notFound: true }`. In normal app usage, this is not a real problem but we had a user try to enumerate all endpoints (which is not protected given that all that info is public, so we don't mind the enumeration) it caused unnecessary load and errors for our APP.

## Expected behavior

When a data route returns 404 it doesn't include HTML

## System information

- OS: any
- Browser: any
- Version of Next.js: 10.0.3
- Version of Node.js: 12.14.1
- Deployment: next start

Is this related enough or should I open a new ticket?

**Comment by bscaspar** [comment] 2020-12-19 00:04
I am encountering something similar. Details also in the template:

# Bug report

## Describe the bug

On our dynamic route `pages/[username]`, we use `fallback: true` so when a new user is onboarded, their static page is generated and viewable on the first visit to the page.

During fallback, we render a loading spinner.

If `getStaticProps` throws an error or does not find a user associated with the `/[username]` route, a flag is set in the props and the `/[username]` page redirects to a 404 page. 

When I am testing this out locally, this works great. However, once deployed to a preview environment, something odd happens. After creating a new user, on the first navigation to their `/[username]` page, an error occurs and the page changes to this:
<img width="275" alt="Screen Shot 2020-12-18 at 3 57 32 PM" src="https://user-images.githubusercontent.com/6042704/102674147-c052c500-4149-11eb-9d71-f8a60e92465e.png">

According to the logs, `getStaticProps` was run twice - once for the dynamic `[username]` associated with the route as expected, and then again for `ce4e51338c75d24b38ed.css.map` which is actually a build output. This second execution throws an error and rerenders the page with fewer hook executions which makes React unhappy and causes this error page. 

## Expected behavior

I expect `getStaticProps` not to run for anything but the initial `/[username]` url the user navigates to.

## System information

- OS: macOS Catalina 10.15.7
- Browser: Chrome 87.0.4280.88
- Version of Next.js: `^10.0.0`
- Version of Node.js: v10.23.0
- Deployment: Vercel

**Comment by bscaspar** [comment] 2020-12-23 16:22
@r00dY what was your fix for this bug?

**Comment by vdhpieter** [comment] 2020-12-23 19:12
@Timer @timneutkens Would this be easy to fix for a newbie? I would love to contribute if possible!

**Comment by r00dY** [comment] 2020-12-24 10:17
@bscaspar in my case I added a condition in `getServerSideProps` which checks whether route starts with `_next`. If so, 404, otherwise continue. It solved the issue.

But obviously, it's a hack. This should be fixed.

@vdhpieter I have never looked deeply into next.js codebase, but my intuition tells me it shouldn't be a big deal. Why don't you try out by yourself? You'll learn a lot in the process :)

**Comment by vdhpieter** [comment] 2020-12-24 10:54
I quickly checked and found the root cause I think. This is when gSSP returns 404 it ends up here:
https://github.com/vercel/next.js/blob/788183e8d3c6e354e24a89febcfdc482fc55640b/packages/next/next-server/server/next-server.ts#L1450-L1459

It knows at that point if the request is a data request or not (as seen on line 1450) but doesn't pass that info to render404.
https://github.com/vercel/next.js/blob/788183e8d3c6e354e24a89febcfdc482fc55640b/packages/next/next-server/server/next-server.ts#L1867-L1884
In render 404 the broader function renderError is called
https://github.com/vercel/next.js/blob/788183e8d3c6e354e24a89febcfdc482fc55640b/packages/next/next-server/server/next-server.ts#L1779-L1798

Which always returns HTML.

I think the solution would be to make sure that renderError is aware if it's a dataReq or not and handles those differently

**Comment by kachkaev** [comment] 2020-12-26 00:06
Just remembered that some tools might need access to handling `/_next/*` calls. The example I have is Sentry, which can be requesting `/_next/(.*).map` files to generate user-friendly error stacks. I have a project with a custom Express server, which does this:

```ts
const sourcemapsForSentryOnly = (token) => (req, res, next) => {
  // In production we only want to serve source maps for Sentry
  if (
    process.env.NODE_ENV === "production" &&
    !!token &&
    req.headers["x-sentry-token"] !== token
  ) {
    res
      .status(401)
      .send("Authentication access token is required to access the source map.");

    return;
  }
  next();
};

// ...

server.get(/\.map$/, sourcemapsForSentryOnly(serverRuntimeConfig.sentryToken));
```

This logic is transferrable to a Next.js rewrite rule + api route. However, if there is some special rule for `/_next/` folder as proposed in this ticket, it may become necessary to stick with a custom server.

**Comment by vdhpieter** [comment] 2021-01-09 19:47
The latest next update solved my issue!

**Comment by jaiew** [comment] 2021-03-28 14:12
Moving to next 10.0.0.9 solved my issue (But I think it was fixed in 10.0.0.5 or 10.0.0.6. I was previously on 10.0.0.0.
I have a catch all handler at `pages/[...uid].js` which was receiving the request for `_next/` request when a redeployment on vercel happened. Now it is reloading the page when trying to go to another page after the deployment to fetch the latest deployed version.

**Comment by lapa182** [comment] 2022-05-27 15:15
We have some logic inside `_app.tsx` and with source maps enabled on the browser we are getting some 404s which is causing `_app.tsx` to be triggered and causing some weird issues in the application. As a workaround, we add some safety checks, for example, "if it's 404 we don't want to run this".

Example of the error:

```
DevTools failed to load source map: Could not parse content for https://path.com/b0d8c17736ae7937.css.map: Unexpected token < in JSON at position 0
```

**Comment by Naveed-Iftikhar** [comment] 2022-05-27 16:17
Naveed

**Closed** 2024-02-27 23:01 UTC
Labels: kind: story, area: Routing
