### ISSUE TITLE
Allow configuring EXPORT_DETAIL path (error running export in a Lambda).

### ISSUE THREAD

**Issue by jschr** [vercel/next.js#10397] opened 2020-02-03 14:35 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I would like to run next export inside an AWS Lambda to periodically re-export my app. The output of next build is packaged and deployed to Lambda and only next export is run periodically. 

When Next.JS exports, it will write the export result to the `dist` directory. In the AWS Lambda environment, this will error because any directory other than `/tmp` is read-only.

I believe this would also resolve https://github.com/zeit/next.js/issues/10137.

Here is where export errors:
- https://github.com/zeit/next.js/blob/canary/packages/next/export/index.ts#L188
- https://github.com/zeit/next.js/blob/canary/packages/next/export/index.ts#L388

## Describe the solution you'd like

I would like an option to specify the path where Next.JS will write the export results (ie. `/tmp/next-export/results.json`) or disable writing results altogether.

```ts
import nextExport from 'next/dist/export';

await nextExport(
      dir,
      { 
        outdir: outDir,
        resultsFile:  `/tmp/next-export/results.json` // Specify path for 
        generateResultsFile: true,  // Alternatively, disable generating the results file.
      },
      {
        ...
      }
    );
```

## Describe alternatives you've considered

I've tried copying the next build output to `/tmp` before running export but this also means I'd need to copy over `node_modules`.

I could run the build in the Lambda and output to `/tmp` but re-running the build seems unnecessary as the source hasn't changed.

**Comment by Timer** [comment] 2020-04-15 05:19
This is likely covered by https://github.com/zeit/next.js/discussions/11552

**Comment by Timer** [comment] 2020-09-10 18:32
Closing as incremental static regeneration was released stable and should cover your use-case.

**Closed by Timer** 2020-09-10 18:32 UTC

**Comment by balazsorban44** [comment] 2022-01-29 13:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
