### ISSUE TITLE
Intercepting routes does not work with dynamic routes

### ISSUE THREAD

**Issue by volnei** [vercel/next.js#51414] opened 2023-06-16 13:23 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.0.1
      npm: 9.4.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.5
      eslint-config-next: 13.4.5
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4

warn  - Latest canary version not detected, detected: "13.4.5", newest: "13.4.7-canary.0".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
✨  Done in 2.32s.
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

private

### To Reproduce

Create a dynamic route [team] and a intercept route @[team].

### Describe the Bug

When tryed to create a dynamic route using intercepting next throw an error.

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server.edge' is not defined by "exports" in /Users/volnei/Projects/cursiva/node_modules/react-dom/package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:292:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:602:3)
    at resolveExports (node:internal/modules/cjs/loader:529:36)
    at Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at /Users/volnei/Projects/cursiva/node_modules/next/dist/server/require-hook.js:189:36
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at /Users/volnei/Projects/cursiva/node_modules/next/dist/server/app-render/app-render.js:978:37
    at /Users/volnei/Projects/cursiva/node_modules/next/dist/server/lib/trace/tracer.js:159:62
    at /Users/volnei/Projects/cursiva/node_modules/next/dist/server/lib/trace/tracer.js:117:36
    at NoopContextManager.with (/Users/volnei/Projects/cursiva/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
    at ContextAPI.with (/Users/volnei/Projects/cursiva/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
    at NoopTracer.startActiveSpan (/Users/volnei/Projects/cursiva/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
    at ProxyTracer.startActiveSpan (/Users/volnei/Projects/cursiva/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
    at /Users/volnei/Projects/cursiva/node_modules/next/dist/server/lib/trace/tracer.js:106:107
    at NoopContextManager.with (/Users/volnei/Projects/cursiva/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
    at ContextAPI.with (/Users/volnei/Projects/cursiva/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
    at NextTracerImpl.trace (/Users/volnei/Projects/cursiva/node_modules/next/dist/server/lib/trace/tracer.js:106:32)
    at /Users/volnei/Projects/cursiva/node_modules/next/dist/server/lib/trace/tracer.js:159:31
    at wrappedRender (/Users/volnei/Projects/cursiva/node_modules/next/dist/server/app-render/app-render.js:1025:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

### Expected Behavior

Works like intercepting routes expected.

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by alserembani94** [comment] 2023-06-30 19:04
I might want to add a bit of context of how I get the same error with intercepting routes using dynamic routes.

### Provide environment information

```
Operating system:
    System Version: macOS 14.0 (23A5276g)
    Kernel Version: Darwin 23.0.0
    Boot Volume: Macintosh HD
Binaries:
    Node: 16.20.1
    npm: 8.19.4
    yarn: 1.22.19
    pnpm: 7.12.2
Relevant packages:
    next: 13.4.7
    eslint-config-next: 13.4.7
    react: 18.2.0
    react-dom: 18.2.0
    typescript: 5.1.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)
App Directory

### Link to the code that reproduces this issue or a replay of the bug
https://github.com/alserembani94/atifaimandev-v4/blob/dev/next.config.js

> You can clone, and uncomment the `i18n` to replay the bug

### To Reproduce

I just add `i18n` configuration in `next.config.js`, while having `app/[lang]` directory. Then, I get the error.

### Describe the bug

I already configure the dynamic route `app/[lang]` to handle `i18n` routing. I just want to add this configuration inside `next.config.js` that should do route interception. However, I got this error instead when I try to run the project by running the following command:
```bash
pnpm dev
```

And this is the error:
```bash
- error Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server.edge' is not defined by "exports" in /Users/alserembani/alserembani/atifaimandev-v4/node_modules/.pnpm/next@13.4.7_biqbaboplfbrettd7655fr4n2y/node_modules/react-dom/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:649:3)
    at resolveExports (node:internal/modules/cjs/loader:556:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:596:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1014:27)
    at /Users/alserembani/alserembani/atifaimandev-v4/node_modules/.pnpm/next@13.4.7_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/require-hook.js:189:36
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at /Users/alserembani/alserembani/atifaimandev-v4/node_modules/.pnpm/next@13.4.7_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/app-render/app-render.js:980:37
    at /Users/alserembani/alserembani/atifaimandev-v4/node_modules/.pnpm/next@13.4.7_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/lib/trace/tracer.js:159:62
    at /Users/alserembani/alserembani/atifaimandev-v4/node_modules/.pnpm/next@13.4.7_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/lib/trace/tracer.js:117:36
    at NoopContextManager.with (/Users/alserembani/alserembani/atifaimandev-v4/node_modules/.pnpm/next@13.4.7_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/Users/alserembani/alserembani/atifaimandev-v4/node_modules/.pnpm/next@13.4.7_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NoopTracer.startActiveSpan (/Users/alserembani/alserembani/atifaimandev-v4/node_modules/.pnpm/next@13.4.7_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
    at ProxyTracer.startActiveSpan (/Users/alserembani/alserembani/atifaimandev-v4/node_modules/.pnpm/next@13.4.7_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
    at /Users/alserembani/alserembani/atifaimandev-v4/node_modules/.pnpm/next@13.4.7_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/lib/trace/tracer.js:106:107
    at NoopContextManager.with (/Users/alserembani/alserembani/atifaimandev-v4/node_modules/.pnpm/next@13.4.7_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/Users/alserembani/alserembani/atifaimandev-v4/node_modules/.pnpm/next@13.4.7_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NextTracerImpl.trace (/Users/alserembani/alserembani/atifaimandev-v4/node_modules/.pnpm/next@13.4.7_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/lib/trace/tracer.js:106:32)
    at /Users/alserembani/alserembani/atifaimandev-v4/node_modules/.pnpm/next@13.4.7_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/lib/trace/tracer.js:159:31
    at wrappedRender (/Users/alserembani/alserembani/atifaimandev-v4/node_modules/.pnpm/next@13.4.7_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/app-render/app-render.js:1028:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  digest: undefined
}
```

### Expected Behavior
Works with `i18n` routing as expected.

### Which browser are you using? (if relevant)
Chrome, Arc

### How are you deploying your application? (if relevant)
Vercel

**Comment by hadnet** [comment] 2023-10-09 21:25
Same thing with me, it doesn't work using i18n enabled, i'm using the app router and the intercepting routes is completely ignored. My project needs i18n, so WTF Vercel?

**Comment by enchorb** [comment] 2023-10-23 22:15
+1 intercepting routes is completely broken when your app is nested in `[lang]` for i18n

**Comment by hadnet** [comment] 2023-10-24 01:08
That’s why Vercel is highly criticized in the market when you take a look at their products. What’s worse, they’re not honest enough to clarify. I think the Vercel CEO is falling short in many ways. It’s a shame.

**Comment by kachkaev** [comment] 2023-12-11 14:08
👋 @balazsorban44! There is a reproduction of a similar case with intercepting routes in https://github.com/vercel/next.js/issues/53170. The title of the issue is different, but it might have the same root cause. You can also find a few incoming links below my report. I guess there is a bunch of issues originating from a single bug, which can potentially be solved all at once.

![Screenshot 2023-12-11 at 14 05 53](https://github.com/vercel/next.js/assets/608862/1c3ab937-bc09-4ea5-b6bd-65e545264baf)

**Comment by balazsorban44** [comment] 2023-12-11 14:19
Thanks @kachkaev! I'm looking into that issue right now. I'll be closing this one manually, if anyone having the same issue and has a complete but minimal reproduction with `next@canary`, feel free to open a new issue, and we will follow up!

**Closed by balazsorban44** 2023-12-11 14:19 UTC
Labels: please add a complete reproduction, template: bug, area: app
