### ISSUE TITLE
Failure when using dependencies with optional chaining

### ISSUE THREAD

**Issue by jonathantneal** [vercel/next.js#20363] opened 2020-12-21 14:08 UTC
# Bug report

## Describe the bug

Using a dependency with optional chaining throws NextJS, at least crashing the page and potentially crashing the process depending on where it is used.

Optional chaining feature is supported in at least the last two versions of all modern browsers, and it works out of the box in Node 14 and Node 15.

When a dependency uses optional chaining, it seems like it passes through some JavaScript processor that cannot handle this feature. This is what leads NextJS to forward the error by saying that I may “_need an appropriate loader to handle this file type, currently no loaders are configured to process this file._”

I did try to configure Babel filters using an `.babelrc` configuration, but it did not have any affect on the module. Also, I’m not interested in transpiling this feature. I only want to ship it.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Checkout [nextjs-dependency-with-optional-chaining-bug](https://github.com/jonathantneal/nextjs-dependency-with-optional-chaining-bug), install the dependencies, and run the `start` script.
2. Visit the server.
3. See error (pasted below)

Alternatively, visit this [CodeSandbox reproduction](https://codesandbox.io/s/github/jonathantneal/nextjs-dependency-with-optional-chaining-bug).

> Failed to compile
> ```
> ./node_modules/some-dependency/index.mjs 3:31
> Module parse failed: Unexpected token (3:31)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> | export default () => {
> | 	console.log(typeof globalThis)
> > 	console.log(typeof globalThis?.navigator)
> | }
> |
> ```
> This error occurred during the build process and can only be dismissed by fixing the error.

## Expected behavior

Using optional chaining in a dependency should not throw the page or the process. It should only fail if either Node or my browser does not support the feature.

## Screenshots

![Screen shot of the NextJS error](https://user-images.githubusercontent.com/188426/102785049-4e59c600-436b-11eb-8e2c-2ca28150fa7d.jpg)

## System information

- OS: macOS
- Version of Next.js: 10.0.3
- Version of Node.js: 15.4.0
- Deployment: next dev

**Comment by timneutkens** [comment] 2020-12-22 13:28
Assuming this is an upstream issue in webpack 4 (older JS parser). I think it's fixed in webpack 5 already.

**Comment by jonathantneal** [comment] 2020-12-22 15:20
Thanks for the followup, @timneutkens.

I confirm the issue appears resolved in Webpack 5, tested using [`resolutions`](https://nextjs.org/blog/next-9-5#webpack-5-support-beta), which is pushed to this [branch](https://github.com/jonathantneal/nextjs-dependency-with-optional-chaining-bug/tree/use-webpack-5?file=/my-app/package.json), which can be seen at this [CodeSandbox](https://codesandbox.io/s/github/jonathantneal/nextjs-dependency-with-optional-chaining-bug/tree/use-webpack-5?file=/my-app/package.json).

How can I help? Should this be closed and/or make a reference another issue or story that would enable Webpack 5 out-of-the-box?

**Comment by timneutkens** [comment] 2021-01-03 14:00
You can follow https://github.com/vercel/next.js/pull/20598

**Comment by dlcoffee** [comment] 2021-01-30 02:47
i'm not sure if the issue came back or not, as i was testing this today. the `resolutions` for webpack 5 works on @jonathantneal's branch using `next: "10.0.3`. i _think_ today's release of `10.0.6` broke it again. here's the diff: https://github.com/dlcoffee/nextjs-dependency-with-optional-chaining-bug/commit/6baa9b2f749de75a8f1ef3152c2cc0c3e5aa7736

i tried `10.0.3`, `10.0.4`, `10.0.5`, and `10.0.6` and the last one seems to be the only one where it fails.

here's some additional info on my machine:

    OS: macOS
    Version of Next.js: 10.0.6
    Version of Node.js: 14.7.0

https://user-images.githubusercontent.com/2092822/106345063-46424f80-6262-11eb-994d-3846415625c9.mov

**Comment by timneutkens** [comment] 2021-02-01 08:53
Resolutions is no longer needed / doesn't do anything anymore, instead you can use the `future` flag in `next.config.js`:

```
module.exports = {
  future: { webpack5: true }
}
```

**Comment by dlcoffee** [comment] 2021-02-01 17:19
@timneutkens thanks for the update! does this mean that `yarn` is no longer necessary?

**Comment by ramsunvtech** [comment] 2021-11-17 11:42
`future.webpack5` in `next.config.js` has moved to the top level so it will be like below.

```
{
  webpack5: true,
  webpack(config, options) {
  ...
```

**Comment by timneutkens** [comment] 2021-11-17 13:05
Webpack 5 has been the default since Next.js 11. In Next.js 12 webpack 4 is no longer available to s this should be fixed.

**Closed by timneutkens** 2021-11-17 13:05 UTC
Labels: kind: bug, type: upstream, type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-27 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
