### ISSUE TITLE
SCSS module is not loading on route change when using dynamic import

### ISSUE THREAD

**Issue by SZharkov** [vercel/next.js#18252] opened 2020-10-26 13:37 UTC
# Bug report
After I've implemented [dynamic](https://nextjs.org/docs/advanced-features/dynamic-import) loading of components - some of the components are not loading their scss module when changing the page. I see no issues in dev mode and that's only related to the production.

## Describe the bug
My app is dynamic, pages and sections are generated dynamically (based on received data from the server).
It works this way:
1) I open the homepage. All the components are working ok. 
2) Using navbar I navigate to another page (without page refresh) and from this point some of the components are loaded without styles. 
3) Once I refresh the page - styles are working again

## System information

- Latest version of Next.js

**Comment by jamesmosier** [comment] 2020-10-27 01:11
Hi @SZharkov. Can you please provide a full reproduction of this issue in a repository?

**Comment by SZharkov** [comment] 2020-10-27 09:23
@jamesmosier that's problematic, because the project is private. And I am not sure whether trying to reproduce from scratch will show this issue. I just hope that somebody faces the same issue.
I guess that the problem could be related to this part of code - https://github.com/vercel/next.js/blob/11fce3a6861c2415ed2dfdc411e428e142373f96/packages/next/pages/_document.tsx#L168. When changing the page it just stops injecting css for some components.

**Comment by SZharkov** [comment] 2020-10-29 12:46
@jamesmosier you can find the reproduction in this repo - https://github.com/SZharkov/dynamic-import-no-styles. 
Just `next build` and `next start`. Then try to navigate between pages, for example from homepage to page1 etc, and you will see that the styles are not applied for some of the components for example text is dark while it should be red. Then when you see this inconsistency - reload page, styles will be ok again, but try to navigate to another page and they will be broken again.

**Comment by SZharkov** [comment] 2020-11-04 21:22
@jamesmosier do you have any update? :)

**Comment by zenhob** [comment] 2020-11-10 18:04
I am seeing the same behavior, but with productions builds only, it works as expected in development mode.

**Comment by SZharkov** [comment] 2020-11-15 22:59
Really would appreciate some thoughts. This bug blocks me from optimizing projects using dynamic imports and that affects negatively on page speed and scores too much 😞

**Comment by Timer** [comment] 2020-11-16 16:30
This was fixed on `next@canary`.

**Closed by Timer** 2020-11-16 16:30 UTC

**Comment by balazsorban44** [comment] 2022-01-29 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
