### ISSUE TITLE
SSR redirect destition with basePath

### ISSUE THREAD

**Issue by sebascomeau** [vercel/next.js#18984] opened 2020-11-09 15:35 UTC
# Bug report

## Describe the bug

We are using basePath in our application and from / we are directing to /[goalType] with Server Side Rendering. We are determining the goalType base on a API fetch and the language use in the app. GoalType can be AS or GE. If I use basePath '/resource-finder' and trying it, the page is hitted but I'm redirected to '/AS'. It should redirect me to '/resource-finder/AS'. I have the same behavior if using router.push('/AS').

Here's the getServerSideProps function
```javascript
export async function getServerSideProps(context) {
  const { i18n } = context.req;
  const isFrench = i18n.language.startsWith('fr');
  const sort = [isFrench ? 'descriptionFr' : 'descriptionEn'];

  const goals = [...((await GoalService.getGoals({ size: 1, sort }))._embedded?.goals ?? [])];
  const goal = goals.length ? goals[0] : undefined;

  // redirects to goal
  if (goal) return { props: {}, redirect: { destination: `/${goal.goalType}` } };

  // returns 404
  return { notFound: true };
}
```
## Expected behavior

Usins basePaht '/resource-finder should redirect me to '/resource-finder/AS' if using '/resource-finder/' path in the browser. This basePath is ignored in getServerSideProps and router.push().

## System information

- OS: Windows
- Version of Next.js: 10.0.1
- Version of Node.js: 15.1.0

**Comment by sebascomeau** [comment] 2020-11-10 12:22
Tested building and starting the app locally and here's what I noticed.

- Redirecting in getServerSideProps dont works (basePath ignored).
- Router.push() works (basePath not ignored).

Tested the app from a docker image and here's what I noticed.

- Redirecting in getServerSideProps dont works (basePath ignored).
- Router.push() dont works (basePath ignored).

The docker image running in a container pickup the env variables because I can reach my API that is using the env variable.

next.config.js
``` javascript
const basePath = process.env.BASE_PATH ?? '';
const environment = process.env.ENVIRONMENT ?? 'UNKNOWN';
const apiBaseUri = process.env.API_BASE_URI ?? '';

/**
 * The main Next.js configuration.
 * see: https://nextjs.org/docs/api-reference/next.config.js/environment-variables
 *
 * @author Greg Baker <gregory.j.baker@hrsdc-rhdcc.gc.ca>
 */
module.exports = {
  basePath,
  publicRuntimeConfig: {
    basePath,
    environment,
    i18n: { lookupCookie: 'locale' },
    apiBaseUri
  }
};
```

Dockerfile
``` yaml
#
# Create 'BUILD' image
#
FROM node:15.1.0-alpine AS BUILD
WORKDIR /build

# install build dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install

# build the application
COPY public/ public/
COPY src/ src/
COPY next.config.js .
RUN yarn build

#
# Create 'RUNTIME' image
#
FROM node:15.1.0-alpine
WORKDIR /app

# install the nextjs runtime and application
COPY --from=BUILD /build/.next/ .next/
COPY --from=BUILD /build/public/ public/
COPY --from=BUILD /build/next.config.js .
COPY --from=BUILD /build/package.json .
COPY --from=BUILD /build/yarn.lock .
RUN yarn add next

#CMD yarn start
CMD ["yarn", "start"]
EXPOSE 3000
```

**Comment by sebascomeau** [comment] 2020-11-10 13:08
I've changed my Dockerfile and the problem is still there when running in a container.

``` yaml
FROM node:15.1.0-alpine

# setting working directory. All the path will be relative to WORKDIR
WORKDIR /app

# installing dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install

# copying source files
COPY . .

# building app
RUN yarn build

# running the app
CMD [ "yarn", "start" ]

# expose port
EXPOSE 3000
```

**Comment by ijjk** [comment] 2020-11-10 15:47
Hi, this should be resolved after https://github.com/vercel/next.js/pull/18988 is landed

**Closed** 2020-11-11 07:13 UTC
Labels: kind: bug, point: 2

**Comment by ijjk** [comment] 2020-11-11 18:08
The above PR is now available in `v10.0.2-canary.9` of Next.js, please upgrade and give it a try!

**Comment by sebascomeau** [comment] 2020-11-12 12:26
I still have problems with "next": "^10.0.2-canary.12".

Tested building and starting the app locally and here's what I noticed.

- [X] Redirecting in getServerSideProps works (basePath not ignored).
- [ ] Router.push() doesn't works (basePath ignored).

Tested the app from a docker image and here's what I noticed.

- [X] Redirecting in getServerSideProps works (basePath not ignored).
- [ ] Router.push() dont works (basePath ignored).

**Comment by sebascomeau** [comment] 2020-11-12 13:24
I still have problems with "next": "10.0.2-canary.9".

Tested building and starting the app locally and here's what I noticed.

:heavy_check_mark: Redirecting in getServerSideProps works (basePath not ignored).
:heavy_check_mark: Router.push() works (basePath not ignored).

Tested the app from a docker image and here's what I noticed.

:heavy_check_mark: Redirecting in getServerSideProps works (basePath not ignored).
:x: Router.push() dont works (basePath ignored).

**Comment by ijjk** [comment] 2020-11-12 17:28
Looks like the above mentioned error with `basePath` being ignored with `router.push` is from https://github.com/vercel/next.js/issues/19099 and not a bug in the latest canary, we also have tests covering this feature with `basePath` support which are passing correctly

**Comment by balazsorban44** [comment] 2022-01-29 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
