### ISSUE TITLE
Allow using _error page in development

### ISSUE THREAD

**Issue by Yankovsky** [vercel/next.js#11898] opened 2020-04-14 23:57 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

[custom-error-page doc](https://nextjs.org/docs/advanced-features/custom-error-page) states that 

> pages/_error.js is only used in production. In development you’ll get an error with the call stack to know where the error originated from.

but it makes debugging and testing custom _error page a difficult task. Currently I need to use `yarn build` and `yarn start` which is too slow compared to development mode.

## Describe the solution you'd like

It would be great to have a way to switch from [error-overlay-webpack-plugin](https://github.com/smooth-code/error-overlay-webpack-plugin) to _error page in development mode.

## Describe alternatives you've considered

Maybe we can use some env variable, pass some option in next.config or change the error handling behavior according to NODE_ENV.

## Additional context

What I also don't like about current behavior is that if error has happened during the page change the url will change but the page won't [video](http://s.csssr.ru/U02D248T6/2020-04-15-02-45-48-i2wym.mp4).

It is possible right now to navigate to /_error page in development but what I really want to do is to test whole error handling flow starting from error invocation and ending on custom _error page.

Thank you!

**Comment by lachlanjc** [comment] 2021-01-03 07:48
Related: #8036

**Comment by Timer** [comment] 2021-01-04 19:32
Closing as duplicate of above issue

**Closed by Timer** 2021-01-04 19:32 UTC

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
