### ISSUE TITLE
Unhandled Rejection at: Promise

### ISSUE THREAD

**Issue by andyTsing** [vercel/next.js#10157] opened 2020-01-19 02:42 UTC
# Bug report
Unhandled Rejection at: Promise

## Describe the bug
[ ready ] compiled successfully - ready on http://localhost:3000
Unhandled Rejection at: Promise {
  <rejected> Error: EPERM: operation not permitted, lstat 'D:\Temp\TXSSPrinter\FEAdmin\.next\static\development\pages\index.js'
      at realpathSync (fs.js:1562:7)
      at deleteCache (D:\Temp\TXSSPrinter\FEAdmin\node_modules\next\dist\build\webpack\plugins\nextjs-require-cache-hot-reloader.js:1:177)    
      at D:\Temp\TXSSPrinter\FEAdmin\node_modules\next\dist\build\webpack\plugins\nextjs-require-cache-hot-reloader.js:2:355
      at _next0 (eval at create (D:\Temp\TXSSPrinter\FEAdmin\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:19:1)
      at eval (eval at create (D:\Temp\TXSSPrinter\FEAdmin\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:1)
      at D:\Temp\TXSSPrinter\FEAdmin\node_modules\next\dist\build\webpack\plugins\unlink-removed-pages-plugin.js:2:517 {
    errno: -4048,
    syscall: 'lstat',
    code: 'EPERM',
    path: 'D:\\Temp\\TXSSPrinter\\FEAdmin\\.next\\static\\development\\pages\\index.js'
  }
} reason: Error: EPERM: operation not permitted, lstat 'D:\Temp\TXSSPrinter\FEAdmin\.next\static\development\pages\index.js'
    at realpathSync (fs.js:1562:7)
    at deleteCache (D:\Temp\TXSSPrinter\FEAdmin\node_modules\next\dist\build\webpack\plugins\nextjs-require-cache-hot-reloader.js:1:177)      
    at D:\Temp\TXSSPrinter\FEAdmin\node_modules\next\dist\build\webpack\plugins\nextjs-require-cache-hot-reloader.js:2:355
    at _next0 (eval at create (D:\Temp\TXSSPrinter\FEAdmin\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:19:1)
    at eval (eval at create (D:\Temp\TXSSPrinter\FEAdmin\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:1)
    at D:\Temp\TXSSPrinter\FEAdmin\node_modules\next\dist\build\webpack\plugins\unlink-removed-pages-plugin.js:2:517 {
  errno: -4048,
  syscall: 'lstat',
  code: 'EPERM',
  path: 'D:\\Temp\\TXSSPrinter\\FEAdmin\\.next\\static\\development\\pages\\index.js'
}
## Expected behavior

no this to happen.

## Screenshots

![图片](https://user-images.githubusercontent.com/3162544/72673618-1174b780-3aa8-11ea-99e1-0f18a50c9a68.png)

## System information

- OS: Windows
- Browser: FF
- Version of Next.js: 9.2.0

**Comment by timneutkens** [comment] 2020-01-19 09:44
Please provide a github repository with all code needed to reproduce this issue.

**Comment by andyTsing** [comment] 2020-01-19 14:07
https://github.com/andyTsing/FEAdmin
TKS.

**Comment by ijjk** [comment] 2020-01-19 22:07
@andyTsing Can you provide additional details on the environment you're running this in, since this looks like a permission error knowing the permissions you're using and environment details could help.

The related line [here](https://github.com/zeit/next.js/blob/71c2354ecd615986835a2d5c2ea6117b17801703/packages/next/build/webpack/plugins/nextjs-require-cache-hot-reloader.ts#L8) re-throws when we get an error other than file not found which I'm not sure we want to change since we shouldn't run into permission errors checking a file's path as this could mean something else is wrong 🤔

**Comment by thusitha92** [comment] 2020-01-20 03:43
Same problem occurs for me.
Server starts fine and after a certain time it automatically throws this error (Even if there are no code errors). After this error, hot reloading is stopped in the browser. Need to restart the server again.

![next js error](https://user-images.githubusercontent.com/7900564/72696992-42b2bd80-3b64-11ea-8619-0dd6d1a7cd7b.png)

I'm currently using 
**Next: v9.2.0**
**Node JS: v10.18.1**
**NPM: v6.13.4**
**OS: Windows 10**

I tried to resolve this issue by updating Node version to `12.x`. Problem didn't resolve.
No effect on execute with admin privileges as well.

**Comment by andyTsing** [comment] 2020-01-20 07:59
@ijjk I used the vs code IDE, which was started with administrator privileges.
Also, the project's  directory is in a non-C: drive and should not have permission issues.

    OS: Windows 10 1909-18363.592
    Browser: firefox 72.0.1 (64 位)
    Version of Next.js : v9.2.0
    Version of Node   : v13.6.0
    Version of yarn    : v1.21.1

    vscode about show:
        版本: 1.42.0-insider (system setup)
        提交: fd13e449f5f2fe300f187129d6065ed1cfad74d3
        日期: 2020-01-17T17:23:31.960Z
        Electron: 7.1.7
        Chrome: 78.0.3904.130
        Node.js: 12.8.1
        V8: 7.8.279.23-electron.0
        OS: Windows_NT x64 10.0.18363

**Comment by ijjk** [comment] 2020-01-20 21:02
I'm not able to reproduce this on Windows 10 with `node 10` or `node 12` using an `NTFS` or `exFAT` drive mounted at `D:`. A detail from the above set-ups must be missing that is causing this permission conflict for those specific set-ups

**Comment by andyTsing** [comment] 2020-01-21 05:30
Repeatedly switching between routes, and with the browser navigation refresh, although the rule of reproduction is not standard, only in my case always appear...
It could be that in this case, just in the development phase...

**Comment by thusitha92** [comment] 2020-01-21 05:37
@andyTsing For the time being I have resolved this issue by commenting out the exception throwing. It works fine now. This is a dirty fix and it was a pain before when developing.
`node_modules\next\dist\build\webpack\plugins\nextjs-require-cache-hot-reloader.js`

Commented out `/**if(e.code!=='ENOENT')throw e;**/`

**Comment by andyTsing** [comment] 2020-01-21 05:42
@thusitha92 Thank you very much. In the absence of a better solution, I think I will do the same

**Comment by timneutkens** [comment] 2020-01-21 09:36
Highly recommend not doing that @thusitha92, this is a real error related to your machine and could potentially cause a larger issue on your machine.

**Comment by andyTsing** [comment] 2020-01-21 10:38
ref @ijjk "The related line[ here](https://github.com/zeit/next.js/blob/71c2354ecd615986835a2d5c2ea6117b17801703/packages/next/build/webpack/plugins/nextjs-require-cache-hot-reloader.ts#L8) re-throws when we get an error other than file not found which I'm not sure we want to change since we shouldn't run into permission errors checking a file's path as this could mean something else is wrong"
------------------------------------------------------------------------------------------------------
function deleteCache(path: string) {
  try {
    delete require.cache[realpathSync(path)]
  } catch (e) {
    if (e.code !== 'ENOENT') throw e
  } finally {
    delete require.cache[path]
  }
}
--------------------------------------------------------------------------------------------------------
I searched on Google and found that the earlier version looks like this:
function deleteCache(path: string) {
    delete require.cache[path]
}
The core issue of this commit is the issue of clearing the require.cache by 'hot reloading'，But, how do you identify the problem and eliminate it?
I use it like this for now：
function deleteCache(path: string) {
    delete require.cache[path]
}

**Comment by timneutkens** [comment] 2020-01-21 10:47
Are you using symlinks in your Next.js app by any chance?

**Comment by andyTsing** [comment] 2020-01-21 10:59
@timneutkens 
My own code is definitely not used symlinks ,But I'm not sure if other referenced npm packages are used.
TKS.

**Comment by quangtho2910** [comment] 2020-01-22 00:48
I have the same issues too. 
I'm currently using
Next: v9.2.0
Node JS: v10.18.1
NPM: v6.13.6
OS: Windows 10

**Comment by quangtho2910** [comment] 2020-01-28 07:10
Any update about this bug?

**Comment by timneutkens** [comment] 2020-01-28 09:49
@quangtho2910 feel free to investigate the issue.

**Comment by andyTsing** [comment] 2020-01-30 03:02
Recently did a trial, migrated the project directory to the E drive, and still reported the error ...
I haven't been able to reinstall the entire system for the time being. I suggest similar errors. Would you like to reinstall the system and report the results?

**Comment by yorgyetson** [comment] 2020-04-13 06:43
I ran into this exact issue 2 days ago. I've been struggling to find a solution until today I found two solutions. (More like 1.5 solutions)

I was working on this project for a couple weeks before I ran into this issue, so I think it may have something to do with the dependencies installed, though I'm not sure what exact package is causing the issue.

The root of the problem is Windows Defender's Real-time protection. The workarounds I found were to either completely disable real-time protection (not ideal) or to add the project folder to the exclusion list. I'll include steps for both below for Windows 10, but I strongly recommend just doing the exclusion.

**Fix 1 - Exclude your project folder from Windows Defender**
Open 'Windows Security' 
Click on 'Virus & Threat Protection'
Under 'Virus & threat protection settings' Click on 'Manage Settings'
Scroll down to the 'Exclusions' section and click on 'Add or remove exclusions'
Click 'Add an exclusion' and select your project folder or a parent.

**Fix 2 - Drastic Option - You probably don't want to do this.**

Open 'Windows Security' 
Click on 'Virus & Threat Protection'
Under 'Virus & threat protection settings' Click on 'Manage Settings'
Turn Off 'Real-time protection'

**Comment by officialrajdeepsingh** [comment] 2020-06-14 16:40
Read This https://medium.com/@officialrajdeepsingh/unhandledpromiserejectionwarning-unhandled-promise-rejection-f7d7b0e884d0?sk=65ac6178cc73bce81edb21f984fb2289

**Comment by musme** [comment] 2020-07-14 16:14
Same problem occurs for me. 
Any update about this bug?

**Comment by timneutkens** [comment] 2021-11-18 09:16
This was probably solved by moving to webpack 5.

**Closed by timneutkens** 2021-11-18 09:16 UTC
Labels: kind: bug, type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-27 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
