### ISSUE TITLE
Margin styles are creating unexpected behaviour in the new Image component

### ISSUE THREAD

**Issue by harshvitra** [vercel/next.js#18344] opened 2020-10-27 21:31 UTC
# Bug report

## Describe the bug

Margin styles are creating unexpected behaviour in the new Image component

Issue is because of position relative+absolute combination

**The structure Image component creates -** 

`<Image styles /> is replaced by `

```
<div> // with the width passed to image
   <div> // position relative
       <img /> // position absolute with the margin and other styles
   </div>
</div>
```

Issue is that the margin along with other styles are passed to the img component which has absolute position so it spoils the designs

## To Reproduce

Add margin to the Image component and see the unexpected behaviour

## Expected behavior

Expected that the margin is applied to the parent div and not to child

In the case of Image component it should be applied to the Wrapper

## Screenshots

<img width="342" alt="Screenshot 2020-10-28 at 2 41 18 AM" src="https://user-images.githubusercontent.com/44316146/97362636-4fb8c600-18c7-11eb-9835-6bb23bae78b6.png">

## Additional context

This can be added in the to do here
https://github.com/vercel/next.js/issues/18122

**Comment by lachlanjc** [comment] 2020-11-01 19:13
+1. https://github.com/hackclub/summer-scrapbook/issues/117 & https://github.com/hackclub/summer-scrapbook/issues/115

**Comment by Timer** [comment] 2020-11-01 23:46
Can you please try `next@canary` and see if it fixes your issue?

**Comment by lachlanjc** [comment] 2020-11-02 06:23
Yep, already did! Thanks.

**Comment by Timer** [comment] 2020-11-02 13:34
Closing as fixed on `next@canary`. Thanks!

**Closed by Timer** 2020-11-02 13:34 UTC
Labels: kind: story, point: 2, priority: p0, type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-29 07:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
