### ISSUE TITLE
Turbo: json-schema-to-typescript package errors (Cannot convert undefined or null to object)

### ISSUE THREAD

**Issue by AlessioGr** [vercel/next.js#66723] opened 2024-06-10 20:11 UTC
### Link to the code that reproduces this issue

https://github.com/AlessioGr/turbo-pkg-repro

### To Reproduce

In my reproduction repo: run `pnpm dev`

From scratch:
1. npx create-next-app@canary
2. pnpm add json-schema-to-typescript
3. `import {compile} from 'json-schema-to-typescript'` in the root layout
4. Call that function in the root layout
5. pnpm dev --turbo

### Current vs. Expected behavior

Current: This works on webpack. On turbopack it throws the following error:

```
> next dev --turbo

  ▲ Next.js 15.0.0-canary.23 (turbo)
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 1184ms
 ○ Compiling /_not-found/page ...
 ✓ Compiled /_not-found/page in 2.9s
 ⨯ TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at /Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/node_modules__pnpm_f51c9a._.js:8179:29
    at instantiateModule (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:530:23)
    at getOrInstantiateModuleFromParent (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:582:12)
    at esmImport (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at /Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/node_modules__pnpm_f51c9a._.js:8190:235
    at instantiateModule (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:530:23)
    at getOrInstantiateModuleFromParent (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:582:12)
    at esmImport (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at /Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/node_modules__pnpm_f51c9a._.js:8217:247
    at instantiateModule (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:530:23)
    at getOrInstantiateModuleFromParent (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:582:12)
    at commonJsRequire (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:146:20)
    at Object.<anonymous> (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/fbfc9_@apidevtools_json-schema-ref-parser_dist_lib_f238c6._.js:1049:15)
    at instantiateModule (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:530:23)
    at getOrInstantiateModuleFromParent (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:582:12)
    at commonJsRequire (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:146:20)
    at Object.<anonymous> (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/fbfc9_@apidevtools_json-schema-ref-parser_dist_lib_f238c6._.js:2884:35)
    at instantiateModule (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:530:23)
    at getOrInstantiateModuleFromParent (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:582:12)
    at commonJsRequire (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:146:20)
    at Object.<anonymous> (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/node_modules__pnpm_f51c9a._.js:3494:34)
    at instantiateModule (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:530:23)
    at getOrInstantiateModuleFromParent (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:582:12)
    at commonJsRequire (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:146:20)
    at Object.<anonymous> (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/node_modules__pnpm_f51c9a._.js:3669:20)
    at instantiateModule (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:530:23)
    at getOrInstantiateModuleFromParent (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:582:12)
    at esmImport (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at /Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/_ad62d2._.js:129:258
    at [project]/app/layout.tsx [app-rsc] (ecmascript) (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/_ad62d2._.js:205:3)
    at instantiateModule (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:530:23)
    at getOrInstantiateModuleFromParent (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:582:12)
    at esmImport (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at Module.default (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/_ad62d2._.js:209:20)
    at tree.layout (/Users/alessio/Documents/GitHub/reprot/.next/server/chunks/ssr/59b3a_next_dist_328f19._.js:3892:162)
digest: "2764682777"
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031
  Available memory (MB): 65536
  Available CPU cores: 16
Binaries:
  Node: 22.2.0
  npm: 8.19.4
  Yarn: 1.22.22
  pnpm: 8.15.8
Relevant Packages:
  next: 15.0.0-canary.23 // Latest available version is detected (15.0.0-canary.23).
  eslint-config-next: 15.0.0-canary.23
  react: 19.0.0-rc.0
  react-dom: 19.0.0-rc.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

This is the line in the compiled/bundled JS output where it errors at:

```js
const __TURBOPACK__default__export__ = __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f40$jsdevtools$2b$ono$40$7$2e$1$2e$3$2f$node_modules$2f40$jsdevtools$2f$ono$2f$esm$2f$singleton$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ono"];
// CommonJS default export hack
if (typeof module === "object" && typeof module.exports === "object") {
    module.exports = Object.assign(module.exports.default, module.exports);
} //# sourceMappingURL=index.js.map
```

**Comment by lfades** [comment] 2024-09-23 18:56
👋 

Tested your demo and was able to reproduce the issue, but it disappeared after I upgraded to the latest canary and react beta:

```json
  "dependencies": {
    "json-schema-to-typescript": "^14.0.5",
    "next": "15.0.0-canary.162",
    "react": "19.0.0-beta-26f2496093-20240514",
    "react-dom": "19.0.0-beta-26f2496093-20240514"
  },
``` 

I'll close the issue for now as it seems to be working fine but feel free to comment again if that's not the case.

**Closed by lfades** 2024-09-23 18:56 UTC
Labels: bug, Turbopack, linear: turbopack
