### ISSUE TITLE
Image component not passing all http headers to external image

### ISSUE THREAD

**Issue by modbender** [vercel/next.js#44118] opened 2022-12-18 08:22 UTC
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.18.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.7
      eslint-config-next: 13.0.7
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue

NA

### To Reproduce

NA

### Describe the Bug

On my NGINX image server I have a extra check for valid referrer

```config
if ($http_referer !~ '^https?://(localhost\:3000|site\.com|api\.site\.com)') {
    return 403;
}
```

When I'm using `Image` component from `next/image` I see 403 errors (in browser console) and when I open the url something like `http://localhost:3000/_next/image?url=image.site.com/image1.jpg`
```
"url" parameter is valid but upstream response is invalid
```

But when I'm **not** using `Image` component and instead loading it with direct url using `<img src>` I don't see any problems.

### Expected Behavior

HTTP Headers like `referer` and all other required headers should be passed to the url.

### How are you deploying your application? (if relevant)

localhost

**Comment by vr-santi** [comment] 2023-05-04 11:35
Same issue here.

**Comment by styfle** [comment] 2024-02-13 14:44
Closing as a duplicate of https://github.com/vercel/next.js/issues/23755

- See this comment https://github.com/vercel/next.js/issues/23755#issuecomment-848052191

**Closed by styfle** 2024-02-13 14:44 UTC
Labels: template: bug
