### ISSUE TITLE
Prop `className` did not match between server and client when "use client" and edge runtime

### ISSUE THREAD

**Issue by alexeygorbachevskiy** [vercel/next.js#52534] opened 2023-07-11 04:32 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
next version: 13.4.9
```

### Link to the code that reproduces this issue or a replay of the bug

See "To Reproduce"

### To Reproduce

Code:

```
"use client";

import { FC } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";

import LogoIcon from "icons/logo.svg";

import { Pages } from "constants/pages";

import styles from "./styles/header.module.scss";

const Header: FC = () => {
  const pathname = usePathname();

  return (
    <header className={styles.header}>
      <Link href={Pages.home}>
        <LogoIcon
          className={
            pathname === Pages.home
              ? styles.whiteColor
              : styles.primaryBlueColor
          }
        />
      </Link>
    </header>
  );
};
```

-------------------------

### Describe the Bug

Warning: Prop `className` did not match. Server: "header_primaryBlueColor__wYt_4" Client: "header_whiteColor__UEIv6"

So LogoIcon appears with incorrect styles applied both on dev and prod when app loaded first time.

### Expected Behavior

LogoIcon appears with correct styles when app loaded first time.

**Comment by alexeygorbachevskiy** [comment] 2023-07-11 05:21
@balazsorban44

**Comment by alexeygorbachevskiy** [comment] 2023-07-11 09:42
The issue is being reproduced when `export const runtime = "edge";` is set for page where `Header`  noted above used.

**Comment by balazsorban44** [comment] 2023-07-11 11:18
Please still add a complete (but minimal) reproduction. :pray:

```ts
import LogoIcon from "icons/logo.svg";
import { Pages } from "constants/pages";
import styles from "./styles/header.module.scss";
```

Would like to know what these imports look like, and if you have any `next.config.js`. Here is a template to get you started: https://github.com/vercel/next.js/tree/canary/examples/reproduction-template-app-dir

**Comment by alexeygorbachevskiy** [comment] 2023-07-11 12:45
Are u really? Did you even try? I have reproduced it with repo u provided in 3 minutes.

Just put

Full info:

layout.tsx
![image](https://github.com/vercel/next.js/assets/37103509/e4a2598c-ccb3-4ae2-a711-ae37bcc577f4)
Header.tsx
![image](https://github.com/vercel/next.js/assets/37103509/786d4643-685f-43af-a743-8b3f031d8eb8)
main page.tsx
![image](https://github.com/vercel/next.js/assets/37103509/2b5856b4-cb19-4ac9-92e1-dcfc6df48fb9)
home2/page.tsx
![image](https://github.com/vercel/next.js/assets/37103509/1481d1b0-4ab9-44a4-9256-9c673ec87030)

Actual Result:
![image](https://github.com/vercel/next.js/assets/37103509/834d8b23-e3d2-4312-b856-3b3bf5736838)

Expected result: "Issue" text should have red color when we visit home "/" page first time

**Comment by yashchaddha** [comment] 2023-07-11 17:05
Hi @alexeygorbachevskiy Can i please get assigned to this issue as I would like to contribute on this

**Comment by alexeygorbachevskiy** [comment] 2023-07-12 03:13
@yashchaddha Try asking @balazsorban44  cause i'm not a maintainer

**Comment by shuding** [comment] 2023-07-12 15:04
@yashchaddha feel free to open a PR for it! 💪

**Comment by icyJoseph** [comment] 2023-07-12 17:37
Well, I can't reproduce this :( 

Home page:

```tsx
export const runtime = "edge";

export default function Home() {
  return <h1>Home</h1>;
}

```

Header Component:

```tsx
"use client";

import { usePathname } from "next/navigation";

export function Header() {
  const pathname = usePathname();

  return <header className={pathname === "/" ? "red" : "green"}>hello</header>;
}

```

and layout:

```tsx
import { Header } from "./Header";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
```

It works fine in dev and prod builds, with next@13.4.9

**Comment by alexeygorbachevskiy** [comment] 2023-07-13 02:42
@icyJoseph **Are you kidding?** 
Doesn't this line bother you? -> `<header className={pathname === "/" ? "red" : "green"}>hello</header>;`

You should do:
<header style={{color: pathname === "/" ? "red" : "green"}}>hello</header>;  or
<header className={pathname === "/" ? styles.red : styles.green}>hello</header>, but not like you did.

**Comment by icyJoseph** [comment] 2023-07-13 05:21
No sir, I am not kidding, I am genuinely trying to reproduce this. 

https://github.com/vercel/next.js/assets/21013447/50e24a5b-bdfc-4b94-b969-44fae0ea1d3f

Could you please provide a repository? I have also tried with node 16, and still no issue.

I had initially suspected that the CSS module hash was not matching up when rendering on the edge, but your screenshots seem to suggest that the style prop also triggers it for you, so that would discard the CSS module hash.

Are there any other assumptions we could be leaving out?

**Comment by alexeygorbachevskiy** [comment] 2023-07-13 07:32
@icyJoseph Can u check on Windows?

**Comment by icyJoseph** [comment] 2023-07-13 07:49
Yeah I can, but I'm not at home now. If I get time later today I'll give it a go with Windows and Linux. 

This makes it even more important to have a reproduction repository that we can easily clone and start in various systems. If it's windows specific it might be harder to fix than I initially thought 🤔

**Comment by alexeygorbachevskiy** [comment] 2023-08-24 09:41
@icyJoseph Any updates? It seems the issue is being reproduced  even without "edge" runtime in 13.4.16 version and later.

**Comment by icyJoseph** [comment] 2023-08-24 09:54
@alexeygorbachevskiy sorry mate, I've been really busy these weeks. Did you ever try changing Node JS version? Like higher than 18.16

**Comment by michal-th** [comment] 2023-08-28 07:32
I'm facing same errors using `const pathname = usePathname();` to style active menu item in a client component.  If this is intentional, what should be the correct approach to this?

**Closed** 2023-10-20 21:20 UTC
Labels: please add a complete reproduction, template: bug, type: needs triage
