### ISSUE TITLE
exporting a page with getStaticProps does not get exported

### ISSUE THREAD

**Issue by yans** [vercel/next.js#17356] opened 2020-09-25 08:17 UTC
# Bug report

## Describe the bug

App has 2 routes and 1 page
- `/` serves the home page
- `/about/` serves the home page, but at the `/about/` route

#### Folder Structure
```
│─ package.json
│─ next.config.js
│─ build/
│  │─ ... (see below)
│─ pages/
│  │─ index.js
```

#### `next.config.js`
```
module.exports = {
  trailingSlash: true,
  exportPathMap: async () => {
    return {
      "/": { page: "/" },
      "/about": { page: "/" },
      "/about/test": { page: "/about/test" },
    };
  },
};
```

#### `pages/index.js`
```
import React from "react";

export default function Home(props) {
  return <div>root {props.title}</div>;
}

export async function getStaticProps() {
  return {
    props: {
      title: "hi",
    },
  };
}
```

### THE BUG

When the `getStaticProps` is **present** in `pages/index.js` the build output **omits** the `build/about/index.html` file:
```
build/
│─ index.html
```

When the `getStaticProps` is **not present** in `pages/index.js` the build output **includes** the `build/about/index.html` file:
```
build/
│─ index.html
│─ about/
│  │─ index.html
```

This interaction between `getStaticProps` and `exportPathMap` isn't mentioned on any of the relevant documentation pages [here](https://nextjs.org/docs/advanced-features/static-html-export), [here](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation), or [here](https://nextjs.org/docs/api-reference/next.config.js/exportPathMap) leads me to believe it's a bug. 

The adding `trailingSlash: true` or the deprecated `exportTrailingSlash: true` (or both) doesn't fix the issue, which leads me to believe it's related to but not a duplicate of [this issue](https://github.com/vercel/next.js/issues/15315)

## Expected behavior

I don't think the presence of `getStaticProps` should prevent the page from being exported. I think in both cases the final build output should either include or exclude `about/index.html`, irregardless of whether `getStaticProps` is present in `pages/index.js`.

## System information

- Version of Next.js: `9.5.3`
- Version of Node.js: `10.15.3`

**Comment by yans** [comment] 2020-09-25 08:26
i have a reproduction of the issue here: https://github.com/yans/next-issue-17356

**Comment by rawat07102** [comment] 2020-10-05 05:21
in your next.config.js your "about" page is linked to { page: "/" }

**Comment by ijjk** [comment] 2020-12-01 21:57
Hi, this does appear to be a duplicate of https://github.com/vercel/next.js/issues/15315 as they both relate to attempting to override `getStaticProps` paths with `exportPathMap`. I'm going to close this in favor of the previous issue

**Closed by ijjk** 2020-12-01 21:57 UTC
Labels: good first issue, kind: bug, type: next

**Comment by balazsorban44** [comment] 2022-01-29 02:12
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
