### ISSUE TITLE
Error: invariant: dynamic responses cannot be unchunked

### ISSUE THREAD

**Issue by todorpopov93** [vercel/next.js#45509] opened 2023-02-02 06:32 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

A next 13 production build hosted on GCP Kubernetes

### Link to the code that reproduces this issue

it's a private repository and I cannot share the code. I think it should be easily reproducible

### To Reproduce

Just run the latest Nextjs 13 on production

### Describe the Bug

Hello,

I have recently installed the latest next 13 ("next": "13.1.4"), and ran it on production (despite being experimental yet) and started receiving occasional error logs on the server side. However, the web app itself loads properly and everything works normally so far (2 days up time on production).

Here is the error:

`Error: invariant: dynamic responses cannot be unchunked. This is a bug in Next.js at RenderResult.toUnchunkedString (/usr/src/app/node_modules/next/dist/server/render-result.js:16:19) at /usr/src/app/node_modules/next/dist/server/response-cache/index.js:103:57 at processTicksAndRejections (node:internal/process/task_queues:96:5)`

### Expected Behavior

Not to have this bug log in Next 13 I suppose

**Comment by itsuki0927** [comment] 2023-02-11 16:02
+1

**Comment by Arctomachine** [comment] 2023-02-24 21:07
Encountered this issue at 13.0.6. Other than getting it seemingly randomly, one situation where it was triggered is running online schema validator

**Comment by Clarity-89** [comment] 2023-03-07 07:23
Happened to me as well, with app directory enabled. Seems like it was caused by another error, in this case I was desctructuring `const post = allPosts.find((p) => p.id === id)`, where `post` was occasionally undefined. Fixing that error also removed the `dynamic responses cannot be unchunked` error, so I'd suggest to check if you have any other errors in your app that may cause this.

**Comment by thevuong** [comment] 2023-03-13 15:05
I also get the same error when I upgrade to version `13.2.4`, in version `13.2.3` I don't get that error.

**Comment by Arctomachine** [comment] 2023-03-14 00:21
Since you figured out how it is triggered, did you perhaps find severity of this bug? Does it make something work worse or does it just leave error in log without breaking anything (requesting bot included)?

**Comment by todorpopov93** [comment] 2023-03-16 06:32
> 

would try this out with the versions and will leave feedback here if it worked for me. Thank you!

**Comment by todorpopov93** [comment] 2023-03-16 06:39
> Happened to me as well, with app directory enabled. Seems like it was caused by another error, in this case I was desctructuring `const post = allPosts.find((p) => p.id === id)`, where `post` was occasionally undefined. Fixing that error also removed the `dynamic responses cannot be unchunked` error, so I'd suggest to check if you have any other errors in your app that may cause this.
> 
> **Edit**: Nevermind, seems like error still appears randomly on production. Started happening after upgrading to Next.js 13.2.3 and switching to app directory.

the problem is that for me it's happening since 13.1.4, but that was the first version that I did try and also ran on prodution, so it might be occurring from even earlier versions. And the worst is that I cannot give any steps to reproduce it, as I haven't done anything special.. having 1 page, 1 fetch and react components loaded is something that I don't think has anything special on it..
I think the issue lies somewhere within nextjs package itself, but it's not specific/not detailed and can't understand how to have it fixed (if possible at all).

**Comment by todorpopov93** [comment] 2023-03-16 06:39
> I also get the same error when I upgrade to version `13.2.4`, in version `13.2.3` I don't get that error.


I would try this out with increasing my version to 13.2.3 and will leave feedback here if it worked for me. Thank you!

**Comment by davidbnk** [comment] 2023-03-30 01:31
I'm experiencing this in production as well, next v13.2.4
Have no clue how to reproduce it because I never saw it during dev and there is no useful information in the error message

**Comment by Arctomachine** [comment] 2023-04-12 13:56
Still happens in 13.3. This error makes up most of production logs, being outputed regularly.
Is there relation to hosting type? In my case server is self hosted on vps.

**Comment by PassTheMayo** [comment] 2023-05-10 14:26
This error is still happening on NextJS 13.4.1. I'm currently using the app directory without Turbo if that helps at all.

![image](https://github.com/vercel/next.js/assets/16949253/debacb77-11f6-4e81-b92f-e3a2f493b3cd)

**Comment by somersby10ml** [comment] 2023-05-16 11:47
next 13.4.1 AppRouter is in use and

yarn build` -> `yarn start ` 

After a few hours or days, you will see an error and the
server is not working.

```
Error: invariant: dynamic responses cannot be unchunked. This is a bug in Next.js
node_modules\next\dist\server\response-cache\index.js:119:57
node_modules\next\dist\server\render-result.js:28:19
```

**Comment by nithin-murali-arch** [comment] 2023-05-17 06:14
I was using a custom server implementation, where I use app.renderToHTML. This causes the issue for me.

**Comment by cloetensbrecht** [comment] 2023-06-07 08:50
We're getting the same issue in v 13.4.4 with AppRouter.
The website works fine, but the error log is full of these types of errors.
The server is a Windows server running PM2.
```
Error: invariant: dynamic responses cannot be unchunked. This is a bug in Next.js
	at RenderResult.toUnchunkedString (C:\wwwNodeJs\*****\node_modules\next\dist\server\render-result.js:28:19)
	at C:\wwwNodeJs\*****\node_modules\next\dist\server\response-cache\index.js:119:57
```

In `node_modules\next\dist\server\render-result.js`:
```
toUnchunkedString() {
	if (typeof this._result !== "string") {
		throw new Error("invariant: dynamic responses cannot be unchunked. This is a bug in Next.js");
	}
	return this._result;
}
```
https://github.com/vercel/next.js/blob/e4b230677c24744ff2a2253a475d271c38d1443f/packages/next/src/server/render-result.ts#L49

**Comment by AGalbe** [comment] 2023-06-23 23:22
> We're getting the same issue in v 13.4.4 with AppRouter. The website works fine, but the error log is full of these types of errors. The server is a Windows server running PM2.
> 
> ```
> Error: invariant: dynamic responses cannot be unchunked. This is a bug in Next.js
> 	at RenderResult.toUnchunkedString (C:\wwwNodeJs\*****\node_modules\next\dist\server\render-result.js:28:19)
> 	at C:\wwwNodeJs\*****\node_modules\next\dist\server\response-cache\index.js:119:57
> ```
> 
> In `node_modules\next\dist\server\render-result.js`:
> 
> ```
> toUnchunkedString() {
> 	if (typeof this._result !== "string") {
> 		throw new Error("invariant: dynamic responses cannot be unchunked. This is a bug in Next.js");
> 	}
> 	return this._result;
> }
> ```
> 
> https://github.com/vercel/next.js/blob/e4b230677c24744ff2a2253a475d271c38d1443f/packages/next/src/server/render-result.ts#L49

I'm getting the same error v 13.4.4. Did you solve it? Thanks!

**Comment by charnog** [comment] 2023-07-13 20:11
Was resolved in https://github.com/vercel/next.js/pull/52581

**Comment by balazsorban44** [comment] 2023-10-20 21:03
Closing as per the above comment. Feel free to reopen with a new reproduction if you are still seeing this!

**Closed by balazsorban44** 2023-10-20 21:03 UTC
Labels: please add a complete reproduction, template: bug, type: needs triage
