### ISSUE TITLE
CSS order of bootstrap.css+globals.css changed in PRODUCTION in VERCEL server after upgrade to v12 

### ISSUE THREAD

**Issue by heylols** [vercel/next.js#34264] opened 2022-02-12 12:26 UTC
### Run `next info` (available from version 12.0.8 and up)

'pnpm' is not recognized as an internal or external command,
operable program or batch file.

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 14.17.3
      npm: 6.14.8
      Yarn: 1.22.0
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12

### What version of Node.js are you using?

14.17.3

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

Today upgraded the NextJS version from v11 to v12. When tested in development mode, it is working fine. But when pushed to Vercel (production), the Bootstrap CSS is overriding the globals.css.

This is how am using in **_app.js** file:
```
import 'bootstrap/dist/css/bootstrap.min.css';  //-- for Bootstrap to work
import '../styles/globals.css'

//.....
```

The CSS rules defined in my **globals.css** file is overriden by the **bootstrap.min.css**. Before the upgradation to v12, it was working fine in PRODUCTION.
It seems to be an issue happening with the minification or something.

I tried updating the **ReactBootstrap** also. But it didn't worked. And tried adding `swcMinify: true,` in **next.config.css** and still not working.

Dependencies are as follows:

```
    "@algolia/autocomplete-js": "^1.5.1",
    "@auth0/nextjs-auth0": "^1.3.1",
    "@bigcommerce/storefront-data-hooks": "^1.7.0",
    "@contentful/rich-text-plain-text-renderer": "^15.1.0",
    "@contentful/rich-text-react-renderer": "^15.0.0",
    "@googlemaps/js-api-loader": "^1.12.11",
    "@mailchimp/mailchimp_marketing": "^3.0.56",
    "@sendgrid/mail": "^7.4.7",
    "@vercel/fetch": "^6.1.1",
    "algoliasearch": "^4.12.0",
    "bootstrap": "5.1.3",
    "card-validator": "^8.1.1",
    "country-state-city": "^3.0.1",
    "date-fns": "^2.25.0",
    "graphql": "^15.5.1",
    "graphql-request": "^3.4.0",
    "js-base64": "^3.6.1",
    "jsonwebtoken": "^8.5.1",
    "mongoose": "^6.0.10",
    "next": "12",
    "next-auth": "^4.0.0-beta.2",
    "next-seo": "^4.26.0",
    "nextjs-progressbar": "^0.0.13",
    "nookies": "^2.5.2",
    "react": "^17.0.2",
    "react-bootstrap": "^2.1.2",
    "react-dom": "^17.0.2",
    "react-elastic-carousel": "^0.11.5",
    "react-infinite-scroll-component": "^6.1.0",
    "react-instantsearch-dom": "^6.21.1",
    "react-items-carousel": "^2.8.0",
    "react-masonry-css": "^1.0.16",
    "react-slick": "^0.28.1",
    "styled-components": "^5.3.3",
    "swr": "^1.0.1",
    "twilio": "^3.73.1",
    "uuid": "^8.3.2",
    "video.js": "^7.14.3"
```

**But when I downgraded to v11, it is working fine!!**

### Expected Behavior

The CSS rules defined in **globals.css** file should override the **bootstrap.min.css**.

### To Reproduce

Install the ReactBootstrap in your NextJS v12 project:

`npm install react-bootstrap bootstrap@5.1.3`

And in the _app.js file, try importing the CSS like this:

```
import 'bootstrap/dist/css/bootstrap.min.css'; 
import '../styles/globals.css'

```

Check whether the body style that you wrote in `/styles/globals.css` is overriding the one in `bootstrap.min.css`

**Comment by balazsorban44** [comment] 2022-02-12 12:53
Duplicate of #16630

**Closed by balazsorban44** 2022-02-12 12:53 UTC
Labels: template: bug

**Comment by heylols** [comment] 2022-02-12 12:56
@balazsorban44 what's the solution to this issue? It's URGENT. I do not want to use **!important** to override

**Comment by balazsorban44** [comment] 2022-02-12 14:27
It's being actively worked on https://github.com/vercel/next.js/issues/16630#issuecomment-1017322345
