### ISSUE TITLE
Dynamic routing with prefix

### ISSUE THREAD

**Issue by bamzi** [vercel/next.js#17132] opened 2020-09-16 04:47 UTC
# Feature request

we have a problem where we want to keep almost everything at the top level while support different dynamic routes with constant prefixes as differentiator. For example we have one route `example.com/@username` where `@` is a constant prefix and also another route `example.com/[123_post_id] where the prefix  is `123_` ... but  `[@username].tsx` is not different from `[123_post_id].tsx` 

I understand we can put them into different folders and manage but the above is just an example and our application behaviour is based on `prefixes` and everything being at the top level

## Describe the solution you'd like

Ideally ability to add some sort of prefix to dynamic routing file names. i.e. `[@:username]` where `@` is a prefix and `username` is the parameter ... another design solution might be `[<@>username]` or `[username<@>]` where `@` is a required fixed constant but can be placed anywhere [far more complex in implementation than prefixes]

## Describe alternatives you've considered

- For now the native solution of `/profile/[username]/...` seems like the only option
- Introducing a route manager to handle this situation
- reverse proxy

**Comment by rubybb** [comment] 2020-09-16 17:26
I was just about to make an issue for this, for the exact same use case.

**Comment by timneutkens** [comment] 2020-09-17 09:15
> for some reason, you can't use rewrites with statically optimized pages, so I had to just use it as an external page.

Make sure you're on the latest version of Next.js as there have been improvements to rewrites recently 👍 

Going to close this as a duplicate of #12051 as it's basically the same issue, however `rewrites` should be enough for your use-case, they're applied client-side as well.

**Comment by timneutkens** [comment] 2020-09-17 09:15
Duplicate of #12051

**Closed by timneutkens** 2020-09-17 09:15 UTC

**Comment by bamzi** [comment] 2020-09-17 16:35
This issue / feature request needs to be reopened. It was prematurely closed without addressing the actual request.

"rewrite" function DOES NOT work to address the request. Please read more carefully before jumping into conclusion.

rewrite rule barely works with code below: `example.com/@username`

The following case doesn't work:
`example.com/@username/about` <- 404 not found
but this works: `example.com/u/:username`

*** If the above case "should work" but it's not, then that's a bug that needs to be addressed

```js
module.exports = {
	async rewrites() {
		return [
			{
			       // The only things that works but not what we want!!!
				source: '/@:username',
				destination: '/u/:username',
			},
			// BUT none of these work:
			//{
			//	source: '/@:username*',
			//	destination: '/u/:username*',
			//  --> `example.com/@username/about` <- 404 not found
			//},
			// {
			// 	source: '/@:username((?!.*..)(?!.*.$)[^W][w.]{0,29})*', <- 404 not found
			// 	destination: '/u/:username*',
			// },
			// {
			// 	source: '/:username(@(?!.*..)(?!.*.$)[^W][w.]{0,29})*', <- 404 not found
			// 	destination: '/u/:username*',
			// },
		];
	},
};
```

**Comment by tsejerome** [comment] 2022-01-12 07:13
AGree with @bamzi, Rewrite technically does not provide the same outcome. The fix at https://github.com/vercel/next.js/issues/12051 will actually badly affects the SEO performance (which was part of the reason to use SSR instead of just React)

**Comment by balazsorban44** [comment] 2022-02-11 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
