### ISSUE TITLE
[Next 10] TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Location"]

### ISSUE THREAD

**Issue by eduludi** [vercel/next.js#24497] opened 2021-04-27 08:02 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

15.11.0

### What browser are you using?

Chrome, Safari, Firefox

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

When a page url has a trailing slash and a query string that includes an invalid non-ASCII character in the _key_ part of one of the parameters, the server throws a 500 error:

```
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Location"]
```

Looks like this may be related to  issue #17907

### Expected Behavior

The same behavior as when there is no trailing slash.

### To Reproduce

Access any page url with:
- a trailing slash, `(example.com/about/)`
- **and** a non-ASCII char in the key part of query param `(example.com/about/?invalid%E2%80%A6)` (`%E2%80%A6` is an ellipsis char).

> Note: `trailingSlash` is **not** set to `true` in `next.config.js`

Here is a codesandbox to reproduce this issue:
https://codesandbox.io/s/nextjs-bug-errinvalidchar-invalid-character-in-header-content-location-ukhrh

**Comment by ijjk** [comment] 2021-04-28 01:15
Closing as a duplicate of https://github.com/vercel/next.js/issues/24047

**Closed by ijjk** 2021-04-28 01:15 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
