### ISSUE TITLE
Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by srikanth912** [vercel/next.js#13479] opened 2020-05-28 03:35 UTC
# Bug report

## Missing dependency (maybe)?

After upgrading from 9.4.2 to 9.4.3, npm run dev throws an error "Cannot find module 'fs-extra'"

## To Reproduce

Upgrade project from 9.4.2 to 9.4.3 or just create a new next app using "npx create-next-app" and run _npm run dev._ (Verified on Ubuntu 18.04 with Node 12.16.3)

## Expected behavior

Expect it to start the server, rather it shows module not found error. 

## System information

- OS: Ubuntu 18.04
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: 9.4.3
- Version of Node.js: v12.16.3

## Additional context

Happens on new projects as well as existing projects. For now, I've installed fs-extra separately and it seems to be working fine.

**Comment by Timer** [comment] 2020-05-28 03:44
Thanks for the report! Fixing immediately.

**Comment by Timer** [comment] 2020-05-28 03:45
Landed in #13481, cutting a canary and getting a stable out ASAP.

**Comment by elvisduru** [comment] 2020-05-28 04:05
Yeah, I still get the same error

**Comment by sebazelonka** [comment] 2020-05-28 04:27
hey @Timer, I'm starting a project right now and I found this issue too. 
Should I wait to have the latest version with this fix or I can start with canary?

**Comment by Timer** [comment] 2020-05-28 04:29
Try again with `create-next-app` or upgrade to `next@9.4.4` please!

**Comment by sebazelonka** [comment] 2020-05-28 04:31
It works, thank you!

**Comment by Timer** [comment] 2020-05-28 04:35
Closing, sorry about this!

**Closed by Timer** 2020-05-28 04:35 UTC

**Comment by balazsorban44** [comment] 2022-01-30 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
