### ISSUE TITLE
Can't load internationalized page with custom query params

### ISSUE THREAD

**Issue by wadehammes** [vercel/next.js#19211] opened 2020-11-16 16:20 UTC
# Bug report

## Describe the bug

Visiting a localized page with query params fails to load, giving the "href and as mismatch error" (see screenshot below). Without the query params, the page loads fine.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. have internalization set up with two or more locales
2. visit a localized link with attached query params (they could be anything)

Assuming this has something to do with https://github.com/vercel/next.js/pull/17872

## Expected behavior
Params would be passed to the localized page without failure.

## Screenshots

Working without query parms:
![image](https://user-images.githubusercontent.com/222170/99278613-456e5580-27fd-11eb-9af9-b7b7f8199f4d.png)

Error with query params:
![image](https://user-images.githubusercontent.com/222170/99278663-5b7c1600-27fd-11eb-8efc-27f920b7fe5d.png)

## System information

- OS: [e.g. Windows]
- Browser (if applies): Edge
- Version of Next.js: [e.g. 10.0.1]
- Version of Node.js: [e.g. 14.8.0]

**Comment by timneutkens** [comment] 2020-11-17 12:57
Haven't verified but marked tihs issue for investigation.

**Comment by wadehammes** [comment] 2020-11-17 13:02
@timneutkens was able to confirm this is only happening in dev mode (`npm run dev`). Once I published the branch to our staging Vercel instance this issue didn’t persist and the params were passed correctly through route changes.  

Still, this issue in dev mode is problematic for testing but at least we can ship production without needing an immediate hot fix.

**Comment by mattboon** [comment] 2020-11-18 13:37
Experiencing this behaviour too, again only in Development mode

**Comment by kivohin** [comment] 2020-11-19 02:58
I can confirm this happens to me too on `localhost` when running `npm run dev`.

But it happens on the `non` defaultLocale pages, i.e `localhost:3000/fr/about`. The defaultLocale pages work fine with query parameters.

Also the error I am getting is a bit different:
<img width="967" alt="Screen Shot 2020-11-18 at 9 55 43 PM" src="https://user-images.githubusercontent.com/17774060/99615203-fa189a80-29e8-11eb-9eca-e4b57a6d2e64.png">


### System information
OS: macOS 10.15.6
Browser: Google Chrome 86.0.4240.80
Version of Next.js: 10.0.2 (stable)
Version of Node.js: 12.16.3

**Comment by ijjk** [comment] 2020-12-22 04:02
Hi, this appears to be fixed in the latest canary of Next.js `v10.0.4-canary.9`, please upgrade and give it a try!

**Closed** 2020-12-22 13:10 UTC
Labels: kind: bug, point: 2, type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-29 00:11
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
