### ISSUE TITLE
getServerSideProps runs twice with data lost [query, params] etc

### ISSUE THREAD

**Issue by djleonskennedy** [vercel/next.js#27305] opened 2021-07-19 19:57 UTC
### What version of Next.js are you using?

10.0.9 - 11+

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

Windows, Mac

### How are you deploying your application?

Yes

### Describe the Bug

Hi there!

When we're querying a page with `getServerSideProps`  with query parameters and dynamic routes (or without if prod see related issues), next call `getServerSideProps`  twice and on second attempt, next is `loosing all data about query parameters or path params`. May be it is calling with another context second time

In my project it can be reproduced on prod only! However i've found good repo to reproduce https://github.com/johnruane/dynamic-route-test here you can check it even in `dev` mode.

Related: 
https://github.com/FormidableLabs/react-progressive-image/issues/34
https://github.com/vercel/next.js/discussions/13064

Issue is `critical` for my project, if you'd suggest some workaround i'll be very thankfull!

BR Yuriy

### Expected Behavior

`getServerSideProps` should no be called twice or should not lost query/path parameters from it's context

### To Reproduce

clone: https://github.com/johnruane/dynamic-route-test

```
git clone git@github.com:johnruane/dynamic-route-test.git
cd dynamic-route-test 
yarn
yarn dev
```

- open `chrome`: `http://localhost:3000`
- search something in dynamic input

![image](https://user-images.githubusercontent.com/8366455/126218175-36a10135-6031-45a6-a884-a9d857411cde.png)

that you can see log on server:

![image](https://user-images.githubusercontent.com/8366455/126218359-30fcf48c-d178-44f6-91c6-6f8cc82f4810.png)

**Comment by ijjk** [comment] 2021-07-19 20:30
Hi, it looks like `src` isn't being set on `react-progressive-image` [here](https://github.com/johnruane/dynamic-route-test/blob/d23ca828bff93431ea5addb809a8d94b8a248a6a/pages/dynamic/%5B...search%5D.js#L14) causing it to attempt fetching the current path with an undefined value. Setting the image's URL on the `src` prop there seems to resolve it. 

I'm going to close this since it doesn't appear to be a Next.js issue.

**Closed by ijjk** 2021-07-19 20:30 UTC
Labels: template: bug

**Comment by djleonskennedy** [comment] 2021-07-19 21:16
@ijjk a bit unclear how can it affect on `getServerSideProps` calls? Could you explain please, may be it will help to resolve such behavior on my project

**Comment by ijjk** [comment] 2021-07-19 21:21
`getServerSideProps` is called every-time `/dynamic/<some-value>` is called, the `react-progressive-image` component was causing a request to be done to `/dynamic/undefined` so `getServerSideProps` was called.

**Comment by djleonskennedy** [comment] 2021-07-19 21:29
@ijjk now i see, thank you

**Comment by balazsorban44** [comment] 2022-01-28 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
