### ISSUE TITLE
bug: dynamic path segment with %25 crashes page

### ISSUE THREAD

**Issue by lucacasonato** [vercel/next.js#15523] opened 2020-07-27 15:28 UTC
# Bug report

## Describe the bug

When `%25` is included in a dynamic path segment (e.g. `/%25` with page `pages/[id].js`) server and client both panic with the error `Error: failed to decode param`.

## To Reproduce

1. Create a page at `/[id].js`
2. `yarn dev`
3. Go to `http://localhost:3000/%25`
4. See unhandled error message

## Expected behavior

I expect no error. It looks like next.js is recursively checking the path segment, and as `%25` resolves to `%`, in a second pass the lone `%` is causing issues.

## System information

- OS: Linux, Ubuntu 20.04
- Browser: Chrome
- Version of Next.js: 9.4.4
- Version of Node.js: v12.14.1

**Comment by Timer** [comment] 2020-07-27 15:35
This is fixed in Next.js 9.5 which is being released to npm ATM!

**Closed by Timer** 2020-07-27 15:35 UTC

**Comment by lucacasonato** [comment] 2020-07-27 15:42
Great, thanks a lot for this awesome tool!

**Comment by balazsorban44** [comment] 2022-01-29 20:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
