### ISSUE TITLE
css minification breaks calc with multiplication

### ISSUE THREAD

**Issue by cevr** [vercel/next.js#17350] opened 2020-09-25 02:07 UTC
# Bug report

## Describe the bug

```css
calc(
    100vh -
      (
        var(--nav-height) + var(--footer-height) + (var(--vertical-padding) * 2) +
          (var(--grid-gap) * 2)
      )
  );
```

Is minified to 
```css
calc(100vh - var(--nav-height) + var(--footer-height) + var(--vertical-padding)*2 - var(--grid-gap)*2)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

- 1: clone https://github.com/cevr/me
- 2: look at Layout.module.css in `src/layouts` line 5
- 3: build
- 4: start
- 5: Inspect first div inside _next
- 6:  `--min-content` has incorrect calc
- 7: copy Layout.module.css line 5 calc
- 8: paste into `--min-content`
- 9: observe correct page layout

## Expected behavior

multiplication expressions should not be minified within css

## System information

- OS: macos
- Browser (if applies) chrome
- Version of Next.js: 9.3.3
- Version of Node.js: 14.12.0

**Comment by awareness481** [comment] 2020-09-26 06:09
Likely related to https://github.com/vercel/next.js/issues/17066

**Comment by timneutkens** [comment] 2020-09-28 07:25
Duplicate of #17066

**Closed by timneutkens** 2020-09-28 07:25 UTC

**Comment by balazsorban44** [comment] 2022-01-29 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
