### ISSUE TITLE
Add option to opt-in to swc even in the presence of a bable file

### ISSUE THREAD

**Issue by erikbrinkman** [vercel/next.js#36763] opened 2022-05-09 03:15 UTC
### Describe the feature you'd like to request

I want to be able to opt into to SWC processing, even if there's a babel file. In this case, I use bable for other tools, which are also difficult to configure, but I would like to use SWC with next.

This was already asked here #36590 which was moved to discussion, but the end result is that it needs to be a feature request.

### Describe the solution you'd like

The fix should be pretty easy. It seems like the relevant line is here:
https://github.com/vercel/next.js/blob/44f436b91b9201696c59754d4394f91dcdf77999/packages/next/build/webpack-config.ts#L415
and all that would need to change is to patch it to be
```ts
let useSWCLoader = !babelConfigFile || config.experimental.forceSwc // or some other name
```

I could submit a PR but I wanted to make sure it was desired. Also I'm not super clear on the process for adding a new config option, but I imagine it's just tweaking this file:
https://github.com/vercel/next.js/blob/e8a8220d49434021f2fb9975a6ec7081043b97b4/packages/next/server/config-shared.ts#L81

### Describe alternatives you've considered

It doesn't seem possible to change this otherwise so the alternative would be to configure the other tools to use non-standard babel paths, which is not really how babel seems designed.

**Comment by balazsorban44** [comment] 2022-05-09 09:00
Hi, feature requests like this are moved to discussions by default (this is explained in our [contributing document](https://github.com/vercel/next.js/blob/canary/contributing.md#triaging)).

So this sounds like a duplicate of #36590. Please consider adding your use case to that discussion, and upvote it instead. :+1:

As a workaround, if you don't use Babel for the Next.js build process, you can rename the Babel config file right before running `next build` and then rename it back if it was successful.

**Closed by balazsorban44** 2022-05-09 09:00 UTC
Labels: template: story

**Comment by erikbrinkman** [comment] 2022-05-09 14:16
@balazsorban44 Sorry for not reading the contributing document clearly. I mainly opened this request to solicit feedback from maintainers if a PR related to this would be accepted, not just to open discussion about when it would be useful.

As a side note: the moving practice does work, and was something I also tried, but it also has to be moved for dev and other features, and then there's a synchronicity issue. All of this could be added to the discussion, but again, the point was more to inquire if a PR would be accepted.
