### ISSUE TITLE
i18n subroutes and rewrites not working in dev

### ISSUE THREAD

**Issue by JohnPhoto** [vercel/next.js#18335] opened 2020-10-27 20:34 UTC
# Bug report

## Describe the bug

When combining new i18n subroutes and rewrites in development mode the rewrite-paths does not work.

## To Reproduce
* Clone and npm install: [https://github.com/JohnPhoto/next-rewrites](https://github.com/JohnPhoto/next-rewrites)
* `npm run dev`
* navigate to [http://localhost:3000/hej](http://localhost:3000/hej) or [http://localhost:3000/sv/hej](http://localhost:3000/sv/hej)
* See the `404`

(Now do the same after `npm run build && npm run start` to see that the page(s) exist as expected)

To lazy to clone? boils down to this config:
```js
module.exports = {
  i18n: {
    locales: ['en', 'sv'],
    defaultLocale: 'sv',
  },
  async redirects() {
    return [
      {
        source: `/_next/data/:deployment/hej.json`,
        destination: `/_next/data/:deployment/sv/hello.json`,
        permanent: true,
      }

    ];
  },
  async rewrites() {
    return [
      {
        source: '/hej',
        destination: '/sv/hello',
      }
    ];
  },
};
```

## Expected behavior

The page named `/hello` should be shown for `sv` locale.

## System information

- OS: macOS
- Browser (if applies) chrome
- Version of Next.js: 10.0.0
- Version of Node.js: v12.19.0

**Comment by Timer** [comment] 2020-10-30 19:00
Can you please try `next@canary` and see if it's fixed?

**Comment by JohnPhoto** [comment] 2020-10-30 19:21
Sadly it did not help. (Updated example repo for "proof").

**Comment by johnrackles** [comment] 2020-11-05 09:04
I've had the same problem but with a rewrite to an external route. Uncommenting the i18n line in the config fixes this. An update to canary did sadly not.

Anything I can do to help here?

**Comment by JohnPhoto** [comment] 2020-11-14 22:28
Further investigation sugests that the prod version does not in fact work properly either, (but I am not sure what the reasoning behind this is).

If I use the default `next/link` (with the non-translated paths) to navigate between pages the client-side-only navigation (basically the SPA) works as intended. But when I am using a custom link which is translations-aware and replaces the paths with the translated ones the browser does a full non-pushState navigation and I loose clientside contexts/state (data stored in 
hooks etc) etc.

**Comment by lipoolock** [comment] 2020-11-26 08:49
Hi 
I spotted a similar issue with redirects or rewrites + i18n
I wrote a post in "Discussions" but no reactions 
Perhaps my sample could help about your issue too
https://github.com/vercel/next.js/discussions/19482

**Comment by kivohin** [comment] 2020-11-30 19:59
This bug report is exactly the same or strongly related to the one I reported here:
https://github.com/vercel/next.js/issues/19227

Similar issue, plus includes an additional issue when deployed on Vercel Now.

Also I prepared a demo repository in which you can reproduce the errors, and play with the next.config.js to see the effects:
https://github.com/kivohin/i18n-routing-rewrites-vercel-now

**Comment by dennispassway** [comment] 2020-12-08 09:25
We have a similair issue that I described in a discussion.
Maybe it could help you find the problem:
https://github.com/vercel/next.js/discussions/19707

**Comment by JackOddy** [comment] 2020-12-18 15:26
I have also come across this issue and haven't been able to come up with a work around

bump for a fix

**Comment by ijjk** [comment] 2020-12-29 06:07
Hi, the rewrites + i18n support has been updated in the latest version of Next.js `v10.0.5-canary.3` with updated documentation available here https://nextjs.org/docs/api-reference/next.config.js/rewrites#rewrites-with-i18n-support

I'm going to close this since similar issues related to this have been resolved, if anyone is still encountering issues with this please provide an updated minimal reproduction and we can investigate further!

**Closed by ijjk** 2020-12-29 06:07 UTC
Labels: kind: bug, point: 3

**Comment by balazsorban44** [comment] 2022-01-29 00:11
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
