### ISSUE TITLE
Automatic static optimization indicator navigates to the wrong page

### ISSUE THREAD

**Issue by ivoelbert** [vercel/next.js#15445] opened 2020-07-23 21:54 UTC
# Bug report

Automatic static optimization indicator navigates to the wrong page

## Describe the bug

The automatic static optimization indicator navigates to `https://nextjs.org/docs#automatic-static-optimization-indicator`. However, that link takes you to the Getting Started page.

I think that the correct link should be `https://nextjs.org/docs/api-reference/next.config.js/static-optimization-indicator` or `https://nextjs.org/docs/advanced-features/automatic-static-optimization`

## To Reproduce

1. Create a new Next App with a single page, without `getServerSideProps` or `getInitialProps`.
2. Start your application
3. Click on the Automatic static optimization indicator

## Expected behavior

The indicator should take you to some docs page explaining either what that indicator means, or just what Automatic Static Optimization means.

## System information

- OS: macOS (should be irrelevant)
- Browser: Chrome (should be irrelevant)
- Version of Next.js: 9.3.5
- Version of Node.js: 13.3.0

**Comment by heanzyzabala** [comment] 2020-07-24 17:01
Hi, I would like to work on this. Thanks!

**Comment by ivoelbert** [comment] 2020-07-24 19:27
Actually this looks like a `create-next-app` problem. [This commit](https://github.com/vercel/next.js/commit/279ae19c7e4cb75bd79873b0036332222781b792) changes the link to the expected one. Probably the `next.js` version that CNA uses still doesn't have that change reflected.

**Comment by heanzyzabala** [comment] 2020-07-25 02:35
Alright. Thanks @ivoelbert

**Comment by awareness481** [comment] 2020-07-25 07:35
I was running `v9.4.5-canary.42` and the static indicator has the correct link.

@timneutkens As @ivoelbert pointed out, this seems to be fixed by [https://github.com/vercel/next.js/commit/279ae19c7e4cb75bd79873b0036332222781b792](commit) so the issue can be closed?

**Comment by timneutkens** [comment] 2020-07-26 10:02
This is solved on canary indeed. Will be released on stable soon!

**Closed by timneutkens** 2020-07-26 10:02 UTC
Labels: good first issue, kind: bug

**Comment by balazsorban44** [comment] 2022-01-29 20:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
