### ISSUE TITLE
Build is too slow(seems unable) when using yarn@3.2.0-rc.5

### ISSUE THREAD

**Issue by hoondeveloper** [vercel/next.js#31880] opened 2021-11-28 07:52 UTC
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS 11.4 (M1 Mac)

### How are you deploying your application?

Local Environment (ARM M1)

### Describe the Bug

i am using yarn berry. when i use yarn@3.1.1 and i tried to `yarn dev`, [this problem](https://github.com/yarnpkg/berry/pull/3667) has occurred. so i changed yarn's version to canary(3.2.0.rc.6), then it works.

however, when I tried to build it, there was no response(or too slow) even after several minutes.
<img width="672" alt="스크린샷 2021-11-28 오후 4 50 44" src="https://user-images.githubusercontent.com/32122626/143734290-28936630-b647-4751-99bc-79b4f7ec5270.png">
There were no logs or reactions except the logs shown in that picture.

weirdly, when i build at Vercel, it works.

### Expected Behavior

build successfully.

### To Reproduce

1. clone [this repository](https://github.com/hoondeveloper/feed)
2. yarn set version berry
3. yarn set version canary
4. yarn build

**Comment by kherock** [comment] 2021-12-02 00:19
Duplicate of https://github.com/vercel/next.js/issues/31279.

I'm guessing it works on Vercel because they have `experimental: { workerThreads: true }` enabled there.

**Closed** 2021-12-02 23:59 UTC
Labels: template: bug, area: Yarn PnP / pnpm

**Comment by balazsorban44** [comment] 2022-01-27 06:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
