### ISSUE TITLE
`next/image` should (probably) return original format by default

### ISSUE THREAD

**Issue by daneden** [vercel/next.js#18592] opened 2020-10-31 18:39 UTC
# Bug report

## Describe the bug

Using `next/image`, I noticed that requesting a `.jpe?g` image returns a `.png` via `_next/image` in Safari 14.0.1. This seems to be due to the `Accepts` header sent by Safari not including a jpg format.

Either way, I also noticed that the returned `png` image was almost twice the size as the source `jpg` (72kb vs 41kb).

- Basic/canonical formats (`png`, `jpe?g`, `gif`) should probably be returned where it makes sense, even if they're not explicitly listed in the `accepts` header
- Source images should probably be returned if they're smaller in size than the transformed result

## To Reproduce

[daneden/handy](https://github.com/daneden/handy) to reproduce:

https://github.com/daneden/handy/blob/6ca0e5346f623e8c8437151ffe61031a2144232c/pages/index.tsx#L28

- Request a small jpg image using `next/image`
- Load the page in Safari 14.0.1
- Observe the network request(s) for a transformed `png` image

## Expected behavior

- When the transformed result is smaller in size than the source image, the source image should be returned
- Additionally, other than `webp`, it seems more desirable for the original source format to be the returned image format i.e. requesting a jpg returns a jpg; requesting a png returns a png; _unless_ a webp is smaller in size and supported by the requesting browser.

## System information

- OS: macOS
- Browser: Safari 14.0.1
- Version of Next.js: 10.0.0

**Comment by styfle** [comment] 2020-10-31 22:10
Thanks for reporting!

This looks like a duplicate of #18509.

**Closed by styfle** 2020-10-31 22:10 UTC

**Comment by michrome** [comment] 2020-11-02 17:18
@daneden FYI fix landed in `10.0.1-canary.5`!

**Comment by daneden** [comment] 2020-11-02 17:19
@michrome yay! Thank you!

**Comment by balazsorban44** [comment] 2022-01-29 07:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
