### ISSUE TITLE
[NEXT-1226] Error: NextRouter was not mounted (NOT IN app folder)

### ISSUE THREAD

**Issue by elucidsoft** [vercel/next.js#43585] opened 2022-11-30 22:38 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

I am getting this error that most people get only inside the app folder. I migrated from NextJs 12 to 13. Made no changes to my code, after migration was completed I get this error on build. I migrated another app as well that shares similar code and components and it builds just fine.  I have spent hours and hours on this problem before submitting this issue. I have tried everything I can think of without resolution.

To be 100% clear, none of this is in a folder called app.  This error is being thrown on every single page in the entire application, not just one. 

### Which area of Next.js is affected? (leave empty if unsure)

CLI (create-next-app)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

@PathfinderH Was able to get a reproduction of this issue:
https://github.com/PathfinderH/next13-demo

@kylemh Was able to get a reproduction of this issue:
https://github.com/kylemh/kylemh-com/tree/16b2005c1689ec51c4eff33c214daa5530206de4

### To Reproduce

If I knew how to reproduce I could of fixed the issue.

### Describe the Bug

Some scenario (undetermined) creates a situation where it tried to build client pages and components as server pages and components outside of the app directory. It throws the error: "Error: NextRouter was not mounted" which is most commonly found when attempting to use router in the app directory.  Placing "use client" at the top of components and pages does not appear to affect anything.

### Expected Behavior

For the app to build like it did in 12.x

<sub>[NEXT-1226](https://linear.app/vercel/issue/NEXT-1226/error-nextrouter-was-not-mounted-not-in-app-folder)</sub>

**Comment by elucidsoft** [comment] 2022-11-30 22:41
https://github.com/vercel/next.js/discussions/43570

**Comment by elucidsoft** [comment] 2022-12-01 13:30
If I could reproduce it I would of fixed it myself.

**Comment by balazsorban44** [comment] 2022-12-01 13:41
Please read the message carefully. We need a link to your source code to be able to help.

**Comment by FiberJW** [comment] 2022-12-02 06:29
I'm getting the same issue. Upgraded a Next 12 project and haven't even created an `app` folder but I'm getting these errors. The website runs fine and doesn't crash in the browser and `next build` works so it's likely something going on with the Next dev server.

**Comment by FiberJW** [comment] 2022-12-02 06:42
I'm seeing this error occur on pages that don't import useRouter, but a page that it links to gets pre-rendered and logs that error

**Comment by Maiveasna** [comment] 2022-12-02 08:44
Hello all guys. I think this issue will be solved  until the release  nextjs v13 support app layout

**Comment by balazsorban44** [comment] 2022-12-02 13:11
> I'm getting the same issue. Upgraded a Next 12 project and haven't even created an app folder but I'm getting these errors. The website runs fine and doesn't crash in the browser and next build works so it's likely something going on with the Next dev server.

@FiberJW please read https://github.com/vercel/next.js/issues/43585#issuecomment-1333577007 "I did not open this issue, but it is relevant to me, what can I do to help?"

**Comment by FiberJW** [comment] 2022-12-02 15:11
> > I'm getting the same issue. Upgraded a Next 12 project and haven't even created an app folder but I'm getting these errors. The website runs fine and doesn't crash in the browser and next build works so it's likely something going on with the Next dev server.
> 
> 
> 
> @FiberJW please read https://github.com/vercel/next.js/issues/43585#issuecomment-1333577007 "I did not open this issue, but it is relevant to me, what can I do to help?"

Thanks for the reminder! I didn't have time to make a repro at the moment since I was nearing the end of the day but I'll try to make a repro case if possible!

**Comment by PathfinderH** [comment] 2022-12-08 12:56
I'm getting the same issue  This is the reproduce link   https://github.com/PathfinderH/next13-demo

**Comment by kylemh** [comment] 2022-12-10 16:16
I don't even _have_ an app directory and I'm seeing this issue.

Reproduction: https://github.com/kylemh/kylemh-com/tree/16b2005c1689ec51c4eff33c214daa5530206de4
Failing Vercel Build: https://vercel.com/innocuous-tech/kylemh-com/3UvbLD7qmfbAzj3BfMba6gCxpxDG

**Comment by elucidsoft** [comment] 2022-12-11 15:30
> I don't even _have_ an app directory and I'm seeing this issue.
> 
> Reproduction: https://github.com/kylemh/kylemh-com/tree/16b2005c1689ec51c4eff33c214daa5530206de4 Failing Vercel Build: https://vercel.com/innocuous-tech/kylemh-com/3UvbLD7qmfbAzj3BfMba6gCxpxDG
> 
> I walked back by version of Next.js and my build seems to stop working on and after version 13.0.3

Dude, thank you for adding a repro, seriously! Hopefully this gets resolved, I just decided to wait a couple months before I try to upgrade again.  Hopefully all these odd issues will be resolved.

**Comment by FiberJW** [comment] 2022-12-21 03:58
My workaround for this is to downgrade to 13.0.2. Also, an SSR bug I was having (Apollo queries weren't being rendered on the server, resulting in spinners on the first load) was fixed by downgrading to that version.

**Comment by julioflima** [comment] 2022-12-29 01:41
Still not resolved in the 13.1.1...

**Comment by sahaviev** [comment] 2022-12-29 23:28
Hello everyone.
We had the similar issue in our monorepo(but I supposed that it might happen in polyrepo also). 

Despite of the fact that all our apps use the same fixed version of Next - we got "_Error: NextRouter was not mounted_" error in our Next build .
One small thing helped us to fix this - we added resolution version of Next in **package.json**.
Try these. Probably it would help to somebody.

```
"resolutions": {
    "**/next": "13.1.1"
  },
```

Reference 1: Yarn https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/
Reference 2: NPM https://stackoverflow.com/questions/52416312/npm-equivalent-of-yarn-resolutions

**Comment by selenecodes** [comment] 2022-12-30 13:44
Also running into this in 13.1.1

**Comment by pacocoursey** [comment] 2023-01-08 19:41
I encountered this error while server rendering components for an RSS feed inside of `getStaticProps`. Those components had children that used `useRouter`, which wasn't available outside of a page context.

It may be worth checking for your usage of `renderToString` or similar `react-dom/server` methods for a similar case.

**Comment by wanjas** [comment] 2023-01-12 08:23
Seems like this is by design:

(since 13.0.3)
https://github.com/vercel/next.js/blob/4240dcc410b441807a33a87191a3413d3dc4564b/packages/next/client/compat/router.ts

Changing import to `import { useRouter } from 'next/compat/router'` might fix an issue for some people.

**Comment by michelalbers** [comment] 2023-02-12 14:46
> Seems like this is by design:
> 
> (since 13.0.3) https://github.com/vercel/next.js/blob/4240dcc410b441807a33a87191a3413d3dc4564b/packages/next/client/compat/router.ts
> 
> Changing import to `import { useRouter } from 'next/compat/router'` might fix an issue for some people.
> 
> P.s. I don't know how to resolve this issue (with `renderToString` in my case) in a future-proof way.

This is the solution! Should be documented in the upgrade guidelines!

**Comment by elucidsoft** [comment] 2023-02-15 15:45
> > Seems like this is by design:
> > (since 13.0.3) https://github.com/vercel/next.js/blob/4240dcc410b441807a33a87191a3413d3dc4564b/packages/next/client/compat/router.ts
> > Changing import to `import { useRouter } from 'next/compat/router'` might fix an issue for some people.
> > P.s. I don't know how to resolve this issue (with `renderToString` in my case) in a future-proof way.
> 
> This is the solution! Should be documented in the upgrade guidelines!

Just a note, this applies to any shared components that use router as well like Buttons, etc.

**Comment by saltcod** [comment] 2023-02-18 17:55
Seeing this on a brand new install of next@latest. 


Spun up a quick repo, though these 2 lines are all I changed. Import the router, and then use it:
https://github.com/saltcod/next13-vanilla/blob/main/app/page.tsx


<img width="946" alt="CleanShot 2023-02-18 at 14 19 44@2x" src="https://user-images.githubusercontent.com/105593/219880746-06d8dbe2-5d82-422b-af64-8af3837372fa.png">
 
— 

Adding `import { useRouter } from 'next/compat/router'` fixes the error, but `const router = useRouter()` is always undefined when I do this.

**Comment by wanjas** [comment] 2023-02-20 04:42
@saltcod 

https://beta.nextjs.org/docs/api-reference/use-router
There is a section: **Migrating from the pages directory.**

**Comment by f1729** [comment] 2023-02-24 21:50
Same error here, 'next/compat/router' worked as a work around.

**Comment by TamoMaes** [comment] 2023-03-14 12:06
Still same error in 13.2.4 🥲 So keeping it on 13.0.2 as mitigation

**Comment by twiddli** [comment] 2023-04-04 20:47
I remember I was getting this error because I had set:
```js
    experimental: {
      appDir: false,
    }
```

Then it didn't matter whether I was using the app folder or not. It would always build according to an app folder environment.

**Comment by thebiltheory** [comment] 2023-04-21 13:55
How do you actually use `useRouter` inside a hook? `/hook` is neither the `/app` folder nor the `/pages` folder?

**Comment by SamKomesarook** [comment] 2023-05-05 13:34
Also encountering this issue using `13.4.1` with the `app` folder.

**Comment by nixjs** [comment] 2023-05-06 15:19
The new useRouter hook should be imported from `next/navigation` and not `next/router`

**Comment by zougari47** [comment] 2023-05-15 13:48
but useRouter from next/navigation is different from next/router 

previously in next 12 i can do with next/router
```jsx

import { useRouter } from 'next/router'

const Button = () => {
  const router = useRouter()
  const options = {
    id: 5,
    category: 'Cat',
  }
  return (
    <div>
      <button
        onClick={() =>
          router?.push(
            {
              pathname: '/search',
              query: options,
            },
            '/search'
          )
        }
      >
        use router
      </button>
    </div>
  )
}

export default Button
```
which redirects to page search with params without showing them in URL 


But with next/navigation router I can't do that !!

**Comment by CobyPear** [comment] 2023-05-19 16:37
We are still using the `pages` directory and have suddenly started running into this issue. I see there is a reproduction linked in the original comment, does this issue still ned a reproduction? Using the `next/compat/router` does not seem to help as `useContext` is trying to be called and is undefined.

**Comment by BeqaLobzhanidze** [comment] 2023-05-20 19:21
I had same issue . the problem is happening because u are using (app) directory . if you are using app directory you should use Router from (next/navigator) package . but if you need to use (next/router) package then you need to change directory (from app to pages) . and it will be fixed .

**Comment by balazsorban44** [comment] 2023-05-25 07:17
@PathfinderH looks like you are using `next/router` instead of `router/navigation`, which should be the case in the App Router, as mentioned in the docs: https://nextjs.org/docs/app/api-reference/functions/use-router#userouter

@saltcod same issue for you.

@kylemh your reproduction seems to be private as it gives 404


I'm closing this issue, as it seems like most reports are not following the docs or point to an unreachable reproduction. If you think this is still an issue after following the docs and trying out the `next@canary` release, please open a new issue with an accessible, minimal reproduction. Thank you!

**Closed by balazsorban44** 2023-05-25 07:17 UTC
Labels: template: bug, linear, type: needs triage

**Comment by iamsabbirsobhani** [comment] 2023-06-01 03:11
I am unable to use next/compat/router and next/navigation to add router.events.on.

**Comment by market-south** [comment] 2023-06-08 05:43
I am also having the same issue as @iamsabbirsobhani on the Next 13. 

Just wondering whether any solution or workaround was found. 

We are importing as follows:
```
import {  useRouter , usePathname  } from "next/navigation"
import {  Router  } from "next/router";
```

useRouter and usepathname are working as expected, but we want to use Router to perform a state change on event change.

Sample code as below:
```
 const [megaMenu, setMegaMenu] = useState(false);

 const toggleMenuBar = () => {
        setMegaMenu((b) => !b);
    };

 const hideMegaMenu = (url) => {
        setMegaMenu(false);
      };
const router = useRouter();

useEffect(() => {


    Router.events.on("hashChangeStart",  setMegaMenu(false));
    Router.events.on("routeChangeError", hideMegaMenu);
    Router.events.on("routeChangeStart", hideMegaMenu);
    Router.events.on("hashChangeComplete", hideMegaMenu);
    return () => {
      // Make sure to remove the event handler on unmount!
      Router.events.off("routeChangeStart", hideMegaMenu);
      Router.events.off("routeChangeComplete", hideMegaMenu);
      Router.events.off("routeChangeError", hideMegaMenu);
    };
  }, [router]);
```

The above code works perfectly on Next 12 and Next 11 as we have other websites using them.

Any help would be appricated.

**Comment by giorgiabosello** [comment] 2023-06-21 19:59
@iamsabbirsobhani @market-south same, I [found this](https://nextjs.org/docs/app/api-reference/functions/use-router#router-events) in the documentation. We should create an hook by ourselves with `usePathname` and `useSearchParams`.

I used locale and defaultLocale with `useRouter` to change the language of the website, now I can't find a way to do it with the new router.

**Comment by khanakia** [comment] 2023-06-28 16:32
I have some shared components and i cannot use `useRouter` outside of the app directory. So now next.js forcing me to move all the shared hooks and components inside app directory so i cannot make keep shared components as separate shared packages (monorepo)
