### ISSUE TITLE
InferGetStaticPropsType does not infer props when GetStaticProps is used

### ISSUE THREAD

**Issue by selbekk** [vercel/next.js#29963] opened 2021-10-16 09:20 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

16.9.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Props are not being inferred correctly by InferGetStaticPropsType in the following case:

```tsx
export const getStaticProps: GetStaticProps = (context) => {
  return {
    props: { hello: 'world' }
  }
}

export default function Example({ hello }: InferGetStaticPropsType<typeof getStaticProps>) {
  // here, `hello` is "any"
}
```

If I remove the `GetStaticProps` definition on the first line, things work as expected. I assume that's because I could specify the props type as a type argument to `GetStaticProps<{ hello: string }>`, but I don't want that.

Is this even possible to fix?

### Expected Behavior

Would love for this to just propagate the props as expected.

### To Reproduce

Create a new Next.js project with TypeScript, and create a new pages file (index.tsx) for example. Paste the following code:

```tsx
export const getStaticProps: GetStaticProps = (context) => {
  return {
    props: { hello: 'world' }
  }
}

export default function Example({ hello }: InferGetStaticPropsType<typeof getStaticProps>) {
  // here, `hello` is "any"
}
```

**Comment by dephraiim** [comment] 2021-10-22 00:00
Don't forget you can obtain argument type in `getStaticProps` with `GetStaticPropsContext`.

```ts
import { InferGetStaticPropsType, GetStaticPropsContext} from 'next'

export const getStaticProps = (context: GetStaticPropsContext) => {
  return {
    props: { hello: 'world' }
  }
}

export default function Example({ hello }: InferGetStaticPropsType<typeof getStaticProps>) {
}

export default Blog\
```

**Comment by timneutkens** [comment] 2021-10-31 10:40
Going to close this as a duplicate of #15913 to track it in one place.

**Closed by timneutkens** 2021-10-31 10:40 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
