### ISSUE TITLE
"Invalid hook call" in 11.1.2

### ISSUE THREAD

**Issue by Ultharite** [vercel/next.js#28656] opened 2021-08-31 13:14 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

next dev

### Describe the Bug

The CSS issue in Windows is cleared up, but this new one appears on any fresh NextJS project:

`Server Error
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.`

### Expected Behavior

NextJS would work as it did before 11.1.1.

### To Reproduce

npx create-next-app (anything)

**Comment by LemonJuicer96** [comment] 2021-08-31 13:39
Same here

**Comment by LemonJuicer96** [comment] 2021-08-31 14:37
To Reproduce
yarn create next-app test
yarn dev
open localhost:3000
get errors

**Comment by LemonJuicer96** [comment] 2021-08-31 15:26
@ijjk

**Comment by ijjk** [comment] 2021-08-31 18:35
Hi @LemonJuicer96 I'm not able to reproduce the error with the above steps on macOS or Windows 10, can you provide any more details to help track this down e.g. the output from `npm ls -g`, `npm ls` in newly created project, or a screen recording?

**Comment by LemonJuicer96** [comment] 2021-08-31 19:18
Strange, I tried reproducing it again using both yarn create and npx but didn't get any errors

**Comment by LemonJuicer96** [comment] 2021-08-31 19:27
I tried again but got the error this time.

**Comment by LemonJuicer96** [comment] 2021-08-31 19:29
The time I didn't get any errors I was testing in user folder just because I forgot to cd into desktop. Turns out error only occurs when I use the app on Desktop. Dragging app folder worked.

**Comment by LemonJuicer96** [comment] 2021-08-31 19:30
@ijjk Found a temporally solution. Try to reproduce in C:\Users\<User>\Desktop folder

**Comment by LemonJuicer96** [comment] 2021-08-31 20:45
`npm ls > ls-local.txt` + copypasted npm ERR line
[ls-local.txt](https://github.com/vercel/next.js/files/7086701/ls-local.txt)

npm ls -g > ls-global.txt
[ls-global.txt](https://github.com/vercel/next.js/files/7086713/ls-global.txt)

`create-next-app --version`
11.1.2
@ijjk

**Comment by ijjk** [comment] 2021-08-31 21:04
Hmm nothing sticks out there, can you try deleting the `.next` folder and restarting `yarn dev` in the new project?

**Comment by Ultharite** [comment] 2021-08-31 21:16
Running` yarn dev`:

> Server Error
> Error: Cannot find module '../../../AppData/Roaming/npm/node_modules/next/dist/shared/lib/constants.js'
> Require stack:
> - C:\Users\Brian\Projects\a8nextwp-frontend\.next\server\pages\_document.js
> - C:\Users\Brian\Projects\a8nextwp-frontend\node_modules\next\dist\server\require.js
> - C:\Users\Brian\Projects\a8nextwp-frontend\node_modules\next\dist\server\load-components.js
> - C:\Users\Brian\Projects\a8nextwp-frontend\node_modules\next\dist\server\api-utils.js
> - C:\Users\Brian\Projects\a8nextwp-frontend\node_modules\next\dist\server\next-server.js
> - C:\Users\Brian\Projects\a8nextwp-frontend\node_modules\next\dist\server\next.js
> - C:\Users\Brian\Projects\a8nextwp-frontend\node_modules\next\dist\server\lib\start-server.js
> - C:\Users\Brian\Projects\a8nextwp-frontend\node_modules\next\dist\cli\next-dev.js
> - C:\Users\Brian\Projects\a8nextwp-frontend\node_modules\next\dist\bin\next

Running `next dev`:

> Server Error
> Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

`npm ls > ls-local.txt` :

a8nextwp-frontend@0.1.0 C:\Users\Brian\Projects\a8nextwp-frontend
+-- eslint-config-next@11.1.2
+-- eslint@7.32.0
+-- next@11.1.2
+-- react-dom@17.0.2
`-- react@17.0.2

Two days ago I could run npx create-next-app (anything) and it would work perfectly. These aren't under my Desktop folder, they're under c:\Users\Brian\Projects\

**Comment by LemonJuicer96** [comment] 2021-08-31 21:23
> Hmm nothing sticks out there, can you try deleting the `.next` folder and restarting `yarn dev` in the new project?

Doesn't work @ijjk

**Comment by ijjk** [comment] 2021-08-31 21:30
@Ultharite is `next` install globally for you? `next` shouldn't be able to be run without prefixing it with `yarn` since it won't resolve correctly to `node_modules/.bin` automatically without. 

Note: `next` is not meant be installed globally and can cause this error to occur

**Comment by Ultharite** [comment] 2021-08-31 21:34
I uninstalled next globally, and that seems to have done the trick so far! Running yarn dev and that starter homepage popped up.

**Comment by LemonJuicer96** [comment] 2021-08-31 21:35
Don't have it installed globally 😢

**Comment by LemonJuicer96** [comment] 2021-09-02 13:40
All I have Installed in global modules folder is yarn. In yarn global modules folder is just create-next-app, which is automatically updated when using `yarn create next-app`. I also tried removing NVM for windows and installing node through official installer but that didn't work either

**Comment by LemonJuicer96** [comment] 2021-09-02 13:50
Using older versions of create-next-app didn't help either

**Comment by LemonJuicer96** [comment] 2021-09-03 23:45
@ijjk Do you have any ideas? I can't use nex.js until the issue is solved

**Comment by ijjk** [comment] 2021-09-04 14:43
@LemonJuicer96 is next available in your path at all still e.g. running `next` without `yarn`? Are you using `npx next` to start next if so this could cause issues as well. Maybe conflicting react or react-dom versions are installed globally that are conflicting 🤔

**Comment by LemonJuicer96** [comment] 2021-09-04 15:23
I never installed next globally or runned it without yarn or npm. I also already said that all I have installed globally is `create-next-app` which is automatically installed and updated when `yarn create next-app` runs @ijjk

**Comment by LemonJuicer96** [comment] 2021-09-08 17:02
I cleaned my pc and it started working again, though I don't know what was conflicting. @Ultharite I suggest to close the issue until someone else encounters same problem.

**Comment by igorbarbashin** [comment] 2021-09-09 15:18
I have the same issue when using this package
https://www.npmjs.com/package/react-click-outside-hook

<img width="976" alt="Screen Shot 2021-09-09 at 8 18 28 AM" src="https://user-images.githubusercontent.com/1911427/132714060-e59157cc-a39e-432d-898c-a06d0a77e242.png">

**Comment by ijjk** [comment] 2021-09-09 15:28
I'm going to close this as the initial issue appears to be resolved and was due to `next` being installed globally. 

@igorbarbashin if you are having trouble with a specific package please open a help discussion https://github.com/vercel/next.js/discussions/categories/help and it can be investigated there.

**Closed by ijjk** 2021-09-09 15:28 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 20:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
