### ISSUE TITLE
[Bug;v9.5.3] URL parameter not filled in router.query when using trailingSlash:true

### ISSUE THREAD

**Issue by NicolasRiche** [vercel/next.js#17112] opened 2020-09-15 14:29 UTC
Hi, I think there is a bug on v9.5.3 : 

When I enabled trailingSlash in next.config.js
```
module.exports = {
  trailingSlash: true,
}
```
The router no longer extract URL parameters.

## Example
Let's say I have a page: /mypage.

If I call the page with **/mypage/?foo=abc** (trailingSlash included)

The page is well served by NextJs, however when I try to read the **foo** URL parameter, it appear as **undefined** (CF code below)

```Javascript
export default function MyPage(props) {
    const router = useRouter();
    const { foo } = router.query

   // foo is undefined is I access the page with a trailing slash  /mypage/?foo=abc
}
```

---

**Note: It worked on v9.5.2, when I used the exportTrailingSlash, on v9.5.3 both exportTrailingSlash and trailingSlash:true trig the same results.**

```
module.exports = {
  exportTrailingSlash: true,
}
```

Thank you

**Comment by nicholaschiang** [comment] 2020-09-17 15:42
I'm getting the same issue even without using the `trailingSlash` option.

**Comment by davidgruar** [comment] 2020-10-12 15:14
If you're experiencing this issue only on first render, it appears to be expected and documented behaviour: see https://github.com/vercel/next.js/issues/10521 and https://nextjs.org/docs/routing/dynamic-routes#caveats.

That said, I am seeing this after upgrading from 9.4.4 to 9.5.5. Dynamic routed pages in my app that previously relied on `useRouter().query.id` being populated are now getting an empty `query` object on first render. The `trailingSlash` option does seem to be a red herring - it doesn't make any difference whether it's true, false or absent.

**Comment by ijjk** [comment] 2021-09-21 04:19
Closing as this appears to be working correctly in the latest version of Next.js `v11.1.2`, as noted above for static pages it is expected the first render will have an empty query until after hydration.

**Closed by ijjk** 2021-09-21 04:19 UTC

**Comment by balazsorban44** [comment] 2022-01-27 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
