### ISSUE TITLE
Image error with no Image tag specified

### ISSUE THREAD

**Issue by pkail** [vercel/next.js#29187] opened 2021-09-17 21:47 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.17.3

### What browser are you using?

FireFox

### What operating system are you using?

Linux

### How are you deploying your application?

Problem is dev.

### Describe the Bug

When I run yarn dev I get:

error - node_modules/next/dist/client/image.js (470:18) @ Image1
Error: Image with src "/undefined.png" must use "width" and "height" properties or "layout='fill'" property.

There is no image called /undefined.png, nor any other images using <Image />.

### Expected Behavior

The error would either point to a specific Image tag or else not be shown.

### To Reproduce

This doesn't seem to be related to any of my code.

**Comment by pkail** [comment] 2021-09-17 23:37
I found the image in the end: its filename was specified using props.
The problem is solved, but Next.js should identify the component where the error occurs and/or the file name of the image.

**Comment by ijjk** [comment] 2021-09-19 17:16
It sounds like the passed image src was logged correctly by Next.js although was hard to find due to `undefined` being interpolated into the filename. I'm not sure we can expand the error to catch this case more precisely currently so I'm gonna close this since it was tracked down in the end.

**Closed by ijjk** 2021-09-19 17:16 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
