### ISSUE TITLE
Input with type="email" causes hydration error in dev

### ISSUE THREAD

**Issue by Vinnl** [vercel/next.js#44644] opened 2023-01-06 10:23 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Wed Dec 21 18:33:23 UTC 2022
    Binaries:
      Node: 16.18.0
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.2-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://gitlab.com/bug-repros/nextjs-bug-repro

### To Reproduce

```
git clone https://gitlab.com/bug-repros/nextjs-bug-repro;
cd nextjs-bug-repro;
npm install;
npm run dev;
```

Open the dev server in Firefox.

### Describe the Bug

When you use an `<input type="email">` on a Next.js page, running the dev server and then visiting that page in Firefox reslts in a hydration error:

![image](https://user-images.githubusercontent.com/4251/210985058-e9a12378-68c0-40f0-a354-440fcd3ea09e.png)

### Expected Behavior

No hydration error on all browseres.

### Which browser are you using? (if relevant)

Firefox 108.0.1

### How are you deploying your application? (if relevant)

next dev

**Comment by Vinnl** [comment] 2023-01-06 10:30
Note: someone else also mentioned this issue on StackOverflow: https://stackoverflow.com/questions/73571827/nextjs-input-hydration-error-when-using-type-email

**Comment by balazsorban44** [comment] 2023-01-06 16:53
I cannot reproduce it, this is likely a duplicate of #41026. Make sure there is no conflicting browser extension.

**Closed by balazsorban44** 2023-01-06 16:53 UTC
Labels: template: bug
