### ISSUE TITLE
Encountered issue when compiling on `next dev` - RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by madebyais** [vercel/next.js#26246] opened 2021-06-17 08:24 UTC
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows 10

### How are you deploying your application?

it is still under developement

### Describe the Bug

Got error when running `next dev`. This error is intermittently happened after 15 minutes.

```
wait  - compiling...
internal/buffer.js:951
class FastBuffer extends Uint8Array {}
^

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:951:1)
    at createUnsafeBuffer (buffer.js:152:12)
    at Function.allocUnsafeSlow (buffer.js:397:10)
    at read (E:\Workspace\cosmiq\webapp\node_modules\next\dist\compiled\webpack\bundle5.js:122381:32)
    at E:\Workspace\cosmiq\webapp\node_modules\next\dist\compiled\webpack\bundle5.js:122429:7
    at E:\Workspace\cosmiq\webapp\node_modules\next\dist\compiled\webpack\bundle5.js:29762:16
    at FSReqCallback.oncomplete (fs.js:180:23)
```

### Expected Behavior

The compiling should running properly as usual.

The yarn build is running successfully.

```
yarn run v1.22.10
$ next build
info  - Loaded env from E:\Workspace\cosmiq\webapp\.env.local
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types

./pages/api/oauth/[provider]/callback.ts
7:1  Warning: Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

./pages/_document.tsx
9:11  Warning: Do not include stylesheets manually. See: https://nextjs.org/docs/messages/no-css-tags.  @next/next/no-css-tags

./components/svg/index.tsx
12:5  Warning: Image elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text


info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
info  - Generating static pages (3/3)
info  - Finalizing page optimization

Page                                Size     First Load JS
┌ ○ /                               1.01 kB        91.8 kB
├   /_app                           0 B            63.7 kB
├ ○ /404                            3.18 kB        66.9 kB
├ λ /api/hello                      0 B            63.7 kB
├ λ /api/oauth/[provider]/callback  0 B            63.7 kB
├ λ /dashboard                      1.13 kB        91.9 kB
└ λ /login                          8.19 kB        89.4 kB
+ First Load JS shared by all       63.7 kB
  ├ chunks/framework.923004.js      42 kB
  ├ chunks/main.0c4bed.js           20.3 kB
  ├ chunks/pages/_app.88adf7.js     555 B
  ├ chunks/webpack.715970.js        804 B
  └ css/2fe097d1e0031b7f53b0.css    633 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

Done in 101.99s.
```

### To Reproduce

I don't know how to reproduce this.

**Comment by anton-paskanny** [comment] 2021-06-17 13:09
I also noticed such a behavior, but I have the 10.2.3 Next.js version. It happens from time to time, I can't say the exact steps I do to cause this error.

**Comment by anton-pas** [comment] 2021-06-18 07:37
Node.js - 14.0.7
OS - Windows 10 (i7, 16gb RAM)
Browser - Chrome

I also noticed such behavior, it happens from time to time, can't name the exact step to reproduce this situation.

**Comment by xSCIven** [comment] 2021-06-22 07:59
Experiencing the same thing, windows 10

**Comment by xSCIven** [comment] 2021-06-23 00:30
Ok so It works with the latest version of node from what I can see, it hasn't shown the error. Node version 16.3.0

**Comment by opolo** [comment] 2021-06-23 13:42
Thx for info, will try and update Node. Will let know if issue comes back

**Comment by xSCIven** [comment] 2021-06-24 23:29
I have now realised that I had accidentally downloaded the 32 bit arch of node. You need the 64bit version to avoid this error. Check the architecture in node version manager for windows.

**Comment by anton-pas** [comment] 2021-07-06 09:06
> I have now realised that I had accidentally downloaded the 32bit arch of node. You need the 64bit version to avoid this error. Check the architecture of your node install in node version manager for windows.

I did that mistake too. Reinstalled Node.js from 32bit to 64bit and everything works fine)

**Comment by timneutkens** [comment] 2021-11-17 15:45
Closing as no reproduction was provided and there was no recent comments.

**Closed by timneutkens** 2021-11-17 15:45 UTC
Labels: please add a complete reproduction

**Comment by hrr2000** [comment] 2022-01-09 13:56
> I have now realised that I had accidentally downloaded the 32bit arch of node. You need the 64bit version to avoid this error. Check the architecture of your node install in node version manager for windows.

Worked for me thanks.

**Comment by balazsorban44** [comment] 2022-02-08 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
