### ISSUE TITLE
`next export` creates wrong files / urls

### ISSUE THREAD

**Issue by Paratron** [vercel/next.js#23217] opened 2021-03-19 11:25 UTC
### What version of Next.js are you using?

10.0.6

### What version of Node.js are you using?

12.18.4

### What browser are you using?

doesnt matter

### What operating system are you using?

doesnt matter

### How are you deploying your application?

doesnt matter

### Describe the Bug

Basically all links break when using `next export`. But in a weird way.

For example: When I create the route `/pages/example.js`, I can call this route during development with the URL `/example`. However, when using `next export`, the result file is `/example.html` which would be fine but all `<Link>` elements pointing to that page will link to `/example`. 

While the client side router seems to handle this just fine (I can navigate the page by clicking on links), the bug reveals itself when I reload the page or directly jump to `/example` without getting there through clicking on `<Link>`s.

The server correctly tells me 404 - page not found.

### Expected Behavior

So what should happen: 

I guess when exporting, the routes where `<Link>` components point to need to be rewritten to actually contain a `.html` at the end. 

### To Reproduce

Create any route and use `next export`.

**Comment by Paratron** [comment] 2021-03-19 11:39
For anyone else having this issue right now:

I created a workaround by creating a component `<FixedLink>` which removes the `.html` during development phase and leaves it in place in build/export phase.

Then I just go and place `<FixedLink href="/example.html">...` everywhere, assuming that the pages will be html files in the end.

**Comment by JanKaifer** [comment] 2023-01-13 12:46
Yup, this is a duplicate of https://github.com/vercel/next.js/issues/9213.

**Closed by JanKaifer** 2023-01-13 12:46 UTC
Labels: template: bug
