### ISSUE TITLE
[i18n][link] Link does not redirect with a locale

### ISSUE THREAD

**Issue by jansedlon** [vercel/next.js#18545] opened 2020-10-30 16:13 UTC
# Bug report

## Describe the bug

If I use a default locale `en` and create a link which has a `about` href, after clicking on it, it does not redirect to a `/en/about` but just `/about` instead.

## To Reproduce

https://codesandbox.io/s/busy-franklin-tsv28?file=/next.config.js

## Expected behavior

It should redirect to an url with a locale if url contains default locale

## System information

- OS: macOS
- Version of Next.js: 10.0.0
- Version of Node.js: 14.12.0

**Comment by ijjk** [comment] 2020-10-30 16:24
Hi, this is a duplicate of https://github.com/vercel/next.js/discussions/18419 closing in favor of that one

**Closed by ijjk** 2020-10-30 16:24 UTC

**Comment by balazsorban44** [comment] 2022-01-29 08:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
