### ISSUE TITLE
soft navigation doesn't work in app dir

### ISSUE THREAD

**Issue by xiaoyu12345678** [vercel/next.js#46345] opened 2023-02-24 06:31 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 1.22.17
      pnpm: 7.26.2
    Relevant packages:
      next: 13.2.1
      eslint-config-next: 13.2.1
      react: 18.2.0
      react-dom: 18.2.0

### Which example does this report relate to?

app-dir-i18n-routing

### What browser are you using? (if relevant)

chrome 110.0.5481.177

### How are you deploying your application? (if relevant)

npm run dev

### Describe the Bug

Navigate using client-side routing (next/link),But there will be a request every time, causing the interaction to freeze

### Expected Behavior

When using the client to navigate, do not initiate a request, causing the interaction to freeze

### To Reproduce

npm run dev -> click tab  It can be clearly seen that the interaction is stuck

**Comment by lucashfreitas** [comment] 2023-02-24 08:51
+1 on this issue - i have done a reproduction and we are discussing this issue on discord - it seems to be gone on the new canary version. Please have a look here https://github.com/vercel/next.js/discussions/46295

**Comment by lucashfreitas** [comment] 2023-03-15 11:01
@xiaoyu12345678 we should close this issue as this was already fixed.

**Comment by samcx** [comment] 2024-01-07 00:08
@lucashfreitas Thank you for confirming!

I will be closing this issue since this is very likely <picture data-single-emoji=":fixed:" title=":fixed:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/fixed/66bb8455f24bd50e.png" alt=":fixed:" align="absmiddle"></picture> in later <picture data-single-emoji=":nextjs:" title=":nextjs:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/nextjs/2a85d633ae594556.png" alt=":nextjs:" align="absmiddle"></picture> versions.

If you are still seeing an issue, please submit a new [bug report](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml) so we can take a look!

**Closed by samcx** 2024-01-07 00:08 UTC
Labels: area: examples
