### ISSUE TITLE
SWC Transpilation is incorrect

### ISSUE THREAD

**Issue by arackaf** [vercel/next.js#35053] opened 2022-03-04 17:44 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

/bin/sh: pnpm: command not found

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64
    Binaries:
      Node: 16.11.1
      npm: 8.0.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

n/a

### Describe the Bug

Looks like this is fixed in Next Canary, but I'll create the issue anyway, so hopefully someone can find it. If you do ... this is fixed in next 12.1.1-canary.6

---

The full repo is here: https://github.com/arackaf/swc-repro 

You can clone, npm i, and run the next app. Click the green button, with the dev tools open, and you should hit a debugger, with some comments above it, followed by an error.

Basically, the issue is (was) that `this` was transpiled wrongly in a non-arrow function. Relevant bit of code is below, full context in the linked repo above. 

```js
this.simplify = geoTransform({
  point() {
    // ERROR IS HERE. At runtime, the `this` value from `this.stream.point`, below, is transformed to `_this`,
    // with a value bound to the class component's `this` value, which has no stream object.

    // Note in the dev tools that `this` does indeed have a stream object on it, with a point method therein, which can be called.
    // But regardless, at a more basic level, the point method is NOT an arrow, and so references to `this` inside of it should NOT be transformed
    debugger;
    this.stream.point();
  },
```

### Expected Behavior

`this` should not be transpiled in a non-arrow function. 

### To Reproduce

See repo above

**Comment by SukkaW** [comment] 2022-03-05 03:53
Can't repro in [swc's playground](https://play.swc.rs/?version=1.2.146&code=H4sIAAAAAAAAA2VSy27bMBC85ysGvtQBBDlA0UtiB2gNA%2B0lKRzfa1pcS2workBSftTQv3clWY6N6EJoOZyZnV06VOwjMqtCwKowLgcdIjkdMOeyYkcuTn97rsIzTndAMGVlzfb4COWOT3dSydiF6Osssh9XLfC%2BAwq0rmgodUggFiakAwVmyIlXXrmwZV%2BO%2B1dAxcbF8cDSfpMJFsvl6xK%2F3vBzsVyk%2BB7haxdNSYmQEtYt8xo7ZWvC1nPZV1JxRqpMO8p1gg1Z3icwAXGQJY3IWP%2FpCJJryb2JBdSZc8O165CtWp9WNuTzJdzoJ9gXJitQqADH6C2AN38pi%2BndtcILR4JxHaemndCzFWuFigOhZgqC0CQ2C7Uj8XPDB3YwMRm8dn2ipFiwblk9GTfYyZST%2FuWwlnR6beNHLWlSrry2FEICkVco2UvXKpgMlnZk%2B5xvBCTGl9eVLAKU922uSiIKLFxbUXaZWG%2Bj7TsxLhhN4K34RSi4trp7LZauZnGxpWlT5zn5p0vl0zzH98Nl08%2Bt6QpNG7HIa1m%2BYYk8xdo7jM%2F4qTa75wvxdFPHKDmGeLQ0O50kTB2LR4y%2BPjxUh1GCLbv4Zv6RlL71lY3K3nPfrsScLXu5yD2Rk5vs%2FC%2BZRxqhaWRCc2uy99npZvmbD32gA0iqH5YmvacBNJ1cHJ97bP4Dm226h7kDAAA%3D&config=H4sIAAAAAAAAA3VTwXLjIAz9F845tIfd6eQDeus3MMQIR10MDBJuPJn8e0XsYjvp3tDjSTzpiav6pE4dryqZTJDriabA5qKOiqcE1GVMrA6KSSDOBW5yNrkHFgbQH7nyMRKoozOe4KAGDOimWqiLQ8pAVM%2BSUQYITI1nco5fNNc8qFOMHkx4irUhjYGhh7ymdtF7kwj0aHLLqK%2BZjBTDDioMVqcc0zY9WGSMQcIGWjBWd9GujVjM0DGOsCFJHSEFEnF70MKp9H0d4Pw0jMYXw9Diy30U8mjLO0ck1q4EeoAWtXPiDM2NLix0OgOXHH44nxHDbhb%2FAESnN0TBDBv9d9yJF3um%2B4WFwYmRPDVUXF5VBeilOY3oWodVNWRGaKQMtnRQO%2BzW4gu4a4jQggbnZNwtmb6Qu%2FNGVd3G6Nq9jM241YQ51D9LtUfrHjyB7yKLt34s%2BGD4%2FIjRNJyifyoxAJ%2BjfYJlEhwfwSwrfEmPaAkWZM5gNxeFarh8tcGEvu7aVXFMHkbwe5v%2Ba%2FIvWMo4Vtf2vwHhbTXCyHLg68sC3G5VQbRlUSAO3D%2F9X3Vb%2F%2FlsB9LHwrsL%2FwaUHvMLVwQAAA%3D%3D) though.

**Comment by balazsorban44** [comment] 2022-03-05 04:05
> Looks like this is fixed in Next Canary, but I'll create the issue anyway, so hopefully someone can find it. If you do ... this is fixed in next 12.1.1-canary.6

As stated above, this has been fixed in the latest `canary` and could not reproduce any issues.

**Closed by balazsorban44** 2022-03-05 04:05 UTC
Labels: template: bug

**Comment by arackaf** [comment] 2022-03-05 14:55
@balazsorban44 I was pretty much done writing it up, saw the box to repro in canary, did, and then saw it had been fixed.

Like I said in the issue, I thought this existing might help the next person searching for why their code was broken. Sorry if it wasted anyone's time :)

**Comment by balazsorban44** [comment] 2022-03-05 22:59
No worries!
