### ISSUE TITLE
Next image is not served as webp in compatible Chrome version

### ISSUE THREAD

**Issue by rubenpoppe** [vercel/next.js#29034] opened 2021-09-12 16:38 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.15.3

### What browser are you using?

Chrome 93/Chromium 93

### What operating system are you using?

Windows 11

### How are you deploying your application?

Vercel/local build

### Describe the Bug

When right-clicking on an image and choosing save as, the image is not webp. Although the response in dev tools is webp, both content-type and preview.
The issue does not persist in Firefox.

### Expected Behavior

Image should be served in webp when viewed in compatible Chrome version.

### To Reproduce

1. Use Next `Image`
2. View in chrome
3. Save image as

**Comment by rubenpoppe** [comment] 2021-09-13 11:24
Same result on MacOS 11.5, Chrome 93

**Comment by ijjk** [comment] 2021-09-19 15:11
Hi, this seems to be a Chrome bug and can be tracked [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1243412) I'm gonna close this since it's not a Next.js bug per-se but we are tracking this.

**Closed by ijjk** 2021-09-19 15:11 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
