### ISSUE TITLE
Returning 'notFound: true' in getServerSideProps when using Yarn 2 never loads in development mode

### ISSUE THREAD

**Issue by statico** [vercel/next.js#24286] opened 2021-04-20 21:12 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

15.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

If you use Yarn 2 and create a page with `getServerSideProps` that returns `{notFound: true}`, that page will never load.

For example, with `pages/test.jsx`:

```jsx
const Page = () => <h1>Hello JavaScript</h1>

export const getServerSideProps = async () => {
  return { notFound: true }
}

export default Page
```

And cURL:

```
$ curl --max-time 5 http://localhost:3000/test
curl: (28) Operation timed out after 5003 milliseconds with 0 bytes received
```

Sometimes I see Webpack erors:

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 4. Reason: future.webpack5 option not enabled https://nextjs.org/docs/messages/webpack5
error - ./.yarn/$$virtual/next-virtual-cc4f05f22a/0/cache/next-npm-10.1.3-435c930891-7e12ae9ea2.zip/node_modules/next/dist/next-server/lib/side-effect.js
Module not found: Can't resolve '/Users/ian/Desktop/test/node_modules/@babel/runtime/helpers/assertThisInitialized' in '/Users/ian/Desktop/test/.yarn/$$virtual/next-virtual-cc4f05f22a/0/cache/next-npm-10.1.3-435c930891-7e12ae9ea2.zip/node_modules/next/dist/next-server/lib'
event - build page: /next/dist/pages/_error
wait  - compiling...
error - ./.yarn/$$virtual/next-virtual-cc4f05f22a/0/cache/next-npm-10.1.3-435c930891-7e12ae9ea2.zip/node_modules/next/dist/next-server/lib/side-effect.js
Module not found: Can't resolve '/Users/ian/Desktop/test/node_modules/@babel/runtime/helpers/assertThisInitialized' in '/Users/ian/Desktop/test/.yarn/$$virtual/next-virtual-cc4f05f22a/0/cache/next-npm-10.1.3-435c930891-7e12ae9ea2.zip/node_modules/next/dist/next-server/lib'
```

### Expected Behavior

If you use Yarn 1, the page works as expected and shows Next's 404 page.

```
$ curl --max-time 5 http://localhost:3000/test
<!DOCTYPE html><html>
....
```

### To Reproduce

1. Clone https://github.com/statico/nextjs-yarn2-getserversideprops-bug
1. Run `yarn install`
1. Run `yarn run dev`
1. Navigate to http://localhost:3000/test which should show the Next.js 404 page, which is expected
1. Stop the server
1. Run `yarn set version berry`
1. Run `yarn install`
1. Run `yarn run dev`
1. Navigate to http://localhost:3000/test will hang forever and maybe show Webpack errors on the console

**Comment by statico** [comment] 2021-04-20 21:16
Update: If you build the site and use the production server with `yarn run build` and `yarn run start`, the 404 page will work correctly.

**Comment by xorander00** [comment] 2021-04-21 01:23
Might be related to #21828

I had a similar problem to what you describe and I fixed it (temporarily) by using yarn patch.  The issue is in the way the dev server works with the file system to detect build/ready/changed/etc, since yarn2 uses a virtual fs and thus the dev server never sees the changes.

**Comment by statico** [comment] 2021-04-21 03:20
You're right. This definitely sounds very similar to #21828.

**Comment by meglio** [comment] 2021-08-05 04:16
So is it correct that:

- in the dev mode, the workaround is to either providing own 404 and other error pages, or by using `yarn patch`
- in production, it works just fine

Also, is it still an issue with Next 11 as well?

**Comment by statico** [comment] 2021-08-05 05:20
Unfortunately I had to go back to Yarn v1. I don't have the time to diagnose this further, so you might want to close the issue.

**Comment by meglio** [comment] 2021-08-06 14:38
Please don't close. If it's still an issue, it should be open. Thanks.

**Comment by ijjk** [comment] 2021-10-16 05:35
Hi, this appears to be a duplicate of https://github.com/vercel/next.js/issues/21828 so I'm gonna close this in favor of that one please track this there.

**Closed by ijjk** 2021-10-16 05:35 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 15:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
