### ISSUE TITLE
Pages route suddenly fails with Headers Overflow Error.

### ISSUE THREAD

**Issue by haensl** [vercel/next.js#54709] opened 2023-08-29 10:53 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.16.1
      npm: 9.7.2
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

See below.

### To Reproduce

This is the route code, it splits traffic by iOS and other operating systems:

```
import { getSelectorsByUserAgent } from 'react-device-detect';
import { extUrl } from '../support/targets/ios';

const redirectHome = {
  redirect: {
    destination: '/',
    permanent: false
  },
  props: {}
};

const redirectExt = {
  redirect: {
    destination: extUrl,
    permanent: false
  },
  props: {}
};

export const getServerSideProps = async (ctx) => {
  const userAgent = ctx.req.headers['user-agent'] || '';
  const { isIOS } = getSelectorsByUserAgent(userAgent);

  const requestUrl = new URL(ctx.req.url, `https://${ctx.req.headers.host}`);

  const redirect = (() => {
    if (isIOS) {
      const _redirect = {
        ...redirectExt
      };
      
      return _redirect;
    } else {
      const _redirect = {
        ...redirectHome
      };

      return _redirect;
    }
  })();

  return redirect;
};

const Page = () => (
  <></>
);


export default Page;
```

### Describe the Bug

We maintain an app that still uses `pages/` routing. In this app there is a redirecting route that, depending on client OS redirects to an external third party or the landingpage (see reproduction section). The implementation uses `getServerSideProps()` to return a redirect object, e.g. 

```
{
  redirect: {
    destination: 'https://example.com',
    permanent: false
  },
  props: {}
}
```

This worked fine until recently, presumably the update to next 13.

Since then we're seeing the page crash at the redirect route with a 500. The server logs show a `'UND_ERR_HEADERS_OVERFLOW'` error with the following stack:

```
TypeError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:11576:11)\n    at async invokeRequest (/var/www/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)\n    at async invokeRender (/var/www/node_modules/next/dist/server/lib/router-server.js:254:29)\n    at async handleRequest (/var/www/node_modules/next/dist/server/lib/router-server.js:447:24)\n    at async requestHandler (/var/www/node_modules/next/dist/server/lib/router-server.js:464:13)\n    at async Server.<anonymous> (/var/www/node_modules/next/dist/server/lib/start-server.js:117:13)
cause: HeadersOverflowError: Headers Overflow Error
at Parser.trackHeader (/var/www/node_modules/next/dist/compiled/undici/index.js:1:59276)
at Parser.onHeaderValue (/var/www/node_modules/next/dist/compiled/undici/index.js:1:59155)
at wasm_on_header_value (/var/www/node_modules/next/dist/compiled/undici/index.js:1:55720)
at wasm://wasm/00036ac6:wasm-function[49]:0xf91
at wasm://wasm/00036ac6:wasm-function[68]:0x7316
at wasm://wasm/00036ac6:wasm-function[67]:0x154d
at wasm://wasm/00036ac6:wasm-function[21]:0x552
at Parser.execute (/var/www/node_modules/next/dist/compiled/undici/index.js:1:57682)
at Parser.readMore (/var/www/node_modules/next/dist/compiled/undici/index.js:1:57424)
at Socket.onSocketReadable (/var/www/node_modules/next/dist/compiled/undici/index.js:1:62761) {
  code: 'UND_ERR_HEADERS_OVERFLOW'
}
```

### Expected Behavior

The redirect route should work without throwing an exception.

### How are you deploying your application? (if relevant)

Google Cloud

**Comment by haensl** [comment] 2023-08-29 13:42
Unfortunately we're lacking the time to spend on creating a demo-repo for reproduction. However, for what it's worth and for anyone else arriving here:

Updating our container from Node.js LTS (18) to Latest (20) seems to have resolved the issue, i.e. we're no longer seeing this error pop up in server logs for 4 hours now.

**Comment by StarlinMarrero** [comment] 2023-08-29 19:26
I have the same issue, Im using Node TLS v18.17.1, NextJS 13.4.7

Localhost

Server Error
Error: Parse Error: Header overflow
This error happened while generating the page. Any console logs will be displayed in the terminal window.

**Comment by haensl** [comment] 2023-08-29 19:27
Ours has reappeared as well, i.e. Node v20 did not solve the issue.

**Comment by StarlinMarrero** [comment] 2023-08-30 15:09
the way I fixed the problem was me, I was setting too long header.

Nota: property response comes from NextResponse.next() I was using this code in middleware.ts.
this kind of problem could be for any header as well, it does not depend on the name of header.

![image](https://github.com/vercel/next.js/assets/42224994/c3a1b481-e55a-4ee6-914c-7dda149f90a9)

**Comment by adoprog** [comment] 2023-08-31 02:24
I have the same error after upgrading to any version above 13.4.9 (tested latest and canary too).

There is a related issue here https://github.com/nodejs/node/issues/47246 and it seems there is no way in NextJS to tweak this setting.

**Comment by adoprog** [comment] 2023-08-31 02:26
It is not possible to reduce the headers size for us as they are large because of the JWT token / Auth0 session.

**Comment by balazsorban44** [comment] 2023-08-31 11:47
Thanks for the context @adoprog. This sounds like a Node.js/undici bug then.

Note that if `globalThis.fetch` is available in the runtime environment (issue claims Node.js "18.16.1" and `fetch` has been [exposed](https://nodejs.org/api/globals.html#fetch) since 18.0.0), Next.js does nothing to patch that global value, so we can do nothing here, as we don't override the undici `Agent` in that case:

https://github.com/vercel/next.js/blob/ac56bcafa76ebec2350e9191b2d3a8cf6a36abf9/packages/next/src/server/node-polyfill-fetch.ts#L4

Without anyone adding a reproduction though, it's also not clear how bumping a Next.js version affected this compared to previous versions. Instead of commenting "same issue", etc. please provide us with a minimal code/reproduction that we can use to reproduce the issue to verify it. Any unhelpful comment will be marked as off-topic.

Thanks!

cc @Ethan-Arrowood if you have more advice here, but I feel that this should be fixed upstream by `undici` respecting the flag as suggested here: https://github.com/nodejs/node/issues/47246#issuecomment-1484026906

**Comment by balazsorban44** [comment] 2023-09-01 11:36
I opened a PR to fix this upstream in Node.js. You can follow along here: https://github.com/nodejs/undici/pull/2234

I'm closing this as it's not a Next.js bug, but how Node.js+undici works currently. When that PR lands in Node.js, you'll be able to set the Node.js flag `--max-http-header-size`

**Closed by balazsorban44** 2023-09-01 11:36 UTC
Labels: please add a complete reproduction, type: upstream, template: bug
