### ISSUE TITLE
[Example] with-sentry-simple fails to upload sourcemap on Vercel

### ISSUE THREAD

**Issue by TheHolyWaffle** [vercel/next.js#12454] opened 2020-05-03 20:09 UTC
# Bug report

## Describe the bug

The [with-sentry-simple](https://github.com/zeit/next.js/tree/canary/examples/with-sentry-simple) example results in a build failure when trying to push sourcemaps by using @sentry/webpack-plugin

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Reproduce example in [with-sentry-simple](https://github.com/zeit/next.js/tree/canary/examples/with-sentry-simple)
2. Make sure to specify SENTRY_ORG, SENTRY_PROJECT and SENTRY_AUTH_TOKEN environment variables on Vercel

Vercel build output shows the following:
```
22:00:59.955  Failed to compile.
22:00:59.955  Sentry CLI Plugin: Unable to determine version. Make sure to include `release` option or use the environment that supports auto-detection https://docs.sentry.io/cli/releases/#creating-releases
22:00:59.955  > Build error occurred
22:00:59.957  Error: > Build failed because of webpack errors
22:00:59.957      at build (/zeit/7adcd5d0/node_modules/next/dist/build/index.js:13:900)
22:00:59.993  error Command failed with exit code 1.
22:00:59.994  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
22:01:00.003  Error: Command "yarn run now-build" exited with 1
22:01:01.806  Done with "package.json"
```

## Expected behavior

Sourcemaps are correctly uploaded to Sentry without any build failure on Vercel.

## System information

- Nextjs 9.3.6
- @sentry/webpack-plugin: 1.11.1

## Additional context

Possible related issue: https://github.com/getsentry/sentry-webpack-plugin/issues/185

**Comment by 5tormTrooper** [comment] 2020-05-06 07:58
Same issue. You can see this happening even when running `npm run build` locally.

**Comment by TheHolyWaffle** [comment] 2020-05-11 10:18
Using `release: options.buildId` in SentryWebpackPlugin fixes the upload issue indeed. 

However, the `Sentry.init(...)` snippet in `_app.js` must also be updated. In there, the same `release` variable must be used as defined in `next.config.js`. This is to ensure that Sentry can link tracked errors to the correct corresponding release/sourcemaps. See https://docs.sentry.io/error-reporting/configuration/?platform=browsernpm#release

**Comment by sambokai** [comment] 2020-05-23 00:30
@TheHolyWaffle Did you end up updating `Sentry.init(...)`? How did you access buildId in `_app.js`?

**Comment by TheHolyWaffle** [comment] 2020-05-23 09:10
@sambokai I've created a new env variable in `next.config.js` which I passed to SentryWebpackPlugin as `release`. Then in `_app.js` I accessed that same env variable to use when calling `Sentry.init(...)`

**Comment by tomasdisk** [comment] 2020-06-21 06:39
I'm with the same issue using the new with-sentry example. I'll try your workaround, thanks!
[Example] with-sentry: https://github.com/vercel/next.js/blob/bef9b5610911532689dc251b7ceac72985e6b6dd/examples/with-sentry/next.config.js#L54

**Comment by georgiosd** [comment] 2020-06-28 18:25
For anyone that landed here, this seems to have been added to the example

**Comment by sharma0611** [comment] 2020-07-22 17:52
@TheHolyWaffle how did you create an environment variable from the build ID? Or did you not use the build ID at all anymore?

**Comment by sharma0611** [comment] 2020-07-22 19:39
@georgiosd It doesn't look like the example actually uses a release variable. See the sentry.init call in _app.js.

**Comment by georgiosd** [comment] 2020-07-23 04:55
@sharma0611 it gets included in the sourcemap upload but I haven't check if it's correctly reported when sentries are sent to the server.

**Comment by leerob** [comment] 2021-02-07 17:39
As @georgiosd mentioned, this has been added to the [with-sentry](https://github.com/vercel/next.js/tree/canary/examples/with-sentry) example 🙏

**Closed by leerob** 2021-02-07 17:39 UTC
Labels: type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-28 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
