### ISSUE TITLE
Production Fatal Error 

### ISSUE THREAD

**Issue by joacub** [vercel/next.js#52578] opened 2023-07-12 04:56 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
at validateURL (/app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/app-render/validate-url.js:24:19)
    at renderToHTMLOrFlight (/app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/app-render/app-render.js:102:51)
    at NextNodeServer.renderHTMLImpl (/app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/next-server.js:694:20)
    at /app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/next-server.js:685:105
    at NextTracerImpl.trace (/app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/lib/trace/tracer.js:90:20)
    at NextNodeServer.renderHTML (/app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/next-server.js:685:41)
    at doRender (/app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/base-server.js:1059:37)
    at cacheEntry.responseCache.get.incrementalCache.incrementalCache (/app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/base-server.js:1197:34)
    at /app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/response-cache/index.js:99:42
    at ResponseCache.get (/app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/response-cache/index.js:149:11)
Error: Invalid request URL
    at validateURL (/app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/app-render/validate-url.js:24:19)
    at renderToHTMLOrFlight (/app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/app-render/app-render.js:102:51)
    at NextNodeServer.renderHTMLImpl (/app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/next-server.js:694:20)
    at /app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/next-server.js:685:105
    at NextTracerImpl.trace (/app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/lib/trace/tracer.js:90:20)
    at NextNodeServer.renderHTML (/app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/next-server.js:685:41)
    at doRender (/app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/base-server.js:1059:37)
    at cacheEntry.responseCache.get.incrementalCache.incrementalCache (/app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/base-server.js:1197:34)
    at /app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/response-cache/index.js:99:42
    at ResponseCache.get (/app/node_modules/.pnpm/next@13.4.10-canary.3_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/server/response-cache/index.js:149:11)
```

### Link to the code that reproduces this issue or a replay of the bug

no response

### To Reproduce

Just update to latest canary version you have broken this really badly 

### Describe the Bug

500 server error

### Expected Behavior

no server error

### Which browser are you using? (if relevant)

no response

### How are you deploying your application? (if relevant)

no response

**Comment by joacub** [comment] 2023-07-12 18:54
@balazsorban44 can make a reproduction , this only happens in production in a certain point without notice, we dont know what is causing this, seems like there were a change in caches or something about bots conflicting with isr. bu i really dont know what is causing this, we just notice that when time pass, this happens to all the pages in the project.

**Comment by joacub** [comment] 2023-07-13 15:44
again failing, we have a production website failing again and again with no reason after working properly. is frustrating

<img width="1368" alt="image" src="https://github.com/vercel/next.js/assets/2091228/0bdfd359-0213-407d-901b-b06ab6e34f39">

**Comment by joacub** [comment] 2023-07-13 16:17
https://github.com/vercel/next.js/pull/52360
https://github.com/vercel/next.js/pull/51663/files

**Comment by joacub** [comment] 2023-07-13 16:29
this is the code failing:

```js
async function renderToHTMLOrFlight(req, res, pagePath, query, renderOpts) {
    const isFlight = req.headers[_approuterheaders.RSC.toLowerCase()] !== undefined;
    const pathname = (0, _validateurl.validateURL)(req.url);
```
there were a pr about changing the function that validates the url to rely on nodes validating url for performance reason, i dont see now the pr but i recall that.

as you can see you are expecting in a header an url that can be wrong and there is not catch of the error which is causing all website to crash

**Comment by xesrevinu** [comment] 2023-07-14 16:48
I encountered the same problem while using wrk for stress testing. `13.4.10 production`

`wrk -t12 -c400 -d30s http://127.0.0.1:3000`

```
Error: Invalid request URL
    at validateURL (/workspace/node_modules/.pnpm/next@13.4.10_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/app-render/validate-url.js:24:19
```

**Comment by joacub** [comment] 2023-07-15 16:09
> I encountered the same problem while using wrk for stress testing. `13.4.10 production`
> 
> `wrk -t12 -c400 -d30s http://127.0.0.1:3000`
> 
> ```
> Error: Invalid request URL
>     at validateURL (/workspace/node_modules/.pnpm/next@13.4.10_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/app-render/validate-url.js:24:19
> ```

Do you manage to fix or workaround we are getting this issue all the time and customers are starting to yield😔

**Comment by joacub** [comment] 2023-07-16 06:07
the error that fails the url is this: 

<img width="561" alt="image" src="https://github.com/vercel/next.js/assets/2091228/d99106e2-894c-4baa-8db7-5c573b00485b">

**Comment by xesrevinu** [comment] 2023-07-16 09:36
Hey @joacub What is your Node version? Can you currently reproduce the issue? Everything works fine when I revert back to node v18.16.0.

**Comment by joacub** [comment] 2023-07-16 16:56
> Hey @joacub What is your Node version? Can you currently reproduce the issue? Everything works fine when I revert back to node v18.16.0.
> 
> node 20.0.0 will have errors node 20.1.0 works fine

I have latest node version 20.4

**Comment by a4lmamun** [comment] 2023-07-16 17:26
`1|dp-v2-app | Error: Invalid request URL
1|dp-v2-app |     at validateURL (/opt/dp-v2-app/node_modules/next/dist/server/app-render/validate-url.js:24:19)
1|dp-v2-app |     at renderToHTMLOrFlight (/opt/dp-v2-app/node_modules/next/dist/server/app-render/app-render.js:120:51)
1|dp-v2-app |     at AppPageRouteModule.render (/opt/dp-v2-app/.next/server/chunks/5247.js:7402:52)
1|dp-v2-app |     at doRender (/opt/dp-v2-app/node_modules/next/dist/server/base-server.js:1068:40)
1|dp-v2-app |     at cacheEntry.responseCache.get.incrementalCache.incrementalCache (/opt/dp-v2-app/node_modules/next/dist/server/base-server.js:1215:34)
1|dp-v2-app |     at /opt/dp-v2-app/node_modules/next/dist/server/response-cache/index.js:99:42
1|dp-v2-app |     at ResponseCache.get (/opt/dp-v2-app/node_modules/next/dist/server/response-cache/index.js:149:11)
1|dp-v2-app |     at NextNodeServer.renderToResponseWithComponentsImpl (/opt/dp-v2-app/node_modules/next/dist/server/base-server.js:1134:53)
1|dp-v2-app |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

I got same issue today **500 | Internal Server Error**. Running on nextjs 13.4.10 with node v20.2.0.

**Comment by joacub** [comment] 2023-07-16 17:54
🥲🥲🥲🥲🥲

**Comment by cyrillbolliger** [comment] 2023-07-17 08:58
same issue here:
```
2023-07-17T08:27:28.910 app[683d023f792528] cdg [info] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-07-17T08:27:28.915 app[683d023f792528] cdg [info] Error: Invalid request URL
2023-07-17T08:27:28.915 app[683d023f792528] cdg [info] at validateURL (/app/node_modules/next/dist/server/app-render/validate-url.js:24:19)
2023-07-17T08:27:28.915 app[683d023f792528] cdg [info] at renderToHTMLOrFlight (/app/node_modules/next/dist/server/app-render/app-render.js:120:51)
2023-07-17T08:27:28.915 app[683d023f792528] cdg [info] at A
ppPageRouteModule.render (/app/.next/server/chunks/674.js:7538:52)
2023Invalid request URL-07-17T08:27:28.915 app[683d023f792528] cdg [info] at doRender (/app/node_modules/next/dist/server/base-server.js:1068:40)
2023-07-17T08:27:28.915 app[683d023f792528] cdg [info] at cacheEntry.responseCache.get.incrementalCache.incrementalCache (/app/node_modules/next/dist/server/base-server.js:1215:34)
2023-07-17T08:27:28.915 app[683d023f792528] cdg [info] at /app/node_modules/next/dist/server/response-cache/index.js:99:42
2023-07-17T08:27:28.915 app[683d023f792528] cdg [info] at ResponseCache.get (/app/node_modules/next/dist/server/response-cache/index.js:149:11)
2023-07-17T08:27:28.915 app[683d023f792528] cdg [info] at NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/next/dist/server/base-server.js:1134:53)
2023-07-17T08:27:28.915 app[683d023f792528] cdg [info] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

node: v20.4.0
next: 13.4.10

also only happens in production.

any fixes / workarounds yet?

**Comment by sandrotanner** [comment] 2023-07-17 09:12
[#52353](https://github.com/vercel/next.js/pull/52353)?

**Comment by joacub** [comment] 2023-07-17 15:48
> [#52353](https://github.com/vercel/next.js/pull/52353)?

That’s the one I was referencing before . That’s the change is braking everything

**Comment by joacub** [comment] 2023-07-17 16:22
there is something wrong with this canParse function, in my case is failing a slash and it should not fail, so my guess is that next or something else is polifying the function and is not working properly, when using the canParse in a raw node with the same params, does not fail and works a expected, but in the next context fails at some point, or the slash is a special character or something, i dont really know.

**Comment by joacub** [comment] 2023-07-17 16:24
this:
```js
const test = URL.canParse('/ ', 'http://n');
console.log(test);
```
return true, but in next context sometimes return false which cause the function to return a exception

**Comment by joacub** [comment] 2023-07-17 16:34
open a issue in nodejs:

https://github.com/nodejs/node/issues/48816

**Comment by anonrig** [comment] 2023-07-17 17:50
I opened a fix for this in the Node repository. Hopefully, it can be included in the next LTS release - v18.17.0 - https://github.com/nodejs/node/pull/48817

**Comment by joacub** [comment] 2023-07-17 18:50
> I opened a fix for this in the Node repository. Hopefully, it can be included in the next LTS release - v18.17.0 - [nodejs/node#48817](https://github.com/nodejs/node/pull/48817)

this is happening also in the 20.4 version, the fix you submit is only for older versions ?

**Comment by joacub** [comment] 2023-07-17 18:53
Are you a worker of nextjs ? the pr you sibmited to nextjs should be revert untile this is fixed by node

**Comment by anonrig** [comment] 2023-07-17 19:46
> > I opened a fix for this in the Node repository. Hopefully, it can be included in the next LTS release - v18.17.0 - [nodejs/node#48817](https://github.com/nodejs/node/pull/48817)
> 
> this is happening also in the 20.4 version, the fix you submit is only for older versions ?

The PR I've opened will be backported to Node 18 and 20 as well.

**Comment by maxkvmcloud** [comment] 2023-07-20 17:15
This error started showing for us after the nextjs 13.4.10 update using node 20.4.0, but reverting to nextjs 13.4.9 seemed to resolve the issue until last night.

We moved to node 18.7.0 from 20.4.0 after the latest downtime, but the site went offline again within an hour showing the same error. Should this have been fixed in the node 18.7.0 release?

```
Error: Invalid request URL
    at validateURL (/opt/maxkvm/app/validate-url.js:24:19)
    at renderToHTMLOrFlight (/opt/maxkvm/app/app-render.js:120:51)
    at AppPageRouteModule.render (/opt/maxkvm/app/335.js:20357:52)
    at doRender (/opt/maxkvm/app/base-server.js:1068:40)
    at cacheEntry.responseCache.get.incrementalCache.incrementalCache (/opt/maxkvm/app/base-server.js:1215:34)
    at /opt/maxkvm/app/index.js:99:42
    at ResponseCache.get (/opt/maxkvm/app/index.js:149:11)
    at NextNodeServer.renderToResponseWithComponentsImpl (/opt/maxkvm/app/base-server.js:1134:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Now using 20.1.0 since @xesrevinu mentioned that version works fine.

**Comment by anonrig** [comment] 2023-07-20 17:22
This issue does not exist in Node 18.7.0, or any LTS release. It was a false alarm.

**Comment by joacub** [comment] 2023-07-20 18:02
> This issue does not exist in Node 18.17.0, or any LTS release. It was a false alarm.

So when it is happening ? We tested and when stressed this is showing up

**Comment by anonrig** [comment] 2023-07-20 18:13
This particular code does work as expected as of `Node v18.17.0` which is released 2 days ago. `v20.5.0` which will be released today/tomorrow (ref: https://github.com/nodejs/node/releases/tag/v20.5.0), will also fix this in version 20.


```
while (true) {
  const test = URL.canParse('/ ', 'http://n');
  console.log(test);
}
```

**Comment by maxkvmcloud** [comment] 2023-07-20 20:00
It seems that our test with node 18.17.0 didn't actually use that version -- the user account still had 20.4.0 in $PATH.

Now running a custom build of 20.5.0.

**Comment by styfle** [comment] 2023-07-25 22:15
Great! Sounds like its fixed upstream. Can we close this issue?

**Closed** 2023-08-14 15:50 UTC
Labels: please add a complete reproduction, template: bug, type: needs triage
