### ISSUE TITLE
Running multiple next projects

### ISSUE THREAD

**Issue by MahdiGraph** [vercel/next.js#35070] opened 2022-03-05 07:56 UTC
### Verify canary release

- [x] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 14 13:59:45 UTC 2022
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

when i install next globally like this : `npm i next -g` i cant run multiple projects with next start on different ports and it makes interference between projects

there is no problem until you send a request to second app , then show an 500 error response and this irrelevant error message on console :
`Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings ...`

for fixing this issue i use `npm run start -- -p 3001` directly from project folder

### Expected Behavior

we must be able to run multiple projects with globally installed version of next and it will better if `next start` detect empty ports for run application just like `npm run dev`

### To Reproduce

use `npm run start -- -p 3001` instead of `next start --port=3001`

**Comment by balazsorban44** [comment] 2022-03-05 23:17
Sounds like a duplicate of https://github.com/vercel/next.js/issues/35029. Could you expand on the reason for installing `next` globally?

**Comment by MahdiGraph** [comment] 2022-03-06 06:10
> 

i installed globally because next command doesn't work for me in project folder

**Comment by balazsorban44** [comment] 2022-03-07 08:51
Closing, as it sounds like a project issue then, not a bug in Next.js. You can still follow 
#35029 instead.

**Closed by balazsorban44** 2022-03-07 08:51 UTC
Labels: template: bug, area: Application Code
