### ISSUE TITLE
getServerSideProps shall not crash when there is no return sentence

### ISSUE THREAD

**Issue by agreatfool** [vercel/next.js#15111] opened 2020-07-13 06:54 UTC
# Bug report

## Describe the bug

getServerSideProps crash the page when there no return sentence given.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new page: "pages/mytest.tsx"
2. Define a getServerSideProps function, and leave it empty
3. Open the page: http://localhost:8080/mytest

## Expected behavior

```typescript
import {GetServerSideProps, GetServerSidePropsContext} from "next";
export const getServerSideProps: GetServerSideProps = async (ctx: GetServerSidePropsContext<{}>) => {
  return {props: {}}; // even without this, page shall be displayed without errors
};
```

## Screenshots

![截屏2020-07-13 下午2 51 31](https://user-images.githubusercontent.com/195293/87278950-6275dd80-c518-11ea-8bdc-128cc9864848.png)

## System information

- OS: [macOS 10.15.5]
- Browser (if applies) [Chrome 83.0.4103.116]
- Version of Next.js: [9.4.4]
- Version of Node.js: [v10.15.2]

## Additional context

N/A

**Comment by jamesmosier** [comment] 2020-07-17 01:55
The error message appears to be greatly improved (tested with `9.4.5-canary.36`). 

Using this code:

```js
export default function MyPage() {
  return <div>test</div>
}

export const getServerSideProps = () => {}
```

the error that it displayed to the user is ```Error: Your `getServerSideProps` function did not return an object. Did you forget to add a `return`?``` 


<img width="994" alt="Screen Shot 2020-07-16 at 9 49 18 PM" src="https://user-images.githubusercontent.com/2854919/87739582-3a071100-c7ae-11ea-8724-2f08cec92951.png">


I think this developer experience is best because having an empty `getServerSideProps` function would force the page to be server rendered when it doesn't need to be (since `getServerSideProps` is empty anyway).

**Comment by agreatfool** [comment] 2020-07-17 02:31
In my scenario, I just want to force some pages to use SSR. So I previously wrote the empty function(I thought next.js would handle it) and encountered the error. 

Actually write a function with some return sentence is not a big work. If you guys think error shall be given by design, I just think it's OK.

**Comment by Timer** [comment] 2020-07-17 15:59
Closing per https://github.com/vercel/next.js/issues/15111#issuecomment-659784213, thanks!

**Closed by Timer** 2020-07-17 15:59 UTC
Labels: good first issue, kind: story

**Comment by Ariiieee** [comment] 2021-09-24 10:53
I am currently having this same issue and I have no idea how to solve it

**Comment by lilfrootyloops** [comment] 2021-11-29 14:53
@Ariiieee I'm currently experiencing this issue too. Were you able to identify a fix to resolve the issue for yourself?

**Comment by balazsorban44** [comment] 2022-01-27 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
