### ISSUE TITLE
Tailwind CSS + Emotion production Cannot read property 'theme' of undefined

### ISSUE THREAD

**Issue by ghost** [vercel/next.js#27781] opened 2021-08-05 05:13 UTC
### What example does this report relate to?

with-tailwindcss-emotion

### What version of Next.js are you using?

latest (11.0.1)

### What version of Node.js are you using?

14.17.3

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

npm run dev

### Describe the Bug

npx create-next-app --ts -e with-tailwindcss-emotion twopointoh
cd twopointoh
npm run dev

produces this error

error - ./pages/_app.js
TypeError: Cannot read property 'theme' of undefined

### Expected Behavior

It should compile and run in the browser

### To Reproduce

See description

**Comment by ch4nd4n** [comment] 2021-11-24 12:54
Duplicate of - https://github.com/vercel/next.js/issues/26337
to solve it

1. Downgrade tailwindcss to 2.1.4 in `package.json`
2. comment out mode jit in `tailwinds.config.js`

delete .next folder and reinstall dependencies. I wrote about it at https://www.chandankumar.com/tutorial/nextjs-tailwind-emotion-setup

**Comment by balazsorban44** [comment] 2021-12-07 01:36
Duplicate of #26337

**Closed by balazsorban44** 2021-12-07 01:36 UTC
Labels: area: examples, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
