### ISSUE TITLE
Multiple pages folder using the same config file

### ISSUE THREAD

**Issue by dillonraphael** [vercel/next.js#3027] opened 2017-10-01 21:38 UTC
I have 2 next.js apps that need to use the same package.json & next.config.js file but with different sub-routes. One being "/" and the other "/dashboard/*". Is there a way to include multiple pages & static folders to the build process?

I currently set a custom directory inside the next object when using a custom express server. But when trying to offer an array, I get an error stating it accepts strings only.

**Comment by DullReferenceException** [comment] 2018-05-24 20:57
Seems somewhat related to https://github.com/zeit/next.js/pull/4406.

**Comment by kachkaev** [comment] 2019-07-17 17:53
A few thoughts following app upgrades to Next 9: https://github.com/zeit/next.js/issues/4315#issuecomment-512360448

**Comment by Timer** [comment] 2020-07-19 05:35
Closing this feature request as it has been extensively discussed in the linked issues above.

We highly suggest you use a monorepo setup and are not currently exploring having two Next.js apps co-located in the same folder.

**Closed by Timer** 2020-07-19 05:35 UTC
Labels: type: feature request

**Comment by balazsorban44** [comment] 2022-01-29 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
