### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by florianbress** [vercel/next.js#50158] opened 2023-05-22 12:21 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.3.1
    Relevant packages:
      next: 13.4.4-canary.0
      eslint-config-next: 13.4.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Link to the code that reproduces this issue or a replay of the bug

it's a private repository.

### To Reproduce

i ran pnpm install and next dev and when the page loaded it showed me the error

### Describe the Bug

When spinning up the app, i am getting this error. I am using pages directory with version 13.4.3

### Expected Behavior

It should not show me this error as I am importing react within the two components.

### Which browser are you using? (if relevant)

Chrome 113.0.5672.127

### How are you deploying your application? (if relevant)

Uing vercel but it is happening locally

**Comment by florianbress** [comment] 2023-05-22 13:44
> @florianbress are you using `nx` ? I'm getting that issue if I'm on nx's `16.2.1` ... on `16.1.0` it seems to be working fine 🤔

I am not. simply just nextjs

**Comment by rmachado-studocu** [comment] 2023-05-22 13:46
Yeah to be fair, the issue with `nx@>=16.1.1` seems to be that they added support for `next@>=13.4.0` which indeed seems to cause an issue...

**Comment by florianbress** [comment] 2023-05-22 13:49
How should I make a reproduction... @balazsorban44 ? It's a big codebase we have. I am happy to get into a call tho.

**Comment by florianbress** [comment] 2023-05-22 13:50
i even tried downgrading

**Comment by florianbress** [comment] 2023-05-22 13:52
Wait. i downgraded even further to 13.2.0, and the issue is gone...

**Comment by shuding** [comment] 2023-05-22 16:14
Hi, this seems to be a duplicate of #48518 and we'll track there, thanks!

**Closed by shuding** 2023-05-22 16:14 UTC
Labels: please add a complete reproduction, template: bug, type: needs triage
