### ISSUE TITLE
The error overlay should not be dismissable for a server error

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#13955] opened 2020-06-09 16:06 UTC
# Bug report

When a "Server Error" (runtime) occurs, the error overlay should not be dismissable. Similar to a compile error, but not full screen.

## To Reproduce

Cause a runtime error in your rendering function on the server.

## Expected behavior

The overlay should not be dismissable. It currently can be minimized and reveals a blank page.

**Comment by darshkpatel** [comment] 2020-06-10 05:18
I'll take this up

**Comment by eKhattak** [comment] 2020-06-10 10:09
I'll write a fix for this one,

**Closed** 2020-07-30 04:57 UTC
Labels: kind: bug, priority: p2

**Comment by balazsorban44** [comment] 2022-01-29 19:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
