### ISSUE TITLE
React does not recognize the `blurDataURL` prop on a DOM element.

### ISSUE THREAD

**Issue by scurrilus-funke** [vercel/next.js#28193] opened 2021-08-17 10:50 UTC
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

15.5.1

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOs

### How are you deploying your application?

Vercel, Amazon Webservice

### Describe the Bug

` Warning: React does not recognize the 'blurDataURL' prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `blurdataurl` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
`

The implementation of Img placeholder with 'blur' and 'blurDataURL' works perfect, but by running jest Test with Img component the console outputs a warning. Write spell to lowercase breaks working functionality.

### Expected Behavior

Run jest test without warning.

### To Reproduce

Test Img component with jest.

## Component

`<Image
            width={width}
            height={height}
            src={imgSrc}
            alt={alt}
            title={title}
            sizes={sizes}
            className={className}
            quality={isValidSrc ? quality : 100}
            priority={priority}
            placeholder="blur"
            blurDataURL={imgSrc}
            loading={loading}
            layout={layout}
            onError={() => setSrcType(isValidSrc ? 'ratioFallback' : 'defaultFallback')}
            unoptimized={unoptimized}
            data-testid='img'}
        />`

## Jest Test

`test('Img Test', () => {
    const { getByTestId, queryByTestId } = render(<Img ratio="16:9" src="https://www.nrz.de/img.jpg" className="test" />);
    expect((getByTestId('img') as HTMLImageElement).src).toBe('https://www.nrz.de/img.jpg');
});`

**Comment by vehidt** [comment] 2021-08-21 10:34
I don't know if Img is a custom component that you've created and inside you are using the Image component from Next.js, or you made a mistake and try rendering Img instead of Image. If you have a custom Img component try and see if you are trying to pass prop to DOM element via {...props}. Usually passing props to DOM elements is causing this, since those don't exist on them.

Something like:

`export default function Img({ children, ...rest }) {
  return <div {...rest}>Content</div>;
}`

**Comment by ijjk** [comment] 2021-10-05 03:59
Closing per above as this doesn't appear to be a bug with `next/image` and is instead related to user code

**Closed by ijjk** 2021-10-05 03:59 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 16:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
