### ISSUE TITLE
Dynamic getStaticProps Page with i18n (locales) and fallback:true does not build

### ISSUE THREAD

**Issue by diegopelusa** [vercel/next.js#24050] opened 2021-04-14 09:54 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

12.19.0

### What browser are you using?

Firefox, Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

npm run build && npm run start (local machine)

### Describe the Bug

By building a page with dynamic getStaticProps and i18n, I get a build error if fallback is set to true.
When building the same page but with fallback set to false, it builds correctly. The dynamic pages contained in paths are build correctly.

This is my configuration in next.config.js:
```
  i18n: {
    locales: ["de", "en", "es", "fr", "it"],
    defaultLocale: "es",
  },

```

This is my getStaticPaths for the page that I want to build:
(I put here just the version with 5 paths prerendered. The same happens when paths is empty)

```
export const getStaticPaths: GetStaticPaths<{ id: string }> = async (
  ctx: GetStaticPathsContext
) => {
  // Read the first 5 Recipes from the DB
  const recipes = await apiGetRecipes(5);
  const paths = recipes
    .map((a) => {
      return [
        { params: { id: a.id.toString() }, locale: "en" },
        { params: { id: a.id.toString() }, locale: "es" },
        { params: { id: a.id.toString() }, locale: "fr" },
        { params: { id: a.id.toString() }, locale: "de" },
        { params: { id: a.id.toString() }, locale: "it" },
      ];
    })
    // NOTE: The reduce is to flat the array of arrays!!!
    .reduce((acc, val) => acc.concat(val), []);

  return {
    fallback: true,
    paths,
  };
};

```

And this is the error by building:

```
> Build error occurred
Error: Export encountered errors on following paths:
        /de/recipe/[id]
        /en/recipe/[id]
        /es/recipe/[id]
        /fr/recipe/[id]
        /it/recipe/[id]
    at f:\git_f\web-client-nextjs\node_modules\next\dist\export\index.js:31:1106
    at async Span.traceAsyncFn (f:\git_f\web-client-nextjs\node_modules\next\dist\telemetry\trace\trace.js:5:584)
    at async f:\git_f\web-client-nextjs\node_modules\next\dist\build\index.js:43:49
    at async Span.traceAsyncFn (f:\git_f\web-client-nextjs\node_modules\next\dist\telemetry\trace\trace.js:5:584)
    at async f:\git_f\web-client-nextjs\node_modules\next\dist\build\index.js:25:1475
    at async Span.traceAsyncFn (f:\git_f\web-client-nextjs\node_modules\next\dist\telemetry\trace\trace.js:5:584)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web-client-diego-nextjs@0.1.0 build: `next build`
npm ERR! Exit status 1

```

### Expected Behavior

I expect that the build works and generate the dynamic pages contained in paths.
And when a page with a new id is called, then that page will be first statically generated, because fallback was set to true.

The output after building the App, when fallback was set to false is like this.
I would expect the same output in the case of fallback set to true.

```
info  - Generating static pages (83/83)
info  - Finalizing page optimization

Page                                       Size     First Load JS
┌ λ /                                      1.74 kB        71.7 kB
├   /_app                                  0 B            69.9 kB
├ ○ /404                                   3.79 kB        73.7 kB
├ ● /recipe/[id]                           1.46 kB         135 kB
├   ├ /en/recipe/5908
├   ├ /es/recipe/5908
├   ├ /fr/recipe/5908
├   └ [+22 more paths]

```

### To Reproduce

This is my getStaticPaths for the page that I want to build:
(I put here just the version with 5 paths prerendered. The same happens when paths is empty)

```
export const getStaticPaths: GetStaticPaths<{ id: string }> = async (
  ctx: GetStaticPathsContext
) => {
  // Read the first 5 Recipes from the DB
  const recipes = await apiGetRecipes(5);
  const paths = recipes
    .map((a) => {
      return [
        { params: { id: a.id.toString() }, locale: "en" },
        { params: { id: a.id.toString() }, locale: "es" },
        { params: { id: a.id.toString() }, locale: "fr" },
        { params: { id: a.id.toString() }, locale: "de" },
        { params: { id: a.id.toString() }, locale: "it" },
      ];
    })
    // NOTE: The reduce is to flat the array of arrays!!!
    .reduce((acc, val) => acc.concat(val), []);

  return {
    fallback: true,
    paths,
  };
};

```

**Comment by ijjk** [comment] 2021-04-17 22:11
Hi, it sounds like the fallback rendering case is not being handled correctly. Inside of the page's component you need to use `router.isFallback` to render a loading screen when `fallback: true` is being used, see additional information here in the docs https://nextjs.org/docs/basic-features/data-fetching#fallback-pages

I'm going to close this since it doesn't appear to be an issue, if you are still having trouble with this feel free to respond with additional information.

**Closed by ijjk** 2021-04-17 22:11 UTC
Labels: template: bug

**Comment by diegopelusa** [comment] 2021-04-20 10:06
I found the error. 
It was my error!!!
It was not clear to me, that when writing fallback:true, then the following code (or equivalent) must be writen:
```
if (router.isFallback) {
    return <div>Loading...</div>;
  }
```
I was just swapping from fallback:false to fallback:true, without having the above code.
That provoked the error.
The tag "template:bug" can be removed!
Many thanks!

**Comment by balazsorban44** [comment] 2022-01-28 11:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
