### ISSUE TITLE
[i18n + catch-all + domain] not loading the right landing page locale

### ISSUE THREAD

**Issue by dohomi** [vercel/next.js#19513] opened 2020-11-25 07:13 UTC
# Bug report

## Describe the bug

I am trying to convert a project to the new i18n feature. Everything works but not the initial loading of the landing page. Always the `defaultLocale` which is `en` is being loaded, not the `defaultLocale` based on the `domains` setup

## To Reproduce

```js
// one single [[...index]].ts endpoint to catch all pages of the CMS

// next.config.js
module.exports = {
  i18n: {
    locales: ['en', 'de'],
    defaultLocale: 'en',
    domains: [
      {
        domain: 'students-en.now.sh',
        defaultLocale: 'en'
      },
      {
        domain: 'students-de.now.sh',
        defaultLocale: 'de'
      }
    ]
  }
}
```

## Expected behavior

https://students-de.now.sh should load german language
https://students-en.now.sh should load english language

But both endpoints are loading the english language. I would need to load 
https://students-de.now.sh/de/home to load the german version of the landing page.

## Additional information

With this setup it is possible to load a german version on the english domain:
https://students-en.now.sh/de/home 
I think this internally should redirect to the configured german domain?

## System information

- Browser: All
- Version of Next.js: 10.0.3
- Version of Node.js: 12.x
- Deployment: Vercel

**Comment by ijjk** [comment] 2020-12-30 04:26
Hi, I'm not able to reproduce this on the latest version of Next.js `v10.0.5-canary.3`, please update and give it a try! Also, please make sure the locale domains are assigned to your latest deployment.

**Closed by ijjk** 2020-12-30 04:26 UTC
Labels: kind: bug, type: needs investigation

**Comment by lisilinhart** [comment] 2021-05-19 14:50
I have seen a similar bug with the following next-config.js setup:
When I start it on a [[...slug]].js catch-all route, it will always start on http://localhost:3000/de instead of just http://localhost:3000/ or http://localhost:3000/en. If I change the `de` to `DE`, it doesn't happen

`
module.exports = {
    i18n: {
        locales: ['en', 'de'], 
        defaultLocale: 'en',
    },
}
`

**Comment by dohomi** [comment] 2021-05-20 01:48
@lisilinhart this is not a bug its a feature: if you have a German browser you will directly redirected to `/de`,. Changing it to "DE" just breaks the locale handling because its uppercased.
You can disable the automatic detection: https://nextjs.org/docs/advanced-features/i18n-routing#disabling-automatic-locale-detection
Hope this helps and is the actual issue which you are facing.

**Comment by balazsorban44** [comment] 2022-01-28 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
