### ISSUE TITLE
Memory leak in Image Optimization

### ISSUE THREAD

**Issue by Pythe1337N** [vercel/next.js#23189] opened 2021-03-18 13:37 UTC
### What version of Next.js are you using?

10.0.9

### What version of Node.js are you using?

14.15.5

### What browser are you using?

Chrome

### What operating system are you using?

alpine (docker image)

### How are you deploying your application?

express server

### Describe the Bug

Upgrading from 10.0.7 to 10.0.8 or 10.0.9 results in a server side memory leak when using the <Image /> component.
Consumes over 1GB of memory after only 10-20 image optimizations.

### Expected Behavior

Memory usage should be normal.

### To Reproduce

Import Image from 'next/image' and use it as the the documentation says https://nextjs.org/docs/api-reference/next/image with an allowed external image source.
In this case layout="fixed" was used.

**Comment by shuding** [comment] 2021-03-18 14:21
Could you please try installing the latest canary (`next@canary`)? It should be fixed there, see also #22925.

**Comment by Pythe1337N** [comment] 2021-03-18 14:45
Tried with 10.0.10-canary.4 and I'm still having issues. Been running in a 512 MB ram  docker image up to version 10.0.7. Increased it to 1024 MB to test this, but it's still using all of the memory available.

**Comment by fabb** [comment] 2021-03-19 08:10
we are also having memory leaks and pod crashes since updating from next.js 10.0.7 to 10.0.9 yesterday. we updated a few other dependencies as well, so it's not yet certain that the next.js updated caused the issue. note that we do not use the image optimization feature.

**Comment by Pythe1337N** [comment] 2021-03-19 08:39
I did a rollback on all deps other than for next and still had the same problem. The memory leak might be part of the image optimization, but that is what is running slow. To fetch an image from the _next/image endpoint is really slow while everything else seems to run as usual. Will try to only fetch images to try to pinpoint the leak.

**Comment by fabb** [comment] 2021-03-19 09:13
i did a rollback of just next.js to 10.0.7 and it fixed the issue. so it's definitely caused by next.js.

**Comment by shuding** [comment] 2021-03-19 12:15
We've fixed some know issues regarding memory usage in canary already. It would be great if you can test `next@canary` vs latest stable release and share more information, so we can identify the cause quickly!

**Comment by ahmetuysal** [comment] 2021-03-19 14:09
I think the problem persists in `10.0.10-canary.5`. Memory utilization is steadily increasing in our website deployed to AWS Beanstalk. It was stable until I updated next to `10.0.10-canary.5` from  `10.0.7`.
![image](https://user-images.githubusercontent.com/26417668/111792740-98543880-88d5-11eb-8408-1280a7269995.png)

**Comment by tiagocarmo** [comment] 2021-03-19 14:13
I had the same memory problem here.
We did some tests on an application that we developed, when version 10.0.7 occurs, the memory increases consumption.
With version 10.0.6 it is ok to use.

**Comment by stefanprobst** [comment] 2021-03-19 16:20
as i understand it, these memory issues are caused by the switch from `sharp` to `squoosh` in https://github.com/vercel/next.js/pull/22253. the reason for the change given in that pr is that:

> the native sharp dependency (which doesn't work on some Linux variants, nor M1 Mac)

i wonder if this is still a valid concern with the soon-to-be-released `sharp` v0.28 (see [here](https://github.com/lovell/sharp/issues/2604)). i'm also curious about a response to the sharp maintainer's comment [here](https://github.com/vercel/next.js/issues/20915#issuecomment-797763705).

**Comment by gustavpursche** [comment] 2021-03-22 18:24
Alrighty, then here again :)

v10.0.10-canary.7 doesn't fix the issue in my case. It's still:

`10.0.10-canary.7`: 1960MB
`10.0.7`: 230MB

**Comment by mjenzen** [comment] 2021-03-22 21:14
canary 7 didnt fix the issue for me either.  I am showing a massive memory leak on my Windows 10 dev machine at 6,5GB/16GB and 3.5GB/8GB on my Azure Linux App Service.  The resources are never recovered until the dev process or app service are stopped

**Comment by jdfm** [comment] 2021-03-24 20:32
> i did a rollback of just next.js to 10.0.7 and it fixed the issue. so it's definitely caused by next.js. as i said, we are not using the image optimization feature at all.

Our team had the same situation as @fabb where we upgraded to 10.0.8 and we were **not** using next/image, yet our containers were running out of memory. After downgrading to 10.0.7 our containers were back to running normally.

Interestingly, this only surfaced in production containers. Our local environments didn't face this issue, and our playground (something like dev/staging) environments also didn't have this issue. We still haven't been able to determine why.

**Comment by avisra** [comment] 2021-03-25 16:44
I just found that we are also experiencing this same bug while hosting in AWS (elastic beanstalk). It is at 98% memory consumption :(

**Comment by joe-bell** [comment] 2021-03-26 08:05
I believe this issue could be related to something I'm seeing when using Plaiceholder on Vercel with `next@10.0.9`:
https://github.com/joe-bell/plaiceholder/issues/60

```sh
00:01:35.213 | info  - Finalizing page optimization...
-- | --
00:01:41.224 | sh: line 1:   729 Segmentation fault      (core dumped) next build
00:01:41.234 | npm ERR! code ELIFECYCLE
00:01:41.234 | npm ERR! errno 139
```

**Comment by andrijavulicevic** [comment] 2021-03-26 08:54
The same issue on my side had to switch from 1GB to 6GB instance (though memory usage keeps at between 4 and 5GB) on GAE. Tried canary build `10.0.10-canary.11` and it seems way better, average memory consumption is around 1.5GB.

**Comment by thomasgrivet** [comment] 2021-03-28 17:50
Hello!
Same issue on my end, had to switch from a 512mb instance to a 2gb instance and even then it still crash from time to time.
I tried using 10.0.9 and the latest canary with no luck. I just got back to using 10.0.7, it seems to be working just fine for now.

**Comment by henryStelle** [comment] 2021-03-29 16:04
Hello,
I see that #23188 has been merged in the 10.1.0 release - has this been confirmed to fix this issue? Also, Sharp 0.28 was just released, does it merit a second look considering https://github.com/vercel/next.js/issues/23189#issuecomment-802951488?

**Comment by henryStelle** [comment] 2021-03-29 20:57
In my initial testing of 10.1.1 using the node:14.16.0-alpine3.10 docker image, the container's memory usage hit 2.5GiB within 45 seconds and didn't decrease. In comparison, 10.0.7 spikes to 400MiB when images are being generated and then falls back to 145 MiB. As a side note, adding `RUN apk add --no-cache libc6-compat` to the Dockerfile when testing 10.1.1 resulted in the container quickly consuming over 3.5GiB, at which point the instance became unresponsive and was restarted. Is anyone else seeing similar performance issues?

**Comment by fabb** [comment] 2021-03-30 05:24
Should we rename this issue since it‘s not only happening when using image optimization? Or should we rather create a new one?

**Comment by gustavpursche** [comment] 2021-03-30 06:57
I've tried with `10.1.1` yesterday and the leak is still happening: 

10.1.1-canary.7: 1630MB
10.0.7: 230MB

It has gotten better, but it's still a lot more than it used to be in 10.0.7. Unfortunately.

**Comment by tbanys** [comment] 2021-03-30 07:05
@gustavpursche are you using next/image component or memory usage high even without it?

**Comment by gustavpursche** [comment] 2021-03-30 07:09
That's something I haven't tested yet. I'm not super good at debugging at this level 🤦🏽 If it helps I can provide access to the private repo (the site itself is very small). I'm using a shared hosting and whenever (after 10.0.7) someone loads a page with a lot of images (e.g. https://sibylleberg.com/en/books) the process is terminated by the hoster. The site uses quite a lot `next/image`s.

**Comment by JVictorV** [comment] 2021-03-30 10:29
Got even worse for me with thew new next version + webpack 5. My solution was to rollback to the 10.0.6 version

**Comment by karlhorky** [comment] 2021-03-30 11:01
Yeah, I was a big supporter of trying out something different other than `sharp`, but the `squoosh` solution just doesn't cut it for anything other than usage on an M1.

Please consider adding back `sharp` for all non-M1 environments @shuding . I say this as an M1 user myself.

**Comment by kmdev1** [comment] 2021-03-30 15:05
I've found a race condition in the image optimisation that seems to not only relate to this but also severely exaggerates it:

#23436

**Comment by timneutkens** [comment] 2021-03-31 09:53
Please try out Next.js canary which includes #23565: `yarn add next@canary`

**Comment by gustavpursche** [comment] 2021-03-31 10:02
@timneutkens Thanks for the new release! I can see that is gotten much better:

10.1.3-canary.0: 940MB
10.1.1: 1630MB
10.0.7: 230MB

However, the memory consumption is still much higher than it used to be in my case.

**Comment by shuding** [comment] 2021-03-31 13:25
Hi @gustavpursche thanks for sharing the numbers! I'm curious that if 940MB is the **stable** memory usage after image optimization, or is it the memory usage without image optimization? 

This is important for us to debug because most of the memory should be freed in a while (5s~15s) after image optimization, according to my test in #23565.

**Comment by shuding** [comment] 2021-03-31 14:57
@gustavpursche thank you very much, these 2 charts are helpful! These basically match my test results that the memory leak in next/image is gone.

The initial memory usage being higher could be something else such as the new worker library that we introduced, I'll keep looking into it.

**Comment by karlhorky** [comment] 2021-04-01 07:46
Great, thanks for your continued effort on this @shuding ! Really cool to see the fast response and the amount of care that Vercel puts into things.

**Comment by mjenzen** [comment] 2021-04-01 14:20
@shuding 

Here is a comparison of my memory usage.  Its not a direct apples-to-apples comparison as the blue line has probably cached most of the optimized images, but on the orange line, I was hammering on the image processor generating e-commerce images after a fresh build.  But if anything that indicates an even better result for the new version.

![image](https://user-images.githubusercontent.com/7539434/113307123-cc1a5f80-92d2-11eb-8c8f-e3433b0b157a.png)

blue line - 10.0.7
salmon-y orange line - 10.1.3-canary.0

The only downside with the new build, is that the initial image optimization is noticeably slower than the previous version and can take seconds to populate images on the page.  It seems to be exacerbated by loading more images in quick succession as well.

**Comment by kmdev1** [comment] 2021-04-01 16:00
Hey @shuding,

Great piece of work there 😄 - The canary release does indeed fix the overload of memory and it now seems to stay similar to that of 10.0.7 with no real noticeable difference between the two for myself 😄

**Comment by henryStelle** [comment] 2021-04-01 21:12
Great work @shuding. I am also seeing the memory being deallocated after the images are optimized with the same amount of memory being used during the optimization process, compared to 10.0.7. However, as @mjenzen reported, the rate of the initial image optimization has decreased significantly.

**Closed** 2021-04-02 10:26 UTC
Labels: kind: bug

**Comment by karlhorky** [comment] 2021-04-02 13:05
> The initial memory usage being higher could be something else such as the new worker library that we introduced, I'll keep looking into it.

> However, as @mjenzen reported, the rate of the initial image optimization has decreased significantly.

@shuding Now that this is closed, where can we follow along about these two issues?

1. Higher peak memory usage at start
2. Up to 25x slower

**Comment by mjenzen** [comment] 2021-04-02 13:20
I created issue #23637  to report the slowdown

**Comment by balazsorban44** [comment] 2022-01-28 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
