### ISSUE TITLE
Docs: https://nextjs.org/ consumes too much GPU

### ISSUE THREAD

**Issue by twbbbb** [vercel/next.js#41847] opened 2022-10-26 11:11 UTC
### What is the improvement or update you wish to see?

https://nextjs.org/docs is a static page but it keeps cosuming 30% GPU

### Is there any context that might help us understand?

I've tried Ubuntu intel i5-6200U laptop, Windows 10 i7-870, GT430 desktop
firefox, chrome, edge, disable javascript, guest mode(no extensions)

only disabling CSS removes the problem (copied from stackoverflow)
document.head.parentNode.removeChild(document.head);

**Comment by codart1** [comment] 2022-10-26 12:48
Same here
![image](https://user-images.githubusercontent.com/1023519/198029846-54c2f2e0-b97b-4690-ae80-294dfa129bda.png)

**Comment by QQCif** [comment] 2022-11-03 07:20
I guess it's the animation of Next.js Conf button causing high GPU usage. After removing that button, GPU usage drops down to normal.

**Comment by balazsorban44** [comment] 2023-02-28 12:27
Given Next.js Conf is over, and the fact that I could not reproduce, I'll close this issue for now. Let us know if you still think there is a problem in a new issue. :+1:

**Closed by balazsorban44** 2023-02-28 12:27 UTC
Labels: template: documentation
