### ISSUE TITLE
Yarn Setup Warnings

### ISSUE THREAD

**Issue by jibberishclient** [vercel/next.js#16991] opened 2020-09-10 14:07 UTC
Using `yarn create next-app <app_name>` to generate my project and it's dependencies. However, I'm getting a bunch of warnings about outdated packages and whatnot. Is there a fix on the way for this?

```
warning next > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning next > mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning next > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning next > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning next > resolve-url-loader > rework > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning next > chokidar > braces > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning next > chokidar > braces > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
```

**Comment by Timer** [comment] 2020-09-10 14:12
Unfortunately there's no way to fix these warnings. We're aware of them and are working to have them fixed in the future, but it requires breaking changes so it will not be until Next.js 10 or 11.

**Closed by Timer** 2020-09-10 14:12 UTC

**Comment by balazsorban44** [comment] 2022-01-29 13:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
