### ISSUE TITLE
problem with Router.push using hash

### ISSUE THREAD

**Issue by fabinppk** [vercel/next.js#16410] opened 2020-08-20 19:19 UTC
# Bug report

## Describe the bug

In my case when i change only hash url using `Router.push(localhost:3000/#change)` coming from `localhost:3000` all stylesheets reload again causing the screen blink and a error in browser console.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Checkout https://github.com/fabinppk/hash-problem
2. All instructions on readme file.

## Screenshots

![image](https://user-images.githubusercontent.com/15840422/90815040-70c9cd00-e300-11ea-94c5-ed3aa96a2017.png)

## System information

- OS: Ubuntu 20.04
- Version of Next.js: 9.5.3-canary.6 or higher
- Version of Node.js: v12.13.1

**Comment by Timer** [comment] 2020-08-24 16:01
This appears fixed on the latest canary Next.js version!

**Comment by fabinppk** [comment] 2020-08-25 12:15
@Timer The problem still persist. The repository inside description still show the console error in `9.5.3-canary.22`.

**Comment by Timer** [comment] 2020-08-25 15:34
Will look again.

**Comment by Timer** [comment] 2020-08-25 15:39
Just re-confirmed it does not reproduce. Please see https://hash-problem.vercel.app/.

Please provide a demo and video if you can get it to reproduce for you!

**Comment by fabinppk** [comment] 2020-08-25 16:45
I made some tests using `https://hash-problem.vercel.app/` and chrome browser, and the problem in console and the screen blink still persist.
Ps: In Mozilla Firefox doesnt happens.

Please, see the [video here](https://drive.google.com/drive/folders/1AOTDE08TXzKIP_KV4GDxVhnBegcEib3X?usp=sharing).

If you need more details, just ask me for it.

**Comment by Timer** [comment] 2020-08-25 16:49
Wow, I can't reproduce that at all. Since you can reproduce do you think you could try to send a PR fixing the unhandled promise rejection?

**Comment by fabinppk** [comment] 2020-08-25 16:51
Sure, but i don't know what the solution is. what do I do?

**Comment by kylemh** [comment] 2020-08-25 23:32
I tried this myself, and only got issues if I went to Chrome's device mode (as a fake iPhone) and IMMEDIATELY spammed the button; however, I only get the error/flash once.

**Comment by Timer** [comment] 2020-08-27 03:13
Can y'all test the latest Next.js canary and see if the flash of styles is fixed for you?

**Comment by fabinppk** [comment] 2020-08-27 12:24
@Timer  Fixed!! :clap: 
I've test using `https://hash-problem.vercel.app/`, the repository in description and in my personal private repository.

Thank you for all your support about this.

**Comment by Timer** [comment] 2020-08-27 19:52
Gonna close this out then!

**Closed by Timer** 2020-08-27 19:52 UTC
Labels: kind: bug, point: 3, priority: p0

**Comment by balazsorban44** [comment] 2022-01-29 15:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
