### ISSUE TITLE
Windows folder path with ampersand is causing problems

### ISSUE THREAD

**Issue by LMS007** [vercel/next.js#26906] opened 2021-07-03 21:30 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

12.19

### What browser are you using?

NA

### What operating system are you using?

Windows 10

### How are you deploying your application?

NA

### Describe the Bug

I tried the nextjs demo from here. https://nextjs.org/learn/basics/create-nextjs-app/setup

It installed just fine, but when I tried to build the project, it failed.

C:\Users\kkeat\Documents\Code & Projects\nextjs-blog

```
$ npm run build

> nextjs-blog@0.1.0 build C:\Users\kkeat\Documents\Code & Projects\nextjs-blog
> next build

'Projects\nextjs-blog\node_modules\.bin\' is not recognized as an internal or external command,
operable program or batch file.
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'C:\Users\kkeat\Documents\next\dist\bin\next'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
...
```

I tracked this down to using the ampersand in the folder path, which is perfectly valid in Windows. I think this may be a bug.

### Expected Behavior

`npm run build` does not error when used with a folder location that has an & in one of the parent folders.

### To Reproduce

Place a nextjs project or demo inside a parent folder with "&" as part of its name.
Run any next script
e.g.

`npm run build`

```
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },```

**Comment by Zazzik1** [comment] 2022-01-08 23:26
This problem is not related to Next.js, but to **npm**. I described it in more detail above.

**Comment by balazsorban44** [comment] 2022-01-11 12:11
Closing as @Zazzik1 seems to be right, and the problem is reproducible even without Next.js

**Closed by balazsorban44** 2022-01-11 12:11 UTC
Labels: template: bug
