### ISSUE TITLE
Getting a big useless `Object` as error message and I can not find where it is coming from

### ISSUE THREAD

**Issue by danielo515** [vercel/next.js#42937] opened 2022-11-15 10:32 UTC
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.18.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

not relevant

### How are you deploying your application? (if relevant)

not relevant

### Describe the Bug

Because I can not customise what happens when a server side error is triggered in development, I can not describe the bug in detail.
If you see my screenshot, you will see that all that I get in the debug console is a useless `Object object` stringification of some kind of error.

![image](https://user-images.githubusercontent.com/2270425/201896720-44e372b8-7a41-4dfe-9ef3-f89b8c0dfe33.png)

### Expected Behavior

I want to be able to properly debug what is happening, either by providing my own function to log the errors, or to be able to put debug points in the function handling this errors. However, this information is currently hard to grasp, and I can not find the right place where this is happening, because, as you can see also on my screenshot, the reported trace is on typescript files, which are obviously not available for debugging.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

I don't know what is causing it, so I can not reproduce

### To Reproduce

I have no idea how to reproduce it, and that is the problem. I don't know where the error is coming from to begin with, and it just happens randomly. I don't know if it is a problem in node internals, next-js code or even my own code, because I have no way to see what the hell is actually being triggered.

**Comment by balazsorban44** [comment] 2022-11-15 15:12
Please link to your code/create a minimal reproduction, so we can help investigate the issue. It looks like you are also on an old version (`12.1.0`) of Next.js, so the first step would be to upgrade to `next@canary` and see if the issue still reproduces (although based on the information provided, it's unlikely that this is a Next.js issue). Thanks!

**Comment by danielo515** [comment] 2022-11-15 18:04
Hello @balazsorban44, it is indeed not a Next.js issue.
Maybe it is worth opening it as a feature request. The problem is that this was some unhandled rejection somewhere in my code-base, but it was being impossible for me to figure out where or why, because errors were being serialized by next.js
The inability to debug the next.js internals only added more gasoline to the fire. I had to go into the npm_modules folder and delete the references to the source-maps of the files you don't ship as part of your npm module in order to be able to just put breakpoints

I don't think it is uncommon on JS projects to get errors that you don't know where are coming, given the weak nature of the language in terms of typing, and next.js shadowing the actual stack traces is not helping anyone.

I can not try to reproduce it with next canary because that will require React 18, and I can't get the time to upgrade the entire codebase just to find where a error is coming from.

Please consider adding better debugging primitives.

**Comment by balazsorban44** [comment] 2022-11-15 18:30
Closing as

> it is indeed not a Next.js issue.

To help with debugging, please refer to our documentation: https://nextjs.org/docs/advanced-features/debugging

**Closed by balazsorban44** 2022-11-15 18:30 UTC
Labels: please add a complete reproduction, template: bug

**Comment by danielo515** [comment] 2022-11-15 21:18
I already read the debugging documentation already and they do not address
the issues I mentioned. This is not the first time this problem is raised,
so please consider taking it into account
