### ISSUE TITLE
Capture group in redirect source causes Uncaught SyntaxError

### ISSUE THREAD

**Issue by vallode** [vercel/next.js#23741] opened 2021-04-06 13:13 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Firefox 78.9.0 ESR

### What operating system are you using?

Debian 10

### How are you deploying your application?

next start

### Describe the Bug

When adding a redirect with a source that has a wildcard capture group the app will build and error with an Uncaught SyntaxError once you visit the site. The aim here was to create a wildcard redirect for **all but one specific** endpoint. I used the wildcard example seen at this comment https://github.com/vercel/next.js/issues/15712#issuecomment-666676618

### Expected Behavior

The app should build without errors.

### To Reproduce

Add a new redirect to your `next.config.js` as follows:
```
{
  source: '/:path((?!incompatible).*)',
  destination: '/incompatible',
  permanent: false,
},
```

Either use `next run` or `next start` to observe the resulting SyntaxError.

**Comment by LordTep** [comment] 2021-04-06 17:21
Bump. The regex also does not work if you start with a ^ character for start of string...

**Comment by ysyzqq** [comment] 2021-04-14 03:29
Same problem

**Comment by ijjk** [comment] 2021-04-14 14:52
The above redirect is causing all `_next/static` resources to be redirected as well so the needed JavaScript chunks are not able to load, you need to also exclude the `_next` path on the above redirect to prevent this e.g. `source: "/:path((?!incompatible|_next).*)"`. 

Closing as this doesn't appear to be a bug in Next.js and the redirect is working as expected.

**Closed by ijjk** 2021-04-14 14:52 UTC
Labels: template: bug

**Comment by vallode** [comment] 2021-04-14 15:51
> The above redirect is causing all `_next/static` resources to be redirected as well so the needed JavaScript chunks are not able to load, you need to also exclude the `_next` path on the above redirect to prevent this e.g. `source: "/:path((?!incompatible|_next).*)"`.
> 
> Closing as this doesn't appear to be a bug in Next.js and the redirect is working as expected.

Thanks this makes total sense, I thought I must have been missing something. Appreciate the solution suggested too.

**Comment by hazzo** [comment] 2021-04-26 19:23
> The above redirect is causing all `_next/static` resources to be redirected as well so the needed JavaScript chunks are not able to load, you need to also exclude the `_next` path on the above redirect to prevent this e.g. `source: "/:path((?!incompatible|_next).*)"`.
> 
> Closing as this doesn't appear to be a bug in Next.js and the redirect is working as expected.

This helps showing the page and styles but static assets like images and fonts don't get loaded

**Comment by hazzo** [comment] 2021-04-26 19:42
Not a regex expert and maybe it can be simplified but this actually works: `/:path(^(?!\/?_next)(?!\/? incompatible).+$)`. It contemplates subpaths and for that reasons /assets and /images are loading.

**Comment by hazzo** [comment] 2021-04-27 08:04
Adding the `assets` path solved my previous comment: `"/:path((?!incompatible|_next|assets).*)"`

**Comment by balazsorban44** [comment] 2022-01-28 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
