### ISSUE TITLE
/analytics route doesn't render

### ISSUE THREAD

**Issue by samstr** [vercel/next.js#13676] opened 2020-06-02 15:38 UTC
# Disregard: See https://github.com/vercel/next.js/issues/13676#issuecomment-637635519

## Describe the bug

For some reason if you use the route `/analytics` the page will always be blank.

## To Reproduce

* Clone https://github.com/samstr/next-analytics-route
* Visit /blah in a brower. Loads.
* Visit /analytics in a browser. Blank page.

## System information

- macOS 10.15.5. Chrome latest. 
- 83.0.4103.61
-
```  "dependencies": {
    "next": "9.4.4",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  }
```

- Version of Node.js: v12.14.1

**Comment by samstr** [comment] 2020-06-02 15:42
<img width="544" alt="Screen Shot 2020-06-02 at 16 40 42" src="https://user-images.githubusercontent.com/428626/83540166-d8396300-a4ef-11ea-831e-06f3a0cafe81.png">

Oh. Turns out it's the uBlock Origin 1.27.10 Chrome extension blocking the URL.

Feel free to close. This confused me for a moment though.

**Comment by balazsorban44** [comment] 2020-06-02 16:01
Could you close it yourself if it is answered? :) I believe it is less noise to deal with a self-answered /closed issue than one that looks open and needs answering.

**Closed** 2020-06-02 16:34 UTC

**Comment by balazsorban44** [comment] 2022-01-30 02:14
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
