### ISSUE TITLE
Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules

### ISSUE THREAD

**Issue by kuongknight** [vercel/next.js#17930] opened 2020-10-16 05:11 UTC
# Bug report

## Describe the bug

DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules

## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:

1. Setting assetPrefix to subdomain
2. Use withSass default config, import scss file in a page
3. Handle error componentDidCatch in _app.js
4. Run production mode

## Expected behavior

App render success without catch

## System information

- OS: Windows
- Browser Chrome
- Version of Next.js: 9.5.5
- Version of Node.js: 11.15.0

**Comment by timneutkens** [comment] 2020-10-16 09:33
Please a complete repository. Would also recommend using built-in Sass support.

**Comment by jeremy-coleman** [comment] 2020-10-17 11:19
I think the problem is probably some jss lib trying to access a style element to inject styles into, but there isnt one on the doc yet, doubt it has anything to do with sass

**Comment by kuongknight** [comment] 2020-10-19 02:06
https://github.com/vercel/next.js/blob/9a5a1525bc6b9b1aab4325bc1e15c156941a28bf/packages/next/client/page-loader.ts#L30
It come from core of nextjs @jeremy-coleman

**Comment by jeremy-coleman** [comment] 2020-10-19 11:30
ah nice find. ```js

**Comment by kuongknight** [comment] 2020-10-20 03:58
I think we need to check assetPrefix, if it isn't passed cors security rules, then we disable attribute `data-n-p`
Which use to identity cache by XHR request
https://github.com/vercel/next.js/blob/b2d1d87e7feed5535a05ec99d7558934dcbc82a5/packages/next/pages/_document.tsx#L207

**Comment by jeremy-coleman** [comment] 2020-10-20 14:22
ooh, smart man. I'm curious what the cssRules property value is for that case (undefined I guess?). Also curious about the cases where the link uri points to an empty file or points to an invalid url.

**Comment by bmathews** [comment] 2020-10-26 16:12
Duplicate of https://github.com/vercel/next.js/issues/17029

**Closed** 2020-11-03 12:50 UTC
Labels: kind: bug, point: 3, priority: p1

**Comment by balazsorban44** [comment] 2022-01-29 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
