### ISSUE TITLE
Compilation fails with a js file containing both client-side sync and server-side async functions

### ISSUE THREAD

**Issue by meglio** [vercel/next.js#23028] opened 2021-03-13 05:02 UTC
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

v15.11.0

### What browser are you using?

Firefox Later

### What operating system are you using?

MacOS

### How are you deploying your application?

This is happening in the dev mode. Deploying process is not applicable to this bug report.

### Describe the Bug

Next fails to compile when there is a js file containing both client-side sync and server-side async functions, even though the server-side async function is only used server-side (in my case, it is called from within `getServerSideProps()`).

My research lead me to the following thread:
https://stackoverflow.com/a/64051156/335304:

Citing:

> Webpack is trying to bundle things for the client that can only be used in the server. The solution was to add the externals property to my webpack.config.js file and include all the modules that cannot be resolved by Webpack. See https://github.com/webpack/webpack/issues/744#issuecomment-320437402.

### Expected Behavior

I expect compilation to succeed because I am not using the async function client-side; I am only using it server-side.

### To Reproduce

The reproduction steps are based on my case, but are simplified.

1. Install `pg` module.

2. Create a js file with A) a sync (not async) function used client-side only; and B) an async function reading from a postgresql database with using `pg`.

3. Create a new page for Next and call the async function B from `getServerSideProps()`.

4. `pnpm run dev`

The output in console:

```
error - ./node_modules/.pnpm/pg@8.5.1/node_modules/pg/lib/connection-parameters.js:3:0
Module not found: Can't resolve 'dns'
null
```

Note I'm using `pnpm` if it makes for any difference.

**Comment by meglio** [comment] 2021-06-02 08:55
This has been happening time to time with a similar error message mentioning 'dns' or 'fs'.

I found a detailed explanation of what is going on here: https://maikelveen.com/blog/how-to-solve-module-not-found-cant-resolve-fs-in-nextjs

Turns out the issue is the following: as soon as there is an unused import function, Next.js / Webpack tree-shaking fails to remove the function from the module. As a result, `dns`, `fs` and other server-side-only packages made their way to js bundles that are loaded to the user browser.

I can confirm that every time this error happens, I have to search for unused imports, remove them, and the error goes away.

Does this explanation make sense to you?

**Comment by meglio** [comment] 2021-06-03 01:30
This has been happening time to time with a similar error message mentioning 'dns' or 'fs'.

I found a detailed explanation of what is going on here: https://maikelveen.com/blog/how-to-solve-module-not-found-cant-resolve-fs-in-nextjs

Turns out the issue is the following: as soon as there is an unused import function, Next.js / Webpack tree-shaking fails to remove the function from the module. As a result, `dns`, `fs` and other server-side-only packages made their way to js bundles that are loaded to the user browser.

I can confirm that every time this error happens, I have to search for unused imports, remove them, and the error goes away.

Does this explanation make sense to you?

**Comment by ijjk** [comment] 2021-09-23 04:14
Hi, this sounds like the expected behavior for code elimination with `getServerSideProps`/`getStaticProps` as we can only be sure the imports are specific to those methods if they are used inside of the methods. 

We have a tool to help debugging this here https://next-code-elimination.vercel.app/ which may help seeing this better. 

I'm gonna close this since it doesn't sound like a bug is the expected behavior currently.

**Closed by ijjk** 2021-09-23 04:14 UTC
Labels: please add a complete reproduction

**Comment by meglio** [comment] 2021-11-10 01:06
Thanks @ijjk.

>  this sounds like the expected behavior for code elimination with getServerSideProps/getStaticProps as we can only be sure the imports are specific to those methods if they are used inside of the methods.

I got a bit confused about this, could you please explain how it works? If a function is imported but never used in a file, why it is not an option for your to code-eliminate it entirely? Basically that's what is causing the error - an unused import.

If it is not an option to eliminate an unused import, then I'm failing to understand what problem exactly your existing code elimination logic solves? Please elaborate. -- many thanks

**Comment by balazsorban44** [comment] 2022-01-27 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
