### ISSUE TITLE
Custom 404 error page not rendering

### ISSUE THREAD

**Issue by mithleshjs** [vercel/next.js#20257] opened 2020-12-17 10:10 UTC
# Bug report

## Describe the bug

Custom 404 error page is not being rendered when calling it manually.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a page.
2. Add this line -  return (<Error statusCode={404} />)

## Expected behavior

It should render the custom 404 but it is showing the default 404 page when it is called manually otherwise I am seeing my custom 404 page.

## System information

- OS:  macOS Big Sur
- Version of Next.js: v10.0.3

**Comment by timneutkens** [comment] 2020-12-17 10:21
Closing as this issue is not actionable.

**Closed by timneutkens** 2020-12-17 10:21 UTC
Labels: template: bug

**Comment by mithleshjs** [comment] 2020-12-17 10:50
Sorry, I there was a typo mistake. Here the code -
` if(error) return <Error statusCode={404}/>;`

**Comment by mithleshjs** [comment] 2020-12-17 10:52
@timneutkens Sorry, the code got removed somehow. Here the code -
` if(error) return <Error statusCode={404}/>;`

**Comment by timneutkens** [comment] 2020-12-17 11:35
`next/error` is the built-in error component, not one living in your application.

**Comment by mithleshjs** [comment] 2020-12-17 12:06
Then how do I call the custom one?

**Comment by peterchibunna** [comment] 2020-12-27 16:07
@mithleshjs just create a file `pages/404.js` and in it, have your Custom 404 error page.

**Comment by balazsorban44** [comment] 2022-01-29 00:11
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
