### ISSUE TITLE
[NEXT-877] Link not working when deployed to Vercel

### ISSUE THREAD

**Issue by dotellie** [vercel/next.js#47297] opened 2023-03-19 13:19 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.6.0
      npm: 9.4.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.8
      eslint-config-next: 13.2.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-q4mphh?file=app/page.tsx

### To Reproduce

1. Press the "Go to blog" link
2. Press the "Go to post" link

### Describe the Bug

Pressing on the "Go to post" link after pressing on the "Go to blog" link will never perform a navigation even though the data is seemingly fetched fine from the server when looking at dev tools.

This seemingly only happens for me in the reproduction and when deploying on Vercel. It does not however happen locally on my machine on my own project using "next dev".

Also worth noting, this is a regression and has worked before. I believe is started occurring somewhere around 13.2.x

### Expected Behavior

The navigation should occur.

### How are you deploying your application? (if relevant)

Vercel

<sub>[NEXT-877](https://linear.app/vercel/issue/NEXT-877/link-not-working-when-deployed-to-vercel)</sub>

**Comment by JesseKoldewijn** [comment] 2023-03-20 10:29
It kind of seems like a local problem on your end. when I go to your stackblitz the links work just fine.

**Comment by JesseKoldewijn** [comment] 2023-03-20 10:45
Will do, although if it doesnt work on stackblitz for you either I dont really expect deploying a fork onto vercel will net any results tho.

**Comment by dotellie** [comment] 2023-03-20 11:09
Checked the deploy version you sent there, has the issue for me! Tested on Arc on Mac, Safari on iPhone and Edge on a Windows 11 ARM VM.

The symptom I'm getting is essentially as is shown in this screenshot:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/4590037/226322073-f3891576-3aa9-484a-937e-4fdc9f8b6049.png">

It makes a request and gets the data, but the navigation never happens.

I honestly have no idea what it can be at this point considering you don't have it @JesseKoldewijn, but if there are any debugging steps I can help with just say the word!

**Comment by JesseKoldewijn** [comment] 2023-03-20 11:11
If I understand it correctly, you've tried it on 2 apple devices and a windows vm right? Do you have any other devices you could try it on just to rule out its not an apple issue? (since I assume you ran that windows vm on your mac)

**Comment by rortan134** [comment] 2023-03-20 11:19
Issue is also reproducible on my end with the deployed app

![image](https://user-images.githubusercontent.com/37253958/226324183-2b426cc9-8f33-4026-8c48-cfd6a1613e72.png)
Downloaded a-page but didn't navigate

Running windows with chrome v110.0.5

**Comment by JesseKoldewijn** [comment] 2023-03-20 11:23
> I don't know if this is related but i've got something similar happening on https://use-selectify-rortan134.vercel.app. I've tested on multiple devices and browsers and sometimes navigating between the examples doesn't work, after isolating the problem everything points to the link itself. My implementation is a bit more complex though https://github.com/rortan134/use-selectify/blob/master/www/src/components/Button.tsx

In your case I would recommend trying the latest canary build combined with maybe attaching a click handler to your buttons to check if the click gets registered.

**Comment by dotellie** [comment] 2023-03-20 11:23
Just managed to reproduce it on my PC with Windows 10 and Chrome. So I doubt this is an OS or browser issue, but it's certainly weird behavior.

**Comment by JesseKoldewijn** [comment] 2023-03-20 11:25
yeah, for me it now seems like that the dynamic route of /blog/a-post doesnt work but all the other routes work just fine.

**Comment by JesseKoldewijn** [comment] 2023-03-20 13:58
lol, just found out what the issue probably is. Having a dynamic route without having a page in the root of the folder breaks the route behavior apparently. 

Fixed it by adding a page to the /blog directory.

**Comment by JesseKoldewijn** [comment] 2023-03-20 14:06
I'll have a look into it, maybe I can find where it breaks 😄

**Comment by JesseKoldewijn** [comment] 2023-03-20 14:43
Welp... I can't really find where the link component does the page prefetch cuz I would think the part of the flow that is breaking would be close-ish to that logic. Or it would already be failing of the local url check which would sound kinda unlikely to me because this check seems to happen before the page prefetch.

**Comment by JesseKoldewijn** [comment] 2023-03-20 14:44
Hey man @huozhi, out of curiosity. Would you happen to know a fix for this behavior?

**Comment by leandromatos** [comment] 2023-03-21 11:40
I'm using the latest canary version (13.2.5-canary.10), and this error happens all time.

When I try to navigate from one page to another, the fetch happens on the network tab, but the route doesn't change.

**Comment by leandromatos** [comment] 2023-03-21 12:43
> Hey man @huozhi, out of curiosity. Would you happen to know a fix for this behavior?

I tried to reproduce your suggestion of including a `page.ts` in all directories inside the app dir, including dynamic directories, but nothing changed. The error with the link still happens.

**Comment by JesseKoldewijn** [comment] 2023-03-21 12:56
> Sorry but I can't really reproduce the issue at hand. Checked just about the same code as you had in your stackblitz deployed on vercel and it works just fine both on windows 10/11 and linux.
> 
> repo: https://github.com/JesseKoldewijn/next.js-link-test-deployed deployed: https://next-js-link-test-deployed.vercel.app/

@leandromatos if you take a look inside of this repo every page works just fine. But the page apparently is needed in the root of the [someSlug] directory to allow the route to work. Which is not really (probably) what should happen.

**Comment by leandromatos** [comment] 2023-03-21 16:26
> > Sorry but I can't really reproduce the issue at hand. Checked just about the same code as you had in your stackblitz deployed on vercel and it works just fine both on windows 10/11 and linux.
> > repo: https://github.com/JesseKoldewijn/next.js-link-test-deployed deployed: https://next-js-link-test-deployed.vercel.app/
> 
> @leandromatos if you take a look inside of this repo every page works just fine. But the page apparently is needed in the root of the [someSlug] directory to allow the route to work. Which is not really (probably) what should happen.

Unfortunately, in my project, the problem still happens. I'll prepare a repository to share with you.

**Comment by leandromatos** [comment] 2023-03-21 17:27
Here is the project @JesseKoldewijn  https://github.com/leandromatos/next-link-fetch-error.

Try to change the language, and navigate between the home page, about page, or privacy policy page. You'll see the fetch happing on the network tab, but the route doesn't change.

**Comment by JesseKoldewijn** [comment] 2023-03-21 17:39
> Here is the project @JesseKoldewijn  https://github.com/leandromatos/next-link-fetch-error.
> 
> Try to change the language, and navigate between the home page, about page, or privacy policy page. You'll see the fetch happing on the network tab, but the route doesn't change.

That might be a combination of the link component acting up with nested dynamic paths already. I don't see anything weird in your repo tho so I think this might have to get pushed to some of the maintainers/vercel squad.

Btw, what you could try is throw a middleware in your appDir root and log the req and res. Maybe that coupd give ya some more info in your usecase.

**Comment by JesseKoldewijn** [comment] 2023-03-21 17:50
> Even without middleware, the strange behaviour still happens.

Thats not what I suggested, what I mentioned was trying to check what yhe server receives and sends using middleware in the appDir root folder.

**Comment by leandromatos** [comment] 2023-03-21 19:24
Here the guy has the kinda of the same problem https://github.com/vercel/next.js/issues/42991

**Comment by JesseKoldewijn** [comment] 2023-03-21 20:05
Seems like it. @karlhorky just pinning ya due to your chatter in the other issue🤙

**Comment by leandromatos** [comment] 2023-03-22 11:34
I tried the [v13.2.5-canary.12](https://github.com/vercel/next.js/releases/tag/v13.2.5-canary.12) version today, and my problem is gone 🧐.

I'm still insecure about this behaviour. If something wrong happens again, I'll notice it here.

**Closed** 2023-04-05 13:40 UTC
Labels: kind: bug, template: bug, area: Routing, area: app
