### ISSUE TITLE
Invalid next config -- even if it's valid 

### ISSUE THREAD

**Issue by scerelli** [vercel/next.js#39720] opened 2022-08-18 10:56 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.15
      pnpm: 7.6.0
    Relevant packages:
      next: 12.2.3
      eslint-config-next: 12.2.3
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "12.2.3", newest: "12.2.6-canary.1".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### What browser are you using? (if relevant)

Not relevant

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

On `pnpm run dev` i get this error:

```
warn  - Invalid next.config.js options detected: 
[
  {
    "instancePath": "",
    "schemaPath": "#/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "webpackDevMiddleware"
    },
    "message": "must NOT have additional properties"
  },
  {
    "instancePath": "",
    "schemaPath": "#/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "configOrigin"
    },
    "message": "must NOT have additional properties"
  },
  {
    "instancePath": "",
    "schemaPath": "#/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "target"
    },
    "message": "must NOT have additional properties"
  },
  {
    "instancePath": "",
    "schemaPath": "#/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "analyticsId"
    },
    "message": "must NOT have additional properties"
  },
  {
    "instancePath": "",
    "schemaPath": "#/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "webpack5"
    },
    "message": "must NOT have additional properties"
  },
  {
    "instancePath": "/amp/canonicalBase",
    "schemaPath": "#/properties/amp/properties/canonicalBase/minLength",
    "keyword": "minLength",
    "params": {
      "limit": 1
    },
    "message": "must NOT have fewer than 1 characters"
  },
  {
    "instancePath": "/assetPrefix",
    "schemaPath": "#/properties/assetPrefix/minLength",
    "keyword": "minLength",
    "params": {
      "limit": 1
    },
    "message": "must NOT have fewer than 1 characters"
  },
  {
    "instancePath": "/basePath",
    "schemaPath": "#/properties/basePath/minLength",
    "keyword": "minLength",
    "params": {
      "limit": 1
    },
    "message": "must NOT have fewer than 1 characters"
  },
  {
    "instancePath": "/generateEtags",
    "schemaPath": "#/properties/generateEtags/isFunction",
    "keyword": "isFunction",
    "params": {},
    "message": "must pass \"isFunction\" keyword validation"
  }
] 
See more info here: https://nextjs.org/docs/messages/invalid-next-config
```

but this is my next.config

```
/** @type {import('next').NextConfig} */
/* eslint-disable @typescript-eslint/no-var-requires */
const withTranspileModules = require('next-transpile-modules')(['@talent-garden/react-components'])
const withImages = require('next-images')
const withPlugins = require('next-compose-plugins')
const withBundleAnalyzer = require('@next/bundle-analyzer')
const { i18n } = require('./next-i18next.config')

module.exports = withPlugins(
  [
    [withBundleAnalyzer, {
      enabled: process.env.ANALYZE === 'true'
    }],
    [withImages],
    [withTranspileModules],
  ],
  {
    i18n,
    reactStrictMode: true,
    images: {
      domains: [
        'cdn.sanity.io'
      ],
    },
    trailingSlash: true,
    experimental: {
      esmExternals: false
    },
  }
)
```

Everything works fine, but unfortunately i get this warning about invalid config that reports config keys that are not even used.

### Expected Behavior

To not show the warning or if there are problems to show a warning that is meaningful to my setup.

### Link to reproduction

https://github.com/scerelli/invalid-next-config-bug-report

### To Reproduce

1. create a project
2. use this package json
3. use attached next config in the previous step
```
{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@next/bundle-analyzer": "^12.2.3",
    "@radix-ui/react-accordion": "^1.0.0",
    "@tanstack/react-query": "^4.0.10",
    "axios": "^0.27.2",
    "classnames": "^2.3.1",
    "next": "12.2.3",
    "next-auth": "^4.10.3",
    "next-compose-plugins": "^2.2.1",
    "next-i18next": "^11.3.0",
    "next-images": "^1.8.4",
    "next-transpile-modules": "^9.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-markdown": "^8.0.3",
    "react-use": "^17.4.0",
    "rehype-raw": "^6.1.1"
  },
  "devDependencies": {
    "@types/node": "18.6.3",
    "@types/react": "18.0.15",
    "@types/react-dom": "18.0.6",
    "eslint": "8.21.0",
    "eslint-config-next": "12.2.3",
    "typescript": "4.7.4"
  }
}
```

**Comment by ijjk** [comment] 2022-08-18 11:12
closing as duplicate of https://github.com/vercel/next.js/issues/39161

**Closed by ijjk** 2022-08-18 11:12 UTC
Labels: template: bug
