### ISSUE TITLE
Next.js 12 Middlewares trigger too many HEAD requests

### ISSUE THREAD

**Issue by emwp** [vercel/next.js#30901] opened 2021-11-03 16:44 UTC
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

15.5.1

### What browser are you using?

Edge 95.0.1020.30

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

Whenever a [middleware](https://nextjs.org/docs/middleware) runs it triggers lots of HEAD request.
This is specially bad when you have tons of Next links, since for each Next Link in the screen it prefetches the JS bundle for it and does one HEAD request per link.

I ran into an issue with this because of Cloudflare rate-limiting. 

This doesn't seem like optimal behaviour.

![2021-11-03 18 29 43](https://user-images.githubusercontent.com/45342364/140104121-25c71a76-f815-4fa1-a8ea-8311385291fa.gif) 

### Expected Behavior

Not to send these HEADS requets for Next Link prefetch requests, or at least have some way of disabling it.

### To Reproduce

I've put together a minimal reproduction repository. It's the same repo used in the example gif.

https://github.com/emwp/nextjs-head-requests-example
Just clone it, install dependencies and run `yarn prod`.

**Comment by TERADA-DANTE** [comment] 2021-11-04 01:23
You are using middleware globally in `pages/_middleware.ts`.
I recommend create middleware where it is specifically needed(e.g. `pages/XXX/_middleware.ts`).

**Comment by emwp** [comment] 2021-11-04 07:57
> You are using middleware globally in `pages/_middleware.ts`. I recommend create middleware where it is specifically needed(e.g. `pages/XXX/_middleware.ts`).

The intention was to be global.
Thanks for the reply @TERADA-DANTE, but it doesn't really address the issue.

**Comment by klarstrup** [comment] 2021-11-04 22:01
Experiencing this too

**Comment by javivelasco** [comment] 2021-11-16 12:42
This is expected to happen.

With the introduction of Middleware the client can't know without checking with the server where a certain link is resolving to. For example, if you have a global middleware that rewrites `/about` with `about2` when there is a certain cookie (like in an A/B Test), there will be cases where we need to pre-load `about` and others where it should be `about2`, it will depend on the request.

Because the middleware runs in the server we must run a "preflight" request to see what we need to prefetch. There is no other way around this request that doesn't involve running the middleware. To avoid having so many requests on the first load you can disable `prefetch` in the `Link` component but it will still trigger on hover and of course block navigation.

I don't see a way to _prevent_ those requests if you require to have a global middleware while keeping client navigation. The max we can delay this request is to the moment where the navigation happens but that could add latency on navigation which would feel sloppy.

**Closed by javivelasco** 2021-11-16 12:42 UTC
Labels: template: bug, area: Middleware

**Comment by maapteh** [comment] 2021-12-13 12:27
@javivelasco Maybe worthwile to mention in the Docs?

**Comment by balazsorban44** [comment] 2022-01-27 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
