### ISSUE TITLE
[Next 9.5] `process` (and `.env`) not available when using Webpack 5.0 beta

### ISSUE THREAD

**Issue by Danetag** [vercel/next.js#15646] opened 2020-07-29 20:13 UTC
# Bug report

## Describe the bug

I'm trying to migrate a project from next 9.4 to next 9.5, using webpack `^5.0.0-beta.22`. The project is also a Vercel project.
When compiling, the browser doesn't seem to be able to access the `process`, therefore it can't access the `.env` variables.

## To Reproduce

`next.config.js`

```.js
// eslint-disable-next-line @typescript-eslint/no-var-requires
const path = require('path');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
});

module.exports = withBundleAnalyzer({
  env: {
    // some env
    AN_API_KEY: process.env.AN_API_KEY,
  },
  webpack: (config, { webpack }) => {
    config.module.rules.push({
      issuer: /\.(js|ts)x?$/,
      test: /\.svg$/,
      use: ['raw-loader'],
    });
    
    // Attempt to make `process` available on the client side
    // config.plugins.push(
    //   new webpack.ProvidePlugin({
    //     process: 'process/browser',
    //   }),
    // );

    // Alias
    config.resolve.alias['~'] = path.resolve(__dirname + '/src');
    
    // Also had to add this for `react-remarks` to work on client-side
    config.resolve.alias['path'] = 'path-browserify';

    return config;
  },
});
```

## Expected behavior

`process` and `process.env` should be available on client-side (or compiled to provide the correct values)

## System information

- OS: macOS
- Version of Next.js: 9.5
- Version of Node.js: 12.16.1

Hope that helps!

**Comment by Timer** [comment] 2020-07-29 22:47
This is fixed on `next@canary`.

**Closed by Timer** 2020-07-29 22:47 UTC

**Comment by balazsorban44** [comment] 2022-01-29 20:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
