### ISSUE TITLE
Edge <=17 broken: syntax problem in main.js chunk (in initHeadManager())

### ISSUE THREAD

**Issue by fabb** [vercel/next.js#17911] opened 2020-10-15 10:35 UTC
# Bug report

## Describe the bug

Loading a next.js page in Edge 17 fails on hydration in `initHeadManager` with a syntax error:

![Screenshot 2020-10-15 at 12 23 58](https://user-images.githubusercontent.com/153960/96111739-e5288300-0ee1-11eb-8371-203401061b37.png)

![Screenshot 2020-10-15 at 12 24 12](https://user-images.githubusercontent.com/153960/96111747-e78add00-0ee1-11eb-82f4-4d26adb037f0.png)

![Screenshot 2020-10-15 at 12 24 41](https://user-images.githubusercontent.com/153960/96111751-e9ed3700-0ee1-11eb-80ca-4c5623945a27.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. In Edge 17, go to https://www.willhaben.at/iad/immobilien/ and check the browser console
2. See error

## Expected behavior

The compiled main chunk should be loadable in Edge 17.

## System information

- OS: Windows 10
- Browser: Edge 17 and below
- Version of Next.js: 9.5.4
- Version of Node.js: 12.18.4

## Additional context

Curiously it works correctly in IE11.

It looks like Edge does not like this code:
```
var e=document.getElementsByTagName("head")[0],n=new Set(e.children);
```
![Screenshot 2020-10-15 at 12 34 53](https://user-images.githubusercontent.com/153960/96112403-d7bfc880-0ee2-11eb-94ca-fefb461f740b.png)

It seems that `document.getElementsByTagName("head")[0]` returns the `<head>` element correctly, but `e.children` returns a `<HtmlCollection>` which cannot be used as argument to create a new `Set`.

Is a proper `Set` polyfill missing for Edge <= 17?

**Comment by timneutkens** [comment] 2020-10-15 14:05
Looks like a duplicate of #17775

**Comment by fabb** [comment] 2020-10-15 15:04
I just tried Edge 17 and 18, and it worked correctly in 18, so I did not check higher versions.

**Comment by skarthikeyan96** [comment] 2020-10-30 10:25
+1 @fabb Problems seems to be in Edge 17

**Comment by styfle** [comment] 2020-11-10 19:05
Closing as a duplicate of #17775

**Closed by styfle** 2020-11-10 19:05 UTC
Labels: kind: bug

**Comment by balazsorban44** [comment] 2022-01-29 05:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
