### ISSUE TITLE
Next 13 + experimental app dir + Tailwind hot-reload of classes doesn't work

### ISSUE THREAD

**Issue by Dannymx** [vercel/next.js#43878] opened 2022-12-09 10:28 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

❯ npx next info

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 2.4.3
      pnpm: N/A
    Relevant packages:
      next: 13.0.7-canary.3
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://github.com/vercel/app-playground

### To Reproduce

- Grab latest version of Next.js with experimental app dir enabled ([I'm using the playground example](https://github.com/vercel/app-playground))
- Load project, go to `/streaming`
- In your editor, go to `Product.tsx` and edit a class with a width class `w-*` (go to line 75)
- Swap `w-1/3` for `w-6/12` save and wait for hot-reload (**don't** manually refresh the page)
- You won't see your new class applied, element will break due to class not being applied
- Go back to editor and try now `w-10/12`, wait for hot-reload. Same result as above.
- Set it now to `w-6/12` and manually reload, you will see your class now (and it seems to be caching this class now)
- If you repeat the steps above `w-6/12` won't fail anymore because it seems to be cached now somehow

### Describe the Bug

Hot reloading of Tailwind CSS when you change classes in your code doesn't work. 
Only works after you apply a new class and manually reload the page.

Bug in action:
![bug](https://user-images.githubusercontent.com/364003/206681426-b3c4363f-94ab-470f-9a39-b83d16d4d08b.gif)

### Expected Behavior

Swapping Tailwind classes from elements should work when hot-reloading.

### Which browser are you using? (if relevant)

Chrome  108.0.5359.98 (Official Build) (x86_64)

### How are you deploying your application? (if relevant)

Locally (npm run dev)

**Comment by ciruz** [comment] 2022-12-09 12:19
I got the same error, it only works with classes already defined somewhere else.

**Comment by ElektrikSpark** [comment] 2022-12-09 14:01
Same error on `13.0.7-canary.1`. Seems to work on `13.0.6`? Correct me if I am wrong.

**Comment by iamjohnlong** [comment] 2022-12-09 16:07
Related issue here https://github.com/vercel/next.js/issues/43396#issuecomment-1342924284

**Comment by ciruz** [comment] 2022-12-09 16:08
> Same error on `13.0.7-canary.1`. Seems to work on `13.0.6`? Correct me if I'm wrong.

I'm on ``13.0.6`` and it doesn't work. I just tried a fresh next.js installation based on the official tailwind guide, with the ``/app`` directory ``https://tailwindcss.com/docs/guides/nextjs#app-directory`` and it's the same problem there (``13.0.6``).

I up- and downgraded between different next.js versions and there is a difference between ``13.0.5`` and ``13.0.4``, hot reload works works well with ``13.0.4``, but is broken with ``13.0.5``.

**Comment by teddybee** [comment] 2022-12-09 20:44
I have an issue as well with 13.0.6, hot reload often "loading" endless, with a small project.
(node:17576) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 client/ listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit

**Comment by teddybee** [comment] 2022-12-09 23:24
My problem looks like was solved. I added this into the tailwind.config:
```
  content: [
    "!./node_modules",
  ],
```

**Comment by PatrikTheDev** [comment] 2022-12-11 10:27
Unfortunately @teddybee's workaround didn't work for me, it may be because I'm in a pnpm monorepo

Still broken on latest canary

**Comment by masasidan** [comment] 2022-12-12 08:52
Facing the same issue. The only workaround I've found is to downgrade your next version to `13.0.4`.

**Comment by surjithctly** [comment] 2022-12-12 08:56
I can confirm the issue. Happens specifically on `app` directory + `v13`

**Comment by huozhi** [comment] 2022-12-15 20:35
We land a fix in 13.0.8-canary.0. Could you upgrade to to see if the hmr is fixed for you?

**Comment by asheikho99** [comment] 2022-12-16 17:21
doesn't seem to work for me when upgrading to `13.0.8-canary.0` but downgraded to `13.0.4` and working just fine.

**Comment by huozhi** [comment] 2022-12-16 17:45
@asheikho99 could you provide a reproduction, will be easier to investigate 🙏 thanks

**Comment by asheikho99** [comment] 2022-12-17 02:34
> @asheikho99 could you provide a reproduction, will be easier to investigate 🙏 thanks
Here is a GIF shows the exact issue. Notice how it's working fine until couple changes then it stops working. 


❯ Using: 
`Firefox 108.0.1 (64-bit)`
`Chrome Version 108.0.5359.125 (Official Build) (64-bit)`
No cache for localhost
❯ npx next info
```Operating System:
    Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.8-canary.0
      eslint-config-next: 13.0.7
      react: 18.2.0
      react-dom: 18.2.0```

**Comment by jstnmthw** [comment] 2022-12-18 04:26
Running under WSL on Windows 10, clean yarn install **doesn't work** for me. New classes are not compiled in when saved.

```
    Operating System:                            
      Platform: linux                            
      Arch: x64                                  
      Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
    Binaries:                                    
      Node: 18.8.0                               
      npm: 9.2.0                                 
      Yarn: 1.22.19                              
      pnpm: N/A                                  
    Relevant packages:                           
      next: 13.0.8-canary.0                      
      eslint-config-next: 13.0.6                 
      react: 18.2.0                              
      react-dom: 18.2.0   
```

**Comment by DerTyp876** [comment] 2022-12-18 15:18
Same problem, but without using Tailwind.

```
Platform: win32
      Arch: x64
      Version: Windows 10 Pro
Binaries:
  Node: 16.16.0
  npm: 8.19.2
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 13.0.8-canary.0
  eslint-config-next: 13.0.7
  react: 18.2.0
  react-dom: 18.2.0
```

**Comment by DerTyp876** [comment] 2022-12-18 19:37
I fixed the problem for me by adding a proper HTML structure to my RootLayout, like this:

Before (app/layout.tsx):
```tsx
import "../styles/globals.scss";
import Nav from "./Nav";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Nav />
      <main>{children}</main>
    </>
  );
}
```

After(app/layout.tsx):
```tsx
import "../styles/globals.scss";
import Nav from "./Nav";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
	<head></head>
	<body>
	  <header>
		  <Nav />
	  </header>
	  <main>{children}</main>
	</body>
    </html>
  );
}
```

**Comment by denizyoldas** [comment] 2022-12-19 16:20
Not fixed in 13.0.7

**Comment by huozhi** [comment] 2022-12-19 16:24
@asheikho99 I tried your reproduction on a windows VM it works for me. I feel it's another issue with windows specific based on the reports after reopening. I'd like to close this for now since it's fixed for the original issue. We can track the windows one in the new issue.

**Closed by huozhi** 2022-12-19 16:24 UTC
Labels: kind: bug, area: Server Components, area: app

**Comment by phuson** [comment] 2022-12-19 16:38
For the record, this is mostly fixed for me (I haven't thoroughly tested it yet) in canary version `13.0.8-canary.0`. But I'm using it on a Mac M1.

**Comment by jstnmthw** [comment] 2022-12-20 02:51
> @asheikho99 I tried your reproduction on a windows VM it works for me. I feel it's another issue with windows specific based on the reports after reopening. I'd like to close this for now since it's fixed for the original issue. We can track the windows one in the new issue.

@huozhi, I used Linux under WSL and it doesn't work for me. So not just only Windows specific? Can you at least link the new issue so others can follow the core issue of it not refreshing?

**Comment by Melvynx** [comment] 2022-12-21 08:35
I follow all the thread and it didn't work for me.

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.9.0
      npm: 8.19.1
      Yarn: N/A
      pnpm: 7.18.2
    Relevant packages:
      next: 13.0.8-canary.0
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0
```

I switch to 13.0.8-canary.0 but hot-reloading tailwind style doesn't work.

I follow all this issues and add 
```
content: [
    //...
    '!./node_modules',
  ],
```

But this change nothing.

I hope it's me ! Thanks you for your answer.

**Comment by mxswat** [comment] 2022-12-22 12:53
Also, on next `13.0.8-canary.4` tailwind does not work at all, and no CSS is loaded. I will try `13.0.8-canary.0` and update this comment if I get something close to working

**Comment by Rikimbili** [comment] 2022-12-23 17:53
On version 13.1.0 TailwindCSS appears to still be broken when using with the app directory. The last working version for me is 13.0.6

**Comment by jupelost** [comment] 2022-12-23 20:41
same here I get a hydration error

**Comment by robert-yates** [comment] 2022-12-23 22:01
> 

I can also confirm 13.1 not working but rolling back the version fixes it

**Comment by babaei-mostafa** [comment] 2022-12-24 05:25
Same here. On version 13.1.0 Tailwindcss not working on app directory. I tried every single solution and still not working.

**Comment by ondrej-langr** [comment] 2022-12-24 08:24
Same here - version 13.0.2 still works. 13.0.7 did not aswell as 13.1

**Comment by nghiepdev** [comment] 2022-12-25 02:53
Same here in Next v13.1.1

**Comment by babaei-mostafa** [comment] 2022-12-27 11:02
> Same here - version 13.0.6 still works. Version 13.0.7 is where it breaks and 13.1 does not fix it. Seems like turbopack and swc_core was updated for that 13.0.7 version. That may be the reason

Thank you for this information. I downgraded to version 13.0.6 and the problem got solved

**Comment by AndresdoSantos** [comment] 2023-01-01 02:40
I don't remember who said it anymore, but it worked after I put it on version `13.0.6`

**Comment by caickdias** [comment] 2023-01-03 20:26
It didn't work for me either on version 13.1.
I tried downgrading to 13.0.6, no success.
Then I tried 13.0.4 and it worked.

**Comment by Kmachappy** [comment] 2023-01-03 20:50
I'm on fedora linux

13.1.1 not wroking for me .

**Comment by elhe26** [comment] 2023-01-04 01:52
> Windows 10, didn't work for me either on version 13.1.1.

Same issue.

**Comment by andresev** [comment] 2023-01-04 18:08
Downgraded from version 13.1.1 to 13.0.4 and it works now.

**Comment by AminAddow** [comment] 2023-01-05 00:55
Same issue for me on v13.1.

**Comment by Kmachappy** [comment] 2023-01-05 00:59
Since this issue is closed what happening to the feedback here?

**Comment by PatrikTheDev** [comment] 2023-01-05 07:33
I don't understand either, it's clearly still not fixed in the recent versions based on user feedback. Doesn't work past 13.0.4 for me

**Comment by Rikimbili** [comment] 2023-01-05 07:38
For me it is working on 13.1.1. Make sure you are using the exact version `"next": "13.1.1"` instead of `"next": "^13.1.1"`.

**Comment by Kmachappy** [comment] 2023-01-05 07:47
> For me it is working on 13.1.1. Make sure you are using the exact version `"next": "13.1.1"` instead of `"next": "^13.1.1"`.

Still not working probably my environment then.

**Comment by ekil1100** [comment] 2023-01-05 15:04
It is still not working on `13.1.1`.
```
experimental: {
	appDir: true,
}
```
Also, I found out, enable `appDir` does affect TailwindCSS hot reload in pages folder.

**Comment by reginpv** [comment] 2023-01-06 17:12
Still same issue for me V13.1.1

Putting in `"!./node_modules",` inside tailwind config content looks like fixed it for me:

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "!./node_modules",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

**Comment by andresev** [comment] 2023-01-06 18:11
@reginpv this worked!  I did a brand new build of next.js 13 with app directory using 
`yarn create next-app --experimental-app`

After that, I installed Tailwindcss: 
```
yarn add -D tailwindcss postcss autoprefixer
npx tailwindcss init -p
```

Added the Tailwind directives to globals.css:
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

And lastly, modified the tailwind.config.js file: 
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    '!./node_modules',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
```


I previously had done this but it didn't work when I did everything manually and started with just `yarn add next-app`. Weirdly, it works when I did it this way starting with `yarn add next-app --experimental-app`

**Comment by reginpv** [comment] 2023-01-06 18:17
@andresev exactly how I did it!

**Comment by kengeo** [comment] 2023-01-06 22:17
After trying for a while with all the suggestions, adding the following to your root layout file works:
```
import "../styles/dist.css";
import "tailwindcss/tailwind.css"; <-- add this
```
It works with `13.1.1` as well.

**Comment by psugihara** [comment] 2023-01-07 22:43
I've tried every mentioned solution with no luck.

Downgrading to 13.0.4 seems to work for me. Hopefully this gets fixed soon.

**Comment by leerob** [comment] 2023-01-09 21:18
@PatrikTheDev do you have a reproduction using the latest canary?

**Comment by engageintellect** [comment] 2023-01-10 04:55
same issue. 13.1.1, WSL, Tailwind + DaisyUI

**Comment by kleinesNugget** [comment] 2023-01-10 14:19
Same issue. Classes assigned when executing `npm run dev` work, but once I assign a class that didn't exist on start it just doesn't create them.
I created a project using `npx create-next-app@latest testing --typescript --experimental-app --eslint` (Version 13.1.1)
then changed the dev script in the package.json to `next dev --turbo`
and finally installed tailwindcss following the steps in their tailwindcss nextjs guide (Category "Using the app directory") starting from step 2, as I already created the project.
Now you can assign any container a tailwindcss class (i.e. `bg-red-500`), then run `npm run dev` and it'll work. If you were to change the color to let's say `bg-green-500`, the container won't have any color anymore. The class simply didn't exist on server start and it doesn't get created on hot reload.
I'm on Windows 11, using the latest Firefox and Visual Studio Code.

**Comment by ngoov** [comment] 2023-01-10 21:54
Same issue with nextjs 13.1.1 and canary with windicss. Already posted an issue on their webpack plugin also, because I thought it might be related to that. The repro codesandbox: [CSB](https://codesandbox.io/p/sandbox/next-windicss-3iu9rp?file=%2Fapp%2Fpage.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A4%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A4%7D%5D) 

Just change the bg-red-500 to something like bg-red-800 or bg-blue-500, something that is not used in the app yet and it will not have any style.

**Comment by Dannymx** [comment] 2023-01-10 21:58
I'm the author of this GitHub issue and I can say the issue was fixed for me for my specific settings (I use macOS).

It seems that the people who still have the issue run Windows or WSL, as well as having an incorrect rootLayout.

If you are on those settings mentioned above please create a new detailed issue, as this issue should be marked as closed because the latest canary fixed the problem for me.

**Comment by shaunchurch** [comment] 2023-01-11 13:54
I'm seeing this issue too.

The reproduction is simply:
- Begin a new Next.js 13 project with app directory, using the next-create-app command.
- Install tailwind and configure it.
- Use any tailwind class in dev mode, then change the class to one you haven't used.

I'm on macOS, so it's not just a WSL issue.

The latest canary is broken in another way wqith an SSR rendering error, so not usable at the moment.

**Comment by kleinesNugget** [comment] 2023-01-11 19:48
> Edit: Ok, looks like this is a Firefox issue - it works for me in Chrome and Safari, but not in Firefox or Firefox Dev Edition. Odd.

Just like the author of the issue suggested, I've created a new issue since this issue really seems to just be just on Firefox now.
https://github.com/vercel/next.js/issues/44782

**Comment by aandriamanga** [comment] 2023-01-11 23:02
> After trying for a while with all the suggestions, adding the following to your root layout file works:
> 
> ```
> import "../styles/dist.css";
> import "tailwindcss/tailwind.css"; <-- add this
> ```
> 
> It works with `13.1.1` as well.

It’s work for me. But need to move tailwindcss from dev dependencies to dependencies.

**Comment by psugihara** [comment] 2023-01-11 23:07
> > After trying for a while with all the suggestions, adding the following to your root layout file works:
> > ```
> > import "../styles/dist.css";
> > import "tailwindcss/tailwind.css"; <-- add this
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It works with `13.1.1` as well.
> 
> It’s work for me. But need to move tailwindcss from dev dependencies to dependencies.
> 
> windows 10 + wsl + NextJS 13.1.1

Will that include all unpruned tailwind classes in your production build? If so, that's a lot of extra CSS.

**Comment by aandriamanga** [comment] 2023-01-11 23:22
> > > After trying for a while with all the suggestions, adding the following to your root layout file works:
> > > ```
> > > import "../styles/dist.css";
> > > import "tailwindcss/tailwind.css"; <-- add this
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > It works with `13.1.1` as well.
> > 
> > 
> > It’s work for me. But need to move tailwindcss from dev dependencies to dependencies.
> > windows 10 + wsl + NextJS 13.1.1
> 
> Will that include all unpruned tailwind classes in your production build? If so, that's a lot of extra CSS.

Interesting point.
Finally, it’s not a right solution.

**Comment by cdedreuille** [comment] 2023-01-13 11:43
I'm having the same issue. In my case, I have the `appDir` activated but I'm still using the pages folder. I only have Sanity on the app folder. The weird thing is that it seems that it only refresh if the class name has already been used somewhere else. If that's a new one I have to refresh.

All the code is available here: https://github.com/cdedreuille/portfolio-2022

**Comment by kleinesNugget** [comment] 2023-01-13 16:19
> I'm having the same issue. In my case, I have the `appDir` activated but I'm still using the pages folder. I only have Sanity on the app folder. The weird thing is that it seems that it only refresh if the class name has already been used somewhere else. If that's a new one I have to refresh.
> 
> All the code is available here: https://github.com/cdedreuille/portfolio-2022
> 
> @Dannymx Can you open this issue again? It doesn't seem to be fixed.

Are you using Firefox? If so, I've opened a new issue because it seems to only be affecting Firefox. (https://github.com/vercel/next.js/issues/44782)

**Comment by cdedreuille** [comment] 2023-01-16 08:28
@kleinesNugget I'm using Chrome and Safari. I'm not sure it is a browser problem.

**Comment by kleinesNugget** [comment] 2023-01-16 08:41
Hm, that's odd then. Not quite sure what similarities we share then. For me it works when I use Chrome, but it doesn't work on Firefox, it's also pretty irrelevant whether I use Turbopack and the app directory, or not.

**Comment by leerob** [comment] 2023-01-16 19:01
Can anyone reproduce this in CodeSandbox for example? That would help pinpoint if it's a Next.js issue or an issue with your machine (e.g. it's still working as expected on my machine). It's also possible it's a Windows issue.

There was one posted above, but it's using Windi CSS which I'm not sure if the common theme here.

**Comment by cdedreuille** [comment] 2023-01-16 21:35
@leerob Here is a codesandbox to reproduce the issue I'm having.

https://codesandbox.io/p/sandbox/quizzical-austin-9rcihp?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A10%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A10%7D%5D&file=%2Fpages%2Ftest.tsx

If `appDir` is set to false, tailwind updates without any issue when you save the file. But if `appDir` is set to true then I have to reload every time to see the update. I just want to make it clear that this is happening for me on the pages routing system. In my case, I have Sanity in the new app folder and I have to keep my site in the pages folder because the 'as' property is not there yet in the new routing. I hope this makes sense.

I also made a video to show the issue just in case: https://share.cleanshot.com/rWbx5WHx

**Comment by leerob** [comment] 2023-01-16 22:30
@cdedreuille Looking at your [repro](https://codesandbox.io/p/sandbox/quizzical-austin-9rcihp?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A10%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A10%7D%5D&file=%2Fpages%2Ftest.tsx), it is working for me. What am I missing?

https://user-images.githubusercontent.com/9113740/212774511-f24afdbf-9966-422e-a301-24e8d2ef837d.mp4


https://user-images.githubusercontent.com/9113740/212774646-6c85e73d-b860-46b1-b859-ddca96cd4af2.mp4

**Comment by engageintellect** [comment] 2023-01-16 23:32
Deleted node_modules, installed tailwind first, then running npm I solved my issue.

For reference, I was unable to re-produce on a Mac, only WSL.

All good here 👍🏻

**Comment by chunsch** [comment] 2023-01-17 01:51
@leerob I use `create-next-app@canary' to create a project and find that if you modify tailwindcss in the app directory, the page will be forced to refresh and scroll to the top.

In this [repro](https://codesandbox.io/p/sandbox/quizzical-austin-9rcihp?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A10%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A10%7D%5D&file=%2Fapp%2Fabout%2Fpage.tsx), I modify the code of `app/about/page.tsx`, scroll to the bottom, and then modify the last element, and find that every modification will scroll to the top.

```tsx
export default function About() {
  return (
    <div>
      <div className="h-[100vh] text-red-600">Block 1</div>
      <div className="h-96 text-blue-600">Block 2</div>
      <div className="h-96 text-yellow-600">Block 3</div>
    </div>
  );
}
```

https://user-images.githubusercontent.com/14866288/212792379-f55dfaae-2429-4cc8-9d13-368e0711f69e.mov

**Comment by leonardorb** [comment] 2023-01-17 14:19
The problem here is the layout structure, like @DerTyp876 mentioned. Making sure to have the proper structure solves the issue.

**Comment by cdedreuille** [comment] 2023-01-17 16:06
@leerob 

> @cdedreuille Looking at your [repro](https://codesandbox.io/p/sandbox/quizzical-austin-9rcihp?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A10%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A10%7D%5D&file=%2Fpages%2Ftest.tsx), it is working for me. What am I missing?
> 
>  CleanShot.2023-01-16.at.16.27.49.mp4 
>  CleanShot.2023-01-16.at.16.29.44.mp4

@leerob You are editing app/page.tsx not pages/test.tsx. My problem happen only in the pages folder, not the app folder.

**Comment by leerob** [comment] 2023-01-18 03:16
The second video is `pages/text.tsx`.

**Comment by cdedreuille** [comment] 2023-01-18 12:27
@leerob I've tested your video and it seems that the colours have been generated somehow. If you try with a completely new colour like `bg-emerald-200` or `bg-[#FFD000]` you'll see that this colour is not applied.

You'll see in this video that colours I've used previously are updated straight away but if I try a new colour like `bg-yellow-200` in my case it is not generated. I have to refresh to make this colour available.

https://user-images.githubusercontent.com/1540635/213171154-4d346913-e109-40b6-8008-f6b6e42188ec.mp4

**Comment by kleinesNugget** [comment] 2023-01-19 09:43
As for me I couldn’t get it to work in neither pages, nor app directory, also didn’t matter whether I was using Turbopack or not.

**Comment by surjithctly** [comment] 2023-01-19 13:24
Tailwind Integration is indeed buggy in Next 13. Both Pages and app, there are some issues. 

Recently, none of my styles was affecting, but `pnpm build and start` loaded it correctly. It did not work on `pnpm dev`

finally added a `space` in the tailwind CSS file. Just just a space. Then it worked. Wasted half an hour debugging why it did not work. I also think deleting `.next` would also have chances to work. 

**For Next.js team, Please add a `--tw-debug` flag so that we can see what's happening with tailwind in the CLI. class added or refreshed or loaded or everything verbose.**

**Comment by psugihara** [comment] 2023-01-19 17:04
I've noticed that sometimes it will start working in safari if I totally quit and restart the browser (not just hard refresh or close the page).

**Comment by sroussey** [comment] 2023-01-23 17:12
I see this failure on MacOS using Next 13.1.4, so still not fixed.

**Comment by SheryConcepts** [comment] 2023-01-24 09:35
Hy, I am also facing this issue. I am am using nextjs v13.1.5 (also same issue on 13.1.4).

On save, classes in browser do get changed but for them to take effect browser needs to be refreshed. But when use a previously class that took effect. Styles work without manually refreshing. 

I tested on firefox and brave.

In the video when i switch 'p-20' to 'p-10' (which is previously used class that took effect on refresh) ui changes without refreshing the browser. But when I change 'p-10' to 'p-24' (which is not used previously) and hit save, class in browser console change but ui does not change. Then i refresh and 'p-24' takes effect.

My guess is that styles are not being generated by tailwind on save. ( its just a guess, i dont know anything)

![simplescreenrecorder-2023-01-24_14 18 08](https://user-images.githubusercontent.com/63170620/214256410-eab6b50a-5189-4be6-9674-e4de892b8085.gif)

**Comment by laneme** [comment] 2023-01-24 16:38
The issue does exist on `13.1.1` and `13.1.5` for me.

But I would also like to confirm the issue DOES happen on Firefox and DOES NOT happen on Chromium. I'm using ubuntu but i dont think that matters. 

I inspected the requests on both browsers and it seems firefox isnt sending the css requests. See the screenshots below

![image](https://user-images.githubusercontent.com/26094878/214348034-75fca414-6398-47d1-a64a-a996626a8c9f.png)
![image](https://user-images.githubusercontent.com/26094878/214348514-5dc22595-659a-46ea-9448-c7a28cb0f5be.png)



Another thing i noticed the request to `/` (happens on each refresh) returns different response on chrome versus firefox. Could be the same thing differently encoded/compressed which i'm not sure. Just helping with my little obsevations.

![image](https://user-images.githubusercontent.com/26094878/214349402-98bf440a-1b2c-470d-abc3-c01e24d22ac2.png)
![image](https://user-images.githubusercontent.com/26094878/214349653-6a16f5b8-f41c-4e79-bd4b-23a34e04acdf.png)

**Comment by matthewdavi** [comment] 2023-01-25 18:03
This is happening on 13.1.5 for me in both the app dir and pages dir. Tailwind works but requires a hard refresh in Chrome, Brave, and Safari.

**Comment by laneme** [comment] 2023-01-27 21:08
> This is happening on 13.1.5 for me in both the app dir and pages dir. Tailwind works but requires a hard refresh in Chrome, Brave, and Safari.

Interesting, the issue might really be browser independent then. 

@matthewdavi But do you encounter the issue in pages directory when the appDir feature is disabled in next.config?

**Comment by vanquishkuso** [comment] 2023-01-28 14:04
I had problems with 13.1.4 and so on, tried almost everything in this thread but still didn't work. But upgrading to canary 13.1.6 fixed it for me and it works on Firefox and Chrome using Windows.

**Comment by laneme** [comment] 2023-01-28 17:24
> I had problems with 13.1.4 and so on, tried almost everything in this thread but still didn't work. But upgrading to canary 13.1.6 fixed it for me and it works on Firefox and Chrome using Windows.

@vanquishkuso  Are you saying _this issue_ was fixed for you after you upgraded to `13.1.6-canary`?

Next `13.1.6` was released today. I upgraded it to it. The issue still remains for me :/

**Comment by ngimdock** [comment] 2023-01-28 18:24
Tailwind classes don't work, i am on nextjs `13.1.6`.

**Comment by IsraelOgas** [comment] 2023-01-28 19:22
> Tailwind classes don't work, i am on nextjs `13.1.6`.

@ngimdock I was testing today the latest version of NEXTJS creating a project from scratch, I did the configuration of the tailwindcss beta documentation with next 13 and the styles were not working. And it was because I put in the installation "use /src" in the project. Then looking for the error in stackoverflow, I noticed that when copying/pasting the tailwind.config.js, I forgot to change the path of the content.

Source: [https://stackoverflow.com/a/75151704](url)

**Comment by ngimdock** [comment] 2023-01-28 19:53
> > Tailwind classes don't work, i am on nextjs `13.1.6`.
> 
> @ngimdock I was testing today the latest version of NEXTJS creating a project from scratch, I did the configuration of the tailwindcss beta documentation with next 13 and the styles were not working. And it was because I put in the installation "use /src" in the project. Then looking for the error in stackoverflow, I noticed that when copying/pasting the tailwind.config.js, I forgot to change the path of the content. I feel SO Stup.... XD
> 
> Source: [Stackoverflow Comment](https://stackoverflow.com/a/75151704)

Thanks for your sharing @IsraelOgas it solve my problem and i am feeling so stup** too

**Comment by vanquishkuso** [comment] 2023-01-29 21:45
> > I had problems with 13.1.4 and so on, tried almost everything in this thread but still didn't work. But upgrading to canary 13.1.6 fixed it for me and it works on Firefox and Chrome using Windows.
> 
> @vanquishkuso Are you saying _this issue_ was fixed for you after you upgraded to `13.1.6-canary`?
> 
> Next `13.1.6` was released today. I upgraded it to it. The issue still remains for me :/

I did a from scratch installation with canary, didn't upgrade from an earlier version. If I recall I installed Tailwind first as well as mentioned in this thread. Maybe you can try cloning my test repo portfolio and see if it works?

**Comment by laneme** [comment] 2023-01-30 09:29
@vanquishkuso Thank you for following up. I assume you mean this repo https://github.com/vanquishkuso/portfolio

I cloned it and the issue is still there. Feels weird.

I even quickly booted into a windows machine, just to be sure, installed node `18.13.0`  (noticed you using 18), tested it on firefox 109 and chromium. The issue is still there. 

The issue was even severe in windows. On linux, styles updated if i just reloaded the page. And worked fine on chromium. Not on windows, had to restart the next dev server for the classnames to be effective. Very weird :/


I'll leave my versions for others

Windows: npm `v8.19.3`, node `v18.13.0`, firefox 109
Ubuntu: yarn `v3.1.1`, npm `v18.19.3`, node `v16.19.0`, firefox 109, chromium 109

**Comment by rvanbaalen** [comment] 2023-01-30 20:57
Here to confirm this is still an issue in `NextJS 13.1.6`

Works in Chrome/chromium, doesn't work in Firefox (both macos).

**Comment by sroussey** [comment] 2023-01-30 21:29
Here are the network panel recordings for both:

Chrome: (note that is reloads the css file -- twice)
<img width="619" alt="image" src="https://user-images.githubusercontent.com/127349/215598853-4db05afe-6703-4e7e-8c25-ef92ffa4b76e.png">

Firefox: (note that no css is reloaded)
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/127349/215599107-18063353-62dc-42db-8d04-13f8a0fcf95d.png">

**Comment by sroussey** [comment] 2023-01-31 00:34
So, I looked into it more. Firefox does not reload a css file by the same name if you add it to the `document.head`. You can do one of two things: delete the link to css first and then add it back, or use a different name.

NextJS is using MiniCssExtractPlugin ([see here](https://github.com/vercel/next.js/blob/canary/packages/next/src/build/webpack/config/blocks/css/index.ts#L553)).

**Comment by sroussey** [comment] 2023-01-31 00:36
Here is a potential fix (will fix ordering issue that may exist in addDir that did not exist elsewhere:

Search you node_modules for `chunkFilename: ctx.isProduction ? "static/css/[contenthash].css" : "static/css/[name].css"` which you will find in two files. In the line after, add this:

```
            insert: function (linkTag) {
                const previous = Array.from(document.head.children).find(link=>link.href===linkTag.href);
                const after = previous?.previousElementSibling;
                console.log({linkTag, previous, hre: linkTag.href, after})
                
                if (after) {
                    after.insertAdjacentElement(linkTag)
                } else {
                    document.head.appendChild(linkTag)
                }
                
                if (previous) {
                    previous.parentElement.removeChild(previous);
                }
              },
```

The whole section will then look like this:

```
new MiniCssExtractPlugin({
            filename: ctx.isProduction ? "static/css/[contenthash].css" : "static/css/[name].css",
            chunkFilename: ctx.isProduction ? "static/css/[contenthash].css" : "static/css/[name].css",
            insert: function (linkTag) {
                const previous = Array.from(document.head.children).find(link=>link.href===linkTag.href);
                const after = previous?.previousElementSibling;
                console.log({linkTag, previous, hre: linkTag.href, after})
                
                if (after) {
                    after.insertAdjacentElement(linkTag)
                } else {
                    document.head.appendChild(linkTag)
                }
                
                if (previous) {
                    previous.parentElement.removeChild(previous);
                }
              },
            // Next.js guarantees that CSS order "doesn't matter", due to imposed
            // restrictions:
            // 1. Global CSS can only be defined in a single entrypoint (_app)
            // 2. CSS Modules generate scoped class names by default and cannot
            //    include Global CSS (:global() selector).
            //
            // While not a perfect guarantee (e.g. liberal use of `:global()`
            // selector), this assumption is required to code-split CSS.
            //
            // If this warning were to trigger, it'd be unactionable by the user,
            // but likely not valid -- so we disable it.
            ignoreOrder: true
        })));
```

Then `npm start dev` again and see if things work. Let me know please!

**Comment by shuding** [comment] 2023-02-01 00:55
Hi all, we are tracking the issue here instead: https://github.com/vercel/next.js/issues/43396#issuecomment-1405218446.
