### ISSUE TITLE
Next.js does not revalidate pages if the page has been removed from the LRU cache whilst still on disk

### ISSUE THREAD

**Issue by joriregter** [vercel/next.js#26689] opened 2021-06-28 15:15 UTC
### What version of Next.js are you using?

11.0.2

### What version of Node.js are you using?

14 (N/A)

### What browser are you using?

Chrome (N/A)

### What operating system are you using?

macOS, deployed on Linux

### How are you deploying your application?

next start (using Platform.sh)

### Describe the Bug

Next.js does not keep track of `revalidateAfter` on disk, which breaks the caching system when these cases apply:

1. the page is on disk
2. the page is not in memory (removed by max size of LRU cache)

Instead of marking the page as stale, the page on disk is read and put into the LRU cache as if its data has just been requested. However, the `revalidateAfter` is set to the specified `revalidate` value of the page on disk and the page isn't actually revalidated.

In practice, websites with heavy traffic or with large pages and websites that aren't redeployed often have pages that aren't revalidated when updated (for example, by a CMS). In turn, clients won't see changes they're applying to the CMS at all.

### Expected Behavior

Next.js should keep track of the `revalidateAfter` time on disk as well, so it can fallback to the original `revalidateAfter` value instead of to simply refreshing it as if it were new.

### To Reproduce

The issue is somewhat hard to reproduce, because it requires the LRU cache to be full. Although, by reading the code, you can logically deduce this is happening.

1. Cache is instantiated with a max at 50MB. Over time, this can hit that limit.
https://github.com/vercel/next.js/blob/5b2c845e57ca3ba156901f8669465ea9761e0293/packages/next/next-server/server/incremental-cache.ts#L73-L82

2. In the get function, the requested page is read from the incremental cache. In case the limit of the LRU cache is reached and the page can't be found, Next.js tries to read it from disk.
https://github.com/vercel/next.js/blob/5b2c845e57ca3ba156901f8669465ea9761e0293/packages/next/next-server/server/incremental-cache.ts#L115-L119

3. If it's found on disk, the time this page was revalidated isn't considered, but refreshed instead, leading to the page wrongfully being marked fresh.
https://github.com/vercel/next.js/blob/5b2c845e57ca3ba156901f8669465ea9761e0293/packages/next/next-server/server/incremental-cache.ts#L127-L142

The problem can be resolved by keeping track of the `revalidateAfter` time on disk as well. Using a patch in production, we have been able to resolve this problem by doing so.  The patch roughly does the following:

_Upon page creation/revalidation, our patch basically writes the `revalidateAfter` time to a `[page].metadata.json` file. This file is read in step (3) line 139 to determine the revalidation time instead of refreshing it altogether._

In case this is the correct path to solving this problem, we can create a pull request including this fix. If not, let's discuss a better solution, so we can fix this issue.

**Comment by jamsinclair** [comment] 2021-06-29 07:24
I believe the following issue and PR are also related: https://github.com/vercel/next.js/issues/24806 https://github.com/vercel/next.js/pull/24807 and may help give more context 🕵️

**Comment by Stefwint** [comment] 2021-07-15 07:11
We're running into the same issue on our project. When there is a new build it works for a bit, but after a while it stops working. So I'm pretty sure the LRU cache is also running full in our case.

@joriregter Would you mind sharing your patch to see if this will work for us?

**Comment by stefanb2** [comment] 2021-07-20 12:18
I guess this one could also be closed as duplicate of #24806

**Closed** 2021-07-20 17:01 UTC
Labels: template: bug

**Comment by ijjk** [comment] 2021-07-20 17:46
Hi, this has been updated in `v11.0.2-canary.18` of Next.js, please update and give it a try!

**Comment by balazsorban44** [comment] 2022-01-28 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
