### ISSUE TITLE
next route with GET parameter redirect without locale if it's default one

### ISSUE THREAD

**Issue by AntoineBourin** [vercel/next.js#25648] opened 2021-05-31 15:41 UTC
### What example does this report relate to?

next/router - next i18n

### What version of Next.js are you using?

10.1.1

### What version of Node.js are you using?

12.0.0

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

I use nextJS with internationalization. 
I have different locale in my next project : 
`i18n: {
    locales: ['fr-fr', 'fr-be', 'nl-be'],
    defaultLocale: 'fr-fr',
  },`
  
When I'm trying to access my website with : `localhost:3000/fr-fr` -> it works. No redirection.
When I'm trying to access with same URL but with a GET parameter e.g : l`ocalhost:3000/fr-fr?next=test `-> the application redirect me to `localhost:3000/?next=test`.

This behavior happen only with default locale. If I add a parameter with locale nl-be for example, the locale is not deleted.

### Expected Behavior

I would like to be able to keep the default locale in the URI when a GET parameter is added inside.

### To Reproduce

1. Enable internationalization on your next app.
2. Choose a defaultLocale (e.g. "en").
3. Access to your website with this locale inside your request : localhost:3000/en
4. Now, add a GET parameter inside : localhost:3000/en?test=ok
5. You will be redirect without the defaultLocale : localhost:3000/?test=ok

**Comment by ijjk** [comment] 2021-09-21 05:24
Closing in favor of https://github.com/vercel/next.js/discussions/18419

**Closed by ijjk** 2021-09-21 05:24 UTC
Labels: type: example, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
