### ISSUE TITLE
[BUG] Error on auto generated OpenAPI(@openapitools/openapi-generator-cli) file when upgrading to Next.js 12

### ISSUE THREAD

**Issue by rajanvalencia** [vercel/next.js#31300] opened 2021-11-11 13:03 UTC
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

Error on auto generated OpenAPI file when upgrading to Next.js 12.

<img width="962" alt="スクリーンショット 2021-11-11 20 11 03" src="https://user-images.githubusercontent.com/47655366/141302195-07a34095-f276-4958-81e8-07bbfe59e915.png">

### Expected Behavior

No errors and can call API successfully.

### To Reproduce

1. Install `@openapitools/openapi-generator-cli` 
[https://www.npmjs.com/package/@openapitools/openapi-generator-cli](https://www.npmjs.com/package/@openapitools/openapi-generator-cli)

2. Try to call api from the auto generated file.

**Comment by nik0145** [comment] 2021-11-15 11:10
This can be fixed by creating a `.babelrc.js` file.
```
module.exports = {
  presets: ['next/babel'],
};
```
But SWC will be disabled.
I recreated the situation on [codesandbox ](https://codesandbox.io/s/yf7c3?file=/.babelrc.js:0-48)

**Comment by nik0145** [comment] 2021-12-07 09:43
fixed in version next@12.0.7

**Comment by balazsorban44** [comment] 2021-12-07 22:30
This is indeed fixed. Please upgrade to `next@12.0.7`

**Closed by balazsorban44** 2021-12-07 22:30 UTC
Labels: template: bug, area: SWC transforms

**Comment by balazsorban44** [comment] 2022-01-27 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
