### ISSUE TITLE
Module not found: Can't resolve './pages/500' in '/Users/user/Desktop/my-app'

### ISSUE THREAD

**Issue by saurabhguptarock** [vercel/next.js#31492] opened 2021-11-16 12:47 UTC
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Module not found: Can't resolve './pages/500' in '/Users/user/Desktop/my-app'

This is what is shown on screen.
<img width="667" alt="Screenshot 2021-11-16 at 18 14 44" src="https://user-images.githubusercontent.com/32234038/141987465-6b05306f-bb89-4186-b17d-a2c06e22406f.png">

### Expected Behavior

The project should not give any error

### To Reproduce

Create a new project

my next.config.js file

const moduleExports = {
  experimental: {
    reactRoot: true,
    concurrentFeatures: true,
    serverComponents: true,
  },
};

module.exports = moduleExports;

it gives errors on new project;

This is what is shown on screen.
<img width="667" alt="Screenshot 2021-11-16 at 18 14 44" src="https://user-images.githubusercontent.com/32234038/141987465-6b05306f-bb89-4186-b17d-a2c06e22406f.png">

**Comment by sauloquirino** [comment] 2021-11-17 03:26
I'm having the same issue.
Latest React 18 Beta
Same configs in my next.config.js file

**Comment by mapsgeek** [comment] 2021-11-18 18:42
I'm trying to test suspense with concurrent mode config and get the same error

**Comment by huozhi** [comment] 2021-11-18 19:04
Can you try with latest canary? It's fixed in 12.0.5-canary.0

**Comment by mapsgeek** [comment] 2021-11-18 19:13
@huozhi  trying the latest canary, just with basic `concurrentFeatures: true` 
not used any suspense in my code or dynamic imports, gives an error `error - ReferenceError: window is not defined`

**Comment by huozhi** [comment] 2021-11-18 19:22
@mapsgeek The `concurrentFeatures` is running inside the a custom web runtime which doesn't support `window` as global reference but `globalThis`. The browser bundle of package will be consumed if there's one. Might be caused by some library using any library that using window directly without checking. It's an known issue, we're working on it to provide more flexibility to let user play with node runtime in the future

**Comment by huozhi** [comment] 2022-12-01 12:34
This should be resolved by the [server components under app directory in next 13](https://nextjs.org/blog/next-13#server-components) already

**Closed by huozhi** 2022-12-01 12:34 UTC
Labels: template: bug, area: Server Components, please verify canary
