### ISSUE TITLE
Next.js cra to next not working.

### ISSUE THREAD

**Issue by angelo1104** [vercel/next.js#26268] opened 2021-06-17 14:30 UTC
### What version of Next.js are you using?

11

### What version of Node.js are you using?

14.6.1

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04

### How are you deploying your application?

next start

### Describe the Bug

I tried `npx @next/codemod cra-to-next my-app --dry` and it didn't work instead it gave an error.

`Error: Cannot find module 'jscodeshift/src/runner'
Require stack:
- /home/madhav/.npm/_npx/a0dc7465aefb54f9/node_modules/@next/codemod/lib/run-jscodeshift.js
- /home/madhav/.npm/_npx/a0dc7465aefb54f9/node_modules/@next/codemod/transforms/cra-to-next.js
- /home/madhav/.npm/_npx/a0dc7465aefb54f9/node_modules/@next/codemod/bin/cli.js
- /home/madhav/.npm/_npx/a0dc7465aefb54f9/node_modules/@next/codemod/bin/next-codemod.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/madhav/.npm/_npx/a0dc7465aefb54f9/node_modules/@next/codemod/lib/run-jscodeshift.js:7:34)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
`

This is the error. I tried `npm install -g jscodeshift` but it didn't fixed the error.

### Expected Behavior

It should try to transform the create react app into a next js app and print the files which would be changed.

### To Reproduce

`npx @next/codemod cra-to-next your-cra-app --dry`

**Comment by timneutkens** [comment] 2021-06-17 14:37
This has been fixed on canary already 👍 you can try it out using `npx @next/codemod@canary`

**Closed by timneutkens** 2021-06-17 14:37 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 06:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
