### ISSUE TITLE
DELETE HTTP Method still doesn't work for any version above 13.2.4 ( May 5, 2023 )

### ISSUE THREAD

**Issue by OatsProgramming** [vercel/next.js#49353] opened 2023-05-06 05:06 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64

    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A

    Relevant packages:
      next: 13.4.1-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/OatsProgramming/nextjs-http-issue

### To Reproduce

Simply call DELETE method in any of your Route Handlers and try to parse JSON data

### Describe the Bug

I understand that with the repo I've provided would require additional things to reproduce the issue such as OAuth for Github and Google; however, that's another issue that I'm dealing with that I won't go any further as it concerns NextAuth, not NextJS. Instead, the repo only concerns itself with "Credentials".

Even with that said, it doesn't really matter if we're talking about auth or not: **the main concern is the HTTP method, DELETE**. I've brought this issue before ( and I'm sure many others as well ) in the question section, but I'd like to try my best to bring it to light again as it seems that 13.4 is considered stable. If Route Handlers fall under that category, then I'm afraid that it shouldn't be considered ready. 

I want to clarify: I absolutely love how NextJS makes frontend and backend come together ever so easily. That is why I'm trying to bring this into light. It makes a freshie like myself feel like a true developer. I don't want it to be bashed for something minor. 

The bug is this: **it doesn't delete**. If you try to do the following:
```typescript
...
const res = await fetch('api/insertRoute', {
  method: 'DELETE',
  headers: {
    'Content-Type': 'application/json'
  },
  body: JSON.stringify(data)
}
...
```

It will call DELETE method in your API. However, it won't be able to parse the JSON data you give it. 
The code: 
```typescript
export async function DELETE(req: Request) {
    // added console.log here to see if it's being called
    console.log('hello')

    const body = await ValidReq(req) as User | Response
    if (body instanceof Response) return body

    const user = await prismadb.user.delete({
        where: { email: body.email }
    })

    return new Response(JSON.stringify(user), { status: 200 })
}

...

async function ValidReq(req: Request) {
    const body = await req.json()

    // Check if user exists
    const user = await prismadb.user.findUnique({
        where: { email: body.email}
    })
    if (!user) {
        return new Response("User not found", { status: 404 })
    }
    
    // Check if password matches
    else if (!(await compare(body.password, user.hashedPassword))) {
        return new Response("Password mismatch", { status: 401 })
    }

    return body
}
```

The error:
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at NextRequest.json (node:internal/deps/undici/undici:6160:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ValidReq (webpack-internal:///(sc_server)/./app/api/user/route.ts:90:18)
    at async DELETE (webpack-internal:///(sc_server)/./app/api/user/route.ts:78:18)
    at async eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:244:37)
```

### Expected Behavior

To be able to parse JSON data in DELETE method

**Comment by MatheusCamargo-dev** [comment] 2023-05-06 16:31
I am also having the same problem in version 13.4.1

**Comment by Farhanaziz95** [comment] 2023-05-06 20:03
I'm also having the same issue but with post request sending the data its shows that payload is sent with that data but when it reaches the endpoint of api the request.body does not retrieve that data

**Comment by Kaligraphy247** [comment] 2023-05-06 20:47
Having the same issue with Nextjs 13.4, with a simple GET request

**Comment by sannajammeh** [comment] 2023-05-07 00:02
> RFC 2616 does not explicitly prohibit or encourage sending a body with an HTTP DELETE request, but most servers ignore it.

From what I have experienced, body is ignored on almost every data framework. A delete request should for the most part only contain an identifier in the URL.

As far as I can see this is not a bug, but a lack of feature which almost no framework includes.

**Comment by OatsProgramming** [comment] 2023-05-07 00:15
@sannajammeh 
Whatever the case may be, NextJS 13.2.4 and lower had no issues with any HTTP methods. Because of the updates, it has become an issue, rather than a lack of feature as it was available and working in the first place. 

The issue can be circumvented with a POST request, but it won't be considered solve if there needs to be a workaround.

**Comment by tonymmm1** [comment] 2023-05-07 01:40
I am having a similar issue which I first assumed was an issue with Prisma ORM. https://github.com/prisma/prisma/issues/19119. But if this is the case with all api requests using Delete method that would be a problem.

**Comment by tonymmm1** [comment] 2023-05-07 01:48
I can confirm by reverting nextjs package the delete method works again.

```
npm i next@13.2.4
```

**Comment by simonknittel** [comment] 2023-05-07 17:18
Duplicate of https://github.com/vercel/next.js/issues/48096

**Comment by OatsProgramming** [comment] 2023-05-07 17:49
> Duplicate of #48096

@simonknittel As I've stated earlier, I understand that there are people that have brought up this issue before ( as well as I have in the past with #48072 ); I was even one of those that told the issue to that person that created #48096.

> ...I'd like to try my best to bring it to light again as it seems that 13.4 is considered stable. If Route Handlers fall under that category, then I'm afraid that it shouldn't be considered ready.

There's a boundless amount of issues being posted here and I've checked some of them: it turns out some of their bugs are actually caused by their own code rather than the NextJS framework, which would hinder the Vercel team in trying to resolve actual issues with the framework. I'm trying to bring this into light as it seems that it's being overshadowed by the thousands upon thousands of other issues that actually may or may not relate to the NextJS framework.

**Comment by palamago** [comment] 2023-05-08 14:58
Kind of duplicate of: https://github.com/vercel/next.js/issues/48898
My isolated proof of the issue: https://codesandbox.io/p/sandbox/nextjs-issue-canary-xyyiu7

**Comment by DarkSmile92** [comment] 2023-05-11 19:13
`v13.2.4` I found this works on deployed docker containers, but on localhost the issue exists. Strange.

**Comment by ijjk** [comment] 2023-05-18 05:07
Closing in favor of https://github.com/vercel/next.js/issues/48096

**Closed by ijjk** 2023-05-18 05:07 UTC
Labels: template: bug

**Comment by Hakeemmidan** [comment] 2023-05-21 17:17
I'm facing the same issue with a GET request on `next@13.4.3`
