### ISSUE TITLE
notFound() wrong Metadata after hydration

### ISSUE THREAD

**Issue by valeryq** [vercel/next.js#68392] opened 2024-08-01 10:15 UTC
### Link to the code that reproduces this issue

https://github.com/valeryq/nextjs-not-found-metadata-bug-debug

### To Reproduce

There are 2 behaviors:
1. Route does not exist at all in the application (**work as expected**).
**URL:** https://nextjs-not-found-metadata-bug-debug.vercel.app/

![image](https://github.com/user-attachments/assets/c30726ec-2b6b-4179-88da-5f979a91e3e2)

2. Route `/test` with `notFound()` in Server Component render function (**doesn't work as expected, wrong metadata**).
**URL:** https://nextjs-not-found-metadata-bug-debug-p93w1k52u.vercel.app/test

P.S. The metadata does not exist at all in not-found.tsx. If there is some metadata in layout.tsx, it will apply, but not the metadata from not-found.tsx. Although the server-rendered HTML returned from the server contains the title, after hydration it seems like something overrides it, because I can see a brief flash of the 404 | Not found title, and then it disappears.
![image](https://github.com/user-attachments/assets/cd2120d6-49a8-4159-a0e7-319ddefdad16)
![image](https://github.com/user-attachments/assets/f0dce09f-d33d-4ac4-ac72-dcad5daf45b6)

### Current vs. Expected behavior

**Current:**
Metadata from `not-found.tsx` isn't applied when `notFound()` function is invoked manually.

**Expected:**
Metadata is applied from `not-found.tsx` when `notFound()` function is invoked manually.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 20.12.0
  npm: 10.5.0
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Metadata

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed), Other (Deployed)

### Additional context

The result is the same whether I use local dev server, built version, deployed on Vercel or custom build on k8s cluster in docker container.

**Comment by jrjake** [comment] 2024-08-03 18:43
I think this might be a duplicate of #45620, this person has a workaround for specifically calling notFound() in a page: https://github.com/vercel/next.js/issues/45620#issuecomment-2115853279

**Comment by valeryq** [comment] 2024-08-05 11:31
@jrjake It looks like invoking `notFound()` fn in my dynamic page in `generateMetadata` gives no positive effect and even worse, I received nothing even from parent `generateMetadata`.

**Comment by samcx** [comment] 2024-08-08 22:01
@valeryq Thank you for submitting an issue!

Can confirm this is still an issue! I will close this one in favor of the original.

**Closed by samcx** 2024-08-08 22:01 UTC
Labels: bug, Metadata
