### ISSUE TITLE
"Component definition is missing display name" Next.js build fail using code from docs

### ISSUE THREAD

**Issue by tr1s** [vercel/next.js#29204] opened 2021-09-19 01:41 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

15.5.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

A recent update in my `npm` packages _(probably from Next.js)_ has caused build failures.

The code [styled-components provides in the docs](https://styled-components.com/docs/advanced#nextjs) that you add to `_document.js` in order for styled-components to work in a Next.js project is no longer working.

I can't figure out how to fix this code even when looking at the [react/display-name rules](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/display-name.md). Any help would be appreciated, thank you!

**The error I get in vercel:**

<img width="787" alt="CleanShot 2021-09-18 at 21 13 24@2x" src="https://user-images.githubusercontent.com/19172250/133912377-97e27cc0-ff65-43a2-98f0-81dabf0370a6.png">

**What the error looks like in my code:**

<img width="1113" alt="CleanShot 2021-09-18 at 21 01 36@2x" src="https://user-images.githubusercontent.com/19172250/133912303-69a3896f-5ce4-4480-8faf-1e9105a94fc4.png">

**These are the package updates I made that caused the sudden build failure:**

<img width="1454" alt="CleanShot 2021-09-18 at 21 24 54@2x" src="https://user-images.githubusercontent.com/19172250/133912527-cb4302f7-7e39-4ac2-8536-6cc3110a37ec.png">

### Expected Behavior

No build errors.

### To Reproduce

Add the [code from styled-components docs](https://styled-components.com/docs/advanced#nextjs) to `_document.js` in order for styled-components to work in a Next.js project.

**Comment by stefanprobst** [comment] 2021-09-19 07:50
see https://github.com/vercel/next.js/issues/28786#issuecomment-913625103

**Comment by ijjk** [comment] 2021-09-19 15:02
Closing as a duplicate of https://github.com/vercel/next.js/issues/28786#issuecomment-913625103 per above comment

**Closed by ijjk** 2021-09-19 15:02 UTC
Labels: template: bug

**Comment by tr1s** [comment] 2021-09-19 15:23
For whoever stumbled across this:

[Naming the function](https://github.com/vercel/next.js/issues/28786#issuecomment-913625103) doesn't fix this issue, but [downgrading `eslint-config-next`](https://github.com/vercel/next.js/issues/28786#issuecomment-913485325) does fix the build error.

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
