### ISSUE TITLE
Docs: Fix colors in deduplicated-fetch-requests.png

### ISSUE THREAD

**Issue by SubsequentlySneeds** [vercel/next.js#53394] opened 2023-07-31 16:20 UTC
### What is the improvement or update you wish to see?

The second "C" request in the "Multiple Requests in a Component Tree" section on the left is colored blue, but the "C" requests are color-coded red. 

This is the current image:

![light](https://github.com/vercel/next.js/assets/118424338/070d5297-48c8-4676-8cd8-98a7b3911c0f)

Here are fixed versions for both dark and light mode:

 
![dark-fixed](https://github.com/vercel/next.js/assets/118424338/370ae561-64e7-413c-8389-15dc3bdd26bc)
![light-fixed](https://github.com/vercel/next.js/assets/118424338/aeba6bc5-7984-4aa6-a283-54a534b63c84)

### Is there any context that might help us understand?

The bubble in the component tree doesn't match the corresponding bubble in the "All Requests" section, which can be confusing for users trying to track where the component requests ended up.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching

**Comment by balazsorban44** [comment] 2023-08-01 06:48
Duplicate of #53360

**Closed** 2023-08-01 06:48 UTC
Labels: template: documentation
