### ISSUE TITLE
Latest version 10.1.3 is not working with ie11

### ISSUE THREAD

**Issue by devzhen** [vercel/next.js#24058] opened 2021-04-14 13:41 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

v12.17.0

### What browser are you using?

IE 11

### What operating system are you using?

Windows 10

### How are you deploying your application?

heroku

### Describe the Bug

Have created a nextjs app using create-next-app

![image](https://user-images.githubusercontent.com/23298767/114718880-1bcf4100-9d3f-11eb-9c4a-1e25636494a3.png)

Run server with yarn dev

Open http://localhost:3000 with ie 11

It shows a blanket page and dev tool shows errors:

![Create Next App - Internet Explorer 2021-04-14 16](https://user-images.githubusercontent.com/23298767/114719908-33f39000-9d40-11eb-96a8-2226b20145d1.png)

### Expected Behavior

Should show start page

![image](https://user-images.githubusercontent.com/23298767/114720500-bc723080-9d40-11eb-96da-7ee63dc3108a.png)

### To Reproduce

$ create-next-app app_name

$ yarn dev

$ open http://localhost:3000 in ie11

**Comment by timneutkens** [comment] 2021-04-14 14:45
Duplicate of #22270

**Closed by timneutkens** 2021-04-14 14:45 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
