### ISSUE TITLE
`TypeError: fetch failed` for Edge API Routes running locally

### ISSUE THREAD

**Issue by jahirfiquitiva** [vercel/next.js#39207] opened 2022-07-31 20:23 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.1
      npm: 8.13.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.4-canary.8
      eslint-config-next: 12.2.3
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Edge

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

When accessing an API route setup to use the Edge Runtime, we'd get an error saying `TypeError: fetch failed`

![Shot 2022-07-31 at 15 08 09@2x](https://user-images.githubusercontent.com/10360816/182043621-33b41be8-d7a1-4734-bb93-5dec284448f5.png)

### Expected Behavior

The API should work normally and have a valid response.

### Link to reproduction

https://github.com/jahirfiquitiva/sponsors-edge-api

### To Reproduce

Run the project using `next dev` and access `http://localhost:3000/api/sponsors-edge` to see the error.

Also, I created a normal API route at `http://localhost:3000/api/sponsors` which works fine.

Worth mentioning this issue is not present in Next.js `12.2.2`, but started happening after updating to `12.2.3` (I didn't try the canary versions between `12.2.2` and `12.2.3`, but I tried the latest canary `12.2.4-canary.8` and this issue is still present)

**Comment by balazsorban44** [comment] 2022-07-31 20:44
Likely a duplicate of #38963

**Closed by balazsorban44** 2022-07-31 20:44 UTC
Labels: template: bug

**Comment by jahirfiquitiva** [comment] 2022-07-31 22:06
@balazsorban44 this isn't just for `Middleware` but API routes 🤔

**Comment by balazsorban44** [comment] 2022-07-31 22:42
Edge API routes and Middleware use the same runtime. 👍

**Comment by jahirfiquitiva** [comment] 2022-07-31 22:44
got it, thanks @balazsorban44 🙌
