### ISSUE TITLE
Next App with assetPrefix and basePath infinitely reloads pages with route params

### ISSUE THREAD

**Issue by egucciar** [vercel/next.js#14560] opened 2020-06-25 15:59 UTC
# Bug report

## Describe the bug

The Next App will infinitely reload itself on a page with route parsm (`[routeParam].js`) if using the assetPrefix and basePath features

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

https://github.com/egucciar/next-app-refresh-reproducer

Clone the above repo. `yarn` and `yarn dev`. Go to http://localhost:3000/next-app/example/broke . Observe the page. After a few seconds, the app will reload itself. It should not reload itself.

## Expected behavior

Page should load and only refresh itself if there are build changes.

## Screenshots

The reload originates from `on-demand-entries-utils` as seen here:

![image](https://user-images.githubusercontent.com/2848185/85754310-f3f0ed00-b6da-11ea-9a0c-1803874ac769.png)

![image](https://user-images.githubusercontent.com/2848185/85754362-feab8200-b6da-11ea-9236-a9ed70c47baf.png)

I could not dig deeper into the file here to find the specific cause because i could not add logging or more debugging breakpoints around it (from minification/mapping)

## System information

- OS: macOs
- Browser Chrome
- Version of Next.js: latest
- Version of Node.js:  10.16

**Comment by ijjk** [comment] 2020-06-25 20:36
Hi, this is fixed in `v9.4.5-canary.19` of Next.js, specifically this PR https://github.com/vercel/next.js/pull/14535

**Closed by ijjk** 2020-06-25 20:36 UTC
Labels: kind: bug, priority: p1

**Comment by balazsorban44** [comment] 2022-01-30 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
