### ISSUE TITLE
Intercepting Route with (..) Catch All route doesn't work

### ISSUE THREAD

**Issue by teodorus-nathaniel** [vercel/next.js#62643] opened 2024-02-28 12:49 UTC
### Link to the code that reproduces this issue

https://github.com/teodorus-nathaniel/nextgram-issue

### To Reproduce

1. Install Dep
2. Run in build mode or dev mode
3. Navigate to localhost:3000/nested
4. Click on one of the image
5. Click close on the modal

### Current vs. Expected behavior

Current:
It doesn't close the modal (the catch all route doesn't get matched)
But, if the route is using (.) (not in /nested) it works fine

Expected:
It closes the modal (matches the catch all route) because /cart doesn't have intercepting route

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 8.7.4
Relevant Packages:
  next: 14.1.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

### Additional context

This should work, according to [Parallel Routes Docs](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#closing-the-modal), and right now it also works if using the nextgram default routes (refer to commit [be2d6](https://github.com/teodorus-nathaniel/nextgram-issue/commit/be2d61b3cd9222002f81f6c525eea3314e4e6cc2) of my repro repo)

I tested this in next latest (14.1.0) and also canary, it has same behavior right now, and it also doesn't work either in build or dev mode

Here's my video of the issue
https://github.com/vercel/next.js/assets/53143942/46494430-9bb9-415e-859d-98f22641a507

**Comment by balazsorban44** [comment] 2024-02-28 14:43
So the link to the docs shows using `router.back()`, but you are trying to `router.replace("/nested")`, which I don't see why it should close the modal. You are on the same URL when the modal is open, so it won't have an affect on the state. :thinking:

A different approach you could take that also works with `router.replace` is using a regular state to control the dialog:

```diff
"use client";

+ import { type ElementRef, useState } from "react";
- import { type ElementRef, useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
import { createPortal } from "react-dom";

export function Modal({ children }: { children: React.ReactNode }) {
  const router = useRouter();
+ const [open, setOpen] = useState(true);

- const dialogRef = useRef<ElementRef<"dialog">>(null);

- useEffect(() => {
-   if (!dialogRef.current?.open) {
-    dialogRef.current?.showModal();
-   }
- }, []);

  function onDismiss() {
+   setOpen(false);
    router.replace("/nested");
  }

  return createPortal(
    <div className="modal-backdrop">
+      <dialog open={open} className="modal" onClose={onDismiss}>
-      <dialog ref={dialogRef} className="modal" onClose={onDismiss}>
        {children}
        <button onClick={onDismiss} className="close-button" />
      </dialog>
    </div>,
    document.getElementById("modal-root")!
  );
}
```

**Comment by teodorus-nathaniel** [comment] 2024-02-28 14:52
For the docs link, I mean this one where it says that you can use Link to close the modal
![image](https://github.com/vercel/next.js/assets/53143942/c2b3912b-ebc8-4c7a-8bf5-2075aafae11a)

for this statement:
```
You are on the same URL when the modal is open, so it won't have an affect on the state. 🤔
```
in the reproduction repo, it changes the url, where it should change remove the rendered modal

So here's the flow:
1. you are in /nested, which renders just list of images
2. you click on the image => redirect to /photos/1 which was intercepted and rendered as modal
3. you click close, you redirect to /nested => this should make the modal closed

if I'm not using (..), so like the original nextgram, it works
1. you are in /
2. you click on image => redirect to /photos/1, which was intercepted and rendered as modal
3. you click close => redirect to / => the modal closed

by my logic, the /nested one should also works the same way
pls let me know if I misunderstood something 🙏

**Comment by ztanner** [comment] 2024-02-28 16:06
Hi @teodorus-nathaniel -- since catch-all routes (`[...route]`) match everything except the index route (ie, `/nested/bar`, `/nested/bar/baz`, but not `/nested`), and you're linking back to the root page, you'd ideally use an optional catch-all route here (`[[...route]]`). This would include the index route. However, parallel routes don't yet support optional catch-all segments (but it's being tracked https://github.com/vercel/next.js/issues/61206).

In the meantime, you can work around this by having a @modal/page.tsx component that returns null. I tested that with your provided reproduction and it appears to have worked as you expect. I'm going to close this for now as there's a workaround and we'll continue to track the optional catch-all use-case in the above mentioned issue.

**Closed by ztanner** 2024-02-28 16:06 UTC
Labels: template: bug, area: Routing

**Comment by teodorus-nathaniel** [comment] 2024-02-28 17:37
Thanks for the explanation and quick feedback @ztanner @balazsorban44 🙏
Its clear now
