### ISSUE TITLE
API Route Query parameters are not accessible on Production.

### ISSUE THREAD

**Issue by AlexandraKlein** [vercel/next.js#20673] opened 2021-01-01 20:20 UTC
# Bug report

## Describe the bug

Query parameters aren't accessible in production. Using [https://github.com/vercel/next.js/blob/canary/examples/cms-contentful/pages/api/preview.js](https://github.com/vercel/next.js/blob/canary/examples/cms-contentful/pages/api/preview.js) as example.

## To Reproduce

In `/pages/api/preview.js`

```javascript 
export default async function preview(req, res) {
     const { slug, id, directory } = req.query;
     console.log({ slug, id, directory }); // In production, these are not accessible. They ARE accessible in development.

     if (!slug || !id || !directory) {
        return res.status(401).json({ slug, id, directory });
     }

     ...
}
```

When navigating to `https://mywebsite.com/api/preview?slug=preview-test&id=test-id&directory=test-directory`, query params aren't accessible.

When returning: 

```javascript 
res.json({
     method: req.method,
     url: req.url,
     slug,
     id,
     directory
});
```
the results is: 

`{"method":"GET","url":"/api/preview","slug":null,"id":null,"directory":null}`

However, the same code in development (localhost) results in:

`{"method":"GET","url":"/api/preview?slug=preview-test&id=partner-page&directory=partners","slug":"preview-test","id":"partner-page","directory":"partners"}`

## System information

- OS: macOS 10.15.7 
- Browser: Chrome, Safari, Firefox...
- Version of Next.js: 10.0.1 & 10.0.5-canary.10
- Version of Node.js: v12.20.0
- Deployment: AWS

**Comment by AlexandraKlein** [comment] 2021-01-13 01:43
I'm finding this to be the case with `useRouter()`'s `query` as well, even with a `useEffect` to wait for hydration. Again, this works in development, but not in prod on a server.

**Comment by ijjk** [comment] 2021-01-27 20:55
Hi, we are not able to reproduce this with `next start` or when deploying on Vercel so this is most likely related to your custom deployment infrastructure. I'm going to close this since it doesn't appear to be an issue in Next.js itself. 

<details>

<summary>Example with `next start`</summary>

https://user-images.githubusercontent.com/22380829/106052746-9331f480-60af-11eb-85ad-7b19d9ca1588.mp4

</details>

<details>

<summary>Example with Vercel</summary>

https://user-images.githubusercontent.com/22380829/106052754-962ce500-60af-11eb-85ed-9108763547e0.mp4

</details>

**Closed by ijjk** 2021-01-27 20:55 UTC
Labels: kind: bug

**Comment by AlexandraKlein** [comment] 2021-04-27 21:07
Thank @ijjk! Definitely working when deployed on Vercel!

**Comment by balazsorban44** [comment] 2022-01-28 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
