### ISSUE TITLE
Env variables with special characters

### ISSUE THREAD

**Issue by Deepak13245** [vercel/next.js#14985] opened 2020-07-08 16:30 UTC
# Bug report

## Describe the bug

Env variables having special characters are not being loaded from .env.local

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. In .env.local add a variable with special characters. `NEXT_PUBLIC_TEST="abcd$ef"`
2. In next.config.js add a log. `console.log(process.env.NEXT_PUBLIC_TEST)`
3. The log will print only `abcd`

## Expected behavior
It should load complete value `abcd$ef`

## System information

- OS: macOS
- Version of Next.js: 9.4.4
- Version of Node.js: 12.9.1

**Comment by ijjk** [comment] 2020-07-08 16:38
Hi, this should be fixed in Next.js >= `v9.4.5-canary.26` specifically [this PR](https://github.com/vercel/next.js/pull/14750). Can you try upgrading and let us know if it is resolved with this version?

**Comment by Tudes** [comment] 2020-07-08 17:08
Hi, @Deepak13245 the issue is not with NextJS, but more with how dotenv works. 

You need to escape your `$` e.g. `\$`. Please see https://github.com/bkeepers/dotenv/issues/214

**Comment by Tudes** [comment] 2020-07-08 17:20
Hi, @Deepak13245 I'm not sure if the issue is with NextJS per se

But with dotenv previously you'd have to escape `$` sign. You'll have to do the same here e.g. `abcd\$ef`

**Comment by Deepak13245** [comment] 2020-07-08 17:25
Got it ! Thanks @Tudes

**Closed** 2020-07-08 17:25 UTC

**Comment by balazsorban44** [comment] 2022-01-29 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
