### ISSUE TITLE
Wildcard headers behave inconsistently with locales or trailingSlash

### ISSUE THREAD

**Issue by jvarho** [vercel/next.js#25243] opened 2021-05-19 05:36 UTC
### What version of Next.js are you using?

10.2.0, 10.2.1-canary.11

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

ubuntu

### How are you deploying your application?

next start

### Describe the Bug

Adding a header for "/:path*" does not apply to the root, i.e. opening "/" gives you a page without the header. Unless you use locales, in which case it does.

Adding a header for "/test/:path*" applies to /test when trailingSlash is false, but not when trailingSlash is true.

### Expected Behavior

It should behave consistently and the docs should say whether "/test/:path*" matches "/test" or not.

### To Reproduce

1. Basic app from e.g. create-next-app
2. next.config.js:
     ```
    module.exports = {
      // i18n: {defaultLocale: 'en', locales: ['en']},
      async headers() {
        return [
          {
            source: '/:path*',
            headers: [{key: 'x-custom', value: 'custom'}]
          }
        ]
      }
    }
    ```
3. next build, next start
4. Open "http://localhost:3000" and look at the headers (no x-custom).
5. Uncomment i18n, rebuild and retest (x-custom is now set).

**Comment by apuyou** [comment] 2021-08-06 09:29
I can confirm that I am facing the same issue with the latest version of Next.js. Enabling i18n supports prevents using a source path that matches the root path when trailing slashes are disabled.

I have identified that the issue is due to a special handling of the root path [here](https://github.com/vercel/next.js/blob/c6a08f51b1ea0f0debdc7dbf1aa4192b3d67009d/packages/next/lib/load-custom-routes.ts#L551).

I'll send a PR for this if I can figure out a fix.

For now, the workaround is to include an extra entry if you need the root path to be matched. This will work for /, but also /en.

```
module.exports = {
 i18n: {defaultLocale: 'en', locales: ['en']},
 async headers() {
   return [
     {
       source: '/',
       headers: [{key: 'x-custom', value: 'custom'}]
     },
     {
       source: '/:path*',
       headers: [{key: 'x-custom', value: 'custom'}]
     },
   ]
 }
}
```

**Comment by ijjk** [comment] 2021-09-21 02:41
Hi, this appears to be duplicate of https://github.com/vercel/next.js/issues/14930 so I'm gonna close this in favor of that

**Closed by ijjk** 2021-09-21 02:41 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
