### ISSUE TITLE
Create Next App template does not look correct in IE11

### ISSUE THREAD

**Issue by yeldiRium** [vercel/next.js#21324] opened 2021-01-19 11:17 UTC
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

14.14.0

**What browser are you using?**

IE11

**What operating system are you using?**

Windows 10

**How are you deploying your application?**

next start

**Describe the Bug**

The start page of next.js does not render properly.

See image below.

**Expected Behavior**

It should render the same as in other browsers, since next.js claims it ["supports IE11 and all modern browsers (Edge, Firefox, Chrome, Safari, Opera, et al) with no required configuration."](https://nextjs.org/docs/basic-features/supported-browsers-features).

**To Reproduce**

Follow [these instructions](https://dev.to/filippofonseca/how-to-set-up-a-next-js-project-with-typescript-and-react-576h) to set up a next.js application with TypeScript.

Then, since [the development mode of next.js does not work in IE11 anyway](https://github.com/vercel/next.js/issues/13231), first run `npm run build` to build the production version and then serve it with `npm run start`.

![The broken next.js start page.](https://user-images.githubusercontent.com/11889637/105027639-4c5d5280-5a50-11eb-9fa7-db12961811b1.png)

**Comment by leerob** [comment] 2021-01-20 21:22
Thanks for reporting! I marked this as a good first issue is someone wants to debug [which styles are breaking here](https://github.com/vercel/next.js/blob/canary/packages/create-next-app/templates/default/styles/Home.module.css).

**Comment by moh12594** [comment] 2021-01-21 16:57
Hello ! I could take it !

**Comment by Itsaadarsh** [comment] 2021-01-25 00:07
Hello there, I'm on it.

**Comment by MonstraG** [comment] 2021-04-03 13:03
Seems like there are two issues: 
1) footer is too high
2) cards don't fill width

At least first, but most likely both are due to https://stackoverflow.com/questions/28627879/flexbox-not-filling-height-in-ie11

**Comment by Hanaffi** [comment] 2021-04-19 18:26
@leerob Hey Lee, Can you assign this to me?

**Comment by leerob** [comment] 2021-04-19 20:58
Sure, thank you @Hanaffi 🙏

**Closed** 2021-04-20 19:18 UTC
Labels: good first issue, template: bug

**Comment by balazsorban44** [comment] 2022-01-28 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
