### ISSUE TITLE
Automatic WebFont Optimization does not work

### ISSUE THREAD

**Issue by Co9xs** [vercel/next.js#24781] opened 2021-05-04 11:33 UTC
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Chrome

### What operating system are you using?

macOS BigSur

### How are you deploying your application?

Vercel

### Describe the Bug

The font style is not inlined even though I added a link to`_document.tsx` in the following format.
(I'm sure using the `Head` component exported from `next/document`)

```jsx
<Html lang="ja">
  <Head>
    <meta charSet="utf-8" />
    <link  href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP" rel="stylesheet" />
  </Head>
  <body>
    <Main />
    <NextScript />
  </body>
</Html>
```
I forked next.js to use a local next.js, and the same thing happened.

When I run 'next build', `.next/server/font-manifest.json` will be generated, but its contents will be empty.
This probably happens only with certain fonts (maybe Japanese font?).

Also, if you run 'yarn dev' after 'yarn build', regardless of whether the font is Japanese or not, the `.next/server/font-manifest. json` was disappeared, is this a problem?

I found this issue([#19159](https://github.com/vercel/next.js/issues/19159)), but it was already closed and did not solve the problem.

### Expected Behavior

The tag is transformed as expected
- link href property is replaced with data-href of the same value
- style tag is created with the same data-href key/value
- style tag contains an inlined font definition

The .next/server/font-manifest.json contains font definitions as fetched from https://fonts.googleapis.com/css...

### To Reproduce

1. Build and start a server from my minimal repo:
```
git clone https://github.com/Co9xs/next-automatic-webfont-optimization-sample.git
cd next-automatic-webfont-optimization-sample
yarn 
yarn build
yarn dev
```

2. Open http://localhost:3000/
3. Inspect the <head> of the document
4. Inspect the built .next/server/font-manifest.json file

**Comment by janicklas-ralph** [comment] 2021-05-06 20:36
Thanks for reporting this. I will have a look into it.

**Comment by aresrioja10** [comment] 2021-05-14 07:33
Same issue here. Any update? @janicklas-ralph

**Comment by marcelobaez** [comment] 2021-06-14 19:32
The same happens to me. Neither using it on _app or _document works here.
Node version: 14.16.1
Nextjs version: 10.2.3

**Comment by pixelass** [comment] 2021-06-16 06:33
still an issue with: `"next": "^11.0.0"`

**Comment by pixelass** [comment] 2021-06-16 07:00
Note for OP: @Co9xs 

The commands you mentioned don't optimize fonts: `next dev`

```sh
yarn 
yarn build
yarn dev # <-- this starts a dev server and ignores the next build command
```

However it is also an issue with `next start`

```sh
yarn 
yarn build
yarn start
```

This is the output we see:

```html

<head>
<link rel="stylesheet" data-href="https://fonts.googleapis.com/css2?family=Poppins">
<!-- ... -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins">
</head>
```

The link is transformed and prepended in the head but the fonts never get inlined and therefore no optimization has been done. Actually the DOM gets larger instead, since we now have an extra "useless" `<link rel="stylesheet" data-href="https://fonts.googleapis.com/css2?family=Poppins">`

**Comment by pixelass** [comment] 2021-06-16 15:13
For us this issue happened when loading additional babel presets

FAILS

```js
// Result
// <head>
//   <link rel="stylesheet" data-href="https://fonts.googleapis.com/css2?family=Poppins">
//   <!-- ... -->
//   <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins">
// </head>
module.exports = {
	presets: ["next/babel", "@babel/preset-env", "@babel/preset-typescript", "@babel/preset-react"],
	plugins: [
		[
			"@emotion/babel-plugin",
			{
				sourceMap: true,
				autoLabel: "dev-only",
				labelFormat: "[local]",
				cssPropOptimization: true,
			},
		],
	],
};

```

DOES NOT FAIL
```js
// Result
// <head>
//   <link rel="stylesheet" data-href="https://fonts.googleapis.com/css2?family=Poppins">
//   <!-- ... -->
//   <style data-href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&amp;display=swap">/* ... */</style>
// </head>
module.exports = {
	presets: ["next/babel"],
	plugins: [
		[
			"@emotion/babel-plugin",
			{
				sourceMap: true,
				autoLabel: "dev-only",
				labelFormat: "[local]",
				cssPropOptimization: true,
			},
		],
	],
};
```

**Comment by timneutkens** [comment] 2021-06-16 16:15
> For us this issue happened when loading additional babel presets
> 
> FAILS
> 
> ```js
> // Result
> // <head>
> //   <link rel="stylesheet" data-href="https://fonts.googleapis.com/css2?family=Poppins">
> //   
> //   <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins">
> // </head>
> module.exports = {
> 	presets: ["next/babel", "@babel/preset-env", "@babel/preset-typescript", "@babel/preset-react"],
> 	plugins: [
> 		[
> 			"@emotion/babel-plugin",
> 			{
> 				sourceMap: true,
> 				autoLabel: "dev-only",
> 				labelFormat: "[local]",
> 				cssPropOptimization: true,
> 			},
> 		],
> 	],
> };
> ```
> 
> WORKS
> 
> ```js
> // Result
> // <head>
> //   <link rel="stylesheet" data-href="https://fonts.googleapis.com/css2?family=Poppins">
> //   
> //   <style data-href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&amp;display=swap">/* ... */</style>
> // </head>
> module.exports = {
> 	presets: ["next/babel",  "@babel/preset-env", ],
> 	plugins: [
> 		[
> 			"@emotion/babel-plugin",
> 			{
> 				sourceMap: true,
> 				autoLabel: "dev-only",
> 				labelFormat: "[local]",
> 				cssPropOptimization: true,
> 			},
> 		],
> 	],
> };
> ```

`presets: ["next/babel"]` is only needed for the example posted as all presets referenced are already used by `next/babel`. Adding them on top of `next/babel` will have a negative effect on performance and bundle size.

**Comment by pixelass** [comment] 2021-06-16 18:20
@timneutkens thanks for the explanation. We carried/copied this config through several repos and versions of nextjs. Bad habits.
We kept `@babel/preset-env` since we add a custom config to that plugin (no issues) but looking at the docs: (https://nextjs.org/docs/advanced-features/customizing-babel-config) we will now add it to `next/babel`

```json
{
  "presets": [
    [
      "next/babel",
      {
        "preset-env": {},
      }
    ]
  ],
  "plugins": []
}
```

**Comment by RyKilleen** [comment] 2021-09-09 13:41
This appears to still be an issue, with real impact on mobile lighthouse scores. Anything we can do to help support it being fixed?

**Comment by RyKilleen** [comment] 2021-09-09 14:37
It appears our issue is directly related to our .babelrc as well, so it's safe to say that if you're having font optimization issues: start there.

In our case, we were including the following plugin, which is already a part of `babel/preset-env`, which is already part of the next/babel preset.

``` 
[
    "@babel/plugin-transform-react-jsx",
    {
        "pragmaFrag": "React.Fragment"
    }
 ]
```

**Comment by dasblitz** [comment] 2021-10-05 08:25
Ran into this issue as well using "next": "11.0.1". 

I cleaned up my .babelrc and .eslintrc files according to the documentation:

.babelrc: https://nextjs.org/docs/advanced-features/customizing-babel-config
.eslintrc: https://nextjs.org/docs/basic-features/eslint

Unfortunately the font still wasn't included correctly. Turned out that for me the culprit was a key prop which I added because when running `yarn dev` I got the following warning:
```
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at script
    at Head (webpack-internal:///./node_modules/next/dist/pages/_document.js:252:5)
```

```javascript
class MyDocument extends Document {
  render(): JSX.Element {
    return (
      <Html>
        <Head>
          {/* This does not work, notice the key prop. Removing it fixed the issue for me */}
          <link
            key="does-not-work"
            href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap"
            rel="stylesheet"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```

Removing the `key` prop from the `<link>` element added the inline style element:

```html
<style data-href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&amp;display=swap">@font-face{font-family:'Poppins';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLCz7V1g.woff) format('woff')}@font-face{font-family:'Poppins';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLCz7Z11lFd2JQEl8qw.woff2) format('woff2');unicode-range:U+0900-097F,U+1CD0-1CF6,U+1CF8-1CF9,U+200C-200D,U+20A8,U+20B9,U+25CC,U+A830-A839,U+A8E0-A8FB}@font-face{font-family:'Poppins';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLCz7Z1JlFd2JQEl8qw.woff2) format('woff2');unicode-range:U+0100-024F,U+0259,U+1E00-1EFF,U+2020,U+20A0-20AB,U+20AD-20CF,U+2113,U+2C60-2C7F,U+A720-A7FF}@font-face{font-family:'Poppins';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLCz7Z1xlFd2JQEk.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}</style>
```

The link element itself is also added to the `<head>` of the document btw, I don't know if that is supposed to happen?

```html
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&amp;display=swap" rel="stylesheet">
```

**Comment by drpancake** [comment] 2021-12-20 08:25
> Unfortunately the font still wasn't included correctly. Turned out that for me the culprit was a key prop which I added because when running `yarn dev` I got the following warning:

Thank you. Removing the `key` prop fixed it for me too.

**Comment by caleb531** [comment] 2022-01-23 05:00
For me, I found that my `getInitialProps` export in my `_app.tsx` was causing the Automatic Font Optimization conversion to fail.

Removing the `getInitialProps` export immediately fixed the inlining of the Google Font stylesheet.

Hope this helps someone!

**Comment by stephanvane** [comment] 2022-02-11 15:18
Same problem here. `getInitialProps` seems to be causing the issue. Anywhere, not just in the `_app.tsx` page. (only in production, after running 'build/start'

**To reproduce on a new project:**

`pages/_document.jsx`
```jsx
import { Head, Html, Main, NextScript } from "next/document";

const Document = () => {
  return (
    <Html>
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
};

export default Document;
```

---

`pages/working.jsx`
```jsx
const WorkingPage = () => <>Working font here</>;

export default WorkingPage;
```
This page works as expected, it contains the html:
```html
<style data-href="https://fonts.googleapis.com/css2?family=Inter&amp;display=swap">@font-face{font-family:'Inter';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfMZs.woff) format('woff')}@font-face{font-family:'Inter';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZJhjp-Ek-_EeAmM.woff) format('woff');unicode-range:U+0460-052F,U+1C80-1C88,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F}@font-face{font-family:'Inter';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZthjp-Ek-_EeAmM.woff) format('woff');unicode-range:U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116}@font-face{font-family:'Inter';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZNhjp-Ek-_EeAmM.woff) format('woff');unicode-range:U+1F00-1FFF}@font-face{font-family:'Inter';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZxhjp-Ek-_EeAmM.woff) format('woff');unicode-range:U+0370-03FF}@font-face{font-family:'Inter';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZBhjp-Ek-_EeAmM.woff) format('woff');unicode-range:U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+1EA0-1EF9,U+20AB}@font-face{font-family:'Inter';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZFhjp-Ek-_EeAmM.woff) format('woff');unicode-range:U+0100-024F,U+0259,U+1E00-1EFF,U+2020,U+20A0-20AB,U+20AD-20CF,U+2113,U+2C60-2C7F,U+A720-A7FF}@font-face{font-family:'Inter';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/inter/v7/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hjp-Ek-_EeA.woff) format('woff');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}</style>
```

---

`pages/broken.jsx`
```jsx
const BrokenPage = () => <>Broken font here</>;

export default BrokenPage;

export async function getServerSideProps(context) {
  return {
    props: {},
  };
}
```

This page doesn't load the font at all. The html contains:
```html
<link rel="stylesheet" data-href="https://fonts.googleapis.com/css2?family=Inter&amp;display=swap"/>
```

I'm surprised there are not that many people experiencing this problem. I thought that a web-font in combination with `getServerSideProps` would be a pretty standard scenario :)

**Comment by jlabedo** [comment] 2022-02-21 09:50
Same problem here: the font does not get loaded and the html contains:
```html
<link rel="stylesheet" data-href="https://fonts.googleapis.com/css2?family=Inter&amp;display=swap"/>
```

I am facing this issue only on pages with a **dynamic route**:
- `/pages/test.tsx` will load the font as expected but
- `/pages/[slug].tsx` will not load the font.

Both pages **do not** have any `get***Props` export.

**Comment by saheljalal** [comment] 2022-03-12 17:47
Running into the same issue, the feature doesn't seem to be working as documented. Please take a look and help resolve.

**Comment by samcarton** [comment] 2022-03-17 06:10
We're having the same issue here. The workaround is to [disable font optimization](https://nextjs.org/docs/basic-features/font-optimization#disabling-optimization) to get any google fonts to work in production build

```
// next.config.js

module.exports = {
  optimizeFonts: false,
}
```

**Comment by haldunanil** [comment] 2022-03-29 20:07
I'm also having the same issue on Next 12.1.2.

**Comment by muhmushtaha** [comment] 2022-03-31 10:12
I'm also having the same issue on next@12.1.0

**Comment by twankruiswijk** [comment] 2022-04-05 10:45
Okay, I found what is causing the confusion, or maybe it's a bug? Not sure. Maybe @timneutkens can tell us more about it?

So in the documentation of the [font-optimalization](https://nextjs.org/docs/basic-features/font-optimization) they tell you to create a `_document` file. If you go to the `_document` documentation, they give you the following function example:

```
import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html>
      <Head />
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
```

However, if you look closely at the font optimization documentation, you see that you should probably be using the class component version:

```
import Document, { Html, Head, Main, NextScript } from 'next/document'

class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head>
          <link
            href="https://fonts.googleapis.com/css2?family=Inter&display=optional"
            rel="stylesheet"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument
```

After updating my document to a class component, everything worked as expected. If this is the way it is, the documentation of the font optimization might benefit from a warning or explanation about this.

**Comment by haldunanil** [comment] 2022-04-05 17:52
Unfortunately, @twankruiswijk 's approach didn't work for me as my Document component is already a class. For reference, it doesn't work with this:

```ts
import React from "react";
import Document, { Html, Head, Main, NextScript } from "next/document";
import { ServerStyleSheet } from "styled-components";
import ServerStyleSheets from "@mui/styles/ServerStyleSheets";

class MyDocument extends Document {
  static async getInitialProps(
    // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
    ctx
  ): Promise<{
    styles: JSX.Element;
    html: string;
    head?: JSX.Element[];
  }> {
    const styledComponentsSheet = new ServerStyleSheet();
    const materialSheets = new ServerStyleSheets();
    const originalRenderPage = ctx.renderPage;

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: (App) => (props) =>
            styledComponentsSheet.collectStyles(
              materialSheets.collect(<App {...props} />)
            ),
        });

      const initialProps = await Document.getInitialProps(ctx);

      return {
        ...initialProps,
        styles: (
          <>
            {initialProps.styles}
            {materialSheets.getStyleElement()}
            {styledComponentsSheet.getStyleElement()}
          </>
        ),
      } as any;
    } finally {
      styledComponentsSheet.seal();
    }
  }

  render(): React.ReactElement {
    return (
      <Html lang="en">
        <Head>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin=""
          />
          <link
            href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@300;400;500;700&display=swap"
            rel="stylesheet"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```

**Comment by janicklas-ralph** [comment] 2022-04-05 18:18
Does it work sometimes, or it doesn't inline always? Do you see any errors on the console during `next build`?
I'm having a hard time reproducing the bug with the info provided. Any additional info is appreciated.

**Comment by haldunanil** [comment] 2022-04-05 21:33
Not sure if it was specifically addressed, but upgrading to Next.js 12.1.4 seemed to fix it!

**Comment by bouncycat** [comment] 2022-04-07 22:52
> Unfortunately, @twankruiswijk 's approach didn't work for me as my Document component is already a class. For reference, it doesn't work with this:
> 
> ```ts
> import React from "react";
> import Document, { Html, Head, Main, NextScript } from "next/document";
> import { ServerStyleSheet } from "styled-components";
> import ServerStyleSheets from "@mui/styles/ServerStyleSheets";
> 
> class MyDocument extends Document {
>   static async getInitialProps(
>     // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
>     ctx
>   ): Promise<{
>     styles: JSX.Element;
>     html: string;
>     head?: JSX.Element[];
>   }> {
>     const styledComponentsSheet = new ServerStyleSheet();
>     const materialSheets = new ServerStyleSheets();
>     const originalRenderPage = ctx.renderPage;
> 
>     try {
>       ctx.renderPage = () =>
>         originalRenderPage({
>           enhanceApp: (App) => (props) =>
>             styledComponentsSheet.collectStyles(
>               materialSheets.collect(<App {...props} />)
>             ),
>         });
> 
>       const initialProps = await Document.getInitialProps(ctx);
> 
>       return {
>         ...initialProps,
>         styles: (
>           <>
>             {initialProps.styles}
>             {materialSheets.getStyleElement()}
>             {styledComponentsSheet.getStyleElement()}
>           </>
>         ),
>       } as any;
>     } finally {
>       styledComponentsSheet.seal();
>     }
>   }
> 
>   render(): React.ReactElement {
>     return (
>       <Html lang="en">
>         <Head>
>           <link rel="preconnect" href="https://fonts.googleapis.com" />
>           <link
>             rel="preconnect"
>             href="https://fonts.gstatic.com"
>             crossOrigin=""
>           />
>           <link
>             href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@300;400;500;700&display=swap"
>             rel="stylesheet"
>           />
>         </Head>
>         <body>
>           <Main />
>           <NextScript />
>         </body>
>       </Html>
>     );
>   }
> }
> 
> export default MyDocument;
> ```

I am encountering exactly the same problem with using Class and `styled-component` together inside `getInitialProps`, also unfortunately upgrading to `next@12.1.4` does not fix the problem

**Comment by MakChan** [comment] 2022-04-08 07:52
> Does it work sometimes, or it doesn't inline always? Do you see any errors on the console during `next build`? I'm having a hard time reproducing the bug with the info provided. Any additional info is appreciated.

No, it never inlines, and there are no errors or warnings during `next build`.

I'm also using a Class component and `next@12.1.4`. The document page itself doesn't have a `getInitialProps` but individual pages do have `getServerSideProps`.

**Comment by janicklas-ralph** [comment] 2022-04-25 18:19
Thanks. 
I tried with your version and I still haven't been able to recreate this issue. Can you check if there is a `font-manifest.json` in your build folder, and share the contents. 

Also, what version of react are you using?

**Comment by alex-statsig** [comment] 2022-05-13 17:46
This seemed to start happening to me after upgrading to react 18. Ended up disabling fontOptimization to fix for now

**Comment by baptisteArno** [comment] 2022-05-14 15:12
I'm experiencing the same issue on [Typebot](https://github.com/baptisteArno/typebot-io) after upgrading packages (React 18 and Next.js 12.1.6)

**Comment by zbauman3** [comment] 2022-05-20 16:35
The most progress I've made is that it seems my elements are getting filtered out [here](https://github.com/vercel/next.js/blob/0468a566041bd8f9a5e4a0b47d92a3e0796a3998/packages/next/build/webpack/plugins/font-stylesheet-gathering-plugin.ts#L87). It seems that [isNodeCreatingLinkElement](https://github.com/vercel/next.js/blob/0468a566041bd8f9a5e4a0b47d92a3e0796a3998/packages/next/build/webpack/plugins/font-stylesheet-gathering-plugin.ts#L244) may be causing some of the issues people are having above, although I'm not sure that it is my issue exactly. I'll have more time to research this weekend.


I hope this helps some people track down their issues!

**Comment by aoshi321** [comment] 2022-05-24 12:36
Any update in regards to this issue Im still experiencing this with React 18 and the latest version of next?

**Comment by brychter-merix** [comment] 2022-05-31 11:02
Same issue: Next 12.1.6 and React 18.1.0. Custom `_document` is a React Class Component.

**Comment by thomaswang** [comment] 2022-06-09 17:16
```
<NextHead>
  <link // eslint-disable-line
    href="https://fonts.googleapis.com/css2?family=Inter:wght@400..800&display=swap"
    rel="stylesheet"
  />
</NextHead>
```

^ Currently using this hotfix: adding the `<link>` tag to your Next.js page with `getServerSideProps`

**Comment by xereda** [comment] 2022-06-15 22:11
> ```
> const Page = () => (
>   <>
>     <NextHead>
>       <link // eslint-disable-line
>         href="https://fonts.googleapis.com/css2?family=Inter:wght@400..800&display=swap"
>         rel="stylesheet"
>       />
>     </NextHead>
>   </>
> )
> 
> export async function getServerSideProps(context) {
>   return {
>     props: {},
>   };
> }
> 
> export default Page;
> ```
> 
> ^ Currently using this hotfix: adding the `<link>` tag to your Next.js page with `getServerSideProps`

Doesn't it make more sense to turn off the functionality?

**Comment by tomchentw** [comment] 2022-06-30 04:43
I have appkied @twankruiswijk 's solution. Mine is a class component which only has `render()` defined.

**IT WORKS**!!!

My route is `/[...slug]` with `getServerSideProps`.

**Comment by JuniorTour** [comment] 2022-07-05 07:49
This issue seems to have been fixed by `"next": "12.2.0"`. 

I just test the case above with:
- `getServerSideProps`
- `<Head><link></Head>`

**Comment by ahmedB7r** [comment] 2022-07-09 23:20
i have same issue with writing the link in this dynamic form 
 ```  
<link href={`https://fonts.googleapis.com/css2?family=${fontFamily}:wght@500;700&display=optional`}
         rel="stylesheet"
            />
```

and just get this  
```
<link rel="stylesheet" data-href="https://fonts.googleapis.com/css2?family=Cairo:wght@500;700&amp;display=optional">
```
work normally if write the href without any variables

maybe help

**Comment by xereda** [comment] 2022-07-22 11:39
NEWS! It was resolved with the Next.js update

**Comment by ahmedB7r** [comment] 2022-08-21 14:48
> i have same issue with writing the link in this dynamic form
> 
> ```
> <link href={`https://fonts.googleapis.com/css2?family=${fontFamily}:wght@500;700&display=optional`}
>         rel="stylesheet"
>            />
> ```
> 
> and just get this
> 
> ```
> <link rel="stylesheet" data-href="https://fonts.googleapis.com/css2?family=Cairo:wght@500;700&amp;display=optional">
> ```
> 
> work normally if write the href without any variables
> 
> maybe help

my case still not working

**Comment by TrejoCode** [comment] 2022-10-06 01:42
Same error, doesn't load on 12.3.1

**Comment by 0xmax** [comment] 2022-10-12 08:28
Same here, any updates on this?

**Comment by kfranqueiro** [comment] 2023-03-21 22:02
I also ran into this issue of Next 12 never properly inlining google font resources, even when it's nothing but a `<link rel="stylesheet" href="...">` (i.e. no variables or spreads involved).

I dug around for a while and was able to get it working with this patch. I won't pretend to understand the details of the AST, but apparently the nodes of interest were neither `_jsx` nor `__jsx`, but just plain `jsx` for me. (Next 12.3.4, React 17.0.2)

```diff
diff --git a/node_modules/next/dist/build/webpack/plugins/font-stylesheet-gathering-plugin.js b/node_modules/next/dist/build/webpack/plugins/font-stylesheet-gathering-plugin.js
index 1ebc70a..d9050fe 100644
--- a/node_modules/next/dist/build/webpack/plugins/font-stylesheet-gathering-plugin.js
+++ b/node_modules/next/dist/build/webpack/plugins/font-stylesheet-gathering-plugin.js
@@ -76,7 +76,7 @@ function isNodeCreatingLinkElement(node) {
     }
     // React has pragma: _jsx.
     // Next has pragma: __jsx.
-    return (callee.name === "_jsx" || callee.name === "__jsx") && componentNode.value === "link";
+    return /^_*jsx$/.test(callee.name) && componentNode.value === "link";
 }
 class FontStylesheetGatheringPlugin {
     gatheredStylesheets = [];
@@ -109,7 +109,7 @@ class FontStylesheetGatheringPlugin {
                         return;
                     }
                     let result;
-                    if (node.name === "_jsx" || node.name === "__jsx") {
+                    if (/^_*jsx$/.test(node.name)) {
                         result = new _webpack.BasicEvaluatedExpression();
                         // @ts-ignore
                         result.setRange(node.range);
@@ -153,6 +153,7 @@ class FontStylesheetGatheringPlugin {
                     }
                 };
                 // React JSX transform:
+                parser.hooks.call.for("jsx").tap(this.constructor.name, jsxNodeHandler);
                 parser.hooks.call.for("_jsx").tap(this.constructor.name, jsxNodeHandler);
                 // Next.js JSX transform:
                 parser.hooks.call.for("__jsx").tap(this.constructor.name, jsxNodeHandler);
```

**Comment by timneutkens** [comment] 2023-03-22 13:20
Going to close this issue as automatic font optimization was superseded by `next/font`: https://nextjs.org/docs/basic-features/font-optimization

**Closed by timneutkens** 2023-03-22 13:20 UTC
Labels: kind: bug, area: Font Optimization
