### ISSUE TITLE
Rewrite fallback isn't executed when getStaticProps returns notFound

### ISSUE THREAD

**Issue by vetalstar** [vercel/next.js#30725] opened 2021-11-01 09:20 UTC
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

npm run dev

### Describe the Bug

next.config.js
```
async rewrites() {
        return {
            afterFiles: [
                {
                    source: '/:path(.*)',
                    has: [
                        {
                            type: 'host',
                            value: '(?<host>.*)',
                        },
                    ],
                    destination: '/_hosts/:host/:path*',
                },
            ],
            fallback: [
                {
                    source: '/:path(.*)',
                    has: [
                        {
                            type: 'host',
                            value: '(?<host>.*)',
                        },
                    ],
                    destination: '/_hosts/:host/404',
                },
            ],
        }
    },
```

_hosts/[host]/catalog/[category].tsx
```
export const getStaticProps: GetStaticProps = async ({params}) => {
    const data: PropsQueryResponse = await request(process.env.API_URL, propsQuery, variables)

    if (!data.category) {
        return {
            notFound: true,
        }
    }

    return {
        props: {
            ...data,
        },
        revalidate: 60,
    }
}

export const getStaticPaths: GetStaticPaths = async () => {
    const data: PathsQueryResponse = await request(process.env.API_URL, pathsQuery)

    return {
        paths: [
           { params: { ... } }
        ],
        fallback: 'blocking',
    }
}
      
```

Also I have custom 404 page
_hosts/[host]/404.tsx

When I return notFound, fallback rewrites aren't executed. So I can't rewrite pages with dynamic routes to the custom 404 page

### Expected Behavior

Fallback rewrites should be executed when dynamic routes are not found

### To Reproduce

N/A

**Comment by ijjk** [comment] 2021-11-08 16:48
Hi, rewrites are not meant to be triggered when returning `notFound: true` currently. I'm going to close this as a duplicate of https://github.com/vercel/next.js/issues/26883

**Closed by ijjk** 2021-11-08 16:48 UTC
Labels: template: bug

**Comment by vetalstar** [comment] 2021-11-08 17:38
@ijjk is there any way to set a custom path to 404 page? As I had showed I have 404 page in the subfolder: _hosts/[host]/404.tsx

**Comment by ijjk** [comment] 2021-11-08 17:40
Nested 404 pages are not currently available, you can conditionally render on the client based on the props returned from `getStaticProps` instead though.

**Comment by vetalstar** [comment] 2021-11-08 17:42
I see. I've done so. Thank you

**Comment by balazsorban44** [comment] 2022-01-27 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
