### ISSUE TITLE
error - ESLint must be installed: yarn add --dev eslint

### ISSUE THREAD

**Issue by skhaz** [vercel/next.js#30182] opened 2021-10-22 16:50 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.18.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows WSL2

### How are you deploying your application?

Vercel

### Describe the Bug

I just created a new project using

```
npx create-next-app@latest --ts
```

And when I run

```
npm run lint
```

I got the error:

```
> next lint

info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
error - ESLint must be installed: yarn add --dev eslint
```

### Expected Behavior

Ran without error

### To Reproduce

```bash
npx create-next-app@latest --ts
cd app
npm install
npm run lint
```

**Comment by sicarius97** [comment] 2021-10-23 01:51
#29770 Originally referenced this issue, and I saw that there was a PR opened that was intended to fix the issue here  #29837. Unfortunately there still appears to be an issue when using yarn create next-app specifically. It may be fixed with create-next-app, but I haven't confirmed that yet

**Comment by monicalabbao** [comment] 2021-11-09 08:59
I also experience this while using `yarn` instead of `npx` and `npm`

`npx create-next-app@latest --ts`
`cd app`
`yarn lint`

But the project runs fine (`yarn dev`)

**Comment by jcarpe** [comment] 2021-11-10 19:47
Likewise... I am having this issue but with an existing project. We recently upgraded our nextJS version and since linting was a new feature we could take advantage of, we gave it a shot! I _was_ able to get things working with the following versions:

```
"next": "^11.1.2"
"eslint": "7.32.0"
```

**Comment by timneutkens** [comment] 2021-11-18 12:00
This has been fixed on https://github.com/vercel/next.js/releases/tag/v12.0.5-canary.0, will be out on stable soon!

**Closed** 2021-11-18 12:00 UTC
Labels: template: bug, area: ESLint

**Comment by Solaimanx** [comment] 2022-01-19 16:32
> Likewise... I am having this issue but with an existing project. We recently upgraded our nextJS version and since linting was a new feature we could take advantage of, we gave it a shot! I _was_ able to get things working with the following versions:
> 
> ```
> "next": "^11.1.2"
> "eslint": "7.32.0"
> ```

Thanks . This version also working for me.
