### ISSUE TITLE
Env variables from `.env*` file don't expose to `next.config.*` anymore

### ISSUE THREAD

**Issue by fliptheweb** [vercel/next.js#22881] opened 2021-03-08 17:43 UTC
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

14.7.0

### What browser are you using?

any

### What operating system are you using?

macOS

### How are you deploying your application?

local, codesandbox

### Describe the Bug

Env variables don't expose to `next.config.js` and not available w/o manual using `dotenv` package.
Seems like after '10.0.8' nextjs starts to use `next-env` after `next.config` loaded.

### Expected Behavior

We should be able to use Env variables in `next.config`, `webpack`, `plugins` configurations.

### To Reproduce

Sandbox with 10.0.8 and the behavior:
https://codesandbox.io/s/nextjs-1008-process-env-bug-wmwkn
in terminal
```sh
check VAR env: undefined
check NEXT_PUBLIC_VAR env: undefined
warn  - Detected next.config.js, no exported configuration found.https://err.sh/vercel/next.js/empty-configuration
info  - Loaded env from /sandbox/.env
```

Sandbox with 10.0.7 w/o:
https://codesandbox.io/s/nextjs-1007-process-env-nvnnh
in terminal
```sh
Loaded env from /sandbox/.env
check VAR env: FOO
check NEXT_PUBLIC_VAR env: BAR
```

**Comment by matamatanot** [comment] 2021-03-08 20:08
Check #22879.
You can try out https://github.com/vercel/next.js/releases/tag/v10.0.9-canary.2 .

**Comment by ijjk** [comment] 2021-03-08 20:19
Closing as a duplicate of https://github.com/vercel/next.js/issues/22811 per above

**Closed by ijjk** 2021-03-08 20:19 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 15:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
