### ISSUE TITLE
Link Support other than English

### ISSUE THREAD

**Issue by rajatdhoot123** [vercel/next.js#12780] opened 2020-05-12 11:30 UTC
# Feature request
Is it possible to support the URL in other than the English language like
http://kukufm.com/हिंदी
Currently, it is throwing 404 created page with the same name (हिंदी).

## Is your feature request related to a problem? Please describe.
The requirement is to display URL in Hindi and Marathi Languages which is not dynamic URL so cant use [...lang] inside page directory

**Comment by getspooky** [comment] 2021-02-19 16:55
The same problem with chinese language

**Comment by shuding** [comment] 2021-03-08 18:47
Closing as duplicate of #10084.

**Closed by shuding** 2021-03-08 18:47 UTC
Labels: good first issue, kind: bug, type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-28 15:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
