### ISSUE TITLE
Next/Image blur not working 

### ISSUE THREAD

**Issue by okeybond** [vercel/next.js#20645] opened 2020-12-31 13:04 UTC
### Blur not working in Next/Image

`<Image
    layout={"fill"}
    src={"https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2019/12/03202400/Yellow-Labrador-Retriever.jpg"}
    className={'rounded'}
    alt="thumbnail"
    style={{filter: 'blur(2px)'}}
/>
`

Image blur stopped working after using next/image, please assist

**Comment by lachlanjc** [comment] 2020-12-31 16:05
I believe this isn’t specific to blurring—it’s because the Image component doesn’t allow styling with `className`/`style`. See #18585

**Comment by Timer** [comment] 2020-12-31 16:37
Closing as duplicate of #18585

**Closed by Timer** 2020-12-31 16:37 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 23:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
