### ISSUE TITLE
Typekit fonts not loading in production build with Next.js v12

### ISSUE THREAD

**Issue by sveggiani** [vercel/next.js#30569] opened 2021-10-28 16:42 UTC
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

14.15.3

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel / Local builds

### Describe the Bug

Typekit fonts imports **not working in production build (`yarn build`) but working OK in dev mode (`yarn dev`)**.

Notes:
- We have  defected to Babel by adding `.babelrc` file because [SWC broke our builds](https://github.com/vercel/next.js/issues/30395).
- Canary build doesn't even build for us so we couldn't can test it.

```tsx
// file: .babelrc
// ---
// Added ONLY to disable SWC and fallback to Babel in Next.js 12.
// 1. https://github.com/vercel/next.js/issues/30395
// 2. https://github.com/vercel/next.js/discussions/30174
// 3. https://nextjs.org/docs/upgrading#upgrading-from-11-to-12
//
// TODO: this file should be removed when the issue is fixed
{
  "presets": ["next/babel"]
}

// file: _app.tsx
import '@assets/styles/main.css';

// file: assets/styles/main.css
@import './base.css';
@import './fonts.css';

// file: assets/styles/fonts.css
@import url('https://fonts.googleapis.com/css2?family=Rubik:wght@900&display=swap'); // WORKS!
@import url('https://use.typekit.net/yvn5rnt.css'); // DOESN'T WORK!
```

Something weird is that Google Web Fonts imports work as expected.

### Expected Behavior

Fonts imported from Typekit loads as expected.

### To Reproduce

1. Import some fonts from Typekit and use them in your styles.
2. Run `yarn build` and then `yarn start`.
3. Check that Typekit fonts are not loaded by the page.

**Comment by joshdocking** [comment] 2021-12-21 04:05
Still an issue in 12.0.7

**Comment by balazsorban44** [comment] 2021-12-21 11:21
Hi, this might be caused by the same issue reported in #32645

Could someone verify if this works if you put the `@import` statement at the top of the file/before you define `font-family`?

**Comment by sveggiani** [comment] 2021-12-21 11:43
I'm sorry @balazsorban44 , I don't have access to this project anymore. Perhaps @joshdocking has a working case for it.

**Comment by Shuhratt** [comment] 2021-12-21 12:05
next 12.0.4
I specify fonts in css files
@import url('https://fonts.googleapis.com/css2?family=Rubik:wght@900&display=swap')

after building the project 

in css files, the font is displayed like this

@import ("https://fonts.googleapis.com/css2?family=Rubik:wght@900&display=swap")

**Comment by balazsorban44** [comment] 2021-12-23 00:00
I'm closing as possible duplicate of #32645

If someone can prove otherwise, I'm happy to re-open and discuss this further.

**Closed by balazsorban44** 2021-12-23 00:00 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 01:27
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
