### ISSUE TITLE
Metadata is not working at all in `/not-found.tsx` (App directory)

### ISSUE THREAD

**Issue by ReoHakase** [vercel/next.js#49030] opened 2023-05-01 09:16 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
    Binaries:
      Node: 18.14.1
      npm: 9.3.1
      Yarn: 3.3.0
      pnpm: 7.29.3
    Relevant packages:
      next: 13.3.3-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue

https://github.com/ReoHakase/next13-app-head-is-not-working-in-not-found

### To Reproduce

```bash
# Clone the repo to reproduce
gh repo clone ReoHakase/next13-app-head-is-not-working-in-not-found

# Install dependencies
pnpm i

# Run the dev server
pnpm dev
```

## Visit `/`
You can see `metadata` from `layout.tsx` is loaded and working as intended.
<img width="627" alt="image" src="https://user-images.githubusercontent.com/16751535/235432451-28951da7-1b57-40db-b791-4f4d3c78107d.png">
<img width="540" alt="image" src="https://user-images.githubusercontent.com/16751535/235432847-17f84815-6835-4488-9d19-b65bfd8f973e.png">

## Visit `/404` or `/not-found` or `/whatever-you-can-type`
No `metadata` is loaded unlike `/`.
<img width="629" alt="image" src="https://user-images.githubusercontent.com/16751535/235432558-df69785d-9cf2-40c4-add5-a0666c3dff1b.png">
Since no viewport settings is given, the content gets displayed very tiny in mobile environment.
<img width="538" alt="image" src="https://user-images.githubusercontent.com/16751535/235432658-46039e09-7e3b-4c64-b314-3b974659e5c3.png">

### Describe the Bug

Metadata is not loaded and working in `/not-found.tsx`

### `metadata` configuration
```tsx
// layout.tsx
export const metadata: Metadata = {
  title: {
    default: "Acme Inc.",
    template: "%s | Acme Inc.",
  },
  description: "Lorem Ipsum",
  viewport: {
    width: "device-width",
    initialScale: 1.0,
  },
  openGraph: {
    // Open graph image will be provided via file-based configuration.
    // Refer: https://beta.nextjs.org/docs/api-reference/metadata#static-images
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    site: "@acme",
  },
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f8f9fa" },
    { media: "(prefers-color-scheme: dark)", color: "#1a1d1e" },
  ],
};
```

```tsx
// not-found.tsx
export const metadata: Metadata = {
  title: "Not Found",
};
```

### Rendered `<head>` in routes that `/not-found.tsx` is used
No corresponding tags is rendered, even `title`.
```html
<head><meta name="robots" content="noindex"><script src="/_next/static/chunks/polyfills.js" nomodule=""></script></head>
```

### Rendered `<head>` in the other normal routes such as `/`.
Working as expected
```html
<head><meta charset="utf-8"><title>Acme Inc.</title><meta name="description" content="Lorem Ipsum"><meta name="theme-color" media="(prefers-color-scheme: light)" content="#f8f9fa"><meta name="theme-color" media="(prefers-color-scheme: dark)" content="#1a1d1e"><meta name="viewport" content="width=device-width, initial-scale=1"><meta property="og:type" content="website"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:site" content="@acme"><script src="/_next/static/chunks/polyfills.js" nomodule=""></script></head>
```

### Expected Behavior

`<head>` should be rendered with the following content in `/not-found.tsx`, as it is working in the other routes.
```html
<head><meta charset="utf-8"><title>Not Found | Acme Inc.</title><meta name="description" content="Lorem Ipsum"><meta name="theme-color" media="(prefers-color-scheme: light)" content="#f8f9fa"><meta name="theme-color" media="(prefers-color-scheme: dark)" content="#1a1d1e"><meta name="viewport" content="width=device-width, initial-scale=1"><meta property="og:type" content="website"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:site" content="@acme"><script src="/_next/static/chunks/polyfills.js" nomodule=""></script></head>
```

**Comment by darthmaim** [comment] 2023-05-01 13:31
Duplicate of #45620 and #46619

**Comment by shuding** [comment] 2023-05-03 13:15
Closing this one as we are tracking it in #45620.

**Closed by shuding** 2023-05-03 13:15 UTC
Labels: template: bug, area: Metadata, area: app
