### ISSUE TITLE
No pathname getServerSideProps

### ISSUE THREAD

**Issue by rajatdhoot123** [vercel/next.js#20737] opened 2021-01-04 11:43 UTC
# Bug report

## Describe the bug

When I navigate from the client (not hard refresh) getServerSideProps called in which I required pathname (current URL showing in browser) but there seems no option for it because it was dynamic Routing it always provides `href` and I want `as` also

`<Link as="/english" href="/">`

**Comment by ijjk** [comment] 2021-01-04 19:39
Hi, this doesn't appear to be a bug but is hard to tell as no reproduction was provided. I'm going to close this since it doesn't appear actionable, see here for more information on the values available in `getServerSideProps` context https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering

**Closed by ijjk** 2021-01-04 19:39 UTC

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
