### ISSUE TITLE
Rewrite adds query param when re-appending a matched path param to the destination

### ISSUE THREAD

**Issue by sventschui** [vercel/next.js#15626] opened 2020-07-29 10:55 UTC
# Bug report

## Describe the bug

A rewrite from `/source/:route*` to `http://my-api-server.example.org/destination/:route*` forwards a request sent to `/source/foo` to `http://my-api-server.example.org/destination/foo?route=foo`. The extra query param will lead to issues especially with API servers as in REST this might represent a filter criteria.
## To Reproduce

1. Create a new next app

2. Create a custom next.config.js:

```js
module.exports = {
  async rewrites() {
    return [
      {
        source: "/api/:route*",
        destination: "https://postman-echo.com/:route*",
      },
    ];
  },
};

```

3. Start next: `yarn next dev`

4. Open up `http://localhost:3000/api/get`

5. The results includes `"url":"https://postman-echo.com/get?route=get"`

## Expected behavior

Params that are added to the destination path should not be included as a query param.

5. The results includes `"url":"https://postman-echo.com/get"`

## Screenshots

n/a

## System information

- Version of Next.js: 9.5.0
- Version of Node.js: n/a

## Additional context

n/a

**Comment by mAAdhaTTah** [comment] 2020-07-29 14:08
I'm seeing similar behavior, although in my case it's `path`, rather than `route`. Comparing your implementation & mine, the param appears to be chosen based on the config param name:

```
source: "/api/:route*",
destination: "https://postman-echo.com/:route*",
```

Because you're using `:route*` here, and we're using `:path` (which we copied straight from the docs), that's what gets appended as a query string. If it helps, a workaround could be to change that param name to something obvious to ignore and either ignoring it completely at the server side or just choosing something that won't conflict.

**Comment by ijjk** [comment] 2020-07-29 15:59
Hi, this is the behavior currently since when rewriting the end-user doesn't see the query values so we make all params available in the query automatically. 

After discussion it looks like it would make sense to not add the params to the query automatically for rewrites if it is already used in the destination so we will be investigating this behavior

**Comment by pratheekhegde** [comment] 2020-07-30 13:49
Stumbled upon the same issue and it bugged me for the last two days. Later in my local next build when `appendParamsToQuery` in `rewrites` was set to `false` resolved the issue. 

https://github.com/vercel/next.js/blob/dcb69ee92f9d8bac28f7c53d7ded30919931cf3d/packages/next/next-server/server/next-server.ts#L588

But there seems to be another weird behavior. If the request URL has a trailing slash it's being ignored while proxying.
My `next.config.js`
```
{
    async rewrites() {
      return [
        {
          source: "/api/:path*",
          destination: "https://myservice.com/api/:path*",
        },
      ];
    }
  }
```
Request URL : `http://localhost:3000/api/xyz/`
Proxied URL : `https://myservice.com/api/xyz` (In my server logs)

And when I set `trailingSlash` to `true` in my `next.config.js` My request URL gets `308` to the same URL with trailing slash (Expected) but the page return `404`.

Isn't this unusual @ijjk ?

**Closed** 2020-08-14 18:51 UTC
Labels: kind: bug, point: 2, priority: p0

**Comment by ijjk** [comment] 2020-08-14 20:50
Hi, this has been updated in the latest canary of Next.js (`v9.5.3-canary.3`), please upgrade and give it a try!

**Comment by ijjk** [comment] 2020-08-14 20:50
@pratheekhegde the issue you mentioned with the trailing slash and rewrites can be tracked in this issue https://github.com/vercel/next.js/issues/15700

**Comment by pratheekhegde** [comment] 2020-08-15 07:56
Thank you @ijjk , I shall track it there.

**Comment by a-axton** [comment] 2021-03-04 00:01
Hope it's okay to piggy-back off this but I'm still seeing this issue on v10.0.5. I have a different setup than this which I found in another issue for adding `X-Forwarded` headers, as seen here https://github.com/vercel/next.js/discussions/17325#discussioncomment-105499. I'm guessing having slightly different paths in the rewrites messes up the changes in 9.5.3? Here's an example of one of my rewrites
```
      {
        source: '/api/:path*',
        destination: '/api/proxy/:path*',
      },
```
A little curious to the reason of adding those query params at all, what are they used for?

**Comment by balazsorban44** [comment] 2022-01-28 16:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
