### ISSUE TITLE
TypeError: res.clearPreviewData is not a function when disabling preview

### ISSUE THREAD

**Issue by mathewtrivett** [vercel/next.js#30092] opened 2021-10-20 09:49 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

We have preview set up on our application. We have an API route to disable preview by calling `res.clearPreviewData()` as in the docs. This has been working fine until yesterday, when we implemented fully dynamic routes. Now we are getting the following error / stack trace.

This is causing the server to die and our container restarts.

```
[1634722442662] ERROR (21691 on Mathews-MacBook-Pro.local): res.clearPreviewData is not a function
    err: {
      "type": "TypeError",
      "message": "res.clearPreviewData is not a function",
      "stack":
          TypeError: res.clearPreviewData is not a function
              at disable (/Users/mathewtrivett/Documents/Codebase/fettle-amber/build/server/pages/api/preview/disable.js:29:9)
              at d (/Users/mathewtrivett/Documents/Codebase/fettle-amber/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
              at bb (/Users/mathewtrivett/Documents/Codebase/fettle-amber/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
              at a.b.render (/Users/mathewtrivett/Documents/Codebase/fettle-amber/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
              at a.b.read (/Users/mathewtrivett/Documents/Codebase/fettle-amber/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
              at Object.exports.renderToString (/Users/mathewtrivett/Documents/Codebase/fettle-amber/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
              at renderPage (/Users/mathewtrivett/Documents/Codebase/fettle-amber/node_modules/next/dist/server/render.js:596:45)
              at Object.ctx.renderPage (/Users/mathewtrivett/Documents/Codebase/fettle-amber/build/server/pages/_document.js:39:30)
              at Function.getInitialProps (/Users/mathewtrivett/Documents/Codebase/fettle-amber/build/server/chunks/859.js:603:19)
              at Function.getInitialProps (/Users/mathewtrivett/Documents/Codebase/fettle-amber/build/server/pages/_document.js:43:85)
    }
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Promise%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at O (/Users/mathewtrivett/Documents/Codebase/fettle-amber/node_modules/react/cjs/react.production.min.js:17:207)
    at P (/Users/mathewtrivett/Documents/Codebase/fettle-amber/node_modules/react/cjs/react.production.min.js:17:355)
    at toArray (/Users/mathewtrivett/Documents/Codebase/fettle-amber/node_modules/react/cjs/react.production.min.js:19:177)
    at a.b.render (/Users/mathewtrivett/Documents/Codebase/fettle-amber/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:249)
    at a.b.read (/Users/mathewtrivett/Documents/Codebase/fettle-amber/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (/Users/mathewtrivett/Documents/Codebase/fettle-amber/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at renderPage (/Users/mathewtrivett/Documents/Codebase/fettle-amber/node_modules/next/dist/server/render.js:596:45)
    at Object.ctx.renderPage (/Users/mathewtrivett/Documents/Codebase/fettle-amber/build/server/pages/_document.js:39:30)
    at Function.getInitialProps (/Users/mathewtrivett/Documents/Codebase/fettle-amber/build/server/chunks/859.js:603:19)
    at Function.getInitialProps (/Users/mathewtrivett/Documents/Codebase/fettle-amber/build/server/pages/_document.js:43:85)
```

Routes are set up like this:

```
[topLevel]
   index.jsx
   [subLevel]
      index.jsx
      [slug].jsx
api/
   preview/
       [contentType]
           [slug].jsx
       disable.jsx      
``` 

### Expected Behavior

We expected to be able to call `res.clearPreviewHeaders()` and it clear the headers without error before calling `res.redirect('/')

### To Reproduce

Reproduce-ability is hard as it involves integration with a CMS. Happy to receive any guidance on what would make a minimally reproducible case here.

**Comment by ijjk** [comment] 2021-10-21 03:51
Hi, can you provide a minimal reproduction? It looks like the API route is being called with the same `res` object that is provided to `getServerSideProps` which differs from the `res` object provided to API routes.

**Comment by timneutkens** [comment] 2021-11-17 15:49
Closing as no reproduction was provided.

**Closed by timneutkens** 2021-11-17 15:49 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
