### ISSUE TITLE
[static export] assetPrefix is configured but the page loads [assetPrefix].js, and/orr loads wrong js under the _next folder.

### ISSUE THREAD

**Issue by codyng** [vercel/next.js#10753] opened 2020-02-29 18:05 UTC
# Bug report

When exporting the site to static files, and assetPrefix is set in next.config.js, e.g. 
assetPrefix: '/sales', the site loads wrong js files. (I put the static site to my local host Apache to run)

http://localhost/sales/_next/static/lOxnKk2GrKFkXm_C1zUkT/pages/sales.js
The sales.js shouldn't exist. I don't know why it needs to load it and thus it makes 404 js error.

http://localhost/sales/_next/static/lOxnKk2GrKFkXm_C1zUkT/pages/sales/reports.js
It tried to load reports.js under the sales folder.

## Describe the bug

The bug happens if we build and export the sites by setting the assetPrefix.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create the src folder and move the pages folder inside
2. Configure the next.config.js likes below:

```
const isProd = process.env.NODE_ENV === 'production';
const prodSubFolder = '/sales';

module.exports = {
    exportTrailingSlash: true,
    assetPrefix: isProd ? prodSubFolder : '',
    publicRuntimeConfig: {
        staticFolder: isProd ? prodSubFolder : ''
    }
}
```

3. Make the page structure:

src/pages/_app.js
src/pages/_document.js
src/pages/index.js
src/pages/reports/index.js

4. build and export

5. Put the static built files to another web server to test (I use Apache @ localhost)

6. Go to: http://localhost/sales/reports/

Open the Chrome debug console, you will see two 404 file not found, the paths are something like:

http://localhost/sales/_next/static/lOxnKk2GrKFkXm_C1zUkT/pages/sales.js
http://localhost/sales/_next/static/lOxnKk2GrKFkXm_C1zUkT/pages/sales/reports.js

## Expected behavior

The sales.js should not be loaded (or desired to created) and
the reports.js should be loaded in this path: http://localhost/sales/_next/static/lOxnKk2GrKFkXm_C1zUkT/pages/reports.js

I have visited to /_next/static/lOxnKk2GrKFkXm_C1zUkT/pages/ and see there are only index.js and reports.js, no any folders.

## Screenshots

Please see the attached screenshots.

<img width="983" alt="Screenshot 2020-03-01 at 02 02 56" src="https://user-images.githubusercontent.com/4618641/75612705-19248300-5b61-11ea-8737-93375dcd5fae.png">

## System information

- OS: macOS Catalina 10.15.3
- Browser: Chrome Version 80.0.3987.122 (Official Build) (64-bit)
- Version of Next.js: 9.2.2

## Additional context

N/A

**Comment by codyng** [comment] 2020-02-29 20:32
I've just found that it should be the bug of prefetch of <Link>.

The hyperlink to the reports page is:

```
                <Link href="/sales/articles"}>
                    <a>
                        Reports
                    </a>
                </Link>
```

The above code will show the 404 js error. However, after I put prefetch={false}, or I don't use <Link>, the error is gone.

If not using prefetch, the 404 js error happens when jumping to the articles page.

So it should be the bug about prefetch that it finds the wrong "route".

**Comment by ijjk** [comment] 2020-02-29 20:49
Hi, it looks like an incorrect `href` value is being used above since you don't mention having a `sales/articles` or a `sales/reportes` page. 

The `href` should be the page you are trying to navigate to. If you are wanting a different URL to be shown than the page you are navigating to you can use the `as` prop along with `href` e.g. `<Link href='/reports' as='/sales/reports'><a>Click me</a></Link>`. See more info for `next/link` in [our docs](https://nextjs.org/docs/api-reference/next/link)

**Comment by codyng** [comment] 2020-03-01 04:32
Thanks for your reply. I made the typo mistake: originally it should be:
```
<Link href="/sales/reports"}>
	<a>
		Reports
	</a>
</Link>
```
I've just found that by adding the "as" parameter, the problem is fixed. Thanks!

```
<Link href="/articles" as="/sales/articles"}>
	<a>
		Reports
	</a>
</Link>
```

I am just thinking the combined usage of href and as are quite confusing.

Users have set assetPrefix in next.config.js, here we also need to manually assign the "as" path.....
Next.js won't help us add the base path prefix to all <Link>???

Actually, I am using the public runtime variable, staticFolder:

```
module.exports = {
...
    publicRuntimeConfig: {
        staticFolder: isProd ? prodSubFolder : ''
    }
...
}
```
and apply <Link> like this:

```
<div>
	<Link href={`${Config.staticFolder}/reports`}>
		<a>
			Reports
		</a>
	</Link>
</div>
```

On usage, I missed the as parameter. Now the safe usage that supports assetPrefix becomes:

```
<Link href="/reports" as={`${Config.staticFolder}/reports`}>
</Link>
```

which is not friendly usage compared with just:
```
<Link href={`${Config.staticFolder}/reports`}>
</Link>
```

Next.js always expects loading ${Config.staticFolder}/reports.js file (during the prefetch) which is not exist physically. The prefetch URL depends heavily on the href parameter of <Link>.

Just think that users won't put reports.js like this: pages/[assetPrefix]/reports.js,
but should be this: pages/reports.js

The conclusion is: we need to use both the **href** and **as** if the site needs to support the assetPrefix configure. We don't know whether the clients tell you the production site needs to be put under some base paths within the domain someday.

Please also let me know if there are any smart solutions. :)

**Comment by Timer** [comment] 2020-09-03 02:38
Closing as this is properly handled now by the new base path support:
https://nextjs.org/docs/api-reference/next.config.js/basepath

**Closed by Timer** 2020-09-03 02:38 UTC

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
