### ISSUE TITLE
Error in 12.0.1 with experimental features enabled

### ISSUE THREAD

**Issue by callumok2004** [vercel/next.js#30437] opened 2021-10-27 13:30 UTC
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

16.12.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows 11

### How are you deploying your application?

Development Server | yarn dev

### Describe the Bug

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from E:\Developing\Ryft\Website-Main\.env
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

warn  - SWC minify beta enabled. https://nextjs.org/docs/messages/swc-minify-enabled
info  - Using the experimental web runtime.
wait  - compiling...
event - compiled successfully in 1666 ms (174 modules)
warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
wait  - compiling /...
wait  - compiling...
error - ./node_modules/next/dist/build/webpack/loaders/next-middleware-ssr-loader/index.js?page=-web%2F&absolutePagePath=E%3A%5CDeveloping%5CRyft%5CWebsite-Main%5Csrc%5Cpages%5Cindex.tsx&isServerComponent=false&buildId=development&basePath=&assetPrefix=!
Module not found: Can't resolve 'E:/Developing/Ryft/Website-Main/pages/_document' in 'E:\Developing\Ryft\Website-Main'
error - Error: ENOENT: no such file or directory, open 'E:\Developing\Ryft\Website-Main\.next\server\middleware-ssr-runtime.js'
wait  - compiling /_error...
wait  - compiling...
error - ./node_modules/next/dist/build/webpack/loaders/next-middleware-ssr-loader/index.js?page=-web%2F&absolutePagePath=E%3A%5CDeveloping%5CRyft%5CWebsite-Main%5Csrc%5Cpages%5Cindex.tsx&isServerComponent=false&buildId=development&basePath=&assetPrefix=!
Module not found: Can't resolve 'E:/Developing/Ryft/Website-Main/pages/_document' in 'E:\Developing\Ryft\Website-Main'
error - Error: ENOENT: no such file or directory, open 'E:\Developing\Ryft\Website-Main\.next\server\middleware-ssr-runtime.js'
```

### Expected Behavior

It should be able to compile just fine.

### To Reproduce

Update from next.js 12.0.0 to 12.0.1

**Comment by shuding** [comment] 2021-10-30 00:10
Closing this as it's duplicated with #30424, will track there 👍

**Closed by shuding** 2021-10-30 00:10 UTC
Labels: kind: bug, type: needs investigation

**Comment by balazsorban44** [comment] 2022-01-27 13:08
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
