### ISSUE TITLE
next/script not loading anything at all

### ISSUE THREAD

**Issue by mrtnbroder** [vercel/next.js#26187] opened 2021-06-16 13:09 UTC
### What version of Next.js are you using?

11

### What version of Node.js are you using?

15

### What browser are you using?

Brave

### What operating system are you using?

macOS

### How are you deploying your application?

next dev, next build, serverless

### Describe the Bug

Using the new `next/script` tag inside `document.tsx`

```tsx
<Script
  id="gmaps-script"
  src="https://maps.googleapis.com/maps/api/js?libraries=places&key=[KEY]&map_ids=[MAP_ID]"
  strategy="afterInteractive"
/>
```
          
The script is not being loaded

### Expected Behavior

The script should load google maps

### To Reproduce

Create a new project via `create-nextjs-app` and add the snippet above.

**Comment by keslert** [comment] 2021-06-16 17:11
I'm also experiencing this on Chrome in prod and dev with all of my Script components regardless of the strategy I set.

**Comment by dareiff** [comment] 2021-06-16 17:23
The same — after reading about the feature in Docs, I'm wondering where the recommended spot for using <Script> is — _app/_doc? Or in a top-level component?

**Comment by Sandeep0695** [comment] 2021-06-16 19:15
I am also facing the same !!!

**Comment by sebascomeau** [comment] 2021-06-16 19:37
Moved Script to _app.tsx... working!

**Comment by Sandeep0695** [comment] 2021-06-16 20:28
> Moved Script to _app.tsx... working!

But is that right place (_App.tsx) to load that?

**Comment by igormartimiano** [comment] 2021-06-16 21:16
> > Moved Script to _app.tsx... working!
> 
> But is that right place (_App.tsx) to load that?

Don't think so, they even have it on an example using scripts on `_document.js`:
https://github.com/vercel/next.js/blob/canary/examples/with-google-analytics/pages/_document.js
That would be the case if they changed the `Script` component behavior, but I don't think that's not documented at all.

**Comment by sebascomeau** [comment] 2021-06-16 21:45
> > > Moved Script to _app.tsx... working!
> > 
> > 
> > But is that right place (_App.tsx) to load that?
> 
> Don't think so, they even have it on an example using scripts on `_document.js`:
> https://github.com/vercel/next.js/blob/canary/examples/with-google-analytics/pages/_document.js
> That would be the case if they changed the `Script` component behavior, but I don't think that's documented at all.

<script> is not the "next/script" component but html script tag

"next/script" can be place at _app level or at any page level, imo

**Comment by nratter** [comment] 2021-06-16 21:46
It doesn't work if you put it inside a <Head> tag

**Comment by igormartimiano** [comment] 2021-06-16 22:03
> > > > Moved Script to _app.tsx... working!
> > > 
> > > 
> > > But is that right place (_App.tsx) to load that?
> > 
> > 
> > Don't think so, they even have it on an example using scripts on `_document.js`:
> > https://github.com/vercel/next.js/blob/canary/examples/with-google-analytics/pages/_document.js
> > That would be the case if they changed the `Script` component behavior, but I don't think that's documented at all.
> 
> `<script>` is not **_next/script_** component but a html script tag
> 
> **_next/script_** can be place at _app or page level
> 
> The docs need to mentionne it though.

Excuse me if it was a little confusing, but that's exactly what I meant. If they changed the `Script` component behavior  in that sense compared to a common `<script>` tag like the one in the example, that could cause side effects like this issue. 

As you said and I agree, this really need to be addressed by docs. If that's actually intended, this is a breaking change. Like the one in the example, scripts shared between pages were commonly used in `_document.js`.

**Comment by AndreAffonso** [comment] 2021-06-17 00:18
Same problem here. It's working in `_app.tsx`but is not a big deal loading the same scripts in every single page.
 
The ideal behavior would be using in `_document.js`

**Closed** 2021-06-17 13:46 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 06:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
