### ISSUE TITLE
preloaded images have blur filter applied even if they are already loaded

### ISSUE THREAD

**Issue by riccardogiorato** [vercel/next.js#27539] opened 2021-07-27 17:10 UTC
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

14.0.0

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS, Linux, Windows

### How are you deploying your application?

Vercel

### Describe the Bug

preloaded images have blur filter applied even if they are already loaded

Taken from an existing PR: https://github.com/vercel/next.js/pull/26405/
> In Next.js v11.0.0 next/image <img /> element always has filter: blur(20px) initially. It's removed once image onLoad callback fires. But, when image is already cached, it renders almost instantly, and the onLoad callback usually fires with a delay 1s or more. This creates a redundant blurring affect on already rendered images.

### Expected Behavior

As soon as the image gets loaded thanks to the "priority" flag it should be visible in the page. 

### To Reproduce

Visible if you do a build of this code: https://codesandbox.io/s/nextjs-bug-blur-priority-nt3tr

**Comment by styfle** [comment] 2021-08-04 18:52
The linked [codesandbox](https://codesandbox.io/s/nextjs-bug-blur-priority-nt3tr) isn't using the the correct props.

I'm seeing:

```jsx
import Img from "next/image";

<Img
  placeholder="placeholder"
  placeholder="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
  layout="fill"
  src="/sea.jpg"
  priority
/>
```

But it should be:

```jsx

import Img from "next/image";

<Img
  placeholder="blur"
  blurDataURL="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
  layout="fill"
  src="/sea.jpg"
  priority
/>
```

Although a better solution is to utilize the native blur feature by using a static import:

```jsx
import Img from "next/image";
import sea from "../public/sea.jpg";

<Img
  placeholder="blur"
  layout="fill"
  src={sea}
  priority
/>
```

**Comment by riccardogiorato** [comment] 2021-08-04 20:33
My bad it's clear bug if you look at the PR I referenced in the description.
The problem is not related to local or remote images.

The next/image <img /> element always has filter: blur(20px) initially. It's removed once image onLoad callback fires. But, when image is already cached, it renders almost instantly, and the onLoad callback usually fires with a delay 1s or more. This creates a redundant blurring affect on already rendered images.


If you look at this screenshot the blurred image:
1. nextjs shows the blurred version
2. just a bit after DCL(dom content loaded) the full image resolution is loaded from the server but the filter: blur(20px) is still applied on it
3. after 1s or more the filter blur is removed and finally you can see the already downloaded image.

Is this behaviour wanted? If we remove the filter blur as soon as the high resolution ends the download would it possible to merge the already mentioned PR or a variation of it to fix this?

![image](https://user-images.githubusercontent.com/4527364/128250478-a1e87072-1f5a-4939-ba54-403ae9632527.png)

**Comment by styfle** [comment] 2021-08-04 22:20
> the onLoad callback usually fires with a delay 1s or more

I'm not seeing this behavior, its nearly instant.
For example, visit https://styfle.dev/contact and the refresh the page.
The blur is only there for a fraction of a second as the cached image decodes.

> would it possible to merge the already mentioned PR or a variation of it to fix this?

We need to have an integration test to merge the PR, and in order to create a test we need to reproduce the issue.

**Comment by riccardogiorato** [comment] 2021-08-05 05:46
With a video you should be able to see it.
The reference url is:  https://www.amusi.it
The specific test run is here too: https://www.webpagetest.org/video/compare.php?tests=210805_BiDc62_5be8024ad21baf9f6f827203629b6eb7

Let's timestamp the exact moment to visualize this delay:
1. the page loads the blurred image, visibile from time 2.8s to 8.1s
2. from 8.2s the high resolution image starts to be downloaded until 9.9s, you can see the gradual download appearing on top of the blurred image until the second 
3. finally even if the full image is all downloaded at 9.9 seconds the image become visible without the blurred ontop at second 11.5s.

The time I'm trying to debug with you is the time from 9.9s to 11.5s, during this 2 seconds next is still not showing the fully downloaded image even if it's fully ready and visible under the blur.

https://user-images.githubusercontent.com/4527364/128296827-af2e7738-e454-49f7-a2bb-839319b1b9a7.mp4


If you look closely in the webpagetest page here, you can see the 2 seconds from when the image is fully downloaded up until the visualization at 11.5s: https://www.webpagetest.org/video/compare.php?tests=210805_BiDc62_5be8024ad21baf9f6f827203629b6eb7
![image](https://user-images.githubusercontent.com/4527364/128297615-211023d9-f2ee-4cd2-b3ad-ae6eb20e5dba.png)

**Comment by ijjk** [comment] 2021-09-21 04:41
The [above comment](https://github.com/vercel/next.js/issues/27539#issuecomment-906292999) is correct and the blur is only expected to be removed after the image is fully loaded and rendered. I'm going to close this since it doesn't appear to be a bug and seems to be working correctly in the latest version of Next.js `v11.1.2`

**Closed by ijjk** 2021-09-21 04:41 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
