### ISSUE TITLE
next/image build err, get img err

### ISSUE THREAD

**Issue by Vsion** [vercel/next.js#27164] opened 2021-07-14 10:12 UTC
### What version of Next.js are you using?

11.0.2-canary.14

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

chrome

### What operating system are you using?

windows 10

### How are you deploying your application?

next build

### Describe the Bug

![image](https://user-images.githubusercontent.com/11804448/125604340-731859ea-b39c-43c4-8480-ae53d698eb5a.png)

![image](https://user-images.githubusercontent.com/11804448/125604746-93ef130f-fa9f-49bc-acb1-cd2049d15054.png)

received: The requested resource isn't a valid image.

without data.map, Image worked.

### Expected Behavior

worked in data.map(({ src }) => <Image src={src}>)

### To Reproduce

import Image from 'next/image'

const honours =  [
  { name: 'test', props: {
    width: 100,
    height: 73,
  }, image: 'test1' }]

honours.map((item: any) => {
              return <Image priority {...item.props} src={'/assets/xxx' + item.image + '.png'} title="title"/>})

**Comment by Vsion** [comment] 2021-07-14 10:16
also expect support "next export" with next/image

**Comment by Vsion** [comment] 2021-07-22 09:29
maybe something wrong with "next build"

**Comment by Vsion** [comment] 2021-07-22 10:22
found it!
because the path of image with chinese, but it worked in dev mode and next export (before i use next/image, i used with "next build && next export"). it confuse me.

**Comment by ijjk** [comment] 2021-07-22 20:56
Hi it sounds like this has been resolved from the above comment so I'm gonna close this, if you're still having trouble with this feel free to respond with additional info!

**Closed by ijjk** 2021-07-22 20:56 UTC
Labels: template: bug

**Comment by Vsion** [comment] 2021-07-27 07:31
sorry, maybe I can't make it clear.
In prod mode,  it could not get img, (img.src within chinese)
but it work in dev mode

**Comment by balazsorban44** [comment] 2022-01-28 01:27
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
