### ISSUE TITLE
Custom App.js documentation example can lead to unexpected production build issues

### ISSUE THREAD

**Issue by beager** [vercel/next.js#10904] opened 2020-03-09 18:53 UTC
# Bug report

## Describe the bug

The Custom App.js documentation includes a code sample that instructs users to override next/app with a function component:

```js
// import App from 'next/app'

function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}

// Only uncomment this method if you have blocking data requirements for
// every single page in your application. This disables the ability to
// perform automatic static optimization, causing every page in your app to
// be server-side rendered.
//
// MyApp.getInitialProps = async (appContext) => {
//   // calls page's `getInitialProps` and fills `appProps.pageProps`
//   const appProps = await App.getInitialProps(appContext);
//
//   return { ...appProps }
// }

export default MyApp
```

https://github.com/zeit/next.js/blob/canary/docs/advanced-features/custom-app.md

This example is instructive with respect to showing users how to disable automatic site optimization by defining an app-wide `getInitialProps`, but when using this example in an application, it seems to block app rehydration across the board when running a production build.

I do not have visibility into the breadth of use cases this documentation intends to support, but I was able to create a true no-op default override based on other examples:

```js
import App from 'next/app';

class MyApp extends App {
  render() {
    const { Component, pageProps } = this.props;

    return <Component {...pageProps} />;
  }
}

export default MyApp;
```

(NB: This does not include a commented-out section on overriding `getInitialProps`)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a Next.js project and apply the custom _app.js code from the existing documentation.
2. Create a dynamic Next.js page in this project that can be statically optimized but whose functionality relies on rehydration
3. Create and run a production build of the app.
4. Observe that with the custom _app.js code from the existing documentation, the static page does not properly rehydrate.

## Expected behavior

Expect that the example code for creating a custom App does not have unexpected side effects.

## System information

- OS: macOS 10.14.6
- Browser (if applies): Tested in Chrome 80.0.3987.132
- Version of Next.js: 9.2.0

Thank you for your consideration of this issue.

**Comment by Timer** [comment] 2020-04-15 05:37
I cannot reproduce this. Can you please provide a full demo?

**Comment by Timer** [comment] 2020-09-03 02:34
Closing as no reproduction provided.

**Closed by Timer** 2020-09-03 02:34 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
