### ISSUE TITLE
Typescript return type of res.setHeader(header, value) doesn't match actual return type (undefined)

### ISSUE THREAD

**Issue by bugsalexander** [vercel/next.js#27253] opened 2021-07-17 06:28 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

12.21.0

### What browser are you using?

n/a

### What operating system are you using?

macOS catalina 10.15.7

### How are you deploying your application?

next start

### Describe the Bug

The typescript return type indicates that the method `NextApiResponse#setHeader` returns a NextApiResponse, but doing something like `res.setHeader("Allow", "GET, POST").status(405).send() results in `TypeError: Cannot read property 'status' of undefined`

### Expected Behavior

The method should return the response object 

### To Reproduce

for minimum test case, create a file in the `pages/api` folder something like the following (the particular header/status code doesn't matter):

```typescript
import { NextApiRequest, NextApiResponse } from 'next';
export default function handler(
    req: NextApiRequest,
    res: NextApiResponse
) {
    res.setHeader("Allow", "GET, POST").status(405).send(undefined);
}
```

run `next dev` or `next build` + `next start`. make a request to `localhost:300/api/<filename>` and the server should internal error with a TypeError.

**Comment by bugsalexander** [comment] 2021-07-17 06:29
was using postman to make the request, but it should happen with any browser

**Comment by ijjk** [comment] 2021-07-18 03:33
Hi, it looks like this type is correct for the latest version of Node `v16`, related `@types/node` type [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/33988371025ae2e58bdaa4391d6661d4ef273242/types/node/v15/http.d.ts#L179). To ensure this type matches the version of node you are using you can install the matching `@types/node` version which would be `@types/node@12.20.16` from the above provided info. 

I'm going to close this since it appears to be correct when using a matching version of node.

**Closed by ijjk** 2021-07-18 03:33 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
