### ISSUE TITLE
Unable to start the server

### ISSUE THREAD

**Issue by Hanaffi** [vercel/next.js#40636] opened 2022-09-17 13:29 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.3.0
      eslint-config-next: N/A
      react: 18.1.0
      react-dom: 18.1.0

### Describe the Bug

`npx create-next-app -e with-tailwindcss spotify` 
and then `cd spotify && yarn dev`
gives me this error:
```
info  - Using external babel configuration from /home/ahmed/spotify/.babelrc
error - ./node_modules/next/dist/client/dev/amp-dev.js
Error: Cannot find module 'xwind/babel'
Require stack:
- /home/ahmed/spotify/node_modules/next/dist/compiled/babel/bundle.js
- /home/ahmed/spotify/node_modules/next/dist/compiled/babel/traverse.js
- /home/ahmed/spotify/node_modules/next/dist/build/babel/loader/transform.js
- /home/ahmed/spotify/node_modules/next/dist/build/babel/loader/index.js
- /home/ahmed/spotify/node_modules/next/dist/compiled/webpack/bundle5.js
- /home/ahmed/spotify/node_modules/next/dist/compiled/webpack/webpack.js
- /home/ahmed/spotify/node_modules/next/dist/server/config-utils.js
- /home/ahmed/spotify/node_modules/next/dist/server/config.js
- /home/ahmed/spotify/node_modules/next/dist/server/next.js
- /home/ahmed/spotify/node_modules/next/dist/server/lib/start-server.js
- /home/ahmed/spotify/node_modules/next/dist/cli/next-dev.js
- /home/ahmed/spotify/node_modules/next/dist/lib/commands.js
- /home/ahmed/spotify/node_modules/next/dist/bin/next
```

### Expected Behavior

It should start the server !

### Link to reproduction

unneeded

### To Reproduce

`npx create-next-app -e with-tailwindcss spotify` 
and then `cd spotify && yarn dev`

**Comment by Hanaffi** [comment] 2022-09-17 13:45
Its solved by removing `.babelrc` file..
https://stackoverflow.com/a/73754647/19257410


Will keep it open in case there is a root issue..

**Comment by HaNdTriX** [comment] 2022-09-19 11:53
Looks like create-next-app picked up an old example:

```bash
$ npx create-next-app@canary -e with-tailwindcss-emotion spotify
```

should do the trick.

**Comment by balazsorban44** [comment] 2022-09-19 19:29
It was likely caused by a mixup when we were extracting examples from multiple directories, which has been fixed in this PR: https://github.com/vercel/next.js/pull/40513, currently available on `canary` as suggested above. This will be included in the next stable release.

**Closed by balazsorban44** 2022-09-19 19:29 UTC
Labels: template: bug
