### ISSUE TITLE
No page props after redirect in getStaticProps

### ISSUE THREAD

**Issue by alicerocheman** [vercel/next.js#23496] opened 2021-03-29 07:41 UTC
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

the route is composed like this: /myPage/{id}/{nameSlug}
I check if the nameSlug is the right one. If it isn't, I redirect to the path with the right slug.
The route is redirected (the url is corrected) but there are no pageProps

### Expected Behavior

route is redirected with pageProps

### To Reproduce

// in [...id_slug].tsx
```tsx
const MyPage: FC<InferGetStaticPropsType<typeof getStaticProps>> = ({establishment}) => {...};
export const getStaticPaths: GetStaticPaths = async () => {...}
export const getStaticProps: GetStaticProps<TProps, IParams> = async ({ params }) => {
  const {id_slug} = params;
  const id = id_slug[0]
  const data = getData(id)
  if(!data){
    return ({
      notFound: true
    });
  }
  if(id_name.length<2 || id_slug[1] !== data.establishment.slug){
    return({
      redirect:{
        destination: `/myPage/${id_name[0]}/${data.establishment.slug}`,
        statusCode: 301
      },
      revalidate:1
    });
  }
  return {
    props: {establishment: data.establishment},
    revalidate: 1
  }
}
```

call url with only id (no nameSlug)
=> url is fixed but no page props

**Comment by alicerocheman** [comment] 2021-03-29 08:23
id: 15
slug: château-alice

pageProps are empty:
<img width="499" alt="Screenshot 2021-03-29 at 10 21 11" src="https://user-images.githubusercontent.com/21168856/112807737-85c9c400-9078-11eb-834e-41e7d5b39d0a.png">

network call "15"
<img width="645" alt="Screenshot 2021-03-29 at 10 19 47" src="https://user-images.githubusercontent.com/21168856/112807836-a1cd6580-9078-11eb-8e0d-44b22ce02e74.png">

network call "15.json"
<img width="797" alt="Screenshot 2021-03-29 at 10 20 03" src="https://user-images.githubusercontent.com/21168856/112807869-ab56cd80-9078-11eb-93d2-4dc916ae384e.png">
<img width="975" alt="Screenshot 2021-03-29 at 10 20 14" src="https://user-images.githubusercontent.com/21168856/112807877-adb92780-9078-11eb-9a6a-ae47abb1ae09.png">

network call "château-alice.json"
<img width="932" alt="Screenshot 2021-03-29 at 10 20 42" src="https://user-images.githubusercontent.com/21168856/112807921-b9a4e980-9078-11eb-88ec-0f9b898c8053.png">
<img width="910" alt="Screenshot 2021-03-29 at 10 20 55" src="https://user-images.githubusercontent.com/21168856/112807930-bc074380-9078-11eb-841e-d6320394c869.png">

**Comment by ijjk** [comment] 2021-04-17 16:16
Hi, I'm not able to reproduce this on the latest version of Next.js `v10.1.3` so I'm going to close this, if you are still encountering problems with this please respond with additional information and we can investigate further.

**Closed by ijjk** 2021-04-17 16:16 UTC
Labels: template: bug

**Comment by alicerocheman** [comment] 2021-05-04 07:45
Hello @ijjk 
Thank you for your reply.
I've upgraded next to version 10.2.0
Now the redirection works well locally in dev mode.
The redirection also works in build/start mode locally, although it shows an error in the terminal:
```
Failed to update prerender files for /fr/producteur/15/chatau-alice TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
    at Object.writeFile (internal/fs/promises.js:621:5)
    at IncrementalCache.set (/Users/currentUser/Dev/myApp/react/node_modules/next/dist/next-server/server/incremental-cache.js:16:206)
    at async Server.renderToHTMLWithComponents (/Users/currentUser/Dev/myApp/react/node_modules/next/dist/next-server/server/next-server.js:137:27)
    at async Server.renderToHTML (/Users/currentUser/Dev/myApp/react/node_modules/next/dist/next-server/server/next-server.js:137:1088)
    at async Server.render (/Users/currentUser/Dev/myApp/react/node_modules/next/dist/next-server/server/next-server.js:74:255)
    at async Object.fn (/Users/currentUser/Dev/myApp/react/node_modules/next/dist/next-server/server/next-server.js:48:704)
    at async Router.execute (/Users/currentUser/Dev/myApp/react/node_modules/next/dist/next-server/server/router.js:25:67)
    at async Server.run (/Users/currentUser/Dev/myApp/react/node_modules/next/dist/next-server/server/next-server.js:68:1042)
    at async Server.handleRequest (/Users/currentUser/Dev/myApp/react/node_modules/next/dist/next-server/server/next-server.js:32:504) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
In production I get a 500 error. 
Here's the production server log:
```
2021-05-04T07:23:57.857868820Z [Error: ENOENT: no such file or directory, open '/app/.next/server/pages/[establishmentType]/[...id_name].html'] {
2021-05-04T07:23:57.857919268Z   errno: -2,
2021-05-04T07:23:57.857923377Z   code: 'ENOENT',
2021-05-04T07:23:57.857926595Z   syscall: 'open',
2021-05-04T07:23:57.857929825Z   path: '/app/.next/server/pages/[establishmentType]/[...id_name].html'
2021-05-04T07:23:57.857933187Z }
```
Any idea what's going on?

**Comment by ijjk** [comment] 2021-05-04 16:00
@alicerocheman can you provide a repo with a minimal reproduction where you are seeing the above logs occur?

**Comment by balazsorban44** [comment] 2022-01-28 09:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
