### ISSUE TITLE
Image doesn't work with basePath and assetPrefix

### ISSUE THREAD

**Issue by lavcraft** [vercel/next.js#21131] opened 2021-01-14 23:36 UTC
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

15.3.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

ssr app -> gitlab + docker + kubernetes

**Describe the Bug**

Image component build with incorrect url when basePath/assetPrefix defined

For /public/art/my-logo.svg:
Actual url: ```http://localhost:3000/ui/_next/image?url=%2Fart%2Fmy-logo.svg&w=2048&q=75``` 404
When i add /ui — ```http://localhost:3000/ui/_next/image?url=%2Fui%2Fart%2Fmy-logo.svg&w=2048&q=75``` 200

**Expected Behavior**

Image correctly handling assetPrefix/basePath

**To Reproduce**

1. Place a svg file into /public/art/my-logo.svg
2. Add 
```javascript
<Image src='/art/my-logo.svg' layout='fill'/>
```
3. Run app with next.config.js:
```javascript
basePath: '/ui/',
assetPrefix: `/ui/`,
```
No image displayed. But if i change src with prefix like below:
```javascript
<Image src='/ui/art/my-logo.svg' layout='fill'/>
```
It working.

I expect — Image handle basePath correctly. Or maybe i do sth wrong?

**Comment by kaykdm** [comment] 2021-01-15 02:13
> Asset prefix support does not influence the following paths:
 Files in the public folder; if you want to serve those assets over a CDN, you'll have to introduce the prefix yourself

https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix

**Comment by lavcraft** [comment] 2021-01-15 08:01
> > Asset prefix support does not influence the following paths:
> > Files in the public folder; if you want to serve those assets over a CDN, you'll have to introduce the prefix yourself
> 
> https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix

@kaykdm thanks for the answer. But i guess, that images processed in compilation process is a different case. Because in runtime image loaded not from static resources directly. Image loading from special `_/next/image?url=IMAGE_URL` script. In my opinion, this functionality can be more intuitive without any problem, but i can be wrong with this. 

Trying to understand - it's a bug or feature :) Thank you for discussion

**Comment by charlzyx** [comment] 2021-03-04 06:38
@lavcraft you are not alone, I have the same bug, and maybe reason is here.
`<Image >` will wrapper your src to request url `BASEPATH/_next/image?url=PATHINPUBLIC` and then in [Here: L217](https://github.com/vercel/next.js/blob/canary/packages/next/next-server/server/image-optimizer.ts#L217)

the router handler try the `url=PATHINPUBLIC` params as `href` by inner mock request, but **without basePath**, so it cannot resolve the image in public;

and pr maybe like this:

` href = url` -> ` href = (nextConfig.basePath || '') + url`

at [Here: L70](https://github.com/vercel/next.js/blob/canary/packages/next/next-server/server/image-optimizer.ts#L70)

and why not direct fix at [L217](https://github.com/vercel/next.js/blob/canary/packages/next/next-server/server/image-optimizer.ts#L217) here is because `href` was used by hash creator at  [L124](https://github.com/vercel/next.js/blob/canary/packages/next/next-server/server/image-optimizer.ts#L142) so shoule be fix early.

and i have a pr to fix this [https://github.com/vercel/next.js/pull/22759](https://github.com/vercel/next.js/pull/22759)

in other way, util vercel fix this, you can fix with client component like this

```tsx
import React from 'react';
import Image from 'next/image';

const basePath = process.env.NEXT_PUBLIC_BASE_PATH;

const ImageWithBasePath: typeof Image = (props) => {
  return <Image src={`${basePath || ''}${props.src}`} {...props}></Image>;
};

export default ImageWithBasePath;
```
export your basePath in env as NEXT_PUBLIC_BASE_PATH and replace the `import  Image form 'next/image'` by 'import Image from 'comppath''

**Comment by lavcraft** [comment] 2021-03-12 14:12
Wow. @charlzyx thank you for your work and explanation.
Really appreciate for it and waiting for release with your PR :)

**Comment by imansafari1991** [comment] 2021-06-26 08:36
Hi 
I have resolved this issue by following instructions;

next.config.js

`const isProd = process.env.NODE_ENV === "production";

module.exports = {
    images: {
        domains: ['XXX.XXXX.com']
     
      },
    assetPrefix: isProd ? '/fr' : '',

}`
 
I have defined a loader function :

 const myLoader = ({ src,height, width, quality }) => {
        return `${assetPrefix}/_next/image?url=${src}&w=${width}&h=${height}&q=${quality || 70}`
      }

This is worked for me!

**Comment by ijjk** [comment] 2021-07-21 03:09
Hi, as mentioned in https://github.com/vercel/next.js/issues/20097#issuecomment-752727883 it is currently required to pass the `basePath` to the `src` for `next/image`, using the loader solution mentioned above is a valid way to handle this automatically so I'm gonna close this as it doesn't appear to be a bug.

**Closed by ijjk** 2021-07-21 03:09 UTC
Labels: template: bug

**Comment by dustinlacewell** [comment] 2022-01-05 03:32
Why have a basePath setting then not respect it in your Image element?

**Comment by balazsorban44** [comment] 2022-02-04 04:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
