### ISSUE TITLE
prefetch in combination with i18n and next/link locale:false result in 404 of defaultLocale

### ISSUE THREAD

**Issue by dohomi** [vercel/next.js#19048] opened 2020-11-11 08:47 UTC
# Bug report

## Describe the bug

Use of i18n and defaultLocale returns in prefetched links in the defaultLocale to be 404 not found.

## To Reproduce

Use i18n and SSG mode the prefetched links inside of the default locale are wrong. 

## Expected behavior

The generated refetch URL is wrong, defaultLocale === en
```
/_next/data/Zs6ypKU6jWKL8TDFyfTqC/home.json
instead of:
/_next/data/Zs6ypKU6jWKL8TDFyfTqC/en/home.json
```
https://storyblok-mui-planettraining-dohomi.lumenmedia1.vercel.app/
## System information

- OS: every
- Browser every
- Version of Next.js: 10.0.1
- Version of Node.js: 12.x

## Additional context

It seems that the defaultLocale is missing the defaultLocale inside of the PATH of the generated prefetch data links

**Comment by ijjk** [comment] 2020-11-11 17:03
Hi, this sounds related to https://github.com/vercel/next.js/pull/18511 which is available in `v10.0.2-canary.8` of Next.js. Please upgrade to that version and give it a try!

**Comment by dohomi** [comment] 2020-11-12 02:17
@ijjk I updated to the latest canary.10. I updated the Endpoint:
https://storyblok-mui-planettraining-dohomi.lumenmedia1.vercel.app
as you can see it still fetches on the default locale `en` all prefetch links wrong, here an example:
https://storyblok-mui-planettraining-dohomi.lumenmedia1.now.sh/_next/data/0Opc5puLONZzrfcNKqz0y/support/faq.json
should be:
https://storyblok-mui-planettraining-dohomi.lumenmedia1.now.sh/_next/data/0Opc5puLONZzrfcNKqz0y/en/support/faq.json

My i18n setup is following:
```
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'de', 'it', 'es']
  },
```

**Comment by dohomi** [comment] 2020-11-17 09:34
@ijjk I tried with the newest iteration of canary.18 and the issue still persist. Let me know if I can somehow be of any help. Thanks!

**Comment by ijjk** [comment] 2020-11-17 15:50
This should be fixed after https://github.com/vercel/next.js/pull/19085 is landed

**Comment by ijjk** [comment] 2020-11-17 18:58
The above PR is available in `v10.0.2-canary.19` of Next.js, please update and give it a try!

**Comment by dohomi** [comment] 2020-11-18 01:45
@ijjk I gave the latest `canary.19` a go but still all defaultLocale pages result in 404. The defaultLocale is missing in the prefetch link.
```
https://storyblok-mui-etherhill-dohomi.etherhill.vercel.app/_next/data/HylSrNKN2WZr-w-CML3y2/work-projects-cluse.json
instead of:
https://storyblok-mui-etherhill-dohomi.etherhill.vercel.app/_next/data/HylSrNKN2WZr-w-CML3y2/en/work-projects-cluse.json
```

**Comment by ijjk** [comment] 2020-11-18 16:03
@dohomi can you provide a minimal reproduction where this is not working on the latest version of Next.js? We have tests covering this now [here](https://github.com/vercel/next.js/blob/ce5d9c858b70f647b532ec2f62ddde506af32b6a/test/integration/i18n-support-catchall/test/index.test.js#L193) and [here](https://github.com/vercel/next.js/blob/ce5d9c858b70f647b532ec2f62ddde506af32b6a/test/integration/i18n-support/test/shared.js#L42)

**Comment by dohomi** [comment] 2020-11-19 01:23
@ijjk I isolated the issue, the reason for the `404` is that I use `next/link` with the option `locale={false}`. I wanted to disable the locale because my CMS is already passing the locale in every request. With `locale={true}` the issue is resolved but would require additional coding that I don't end up with false `href`. I will update the title of this issue.

**Comment by dohomi** [comment] 2020-11-19 02:56
Currently I use this code to somehow tackle the current issue. But I am still investigating if it breaks links coming from my CMS
```js
const { locale, defaultLocale } = useRouter()
<NextLink
        {...props}
        locale={
          locale !== defaultLocale && !other.href.startsWith(`/${locale}`)
            ? false
            : locale
        }
      >
        <a ref={ref} {...other} />
      </NextLink>
```

**Comment by dohomi** [comment] 2020-11-19 07:06
<img width="1091" alt="Screenshot 2020-11-19 at 15 05 49" src="https://user-images.githubusercontent.com/489221/99632771-bff6d980-2a78-11eb-83ba-4d9beee52e67.png">

**Comment by ijjk** [comment] 2020-11-19 16:42
@dohomi in [this deployment](https://storyblok-mui-planettraining-dohomi.lumenmedia1.vercel.app/it/home) the correct prefetch link is being generated e.g. https://storyblok-mui-planettraining-dohomi.lumenmedia1.vercel.app/_next/data/JIeNl2403wuzTj-eXFov_/it/support.json as the locale always needs to be included in `_next/data` routes even with `locale={false}` provided on `next/link` as `locale={false}` just instructs the router to parse the locale from the provided `href`

It looks like your page is encountering a user error which you should see additional information in your function logs on the dashboard. 

I opened a PR ensuring this specific case is being tested in the i18n-support-catchall suite [here](https://github.com/vercel/next.js/pull/19322)

**Comment by dohomi** [comment] 2020-11-19 22:52
@ijjk the following url is the link to the `defaultLocale` support page. Basically the link on the `it` locale points to a page of `defaultLocale` because the page is not yet translated. Its not a user error more I just need to find a way how to deal with this specific `next/link`. Is it the developer duty to analyse every `href` and see if the correct locale is prepended? Because as `defaultLocale` does not prepend the `href` with the locale identifier I think it would make more sense if the `/_next/data/` prefetch link also don't include the `defaultLocale` in their `url` which would eliminate the `404 error` 

`it` version of this page does not exists but gets prefetched: 
https://storyblok-mui-planettraining-dohomi.lumenmedia1.vercel.app/_next/data/JIeNl2403wuzTj-eXFov_/it/support.json
`defaultLocale` exists:
https://storyblok-mui-planettraining-dohomi.lumenmedia1.vercel.app/_next/data/JIeNl2403wuzTj-eXFov_/en/support.json

**Comment by ijjk** [comment] 2020-11-19 23:02
@dohomi Ah ok I see the expected behavior now, thanks for the more verbose description. 

Currently the behavior when a locale isn't provided for `next/link` and it isn't able to parse it from the `href` it uses the currently active `locale` although with `locale={false}` it sounds like it would be more expected to use the `defaultLocale` when one isn't detected in the path

**Comment by dohomi** [comment] 2020-11-19 23:02
@ijjk another question is, in my example code I use `prefetch={shouldPrefetch}` where `shouldPrefetch===false` and I am not sure why the https://storyblok-mui-planettraining-dohomi.lumenmedia1.vercel.app/_next/data/JIeNl2403wuzTj-eXFov_/it/support.json is generated. Shouldn't the generation of `_next/data` be suppressed by the `prefetch={false}` statement?

**Comment by ijjk** [comment] 2020-11-19 23:07
The `_next/data` links are still loaded on hover, `prefetch={false}` disables prefetching when the item is in the viewport. See more related thread here https://github.com/vercel/next.js/pull/19299#issuecomment-730533444

**Comment by dohomi** [comment] 2020-11-19 23:08
@ijjk so you think this would be the best way to deal with the situation:
```js
const detectedLocale =
      locales?.find((l) => l === href.split('/')[1]) || defaultLocale
return (
  <NextLink
      href={href}
      locale={detectedLocale}
)
```

**Comment by dohomi** [comment] 2020-11-19 23:15
> @dohomi Ah ok I see the expected behavior now, thanks for the more verbose description.
> 
> Currently the behavior when a locale isn't provided for `next/link` and it isn't able to parse it from the `href` it uses the currently active `locale` although with `locale={false}` it sounds like it would be more expected to use the `defaultLocale` when one isn't detected in the path

I think for path based language handling it would be great if the fallback is `defaultLocale` instead of `locale`

**Comment by ijjk** [comment] 2020-11-20 00:59
The updated behavior for the fallback `locale` is now in https://github.com/vercel/next.js/pull/19322 and will be available after that is landed

**Comment by dohomi** [comment] 2020-11-20 01:02
Sounds great will try as soon its available in canary

**Closed** 2020-11-20 21:50 UTC
Labels: kind: bug, point: 2

**Comment by balazsorban44** [comment] 2022-01-29 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
