### ISSUE TITLE
Dev server is crashing and most API routes is unresponsive after updating to Next 12

### ISSUE THREAD

**Issue by hoodwink73** [vercel/next.js#32498] opened 2021-12-14 14:07 UTC
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Firefox, Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

I have a `.babelrc`,  so `swc` is disabled.
Feels like compile is taking more time than it did with Next 11 and then most APIs fail to respond and after around 2-3 mins `next dev` crashes with this

```
RangeError: Value undefined out of range for undefined options property undefined
    at Map.set (<anonymous>)
    at AsyncHook.init (domain.js:75:15)
    at PromiseWrap.emitInitNative (internal/async_hooks.js:199:43)
    at Promise.then (<anonymous>)
    at Promise.catch (<anonymous>)
    at Promise.promise.<computed> (~/project/.next/server/webpack-api-runtime.js:103:30)
    at ~/project/.next/server/webpack-api-runtime.js:91:52
    at Array.map (<anonymous>)
    at whenAll (~/project/.next/server/webpack-api-runtime.js:91:19)
    at Promise.promise.<computed> (~/project/.next/server/webpack-api-runtime.js:101:31)
```

When I dowgrade to NextJS 11, with an unchanged `next.config.js`, things work out fine.

Here is a snapshot of my. `next.config.js`

```
const { withSentryConfig } = require("@sentry/nextjs");

const {
  NODE_ENV,
  SENTRY_AUTH_TOKEN,
  VERCEL_GITHUB_COMMIT_SHA,
  NEXT_PUBLIC_SENTRY_PROJECT
} = process.env;

const SENTRY_ORG = "plum-mu";
const SENTRY_PROJECT = NEXT_PUBLIC_SENTRY_PROJECT || `plum-nextjs-pre-prod`;

const moduleExports = {
  productionBrowserSourceMaps: false,
  async headers() {
    return [
      {
        // matching all API routes
        source: "/api/:path*",
        headers: [
          {
            key: "Access-Control-Allow-Headers",
            value: "sentry-trace"
          }
        ]
      }
    ];
  },
  eslint: {
    // Warning: Dangerously allow production builds to successfully complete even if
    // your project has ESLint errors.
    ignoreDuringBuilds: true
  }
};

const SentryWebpackPluginOptions = {
  authToken: SENTRY_AUTH_TOKEN,
  ignore: ["node_modules"],
  include: ".next",
  release: VERCEL_GITHUB_COMMIT_SHA,
  org: SENTRY_ORG,
  project: SENTRY_PROJECT,
  silent: NODE_ENV === "production" ? false : true
};

module.exports = withSentryConfig(moduleExports, SentryWebpackPluginOptions);
```

### Expected Behavior

Dev server should run as it is running when on Next 11

### To Reproduce

I have not been able to reproduce outside of the vast context of my project.
But after looking at the error above, can anyone please guide towards a direction or any hint towards what might be happening.

**Comment by balazsorban44** [comment] 2021-12-14 17:20
Could you try disabling (temporarily remove from `next.config.js`) Sentry and see if that changes anything? Next 12 support in Sentry is ongoing as far as I am aware, and some of that might be related: https://github.com/getsentry/sentry-javascript/milestone/9

You can also try and make sure you are on the latest version of Sentry to see if anything has changed.

**Comment by hoodwink73** [comment] 2021-12-14 20:38
Did temporarily remove `next.config.js` now. But same problem persist. Some API routes are getting stuck. And after a while the error shared in the description occurs again.

**Comment by hoodwink73** [comment] 2022-01-09 13:59
I spent some time. While I was looking at some issues in the repo, I found this fix of turning off `esmExternals` in `next.config.js`

```
{
   experimental: {
      esmExternals: false
  }
}
```

This immediately fixed the issue – crashing of the app, apis taking 40s to load.

It would be nice to figure out which package is causing the problem? Is there a way to debug this?

**Comment by balazsorban44** [comment] 2022-01-11 12:22
Hard to tell without a log/reproduction. But you can try removing pages/code/packages in a binary search fashion, and you will end up with the broken package.

**Comment by iduartindigo** [comment] 2022-02-03 14:25
Getting same error. First I was getting a node memory heap error, I increased memory and I got this particular error.

`esmExternals: false` is not working for me, I get the following error 
`Module not found: ESM packages (lodash-es) need to be imported. Use 'import' to reference the package instead.`

<img width="1021" alt="Screen Shot 2022-02-03 at 8 54 50 AM" src="https://user-images.githubusercontent.com/87097472/152360581-bffe45b5-1fd7-4c6d-9682-a739b264fee1.png">

**Comment by balazsorban44** [comment] 2022-02-09 15:36
@iduartindigo @hoodwink73 are you using `next-transpile-modules` by any chance?

**Comment by iduartindigo** [comment] 2022-02-09 15:49
@balazsorban44 Yes, I'm using `next-transpile-modules`. 

In my case, this is now working fine after doing `esmExternals: false` and updating imports for some packages, for example:

changed this `import { VectorLayer } from '@indigo-ag/atlas-sdk';` to `import { VectorLayer } from '@indigo-ag/atlas-sdk/dist/esm/components/Map/layers/VectorLayer';`

**Comment by patroza** [comment] 2022-02-28 23:45
similar experience since upgrading some of my dependencies to ESM. we also use transpile modules in mono repo.

I noticed that the issue sort of exponentially get worse the more files you load which use these modules.
basically if I comment out enough imports, it works (but is very slow loading after compiled), if I comment back in a few, it breaks again. (it doesn't really matter which).
`esmExternals: false` is the saving grace.

can't provide a public repro atm.

**Comment by balazsorban44** [comment] 2022-03-01 00:33
I'm going to close this in favor of #32314 as it is suspiciously similar. Without a full reproduction, we cannot investigate further anyway. If you find anything interesting, please post it on the other issue, potentially linking back this where you come from. :+1: The greatest help is creating a repository that consistently produces the error, or at least has clear steps on how to induce one.

**Closed by balazsorban44** 2022-03-01 00:33 UTC
Labels: type: needs investigation, template: bug, area: Compiler
