### ISSUE TITLE
window.btoa is not a function

### ISSUE THREAD

**Issue by johnwunderfauks** [vercel/next.js#22711] opened 2021-03-03 08:14 UTC
### What version of Next.js are you using?

10.0.8-canary.13

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

Locally and on Vercel after we've experienced a weird issue whereby an <Image> tag doesn't refresh when routing on the same page.

After upgrading to latest next and also canary we're facing this issue.

event - compiled successfully
event - build page: /404
wait  - compiling...
event - compiled successfully
TypeError: window.btoa is not a function
    at toBase64 (D:\Projects\id21-cna\node_modules\next\dist\next-server\lib\to-base-64.js:3:122)
    at Image (D:\Projects\id21-cna\.next\server\pages\_app.js:3796:60)
    at processChild (D:\Projects\id21-cna\node_modules\react-dom\cjs\react-dom-server.node.development.js:3043:14)
    at resolve (D:\Projects\id21-cna\node_modules\react-dom\cjs\react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (D:\Projects\id21-cna\node_modules\react-dom\cjs\react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (D:\Projects\id21-cna\node_modules\react-dom\cjs\react-dom-server.node.development.js:3373:29)
    at renderToString (D:\Projects\id21-cna\node_modules\react-dom\cjs\react-dom-server.node.development.js:3988:27)
    at Object.renderPage (D:\Projects\id21-cna\node_modules\next\dist\next-server\server\render.js:54:851)
    at Function.getInitialProps (D:\Projects\id21-cna\.next\server\pages\_document.js:677:19)
    at Function.getInitialProps (D:\Projects\id21-cna\.next\server\pages\_document.js:1471:85)
    at loadGetInitialProps (D:\Projects\id21-cna\node_modules\next\dist\next-server\lib\utils.js:5:101)
    at renderToHTML (D:\Projects\id21-cna\node_modules\next\dist\next-server\server\render.js:54:1142)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async D:\Projects\id21-cna\node_modules\next\dist\next-server\server\next-server.js:109:97
    at async D:\Projects\id21-cna\node_modules\next\dist\next-server\server\next-server.js:102:142
    at async DevServer.renderToHTMLWithComponents (D:\Projects\id21-cna\node_modules\next\dist\next-server\server\next-server.js:134:387)
event - build page: /blog

next.config.js

const withImages = require('next-images')
const withVideos = require('next-videos')
const withTM = require('next-transpile-modules')(['react-spring', 'react-leaflet'])

const withPlugins = require('next-compose-plugins');
const nextConfig = {
  images: {
    deviceSizes: [320, 420, 768, 1024, 1200],
    iconSizes: [],
    domains: ['abc.xxx.com'],
    // path: '/_next/image',
    loader: 'default',
  },
  webpack: (config, options) => {
    //require('./utils/sitemap-commmon')
    // modify the `config` here
    return config;
  },
};

module.exports = withPlugins([
  // [withVideos(withImages(withTM()))],
  [withVideos(withImages(withTM()))],
  //[withVideos(withImages())]
  // your other plugins here
 
]);

### Expected Behavior

Project is live and running fine, on debugging first issue, this issue occurs.
Expected to be able to 'npm run dev' and 'npm run build' the site.
Occurs locally and on Vercel

### To Reproduce

Could provide git access to show the error.

![image](https://user-images.githubusercontent.com/20655113/109774546-71420980-7c3b-11eb-92b4-fd34c0fef4ca.png)

**Comment by arthurjdam** [comment] 2021-03-03 19:36
`window` is undefined during server-side generation. You could check `typeof window === undefined` inside the toBase64 method, load the component lazily, or generate it inside a useEffect

```javascript
import { toBase64 } from 'somewhere';

function Image({ sizerSvg }) {
  const [src, setSrc] = useState('');
  useEffect(() => {
    setSrc(`data:img/svg+xml;base64,${toBase64(sizerSvg)}`);
  }, []);
  return <img aria-hidden={true} role="presentation" src={src} />;
}
```

**Comment by marcin-piechaczek** [comment] 2021-03-06 23:51
You can use [Buffer](https://nodejs.org/api/buffer.html) node native API to make universal utility functions:

```js
/*
 * Check if global object window is defined
 */
export function isBrowser() {
  return typeof window !== 'undefined';
}

/*
 * Decode base64 value, returns string
 * @Params: string
 */
export function decodeValue(value) {
  if (!value) {
    return null;
  }

  const valueToString = value.toString();

  if (isBrowser()) {
    return btoa(valueToString);
  }

  const buff = Buffer.from(valueToString, 'ascii');
  return buff.toString('base64');
}

/*
 * Encode string, returns base64 value
 * @Params: string
 */
export function encodeValue(value) {
  if (!value) {
    return null;
  }

  const valueToString = value.toString();

  if (isBrowser()) {
    return atob(valueToString);
  }

  const buff = Buffer.from(valueToString, 'base64');
  return buff.toString('ascii');
}
```

**Comment by ijjk** [comment] 2021-04-28 03:14
Hi, I'm not able to reproduce this in the latest version of Next.js `v10.1.3` so I'm going to close this, if you're still having problems with this please respond with additional info and we can investigate further!

**Closed by ijjk** 2021-04-28 03:14 UTC
Labels: template: bug

**Comment by dolie** [comment] 2021-06-15 08:48
> 
> 
> You can use [Buffer](https://nodejs.org/api/buffer.html) node native API to make universal utility functions:
> 
> ```js
> /*
>  * Check if global object window is defined
>  */
> export function isBrowser() {
>   return typeof window !== 'undefined';
> }
> 
> /*
>  * Decode base64 value, returns string
>  * @Params: string
>  */
> export function decodeValue(value) {
>   if (!value) {
>     return null;
>   }
> 
>   const valueToString = value.toString();
> 
>   if (isBrowser()) {
>     return btoa(valueToString);
>   }
> 
>   const buff = Buffer.from(valueToString, 'ascii');
>   return buff.toString('base64');
> }
> 
> /*
>  * Encode string, returns base64 value
>  * @Params: string
>  */
> export function encodeValue(value) {
>   if (!value) {
>     return null;
>   }
> 
>   const valueToString = value.toString();
> 
>   if (isBrowser()) {
>     return atob(valueToString);
>   }
> 
>   const buff = Buffer.from(valueToString, 'base64');
>   return buff.toString('ascii');
> }
> ```

Hi,
Nice snippet that fit for SSR and client, but encode and decode are inverted : `encodeValue()` decodes, and `decodeValue()` encodes...

**Comment by balazsorban44** [comment] 2022-01-28 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
