### ISSUE TITLE
Built-In Global CSS Support Not working!

### ISSUE THREAD

**Issue by Melonendk** [vercel/next.js#29176] opened 2021-09-17 10:24 UTC
### What version of Next.js are you using?

11.1.2 Tested in canary to

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome 93.0.4577.82 

### What operating system are you using?

Windows

### How are you deploying your application?

Other platform

### Describe the Bug

Global CSS import in custom _app.js with either CSS or SASS cannot be importet

Even if you have a nextJS config 2 with sass options and added paths still same error

```node
(node:13500) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
error - ./public/css/globals.scss
Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
Location: pages\_app.js
```

### Expected Behavior

It should import the css or scss like every other time import the css or scss like normal but it fails completely

### To Reproduce

2 ways to do it manually or with `npx create-next-app`

Manually:
1. Create a new project with `npm init -y` in a test folder
2. Install NextJS `npm install -P next react react-dom`
3. Create the pages folder and create an `index.js` and `_app.js` file
4. In the Root of the project Create a scss file `styles.scss`
5. In the `index.js` file just simply create a hello world like so
```js
export default function Index() {
  return 'Hello World!';
}
```
6. In the `_app.js` use this:
```js
import '../styles.scss'

export default function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}
```
7. In the `styles.scss` use this:
```scss
body {
  background-color: slateblue;
}
```
8. Last open a console and run the dev application `npm run dev`

**Comment by timneutkens** [comment] 2021-09-17 11:36
Thanks for your report! This issue has been fixed on the canary (beta) release already. You can try it out by installing `next@canary`: `npm install next@canary`. Let us know how it goes 👍

**Closed by timneutkens** 2021-09-17 11:36 UTC
Labels: template: bug

**Comment by Melonendk** [comment] 2021-09-17 12:55
At the point of writeing aswell as tested on `11.1.3-canary.23` Its not fixed that current state. Will update once it is :)

**Comment by ijjk** [comment] 2021-09-17 14:25
Hi, I just double checked this locally and it appears to be working fine, can you confirm you are installing the latest Next.js version by running `yarn next --version` from the same directory you are seeing the error with `yarn next dev`?


https://user-images.githubusercontent.com/22380829/133799034-249025fc-e1f2-457d-a3e6-0185d2dbfc9c.mp4

**Comment by Melonendk** [comment] 2021-09-17 15:44
Upon further investigation i on my own pc at home it works fine now, maybe it was some caching even tho i cleared it to test. but anyway thanks for the response Keep up the great work! :)

**Comment by Melonendk** [comment] 2021-09-20 12:57
Its really a persisting issue 🤔 if its  coming back, and happeds, i did try reinstalling node and doing a complete run.

I have no clue to do next.

https://user-images.githubusercontent.com/30480143/134005158-46136031-3b34-4c8b-8e27-c097a1b58bb2.mp4

**Comment by ijjk** [comment] 2021-09-20 14:41
@Melonendk did you say this was happening on a specific Windows install or are you able to reproduce it on multiple? Also is this issue happening in other terminals e.g. command prompt instead of power shell?

**Comment by Melonendk** [comment] 2021-09-20 15:33
> @Melonendk did you say this was happening on a specific Windows install or are you able to reproduce it on multiple? Also is this issue happening in other terminals e.g. command prompt instead of power shell?

Seems to be a PC problem weird enough had cleared cache and reinstalled note but that does not seem to help tried running with yarn and another

**Comment by ijjk** [comment] 2021-09-20 15:40
@Melonendk did you trying clearing the yarn cache with `yarn cache clean`?

**Comment by Melonendk** [comment] 2021-09-20 15:48
@ijjk i haven't done that but i don't think its nessesary because i used npm before i even installed yarn, I'll have to try the tomorrow on the PC

**Comment by balazsorban44** [comment] 2022-01-27 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
