### ISSUE TITLE
Intercepting Routes do not close on navigation with `router.push` or `<Link>` in Next.js

### ISSUE THREAD

**Issue by hqw567** [vercel/next.js#62430] opened 2024-02-23 08:10 UTC
### Link to the code that reproduces this issue

https://github.com/hqw567/nextgram

### To Reproduce

1. Set up an Intercepting Route in a Next.js application.
2. Navigate to the page that triggers the Intercepting Route.
3. From the Intercepting Route, use `router.push('/')` or a `<Link href={'/'}>` element to navigate back to the home page.
4. Notice that the Intercepting Route does not close or unmount as expected.

https://github.com/vercel/next.js/assets/74847198/ec0a21cf-3d34-4c5d-9e64-4d53bf45c88e

### Current vs. Expected behavior

**Current Behavior:**
When navigating away from an Intercepting Route using `router.push('/')` or `<Link href={'/'}>`, the Intercepting Route's component does not unmount or close, leaving the Intercepting Route's state or UI still active or visible in the background.

**Expected Behavior:**
Upon navigating away from an Intercepting Route using either `router.push('/')` or a `<Link href={'/'}>`, the Intercepting Route's component should unmount and close properly, similar to how it behaves when using `router.back()`. This ensures a consistent and predictable navigation experience within Next.js applications.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro for Workstations
  Available memory (MB): 16070
  Available CPU cores: 12
Binaries:
  Node: 20.11.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.70 // Latest available version is detected (14.1.1-canary.70).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

**Comment by xvvvyz** [comment] 2024-02-24 06:57
Looks like you don't have a catch-all route in your @modal slot. Read:

https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#closing-the-modal

**Comment by ztanner** [comment] 2024-02-28 04:14
Hi - as mentioned by @xvvvyz, the catch-all route is the correct way to handle this, and the docs link provided above explains why it behaves this way. 

Going to close this out but don't hesitate to ask any follow-up questions if you have any :)

**Closed by ztanner** 2024-02-28 04:14 UTC
Labels: template: bug

**Comment by hqw567** [comment] 2024-02-28 06:55
> Hi - as mentioned by @xvvvyz, the catch-all route is the correct way to handle this, and the docs link provided above explains why it behaves this way.
> 
> Going to close this out but don't hesitate to ask any follow-up questions if you have any :)

Hi @ztanner,
I tried using the [catch-all route](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#closing-the-modal) you mentioned, but it didn't work at all.

**Comment by steve-marmalade** [comment] 2024-02-28 07:22
I am having the same issue - a modal (built using parallel + intercepted route) in my application is not closing on client-side navigation, even after adding the `[...catchAll]` route. Thanks for creating the repro @hqw567 .

One observation is that I have a seen a difference between `development` and `production` builds. When I downgrade @hqw567 's repro to `14.1.0` and do `next build && next start`, the navigation works as expected. But development mode doesn't work in `14.1.0`, and in the latest canary the navigation issue is present in both development and production builds.

**Comment by ztanner** [comment] 2024-02-28 16:03
Hi @hqw567 and @steve-marmalade -- since catch-all routes (`[...route]`) match everything _except_ the index route (ie, `/foo/bar`, `/foo/bar/baz`, but not /`foo`), and you're linking back to the root page, you'd ideally use an optional catch-all route here (`[[...route]]`). This would include the index route. However, parallel routes don't yet support optional catch-all segments (but it's being tracked [here](https://github.com/vercel/next.js/issues/61206)). 

In the meantime, you can work around this by having a `@modal/page.tsx` component that returns null. I tested that with your provided reproduction and it appears to have worked as you expect.

**Comment by steve-marmalade** [comment] 2024-02-28 19:06
@ztanner , thanks for the quick response and the additional context! unfortunately, this didn't immediately help me, since in my application I am routing to a non-index route and still seeing the modal stay open (which it sounds like should be covered by the regular `[...catchAll]` route).

I will try to modify the nextgram repo to see if I can easily reproduce.

**Comment by steve-marmalade** [comment] 2024-03-06 14:45
Hi @ztanner - should I create a new issue with the reproduction I shared above?

**Comment by ztanner** [comment] 2024-03-06 15:18
Hi @steve-marmalade -- a new issue would be helpful, thank you! It appears to function correctly with Turbopack (`--turbo`) so likely a bundling edge case that we need to fix for your particular setup.

**Comment by ztanner** [comment] 2024-03-06 16:58
That's correct, yes -- production builds are not yet supported. Thank you for creating the issue!

**Comment by steve-marmalade** [comment] 2024-03-08 05:35
@lhrinaldi - would you mind giving https://github.com/vercel/next.js/issues/62948 a :+1: if you think it's similar to the issue you are facing?

**Comment by MrOxMasTer** [comment] 2024-03-17 15:48
ожидали.



> Hi @hqw567 and @steve-marmalade -- since catch-all routes (`[...route]`) match everything _except_ the index route (ie, `/foo/bar`, `/foo/bar/baz`, but not /`foo`), and you're linking back to the root page, you'd ideally use an optional catch-all route here (`[[...route]]`). This would include the index route. However, parallel routes don't yet support optional catch-all segments (but it's being tracked [here](https://github.com/vercel/next.js/issues/61206)).
> 
> In the meantime, you can work around this by having a `@modal/page.tsx` component that returns null. I tested that with your provided reproduction and it appears to have worked as you expect.

I understand correctly that using Link:

![image](https://github.com/vercel/next.js/assets/59291123/2b098670-ad9b-4ccb-8fa2-3fae32180bcf)

There is no way we can close a window like "menu" in the header and it will always send us to a specific page. Is that the only way I understood router.back() to help?

**Comment by sejoalfaro** [comment] 2024-03-20 01:21
Recently I had the same problem and it was fixed using the` [...catchAll] `file directory. But I wonder if the default file is not enough to solve this? I tried with `default.tsx` but it dosent work. In my personal opinion, it doesn't look good to have a catchAll directory just for a modal to work on.
