### ISSUE TITLE
Yarn lint causes error: Cannot read property 'expression' of undefined

### ISSUE THREAD

**Issue by bigint** [vercel/next.js#27989] opened 2021-08-12 04:27 UTC
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

16.X

### What browser are you using?

Chrome

### What operating system are you using?

macOS and Windows

### How are you deploying your application?

Vercel and Netlify

### Describe the Bug

Yarn lint causes error: Cannot read property 'expression' of undefined after upgrading to the new version 11.1.0

![image](https://user-images.githubusercontent.com/69431456/129138171-7d364f12-d2dc-46dc-8d22-bbf1bc822483.png)

AFAIK it is point to all <img> tags

![image](https://user-images.githubusercontent.com/69431456/129138200-c1e12659-677d-48a2-900d-86059eed9abb.png)

CI output is here: https://gitlab.com/yo/devparty/-/jobs/1497531688

### Expected Behavior

Should not throw an error while linting

### To Reproduce

Not sure how to repro

**Comment by housseindjirdeh** [comment] 2021-08-12 13:26
Thanks for logging this. Thankfully it was reproducible :)

This is an [open issue](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/770) with the `role-supports-aria-props` rule in `eslint-plugin-jsx-a11y`. Combining conditional chaining with type assertion causes this error and I'm not sure why, but you have three options to resolve this until it gets fixed upstream:

- Remove the type assertion: <code>src={like?.node?.user?.profile?.avatar ~as string~}</code>
- Remove the conditional chaining: <code>src={like.node.user.profile.avatar as string}</code>
- Turn off the [rule](https://github.com/vercel/next.js/blob/canary/packages/eslint-config-next/index.js#L31) within your `.eslintrc` config: `"jsx-a11y/role-supports-aria-props": "off"`

Closing this, but please let me know if you're still seeing the issue after doing any of the above 🙏

**Closed by housseindjirdeh** 2021-08-12 13:26 UTC
Labels: template: bug

**Comment by bigint** [comment] 2021-08-12 14:23
Thanks @housseindjirdeh 🙏🏻  this is fixed 🎉

**Comment by balazsorban44** [comment] 2022-01-27 23:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
