### ISSUE TITLE
Add Auto Server Restart after saving changes in config file

### ISSUE THREAD

**Issue by piyushsi** [vercel/next.js#19400] opened 2020-11-21 18:11 UTC
# Add Auto Server Restart after saving changes in config file

**Comment by balazsorban44** [comment] 2020-11-21 20:17
Duplicate of #19268?

**Comment by timneutkens** [comment] 2020-11-22 11:19
Duplicate of #19268. Additionally always follow the issue template. Creating issues with one line of text is generally a bad idea.

**Closed by timneutkens** 2020-11-22 11:19 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-29 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
