### ISSUE TITLE
Nextjs Image component not working with img src file name with non English characters

### ISSUE THREAD

**Issue by yulev5** [vercel/next.js#30686] opened 2021-10-31 09:13 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

12.0.0

### What browser are you using?

chrome

### What operating system are you using?

windows

### How are you deploying your application?

vercel

### Describe the Bug

When using <Image /> component from NextJs it is working good as expected, only when file names are in English.
for example this code is working good:

```
import Image from 'next/image';
<Image alt="shark image" src="/images/shark.png" width={1000} height={1000} />
```

But when providing a src with filename that contain Hebrew letters the image is not loading, for example:

```
import Image from 'next/image';
<Image alt="shark image" src="/images/כריש.png" width={1000} height={1000} />
```

and the following error is shown:
error - TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
    at ServerResponse.setHeader (_http_outgoing.js:470:3)
    at setResponseHeaders (..\node_modules\next\dist\server\image-optimizer.js:442:13)

with network response of 
Status Code: 500 Internal Server Error

### Expected Behavior

Image will be loaded successfully also when using non English filenames

### To Reproduce

Use NextJs image component with a src filename with Some Hebrew letter, for example:
src="/כריש.png"
instead of
src="shark.png"

**Comment by brc-dd** [comment] 2021-10-31 10:14
Possible duplicate of #30285

**Comment by timneutkens** [comment] 2021-10-31 12:17
Yep sounds like a duplicate of #30285, thanks @brc-dd!

**Closed by timneutkens** 2021-10-31 12:17 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
