### ISSUE TITLE
500 INTERNAL_SERVER_ERROR using Next.js Images

### ISSUE THREAD

**Issue by Jonofat** [vercel/next.js#27739] opened 2021-08-03 18:43 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.4

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### How are you deploying your application?

Vercel

### Describe the Bug

I am using images from an api (headless WordPress) and I keep getting this weird intermittent issue. Sometimes it will just happen out of the blue and sometimes it will happen with a particular image. Basically the image does not show on the frontend and when I view the image path in console and open in a new browser I get the error along with an ID.

```
500: INTERNAL_SERVER_ERROR
Code: INTERNAL_UNEXPECTED_ERROR
ID: lhr1::xwssj-1628015491403-b1f6b19b3a68
```

If I view the url for the actual image where it is hosted it works fine, so it isn't like the image is missing or broken.

### Expected Behavior

Expect all images to display from https://api.mywebsite.com/...... and not only some

### To Reproduce

I have tried creating a custom endpoint in WordPress as well as using a wordpress GraphQL plugin with Apollo and they both give me the same result.

```
        <Image
          src={feature_image}
          alt="testimonials"
          layout="fill"
          className={styles.testimonial_image}
        />
```

I do have the url in my config file

```
  images: {
    domains: ["localhost", "api.mywebsite.com"],
  },
```

**Comment by styfle** [comment] 2021-08-04 15:06
Hi @Jonofat 

What is the URL for your website and what is the URL for your upstream image host? (I'm assuming its not api.mywebsite.com)

**Comment by Jonofat** [comment] 2021-08-05 18:09
Please don't close this yet. Before I respond with the details you are requesting I want to first remove the Wordpress GraphQl plugin and instead of using apollo for my http requests I am going to build a few of my own WordPress REST api endpoints and rather query the data that way and see if it makes a difference.

**Comment by styfle** [comment] 2021-08-05 19:42
Is the project hosted on Vercel?

You can [submit a support ticket](
https://vercel.com/support/request) with the deployment URL and we can take a look.

**Comment by robbienohra** [comment] 2021-08-06 03:09
I'm also experiencing a 500 internal server error for images in a production build mode but with a custom server in my case.

**Comment by Jonofat** [comment] 2021-08-06 05:17
Ah, so it isn’t just a headless WordPress thing then. It’s just weird for me because it isn’t all images, only some. And in some cases the images start off fine and when I check back days later, then some are broken. If you are also hosting a site on Vercel then maybe the issue is there. I updated my Next.js from v 10 to 11.0.1 hoping that would fix it but no joy.

**Comment by timmysmalls** [comment] 2021-08-10 21:50
Same here. Getting occasional 500s.

**Comment by ijjk** [comment] 2021-09-21 04:04
Closing as the initial issue seems to be due to an upstream server per https://github.com/vercel/next.js/issues/27739#issuecomment-894008030 and not a Next.js bug, if you are still experiencing issues with this in the latest version of Next.js `v11.1.2` and the upstream server is working please respond with additional info and we can investigate further!

**Closed by ijjk** 2021-09-21 04:04 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
