### ISSUE TITLE
Upgrading from 10.0.1 to 10.0.2 causes Error: Cannot find module 'babel-plugin-import'

### ISSUE THREAD

**Issue by nodeworks** [vercel/next.js#19641] opened 2020-11-29 00:38 UTC
# Bug report

## Describe the bug

Upgrading from Next 10.0.1 -> 10.0.2 causes dev to break:

```
error - /yarn/v6/npm-next-10.0.3-2bf9a1625dcd0afc8c31be19fc5516af68d99e80-integrity/node_modules/next/dist/client/next-dev.js
Error: Cannot find module 'babel-plugin-import' from '/usr/src/app'
```

Rolling back to 10.0.1 fixes the issue. Using Yarn PnP and yarn version 1.22.4.

babel-plugin-import is included in my package.json so it's not an issue with that.

## To Reproduce

1. Add babel-plugin-import
2. Add Next V10.0.2
3. Try to run next start and see if build fails

## Expected behavior

Expected next start to not fail

## System information

- OS: Mac Big Sur
- Version of Next.js: 10.0.2
- Version of Node.js: node:14.15.0-alpine (docker)
- Deployment: next start

**Comment by mrtnbroder** [comment] 2020-11-30 08:13
I'm having the exact same issue and was able to pinpoint this to this release: v10.0.2-canary.1, v10.0.2-canary.0 works fine still. I guess it has to do with the babel-inlining.

**Comment by mrtnbroder** [comment] 2020-11-30 09:32
Linking https://github.com/vercel/next.js/pull/19518 as a possible fix.

**Comment by merceyz** [comment] 2021-01-09 18:46
Fixed in https://github.com/vercel/next.js/pull/20586 (v10.0.5-canary.4)

> Using Yarn PnP and yarn version 1.22.4.

I'd strongly suggest using V2 for PnP https://yarnpkg.com/getting-started/migration

**Closed** 2021-01-11 13:06 UTC
Labels: kind: bug

**Comment by balazsorban44** [comment] 2022-01-28 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
