### ISSUE TITLE
Append local network address (stdout)

### ISSUE THREAD

**Issue by unigazer** [vercel/next.js#35312] opened 2022-03-14 18:45 UTC
### Describe the feature you'd like to request

If I were to spin up a new dev server with the command
```
npm run dev
```
I expect to be informed about the **network address where I can preview the app development on other devices**.

This would be an example of the output (taken from the [create-react-app](https://github.com/facebook/create-react-app) example. Something similar exists for Gatsby as well)
```
Local:            http://localhost:3000
On Your Network:  http://192.168.0.18:3000
```

I am referring to this part -> `On Your Network:  http://192.168.0.18:3000`.
This type of information is missing in the terminal output even though I can preview my Next.js app on other devices if I were to visit the "On Your Network" address on other devices.

Currently, when I start a local development server for the Next.js app, the only information I see in the terminal is
```
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
```

but it would be nice if the output in the terminal was something like this
```
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000, network: http://192.168.0.18:3000
```

As said, the "network" URL is already available and operational for the Next.js app development and I can preview the app on other devices, but the network URL information is not present in the terminal. My suggestion is to add that missing information when the local development server is started.

### Describe the solution you'd like

Add the missing "network" URL information in the terminal output when the local development server is started.

Example
```
Local:            http://localhost:3000
On Your Network:  http://192.168.0.18:3000
```

### Describe alternatives you've considered

/

**Comment by balazsorban44** [comment] 2022-03-16 10:57
This is a duplicate of #11367, there is also an open PR at #22352

**Closed by balazsorban44** 2022-03-16 10:57 UTC
Labels: template: story
