### ISSUE TITLE
ISG not working properly when page route has spaces and deployed through Vercel

### ISSUE THREAD

**Issue by illusionconnect** [vercel/next.js#27711] opened 2021-08-02 23:15 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.3.0

### What browser are you using?

Not relevant

### What operating system are you using?

Not relevant

### How are you deploying your application?

Vercel

### Describe the Bug

The incremental static generation is not working if the page route has white spaces in the name, like /news/head to head.
Looking in vercel function logs we can see that the revalidation request fails with the error.

```
ERROR	Invoke Error 	{"errorType":"TypeError","errorMessage":"Request path contains unescaped characters","code":"ERR_UNESCAPED_CHARACTERS","stack":["TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters","    at new ClientRequest (_http_client.js:148:13)","    at Object.request (http.js:46:10)","    at /var/task/now__bridge.js:125:32","    at new Promise (<anonymous>)","    at Bridge.launcher (/var/task/now__bridge.js:123:16)"]}
```

### Expected Behavior

Revalidation should work as the build time process and revalidate the page.

### To Reproduce

1. Deploy https://github.com/thiniulian/nextjs-whitespace-bug to vercel
2. Access the page <deployment>/page one
3. Refresh the page a few times
4. Observe the date not changing after all the refreshes
5. Go to functions log in vercel dashboard, refresh the deployed page and see the error

![image](https://user-images.githubusercontent.com/88301346/127934869-2e56f4e2-436d-4002-ae52-a3a5d6785da2.png)

**Comment by curly210102** [comment] 2021-08-03 02:08
Hi, the date not change because "getStaticPaths" executed in build-time, the date value is defineded with static file generated. The error in the dashboard seems throwed by vercel program.

If you want to refresh the date per request, you should use `getServerSideProps` or generate the date in Client-side.

**Comment by LetItRock** [comment] 2021-08-06 10:13
hi all! 
@curly210102, you've probably missed the `revalidate: 1` part in the `getStaticProps` which is re-generating the page created at the build time every 1s. 

@illusionconnect from what I do see is that might be a Vercel platform error because the local build works properly, but it doesn't when deploying it to the Vercel platform.

@leerob @timneutkens fyi

**Comment by curly210102** [comment] 2021-08-08 01:23
@LetItRock Yeah, I'v turly missed this solution🤣,  thx for reminding。

**Comment by kimcuong2407** [comment] 2021-08-12 17:48
Has this problem been fixed?
Currently, it is not a re-render page. I just have to build again

**Comment by ijjk** [comment] 2021-08-25 14:47
Hi, this should now be updated, please re-deploy your application and give it a try!

**Comment by ijjk** [comment] 2021-09-18 14:09
Closing as this should be resolved now per above.

**Closed by ijjk** 2021-09-18 14:09 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
