### ISSUE TITLE
i18n support is not compatible with next export. (SSR - NextJS 10)

### ISSUE THREAD

**Issue by lucasReghiniM** [vercel/next.js#20616] opened 2020-12-30 20:46 UTC
# i18n support is not compatible with next export.

## NextJS dont run the deploy with i18n

Im using nextJS 10, and the main reason that i choose next 10, is that i can do SSR and use the i18n.
 [Internationalized Routing](https://nextjs.org/docs/advanced-features/i18n-routing
) its a new next js 10 feature and have a page only to tha feature.

But when im gonna do a deploy, this error appears: **i18n support is not compatible with next export.**
Theres nothing about this in internationalized routing page.

### My code
**next.config.js**

```
const withImages = require('next-images')
const path = require('path')

module.exports = withImages({
    esModule: false,
    i18n: {
        locales: ['en-US', 'pt-BR', 'pt-PT', 'es-ES'],
        defaultLocale: 'pt-BR',
      },
});

```

I created a translate archive that make the condition with next router
obs: PT and EN are JSON files with text
```
import * as pt from "./pt";
import * as en from './en';
import { useRouter } from "next/router"

export const traducao = () =>{
  let routes = useRouter();

  let translate;
 
    if (routes.locale == 'pt-PT' || routes.locale == 'pt-BR') {
      translate = pt.default;
    } else {
      translate = en.default;
    }
  
  return translate 
}

```

And the i just use in my project like a function:

`{traducao().homeText.button_text}`

Work well, recognizes the browser language and switch.
Im using deploy script
```
npm run deploy
"deploy": "npm run clean && npm run build && next export -o dist/"
```

### Steps to reproduce

1. Go to 'next.config,js'
2. create the i18n export
3. create a Translate file that recognizes the browser language
4. import JSONs files with your site text
5. Use where you want
6. Try to deploy

## Expected behavior

Its just suppose to work fine and Deploy normal.

## Screenshots

![image](https://user-images.githubusercontent.com/47827740/103380122-aceb1680-4ac6-11eb-9178-e00c28092189.png)
![image](https://user-images.githubusercontent.com/47827740/103380129-b4aabb00-4ac6-11eb-92c7-3bad5ce75ec2.png)
![image](https://user-images.githubusercontent.com/47827740/103380140-bc6a5f80-4ac6-11eb-93b9-41af2f515768.png)
![image](https://user-images.githubusercontent.com/47827740/103380173-d4da7a00-4ac6-11eb-972f-9d6e58c68148.png)

## System information

- OS: Linux Ubuntu
- IDE: VSCode
- Version of Next.js: 10
- Version of Node.js: v15.3.0
- Deployment: next deploy

**Comment by ijjk** [comment] 2020-12-30 21:01
Closing as duplicate of https://github.com/vercel/next.js/issues/18318

**Closed by ijjk** 2020-12-30 21:01 UTC
Labels: template: bug

**Comment by lucasReghiniM** [comment] 2020-12-30 21:04
> Closing as duplicate of #18318

But no one came to a conclusion on this topic.
I18n is a new next function that is presented on next's own website, there should be documentation explaining this error. (well ... that error shouldn't even exist.)

**Comment by lucasReghiniM** [comment] 2020-12-30 21:05
I need to deploy this today, what can i do?

**Comment by lucasReghiniM** [comment] 2020-12-30 21:06
You just closed that issue report too

**Comment by ijjk** [comment] 2020-12-30 21:14
If you are deploying on a platform that supports Next.js like Vercel you do not need to call `next export` and will not encounter the error, also note calling `next export` disables pages from using `getServerSideProps` or other SSR features. `next export` support was not mentioned in the initial `i18n` RFC since `next export` is opting out of Next.js server routing support.

**Comment by lucasReghiniM** [comment] 2020-12-30 21:42
> If you are deploying on a platform that supports Next.js like Vercel you do not need to call `next export` and will not encounter the error, also note calling `next export` disables pages from using `getServerSideProps` or other SSR features. `next export` support was not mentioned in the initial `i18n` RFC since `next export` is opting out of Next.js server routing support.

I understand.
However I did not try to use the export.
I just used the deploy script (npm run deploy). This script already comes with the project.
What can I do to deploy without export.
I'm deploying through Debian, on a company server.

**Comment by lucasReghiniM** [comment] 2020-12-30 21:46
I just need the SSR working well with a good performance. In using NEXT JS to deal better with SEO.

**Comment by quyphan97** [comment] 2021-09-19 08:10
i had similar problem. can anyone tell me how to fix it?

**Comment by lucasReghiniM** [comment] 2021-09-19 21:12
> i had similar problem. can anyone tell me how to fix it?

Unfortunately not.
I had a big problem with this, and unfortunately after a lot of searching I couldn't find anyone who was able to solve it.

I think it's really bad that one of the main tools in NEXT doesn't support something that important. simply shameful

**Comment by quyphan97** [comment] 2021-09-21 04:14
@lucasReghiniM [fix error to issues 677](https://github.com/vinissimus/next-translate/issues/677)

**Comment by adrai** [comment] 2021-12-09 22:42
@lucasReghiniM you might have a look at: https://dev.to/adrai/static-html-export-with-i18n-compatibility-in-nextjs-8cd

**Comment by bakydev** [comment] 2022-01-26 21:06
> @lucasReghiniM you might have a look at: https://dev.to/adrai/static-html-export-with-i18n-compatibility-in-nextjs-8cd

Can anyone tell me if it works?

**Comment by adrai** [comment] 2022-01-26 21:24
> > @lucasReghiniM you might have a look at: https://dev.to/adrai/static-html-export-with-i18n-compatibility-in-nextjs-8cd
> 
> 
> 
> Can anyone tell me if it works? 

@bakydev for sure it works...
an example here: https://github.com/adrai/next-language-detector/tree/main/example

And a production example of localistars.com here: https://github.com/localistars/localistars-landing

**Comment by bakydev** [comment] 2022-01-26 21:30
> > > @lucasReghiniM you might have a look at: https://dev.to/adrai/static-html-export-with-i18n-compatibility-in-nextjs-8cd
> > 
> > 
> > Can anyone tell me if it works?
> 
> @bakydev for sure it works... an example here: https://github.com/adrai/next-language-detector/tree/main/example
> 
> And a production example of [localistars.com](https://localistars.com) here: https://github.com/localistars/localistars-landing

cool, I'm gonna try out, btw thank you for the fast answer

**Comment by poohia** [comment] 2022-02-16 13:51
Hello I show you my soluce with only i18n-js, I know is closed

```typescript
  // i18n.ts
  import i18n from "i18n-js";
  
  import en from "./en.json";
  import fr from "./fr.json";
  
  const localeEnable = ["fr", "en"];
  
  const fortmatLocale = () => {
    const { language } = window.navigator;
    if (language.includes("en")) return "en";
    if (language.includes("fr")) return "fr";
    if (!localeEnable.includes(language)) return "en";
  
    return "en";
  };
  // Set the key-value pairs for the different languages you want to support.
  i18n.translations = {
    en,
    fr,
  };
  // Set the locale once at the beginning of your app.
  i18n.locale = "en";
  
  const useTranslate = () => {
    return (t: string) => {
      if (typeof window !== "undefined") {
        i18n.locale = fortmatLocale();
      }
      return i18n.t(t);
    };
  };
  
  export default useTranslate;

  // home.tsx
  import useTranslate from "../locales/i18n";
  
  const t = useTranslate();
  
  return (<p>{t("idstring")}</p>)

```
