### ISSUE TITLE
React 17: Property expression of JSXExpressionContainer expected node to be of a type ["Expression","JSXEmptyExpression"] but instead got undefined

### ISSUE THREAD

**Issue by jakeherp** [vercel/next.js#18083] opened 2020-10-21 11:22 UTC
# Bug report

## Describe the bug

In a Next.js project using styled-jsx I get the following error across different components that create a <style jsx> tag to generate CSS selectors within template literals (or import such styles from a separate file):

```
Property expression of JSXExpressionContainer expected node to be of a type ["Expression","JSXEmptyExpression"] but instead got undefined
```
The error appears as soon as I update react and react-dom to 17.0.0 and might be related to the new JSX transform in React v17.

## Expected behavior

It renders the component as expected without any errors.

## System information

- OS: macOS Catalina
- Version of React: 17.0.0 
- Version of Next.js: 9.5.5
- Version of Node.js: 12.18.3
- Version of TypeScript: 4.0.3

**Comment by jakeherp** [comment] 2020-10-21 11:34
To add a bit more context: one component that shows the above-mentioned error is my Loader component. Removing `<style jsx>{...}</style>` altogether gets rid of the error:
```
const Loader = () => {
	return (
		<div>
			Loading ...
			<style jsx>{`
				div {
					background: red;
				}
			`}</style>
		</div>
	);
};

export default Loader;
```
(CSS is simplified here, but still throws the error for me)

**Comment by timneutkens** [comment] 2020-10-21 11:39
Just tried this and it seems to work correctly in a plain Next.js app. There's 2 things I would suspect causing this. The first is could you try to run `rm -rf .next/cache` as I'm wondering if this is caused by React 17 using a different transform but that not invalidating the cache right now.

The second would be more so a question, do you have a custom `.babelrc` or `babel.config.js` with additional plugins?

**Comment by jakeherp** [comment] 2020-10-21 12:01
Hi @timneutkens, I tried to reproduce it in a code sandbox, but wasn't able to get the same errors to appear, so not quite sure what else might affect this? I removed `.next/cache` and still get the same error.

My `.babelrc.js` looks like that:

```javascript
module.exports = {
	env: {
		production: {
			presets: ['next/babel'],
		},
		development: {
			presets: ['next/babel'],
		},
		test: {
			presets: [
				[
					'@babel/preset-env',
					{
						targets: {
							node: 'current',
						},
					},
				],
				[
					'next/babel',
					{
						'styled-jsx': {
							'babel-test': true,
						},
					},
				],
			],
			plugins: ['babel-plugin-dynamic-import-node'],
		},
	},
};
```

**Comment by timneutkens** [comment] 2020-10-21 12:08
Hmm so the babelrc has nothing special 🤔 except for the `@babel/preset-env` preset is not needed as `next/babel` has it built in. However you didn't mention this happens in the testing environment so seems unrelated.

**Comment by narciero** [comment] 2020-10-21 16:45
I'm having the same issue, removing my inline styles `<style jsx global>{...}</style>` from `_app.tsx` fixed it for me as well. I don't have a custom babel config, also tried running `rm -rf .next/`

**Comment by timneutkens** [comment] 2020-10-21 19:07
> I'm having the same issue, removing my inline styles `<style jsx global>{...}</style>` from `_app.tsx` fixed it for me as well. I don't have a custom babel config, also tried running `rm -rf .next/`

If you could put together a reproduction that'd be great 🙏

**Comment by message** [comment] 2020-10-22 10:07
Yeap, removing global styled-jsx fixes an error
```jsx
<style jsx global>{`
	@media (min-width: 900px) {
		.cjsx-1602028081713 > a:nth-child(5),
		.cjsx-1602028081713 > a:nth-child(6) {
			display:none !important
		}
	}
 `}
</style>
```

@narciero will you provide a reproduction repo?

**Comment by jakeherp** [comment] 2020-10-22 10:11
@message same here, tried to reproduce the error in a simplified version of my repo and can't reproduce the errors I'm getting, which made me think it might be a different dependency causing the problem, but we don't use anything related to styled-jsx that might be responsible for this error.

**Comment by message** [comment] 2020-10-22 11:48
Uhm, `rm -rf yarn.lock yarn-error.log node_modules/ build/ .next/ && yarn install && yarn dev` fixed my issue :thinking: @jakeherp

**Comment by jakeherp** [comment] 2020-10-22 13:21
I can confirm, that the error disappeared after removing `package-lock.json` in my case. Problem is therefore resolved for me and @message as it seems. @timneutkens do you want me to close this issue, or is this something worth investigating from your end?

**Comment by timneutkens** [comment] 2020-10-22 15:13
I'm just wondering what changed 🤔

**Comment by message** [comment] 2020-10-23 09:20
@timneutkens [nextjs-react17-error.zip](https://github.com/vercel/next.js/files/5428557/nextjs-react17-error.zip) here. I trimmed everything and left old yarn.lock.

**Comment by timneutkens** [comment] 2020-10-23 09:53
Thanks! We'll have a look after the conference.

**Comment by SemperFortis** [comment] 2020-10-30 13:13
This also seems to be occurring on Next 10, even after removing the package.json lockfile, node_modules, and .next directories completely (project using default babel config). After removing the `styled jsx`, it seems to work fine.

**Comment by brianshano** [comment] 2020-11-02 16:24
Upgrading NextJS 10 and React 17. 
Removing cache & build files didn't resolve it. 
I needed to remove `<style jsx global>` from my main layout.

**Comment by Timer** [comment] 2020-11-13 21:47
The provided reproduction is fixed on `next@canary`!

**Closed by Timer** 2020-11-13 21:47 UTC
Labels: kind: bug

**Comment by balazsorban44** [comment] 2022-01-29 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
