### ISSUE TITLE
Error on Router.back() after at least two window.history.pushState()

### ISSUE THREAD

**Issue by arso1er** [vercel/next.js#15482] opened 2020-07-25 23:00 UTC
# Bug report

## Describe the bug

When you do `window.history.pushState` at least twice successively on the same page and then `Router.back`, there is an error: `TypeError: Cannot read property 'indexOf' of undefined`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a next app: `yarn create next-app`
2. Start the dev server: `yarn dev`
3. On the home page, import `Router` and add the following two buttons: 
```
<button onClick={() => Router.back()}>back</button>
      <button
        onClick={() => {
          const state = { ts: Date.now() };
          const title = '';
          const url = '';
          window.history.pushState(state, title, url);
        }}
      >
        push
      </button>
```
4. In the browser, go to the home page, click at least twice on the push button, then click on the back button.
5. You'll see an error: **Unhandled Runtime Error
TypeError: Cannot read property 'indexOf' of undefined**

Note that the same error happens with `window.history.back()`

## Expected behavior

Expected to go back in history without error.

## System information

- OS: WSL on Windows 10
- Browser: Chrome
- Version of Next.js: 9.4.4
- Version of Node.js: 12.16.3

**Comment by Janpot** [comment] 2020-07-26 08:09
Should also be fixed by https://github.com/vercel/next.js/pull/15379

**Comment by timneutkens** [comment] 2020-07-26 10:15
Duplicate of ##15256

**Closed by timneutkens** 2020-07-26 10:15 UTC

**Comment by Timer** [comment] 2020-07-30 03:28
This was just fixed in 9.5.1, please upgrade!

**Comment by arso1er** [comment] 2020-07-30 15:47
Yes. The error is gone in 9.5.1. Thanks a lot.

**Comment by balazsorban44** [comment] 2022-01-29 19:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
