### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by dmudro** [vercel/next.js#24295] opened 2021-04-21 07:51 UTC
### What version of Next.js are you using?

10.0.9

### What version of Node.js are you using?

14.x

### What browser are you using?

Safari, Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Multiple locales in URL path should not be allowed. Given following i18n config:

```
...
i18n: {
  locales: ['en', 'sk', 'cs'],
  defaultLocale: 'sk',
},
...
```

The site allows following URL paths, returns 200 and renders:

http://localhost:3000/en/en
http://localhost:3000/en/sk
http://localhost:3000/en/cs
http://localhost:3000/cs/en
http://localhost:3000/sk/en
etc.

### Expected Behavior

Should return 404

### To Reproduce

Use the above i18n config or equivalent

**Comment by ijjk** [comment] 2021-04-28 01:14
Closing as a duplicate of https://github.com/vercel/next.js/issues/21210

**Closed by ijjk** 2021-04-28 01:14 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
