### ISSUE TITLE
Turbopack breaks with relay artifactDirectory

### ISSUE THREAD

**Issue by alex-statsig** [vercel/next.js#63454] opened 2024-03-19 08:28 UTC
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/relay-turbo-repro-2jvzlw?file=%2Fconsole%2Fcomponents%2FQueryRoot.tsx%3A5%2C9

### To Reproduce

1. Setup a nextjs project using relay with artifactDirectory set
2. Observe that all artifacts go to the *absolute* path specified via artifactDirectory (relative to the root of the project); running `next dev` after compiling relay works properly
3. Run `next dev --turbo` and observe the error about module not found

### Current vs. Expected behavior

Turbopack should support the artifactDirectory setting of relay as before. I'm not sure if this is an issue with turbopack x relay in particular, or an issue with the way the relay plugin generates the imports or what.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.2.0-canary.30 // Latest available version is detected (14.2.0-canary.30).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

As mentioned before, the repro code above seems to work fine when artifactDirectory is not set, so it seems like some issue with turbopack + the nextjs relay plugin only when this setting is set.

<sub>[PACK-2926](https://linear.app/vercel/issue/PACK-2926/turbopack-breaks-with-relay-artifactdirectory)</sub>

**Comment by timneutkens** [comment] 2024-03-20 17:28
Had a look at the linked reproduction but there's only an empty page in there and nothing related to a Relay setup 🤔

**Comment by alex-statsig** [comment] 2024-04-01 18:14
> Had a look at the linked reproduction but there's only an empty page in there and nothing related to a Relay setup 🤔

@timneutkens  I see the same myself, just tried regenerating the share link and confirmed it works in incognito, we'll see if this works:

https://codesandbox.io/p/devbox/relay-turbo-repro-2jvzlw?file=%2Fconsole%2Fcomponents%2FQueryRoot.tsx%3A5%2C9&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clty0jjov00073b6in8bw8idk%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clty0jjov00023b6i2my48fpo%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clty0jjov00043b6i6pqfi778%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clty0jjov00063b6i0lwtbeky%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clty0jjov00023b6i2my48fpo%2522%253A%257B%2522id%2522%253A%2522clty0jjov00023b6i2my48fpo%2522%252C%2522activeTabId%2522%253A%2522clty3scz503tn3b6igtib8058%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clty0psy200ix3b6i6gntck44%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fconsole%252Fcomponents%252FQueryRoot.tsx%2522%252C%2522id%2522%253A%2522clty3scz503tn3b6igtib8058%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A9%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A9%257D%255D%257D%255D%257D%252C%2522clty0jjov00063b6i0lwtbeky%2522%253A%257B%2522id%2522%253A%2522clty0jjov00063b6i0lwtbeky%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clty0jjov00053b6ifbkqfoix%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clty0jjov00053b6ifbkqfoix%2522%257D%252C%2522clty0jjov00043b6i6pqfi778%2522%253A%257B%2522id%2522%253A%2522clty0jjov00043b6i6pqfi778%2522%252C%2522activeTabId%2522%253A%2522clty3vlnp04cf3b6ixi8rjg3d%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clty0p8du00g93b6ir8hesx9y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clty0p8k900efdgglh7al1wc5%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clty3vlnp04cf3b6ixi8rjg3d%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by timneutkens** [comment] 2024-04-11 14:42
Looks like it works now indeed, thanks!

**Comment by mo-rally-dev** [comment] 2024-04-22 14:12
Hello, I just wanted to add that I am running into the same issue as well and it's keeping me from moving to Turbopack. 🙏

**Comment by alex-statsig** [comment] 2024-08-06 05:31
@timneutkens is there any update on the work to enable relay support, or anywhere to track progress? Feels like turbo support for relay must be mostly there, but this is a crucial piece. This is the main blocker for me using turbo, I've tried hackily getting rid of our artifactDirectory (which is not recommended per [docs](https://nextjs.org/docs/architecture/nextjs-compiler#relay) and makes the imports much messier, so not ideal) and everything else is working

**Comment by mischnic** [comment] 2024-08-08 14:46
@alex-statsig I just took your reproduction and upgraded to packages to
```
  "dependencies": {
    "next": "15.0.0-canary.108",
    "react": "19.0.0-rc-06d0b89e-20240801",
    "react-dom": "19.0.0-rc-06d0b89e-20240801",
    "react-relay": "17.0.0",
    "relay-runtime": "16.2.0"
  },
```
and the previous `Module not found: Can't resolve './client/lib/__generated__/QueryRootQuery.graphql.ts'` error is gone.

Could you also try upgrading to the latest Next canary? 
Otherwise I'd be happy to take a look at another reproduction if you still run into a relay problem.

**Comment by alex-statsig** [comment] 2024-08-08 20:38
Hey @mischnic, looks like this fixes it for me locally, thanks! Is it possible to include this fix on nextjs 14.x? Not sure when I can expect 15 to have a stable release, but will certainly update and use turbo once its out

**Comment by mischnic** [comment] 2024-08-09 07:54
Unfortunately not, but we want to do more Turbopack backports in the future which is feasible now after https://vercel.com/blog/turbopack-moving-homes.

**Closed** 2024-08-09 07:54 UTC
Labels: bug, Turbopack, linear: turbopack
