### ISSUE TITLE
NEXT_LOCALE cookie is being ignored

### ISSUE THREAD

**Issue by M1ck0** [vercel/next.js#22375] opened 2021-02-20 13:56 UTC
**What version of Next.js are you using?**

10.0.6

**What version of Node.js are you using?**

15.8.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Linux

**How are you deploying your application?**

yarn start

**Describe the Bug**

When using `i18n` feature of Next that is introduced in version 10 I don't want the language to be read from header.t

I saw in docs that `NEXT_LOCALE` cookie is perfect for my case

>Next.js supports overriding the accept-language header with a NEXT_LOCALE=the-locale cookie. This cookie can be set using a language switcher and then when a user comes back to the site it will leverage the locale specified in the cookie.
>
>For example, if a user prefers the locale fr but a NEXT_LOCALE=en cookie is set the en locale will be used instead until the cookie is removed or expired.

A cookie is being ignored, and no matter what I set in `NEXT_LOCALE` cookie it doesn't return it's value.

This works on version `10.0.0` of Next but, but it doesn't on anything above `10.0.*`

**Expected Behavior**

The locale should be read from the cookie.

**To Reproduce**

1. Create a new project.
2. Set the `NEXT_LOCALE` cookie on a value that you want
3. Try to read locale value from `useRouter` or on server-side from `context`

**Comment by slevy85** [comment] 2021-02-21 13:29
The cookie NEXT_LOCALE is only used when you load the application from the root path `/`, else Next will use the locale that is in the path.
In other words, whatever NEXT_LOCALE value is, it will be ignored if you are not landing on `/`.

Does it answer your question ?

And to access the cookie you don't need useRouter but `document.cookie` or if in the request `req.cookies.NEXT_LOCALE`.

**Comment by M1ck0** [comment] 2021-02-22 08:45
> The cookie NEXT_LOCALE is only used when you load the application from the root path `/`, else Next will use the locale that is in the path.
> In other words, whatever NEXT_LOCALE value is, it will be ignored if you are not landing on `/`.
> 
> Does it answer your question ?
> 
> And to access the cookie you don't need useRouter but `document.cookie` or if you are server-side you can have it in the request `req.cookies.NEXT_LOCALE`.

Hello, thanks for your answer.

This does not answer my question. As I stated in the issue

> This works on version 10.0.0 of Next but, but it doesn't on anything above 10.0.*

This does not work in the version above `10.0.0`. I even tried to create a clean new project and the issue still presists.

**Comment by M1ck0** [comment] 2021-02-25 19:50
bump?

**Comment by leerob** [comment] 2021-03-04 14:19
> The cookie NEXT_LOCALE is only used when you load the application from the root path /, else Next will use the locale that is in the path.

We've updated the documentation to reflect this better, thank you!

> This does not work in the version above 10.0.0. I even tried to create a clean new project and the issue still persists.

I was unable to reproduce. Please attach a CodeSandbox with a reproduction, and I'm happy to investigate this further. Thank you!

Closing as addressed with https://github.com/vercel/next.js/pull/22736 🙏

**Closed by leerob** 2021-03-04 14:19 UTC
Labels: template: bug

**Comment by M1ck0** [comment] 2021-03-05 09:20
@leerob 

Here is a git repo with a reproduction.

https://github.com/M1ck0/next-locale-test

As you can see, when `console.log(router)` is printed it shows `me` as a locale (the default one) even though `NEXT_COOKIE` is being set on `en` after the button click.

This works fine on `next@10.0.0`.

**Comment by kristijorgji** [comment] 2021-09-13 16:19
This is not working in next 11.0 also, NEXT_LOCALE is being ignored. Any update on this?

**Comment by pgmanutd** [comment] 2021-09-24 18:11
Not sure about actual issue. But in my case browser caching was messing up. I did some redirections from `/` to `/home` and same page (with default locale) was getting served from cache. Status was: `Status Code: 308 Permanent Redirect (from disk cache)`. I disabled the cache in the browser network tab and it worked. Still figuring out how I can avoid this cached redirection.

**Comment by balazsorban44** [comment] 2022-01-27 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
