### ISSUE TITLE
Redirect to lower case - never complete

### ISSUE THREAD

**Issue by BernardA** [vercel/next.js#26171] opened 2021-06-16 07:58 UTC
### What version of Next.js are you using?

10.12.3

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS

### How are you deploying your application?

npm run dev

### Describe the Bug

Redirect uppercase route to lowercase causes browser error: 
Firefox: 

> The page isn’t redirecting properly

> Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

A similar error is thrown on Chrome.

I have legacy uppercase routes that need redirect to lowercase one.

I first filed [this issue](https://github.com/vercel/next.js/issues/25586) to solve it globally.

Waiting for that one I was attempting to solve it manually for each specific route, which would give a very long `next.config` but so it would be.

This is one instance of redirect: 

              {
                source: '/marques-voiture/Audi',
                destination: '/marques-voiture/audi',
                permanent: true,
            },

So BEFORE adding the redirect:

1 - attempting to reach `/marques-voiture/audi` will work fine
2 - attempting to reach `/marques-voiture/Audi` will throw 404

AFTER adding the redirect above:

attempting to reach both routes will throw the redirect error on the browser

Note that I do have other redirects that work fine like these:

            {
                source: '/prix-voiture/(.*)',
                destination: '/prix-budget-voiture',
                permanent: true,
            },
            {
                source: '/segmentes-automobile/:segment(.*)',
                destination: '/segments-automobile/:segment',
                permanent: true,
            },
            {
                source: '/comparatif-voiture/(.*)',
                destination: '/comparateur-voiture',
                permanent: true,
            },

### Expected Behavior

Should redirect properly

### To Reproduce

See code above added to `next-config.js`

**Comment by ijjk** [comment] 2021-09-19 05:38
Closing as a duplicate of https://github.com/vercel/next.js/issues/25586

**Closed by ijjk** 2021-09-19 05:38 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
