### ISSUE TITLE
`next lint` does not work with `src` directory

### ISSUE THREAD

**Issue by brandonpittman** [vercel/next.js#26155] opened 2021-06-16 01:02 UTC
### What version of Next.js are you using?

11

### What version of Node.js are you using?

16.3

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

If you run `next lint` when storing your code in a `src` directory, the CLI complains that there is no `/components` directory.

This also means that `next build` fails when using the ESLint config.

```
> site@1.6.0 build
> next build

info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types

> Build error occurred
Error: No files matching '/Users/blp/Sites/site/components' were found.
    at FileEnumerator.iterateFiles (/Users/blp/Sites/site/node_modules/eslint/lib/cli-engine/file-enumerator.js:317:27)
    at iterateFiles.next (<anonymous>)
    at CLIEngine.executeOnFiles (/Users/blp/Sites/site/node_modules/eslint/lib/cli-engine/cli-engine.js:765:48)
    at ESLint.lintFiles (/Users/blp/Sites/site/node_modules/eslint/lib/eslint/eslint.js:530:23)
    at lint (/Users/blp/Sites/site/node_modules/next/dist/lib/eslint/runLintCheck.js:2:1752)
    at async Object.runLintCheck (/Users/blp/Sites/site/node_modules/next/dist/lib/eslint/runLintCheck.js:8:8) {
  type: 'NoFilesFoundError',
  messageTemplate: 'file-not-found',
  messageData: { pattern: '/Users/blp/Sites/site/components', globDisabled: false }
}
```

### Expected Behavior

`next lint` should look inside a `src` directory.

### To Reproduce

Create a Next project, move source code into a `src` directory, and run `npx next lint`.

**Comment by brandonpittman** [comment] 2021-06-17 00:01
@vasco3 I had an empty `/components` folder left over in root that was causing the conflict. I deleted the erroneous `/components` folder and things started to work as normal! 😄

**Comment by ranisalt** [comment] 2021-06-17 08:05
I still think this is a bug. Why is it completely breaking when an empty folder is found, instead of just proceeding to the next files?

**Comment by n3oney** [comment] 2021-07-07 22:48
I agree with @ranisalt, and the same just happened to me. Had an empty /components folder, same error produced. This is definitely a bug!

**Comment by timneutkens** [comment] 2021-07-08 19:10
I'm going to re-open this as I've found the root cause and fixed it in #26915, can be ported into a separate PR though.

**Comment by housseindjirdeh** [comment] 2021-07-14 15:08
Fix is in #27119 which will likely be merged before #26915

**Closed** 2021-07-16 18:19 UTC
Labels: kind: bug

**Comment by ijjk** [comment] 2021-07-19 23:40
Hi, this has been updated in `v11.0.2-canary.17` of Next.js, please update and give it a try!

**Comment by balazsorban44** [comment] 2022-01-28 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
