### ISSUE TITLE
Next App api-routes-apollo-server-and-client-auth fail on build

### ISSUE THREAD

**Issue by LadyDzidzor** [vercel/next.js#10786] opened 2020-03-02 14:12 UTC
# Bug report
NEXTJS Examples api routes and apollo not working on build
https://github.com/zeit/next.js/tree/canary/examples/api-routes-apollo-server-and-client-auth

## Describe the bug
The examples project does not login user after I run `next build`
The JWT token is created and signed, but the error seems to happen when it calls

```js
  context.res.setHeader(
          'Set-Cookie',
          cookie.serialize('token', token, {
            httpOnly: true,
            maxAge: 6 * 60 * 60,
            path: '/',
            sameSite: 'lax',
            secure: process.env.NODE_ENV === 'production',
          })
        )
```

The token isn't signed on the browser head, which makes login to fail in production

## To Reproduce
Create a nextjs boilerplate using https://github.com/zeit/next.js/tree/canary/examples/api-routes-apollo-server-and-client-auth
the example here 

run `npm run build`. then run `npm start`
Navigate to http://localhost:3000 - and try to create an account and login

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Chrome]
- Browser (if applies) [e.g. chrome,]
- Version of Next.js: [e.g. 9.]

**Comment by rafaelalmeidatk** [comment] 2020-03-02 14:27
Are you using `https` when testing on localhost? The `secure` flag will be `true` when running the production build, so the cookie won't be set if you are using `http`

**Comment by goranovs** [comment] 2020-03-04 21:52
Maybe not related but `api-routes-apollo-server-and-client-auth` also does not work when deployed on **Now** where `https` is available. Error 500 is returned instead.

**Comment by rbelow** [comment] 2020-03-07 17:44
Hello everyone! Thanks for reporting this issue, @LadyDzidzor . Please remove the default template text from the issue description, it makes it easier to localize the issues important information ([more signal](https://dzone.com/articles/whats-your-signal-noise-ratio)).

Is somebody working on it?

**Comment by djanda97** [comment] 2020-03-31 22:16
> Maybe not related but `api-routes-apollo-server-and-client-auth` also does not work when deployed on **Now** where `https` is available. Error 500 is returned instead.

I was unable to replicate this bug when I deployed on Now. The behavior worked as expected.

**Comment by djanda97** [comment] 2020-03-31 22:31
@LadyDzidzor Since running `npm run build` before `npm start` sets process.env.NODE_ENV to 'production', the secure property is set to true meaning that the cookie would only be sent using https. During development, use `npm run dev` to start the application, as this will set the secure property to false allowing you to try the example as intended on localhost. I hope this helps.

-David

**Comment by JanKaifer** [comment] 2022-11-24 09:33
This issue is super old and it looks like it might have been already resolved.
I'll close it but please open a new issue if you think that this is still relevant.

**Closed by JanKaifer** 2022-11-24 09:33 UTC
Labels: good first issue
