### ISSUE TITLE
Next11-12, custom app.ts error

### ISSUE THREAD

**Issue by nnnnnnnnnni** [vercel/next.js#36465] opened 2022-04-26 04:23 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

 Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64
    Binaries:
      Node: 16.3.0
      npm: 7.15.1
      Yarn: 1.22.11
      pnpm: N/A
    Relevant packages:
      next: 12.1.5
      react: 18.0.0
      react-dom: 18.0.0

### What browser are you using? (if relevant)

chrome 100.0.4896.127

### Describe the Bug

Deleted node_moules and yarn , because i want to get a lastest yarn.lock.
then i touch the error.
<img width="916" alt="image" src="https://user-images.githubusercontent.com/24198845/165220219-93776592-6695-4c09-9046-bf97beae6f0a.png">
this error info show in "Component" component in _app.ts, which is my custiom app.ts.
and i got "Component" component by this.
<img width="376" alt="image" src="https://user-images.githubusercontent.com/24198845/165220329-d78ded75-e665-4734-853a-527193dff798.png">
and i use "Component" component behind.
<img width="266" alt="image" src="https://user-images.githubusercontent.com/24198845/165220385-cec7538b-25e8-48d8-84de-423eeda60dc4.png">
i try to update next.js version but useless

### Expected Behavior

i need to pass build action ,so i want to resolve this error

### To Reproduce

<img width="935" alt="image" src="https://user-images.githubusercontent.com/24198845/165220729-fcb7592b-f9f0-46ac-82b8-1c699d2df3fb.png">

**Comment by MedzikUser** [comment] 2022-04-26 18:19
I have the same issues

**Comment by MedzikUser** [comment] 2022-04-26 18:21
![err](https://cdn.magicuser.cf/DRSOwLA.png)
![code](https://cdn.magicuser.cf/q08PXDZ.png)

**Comment by balazsorban44** [comment] 2022-04-28 11:06
The reported issues here are coming from upstream/third-party libraries, and are not related to Next.js. These should be reported on the respective repositories.

Some useful links:

- [Suggestions from Twitter](https://twitter.com/dan_abramov/status/1512833611401150474) by Dan Abramov
- https://github.com/facebook/react/issues/24304#issuecomment-1094565891
- [DefinitelyTyped `react` issues/PRs since React 18 types have been merged](https://github.com/DefinitelyTyped/DefinitelyTyped/issues?q=created%3A%3E%3D2022-04-07+react+) (follow this, your lib might add a fix if it's on DefinitelyTyped)


I'm closing this for now. If you still think there is a problem with Next.js itself, please provide a reproduction in a new issue so we can look more into it.

**Closed by balazsorban44** 2022-04-28 11:06 UTC
Labels: template: bug, area: TypeScript, React 18
