### ISSUE TITLE
getServerSideProps not trigger in _app

### ISSUE THREAD

**Issue by bluelovers** [vercel/next.js#18239] opened 2020-10-26 06:34 UTC
# Bug report

## Describe the bug

getServerSideProps not trigger in _app

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by rokinsky** [comment] 2020-10-26 11:50
As far as I know, this has been disabled on purpose.

**Comment by jamesmosier** [comment] 2020-10-26 13:18
Please provide a complete issue template with description, reproduction, and all other sections filled out.

**Comment by tiagooliveira08** [comment] 2020-10-26 17:39
please @jamesmosier look this issue https://github.com/vercel/next.js/issues/18125

**Comment by timneutkens** [comment] 2020-10-28 13:56
Duplicate of #10949

**Closed by timneutkens** 2020-10-28 13:56 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
