### ISSUE TITLE
image optimizer

### ISSUE THREAD

**Issue by matheuskousen** [vercel/next.js#19104] opened 2020-11-12 15:23 UTC
my images are not work on my landing page when i do a upload to my host 

look at => http://soundlineventos.me/

i'm building as static

"build": "next build && next export", this my way to build in production

**Comment by Timer** [comment] 2020-11-12 15:52
This has been fixed in canary. You cannot use `next export` with the default image optimizer.

See:
https://github.com/vercel/next.js/blob/canary/errors/export-image-api.md

**Closed by Timer** 2020-11-12 15:52 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-29 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
