### ISSUE TITLE
Type definitions file getting overwritten on build and dev 

### ISSUE THREAD

**Issue by azzazkhan** [vercel/next.js#26622] opened 2021-06-26 09:26 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome version 91.0.4472.114 (Official Build) (64-bit)

### What operating system are you using?

Windows 10 Home (64-bit)

### How are you deploying your application?

next dev/next build

### Describe the Bug

When running `next build` or `next start` the configured `next-env.d.ts` gets overwritten and all configurations are removed. I'm using the [next-page-transitions](https://www.npmjs.com/package/next-page-transitions) package to add transition effects on navigation but when I import the package typescript yells that **no type definitions found** for package `next-page-transitions`.

To solve this I added custom type declarations for the `next-page-transitions` and `.svg` files, by doing so my `next-env.d.ts` files looks like this.

```typescript
/// <reference types="next" />
/// <reference types="next/types/global" />
/// <reference types="next/image-types/global" />

declare module "next-page-transitions";

declare module "*.svg" {
  content: string;
  export default content;
}
```

But when I run `next build` or `next dev` commands it overwrites my `next-env.d.ts` file to this
```typescript
/// <reference types="next" />
/// <reference types="next/types/global" />
/// <reference types="next/image-types/global" />
```

BTW I'm using the yarn package manager and using the `yarn run dev` and `yarn run build` commands. Due to this bug, I have to rewrite the file every time I need to start the server.

### Expected Behavior

Should not overwrite the type declaration file.

### To Reproduce

Just initialize a new Next.js project with `yarn create next-app --typescript` and add type declarations for packages in `next-env.d.ts` file or follow up using [this repository](https://github.com/azzazkhan/next-typedef-bug.git)

**Comment by ijjk** [comment] 2021-06-26 15:58
Closing as a duplicate of https://github.com/vercel/next.js/issues/26560

**Closed by ijjk** 2021-06-26 15:58 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 05:04
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
