### ISSUE TITLE
Public files not accessible on i18n domains

### ISSUE THREAD

**Issue by RobVermeer** [vercel/next.js#54765] opened 2023-08-30 09:42 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.2.0
      npm: 9.6.4
      Yarn: 1.22.19
      pnpm: 8.7.0
    Relevant Packages:
      next: 13.4.20-canary.12
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Internationalization (i18n), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://app.replay.io/recording/reproduction--e17b7c87-6019-40b2-b719-1e9b9ce80b13

### To Reproduce

- Create new next app
- Add robots.txt in public folder
- Setup basic i18n (see example below)
- Make sure you are on different domains (as example)
- Go to default domain `/robots.txt`
- See the robots.txt output
- Go to different domain `/robots.txt`
- See 404

```js
  i18n: {
    defaultLocale: "en",
    locales: ["en", "nl-NL"],
    domains: [
      {
        domain: "com.rob.ticketswap.pizza",
        defaultLocale: "en",
        http: false,
      },
      {
        domain: "nl.rob.ticketswap.pizza",
        defaultLocale: "nl-NL",
        http: false,
      },
    ],
    localeDetection: false,
  },
```

### Describe the Bug

This bug presented itself specifically in Next v13.

Public files are no longer accessible on all domains that are not the default domain (default locale domain).

### Expected Behavior

All files in public folder should be accessible on every domain that is setup in the i18n config.

**Comment by cosieLq** [comment] 2023-09-04 10:29
I haven't checked the reproduction but it seems to me similar to #54159

**Comment by michalpulpan** [comment] 2023-09-05 12:46
@RobVermeer 

I'm encountering a the same issue 😞. I stumbled upon this GitHub issue after creating local "minimal" example. Since I'm using [next-translate-routes](https://github.com/hozana/next-translate-routes/tree/master) in my project I thought it's caused by mentioned library. Instead, it seems to be a bug within Next.js itself.

Have you tried alternative approaches to handle locale domain routing, perhaps using middleware or other methods?

**Comment by RobVermeer** [comment] 2023-09-07 10:29
> I don't want to jump to conclusions, but it seems to me that `next@13.4.12` is the last version where this issue isn't present.

In another project we also have an issue in the latest version, going back to `next@13.4.12` fixes that (thanks for the tip @michalpulpan!).

In that project client side routing didn't work anymore, since `getServesideProps` wasn't called anymore.

I haven't looked into what could have cause all these issues, but it seems something with routing is going on that breaks multiple things.

**Comment by jonathandsouza** [comment] 2023-09-07 19:44
I am facing similar problems with images in the public dir. Any solutions other than dropping the version to 13.4.12?

**Comment by dowrow** [comment] 2023-09-12 10:01
I found the same bug on version 13.2.1 
Fixed it by upgrading next package version to 13.4.12

**Comment by arielvieira** [comment] 2023-10-20 05:33
Having the same issue with the latest versions of next (`13.5.4`, `13.5.5` and `13.5.6`)

I managed to fix this for now by patching the next package with the solution of this [PR ](https://github.com/vercel/next.js/pull/55137)

```diff
diff --git a/node_modules/next/dist/server/lib/router-utils/filesystem.js b/node_modules/next/dist/server/lib/router-utils/filesystem.js
index 635fcdc..f56164e 100644
--- a/node_modules/next/dist/server/lib/router-utils/filesystem.js
+++ b/node_modules/next/dist/server/lib/router-utils/filesystem.js
@@ -348,7 +348,7 @@ async function setupFsCheck(opts) {
                 let locale;
                 let curItemPath = itemPath;
                 let curDecodedItemPath = decodedItemPath;
-                const isDynamicOutput = type === "pageFile" || type === "appFile";
+                const isDynamicOutput = type === 'pageFile' || type === 'appFile' || type === 'publicFolder'
                 if (i18n) {
                     const localeResult = handleLocale(itemPath, // legacy behavior allows visiting static assets under
                     // default locale but no other locale

```

**Comment by erwanriou** [comment] 2023-10-25 11:44
same here... That would be nice to fix it.

**Comment by erwanriou** [comment] 2023-10-25 12:48
the current fix that i managed to do is that instead of having the `robots.txt` at the public folder. i generate it within the `pages` folder as `robots.txt.js` with the following content:

```js
const RobotsTxt = () => {}

export const getServerSideProps = async ({ res }) => {
  // GENERATE ROBOT DATA
  const robotsTxtData = `User-agent: *\nAllow: /`

  res.setHeader("Content-Type", "text/plain")
  res.write(robotsTxtData)
  res.end()

  return { props: {} }
}

export default RobotsTxt
```

this way it work with any version of nextjs, localisation and also whenever you have a first level programatical route such as `/pages/[slugs]` that could conflict with the robots.txt

**Comment by goguda** [comment] 2023-10-26 20:35
Having this problem as well! For example, [https://www.iroomit.com/fonts/Crimson_Pro/CrimsonPro-Bold.woff2](https://www.iroomit.com/fonts/Crimson_Pro/CrimsonPro-Bold.woff2) is accessible, but [https://www.iroomit.co.uk/fonts/Crimson_Pro/CrimsonPro-Bold.woff2](https://www.iroomit.co.uk/fonts/Crimson_Pro/CrimsonPro-Bold.woff2) is not...

**Comment by enmielado** [comment] 2023-11-01 18:02
Having the same issue. Public folder files are only accessible from the top-level defaultLocale (i18n.defaultLocale).

**Comment by ovionlogis** [comment] 2023-11-03 06:39
I have the same issue in NextJS up to latest version `14.0.1`, in dev mode this is not so important, but for production builds via `docker` I wrote this fix in the `Dockerfile`. It involves copying the public directory into a locale subdirectory
Original `Dockerfile` [https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile](https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile)
```Dockerfile
...
COPY --from=builder /app/public ./public
COPY --from=builder /app/public ./public/{locale} # <-- added this line
...
```

**Comment by goguda** [comment] 2023-11-03 21:50
> I have the same issue in NextJS up to latest version `14.0.1`, in dev mode this is not so important, but for production builds via `docker` I wrote this fix in the `Dockerfile`. It involves copying the public directory into a locale subdirectory Original `Dockerfile` https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile
> 
> ```dockerfile
> ...
> COPY --from=builder /app/public ./public
> COPY --from=builder /app/public ./public/{locale} # <-- added this line
> ...
> ```

We're using docker to deploy too and this works great as a workaround in the meantime. Thank you!

**Comment by goguda** [comment] 2023-11-23 21:49
> Also having the same issue. We haven't been able to update from 13.3. This is a silly issue with a really small fix. I imagine a lot of people would have this problem?? Please, just fix it already!

If it's a really small fix, why not fix it yourself and submit a pr? ;)

**Comment by erwanriou** [comment] 2023-11-23 22:07
I think there is a PR already to fix the solution but she was not approved and time passed. 

The docker solution works fine in a case that you handle translation within sub urls but if you handle multiple domains then it doesn't work as expected.  

The lesson learned here is to not rely on nextjs for assets in multi domain applications and handle it in a S3/gcloud/azure bucket that point to a different sub domain etc.

**Comment by aledovskikh** [comment] 2023-11-24 11:52
Docker solution (dirty workaround) works well with small `/public` dir and several locales. But (for example) our /public dir is 200mb and we have 26 locales :(
And yes, there is PR already https://github.com/vercel/next.js/pull/55137

**Comment by mbohgard** [comment] 2023-11-24 15:17
@goguda 
> If it's a really small fix, why not fix it yourself and submit a pr? ;)

1. There already is a PR, no need to create another one
2. The issue is known, the solution is known, the fix is tiny - the whole thing is silly
3. Like @aledovskikh said, the "fix" is not realistic with a big public folder and a lot of locales
4. Next.js i backed by Vercel - people are getting payed to work on it and people are paying Vercel to host their apps. It shouldn't have to be fixed by the public. Next.js is real product backed by a big company.
5. It's even more silly what has to be done to _fix_ the problem (duplicating public files)

**Comment by kamesdev** [comment] 2023-11-24 16:30
@arielvieira 
I used your solution. restarted the server and this still doesn't work.

**Comment by TheWalkingDad3** [comment] 2023-11-24 16:49
@kamesdev - we also use the fix with v13.5.6 and it works really great.

We added this line in our Dockerfile to "patch" nextjs:
`RUN sed -i 's/const isDynamicOutput.*/const isDynamicOutput = type === "pageFile" || type === "appFile" || type === "publicFolder";/g' /frontend/node_modules/next/dist/server/lib/router-utils/filesystem.js`

@arielvieira - thank you very much for this workaround!!

**Comment by kamesdev** [comment] 2023-11-24 16:51
What if I don't use docker?

**Comment by erwanrioualbelli** [comment] 2023-11-24 16:58
> @kamesdev - we also use the fix with v13.5.6 and it works really great.
> 
> We added this line in our Dockerfile to "patch" nextjs: `RUN sed -i 's/const isDynamicOutput.*/const isDynamicOutput = type === "pageFile" || type === "appFile" || type === "publicFolder";/g' /frontend/node_modules/next/dist/server/lib/router-utils/filesystem.js`
> 
> @arielvieira - thank you very much for this workaround!!

Nice, i will tryout on our next release, this might work.

**Comment by kamesdev** [comment] 2023-11-24 17:08
> > @kamesdev - we also use the fix with v13.5.6 and it works really great.
> > We added this line in our Dockerfile to "patch" nextjs: `RUN sed -i 's/const isDynamicOutput.*/const isDynamicOutput = type === "pageFile" || type === "appFile" || type === "publicFolder";/g' /frontend/node_modules/next/dist/server/lib/router-utils/filesystem.js`
> > @arielvieira - thank you very much for this workaround!!
> 
> Nice, i will tryout on our next release, this might work.
> 
> @kamesdev If you don't use docker i assume you still have a release process for a versel/heroku something and that reference to a script within your application right? Generaly its associated to your package.json scripts
> 
> just make sure to add a pre-install/pre-build step where you do `sed -i 's/const isDynamicOutput.*/const isDynamicOutput = type === "pageFile" || type === "appFile" || type === "publicFolder";/g' /frontend/node_modules/next/dist/server/lib/router-utils/filesystem.js`
> 
> https://vercel.com/docs/deployments/configure-a-build

Thanks for reply and solution. Will this work locally with "npm run dev"?

**Comment by pekarja5** [comment] 2023-11-24 17:09
@kamesdev You can also use [patch-package](https://www.npmjs.com/package/patch-package)

**Comment by kamesdev** [comment] 2023-11-24 17:48
> @kamesdev You can also use [patch-package](https://www.npmjs.com/package/patch-package)

@pekarja5 

Thanks for suggestion. Can you please tell me what I did wrong?

1. I installed patch-package.

2. I replaced `const isDynamicOutput = type === "pageFile" || type === "appFile";` with
`const isDynamicOutput = type === 'pageFile' || type === 'appFile' || type === 'publicFolder'` in node_modules/next/dist/server/lib/router-utils/filesystem.js. 

3. I ran `npx patch-package next` command.

4. I added `"postinstall": "patch-package"` to scripts in package.json.

5. I ran `npx run dev` command and this still doesn't work.

I looked on generated patch file and it seems it almost identical.

**Comment by aledovskikh** [comment] 2023-12-12 13:02
Any progress of releasing [fix](https://github.com/vercel/next.js/pull/55137) for this issue?

**Comment by kissifrot** [comment] 2023-12-15 10:40
I'm bumping this, as we are stuck to NextJS 13.4.12 😅  without this change

**Comment by sawden** [comment] 2023-12-16 17:58
Without meaning any disrespect, I'm quite surprised that this issue is still open...

It's almost unbelievable that multilingual functionality, a critical feature, is currently not possible in Next.js, and this has been the case for over **3 months** now... 👀

**Comment by persocon** [comment] 2024-01-09 12:38
IF THE FIX WAS TINY WHAT'S TAKING SO LONG?! 5 MONTHS NOW?! WTF GUYS!!! FIX THIS SHIT ALREADY!!!

**Comment by persocon** [comment] 2024-01-09 12:45
`didvercelfixedpublicfilesnotaccessibleoni18ndomains.com` website coming up soon

**Comment by chrisneven** [comment] 2024-01-09 12:58
@persocon 

Such aggressive and disrespectful language is not constructive and won't help at all. Get it together dude.

**Comment by chrisneven** [comment] 2024-01-09 13:00
@timneutkens Hallo Tim, could the team take a look at the following https://github.com/vercel/next.js/pull/59773? This should solve the issue and even contains tests as requested in https://github.com/vercel/next.js/pull/55137.

**Comment by JohnConstantin** [comment] 2024-01-09 13:12
hello, today I encountered the same problem, I'm solving it by copying the public folder, please any update?

```
COPY --from=build /opt/app/public ./public/en
COPY --from=build /opt/app/public ./public/de
COPY --from=build /opt/app/public ./public/sk
```

**Closed** 2024-01-17 21:41 UTC
Labels: template: bug, area: Routing
