### ISSUE TITLE
Rewrite loop when using next-dev with localhost and different ports e.g. MultiZone setup

### ISSUE THREAD

**Issue by PacoSoftwerft** [vercel/next.js#56615] opened 2023-10-09 14:14 UTC
### Link to the code that reproduces this issue

https://github.com/PacoSoftwerft/multi-zone-microfrontends

## Start main-site

```bash
cd main-site
npm run dev
```

## Start blog

Start the blog in a new shell

```bash
cd blog
npm run dev
```

## Bug

Open `http://localhost:3000/blog`, it is loading in a loop.

### Current vs. Expected behavior

Expected behavior:

rewrite to same domain "localhost" with different port should work like they did in 13.4.12

Version `next@13.4.12` is working just fine.
Stop the `main-site` then

```bash
cd main-site
npm i next@13.4.12 --save-exact
npm run dev
```

open `http://localhost:3000/blog`

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

Node:           v18.18.0
npm:            10.1.0
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link)

### Additional context

This bug was introduced with **13.4.13**

The bug only appears when using the **Pages Router**

The bug depends on the version of the app that rewrites, here **main-site**.

It seems like the **port** is stripped/not respected somewhere.

The rewrite works if it points to another domain.

Additional info 2023-10-20

The bug only appears when **both** zones are started with `npm run dev`

| main (3000) | blog (3001) | works?  |
|---|---|---|
| `npm run dev` | `npm run dev` | ❌ |
| `npm run dev` | `npm run build`  `npm run start`   | ✅ |
|  `npm run build`  `npm run start` | `npm run dev` | ✅ |
| `npm run build`  `npm run start` | `npm run build`  `npm run start` | ✅|

**Comment by AhmedOsamaSecurrency** [comment] 2023-10-12 15:44
facing the same issue with v13.5.4

downgraded to 13.4.3

**Comment by exneval** [comment] 2023-10-21 06:50
duplicate of #54454

**Closed** 2023-12-06 20:15 UTC
Labels: template: bug, area: Routing
