### ISSUE TITLE
Optional catch all routes not working as expected with Internationalized Routing and getStaticParams with path: [] and fallback: 'blocking'

### ISSUE THREAD

**Issue by ramirezsandin** [vercel/next.js#33248] opened 2022-01-13 08:53 UTC
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.13.0
      npm: 8.1.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

**Optional catch all routes** doesn't work as expected when it is used under the following conditions:

- Nested inside a dynamic route.
- Using getStaticPaths with `paths: []` and `fallback: 'blocking'`.
- Using Internationalized Routing.
- When it's deployed (e.g. Vercel), locally runs as properly).

In this scenario "**optional catch all routes**" works as "**catch all routes**".

### Expected Behavior

so for example this file:

_/articles/[category]/[[...pages]].tsx_

should catch, among others, the following routes:

_/articles/sport_

_/articles/sport/page/1_

but _/articles/sport_ (that would be the special route that **optional catch all routes** has as a target), results in 404.
_/articles/sport/page/1_ loads fine.

### To Reproduce

Set up internationalized Routes on next.config.ts
```javascript
module.exports = {
  reactStrictMode: true,
  i18n: {
    locales: ['en', 'es'],
    defaultLocale: 'en',
  },
}
```
Create a simple file with a parent dynamic route and an optional catch all route:
_/pages/articles/[category]/[...pages]].tsx_
```typescript
interface PageProps {
    locale: string
    params: ParsedUrlQuery | undefined
}
const Page = ({ locale, params }: PageProps) => {
    return (
        <Stack
            py={2}
            spacing={2}
        >
            <h1>
                It Loads
            </h1>
            <ul>
                <li>Locale: {locale} </li>
                {params &&
                    <li>Params: <pre>{JSON.stringify(params, null, 4)}</pre></li>
                }
            </ul>
        </Stack>
    )
}
Page.getLayout = (page: ReactElement) => (
    <SiteLayout>
        {page}
    </SiteLayout>
)
export default Page

export const getStaticPaths = async () => {
    return {
        paths: [],
        fallback: 'blocking',
    }
}

export const getStaticProps = async ({ locale, params }: GetStaticPropsContext) => {
    return {
        props: {
            locale,
            params,
        },
        revalidate: 60
    }
}
```

Deploy.

GitHub repository: [here](https://github.com/ramirezsandin/optional-catch-all-routes)
Test site in Vercel: [live site](https://optional-catch-all-routes.vercel.app/)

**Comment by balazsorban44** [comment] 2022-01-15 02:47
I was looking through older issues, and this actually has an earlier report. So I'm closing it as a duplicate of #30631

**Closed by balazsorban44** 2022-01-15 02:47 UTC
Labels: kind: bug, area: Routing, area: I18n
