### ISSUE TITLE
13.3.0 Intercepting with grouped app does not work

### ISSUE THREAD

**Issue by khuezy** [vercel/next.js#48104] opened 2023-04-07 19:30 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.14.0
      npm: 9.3.1
      Yarn: 1.22.19
      pnpm: 7.27.0
    Relevant packages:
      next: 13.3.1-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/khuezy/next-intercept

### To Reproduce

- `npm install`
- `npm run dev`
- go to localhost:3000/shop
- Click on `Go to nested`, route is stuck
- go to localhost:3000/shop_no_group
- Click on `Go to nested`, route is intercepted

### Describe the Bug

When using group routes, interception does not work.
eg:
```
app/(group)/shop
```

### Expected Behavior

When using grouped routes, interception should work.

**Comment by khuezy** [comment] 2023-04-07 19:46
I had to look over the e2e tests in nextjs to find out that you need `default.tsx` in order to fix the 404. Would be nice to not have to create a temp file though.

**Comment by bob-obringer** [comment] 2023-04-08 22:26
Running into the same problem.  Sometimes it seems to sort of half work the first time, but otherwise, it's broken with route groups.

**Comment by borispoehland** [comment] 2023-04-09 11:20
Same here. Also, it would be lovely to configure that an interception happens on all routes of a specific group, as currently you would have to duplicate the interception path across all routes where we want interception to happen: https://github.com/vercel/next.js/issues/48157

**Comment by feedthejim** [comment] 2023-04-12 07:58
looking!

**Comment by feedthejim** [comment] 2023-04-12 08:05
should be fixed by https://github.com/vercel/next.js/pull/48276

**Comment by khuezy** [comment] 2023-04-12 17:39
@feedthejim :( I don't think the fix addresses interception w/ modal.
eg:
```
/photos/[author]/[id]/page.tsx // shows the individual photo by the author
/photos/page.tsx                      // shows all the photos
/@modal/(.)[author][id]/page.tsx // doesn't appear to work
```

**Comment by Nickman87** [comment] 2023-04-13 12:38
@feedthejim I think I have the same issue as @khuezy (intercepting routes not working inside of a group folder).

I built a small reproduction here: https://codesandbox.io/p/sandbox/nextjs-intercepting-routes-s9j6mo

I have a REAL group dashboard (using a `(group)` folder) and a FAKE group dashboard using exactly the same code and folder structure but inside a regular `group` folder (which means it is also like that in the path of the URL).

Testing the fake one, the modal content is loaded as expected, when you go to the real one, next will always navigate away.

Hope this helps you track down the issue :)

**Comment by khuezy** [comment] 2023-04-13 16:05
@feedthejim can you look at: https://codesandbox.io/p/sandbox/nostalgic-chaplygin-tfyi0p

Append "/photos" to the site url, eg: "csb.app/photos".

Clicking on the "Go to /photos/[author]/[id]" will navigate to the page, I expect it to intercept.
If you then click "Back" in the browser, the navigation seems to be stuck too.

**Comment by feedthejim** [comment] 2023-04-13 16:09
thanks for the repro @khuezy I can confirm it does not work as expected, let me investigate

**Comment by Nickman87** [comment] 2023-04-13 16:15
@feedthejim You are right, I did make a mistake there, my bad :).
I changed the links to be correct now and the error still persists, The modal is not loaded but next redirects to the page.
Do you see any other issues with the setup now?

**Comment by khuezy** [comment] 2023-04-13 16:32
Would it be possible to make `(.)` optional, ie it should default to the current directory of the "@modal".
eg: `@modal/(.)[author]` and `@modal/[author]` is equivalent. You'd use `(...)` or `(..)` to go to root or up a level, respectively.

**Comment by feedthejim** [comment] 2023-04-13 16:51
Opened a PR for the route group support!

@khuezy no because that would disable the interception route! checkout the doc for both concepts https://beta.nextjs.org/docs/routing/parallel-routes

**Comment by khuezy** [comment] 2023-04-13 16:54
Gotcha, thanks for the quick turnaround!

**Closed** 2023-04-13 21:29 UTC
Labels: template: bug

**Comment by borispoehland** [comment] 2023-04-18 12:08
Hey @feedthejim, I was trying to apply that in my Nextgram demo from a different issue and it does not work. Could you please take a look?
https://github.com/borispoehland/nextgram-demo
https://nextgram-demo.vercel.app/

I took the working example and broke it by putting the 2 routes `/` and `/test` into the `(app)` group

**Comment by prodbygoss** [comment] 2023-05-03 01:26
On a related note, I am having issues getting intercept to work when there are multiple nested dynamic slugs .
For example, intercepting at `(...)posts/[collectionId]/[postId]` does not work. Only `(...posts)/[postId]` works.

**Comment by TrustyTechSG** [comment] 2023-05-08 11:23
> On a related note, I am having issues getting intercept to work when there are multiple nested dynamic slugs . For example, intercepting at `(...)posts/[collectionId]/[postId]` does not work. Only `(...posts)/[postId]` works.

I have exact the same issue on 13.4.1,
/[lang]/checkout/[businessCode]/[serviceId]/@calendar/(..)testpath **work**
/[lang]/checkout/[businessCode]/[serviceId]/@calendar/(..)(..)anothertestpath **not work** (always hard navigate to anothertestpath)
/[lang]/checkout/[businessCode]/[serviceId]/@calendar/(...)[lang]/thirdtestpath **not work** (always hard navigate to thirdtestpath)

**Comment by khuezy** [comment] 2023-05-09 21:15
@feedthejim Can you take a look at this ticket again please. Or should I open another ticket? As others have mentioned, dynamic routes don't seem to be interception. Here's a new repro: https://codesandbox.io/p/sandbox/youthful-butterfly-l44fsy?file=%2Fapp%2F%28main%29%2Fstatic%2Fpage.tsx%3A6%2C57

The `photos` app has dynamic routes of `[author]`, which doesn't appear to be intercepted at all.
If you go to the `/static`, the interception works.

Thanks!

**Comment by Nithur-M** [comment] 2023-05-15 10:28
Hello @khuezy did you able to find a solution for this?

**Comment by khuezy** [comment] 2023-05-15 14:08
@Nithur-M I think one of the work around is to go to the root: `(...)someroute`.
I opened ticket: https://github.com/vercel/next.js/issues/49614

**Comment by Nithur-M** [comment] 2023-05-21 11:57
> @Nithur-M I think one of the work around is to go to the root: `(...)someroute`. I opened ticket: #49614

Thanks for this. Facing the same issue now.
