### ISSUE TITLE
Invalid HMR Message 'Error: No router instance found.' when using AntD components

### ISSUE THREAD

**Issue by Servellia** [vercel/next.js#30937] opened 2021-11-04 07:51 UTC
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

Azure DevOps containerized

### Describe the Bug

When loading a page using Antd it throws the error 

`Invalid HMR message: {"action":"sync","hash":"587bdc7eaabbfd86","warnings":[],"errors":[]}
Error: No router instance found.
You should only use "next/router" on the client side of your app.`

This also breaks functionality to route between locales. For instance switching from `/index ` to `/en/index` results in a blank screen

Removing AntD components OR reverting back to v11 resolves the error

### Expected Behavior

No next/router error should occur

### To Reproduce

Public repo to reproduce steps: https://github.com/Servellia/next12-hmr-error

**Comment by meandillar** [comment] 2021-11-05 20:16
Looks like same issue as #30710

**Comment by timneutkens** [comment] 2021-11-05 20:29
Closing as duplicate of #30710

**Closed by timneutkens** 2021-11-05 20:29 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
