### ISSUE TITLE
feature request: Allow all subdomains for a domain in next/image

### ISSUE THREAD

**Issue by neeraj3029** [vercel/next.js#34602] opened 2022-02-20 05:53 UTC
### Describe the feature you'd like to request

Currently in next/image, we need to all subdomains for all external URLs to allow fetching images from them. This could get problematic when we use multiple subdomains from the same domain. As the number of subdomains grow, it becomes difficult maintain.

### Describe the solution you'd like

Solution 1. We can add another array attribute to `images` config, called `allowSubdomainsFrom`.  Then, next/image would support all the domains mentioned inside that array.

Solution 2. We can allow all subdomains for the `domains` given in the images config.

**Comment by balazsorban44** [comment] 2022-02-20 14:07
This is a duplicate of #27925

**Closed by balazsorban44** 2022-02-20 14:07 UTC
Labels: template: story
