### ISSUE TITLE
next@canary - can't find module "webpack5"

### ISSUE THREAD

**Issue by Xapu1337** [vercel/next.js#30167] opened 2021-10-22 09:00 UTC
### What version of Next.js are you using?

canary

### What version of Node.js are you using?

16.11.1

### What browser are you using?

Brave

### What operating system are you using?

Windows

### How are you deploying your application?

NestJS / Express

### Describe the Bug

next@canary can't find the module "webpack5"
```
[10:53:32] Starting compilation in watch mode...

node_modules/next/dist/server/config-shared.d.ts:1:27 - error TS2307: Cannot find module 'webpack5' or its corresponding type declarations.

1 import type webpack5 from 'webpack5';
                            ~~~~~~~~~~

[10:53:37] Found 1 error. Watching for file changes.
```

### Expected Behavior

next@canary can find the module and compiles without issues

### To Reproduce

Create a express app with nextjs and typescript.
replace next with next@canary
error should occour

**Comment by dontsave** [comment] 2021-11-03 14:35
for anyone else running into this in 12, we got around it by hacking an override of the ambient types with the following in `module.d.ts` file:

```ts
declare module 'next/dist/compiled/webpack/webpack' {
  export namespace webpack {
    interface Compiler {
      [key: string]: any;
    }
    interface Plugin {
      [key: string]: any;
    }
  }
  export namespace webpack5 {
    interface Configuration {
      [key: string]: any;
    }
  }
}
```

**Comment by Xapu1337** [comment] 2021-11-04 05:17
> for anyone else running into this in 12, we got around it by hacking an override of the ambient types with the following in `module.d.ts` file:
> 
> ```ts
> declare module 'next/dist/compiled/webpack/webpack' {
>   export namespace webpack {
>     interface Compiler {
>       [key: string]: any;
>     }
>     interface Plugin {
>       [key: string]: any;
>     }
>   }
>   export namespace webpack5 {
>     interface Configuration {
>       [key: string]: any;
>     }
>   }
> }
> ```

Works with the latest canary version!  
Thanks!

**Comment by kevinsimper** [comment] 2021-11-04 14:11
I tried the latest canary
`^12.0.3-canary.7`

and I get this error still
```
> tsc

node_modules/next/dist/server/config-shared.d.ts(1,15): error TS2724: '"next/dist/compiled/webpack/webpack"' has no exported member named 'webpack5'. Did you mean 'webpack'?
The command '/bin/sh -c npm run build' returned a non-zero code: 2
```

**Comment by geongeorge** [comment] 2021-11-05 07:53
Still not fixed in the latest canary. Just bumping this up

**Closed** 2021-11-08 15:19 UTC
Labels: kind: bug, area: TypeScript

**Comment by ijjk** [comment] 2021-11-08 19:54
Hi, this has been updated in `v12.0.4-canary.0` of Next.js, please update and give it a try!

**Comment by Eigilak** [comment] 2021-11-08 23:13
> v12.0.4-canary.0

It gives a new error: 

TS2694: Namespace '"./node_modules/next/dist/compiled/webpack/webpack".webpack5' has no exported member 'Compilation'.

26     createAssets(compilation: webpack5.Compilation, assets: any, envPerRoute: Map<string, string[]>): void;

**Comment by aralroca** [comment] 2021-11-10 13:02
`12.0.4-canary.4` works well  😊

**Comment by balazsorban44** [comment] 2022-01-27 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
