### ISSUE TITLE
Cannot read property 'prefetch' of null error on StoryBook

### ISSUE THREAD

**Issue by hems** [vercel/next.js#19825] opened 2020-12-04 14:40 UTC
# Bug report

## Describe the bug

`Cannot read property 'prefetch' of null` error is being displayed on StoryBook when making a storybook of an item with `<Link>` after updating to Next 10

## To reproduce

Create a component with the following content:

````ts
      <Link href="/" prefetch={false}>
        <Box as="a" justifyItems="center" display="flex">
          ....
        </Box>
      </Link>
````

## Expected behavior

Components should render normally as previously experienced on Next 9.

Currently to work around this issue i'm adding `prefetch={false}` to the `Link` objects but that disables the prefetch on the website which is not desirable

## Screenshots

![image](https://user-images.githubusercontent.com/27327/101176501-7d1f2f00-363e-11eb-97a8-5f2d15c941de.png)

## System information

- OS: Linux
- Browser (if applies): chrome
- Version of Node.js: 14

**Comment by PaulCaruana** [comment] 2020-12-05 06:33
I am having the same issue. If you go back to next 9.5.5 it works then go back 10.0.x it fails. Having said that it appears to a timing issues when doing yarn install. It started working on one of my projects (with 10.0.3) and when I deleted yarn.lock and re-did yarn install it failed. I spent all afternoon trying to figure this out.

**Comment by timneutkens** [comment] 2020-12-08 10:15
Duplicate of #16864

**Closed by timneutkens** 2020-12-08 10:15 UTC
Labels: template: bug

**Comment by ybrodsky** [comment] 2020-12-08 14:47
#16864 refers to jest. The solutions / hacks provided there dont work on storybook.

**Comment by hems** [comment] 2020-12-08 21:16
> Duplicate of #16864

indeed the other error is on jest / tests.. not on storybook

**Comment by timneutkens** [comment] 2020-12-09 10:02
It's the same issue though.

**Comment by ybrodsky** [comment] 2020-12-09 12:03
The proposed solution doesnt work in that issue doesnt work here. Closing this is the same as ignoring it.

**Comment by hems** [comment] 2020-12-10 01:40
> The proposed solution doesnt work here. Closing this is the same as ignoring it.

@ybrodsky i have [made a comment in the other issue](https://github.com/vercel/next.js/issues/16864#issuecomment-742176430), maybe @timneutkens or someone else will be able to help..

**Comment by damusnet** [comment] 2020-12-10 02:57
I believe https://github.com/vercel/next.js/pull/19857 would solve both but I need help to write the integration test.

**Comment by gfortaine** [comment] 2021-01-05 15:28
```ts
       <Link href="/" prefetch={!process.env.STORYBOOK}>
         <Box as="a" justifyItems="center" display="flex">
           ....
         </Box>
       </Link>
 ```

**Comment by hems** [comment] 2021-01-05 16:27
> [storybookjs/storybook#12997](https://github.com/storybookjs/storybook/pull/12997)
> 
> ```ts
>        <Link href="/" prefetch={!process.env.STORYBOOK}>
>          <Box as="a" justifyItems="center" display="flex">
>            ....
>          </Box>
>        </Link>
> ```

Thanks for the suggestion @gfortaine but the solution presented [in this comment](https://github.com/vercel/next.js/issues/16864#issuecomment-743743089) is cleaner as it doesn't involved modifying the application code, instead, we just mock the router on the storybook.

I can see how checking if the application is running inside of storybook and setting prefetch to false would be great, but that would have to be added to the Router on Next.js and not on all links inside of an application!

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
