### ISSUE TITLE
create-next-app cli reports all github urls for as invalid when using -e or --example

### ISSUE THREAD

**Issue by BuddyLReno** [vercel/next.js#19277] opened 2020-11-18 18:00 UTC
# Bug report

## Describe the bug

When trying to use `yarn create next-app` or `npx create-next-app` with the -e flag to create a starter from an example url, the cli reports: `Found invalid GitHub URL: <URL>. Please fix the url and try again.`

I've tried a few different times:

```bash
$ npx create-next-app your-blog -e https://github.com/wutali/nextjs-netlify-blog-template

$ yarn create next-app my-app -e https://github.com/wutali/nextjs-netlify-blog-template

$ npx create-next-app my-app -e https://github.com/colbyfayock/next-sass-starter

$ npx create-next-app your-blog --example https://github.com/wutali/nextjs-netlify-blog-template
```

And they all report the same issue.

## To Reproduce

Run any of the above commands and you should see the error.

## Expected behavior

Should create the site from the example.

## Screenshots

![image](https://user-images.githubusercontent.com/1429547/99568793-6f5a8000-2995-11eb-9a94-ae62fcc5f1c7.png)

## System information

- OS: MacOS Catalina 10.15.7
- Version of Node.js: 12.18.0

**Comment by BuddyLReno** [comment] 2020-11-18 18:28
I've been able to verify this is a bug with the newest `create-next-app` release on 10.0.2. Moving back to 10.0.1 fixes the issue.

**Comment by kyrstenkelly** [comment] 2020-11-24 22:01
+1 also seeing this issue

**Comment by kyrstenkelly** [comment] 2020-11-24 22:05
I'm also seeing this issue. however, reverting to 10.0.1 didn't fix it for me. 

```
[kkelly]:~/git/test$ ➭ npx create-next-app --version
10.0.1
[kkelly]:~/git/test$ ➭ npx create-next-app --example https://github.com/udacity/next-js-boilerplate
✔ What is your project named? … test-next-js-app
Found invalid GitHub URL: "https://github.com/udacity/next-js-boilerplate". Please fix the URL and try again.
```

**Comment by debugginator** [comment] 2020-11-27 12:42
@BuddyLReno Tried reproducing your error, but it seems to be fixed in `10.0.3`.

@kyrstenkelly If I try opening the repo you used (https://github.com/udacity/next-js-boilerplate) in the browser I get a 404, are you sure it's public?

**Comment by BuddyLReno** [comment] 2020-11-27 13:18
@debugginator weird. It was public when I tried to do it. It was also doing it for other GitHub URLs. I'll try it again and see if it's fixed

**Comment by debugginator** [comment] 2020-11-27 15:35
> @debugginator weird. It was public when I tried to do it. It was also doing it for other GitHub URLs. I'll try it again and see if it's fixed

I think all of your urls work, I was referring to @kyrstenkelly's url

**Comment by kyrstenkelly** [comment] 2020-11-30 16:01
@debugginator no you're correct - my URL is private, however I also tried it with other public URLS (like @BuddyLReno's) and got the same error. 

When working properly, does it only work with public URLs? (That would make sense, and I can change mine to public if needed)

**Comment by dunin** [comment] 2021-03-29 11:09
Got the same things for my private repo. Any workaround there?

**Comment by ilangorajagopal** [comment] 2021-05-28 15:24
Not sure if the issue still persists for someone. Adding it here for reference. It worked for me with a public repo. I tested with a private repo and it didn't work. I just had to wrap the Github URL in double quotes. Using `10.2.3`.

**Comment by guanacone** [comment] 2021-06-24 18:33
With or without quotes, you need to remove `.git` from your URL.

**Comment by balazsorban44** [comment] 2021-12-21 16:29
I cannot reproduce this anymore, probably has been fixed at some point.

**Closed by balazsorban44** 2021-12-21 16:29 UTC
Labels: kind: bug, good first issue, area: create-next-app

**Comment by balazsorban44** [comment] 2022-01-27 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
