### ISSUE TITLE
Upgrading to Next 11 causes "Unexpected token / in JSON at position 0"

### ISSUE THREAD

**Issue by Hassaan016** [vercel/next.js#26156] opened 2021-06-16 01:50 UTC
### What version of Next.js are you using?

11

### What version of Node.js are you using?

15.14

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Next Start

### Describe the Bug
**Dependency List**
`{
  "name": "frontend-proj",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.35",
    "@fortawesome/free-solid-svg-icons": "^5.15.3",
    "@fortawesome/react-fontawesome": "^0.1.14",
    "@iktakahiro/markdown-it-katex": "^4.0.1",
    "@sendgrid/mail": "^7.4.4",
    "bootstrap": "^4.6.0",
    "cogo-toast": "^4.2.3",
    "date-fns": "^2.22.1",
    "es6-promise": "^4.2.8",
    "highlight.js": "^10.7.3",
    "isomorphic-fetch": "^3.0.0",
    "js-cookie": "^2.2.1",
    "jsonwebtoken": "^8.5.1",
    "katex": "^0.12.0",
    "markdown-it": "^12.0.6",
    "markdown-it-emoji": "^2.0.0",
    "nanoid": "^3.1.23",
    "next": "^11.0.0",
    "nprogress": "^0.2.0",
    "prop-types": "^15.7.2",
    "query-string": "^6.14.1",
    "quill-better-table": "^1.2.10",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-google-login": "^5.2.2",
    "react-icons": "^4.2.0",
    "react-markdown-editor-lite": "^1.2.4",
    "react-multi-carousel": "^2.6.3",
    "react-quill": "^2.0.0-beta.2",
    "react-render-html": "^0.6.0",
    "react-timeout": "^2.0.1",
    "reactstrap": "^8.9.0",
    "sass": "^1.35.1",
    "styled-components": "^5.3.0"
  },
  "devDependencies": {
    "@svgr/cli": "^5.5.0",
    "babel-plugin-inline-react-svg": "^2.0.1",
    "babel-plugin-styled-components": "^1.12.0"
  }
}
`

**_Upgrading to Next 11 causes "Unexpected token / in JSON at position 0":_**

**Error** - ./node_modules/next/dist/client/dev/amp-dev.js
SyntaxError: Unexpected token / in JSON at position 0 
    at JSON.parse (<anonymous>)

### Expected Behavior

The upgrade procedure should work out of the box. As the same application was working fine with NextJs 10.2 release

### To Reproduce

The upgrade procedure should work out of the box. As the same application was working fine with NextJs 10.2 release

**Comment by shenghanqin** [comment] 2021-06-16 06:19
Me too.

**Comment by myeongwon** [comment] 2021-06-16 09:38
Me too 222

**Comment by timneutkens** [comment] 2021-06-16 11:54
Duplicate of #26163

**Closed by timneutkens** 2021-06-16 11:54 UTC
Labels: template: bug

**Comment by Hassaan016** [comment] 2021-06-16 12:07
@timneutkens What's the solution ?

**Comment by balazsorban44** [comment] 2022-01-28 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
