### ISSUE TITLE
Visual Studio Code - IntelliSense for JS and TS not working properly with NextJs. 

### ISSUE THREAD

**Issue by tahonaPL** [vercel/next.js#32045] opened 2021-12-02 14:11 UTC
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

16.xx

### What browser are you using?

Chrome

### What operating system are you using?

Windows/MacOS

### How are you deploying your application?

not important

### Describe the Bug

VSC doesn't see Next components. I tried with clean install for ts and js project.

For this components: 
Image, Head, Link etc.

there is no auto-completion/suggestions that should come from next/image , next/head and next/link.  

### Expected Behavior

nice auto completion and auto import. 

### To Reproduce

1. yarn create next-app --typescript **or** yarn create next-app -
2. go to /pages/index.ts 
3. remove import next/head
4. click on  < Head > 
5. hit CTRL + space (to show suggestion or import )

**Comment by timneutkens** [comment] 2021-12-02 15:03
Can you try using `next@canary`? We recently landed #28316.

**Comment by tahonaPL** [comment] 2021-12-02 20:09
@timneutkens  I have checked the canary. There is some improvement but it tries to use wrong module path. 

example:
import { **Head** } from "next/document";  ???


and still no **Link** and **Image** in suggestions

**Comment by balazsorban44** [comment] 2021-12-03 00:55
`import { Head } from "next/document"`

Is not the one you want to use in `pages/index`, that's for the `_document` file. This seems to work already on `latest`.

I do auto-suggestions after upgrading to `canary` like so:

`next/head`
![image](https://user-images.githubusercontent.com/18369201/144526071-545f29c8-1a86-446c-8381-8a2c9fd15c44.png)

`next/image`
![image](https://user-images.githubusercontent.com/18369201/144526156-5438b893-337c-42be-ab73-fecef6c80b82.png)

`next/link`
![image](https://user-images.githubusercontent.com/18369201/144526227-dc062a42-d6ac-42d7-b740-63ea087826db.png)

**Closed** 2021-12-03 07:16 UTC
Labels: area: TypeScript, area: Developer Experience

**Comment by balazsorban44** [comment] 2021-12-03 13:14
This is fixed in `next@12.0.5-canary.16` give it a try!

Example:
![image](https://user-images.githubusercontent.com/18369201/144608353-f39092b6-db8d-428c-9da2-ac2aa7434cfa.png)

**Comment by tahonaPL** [comment] 2021-12-04 14:04
Love you, guys. thx for fixing this.

**Comment by balazsorban44** [comment] 2022-01-27 06:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
