### ISSUE TITLE
/500 url returns a 500 code instead of 200.

### ISSUE THREAD

**Issue by thomasverleye** [vercel/next.js#29253] opened 2021-09-21 11:10 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

16.4.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

When surfing too `/500` path, a `500` statuscode is returned.
This in fact isn't really a server error, the server does not get an error returned.

### Expected Behavior

`/500` path should get a `200` status code

### To Reproduce

surf on any setup to `/500`

**Comment by ijjk** [comment] 2021-09-21 13:06
Hi, this is the expected behavior and ensures crawlers don't consider this page for search results while still allowing the `/500` page to be previewed. I'm gonna close this isn't a bug and is currently expected. If you would like to prevent this page from being visited a `beforeFiles` rewrite can be used to rewrite it to a 404 instead.

**Closed by ijjk** 2021-09-21 13:06 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
