### ISSUE TITLE
next/server should not be imported outside of pages/_middleware.js

### ISSUE THREAD

**Issue by saurabhguptarock** [vercel/next.js#32121] opened 2021-12-04 14:00 UTC
### What version of Next.js are you using?

12.0.6

### What version of Node.js are you using?

14.18.2

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

I have added _middleware.tsx file in /pages/login/_middleware.tsx and it gives error.

### Expected Behavior

It should not give any error

### To Reproduce

My files

_middleware.tsx
```ts
import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";

export const middleware = (req: NextRequest) => {
  const cookie = req.cookies["auth"];

  if (cookie) {
    return NextResponse.redirect("/");
  }
};
```
Folder structure
<img width="259" alt="Screenshot 2021-12-04 at 7 29 54 PM" src="https://user-images.githubusercontent.com/32234038/144712222-5abbc69c-f61f-42cf-99f9-51a3ddc63f9d.png">

<img width="1123" alt="Screenshot 2021-12-04 at 7 30 06 PM" src="https://user-images.githubusercontent.com/32234038/144712234-4a6b2815-59c0-41ff-b9de-c8b0a47c7d8c.png">

**Comment by balazsorban44** [comment] 2021-12-05 14:39
This is being addressed in https://github.com/vercel/next.js/pull/32139

**Closed** 2021-12-05 14:41 UTC
Labels: kind: bug, area: ESLint

**Comment by balazsorban44** [comment] 2022-01-27 05:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
