### ISSUE TITLE
Docs: `next/image` `layout=fill` is heavy on thread work

### ISSUE THREAD

**Issue by giovanni-caiazzo** [vercel/next.js#40049] opened 2022-08-29 09:04 UTC
### What is the improvement or update you wish to see?

The `<Image>` docs are missing some info on the impact the `layout=fill` property can have on the page performance.
I have a homepage with about 10 images with an aspect ratio that is fixed by the design of the page, however the images most of the time do not have the same aspect ratio. So, in order for them to fit nicely in their container I used the `layout=fill` property with the `objectFit=cover` and it looked nice. However the PageSpeed score descreased substantially (from high 90s to low 60s) lamenting high main-thread work and high server response time. Setting the images to `layout=intrinsic` or `layout=responsive` removes this problem, but the images don't fit in the container properly anymore.
I would like a warning on the `layout=fill` part regarding this possible slowdown

### Is there any context that might help us understand?

I have built a nextJS blog site and the pages with most image received a big impact to their PageSpeed score when the images had `layout=fill`. This was not the case when `layout` was set to any of the other three properties

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-reference/next/image#layout

**Comment by leerob** [comment] 2024-01-13 18:51
If you could include a reproduction of this, we're happy to take a look at what the root issue might be. I know it's been a minute since you reported this, so no worries if you don't want to. We haven't seen any other reports on (or upvotes on this issue) so going to close this out. Thank you regardless!

**Closed by leerob** 2024-01-13 18:51 UTC
Labels: template: documentation
