### ISSUE TITLE
Cannot find module 'next/babel' when "next" in .eslintrc

### ISSUE THREAD

**Issue by fated-x** [vercel/next.js#26541] opened 2021-06-23 18:18 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

next start

### Describe the Bug

I just updated Nextjs from v10.2.0 to 11.0.1. When I include "next" in my .eslintrc file (see "To reproduce" snippet below), every single file that ESLint is monitoring shows an error on line 1 stating "Parsing error: Cannot find module 'next/babel'".

This error blocks all other real ESLint errors so until I get this sorted out, I have to add "next" to my .eslintrc file, run `npm run lint` to get the proper output in the CLI and then remove "next" right before I commit my code. Not ideal.

I should also mention that I already had ESLint installed and configured prior to the changes Next v11 introduced.

And the error message:
![image](https://user-images.githubusercontent.com/14049283/123147615-7dd1b400-d41c-11eb-9724-b90aee1a8e4b.png)

### Expected Behavior

I expect to see only actual ESLint errors appearing in my files.

### To Reproduce

Add "next" to the .eslintrc file:

```
{
  ...
  "extends": ["plugin:react/recommended", "airbnb", "next", "prettier"],
  ...
}
```

**Comment by anthonyshew** [comment] 2021-06-24 06:03
I tried upgrading to v11 from v10 and ran into the same thing. Same issue but using (almost) all defaults for babel, eslint, next.config.js, etc.

The only difference from defaults that I have going is that my `.babelrc` looks like:
```
{
    "presets": [
        "next/babel"
    ],
    "plugins": [
        [
            "styled-components",
            {
                "ssr": true
            }
        ]
    ]
}
```

I tried removing the preset there as well to no avail.

Plz, halp! Must lint! :)

**Comment by housseindjirdeh** [comment] 2021-06-28 20:51
Duplicate of #26406

@fated-x @anthonyshew Can you try uninstalling the ESLint VSCode extension as mentioned [here](https://github.com/vercel/next.js/issues/26406#issuecomment-866408725) and see if that fixes the issue? If you are not seeing these errors in the terminal when you run `npm run lint` but only in your editor, then it sounds like something the extension may be doing.

Please add any comments to #26406 if you need more help or if the above solution doesn't fix it.

**Closed by housseindjirdeh** 2021-06-28 20:51 UTC
Labels: kind: bug

**Comment by anthonyshew** [comment] 2021-06-29 22:31
@housseindjirdeh Yuuuuup, that fixed it! Thank you!

**Comment by balazsorban44** [comment] 2022-01-28 04:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
