### ISSUE TITLE
id attribute is not added to headings in MDX

### ISSUE THREAD

**Issue by chimit** [vercel/next.js#32158] opened 2021-12-06 06:52 UTC
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

v16.11.1

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying your application?

npm run dev

### Describe the Bug

In the [Using MDX](https://nextjs.org/docs/advanced-features/using-mdx#custom-elements) documentation, there is a code example:
```md
# H1 heading

## H2 heading

This is a list in markdown:

- One
- Two
- Three
```

And it's stated that "The above generates the following HTML:"

```html
<h1 id="h1-heading">H1 heading</h1>

<h2 id="h2-heading">H2 heading</h2>

<p>This is a list in markdown:</p>

<ul>
  <li>One</li>
  <li>Two</li>
  <li>Three</li>
</ul>
```

But in my case I get just `<h1>` tags without `id`'s.

### Expected Behavior

Output should include `id`'s on headings:
```html
<div id="__next">
  <h1 id="some-mdx-page">Some MDX page</h1>
  <h2 id="sub-header">Sub header</h2>
  <h3 id="another-header">Another header</h3>
</div>
```

### To Reproduce

`./pages/index.js`:
```jsx
import SomeMdxPage from './page.mdx'

export default function Home() {
  return (
    <SomeMdxPage />
  )
}
```

`page.mdx`:
```
# Some MDX page

## Sub header

### Another header
```

Output:
```html
<div id="__next">
  <h1>Some MDX page</h1>
  <h2>Sub header</h2>
  <h3>Another header</h3>
</div>
```

As you see, there are no `id`'s on `<h*>` tags.

My `package.json`:
```json
{
  "name": "docs",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@mdx-js/loader": "^1.6.22",
    "@next/mdx": "^12.0.4",
    "@tailwindcss/typography": "^0.4.1",
    "next": "12.0.4",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.0",
    "eslint": "7.32.0",
    "eslint-config-next": "12.0.4",
    "postcss": "^8.4.4",
    "tailwindcss": "^2.2.19"
  }
}
```

`next.config.js`:
```js
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    externalDir: true,
  },
}

const withMDX = require('@next/mdx')()
module.exports = withMDX(nextConfig)
```

**Comment by stefanprobst** [comment] 2021-12-06 07:30
mdx does not add heading ids out of the box (this is misleading in the docs i think), you'll need to add a plugin for that. this should work:

```js
const withMDX = require('@next/mdx')({
  options: {
    rehypePlugins: [
      require('rehype-slug')
    ],
  },
})
```

**Comment by chimit** [comment] 2021-12-06 08:40
Unfortunately, it doesn't work either because `rehype-slug` can't be loaded as a Common JS module:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module
```

**Comment by stefanprobst** [comment] 2021-12-06 08:51
`rehype-slug@4.0.1` should work - or you can try moving everything to esm in `next.config.mjs`.

**Comment by chimit** [comment] 2021-12-06 09:31
`next.config.mjs` is definitely the way to go! Thank you @stefanprobst!

**Comment by balazsorban44** [comment] 2021-12-06 17:12
Fixed in https://github.com/vercel/next.js/pull/32163

**Closed** 2021-12-06 17:12 UTC
Labels: good first issue, area: documentation

**Comment by balazsorban44** [comment] 2022-01-27 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
