### ISSUE TITLE
Regression of tippy.js between 13.4.10-canary.0 and 13.4.10-canary.1

### ISSUE THREAD

**Issue by damianfrizzi** [vercel/next.js#53151] opened 2023-07-25 08:26 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
Binaries:
  Node: 18.15.0
  npm: 9.6.6
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 13.4.12
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/damianfrizzi/nextjs-tippy-regression

### To Reproduce

- Clone the minimal repro
- Run `yarn dev` -> everything works fine
- Run `yarn build` and `yarn start` -> app crashes with _Application error: a client-side exception has occurred (see the browser console for more information)._

### Describe the Bug

We tried to upgrade to the latest Next.js and it broke pages that where using `@tippyjs/react`. 
**This only happens in production.** Everything works correctly in development.

Git bisect shows me that the regression was introduced between [13.4.10-canary.0 (good) and 13.4.10-canary.1 (bad)](https://github.com/vercel/next.js/compare/v13.4.10-canary.0...v13.4.10-canary.1).

### Expected Behavior

- The behaviour between development and production should be the same
- The app shouldn't crash in production

**Comment by crypt0miester** [comment] 2023-07-26 16:34
can confirm. having the same issue with tippy 4.2.6 on >13.4.10 as well. downgrading to =13.4.9 fixed it.

**Comment by focux** [comment] 2023-07-27 04:25
I'm experiencing this as well. It broke after upgrading the Next.js version and it works on development but not in production. Tippy's author also confirmed that this looks like a minification issue on Next.js https://github.com/atomiks/tippyjs-react/issues/379

**Comment by icyJoseph** [comment] 2023-07-27 08:10
Hi,

Disabling swcMinify fixes the issue:

- https://nextjs.org/docs/architecture/nextjs-compiler#minification

Which leads me to believe this is an issue with SWC, as [this playground](https://play.swc.rs/?version=1.3.71&code=H4sIAAAAAAAAA02OvQrDMAyEdz%2BFRgdCSn%2Bm0GTrXrqGDK0jpwbXCrZcCiXvXjvpEE0fd8fpFLnAMNk4GgcNfAUA01TDvkxkUXMNh4zejM%2FEx8wPYqZXDadSzELgZyLPoKNTbMjBlYLJcEM3oJfF0gkx4EVrVCyT0rSrmE5t%2Foc0oFuxr5Kh7iy7vtgkyWJlaZT%2F%2FGLNhcj7kKN3cB7MG3Zt3iV%2BhE9Hk9sAAAA%3D&config=H4sIAAAAAAAAA32VwXLjIAyG73mKjM%2B99rIPsLc%2BA0OMcMhi5EEijaeTd19BnNRt5Fw89v8hCSQhf%2B32%2B%2B5Effdn%2FyWv8jHZTJAf36LQnNheROl4noD6HCbu3u6UqSLOBZpyvYGOs03kMY9rTxlsz3dhEa8%2FzWweoC7pgN6XIF1EJFiCLNIYUvDz2neP45SBaKWJKu7KCImr7G0keFuzjJ%2F0w2%2FTD4gRZPfbxFgyITEMkDXHPcZoJwJztlnxUndqcyDUQlRYGJyZMk4qTy5wwCQxn6kD60yPDhQUMvQczqCZSSwxSyTHU87TsINDGYbWGb%2Bs4WxjsazEhEsriexW8XrEQGx8SVoKb3AjBze4JPe3ZfAmA5ecnu1OGNJGTf4BSAaiJUp2BM1vW%2BGln7as%2FUvLkLy0LM8Kl%2FbWTplgkKSaELyS2ZoZyBy0amZwpYea2V7bzoI30kfBgQHvpVcU1%2FQZuD9qQetoQK8Aqa%2F1WlfdgHncwg1eL8QL%2FFdOyXqDLStGy8dtSvN4wPgiwAh8RPdigZSCcRtnmRKXaZuX5EBaA5y6pFADz0NALgCjiW1WPvWGXA%2FxaIaIh%2B8x8Txv26ML9IGuxHWTdeNdWX4Ktbp1KEsxRkwn6h7Wj0Hc9r677v4DNkYPd1IGAAA%3D), somewhat shows.

What happens is that the className plugin from tippy gets resolved to an empty object when minifying, and there's no `fn` property on such empty object.

- https://github.com/atomiks/tippyjs-react/blob/master/src/className-plugin.js

**Comment by icyJoseph** [comment] 2023-07-27 08:13
I guess the course of action here is to track these (?):

- https://github.com/swc-project/swc/issues/7700
- https://github.com/swc-project/swc/issues/7710

And this, already closed, but related issue: https://github.com/vercel/next.js/issues/53096

**Comment by kdy1** [comment] 2023-07-28 13:55
This will be fixed by https://github.com/swc-project/swc/pull/7702

**Comment by shanehoban** [comment] 2023-07-31 21:01
This looks like it was [added, but then reverted in a canary release.](https://github.com/vercel/next.js/releases/tag/v13.4.13-canary.7)

Any further updates on this?

**Comment by shanehoban** [comment] 2023-08-03 21:49
Thanks for the work on this, but it seems the issue is not resolved with the changes contained in release 13.4.13-canary.13.

The error persists as described by the OP. Working locally, but errors out when built and run on production.

**Comment by Geminii** [comment] 2023-08-04 08:25
We are facing the same issue too 😭
Waiting for next version to upgrade 🙈

**Comment by clementgateaud** [comment] 2023-08-04 08:37
We are also facing this issue with Tippy 😰

**Comment by kdy1** [comment] 2023-08-06 20:23
Well, this is already fixed. I did `yarn add next@canary`.

@shanehoban Please retry

<img width="1840" alt="image" src="https://github.com/vercel/next.js/assets/29931815/18b4dda0-ac5a-4233-83b7-ecfe40aea080">

**Comment by kdy1** [comment] 2023-08-07 13:16
@shanehoban Please provide a repro

**Comment by kdy1** [comment] 2023-08-07 15:23
@shanehoban 
<img width="1840" alt="image" src="https://github.com/vercel/next.js/assets/29931815/9ec947c0-4c64-4f2c-a9f4-a016dbf882c2">

I did
 - clone
 - `npm ci`
 - `rm -rf .next && yarn next build && yarn next start`

**Closed by kdy1** 2023-08-07 15:23 UTC
Labels: template: bug, area: SWC Minify

**Comment by shanehoban** [comment] 2023-08-07 15:31
Not sure why it's working for you but not others, or myself:

![image](https://github.com/vercel/next.js/assets/1383797/dc21db1d-287f-44f6-a10d-f77bf02180f7)

**Comment by icyJoseph** [comment] 2023-08-07 15:43
Works for me too, using:

```
  Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.7.1
      Yarn: 1.22.19
      pnpm: 7.22.0
    Relevant Packages:
      next: 13.4.14-canary.0
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

**Comment by shanehoban** [comment] 2023-08-07 15:45
I deployed my github repo above, and it fails on vercel, this isn't completely closed yet I would imagine:

https://nextjs-tippy-issue.vercel.app/

Deployment ID: DG1D2kjN5QVhNNgp1bEXorZecWHy

**Comment by leffot** [comment] 2023-08-10 11:18
Can report that we're having the same issue here. Works locally and fails in production.

**Comment by kdy1** [comment] 2023-08-10 12:10
@leffot Please provide a repro

**Comment by shanehoban** [comment] 2023-08-10 12:33
@kdy1 have you tried deploying [this repo](https://github.com/vercel/next.js/issues/53151#issuecomment-1668071851) to vercel? The issue is present when deployed even though it works for you locally.

**Comment by kdy1** [comment] 2023-08-10 12:35
@shanehoban Yes it works

**Comment by shanehoban** [comment] 2023-08-10 12:43
It doesn't though?

![image](https://github.com/vercel/next.js/assets/1383797/f058d141-c8b2-47a8-9085-a730c7fdc43a)

https://nextjs-tippy-issue.vercel.app/

On version `13.4.14-canary.1`

Repo deployed: https://github.com/shanehoban/nextjs-tippy-issue

**Comment by icyJoseph** [comment] 2023-08-10 14:06
Does it fail locally for you @shanehoban? What Node version does the deployed version use?

**Comment by shanehoban** [comment] 2023-08-10 15:12
@icyJoseph Yeah it fails for me when built and run locally for prod.

I'm on Node `v18.17.0` on my local machine (Ubuntu via WSL) and vercel node is set to `18.x`
