### ISSUE TITLE
[Feature](Docs) Give names to anonymous arrow functions in docs examples

### ISSUE THREAD

**Issue by awareness481** [vercel/next.js#17200] opened 2020-09-18 13:05 UTC
For example, in [api-routes](https://nextjs.org/docs/api-routes/introduction)

we have this example

```js
export default (req, res) => {
  res.statusCode = 200
  res.setHeader('Content-Type', 'application/json')
  res.end(JSON.stringify({ name: 'John Doe' }))
}
```

Exporting **anonymous** functions is arguably bad practice. If this agreed upon, I think any examples containing anonymous exports should be changed to use named functions

**Comment by timneutkens** [comment] 2020-09-21 12:44
Feel free to send a PR.

**Comment by Jashnm** [comment] 2020-09-30 19:08
Hey, if this issue is not assigned to anyone, can I take this up?
If yes, should I use arrow functions or regular functions?

**Comment by timneutkens** [comment] 2020-09-30 20:30
Regular functions is fine!

**Comment by awareness481** [comment] 2020-10-01 06:32
Obviously the PR is going to be reviewed by one of the Next.js maintainers but I wanted to say that it looks good to me. Nice contribution @Jashnm !

**Closed** 2020-10-05 21:16 UTC
Labels: good first issue

**Comment by lcswillems** [comment] 2020-10-28 14:23
Why is exporting anonymous functions a bad practice? @awareness481

I have a lot of anonymous functions and now Next.js aks me to rename all of them even if they have no impact on fast refresh.

**Comment by ljosberinn** [comment] 2020-11-06 13:53
@lcswillems 
- named exports are better for treeshaking
- the barrier of renaming named exports is larger than for default exports, but even then, a named export is find-and-replace-able:

```js
import something from 'somewhere' // Something is internally called foo though
import { foo as something } from 'somewhere' // can find-replace foo easily here
```
this goes hand in hand with better refactoring support in editors

- named exports usually have better autocompletion support for editors (although this is changing)

Personally, I consider default exports to be bad practice because of mentioned reasons and actively lint against them. In places where I _have to_ use default exports, e.g. nextjs pages, I `// eslint-disable-next-line import/no-default-export`.

**Comment by lcswillems** [comment] 2020-11-06 18:24
Thank you for your answer @ljosberinn !

**Comment by balazsorban44** [comment] 2022-01-29 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
