### ISSUE TITLE
Using Preact example is broken -- no scheduler module

### ISSUE THREAD

**Issue by OmerWow** [vercel/next.js#33562] opened 2022-01-22 13:45 UTC
### What example does this report relate to?

using-preact

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

17

### What browser are you using?

Brave, Safari

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel & next dev

### Describe the Bug

The Using-Preact example is broken, it throws an error: Error: Cannot find module 'scheduler/package.json'.

I saw that there are other issues open regarding this problem but they offer a fix that doesn't work anymore, which is just installing scheduler as a dependency/dev dependency.

I really want to switch to Preact, is that not possible anymore?

### Expected Behavior

Everything should just work with Preact instead of React.

### To Reproduce

Just clone and run the example or follow the installation steps in your own repo.
It's simply broken.

Also you can open the example StackBlitz link from it's README.md and you'll get the same error.

**Comment by balazsorban44** [comment] 2022-01-23 23:06
Duplicate of #31240

**Closed by balazsorban44** 2022-01-23 23:06 UTC
Labels: area: examples, template: bug
