### ISSUE TITLE
v12.1.5 regression with apollo client in SSR

### ISSUE THREAD

**Issue by macrozone** [vercel/next.js#36115] opened 2022-04-13 08:58 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
  Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64
    Binaries:
      Node: 14.19.1
      npm: 6.14.16
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.5
      react: 17.0.2
      react-dom: 17.0.2
```

### Describe the Bug

we use the classic approach of doing ssr with @apollo/client where it runs getDataFromTree on the server and hydrates the client in a getInitialProps function.

when I upgraded next from 12.1.4 to 12.1.5 this broke:

```
Error while running `getDataFromTree` Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClient instance in via options.
    at new InvariantError (/path/project/node_modules/@apollo/client/node_modules/ts-invariant/lib/invariant.esm.js:12:28)
    at Object.invariant (/path/project/node_modules/@apollo/client/node_modules/ts-invariant/lib/invariant.esm.js:24:15)
    at useApolloClient (/path/project/node_modules/@apollo/client/react/hooks/useApolloClient.js:7:15)
    at useQuery (/path/project/node_modules/@apollo/client/react/hooks/useQuery.js:13:18)
    at useAssortment (webpack-internal:///./src/modules/categories/hooks/useAssortment.ts:31:97)
    at CategoryPage (webpack-internal:///./src/modules/categories/components/ShopRegularCategory.tsx:56:122)
    at processChild (/path/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/path/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/path/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/path/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29) {
  framesToPop: 1
}
```

### Expected Behavior

this kind of setup should not be affected by a patch-release

### To Reproduce

will try to provide later, i still need to gather information and try to find out which actual change is the root cause o this bug.

**Comment by KATT** [comment] 2022-04-14 00:51
Thanks - got the same issue in tRPC.

## Repro:

1. `yarn create next-app --example https://github.com/trpc/trpc --example-path examples/next-prisma-starter trpc-prisma-starter`
2. `yarn dx`

### Expected 

App works without errors 

### Actual

App errors.


Try updating `package.json` to hard dep of `12.1.4` and it works fine.


---

For the easy server-side rendering in tRPC/Apollo/urql we all rely on `getInitialProps` and doing prepasses on the React-tree to fetch data on the server. tRPC uses [react-ssr-prepass](https://www.npmjs.com/package/react-ssr-prepass).

**Comment by macrozone** [comment] 2022-04-14 06:34
has anyone an idea what this could be?

Usually this kind of error arises, when usages of  apollo's `useQuery` do not find the client in the context. Or if they find a different version. I verified that i have only one version of apollo/client in my yarn.lock.

**Comment by balazsorban44** [comment] 2022-04-14 08:48
Thanks for the repro, but for completeness, @macrozone could you also add one?

FWIW @KATT, I think `react-query` only recently started supporting React 18 in their v4 beta: https://github.com/tannerlinsley/react-query/releases/tag/v4.0.0-beta.1. Not sure yet if related, but I wanted to mention it.

**Comment by macrozone** [comment] 2022-04-14 09:06
> Thanks for the repro, but for completeness, @macrozone could you also add one for your case?
> 
> FWIW @KATT, I think `react-query` only recently started supporting React 18 in their v4 beta: https://github.com/tannerlinsley/react-query/releases/tag/v4.0.0-beta.1. Not sure yet if related, but I wanted to mention it.

Not sure if I can provide one in the next few hours or days. One important thing to know is, that its not about react 18. Its happening with react 17.

conceptually my case is very similar to the one @KATT provided with his `TRPC` example. There the `App` component in `pages/_app` is wrapped in a HOC `withTRPC` which provides the right context and collects data on SSR to hydrate the client cache. My guess is that there might be a problem how the App-component of `_app` is mounted

**Comment by KATT** [comment] 2022-04-14 10:03
> FWIW @KATT, I think `react-query` only recently started supporting React 18 in their v4 beta: https://github.com/tannerlinsley/react-query/releases/tag/v4.0.0-beta.1. Not sure yet if related, but I wanted to mention it.

Official support, yes, but they have run their tests with react 18 for ages


---

I made a better repo (which is using react 17 as well).

- CI passes: https://github.com/KATT/next.js-issues-36115
- PR only with Next.js upgrade, CI fails: https://github.com/KATT/next.js-issues-36115/pull/3

I've invited you as a contributor, @balazsorban44, so if you wanna test a new canary or something, feel free to open a new PR that runs through the E2E test suite.

**Comment by balazsorban44** [comment] 2022-04-14 10:43
Thank you, will have a look!

**Comment by klarstrup** [comment] 2022-04-14 13:56
Happened upon this myself in my `react-query` SSR setup 

Seems like the `AppTree` passed to `_app`'s `getInitialProps` has changed between 12.1.4 and 12.1.5 - the `_app` (default export) component tree doesn't seem to be applied to it any more.

**Comment by imkrunal** [comment] 2022-04-16 04:49
@KATT I have tested with `next@12.1.6-canary.2` same issue.

**Comment by klarstrup** [comment] 2022-04-18 19:43
My tests are now passing again as of `next@12.1.6-canary.3`! (https://github.com/vercel/next.js/pull/36206 & https://github.com/vercel/next.js/issues/36198)

**Comment by klarstrup** [comment] 2022-04-20 12:18
It's @macrozone's issue, but I believe so yes

**Comment by timneutkens** [comment] 2022-04-20 12:30
Okay then I'll close it and @balazsorban44 can re-open if @macrozone is still running into it 👍

**Closed by timneutkens** 2022-04-20 12:30 UTC
Labels: type: needs investigation, template: bug

**Comment by KATT** [comment] 2022-04-20 12:37
Confirmed fixed in https://github.com/KATT/next.js-issues-36115/pull/4

**Comment by HananoshikaYomaru** [comment] 2022-04-29 07:19
hope next@12.1.6 will come soon

**Comment by vinamelody** [comment] 2022-05-15 14:57
Thanks for the potential future fix!
fyi, i got this error at first `Error while running `getDataFromTree` Invariant Violation: Could not find "client" in the context or passed in as an option.` due to `@apollo/client` version 3.6.2

however, i had to downgrade due to https://github.com/apollographql/apollo-client/issues/9456

The error msg then changed to `Error while running `getDataFromTree` Invariant Violation: Could not find "client" in the context or passed in as an option.` and led me here
