### ISSUE TITLE
Public assets with subPath don't work in production build

### ISSUE THREAD

**Issue by marcin-piela-sf** [vercel/next.js#17176] opened 2020-09-17 12:37 UTC
# Bug report

Public assets with subPath don't work in production build

## To Reproduce

1. ```npx create-next-app```
2. Add `next.config.js` with content
```js
module.exports = {
  basePath: '/test/sub-path',
  trailingSlash: false,
}
```

3. Edit file `pages/index.js` and replace line
```js
<img src="/vercel.svg" alt="Vercel Logo" className={styles.logo} />
```
with
```js
<img src="/test/sub-path/vercel.svg" alt="Vercel Logo" className={styles.logo} />
```
4. Run dev application `npm run dev` - everything works fine
5. Run prod application `npm run build` `npm run start` - static image asset doesn't work - 404

## Expected behavior

Public assets should work in dev and prod

## System information

- OS: macOs
- Version of Next.js: 9.5.3
- Version of Node.js: v13.14.0

**Comment by richardhomewood** [comment] 2020-09-17 23:47
I am experiencing the exact same issue today on an identical system.

Interestingly, building a static site with `next export` does work, which leads me to believe it's the `next server` module itself where the bug lies.

**Comment by marcin-piela-sf** [comment] 2020-09-18 06:58
Yes, and it works on 9.5.2 correctly

**Comment by marcin-piela-sf** [comment] 2020-10-12 07:26
Any progress on it?

**Comment by colinhemphill** [comment] 2020-10-15 15:31
This is also preventing us from upgrading past 9.5.2. I see that a PR was already opened, but I may take a crack at it if it will get us moving forward on this fix.

**Comment by ricardoGlobant** [comment] 2020-10-15 18:37
Is there any workaround for this issue while the fix is ready?

**Comment by IkeLutra** [comment] 2020-10-21 10:14
@ricardoGlobant I have worked around this by using the custom server setup of Next JS and using express static to serve those files. This is _ok_ but obviously comes with all the downsides of using a custom server.

https://nextjs.org/docs/advanced-features/custom-server
https://expressjs.com/en/starter/static-files.html

**Comment by ijjk** [comment] 2020-12-01 20:01
Hi, this appears to be a duplicate of https://github.com/vercel/next.js/issues/17889 which was corrected in https://github.com/vercel/next.js/pull/18715 so I'm going to close this, please upgrade to the latest version of Next.js `v10.0.3` and give it a try!

**Closed by ijjk** 2020-12-01 20:01 UTC
Labels: good first issue, kind: bug

**Comment by balazsorban44** [comment] 2022-01-29 02:12
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
