### ISSUE TITLE
[NEXT-684] Fast-refresh for CSS files is not working in Firefox

### ISSUE THREAD

**Issue by lucasmotta** [vercel/next.js#43396] opened 2022-11-25 19:45 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.1.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.14.2
    Relevant packages:
      next: 13.0.6-canary.1
      eslint-config-next: 13.0.5
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

So I just started a new next.js app using the `v13.0.5` with the experimental `app` folder.  I noticed that CSS changes are not correctly updated in the browser. The browser is notified of the change, but the styles are not applied - if I manually refresh the browser I can see the correct styles.

I also tried the canary version and the error still exists. Moving to `v13.0.4` seems to work fine.

And I also tried with Tailwind following the beta documentation and also it doesn't work.

### Expected Behavior

Updating styles should fast refresh and update the page with the new styles.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://stackblitz.com/edit/vercel-next-js-viybne?file=app/global.css

### To Reproduce

Open the `global.css` file, change the colors and save the file.

You can see it working with the 13.0.4:
https://stackblitz.com/edit/vercel-next-js-6sncvk?file=app/global.css

<sub>[NEXT-684](https://linear.app/vercel/issue/NEXT-684/fast-refresh-for-css-files-is-not-working-in-firefox)</sub>

**Comment by Svish** [comment] 2022-11-27 20:16
Been trying to get started with a [Next@13 + Sanity@v3](https://vercel.com/templates/next.js/blog-nextjs-sanity) setup today. Things seemed to be working fine until I tried to change the Tailwind styling...

Can confirm that HMR for Tailwind with Next > `13.0.4` definitely does _not_ work properly. More specifically, versions above `13.0.4` seems to break the JIT-compiler of Tailwind? That is, given the following `src/app/page.tsx file:

```ts

export default function Home() {
  return (
    <>
      <div className="text-3xl font-bold underline bg-indigo-500">
        Hello world!
      </div>
      <div className="text-3xl font-bold underline bg-indigo-700">
        Hello world!
      </div>
      <div className="text-3xl font-bold underline bg-indigo-700">
        Hello world!
      </div>
    </>
  )
}
```

If I change the classes and save the file, the browser does update immediately, but I change to a previously unused class, then the styling just doesn't apply at all.

For example, changing the color of the last `div` between `bg-indigo-500` and `bg-indigo-700`, classes already used on the other two divs, results in the color updated correctly on save. But if I change it to a different one, for example `bg-indigo-200`, the background color just disappears. Hard refreshing the page, _seems_ to get the new background color to turn up, but there have been a few times where it didn't, and I had to actually restart the dev-server... 

Guessing a link between Tailwind/PostCSS and Next is broken or something? 🤷‍♂️

**Comment by spencer5051** [comment] 2022-11-27 20:49
Same issue here. You can use the solution for Turbo Pack (concurrently) in the mean time.

npm install --save-dev concurrently

{
  "scripts": {
    "dev": "concurrently \"next dev --turbo\" \"tailwindcss --input input.css --output output.css --watch\"",
    "build": "tailwindcss input.css --output output.css && next build"
  }
}

https://beta.nextjs.org/docs/styling/tailwind-css

**Comment by Svish** [comment] 2022-11-27 20:52
For now I have just downgraded to `13.0.4`, where it at least _seems_ to work. Not sure what I'm missing from Next-wise from the versions above though... 🤔

**Comment by MattL-NZ** [comment] 2022-11-28 04:41
Can confirm I am experiencing the same issues with 13.0.5 and tailwind as reported by @Svish. Going back to 13.0.4 is fine.

**Comment by thesampaton** [comment] 2022-11-29 10:31
Just did some preliminary investigation, the defect looks to have been introduced in 13.0.5-canary.4

The canary versions prior to that do not have the issue, a few updates to the hot reloader types in that release

**Comment by volnei** [comment] 2022-12-01 18:17
For me it's not working even in previous versions :(

**Comment by rijk** [comment] 2022-12-01 18:18
Same, for me it has never worked on v13. Tailwind works but JIT classes are not added until you refresh the page.

**Comment by iamjohnlong** [comment] 2022-12-08 15:43
Tailwind and HRM working is on `v13.0.4-canary.5` for me but I can't get it working on anything above it.

**Comment by ciruz** [comment] 2022-12-09 16:16
> Tailwind and HRM is working on `v13.0.4-canary.5` for me but I can't get it working on anything above it.

Just tested different next.js versions with tailwind because of the hot reload error and for me it works with ``13.0.4-canary.5`` (pre release) and ``13.0.4`` (release), but is broken with ``13.0.5-canary.0``.

**Comment by jimbits** [comment] 2022-12-11 16:20
Downgrading to 13.0.4-canary.5 worked for me. MACOS Big Sur 11.4 Intel.
"dependencies": {
    "@types/node": "18.11.13",
    "@types/react": "18.0.26",
    "@types/react-dom": "18.0.9",
    "eslint": "8.29.0",
    "eslint-config-next": "13.0.6",
    "framer-motion": "^7.6.19",
    "next": "^13.0.4-canary.5",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "4.9.4"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.13",
    "postcss": "^8.4.19",
    "tailwindcss": "^3.2.4",
    "concurrently": "^7.6.0" 
  }

**Comment by rijk** [comment] 2022-12-12 09:56
> Just did some preliminary investigation, **the defect looks to have been introduced in 13.0.5-canary.4**
> 
> The canary versions prior to that do not have the issue, a few updates to the hot reloader types in that release

Okay, just did some testing and can confirm this. I don't know how you tested, I just added a `<strong className="text-[#22bdec]">test</strong>` element with a different hex code each time. From `13.0.5-canary.4` the text is black after the hot reload, instead of the new color.

**Comment by rijk** [comment] 2022-12-12 10:06
Digging into the changes, I think this is the culprit:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/159500/207018028-0854f556-8551-4480-b8a5-8123c799ec29.png">

Because I see the 'cache buster' suffix is no longer added to the stylesheet, making the browser unaware that its contents changed. If I refresh the stylesheet manually in a second tab, I do see the new class added to it.

**Comment by huozhi** [comment] 2022-12-15 20:40
We land a fix in 13.0.8-canary.0. Could you upgrade to to see if the hmr is fixed for you?

**Comment by mmiszy** [comment] 2022-12-15 20:49
@huozhi HMR is indeed working in 13.0.8-canary.0 when using Tailwind.
There's a small issue, though: a flash of unstyled content before new styles are applied.

**Comment by MattL-NZ** [comment] 2022-12-15 21:13
@huozhi Working for me but I am also experiencing UI flashes similar to what @mmiszy mentioned.

**Comment by thesampaton** [comment] 2022-12-16 01:24
It seems to be working, though I hacked around some stuff so need to validate imported stuff again. Will update if I can repro issue again

**Comment by Svish** [comment] 2023-01-04 19:51
Tried to upgrade to version `13.1.1` now, but it's still broken, so I'm back at `13.0.4`. 😕

Saw the [Next.js 13.1 Explained!](https://www.youtube.com/watch?v=_q1K7cybyRk) video, where he showed off tailwind with `--turbo`, where it seemed to work, so hoped it would be fixed now, but... nope... ☹

**Comment by zhangwei900808** [comment] 2023-01-18 07:32
antd same problem

**Comment by akomm** [comment] 2023-01-20 13:54
I wonder, is there something preventing a fix from happening? Judging by the (comment)[https://github.com/vercel/next.js/issues/43396#issuecomment-1346206618] added with the change why it was changed it seems like "oh we just don't need it", but it appears we do need it to bust cache. What stops the devs from reverting this breaking change? Can we help somehow?

**Comment by MattHeslington** [comment] 2023-01-22 05:54
> I wonder, is there something preventing a fix from happening? Judging by the [comment](https://github.com/vercel/next.js/issues/43396#issuecomment-1346206618) added with the change why it was changed it seems like "oh we just don't need it", but it appears we do need it to bust cache. What stops the devs from reverting this breaking change? Can we help somehow? Or is there a more important reason why it was changed, that is not explained in the comment that explains the change, hence reversion isn't desired?

I'm staggered this issue was raised in November and we're now approaching the end of January without a fix

**Comment by akomm** [comment] 2023-01-23 11:06
@MattHeslington 

If https://github.com/vercel/next.js/issues/43396#issuecomment-1353690564 is correct and `13.0.8-canary.0` has/had it fixed, yet it didn't make it into the recent releases, including 13.1.X, maybe they encountered an issue with that. This is why I would approach this with doubt. It annoys me, but its beta. They have a lot things on the table. But its weird, if there is no problem why it was not simply reverted until a better solution for what the removal wanted to achieve is found.

**Comment by laneme** [comment] 2023-01-24 13:40
Can confirm the issue exist on `13.1.1` & `13.1.5`.

**Comment by laneme** [comment] 2023-01-25 03:28
> Hi all, I can't reproduce the bug in latest canary `13.1.6-canary.0`.
> 
> Here's the playground: https://stackblitz.com/edit/vercel-next-js-qjrbnv?file=app%2Fglobal.css And here's a recording of it working: https://share.cleanshot.com/w86DpQbb
> 
> If anyone can reproduce it, please fork that StackBlitz project and let me know, thanks!

Dint work for me, the issue exist in you playground. Are you using firefox? Seem to be only affecting firefox

**Comment by akomm** [comment] 2023-01-25 09:25
I have the bug still in the unmodified playground you've provided.

Might be as mentioned FF specific? I have FF **109.0**.

**Comment by shuding** [comment] 2023-01-26 15:53
So based on @laneme and @akomm's feedback the issue can be reproduced on Firefox only. I'll investigate that specifically. Thanks all!

**Comment by laneme** [comment] 2023-01-31 20:42
@shuding might as well take a look back at https://github.com/vercel/next.js/issues/43878, that thread still active

**Comment by cdedreuille** [comment] 2023-02-01 09:04
@shuding Here is a codesandbox to reproduce the issue even on Chrome.

https://codesandbox.io/p/sandbox/quizzical-austin-9rcihp?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A10%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A10%7D%5D&file=%2Fpages%2Ftest.tsx

If appDir is set to false, tailwind updates without any issue when you save the file. But if appDir is set to true then I have to reload every time to see the update. I just want to make it clear that this is happening for me on the pages routing system. In my case, I have Sanity in the new app folder and I have to keep my site in the pages folder because the 'as' property is not there yet in the new routing. I hope this makes sense.

To reproduce it, try to always use custom colours for example `bg-[#ffd000]`

I also made a video to show the issue just in case: https://share.cleanshot.com/rWbx5WHx

**Comment by shuding** [comment] 2023-02-01 19:55
@cdedreuille Thanks for your reproduction! However, I saw `next@13.0.0` in your codesandbox.  I forked your sandbox and upgraded Next.js and I can't reproduce any HMR problem:


https://user-images.githubusercontent.com/3676859/216149417-009f68f8-6946-4350-b809-1f5663103900.mp4



Please make sure to provide a reproduction on the latest canary, thanks! 🙏

**Comment by Nathanael-Shermett** [comment] 2023-02-01 22:48
> Were you able to produce this bug yourself yet? If not, might wanna take a look at windows. I noticed a lil bit of different behavior on windows versus ubuntu https://github.com/vercel/next.js/issues/43878#issuecomment-1408260051

For whatever it's worth, I am having this issue also, and can consistently reproduce on Windows 11 with the latest version of Firefox (v109.0.1). Reloading loads the correct styles for me, contrary to what the person in the above comment mentioned.

As described by others, it works fine in Chrome and Edge.

**Comment by axmad386** [comment] 2023-02-02 07:29
> @cdedreuille Thanks for your reproduction! However, I saw `next@13.0.0` in your codesandbox.  I forked your sandbox and upgraded Next.js and I can't reproduce any HMR problem:
> 
> 
> https://user-images.githubusercontent.com/3676859/216149417-009f68f8-6946-4350-b809-1f5663103900.mp4
> 
> 
> 
> Please make sure to provide a reproduction on the latest canary, thanks! 🙏 

Hi, i see you are updating the tsx file which is nextjs aware of. But the problem is when we update the css file (imported on layout), nextjs won't update.

**Comment by shuding** [comment] 2023-02-02 11:23
@axmad386 I'll test! But here's what the OP said:

> To reproduce it, try to always use custom colours for example bg-[#ffd000]

**Comment by imranbarbhuiya** [comment] 2023-02-04 12:20
I'm also having the same issue with global css. I'm on `v13.1.6`

**Comment by frostypenguin0100** [comment] 2023-02-04 12:42
> 
https://github.com/vercel/next.js/issues/43396#issue-1464877520

**Comment by frostypenguin0100** [comment] 2023-02-04 12:42
``

**Comment by jeffrafter** [comment] 2023-02-04 18:56
I was able to reproduce this today on v13.1.6 (in firefox and Safari) and in the latest canary I am not seeing the problem. Is it possible to try with `v13.1.7-canary.4` or newer?

**Comment by laneme** [comment] 2023-02-04 20:10
> I was able to reproduce this today on v13.1.6 (in firefox and Safari) and in the latest canary I am not seeing the problem. Is it possible to try with `v13.1.7-canary.4` or newer?

Just tried the latest canary `v13.1.7-canary.5`, the issue still there ¯\\_(ツ)_\/¯

**Comment by ciruz** [comment] 2023-02-06 15:30
I tested different latest next.js releases.

For me on Windows 11, tested with and in Chrome, fast-refresh with tailwind is broken in:

- ``v13.1.6``
- ``v13.1.5``
- ``v13.1.4``
- ``v13.1.3``
- ``v13.1.2``
- ``v13.1.1``
- ``v13.1.0`` (tailwind totally broken)

It works with ``v13.0.7`` and I also tested a version below just to make sure, it works with ``v13.0.6`` too.

(disclaimer: no canary versions tested)

**Comment by laneme** [comment] 2023-02-06 16:33
@ciruz I think you might wanna test with firefox too, apparently the issue has been significantly more prominent in firefox

The issue still there in `v13.1.7-canary.6` for me. Though I only see it in firefox.

Would like re-add that, even though it doesnt happen in chrome for me, there is a flash of unstyled content for a moment. Wouldnt call it a `flash`, cause it stays for a good half second, maybe a lil less.

**Comment by shuding** [comment] 2023-02-06 17:10
@laneme I observed the same thing, that the problem exists in **Firefox only**. I think it's due to Firefox not respecting the cache header for CSS resources.

We are working on a proper fix for it in both React and Next.js.

**Comment by shuding** [comment] 2023-02-06 17:16
@rijk Thanks! I'm aware of that as I removed it. But currently we need to fix something in React, otherwise if we add back the `?ts=` query it will cause another bug (link tags with different queries will be added but old ones can't be removed upon HMR).

**Comment by shuding** [comment] 2023-02-08 16:31
> after the successful HMR, this is causing a full and complete browser reload, negating the benefits of HMR.

Was CSS the only changed part?

**Comment by laneme** [comment] 2023-02-16 10:47
Confirming the issue still exist on `13.1.7-canary.15` :man_shrugging:

**Comment by matteing** [comment] 2023-02-18 01:36
> @shuding just FYI everything was working fine before with this `cacheBustingUrlSuffix`:
> 
> ![](https://user-images.githubusercontent.com/159500/207018028-0854f556-8551-4480-b8a5-8123c799ec29.png)

Hi all, here to report that this change breaks Safari hot reloading referencing [this WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=193533). The CSS files are always loaded from memory, and Safari doesn't respect the "Disable Caches" setting.

**Comment by shuding** [comment] 2023-02-18 21:28
@matteing Which Next.js version you're on? With the latest canary, I don't see any problem on Chrome or Safari, can only reproduce it on Firefox.

**Comment by matteing** [comment] 2023-02-18 21:45
I’m in the latest stable version, and this is a problem that seems to only affect Safari after a couple of CSS changes w/ Tailwind.

Sent from my iPhone

On Feb 18, 2023, at 5:29 PM, Shu Ding ***@***.***> wrote:

﻿

@matteing<https://github.com/matteing> Which Next.js version you're on? With the latest canary, I don't see any problem on Chrome or Safari, can only reproduce it on Firefox.

**Comment by shuding** [comment] 2023-02-18 22:02
@matteing Then that's fixed (Safari support) in the latest canary: https://github.com/vercel/next.js/issues/43396#issuecomment-1419272476, right now only Firefox support is broken.

**Comment by 96312** [comment] 2023-02-20 14:21
Worst day to start learning next.js. Begun with next.js 13 because our professor asked us to start from there as it's "future proof".

Using firefox and tailwind, no fast refresh works. Tried edge, doesnt work either. What a waste of a couple of hours, I'm going to link this comment thread to my homework submission as an excuse why I got it late.

**Comment by laneme** [comment] 2023-03-04 14:27
Has there been any luck with this issue.

**Comment by darklight9811** [comment] 2023-03-05 05:12
Bug still present in `13.2.3`

**Comment by dboekhout** [comment] 2023-03-05 23:17
Im not entirely sure the issue is fixed on Safari. I mainly use Firefox but had to switch to Safari for a bit because of this issue, having to hard reload makes development tedious tbh. Now after some time my Safari refuses to update as well, even hard reloading doesn't work. I disabled cache in the inspection tools but no bueno.

**Comment by jasongerbes** [comment] 2023-03-06 01:57
I can confirm that this issue also affects development in Safari. These steps reliably reproduce the issue for me:

1. Create a Next 13.2 project using the `/app` directory.
2. Add Tailwind using [the official guide](https://tailwindcss.com/docs/guides/nextjs).
3. Run `npm run dev` and open http://localhost:3000 in Safari.
4. Change the `className` of an element (e.g. `bg-red-400`) repeatedly until the CSS stops updating.

During step 4, be sure to use a unique class name each time (e.g. choose different background color variations that aren't already used anywhere across the site). Eventually, usually after repeating step 4 for around five or six times, Safari will no longer reflect changes to the CSS (i.e. classes that have been automatically added by Tailwind).

Refreshing the page doesn't resolve the issue, and you have to manually empty the page cache (`⌥ ⌘ E`) and then refresh the page to load the new styles.

P.S. I've noticed that Safari is caching `app.css` despite the `Cache-Control: no-store, must-revalidate` header. Other "disable cache" headers across Next.js use `Cache-Control: no-cache, no-store, max-age=0, must-revalidate` - so this may be worth looking into.

![image](https://user-images.githubusercontent.com/13686180/223002045-478d10e4-4bf0-4113-88bc-adf31add82ab.png)

**Comment by chrisyalamov** [comment] 2023-03-08 15:58
Aggressive caching in Safari seems to be a long-standing problem (see [here](https://stackoverflow.com/questions/48693693/macos-safari-caching-response-while-headers-specify-no-caching), [here](https://discussions.apple.com/thread/251817133) and [here](https://stackoverflow.com/questions/49547/how-do-we-control-web-page-caching-across-all-browsers/2068353#2068353)).

The [last link](https://stackoverflow.com/questions/49547/how-do-we-control-web-page-caching-across-all-browsers/2068353#2068353) suggests using a `Vary: *` header (the current value seems to be `Accept-Encoding`).

**Comment by opr-inzn** [comment] 2023-03-10 22:48
I have this issue (13.2.4) in Safari and Chrome as well!

**Comment by darklight9811** [comment] 2023-03-16 12:58
Can confirm this issue is still present in `13.2.5-canary.4`

**Comment by darklight9811** [comment] 2023-03-16 13:00
@jasongerbes cache bursting with query variables or hashes should work in fixing this, right?

**Comment by Kais3rP** [comment] 2023-03-16 13:59
Issue still present 13.2.4, Edge, Chrome and FFox.

**Comment by OfirYC** [comment] 2023-03-25 05:34
i'm not sure how related this is - But on my end (tw@3.2.7, next@13.2.3, Chrome) some elements do not appear on the first paint (like, at all) - and they would only appear if i make a classname change to a parent element and then hot reload... This happens both on the dev server and on build.

I am also getting the initial style-lacking flashes like some others mentioned

**Comment by sx-motive** [comment] 2023-03-29 14:03
chrome and safari working fine for me, but firefox isn't next@13.2.4 😓

**Comment by GonzaloZiadi** [comment] 2023-04-02 05:56
Also affected by this issue. Using Firefox. Deleting .next directory and rebuilding fixes it but is a pain.

**Comment by malviyaritesh** [comment] 2023-04-06 10:45
I was also facing this issue with tailwindcss. I'm using Next 13.2.4 and Safari 16.4.

After some research, I managed to workaround this issue by adding following in `next.config.js`:

```js
headers:
    process.env.NODE_ENV === 'development'
      ? () => [
          {
            source: '/_next/static/css/_app-client_src_app_globals_css.css',
            headers: [{ key: 'Vary', value: '*' }],
          },
        ]
      : undefined,
```  

> `Vary: *`
> Indicates that factors other than request headers influenced the generation of this response. Implies that the response is uncacheable.  

This is working perfectly for me. You can read more about `Vary: *` on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary).

**Comment by ncinme** [comment] 2023-04-06 12:10
This is awesome @malviyaritesh. I confirm that with your solution, it is working for me with the latest Next.js v13.2.4 and tailwindcss 3.3.1 on both Chrome and Edge browsers.

**Comment by stathis1998** [comment] 2023-04-06 12:15
Works perfectly thank you!

**Comment by Spacey4K** [comment] 2023-04-09 11:45
Issue still exists in Next 13.3.0 and Firefox 111.0.1

**Comment by Anshuman115** [comment] 2023-04-09 13:31
> Issue still exists in Next 13.3.0 and Firefox 111.0.1

Yes same for me in my firefox, already tried reinstalling the next app, removed tailwind and reinstalled it using official tailwind docs. Still its not working.

**Comment by timneutkens** [comment] 2023-04-09 17:26
Hey, you don't have to comment saying an issue still exists in "version x" because the issue is still open it is not fixed. Thanks!

**Comment by darklight9811** [comment] 2023-04-09 18:46
@timneutkens I think it's valid, so the issue doesn't get tagged as stale and ends up thrown in stale oblivion (forgotten).

**Comment by timneutkens** [comment] 2023-04-10 07:14
<img width="221" alt="CleanShot 2023-04-10 at 09 13 16@2x" src="https://user-images.githubusercontent.com/6324199/230848009-688c0c6d-13d3-40b7-a76c-08ac997f909f.png">

When these labels are added it'll never be set as stale as it's triaged, we're aware of it, and no further action is needed as it's already being tracked.

**Comment by darklight9811** [comment] 2023-04-10 18:54
@malviyaritesh your fix stopped working between the latest releases

**Comment by timneutkens** [comment] 2023-04-10 19:31
Adding the vary header has no effect on this issue, it needs special handling in React which is something we're looking into.

**Comment by stephtr** [comment] 2023-04-16 23:44
I also noticed that importing the global.css file from a server component (as also done in the starter template) didn't enable fast-refresh with --turbo. Once I moved the import into a client component, fast-refresh is working, without the header setting. Using Edge @13.2.4

**Comment by akomm** [comment] 2023-04-17 11:15
@malviyaritesh 

I'm not sure if the workaround really works. On my end it does not help. I see people say it works, but can they verify the following: check the css file generated by TW and see if the utility you test against fast-refresh isn't in the file already. TW in development does not truncate the utilities, so when you used them once for testing of fast-refresh and then changed back, the utility still remains in the css file and when you test it later again, it appears to work, but in fact it doesn't.

The problem here is not that FF is loading the cached file, but that it doesn't even know it has to recheck it. Because it will only consult the cache if it sees a reason for fetching the file again. So actually changing the vary header shouldn't have any effect on the problem, because FF is never going to consult caching settings if it doesn't even see a reason to reload the file.



The workaround doesn't do anything on my end. Because the problem isn't caching, but the browser doesn't know it has to reload the file (at which point it would consult cache and settings).

**Comment by valentincostam** [comment] 2023-04-23 23:05
I updated Next.js to 13.3.1 (which includes #48578) and fast-refresh doesn't work. When I change a Tailwind class, the browser notices the changes but the styles are not applied. I have to refresh the page manually.

Did I miss anything? Is anyone experiencing the same?

Tried on:

- Windows 11 Pro 22H2 Build 22621.1555
- WSL2: Ubuntu 20.04
- Firefox 112.0.1
- Brave 1.50.121 (Chromium: 112.0.5615.138)

**Comment by akomm** [comment] 2023-05-02 13:57
Whoever still copes with the issue, here's the fix:

The issue is still present, but you can circumvent the issue by integrating tailwind differently. I'm not sure if this method was available before, but at least since next 13.3.1 you can integrate it via postcss as a plugin. Then instead of importing the TW **output** css file, you import the TW **input** css file. The webpack loader chain this way recompiles the input file and reloads the link properly.

It has been added to the docs: https://beta.nextjs.org/docs/styling/tailwind-css

**Comment by eduardochiaro** [comment] 2023-05-08 06:08
@akomm followed what you said it works, but I notice that the issue is still present if you use `scss` instead if `css` as global file. Issue with SASS i guess, but it seems to work fine if applied to a `pages` page instead.

**Comment by akomm** [comment] 2023-05-08 09:41
@eduardochiaro I did not test it with scss, but did you integrate scss as postcss plugin? Can you also verify that the postcss plugin is used and just scss->css->style loaders that would normally by used when you globally import scss in next?

**Comment by eduardochiaro** [comment] 2023-05-08 15:55
@shuding I created this https://github.com/eduardochiaro/test-sass
I set up 2 pages, one under `app` folder, the other under `pages` folder. Both using same `scss` global file and component.
To test, open homepage `/` and also `/test` page. 
**`http://localhost:3000/`** use `app` folder, 
**`http://localhost:3000/test`** use `pages` folder.

Using `next dev` make a change on `\src\app\Component.tsx`. the change need to be a tailwind call not used before. Hot reload will trigger on `http://localhost:3000/test` but not on `http://localhost:3000/`.

**Closed** 2023-05-09 16:28 UTC
Labels: kind: bug, area: app, linear
