### ISSUE TITLE
What is an alternative to the revalidate feature

### ISSUE THREAD

**Issue by bryandandan** [vercel/next.js#17192] opened 2020-09-17 21:59 UTC
Given that revalidate is still experimental, how can we pre-fetch data from a headless CMS? It is said in the documentation to use getStaticProps but it doesn't work since we have to redeploy the app everytime the database changes.

**Comment by jamesmosier** [comment] 2020-09-17 23:51
Hi @bryandandan. `revalidate` is not experiment anymore and is in the official [docs](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation)! So definitely give it a try and it should work well for your use case 😄 

I'll close this issue in favor of the discussion https://github.com/vercel/next.js/discussions/17191

**Closed by jamesmosier** 2020-09-17 23:51 UTC

**Comment by balazsorban44** [comment] 2022-01-29 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
