### ISSUE TITLE
[NEXT-855] [AppDir] Interacting with Client Component before page fully load cause Hydration failed error.

### ISSUE THREAD

**Issue by lelabo-m** [vercel/next.js#45047] opened 2023-01-19 15:26 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Nov 23 01:01:46 UTC 2022
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: N/A
      pnpm: 7.25.1
    Relevant packages:
      next: 13.1.3-canary.5
      eslint-config-next: 13.1.3-canary.5
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

NA

### To Reproduce

Create a new app: `pnpm dlx create-next-app@latest --experimental-app`

Create a client component:
```typescript
"use client";

export function ClientComponent() {
  return (
    <button
      onClick={() => {
        console.log("clicked");
      }}
    >
      Test Client Component
    </button>
  );
}
```

Add it to `page.tsx`.

Run the app with: `pnpm run dev`

Reload the page and click the button component as soon as available, but before the page loaded fully load.

### With `pnpm run dev`:

An `Unhandled Runtime Error` will happen.
```
Error: Hydration failed because the initial UI does not match what was rendered on the server.
throwOnHydrationMismatch
node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (14726:0)
tryToClaimNextHydratableInstance
node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (14776:0)
updateHostComponent
node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23001:0)
beginWork
node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (24831:0)
beginWork$1
node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (32185:0)
performUnitOfWork
node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (31082:0)
workLoopSync
node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (30891:0)
renderRootSync
node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (30856:0)
performSyncWorkOnRoot
node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (30368:0)
flushSyncCallbacks
node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (14254:0)
eval
node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (29896:0)
```

while in the inspect window in chrome display the following errors:
```
The above error occurred in the <NotFoundErrorBoundary> component:

    at NotFoundErrorBoundary (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/layout-router.js:370:9)
    at NotFoundBoundary (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/layout-router.js:377:11)
    at LoadingBoundary (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/layout-router.js:289:11)
    at ErrorBoundary (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/error-boundary.js:76:11)
    at RenderFromTemplateContext (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/render-from-template-context.js:12:34)
    at OuterLayoutRouter (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/layout-router.js:20:11)
    at body
    at html
    at ReactDevOverlay (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:58:9)
    at HotReload (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:19:11)
    at Router (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/app-router.js:99:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/error-boundary.js:63:9)
    at ErrorBoundary (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/error-boundary.js:76:11)
    at AppRouter (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/components/app-router.js:20:13)
    at ServerRoot (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/app-index.js:126:11)
    at RSCComponent
    at Root (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.1.3-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/app-index.js:143:11)

React will try to recreate this component tree from scratch using the error boundary you provided, ReactDevOverlay.
  | overrideMethod | @ | react_devtools_backend.js:4012
  | logCapturedError | @ | react-dom.development.js:21544
  | callback | @ | react-dom.development.js:21605
  | callCallback | @ | react-dom.development.js:17363
  | commitCallbacks | @ | react-dom.development.js:17410
  | commitClassCallbacks | @ | react-dom.development.js:26824
  | commitLayoutEffectOnFiber | @ | react-dom.development.js:26926
  | recursivelyTraverseLayoutEffects | @ | react-dom.development.js:28377
  | commitLayoutEffectOnFiber | @ | react-dom.development.js:26908
  | recursivelyTraverseLayoutEffects | @ | react-dom.development.js:28377
  | commitLayoutEffectOnFiber | @ | react-dom.development.js:27078
  | recursivelyTraverseLayoutEffects | @ | react-dom.development.js:28377
  | commitLayoutEffectOnFiber | @ | react-dom.development.js:27078
  | recursivelyTraverseLayoutEffects | @ | react-dom.development.js:28377
  | commitLayoutEffectOnFiber | @ | react-dom.development.js:27078
  | recursivelyTraverseLayoutEffects | @ | react-dom.development.js:28377
  | commitLayoutEffectOnFiber | @ | react-dom.development.js:27078
  | recursivelyTraverseLayoutEffects | @ | react-dom.development.js:28377
  | commitLayoutEffectOnFiber | @ | react-dom.development.js:27078
  | recursivelyTraverseLayoutEffects | @ | react-dom.development.js:28377
  | commitLayoutEffectOnFiber | @ | react-dom.development.js:26908
  | recursivelyTraverseLayoutEffects | @ | react-dom.development.js:28377
  | commitLayoutEffectOnFiber | @ | react-dom.development.js:26919
  | recursivelyTraverseLayoutEffects | @ | react-dom.development.js:28377
  | commitLayoutEffectOnFiber | @ | react-dom.development.js:26908
  | recursivelyTraverseLayoutEffects | @ | react-dom.development.js:28377
  | commitLayoutEffectOnFiber | @ | react-dom.development.js:26908
  | recursivelyTraverseLayoutEffects | @ | react-dom.development.js:28377
  | commitLayoutEffectOnFiber | @ | react-dom.development.js:26908
  | recursivelyTraverseLayoutEffects | @ | react-dom.development.js:28377
  | commitLayoutEffectOnFiber | @ | react-dom.development.js:26908
  | recursivelyTraverseLayoutEffects | @ | react-dom.development.js:28377
  | commitLayoutEffectOnFiber | @ | react-dom.development.js:26908
  | recursivelyTraverseLayoutEffects | @ | react-dom.development.js:28377
  | commitLayoutEffectOnFiber | @ | react-dom.development.js:27078
  | recursivelyTraverseLayoutEffects | @ | react-dom.development.js:28377
  | commitLayoutEffectOnFiber | @ | react-dom.development.js:27078
  | recursivelyTraverseLayoutEffects | @ | react-dom.development.js:28377
  | commitLayoutEffectOnFiber | @ | react-dom.development.js:26938
  | commitLayoutEffects | @ | react-dom.development.js:28363
  | commitRootImpl | @ | react-dom.development.js:31471
  | commitRoot | @ | react-dom.development.js:31325
  | performSyncWorkOnRoot | @ | react-dom.development.js:30401
  | flushSyncCallbacks | @ | react-dom.development.js:14254
  | eval | @ | react-dom.development.js:29891
```

With `pnpm run build & pnpm run start`:

The following error happen (which I think is the same error).
```
Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at a7 (214-d6b33925b4f15160.js:9:55659)
    at s (214-d6b33925b4f15160.js:9:143663)
    at sh (214-d6b33925b4f15160.js:9:119001)
    at 214-d6b33925b4f15160.js:9:118828
    at sp (214-d6b33925b4f15160.js:9:118835)
    at sl (214-d6b33925b4f15160.js:9:117115)
    at aH (214-d6b33925b4f15160.js:9:53961)
    at 214-d6b33925b4f15160.js:9:114143
uu @ 214-d6b33925b4f15160.js:9
n.callback @ 214-d6b33925b4f15160.js:9
lj @ 214-d6b33925b4f15160.js:9
lU @ 214-d6b33925b4f15160.js:9
u4 @ 214-d6b33925b4f15160.js:9
(anonymous) @ 214-d6b33925b4f15160.js:9
sy @ 214-d6b33925b4f15160.js:9
sl @ 214-d6b33925b4f15160.js:9
aH @ 214-d6b33925b4f15160.js:9
(anonymous) @ 214-d6b33925b4f15160.js:9
214-d6b33925b4f15160.js:9

Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at a7 (214-d6b33925b4f15160.js:9:55659)
    at s (214-d6b33925b4f15160.js:9:143663)
    at sh (214-d6b33925b4f15160.js:9:119001)
    at 214-d6b33925b4f15160.js:9:118828
    at sp (214-d6b33925b4f15160.js:9:118835)
    at sl (214-d6b33925b4f15160.js:9:117115)
    at aH (214-d6b33925b4f15160.js:9:53961)
    at 214-d6b33925b4f15160.js:9:114143
```

### Expected Behavior

As soon as the client component render, I expect to be able to interact with them.

### Which browser are you using? (if relevant)

Opera Gx / Google Chrome

### How are you deploying your application? (if relevant)

next dev / next start

<sub>[NEXT-855](https://linear.app/vercel/issue/NEXT-855/[appdir]-interacting-with-client-component-before-page-fully-load)</sub>

**Comment by lelabo-m** [comment] 2023-01-20 08:24
Updated to next@13.1.3 to see if I get better errors message about the hydration error.

Both the react dev overlay and inspect console seems to be the exact same...

**Comment by awareness481** [comment] 2023-01-20 08:43
I can't repro on either dev/prod https://github.com/awareness481/next-app-repro (here's the repo in case I didnt follow the instructions correctly)

**Comment by njarraud** [comment] 2023-01-20 09:03
I have this issue in dev mode on first load. If it interact with the page by any means before it is loaded I get an error

1. In dev mode:
<img width="1041" alt="Capture d’écran 2023-01-20 à 21 56 24" src="https://user-images.githubusercontent.com/45501180/213655772-58886b19-0382-4f4c-bc34-ff03103730a8.png">

2. In production mode:
<img width="1038" alt="Capture d’écran 2023-01-20 à 22 01 06" src="https://user-images.githubusercontent.com/45501180/213656439-e5a019f0-a146-4657-ac29-14fe01b72e34.png">

If the page is very light you have to be super quick :grin:

**Comment by hamzashah0302** [comment] 2023-01-20 09:22
same with me , but i have fixed it with useEffect method , my case was i fetched the data from api, then i render component conditionally, the problem was conditional render ,

**Comment by H4kt** [comment] 2023-01-24 18:50
Same here
Using unmodified `npx create-next-app@latest --experimental-app` & `npm run dev`

![image](https://user-images.githubusercontent.com/50774419/214382095-26e0b7cd-82de-427e-9543-4b7bea9a2e24.png)

**Comment by H4kt** [comment] 2023-01-26 14:48
Also, seems the same as #44945

**Comment by nabildroid** [comment] 2023-01-28 12:13
this is awful  :'(

**Comment by the-jasoney** [comment] 2023-01-31 00:05
I get this error when wrapping everything in an `<html>` tag in `app/layout.tsx`. A workaround I found is to use `<section>` or another element instead, but this puts it in Quirks Mode, which is not ideal.

**Comment by ItayElgazar** [comment] 2023-03-06 18:26
any news on this one?

**Comment by franzwarning** [comment] 2023-03-06 20:23
Same error here, clicking anywhere on the page

**Comment by ItayElgazar** [comment] 2023-03-06 20:29
I actually dont need to click, it happens sometimes just after the page
renders

**Comment by franzwarning** [comment] 2023-03-06 21:36
After upgrading to next.js 13.2, this isn't an issue anymore for us.

**Comment by franzwarning** [comment] 2023-03-06 21:59
@ItayElgazar could it be something like:
```
// layout.tsx
<ClientContext>
  <ServerComponent2>
    <ClientComponentThatConsumesContext />
  </ServerComponent2>
</ClientContext>
```

? Just throwing out possible causes...

**Comment by ItayElgazar** [comment] 2023-03-06 22:06
@franzwarning 
I tried removing basically every provider, layout, links and some odd components just to rule out this issue, I suspect that it happens when I fetch data using server component (with async await) 🤷‍♂️🤦‍♂️

**Comment by franzwarning** [comment] 2023-03-06 22:16
@ItayElgazar can you replicate on codesandbox?

**Comment by franzwarning** [comment] 2023-03-06 23:14
@ItayElgazar I figured it out for my case -- I was importing a css file from node_module in a client component

**Comment by franzwarning** [comment] 2023-03-07 03:59
@ItayElgazar do you use headlessui by chance? I also noticed my `<body>` was getting set with `overflow:hidden` if I clicked at the right time during hydration. Hit me on telegram https://t.me/franzwarning and we can debug together, and post the result here

**Comment by luoweii** [comment] 2023-03-07 04:12
![image](https://user-images.githubusercontent.com/7483944/223318959-01f2ba35-2fd0-4cdf-9154-4cf692663d7f.png)

**Comment by luoweii** [comment] 2023-03-07 04:24
I get this error when I click somewhere on page while the page is loading

**Comment by franzwarning** [comment] 2023-03-07 17:13
Update -- when I clear my .next cache and restart my next dev server it starts working. It could be something with the cache returning old information on dynamic pages?

**Comment by AdamMikacich** [comment] 2023-03-07 20:46
Updated to 13.2.3 and still experiencing the issue. Error is thrown in NotFoundErrorBoundary when interacting with input elements (focusing them) while page is still loading.

**Comment by jabza** [comment] 2023-03-11 01:36
Also seeing this. I have interleaved server component > client context > server component > client consumer components, but my understanding is this is allowed.

**Comment by itoutcome** [comment] 2023-03-12 00:40
A fresh nextjs install and just enabling appDir causes this without doing anything else. Just press F5 over and over again (really fast).

**Comment by Kinbaum** [comment] 2023-03-13 13:28
I am running into this same issue as well. @leerob Just for kicks, I tried loading [your site](https://leerob.io/) to test this out, and sure enough, spam clicking your page just after a reload produces the hydration error.

<img width="1086" alt="Screen Shot 2023-03-13 at 9 28 06 AM" src="https://user-images.githubusercontent.com/6590356/224715627-2a9b2304-645e-43ac-8f5b-b64a6c751da9.png">

**Comment by timneutkens** [comment] 2023-03-17 17:38
Most of these we've seen so far are caused by browser extensions installed which is likely why you can reproduce it on any site @Kinbaum, can you narrow down which extension is causing it?

**Comment by Kinbaum** [comment] 2023-03-17 17:55
Hey @timneutkens 

I have disabled every extension, tried incognito, and multiple browsers (Safari, Edge, Chrome). Each has the same issue when spam clicking immediately after reloading. I've tried on my own site @leerob's, and the app dir playground https://app-dir.vercel.app/

**Comment by JayAdra** [comment] 2023-03-20 05:16
Same here. Any update on this? Seems wild this has been an issue for 2 months with no fix.

**Comment by faradaytrs** [comment] 2023-03-20 11:37
@shuding @huozhi @leerob Could you guys fix this because it's been there for quite a while and it's very big problem.

**Comment by nabildroid** [comment] 2023-03-20 11:45
a huge one honestly, because the pages become totally not functional and since this bug affects everything else, Next13 is useless because this bug

**Comment by patricijo** [comment] 2023-03-20 11:57
@faradaytrs @nabildroid  just use dynamic imports for the client components. 
```const Menu = dynamic(() => import("@/components/menu"), {
  loading: () => <p>Loading...</p>,
});```

**Comment by timneutkens** [comment] 2023-03-20 13:41
Just to be clear this is already triaged and being looked at. We're struggling to consistently reproduce the issue to investigate the root cause of the problem. Please be patient.

**Comment by timneutkens** [comment] 2023-03-25 09:49
I've managed to record a replay using https://replay.io, quite certain it's something in React. Asked @acdlite to take a look.

**Comment by timneutkens** [comment] 2023-04-01 08:35
@acdlite looked into this case and found it was accidentally fixed with some other bugfixes to React two weeks ago. I've taken @awareness481's reproduction, upgraded to `next@canary`, and verified the reproduction steps and can no longer reproduce so I'm going to close this issue as fixed 👍 

Codesandbox: https://codesandbox.io/p/github/awareness481/next-app-repro/csb-nhq2u0/draft/trusting-sound?file=%2FREADME.md

**Closed by timneutkens** 2023-04-01 08:35 UTC
Labels: template: bug, linear
