### ISSUE TITLE
 12.0.2: CSS concatenated in reversed order

### ISSUE THREAD

**Issue by hanayashiki** [vercel/next.js#30717] opened 2021-11-01 06:42 UTC
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

The css is inserted in wrong order.

### Expected Behavior

The css is inserted in the order as they are imported in _app.js

### To Reproduce

I'm using `next-with-less` to handle `.less` files.

next.config.js
```
import withLess from 'next-with-less';
import type { NextConfig } from 'next/dist/server/config-shared';

import tw from './tailwind.config';

const nextConfig: NextConfig = {
  experimental: {},
  future: {},
};

const finalConfig = withLess({
  lessLoaderOptions: {
    lessOptions: {
      modifyVars: {
        'primary-color': tw.theme.extend?.colors?.primary,
        'layout-header-background': tw.theme.extend?.colors?.primary,
      },
    },
  },
  ...nextConfig,
});

export default finalConfig;

module.exports = finalConfig;

```

_app.ts
```
import 'antd/dist/antd.less';
import '../styles/globals.css';
// ...
```

When deployed:

![image](https://user-images.githubusercontent.com/26056783/139631872-04fa1f77-3169-4a29-9cef-383b767c54c3.png)

The first css is generated probably for global css(es). It is concatenated with tailwindcss at first, antd at the second, conversed to import order. With this, I cannot override antd styles with my own.

I've checked with `yarn add next@^11.0.0` there's no such problem.

**Comment by hanayashiki** [comment] 2021-11-01 07:32
The following workaround works for me:

1. rename `global.css` to `global.less`
2. delete `import 'antd/dist/antd.less';` from `_app.ts`
3. add `@import url('../../node_modules/antd/dist/antd.less');` to `global.less` on the top.

This ensures the order of concatenation is not affected by next.js's algorithm

**Comment by Maczuga** [comment] 2021-11-05 15:10
This might be related: https://github.com/vercel/next.js/issues/30251#issuecomment-961975650

**Comment by visnup** [comment] 2022-02-12 00:19
I've run into this to and have a minimal reproduction case at https://codesandbox.io/s/agitated-dubinsky-16xg4?file=/pages/global.css.

The presence of an `@import` declaration in a global stylesheet causes `next build` to always put it at the beginning of the generated static css bundle, ignoring the import order in _app.js. This is different (and surprising!) behavior with development, which always follows the order in _app.js.

In the linked reproduction, in a new terminal run `next build` and inspect the output css in .next/static/css: the pa3 override will come first followed by tachyons (from node_modules). If you remove the `@import` in global.css or simply add a comment above it and rerun `next build`, the order switches back.

**Comment by balazsorban44** [comment] 2022-02-12 13:03
Thanks for reporting, this does sound like a duplicate of #16630, where we track CSS ordering issues. I'm closing this as a duplicate of #16630. Feel free to comment on that issue if you have anything to add! :pray:

**Closed by balazsorban44** 2022-02-12 13:03 UTC
Labels: template: bug
