### ISSUE TITLE
SSR can't resolve 'http2' import

### ISSUE THREAD

**Issue by arobert93** [vercel/next.js#26108] opened 2021-06-15 07:59 UTC
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

16.3.0

### What browser are you using?

Chrome latest

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

When using `getServerSideProps` I'm unable to import Node.js http2 internal module.

```bash
Module not found: Can't resolve 'http2'
  1 | import { Readable } from 'stream';
> 2 | import { connect, constants as http2Constants } from 'http2';
```

### Expected Behavior

Being able to import the Node.js http2 internal module.

### To Reproduce

Dynamically importing an external library inside `getServerSideProps` which should be executed only on server. 

// external.js

```js
import { Readable } from 'stream';
import { connect, constants as http2Constants } from 'http2';

export class H2Fetch {}
```

// some-component.js

```jsx
export const getServerSideProps = async () => {
    const H2Fetch = (await import('external.js')).H2Fetch;
    const h2Fetch = new H2Fetch();

    // ...

    return {
        props: {}
    };
};

```

**Comment by arobert93** [comment] 2021-06-28 07:47
Any feedback on this?

**Comment by ijjk** [comment] 2021-09-19 05:22
Hi, looking at the above snippet with the file being named `some-component.js` is this in your `pages` folder? Only pages can export `getServerSideProps` and it be handled correctly. Also are all references to server-side modules being used inside of `getServerSideProps`? If not they will not be removed from the client bundle correctly. You can test the code elimination using the util here to see it working https://next-code-elimination.vercel.app/

I'm gonna close this since it doesn't sound like a Next.js bug, feel free to respond with additional info you are still having trouble with this!

**Closed by ijjk** 2021-09-19 05:22 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
