### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by abdoufaci** [vercel/next.js#29152] opened 2021-09-16 17:20 UTC
### What version of Next.js are you using?

latest

### What version of Node.js are you using?

14.15.2

### What browser are you using?

chrome

### What operating system are you using?

windows

### How are you deploying your application?

vercel

### Describe the Bug

i don't know why is this happening

18:09:37.348
Failed to compile.
18:09:37.348
18:09:37.348
./public/logo.png
18:09:37.348
Module parse failed: Unexpected character '�' (1:0)
18:09:37.348
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
18:09:37.348
(Source code omitted for this binary file)
18:09:37.349
18:09:37.349
18:09:37.349
> Build error occurred
18:09:37.350
Error: > Build failed because of webpack errors
18:09:37.350
    at /vercel/path0/node_modules/next/dist/build/index.js:17:924
18:09:37.350
    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:6:584)
18:09:37.375
error Command failed with exit code 1.
18:09:37.375
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
18:09:37.396
Error: Command "yarn run build" exited with 1

### Expected Behavior

i expected the app to be deployed

### To Reproduce

......

**Comment by ijjk** [comment] 2021-09-18 15:20
Hi, this is most likely caused by custom configuration added breaking image imports. I'm going to close this as a reproduction was provided and doesn't sound like a bug in Next.js.

**Closed by ijjk** 2021-09-18 15:20 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
