### ISSUE TITLE
Source map error: Error: Invalid URL: (Firefox)

### ISSUE THREAD

**Issue by jasonwilliams** [vercel/next.js#9471] opened 2019-11-20 15:39 UTC
# Bug report
Navigating to our next.js page in Firefox we recieve the following error in the console:
```
Source map error: Error: Invalid URL: webpack://[name]_[chunkhash]/webpack/bootstrap
Resource URL: http://127.0.0.1:3001/_next/static/development/dll/dll_01ec57fc9b90d43b98a8.js?ts=1574263926643
Source Map URL: dll_01ec57fc9b90d43b98a8.js.map
```

When investigating the file itself i do see a lot of `webpack://[name]_[chunkhash]` here are the first few lines: (Im guessing it shouldn't be like this?)
```
{"version":3,"file":"dll_01ec57fc9b90d43b98a8.js","sources":["webpack://[name]_[chunkhash]/webpack/bootstrap","webpack://[name]_[chunkhash]/./node_modules/object-assign/index.js","webpack://[name]_[chunkhash]/./node_modules/prop-types/checkPropTypes.js","webpack://[name]_[chunkhash]/./node_modules/prop-types/lib/ReactPropTypesSecret.js","webpack://[name]_[chunkhash]/./node_modules/react-dom/cjs/react-dom.development.js","webpack://[name]_[chunkhash]/./node_modules/react-dom/index.js","webpack://[name]_[chunkhash]/./node_modules/react/cjs/react.development.js","webpack://[name]_[chunkhash]/./node_modules/react/index.js","webpack://[name]_[chunkhash]/./node_modules/scheduler/cjs/scheduler-tracing.development.js","webpack://[name]_[chunkhash]/./node_modules/scheduler/cjs/scheduler.development.js","webpack://[name]_[chunkhash]/./node_modules/scheduler/index.js","webpack://[name]_[chunkhash]/./node_modules/scheduler/tracing.js"],"sourcesContent":[" \t// The module cache\n \tvar installedModules = {};\n\n \t// The require function\n \tfunction __webpack_require__(moduleId) {\n\n \t\t// Check if module is in cache\n \t\tif(installedModules
```

## To Reproduce
* Run next watch
* Navigate to next in Firefox 
* Open dev tools

## Screenshots

![image](https://user-images.githubusercontent.com/936006/69252866-98daa300-0bab-11ea-95b6-a88fa042cfe3.png)

## System information

- OS: MacOS 10.14.6
- Browser: Firefox Developer Edition (71.0b10)
- Version of Next.js: 9.1.3

## Additional context
This only seems to be affecting Firefox, Chrome reports no issues in the console

**Comment by jasonLaster** [comment] 2019-11-20 16:44
@jasonwilliams does this happen for a publicly available project I can pull down and run test?

**Comment by jasonLaster** [comment] 2019-11-20 16:45
CC @loganfsmyth this looks like a URL. Do you remember the sourcemap library we're using.

**Comment by jasonwilliams** [comment] 2019-11-20 16:54
@jasonLaster yes it does i can reproduce this in the next examples:

**Steps**
* Checkout next.js (i checked out master - d90c85311140b8a55d611dd5cc4fd15e30f7e708)
* in the vscode directory, add a `lauch.json` file with this content https://gist.github.com/jasonwilliams/417920a7bb231e853c6e0521621c4e3d
* Navigate to examples/blog-starter
* npm install in this directory.
* `npm run next`
* In VSCode launch debugger "Firefox - Next"

**Comment by loganfsmyth** [comment] 2019-11-21 01:06
Given the `sources` values, I think this error is expected, because `webpack://[name]_[chunkhash]/webpack/bootstrap` is indeed an invalid URL. Since it is `://`, the value after it is a hostname, e.g. `mozilla.com` or whatever. URLs define a initial `[` at the beginning to indicate a URL that is an IPv6 address, e.g. `webpack://[1::1]`. Given that `name` and `chunkhash` here are clearly a bug, let's move on to that:

This seems to be either a bug in https://github.com/asfktz/autodll-webpack-plugin, which Next is using, or a bug in Webpack itself. `autodll` creates DLLs with a global library [with `"[name]_[chunkhash]"`](https://github.com/asfktz/autodll-webpack-plugin/blob/546ccc450b13e4aad7da95d694e3c0a174b9ccfd/src/createConfig.js#L46) as the name of the DLL [and the name of the library](https://github.com/asfktz/autodll-webpack-plugin/blob/546ccc450b13e4aad7da95d694e3c0a174b9ccfd/src/createConfig.js#L51).

I'm _guessing_ it's the second one that's the problem, though it's hard to tell. The [docs for `DllPlugin`'s `name` argument](https://webpack.js.org/plugins/dll-plugin/) say it accepts template replacements for `[name]` and `[hash]` (though I think `[chunkhash]` is probably also assumed to work there?). However, the [docs for `output.library` make no such mention](https://webpack.js.org/configuration/output/#outputlibrary). And since sourcemaps are generated using [`output.devtoolModuleFilenameTemplate`](https://webpack.js.org/configuration/output/#outputdevtoolmodulefilenametemplate)'s default of `webpack://[namespace]/[resource-path]?[loaders]` and those same docs say `[namespace]` is "The modules namespace. This is usually the library name when building as a library, empty otherwise", it sounds like `autodll` is expecting Webpack to place `[name]` and `[chunkhash]` in the library name whereas Webpack's docs don't suggest that it is supposed to do that.

**Comment by jasonLaster** [comment] 2019-11-21 01:36
cc @Timer I wonder if you have more context here.

**Comment by jasonwilliams** [comment] 2019-11-21 10:39
Also cc @asfktz

**Comment by jasonwilliams** [comment] 2020-01-30 17:23
It is true that `static/development/dll.dll_***.map/` is spitting out bad sourcemaps

**Comment by jasonwilliams** [comment] 2020-01-30 18:06
Up to date reproduction steps:
* VSCode (v1.41.1)
* Make sure you have the "Debugger for Firefox" (im using 2.6.1)
* Check out https://github.com/jasonwilliams/nextjs9-typescript-server-vscode-example @ 315318e21619f16f09e593b8b255e45de1a66a7b
* npm install
* npm run-script dev
 
You should see :
![image](https://user-images.githubusercontent.com/936006/73476864-06b10100-438b-11ea-99f8-19e8964e9002.png)

**Comment by jasonwilliams** [comment] 2020-01-31 00:30
https://github.com/asfktz/autodll-webpack-plugin looks to be deprecated and is recommending https://github.com/mzgoddard/hard-source-webpack-plugin until Webpack 5.0 comes out

**Comment by jasonwilliams** [comment] 2020-03-02 21:13
This issue will go away in webpack 5 which is being looked at https://github.com/zeit/next.js/issues/9426#issuecomment-593555575 module federation will be replacing the dlls

**Comment by oyeanuj** [comment] 2020-04-13 18:14
@Timer @tim Also seeing this issue on a new project we are starting with Next. Is there a workaround as this seems like a production-stopping issue?

@jasonwilliams Did you end up with a workaround?

**Comment by oyeanuj** [comment] 2020-04-14 22:31
@jasonLaster @loganfsmyth Any updates/workaround from the Mozilla's side here?

**Comment by jasonwilliams** [comment] 2020-04-14 22:39
@oyeanuj i only ever came across this issue when using the Firefox debugger, and they fixed it on their side by adding the path mapping as a default https://github.com/firefox-devtools/vscode-firefox-debug/issues/177#issuecomment-591005586 commit is here https://github.com/firefox-devtools/vscode-firefox-debug/commit/caeb6ba011775d7ac871e38df6ac9a0a0d71271c

**Comment by chrisbenincasa** [comment] 2020-04-29 15:06
I've been hitting this issue in the Firefox dev console (not while using vscode for debugging). Is there guidance on fixing the mappings there?

**Comment by Timer** [comment] 2020-07-19 05:50
This bug should be resolved on Next.js' canary channel (`next@canary`), could you please try and confirm?

**Comment by jasonwilliams** [comment] 2020-07-19 11:25
@Timer Out of interest how was this fixed? Can you link to a PR?

**Comment by Timer** [comment] 2020-07-20 13:35
We dropped `autodll-webpack-plugin` and switched to a Firefox-compatible `devtool` option. These changes were made over multiple PRs so it'd be hard to track down exact links.

**Comment by Timer** [comment] 2020-07-20 14:24
Closing as I assume you've confirmed this as fixed for you. Please let me know if you still have problems!

**Closed by Timer** 2020-07-20 14:24 UTC
Labels: kind: bug, type: needs investigation

**Comment by jcarraway** [comment] 2020-08-30 15:37
For anyone still running into this issue - upgrading to the latest version of Firefox (80.0 (64-bit) for Mac) fixed it for me

**Comment by balazsorban44** [comment] 2022-01-29 13:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
