### ISSUE TITLE
Alias `react-dom/server` based on environment

### ISSUE THREAD

**Issue by devknoll** [vercel/next.js#31035] opened 2021-11-05 15:35 UTC
For now, `react-dom/server` should be aliased to `react-dom/server.(browser|node).(production|development)` via webpack (i.e. code should import `react-dom/server` directly). This more closely matches the longer term strategy for React's bundling using [conditional exports](https://nodejs.org/api/packages.html#conditional-exports).

**Comment by shuding** [comment] 2021-11-07 00:19
Closing as resolved in #30906.

**Closed by shuding** 2021-11-07 00:19 UTC
Labels: kind: story, area: Server Components

**Comment by balazsorban44** [comment] 2022-01-27 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
