### ISSUE TITLE
[i18n] routes prefixed with defaultLocale should be inaccessible

### ISSUE THREAD

**Issue by dmitrykozyrenko** [vercel/next.js#19406] opened 2020-11-21 20:29 UTC
# Bug report

## Describe the bug

Routes prefixed with `defaultLocale` should be inaccessible. This is confusing behavior.

## System information

- OS: Windows
- Browser: Chrome
- Version of Next.js: 10.0.3-canary.0
- Version of Node.js: 12.16.1
- Deployment: dev, next start, Vercel

**Comment by timneutkens** [comment] 2020-11-22 16:53
Closing as there's no context provided in the issue.

**Closed by timneutkens** 2020-11-22 16:53 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-29 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
