### ISSUE TITLE
Please leave your feedback about the Create React App to Next.js migration tool in this thread.

### ISSUE THREAD

**Issue by laur80** [vercel/next.js#26195] opened 2021-06-16 15:18 UTC
I don't know if I need to add anything and what after using the command:

`npx @next/codemod cra-to-next                                                                                                   
 npx: installed 469 in 33.702s
 ? On which files or directory should the codemods be applied? (.) `

But after I choose to press enter, the following errors appear:

`
Error: Cannot find module 'jscodeshift/src/runner'
Require stack:
- /home/laur/.npm/_npx/61288/lib/node_modules/@next/codemod/lib/run-jscodeshift.js
- /home/laur/.npm/_npx/61288/lib/node_modules/@next/codemod/transforms/cra-to-next.js
- /home/laur/.npm/_npx/61288/lib/node_modules/@next/codemod/bin/cli.js
- /home/laur/.npm/_npx/61288/lib/node_modules/@next/codemod/bin/next-codemod.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/laur/.npm/_npx/61288/lib/node_modules/@next/codemod/lib/run-jscodeshift.js:7:34)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19`

**Comment by ykzts** [comment] 2021-06-16 15:25
I think this issue has been fixed in #26172.

**Comment by TUPPENCEMATE** [comment] 2021-06-16 15:43
Yeah looks good

**Closed** 2021-06-16 16:08 UTC

**Comment by balazsorban44** [comment] 2022-01-28 06:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
