### ISSUE TITLE
getStaticProps used along with getStaticPaths is not updating the data for dynamic routes based on params

### ISSUE THREAD

**Issue by Anam0927** [vercel/next.js#26944] opened 2021-07-06 07:48 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.17.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

I've pages with URLs like `/how-it-works/[id]` which use `getStaticProps` and `getStaticPaths`. The problem occurs when I navigate to a similar route with different `id`. The data (from `getStaticProps`) is not updated. It remains as the data from the first time this route was accessed. If I refresh the page, the data gets updated but then the error occurs again when I try to navigate using links.

I'm accessing the data based on `id` through `ctx.params` in `getStaticPaths`.

The problem only started after upgrading to NextJS 11. This was working fine before.

I'm using `next/link` for navigating.

### Expected Behavior

The data should get updated based on `id` when navigating using `next/link`.

### To Reproduce

1. Create a dynamic route page like `/how-it-works/[id]`
2. Add `getStaticPaths` and `getStaticProps` to this page with data fetching based on `id` in `getStaticProps`.
3. Add some `next/link` Links to routes with different `id`s.
4. Try navigating using those links.
5. Error occurs.

**Comment by Anam0927** [comment] 2021-07-06 08:10
**UPDATE:**

Further investigation showed that the data is being changed in `getStaticPaths` but is not being reflected in the page component props

**Comment by timneutkens** [comment] 2021-07-06 09:55
Can you create a minimal reproduction, e.g. in a github repository or https://stackblitz.com/

**Comment by ijjk** [comment] 2021-07-15 22:53
Hi, this sounds like it could potentially be a duplicate of https://github.com/vercel/next.js/issues/26270

**Comment by ijjk** [comment] 2021-09-19 04:56
Closing per above as this appears to be a duplicate

**Closed by ijjk** 2021-09-19 04:56 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
