### ISSUE TITLE
`next/og` cause memory leak in production standalone build

### ISSUE THREAD

**Issue by Innei** [vercel/next.js#65451] opened 2024-05-07 12:41 UTC
### Link to the code that reproduces this issue

https://github.com/Innei/next-og-oom-repro

### To Reproduce

1. build project
2. run as standalone build `node server.js`
3. open `/og`
4. open devtools and force refresh the page(ignore cache) more times.
5. watch the system monitor, and the next app memory usage is increasing.

The initial memory usage about to 50M, and refresh `/og` about 10 times, got 300M
![CleanShot 2024-05-07 at 8  26 37@2x](https://github.com/vercel/next.js/assets/41265413/a5596f61-dac7-465a-8885-b6b219e8d749)

![CleanShot 2024-05-07 at 8  30 54@2x](https://github.com/vercel/next.js/assets/41265413/a466bd3e-6146-49c3-bc89-95ce3053eb10)

I can provide some ways to try to troubleshoot memory issues.

Add memory dump code in `.next/standalone/server.js`

```js

process.title = 'next-og-oom'

const v8 = require('v8')
const fs = require('fs')

function createHeapSnapshot() {
  const snapshotStream = v8.getHeapSnapshot()
  const timestamp = new Date().toISOString().replace(/[:\.]/g, '-')
  const fileName = `/tmp/${timestamp}.heapsnapshot`
  const fileStream = fs.createWriteStream(fileName)
  snapshotStream.pipe(fileStream).on('finish', () => {
    console.log('Heap snapshot saved to', fileName)
  })
}

process.on('SIGUSR2', () => {
  console.log('SIGUSR2 received, creating heap snapshot...')
  createHeapSnapshot()
})

```

And then refresh the page and refresh the page several times and observe the app memory usage afterwards. When memory overflows and is not freed, hit the heap of memory at that point with `kill -SIGUSR2 <pid>`.

As you can see from the following dump, it's the ImageResponse-related modules that are leaking memory. ImageResponse and FigmaImageResponse that means @vercel/og causes memory leak?

Link to https://github.com/vercel/next.js/issues/44685#issuecomment-2098076162.

### Current vs. Expected behavior

1. Memory does not free up and increases more and more, finally oom.

expected:

Memory can be freed up.

### Provide environment information

```bash
Operating System:
  Platform: darwin/linux
  Arch: arm64/amd64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020/ or Linux
  Available memory (MB): 32768
  Available CPU cores: 12
Binaries:
  Node: 18.18.0/20.x
  npm: 10.2.4
  Yarn: 1.22.21
  pnpm: 9.1.0
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Image (next/image)

### Which stage(s) are affected? (Select all that apply)

Other (Deployed)

**Comment by Innei** [comment] 2024-05-07 12:43
Attachment: [2024-05-07T12-30-03-488Z.heapsnapshot.zip](https://github.com/vercel/next.js/files/15235615/2024-05-07T12-30-03-488Z.heapsnapshot.zip)

**Comment by chipcop106** [comment] 2024-07-01 02:17
Here is our memory chart when using the Next 14.2.3. I confirmed a memory leak issue with the open graph and Twitter images. From 27/6, we disable this function, and this chart becomes normal.
image

<img width="1046" alt="image" src="https://github.com/vercel/next.js/assets/17249557/ed39f400-f4fe-43ef-a852-84dec604f6ee">

### Solution
Please don't use dynamically generated metadata images using tsx, js, or ts until fixed.

**Comment by zhyd1997** [comment] 2024-07-01 03:11
Hi @chipcop106 

What's the metrics tracing platform?
Are you using [Sentry](https://sentry.io/) or [Datadog](https://www.datadoghq.com/)? 👀

**Comment by chipcop106** [comment] 2024-07-01 03:45
> Hi @chipcop106
> 
> What's the metrics tracing platform? Are you using [Sentry](https://sentry.io/) or [Datadog](https://www.datadoghq.com/)? 👀

I'm using AWS ECS, which is the metrics of the docker's container.

**Comment by zhyd1997** [comment] 2024-07-01 03:47
@chipcop106 

Thanks!

**Comment by matthewmorek** [comment] 2024-07-10 22:23
Possible fix already sitting on your doorstep for free since March 13: https://github.com/orgs/vercel/discussions/6117#discussioncomment-8776252

**Comment by khuezy** [comment] 2024-08-05 16:56
![image](https://github.com/user-attachments/assets/d1b841d2-8b6c-4104-aeff-878b76e424dc)

This leak is still not fixed in the latest 15-canary.102. Memory is stable around 200MB, then 1 request to generate dynamic `og` causes the memory to spike to 230MB and is never freed.
Since the thread above isn't available for discussion, can we get some vercel devs' 👀 on this, CC: @shuding

**Comment by shuding** [comment] 2024-08-05 17:02
Self assigned - will take a look!

**Comment by frankharkins** [comment] 2024-08-05 18:45
Thanks @shuding! This approach worked well for us https://github.com/orgs/vercel/discussions/6117#discussioncomment-8776252. After applying the patch, our memory stopped growing as aggressively.

![Screenshot 2024-08-05 at 19 42 46](https://github.com/user-attachments/assets/619fd6fb-7ada-4045-b3d2-474bcabc5812)

**Comment by khuezy** [comment] 2024-08-05 19:50
@frankharkins 
Might be a little off topic here, but related to memory usage and leaks. Is it normal for the memory to grow like yours after the patch? It looks like it grows but a decent amount post 08/03. Is this a general memory issue with javascript , reactjs, or nextjs?
I've noticed a gradual memory usage in my app too over a period of several days.

My other apps that run on `golang` and `rust` have a flatline memory usage over long periods of months+

**Comment by Eric-Arellano** [comment] 2024-08-05 20:21
> Is it normal for the memory to grow like yours after the patch?

(Coworker of Frank). No, I don't think it's normal. Our usage stats suggest it is not due to more usage over time, but rather we suspect a memory leak. We're still trying to figure out what causes it, with two leading hypotheses:

* Image optimization (https://github.com/vercel/next.js/issues/44685 and https://github.com/vercel/next.js/issues/54482)
* We prebuild our 200 most popular pages, but we have about 20,000 pages that get dynamically built. Local testing shows that memory usage increases when those pages are accessed, which is expected. However, we're still trying to confirm whether memory is being properly cleaned up afterwords.

**Comment by khuezy** [comment] 2024-08-05 20:28
Hey @Eric-Arellano, I've seen a few issues on the next/image optimization leakage too. But my app continues to grow in memory over time, when it does garbage collect the memory drops but is always a little higher than the previous GC, so over time is continues to grow.

I have a `rewrite` and a custom image loader that routes all `/_next/img` to a non-js server than handles the image optimization and there still seems to be a leak. So there might be multiple instances of leaks somewhere in the javascript, reactjs, or nextjs stack.

**Comment by matthewmorek** [comment] 2024-08-05 21:02
@khuezy If you dig a little deeper, there is an open issue in `resvg-wasm` package which has identified a memory leak: https://github.com/yisibl/resvg-js/issues/216#issuecomment-2188877664

We have applied the above patch to `@vercel/og` manually in our project and yet we keep experience heavy memory leak. The above solution is still better than no patch, but this package doesn't seem to be the inherent cause of the leak.

**Comment by QuentinScDS** [comment] 2024-08-06 12:34
> Sorry if it's the wrong thread but just to share the experience. I'm having the same memory increase issue. The memory keeps increasing without being cleared. I've removed all usage of next/image and I'm not using resvg-wasm but the issue still persists. I have a suspicion that it might be related to the cache being stored in the memory and not in files but have to look into more details into my docker image.

Which version of Node are you using ?

**Comment by fredi1993** [comment] 2024-08-06 12:36
Version: `node:20.12.0-alpine`

**Comment by QuentinScDS** [comment] 2024-08-06 12:41
> Version: `node:20.12.0-alpine`

Try with 18-alpine, starting from version 19, I have the same memory leak issue, but everything is fine with version 18. 🤷‍♂️

**Comment by khuezy** [comment] 2024-08-06 13:47
@QuentinScDS does the node team know about the leakage? I thought they fixed the `fetch` memory leak in 18? Did they introduce another one in 19+?

**Comment by QuentinScDS** [comment] 2024-08-06 13:54
> @QuentinScDS does the node team know about the leakage? I thought they fixed the `fetch` memory leak in 18? Did they introduce another one in 19+?

Discover this yesterday after a lot of testing... Indeed, I have seen mentions of memory leaks in version 18, but I haven’t found anything about more recent versions. I haven’t had time to create a reproducible case. I have the impression that it only concerns Docker images.

**Comment by khuezy** [comment] 2024-08-06 14:12
I don't think it's related to Docker images - I'm deploying on fly.io and they only use the Dockerfile to pull down the dependencies, then they run the stack raw on firecracker. I have a typescript temporal worker stack running on `node-22.5.1` and memory has been stable... so I think this is a reactjs or nextjs leak (probably the latter)

**Comment by jnm733** [comment] 2024-09-18 06:48
> Thanks @shuding! This approach worked well for us https://github.com/orgs/vercel/discussions/6117#discussioncomment-8776252. After applying the patch, our memory stopped growing as aggressively.
> 
> ![Screenshot 2024-08-05 at 19 42 46](https://private-user-images.githubusercontent.com/36071638/355207922-619fd6fb-7ada-4045-b3d2-474bcabc5812.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDEzNjcsIm5iZiI6MTcyNjY0MTA2NywicGF0aCI6Ii8zNjA3MTYzOC8zNTUyMDc5MjItNjE5ZmQ2ZmItN2FkYS00MDQ1LWIzZDItNDc0YmNhYmM1ODEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA2MzEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzN2YzNGI0NzM2MDJmZGUwYTBmM2MyMDFhN2ZhNmQ0NjBiZDk2YjU5ZDZhMTg4NGFkZDQ2YTU1OTJlZjhjMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-EIyp7G8YnPXgRzB0X5ZdTgWqTEiTOvhL1LRSEQkDNk)

That fix the memory leak for me too. Thanks!

**Comment by stephancill** [comment] 2024-09-18 11:32
Not sure the suggested patch completely fixes the issue. Still getting the same error, but less frequently

**Closed** 2024-09-18 13:09 UTC
Labels: bug, Image (next/image)

**Comment by huozhi** [comment] 2024-09-21 11:07
The fix is patched in v14.2.13, please upgrade to the new version 🙏

**Comment by ethos-seth** [comment] 2024-09-30 20:35
@huozhi I'm not sure if I should comment here or open a new issue. Please redirect me if needed!

We bumped up to v14.2.13, but continue to see the memory leak running nextjs in a long-lived docker container. The upgrade did slow the memory leak a bit, but it still appears to be present. This app only has a few server-side routes, all of which are using the `@vercel/og` package. 

![image](https://github.com/user-attachments/assets/3628c4a9-4480-4231-8a60-e35ac8a87cc2)

**Comment by huozhi** [comment] 2024-09-30 20:56
@ethos-seth please import from `next/og` instead of `@vercel/og`. If you're still having the issue, please file a new issue with repro where you monitored it has memory leak
