### ISSUE TITLE
 MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by amirhega** [vercel/next.js#53949] opened 2023-08-12 20:26 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
    Binaries:
      Node: 20.5.0
      npm: 8.19.4
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.14-canary.2
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

none

### To Reproduce

Not quite sure what causes this behavior, some interactions spam it but I have not been able to narrow it down. Ensures it happens with the canary. 

### Describe the Bug

Note sure why it happens it suddently started happening a few weeks ago. I have noticed the fast refresh takes like 10 seconds other weird bugs I have a feeling are caused by this
```
(node:37346) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:37346) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:37346) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:37346) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:37346) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:37346) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:37346) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:37346) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:37346) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
```

### Expected Behavior

N/A

### Which browser are you using? (if relevant)

Arc Chromium Engine Version 115.0.5790.170

### How are you deploying your application? (if relevant)

next dev

**Comment by devjiwonchoi** [comment] 2023-09-04 01:29
duplicate of https://github.com/vercel/next.js/issues/49929#issuecomment-1662198738

**Comment by javivelasco** [comment] 2023-09-21 18:21
I'm closing this one as a duplicate of https://github.com/vercel/next.js/issues/54899

**Closed by javivelasco** 2023-09-21 18:21 UTC
Labels: template: bug
