### ISSUE TITLE
[Internationalization] i18n and rewrites subfolder page is reload return 404 page when deployed on Vercel Now

### ISSUE THREAD

**Issue by MSefer** [vercel/next.js#20337] opened 2020-12-19 21:54 UTC
# Bug report

## Describe the bug

A website which is being migrated over to Next.js page by page uses the Rewrites feature, when used in combination with the new Internationalized Routing feature, and when deployed to Vercel Now. I'am going to vercel-url.com/en/info/456 page via link. I see that this page work. But when i reload this page i get 404 page. It work on locally.

On the rest of the Rewrites the 404 page is displayed when page is reload, i.e. on:

vercel-url.com/en/info/456

Given below folder structure:

```
├──_app.js
├── index.js
├── info
  ├── [...slug].js
```

And below `next.config.js`

```
module.exports = {
  i18n: {
    locales: ['tr', 'en'],
    defaultLocale: 'tr',
  },
  async rewrites() {
    return [
      {
        source: '/bilgi/:slug*', 
        destination: '/info/:slug*', 
      },
      {
        source: '/en/info/:slug*',
        destination: '/info/:slug*',
        locale: false,
      },
    ]
  },
};
```

And below `index.js`

```
import Link from "next/link";

export default function Home() {
  return (
    <div>
        <Link href="/bilgi/123" locale="tr">
          <a>bilgi/detay</a>
        </Link>

        <br/>

        <Link href="/info/456" locale="en">
          <a>en/info/detail</a>
        </Link>
    </div>
  )
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Setup a small Next.js web app with above pages structure, and above next.config.js configuration.
2. Run the Rewrites locally and you will see that it work.
3. Deploy the web app on Vercel Now
4. Go to vercel-url.com/en/info/456 page you will see normal page. And reload this page. And you will see 404 page.

## Expected behavior

When using Rewrites feature, in combination with the new Internationalized Routing, and being deployed on Vercel Now, the Rewrites should work correctly without 404 page when page does exist and use sub folders.

## System information

OS: macOS 10.15.6
Browser: Google Chrome 86.0.4240.80
Version of Next.js: 10.0.4-canary.3
Version of Node.js: 14.15.1
Deployment: Vercel Now

## Additional context

I do not encounter this problem when I do not use subfolders. Like this:

```
module.exports = {
  i18n: {
    locales: ['tr', 'en'],
    defaultLocale: 'tr',
  },
  async rewrites() {
    return [
      {
        source: '/bilgi',
        destination: '/info', 
      },
      {
        source: '/en/info',
        destination: '/info',
        locale: false,
      },
    ]
  },
};
```

**Comment by ijjk** [comment] 2020-12-20 22:19
Hi, looking at the above config it appears the rewrite is failing from the destination not containing the locale when `locale: false` is used. The locale needs to be included for the rewrites to resolve correctly as mentioned in the docs [here](https://nextjs.org/docs/api-reference/next.config.js/rewrites#rewrites-with-i18n-support)

**Comment by timneutkens** [comment] 2020-12-22 13:32
Closing as there was no reply.

**Closed** 2020-12-22 13:32 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-29 00:11
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
