### ISSUE TITLE
Impossible to deploy v12.0.1

### ISSUE THREAD

**Issue by BluetyIt** [vercel/next.js#30543] opened 2021-10-28 11:34 UTC
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

14.15.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

After changing nextjs v11 to nextjs v12 compiler triggers uncounted issues to all modules using webpack features.
Here are logs about problems can appear during `build`.

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle nextjs@0.1.0~prebuild: nextjs@0.1.0
6 info lifecycle nextjs@0.1.0~build: nextjs@0.1.0
7 verbose lifecycle nextjs@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle nextjs@0.1.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\bluety2021\bluety-clear\node_modules\.bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\Microsoft\Azure Functions Core Tools\;C:\Program Files\dotnet\;C:\Program Files\Git\usr\bin;C:\Program Files\MongoDB\Server\5.0\bin;C:\Users\kenl7\AppData\Local\Microsoft\WindowsApps;C:\Users\kenl7\AppData\Roaming\Dashlane\6.1926.1.21432\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\kenl7\AppData\Roaming\Dashlane\6.1926.1.21432\ucrt;C:\Users\kenl7\AppData\Roaming\Dashlane\6.1926.1.21432\bin\Qt;C:\Users\kenl7\AppData\Roaming\Dashlane\6.1926.1.21432\ucrt;C:\Users\kenl7\AppData\Roaming\Dashlane\6.1926.1.21432\bin\Ssl;C:\Users\kenl7\AppData\Local\atom\bin;C:\Users\kenl7\AppData\Local\Microsoft\WindowsApps;C:\Users\kenl7\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\kenl7\AppData\Roaming\npm;C:\Users\kenl7\.dotnet\tools;C:\Program Files (x86)\BrowserStackLocal\;C:\Program Files\MongoDB\Server\5.0\bin;
9 verbose lifecycle nextjs@0.1.0~build: CWD: D:\bluety2021\bluety-clear
10 silly lifecycle nextjs@0.1.0~build: Args: [ '/d /s /c', 'next build' ]
11 silly lifecycle nextjs@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle nextjs@0.1.0~build: Failed to exec build script
13 verbose stack Error: nextjs@0.1.0 build: `next build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid nextjs@0.1.0
15 verbose cwd D:\bluety2021\bluety-clear
16 verbose Windows_NT 10.0.19043
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v14.15.1
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error nextjs@0.1.0 build: `next build`
22 error Exit status 1
23 error Failed at the nextjs@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
What I tried:
1. Reinitialize project (with deleting .next folder)
2. Delete `node_modules` and reinit it.
3. Change `next.config.js` to add modules.exports (webpack)

P.S. when you run the project locally no issues are detected

### Expected Behavior

I expect normal behavior

### To Reproduce

Update nextjs project v11 with modules to nextjs project v12

**Comment by bryanrsmith** [comment] 2021-10-29 19:07
Perhaps I'm misreading things, but I notice your log output references `nextjs` (https://www.npmjs.com/package/nextjs), which looks like some sort of async helper library. The proper package name of this project is `next` (https://www.npmjs.com/package/next). Did you, by any chance, use the wrong package name when trying to update?

**Comment by SushritPasupuleti** [comment] 2021-10-29 19:27
> Perhaps I'm misreading things, but I notice your log output references `nextjs` (https://www.npmjs.com/package/nextjs), which looks like some sort of async helper library. The proper package name of this project is `next` (https://www.npmjs.com/package/next). Did you, by any chance, use the wrong package name when trying to update?

A colleague did the same, and this was the exact same output, so yes it is clearly a case of confusion. Fixing the package.json and reinstalling should be enough.

**Comment by ijjk** [comment] 2021-10-29 20:40
Closing per above as this appears to be the incorrect package.

**Closed by ijjk** 2021-10-29 20:40 UTC
Labels: template: bug

**Comment by BluetyIt** [comment] 2021-11-01 12:10
My project called nextjs, so I changed the name but noting happened

**Comment by balazsorban44** [comment] 2022-01-27 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
