### ISSUE TITLE
generateStaticParams runs in dev mode

### ISSUE THREAD

**Issue by capJavert** [vercel/next.js#44904] opened 2023-01-15 17:46 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 1.22.18
      pnpm: 7.22.0
    Relevant packages:
      next: 13.1.3-canary.0
      eslint-config-next: 13.1.2
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/vercel/app-playground

### To Reproduce

Add `generateStaticParams` to ISR dynamic page and it will be run in dev mode. In the example above go to `/app/isr/[id]/page.tsx` and you will see that it is run in dev mode.

### Describe the Bug

From my understanding `generateStaticParams` should be run only at build time, to quote [the docs](https://beta.nextjs.org/docs/api-reference/generate-static-params#generatestaticparams):
> The generateStaticParams function runs at build time before the corresponding Layouts or Pages are generated. It will not be called again during revalidation (ISR).

Fetching data for pre-rendering in dev mode is kinda an overhead and waste of resources. For now I am using a workaround:
```js
if (process.env.NODE_ENV === 'development') {
    return []
}
```

### Expected Behavior

`generateStaticParams` runs only at build time.

Alternatively update the docs to reflect that this also runs in dev mode. I would imagine this is useful if you wish to test out the method. But in my opinion `next build` should be used to test it because it will have correct env and variables.

**Comment by SamuelScheit** [comment] 2023-02-24 14:21
any updates on this?

**Comment by timneutkens** [comment] 2023-02-27 09:14
The docs are incorrect, it is supposed to run in development so this is not a bug. We'll update the documentation.

**Comment by delbaoliveira** [comment] 2023-03-05 17:17
Hey! Updated the docs to clarify this. Going to close this since it's not a bug. 

Please leave feedback on the docs page if we can further improve the wording :pray:

**Closed by delbaoliveira** 2023-03-05 17:17 UTC
Labels: area: documentation
