### ISSUE TITLE
CSS autoprefixer not working in version 10.0.6+

### ISSUE THREAD

**Issue by geekonthemove** [vercel/next.js#23551] opened 2021-03-30 13:16 UTC
### What version of Next.js are you using?

10.0.6

### What version of Node.js are you using?

12.19.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows and OSX

### How are you deploying your application?

Vercel

### Describe the Bug

We had an issue with autoprefixer not working. However, downgrading to version 10.0.5 seems to fix the issue. All the versions tested, 10.0.6 and above, seem to have this issue.

### Expected Behavior

That styles would be vendor prefixed.

### To Reproduce

Setup a project with NextJS version 10.0.6 or above, or simply changing the version in an existing project, run `yarn` and then `yarn dev`, and notice that your styles are no longer being prefixed.

**Comment by Flydiverny** [comment] 2021-04-12 14:27
Yepp something for sure changed..
Doing a static export with the below listed versions gives very different CSS output

| next.js 10.0.9 | nextjs 10.0.5 |
| -------------- | -------------- |
| ![image](https://user-images.githubusercontent.com/326929/114410354-98c9b180-9bab-11eb-9a29-4271051cb4df.png) | ![image](https://user-images.githubusercontent.com/326929/114410468-aed77200-9bab-11eb-883e-053e1e1f9c6f.png) |
| 58 -webkit- prefixes |  853 -webkit- prefixes |

**Comment by Flydiverny** [comment] 2021-04-12 16:06
Did some more digging.
Everything is working fine up to and including `10.0.6-canary.7`.
When upgrading to `10.0.6-canary.8` I go from 853 prefixes to 611.
When I keep upgrading one version at a time I'm not sure how I could have ended up on 58 tho. Only way for me to achieve that is to reset my yarn.lock and package.json to master state. So even if I upgraded to 10.0.9 again after downgrading I see 611 -webkit- prefixes.
Removing next 10.0.9, and reinstalling it seems to resolve the issues and allow me to see 611 prefixes. What those missing 200 prefixes are I have no clue, if its just a bump of browserlists or something?

```
yarn remove next
rm -rf node_modules/ out/ .next/
yarn add next@10.0.9
```

**Comment by ijjk** [comment] 2021-04-28 02:01
It looks like this was indeed due to a browserslist update between these versions which is expected so doesn't appear to be a bug as css prefixes are being generated correctly in the latest version of Next.js `v10.1.3`

I'm going to close this since it appears to be working correctly, if you are noticing any unexpected behavior with this in the latest version, please respond with additional info and we can investigate further!

**Closed by ijjk** 2021-04-28 02:01 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
