### ISSUE TITLE
FOUC using new Next.js 10 and React 17

### ISSUE THREAD

**Issue by nicholaschiang** [vercel/next.js#18769] opened 2020-11-04 00:06 UTC
# Bug report

## Describe the bug

Before Next.js 10, my [portfolio website](https://nicholaschiang.com) had no flashes of unstyled content on both the development server and after being deployed to Vercel. After upgrading to Next.js 10 and React 17, however, I seem to have lots:

![FOUC](https://user-images.githubusercontent.com/20798889/98053854-6d69bc00-1dee-11eb-9a81-77596c32b869.gif)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://nicholaschiang.com
2. See FOUC

Or, if you want to reproduce locally:

1. Clone [this repository](https://github.com/nicholaschiang/website)
2. Follow [these instructions](https://github.com/nicholaschiang/website#development-environment) to install deps, etc
3. Run `yarn dev` or `yarn build && yarn start`
4. Open up http://localhost:3000
5. See FOUC

## Expected behavior

There should be no FOUC when using React 17 and Next.js 10.

## System information

- OS: PopOS 20.10
- Browser (if applies) Firefox
- Version of Next.js: 10.0.0
- Version of Node.js: 12.18.3

**Comment by felixmosh** [comment] 2020-11-04 09:15
Probably related to #17086

**Comment by nicholaschiang** [comment] 2020-11-04 20:56
@felixmosh I think these are two different issues because styling works fine with client-side navigation, but is messed up when users first visit the page. I'm going to revert back to Next.js 9 to get rid of that FOUC.

**Comment by drazik** [comment] 2020-11-16 09:56
Same problem here. I absolutely can't find why I have a FOUC, but here is what I can see: dev builds are OK, but prod builds produce a FOUC on first visit (or refresh with cache cleaned). I used [this "fix"](https://github.com/vercel/next.js/issues/15642#issuecomment-710747889) but it doesn't seem like a long-term fix.

But even if I use next@9 I have the issue.

**Comment by serhii-baraniuk** [comment] 2020-11-16 10:17
I use styled-jsx on my project and have the same problem. Dev builds works well, but if I disable JavaScript I see that the styles are not loaded.

**Comment by nicholaschiang** [comment] 2020-11-16 22:14
@serhii-baraniuk I can confirm that this is a [`styled-jsx`](https://github.com/vercel/styled-jsx/) issue because I recently ported over some of [that website code](https://github.com/nicholaschiang/website) into [my TB project](https://github.com/tutorbookapp/tutorbook) and experienced the same issue. So, I switched over to using SCSS modules and it worked fine.

**Comment by 4lejandrito** [comment] 2020-11-19 21:33
I can reproduce this with the initial installation of Next:

1. Run `npx create-next-app next-fouc`
2. cd next-fouc && yarn build && yarn start
3. Open Firefox (with or without the devtools open).
4. Press CMD + Shift + Refresh repeatedly and eventually (normally the first time) you'll see the fouc.

If performed with the devtools open the console will contain:
```
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. node.js:361
```

**Comment by dpatel4-lat** [comment] 2020-12-03 03:32
Was this not fixed with https://github.com/vercel/next.js/pull/19125 ?

**Comment by 4lejandrito** [comment] 2020-12-03 07:58
I can still reproduce it following the steps from https://github.com/vercel/next.js/issues/18769#issuecomment-730649982.

**Comment by TylerJNewman** [comment] 2020-12-07 18:07
> this "fix"

I used this fix as well thank you...
Not sure why adding a <script>0</script> tag right after the opening <body> works...

**Comment by TylerJNewman** [comment] 2020-12-07 18:08
> Same problem here. I absolutely can't find why I have a FOUC, but here is what I can see: dev builds are OK, but prod builds produce a FOUC on first visit (or refresh with cache cleaned). I used [this "fix"](https://github.com/vercel/next.js/issues/15642#issuecomment-710747889) but it doesn't seem like a long-term fix.
> 
> But even if I use next@9 I have the issue.

I used this fix as well thank you...
Not sure why adding a <script>0</script> tag right after the opening works...

**Comment by rgbskills** [comment] 2021-01-10 12:22
Hey I'm having the same issue, I'm using next `10.0.5` and react `17.0.1` with CSS modules.

https://user-images.githubusercontent.com/5773622/104122695-34e6e100-534f-11eb-9af7-7f99dab6d331.mp4

**Comment by meandillar** [comment] 2021-01-12 03:14
I am using css modules and experiencing the same issue.  I have managed to fix it by adding `prefetch={false}` to all Link tags. It seems that these prefetch downloads are somehow blocking some css from loading immediately, even though the tags are positioned after the stylesheets in the head.

**Comment by nicholaschiang** [comment] 2021-01-20 06:59
I'm using SCSS modules for [`tutorbookapp/tutorbook`](https://github.com/tutorbookapp/tutorbook) and I'm still getting a FOUC (just [open this website](https://tutorbook.app) to see it).

**Comment by AlexSapoznikov** [comment] 2021-01-29 14:17
After digging around, found **[this](https://github.com/styled-components/styled-components/issues/2962#issuecomment-585665413)** which solved my issue with material-ui + styled-components:

**Comment by ITSWYoo** [comment] 2021-02-01 06:24
Using a custom server seems to solve the problem. 😢

**Comment by Timer** [comment] 2021-02-12 17:21
This would've been fixed by https://github.com/vercel/next.js/pull/19006. Confirmed there's no layout shift on your website in Chrome/Firefox/Safari when on latest Next.js version.

Let me know if you can still reproduce!

**Closed by Timer** 2021-02-12 17:21 UTC
Labels: kind: bug, point: 3, type: needs investigation

**Comment by nicholaschiang** [comment] 2021-02-16 02:08
@Timer I've just upgraded to Next.js 10.0.7 for [my portfolio website](https://nicholaschiang.com) and it's still showing a FOUC. 

Here's the open source repository: [`nicholaschiang/website`](https://github.com/nicholaschiang/website). You should be able to:
1. Clone (using `git clone https://github.com/nicholaschiang/website`)
2. Install (using `yarn install`)
3. Start a Next.js development server (using `yarn dev`) to reproduce

**Comment by nikoladev** [comment] 2021-02-16 10:18
> @Timer I've just upgraded to Next.js 10.0.7 for my portfolio website and it's still showing a FOUC.

Interestingly, if JS is disabled the styles aren't loaded at all. My NoScript extension blocked JS on your site by default and the site stays unstyled until I enable JS and reload the page.

**Comment by serhii-baraniuk** [comment] 2021-02-16 11:04
> @Timer I've just upgraded to Next.js 10.0.7 for [my portfolio website](https://nicholaschiang.com) and it's still showing a FOUC.
> 
> Here's the open source repository: [`nicholaschiang/website`](https://github.com/nicholaschiang/website). You should be able to:
> 
> 1. Clone (using `git clone https://github.com/nicholaschiang/website`)
> 2. Install (using `yarn install`)
> 3. Start a Next.js development server (using `yarn dev`) to reproduce

`npm i next@carary` fixed the problem for me

**Comment by nagman** [comment] 2021-03-05 11:32
`npm i next@canary` changed nothing for me.
Still having this FOUC (while it's a partial FOUC: only a part of the CSS is applied later).

I can see this bug only on production mode (`yarn dev` doesn't show this issue, but `yarn build && yarn start` does).

Without `<script>0</script>` hack:

https://user-images.githubusercontent.com/16116486/110110244-d1a58800-7dae-11eb-9d13-9328ca225067.mov


With `<script>0</script>` hack:

https://user-images.githubusercontent.com/16116486/110110228-ceaa9780-7dae-11eb-9a48-bae1154da531.mov

**Comment by nicholaschiang** [comment] 2021-03-08 18:48
@nagman see #22465 (because I can't seem to be able to re-open this issue).

**Comment by gregorybolkenstijn** [comment] 2021-03-11 08:03
I'm still seeing this is as well in production mode in 10.0.9-canary.2, but the same as @nagman: only a partial part of the CSS is applied later. Everything page related seems to work well, any global CSS comes in later.

**Comment by 4lejandrito** [comment] 2021-03-11 09:25
>     1. npx create-next-app next-fouc && cd next-fouc && yarn build && yarn start

I followed the same steps but installing `^10.0.9-canary.5` and the issue is still present. I believe this is the simplest way to reproduce it.

**Comment by nagman** [comment] 2021-03-11 09:38
I wonder if it's not related to the process of adding/removal of stylesheets.

I explain myself:
When I add pages transitions with something like `react-transition-group` (I've tried `framer-motion` but I find it heavy and not SEO optimized), I can see the same FOUC during the transition.

But it only happens between pages that don't share the same stylesheet.
And If I inspect the DOM, I can see that the previous page's stylesheet is removed before the page's component is unmounted (because I delay its unmount through a `<Transition>` component).
So when I go from page A to page B, the page A loses its style during a short time and then the page B comes in.

**Comment by mohamedGamalAbuGalala** [comment] 2021-03-14 21:12
This solution solved my problem https://stackoverflow.com/a/55657362/5055925

**Comment by hagilemha** [comment] 2021-03-18 22:16
`import Document, { Html, Head, Main, NextScript } from 'next/document'

exports.PERMANENT_REDIRECT_STATUS = 301;

class MyDocument extends Document {

  render() {
    return (
      <Html>
        <Head />
        <body>
          <script>0</script>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument`

A custom _document.js fixed this issue for me

**Comment by hagilemha** [comment] 2021-03-18 22:18
Adding exports.PERMANENT_REDIRECT_STATUS = 301; 
and `<script>0</script>` to _document.js fixed it for me

**Comment by osequi** [comment] 2021-03-30 15:42
The bug is present both in production and dev environments.

**Comment by michaeldever** [comment] 2021-03-31 12:16
We’re seeing it in production. Have hacked around it by disabling visibility until the app is fully mounted.

**Comment by phumaster** [comment] 2021-04-07 03:10
I'm using a trick:
`_document.js` I'm adding a id.

```js
// ....
render() {
    return (
      <Html lang="ja" id="no-fouc"> // <- this id
        <Head />
       // and styles
        <style
          dangerouslySetInnerHTML={{
            __html: `
            #no-fouc {
              opacity: 0;
              pointer-events: none;
            }
            `,
          }}
        />
// ...
```
In `_app.js`

```js
removeNoFouc = () => {
    const noFouc = document.getElementById('no-fouc');
    if (noFouc) {
      noFouc.removeAttribute('id');
    }
  };

componentDidMount() {
    this.removeNoFouc();
  }
```
It worked for me 👯

**Comment by trompx** [comment] 2021-04-10 08:39
Could this be reopened @Timer? It seems everyone is applying its own hack to get rid of this FOUC.
Or is there a link to the doc explaining what needs to be set exactly in _document.js or any other things required to get rid of the problem?
Thanks in advance

**Comment by 1jmj** [comment] 2021-05-05 09:46
I'm having same issue using mix of CSS Modules and Material-UI with WOFF fonts. Layout seems ok but fonts apply a second after page load. Only happens on refresh. Router-based navigation seems ok.  With js disabled, no styles show.

**Comment by alittlebitweird** [comment] 2021-05-13 00:43
Also having this issue with CSS Modules, only on production builds.

**Comment by srameshr** [comment] 2021-05-14 16:47
> @serhii-baraniuk I can confirm that this is a [`styled-jsx`](https://github.com/vercel/styled-jsx/) issue because I recently ported over some of [that website code](https://github.com/nicholaschiang/website) into [my TB project](https://github.com/tutorbookapp/tutorbook) and experienced the same issue. So, I switched over to using SCSS modules and it worked fine.

@serhii-baraniuk Your site loads blazing fast for me. Why does Google lighthouse still give it a poor score for performance in the low 20's?

**Comment by joeltg** [comment] 2021-05-14 17:45
fwiw I spent a day debugging a production-only FOUC with next 10 and react 17 only to eventually find out it had nothing to do with next or react - I was using my UI library (evergreen-ui) wrong and there was evergreen-specific ssr stuff I needed to add to _document.js that I had missed. There totally still might be a bug here but in my case it was something else.

**Comment by sorokinvj** [comment] 2021-05-25 10:38
Just confirming FOUC existence with next@10.2.2, styled-components@5.2.1, _document from examples, getStaticProps. 

Currently using a hack with hiding a body by default and unhiding it in _app with 100 ms timeout. I know that it is not the best solution, but I couldn't come up with anything else yet.

**Comment by ricardo-rp** [comment] 2021-09-30 21:18
Seems like this is quite the common issue. I get a FOUC in production when using styled-components and material-ui v4. I haven't had much finding a working template for `_app.tsx` and `_document.tsx`.
Is anyone using `Mui` together with `styled-components` successfully in production? We might have to disable SSR if this doesn't work out.

**Comment by glombadev** [comment] 2021-10-09 23:41
> Seems like this is quite the common issue. I get a FOUC in production when using styled-components and material-ui v4. I haven't had much finding a working template for `_app.tsx` and `_document.tsx`. Is anyone using `Mui` together with `styled-components` successfully in production? We might have to disable SSR if this doesn't work out.

@ricardo-rp I got the same issue using material-ui v4 and latest next version. Tried upgrading to mui v5 (with emotion engine instead of styled-components tho) and still the same FOUC, so I am guessing it's a next issue

**Comment by glombadev** [comment] 2021-10-12 00:56
For future references: I solved the FOUC by finishing the v4 to v5 migration, including the complete removal of jss usages (withStyles, makeStyles, and the rest of the references to the @mui/styles package)

**Comment by osequi** [comment] 2021-11-25 15:27
> Had this issue with MUI V4, upgraded to V5 with emotion and it still persists.
> 
> You can hide it with this in your _app.js
> 
> ` const [mounted, setMounted] = useState(false) useEffect(() => setMounted(true), [])`
> 
> then wrap your app with:
> 
> `<div style={{ visibility: !mounted ? 'hidden' : '' }}><Component {...pageProps} /></div>`
> 
> This prevents the flash, but doesn't prevent search engines from accessing meta tags deeper in your tree for SEO.
> 
> This is just a hack, any better solutions will be much appreciated.

This works like charm for me. Thanks a lot!

**Comment by ghana7989** [comment] 2021-12-12 08:30
I am using pure css modules but still none of the above solutions are working
` "next": "12.0.7",
    "react": "17.0.2",
    "react-dom": "17.0.2",`
these are my package versions

**Comment by bengrunfeld** [comment] 2021-12-14 15:36
I am still experiencing this issue in Dec 2021.
