### ISSUE TITLE
trailingSlash: true don't work together with SSG and 404 page

### ISSUE THREAD

**Issue by omariosouto** [vercel/next.js#16218] opened 2020-08-15 20:42 UTC
# Bug report

## Describe the bug

I want to enable redirects with `trailingSlash: true` in a project that uses **SSG** but seems that after enable this configurations together my project is not allowed to display 404 page.

- https://devsoutinhoblog.omariosouto.vercel.app/
- https://devsoutinhoblog.omariosouto.vercel.app/any-page-that-dont-exist

## To Reproduce

Check this project here https://github.com/omariosouto/devsoutinhoblog/tree/test, I only changed the pages directory and next.config.js

## Expected behavior

I believe that 404 page must work as the result of the redirect of a page that don't exists even if the `trailingSlash: true` is enabled

## Screenshots

![image](https://user-images.githubusercontent.com/13791385/90321263-81ec9580-df1e-11ea-8fad-17e3036de3c7.png)

## System information

- Version of Next.js: latest

**Comment by ijjk** [comment] 2020-08-17 01:41
Hi, we have identified the cause for this and PR with a fix has been opened [here](https://github.com/vercel/vercel/pull/5048), I will update here once the fix is published and your application can be redeployed. 

Note: `next export` in your `package.json`'s `build` script isn't required for your pages to be deployed statically on Vercel and each page is automatically deployed as optimally as we can.

**Closed** 2020-08-17 14:12 UTC
Labels: kind: bug, point: 2

**Comment by ijjk** [comment] 2020-08-17 14:55
The above mentioned fix has been published and you should be able to redeploy your application without change, thanks for the detailed report!

**Comment by balazsorban44** [comment] 2022-01-29 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
