### ISSUE TITLE
Cannot find module rox-node

### ISSUE THREAD

**Issue by cyrus-za** [vercel/next.js#13736] opened 2020-06-03 21:43 UTC
# Bug report

## Describe the bug

When using [rox-ssr-multi-entrypoints](https://github.com/g-guirado/rox-ssr-multi-entrypoints) with nextjs, it appears that webpack is not bundling a indirect dependency, [rox-node](https://www.npmjs.com/package/rox-node)

## To Reproduce

I created a repo [here](https://github.com/cyrus-za/next-rox-node-issue) using the following steps:

1. `npx create-next-app rox-node-issue`
1. `yarn add rox-ssr-milti-entrypoints`
1. open `pages/index.js` and add the following code snippet to the bottom
```js
Home.getInitialProps = () => ({foo: 'bar'})

import { Rox } from 'rox-ssr-multi-entrypoints'

Rox.register('', {})
Rox.setup('12345')
```
1. Install vercel: `yarn add -D now`
1. deploy with `now` or `yarn now` (if node_modules not in default path) and follow steps. (Could probably reproduce it locally with `yarn build`
1. browse the deployed app on vercel and check the logs (see latest [here](https://rox-node-issue.now.sh/))

## Expected behavior
The module `rox-node` is a dependency of rox-ssr so it should be part of the bundle, but on the server during SSR it appears not to be available.

## Screenshots
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/1845861/83691634-cd1b2b80-a5f2-11ea-850e-c1a3cc140ccc.png">
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/1845861/83691680-dc9a7480-a5f2-11ea-9025-21cca39eaddf.png">

## System information

- hosted on vercel
- Version of Next.js: 9.4.4
- Version of Node.js: 12.5.0

## Additional context

The issue is also logged [here](https://github.com/g-guirado/rox-ssr-multi-entrypoints/issues/35) at `rox-ssr-multi-entrypoints` repo.

The issue `ONLY` happens when `getInitialProps` is used (even on pages that do not strictly make use of rox/rollout).

**Comment by styfle** [comment] 2020-06-04 14:01
Hi @cyrus-za 

I get the following error message:

```
Error: Cannot find module 'rox-node'
Require stack:
- /Users/styfle/Code/example/dist/node_modules/rox-ssr/dist/es6/utils.js
- /Users/styfle/Code/example/dist/node_modules/rox-ssr/dist/es6/index.js
- /Users/styfle/Code/example/dist/node_modules/rox-ssr-multi-entrypoints/dist/es6/index.js
- /Users/styfle/Code/example/dist/index.js
```

The contents of `rox-ssr/dist/es6/utils.js` is the following:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let Rox;
if (typeof window !== 'undefined') {
    Rox = require('rox-browser'); // eslint-disable-line global-require
}
else {
    // Hoping that tree shaking will remove this branch is too optimistic.
    // By using eval, 'hide' the require from webpack, such that rox-node is not
    // bundled into the browser code.
    Rox = eval('require(\'rox-node\')'); // eslint-disable-line
    Rox.setContext({ server: true });
}
function isBrowser() {
    return typeof window !== 'undefined';
}
exports.isBrowser = isBrowser;
exports.internalRox = Rox;
//# sourceMappingURL=utils.js.map%
```

It looks like the author of rox has made a special case to prevent webpack from bundling this file so this is why the there is an error at runtime.

Probably the best solution here is to change rox to use the `browser` field instead (however it doesnt seem like this package is open source). https://github.com/rollout/roxjs

**Comment by cyrus-za** [comment] 2020-06-04 20:54
Thanks @styfle I responded to the package author. The package is open source [here](https://github.com/g-guirado/rox-ssr-multi-entrypoints) but you are correct that the dependencies do not seem to have a public git repository, only a npm package.

**Comment by cyrus-za** [comment] 2020-06-06 13:43
This is still an issue. It works fine running `next build` or `now dev` but breaks when deploying to vercel.

**Comment by cyrus-za** [comment] 2020-06-06 19:27
Found [this](https://spectrum.chat/zeit/now/runtime-importmoduleerror-on-deploys~97661f05-a985-48e8-8d96-3423107e2739) on the old zeit spectrum chat. 

I tried removing the `engines` field on my production app, and that didnt work. the repo above to reproduce it doesn't have it anyways. I also tried setting it to node 10.x but same issue. (been using 12.x)

This also seems related: https://github.com/vercel/next.js/issues/7889

Not sure what else to do next

**Comment by styfle** [comment] 2020-06-08 16:03
If the author can't the `eval()` to `require()` then we'll have to add a special case.

See https://github.com/vercel/node-file-trace/issues/118

**Comment by cyrus-za** [comment] 2020-06-09 09:27
I ended up droppoing the `rox-ssr` package and wrote my own logic for when to use `rox-node` and `rox-browser` but I'd suggest to still add the special case. There are many packages that use `eval()` and do some crazy AST stuff. `babel` supports it, so it's normal to expect frameworks like `next` to also support it.

**Comment by timneutkens** [comment] 2020-06-09 09:34
> babel supports it

What does Babel support? Babel parses code, turn it into an AST and then runs plugins to transform the AST. Babel is not a bundler and as such does not support bundling.

> There are many packages that use eval()

This in particular is a package that uses `eval("require('something')")` as @styfle explained. This generally means that the original author tried to hack around bundlers and intended for the library to not work in many use-cases including bundling server-side code. It should definitely be fixed by them as they did not use the `browser` field to solve this issue. Which gives significantly better results including correct tree shaking which it currently does not do.

**Closed** 2021-04-12 11:51 UTC

**Comment by balazsorban44** [comment] 2022-01-28 13:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
