### ISSUE TITLE
Empty tsconfig.json after installing the required typescript dependencies.

### ISSUE THREAD

**Issue by MrBirb** [vercel/next.js#24343] opened 2021-04-22 08:07 UTC
### What version of Next.js are you using?

v10.1.3

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

My tsconfig.json doesnt get configured automatically after installing the required typescript dependencies. Also, docs says nextjs should instruct me to install typescript, @types/react, and @types/node after running npm run dev. However, it only mentions typescript and @types/react. So is @types/node required?

### Expected Behavior

tsconfig.json gets configured automatically after installing the required dependencies.

### To Reproduce

Run `touch tsconfig.json`
Run `npm run dev` and install the dependencies.

**Comment by ijjk** [comment] 2021-04-28 00:50
Hi, I'm not able to reproduce the `tsconfig.json` not being generated correctly following the above steps. 

The reason `@types/node` is not being listed as needed to be installed is because Next.js is detecting it is already installed in your project. You can see that it is installed with `yarn why @types/node` or `npm ls @types/node`

I'm going to close this since the `tsconfig.json` appears to be working correctly in the latest version of Next.js

**Closed by ijjk** 2021-04-28 00:50 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
