### ISSUE TITLE
Config option to Allow importing CSS from any file

### ISSUE THREAD

**Issue by Pytal** [vercel/next.js#10665] opened 2020-02-24 18:11 UTC
# Feature request

## Is your feature request related to a problem? Please describe.
I'm using [Linaria](https://github.com/callstack/linaria) with Next.js which generates unique hashes for each className so it is safe to import the generated CSS globally.

Currently importing global CSS is only allowed in `_app.js`.

## Describe the solution you'd like
It would be great if we had the option to allow css files to be imported from any file with a configuration option in `next.config.js`:
``` js
module.exports = {
  css: {
    importAsGlobal: true
  }
}
````

**Comment by stegano** [comment] 2020-02-29 20:12
The built-in CSS feature was added in next.js version 9.2. This feature allows you to handle files using file naming conventions.
- https://nextjs.org/blog/next-9-2#built-in-css-support-for-global-stylesheets

**Comment by Pytal** [comment] 2020-02-29 20:27
Yeah it's pretty great although as linaria inserts css import statements into each file that imports linaria, and the built-in css support does not allow importing global css files into any file (only `_app.js`), linaria currently does not work with built-in css support.

**Comment by mikestopcontinues** [comment] 2020-04-25 16:27
I found this thread trying to make Linaria work again as well.

**Comment by gragland** [comment] 2020-04-25 17:22
If you use the `next-css` or `next-sass` plugins then it will automatically disable the new CSS handling and allow global imports.

**Comment by Timer** [comment] 2020-09-10 19:23
Closing as duplicate of #12079

**Closed by Timer** 2020-09-10 19:23 UTC

**Comment by balazsorban44** [comment] 2022-01-29 13:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
