### ISSUE TITLE
Infer types of props returned by getStaticProps

### ISSUE THREAD

**Issue by manuschillerdev** [vercel/next.js#11824] opened 2020-04-11 12:38 UTC
# Feature request

Right now I have to redeclare the types for page props injected by `getStaticProps`, although typescript already infers them correctly. We could create a `type` that infers them from the locally exported `typeof getStaticProps`.

## Describe alternatives you've considered

I am by no means a TS expert, so I am not sure if there are better alternatives for inferring the types.

First working draft: 
```typescript
export type StaticPropsReturnValue<P> = {
    props: P;
    revalidate?: number | boolean;
  };

export type ResolvedGetStaticProps<T extends (...args: any) => any> =
    T extends (...args: any) => Promise<StaticPropsReturnValue<infer U>>
        ? StaticPropsReturnValue<U> : never;
        
export type StaticProps<T extends GetStaticProps> = ResolvedGetStaticProps<T>["props"];
```

used like this:
```tsx
export const getStaticProps = async () => ({
    props: {
        propNumberOne: "hello world",
        propNumberTwo: 2,
    },
});


const TypesTest = ({ propNumberOne }: StaticProps<typeof getStaticProps>) => (<div>{propNumberOne}</div>);
```

we get correct type inference for our props.

### Next steps:
- I would love to get feedback from TS experts if there is a better solution to do this
- if you like the feature I will gladly create a PR for this.

**Comment by manuschillerdev** [comment] 2020-04-11 17:16
I narrowed it down to a stricter conditional type.
stillt feels a bit off..

```typescript
export type StaticPropsReturn<P> = {
    props: P;
    revalidate?: number | boolean;
};

export type StaticProps<T> = T extends (ctx?: {
    params?: ParsedUrlQuery;
    preview?: boolean;
    previewData?: any;
}) => Promise<StaticPropsReturn<infer P>>
    ? StaticPropsReturn<P>["props"]
    : never;

const Posts = ({ posts }: StaticProps<typeof getStaticProps>) => (
...
);
```

**Comment by manuschillerdev** [comment] 2020-04-11 20:53
really happy with the result now! 

![props](https://user-images.githubusercontent.com/56154253/79054658-06fd3080-7c47-11ea-82d6-02253c823e48.gif)

**Comment by lukebarton** [comment] 2020-08-05 18:03
```ts
export const getServerSideProps = async ({ params }) => {
  return { 
    props: { foo: "bar" } 
  }
};

export const Page = (props: InferGetServerSidePropsType<typeof getServerSideProps>) => { ... }
```
causes `props: never` however the following works fine:
```ts
export const getServerSideProps = async (ctx) => {
  const params = ctx.params;
  return { 
    props: { foo: "bar" } 
  }
};

export const Page = (props: InferGetServerSidePropsType<typeof getServerSideProps>) => { ... }
```

**Comment by Timer** [comment] 2020-08-05 18:10
Closing as OP issue was resolved. Please open a new issue if you're experiencing a problem!

**Closed by Timer** 2020-08-05 18:10 UTC
Labels: kind: story

**Comment by balazsorban44** [comment] 2022-01-29 18:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
