### ISSUE TITLE
with-apollo example broken with Apollo 3

### ISSUE THREAD

**Issue by pix2D** [vercel/next.js#13702] opened 2020-06-03 06:44 UTC
# Bug report

## Describe the bug

The index page (with `ssr: true`) just keeps loading forever until it times out. The client-only page (with `ssr: false`) works fine.

## To Reproduce

Update `package.json`:
```package.json
{
  "name": "with-apollo",
  "version": "2.0.0",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@apollo/client": "3.0.0-rc.0",
    "@apollo/react-ssr": "^4.0.0-beta.1",
    "graphql": "^14.0.2",
    "graphql-tag": "2.10.3",
    "next": "latest",
    "prop-types": "^15.6.2",
    "react": "^16.7.0",
    "react-dom": "^16.7.0"
  },
  "license": "ISC",
  "devDependencies": {
    "babel-plugin-graphql-tag": "^2.5.0"
  }
}
```

Update all imports to import from `@apollo/client` instead of `@apollo/react-hooks`, `apollo-client` etc.

## Expected behavior

The page should load, with queries processed via SSR.

## System information

- OS: macOS
- Browser (if applies): Firefox 77
- Version of Next.js: 9.4.4
- Version of Node.js: 14.2.0

**Comment by TodorTotev** [comment] 2020-06-03 09:41
The example will be updated in the next few days.

**Comment by pix2D** [comment] 2020-06-08 06:49
Works again from v3.0.0-rc.2; see https://github.com/apollographql/apollo-client/pull/6388.

**Comment by TodorTotev** [comment] 2020-06-08 16:02
![Screenshot 2020-06-08 at 19 01 03](https://user-images.githubusercontent.com/51530311/84053319-6747ee80-a9ba-11ea-9d46-83c1738a4bb5.png)

@Timer The example has been updated by @lfades , also the with-apollo example doesn't use the beta version of @apollo/client, so that issue is not relevant I believe.

**Comment by Timer** [comment] 2020-06-08 16:10
Closing as our example doesn't use the beta package.

**Closed by Timer** 2020-06-08 16:10 UTC
Labels: good first issue, type: example

**Comment by balazsorban44** [comment] 2022-01-30 02:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
