### ISSUE TITLE
`minimumCacheTtl` option in `next.config` does not work when deployed on Vercel, but works locally (next build + next start)

### ISSUE THREAD

**Issue by jzxhuang** [vercel/next.js#52569] opened 2023-07-11 20:42 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:13 PST 2022; root:xnu-8020.240.14~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.18
      pnpm: 7.25.1
    Relevant Packages:
      next: 13.4.10-canary.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/jzxhuang/next-image-ttl

Vercel Deploy URL: https://next-image-ttl.vercel.app/

### To Reproduce

- Set `minimumCacheTtl` to a value other than 60 in `next.config`
- Render a remote image that does not return a `Cache-Control` header
- Deploy to Vercel

### Describe the Bug

When we set `minimumCacheTtl` in next.config, and no `Cache-Control` header is present on the remote resource, we expect the cache-control max-age value to be set to `minimumCacheTtl` as described in https://nextjs.org/docs/pages/api-reference/components/image#caching-behavior. 

This works as expected when building and running Next.js locally, i.e. `next build` followed by `next start`. Here is a screenshot of the response headers when running locally:
<img width="517" alt="image" src="https://github.com/vercel/next.js/assets/26701004/16f6d89e-6bd2-42d8-97e6-0f9f4fcb6c3e">

However, this does not work when deploying the same code to Vercel. The `max-age` is always set to `60` (the default), instead of the value specified by `minimumCacheTtl` in next.config.js
<img width="534" alt="image" src="https://github.com/vercel/next.js/assets/26701004/9eaa7036-7db4-47bb-a2d2-9972e678ad8c">

### Expected Behavior

The `Cache-Control max-age` should be `600` (should equal `minimumCacheTtl` in `next.config`). 

### How are you deploying your application? (if relevant)

Vercel

<sub>[NEXT-1447](https://linear.app/vercel/issue/NEXT-1447/minimumcachettl-option-in-nextconfig-does-not-work-when-deployed-on)</sub>

**Comment by jrobsontull** [comment] 2023-07-12 08:45
@jzxhuang On a local build of canary, this works as expected:

<img width="502" alt="Screenshot 2023-07-12 at 10 43 15 AM" src="https://github.com/vercel/next.js/assets/6155533/c43e02e7-e554-41c6-9c04-1f636b56eb25">

Can you confirm if this is still exists with the latest version of canary and if so, if this is only present when built on Vercel?

**Comment by jzxhuang** [comment] 2023-07-12 11:49
> Can you confirm if this is still exists with the latest version of canary and if so, if this is only present when built on Vercel?

@jrobsontull Yes, this issue is occurring only when deployed on Vercel, as described in the title and description. It occurs on latest canary

However, it is always not caching (MISS) - not sure if this expected behaviour for a local build.
> 
> <img alt="Screenshot 2023-07-12 at 10 43 15 AM" width="502" src="https://user-images.githubusercontent.com/6155533/252910761-c43e02e7-e554-41c6-9c04-1f636b56eb25.png">

In my testing it works as expected locally. Assuming a cold start where you clear `cache` from `.next` output:
- First request to the image would be a MISS, since Next.js has not generated this image yet
- Within the next 10 minutes, requests to the image will hit the browser cache. The browser caches response headers, so this will always show MISS until it needs to be revalidated
- After 10 minutes, browser refetches from the server, and the cache would be STALE (followed by HIT on the next refresh)

Or you can replicate this by disabling cache in network tools. If you disable cache, it will be a cache hit after the initial image generation, and this works as expected for me when running locally. The issue is the value of `max-age`, which should be derived from `minimumCacheTtl` but does not work as expected when deployed on Vercel

**Comment by styfle** [comment] 2023-07-14 16:38
> However, it is always not caching (MISS)

Make sure you have "Disable cache" checked in dev tools or else it will cache the header too.

For my testing, this looks like the Vercel Edge cache works correctly. It can be tested by checking "Disable cache" in dev tools and looking for the `x-vercel-cache: HIT` header. If I wait more than 60 seconds, for example 300 seconds, between page refreshes of https://next-image-ttl.vercel.app then it still responds with `x-vercel-cache: HIT` for the image with a response time of about 65ms. So that confirms the Vercel Edge cache works.

However, the  `Cache-Control` header is wrong. It is stuck at `public, max-age=60` but I would expect that to be `public, max-age=600` like you have [configured in next.config.js](https://github.com/jzxhuang/next-image-ttl/blob/d18b5c13e01e02e88389915f1cafbf8de61662d9/next.config.js#L6C22-L6C25).

I'll let the Edge team know about this bug, thanks!

**Comment by OhKai** [comment] 2023-07-16 12:48
The `Cache-Control` also gets correctly adjusted if the upstream image provider has a greater TTL set. It just won't get updated if the `minimumCacheTTL` in the config is greater.

**Comment by eyyazubi** [comment] 2023-07-26 22:19
i have the same error  max-age=60

**Comment by drichfield** [comment] 2023-07-28 20:16
Problem is still happening, we have an enterprise account and I'll open a ticket with them now.

**Comment by drichfield** [comment] 2023-07-28 21:08
> The `Cache-Control` also gets correctly adjusted if the upstream image provider has a greater TTL set. It just won't get updated if the `minimumCacheTTL` in the config is greater.

I was not able to confirm @OhKai's findings.  What I found is that regardless of if the `minimumCacheTTL` is higher or lower than the origin's max-age, next/image seems to honor the origin's max-age.

I can confirm that `minimumCacheTTL` sets the max-age properly when doing a local production build, just not when running in Vercel.

**Comment by OhKai** [comment] 2023-07-28 21:48
> > The `Cache-Control` also gets correctly adjusted if the upstream image provider has a greater TTL set. It just won't get updated if the `minimumCacheTTL` in the config is greater.
> 
> I was not able to confirm @OhKai's findings. What I found is that regardless of if the `minimumCacheTTL` is higher or lower than the origin's max-age, next/image seems to honor the origin's max-age.

Yeah it might be poorly worded, but that is exactly what I meant. Vercel honors the origin's cache header but not the setting. I wrote "greater" because the `minimumCacheTTL` is not supposed to overwrite a cache-control header if the origin has a higher value so that is as expected.

**Comment by styfle** [comment] 2023-08-02 21:58
This has been fixed. You may have to wait for the duration of the TTL for any existing images to revalidate and receive the new headers.

You can verify using the example image from the original post:

<img width="834" alt="image" src="https://github.com/vercel/next.js/assets/229881/19729f60-3b59-463d-91de-9554920e9cb5">

**Closed by styfle** 2023-08-02 21:58 UTC
Labels: kind: bug, area: next/image, linear: next

**Comment by jzxhuang** [comment] 2023-08-03 02:53
sweet, thanks @styfle can confirm it appears to be fixed! 🎉
