### ISSUE TITLE
CSS Modules not being built or injected into pages

### ISSUE THREAD

**Issue by dijs** [vercel/next.js#13083] opened 2020-05-19 08:52 UTC
# Bug report

## Describe the bug

I followed the docs when setting up my styles. I am using a global `.scss` file from within my `_app.js` page and for every other page I import a `<page>.module.scss` file.

After compiling, I see the built global styles and they work. But none of the module styles are built or injected.

I am **not** using any `withSass` or `withCss`, this is plain NextJS v9.4.1

## Expected behavior

Module styles should be built and injected into pages

## System information

- OS: macOS
- Version of Next.js: v9.4.1
- Version of Node.js: v12.16.1

**Comment by timneutkens** [comment] 2020-05-19 09:09
Please add a complete reproduction.

**Comment by Timer** [comment] 2020-09-03 02:32
Closing as no reproduction provided.

**Closed by Timer** 2020-09-03 02:32 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
