### ISSUE TITLE
TypeScript error when importing `next/image` with `"type": "module"` and `"moduleResolution": "nodenext"`

### ISSUE THREAD

**Issue by michaelhays** [vercel/next.js#47279] opened 2023-03-18 19:27 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: 7.29.1
    Relevant packages:
      next: 13.2.5-canary.8
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

TypeScript

### Link to the code that reproduces this issue

https://github.com/michaelhays/next-ts-import

### To Reproduce

In a new Next.js project, add `"type": "module"` to `package.json`, and set `"moduleResolution": "nodenext"` in `tsconfig.json`.

Importing `next/image` (or any `next/*` package) throws a TypeScript error, though the package is actually found when running the app.

### Describe the Bug

![import](https://user-images.githubusercontent.com/6445661/226132860-fd8df256-5652-494f-bdbc-69b944ba8def.png)

### Expected Behavior

The import should be found by TypeScript.

**Comment by balazsorban44** [comment] 2023-03-19 12:18
Duplicate of #46078

**Closed by balazsorban44** 2023-03-19 12:18 UTC
Labels: template: bug, area: TypeScript
