### ISSUE TITLE
Parallel routes loading both components even in conditional state

### ISSUE THREAD

**Issue by iamarpitpatidar** [vercel/next.js#65344] opened 2024-05-03 23:34 UTC
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/heuristic-wood-sczzqw

### To Reproduce

1. Create next app a parallel route
2. add some console log in both of them
3. no matter what condition you use both console logs get logged.

### Current vs. Expected behavior

logic (in our case console.log) should only be executed of the rendered components

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 15 10:51:06 UTC 2
  Available memory (MB): 15851
  Available CPU cores: 4
Binaries:
  Node: 20.11.1
  npm: 10.7.0
  Yarn: 1.22.22
  pnpm: 9.0.1
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: 14.2.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Parallel & Intercepting Routes

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

**Comment by samcx** [comment] 2024-05-04 01:26
Closing since this is a duplicate of this. → https://github.com/vercel/next.js/issues/53292

**Closed by samcx** 2024-05-04 01:26 UTC
Labels: bug, Parallel & Intercepting Routes
