### ISSUE TITLE
Commonjs detection is too loose in swc-loader

### ISSUE THREAD

**Issue by ewnd9** [vercel/next.js#30638] opened 2021-10-29 21:03 UTC
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

14.17.3

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

Right now commonjs is detected via `indexOf` on a raw source code string: 

https://github.com/vercel/next.js/blob/b5a89160f7b08f8facf5c6d0f1aee6a5c51e0cb1/packages/next/build/webpack/loaders/next-swc-loader.js#L130

I have a dependency which is bundled via `rollup` and containing the following helper:

https://github.com/rollup/rollup/blob/dba6f13132a1d7dac507d5056399d8af0eed6375/test/chunking-form/samples/chunk-namespace-boundary/commonjsHelpers.js#L11-L13

This dependency is transpiled via `next-transpile-modules@9.0.0` (so it's bundled with the app, `dependencyType` changed to `commonjs`) 

It also imports another dependency with `{"type":"module"}` in package.json (`tslib` in my case, not bundled, external).

`webpack` converts it to dynamic import (`module.exports = import("tslib");`, this behaviour is described in https://github.com/webpack/webpack/releases/tag/v5.41.0, couldn't find in docs)

### Expected Behavior

I suppose there is no official way to check if the source is commonjs or not, so just better heuristic.

E.g. check if `module.exports` is in the top level and it's not commented out.

### To Reproduce

https://github.com/ewnd9/next-transpile-modules-repro

**Comment by timneutkens** [comment] 2021-10-30 13:01
This will probably be fixed by #30661

**Comment by ijjk** [comment] 2021-11-01 23:14
Closing as this should be fixed in the latest version of Next.js `v12.0.2`, please update and give it a try!

**Closed by ijjk** 2021-11-01 23:14 UTC
Labels: template: bug, area: SWC transforms

**Comment by ewnd9** [comment] 2021-11-02 08:18
It's still reproducible, I've updated repro to `v12.0.2` https://github.com/ewnd9/next-transpile-modules-repro

It works correctly only if I manually add `module: { type: 'es6' }` in node_modules/.../next-swc-loader.js for server options
 https://github.com/vercel/next.js/blob/b95bc4b74bfa457ee2250108be86fca702cf8461/packages/next/build/webpack/loaders/next-swc-loader.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L77

Just to reiterate, the issue is `swc-loader` transpiling `import` to `require` when it encounters `module.export` (treating it as commonjs file) even though `module` in this case is a function argument.

**Comment by balazsorban44** [comment] 2022-01-27 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
