### ISSUE TITLE
Metadata title won't update if serverActions is enabled

### ISSUE THREAD

**Issue by bagaswastu** [vercel/next.js#51688] opened 2023-06-23 05:26 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 20.2.0
      npm: N/A
      Yarn: N/A
      pnpm: 8.6.3
    Relevant packages:
      next: 13.4.8-canary.1
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/bagaswastu/next-route-reproduction

### To Reproduce

1. Clone the project
2. run `pnpm run dev`
3. Click on "Go to /test"
4. Browser title is changed to "Test Page"
5. Click on "Go to index"
6. Browser title still on "Test Page" when it's should be changed to "Index"
7. Disable serverActions by changing the value from `next.config.js`, and see the expected behavior

Note:
- The bug is tested on two different browsers (Chrome and Edge Chromium)
- The <title> tag is changing, but the change is not reflective to the browser unless user performs a browser refresh (F5)

### Describe the Bug

The metadata title won't updated after going to another route if serverActions is enabled.

### Expected Behavior

The title is changed based on configured metadata.

### Which browser are you using? (if relevant)

Latest Chrome Version 114.0.5735.134 (Official Build) (64-bit), fresh from installation with default setting. No extension or modification

**Comment by shuding** [comment] 2023-06-23 14:20
Duplicate of #49409.

**Closed by shuding** 2023-06-23 14:20 UTC
Labels: template: bug
