### ISSUE TITLE
Different req.query results locally and deployed

### ISSUE THREAD

**Issue by jrozbicki** [vercel/next.js#26486] opened 2021-06-22 16:06 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

14

### What browser are you using?

Brave, Safari

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When calling function e.g. `/api/facilities`, inside `pages/api/facilities.ts` file `req.query` locally I would return `{}`, but deployed server less function will also include `path`, so `req.query` returns `{ path: ['api', 'facilities'] }`. 

This caught me off guard because I had some conditional logic that checked whether object was empty.

Passing query params like `/api/facilities?facilityStatus=existing` would make `req.query` return `{ facilityStatus: 'existing' }` locally, but `{ facilityStatus:'existing', path: ['api', 'facilities'] }` when deployed.

By locally above I mean both `yarn dev` and `yarn build` & `yarn start`

I'm using node v14 both locally and deployed.

### Expected Behavior

`req.query` should yield the same output locally and deployed.

### To Reproduce

https://codesandbox.io/s/reqquery-repro-y93bu - here is basic reproduction of local behaviour

For deployed repro I can only provide screens:
![image](https://user-images.githubusercontent.com/35103924/122960949-3697e480-d384-11eb-97a1-ec52f345e221.png)

**Comment by ijjk** [comment] 2021-06-22 16:12
Hi, can you share the deployment URL for the above project?

**Comment by ijjk** [comment] 2021-06-28 20:43
I'm not able to reproduce this off of the provided information, are rewrites being used when deploying or i18n configuraiton? If you would like to share the deployment URL privately you can share it via https://vercel.com/support

**Comment by ijjk** [comment] 2021-08-04 19:39
I'm gonna close this as a complete reproduction wasn't provided so can't be investigated further. If you are still encountering this please respond with additional information to allow investigating!

**Closed by ijjk** 2021-08-04 19:39 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-01-28 00:13
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
