### ISSUE TITLE
Trojan in webpack.js

### ISSUE THREAD

**Issue by vbragaesilva** [vercel/next.js#21805] opened 2021-02-03 12:56 UTC
**What version of Next.js are you using?**

10.0.3

**What version of Node.js are you using?**

14.15.3

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**How are you deploying your application?**

next dev

**Describe the Bug**

Every time I run "next dev" my windows defender alerts about some trojan in the .next/static/chunks/webpack.js

**Expected Behavior**

No malware should be expected

**To Reproduce**

Only in my computer?

![defender](https://user-images.githubusercontent.com/59237723/106749948-f23ebe80-6605-11eb-8acd-09e477292206.png)

**Comment by talentlessguy** [comment] 2021-02-03 13:01
False positive probably?

**Comment by vbragaesilva** [comment] 2021-02-03 13:35
Ah, yes. Probably it is.

**Comment by timneutkens** [comment] 2021-02-03 15:20
It's a false positive, likely because of the word `eval` being repeated a few times inside of webpack. Disabling windows defender on node.js applications will significantly speed up development in general as well.

Closing as this is a bug in windows defender.

**Closed by timneutkens** 2021-02-03 15:20 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
