### ISSUE TITLE
`next/image` interprets protocol-agnostic `src` prop as relative path

### ISSUE THREAD

**Issue by mduleone** [vercel/next.js#18918] opened 2020-11-07 01:36 UTC
# Bug report

## Describe the bug

When passing the `Image` component a `src` prop that is a protocol-agnostic absolute url, the `Image` component interprets the url as a relative url and fails to properly render.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new `next` app with a page defined as the following
    ```js
    import Image from 'next/image';

    const Home = () => {
      const imageSrc = '//www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'; // or any other protocol-agnostic image source and set up `next.config.js` appropriately

      return (
        <div>
          Protocol Agnostic Images do not work
          <div style={{ position: 'relative', height: '100px', width: '200px' }}>
            <Image layout="fill" src={imageSrc} alt="google logo" />
          </div>
        </div>
      );
    };
    ```
1. Set up `next.config.js` appropriately
1. See that the image doesn't load
1. Update the `imageSrc` to include `https:` in front of `//`
1. See the image load, be sad about the necessary protocol

## Expected behavior

The image should render, however the image fails to render. Inspecting the source reveals that the `Image` component thinks this protocol-agnostic url is instead a relative url

```html
<img alt="google logo" data-src="/_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=3840&amp;q=75" data-srcset="/_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=640&amp;q=75 640w, /_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=750&amp;q=75 750w, /_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=828&amp;q=75 828w, /_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=1080&amp;q=75 1080w, /_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=1200&amp;q=75 1200w, /_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=1920&amp;q=75 1920w, /_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=2048&amp;q=75 2048w, /_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=3840&amp;q=75 3840w" decoding="async" class="" style="visibility: visible; position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px; box-sizing: border-box; padding: 0px; border: none; margin: auto; display: block; width: 0px; height: 0px; min-width: 100%; max-width: 100%; min-height: 100%; max-height: 100%;" src="/_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=3840&amp;q=75" srcset="/_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=640&amp;q=75 640w, /_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=750&amp;q=75 750w, /_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=828&amp;q=75 828w, /_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=1080&amp;q=75 1080w, /_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=1200&amp;q=75 1200w, /_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=1920&amp;q=75 1920w, /_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=2048&amp;q=75 2048w, /_next/image?url=%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F2x%2Fgooglelogo_color_272x92dp.png&amp;w=3840&amp;q=75 3840w">
```

## Screenshots

![Screen Shot 2020-11-06 at 8 33 51 PM](https://user-images.githubusercontent.com/2913188/98428424-68676f80-206f-11eb-8df3-82b60fd14e43.png)

## System information

- OS: macOS
- Browser (if applies) all
- Version of Next.js: 10.0.1
- Version of Node.js: 12.3.1

## Additional context

I would expect protocol-agnostic urls to work as absolute urls.

**Comment by gd996** [comment] 2020-11-08 19:44
any update on this? with local images the folder name is messed up as well.

**Comment by timneutkens** [comment] 2020-11-09 15:26
Duplicate of #18536

**Closed by timneutkens** 2020-11-09 15:26 UTC
Labels: template: bug

**Comment by aldimirprincipal** [comment] 2020-11-13 11:17
@timneutkens How is this a duplicate? In that post there is no solution to this problem. How can you set up images using a variable?

**Comment by balazsorban44** [comment] 2022-01-29 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
