### ISSUE TITLE
Env property undefined in deployed serverless function

### ISSUE THREAD

**Issue by AshConnolly** [vercel/next.js#13454] opened 2020-05-27 17:10 UTC
## Describe the bug

I am connecting to my database in a serverless function. This works locally, but not once deployed. My database connection string is stored in a .env file. When deployed this string is undefined. The env file is committed and in the repo. 

Github repo example - https://github.com/AshConnolly/next-env-issue

Here is my example .env file:
```js
API_KEY='default-api-key'
CLIENT_KEY='default-client-key'
NEXT_PUBLIC_APP_LOCALE='en-us'
TEST='test'
```

When outputted into a page:
```js
  <li>API_KEY='default-api-key' : {process.env.API_KEY}</li>
  <li>CLIENT_KEY='default-client-key' : {process.env.CLIENT_KEY}</li>
  <li>NEXT_PUBLIC_APP_LOCALE='en-us' : {process.env.NEXT_PUBLIC_APP_LOCALE}</li>
  <li>TEST='test' : {process.env.TEST}</li>
```
It shows only the value `NEXT_PUBLIC_APP_LOCALE` - as expected √. 

However in a serverless function, it does not read my env variables correctly. 
This is what my serverless function looks like:
```js
export default async (req, res) => {
  res.setHeader('Content-Type', 'application/json')
  res.statusCode = 200
  res.json({
    API_KEY: process.env.API_KEY,
    CLIENT_KEY: process.env.CLIENT_KEY,
    NEXT_PUBLIC_APP_LOCALE: process.env.NEXT_PUBLIC_APP_LOCALE,
    TEST: process.env.TEST,
  })
}
```
## Expected behavior
Locally this shows correctly when i visit http://localhost:4000/api/test, outputting:
```js
{
"API_KEY": "default-api-key",
"CLIENT_KEY": "default-client-key",
"NEXT_PUBLIC_APP_LOCALE": "en-us",
"TEST": "test"
}
```
## Actual behavior when deployed
However when deployed it does not. it only shows the NEXT_PUBLIC_APP_LOCALE - 
```js
{
"NEXT_PUBLIC_APP_LOCALE": "en-us"
}
````

## To Reproduce

Github repo - https://github.com/AshConnolly/next-env-issue
Run locally, and deploy it to vercel to see the issue. 

## System information

Not applicable as its the deployment issue. 

Why is this happening?
Thanks! 👍

**Comment by ijjk** [comment] 2020-05-27 17:15
Hi, this sounds like a duplicate of https://github.com/zeit/next.js/issues/13332 which was resolved by https://github.com/zeit/next.js/pull/13406 and is available in >= `v9.4.3-canary.1` of Next.js

**Comment by AshConnolly** [comment] 2020-05-27 17:37
Great! Thanks @ijjk! Do you have a rough estimation of how long it will be until that fix is released to master?

**Comment by ijjk** [comment] 2020-05-28 02:59
This should be available on master now in v9.4.3 of Next.js

**Closed** 2020-05-28 03:09 UTC

**Comment by timneutkens** [comment] 2020-05-28 08:10
It was released on stable last night 👍

**Comment by AshConnolly** [comment] 2020-05-28 11:14
You heroes! Thanks @ijjk @timneutkens! 😄

**Comment by balazsorban44** [comment] 2022-01-30 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
