### ISSUE TITLE
Support Nextjs on Deno 

### ISSUE THREAD

**Issue by Gumichocopengin8** [vercel/next.js#24049] opened 2021-04-14 09:38 UTC
### Describe the feature you'd like to request

Nextjs is a powerful React framework on Node, however, it seems like Nextjs are not provided on Deno. Deno is rapidly growing, so I want Nextjs on Deno too!

### Describe the solution you'd like

Uploading Nextjs on https://deno.land/x as third party library. 

### Describe alternatives you've considered

I'm not sure if there's alternative way to use Nextjs on Deno.
If anybody has ideas, I'd like to hear!

**Comment by timneutkens** [comment] 2021-04-14 10:01
Duplicate of #12334

**Closed by timneutkens** 2021-04-14 10:01 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-28 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
