### ISSUE TITLE
Tailwind customization not working on electron

### ISSUE THREAD

**Issue by daniboomerang** [vercel/next.js#22970] opened 2021-03-11 13:24 UTC
### What example does this report relate to?

with-electron-typescript

### What version of Next.js are you using?

10.0.7

### What version of Node.js are you using?

12.20.2

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Other platform

### Describe the Bug

The issue is Tailwind customization in the context of electron

- Install/Run the `with-electron-typescript` example https://github.com/vercel/next.js/tree/canary/examples/with-electron-typescript

- Setup tailwind following the example `with-tailwindcss` https://github.com/vercel/next.js/tree/canary/examples/with-tailwindcss

- Define a custom color, for instance `accent-1`

I can use Tailwind with no problem. The issue comes when trying to use any custom class defined in `tailwind.config.js`
I can use Tailwind classes, what I can't do is

- Neither using custom tailwind classes defined in tailwind.config.js
   For instance `<div className='bg-accent-1'>` doesn't work
- Or use @apply rule on css/less files for custom classes defined in tailwind.config.js
   For instance in a css/less file `.myClass { @apply bg-accent-1 }` doesn't work

It looks to me it's related with the order in which things happen/load. 
It looks like at runtime the custom classes that should have been generated by tailwind are not there
In fact I can confirm they are not there, as I can see in the element web inspector my html using a custom tailwind class, however the style is not there.

There is something going on in electron main and the way at runtime css is loaded that Tailwind customs classes are not created and imported to the compiled css

I'd really appreciate some help here...

Regards

### Expected Behavior

Custom tailwind classes should be available in the compiled css

### To Reproduce

- Install/Run the `with-electron-typescript` example https://github.com/vercel/next.js/tree/canary/examples/with-electron-typescript

- Setup tailwind following the example `with-tailwindcss` https://github.com/vercel/next.js/tree/canary/examples/with-tailwindcss

- Define a custom color, for instance `accent-1`

Try to to make use in a className
F.x `<div className='bg-accent-1'>` doesn't work

Try to @apply it in css/less
F.x `.myClass { @apply bg-accent-1 }` doesn't work

**Comment by daniboomerang** [comment] 2021-03-12 11:04
I figured it out.
It was pretty simple actually.
The issue is in electron projects, the whole web project is placed under a folder renderer.
But the package.json of the project is placed at the root

├── .package.json
├── renderer
├── tailwind.config.json
└── postcss.config.json
└── etc...

The issue is that tailwind is expecting the tailwind.config.json file to be at the root folder.

This can be easily fixed by moving tailwind.config.json and postcss.config.json to the root folder.
However I'd love to keep them inside the rendered folder, cause it's the web project...

Do you know if it's possible to tell tailwind to go find the config files to a different path other than the package.json root folder?

**Comment by daniboomerang** [comment] 2021-03-12 11:34
A key in `package.json` for postcss makes it
```
"postcss": {
    "plugins": {
      "tailwindcss": { "config": "./renderer/tailwind.config.js" }
    }
  },
 ```

**Comment by ijjk** [comment] 2021-04-28 02:58
Closing as this appears to be solved in https://github.com/vercel/next.js/issues/22970#issuecomment-797419328

**Closed by ijjk** 2021-04-28 02:58 UTC
Labels: template: bug, type: example

**Comment by balazsorban44** [comment] 2022-01-28 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
