### ISSUE TITLE
ReactDOMServer does not yet support Suspense

### ISSUE THREAD

**Issue by m-sterspace** [vercel/next.js#29116] opened 2021-09-15 16:32 UTC
### What version of Next.js are you using?

10.0.7

### What version of Node.js are you using?

14.17.5

### What browser are you using?

Edge, Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

export

### Describe the Bug

I tried adding Recoil to my project for state management and used async selectors for datafetching, but as soon as I try and use a Suspense boundary in my project with them, I get thid "ReactDOMServer does not yet support Suspense" error coming from the _document.js file used with Material UI: https://github.com/mui-org/material-ui/blob/master/examples/nextjs/pages/_document.js

![image](https://user-images.githubusercontent.com/37154205/133473711-8b5c3795-6306-4a83-a243-47441b664903.png)

### Expected Behavior

I expect to be able to use Suspense in my project with Material UI without it crashing. 

### To Reproduce

Start a project, add Material UI and the _document file from here: https://github.com/mui-org/material-ui/blob/master/examples/nextjs/pages/_document.js, then add a Suspense boundary to your React tree and refresh the page.

**Comment by m-sterspace** [comment] 2021-09-15 16:33
This seems to have cropped up [before ](https://github.com/vercel/next.js/issues/22508) when a translation module started using Suspense, but the solutions seem to boil down to disabling Suspense on it, which doesn't help me if I'm trying to use Suspense.

**Comment by awareness481** [comment] 2021-09-15 17:00
> but as soon as I try and use a Suspense boundary in my project with them

React `Suspense` isn't yet supported on the server so you can't use it

**Comment by m-sterspace** [comment] 2021-09-15 17:23
Even though my site is purely static using next export?

**Comment by ijjk** [comment] 2021-09-19 15:06
Hi, as mentioned above `Suspense` is not yet available for SSR which is used while prerendering pages, you can ensure `Suspense` is only used on the client by waiting to render these components until after hydration (after useEffect(() => {}, []) has been called)

I'm gonna close this as this doesn't appear to be a bug in Next.js.

**Closed by ijjk** 2021-09-19 15:06 UTC
Labels: template: bug

**Comment by yagudaev** [comment] 2022-01-13 20:46
This seems to work in next@12.0.8.

What happen to me is I did:

```
yarn upgrade react@rc
```

however, `react-dom` package wasn't upgraded.

Doing:

```
yarn upgrade react-dom@rc
```

Fixed it. 

Take a look at other dependencies and make sure they are up to date as well.

**Comment by jonsmithers** [comment] 2022-01-17 18:54
Based on what @ijjk said, I thought an easy/elegant solution would be to just drop in a Suspense replacement that waits until after hydration:

```typescript
const SuspensePostHydration = function(props: SuspenseProps): JSX.Element {
  const [postHydration, setPostHydration] = useState(false);
  useEffect(() => {
    setPostHydration(true);
  }, []);
  return postHydration 
    ? (<Suspense {...props} />) 
    : <></>;
}
```

And use it like so:

```typescript
const DynamicNoSsrComponent = dynamic(() => import('./DynamicComponent'), { ssr: false });

// ...

return (
  <SuspensePostHydration
    fallback={(
      <h1>loading...</h1>
    )} 
  >
    <DynamicNoSsrComponent />
  </SuspensePostHydration>
);
```

But for some reason it never renders the `fallback` property.

**Comment by balazsorban44** [comment] 2022-02-17 00:11
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
