### ISSUE TITLE
❌ [BUG] Infinite reloading with query in URL with `i18n` enabled

### ISSUE THREAD

**Issue by ihmpavel** [vercel/next.js#26926] opened 2021-07-05 08:55 UTC
### What version of Next.js are you using?

^11.0.1

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

- `next start`, `next build`

### Describe the Bug

App (production and development) is reloading infinitely with `internalization` in `next.config.js` and without `getServerSideProps`.

### Expected Behavior

Page should render just once, but without providing `getServerSideProps` it will be reloading infinitely. 

To stop reloading, add to `pages/index.tsx` (as a workaround).
```
export const getServerSideProps = async () => {
  return {
    props: {}
  }
} 
```

### To Reproduce

Create an app `npx create-next-app --ts`.

Edit content `pages/index.tsx` to 
```
import { useRouter } from 'next/router'

const Home = () => {
  const router = useRouter()
 
  return <div>Router info {JSON.stringify(router)}</div>
}
export default Home
```

Edit `next.config.js` to (edit `defaultLocale`  to match your PC locale - eg. local development port)
```
module.exports = {
  reactStrictMode: true,
  i18n: {
    locales: ['cs', 'es', 'de'],
    defaultLocale: 'cs', // <- edit your defaultLocale
    domains: [
      {
        domain: 'localhost:3000',
        defaultLocale: 'cs', // <- edit your defaultLocale
        http: true,
      },
      {
        domain: 'example.com',
        defaultLocale: 'es',
      },
      {
        domain: 'example.de',
        defaultLocale: 'de',
      },
    ],
  }
}

```

Start an app running `yarn dev`.

Load url with some query parameters. Such as `http://localhost:3000/?something=value`

**Comment by ijjk** [comment] 2021-07-07 21:06
Hi, this is due to the port being provided in the domain configuration for `i18n`, this value is only supposed to be the hostname and not the port. 

I'm going to close this since it appears to be caused by invalid configuration, if you are still encountering this after fixing the domain's value please respond with additional information and we can investigate further!

**Closed by ijjk** 2021-07-07 21:06 UTC
Labels: template: bug

**Comment by ihmpavel** [comment] 2021-07-08 09:21
Hi, 

thank you for an easy solution. I am wondering, whether I should create PR for checking if the domain (if provided) is really hostname and if not, throw a warning to the console.

Let me know, if I should create one.

**Comment by ijjk** [comment] 2021-07-08 15:57
Yeah that sounds like a good check to add! This can be added here with other checks being done when loading the config: https://github.com/vercel/next.js/blob/5e6b92059fa9bac0f8a54bd4a1cc02ce6effb597/packages/next/server/config.ts#L322

**Comment by balazsorban44** [comment] 2022-01-28 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
