### ISSUE TITLE
Scripts with async in Head are executed twice

### ISSUE THREAD

**Issue by jonkwheeler** [vercel/next.js#9070] opened 2019-10-14 14:35 UTC
# Bug report

## Describe the bug

Scripts in the Head are run twice if marked `async`.

## To Reproduce

1. Create next app
2. Create file at `/static/log.js` with `console.log('hello');` inside
3. Attach to a page (make sure to add the `async` attribute)
```
<NextHead>
  <script src="/static/log.js" async></script>
</NextHead>
```
4. Run site
5. See duplicate console.log in console.

## Expected behavior

Scripts should only run once.

## Screenshots

![Screen Shot 2019-10-14 at 3 34 44 PM](https://user-images.githubusercontent.com/3136271/66759472-36013800-ee98-11e9-9157-86b2e395adda.jpg)

## System information

- OS: macOS
- Version of Next.js: latest 9.1.1

**Comment by eldyvoon** [comment] 2019-10-15 02:48
doesn't happens to me, here's how I use script in a page
```
import Head from 'next/head'

...
...
return(
    <div>
       <Head><script src='../static/myscript.js' /></Head>
    </div>
)
```

**Comment by jonkwheeler** [comment] 2019-10-15 09:22
@eldyvoon your code shows you didn't set the script tag to `async`. This issue is about `async` scripts.

**Comment by mattjburrows** [comment] 2019-10-17 19:48
I'm very new to nextjs, but this issue peaked my interest.

I've managed to take a quick look at the issue and found that it also happens for script tags with the `defer` attribute as well.

Testing it out locally, it looks like it happens when the client mounts and the script tag goes from `<script src="/logs.js" async=""></script>` to `<script src="/logs.js" async="true"></script>`. Not sure whether React is treating the async attribute as a boolean prop, but not sure how it ends up resolving it to true either.

I tracked it down to [this line in the next-server/lib/head.tsx file](https://github.com/zeit/next.js/blob/canary/packages/next/next-server/lib/head.tsx#L146). Removing the `updateHead` function from the `handleStateChange` prop, stopped the double call. I appreciate this wouldn't be a fix, as the updateHead is there for a reason.

Hopefully this little investigation can help track down the true source of the issue.

**Comment by developit** [comment] 2019-10-17 21:08
On the client, a NextHead update following initial hydration will change the value of the `async` prop from `""` to `true`, which will cause the script to be re-executed.

A brute-force fix for this would be to read in the `props` [when invoking `cloneElement()`](https://github.com/zeit/next.js/blob/c5caa8920973c52f941d9750ac190848c7ca52ee/packages/next/next-server/lib/head.tsx#L128) on the ReactElements passed as children to NextHead, and coerce `async` / `defer` to `""` for true, `undefined` for `false`:

```js
    .map((c: React.ReactElement<any>, i: number) => {
      const key = c.key || i
      const props = { key }
      if ('async' in c.props) props.async = c.props.async ? '' : undefined
      if ('defer' in c.props) props.defer = c.props.defer ? '' : undefined
      return React.cloneElement(c, props)
    })
```

This is not a real solution either, but it might help narrow down the issue.

**Comment by Timer** [comment] 2019-10-17 21:19
A temporary work around is to probably render this instead:
```
<script src="/static/log.js" async="async"></script>
```

**Comment by mattjburrows** [comment] 2019-10-18 09:05
> A temporary work around is to probably render this instead:

I gave that a try when looking into the issue and that still results in the script been re-executed (I should have mentioned that before).

Again, the script element goes from `<script src="/logs.js" async=""></script>` to `<script src="/logs.js" async="async">`.

If you end up going with @developit suggestion, it might be worth taking a look at other boolean [attributes for script tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#Attributes).

**Comment by dsmikeyorke** [comment] 2019-11-06 17:36
I'm experiencing the same issue on a client's website.  They are using Google Hire for job openings so we are loading the following script in <Head>

`<script  id="hire-embed-loader" defer async src="https://hire.withgoogle.com/s/embed/hire-jobs.js" />`

On a client-side render, it loads as expected.  On a server-side render, it runs twice resulting in two identical iframes.  I tried adjusting `async` to `async="async"` which did not do the trick.  

Has anyone found a solution that does not involve the temporary workarounds?

**Comment by jonkwheeler** [comment] 2019-11-06 19:39
@dsmikeyorke a temporary workaround is to have a global var init at the top of the file...

```
/* see if this file already ran, if so, do nothing */
if (window.hasOwnProperty('myScriptNameInit') && window.myScriptName){
  return;
}

/* else if it hasn't run, make that it has. */
window.myScriptNameInit = true;
```

While not ideal, this is a workaround to stop the file from running twice.

**Comment by fabb** [comment] 2019-11-06 20:54
Maybe putting the scripts into `_document.js` resolves the issue temporarily since its contents should only be rendered during SSR and not being hydrated? I might be wrong, just guessing.

**Comment by dsmikeyorke** [comment] 2019-11-12 16:49
Thanks for the feedback!  I ended up wrapping the script in the following conditional so it only renders client-side:

`{process.browser && <script id="hire-embed-loader" defer async src="https://hire.withgoogle.com/s/embed/hire-jobs.js" /> }`

**Comment by jonkwheeler** [comment] 2019-11-12 16:52
@dsmikeyorke oh that's a nifty way to handle that. Any side effects to doing this on a ton of script inclusions?

**Comment by jonkwheeler** [comment] 2019-11-13 13:29
@dsmikeyorke I think I'm gonna go with @timneutkens suggestion here - https://github.com/zeit/next.js/issues/2177#issuecomment-536178575

Very similar to what you said, and to what he said. He says _not_ to assign it to a variable so it tree shakes away, so I'd love confirmation if this is bad or not. I can't imagine one var declaration harming anything, but wanted to double check.

```
const isBrowser = typeof window !== 'undefined'

.......

{isBrowser && <script src="1" />}

{isBrowser && <script src="2" />}

{isBrowser && <script src="3" />}
```

**Comment by fabb** [comment] 2020-03-02 13:53
React forbids difference between SSR and CSR on hydration:

> React expects that the rendered content is identical between the server and the client. It can patch up differences in text content, but you should treat mismatches as bugs and fix them. In development mode, React warns about mismatches during hydration. There are no guarantees that attribute differences will be patched up in case of mismatches. This is important for performance reasons because in most apps, mismatches are rare, and so validating all markup would be prohibitively expensive.

Source: https://reactjs.org/docs/react-dom.html#hydrate

So the solutions outlined here might lead to weird issues. I already had such issues with DOM elements not matching up anymore and having wrong attributes.

**Comment by sambokai** [comment] 2020-05-12 10:22
Loading the script in the following Head component works for me **so far**. Fingers crossed.

```js
const NonSSRHead = dynamic(
    () => import('next/head'),
    { ssr: false }
);
```

**Comment by fabyeah** [comment] 2020-06-27 19:38
> Loading the script in the following Head component works for me **so far**. Fingers crossed.
> 
> ```js
> const NonSSRHead = dynamic(
>     () => import('next/head'),
>     { ssr: false }
> );
> ```

I'm using this workaround now. Though I still get a console warning about "Expected server HTML to contain a matching <header> in <div>." from time to time locally after hot reload. It then seems to break some styles. A page reload fixes it.

**Comment by nileshparwan** [comment] 2020-07-23 13:16
Hello @all, 

I'm getting the same issue as mentioned above.
Does anyone know if a workaround exists? 
Thank you.

**Comment by wyattjoh** [comment] 2020-07-23 14:32
I personally haven’t found anything to get it working. I ended up just loading what I needed in the body and setting up polling to wait for it to load 🙄. It seems that the distinction on the `async=“”` which turns into `async=“async”` is what’s causing the double render, but there’s no way to patch that easily yet.

**Comment by fabyeah** [comment] 2020-08-12 19:53
> > Loading the script in the following Head component works for me **so far**. Fingers crossed.
> > ```js
> > const NonSSRHead = dynamic(
> >     () => import('next/head'),
> >     { ssr: false }
> > );
> > ```
> 
> I'm using this workaround now. Though I still get a console warning `Warning: Expected server HTML to contain a matching <header> in <div>.` from time to time locally after hot reload. It then seems to break some styles. A page reload fixes it.

I changed some code and this stopped working. I am now using `react-script-loader-hoc` (https://github.com/sesilio/react-script-loader-hoc), which is based on this: https://usehooks.com/useScript/
Works so far, no more console errors about

>You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.

**Comment by alexandermendes** [comment] 2020-09-30 20:04
Just came across this too, PR to hopefully fix ☝️

**Comment by Timer** [comment] 2021-01-04 17:54
I just did some more research into this and it appears we cannot fix this in Next.js. It'll have to be fixed by the React team during hydration.

**Closed** 2021-01-04 19:57 UTC
Labels: kind: bug, point: 3

**Comment by msafi** [comment] 2021-12-22 18:23
In my case, I needed to specify `id` attribute on the tag to prevent Next from re-appending it multiple times.

**Comment by balazsorban44** [comment] 2022-01-27 01:28
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
