### ISSUE TITLE
Upgrade V.11 still display Image component width and height error

### ISSUE THREAD

**Issue by Dupflo** [vercel/next.js#29519] opened 2021-09-30 12:18 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.17.1

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### How are you deploying your application?

local

### Describe the Bug

I upgraded Next from v10 to v11 and when I am removing width and height and apply responsive layout I am still facing the issue like if I was at the same V10 version... 

<img width="1000" alt="Capture d’écran 2021-09-30 à 08 16 32" src="https://user-images.githubusercontent.com/39828779/135453315-ca0e0962-d75d-44a6-9fe0-6ad3153dd6eb.png">

Same when I am tying to apply a blur effect

<img width="979" alt="Capture d’écran 2021-09-30 à 08 17 16" src="https://user-images.githubusercontent.com/39828779/135453410-51c66fba-1034-40c8-9a5b-79ef61bfb2b0.png">

### Expected Behavior

Error were not supposed to shown and I must see my app running

### To Reproduce

Upgrade V10 to V11 and remove width and height on Next image component

**Comment by ijjk** [comment] 2021-09-30 14:31
Hi, `height` and `width` is still currently required unless using static image imports, related documentation here https://nextjs.org/docs/basic-features/image-optimization#image-imports

Closing as this isn't a bug and is the expected behavior currently.

**Closed by ijjk** 2021-09-30 14:31 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 16:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
