### ISSUE TITLE
When using i18n on different domains, the subpath routing paths are still active and does not generate 404

### ISSUE THREAD

**Issue by simplenotezy** [vercel/next.js#33491] opened 2022-01-20 11:20 UTC
### Run `next info` (available from version 12.0.8 and up)

Currently using Next.js version `^11.1.2` but issue was also in `12.0.9-canary.4`.

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 14.17.1
      npm: 8.3.0
      Yarn: 1.22.11
      pnpm: N/A
    Relevant packages:
      next: 12.0.9-canary.4
      react: 17.0.2
      react-dom: 17.0.2
```

### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.17.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

When using [domain routing](https://nextjs.org/docs/advanced-features/i18n-routing#domain-routing) you can still access pages using page prefix. E.g.:

    https://domain.com/about-us
    https://domain.com/en/about-us

Both resolve the same URL.

### Expected Behavior

I would expect a 404 for this page:

    https://domain.com/en/about-us

### To Reproduce

Setup domain routing as per [documentation](https://nextjs.org/docs/advanced-features/i18n-routing#domain-routing):

![image](https://user-images.githubusercontent.com/3786627/150329174-3f7cffba-833a-4e5d-8566-15b0c9aa2584.png)

Try to access:

    https://example.nl/fr

You will see the french website.

**Comment by balazsorban44** [comment] 2022-01-20 12:31
Duplicate of #21210

**Closed by balazsorban44** 2022-01-20 12:31 UTC
Labels: template: bug, area: I18n
