### ISSUE TITLE
[i18n + redirects] redirect from prefixed path (/en) to non prefixed path (/) doesn't work

### ISSUE THREAD

**Issue by IskanderMustafin** [vercel/next.js#19574] opened 2020-11-26 18:35 UTC
# Bug report

Redirects from locale prefixed path to non prefixed paths doesn't work when enabling i18n.
In other words redirects from `/en` to `/` (and from `/en/hello` to `/hello`) doesn't happen when I configure `next.config.js` like below:

```
        async redirects() {
            return [
                {
                    source: '/en',
                    destination: '/',
                    permanent: true,
                },
                {
                    source: '/en/:path*',
                    destination: '/:path*',
                    permanent: true,
                }
            ];
        },

       i18n: {
            locales: ['en', 'fr'],
            defaultLocale: 'en',
            localeDetection: false,
        },
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create next.config.js as shown above
2. Try to open `/en`
3. Confirm that redirect doesn't happen

## Expected behavior
Should correctly redirect from `/en` to `/`

## Additional context
This feature worked as expected after [this pull request](https://github.com/vercel/next.js/pull/18427) made by @ijjk (i.e. ), but stopped to work after I upgraded to next.js 10.0.3. I.e. it was broke somewhere between `v10.0.1-canary.1` and `10.0.3`

## System information

- Version of Next.js:  10.0.3

**Comment by ijjk** [comment] 2021-09-21 02:25
Closing as a duplicate of https://github.com/vercel/next.js/issues/21040

**Closed by ijjk** 2021-09-21 02:25 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
