### ISSUE TITLE
Issues with ES2018 unicode RegExp

### ISSUE THREAD

**Issue by xxczaki** [vercel/next.js#19464] opened 2020-11-24 00:03 UTC
# Bug report

## Describe the bug

When I try to use regular expression with `\p{Letter}` or `\p{L}` and the `u` flag, like so:

`/delta(?![\p{Letter}])/u`

I get the following error:

```
Unknown property: Letter
    at Array.map (<anonymous>)
    at Array.map (<anonymous>)
```

## To Reproduce

Try using the RegExp mentioned above in any way on any page.

## Expected behavior

I should be able to use this kind of features, especially in the newer browsers.

## System information

- OS: macOS
- Browser (if applies) N/A
- Version of Next.js: 10.0.2
- Version of Node.js: 14.15.0
- Deployment: local (`next dev`)

## Additional context

The problem doesn't exist in Next.js 9.5.1 and similar versions.

**Comment by timneutkens** [comment] 2020-11-24 08:34
Duplicate of #19303

**Closed by timneutkens** 2020-11-24 08:34 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-29 03:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
