### ISSUE TITLE
Next Image Vercel - Error 502 

### ISSUE THREAD

**Issue by Kellokes** [vercel/next.js#51986] opened 2023-06-29 13:24 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Hi Guys,

Was there any update on vercel yesterday related to the image optimization component?  I haven't made any changes to my code for over a week and yesterday all new images optimized via the Next.js Image component started to break, here's the evidence.

IMAGE URL: https://www.postforge.app/_next/image?url=https://cdn.midjourney.com/0396d1da-905b-49c8-9047-a2534fb287cd/0_0.png&w=828&q=75
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue or a replay of the bug

https://www.postforge.app/_next/image?url=https://cdn.midjourney.com/0396d1da-905b-49c8-9047-a2534fb287cd/0_0.png&w=828&q=75

### To Reproduce

Click in the link of  broken Image: https://www.postforge.app/_next/image?url=https://cdn.midjourney.com/0396d1da-905b-49c8-9047-a2534fb287cd/0_0.png&w=828&q=75

### Describe the Bug

Images broken: https://www.postforge.app/_next/image?url=https://cdn.midjourney.com/0396d1da-905b-49c8-9047-a2534fb287cd/0_0.png&w=828&q=75

![Screenshot_20230629-101852](https://github.com/vercel/next.js/assets/15666/9a4531e7-10ee-4969-92ba-615ab83ba35b)
![Screenshot_20230629-101846](https://github.com/vercel/next.js/assets/15666/1ef98ce5-a120-4628-8ed1-5722deab71c5)

### Expected Behavior

Image appears correctly

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by balazsorban44** [comment] 2023-06-30 12:36
Hi, it's unclear from the provided information what could have happened here. Can you link to a _minimal_ reproduction repository? You can first also make sure that you have the latest version of `next` installed in case an issue related has already been fixed.

The issue might have different reasons, one is that the original image needs authorization, just like in the case of #42776.

We can investigate more with more details. :pray:

**Comment by flosrn** [comment] 2023-07-06 10:40
I am experiencing the exact same issue. All of my new images, whether optimized with next/image or next/legacy/image, are encountering problems.

**Comment by styfle** [comment] 2023-08-02 19:58
Closing since https://www.postforge.app doesn't exist anymore.

If you are having problems with Next.js, please provide the code to reproduce using `next build && next start`.

If the problem only happens on Vercel deployments, please create a support case here: https://vercel.com/help#issues

**Closed by styfle** 2023-08-02 19:58 UTC
Labels: please add a complete reproduction, template: bug, area: next/image, type: needs triage
