### ISSUE TITLE
i need to refresh everytime on same page to display the changes in ondemand isr

### ISSUE THREAD

**Issue by 2820402** [vercel/next.js#37903] opened 2022-06-22 03:50 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

"next": "^12.1.6",
"react": "18.2.0",
"react-dom": "18.2.0",

### What browser are you using? (if relevant)

chrome, firefox, brave

### How are you deploying your application? (if relevant)

vercel

### Describe the Bug

I host my website on Vercel. After that, when I change something on Sanity Studio, the changes are only reflected when I refresh the page, but when I go to another page using Link tag without refreshing the page and come back to the same page, I don't get an updated page, I get a previous page that does not have changes in it.

### Expected Behavior

I expect not to reload the page every time I come to that same page.

### Link to reproduction

the repo is private so i can't public that

##  Api revalidate page

```js
await res.unstable_revalidate(`/categories`);
return res.status(200).send({
    success: true,
    message: 'Revalidated Successfully',
});
```

## that categories page
```jsx
import Link from 'next/link';

const Categories = ({ category }) => {
    return (
        <>
            <div className="row">
                <div className="col-12 col-lg-11 col-xl-8">
                    <div id="page" className="post pb-5 pl-1 pr-1 pl-sm-2 pr-sm-2 pl-md-4 pr-md-4 mb-md-4">
                        <h1 className="dynamic-title">Categories</h1>
                        <div className="post-content">
                            {
                                category.map((item, key) => {
                                    return (
                                        <div className="card categories" key={key}>
                                            <div className="card-header d-flex justify-content-between hide-border-bottom" id="h_2">
                                                <span>
                                                    <i className="far fa-folder-open fa-fw"></i>
                                                    <Link href={`/categories/${item.title.toLowerCase()}`}><a className="ml-1 mr-2">{item.title} </a></Link>
                                                </span>
                                                <span className="text-muted small font-weight-light">{parseInt(item.count)} posts </span>
                                            </div>
                                        </div>
                                    )
                                })
                            }
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default Categories
```

**Comment by ijjk** [comment] 2022-06-22 04:05
Closing as a duplicate of https://github.com/vercel/next.js/issues/35195

See this comment specifically https://github.com/vercel/next.js/issues/35195#issuecomment-1093247078

**Closed by ijjk** 2022-06-22 04:05 UTC
Labels: template: bug
