### ISSUE TITLE
`use` not found in React export with React `18.2`

### ISSUE THREAD

**Issue by andrewmartin** [vercel/next.js#42548] opened 2022-11-06 22:31 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 14.20.0
      npm: 6.14.17
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

I am following the well-written examples [here](https://beta.nextjs.org/docs/data-fetching/fetching#example-fetch-and-use-in-client-components) to use the new React `use` hook in a Client component. I've tried fresh-installing a few times and googling around and couldn't figure out why I'm seeing this error:

```ts
TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_2__.use) is not a function
```

I've tried re-installing React a few times now and I'm definitely using `18.2`.

All I'm really doing is this:

```ts
import {
  use,
} from 'react';
```

Has anyone seen this error before? 

### Expected Behavior

I'd hopefully expect the `use` export from React to be defined.

### Link to reproduction

I'm happy to provide repo if helpful!

### To Reproduce

Simply try importing `use` from React.

**Comment by andrewmartin** [comment] 2022-11-06 22:32
Apologies if this is a silly bug, but I cannot for the life of me figure out what's going on here and am a bit stumped.

**Comment by ShanonJackson** [comment] 2022-11-06 23:08
Think it's exported as `experimental_use` and people are doing import { experiemental_use as use } from "react"

**Comment by Chia1104** [comment] 2022-11-07 02:10
The `use` and `cache` API were declared by Next, they extend the React types.
you can check out [here by the source code](https://github.com/vercel/next.js/blob/canary/packages/next/types/index.d.ts#L31)

The `use` hook still in experimental
if you want to use this in pure React app, you need to install experimental version of React with `import { experiemental_use as use } from "react"`

I think you might have to reinstall Next or make sure you have import the API in Next project.

**Comment by himyjan** [comment] 2022-11-07 08:27
use() hook is in react 18.3 next channel
```
npm i react@next react-dom@next
```
import { use } from "react"

**Comment by balazsorban44** [comment] 2022-11-07 14:06
Hi, `import {use} from "react"` should work, please provide a reproduction.

**Comment by andrewmartin** [comment] 2022-11-07 15:21
Awesome! Thank you!

**Comment by andrewmartin** [comment] 2022-11-07 16:49
I should ask that we update the docs (unless I missed it?).

**Comment by balazsorban44** [comment] 2022-11-08 04:18
You don't need to install `react@next`, if that's what you refer to. If you are having issues, I still ask for a reproduction so, we can have a look.

**Comment by himyjan** [comment] 2022-11-08 08:22
# React 18.2 (latest channel)

https://unpkg.com/react@18.2.0/cjs/react.development.js
<img width="594" alt="image" src="https://user-images.githubusercontent.com/51815522/200498757-f9f49462-82eb-4cf4-a3d8-78338e657bf5.png">

# React 18.3 (next channel or canary)

https://unpkg.com/react@18.3.0-next-fecc288b7-20221025/cjs/react.development.js
<img width="891" alt="image" src="https://user-images.githubusercontent.com/51815522/200499223-0bad91ec-9dcc-4058-9b0d-0eafe057371f.png">

# I think the use() not error with React 18.2 are because using npm package `@types\react` or  `next` types definition (.d.ts), not exposed function from React 18.2 source code

npm package `next` types definition
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/51815522/200502791-ae393c2d-3386-414b-ade6-bcb4c97e620a.png">

npm package `@types\react` types definition
<img width="777" alt="image" src="https://user-images.githubusercontent.com/51815522/200503631-faf5b78b-a102-4d6d-bb9a-5068c4a31e50.png">

so maybe use() hook in React 18.2 in `javascript` project not avaliable, but can use by using type export form `@types\react` or  `next` in `typescript` project.

not work in `javascript` project

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/51815522/200509702-339e83a0-19ff-45f0-a7a5-e3ed757cb283.png">

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/51815522/200511847-5e71958d-83d8-4da7-84d1-fcc4d1635b22.png">

**Comment by andrewmartin** [comment] 2022-11-08 11:44
Ah thank you for the thorough answer with screenshots. Presumably and hopefully if people have issues they'll stumble on this thread if we don't think a docs update is warranted.

**Comment by balazsorban44** [comment] 2022-11-09 01:51
The above is somewhat correct, but when using the `app/` directory, Next.js bundles it's own version of `react`, so it really does not matter what is installed currently. Hence I am asking for a reproduction of a case where you have `react@18.2.0` installed, but `use` is unavailable in `app/`.

**Comment by balazsorban44** [comment] 2022-12-01 13:28
Closing as this is likely not an issue as explained above. Please open a new issue with a reproudction if you believe so.

**Closed by balazsorban44** 2022-12-01 13:28 UTC
Labels: please add a complete reproduction, type: needs investigation, template: bug, area: Server Components
