### ISSUE TITLE
Styled Components Server Rendering - Create Context Error

### ISSUE THREAD

**Issue by nesbtesh** [vercel/next.js#42178] opened 2022-10-30 14:50 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Version 107.0.5304.87 

### Describe the Bug

I am getting  r.createContext is not a function with next 13. The issue appears when I use ThemeProvider with Styled Components server rendering.

<img width="431" alt="Screen Shot 2022-10-30 at 9 47 59 AM" src="https://user-images.githubusercontent.com/3814044/198885024-148b3542-b6dd-45aa-9276-9a109a6c7d77.png">

### Expected Behavior

I expect server rendering to work properly with styled components theme provider. It works fine in previous versions of next js

### Link to reproduction

N/A

### To Reproduce

<img width="802" alt="Screen Shot 2022-10-30 at 9 50 16 AM" src="https://user-images.githubusercontent.com/3814044/198885138-9cc3b090-6c12-4369-bc09-3853132bd3cc.png">

**Comment by kendhia** [comment] 2022-10-30 17:31
duplicate of https://github.com/vercel/next.js/issues/41958 .

**Comment by balazsorban44** [comment] 2022-10-31 17:39
Indeed, a duplicate, please read https://github.com/vercel/next.js/issues/41958#issuecomment-1294063309

**Closed by balazsorban44** 2022-10-31 17:39 UTC
Labels: template: bug, area: app
