### ISSUE TITLE
Docs: DynamicServerError: Dynamic server usage: cookies

### ISSUE THREAD

**Issue by MincePie** [vercel/next.js#54743] opened 2023-08-29 23:25 UTC
### What is the improvement or update you wish to see?

My dev environment works fine. 

Vercel is failing builds on deployment with this error message:

> 
> DynamicServerError: Dynamic server usage: Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
> 09:18:23.380 | at staticGenerationBailout (/vercel/path0/.next/server/chunks/166.js:415:21)
> 09:18:23.380 | at Object.cookies (/vercel/path0/.next/server/chunks/166.js:173:62)
> 09:18:23.380 | at NextServerComponentAuthStorageAdapter.getCookie (/vercel/path0/.next/server/chunks/450.js:203:42)
> 09:18:23.380 | at NextServerComponentAuthStorageAdapter.getItem (/vercel/path0/.next/server/chunks/450.js:572:28)
> 09:18:23.381 | at getItemAsync (/vercel/path0/.next/server/chunks/450.js:3786:33)
> 09:18:23.381 | at SupabaseAuthClient._recoverAndRefresh (/vercel/path0/.next/server/chunks/450.js:2676:69)
> 09:18:23.381 | at SupabaseAuthClient._initialize (/vercel/path0/.next/server/chunks/450.js:1403:24)
> 09:18:23.381 | at /vercel/path0/.next/server/chunks/450.js:1363:35
> 09:18:23.381 | at /vercel/path0/.next/server/chunks/450.js:2041:36
> 09:18:23.381 | at SupabaseAuthClient.lockNoOp [as lock] (/vercel/path0/.next/server/chunks/450.js:1275:18) {
> 09:18:23.381 | digest: 'DYNAMIC_SERVER_USAGE'
> 09:18:23.381
> 
> <br class="Apple-interchange-newline">

This issue thread has now been closed - but I can't find the recommended answer. https://github.com/vercel/next.js/issues/49373

Some of the suggestions in the closed thread adopt something along the lines of:

```
export default async function Index() {
  const cookieStore = cookies(); // <-- this is a new line
  const supabase = createServerComponentClient<Database>({ cookies: () => cookieStore }); // <-- previously this used {cookies} from next header
  const {
    data: { user },
  } = await supabase.auth.getUser()

```

I still fail deployments when I try this.

### Is there any context that might help us understand?

Please can you help to identify what needs to be done to resolve this error. the docs suggest this error results from there not being an await after an async, before a function - i don't have any of those.

thank you

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/messages/dynamic-server-error

**Comment by andrueandersoncs** [comment] 2023-09-21 20:53
I could use some help with this as well, I'm running into the same issue and the given fix doesn't work for me

**Comment by mozeryansky** [comment] 2023-09-23 04:16
This fixed it for me: https://www.reddit.com/r/nextjs/comments/16nptxw/dynamic_server_error_after_upgrading_to_1351_why/k1i2htu

Caused by supabase's example code. Change:
```
export const createServerSupabaseClient = cache(() =>
  createServerComponentClient<Database>({ cookies })
)
```
to:
```
export const createServerSupabaseClient = cache(() => {
  const cookieStore = cookies()
  return createServerComponentClient<Database>({ cookies: () => cookieStore })
})
```

**Comment by landsman** [comment] 2023-10-24 18:18
I would expect to show the actual page (file path of the page) in the error message. I just hit the same error and it's not quite useful to me :(

**Comment by leerob** [comment] 2023-11-09 14:27
The page is dynamically rendering because, presumably, the Supabase instead if needing `cookies`. You can't force having a statically rendering page while also reading from cookies. You'll want to instead cache the data separately from rendering, so you can dynamically render and read the cookies. We're also exploring a way to handle this better called https://www.partialprerendering.com/.

**Comment by leerob** [comment] 2024-01-13 18:38
Closing since this is addressed, please also see the latest Supabase example!

https://github.com/vercel/next.js/tree/canary/examples/with-supabase

**Closed by leerob** 2024-01-13 18:38 UTC
Labels: template: documentation
