### ISSUE TITLE
Next.js executing getStaticProps multiple times at the same second.

### ISSUE THREAD

**Issue by emilpriverrc** [vercel/next.js#26084] opened 2021-06-14 14:49 UTC
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

14.X

### What browser are you using?

Safari

### What operating system are you using?

MacOS

### How are you deploying your application?

Vercel

### Describe the Bug

Revalidation for Next.js sending many requests during the rebuilding of a page. After the build is finished and I enter a page do next send 6 requests, as expected, but when the revalidation is "done" and next want to rebuild the page does next, not all the time but often, send the same 6 requests like 3-4 times per requests which creates a total of 24 requests. It can be more and less at the same time. It's like getStaticProps is executed multiple times instead of only 1 time. It kind of looks like next.js is adding a queue to rebuild the page but don't clear the last request in the queue for that specific page and then execute the queue all at the same time. Which generates this log I show below. All these requests happen at the exact same time.

To clarify, I am console.log the params for the request.

<img width="2047" alt="Skärmavbild 2021-06-14 kl  16 45 18" src="https://user-images.githubusercontent.com/48241986/121911258-e8556680-cd2f-11eb-84d4-33f4de671d93.png">

We are using Sanitys client for the requests and the next-sanity package.

Anyone that has experienced the same issue?

### Expected Behavior

To getStaticProps to only execute 1 time.

### To Reproduce

I did console.log the params for the requests. But a simple console log where you execute your requests.

**Comment by JarrodMFlesch** [comment] 2021-06-14 15:47
@emilpriverrc Maybe your issue is similar to our issue here: #26085?

**Comment by emilpriver** [comment] 2021-06-14 15:51
> @emilpriverrc Maybe your issue is similar to our issue here: #26085?

Yes, it looks like we have the same issue. GetStaticProps fires multiple times?

**Comment by ijjk** [comment] 2021-09-19 05:25
Closing this in favor of the duplicate mentioned issue https://github.com/vercel/next.js/issues/26085

**Closed by ijjk** 2021-09-19 05:25 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
