### ISSUE TITLE
Next/Image priority doesn't add prefetch head tag

### ISSUE THREAD

**Issue by HamAndRock** [vercel/next.js#50694] opened 2023-06-02 13:46 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.4.5-canary.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/cocky-andras-i9yy4p

### To Reproduce

Use Next/Image in any page and add prop priority={true} / priority

### Describe the Bug

Priority tag is ignored and no prefetch tag is added to head tag. It missing both in dev and prod builds

![image](https://github.com/vercel/next.js/assets/24235083/55a17cb1-1dca-4d08-85b3-d0e0633af1ea)

### Expected Behavior

I would expect prefetch to the image being in head tags to speed up loading

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

self, codesandbox

**Comment by HamAndRock** [comment] 2023-06-03 09:55
Found the issue next/image is still using <Head> for the link preload tag, I assume that's broken in app directory since <Head> is no longer supported. I found that there is now ReactDOM.preload() that should be probably used

https://github.com/vercel/next.js/blob/18d112fb5ca62bdb7b1361a65c7e33615d16bdd1/packages/next/src/client/image.tsx#LL959C12-L959C12 Link to source code

**Comment by philipheinser** [comment] 2023-06-09 19:44
@HamAndRock ReactDOM.preload() throws this error for me `Warning: ReactDOM.preload() expected a valid "as" type in the options (second) argument but found "image" instead. Please use one of the following valid values instead: "style", "font", or "script". The href for the preload call where this warning originated is`

**Comment by styfle** [comment] 2023-06-13 21:39
Closing as a duplicate of #43134

See the latest comment here https://github.com/vercel/next.js/issues/43134#issuecomment-1508509744

**Closed by styfle** 2023-06-13 21:39 UTC
Labels: template: bug, area: next/image, area: app
