### ISSUE TITLE
The router cache does not operate properly

### ISSUE THREAD

**Issue by doinki** [vercel/next.js#59600] opened 2023-12-14 00:36 UTC
### Link to the code that reproduces this issue

https://github.com/doinki/next-route-cache

### To Reproduce

```bash
pnpm install
pnpm build
pnpm start
```

The first dynamic page is cached, and after 30 seconds, requests continue to be sent without being cached.
After 30 seconds, you can see that the date changes every time you visit the dynamic page.

![1](https://github.com/vercel/next.js/assets/90969158/738dd341-c405-419f-8dc5-a1f02a1a0b2c)

<video src='https://github.com/vercel/next.js/assets/90969158/ec88f2b6-c438-415c-a86b-71e4270f9f20'></video>

## Current
After 30 seconds, the router cache does not work.

## Expected behavior
If you visit the dynamic page again after 30 seconds, it should be cached for 30 seconds.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 8.12.0
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by ztanner** [comment] 2023-12-19 20:12
Thanks for flagging - this is a duplicate of https://github.com/vercel/next.js/issues/58969 which we'll be looking into soon! Going to close this in favor of having a single issue 🙏

**Closed by ztanner** 2023-12-19 20:12 UTC
Labels: template: bug
