### ISSUE TITLE
next/image 404 no events are fired

### ISSUE THREAD

**Issue by Capricair** [vercel/next.js#36694] opened 2022-05-05 02:21 UTC
### Verify canary release

- [x] I verified that the issue exists in Next.js canary release

### Provide environment information

```
 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 14.17.6
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.5
      react: 17.0.2
      react-dom: 17.0.2
```

### What browser are you using? (if relevant)

Chrome 99.0.4844.82

### Describe the Bug

image 404 onerror event not fired

### Expected Behavior

image 404 fire onerror event

### To Reproduce

```
import Image from "next/image"

export default function Home() {
  function handleLoad() {
    console.log("image load")
  }

  function handleLoadingComplete() {
    console.log("image loading complete")
  }

  function handleError() {
    console.log("image error")
  }

  return (
    <Image
      src="https://img1.jeulia.com/data/product/123.jpg"
      width={300}
      height={300}
      onLoad={handleLoad}
      onLoadingComplete={handleLoadingComplete}
      onError={handleError}
    ></Image>
  )
}
```

**Comment by balazsorban44** [comment] 2022-05-05 11:10
Given your code above, I am not able to reproduce this in either dev or production mode, the error handler gets fired correctly:

![image](https://user-images.githubusercontent.com/18369201/166911339-9b70fa47-a9e8-42ae-9ef2-b186ae8916c7.png)

Is this happening in certain scenarios/browsers/deployments? 

Could you attach a full reproduction?

**Comment by balazsorban44** [comment] 2022-05-05 11:22
I've decided to double-check, and it was actually an issue in `12.1.5` but has been fixed in https://github.com/vercel/next.js/pull/36305

So please upgrade!

**Closed by balazsorban44** 2022-05-05 11:22 UTC
Labels: please add a complete reproduction, area: next/image
