### ISSUE TITLE
ReferenceError: document is not defined in .next/server/middleware-ssr-runtime.js:1:2174)

### ISSUE THREAD

**Issue by saurabhguptarock** [vercel/next.js#31127] opened 2021-11-08 05:47 UTC
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When enabling concurrentFeatures:true and removing 404.tsx page the build proceeds but when running it with next start it gives ReferenceError: document is not defined
    at Function.j.l (/.next/server/middleware-ssr-runtime.js:1:2174)
    at Object.j.f.j (/.next/server/middleware-ssr-runtime.js:1:3469)

### Expected Behavior

There should be no error and it should run properly.

### To Reproduce

Enable concurrentFeatures: true in next.config.js

**Comment by timneutkens** [comment] 2021-11-17 14:44
Closing as no reproduction was provided.

**Closed by timneutkens** 2021-11-17 14:44 UTC
Labels: please add a complete reproduction, template: bug

**Comment by balazsorban44** [comment] 2022-01-27 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
