### ISSUE TITLE
502 error on exception in getStaticProps

### ISSUE THREAD

**Issue by joshuabaker** [vercel/next.js#18013] opened 2020-10-19 11:30 UTC
# Bug report

We’re seeing 502 errors whilst using `getStaticProps` with Next 9.5.3 for the actual dynamic route paths (e.g. `/pages/post/[pid]`). This was initially noticed in Google’s Search Console.

These paths show a `NO_RESPONSE_FROM_FUNCTION` error on Vercel.

## Expected behavior

We’re expecting 404 errors for these, which seemed to be the case in Next 9.4.x.

#### Vercel Error

<img src="https://user-images.githubusercontent.com/160484/96443852-3055d500-1205-11eb-9aa0-99ad3691703f.png" width="482" />

#### Build log

<img src="https://user-images.githubusercontent.com/160484/96444140-a6f2d280-1205-11eb-87cd-e5c7a9355cdc.png" width="246" />

## Additional context

- There’s no additional output in the logs.
- Possibly related to or a duplicate of vercel/next.js#15981.

**Comment by timneutkens** [comment] 2020-10-19 12:08
Steps to reproduce are missing from the template. Always make sure to follow the full issue template.

**Comment by skylus** [comment] 2020-12-27 14:15
I had the exact same issue. 
I have a statically generated page with dynamic params like this:
[lang]/blog/[articleUrlPath]

(The following examples relate to next/link)
My issue appeared when I was linked to it like this(the old way):
```
            href='/[lang]/blog/[articleUrlPath]'
            as={`/${locale}/blog/${article[locale].urlPath}`}
```
I got 502 when navigated to example.com/[lang]/blog/[articleUrlPath]

And then resolved it switching to the new way of using next/link:
```
            href={{
              pathname: '/[lang]/blog/[articleUrlPath]',
              query: {
                lang: locale,
                articleUrlPath: article[locale].urlPath
              }
            }}
            as={`/${locale}/blog/${article[locale].urlPath}`}
```

**Comment by Timer** [comment] 2020-12-28 16:09
Closing as a reproducible demo was never provided.

**Closed by Timer** 2020-12-28 16:09 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 00:11
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
