### ISSUE TITLE
middleware NextResponse.rewrite combination with useRouter

### ISSUE THREAD

**Issue by maapteh** [vercel/next.js#32313] opened 2021-12-09 10:51 UTC
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.7.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

When using the middleware we use the 'NextResponse.rewrite' option to move traffic to other internal places (by doing so we can keep our SEO requirements in place) on route change when passing just a simple query param it wants to go further on the internal part.

```js
export function middleware(req: NextRequest) {
  const { pathname } = req.nextUrl;
  const hostname = req.headers.get('host');

  const country = getCountryCode(hostname);

  if (pathname.startsWith('/locales')) {
    return new Response(null, { status: 404 });
  }

  // when we are on NL website use nl internally
  if (
    country === 'nl' &&
    !pathname.includes('.') && // exclude all files in the public folder
    !pathname.startsWith('/api') // exclude all API routes
  ) {
    if (pathname.startsWith('/nl')) {
      return new Response(null, { status: 404 });
    }

    return NextResponse.rewrite(`/locales/nl-NL${pathname}`);
  }
}
```

My browser url clearly shows: 'http://mpth.nl:3001/tafels-en-bureaus/bijzettafels'

Then the pathname of 'NextRouter' shows it is "/locales/nl-NL/tafels-en-bureaus", which it isn't (maybe internal, but certainly not when looking from client url perspective). 

Now when I do a client-side call for the next page (updating a query parameter) it then also wants to go to the "internal" endpoint  by apending "/locales/nl-NL" to the route.

Is it possible to get both pathnames :) ?

### Expected Behavior

I hoped the internal folder structure with a rewrite would not be pushed to the client code. It seems to be now! All absolute urls using next Link work fine. But i also expect that for the useRouter

```js
export { useRouter } from 'next/router';
```

it seems pathname is the internal one (totally understandable), but i would like to also have the public one (client).

Now im using an altered pathname:

```js
  router.push({
    pathname: window.location.pathname,
    query: params,
  });
```

To bypass the issue

### To Reproduce

~~If needed i can make an example, i firstly hope maybe by adding my used middleware its clear :)~~
https://codesandbox.io/s/github/maapteh/i18n-internal/tree/main

**Comment by maapteh** [comment] 2021-12-09 14:53
@balazsorban44 i understand if pathname in router is the internal route, my question is if we will get both available on the route? Because im fine with using my window.location

**Comment by balazsorban44** [comment] 2021-12-09 15:12
I'm not totally following what internal means here, a clear example would make it easier for me to answer.

**Comment by maapteh** [comment] 2021-12-10 11:09
I made a simple sample, and while creating im more convinced for the router maybe its the correct pathname, and so not a bug.

https://codesandbox.io/s/github/maapteh/i18n-internal/tree/main

From here you can see the Bad button goes into a 404 because it tries to go to the restricted "/locales/nl-NL" part. The Good button will simply use window.location.href and is all fine. Just tell me if the pathname given is expected and works correct :)

**Comment by javivelasco** [comment] 2021-12-15 11:23
I've been looking into this issue and I think it is all expected. When you rewrite using the middleware the actual pathname is indeed the "internal" one (or the one you are rewriting to). The pathname that is shown in the browser is available in the property `asPath` that you can get from the router. The fix for your use case is simply to replace the window location with `asPath`.

I'm going to close this issue but if you find anything wrong feel free to push to reopen it.
Thanks :)

**Closed** 2021-12-15 11:26 UTC
Labels: area: Middleware, area: Routing

**Comment by maapteh** [comment] 2021-12-23 16:42
No Javi, let it stay closed forever :) Thanks for requesting the sample! Appreciated!

**Comment by balazsorban44** [comment] 2022-01-27 01:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
