### ISSUE TITLE
Next 12.3.1 breaks smooth-scrolling, change made in 12.3.1-canary.4, woks in 12.3.1-canary.3 and before

### ISSUE THREAD

**Issue by gurkerl83** [vercel/next.js#40719] opened 2022-09-20 14:36 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 3.2.3
      pnpm: N/A
    Relevant packages:
      next: 12.3.1-canary.3
      eslint-config-next: N/A
      react: 0.0.0-experimental-8951c5fc9-20220915
      react-dom: 0.0.0-experimental-8951c5fc9-20220915

### Describe the Bug

@timneutkens @cramforce The following commit completely disables smooth-scrolling- https://github.com/vercel/next.js/pull/40642. We use the following custom hook here to trigger the scroll-behaviour we want. We do not have anything else like a global css which sets the scroll-behaviour on html. 

The scroll-behaviour becomes non-deterministic in version 12.3.1-canary.4, the previous version 12.3.1-canary.3 works perfectly. The latest release 12.3.1 is also affected.

```
import { MittEmitter } from '@app/render-utils';
import { useEffect } from 'react';

/**
 * The scrolling behavior is always set to smooth, when a page mounts.
 * On route change, the scrolling behavior switches to auto before it snaps back to smooth.
 *
 * Note:
 * Do not use the nextJs hook "use-router" in this custom hook; constant re-renders get executed;
 * Unfortunately, it seems there are some bugs in the router implementation (asPath / hash-change).
 *
 * Instead, the nextJs router events object from the _app component is given as an argument.
 */

export const useSmoothScroll = (events: MittEmitter) => {
  const setSmoothScroll = (isSmooth: boolean) => {
    document.documentElement.style.scrollBehavior = isSmooth
      ? 'smooth'
      : 'auto';
  };

  useEffect(() => {
    setSmoothScroll(true);

    const handleRouteChangeStart = () => setSmoothScroll(false);
    const handleRouteChangeComplete = () => setSmoothScroll(true);

    events.on('routeChangeStart', handleRouteChangeStart);
    events.on('routeChangeComplete', handleRouteChangeComplete);

    return () => {
      events.off('routeChangeStart', handleRouteChangeStart);
      events.off('routeChangeComplete', handleRouteChangeComplete);
    };
  }, []);
};
```

Can you please provide feedback on how to enable scroll-behaviour using the hook again?
Thx!

### Expected Behavior

Identical behaviour like in 12.3.1-canary.3

### Link to reproduction

I will not create a reproducer for things y break; and smooth-scrolling is something which broke a few times in the past.

### To Reproduce

Use the hook from above in _app.

**Comment by gurkerl83** [comment] 2022-10-08 14:08
@timneutkens @cramforce Is there any update on this?

**Comment by noxzym** [comment] 2022-11-11 11:01
any update for this?

**Comment by timneutkens** [comment] 2022-11-11 14:39
@gurkerl83 I'm trying to understand what the problem is with the change that was landed, it implements exactly the behavior that is intended based on your hook: before it scrolls to top during navigation it sets it to `auto`, after it scrolled it sets it to what the value was before scrolling. Seems you can remove that hook and it'll work the way you want it to work?

**Comment by gurkerl83** [comment] 2022-11-13 23:19
@timneutkens I disabled the hook, and configured scrolling with css. The result was really not the same, compared with the hook enabled using a nightly version of Next right before the change landed. For the next two weeks I’m traveling without any device on hand, but I can provide a reproducer afterwards. Thx for looking into that!

**Comment by gurkerl83** [comment] 2022-11-29 12:59
@timneutkens I spent a bit of time on this problem yesterday.

"before it scrolls to top during navigation it sets it to auto, after it scrolled it sets it to what the value was before scrolling."

In fact, the implementation seems to be wrong, as the scroll behaviour "auto" immediately or during scrolling switches back to "smooth" or the globally defined behaviour of the html tag.

Local experiments showed that the scrolling behaviour "auto" must be initiated at the start of a route change "routeChangeStart" and must be maintained until a route change is completed "routeChangeComplete".

Pre-condition: The scroll behaviour "smooth" must either be defined globally in css for the html element. From the hook provided this is done once in the effect-lifecycle, however a user defined configuration seems better, especially as the behaviour can be integrated into Next as described in the next step.

Summary of the lifecycle:
1. Subscribe to routeChangeStart, routeChangeComplete
2. When the route change starts - switch to auto -> scroll immediately to the top / hold this value until the route change finishes.
3. When the route change finishes - switch back to smooth (or whatever was before or globally defined) -> e.g. hash changes are not route changes -> results in smooth scrolling.

In the next step I describe the necessary changes 
- next/client/index.tsx -> component Root

Probably the identical logic is also necessary in the file (not tested as this is probably due to Next's new layout system)
- next/client/components/layout-router -> InnerLayoutRouter

Furthermore, the function handleSmoothScroll, which is called in scrollToHash (file next/shared/lib/router.ts) is not needed.

Thx!

**Comment by wyattjoh** [comment] 2022-11-30 23:52
Hi @gurkerl83! I've attempted to reproduce the issue you described with the scrolling behavior, but I'm having issues with finding any issue.

You can see [this reproduction](https://github.com/wyattjoh/nextjs-scroll-repro) over here https://nextjs-scroll-repro.vercel.app/ and can see that between the navigations, there is no issues.

**Comment by gurkerl83** [comment] 2022-12-01 00:26
@wyattjoh The issue is when you have two pages, both huge in space. Obviously, smooth scrolling on one page is not a problem at it works. But when you are very far from the top of a page and then execute a route change to the other page (also very long) during navigation, the page scrolls all the way up from the previous page position to the top (newly loaded page); this has to be immediate, with "auto" activated until the page loading is finished. I hope this makes sense.

**Comment by wyattjoh** [comment] 2022-12-01 00:31
Is it possible to fork my reproduction to create an appropriate reproduction of the issue?

**Comment by gurkerl83** [comment] 2022-12-01 00:38
I think i see this already in your reproducer. Make the sections larger, scroll down in one page and execute a route change to the other page (not a hash change). You will see a scroll during navigation to the top and this is what needs to be immediate.

**Comment by gurkerl83** [comment] 2022-12-01 22:59
![13932F1A-AE70-418F-A8FE-A39A69132A1C_1_102_o](https://user-images.githubusercontent.com/301689/205176889-794e04f6-9fea-44df-a0d1-3b7658705ce9.jpeg)

**Comment by JanKaifer** [comment] 2022-12-03 18:25
I did the following experiments: [repro](https://github.com/JanKaifer/next-repro-40719/blob/d88d259e7df7d2c0c7969aafdbe267bbbea8b5d8/pages/index.tsx#L5-L9)

These are smooth:
```js
document.documentElement.style.scrollBehavior = "smooth"
await sleep(0);
document.documentElement.style.scrollBehavior = "auto"
window.scrollTo(0, 0)
```
```js
document.documentElement.style.scrollBehavior = "smooth"
await sleep(0);
document.documentElement.style.scrollBehavior = "auto"
await sleep(0);
window.scrollTo(0, 0)
```

These are instant:
```js
document.documentElement.style.scrollBehavior = "smooth"
document.documentElement.style.scrollBehavior = "auto"
window.scrollTo(0, 0)
```
```js
document.documentElement.style.scrollBehavior = "smooth"
await sleep(0);
document.documentElement.style.scrollBehavior = "auto"
await sleep(10);
window.scrollTo(0, 0)
```

Adding `scrollBehavior = "smooth"` after `scrollTo` doesn't change the behavior.

Observations:
- `scrollTo` only cares about the css styles when it is fired
- "smooths" - needs `setTimeout(0)`" to kick in
- "auto" - needs at least `setTimeout(2)` to kick in (`setTimeout(1)` works only sometimes)

**Comment by JanKaifer** [comment] 2022-12-03 18:58
Weird this will be instant:
```css
html {
  scroll-behavior: smooth;
}
```

```js
document.documentElement.style.scrollBehavior = "auto"
await sleep(0);
window.scrollTo(0, 0)
```

And this one seems to be instant even with value set in `css`:
```js
document.documentElement.style.scrollBehavior = "auto"
await sleep(0);
document.documentElement.style.scrollBehavior = "smooth"
await sleep(0);
window.scrollTo(0, 0)
document.documentElement.style.scrollBehavior = originalValue;
```


It seems that when setting from JS it needs `setTimeout(0)` to start using the new CSS and it needs `setTimeout(1+)` when setting it again.

**Comment by JanKaifer** [comment] 2022-12-03 19:05
The problem might be that `scrollTo` is not triggering reflow (but [it should](https://css-tricks.com/what-forces-layout-reflow/)? I haven't found proper docs).
This scrolls instantly:
```css
html {
  scroll-behavior: smooth;
}
```
```js
document.documentElement.style.scrollBehavior = "auto"
document.documentElement.getClientRects() // triggers reflow
window.scrollTo(0, 0)
```

**Comment by JanKaifer** [comment] 2022-12-03 20:00
Forcing reflow with `getClientRects()` in `next.js` source code fixes the issue in @wyattjoh reproduction.
But it's a bit hacky.

Is there something wrong with my observations?

**Comment by gurkerl83** [comment] 2022-12-03 23:11
@JanKaifer I think you have to look at the changes made in https://github.com/vercel/next.js/pull/40642 also mentioned in the very first comment of this issue to make sense of it. To set „auto“, then scroll and then reset back to „smooth“ does not force scrolling to do it in „auto“ or immediate mode, these changes execute in a synchronized manner (resetting to smooth does not wait for scroll to finish).

**Comment by JanKaifer** [comment] 2022-12-04 11:00
I've read the whole thread and I've seen that commit.
I forgot to include the most basic example in my experiments, it's this one:

```css
html {
  scroll-behavior: smooth;
}
```

```js
document.documentElement.style.scrollBehavior = "auto"
window.scrollTo(0)
```

This will be smooth. And triggering reflow before `scrollTo` makes it instant.
That's why I think that your hypothesis with _`auto` needs to be set for the whole animation_ is not right.

_Forcing reflow is a little-known hack that is sometimes necessary. For example for triggering [FLIP](https://aerotwist.com/blog/flip-your-animations/) animations. I don't know about any proper docs._

**Closed** 2022-12-07 10:45 UTC
Labels: template: bug
