### ISSUE TITLE
[NEXT-666] Nested Open Graph metadata overwrites root metadata

### ISSUE THREAD

**Issue by vxna** [vercel/next.js#46434] opened 2023-02-26 04:53 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.19.1
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.28.0
    Relevant packages:
      next: 13.2.2-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue

https://github.com/vxna/next-nested-metadata-merge-repro

### To Reproduce

Navigate the index and nested page back and forth and check meta tags in devtools:

https://user-images.githubusercontent.com/30002276/221392588-36762433-d677-4daf-8bcb-7da4acded778.mp4

### Describe the Bug

Existing Open Graph metadata keys from the root layout aren't getting merged, but completely overwritten with the nested page metadata. That leads into the unused (at the nested page level) keys like `type`, `siteName` or `url` are just gone.

https://github.com/vxna/next-nested-metadata-merge-repro/blob/main/app/layout.tsx#L32-L45
https://github.com/vxna/next-nested-metadata-merge-repro/blob/main/app/nested/page.tsx#L18-L27

### Expected Behavior

> Objects are merged together to form the final metadata output. Duplicate keys are replaced based on their ordering.

https://beta.nextjs.org/docs/api-reference/metadata#ordering

<sub>[NEXT-666](https://linear.app/vercel/issue/NEXT-666/nested-open-graph-metadata-overwrites-root-metadata)</sub>

**Comment by pf1gura** [comment] 2023-02-27 11:11
Same thing happens for `robots`

**Comment by huozhi** [comment] 2023-02-27 12:06
As the documentation mentioned, it's by designed, you need to speicify the full information as well. We merged the first layer of properties, but we don't merge the deeper layers of those properties.

> Objects are merged together to form the final metadata output. Duplicate keys are replaced based on their ordering. Learn more about pages and layouts.

One bad case might happen could be when you don't want to specify some property, but it might accidently deep merge with the few layers away topper level metadata, resulting in unexpected metadata.

**Comment by pf1gura** [comment] 2023-02-27 12:36
In our case properties that are dynamic are not included in metadata for root layout, so this exact issue you described does not happen.

If objects are not deep merged then in most cases specifying this in root layout does not make sense and should not be done.

---

> Objects are merged together to form the final metadata output. Duplicate keys are replaced based on their ordering.

I did not interpret this line in documentation as "objects won't be deep merged", in fact I understood the opposite of it. If the decision on deep merging is final can the documentation be more clear about this?

**Comment by huozhi** [comment] 2023-03-07 14:25
@pf1gura we're tracking the doc updates internally so I'll close this issue for now 🙏 Will rephrase the description on beta docs later

**Closed by huozhi** 2023-03-07 14:25 UTC
Labels: area: Metadata
