### ISSUE TITLE
Separate Argument and Return Types from GetServerSideProps

### ISSUE THREAD

**Issue by defrex** [vercel/next.js#10980] opened 2020-03-11 16:07 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

In the 9.3 docs, the TypeScript solution for `getServerSideProps` is as follows.

```typescript
import { GetServerSideProps } from 'next'

export const getServerSideProps: GetServerSideProps = async context => {
  // ...
}
```

This isn't ideal for two reasons. 

One, you can't use a `function` statement. Not the end of the world, of course, but could be problematic for some teams if they have standards around top-level functions using `function`.

Two, it forces you to return a promise. If you happen to be doing something synchronously, but need it to happen on the server, you are forced to return `Promise.resolve({})` or something similar.

The issues are admittedly minor, but so would be the solution.

## Describe the solution you'd like

This is how `GetServerSideProps` is defined.

```typescript
export type GetServerSideProps = (context: {
  req: IncomingMessage
  res: ServerResponse
  params?: ParsedUrlQuery
  query: ParsedUrlQuery
  preview?: boolean
  previewData?: any
}) => Promise<{ [key: string]: any }>
```

If that was changed to the following, it would be easy to solve these issues.

```typescript
export type GetServerSidePropsContext = {
  req: IncomingMessage
  res: ServerResponse
  params?: ParsedUrlQuery
  query: ParsedUrlQuery
  preview?: boolean
  previewData?: any
}
export type GetServerSidePropsReturn = Promise<{ [key: string]: any }>
export type GetServerSideProps = (context: GetServerSidePropsContext) => GetServerSidePropsReturn
```

**Comment by defrex** [comment] 2020-03-11 16:08
Happy to make a PR if the answer is 👍.

**Comment by herrstucki** [comment] 2020-03-11 16:35
@defrex FYI, I proposed a different approach (doesn't solve the function statement issue though): #10856.

BTW, when declaring an `async` function, the return type will always be a Promise.

```ts
async function f(): Promise<string> { return "foo"; }
```

**Comment by majelbstoat** [comment] 2020-03-12 19:15
I'd like to combine these ideas with allowing GetServersideProps to be parameterised.

At the moment, I can't type the params or query that i'll get into the function:

```ts
export const getServerSideProps: GetServerSideProps = async ({ params }) => {
  const { username } = params // Error username is not defined on {[key: string]: any}
}
```

Also, I can't strongly match the return type to the props that my function will receive. I would like:

```ts
export type GetServerSidePropsContext<Params = ParsedUrlQuery> = {
  req: IncomingMessage
  res: ServerResponse
  params?: Params
  query: ParsedUrlQuery
  preview?: boolean
  previewData?: any
}
export type GetServerSidePropsReturn<Props = {[key: string]: any}> = Promise<{ props: Props }>
export type GetServerSideProps<Params = ParsedUrlQuery, Props = {[key: string]: any}> = (context: GetServerSidePropsContext<Params>) => GetServerSidePropsReturn<Props>
```

With that, I can define:

```ts
type User {
  id: string
}

type MyPageProps = {
  user: User
}

type MyPageParams = {
  username: string
}

const ProfilePage: NextPage<MyPageProps> = ({ user }) => {
  const { id } = user
  // ...
}

export const getServerSideProps: GetServerSideProps<MyPageParams, MyPageProps> = async ({ params }) => {
  const username = params?.username
  const user: User = getUser(username)
  return { props: { user } }
}
```

Thoughts?

**Comment by danilofuchs** [comment] 2020-03-16 17:42
As a workaround while this isn't merged, if you need to get access to the context types:
```
type GetServerSidePropsContext = Parameters<GetServerSideProps>[0];
type GetStaticPropsContext = Parameters<GetStaticProps>[0];
```

**Comment by Timer** [comment] 2020-09-10 19:26
This has been done in the latest Next.js version:
```tsx
export type GetServerSidePropsResult<P> = {
  props?: P
  unstable_redirect?: Redirect
}

export type GetServerSideProps<
  P extends { [key: string]: any } = { [key: string]: any },
  Q extends ParsedUrlQuery = ParsedUrlQuery
> = (
  context: GetServerSidePropsContext<Q>
) => Promise<GetServerSidePropsResult<P>>
```

**Closed by Timer** 2020-09-10 19:26 UTC

**Comment by hems** [comment] 2020-09-28 19:14
> This has been done in the latest Next.js version:

I believe this still only on the `canary` branch?

I tried to add the latest version of next.js to my package.json but i could not because it's a mono repo and turns out there isn't a simple way - that i know - for adding subfolder to the repo.

Is there a simple way of adding the latest commit to the package.json file of a project that relies on a canary version?

**Comment by balazsorban44** [comment] 2022-01-29 11:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
