### ISSUE TITLE
top level :global class should be allowed in local stylesheets (scss)

### ISSUE THREAD

**Issue by orszaczky** [vercel/next.js#10569] opened 2020-02-18 09:56 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

Sometimes we have to style :local scoped classes based on a :global parent class.
Eg: if we have a navbar (higher scope) that contains component wth an input (local scope)
```
:global(.navbar-light) {
    :local(.input-wrapper) {
        ...some styling
    }
}
```
**Error: pure selectors must contain at least one local class or id**

## Describe the solution you'd like

Accept top level :global scope class

## Describe alternatives you've considered

Alternative is adding global class names to local components, which would defeat the purpose of local scope stylesheets, and results in having styling for the same component in multiple location (both the global and local stylesheets)

**Comment by orszaczky** [comment] 2020-02-18 09:59
Also getting the same error when there is clearly at least one local class in the selector:
```
:global(.navbar-light) :local(.input-wrapper) {
    ...some styling
}
```

**Comment by Timer** [comment] 2020-09-03 02:27
Duplicate of #12079

**Closed by Timer** 2020-09-03 02:27 UTC

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
