### ISSUE TITLE
Material ui styling breaks on next 9.5.2

### ISSUE THREAD

**Issue by robertwt7** [vercel/next.js#16347] opened 2020-08-19 12:20 UTC
# Bug report

## Describe the bug

Previously I have 3 projects on next 9.4.4 that works with the latest MUI styling, now it just breaks

## To Reproduce

Install latest material-ui, try to import `<TextField variant="outlined" />`, then it breaks

## Screenshots

![image](https://user-images.githubusercontent.com/15647967/90633776-ff3f3f80-e269-11ea-943c-3ea1fae22917.png)

Previously, looks like this: 

![image](https://user-images.githubusercontent.com/15647967/90633790-09f9d480-e26a-11ea-9972-29e6756cfe6d.png)

## System information

- OS: Windows, WSL
- Browser (if applies) both chrome and safari
- Version of Next.js: latest, checked in yarn.lock got version 9.5.2
- Version of Node.js: v12.18.1

## Additional context

This actually only happens to the `outlined` variant of MUI, if i went to the other variants it works just fine.

Can anyone clarify?

Thanks

**Comment by timneutkens** [comment] 2020-08-19 12:50
Please add a minimal reproduction in a github repository

**Comment by robertwt7** [comment] 2020-08-19 13:19
Here mate:

![image](https://user-images.githubusercontent.com/15647967/90639575-31ed3600-e272-11ea-9fc4-71336d38063b.png)


https://github.com/robertwt7/bug-16347

**Comment by oliviertassinari** [comment] 2020-08-27 17:53
@robertwt7 Did you follow the Next.js example in the Material-UI repository? It looks like you didn't configure _document.js

**Comment by robertwt7** [comment] 2020-09-02 05:30
@oliviertassinari oh no i didn't. I just created nextjs and uses material ui like usual. May i know what's the reason we have to add the `getInitialProps` on the _document? Does that mean that everytime i want to use material ui and nextjs i have to follow that example?

Prior to upgrading I didn't need to do any of those when using material ui though

**Comment by oliviertassinari** [comment] 2020-09-02 09:47
Try https://github.com/mui-org/material-ui/tree/next/examples/nextjs and let us know if you still experience an issue.

**Comment by robertwt7** [comment] 2020-09-15 13:00
Hey guys, just found out today that using `<Icon>close</Icon>` also breaks on latest nextjs and material ui 4.11

**Comment by robertwt7** [comment] 2020-09-15 13:15
Also yes after using `_document.js` example, i can confirm that it works! Is there any reason for that? I'll put that in mind everytime i used material ui with nextjs. I thought that I can use it like previously (just plug and play)

**Comment by Timer** [comment] 2020-09-15 14:35
Closing as OP said it works after following the example.

**Closed by Timer** 2020-09-15 14:35 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
