### ISSUE TITLE
next/image demo doesn't render image when JS is disabled

### ISSUE THREAD

**Issue by remy** [vercel/next.js#27791] opened 2021-08-05 14:56 UTC
### What version of Next.js are you using?

v11.0.0

### What version of Node.js are you using?

12.0.0

### What browser are you using?

Firefox latest

### What operating system are you using?

macOS

### How are you deploying your application?

am not - this is a link from next docs

### Describe the Bug

This URL: https://image-component.nextjs.gallery/layout-fill from the next documentation [next/image page](https://nextjs.org/docs/api-reference/next/image) only renders two images when JS is disabled and not three.

The middle image looks to have a `noscript` but it's not resolving the image source.

### Expected Behavior

next/image progressively enhances and the `img` tag is used when there's broken JS or no JS.

### To Reproduce

Visit https://image-component.nextjs.gallery/layout-fill with js disabled.

**Comment by masx200** [comment] 2021-08-05 15:49
```html

<noscript>
<img loading="lazy" src="pathtoimg">
</noscript>
```

**Comment by remy** [comment] 2021-08-05 16:16
Yeah, @masx200 that _should_ be what nextjs does by default in the next/image component, but it's not.

**Comment by styfle** [comment] 2021-08-05 18:02
I can't reproduce. Here's what I tried:

1. Created new Chrome profile with setting "Don't allow sites to use javascript" chrome://settings/content/javascript
2. Visited https://image-component.nextjs.gallery/layout-fill
3. I see all 3 images on the page and 3 `<noscript>` with view-source

**Comment by kmvan** [comment] 2021-08-08 14:15
Why you disable JS in 2021?

**Comment by remy** [comment] 2021-09-14 16:05
> Why you disable JS in 2021?

All browsers run with JS disabled _before_ JS has finished parsing. And only if the JS parses correctly will it run - assuming the user has it enabled (most do). But if it fails in flight, you have a page that has no JS - and Next's selling point is SSR which means the page will render without JS.

**Comment by remy** [comment] 2021-09-14 16:08
@styfle on Chrome it renders, but **not** in Firefox (I had that in the original bug filed).

I'm using this extension to do it: https://github.com/dpacassi/disable-javascript - but I'd imagine any extension or method would work in Firefox.

**Comment by styfle** [comment] 2021-09-22 17:49
@remy I was able to reproduce with that extension.

However the built-in way (visit `about:config` and set `javascript.enabled: false`) works fine, it loads all 3 images.

I'm not sure why it doesn't observe the `<noscript>` in this case. Seems like a bug with that extension.

**Comment by ijjk** [comment] 2021-09-22 20:26
Looks like this is a known issue with the extension https://github.com/dpacassi/disable-javascript/issues/79

I'm gonna close this in favor of that issue since it doesn't appear to be a Next.js issue.

**Closed by ijjk** 2021-09-22 20:26 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
