### ISSUE TITLE
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Location"]

### ISSUE THREAD

**Issue by Jakst** [vercel/next.js#24977] opened 2021-05-11 07:00 UTC
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

12.21.0

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying your application?

`next start` on heroku

### Describe the Bug

Using some special characters in a URL query key crashes Next and gives a 500 with the following stack trace.

```
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Location"]
  at ServerResponse.setHeader (_http_outgoing.js:533:3)
  at Object.fn (/app/node_modules/next/dist/next-server/server/next-server.js:53:938)
  at Router.execute (/app/node_modules/next/dist/next-server/server/router.js:25:83)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
  at async Server.run (/app/node_modules/next/dist/next-server/server/next-server.js:68:1042)
  at async Server.handleRequest (/app/node_modules/next/dist/next-server/server/next-server.js:32:504) {
    code: 'ERR_INVALID_CHAR'
  }
```

Seems like this has been a problem before in https://github.com/vercel/next.js/issues/17907, but was fixed for that set of characters.

### Expected Behavior

The Next server should return a 404.

### To Reproduce
* Bootstrap a new app with `create-next-app` and start it with either `next dev` or `next start`
* Visit the app with for example the following path: `http://localhost:3003/u/?%23%0d%0ahrs:hrs` (looks like it doesn't crash if you add the query to the root path)
* Observe the server throwing an `Internal server error` and returning 500.

**Comment by Aviortheking** [comment] 2021-06-15 07:54
I am having the same issue with ['Refresh'] instead of ['Location']
```
2021-06-15T07:46:06.094Z	59371c74-5ba8-4fbe-9081-4b3af75c4d1f	ERROR	TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Refresh"]
    at ServerResponse.setHeader (_http_outgoing.js:564:3)
    at handleRedirect (/var/task/node_modules/next/dist/next-server/server/next-server.js:90:1278)
    at Server.renderToHTMLWithComponents (/var/task/node_modules/next/dist/next-server/server/next-server.js:137:683)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Server.renderToHTML (/var/task/node_modules/next/dist/next-server/server/next-server.js:138:1088)
    at async Server.render (/var/task/node_modules/next/dist/next-server/server/next-server.js:75:160)
    at async Object.fn (/var/task/node_modules/next/dist/next-server/server/next-server.js:58:672)
    at async Router.execute (/var/task/node_modules/next/dist/next-server/server/router.js:25:67)
    at async Server.run (/var/task/node_modules/next/dist/next-server/server/next-server.js:68:1042)
    at async Server.handleRequest (/var/task/node_modules/next/dist/next-server/server/next-server.js:32:504) {
  code: 'ERR_INVALID_CHAR'
}
RequestId: 59371c74-5ba8-4fbe-9081-4b3af75c4d1f Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by balazsorban44** [comment] 2022-01-27 14:51
Duplicate of #24047

**Closed by balazsorban44** 2022-01-27 14:51 UTC
Labels: template: bug
