### ISSUE TITLE
Unspecified error while opening the page on IE11

### ISSUE THREAD

**Issue by sarioglu** [vercel/next.js#26931] opened 2021-07-05 13:51 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Internet Exporer 11

### What operating system are you using?

Windows

### How are you deploying your application?

Self managed server

### Describe the Bug

In some situations, Internet Explorer 11 gives `Unspecified Error` on startup while executing the code at`next/next-server/lib/router/router.ts:1231`. This is likely to happen because IE does not allow changing history state if it is either the first page opened on that tab or navigation buttons are disabled. In order to replicate this consistently `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer\Restrictions\NoNavButtons` can be set to `1`. This is a blocker for us since it prevents the site from opening.

### Expected Behavior

The page should open properly.

### To Reproduce

- Set `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer\Restrictions\NoNavButtons` to `1`using Registry Editor.
- Create a new project using `create-next-app`
- Run that new project
- Open the page using Internet Explorer 11
- Page will remain blank.
- To see error on console, open Developer Tools and reload the page.

**Comment by sarioglu** [comment] 2021-07-07 07:39
After some research, I found this answer from StackOverflow: https://stackoverflow.com/a/55595931

As it is advised there, I wrapped original history APIs with a try-catch block to suppress the exception and somehow it worked. I don't know if something else should be done to fix this on next.js codebase.

**Comment by ijjk** [comment] 2021-09-21 04:49
I'm gonna close this as the above workaround sounds alright to handle this case if needed. I don't think we want to add this in Next.js itself as this is a very specific edge case and most IE11 setups should be working as our tests are passing for this.

**Closed by ijjk** 2021-09-21 04:49 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
