### ISSUE TITLE
SSR in next v9 w/ graphql-hooks does not work

### ISSUE THREAD

**Issue by secretlifeof** [vercel/next.js#8598] opened 2019-09-02 09:40 UTC
BUG REPORT

I tried downloading and running the with-graphql-hooks example. It works well with javascript enabled, but does not work with SSR.

Logging { data } to console returns _undefined_.

It is probably related to this:
#8538 

To reproduce:
```
yarn create next-app --example with-graphql-hooks with-graphql-hooks-app
cd with-graphql-hooks-app
yarn dev
```

**Comment by Boosmith** [comment] 2019-09-03 09:05
Hi @timneutkens 
I'd like to take this on please.

**Comment by timneutkens** [comment] 2019-09-03 09:09
@Boosmith sure!

**Comment by julmot** [comment] 2019-09-23 15:43
Related to #8830

**Comment by julmot** [comment] 2019-10-07 08:52
Hey guys, anyone knowing the reason here? I'm willing to contribute, but I don't know where to get started. Do you know the reason for this behavior?

**Comment by luke-j** [comment] 2019-12-22 08:10
I've run into this problem myself, as well. As far as I can see any combination of Apollo hooks and next.js results in no SSR content. 

Just curious what the status is on this issue?

**Comment by mmcxii** [comment] 2020-02-19 07:07
Is this issue still unsolved?

**Comment by aej11a** [comment] 2020-03-14 14:08
@Boosmith / @timneutkens any update on this?

**Comment by jimmyjamieson** [comment] 2020-05-28 13:32
Any update?

I've tried updating to the latest packages, 

`
"graphql-hooks": "^4.4.4",
"graphql-hooks-memcache": "^1.3.2",
"graphql-hooks-ssr": "^1.1.5",
`

but still the same. I like that this is lighter and apollo, so was hoping to use.

**Comment by leerob** [comment] 2021-02-07 17:28
Appears this has been fixed with https://github.com/vercel/next.js/pull/20929.

**Closed by leerob** 2021-02-07 17:28 UTC
Labels: good first issue, type: example

**Comment by balazsorban44** [comment] 2022-01-28 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
