### ISSUE TITLE
NextApiRequest.query has wrong type

### ISSUE THREAD

**Issue by PolarPayne** [vercel/next.js#22152] opened 2021-02-13 17:10 UTC
**What version of Next.js are you using?**

v10.0.6

**What version of Node.js are you using?**

v14.15.4

**What browser are you using?**

Firefox

**What operating system are you using?**

Windows + WSL

**How are you deploying your application?**

next dev

**Describe the Bug**

The type of `NextApiRequest.query` seems to be

```
NextApiRequest.query: {
    [key: string]: string | string[];
}
```

but in reality the value can also be `undefined`.

**Expected Behavior**

The type should be

```
NextApiRequest.query: {
    [key: string]: string | string[] | undefined;
}
```

**To Reproduce**

The following application added as an API page easily shows the problem.

```
import { NextApiRequest, NextApiResponse } from "next";

export default (req: NextApiRequest, res: NextApiResponse) => {
  const { id } = req.query;

  console.log(id);

  res.status(200).json({ id });
};
```

If I'm reading correctly, the problem is [here](https://github.com/vercel/next.js/blob/56b149f7bee9e3fe0565461224a0a94def24b6d0/packages/next/next-server/lib/utils.ts#L203) and the fix would just be adding `| undefined` to the type.

**Comment by PolarPayne** [comment] 2021-02-13 17:11
I checked canary release and this seems to be wrong there too.

**Comment by PolarPayne** [comment] 2021-02-13 17:13
The same problem seems to also apply for the [`cookies`](https://github.com/vercel/next.js/blob/56b149f7bee9e3fe0565461224a0a94def24b6d0/packages/next/next-server/lib/utils.ts#L209).

**Comment by ijjk** [comment] 2022-02-06 00:57
Hi, the types here are correct and the `req.query` and `req.cookies` values should always default to `{}` not `undefined`, if you are seeing undefined then that is a bug. I'm not able to reproduce these values being `undefined` in the latest version of Next.js `v12.0.10` so I'm going to close this. Please open a new issue with a reproduction if you are still seeing this so we can investigate further!

**Closed by ijjk** 2022-02-06 00:57 UTC
Labels: kind: bug, good first issue, area: TypeScript

**Comment by PolarPayne** [comment] 2022-02-09 12:50
Yes, this problem seems to have been fixed with some release.
