### ISSUE TITLE
Smarter Incremental Static Regeneration (ISR)

### ISSUE THREAD

**Issue by TrustyTechSG** [vercel/next.js#29164] opened 2021-09-17 03:16 UTC
### Describe the feature you'd like to request

Now with ISR, we can set a time window so next time someone visit the page might trigger the regeneration process.

For our use case, we only want a page to be regenerated when we made changes on some specific data the page is depend on, and we want the dirty page to be regenerate immediately once the changes is made.

### Describe the solution you'd like

So is there is way we can tell nextJS deployment a page is dirty and needs to be regenerate?

### Describe alternatives you've considered

Like a http call to a /api endpoint?

**Comment by timmysmalls** [comment] 2021-09-17 21:43
I hear ya. I believe this was actually brought up by Tim Neutkens as kind of a north star when static regeneration was first introduced in Next.js. I'm pretty sure this is a duplicate though.

**Comment by ijjk** [comment] 2021-09-18 14:12
Hi, yeah this is a duplicate of https://github.com/vercel/next.js/discussions/22384 and https://github.com/vercel/next.js/discussions/21903 so I'm gonna close this in favor of those.

**Closed by ijjk** 2021-09-18 14:12 UTC
Labels: template: story

**Comment by balazsorban44** [comment] 2022-01-27 20:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
