### ISSUE TITLE
Conflict between rewrites and trailing slash

### ISSUE THREAD

**Issue by jleck** [vercel/next.js#21290] opened 2021-01-18 16:44 UTC
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

14.15.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

Exporting

**Describe the Bug**

When rewrites are configured in next.config.js, the trailing slash conflicts and adds a slash.

**Expected Behavior**

Rewrite rules should take presidence.

**To Reproduce**

Working:

```
{
  async rewrites() {
    return [
      {
        destination: "http://localhost:3000/api/:path*",
        source: "/api/:path*",
      },
    ];
  },
  trailingSlash: false,
}
```

Not working:

```
{
  async rewrites() {
    return [
      {
        destination: "http://localhost:3000/api/:path*",
        source: "/api/:path*",
      },
    ];
  },
  trailingSlash: true,
}
```

**Comment by jleclanche** [comment] 2021-01-23 19:43
Same as #20984 I think.

**Comment by tarunama** [comment] 2021-01-25 04:11
@jleck 
Maybe better to close this issue same as #20984
 for Next.js members.

**Comment by timneutkens** [comment] 2021-01-27 11:36
Duplicate of #20984

**Closed by timneutkens** 2021-01-27 11:36 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 19:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
