### ISSUE TITLE
Can't find module Webpack with example using-preact

### ISSUE THREAD

**Issue by enochndika** [vercel/next.js#22159] opened 2021-02-13 23:20 UTC
**What example does this report relate to?**

using-preact

**What version of Next.js are you using?**

10.0.0

**What version of Node.js are you using?**

15.8.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Ubuntu 20.10

**How are you deploying your application?**

next dev

**Describe the Bug**

When I am trying to run the example with using-preact, it throws the error and it looks like it can't find webpack. I even updated all dependencies to the latest version but it still throws the same error

```
Error: Cannot find module 'webpack'
Require stack:
    - /home/enoch/using-preact-app/node_modules/@prefresh/webpack/src/index.js
- /home/enoch/using-preact-app/node_modules/@prefresh/next/src/index.js
- /home/enoch/using-preact-app/node_modules/next-plugin-preact/index.js
- /home/enoch/using-preact-app/next.config.js
- /home/enoch/using-preact-app/node_modules/next/dist/next-server/server/config.js
- /home/enoch/using-preact-app/node_modules/next/dist/next-server/server/next-server.js
- /home/enoch/using-preact-app/node_modules/next/dist/server/next.js
- /home/enoch/using-preact-app/node_modules/next/dist/server/lib/start-server.js
- /home/enoch/using-preact-app/node_modules/next/dist/cli/next-dev.js
- /home/enoch/using-preact-app/node_modules/next/dist/bin/next
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
at Function.Module._resolveFilename (/home/enoch/using-preact-app/node_modules/module-alias/index.js:49:29)
at Function.Module._load (node:internal/modules/cjs/loader:769:27)
at Module.require (node:internal/modules/cjs/loader:997:19)
at require (node:internal/modules/cjs/helpers:92:18)
at Object.<anonymous> (/home/enoch/using-preact-app/node_modules/@prefresh/webpack/src/index.js:1:17)
  at Module._compile (node:internal/modules/cjs/loader:1108:14)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
  at Module.load (node:internal/modules/cjs/loader:973:32)
  at Function.Module._load (node:internal/modules/cjs/loader:813:14)
  at Module.require (node:internal/modules/cjs/loader:997:19)
  at require (node:internal/modules/cjs/helpers:92:18)
  at Object.<anonymous> (/home/enoch/using-preact-app/node_modules/@prefresh/next/src/index.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
      '/home/enoch/using-preact-app/node_modules/@prefresh/webpack/src/index.js',
      '/home/enoch/using-preact-app/node_modules/@prefresh/next/src/index.js',
      '/home/enoch/using-preact-app/node_modules/next-plugin-preact/index.js',
      '/home/enoch/using-preact-app/next.config.js',
      '/home/enoch/using-preact-app/node_modules/next/dist/next-server/server/config.js',
      '/home/enoch/using-preact-app/node_modules/next/dist/next-server/server/next-server.js',
      '/home/enoch/using-preact-app/node_modules/next/dist/server/next.js',
      '/home/enoch/using-preact-app/node_modules/next/dist/server/lib/start-server.js',
      '/home/enoch/using-preact-app/node_modules/next/dist/cli/next-dev.js',
      '/home/enoch/using-preact-app/node_modules/next/dist/bin/next'
      ]
    }
```

**Expected Behavior**

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully

```

**To Reproduce**

yarn create next-app --example using-preact using-preact-app

**Comment by Regaron** [comment] 2021-02-15 03:03
Adding webpack 4 as dev-dependency solved the problem for me

**Comment by timneutkens** [comment] 2021-02-15 15:44
Duplicate of #21679

**Closed by timneutkens** 2021-02-15 15:44 UTC
Labels: template: bug, type: example

**Comment by balazsorban44** [comment] 2022-01-28 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
