### ISSUE TITLE
swcMinify: true and new Array(n).keys() returns incorrect value in production

### ISSUE THREAD

**Issue by FelixTellmann** [vercel/next.js#38262] opened 2022-07-02 15:45 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise LTSC 2019
    Binaries:
      Node: 16.14.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.1-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome Canary 105.0.5155.1 

### Describe the Bug

Using `swcMinify: true` in the nextjs config breaks the `Array(n)`  operator turning `Array(n)` into `Array(n-1)` in production.

Example:
```
[...Array(4).keys()] // Returns [0, 1, 2] in production
```
Without the swcMinify flag everything works properly.

### Expected Behavior

Array(n) should return  Array(n).

Example:
```
[...Array(4).keys()] // Shouldd return [0, 1, 2, 3] in production
```

### Link to reproduction

https://codesandbox.io/s/dazzling-driscoll-5hubw4?file=/next.config.js

### To Reproduce

Link to production version: https://csb-5hubw4.vercel.app/ with swcMinify true

**Comment by SukkaW** [comment] 2022-07-02 16:42
@FelixTellmann 

Thanks for reporting this!

IMHO, performing such a modification is not safe. Consider this:

```js
globalThis.Array = () => {};
console.log([...Array(4).keys()]);
// This should throw Uncaught TypeError: {}.keys is not a function
// It is not [0, 1, 2, 3]
```

swc can't know if `Array` has been modified, thus it can't perform such an unsafe evaluation.

**Comment by timfuhrmann** [comment] 2022-07-02 23:45
The problem started occurring after updating to React 18 for me. Before, this wasn't problem, even with swcMinify enabled.

**Comment by Austaras** [comment] 2022-07-03 13:34
> @FelixTellmann
> 
> Thanks for reporting this!
> 
> IMHO, performing such a minification is not safe. Consider this:
> 
> ```js
> globalThis.Array = () => {};
> console.log([...Array(4).keys()]);
> // This should throw Uncaught TypeError: {}.keys is not a function
> // It is not [0, 1, 2, 3]
> ```
> 
> swc can't know if `Array` has been modified, thus it can't perform such an unsafe evaluation.

This is indeed enabled by `unsafe` option in terser, however in swc it's enabled by `pristine_globals` and it's enabled by default. I believe it's pretty common in nowadays not to modify built-in objects.

This issue is caused by `swc_ecmascript` version 0.164 upgraded `swc_ecma_minifier` but not correspondingly `swc_ecma_codegen`, upgrade to latest version would fix it.

**Comment by redeyes2015** [comment] 2022-09-01 06:16
It seems next@12.2.3 has fixed this issue. Related PR: https://github.com/vercel/next.js/pull/38347

**Comment by kdy1** [comment] 2023-02-09 01:26
Closing as fixed.
https://codesandbox.io/s/gifted-cloud-qx12zj

**Closed** 2023-02-09 01:27 UTC
Labels: template: bug
