### ISSUE TITLE
Next/Image: Blank div added on top of images in production build only on mobile view

### ISSUE THREAD

**Issue by jahnavijanu143** [vercel/next.js#29338] opened 2021-09-23 17:18 UTC
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

v14.17.3

### What browser are you using?

chrome

### What operating system are you using?

windows 

### How are you deploying your application?

docker,aws

### Describe the Bug

 images loaded using next/image on mobile sized screens seem to be separating from a wrapper div that next/image adds on top of the image in production page. The effect is that there is a blank space above every image about the same size as the image and the image is pushed downwards. This occurs until a hard refresh is done. 

It Does not happen when using normal <img />  tag which is why I believe it's something with next/image.

### Expected Behavior

The image should have the div(white space) on top of it and not above it. Should look as normal.

### To Reproduce

load a page with images using next/image on a mobile screen. Hard refresh to fix the issue.

I deployed my page using docker.In localhost i didnot got any blackspace in mobile view,but in production page the blank space is coming above all image components.I tried by giving "placeholder=empty" and blur value,i also gave BlurdataURL,but nothing was reflected on production page

I also deployed my page using vercel platform in this case,i didnot got any blank space in production page
Is this because of platform issue ?
**this is the production page:**
![Screenshot (42)](https://user-images.githubusercontent.com/86767809/134551441-0ce9c177-b845-4ec2-bf86-a0f1782bee2a.png)

**this is the local host :**
In local host when hover over that img tag
![Screenshot (43)](https://user-images.githubusercontent.com/86767809/134551939-0809aa14-9bf0-4993-84af-15437f44494b.png)

**Example of my Images component:**
 <Image
            src={image2}
            alt={`${title} picture`}
            width={88}
            height={88}
            unoptimized={true}
            blurDataURL={image2}
          />

**Comment by ijjk** [comment] 2021-09-23 17:26
Closing as a duplicate of https://github.com/vercel/next.js/issues/23774

**Closed by ijjk** 2021-09-23 17:26 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 17:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
