### ISSUE TITLE
Index JSON Not found 

### ISSUE THREAD

**Issue by johnthachil** [vercel/next.js#18316] opened 2020-10-27 18:19 UTC
## Newer Vercel Builds 
**Build in Vercel** 
![Image of Yaktocat](https://i.ibb.co/VwRY5Kf/Screenshot-2020-10-27-at-11-27-35-PM.png)

**Vercel Build Output**
![Current Vercel Build Output](https://i.ibb.co/C0hbK5P/Screenshot-2020-10-27-at-11-33-30-PM.png)

This is causing the home page to reload every time I visit

## Older Vercel Builds 
**Build Output** 
![Previous Vercel Build Output](https://i.ibb.co/rHc94mn/Screenshot-2020-10-27-at-11-47-43-PM.png)

**Comment by gutobenn** [comment] 2020-10-27 18:51
Happening here too. It seems since v10.0.0 the index.json is saved to `/_next/data/<build>/index/index.json`, but still try to load from `/_next/data/<build>/index.json`, which returns a 404 error.

**Comment by ijjk** [comment] 2020-10-27 18:52
Hi, this should be corrected, please re-deploy your application and let us know if this is resolved for you!

**Comment by gutobenn** [comment] 2020-10-27 18:55
@ijjk Great, it's working again! Thank you :)

**Comment by ijjk** [comment] 2020-10-27 19:00
@gutobenn thanks for re-trying that! I'm going to close this since it should be resolved correctly now per above.

**Closed by ijjk** 2020-10-27 19:00 UTC

**Comment by johnthachil** [comment] 2020-10-28 02:04
@ijjk Thanks, it's working now 😇

**Comment by balazsorban44** [comment] 2022-01-29 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
