### ISSUE TITLE
Zones, Rewrites and Locales

### ISSUE THREAD

**Issue by alexedwardjones** [vercel/next.js#23264] opened 2021-03-22 09:04 UTC
### Summary
I've followed the [with-zones example](https://github.com/vercel/next.js/tree/canary/examples/with-zones) for having multiple Next.js apps as different "zones" under the same domain using rewrites.

It works really well with the home app running on `localhost:3000` and the blogs app running on `localhost:4000`.
```
localhost:3000 -> Index page of the home app ✅ 
localhost:3000/about -> About page of the home app ✅ 
localhost:3000/blog -> Index page of the blog app ✅ 
localhost:3000/blog/post/1 -> post/[id] page of the blog app ✅ 
```

I've then tried to add i18n to the example using [next-i18next](https://github.com/isaachinman/next-i18next) and it all gets a bit strange. For example if we have two locales for english and german which are `en` and `de` respectively. The routes within the home app work as expected.
```
localhost:3000 -> Index page of the home app in english ✅ 
localhost:3000/de -> Index page of the home app in german ✅ 
localhost:3000/about -> About page of the home app in english ✅ 
localhost:3000/de/about -> About page of the home app in german ✅ 
```
The rewrites to the blog app start getting weird and don't work as expected, presumably partially due to the `basePath` setting.
```
localhost:3000/blog -> Index page of the blog app in english ✅ 
localhost:3000/de/blog -> Index page of the blog app in english ❌ 
localhost:3000/blog/de -> Index page of the blog app in german but the URL doesn't match with "/de/about" ❌ 
localhost:3000/blog/post/1 -> post/[id] page of the blog app in english ✅ 
localhost:3000/de/blog/post/1 -> post/[id] page of the blog app in english ❌ 
localhost:3000/blog/de/post/1 -> 404 error ❌ 
```
### Repo with issue
https://github.com/alexedwardjones/with-zones-and-i18n

### Questions
- Am I doing something wrong?
- Is there anything I can do about this with the current configuration options?
- If not, should I submit a bug or feature request? It seems more like a bug because the [Next.js concept of zones](https://nextjs.org/docs/advanced-features/multi-zones) doesn't support locales properly.

_Originally posted by @alexedwardjones in https://github.com/vercel/next.js/discussions/23198_

**Comment by Alan-QK** [comment] 2021-03-25 03:23
Do you resolove this problem?

**Comment by MitkoTschimev** [comment] 2021-03-25 06:26
I have the same problem related to a subpath before the zones are starting.
We have a micro frontend architecture where every app is in a zone. 
We are working only with SSG and the basePath is destroying the possibility at the moment.
We are not able to put the locale in front of the basePath

/en-us/app1/index.html
/en-us/app2/index.html

Maybe someone else found a solution?

**Comment by ckeeney** [comment] 2021-04-06 23:54
This is likely related (possibly a duplicate) of #21565

**Comment by sandra-goag** [comment] 2021-05-25 15:45
I have the same issue, any ideas??

**Comment by balazsorban44** [comment] 2022-01-25 15:36
Duplicate of #21565

**Closed by balazsorban44** 2022-01-25 15:36 UTC
