### ISSUE TITLE
Update Next.js learn starter to Next.js 10

### ISSUE THREAD

**Issue by lfades** [vercel/next.js#18430] opened 2020-10-28 22:51 UTC
Our current starter has some concerning logs due to Next.js `9.5.3`

Running the following script:

```bash
npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn-starter/tree/master/learn-starter"
```

Output:

![image](https://user-images.githubusercontent.com/4278345/97504929-f17ef800-1945-11eb-8b4a-53dbc05cb7d6.png)

Starter repo: https://github.com/vercel/next-learn-starter
Site repo: https://github.com/vercel/next-site

**Comment by M1ck0** [comment] 2020-10-29 09:15
Is anyone working on this?

**Comment by Danishkhurshid** [comment] 2020-10-29 09:16
I would like to work work on this.

**Comment by Danishkhurshid** [comment] 2020-10-29 10:00
Pull request https://github.com/vercel/next-learn-starter/pull/22

**Comment by timneutkens** [comment] 2020-10-29 12:13
Merged! Thanks @Danishkhurshid 🙏

**Closed by timneutkens** 2020-10-29 12:13 UTC
Labels: good first issue, kind: story, type: website

**Comment by balazsorban44** [comment] 2022-01-29 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
