### ISSUE TITLE
ERR_HTTP_HEADERS_SENT when requesting fallback page in dev

### ISSUE THREAD

**Issue by jamespegg** [vercel/next.js#13868] opened 2020-06-07 14:17 UTC
# Bug report

## Describe the bug

Ever since upgrading to v9.4.4, whenever I'm running the project locally and request a dynamic page which isn't included in `getStaticPaths` it'll error;

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:533:11)
    at DevServer.sendHTML (/Users/jamespegg/Repositories/next_error_example/node_modules/next/dist/server/next-dev-server.js:23:5)
    at DevServer.render (/Users/jamespegg/Repositories/next_error_example/node_modules/next/dist/next-server/server/next-server.js:49:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.fn (/Users/jamespegg/Repositories/next_error_example/node_modules/next/dist/next-server/server/next-server.js:35:852)
    at async Router.execute (/Users/jamespegg/Repositories/next_error_example/node_modules/next/dist/next-server/server/router.js:28:28)
    at async DevServer.run (/Users/jamespegg/Repositories/next_error_example/node_modules/next/dist/next-server/server/next-server.js:44:494)
    at async DevServer.handleRequest (/Users/jamespegg/Repositories/next_error_example/node_modules/next/dist/next-server/server/next-server.js:13:133) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

This is also usually followed by the next-server crashing;

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_http_outgoing.js:643:15)
    at ServerResponse.end (_http_outgoing.js:763:7)
    at DevServer.handleRequest (/Users/jamespegg/Repositories/orangedrivertraining.co.uk/node_modules/next/dist/next-server/server/next-server.js:13:221)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Emitted 'error' event on ServerResponse instance at:
    at writeAfterEndNT (_http_outgoing.js:702:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
error Command failed with exit code 1.
```

I've created a repo to reproduce the issue: https://github.com/jamespegg/next_error_example
Weirdly, it gets the first error but doesn't then crash like it does in my real project.

Going back to v9.4.2 fixes the issue. It also works okay in production / Vercel, so it only seems to affect local development.

## To Reproduce

1. Clone and run https://github.com/jamespegg/next_error_example
2. Go to http://localhost:3000/world
3. See error in logs

The `[...page].js` page component;
```
import React from 'react'

const Page = props => (
  <div>Hello</div>
)

export async function getStaticProps ({ params, preview = false, previewData }) {
  return {
    props: {
      preview
    },
  }
}

export async function getStaticPaths () {

  return {
    paths: [
      { params: 
        {
          page : ["hello"]
        }
      }
    ],
    fallback: true
  }
}

export default Page

```

## Expected behavior

No error

## System information

- OS: macOS 10.15.4
- Version of Next.js: v9.4.4
- Version of Node.js: v14.2.0

**Comment by darshkpatel** [comment] 2020-06-08 06:34
Just checked [jamespegg/next_error_example](https://github.com/jamespegg/next_error_example) 
I was able to reproduce the error 
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:533:11)
    at DevServer.sendHTML (/private/tmp/next_error_example/node_modules/next/dist/server/next-dev-server.js:23:5)
    at DevServer.render (/private/tmp/next_error_example/node_modules/next/dist/next-server/server/next-server.js:49:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.fn (/private/tmp/next_error_example/node_modules/next/dist/next-server/server/next-server.js:35:852)
    at async Router.execute (/private/tmp/next_error_example/node_modules/next/dist/next-server/server/router.js:28:28)
    at async DevServer.run (/private/tmp/next_error_example/node_modules/next/dist/next-server/server/next-server.js:44:494)
    at async DevServer.handleRequest (/private/tmp/next_error_example/node_modules/next/dist/next-server/server/next-server.js:13:133) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

## System Information
* OS: macOS 10.15.5
* Version of Node.js: v14.4.0
* Version of Next.js: v9.4.4

**Comment by TodorTotev** [comment] 2020-06-08 08:06
On it ➤

**Comment by Timer** [comment] 2020-06-08 18:49
This was fixed via #13622!

**Closed by Timer** 2020-06-08 18:49 UTC
Labels: kind: bug

**Comment by ninjadev101** [comment] 2021-03-04 16:35
hey I am seeing this error again: https://tory-api.vercel.app/api/item/1

**Comment by balazsorban44** [comment] 2022-01-28 16:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
