### ISSUE TITLE
The server-only environment variable can not be loaded if `concurrentFeatures: true`

### ISSUE THREAD

**Issue by kjj6198** [vercel/next.js#30891] opened 2021-11-03 13:53 UTC
### What version of Next.js are you using?

latest (12.0.2)

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Edge

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

I'm using [next.js environment variables example](https://github.com/vercel/next.js/tree/canary/examples/environment-variables) as an example. When I upgrade react to 18 (alpha) and enable the `concurrentFeatures: true`, the environment variables become `undefined`.

<img width="1133" alt="截圖 2021-11-03 下午10 45 40" src="https://user-images.githubusercontent.com/6581081/140072532-679265c5-3df3-4a9c-8205-4a8c28b9e7f7.png">

However, public variable can be read.

![public](https://user-images.githubusercontent.com/6581081/140072481-e18ab952-0f81-4531-86ee-8dcac991bbe5.png)

### Expected Behavior

The blog post and docs seems not describing this behavior, so I expected the env variables should be loaded correctly.

### To Reproduce

[Repo](https://github.com/kjj6198/nextjs-concurrent-repro) can be found here.

1. define env variable in `.env`
2. enable `concurrentFeatures: true`
3. restart the dev server and observe the console output

**Comment by huozhi** [comment] 2021-12-25 14:22
Looks like it's fixed in #31261, it works in latest next.js now could you please try again? 🙏

**Closed by huozhi** 2021-12-25 14:22 UTC
Labels: template: bug, area: Concurrent Features

**Comment by balazsorban44** [comment] 2022-01-27 01:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
