### ISSUE TITLE
[WEB-970] [turbopack] Docker ENV  - webpack bundler way faster than turbopack

### ISSUE THREAD

**Issue by joacub** [vercel/next.js#48848] opened 2023-04-26 02:18 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
npx --no-install next info

    Operating System:
      Platform: linux
      Arch: arm64
      Version: #1 SMP Mon Apr 24 06:47:55 UTC 2023
    Binaries:
      Node: 19.9.0
      npm: 9.6.5
      Yarn: N/A
      pnpm: 8.3.1
    Relevant packages:
      next: 13.3.2-canary.6
      eslint-config-next: 13.3.2-canary.6
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Turbopack (--turbo)

### Link to the code that reproduces this issue

no response

### To Reproduce

Run next dev --turbo in a docker environment and in host environment 

### Describe the Bug

Running next dev (Webpack) in a `host machine` MacBook m1 is super slow
Running next dev --turbo (TurboPack) `in host machine` is super fast (or at least good enough) in host machine

Buuuut....

Doing the same yields the oposite, webpack is super fast and turbo pack similar or way slower than webpack, been not stable in the building times ranging from sometimes 2 seconds to 20 seconds with no reasons, webpack remains stable and builds are always ranging from 1 second to 6 seconds pretty much.

Those are Cold builds, hot builds are in webpack slower than in turbo pack which is super fast.

Problems are in cold build that turbo pack is acting erratic and shutingdown some times and not finishing the build in some circumstances.

Also already reported that turbopack has issues with https in docker so I don't know if this is related or not, or if there is any specific configuration or package that we should install in docker to gain the speed that we get in the host machine.

 
_**just in case you may ask, I tested this isolating completely the docker volumes without sharing them with the host machine and yields exactly the same result. sharing volumes are not the cause of this (as also you can notice that webpack is faster in docker than in host machine).**_

### Expected Behavior

Turbopack been faster in docker

this is the image I’m using in docker 
https://github.com/nodejs/docker-node/blob/7a8d51d0e6acd67d14059140231ea52c7be8f023/19/bullseye/Dockerfile

<sub>[WEB-970](https://linear.app/vercel/issue/NEXT-1068/[turbopack]-docker-env-webpack-bundler-way-faster-than-turbopack)</sub>

**Comment by joacub** [comment] 2023-04-26 02:36
don't know if this is util or not but as you can see the Block I/O is really big, that is just running one minute, is writing and reading a lot of datas to the disk.
```
CONTAINER ID   NAME                                  CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
6fa1898807e9   wsy-dev-api                           0.70%     648MiB / 23.44GiB     2.70%     909kB / 1.06MB    19.5MB / 54.6MB   64
fa57eec76e1c   wsy-dev-web                           0.32%     3.424GiB / 23.44GiB   14.61%    243kB / 15.1MB    812MB / 2.54GB    96
1064f40f2cc0   wsy-dev-redis                         0.41%     16.42MiB / 23.44GiB   0.07%     20.8kB / 16.7kB   14.7MB / 0B       5
707d2c6b710c   wsy-prod-torproxy                     0.07%     45.44MiB / 23.44GiB   0.19%     3.94MB / 581kB    22.6MB / 15.4MB   3
b80959765d1c   wsy-dev-db                            0.05%     158.1MiB / 23.44GiB   0.66%     506kB / 868kB     47.2MB / 0B       13
994a4ca50e85   wsy-monorepo-baseimages-baseimage-1   0.00%     77.42MiB / 23.44GiB   0.32%     1.63kB / 0B       71.8MB / 0B       11

```

**Comment by timneutkens** [comment] 2024-05-01 09:29
Going to close this issue as there is no reproduction and there's been a lot of fixes and performance improvements since last year. If you're still running into this please provide a full reproduction / trace files using https://nextjs.org/docs/architecture/turbopack#generating-trace-files. Thanks!

**Closed by timneutkens** 2024-05-01 09:29 UTC
Labels: bug, area: app, Turbopack, linear: next
