### ISSUE TITLE
Unable to build project, Cannot read properties of null (reading 'useContext') 

### ISSUE THREAD

**Issue by zlace** [vercel/next.js#63123] opened 2024-03-11 08:25 UTC
### Link to the code that reproduces this issue

https://github.com/zlace/next-build-error

### To Reproduce

`pnpm dev` works, `pnpm build` fails
 
https://stackblitz.com/edit/github-cmffvl?file=README.md

### Current vs. Expected behavior

Should build successfully

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Thu Sep 14 23:08:13 PDT 2023; root:xnu-10002.40.63.505.1~3/RELEASE_ARM64_T8112
Binaries:
  Node: 18.19.1
  npm: 10.2.4
  Yarn: 1.22.21
  pnpm: 8.12.1
Relevant Packages:
  next: 14.1.3
  eslint-config-next: 14.1.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Module resolution (CJS / ESM, module resolving)

### Which stage(s) are affected? (Select all that apply)

next build (local), Vercel (Deployed)

**Comment by stavros-k** [comment] 2024-03-11 23:12
Might be related with #57277, which was closed due to no re-pro link.

**Comment by batazor** [comment] 2024-03-12 00:16
Suddenly I started catching this error too

Example pipeline - https://gitlab.com/shortlink-org/shortlink/-/jobs/6368837674
Repository: https://github.com/shortlink-org/shortlink/tree/main/boundaries/ui/nx-monorepo/packages/next

I've tried leaving 1 blank page, tried different versions of nx/next/etc, checked that the peer dependencies are correct, deleted the cache, and upgraded the NodeJS version to 21.7 - but nothing worked.

**Comment by collinversluis** [comment] 2024-03-12 22:48
I am having the same issue here

**Comment by poorvasingh04** [comment] 2024-03-17 10:25
Looked at the repo https://github.com/zlace/next-build-error. 

I fixed it by changing `next.config.mjs`. Added node-gyp-build as an external module and use the CommonJS module system when requiring it. 

`/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: config => {
    config.resolve.fallback = { fs: false, net: false, tls: false };
    config.externals.push('pino-pretty', 'lokijs', 'encoding', { 'node-gyp-build': 'commonjs node-gyp-build' });
    return config;
  },
};


export default nextConfig;
`

**Comment by poorvasingh04** [comment] 2024-03-17 10:30
A better fix was me adding previous externals in the webpack config. 

`/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config) => {
    return {
      ...config,
      externals: [...config.externals, "pino-pretty", "encoding"],
    };
  },
};`

**Comment by Matts** [comment] 2024-04-24 17:48
Same issue here, seems to be coming from serverside. NextJS 14.2.3 with --turbo
`Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
 ⨯ TypeError: Cannot read properties of null (reading 'useContext')
    at usePathname (/Users/panda/Documents/Application/frontend/.next/server/chunks/ssr/node_modules_d26df3._.js:4791:238)
    at ErrorBoundary (/Users/panda/Documents/Application/frontend/.next/server/chunks/ssr/node_modules_d26df3._.js:5101:227)
digest: "3330820784"
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:162241)
    at usePathname (/Users/panda/Documents/Application/frontend/.next/server/chunks/ssr/node_modules_d26df3._.js:4791:238)
    at ErrorBoundary (/Users/panda/Documents/Application/frontend/.next/server/chunks/ssr/node_modules_d26df3._.js:5101:227)
    at au (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10446)
    at /Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:15122
    at aw (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at a_ (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ab (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11808)
    at /Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16871
    at aw (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at aw (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46505)
    at a_ (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ab (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11808)
    at /Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16871
    at aw (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at a_ (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at /Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:58612
    at /Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:59270
    at aN (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:59278)
    at Timeout._onTimeout (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:6939)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
 ⨯ TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:162241)
    at usePathname (/Users/panda/Documents/Application/frontend/.next/server/chunks/ssr/node_modules_d26df3._.js:4791:238)
    at ErrorBoundary (/Users/panda/Documents/Application/frontend/.next/server/chunks/ssr/node_modules_d26df3._.js:5101:227)
    at au (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10446)
    at /Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:15122
    at aw (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at a_ (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ab (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11808)
    at /Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16871
    at aw (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at aw (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46505)
    at a_ (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ab (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11808)
    at /Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16871
    at aw (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at a_ (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at /Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:58612
    at /Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:59270
    at aN (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:59278)
    at Timeout._onTimeout (/Users/panda/Documents/Application/frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:6939)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  page: '/backoffice/leads'
}
 GET /backoffice/leads 500 in 514ms

`

**Comment by marlier** [comment] 2024-05-13 20:15
Ran into this today.  Upon investigation discovered that react and react-dom@18.3.1 had been installed, instead of 18.2.0.  Reverting to 18.2.0 made the error go away.

Obviously no promises, but if anyone else is running into this it might be worth checking.

**Comment by osdiab** [comment] 2024-05-14 01:28
My project does still use 18.2.0 and I experience it often so I don't think that's it, at least in my case..

**Comment by telephant** [comment] 2024-05-17 08:04
check the enviroment: `NODE_ENV`, it should be `production` when the `next build`

and I fixed it by set NODE_ENV to production

**Comment by hufftheweevil** [comment] 2024-05-17 14:06
> I have the same issue in development mode, using NextJS 14.2.3 with --turbo. No idea what is causing it.

Ditto. Perhaps this should be in a separate issue, since the OP is referring to `build` and not `dev`. But curious that it's happening both places.

For me, it happens most frequently when I try type in a direct path to a page. In other words, not clicking through the UI to get to a specific page. What I usually do then is go to the root and navigate via the UI. Pain.

**Comment by stabildev** [comment] 2024-05-25 18:42
I am having the same issue **in dev mode**

Can't use `turbopack` in my project currently.

<img width="857" alt="image" src="https://github.com/vercel/next.js/assets/89942958/bcb98cc5-6725-45c4-a62c-3c69fadc3def">

**Comment by john-subba** [comment] 2024-05-29 05:45
This issue is only comes with --turbo flag. When i don't use turbo-pack i don't face the issue. Seems like the turbo pack has issues with other packages.

My versions:
next@14.1.4
react@18.2.0
react@18.2.0

**Comment by kimjong95** [comment] 2024-05-30 00:54
The same issue happens with my projects that don't use turbo.

Occurs with a custom development server, > `"dev": .env.development.local npm run dev-server`
and also occurs with npx next dev. > `npx next dev`

I'm currently using both routers because I'm switching the service from pageRouter to AppRouter.

<img width="966" alt="스크린샷 2024-05-30 09 44 06" src="https://github.com/vercel/next.js/assets/51505451/3e8c29d2-b1ba-4329-872e-a691a0ec8e35">

My error is
- This is not a problem when you use `next/router` or `next/navigation` to access other routers. - O
- This is not a problem when you access the path to the page router directly to the url in your browser. - O
- Problems occur when accessing the route to the app router directly to the url in the browser. - X
- Problems occur when accessing routes that do not match the router. - X

my version
- node: 20.9.0
- next: 14.2.4
- react: 18.2.0
- react-dom: 18.2.0

**Comment by kimjong95** [comment] 2024-05-30 05:28
I solved it.

```diff
// next.config.js
...
   config.resolve.alias = {
        ...config.resolve.alias,
-        react: path.resolve('./node_modules/react'),
        'styled-components': path.resolve('./node_modules/styled-components'),
      };
```

We used alias to unify modules' dependencies while using npm link to use react of current project. we set to an alias for react to `./node_modules/react`.

Seems to work after deleting the alias.

May I know why is this occurring only in dev server?

**Comment by hufftheweevil** [comment] 2024-05-30 06:06
I don't have any alias' in my next config, but I do have a path set in my `jsconfig.json`
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "incremental": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["**/*.js", "**/*.jsx", "src/**/*", "tailwind.config.js"],
  "exclude": ["node_modules"]
}
```
Could that be related?

**Comment by imprisonedmind** [comment] 2024-06-03 19:11
Can confirm it happens to me as soon as I build on v14.2.0 anything lower works fine. 
any page.tsx that has useContext fails with  `Cannot read properties of null (reading 'useContext')`



```json
"next": "14.2.0",
"react": "^18",
"react-dom": "^18",
```

**Comment by Xavier-IV** [comment] 2024-06-12 02:56
Facing this and been scratching my head for hours.

What seems to work is to run the build with experimental compile mode.

```
$ npx next build --experimental-build-mode compile
```

Related comments/issues regarding this flag: https://github.com/vercel/next.js/discussions/46544#discussioncomment-7115457

Extra info:
```
    "next": "^14.2.3",
    "react": "^18",
    "react-dom": "^18",
```

I can confirm this run well on my local and production in Vercel. I'm using dynamic rendering anyway since its more of a "CMS" rather than static blog, so this seems fitting in my case.

**Comment by jvitormelo** [comment] 2024-06-19 12:54
I still have this problem only in dev mode (14.2.3). 

This happens on some pages of my application at random times.

I will update Next it to 14.2.4 to see if fixes it 

![image](https://github.com/vercel/next.js/assets/66218248/b8e02c1e-059d-46c0-9d6b-a9bc7bebcfdb)

**Comment by john-subba** [comment] 2024-06-19 17:25
> I still have this problem only in dev mode (14.2.3).
> 
> This happens on some pages of my application at random times.
> 
> I will update Next it to 14.2.4 to see if fixes it
> 
> ![image](https://private-user-images.githubusercontent.com/66218248/341079935-b8e02c1e-059d-46c0-9d6b-a9bc7bebcfdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MTgxNTgsIm5iZiI6MTcxODgxNzg1OCwicGF0aCI6Ii82NjIxODI0OC8zNDEwNzk5MzUtYjhlMDJjMWUtMDU5ZC00NmMwLTlkNmItYTliYzdiZWJjZmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE3MjQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MWRkYjczYTUyYmFhYjBiYzU0ZGZhNjI1ODAyZjEwNjg0NWZkZGI4NDg0OTU2MGZkMWRmMzI0YTRjNjhjNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t1j8ZKXhbISPM0aMAx6IhyTrnL9Pt9ozZLmy6LuRx5w)

have u tried removing the turbo flag if ure using turbo? if not then this issue will haunt us forever. 😁

**Comment by jvitormelo** [comment] 2024-06-19 19:37
> > I still have this problem only in dev mode (14.2.3).
> > This happens on some pages of my application at random times.
> > I will update Next it to 14.2.4 to see if fixes it


> have u tried removing the turbo flag if ure using turbo? if you are not using turbo then this issue will haunt us forever. 😁

If I remove turbo the app is so slow that it is better to get random crashes lol

**Comment by karlhorky** [comment] 2024-06-25 14:33
For us, this happened when using `@mdx-js/react` in our project along with [Yarn v1 Workspaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/) and [`nohoist`](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/):

- https://github.com/mdx-js/mdx/issues/2499

**Comment by john-subba** [comment] 2024-06-25 16:03
> > > I still have this problem only in dev mode (14.2.3).
> > > This happens on some pages of my application at random times.
> > > I will update Next it to 14.2.4 to see if fixes it
> 
> > have u tried removing the turbo flag if ure using turbo? if you are not using turbo then this issue will haunt us forever. 😁
> 
> If I remove turbo the app is so slow that it is better to get random crashes lol

hahaha yeah man without turbo compile time is so slow.

**Comment by hufftheweevil** [comment] 2024-07-06 15:28
Hopefully that will help put someone on the right track to solve it. However, I am not using next-auth, so it's not limited to just that. But it clearly has something to do with changing some code while in dev mode.

**Comment by hufftheweevil** [comment] 2024-07-06 22:09
Also: sometimes it happens when opening a link to a different page of the same project in a new tab.

**Comment by abriginets** [comment] 2024-08-11 18:06
I was able to fix this in my project! So I'm using next-seo and it's JSON+LD components and the issue was that I forgot adding `useAppDir` to `<BreadcrumbJsonLd />`.

The error behavior and message are completely counter-intuitive though. Pages worked fine, all components rendered and page looked OK, yet NextJS was returning 500 Internal Server Error in both development and production. Debugging this was as simple as removing certain components from the tree.

**Comment by hilmyveradin** [comment] 2024-08-29 13:54
> I'm facing the same issue
> 
> ```
> Uncaught TypeError: Cannot read properties of null (reading 'useContext')
>     at t.useContext (file:///Users/mario/Documents/GitHub/blah/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:162241)
>     at usePathname (file:///Users/mario/Documents/GitHub/blahapps/web/.next/server/chunks/ssr/08b5e_next_dist_esm_1c713e._.js:3834:238)
>     at ErrorBoundary 
> ```
> 
> I can reproduce it. Changing the authOptions for next-auth while application is running in dev mode triggers the same error everytime. I always restart the server to fix the problem, It's extreamly annoying.

I had the exact same issue and this solved it! Thank you

**Comment by huozhi** [comment] 2024-09-04 23:17
Reagrding to the original issue, it's erroring because it drops the default webpack config externals and [this comment](https://github.com/vercel/next.js/issues/63123#issuecomment-2002398438) is the right fix. Closing this issue as this general react error could cause by various root cause.

Please open a new issue with reproduction of your case, we'd love to help investigate the specific root cause 🙏

**Closed by huozhi** 2024-09-04 23:17 UTC
Labels: bug, Module Resolution
