### ISSUE TITLE
styled-jsx css.resolve tag does not work anymore when using top level css rules without enclosing those rules in a selector

### ISSUE THREAD

**Issue by AzureLithium** [vercel/next.js#30530] opened 2021-10-28 09:49 UTC
### What version of Next.js are you using?

12.0.1 and 12.0.2-canary.2

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04.3 LTS

### How are you deploying your application?

next start

### Describe the Bug

In previous Next.js versions, styled-jsx css.resolve tag works using top level css rules without enclosing those rules in a selector, in Next.js 12.0.0+ it does not.

Running npm run dev results in:

```
wait  - compiling /...
error - ./components/NavLink/NavLink.js
Error: error: Invalid selector
  
   |
38 |   border-bottom: 3px solid #000000;
   |                 ^

error: Failed to parse css in styled jsx component
  
   |
37 |   const navLinkSelected = () => css.resolve`
   |  __________________________________________^
38 | |   border-bottom: 3px solid #000000;
39 | | `;
   | |_^
   |
   = note: Input to the css parser is 
             border-bottom: 3px solid #000000;
```

### Expected Behavior

CSS compiles and aplies correctly to the element, like the [styled-jsx resolve tag documentation](https://github.com/vercel/styled-jsx#the-resolve-tag) specifies

### To Reproduce

Try to render an example component like this one:

**NavLink.js**

```
import { css } from 'styled-jsx/css';

const navLinkSelected = () => css.resolve`
  border-bottom: 3px solid #000000;
`;

function NavLink() {
  const { className: navLinkSelectedClassName, styles: navLinkSelectedJSX } = navLinkSelected();

  return (
    <a className={navLinkSelectedClassName} >
        {navLinkSelectedJSX}
        {'example nav link'}
    </a>
  );
}
```

**Comment by sudhiry** [comment] 2021-11-25 05:16
Is there any workaround we can do in the meantime?

**Comment by padmaia** [comment] 2021-11-30 19:17
This has to do with our new CSS parser written in Rust. We wrote about it a bit in our [v12 upgrade guide](https://nextjs.org/docs/upgrading)

>On top of the Rust-based compiler we've implemented a new CSS parser based on the CSS parser that was used for the styled-jsx Babel transform. This new parser has improved handling of CSS and now errors when invalid CSS is used that would previously slip through and cause unexpected behavior.

The example in the issue could be fixed by changing the css to have valid syntax:
```
const navLinkSelected = () => css.resolve`
  a {
    border-bottom: 3px solid #000000;
  }
`;
```
This is very similar to the example in the styled-jsx documentation linked to in the issue:

```
const { className, styles } = css.resolve`
  a { color: green }
`
```
I don't think it was ever an explicitly supported feature, just a quirk of the css parser that happened to work. I am going to close the issue for now as we probably will not add support for this.

**Closed by padmaia** 2021-11-30 19:17 UTC
Labels: kind: bug, area: SWC transforms

**Comment by balazsorban44** [comment] 2022-01-27 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
