### ISSUE TITLE
not support proxy-agent

### ISSUE THREAD

**Issue by coderzzp** [vercel/next.js#47039] opened 2023-03-12 03:47 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64
    Binaries:
      Node: 16.19.1
      npm: 8.19.3
      Yarn: 1.3.2
      pnpm: 7.29.1
    Relevant packages:
      next: 13.2.3
      eslint-config-next: 13.2.3
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

no

### To Reproduce

```javascript
  const res = await fetch('https://api.openai.com/v1/chat/completions', {
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${process.env.OPENAI_API_KEY ?? ''}`,
    },
    agent: new ProxyAgent('http://127.0.0.1:7890'),
    method: 'POST',
    body: JSON.stringify(payload),
  })
```

### Describe the Bug

proxy failed and fetch failed
```shell
error - Error: The edge runtime does not support Node.js 'events' module.
```

### Expected Behavior

ProxyAgent can proxy correctly rather than report error

**Comment by liudhzhyym** [comment] 2023-03-28 15:55
any solutions?

**Comment by coderzzp** [comment] 2023-03-30 11:27
> any solutions?

not yet

**Comment by wenerme** [comment] 2023-03-31 15:48
NextJS support proxy just like nodejs https://github.com/Yidadaa/ChatGPT-Next-Web/pull/295/files

**Comment by jernkuan** [comment] 2023-07-26 01:32
an alternative is to use global-agent and cross-fetch/polyfill

for dev env setup
run the following
` node -r global-agent/boot-strap -r cross-fetch/polyfill --no-experiemental-fetch node_modules/next/dist/bin/next dev`

Remember to setup the GLOBAL_AGENT_HTTP_PROXY etc.

**Comment by aksjer** [comment] 2023-12-21 18:25
It does not work with the next version 13 or 14 which uses undici

**Comment by padupuy** [comment] 2024-06-25 13:28
Thanks to this comment https://github.com/vercel/next.js/issues/66373#issuecomment-2174015301 I successfully setup a global proxy agent with no custom server inside the `layout.ts`


```ts filename="layout.ts"
import { ProxyAgent, setGlobalDispatcher } from "undici";

if (process.env.HTTP_PROXY) {
  const proxyAgent = new ProxyAgent(process.env.HTTP_PROXY);
  setGlobalDispatcher(proxyAgent);
}

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html >
      <body>
          {children}
      </body>
    </html>
  );
}
```

**Comment by thescientist13** [comment] 2024-08-27 22:04
I was also able to leverage **undici** + `setGlobalDispatcher` in a Next 14 app using a custom _server.js_ and it seems to be working well
```js
const { ProxyAgent, setGlobalDispatcher } = require('undici');

// ...

const { PROXY_HOST, PROXY_PORT } = process.env;
setGlobalDispatcher(new ProxyAgent(`http://${PROXY_HOST}:${PROXY_PORT}`));

const app = next({ /* ... */ });
```

**Comment by abalmus** [comment] 2024-09-19 09:53
> Thanks to this comment [#66373 (comment)](https://github.com/vercel/next.js/issues/66373#issuecomment-2174015301) I successfully setup a global proxy agent with no custom server inside the `layout.ts`
> 
> ```ts
> import { ProxyAgent, setGlobalDispatcher } from "undici";
> 
> if (process.env.HTTP_PROXY) {
>   const proxyAgent = new ProxyAgent(process.env.HTTP_PROXY);
>   setGlobalDispatcher(proxyAgent);
> }
> 
> export default async function Layout({
>   children,
> }: {
>   children: React.ReactNode;
> }) {
>   
>   return (
>     <html >
>       <body>
>           {children}
>       </body>
>     </html>
>   );
> }
> ```

Good one, I would also recommend looking at the instrumentationHook, and use instrumentation.js to set the proxy agent, instead of layout.

**Comment by ztanner** [comment] 2024-09-20 03:28
Closing as there appear to be working solutions provided above and the original issue does not provide a valid reproduction (and may be out of date as the fetch builtin is Undici which leverages dispatchers). Please feel free to create a new issue following the [bug report template](https://github.com/vercel/next.js/issues/new?assignees=&labels=bug&projects=&template=1.bug_report.yml) if you have a valid reproduction of a bug.

**Closed by ztanner** 2024-09-20 03:28 UTC
Labels: bug
