### ISSUE TITLE
next dev constantly errors when using emacs, failing to load emacs lock files

### ISSUE THREAD

**Issue by lacker** [vercel/next.js#15278] opened 2020-07-17 19:33 UTC
# Bug report

When using `next dev` with emacs, as you develop, emacs creates symbolic link files starting with `.#` as lock files. Next.js seems to attempt to load these but fails, spewing out errors constantly.

## To Reproduce

1. Run `next dev`
2. Develop your `.js` files using emacs
3. Observe errors like:

```
(node:13646) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/home/lacker/twitroid/pages/.#app.js'
(node:13646) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13646) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

## Expected behavior

I expected to not get these errors

## System information

- OS: Ubuntu 18
- Version of Next.js: 9.4.4
- Version of Node.js: 10.21.0

## Additional context

I tried adding a webpack ignore filter to ignore these files, but it did not have any effect.

**Comment by lacker** [comment] 2020-07-17 19:36
A couple other notes that might help - I saw that `create-react-app` had a similar issue recently at https://github.com/facebook/create-react-app/issues/9056 . The workaround there of putting `(setq create-lockfiles nil)` in your `.emacs` file does work to suppress the errors, but it does so by having emacs no longer create lock files, which is dangerous because then emacs and git will overwrite each others' changes without emacs noticing.

**Comment by ignaciocaamanio** [comment] 2020-08-15 18:54
I have the same problem. Maybe it's an Emacs issue and should be open in their repository? I'm learning Next and because of this I switched to VSCode.

**Comment by ignaciocaamanio** [comment] 2020-08-15 18:58
Here is some related discussion #9056

**Comment by ignaciocaamanio** [comment] 2020-08-15 19:01
This is related https://github.com/facebook/create-react-app/issues/9056

**Comment by ignaciocaamanio** [comment] 2020-08-15 19:26
Here is a solution: https://stackoverflow.com/questions/62567370/reactjs-local-server-crashes-after-editing-file-in-emacs-even-without-saving

**Comment by ignaciocaamanio** [comment] 2020-08-15 19:37
To disable lockfiles for a specific project only https://stackoverflow.com/questions/62567370/reactjs-local-server-crashes-after-editing-file-in-emacs-even-without-saving

**Comment by kjmph** [comment] 2020-10-28 06:37
I posted a comment in #8238 as well.. This is easy to reproduce via:

```shell
host:next.js kjmph$ ln -s notexists examples/basic-css/pages/testfile
host:next.js kjmph$ yarn next ./examples/basic-css/
yarn run v1.22.10
$ node --trace-deprecation packages/next/dist/bin/next ./examples/basic-css/
ready - started server on http://localhost:3000
[Error: ENOENT: no such file or directory, stat '/home/kjmph/next.js/examples/basic-css/pages/testfile'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/home/kjmph/next.js/examples/basic-css/pages/testfile'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm causing it to manifest slightly differently, yet it appears to be the same thing.

**Comment by Mstrodl** [comment] 2020-11-03 22:45
This is still an issue, disabling lockfiles for emacs is _not_ a good fix for this at all.

**Comment by dmlap** [comment] 2020-12-22 16:33
I spent some time digging into this myself. The unhandled promise rejection looks to be coming from this issue: https://github.com/paulmillr/chokidar/issues/955

**Comment by dmlap** [comment] 2020-12-22 16:51
As an alternate workaround to disabling emacs lockfiles, applying [this patch](https://github.com/paulmillr/chokidar/pull/1010/files) directly to `chokidar/lib/nodejs-handler.js` solved the problem for me.

**Comment by lfender6445** [comment] 2020-12-26 17:34
I have a fix for this staged here 

https://github.com/vercel/next.js/pull/20497

if you are using a custom webpack configuration, you can extend the existing config until the fix is released, maybe something like this

```js
config.watchOptions = config.watchOptions.concat('**/.#*')
```

**Closed** 2020-12-29 16:12 UTC
Labels: kind: bug

**Comment by ZelphirKaltstahl** [comment] 2021-09-21 16:34
Voting to reopen this issue, as it is _still_ an issue.
Why did the bot close this ongoing issue?

**Comment by balazsorban44** [comment] 2022-01-27 18:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
