### ISSUE TITLE
"TypeError: fetch failed" is an incomplete error: `fetch` in Server Component, if throws and isn't caught, loses info

### ISSUE THREAD

**Issue by tomsseisums** [vercel/next.js#49896] opened 2023-05-17 07:19 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.4.3-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/next-js-server-components-fetch-incomplete-error-if-uncaught-o09yqm

### To Reproduce

In server component, try to load data from an non-existent URL without try/catch.
```
await fetch('http://127.0.0.1:1337/non-existent')
```

### Describe the Bug

The terminal logs just:
```
TypeError: fetch failed
```

And with `next dev`, it will be surfaced to frontend with just the same:
```
Unhandled runtime error
TypeError: fetch failed
```

If I include my own `error.tsx` and try to destructure the error into `const { name, message, trace, cause, ...rest } = error`, it will still be incomplete, having only `name` and `message` (and `digest` in `...rest`), and there the `name` even will be dropped from `TypeError` to just `Error`.

Related: https://github.com/vercel/next.js/issues/44062, but there the focus isn't on error being incomplete, rather that it happens at all.

The issue seems that it only surfaces first line for low-level errors (ECONNREFUSED etc.). Which is why the #44062 seems like a mysterious thing, albeit if you look inside, you'd see that it's the `localhost` resolving to `::1` IPv6 issue at most cases.

### Expected Behavior

Given I `try/catch` and `console.error('FULL ERROR', e)` the error and get this out:
```
FULL ERROR:  TypeError: fetch failed
    at Object.fetch (/project/sandbox/node_modules/next/dist/compiled/undici/index.js:1:26669)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:1337
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 1337
  }
}
```

1. I would expect this to be shown by default in terminal logs. Without me having to try/catch + console.error to see the details.
2. I would expect the `error.tsx` to also have the full info available, as it is for any other (although with this I'm not sure) uncaught exception in Server Component.
3. I would expect the Error surfaced to `error.tsx` not to lose it's `name` (`error.tsx` shows `Error` instead of `TypeError`).

**Comment by tomsseisums** [comment] 2023-05-17 07:55
This seems to have been introduces with v13.2 with the new `error - <error>` output, in v13.1 without `error - <error>` the error is displayed in full in server terminal. `error.tsx` still receives incomplete info, though.

Here is sandbox with 13.1, but otherwise same environment: https://codesandbox.io/p/sandbox/next-js-server-components-fetch-complete-error-if-uncaught-13-1-yvot4e

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.1.6
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

**Comment by Athrun-Judah** [comment] 2023-05-18 07:08
I had the same problem in the server component.

**Comment by maciejadamski89** [comment] 2023-05-24 12:57
Same for me - can't fetch from `server component`. From `client component` there are no any problems.
Change request `url` from `localhost:8000` to `127.0.0.1:8000` solved my problem.

**Comment by MoncefDeveloper** [comment] 2023-05-25 11:33
same problem
Changing 'localhost' to '127.0.0.1',  still causes the same problem.
add dns.setDefaultResultOrder('ipv4first') to my app, still the same problem.

**Comment by gempi** [comment] 2023-05-25 14:37
@MoncefDeveloper have you tried to update to `v13.4.4-canary.9` according to https://github.com/vercel/next.js/issues/50298#issuecomment-1562037690?

**Comment by MoncefDeveloper** [comment] 2023-05-25 23:37
> @MoncefDeveloper have you tried to update to `v13.4.4-canary.9` according to [#50298 (comment)](https://github.com/vercel/next.js/issues/50298#issuecomment-1562037690)?

thanks Gempi. I updated my app to 13.4.4 but still faced the same error. 
after that, I tried to switch the node to 16! still showing me the same error
I tried almost every solution :') 

```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3000
  }
}
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3000
  }
}
/item/....
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3000
  }
}
TypeError: fetch failed
    ....
    ....
    ....
```

**Comment by Gr33nLight** [comment] 2023-06-08 11:22
> I tried almost every solution :')

Heyyyyyyy did you manage to find a solution to this?

**Comment by myzsqn** [comment] 2023-06-12 00:50
> 

I fixed this issue by ensuring that my endpoint URL was not involved in a redirect.

My example:

website.io was redirecting to www.website.io

Thus removing the Content-Length

#https://github.com/nodejs/undici/issues/2046#issuecomment-1497533376

Hope it helps

**Comment by hrdwdmrbl** [comment] 2023-07-10 22:32
Just in case people are missing it, the original author's "Expected Behavior" section gives a good workaround: try/catch your fetches for now.

**Comment by Sumitmaithani** [comment] 2023-07-23 15:50
I also getting this error on next@13.4.12 everything works fine on locally but getting this error on deployment in vercel.

Want to see my code details [https://github.com/Sumitmaithani/competency-passbook](https://github.com/Sumitmaithani/competency-passbook)
```
Error loading courses:  TypeError: fetch failed
--
20:25:18.646 | at Object.fetch (node:internal/deps/undici/undici:11457:11)
20:25:18.646 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
20:25:18.647 | cause: Error: connect ECONNREFUSED 127.0.0.1:3000
20:25:18.647 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
20:25:18.647 | at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
20:25:18.648 | errno: -111,
20:25:18.649 | code: 'ECONNREFUSED',
20:25:18.649 | syscall: 'connect',
20:25:18.657 | address: '127.0.0.1',
20:25:18.657 | port: 3000
20:25:18.657 | }
```

**Comment by anthonytison** [comment] 2023-07-23 16:11
Hey,
I'm not using the appDir functionality yet so for fixing that issue i had to modify the `next.config.js` by 

* turning off the appDir
 ```json
 experimental: {
    appDir: false
  },
 ```
* forcing ip4 on the server
 ```javascript
 const dns = require('dns');
dns.setDefaultResultOrder("ipv4first");
 ```
I hope it will give you some ideas if it doesn't help you.

**Comment by MrZhouZh** [comment] 2023-08-02 14:51
Same error! on next@13.4.12 and deployment in vercel

```sh
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: connect ECONNREFUSED ::1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 3000
  }
}

Error occurred prerendering page "/todos". Read more: https://nextjs.org/docs/messages/prerender-error
```

**Comment by em1l1000** [comment] 2023-08-09 13:56
I have this issue in next.js version 13.4.13 as well (node 20.4.9). Is there a fix in the pipeline?

**Comment by DevEmmy** [comment] 2023-08-23 08:28
Currently, I'm experiencing this issue on my linux duing development. 
Is there any solution yet?

**Comment by renanrodrigueszup** [comment] 2023-08-23 12:41
same here

**Comment by AndyLeezard** [comment] 2023-08-31 23:52
I am having this issue as well, with `errorno: -4078` and `code: 'ECONNREFUSED'` starting with `TypeError: fetch failed...`.
Node version: 18.17.1 (LTS)
NextJS version: 13.4.19 (app router)
Typescript version: 5.2.2

It looks like downgrading to `next": "13.4.7` or migrating all fetch requests to `axios` solves this issue as a workaround.

However I wonder why this issue persists because this should be fixed by now with the current version of Next, as [kaloyanBozhkov](https://github.com/kaloyanBozhkov) commented, this issue had been documented in #48744 , and a PR https://github.com/vercel/next.js/pull/53843 was created and merged.

In my case, it could be due to the middleware from `next-auth` that appears to use `undici`.
(Knowing that all my fetch requests are already wrapped inside a try catch block.)

For what it's worth, I'm sharing what I've been going through:

The deployed web app seems to be running fine but in the dev env, I constantly encounter this server crash error when HMR occurs (on code change), about every 20 minutes or so.

These are all kinds of attempts I made so far to solve this issue.

- Tried removing all cache in .next folder and re-run; no luck.
- Explicitly specified the Hostname and the port when running the dev server: `npx next dev -H 127.0.0.1 -p 3000`  or `npx next dev -H 0.0.0.0 -p 3000`; no luck.
- Downgrade Node to 16.x.x; no luck. Reverted.
- Wrap all my `fetch` requests with try catch block; no luck.
- Use '127.0.0.1:8000' instead of 'http://localhost:8000' as part of my api endpoint of local backend server; no luck.


```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeRequest (D:\dev\my-project\my-project-nextjs\node_modules\.pnpm\next@13.4.19_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\server-ipc\invoke-request.js:17:12)
    at async invokeRender (D:\dev\my-project\my-project-nextjs\node_modules\.pnpm\next@13.4.19_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:254:29)
    at async handleRequest (D:\dev\my-project\my-project-nextjs\node_modules\.pnpm\next@13.4.19_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:447:24)
    at async requestHandler (D:\dev\my-project\my-project-nextjs\node_modules\.pnpm\next@13.4.19_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:464:13)
react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\start-server.js:117:13) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:58339
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 58339
  }
```

**Comment by Elvincth** [comment] 2023-09-08 20:25
Same random error appear using app dir with next.js v13.4.19
<img width="1377" alt="image" src="https://github.com/vercel/next.js/assets/6602723/b83c7027-2b32-47a5-b7b6-d567169d4145">

**Comment by TheKenoCode** [comment] 2023-09-11 02:39
> Same random error appear using app dir with next.js v13.4.19 <img alt="image" width="1377" src="https://user-images.githubusercontent.com/6602723/266723041-b83c7027-2b32-47a5-b7b6-d567169d4145.png">

same here >:(
![2023-09-10 19_38_30-](https://github.com/vercel/next.js/assets/67208480/b5590f1d-0057-4c78-b459-8a49ef290cf5)

**Comment by adanperez** [comment] 2023-09-11 02:51
In my case I was using fetch to call a service with a bad/unkown certificate.  I had to capture the fetch error and log it out to see what the actual issue was.  Worth looking at `NODE_TLS_REJECT_UNAUTHORIZED=0` if doing local development.

**Comment by karlhorky** [comment] 2023-09-11 16:00
Seems similar to what's happening over here:

- #54961

**Comment by karlhorky** [comment] 2023-09-11 16:19
For all the people who have been reporting that it happens with Next.js v13.4.19, please upgrade to the latest canary on [the Releases page](https://github.com/vercel/next.js/releases) (currently `13.4.20-canary.23`) and try again - this will be helpful to see if the problem still occurs

(I am also experiencing this issue on the latest canary personally, but would be good to get some other data points)

**Comment by LiorDueto** [comment] 2023-09-11 17:43
> I am having this issue as well, with `errorno: -4078` and `code: 'ECONNREFUSED'` starting with `TypeError: fetch failed...`, always followed by `The server is running out of memory, restarting to free up memory`.
> 
> 
> (Every time this error occurs, I see different value on Port:xxx but the rest is always the same with node:internal/deps/undici...
> 
> Node version tested (all having same issues): 16.20.2, 18.17.1, 20.5.1 NextJS version tested (all having same issues): 13.4.6, 13.4.19 Package Manager: pnpm 8.7.1 Typescript version: 5.2.2
> 
>... 
> The deployed web app seems to be running fine but in the dev env, I constantly encounter this server crash error when HMR occurs (on code change), about every 20 minutes or so.
> 
> These are all kinds of attempts I made so far to solve this issue.
> 
> * Tried removing all cache in .next folder and re-run; no luck.
> * Explicitly specified the Hostname and the port when running the dev server: `npx next dev -H 127.0.0.1 -p 3000`  or `npx next dev -H 0.0.0.0 -p 3000`; no luck.
> * Use '127.0.0.1:8000' instead of 'http://localhost:8000' as part of my api endpoint of local backend server; no luck.
> 
> Edited: The error message is a bit different in Next 13.4.6 or lower
> 

We also encountered similar 'out of memory', 'fetch' errors and eventual crashes (13.4.19).
[Disabling image optimization](https://nextjs.org/docs/app/api-reference/components/image#unoptimized) solved this for us and server memory in production has become more stable.
Just add `images: { unoptimized: true}` to next configuration

**Comment by parthy007** [comment] 2023-09-13 20:04
Gettiing this below error when trying to build my nextjs project, i tried chaging the localhost to 127.0.0.1 in the env but it's not working, It would be great if anybody can help me get  through this error.

My Versions: 
next - 13.4.19
node - 18.17.1

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3000
  }
}

Error occurred prerendering page "/blog". Read more: https://nextjs.org/docs/messages/prerender-error    
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
- info Generating static pages (13/13)

> Export encountered errors on following paths:
        /blog/page: /blog

**Comment by Zakisb** [comment] 2023-09-17 09:38
Having the same issue too !

**Comment by karlhorky** [comment] 2023-09-19 13:55
Check out [my comment](https://github.com/vercel/next.js/issues/54961#issuecomment-1725629311) from the other issue (54961):

> I upgraded to [`next@13.4.20-canary.35`](https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.35) and we have also not experienced the `fetch` failures since then... 👀 🤔 
>
> I will keep an eye on this, but maybe this has been fixed

Try upgrading to the latest canary and see if it helps your project 👍

**Comment by timomedia** [comment] 2023-09-22 01:28
> Try upgrading to the latest canary and see if it helps your project

I tried updating to version 13.5.2 but still get the same error. It will randomly display a few endpoints

**Comment by MAhmedSid** [comment] 2023-10-08 16:40
I solved this by removing all redirect domains in Vercel, and by adding "www" in the fetch request url.
https://github.com/nodejs/undici/issues/2046

**Comment by AatifxShaikh** [comment] 2023-10-15 09:00
```TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3000
  }
}
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3000
  }
}
 ```
facing the same error as well in my the login page seems to be working fine but the server component provides the
Application error: a server-side exception has occurred (see the server logs for more information). error.

**Comment by Rivalakmalll** [comment] 2023-10-26 12:33
have same issue with this eror output

<html>
<body>


TypeError: fetch failed
--
19:15:38.229 | at Object.fetch (node:internal/deps/undici/undici:11576:11)
19:15:38.229 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
19:15:38.230 | cause: Error: connect ECONNREFUSED 127.0.0.1:3000
19:15:38.230 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
19:15:38.230 | at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
19:15:38.230 | errno: -111,
19:15:38.230 | code: 'ECONNREFUSED',
19:15:38.231 | syscall: 'connect',
19:15:38.231 | address: '127.0.0.1',
19:15:38.231 | port: 3000
19:15:38.231 | }
19:15:38.231 | }
19:15:38.232 | TypeError: Cannot read properties of undefined (reading 'json')
19:15:38.233 | at profileFetcher (/vercel/path0/.next/server/app/open-source/page.js:411:41)
19:15:38.233 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
19:15:38.233 | at async OpenSourcePage (/vercel/path0/.next/server/app/open-source/page.js:472:21)
19:15:38.244 |  
19:15:38.244 | Error occurred prerendering page "/open-source". Read more: https://nextjs.org/docs/messages/prerender-error
19:15:38.244 | TypeError: Cannot read properties of undefined (reading 'json')
19:15:38.245 | at profileFetcher (/vercel/path0/.next/server/app/open-source/page.js:411:41)
19:15:38.245 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
19:15:38.245 | at async OpenSourcePage (/vercel/path0/.next/server/app/open-source/page.js:472:21)
19:15:38.285 | TypeError: fetch failed
19:15:38.290 | at Object.fetch (node:internal/deps/undici/undici:11576:11)
19:15:38.291 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
19:15:38.291 | cause: Error: connect ECONNREFUSED 127.0.0.1:3000
19:15:38.291 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
19:15:38.291 | at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
19:15:38.291 | errno: -111,
19:15:38.291 | code: 'ECONNREFUSED',
19:15:38.291 | syscall: 'connect',
19:15:38.291 | address: '127.0.0.1',
19:15:38.291 | port: 3000
19:15:38.291 | }
19:15:38.291 | }
19:15:38.296 |  
19:15:38.296 | Error occurred prerendering page "/spotify". Read more: https://nextjs.org/docs/messages/prerender-error
19:15:38.296 | TypeError: fetch failed
19:15:38.296 | at Object.fetch (node:internal/deps/undici/undici:11576:11)
19:15:38.296 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
19:15:38.297 | - info Generating static pages (13/13)
19:15:38.302 |  
19:15:38.303 | > Export encountered errors on following paths:
19:15:38.303 | /open-source/page: /open-source
19:15:38.303 | /spotify/page: /spotify
19:15:38.363 | error Command failed with exit code 1.
19:15:38.365 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
19:15:38.386 | Error: Command "yarn run build" exited with 1


</body>
</html>

**Comment by eademir** [comment] 2023-10-27 01:01
async function getData() {
  const res = await fetch('https://localhost:8080/api/v1/posts')
  // The return value is *not* serialized
  // You can return Date, Map, Set, etc.
 
  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error('Failed to fetch data')
  }
 
  return res.json()
}
 
export default async function Page() {
  const data = await getData()
 
  return <main>...</main>
}

I've got this from [here](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating) yet getting the same error.

**Comment by MAhmedSid** [comment] 2023-10-27 03:43
This error is generating, because your are trying to fetch fr9m local api in server component. Because of app is not completely build the server components are not able to find it. This error usually occurs at build time.

SOLUTION:  The solution is tha don't call local api inside server component instead of direct fetch data from resource url in the server component.

**Comment by eademir** [comment] 2023-11-04 01:54
> This error is generating, because you are trying to fetch from local api in server component. Because of app is not completely build, the server components are not able to find it. This error usually occurs at build time.
> 
> SOLUTION: The solution is tha don't call local api inside server component instead of direct fetch data from resource url in the server component.

I guess, you are wrong. Do you have any example?

I tried localhost:8080 and localhost (pass_proxy to :8080 via nginx) no luck. but if I send a request via browser or postman or terminal I can get the json I need. This is only occurs when I use `npm run build` but there is no any problem with `npm run dev`, too. By the way, the app is completely built and running in a container with docker compose.

**Comment by MAhmedSid** [comment] 2023-11-04 02:00
Now It is officially documented in a Next Js docs that it is better to fetch data from direct source instead of using local api route in Server components. Because at build time Server components will not able tofind those routes which are not still built yet. And you can refer the examples there.

**Comment by ddikodroid** [comment] 2023-11-09 03:46
> Now It is officially documented in a Next Js docs that it is better to fetch data from direct source instead of using local api route in Server components. Because at build time Server components will not able tofind those routes which are not still built yet. And you can refer the examples there.
> 
> It works in dev env because dev server don't create pre rendered static pages.

could you share the link that point to the docs?

**Comment by AatifxShaikh** [comment] 2023-11-09 04:51
> have same issue with this eror output
> 
> ## TypeError: fetch failed
> 19:15:38.229 | at Object.fetch (node:internal/deps/undici/undici:11576:11) 19:15:38.229 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { 19:15:38.230 | cause: Error: connect ECONNREFUSED 127.0.0.1:3000 19:15:38.230 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) 19:15:38.230 | at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) { 19:15:38.230 | errno: -111, 19:15:38.230 | code: 'ECONNREFUSED', 19:15:38.231 | syscall: 'connect', 19:15:38.231 | address: '127.0.0.1', 19:15:38.231 | port: 3000 19:15:38.231 | } 19:15:38.231 | } 19:15:38.232 | TypeError: Cannot read properties of undefined (reading 'json') 19:15:38.233 | at profileFetcher (/vercel/path0/.next/server/app/open-source/page.js:411:41) 19:15:38.233 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 19:15:38.233 | at async OpenSourcePage (/vercel/path0/.next/server/app/open-source/page.js:472:21) 19:15:38.244 |   19:15:38.244 | Error occurred prerendering page "/open-source". Read more: https://nextjs.org/docs/messages/prerender-error 19:15:38.244 | TypeError: Cannot read properties of undefined (reading 'json') 19:15:38.245 | at profileFetcher (/vercel/path0/.next/server/app/open-source/page.js:411:41) 19:15:38.245 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 19:15:38.245 | at async OpenSourcePage (/vercel/path0/.next/server/app/open-source/page.js:472:21) 19:15:38.285 | TypeError: fetch failed 19:15:38.290 | at Object.fetch (node:internal/deps/undici/undici:11576:11) 19:15:38.291 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { 19:15:38.291 | cause: Error: connect ECONNREFUSED 127.0.0.1:3000 19:15:38.291 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) 19:15:38.291 | at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) { 19:15:38.291 | errno: -111, 19:15:38.291 | code: 'ECONNREFUSED', 19:15:38.291 | syscall: 'connect', 19:15:38.291 | address: '127.0.0.1', 19:15:38.291 | port: 3000 19:15:38.291 | } 19:15:38.291 | } 19:15:38.296 |   19:15:38.296 | Error occurred prerendering page "/spotify". Read more: https://nextjs.org/docs/messages/prerender-error 19:15:38.296 | TypeError: fetch failed 19:15:38.296 | at Object.fetch (node:internal/deps/undici/undici:11576:11) 19:15:38.296 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 19:15:38.297 | - info Generating static pages (13/13) 19:15:38.302 |   19:15:38.303 | > Export encountered errors on following paths: 19:15:38.303 | /open-source/page: /open-source 19:15:38.303 | /spotify/page: /spotify 19:15:38.363 | error Command failed with exit code 1. 19:15:38.365 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 19:15:38.386 | Error: Command "yarn run build" exited with 1

you have to update the fetch link to the deployed link you will get after deploying the application, that is how i got my application running

**Comment by MAhmedSid** [comment] 2023-11-09 06:25
> > Now It is officially documented in a Next Js docs that it is better to fetch data from direct source instead of using local api route in Server components. Because at build time Server components will not able tofind those routes which are not still built yet. And you can refer the examples there.
> > 
> > It works in dev env because dev server don't create pre rendered static pages.
> 
> could you share the link that point to the docs?

Sure, https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating

![Screenshot_20231109-112434.jpg](https://github.com/vercel/next.js/assets/110467743/774cd1d3-38c6-43e1-aaf1-136303c31b30)

**Comment by aswnss-m** [comment] 2023-12-29 21:04
I encountered a similar problem , mine arise when the .env varibales was not recognized or unset. The problem got resolved when .env was fixed

**Comment by huozhi** [comment] 2024-01-09 22:36
I got a [PR](https://github.com/vercel/next.js/pull/60274) up here to fix this 🙏

**Closed** 2024-01-09 22:38 UTC
Labels: template: bug, area: app
