### ISSUE TITLE
Next.js 13: Build failure when enabling appDir and using Yarn PnP

### ISSUE THREAD

**Issue by shun-shobon** [vercel/next.js#42427] opened 2022-11-03 17:31 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
    Binaries:
      Node: 18.12.0
      npm: 8.19.2
      Yarn: 3.2.4
      pnpm: N/A
    Relevant packages:
      next: 13.0.2-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

When using Yarn PnP to manage packages, running `next bulid` with appDir enabled will fail to build.
The build log is:
```
warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

warn  - `enableUndici` option is unnecessary in Node.js v18.0.0 or greater.

> Build error occurred
Error: EROFS: read-only filesystem, open '/node_modules/next/dist/server/initialize-require-hook.js'
    at makeError$1 (/Users/shun_shobon/tmp/my-app/.pnp.cjs:958:24)
    at EROFS (/Users/shun_shobon/tmp/my-app/.pnp.cjs:985:10)
    at ZipFS.prepareWriteFile (/Users/shun_shobon/tmp/my-app/.pnp.cjs:2820:13)
    at ZipFS.writeFilePromise (/Users/shun_shobon/tmp/my-app/.pnp.cjs:2791:55)
    at /Users/shun_shobon/tmp/my-app/.pnp.cjs:3912:26
    at /Users/shun_shobon/tmp/my-app/.pnp.cjs:4136:81
    at ZipOpenFS.getZipPromise (/Users/shun_shobon/tmp/my-app/.pnp.cjs:4243:22)
    at ZipOpenFS.makeCallPromise (/Users/shun_shobon/tmp/my-app/.pnp.cjs:4136:23)
    at ZipOpenFS.writeFilePromise (/Users/shun_shobon/tmp/my-app/.pnp.cjs:3909:23)
    at VirtualFS.writeFilePromise (/Users/shun_shobon/tmp/my-app/.pnp.cjs:3219:24) {
  code: 'EROFS'
}
```
Looking at the error log, it appears that the attempt to write in `next/dist/server/initialize-require-hook.js` is failing:
https://github.com/vercel/next.js/blob/ef73798e4557a8f203f814afe0908e041b2792b2/packages/next/build/index.ts#L317-L324

### Expected Behavior

No error logs are displayed and the build succeeds.

### Link to reproduction

https://github.com/shun-shobon/nextjs-13-yarn-berry-build-reproduction

### To Reproduce

- clone this repo
- run `yarn` to install dependencies
- run `yarn build`
- an error log is output and the build fails

<sub>[NEXT-1378](https://linear.app/vercel/issue/NEXT-1378/nextjs-13-build-failure-when-enabling-appdir-and-using-yarn-pnp)</sub>

**Comment by travigd** [comment] 2022-11-03 20:28
I just ran into this. A temporary workaround is to `yarn unplug next`.

**Comment by dengoyoon** [comment] 2022-11-09 08:15
Can you check the 'experimental' of next.config.js? 
I've had the same problem.
Clearing 'appDir : true' resolved the issue 🙂
```
experimental: {
    // appDir: true,
},
```

**Comment by nastynaz** [comment] 2022-12-11 10:04
I spent hours trying to figure this out. Bump.

**Comment by Revolt9k** [comment] 2022-12-13 08:20
Same problem

**Comment by madjam002** [comment] 2022-12-16 15:53
This is also a problem when running ‘next build’ where node_modules is on a read only file system as is the case with some build systems.

**Comment by cyrilwanner** [comment] 2023-01-16 08:00
We are also facing this issue with Bazel (rules_js & pnpm) when trying to enable the appDir feature.
Modifying files within node_modules might work for simple setups, but can cause a lot of issues with more complex and restrictive build systems where node_modules is on a read only file system (for example to avoid any side effects when sharing dependencies between build agents and for guaranteeing hermetic builds).

It looks like this was introduced in #41687

@huozhi @ijjk would it be possible to maybe move this file to the `.next` output folder or avoid writing it in node_modules in another way, e.g. by checking if the appDir feature is enabled differently?
I am also happy to contribute if there is a common agreement on how this should be fixed.

**Comment by samwightt** [comment] 2023-01-18 20:25
Bump, this really needs attention. Huge blocker for anyone using yarn 2.

**Comment by ranisalt** [comment] 2023-02-18 01:55
Not a good idea for a dependency to modify its own source code when ran... Just generate this file elsewhere

**Comment by power-f-GOD** [comment] 2023-03-08 15:34
I just faced this issue with `pnpm` as well.😕 Any concrete solutions yet?

**Comment by codebycarlos** [comment] 2023-03-09 14:09
Just came across this as well

**Comment by faeb187** [comment] 2023-03-22 02:38
yarn 3.4.1 @samwightt not only v2 affected.
node LTS 18.14.1
next@latest same as with next@v13.2.5-canary.12 (obviously, PNP both default)

```typescript
Build error occurred
Error: EROFS: read-only filesystem, open '/node_modules/next/dist/server/initialize-require-hook.js'
```

**Workaround** (opt-out Yarn PNP and use node_modules again):
```bash
# prerelease use @v13.2.5-canary.12
npx create-next-app@latest app \
--ts \
--eslint \
--tailwind \
--experimental-app \
--src-dir \
--import-alias "@/*"

# switch to created app/ directory
cd app

# adds `nodeLinker:node_modules` to `.yarnrc.yml` and runs `yarn install` in one command
yarn config set nodeLinker node_modules
```

Output:
`➤ YN0000: Successfully set nodeLinker to 'node-modules'`

**Comment by bryanjtc** [comment] 2023-04-16 22:05
Unplugging next in a project using module and module resolution node 16 throws this error. My project has type module in the package.json
```
Type error: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("../../../app/layout.js")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.
```

**Comment by oxc** [comment] 2023-04-30 12:48
> Trying to use the workaround by unplugging next in a project using module and module resolution node 16 throws this error. 

@bryanjtc, this is unrelated ty Yarn PnP. I've reported this issue with some background and a workaround (enable `typedRoutes` feature) in https://github.com/vercel/next.js/issues/49004

**Comment by yannbolliger** [comment] 2023-05-11 09:00
Looks like this fixed for us (with @cyrilwanner) Bazel with rules_js & pnpm, from `next@13.4.1`. 👍

**Comment by huozhi** [comment] 2023-07-24 20:58
Tested the reproduction attached in the description with latest nextjs, it works well for me, will close this issue now.

**Closed by huozhi** 2023-07-24 20:58 UTC
Labels: template: bug, area: package manager, linear: next

**Comment by krisgardiner** [comment] 2023-07-28 18:18
The issue for me was `getInitialProps`. I had done it like `Home.getInitialProps = async () => {}` but it should be exported on the module level like so:
```
export default Home() {
}
export async function getInitialProps () {
}
```
