### ISSUE TITLE
Cannot import TypeScript types that have been re-exported

### ISSUE THREAD

**Issue by jagaapple** [vercel/next.js#7882] opened 2019-07-10 18:04 UTC
# Bug report

## Describe the bug

As [I wrote an issue in @zeit/next-typescript some months ago](https://github.com/zeit/next-plugins/issues/306), Babel does not support to import types or interfaces from re-export files such as `index.ts` .
On large project, developers create index.js (or index.ts ) to encapsulate the API calls from the web app into a single folder.

@zeit/next-typescript throws warnings when importing re-exported types, but Next.js 9 (using built-in TypeScript transpile system) throws errors in that case. So we cannot develop using re-export files.

## To Reproduce

```ts
// packages/package-1.ts
export type TypeA = {};

// packages/index.ts
export { TypeA } from "./package-1";

// main.ts
import { TypeA } from "./packages";
```

Next.js throws errors like the following if the above code is contained in some pages.

```
Attempted import error: 'TypeA' is not exported from './package-1'.
```

## Expected behavior

Do not raise any errors and warnings.

## Additional context

Babel v7 supports to transpile TypeScript files but it is only to remove types from TypeScript files. At this time, the target of import from intersection (index) files will be removed.

```ts
// After transpile by Babel...
// ---
// packages/package-1.ts
// export type TypeA = {}; // REMOVED!

// packages/index.ts
export { TypeA } from "./package-1"; // NOT FOUND!
```

To solve this issue at its foundation, Babel should support re-export files and we should wait to do. However I think that to filter and ignore these errors using regular expressions makes to solve.

**Comment by kachkaev** [comment] 2019-07-10 18:37
This is the result of having `isolatedModules` in the autogenerated `tsconfig.json` and we can't opt-out of that.

I upgraded one rather small app from Next 8 + [`@zeit/next-typescript`](https://github.com/zeit/next-plugins/tree/master/packages/next-typescript) to Next 9 and it was quite painful to refactor all the re-exports. The resulting working code pretty ugly too. Can't imagine upgrading a proper app that has hundreds of `export { ... } from "./path/to/file"` 😱

**Comment by Timer** [comment] 2019-07-10 18:53
This is a Babel bug and I can see how this is frustrating -- we'll want to figure something out for this.

**Comment by jeremy-coleman** [comment] 2019-07-11 04:17
install @codemod/cli and babel-plugin-codemod-named-export-declarations and run this as an npm script
```js
    "trymod": "./node_modules/.bin/codemod -p babel-plugin-codemod-named-export-declarations src/client/**/*.ts"
```

**Comment by martpie** [comment] 2019-07-11 12:15
> This is a Babel bug

Is there a link to this upstream bug?

**Comment by martpie** [comment] 2019-07-11 13:10
To fix it, just replace `export { ... } from "./path/to/file"` with the `export * from "./path/to/file"`

https://github.com/babel/babel/issues/8361#issuecomment-428766985

**Comment by jeremy-coleman** [comment] 2019-07-12 00:02
i put an example repo up here https://github.com/jeremy-coleman/next-tsc-proposal
and a corresponding issue here https://github.com/zeit/next.js/issues/7908

**Comment by cyrus-za** [comment] 2020-02-21 07:45
TS 3.8 might help with this isolatedModules issue. 
https://devblogs.microsoft.com/typescript/announcing-typescript-3-8/#type-only-imports-exports

**Comment by oste** [comment] 2020-03-29 04:06
This is a show stopper for my Next project that uses react native web. I am using TS 3.8.3.

**Comment by timneutkens** [comment] 2020-03-30 08:53
@oste TypeScript added `import type` support for this case as https://github.com/zeit/next.js/issues/7882#issuecomment-589537697 provided.

**Comment by martpie** [comment] 2020-03-30 09:22
Does Babel TS preset support this syntax yet?

**Comment by timneutkens** [comment] 2020-03-30 09:35
As far as I'm aware it does

**Comment by jagaapple** [comment] 2020-04-01 22:49
Babel 7.9 and Prettier 2.0 supports TypeScript 3.8.
Everything will be all right after Next use them.

**Comment by bopfer** [comment] 2020-05-31 14:55
Anyone know if there are plans to upgrade Babel to at least 7.9?  I searched around, but didn't see any issues or PRs.

I really need it because my monorepo packages use "import type" heavily and right now I can't not import the files I need into my Next app.

**Comment by bopfer** [comment] 2020-05-31 15:28
Found a solution for now. Using [next-transpile-modules](https://github.com/martpie/next-transpile-modules) allows me to import from my monorepo packages.

**Comment by Timer** [comment] 2020-06-04 16:10
Example landing in https://github.com/vercel/next.js/pull/13746 which will close this!

**Closed** 2020-06-04 16:25 UTC
Labels: type: example

**Comment by adamsoffer** [comment] 2020-06-19 16:35
Hey guys - heads up just tried deploying the `with-typescript-types` example and still getting the `'=' expected.` error.

**Comment by adamsoffer** [comment] 2020-06-19 16:35
cc @Timer

**Comment by balazsorban44** [comment] 2022-01-29 04:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
