### ISSUE TITLE
Doesn't work with new TypeScript 4.3 syntax

### ISSUE THREAD

**Issue by adriankwiat** [vercel/next.js#25942] opened 2021-06-09 14:20 UTC
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

16.3.0

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying your application?

in development, using custom Express server

### Describe the Bug

Using new TypeScript 4.3  `override` syntax (https://devblogs.microsoft.com/typescript/announcing-typescript-4-3/#override) causes error during compilation:
![image](https://user-images.githubusercontent.com/36125672/121371468-dcd3fb00-c93d-11eb-820a-729ac3c2ca4d.png)

In package.json I have installed latest version of TypeScript (4.3.2)

### Expected Behavior

Code doesn't make any error.

### To Reproduce

Write code using `override` and run/compile.

**Comment by rokinsky** [comment] 2021-06-16 12:45
This syntax still doesn't work with next 11.0.0

**Comment by KeithYeh** [comment] 2021-06-22 07:20
Next.js depends on `@babel/core@7.12.10` for now.
TypeScript 4.3 syntax has supported in`@babel/core@7.14.0`
See https://babeljs.io/blog/2021/04/29/7.14.0

Try to update the version of `@babel/core` should solve this issue.

**Comment by SagnikPradhan** [comment] 2021-06-23 17:16
When is this getting fixed? Not sure how would I update `@babel/runtime` without touching NEXT.js codebase.

**Comment by strothj** [comment] 2021-08-11 14:29
> When is this getting fixed?
> 
> ~Not sure how would I update `@babel/runtime` without touching NEXT.js codebase.~
> Seems like [updating it across the codebase](https://yarnpkg.com/configuration/manifest#resolutions) to 7.14.6 too makes no difference.

I believe this is because `@babel/preset-typescript` is compiled into a bundle and included with Next. The bundled version would need to be bumped.

**Comment by rokinsky** [comment] 2021-09-03 20:00
Finally, this works correctly with `"next": "^11.1.2"` version!

**Comment by ijjk** [comment] 2021-09-03 20:03
Closing as this should be resolved per above comment

**Closed by ijjk** 2021-09-03 20:03 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 21:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
