### ISSUE TITLE
When rewrites are found in next.config chunk hashes are different on different machines

### ISSUE THREAD

**Issue by davscro** [vercel/next.js#23686] opened 2021-04-04 20:35 UTC
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

15.13.0

### What browser are you using?

-

### What operating system are you using?

macOs, Windows, Docker

### How are you deploying your application?

Other

### Describe the Bug

After upgrading Next.js from 10.0.5 to all newer versions of Next, chunk hashes are different between different machines. We found in newer versions (latest 10.1.3 incl. ) if you have any rewrites defined in next.config, chunk hashes will be different on different servers. 

### Expected Behavior

Chunk hashes should stay the same on different servers no matter of rewrites defined in next.config file.

### To Reproduce

1. `yarn create next-app --example with-docker nextjs-docker`
2. Create simple next.config.js file with content
```
module.exports = {
    future: {
        webpack5: true,
    },

    async rewrites() {
        return [
            {source: '/', destination: '/index'},
        ];
    }}
```
3. `docker build . -t nextjs-docker`
4. `docker run -p 3000:3000 nextjs-docker`
_Note: If step 4. is failing because of PORT missing issue, you should append `ENV PORT 3000` just before last line in Dockerfile_

Local build ->
<img width="442" alt="Screenshot 2021-04-04 at 22 21 37" src="https://user-images.githubusercontent.com/1383250/113520585-55ac8480-9594-11eb-98ff-f766b31f968c.png">

Docker build->
<img width="410" alt="Screenshot 2021-04-04 at 22 22 00" src="https://user-images.githubusercontent.com/1383250/113520586-58a77500-9594-11eb-829d-30b5cb61d5f0.png">

If you comment out rewrite line as follow
```
module.exports = {
    future: {
        webpack5: true,
    },

    async rewrites() {
        return [
            // {source: '/', destination: '/index'},
        ];
    }
};
```
And then do `yarn build` (please make sure to do `rm -rf .next` before)  you should endup with correct (same) chunkhasshes btw local and docker. Same happens btw different servers.
Local build ->
<img width="490" alt="Screenshot 2021-04-04 at 22 28 30" src="https://user-images.githubusercontent.com/1383250/113520795-e9328500-9595-11eb-932a-8f9f0726827f.png">

Docker build ->
<img width="401" alt="Screenshot 2021-04-04 at 22 31 34" src="https://user-images.githubusercontent.com/1383250/113520798-ef286600-9595-11eb-9bf5-26272e54bc34.png">

**Comment by ijjk** [comment] 2021-04-05 19:12
This is expected as we do dead-code elimination based on feature usage when able. When no `rewrites` are being used for a Next.js project we are able to remove code specific to rewrites client-side so depending on if they are used or not the JavaScript bundles will differ causing the chunk hashes to differ as well.

**Comment by davscro** [comment] 2021-04-05 20:52
So, that means if you **have** `rewrites` specified, it might be that chunk hashes will be calculated differently on different machines (servers) for the **same** Next.js project, right? 🤔 That's what I am experiencing atm. 
If that's a case, for me this is really strange behaviour, and I believe something code specific for rewrites is causing hash difference (suspecting on build timing; physical project location on drive or something similar). As I said for me it is strange If I do `yarn build` and my colleague do the same we get different hashes for the same project (on 10.0.5 and prior it was working OK).

**Comment by davscro** [comment] 2021-04-12 08:13
> This is expected as we do dead-code elimination based on feature usage when able. When no `rewrites` are being used for a Next.js project we are able to remove code specific to rewrites client-side so depending on if they are used or not the JavaScript bundles will differ causing the chunk hashes to differ as well.

I guess we have misunderstanding here...I am not talking about building twice once with rewrites and once without...of course in that case hashes are different...but I am talking about scenario when you have rewrites and you build same project on different servers (computers) you got different chunk-hashes.

**Comment by ijjk** [comment] 2021-04-17 15:50
This appears to be occurring without rewrites being present as well as mentioned in https://github.com/vercel/next.js/issues/24116 so I'm going to close this in favor of that issue

**Closed by ijjk** 2021-04-17 15:50 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
