### ISSUE TITLE
fetch revalidation not working with Nextjs 14.0.0

### ISSUE THREAD

**Issue by Deepak22448** [vercel/next.js#57632] opened 2023-10-27 20:19 UTC
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/blissful-boyd-mh27hy

#### Home Page
```tsx
import Link from "next/link";

const Home = () => {
  return (
    <div>
      <Link href="/time" className="border-2 p-2 mx-auto">
        Time
      </Link>
    </div>
  );
};

export default Home;
```

#### TimePage
```tsx
const Time = async () => {
  const res = await fetch("http://localhost:3000/api", {
    next: { revalidate: 2 },
  });
  const data = res.json();

  return <div>{data}</div>;
};

export default Time;
```

#### GET Route.
```tsx
import { NextResponse } from "next/server";
export const GET = () => {
  return NextResponse.json(Date.now());
};

export const dynamic = "force-dynamic";
```
Step 1 : Navigate to `Time` using link on home page.
Step 2 : Navigate back to `Home`.
Step 3 : wait for more than 2 seconds.
Step 4 : Again navigate to `Time`.
You see that The Cache is not changed even after completion of 2 seconds which was mentiond in `fetch` of `Time`. 

https://github.com/vercel/next.js/assets/87939462/0cdda015-7599-415c-bcf4-ad634e1d1063

### Current vs. Expected behavior

The cache is not updated which should be updated when mentioned revalidation time has completed.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103
Binaries:
  Node: 19.4.0
  npm: 9.6.7
  Yarn: 1.22.17
  pnpm: N/A
Relevant Packages:
  next: 14.0.0
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by teeto** [comment] 2023-10-28 07:24
RevalidateTag is also not working

**Comment by ijjk** [comment] 2023-11-07 05:30
Hi, please see this discussion for more context on how the cache behaves client-side https://github.com/vercel/next.js/discussions/54075

Also if you are seeing issues with `revalidateTag` or `revalidatePath` please provide a complete reproduction around that we can investigate further!

**Comment by teeto** [comment] 2023-11-07 11:42
Hi @ijjk , in my case, it is working fine in version 13.5.6 and after updating the project to version 14.0.0 it is not refreshing the cache.
I am using tags when using fetch `const res = await fetch(urlApi, { next: { tags: fetchCacheTags } });`
Then when some content in the cms changes i call the api route, which i pass some tags comma separated:
`let tagsRevalidate = tag.split(",");
  tagsRevalidate.map(async (tagItem) => {
    let urlRevalidate = tagItem;
    if (!urlRevalidate) urlRevalidate = "/";
    urlRevalidate = urlRevalidate.trim();
    revalidateTag(urlRevalidate);   
  });`
After calling the api with the tags, then refreshing the page showed the latest changes.
As said earlier, in version 13.5.6 this was working fine, but after updating to 14.0.0 the cache is not updating.

**Comment by Deepak22448** [comment] 2023-11-07 11:58
Yes caching shows unexpected behaviour in Nextjs 13.6+ for me.

**Comment by ijjk** [comment] 2023-11-08 16:52
Hi, any chance you could try the latest canary version `v14.0.2-canary.22`, there were some fixes landed recently around `revalidateTag` that may help here

**Comment by magicspon** [comment] 2023-11-09 13:23
I don't understand how the app router is sold as being stable when issues like this exist.  This is a major issue.

**Comment by magicspon** [comment] 2023-11-09 13:57
sometimes it works... sometimes it doesn't
screams stability!

**Comment by Matthewk01** [comment] 2023-11-09 14:20
Downgraded NextJs from the version 14 to 13.5 and ISR started working as expected.

**Comment by teeto** [comment] 2023-11-09 15:34
> v14.0.2-canary.22

I can confirm that revalidateTag is working in 14.0.2-canary.22

**Comment by john-rock** [comment] 2023-11-09 16:42
@teeto would you be able to share how you are setting the tag in the fetch call? I just tried 14.0.2-canary.22 and revalidateTag still does not work.

**Comment by teeto** [comment] 2023-11-09 16:49
yes, you can see it here:

`const res = await fetch(urlApi, { next: { tags: fetchCacheTags } });`

where fetchCacheTags is an array of tags like `["layout"]`

**Comment by john-rock** [comment] 2023-11-09 20:57
Hmm, on a clean install of next 14.0.2 it seems like tag re-validation still is not working for me once hosted on Vercel. Here's the demo repo. Unless I have the configuration completely wrong it seems like this is on Vercel's end.

https://github.com/john-rock/revalidatetag-bug-next14

**Comment by Galanthus** [comment] 2023-11-09 22:38
> Hmm, on a clean install of next 14.0.2 it seems like tag re-validation still is not working for me once hosted on Vercel. Here's the demo repo. Unless I have the configuration completely wrong it seems like this is on Vercel's end.
> 
> https://github.com/john-rock/revalidatetag-bug-next14

I can confirm this. Developed website using Sanity as the CMS and the latest Next 14.0.2. In order to revalidateTag to work, I have to save/publish the same post/page etc in order to see the changes. Vercel logs show no errors for me. Seems like it's too fast or too slow on revalidate. That said, having multiple tags has one higher fail rate. Hopefully this will be fixed soon.

**Comment by sven-ra** [comment] 2023-11-10 08:19
Can confirm this with version 14.0.0, 14.0.1, 14.0.2-canary.22.
Revalidate sometimes works sometimes does not. I have the same issue on two separate projects. Both use Strapi for back-end. In Vercel logs i see a successful revalidate function call but the content sometimes does not get updated.

**Comment by teeto** [comment] 2023-11-10 11:22
I updated as this:
`npm install next@14.0.2-canary.22`
Published the site, and make a change in the cms and it worked
Then, i updated to this:
`npm install next@latest`
And the same test did not work.

**Comment by isaackoz** [comment] 2023-11-11 22:49
> Hmm, on a clean install of next 14.0.2 it seems like tag re-validation still is not working for me once hosted on Vercel. Here's the demo repo. Unless I have the configuration completely wrong it seems like this is on Vercel's end.
> 
> https://github.com/john-rock/revalidatetag-bug-next14

Hey John I just tried your repo and I got it to work on `next@14.0.2` by adding
`export const dynamic = "force-dynamic";`
[to the route. ](https://github.com/isaackoz/revalidatetag-bug-next14/commit/13f2ec7c3b7843f402b95e3dbd4a897348c0ddfa).

If you check the build logs in Vercel, you'll see that `api/revalidate` is generated as an ISR function meaning it's getting cached. You can verify this by sending an API request to your `api/revalidate` and seeing that the date returned is always the same. By changing it to dynamic, the date returned is always up to date and the page successfully gets revalidated by tag name. 

[The docs](https://nextjs.org/docs/app/building-your-application/routing/route-handlers#opting-out-of-caching) are a bit confusing as they mention that 

> You can opt out of caching by: Using the Request object with the `GET` method

However, the route still gets cached despite having the Request object with the `GET` method. Perhaps it's because the request object isn't being used by the function?

**Comment by jmurty** [comment] 2023-11-11 23:07
Hi, in case it helps I have previously found the same vagueness around when a `GET` API route does or does not become dynamic, and created [an issue](https://github.com/vercel/next.js/issues/49006) to describe my findings.

This was a while ago with version 13.4 so **things might have changed** since then, but I suspect from @isaackoz's comment that the underlying auto-magical and confusing behaviour remains.

IMO there is too much black magic and too many surprising gotchas with this stuff, for example:
- Just passing in the `Request` object to the `GET` function is not enough to make it dynamic, you must also *access* at least one specially blessed attribute or function of the request in your code (at time of writing the issue, `request.cookies` was not one of these blessed attributes)
- Adding a `POST` implementation to a route with a purposefully static `GET` function makes the *entire route* dynamic, including for GET requests, even if you wanted the GET to remain static (for some weird reason)
- Adding `import { cookies } from "next/headers"` to a GET-only app route file doesn't make it dynamic, your code must also change it's behaviour at all unless your code also accesses a blessed attribute.

**Comment by john-rock** [comment] 2023-11-13 14:39
@isaackoz thanks for taking a look into this.

Can it be that the revalidateTag function is frequently inconsistent?

I'm trying to refresh on your deploy preview link and I just created a new branch on mine adding `export const dynamic = "force-dynamic";` and it still shows stale data 🤔

**Comment by Deepak22448** [comment] 2023-11-13 14:53
I confirm that `fetch("http://localhost:3000/api", {
    next: { revalidate: 5 },
  });` works with the latest version of Nextjs with is `14.0.2`

**Comment by Galanthus** [comment] 2023-11-13 14:56
It functions effectively when set to revalidate every 5 seconds. However, the preferred behavior is to trigger revalidation on specific events, such as saving a page or post.

While configuring revalidation to occur every 5 seconds does ensure that the data is consistently updated, it inadvertently undermines the primary purpose of dynamic caching. Ideally, revalidation should be triggered on specific events, such as saving a page or post. This ensures that the cache is cleared on demand, serving the latest fetched data immediately upon page refresh. Setting the revalidate interval to 5 seconds introduces a delay, counteracting the real-time benefits of on-request cache clearing.

**Comment by Galanthus** [comment] 2023-11-13 15:05
@Deepak22448, thank you. I've been trying to figure out this issue for two days. It seems to be a major problem on Vercel's side, to be honest. I'm working on a headless CMS website using Sanity and Next 14.0.2. When saving or publishing a page or post, it's either a hit or miss. I regularly have to save twice to see the changes. Hopefully, this issue will be resolved soon. Multiple other developers have confirmed that this issue is still present and ongoing.

**Comment by john-rock** [comment] 2023-11-13 15:34
Not to take this too far off topic but @Galanthus we are Sanity and Next 14.0.2 as well and as an interim solution I'm using a Sanity webhook that listens for publish, modify, delete actions on specific document types to trigger a [Vercel deploy hook](https://vercel.com/docs/deployments/deploy-hooks). Once the deploy completed the updated content shows. It's not ideal but our build times are only 1.5 - 2 minutes.

**Comment by isaackoz** [comment] 2023-11-13 21:28
@john-rock I removed the `export const dynamic = "force-dynamic";` and changed the revalidate from `GET` to `POST` as per [the Vercel infrastructure docs](https://vercel.com/docs/infrastructure/data-cache#tag-based-revalidation). Lmk if that works for you. I'm getting consistent results and having no issues with tags anymore. Also, it's worth mentioning that you have to clear the cache on the client sometimes (Ctrl+F5 or refresh 2 times). I don't think that's a Vercel/Next issue though.

It would be nice if there was somehow a way to get confirmation the `revalidateTag` successfully worked similar to how [Stripe handles webhook delivery](https://stripe.com/docs/webhooks#retries).

**Comment by john-rock** [comment] 2023-11-13 22:03
Hmm @isaackoz it still does not seem to be working for me after adding `POST` either. See [preview link here](https://github.com/john-rock/revalidatetag-bug-next14/pull/1) for the demonstration.

> It would be nice if there was somehow a way to get confirmation the revalidateTag successfully worked similar to how [Stripe handles webhook delivery](https://stripe.com/docs/webhooks#retries).
Yes, that would be a great QoL improvement!

**Comment by isaackoz** [comment] 2023-11-13 22:18
@john-rock 

It's working for me using your deploy link. I do a post call to your /api/revalidate and then go back to the page and it shows a new date.

**Closed** 2023-11-22 02:37 UTC
Labels: template: bug

**Comment by magicspon** [comment] 2023-11-27 18:00
this still doesn't work! 

https://nextjs.org/docs/app/api-reference/functions/revalidatePath#revalidating-a-page-path

```
revalidatePath('/(search)/search')
revalidatePath(`/(listing)/nursery/${entry._id}`)
revalidatePath(`/(search)/location/${entry.address.region}`)
revalidatePath(
  `/(search)/location/${entry.address.region}/${entry.address.county}`,
)
revalidatePath(
  `/(search)/location/${entry.address.region}/${entry.address.county}/${entry.address.city}`,
)
if (entry.address.borough)
  revalidatePath(
    `/(search)/location/${entry.address.region}/${entry.address.county}/${entry.address.borough}`,
  )

entry.eduType.forEach((edu) => {
  revalidatePath(`/education/${edu.slug}`)
})
```

revalidate all the things! denied... waaaaa
Is this "meant" to work, or am i missing something, are there a bunch of other things i need to do? 

thankfully i'm not too far along with this build, so i can switch back to the pages router. 🤯

I don't want to open another `cache` issue as there seems to be about a trillion already! I know this is free software n'all, but seriously wt----f!
