### ISSUE TITLE
Page changed from static to dynamic at runtime for app/[dynamic] path from Next.js 13.2+

### ISSUE THREAD

**Issue by r-martins** [vercel/next.js#46598] opened 2023-03-01 07:22 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020
    Binaries:
      Node: 19.6.0
      npm: 9.4.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.2.3-canary.0
      eslint-config-next: 13.2.2
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/next-js-bug-replication-rl4i69

### To Reproduce

Open the project at https://codesandbox.io/p/sandbox/next-js-bug-replication-rl4i69

Run npm run dev

Open the preview pane and access the `/gear` url.
It would be a dynamic route declared in `app/[categoria]`.

If you downgrade the project to any next.js version 13.1 < 13.2 the problem doesn't appear.

### Describe the Bug

A server error is generated:

Server Error

Error: Page changed from static to dynamic at runtime /gear
see more here https://nextjs.org/docs/messages/app-static-to-dynamic-error

**The issue does not happen in build mode**

### Expected Behavior

To see the category page with the fetched products.

### How are you deploying your application? (if relevant)

npm run dev, codesandbox.io

**Comment by ijjk** [comment] 2023-03-01 07:57
Closing as a duplicate of https://github.com/vercel/next.js/issues/46436

**Closed by ijjk** 2023-03-01 07:57 UTC
Labels: template: bug
