### ISSUE TITLE
`openGraph` metadata not merging across layouts

### ISSUE THREAD

**Issue by rafaelalmeidatk** [vercel/next.js#47540] opened 2023-03-26 06:18 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #202302091138~1675975749~22.04~f771a7f SMP PREEMPT_DYNAMIC Thu F
Binaries:
  Node: 18.15.0
  npm: 9.5.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant packages:
  next: 13.2.5-canary.18
  eslint-config-next: 13.2.4
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/festive-wind-gg87in?file=%2FREADME.md

### To Reproduce

1. Enter https://gg87in-3000.csb.app
2. The OG tags are correct in the home page:
```html
<meta property="og:title" content="Test OpenGraph"/>
<meta property="og:site_name" content="Test OpenGraph"/>
<meta property="og:type" content="website"/>
```
3. Go to the about page
4. The OG tags did not get merged:
```html
<meta property="og:title" content="About"/>
```

### Describe the Bug

From the docs:
> Objects are merged together to form the final metadata output. Duplicate keys are replaced based on their ordering. Learn more about [pages and layouts](https://beta.nextjs.org/docs/routing/pages-and-layouts).

I would expect that the final metadata output for the About page would have all the other defined tags in the root layout. I thought Next.js could be just overriding the root layout's `openGraph` key with the one in the about page (which would be unexpected as well) but after removing it, it still doesn't work.

Even if I entirely remove the `metadata` export from the about page, it doesn't render the metadata from the root layout.

Also, I am not sure if I did something wrong but the title template is not working as well. The title of the About page should be `About | Test OpenGraph` but it is just `About`. It is working in my local project tho, so not sure what's wrong here.

### Expected Behavior

These are the expected metatags for the about page:
```html
<meta property="og:title" content="About | Test OpenGraph"/>
<meta property="og:site_name" content="Test OpenGraph"/>
<meta property="og:type" content="website"/>
```

**Comment by steve-marmalade** [comment] 2023-03-28 05:23
I encountered this as well, and learned that nested objects like OG are intentionally not being merged (per [this comment](https://github.com/vercel/next.js/issues/46434#issuecomment-1446212307)). I have upvoted this issue as I hope the Next team is open to reconsidering this position. The current implementation has resulted in a lot of additional boilerplate in our metadata definitions and has significantly limited the usefulness of the metadata inheritance.

To the second point you raise, I was also surprised to see that the title template did not apply to the `og:title`. Assuming that the industry best-practice is in fact for `title` and `og:title` to match (which is my understanding), then it would be great to see support for that added as well.

**Comment by rafaelalmeidatk** [comment] 2023-03-28 07:19
Thanks for the other issue link, I somehow missed it while searching for existing issues. It looks like they won't be changing it and the issue is with the docs, I interpreted this line:

> Objects are merged together to form the final metadata output. Duplicate keys are replaced based on their ordering.

As: "Objects are merged, duplicate keys (e.g. `metadata.openGraph.description`) will be replaced based on the ordering"

> To the second point you raise, I was also surprised to see that the title template did not apply to the `og:title`

What made me assume that the metadata would be deep merged was the fact of Next.js accepting `{ title: string; template: string }` as the value of `openGraph.title`. If the keys are not supposed to be merged, what is the use of a title template there if it is not gonna be used?

**Comment by Fredkiss3** [comment] 2023-03-29 08:50
Hello, Metadata are merged from the layout to the pages (i think), and pages are totally replaced between navigations, you should put the metadata template in `app/layout.tsx`  instead of `app/page.tsx`. 

When doing so, the titles are merged (`title` & `openGraph.title`), but the rest of the openGraph items still are not merged and you end up with this : 
```html
<title>About | Test OpenGraph</title>
<meta property="og:title" content="About | Test OpenGraph"/>

<!-- But these are not included  -->
<!-- <meta property="og:site_name" content="Test OpenGraph"/> -->
<!-- <meta property="og:type" content="website"/> -->
```
 
see : https://codesandbox.io/p/sandbox/condescending-pike-b8ql12?file=%2Fapp%2Fabout%2Fpage.tsx&selection=%5B%7B%22endColumn%22%3A20%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A20%2C%22startLineNumber%22%3A9%7D%5D

I agree that this is confusing and maybe it would be better to just merge nested items. 
One thing however is that if all the items are merged then how do you do when you want to remove certains tags from being included in nested pages ? (maybe it is not a problem since defining the metadata in the layout means that you want to include all the tags here in all the children ? 🤔)

**Comment by steve-marmalade** [comment] 2023-03-29 19:33
> how do you do when you want to remove certains tags from being included in nested pages ?

So far I have not encountered any such cases, so that's some evidence to suggest it's not the most important case to handle. That said, I agree it's possible. A solution that's intuitive to me would be to set the value of the tag I want to remove to `null` in the nested page.

**Comment by semy** [comment] 2023-04-06 08:53
For example, some of my title tags are not overwritten when I switch to a new page via a NextJs link. With a hard reload, the correct title appears.

**Comment by huozhi** [comment] 2023-05-03 14:15
It's by designed ew don't merge them automactially as it might introduce more frictions between what users expect or what it behaves. There's a way you can use `generateMetadata` to merge yourself

```
export async function generateMetadata(props, parent) {
	const parentMetadata = await parent
	/* add your merging logic  ... */ 
	const metadata = merge(customMetadata, parentMetadata)
}
```

**Closed** 2023-05-03 14:15 UTC
Labels: template: bug, area: Metadata, area: app

**Comment by bfourgeaud** [comment] 2023-05-05 10:47
@huozhi I was in fact working on that solution to merge data, but it seems to always fire an error on my side. It seems to come from the way the images are retrieved from the parent. as an array of objects instead of an array of strings.

**Error :** 
`Error: The "path" argument must be of type string. Received an instance of Object`

```ts
export async function generateMetadata({ searchParams }: ProductIndexProps, parent?: ResolvingMetadata):Promise<Metadata> {
  const parentMetadata = await parent

  return {
    title: `Recherche : "${searchParams.search || ""}"`,
    openGraph: {
      ...parentMetadata.openGraph,
      title: `Recherche : "${searchParams.search || ""}"`
    }
  }
}
```

If I console.log the returned value it gives me that : 
```
{
  title: 'Recherche : "chaise"',
  openGraph: {
    images: [ { url: {} } ],
    title: 'Recherche : "chaise"',
    description: "Réseau d'experts en Piscines, fontaines, travaux hydrauliques et traitement de l'eau, nous accompagnons vos projets.",
    type: 'website',
    url: null
  }
}
```


For information, in my layout.tsx file I have set images, and they work fine on all other pages
```
openGraph: {
      images: [site.partner.logo.url],
      title: site.partner.name,
      description: site.partner.shortDescription,
      type: "website"
    }
```

**Comment by bfourgeaud** [comment] 2023-05-05 16:09
I created a new issue with reproduction link : https://github.com/vercel/next.js/issues/49316
