### ISSUE TITLE
with-emotion throws an error during `yarn build`

### ISSUE THREAD

**Issue by okmttdhr** [vercel/next.js#19921] opened 2020-12-07 06:04 UTC
# Bug report

## Describe the bug

`with-emotion` example throws an error during the build.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. git clone https://github.com/vercel/next.js.git
1. `cd next.js/examples/with-emotion`
2. ~~`yarn build`~~ `yarn && yarn build`
3. See error:

```bash
± yarn build
yarn run v1.22.5
$ next build
info  - Using external babel configuration from /path/to/next.js/examples/with-emotion/.babelrc
info  - Creating an optimized production build
Failed to compile.

./node_modules/@emotion/react/dist/emotion-element-5144c041.browser.esm.js
Attempted import error: 'createContext' is not exported from 'react'.

> Build error occurred
Error: > Build failed because of webpack errors
    at build (/path/to/next.js/examples/with-emotion/node_modules/next/dist/build/index.js:15:918)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected behavior

Should build `.next/*` without error

## Screenshots

None

## System information

- OS: macOS
- Browser: None
- Version of Next.js: 10.0.3 (10.0.5, still happening)
- Version of Node.js: 14.15.1
- Deployment: None

## Additional context

The build was successful when back to here; https://github.com/merceyz/next.js/tree/ac34a9f960b85fa074726b5f1970dd0c20600752/examples/with-emotion

**Comment by karlhorky** [comment] 2020-12-15 13:38
Hm, interesting... seems like the ESM version of the `emotion-element` file is looking to import `createContext` from React but having problems...

@Andarist would you know what could be the issue here?

**Comment by Andarist** [comment] 2020-12-19 23:39
The provided repro steps are not sufficient to repro this - I'm getting:
> /bin/sh: next: command not found

I've tried to run `yarn` in the root and looked through Lerna setup quickly but I haven't quickly found a way to run this.

My bet is that maybe this, for some reason, has started to opt-into strict node's ESM semantics?

**Comment by tarunama** [comment] 2021-01-11 13:20
@okmttdhr 
I tried to reproduce error, but it is not happened.
Maybe solved in latest version of Next.js.

**Comment by tarunama** [comment] 2021-01-14 14:00
@okmttdhr 
Let's check below PR !
https://github.com/vercel/next.js/pull/21118

**Comment by tarunama** [comment] 2021-01-25 06:26
@timneutkens 
Please judge whether close this issue.

Does not confirm this issue on `next@latest`, when executed below commands.

1. `git clone https://github.com/vercel/next.js.git`
2. `cd next.js/examples/with-emotion`
3. ~yarn build~ -> yarn && yarn build

I tried to reproduce build error, but it was not occured.
`yarn build` is successful.

git commit hash: 8d92010979ea91d27303e47917fdab121ae5f150

**Comment by leerob** [comment] 2021-02-01 21:54
I was not able to reproduce this. If someone else can, we can reopen 🙏

**Closed by leerob** 2021-02-01 21:54 UTC
Labels: good first issue, type: example

**Comment by okmttdhr** [comment] 2021-02-02 09:55
FYI

I found that this issue happens only when `NODE_PATH=./`
Build succeed when I set `NODE_PATH=''`

**Comment by balazsorban44** [comment] 2022-01-28 18:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
