### ISSUE TITLE
Form doesn't work inside client component in server component page

### ISSUE THREAD

**Issue by ZetraDev** [vercel/next.js#34215] opened 2022-02-11 05:41 UTC
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 17.5.0
      npm: 8.4.1
      Yarn: 3.1.1
      pnpm: N/A
    Relevant packages:
      next: 12.0.11-canary.12
      react: 18.0.0-rc.0
      react-dom: 18.0.0-rc.0

### What version of Next.js are you using?

12.0.11-canary.12

### What version of Node.js are you using?

17.5.0

### What browser are you using?

brave

### What operating system are you using?

Windows

### How are you deploying your application?

next dev and next start

### Describe the Bug

When I try to click the submit button of a form which is inside component.client.tsx which is rendered inside page.server.tsx, it pop two errors in console:
```
react-server-dom-webpack.development.js:181          Uncaught TypeError: Failed to fetch
    at fetchFlight (index.js:868:16)
    at useServerResponse (index.js:890:19)
    at ServerRoot (index.js:921:24)
    at renderWithHooks (react-dom.development.js:16186:18)
    at mountIndeterminateComponent (react-dom.development.js:20846:19)
    at beginWork (react-dom.development.js:22284:16)
    at beginWork$1 (react-dom.development.js:27066:14)
    at performUnitOfWork (react-dom.development.js:26255:12)
    at workLoopSync (react-dom.development.js:26165:5)
    at renderRootSync (react-dom.development.js:26133:7)
    at performSyncWorkOnRoot (react-dom.development.js:25797:20)
    at flushSyncCallbacks (react-dom.development.js:11776:22)
```
```
​ The above error occurred in the <ServerRoot> component:

    at ServerRoot (webpack-internal:///./.yarn/__virtual__/next-virtual-009548a309/0/cache/next-npm-12.0.11-canary.9-d23c91026b-fb57be1a2e.zip/node_modules/next/dist/client/index.js:919:30)
    at Suspense
    at eval (webpack-internal:///./.yarn/__virtual__/next-virtual-009548a309/0/cache/next-npm-12.0.11-canary.9-d23c91026b-fb57be1a2e.zip/node_modules/next/dist/client/index.js:943:43)
    at App (webpack-internal:///./.yarn/__virtual__/next-virtual-009548a309/0/cache/next-npm-12.0.11-canary.9-d23c91026b-fb57be1a2e.zip/node_modules/next/dist/pages/_app.js:178:9)
    at ErrorBoundary (webpack-internal:///./.yarn/__virtual__/next-virtual-009548a309/0/cache/next-npm-12.0.11-canary.9-d23c91026b-fb57be1a2e.zip/node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20584)
    at ReactDevOverlay (webpack-internal:///./.yarn/__virtual__/next-virtual-009548a309/0/cache/next-npm-12.0.11-canary.9-d23c91026b-fb57be1a2e.zip/node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23125)
    at Container (webpack-internal:///./.yarn/__virtual__/next-virtual-009548a309/0/cache/next-npm-12.0.11-canary.9-d23c91026b-fb57be1a2e.zip/node_modules/next/dist/client/index.js:357:9)
    at AppContainer (webpack-internal:///./.yarn/__virtual__/next-virtual-009548a309/0/cache/next-npm-12.0.11-canary.9-d23c91026b-fb57be1a2e.zip/node_modules/next/dist/client/index.js:792:26)
    at Root (webpack-internal:///./.yarn/__virtual__/next-virtual-009548a309/0/cache/next-npm-12.0.11-canary.9-d23c91026b-fb57be1a2e.zip/node_modules/next/dist/client/index.js:1048:27)
```
But if I change the page to .client.tsx, it work

The code of the page:
```js
// .server.tsx
export default function Index() {
	return (
		<div>
			<p>Index</p>
			<Form />
		</div>
	);
}
```
The code of the Form
```js
// .client.tsx
export default function Form() {
	return (
		<div>
			<p>Form</p>
			<form
				onSubmit={(e) => {
					e.preventDefault();
					console.log(e.target[0].value);
				}}
			>
				<input type="text" name="textInput" placeholder="Text here" />
				<button type="submit">Submit</button>
			</form>
		</div>
	);
}
```

### Expected Behavior

No Error

### To Reproduce

1. create page that render in server (.server.tsx)
2. import the form component with is rendered in client (.client.tsx)
3. open the page and click submit button

**Comment by balazsorban44** [comment] 2022-02-16 21:12
Hi, this seems to have been fixed in a later release, I could not reproduce anymore on `canary`. Please upgrade.

**Closed by balazsorban44** 2022-02-16 21:12 UTC
Labels: template: bug, area: Server Components
