### ISSUE TITLE
Scroll restoration doesn't work for large pages

### ISSUE THREAD

**Issue by yura3d** [vercel/next.js#37893] opened 2022-06-21 20:29 UTC
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020
    Binaries:
      Node: 14.18.1
      npm: 6.14.15
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.42
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 102.0.5005.115

### Describe the Bug

When pressing back key, if the page to return is pretty large (it's enough to have a 1000 iterations loop for printing simple string), the scroll position always jumps to the top, regardless of the real position was before leaving the page.

### Expected Behavior

The scroll position should restore correctly.

### Link to reproduction

https://codesandbox.io/s/delicate-cache-pnmc7c

### To Reproduce

Open https://pnmc7c.sse.codesandbox.io/
Scroll down to the link to another page and click it.
Return back. The scroll position is not restored.

Fork the sandbox, open `pages/index.js`, change iterations number from `1000` to `10` and save the file.
Open the new sandbox in new window.
Scroll down to the link to another page and click it.
Return back. Now the scroll position is restored.

**Comment by oliviertassinari** [comment] 2022-07-25 11:04
I can reproduce the bug with the documentation of Next.js. https://nextjs.org/docs/getting-started. We have found this regression on MUI https://github.com/mui/material-ui/pull/33196#discussion_r928753221 by moving from v12.1.5 to v12.2.0. So I assume that the regression happened between these two Next.js versions.

**Comment by meotimdihia** [comment] 2022-08-20 15:31
@balazsorban44 could you confirm this is a bug? it is pretty obvious.

**Comment by yura3d** [comment] 2022-09-08 22:50
The solution suggested by @meotimdihia works great. But it would be nice to get explanations from contributors about it.

I can't find any information about `scrollRestoration` key in the docs, and which versions of Next/React are supported by it. The docs contains only the [Scroll Restoration](https://nextjs.org/docs/migrating/from-react-router#scroll-restoration) paragraph that doesn't describe the need for any external steps to enable the feature.

**Comment by rasco** [comment] 2022-11-30 11:23
@meotimdihia @yura3d yes, can confirm the same here. it suddenly works, after i enabled the experimental flag. even though the docs make it seem like it should already be enabled by default.

**Comment by don-esteban** [comment] 2023-01-14 17:06
**TL;TR**

1. With `scrollRestoration: true` and `"next": "^13.0.7"`scroll restoration works in FF, Chrome and Safari for internal links. For internal fragment links (#) it does not work.
2. With `scrollRestoration: false` scroll restoration does not work at all, but for fragment links (#) in FF and Safari. In Chrome it does not work.

### Reproduction

Scroll restoration with fragment links (#-links/anchors) are still buggy. The issue can be reproduced by starting a new Next.js app `npx create-next-app@latest` and adding text with fragment links to the home page.

Fragment links **do work** with FireFox (108.0.2) and Safari (Version 16.2 (17614.3.7.1.7, 17614)) on latest macOS.

Fragment links **do not work** with Chrome (Version 108.0.5359.124) on latest macOS.

I do not have access to Microsoft Windows machines.

With the experimental feature

```
// next.config.js
...
experimental: {
  scrollRestoration: true,
},
...
```

enabled. Scroll restoration with fragment links does not work at all in FF, Chrome and Safari. In some older next.js version, it worked in all three browsers.

**Comment by Pikachews** [comment] 2023-03-02 09:08
> We have found this regression on MUI [mui/material-ui#33196 (comment)](https://github.com/mui/material-ui/pull/33196#discussion_r928753221) by moving from Next.js v12.1.5 to v12.2.0 and React from 17.0.2 to 18.2.0. Maybe the regression happened between these two Next.js versions? 🤷‍♂️

Yes, and to be precise, it appears to have been introduced in `v12.1.5-canary.1`, and versions prior to it (`v12.1.5-canary.0`, `v12.1.4`, ...) did not experience this issue, from my experience.

**Comment by bline** [comment] 2023-04-23 22:44
Any solutions for this? My client makes heavy use of `#hash` links with long pages and it's a mess. This is a major blocking issue for them. There is no way I can go live with the situation the way it is.
If anyone knows a work-around for this issue, please let me know.

**Comment by noveogroup-amorgunov** [comment] 2023-05-07 09:08
I use this workaround for scroll restoration (https://gist.github.com/jeffijoe/510f6823ef809e3711ed307823b48c0a). Save scroll position on unmount in memory storage, and restore position on mount.

**Comment by timneutkens** [comment] 2023-07-04 09:46
Going to close this as a duplicate of https://github.com/vercel/next.js/issues/3303#issuecomment-1617910905

**Closed by timneutkens** 2023-07-04 09:46 UTC
Labels: template: bug, area: Routing
