### ISSUE TITLE
CSR (client side transition) not working on 404 pages

### ISSUE THREAD

**Issue by Vadorequest** [vercel/next.js#13516] opened 2020-05-28 20:26 UTC
# Bug report

## Describe the bug

Using a Link to go to a 404 page doesn't work. The link is unresponsive, nothing happens on the browser.

You can reproduce this at https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-peyfrlyfe.now.sh/fr/examples/built-in-utilities/errors-handling and click on the `This is a client-side navigation (CSR)` link.

Note that using `This is a normal navigation` link works as expected, but it uses a `<a>` link instead.

## To Reproduce

1. Use `<Link>` from `next/link` with href to a non-existing page
2. Try to click on it

## Expected behavior

The link should redirect to a 404 page.

## Screenshots

Video at https://youtu.be/mhJE5s-CIEE

## Additional context

Reproduced on v9.4.1 to v9.4.4

**Comment by Timer** [comment] 2020-06-11 16:59
We added a test to ensure this behavior works in #14082.

You'll need to provide a demo for us to look into this.

**Comment by Vadorequest** [comment] 2020-06-12 07:09
Thanks for the update.

My experimentations showed me that:

- It works when working locally
- If doesn't work when hosted on Vercel (I don't know if that's related to Vercel though)

**Online reproduction:**
- Vercel deployment: https://nrn-v2-mst-aptd-at-lcz-sty-c1-d06z5ct37.now.sh/fr/examples/built-in-utilities/errors-handling
	- Click on the `This is a client-side navigation (CSR)` link, nothing happens

**Local reproduction:**
1. `git clone https://github.com/UnlyEd/next-right-now.git nrn-quick-start`
1. `cd nrn-quick-start && git checkout v2-mst-aptd-gcms-lcz-sty`
1. `yarn`
1. `yarn start`
1. Go to http://localhost:8888/fr/examples/built-in-utilities/errors-handling

As mentioned above, it works locally.

If you want to deploy to Vercel, you'll need to run `yarn deploy:customer1` after updating the `now.customer1.staging.json` file by changing the `scope` to a scope you own.

**Comment by Timer** [comment] 2020-06-12 15:29
Great! We'll look into this asap.

**Comment by ijjk** [comment] 2020-06-12 17:49
Hi @Vadorequest, we recently changed how we handle loading page bundles on the latest canary of Next.js, could you try upgrading/deploying your project with the latest canary of Next.js (9.4.5-canary.12) and confirming whether this is still an issue for you or not?

**Comment by Vadorequest** [comment] 2020-06-12 19:12
@ijjk https://nrn-v2-mst-aptd-at-lcz-sty-c1-irsey8w77.vercel.app/fr/examples/built-in-utilities/errors-handling behaves the same as before, using 9.4.5-canary.12.

Branch: https://github.com/UnlyEd/next-right-now/pull/112

**Comment by ijjk** [comment] 2020-06-12 19:15
@Vadorequest this deployment https://nrn-v2-mst-aptd-at-lcz-sty-c1-irsey8w77.vercel.app/fr/examples/built-in-utilities/errors-handling is still using Next.js `v9.4.4` 🤔

**Comment by Vadorequest** [comment] 2020-06-12 19:16
When the mouse is hovering the link, an error is thrown in the browser console.

![image](https://user-images.githubusercontent.com/3807458/84538362-ce82dd00-acf1-11ea-8e3a-5dafe694ab63.png)

It contains the 404 page 

![image](https://user-images.githubusercontent.com/3807458/84538429-ef4b3280-acf1-11ea-8202-f1230f20598c.png)

**Comment by Vadorequest** [comment] 2020-06-12 19:17
> @Vadorequest this deployment https://nrn-v2-mst-aptd-at-lcz-sty-c1-irsey8w77.vercel.app/fr/examples/built-in-utilities/errors-handling is still using Next.js `v9.4.4` 🤔

How can you tell? I'll check, thanks (my CI is broken tonight due to some Vercel-related stuff, sorry)

**Comment by ijjk** [comment] 2020-06-12 19:21
You can tell since the deployment doesn't have internal Next.js changes from the latest canary and still has internal code for `v9.4.4`. 

For example, client page bundles are no longer nested under a directory with `BUILD_ID` on the latest canary of Next.js and the above deployment is

**Comment by Vadorequest** [comment] 2020-06-12 19:28
Okay, not something obvious that I had missed then 😄 

And indeed, it's fixed now:
https://nrn-v2-mst-aptd-gcms-lcz-sty-c1-7k38q6g0x.vercel.app/fr/examples/built-in-utilities/errors-handling

It doesn't do a client side transition though, it's a normal "full page refresh" navigation that's performed. But it does work! 🎉

**Comment by ijjk** [comment] 2020-06-12 19:33
Yeah definitely not obvious 😅, thanks for checking that! 

The full page transition is the expected behavior since it is detecting it isn't able to perform the client transition so falls back to the full transition

**Comment by Vadorequest** [comment] 2020-06-12 19:40
Alright, awesome. Thanks for fixing that! 

I'll let you close if everything is good for you, or maybe wait until it's officially released? Anyway, your call. 😉

**Comment by Timer** [comment] 2020-06-13 03:16
Closing since it's fixed on canary.

**Closed by Timer** 2020-06-13 03:16 UTC
Labels: kind: bug, priority: p0

**Comment by balazsorban44** [comment] 2022-01-30 01:27
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
