### ISSUE TITLE
Bug: `next build` fails when `NODE_ENV=test` on a simple project

### ISSUE THREAD

**Issue by geelen** [vercel/next.js#20069] opened 2020-12-10 18:44 UTC
# Bug report

## Describe the bug

Running `NODE_ENV=test yarn build` on a fresh create-next-app fails

## To Reproduce

```
yarn create next-app no-bueno
cd no-bueno
NODE_ENV=test yarn build
```

## Expected behavior

Should build, or give a useful error message. Currently it bails with:

```
Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error
TypeError: Object(...) is not a function
```

## Screenshots

![image](https://user-images.githubusercontent.com/23264/101815356-561d9d00-3b17-11eb-83ba-64fdfb75fc93.png)

## Additional context

Happened during an E2E test using Jest and Execa/Shellac: https://github.com/fab-spec/fab/pull/283

**Comment by prophet1996** [comment] 2020-12-17 18:13
Hi @geelen  I have tried reproducing this but the build works
![bug](https://user-images.githubusercontent.com/16836510/102526444-a8cff980-40c1-11eb-88ff-d49688c379cd.png)

**Comment by votemike** [comment] 2020-12-22 21:00
I have also tried the steps to reproduce and the build seems to work fine.

**Comment by alexkhismatulin** [comment] 2021-02-22 04:42
Same. No luck trying to reproduce this.

**Comment by chozzz** [comment] 2021-07-04 16:35
I might have encountered the similar error output before, but it was due to upgrading nextjs.
Try clearing `.next` folder and rebuilt it, fixed it for me.

**Comment by ijjk** [comment] 2021-09-23 04:17
Closing per above as this appears to be working correctly in the latest version of Next.js `v11.1.2`. Also potentially related https://github.com/vercel/next.js/issues/19046

**Closed by ijjk** 2021-09-23 04:17 UTC
Labels: kind: bug, good first issue
