### ISSUE TITLE
turbo fails to resolve with certain node import subpaths

### ISSUE THREAD

**Issue by juliusmarminge** [vercel/next.js#72000] opened 2024-10-29 00:01 UTC
### Link to the code that reproduces this issue

https://github.com/juliusmarminge/turbo-import-subpath

### To Reproduce

1. `pnpm dev`  - works
2. `pnpm dev --turbo` - fails

### Current vs. Expected behavior

When using a string value like

```json
{
	"imports": {
		"#*": "./*.ts"
	}
}
```

turbopack successfully resolves the import subpath. But when adding an array:

```json
{
	"imports": {
		"#*": ["./*.ts", "./*.tsx"]
	}
}
```

it fails. Running without turbopack works in both cases

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Tue Sep 17 07:46:59 PDT 2024; root:xnu-11215.40.59~38/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.15.1
  npm: 10.7.0
  Yarn: N/A
  pnpm: 9.12.2
Relevant Packages:
  next: 15.0.1 // Latest available version is detected (15.0.1).
  eslint-config-next: N/A
  react: 19.0.0-rc-69d4b800-20241021
  react-dom: 19.0.0-rc-69d4b800-20241021
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by juliusmarminge** [comment] 2024-10-29 00:08
hmm might be related to the exports case reported here: https://github.com/vercel/next.js/issues/71001

that's a bummer if that's intended behavior...

**Comment by mischnic** [comment] 2024-11-11 13:54
This is indeed a duplicate of https://github.com/vercel/next.js/issues/71001. See the explanation here:  https://github.com/vercel/next.js/issues/71001#issuecomment-2407453993

You can use tsconfig `paths` instead for the fallback behavior https://www.typescriptlang.org/docs/handbook/modules/reference.html#fallbacks

**Closed by mischnic** 2024-11-11 13:54 UTC
Labels: bug, Turbopack, linear: turbopack
