### ISSUE TITLE
link to dynamic route with query params not working client-side

### ISSUE THREAD

**Issue by cztomsik** [vercel/next.js#10494] opened 2020-02-11 15:39 UTC
# Bug report
Note there are 4 similar issues but I think none of them is duplicate.

## Describe the bug
I think it's not possible to create a Link for dynamic route with query params in a way which would work both server-side & client-side.

## To Reproduce
- create `/pages/[id].js`
- `const { query: { id, foo } } = useRouter()`
- `console.log(id, foo)`
- create `/pages/index.js`
- `<Link href="/[id]" as={{ pathname: '/123', query: { foo: 'bar' } }}><a>...`
  - this way, it doesn't propagate to client-side (only `id` is available, `foo` is `undefined`)
- `<Link href={{ pathname: '/123', query: { foo: 'bar' } }}>...`
  - this seems to work but it also does request to `/pages/123.js` and that throws `404` which in turn does full-page reload which actually shows what's expected (but it's super-ugly and much slower as it's just SSR result and not regular client-side route transition)

## Expected behavior
I'd expect `href="/[id]" as={{ pathname: '/123', query: { foo: 'bar' } }}` to work with both client-side routing and prefetching (if I understand correctly what that `123.js` request is)

## System information
- OS: macOS
- Browser: latest Chrome
- Next.js: 9.2.2-canary.15

**Comment by shouze** [comment] 2020-03-06 09:58
@cztomsik what are similar issues according to you?

We also experience this bug, maybe related to https://github.com/zeit/next.js/issues/10449 which is closed, will will take a look today.

**Comment by Janpot** [comment] 2020-03-06 10:44
What happens when you do
```jsx
<Link 
  href={{ pathname: '/[id]', query: { foo: 'bar' } }} 
  as={{ pathname: '/123', query: { foo: 'bar' } }}
>...<a>
```
?

**Comment by shouze** [comment] 2020-03-06 15:23
@Janpot it works correctly when using href... to with dynamic routes, issue can be closed

**Comment by nlopin** [comment] 2020-04-20 14:35
Hello guys! I experience the same behavior. The @Janpot solution fixes it but it is verbose. 

It looks like everything that is not in the `href` pattern is omitted. I don't understand why the query params cannot be parsed in that case. They are parsed if I reload the page

**Comment by giovannibenussi** [comment] 2020-04-23 17:40
I'm experiencing the same issue. @Janpot solution worked for me too.
It is supposed to be that way? I'd expect query parameters to be provided automatically because otherwise it becomes very verbose to make it work.

The URL works when rendered on the server, and only fails when transitioning client side, which would involve make code to handle a special case on the client which doesn't seems right.

**Comment by ijjk** [comment] 2020-09-10 20:23
I'm going to close this in favor of https://github.com/vercel/next.js/issues/9473 since the issue doesn't appear to be specific to dynamic routes and is also referring to query value being missing unless defined in the `href`

**Closed by ijjk** 2020-09-10 20:23 UTC

**Comment by balazsorban44** [comment] 2022-01-29 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
