### ISSUE TITLE
Cannot use 'in' operator to search for... in version 9.4

### ISSUE THREAD

**Issue by Rhapzody** [vercel/next.js#15248] opened 2020-07-17 04:53 UTC
i upgrade nextjs from 9.3 to 9.4 and i have an error.

<img width="981" alt="Screen Shot 2563-07-17 at 11 47 54" src="https://user-images.githubusercontent.com/12486239/87749685-880a2c00-c823-11ea-99b2-f138f0d0f061.png">
<img width="471" alt="Screen Shot 2563-07-17 at 11 48 44" src="https://user-images.githubusercontent.com/12486239/87749693-8e98a380-c823-11ea-924c-4c6a393501e3.png">

i have no idea what's wrong in my code because there is no "in" operation in my code, but chat-script.js file have jquery script

please hel pme

## System information

- OS: macOS
- Browser: chrome
- Version of Next.js: 9.4.4
- Version of Node.js: 12.13.1

**Comment by timneutkens** [comment] 2020-07-17 09:39
Please provide a full reproduction as asked for in the issue template.

**Comment by Timer** [comment] 2020-09-03 02:34
Closing as no reproduction provided.

**Closed by Timer** 2020-09-03 02:34 UTC
Labels: please add a complete reproduction

**Comment by dancancro** [comment] 2021-04-17 21:51
Hi @Rhapzody. I have this error too. Were you able to find a solution to the problem?

**Comment by balazsorban44** [comment] 2022-01-28 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
