### ISSUE TITLE
The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

### ISSUE THREAD

**Issue by machooper** [vercel/next.js#29605] opened 2021-10-04 10:19 UTC
### What version of Next.js are you using?

^11.1.3-canary.41

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

When deploying my application there are no errors however I was wondering how to remove this warning for future proofing purposes.

```
11:15:48.512 | warning next > native-url > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
-- | --
11:15:48.512 | warning next > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```

### Expected Behavior

Everything working as expected just future proofing.

### To Reproduce

Deploy a repo to Vercel that is using Next.js

**Comment by ijjk** [comment] 2021-10-04 23:17
Closing as a duplicate of https://github.com/vercel/next.js/issues/27230

**Closed by ijjk** 2021-10-04 23:17 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 16:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
