### ISSUE TITLE
Pages css also includes common css

### ISSUE THREAD

**Issue by vhpoet** [vercel/next.js#13879] opened 2020-06-07 19:09 UTC
# Bug report

## Describe the bug

I'm on the newest next.js, using the built in sass. I have a `Button` component with `Button.module.scss` styles. This `Button` is used in most of the pages. When I build the app, the common css chunk under `First Load JS shared by all` includes the `Button` styles, but somehow other pages css files also include it. Is this an expected behavior? I might be missing something here.

## Expected behavior

Those styles should only be included in the common css file.

**Comment by timneutkens** [comment] 2020-06-08 17:36
Please add a complete reproduction (e.g. a github repository) as asked for in the issue template

**Comment by Timer** [comment] 2020-09-03 02:32
Closing as no reproduction provided.

**Closed by Timer** 2020-09-03 02:32 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
