### ISSUE TITLE
Image with src "..." is smaller than 40x40. Consider removing the "placeholder='blur'" property to improve performance.

### ISSUE THREAD

**Issue by danielkrupnyy** [vercel/next.js#26421] opened 2021-06-21 13:28 UTC
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

I'm loading my image from API. It should take up the whole screen. 
When I'm using `layout="fill"`, always getting an error:
 ![Screenshot 2021-06-21 at 4 01 24 PM](https://user-images.githubusercontent.com/33555925/122766227-f5cb9d00-d2a9-11eb-8737-9ebe909609ef.png)
How to fix this?

### Expected Behavior

It should loading without errors.

### To Reproduce

```javascript
<div className="relative h-full w-full">
{project?.images[0]?.url && (
<Image
  src={project?.images[0]?.url}
  alt={project?.images[0]?.caption}
  layout="fill"
  objectFit="cover"
  objectPosition="center"
  className="w-full h-full"
  blurDataURL={project?.images[0]?.url}
  placeholder="blur"
/>
)}
</div>
```

**Comment by timneutkens** [comment] 2021-06-21 14:13
This has been fixed on next@canary already 👍

**Closed by timneutkens** 2021-06-21 14:13 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 05:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
