### ISSUE TITLE
HMR warnings after upgrading to Webpack 5.10.0

### ISSUE THREAD

**Issue by paambaati** [vercel/next.js#19865] opened 2020-12-05 13:03 UTC
# Bug report

After upgrading to Webpack 5.10.0, I see this warning a lot on the console —

```
warn  - HotModuleReplacementPlugin
The configured output.hotUpdateMainFilename doesn't lead to unique filenames per runtime and HMR update differs between runtimes.
This might lead to incorrect runtime behavior of the applied update.
To fix this, make sure to include [runtime] in the output.hotUpdateMainFilename option, or use the default config.
```

**Everything seems to work fine, though.**

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Upgrade Webpack to 5.10.0
2. Use `next` to run a Next.js app in dev mode.
3. Make changes to a SSR page that is currently open in a browser so that HMR can kick in and auto-reload the page.
4. See warning on console —
    ```
    warn  - HotModuleReplacementPlugin
    The configured output.hotUpdateMainFilename doesn't lead to unique filenames per runtime and HMR update differs between runtimes.
    This might lead to incorrect runtime behavior of the applied update.
    To fix this, make sure to include [runtime] in the output.hotUpdateMainFilename option, or use the default config.
    ```

## Expected behavior

No warnings.

## Screenshots

N/A

## System information

- OS: macOS
- Browser (if applies): Microsoft Edge
- Version of Next.js: 10.0.3
- Version of Node.js: v15.3.0
- Deployment: `next` (Dev mode)

## Additional context

N/A

**Comment by awareness481** [comment] 2020-12-05 13:39
Likely related to https://github.com/vercel/next.js/issues/18678

**Comment by Timer** [comment] 2020-12-08 15:39
Duplicate of https://github.com/vercel/next.js/issues/18678

**Closed by Timer** 2020-12-08 15:39 UTC
Labels: template: bug

**Comment by timneutkens** [comment] 2020-12-09 10:00
I can't reproduce this warning with the latest version of webpack 5 and next@canary 🤔

**Comment by paambaati** [comment] 2020-12-09 12:57
@timneutkens I just checked out canary and I'm still seeing these warnings in `10.0.4-canary.3` and `5.10.0`. Is there additional information I could provide to narrow this down?

**Comment by paambaati** [comment] 2021-02-16 05:52
@timneutkens I have a small repro here — https://github.com/paambaati/nextjs-webpack-worker-bug-repro

**Comment by ivan-aksamentov** [comment] 2021-02-18 11:50
I was able to workaround this by prepending `[runtime]-` to the `webpackConfig.output.hotUpdateChunkFilename` and `webpackConfig.output.hotUpdateMainFilename`. Looks like this is the "new" Webpack 5 way. Probably should not be used with Webpack 4. Not sure about Webpack 5 versions before this change.

Taken from `shellscape/webpack-plugin-serve`:

Discussion:
https://github.com/shellscape/webpack-plugin-serve/pull/206#pullrequestreview-568235067

Codez:
https://github.com/Evalon/webpack-plugin-serve/commit/1dd1f378ebd75bdb2d1039c786ee539a4a49a94c#diff-cf84b31417a308f8c05eaf8c08b5caf04ad3fbd8c83f41e3f7546c1955c18f3f

**Comment by subwaymatch** [comment] 2021-03-31 03:51
My workaround is to add `.[runtime]` in the `config.output.hotUpdateMainFilename` option.

Below is my `next.config.js` file:
```javascript
module.exports = {
  future: {
    webpack5: true,
  },
  webpack: (config, { isServer, dev, webpack }) => {
    console.log(`Webpack version: ${webpack.version}`);

    config.output.hotUpdateMainFilename =
      "static/webpack/[fullhash].[runtime].hot-update.json";

    if (!isServer) {
      config.resolve.fallback.fs = false;
    }

    return config;
  },
};
```

This is based on Nextjs' default config (https://github.com/vercel/next.js/blob/cd9bb986eba25006d4872e30eedf24ef5680bc6b/packages/next/build/webpack-config.ts#L898).

**Comment by paescuj** [comment] 2021-06-16 11:54
Can we please reopen this? Still seeing those warnings in Next.js 11.

**Comment by paescuj** [comment] 2021-06-16 15:27
> > Can we please reopen this? Still seeing those warnings in Next.js 11.
> 
> Please open a new issue with a full reproduction.

Will do, thanks!

**Comment by paescuj** [comment] 2021-06-16 17:40
Sorry, I'm not able to provide a full reproduction since I don't know what's causing it. I'll open a new issues when having more information and using workaround from https://github.com/vercel/next.js/issues/19865#issuecomment-810738415 in the meantime.

**Comment by balazsorban44** [comment] 2022-01-28 06:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
