### ISSUE TITLE
getInitialProps not running on client render

### ISSUE THREAD

**Issue by nazmulfahim** [vercel/next.js#27864] opened 2021-08-08 18:12 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.17.1

### What browser are you using?

Chrome , Edge, Firefox

### What operating system are you using?

Windows 10

### How are you deploying your application?

Vercel

### Describe the Bug

getInitialProps is running on the server but not on the client. 

### Expected Behavior

getInitialProps should run whenever router.push or router.replace or next/link component is used.

### To Reproduce

Where the getInitialProps is called. 

```
Login.getInitialProps = async (ctx) => {
  console.log("running");
  return {};
  // return await UnAuthenticatedRoute(ctx);
};

```
This is where Router is called
```

 React.useEffect(() => {
    if (auth) {
      if (auth.user?.verifiCationStatus != "approved") {
        Router.push("/verify");
      }
      return;
    }
    Router.replace("/login");
  }, [auth]);

```

When the link is called

```
<Link href={auth ? "/my-account" : "/login"}>
          <div>
            <div className={style.hamburgerMenuItem}></div>
            <div className={style.hamburgerMenuItem}></div>
            <div className={style.hamburgerMenuItem}></div>
          </div>
        </Link>
```

**Comment by AsazuTaiga** [comment] 2021-08-08 21:01
Hi,

`getInitialProps` is a server side feature. I think it is not a bug.
document: https://nextjs.org/docs/api-reference/data-fetching/getInitialProps

**Comment by masx200** [comment] 2021-08-09 00:34
https://www.nextjs.cn/docs/api-reference/data-fetching/getInitialProps

For the initial page load, getInitialProps will run on the server only. getInitialProps will then run on the client when navigating to a different route via the next/link component or by using next/router. However, if getInitialProps is used in a custom _app.js, and the page being navigated to implements getServerSideProps, then getInitialProps will run on the server.

**Comment by nazmulfahim** [comment] 2021-08-09 06:56
I am not using getInitialProps on custom _app.js nor the page being navigated to uses getServerSideProps

**Comment by nazmulfahim** [comment] 2021-08-09 07:31
getServerSideProps is working but isn't getServerSideProps supposed to run on the server only?

**Comment by ijjk** [comment] 2021-09-18 16:34
The information in https://github.com/vercel/next.js/issues/27864#issuecomment-894883809 is correct and this appears to be working correctly in the latest version of Next.js `v11.1.2` so I'm going to close this as this doesn't appear to be a bug.

**Closed by ijjk** 2021-09-18 16:34 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
