### ISSUE TITLE
[eslint-config-next] Incompatible with eslint@8.0.0

### ISSUE THREAD

**Issue by JustFly1984** [vercel/next.js#29829] opened 2021-10-11 18:40 UTC
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

16.7

### What browser are you using?

irrelevant

### What operating system are you using?

irrelevant

### How are you deploying your application?

irrelevant

### Describe the Bug

Updating to eslint@8.0.0 produces an error:

```sh
Oops! Something went wrong! :(

ESLint: 8.0.0

Error: Cannot read config file: /Users/justfly/projects/tkww/homescreen-v2/node_modules/eslint-config-next/index.js
Error: Failed to patch ESLint because the calling module was not recognized.
If you are using a newer ESLint version that may be unsupported, please create a GitHub issue:
https://github.com/microsoft/rushstack/issues
Referenced from: /Users/justfly/projects/tkww/homescreen-v2/node_modules/eslint-config-next/core-web-vitals.js
    at Object.<anonymous> (/Users/justfly/projects/tkww/homescreen-v2/node_modules/@rushstack/eslint-patch/lib/modern-module-resolution.js:58:19)
    at Module._compile (/Users/justfly/projects/tkww/homescreen-v2/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/Users/justfly/projects/tkww/homescreen-v2/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/justfly/projects/tkww/homescreen-v2/node_modules/@rushstack/eslint-patch/modern-module-resolution.js:1:63)
    at Module._compile (/Users/justfly/projects/tkww/homescreen-v2/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

Currently reverted to 7.32.0

### Expected Behavior

Should support eslint@8

### To Reproduce

update eslint to latest 8.0.0 version in any nextjs project using eslint-config-next

**Comment by linosorice** [comment] 2021-10-11 22:52
same for me

**Comment by stefanprobst** [comment] 2021-10-12 06:48
see  #29770

**Comment by housseindjirdeh** [comment] 2021-10-13 21:19
ESLint 8 is not yet supported (see #29770). I'll submit a patch soon to add support!

**Comment by monsieurnebo** [comment] 2021-11-05 14:11
Same issue over here, hoping to see the PR merging soon 🤞

**Comment by jbergstroem** [comment] 2021-11-10 11:58
You will likely also run into somehting like this:
```
$ yarn run eslint
yarn run v1.22.15
$ eslint --ext=ts,tsx .

Oops! Something went wrong! :(

ESLint: 8.2.0

Error: Rules with suggestions must set the `meta.hasSuggestions` property to `true`.
```

This was fixed in the latest version of `eslint-plugin-react-hooks` released a few hours ago, so next should just update its deps for `eslint-plugin-next`.

**Closed** 2021-11-16 09:18 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 09:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
