### ISSUE TITLE
Router params and path separately 

### ISSUE THREAD

**Issue by vitaliemiron** [vercel/next.js#13100] opened 2020-05-19 15:28 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

I have drupal cms as backend with graphql.
So user can create unlimited nodes starting from root. For example:
site.com/node1
site.com/node2

I have created a page named [slug].tsx and all works fine, but now I also need to get some params from url.
site.com/node1?param=foo
So I didn't find any method to get separately path and params, because 
`useRouter().route or pathname` - will return "[slug]" or full url with params but I need only path and params separately.

## Describe the solution you'd like
`const router = useRouter();
 const path = router.relativePath ;
const param = router.params.param`

## Describe alternatives you've considered

As alternative we can use now
`router.query , join data and obtain path without params`;

**Comment by maxigimenez** [comment] 2020-05-20 07:12
Hi @vitaliemiron, as far as I remember you can access the params using query, this doesn't work for you?

```
const router = useRouter();
console.log(router.query);
```

**Comment by vitaliemiron** [comment] 2020-05-20 10:20
@maxigimenez yes, that works, but every  time I need to join that array, My proposal is to add a method to get full path without queries.

**Comment by Timer** [comment] 2020-09-12 04:39
Closing as there hasn't been any additional support for this feature and it'd unnecessarily bloat the API surface. Thanks for the suggestion!

**Closed by Timer** 2020-09-12 04:39 UTC
Labels: type: feature request

**Comment by balazsorban44** [comment] 2022-01-29 12:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
