### ISSUE TITLE
Interface TransitionOptions not exported

### ISSUE THREAD

**Issue by Dwlad90** [vercel/next.js#28504] opened 2021-08-25 16:11 UTC
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

14.17.4

### What browser are you using?

Chrome

### What operating system are you using?

MacOS Big Sur

### How are you deploying your application?

next start

### Describe the Bug

Typescript complication error: semantic error TS4058: Return type of exported function has or is using name 'TransitionOptions' from external module "node_modules/next/dist/shared/lib/router/router" but cannot be named

### Expected Behavior

Interface TransitionOptions is exported

### To Reproduce

Create NX React library with hook useRouter  and run build
<img width="1281" alt="Screen Shot 2021-08-25 at 19 09 36" src="https://user-images.githubusercontent.com/22377836/130826520-ef107b90-9e26-4ccd-bbca-f6c2b24e31f1.png">

**Comment by ijjk** [comment] 2021-09-18 16:02
I'm gonna close this per above, if you're able to provide a repo with a minimal reproduction we can take a closer look.

**Closed by ijjk** 2021-09-18 16:02 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 19:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
