### ISSUE TITLE
SPA Mode, Export & Dynamic Routes

### ISSUE THREAD

**Issue by ytsruh** [vercel/next.js#49538] opened 2023-05-09 16:43 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Tue Apr 25 04:07:22 PDT 2023; root:xnu-8796.121.2~8/RELEASE_ARM64_T8103
    Binaries:
      Node: 20.0.0
      npm: 9.6.5
      Yarn: 1.22.19
      pnpm: 8.4.0
    Relevant packages:
      next: 13.4.2-canary.3
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/ytsruh/next-dynamic-route

### To Reproduce

1. Clone the repo above
2. Run npm install && npm run build
3. Run npm run serve
4. navigate to 'localhost:3000/post/1' to get a 404 error

### Describe the Bug

Following the docs to export a SPA app, I am unable to get a dynamic route to render in a non-dev envinroment.  Using the instructions on this [link](https://nextjs.org/docs/app/building-your-application/deploying/static-exports#dynamic-fetching-with-client-components ). The docs suggest that this should be absolutely fine.

Edit - I should add that this behaviour existed in the pages directory as well. However I was under the impression that now the app directory is less 'Next' and more plain React that this would be fixed. Dan Ambramov suggested to use a framework for this use case, yet it appears to not work in this use case.

The output of the build does not provide an entry point that can be used to redirect to a dynamic route. If the parameter is valid or invalid a 404 page is always returned. This is counterintuitive to how a SPA should work & I believe this is a fairly basic use case of any SPA.

### Expected Behavior

When a user navigates to a dynamic route a client side router should allow the React component to render. Eg a user should see the client side state (loading, error or result) instead of getting a 404 page.

### How are you deploying your application? (if relevant)

A Go Web server. However the issue persists regardless of how the issue is deployed.

**Comment by qpre** [comment] 2023-05-09 17:52
as of today it is not fixed, you can find the same issue [here](https://github.com/vercel/next.js/issues/48022#issuecomment-1539606159)

**Comment by ytsruh** [comment] 2023-05-09 18:29
Yup, my issue appears to be a duplicate. Thanks for linking. I did look but couldn't find one.

**Comment by timneutkens** [comment] 2023-05-11 12:28
Closing this as duplicate of #48022. Thanks for the detailed description and reproduction though!

**Closed by timneutkens** 2023-05-11 12:28 UTC
Labels: template: bug, area: app
