### ISSUE TITLE
No visual feedback when fast refresh is applied; fast refresh unreliable and cannot be disabled

### ISSUE THREAD

**Issue by dancherb** [vercel/next.js#24589] opened 2021-04-29 06:42 UTC
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Local development

### Describe the Bug

No visual feedback, e.g. a flash or indicator, is available when fast refresh is applied and a content's page reloads after a change. Because fast refrest on next.js is unreliable - and cannot be disabled - this makes development slow and frustrating.

_Sometimes_ on saved changes, a black triangle in the corner seems to show. However, this is rare - and the conditions for it unclear (and an unreliable indicator that you grow to depend on is worse than having no indicator at all).

### Expected Behavior

A page flash or some sort of indicator in the corner to show that fast refresh has been applied. create-react-app instantly reloads the page whenever a change is acknowledged - this is much more helpful and responsive, and makes for quicker development even though it reloads the page every time.

### To Reproduce

Apply alignSelf:"center" to an element. You then have to watch your page for several seconds to see what changes. You never know when the change has actually been applied - whether the style has no effect, or just hasn't been applied by next.js yet. 

Furthermore, you never know if next.js has actually just failed to apply the change, which actually _would_ have an effect, and you now need to reload the page. This happens frequently - and you should not have to regularly apply "border: 1px solid red" on your code to see that next.js is not actually working and needs a page reload.

This is a very slow workflow compared to one that disables fast refresh and causes a full page reload on changes. However, there is no way to disable fast refresh for a project.

**Comment by timneutkens** [comment] 2021-11-17 15:39
Closing as no reproduction was provided.

**Closed by timneutkens** 2021-11-17 15:39 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-27 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
