### ISSUE TITLE
Getting MaxListenersExceededWarning on Typescript project

### ISSUE THREAD

**Issue by alexvilchis** [vercel/next.js#12522] opened 2020-05-05 15:29 UTC
# Bug report

## Describe the bug
I am getting a node warning that I exceeded the listeners limit.

<img width="669" alt="Screen Shot 2020-05-05 at 10 23 33" src="https://user-images.githubusercontent.com/29064411/81083666-7bc83100-8eba-11ea-88b4-b80144012ab8.png">

- OS: macOS
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: ^9.3.6
- Version of Node.js: 12.16.1

## Additional context
My project is a web app that uses typescript, with over 20 pages.

**Comment by timneutkens** [comment] 2020-05-06 09:05
Please provide a clear and concise reproduction in a github repository as asked for in the issue template.

**Comment by lifeiscontent** [comment] 2020-07-01 20:14
@alexvilchis any updates on this? I'm seeing the same issue in our next.js app

**Comment by Timer** [comment] 2020-09-03 02:32
Closing as no reproduction provided.

**Closed by Timer** 2020-09-03 02:32 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-29 14:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
