### ISSUE TITLE
Trying to import non-existing type in framework's source code

### ISSUE THREAD

**Issue by azzazkhan** [vercel/next.js#31171] opened 2021-11-08 19:35 UTC
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

14.18.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

yarn build

### Describe the Bug

The following error occurs while building by Next.js app locally.

```bash
$ yarn build
yarn run v1.22.17
$ next build
Failed to compile.

./node_modules/next/dist/server/config-shared.d.ts:1:15
Type error: '"next/dist/compiled/webpack/webpack"' has no exported member named 'webpack5'. Did you mean 'webpack'?

> 1 | import type { webpack5 } from 'next/dist/compiled/webpack/webpack';
    |               ^
  2 | import { Header, Redirect, Rewrite } from '../lib/load-custom-routes';
  3 | import { ImageConfig, ImageConfigComplete } from './image-config';
  4 | export declare type NextConfigComplete = Required<NextConfig> & {
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

Should run normally

### To Reproduce

Clone the [repository](https://github.com/azzazkhan/antonx-app).

**Comment by ijjk** [comment] 2021-11-08 19:41
Closing as a duplicate of https://github.com/vercel/next.js/issues/30167 

Note: this has been updated in `v12.0.4-canary.0` of Next.js specifically [this PR](https://github.com/vercel/next.js/pull/31140)

**Closed by ijjk** 2021-11-08 19:41 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
