### ISSUE TITLE
Brand new next@12.0.0 app fails to build with {skipLibCheck: false} in tsconfig.json

### ISSUE THREAD

**Issue by utkarshkukreti** [vercel/next.js#30352] opened 2021-10-26 18:45 UTC
### What version of Next.js are you using?

12.0.0

### What version of Node.js are you using?

16.12.0

### What browser are you using?

n/a

### What operating system are you using?

macOS

### How are you deploying your application?

n/a

### Describe the Bug

A brand new app created with `npm create next-app -- --typescript` with `skipLibCheck` set to `false` in tsconfig.json fails to compile. If you just swap out next@12.0.0 with next@11.1.3-canary.68, it compiles.

The error:

```
$ next build
Failed to compile.

./node_modules/next/dist/server/config-shared.d.ts:1:15
Type error: '"next/dist/compiled/webpack/webpack"' has no exported member named 'webpack5'. Did you mean 'webpack'?

> 1 | import type { webpack5 } from 'next/dist/compiled/webpack/webpack';
    |               ^
  2 | import { Header, Redirect, Rewrite } from '../lib/load-custom-routes';
  3 | import { ImageConfig, ImageConfigComplete } from './image-config';
  4 | export declare type NextConfigComplete = Required<NextConfig> & {
error Command failed with exit code 1.
```

### Expected Behavior

It should build.

### To Reproduce

1. Create a new app with `npm create next-app -- --typescript`

2. Open `tsconfig.json` and set `skipLibCheck` to `false`.

3. Run `npm run build`

On 12.0.0, you should get the error I posted above.

Now change the next version to `11.1.3-canary.68` in package.json, run `npm install`, and `npm run build` should work.

**Comment by imtheu** [comment] 2021-10-30 07:54
upgrading to next@12.0.1 here and it is also not working with `"skipLibCheck": true` too. 🤔

**Comment by timneutkens** [comment] 2021-11-02 09:50
Duplicate of #30167

**Closed by timneutkens** 2021-11-02 09:50 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
