### ISSUE TITLE
`rewrites.beforeFiles` should work the same with or without `i18n` configuration.

### ISSUE THREAD

**Issue by LeonardDrs** [vercel/next.js#34371] opened 2022-02-15 12:03 UTC
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT Tue, 01 Feb 2022 21:42:50 +0000
    Binaries:
      Node: 17.3.0
      npm: 8.4.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.11-canary.15
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.11-canary.15

### What version of Node.js are you using?

17.3.0

### What browser are you using?

Firefox

### What operating system are you using?

Linux

### How are you deploying your application?

next start

### Describe the Bug

Rewrites with `beforeFiles` does not work as it used to be with `i18n` enabled. (last known to be working in next@11.1.2)

Back in `next@11.1.2` I used to have this `rewrites` configuration:
```js
  i18n,
  async rewrites() {
    return {
      beforeFiles: [
        {
          source: "/base/:path*",
          destination: "/:path*",
        },
      ],
    };
  },
```
and my urls such as `/base/_next/static/chunks/main.js` used to work. (Use case: CDN shenanigans, CDN are configured to rewrites `assets.xxx.com/foo/*` through `foo.xxx.com/assets/*` for micro frontends.)

Upon upgrading to `next@12.0.10`, this behavior does not work anymore.

This bug does not occurs without `i18n` configured.

I'm providing a PR with tests to confirm the broken behavior, although I've simplified the use case by using an image and not compiled file. Should I add a check for compiled files also?

**Related:** https://github.com/vercel/next.js/issues/23270
**History:** https://github.com/vercel/next.js/issues/23455

### Expected Behavior

`rewrites.beforeFiles` should work the same with or without `i18n` configuration.

### To Reproduce

https://github.com/vercel/next.js/pull/34370

**Comment by kristiankalb** [comment] 2022-03-23 13:15
We are experiencing the same issue.
Our rewrites look like this: 
```
 async rewrites() {
    return {
      beforeFiles: [
        {
             source: `${assetPrefix}/:path*`,
             destination: '/:path*',
        },
      ],
    };
  },
```

`next@12.0.4` seems to introduce it. In versions before that the `rewrites.beforeFiles` above works fine both in projects with and without `i18n`. But from `12.0.4` on they only work in our projects without the `i18n`.

**Comment by 4zuko** [comment] 2022-04-15 23:16
I am facing the same issue that can be reproduced in the following sandbox:

- https://codesandbox.io/s/test-rewrite-app-febe0j

But, it's interesting that I am not able to reproduce the issue in NextJS monorepo running any of these two commands (dev and prod mode):

```shell
next dev ./examples/basic-css/
```

or

```shell
next build ./examples/basic-css/ && next start ./examples/basic-css/
```

**Note:** I've added `next.config.js` configuration into `basic-css` - the same one from the sandbox.

**Comment by indrajithc** [comment] 2022-06-05 06:49
I am facing the same issue, needs to be fixed ASAP

for the time being found a workaround using [_middleware](https://nextjs.org/docs/advanced-features/middleware)

```js script
import { NextResponse } from "next/server";

const assetPrefixRegEx = new RegExp(`^${assetPrefix}`);

export default function middleware(request) {
  const response = NextResponse.next();
  if (assetPrefixRegEx.test(request.nextUrl.pathname)) {
    request.nextUrl.pathname = request.nextUrl.pathname.replace(assetPrefixRegEx, "");
    console.log({ f: request.nextUrl.pathname });
    return NextResponse.rewrite(request.nextUrl);
  }
  return response;
}
```

**Comment by hanneslund** [comment] 2022-06-09 13:26
This should work by doing something like this 👍 
```js
{
  source: '/:locale/base/:path*', // ignore locale
  destination: '/:path*',
  locale: false,
}
```

**Comment by ijjk** [comment] 2022-06-13 02:50
Closing as the above has been documented in https://github.com/vercel/next.js/pull/37581 and we also added regression tests for this.

**Closed by ijjk** 2022-06-13 02:50 UTC
Labels: template: bug, area: I18n
