### ISSUE TITLE
Next/image displays the same images twice in an infinite scroll

### ISSUE THREAD

**Issue by dbaweb** [vercel/next.js#28171] opened 2021-08-16 15:02 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

windows

### How are you deploying your application?

N/A

### Describe the Bug

I have created an infinite list with cards that each contain an image but sometimes two images are the same in two different cards even though the src is correct. 

I don't know why, maybe the cache? 

Is there a solution to this problem? I tried to put a unique key to each image but that didn't solve the problem. When I use <img> it works. But I would like to understand and use next/image to take advantage of all the benefits it can offer me.

### Expected Behavior

View related images 

### To Reproduce

Refer to the screenshot below to see the bug

![Capture](https://user-images.githubusercontent.com/10218039/129584878-d49b14f4-a7e5-4dde-8b4d-9796d8da9c7c.PNG)

![image](https://user-images.githubusercontent.com/10218039/129584256-f35462af-8f67-4539-bb60-cc16174c2f8c.png)

**Comment by zachguo** [comment] 2021-08-19 05:41
possible duplicate of https://github.com/vercel/next.js/issues/23518

**Comment by luizeboli** [comment] 2021-08-19 16:21
It's fixed in v11.1.x. Can you test with the latest version?

**Comment by JanKaifer** [comment] 2022-11-29 16:26
It looks loke this was already fixed.

**Closed by JanKaifer** 2022-11-29 16:26 UTC
Labels: template: bug
