### ISSUE TITLE
Error processing favicon in Next.js 15

### ISSUE THREAD

**Issue by AvishakeAdhikary** [vercel/next.js#71825] opened 2024-10-24 19:37 UTC
### Link to the code that reproduces this issue

https://github.com/AvishakeAdhikary/blog

### To Reproduce

1. Upgrade to Next.js 15.0.1.
2. Run `npm run dev` in the project directory.
3. Observe the error regarding the favicon processing.

### Current vs. Expected behavior

- **Current Behavior:** 
  When running the development server, the following error occurs:
  ```plaintext
  ⨯ ./app/favicon.ico
  Processing image failed
  unable to decode image data

  Caused by:
  - Format error decoding Ico: The PNG is not in RGBA format!
  ```
  
![Screenshot 2024-10-25 004235](https://github.com/user-attachments/assets/df2b7f7b-a238-4c01-910b-e0caa9a37b8d)

- **Expected Behavior:**
The favicon should load without errors, allowing the application to start correctly.

### Provide environment information

```bash
Operating System:
  Platform: Windows
  Arch: x64
  Version: Windows 11

Binaries:
  Node: v20.13.1
  npm: 10.9.0

Relevant Packages:
  next: 15.0.1
  eslint-config-next: 15.0.1
  react: 19.0.0-rc-69d4b800-20241021
  react-dom: 19.0.0-rc-69d4b800-20241021
  typescript: ^5

Next.js Config:
{
    images: {
      domains: ['raw.githubusercontent.com'],
    },
}
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

- This issue occurs locally during development.
- The favicon is expected to be in PNG format, but it seems to be causing format errors.
- I have attempted to clear the browser cache, but the issue persists.

**Comment by samcx** [comment] 2024-10-25 23:07
This is a duplicate of → https://github.com/vercel/next.js/issues/71609

**Closed** 2024-10-25 23:07 UTC
Labels: bug
