### ISSUE TITLE
Next js downloading duplicate chunks on their website https://nextjs.org/

### ISSUE THREAD

**Issue by rahul3103** [vercel/next.js#23406] opened 2021-03-25 19:08 UTC
### What example does this report relate to?

https://nextjs.org/

### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

14

### What browser are you using?

chrome

### What operating system are you using?

macOS

### How are you deploying your application?

vercel

### Describe the Bug

Open https://nextjs.org/. Check network tab and sort by size.
The page index.js is getting downloaded twice, all the chunks are getting downloaded twice.

### Expected Behavior

Chunks shouldn't get duplicated

### To Reproduce

Open https://nextjs.org/ and check Network Tab. Sort by size.

<img width="1674" alt="Screenshot 2021-03-26 at 12 36 02 AM" src="https://user-images.githubusercontent.com/10813252/112530421-6c9ceb00-8dcc-11eb-8096-5da2678ff405.png">

**Comment by MonstraG** [comment] 2021-04-03 10:54
![image](https://user-images.githubusercontent.com/17963791/113476412-d2583980-9494-11eb-9f36-fb51788d5191.png)

For some reason, can reproduce this in chrome 89.0.4389.114 but not firefox 88.0b6

**Comment by ijjk** [comment] 2021-04-28 02:31
This is the expected behavior currently as first is from prefetching and then the second is from the actual script tag being added. The script tag leverages the same request as the prefetch so doesn't transfer the data a second time. 

I'm going to close this as it doesn't appear to be a bug.

**Closed by ijjk** 2021-04-28 02:31 UTC
Labels: template: bug, type: example

**Comment by balazsorban44** [comment] 2022-01-28 10:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
