### ISSUE TITLE
Re-exported getStaticPaths and getStaticProps doesn't work on navigation

### ISSUE THREAD

**Issue by likerRr** [vercel/next.js#17500] opened 2020-09-30 22:14 UTC
# Bug report

## Describe the bug

I want to encapsulate `getStaticPaths` and `getStaticProps` logic into a separate file and then re-export them, so the page file exports these functions. And from the first view everything works well - pages render after direct navigation in browser (or just after reloading a page). But when I try navigating via the `Link` component, I get an error.

This also works vice versa, if you open codesandbox on the `/test1` url (it renders fine) and then click `back` link, you will get an error.

The error disappears if I move `getStaticPaths` and `getStaticProps` functions from `helpers.js` to page files.

It reproduces in dev and prod modes.

As far as I understood, nextjs sees `getStaticPaths` and `getStaticProps` on the initial page (page I load first), but doesn't see these functions on a page I navigate to.

## To Reproduce

Follow the [codesandbox example](https://codesandbox.io/s/data-fetching-incapsulation-zp1qx)

1. Click on any post
or
2. Type `/test1` in a browser and click the `back` link

## Expected behavior

I see a page instead of an error

## System information

- Version of Next.js: 9.5.3

**Comment by lfades** [comment] 2020-10-01 02:53
@likerRr What you're doing is currently not allowed by our data fetching methods 🙅‍♂️ 

Next.js needs a way to know what code belongs to the browser and what code belongs to the server (Node.js). In your code both `getStaticProps` and `getStaticPaths` aren't being removed from the browser build, which most likely means Next.js doesn't can't distinguish them.

You can see how code elimination works in this page: https://next-code-elimination.vercel.now.sh/.

✔️ This is a good and recommended way of using helpers inside Next.js data fetching methods:

```js
export function getStaticProps() {
  return runHelper()
}
```

❌ This is is not recommended and won't work:

```js
export const { getStaticProps } = myUtil();
```


I'm closing the issue because this is not a bug or a problem with Next.js.

**Closed by lfades** 2020-10-01 02:53 UTC

**Comment by likerRr** [comment] 2020-10-01 06:27
@lfades thank you for response. 

I reported this as a bug, because this behavior worked in next@9.4.0 ([codesandbox](https://codesandbox.io/s/data-fetching-incapsulation-forked-qege1)) without any restrictions. And in the further releases there were not any changelogs about such a pattern.

**Comment by lfades** [comment] 2020-10-01 15:53
We mention this in docs here: https://nextjs.org/docs/basic-features/data-fetching#write-server-side-code-directly and link to the [tool](https://next-code-elimination.vercel.now.sh/) I shared above. That tool has been working the same way as it was before, if your current pattern worked before it wasn't because we were supporting it.

**Comment by balazsorban44** [comment] 2022-01-29 10:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
