### ISSUE TITLE
NextJS UI Broken on Linux! 

### ISSUE THREAD

**Issue by LyhourChhen** [vercel/next.js#20809] opened 2021-01-06 08:54 UTC
**What version of Next.js are you using?**

latest - 10.0.4

**What version of Node.js are you using?**

12.16.3

**What browser are you using?**

Chrome

**What operating system are you using?**

Linux - Alpine

**How are you deploying your application?**

Docker with Next Build + Next Start

**Describe the Bug**

NextJS UI is broken on Linux-Alpine that I build & run with docker, I also try to run and build on others distribution like ubuntu and Debian the UI is still broken, but it completely fine on MacOS and Window OS.

**Expected Behavior**

n/a

**To Reproduce**

n/a

![Screenshot](https://i.ibb.co/q5b8kgr/Screen-Shot-2021-01-06-at-3-40-18-PM.png)

**Comment by timneutkens** [comment] 2021-01-06 09:17
This issue is not actionable. Closing as per the issue template.

**Closed by timneutkens** 2021-01-06 09:17 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
