### ISSUE TITLE
PWA not working in production

### ISSUE THREAD

**Issue by GeoBrodas** [vercel/next.js#30692] opened 2021-10-31 11:50 UTC
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

14.17.4

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

I implemented PWA using `next-pwa` in my application, and went through all the necessary steps. ( creating service worker, next-config file, etc ). Everything looks fine in development  - "**Install app**" option pops up . But in production it just seems to disappear, and not even shows the install option

### Expected Behavior

PWA pop-up should both appear in development as well as in production.

### To Reproduce

- Install `next-pwa`
- Generate manifest ( using [Simicart](https://www.simicart.com/manifest-generator.html) ).
- Creating `_document.js` and adding the necessary links.
```js
import Document, { Html, Head, Main, NextScript } from "next/document";

class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head>
          <link rel="manifest" href="/manifest.json" />
          <link rel="apple-touch-icon" href="/icon.png"></link>
          <meta name="theme-color" content="#fff" />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```
- Configure next-config file
```js
const withPWA = require("next-pwa");

module.exports = withPWA({
  pwa: {
    dest: "public",
    register: true,
    skipWaiting: true,
  },
});
```
- Add following to `.gitginore`
```
# PWA files
**/public/sw.js
**/public/workbox-*.js
**/public/worker-*.js
**/public/sw.js.map
**/public/workbox-*.js.map
**/public/worker-*.js.map
```
Also followed according to [Nextjs pwa example](https://github.com/vercel/next.js/tree/canary/examples/progressive-web-app)

For more details visit this [repo](https://github.com/GeoBrodas/adalat-court-management)

Screenshots from Chrome dev tools - 
![image](https://user-images.githubusercontent.com/68821192/139581812-0ddab0db-916e-4a8e-8f39-1d9aeed0d390.png)

Production link - https://adaalat.vercel.app

**Comment by thinhtran3588** [comment] 2021-11-01 09:09
I have the same issue. Changed back to next 11.1.2 then it worked again. Not sure what's the root cause.

**Comment by GeoBrodas** [comment] 2021-11-01 09:23
Yeah I thought so, it's something with the latest release. I'm sure they will fix it.

**Comment by GuillaumeBe** [comment] 2021-11-01 17:38
Same issue here. I spent many hours without being able to fix it

**Comment by julioflima** [comment] 2021-11-03 11:51
Same here, reverted to 11 to make it work again.

There is an example that can easily to reproduced `yarn create next-app --example progressive-web-app progressive-web-app`. The example comes with version "latest".

Follow in below what happens in the lighthouse:
![Screenshot from 2021-11-03 08-40-04](https://user-images.githubusercontent.com/17098382/140054827-de47c900-be8e-4160-b988-87a26f63c608.png)

**Comment by dev-juju** [comment] 2021-11-07 22:50
Looks like something to do with default workbox config 

<img width="724" alt="Screen Shot 2021-11-08 at 12 21 34 AM" src="https://user-images.githubusercontent.com/20828496/140664785-819cb7e2-50f2-41b6-8aef-89e8833a5436.png">

**Comment by adikari** [comment] 2021-11-08 12:49
refreshing the page seems to enable the service worker. Would be good to see a fix for this.

**Comment by wendellhu95** [comment] 2021-11-09 06:54
Working on this.

**Comment by jovenlumaas** [comment] 2021-11-10 11:34
It's my current problem too. But when I tried uncommenting the following on my .gitignore file then it's working on production in vercel. I don't know why.

# PWA
# **/public/sw.js
# **/public/workbox-*.js
# **/public/worker-*.js
# **/public/sw.js.map
# **/public/workbox-*.js.map
# **/public/worker-*.js.map

**Comment by jovenlumaas** [comment] 2021-11-10 11:35
It's my current problem too. But when I tried uncommenting the following on my .gitignore file then it's working on production in vercel. I don't know why.

**/public/sw.js
**/public/workbox-*.js
**/public/worker-*.js
**/public/sw.js.map
**/public/workbox-*.js.map
**/public/worker-*.js.map

**Comment by Encang-Cutbray** [comment] 2021-11-15 05:50
I have same problem how to solve the console error and enable pwa on vercel

**Comment by Encang-Cutbray** [comment] 2021-11-15 07:16
> Same here, reverted to 11 to make it work again.
> 
> There is an example that can easily to reproduced `yarn create next-app --example progressive-web-app progressive-web-app`. The example comes with version "latest".
> 
> Follow in below what happens in the lighthouse: ![Screenshot from 2021-11-03 08-40-04](https://user-images.githubusercontent.com/17098382/140054827-de47c900-be8e-4160-b988-87a26f63c608.png)

Is it running when deploy with vercel

**Comment by DevAndromeda** [comment] 2021-11-16 15:46
same problem for me as well

**Comment by pablodelfante** [comment] 2021-11-16 23:11
Same problem!

**Comment by NachoVazquez** [comment] 2021-11-17 21:40
Any news on this? Having the same problem!

**Comment by c7nasr** [comment] 2021-11-17 23:40
Same here!

**Comment by faturachmanyusup** [comment] 2021-11-18 20:04
Yeah, me too. I'm using NextJS latest. It work on my local.

**Comment by ats1999** [comment] 2021-11-21 07:49
Me, too having to same isue

**Comment by faturachmanyusup** [comment] 2021-11-21 10:44
This config saves me

https://github.com/shadowwalker/next-pwa/issues/295#issuecomment-972302942

**Comment by GeoBrodas** [comment] 2021-11-21 13:06
> This config saves me
> 
> [shadowwalker/next-pwa#295 (comment)](https://github.com/shadowwalker/next-pwa/issues/295#issuecomment-972302942)

Yes this worked for me! Damn

**Closed** 2021-11-23 16:17 UTC
Labels: good first issue, area: examples

**Comment by thinhtran3588** [comment] 2021-11-25 13:26
I believe the issue hasn't been fixed yet, only using the config from the above comment as a work around but it's not a proper fix @lfade
![Screen Shot 2021-11-25 at 20 22 17](https://user-images.githubusercontent.com/7576583/143449688-5b48cddb-b187-4994-bc3c-b99ff2be40d7.png)
s

**Comment by adikari** [comment] 2021-11-25 22:48
yep. I am still having the same issues after upgrading. only updating the config to ignore middleware works.

**Comment by wendellhu95** [comment] 2021-11-26 03:04
Hi @thinhtran3588  @adikari. The fix is just a update to the Next.js pwa template. If you have already created a project using the template, just upgrading Next.js wouldn't help. You should use a new version of next-pwa as the PR did.

**Comment by adikari** [comment] 2021-11-26 08:49
@wendellhu95 makes sense. Pretty sure I updated next pwa too. I am fine using the suggested config and it's working fine for now. Thank you

**Comment by balazsorban44** [comment] 2022-01-27 07:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
