### ISSUE TITLE
`next export` static pages are unable to be loaded when deployed to github pages

### ISSUE THREAD

**Issue by ky28059** [vercel/next.js#27302] opened 2021-07-19 18:51 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

16.0.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next export && gh-pages -d out

### Describe the Bug

A `next` project deployed using `next export` on github pages will 404 when trying to load css and js.
![image](https://user-images.githubusercontent.com/60120929/126209014-96a61147-6ea7-4ff9-ad32-3feb688c9006.png)
The deploy script I used for this project is 
```shell
rimraf node_modules/.cache && next build && next export && touch out/.nojekyll && gh-pages -d out
```
which is a modified version of the [`gh-pages` example's deploy script](https://github.com/vercel/next.js/blob/canary/examples/gh-pages/package.json)
```shell
rm -rf node_modules/.cache && next build && next export && touch out/.nojekyll && git add out/ && git commit -m \"Deploy Next.js to gh-pages\" && git subtree push --prefix out origin gh-pages
```

### Expected Behavior

I expect the js and css to load properly when deploying to github pages.

### To Reproduce

```shell
npx create-next-app -e with-tailwindcss my-project
cd my-project
npm install gh-pages
```
In package.json, add the deploy script:
```diff
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
+   "deploy": "rimraf node_modules/.cache && next build && next export && touch out/.nojekyll && gh-pages -d out"
  },
```
Initiate a github repository and then run `npm run deploy`; `touch` and `rimraf` might need to be downloaded first.
[Affected repository](https://github.com/ky28059/ky28059.github.io)

**Comment by ijjk** [comment] 2021-07-19 19:01
Hi, this appears to be a duplicate of https://github.com/vercel/next.js/issues/3335 so I'm gonna close this one.

**Closed by ijjk** 2021-07-19 19:01 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
