### ISSUE TITLE
next/image having specificity issues with Tailwind Typography

### ISSUE THREAD

**Issue by leerob** [vercel/next.js#19964] opened 2020-12-08 15:15 UTC
# Bug report

## Describe the bug

When using Tailwind Typography and the `prose` element, it automatically adds margin-top and bottom to the `img` element. This messes up the responsive-ness of the `next/image` component.

## To Reproduce

I've set a width and height
![image](https://user-images.githubusercontent.com/9113740/101501610-8f96b280-3935-11eb-96f8-d187668d501d.png)

But it's displayed wrong
![image](https://user-images.githubusercontent.com/9113740/101501515-73931100-3935-11eb-9b8a-52c8bff83666.png)

Toggling these styles fixes it.
![image](https://user-images.githubusercontent.com/9113740/101501490-6a09a900-3935-11eb-85f2-20bf12fca96d.png)

## Expected behavior

I'd be great if we can build this into `next/image` to prevent users from hitting issues with Tailwind Typography.

## Screenshots

See repo.

## System information

- OS: Mac
- Browser: Chrome
- Version of Next.js: 10.0.3
- Deployment: next start and Vercel

**Comment by erhankaradeniz** [comment] 2020-12-09 08:11
Hi Lee, since tailwind 2.0 and the update on the typography plugin you are able to update styles that are applied via prose through your tailwind.config.js. I can imagine it being something like this:

```
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      typography: {
        DEFAULT: {
          css: {
            img: {
              marginTop: 0,
              marginBottom: 0
            },
          },
        },
      }
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
```

But still it would be nice for people who don't know about this feature that next/image fixes it.

**Comment by leerob** [comment] 2020-12-09 12:46
Yep, that's what I ended up doing to fix it 👍 But it'd be great if we make Next.js handle this to prevent others from having issues.

**Comment by brandonpittman** [comment] 2020-12-09 13:21
Finally! I just wasted 45 minutes trying to figure out what was wrong with my images.

**Comment by brandonpittman** [comment] 2020-12-09 13:28
@leerob Worth mentioning that you need to do this for other `prose` sizes.

```
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      typography: {
		DEFAULT: {
          css: {
            img: {
              marginTop: 0,
              marginBottom: 0
            },
          },
        },
        lg: {
          css: {
            img: {
              marginTop: 0,
              marginBottom: 0
            },
          },
        },
      }
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
```

**Comment by michrome** [comment] 2020-12-09 22:06
I think this is a duplicate of https://github.com/vercel/next.js/issues/19817 😀

**Closed** 2020-12-29 17:34 UTC
Labels: kind: bug, point: 2

**Comment by balazsorban44** [comment] 2022-01-29 00:11
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
