### ISSUE TITLE
notFound in fallback:true causes an unexpected error in Vercel

### ISSUE THREAD

**Issue by teppeis** [vercel/next.js#20710] opened 2021-01-03 13:53 UTC
# Bug report

## Describe the bug

If `getStaticPaths()` returns `{fallback: true}` and `getStaticProps()` returns `{notFound: true}`, "An unexpected error has occurred." is displayed in vercel.

## To Reproduce

1. Go to https://nextjs-error-handling.vercel.app/users-ssg-fb-true/105
2. See error "An unexpected error has occurred."

- repository: https://github.com/teppeis/nextjs-error-handling
- code: https://github.com/teppeis/nextjs-error-handling/blob/10eae808c8145b5e74dd331ab65a9d383364192a/pages/users-ssg-fb-true/%5Bid%5D.tsx

## Expected behavior

404 default error page

## Screenshots

<img width="1501" alt="スクリーンショット 2021-01-03 22 47 41" src="https://user-images.githubusercontent.com/26476/103480123-b30a2b80-4e15-11eb-95cb-3f2f3e7627c2.png">

## System information

- OS: macOS
- Browser: chrome
- Version of Next.js: 10.0.4
- Version of Node.js: 14.15.3
- Deployment: Vercel

## Additional context

Same error occurs in local dev mode. No errors in local production mode (build && start).
Also no errors in fallback:blocking.

### Work around

adding custom 404 error page (`pages/404.tsx`)

**Comment by ijjk** [comment] 2021-01-03 18:52
Hi, this is fixed in the latest version of Next.js `v10.0.5-canary.8`, please update and give it a try!

**Closed** 2021-01-04 09:49 UTC
Labels: template: bug

**Comment by teppeis** [comment] 2021-01-04 12:38
@ijjk @timneutkens 
Thanks. I've confirmed in v10.0.5-canary.8.
Also https://github.com/vercel/next.js/issues/20674 is fixed too.

**Comment by teppeis** [comment] 2021-01-04 12:46
Probably this was fixed in https://github.com/vercel/next.js/pull/20594 (landed in v10.0.5-canary.4)

**Comment by timneutkens** [comment] 2021-01-04 12:54
> @ijjk @timneutkens
> Thanks. I've confirmed in v10.0.5-canary.8.
> Also #20674 is fixed too.

Thanks! Posted a reply there to make sure they check as well 👍

**Comment by balazsorban44** [comment] 2022-01-28 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
