### ISSUE TITLE
Remove amp-only components from bundle

### ISSUE THREAD

**Issue by dpuscher** [vercel/next.js#9008] opened 2019-10-09 15:10 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

At the moment, when you use the amp hybrid mode, your frontend bundle also contains the code and components that are only used in amp mode, although they never are needed.

**Example:**
```
export default () => (
  useAmp() ? <AmpComponent /> : <WebComponent />
);
```

Although `AmpComponent` is never used on the "normal" version of the page it is still present in the final bundle.

## Describe the solution you'd like

The bundle should not contain any code that is specific for the amp version of the page.

## Describe alternatives you've considered

At the moment this can be achieved by setting the amp component to dynamic:
```
const AmpComponent = dynamic(() => import("./AmpComponent"));

export default () => (
  useAmp() ? <AmpComponent /> : <WebComponent />
);
```
This works quite well when having separated components for AMP and web but not, when just having small changes inside your component.

**Comment by Timer** [comment] 2020-09-12 04:13
Hi! Thanks for the feature request but I'm going to close this for now because it's not possible with today's bundlers or React itself. We have other issues that spec this more generally—for any conditional statement.

We'll revisit this in a webpack 5/6 and React Concurrent Mode future!

**Closed by Timer** 2020-09-12 04:13 UTC
Labels: type: feature request

**Comment by c0b41** [comment] 2020-09-12 07:21
@Timer can we move instead Discussions

**Comment by balazsorban44** [comment] 2022-01-29 12:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
