### ISSUE TITLE
postcss configuration in package.json is not respected in Turbopack

### ISSUE THREAD

**Issue by BB-19** [vercel/next.js#62805] opened 2024-03-04 11:03 UTC
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/turbopack-tw-bug-933t2x

### To Reproduce

1. Start `apps/web` with `npm run dev` to see tailwind working fine without Turbopack.
2. Start `apps/web` with `npm run dev-turbo` to see missing styles when running with Turbopack.

## Current
Tailwindcss seems to be broken in this monorepo setup when using Turbopack. No error messages are displayed but the styles are missing. Without the --turbo flag, this setup works just fine.

## Expected
Tailwindcss should work fine in this monorepo when using Turbopack.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.1.2-canary.3 // Latest available version is detected (14.1.2-canary.3).
  eslint-config-next: 14.1.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

<sub>[PACK-2657](https://linear.app/vercel/issue/PACK-2657/turbopack-tailwindcss-not-working-in-monorepo)</sub>

**Comment by ForsakenHarmony** [comment] 2024-03-05 02:07
There is a warning, but unfortunately it never gets shown to the user

The issue is that the postcss config is inside package.json which is currently not supported

**Comment by timneutkens** [comment] 2024-10-04 09:49
This has been fixed in https://github.com/vercel/next.js/pull/68679. Thanks for the report!

**Closed by timneutkens** 2024-10-04 09:49 UTC
Labels: bug, Turbopack, linear: turbopack
