### ISSUE TITLE
Doing res.end in getServerSideProps hangs http clients like curl, axios, http etc.

### ISSUE THREAD

**Issue by HelloKashif** [vercel/next.js#32835] opened 2021-12-27 02:53 UTC
### What version of Next.js are you using?

12

### What version of Node.js are you using?

16

### What browser are you using?

Chrome

### What operating system are you using?

Mac

### How are you deploying your application?

Vercel

### Describe the Bug

THIS HAPPENS IN DEV ONLY `yarn dev`
While doing a `res.end` in getServerSideProps returns correct data to the browser it doesn't work with http clients like curl

Example 
1. Do a res.end in your getServerSideProps code
```js
export const getServerSideProps = ({res})=>{
  res.setHeader("Content-Type", "text/plain")
  res.write("Hello")
  res.end()
  return { props: {} }

}
```

2. Try calling this page endpoint via curl eg: `curl http://localhost:3000/test-page` (Or try via axios via node script)
Result: curl/axios just hangs indefinitely trying to fetch this request which doing the same in browser (or axios in a browser) works fine

### Expected Behavior

If the response has ended then any http compliant client should be able to resolve the result. But seems the NextJs router doesn't finish the request for non-browser clients.

### To Reproduce

Here is a reproducible project, try yarn dev and then do a `curl "http://localhost:3000/hello"`
https://github.com/HelloKashif/nextjs-issue

**Comment by balazsorban44** [comment] 2021-12-27 11:16
Duplicate of #32824

**Closed by balazsorban44** 2021-12-27 11:17 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 01:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
