### ISSUE TITLE
Next.js adds `"exclude": ["node_modules"]` to my `tsconfig.json`

### ISSUE THREAD

**Issue by nbouvrette** [vercel/next.js#40556] opened 2022-09-14 17:55 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.0
      npm: 8.19.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.5
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

N/A

### Describe the Bug

When I compiled, without any `exclude` option in my `tsconfig.json` file, Next.js automatically adds `"exclude": ["node_modules"]`:

```console
info  - Checking validity of types .We detected TypeScript in your project and reconfigured your tsconfig.json file for you. Strict-mode is set to false by default.

The following suggested values were added to your tsconfig.json. These values can be changed to fit your project's needs:

        - exclude was set to ['node_modules']
```

If I remove it, it will just add it back.

This configuration is unnecessary because is it already included in the [default values](https://www.typescriptlang.org/tsconfig#exclude).

This also is the default config when running `npx create-next-app@latest --ts`

### Expected Behavior

I would expect, that if I do not have any `exclude` statement, Next.js would not add a configuration that overlaps with default values.

I would also expect `npx create-next-app@latest --ts` to not contain this configuration.

### Link to reproduction

npx create-next-app@latest --ts

### To Reproduce

1) `npx create-next-app@latest --ts`
2) remove the exclude config from `tsconfig.json`
3) `npm run build`

**Comment by balazsorban44** [comment] 2022-09-15 12:13
Duplicate of #39921

**Closed by balazsorban44** 2022-09-15 12:13 UTC
Labels: template: bug
