### ISSUE TITLE
Warning: Invalid prop `className` supplied to `React.Fragment`

### ISSUE THREAD

**Issue by pomber** [vercel/next.js#19062] opened 2020-11-11 15:40 UTC
# Bug report

## Describe the bug

When using `React.Fragment` like this: 

```jsx
import React from "react";

export default function Page() {
  const X = React.Fragment;
  return (
    <div>
      <style jsx global>{`
        html {
          margin: 0;
        }
      `}</style>
      <X>Hello</X>
    </div>
  );
}
```

You get this warning from React in the console:
```
Warning: Invalid prop `className` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.
```

## To Reproduce

CodeSandbox: https://codesandbox.io/s/adoring-wescoff-udecy?file=/pages/index.js

Tested with Next 9.6.0 and 10.0.1

Feel free to transfer the issue to the styled-jsx repo if it makes more sense

**Comment by adebiyial** [comment] 2020-11-12 18:37
Hey @pomber, I suppose this is expected - in some ways - since `React.Fragment` isn't actually a component, it returns `null`

**Comment by cascandaliato** [comment] 2020-11-14 10:51
My understanding of the issue:
- This problem is not specific to Next.js but exists in styled-jsx already (https://codesandbox.io/s/github/cascandaliato/vercel-nextjs-19062).
- `className` should not be injected into `<></>` or `<React.Fragment></React.Fragment>` because there is nothing to style, and React complains about it (apparently only in development mode).
- styled-jsx injects the `className` prop in any JSX tag that looks like a legit primitive HTML tag (`div`, `p`, etc.) or whose name has been bound in the same scope, like the `X` in the example (probably added to support dynamically imported components; see [styled-jsx/src/babel.js#L43](https://github.com/vercel/styled-jsx/blob/eac1703467d941f3efc501a777436e63dbc36393/src/babel.js#L43)).
- It doesn't inject anything into `<React.Fragment>` because there is (usually) no assignment for `React.Fragment`, only the `import React` at the top of the file.
- It also works with plain `<>` fragments because they have their own node type in Babel and the code manages them differently ([styled-jsx/src/babel.js#L256](https://github.com/vercel/styled-jsx/blob/eac1703467d941f3efc501a777436e63dbc36393/src/babel.js#L256)).
- It would even work if you moved the `X` declaration outside the function scope (example: https://codesandbox.io/s/naughty-davinci-5wc7x?file=/pages/index.js).
- In the example you provided, the library assumes that `X` is a regular component and it doesn't know that it is actually a `React.Fragment`.
- Based on my very limited knowledge of Babel,  I don’t think it is possible for any plugin to manage this case properly at transpile time. For example, what should it do in this case?
    ```
    const X = Math.random() > 0.5 ? 'div' : React.Fragment
    ```

As an aside, I had a blast reading and learning about transpilation and ASTs yesterday night, and these are some useful resources I found along the way:
- https://lihautan.com/step-by-step-guide-for-writing-a-babel-transformation/
- https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md
- https://astexplorer.net/#/gist/4a294e23cdab5531c843009749df86c9/6ed25625d0d382b3308739dbd79ecbd015c30570

**Comment by Kevinfoss** [comment] 2020-11-14 20:50
Stop now

**Comment by KarenEfereyan** [comment] 2020-11-15 18:15
Shouldn't React.Fragment be an alternative to div as a wrapper when returning multiple elements so that babel can parse it?

**Comment by lachlanjc** [comment] 2020-11-18 00:30
This issue is already being tracked https://github.com/vercel/styled-jsx/issues/648 & is part of that library 👍

**Comment by Timer** [comment] 2020-11-18 14:56
Closing as duplicate of the styled-jsx issue. Thanks!

**Closed by Timer** 2020-11-18 14:56 UTC
Labels: good first issue, kind: bug

**Comment by adebiyial** [comment] 2020-11-19 13:51
> Shouldn't React.Fragment be an alternative to div as a wrapper when returning multiple elements so that babel can parse it?

Not necessarily, it doesn't actually render any element. It only lets you render multiple elements without React yelling at you. Technically, no element exists for it.

**Comment by balazsorban44** [comment] 2022-01-29 03:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
