### ISSUE TITLE
Can't run basic app with React 18 and Next 12

### ISSUE THREAD

**Issue by SylvainGarrigues** [vercel/next.js#32129] opened 2021-12-04 17:55 UTC
### What version of Next.js are you using?

12.0.6

### What version of Node.js are you using?

17.2.0

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying your application?

npm run dev

### Describe the Bug

```
% npm run dev                                      

> dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - SWC minify beta enabled. https://nextjs.org/docs/messages/swc-minify-enabled
info  - Using the createRoot API for React
warn  - You are using an unsupported prerelease of 'react-dom' which may cause unexpected or broken application behavior. Continue at your own risk.
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /path/to/my/project/node_modules/node_modules/react/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.mod._resolveFilename (/path/to/my/project/node_modules/next/dist/build/webpack/require-hook.js:171:28)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at getPackagePath (/path/to/my/project/node_modules/next/dist/build/webpack-config.js:551:41)
    at Object.getBaseWebpackConfig [as default] (/path/to/my/project/node_modules/next/dist/build/webpack-config.js:567:9) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

### Expected Behavior

Expected successful dev deployment

### To Reproduce
npx create-next-app@latest
then as per https://nextjs.org/docs/advanced-features/react-18
npm install next@latest react@beta react-dom@beta

```
package.json
{
  "name": "mypackage",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^12.0.6",
    "react": "^18.0.0-beta-4729ff6d1-20211202",
    "react-dom": "^18.0.0-beta-4729ff6d1-20211202"
  },
  "devDependencies": {
    "eslint": "8.4.0",
    "eslint-config-next": "12.0.5"
  }
}

next.config.js
module.exports = {
  reactStrictMode: true,
  swcMinify: true,
  experimental: {
    concurrentFeatures: true,
    serverComponents: true,
  },
}

```

**Comment by brc-dd** [comment] 2021-12-04 18:19
It's a known issue (#31514) with Node v17.

**Comment by balazsorban44** [comment] 2021-12-05 14:10
Duplicate of #31514

**Closed** 2021-12-05 14:10 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-27 06:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
