### ISSUE TITLE
NotFound not working with Metadata

### ISSUE THREAD

**Issue by TCM-dev** [vercel/next.js#46619] opened 2023-03-01 12:35 UTC
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:06:26 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8112
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.2-canary.1
      eslint-config-next: 13.2.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/TCM-dev/nextjs-error-handling-bug

### To Reproduce

- Starts the project with `npm run dev`
- Go to the page `http://localhost:3000/user/azer`
- Notice the 404 page is the default nextjs one instead of not-found.tsx in the same directory.
- Open user/[username]/page.tsx file
- Comment the generateMetadata function
- Go back to the page `http://localhost:3000/user/azer`
- Notice the 404 page is now the not-found.jsx file

I noticed this did not happen in root of app directory, the bug occured once I was using a dynamic segment, I did not try with a static segment.

### Describe the Bug

Default 404 template is used instead of the one provided in a not-found.tsx file as soon as a generateMetadata function is present in a page.tsx file

### Expected Behavior

The not-found.tsx file should be used to render the notFound error no matter what

**Comment by whoisandy** [comment] 2023-03-02 19:27
Also, does not seem to be working when the `not-found.tsx` file is placed at the root of `/app` directory.

**Comment by kaceycleveland** [comment] 2023-03-19 19:30
Confirmed that this is still happening on the recent canary release `13.2.5-canary.8`

**Comment by kaceycleveland** [comment] 2023-03-19 19:52
I found a solution my issue in specific!

I was in the process of upgrading to 13.2 and previously I used dynamic OG images via `@vercel/og` under the "old" `pages/api` folder. 

It seems like having the existence of a route in `pages/api` caused my route to not resolve `not-found.tsx`. Very weird!

**Comment by karlhorky** [comment] 2023-03-29 15:58
Since this issue title is pretty general and other people may come her looking for this other issue with `not-found.tsx` and `metadata` / `generateMetadata`, here's a link to a similar-sounding issue:

- https://github.com/vercel/next.js/issues/45620

**Comment by shuding** [comment] 2023-05-03 13:15
Closing this one as we are tracking it in #45620.

**Closed by shuding** 2023-05-03 13:15 UTC
Labels: template: bug
