### ISSUE TITLE
External redirects not working when using i18n domain routing

### ISSUE THREAD

**Issue by glenngijsberts** [vercel/next.js#27405] opened 2021-07-22 16:35 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

15.3.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Other

### Describe the Bug

Since a while we're using the native[ i18n routing](https://nextjs.org/docs/advanced-features/i18n-routing). After a while we figured out that our external [redirects](https://nextjs.org/docs/api-reference/next.config.js/redirects) are not working anymore. Example: https://ticketswap.com/jobs is now redirecting to `https://www.ticketswap.comhttps//jobs.ticketswap.com`. Figured out that this is happening when defining domains in the i18n setup (since we're using domain routing).

### Expected Behavior

External redirects should redirect without looking at the domain. See reproduce section for more info.

### To Reproduce

When using the following config (with your own domains) in your (fresh) Next.js project you'll see that when you navigate to `/jobs` you'll end up at `yourfulldomain.comhttps//jobs.ticketswap.com`.

```js
module.exports = {
  i18n: {
    locales: ["en"],
    defaultLocale: "en",
    domains: [
      { domain: "com.glenn.ticketswap.pizza", defaultLocale: "en" },
      { domain: "nl.glenn.ticketswap.pizza", defaultLocale: "nl" },
    ],
    localeDetection: false,
  },
  async redirects() {
    return [
      {
        source: "/jobs",
        destination: "https://jobs.ticketswap.com",
        basePath: false,
        permanent: false,
      },
    ];
  },
};
```

**Comment by ijjk** [comment] 2021-07-22 17:51
Hi, thanks for the detailed reproduction, I opened a fix for this [here](https://github.com/vercel/next.js/pull/27415) to address this! In the meantime `locale: false` can be used to prevent the locale domain from being added to the external redirect for example: 

```js
{
  source: `/(${i18n.locales.join('|')})/jobs`,
  destination: 'https://example.com'
  locale: false,
  permanent: false
}
```

**Closed** 2021-07-22 18:32 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-28 02:15
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
