### ISSUE TITLE
Preview mode breaking datocms-next-js-blog-demo

### ISSUE THREAD

**Issue by jahlherapath** [vercel/next.js#15147] opened 2020-07-14 06:09 UTC
# Bug report

## Describe the bug

Unhandled Runtime Error
Error: Failed to load static props

When navigating to blog post routes the following error is shown:

<img width="1070" alt="Error" src="https://user-images.githubusercontent.com/12905638/87390048-5a3aa280-c5eb-11ea-912e-010be3638e9c.png">

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Setup repo as per readme
2. Navigate to blog post eg. http://localhost:3000/posts/mistakes-tourists-make-on-their-first-trip-abroad

## Expected behavior

Show blog page without error

## System information

- OS: macOS
- Version of Next.js: 9.4.4
- Version of Node.js: 12.18.1

## Additional context

If I comment out `preview` here it fixes the issue but can't use Preview Mode:

```
export async function getStaticProps({ params, preview }) {
  const data = await getPostAndMorePosts(params.slug, preview);
  const content = await markdownToHtml(data?.post?.content || "");

  return {
    props: {
      // preview,
      post: {
        ...data?.post,
        content,
      },
      morePosts: data?.morePosts,
    },
  };
}
```

**Comment by rokinsky** [comment] 2020-07-14 09:54
@jahlherapath, use the default null value:
```js
export async function getStaticProps({ params, preview = null }) {
  // ...
}
```

**Comment by Timer** [comment] 2020-07-14 16:52
Closing as we confirmed the latest version of this example correctly sets the default `preview` value. Please ensure you have the latest version of the template.

![image](https://user-images.githubusercontent.com/616428/87453678-dd9aca80-c5d0-11ea-934c-2f2c3186aae4.png)

**Closed by Timer** 2020-07-14 16:52 UTC
Labels: good first issue, kind: bug

**Comment by rokinsky** [comment] 2020-07-14 16:59
@Timer btw, it is possible to add in the future a default value (`null` or `false`) of `preview` in the next.js core?

**Comment by balazsorban44** [comment] 2022-01-29 22:05
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
