### ISSUE TITLE
graphql-tools throws error "Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by pck886** [vercel/next.js#26987] opened 2021-07-07 14:19 UTC
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

import { gql } from "apollo-server";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /Users/chanlee/Documents/flyers/haimtree-dev/node_modules/@graphql-tools/load-files/index.cjs.js:126:33
    at Array.map (<anonymous>)

- getting an error from readFileSync in fs module inside graphql-tools.

### Expected Behavior

No error should be thrown and request should be successfully made.

### To Reproduce
*Works in the api folder

**schema.js**
import { loadFilesSync, mergeResolvers, mergeTypeDefs } from "graphql-tools";

const loadedTypes = loadFilesSync(`${__dirname}/**/*.typeDefs.js`);
const loadedResolvers = loadFilesSync(`${__dirname}/**/*.resolvers.js`);

export const typeDefs = mergeTypeDefs(loadedTypes);
export const resolvers = mergeResolvers(loadedResolvers);

**server.js**
import { ApolloServer } from "apollo-server-micro";
import { typeDefs, resolvers } from "../../lib/schema";

require("dotenv").config();

const apollo = new ApolloServer({
  resolvers,
  typeDefs,
});

export default apollo.createHandler({ path: "/api/graphql" });

export const config = {
  api: {
    bodyParser: false,
  },
};

[test-dev.zip](https://github.com/vercel/next.js/files/6799156/test-dev.zip)

**Comment by timneutkens** [comment] 2021-07-09 09:05
Please share a full reproduction

**Comment by pck886** [comment] 2021-07-12 06:51
@timneutkens  add project files thank you!

**Comment by sachinraja** [comment] 2021-07-14 13:36
@pck886
> server.js doesn't go through babel or webpack. Make sure the syntax and sources this file requires are compatible with the current node version you are running.

[reference](https://nextjs.org/docs/advanced-features/custom-server)

**Comment by timneutkens** [comment] 2021-11-17 15:45
This is probably fixed by esmExternals becoming the default in Next.js 12.

**Closed by timneutkens** 2021-11-17 15:45 UTC
Labels: please add a complete reproduction

**Comment by balazsorban44** [comment] 2022-01-27 08:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
