### ISSUE TITLE
Bad module not found error from webpack

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#14711] opened 2020-06-30 04:51 UTC
# Bug report

## Describe the bug

![image](https://user-images.githubusercontent.com/616428/86084798-c2c24500-ba6b-11ea-9a76-005a1dd981f3.png)

## To Reproduce

```tsx
import a from “b”;
```

## Expected behavior

A more clear message that says you're trying to import `b` and that's the problem. This message alludes to `a` being the problem.

---

Useful flag: 

![image](https://user-images.githubusercontent.com/616428/87306475-114cf600-c4e6-11ea-907c-9f181f873b7d.png)

**Comment by darshkpatel** [comment] 2020-06-30 11:19
I'll take this up

**Comment by sambarrowclough** [comment] 2020-07-11 12:11
Hi. Is okay if I tackle this?

**Comment by Timer** [comment] 2020-07-13 12:51
Sure!

**Comment by sambarrowclough** [comment] 2020-07-14 18:02
What do you think about this?

![image](https://user-images.githubusercontent.com/4313694/87459058-c7a5fd80-c602-11ea-9935-108892b073e9.png)

The annoying bit would be that the `/packages` dir will be included in the module trace, giving it some extra fluff. I could blindly replace all lines that contain `packages` but it doesn't seem like a good idea in case someone uses this structure :/

The tips are just some common scenarios I came across on StackOverflow that could be useful for troubleshooting
- case-sensitive:  https://stackoverflow.com/a/45968534
- typos: https://stackoverflow.com/a/41322914
- path: https://stackoverflow.com/a/46664426

**Closed** 2020-08-05 19:11 UTC
Labels: kind: bug, point: 3

**Comment by balazsorban44** [comment] 2022-01-29 18:07
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
