### ISSUE TITLE
Default Browser not open while debugging started

### ISSUE THREAD

**Issue by Sandeep0695** [vercel/next.js#18890] opened 2020-11-06 11:56 UTC
Default browser should be open automatically when we debug using next dev command from visual studio code.
Previously I am using create-react-app in which I am found that feature but with next.js not open the default browser .

**Comment by jamesmosier** [comment] 2020-11-07 04:15
Duplicate of https://github.com/vercel/next.js/issues/12233

**Closed by jamesmosier** 2020-11-07 04:15 UTC
Labels: template: bug

**Comment by balazsorban44** [comment] 2022-01-29 06:06
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
